### ISSUE TITLE
这个不支持看youtube吗？

### ISSUE THREAD

**Issue by luieswww** [XX-net/XX-Net#1]
大神楼主。

PS.这个软件的名字需要改一下。

**Comment by luieswww** [comment]
good job,配置友好了许多，不过期待能很快可以看视频。
好多appid啊！。。

**Comment by xxnet** [comment]
名字，有什么好建议吗？

**Comment by xxnet** [comment]
怀疑是Windows版本的Chrome对Youtube进行了特殊处理，Linux的Chrome就可以看看，是浏览器的问题。
具体解决需要再研究啊。

**Comment by luieswww** [comment]
​望解决chrome的问题哦​

2015-01-17 11:37 GMT+08:00 xxnet <notifications@github.com>:

> 怀疑是Windows版本的Chrome对Youtube进行了特殊处理，Linux的Chrome就可以看看，是浏览器的问题。
> 具体解决需要再研究啊。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1#issuecomment-70352976>.
>



--

**Comment by xxnet** [comment]
奇怪的是，今天下午测试Youtube，一切都正常了。
  你试试能不能看Youtube.

**Comment by xxnet** [comment]
测试正常了，关闭bug

**Comment by EvanWilliam** [comment]
求助：XX-Net3.26无法连接YouTube.
