### ISSUE TITLE
youtube视频看不了？

### ISSUE THREAD

**Issue by cottonty** [XX-net/XX-Net#10]
永远是 出现错误，请稍后重试。。。

**Comment by xxnet** [comment]
请部署自己的appid，公共appid流量太大了，关闭了对Youtube的代理。

**Comment by cottonty** [comment]
已经部署了，手动在proxy.ini改了，还是不行。。

**Comment by xxnet** [comment]
试试最新版本，1.0.4
我这边可以播放。

**Comment by gjbg1989** [comment]
😱如何为 Windows 10 UWP 应用设置代理 - https://zhuanlan.zhihu.com/p/29989157
