### ISSUE TITLE
专门拜谢

### ISSUE THREAD

**Issue by lele2010lele** [XX-net/XX-Net#100]
感谢xx－net啦，网速飞快，感谢你的付出，历史会给你该有的荣耀。

**Comment by xxnet** [comment]
感谢支持。
如果有时间，可以帮忙宣传、帮忙测试新版、提建议意见。

在 2015年4月1日 下午11:43，lele2010lele <notifications@github.com>写道：

**Comment by fhzyfjy** [comment]
感激之情确实无以言表啊。如果用自己的ID可以看视频就更好了。谢谢

**Comment by xxnet** [comment]
用自己id可以看youtube，
niconico需要SwitchSharp 导入配置，然后启用自动模式。
xvideo还不能看

在 2015年4月2日 上午7:29，fhzyfjy <notifications@github.com>写道：

**Comment by lele2010lele** [comment]
请问现在1.7的更新主要是哪些方面？

**Comment by lele2010lele** [comment]
Apr 3 09:31:30 - [DEBUG] get ip:203.165.14.227 t:202
Apr 3 09:31:30 - [ERROR] GAEProxyHandler.do_METHOD_AGENT send to browser 'https://r6---sn-vgqsenek.googlevideo.com/videoplayback?sver=3&clen=172776025&source=youtube&upn=0lbcWllNyyQ&lmt=1426206629163884&ms=au&id=o-AL2SzfxYwrrzGcA4BR8d40CbEMOcNEIQHmcVNkmRduik&pl=27&mv=m&mt=1428024596&signature=A5B205C82EAD14B77F2CAC3922C0521E37C86DB1.AD785B492FD98A1EC77B879C50C222BDBBDC4AB4&keepalive=yes&key=yt5&ip=107.178.200.168&mm=31&fexp=900720%2C907263%2C916614%2C930817%2C934954%2C936118%2C9407712%2C9407791%2C9408101%2C945097%2C948124%2C948703%2C951703%2C952612%2C957201%2C961404%2C961406%2C964741%2C966201&dur=2813.933&ipbits=0&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&gir=yes&expire=1428046263&mime=video%2Fmp4&itag=134&cpn=iII0WipI97Bz1I0j&alr=yes&ratebypass=yes&c=web&cver=html5&range=17136993-17651875' return error(32, 'Broken pipe')
Apr 3 09:31:30 - [ERROR] Except stack:Traceback (most recent call last):
File "/Users/apple/Downloads/XX-Net-1.6.0/XX-Net-1.6.0/goagent/3.1.43/local/proxy_handler.py", line 551, in do_AGENT
ret = self.wfile.write(data)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 324, in write
self.flush()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 303, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 229, in sendall
v = self.send(data[count:])
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 198, in send
v = self._sslobj.write(data)
error: [Errno 32] Broken pipe

**Comment by Softor** [comment]
在此感谢！自从使用 xx-net 感觉很稳定，更专注于自己要做的事儿了！

**Comment by hyskyder** [comment]
在此感谢作者的付出！

**Comment by xxnet** [comment]
回复lele的日志，是浏览器关闭了，断开了链接，不属于问题。
新版本去掉了这个日志。

在 2015年4月4日 上午4:52，笃行 <notifications@github.com>写道：

**Comment by cenruibitch** [comment]
太感谢开发人员了，帮我抢到了梦想的whv名额，万分感谢，也感谢能让我在自由世界任意穿梭。。。哈哈哈

**Comment by Iensgh** [comment]
Thank you for Google goagent(XX-net)! 感谢谷歌公司帮助我朋友顺利注册移民信息，，，愿自由充满整个世界！
