### ISSUE TITLE
新买的surface pro，运行start.vbs时报错

### ISSUE THREAD

**Issue by rainman-pilot** [XX-net/XX-Net#10004]
* 简单描述遇到的问题：
运行start.bat或start.vbs时报错，在data/launcher文件夹里有error和launcher两个文件，显示：
Mar 14 12:12:32.188 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x04CAD990>
Mar 14 12:13:45.910 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x0596C1C0>
Mar 14 12:13:54.611 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x0495C1C0>
Mar 14 12:13:57.631 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x047EC1C0>
Mar 14 12:33:12.247 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x057D3198>
Mar 14 12:36:57.782 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x052941C0>
Mar 14 12:37:04.444 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x05625148>
Mar 14 13:03:42.862 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x04AA41C0>
Mar 14 13:25:17.325 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x04DB41C0>
Mar 14 13:31:23.050 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x04C63198>
Mar 14 13:31:46.080 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x04B841C0>

* 做过哪些尝试：
对surface pro系统不熟悉，虽然时WIN 10 HOME版本，但跟我另一个笔记本的WIN 10专业版不一样。
尝试了安装.NET FRAMEWORK 3.5，重启后还是报错。请指教

**Comment by winters-z** [comment]
我的经验是直接把能用的那个文件夹直接复制过去就行了，连设置都省了

**Comment by rainman-pilot** [comment]
老PC上的文件夹有好几百兆，拷不得。

**Comment by rainman-pilot** [comment]
请教在surface pro上搞定过的大侠，请帮忙。

**Comment by gjbg1989** [comment]
老PC上的文件夹有好几百兆——Smart-Router 内清楚“缓存”，结束进程pythonw.exe，code 下只要整运行的版本及 version.txt ？data 下删除 scan_ip*.log launcher.log 。。。

**Comment by gjbg1989** [comment]
😂一个版本：40-50M

**Comment by winters-z** [comment]
我用的就是 surface，你更新了没有删除旧文件，所以几百兆，我保留了最近三个版本，只有一百多M

**Comment by winters-z** [comment]
直接复制我试过可用

**Comment by rainman-pilot** [comment]
无论是双击还是命令行运行start.vbs，都没有啥显示，就是报错Mar 14 13:31:46.080 - [ERROR] uncaught Exception, type=<type 'exceptions.WindowsError'> value=[Error 5] Access is denied traceback:<traceback object at 0x04B841C0>

**Comment by xxnet** [comment]
搜素到这个：
https://stackoverflow.com/questions/32167418/python-pip-install-trouble-shooting-permissionerror-winerror-5-access-is

建议是：
已管理员权限执行

**Comment by rainman-pilot** [comment]
直接复制过来，启动start.vbs，立马好用，啥也不用额外设置，搞定！
多谢winters-z

**Comment by xxnet** [comment]
​那么这个问题就是在启动时，需要某些初始化的工作抛了一个超级异常，直接退出，连异常日志也没有显示好
