### ISSUE TITLE
X-TUNNEL经常不行，TLS-Relay好像一直用不了

### ISSUE THREAD

**Issue by waitingHao** [XX-net/XX-Net#10014]
### TLS-Relay是做什么的？怎么从来都没正常过。

* 另外，因为经常用不了，流量还有很多用不完，有没有需要的？

# 日志

Mar 15 11:46:30.460 - [INFO] xxnet_version:3.10.4

Mar 15 11:46:30.460 - [INFO] server 127.0.0.1:1080 started.

Mar 15 11:46:30.460 - [INFO] Socks5 server listen:127.0.0.1:1080.

Mar 15 11:46:43.792 - [DEBUG] session not running, try login..

Mar 15 11:46:45.071 - [INFO] api:/login success t:1279

Mar 15 11:46:45.071 - [INFO] update xt_server v13.xx-net.net:443

Mar 15 11:46:45.071 - [INFO] request_balance host:v13.xx-net.net port:443 balance:0.000000 quota:297103887828.000000

Mar 15 11:46:45.071 - [INFO] session timeout, reset it.

Mar 15 11:46:45.418 - [DEBUG] x_tunnel force update info

Mar 15 11:46:45.704 - [INFO] api:/login success t:282

Mar 15 11:46:45.704 - [INFO] request_balance host:v13.xx-net.net port:443 balance:0.000000 quota:297103887828.000000

Mar 15 11:46:55.081 - [WARNING] login session fail, status:602

Mar 15 11:47:05.087 - [WARNING] login session fail, status:602

Mar 15 11:47:15.094 - [WARNING] login session fail, status:602

Mar 15 11:47:25.103 - [WARNING] login session fail, status:602

Mar 15 11:47:35.112 - [WARNING] login session fail, status:602

Mar 15 11:47:45.119 - [WARNING] login session fail, status:602

Mar 15 11:47:55.127 - [WARNING] login session fail, status:602

Mar 15 11:48:05.135 - [WARNING] login session fail, status:602

Mar 15 11:48:15.144 - [WARNING] login session fail, status:602

Mar 15 11:48:25.152 - [WARNING] login session fail, status:602

Mar 15 11:48:35.158 - [WARNING] login session fail, status:602

Mar 15 11:48:45.167 - [WARNING] login session fail, status:602

# Cloudflare前端 日志

Mar 15 11:46:30.396 - [INFO] SSL use version:TLSv1_2

Mar 15 11:46:30.397 - [INFO] OpenSSL support alpn

Mar 15 11:46:30.397 - [INFO] load ip range file:Z:\Program\XX-Net-3.1.19\code\3.10.4\x_tunnel\local\cloudflare_front\ip_range.txt

Mar 15 11:46:30.399 - [INFO] load ip_list num:100, target num:100

Mar 15 11:46:31.914 - [INFO] updated cloudflare front domains from github.

Mar 15 11:46:49.862 - [DEBUG] connect 104.28.100.89 fail:error("conn fail, sni:familychiropracticwny.com, top:movistar.gq e:timeout('timed out',)",)

Mar 15 11:46:49.862 - [DEBUG] report_connect_fail:104.28.100.89

Mar 15 11:46:56.864 - [DEBUG] connect 104.24.179.142 fail:error("conn fail, sni:buyvindictus.com, top:book-mark.ml e:timeout('timed out',)",)

Mar 15 11:46:56.864 - [DEBUG] report_connect_fail:104.24.179.142

Mar 15 11:47:03.866 - [DEBUG] connect 104.28.9.244 fail:error("conn fail, sni:charmforever.fr, top:sawfish.tk e:timeout('timed out',)",)

Mar 15 11:47:03.866 - [DEBUG] report_connect_fail:104.28.9.244

Mar 15 11:47:10.868 - [DEBUG] connect 198.41.221.229 fail:error("conn fail, sni:domainslittle.top, top:book-mark.ml e:timeout('timed out',)",)

Mar 15 11:47:10.868 - [DEBUG] report_connect_fail:198.41.221.229

Mar 15 11:47:18.235 - [DEBUG] create_ssl update ip:104.31.212.74 time:5357 h2:1 sni:marceloarmesto.com, host:sawfish.tk

Mar 15 11:47:24.502 - [DEBUG] create_ssl update ip:104.24.96.173 time:5266 h2:1 sni:marceloarmesto.com.br, host:sawfish.tk

Mar 15 11:47:28.388 - [DEBUG] http2 104.31.212.74 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:28.389 - [DEBUG] 104.31.212.74 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Mar 15 11:47:28.389 - [DEBUG] 104.31.212.74 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:28.389 - [DEBUG] 104.31.212.74 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:47:28.389 - [DEBUG] 104.31.212.74 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:28.390 - [DEBUG] 104.31.212.74 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:47:30.904 - [DEBUG] create_ssl update ip:141.101.114.208 time:5382 h2:1 sni:que-huong-bistro.de, host:book-mark.ml

Mar 15 11:47:34.546 - [DEBUG] http2 104.24.96.173 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:34.546 - [DEBUG] 104.24.96.173 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Mar 15 11:47:34.547 - [DEBUG] 104.24.96.173 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:34.547 - [DEBUG] 104.24.96.173 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:47:34.547 - [DEBUG] 104.24.96.173 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:34.547 - [DEBUG] 104.24.96.173 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:47:36.906 - [DEBUG] connect 104.31.212.74 fail:error("conn fail, sni:marceloarmesto.com.br, top:sawfish.tk e:timeout('timed out',)",)

Mar 15 11:47:36.906 - [DEBUG] report_connect_fail:104.31.212.74

Mar 15 11:47:41.037 - [DEBUG] http2 141.101.114.208 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:41.038 - [DEBUG] 141.101.114.208 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Mar 15 11:47:41.038 - [DEBUG] 141.101.114.208 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:41.038 - [DEBUG] 141.101.114.208 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:47:41.038 - [DEBUG] 141.101.114.208 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:47:41.039 - [DEBUG] 141.101.114.208 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:47:43.910 - [DEBUG] connect 104.24.96.173 fail:error("conn fail, sni:aromajane.com, top:mostlygood.ga e:timeout('timed out',)",)

Mar 15 11:47:43.910 - [DEBUG] report_connect_fail:104.24.96.173

Mar 15 11:47:50.912 - [DEBUG] connect 141.101.114.208 fail:error("conn fail, sni:dropping.global, top:singlefly.tk e:timeout('timed out',)",)

Mar 15 11:47:50.912 - [DEBUG] report_connect_fail:141.101.114.208

Mar 15 11:47:57.913 - [DEBUG] connect 104.31.212.74 fail:error("conn fail, sni:101waystoearnmoneyonline.com, top:superx.gq e:timeout('timed out',)",)

Mar 15 11:47:57.913 - [DEBUG] report_connect_fail:104.31.212.74

Mar 15 11:48:04.916 - [DEBUG] connect 104.24.96.173 fail:error("conn fail, sni:cl8ud.com, top:movistar.gq e:timeout('timed out',)",)

Mar 15 11:48:04.916 - [DEBUG] report_connect_fail:104.24.96.173

Mar 15 11:48:12.210 - [DEBUG] create_ssl update ip:141.101.114.208 time:5284 h2:1 sni:enteha.net, host:gotoworld.tk

Mar 15 11:48:18.212 - [DEBUG] connect 104.31.212.74 fail:error("conn fail, sni:egoshop.ml, top:sawfish.tk e:timeout('timed out',)",)

Mar 15 11:48:18.212 - [DEBUG] report_connect_fail:104.31.212.74

Mar 15 11:48:22.261 - [DEBUG] 141.101.114.208 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Mar 15 11:48:22.261 - [DEBUG] http2 141.101.114.208 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:48:22.261 - [DEBUG] 141.101.114.208 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:48:22.261 - [DEBUG] 141.101.114.208 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:48:22.261 - [DEBUG] 141.101.114.208 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 15 11:48:22.261 - [DEBUG] 141.101.114.208 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Mar 15 11:48:25.214 - [DEBUG] connect 104.24.96.173 fail:error("conn fail, sni:drafabianamello.com, top:flar.tk e:timeout('timed out',)",)

Mar 15 11:48:25.214 - [DEBUG] report_connect_fail:104.24.96.173

Mar 15 11:48:32.216 - [DEBUG] connect 141.101.114.208 fail:error("conn fail, sni:cl8ud.com, top:movistar.gq e:timeout('timed out',)",)

Mar 15 11:48:32.216 - [DEBUG] report_connect_fail:141.101.114.208

Mar 15 11:48:39.218 - [DEBUG] connect 104.31.212.74 fail:error("conn fail, sni:bmovietees.cf, top:c-term.tk e:timeout('timed out',)",)

Mar 15 11:48:39.218 - [DEBUG] report_connect_fail:104.31.212.74

Mar 15 11:48:46.220 - [DEBUG] connect 104.24.96.173 fail:error("conn fail, sni:trhaberdetay.xyz, top:gotoworld.tk e:timeout('timed out',)",)

Mar 15 11:48:46.220 - [DEBUG] report_connect_fail:104.24.96.173

Mar 15 11:48:53.223 - [DEBUG] connect 141.101.114.208 fail:error("conn fail, sni:construyehogar.com, top:superx.gq e:timeout('timed out',)",)

Mar 15 11:48:53.223 - [DEBUG] report_connect_fail:141.101.114.208

Mar 15 11:49:00.227 - [DEBUG] connect 104.31.212.74 fail:error("conn fail, sni:buyvindictus.com, top:book-mark.ml e:timeout('timed out',)",)

Mar 15 11:49:00.227 - [DEBUG] report_connect_fail:104.31.212.74

# TLS-Relay前端 日志

Mar 15 11:46:30.422 - [INFO] SSL use version:TLSv1_2

Mar 15 11:46:30.422 - [INFO] OpenSSL support alpn

Mar 15 11:46:30.423 - [INFO] load ip_list num:1, target num:1

Mar 15 11:46:43.864 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:46:43.865 - [DEBUG] report_connect_fail network fail

Mar 15 11:46:48.876 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:46:48.876 - [DEBUG] report_connect_fail network fail

Mar 15 11:46:53.881 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:46:53.882 - [DEBUG] report_connect_fail network fail

Mar 15 11:46:58.895 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:46:58.895 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:03.898 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:03.898 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:08.912 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:08.912 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:13.917 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:13.917 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:18.923 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:18.923 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:23.927 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:23.927 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:28.941 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:28.941 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:33.946 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:33.947 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:38.951 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:38.951 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:43.847 - [DEBUG] create ssl timeout fail.

Mar 15 11:47:44.130 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:44.130 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:49.144 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:49.144 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:54.148 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:54.149 - [DEBUG] report_connect_fail network fail

Mar 15 11:47:59.153 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:47:59.153 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:04.157 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:04.158 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:09.163 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:09.163 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:14.167 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:14.167 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:19.179 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:19.179 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:24.193 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:24.193 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:29.197 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:29.197 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:34.200 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:34.200 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:39.205 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:39.205 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:44.134 - [DEBUG] create ssl timeout fail.

Mar 15 11:48:44.211 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:44.212 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:49.214 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:49.214 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:54.219 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:54.219 - [DEBUG] report_connect_fail network fail

Mar 15 11:48:59.225 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:48:59.225 - [DEBUG] report_connect_fail network fail

Mar 15 11:49:04.229 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:49:04.229 - [DEBUG] report_connect_fail network fail

Mar 15 11:49:09.235 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:49:09.236 - [DEBUG] report_connect_fail network fail

Mar 15 11:49:14.238 - [DEBUG] connect 2001:19f0:6801:bd9:5400:1ff:fe62:e02d fail:error("conn fail, sni:guard-database.com, top: e:error(10065, '')",)

Mar 15 11:49:14.238 - [DEBUG] report_connect_fail network fail

**Comment by gjbg1989** [comment]
X-Tunnel 登录不正常，貌似由于先前正常登录后 XX-Net 证书（时间）发生了变化引发。
试试：
1、保证 IPv6 隧道及 GAE 代理正常，有 X-Tunnel 账户及密码；
2、结束进程 pythonw.exe，更名 data 下的 x_tunnel 目录以备份；
3、启动 XX-Net 并以 GAE 全局或自动切换代理模式，待 GAE 工作正常后再次登录以生成与当前 XX-Net 证书配套的 x_tunnel\client.json 等文件。
😱你：保证 IPv6 隧道及 GAE 代理正常即可？

**Comment by waitingHao** [comment]
我这边IPv6经常不行，开不了，x-tunnel就算登录正常也经常用不了。

**Comment by gjbg1989** [comment]
GAE 正常，x-tunnel 正常
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by waitingHao** [comment]
就是我常用的网络下不行，其他网络一直用着很正常。🤢

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9940#issuecomment-373263710 人云：这个版本在家、在公司都能用；后来的有了智能路由的在家用不了。

**Comment by xxnet** [comment]
​

请测试新版本：

https://github.com/XX-net/XX-Net/issues/10025

**Comment by waitingHao** [comment]
更新后目前可以用了。
