### ISSUE TITLE
大神 给个指示

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#10034]
![hov lqjago8g6n sml 3 i](https://user-images.githubusercontent.com/10782704/37503590-46451b0a-2914-11e8-9859-47dcf9d4c22b.jpg)

**Comment by xiaoteai** [comment]
![z8k 14yq sq1ozqkdekg 7k](https://user-images.githubusercontent.com/10782704/37504148-75fa26b2-2917-11e8-8c15-1ec75986da55.jpg)
没反应

**Comment by xiaoteai** [comment]
![rrgm0p3 dvs hm or s 3 0](https://user-images.githubusercontent.com/10782704/37504378-e668e842-2918-11e8-8da0-b8f4c23aac70.jpg)

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/37504615-843be1ea-291a-11e8-8670-cad0496438f9.png)
😱是谁在玩你？全角句号或缺少字符。。。
 teredo.iks-jena.de.

**Comment by xiaoteai** [comment]
为什么 复制你的  服务器 还是 出现 贴图 的 全角句号并缺少连字符。。。

![](https://user-images.githubusercontent.com/13290970/37504615-843be1ea-291a-11e8-8670-cad0496438f9.png)

**Comment by AnyWAT** [comment]
🤣你的电脑不是由你操控，被神。。。
结束进程 pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行
netsh int ipv6 set teredo enterpriseclient teredo.iks-jena.de.

**Comment by xiaoteai** [comment]
水军   也太厉害了  还是 码农 有才
