### ISSUE TITLE
为什么100th IP handshake(ms)在不停变大？

### ISSUE THREAD

**Issue by tinyperson** [XX-net/XX-Net#1003]
一开始是240，
一分钟前：
![image](https://cloud.githubusercontent.com/assets/14156036/9836474/50944154-5a4e-11e5-867e-010acb394faf.png)
现在：
![image](https://cloud.githubusercontent.com/assets/14156036/9836484/bef79c54-5a4e-11e5-815d-92dfb8dd17c2.png)
![image](https://cloud.githubusercontent.com/assets/14156036/9836803/913dcbca-5a59-11e5-868d-a9e89fefc5d9.png)

Google IP number会变小吗？

**Comment by xiuluo** [comment]
Property	Value
Google IP num	2998
100th IP handshake(ms)	6208
connected link(帮助)	5,8

**Comment by zhanxiage233** [comment]
你的xxnet是什么版本？

**Comment by tinyperson** [comment]
2.4.0

**Comment by luyang93** [comment]
突然不敢换2.4.0了，我还停留在2.0.5的版本。

**Comment by tinyperson** [comment]
@xiuluo 
我的超过你的六分之一了。
![image](https://cloud.githubusercontent.com/assets/14156036/9839242/e463637c-5aa5-11e5-873b-d71a1324e863.png)

**Comment by rarest** [comment]
没见过世面，看看我这个，你们都不及我的零头
![qq 20150914103058](https://cloud.githubusercontent.com/assets/962449/9840958/0f11769c-5acc-11e5-8fda-e345843c9909.png)

**Comment by xxnet** [comment]
这个机制该改了，现在只要有10个可用ip就可以工作了，要把 100th 改成10th比较合理，谁会帮忙改改？

2015-09-14 10:34 GMT+08:00 rarest <notifications@github.com>:

**Comment by rarest** [comment]
那个文件里改的？

**Comment by xxnet** [comment]
有几个地方，你从web界面上开始查
 gae_proxy/web_ui/下开始查，python部分是gae_proxy/local/web_control.py

2015-09-14 10:51 GMT+08:00 rarest <notifications@github.com>:

**Comment by yangsl158** [comment]
我的貌似一直是-1。
![1](https://cloud.githubusercontent.com/assets/6550682/9841897/f77ed6b6-5ad8-11e5-835d-4ee49afb15e5.jpg)

**Comment by tinyperson** [comment]
@yangsl158 
你好厉害啊！

**Comment by kennir** [comment]
谁敢比我高


Property	Value
Google IP num	2991
100th IP handshake(ms)	25096
connected link(帮助)	11,48
scaning ip thread num	50
block stat(帮助)	OK


- -#
