### ISSUE TITLE
大佬们，以前配置过的appid，今天发现用不了，为什么呢

### ISSUE THREAD

**Issue by andychanha** [XX-net/XX-Net#10032]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5916 ipv4:36 ipv6:2475
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: -5
ip-quality: 329
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=config 。。。保存

**Comment by gjbg1989** [comment]
Using_Public_Appid: false——私有 appid 工作
ipv6-status: Fail——以前配置过的appid，今天发现用不了——貌似说法不对，是 ipv6 异常
最近异动大且快，IP 延迟一直只增不减，一定时间后几乎工作不正常
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP ——开始，稍侯 IPv6 IP 数及延时均减小。。。
故：
改小 max_good_ip_num 500-1000 （便于手动检查 IP）
增大 max_scan_ip_thread_num 50-100
并 force_ipv6
程序默认值分别为：3000、10、auto
😱嫌 IP 延迟数字大？检查 IP ——开始
#9873 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by gjbg1989** [comment]
😱scan-ip-thread-num: -5 😱

**Comment by andychanha** [comment]
@_@  先谢谢，以前的老爷机略渣，设扫描线程为5了，也没发现会变成负数呀……
现在试着改成100了，不过不清楚max_good_ip_num是在哪里修改的
现在正在慢慢检查IP中，目前还是连接尚未建立状态

**Comment by gjbg1989** [comment]
max_good_ip_num是在哪里修改—— https://github.com/XX-net/XX-Net/issues/9920

**Comment by andychanha** [comment]
谢谢啦，在大佬帮助下，现在基本上能正常使用了。
不过，遇到一个有点尴尬的问题，有时候google要验证人机嘛，结果图片加载不出来……

**Comment by gjbg1989** [comment]
鄙人的正常，不行用 X-Tunnel ？

**Comment by andychanha** [comment]
好的，我再次遇到的话试试
