### ISSUE TITLE
无法打开8085配置页面

### ISSUE THREAD

**Issue by wangling12** [XX-net/XX-Net#10046]
ubuntu 16.04
具体信息如下，在3.11.x版本中无法打开配置页面
3.10.4版本一切正常

XX-Net version:default
3月 16 21:59:09.41 [launcher][INFO] use build-in openssl lib
3月 16 21:59:09.41 [launcher][INFO] start XX-Net 3.11.1
3月 16 21:59:09.41 [launcher][DEBUG] start confirm_xxnet_exit
3月 16 21:59:09.41 [launcher][DEBUG] good, xxnet:8085 clear!
3月 16 21:59:09.41 [launcher][DEBUG] finished confirm_xxnet_exit
3月 16 21:59:09.44 [gae_proxy][INFO] SSL use version:TLSv1_2
3月 16 21:59:09.44 [gae_proxy][INFO] OpenSSL support alpn
3月 16 21:59:09.44 [gae_proxy][INFO] load ip range file:/home/****/XX-Net/code/default/gae_proxy/local/ip_range.txt
3月 16 21:59:09.49 [gae_proxy][INFO] load ip_list num:5876, target num:5876
3月 16 21:59:09.50 [gae_proxy][INFO] SSL use version:TLSv1_2
3月 16 21:59:09.50 [gae_proxy][INFO] ------------------------------------------------------
3月 16 21:59:09.50 [gae_proxy][INFO] Python Version     : 2.7.12
3月 16 21:59:09.50 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:16.04; ID:xenial
3月 16 21:59:09.50 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
3月 16 21:59:09.50 [gae_proxy][INFO] Using public APPID
3月 16 21:59:09.50 [gae_proxy][INFO] ------------------------------------------------------

**Comment by xxnet** [comment]
​重新下载解压试试

**Comment by wangling12** [comment]
试过了，这段信息就是重新下载未经过配置的输出，而且终端输出貌似全程未见error，但就是打不开配置页面

**Comment by gjbg1989** [comment]
添加 127.0.0.1 走直连？

**Comment by KnightAtGitHub** [comment]
我也是，连不上

**Comment by gjbg1989** [comment]
😱约2小时测试：强烈建议用回 3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱

**Comment by sysserkl** [comment]
同样问题，3.11.1 打不开 127.0.0.1:8085。
代理正常。

**Comment by wangling12** [comment]
@gjbg1989 我之前试过，3.10.8ip数量远小于3.10.4，估摸着就是因为那行命令的原因？

**Comment by gjbg1989** [comment]
😱贴 config.json （马赛克 appid）。。。但 config.json 文件有错的化，运行不起来，进程 pythonw.exe 会立马自动退出
3.10.8ip数量远小于3.10.4——http://127.0.0.1:8085/?module=gae_proxy&menu=advanced ——检查 IP

**Comment by wangling12** [comment]
3.11.3问题依旧

**Comment by xxnet** [comment]
​用curl 访问看看：
curl -v http://127.0.0.1:8085
看看有没有立即返回内容。

试试不同浏览器访问
