### ISSUE TITLE
发现一个微软的神奇服务，不知道是否可以用来做成代理使用。

### ISSUE THREAD

**Issue by Antecer** [XX-net/XX-Net#10069]
"http://www.microsofttranslator.com/bv.aspx?from=&to=zh-CHS&a=" + 要访问的URL

例如:
http://www.microsofttranslator.com/bv.aspx?from=&to=zh-CHS&a=www.google.com
这样就能访问Google了，速度飞快！

缺点是不能加载该网页需要翻墙的资源文件，估计是因为那些资源文件没有走这个通道。

不知道是否有哪位大能能够把它弄成代理软件使用。

**Comment by Curriculu** [comment]
在早年谷歌没有退出中国的时候谷歌翻译也是可以的，亲测有效（突然感觉自己是一个老人了）。

**Comment by Curriculu** [comment]
实际上访问谷歌走的是微软后台的企业管道，不具备扩展性（不能做成给android studio更新的代理等问题），而且网速一般般

**Comment by GoodSake** [comment]
gae打不开的3xplanet.com/view/318001.html，mstranslator能打开，好强大哦！

**Comment by longwusha** [comment]
@GoodSake 

老哥的回复带我打开了新世界的大门。。。

**Comment by GoodSake** [comment]
@longwusha 微软的译文确实很奇葩。。。

**Comment by willwudk** [comment]
这个网址愣是加载半天没打开。。。

**Comment by vaward** [comment]
@willwudk   前面还是要加 https，不然打不开的 ！

**Comment by gjbg1989** [comment]
@GoodSake  gae打不开的3xplanet.com/view/318001.html，mstranslator能打开，好强大哦！——
![image](https://user-images.githubusercontent.com/13290970/37696757-c5863914-2d13-11e8-96e9-ef28d3c779d2.png)
