### ISSUE TITLE
为什么只要IPV6显示fail 整个网络变得无网速 ？

### ISSUE THREAD

**Issue by lparty** [XX-net/XX-Net#10061]
IPV4是OK  IPV6是fail 整个网络就卡慢无网速，我是路由器 WIN7 用户，按照你们的指南开启IPV6后发生这种情况，哪怕没有在电脑上开启 XX-net,，平时用手机上网也会发生，突然无网速，然后过几分钟又好了

**Comment by gjbg1989** [comment]
没有在电脑上开启 XX-net,，平时用手机上网也会发生，突然无网速，然后过几分钟又好了——😱网络本身问题？
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by lparty** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.11.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1000 ipv4:0 ipv6:810
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:24 h2:1
scan-ip-thread-num: 50
ip-quality: 506
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
xxnet-version: 3.11.1——建议用回3.10.8
use-ipv6: auto 改为只用 ipv6
https://github.com/XX-net/XX-Net/issues/10048

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by lparty** [comment]
有没有办法 ？还原未开启IPV6的状态？

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果，才知。。。

**Comment by lparty** [comment]
netsh int ipv6 show teredo 是哪里？ 找不到

**Comment by gjbg1989** [comment]
Windows CMD 命令提示符窗口😱

**Comment by lparty** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.1.101:61523
外部 NAT 映射    : 113.118.19.89:20499

**Comment by gjbg1989** [comment]
#关闭和卸载Teredo 管理权限运行
netsh interface teredo set state disable

**Comment by lparty** [comment]
谢谢你的帮助 我用Tunnel 就行了

**Comment by goldenfreemanchina** [comment]
最近扫描IP发现IPv4已经出现蜜罐了...所以，尽量不要最近用IPv4了...不过，反正蜜罐也不是最近有的；

╮(╯_╰)╭  ╮(╯_╰)╭  ╮(╯_╰)╭  

@lparty 你的xx貌似就是中了蜜罐...

**Comment by gjbg1989** [comment]
@goldenfreemanchina 中了蜜罐怎么“解救”？
