### ISSUE TITLE
xubuntu 16.04 下 3.11.1 的状态栏图标尺寸不对

### ISSUE THREAD

**Issue by sysserkl** [XX-net/XX-Net#10067]
![xx-net-ico](https://user-images.githubusercontent.com/17306228/37561677-8f4cb192-2a8f-11e8-8909-4f0857b6bd1d.jpeg)

手动修改了 launcher/web_ui/favicon.ico，从128*128，减少到 24*24 ，才正常显示。

3.10.4 没这个问题。

**Comment by goldenfreemanchina** [comment]
这个应该甩锅到ubuntu 的application indicator....早年间就这样了....

**Comment by bhoppi** [comment]
问题可能与AppIndicator和Xfce有关，正在研究。

**Comment by bhoppi** [comment]
试试将这个PR #10125 的文件（仅有一个文件 code/版本/launcher/gtk_tray.py）替换掉现有版本看能否解决问题

**Comment by her999** [comment]
关于 3.11.0 之后的版本在 ubuntu 上面无法运行管理页面，我找到了解决办法，就是用
3.10.8 版本的 code/default/launcher/start.py 文件替换3.11.0版本 之后的相应文件。
ubuntu 上面，使用 pygtk3 ，即 PyGObject ，可能和 XX-Net 使用的 simple_http_server 有冲突，也可能是其他原因。总之是用 pygtk3 出现了问题。把 start.py 替换成 3.10.8 ，依旧使用 pygtk2 ，就能避免问题了。
我用的是 Ubuntu 17.10
