### ISSUE TITLE
下载外网文件视频速度的问题

### ISSUE THREAD

**Issue by asd8299128** [XX-net/XX-Net#10063]
以前3.9.6用IDM下载谷歌网盘满速，还需要限速，不然下着下着连接数用光直接当掉0速，重启模块又恢复，而现在3.11.0只有可怜的十几K，而且下了十几秒IDM直接无响应。

刚试了下发现这情况，我切回3.9.6能正常使用吗？现在全都设置成只通过IPv6了，不知切回老版本会不会有问题。

**Comment by gjbg1989** [comment]
貌似目前3.10.8最好
没问题，最多扫描下

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10048 滚回 3.10.8 "target_handshake_time": 3000 正常😂
此时，正常的 XX-Net 退出后重开，扫描线程自动调整为0、延时慢慢变大后稳定、IP 数稳定，都能正常代理了😄

**Comment by asd8299128** [comment]
@gjbg1989
好，这个先Mark一下，现在3.9.6挺正常网速又快。
