### ISSUE TITLE
这个upm能开着用迅雷下东西吗

### ISSUE THREAD

**Issue by 66cain** [XX-net/XX-Net#10072]
玩游戏应该可以把？说明里好像没写

**Comment by gjbg1989** [comment]
😂谁是 UWP：
如何为 Windows 10 UWP 应用设置代理 - https://zhuanlan.zhihu.com/p/29989157

**Comment by 66cain** [comment]
我是说这个翻墙软件。。。

**Comment by gjbg1989** [comment]
民无禁止皆可行😂
