### ISSUE TITLE
支付后流量没有变化

### ISSUE THREAD

**Issue by lijunW** [XX-net/XX-Net#10077]
看了之前的issue,说等一段时间，已经三天了，应该是不会变了。
Xtunnel账号 1805535658@189.cn
版本：3.11.1
[Transaction details - PayPal.pdf](https://github.com/XX-net/XX-Net/files/1823372/Transaction.details.-.PayPal.pdf)

**Comment by xxnet** [comment]
查到这个交易，是下面这个帐号的：
18055352658@189.cn
