### ISSUE TITLE
证书怎么老是fail

### ISSUE THREAD

**Issue by UnuboreJoe** [XX-net/XX-Net#10075]
老是过一段时间CA证书状态变成fail，其他都是好的。奇怪奇怪

**Comment by gjbg1989** [comment]
貌似速度的锅
😱约2小时测试：强烈建议用回3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱

**Comment by uone0513** [comment]
这阵子状态一直都是双fail，而且状态一直提示请检查浏览器代理设置，但是不影响翻墙使用，好奇怪，反正能翻就行，我也不管那么多了！

**Comment by gjbg1989** [comment]
楼上也许添加 *.deja.com 走 GAE 就🆗

**Comment by mmook** [comment]
@ghost 你说的对！！！！
