### ISSUE TITLE
丢包的问题，高手们有好点的解决办法么？

### ISSUE THREAD

**Issue by gustav183** [XX-net/XX-Net#10074]
用了这几年，XXnet一直给我有丢包率高的印象，尤其是加入IPv6模式以来，各位有什么好办法么？
win10  chrome浏览器。登陆一些海外账号时常常出问题，海淘更是经常出现付款失败钱却划走的现象。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10052 也许有助。。。

**Comment by SeaHOH** [comment]
金融操作请使用更安全可靠的代理。
