### ISSUE TITLE
用xx-net全局代理，访问某个网站，该网站会返回请求者的ip的，我观察了下，返回的ip数量就重复3到4个左右，这是为什么？？

### ISSUE THREAD

**Issue by ronghuaxu** [XX-net/XX-Net#10078]
为什么我配置了1000多个不同google的gae 的appid，但是用xx-net全局代理，访问某个网站，该网站会返回请求者的ip的，我观察了下，返回的ip数量就重复3到4个左右，这是为什么？？

**Comment by 2378** [comment]
appid就像你的银行帐号，但你常去的银行网点也就3、4个
虽然不严谨，将就理解吧

**Comment by 2378** [comment]
appid就像你的银行帐号，但你常去的银行网点也就3、4个
虽然不严谨，将就理解吧

**Comment by ronghuaxu** [comment]
我看了源代码，为什么可以用的work有100多个，但请求的出口ip也就4个左右

**Comment by 2378** [comment]
可用的银行网点更多，但你常去的网点还是那3、4个
还是不严谨～
应该说你汇笔钱去上海，结算的网点就那3’4个，不会是武汉的晚点给你结算。

**Comment by ronghuaxu** [comment]
> def get_worker(self, nowait=False):
>         xlog.info("getw work success all work number is %d",len(self.workers))
>         return self.workers[random.randint(1, len(self.workers))]
>         # while connect_control.keep_running:
>         #     best_rtt = 9999
>         #     best_worker = None
>         #     idle_num = 0
>         #     for worker in self.workers:
>         #         if not worker.accept_task:
>         #             continue
> 
>         #         if worker.version == "1.1":
>         #             idle_num += 1
>         #         else:
>         #             if len(worker.streams) == 0:
>         #                 idle_num += 1
> 
>         #         rtt = worker.get_score()
> 
>         #         if rtt < best_rtt:
>         #             best_rtt = rtt
>         #             best_worker = worker
> 
>         #     if idle_num < 5 or best_rtt > 1000:
>         #         self.triger_create_worker_cv.notify()
> 
>         #     if best_worker or nowait:
>         #         return best_worker
> 
>         #     self.wait_a_worker_cv.wait()

上述返回可用的工作work 我已经修改成为随机返回，替代了原先的返回最高效的work的方法。
但还是无法解决 为什么可以用的work有100多个，但请求的出口ip也就4个左右
