### ISSUE TITLE
3.11.1版本问题

### ISSUE THREAD

**Issue by jaaaar** [XX-net/XX-Net#10079]
升级3.11.1后  不能使用google搜索有时会跳出人机验证(人机验证的图片也加载不出来),有时会600错误
比如我搜索"123" 
600:gae_exception:'600:fetch gae fail' https://www.google.com/search?q=123%E3%80%81&oq=123%E3%80%81&aqs=chrome..69i57l2j69i60l4.868j0j4&sourceid=chrome&ie=UTF-8
但是国外网站都是可以访问的，就是一用google搜索就炸
有没有大神可以给解决一下

**Comment by gjbg1989** [comment]
#10052 有用？
😱约2小时测试：强烈建议用回3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱

**Comment by gustav183** [comment]
趁早降回通知稳定版，不用谢我

**Comment by jaaaar** [comment]
回3.10.8了。。。
