### ISSUE TITLE
请导入浏览器CA证书

### ISSUE THREAD

**Issue by ShixiangWang** [XX-net/XX-Net#10081]
一直弹出这个问题，使用的Windows7 火狐浏览器，我尝试按照链接进行手动导入，没有成功。也尝试过删除证书，用管理员权限自动运行xxnet生成（有弹出已导入GoAgent证书信息），但浏览器还是一直报这个问题。

```
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.11.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:528 ipv4:0 ipv6:509
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:9 h2:11
scan-ip-thread-num: 10
ip-quality: 551
is-idle: 0
proxy_state: OK
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
```

**Comment by gjbg1989** [comment]
试试：运行 certmgr.msc 删除旧的，然后导入新的，再在火狐内导入新的？

**Comment by ShixiangWang** [comment]
谢谢呢。我现在在尝试删除后，直接在浏览器中导入新的证书，重启中。如果先安装证书，在火狐浏览器中导入时会保存，说之前已安装该证书。

发自我的 iPhone

在 2018年3月19日，上午11:15，gjbg1989 <notifications@github.com<mailto:notifications@github.com>> 写道：


试试：运行 certmgr.msc 删除旧的，然后导入新的，再在火狐内导入新的？

―

**Comment by gjbg1989** [comment]
用管理员权限自动运行xxnet生成（有弹出已导入GoAgent证书信息）——说之前已安装该证书，免😂再在火狐内导入新的？

**Comment by ShixiangWang** [comment]
@gjbg1989 谢谢，我试一试。

我刚删除了证书，然后从火狐浏览器导入，但还是“此证书已在此前安装为证书颁发机构”


我刚才还重启过了呀~~ 先试试你的方法吧

**Comment by gjbg1989** [comment]
用管理员权限自动运行xxnet生成（有弹出已导入GoAgent证书信息），但浏览器还是一直报这个问题
在火狐浏览器中导入时会保存，说之前已安装该证书
——貌似系统上新旧冲突，先运行 certmgr.msc 删除旧的、导入新的，再在火狐内删除旧的、导入新的？

**Comment by ShixiangWang** [comment]
@gjbg1989  我也是这样想的，我重新启动，然后确定没有打开xxnet，也没有pythonw.exe在运行，也确定certs目录被删除了，然后也删除了certmgr.msc里面的GoAgent证书，还是一样的问题。 ----尴尬

**Comment by gjbg1989** [comment]
操作有误，2个新的？系统及火狐都导入 data 下那个😂
