### ISSUE TITLE
python脚本占用系统资源，mac高温…

### ISSUE THREAD

**Issue by marxwiggin** [XX-net/XX-Net#10084]
![snip20180319_1](https://user-images.githubusercontent.com/5785306/37578522-7072b952-2b74-11e8-8ec3-d9e803674681.png)
![snip20180319_2](https://user-images.githubusercontent.com/5785306/37578524-710e77c0-2b74-11e8-9448-b2ea8e82cd77.png)
![snip20180319_3](https://user-images.githubusercontent.com/5785306/37578526-715ef47a-2b74-11e8-91f7-916c77b4b268.png)

**Comment by marxwiggin** [comment]
付费的x-tunnel

**Comment by gjbg1989** [comment]
3.10.0/1？试试退回到3.10.8😂参考：#10048

**Comment by marxwiggin** [comment]
@gjbg1989    可以了，666666

**Comment by g8up** [comment]
![xx-net-python](https://user-images.githubusercontent.com/8005686/37587925-a726842a-2b9b-11e8-8db2-1f8e0a2655e9.jpg)
xx-net: v3.10.4

**Comment by gjbg1989** [comment]
xx-net: v3.10.4 
试试：扫描线程 20-50？
manual.ini 添加
[google_ip]
target_handshake_time = 2000
或升级到3.10.8 参考：#10048

**Comment by gjbg1989** [comment]
xx-net: v3.10.4 
目前波动厉害，总IP数6000不好。manual.ini 添加
[google_ip]
max_good_ip_num = 2000
😂足以

**Comment by xxnet** [comment]
​CPU 高的原因，已经找到了，新版解决
