### ISSUE TITLE
如何知道自己在访问某网站时候用的，具体ip是什么

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#10082]
比如我随便打开了一个网站，我想知道我访问这个网站，用的具体代理ip地址是什么。

当然有人肯定会说。你肯定知道自己的代理ip是什么。但是这个不是我需要的答案。因为我配置了多个ip，想知道哪个ip在访问那个网页的时候再起作用。

**Comment by gjbg1989** [comment]
😱网警，然后。。。

**Comment by yuyistar** [comment]
@gjbg1989 啥子网警呀。。。就是ssr里面不是可以添加多个服务器ip吗。我不知道哪个在起作用，主要我懒的删除其中的一个去验证。要不还需要在添加进去。。。。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10078 楼主知道？

**Comment by YHYJ** [comment]
在百度里直接搜索“ip”就可以



发自我的Outlook
在 gjbg1989 <notifications@github.com>，2018年3月19日 下午2:22写道：

#10078<https://github.com/XX-net/XX-Net/issues/10078> 楼主知道？

**Comment by gjbg1989** [comment]
@YHYJ 不明觉厉😂

**Comment by YHYJ** [comment]
百度搜索栏，输入  ip  回车



发自我的Outlook
在 gjbg1989 <notifications@github.com>，2018年3月19日 下午2:45写道：

@YHYJ<https://github.com/yhyj> 不明觉厉😂

**Comment by SeaHOH** [comment]
只能让你访问的服务器告诉你，或者代理软件有日志输出。

**Comment by SwallowData** [comment]
> 比如我随便打开了一个网站，我想知道我访问这个网站，用的具体代理ip地址是什么。
> 
> 当然有人肯定会说。你肯定知道自己的代理ip是什么。但是这个不是我需要的答案。因为我配置了多个ip，想知道哪个ip在访问那个网页的时候再起作用。

请问现在解决了吗
