### ISSUE TITLE
GAE错误老是出现

### ISSUE THREAD

**Issue by Balnea** [XX-net/XX-Net#10083]
v3.11.11

GAE Module老是出现
600:gae_exception:'600:fetch gae fail' https://www.google.com/ncr
请问这个是什么错误？

**Comment by gjbg1989** [comment]
貌似连接池不够的锅，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。也许有用
😱约2小时测试：强烈建议用回3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱

**Comment by Balnea** [comment]
谢谢！
回滚到3.10.8在测试下

**Comment by wushibinbilly** [comment]
@gjbg1989 这个设置到底是什么意思，我加了进去之后确实好了不少啊

**Comment by gjbg1989** [comment]
@wushibinbilly #10048 贴及楼主才有解释权😂

**Comment by Balnea** [comment]
<img width="215" alt="config" src="https://user-images.githubusercontent.com/11453121/37582821-a8d40714-2b89-11e8-8dfe-1115587de25a.PNG">
现在的确好多了。
