### ISSUE TITLE
xxnet里面的heroku如何使用？能换成自己的appid吗？

### ISSUE THREAD

**Issue by yhage** [XX-net/XX-Net#10085]
* 刚才试了一下X-Tunnel里面的heroku，

属性 | 值
-- | --
Score | 40
成功数 | 0
失败数 | 0
工作数 | 1
使用总量 | Up: 0.0 B / Down: 0.0 B

能换成自己的appid吗？原host:xxnet4.herokuapp.com
我在code\3.10.4\x_tunnel\local\heroku_front里面的config.py，改里面的xxnet4.herokuapp.com为自己
self.set_var("check_ip_host", "xxnet4.herokuapp.com")
        self.set_var("check_ip_content", "OK")

        # host_manager
        self.set_var("appids", ["xxnet4.herokuapp.com"])
好像不行.

**Comment by xxnet** [comment]
有兴趣我可以把代码公布出来，增加更多通道。
