### ISSUE TITLE
Ubuntu 16.04卸载Firefox后用chrome打不开8085配置页面，也没有系统托盘图标

### ISSUE THREAD

**Issue by zhangbin0917** [XX-net/XX-Net#10080]
XX-Net version:default
3月 19 10:47:42.15 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
3月 19 10:47:42.19 [launcher][INFO] start XX-Net 3.11.1
3月 19 10:47:42.19 [launcher][DEBUG] start confirm_xxnet_exit
3月 19 10:47:42.19 [launcher][DEBUG] <0>: try to terminate xxnet:8085
3月 19 10:47:43.20 [launcher][DEBUG] <1>: try to terminate xxnet:8085
3月 19 10:47:44.20 [launcher][DEBUG] good, xxnet:8085 clear!
3月 19 10:47:44.20 [launcher][DEBUG] finished confirm_xxnet_exit
3月 19 10:47:44.23 [gae_proxy][INFO] SSL use version:TLSv1_2
3月 19 10:47:44.23 [gae_proxy][INFO] OpenSSL support alpn
3月 19 10:47:44.23 [gae_proxy][INFO] load ip range file:/home/zhangbin/XX-Net/code/default/gae_proxy/local/ip_range.txt
3月 19 10:47:44.26 [gae_proxy][INFO] load ip_list num:1000, target num:1000
3月 19 10:47:44.27 [gae_proxy][INFO] SSL use version:TLSv1_2
3月 19 10:47:44.27 [gae_proxy][INFO] ------------------------------------------------------
3月 19 10:47:44.27 [gae_proxy][INFO] Python Version     : 2.7.12
3月 19 10:47:44.27 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:16.04; ID:xenial
3月 19 10:47:44.27 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
3月 19 10:47:44.27 [gae_proxy][INFO] Using public APPID
3月 19 10:47:44.27 [gae_proxy][INFO] ------------------------------------------------------
3月 19 10:47:44.27 [gae_proxy][INFO] no GAE CA file exist in XX-Net data dir
3月 19 10:47:44.27 [gae_proxy][INFO] clean old site certs in XX-Net cert dir
3月 19 10:47:44.27 [gae_proxy][INFO] generate CA file:/home/zhangbin/XX-Net/data/gae_proxy/CAkey.pem
3月 19 10:47:44.34 [gae_proxy][DEBUG] network IPv4 is ok, cost:140 ms
3月 19 10:47:44.38 [gae_proxy][INFO] create CA
3月 19 10:47:44.38 [gae_proxy][INFO] generate certs's key file:/home/zhangbin/XX-Net/data/gae_proxy/Certkey.pem
3月 19 10:47:44.71 [gae_proxy][DEBUG] Importing CA
3月 19 10:47:44.77 [gae_proxy][INFO] Removing old cert in database $HOME/.pki/nssdb
3月 19 10:47:44.83 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:18::9 time:548 h2:0 sni:worth-responsibility-entrance.org, host:xxnet-hf001.appspot.com
3月 19 10:47:44.83 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:2::8 time:552 h2:0 sni:, host:
GoAgent XX-Net - GoAgent                                     C,,  
3月 19 10:47:45.02 [gae_proxy][INFO] Add cert to database $HOME/.pki/nssdb
3月 19 10:47:45.29 [gae_proxy][DEBUG] Begin importing CA to Firefox
3月 19 10:47:45.29 [gae_proxy][INFO] server 127.0.0.1:8087 started.
3月 19 10:47:45.37 [launcher][INFO] module gae_proxy started
3月 19 10:47:45.37 [launcher][INFO] start gae_proxy time cost:1171 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
3月 19 10:47:45.38 [cloudflare_front][INFO] SSL use version:TLSv1_2
3月 19 10:47:45.38 [cloudflare_front][INFO] OpenSSL support alpn
3月 19 10:47:45.38 [cloudflare_front][INFO] load ip range file:/home/zhangbin/XX-Net/code/default/x_tunnel/local/cloudflare_front/ip_range.txt
3月 19 10:47:45.38 [cloudflare_front][INFO] load ip_list num:99, target num:99
3月 19 10:47:45.39 [cloudfront_front][INFO] SSL use version:TLSv1_2
3月 19 10:47:45.39 [cloudfront_front][INFO] OpenSSL support alpn
3月 19 10:47:45.39 [cloudfront_front][INFO] load ip range file:/home/zhangbin/XX-Net/code/default/x_tunnel/local/cloudfront_front/ip_range.txt
3月 19 10:47:45.39 [cloudfront_front][INFO] load ip_list num:100, target num:100
3月 19 10:47:45.40 [tls_relay][INFO] SSL use version:TLSv1_2
3月 19 10:47:45.40 [tls_relay][INFO] OpenSSL support alpn
3月 19 10:47:45.40 [heroku_front][INFO] SSL use version:TLSv1_2
3月 19 10:47:45.40 [heroku_front][INFO] OpenSSL support alpn
3月 19 10:47:45.40 [heroku_front][INFO] load ip_list num:75, target num:75
3月 19 10:47:45.40 [x_tunnel][INFO] use config_path:/home/zhangbin/XX-Net/data/x_tunnel/client.json
3月 19 10:47:45.40 [x_tunnel][INFO] X-Tunnel window:16777216
3月 19 10:47:45.40 [x_tunnel][INFO] xxnet_version:3.11.1
3月 19 10:47:45.40 [x_tunnel][INFO] server 127.0.0.1:1080 started.
3月 19 10:47:45.40 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
3月 19 10:47:45.50 [launcher][INFO] module x_tunnel started
3月 19 10:47:45.50 [launcher][INFO] start x_tunnel time cost:131 ms
3月 19 10:47:45.54 [smart_router][INFO] Load file:/home/zhangbin/XX-Net/code/default/smart_router/local/gfw_black_list.txt
3月 19 10:47:45.55 [smart_router][INFO] Load file:/home/zhangbin/XX-Net/code/default/smart_router/local/gfw_white_list.txt
3月 19 10:47:45.55 [smart_router][INFO] Load file:/home/zhangbin/XX-Net/code/default/smart_router/local/advertisement_list.txt
3月 19 10:47:45.59 [smart_router][DEBUG] include IP range number：3608
3月 19 10:47:45.59 [smart_router][DEBUG] save to file:/home/zhangbin/XX-Net/data/smart_router/cn_ipdb.dat
3月 19 10:47:45.60 [smart_router][DEBUG] use local DNS server:127.0.1.1
3月 19 10:47:45.60 [smart_router][INFO] server 127.0.0.1:8086 started.
3月 19 10:47:45.60 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
3月 19 10:47:45.60 [smart_router][INFO] start DNS server at 127.0.0.1:53
3月 19 10:47:45.64 [launcher][INFO] module smart_router started
3月 19 10:47:45.64 [launcher][INFO] start smart_router time cost:139 ms
3月 19 10:47:45.64 [launcher][INFO] begin to start web control
3月 19 10:47:45.64 [launcher][INFO] server 127.0.0.1:8085 started.
3月 19 10:47:45.64 [launcher][INFO] launcher web control started.
3月 19 10:47:45.66 [launcher][INFO] generate desktop shortcut
[32461:32461:0319/104745.868261:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
3月 19 10:47:45.90 [cloudflare_front][INFO] load /home/zhangbin/XX-Net/data/x_tunnel/cloudflare_domains.json success
3月 19 10:47:45.90 [cloudflare_front][INFO] updated cloudflare front domains from github.
[32471:32471:0319/104745.927888:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: firefox: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: chromium-browser: not found
[32495:32495:0319/104745.996643:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://localhost:8085/'
3月 19 10:47:46.66 [launcher][INFO] need_new_uuid: uuid is empty
3月 19 10:47:46.66 [launcher][INFO] generate uuid:ea243df8-f004-4dd1-954b-117cf1be236f
3月 19 10:47:46.66 [launcher][INFO] get uuid:ea243df8-f004-4dd1-954b-117cf1be236f
3月 19 10:47:46.68 [gae_proxy][INFO] GAE CONNECT xxnet-update.appspot.com:443 
3月 19 10:47:46.69 [gae_proxy][DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=ea243df8-f004-4dd1-954b-117cf1be236f&version=3.11.1&platform=Linux-4.13.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
3月 19 10:47:46.83 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4017:1b::9 time:489 h2:0
3月 19 10:47:46.84 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4005:800::1009 handshake_time:943, fails:0
3月 19 10:47:48.04 [gae_proxy][INFO] DIRECT t:1349 s:1674 200 xxnet-update.appspot.com /update.json?uuid=ea243df8-f004-4dd1-954b-117cf1be236f&version=3.11.1&platform=Linux-4.13.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
3月 19 10:47:48.04 [launcher][INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to /home/zhangbin/XX-Net/data/downloads/version.txt, retry:0
3月 19 10:47:48.66 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4011:1e::10 time:516 h2:0
3月 19 10:47:48.67 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:400a:1::16 handshake_time:932, fails:0
3月 19 10:47:48.84 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:809::201b time:535 h2:0 sni:, host:
3月 19 10:47:48.87 [gae_proxy][DEBUG] create_ssl update ip:2a00:1450:4017:1b::9 time:1068 h2:0 sni:, host:
3月 19 10:47:49.54 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:80a::2003 time:697 h2:0 sni:, host:
3月 19 10:47:51.48 [gae_proxy][DEBUG] network IPv6 is ok, cost:7280 ms
3月 19 10:47:52.57 [gae_proxy][DEBUG] create_ssl update ip:2a00:1450:4011:1e::10 time:1731 h2:0 sni:campaign.analyst.net, host:zhouxingyucn8.appspot.com
3月 19 10:47:53.00 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4016:1b::a time:306 h2:0
3月 19 10:47:53.00 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:4011:1e::10 handshake_time:1016, fails:0
3月 19 10:47:56.61 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4016:1b::a time:758 h2:0 sni:, host:
3月 19 10:47:59.12 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:807::2000 time:538 h2:1 sni:international-present.us, host:doit2-142709.appspot.com
3月 19 10:47:59.92 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4002:34::c time:751 h2:0
3月 19 10:47:59.93 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:4017:1b::9 handshake_time:989, fails:0
3月 19 10:48:03.15 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:9::a time:537 h2:0 sni:, host:
3月 19 10:48:05.66 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:809::201d time:530 h2:1 sni:gift-rock.us, host:lihuacai9.appspot.com
3月 19 10:48:08.84 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4002:27::7 time:395 h2:0
3月 19 10:48:08.84 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:400a:807::200e handshake_time:923, fails:0
3月 19 10:48:10.65 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4002:27::7 time:1485 h2:0 sni:, host:
3月 19 10:48:12.21 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4005:807::201d time:540 h2:1 sni:count.wave.cancer.org, host:dsetng10.appspot.com
3月 19 10:48:12.62 [gae_proxy][INFO] scan_ip add ip:2800:3f0:4001:e::9 time:514 h2:0
3月 19 10:48:12.62 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4002:27::7 handshake_time:895, fails:0
3月 19 10:48:13.72 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:400a:d::6 time:239 h2:0
3月 19 10:48:13.72 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4007:80a::201e handshake_time:847, fails:0
3月 19 10:48:14.82 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:400a:d::9 time:254 h2:0
3月 19 10:48:14.83 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:400c:c06::65 handshake_time:845, fails:0
3月 19 10:48:17.01 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:400a:d::c time:236 h2:0
3月 19 10:48:17.01 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4002:32::7 handshake_time:841, fails:0

**Comment by gjbg1989** [comment]
<0>: try to terminate xxnet:8085
<1>: try to terminate xxnet:8085
😂貌似终止前一次非正常结束的 XX-Net 进程？打不开8085配置页面，也没有系统托盘图标——或许退出再启就好？

**Comment by zhangbin0917** [comment]
试过好几次了，不行啊

**Comment by zhangbin0917** [comment]
@gjbg1989 试过好几次了，不行啊

**Comment by gjbg1989** [comment]
[smart_router][DEBUG] use local DNS server:127.0.1.1
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: chromium-browser: not found

**Comment by uitb** [comment]
@gjbg1989 我也有这个问题，该咋个解决哇？有设置默认浏览器的

**Comment by gjbg1989** [comment]
😭插错话了，除了 Windows 不会其它

**Comment by xxnet** [comment]
​先看看是浏览器问题还是XX-Net的问题：
 看看有没有建立监听端口
 netstat -napt |grep 8085
 如果有，继续

  如果没有curl，先安装curl:
  sudo apt install curl

执行：
 curl -v http://127.0.0.1:8085
 看看有没有返回html内容，如果有，说明是浏览器问题，坚持浏览器的设置。

**Comment by zhangbin0917** [comment]
@xxnet 输入netstat -napt |grep 8085，显示：
tcp        0      0 127.0.0.1:8085          0.0.0.0:*               LISTEN      22041/python

然后执行 curl -v http://127.0.0.1:8085 ， 也返回了html内容。应该怎么设置chrome浏览器啊？

**Comment by xxnet** [comment]
​说明XX-Net正常，问题出在浏览器设置上。

把浏览器的代理全部去掉，就可以访问XX-Net 设置页面了。

然后可以用SwitchyOmega 导入设置，可以进wiki里看文档参考。

**Comment by her999** [comment]
关于 3.11.0 之后的版本在 ubuntu 上面无法运行管理页面，我找到了解决办法，就是用
3.10.7 版本的 code/default/launcher/start.py 文件替换3.11.0版本 之后的相应文件。
ubuntu 上面，使用 pygtk3 ，即 PyGObject ，可能和 XX-Net 使用的 simple_http_server 有冲突，也可能是其他原因。总之是用 pygtk3 出现了问题。把 start.py 替换成 3.10.7 ，依旧使用 pygtk2 ，就能避免问题了。
我用的是 Ubuntu 17.10
