### ISSUE TITLE
第一次启动XX-Net后，需要重启浏览器，证书才会生效

### ISSUE THREAD

**Issue by AaronL-ee** [XX-net/XX-Net#101]
![qq 20150402182214](https://cloud.githubusercontent.com/assets/10268142/6962259/83b3ef40-d965-11e4-9cbc-e57b13a7a947.png)
我安装的xx-net 1.71 使用Google搜索时，证书出现问题

**Comment by yfdyh000** [comment]
点一下图标，发一下详细信息的截图吧。

**Comment by xxnet** [comment]
估计是证书安装了，但你需要重启一次浏览器。

2015-04-02 6:26 GMT-04:00 YFdyh000 <notifications@github.com>:

**Comment by AaronLeeee** [comment]
谢谢，重启了一次好了

**Comment by xxnet** [comment]
下次导入证书后，提示要重启浏览器，才能让证书生效。

**Comment by xxnet** [comment]
新版1.8.11，会等待证书导入后，再启动浏览器。
不过用户一般是开这浏览器去下载XX-Net，还是需要有明确的提示用户重启浏览器。

**Comment by moxiea** [comment]
大神可否加个是否导入证书的选项？ 我只需手动导入到Firefox的证书系统就可以
