### ISSUE TITLE
3.10.8购买的xxnet流量一直没法使用！！！

### ISSUE THREAD

**Issue by allanharper** [XX-net/XX-Net#10101]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.10.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1001 ipv4:0 ipv6:26
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 15
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by allanharper** [comment]
xx-tunnel 登陆不上 连接服务器失败：session server login fail:602

**Comment by gjbg1989** [comment]
IPv6 隧道有效，GAE 有效，有助于 xx-tunnel 正常。
贴运行 netsh int ipv6 show teredo 结果

**Comment by gjbg1989** [comment]
use-ipv6: auto 改为只用 ipv6
scan-ip-thread-num: 15 增大到50-100
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。扫描一定时间
3.10.8 参考 #10048 
现在用回3.10.4貌似更稳定

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37608797-71151154-2bd6-11e8-942a-47973e20a4d5.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37609756-eaf8ace0-2bd8-11e8-859d-07bda14dab02.png)
