### ISSUE TITLE
修改了target_handshake_time之后发现在使用公共appip，无法部署个人appip

### ISSUE THREAD

**Issue by dgfrwx** [XX-net/XX-Net#10100]
以前自己搜的ipv6 ip在一点点减少，但是网速不受影响，总觉得公共ip会耗尽，怎么部署自己的appid呢？

**Comment by gjbg1989** [comment]
自己搜的ipv6 ip在一点点减少——波动大而已，此刻有用等下就无效
#10048 试试：增大扫描线程为100
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP ——开始。。。
https://github.com/XX-net/XX-Net/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3

**Comment by gjbg1989** [comment]
无法部署个人appip——还是 http://127.0.0.1:8085/?module=gae_proxy&menu=config 配置？
从 config.ini 或 manual.ini 复制——粘贴——保存🆗

**Comment by dgfrwx** [comment]
@gjbg1989 就是没法部署个人appid啊，以前旧版本都不用修改什么 config.ini 或 manual.ini什么的， 直接部署就行我也不懂那些东西，但现在3.10.8部署不了了

**Comment by dgfrwx** [comment]
@gjbg1989 在设置部署服务端那里也显示部署成功，日志也没问题，也有邮箱验证允许，但回到状态那里看还是你在使用公共appid

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/37653809-1829709e-2c7b-11e8-9ae1-f92adb5c1203.png)
但回到状态那里看还是你在使用公共appid——保存🆗后退出再启动——还是你在使用公共appid？

**Comment by gjbg1989** [comment]
复制你的 appid ——粘贴——保存
