### ISSUE TITLE
google人机验证，图片无法显示

### ISSUE THREAD

**Issue by lascqy** [XX-net/XX-Net#10104]
以前也偶尔显示过人机验证，只要点击图片就行了
升级到11.1之后，频繁出现，最重要的是验证的时候图片都没法显示，求指点？

**Comment by gjbg1989** [comment]
不是网速的锅？
use-ipv6: auto 改为只用 ipv6
scan-ip-thread-num: 增大到50-100
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。扫描一定时间
3.10.8 参考 #10048 （目前稍正常的最高可用版本）
现在用回简单易用的3.10.4貌似更稳定

**Comment by lascqy** [comment]
不是网速啊，IP足够啊
各种网络就测试过，换回3.10.4，结果还是人机验证图片无法显示，只有不用google等过一阵看了

**Comment by gjbg1989** [comment]
google相关网站总是提示要认证，快给个过滤*.google.com网站的json配置 #10052

**Comment by gjbg1989** [comment]
RT @williamlong: Chrome通过文件对话框的方式上传一个图片速度很慢，只要在Chrome设置里，将”保护您和您的设备不受危险网站的侵害“的选项去掉，即可秒打开图片。 pic.twitter.com/0JnCPvEGdn
