### ISSUE TITLE
打开xx-net出现Welcome to nginx!页面

### ISSUE THREAD

**Issue by web-Huang** [XX-net/XX-Net#10115]
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.
请问下大家这个怎么解决，谢谢

**Comment by gjbg1989** [comment]
？https://zhidao.baidu.com/question/571062847.html
