### ISSUE TITLE
中共滅絕人性

### ISSUE THREAD

**Issue by makaylen** [XX-net/XX-Net#10117]
人，首先是自然的人，然后才是社会的人。“人之初，性本善”，“恻隐之心，人皆有之”，人们判断是、非、善、恶的准则，很多是与生俱来的。而对共产党来说，人就是动物甚至机器，无论资产阶级和无产阶级在其眼中都是物质力量。

共产党的目的是为了操纵人，逐渐把人改造成造反的革命暴徒。马克思说：“物质力量必须用物质力量来打倒”，“理论一经掌握了群众，就会化为物质力量”“全部人类历史不是别的，就是人性的不断改变”，“人性就是阶级性”。他认为一切都没有内在的先天的东西，都是环境的产物，都是“社会人”，反对费尔巴哈的“自然”人的提法。

列宁说：“马克思主义不可能在工人阶级中自发产生，必须从外面灌输。”列宁费尽心思也不能诱导工人从经济斗争转上夺权的政治斗争。他从而寄希望于获诺贝尔奖的巴甫洛夫“条件反射学说”，说它“对于全世界工人阶级有巨大意义”。托洛斯基更妄想条件反射不仅能从心理上，而且从生理上改变人，像狗一样一听到午餐铃声就流口水，让士兵一听到枪响就勇往直前，为共产党献身。

自古以来，人们认为通过努力、劳动、会得到报偿，通过勤劳使生活富裕让人憧憬；而好吃懒做、不劳而获则被视为恶劣。共产党像瘟疫一样传入中国后，社会上的流氓懒汉，在共产党的鼓励下，分土地，抢财产，欺男霸女，全部堂而皇之地成了合法行为。

古人云：“一日为师，终生为父”。1966年8月5日，北京师范大学女子附属中学卞仲耘老师被女学生们戴高帽子、往身上泼黑墨、敲簸箕游街、挂黑牌子、强迫下跪、用带钉子的木棍打、用开水烫等等方法活活打死。北京大学附属中学的女校长被学生强迫敲著一个破脸盆喊“我是牛鬼蛇神”，头发乱七八糟被剪光，头打出了血，推倒在地上爬。

人类的进步是知识进步，而在共产党统治下，知识却成了不好的东西。知识份子被称为“臭老九”，有文化的人要向没有文化的人学习，要接受贫下中农的再教育才能重新做人。为了实施对知识份子的再教育，北京清华大学的教师们被发派到了江西南昌的鲤鱼洲。这个地方血吸虫流行，原来的劳改营都被迫搬迁。教师们只要沾了河里的水就马上染病。一个个肝硬化、肝腹水，很多人丧失生活劳动的能力。

亲情乃天经地义，夫妻、子女、父母、朋友、人与人的正常交往构成了人类社会。通过不间断的各种政治运动，中国共产党把人变成狼，甚至比虎狼更凶残。虎毒不食子，但在中共统治下，父母，子女，夫妻之间互相揭发，断绝亲属关系的比比皆是。

六十年代北京的一所小学，一个女老师在给小学生听写生字时不慎把“社会主义”和“垮台”放在了一起。结果被学生揭发出来。之后她天天被批斗，被男生扇嘴巴子。她的女儿跟她断绝了母女关系，一有风吹草动她女儿就在全班揭发她妈妈的“阶级斗争新动向”。以后几年这位老师天天在学校打扫卫生、刷厕所。

经过文化大革命的人们都不会忘记张志新，她被投入监狱。狱警多次毫无人性地将她衣服扒光，把手反铐在背后，投进男犯人牢房，任人轮奸，终至精神失常。即使这样，在临处决她时，怕她呼喊口号，监狱直接把她的头按在砖块上，不施麻药动刀切开了她的喉管……

**Comment by aisight** [comment]
战争、条件反射，二者紧紧的联系在了一起。

战争带来的，除了技术上的进步，还有人性的剖析。前者存续下来，改进了社会福利。后者，有意无意的被掩埋了。根据存在的资料，可以推断：“条件反射，的确是公正的敌人”。
我看到了条件反射的用途，我就不禁去想，它是如何发挥作用的呢？

战争和条件反射都是深入人心的，我们很难在战争时期定义公正和人性。
不过战争，给我们留下了财富，就是我们反思的根据。在战争结束之后，即使是在条件反射的书籍，例如华生和斯金纳的著作中，我们都能坚定自己，反思和维护公正的决心。

只是我们的敌人，不止是条件反射，还有集体行为。

集体行为可能朝着意料之外的方向发展，这是被认同的一个观点。可是，我们虽然认同这个观点，但是，却很少采取行动，去阻止它的发生。

**Comment by GoodSake** [comment]
哈哈，怎么不评论下Communist Party USA和American Nazi Party呢。
