### ISSUE TITLE
IPv6 状态 | Fail        版本为最新3.11.1

### ISSUE THREAD

**Issue by liu1475341362** [XX-net/XX-Net#10119]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | Fail
IPv4 IP数 | 0
**IPv6 IP数 | 2580**
XX-Net 状态 | 工作
IP延迟 | 1574
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 10

怎么解决？

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10118
