### ISSUE TITLE
3.11.1版任务栏图标异常

### ISSUE THREAD

**Issue by AlephAlpha** [XX-net/XX-Net#10113]
我用的是操作系统是 Linux Mint，桌面环境是 Xfce。

升级到3.11.1后，任务栏（确切地说是 Xfce panel）里的图标变得特别大：

![任务栏截图](https://user-images.githubusercontent.com/3600593/37653051-87c628b4-2c78-11e8-85a5-9768b5d7bbac.png)

而且 127.0.0.1:8085 也无法打开，无法进行配置。另一个 Issue  （#10112）也提到了这个问题。

但连接互联网并没有问题。

之前用的是3.9.6，无此异常。事实上旧版一直很好用，我升级纯属手贱。

<s>顺便问哪里能下载到旧版？</s>[ 已找到下载旧版的地方。](https://github.com/XX-net/XX-Net/releases)已降级到3.10.8，无此异常。

**Comment by bhoppi** [comment]
试试将这个PR #10125 的文件（仅有一个文件 code/版本/launcher/gtk_tray.py）替换掉现有版本看能否解决问题

**Comment by AlephAlpha** [comment]
@bhoppi 好了。

127.0.0.1:8085 无法打开的问题还是没有解决。不过那个应该与此无关。

**Comment by gjbg1989** [comment]
Windows + FireFox 偶尔需添加 127.0.0.1 走“直接连接”😱不然，127.0.0.1:8085 无法打开

**Comment by her999** [comment]
关于 3.11.0 之后的版本在 ubuntu 上面无法运行管理页面，我找到了解决办法，就是用
3.10.8 版本的 code/default/launcher/start.py 文件替换3.11.0版本 之后的相应文件。
ubuntu 上面，使用 pygtk3 ，即 PyGObject ，可能和 XX-Net 使用的 simple_http_server 有冲突，也可能是其他原因。总之是用 pygtk3 出现了问题。把 start.py 替换成 3.10.8 ，依旧使用 pygtk2 ，就能避免问题了。
我用的是 Ubuntu 17.10
