### ISSUE TITLE
启动  start  弹出127.0.0.1：8085但是一直在加载，打不开

### ISSUE THREAD

**Issue by wmgselfblog** [XX-net/XX-Net#10112]
系统 ubuntu 16.04

一直在转圈，有时候Ctrl z  start  会出来一个没有css样式的页面 但是里面链接都点不了

**Comment by silencefun** [comment]
我也是 新做的 双系统 ubuntu 17.10 配完出现这个情况  一直页面出不来，换成老版本 ok

**Comment by wmgselfblog** [comment]
能摔个旧版本的连接吗

**Comment by wmgselfblog** [comment]
3.10.8行吗

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/releases

**Comment by silencefun** [comment]
可以的 我用的就是 3.10.8  都在这里 https://github.com/XX-net/XX-Net/releases

**Comment by her999** [comment]
关于 3.11.0 之后的版本在 ubuntu 上面无法运行管理页面，我找到了解决办法，就是用
3.10.8 版本的 code/default/launcher/start.py 文件替换3.11.0版本 之后的相应文件。
ubuntu 上面，使用 pygtk3 ，即 PyGObject ，可能和 XX-Net 使用的 simple_http_server 有冲突，也可能是其他原因。总之是用 pygtk3 出现了问题。把 start.py 替换成 3.10.8 ，依旧使用 pygtk2 ，就能避免问题了。
我用的是 Ubuntu 17.10
