### ISSUE TITLE
teredo原本正常，登录xx-net后断开

### ISSUE THREAD

**Issue by zehengdong** [XX-net/XX-Net#10120]
软件版本：xx-net 3.10.4
操作系统：win 10

启动xx-net前，teredo状态保持正常：
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 10.10.5.110:62702
外部 NAT 映射    : 211.140.29.18:62702

且ipv6测试网站通过

启动xx-net后：teredo就马上断开
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

xx-net日志
------------------------------------------
Mar 21 13:43:17.036 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"
Mar 21 13:43:17.036 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

**Comment by gjbg1989** [comment]
刚经历，换3.10.8🆗 #10118

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37696063-c3747820-2d0e-11e8-9270-61dbd9905099.png)
未完全正常

**Comment by zehendong** [comment]
@gjbg1989 
NAT : restricted
如何修复这个问题

**Comment by gjbg1989** [comment]
换3.10.8🆗 #10118
或换服务器？
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录，并将bat内2个11项服务器地址后均追加英文句点？）
使用ping超时的微软服务器或许更稳定！(win7除外？)管理权限运行
netsh int ipv6 set teredo enterpriseclient default default 3544
某些不是在下面有说？
 #9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by gjbg1989** [comment]
😂或许禁用再启用网络也可

**Comment by zehendong** [comment]
上面方法都试过了。不行
边上的同事用同样的方法就ok。我的电脑连上teredo之后，一登录xx-net后teredo就挂了

**Comment by gjbg1989** [comment]
服务器名称 : teredo.remlab.net —— tertdo.bat 自动更换的？贴XX-Net诊断信息

**Comment by zehendong** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:64 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

服务器名称 : teredo.remlab.net —— tertdo.bat 自动更换的？贴XX-Net诊断信息
------
reply：是我手动terdo手动改的，也是在登录xx-net前连接上了ipv6。登录之后好像程序冲突了一样。。就被干掉了

**Comment by zehendong** [comment]
另：原本是ok的昨天装成win10之后就不行了。今天装回了win7没想到还是不行，真是要崩溃 了

**Comment by gjbg1989** [comment]
无线网络属性内取消勾选 IPv6 协议
use-ipv6: auto 改为只用ipv6
scan-ip-thread-num: 10 增大5-10倍
要么 tertdo.bat 自动更换，要么管理权限运行
netsh int ipv6 set teredo enterpriseclient win1710.ipv6.microsoft.com. default 3544
知道不行的缘由了，下图为证：你并没完全遵从指引而操作😱
![image](https://user-images.githubusercontent.com/13290970/37704345-84f0b9c2-2d33-11e8-8be4-35cadeaa337c.png)
![image](https://user-images.githubusercontent.com/13290970/37704411-a33f1c02-2d33-11e8-98dc-0b36a5d606ae.png)
登录之后好像程序冲突了一样——自查，😱莫非国祸软件。。。

**Comment by gjbg1989** [comment]
貌似 win10 胜过 win7
你并没完全遵从指引而操作，更别说 #9783

**Comment by gjbg1989** [comment]
貌似装 win10 后自动正常，参数为
类型 : client
服务器名称 : xxxx. （系统默认，以英文句点结束）

**Comment by zehendong** [comment]
按照 @gjbg1989  兄说的加上端口号
>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 10.10.5.110:3544
外部 NAT 映射    : 123.157.208.7:3544

启动teredo
>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

无线网络属性内取消勾选 IPv6 协议 已经取消
use-ipv6: auto 改为只用ipv6 修改成了ipv6没反应
scan-ip-thread-num: 10 增大5-10倍 增大为100 ipv6数目从一开始的个位数，启动不到半分钟降为0.。。。

1.新装的操作系统--排除国货软件问题
2.同事在同一个网段能成功翻墙--排除网络原因
3.看来只剩下是哪里设置的问题么。。。

**Comment by gjbg1989** [comment]
哪里设置的问题—— #9738 
怎么就舍不得换服务器？服务器名称 : teredo.remlab.net 管理权限运行
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.  或
netsh int ipv6 set teredo enterpriseclient win1710.ipv6.microsoft.com.  或
netsh int ipv6 set teredo enterpriseclient win1711.ipv6.microsoft.com.

**Comment by gjbg1989** [comment]
几乎没有立竿见影，得稍侯片刻。。。

**Comment by zehendong** [comment]
立竿见影了。之前用teredo脚本试了好几个什么芬兰的remlab的都不行。
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.  **终于成功了！**
@gjbg1989
