### ISSUE TITLE
3.10.8版本没有扫描日志，怎么弄出扫描日志？

### ISSUE THREAD

**Issue by dgfrwx** [XX-net/XX-Net#10123]
以前看扫描日志就知道自己搜到没有搜到Google ip，现在新版没有扫描日志了

**Comment by dgfrwx** [comment]
@gjbg1989 GAEProxy 日志看不懂哦，一大堆英文加数字符号不懂什么意思

**Comment by gjbg1989** [comment]
😂那就不要好奇呗，观察下 IPv6 IP数、 IP延迟及连接池（首要？！）

**Comment by dgfrwx** [comment]
@gjbg1989 ipv6在慢慢下降，ip延迟基本不变，连接池数字变来变去

**Comment by gjbg1989** [comment]
版本？

**Comment by dgfrwx** [comment]
@gjbg1989 3.10.8 就怕没过几天ipv6变零了

**Comment by gjbg1989** [comment]
参考 #10048 做了？

**Comment by gjbg1989** [comment]
不行就 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP——开始。。。

**Comment by dgfrwx** [comment]
@gjbg1989 
我调到5000了

**Comment by gjbg1989** [comment]
呵呵，建议1000-1500，你倒好😭

**Comment by dgfrwx** [comment]
@gjbg1989 我在其他帖子看到别人说调到5000很好

**Comment by dgfrwx** [comment]
@gjbg1989 好像ip增加了谢谢

**Comment by gjbg1989** [comment]
😂我上面说的是IP数上限。
我在其他帖子看到别人说调到5000很好——因机而异？不行自己再往下调，程序默认是600

**Comment by dgfrwx** [comment]
target_handshake_time是什么意思？和max_good_ip_num有什么区别？

**Comment by gjbg1989** [comment]
看完 #10048 就没有—— target_handshake_time是什么意思？
我以为后一个是ip上限——👍
