### ISSUE TITLE
登录xx-net的时候一直显示正在登录，就是登不上是怎么回事？

### ISSUE THREAD

**Issue by rain0123** [XX-net/XX-Net#10124]
界面大概就是下面这个情况：
GAEProxy 状态信息

连接尚未建立。

X-Tunnel 配置

正在登录...
信息
登录

电子邮件地址

密码

请稍侯...
没有账户？

**Comment by gjbg1989** [comment]
貌似速度的锅 #10118

**Comment by rain0123** [comment]
日志情况：
X-Tunnel 日志

Mar 21 15:09:10.871 - [INFO] xxnet_version:3.10.4
Mar 21 15:09:10.872 - [INFO] server 127.0.0.1:1080 started.
Mar 21 15:09:10.873 - [INFO] Socks5 server listen:127.0.0.1:1080.
Mar 21 15:09:11.726 - [DEBUG] x_tunnel force update info
Mar 21 15:09:15.873 - [DEBUG] start report_stat
Mar 21 15:09:19.047 - [WARNING] front retry center.xx-net.net/login
Mar 21 15:09:44.049 - [WARNING] api:/login fail:status:602 t:32
Mar 21 15:09:45.037 - [DEBUG] x_tunnel force update info
Mar 21 15:09:45.876 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:09:45.877 - [WARNING] report fail.
Mar 21 15:10:15.041 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:10:17.037 - [DEBUG] x_tunnel force update info
Mar 21 15:10:45.878 - [DEBUG] start report_stat
Mar 21 15:10:47.040 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:10:49.038 - [DEBUG] x_tunnel force update info
Mar 21 15:11:15.880 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:11:15.880 - [WARNING] report fail.
Mar 21 15:11:19.041 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:11:21.038 - [DEBUG] x_tunnel force update info
Mar 21 15:11:51.040 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:11:53.038 - [DEBUG] x_tunnel force update info
Mar 21 15:12:15.881 - [DEBUG] start report_stat
Mar 21 15:12:23.041 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:12:25.039 - [DEBUG] x_tunnel force update info
Mar 21 15:12:45.883 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:12:45.883 - [WARNING] report fail.
Mar 21 15:12:55.042 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:12:57.039 - [DEBUG] x_tunnel force update info
Mar 21 15:13:27.042 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:13:29.040 - [DEBUG] x_tunnel force update info
Mar 21 15:13:45.885 - [DEBUG] start report_stat
Mar 21 15:13:59.043 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:14:01.040 - [DEBUG] x_tunnel force update info
Mar 21 15:14:15.887 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:14:15.887 - [WARNING] report fail.
Mar 21 15:14:31.042 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:14:33.041 - [DEBUG] x_tunnel force update info
Mar 21 15:15:03.043 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:15:03.056 - [DEBUG] x_tunnel force update info
Mar 21 15:15:06.834 - [INFO] Close Socks5 server
Mar 21 15:15:06.835 - [INFO] Stopping session
Mar 21 15:15:06.835 - [WARNING] socket accept fail(errno: 9).
Mar 21 15:15:06.938 - [INFO] use config_path:C:\Users\QBK-2\Desktop\XX-Net-3.7.8\data\x_tunnel\client.json
Mar 21 15:15:06.939 - [INFO] X-Tunnel window:16777216
Mar 21 15:15:06.939 - [INFO] xxnet_version:3.10.4
Mar 21 15:15:06.940 - [INFO] server 127.0.0.1:1080 started.
Mar 21 15:15:06.940 - [INFO] Socks5 server listen:127.0.0.1:1080.
Mar 21 15:15:11.941 - [DEBUG] start report_stat
Mar 21 15:15:12.914 - [INFO] Close Socks5 server
Mar 21 15:15:12.914 - [INFO] Stopping session
Mar 21 15:15:12.914 - [WARNING] socket accept fail(errno: 9).
Mar 21 15:15:13.016 - [INFO] use config_path:C:\Users\QBK-2\Desktop\XX-Net-3.7.8\data\x_tunnel\client.json
Mar 21 15:15:13.017 - [INFO] X-Tunnel window:16777216
Mar 21 15:15:13.017 - [INFO] xxnet_version:3.10.4
Mar 21 15:15:13.017 - [INFO] server 127.0.0.1:1080 started.
Mar 21 15:15:13.018 - [INFO] Socks5 server listen:127.0.0.1:1080.
Mar 21 15:15:18.018 - [DEBUG] start report_stat
Mar 21 15:15:33.059 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:15:41.943 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:15:41.943 - [WARNING] report fail.
Mar 21 15:15:48.020 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:15:48.020 - [WARNING] report fail.
Mar 21 15:16:41.944 - [DEBUG] start report_stat
Mar 21 15:16:48.021 - [DEBUG] start report_stat
Mar 21 15:17:11.946 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:17:11.946 - [WARNING] report fail.
Mar 21 15:17:18.023 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:17:18.023 - [WARNING] report fail.
Mar 21 15:18:11.948 - [DEBUG] start report_stat
Mar 21 15:18:18.024 - [DEBUG] start report_stat
Mar 21 15:18:41.951 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:18:41.951 - [WARNING] report fail.
Mar 21 15:18:48.026 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:18:48.026 - [WARNING] report fail.
Mar 21 15:19:41.953 - [DEBUG] start report_stat
Mar 21 15:19:48.027 - [DEBUG] start report_stat
Mar 21 15:20:11.956 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:20:11.956 - [WARNING] report fail.
Mar 21 15:20:18.029 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:20:18.029 - [WARNING] report fail.
Mar 21 15:21:11.957 - [DEBUG] start report_stat
Mar 21 15:21:18.030 - [DEBUG] start report_stat
Mar 21 15:21:41.959 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:21:41.959 - [WARNING] report fail.
Mar 21 15:21:48.032 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:21:48.032 - [WARNING] report fail.
Mar 21 15:22:41.961 - [DEBUG] start report_stat
Mar 21 15:22:48.033 - [DEBUG] start report_stat
Mar 21 15:23:11.962 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:23:11.962 - [WARNING] report fail.
Mar 21 15:23:18.036 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:23:18.036 - [WARNING] report fail.
Mar 21 15:23:52.065 - [DEBUG] x_tunnel force update info
Mar 21 15:24:11.963 - [DEBUG] start report_stat
Mar 21 15:24:18.037 - [DEBUG] start report_stat
Mar 21 15:24:22.068 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:24:23.048 - [DEBUG] x_tunnel force update info
Mar 21 15:24:41.964 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:24:41.964 - [WARNING] report fail.
Mar 21 15:24:48.040 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:24:48.040 - [WARNING] report fail.
Mar 21 15:24:53.051 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:24:55.050 - [DEBUG] x_tunnel force update info
Mar 21 15:25:25.053 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:25:27.049 - [DEBUG] x_tunnel force update info
Mar 21 15:25:41.965 - [DEBUG] start report_stat
Mar 21 15:25:48.042 - [DEBUG] start report_stat
Mar 21 15:25:57.052 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:25:59.050 - [DEBUG] x_tunnel force update info
Mar 21 15:26:11.968 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:26:11.968 - [WARNING] report fail.
Mar 21 15:26:18.044 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:26:18.044 - [WARNING] report fail.
Mar 21 15:26:29.053 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:27:02.150 - [DEBUG] x_tunnel force update info
Mar 21 15:27:11.969 - [DEBUG] start report_stat
Mar 21 15:27:18.045 - [DEBUG] start report_stat
Mar 21 15:27:32.153 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:27:32.178 - [DEBUG] x_tunnel force update info
Mar 21 15:27:41.971 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:27:41.971 - [WARNING] report fail.
Mar 21 15:27:48.048 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:27:48.048 - [WARNING] report fail.
Mar 21 15:28:02.181 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:28:02.211 - [DEBUG] x_tunnel force update info
Mar 21 15:28:32.214 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:28:32.249 - [DEBUG] x_tunnel force update info
Mar 21 15:28:41.972 - [DEBUG] start report_stat
Mar 21 15:28:48.049 - [DEBUG] start report_stat
Mar 21 15:29:02.251 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:29:02.280 - [DEBUG] x_tunnel force update info
Mar 21 15:29:11.975 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:29:11.975 - [WARNING] report fail.
Mar 21 15:29:18.050 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:29:18.050 - [WARNING] report fail.
Mar 21 15:29:32.283 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:29:32.313 - [DEBUG] x_tunnel force update info
Mar 21 15:30:02.317 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:30:03.053 - [DEBUG] x_tunnel force update info
Mar 21 15:30:11.977 - [DEBUG] start report_stat
Mar 21 15:30:18.052 - [DEBUG] start report_stat
Mar 21 15:30:33.056 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:30:35.054 - [DEBUG] x_tunnel force update info
Mar 21 15:30:41.979 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:30:41.979 - [WARNING] report fail.
Mar 21 15:30:48.054 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:30:48.054 - [WARNING] report fail.
Mar 21 15:31:05.056 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:31:07.053 - [DEBUG] x_tunnel force update info
Mar 21 15:31:37.056 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:31:39.054 - [DEBUG] x_tunnel force update info
Mar 21 15:31:41.980 - [DEBUG] start report_stat
Mar 21 15:31:48.055 - [DEBUG] start report_stat
Mar 21 15:32:09.057 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:32:11.055 - [DEBUG] x_tunnel force update info
Mar 21 15:32:11.983 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:32:11.983 - [WARNING] report fail.
Mar 21 15:32:18.057 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:32:18.057 - [WARNING] report fail.
Mar 21 15:32:41.058 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:32:43.055 - [DEBUG] x_tunnel force update info
Mar 21 15:33:11.985 - [DEBUG] start report_stat
Mar 21 15:33:13.063 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:33:15.056 - [DEBUG] x_tunnel force update info
Mar 21 15:33:18.059 - [DEBUG] start report_stat
Mar 21 15:33:41.986 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:33:41.987 - [WARNING] report fail.
Mar 21 15:33:45.063 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:33:47.057 - [DEBUG] x_tunnel force update info
Mar 21 15:33:48.063 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:33:48.063 - [WARNING] report fail.
Mar 21 15:34:17.060 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:34:19.058 - [DEBUG] x_tunnel force update info
Mar 21 15:34:41.989 - [DEBUG] start report_stat
Mar 21 15:34:48.065 - [DEBUG] start report_stat
Mar 21 15:34:49.063 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:34:51.060 - [DEBUG] x_tunnel force update info
Mar 21 15:35:11.992 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:35:11.993 - [WARNING] report fail.
Mar 21 15:35:18.069 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:35:18.074 - [WARNING] report fail.
Mar 21 15:35:21.065 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:35:23.060 - [DEBUG] x_tunnel force update info
Mar 21 15:35:53.065 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:35:55.061 - [DEBUG] x_tunnel force update info
Mar 21 15:36:11.995 - [DEBUG] start report_stat
Mar 21 15:36:18.076 - [DEBUG] start report_stat
Mar 21 15:36:25.068 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:36:27.061 - [DEBUG] x_tunnel force update info
Mar 21 15:36:41.999 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:36:42.000 - [WARNING] report fail.
Mar 21 15:36:48.080 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:36:48.081 - [WARNING] report fail.
Mar 21 15:36:57.065 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:36:59.062 - [DEBUG] x_tunnel force update info
Mar 21 15:37:29.066 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:37:31.061 - [DEBUG] x_tunnel force update info
Mar 21 15:37:42.002 - [DEBUG] start report_stat
Mar 21 15:37:48.083 - [DEBUG] start report_stat
Mar 21 15:38:01.066 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:38:03.062 - [DEBUG] x_tunnel force update info
Mar 21 15:38:12.005 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:38:12.006 - [WARNING] report fail.
Mar 21 15:38:18.087 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:38:18.087 - [WARNING] report fail.
Mar 21 15:38:33.068 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:38:35.063 - [DEBUG] x_tunnel force update info
Mar 21 15:39:05.067 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:39:07.063 - [DEBUG] x_tunnel force update info
Mar 21 15:39:12.008 - [DEBUG] start report_stat
Mar 21 15:39:18.088 - [DEBUG] start report_stat
Mar 21 15:39:37.068 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:39:39.063 - [DEBUG] x_tunnel force update info
Mar 21 15:39:42.012 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:39:42.012 - [WARNING] report fail.
Mar 21 15:39:48.091 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:39:48.092 - [WARNING] report fail.
Mar 21 15:40:09.067 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:40:09.111 - [DEBUG] x_tunnel force update info
Mar 21 15:40:39.116 - [WARNING] api:/login fail:status:602 t:30
Mar 21 15:40:42.013 - [DEBUG] start report_stat
Mar 21 15:40:48.094 - [DEBUG] start report_stat
Mar 21 15:41:12.017 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:41:12.018 - [WARNING] report fail.
Mar 21 15:41:18.097 - [WARNING] api:/report_stat fail:status:602 t:30
Mar 21 15:41:18.098 - [WARNING] report fail.

**Comment by gjbg1989** [comment]
#10118 去看、去做，贴没神马用，尤其对视代码为天书的纯用户老白😱
