### ISSUE TITLE
GAEProxy和X tunnel速度都很慢

### ISSUE THREAD

**Issue by psychopathetic** [XX-net/XX-Net#10121]
GAE只有几十kb的速度。有很多ip，延迟也不高。X tunne速度l也是只有几十kb。

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | OK
IPv4 IP数 | 0
IPv6 IP数 | 2476
XX-Net 状态 | 工作
IP延迟 | 229
连接池(帮助) | 新:1 h1:83 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 50
屏蔽状态(帮助) | OK

XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2479 ipv4:0 ipv6:2476
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:79 h2:0
scan-ip-thread-num: 50
ip-quality: 228
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。
还有 ipv6:2476😱
#10118

**Comment by gjbg1989** [comment]
3.10.4 调小IP上限以利检查 IP，manual.ini 添加
[google_ip]
max_good_ip_num = 1000 （-1500足以？😱）

**Comment by psychopathetic** [comment]
属性 | 值
-- | --
总IP数 | 2509
待测IP数 | 0
有效IP数 | 2287

检查完了，速度没有任何改变。

**Comment by gjbg1989** [comment]
参考 #10048 的3.10.8或许比3.10.4好？

**Comment by psychopathetic** [comment]
换了3.10.8，状况没改善。可能没救了。。

**Comment by gjbg1989** [comment]
换了版本，手动检查 IP😂

**Comment by psychopathetic** [comment]
全做了。没变化。。

**Comment by gjbg1989** [comment]
3.10.8虽然延时显示大，但代理正常，不行就http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。

**Comment by psychopathetic** [comment]
行。基本能用。

**Comment by psychopathetic** [comment]
发现原来是chrome的问题。在chrome上看youtube速度慢，在IE上看快得很。

**Comment by gjbg1989** [comment]
1080P？

**Comment by psychopathetic** [comment]
不是，在chrome上能流畅看480p吧。在IE上看720p，进度条唰唰地就缓冲完了。IE上没得选1080P，不过估计也毫无压力。

**Comment by gjbg1989** [comment]
1080P 😂 https://github.com/xyuanmu/XX-Mini/issues/144

**Comment by psychopathetic** [comment]
操作了，没变化。我的破电脑在ie上看youtube会卡帧，只能用chrome。慢点就慢点吧。
