### ISSUE TITLE
X-TUNNEL 一直登陆不上

### ISSUE THREAD

**Issue by sky2917** [XX-net/XX-Net#10122]
日志如下：

Mar 21 14:25:25.202 - [INFO] xxnet_version:3.10.4

Mar 21 14:25:25.203 - [INFO] server 127.0.0.1:1080 started.

Mar 21 14:25:25.203 - [INFO] Socks5 server listen:127.0.0.1:1080.

Mar 21 14:25:25.956 - [DEBUG] x_tunnel force update info

Mar 21 14:25:26.568 - [DEBUG] session not running, try login..

Mar 21 14:25:27.377 - [WARNING] front retry center.xx-net.net/login

Mar 21 14:25:30.210 - [DEBUG] start report_stat

Mar 21 14:25:56.668 - [WARNING] api:/login fail:status:602 t:30

Mar 21 14:25:56.668 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

Mar 21 14:25:56.668 - [DEBUG] session not running, try login..

Mar 21 14:25:58.462 - [WARNING] api:/login fail:status:602 t:32

Mar 21 14:26:00.298 - [WARNING] api:/report_stat fail:status:602 t:30

Mar 21 14:26:00.298 - [WARNING] report fail.

Mar 21 14:26:26.708 - [WARNING] api:/login fail:status:602 t:30

Mar 21 14:26:26.708 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

Mar 21 14:26:26.708 - [DEBUG] session not running, try login..

Mar 21 14:26:56.939 - [WARNING] api:/login fail:status:602 t:30

Mar 21 14:26:56.939 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

Mar 21 14:26:56.939 - [DEBUG] session not running, try login..

请教各位大神，这是怎么回事？

**Comment by gjbg1989** [comment]
IPv6（隧道）正常——GAE正常——X-TUNNEL
#10118

**Comment by reclusegit** [comment]
Mar 21 14:43:33.860 - [DEBUG] x-tunnel web_control 127.0.0.1:55577 POST /login
Mar 21 14:43:40.812 - [WARNING] login session fail, status:602
Mar 21 14:43:50.814 - [WARNING] login session fail, status:602

中午还在正常用的，好像刚刚出来
