### ISSUE TITLE
求教一个代理问题

### ISSUE THREAD

**Issue by gustav183** [XX-net/XX-Net#10130]
想海淘一个TNF（北脸）衣服，墙内官网（www.thenorthface.com.cn）已关闭，但是直连美国官网时候总是自动跳转到墙内官网，走代理渠道（GAE tunnel 自动转换都试过）访问美国官网又有丢包率问题，登陆账号、付款都不行。

TNF官网应该是没被墙的，有无办法在直连美国官网时候锁定不跳转到墙内网站？

**Comment by gjbg1989** [comment]
GAE tunnel 自动切换——试试：去掉“自动切换”😱

**Comment by gustav183** [comment]
@gjbg1989 我说“GAE tunnel 自动切换”的意思是都分别试过这几个模式，甚至全局模式都试过。

**Comment by gjbg1989** [comment]
GoGo代理 - GoGo Tunnel - GoGo免费Socks和Http代理 - GoGo Sock and Http Proxy - https://www.gogotunnel.com/home

**Comment by gustav183** [comment]
@gjbg1989 走代理访问没有问题，但是登陆账号、付款都不行，如有账号你可试试，另外我和你网页一样，访问该网址一直有资源未加载提示

**Comment by gjbg1989** [comment]
参考：https://github.com/XX-net/XX-Net/issues/10052 😂 "hosts_direct": ？

**Comment by gjbg1989** [comment]
貌似😂没有万能的代理😱

**Comment by xxnet** [comment]
走​x-tunnel 无法登陆吗？
