### ISSUE TITLE
ubuntu 安装了XX-net 一直处于“等待扫描IP，建议开启IPv6。”状态，IPV6 miredo 测试正常

### ISSUE THREAD

**Issue by wzcf1177** [XX-net/XX-Net#10136]
XX-Net Status:

sys-platform: x86_64, Linux-3.13.0-117-generic-x86_64-with-Ubuntu-12.04-precise
os-system: Linux
os-version: #164~precise1-Ubuntu SMP Mon Apr 10 16:16:25 UTC 2017
os-release: 3.13.0-117-generic
os-detail: Dist:Ubuntu; Version:12.04; ID:precise
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
xxnet-version: 3.8.5
python-version: 2.7.3
openssl-version: 0.12 TLSv1 h2:no
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
