### ISSUE TITLE
X-Tunnel 谷歌学术今天又上不了

### ISSUE THREAD

**Issue by wanyixue** [XX-net/XX-Net#10145]
用X-Tunnel上谷歌学术一直好好的，今早突然发现说是流量异常“... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.” 怎么办，就是为了用谷歌学术

**Comment by gjbg1989** [comment]
RT @oiax: https://sci-bay.org 这个好，Google 学术搜索的镜像，免翻墙，速度快。

**Comment by wanyixue** [comment]
楼上的不要再发的宣传广告了，我看到你的广告昨天每个相关的issue都发了个遍，没必要吧。

**Comment by gjbg1989** [comment]
广告广告广而告之😱
