### ISSUE TITLE
Google报私密设置错误，其它正常。

### ISSUE THREAD

**Issue by xichen612** [XX-net/XX-Net#10148]
系统; Win10
版本: xx-net 3.11.1

* 简单描述遇到的问题：
Google.com报隐私错误，其它如youtube等正常，**将GAE-Proxy自动切换改成GAE-Proxy基本切正常，只是有时会跳出人机验证**

* 做过哪些尝试：
将\data\gae_proxy中cets及CA.crt删了重新启动无效(**ps: cet_tuil.py中252行并没有注释......**)

* 请贴出对应模块的状态页
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 10.11.0.101:3544
外部 NAT 映射    : 123.157.208.7:3544

* 请贴出相关的日志
Mar 22 20:25:11.133 - [INFO] scan_ip add ip:2607:f8b0:400a:7::10 time:276 h2:0
Mar 22 20:25:11.136 - [INFO] remove_slowest_ip:2a00:1450:4003:805::2019 handshake_time:1438, fails:9

Mar 22 20:27:37.502 - [INFO] scan_ip add ip:2a00:1450:400a::12 time:445 h2:0
Mar 22 20:27:37.508 - [INFO] remove_slowest_ip:2607:f8b0:401d:4::8 handshake_time:1407, fails:9
Mar 22 20:27:37.635 - [INFO] scan_ip add ip:2607:f8b0:400a:8::18 time:282 h2:0
Mar 22 20:27:37.641 - [INFO] remove_slowest_ip:2607:f8b0:400a:1::6 handshake_time:1405, fails:9
Mar 22 20:27:38.126 - [INFO] scan_ip add ip:2607:f8b0:401c:18::c time:259 h2:0
Mar 22 20:27:38.130 - [INFO] remove_slowest_ip:2607:f8b0:4009:2d::7 handshake_time:1404, fails:9
Mar 22 20:27:40.706 - [INFO] scan_ip add ip:2607:f8b0:400a:3::f time:281 h2:0
Mar 22 20:27:40.712 - [INFO] remove_slowest_ip:2607:f8b0:4000:80a::200e handshake_time:1404, fails:9
Mar 22 20:27:42.227 - [INFO] scan_ip add ip:2a00:1450:400a:5::13 time:480 h2:0
Mar 22 20:27:42.233 - [INFO] remove_slowest_ip:2a00:1450:400e:808::2000 handshake_time:1402, fails:9

**Comment by xxnet** [comment]
1. ​试试 data目录删除，重新启动，导入证书，再试试看看

2. Chrome浏览器中，访问google.com，然后按F12，看证书，是哪里颁发的

**Comment by xichen612** [comment]
1. 尝试将整个data目录删除，提示导入证书成功，重启浏览器，仍然google.com在GAE-proxy下报隐私设置错误。

2. GAE-proxy下，F12 security下google.com证书显示missing，view certificate看到是由GlobalSign Organization Validation CA -SHA256 - G2 颁发给baidu.com  好奇怪。
GAE下正常， 证书是由GoAgent XX-net颁发给google.com

3. 在GAE-proxy和GAE切换过程中， 有时google.com从报隐私设置错误变成找不到服务器的ip地址。

**Comment by xichen612** [comment]
已解决。

情景模式中*.google.com.*这项不知道怎么变成了直接连接。改成GAE-proxy后解决。

再问下，google.com偶尔出现人机验证有办法解决吗？

**Comment by xxnet** [comment]
​可以加入GAE的Direct模式，副作用是可能会比较慢。
参考Wiki:
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
