### ISSUE TITLE
开启ipv6失败

### ISSUE THREAD

**Issue by kaixinwangzi1982** [XX-net/XX-Net#10149]
enableipv6.bat  下面的"有效的Teredo接口名称”需要自己查找替换，具体名称规则，不是Teredo开头的“Teredo Tunneling Pseudo-Interface”，就是本地连接挂*的，状态应该是已连接(connected)。换成“本地连接* 3”执行bat显示乱码呀，开启不了，求解决呀

我的电脑重启后，teredo的适配器就不见了，不知道怎么回事。win7 64位的环境，重装系统后就这样了，很早以前用xx-net没问题的

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by 66cain** [comment]
teredo卸载了。。。
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无
诊断信息
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:2669 ipv4:0 ipv6:2271
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 249
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
之前能用后来下了个Pcap_DNSProxy-master把本地连接、无线网络宽带网络的DNS全改了以后就没法上了
https://github.com/XX-net/XX-Net/issues/9783里4楼方法均尝试过（第四点除外，win732位盗版没这个服务）

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP。。。

**Comment by 66cain** [comment]
不是啊，是terodo被卸了装不上现在ipv6只有disabled

**Comment by 66cain** [comment]
dns已经改好了，dnsproxy也卸掉了

**Comment by gjbg1989** [comment]
运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by kaixinwangzi1982** [comment]
@gjbg1989 

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无


C:\Users\Administrator>

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，管理权限运行
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.
再贴运行 netsh int ipv6 show teredo 结果
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。

**Comment by kaixinwangzi1982** [comment]
@gjbg1989 

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无


我按开始之后立马就停止了，没什么效果

**Comment by gjbg1989** [comment]
是 win10.ipv6.microsoft.com.  （系统默认最后带.）
非win10.ipv6.microsoft.com
https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by kaixinwangzi1982** [comment]
@gjbg1989 我电脑win7 64位旗舰版的，还是不行呀，你加我qq给我远程下吧，563487103,谢谢

**Comment by gjbg1989** [comment]
qq？上上辈子玩的😱
https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启

**Comment by kaixinwangzi1982** [comment]
@gjbg1989 还是不行，估计是我操作系统的问题，我无语了

**Comment by kaixinwangzi1982** [comment]
最后手动添加的teredo适配器搞定的，然后重启下ip helper服务就连接上了ipv6
