### ISSUE TITLE
3.11.3在linux系统运行失败

### ISSUE THREAD

**Issue by yyy123zc** [XX-net/XX-Net#10152]
3.11.3在linux系统（deepin15.5、archlinux、fedora27）运行失败，不能翻墙。3.11.1、3.11.2在linux系统运行时不能打开http://127.0.0.1:8085页面，但可以翻墙。3.10.8运行一切正常。

3.11.3运行日志：
XX-Net version:default
3月 22 23:00:22.61 [launcher][INFO] Using PyGObject as the GUI Backend.
3月 22 23:00:22.78 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
3月 22 23:00:22.80 [launcher][INFO] start XX-Net 3.11.3
3月 22 23:00:22.80 [launcher][DEBUG] start confirm_xxnet_exit
3月 22 23:00:22.80 [launcher][DEBUG] good, xxnet:8085 clear!
3月 22 23:00:22.80 [launcher][DEBUG] finished confirm_xxnet_exit
3月 22 23:00:23.00 [gae_proxy][INFO] ------------------------------------------------------
3月 22 23:00:23.00 [gae_proxy][INFO] Python Version     : 2.7.13+
3月 22 23:00:23.00 [gae_proxy][INFO] OS                 : Dist:Deepin; Version:15.5; ID:unstable
3月 22 23:00:23.00 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dzqn/XX-Net/code/default/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/home/dzqn/XX-Net/code/default/gae_proxy/local/proxy.py", line 116, in main
    log_info()
  File "/home/dzqn/XX-Net/code/default/gae_proxy/local/proxy.py", line 105, in log_info
    xlog.info('GAE APPID          : %s', '|'.join(front.config.GAE_APPIDS))
  File "/home/dzqn/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 166, in info
    self.log('INFO', self.reset_color, '000000', fmt, *args)
  File "/home/dzqn/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 116, in log
    string = '%s - [%s] %s\n' % (time_str, level, fmt % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1: ordinal not in range(128)
3月 22 23:00:23.08 [gae_proxy][DEBUG] network IPv4 is ok, cost:275 ms
3月 22 23:00:27.82 [gae_proxy][DEBUG] network IPv6 is ok, cost:5009 ms

3.10.8运行日志：

XX-Net version:3.10.8
3月 22 22:53:18.13 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
3月 22 22:53:18.15 [launcher][INFO] start XX-Net 3.10.8
3月 22 22:53:18.15 [launcher][DEBUG] start confirm_xxnet_exit
3月 22 22:53:18.15 [launcher][DEBUG] good, xxnet:8085 clear!
3月 22 22:53:18.15 [launcher][DEBUG] finished confirm_xxnet_exit
3月 22 22:53:18.20 [gae_proxy][INFO] SSL use version:TLSv1_2
3月 22 22:53:18.20 [gae_proxy][INFO] OpenSSL support alpn
3月 22 22:53:18.20 [gae_proxy][INFO] load ip range file:/home/dzqn/XX-Net/code/3.10.8/gae_proxy/local/ip_range.txt
3月 22 22:53:18.23 [gae_proxy][INFO] load ip_list num:614, target num:614
3月 22 22:53:18.24 [gae_proxy][INFO] SSL use version:TLSv1_2
3月 22 22:53:18.24 [gae_proxy][INFO] ------------------------------------------------------
3月 22 22:53:18.24 [gae_proxy][INFO] Python Version     : 2.7.13+
3月 22 22:53:18.24 [gae_proxy][INFO] OS                 : Dist:Deepin; Version:15.5; ID:unstable
3月 22 22:53:18.24 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
3月 22 22:53:18.24 [gae_proxy][INFO] GAE APPID          : 隐藏ID
3月 22 22:53:18.24 [gae_proxy][INFO] ------------------------------------------------------
3月 22 22:53:18.24 [gae_proxy][DEBUG] Importing CA
3月 22 22:53:18.24 [gae_proxy][INFO] please install *libnss3-tools* package to import GoAgent root ca
3月 22 22:53:18.24 [gae_proxy][DEBUG] Begin importing CA to Firefox
3月 22 22:53:18.24 [gae_proxy][INFO] server 127.0.0.1:8087 started.
3月 22 22:53:18.33 [gae_proxy][DEBUG] network IPv4 is ok, cost:174 ms
3月 22 22:53:18.34 [launcher][INFO] module gae_proxy started
3月 22 22:53:18.34 [launcher][INFO] start gae_proxy time cost:190 ms
3月 22 22:53:18.35 [smart_router][DEBUG] x_tunnel not running
3月 22 22:53:18.35 [smart_router][INFO] Load file:/home/dzqn/XX-Net/code/3.10.8/smart_router/local/gfw_black_list.txt
3月 22 22:53:18.35 [smart_router][INFO] Load file:/home/dzqn/XX-Net/code/3.10.8/smart_router/local/gfw_white_list.txt
3月 22 22:53:18.35 [smart_router][INFO] Load file:/home/dzqn/XX-Net/code/3.10.8/smart_router/local/advertisement_list.txt
3月 22 22:53:18.36 [smart_router][DEBUG] use local DNS server:1.2.4.8
3月 22 22:53:18.36 [smart_router][DEBUG] use local DNS server:8.8.8.8
3月 22 22:53:18.36 [smart_router][INFO] server 127.0.0.1:8086 started.
3月 22 22:53:18.36 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.

**Comment by xxnet** [comment]
请把 3.10.8 的配置文件 data/gae_proxy/config.ini 发我邮箱 xxnet.dev@gmail.com，我来调试

**Comment by gjbg1989** [comment]
貌似3.10.5版开始 config.json 有效 config.in 无效？

**Comment by xxnet** [comment]
​恩，搞错了，应该把config.json 发给我

**Comment by yyy123zc** [comment]
我没有在code文件夹内找到config.json，应该意味着3.10.8和3.11.3共用一个config.json文件。所以除了config.json文件外，我将整个XX-Net文件夹打包上传，请按需要下载。
让您等久了，XX-Net不能上传文件到google云盘，使用其它代理方式，发现就http://www.vpngate.net/cn/能用。

**Comment by slimwang** [comment]
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1: ordinal not in range(128)`

看这个issue
#10157

**Comment by yyy123zc** [comment]
3.11.3插入#10157指定代码后正常运行。

**Comment by xxnet** [comment]
好的，​3.11.4版本已经包含这个修复

**Comment by her999** [comment]
关于 3.11.0 之后的版本在 ubuntu 上面无法运行管理页面，我找到了解决办法，就是用
3.10.7 版本的 code/default/launcher/start.py 文件替换3.11.0版本 之后的相应文件。
ubuntu 上面，使用 pygtk3 ，即 PyGObject ，可能和 XX-Net 使用的 simple_http_server 有冲突，也可能是其他原因。总之是用 pygtk3 出现了问题。把 start.py 替换成 3.10.7 ，依旧使用 pygtk2 ，就能避免问题了。
我用的是 Ubuntu 17.10  。

**Comment by yipeterhan** [comment]
请问各位大神在lin下是怎么运行xx-net的……不好意思打扰了，不过我就是想问一下。现在用的是openSUSE，按道理说是./start，但是一直是permission denied，我不清楚是缺什么软件关联还是什么……？谢谢了

**Comment by yyy123zc** [comment]
openSUSE配置XX-Net 前提条件：
sudo zypper install python-gtk-devel pyOpenSSL miredo-client

安装证书：
sudo cp -r CA.crt /etc/ipsec.d/cacerts/

> 请问各位大神在lin下是怎么运行xx-net的……不好意思打扰了，不过我就是想问一下。现在用的是openSUSE，按道理说是./start，但是一直是permission denied，我不清楚是缺什么软件关联还是什么……？谢谢了

**Comment by yyy123zc** [comment]
> 请问各位大神在lin下是怎么运行xx-net的...…不好意思打扰了，不过我就是想问一下。现在用的是openSUSE，按道理说是./start，但是一直是permission denied，我不清楚是缺什么软件关联还是什么……？谢谢了

openSUSE配置XX-Net 前提条件：
sudo zypper install python-gtk-devel pyOpenSSL miredo-client

安装证书：
sudo cp -r CA.crt /etc/ipsec.d/cacerts/
