### ISSUE TITLE
最近IPV6数量少的可怜啊。开启一整天也只有很少的数量。

### ISSUE THREAD

**Issue by longerli** [XX-net/XX-Net#10156]
![image](https://user-images.githubusercontent.com/30004530/37806854-3234bc24-2e7d-11e8-8aa1-d54f964210c0.png)

**Comment by xxnet** [comment]
​升级 3.11.3，再把状态页贴来看

**Comment by gjbg1989** [comment]
@xxnet 建议有严重共性报错的版本，在 https://github.com/XX-net/XX-Net/releases 页面追加警示？😂

**Comment by xxnet** [comment]
​建议不错
