### ISSUE TITLE
中美贸易战打响，对咱这个有什么影响吗

### ISSUE THREAD

**Issue by chendaihang** [XX-net/XX-Net#10161]

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37816959-ef1a683e-2eaf-11e8-9bd0-5227babb9e1c.png)

**Comment by whhxmwhh** [comment]
哈哈。
物价上涨，通货膨胀罢了。

**Comment by GoodSake** [comment]
购买美国产品下单后要备好时间等待，要备好美元，还要备好关税突然翻几倍。
想买波音飞机的小伙伴们又要勒紧裤带了，哈哈哈

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37860430-912a1386-2f5f-11e8-899b-dbb76cc3e434.png)
😂网络防火墻是谁建的？

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37861022-2d04cd76-2f6c-11e8-92ec-d35b395aebe6.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37966761-fb7f5252-31fb-11e8-9ea1-bad7cfa744b2.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37971230-0495fbd2-3208-11e8-92cd-d3b1fe484d50.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37986293-ab0c156c-322d-11e8-9d25-284c3bf96f74.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/38007795-c3a729e0-327d-11e8-83bc-e8e7c5215955.png)

**Comment by gjbg1989** [comment]
RT @zhanglucy88 论脸书（facebook）的报应～苏小和 为什么脸书的报应这么快，理由其实非常简单，他们在一个自由的世界里享受自由的成果，然而却脸不红心不跳地出卖那些渴望自由的人们。这是最大的作恶，脸书无处可逃。 pic.twitter.com/UfYEmaypDd

**Comment by chendaihang** [comment]
谈政治有什么意思，美国已经走向贸易保护主义和孤立主义，还谈什么自由。
你们这些轮子最大的借口已经没有了。
我只是想问问跟咱这个有什么关系，你们又扯到政治

**Comment by gjbg1989** [comment]
RT @caviarokok: 经典网言 这世上有个奇怪的国度，人们从小就被强令学习政治，长大后却不能谈论政治…… pic.twitter.com/hfrssruAvO
![image](https://user-images.githubusercontent.com/13290970/38127634-9a1b586e-3429-11e8-8653-150f65264e3e.png)
![image](https://user-images.githubusercontent.com/13290970/38127643-a8aa1604-3429-11e8-8f92-058d5db5fb85.png)

**Comment by gjbg1989** [comment]
@chendaha 😱
😂打倒美帝！鄙视轮子！！
![default](https://user-images.githubusercontent.com/13290970/38134620-71601942-3446-11e8-87cc-94168fbce89d.png)

**Comment by gjbg1989** [comment]
RT @williamlong 网络安全研究员Paolo Stagno测试了70个VPN提供商，发现其中有16个通过WebRTC泄漏了用户的IP（23％）。 你可以检查你的VPN是否泄漏：http://ip.voidsec.com
RT @williamlong Firefox禁用WebRTC即可防止IP泄漏，方法是：在浏览器上输入：about:config。之后搜索：media.peerconnection.enabled。找到它后双击，将其改成 false 即可。
RT @williamlong Chrome禁用WebRTC可防止IP泄漏，方法是：在Chrome应用商店里，安装一个名为WebRTC Leak Prevent的扩展即可。

**Comment by gjbg1989** [comment]
RT @iyouport_news 微软将于5月1日禁止来自Skype，Xbox，Office和其他服务的'冒犯性语言'和'不适当的内容'，声称它有权审查您的私人数据！！你以为Skype是私人领地？微软告诉你没门儿，他可以监管你和朋友的通话记录 1/ https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K … pic.twitter.com/47awPdI5Q5
RT @iyouport_news 2/ 微软说的“冒犯性语言”究竟是什么鬼？你的交流对象都没觉得是冒犯，微软凭什么要决定什么是冒犯？……纯粹是审查的托辞。 微软也可能阻止 电子邮件，文件共享或即时消息，以执行这些条款，他们说“我们可能因任何原因删除或拒绝发布您的内容” https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K …

**Comment by gjbg1989** [comment]
RT @g2000228 衡量一个人的成功标准并不是用多少金钱，而是你有没有选择与正义，善良同行。周鸿祎能发这个出来，证明有一种不祥预感笼罩他的上空......自求多福吧！ pic.twitter.com/LCzxSRQwqr
![image](https://user-images.githubusercontent.com/13290970/38163001-f141388e-351e-11e8-93f7-816927a4fee7.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38451864-6117fd64-3a6a-11e8-92a6-968b97708252.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38453076-6b5ca17c-3a82-11e8-8f86-c17b941d8159.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38463006-7123e9d0-3b22-11e8-8307-cd20a515a240.png)
