### ISSUE TITLE
3.11.3无法访问scholar.google.com

### ISSUE THREAD

**Issue by BeNhNp** [XX-net/XX-Net#10160]
RT,访问scholar.google.com后被重定向，怎么解决

**Comment by gjbg1989** [comment]
X-Tunnel 代理
https://github.com/XX-net/XX-Net/issues/10052
RT @oiax: https://sci-bay.org 这个好，Google 学术搜索的镜像，免翻墙，速度快。

**Comment by lionisxn** [comment]
问题一样，取消/设置 直连模式均无效，仍然会被重定向到google搜索

**Comment by gjbg1989** [comment]
3.11.4已正常访问

**Comment by lionisxn** [comment]
升级到3.11.4已经正常访问。鉴于升级有风险，已将自动升级关闭。以后没有问题绝不再升级了。
