### ISSUE TITLE
好奇为什么 XX-Net 翻墙之后就只有 Google scholar 无法正常使用

### ISSUE THREAD

**Issue by yuzhounh** [XX-net/XX-Net#10162]
1，切换到 X-Tunnel 大部分时候并不管用。一直用 Google scholar 的替代网站。
2，为什么用 XX-Net 翻墙之后，那么多被屏蔽的网站都能正常访问，就 Google scholar 不行呢？Google scholar 访问量再大，也不可能跟 Google search 相提并论吧。
3，还有类似 Google scholar 这样的翻墙也无法访问的网站吗？

**Comment by gjbg1989** [comment]
#10052 ？

**Comment by gjbg1989** [comment]
3.10.8正常

**Comment by xxnet** [comment]
​你用https方式访问吗

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37835535-59424eee-2eeb-11e8-9987-19a0f6720753.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37835580-7800921e-2eeb-11e8-9452-31ce8440fa10.png)

**Comment by xxnet** [comment]
​奇怪了，先用X-Tunnel吧

**Comment by xxnet** [comment]
​已经找到原因了，是代码bug，3.11.3引入的，明天发新版

**Comment by yuzhounh** [comment]
1，我使用 https 访问啊。
2，切换到 X-Tunel 还是无法访问 Google scholar 啊。之前偶尔这样能够访问，已经现在完全不行了。

**Comment by gjbg1989** [comment]
能打开呢
😂非常时期：不时 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。或：扫描设置——自动调整扫描线程数(帮助)OFF？

**Comment by xxnet** [comment]
用 3.11.4，bug已修复

**Comment by yuzhounh** [comment]
真的用 3.11.4 打开了 Google scholar！太感谢了！我都不记得自己有多少个月没有打开过 Google scholar 了。一直用替代网站。
