### ISSUE TITLE
访问scholar.google.com出来的是www.google.com的页面

### ISSUE THREAD

**Issue by ceski** [XX-net/XX-Net#10165]
3.10.8的gae_proxy/manual.ini中设置

[hosts]
scholar.google.com = direct
scholar.google.com.hk = direct
.googleusercontent.com = direct
可正常访问scholar.google.com，升级到3.11.3后出来的却是www.google.com的页面，再切回3.10.8版本依然正常

**Comment by gjbg1989** [comment]
貌似自3.10.5开始不再支持 manual.ini 及 config.ini，改支持 config.json #10052

**Comment by xxnet** [comment]
​是的，请参考这个wiki：
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by gjbg1989** [comment]
@ceski #10162
