### ISSUE TITLE
完蛋了teredo适配器被我卸了装不回来了咋整？

### ISSUE THREAD

**Issue by 66cain** [XX-net/XX-Net#10169]

**Comment by 66cain** [comment]
设备管理器里现在找不到了

**Comment by gjbg1989** [comment]
确保系统服务IP Helper 为自动并已启动，结束进程 pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启。

**Comment by 66cain** [comment]
感谢，再也不手贱了
