### ISSUE TITLE
XX-Net 3.11.3在Ubuntu 16.04上显示管理页面不正常

### ISSUE THREAD

**Issue by xldelg** [XX-net/XX-Net#10168]
在Ubuntu 16.04上运行XX-Net后自动打开管理页面需等待很长时间，且页面现实不正常，上方的banner覆盖了页面的大约1/3。

**Comment by wangling12** [comment]
我也是，从3.11.0开始就这样了

**Comment by xxnet** [comment]
​什么浏览器？
试试不同浏览器，看看是否浏览器的差异。

**Comment by zbhigh** [comment]
chrome 和 firefox 都不正常

**Comment by her999** [comment]
我用的是 Ubuntu 17.10 ，已经安装了 python-gi 和 PyGObject ，可是依然无法使用新版打开管理页面。后来发现只要把 start.py 文件改成 3.10.8 之前的基本就可以了。好像从  3.10.4 到  3.10.8 ，start.py 都没有改变，到了  3.11.0 就改变了，优先使用  PyGObject ，结果在一些 linux 版本上就出现了问题。

**Comment by xxnet** [comment]
已发布3.11.5 版本，默认采用了原来的库，请测试

**Comment by her999** [comment]
已经测试，正常现实管理页面。
