### ISSUE TITLE
3.11.3 连接尚未建立

### ISSUE THREAD

**Issue by Lishtov** [XX-net/XX-Net#10170]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:10741 ipv4:882 ipv6:509
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

之前一直可用。今天升级之后，不能用了。不知道为什么

**Comment by gjbg1989** [comment]
如自动升级，试试手动下载解压覆盖。
scan-ip-thread-num: 0 ——设置的0还是自动调整的？
netsh int ipv6 show teredo 贴运行结果

**Comment by Lishtov** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.1.116:55093
外部 NAT 映射    : 60.190.139.158:3395

**Comment by Lishtov** [comment]
1、解压覆盖之后没有变化
2、自动调整到0的
3、检查IP没有问题

**Comment by gjbg1989** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.

**Comment by Lishtov** [comment]
无效，还是连接尚未建立……

**Comment by gjbg1989** [comment]
禁用再启用网络，检查IP

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by Lishtov** [comment]
怎么样降级回去？

**Comment by gjbg1989** [comment]
贴目录 code 图

**Comment by xxnet** [comment]
​scan-ip-thread-num: 0 是关键。

贴GAE 启动时的日志看看

**Comment by ljhui** [comment]
我也遇到这个情况，莫名其妙扫描线程数一直保持为0,只能把自动调整扫描线程数关掉,才能使用

**Comment by xxnet** [comment]
​gws-ip-num: total:10741 ipv4:882 ipv6:509

这可能就是原因了， ip够了，就不再扫描。
但是检查ip，应该能够解决。

所以，要看看GAE的日志才知道为什么这样
