### ISSUE TITLE
发觉自3.10.8开始开启局域网代理模式就无限掉i到掉没为止

### ISSUE THREAD

**Issue by Skull-Li** [XX-net/XX-Net#10175]
若开启局域网代理模式，那么自动扫描ip就会停止，然后ip就无效掉，直到掉没就提示开始扫描ipv6

但是关掉后ip马上就迅速恢复
我配置错误么？

局域网代理模式 http
代理ip 192.168.1.100
代理端口8087

本机ip 192.168.1.110

关于局域网代理这方面的介绍和说明甚少，以及8086端口下的pac文件模式该如何使用？

**Comment by xxnet** [comment]
​局域网代理模式 http
代理ip 192.168.1.100
代理端口8087

这是什么代理？
如果你不开启局域网代理，也可以上网，说明你不需要局域网代理。
你可以参考wiki上的说明

**Comment by Skull-Li** [comment]
自己没问题，没搞明白GAE给局域网内用户代理上网的问题

**Comment by Skull-Li** [comment]
自己没问题，没搞明白GAE给局域网内用户代理上网的问题

**Comment by gjbg1989** [comment]
GAE给局域网内用户代理上网——http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页(帮助)ON
对比 data\launcher\config.yaml 的变化？

**Comment by xx-Chen** [comment]
误解“前置代理”然后网络不通所以一直掉ip吧
