### ISSUE TITLE
所有新版本的最大问题是：

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#10173]
3.10.4以后的所有新版本，最大的问题是ip延迟大为增加，从原来的300以下，变成500以上。
这就比较郁闷了。

**Comment by gjbg1989** [comment]
别看广告看疗效😱

**Comment by dahai058** [comment]
这个问题x神已经多次解释属于版本计算问题，只要不影响使用就成，我经过测试观看youtube基本无差别。

**Comment by gjbg1989** [comment]
😂已经多次解释——得每个贴。。。

**Comment by wuwuti** [comment]
我提这个问题，是因为实际使用效率不同，并非只是数据不同。
并非基本无差别——打开同一网页，新版本明显用时增加，甚至打不开。
如果只是版本计算问题，不能统一吗？

**Comment by xxnet** [comment]
​用最新版本试试，3.10.8到3.11.2 版本确实是慢了。
最新 3.11.3 之后的版本有大幅提升，可能比3.9.8还快。

**Comment by wuwuti** [comment]
@xxnet   谢谢回复。
     当下3.11.3的  IP延迟  为567，还能用。
到了600以上，基本就不能用了，网页打开会巨慢，难以忍受。
我觉得上面有人解释说【这个问题x神已经多次解释属于版本计算问题】，是不负责任的。
——ip实际延迟该多少就是多少，与版本没关系。如显示有错误，一直高于实际数据，抽时间修改一下。

**Comment by gjbg1989** [comment]
到了600以上——不时 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP

**Comment by Zmm1977** [comment]
还是退回了3.10.4.。。没啥好说的，油管的速度巨大的差距摆在那里

**Comment by gjbg1989** [comment]
😱也许楼主 @wuwuti @Zmm1977 是对的 https://github.com/XX-net/XX-Net/issues/10171#issuecomment-375893769

**Comment by gjbg1989** [comment]
😂几乎程序默认设置下简单肉眼观察结果：
3.10.4能基本稳定 IP 延迟，有效 IP 数逐渐增长并接近总 IP 数，自动维持正常——貌似与以往使用经验一致；
3.10.8 IP 延迟逐渐增大，有效 IP 数逐渐减小，得不时 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。手动维持正常😱

**Comment by xxnet** [comment]
我看看啊，可能有些代码还没有完全恢复到原来版本的做法

**Comment by gjbg1989** [comment]
辛苦了😂

**Comment by xxnet** [comment]
​已经发现了几个代码上的问题，明显继续对比代码
