### ISSUE TITLE
IPv6-Fail时是否应该停止标记IP无效？

### ISSUE THREAD

**Issue by xx-Chen** [XX-net/XX-Net#10171]
![20180323231151](https://user-images.githubusercontent.com/36025202/37837229-aa1dd6ea-2eef-11e8-9752-a41afb612871.png)

IPv6-Fail的情况下XX-Net仍在检测IP并标记无效，一段时间IPv6不通后再通会出现IP数会为0.

**Comment by xxnet** [comment]
​有这样的设计的，不能保证完全没有bug

**Comment by xx-Chen** [comment]
@xxnet 以前是有效的，但更新GAE模块后就失效了。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/releases
V3.10.5 新版改进：重构 GAE_PROXY 代码

**Comment by xxnet** [comment]
检查过代码，确实存在问题，目前已修复，待发版本

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/10227
