### ISSUE TITLE
我的ipv4 ip数量为1，ipv6 ip数量为 1000左右，最近上谷歌总是要验证数据是不是自己发出的。麻烦大佬们帮忙看看。

### ISSUE THREAD

**Issue by hblin94** [XX-net/XX-Net#10179]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:959 ipv4:1 ipv6:955
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:17 h2:5
scan-ip-thread-num: 0
ip-quality: 509
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
#10052

**Comment by hblin94** [comment]
我认为还是不太意义，因为出现人机验证的时候，网址会有显示ipv4，但是我的ipv4基本上就是0

**Comment by wioo123** [comment]
不错了 我的比你还差
IPv4 IP数 | 0
IPv6 IP数 | 501
IP扫描线程数(设置) | 5

**Comment by hblin94** [comment]
现在我和你一样了，不过我的扫描线程数是10

**Comment by gjbg1989** [comment]
参考：#10184

**Comment by hblin94** [comment]
我看了一下，这个其实和我的问题不太符合，我是ipv4没了ip数，只要上ipv4就有人机交互的画面，而且在更新xxnet以前我的ip数都是好几千的

**Comment by gjbg1989** [comment]
ipv4 貌似见光死
在更新xxnet以前我的ip数都是好几千的——程序IP上限默认值发生了变化 3000-6000-100-1000-500
#10184 😂可以自设定 IP 数上限 xxx，3.10.5 以前版本，manual.ini 添加
[google_ip]
max_good_ip_num = xxx
3.10.5 开始，config.json 添加
"max_good_ip_num": xxx

**Comment by hblin94** [comment]
我的是最新版本的3.11.5

**Comment by gjbg1989** [comment]
最新版本的3.11.5——内部评估版？
![image](https://user-images.githubusercontent.com/13290970/37864996-2a97ca9e-2fb1-11e8-8174-864749b913da.png)

**Comment by hblin94** [comment]
抱歉哈，我写错了，是3.11.3

**Comment by hblin94** [comment]
好的，谢谢您
