### ISSUE TITLE
关于使用全局代理在游戏程序内登陆其他网站遇到的问题

### ISSUE THREAD

**Issue by happyvsp** [XX-net/XX-Net#10186]
前情提要：twitch在某游戏内赠送道具，但是需要从游戏内登陆twitch才能够领取。
登陆twitch除了用户名密码外还需要通过一个人机验证，未使用全局代理时仅能看到输入用户名密码的界面而看不到人机验证的入口。
![qq 20180324162057](https://user-images.githubusercontent.com/15385502/37861993-eadabb30-2f80-11e8-9485-91455cd02b81.png)
使用各种全局代理之后可以看到人机验证入口
![qq 20180324161941](https://user-images.githubusercontent.com/15385502/37862002-0cb9b4e0-2f81-11e8-904a-a67bc3c6fe4c.png)
但是点击左侧方框开始进行人机验证之后会出现
1：无法连接recaptcha
![qq 20180324162255](https://user-images.githubusercontent.com/15385502/37862011-319c2518-2f81-11e8-9949-9ff8262704cc.png)
2：提示稍后重试，然而点什么都没有反应，似乎是直接被判定未通过验证
![qq 20180324162002](https://user-images.githubusercontent.com/15385502/37862019-475f4132-2f81-11e8-9da1-efe7f44e8966.png)
3：可以进入验证页面，但看不到验证内容，点选刷新或语音验证的话会变成2
![qq 20180324162401](https://user-images.githubusercontent.com/15385502/37862030-81e2b410-2f81-11e8-8a86-d67fa08316ad.png)

总之4种全局代理全都试过了，全都不行。
这里是目前的计算机代理设置状态
![qq 20180324163754](https://user-images.githubusercontent.com/15385502/37862050-c2186c1e-2f81-11e8-9f83-eea5f3c2af64.png)
事实上此前也尝试过开启下方手动代理，结果也是一样的。
使用chrome网页登陆的话可以正常通过验证并登陆。
不知道有没有大佬能提供一下解决方案？

**Comment by gjbg1989** [comment]
也许3.10.4正常？

**Comment by SeaHOH** [comment]
尝试新版本
