### ISSUE TITLE
维护 IPv6隧道 win7&10 32位开机及唤醒几乎分秒正常的非组策略（非校园）经验

### ISSUE THREAD

**Issue by gjbg1989** [XX-net/XX-Net#10184]
😱目前也许3.10.4更正常？试试3.11.6 😂IPv6隧道正常——GAE正常——X-Tunnel 正常
首次开启 IPv6 隧道，运行 XX-Net 目录内的 enable_ipv6.bat
非首次，结束进程 pythonw.exe，先 disable_ipv6.bat 再 enable_ipv6.bat 机器重启，也许能恢复正常。
公司、家庭适宜各自运行一个XX-Net（不同网络、设置、扫描结果？），至少 good_ip.txt 文件应有所区分？
😂一般协助，贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）及XX-Net诊断信息文字😂
0、use-ipv6: auto 改为 force_ipv6（只用 ipv6），临时增大扫描线程，正常后改回？至少不是（以下）全部修改项目能立竿见影，观察IP延时、连接池的变化😂
1、试试：无线网络属性内取消勾选 IPv6 协议
2、弃用ISP商DNS ，指定IPv4 及IPv6 DNS ？如 http://www.freenom.world （某天没弃，1小时内 fail 3次）
3、保证注册表项（dword，十六进制0）：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
4、Ipv6 自动转换 | 💖闪闪的红星💖 - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
5、出问题：多次刷新或重载控制页，或禁用再启用网络并稍侯，或结束进程 pythonw.exe、再启动XX-Net，或换服务器。。。
6、#8915 tertdo.bat 自动（或手动）优选服务器（文件解压放在 XX-Net 程序的根目录，并将 bat 内2个11项服务器地址后均追加英文句点？貌似系统默认服务器地址最后都带句点。如运行报错，请用电脑上 XX-Net 的版本号目录 a.b.c 置换掉 tertdo.bat 内 \default\python27\1.0\python.exe 的 default 😂）
7、使用 ping 超时的微软服务器或许更稳定！(win7除外？）莫非类型 natawareclient 比 enterpriseclient 强劲？试试：管理权限运行（最后2项：default 3544 为可选项😂）
netsh int ipv6 set teredo natawareclient default default 3544
(win7只支持 enterpriseclient，如下 )
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com. default 3544
8、（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态 dormant 即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop
9、貌似3.10.4及以前不需。。：不时 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。或：扫描设置——自动调整扫描线程数(帮助)OFF？观察IP延时、连接池的变化😂

![image](https://user-images.githubusercontent.com/13290970/37861286-d9bf1864-2f71-11e8-80bf-8edc8fc5d4f6.png)
![image](https://user-images.githubusercontent.com/13290970/37861289-e5c72278-2f71-11e8-882b-630d63bea314.png)
![image](https://user-images.githubusercontent.com/13290970/37861297-f6218c76-2f71-11e8-86d8-fb9ade36541d.png)

**Comment by gjbg1989** [comment]
貌似无智能路由的最高版3.8.4前后证书文件发生了变化，排除3.8.5无法解决双 Fail ，想各版本来回正常切换，只能是分2段（高低版本各在一个 code 目录，相当于2个XX-Net，如下图的高版本）：3.8.4与之前版本，3.8.5与之后版本
![image](https://user-images.githubusercontent.com/13290970/37861328-800cbd84-2f72-11e8-9030-845a0d5d94a4.png)
如3.8.4前后版本都在一个 code ，更新了3.8.5之后版本想返回3.8.4之前版本 a.b.c，按下处理即可:
结束进程 pythonw.exe，编辑类似图示文件 version.txt 内容为 a.b.c，（删除目录 certs ？）改名 CA.crt 以备份，复制 CAkey.pem 为 CA.crt https://github.com/XX-net/XX-Net/issues/10174

**Comment by xxnet** [comment]
​目前 3.11.4已修复各bug并提升性能，还有多少情况需要切换回老版本的？

**Comment by gjbg1989** [comment]
终极修复：
1、结束进程 pythonw.exe，https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6
2、结束进程 pythonw.exe，https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启。

**Comment by FSP-Butters** [comment]
3.10.5 开始，config.json 添加
"max_good_ip_num": xxx
格式！格式！格式！
前面加逗号！前面加逗号！前面加逗号！
重要的事情粘三遍！重要的事情粘三遍！重要的事情粘三遍！

**Comment by litianyuhehe** [comment]
问下3.11.6版本ip个数是不是限死了 一直是361个 配置文件里加了max good ip 1000 这个参数也不行

**Comment by gjbg1989** [comment]
貌似500-1500足以，程序默认IP上限变迁史：3000-6000-100-1000-500
😂见2楼。。。
参考：#10207 （3.10.5开始）
#10052 3.10.4及以前版本 manual.ini
[hosts]
。。。

**Comment by litianyuhehe** [comment]
我早加了 前两天还是1000个 今天更新完就不动了

**Comment by gjbg1989** [comment]
今天更新完就不动了——手动检查IP，3.10.4以后的版本，关闭“自动调整扫描线程数”😂2楼底

**Comment by litianyuhehe** [comment]
"use_ipv6": "force_ipv6", 
  "max_scan_ip_thread_num": 200, 
  "max_good_ip_num": 1000,
早就关了 还是强制ipv6 最大设1000 最大到361

**Comment by litianyuhehe** [comment]
"auto_adjust_scan_ip_thread_num": 0,

**Comment by gjbg1989** [comment]
😱目前也许3.10.4更正常？开启“自动调整扫描线程数”，有效IP会逐渐接近上限，延时较其它新版小

**Comment by xxnet** [comment]
@litianyuhehe
​
GAE 的诊断信息贴出来看

**Comment by gjbg1989** [comment]
哈哈，有人 @jinsmengjin 心特黑😱#10243
![image](https://user-images.githubusercontent.com/13290970/38027758-68216f0e-32c3-11e8-970e-5fbfd17b92b4.png)
![image](https://user-images.githubusercontent.com/13290970/38027785-7d0b2bb2-32c3-11e8-980d-f70da0768011.png)

**Comment by gjbg1989** [comment]
😭因为404，请帮忙截图3个贴的 @xxnet 最后回复，学习下。。。
![image](https://user-images.githubusercontent.com/13290970/38034777-95aa67f2-32d5-11e8-82ea-45fd055a1c2b.png)

**Comment by xxnet** [comment]
​呵呵

**Comment by gjbg1989** [comment]
谁在呵呵，谁来👌

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/38036238-dde2183c-32d8-11e8-81a3-503d2246b168.png)
![image](https://user-images.githubusercontent.com/13290970/38036269-ec1e672a-32d8-11e8-9f0d-fcaa829cbc53.png)
![image](https://user-images.githubusercontent.com/13290970/38036277-f037c7c0-32d8-11e8-878b-ded8a854ee0b.png)
![image](https://user-images.githubusercontent.com/13290970/38036297-faacda74-32d8-11e8-9728-54728a290750.png)

**Comment by gjbg1989** [comment]
😱没人贴图，被黑心😂勾起的“为其他设备提供代理服务” https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1 也没折腾成功😭

**Comment by litianyuhehe** [comment]
Mar 29 14:06:51.259 - [WARNING] get_slice fail

Mar 29 14:06:51.259 - [WARNING] get_slice fail

Mar 29 14:06:51.259 - [ERROR] scan_ip_worker except:Exception()

Mar 29 14:06:51.259 - [ERROR] scan_ip_worker except:Exception()

Mar 29 14:06:51.259 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_manager.py", line 647, in scan_ip_worker ip = self.ip_source.get_ip() File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 231, in get_ip return self.ipv6_source.get_ip() File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 211, in get_ip line = self.get_slice() File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 204, in get_slice raise Exception() Exception

Mar 29 14:06:51.259 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_manager.py", line 647, in scan_ip_worker ip = self.ip_source.get_ip() File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 231, in get_ip return self.ipv6_source.get_ip() File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 211, in get_ip line = self.get_slice() File "E:\XX-Net\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 204, in get_slice raise Exception() Exception

我是昨天那位 后台报这个错 ip上限设的1000 现在100个出头 不知道和这个报错有没有关系 家里电脑没问题 公司的就不行

**Comment by gjbg1989** [comment]
😱视代码为天书的纯用户老白，无视。。。
😂要么重温一楼第5行。。。

**Comment by litianyuhehe** [comment]
昨天手动下载 切成default ip也涨不上去

**Comment by gjbg1989** [comment]
切成default——手动解压目录？放在更新前正常版本的 code 下的？
ip也涨不上去——1楼9、。。。做了？

**Comment by litianyuhehe** [comment]
昨天都回答过一遍了 该调的都调了

**Comment by gjbg1989** [comment]
如果已按一楼操作，增大扫描线程、不时手动检查IP都无解，老白也帮不上了😂

**Comment by xxnet** [comment]
@​litianyuhehe

这个异常确实是bug，不过不是必然出现，有一定概率，会影响扫描ipv6，如果不是不断的出现，就没有问题。
出一次错，只影响这次的扫描，下一轮扫描不受影响。

下个版本会修复.

**Comment by litianyuhehe** [comment]
那我估计是我的网的问题 原来都没什么问题的 就这两天出的问题 估计是教育部的网封杀的比较严重 ip100+ 上不去 前两天稳定1000的

**Comment by litianyuhehe** [comment]
Mar 29 15:48:37.631 - [WARNING] gae_exception:'600:fetch gae fail' https://www.google-analytics.com/analytics.js

Mar 29 15:48:38.113 - [INFO] GAE t:5507 s:0 GET https://www.google-analytics.com/analytics.js 0:start_request,0:get_task(5),0:get_worker(0):2620:11a:a012:1::e,0:h1_req,0:h1_req_sended,479:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:381],:0

Mar 29 15:48:38.264 - [WARNING] 2001:b032:8101::13 h1_request:Exception('time out',) inactive_time:125 task.timeout:5

Mar 29 15:48:38.264 - [WARNING] 2001:b032:8101::13 trace: 0:connect, 7285:init, 0:head, 483:head end, 119625:request,:5658, processed:0, transfered:0, sni:clouddoubledeparture.org

**Comment by litianyuhehe** [comment]
Mar 29 15:35:34.613 - [WARNING] h1 2620:11a:a02d::16 HEAD keep alive request fail:Exception('time out',)

Mar 29 15:35:34.613 - [WARNING] 2620:11a:a02d::16 trace: 0:connect, 3626:init, 2014:head,:6171, processed:0, transfered:0, sni:tune-loss-reply.net

**Comment by litianyuhehe** [comment]
这些算不算是问题呀 感觉不是bug吧

**Comment by litianyuhehe** [comment]
Mar 29 15:41:18.160 - [WARNING] h1 2607:f8b0:400f:13::c HEAD keep alive request fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Mar 29 15:41:18.160 - [WARNING] 2607:f8b0:400f:13::c trace: 0:connect, 8455:init, 0:head,:2516, processed:0, transfered:0, sni:worker.due.net

**Comment by xxnet** [comment]
​Warning 不是Bug，只是网络情况

Error才是bug

**Comment by litianyuhehe** [comment]
哦 好的 谢谢

**Comment by gjbg1989** [comment]
RT @iyouport_news 微软将于5月1日禁止来自Skype，Xbox，Office和其他服务的'冒犯性语言'和'不适当的内容'，声称它有权审查您的私人数据！！你以为Skype是私人领地？微软告诉你没门儿，他可以监管你和朋友的通话记录 1/ https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K … pic.twitter.com/47awPdI5Q5
RT @iyouport_news 2/ 微软说的“冒犯性语言”究竟是什么鬼？你的交流对象都没觉得是冒犯，微软凭什么要决定什么是冒犯？……纯粹是审查的托辞。 微软也可能阻止 电子邮件，文件共享或即时消息，以执行这些条款，他们说“我们可能因任何原因删除或拒绝发布您的内容” https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K …

**Comment by lkhtty** [comment]
其实最重要的就是近来IPV6服务器有问题，我一般都是默认的，然后连不上，换WIN10，连不上再换回默认的，就这二个服务器切换，可保无忧。

**Comment by dvp155** [comment]
恕我直言，自从换了维护者后，我的xxnet就没连接过，是你们搞复杂了，还是封锁变强了？我是个小白，这篇教学完全不知所云。哥们你用通俗点的白话文可以吗，劳资头都大了，毫无逻辑性

**Comment by AnyWAT** [comment]
😜多大的孩子呀，被人领出门就找不回家了？还是根本就没被带上路就已经迷糊了？不过“劳资”估计年纪不小，或来头不小？

**Comment by AnyWAT** [comment]
🤣得有忧患意识？
偶尔即使增大扫描线程、手动检查IP，IP延时就是岿然不动、连接池很少，哪怕退出XX再重开、检查IP还是如此😭某网页都打不开。。。
还好有备无患：在IP延时最小时备份过 good_ip.txt，退出XX，删除 good_ip.txt，改用备份，启动后即使不检查IP，一切又正常了😱

**Comment by AnyWAT** [comment]
RT @oiax DNS 1.1.1.1 支持 DNS-over-TLS 和 DNS-over-HTTPS (DoH) 加密查询，DNS-over-TLS 依赖客户端才能实现，推荐 Stubby (https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby …)；DoH 客户端推荐 DNSCrypt Proxy 2 (https://github.com/jedisct1/dnscrypt-proxy/wiki …)，DNSCrypt Proxy 2 跨平台，负载平衡会选择最快的公共服务器。Firefox 60 已内置 DoH 支持。

**Comment by AnyWAT** [comment]
RT @wuzy Windows 绝赞应用 https://amazing-apps.gitbooks.io/windows-apps-that-amaze-us/content/zh-CN/ … ，https://portableapps.com/ ，http://www.zdfans.com/ 。

**Comment by AnyWAT** [comment]
🤣原来弃用 ISP 的DNS能救命：😱
停电到另处的Win10上用XX-Net为手机分享代理，3.8.4及3.10.4在使用中逐渐异常至不能代理，发现连接池几乎归零，改电脑 IPv4/6 DNS由自动获取到指定四个1，完美解决问题😋

**Comment by AnyWAT** [comment]
3.8.4是没有“智能路由”的最高版本
3.8.5及以前版本与3.8.6及以后版本，证书文件发生了变化，退回3.8.5及以前可不是一个好主意🤣（至少不能同在一个XX-Net根目录下）
建议使用3.10.4，想IP延迟小并稳定，修改 manual.ini
[google_ip]
max_good_ip_num = 1000 （程序默认6000太大，不好😜）
IP延时大、或转换XX-Net版本及网络卡顿，增大扫描线程，”手动检查IP。。。
IP延时😜
3.8.5：250左右
3.10.4：250左右
3.10.8：？
3.11.7：300-350
3.11.9：280-320

**Comment by AnyWAT** [comment]
"仅IPv6" 不可用，请检查。——IPv6 隧道断开，禁用再启用网络，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。🤣

**Comment by AnyWAT** [comment]
😱有说 [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters] 某参数 dword 16进制 0 （以前正常 enterpriseclient 时一直如此），但正常的现在（natawareclient）
![default](https://user-images.githubusercontent.com/37962734/38650763-237d5066-3e30-11e8-8c8c-91e3d992b9cd.png)
