### ISSUE TITLE
version 3.11.4启用smart-route后启动时python进程cpu占用100%

### ISSUE THREAD

**Issue by wuyongwen** [XX-net/XX-Net#10181]
version 3.11.4启用smart-route后启动时python进程cpu占用100%，无法启动web管理端，切换到3.11.3版本后正常。3.11.4运行一会就会python进程100%。

**Comment by wuyongwen** [comment]
额～难道是我电脑问题吗。运行一会python就100%了。

**Comment by gjbg1989** [comment]
3.11.4运行一会就会python进程100%——没见到😱

**Comment by ts0307** [comment]
macos也遇到这个问题了

**Comment by Hspine** [comment]
3.8.7真的很好用

**Comment by xxnet** [comment]
​诊断信息贴出来，看看能否重现

**Comment by morrisli** [comment]
macos同样的问题，linux下就很正常。

**Comment by xxnet** [comment]
​请各位贴出GAE的状态页，看操作系统的具体版本号，好重现问题
