### ISSUE TITLE
老是沒有IP該怎麼辦？

### ISSUE THREAD

**Issue by vinson2088** [XX-net/XX-Net#10180]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5999 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

嘗試過ISATAP隧道開啟IPv6，但是ipconfig裡還是沒有看到IPv6的地址信息。。

**Comment by gjbg1989** [comment]
Appids_Not_Exist: true ——Appid 有错
netsh int ipv6 show teredo 贴运行结果

**Comment by vinson2088** [comment]
cmd裡運行netsh int ipv6 show teredo嗎？
結果如下
類型:disabled
服務器名稱:teredo.ipv6.microsoft.com.
客戶端刷新間隔:30秒
客戶端端口:unspecified
@gjbg1989

**Comment by gjbg1989** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by vinson2088** [comment]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:73 ipv4:1 ipv6:1
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

管理員權限運行netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.之後，現在是這樣的

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP。。。
gws-ip-num: total:5999 ipv4:1 ipv6:0
gws-ip-num: total:73 ipv4:1 ipv6:1——变化中😱
use-ipv6: auto改为只用ipv6

**Comment by vinson2088** [comment]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5999 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:1
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

改完說  "仅IPv6" 不可用，请检查。
https://github.com/XX-net/XX-Net/issues/9783也有跟著在做，但是註冊表那裡[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
這兩項都沒找到。。

**Comment by gjbg1989** [comment]
改完說 "仅IPv6" 不可用，请检查——貌似几百之第二次听说😂
註冊表那裡。。這兩項都沒找到——何谓保证？有而不同则修改，没有则。。。请将 #9783 看完，貌似后面有补图

**Comment by vinson2088** [comment]
謝謝你的幫助，但我還是解決不了。。 後面越看越看不懂了@gjbg1989

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by gjbg1989** [comment]
"仅IPv6" 不可用，请检查——禁用再启用网络，再次检查 IP。。。

**Comment by xxnet** [comment]
参考过wiki吗？
https://github.com/XX-net/XX-Net/wiki/IPV6-Win7

**Comment by gjbg1989** [comment]
@vinson2088 试试用回 3.10.4？

**Comment by xxnet** [comment]
​IPv6失败，和XX-Net版本没有关系

**Comment by gjbg1989** [comment]
终极修复：结束进程 pythonw.exe，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启。

**Comment by vinson2088** [comment]
@xxnet 你好，https://github.com/XX-net/XX-Net/wiki/IPV6-Win7 這個頁面看過了，但是上面提到的code\version\gae_proxy\local\ipv6_tunnel文件夾我這裡沒有看到。。我這邊code文件夾下只有default文件夾和一個version.txt文件。。嘗試重新來這裡下XX-Net，仍然沒有。。倒是code\default\gae_proxy\local\ipv6_tunnel下也有一個enable_ipv6.bat文件，是否使用它？

**Comment by vinson2088** [comment]
@gjbg1989 你好，https://support.microsoft.com/zh-cn/help/929852/  上面一排後3個工具，第一個第二個的下載鏈接不行了，下載不了“在所有非隧道接口上禁用 IPv6”和“在所有隧道接口上禁用 IPv6”這兩個工具。。第二排的倒是都下好了。是否可以跳過第一排的工具直接運行下排的3個工具然後重啟？

**Comment by gjbg1989** [comment]
下載鏈接不行了——试了下，正常弹出下载保存。。。
试试就知，不行再来😂

**Comment by gjbg1989** [comment]
首次开启，运行 enable_ipv6.bat
非首次，先 disable_ipv6.bat 再 enable_ipv6.bat

**Comment by xxnet** [comment]
code\version\gae_proxy\local\ipv6_tunnel
version  应该是：default或最新版本号
wiki已更新
​

**Comment by vinson2088** [comment]
@gjbg1989 你好，重新下載了到了那6個工具，運行之後重啟機器，仍然提示"仅IPv6" 不可用，请检查。
也試過了 @xxnet 所提到的https://github.com/XX-net/XX-Net/wiki/IPV6-Win7 上面說的運行enable.bat，然後運行netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"，得到了“对象已存在”的提示。後面訪問http://test-ipv6.com/ 這個頁面，出來的結果如下：

IPv4 域名连接测试 |   | 成功 (2.013s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 超时 (17.988s)
双栈域名连接测试 |   | 成功 (1.277s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.244s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (1.276s) 使用 ipv4
无域名 IPv6 连接测试 |   | 超时 (16.716s)
IPv6 大数据包传输测试 |   | 超时 (16.717s)
测试运营商 DNS 是否接入 IPv6 |   | 超时 (5.164s)
查询 IPv4 运营商 |   | 成功 (1.721s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 超时 (16.997s)

**Comment by gjbg1989** [comment]
#10184 贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）

**Comment by vinson2088** [comment]
@gjbg1989 你好，嘗試過禁用再启用网络，再次检查 IP了，檢查完還是一樣。。enable_ipv6.bat也運行過，也一樣。。公司電腦的話近段時間不用翻墻所以沒打開XX-Net了，是否也會有影響？現在無線網絡屬性協議ipv6是取消勾選的狀態，DNS也是改成了80.80.80.80，備用改成80.80.81.81了，http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more  上說的IP轉換配置服務沒有找到。。

**Comment by vinson2088** [comment]
這是診斷信息
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:2 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

這是netsh int ipv6 show teredo的文字結果
Teredo 參數
----------------------------------------
類型： enterpriseclient
服務器名稱： terdo.remlab.net
客戶端刷新間隔： 30秒
客戶端端口： unspecified
狀態： probe<primary server>
客戶端類型： teredo client
網絡： managed

這是全部的結果，不明白你說的無需IP地址的2行指的是？

**Comment by gjbg1989** [comment]
檢查完還是一樣。。enable_ipv6.bat也運行過，也一樣——😇大哥，貌似你非首次开启IPv6，没说该怎么做？
公司電腦的話近段時間不用翻墻所以沒打開XX-Net了，是否也會有影響？——不太明白。估计是本本，公司用、其它如家庭也用，貌似没影响，开了倒可能有影响？#10184 开始有说？
win7 没有：4、Ipv6 自动转换，但稍微推敲网文，如 #10184 图片。。。
xxnet-version: 3.11.3——对 #10184 如此不理解，不如用回3.10.4😱

**Comment by gjbg1989** [comment]
服務器名稱： terdo.remlab.net —— #10184 6、#8915 tertdo.bat 自动（或手动）优选服务器的结果？？？
不明白你說的無需IP地址的2行指的是——😂没到时候。。。

**Comment by vinson2088** [comment]
@gjbg1989 disable_ipv6.bat我也有試過的。。不然也不敢繼續問。。disable之後再點enable，重啟，是一樣的。。
然後公司電腦那個問題我是想問如果公司電腦這段時間內沒有用XX-Net，但公司和家裡電腦使用的是同一個AppID，是否會有影響。。估計是我表達的不夠準確吧。。
然後是https://github.com/XX-net/XX-Net/issues/10184 第6點，tertdo.bat這個文件我在本地也沒找到。。
我試試用回3.10.4吧。多謝你了

**Comment by gjbg1989** [comment]
同一個AppID——只一個？除了流量，没影响
tertdo.bat 這個文件我在本地也沒找到——😱高抬贵鼠，移步 #8915
