### ISSUE TITLE
ipv6正常，YouTube分辨率只有144 p的时候加载速度也很慢，直播视频网站无法顺畅播放

### ISSUE THREAD

**Issue by xxg123** [XX-net/XX-Net#10197]
ipv6正常，YouTube分辨率只有144 p的时候加载速度也很慢
其他直播视频网站，m3u8流的，line live之类的播几秒就断，一直在debug或者timeout
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:32 h2:4
scan-ip-thread-num: 2
ip-quality: 596
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Zmm1977** [comment]
换回3.10.4就行了

**Comment by gjbg1989** [comment]
或升级：3.11.4，或试试：3.10.4
参考：https://github.com/XX-net/XX-Net/issues/10184
