### ISSUE TITLE
解决 ubuntu 上面无法运行3.11.0之后版本的管理页面的临时方法。

### ISSUE THREAD

**Issue by her999** [XX-net/XX-Net#10193]
关于 3.11.0 之后的版本（包含最新的稳定版3.11.3）在 ubuntu 上面无法运行管理页面，我找到了解决办法，就是用
3.10.8 版本的 code/default/launcher/start.py 文件替换3.11.0版本 之后的相应文件。
ubuntu 上面，使用 pygtk3 ，即 PyGObject ，可能和 XX-Net 使用的 simple_http_server 有冲突，也可能是其他原因。总之是用 pygtk3 出现了问题。把 start.py 替换成 3.10.8 ，依旧使用 pygtk2 ，就能避免问题了。
我用的是 Ubuntu 17.10 ，已经安装了 python-gi 和 PyGObject ，可是依然无法使用新版打开管理页面。后来发现只要把 start.py 文件改成 3.10.8 之前的基本就可以了。好像从 3.10.4 到 3.10.8 ，start.py 都没有改变，到了 3.11.0 就改变了，优先使用 PyGObject ，结果在一些 linux 版本上就出现了问题。
拜托作者能否在下一个版本中，能够优先使用 pygtk2 呢？

**Comment by her999** [comment]
![2018-03-25 00-08-27](https://user-images.githubusercontent.com/5758402/37866106-d9f56064-2fc0-11e8-8af9-994ace582b72.png)
从编程的角度上讲，这段程序很好，没有问题，但是实际运行起来，一旦调用了PyGObject，页面管理就出现问题，有时 tray 也无法现实出来，只是有一个空白。这个坑可能是因为linux发行版的问题。

**Comment by her999** [comment]
https://github.com/XX-net/XX-Net/releases 
有各个版本的 XX-Net ，发现有类似问题的 Linux 用户可以试试我的方法。

**Comment by bhoppi** [comment]
在ubuntu上面无法运行管理页面是什么意思？
这段代码是我改的，我想说的是，如果你的系统里同时安装了python2-gi和pygtk，那么这段代码改与不改效果应该是完全一样的，因为这里只是一个条件判断，has_gi和has_pygtk只需要有一个为True，真正的调用是在gtk_tray.py中，它调用的依旧是PyGObject。
所以你如果只改回了start.py就能解决问题，我觉得非常奇怪。

**Comment by her999** [comment]
如果用新版的 start.py  ，相应的 log就是
XX-Net version:default
3月 25 01:14:22.77 [launcher][INFO] Using PyGObject as the GUI Backend.

(start.py:28110): Gtk-WARNING **: Theme parsing error: gtk.css:3601:22: 'none' is not a valid color name
3月 25 01:14:23.01 [launcher][INFO] use build-in openssl lib
3月 25 01:14:23.01 [launcher][INFO] start XX-Net 3.11.3
3月 25 01:14:23.01 [launcher][DEBUG] start confirm_xxnet_exit
3月 25 01:14:23.01 [launcher][DEBUG] good, xxnet:8085 clear!
3月 25 01:14:23.01 [launcher][DEBUG] finished confirm_xxnet_exit
3月 25 01:14:23.09 [gae_proxy][INFO] ------------------------------------------------------
3月 25 01:14:23.09 [gae_proxy][INFO] Python Version     : 2.7.14
3月 25 01:14:23.09 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:17.10; ID:artful
3月 25 01:14:23.09 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087

**Comment by bhoppi** [comment]
我明白了，2.10.8的start.py先引入了pygtk，就会阻止再引入gi。
看来还是PyGObject造成的问题，我会研究一下原因。

**Comment by her999** [comment]
我也想到是这个原因，一个应用中 pygtk 和 PyGObject 是不可能都同时调用的，一旦调用了pygtk ，就不用再用gi调用PyGObject 。就是说 gtk2 和 gtk3 只能用一个。先调用谁，就不能用另一个了。

**Comment by bhoppi** [comment]
能否告知一下您的桌面环境，以及GTK2和GTK3所使用的theme？

**Comment by her999** [comment]
桌面： GNOME Shell  ，主题： Ambiance  ，使用  PyGObject 时,

问题：
curl 'http://localhost:8085' ， 
curl localhost:8085/?module=gae_proxy&menu=logging 
能看到网页的文本。
curl 'http://localhost:8085/css/bootstrap.css'   ， 
curl 'http://localhost:8085/js/jquery-1.11.2.min.js' ，
curl 'http://localhost:8085/img/logo.png'  ,
都显示 curl: (52) Empty reply from server 。等待很长时间，没有回应 。

即： web 服务器能相应对动态网页的申请，却不相应对静态文件的申请。

改变主题，不影响问题的产生。
使用 openbox + tint2 桌面环境时 ，问题基本相同。
改回 使用 pygtk ，上述问题消除。

怀疑原因 ： web 服务器 的静态文件功能和 PyGObject 有冲突 。

另外，在 GNOME Shell 上面 ，不管是使用 PyGObject ，还是 pygtk ，都无法显示 tray 。
使用 pygtk 和 PyGObject ，能够在 tint2 正常显示 tray ，包括菜单功能，大概是因为 GNOME 和 python-notify 的兼容性有问题  。

继续测试，在 xfce4  、 plasma 桌面时的表现，与 openbox 完全相同。
使用 PyGObject ，无法访问页面控制器中的静态文件。使用 pygtk ，则页面控制器完全正常，动态文件和静态文件都能访问。
使用 pygtk 和 PyGObject ，能正常显示 tray 。

**Comment by her999** [comment]
ubuntu 上面的 GNOME 无法显示 tray 的问题已经解决 。需要安装 TopIcons-plus 。
具体的做法是先安装 gnome-tweak-tool 
sudo apt install gnome-tweak-tool 
 ，然后再安装 topIcons-plus ， 详见 https://extensions.gnome.org/extension/1031/topicons/
git clone https://github.com/phocean/TopIcons-plus.git
cd TopIcons-plus
make install
运行 gnome-tweak-tool ，选择 extensions ，设置  topIcons-plus 为 on ，并且把 topIcons-plus 设置为 右对齐（默认是居中对齐，我实在不习惯）。

安装并且设置  topIcons-plus 之后，GNOME 和 openbox  、 xfce4 、 plasma 的问题就完全相同了。显示
 tray 和 上面的菜单，完全正常 。但是使用 PyGObject ，却无法访问 页面控制器中的静态文件。

我怀疑原因是 PyGObject 和 所用 web 服务器中有关静态文件的部分有冲突。这个坑比较古怪，但是我觉得可能性很大。
能否改换 python web framework 试试，比如用 Flask 。

**Comment by xxnet** [comment]
​web服务框架是自己写的代码，可以调试看看卡在什么地方，安装pycharm，单步跟踪，看哪一步卡了。

**Comment by xxnet** [comment]
​我这边无法重现改问题，试过 Ubuntu 16.04和17.10.1，都没有重现。

**Comment by her999** [comment]
好的，我自己先调试一下，看看卡在哪里。有几个网友反馈有类似的问题，这个bug有些奇怪，相同的系统，有人出问题，有人不出问题。可能是和linux系统依赖模式有关。

**Comment by bhoppi** [comment]
你试一下这个gtk_tray.py能否解决问题

**Comment by jiyan135960** [comment]
@bhoppi 不行。。。。还是连接不上管理页面

**Comment by xxnet** [comment]
计划今天先发一个版本。
​准备先回滚代码，让大家先用起来。

**Comment by xxnet** [comment]
​你提交PR吧，让大家能先用起来。

**Comment by her999** [comment]
已经测试，正常现实管理页面。
