### ISSUE TITLE
教育网看gae代理看youtube速度太慢

### ISSUE THREAD

**Issue by yuhongkang** [XX-net/XX-Net#10196]
请问大佬：
我是教育网用户，过去看youtube速度都非常快，我今天下了个3.7.3的版本，视频速率能到2000k；但是network activity一项好像不正常所以依然很卡。而用最新的3.11.4版本，能正常看，但速度只有200k左右。不过我要是不开代理，直连的话速度能再1500k以上。
我的问题是 ：
1、如果我设Proxy SwitchyOmega自动切换youtube为直连的话，我感觉网站访问确实直连，但是加载视频好像依然走的代理的路，速度很慢。不知道有没有什么好的解决方案，强迫症表示不想反复切换代理设置
2、或是有什么办法能让gae代理看视频速度更快一些。

期待并感谢你的答案

附上诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.11.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:12347 ipv4:0 ipv6:3307
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:27 h2:0
scan-ip-thread-num: 0
ip-quality: 271
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
试试：3.10.4
参考：https://github.com/XX-net/XX-Net/issues/10184

**Comment by yuhongkang** [comment]
谢谢，但是切换回3.10.4后还是很慢，有什么别的检查项么

**Comment by yuhongkang** [comment]
@gjbg1989 谢谢，但是切换回3.10.4后还是很慢，有什么别的检查项么

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）

**Comment by yuhongkang** [comment]
@gjbg1989 麻烦您帮我看下 多谢！

类型                    : client
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : unmanaged
NAT                     : none (global connectivity)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 162.105.98.50:50458
外部 NAT 映射    : 162.105.98.50:50458

**Comment by gjbg1989** [comment]
教育网😂没用过，用回3.10.4或3.9.6，试试。。。
#10184 7、试试：管理权限运行（最后2项：default 3544 为可选项😂）
netsh int ipv6 set teredo natawareclient default default 3544 
或
netsh int ipv6 set teredo enterpriseclient default default 3544

**Comment by gjbg1989** [comment]
参考：https://github.com/XX-net/XX-Net/issues/9955
![image](https://user-images.githubusercontent.com/13290970/37874157-144599fa-305c-11e8-930d-7dccb02dc309.png)

**Comment by yuhongkang** [comment]
@gjbg1989 谢谢您的指导，不过我改完还是不行。。。
不知是什么原因

**Comment by gjbg1989** [comment]
好几个组合，试完了？

**Comment by yuhongkang** [comment]
@gjbg1989 是的 不知道是不是做的不对...

类型                    : natawareclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : unmanaged
NAT                     : none (global connectivity)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 162.105.98.50:3544
外部 NAT 映射    : 162.105.98.50:3544

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:1373 ipv4:0 ipv6:1338
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:44 h2:0
scan-ip-thread-num: 34
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
3.10.4 系统默认 max_good_ip_num = 6000 减小为1/3？

**Comment by alexbyrant** [comment]
好像是教育网自己的原因，国际出口被限速了。。。
https://www.v2ex.com/t/440687

**Comment by SeaHOH** [comment]
*.youtube.com
*.googlevideo.com
*.ytimg.com

以上设置为直连
