### ISSUE TITLE
IPV6频繁中断

### ISSUE THREAD

**Issue by Santiago810** [XX-net/XX-Net#10199]
IPV6大概半小时就中断了，需要执行以下命令
```
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface" metric=1
```
执行这条命令后，IPV6就好了，可以翻墙了。
快捷方式里面已经添加了这个命令，当然也给与了管理员权限。

IPV6中断时的状态
```
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by gjbg1989** [comment]
或升级：3.11.4，或试试：3.10.4
参考：https://github.com/XX-net/XX-Net/issues/10184

**Comment by Santiago810** [comment]
升级到3.11.4，不起作用

**Comment by Santiago810** [comment]
升级到3.11.4不起作用 @gjbg1989

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）

**Comment by Santiago810** [comment]
```
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
```

@gjbg1989

**Comment by gjbg1989** [comment]
貌似正常，IPV6频繁中断——或用回3.10.4，或换服务器。
https://github.com/XX-net/XX-Net/issues/10184 7、项

**Comment by hzj-777** [comment]
@gjbg1989 我的情况和楼主类似，3.11.4和3.10.4均试过无效

**Comment by gjbg1989** [comment]
#10184 9、项
或：贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）及XX-Net诊断信息文字

**Comment by Santiago810** [comment]
#10184  第7项，还是没效果！不过非常感谢非常耐性的指导，笑脸

**Comment by Santiago810** [comment]
#10184 第7项，还是没效果！不过非常感谢非常耐性的指导，笑脸 @gjbg1989

**Comment by gjbg1989** [comment]
还是没效果——用回3.10.4，或换服务器了？至少不是全部能立竿见影，自动扫描，或
#10184 9、项—— http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。

**Comment by xxnet** [comment]
​ipv6失效， 应该和XX-Net版本没有关系

**Comment by gjbg1989** [comment]
楼主的IPV6频繁中断，貌似某些版本IP延时逐渐增大至（假）死，没在此之前手动检查IP的后果😂

**Comment by gjbg1989** [comment]
楼主的无线网络：https://github.com/XX-net/XX-Net/issues/8709

**Comment by GoodSake** [comment]
换个teredo就又好了，哈哈哈


![snap1](https://user-images.githubusercontent.com/19205130/37873726-eb347e2a-3054-11e8-8269-b238a9414126.png)

**Comment by gjbg1989** [comment]
win10.ipv6.microsoft.com.
win1710.ipv6.microsoft.com.
win1711.ipv6.microsoft.com.

**Comment by Santiago810** [comment]
我换了teredo服务器也没用，谢谢 @GoodSake

**Comment by Santiago810** [comment]
不是无线，有线，而且是校园网用户！ @gjbg1989

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10200 ？

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37890053-a79f3198-3101-11e8-9aa8-03aa7fb3fdc4.png)
结束进程 pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.

**Comment by gjbg1989** [comment]
校园网与否区别在于：http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页ON/OFF ？

**Comment by gjbg1989** [comment]
校园网与否区别在于：http://127.0.0.1:8085/?module=launcher&menu=config 代理 ON/OFF ？

**Comment by rebecca0001** [comment]
我也是最近ipv6部稳定的厉害，经常用着用着就疯狂掉

**Comment by gjbg1989** [comment]
#10184 9、貌似3.10.4及以前版本无需：不时 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。或：扫描设置——自动调整扫描线程数(帮助)OFF？观察IP延时、连接池的变化😂
3.10.4及以前版本没此问题，3.11.4后续版本或许解决

**Comment by rebecca0001** [comment]
IPv6 Tunnel 的状态经常变成 probe (primary server)

**Comment by gjbg1989** [comment]
貌似服务器不稳定？
#10184 6、或7、

**Comment by Santiago810** [comment]
最近校园网IPV6有点变化，而且只能访问本校的pt站，六维也访问不了。

切换回3.10.4了，
```
Teredo 参数
--------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
AT                     : symmetric (port)
AT 特殊行为   : UPNP: 否，PortPreserving: 否
```
现在的状态是: 等待扫描IP，建议开启IPv6

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true @gjbg1989

**Comment by Santiago810** [comment]
但同校的同学，他用的win10，但是他的就正常工作

**Comment by gjbg1989** [comment]
等待扫描IP，建议开启IPv6——先手动扫描下？
服务器地址丢了最后的句点？
use-ipv6: auto——改为只用 ipv6
scan-ip-thread-num: 10——增大5-10倍正常后改回？
win10必须强过win7 😂

**Comment by Santiago810** [comment]
手动扫描怎么操作呢？？
服务器最后的点号加了（之前也注意到这个了，加不加貌似没什么影响）
也执行了，还是“等待扫描IP，建议开启IPv6”

等了一小会儿后，就正常了！
目前暂时正常了


````
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:255 ipv4:0 ipv6:250
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:70 h2:0
scan-ip-thread-num: 100
ip-quality: 254
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
````

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37892341-1eac4dcc-310a-11e8-86d2-0e2bfe542d52.png)
运行 netsh int ipv6 set teredo enterpriseclient default 的结果，服务器末尾都带.，加不加有无什么影响未知
![image](https://user-images.githubusercontent.com/13290970/37892454-7bb4fde8-310a-11e8-926f-30ad930c3dc6.png)
公用 Appid 有某些使用上的限制？

**Comment by gjbg1989** [comment]
不会是不完整的组策略的锅？貌似完整组策略结果，前4行都应有（Group......）
![image](https://user-images.githubusercontent.com/13290970/37892734-5d082dec-310b-11e8-9ebf-7e12455d7350.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37892953-24c30abe-310c-11e8-887e-9db376f71734.png)

**Comment by gjbg1989** [comment]
@GoodSake 😂露了😱

**Comment by Santiago810** [comment]
没什么限制呀，公共的appid并没有提供有效的IPV4地址，都是靠IPV6。已经更换自己的appid
现在的变化是，IPV6数量一千七了（之前才三四百吧）！

不清楚，今天上午Teredo参数没有“Group Policy”！
快半小时了，还没有中断，估计差不多了吧

现在的配置：
```
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1778 ipv4:1 ipv6:1751
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:19 h2:0
scan-ip-thread-num: 10
ip-quality: 252
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

````

**Comment by gjbg1989** [comment]
慢用😂

**Comment by Santiago810** [comment]
真不好意思，我又来了

![aa](https://user-images.githubusercontent.com/13749127/37893391-7400a658-310d-11e8-9e2a-a812b05f6258.png)

关掉后重启，才能正常使用

**Comment by Santiago810** [comment]
这是我的策略组配置
![qq](https://user-images.githubusercontent.com/13749127/37893700-6b9dd2be-310e-11e8-8ac4-6bef90f6497d.jpg)

**Comment by gjbg1989** [comment]
严格 #10184 😂

**Comment by gjbg1989** [comment]
关掉后重启，才能正常使用——5、出问题：多次刷新或重载控制页，或（结束进程 pythonw.exe、）禁用再启用网络并稍侯。。。无需机器重启
win7 没有：4、Ipv6 自动转换
但稍微推敲网文，如图片。。。

**Comment by xc1988** [comment]
我最近也是经常抽风

**Comment by SeaHOH** [comment]
关闭后仍可回复
