### ISSUE TITLE
请问“系统空闲”如何解决？

### ISSUE THREAD

**Issue by githubhao0705** [XX-net/XX-Net#10198]
![snipaste_20180325_115316](https://user-images.githubusercontent.com/17467692/37871572-3c750962-3023-11e8-8cce-49684c9fe852.png)

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
xxnet-version: 3.11.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:272
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 8
ip-quality: 372
is-idle: 1
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
试试：3.10.4
参考：https://github.com/XX-net/XX-Net/issues/10184

**Comment by gjbg1989** [comment]
is-idle: 1——系统空闲：没有开网页，没有连接需求？
ca_state: Fail——证书错误导致上面状况？

**Comment by gjbg1989** [comment]
结束进程，重开？
