### ISSUE TITLE
MAC 更新3.11.4版本后，无法启动 IPV6了。。。而且图标也不出现在托盘了。。很是奇怪。

### ISSUE THREAD

**Issue by yangsl158** [XX-net/XX-Net#10194]

**Comment by yangsl158** [comment]
双击启动 start后，Python 的小火箭长期停留在程序邬，且活动监视器显示“未响应”。。XX-NET 图标不出现。。
MAC 重启后依然这样。无法使用代理。

**Comment by applestone** [comment]
这个版本也不支持无线分享了，想通过电脑转发的这个版本不行

**Comment by ts0307** [comment]
macos我也遇到同样问题了。

**Comment by gjbg1989** [comment]
Windows 如3.11.4不行，用回3.10.4貌似正常😂

**Comment by jack89757** [comment]
同样的问题，双击启动 start后，Python 的小火箭长期停留在程序邬，且活动监视器显示“未响应”。。XX-NET 图标不出现。。无法进行设置，但是代理暂时正常，没有托盘图标没法切换设置了

**Comment by morrisli** [comment]
macos同样的问题+1

**Comment by qinly** [comment]
+1，程序坞和图标不出现。MacOS 10.13.4 Beta, xx-net 3.11.4

**Comment by yangsl158** [comment]
伙伴们有没有试试最新的3.11.6版本？不知道有没有修复。
我在外面还没测试。
