### ISSUE TITLE
X-Tunnel，连接服务器失败：session server login fail:602

### ISSUE THREAD

**Issue by ZhangAllen98** [XX-net/XX-Net#10195]
X-Tunnel，连接服务器失败：session server login fail:602

Mar 25 10:34:12.182 - [INFO] xxnet_version:3.11.4

Mar 25 10:34:12.182 - [INFO] server 127.0.0.1:1080 started.

Mar 25 10:34:12.182 - [INFO] Socks5 server listen:127.0.0.1:1080.

Mar 25 10:34:14.405 - [DEBUG] x_tunnel force update info

Mar 25 10:34:44.458 - [WARNING] api:/login fail:status:602 t:30

Mar 25 10:35:05.683 - [DEBUG] session not running, try login..

Mar 25 10:35:24.062 - [INFO] api:/login success t:18378

Mar 25 10:35:24.062 - [INFO] update xt_server v20.xx-net.net:443

Mar 25 10:35:24.062 - [INFO] request_balance host:v20.xx-net.net port:443 balance:0.000000 quota:1198566600631.000000

Mar 25 10:35:24.062 - [INFO] session timeout, reset it.

Mar 25 10:35:34.119 - [WARNING] login session fail, status:602

Mar 25 10:35:44.178 - [WARNING] login session fail, status:602

Mar 25 10:35:54.186 - [WARNING] login session fail, status:602

Mar 25 10:36:04.199 - [WARNING] login session fail, status:602

Mar 25 10:36:14.211 - [WARNING] login session fail, status:602

Mar 25 10:36:24.220 - [WARNING] login session fail, status:602

Mar 25 10:36:34.230 - [WARNING] login session fail, status:602

**Comment by gjbg1989** [comment]
IPv6隧道正常——GAE正常——X-Tunnel
更新到3.11.4，或用回3.10.4
参考：#10184

**Comment by QGB** [comment]
连接服务器失败：session server login fail:602

**Comment by AnyWAT** [comment]
结束XX-Net，删除 data\x_tunnel 目录下除 *.json 外的文件？
