### ISSUE TITLE
 3.11.4 感觉就没有自动切换

### ISSUE THREAD

**Issue by xpf7622** [XX-net/XX-Net#10209]
不管国内什么网站，都提示添加条件，直接连接还是GAE-Proxy, 不指定就连不上，或非常慢。

**Comment by gjbg1989** [comment]
此时应手动检查IP。。。

**Comment by xxnet** [comment]
​顶楼是什么意思，没有明白，请详细描述

**Comment by gjbg1989** [comment]
貌似：3.11.3 （）3.10.4以后版本）自动扫描完全不运作 #10208

**Comment by xpf7622** [comment]
打开chrome浏览器，不论打开什么网站，都提示资源未加载，通过GAE-Proxy 手动添加条件，就一个百度网站www.baidu.com也得半天，得手动指定直接连接还是通过GAE-Proxy. 比如直接连接百度*.bdstatic.com，百度网站才能打开。

**Comment by gjbg1989** [comment]
或退出重开？

**Comment by xxnet** [comment]
​Chrome 的代理插件SwitchyOmega，你用的是什么模式？
 建议用GAE_Proxy 或 智能路由，先不要用自动切换。

**Comment by gitxxnet2018** [comment]
是的，我也发现了这个问题，在自动切换模式下，访问国内网站也走了GAE，所以速度很慢，应该是软件的问题

**Comment by xxnet** [comment]
​自动切换是SwtichyOmega的功能，难道SwitchyOmega出问题了吗

**Comment by gjbg1989** [comment]
GAE自动切换模式正常，3.8.4-3.11.4
