### ISSUE TITLE
两台电脑，系统、网络、XX-Net 都完全相同，然而只有一台正常，另一台IP疯狂掉

### ISSUE THREAD

**Issue by Antecer** [XX-net/XX-Net#10206]
如图所示：
![123](https://user-images.githubusercontent.com/8684916/37885532-5d427632-30e8-11e8-97a4-8ffea112bce7.JPG)

左边是第一台电脑的诊断参数，右边是另一台电脑的诊断参数。
从数据上看，两台电脑设置都是一样的。
然而同时启动XX-Net后，左边这台电脑的IP从500+疯狂掉到只有几个，然后就0了。。
右边这台电脑却稳定运行，IP数保持在500左右..

两台电脑都用了XX-Net自带的EnableIPv6.bat脚本开启IPv6通道。

**Comment by Antecer** [comment]
能够Ping通ipv6服务器，然而XX-Net就是显示 IPv6 状态:Fail
`ping -6 ipv6.test-ipv6.com`

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）——2台，左右

**Comment by gjbg1989** [comment]
#10158 试试：绿色免费的 Autoruns https://filehippo.com/zh/search?q=Autoruns 检查系统？

**Comment by Antecer** [comment]
netsh int ipv6 show teredo
结果如下，看起来都差不多，IPv6服务器应该不是导致Fail的原因吧：
![124](https://user-images.githubusercontent.com/8684916/37888045-bd48f254-30f7-11e8-9d84-e22b993ee6a2.JPG)

**Comment by gjbg1989** [comment]
严重怀疑楼上图片与1楼图片的左右颠倒了——左侧行、右侧不行？
IPv6服务器应该不是导致Fail的原因——或贼首😂

**Comment by Antecer** [comment]
我表示并没有颠倒，就是实际数据。
实际上就是左边这个一直显示IPv6状态Fail，右边这个很正常。

**Comment by gjbg1989** [comment]
执行 6、#8915 tertdo.bat 自动（或手动）优选服务器。。。

**Comment by gjbg1989** [comment]
我的
7、使用 ping 超时的微软服务器或许更稳定！(win7除外？)。。。
![image](https://user-images.githubusercontent.com/13290970/37888615-f13ea358-30fa-11e8-95ec-b98a0d7d5bb4.png)

**Comment by Antecer** [comment]
发现奇葩问题了，刚稳定运行了一段时间，有2个v6IP，然后我看IP实在太少，就点了一下检查IP，然后仅有的2个IP也瞬间没了，IPv6的状态又变成了Fail，这到底是BUG还是巧合？

**Comment by standritsu** [comment]
1710不知道是被封了还是停服了，已经不能用了

**Comment by gjbg1989** [comment]
谣言、谣言、谣言😂
![image](https://user-images.githubusercontent.com/13290970/37892927-11f84a0c-310c-11e8-98b4-bd4eaea133e1.png)

**Comment by Antecer** [comment]
看了下，咱俩的唯一区别就是你的客户端端口竟然是打开的，而且有NAT！

**Comment by gjbg1989** [comment]
你校园，我非😂

**Comment by Antecer** [comment]
校园个鬼哦，我是家园网。。。

**Comment by gjbg1989** [comment]
😱泥垢了啊，公司家园无线？
客户端端口3544与default（你的未定义状态）的区别，应不是打开与否，只是指定端口与否
NAT就唔知了——#10184 严格与否的结果？

**Comment by Antecer** [comment]
家里的移动光宽带。。。

**Comment by xc1988** [comment]
移动这几天抽风怪怪的...

**Comment by SeaHOH** [comment]
尝试更换服务器
