### ISSUE TITLE
MAC 3.11.4启动时内存持续上升

### ISSUE THREAD

**Issue by i5possible** [XX-net/XX-Net#10205]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  使用最新版本

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
是  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  无

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
是

* 简单描述遇到的问题：
启动过程中python进程占用内存持续升高，约每秒100M的速度，短时间就达到系统上限

* 做过哪些尝试：
降低为3.11.3之后没有该问题

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by jack89757** [comment]
MAC的3.11.4版本，python内存占用能到9G，我12G的机器一会就假死了

**Comment by gjbg1989** [comment]
😂退出重开？

**Comment by xxnet** [comment]
已发布 3.11.5，对应代码修改，并在Mac 10.12上测试通过，请测试反馈

**Comment by i5possible** [comment]
目前测试OK 了

**Comment by xxnet** [comment]
​好
