### ISSUE TITLE
配置config.json后无法启动xx-net。请问这是怎么回事？

### ISSUE THREAD

**Issue by zhencaihao** [XX-net/XX-Net#10207]
google总是出现流量异常，我就按照wiki里的配置了config.json，但是配置好后xx-net就启动不了了（删除config.json后可以恢复正常）。
{
  “hosts_direct”:[
    "scholar.google.com",
    "www.google.com"
  ] 

}

**Comment by gjbg1989** [comment]
#10052 config.json 格式有误？

**Comment by yyy123zc** [comment]
{
  "hosts_direct": [
    "scholar.google.com", 
    "scholar.google.com.hk", 
    "calendar.google.com", 
    "www.youtube.com", 
    "drive.google.com", 
    "mail.google.com", 
    "play.google.com", 
    "photos.google.com", 
    "imap.gmail.com", 
    "smtp.gmail.com"
  ], 
  "GAE_APPIDS": [

  ], 
  "hosts_gae": [
    "deja.com"
  ], 
  "hosts_direct_endswith": [
    ".appspot.com", 
    ".google.com"
  ]
}

注意符号为半角，非最后 ]要有,

**Comment by zhencaihao** [comment]
![qq 20180326133114](https://user-images.githubusercontent.com/19796493/37888446-16ac04b0-30fa-11e8-8874-ed8be9ba1fa3.jpg)
谢谢二位帮忙。我查了好几次发现是这两个引号菜导致的不能启动XX-NET，改成半角后就好了。

**Comment by abigbone** [comment]
![image](https://user-images.githubusercontent.com/4329020/38066963-e2313210-333c-11e8-83bd-711cbee0c9b8.png)
#10240    done！
