### ISSUE TITLE
链接尚未建立

### ISSUE THREAD

**Issue by HKCLY** [XX-net/XX-Net#10202]
为什么换一个地方ipv6就链接失败了呢？再别的地方就可以正常链接，但是最近新办网后就链接不上了？
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2750 ipv4:0 ipv6:1712
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 532
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10184 贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）

**Comment by 66cain** [comment]
开机启动哪一个？tertdo.bat这个吗？

**Comment by HKCLY** [comment]
抱歉，我的问题还没解决呢，你所问的问题我也不太清除，希望有人会为你解答

**Comment by gjbg1989** [comment]
抱歉，我的问题还没解决呢——不是终止在2楼了？😱

**Comment by pendave** [comment]
这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
尝试使用其中的工具和解决方法
