### ISSUE TITLE
Heroku访问问题

### ISSUE THREAD

**Issue by Zhangjin1993** [XX-net/XX-Net#10213]
直接连接或者使用X-Tunnel访问都很慢，很久才能打开，所以想用GAE，GAE打开其他网站都很快，但是每次访问https://dashboard.heroku.com/ 就会出错，提示广告插件问题，但是我已经禁用ad-block了，不过访问账户设置虽然会提示错误，但是还是能访问的，就是dashboard访问不了。
这个有没有什么解决办法，求解答
![image](https://user-images.githubusercontent.com/33750515/37894317-7311a3c0-3110-11e8-9f9f-0e7a8a4c06e8.png)
![image](https://user-images.githubusercontent.com/33750515/37894542-21e912fc-3111-11e8-8a44-f1d6ac476049.png)

**Comment by xxnet** [comment]
​heroku 官方网站用了WebSocket，GAE不支持。
请升级到最新版本，用X-Tunnel，太慢的话把X-Tunnel状态页发出来看

**Comment by Zhangjin1993** [comment]
@xxnet 日志如下，有时候快有时慢，很不稳定，总体上速度不如开启v6的GAE，另外heroku前端和TLS_Relay 前端一直都是False，这正常吗
![image](https://user-images.githubusercontent.com/33750515/37905006-0ea12990-3130-11e8-9133-8135267c365d.png)

3月 26 19:53:07.47 - [DEBUG] roundtrip time:25372 cost:25096 transfer_no:2580 send:0 rcv:21

3月 26 19:53:07.67 - [DEBUG] roundtrip time:25265 cost:25011 transfer_no:2581 send:0 rcv:21

3月 26 19:53:07.72 - [WARNING] roundtrip time:36020 transfer_no:2550 send:27 status:602

3月 26 19:53:07.82 - [WARNING] roundtrip time:36024 transfer_no:2551 send:27 status:602

3月 26 19:53:07.83 - [WARNING] front retry v19.xx-net.net/data?tid=2554

3月 26 19:53:07.98 - [DEBUG] roundtrip time:25274 cost:25006 transfer_no:2582 send:0 rcv:21

3月 26 19:53:08.23 - [WARNING] roundtrip time:36026 transfer_no:2552 send:32 status:602

3月 26 19:53:08.34 - [WARNING] front retry v19.xx-net.net/data?tid=2555

3月 26 19:53:08.38 - [INFO] socks5 ('127.0.0.1', 41542) connect to simi.heroku.com:443 conn_id:265

3月 26 19:53:08.84 - [WARNING] roundtrip time:36026 transfer_no:2554 send:0 status:602

3月 26 19:53:08.95 - [WARNING] front retry v19.xx-net.net/data?tid=2557

3月 26 19:53:09.34 - [WARNING] roundtrip time:36045 transfer_no:2555 send:32 status:602

3月 26 19:53:09.46 - [WARNING] front retry v19.xx-net.net/data?tid=2559

3月 26 19:53:09.46 - [WARNING] front retry v19.xx-net.net/data?tid=2558

3月 26 19:53:09.77 - [WARNING] front retry v19.xx-net.net/data?tid=2560

3月 26 19:53:09.95 - [WARNING] roundtrip time:36029 transfer_no:2557 send:0 status:602

3月 26 19:53:10.07 - [WARNING] front retry v19.xx-net.net/data?tid=2561

3月 26 19:53:10.38 - [WARNING] front retry v19.xx-net.net/data?tid=2562

3月 26 19:53:10.47 - [WARNING] roundtrip time:36027 transfer_no:2559 send:538 status:602

3月 26 19:53:10.47 - [WARNING] roundtrip time:36084 transfer_no:2558 send:41 status:602

3月 26 19:53:10.68 - [WARNING] front retry v19.xx-net.net/data?tid=2563

3月 26 19:53:10.77 - [WARNING] roundtrip time:36031 transfer_no:2560 send:0 status:602

3月 26 19:53:10.99 - [WARNING] front retry v19.xx-net.net/data?tid=2564

3月 26 19:53:11.08 - [WARNING] roundtrip time:36033 transfer_no:2561 send:0 status:602

3月 26 19:53:11.29 - [WARNING] front retry v19.xx-net.net/data?tid=2565

3月 26 19:53:11.38 - [WARNING] roundtrip time:36036 transfer_no:2562 send:0 status:602

3月 26 19:53:11.60 - [WARNING] front retry v19.xx-net.net/data?tid=2566

3月 26 19:53:11.69 - [WARNING] roundtrip time:36040 transfer_no:2563 send:0 status:602

3月 26 19:53:11.90 - [WARNING] front retry v19.xx-net.net/data?tid=2567

3月 26 19:53:11.99 - [WARNING] roundtrip time:36044 transfer_no:2564 send:0 status:602

3月 26 19:53:12.29 - [WARNING] roundtrip time:36046 transfer_no:2565 send:0 status:602

3月 26 19:53:12.60 - [WARNING] roundtrip time:36051 transfer_no:2566 send:0 status:602

3月 26 19:53:12.91 - [WARNING] roundtrip time:36054 transfer_no:2567 send:0 status:602

3月 26 19:53:14.44 - [WARNING] front retry v19.xx-net.net/data?tid=2571

3月 26 19:53:14.74 - [WARNING] front retry v19.xx-net.net/data?tid=2572

3月 26 19:53:15.44 - [WARNING] roundtrip time:36056 transfer_no:2571 send:41 status:602

3月 26 19:53:15.75 - [WARNING] roundtrip time:36058 transfer_no:2572 send:0 status:602

3月 26 19:53:16.56 - [DEBUG] roundtrip time:406 cost:0 transfer_no:2619 send:0 rcv:21

3月 26 19:53:17.40 - [DEBUG] roundtrip time:947 cost:0 transfer_no:2620 send:0 rcv:21

3月 26 19:53:25.55 - [DEBUG] roundtrip time:17164 cost:16880 transfer_no:2591 send:41 rcv:73

3月 26 19:53:26.28 - [DEBUG] roundtrip time:417 cost:0 transfer_no:2622 send:0 rcv:21

3月 26 19:53:26.61 - [DEBUG] roundtrip time:445 cost:0 transfer_no:2623 send:0 rcv:21

3月 26 19:53:28.38 - [DEBUG] Conn session:oufynrkk conn:264 stop:recv fail.

3月 26 19:53:28.38 - [DEBUG] remove conn_id:264

3月 26 19:53:28.77 - [DEBUG] roundtrip time:388 cost:0 transfer_no:2624 send:32 rcv:21

3月 26 19:53:29.10 - [DEBUG] roundtrip time:399 cost:0 transfer_no:2625 send:0 rcv:21

3月 26 19:53:32.07 - [DEBUG] roundtrip time:22429 cost:22172 transfer_no:2596 send:0 rcv:129

3月 26 19:53:32.07 - [DEBUG] Conn session:oufynrkk conn:231 Peer Close:recv closed

3月 26 19:53:32.07 - [DEBUG] Conn session:oufynrkk conn:231 stop:peer close

3月 26 19:53:32.07 - [DEBUG] Conn session:oufynrkk conn:231 stop:recv fail.

3月 26 19:53:32.07 - [DEBUG] remove conn_id:231

3月 26 19:53:32.07 - [DEBUG] remove conn_id:231

3月 26 19:53:32.78 - [DEBUG] roundtrip time:399 cost:0 transfer_no:2627 send:0 rcv:21

3月 26 19:53:33.04 - [DEBUG] roundtrip time:354 cost:0 transfer_no:2628 send:0 rcv:21

3月 26 19:53:33.47 - [WARNING] front retry v19.xx-net.net/data?tid=2586

3月 26 19:53:33.47 - [WARNING] front retry v19.xx-net.net/data?tid=2585

3月 26 19:53:33.77 - [WARNING] front retry v19.xx-net.net/data?tid=2587

3月 26 19:53:33.82 - [DEBUG] roundtrip time:24481 cost:24225 transfer_no:2595 send:0 rcv:171

3月 26 19:53:34.07 - [DEBUG] roundtrip time:24130 cost:23808 transfer_no:2597 send:0 rcv:3403

3月 26 19:53:34.27 - [DEBUG] roundtrip time:24029 cost:23721 transfer_no:2598 send:0 rcv:3403

3月 26 19:53:34.47 - [WARNING] roundtrip time:36051 transfer_no:2586 send:538 status:602

3月 26 19:53:34.47 - [WARNING] roundtrip time:36085 transfer_no:2585 send:41 status:602

3月 26 19:53:34.68 - [DEBUG] roundtrip time:23831 cost:23576 transfer_no:2600 send:0 rcv:436

3月 26 19:53:34.73 - [DEBUG] roundtrip time:24179 cost:23919 transfer_no:2599 send:0 rcv:67

3月 26 19:53:34.77 - [WARNING] roundtrip time:36055 transfer_no:2587 send:0 status:602

3月 26 19:53:35.52 - [DEBUG] roundtrip time:24374 cost:24119 transfer_no:2601 send:0 rcv:21

3月 26 19:53:36.72 - [DEBUG] roundtrip time:25273 cost:25017 transfer_no:2602 send:0 rcv:21

3月 26 19:53:37.07 - [DEBUG] roundtrip time:25314 cost:25016 transfer_no:2603 send:0 rcv:21

3月 26 19:53:37.34 - [DEBUG] roundtrip time:25287 cost:25016 transfer_no:2604 send:0 rcv:21

3月 26 19:53:37.63 - [DEBUG] roundtrip time:25271 cost:25014 transfer_no:2605 send:0 rcv:21

3月 26 19:53:37.93 - [DEBUG] roundtrip time:25268 cost:25013 transfer_no:2606 send:0 rcv:21

3月 26 19:53:38.23 - [DEBUG] roundtrip time:25270 cost:25013 transfer_no:2607 send:0 rcv:21

3月 26 19:53:38.53 - [DEBUG] roundtrip time:25266 cost:25011 transfer_no:2608 send:0 rcv:21

3月 26 19:53:38.73 - [DEBUG] roundtrip time:25320 cost:25058 transfer_no:2609 send:41 rcv:21

3月 26 19:53:38.83 - [DEBUG] roundtrip time:25386 cost:25130 transfer_no:2610 send:538 rcv:21

3月 26 19:53:39.12 - [DEBUG] roundtrip time:25374 cost:25032 transfer_no:2611 send:0 rcv:21

3月 26 19:53:39.37 - [DEBUG] roundtrip time:25328 cost:25030 transfer_no:2612 send:0 rcv:21

3月 26 19:53:39.73 - [DEBUG] roundtrip time:25386 cost:25030 transfer_no:2613 send:0 rcv:21

3月 26 19:53:40.04 - [DEBUG] roundtrip time:25390 cost:25030 transfer_no:2614 send:0 rcv:21

3月 26 19:53:40.33 - [DEBUG] roundtrip time:25382 cost:25073 transfer_no:2615 send:0 rcv:21

3月 26 19:53:40.65 - [DEBUG] roundtrip time:25404 cost:25072 transfer_no:2616 send:0 rcv:21

3月 26 19:53:40.83 - [DEBUG] roundtrip time:25281 cost:25023 transfer_no:2617 send:0 rcv:21

3月 26 19:53:41.23 - [DEBUG] roundtrip time:25380 cost:25067 transfer_no:2618 send:0 rcv:21

3月 26 19:53:43.44 - [WARNING] front retry v19.xx-net.net/data?tid=2592

3月 26 19:53:43.75 - [WARNING] front retry v19.xx-net.net/data?tid=2593

3月 26 19:53:44.05 - [WARNING] front retry v19.xx-net.net/data?tid=2594

3月 26 19:53:44.44 - [WARNING] roundtrip time:36009 transfer_no:2592 send:538 status:602

3月 26 19:53:44.75 - [WARNING] roundtrip time:36014 transfer_no:2593 send:0 status:602

3月 26 19:53:45.06 - [WARNING] roundtrip time:36018 transfer_no:2594 send:0 status:602

3月 26 19:54:00.64 - [WARNING] front retry v19.xx-net.net/data?tid=2621

3月 26 19:54:01.64 - [WARNING] roundtrip time:36093 transfer_no:2621 send:56 status:602

3月 26 19:54:04.16 - [DEBUG] start report_stat

3月 26 19:54:04.48 - [INFO] api:/report_stat success t:324

3月 26 19:54:05.84 - [DEBUG] roundtrip time:30460 cost:17283 transfer_no:2634 send:54 rcv:66

3月 26 19:54:05.84 - [DEBUG] rtt:13177 speed:0 trace: 0:connect, 9214:init, 1:head, 638:head end, 48171:request, 30458:Res,:0, processed:1, transfered:212, sni:serveclock.org

3月 26 19:54:05.84 - [DEBUG] task trace:0:start_request,0:get_task(0),0:get_worker(0):2804:14d:aef9:3::e,0:h1_req,0:h1_req_sended,30458:response_begin,0:h1_get_head,0:h1_finish[SP:4],0:get_response,:0

3月 26 19:54:07.16 - [WARNING] front retry v19.xx-net.net/data?tid=2626

3月 26 19:54:08.16 - [WARNING] roundtrip time:36086 transfer_no:2626 send:27 status:602

3月 26 19:54:08.89 - [WARNING] front retry v19.xx-net.net/data?tid=2629

3月 26 19:54:09.40 - [WARNING] front retry v19.xx-net.net/data?tid=2630

3月 26 19:54:09.81 - [WARNING] front retry v19.xx-net.net/data?tid=2631

3月 26 19:54:09.89 - [WARNING] roundtrip time:36066 transfer_no:2629 send:64 status:602

3月 26 19:54:10.11 - [WARNING] front retry v19.xx-net.net/data?tid=2632

3月 26 19:54:10.40 - [WARNING] roundtrip time:36018 transfer_no:2630 send:1203 status:602

3月 26 19:54:10.42 - [WARNING] front retry v19.xx-net.net/data?tid=2633

3月 26 19:54:10.81 - [WARNING] roundtrip time:36080 transfer_no:2631 send:151 status:602

3月 26 19:54:11.11 - [WARNING] roundtrip time:36073 transfer_no:2632 send:0 status:602

3月 26 19:54:11.42 - [WARNING] roundtrip time:36076 transfer_no:2633 send:0 status:602

3月 26 19:54:15.41 - [WARNING] front retry v19.xx-net.net/data?tid=2635

3月 26 19:54:16.41 - [WARNING] roundtrip time:36003 transfer_no:2635 send:54 status:602

3月 26 19:54:20.71 - [DEBUG] roundtrip time:20332 cost:20073 transfer_no:2636 send:51 rcv:66

3月 26 19:54:25.77 - [DEBUG] roundtrip time:25083 cost:24779 transfer_no:2637 send:0 rcv:66

3月 26 19:54:25.88 - [DEBUG] roundtrip time:24894 cost:24640 transfer_no:2638 send:0 rcv:73

3月 26 19:54:26.44 - [DEBUG] roundtrip time:250 cost:0 transfer_no:2656 send:0 rcv:21

3月 26 19:54:26.66 - [DEBUG] roundtrip time:25364 cost:25077 transfer_no:2639 send:0 rcv:21

3月 26 19:54:26.92 - [DEBUG] roundtrip time:25330 cost:25076 transfer_no:2640 send:0 rcv:21

3月 26 19:54:27.24 - [DEBUG] roundtrip time:25348 cost:25075 transfer_no:2641 send:0 rcv:21

3月 26 19:54:27.55 - [DEBUG] roundtrip time:25355 cost:25071 transfer_no:2642 send:0 rcv:21

3月 26 19:54:27.86 - [DEBUG] roundtrip time:25360 cost:25073 transfer_no:2643 send:0 rcv:21

3月 26 19:54:28.14 - [DEBUG] roundtrip time:25342 cost:25059 transfer_no:2644 send:0 rcv:21

3月 26 19:54:28.43 - [DEBUG] roundtrip time:25325 cost:25071 transfer_no:2645 send:0 rcv:21

3月 26 19:54:28.79 - [DEBUG] roundtrip time:25386 cost:25062 transfer_no:2646 send:0 rcv:21

3月 26 19:54:28.98 - [DEBUG] roundtrip time:25279 cost:24962 transfer_no:2647 send:0 rcv:129

3月 26 19:54:28.99 - [DEBUG] Conn session:oufynrkk conn:216 Peer Close:recv closed

3月 26 19:54:28.99 - [DEBUG] Conn session:oufynrkk conn:216 stop:recv fail.

3月 26 19:54:28.99 - [DEBUG] remove conn_id:216

3月 26 19:54:28.99 - [DEBUG] Conn session:oufynrkk conn:216 stop:peer close

3月 26 19:54:28.99 - [DEBUG] remove conn_id:216

3月 26 19:54:29.33 - [DEBUG] roundtrip time:25320 cost:25060 transfer_no:2648 send:0 rcv:21

3月 26 19:54:29.64 - [DEBUG] roundtrip time:25327 cost:25065 transfer_no:2649 send:0 rcv:21

3月 26 19:54:29.93 - [DEBUG] roundtrip time:25318 cost:25064 transfer_no:2650 send:0 rcv:21

3月 26 19:54:30.23 - [DEBUG] roundtrip time:25321 cost:25061 transfer_no:2651 send:0 rcv:21

3月 26 19:54:30.53 - [DEBUG] roundtrip time:25316 cost:25061 transfer_no:2652 send:0 rcv:21

3月 26 19:54:30.73 - [DEBUG] roundtrip time:25335 cost:25081 transfer_no:2653 send:51 rcv:21

3月 26 19:54:31.13 - [DEBUG] roundtrip time:25437 cost:25079 transfer_no:2654 send:0 rcv:21

3月 26 19:54:31.65 - [DEBUG] roundtrip time:5769 cost:5517 transfer_no:2655 send:56 rcv:66

3月 26 19:54:36.75 - [DEBUG] roundtrip time:7761 cost:7507 transfer_no:2657 send:27 rcv:66

3月 26 19:54:41.77 - [DEBUG] roundtrip time:12477 cost:12201 transfer_no:2658 send:0 rcv:66

3月 26 19:54:46.77 - [DEBUG] roundtrip time:15393 cost:15141 transfer_no:2659 send:51 rcv:66

3月 26 19:54:56.73 - [DEBUG] roundtrip time:582 cost:0 transfer_no:2691 send:0 rcv:21

3月 26 19:54:56.97 - [DEBUG] roundtrip time:525 cost:0 transfer_no:2692 send:0 rcv:21

3月 26 19:54:57.97 - [DEBUG] roundtrip time:11197 cost:10650 transfer_no:2660 send:0 rcv:66

3月 26 19:54:58.05 - [DEBUG] roundtrip time:666 cost:0 transfer_no:2693 send:51 rcv:21

3月 26 19:54:58.25 - [DEBUG] roundtrip time:564 cost:0 transfer_no:2694 send:0 rcv:21

3月 26 19:55:02.92 - [DEBUG] roundtrip time:15824 cost:15565 transfer_no:2661 send:0 rcv:66

3月 26 19:55:04.48 - [DEBUG] start report_stat

3月 26 19:55:04.75 - [INFO] api:/report_stat success t:267

3月 26 19:55:19.95 - [DEBUG] roundtrip time:25311 cost:25056 transfer_no:2686 send:0 rcv:21

3月 26 19:55:20.55 - [DEBUG] roundtrip time:25309 cost:25055 transfer_no:2688 send:0 rcv:21

3月 26 19:55:20.85 - [DEBUG] roundtrip time:25311 cost:25054 transfer_no:2689 send:0 rcv:21

3月 26 19:55:22.47 - [WARNING] front retry v19.xx-net.net/data?tid=2662

3月 26 19:55:22.78 - [WARNING] front retry v19.xx-net.net/data?tid=2663

3月 26 19:55:23.08 - [WARNING] front retry v19.xx-net.net/data?tid=2664

3月 26 19:55:23.39 - [WARNING] front retry v19.xx-net.net/data?tid=2665

3月 26 19:55:23.47 - [WARNING] roundtrip time:36078 transfer_no:2662 send:0 status:602

3月 26 19:55:23.69 - [WARNING] front retry v19.xx-net.net/data?tid=2666

3月 26 19:55:23.78 - [WARNING] roundtrip time:36082 transfer_no:2663 send:0 status:602

3月 26 19:55:24.00 - [WARNING] front retry v19.xx-net.net/data?tid=2667

3月 26 19:55:24.08 - [WARNING] roundtrip time:36085 transfer_no:2664 send:0 status:602

3月 26 19:55:24.31 - [WARNING] front retry v19.xx-net.net/data?tid=2668

3月 26 19:55:24.39 - [WARNING] roundtrip time:36088 transfer_no:2665 send:0 status:602

3月 26 19:55:24.61 - [WARNING] front retry v19.xx-net.net/data?tid=2669

3月 26 19:55:24.70 - [WARNING] roundtrip time:36093 transfer_no:2666 send:0 status:602

3月 26 19:55:24.82 - [WARNING] front retry v19.xx-net.net/data?tid=2670

**Comment by xxnet** [comment]
​太多602了，不太正常。

你把 状态页的其他地方贴出来，顺便把 cloudflare和cloudfront的日志都贴一下

**Comment by gjbg1989** [comment]
heroku前端和TLS_Relay 前端一直都是False—— me too 😂

**Comment by xxnet** [comment]
​等客户端的代码稳定了，就去解决这两个front

**Comment by Zhangjin1993** [comment]
## @xxnet 有的时候挺快的，但有时候就很不稳定，看这状态页，cloudflare好像正常，cloudfront是不是有问题，成功数好像都是0 
### cloudflare日志
trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,170:end send left body,23365:h2_get_head,0:get_response,0:h2_finish[SP:139874],:0

Mar 27 12:11:56.800 - [DEBUG] POST mostlygood.ga/data?tid=1783 status:200 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,174:end send left body,59:h2_get_head,0:get_response,0:h2_finish[SP:28422],:0

Mar 27 12:12:04.768 - [DEBUG] POST mostlygood.ga/data?tid=1760 status:200 trace:0:start_request,0:get_task(6),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,254:end send left body,25033:h2_get_head,0:get_response,:0

Mar 27 12:12:05.454 - [DEBUG] POST mostlygood.ga/data?tid=1761 status:200 trace:0:start_request,0:get_task(3),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,177:end send left body,22289:h2_get_head,0:get_response,:0

Mar 27 12:12:05.655 - [DEBUG] POST mostlygood.ga/data?tid=1762 status:200 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,172:end send left body,22457:h2_get_head,0:get_response,0:h2_finish[SP:4735952],:0

Mar 27 12:12:05.668 - [DEBUG] POST mostlygood.ga/data?tid=1763 status:200 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,233:end send left body,22149:h2_get_head,0:get_response,:0

Mar 27 12:12:06.067 - [DEBUG] POST mostlygood.ga/data?tid=1764 status:200 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,206:end send left body,22536:h2_get_head,0:get_response,:0

Mar 27 12:12:06.271 - [DEBUG] POST mostlygood.ga/data?tid=1765 status:200 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.97,0:h2_req,0:start send header,0:start send left body,0:end send left body,181:end send left body,22462:h2_get_head,0:get_response,:1
### cloudfront日志
Mar 27 11:46:54.907 - [DEBUG] create_ssl update ip:13.32.154.125 time:780 h2:1 sni:www.kaneva.com, host:

Mar 27 11:47:04.354 - [INFO] Adjust scan thread num from 0 to 5

Mar 27 11:47:05.359 - [DEBUG] create_ssl update ip:54.182.195.8 time:958 h2:1 sni:bible-with-strong-039-s-dictionary-and-concordanc-1.soft32.com, host:

Mar 27 11:47:06.577 - [INFO] scan_ip add ip:54.239.219.15 time:301 h2:1

Mar 27 11:47:06.578 - [INFO] remove_slowest_ip:216.137.52.130 handshake_time:108, fails:1

Mar 27 11:47:12.348 - [INFO] scan_ip add ip:13.33.88.25 time:236 h2:1

Mar 27 11:47:12.349 - [INFO] remove_slowest_ip:54.182.195.8 handshake_time:773, fails:0

Mar 27 11:47:31.988 - [INFO] scan_ip add ip:54.192.233.174 time:89 h2:1

Mar 27 11:47:31.989 - [INFO] remove_slowest_ip:13.32.154.125 handshake_time:760, fails:0

Mar 27 11:47:33.782 - [INFO] scan_ip add ip:52.222.152.61 time:234 h2:0

Mar 27 11:47:33.782 - [INFO] Adjust scan thread num from 5 to 0

Mar 27 11:47:33.782 - [INFO] remove_slowest_ip:54.230.36.30 handshake_time:413, fails:0

Mar 27 11:48:03.721 - [DEBUG] POST /report_stat status:200 trace:0:start_request,0:get_task(126),0:get_worker(0):13.32.154.125,0:h2_req,1:start send header,0:start send left body,0:end send left body,492:h2_get_head,0:get_response,:0

Mar 27 11:49:52.749 - [DEBUG] 54.182.195.8 worker close:status 403

Mar 27 11:49:52.749 - [DEBUG] 54.182.195.8 close:status 403

Mar 27 11:49:52.749 - [WARNING] POST /data?tid=280 status:403 trace:0:start_request,0:get_task(169),0:get_worker(0):54.182.195.8,0:h2_req,0:start send header,0:start send left body,0:end send left body,336:h2_get_head,0:get_response,:0

Mar 27 11:49:54.929 - [DEBUG] create_ssl update ip:54.192.233.174 time:1908 h2:0 sni:dev-archive-cf.kiswe.com, host:

Mar 27 11:51:03.797 - [DEBUG] 13.32.154.125 worker close:ConnectionReset:ZeroReturnError()

Mar 27 11:51:03.798 - [DEBUG] 13.32.154.125 close:ConnectionReset:ZeroReturnError()

Mar 27 11:51:04.849 - [INFO] Adjust scan thread num from 0 to 1

Mar 27 11:51:05.638 - [DEBUG] connect 52.222.152.61 fail:error('check sni:goldmania.vteximg.com.br fail, alt_names:()',)

Mar 27 11:51:05.638 - [DEBUG] report_connect_fail:52.222.152.61

Mar 27 11:51:06.742 - [INFO] scan_ip add ip:52.84.0.54 time:212 h2:1

Mar 27 11:51:06.743 - [INFO] Adjust scan thread num from 1 to 5

Mar 27 11:51:06.744 - [INFO] remove_slowest_ip:52.222.152.61 handshake_time:234, fails:1

Mar 27 11:51:08.385 - [DEBUG] create_ssl update ip:13.33.88.25 time:725 h2:0 sni:cdn2.bitwire.co, host:

Mar 27 11:51:14.784 - [INFO] scan_ip add ip:52.85.246.8 time:259 h2:0

Mar 27 11:51:14.784 - [INFO] scan_ip add ip:52.222.233.3 time:256 h2:0

Mar 27 11:51:14.785 - [INFO] Adjust scan thread num from 5 to 1

Mar 27 11:51:14.786 - [INFO] remove_slowest_ip:13.33.88.25 handshake_time:725, fails:0

Mar 27 11:51:14.786 - [INFO] remove_slowest_ip:54.192.233.174 handshake_time:589, fails:0

Mar 27 11:51:26.715 - [INFO] scan_ip add ip:54.230.98.8 time:226 h2:0

Mar 27 11:51:26.716 - [INFO] Adjust scan thread num from 1 to 0

Mar 27 11:51:26.716 - [INFO] remove_slowest_ip:13.33.46.167 handshake_time:411, fails:0

Mar 27 12:11:26.687 - [DEBUG] create_ssl update ip:52.84.0.54 time:826 h2:1 sni:trustacademy-secure.edcastcloud.com, host:

Mar 27 12:11:30.377 - [WARNING] 13.33.88.25 h1_request:Exception('time out',) inactive_time:22 task.timeout:5

Mar 27 12:11:30.378 - [WARNING] 13.33.88.25 trace: 0:connect, 754:init, 1216963:request,:5001, processed:0, transfered:0, sni:cdn2.bitwire.co

Mar 27 12:11:30.378 - [DEBUG] POST center.xx-net.net/report_stat response_fail:retry timeout:5

Mar 27 12:11:30.378 - [DEBUG] 13.33.88.25 worker close:down fail

Mar 27 12:11:30.378 - [WARNING] POST /report_stat status:601 trace:0:start_request,0:get_task(1402),0:get_worker(0):13.33.88.25,0:h1_req,0:h1_req_sended,5000:get_response,:0

Mar 27 12:11:30.378 - [DEBUG] 13.33.88.25 close:down fail

Mar 27 12:14:27.005 - [DEBUG] 52.84.0.54 worker close:ConnectionReset:ZeroReturnError()

Mar 27 12:14:27.005 - [DEBUG] 52.84.0.54 close:ConnectionReset:ZeroReturnError()

Mar 27 12:14:33.302 - [INFO] Adjust scan thread num from 0 to 5

Mar 27 12:14:34.123 - [DEBUG] create_ssl update ip:54.230.98.8 time:776 h2:1 sni:elklandartcenter.smugmug.com, host:


![image](https://user-images.githubusercontent.com/33750515/37946424-d71988d6-31b7-11e8-9c50-aff966a085d2.png)
![image](https://user-images.githubusercontent.com/33750515/37946458-036164ea-31b8-11e8-94e8-3645b2c60920.png)

**Comment by xxnet** [comment]
​看上去是GAE模块的问题，已经修复这个问题。
今天发一个新版

**Comment by Zhangjin1993** [comment]
更新之后，快多了，非常感谢
