### ISSUE TITLE
升级到3.11.2以后的版本，APPID丢失，监听端口默认变回127.0.0.1

### ISSUE THREAD

**Issue by shanzigang** [XX-net/XX-Net#10217]
基于Docker容器运行的xx-net ，升级到3.11.2以后的版本，APPID丢失，监听端口默认变回127.0.0.1（原本是局域网代理，设置为0.0.0.0），由于无法在配置界面内更改，容器的配置文件又不知道保存在哪里，无法手动更改。

**Comment by gjbg1989** [comment]
3.10.5开始，不再支持 manual.ini 及 config.ini，而支持 config.json
APPID丢失，监听端口默认变回127.0.0.1（原本是局域网代理，设置为0.0.0.0）——
http://127.0.0.1:8085/?module=gae_proxy&menu=config 配置——填写——保存即存于 config.json
http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页(帮助) ON 即存局域网代理参数于 config.yaml

**Comment by shanzigang** [comment]
可能我没有说清楚，我不是要修改“允许远程访问控制页”，而是要通过xx-net为局域网内其它设备提供代理，因此要修改的是“代理监听端口”，但似乎无法在界面内进行设置。谢谢！

**Comment by gjbg1989** [comment]
试试就知，查看操作前后 config.yaml 的变化😱

**Comment by gjbg1989** [comment]
允许远程访问控制页(帮助) 点击“帮助” https://github.com/XX-net/XX-Net/wiki/AllowRemoteConnectToWebControl

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页(帮助)——ON
查看：http://127.0.0.1:8085/?module=launcher&menu=status 模块。。。

**Comment by SeaHOH** [comment]
现在不支持远程修改这个参数，请重新打包。
