### ISSUE TITLE
使用新版后无法更改谷歌账户密码

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#10216]
在新版正常开启的状态下，不知道什么原因无法修改谷歌账户密码，谷歌账户修改密码界面网页都能正常显示但输入新密码后，点确认【更改密码】按钮后没有反应。这是怎么回事？
![screenhunter_04 mar 26 21 36](https://user-images.githubusercontent.com/19446969/37910291-bd24582a-313f-11e8-8a51-f1609feeef72.png)

**Comment by xxnet** [comment]
​试试老版是否就可以

**Comment by gjbg1989** [comment]
试试：3.10.4以后版本，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 
1、自动调整扫描线程数(帮助)OFF 
2、检查 IP——开始。。。待延时减小、连接池增大后再更改谷歌账户密码
或 退回3.10.4，2、。。。

**Comment by gjbg1989** [comment]
使用新版后无法更改谷歌账户密码——貌似GAE代理卡顿的锅😂
😱怎样消除GAE代理卡顿？#10184 9、貌似3.10.4及以前版本无需：不时 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始。。。或：扫描设置——自动调整扫描线程数(帮助)OFF？观察IP延时、连接池的变化😂

**Comment by 80068** [comment]
@xxnet 回来我再对比测试一下新版和老版。去年12月时用的XX-net版本中没有这个问题。2017年9-11月的版本也没有这个情况。

**Comment by 80068** [comment]
@gjbg1989 好的，回来我用新版与老版本对比测试一下

**Comment by gjbg1989** [comment]
V3.4.0 on 31 Aug 2017 
V3.7.10 on 7 Nov 2017 GAE check ipv6 is ok
GAE auto scan ipv6
GAE IPv6 no lost ip.
V3.9.2 on 21 Dec 2017
V3.10.4 on 17 Feb 2018——貌似止于此版，开始于：V3.10.5  20 days ago 重构 GAE_PROXY 代码😂

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10218#issuecomment-376367131

**Comment by jamesdengtm** [comment]
前几天改密码也这种情况。我用的是3.8.5版，改不了密码。后来用别的代理才改成。

**Comment by SeaHOH** [comment]
关闭后仍可回复
