### ISSUE TITLE
我的ip扫描线程数为零，这属于正常现象吗？

### ISSUE THREAD

**Issue by hblin94** [XX-net/XX-Net#10214]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.6.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:7389
network-status: OK
connected-link: new:2 used:0
worker: h1:11 h2:0
scan-ip-thread-num: 0
ip-quality: 751
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
xxnet-version: 3.6.6——更新到3.8.4或3.10.4
#10184

**Comment by hblin94** [comment]
虽然ip扫描线程数为零，但是还是可以上网

**Comment by gjbg1989** [comment]
ip扫描线程数为零——IP够多、自动调整的，貌似正常

**Comment by hblin94** [comment]
"ip扫描线程数为零——IP够多、自动调整的，貌似正常',目前确实比较正常，YouTube可以480p，ip数6500左右，不过好像比早上少了（早上7000多）

**Comment by hblin94** [comment]
@gjbg1989 我的ip一直在掉啊

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37967742-de2ae36c-31fe-11e8-9877-277526d4043b.png)

**Comment by SeaHOH** [comment]
正常
