### ISSUE TITLE
为啥一直在部署呢

### ISSUE THREAD

**Issue by zl612** [XX-net/XX-Net#10211]
![33849651c2b0159211c531664092551](https://user-images.githubusercontent.com/29365019/37891338-8e40bd66-3106-11e8-880d-f84f872372b7.png)

**Comment by gjbg1989** [comment]
建议用3.10.4版本操作

**Comment by SeaHOH** [comment]
有没有弹窗？

**Comment by VessCHN** [comment]
3.11.9也出现了这个问题，求解决

**Comment by SeaHOH** [comment]
重复一遍：有没有弹窗？

请确认浏览器不会阻止弹窗。
