### ISSUE TITLE
3.11.4 youtube视频无法播放，但是降到3.10.4就可以。

### ISSUE THREAD

**Issue by xx-gw** [XX-net/XX-Net#10210]
3.11.4 用googlo.com等一切正常，YouTube也可正常搜索浏览。
但是，就是不能播放youtube页面的主视频。好像视频数据一直都过不来，而页面的其他部分都正常。
  
`
Mar 26 14:56:38.955 - [INFO] remove_slowest_ip:2a00:1b30:8800::c handshake_time:638, fails:1

Mar 26 14:56:40.515 - [DEBUG] 2607:f798:14:41::c worker close:idle timeout

Mar 26 14:56:40.516 - [DEBUG] 2607:f798:14:41::c close:idle timeout

Mar 26 14:56:40.992 - [INFO] scan_ip add ip:2a00:1450:4012::23 time:527 h2:0

Mar 26 14:56:40.995 - [INFO] Adjust scan thread num from 3 to 2

Mar 26 14:56:40.996 - [INFO] remove_slowest_ip:2607:f8b0:4002:c03::63 handshake_time:637, fails:1

Mar 26 14:56:41.048 - [DEBUG] create_ssl update ip:2607:f8b0:4012:b::12 time:795 h2:0 sni:sound.sing.org, host:fffregister11.appspot.com

Mar 26 14:56:42.406 - [INFO] scan_ip add ip:2a00:1b30:8800::f time:1939 h2:0

Mar 26 14:56:42.409 - [INFO] Adjust scan thread num from 2 to 3

Mar 26 14:56:42.410 - [INFO] remove_slowest_ip:2a00:1b30:8800::f handshake_time:1939, fails:0

Mar 26 14:56:42.841 - [DEBUG] 2001:4e8:0:b045::12 worker close:idle timeout

Mar 26 14:56:42.842 - [DEBUG] 2001:4e8:0:b045::12 close:idle timeout

Mar 26 14:56:45.154 - [INFO] scan_ip add ip:2a00:1450:4002:1a::c time:469 h2:0

Mar 26 14:56:45.157 - [INFO] Adjust scan thread num from 3 to 2

Mar 26 14:56:45.157 - [INFO] remove_slowest_ip:2001:ee0:3204:2::11 handshake_time:634, fails:1

Mar 26 14:56:45.404 - [DEBUG] 2607:f798:14:43::e worker close:idle timeout

Mar 26 14:56:45.404 - [DEBUG] 2607:f798:14:43::e close:idle timeout

Mar 26 14:56:45.574 - [DEBUG] 2607:f798:14:42::e worker close:idle timeout

Mar 26 14:56:45.574 - [DEBUG] 2607:f798:14:42::e close:idle timeout

Mar 26 14:56:45.877 - [DEBUG] 2600:802:b00:1::c worker close:idle timeout

Mar 26 14:56:45.878 - [DEBUG] 2600:802:b00:1::c close:idle timeout

Mar 26 14:56:46.057 - [DEBUG] create_ssl update ip:2a00:1450:4001:51::7 time:2928 h2:0 sni:quantity-country.net, host:

Mar 26 14:56:46.813 - [DEBUG] 2a02:8400:0:10e::e worker close:idle timeout

Mar 26 14:56:46.814 - [DEBUG] 2a02:8400:0:10e::e close:idle timeout

Mar 26 14:56:47.829 - [DEBUG] create_ssl update ip:2600:803:f10:1::f time:772 h2:0 sni:lockissuehoney.net, host:fffregister19.appspot.com

Mar 26 14:56:48.054 - [DEBUG] 2607:f8b0:401d:1c::c worker close:idle timeout

Mar 26 14:56:48.054 - [DEBUG] 2607:f8b0:401d:1c::c close:idle timeout

Mar 26 14:56:48.652 - [DEBUG] 2600:806:260::f worker close:idle timeout

Mar 26 14:56:48.653 - [DEBUG] 2600:806:260::f close:idle timeout

Mar 26 14:56:48.685 - [DEBUG] 2001:4958:300:500::d worker close:idle timeout

Mar 26 14:56:48.686 - [DEBUG] 2001:4958:300:500::d close:idle timeout

Mar 26 14:56:48.836 - [DEBUG] 2607:f8b0:400a:3::f worker close:idle timeout

Mar 26 14:56:48.837 - [DEBUG] 2607:f8b0:400a:3::f close:idle timeout

Mar 26 14:56:50.848 - [DEBUG] 2a0b:880:1:1::f worker close:idle timeout

Mar 26 14:56:50.849 - [DEBUG] 2a0b:880:1:1::f close:idle timeout 
`

**Comment by gjbg1989** [comment]
标题👍

**Comment by xx-gw** [comment]
感恩xx-net团队！高调的话不用说，这是大贡献！

**Comment by xxnet** [comment]
​会不会是使用公共appid的影响？

**Comment by SeaHOH** [comment]
关闭后仍可回复
