### ISSUE TITLE
电信网络下登陆不上x-Tunnel，一直显示“正在登录，请稍侯。。。”

### ISSUE THREAD

**Issue by ZhangFanruo** [XX-net/XX-Net#10222]
校园网可以但是电信宽带不行，怎么解决

* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
校园网可以但是电信宽带——各用各的XX-Net
IPv6隧道正常——GAE正常—— x-Tunnel 正常😂参考：#10184

**Comment by ZhangFanruo** [comment]
什么叫各用各的xx-net啊 我平时只有个x-tunnel的，但是只有校园网可以用，我也没有开通ipv6

**Comment by gjbg1989** [comment]
2地各用各的XX-Net，用IPv6隧道并不要求开通ipv6😂

**Comment by gjbg1989** [comment]
IPv6隧道正常——GAE才正常—— x-Tunnel 也才正常

**Comment by ZhangFanruo** [comment]
也就是如果电信的ipv6端口不开放的话 x-tunnel就不能用是吗

**Comment by gjbg1989** [comment]
貌似无关？正如现在不知道我的宽带 ipv6 端口开放与否，但：x-Tunnel 正常，因GAE正常🤣；想GAE正常，IPv6隧道必须正常😱

**Comment by ZhangFanruo** [comment]
但是我在学校 gae也用不了 但是可以用x-tunnel 这是怎么回事

**Comment by gjbg1989** [comment]
没经历😂点击“帮助”
http://127.0.0.1:8085/?module=launcher&menu=config 代理——局域网代理 (帮助)

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6

**Comment by xxnet** [comment]
​X-Tunnel 有多条通道，只要一条能通就能用。
GAE_proxy是其中一条通道，GAE_Proxy目前依赖IPv6

**Comment by ZhangFanruo** [comment]
属性 | 值
-- | --
服务监听地址 | SOCKS5://127.0.0.1:1080
请求处理数量 | 512
响应时间 | 9999
Roundtrip num | 0
Slow roundtrip | 0
Resend | 0
Timeout roundtrip | 0
速度 | Up: 0.0 B/s / Down: 0.0 B/s
Total use | Up: 0.0 B / Down: 0.0 B

**Comment by ZhangFanruo** [comment]
属性 | 值
-- | --
Score | False
Success num | 0
Fail num | 0
Worker num | 0
Total use | Up: 0.0 B / Down: 0.0 B

**Comment by ZhangFanruo** [comment]
GAE front
 Cloudflare front
Heroku front
都是false

**Comment by AnyWAT** [comment]
退出XX-Net，X_Tunnel 目录下除了 client.json 都删除？

**Comment by ZhangFanruo** [comment]
删除后cloudflare可用，评分335，过几分钟又不可用，重启xx-net客户端之后又陷入之前的无法登陆的状况，cloudflare又变成false

**Comment by AnyWAT** [comment]
😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by SeaHOH** [comment]
试试新测试版 3.11.10

定期删除 ***_ip_list.txt，重启。这是个笨办法。

关闭后仍可回复
