### ISSUE TITLE
运行出现错误No module named distutils

### ISSUE THREAD

**Issue by thrushxiao** [XX-net/XX-Net#10221]
由于3.11.3版本出现莫名奇妙的ipv6错误（之前ipv6是没问题的），于是我重新下载3.10.4版本，复制data文件夹至新XX-Net
运行start.vbs无反应，检查data/launcher/launcher.log文件，提示错误为

> Mar 27 09:49:06.455 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=No module named distutils.version traceback:<traceback object at 0x034E6EB8>

在code/default/python27/1.0/lib/distutils只中有一个名为version.py的文件
重新运行3.11.3，可以成功（当然还是有ipv6问题

求解，感谢

**Comment by thrushxiao** [comment]
@gjbg1989 
1、data/downloads/version.txt ，内容删除改为，3.10.4
2、移走cert文件夹
3、移走CA.crt，复制CAkey.pem并改名为CA.crt
(正确标准的处理步骤吧？

至于pythonw.exe这个进程我根本没找到。。。之后重启了一下
再运行start.vbs还是无事发生，distutils依然报错

**Comment by thrushxiao** [comment]
@gjbg1989 
1、修改version.txt，内容为3.10.4（我搜索XX-Net里所有的version.txt，把他们都改了）
2、移走cert文件夹
3、移走CA.crt，复制CAkey.pem并改名为CA.crt
（以上是正确且标准的处理流程？

至于pythonew.exe，我根本没找到这个进程，于是重启一下
然后再运行start.vbs，无事发生，依旧报错distutils

**Comment by gjbg1989** [comment]
未运行3.11.3的情况下，也可将其目录 code\defalut  改成 code\3.11.3，改 code\version.txt 内容成 3.11.3 退出XX-Net 再启即运行3.11.3

**Comment by thrushxiao** [comment]
@gjbg1989 事情变得越发诡异了起来=。=
我之前确实没看懂，直接在3.10.4版本改的，顺手彻底删掉了3.11.3（保留了data这是早上8:47我发帖之前备份的（没修改过cert，ca.crt之类的）

可是。。。现在重新下载3.11.3，解压，粘贴data文件夹，不修改任何文件。运行.vbs，依然distutils报错

将code中的default改成3.11.4，version.txt内容修改，也报错

复制3.10.4的default并改名，同时修改version.txt，也报错

感觉突然就不正常了呀（迷之体质？

**Comment by gjbg1989** [comment]
既然有 data 的备份，清空原XX-Net的所有目录、文件，解压3.11.3到原位置，复制 data 到原位置，运行3.11.3不应报错（不管IPv6正常与否）。然后
![image](https://user-images.githubusercontent.com/13290970/37945613-93041e1c-31b3-11e8-91bd-825b94dcb504.png)
或：
![image](https://user-images.githubusercontent.com/13290970/37945585-83091710-31b3-11e8-8c30-81edcb8bcc15.png)

**Comment by thrushxiao** [comment]
@gjbg1989 呃很遗憾。。。事实上，就算我现在重新下载最新3.11.3，重新解压， 运行.vbs都会报distutils的错误
有什么自检的方法吗，比如解决distutils这个模块的问题需要下载个xx，或者做一些操作可以初始化回到最开始弹出防火墙警告什么的（反正我备份了data。。。

**Comment by gjbg1989** [comment]
运行XX-Net 就有 pythonw.exe 进程——首先解决——找到这个进程，终止它？

**Comment by gjbg1989** [comment]
在code/default/python27/1.0/lib/distutils只中有一个名为version.py的文件——清空后再解压，有几个文件？

**Comment by thrushxiao** [comment]
@gjbg1989 
查了很多遍，确实没看见疑似pythonw.exe的进程（直到我打开spyder，才看到，再结束进程运行vbs也没什么用，我怀疑之前没有pythonw.exe的原因是我根本没运行起来XX-Net。。。
另外那个distutils的文件夹中确实只有一个version.py的文件，我发帖之前就查过，3.11.3和3.10.4都是，然后发现不是自己这少了某些文件才搞不懂错误原因的

**Comment by thrushxiao** [comment]
项目里倒是有个0字节的__init__.py，但是是0字节，下载就没有这个文件，应该不是这个的原因吧

**Comment by thrushxiao** [comment]
@gjbg1989  我在distutils文件夹里补上一个空的__init__.py，再运行vbs，launcher.log有新花样了，大佬来看看

> Mar 27 14:52:57.433 - [INFO] use build-in openssl lib
Mar 27 14:52:57.457 - [WARNING] get_version_fail in update_from_github
Mar 27 14:52:57.457 - [INFO] start XX-Net get_version_fail
Mar 27 14:52:57.457 - [DEBUG] start confirm_xxnet_exit
Mar 27 14:52:58.476 - [DEBUG] good, xxnet:8085 clear!
Mar 27 14:52:58.476 - [DEBUG] finished confirm_xxnet_exit
Mar 27 14:52:58.521 - [WARNING] get_version_fail in update_from_github
Mar 27 14:52:58.568 - [WARNING] start module script not exist:D:\XX-Net\code\3.10.4\gae_proxy\start.py
Mar 27 14:52:58.568 - [INFO] start gae_proxy time cost:0 ms
Mar 27 14:52:58.966 - [ERROR] start module x_tunnel fail:No module named gae_proxy.local
Mar 27 14:52:58.968 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net\code\3.10.4\x_tunnel\start.py", line 14, in <module>
    import local.client as client
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_handler.py", line 12, in <module>
    import proxy_session
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_session.py", line 14, in <module>
    from gae_proxy.local import check_local_network
ImportError: No module named gae_proxy.local

Mar 27 14:52:58.968 - [ERROR] launcher except:ImportError('No module named gae_proxy.local',)
Mar 27 14:52:58.968 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\start.py", line 230, in <module>
    main()
  File "D:\XX-Net\code\3.10.4\launcher\start.py", line 207, in main
    module_init.start_all_auto()
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net\code\3.10.4\x_tunnel\start.py", line 14, in <module>
    import local.client as client
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_handler.py", line 12, in <module>
    import proxy_session
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_session.py", line 14, in <module>
    from gae_proxy.local import check_local_network
ImportError: No module named gae_proxy.local

Mar 27 14:52:58.973 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x029224B8>
Mar 27 14:52:58.973 - [ERROR] stop module gae_proxy fail:'proc'
Mar 27 14:52:58.973 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 81, in stop
    proc_handler[module]["proc"].terminate()  # Sends SIGTERM
KeyError: 'proc'

Mar 27 14:52:58.973 - [ERROR] stop module x_tunnel fail:'imp'
Mar 27 14:52:58.973 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Mar 27 14:52:58.973 - [INFO] begin to exit web control
Mar 27 14:52:58.978 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x028B8418>

**Comment by thrushxiao** [comment]
@gjbg1989 我在distutils文件夹里补上一个空的__init__.py，再运行vbs，launcher.log有新花样了，大佬来看看

Mar 27 14:52:57.433 - [INFO] use build-in openssl lib
Mar 27 14:52:57.457 - [WARNING] get_version_fail in update_from_github
Mar 27 14:52:57.457 - [INFO] start XX-Net get_version_fail
Mar 27 14:52:57.457 - [DEBUG] start confirm_xxnet_exit
Mar 27 14:52:58.476 - [DEBUG] good, xxnet:8085 clear!
Mar 27 14:52:58.476 - [DEBUG] finished confirm_xxnet_exit
Mar 27 14:52:58.521 - [WARNING] get_version_fail in update_from_github
Mar 27 14:52:58.568 - [WARNING] start module script not exist:D:\XX-Net\code\3.10.4\gae_proxy\start.py
Mar 27 14:52:58.568 - [INFO] start gae_proxy time cost:0 ms
Mar 27 14:52:58.966 - [ERROR] start module x_tunnel fail:No module named gae_proxy.local
Mar 27 14:52:58.968 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net\code\3.10.4\x_tunnel\start.py", line 14, in <module>
    import local.client as client
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_handler.py", line 12, in <module>
    import proxy_session
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_session.py", line 14, in <module>
    from gae_proxy.local import check_local_network
ImportError: No module named gae_proxy.local

Mar 27 14:52:58.968 - [ERROR] launcher except:ImportError('No module named gae_proxy.local',)
Mar 27 14:52:58.968 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\start.py", line 230, in <module>
    main()
  File "D:\XX-Net\code\3.10.4\launcher\start.py", line 207, in main
    module_init.start_all_auto()
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net\code\3.10.4\x_tunnel\start.py", line 14, in <module>
    import local.client as client
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_handler.py", line 12, in <module>
    import proxy_session
  File "D:\XX-Net\code\3.10.4\x_tunnel\local\proxy_session.py", line 14, in <module>
    from gae_proxy.local import check_local_network
ImportError: No module named gae_proxy.local

Mar 27 14:52:58.973 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x029224B8>
Mar 27 14:52:58.973 - [ERROR] stop module gae_proxy fail:'proc'
Mar 27 14:52:58.973 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 81, in stop
    proc_handler[module]["proc"].terminate()  # Sends SIGTERM
KeyError: 'proc'

Mar 27 14:52:58.973 - [ERROR] stop module x_tunnel fail:'imp'
Mar 27 14:52:58.973 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\3.10.4\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Mar 27 14:52:58.973 - [INFO] begin to exit web control
Mar 27 14:52:58.978 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x028B8418>

**Comment by xxnet** [comment]
​再下载一次，检查文件大小

**Comment by gjbg1989** [comment]
直到我打开spyder——有其它程序相伴XX-Net？就没见有 pythonw.exe 进程？😱 
![image](https://user-images.githubusercontent.com/13290970/37953973-f09eba50-31d6-11e8-96ce-a26f3ffc5a35.png)
😂不识代码的纯用户老白，从多次观察几个版本（其它文件）、文件时间上判断，程序原有及运行时生成的文件各半，事后查看 .zip，果然。。。
![image](https://user-images.githubusercontent.com/13290970/37954234-bf69b876-31d7-11e8-9a21-d074ae41b7f1.png)
视“检查 config.yaml ”而不见？

**Comment by thrushxiao** [comment]
@gjbg1989 额哈哈，config.yaml用记事本打开之后，有个路径，指向的是3.11.3，修改为3.10.4依然报错。其他的我就不知道该怎么查了，这个文件只在data中，每个人都不同，里面有个uid的

至于相伴程序我觉得跟这个无关，因为之前pythonw.exe这个进程都没启动过，我是启动了别的程序才确认了pythonw.exe长得什么样。。。

有个小请求，大佬把你的XXNet打个压缩包发我一份行不？没有data的那种，我想看看是不是我的文件有问题了（虽然我这是直接下载的，但是上面依然出了点小插曲~
大佬要是有空，不妨发个压缩包？邮箱513569127@qq.com

**Comment by thrushxiao** [comment]
@xxnet 这个检查文件大小是不是查SHA1值啊？github上的sha值和我下载到的安装包用cmd的命令
> certutil -hashfile 文件名 SHA1
得出的结果确实不对
这里是github上的SHA值是SHA1吗？
或者是我这里网络有问题所以丢包了。。（这应该不能吧

**Comment by xxnet** [comment]
​简单下载，解压，就可以运行的，Windows下没有太多差别，因为python库是统一的。
问题应该就出在下载的zip文件不完整上。

下载最新 3.11.5 试试，大小是14075298

**Comment by thrushxiao** [comment]
@xxnet 很抱歉，换成最新的3.11.5也是出现错误，来自launcher.log

> Mar 27 18:20:58.197 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=No module named distutils.version traceback:<traceback object at 0x02C11328>

**Comment by gjbg1989** [comment]
至于相伴程序我觉得跟这个无关，因为之前pythonw.exe这个进程都没启动过——与你相反，无相伴程序、启动XX-Net 即有 pythonw.exe 进程，XX-Net 版本好几个，怎么整都没像你的有关 distutils 错误。😱

**Comment by gjbg1989** [comment]
XX-Net 有错误，不舍得先停止相伴的其它程序。。。——与解决问题的一般逻辑完全相背😂

**Comment by thrushxiao** [comment]
@gjbg1989 大佬你搞错啦，我不管做什么都无法让xxnet相关的pythonw.py出现在任务管理器中，跟停不停其他程序完全无关，因为它根本没出现过

**Comment by xxnet** [comment]
​请用start.bat 启动，把日志贴上来

**Comment by thrushxiao** [comment]
@xxnet 先一个dos窗口快速闪过，然后另一个dos窗口快速闪过，录屏暂停得到结果。。。跟launcher.log日志基本一样。。。
`Mar`` 27 19:18:35.245 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=No module named distutils.version traceback:<traceback object at 0x03413580>

**Comment by xxnet** [comment]
先执行 cmd，打开命令行窗口，切换到XX-Net目录下，再执行start.bat看看

**Comment by thrushxiao** [comment]
@xxnet 在命令行窗口执行了start.bat，闪过一个dos窗口，在命令行窗口中，可以看到结果，

> “d:\XX-Net\start.vbs” console

然后查看launcher.log，依然no moudle named distutils错误

**Comment by gjbg1989** [comment]
贴 config.yaml

**Comment by thrushxiao** [comment]
![m un9g 02 _hhd30jh vwm](https://user-images.githubusercontent.com/37820966/37967579-71168060-31fe-11e8-99f1-9b0576537184.png)
config.yaml的内容为
![64eo_ 5r_q y8 qi d n dh](https://user-images.githubusercontent.com/37820966/37967627-95ab82a4-31fe-11e8-8a06-8d4c805bd66f.png)
横线处是我觉得可以修改的部分
@gjbg1989

**Comment by thrushxiao** [comment]
![64eo_ 5r_q y8 qi d n dh](https://user-images.githubusercontent.com/37820966/37967689-b7c802b8-31fe-11e8-8e65-62ddd019d21f.png)
config.yaml内容如上，横线部分中间修改过，由于现在是重新下载的3.11.5就又改回default了（code下也是default

至于目录截图你说的应该是这个吧
![k xbhd 2a w98a9 4 xn](https://user-images.githubusercontent.com/37820966/37967758-e77cc746-31fe-11e8-9edc-427bc43b3246.png)
@gjbg1989

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37967864-316868c4-31ff-11e8-9126-00f28b194aac.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37967914-52e3383a-31ff-11e8-9a9f-0f7821949694.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37967975-847a9712-31ff-11e8-9402-aa2c359576b4.png)

**Comment by gjbg1989** [comment]
php_proxy。。。😂有效？
![image](https://user-images.githubusercontent.com/13290970/37968422-a2366cbc-3200-11e8-8443-f7a4cab566e7.png)

**Comment by thrushxiao** [comment]
@gjbg1989 

不知道抽了什么风，上传图片失败，我来口述
d;\XX-Net\code\default\python27\1.0\lib\distutiles
中只有一个version.py文件（虽然项目中，这里文件夹里有个__init__.py但是是0字节所以下载压缩包的时候没有这个

另外那个php_proxy，我不是很懂这个，只知道现在连xxnet都无法启动，别的有效无效都没用啦

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37969022-55d5a962-3202-11e8-85b4-a91ddeeba698.png)

**Comment by gjbg1989** [comment]
简化，试试：
既然有 data 的备份，清空原XX-Net的所有目录、文件，解压XX-Net-3.11.3.zip到原位置，复制 data 到原位置，删除或改名 config.yaml，管理权限运行 start.vbs ，或许需要重新设置，3.11.3不应报错（不管IPv6正常与否）。然后
![image](https://user-images.githubusercontent.com/13290970/37969688-eeba09a6-3203-11e8-8bb3-b8b44437f602.png)

**Comment by gjbg1989** [comment]
貌似3.11.3 与 default 必须统一到程序目录（前面2选1）？——没有此说😭即图中3.11.3 与 default 正确

**Comment by xxnet** [comment]
这个​data目录应该很久以前的了，才会有php_proxy。

抛开这个data，另外找个干净的空目录，解压后执行

**Comment by thrushxiao** [comment]
@xxnet @gjbg1989 原来是d:\，重新在f:\并且没加data文件夹，运行vbs之后在自动生成的文件夹中依然是
uncaught Exception, type=<type 'exceptions.ImportError'> value=No module named distutils.version traceback:<traceback object at 0x02617EE0>

**Comment by gjbg1989** [comment]
没加data文件夹——😱管理权限运行vbs

**Comment by thrushxiao** [comment]
@gjbg1989 .vbs文件没有以管理员运行的选项，我用管理员运行了start.bat，结果还是那个distutils

**Comment by gjbg1989** [comment]
解压XX-Net-3.10.4.zip到桌面，自建目录 data，复制
![image](https://user-images.githubusercontent.com/13290970/37972837-c8b3102e-320b-11e8-9b07-c70657f4c98f.png)
到 data，运行

**Comment by gjbg1989** [comment]
再不济，CCleaner.exe 清理系统后。。。

**Comment by xxnet** [comment]
​会不会是什么杀毒软件在后面搞鬼？

**Comment by caofengzi** [comment]
有可能，如果用360它會毫不客氣的幹掉。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10248

**Comment by SeaHOH** [comment]
检测 code\default\python27\1.0\lib\distutils 下是否有 `__init__.py` 和 `version.py`。
