### ISSUE TITLE
用xx-net访问证书错误的网址，会被替换成被信任的GoAgent的证书，这有风险吗？

### ISSUE THREAD

**Issue by zjengjie** [XX-net/XX-Net#1022]
比如访问著名的 12306

**Comment by xxnet** [comment]
问题不大，因为首先要欺骗Google域名解析，这不容易。
另外一个，GAE代理本身的安全性定位并不高，如果要高安全性，请使用其他代理，比如ShadowSocks

2015-09-15 10:21 GMT+08:00 zjengjie <notifications@github.com>:

**Comment by dartall** [comment]
另外把自带的证书（若有的话）删除，再重新生成，会稍微安全点。

**Comment by zjengjie** [comment]
嗯，了解了，自己注意下就好。
