### ISSUE TITLE
xndroid如何关闭

### ISSUE THREAD

**Issue by jamesblunt** [XX-net/XX-Net#10229]
在 nexus 5X上如何关闭掉，关掉软件还是开着代理。

**Comment by gjbg1989** [comment]
莫非：http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页(帮助)OFF——除了XX-Net 本机，谁也别再用？😂

**Comment by SeaHOH** [comment]
https://github.com/XndroidDev/Xndroid
