### ISSUE TITLE
GAE 无法完全加载Google Calendar

### ISSUE THREAD

**Issue by summerdaydream** [XX-net/XX-Net#10224]
走GAE访问Google calender时，可以加载网页框架，但是无法加载日历中的事件。SwitchOmega显示有failed resources.
x-Tunnel和赛风可以完整加载，前段时间教育网ipv6也可以直连Google calendar。加载成功一次之后，再使用GAE访问，可以正常加载日历事件并且可以编辑。

**Comment by gjbg1989** [comment]
试试用回3.10.4？#10184

**Comment by summerdaydream** [comment]
3.10.4是一样的

**Comment by xxnet** [comment]
​ 请升级到 3.11.5，已经解决这个问题

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/10227
