### ISSUE TITLE
Google plus只能显示第一页，滚动到下面无法加载更多内容

### ISSUE THREAD

**Issue by griefforyou** [XX-net/XX-Net#10220]
如题，其它网址一切正常。

开发者工具控制台错误：
https://www.gstatic.com/_/boq/_/js/k=boq.PlusAppUi.zh_CN.JSLeqH4d9bk.O/ck=b…/excm=squarediscoverhome,_b,_tp/ed=1/rs=AGLTcCMYVF5myPK8mhyD-e3Wb2TRpAIFWw Failed to load resource: net::ERR_EMPTY_RESPONSE
content.js:1 Uncaught IndexSizeError: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
2https://play.google.com/log?format=json&authuser=0 Failed to load resource: net::ERR_EMPTY_RESPONSE
https://notifications.google.com/_/scs/social-static/_/js/k=boq.Notificatio…CAACA/rt=j/d=0/excm=home,_b,_tp/ed=1/rs=AGLTcCP08H3Uhl7hGKPwyu9iJvJDYDf0XQ Failed to load resource: net::ERR_EMPTY_RESPONSE
2https://www.gstatic.com/_/boq/_/js/k=boq.PlusAppUi.zh_CN.JSLeqH4d9bk.O/ck=b…/excm=squarediscoverhome,_b,_tp/ed=1/rs=AGLTcCMYVF5myPK8mhyD-e3Wb2TRpAIFWw Failed to load resource: net::ERR_EMPTY_RESPONSE
2https://play.google.com/log?format=json&authuser=0 Failed to load resource: net::ERR_EMPTY_RESPONSE
https://www.gstatic.com/_/boq/_/js/k=boq.PlusAppUi.zh_CN.JSLeqH4d9bk.O/ck=b…/excm=squarediscoverhome,_b,_tp/ed=1/rs=AGLTcCMYVF5myPK8mhyD-e3Wb2TRpAIFWw Failed to load resource: net::ERR_EMPTY_RESPONSE

**Comment by gjbg1989** [comment]
试试：用回3.10.4 😂#10184

**Comment by xxnet** [comment]
​找到代码了，已经解决。
今天发一个版本

**Comment by griefforyou** [comment]
更新到3.11.6，故障依旧

**Comment by xxnet** [comment]
​请再刷新一遍，我这边验证是正常的。

看开发者工具控制台错误，把出错对应的url 在GAE的日志中找，有没有异常日志
