### ISSUE TITLE
不同版本的IP延迟！

### ISSUE THREAD

**Issue by gitxxnet2018** [XX-net/XX-Net#10226]
![01](https://user-images.githubusercontent.com/37608157/37949914-3affc03e-31c9-11e8-9079-fade64087973.PNG)
![02](https://user-images.githubusercontent.com/37608157/37949919-3cfaf818-31c9-11e8-89af-e6fd581b47b9.PNG)

**Comment by vert404** [comment]
![default](https://user-images.githubusercontent.com/32587285/37950091-e36303a8-31c9-11e8-9d42-491f7345c07b.png)
3.10.4最好用，YouTube 740p都可以看

**Comment by gjbg1989** [comment]
纯粹从延迟数字上看，新版3.11.5处于3.10.4与3.11.4之间

**Comment by gjbg1989** [comment]
RT @iyouport_news 微软将于5月1日禁止来自Skype，Xbox，Office和其他服务的'冒犯性语言'和'不适当的内容'，声称它有权审查您的私人数据！！你以为Skype是私人领地？微软告诉你没门儿，他可以监管你和朋友的通话记录 1/ https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K … pic.twitter.com/47awPdI5Q5
RT @iyouport_news 2/ 微软说的“冒犯性语言”究竟是什么鬼？你的交流对象都没觉得是冒犯，微软凭什么要决定什么是冒犯？……纯粹是审查的托辞。 微软也可能阻止 电子邮件，文件共享或即时消息，以执行这些条款，他们说“我们可能因任何原因删除或拒绝发布您的内容” https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K …
