### ISSUE TITLE
开始尚未建立连接  后来是你可以尝试 开启IPv6 或 使用X-Tunnel。

### ISSUE THREAD

**Issue by zk19920423** [XX-net/XX-Net#10223]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3355.0 Safari/537.36
xxnet-version: 3.11.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:939 ipv4:0 ipv6:438
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

使用的是公司网   怀疑是网络问题  或者是个人电脑网络设置问题   但是不知道怎么解决，求帮助

**Comment by gjbg1989** [comment]
#10184

**Comment by zk19920423** [comment]
enable_ipv6.bat    disable_ipv6.bat 
我的没有这些东西啊

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
