### ISSUE TITLE
[发布] 发布 3.11.5  

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#10227]
## 新版改进：
* Google Plus 和calander等网站，访问不完整
* GAE代理性能提升
* X-Tunnel 使用GAE代理时，稳定性提升
* bug: Mac 平台上 CPU 100%, 内存无限上升
* bug: 网络不通时，ip不停的掉。
* Ubuntu 启动无法进入设置页面

已推送测试版更新，请测试反馈。

**Comment by stevegao2002** [comment]
开发者辛苦了！请问什么时候开发x-tunnel的移动手机版本，已购买了套餐，谢谢。

**Comment by MacSur** [comment]
这么快的速度，谢谢，辛苦了。。。

上个版本真的不好用，谢谢！！！顶！！！

**Comment by gjbg1989** [comment]
Chrome 插件 Smart-Router 模式：双Fail 貌似无解😂

**Comment by freesd** [comment]
终于好了，一直以为自己的网络问题导致的呢

**Comment by xxnet** [comment]
​大重构，确实成本很高，不过收获也很大，性能提高、资源消耗下降，代码精简，方便继续改进。

**Comment by zhangbin0917** [comment]
感谢，Ubuntu下配置页面终于打开了

**Comment by summerdaydream** [comment]
辛苦了，马上测试使用

**Comment by Rurikou** [comment]
辛苦了，3.11.5版本在部署appid时，google.appengine.tools.appengine_rpc返回http 409，不知道什么情况。。

**Comment by gjbg1989** [comment]
@Rurikou 🤣或许试试3.10.4？http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP，待延时、连接池足够好后全局GAE下部署？

**Comment by wankuizhuankan** [comment]
新版能720p油管了，提升巨大。老版才144

**Comment by gjbg1989** [comment]
😂因人、机而异？https://github.com/XX-net/XX-Net/issues/10226#issuecomment-376492354

**Comment by xxnet** [comment]
​@Rurikou
 409 错误，似乎和appcfg的版本有关
  下面是google出来的：
  https://issuetracker.google.com/issues/35896320#c10

 下面是GoAgent 的：
https://goproxy0.github.io/discuss_history/goagent/detail_id=433.html

**Comment by wicatu** [comment]
Mar 27   - [DEBUG] domain gae to www.m.com:80 except:AttributeError("'ConnectManager' object has no attribute 'gae_conn_pool'",)

Mar 27   - [INFO] domain www.m.com:80 socks

Mar 27  - [DEBUG] domain socks to www.m.com:80 except:XTunnelNotRunning()

Mar 27  - [INFO] domain ['gae', 'socks'] to www.m.com:80 fail

Mar 27  - [DEBUG] domain gae to www.m:80 except:AttributeError("'ConnectManager' object has no attribute 'gae_conn_pool'",)

3.11.5

**Comment by Rurikou** [comment]
@xxnet @gjbg1989 确实是版本问题，将版本降低为3.11.3解决了，感谢🤣

**Comment by xxnet** [comment]
@sss
  代码没有清理干净，影响智能工作，看来需要马上发一个新版了。

**Comment by dongbeak36** [comment]
@gjbg1989 
Chrome 插件 Smart-Router 模式：*.deja.com 引发双Fail 
这个问题在XX-NET选择智能路由后，Chrome插件SwitchyOmega中，直接选择XX-NET连接模式，就好了。
![qq 20180327214103](https://user-images.githubusercontent.com/31989402/37971153-d4042cb4-3207-11e8-918d-d2809fa45616.png)
![qq 20180327214223](https://user-images.githubusercontent.com/31989402/37971164-d9aa0864-3207-11e8-84d4-59a2c17718fc.png)

**Comment by gjbg1989** [comment]
在XX-NET选择（全局）智能路由——理论上对应Chrome插件SwitchyOmega中的“系统代理”😂

**Comment by dongbeak36** [comment]
习惯自己设置：
![qq 20180327215117](https://user-images.githubusercontent.com/31989402/37971700-2c0a1ecc-3209-11e8-864d-e469e51a7392.png)
(*^__^*) 嘻嘻……

**Comment by gjbg1989** [comment]
上图近似在XX-NET选择智能路由的结果，只是没勾选下面的对勾😂

**Comment by dongbeak36** [comment]
那就在XX-NET选择智能路由后，Chrome插件SwitchyOmega中，选择XX-NET自动切换，心理会爽点 O(∩_∩)O
![qq 20180327220541](https://user-images.githubusercontent.com/31989402/37972669-6775f8e4-320b-11e8-836f-d1f298f83b96.png)
![qq 20180327220620](https://user-images.githubusercontent.com/31989402/37972682-6cbdfe46-320b-11e8-9ceb-600a82323ce5.png)

~

**Comment by dongbeak36** [comment]
哇塞，XX-NET智能路由，Chrome插件SwitchyOmega，选择XX-NET自动切换，这个好啊！
走gae的网页SwitchyOmega显示：
![qq 20180327221749](https://user-images.githubusercontent.com/31989402/37973285-bb350096-320c-11e8-9dd9-9933ed0e42e1.png)
直连的网页SwitchyOmega显示：
![qq 20180327221755](https://user-images.githubusercontent.com/31989402/37973352-dec5bf96-320c-11e8-90a3-60591be0a6fd.png)

一目了然啊！
O(∩_∩)O~

**Comment by gjbg1989** [comment]
@dongbeak36 代理法则推广已启动🤣

**Comment by 80068** [comment]
正在测试...

**Comment by xxnet** [comment]
​发布 3.11.6
修复：
1. 智能路由无法使用GAE_proxy
2. 智能路由导致CPU 100%
3. 智能路由下，GAE不支持的请求，会转向XTunnel

https://github.com/XX-net/XX-Net/releases/tag/3.11.6

**Comment by wicatu** [comment]
老问题解决，再探再报:
手机端通过局域网共享出的0.0.0.0:8086设置后上网，
部分应用通过smartrouter可使用GAE_proxy，
部分应用samrtrouter日志显示
Mar 28  - [DEBUG] host:youtubei.googleapis.com:443 do gae
Mar 28  - [DEBUG] domain host:youtubei.googleapis.com:443 try gae, GetReqTimeout:71
Mar 28  - [WARNING] domain domain:play.googleapis.com fail:SslWrapFail()
Mar 28  - [WARNING] domain domain:mesu.apple.com fail:SslWrapFail()

**Comment by xxnet** [comment]
fail:SslWrapFail 是客户端不接受GAE的证书，某些APP是这样的比如Android的Twitter客户端，目前只能通过浏览器方式。

GetReqTimeout 是等待客户端发来的请求超时，不清楚什么原因

**Comment by gjbg1989** [comment]
如何为 Windows 10 UWP 应用设置代理 - https://zhuanlan.zhihu.com/p/29989157

**Comment by imldf** [comment]
圖標右鍵不能選擇全局代理了嗎？衹能選擇衹能代理，但是有時候全局代理還是很有作用的啊。

**Comment by gjbg1989** [comment]
@imldf https://github.com/XX-net/XX-Net/issues/10238 PAC全局代理沒有了，衹能選擇全局PAC衹能代理——貌似说辞不同而已，功能应一样？

**Comment by dongbeak36** [comment]
XX-NET全局智能路由，Chrome插件SwitchyOmega系统代理
![qq 20180328130216](https://user-images.githubusercontent.com/31989402/38009837-ebdcad30-3288-11e8-8337-f8f563dffa3f.png)
XX-NET3.11.6
很棒！

**Comment by xxnet** [comment]
发布 3.11.7
修复：
1. GAE 无法部署appid
2. Xndroid 无法工作

**Comment by yeezylife** [comment]
xxnet 全局智能路由代理 的时候  微软小娜无法正常工作。估计走了GAE路线了。

**Comment by xxnet** [comment]
​可以看智能路由的日志。

可以试试把对应的域名加入智能路由的socks列表中

**Comment by applestone** [comment]
之前MAC上3.87版本通过添加manual.ini文件可以实现共享翻墙，现在新的版本是否不支持这个功能了？添加manual.ini后貌似无效，应该如何解决？

**Comment by xxnet** [comment]
​系统菜单，设置->允许远程连接 就可以了
