### ISSUE TITLE
IP越来越少

### ISSUE THREAD

**Issue by scljy** [XX-net/XX-Net#10228]
前段时间是1001，昨天开始变成501，今天只有480左右，是被封了，还是什么原因？

**Comment by gjbg1989** [comment]
貌似程序默认上限值不同而已。#10148 二楼

**Comment by goalkeeper24** [comment]
确实，我也发现了，只是程序上限问题？

**Comment by xxnet** [comment]
​是的，请升级到 3.11.5，还是保留500个ip，性能有提高

**Comment by winters-z** [comment]
但前面 3000 是满的，500 也是满的 ，现在只有100多，然后还在下降，延迟到1000多了

**Comment by hbsxwhb** [comment]
我的也是掉到40个了

**Comment by gjbg1989** [comment]
试试：嫌有效IP少或延时大，增大“最大扫描线程数”，关闭“自动调整扫描线程数”，貌似从3.10.5版本开始，不时手动检查IP——http://127.0.0.1:8085/?module=gae_proxy&menu=advanced

**Comment by pyyii** [comment]
最新版3.11.7 有效IP数只有100多个  延迟1000多
