### ISSUE TITLE
请教smart route 显示xx-net 状态，连接尚未建立

### ISSUE THREAD

**Issue by jessicapd** [XX-net/XX-Net#10233]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7600-SP0
os-system: Windows
os-version: 6.1.7600
os-release: 7
os-detail: Version:6-1; Build:7600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3403 ipv4:5 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 515
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10227#issuecomment-376542909 @dongbeak36 法则：
XX-NET自身选择：全局通过智能路由代理，Chrome插件SwitchyOmega 选择：GAE自动切换，保证
proxy_state: Fail
ca_state: Fail——二者变正常😂

**Comment by gjbg1989** [comment]
#10184 贴运行 netsh int ipv6 show teredo 文字结果（无需IP地址的2行）

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
