### ISSUE TITLE
3.11.3版本如果开启自动扫描的话，会有很高的IP延迟，希望后续能更新

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#10236]
一、3.11.3版本如果开启自动扫描的话，会有很高的IP延迟，希望后续能更新；
二、自从更新之后，IP数越来越少了，不知道为什么；
![image](https://user-images.githubusercontent.com/37856464/38006002-d47fbc80-3275-11e8-989a-413490222358.png)
![image](https://user-images.githubusercontent.com/37856464/38006014-de5d2f30-3275-11e8-865f-76a09968a0d8.png)

**Comment by gjbg1989** [comment]
试试最新3.10.6
3.11.3版本如果开启自动扫描。。。——说法不对，是打开“自动调整扫描线程数”，既是开关，关闭时正常，应没有“希望后续能更新”一说？貌似3.10.4以后版本都得关闭😂
自从更新之后，IP数越来越少了，不知道为什么——程序默认IP上限不同以往而已，参考 #10184 二楼

**Comment by milanthree** [comment]
如果程序默认IP修改之后，增加了IP上限，会不会对系统性能有影响？

**Comment by gjbg1989** [comment]
貌似用户设置优选于程序默认
