### ISSUE TITLE
经常会出现连接服务器失败：session server login fail, code:2 msg:no quota

### ISSUE THREAD

**Issue by kirite** [XX-net/XX-Net#10234]
经常连上一会就会出现这个，然后就要等很长一段时间才能重新连上，并且有时候会出现流量消耗很快的情况，不知道是什么原因

**Comment by xxnet** [comment]
​确定有流量吗？
  请把你的X-Tunnel 发 xxnet.dev@gmail.com

**Comment by kirite** [comment]
意思是连接服务器失败的原因是因为没有流量了吗》？

**Comment by kirite** [comment]
并且连接速度非常缓慢，一个网页有时候要1分钟才能打开。。也是流量的问题么。。。

**Comment by xxnet** [comment]
​X-Tunnel的剩余流量、X-Tunnel的状态页、X-Tunnel日志贴出来看
