### ISSUE TITLE
youtube 无响应是怎么回事

### ISSUE THREAD

**Issue by gfvre123** [XX-net/XX-Net#10239]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10235#issuecomment-376737942

**Comment by gfvre123** [comment]
只出现了youtube的图标，下面全是空白
![image](https://user-images.githubusercontent.com/37858603/38011084-8457a678-328e-11e8-9262-3ca6f708b1b1.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/38013495-e7c82dc8-3297-11e8-850b-6d32d47b1d2a.png)
![image](https://user-images.githubusercontent.com/13290970/38013481-da9f3fba-3297-11e8-941d-81eb99f1e3bd.png)

**Comment by gfvre123** [comment]
我这里ipv6 只有200多，检查ip后，只有几个可用

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP 
3.10.4以后版本关闭“自动调整扫描线程数”😂#10184
