### ISSUE TITLE
新版本如何开启后让页面像老版本那样停在gae状态页

### ISSUE THREAD

**Issue by djay1126** [XX-net/XX-Net#10247]
现在貌似默认启动后显示的是x-tunnel登录页面

**Comment by gjbg1989** [comment]
要求太高？多点一下下😂

**Comment by djay1126** [comment]
@gjbg1989 这要求还算高阿？肯定是哪里代码开启指定到gae改一下就可以实现了的吧...

**Comment by gjbg1989** [comment]
😂就不兴大佬有所考虑，启动控制页即自动登录 x-tunnel ？

**Comment by djay1126** [comment]
答非所问了吧...可能也有人只用gae所以想修改首页呢？个人个性化修改并不影响他人使用呀。只求知道方法的大佬抽空能告知下而已。

**Comment by xxnet** [comment]
​关闭X-Tunnel模块就好了

**Comment by djay1126** [comment]
@xxnet 谢谢！果然可以了！
