### ISSUE TITLE
求助，更新到最新版以后无法打开，双击后提示系统找不到指定的文件

### ISSUE THREAD

**Issue by mogwaiwxg** [XX-net/XX-Net#10248]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
修改 code\version.txt 内容为版本号？

**Comment by mogwaiwxg** [comment]
@gjbg1989 您好，感谢解答，我按照您说的修改之后，倒是不会弹出“找不到指定的文件”的提示，但是双击之后没有任何反应，请问这应该怎么办呢？

**Comment by gjbg1989** [comment]
操作系统版本？

**Comment by mogwaiwxg** [comment]
@gjbg1989  win10企业版 64位

**Comment by gjbg1989** [comment]
如自动更新，或许是图标被10操作系统隐藏了，检查是否有进程 pythonw.exe

**Comment by mogwaiwxg** [comment]
@gjbg1989 不是自动更新，是我今天手动点击更新的，之前一直是3.9.6版本的

**Comment by mogwaiwxg** [comment]
进程中也没有pythonw.exe

**Comment by gjbg1989** [comment]
手动点击更新——与XX自动更新貌似一样，或许程序不完整，手动下载、解压覆盖改code\version.txt 内容版本号的目录，再试试。。。

**Comment by gjbg1989** [comment]
保险做法：更新到——通知测试/稳定版，手动下载、解压，然后更改目录 default 为版本号，改  code\version.txt 内容为想运行的版本号。。。

**Comment by mogwaiwxg** [comment]
@gjbg1989 请问您的意思是要我重新下载一个然后重来吗，那么我之前的配置能不能转移到新的里面呢，我不是很懂，麻烦告知一下 谢谢

**Comment by gjbg1989** [comment]
1、自动更新，目录 code 下会有新版本如 a.b.c 及原来的3.9.6（如是以前手动解压的，会是 default ）等目录，如有 default 目录，检查该目录下的 version.txt 即知其版本，将 default 改名为软件的版本号，这样，目录 code 下全是版本号目录。删除目录如 a.b.c
2、手动下载、解压 a.b.c 版到目录 code 的上级目录（即第一次解压的位置），确认全覆盖，完成后改 code\default 为 code\a.b.c ，改 code\version.txt 内容为想运行的、目录下已存在的版本号。。。

**Comment by mogwaiwxg** [comment]
@gjbg1989 非常的感谢，我刚才按照您说的重新弄好了已经 但是有一点疑问的就是为什么IPV6的IP数竟然才有几十个，是什么原因这么的少呢？ 晚安

**Comment by gjbg1989** [comment]
嫌少或延时大，增大“最大扫描线程数”，关闭“自动调整扫描线程数”，不时手动检查IP——http://127.0.0.1:8085/?module=gae_proxy&menu=advanced
