### ISSUE TITLE
新手菜鸟求助

### ISSUE THREAD

**Issue by thomas19940617** [XX-net/XX-Net#10245]
XX-NET 3.11.3

已经按照wiki里的教程下载好xxnet，并已经配置好chrome的代理（gae-proxy自动代理），但仍无法访问外网，日志如下：（讲道理应该可以上，只是网速比较慢才对啊）求各位大佬指点指点，感谢！  

XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; LCJB; rv:11.0) like Gecko
xxnet-version: 3.11.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by thomas19940617** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; LCJB; rv:11.0) like Gecko
xxnet-version: 3.11.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
#10184

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
