### ISSUE TITLE
【3.11.6】 IPV6经常fail

### ISSUE THREAD

**Issue by bitternolis** [XX-net/XX-Net#10249]
teredo服务器连接上了的
只有退出XX-net，断开网络连接后重新使用才能看到IPV6状态OK
然后过一段时间就自动fail了，terodo服务器也没有问题。

**Comment by gjbg1989** [comment]
试试：http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 关闭“自动调整扫描线程数”

**Comment by pendave** [comment]
这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

**Comment by bitternolis** [comment]
关闭自动调整扫描线程数之后好了。
