### ISSUE TITLE
3.10.8的问题

### ISSUE THREAD

**Issue by xdg92** [XX-net/XX-Net#10241]
这几天3.10.8 版本IP延迟不是一般的高，通常在1200以上，最高达1800网页都开不了，视频就更没办法看 了，是版本的问题还是受GFW的影响？如何解决

**Comment by gjbg1989** [comment]
试试3.11.4，建议3.10.4🤣
https://github.com/XX-net/XX-Net/issues/10235

**Comment by xdg92** [comment]
3.10.4出现尚末建立连接或者等待扫描IP建议开启IPV6

**Comment by gjbg1989** [comment]
等待扫描IP——手动检查IP  #10184

**Comment by xdg92** [comment]
3.10.4搞了半天还是等待扫描，没办法只有用3.11.6，但是延迟最高达2000

**Comment by gjbg1989** [comment]
退出XX-Net 重开？

**Comment by xdg92** [comment]
我不仅重开，电脑都重启了

**Comment by xdg92** [comment]
3.11.6延迟还是居高不下呀 ，部署都慢的很

**Comment by gjbg1989** [comment]
3.11.6不如3.10.4😂

**Comment by xdg92** [comment]
3.10.4刚试了，一直不成功，你们用着正常吗？

**Comment by gjbg1989** [comment]
我坏银😱自己不正常还推荐😭

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/38027456-50e59e2e-32c2-11e8-8335-293f58da6a40.png)
![image](https://user-images.githubusercontent.com/13290970/38027522-7afd0b70-32c2-11e8-9280-00c0441b7acf.png)
@xxnet  哈哈，有人心特黑😱

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
