### ISSUE TITLE
appID流量用尽

### ISSUE THREAD

**Issue by zhiganghan** [XX-net/XX-Net#10254]
哪位好人借一个appID临时用一下，今天突然流量用完了，还是第一次遇到。。谢谢。借来注册下即归还

**Comment by xxnet** [comment]
​使用公共appid就好，不填appid就是使用公共的

**Comment by zhiganghan** [comment]
@xxnet 请问那下个月1号就重新又有流量了么？是每月限量么？

**Comment by xxnet** [comment]
​每天下午4点恢复流量

**Comment by zhiganghan** [comment]
@xxnet 哦，谢谢您回答。我还是去注册几个ID备用

**Comment by feimeng2017** [comment]
很奇怪 感觉没怎么用 我这边也显示流量用完了  我12个ID

**Comment by feimeng2017** [comment]
全局默认智能路由.....这个肯定是国内也走代理了

**Comment by xxnet** [comment]
​可以看智能路由的日志，如果走代理了是gae或socks，走直连是direct
