### ISSUE TITLE
两个版本的xx，ip数都在掉

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#10258]
一个是3.10.8，掉到40个了，还在掉。
一个是3.8.4，从2100掉到770，也还在掉。

**Comment by gjbg1989** [comment]
试试：嫌有效IP少、延时大及卡顿，或增大“最大扫描线程数”，（貌似从3.10.5版本开始，）或关闭“自动调整扫描线程数”，不时手动检查IP——http://127.0.0.1:8085/?module=gae_proxy&menu=advanced

**Comment by nly4lov** [comment]
我这两招同时使用，貌似ip数还在掉（3.10.8）

**Comment by gjbg1989** [comment]
😂悄悄话：貌似3.10.4延时偏小且稳定（转换版本后手动检查IP一下）

**Comment by nly4lov** [comment]
哈哈，已经只剩下12个了，还在掉中。

**Comment by gjbg1989** [comment]
😂 https://github.com/XX-net/XX-Net/issues/10262

**Comment by xxnet** [comment]
诊断信息和GAE日志贴来看

**Comment by ablebodied** [comment]
我的也是，不知道为啥teredo一会好一会不行的

**Comment by ncmon** [comment]
这2天防火墙开启封锁功能了 IP大量被封

**Comment by pyyii** [comment]
这几天    IP延迟好高  我这里延迟1200多。3.11.7版本

**Comment by xxnet** [comment]
​哪个城市？
什么操作系统，能否换个电脑试试

**Comment by xxnet** [comment]
​​有反馈说 3.10.4 版本没有这个问题的，请试试是否能解决问题，然后反馈
https://github.com/XX-net/XX-Net/releases/3.10.4

**Comment by asd1219** [comment]
上海移动宽带，今天ipv6状态正常，可以翻墙
估计是移动在测试屏蔽teredo翻墙
暂时先用goproxy+quic翻

**Comment by nly4lov** [comment]
@xxnet 我坚持使用3.10.8呢。
