### ISSUE TITLE
ipv6和ipv4问题

### ISSUE THREAD

**Issue by hzj-777** [XX-net/XX-Net#10253]
这一两个月xxnet时而连的上，时而连不上，ipv6经常断，问题区提供的方法试了个遍，并没有根治，最近突然发现ipv4有了几个ip，而且稳定不掉了。ipv6还是连不上

IPv4 状态 | OK
-- | --
IPv6 状态 | Fail
IPv4 IP数 | 9
IPv6 IP数 | 0
XX-Net 状态 | 工作
IP延迟 | 286

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引
