### ISSUE TITLE
【3.11.6】重启后IPv6就会fail

### ISSUE THREAD

**Issue by LYLuP** [XX-net/XX-Net#10250]
教育网ISATAP隧道和teredo隧道的IP设置按照文档操作后都不正确

**Comment by LYLuP** [comment]
诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.168 Safari/537.36
xxnet-version: 3.11.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by pendave** [comment]
这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

**Comment by SeaHOH** [comment]
这个没法手把手
尝试下 teredo 测试工具 #10328
