### ISSUE TITLE
移动网3.11.6 IPV6经常fail，3.11.4没问题

### ISSUE THREAD

**Issue by xc1988** [XX-net/XX-Net#10251]
突然就fail了...
换回3.11.4就没问题了

**Comment by xxnet** [comment]
​会不会是扫描线程数？
试试降低扫描线程看看

**Comment by xc1988** [comment]
公司电信又没问题..在家移动就会出这种情况

**Comment by gjbg1989** [comment]
公司电信又没问题..在家移动就会出这种情况——或许再到公司也会出状况
建议：公司、家庭各用各的XX，至少 good_ip.txt 有所区分 #10184

**Comment by xibaibai9527** [comment]
同移动网络，同样fail。强行代理所有链接，就连8085端口的页面都打不开了。

**Comment by xxnet** [comment]
​8085端口的页面都打不开了
 这可能是浏览器的问题

**Comment by gjbg1989** [comment]
就连8085端口的页面都打不开了——GAE自动切换，或许得添加 127.0.0.1 走“直接连接”。。。

**Comment by xibaibai9527** [comment]
不是啊，浏览器不代理连接，直连可以打开8085端口，用autoproxy代理全局，就打不开

**Comment by xxnet** [comment]
那问题还是出在浏览器设置上。

用8086智能代理方便

**Comment by xibaibai9527** [comment]
改成8086端口就好了……谢谢
