### ISSUE TITLE
ip扫描需要2小时，ip6为开启状态

### ISSUE THREAD

**Issue by 410919244** [XX-net/XX-Net#10252]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.4793.400 QQBrowser/10.0.745.400
xxnet-version: 3.6.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by 410919244** [comment]
系统ip6是开启状态的，xxnet提示禁用。。。搞不懂

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
