### ISSUE TITLE
不存在的appId?

### ISSUE THREAD

**Issue by jaaaar** [XX-net/XX-Net#10266]
今天一觉睡醒突然这样了，打开xx后,发现appId
那有两行

属性 | 值
-- | --
工作AppID | 你正使用公共AppID。
不存在的AppID | 我的appId
然后就去重新部署,部署提示成功了,当前工作的appId也变成了我自己的appId,但是一搜索就会又变成公共appid,又显示我自己的appId是不存在的，有遇到这个问题的的吗，xx版本是3.10.4

**Comment by gjbg1989** [comment]
😱确认是保存在 config.ini 或 manual.ini 的3.10.4版本？3.10.5开始 http://127.0.0.1:8085/?module=gae_proxy&menu=config 填写——保存，即永久显示在此并保存到 config.json

**Comment by SeaHOH** [comment]
公共 AppID 使用是否正常
还有检查 `https://你的AppID.appspot.com/` 是否返回正确
