### ISSUE TITLE
3.11.3 Wrong password('') GoAgent proxy.ini password is wrong!

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#10263]
我升级到3.11.3登录油管第一次密码错， 第二次联通。登陆google报密码错。3.10.4无此错。
3.8.5曾设置密码。升级到3.10.4密码消失。
https://console.cloud.google.com/debug		gae.py	3.8.5中有密码。
现在无

**Comment by xxnet** [comment]
​新版采用新的配置文件：
  https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
