### ISSUE TITLE
gmail:该网页无法正常运作

### ISSUE THREAD

**Issue by xurz97** [XX-net/XX-Net#10264]
![capture](https://user-images.githubusercontent.com/22641077/38090314-ccda69ec-3394-11e8-912a-a30ec19e4ef8.PNG)
版本3.11.7，访问其他网站都可以，但是gmail上不去，清理了cookie也上不去。但用shadowsocks可以上。
有遇到相同情况的朋友吗

**Comment by xxnet** [comment]
1. 什么浏览器
2. 试试 ​3.11.6

**Comment by xxnet** [comment]
​把访问gmail时的GAE日志发出来看看

**Comment by xurz97** [comment]
`Mar 29 22:31:56.870 - [DEBUG] create_ssl update ip:2607:f8b0:4006:2f::c time:2914 h2:0 sni:study-smile.com, host:

Mar 29 22:31:57.946 - [INFO] DIRECT t:1289 s:264 302 mail.google.com /mail/?auth=8AX18SKI43yJrkMxFwza5U8E4ozRyNUva-HIoeUqtknXptYN5OHebvj3StGpEQLf6hNjlw.

Mar 29 22:31:57.958 - [DEBUG] GAE GET /ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/&ss=1&scc=1<mpl=default<mplcache=2&emr=1&osid=1 from:127.0.0.1:20654

Mar 29 22:31:58.325 - [INFO] GAE t:365 s:421 GET https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/&ss=1&scc=1<mpl=default<mplcache=2&emr=1&osid=1 0:start_request,0:get_task(2),0:get_worker(0):2600:6:400:1::e,0:h1_req,0:h1_req_sended,357:response_begin,0:h1_get_head,0:get_response,2:h1_finish[SP:4388],:3

Mar 29 22:31:58.343 - [DEBUG] DIRECT GET https://mail.google.com/accounts/SetOSID?authuser=0&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F%3Fpli%3D1%26auth%3D8AX18ZvFuSg3yFkbAnbGdiGljNXRycEjBq-yvOg5dIs1DXQZuCkxm2_OYMQGaMfJnemEeQ.&osidt=ALWU2ctLuPx_HHGM9U8tq7j2eHSWzt75UPuhEmmzJ7M8egFnaA0UNyCU39MKHM5Wrnet1aquzFcum377YQiv4yVqTIx4YWXH0OXo2oTDJpgY_ytRG10LF30RSErUaquDX9wFTLZKckeM`
大体情况好像是浏览器反复请求account.google.com和mail.google.com/accounts，二者相互重定向
浏览器是chrome 65.0.3325.181

**Comment by xxnet** [comment]
1. ​试试换浏览器，比如Firefox

2. 试试 3.11.6
  3.11.7 版本有一些小改动，mail.gmail.com是直连，而accounts.google.com 走GAE，怀疑和这有关系。

3. 试试3.11.7版本，设置文件
  data/gae_proxy/config.json 试试下面两种方案：

{
  "hosts_direct":[
    "accounts.google.com",
    "mail.google.com"
  ],

"hosts_gae":[]

}

{
  "hosts_gae":[
    "accounts.google.com",
    "mail.google.com"
  ],

"hosts_direct":[]

}


看哪种有效果

**Comment by KennyLisc** [comment]
{
  "hosts_gae":[
    "accounts.google.com",
    "mail.google.com"
  ],

"hosts_direct":[]

}
这个有效果!
