### ISSUE TITLE
不太懂Smart Router 配置，哪位高手解答一下

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#10269]
通过配置，选择了全局通过智能路由代理；但对规则如何去配置不懂，想请教一下，我现在规则配置那块都是为空的
![image](https://user-images.githubusercontent.com/37856464/38122583-846c318a-3408-11e8-977e-70c834c6b453.png)
![image](https://user-images.githubusercontent.com/37856464/38122606-9b3b5cb0-3408-11e8-9e16-cbdb8621e5d0.png)

**Comment by gjbg1989** [comment]
规则配置那块都是为空的——空且能正常代理，乃最高境界👍

**Comment by milanthree** [comment]
![image](https://user-images.githubusercontent.com/37856464/38122768-bce5ab1c-3409-11e8-983a-1061d2dc20f8.png)
@gjbg1989，哈哈哈，这样嘛，那我就放心了，我现在能正常代理

**Comment by gjbg1989** [comment]
超出程序默认规则的才需要用户在此设置，如浏览器插件自动切换模式内的规则一样对应设置
