### ISSUE TITLE
一直连接尚未建立。 不清楚原因，前几天用还挺好的，期间也没更新版本

### ISSUE THREAD

**Issue by ice0526** [XX-net/XX-Net#10260]
`XX-Net Status:

sys-platform: x86_64, Darwin-14.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64
os-release: 14.4.0
os-detail: Release:10.10.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.6
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:335 ipv4:0 ipv6:160
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 309
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by cloudydayoffice** [comment]
同问+1
一时连接成功，一时连接尚未建立，一时可以尝试 开启IPv6 或 使用X-Tunnel

**Comment by xxnet** [comment]
​可以试试 3.11.7。

另外，可以把GAE的日志贴出来看

**Comment by Wchenghui** [comment]
同问+1，部分gae日志：
Mar 29 17:58:35.507 - [WARNING] network IPv6 fail

Mar 29 17:58:35.507 - [DEBUG] connect 2607:f8b0:4007:1c::c fail:error("conn fail, sni:singmeaning.com, top:didididw.appspot.com e:error(10051, '')",)

Mar 29 17:58:35.507 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2397

Mar 29 17:58:35.507 - [DEBUG] report_connect_fail:2607:f8b0:4007:1c::c

Mar 29 17:58:36.340 - [DEBUG] connect 2404:6800:400c:2::a fail:error("conn fail, sni:chest.till.org, top:bonnyshenvpn-006.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.340 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2398

Mar 29 17:58:36.340 - [DEBUG] report_connect_fail:2404:6800:400c:2::a

Mar 29 17:58:36.347 - [DEBUG] connect 2607:f8b0:400a:2::f fail:error("conn fail, sni:blackemphasis.us, top:appid7-174905.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.347 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2399

Mar 29 17:58:36.347 - [DEBUG] report_connect_fail:2607:f8b0:400a:2::f

Mar 29 17:58:36.348 - [DEBUG] connect 2607:f8b0:400a::17 fail:error("conn fail, sni:buddy.pride.associate.us, top:sfowqd13.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.348 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2400

Mar 29 17:58:36.348 - [DEBUG] report_connect_fail:2607:f8b0:400a::17

Mar 29 17:58:36.352 - [DEBUG] connect 2a00:1450:401e:28::a fail:error("conn fail, sni:, top: e:error(10051, '')",)

Mar 29 17:58:36.352 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2401

Mar 29 17:58:36.352 - [DEBUG] report_connect_fail:2a00:1450:401e:28::a

Mar 29 17:58:36.359 - [DEBUG] connect 2607:f8b0:400a:e::16 fail:error("conn fail, sni:night.wave.beer.ml, top:xx-net-8-183714.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.359 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2402

Mar 29 17:58:36.359 - [DEBUG] report_connect_fail:2607:f8b0:400a:e::16

Mar 29 17:58:36.370 - [DEBUG] connect 2607:f8b0:400a:e::6 fail:error("conn fail, sni:beyondmallface.us, top:xxnet-156.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.370 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2403

Mar 29 17:58:36.370 - [DEBUG] report_connect_fail:2607:f8b0:400a:e::6

Mar 29 17:58:36.370 - [DEBUG] connect 2404:6800:4007:3::16 fail:error("conn fail, sni:tensionemployerstructure.org, top:xxnet-15.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.371 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error("conn fail, sni:piece-cloud.org, top:changzhou-194903.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.371 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2404

Mar 29 17:58:36.371 - [DEBUG] connect 2404:6800:4005:809::201a fail:error("conn fail, sni:bicycle-carry-player.ml, top:metleau01.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.372 - [DEBUG] connect 2607:f8b0:4017:d::a fail:error("conn fail, sni:valuable-apple.org, top:xxnetid123.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail:2404:6800:4007:3::16

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2405

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail:2607:f8b0:400a:1::12

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2406

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail:2404:6800:4005:809::201a

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2407

Mar 29 17:58:36.372 - [DEBUG] report_connect_fail:2607:f8b0:4017:d::a

Mar 29 17:58:36.373 - [DEBUG] connect 2607:f8b0:400a:2::12 fail:error("conn fail, sni:quiet-deep.us, top:xxnet-1678.appspot.com e:error(10051, '')",)

Mar 29 17:58:36.373 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2408

Mar 29 17:58:36.373 - [DEBUG] report_connect_fail:2607:f8b0:400a:2::12

Mar 29 17:58:37.519 - [DEBUG] connect 2404:6800:4007:3::a fail:error("conn fail, sni:monthplastic.us, top:my-project-002-148912.appspot.com e:error(10051, '')",)

Mar 29 17:58:37.519 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2409

Mar 29 17:58:37.519 - [DEBUG] report_connect_fail:2404:6800:4007:3::a

Mar 29 17:58:38.342 - [DEBUG] connect 2607:f8b0:400a:12::8 fail:error("conn fail, sni:friendshipdepositfinding.org, top:chengchongfan9.appspot.com e:error(10051, '')",)

Mar 29 17:58:38.342 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2410

Mar 29 17:58:38.342 - [DEBUG] report_connect_fail:2607:f8b0:400a:12::8

Mar 29 17:58:38.348 - [DEBUG] connect 2607:f8b0:400a:807::200e fail:error("conn fail, sni:kitchen.establishment.ml, top:makrse-1470053659892.appspot.com e:error(10051, '')",)

**Comment by xxnet** [comment]
​楼上的  network IPv6 fail
请看wiki，开通ipv6

**Comment by xpf7622** [comment]
前几个版本，起码能连上，3.11.7 现在连接都成问题了。（IPV6早就设定了）

**Comment by zhiganghan** [comment]
Apr 01 22:18:10.593 - [DEBUG] report_connect_fail IPv6 continue_fail_count:3654

Apr 01 22:18:10.593 - [DEBUG] report_connect_fail:2804:14d:4cf9:3::c

Apr 01 22:18:10.593 - [DEBUG] connect 2800:3f0:4001:13::14 fail:error("conn fail, sni:incident.stop.com, top:lvchengdichan.appspot.com e:error(10065, '')",)

Apr 01 22:18:10.593 - [DEBUG] report_connect_fail IPv6 continue_fail_count:3655

Apr 01 22:18:10.593 - [DEBUG] report_connect_fail:2800:3f0:4001:13::14

Apr 01 22:18:11.150 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 01 22:18:11.150 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Apr 01 22:18:11.150 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Apr 01 22:18:11.150 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Apr 01 22:18:11.151 - [WARNING] send response fail

Apr 01 22:18:11.164 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:9338

更新了3.11.3就连接不上了

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
