### ISSUE TITLE
3.11.7  ok!

### ISSUE THREAD

**Issue by dongbeak36** [XX-net/XX-Net#10261]
![qq 20180329140007](https://user-images.githubusercontent.com/31989402/38072618-bf8cd90e-3359-11e8-873e-8e125223ac8a.png)
O(∩_∩)O~~~

**Comment by lon91ong** [comment]
不知怎么回事，我这里3.11.7用QQ浏览器打不开油管，能打开twitter；用原版Chorme都能打开！
排除是QQ浏览器的问题，之前用3.10.4一切正常！

**Comment by marswow** [comment]
用QQ浏览器的，你不出问题才怪了。别人都是用原生浏览器的，比如chrome、firefox

**Comment by xpf7622** [comment]
为什么我的3.11.7老是不能智能切换，访问国内网站，都要手动指定直接连接才行。

**Comment by dongbeak36** [comment]
@lon91ong 
我自己的感觉，手机端用过QQ浏览器，电脑端也用过，在手机端特别明显的，即使翻了墙，很多网站浏览器也会检测不安全网站、甚至禁止打开。同理电脑端也有这样的情形。
逻辑上说，我们所要连接的网站，是连接前被QQ浏览器云端先检测过的。这种被QQ浏览器阻止的网站，用chrome并不会阻止。chrome阻止危险网站的能力，技术上来说，一定高于QQ浏览器水平的。
所以我们可以简单判断：QQ浏览器的这种检测，是基于GFW需要，而并不是基于网络安全技术建立的。
所以，我个人习惯于用chrome，从不使用QQ浏览器，源于对它的不信任。
简单来说，YouTube就是GFW屏蔽的网址之一，QQ浏览器不得遵循GFW规则么？
就这样……
O(∩_∩)O~

**Comment by lon91ong** [comment]
@marswow @dongbeak36 你们的逻辑无法解释为何3.10.4+QQ浏览器可以正常访问油管，而3.11.7却不行。
@marswow 用原生的Chorme也没必要刷优越感，很low的！
@dongbeak36 无聊的阴谋论在此处行不通！

**Comment by AnyWAT** [comment]
就是要365天360，永远的麻花疼粉丝，坚决不撞南墙不回头😂

**Comment by AnyWAT** [comment]
截止目前，能给大陆推特使用者最清晰的建议就是，不要让后台驻留微信，支付宝，QQ，各种地图，百度全家桶 360全家桶如果是IOS且ID是大陆的，务必关闭icloud，这样自带的输入法才不会泄露你说过的话。如果是android请使用单独的手机在不插卡的情况下使用吧，也可以使用各类pad在不注册厂商id的情况下翻

**Comment by marswow** [comment]
@lon91ong 哪来的优越？这不算哦。
我只是给出我该说的建议，虽然我用的是chrome但是我也推荐了Firefox呀这个你没注意么？

**Comment by lon91ong** [comment]
@marswow 好吧，既然坚持原生，不妨用原生的linux，原生的Android。。。

**Comment by SeaHOH** [comment]
新测试版 3.11.10
关闭后仍可回复
