### ISSUE TITLE
尚未建立连接....

### ISSUE THREAD

**Issue by crazyYellowCat** [XX-net/XX-Net#10268]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5216 ipv4:0 ipv6:5
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by crazyYellowCat** [comment]
ipv4和ipv6的status都是OK但却显示尚未建立连接。

**Comment by crazyYellowCat** [comment]
类型                    : client (Group Policy)
服务器名称              : win1710.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.0.100:64319
外部 NAT 映射    : 223.71.166.245:26283

**Comment by gjbg1989** [comment]
ipv4和ipv6的status都是OK但却显示尚未建立连接。——因为以下：
gws-ip-num: total:5216 ipv4:0 ipv6:5——有效 ipv6:5太少？
worker: h1:0 h2:0——连接池没有
类型 : client (Group Policy)——共4项参数，仅该项为组策略设置，统一到非组策略（？）：
管理权限运行 netsh int ipv6 set teredo enterpriseclient
改为只用 ipv6 增大扫描线程（正常后改回）？

**Comment by gjbg1989** [comment]
😂只求没应😱

**Comment by xpf7622** [comment]
3.11.7 貌似更差了，经常连不上外面。

**Comment by chkjc10** [comment]
我也是，原来都好用的

**Comment by gjbg1989** [comment]
#10184

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
