### ISSUE TITLE
XX-NET突然不能启动

### ISSUE THREAD

**Issue by leoxxnet** [XX-net/XX-Net#10279]
运行XX-NET没反应，重启电脑，关闭360安全卫士和杀毒软件也不能运行。
请大神帮忙！

**Comment by gjbg1989** [comment]
自动更新的？

**Comment by leoxxnet** [comment]
不是，我的版本是3.11.3，后来下了3.11.6也是一样
刚刚看了进程有pythonw.exe
试了一下谷歌也能上，但是http://127.0.0.1:8085/打不开，任务栏也没有XX-NET的图标，
这是什么问题呢？

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/ 打不开——（GAE自动切换模式，）或许需要添加 127.0.0.1 走“直接连接”
任务栏也没有XX-NET的图标——被Win10系统隐藏了新目录下的程序图标而已？

**Comment by leoxxnet** [comment]
我试了GAE自动切换模式和直接连接都不能打开http://127.0.0.1:8085/

**Comment by gjbg1989** [comment]
添加 127.0.0.1 走“直接连接”？右键XX图标是”取消全局代理“？再不行，结束进程  pythonw.exe 重开。。。

**Comment by gjbg1989** [comment]
不是，我的版本是3.11.3，后来下了3.11.6也是一样——如果说你是最新版3.11.7还没有：或许已自动更新但不完整😱
【注意】因网络不稳，建议 http://127.0.0.1:8085/?module=launcher&menu=config 版本——自动升级到: 通知测试/稳定版。在IP延时、连接池均够好的情况下才好点击更新，也需要足够的时间完成。其实手动下载、解压处理来得稳妥且快得多。

**Comment by leoxxnet** [comment]
现在的问题在任务栏看不到XX图标，不能取消全局代理，
麻烦先教我如何恢复xx图标，谢谢！

**Comment by gjbg1989** [comment]
度娘。。。

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，编辑 data\launcher\config.yaml "取消全局代理"
popup_webui: 0, proxy: disable, xxnet_port: 8087}

**Comment by hongkonghot** [comment]
之前有过类似情况，那次是将之前用的data目录直接拷到新版目录中，然后启动就正常了。不知道和你的问题是否一样？可以试一下！

**Comment by caofengzi** [comment]
結束进程有pythonw.exe重新啟動應該好了，另外幹嘛用國產安全程序？它們會偷偷地幹壞事。

**Comment by gjbg1989** [comment]
RT @williamlong 网络安全研究员Paolo Stagno测试了70个VPN提供商，发现其中有16个通过WebRTC泄漏了用户的IP（23％）。 你可以检查你的VPN是否泄漏：http://ip.voidsec.com
RT @williamlong Firefox禁用WebRTC即可防止IP泄漏，方法是：在浏览器上输入：about:config。之后搜索：media.peerconnection.enabled。找到它后双击，将其改成 false 即可。
RT @williamlong Chrome禁用WebRTC可防止IP泄漏，方法是：在Chrome应用商店里，安装一个名为WebRTC Leak Prevent的扩展即可。

**Comment by gjbg1989** [comment]
RT @iyouport_news 微软将于5月1日禁止来自Skype，Xbox，Office和其他服务的'冒犯性语言'和'不适当的内容'，声称它有权审查您的私人数据！！你以为Skype是私人领地？微软告诉你没门儿，他可以监管你和朋友的通话记录 1/ https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K … pic.twitter.com/47awPdI5Q5
RT @iyouport_news 2/ 微软说的“冒犯性语言”究竟是什么鬼？你的交流对象都没觉得是冒犯，微软凭什么要决定什么是冒犯？……纯粹是审查的托辞。 微软也可能阻止 电子邮件，文件共享或即时消息，以执行这些条款，他们说“我们可能因任何原因删除或拒绝发布您的内容” https://plus.google.com/b/104314277918209223775/104314277918209223775/posts/dTKKLEvgb7K …

**Comment by SeaHOH** [comment]
data\launcher\config.yaml
`show_systray: 1`
