### ISSUE TITLE
部署完APPID后，配置APPID的时候总是提示“无效的AppID：especially-for-xx-net2，使用前请先部署。”

### ISSUE THREAD

**Issue by kungfutyf** [XX-net/XX-Net#10278]
![image](https://user-images.githubusercontent.com/12183322/38137308-8b03e01c-3456-11e8-8294-9defbe4b366b.png)
这是部署日志。
![image](https://user-images.githubusercontent.com/12183322/38137353-bfb31968-3456-11e8-8e39-9c607aa5af10.png)
appid部署完，但是配置的时候总是提示“无效的AppID：especially-for-xx-net2，使用前请先部署。”
根据帮助文档所述，访问especially-for-xx-net2.appspot.com失败
![image](https://user-images.githubusercontent.com/12183322/38137494-7b417fee-3457-11e8-951f-6ba187d01e5e.png)
公共APPID使用正常，我的这几个APPID是1年前申请的，每一个部署都需要大概3-5分钟，今天新申请的APPID秒部署完成，都没有跳出来那个允许界面，请问这是什么问题

**Comment by SeaHOH** [comment]
![ff](https://user-images.githubusercontent.com/8470820/38138564-2e85695e-341b-11e8-8ff3-fc8b8e5725be.png)

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/38138665-a802bb4a-345e-11e8-8c54-835e06dfe753.png)

**Comment by kungfutyf** [comment]
我这个xxnet是3.11.6版本的，应该是最新版吧，刚才把浏览器重启了两次，莫名其妙的解决了问题，而且我发现我部署APPID有一定的失败几率，有些要部署两次才行，不知道为什么

**Comment by xxnet** [comment]
​要 3.11.6版存在部署bug，请升级到 3.11.7，目前是测试版
