### ISSUE TITLE
不知道啥原因，最近你一直显示连接尚未建立. ipv6-status: Fail

### ISSUE THREAD

**Issue by gtzeolite** [XX-net/XX-Net#10277]
持续时间小半个月。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5102 ipv4:0 ipv6:1286
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 3005
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
#10184

**Comment by kkkmzh** [comment]
把旧的IP删了重新扫，都是没用的IP了 或者干脆换个新版本。我是这么解决的

**Comment by gtzeolite** [comment]
关闭IPV6协议，,运行enable_ipv6.bat. 重启后已经正常。

**Comment by gtzeolite** [comment]
@msjwind  你用的是移动网络吗？ 这种状况也碰到过，后来让移动重启了一次。不知道能不能帮到你，可以试一下。

**Comment by msjwind** [comment]
@gtzeolite 谢谢了，我是单位电信的，再看看把
