### ISSUE TITLE
如何增多3.10.4版本的ipv6地址？

### ISSUE THREAD

**Issue by hainingbaby** [XX-net/XX-Net#10272]
今天换回了3.10.4版本，IP检查了一遍之后只有150个。
在proxy/local/config.py里并没有handshake_time 类似的参数。
求问如何增多IP地址呢？

**Comment by hainingbaby** [comment]
翻了很多之前的讨论没有发现答案，求指点...

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10262

**Comment by SeaHOH** [comment]
如果 IP 数过少影响使用，请具体描述。
