### ISSUE TITLE
为何总IP数被限定到了500 ？

### ISSUE THREAD

**Issue by Antecer** [XX-net/XX-Net#10273]
![123](https://user-images.githubusercontent.com/8684916/38126042-9aed7258-3420-11e8-91e9-a6791a7cdd71.JPG)
即使手动添加了配置为5000也没用！
`{
  "max_good_ip_num": 5000
}`

**Comment by cloudydayoffice** [comment]
如何手动添加配置 5000？

另外ip数最近也很少

**Comment by gjbg1989** [comment]
#10052

**Comment by gjbg1989** [comment]
即使手动添加了配置为5000也没用！——如果手动修改 config.json 正常，退出再重开才有效😂

**Comment by peqing** [comment]
请问今天3.11.3版本突然不能用了，提示开启IPV6，升级到3.11.6后可以使用了，但是IP只有500个，切延迟很大1171多，这么解决IP只有500个啊？

**Comment by Antecer** [comment]
@ghost 不是重开不重开的问题，即便重启在多次，那个IP数量也只有500个，不知道是哪里限定死了。

**Comment by AnyWAT** [comment]
贴 config.json 马赛克 appID

**Comment by Antecer** [comment]
`{
  "auto_adjust_scan_ip_thread_num": 0, 
  "listen_ip": "0.0.0.0", 
  "PROXY_HOST": "192.168.1.13", 
  "hosts_direct_endswith": [
    ".appspot.com", 
    ".google.com"
  ], 
  "PROXY_ENABLE": 1, 
  "PROXY_PORT": 8087, 
  "max_scan_ip_thread_num": 50, 
  "hosts_direct": [
    "scholar.google.com", 
    "scholar.google.com.hk", 
    "calendar.google.com", 
    "www.youtube.com", 
    "drive.google.com", 
    "mail.google.com", 
    "play.google.com", 
    "photos.google.com", 
    "imap.gmail.com", 
    "smtp.gmail.com"
  ], 
  "hosts_gae": [
    "deja.com"
  ], 
  "max_good_ip_num": 5000, 
  "target_handshake_time": 2000
}`

不用马赛克了，我直接把APPIDS给切掉了

**Comment by AnyWAT** [comment]
大括号之前后都有多余符号？"target_handshake_time": 2000或许大了些？XX的版本号？不是说 config.json 对3.10.5开始启作用，之前版本是 config.ini 或 manual.ini ？

**Comment by Antecer** [comment]
先不管参数是否有效的问题，就算参数无效，只要json结构正确是不影响解析的。
版本当然是最新的版本，我不理解的就是为嘛总IP数只有500.

**Comment by AnyWAT** [comment]
如果 json 结构不正确，XX运行不起来，没有修改"target_handshake_time"默认（600？），但改了"max_good_ip_num"是有效的，或许正是"target_handshake_time": 2000大了些？

**Comment by Antecer** [comment]
试过了，target_handshake_time 这个东西，怎么改都没用的。

**Comment by AnyWAT** [comment]
只要json结构正确是不影响解析的能搞不定？https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
