### ISSUE TITLE
不知道怎么回事，能上谷歌不能登陆gmail，cloud，youtube账号

### ISSUE THREAD

**Issue by TianMo-ZhangSan** [XX-net/XX-Net#10271]
能上谷歌不能登陆gmail，cloud，youtube账号。
请过缓存都不行。

**Comment by xxnet** [comment]
请贴出诊断信息和访问gmail时GAE的日志

**Comment by feimeng2017** [comment]
我也是 发现不能登陆谷歌的邮箱

**Comment by abigbone** [comment]
是不是等等就好了，除非你打开很久了

**Comment by yangsl158** [comment]
我可以登陆谷歌邮箱，不能发邮件。时不时会提醒错误。

**Comment by TianMo-ZhangSan** [comment]
Mar 30 21:18:42.266 - [DEBUG] 2001:ee0:3203:8::d close:exit

Mar 30 21:18:42.438 - [WARNING] IP:2404:6800:400e:3::7 host:www.cloud.google.com not support GAE, server type: status:404

Mar 30 21:18:42.438 - [INFO] remove ip:2404:6800:400e:3::7 left amount:466 target_num:466

Mar 30 21:18:42.439 - [DEBUG] 2404:6800:400e:3::7 worker close:

Mar 30 21:18:42.439 - [DEBUG] 2404:6800:400e:3::7 close:

Mar 30 21:18:42.439 - [WARNING] read fail, ip:2404:6800:400e:3::7, chunk:0 url:GET www.cloud.google.com/favicon.ico task.timeout:56 e:error(10038, '')

Mar 30 21:18:42.440 - [WARNING] 2404:6800:400e:3::7 trace: 0:connect, 2447:init, 535:request,:467, processed:0, transfered:0, sni:bake-cheek.net

Mar 30 21:18:42.440 - [DEBUG] 2404:6800:400e:3::7 worker close:down fail

Mar 30 21:18:42.440 - [DEBUG] 2404:6800:400e:3::7 close:down fail

Mar 30 21:18:42.441 - [DEBUG] 2404:6800:400e:3::7 worker close:exit

Mar 30 21:18:42.441 - [DEBUG] 2404:6800:400e:3::7 close:exit

**Comment by TianMo-ZhangSan** [comment]
Mar 30 21:18:42.266 - [DEBUG] 2001:ee0:3203:8::d close:exit

Mar 30 21:18:42.438 - [WARNING] IP:2404:6800:400e:3::7 host:www.cloud.google.com not support GAE, server type: status:404

Mar 30 21:18:42.438 - [INFO] remove ip:2404:6800:400e:3::7 left amount:466 target_num:466

Mar 30 21:18:42.439 - [DEBUG] 2404:6800:400e:3::7 worker close:

Mar 30 21:18:42.439 - [DEBUG] 2404:6800:400e:3::7 close:

Mar 30 21:18:42.439 - [WARNING] read fail, ip:2404:6800:400e:3::7, chunk:0 url:GET www.cloud.google.com/favicon.ico task.timeout:56 e:error(10038, '')

Mar 30 21:18:42.440 - [WARNING] 2404:6800:400e:3::7 trace: 0:connect, 2447:init, 535:request,:467, processed:0, transfered:0, sni:bake-cheek.net

Mar 30 21:18:42.440 - [DEBUG] 2404:6800:400e:3::7 worker close:down fail

Mar 30 21:18:42.440 - [DEBUG] 2404:6800:400e:3::7 close:down fail

Mar 30 21:18:42.441 - [DEBUG] 2404:6800:400e:3::7 worker close:exit

Mar 30 21:18:42.441 - [DEBUG] 2404:6800:400e:3::7 close:exit

**Comment by TianMo-ZhangSan** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:422 ipv4:0 ipv6:289
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:43 h2:10
scan-ip-thread-num: 10
ip-quality: 1008
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by meilianwei** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3346.9 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:undefined
worker: h1:44 h2:2
scan-ip-thread-num: 184
ip-quality: 289
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by meilianwei** [comment]
我的youtube google账号也登不上去

**Comment by gjbg1989** [comment]
#10184

**Comment by xxnet** [comment]
​
@ZhangSan
www.cloud.google.com  要试试GAE模式

编辑 data/gae_proxy/config.json

{
  "hosts_gae":[
    "www.cloud.google.com"
  ]

}

**Comment by zhgna08** [comment]
遇到一樣的問題，gmail能登入，也能收郵件，但不能發郵件，不能刪郵件等。

**Comment by Chriszhung** [comment]
遇到同样问题

**Comment by SeaHOH** [comment]
尝试测试版 3.11.10
