### ISSUE TITLE
江苏电信IPV6 IP不多了看着情况不妙

### ISSUE THREAD

**Issue by 935352** [XX-net/XX-Net#10274]
TEREDO服务器原来可用的几个也连不上，哪位大大搜集TEREDO服务器的私给我吧
新版IP有100个左右 3.1.0.4在300多上下

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录

**Comment by 935352** [comment]
谢谢 我原来都是手动切换

**Comment by evilhentaro** [comment]
跟服务器好像没什么关系，我的也是从30号开始可用v6锐减至200个

**Comment by xxnet** [comment]
​有反馈说 3.10.4 版本没有这个问题的，请试试是否能解决问题，然后反馈
https://github.com/XX-net/XX-Net/releases/3.10.4

**Comment by evilhentaro** [comment]
试过，在我这是差不多的，而且这几天v6资源获取速度极慢
挂了2天才600多

**Comment by xxnet** [comment]
​看样子墙已经对miredo进行干扰了，能用先用着先

**Comment by AnyWAT** [comment]
IP延时大、网络卡顿时，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced （手动）检查IP

**Comment by AnyWAT** [comment]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:999 ipv4:0 ipv6:1000
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:66 h2:1
scan-ip-thread-num: 9
ip-quality: 250
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by evilhentaro** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36 Maxthon/5.2.0.2000
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3485 ipv4:2 ipv6:2748
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:22 h2:8
scan-ip-thread-num: 200
ip-quality: 529
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
手检IP后，可能
gws-ip-num: total:3485 ipv4:2 ipv6:2748——去整剩零😁 ipv6: 748
ip-quality: 529——有所减小
