### ISSUE TITLE
请教！ 经常断线，IP数量，IP设定问题

### ISSUE THREAD

**Issue by cloudydayoffice** [XX-net/XX-Net#10276]
最近经常断线，不知道为什么，昨天请教了一天之后，经过热心朋友gjbg1989以及xxnet 的帮忙，今天早上试了半天没有什么问题

可是到了下午的时候又开始断线，重启XXnet几次，开始的时候显示正常，然后又断了。后来浏览文章#8915
管理权限运行 netsh int ipv6 set teredo enterpriseclient default 后正常

1.所以是服务器问题？

![image](https://user-images.githubusercontent.com/37390427/38128845-ed060006-342e-11e8-94ba-ab133c3bb71d.png)

貌似IP延迟挺不错
2.但IPV6数0正常？

![image](https://user-images.githubusercontent.com/37390427/38128874-11e86012-342f-11e8-9489-cca4df6f9401.png)

3.总IP数225 有效IP4 是偏少水平？

4.浏览文章#10273 ，手动添加如何操作？
![image](https://user-images.githubusercontent.com/37390427/38128939-5be745d4-342f-11e8-8239-d96a0fa1bcaa.png)

**Comment by cloudydayoffice** [comment]
会突然延迟9999 然后断了

![9999](https://user-images.githubusercontent.com/37390427/38159008-c1e3c76a-34d2-11e8-9cb6-70f6cbe0928f.jpg)

**Comment by SeaHOH** [comment]
因为 IPv4 基本用不了

**Comment by cloudydayoffice** [comment]
@SeaHOH  所以应该怎么调教？有什么应对方法吗？

**Comment by SeaHOH** [comment]
所以说，保证 IPv6 畅通就好了。

**Comment by cloudydayoffice** [comment]
所以应该如何保证？有什么方法吗？ @SeaHOH

**Comment by cloudydayoffice** [comment]
好的，我去试一下，谢谢热心解答：）
