### ISSUE TITLE
xxnet设置一直打不开，点设置一直在加载，就是进不去设置的页面

### ISSUE THREAD

**Issue by 862316674** [XX-net/XX-Net#10280]
如题

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/10279

**Comment by gjbg1989** [comment]
某操作系统、某XX版本😱，xxnet设置一直打不开，点设置一直在加载，就是进不去设置的页面

**Comment by hongkonghot** [comment]
将之前用的data目录直接拷到新版目录中，然后启动，试一下！

**Comment by xxnet** [comment]
​报告问题，请告知什么操作系统，xxnet什么版本，
先试最新的测试版本，很多问题在新版中解决。
