### ISSUE TITLE
gae_exception:'600:fetch gae fail' https://www.youtube.com/

### ISSUE THREAD

**Issue by yylays** [XX-net/XX-Net#10281]
win7 和linux 突然都是这样，xx显示正常却翻不过去。。

**Comment by gjbg1989** [comment]
win7 试试：http://127.0.0.1:8085/?module=gae_proxy&menu=advanced （手动）检查IP

**Comment by xuanxuaner** [comment]
同样也是这样，楼上方法未能解决

**Comment by gjbg1989** [comment]
#10285 #10282 #10184

**Comment by xuanxuaner** [comment]
600:gae_exception:'600:fetch gae fail' https://twitter.com/
@gjbg1989 这个是什么意思？我XX运行在梅林上的

**Comment by yylays** [comment]
发现了个问题，虽然xx-net显示一切正常，可是我的ipv6 代理服务器是无法ping通的，我用的是：teredo.remlab.net

**Comment by yylays** [comment]
原来不是teredo服务器问题，现在能连上google，teredo.remlab.net还是无法获取地址。现在明显ip6数量大幅下降，估计如网友所所，是对ip6开始下手了。

**Comment by SeaHOH** [comment]
信息不足，参照以下方法。

#10328
或删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
