### ISSUE TITLE
智能路由可否增加选项 仅明文http走gae ？

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#10292]
避免证书问题

**Comment by xxnet** [comment]
建议不错，不必什么都走x-tunnel，提高响应速度。

开关的设计，可以在目前”尝试 GAE“的基础上，增加一个是否”采用假证书”的开关。

**Comment by leeonyan** [comment]
请问现在智能路由有哪些型号？

**Comment by xxnet** [comment]
​智能路由，这里不是指路由器，而是XX-Net 中的一个模块。


上面提到这个功能已经实现，最新版 3.11.9

**Comment by xxnet** [comment]
​这个不难：
1. 监听多一个端口
2. 根据端口来源，判断要不要替换CA，把参数传给后续的路由规则

你可以试试 @woowoo
