### ISSUE TITLE
不能升级到最新版本

### ISSUE THREAD

**Issue by wang0371** [XX-net/XX-Net#10294]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  3.11.6和3.11.7都不能升级，都是下载文件进行到30%-60%就中断了！

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:78
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:23 h2:0
scan-ip-thread-num: 200
ip-quality: 1539
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by AnyWAT** [comment]
3.11.6和3.11.7都不能升级，都是下载文件进行到30%-60%就中断了！
手动下载如何？😘

**Comment by wang0371** [comment]
手动也是下载到40%左右会提示远程服务器关闭

**Comment by zxsword** [comment]
而且手动下载的压缩包提示损坏。.6和.7都是这样

**Comment by wang0371** [comment]
今天早上终于升级成功了。昨天应该是服务器的问题。
