### ISSUE TITLE
【关于XX-Net众版本和IP数量】

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#10291]
经测试，所有版本中，有十来个还能用。
ip数量保持在1500个左右。
延迟从250到800都有。
最快的肯定不是最新版！而是稳定版、经典版。
道理很简单：测试版就是在做实验，当然有可能有各种问题。
开发新版，数据量越来越大和复杂，是很辛苦的事情！
——真正的优化需要时间、精力、资金。
而这些工作都是志愿者无偿免费在做。
所以，大家遇到任何问题都不要抱怨，应该鼓励和支持，抱着感恩之心。

**Comment by leonliu1995** [comment]
感恩+1，我的版本开始好像是3.10.4，前两天突然不能用了。但是今天突然变成了3.11.3，又可以用了，，，，目前ipv6的ip有380个左右，延迟将近600，能用已经非常的感谢了

**Comment by dahai058** [comment]
我的3.10.4一直正常，ip始终保持1800左右，延迟250至300。

**Comment by AnyWAT** [comment]
3.10.4😄IP有效/总数：1800/N？1000/1000，延迟250至300的路过
