### ISSUE TITLE
怎么手动增加IP总数

### ISSUE THREAD

**Issue by wang0371** [XX-net/XX-Net#10296]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  看到这里有大神讲可以手动修改IP的上限，在论坛里找了很久，也没找到。
哪位大神能给详细讲一下怎么修改，或者发个修改贴的链接也可以。
不胜感激

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by MadMaxPayne8964** [comment]
data/gae_proxy文件夹内编辑config.json文件,{}内添加""max_good_ip_num": 3000

**Comment by wang0371** [comment]
谢谢找到了，试试修改后的效果。

**Comment by cloudydayoffice** [comment]
@MadMaxPayne8964 
请问是这样吗？
![image](https://user-images.githubusercontent.com/37390427/38186877-c4b38b40-3687-11e8-8e57-89d1bc93f43d.png)

**Comment by MadMaxPayne8964** [comment]
老版本ini文件直接加入max_good_ip_num=3000，[]是注释，不要这个
新版本json文件{}内添加""max_good_ip_num": 3000

**Comment by xiaowen007** [comment]
![image](https://user-images.githubusercontent.com/37954947/38230206-4bf3a826-373f-11e8-94db-0f72220188c6.png)
是在这样吗？8964

**Comment by AnyWAT** [comment]
"auto_adjust_scan_ip_thread_num": 0,   （缺失行末符号）
"max_good_ip_num": 3000                    （缺失行首符号）

**Comment by AnyWAT** [comment]
不添加就能启动？
有中文标点？得英文符号😋

**Comment by xiaowen007** [comment]
@AnyWAT   起始符吗？

**Comment by AnyWAT** [comment]
程序（运行）代码有任何中文标点？

**Comment by xiaowen007** [comment]
@AnyWAT 不添加就能运行，，肯定是添加的哪一条的原因

**Comment by AnyWAT** [comment]
😥向上爬楼。。。

**Comment by xiaowen007** [comment]
@AnyWAT 可以直白点吗？

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38232530-f4d938de-3749-11e8-8164-0f209378aa32.png)

**Comment by AnyWAT** [comment]
😱能再。。。
![image](https://user-images.githubusercontent.com/37962734/38232619-4e47811e-374a-11e8-8d30-5175489b9c2a.png)

**Comment by cloudydayoffice** [comment]
非常感谢 @MadMaxPayne8964 @AnyWAT

**Comment by xiaowen007** [comment]
@AnyWAT 发现了，谢谢
0,这小点⊙﹏⊙‖∣没添加上

**Comment by cloudydayoffice** [comment]
IP数偏少？
![image](https://user-images.githubusercontent.com/37390427/38233557-7a2b73d2-374d-11e8-9384-c5a1f4c116c4.png)

IPV6为0什么鬼？
![image](https://user-images.githubusercontent.com/37390427/38233585-9723f4a0-374d-11e8-942a-d34c16c34f03.png)

**Comment by loveyou90** [comment]
{
  "max_scan_ip_thread_num": 50,
  "GAE_APPIDS": [
    "apple-594", 
    "apple-595", 
    "apple-596", 
    "apple-597", 
    "apple-598", 
    "apple-599", 
    "apple-600", 
    "apple-601", 
         @@@@@"apple-602", 
   ]
}
{"auto_adjust_scan_ip_thread_num": 0,}
{"max_good_ip_num": 3000}
@AnyWAT  请问 是这样 添加的吗

**Comment by loveyou90** [comment]
{
"max_scan_ip_thread_num": 50,
"GAE_APPIDS": [
"apple-594",
"apple-595",
"apple-596",
"apple-597",
"apple-598",
"apple-599",
"apple-600",
"apple-601",
"apple-602",
]
}
{"auto_adjust_scan_ip_thread_num": 0,}
{"max_good_ip_num": 3000} 
@AnyWAT   @MadMaxPayne8964 请问 是这样 添加的么

**Comment by AnyWAT** [comment]
{
"max_scan_ip_thread_num": 50,
"GAE_APPIDS": [
"apple-594",
"apple-595",
"apple-596",
"apple-597",
"apple-598",
"apple-599",
"apple-600",
"apple-601",
"apple-602"
]，
"auto_adjust_scan_ip_thread_num": 0,
"max_good_ip_num": 3000
}

**Comment by AnyWAT** [comment]
"max_good_ip_num": 3000——1-2000足以
露富咯😱 AppID

**Comment by loveyou90** [comment]
{
  "max_scan_ip_thread_num": 50,
  "GAE_APPIDS": [
    "apple-594", 
    "apple-595", 
    "apple-596", 
    "apple-597", 
    "apple-598", 
    "apple-599", 
    "apple-600", 
    "apple-601", 
     "apple-602", 
  ]
   "auto_adjust_scan_ip_thread_num": 0,
   "max_good_ip_num": 3000
}
@AnyWAT 原格式 是这样的  保存以后 启动不了啊  兄弟 怎么破 是格式不对么

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38509506-a45a5b44-3c54-11e8-9044-6e2a4bac1fc7.png)

**Comment by loveyou90** [comment]
@AnyWAT 还是启动不了啊 兄弟 我都糊涂了 不知道 格式哪里错了 可以麻烦帮我远程弄下么 感谢 QQ948816765

**Comment by AnyWAT** [comment]
建议：
{
"max_scan_ip_thread_num": 50,
"GAE_APPIDS": [
"apple-594",
"apple-595",
"apple-596",
"apple-597",
"apple-598",
"apple-599",
"apple-600",
"apple-601",
"apple-602"
]，
"auto_adjust_scan_ip_thread_num": 0,
"max_scan_ip_thread_num": 40,
"max_good_ip_num": 1000
}

**Comment by AnyWAT** [comment]
XX-Net 版本？

**Comment by loveyou90** [comment]
@AnyWAT 3.11.8的版本

**Comment by loveyou90** [comment]
@AnyWAT 启动不了 弄了 好几个小时了 晕死

**Comment by AnyWAT** [comment]
爬楼😱
QQ远程😱，看看下列网文
RT @wuzy Windows 绝赞应用 https://amazing-apps.gitbooks.io/windows-apps-that-amaze-us/content/zh-CN/ … ，https://portableapps.com/ ，http://www.zdfans.com/ 。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38510230-f442cdf6-3c56-11e8-9976-e807d82aeb5c.png)
![default](https://user-images.githubusercontent.com/37962734/38510257-08a85806-3c57-11e8-8860-de4b71920e85.png)

**Comment by loveyou90** [comment]
@AnyWAT 


帮我 远程弄一下 吧 兄弟  格式 实在弄不明白了┭┮﹏┭┮

**Comment by AnyWAT** [comment]
温故知新、温故知新、温故知新

**Comment by loveyou90** [comment]
![111](https://user-images.githubusercontent.com/38221182/38510504-e3f90b94-3c57-11e8-933b-9e2c63f15cef.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38510649-3dda22f6-3c58-11e8-84ed-0b6583b8a505.png)

**Comment by loveyou90** [comment]
是这样么 兄弟

**Comment by loveyou90** [comment]
"auto_adjust_scan_ip_thread_num": 0,
  "max_good_ip_num": 1000                我就想知道 这两条命令所在的 位置 对么

**Comment by AnyWAT** [comment]
别理会，貌似没有前后之分，程序能启动运行即可。在控制页内不做任何修改，提交保存下（自动保存 config.json），也许会这下这顺序，那下那顺序。

**Comment by AnyWAT** [comment]
露富咯😱 AppID 不怕被人用光流量？

**Comment by AnyWAT** [comment]
😱害人，给 https://github.com/XX-net/XX-Net/issues/10400 回的一些东东被贵贴。。。没完成，没了

**Comment by loveyou90** [comment]
复制你回复的  根本启动不了啊 兄弟

**Comment by elo5** [comment]
"max_good_ip_num": 1000  前面结束的地方要加个逗号
{
  "max_scan_ip_thread_num": 100, 
  "GAE_APPIDS": [
    "project16426", 
    "lilichen8411"
  ], 
  "use_ipv6": "force_ipv6",
  "max_good_ip_num": 3000
}

**Comment by elo5** [comment]
"max_good_ip_num": 1000  前面结束的地方要加个逗号，以下是我的xxxxxxxx表示我的2个appid
{
  "max_scan_ip_thread_num": 100, 
  "GAE_APPIDS": [
    "xxxxxxxx", 
    "xxxxxxxx"
  ], 
  "use_ipv6": "force_ipv6",
  "max_good_ip_num": 3000
}

**Comment by AnyWAT** [comment]
@loveyou90 中括号末的标点是全角，已修改🤣

**Comment by SeaHOH** [comment]
所以说你们不要乱改，IP 过少直接删除 good_ip.txt，然后重新扫。

**Comment by AnyWAT** [comment]
因噎废食🤣

**Comment by SeaHOH** [comment]
失效 IP 会占据 IP 数，所以。。。

**Comment by AnyWAT** [comment]
貌似以前在日志内看到IP排序花多少时间，现在没有，即没排序？

**Comment by AnyWAT** [comment]
从来没有，那不是排序：🤣刚从运行3.8.4的手机截图，sort IP time:63ms 貌似以前在PC日志内也见过，只是奇怪，现在PC上同样运行3.8.4却没见有😱
![screenshot_2018-04-15-16-26-06](https://user-images.githubusercontent.com/37962734/38776621-7434b19a-40cc-11e8-8c1e-21da3a6a3b34.png)

**Comment by SeaHOH** [comment]
记得原来是有个评分，刚查了下，确实是排序，我记错了。 :trollface:

**Comment by SeaHOH** [comment]
不建议修改
