### ISSUE TITLE
打不开谷歌学术

### ISSUE THREAD

**Issue by yuezhang666** [XX-net/XX-Net#10293]
显示：XX-Net 3.11.3，一切正常，你可以访问真正的互联网了。
ipv6数量20-50，ip延迟1000-2000，打不开谷歌学术，显示：连接超时，休息一会再来

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38172837-d9c98ee6-35e5-11e8-8377-d6ba96de16b6.png)
