### ISSUE TITLE
Windows下，放在Program Files目录下，开机自动启动问题

### ISSUE THREAD

**Issue by haoliao** [XX-net/XX-Net#103]
问题1：配置中设置开机自动启动后，无法开机自动启动
查看注册表，数据为“D:\Program Files\BypassWall\XX-Net\python27\1.0\pythonw.exe D:\Program Files\BypassWall\XX-Net\launcher\start.py”
改为“"D:\Program Files\BypassWall\XX-Net\python27\1.0\pythonw.exe" "D:\Program Files\BypassWall\XX-Net\launcher\start.py"”，即增加两个双引号后，可以开机自动启动

问题2：左键单击xx-net状态栏图标或右键单击xx-net状态栏图标》config后，IE和chrome均弹出状态页，每次操作均弹出两个状态页
IE版本为IE11，路径为"C:\Program Files\Internet Explorer\iexplore.exe"
chrome为默认浏览器，版本为41.0.2272.118，是用MyChrome引导的绿色便携版，MyChrome路径为"D:\Program Files\Google Chrome\MyChrome.exe"，chrome.exe路径为"D:\Program Files\Google Chrome\Chrome\chrome.exe"

附上xx-net状态页：

GoAgent状态信息
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.7.1
Launcher Version	1.2.0
GoAgent Version	3.1.44
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	 xxxxxx1|xxxxxx2|xxxxxx3
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	 3000

**Comment by xxnet** [comment]
感谢的的探索和反馈。

对于问题1，你可以试试提交补丁。就是用github自己clone一个版本，修改后，提交，然后请求合并过来。
谢谢。

第二个问题，源码中只是调用浏览器的api webbrowser，按道理，默认的浏览器只会有一个。
  你试试资源浏览器中，点击一个html文件，看会不会弹出来2个浏览器？
  这个问题，出现情况少，怀疑是MyChrome的机制不够标准通用导致。
  我用过Chrome\IE\ChromePortable一起工作，没有出现这种情况。

2015-04-02 23:57 GMT-04:00 haoliao <notifications@github.com>:

**Comment by haoliao** [comment]
多谢回复。
对问题1：个人对编程不了解，不知道怎么操作。xx-net设置开机自动启动时，路径能带上双引号么，这样可行么？

对问题2：通过取消MyChrome默认浏览器以及重新设置MyChrome默认浏览器后解决。

PS：多谢提供这么好的工具。

**Comment by xxnet** [comment]
收到反馈。

问题1 我这几天升级时修复。

谢谢

在 2015年4月7日 上午1:07，haoliao <notifications@github.com>写道：

**Comment by xxnet** [comment]
1.8.x 修复了目录含空格情况下，开机自动启动的问题
