### ISSUE TITLE
Chrom用SwitchyOmega时的问题

### ISSUE THREAD

**Issue by ZhengYuen** [XX-net/XX-Net#10308]
SwitchyOmega选用GAE-Proxy之后，经常自动切换到SmartRouter；另外移除SwitchyOmega选用全局PAC的时候，在设置界面经常会提示检查浏览器代理设置

**Comment by AnyWAT** [comment]
SwitchyOmega选用GAE-Proxy之后，（重启浏览器后？）经常自动切换到SmartRouter
![image](https://user-images.githubusercontent.com/37962734/38204782-c80b4216-36d6-11e8-9ee4-5b58e8aa22a7.png)
移除SwitchyOmega选用全局PAC的时候，在设置界面经常会提示检查浏览器代理设置（务必开启？）
![image](https://user-images.githubusercontent.com/37962734/38204822-ee132924-36d6-11e8-86ef-3276067c33c8.png)

**Comment by ZhengYuen** [comment]
感谢，第一个问题已解决。
关于第二个问题，您的意思是如果不使用SwitchyOmega的话，一定要开启Smart Router吗？

**Comment by AnyWAT** [comment]
选用全局PAC的时候，一定要开启Smart Router
