### ISSUE TITLE
XX-Net-3.11.7 版本安装后运行start.vbs提示报毒

### ISSUE THREAD

**Issue by jaxguo** [XX-net/XX-Net#10301]
XX-Net-3.11.7 新版本安装提示报毒, 挂马攻击. 
老版本没出过报错,是更新了什么功能吗?

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10282 下载附件 enable_ipv6.zip 报毒，再次下载正常，完成后检查也没事
