### ISSUE TITLE
3.11.7经常会断，3.11.3一切正常

### ISSUE THREAD

**Issue by zenzenmo** [XX-net/XX-Net#10304]
还好有自动保存旧版本

**Comment by AnyWAT** [comment]
😋恐怕言时过早？

**Comment by zenzenmo** [comment]
3.11.3虽然ip才200多，但ipv6不会断，3.11.7开机正常，一会就没ip了，重启才能恢复，然后又没ip，和之前的某个版本现象是一样的，至少3.11.3很稳定不掉

**Comment by AnyWAT** [comment]
3.10.5及以后版本关闭“自动调整扫描线程”，不时手动检查IP

**Comment by standritsu** [comment]
因为3.11.7默认的target_handshake_time是200，网络有点不好就会疯狂丢弃IP，往后面加个0吧...

**Comment by JhonZRoger** [comment]
3.8.7可以使用！！！
