### ISSUE TITLE
3.11.7为什么一直占用上传和下载网速

### ISSUE THREAD

**Issue by ppeng** [XX-net/XX-Net#10309]
不浏览网页也是占用网速 在传输什么呢 ？
下载120多kb上传30kb
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:37 h2:6
scan-ip-thread-num: 112
ip-quality: 255
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Chriszhung** [comment]
分布式挖矿？？？

**Comment by lucifinilsu** [comment]
怕不是真的有挖矿代码吧卧槽

**Comment by gitxxnet2018** [comment]
应该是在扫描可用的IPv6地址吧

**Comment by ppeng** [comment]
下载120多kb上传30kb

**Comment by xxnet** [comment]
这不是正常流量。
​看看各模块日志，后台有没有连接

**Comment by ppeng** [comment]
怎么回复  没找到回复按钮啊 怎么能回复别人的评论呢

**Comment by ppeng** [comment]
@xxnet   pythonnw.exe占用网速，下载100k左右
