### ISSUE TITLE
3.11.7 更新过后证书显示失败

### ISSUE THREAD

**Issue by chenmolm** [XX-net/XX-Net#10311]
更新过后 未作其他做过 ，删除证书后 重新添加也不起效

**Comment by chenmolm** [comment]
诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:500
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 299
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 2609665** [comment]
XX-Net\data\gae_proxy\certs   
好像删除证书要同时把这个目录文件夹删掉
然后再重新运行CA安装证书!

**Comment by wub722** [comment]
试了3.11.7和3.11.6，均出现了证书问题
换回3.10.4就OK

**Comment by SeaHOH** [comment]
请参照 Wiki 页面操作，这个也没什么好讲的。
就是 Firefox 要注意一下，删除后一定要重启再导入。
