### ISSUE TITLE
开机时ipconfig /all显示2001开头的ipv6地址，只要启动xxnet或者ping test-ipv6.com就不行了

### ISSUE THREAD

**Issue by dhxy5117** [XX-net/XX-Net#10312]

**Comment by AnyWAT** [comment]
https://support.microsoft.com/zh-cn/help/929852/ 上排第一个执行后重启？

**Comment by dhxy5117** [comment]
@AnyWAT 不行，好像是只要有ipv6的网络请求就不行，昨天更新了网卡驱动，以为是这个原因，还原到低版本还是不行。。。

**Comment by AnyWAT** [comment]
https://support.microsoft.com/zh-cn/help/929852/ 下排第（2、3、）4个？

**Comment by AnyWAT** [comment]
XX正常过？不正常后电脑做了哪些修改？

**Comment by AnyWAT** [comment]
https://support.microsoft.com/zh-cn/help/929852/ 或许先上排第（2、3、）4个，再下排第（2、3、）4个？

**Comment by dhxy5117** [comment]
@AnyWAT  上周一直在用，周末的时候感觉电脑连wifi一直很慢，就手贱用联想官方工具更新了下，包括几个驱动和bios，我再试试吧，谢谢了

**Comment by AnyWAT** [comment]
不会是某注册表项被改回了？
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]

**Comment by AnyWAT** [comment]
上图需代理。dword 16进制 0 就对了

**Comment by dhxy5117** [comment]
Dnscache\Parameters\ServiceDllUnloadOnStop 为1，这个要改吗

**Comment by dhxy5117** [comment]
我还是用tunnel吧，搞不定了

**Comment by AnyWAT** [comment]
😱有说 [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters] 某参数也 dword 16进制 0 ，但正常的现在
![image](https://user-images.githubusercontent.com/37962734/38285463-da071630-37f2-11e8-9aea-f543b6bbf68b.png)

**Comment by AnyWAT** [comment]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:999 ipv4:0 ipv6:1000
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:0
worker: h1:58 h2:0
scan-ip-thread-num: 9
ip-quality: 250
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by dhxy5117** [comment]
@AnyWAT 昨天win10更新了，执行
netsh interface Teredo set state disable
netsh interface Teredo set state type=default
netsh interface teredo set state enterpriseclient server=default
就ok了，不过还是不太稳定

**Comment by AnyWAT** [comment]
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值？）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
😜3.10.5-3.11.9得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by AnyWAT** [comment]
netsh interface Teredo set state disable
netsh interface Teredo set state type=default
netsh interface teredo set state enterpriseclient server=default 替代：管理权限运行
netsh int ipv6 set teredo enterpriseclient default （有说 enterpriseclient 好过默认的 client）
