### ISSUE TITLE
将您重定向的次数过多

### ISSUE THREAD

**Issue by liumd1** [XX-net/XX-Net#10314]
该网页无法正常运作
ipv6.google.com 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS

这是怎么回事，哪位大神有方案解决？
还有：
我们检测到您的 Cookie 设置存在问题。
启用 Cookie
请确保Cookie处于启用状态。要启用Cookie，请按照各浏览器的说明进行操作。

清除缓存和 Cookie
如果启用Cookie后仍然存在问题，请清空浏览器的缓存和Cookie。

调整隐私权设置
如果清除缓存和 Cookie 不能解决问题，请尝试调整浏览器的隐私权设置。如果您的设置为“高”，请手动将 www.google.com 添加到允许的网站列表中。
貌似跟cookie也没关系，按照上述方式解决不了问题

**Comment by liumd1** [comment]
3.10.4没有这个提示，但3.10.4经常连不上

**Comment by lkyyang** [comment]
同遇到过，清除cookie也没用。在打不开的页面上还出现了*.lianmeng.360.cn这个东西，不知道是什么，从来没用过360的软件。

**Comment by liumd1** [comment]
3.11.7 gmail邮箱无法登录，密码输入错误会提示“密码错误”，输入正确的密码后等很久就是登录不上

**Comment by xiaowen007** [comment]
@liumd1 换chrome,，，

**Comment by sd613** [comment]
3.11.3没有上述问题

**Comment by liumd1** [comment]
@xiaowen007 用的是chrome最新版的
Google Chrome 已是最新版本
版本 65.0.3325.181（正式版本） （64 位）

**Comment by liumd1** [comment]
@sd613  是的，3.11.3没有问题

**Comment by AnyWAT** [comment]
将您重定向的次数过多：😱是否网速的锅？
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
😜3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程为40（或自己调试），转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程为20（或自己调试），转换XX-Net版本、或延时大网络卡顿，得。。。
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅

**Comment by SeaHOH** [comment]
我觉得还是浏览器设置的原因

@AnyWAT 你发的重复内容太多，不利于检索，可使用引用来替代，如： https://github.com/XX-net/XX-Net/issues/10314#issuecomment-379511362 。

**Comment by THLIVSQAZ** [comment]
不，问题在xx-net上，同样的浏览器，退回旧版就正常了       3.10.4正常，3.11.7就出现该问题   个人猜测可能是smart-router @SeaHOH

**Comment by AnyWAT** [comment]
难怪没用 smart-router（因时有卡顿，3.10.4也是）的没遇到🤣

**Comment by SeaHOH** [comment]
@liumd1 @THLIVSQAZ 能不能发一下重定向时的日志？

**Comment by THLIVSQAZ** [comment]
xx-net没有什么错误日志

**Comment by SeaHOH** [comment]
不是错误日志，就是一般日志，重定向时发生的。

可以尝试新版，不过要等会儿。

关闭后仍可回复。

**Comment by SeaHOH** [comment]
还有，不要使用 ipv6.google.com，而是 www.google.com。
