### ISSUE TITLE
4月3号开始，可以打开Google首页，但是用Google搜索一直显示“连接超时，先休息一会再来！”

### ISSUE THREAD

**Issue by yangsl158** [XX-net/XX-Net#10313]
升级3.11.7版本后，Gmail的问题也一直存在，打开速度很慢，可以收邮件，不能发邮件。
经常出现提示：“Oops… the system encountered a problem (#500) - Retrying in 4s…”
似乎证书也有一些问题，因为早上遇到有些网页打不开。。比如，http://wallfans.eu.org/ iTunes更新也提示证书的问题。当然，这个是我的猜测。。

**Comment by SeaHOH** [comment]
关闭后仍可回复
