### ISSUE TITLE
4800 个 IP，出现 504 , 连接超时，先休息一会再来！

### ISSUE THREAD

**Issue by FoamValue** [XX-net/XX-Net#1031]
Sep 15 16:10:29 - [DEBUG] 143.215.193.205 fail
Sep 15 16:10:30 - [DEBUG] 213.208.156.223 fail
Sep 15 16:10:30 - [DEBUG] 213.155.151.144 fail
Sep 15 16:10:30 - [DEBUG] 117.102.117.213 fail
Sep 15 16:10:30 - [DEBUG] 110.164.16.75 fail
Sep 15 16:10:30 - [DEBUG] 220.255.6.181 fail
Sep 15 16:10:30 - [DEBUG] 201.248.78.68 fail
Sep 15 16:10:30 - [DEBUG] 114.121.194.86 fail
Sep 15 16:10:30 - [DEBUG] 187.72.192.196 fail
Sep 15 16:10:30 - [DEBUG] 121.78.52.68 fail
Sep 15 16:10:31 - [DEBUG] 59.18.44.43 fail
Sep 15 16:10:32 - [DEBUG] get ip:41.205.32.170 t:4908
Sep 15 16:10:32 - [DEBUG] get ip:31.55.167.152 t:4908
Sep 15 16:10:32 - [DEBUG] get ip:42.112.9.89 t:4908
Sep 15 16:10:32 - [DEBUG] get ip:101.99.49.155 t:4908
Sep 15 16:10:32 - [DEBUG] get ip:208.117.250.162 t:4908
Sep 15 16:10:32 - [DEBUG] get ip:118.98.106.248 t:4909
Sep 15 16:10:32 - [DEBUG] get ip:210.245.14.249 t:4909
Sep 15 16:10:32 - [DEBUG] get ip:193.134.255.6 t:4909
Sep 15 16:10:32 - [DEBUG] get ip:208.65.155.48 t:4909
Sep 15 16:10:33 - [DEBUG] get ip:210.245.14.168 t:4909
Sep 15 16:10:33 - [DEBUG] get ip:151.21.210.20 t:4909
Sep 15 16:10:36 - [DEBUG] 41.205.32.170 fail
Sep 15 16:10:36 - [DEBUG] 31.55.167.152 fail
Sep 15 16:10:36 - [DEBUG] 42.112.9.89 fail
Sep 15 16:10:36 - [DEBUG] 101.99.49.155 fail
Sep 15 16:10:36 - [DEBUG] 208.117.250.162 fail
Sep 15 16:10:36 - [DEBUG] 118.98.106.248 fail
Sep 15 16:10:36 - [DEBUG] 210.245.14.249 fail
Sep 15 16:10:36 - [DEBUG] 193.134.255.6 fail
Sep 15 16:10:36 - [DEBUG] 208.65.155.48 fail
Sep 15 16:10:37 - [DEBUG] 210.245.14.168 fail
Sep 15 16:10:37 - [DEBUG] 151.21.210.20 fail

**Comment by FoamValue** [comment]
IP 会越来越多，要把 fail 次数很多的 IP，从 IP 池中删除。

**Comment by myTruth** [comment]
怎么删？一个一个对照日志 手动删除么？

**Comment by swizardlv** [comment]
今天好像这种现象特别多

**Comment by FoamValue** [comment]
手动删除，要删到什么时候。。。
* 程序自动判断，删除不适用的 IP
