### ISSUE TITLE
youtube无法搜索、无法用google帐号登录

### ISSUE THREAD

**Issue by genliu777** [XX-net/XX-Net#10315]
XX-Net Version | 3.11.7
-- | --

**Comment by xiaowen007** [comment]
我也遇到这问题，，youtube登陆就出错

**Comment by Tim-Xue** [comment]
可以进入youtube界面，但是一点登陆就连接超时。
同时登入gmail后会报#500错误。

**Comment by f18love** [comment]
拿看来不是我个人问题了，  我还以为被封了账号   但是很奇怪 ， 不登录的话又能上哦。

**Comment by dxdvid** [comment]
我的也是

**Comment by dxdvid** [comment]
最新版本，之前使用正常，最近google账号登录不了。 能打开youtube 但是不能登录。 #10349
完美解决

**Comment by SeaHOH** [comment]
等待新版发布
