### ISSUE TITLE
更新到3.11.7后password如何设置

### ISSUE THREAD

**Issue by pangxin123** [XX-net/XX-Net#10320]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config

**Comment by pangxin123** [comment]
设置后无法打开

**Comment by AnyWAT** [comment]
用了中文标点还是少了引号？
“GAE_PASSWORD”: "PASSWORD",

**Comment by zhaoruihao** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config
这里面应该有语法错误吧，“listen_ip” : “127.0.0.1”后面少了逗号，
“www.google.com”
], 这个地方多一个逗号
小白一个，非计算机专业，改完好了，不知道改的对不对

**Comment by pangxin123** [comment]
按照楼上的改了一遍能启动了，但是之前设有密码，更新到新版本后手误有重新部署了一遍，现在没有密码了，想问一下怎么重新设置密码

**Comment by SeaHOH** [comment]
#10336
