### ISSUE TITLE
版本3.11.7的问题？bug

### ISSUE THREAD

**Issue by shirokuuhaku** [XX-net/XX-Net#10324]
在高级选项卡里开起ipv6隧道
>: netsh int 6to4 set state default
------------------------------------ 
OK之后可正常使用

但在下面的
>: netsh int isatap set state default
------------------------------------ 
OK 

>: netsh int teredo set state server=teredo.remlab.net
------------------------------------ 
OK 

>: netsh int ipv6 set teredo enterpriseclient
------------------------------------ 
OK 
之后xx-net显示report_connect_fail network fail，扫描不到任何ip，ipv6也失败
使用检查ip，刚刚扫到的所有可用IP也都消失了

Apr 04 10:33:05.071 - [ERROR] Except stack:Traceback (most recent call last): File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_manager.py", line 647, in scan_ip_worker ip = self.ip_source.get_ip() File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 238, in get_ip return self.ipv6_source.get_ip() File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 211, in get_ip line = self.get_slice() File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 204, in get_slice raise Exception() Exception

这是bug还是设计缺陷？

以下为再次尝试的结果，记录了可用到不可用的瞬间
Apr 04 10:54:19.986 - [INFO] remove_slowest_ip:2607:f8b0:401a:1::7 handshake_time:427, fails:15

Apr 04 10:54:20.161 - [INFO] scan_ip add ip:2a00:1450:4003:f::17 time:1416 h2:0

Apr 04 10:54:20.163 - [INFO] remove_slowest_ip:2a00:1450:4015:e::1e handshake_time:424, fails:15

Apr 04 10:54:20.416 - [INFO] scan_ip add ip:2607:f8b0:401c:2::b time:237 h2:0

Apr 04 10:54:20.418 - [INFO] remove_slowest_ip:2404:6800:4008:c04::5e handshake_time:1422, fails:14

Apr 04 10:54:20.548 - [DEBUG] create_ssl update ip:2806:10a0:cfff:2::f time:597 h2:0 sni:variation.friend.us, host:

Apr 04 10:54:20.754 - [INFO] scan_ip add ip:2607:f8b0:401c:12::7 time:228 h2:0

Apr 04 10:54:20.756 - [INFO] remove_slowest_ip:2a00:1450:4017:16::7 handshake_time:416, fails:15

Apr 04 10:54:20.775 - [DEBUG] GAEProxy Web_control 127.0.0.1:1703 GET /ipv6_tunnel?cmd=get_log

Apr 04 10:54:21.776 - [DEBUG] GAEProxy Web_control 127.0.0.1:1703 GET /ipv6_tunnel?cmd=get_log

Apr 04 10:54:22.778 - [DEBUG] GAEProxy Web_control 127.0.0.1:1703 GET /ipv6_tunnel?cmd=get_log

Apr 04 10:54:22.822 - [DEBUG] netsh state: Teredo p[^[ --------------------------------------------- : client T[o[ : teredo.remlab.net NCAgXVԊu : 30 b NCAg |[g : unspecified : qualified NCAg̎ : teredo host-specific relay lbg[N : unmanaged NAT : none (global connectivity) NAT ̓ȓ : UPNP: Aێ|[g: [J }bsO : （本地ip）:55367 O NAT }bsO : （本地IP）:55367

Apr 04 10:54:23.458 - [DEBUG] 2806:10a0:cfff:2::f close:alive_timeout

Apr 04 10:54:23.477 - [DEBUG] report_connect_fail:2607:f8b0:400f:13::7

Apr 04 10:54:23.477 - [DEBUG] connect 2607:f8b0:400f:13::7 fail:error("conn fail, sni:longsummer.org, top:XXXXXXXXXXXXXXXX.appspot.com e:timeout('timed out',)",)

Apr 04 10:54:23.778 - [DEBUG] GAEProxy Web_control 127.0.0.1:1703 GET /ipv6_tunnel?cmd=get_log

Apr 04 10:54:24.780 - [DEBUG] GAEProxy Web_control 127.0.0.1:1703 GET /ipv6_tunnel?cmd=get_log

Apr 04 10:54:25.488 - [DEBUG] report_connect_fail:2607:f8b0:401c:12::7

Apr 04 10:54:25.488 - [DEBUG] connect 2607:f8b0:401c:12::7 fail:error("conn fail, sni:action.habit.net, top:XXXXXXXXXXXXXXX.appspot.com e:error(10051, 
'\\x93\\x9e\\x92B\\x82\\xc5\\x82\\xab\\x82\\xc8\\x82\\xa2\\x83l\\x83b\\x83g\\x83\\x8f\\x81[\\x83N\\x82\\xc5\\x83\\\\\\x83P\\x83b\\x83g\\x91\\x80\\x8d\\xec\\x82\\xf0\\x8e\\xc0\\x8ds\\x82\\xb5\\x82\\xe6\\x82\\xa4\\x82\\xc6\\x82\\xb5\\x82\\xdc\\x82\\xb5\\x82\\xbd\\x81B')",)
Apr 04 10:54:31.621 - [WARNING] h1 2607:f8b0:401c:8::7 HEAD keep alive request fail:Exception('time out',)

Apr 04 10:54:31.622 - [WARNING] 2607:f8b0:401c:8::7 trace: 0:connect, 2334:init, 1039:request, 13095:Res, 0:head,:6006, processed:1, transfered:1303547, sni:angle.example.official.org

Apr 04 10:54:31.623 - [DEBUG] 2607:f8b0:401c:8::7 worker close:down fail

Apr 04 10:54:31.624 - [DEBUG] 2607:f8b0:401c:8::7 close:down fail

Apr 04 10:54:31.624 - [DEBUG] report_connect_fail:2607:f8b0:401c:8::7

Apr 04 10:54:31.634 - [DEBUG] 2607:f8b0:401c:8::7 worker close:keep alive

Apr 04 10:54:31.635 - [DEBUG] 2607:f8b0:401c:8::7 close:keep alive

Apr 04 10:54:36.370 - [DEBUG] report_connect_fail:2a02:8400:0:108::11

Apr 04 10:54:36.371 - [DEBUG] connect 2a02:8400:0:108::11 fail:error("conn fail, sni:catstudy.com, top:XXXXXXXXXXXXXXXX.appspot.com e:error(10051, '\\x93\\x9e\\x92B\\x82\\xc5\\x82\\xab\\x82\\xc8\\x82\\xa2\\x83l\\x83b\\x83g\\x83\\x8f\\x81[\\x83N\\x82\\xc5\\x83\\\\\\x83P\\x83b\\x83g\\x91\\x80\\x8d\\xec\\x82\\xf0\\x8e\\xc0\\x8ds\\x82\\xb5\\x82\\xe6\\x82\\xa4\\x82\\xc6\\x82\\xb5\\x82\\xdc\\x82\\xb5\\x82\\xbd\\x81B')",)

Apr 04 10:54:36.573 - [WARNING] get_slice fail

Apr 04 10:54:36.574 - [ERROR] scan_ip_worker except:Exception()

Apr 04 10:54:36.575 - [ERROR] Except stack:Traceback (most recent call last): File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_manager.py", line 647, in scan_ip_worker ip = self.ip_source.get_ip() File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 238, in get_ip return self.ipv6_source.get_ip() File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 211, in get_ip line = self.get_slice() File "F:\XX-Net-master\XX-Net-3.1.4\code\3.11.7\python27\1.0\lib\noarch\front_base\ip_source.py", line 204, in get_slice raise Exception() Exception

Apr 04 10:54:36.793 - [DEBUG] GAEProxy Web_control 127.0.0.1:1703 GET /ipv6_tunnel?cmd=get_log

Apr 04 10:54:37.567 - [DEBUG] report_connect_fail:2a02:8400:0:111::11

Apr 04 10:54:50.450 - [WARNING] get body fail, until:5446334 https://clients2.googleusercontent.com/crx/blobs/XXXXXXXXXX-XXXXXXXXXXXXX/extension_3_3_7_0.crx

**Comment by shirokuuhaku** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1437 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:1
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
这是三个通道（6to4、isatap、teredo），既然 6to4 能用就把其它两个关闭，因为有优先级问题。
其它（isatap、teredo）同理。
