### ISSUE TITLE
求 手把手教育，ipv6尚未连接

### ISSUE THREAD

**Issue by dvp155** [XX-net/XX-Net#10329]
折腾好久都未果。
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3000 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![U

ploading 捕获1.PNG…]()
![Uploading 捕获2.PNG…]()
![Uploading 捕获3.PNG…]()
![Uploading 捕获4.PNG…]()
![Uploading 捕获55.PNG…]()
![jiaoben1](https://user-images.githubusercontent.com/12059865/38293094-ccabefc6-3818-11e8-8471-c6e93f158cb8.PNG)

**Comment by dvp155** [comment]
![jiaoben3](https://user-images.githubusercontent.com/12059865/38293214-3fccfeaa-3819-11e8-926b-a4af7ec19576.PNG)
![jiaoben4](https://user-images.githubusercontent.com/12059865/38293220-44f8b9a0-3819-11e8-8c75-14c4ff676ad2.PNG)
![jiaoben55](https://user-images.githubusercontent.com/12059865/38293228-4a60c946-3819-11e8-9c88-d18481249a10.PNG)
![jiaoben2](https://user-images.githubusercontent.com/12059865/38293237-514cda1a-3819-11e8-90d5-89617b0cf9ea.PNG)

**Comment by AnyWAT** [comment]
自动选择PING延时少的服务器都没成功？
试试：。。。或许使用微软默认服务器会好些？。。。
管理权限运行 netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.
use-ipv6: auto 改为 force_ipv6
电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
😋模块管理 ：关闭 Smart Router
XX：取消全局代理
插件：GAE自动切换
3.10.5-3.11.7得关闭“自动调整扫描线程”，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP

**Comment by dvp155** [comment]
@AnyWAT  自动选择PING延时少的服务器都没成功？
试试：。。。或许使用微软默认服务器会好些？。。。
管理权限运行 netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.【√】
use-ipv6: auto 改为 force_ipv6【？没找着，xx3.11.3】
电脑DNS：【√】
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值【无】）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
yum模块管理 ：关闭 Smart Router【√】
XX：取消全局代理【√】
插件：GAE自动切换【√】
3.10.5-3.11.7得关闭“自动调整扫描线程”【√】，转换XX版本【？】、或延时大网络卡顿【？】，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP【√】
![jietu1](https://user-images.githubusercontent.com/12059865/38364542-bbd2e65c-390b-11e8-9802-e60807404074.PNG)
![jietu2](https://user-images.githubusercontent.com/12059865/38364553-c49cce1a-390b-11e8-95c0-34d752e7eb9d.PNG)
![jietu3](https://user-images.githubusercontent.com/12059865/38364559-c961a9d4-390b-11e8-8175-c812c002803d.PNG)
![jietu4](https://user-images.githubusercontent.com/12059865/38364560-cca73122-390b-11e8-8aa1-46f4e5797da4.PNG)

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 10 增大扫描线程5-10倍

**Comment by dvp155** [comment]
@AnyWAT
"仅IPv6" 不可用，请检查。


IPv4 状态 | OK
-- | --
IPv6 状态 | Fail

另外 terodo参数不显示状态了，如上楼图。 我没有重启pc

**Comment by AnyWAT** [comment]
网络禁用再启用

**Comment by dvp155** [comment]
网友制作的那个脚本  第6项 电脑休眠-〉ipv6 fail处理  功能试过，既是先禁网卡再启用。
 是teredo的原因吗，还是xxnet 版本呢，我更新都是覆盖原有老版本，这个文件夹还是3.9.2那个。
 就是死活通过不了ipv6 测试

**Comment by AnyWAT** [comment]
我更新都是覆盖原有老版本，这个文件夹还是3.9.2那个：没明白神马意思
几乎不用 ipv6 测试，只用
（开机）启动XX-Net前即运行以下 bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

显示IPv6隧道是否正常，并借助观察系统任务管理器的网络流量。。。

**Comment by AnyWAT** [comment]
😂求 手把手教育，ipv6尚未连接 #10329
😱希望你在不断给予的同时可以让技术精益求精，3q，@AnyWAT
![image](https://user-images.githubusercontent.com/37962734/38368521-16c052b4-3918-11e8-918b-9ed92ea73d53.png)
![image](https://user-images.githubusercontent.com/37962734/38368459-effdb374-3917-11e8-8d44-2f1552a5ad44.png)

**Comment by AnyWAT** [comment]
😝70分的帮30分的，反被30分的说。。。

**Comment by dvp155** [comment]
很激动 。被我瞎弄成功。关闭6to4，isatap功能也许可以，希望帮助有需要的关于ipv6状态失效的情况。@AnyWAT
