### ISSUE TITLE
关于Mac上启用xx-net之后，AndroidStudio无法访问网络的问题。

### ISSUE THREAD

**Issue by kylin17** [XX-net/XX-Net#10322]
最近刚从windows迁移到mac不久，仍然使用xx-net来作为vpn，但遇到一个在windows上不会发生的问题。
在mac上启用xx-net之后，会修改网页代理到``127.0.0.1:8086``，结果导致AndroidStudio无法访问互联网，退出xx-net后重启AndroidStudio则恢复正常。
![xx-net proxy](https://user-images.githubusercontent.com/1879771/38283729-41451e9a-37ea-11e8-9d30-de8da87e3a7c.jpg)
![xx-net androidstudio](https://user-images.githubusercontent.com/1879771/38283753-5d870cda-37ea-11e8-9d26-ff2802fae509.jpg)
在AndroidStudio中导入证书或修改http代理到``127.0.0.1:8087``无果，求解决方案~~

**Comment by xxnet** [comment]
​怀疑是证书问题。
试试全局X-Tunnel，或者智能路由

**Comment by kylin17** [comment]
xx-net用的就是智能路由模式，浏览器插件用智能路由模式则直接提示``请检查浏览器代理设置``。

**Comment by kylin17** [comment]
X-Tunnel模式下，AndroidStudio同样无法访问网络。

**Comment by xxnet** [comment]
先确认X-Tunnel可用。
AndroidStudio访问网络时，看x-tunnel的日志，有没有请求，是否正常

**Comment by kylin17** [comment]
最终通过设置xx-net模式为``AUTO-GAEProxy``就可以正常使用了
![image](https://user-images.githubusercontent.com/1879771/38479774-fdc78118-3bf3-11e8-9df5-4fd197021ff8.png)

X-Tunnel稍晚一些我再试一下。
