### ISSUE TITLE
一会显示“尚未建立连接”，一会显示“一切正常，你可以访问真正的互联网了。”

### ISSUE THREAD

**Issue by bjtopgod** [XX-net/XX-Net#10326]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5155 ipv4:0 ipv6:1364
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by bjtopgod** [comment]
ip延迟也是一直跳，一会9999一会400多！但就是不能翻~

**Comment by AnyWAT** [comment]
手动检查所有IP？http://127.0.0.1:8085/?module=gae_proxy&menu=advanced

XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:999 ipv4:0 ipv6:841
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:77 h2:0
scan-ip-thread-num: 9
ip-quality: 250
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by bjtopgod** [comment]
检查IP后有效ip显示0
ipv6测试
这一项显示

测试运营商 DNS 是否接入 IPv6 |   | 超时 (16.172s)
-- | -- | --

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 运行结果（无需IP地址的2行）

**Comment by AnyWAT** [comment]
特地下了3.8.5，检查IP后
XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:999 ipv4:0 ipv6:151
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:67 h2:0
scan-ip-thread-num: 10
ip-quality: 266
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38288854-ad0dd200-3805-11e8-9bbc-78a62924d328.png)

DNS：
IPv4 – 1.1.1.1 & 1.0.0.1
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001

**Comment by weareyoungi** [comment]
我的这个IPV6很不稳定

**Comment by AnyWAT** [comment]
IPV6很不稳定，或许使用微软默认服务器会好些？

**Comment by AnyWAT** [comment]
🤣滚回3.10.4了

**Comment by bjtopgod** [comment]
@AnyWAT netsh int ipv6 show teredo 运行结果看哪一个啊？

**Comment by AnyWAT** [comment]
NAT : restricted 自己查查神马意思？
换服务器？管理权限运行 netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com.

**Comment by bjtopgod** [comment]
但是教程那个图片里这项显示的是
PortPreserving: 是

**Comment by bjtopgod** [comment]
@woosley @zhouxiaoxiaoxujian @AnyWAT @

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38297177-2e1ce65e-3826-11e8-8068-44c8dbe96808.png)

**Comment by AnyWAT** [comment]
只有 NAT：symmetric 才正常

**Comment by bjtopgod** [comment]
@AnyWAT 新手之前没有看过这些，但是之前一直都可以用，今天突然不能用了。。。那现在要怎么弄啊

**Comment by bjtopgod** [comment]
如果换服务器有什么影响啊？

**Comment by bjtopgod** [comment]
http://ju.outofmemory.cn/entry/94277你看这个教程，上面好像跟我一样啊

**Comment by AnyWAT** [comment]
看个头。如果换服务器有什么影响啊：不就是想害你，从不正常到正常呗😥

**Comment by bjtopgod** [comment]
@AnyWAT 那现在我怎么操作啊，我win7

**Comment by AnyWAT** [comment]
自己从我开始回复开始往下看🙃

**Comment by bjtopgod** [comment]
C:\Users\Administrator>netsh int ipv6 set teredo enterpriseclient win7.ipv6.micr
osoft.com
确定。

**Comment by bjtopgod** [comment]
@AnyWAT 没反应

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 运行结果（无需IP地址的2行）
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP，扫描一点时间

**Comment by bjtopgod** [comment]
类型                    : enterpriseclient
服务器名称              : win7.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能解析服务器名

**Comment by bjtopgod** [comment]
刚才还能显示啊。。。

**Comment by AnyWAT** [comment]
聪明反被聪明误——自作聪明😱

**Comment by bjtopgod** [comment]
@AnyWAT ??

**Comment by bjtopgod** [comment]
@AnyWAT 这咋办啊，头昏了

**Comment by AnyWAT** [comment]
😂去球，自作孽。。。

**Comment by bjtopgod** [comment]
@AnyWAT 
C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by bjtopgod** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5155 ipv4:0 ipv6:1068
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 2512
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by bjtopgod** [comment]
@AnyWAT 按你说的换了服务器啊，我自己改过来好像又有了

**Comment by bjtopgod** [comment]
@AnyWAT 现在看下吧

**Comment by bjtopgod** [comment]
5000多IP检查所有IP后有效IP显示0

**Comment by bjtopgod** [comment]
@AnyWAT 

IPv4 域名连接测试 |   | 成功 (0.354s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 超时 (16.971s)
双栈域名连接测试 |   | 成功 (0.365s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.347s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (0.350s) 使用 ipv4
无域名 IPv6 连接测试 |   | 超时 (16.905s)
IPv6 大数据包传输测试 |   | 超时 (16.887s)
测试运营商 DNS 是否接入 IPv6 |   | 超时 (16.868s)
查询 IPv4 运营商 |   | 成功 (0.228s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 超时 (16.018s)

**Comment by bjtopgod** [comment]
@AnyWAT 全部贴出来了，大神咋办啊~~~你一步一步说我一步一步来弄

**Comment by bjtopgod** [comment]
@AnyWAT 没有指示，我现在什么都不敢动了~

**Comment by bjtopgod** [comment]
@yctsang

**Comment by bjtopgod** [comment]
@SeaHOH

**Comment by bjtopgod** [comment]
@AnyWAT 大神还在吗？

**Comment by bjtopgod** [comment]
@AnyWAT 电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
yum模块管理 ：关闭 Smart Router
XX：取消全局代理
插件：GAE自动切换

这是要改dns吗？然后gae插件在哪里下载啊

**Comment by weareyoungi** [comment]
滚回稳定版要好些，我的这个IPV6好不稳定，经常好好的fail,然后怎么enable，结果都是unknown,希望作者大神把这个enable_ipv6重写一下，结果看不懂

**Comment by bjtopgod** [comment]
@weareyoungi 更新3.11.7的稳定版是不是就好了啊？

**Comment by weareyoungi** [comment]
@bjtopgod   
 已经OK，但是害怕再出问题，出去玩已经越来越难了。

**Comment by bjtopgod** [comment]
@weareyoungi 我更新下试试

**Comment by bjtopgod** [comment]
@AnyWAT 到底怎么弄啊，我怎么聪明反被聪明屋了，一直在按你的操作，不懂的问你你就说我聪明反被聪明误一脸懵逼

**Comment by veeson** [comment]
我的也是
```
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:136
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1174
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by AnyWAT** [comment]
我怎么聪明反被聪明屋了，一直在按你的操作：😋有图有真相？
![image](https://user-images.githubusercontent.com/37962734/38369240-db735812-3919-11e8-8eb6-bac9f0ca88d6.png)
![image](https://user-images.githubusercontent.com/37962734/38369390-2a629da2-391a-11e8-99e9-be0843691c27.png)

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
