### ISSUE TITLE
创建个人appid有什么好处吗？

### ISSUE THREAD

**Issue by zhaoruihao** [XX-net/XX-Net#10323]
个人appid和公用appid有什么不同

**Comment by caofengzi** [comment]
公共appid由於使用的人多所以有流量控制，個人的可以自由使用流量。

**Comment by kylin17** [comment]
公共appid数量有限，限制流量限制观看视频和下载。
请参阅[使用方法](https://github.com/XX-net/XX-Net/wiki/How-to-use#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)及[个人appid说明](https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids#%E8%AF%B4%E6%98%8E)

**Comment by SeaHOH** [comment]
这样 X 大就不能偷看你在干嘛了 :smile_cat:
