### ISSUE TITLE
IPv6测试 不对  Ip 数量700  延迟也是 700

### ISSUE THREAD

**Issue by lianbookca** [XX-net/XX-Net#10325]
![default](https://user-images.githubusercontent.com/15099252/38287317-a6ccd502-37fc-11e8-91f1-e5a5cb214aec.png)
![default](https://user-images.githubusercontent.com/15099252/38287021-f650699c-37fa-11e8-946d-af660ca59976.png)
![default](https://user-images.githubusercontent.com/15099252/38287031-fd425382-37fa-11e8-9410-b3d1360c497a.png)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10326

**Comment by lianbookca** [comment]
@AnyWAT 
路由器DNS 要改成  固定的啊     用XX 全局行 吗？  不用 GAE行吗 ?
模块管理  是什么东西啊

**Comment by AnyWAT** [comment]
用XX 全局行：自己试试
http://127.0.0.1:8085/?module=launcher&menu=config 模块管理

**Comment by lianbookca** [comment]
@AnyWAT 那你说 改DNS  都要改吗 ？
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001

**Comment by lianbookca** [comment]
@AnyWAT   延迟有点高吧 ？  

IPv6 IP数 | 1923
-- | --
XX-Net 状态 | 工作
IP延迟 | 717

**Comment by SeaHOH** [comment]
信息不足
#10328
