### ISSUE TITLE
提个问题，我已经懵逼了。。

### ISSUE THREAD

**Issue by JevonChu** [XX-net/XX-Net#10333]
照教程设置好后IPV6后，test-ipv6.com 的无域名 IPv6 连接测也能通过，但一打开XX-NET，再测试就失败了，这是正常的吗？？

![ss](https://user-images.githubusercontent.com/8470820/39360963-e311fdd8-4a0f-11e8-8865-fc62a61c3637.png)

**Comment by cccccry** [comment]
我也是从昨日开始突然这样，很奇怪

**Comment by AnyWAT** [comment]
Win7 ？貌似80端口不是被封了？非守着不一定适合你的 teredo.remlab.net ？

**Comment by AnyWAT** [comment]
Win7换服务器？管理权限运行
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com. default 3544  （换端口为3544）

**Comment by bjtopgod** [comment]
我3.8.5更新都更新不了，几次都是到三四十就不动了

**Comment by bjtopgod** [comment]
@AnyWAT 怎么同时换服务器又改端口啊，新手求教啊~
是不是在cmd直接输入netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com. default 3544 运行就行了？

**Comment by no-name2017** [comment]
@AnyWAT 你好，请问我照你的方法改了端口，现在想改回来，怎么操作？谢谢

**Comment by AnyWAT** [comment]
管理权限运行
netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com. default default

**Comment by SeaHOH** [comment]
`netsh interface teredo set state clientport=default`
