### ISSUE TITLE
一会显示“尚未建立连接”，一会显示“一切正常，你可以访问真正的互联网了！ip检测后有效IP变成0

### ISSUE THREAD

**Issue by bjtopgod** [XX-net/XX-Net#10332]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5155 ipv4:0 ipv6:1086
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 342
is-idle: 0
block-stat: Connect Blocked, 3 seconds to wait.
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

IPv4 域名连接测试 |   | 成功 (0.364s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 成功 (1.017s) 使用 ipv6 Teredo
双栈域名连接测试 |   | 成功 (0.375s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.359s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (0.344s) 使用 ipv4
无域名 IPv6 连接测试 |   | 成功 (0.925s) 使用 ipv6 Teredo
IPv6 大数据包传输测试 |   | 成功 (0.994s) 使用 ipv6 Teredo
测试运营商 DNS 是否接入 IPv6 |   | 超时 (16.851s)
查询 IPv4 运营商 |   | 成功 (0.303s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 成功 (0.309s) 使用 ipv6 Teredo ASN 29259

**Comment by bjtopgod** [comment]
求助啊，一天了没有用！
有个大神叫我换微软服务器，换了之后也米用，现在已经改过来了还是没用

**Comment by bjtopgod** [comment]
插件：GAE自动切换是什么？怎么弄出来啊？？

**Comment by bjtopgod** [comment]
@yctsang 我3.8.5更新都更新不了，几次都是到三四十就不动了

**Comment by yctsang** [comment]
https://github.com/XX-net/XX-Net/blob/master/code/default/download.md

**Comment by yctsang** [comment]
索性弄个全新的吧

**Comment by bjtopgod** [comment]
@yctsang 应该不是版本问题，好多人更新之后还是没有解决啊

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
