### ISSUE TITLE
ipv6 总是fail

### ISSUE THREAD

**Issue by cccccry** [XX-net/XX-Net#10331]
今年一直用3.8.2，用的好好的，一点问题没有。但从昨天开始就不能用了，ipv6各种fail，到咱们网站看帖学习，尝试做了无数次处理都不行。我是山东电信网络，难道我的ipv6被封了吗……

![qq 20180404174840](https://user-images.githubusercontent.com/38069534/38300976-dedd10fe-3830-11e8-8454-7f3b01ea76ab.png)
![qq 20180404174942](https://user-images.githubusercontent.com/38069534/38300977-df23afc8-3830-11e8-86d1-a1655cb465a3.png)
诊断结果：
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:6000 ipv4:2 ipv6:2701
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 754
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by leeonyan** [comment]
山东电信的没问题啊 鉴于你以前正常 猜测 你换微软的服务器吧

**Comment by SeaHOH** [comment]
#10328
