### ISSUE TITLE
按教程整的 IPv6  测试还是过不了啊

### ISSUE THREAD

**Issue by lianbookca** [XX-net/XX-Net#10342]
https://github.com/XX-net/XX-Net/issues/10282  用着这个软件 整的

![default](https://user-images.githubusercontent.com/15099252/38321619-a41be906-386a-11e8-8be8-6b41c993510b.png)
![qq 20180405004539](https://user-images.githubusercontent.com/15099252/38321692-db9126ee-386a-11e8-9102-016c7bb9f9d5.png)
![qq 20180405004550](https://user-images.githubusercontent.com/15099252/38321694-dc278044-386a-11e8-8410-e4bc46fbb2e3.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38321778-175c0cc0-386b-11e8-872e-352580e1d0c9.png)
![image](https://user-images.githubusercontent.com/37962734/38321815-35a37ff6-386b-11e8-857b-c64f8fd73fc8.png)

**Comment by lianbookca** [comment]
@AnyWAT 设置和你都对啊 延迟有点 高  
那你摘要  部分那？
刚才 测试 过了  第二次 没过  
![6666](https://user-images.githubusercontent.com/15099252/38322227-664cad84-386c-11e8-897d-7b4560bb2e14.jpg)

**Comment by AnyWAT** [comment]
黄色盲？

**Comment by lianbookca** [comment]
@AnyWAT   
盲 什么 图片 设定 和你的一让
测试没过 能看yt 视频 速度感人
![66666](https://user-images.githubusercontent.com/15099252/38322474-1fd2227a-386d-11e8-96d1-c2bd7659dabb.jpg)

**Comment by AnyWAT** [comment]
你我何时对比过，还一样😝
![image](https://user-images.githubusercontent.com/37962734/38322607-81d79626-386d-11e8-81cd-2936428ff628.png)

**Comment by lianbookca** [comment]
@AnyWAT  
没仔细看  按你 整了
可还是 测试 没过
![456](https://user-images.githubusercontent.com/15099252/38323064-cc0f9a94-386e-11e8-80fa-f5779316538b.jpg)
![6666](https://user-images.githubusercontent.com/15099252/38323067-ccad0e28-386e-11e8-94bb-2a8d702e6215.jpg)
![45677](https://user-images.githubusercontent.com/15099252/38323068-cd773ff4-386e-11e8-89ed-464afbad362c.jpg)

**Comment by lianbookca** [comment]
@AnyWAT  自带切换了 
是不 IP 延迟太高了  测试过不了啊
![456](https://user-images.githubusercontent.com/15099252/38323823-f70c8174-3870-11e8-98ac-a988bdf22f37.jpg)

**Comment by AnyWAT** [comment]
3.10.5-3.11.7得关闭“自动调整扫描线程”，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP

**Comment by SeaHOH** [comment]
不用 hosts，设置 IPv6 DNS 用处不大，而且一般 DNS 都会提供 IPv6 解析。
测试 teredo 用这个 #10328
