### ISSUE TITLE
6p@ios8.3已越狱，win7x64+chrome65+SwitchyOmega，电脑端没问题，手机不行。

### ISSUE THREAD

**Issue by qq275327347** [XX-net/XX-Net#10346]
研究了很多天，搜遍了Issue，手机端浏览器就是提示“请检查浏览器代理设置”，没办法，放弃了。
电脑端xxnet托盘选的是“取消全局代理”，后来又尝试了“全局PAC智能代理”，反正都不行。

**Comment by AnyWAT** [comment]
貌似“全局PAC智能代理”必须“启用 Smart Router”模块

**Comment by qq275327347** [comment]
@AnyWAT 智能路由模块一直开着的

**Comment by SeaHOH** [comment]
导入并信任证书
