### ISSUE TITLE
xxnet是彻底不能用了吗？昨天到现在没有恢复。。。

### ISSUE THREAD

**Issue by bjtopgod** [XX-net/XX-Net#10344]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5155 ipv4:0 ipv6:203
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:0
scan-ip-thread-num: 150
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

在你所在的地区，本站的测试结果并不可靠。

测试运营商 DNS 是否接入 IPv6 |   | 超时 (16.044s)

Teredo 参数

类型 : enterpriseclient
服务器名称 : teredo.remlab.net
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : qualified
客户端类型 : teredo client
网络 : managed
NAT : restricted
NAT 特殊行为 : UPNP: 否，PortPreserving: 否

**Comment by sd613** [comment]
再试试，刚才我的也不行，现在好了

**Comment by bjtopgod** [comment]
@sd613 怎么弄啊？

**Comment by bjtopgod** [comment]
@AnyWAT

**Comment by bjtopgod** [comment]
真的浪费时间啊~昨天弄一天到现在还不会弄~
求大神教一下~

**Comment by bjtopgod** [comment]
@AnyWAT 电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
yum模块管理 ：关闭 Smart Router
XX：取消全局代理
插件：GAE自动切换

全部按上面办了还是没用

**Comment by bjtopgod** [comment]
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 3544 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问主 teredo 服务器

**Comment by SeaHOH** [comment]
```
netsh interface 6to4 set state disable
netsh interface isatap set state disable
netsh interface teredo set state default
```

**Comment by haima11** [comment]
![qq 20180405131229](https://user-images.githubusercontent.com/26682473/38348207-0d39e5ba-38d3-11e8-8246-eb0eabd7ec3a.jpg)
可以用啊

**Comment by toobed** [comment]
ip6被彻底封杀？goproxy也完全不能用了

**Comment by bjtopgod** [comment]
@SeaHOH 
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 3544 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by bjtopgod** [comment]
急的我直冒汗~
重新下载最新版本全部解决了

**Comment by izhangza** [comment]
0.0

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
