### ISSUE TITLE
最新版本，之前使用正常，最近google账号登录不了。 能打开youtube 但是不能登录。

### ISSUE THREAD

**Issue by f18love** [XX-net/XX-Net#10349]
登录报错。

提示 多次重复导向

让清除浏览器cookies   

但是问题依旧

试过重新下载浏览器

试过 重新下载xx-net

**Comment by shishui12388** [comment]
同样的问题 ip大概50多个 可以上油管 但是一点登录提示”
登录YouTube时出错。点击此处排查问题。”

**Comment by Guowei1992** [comment]
切换到旧版本就可以登陆。我切换到3.9.6版本后可以登陆YouTube。

**Comment by martinbeyond** [comment]
只是.com打不开，.com.hk可以访问。

**Comment by zegzhi** [comment]
在 `config.json` 文件中增加下面内容。
``` 
 "hosts_direct_endswith": [
    "accounts.google.com"
  ]
```

**Comment by Tim-Xue** [comment]
@zegzhi 请问config.json这个文件在哪里找？

**Comment by zegzhi** [comment]
@Tim-Xue 在 `xxnet/data/gae_proxy/` 目录。
添加的时候注意在上以行末尾增加一个英文逗号，然后重启xxnet。
![tim 20180406135731](https://user-images.githubusercontent.com/16538800/38405471-9f7bb758-39a2-11e8-99e0-1b3a93088399.png)

**Comment by Tim-Xue** [comment]
@zegzhi 在请问一下，json的文件是用sublime Text3打开的吗？为什么我去官网下的时候，下不下来，提示我说“download.sublimetext.com 的响应时间过长。”

**Comment by zegzhi** [comment]
@Tim-Xue 记事本就可以。
我用的是Visual Studio Code

**Comment by Tim-Xue** [comment]
@zegzhi 哦哦，好的。那个你上面添加的代码好像是用来解决登陆google账号的吧？能不能用来解决无法登陆YouTube的问题？

**Comment by Guowei1992** [comment]
我这边有个奇怪的问题。
YouTube在登陆状态下加载不出内容；是空白页，切换chrome为隐身模式后YouTube又正常，IE浏览器也是同样。

**Comment by Tim-Xue** [comment]
@zegzhi 还能问你个问题吗？为什么我登陆之后，youtube后面有HK的后缀？这算正常吗？

**Comment by zegzhi** [comment]
@Tim-Xue 访问一下 https://www.google.com/ncr ，再打开Youtube试试。

**Comment by zegzhi** [comment]
@Tim-Xue 你是说图标后面有HK后缀？
如果是这样的话，只用在网页右下角设置里面把所在地改为美国就可以了。

**Comment by Tim-Xue** [comment]
@zegzhi 嗯呢，这是一方面，还有就是youtube的首页推荐给我的绝大多数是国内的视频，所以我想改了。改成美国之后，就好多了。真的很谢谢你。

**Comment by Phil-Chang** [comment]
@zegzhi 我的已经是3.11.7了

**Comment by zegzhi** [comment]
@Phil-Chang 这就不清楚了，按道理来说一定会有这个文件的。

**Comment by Phil-Chang** [comment]
@zegzhi 我是由之前的版本升级到3.11.7的，是不是要重新下啊

**Comment by dxdvid** [comment]
完美解决

**Comment by f18love** [comment]
感谢大神   改一下那个文件已经OK了

**Comment by AnyWAT** [comment]
系统升级，手动管理 (高级)，所有版本下载页面

**Comment by foho8080** [comment]
在 config.json 文件中增加下面内容。

 "hosts_direct_endswith": [
    "accounts.google.com"
  ]
為什麼我加這個不行 doc畫面變成紅色字體(正常時綠色或白色字體)和有一項白色字體寫著press enter to continue

**Comment by foho8080** [comment]
config.json這個打開是只有我的appid號

**Comment by zegzhi** [comment]
@foho8080 注意前一行末尾要加上逗号

**Comment by foho8080** [comment]
@zegzhi 已經在末尾加上逗号 請看圖
![0001](https://user-images.githubusercontent.com/17214241/39092522-3113fd28-4642-11e8-9ac5-534360fd2c13.jpg)

**Comment by foho8080** [comment]
@zegzhi 已經在末尾加上逗号 白色部分是我的appid 請看圖
![0001](https://user-images.githubusercontent.com/17214241/39092526-5ec525da-4642-11e8-9e09-83575c712a00.jpg)

**Comment by foho8080** [comment]
@zegzhi  我已經加逗號 白色部分是我的appid號  請看圖
![0001](https://user-images.githubusercontent.com/17214241/39092545-accbbd0c-4642-11e8-8ffb-7642408eea21.jpg)

**Comment by zegzhi** [comment]
@foho8080 你可以看看我上面的图。
1.所有内容都放在大括号内
2.逗号放在上一行末尾

另外：最新的 3.11.9已经解决了这个问题，不需要添加这一行。

**Comment by SeaHOH** [comment]
网页 UI 中修改不好吗，非要改 json 文件，小白改错了就启动不了。

**Comment by zegzhi** [comment]
@SeaHOH 主要是网页UI中没这个设置选项啊

**Comment by foho8080** [comment]
@zegzhi  我是3.11.9版本 能登陸gmail和youtube.就是輸入ID和密碼之後就不能登錄

**Comment by SeaHOH** [comment]
@zegzhi 智能代理设置

**Comment by AnyWAT** [comment]
貌似代理速度的锅😜😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by SeaHOH** [comment]
等待新版发布

**Comment by runqiwoo** [comment]
> @zegzhi 在请问一下，json的文件是用sublime Text3打开的吗？为什么我去官网下的时候，下不下来，提示我说“download.sublimetext.com 的响应时间过长。”

xxnet/data/gae_proxy/ 请问这个是Chrome的安装目录里面的路径吗，小白不懂，找不到哇
