### ISSUE TITLE
smart router的自动配置脚本局域网位置在哪？

### ISSUE THREAD

**Issue by Jerryliukz** [XX-net/XX-Net#10357]
我知道以前PAC的位置是http://127.0.0.1:8086/proxy.pac，新版smart router的位置是哪里？

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38419219-1e348032-39d2-11e8-94f7-2c9c9828aa36.png)
通过右键XX图标，全局。。。代理，查看IE或系统代理可知
smart router：http://127.0.0.1:8086
PAC：http://127.0.0.1:8086/proxy.pac

**Comment by Jerryliukz** [comment]
我想给iPad提供WiFi下的代理，以前就这么做的，突然有一天浏览器代理设置就不正常了

**Comment by AnyWAT** [comment]
🤣手机或电脑为手机提供代理服务，手机Wifi高级设置，通过分享者8087代理（整个）Wifi，解决了自身无法运行XX-Net的安卓4.2.2手机运行Twitter App、谷歌商店的问题😋

**Comment by Jerryliukz** [comment]
我是ios啊……

**Comment by AnyWAT** [comment]
触类旁通？

**Comment by Jerryliukz** [comment]
没现象也没问题。。就是想知道怎么用ios调用自动配置脚本。。

**Comment by AnyWAT** [comment]
问题——就是想知道怎么用ios（操作系统）调用自动配置脚本（或许不同版本不同做法？）

**Comment by Jerryliukz** [comment]
好吧。。我重开一个

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/10377#issuecomment-384923934
