### ISSUE TITLE
修改IPV6的DNS，系统提示要重启，重启之后又自动还原

### ISSUE THREAD

**Issue by lxf1009** [XX-net/XX-Net#10356]
WIN7系统，ipv4的DNS随便改，ipv6的DNS每次修改完都提示重启，重启后也改不成功。前几天还没这毛病，求求给位，谁懂，帮帮忙

**Comment by SeaHOH** [comment]
只是使用 XX-Net 不需要添加 IPv6 DNS，建议取消勾选适配器中的 IPv6 协议。
