### ISSUE TITLE
访问Youtube很慢，有一样情况的吗

### ISSUE THREAD

**Issue by no-name2017** [XX-net/XX-Net#10359]
能翻，就是播放youtube很慢，而且IPv6 teredo隧道检测总是超时，但就是能上。

**Comment by AnyWAT** [comment]
youtube 正常可达：自动480P

**Comment by asmosn** [comment]
3117一直延迟1000+

**Comment by AnyWAT** [comment]
3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
