### ISSUE TITLE
请问关于IPV6的检测，为什么总是跳过的状态

### ISSUE THREAD

**Issue by no-name2017** [XX-net/XX-Net#10350]
![ddddddddd333333333](https://user-images.githubusercontent.com/30927426/38375760-832c5810-3929-11e8-9a23-3505c474ca05.png)

无域名 IPv6 连接测试 |   | 跳过 (15.351s)

请问为什么这一项总是跳过呢？ 现在可以上youtube，但是速度太慢了，连接速度 100多Kbps
IPV6 IP ： 500 多个，延迟800+

请问是不是和上面那一项跳过有关，所以速度才那么慢？

**Comment by no-name2017** [comment]
![oooooooyyyyyyyyyy](https://user-images.githubusercontent.com/30927426/38377142-d7f2ceda-392c-11e8-865b-d2d3807d3f9a.png)

有人能解决吗？

**Comment by no-name2017** [comment]
@AnyWAT 请问大佬能解决吗？

**Comment by AnyWAT** [comment]
@no-name2017  贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by no-name2017** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:498
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:51 h2:0
scan-ip-thread-num: 100
ip-quality: 657
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


请问大佬，会不会是我teredo哪里设置出错了？我总感觉我的teredo设置有问题

**Comment by no-name2017** [comment]
![cnnnnnnnnnnnnnnnnnn](https://user-images.githubusercontent.com/30927426/38377966-ec6d6e7c-392e-11e8-816b-491c1f758d0f.png)

**Comment by AnyWAT** [comment]
总感觉我的teredo设置有问题：从截图看，只是那服务器对你不友好而已，#8915 tertdo.bat 自动（或手动）优选服务器
使用ping超时的微软服务器或许更稳定！(win7除外？) 管理权限运行
netsh int ipv6 set teredo enterpriseclient win1710.ipv6.microsoft.com. 
或
netsh int ipv6 set teredo enterpriseclient win1711.ipv6.microsoft.com. 
3.10.5-3.11.7得关闭“自动调整扫描线程”，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001

**Comment by no-name2017** [comment]
@AnyWAT 大佬，我的teredo的类型是enterpriseclient，和NAT是：restricted，这两项会有影响吗？
另外，我的端口也设置成了3544，DNS，扫描线程全调了，teredo服务器也换了8个了，感觉Youtube的速度还是100Kbps，很慢啊，还有其他方法吗？或者哪里出问题了？

**Comment by no-name2017** [comment]
@AnyWAT  我也不懂为什么总是跳过的状态，但是又能翻墙。如果重装teredo会正常吗？

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38379815-781f36bc-3934-11e8-99b0-fd7c43258a31.png)
通过：（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

NAT是：restricted 并没完全正常，symmetric 才是
没有重装 teredo 之说，启用即可，只是服务器的好坏？
很慢啊，还有其他方法吗：建议用回3.10.4，转换XX版本、或延时大代理卡顿时手动扫描IP

**Comment by AnyWAT** [comment]
我也不懂为什么总是跳过的状态：🙃回避有无国祸。。。

**Comment by AnyWAT** [comment]
🤣有图有真相？ #10350 #10348 #10295

**Comment by no-name2017** [comment]
以后每次重启之后，都要执行netsh int ipv6 add route ::/0 "有效的Teredo接口名称" metric=1再启动XX-Net，可以把它写入XX-Net目录中的start.bat中：

@echo off
netsh int ipv6 add route ::/0 "有效的Teredo接口名称" metric=1
SET PYTHONPATH=
"%~dp0%start.vbs" noconsole


这一步要设置吗？
这里：netsh int ipv6 add route ::/0 "有效的Teredo接口名称" metric=1 
是改成这样吗：netsh int ipv6 add route ::/0 "win10.ipv6.microsoft.com." metric=1

**Comment by no-name2017** [comment]
@xxnet  只能求助X大和各位大佬了
另外，我执行enable_ipv6.bat  发现好像挺多错误的？ 是不是要改注册表什么的？

**Comment by AnyWAT** [comment]
别理会。。。
没从  #10348 #10295 发现那狗屎 #10184 🤣

**Comment by no-name2017** [comment]
@AnyWAT 大佬，什么狗屎？等我明天过去帖子看看，早点休息吧！
