### ISSUE TITLE
【将您重定向的次数过多】谷歌首页打不开？

### ISSUE THREAD

**Issue by martinbeyond** [XX-net/XX-Net#10353]
> 该网页无法正常运作
> www.google.com 将您重定向的次数过多。
> 尝试清除 Cookie.
> ERR_TOO_MANY_REDIRECTS

-------------------------------
最近几天，打开www.google.com，显示这个，页面不能打开。
求解！谢谢！

**Comment by no-name2017** [comment]
这几天问题多多

**Comment by ahhh111222** [comment]
昨天也是这样，后来无意点了一下https://www.google.com/ncr，就可以正常打开了，也不知道为什么

**Comment by Wybxc** [comment]
google 由于性质特殊，要手动指定 https 才能打开。
用`https://google.com`代替。
