### ISSUE TITLE
感觉XXNET  要挂了， 最近延迟高的吓死人， 看起来这个问题亟待解决

### ISSUE THREAD

**Issue by gnehc05** [XX-net/XX-Net#10362]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | OK
IPv4 IP数 | 0
IPv6 IP数 | 464
XX-Net 状态 | 工作
IP延迟 | 1062
连接池(帮助) | 新:0 h1:33 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 200

我看 油管一个52分钟的视频， 卡的看了2小时还没有看完！！！    无语死了

**Comment by AnyWAT** [comment]
扫描放到最大40/50

**Comment by asmosn** [comment]
我也后悔从3104升级3117，3117(WIN7)速度不如手机3104（Xndroid），现在电脑上重装老版本初始运行都登录错误：602...

**Comment by AnyWAT** [comment]
😱楼上贴 code 目录的图

**Comment by asmosn** [comment]
![qq 20180407105034](https://user-images.githubusercontent.com/9925193/38450531-e68a4894-3a51-11e8-8ddc-5b8afdea0bae.png)
大倒车奇迹般后复活了。。。

**Comment by lkyyang** [comment]
@asmosn 哪一个版本？

**Comment by jianeddie** [comment]
![default](https://user-images.githubusercontent.com/33176763/38462314-8de0922c-3b17-11e8-9f45-8ee136bd559d.png)

额，导出IP，清空good_ip.txt，再重新导入，发现延迟降到了100

就是实际效果不太清楚

**Comment by AnyWAT** [comment]
以前被告知：假象、假象、假象🤣

**Comment by AnyWAT** [comment]
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值？）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
😜3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。
