### ISSUE TITLE
谷歌自己的网站打不开

### ISSUE THREAD

**Issue by Anudorannador** [XX-net/XX-Net#10367]
最近谷歌老是打不开，于是找来了一堆被屏蔽的网站，结果发现只有谷歌自己旗下的网站打不开，包括但不限于搜索、邮箱、YouTube (仅能打开网页，不能播放视频) 等。
而其他网站代理貌似没什么问题。

属性|值
-- | --
XX-Net Version | 3.11.7
OS System | Windows
OS Version | 10.0.16299

**Comment by GoodSake** [comment]
gae的目标是啥呀

**Comment by CrawlingCaterpillar** [comment]
XX-Net本地启动了，Google搜索啥的也正常，就是速度慢，
我想配置自己的AppID，
但是https://console.cloud.google.com/start一直打不开，这就纳闷了

**Comment by AnyWAT** [comment]
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值？）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
😜3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。

**Comment by SeaHOH** [comment]
信息不足
