### ISSUE TITLE
3.10.4一直显示尚未建立连接，IPV6:Fail

### ISSUE THREAD

**Issue by Zhouhaikang** [XX-net/XX-Net#10365]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by Zhouhaikang** [comment]
状态一开始显示：probe，隔不久又变成：offline了。

**Comment by Zhouhaikang** [comment]
求助大神。

**Comment by Zhouhaikang** [comment]
teredo状态：一开始是dormant,打开XX-NET后立马就变成了probe,然后就 变成offline了，虽然每次刷bat能够刷回dormant.但是一旦打开XX-NET又变成probe/offline了，头疼。

**Comment by GoodSake** [comment]
不是你用的dns被攻击了，就是teredo被攻击了，换一下别的吧

**Comment by GoodSake** [comment]
或者等攻击停下，或防御启动，等着就自动恢复了。

**Comment by GoodSake** [comment]
攻击者是消耗十几亿大国的军费，防御者是资本主义的奸商，力量与耐力的比拼。我觉得不稳定是正常的。

老铁们，同意的666双击关注！！！！！！！！！

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10360#issuecomment-379326062

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引
#10328
