### ISSUE TITLE
XX-Net 3.11.7，一切正常，你可以访问真正的互联网了。但还是上不去啊

### ISSUE THREAD

**Issue by aoyoo111** [XX-net/XX-Net#10363]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.4549.400 QQBrowser/9.7.12900.400
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:499
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:35 h2:0
scan-ip-thread-num: 100
ip-quality: 1171
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
ip-quality: 1171 延时太大🤣
3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX版本、或延时大网络卡顿，得手动 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001

**Comment by aoyoo111** [comment]
@AnyWAT 延迟确实高

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
