### ISSUE TITLE
3.11.7最近ipv6,经常fail,证书也时不时fail,ip变500了.....

### ISSUE THREAD

**Issue by ORO44** [XX-net/XX-Net#10364]
..........

**Comment by AnyWAT** [comment]
SwitchyOmega 添加未加载资源走。。。

**Comment by ORO44** [comment]
SwitchyOmega 设置是代理模式，之前设置自动模式也没事，关键是现在IPV6时好时坏。

**Comment by AnyWAT** [comment]
3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程（40-50？），转换XX版本、或延时大网络卡顿，得手动 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001

**Comment by SeaHOH** [comment]
#10328
