### ISSUE TITLE
ipv6 failed

### ISSUE THREAD

**Issue by NanaseRuri** [XX-net/XX-Net#10368]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3659 ipv4:1 ipv6:3381
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 318
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

Teredo参数
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

**Comment by AnyWAT** [comment]
3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 PAC模式，IPv6 IP数上限1000，扫描放到最大40/50，IP延迟330-350，自动480P流畅
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001

**Comment by AnyWAT** [comment]
🤣IP延迟较小时的 good_ip.txt 备份保存以防不时之需！

**Comment by SeaHOH** [comment]
#10328
