### ISSUE TITLE
貌似翻牆入刑的”法律“依據來啦？！

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#10373]
![image](https://user-images.githubusercontent.com/37962734/38453094-a5b74ebc-3a82-11e8-80ac-8ed4b705fdba.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38453194-482e3f24-3a84-11e8-80b6-6ae3af78cadf.png)

**Comment by applestone** [comment]
关于进口车的渠道问题早就不是什么秘密问题了

**Comment by GoodSake** [comment]
cn把us教坏了，那个什么网络中立法不是要废除吗，废除后就是ISP都可以大搞gfw了，什么屏蔽baidu，什么直接断你bittorrent......。

我觉得法啊，没什么了不起，不都是人制定的吗，等有了言论自由，都会被推翻或重立的。

**Comment by no-name2017** [comment]
迟早的事，庆丰年代，只会更左。之前重庆早就出台了使用VPN算违法的规定，几个梯子的开发者维护者，要么被警告，要么被抓，该来的始终要来。

**Comment by rothen80** [comment]
看了下 貌似是针对没有执行实名注册的网站和拒绝提供用户信息的公司的法规，没有针对个人的条例，楼主是怎么和翻墙联系到一起的？如果想完全堵住，何不干脆把对外连接完全切断。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38463017-ae4d2dd0-3b22-11e8-98ec-ee2b962191de.png)

**Comment by GoodSake** [comment]
代工啊，cn不厉害的不多(tormach,mazak)，tw的台积电(intel,nvideo,qualcomm)和富士康(apple)还可以。

**Comment by moonza** [comment]
管理员干啥呢？这贴是想让XXNET彻底凉透是吗？

**Comment by GoodSake** [comment]
这是反gfw同盟军交流，心胸不宽，早晚会被收编哦。哈哈哈

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38464031-42851d80-3b39-11e8-9724-edf8502f3c22.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38464312-3d94109c-3b3e-11e8-83af-a1921fba0938.png)
![default](https://user-images.githubusercontent.com/37962734/38464316-45646cd6-3b3e-11e8-836d-338afd9d6287.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38466796-184cf556-3b61-11e8-87e4-c842534f6872.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38468984-58cbaff4-3b80-11e8-801a-b209f360ae29.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38469020-f0b3fb6e-3b80-11e8-9179-e7e5940ade81.png)

**Comment by AnyWAT** [comment]
转：中國又成最大赢家！美帝继给我们争取来了双休日之后，又一次给我们送来了福利，中國将取消贸易壁垒，也就是说，以后我们不用去香港、澳门、台灣以及周边國家去疯狂购物了，中國关税如果降到WTO的2.5%的标准，國内的大部分进口商品和周边國家和地区的价格一样便宜！
![default](https://user-images.githubusercontent.com/37962734/38469524-bfd8b4f0-3b88-11e8-8181-af601a90c66a.png)
![default](https://user-images.githubusercontent.com/37962734/38469529-c7d9228e-3b88-11e8-883f-ec60d7df5d70.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38488142-085272ca-3c15-11e8-8702-6e936dd57533.png)

**Comment by 117649** [comment]
我觉得你对床普有太多不切实际的幻想了，他是美国总统不是来给全世界无产阶级当圣人的，而且贼精，中共的个性从来按自己的规矩来，床普算准了中共借他收缩的时侯拉拢欧洲的时机找一把面子回来而已，才不会把个支那仔当回事

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38533761-5fb78a76-3cad-11e8-9b91-3eea3a9a5b89.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38537158-a41c6aa8-3cbf-11e8-8715-1c3166722687.png)
![default](https://user-images.githubusercontent.com/37962734/38537172-b27595d4-3cbf-11e8-80a7-abbe754373b6.png)
![default](https://user-images.githubusercontent.com/37962734/38537188-cdb4f470-3cbf-11e8-8dc4-4b8378e94f87.png)

**Comment by AnyWAT** [comment]
🤣转：贸易战应该算结束了，口水仗可能还要打几天。现在最大的分歧在于：中国开放市场的功劳属于谁？ 一个说是我逼的； 一个说是我主动！
![default](https://user-images.githubusercontent.com/37962734/38545234-2da3de7a-3cdc-11e8-98ae-f1d817f0c4e5.png)
![default](https://user-images.githubusercontent.com/37962734/38545253-3729b672-3cdc-11e8-9331-0615383b88cd.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38587444-0a29b276-3d54-11e8-983e-180a5acedde8.png)

**Comment by AnyWAT** [comment]
🤣RT @qq196837【当地时间4月10日，脸书创始人扎克伯格在美国国会接受听证。就数据泄漏事件，他再次公开道歉。然而，议员并未打算放过他，议员杜宾一连串的尖锐提问让扎克伯格略显尴尬：你能告诉大家，昨晚住哪家酒店嘛？最近和谁通信？】 很想看到李彦宏或马化腾被公开质询时的反应。 pic.twitter.com/BoHPdTZCor

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38616017-2de8c4f6-3dc5-11e8-89ca-47253121390d.png)

**Comment by AnyWAT** [comment]
😱转：我不相信任何一个民族能够永远被奴役，宣传机构可以用谎言填充他们的思想，否认真理达数代人之久，但人们在漫长黑夜中被迷惑、冻结的灵魂会由于不知来自何处的火花而觉醒，立刻，谎言和压迫的构架将因此而受到审判，被奴役的民族永远也不要绝望。  ——丘吉尔
![image](https://user-images.githubusercontent.com/37962734/38616506-d11445b4-3dc6-11e8-9066-fe70b321d3ee.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38616748-aacf1d1a-3dc7-11e8-84c7-f0defe721547.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38617291-34af600c-3dc9-11e8-9139-130b42b3e807.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38617553-ea1d3ad6-3dc9-11e8-844c-ddc31b12476b.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38620179-757c1e66-3dd0-11e8-8d5e-3913203e5ed0.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38645821-0a47f0dc-3e18-11e8-851e-fb4af467c346.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38653270-85778690-3e3c-11e8-8d19-95f12d74a28f.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38654434-e4aa00b6-3e41-11e8-885b-c3d03146d7ff.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38671956-6f0f1880-3e7f-11e8-970c-60cef53e6f8f.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38676436-96474d60-3e8d-11e8-8ec2-3dcccd64b946.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38709926-430a649e-3ef0-11e8-841c-f2c12f35ecec.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38722892-09a3f746-3f32-11e8-8640-85814bb77d92.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38728300-19ca6b9a-3f42-11e8-8bb4-c5713d6409c7.png)
