### ISSUE TITLE
新人，connected link一直是0，求解

### ISSUE THREAD

**Issue by ACTheking** [XX-net/XX-Net#10379]
-----------问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
xxnet-version: 2.7.0
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000,1047
connected-link: 0,0
ip-connect-interval: 8
scan-ip-thread-num: 0
ip-handshake-10: 129
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by no-name2017** [comment]
哪里可以看connected link

**Comment by AnyWAT** [comment]
哪里可以看connected link：较低版本，连接池？

**Comment by no-name2017** [comment]
噢噢

**Comment by no-name2017** [comment]
大佬总是那么晚睡觉的吗

**Comment by AnyWAT** [comment]
少年睡不醒，老人睡不着😋

**Comment by ACTheking** [comment]
谢谢各位大佬

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引
#10328
