### ISSUE TITLE
x-tunnel明天就要到期了，不知道还要不要续费。

### ISSUE THREAD

**Issue by waitingHao** [XX-net/XX-Net#10374]
最近太不稳定了，只是偶尔能用。
300G都没用几G，续费又怕一直都不稳定。

**Comment by GoodSake** [comment]
续吧。
就一天了。。。。下次记得提前3个月给大家送流量！！！

**Comment by AnyWAT** [comment]
IPv6隧道正常——GAE正常——X-Tunnel 正常
3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40/50，IP延迟330-350，自动480P流畅
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
3.10.4 IPv6 IP数上限1000，扫描线程最大20，IP延迟250，自动480P流畅

**Comment by waitingHao** [comment]
@GoodSake 之前还真的考虑要不要发出来问谁要的，不过最后只是问了朋友而已。

**Comment by xxnet** [comment]
​不稳定的原因，估计是cloudflare 干扰造成的，能建立连接，但是无法使用。
明天发个版本改进这个问题。

**Comment by waitingHao** [comment]
期待。
