### ISSUE TITLE
还是版本回滚比较好，这几天11.7突然就无法正常工作了，CA证书无法导入，从而导致连接问题

### ISSUE THREAD

**Issue by fengzean** [XX-net/XX-Net#10372]

**Comment by AnyWAT** [comment]
来回滚滚更健康😂

**Comment by AnyWAT** [comment]
🤣IP延迟较小时的 good_ip.txt 备份保存以防不时之需！

**Comment by Zmm1977** [comment]
现在墙越来越高了。。。。dns污染很难搞定的

**Comment by fengzean** [comment]
已经回滚到3.10.0

**Comment by AnyWAT** [comment]
3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX版本、或延时大网络卡顿，得
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 PAC模式，IPv6 IP数上限1000，扫描线程最大40/50，IP延迟330-350，自动480P流畅
？电脑DNS：
IPv4 – 1.1.1.1 & 1.0.0.1 （路由器也设置此值）
IPv6 – 2606:4700:4700::1111 & 2606:4700:4700::1001
3.10.4 PAC模式，IPv6 IP数上限1000，扫描线程最大20，IP延迟250，自动480P流畅
#10357

**Comment by AnyWAT** [comment]
😂貌似要么3.10.4，要么3.11.7

**Comment by applestone** [comment]
@AnyWAT 
用了你介绍改DNS的方式，但是没有效果，不知道你的网络是哪家的？地区也可能不同限制。北京联通的部分地区已经不行了，青岛联通的全部不行了

**Comment by AnyWAT** [comment]
湘移动

**Comment by AnyWAT** [comment]
80.80.80.80
80.80.81.81
。。。。。。
#google ipv6 dns:
2001:4860:4860::8888
2001:4860:4860::8844

#opendns ipv6 dns:
2620:0:ccc::2
2620:0:ccd::2

#HE ipv6 dns:
（2001:470:0:78::2）
2001:470:20::2

**Comment by applestone** [comment]
@AnyWAT 
我特别想知道你的网络提供商和地区

**Comment by AnyWAT** [comment]
😝网警查水表？

**Comment by no-name2017** [comment]
哈哈，他不是要查水表，好像是另一个帖子的楼主

**Comment by AnyWAT** [comment]
刚才3.11.7死掉，已滚回3.10.4😂
