### ISSUE TITLE
如何在ios上用wlan调用pc端的自动配置脚本?

### ISSUE THREAD

**Issue by Jerryliukz** [XX-net/XX-Net#10377]
我知道以前PAC的位置是http://127.0.0.1:8086/proxy.pac，新版smart router的位置是哪里？远程控制端当然开启了，问题是浏览器代理配置在ios上显示错误……

**Comment by freebacao** [comment]
证书安装了没?信任了没?

**Comment by SeaHOH** [comment]
位置没变，按楼上说的导入并信任证书。
