### ISSUE TITLE
脑壳痛，现在到底应该咋整？？？

### ISSUE THREAD

**Issue by BjeeJean** [XX-net/XX-Net#10380]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  是

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  打不开

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  看不懂

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
看不懂，没找到

* 简单描述遇到的问题：

【 性别：女，电脑水平：会使用，翻墙专业知识：比看门大爷和隔壁同事略懂；
浏览器：Chrome，宽带：联通，坐标：北京

从来没在讨论区提过问，这次也是被逼疯了……

宝宝最早是用GoAgent的，从它挂了以后开始用XX-Net，好多年了，一直很稳定（除了举国同庆节日和被迫举国同庆节日以外）。
去年开始XX-Net也不太好用了，IPv4挂了，大家开始弄IPv6。我也试图设置但完全看不懂所谓的教程。即便如此，后来多数时候惊喜的发现不管他自己也会出现“IPv6：OK”然后就可以用了，所以当“IPv6：Fail”的时候我就等着先不用了。
自从IPv6开始，更新和设置的成功与否就随缘了，所以我就选择不更新，我上一个版本是3.6.13是去年10月弄得，一直到今年年初都还好好的。然后到了今年3月初两会“举国同庆”，我就一如既往的等开完会，结果会开完了还是不能用。看了讨论区（一知半解）猜测是不是版本太老了就更新了3.11.3（2018年3月23日），开了轮子传ID，但是验证google账户密码的页面一直没出现，当时想也许刚开完会政要们还没回家再等等吧。
今天，想着再把XX-Net设置一下吧，于是更新了最新的3.11.7，结果开心了，不止google账户验证弹不出，现在干脆连设置页面也转不出了！我把Proxy SwitchyOmega的设置用新包里的bak重新导入了，甚至把原来的Proxy SwitchyOmega删了用新包里的重新安装了，还是打不开设置页面。轮子开着和关了，Proxy SwitchyOmega里“直接连接”、“系统代理”以及三种通道模式都试过了，依然打不开设置页面。“http://localhost:8085/”和“http://127.0.0.1:8085/”都一样打不开……

所以，综上，我想知道对于我这样的知识储备水平来说，这XX-Net是不是没法用了？？？实在不想从此一直用轮子产品，虽然我不大相信会被查水表，但也从心理层面觉得有点膈应，毕竟咱还是个一心为民族复兴中国梦感到自豪的普通小老百姓，希望翻墙的时候多少能堂堂正正一些……

要是XX-Net真的没法使了，各位大神能不能推荐点比较脑残好设置又免费稳定的翻墙软件了，万分感谢！
（泪奔……） 】

* 做过哪些尝试：
[ 今天，想着再把XX-Net设置一下吧，于是更新了最新的3.11.7，结果开心了，不止google账户验证弹不出，现在干脆连设置页面也转不出了！我把Proxy SwitchyOmega的设置用新包里的bak重新导入了，甚至把原来的Proxy SwitchyOmega删了用新包里的重新安装了，还是打不开设置页面。轮子开着和关了，Proxy SwitchyOmega里“直接连接”、“系统代理”以及三种通道模式都试过了，依然打不开设置页面。“http://localhost:8085/”和“http://127.0.0.1:8085/”都一样打不开…… ]

* 请贴出对应模块的状态页
打不开

* 请贴出相关的日志
打不开

**Comment by AnyWAT** [comment]
😂敏感词而已？

**Comment by SeaHOH** [comment]
关掉也可以回复，的确中了关键字被机器人关闭。
