### ISSUE TITLE
既然xx-net里面有谷歌IP段。。为什么GFW不把全部IP段都封了 还让你翻?...

### ISSUE THREAD

**Issue by Gongqiao24** [XX-net/XX-Net#10381]
IPv4的死应该就是把全部谷歌IPv4的谷歌IP段全部屏蔽吧？？？哪有没有可能把全部谷歌IPv6地址全部屏蔽掉。。。

**Comment by GoodSake** [comment]
如果google ip 段都是adsl的动态IP呢，一个IP单独占一个段，哈哈哈。技术问题不是聊天词汇表面那么单纯的。单纯是为了交流的方便。

**Comment by GoodSake** [comment]
其实屏蔽也是真正意义的屏蔽，只不过是入侵检测，丢包，掉包。。。。

**Comment by no-name2017** [comment]
作为谷歌认证的，流量断流次数最多的国家，给你切断海底光缆都有可能。中东诸如伊朗等独裁国家，好歹只是屏蔽了谷歌的个别产品，而某国几乎全灭。 https://transparencyreport.google.com/traffic/overview?expand=ALL   可以参考这里，可见我们生活得多么幸福。

**Comment by Gongqiao24** [comment]
@GoodSake 学到了。。。我以为整段都是谷歌的。。

**Comment by AnyWAT** [comment]
😱小老师傅👍

**Comment by no-name2017** [comment]
![wwwwwwwwwwwwweeee3333333](https://user-images.githubusercontent.com/30927426/38464143-06550666-3b3b-11e8-9877-a31a0ce90e97.png)

根据谷歌的流量报告，还是红色大国的人民幸福啊。

**Comment by waitingHao** [comment]
@no-name2017 朝鲜呢？

**Comment by AnyWAT** [comment]
朝鲜白色恐怖😋

**Comment by no-name2017** [comment]
@waitingHao  你以为朝鲜没互联网？ 要知道朝鲜黑客是有名的。谁是全球倒数第一，一目了然。幸福感满满的。

**Comment by waitingHao** [comment]
@no-name2017  我以为朝鲜不是人人都可以上谷歌。原来每个人都能上啊？真让我涨见识了。

**Comment by no-name2017** [comment]
@waitingHao 朝鲜网络和你朝的特供食品一样，是屁民享用不到的。

**Comment by waitingHao** [comment]
@no-name2017 我说没有，你说有，我说有你又说用不到。用不到你还跟我谈互联网，你真的不是来搞笑的么？

**Comment by no-name2017** [comment]
@waitingHao 你智商有问题吗？随便找部朝鲜的纪录片都知道朝鲜百姓没有互联网，我在上面都说了，朝鲜的互联网是特供产品，还不懂意思？谷歌统计的时流量中断的问题，只要朝鲜特供的网络有流量到达谷歌，谷歌就不标红，说那么清楚还不懂，建议你去看脑科了。

**Comment by no-name2017** [comment]
另外，谷歌为什么不标红，你去问谷歌就好，问我有个卵用。

**Comment by waitingHao** [comment]
@no-name2017 我说朝鲜不标红只是个玩笑，不是认真地在问为什么，什么情况又不是不知道。😂我看过脑科才过来问的，没问题，所以可能是你的脑有问题了。

**Comment by no-name2017** [comment]
真tm无聊，中国网络自由全球第一行了吧，满足你。谁有这闲功夫在这和你扯。另外，我那句话没问题谢谢。朝鲜有黑客。中国的网络自由全球倒数第一，懂？

**Comment by AnyWAT** [comment]
🤣楼主，关门打。。。
