### ISSUE TITLE
无法改teredo类型一直是client

### ISSUE THREAD

**Issue by yifenghanjinyong** [XX-net/XX-Net#10384]
Teredo 参数
---------------------------------------------
类型                    : client (Group Policy) 
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified  (Group Policy) 
状态                    : offline
错误                   : 客户端位于托管网络中
然后就一直不能上IPv6
有没有大神帮忙看一下，万分感激

**Comment by AnyWAT** [comment]
贴XX-Net诊断信息

**Comment by yifenghanjinyong** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4765 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:1
scan-ip-thread-num: 40
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
@Tim-Xue 贴 netsh int ipv6 show teredo 运行结果，XX-NET代理及插件模式的选用？

**Comment by Tim-Xue** [comment]
@AnyWAT 啊？小白不是很会，这怎么弄？大神求指点。。。

**Comment by AnyWAT** [comment]
CMD窗口运行。。。
右键任务栏XX-Net图标选用的。。。
浏览器代理插件选用的。。。

**Comment by Tim-Xue** [comment]
@AnyWAT 
![default](https://user-images.githubusercontent.com/38043364/38469404-a49c8312-3b86-11e8-99a3-f89c584d60b0.PNG)
选的是PAC智能代理
浏览器插件没用代理（之前用了Proxy SwitchyOmega，但是好像不能上国内的网，就禁用了）
![1](https://user-images.githubusercontent.com/38043364/38469420-fb68d10a-3b86-11e8-9573-5d55ea2bbac8.PNG)

**Comment by AnyWAT** [comment]
已禁用代理插件，XX-Net“全局PAC智能代理”，http://127.0.0.1:8085/?module=launcher&menu=config 模块管理，启用 Smart Router 必须ON
管理权限运行 netsh int ipv6 set teredo enterpriseclient default
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP

**Comment by Tim-Xue** [comment]
@AnyWAT 那个Smart Router 原先就是ON
然后检查IP的结果：
![1](https://user-images.githubusercontent.com/38043364/38469548-11fcc7ee-3b89-11e8-9ee0-ed2861c455e0.PNG)

**Comment by AnyWAT** [comment]
检查IP的结果自己看就行，正常了？

**Comment by Tim-Xue** [comment]
@AnyWAT 我现在的问题有着些个：
1.ipv6经常会fail
2.就是那个代理经常会挂，但是等个十来分钟，它自己又会自动会好
大神，请问这些是什么原因？

**Comment by AnyWAT** [comment]
😜3.10.5-3.11.7得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38469890-52303792-3b8e-11e8-80ae-f2ad4a14e3bf.png)

**Comment by Tim-Xue** [comment]
@AnyWAT 好的，谢谢大神。

**Comment by yifenghanjinyong** [comment]
@AnyWAT试了一下好像还是没有变化

**Comment by AnyWAT** [comment]
爬楼改小IP上限，推出重开XX，检查IP

**Comment by AnyWAT** [comment]
爬楼改小IP上限，退出重开XX，检查IP

**Comment by yifenghanjinyong** [comment]
@AnyWAT 什么是爬楼改小IP上限？

**Comment by yifenghanjinyong** [comment]
@AnyWAT已经弄好了，谢谢大神

**Comment by Joeylon** [comment]
各位大神帮我看看这个是咋回事呢，我的ipv6明明是打开的啊
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:500
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 450
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）

**Comment by Joeylon** [comment]
**运行结果如下：**
类型                    : client
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by AnyWAT** [comment]
use-ipv6: auto 改为仅 ipv6
scan-ip-thread-num: 10 增大4-5倍，关闭“自动调整扫描线程”
管理权限运行 netsh int ipv6 set teredo enterpriseclient default
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP。。。扫描一定时间优于 ip-quality: 450

**Comment by Joeylon** [comment]
还是不行，提示仅ipv6不可用。。。。
检查ip后有效iP数为0。。。

**Comment by AnyWAT** [comment]
禁用再启用网络，手动检查IP。。。
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by Joeylon** [comment]
OK 啦谢谢:)，不过IP不多。
Gmail不能回复邮件是什么鬼

**Comment by Joeylon** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : none (global connectivity)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
不过IP不多：程序默认上限500，能多到哪去？
服务器名称 : win10.ipv6.microsoft.com 😂应该有尾巴英文句点的
NAT : none (global connectivity)😱首次见到，不明
😜爬楼，温故而知新

**Comment by AnyWAT** [comment]
@Joeylon https://github.com/XX-net/XX-Net/issues/10407#issuecomment-379979519

**Comment by SeaHOH** [comment]
本机拨号，公网 IP。

**Comment by AnyWAT** [comment]
👍学习了，谢谢大海GG

**Comment by SeaHOH** [comment]
#10328
