### ISSUE TITLE
为什么刚申请并部署的AppId就显示流量已用完？

### ISSUE THREAD

**Issue by WuYufeng233** [XX-net/XX-Net#10386]
我还没开始用呢就说我appid流量已用完，为什么呢！？

**Comment by SeaHOH** [comment]
遇到这种情况，先访问 `https://appid.appspot.com` 看响应什么内容。

显示服务端信息：正常
404：AppID 不存在
503：流量用完

**Comment by WuYufeng233** [comment]
503，可为什么还没用就没有流量了呢？

**Comment by SeaHOH** [comment]
旧 AppID？

**Comment by WuYufeng233** [comment]
我的谷歌账号都是昨天才申请的，难道appid和其他用户之间相同也会冲突的？！

**Comment by WuYufeng233** [comment]
emmm.这就很奇怪了。。。我继续摸索看看，谢谢各位

**Comment by THLIVSQAZ** [comment]
app engine可以查日志，所有的请求以及请求的ip。 
你可以登陆控制台查看

**Comment by SeaHOH** [comment]
关闭会仍可回复
