### ISSUE TITLE
以下僅供參考(win7 8.1 10都可以) 試了幾天暫時還可以

### ISSUE THREAD

**Issue by foho8080** [XX-net/XX-Net#10382]
1.先在ipv4 dns 1.1.1.1和1.0.0.1 再ipv6 DNS 2606:4700:4700::1111和2606:4700:4700::1001
2.打開控制面板--時鐘.語言和區域----區域和語言----位置-----當前位置不要選擇中國和港澳.其它都可以
![0001](https://user-images.githubusercontent.com/17214241/38464524-ab3cab10-3b41-11e8-8855-4dbb9c673a34.jpg)
試了幾天暫時還可以

**Comment by AnyWAT** [comment]
😱转：上网困难时，请把手机操作系统语言转换为主流外语(以英语为主的几种语言)操作系统，可以有效的增强翻墙功能。

**Comment by whhxmwhh** [comment]
试试看了。当回台湾人。

**Comment by whhxmwhh** [comment]
试试看了。当回台湾人。

**Comment by AnyWAT** [comment]
卡顿，同样内容自动给来个N遍👌
