### ISSUE TITLE
【请问】test-ipv6.com，测试没有检测到 IPv6 地址，是不是就搞头呢？？？？？？

### ISSUE THREAD

**Issue by kapans** [XX-net/XX-Net#10390]
以前是好的，但从上周开始xx-net里面ipv6就是unknow，之后就变成fail

test-ipv6.com
测试没有检测到 IPv6 地址

使用这个方法换了通道还是通不过监测
https://github.com/XX-net/XX-Net/issues/10282
是不是没搞头了？

哎。。。

**Comment by AnyWAT** [comment]
贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/10328
试试这个脚本，测试你的网络是否**还**支持 teredo。

**Comment by AnyWAT** [comment]
😜海GG，非程序员想运行 *.py 有些难呢，尽管谷歌了。。。

**Comment by SeaHOH** [comment]
刚加了用 XX-Net 自带 Python 的脚本。其实安装一个 Python 很简单的，一路 Next。

**Comment by kapans** [comment]
请问这个dormant是啥意思？休眠状态？
另外，我的组策略全是未配置的，应该没问题的。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.2000 Chrome/30.0.1599.101 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
需要等待几十秒

**Comment by SeaHOH** [comment]
你运行的结果是什么？ @kapans

**Comment by AnyWAT** [comment]
正常等待3-5秒🆗

**Comment by AnyWAT** [comment]
xxnet-version: 3.11.9：😜从3.10.5开始得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
use-ipv6: auto 改为仅ipv6
scan-ip-thread-num: 10 增大到40-50

**Comment by AnyWAT** [comment]
开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by kapans** [comment]
@SeaHOH 你说那个脚本啊？
我在那个帖子里面回复了的

File "E:\SOFTWARE\NET\PROXY\XX-Net\pteredor.py", line 397
def main(*args, local_port=None, remote_port=None):
^
SyntaxError: invalid syntax
请按任意键继续. . .

**Comment by kapans** [comment]
@AnyWAT

现在变成这样了

C:\Windows\system32>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问主 teredo 服务器


有时候又是这样：
C:\Windows\system32>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

**Comment by SeaHOH** [comment]
@kapans 先前有个错误，Python 2 无法正常运行，现在改了，方便的话重新试试。

**Comment by AnyWAT** [comment]
@kapans 手动检查IP了还不行？参考：#10184

**Comment by kapans** [comment]
@SeaHOH

奇怪啊
我code下面有那个txt文件，可还是提示：

系统找不到文件 code\version.txt。
系统找不到指定的路径。
请按任意键继续. .

**Comment by kapans** [comment]
@SeaHOH

奇怪啊
我code下面有那个txt文件
当我以管理员方式运行显示：

系统找不到文件 code\version.txt。
系统找不到指定的路径。
请按任意键继续. .


直接双击显示：

是否先暂时关闭 teredo 客户端（IPv6）再进行测试？（Y/N）n
('try bind local port:', 3691)
Starting probe NAT type...
当前设备可能无法正常使用 teredo 隧道，NAT 类型是 offline！

\u7ecf\u68c0\u6d4b\uff0c\u63a8\u8350\u670d\u52a1\u5668\u662f None.
按回车键结束……



点击y也是同样的结果


是否先暂时关闭 teredo 客户端（IPv6）再进行测试？（Y/N）Y
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

0
('try bind local port:', 2238)
Starting probe NAT type...
当前设备可能无法正常使用 teredo 隧道，NAT 类型是 offline！

\u7ecf\u68c0\u6d4b\uff0c\u63a8\u8350\u670d\u52a1\u5668\u662f None.


是不是彻底没搞了啊。。。

**Comment by AnyWAT** [comment]
🤣想正常，终止 @SeaHOH 的方法
至少检查 #10184 的3、4、两项，管理权限运行
netsh int ipv6 set teredo enterpriseclient default
贴netsh int ipv6 show teredo 运行结果（无需IP地址的2行）

**Comment by AnyWAT** [comment]
😱奇怪啊、😱奇怪啊、😱奇怪啊
我code下面有那个txt文件
当我以管理员方式运行显示：
系统找不到文件 code\version.txt。
系统找不到指定的路径。

**Comment by kapans** [comment]
@AnyWAT

谢谢
我先研究下
那个方法有点复杂
不太懂。。。

**Comment by AnyWAT** [comment]
莫非：
如果 version.txt 的内容为3.11.9
code 下没有目录3.11.9，而是 default ?

**Comment by kapans** [comment]
补充下
我ipv6不通也是上周才开始的。。。

刚才我试了下
用goporxy是可以连接出去的
测试ipv6也可以通过的。。。

我不知道到底是我系统问题
还是xx-net的问题
或者是整个网络问题。。。
哎。。。

**Comment by SeaHOH** [comment]
@kapans 你的测试完全通不过，可能有两点：
1. 受到本地安全策略影响，如本机防火墙、路由器设置改变等
1. 受到墙的干扰，你使用的 IPv6 是什么方式，原生、6to4、teredo？

另外，最先你说
>test-ipv6.com
测试没有检测到 IPv6 地址

然后
>刚才我试了下
用goporxy是可以连接出去的
测试ipv6也可以通过的。。。

请问 gp 是怎么用的，直接放入 v6 的 IP 吗，还是有其它特别设置？IPv6 测试通过具体结果是什么？

**Comment by kapans** [comment]
@SeaHOH

应该是teredo

如果直接用test-ipv6.com
结果如下：
没有检测到 IPv6 地址 [更多信息]
你似乎只能连接 IPv4 互联网，不能访问纯 IPv6 网站。


如果连接上goproxy后（直接运行，没做设置）
再用test-ipv6.com
结果如下：
你的公网 IPv6 地址是 2600:1900:0:1::9
你的运营商（ISP）是 Google LLC
你已接入 IPv6，因此我们增加了一个标签页，显示你能否访问其他 IPv6 网站。

**Comment by SeaHOH** [comment]
@kapans 你提供的信息不足，无法判断。不过能用就好。
1. 不使用 goproxy 时 `无域名 IPv6 连接测试` 是否成功？
1. 使用 goproxy 时是不是整个浏览器都通过 goproxy 连接，未使用 pac 或浏览器插件？

以下是我未使用任何 IPv6 设置，PC 上根本就没有 IPv6 地址，仅全局通过 GAE 代理的测试结果
![1523406413268](https://user-images.githubusercontent.com/8470820/38590212-55756610-3d1f-11e8-8c9e-a637abceb8a6.png)
![1523406339095](https://user-images.githubusercontent.com/8470820/38590215-59753628-3d1f-11e8-9f8c-6284a0f78694.png)
