### ISSUE TITLE
YouTube无法登陆

### ISSUE THREAD

**Issue by ppeng** [XX-net/XX-Net#10392]
网络连接正常，先是谷歌www.google.com无法登陆，
![default](https://user-images.githubusercontent.com/16084934/38476521-c18e90dc-3be0-11e8-98a3-befa4ee7e17d.JPG)
后来换了个网址https://google.com可以了 可是YouTube还是无法的登陆，看视频正常，就是不能用谷歌账号登陆，感觉还是谷歌的问题
![2](https://user-images.githubusercontent.com/16084934/38476556-fbaf5a76-3be0-11e8-97a5-d2c3a1df2502.JPG)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/releases/tag/3.11.9

**Comment by ppeng** [comment]
Thanks  新版本已解决
