### ISSUE TITLE
127.0.0.1:8085页面打不开，程序始终启不来

### ISSUE THREAD

**Issue by sky-alex** [XX-net/XX-Net#10399]
上传照片总失败
Apr 10 01:32:38.360 [launcher][INFO] use build-in openssl lib
Apr 10 01:32:38.360 [launcher][INFO] start XX-Net 3.11.9
Apr 10 01:32:38.360 [launcher][DEBUG] start confirm_xxnet_exit
Apr 10 01:32:39.385 [launcher][DEBUG] good, xxnet:8085 clear!
Apr 10 01:32:39.385 [launcher][DEBUG] finished confirm_xxnet_exit
Apr 10 01:32:39.777 [gae_proxy][INFO] ------------------------------------------------------
Apr 10 01:32:39.785 [gae_proxy][INFO] Python Version     : 2.7.13
Apr 10 01:32:39.785 [gae_proxy][INFO] OS                 : Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Apr 10 01:32:39.785 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
Apr 10 01:32:39.785 [gae_proxy][INFO] Using public APPID
Apr 10 01:32:39.785 [gae_proxy][INFO] ------------------------------------------------------
Apr 10 01:32:39.809 [gae_proxy][DEBUG] Importing CA
Apr 10 01:32:39.809 [gae_proxy][DEBUG] Removing windows CA
Apr 10 01:32:40.269 [gae_proxy][DEBUG] Begin to import Windows CA
Apr 10 01:32:40.277 [gae_proxy][INFO] SSL use version:TLSv1_2
Apr 10 01:32:40.570 [gae_proxy][DEBUG] network IPv4 is ok, cost:1132 ms
Apr 10 01:32:41.170 [gae_proxy][INFO] OpenSSL support alpn
Apr 10 01:32:41.170 [gae_proxy][INFO] load ip range file:D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\gae_proxy\local\ip_range.txt
Apr 10 01:32:41.238 [gae_proxy][INFO] load ip_list num:500, target num:500
Apr 10 01:32:41.246 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:32:41.246 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:32:41.246 [gae_proxy][INFO] SSL use version:TLSv1_2
Apr 10 01:32:41.246 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(10013, '')
Apr 10 01:32:41.246 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:32:41.246 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\gae_proxy\start.py", line 18, in main
    client.main(args)
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\gae_proxy\local\proxy.py", line 130, in main
    (listen_ip, front.config.listen_port), proxy_handler.GAEProxyHandler, logger=xlog)
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 410, in __init__
    self.init_socket()
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 420, in init_socket
    self.add_listen(addr)
  File "D:\Downloads\Software\XX-Net-3.11.9\XX-Net-3.11.9\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 434, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(10013, '')

Apr 10 01:32:43.527 [gae_proxy][WARNING] network IPv6 fail
Apr 10 01:32:52.255 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:32:52.256 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:32:52.256 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:32:52.257 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:03.270 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:03.270 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:03.270 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:03.270 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:33:14.305 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:14.305 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:33:14.305 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:14.305 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:25.330 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:25.338 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:33:25.338 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:25.338 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:36.343 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:11
Apr 10 01:33:36.351 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:36.351 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:36.351 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:12
Apr 10 01:33:36.351 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:36.351 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:33:40.379 [gae_proxy][WARNING] network IPv6 fail
Apr 10 01:33:47.385 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:13
Apr 10 01:33:47.385 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:47.385 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:33:47.385 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:14
Apr 10 01:33:47.385 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:47.385 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:51.425 [gae_proxy][WARNING] network IPv6 fail
Apr 10 01:33:58.399 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:15
Apr 10 01:33:58.400 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:58.401 [gae_proxy][DEBUG] connect 2404:6800:4005:809::2017 network fail
Apr 10 01:33:58.401 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:16
Apr 10 01:33:58.401 [gae_proxy][DEBUG] report_connect_fail network fail
Apr 10 01:33:58.401 [gae_proxy][DEBUG] connect 2404:6800:400c:4::c network fail
Apr 10 01:34:02.405 [gae_proxy][WARNING] network IPv6 fail

试过重装程序，试过无插件浏览器，试过不同浏览器，试过关闭防火墙 defender，试过以管理员身份运行，都没什么效果，进程里pathonw.exe在运行，但是托盘启动不来，查看侦听8000-8010都没有占用。

我这里插网线有ipv6ip，日志为无线连接时的数据，但两者情况下，都启动不了，也访问不了google

**Comment by abigbone** [comment]
#10408  我们的情况差不多~~

**Comment by SeaHOH** [comment]
不一样，似乎是防火墙的问题，建议先重启一次电脑并禁用防火墙观察下是否能启动，然后再恢复防火墙看看。

**Comment by SeaHOH** [comment]
关闭后仍然可以回复
