### ISSUE TITLE
使用自己的appid，为什么还会跳出来“共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问，请使用自己的appid”

### ISSUE THREAD

**Issue by hacky2015** [XX-net/XX-Net#104]
配置好自己的appid了，前面一段时间一直都正常，这两天经常跳出来“共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问，请使用自己的appid”，这是什么情况？

**Comment by xxnet** [comment]
请使用最新版本，已经修复这个问题。

自动升级，待1.7.1 稳定了，就部署自动升级

在 2015年4月3日 上午2:44，hacky2015 <notifications@github.com>写道：
