### ISSUE TITLE
mac更新到10.13.4 miredo一直红灯

### ISSUE THREAD

**Issue by hanjianfei** [XX-net/XX-Net#10406]
XX-Net Status:

sys-platform: x86_64, Darwin-17.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
os-release: 17.5.0
os-detail: Release:10.13.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5245 ipv4:0 ipv6:2725
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 271
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by applestone** [comment]
重新建立一个新的网络连接位置试试

**Comment by hanjianfei** [comment]
重新建立？wifi ？还是什么意思呢？

**Comment by zhuxt2015** [comment]
就是在打开网络偏好设置里，最上面有个位置，新建一个就行了，我已经解决

**Comment by ywqqqqq** [comment]
@zhuxt2015 请问怎么操作呢，刚更新了系统，miredo就一直红灯了:(


是这个位置吗？

![fc8af0ba-c5ca-41e3-981c-8bcee8c16a4a](https://user-images.githubusercontent.com/17809646/38601632-d9f0a384-3d9a-11e8-8421-b98b6dfeb4da.png)

**Comment by hanjianfei** [comment]
已解决，我重新安装了miredo之后，就好了，大家可以试试

**Comment by ywqqqqq** [comment]
@hanjianfei  reinstall miredo works for me, thx:)

**Comment by zhuxt2015** [comment]
<img width="671" alt="2018-04-10 21 31 20" src="https://user-images.githubusercontent.com/13765310/38774466-6180832e-409c-11e8-9278-27f3039f1e54.png">
@ywqqqqq 是这个地方，但是我现在依旧经常IPv6 failed状态，网络很不稳定
