### ISSUE TITLE
有人遇到无法登录google账号的问题吗？

### ISSUE THREAD

**Issue by Shu1110** [XX-net/XX-Net#10404]
能正常访问外网，可是登录谷歌账号的时候，点“下一步”按钮一直没有反应
![image](https://user-images.githubusercontent.com/5476228/38531753-0c131d6c-3ca4-11e8-8699-1d730742dc50.png)

本来应该是将鼠标移动到“下一步”按钮的时候，浏览器左下角会出现一串网址的，可是这个没有。而且点“创建账号”也没有反应

有没有大神知道怎么回事啊？

**Comment by AnyWAT** [comment]
😭问题都不清晰，操作系统及XX-Net版本。。。

**Comment by Shu1110** [comment]
没有经验…… 
![image](https://user-images.githubusercontent.com/5476228/38533628-d0f256e0-3cac-11e8-8635-77b3b3c043c3.png)
![image](https://user-images.githubusercontent.com/5476228/38533636-d79aa880-3cac-11e8-942c-04a9715017b3.png)

**Comment by dannysl** [comment]
一樣~~！

**Comment by AnyWAT** [comment]
貌似遵循此法的没有问题？
😜3.10.5-3.11.9得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。
😂可以自设定 IP 数上限 xxx，3.10.5 以前版本，manual.ini 添加
[google_ip]
max_good_ip_num = xxx
3.10.5 开始，config.json 添加
"max_good_ip_num": xxx

**Comment by SeaHOH** [comment]
其实是 X 大不断在改谷歌系的默认连接方式，这个不可能适应所有人，所以自己到智能代理自定义连接方式最方便。

**Comment by Shu1110** [comment]
受 @SeaHOH 提醒，我在登陆google账号的时候设置xx-net连接方式为“XX-Net”就能正常登陆google账号了！
![image](https://user-images.githubusercontent.com/5476228/38537661-78fe01da-3cc2-11e8-8304-515216a933de.png)

**Comment by Shu1110** [comment]
感谢各位帮助！！！

**Comment by AnyWAT** [comment]
😂浏览器内的全局8087

**Comment by Edroid** [comment]
今天也遇到这个问题了，直接将代理设为全局模式就能正常登录。

**Comment by AnyWAT** [comment]
4个全局呢😂

**Comment by SeaHOH** [comment]
等待新版发布

**Comment by Jeepin-Ann** [comment]
你好，你的问题我也遇到过，我用的是SSR代理，直接打开谷歌，可以翻墙出去，但是登陆账号的时候出现了问题，就是你所描述的，我下载了一个谷歌的插件SwitchyOmega，自动代理，配置好以后再去登陆账号就正常登陆了，具体什么原理我也不清楚，还望有懂的大神给解释一下。谢谢

**Comment by yoodu** [comment]
把翻墙改成全局就可以了

**Comment by xiaolongdeico** [comment]
我也遇到了这个问题，最后成功解决，希望我的这个可以帮助到大家。梯子是没有问题的，检查发现外网一切正常，唯一不支持的就是登录不是谷歌，输入了邮箱，但是点击下一步，按钮就是没有反应，带给我最大的困扰就是网页表情收藏不了了，我怀疑可能是我前几天安装了一个类似免费翻墙的插件导致的，试了3台电脑都没有登录上，找了很多方法。
看到一个贴吧一个网友的方法。

**Comment by xiaolongdeico** [comment]
安装一个谷歌访问助手，然后主页设置，自动打开主页，选择其中的一个网址，然后关闭浏览器，就可以登录了，点击下一步也有反应了，不知道是哪个参数被修改了，方法可能有点笨，希望能帮到大家。

**Comment by xiaolongdeico** [comment]
不能上图和上传谷歌访问助手，希望大家可以试一试，还有这个问题太拐了，我也开了全局。庆幸解决了，加油啊

**Comment by hizeng** [comment]
切换到美国的线路

**Comment by collins7184** [comment]
我今天也遇到了这个问题，我的做法是清除了所有的cookie，把代理切换成全局后关闭油猴脚本，然后打开f12查看运行状态，多刷新几遍后就恢复了

**Comment by collins7184** [comment]
我也不太清楚是什么情况

**Comment by ZHLCHLC** [comment]
我关闭了油猴脚本就好了！！！

**Comment by CODE-FOR** [comment]
根据logs里面的信息，在登陆google时，主要会访问三个域名:
- accounts.google.com
- ssl.gstatic.com
- *.googleapis.com
一般的proxies中只把accounts.google.com加入了代理的范围中，而剩余两个则使用的是DIRECT策略。
而剩余两个域名也在GFW的范围中，因此需要将剩余两个网址加入proxies中。
亲测可以解决问题，当然开`全局模式`也理所当然可以解决问题。

**Comment by WAFAGHJ** [comment]
有一个扩展程序可以解决登陆问题

**Comment by 7467284** [comment]
我梯子手机可以登，电脑别的浏览器也可以，就是所有chrome里的谷歌相关网站都显示无网络连接，是怎么回事啊

**Comment by xxnet** [comment]
试试全局模式

**Comment by Lmce** [comment]
我的问题是用了FlClash全局都不行 后面换回clash就可以了xddddd 我怀疑是环境配置问题

**Comment by e370370** [comment]
我解决了这个问题，但这真一个非常愚蠢的错误（也行大家碰到的情况和我不同）。
我用的是chrome浏览器，进入设置——隐私与安全——安全——【“三档安全浏览”选择第三档】不保护（不建议）就可以了。。。
真是搞不懂，谷歌自己的安全模式，把自己的邮箱登陆给阻断了，没见过这么蠢的，如果之后还想要开启安全模式，就在登陆账户后再设置回来即可。。。
不知道能不能帮到大家，在我看来相当无语。

**Comment by scmales** [comment]
> 我解决了这个问题，但这真一个非常愚蠢的错误（也行大家碰到的情况和我不同）。 我用的是chrome浏览器，进入设置——隐私与安全——安全——【“三档安全浏览”选择第三档】不保护（不建议）就可以了。。。 真是搞不懂，谷歌自己的安全模式，把自己的邮箱登陆给阻断了，没见过这么蠢的，如果之后还想要开启安全模式，就在登陆账户后再设置回来即可。。。 不知道能不能帮到大家，在我看来相当无语。

我用这个方法解决了，谢谢你！
