### ISSUE TITLE
ip太少求指教

### ISSUE THREAD

**Issue by leeonyan** [XX-net/XX-Net#10400]
* 是否试过最新的测试版本？
 3.6.3 3.10.4 3.10.8 3.11.3  3.11.7各版本都用过ip无变化非常少，yb（240p）偶尔有卡顿现象。
  目前使用3.10.8 "target_handshake_time": 已改 （不知道对错- -！） appid部署成功
![1523310672 1](https://user-images.githubusercontent.com/38132292/38525063-7fc209ba-3c83-11e8-8adc-26b56f22c196.png)
![123](https://user-images.githubusercontent.com/38132292/38525123-b1218b66-3c83-11e8-8405-4c5ad69d2a66.png)
诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.10.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:68 ipv4:1 ipv6:28
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:27 h2:1
scan-ip-thread-num: 200
ip-quality: 375
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
退出XX-Net，改名 config.json，使用程序默认参数
xxnet-version: 3.10.8，建议3.10.4（延时250左右）或3.11.9（延时300左右）
use-ipv6: auto，改为仅 ipv6
scan-ip-thread-num: 200，3.10.4：20-30，3.11.9：50-60
Using_Public_Appid: false，神奇，config.json 截图里并无私有AppID，怎做到的？
😜3.10.5-3.11.9得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。

**Comment by leeonyan** [comment]
这个是不是就已经使用自己的appid了？
![223](https://user-images.githubusercontent.com/38132292/38530632-2ac18c18-3c9e-11e8-9022-72e9170daa7f.png)
我曾经手动添加过一批ip然而依旧如此
我曾经单独使用过3.10.4 跟3.10.8 也就是说更新包并没有在同一个路径下 也没作用。
而且还用过3.11.7 当时因为gmail打不开所以又换回了3.10
关闭自动扫描线程也试过  我一直以为是我这封的比较严重 但是别人都上千的ip我就頽了

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38530912-e7f2ad70-3c9f-11e8-9d45-99c09fbcc8d8.png)

**Comment by leeonyan** [comment]
use-ipv6: auto，改为仅 ipv6 这个是从代码改吗？自动应该改成什么？

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced

**Comment by leeonyan** [comment]
尴尬了 以前还从这看到过就是没改 - -

**Comment by leeonyan** [comment]
我的appid必须在 config.json 内保存貌似才有效

这个3.10.8 需要这么做么？

**Comment by AnyWAT** [comment]
从3.10.5开始，

**Comment by leeonyan** [comment]
都说是3.10.8 是最好用的我才用回了 3.10.8  可是  可是可是  ip 好可怜啊

**Comment by AnyWAT** [comment]
都说是3.10.8 是最好用：基于3.10.8与后面的较近版本而言

**Comment by leeonyan** [comment]
我用了 3.11.7 因为gmail打不开当时着急 没有仔细研究 就换回了 3.10.4 然后就打开了 
而且当时3.11.7 ip也是少的可怜

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP😂很重要

**Comment by leeonyan** [comment]
再麻烦请教下  config.json 保存我的appid的 代码是什么？

**Comment by AnyWAT** [comment]
当时3.11.7 ip也是少的可怜：程序默认IP上限为500，且你没有检查IP😂。。。

**Comment by leeonyan** [comment]
就是现在我的ip数 77  多久检查一次？曾经检查过

**Comment by AnyWAT** [comment]
config.json 保存我的appid的 代码是什么？😱爬楼，在图片内输入并保存即可

**Comment by AnyWAT** [comment]
就是现在我的ip数 77 多久检查一次？曾经检查过
😂温故知新😱

**Comment by leeonyan** [comment]
哦你是说这个保存么？ 这个肯定是保存的呀！否则状态中是不会显示工作appid的‘
不是很久检查一次哦！想起来就检查一下强迫症的我’

**Comment by AnyWAT** [comment]
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅——基本不用手动检查

**Comment by leeonyan** [comment]
图片怎么还传不上了呢？

**Comment by AnyWAT** [comment]
这个肯定是保存的呀——3.10.8会在config.json里有，没有即没保存

**Comment by AnyWAT** [comment]
下载、上图需代理（正常）

**Comment by leeonyan** [comment]
!好吧 现在ip6 数 为0 链接尚未建立

**Comment by leeonyan** [comment]
诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.10.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:79 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 40
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
您老再麻烦给看一下

**Comment by leeonyan** [comment]
我appid 都是部署完成保存完毕的啊  都是成功了的

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=config 配置，不是 http://127.0.0.1:8085/?module=gae_proxy&menu=deploy 部署😱

**Comment by AnyWAT** [comment]
要么3.10.4要么3.11.9，忽略3.10.8🤣

**Comment by leeonyan** [comment]
是的 部署完成之后 在配置页面保存的 也是成功的

**Comment by leeonyan** [comment]
现在检查一下就会有一两个有效ip 一会自己就没了

**Comment by AnyWAT** [comment]
😂莫非程序就对你一人特殊？

**Comment by AnyWAT** [comment]
参考：#10184 
再见，执拗。。。

**Comment by leeonyan** [comment]
已经很感谢了！我主要是研究学习一下！

**Comment by leeonyan** [comment]
不是程序，我是想找到我什么地方没调对！

**Comment by jcorg** [comment]
![image](https://user-images.githubusercontent.com/22322219/39290910-c2e26662-4963-11e8-935e-1c5292821aa3.png)

**Comment by SeaHOH** [comment]
>Using_Public_Appid: false

没有使用公告 AppID 的意思就是使用了私人的
