### ISSUE TITLE
用3.11.9登录google账号会提示您的浏览器似乎禁用了 Cookie

### ISSUE THREAD

**Issue by thurse** [XX-net/XX-Net#10407]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:14481 ipv4:1 ipv6:5977
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:undefined
worker: h1:51 h2:1
scan-ip-thread-num: 200
ip-quality: 1376
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38537674-8a7a2d12-3cc2-11e8-9a09-c081b83f6ad0.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38537921-f8e92bf8-3cc3-11e8-9fe3-c9be40c5b7f6.png)
![default](https://user-images.githubusercontent.com/37962734/38537927-07487532-3cc4-11e8-8491-85088a519261.png)

**Comment by Zhu69** [comment]
我还是3.11.7我为什么没有收到推送呢?

**Comment by AnyWAT** [comment]
取决于 http://127.0.0.1:8085/?module=launcher&menu=config 自动升级到: (帮助)。。。

**Comment by SeaHOH** [comment]
等待新版发布
