### ISSUE TITLE
以下僅供參考(win7 8.1 10都可以) 試了幾天暫時還可以

### ISSUE THREAD

**Issue by foho8080** [XX-net/XX-Net#10409]
1.先在ipv4 dns可以隨便填寫 ipv6 DNS 2606:4700:4700::1111和2606:4700:4700::1001
2.打開控制面板--時鐘.語言和區域----區域和語言----位置-----當前位置不要選擇中國和港澳.選亞洲地區國家
![38464524-ab3cab10-3b41-11e8-8855-4dbb9c673a34](https://user-images.githubusercontent.com/17214241/38540676-50d7e6dc-3ccf-11e8-9ee0-c44857f92780.jpg)

**Comment by AnyWAT** [comment]
😱 https://github.com/XX-net/XX-Net/issues/10382

**Comment by foho8080** [comment]
我用3.10.8版本試的

**Comment by AnyWAT** [comment]
IP延时😜
3.10.4：250左右
3.10.8：？
3.11.7：300-350
3.11.9：300左右

**Comment by whhxmwhh** [comment]
我的299

**Comment by AnyWAT** [comment]
没有版本，残缺😜

**Comment by lkyyang** [comment]
操作系统的语言需要修改吗？

**Comment by AnyWAT** [comment]
🤣改成谁也不识的某某？

**Comment by whhxmwhh** [comment]
不用的。

**Comment by foho8080** [comment]
@lkyyang 就是改地理位置(語言不用改)

**Comment by lkyyang** [comment]
![image](https://user-images.githubusercontent.com/11970471/38553368-a2108c26-3cf1-11e8-8796-6895eca32100.png)
@foho8080

**Comment by evilhentaro** [comment]
1111跟1001也被干扰了，不是很稳

**Comment by SeaHOH** [comment]
不确定，不提倡，关闭。
