### ISSUE TITLE
xxnet不支持Firefox瀏覽器嗎？

### ISSUE THREAD

**Issue by imldf** [XX-net/XX-Net#10405]
最近想要使用Firefox瀏覽器，但是衹要是使用xxnet的時候都無法使用Firefox打開Google、YouTube等網站。我在想是不是不兼容Firefox呢？Firefox顯示的問題是：您的連接不安全！

![001](https://user-images.githubusercontent.com/33856971/38532513-c69cb726-3ca7-11e8-8134-ec3ef5fe1f41.PNG)

**Comment by BaoJingchuan** [comment]
手动导入data\gae_proxy目录下的CA证书，看这里https://github.com/XX-net/XX-Net/wiki/使用Firefox浏览器#手动导入证书

**Comment by AnyWAT** [comment]
Firefox瀏覽器需要加载 data\gae_proxy\CA.crt

**Comment by imldf** [comment]
@BaoJingchuan  感謝

**Comment by imldf** [comment]
@BaoJingchuan  請問可以打開網站了，但是無法登陸Google賬號是怎麽回事呢？ 提示似乎禁止了cookie，但是這個設置是沒有問題的呀！
![001](https://user-images.githubusercontent.com/33856971/38534852-023e4a28-3cb3-11e8-9122-38f0088d9d13.PNG)
![002](https://user-images.githubusercontent.com/33856971/38534854-06741744-3cb3-11e8-8ad8-963ee6e92777.PNG)

**Comment by imldf** [comment]
找到問題了，無法登陸Google賬號不是瀏覽器的問題，而是3.11.9版本問題，現已經退回3.11.4
