### ISSUE TITLE
3.11.9 延迟高怎么解！！！

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#10413]
IP 在300 到 700 不等。  延迟破2000 YOUTUBE没办法看很慢，   之前在700－1000上下 看YOUTUBE暂停一下就可以了。IPv6今天也基本稳定没有很长时间FAIL。怎么解  求指点

**Comment by AnyWAT** [comment]
😜3.10.5-3.11.9得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。

**Comment by kitkw** [comment]
之前一直在用3.11.7  但前天突然无限fail(ipv6), 回滚版本无效。才升3118 但很快又不行，3119很快就出来了，IPV6基本稳定 但就是延迟高

**Comment by AnyWAT** [comment]
50%以上，3119很快就不行🤣

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38564501-d5da8f28-3d11-11e8-9f8a-55d43701b9d8.png)

**Comment by lw8228** [comment]
IP延迟	1618

**Comment by ARCHOTZ** [comment]
原本在3.10.4两三百延迟，换成3.11.x之后的版本就必定会变成六七百，换回去又两三百，全默认配置，无解。

**Comment by AnyWAT** [comment]
有解，楼主说没用，删了🤣

**Comment by hbsxwhb** [comment]
我的一直是500至600
![2](https://user-images.githubusercontent.com/33019911/38601354-cc4cbc1e-3d99-11e8-8e89-fa4bc292117a.png)

**Comment by AnyWAT** [comment]
增大扫描线程为40-50（或自己调试），关闭“自动调整扫描线程”，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP ✌

**Comment by kitkw** [comment]
还是高延迟。手动检查IP  IP数有6，700 但很快掉到300…………看来只能试试你们的说的3.10.4，看看是不是这么神

**Comment by kitkw** [comment]
3.10.4 提示开启IPV6！！后续版本都是打开就可以用，都忘记了这个怎样设置了……………………

**Comment by AnyWAT** [comment]
手动检查IP IP数有6，700 但很快掉到300…………貌似去伪存真呢🤣
3.10.4 提示开启IPV6！！😱不是说见过：。。。转换XX-Net版本。。。

**Comment by kitkw** [comment]
ip数700时  延迟 5 ，600  但掉到300 延迟就破千  近2千

转换XX-Net版本？？？我就是看到你们说3.10.4  延迟低 才回滚的，  但提示要开启IPV6

**Comment by asmosn** [comment]
延迟都一样高了，3.10.4显示假延迟500+（实际很卡），药丸的节奏。。。

**Comment by AnyWAT** [comment]
同一IP上限、适当增大扫描线程，或关闭“自动调整扫描线程”后基本稳定的 IP延时😜
3.8.5：250左右
3.10.4：250左右
3.10.8：？
3.11.7：300-350
3.11.9：280-320

**Comment by asmosn** [comment]
![qq 20180411220045](https://user-images.githubusercontent.com/9925193/38621690-f2df3dcc-3dd3-11e8-922d-e549431467c6.png)
改DNS后出现以上问题...改回gg DNS来还是这样，咋办？

**Comment by asmosn** [comment]
按教程删除cert证书后初始化导入还是fail

**Comment by bibichuan** [comment]
3.13.1 ip延迟始终在1000左右，我是自己弄了APPID,也不行啊。1000左右，感觉上炕都费劲

**Comment by AnyWAT** [comment]
一般300（左）右。贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息
