### ISSUE TITLE
全局通过智能路由代理时，该网站无法访问

### ISSUE THREAD

**Issue by clipperL** [XX-net/XX-Net#10418]
mtj.baidu.com

**Comment by SeaHOH** [comment]
这不是直连的么？观察一下日志，或者你的智能路由配置。

**Comment by clipperL** [comment]
@SeaHOH 
我不知道什么叫直连；
一直在生成新的日志，也不知道是哪一行或几行，生成的太快了。
智能路由配置我没改动，实际上我也不知道在哪改。

我刚切换到“全局PAC智能代理”，可以访问了。
不知道“全局PAC智能代理”和“全局通过智能路由代理”有什么区别。

**Comment by SeaHOH** [comment]
很大可能是自定义过智能代理，自己打开网页 UI 的智能代理页面看看就知道了。
