### ISSUE TITLE
您的连接并不安全

### ISSUE THREAD

**Issue by wsgdlhy** [XX-net/XX-Net#10417]
XX-Net Status:

sys-platform: x86_64, Linux-4.15.15-1-ARCH-x86_64-with-glibc2.2.5
os-system: Linux
os-version: #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018
os-release: 4.15.15-1-ARCH
os-detail: Dist:; Version:; ID:
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.14
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:20 h2:0
scan-ip-thread-num: 50
ip-quality: 678
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

遇到错误码 “SEC_ERROR_UNKNOWN_ISSUER” ，必须删除证书重新导入才可以，关闭浏览器再开必须重复删除导入。怎么回事？

**Comment by SeaHOH** [comment]
检查是否真的导入了，导入时必须 root 权限。
