### ISSUE TITLE
Ipv6状态老是fail

### ISSUE THREAD

**Issue by if2012** [XX-net/XX-Net#10410]
https://support.xbox.com/zh-CN/xbox-on-windows/social/troubleshoot-party-chat
每次按照操作就是先关闭再启用重启电脑之后又可以。
有什么办法阻止频繁fail吗？？？那个ipv6协议是关了的。

**Comment by AnyWAT** [comment]
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by dylanleesky** [comment]
我的也是这样，现在出现三个可用的IPV4资源，但上网极慢。本地网络状态显示正常，但IPv6测试网站测试显示全超时，试了各种方法，找到那俩bat运行，还有恢复系统，切换路由的6to4为6in4，都不行。
![00000](https://user-images.githubusercontent.com/14555503/38546031-1b54f284-3cde-11e8-9565-96695eb7e0ce.png)

**Comment by dylanleesky** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)
我晕。。。重新运行了关闭IPv6的bat。。。竟然测试OK了。。。我擦。。。。。。。。

**Comment by AnyWAT** [comment]
😭你这有原生IPv6支持的，非我等能。。。

**Comment by dylanleesky** [comment]
....不行，见鬼了，依旧fail。。。。重启后测试依旧失败。。。

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f615.png)

**Comment by dylanleesky** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:16 ipv4:2 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:2
scan-ip-thread-num: 32
ip-quality: 233
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
重温2楼🤣

**Comment by ZeonChar** [comment]
我也出现同样的问题了。。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:2 ipv6:354
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 986
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

C:\WINDOWS\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo-debian.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by AnyWAT** [comment]
use-ipv6: auto 改为仅 ipv6
scan-ip-thread-num: 10 增大4-5倍
结束进程 pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行
netsh int ipv6 set teredo enterpriseclient default
😜3.10.5-3.11.9得关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP
3.11.7 IPv6 IP数上限1000，扫描线程最大40（或自己调试），IP延迟300-350，自动480P流畅
😜😜3.10.4及以前版本，不必关闭“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP
3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右，自动480P流畅
注意备份IP延时小时的 good_ip.txt 以防不时之需！
在曾运行正常的版本如3.10.4或3.11.7不正常时，改用回另一版本，手动检查IP，或许又能正常了。

**Comment by dylanleesky** [comment]
好累好累好累。。。。。。不研究了

另外，你们的表情怎么弄个上去的？我这就没有表情有关的按钮。。

**Comment by dylanleesky** [comment]
尼玛。。。什么鬼。。我操。。。关了路由器的IPv6。XX的IPv6竟然又能用了显示OK、、、瞬间出现几十个可用ip6资源。。。。。。！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by AnyWAT** [comment]
(win7)管理权限运行 netsh int ipv6 set teredo enterpriseclient win10.ipv6.microsoft.com. （带英文句点的尾巴）
表情或许只在桌面版🤣

**Comment by dylanleesky** [comment]
大神 @AnyWAT    这到底怎么回事？？？路由支持的IP6不可用，系统默认的隧道反而能用。两者还不能并存。。。怎么破？？
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f923.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38548798-3f2fa9fe-3ce5-11e8-9845-b8ed8e48f724.png)

**Comment by dylanleesky** [comment]
哈？？？路由器支持的这种原生无法兼容XX么？但是手机上的XX却也可用啊，小米系统，路由分的IPv6地址和IP4地址并存。虽然其他软件无法开代理用，但xx里的浏览器却联网正常。。。
有什么办法能关掉win系统的IP6解决对路由的冲突么？

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f62d.png)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6

**Comment by dylanleesky** [comment]
好吧，试了一圈，电脑版的唯有关闭网卡里的IPv6协议才能正常。3.8.5的倒是可以兼容路由器分的IP6并且显示网络ok，但就是连不上网显示无返回数据。

。。。

**Comment by AnyWAT** [comment]
3.8.5及以前版本与3.8.6及以后版本，证书文件发生了变化，退回3.8.5及以前不是一个好主意🤣
建议使用3.10.4，想IP延迟小并稳定，修改 data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/manual.ini
[google_ip]
max_good_ip_num = 1000 （程序默认6000太大，不好😜）
IP延时大、或转换XX-Net版本及网络卡顿，增大扫描线程（貌似保存不了）、关闭“自动调整扫描线程”（能否保存？）手动检查IP。。。

**Comment by ZeonChar** [comment]
我现在ipconfig里竟然有三个不同的ipv6地址，怕是把电脑调坏了，看来只能重置一下看看了。
蓝瘦_(:з」∠)_

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38556217-74e45728-3cfb-11e8-991e-879acff91566.png)
![default](https://user-images.githubusercontent.com/37962734/38556243-8a226800-3cfb-11e8-98f8-e08b0507e48f.png)

**Comment by if2012** [comment]
奇怪的是，按照链接中方案2卸载重启重装之后，设备管理器中就再也没有Teredo 适配器了。

**Comment by SeaHOH** [comment]
#10328
