### ISSUE TITLE
ipv6 之前能成功，重启电脑后失败

### ISSUE THREAD

**Issue by MetSystem** [XX-net/XX-Net#10424]
ipv6 之前能成功，重启电脑后失败
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:282
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1227
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
use-ipv6: auto 改为仅ipv6
scan-ip-thread-num: 10 增大5倍？关闭”自动调整扫描线程数“， http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP
贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）

**Comment by SeaHOH** [comment]
#10328
