### ISSUE TITLE
IPv6状态 一直 fail

### ISSUE THREAD

**Issue by cooperrrrr** [XX-net/XX-Net#10431]
我的连接状态一直显示“连接尚未建立”IPv6状态 一直 fail，请大神指教如何设置。（IPv6已禁用，组策略也设置过了）
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:373 ipv4:0 ipv6:101
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1067
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
先恢复组策略为**未设置**，然后看看这个脚本 #10328

**Comment by AnyWAT** [comment]
又一个（😋通过代理）上 https://github.com/ 网络卡顿的家伙，同样内容自动给来个N遍😜

**Comment by SeaHOH** [comment]
@whhxmwhh 你用的这个脚本中两个测试都不准确，所以我才重写了一个。

**Comment by bencage** [comment]
我安装好之后可以访问，但是再次开启电脑显示连接尚未建立。需要打开文件夹3.11.9,XX-Net-3.11.9\code\default\gae_proxy\local\ipv6_tunnel, 点击enable_ipv6.bat，然后重启电脑就可以了。尝试过的，这个方法效率最高，虽然需要重启电脑。

**Comment by AnyWAT** [comment]
这个方法效率最高，虽然需要重启电脑：试试效率不怎么高的“禁用再启用网络”🤣

**Comment by whhxmwhh** [comment]
谢谢。我都没有更新。一直用这个。

**Comment by whhxmwhh** [comment]
404: Not Found文件被删除了？

**Comment by pendave** [comment]
这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

而其他的方法都要重启很多次电脑都不管用！
