### ISSUE TITLE
不自动检测更新，只能检查到最新版本为3.11.7

### ISSUE THREAD

**Issue by shelderzhang** [XX-net/XX-Net#10432]
自动检查只能检测到3.11.7，不能测到最新版，手更新3.11.9，更新后还是只能检测到3.11.7
![image](https://user-images.githubusercontent.com/12554852/38653441-59802d66-3e3d-11e8-9f32-2f0ab4295c79.png)

**Comment by shelderzhang** [comment]
![image](https://user-images.githubusercontent.com/12554852/38653428-3f656aa4-3e3d-11e8-831d-52fcbbda7844.png)

**Comment by AnyWAT** [comment]
与 http://127.0.0.1:8085/?module=launcher&menu=config 版本——自动升级到: （通知）稳定/测试版、当前运行的版本（😜貌似跨度不能太大，蛋。。。）相关。

**Comment by SeaHOH** [comment]
只是没有推送而已，跟版本跨度无关。

**Comment by AnyWAT** [comment]
😜有图没真相？
![image](https://user-images.githubusercontent.com/37962734/38653849-47374502-3e3f-11e8-9cff-e8df7544ea1e.png)

**Comment by AnyWAT** [comment]
楼主将此改为“通知测试版”貌似就有3.11.9了

**Comment by WLZLCX** [comment]
点击下面【手动管理 (高级)】，一样可以更新

**Comment by SeaHOH** [comment]
@AnyWAT 并不会，没推送。

**Comment by shelderzhang** [comment]
@SeaHOH 应该是官方没有推送
