### ISSUE TITLE
关于在华硕RT-AC86U 梅林版本无法上传文件？？？？？

### ISSUE THREAD

**Issue by marswow** [XX-net/XX-Net#10435]
* 简单描述遇到的问题：
这个版本的梅林固件上传文件后提示：“插件压缩包格式不正确”！
这样一来我后续想做的事情就无法完成了。
硬件：华硕RT-AC86U 
固件：梅林
版本：384.4_0
MD5: 82D191A33CEBE58E034E5C64BD6A3C2E
SHA1: 09F7FFD94A9EF0C453DB92765209C72951E92591
http://firmware.koolshare.cn/koolshare_merlin_hnd_router/RT-AC86U/384.4_0/RT-AC86U_384.4_0_ubi.w

**Comment by SasamiMasakiJurai** [comment]
不刷正版梅林出问题很正常

**Comment by marswow** [comment]
@SasamiMasakiJurai 我地址里的不是正版的固件吗？

**Comment by SasamiMasakiJurai** [comment]
那个怎么可能是正版梅林。。。。。。。。。。

是国内论坛的自己弄的所谓梅林

有没有后门都难说的
