### ISSUE TITLE
等待扫描IP，建议开启IPv6。

### ISSUE THREAD

**Issue by lnsane** [XX-net/XX-Net#10433]
**XX-Net Status:

sys-platform: AMD64, Windows-2012ServerR2-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 2012ServerR2
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:16; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true*

**Comment by AnyWAT** [comment]
贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）
