### ISSUE TITLE
这延迟真是让人受不了!

### ISSUE THREAD

**Issue by 2609665** [XX-net/XX-Net#10434]
![3 10 4](https://user-images.githubusercontent.com/20493163/38654582-a2f96214-3e42-11e8-9d44-f42c46ba757d.jpg)
3.10.4通常500+600  偶尔200+  比较稳定  不过看ytb720的视频还是经常会卡~   Google Plus 经常会出现访问不完整的BUG有时又正常!~
![3 11 7](https://user-images.githubusercontent.com/20493163/38654583-a3330c8a-3e42-11e8-954c-e7b116f5d3d8.jpg)
![3 11 9](https://user-images.githubusercontent.com/20493163/38654584-a366f4be-3e42-11e8-8175-fcf436b21102.jpg)
3.11.7/3.11.9差不多  最近几天都是1000+   不稳定  500+------1800左右的跳

几个版本手动扫描IP也涨不到哪去  最后还是减少回扫描前那数字
![qq 20180412112706](https://user-images.githubusercontent.com/20493163/38654958-7a635ff6-3e44-11e8-9449-3419e54b4a7b.jpg)

**Comment by AnyWAT** [comment]
😜这结果怎么样？
同一IP上限、适当增大扫描线程，或关闭“自动调整扫描线程”后基本稳定的 IP延时😜
3.8.5：250左右
3.10.4：250左右
3.10.8：？
3.11.7：300-350
3.11.9：280-320
![image](https://user-images.githubusercontent.com/37962734/38655278-55bc13ee-3e46-11e8-8a53-2d6ea2c36546.png)
![image](https://user-images.githubusercontent.com/37962734/38655258-3fa0b326-3e46-11e8-930a-c45df0e5af54.png)

**Comment by SeaHOH** [comment]
备份然后删除 good_ip.txt，重新扫描。

@AnyWAT 你不要老是拿你的好网络跟别人秀，不一样的。

**Comment by AnyWAT** [comment]
貌似还有设置的不同😜

**Comment by foho8080** [comment]
![0001](https://user-images.githubusercontent.com/17214241/38655536-e063ac36-3e47-11e8-9094-70d203efcc42.jpg)

**Comment by AnyWAT** [comment]
几个版本手动扫描IP也涨不到哪去 最后还是减少回扫描前那数字：貌似只说有效 IP数，没关心 IP延时，操作适当，有效 IP数达到总数上限，延时趋于稳定😂

**Comment by AnyWAT** [comment]
@SeaHOH 🤣原来弃用 ISP 的DNS能救命：😱
停电到另处的Win10上用XX-Net为手机分享代理，3.8.4及3.10.4在使用中逐渐异常至不能代理，发现连接池几乎归零，改电脑 IPv4/6 DNS由自动获取到指定四个1，完美解决问题😋

**Comment by SeaHOH** [comment]
跟 DNS 无关，IPv6 都是扫的自带库，没有走解析。

**Comment by AnyWAT** [comment]
貌似当时有效IP数未减，只是连接池几乎归零

**Comment by SeaHOH** [comment]
避免 DNS 污染是翻墙必备措施，XX-Net 就自带一个。
你说的情况可能是浏览器没有设置远程解析，Chrome 是默认启用的，火狐以前需要手动设置，现在不知道。

**Comment by AnyWAT** [comment]
昨天的事情，没有浏览器设置问题。2处的网络是同一个ISP😂，只是操作系统版本有差异，一个刚更新的1803一个1709（当前）

**Comment by 2609665** [comment]
![3 10 4](https://user-images.githubusercontent.com/20493163/38660289-4af6c99a-3e5f-11e8-88c8-e25b1b26a52c.jpg)
![3 11 9](https://user-images.githubusercontent.com/20493163/38660290-4b3ae49a-3e5f-11e8-92da-406f44f5265b.jpg)
删除good_ip.txt重新扫描后   看来还是3.10.4好用些
![qq 20180412145148](https://user-images.githubusercontent.com/20493163/38660792-29658558-3e61-11e8-9de2-46b0aa7d6654.jpg)
![qq 20180412145213](https://user-images.githubusercontent.com/20493163/38660793-299774d2-3e61-11e8-95df-f21cc2b26d95.jpg)

**Comment by SeaHOH** [comment]
>貌似当时有效IP数未减，只是连接池几乎归零
遂改 DNS ，手动检查 IP，连接池在增加

这不是 IP问题还能是什么，你经常叫人`手动检查 IP`，难道不知道这是什么意思么？
给你们画了个简单流程图
![x2scrap](https://user-images.githubusercontent.com/8470820/38661422-55c9f1a6-3e20-11e8-9746-f81c6ec128a1.png)

**Comment by SeaHOH** [comment]
@2609665 
网络就这样，跟 IP 本身无关，跟使用策略有关，各个版本有细微的不同。
如果网络够好就没有差别，你这个算是被影响到了。

**Comment by abigbone** [comment]
![image](https://user-images.githubusercontent.com/4329020/38661776-8d01d33e-3e64-11e8-89a6-85af9b050f14.png)
看来不是一个地区问题，延迟都比较多~~ 速度慢，油管要缓冲

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38662070-afbdff0a-3e65-11e8-86f0-3fbc1aadd390.png)

**Comment by AnyWAT** [comment]
@SeaHOH 辛苦海GG了，貌似当时比一般情况下的掉垃圾池速度快很多

**Comment by kitkw** [comment]
我这几天也是延迟超高的，基本1500+超慢。  自己乱搞，只导出有效IP（我自己是600多）然后把全部IP全清了。重开软件导入有效IP  同时把 扫描程数 调到 1 （2  3 也可以  调掉就是）自动调整程数我也是看@AnyWAT才关掉  不知道打开会不会影响。

其他没搞  现在延迟500左右， 打开网页是有变快了  youtube 网页也是  但加载youtube 视频（720）  就没有变化  还是很慢，无解！！  非技术贴  自己乱试 的  不知道什么原理

**Comment by SeaHOH** [comment]
我觉得有部分可能是，愈来愈多的设备在使用 teredo 隧道，所以自然增加了网络延迟。
在网络中离中继服务器越近（跳数），延迟越小，因为封包排队次数少。

**Comment by AnyWAT** [comment]
报告友友，貌似参数得加码😱
原来：3.10.4及以前版本，开启“自动调整扫描线程”，适当增大扫描线程，转换XX-Net版本、或延时大网络卡顿，得。。。检查IP。3.10.4 IPv6 IP数上限1000，扫描线程最大20（或自己调试），IP延迟250左右
😋0.5-1小时前运行3.11.9，"仅IPv6" 不可用，请检查。滚回3.10.4，延时比250大多了下不来，且不久又死掉。整活，扫描线程最大40，关闭“自动调整扫描线程”，延时恢复到250左右，已正常。。。

**Comment by SeaHOH** [comment]
真的弄不清你啥意思，能不能排下版，多打几个字把情况说清楚？

**Comment by AnyWAT** [comment]
想表达的意思：首行——貌似参数得加码😱

**Comment by SeaHOH** [comment]
哪个参数，扫描线程？加什么码？
想起了学生时代，有些古文跟这个差不多。 :smiley_cat:

**Comment by AnyWAT** [comment]
😝加码：20变40，开启变关闭

**Comment by SeaHOH** [comment]
明白了，所以说还是 IP 问题。IP 上限数过大就是这个效果，会包含有许多失效 IP，当然根据网络状况，这个数字会有所变动。
IP 上限数和扫描线程数，这两个值不会有同时适用所有人的最佳值，需自行尝试。

**Comment by bibichuan** [comment]
我的情况是
![image](https://user-images.githubusercontent.com/14054904/53064475-ecc43880-3502-11e9-8c43-275dd5f2f68a.png)最好的情况在400以上，最差的情况在1000以上，同一个网络，在linux虚拟机中倒是表现的很好，始终是在300到400之间
