### ISSUE TITLE
糟糕!您的浏览器似乎禁用了 Cookie。请务必启用 Cookie 或尝试打开一个新的浏览器

### ISSUE THREAD

**Issue by suoqingqiu15** [XX-net/XX-Net#10437]
有人知道这个怎么解决，部署的时候无法验证，cookies肯定是开着的。手机上搭梯子也打不开。

**Comment by suoqingqiu15** [comment]
而且，谷歌账号密码都对了，也登不上，出现同样的提示

**Comment by SeaHOH** [comment]
尝试前进或后退一个小版本号。

**Comment by SeaHOH** [comment]
这是代理规则的锅。

**Comment by SeaHOH** [comment]
SSR 没有证书问题吧。

**Comment by AnyWAT** [comment]
网页乱码，神马不是私密连接。。。GAE证书？忘记了

**Comment by suoqingqiu15** [comment]
哪里能下xxnet的老版本

**Comment by bluerxing** [comment]
同，应该是新版的问题，已退回到3.6.16，没再出现问题

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 版本——手动管理 (高级)——全部已发布版本
😜运行旧版本前：从3.8.6及以后版本退回到3.8.5及以前版本，改名或删除 CA.crt（Certkey.pem 即不同名的相同文件？），复制 CAkey.pem 为 CA.crt

**Comment by QiangZhu** [comment]
3.11.9 存在同样的问题。（不能登录google账号）回退到3.6.15(登录没有问题)[](url)
![cannot_login_google_account_20180413_xx-net-3 11 9](https://user-images.githubusercontent.com/301483/38727490-bab0354c-3f3f-11e8-8049-5389f3a03ac5.png)
供参考，感谢xx-net!

**Comment by SeaHOH** [comment]
等待新版发布
