### ISSUE TITLE
关于目前速度慢的个人想法

### ISSUE THREAD

**Issue by SasamiMasakiJurai** [XX-net/XX-Net#10436]
个人认为主要是dns污染加剧以及封锁趋严导致的

dns污染现在已经非常可怕了

现在国内dns基本咩有不污染的了

而封锁趋严在两年之前就已经开始

其实在两会之前ipv4已经大面积死亡

两会期间隧道已经开始出现波动

现在两会之后

国内媒体已经宣告要推广ipv6

部分地区已经有ipv6地址分发

这已经说明ipv6封锁已经成功

因此

目前状况是可以预料的

这也就是我为什么之前想尝试通过类似亚马逊等服务器架设软件翻越的出发点

xx-net目前看来

付费版还算稳定

毕竟多手段翻越

免费版和个人id版估计会越来越慢的

毕竟明码翻越被封只是时间问题。。。。。。。。。。。

**Comment by SeaHOH** [comment]
走智能代理有个内置 DNS，是加密的，但是不知道做没做 CDN 优化。
关键是浏览器要开启远程解。火狐旧版需要设置，新版不清楚；Chrome socks 是默认开启，http 不清楚。
IPv6 的话，teredo 情况要好些，这个封包稍微复杂点，需要多解一次。

>毕竟明码翻越被封只是时间问题

我比较赞同这句。其实现在很多人都用加密代理，X-Tunnel 也算，但是为了公开提供服务，加了很多前端。自己架设的话可以不这么麻烦，结构简单点，做个 CDN 优化就好。

**Comment by SasamiMasakiJurai** [comment]
cdn优化也不是长久之计

全部污染只是时间问题

现在说白了就是通过加密隧道直接通过海外解析dns

但是也会有一些问题

例如访问国内网站速度慢等等

xx-net是通过gwflist来区分地址段来翻越的

但是目前包括gwflist chinadns等等都有污染

所以不稳定会越来越厉害

这些时段各类延迟 断线等等就是例子

**Comment by SeaHOH** [comment]
自己建加密代理是没问题的，起码能用。

**Comment by AnyWAT** [comment]
火狐开启远程解（析）？
![image](https://user-images.githubusercontent.com/37962734/38682836-a8971b56-3e9e-11e8-818d-62a00e779a25.png)

**Comment by QuocTroy** [comment]
看最近的大家的消息，应该就是DNS污染的可能性最大了，我手动设置了下IPV6的DNS地址才能用XX-NET但是延迟1000+很慢，自动获取的话根本连不上，但是我这个宽带是电信的。不过我发现使用手机开热点（手机是联通4G网）共享给电脑后速度明显提升了很多而且不需要手动设置IPV6的DNS地址且手机上能用XX-NET无压力。

**Comment by SeaHOH** [comment]
使用 XX-Net 不需要设置 IPv6 连接的 DNS 地址，保证 IPv4 连接的 DNS 无污染就行。

**Comment by 2378** [comment]
v6污染确实头大，目前只能在路由里添加大量hosts应对。
如果哪一天，国产v6全面铺开，hosts照样没戏。
自架服务目前没问题，但就怕流量一大连cdn都一锅端了

**Comment by dahai058** [comment]
今早3.10.4延迟突然升到1千多，我把goog_ip.txt文件删了，然后重启xx扫描ip，十来分钟后ip到3百多，延迟降到313。油管480p

**Comment by AnyWAT** [comment]
🤣貌似手动扫描数十秒即有同等效果，除非IP上限很大，如2000以上。。。

**Comment by SasamiMasakiJurai** [comment]
目前国内dns污染越来越厉害了

所以很麻烦

除非dns解析放在国外

hosts只能解一时

而且需要有人一直维护

目前好些hosts都处于半死状态。。。。。。。

更新很缓慢。。。。。。

**Comment by bibichuan** [comment]
不知道最快能达到多少？我的谷歌ssr能达到七八十毫秒，xxnet我看到最高也就250左右。
