### ISSUE TITLE
问下有没有在merlin上成功启用IPv6（没有公网IPv4地址）的案例，请分享下，谢谢

### ISSUE THREAD

**Issue by cuanliusw** [XX-net/XX-Net#10440]
折腾很久了，还是没找到方法

PC的win10已经搞定，自己能翻
PC做共享，LAN里的所有设备通过pac可以翻

现在就是想能不能干脆把xx-net放到merlin上，同时又能像win一样，在没有公网IP的情况下，搞个terado这样的折中方法虚出来IPv6

如果哪位大神搞成了，分享下吧，谢谢了 orz

(P.S. 我在merlin上已经装上xx-net了，就差IPv6的问题)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10183
