### ISSUE TITLE
小米路由器ipv6相关问题

### ISSUE THREAD

**Issue by Mark486** [XX-net/XX-Net#10447]
* 简单描述遇到的问题：最近换了个小米路由器，千兆的，支持2.5G5G双频，不是有个小米路由的管理软件在手机上嘛，无聊翻来翻去，找到了这个：
![674943450066340798](https://user-images.githubusercontent.com/21996475/38734266-811017a4-3f57-11e8-9012-c9669ac2991b.jpg)
![453990187270406619](https://user-images.githubusercontent.com/21996475/38734451-4e6c4ba0-3f58-11e8-9882-57422942cce6.jpg)

说什么可以开启ipv6访问国际教育网站之类的，请问这个和内网的teredo有什么区别，并网速会不会更快，另外设置方法有没有。

（需要更多信息请联系mark3046069360@gmail.com）

**Comment by SeaHOH** [comment]
在手机上实现的，估计就是 teredo，而且还是加了过滤的。
用多个手机试试，如果地址不一样就是了。

**Comment by SeaHOH** [comment]
先关掉，仍然可以回复。
