### ISSUE TITLE
总ip数太少

### ISSUE THREAD

**Issue by Mark486** [XX-net/XX-Net#10449]
![fireshot capture 6 - xx-net - http___127 0 0 1_8085__module gae_proxy menu advanced](https://user-images.githubusercontent.com/21996475/38735861-ae4d2d1a-3f5c-11e8-9399-59f0a0258aac.png)
如何增加总ip数，我的版本是3.11.7，最新测试版

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10443#issuecomment-381071174

**Comment by Mark486** [comment]
[gae]

password = 

[proxy]
enable = 0
type = HTTP
host = 
port = 0
user = 
passwd = 

[google_ip]

max_scan_ip_thread_num = 200
"auto_adjust_scan_ip_thread_num": 0,

use_ipv6 = force_ipv6
"max_good_ip_num": 2000
已经按照配置了，可总ip数依旧500

**Comment by Mark486** [comment]
[proxy]
enable = 0
type = HTTP
host = 
port = 0
user = 
passwd = 

[google_ip]

max_scan_ip_thread_num = 200

use_ipv6 = force_ipv6
"max_good_ip_num": 2000
还是不行啊/(ㄒoㄒ)/~~

**Comment by 2378** [comment]
500也不算少了
我这高危地区，ip200+，延迟1000+

**Comment by GoodSake** [comment]
100多够用飘过。

![snap1](https://user-images.githubusercontent.com/19205130/38763091-4a887fbc-3fc7-11e8-951c-77e417c09b3a.png)

**Comment by AnyWAT** [comment]
@GoodSake 🤣楼主说的是总ip数，貌似3.7.5程序默认不是6000就是3000。检查你的
 code\default(或3.7.5)\gae_proxy\local\proxy.ini 文件，max_good_ip_num = 6000（或3000）
