### ISSUE TITLE
smart router使用相关问题

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#10446]
环境：Windows 10 64位  校园网（有ipv6）
平时使用hosts上Google
①仅使用ipv6 hosts，switchOmega为直接连接，可访问谷歌
![image](https://user-images.githubusercontent.com/14359560/38732158-ce75451c-3f4f-11e8-8aeb-480c202b8064.png)

②使用smart router时：
![image](https://user-images.githubusercontent.com/14359560/38732255-227f93c4-3f50-11e8-9024-5b96d8b6000b.png)
可看到Google经过age代理访问了

③将Google添加到直连（添加为google.com），使用smartrouter时
![image](https://user-images.githubusercontent.com/14359560/38732358-76344c3a-3f50-11e8-8271-14cdea519b5d.png)
![image](https://user-images.githubusercontent.com/14359560/38732325-6087d3a2-3f50-11e8-8b01-e86b86b5137a.png)
smart router日志：
Apr 13 19:28:37.436 - [DEBUG] domain host:www.google.com:443 try gae, GetReqTimeout:19
Apr 13 19:28:37.455 - [DEBUG] host:www.google.com:443 do gae
Apr 13 19:28:37.622 - [DEBUG] host:www.google.com:443 do gae
可看到Google仍然使用了gae代理访问
若将Google添加直连为www.google.com时，则无法访问
![image](https://user-images.githubusercontent.com/14359560/38732450-c2225560-3f50-11e8-9f5b-f4828633b7d8.png)

ps：因为直接使用hosts方式访问速度更快，使用gae时打开谷歌需要5s左右。

**Comment by SeaHOH** [comment]
可以用 switchOmega 来配置直连，没必要全走智能代理。

**Comment by SeaHOH** [comment]
先关闭，仍然可以回复。
