### ISSUE TITLE
没有完全适配python 3

### ISSUE THREAD

**Issue by chaikau** [XX-net/XX-Net#10448]
xxnet版本：3.11.9(最新版)
系统：ArchLinux x86_64 
python版本：python 3.6.4

未在wiki搜到相关信息，未在issues区搜到相关讨论

由于这篇[即将放弃Python 2.7的不止有Numpy，还有pandas和这些工具](https://www.jiqizhixin.com/articles/2017-11-18-2)的说明，遂决定移除python 2，将系统迁移到python 3 环境，切换后 xx-net启动失败。

已安装pyopenssl库，方式为直接启动start脚本

尝试：

- start脚本错误

文件：start
脚本的28行，逻辑刚好反了。纯python 3环境下，PYTHON被设为python2：
`if python -V 2>&1| grep -q "Python 3" ;then
    PYTHON="python2"
else
    PYTHON="python"
fi`
改为如下代码后此问题修复：
`if python -V 2>&1| grep -q "Python 2" ;then
    PYTHON="python2"
else
    PYTHON="python"
fi`

- reload(sys)错误

文件：code/default/python27/1.0/lib/noarch/xlog.py
reload为python2才有的，python3已移除。
删除reload(sys)、sys.setdefaultencoding以及import sys后不再报错。

- basestring、unicode错误

文件：code/default/python27/1.0/lib/noarch/xlog.py
python中basestring和unicode均已经移除，使用str代替

- 未知错误
文件：未知
之前的问题都修复后，仍出现异常，message如下：

> [b'launcher'][ERROR] uncaught Exception, type=<class 'ModuleNotFoundError'> value=No module named 'error' traceback:<traceback object at 0x7f3dbcf8cfc8>

由于message中没有给出文件名、行号等有用信息，无法再修改下去

相关的日志：
- start:

> ./start:行56: python2: 未找到命令

- xlog.py:

> Traceback (most recent call last):
>   File "code/default/launcher/start.py", line 54, in <module>
>     from xlog import getLogger
>   File "/home/user/.local/opt/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 12, in <module>
>     reload(sys)
> NameError: name 'reload' is not defined

> Traceback (most recent call last):
>   File "code/default/launcher/start.py", line 54, in <module>
>     from xlog import getLogger
>   File "/home/user/.local/opt/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 273, in <module>
>     default_log = getLogger()
>   File "/home/user/.local/opt/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 259, in getLogger
>     if not isinstance(name, basestring):
> NameError: name 'basestring' is not defined

> Traceback (most recent call last):
>   File "code/default/launcher/start.py", line 54, in <module>
>     from xlog import getLogger
>   File "/home/user/.local/opt/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 273, in <module>
>     default_log = getLogger()
>   File "/home/user/.local/opt/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 261, in getLogger
>     if isinstance(name, unicode):
> NameError: name 'unicode' is not defined

- 未知错误部分：

data/launcher/error.log:

> 4月 13 20:17:00.3884 type:<class 'ModuleNotFoundError'> value=No module named 'error' traceback:<traceback object at 0x7f619ce3dfc8>

data/launcher/launcher.log:

> 4月 13 20:17:00.3884 - [ERROR] uncaught Exception, type=<class 'ModuleNotFoundError'> value=No module named 'error' traceback:<traceback object at 0x7f619ce3dfc8>

请修复python3的兼容性

**Comment by SeaHOH** [comment]
其实这个只是 Python 2 版本，还有个 Python 3 的版本，不过没有同步升级。

之所以只升级 2 的版本，我想是因为人力不够吧。

**Comment by 2378** [comment]
不久之前就是python3版了，很多ubut用户打不开8085，才改回来的吧

**Comment by chaikau** [comment]
@SeaHOH 主要是最后那个异常不知道是哪里抛的，不然就追踪下去了

**Comment by chaikau** [comment]
@2378 有一种升级叫python2到python3, 有一种重构叫urllib到urllib2到urllib3(滑稽

**Comment by SeaHOH** [comment]
代码量太大，不要调了，除非你有大量时间和精力。

**Comment by inksnw** [comment]
1.python3生成证书cert_util搞定
2.寻找可用ip,建立连接池搞定
3.本地访问走8087到simple_server搞定
4.simple_client接收gae主机的response搞定
5.接收到response后zlib.compress失败,感觉是因为gae部署的服务端是python2版本的?,socket返回的格式不对?...折腾好几天,放弃治疗了...

**Comment by SeaHOH** [comment]
@inksnw 你可以看我的 GotoX 3.3.2 版本的处理，之后版本放弃 python 2 兼容了。

**Comment by inksnw** [comment]
@chaikau 
XX-Net\code\default\launcher\start.py的74行
sys.excepthook = uncaughtExceptionHandler注释掉你就能看到异常在哪了

**Comment by chaikau** [comment]
@inksnw 好的，我试试，thx!

**Comment by SeaHOH** [comment]
如果要继续讨论，可以转到 https://github.com/XX-net/XX-Net-dev ，这里先关掉。
