### ISSUE TITLE
youtube 3.11.7登录不了

### ISSUE THREAD

**Issue by wushibinbilly** [XX-net/XX-Net#10442]
3.11.7版本，YouTube可以打开，但是不能登录！

**Comment by AnyWAT** [comment]
貌似代理速度的锅😂
试试：http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP，待扫描结束，IP延时减小后再操作。。。
需保持较小的延时，关闭”自动调整扫描线程数“，增大扫描线程到50-100？

**Comment by wushibinbilly** [comment]
不是吧，，我上Facebook，Google等等国外的网站都是毫秒级别的，快得很，就是登陆不了YouTube而已

**Comment by wushibinbilly** [comment]
现在xx-net加上ipv6的话速度是非常屌的，这个毋庸置疑，很棒；就是登陆不了YouTube，奇怪

**Comment by wushibinbilly** [comment]
赞，更新了就登录成功了，谢谢

**Comment by wushibinbilly** [comment]
奇怪，现在又登录不上，变成cookie问题了，明明浏览器允许的

Oops! Your browser seems to have cookies disabled. Make sure cookies are enabled or try opening a new browser window.

**Comment by AnyWAT** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by SeaHOH** [comment]
等待新版发布
