### ISSUE TITLE
ip延迟高是什么原因？怎么解决？

### ISSUE THREAD

**Issue by ShoukakuCoCi** [XX-net/XX-Net#10443]
ip延迟高是什么原因？怎么解决？

**Comment by userggg** [comment]
新版本延时确实高，先换回以前的版本吧。win10 64 最好用的还是3.8.7.
![xx-net -](https://user-images.githubusercontent.com/38343486/38720470-eea3ba66-3f28-11e8-958e-b68bb55b21ce.png)

**Comment by ShoukakuCoCi** [comment]
现在是用最新的3.11.9，我倒退试试

**Comment by SeaHOH** [comment]
删除 good_ip.txt，然后重启 XX-Net，等待几至十几分钟。

**Comment by mtgitnerd** [comment]
试过了，连dns都改了，没啥用，还是维持在延迟1000+

**Comment by SeaHOH** [comment]
@mtgitnerd 试过我说的了？那么换个 teredo 服务器再试试，这个再不行就是没法了。
换版本并不会解决这个问题。

还有就是显示延迟大，但是用起来没感觉，表现为点击连接后加载很快，而不是很久才能加载完毕。
这种只是显示问题而已。

**Comment by AnyWAT** [comment]
🤣IP延时大、或转换XX-Net版本及网络卡顿，试试：
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP，IP延时减小。。。
保持较小的延时，（3.10.5及以后版本？）需关闭”自动调整扫描线程数“，增大扫描线程到50-100（或自己调试）？
😂试过了，连dns都改了，没啥用，还是维持在延迟1000+：需要给你“有图有真相”么？
同一IP上限、适当增大扫描线程，或关闭“自动调整扫描线程”后基本稳定的 IP延时😜
3.8.5：250左右
3.10.4：250左右
3.10.8：？
3.11.7：300-350
3.11.9：280-320
😂😂换版本并不会解决这个问题：从程序显示的IP延时数字上看，换版本是可以解决的

**Comment by SeaHOH** [comment]
不同版本计算延迟的算法有些微差别，还不懂我也不会重复了。

**Comment by AnyWAT** [comment]
从程序显示的IP延时数字上看🤣

**Comment by mtgitnerd** [comment]
好的，再试下，另外，修改ip最大上限数这个，在哪改呀，请教各位？

**Comment by AnyWAT** [comment]
😂可以自设定 IP 数上限 xxx，3.10.5 以前版本，manual.ini 添加（建议1000足以）
[google_ip]
max_good_ip_num = xxx
3.10.5 开始，config.json 添加
"max_good_ip_num": xxx

**Comment by noritor** [comment]
@AnyWAT 

3.10.5 开始，config.json 添加
"max_good_ip_num": xxx

3.11.7添加这一段后XX无法启动。XXX=1000

**Comment by AnyWAT** [comment]
config.json 有错误，贴（马赛克AppID，但可看清行末符号）

**Comment by SeaHOH** [comment]
不要手动修改！删除 good_ip.txt 重启 XX-Net 扫描十几分钟即可。
如果这样也无法改善，修改上限也不会好转。

**Comment by AnyWAT** [comment]
如果IP上限不超过2000，千万不要删除 good_ip.txt，
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP，最快几十秒内即正常🤣

**Comment by SeaHOH** [comment]
你是想几十秒正常还是几天十几天都正常？

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38749205-5d0105e0-3f83-11e8-8ddd-3ca8ce7e6b19.png)
😂代码盲请教：如果仅仅”不同版本计算延迟的算法有些微差别“，怎解释貌似3.10.5以后的版本，程序默认设置下运行一定时间后IP延时达大几百（不能代理、假死、死？我没让它达上千还不人工干预），但手动扫描后可折半到250-350，调整参数后却能保持稳定在较小的数值呢？✋

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10429 
![image](https://user-images.githubusercontent.com/37962734/38750116-7f77bc7e-3f86-11e8-8458-fe7110495f69.png)
貌似记得当时看到他人的此说法后还@了某大佬，好像没看到回应，贴子也没本事搜索到了😥

**Comment by SeaHOH** [comment]
之所以会给你说这些，是因为你总是想用一套同样的方法来解决所有问题。
没你那么好精力，不太想说了。

透露一条消息，我才分析了一个多小时：
谷歌 App 的服务器和一般网页的服务器，已经不支持任意 SNI 名称混用了，估计 XX-Net 的 fake SNI 也会受到影响。

**Comment by AnyWAT** [comment]
总是想用一套同样的方法来解决所有问题：如果行就好，再说虽代码盲但还是😥老机械人，绝不会妄想如此，只是经历并成功了，才。。。
透露的消息对代码、网络盲简直是对牛弹琴，想必会要更加辛苦你们程序员大佬了，👍万分感激！！！

**Comment by AnyWAT** [comment]
哎，明说了从1000到500再到300，还说神马2000😱
马赛克AppID，贴config.json，能清晰每行末标点

**Comment by jkng** [comment]
因为IP库 还是那些IP 不管你怎么扫 还是用那堆IP

**Comment by bibichuan** [comment]
我的常年在400到600之间，只能做个备用，还是自己花钱弄个ssr，速度可以达到七八十毫秒

**Comment by AnyWAT** [comment]
一般300（左）右

**Comment by ShoukakuCoCi** [comment]
我自己租了个毛子的服务器 私人机场还是很爽的 XX-Net现在当三号机备用
