### ISSUE TITLE
GMAIL邮箱收不到新邮件

### ISSUE THREAD

**Issue by robert301** [XX-net/XX-Net#10441]
XX-Net Version | 3.11.7
打开xx-net以后，可以自由打开外网。 但是登录邮箱以后，就显示“对不起 系统遇到问题（#500）然后新邮件就收不到。

* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by SeaHOH** [comment]
请提供更多日志

**Comment by SeaHOH** [comment]
是不是记错了，我好像什么都没写，你要怎么试？？

**Comment by robert301** [comment]
哈哈， 回复错人了。 现在有新版本了，已经解决了这个问题。不过还是很感谢

2018-05-04 18:28 GMT+08:00 SeaHOH <notifications@github.com>:
