### ISSUE TITLE
土办法解决叉叉奈特新版IP猛掉问题

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#10445]
最近叉叉奈特不稳定，各种新版IP猛掉，经常断线。
技术方面咱不懂，一点不懂。
只能用土办法解决
——多下载几个版本，这个不行用那个，总有一款是能用、好用的。
——而不好用的版本，过两天也许又能用了。
这么神奇吗？
真的~
不信你试试~
虽然很土。

**Comment by AnyWAT** [comment]
此其一，其二：
https://github.com/XX-net/XX-Net/issues/10443#issuecomment-381071174

**Comment by Zmm1977** [comment]
换旧版一般能坚持10分钟，然后ip经常会归零

**Comment by Zmm1977** [comment]
换旧版一般能坚持几分钟到一小时，然后ip数会慢慢归零，新版虽然延迟高却不会慢慢的ip归零，实话实说

**Comment by wuwuti** [comment]
@Zmm1977    嗯，那就再换。貌似几个经典版（每次大改动之前的版本），一直能用。

**Comment by MadMaxPayne8964** [comment]
跟运营商和地区有关，AnyWAT也别到处复制粘贴你所谓的方法了，封锁严重的地区那根本就不是方法。我电信换任何版本都一切正常，联通几个省份IP都很快掉到100以内延迟过千

**Comment by AnyWAT** [comment]
@MadMaxPayne8964 🤣此其一，其二：#10443 (comment)
解决好其二，就没有其一的各种新版IP猛掉，经常断线

**Comment by AnyWAT** [comment]
@MadMaxPayne8964 🤣（或退出XX-Net再重开，或禁用再启用网络）
手动检查IP。。。“去伪存真”，减小IP延时
如果关闭了“自动调整扫描线程”，仅 IPv6 ，尝试再增大扫描线程。。。维持较小IP延时
