### ISSUE TITLE
古老问题：现在有办法解决文件上传的问题了没？

### ISSUE THREAD

**Issue by DipperTheCoder** [XX-net/XX-Net#10450]
这是一个极其古老的问题了，印象中四五年前用GAE的时候就搜过，当时发现GAE是无法正常往youtube传视频的，事实上稍微大一点的文件如音乐也都不能上传。后来看到一些解决方案但是都不管用。
不知道现在XX-Net有没有办法解决了吗？
刚刚试了下发现好像可以传视频了，只是进度显示有问题。
关键不能往soundcloud传音乐，我是做音乐的，很想分享作品，但是传不上去比较头疼。

**Comment by SeaHOH** [comment]
要求太细，这个需要自己根据 url 调配规则，使用 SwitchyOmega 之类的。
建议上传使用 X-Tunnel。

**Comment by DipperTheCoder** [comment]
@SeaHOH 有具体的操作步骤吗，印象中当年就是改一堆规则但是最后没成功

**Comment by SeaHOH** [comment]
自己尝试，我又不用上传。`F12` 观察网络加载情况。

**Comment by GoodSake** [comment]
github上传，youtube上传一切正常飘过，soundstrack第一次听说，哈哈哈

**Comment by DipperTheCoder** [comment]
@SeaHOH 我知道可以用别的，那我还可以用其他工具还可以买VPN，但我问的是XX-NET。

**Comment by AnyWAT** [comment]
貌似不会添加切换规则😜
不就是在模式X-Tunnel自动切换或GAE-Pro自动切换，添加你的 soundcloud 走X-Tunnel 或GAE
![image](https://user-images.githubusercontent.com/37962734/38776004-4f6c4cd8-40c2-11e8-878b-65fdb5604260.png)

**Comment by SeaHOH** [comment]
@AnyWAT 你再喂他也不一定会，而且好些时候你喂的都算不上饭。。。

其实你们这种适合远程，直接让别人帮操作就行。

**Comment by AnyWAT** [comment]
F12 观察网络加载情况：（这后面貌似@SeaHOH 说的非饭😂）未正常连接的网址添加到。。。
😜用户千差万别。。。

**Comment by DipperTheCoder** [comment]
@SeaHOH 你有病吗，瞎扯什么喂饭，用了多少年了，基本的规则添加我当然会。
但当年的GAE和现在的XX-NET上传一直有一个很奇怪的现象，上传会突然间“冲破带宽限制”，显示每秒十几兆甚至几十兆，但实际上并没有什么进度。然后过一会进度会往回退，运气好的话几百兆上G的视频可能能传好，也可能传不好。
这是youtube的情况，而soundcloud则是完全没办法传。

**Comment by AnyWAT** [comment]
既然如此，说明GAE、X-Tunnel都无法代理，在2楼的@SeaHOH 回复后就应告知，怎会有3楼的“@SeaHOH 有具体的操作步骤吗”呢？也就没有3楼以后的对你无助的各楼了。
🤣貌似没有万能的代理

**Comment by DipperTheCoder** [comment]
顺便提一点，soundcloud这个网站对GAE和XX-NET似乎向来不友好，印象中当年有一段时间GAE直接上不去，后来更新了新版本才能用。即使现在，很偶尔的时候XX-NET也要刷新一遍才能正常访问soundcloud。

**Comment by AnyWAT** [comment]
后来更新了新版本才能用：现在不可运行此版？

**Comment by SeaHOH** [comment]
上面说了，我又不用，怎么知道？？
SwitchyOmega 和 `F12` 的信息量还不够你折腾？？

**Comment by DipperTheCoder** [comment]
@SeaHOH 不用或者不知道可以不参与讨论，不能提供更详细的解决方案可以不参与讨论，你就贴个SwitchyOmega 和 F12 这叫什么信息量。

**Comment by DipperTheCoder** [comment]
@AnyWAT 感谢参与讨论，只是我觉得我这边贴个诊断信息并没有什么代表性，过去几年我换了很多网络环境、操作系统，但soundcloud上传的问题一直都存在，你们传可能也传不上去。
而且为什么会出现上面说的进度、速度很奇怪的现象？恐怕要开发者才能解答吧。

**Comment by AnyWAT** [comment]
嗯嗯，造车的一定比开车的处处在行🤣

**Comment by SeaHOH** [comment]
有人帮解决了，我就关掉啦。
