### ISSUE TITLE
无法设置局域网代理，显示“保存设置失败：test proxy fail”

### ISSUE THREAD

**Issue by ZFSieben** [XX-net/XX-Net#10455]
版本3.11.8

**Comment by SeaHOH** [comment]
这个其实是 XX-Net 使用的前置代理，不知道谁改的这个名字。

**Comment by AnyWAT** [comment]
LS意思，楼主需要的 http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页(帮助)——ON

**Comment by ZFSieben** [comment]
需要手动改监听吗？以及iOS上怎么填？现在端口8086似乎给了smart router
