### ISSUE TITLE
感觉新一层砖块已经叠高了

### ISSUE THREAD

**Issue by abigbone** [XX-net/XX-Net#10458]
我还在油管上看视频~~ ，上个厕所回来就 上不去了。

**Comment by AnyWAT** [comment]
手动检查IP。。。
如果关闭了“自动调整扫描线程”，仅 IPv6 ，尝试再增大扫描线程。。。

**Comment by applestone** [comment]
别的地方不能确认，青岛这边的确提高了。前几天也是一直出不去，后来经过高人指点解决了。后来问了一下青岛联通这边的朋友，因为要开上合会议，的确是加大了监管力度。

**Comment by f18love** [comment]
之前登录不了账号的问题解决后。  
这两天YouTube  看不了。  

页面加载不了。  一片白

邮箱可以登

**Comment by tokjay** [comment]
@applestone 老哥，请问如何解决的，同青岛

**Comment by wengerout2049** [comment]
刚打完电话 青岛正在入户登记 连做什么工作和有无煤气罐都要汇报上去 
把老百姓当敌人 早晚上歪脖树

**Comment by SeaHOH** [comment]
燃气似乎属于常规安全检查，工作就不用关心了吧，除非是非常住人口。

**Comment by Eri5Ch** [comment]
海底光缆有一个入口就在青岛哦...

**Comment by wengerout2049** [comment]
我奶奶的房子 我奶奶去世了没人住 派出所就来人问东问西 好像我们有做错事似的
即便是外来人口又怎样 他们不是中国人吗 又要学北京排华驱逐低端人口吗

**Comment by SeaHOH** [comment]
中国的治安算得上很好，但也不是没有恶性事件发生，这属于正常检查。
当然，如果警员态度不好，反映后依旧如此，别犹豫，记下警号，投诉。。。

**Comment by SeaHOH** [comment]
忘了说，检查需要出具身份证明和检查文件。

**Comment by abigbone** [comment]
看什么时候，我就遇到过路口设卡检查，你找他要工作证，他要把你带进小黑屋询问  @SeaHOH

**Comment by AnyWAT** [comment]
有说理论上的，有说实际上的。然而，绝大部分是实际与理论严重不符的。。。

**Comment by SeaHOH** [comment]
我说的是上门检查。。。
人家自己地盘最多就敬个礼、秀下证件，没有检查文件。

除非有正当理由，不要配合他的任何不合理要求，必要时记得悄悄打开录音，以便事后追查。
