### ISSUE TITLE
封锁越来越紧 说明鬼子的末日就要来到了

### ISSUE THREAD

**Issue by wengerout2049** [XX-net/XX-Net#10452]
现在连玩段子的觉悟都这么高，再不跟上形势就真的落后了:)

![2018-04-12_222546](https://user-images.githubusercontent.com/32247328/38746979-e8273228-3f7b-11e8-9e9b-7311b13eca71.jpg)

![83a4ba1bb051f819a45228b9d3b44aed2f73e700](https://user-images.githubusercontent.com/32247328/38746824-44dc1c64-3f7b-11e8-94f0-021bf6e01e94.jpg)

哪天突然不需要xxent了会不会有失落感^_^

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38763346-fd9fe154-3fcb-11e8-8d02-91ab15111a22.png)

**Comment by 2378** [comment]
嘀～嘀嘀～ :trollface:

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38765333-2a3da45a-3ff2-11e8-8002-50d1ed57c211.png)

**Comment by GoodSake** [comment]
冷战是技术准备，今天是开打，打光那些闹事叙利亚兔崽子。大光us导弹，然后停战回家再生产更新的。
钱多弹多没地方花，真是个事，哈哈哈！
我觉得把导弹卖给台湾，然后把钱捐给菲力宾教育部就是更好？突然觉得Trump比我笨，哈哈哈！

**Comment by AnyWAT** [comment]
🙃RT @qq196837 【叙利亚总统府在推特发视频称：阿萨德在空袭第二日早上，“步伐坚定”地来到办公室。此前，在美国宣布对叙利亚空袭的同时，叙利亚总统府发推称：高贵的灵魂不会被侮辱】 萨达姆、卡扎菲在被消灭前同样也是这么高贵和坚定。 pic.twitter.com/T6f1paXvVa

**Comment by AnyWAT** [comment]
🤣美国总统川普和法国总统马克龙：那些认为关起门来就可以肆意凌辱自己国民的时代，结束了！

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38766559-0a1ea160-4006-11e8-8690-0b3e0bda3b87.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38766677-9e0e0bf8-4007-11e8-8a67-ad6aa250ceb3.png)

**Comment by asmosn** [comment]
墙内新闻吹嘘Syria拦截了联军飞弹，暗地里确取消包帝登辽宁舰计划

**Comment by lndnxp** [comment]
![capture](https://user-images.githubusercontent.com/32247328/38767616-3037afac-4017-11e8-98d8-f0f4f27529d3.PNG)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38774058-1d0c33ce-4091-11e8-959d-3f127ede2b74.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38777991-1d05adda-40e4-11e8-9196-f4ee89237ea4.png)

**Comment by kksh3ll** [comment]
傻x玩意儿，有问题就问，没问题就悄悄的，贴了一堆破图片，这里是讨论政治的地方吗？以后github不能访问，就是你们这些蠢b搞得

**Comment by GoodSake** [comment]
github才不在乎cn能不能用呢，哈哈哈。。。

**Comment by SeaHOH** [comment]
有人投诉的话会处理这类。。。

**Comment by wengerout2049** [comment]
> 傻x玩意儿，有问题就问，没问题就悄悄的，贴了一堆破图片，这里是讨论政治的地方吗？以后github不能访问，就是你们这些蠢b搞得

1. 五毛你好 等你好久了. 现在钓一条要这么久 是发不出工资了吗？

2. 每次的借口都一样 能拿点新意吗 ，五毛培训水平要跟上形势变化偶

3. 张口就是生殖器 这是五毛的标准作业流程吗？土匪人人皆可骂，真正的恶行你视而不见，对于不同的意见确如饿虎扑食一般疯狂压制，我都替你羞耻

4. 求你提供一个可以在墙内没有政治审查可以"讨论政治的地方",在线等挺急的^_^

**Comment by wengerout2049** [comment]
我不想关心政治 你主子把段子关了逼我关心政治 我也很无奈：（

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38778842-e114c29e-40f1-11e8-81e4-954fb2488cca.png)

**Comment by SeaHOH** [comment]
https://xbrick.blog/2018/01/09/XBrick教你如何下载电报（Telegram）与加入电报群/
这个更安全

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38780566-41f515f0-410b-11e8-81b2-71b0fe88717d.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38784533-dbe226dc-4145-11e8-8d3e-3dce352f4c7d.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38785610-4e3c6388-4154-11e8-98a6-bdc0bfd233fa.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38787566-58c20e90-4161-11e8-929a-62bc47f158df.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38789135-cfa976e8-416a-11e8-9274-c3e0e7d98914.png)

**Comment by noritor** [comment]
那王八图P得太烂了。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38802412-f2cd2d20-419e-11e8-8775-f3441e57e387.png)

**Comment by wengerout2049** [comment]
> 那王八图P得太烂了。

那图确实没有经过求证真伪 觉得好玩就发上来了. 若觉得不可信 不信就好

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38816160-15e54db4-41c8-11e8-83ed-0535afb77767.png)

**Comment by AnyWAT** [comment]
😱RT @szstupidcool 质疑鸿茅药酒的广州谭医生，关进看守所三个月前后的对比。 pic.twitter.com/vRYEvquH1D
![image](https://user-images.githubusercontent.com/37962734/38867048-6ffd1db0-4275-11e8-8ec3-4a1b50bf3752.png)
![image](https://user-images.githubusercontent.com/37962734/38867056-74ab3e14-4275-11e8-9fcd-54f8777e5d29.png)

**Comment by AnyWAT** [comment]
转：北京某名牌小学，一个女学生在哭泣。 同学愕然，老师也奇怪，这个女学生的父亲是高官，为何哭泣？ 老师好劝歹劝，女孩终于说话了：“我爸爸经常说美国黑暗，是人间地狱，但是昨晚我听到爸爸对妈妈说等我大一点，要送我去美国。”
![default](https://user-images.githubusercontent.com/37962734/38906346-c0ef7358-42e8-11e8-9051-8bec01558417.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38906684-abe0a49e-42ea-11e8-83c3-97246b146170.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38906926-e636f836-42eb-11e8-9b5a-a8d77210d685.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38908689-039d4616-42f4-11e8-8c51-e1dfcdc03c59.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38909677-3794d214-42f8-11e8-97c9-52f968e8e054.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38910406-bd667ff2-42fb-11e8-9e6c-5ce2d8aca0c3.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38924431-882b91b8-432f-11e8-8750-ac415965b47a.png)

**Comment by asmosn** [comment]
@AnyWAT  大神兄弟别挖坟了，低调点啊（你在墙内的话，要是被抓XX版就没人排忧解难了）...

**Comment by wengerout2049** [comment]
人家都上街了也没见抓人啊 估计经费不够了

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38964149-da456bfe-43a7-11e8-9641-41baaa9d8189.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38968071-7ca81996-43bc-11e8-8eaa-99cf2d3125c8.png)

**Comment by nly4lov** [comment]
这个帖子里说的都是些神马瘠薄玩意啊？！

**Comment by wengerout2049** [comment]
> 这个帖子里说的都是些神马瘠薄玩意啊？！

你不爱看别看啊 我没逼你看

我们不像某些人控制全部电台电视报纸还不够 每天微博微信段子删不完封不够 用纳税人的钱造墙制造信息鸿沟 不断过滤信息圈养你这种猪

**Comment by wengerout2049** [comment]
不过图太长了 打开都要费老天事 可以考虑换个阵地:) @AnyWAT

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39026448-cf6f5194-447f-11e8-88f7-c2e60063c6a7.png)
🤣转：厉害了，我的国，网上盛传下架。即便下架，我的国，还是厉害！这片子出来，就像一莽汉出来到处说：我的家，厉害了！我，厉害了！别人看了会害怕？估计别人只会说，这人真二！厉害这词出自别人口，那是真厉害了，出自自己口，那是口活的厉害。不管厉害不厉害，这片子已经卖了四个亿，爱国者的营销厉害！
![image](https://user-images.githubusercontent.com/37962734/39026475-f6a2ba30-447f-11e8-9c16-3a71aebe2168.png)
![image](https://user-images.githubusercontent.com/37962734/39026509-1797e724-4480-11e8-939c-446d599ff3dd.png)
