### ISSUE TITLE
360太恶心老是阻拦XX，求一个好用的防护软件。

### ISSUE THREAD

**Issue by 9394sky** [XX-net/XX-Net#10451]
360太恶心老是阻拦XX，一起IPV4阻拦，现在IPV6老是将IP Helper服务禁用，导致IPv6相关的隧道和其他功能无法使用。

求一个好用的防护软件。

**Comment by asmosn** [comment]
360和工信部早就一伙了，用这些国产流氓软件XX死的更快

**Comment by 9394sky** [comment]
我也想用火绒，但网上说老是蓝屏。近段时间在调测路由不敢试，怕刷固件是蓝屏

**Comment by ARCHOTZ** [comment]
用XX就把电脑上的国产软件都干了，不然多少IP都没用。

**Comment by 9394sky** [comment]
楼上，火绒也是国产的。也不能用了，对吧？

**Comment by asmosn** [comment]
防护可以试试小红伞,卡巴斯基,comodo...我上网用chrome/Win7裸奔啥事都没，越用国产软件越中毒

**Comment by lkyyang** [comment]
卡巴斯基免费版

**Comment by asmosn** [comment]
非要用国产软件的话，尽量google搜索绿化免安装版，基本不会中毒

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/38750699-57e22a1c-3f88-11e8-96a4-82eb7cfbc389.png)
![image](https://user-images.githubusercontent.com/37962734/38750704-5ceeaa80-3f88-11e8-97dd-13dae436ab67.png)

**Comment by momo3030** [comment]
防毒：Malwarebytes（免费版没有实时保护，靠手动扫），Adware Removal Tool（手动扫），Hitman Pro（手动扫）
清理：Wise Care 365（免费版无法清理操作记录，可以清理垃圾），CCleaner

其实直接输入法切换成繁体然后Google上搜 免費防毒軟體 之类的就行...

**Comment by caofengzi** [comment]
安全不是靠程序來做的，安全是需要自己來做的，好的習慣比好的安全軟件更加有用。

**Comment by GoodSake** [comment]
没防毒软件飘过一只，哈哈哈。
很多人惊奇我一个4G小本本，怎么开那么多youtube页面，我只想说没防毒软件占内存，当然能开很多哦。哈哈哈哈！

**Comment by cennong** [comment]
用mse

**Comment by imldf** [comment]
微軟defender

**Comment by ARCHOTZ** [comment]
接昨天，个人用的COMODO互联网套装，火绒应该可以，那些有流氓行为大公司就别装。

**Comment by tcwilliy** [comment]
用win10 基本就是裸奔

**Comment by iversonLv** [comment]
裸奔啊兄弟。

**Comment by SeaHOH** [comment]
离主题太远，关闭。
