### ISSUE TITLE
新的风暴已经出现

### ISSUE THREAD

**Issue by yxlrz** [XX-net/XX-Net#10459]
请问还有没地方可以找到组织，我怕这里以后都见不到了

**Comment by yxlrz** [comment]
原来是昨天WIN10更新把防火墙开了导致IPV6状态FAIL...囧

**Comment by AnyWAT** [comment]
🙃一直开启，一直正常的路过

**Comment by dahai058** [comment]
我的也一直开着防火墙

**Comment by asmosn** [comment]
手机版xndroid比PC上顺畅(同一路由，相同XX版本)…

**Comment by AnyWAT** [comment]
手机版xndroid默认没开启 X-Tunnel、Smart-Router
