### ISSUE TITLE
局域网设备无法连接8087端口了

### ISSUE THREAD

**Issue by DNACore** [XX-net/XX-Net#10461]
局域网设备无法连接 gae:8087，可以正常连接SmartRouter:8086
本机可以正常连接127.0.0.1：8087，8086等
这是怎么回事啊？
备注：以前是正常的，期间没有改过任何设置。升级到最新版本还是这个样子。

另外再求教一个问题，Smart Router里面缓存的连接规则怎么看啊？
比如说`imgcache.qq.com unknown 1 `这里的 `unknown` `1`各是什么意思？

```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:27 h2:0
scan-ip-thread-num: 10
ip-quality: 453
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by AnyWAT** [comment]
运行XX-Net的本机上GAE证书与先前有（重载了？时间上）变化，其它机器得加载当前本机的证书？
use-ipv6: auto 改为仅 ipv6
scan-ip-thread-num: 10 增大5倍，关闭“自动调整扫描线程”
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查IP

**Comment by SeaHOH** [comment]
其它设备可以打开 8085 不？

**Comment by DNACore** [comment]
@SeaHOH 如果不设置任何代理，是可以直接打开的，如果设置成8087之后，就什么也打不开了。GAE也没有任何日志。就好像这个端口根本不通一样。

**Comment by DNACore** [comment]
@AnyWAT 我没有在本机上安装证书，因为我一般都是通过局域网其他设备上网。所以，这里说的证书有问题应该不会影响局域网其他设备。局域网其他设备是已经安装了对应的证书的。
当走SMART ROUTER 访问网络完全正常说明证书没有问题，也说明GAE本身是好使的，就是8087端口不能远程访问。

gae d的 config 文件
```
[listen]
ip = 0.0.0.0
```
也没有更改过。

另外
```
use_ipv6 = force_ipv6
```

这个意思是已经强制使用 ipv6 了吧。

**Comment by SeaHOH** [comment]
查一下防火墙，8085 和 8086 都是好的，照理 8087 也不会监听错。
试试重启下 XX-Net，万一神奇的恢复了呢。

**Comment by DNACore** [comment]
@SeaHOH 我已经把 pythonw 可执行文件删除又重新添加了，仍然不行。、
其实这个问题两三个星期之前就有了。简单的开启关闭看来不是很管用。

**Comment by SeaHOH** [comment]
只能想到防火墙或安全软件，也许还有国产某软？

**Comment by AnyWAT** [comment]
没有在本机上安装证书——厉害😂，貌似启动XX-Net，不手动连接任何网页，也会自动连接某些网，即需要GAE证书
局域网其他设备是已经安装了对应的证书的——其它机器得加载当前运行XX-Net本机的证书？
https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1 采用GAEPROXY需要先导入证书 http://PC-IP:8085/module/gae_proxy/control/download_cert

**Comment by AnyWAT** [comment]
🤣不过，标题“局域网设备无法连接8087端口了”貌似按楼主说的曾经正常过？

**Comment by DNACore** [comment]
@SeaHOH 裸奔好多年，原装Windows 10，无任何第三方安全软件。
用 tcpview 查看8087端口也是 listen 状态。就是不通，不太清楚到底是哪里的问题。
局域网设备连接8087端口用这个软件看是没有入流量的，连接8086的时候机会有流量走...

**Comment by DNACore** [comment]
@AnyWAT 以前都是正常的，后来突然就不正常了。期间可能系统有升级过，记不太清楚了。但是XX升级过但是设置从来没动过。

**Comment by AnyWAT** [comment]
检查运行XX-Net机器与局域网其他任一设备的证书是否同一文件？

**Comment by SeaHOH** [comment]
>局域网设备连接8087端口用这个软件看是没有入流量的

连接上了？

**Comment by DNACore** [comment]
@SeaHOH 仍然没有，我已经放弃了...先凑合用SMART ROUTERR 吧。虽然我觉得这个东西非常不直观。、
比如我设置了某个域名直连，但是域名缓存里面没有我设置的那个，还有一大堆 UNKNOWN 的 不知道什么意思。

**Comment by SeaHOH** [comment]
没有更多相似案例，先关闭。
