### ISSUE TITLE
路由器推荐？

### ISSUE THREAD

**Issue by edamame43** [XX-net/XX-Net#10463]
想入一个路由器接所有的移动设备，不知如何挑选？符合openwrt的里面哪些比较好？稳定快速，价格1k一下，谢谢

**Comment by 9394sky** [comment]
华硕 刷 梅林

**Comment by 9394sky** [comment]
华硕 刷 梅林

**Comment by 9394sky** [comment]
我现在 一级用newifi D1 刷H大老毛子 （chinadns）  + 二级 newifi mini 刷iljiamin老毛子 (dnsmasq),可有youtuber 1080。

但是方便省事还是 买华硕刷 梅林吧！

**Comment by SasamiMasakiJurai** [comment]
1k价位可以组软路由了

自己买个软路由刷系统吧

**Comment by edamame43** [comment]
好的 我去研究一下

**Comment by roc1010kmt** [comment]
openwrt和梅林老毛子哪個好？

**Comment by SasamiMasakiJurai** [comment]
论可玩性是lede openwrt现在已经并入lede了

梅林可玩性不高

当然 

如果你不怕后门啥的可以刷第三方梅林

老毛子和lede一样

也有原版的

国内也有修改版

同样

你不怕后门可以刷国内修改版

**Comment by SasamiMasakiJurai** [comment]
又是第三方梅林。。。。。。。。。

k论坛有后门的

不怕死可以刷

**Comment by erdcy** [comment]
Linksys 1900ACS
