### ISSUE TITLE
xtunnel很不稳定速度又慢，求问怎么解决

### ISSUE THREAD

**Issue by yqqyzy** [XX-net/XX-Net#10467]
目前表现是
1、开启了xtunnel之后，可以用几分钟，之后经常出现无法使用的情况；
2、开启xtunnel，然后过一两个小时，就无法使用，需要重新启动才可以使用；
3、xtunnel速度慢，打开google首页都要几秒，油管视频无法流畅播放

状态页如下，求解：
X-Tunnel 状态信息

全局

属性	值
请求数	255
响应时间	41566
往返数	2995
较慢	407
重传	495
超时	2420
当前速度	Up: 1.0 KB/s / Down: 271.7 KB/s
使用总量	Up: 67.6 KB / Down: 20.5 MB
GAE 前端

属性	值
Score	False
成功数	0
失败数	0
工作数	0
使用总量	Up: 0.0 B / Down: 0.0 B
Cloudflare 前端

属性	值
Score	False
成功数	1051
失败数	225
工作数	1
使用总量	Up: 47.6 KB / Down: 7.3 MB
Cloudfront 前端

属性	值
Score	10359853
成功数	354
失败数	3
工作数	2
使用总量	Up: 19.9 KB / Down: 13.2 MB
Heroku 前端

属性	值
Score	False
成功数	0
失败数	0
工作数	0
使用总量	Up: 0 / Down: 0
TLS_Relay 前端

属性	值
Score	False
成功数	0
失败数	0
工作数	0
使用总量	Up: 0.0 B / Down: 0.0 B

**Comment by AlexanderShang** [comment]
iPV6打开了吗？ @yqqyzy

**Comment by AlexanderShang** [comment]
iPv4状态下的XX-Net很不稳定，极容易掉线

**Comment by yqqyzy** [comment]
ipv6没开，之前就是因为gae的ipv6没弄成功，才买了xtunnel的

**Comment by AlexanderShang** [comment]
XX-Net也是需要iPv6的

**Comment by AlexanderShang** [comment]
之前用了iPv4的XX-Net十分不稳定

**Comment by SeaHOH** [comment]
你这只有两个前端能工作，封的也太厉害了，尝试删除 xxx_ip_list.txt 重启试试。
最好把 IPv6 开启，多条通道。

**Comment by liuhun2000** [comment]
我跟楼主的情况一毛一样，卡慢，中途需重启才行，，。。之前用里面得到gaeproxy快多了，现在就是开不了ipv6，用不了。。实在郁闷，，去年十一月买了一年的X-TUNNEL，1200G，现在还剩1187G！

**Comment by liuhun2000** [comment]
有需要X-TUNNEL流量的告诉我，拿800G送人（单个账号最多80G）

**Comment by AreisII** [comment]
@liuhun2000 求转让流量，zy2587573qq@126.com

**Comment by SeaHOH** [comment]
等待新版发布
