### ISSUE TITLE
修改总ip数

### ISSUE THREAD

**Issue by seasandsky** [XX-net/XX-Net#10468]
XX-Net-3.11.9\code\default\gae_proxy\local   
config.py文件
打开找到以下代码
        self.set_var("max_scan_ip_thread_num", 10)
        self.set_var("max_good_ip_num", 500)
        self.set_var("target_handshake_time", 200)
修改第二行“500”。
关闭保存文件。

**Comment by AnyWAT** [comment]
直截了当🤣

**Comment by Mark486** [comment]
谢谢楼主，适用3.11.7

**Comment by 114zhangming** [comment]
精简.有用.谢谢
