### ISSUE TITLE
请检查代理设置 求解

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#10473]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:9 ipv4:0 ipv6:7
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:7 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
use-ipv6: auto　。。。
scan-ip-thread-num: 10　。。。
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced　。。。
重复若干次的臭大街。。。自动调整扫描线程数(帮助)，检查所有IP。。。

**Comment by SeaHOH** [comment]
组策略终于弄好了，这次轮到证书了。
怎么做已经滥大街了，此页顶部搜索`导入证书`即可，七百多结果。

**Comment by xiaoteai** [comment]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:46 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xiaoteai** [comment]
组策略 未配置   等待扫描IP，建议开启IPv6。  
 你可以连接互联网了   连上不到 一 秒

**Comment by xiaoteai** [comment]
状态
qualified

**Comment by xiaoteai** [comment]
弄烂烂   了大街

**Comment by SeaHOH** [comment]
>ip-quality: 9999

手动扫描或者删除 good_ip.txt 重启
