### ISSUE TITLE
无法打开google

### ISSUE THREAD

**Issue by mm333444** [XX-net/XX-Net#10478]
提示信息:
600:gae_exception:'600:fetch gae fail' http://www.google.com.hk/gae_exception:'600:fetch gae fail' http://www.google.com.hk/gae_exception:'600:fetch gae fail' http://www.google.com.hk/

XX-Net Status:

sys-platform: x86_64, Darwin-15.6.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64
os-release: 15.6.0
os-detail: Release:10.11.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
>ipv6-status: Fail
Appid_Working: false

https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引
