### ISSUE TITLE
私人AppID流量为何总显示被用完？

### ISSUE THREAD

**Issue by Richardleeeeeee** [XX-net/XX-Net#10471]
为何我的9个私人Google APPID的流量都会被用完了？我刚刚自己搜了一下，貌似是知道我的appid名字即可随意使用该APPID的流量？
如是，请问有什么解决的办法吗？
真的不想每天打开就说我的流量已经被全部占用了。。好烦。。。

对了 想捐出几个去换X-tunnel的流量。。该如何操作？

辛苦作者。。THX

**Comment by AnyWAT** [comment]
貌似是知道我的appid名字即可随意使用该APPID的流量：暴露了且没有密码倒有可能😋
报 X-Tunnel 账号接收流量？

**Comment by pingtouzi** [comment]
pingtouzizi@hotmail.com  @AnyWAT 这是我的X-Tunnel 账号  谢谢啦~~~

另外想问问  我如何给APPID加密？  

再说，，怎么会暴露的啊。。我貌似没做过什么会暴露的操作啊。。

刚刚刷新的流量  现在每个APPID的流量都去了60%了。。。我的天。。。

**Comment by AnyWAT** [comment]
我貌似没做过什么会暴露的操作啊：貌似在贴报错日志的时候
貌似加密得修改APPID。。。
已转

**Comment by pingtouzi** [comment]
@AnyWAT 可否指教一下？谢谢。。。

说真的我还真没有贴过报错日志。。以前一直都是自己解决的。。。这次不是XXNET的问题我反而还懵了。。。

**Comment by AnyWAT** [comment]
😜没加密。。。
[安全！安全！安全！]配置appid可以随便填，容易被盗用，盗用appid的也会被fuck #9184 二楼不是？试试重新部署一个。如不行，或许得删除旧的、重新创建APPID？
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

**Comment by AnyWAT** [comment]
如账号的APPID已建完（10个？12个？）删旧的至少1周后才能建新的

**Comment by SeaHOH** [comment]
其实加不加密我都可以让一个 ID 在一小时之类玩完。所以，你们千万别秀 AppID。

**Comment by GoodSake** [comment]
花时间设密码。。。不如再搞12个新的，哈哈哈。最近露id的怎么少了呀。。。

**Comment by xxnet** [comment]
​流量不够，用公共appid就好了吧，前段时间发布的公共appid足够大家用很久了

自己的appid流量丢了，可以上去看都访问了些什么网站，是哪个来源ip的，看谁敢偷别人的id
https://console.cloud.google.com/logs/viewer?project=你的appid

**Comment by ClarkCleson** [comment]
@AnyWAT 
* 创建密钥，需要关联结算帐户，但开了结算账户后，浏览配合就无限了。流量用了超过1GB怎么破，你可知道控制流量的设置吗？
* 设置密码环哪儿走不下去了，网络老师不稳定，悲催。感觉设置密钥好复杂，英文看着费劲。你可知道是否有中文的设置密码的教程？

**Comment by SeaHOH** [comment]
这里的密码不是密钥，而是个用于简单验证的字符串，写在 App 内部。

**Comment by ClarkCleson** [comment]
@AnyWAT @xxnet 怎么给AppID加密？可有可参考的文档？谢谢

**Comment by SeaHOH** [comment]
点知识分类就能看到
#10336

**Comment by ClarkCleson** [comment]
@SeaHOH 你真好，谢谢你
