### ISSUE TITLE
无法启动x-x net

### ISSUE THREAD

**Issue by beeblebum** [XX-net/XX-Net#10489]
* 是否试过最新的测试版本？
 3.11.9无法解决
  
* 简单描述遇到的问题：
xx net 无法启动，双击start.bat无用

* 做过哪些尝试：
3.11.7解压覆盖，没有解决
3.10.4解压覆盖没有解决

似乎是改过config.json，不知道怎么改回去

launcher.log

Apr 18 11:27:26.969 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0611FAA8>
Apr 18 11:27:39.697 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05A550F8>
Apr 18 11:39:41.799 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05E2DF30>
Apr 18 11:39:48.947 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0538CF58>
Apr 18 11:46:10.272 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05F79F80>
Apr 18 11:46:57.148 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05BFDF30>
Apr 18 11:51:46.371 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0608BF80>
Apr 18 11:51:47.777 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x056B9F80>
Apr 18 11:51:48.916 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05219F80>
Apr 18 11:51:50.004 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05DD9F80>
Apr 18 12:08:24.030 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x060FAF80>
Apr 18 12:08:26.632 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05D2DF30>
Apr 18 12:14:24.967 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0530DF30>
Apr 18 12:14:33.287 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05F59F80>
Apr 18 12:30:01.028 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05A3DF30>
Apr 18 12:30:04.158 - [ERROR] uncaught Exception, type=<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x053C9F80>

error.log

Apr 18 11:27:26.969 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0611FAA8>Apr 18 11:27:39.697 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05A550F8>Apr 18 11:39:41.799 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05E2DF30>Apr 18 11:39:48.947 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0538CF58>Apr 18 11:46:10.272 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05F79F80>Apr 18 11:46:57.140 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05BFDF30>Apr 18 11:51:46.371 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0608BF80>Apr 18 11:51:47.777 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x056B9F80>Apr 18 11:51:48.916 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05219F80>Apr 18 11:51:50.004 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05DD9F80>Apr 18 12:08:24.030 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x060FAF80>Apr 18 12:08:26.632 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05D2DF30>Apr 18 12:14:24.966 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x0530DF30>Apr 18 12:14:33.286 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05F59F80>Apr 18 12:30:01.028 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x05A3DF30>Apr 18 12:30:04.158 type:<type 'exceptions.ImportError'> value=WSAStartup failed: error code 10107 traceback:<traceback object at 0x053C9F80>

**Comment by SeaHOH** [comment]
删掉 json，重新配置，AppID 填原来的，不用重新部署。

**Comment by xxnet** [comment]
​搜索 “WSAStartup failed: error code 10107”
得到的答案，都是Windows系统的Socket 坏了
