### ISSUE TITLE
如何增加ip数量上限

### ISSUE THREAD

**Issue by ShoukakuCoCi** [XX-net/XX-Net#10486]
XX-Net版本3.11.9

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10487#issuecomment-382230833

**Comment by ShoukakuCoCi** [comment]
what?我是想把ip500上限设置成1000

**Comment by AnyWAT** [comment]
你的延时有达到250？由于GFW越来越。。。昨天从上限1000调整辉300🤣
