### ISSUE TITLE
4月17号以后大家还能连吗？

### ISSUE THREAD

**Issue by ccbynow** [XX-net/XX-Net#10487]
我就是想知道大家也都连不上了吗？我从昨天上午上班开始就连不上了
http://127.0.0.1:8085/ 这个都没有响应

无法访问此网站
127.0.0.1 的响应时间过长。
请试试以下办法：。。。。。。。

**Comment by foho8080** [comment]
可以連

**Comment by xuzhijiangx** [comment]
300多个IP 300多的延迟 480p基本都加载不动了

**Comment by shpherd** [comment]
16号17号两天可能GFW发动总攻了，看着ipv6数目大幅减少到没有或者几个，之前我一直是1000个左右。

**Comment by abigbone** [comment]
![image](https://user-images.githubusercontent.com/4329020/38907155-ffb2c758-42ec-11e8-986f-81628691436e.png)
这样算么？~  重启一下可好？

**Comment by milanthree** [comment]
我是连不上了

**Comment by ShineZhang090** [comment]
4月18日 努力挣扎一下 连上了
![qq 20180418102338](https://user-images.githubusercontent.com/32865256/38908427-b5e53ea2-42f2-11e8-80c2-c0974a8fc3e3.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38908788-82a3618e-42f4-11e8-8efd-3984162b4436.png)
![default](https://user-images.githubusercontent.com/37962734/38908816-99bcb24e-42f4-11e8-9b43-df8db6c82dc1.png)
![default](https://user-images.githubusercontent.com/37962734/38908857-b7cf8108-42f4-11e8-95d8-ce740fe560a5.png)

**Comment by GoodSake** [comment]
3.7.5与常无异！

**Comment by abigbone** [comment]
看了老版本延迟神马的都比较稳定~~

**Comment by AnyWAT** [comment]
😱转：源新闻我看了，不过我个人觉得一点都不意外。对于中国用户而言，影响也不大，无非就是以后不能用GAE方式来翻墙了。 https://twitter.com/DonEvansWm/status/986773801697357824

**Comment by xxxdd360noscope** [comment]
3.8.5运行正常但是无法翻墙

**Comment by AnyWAT** [comment]
IP延时及连接池的锅🤣
