### ISSUE TITLE
win8.1总是提示：GAEProxy 状态信息 你可以尝试 开启IPv6 或 使用X-Tunnel。

### ISSUE THREAD

**Issue by ivaniweb** [XX-net/XX-Net#10480]
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ivaniweb** [comment]
C:\Windows\system32>netsh int ipv6 show teredo state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified


C:\Windows\system32>

**Comment by ivaniweb** [comment]
系统装完后，用管理员CMD，操作如下
netsh interface ipv6 set teredo enterpriseclient teredo.remlab.net 30 default
ping -6 [2001:470:1:18::125]
netsh int ipv6 show teredo state

**Comment by ivaniweb** [comment]
C:\Windows\system32>ping teredo.remlab.net

正在 Ping teredo.remlab.net [83.170.6.76] 具有 32 字节的数据:
来自 83.170.6.76 的回复: 字节=32 时间=236ms TTL=43
来自 83.170.6.76 的回复: 字节=32 时间=236ms TTL=43
来自 83.170.6.76 的回复: 字节=32 时间=236ms TTL=43
来自 83.170.6.76 的回复: 字节=32 时间=236ms TTL=43

83.170.6.76 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 236ms，最长 = 236ms，平均 = 236ms

**Comment by SeaHOH** [comment]
#10328 用这个检查看看

**Comment by UxxUnet** [comment]
teredo.remlab.net 一直用不了，现在我这里用win10.ipv6.microsoft.com 是可以的

**Comment by SeaHOH** [comment]
@ivaniweb 谢谢报错，马上修改。

**Comment by ivaniweb** [comment]
还是没解决

**Comment by SeaHOH** [comment]
@ivaniweb 这个脚本主要是检测筛选，设置是顺带。

看到里面写的注意事项了吗？有说明不成功时该怎么处理。
