### ISSUE TITLE
无法访问日本网站

### ISSUE THREAD

**Issue by AbelAI** [XX-net/XX-Net#10483]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3393.4 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:1 ipv6:500
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:57 h2:1
scan-ip-thread-num: 200
ip-quality: 559
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false
其他外网都可以访问，包括YouTube视频也可以打开，就是打不开日本网站，日亚都打不开，什么情况啊！

**Comment by SeaHOH** [comment]
所有？？你用的什么工具来控制流量，系统代理、pac、智能代理、浏览器扩展？

**Comment by AbelAI** [comment]
用了浏览器扩展，看YouTube看视频都不卡啊，怎么日亚上不去，还有个别.jp打不开

**Comment by SeaHOH** [comment]
检查规则并修正，或者直接用智能代理端口。

**Comment by AbelAI** [comment]
切换智能代理已解决，谢谢
