### ISSUE TITLE
2018.4.17 Ipv6 数量急剧减少

### ISSUE THREAD

**Issue by heracleshebe147** [XX-net/XX-Net#10485]
如题所示，上午IPV6还有300，下午突然就没有了，折腾半天后，重启后只有10-15了，究竟是怎么回事？

* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by lon91ong** [comment]
@SeaHOH 你的GotoX的功能和XX-net的类似吗？能替代吗？资源消耗是否更少？路由器能玩得转吗？

**Comment by heracleshebe147** [comment]
搜到了4个，有gea_proxy，local内有三个关于front的，都要删掉吗？

**Comment by SeaHOH** [comment]
@lon91ong  路由器可以装，但是是 Python 3，可能需要自己动手编译 https://github.com/SeaHOH/GotoX/issues/58

@heracleshebe147 不是 code 文件夹，是 data 文件夹。

**Comment by lon91ong** [comment]
@SeaHOH 编译环境的搭建太…… 可不可以分享几个常见的（折腾人数较多的）路由器平台的现成安装包

**Comment by SeaHOH** [comment]
上面折腾的不是安装包，而是编译 OpenWrt 系统。
主要是固件的 Python 3 支持问题。

**Comment by heracleshebe147** [comment]
@SeaHOH  只恢复到150左右

**Comment by SeaHOH** [comment]
150 还算能用，过段时间不好用了继续删。。。

**Comment by heracleshebe147** [comment]
过200了
