### ISSUE TITLE
连接尚未建立

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#10482]
目前版本3.11.7，连接方式为全局通过GAEProxy代理，请大神看看啥原因
![image](https://user-images.githubusercontent.com/37856464/38845784-ac3a897e-422b-11e8-8595-59e509908709.png)
![image](https://user-images.githubusercontent.com/37856464/38845835-ed266ac0-422b-11e8-94d7-78e596964362.png)

**Comment by cnscorpions** [comment]
同样的问题，IPv6 fails 求解

**Comment by maolidi** [comment]
试试把适配器的ipv6禁用

**Comment by cnscorpions** [comment]
过一段事件自己脸上了，还是谢谢了



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality1&>
Sent
with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality1&>

**Comment by Whiteonename** [comment]
可能是之前填写的teredo服务器不可用了 ，看看是不是ping不通了，修改teredo服务器命令
`netsh interface teredo set state server=www.xxxxx.com`
