### ISSUE TITLE
推荐一款国外VPN，注册就送10G/month, 速度杠杠的，

### ISSUE THREAD

**Issue by cnscorpions** [XX-net/XX-Net#10499]
现在感觉GAE的延迟有的高，推荐一款国外vpn ---> windscribe
ps: 请通过[此链接](https://windscribe.com/?friend=bnalwov4)，帮小弟赚点流量

**Comment by GoodSake** [comment]
又来骗我注册！

**Comment by cnscorpions** [comment]
@GoodSake hey dude, 你还是注册了，哈哈。今天找到的还行

**Comment by SasamiMasakiJurai** [comment]
@xxnet 

广告

**Comment by elo5** [comment]
我用过，还行

**Comment by hahsfb** [comment]
@cnscorpions @elo5 速度怎么样？

**Comment by elo5** [comment]
@haohsfb 没有比较过，就是有时xx抽风用来看看推ins这些，反正比tor快，多备几个，一个抽风了还可以换另一个用

**Comment by elo5** [comment]
当然了，用谷歌搜东西还是没问题的，看youtube就没试过了，毕竟流量就那么多，舍不得呢

**Comment by hallochina** [comment]
安卓苹果windows全平台支持，在中国，最好用的付费VPN推荐 https://vpnchina.zdhweb.com
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。
