### ISSUE TITLE
未能打开隧道适配器，怎么解决？

### ISSUE THREAD

**Issue by dragonwang2016** [XX-net/XX-Net#10493]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by 308901951** [comment]
计算机管理----------------服务和应用程序--------------服务------IP helper---启动类型为“自动”并”启动”

**Comment by AnyWAT** [comment]
先禁用再启用网络
https://github.com/XX-net/XX-Net/issues/10515#issuecomment-383109033

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引
