### ISSUE TITLE
Google 关闭域前置，影响反审查工具

### ISSUE THREAD

**Issue by XuJ0e** [XX-net/XX-Net#10496]
Google 的云计算平台 App Engine（GAE） 正在关闭域前置(Domain fronting)功能，导致利用 Google 域名绕过国家级审查的反审查工具失效。域前置是一种隐藏连接真实端点来规避审查的技术。此技术的原理为在不同通信层使用不同的域名。在明文的 DNS 请求和 TLS 服务器名称指示中使用无害的域名来初始化连接、公布给审查者，而实际要连接的被封锁域名仅在创建加密的 HTTPS 连接后发出，使其不以明文暴露给网络审查者。比如在没有屏蔽 Google 域名的国家，反审查工具可以通过 Google 的域名 appspot.com 转发流量。Tor 开发者在 4 月 13 日率先报告了 GAE 的域前置停止工作。域前置失效干扰到了 Signal、GreatFire.org 和 Psiphon VPN 等反审查服务。Google 的代表对此表示，域前置从来不是 Google 支持的一项特性，它能工作是因为软件栈的古怪行为，Google 在不断更新网络，作为计划中的软件更新的一部分，域前置不再能工作。Google 没有计划将其作为一项功能提供。

**Comment by whimian** [comment]
那以后都不能使用了吗

**Comment by GoodSake** [comment]
快帮我看看，我是不是见鬼了！chrome 66.0.3359.117 64bit, gae打开google正常！

![snap1](https://user-images.githubusercontent.com/19205130/38972508-8d3f3cd2-43d3-11e8-8690-8747742821bd.png)

**Comment by yongqingxie** [comment]
看起来要搞个大新闻

**Comment by Anway2** [comment]
很奇怪，同一网络下，PC翻不过去，但手机用xndroid却可以。

**Comment by xxnet** [comment]
对GAE_Proxy没有影响，墙内是teredo的方式，不需要假冒sni。

**Comment by Just2co** [comment]
受影响的只是通过SNI servername方式连接GAE翻墙上网的，xx-net是通过teredo隧道连接IPV6的GAE上网的，同样没有受影响的还有QUIC方式，仍然高速可用。
