### ISSUE TITLE
xxnet 3.11.9 不定时 IPv6 状态	Fail！

### ISSUE THREAD

**Issue by hongkonghot** [XX-net/XX-Net#10498]
升级到 xxnet 3.11.9后，不定时出现IPv6 状态 Fail！刚起动软件时，能连上，过一会就变成IPv6 状态 Fail，netsh int teredo show state 如下：Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

**Comment by AnyWAT** [comment]
IP 变成 蛋蛋了 #10516

**Comment by hongkonghot** [comment]
@AnyWAT 感谢楼上，这样设置后真的好多了！
