### ISSUE TITLE
更新了chrome 66.0.3359.117后无法登陆google首页了

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#10494]
https://www.google.com，就是这个页面，显示未登陆，登陆邮箱、输入密码后提示：

> 糟糕！您的浏览器似乎禁用了 Cookie。请务必启用 Cookie 或尝试打开一个新的浏览器窗口
可是我cookie那边一直是Allow sites to save and read cookie data (recommended)。
怀疑是chrome版本的问题，准备降级观察一下。

**Comment by nly4lov** [comment]
shit, 降级回65.0.3325.181也无法登陆了。

**Comment by nly4lov** [comment]
@AnyWAT 我还不知道到底是什么情况，看到有的网友说滚回3117可以解决登陆，我就滚回去了，然后登陆了google首页，youtube又上不去了。然后再回到3119，google没掉下来，youtube也上去了哈哈

**Comment by AnyWAT** [comment]
来回滚不失为一种（临时）解决之道👍

**Comment by nly4lov** [comment]
@AnyWAT 看不懂那个![qq 20170916110138](https://user-images.githubusercontent.com/11325411/38972453-28677568-43d3-11e8-9f36-7db4ad1e8e11.gif)

**Comment by yongqingxie** [comment]
试下这个 我刚刚也升级了chrome 并没有任何问题
https://www.google.com/ncr
