### ISSUE TITLE
无法在各种网站上登录，可能是加载不了cookie的原因

### ISSUE THREAD

**Issue by GeTMH** [XX-net/XX-Net#10492]
Apr 18 19:58:59.129 - [INFO] GAE t:362 s:35 GET https://stats.g.doubleclick.net/r/collect?t=dc&aip=1&_r=3&v=1&_v=j67&tid=UA-3755767-19&cid=1826604009.1523888067&jid=1343464694&gjid=1678088762&_gid=418633010.1523888138&_u=SCCCgEADQ~&z=310600034 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400a:6::f,0:h1_req,0:h1_req_sended,359:response_begin,0:h1_get_head,1:get_response,0:h1_finish[SP:1132],:1 
Apr 18 19:58:59.160 - [INFO] GAE t:386 s:0 GET https://www.googletagmanager.com/a?id=GTM-TLDGMQW&cv=10&v=t&n=ga&g=2832&p=gtm&l=2830&sr=0.050000&ps=0.022070632576075555&cb=861854925 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4009:35::b,0:h1_req,0:h1_req_sended,386:response_begin,0:h1_get_head,0:h1_finish[SP:803],0:get_response,:0 
Apr 18 19:58:59.544 - [DEBUG] create_ssl update ip:2607:f8b0:4006:33::9 time:773 h2:0 sni:revolution.pie.movie.ml, host:xx-net001-140309.appspot.com 
Apr 18 19:58:59.691 - [INFO] scan_ip add ip:2402:800:6150:7::12 time:615 h2:0 
Apr 18 19:58:59.691 - [INFO] remove_slowest_ip:2a00:1450:4003:11::6 handshake_time:467, fails:1 
Apr 18 19:59:02.048 - [DEBUG] create_ssl update ip:2a00:1450:4001:65::8 time:2903 h2:0 sni:brilliantcold.net, host:dsetng10.appspot.com 
Apr 18 19:59:02.129 - [DEBUG] report_connect_fail:2800:e0:c68::10 
Apr 18 19:59:02.129 - [DEBUG] connect 2800:e0:c68::10 fail:error("conn fail, sni:error-history-sport.com, top:xxnet-xtkong6.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:02.148 - [DEBUG] report_connect_fail:2a00:1450:4007:2d::9 
Apr 18 19:59:02.148 - [DEBUG] connect 2a00:1450:4007:2d::9 fail:error("conn fail, sni:potbaby.ml, top:liy-pay-153300.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:02.696 - [DEBUG] report_connect_fail:2607:f8b0:401e:27::7 
Apr 18 19:59:02.696 - [DEBUG] connect 2607:f8b0:401e:27::7 fail:error("conn fail, sni:pitch-song-lip.com, top:chrome---1234.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:03.682 - [DEBUG] GAE GET /poll?r=0.3973560760242789&u=2258587330&s=7&k=pI5eKRwkwk6fhpnr&t=0&i=30&r=0.4730421464562604 from:127.0.0.1:60179 
Apr 18 19:59:03.898 - [DEBUG] report_connect_fail:2a00:1450:4002:b::8 
Apr 18 19:59:03.898 - [DEBUG] connect 2a00:1450:4002:b::8 fail:error("conn fail, sni:drunkschoolsad.ml, top:asxx-1.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:04.431 - [DEBUG] report_connect_fail:2001:7f8:49:1::c 
Apr 18 19:59:04.431 - [DEBUG] connect 2001:7f8:49:1::c fail:error("conn fail, sni:song-refrigerator-tension.com, top:xxnet-2017163.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:04.465 - [DEBUG] create_ssl update ip:2a00:1450:400e:4c::20 time:5335 h2:0 sni:writing-bet.us, host:tony0415978520.appspot.com 
Apr 18 19:59:05.495 - [DEBUG] GAE POST /user/login.php from:127.0.0.1:60186 
Apr 18 19:59:05.839 - [INFO] scan_ip add ip:2c0f:fc89:70::f time:555 h2:0 
Apr 18 19:59:05.839 - [INFO] remove_slowest_ip:2001:7f8:49:1::c handshake_time:469, fails:1 
Apr 18 19:59:06.086 - [INFO] GAE t:591 s:20 POST https://engradepro.com/user/login.php 0:start_request,0:get_task(1),0:get_worker(0):2607:f8b0:400a:6::f,0:h1_req,0:h1_req_sended,591:response_begin,0:h1_get_head,0:h1_finish[SP:934],0:get_response,:0 
Apr 18 19:59:06.101 - [DEBUG] GAE GET /student/?rand=280600&first=1&login=1 from:127.0.0.1:60187 
Apr 18 19:59:06.155 - [DEBUG] report_connect_fail:2a00:1450:400d:8::12 
Apr 18 19:59:06.155 - [DEBUG] connect 2a00:1450:400d:8::12 fail:error("conn fail, sni:redwelcomeabroad.ml, top: e:timeout('timed out',)",) 
Apr 18 19:59:07.136 - [INFO] GAE t:1034 s:232 GET http://www.engradepro.com/student/?rand=280600&first=1&login=1 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4009:35::b,0:h1_req,0:h1_req_sended,1033:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:457],:0 
Apr 18 19:59:07.140 - [DEBUG] GAE GET /student/?rand=280600&first=1&login=1 from:127.0.0.1:60151 
Apr 18 19:59:07.920 - [INFO] gae_handler send to browser return error(10053, '') 'https://www.engradepro.com/student/?rand=280600&first=1&login=1', len:15462, sended:4633 
Apr 18 19:59:07.939 - [DEBUG] GAE GET /student/?stuid=T161920492016 from:127.0.0.1:60196 
Apr 18 19:59:08.420 - [DEBUG] GAE POST /jserrors/1/6ce79480f5?a=35870407&v=1071.385e752&to=Y1wGYUdTVkRWW0UKVloWMUdcHUtDQlxUDU0bUApRUEoWR19I&rst=14076&ref=https://www.engradepro.com/student/&xhr=%5B%7B%22params%22:%7B%22method%22:%22POST%22,%22host%22:%22bam.nr-data.net:443%22,%22pathname%22:%22/events/1/6ce79480f5%22,%22status%22:200%7D,%22metrics%22:%7B%22count%22:1,%22txSize%22:%7B%22t%22:190%7D,%22duration%22:%7B%22t%22:289%7D,%22rxSize%22:%7B%22t%22:24%7D,%22cbTime%22:%7B%22t%22:1%7D,%22time%22:%7B%22t%22:3143%7D%7D%7D%5D from:127.0.0.1:60149 
Apr 18 19:59:08.458 - [INFO] GAE t:519 s:11669 GET https://www.engradepro.com/student/?stuid=T161920492016 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4009:35::b,0:h1_req,0:h1_req_sended,401:response_begin,0:h1_get_head,0:get_response,115:h1_finish[SP:23355],:0 
Apr 18 19:59:08.589 - [DEBUG] GAE GET /collect?v=1&_v=j67&a=706456798&t=pageview&_s=1&dl=https%3A%2F%2Fwww.engradepro.com%2Fstudent%2F%3Fstuid%3DT161920492016&ul=zh-cn&de=utf-8&dt=McGraw-Hill%20Education&sd=24-bit&sr=1600x900&vp=1600x753&je=1&_utma=221720652.1826604009.1523888067.1524048493.1524052730.6&_utmz=221720652.1523888067.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)&_utmht=1524052748593&_u=SACCAEAB~&jid=&gjid=&cid=1826604009.1523888067&uid=&tid=UA-3755767-7&_gid=418633010.1523888138&cd6=%2Fstudent%2Findex.php&z=1871861401 from:127.0.0.1:60158 
Apr 18 19:59:08.658 - [DEBUG] GAE GET /1/6ce79480f5?a=35870407&v=1071.385e752&to=Y1wGYUdTVkRWW0UKVloWMUdcHUtDQlxUDU0bUApRUEoWR19I&rst=3158&ref=https://www.engradepro.com/student/&ap=47&be=2976&fe=3128&dc=3103&af=err,xhr,stn,ins,spa&perf=%7B%22timing%22:%7B%22of%22:1524052745482,%22n%22:0,%22f%22:2436,%22dn%22:2436,%22dne%22:2436,%22c%22:2436,%22ce%22:2436,%22rq%22:2454,%22rp%22:2867,%22rpe%22:3006,%22dl%22:2867,%22di%22:3101,%22ds%22:3103,%22de%22:3113,%22dc%22:3123,%22l%22:3127,%22le%22:3131%7D,%22navigation%22:%7B%7D%7D&at=TxsFFw9JRUo%3D&jsonp=NREUM.setToken from:127.0.0.1:60200 
Apr 18 19:59:08.705 - [INFO] GAE t:284 s:24 POST https://bam.nr-data.net/jserrors/1/6ce79480f5?a=35870407&v=1071.385e752&to=Y1wGYUdTVkRWW0UKVloWMUdcHUtDQlxUDU0bUApRUEoWR19I&rst=14076&ref=https://www.engradepro.com/student/&xhr=%5B%7B%22params%22:%7B%22method%22:%22POST%22,%22host%22:%22bam.nr-data.net:443%22,%22pathname%22:%22/events/1/6ce79480f5%22,%22status%22:200%7D,%22metrics%22:%7B%22count%22:1,%22txSize%22:%7B%22t%22:190%7D,%22duration%22:%7B%22t%22:289%7D,%22rxSize%22:%7B%22t%22:24%7D,%22cbTime%22:%7B%22t%22:1%7D,%22time%22:%7B%22t%22:3143%7D%7D%7D%5D 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400a:6::f,0:h1_req,0:h1_req_sended,284:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:564],:0 
Apr 18 19:59:08.721 - [DEBUG] GAE_Exception 600 'fetch gae fail' 
Apr 18 19:59:08.721 - [WARNING] gae_exception:'600:fetch gae fail' https://wp.mail.qq.com/poll?r=0.3973560760242789&u=2258587330&s=7&k=pI5eKRwkwk6fhpnr&t=0&i=30&r=0.4730421464562604 
Apr 18 19:59:08.790 - [INFO] scan_ip add ip:2800:3f0:4001:14::18 time:532 h2:0 
Apr 18 19:59:08.790 - [INFO] remove_slowest_ip:2a00:1450:400d:8::12 handshake_time:477, fails:1 
Apr 18 19:59:08.958 - [INFO] scan_ip add ip:2405:4800:100:24::f time:553 h2:0 
Apr 18 19:59:08.958 - [INFO] remove_slowest_ip:2a00:1450:4002:b::8 handshake_time:468, fails:1 
Apr 18 19:59:08.990 - [INFO] GAE t:332 s:57 GET https://bam.nr-data.net/1/6ce79480f5?a=35870407&v=1071.385e752&to=Y1wGYUdTVkRWW0UKVloWMUdcHUtDQlxUDU0bUApRUEoWR19I&rst=3158&ref=https://www.engradepro.com/student/&ap=47&be=2976&fe=3128&dc=3103&af=err,xhr,stn,ins,spa&perf=%7B%22timing%22:%7B%22of%22:1524052745482,%22n%22:0,%22f%22:2436,%22dn%22:2436,%22dne%22:2436,%22c%22:2436,%22ce%22:2436,%22rq%22:2454,%22rp%22:2867,%22rpe%22:3006,%22dl%22:2867,%22di%22:3101,%22ds%22:3103,%22de%22:3113,%22dc%22:3123,%22l%22:3127,%22le%22:3131%7D,%22navigation%22:%7B%7D%7D&at=TxsFFw9JRUo%3D&jsonp=NREUM.setToken 0:start_request,0:get_task(0),0:get_worker(0):2620:11a:a01d::14,0:h1_req,0:h1_req_sended,332:response_begin,0:h1_get_head,0:h1_finish[SP:454],0:get_response,:0 
Apr 18 19:59:09.105 - [INFO] GAE t:516 s:35 GET https://www.google-analytics.com/collect?v=1&_v=j67&a=706456798&t=pageview&_s=1&dl=https%3A%2F%2Fwww.engradepro.com%2Fstudent%2F%3Fstuid%3DT161920492016&ul=zh-cn&de=utf-8&dt=McGraw-Hill%20Education&sd=24-bit&sr=1600x900&vp=1600x753&je=1&_utma=221720652.1826604009.1523888067.1524048493.1524052730.6&_utmz=221720652.1523888067.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)&_utmht=1524052748593&_u=SACCAEAB~&jid=&gjid=&cid=1826604009.1523888067&uid=&tid=UA-3755767-7&_gid=418633010.1523888138&cd6=%2Fstudent%2Findex.php&z=1871861401 0:start_request,0:get_task(0),0:get_worker(0):2607:f798:1e:400::10,0:h1_req,0:h1_req_sended,516:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:707],:0 
Apr 18 19:59:09.174 - [DEBUG] report_connect_fail:2a02:8400:0:117::e 
Apr 18 19:59:09.174 - [DEBUG] connect 2a02:8400:0:117::e fail:error("conn fail, sni:sky-burn.us, top:mickweb-1.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:09.241 - [INFO] scan_ip add ip:2001:13d0:0:d::10 time:767 h2:0 
Apr 18 19:59:09.243 - [INFO] remove_slowest_ip:2a02:8400:0:117::e handshake_time:469, fails:1 
Apr 18 19:59:09.290 - [WARNING] 2607:f8b0:4000:4c::8 h1_request:Exception('time out',) inactive_time:10 task.timeout:5 
Apr 18 19:59:09.290 - [WARNING] 2607:f8b0:4000:4c::8 trace: 0:connect, 763:init, 4332:request, 548:Res, 8384:request, 599:Res, 1900:request, 316:Res, 871:request, 493:Res, 1486:request, 352:Res, 684:request, 601:Res, 516:request, 401:Res, 1093:request, 315:Res, 1476:request, 309:Res, 4605:request,:5608, processed:9, transfered:28011, sni:healthpanicsubstance.com 
Apr 18 19:59:09.290 - [DEBUG] POST None/_gh/ response_fail:retry timeout:5 
Apr 18 19:59:09.290 - [DEBUG] 2607:f8b0:4000:4c::8 worker close:down fail 
Apr 18 19:59:09.543 - [DEBUG] GAE GET /pages/scripts/0027/3530.js?423347 from:127.0.0.1:60157 
Apr 18 19:59:09.691 - [INFO] scan_ip add ip:2607:f8b0:4000:4b::9 time:300 h2:0 
Apr 18 19:59:09.691 - [INFO] remove_slowest_ip:2607:f8b0:401e:27::7 handshake_time:468, fails:1 
Apr 18 19:59:09.975 - [INFO] GAE t:431 s:0 GET https://dnn506yrbagrg.cloudfront.net/pages/scripts/0027/3530.js?423347 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400a:6::f,0:h1_req,0:h1_req_sended,431:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:738],:0 
Apr 18 19:59:10.560 - [DEBUG] GAE GET /collect?v=1&_v=j67&a=706456798&t=pageview&_s=1&dl=https%3A%2F%2Fwww.engradepro.com%2Fstudent%2F%3Fstuid%3DT161920492016&ul=zh-cn&de=utf-8&dt=McGraw-Hill%20Education&sd=24-bit&sr=1600x900&vp=1600x753&je=1&_utma=221720652.1826604009.1523888067.1524048493.1524052730.6&_utmz=221720652.1523888067.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)&_utmht=1524052750567&_u=SCCCgEADQ~&jid=&gjid=&cid=1826604009.1523888067&uid=&tid=UA-3755767-19&_gid=418633010.1523888138&cd6=%2Fstudent%2Findex.php>m=G465PQR82&z=675464871 from:127.0.0.1:60158 
Apr 18 19:59:10.944 - [INFO] GAE t:384 s:35 GET https://www.google-analytics.com/collect?v=1&_v=j67&a=706456798&t=pageview&_s=1&dl=https%3A%2F%2Fwww.engradepro.com%2Fstudent%2F%3Fstuid%3DT161920492016&ul=zh-cn&de=utf-8&dt=McGraw-Hill%20Education&sd=24-bit&sr=1600x900&vp=1600x753&je=1&_utma=221720652.1826604009.1523888067.1524048493.1524052730.6&_utmz=221720652.1523888067.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)&_utmht=1524052750567&_u=SCCCgEADQ~&jid=&gjid=&cid=1826604009.1523888067&uid=&tid=UA-3755767-19&_gid=418633010.1523888138&cd6=%2Fstudent%2Findex.php>m=G465PQR82&z=675464871 0:start_request,0:get_task(1),0:get_worker(0):2607:f8b0:400a:6::f,0:h1_req,0:h1_req_sended,384:response_begin,0:h1_get_head,0:h1_finish[SP:937],0:get_response,:0 
Apr 18 19:59:11.107 - [DEBUG] report_connect_fail:2607:f798:14:41::e 
Apr 18 19:59:11.107 - [DEBUG] connect 2607:f798:14:41::e fail:error("conn fail, sni:mistakeclothes.us, top:gaedonate04.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:11.370 - [INFO] scan_ip add ip:2001:4600:9:307::12 time:593 h2:0 
Apr 18 19:59:11.370 - [INFO] remove_slowest_ip:2607:f798:14:41::e handshake_time:478, fails:1 
Apr 18 19:59:11.461 - [DEBUG] report_connect_fail:2a02:a000:1:202::c 
Apr 18 19:59:11.461 - [DEBUG] connect 2a02:a000:1:202::c fail:error("conn fail, sni:invitekiss.ml, top:strav317.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:11.624 - [DEBUG] report_connect_fail:2607:f8b0:4002:37::7 
Apr 18 19:59:11.624 - [DEBUG] connect 2607:f8b0:4002:37::7 fail:error("conn fail, sni:milk.district.combine.org, top:xxnet-99903.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:11.924 - [DEBUG] create_ssl update ip:2607:f8b0:4000:4b::9 time:732 h2:0 sni:purple-representative-mall.net, host:bonnyshenvpn-005.appspot.com 
Apr 18 19:59:12.061 - [INFO] scan_ip add ip:2405:4800:100:16::e time:707 h2:0 
Apr 18 19:59:12.061 - [INFO] remove_slowest_ip:2607:f8b0:4002:37::7 handshake_time:480, fails:1 
Apr 18 19:59:12.139 - [DEBUG] report_connect_fail:2a00:1450:4003:12::16 
Apr 18 19:59:12.139 - [DEBUG] connect 2a00:1450:4003:12::16 fail:error("conn fail, sni:spend-office.com, top:chrome--1234.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:12.393 - [INFO] scan_ip add ip:2620:11a:a015::18 time:284 h2:0 
Apr 18 19:59:12.393 - [INFO] remove_slowest_ip:2a00:1450:4003:12::16 handshake_time:480, fails:1 
Apr 18 19:59:12.547 - [DEBUG] GAE POST /events/1/6ce79480f5?a=35870407&v=1071.385e752&to=Y1wGYUdTVkRWW0UKVloWMUdcHUtDQlxUDU0bUApRUEoWR19I&rst=7058&ref=https://www.engradepro.com/student/ from:127.0.0.1:60200 
Apr 18 19:59:12.663 - [DEBUG] report_connect_fail:2a00:1450:4005:a::c 
Apr 18 19:59:12.663 - [DEBUG] connect 2a00:1450:4005:a::c fail:error("conn fail, sni:owner.rough.employment.com, top:xxnet-idforxxnet-7.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:12.880 - [INFO] GAE t:333 s:24 POST https://bam.nr-data.net/events/1/6ce79480f5?a=35870407&v=1071.385e752&to=Y1wGYUdTVkRWW0UKVloWMUdcHUtDQlxUDU0bUApRUEoWR19I&rst=7058&ref=https://www.engradepro.com/student/ 0:start_request,0:get_task(1),0:get_worker(0):2607:f8b0:4000:4b::9,0:h1_req,0:h1_req_sended,333:response_begin,0:h1_get_head,0:h1_finish[SP:483],0:get_response,:0 
Apr 18 19:59:13.164 - [DEBUG] report_connect_fail:2607:f8b0:4007:2e::9 
Apr 18 19:59:13.164 - [DEBUG] connect 2607:f8b0:4007:2e::9 fail:error("conn fail, sni:phase-career.org, top: e:timeout('timed out',)",) 
Apr 18 19:59:13.180 - [DEBUG] report_connect_fail:2a00:1450:4001:50::c 
Apr 18 19:59:13.180 - [DEBUG] connect 2a00:1450:4001:50::c fail:error("conn fail, sni:wifefarmer.net, top:xxnet-maxuyang2.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:13.564 - [INFO] scan_ip add ip:2a00:1450:4011:4b::1c time:2540 h2:0 
Apr 18 19:59:13.564 - [INFO] remove_slowest_ip:2a00:1450:4011:4b::1c handshake_time:2540, fails:0 
Apr 18 19:59:13.695 - [DEBUG] report_connect_fail:2001:850:3110:300::d 
Apr 18 19:59:13.695 - [DEBUG] connect 2001:850:3110:300::d fail:error("conn fail, sni:mortgage.delay.com, top:perfer4-147105.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:14.212 - [DEBUG] report_connect_fail:2a00:1450:400d::11 
Apr 18 19:59:14.212 - [DEBUG] connect 2a00:1450:400d::11 fail:error("conn fail, sni:soil.kill.freedom.ml, top:w511655778.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:14.713 - [DEBUG] report_connect_fail:2a00:1450:400d:2::16 
Apr 18 19:59:14.713 - [DEBUG] connect 2a00:1450:400d:2::16 fail:error("conn fail, sni:winner-ask-duty.ml, top:zhoumeng10088.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:15.230 - [DEBUG] report_connect_fail:2a00:1450:401e:3e::b 
Apr 18 19:59:15.230 - [DEBUG] connect 2a00:1450:401e:3e::b fail:error("conn fail, sni:god.muscle.practice.ml, top:xxnet-1301.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:15.351 - [DEBUG] create_ssl update ip:2620:11a:a015::18 time:669 h2:0 sni:animalcopyland.net, host:my-project14-1332.appspot.com 
Apr 18 19:59:15.715 - [INFO] scan_ip add ip:2a00:1450:4001:57::7 time:786 h2:0 
Apr 18 19:59:15.730 - [INFO] remove_slowest_ip:2a02:a000:1:202::c handshake_time:478, fails:1 
Apr 18 19:59:15.852 - [DEBUG] GAE GET /api/toolbox/geturl.php?h=480DF03F8CE0F48821C5FB3BC7E063B2&v=8.7.0.1682&r=6991_sogou_pinyin_8.2.0.9257_6991 from:127.0.0.1:60230 
Apr 18 19:59:16.631 - [INFO] GAE t:779 s:0 GET http://config.pinyin.sogou.com/api/toolbox/geturl.php?h=480DF03F8CE0F48821C5FB3BC7E063B2&v=8.7.0.1682&r=6991_sogou_pinyin_8.2.0.9257_6991 0:start_request,0:get_task(3),0:get_worker(0):2620:11a:a015::18,0:h1_req,0:h1_req_sended,779:response_begin,0:h1_get_head,0:h1_finish[SP:355],0:get_response,:0 
Apr 18 19:59:16.815 - [INFO] scan_ip add ip:2607:f8b0:4002:28::13 time:414 h2:0 
Apr 18 19:59:16.815 - [INFO] remove_slowest_ip:2a00:1450:401e:3e::b handshake_time:476, fails:1 
Apr 18 19:59:17.900 - [INFO] scan_ip add ip:2404:6800:400c:7::7 time:501 h2:0 
Apr 18 19:59:17.916 - [INFO] remove_slowest_ip:2a00:1450:400d:2::16 handshake_time:476, fails:1 
Apr 18 19:59:17.947 - [DEBUG] report_connect_fail:2806:1020:cfff:6::10 
Apr 18 19:59:17.947 - [DEBUG] connect 2806:1020:cfff:6::10 fail:error("conn fail, sni:bus.quality.state.org, top:tony0469059164.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:18.132 - [DEBUG] report_connect_fail:2a00:1450:400d:9::14 
Apr 18 19:59:18.132 - [DEBUG] connect 2a00:1450:400d:9::14 fail:error("conn fail, sni:male.regret.procedure.net, top:xxnet-2589.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:18.485 - [DEBUG] report_connect_fail:2001:818:e4f2:1::c 
Apr 18 19:59:18.485 - [DEBUG] connect 2001:818:e4f2:1::c fail:error("conn fail, sni:candidategrand.net, top:ren-zhi-chu25.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:18.648 - [DEBUG] report_connect_fail:2a02:8400:0:108::13 
Apr 18 19:59:18.648 - [DEBUG] connect 2a02:8400:0:108::13 fail:error("conn fail, sni:north-push-market.com, top:xxnet-99909.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:19.170 - [DEBUG] report_connect_fail:2620:11a:a012:1::10 
Apr 18 19:59:19.170 - [DEBUG] connect 2620:11a:a012:1::10 fail:error("conn fail, sni:sock.designer.ml, top:xxnet--1265.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:20.187 - [DEBUG] report_connect_fail:2a00:1450:4003:11::11 
Apr 18 19:59:20.187 - [DEBUG] connect 2a00:1450:4003:11::11 fail:error("conn fail, sni:pride.shame.org, top: e:timeout('timed out',)",) 
Apr 18 19:59:20.203 - [DEBUG] report_connect_fail:2a00:1450:400d:d::7 
Apr 18 19:59:20.203 - [DEBUG] connect 2a00:1450:400d:d::7 fail:error("conn fail, sni:hour-character-iron.org, top:app123456-149811.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:20.420 - [INFO] scan_ip add ip:2a00:1450:4011:31::13 time:1935 h2:0 
Apr 18 19:59:20.420 - [INFO] remove_slowest_ip:2a00:1450:4011:31::13 handshake_time:1935, fails:0 
Apr 18 19:59:20.557 - [INFO] scan_ip add ip:2607:f8b0:4000:a::15 time:322 h2:0 
Apr 18 19:59:20.557 - [INFO] remove_slowest_ip:2620:11a:a012:1::10 handshake_time:486, fails:1 
Apr 18 19:59:20.673 - [INFO] scan_ip add ip:2001:12e0:803:5::1f time:585 h2:0 
Apr 18 19:59:20.673 - [INFO] remove_slowest_ip:2a02:8400:0:108::13 handshake_time:485, fails:1 
Apr 18 19:59:20.874 - [DEBUG] report_connect_fail:2001:4e8:0:b03e::13 
Apr 18 19:59:20.874 - [DEBUG] connect 2001:4e8:0:b03e::13 fail:error("conn fail, sni:closet.benefit.part.org, top:xxnet99902.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:21.221 - [DEBUG] report_connect_fail:2001:918:ffaa:8::e 
Apr 18 19:59:21.221 - [DEBUG] connect 2001:918:ffaa:8::e fail:error("conn fail, sni:skin.tap.credit.com, top:xxnet-17101403.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:21.374 - [DEBUG] report_connect_fail:2a00:1450:400d:7::11 
Apr 18 19:59:21.374 - [DEBUG] connect 2a00:1450:400d:7::11 fail:error("conn fail, sni:paintingmachineappearance.us, top:xxnet-143610.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:21.389 - [INFO] scan_ip add ip:2404:6800:4007:3::9 time:700 h2:0 
Apr 18 19:59:21.389 - [INFO] remove_slowest_ip:2a00:1450:400d:7::11 handshake_time:489, fails:1 
Apr 18 19:59:21.737 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11 
Apr 18 19:59:21.737 - [DEBUG] report_connect_fail:2a00:1450:4003:f::10 
Apr 18 19:59:21.737 - [DEBUG] connect 2a00:1450:4003:f::10 fail:error("conn fail, sni:dealthemehunt.ml, top:xxnet-102.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:22.253 - [DEBUG] report_connect_fail IPv6 continue_fail_count:12 
Apr 18 19:59:22.253 - [DEBUG] report_connect_fail:2a00:1450:4003:15::9 
Apr 18 19:59:22.253 - [DEBUG] connect 2a00:1450:4003:15::9 fail:error("conn fail, sni:dishdatabasediet.com, top:unink88.appspot.com e:timeout('timed out',)",) 
Apr 18 19:59:23.876 - [DEBUG] GAE_Exception 600 'fetch gae fail' 
Apr 18 19:59:23.876 - [WARNING] gae_exception:'600:fetch gae fail' https://wp.mail.qq.com/poll?r=0.9471506014022164&u=2258587330&s=7&k=pI5eKRwkwk6fhpnr&t=0&i=30&r=0.18842579576980878 
Apr 18 19:59:23.876 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://wp.mail.qq.com/poll?r=0.9471506014022164&u=2258587330&s=7&k=pI5eKRwkwk6fhpnr&t=0&i=30&r=0.18842579576980878gae_exception:'600:fetch gae fail' https://wp.mail.qq.com/poll?
关掉了xx就可以登录了，求帮助

**Comment by asmosn** [comment]
滚回3117

**Comment by nly4lov** [comment]
@asmosn 滚回3117谷歌可以登陆，油管又登陆不了了

**Comment by AnyWAT** [comment]
貌似IP延时大、连接池小的代理速度低之锅😜
https://github.com/XX-net/XX-Net/issues/10515#issuecomment-383109033

**Comment by SeaHOH** [comment]
不要全局代理，国内请直连，比如 pac、智能代理。
