### ISSUE TITLE
我个人期望的理想路由器及其他

### ISSUE THREAD

**Issue by SasamiMasakiJurai** [XX-net/XX-Net#10501]
稍微谈谈吧

目前我个人使用的是x86软路由

原先用的是华硕ac68u

这里稍微展开说下ac68u及其梅林固件问题

——————————————————

华硕ac68u作为前几年热门款路由主要卖点在于性能足够和可以刷官方梅林

目前很多人喜欢刷国内k站等第三方梅林

例如小宝固件等等

个人十分反对

原因如下

1.国内第三方固件有后门
2.虽然集成了一堆插件，但是更新等等都被绑在论坛更新上，自己是咩有自主权的
3.无法及时获得官方梅林的更新

因此

如果你需要梅林，推荐刷官方梅林

地址如下 https://asuswrt.lostrealm.ca/download

官方梅林的稳定性和安全性是由华硕背书的

而且华硕官方支持你刷官方梅林

并且现在华硕已经封掉了第三方梅林的刷机

所以你刷第三方梅林是很麻烦的

————————————————————

我之所以换掉华硕路由主要是为了全网翻墙的问题

华硕ac68u虽然性能足够

但是对于承担之后的宽带升级和全网翻墙来说

性能已经是有点缺陷了

并且由于有一定年代

系统功耗和发热已经十分可观了

而且现在wifi更新日新月异

华硕这类硬路由已经不能适应需求

因此

上软路由是为了让路由就做路由的事情

wifi有专门的ap负责

使得软硬分离

并且软路由完全可以扔到弱电箱内而不必担心wifi信号覆盖

——————————————

在解决了路由问题后

下面考虑的就是软路由系统和翻墙了

个人选择的路由系统是lede

和openwrt同属一家

软件支持广并且国内氛围研讨较好

初步使用下来非常不错

但是翻墙就较为麻烦

虽然xx-net在电脑运行没有问题

但是在路由中运行始终有点问题

因此

最终选择了走ssr这条路。。。。。。。

关于ssr各大论坛已经基本禁止讨论了

但是我们可以看得很多很多推广贴

尤其是以搬瓦工和vultr为首的各类一键安装推广贴

个人完全不推荐这些

原因如下

1.系统超售严重
2.ip端大量被封
3.一键安装后的码流特征明显，很容易被识别
4.一键安装容易植入后门

因此

个人建议如下

1.自己寻找云服务器，不要使用那些一键安装所推荐的服务器，
2.在尝试自己搭建ssr之前，可以用亚马逊的aws练手，1美元可以用一年，每月15g流量，一般来说足够用了，如果一年内都玩不溜，个人感觉还是放弃吧。。。。。。。
3.不要贪图便宜，便宜没好货这句话还是有道理的，搬瓦工和vultr这类2.5美刀一个月的还是放弃的好，一般来说，一个月5美刀是最低标准，如果加上线路优化等等 7.5美刀至10美刀是至少的
4.不要轻易相信网上合租那些，线路流量控制完全可以让你抓狂的。真要合租还是找周边认识的人吧
5.有空自己可以尝试学习下编译，ssr搭建真研究好了，还是不复杂的，多多谷歌下可以发现好些教程的
6.最后的最后，不要轻易使用一键安装之类，因为你永远不知道对方究竟捆绑了什么东西进去

以上，欢迎交流

**Comment by HuangJiayong** [comment]
官方梅林固件也不能刷了
