### ISSUE TITLE
您的AppID流量已用完，请部署更多AppID。

### ISSUE THREAD

**Issue by wattwei** [XX-net/XX-Net#10503]
部署了多次。部署完，没几个小时流量就被别人用玩了。有没有限制他人使用本appid的方法？有issue提到了这个问题，但是没有看到切实可行的方法。所以再提一次

**Comment by SeaHOH** [comment]
为什么别人会用你的？

**Comment by wattwei** [comment]
谁tm知道。部署完了，应该就自己知道。短短几个小时，怎么就泄露了。id也尽可能复杂了

**Comment by SeaHOH** [comment]
我觉得是你自己用了，是否全局代理？检查本机 GAE 日志，登录查看服务端日志。
https://console.cloud.google.com/logs?project=你的ID

**Comment by wattwei** [comment]
没有用全局代理。查了下，主要是xx-net，和telegram用的，明天有流量了再跟踪下，谢谢啊

**Comment by caofengzi** [comment]
部署幾個appid？正常部署12個每天12g流量還不夠用？

**Comment by 2378** [comment]
appid对网站来说是公开的 不知道会不会有人特意收集？

**Comment by xxnet** [comment]
​不要用GAE代理做高匿名要求的操作，GAE不适合。
普通网站，appid就相当于一个ip地址，没有什么用

**Comment by GoodSake** [comment]
前些天逛某论坛有人还说不要用appid打开baidu和360的首页，除非恶搞别人的id。。。终于理解了，哈哈哈！

看谁还敢露id，哈哈哈
