### ISSUE TITLE
之前将就了两个月X-Tunnel，已是最新版，怎么还这么不稳定呢，经常卡。

### ISSUE THREAD

**Issue by HuJohnny** [XX-net/XX-Net#10509]
<img width="561" alt="screen shot 2018-04-20 at 13 36 52" src="https://user-images.githubusercontent.com/19957085/39032462-324742a2-44a0-11e8-8b3b-12890cc63df8.png">
<img width="598" alt="screen shot 2018-04-20 at 13 36 58" src="https://user-images.githubusercontent.com/19957085/39032470-3dac4f0c-44a0-11e8-984b-37ea72706209.png">
<img width="732" alt="screen shot 2018-04-20 at 13 37 13" src="https://user-images.githubusercontent.com/19957085/39032471-3de28d2e-44a0-11e8-9b9c-e32c3d36bfb5.png">
<img width="552" alt="screen shot 2018-04-20 at 13 37 21" src="https://user-images.githubusercontent.com/19957085/39032472-3e14f07a-44a0-11e8-81a6-846353ea92a7.png">

**Comment by xxnet** [comment]
​GAE 的重传数，怎么有一个"年"?

**Comment by SeaHOH** [comment]
哈哈哈，翻译软件~

**Comment by SeaHOH** [comment]
等待新版发布
