### ISSUE TITLE
推特搜索功能缺失

### ISSUE THREAD

**Issue by nogi6purple** [XX-net/XX-Net#10502]
从一年前开始用XXnet就没办法实现推特的搜索功能，搜索只能成功出现用户，其他项都是不OK的。
其他网站使用都没什么问题
全网搜索跟我同样问题的有一个人，询问了一下他也用的XX net
因此想来问问大家是否遇到这种情况，如果遇到的又是如何解决的。

现在XXNET基本靠学校的ipv6撑住了

**Comment by AnyWAT** [comment]
唯有 1080 😜

**Comment by zhencaihao** [comment]
我是在去年国庆后发现这个情况的。“全局通过GAEProxy代理”才会这样，用x-tunnel或其他软件就没这个问题。

**Comment by SeaHOH** [comment]
twitter 自身策略
