### ISSUE TITLE
kubernetes里面deploy了3个xx-net，启动正常，但是一直没法检查IP

### ISSUE THREAD

**Issue by lenvon2012** [XX-net/XX-Net#10500]
提示：“你可以尝试 开启IPv6 或 使用X-Tunnel。”

XX-Net Status:

sys-platform: x86_64, Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-debian-8.10
os-system: Linux
os-version: #1 SMP Wed Mar 7 19:03:37 UTC 2018
os-release: 3.10.0-693.21.1.el7.x86_64
os-detail: Dist:debian; Version:8.10; ID:
architecture: 64bit,ELF
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.11.9
python-version: 2.7.9
openssl-version: 16.0.0 TLSv1_2 h2:npn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 80
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by GoodSake** [comment]
kubernetes是什么鬼，我老了，你们玩的对我来说都是新的。。。

what the hell is kubernetes? maybe I'm get old, you guys are all about new stuff...
（来自gs真人翻译）

**Comment by lenvon2012** [comment]
https://github.com/kubernetes/kubernetes 
@GoodSake

**Comment by xxnet** [comment]
​能否安装miredo?

**Comment by lenvon2012** [comment]
@xxnet docker image 里面是安装了的，单独跑起来是没问题的，只是在kubernetes跑就有这个问题了

**Comment by xxnet** [comment]
kubernetes 需要启动 ipv6

找到这个文章：
https://www.projectcalico.org/enable-ipv6-on-kubernetes-with-project-calico/
