### ISSUE TITLE
谷歌邮件Deletion notice for your Google Cloud Shell home directory

### ISSUE THREAD

**Issue by AnLvNing** [XX-net/XX-Net#10505]
前天收到的谷歌邮件，请问我该做什么呢
Hello Cloud Shell user,

It's been over 120 days since you opened Cloud Shell from the Google Cloud Platform console. In 7 days, your Cloud Shell home directory will be automatically scheduled for deletion.

To keep your Cloud Shell home directory and its data, just log in and open Cloud Shell.

OPEN CLOUD SHELL TO RETAIN OR BACKUP YOUR DATA
If you do nothing, you'll still have access to Cloud Shell: just start a new session and you're good to go. Your Cloud Platform projects won't be deleted and other services like App Engine or Compute Engine won't be affected.

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39028457-6722b450-4489-11e8-868d-ac470a14cf93.png)

**Comment by AnLvNing** [comment]
那我该做什么呢... @AnyWAT

**Comment by AnyWAT** [comment]
To keep your Cloud Shell home directory and its data, just log in and open Cloud Shell.

OPEN CLOUD SHELL TO RETAIN OR BACKUP YOUR DATA

**Comment by AnLvNing** [comment]
点那个链接就好了吗
