### ISSUE TITLE
呵呵哒

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#10507]
Property | Value
-- | --
IPv4 Status | OK
IPv6 Status | OK
IPv4 Number | 0
IPv6 Number | 501
XX-Net Status | working
IP Quality | 638
Connection Pool(Help) | new:0 h1:50 h2:0
Browser Proxy Setting | OK
CA status(Download) | OK
Number of IP-Scanning Threads(Settings) | 50

**Comment by j999yp** [comment]
请问是如何连上ipv6的？

**Comment by nly4lov** [comment]
@j999yp 当初左搞右搞，搞得头大，也没搞好。后来重装电脑（不是因为用不xx的原因），它自己就ok了。

**Comment by 2378** [comment]
高危地区的情况 是这样的

![default](https://user-images.githubusercontent.com/24506320/39030858-445ab964-4497-11e8-97ee-d605f5c44b7a.PNG)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39031606-d8b3e96a-449b-11e8-92ca-aef00ed66a96.png)
![image](https://user-images.githubusercontent.com/37962734/39031626-fd16b3a0-449b-11e8-856d-ca7c81e09ae3.png)

**Comment by nly4lov** [comment]
楼上牛人。
@2378 你那个样子估计是翻不出去的了。

**Comment by vert404** [comment]
![image](https://user-images.githubusercontent.com/32587285/39033927-f1f36ef4-44a6-11e8-879f-3b6cf0728e45.png)
3.10.4很好用

**Comment by 2378** [comment]
@nly4lov  xnet不是我的主力 换个姿势还是能翻的 :trollface:
![default](https://user-images.githubusercontent.com/24506320/39034723-f069feda-4466-11e8-9a00-782cc54ffe20.PNG)

**Comment by hahsfb** [comment]
@2378 这个是啥

**Comment by 2378** [comment]
ssr

**Comment by nly4lov** [comment]
@vert404 你能登陆youtube吗？

**Comment by AnyWAT** [comment]
😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313 或许你也能从人变成牛🤣
