### ISSUE TITLE
ipv6又不行了 有几天时间了

### ISSUE THREAD

**Issue by guxiwuruo** [XX-net/XX-Net#10504]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
最新版  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  看过

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  没有类似

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：
学校实验室网通的网

* 做过哪些尝试：
test-ipv6.com 不通过
disable_ipv6，enable_ipv6批处理也不行，

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 172.16.75.216:64883
外部 NAT 映射    : *************:64883
* 请贴出对应模块的状态页

* 请贴出相关的日志

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5 ipv4:0 ipv6:5
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by guxiwuruo** [comment]
不大熟悉这个软件  还需要贴什么信息的吗 求助

**Comment by guxiwuruo** [comment]
以为会像之前一样过几天就好了，结果

**Comment by yfor1008** [comment]
今天我也是不行了 ， 用不了

**Comment by whhxmwhh** [comment]
今天我也是不行了 ， 用不了
就是再试试有时候就又可以的。

**Comment by 2378** [comment]
“强”应该对miredo做了精准探测  结核流量时不时来一棍
表现是 v6 时不时fail 看油管时不时断 网页浏览基本无碍

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10515#issuecomment-383109033

**Comment by SeaHOH** [comment]
>NAT : symmetric (port)
可能和 ISP 服务变化有关，看看路由器是不是公网 IP。

**Comment by SeaHOH** [comment]
参考 #10745 尝试切换客户端类型
