### ISSUE TITLE
Xx-net造成Google play store无法更新，安装。

### ISSUE THREAD

**Issue by Soapere** [XX-net/XX-Net#10510]
错误代码960，一般是在连续下载两次后出现。

**Comment by Soapere** [comment]
[xndroid-logs.tar[1].gz](https://github.com/XX-net/XX-Net/files/1931383/xndroid-logs.tar.1.gz)

**Comment by AnyWAT** [comment]
成功过？🤣
正常更新谷歌应用商店：手机WLAN，长按已连接WiFi，修改网络，显示高级选项，代理设置：手动，代理服务器主机名：运行XX-Net并分享代理的电脑或手机内网地址，代理服务器端口：8087，保存。

**Comment by Soapere** [comment]
这样做也太麻烦了吧。

**Comment by GoodSake** [comment]
3.7.5还未遇到任何异常，用了很长时间了，，，无敌是多么寂寞啊，哈哈哈！

**Comment by AnyWAT** [comment]
LS，楼主是手机非电脑👌
成功过？😜也不见回应。
这样做也太麻烦了吧：貌似有些App 不支持（假）证书😱

**Comment by Soapere** [comment]
好吧，是手机。
