### ISSUE TITLE
在小米路由器3C之下，不能开启ipv6，以至于不能使用xx-net上外网怎么解决？

### ISSUE THREAD

**Issue by riqthen** [XX-net/XX-Net#10519]
各种调试都尝试过。
然后用手机热点给电脑用，xx-net可以正常使用了，换接入小米的wifi就提示让开启ipv6，有办法解决吗？

**Comment by AnyWAT** [comment]
接入小米的wifi ，贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by riqthen** [comment]
C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问主 teredo 服务器


Apr 21 15:46:14.189 - [WARNING] network IPv6 fail
Apr 21 15:46:23.201 - [DEBUG] report_connect_fail IPv6 continue_fail_count:67
Apr 21 15:46:23.201 - [DEBUG] report_connect_fail network fail
Apr 21 15:46:23.201 - [DEBUG] connect 2806:1070:cfff:*::d network fail
Apr 21 15:46:23.210 - [DEBUG] report_connect_fail IPv6 continue_fail_count:68
Apr 21 15:46:23.210 - [DEBUG] report_connect_fail network fail
Apr 21 15:46:23.210 - [DEBUG] connect 2607:f8b0:4006:*::a network fail
Apr 21 15:46:27.246 - [WARNING] network IPv6 fail
Apr 21 15:46:34.213 - [DEBUG] report_connect_fail IPv6 continue_fail_count:69
Apr 21 15:46:34.213 - [DEBUG] report_connect_fail network fail
Apr 21 15:46:34.213 - [DEBUG] connect 2806:1070:cfff:*::d network fail
Apr 21 15:46:34.222 - [DEBUG] report_connect_fail IPv6 continue_fail_count:70
Apr 21 15:46:34.222 - [DEBUG] report_connect_fail network fail
Apr 21 15:46:34.222 - [DEBUG] connect 2607:f8b0:4006:*::a network fail
Apr 21 15:46:50.216 - [DEBUG] report_connect_fail IPv6 continue_fail_count:71
Apr 21 15:46:50.216 - [DEBUG] report_connect_fail network fail
Apr 21 15:46:50.216 - [DEBUG] connect 2806:1070:cfff:*::d network fail
Apr 21 15:46:50.225 - [DEBUG] report_connect_fail IPv6 continue_fail_count:72
Apr 21 15:46:50.225 - [DEBUG] report_connect_fail network fail
Apr 21 15:46:50.225 - [DEBUG] connect 2607:f8b0:4006:*::a network fail

贴出了是部分诊断信息

**Comment by SeaHOH** [comment]
https://www.zhihu.com/question/49309265

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39081945-18f0f248-457d-11e8-85e1-6b3bb874a291.png)

**Comment by riqthen** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:153 ipv4:0 ipv6:36
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 898
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
use-ipv6: auto 改为仅 ipv6
scan-ip-thread-num: 10 增大10倍
关闭”自动调整扫描线程“
管理权限运行 netsh int ipv6 set teredo enterpriseclient default
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP，开始
（不时手动扫描IP：XX-Net中断重开后，IP延时大、连接池小的代理卡顿时）

**Comment by SeaHOH** [comment]
没用呃，这是个假 OpenWrt，要绑小米帐号的。

**Comment by AnyWAT** [comment]
😱不就是个路由器，并不在其内运行XX-Net 的家用路由器？

**Comment by riqthen** [comment]
C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

**Comment by AnyWAT** [comment]
😂正常化中。。。

**Comment by AnyWAT** [comment]
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by riqthen** [comment]
然而一直是 probe (primary server) 这个状态 与 offline状态循环切换

**Comment by SeaHOH** [comment]
换手机热点立马好，信不信？路由器的锅不要让 PC 背。

**Comment by AnyWAT** [comment]
用地址替换？管理权限运行 netsh int ipv6 set teredo enterpriseclient 157.56.149.60

**Comment by riqthen** [comment]
是啊，怀疑就是小米路由使坏，就是有没有办法绕过去

**Comment by riqthen** [comment]
依然不行，还是  "仅IPv6" 不可用，请检查。

**Comment by AnyWAT** [comment]
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by SeaHOH** [comment]
又看了一遍，这个 3C 还不让绑帐号。。。换了吧

**Comment by riqthen** [comment]
不好意思 ，并没有找到teredo.zip 或者teredo.bat的文件或代码的下载地址。。

**Comment by AnyWAT** [comment]
6楼附件😜

**Comment by riqthen** [comment]
下不了，好像下载也是需要翻墙的吧..
