### ISSUE TITLE
 IP 变成 蛋蛋了

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#10516]

**Comment by AnyWAT** [comment]
信则灵，不信则无，视而不见亦如是😜
https://github.com/XX-net/XX-Net/issues/10515#issuecomment-383109033

**Comment by SeaHOH** [comment]
你也是闲的，其实让他用 GoGo Tunnel 就行了，折腾 XX-Net 干嘛。

**Comment by AnyWAT** [comment]
无业游民当然闲😂

**Comment by icecoldless** [comment]
换了最原始的老版本，数量提升到180了

**Comment by AnyWAT** [comment]
来回滚滚也好😂

**Comment by xiaoteai** [comment]
臭大街 表示 蛋蛋 又走了 

> 

- 

- #

**Comment by AnyWAT** [comment]
臭大街法则，基本维持正常，不见蛋蛋🤣

**Comment by xiaoteai** [comment]
呼之则来    挥之则去   蛋蛋 回老家
