### ISSUE TITLE
Google 的云计算平台App Engine（GAE）正在关闭域前置（Domain fronting）功能

### ISSUE THREAD

**Issue by jack89757** [XX-net/XX-Net#10512]
Google 的云计算平台App Engine（GAE）正在关闭域前置（Domain fronting）功能，导致利用 Google 域名绕过国家级审查的反审查工具失效。域前置是一种隐藏连接真实端点来规避审查的技术。此技术的原理为在不同通信层使用不同的域名。在明文的DNS请求和TLS服务器名称指示中使用无害的域名来初始化连接、公布给审查者，而实际要连接的被封锁域名仅在创建加密的 HTTPS 连接后发出，使其不以明文暴露给网络审查者。Google 的代表对此表示，域前置从来不是Google支持的一项特性，它能工作是因为软件栈的古怪行为，Google在不断更新网络，作为计划中的软件更新的一部分，域前置不再能工作。Google 没有计划将其作为一项功能提供。 GAE作为工具是不是要完？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10496

**Comment by GoodSake** [comment]
还来吓唬人，我们已经免疫了，哈哈哈。
不明白发这些的脑子是怎么了，不自己先试下gae是否能用，就发了。。。
不是脑子问题，拿到是五毛例行公事？？？

**Comment by jack89757** [comment]
这我就放心了，这是我用过最好的一款工具了，千万不能有事啊
