### ISSUE TITLE
臭大街 不管用 IP一直掉 不稳定 连不上

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#10522]

**Comment by SeaHOH** [comment]
没必要吊死在这里，工具多的是。

**Comment by xiaoteai** [comment]
say

**Comment by AnyWAT** [comment]
🤣师傅引进门，修行靠个人
![image](https://user-images.githubusercontent.com/37962734/39085600-999be116-45b7-11e8-9f62-ca2d5f2c262d.png)

**Comment by intelligentqi** [comment]
![tim](https://user-images.githubusercontent.com/14028620/39085668-c79d89c4-45b8-11e8-8905-644dd27ed9cb.jpg)
师傅引进门，修行靠运气

**Comment by AnyWAT** [comment]
😂依据臭大街法则，不再是靠运气 https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by Guowei1992** [comment]
将 "good_ip" 分享出来会解决其他人的问题吗？我这里速度还可以。

**Comment by xiaoteai** [comment]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:2551 ipv4:0 ipv6:41
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 697
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
😱真服了你😭
gws-ip-num: total:2551 ipv4:0 ipv6:41：2551 违背臭大街法则1次😂
scan-ip-thread-num: 0：如不是自定义（多大，是否遵循。。。）、而是自动调整的结果，违背臭大街法则1次😂

**Comment by AnyWAT** [comment]
😜貌似不是第一次贴给你：（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by AnyWAT** [comment]
😝不遵循法则，竟然说不管用，拉黑拉黑拉黑🙃

**Comment by xiaoteai** [comment]
臭大街   就一秒 连上     不懂不懂
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop
这个 木有  
该死的 墙官

**Comment by SeaHOH** [comment]
条条大路通罗马，不要停留在路上。。。

**Comment by xiaoteai** [comment]
![difli2s _9ucx3kqta2c57](https://user-images.githubusercontent.com/10782704/39094667-e5d7d914-4665-11e8-945a-d9e5ac6c5f9b.jpg)

**Comment by sjfirefox** [comment]
你们这是要比烂么？
![image](https://s1.ax1x.com/2018/04/24/Cl89Cd.png)

**Comment by jcorg** [comment]
![image](https://user-images.githubusercontent.com/22322219/39290777-552ea73e-4963-11e8-8bc5-2c8643be59c0.png)

**Comment by xiaoteai** [comment]
蜘蛛侠
