### ISSUE TITLE
gmail youtube輸入ID和密碼之後就顯示這樣

### ISSUE THREAD

**Issue by foho8080** [XX-net/XX-Net#10523]
就是登錄gmail和youtube網頁之後輸入ID和密碼之後就顯示這樣
![default](https://user-images.githubusercontent.com/17214241/39085597-92a6fa26-45b7-11e8-99c7-adf1f5df3b04.jpg)

**Comment by AnyWAT** [comment]
貌似代理速度的锅😜

**Comment by SeaHOH** [comment]
#10537
