### ISSUE TITLE
Google无法登陆cookie无法加载

### ISSUE THREAD

**Issue by colorsakura** [XX-net/XX-Net#10525]
XX-Net Status:

sys-platform: x86_64, Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
os-system: Linux
os-version: #1 SMP Wed Mar 7 19:03:37 UTC 2018
os-release: 3.10.0-693.21.1.el7.x86_64
os-detail: Dist:CentOS Linux; Version:7.4.1708; ID:Core
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.5
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:93 h2:0
scan-ip-thread-num: 100
ip-quality: 289
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
![screenshot from 2018-04-22 11-04-48](https://user-images.githubusercontent.com/32534829/39090961-a27d8382-461d-11e8-8f41-8ef24f170f1b.png)

**Comment by AnyWAT** [comment]
貌似代理速度的锅😜😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by AnyWAT** [comment]
貌似代理速度的锅😜😜参考臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by colorsakura** [comment]
只用xx-tunnel登录成功，再切换回smart，正常了
