### ISSUE TITLE
一切都好，就是登陆不了google和youtube的账号

### ISSUE THREAD

**Issue by luogx10517** [XX-net/XX-Net#10528]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:491 ipv4:0 ipv6:38
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:11 h2:0
scan-ip-thread-num: 10
ip-quality: 1594
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
貌似代理速度的锅😜😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by Guowei1992** [comment]
#10349

**Comment by colorsakura** [comment]
#10525

**Comment by SeaHOH** [comment]
#10537
