### ISSUE TITLE
youtube 看着就中断了..

### ISSUE THREAD

**Issue by lsq726** [XX-net/XX-Net#10520]
Apr 21 18:09:13.698 - [WARNING] 2806:1050:cfff:6::c h1_request:Exception('time out',) inactive_time:7 task.timeout:5

Apr 21 18:09:13.698 - [WARNING] 2806:1050:cfff:6::c trace: 0:connect, 743:init, 652:request, 1144:Res, 9:request, 497:Res, 539:request, 3788:Res, 100:request, 358:Res, 14891:request, 312:Res, 5279:request, 1385:Res, 11:request, 5292:Res, 8771:request, 1450:Res, 18:request, 603:Res, 8920:request, 1223:Res, 9:request,:6023, processed:10, transfered:546225, sni:knee-finger-interaction.org

Apr 21 18:09:13.698 - [DEBUG] POST None/_gh/ response_fail:retry timeout:6

Apr 21 18:09:13.698 - [DEBUG] 2806:1050:cfff:6::c worker close:down fail

Apr 21 18:09:13.986 - [INFO] GAE t:6312 s:22 GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=171&TYPE=xmlhttp&zx=5yddtcohyz1n&t=1 0:start_request,0:get_task(5),0:get_worker(0):2806:1040:cfff:4::12,0:h1_req,0:h1_req_sended,1220:response_begin,0:h1_get_head,0:h1_finish[SP:291],0:get_response,:2

Apr 21 18:09:13.996 - [DEBUG] GAE GET /client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=174&TYPE=xmlhttp&zx=zfq0yb2zbyr4&t=1 from:127.0.0.1:50866

Apr 21 18:09:14.213 - [DEBUG] create_ssl update ip:2607:f798:1e:1000::d time:1757 h2:0 sni:consequence.youth.south.us, host:

Apr 21 18:09:14.215 - [DEBUG] create_ssl update ip:2620:11a:a027::19 time:941 h2:0 sni:market-chip-initiative.org, host:lsq726t.appspot.com

Apr 21 18:09:14.681 - [INFO] scan_ip add ip:2607:f8b0:401c:1::8 time:296 h2:0

Apr 21 18:09:14.685 - [INFO] remove_slowest_ip:2620:11a:a027::19 handshake_time:843, fails:0

Apr 21 18:09:15.632 - [DEBUG] create_ssl update ip:2800:e0:c74::f time:945 h2:0 sni:excitement.let.charity.net, host:lsq726e.appspot.com

Apr 21 18:09:15.876 - [DEBUG] create_ssl update ip:2607:f798:14:42::e time:1873 h2:0 sni:mathcarrypack.org, host:cgl42602.appspot.com

Apr 21 18:09:16.757 - [INFO] scan_ip add ip:2001:16a0:202:110::c time:560 h2:0

Apr 21 18:09:16.761 - [INFO] remove_slowest_ip:2800:e0:c74::f handshake_time:897, fails:0

Apr 21 18:09:18.462 - [INFO] scan_ip add ip:2a00:1450:4001:6c::9 time:444 h2:0

Apr 21 18:09:18.470 - [INFO] remove_slowest_ip:2607:f798:14:42::e handshake_time:867, fails:0

Apr 21 18:09:18.487 - [INFO] scan_ip add ip:2001:fb0:1064:1a::12 time:638 h2:0

Apr 21 18:09:18.493 - [INFO] remove_slowest_ip:2607:f798:1e:1000::d handshake_time:805, fails:0

Apr 21 18:09:18.677 - [INFO] scan_ip add ip:2a00:1450:401f:3d::c time:432 h2:0

Apr 21 18:09:18.690 - [INFO] scan_ip add ip:2001:4c48:13::11 time:489 h2:0

Apr 21 18:09:18.693 - [INFO] remove_slowest_ip:2001:4c48:13::11 handshake_time:489, fails:0

Apr 21 18:09:18.693 - [INFO] remove_slowest_ip:2607:f8b0:4020::7 handshake_time:786, fails:0

Apr 21 18:09:19.010 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 21 18:09:19.010 - [WARNING] gae_exception:'600:fetch gae fail' https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=174&TYPE=xmlhttp&zx=zfq0yb2zbyr4&t=1

Apr 21 18:09:20.016 - [WARNING] 2806:1040:cfff:4::12 h1_request:Exception('time out',) inactive_time:7 task.timeout:5

Apr 21 18:09:20.016 - [WARNING] 2806:1040:cfff:4::12 trace: 0:connect, 3160:init, 332:request, 1406:Res, 139:request, 374:Res, 664:request, 812:Res, 625:request, 338:Res, 1184:request, 338:Res, 1078:request, 1994:Res, 121:request, 2093:Res, 136:request, 403:Res, 1513:request, 319:Res, 813:request, 2165:Res, 242:request, 893:Res, 493:request, 962:Res, 126:request, 814:Res, 263:request, 870:Res, 148:request, 328:Res, 2659:request, 312:Res, 1122:request, 345:Res, 3611:request, 319:Res, 14483:request, 315:Res, 10585:request, 320:Res, 26939:request, 1220:Res, 16:request,:6016, processed:21, transfered:1018998, sni:examinationlectureregret.ml

Apr 21 18:09:20.016 - [DEBUG] POST None/_gh/ response_fail:retry timeout:6

Apr 21 18:09:20.016 - [DEBUG] 2806:1040:cfff:4::12 worker close:down fail

Apr 21 18:09:20.350 - [INFO] GAE t:6353 s:22 GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=174&TYPE=xmlhttp&zx=zfq0yb2zbyr4&t=1 0:start_request,7:get_task(5),0:get_worker(0):2600:2:100:3::12,3:h1_req,0:h1_req_sended,1324:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:268],:3

Apr 21 18:09:20.356 - [DEBUG] GAE GET /client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=177&TYPE=xmlhttp&zx=p6q699eprwes&t=1 from:127.0.0.1:50866

Apr 21 18:09:20.556 - [INFO] scan_ip add ip:2607:f8b0:4008:27::c time:311 h2:0

Apr 21 18:09:20.559 - [INFO] remove_slowest_ip:2001:fb0:1064:1a::12 handshake_time:638, fails:0

Apr 21 18:09:20.617 - [INFO] scan_ip add ip:2404:6800:400a:a::9 time:473 h2:0

Apr 21 18:09:20.619 - [INFO] remove_slowest_ip:2001:16a0:202:110::c handshake_time:560, fails:0

Apr 21 18:09:20.721 - [INFO] scan_ip add ip:2405:200:1607:1727::d time:1756 h2:0

Apr 21 18:09:20.724 - [INFO] remove_slowest_ip:2405:200:1607:1727::d handshake_time:1756, fails:0

Apr 21 18:09:20.751 - [INFO] scan_ip add ip:2607:f798:14:3e::d time:289 h2:0

Apr 21 18:09:20.753 - [INFO] remove_slowest_ip:2404:6800:400a:a::9 handshake_time:473, fails:0

Apr 21 18:09:20.790 - [DEBUG] create_ssl update ip:2607:f8b0:401c:1::8 time:576 h2:0 sni:screwbidtill.us, host:

Apr 21 18:09:22.409 - [DEBUG] create_ssl update ip:2607:f8b0:4002:2f::8 time:773 h2:0 sni:limitpotentialleading.com, host:lsq726t3.appspot.com

Apr 21 18:09:23.332 - [INFO] scan_ip add ip:2402:800:6150:5::13 time:583 h2:0

Apr 21 18:09:23.338 - [INFO] remove_slowest_ip:2607:f8b0:4002:2f::8 handshake_time:773, fails:0

Apr 21 18:09:23.411 - [INFO] scan_ip add ip:2a00:1e48:99:16::d time:532 h2:0

Apr 21 18:09:23.413 - [INFO] remove_slowest_ip:2402:800:6150:5::13 handshake_time:583, fails:0

Apr 21 18:09:24.111 - [INFO] scan_ip add ip:2607:f8b0:4012:f::15 time:271 h2:0

Apr 21 18:09:24.113 - [INFO] remove_slowest_ip:2607:f8b0:401c:1::8 handshake_time:576, fails:0

Apr 21 18:09:24.779 - [INFO] scan_ip add ip:2001:12e0:803:5::1d time:546 h2:0

Apr 21 18:09:24.781 - [INFO] remove_slowest_ip:2001:12e0:803:5::1d handshake_time:546, fails:0

Apr 21 18:09:24.874 - [INFO] scan_ip add ip:2404:6800:4007:1::d time:702 h2:0

Apr 21 18:09:24.880 - [INFO] remove_slowest_ip:2404:6800:4007:1::d handshake_time:702, fails:0

Apr 21 18:09:25.362 - [INFO] scan_ip add ip:2620:11a:a00e:1::1a time:259 h2:0

Apr 21 18:09:25.373 - [INFO] remove_slowest_ip:2a00:1e48:99:16::d handshake_time:532, fails:0

Apr 21 18:09:25.407 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 21 18:09:25.407 - [WARNING] gae_exception:'600:fetch gae fail' https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=177&TYPE=xmlhttp&zx=p6q699eprwes&t=1

Apr 21 18:09:25.841 - [INFO] scan_ip add ip:2620:11a:a012:2::c time:439 h2:0

Apr 21 18:09:25.848 - [INFO] remove_slowest_ip:2a00:1450:400d:2::12 handshake_time:470, fails:0

Apr 21 18:09:26.215 - [INFO] scan_ip add ip:2001:4958:300:526::d time:316 h2:0

Apr 21 18:09:26.218 - [INFO] remove_slowest_ip:2a00:1450:4001:4f::c handshake_time:467, fails:0

Apr 21 18:09:26.274 - [WARNING] 2600:2:100:3::12 h1_request:Exception('time out',) inactive_time:7 task.timeout:5

Apr 21 18:09:26.274 - [WARNING] 2600:2:100:3::12 trace: 0:connect, 763:init, 2533:request, 1409:Res, 69:request, 1416:Res, 28323:request, 345:Res, 32988:request, 1325:Res, 11:request,:5916, processed:4, transfered:93794, sni:emphasis.assumption.film.com

Apr 21 18:09:26.274 - [DEBUG] POST None/_gh/ response_fail:retry timeout:5

Apr 21 18:09:26.275 - [DEBUG] 2600:2:100:3::12 worker close:down fail

Apr 21 18:09:26.667 - [INFO] GAE t:6311 s:22 GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=177&TYPE=xmlhttp&zx=p6q699eprwes&t=1 0:start_request,0:get_task(5),0:get_worker(0):2607:f8b0:4004:32::9,0:h1_req,0:h1_req_sended,1255:response_begin,0:h1_get_head,0:h1_finish[SP:284],0:get_response,:3

Apr 21 18:09:26.695 - [DEBUG] GAE GET /client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=180&TYPE=xmlhttp&zx=sl5uq3vypda&t=1 from:127.0.0.1:50866

Apr 21 18:09:26.697 - [INFO] scan_ip add ip:2800:3f0:4001:13::e time:505 h2:0

Apr 21 18:09:26.702 - [INFO] remove_slowest_ip:2800:3f0:4001:13::e handshake_time:505, fails:0

Apr 21 18:09:26.983 - [INFO] scan_ip add ip:2607:f8b0:401a:27::9 time:240 h2:0

Apr 21 18:09:26.997 - [INFO] remove_slowest_ip:2a02:a000:1:201::f handshake_time:447, fails:0

Apr 21 18:09:27.104 - [INFO] scan_ip add ip:2a00:1eb8:e000:104::13 time:531 h2:0

Apr 21 18:09:27.110 - [INFO] remove_slowest_ip:2a00:1eb8:e000:104::13 handshake_time:531, fails:0

Apr 21 18:09:27.355 - [INFO] scan_ip add ip:2a02:8400:0:10a::f time:450 h2:0

Apr 21 18:09:27.357 - [INFO] remove_slowest_ip:2a02:8400:0:10a::f handshake_time:450, fails:0

Apr 21 18:09:27.506 - [DEBUG] create_ssl update ip:2620:11a:a00e:1::1a time:714 h2:0 sni:help-promise-blood.ml, host:

Apr 21 18:09:27.577 - [INFO] scan_ip add ip:2620:11a:a013::1e time:576 h2:0

Apr 21 18:09:27.582 - [INFO] remove_slowest_ip:2620:11a:a00e:1::1a handshake_time:714, fails:0

Apr 21 18:09:28.218 - [INFO] scan_ip add ip:2001:fb0:1065:3::e time:634 h2:0

Apr 21 18:09:28.220 - [INFO] remove_slowest_ip:2001:fb0:1065:3::e handshake_time:634, fails:0

Apr 21 18:09:28.607 - [INFO] scan_ip add ip:2001:fb0:1064:1c::f time:651 h2:0

Apr 21 18:09:28.614 - [INFO] remove_slowest_ip:2001:fb0:1064:1c::f handshake_time:651, fails:0

Apr 21 18:09:29.073 - [INFO] scan_ip add ip:2a00:1e48:1:24::d time:605 h2:0

Apr 21 18:09:29.075 - [INFO] remove_slowest_ip:2a00:1e48:1:24::d handshake_time:605, fails:0

Apr 21 18:09:29.125 - [DEBUG] create_ssl update ip:2607:f8b0:4012:f::15 time:713 h2:0 sni:unclecheekgovernment.ml, host:lsq726f2.appspot.com

Apr 21 18:09:30.295 - [INFO] scan_ip add ip:2001:16a0:102:106::e time:582 h2:0

Apr 21 18:09:30.305 - [INFO] remove_slowest_ip:2607:f8b0:4012:f::15 handshake_time:713, fails:0

Apr 21 18:09:30.690 - [INFO] scan_ip add ip:2403:6200:ffff:ffe0::10 time:1710 h2:0

Apr 21 18:09:30.696 - [INFO] remove_slowest_ip:2403:6200:ffff:ffe0::10 handshake_time:1710, fails:0

Apr 21 18:09:30.703 - [INFO] scan_ip add ip:2607:f8b0:400a:9::7 time:427 h2:0

Apr 21 18:09:30.707 - [INFO] remove_slowest_ip:2001:16a0:102:106::e handshake_time:582, fails:0

Apr 21 18:09:31.201 - [INFO] scan_ip add ip:2a00:1450:4002:b::6 time:515 h2:0

Apr 21 18:09:31.204 - [INFO] remove_slowest_ip:2620:11a:a013::1e handshake_time:576, fails:0

Apr 21 18:09:31.312 - [INFO] scan_ip add ip:2620:11a:a014:1::12 time:840 h2:0

Apr 21 18:09:31.315 - [INFO] remove_slowest_ip:2620:11a:a014:1::12 handshake_time:840, fails:0

Apr 21 18:09:31.566 - [INFO] scan_ip add ip:2a00:1450:4011:2e::18 time:560 h2:0

Apr 21 18:09:31.581 - [INFO] remove_slowest_ip:2a00:1450:4011:2e::18 handshake_time:560, fails:0

Apr 21 18:09:31.657 - [INFO] scan_ip add ip:2a00:1450:400d:e::7 time:473 h2:0

Apr 21 18:09:31.659 - [INFO] remove_slowest_ip:2a00:1450:4002:b::6 handshake_time:515, fails:0

Apr 21 18:09:31.719 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 21 18:09:31.719 - [WARNING] gae_exception:'600:fetch gae fail' https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=180&TYPE=xmlhttp&zx=sl5uq3vypda&t=1

Apr 21 18:09:32.714 - [WARNING] 2607:f8b0:4004:32::9 h1_request:Exception('time out',) inactive_time:7 task.timeout:5

Apr 21 18:09:32.714 - [WARNING] 2607:f8b0:4004:32::9 trace: 0:connect, 804:init, 429:request, 430:Res, 73555:request, 1255:Res, 34:request,:6015, processed:2, transfered:880, sni:floorcollection.org

Apr 21 18:09:32.714 - [DEBUG] POST None/_gh/ response_fail:retry timeout:6

Apr 21 18:09:32.714 - [DEBUG] 2607:f8b0:4004:32::9 worker close:down fail

Apr 21 18:09:33.018 - [INFO] GAE t:6322 s:22 GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=180&TYPE=xmlhttp&zx=sl5uq3vypda&t=1 0:start_request,0:get_task(5),0:get_worker(0):2607:f8b0:4012:f::15,0:h1_req,0:h1_req_sended,1293:response_begin,0:h1_get_head,0:h1_finish[SP:275],0:get_response,:2

Apr 21 18:09:33.025 - [DEBUG] GAE GET /client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=183&TYPE=xmlhttp&zx=reo4ynyxrnfz&t=1 from:127.0.0.1:50866

Apr 21 18:09:33.190 - [INFO] scan_ip add ip:2404:6800:400a:9::9 time:478 h2:0

Apr 21 18:09:33.197 - [INFO] remove_slowest_ip:2404:6800:400a:9::9 handshake_time:478, fails:0

Apr 21 18:09:33.644 - [INFO] scan_ip add ip:2404:6800:400c:7::b time:1270 h2:0

Apr 21 18:09:33.650 - [INFO] remove_slowest_ip:2404:6800:400c:7::b handshake_time:1270, fails:0

Apr 21 18:09:33.749 - [INFO] scan_ip add ip:2a02:8400:0:110::10 time:446 h2:0

Apr 21 18:09:33.755 - [INFO] remove_slowest_ip:2a00:1450:400d:e::7 handshake_time:473, fails:0

Apr 21 18:09:33.808 - [INFO] scan_ip add ip:2a00:1450:4011:28::1a time:517 h2:0

Apr 21 18:09:33.814 - [INFO] remove_slowest_ip:2a00:1450:4011:28::1a handshake_time:517, fails:0

Apr 21 18:09:34.079 - [INFO] scan_ip add ip:2a00:1450:400b:2::16 time:446 h2:0

Apr 21 18:09:34.081 - [INFO] remove_slowest_ip:2a02:a000:2:200::11 handshake_time:447, fails:0

Apr 21 18:09:34.186 - [DEBUG] create_ssl update ip:2607:f8b0:401a:27::9 time:677 h2:0 sni:unit-few-knowledge.com, host:

Apr 21 18:09:34.999 - [INFO] scan_ip add ip:2404:6800:4004:17::6 time:1093 h2:0

Apr 21 18:09:35.000 - [INFO] remove_slowest_ip:2404:6800:4004:17::6 handshake_time:1093, fails:0

Apr 21 18:09:35.141 - [INFO] scan_ip add ip:2a00:1450:4011:3d::19 time:523 h2:0

Apr 21 18:09:35.143 - [INFO] remove_slowest_ip:2607:f8b0:401a:27::9 handshake_time:677, fails:0

Apr 21 18:09:35.261 - [INFO] scan_ip add ip:2607:f8b0:400a:3::8 time:253 h2:0

Apr 21 18:09:35.266 - [INFO] remove_slowest_ip:2a00:1450:4011:3d::19 handshake_time:523, fails:0

Apr 21 18:09:35.656 - [INFO] scan_ip add ip:2607:f8b0:401c:29::a time:270 h2:0

Apr 21 18:09:35.658 - [INFO] remove_slowest_ip:2a00:1450:400e:4::6 handshake_time:447, fails:0

Apr 21 18:09:35.837 - [INFO] scan_ip add ip:2607:f8b0:4008:27::a time:305 h2:0

Apr 21 18:09:35.839 - [INFO] remove_slowest_ip:2a02:8400:0:125::11 handshake_time:447, fails:0

Apr 21 18:09:35.886 - [DEBUG] create_ssl update ip:2607:f8b0:4008:27::c time:760 h2:0 sni:solid-regular-two.us, host:cgl42602.appspot.com

Apr 21 18:09:35.982 - [INFO] scan_ip add ip:2804:854:15::12 time:621 h2:0

Apr 21 18:09:35.985 - [INFO] remove_slowest_ip:2607:f8b0:4008:27::c handshake_time:760, fails:0

Apr 21 18:09:36.393 - [INFO] scan_ip add ip:2a00:a040:3:5::c time:585 h2:0

Apr 21 18:09:36.397 - [INFO] remove_slowest_ip:2804:854:15::12 handshake_time:621, fails:0

Apr 21 18:09:36.750 - [INFO] scan_ip add ip:2405:4800:100:17::11 time:578 h2:0

Apr 21 18:09:36.752 - [INFO] remove_slowest_ip:2a00:a040:3:5::c handshake_time:585, fails:0

Apr 21 18:09:37.405 - [INFO] scan_ip add ip:2405:9800:8:3001::10 time:1683 h2:0

Apr 21 18:09:37.406 - [INFO] remove_slowest_ip:2405:9800:8:3001::10 handshake_time:1683, fails:0

Apr 21 18:09:38.029 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 21 18:09:38.029 - [WARNING] gae_exception:'600:fetch gae fail' https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=183&TYPE=xmlhttp&zx=reo4ynyxrnfz&t=1

Apr 21 18:09:38.358 - [INFO] scan_ip add ip:2a00:1450:400a:5::11 time:452 h2:0

Apr 21 18:09:38.360 - [INFO] remove_slowest_ip:2405:4800:100:17::11 handshake_time:578, fails:0

Apr 21 18:09:38.833 - [INFO] scan_ip add ip:2a00:1450:400b:6::9 time:444 h2:0

Apr 21 18:09:38.853 - [INFO] remove_slowest_ip:2a00:1450:400a:5::11 handshake_time:452, fails:0

Apr 21 18:09:38.876 - [INFO] scan_ip add ip:2607:f8b0:4002:2f::a time:355 h2:0

Apr 21 18:09:38.882 - [INFO] remove_slowest_ip:2a00:1450:401f:2::6 handshake_time:446, fails:0

Apr 21 18:09:39.046 - [WARNING] 2607:f8b0:4012:f::15 h1_request:Exception('time out',) inactive_time:7 task.timeout:5

Apr 21 18:09:39.046 - [WARNING] 2607:f8b0:4012:f::15 trace: 0:connect, 2791:init, 519:request, 1294:Res, 10:request,:6019, processed:1, transfered:428, sni:unclecheekgovernment.ml

多事之秋...

* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by lsq726** [comment]
Apr 21 18:12:05.449 - [WARNING] gae_exception:'600:fetch gae fail' https://0.client-channel.google.com/client-channel/channel/bind?ctype=memento&gsessionid=QDBRI1VFFNcyZZSGZixziQI9SkZSvNzn&VER=8&RID=rpc&SID=28F117997AA37B60&CI=1&AID=235&TYPE=xmlhttp&zx=ervigyd2h5pf&t=1

Apr 21 18:12:05.619 - [WARNING] 2806:1050:cfff:5::f h1_request:Exception('time out',) inactive_time:21 task.timeout:20

Apr 21 18:12:05.619 - [WARNING] 2806:1050:cfff:5::f trace: 0:connect, 3499:init, 1071:request, 532:Res, 1460:request, 1717:Res, 432:request, 1128:Res, 5494:request, 506:Res, 844:request, 401:Res, 786:request, 351:Res, 1228:request, 1730:Res, 1746:request, 378:Res, 1800:request, 313:Res, 1329:request, 347:Res, 1782:request, 1542:Res, 177:request,:20260, processed:11, transfered:552113, sni:comfort-cold-farmer.net

**Comment by AnyWAT** [comment]
😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
