### ISSUE TITLE
臭大街法则怎么设置？都设置哪几项啊？

### ISSUE THREAD

**Issue by iSuperYang** [XX-net/XX-Net#10524]
臭大街法则怎么设置？都设置哪几项啊？

**Comment by AnyWAT** [comment]
🤣既然知道臭大街法则，就应晓得怎么设置 https://github.com/XX-net/XX-Net/issues/10515#event-1587262313 #10184

**Comment by AnyWAT** [comment]
舅服你，高抬贵鼠，点击 #10515
