### ISSUE TITLE
请问哪项是"有效的Teredo接口名称"?

### ISSUE THREAD

**Issue by tq01o3n** [XX-net/XX-Net#10526]
已经解决了，谢谢楼下

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引

这个操作更详细

**Comment by tq01o3n** [comment]
@SeaHOH 请问我进行到设置IPV6 DNS时，我没有查到本地IPV6 DNS地址，怎么办？

**Comment by SeaHOH** [comment]
这个无所谓，不设置也能用 XX-Net。

**Comment by tq01o3n** [comment]
好的，谢谢

发自我的 iPhone

**Comment by tq01o3n** [comment]
@SeaHOH 请问，上次我问过你,设置IPV6 DNS时，没有查到本地IPV6 DNS地址,就不设置了，然后一步一步设置到第六项“打开http://test-ipv6.com/查看IPv6 连接测试”，测试完后
摘要页面提示“你的 DNS 服务器（可能由运营商提供）没有接入或没有配置 IPv6，将来这可能会妨碍你访问纯 IPv6 网站。”，
测试项目页面其他项目都是成功，只有两个提示：“
测试运营商 DNS 是否接入 IPv6 |   | 超时 (11.022s)
查询 IPv6 运营商 |   | 失败 (0.385s)

这个怎么办？





”
