### ISSUE TITLE
因中兴而起。。。

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#10521]
🤣弟、兄、嫂
![image](https://user-images.githubusercontent.com/37962734/39083157-a602d452-4592-11e8-866a-70b2cfbaa272.png)
![image](https://user-images.githubusercontent.com/37962734/39083165-b4773a3c-4592-11e8-8f0e-d33740a525aa.png)
![image](https://user-images.githubusercontent.com/37962734/39083167-b9518594-4592-11e8-955e-938e7c8e8925.png)
![image](https://user-images.githubusercontent.com/37962734/39083183-fb805a3a-4592-11e8-8960-e7029c82034c.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39083228-d828e5a6-4593-11e8-9a0d-c5ed35830020.png)

**Comment by GoodSake** [comment]
有意思，哈哈哈！
人和人确实不同，亲人之间发现无法认同，那屏蔽就好了，没有教育义务的哦。
远离臭人，清静修身，严于律己。

**Comment by AnyWAT** [comment]
某地现在进行时😜
![image](https://user-images.githubusercontent.com/37962734/39083502-5bd0d2a8-4597-11e8-9eb2-3d4bef2a6359.png)
![image](https://user-images.githubusercontent.com/37962734/39083506-6afee882-4597-11e8-8c69-135a05dc1dc2.png)

**Comment by ffdzpilot** [comment]
估计怕变革，南郭先生们都急眼了。

**Comment by Guowei1992** [comment]
https://www.bilibili.com/video/av21086017?from=search&seid=595009203699496858

**Comment by GoodSake** [comment]
运动是本质，曾经的动派打倒了反动派就想万岁万岁万万岁独裁了，动派已成反动派被打倒是不可避免的，只是好看难看的问题。信息时代五毛再多再漂亮也是徒劳。哈哈哈！

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39093640-30096248-4655-11e8-8e3c-a180a457b3b2.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39093757-4a379494-4657-11e8-8464-162a637c0767.png)
![default](https://user-images.githubusercontent.com/37962734/39093760-5491309e-4657-11e8-8ca6-0ab2f06145f2.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39094967-2ca666c6-466b-11e8-883d-1c3fdcdbf488.png)
![default](https://user-images.githubusercontent.com/37962734/39094969-3959b1ca-466b-11e8-8899-e015bc581baa.png)
![default](https://user-images.githubusercontent.com/37962734/39094970-3f456eee-466b-11e8-95de-113b8688c680.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39095135-4b8a809c-466e-11e8-923b-52495af515d6.png)
![default](https://user-images.githubusercontent.com/37962734/39095138-555ea788-466e-11e8-8b6e-13fd5b3a008d.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39095161-cc138510-466e-11e8-9f93-aa1b90d1c02e.png)
![default](https://user-images.githubusercontent.com/37962734/39095168-db931640-466e-11e8-926d-28e04c60270d.png)
![default](https://user-images.githubusercontent.com/37962734/39095172-e0c7c0b6-466e-11e8-85fa-24256661fdb5.png)

**Comment by AnyWAT** [comment]
😱转：怎样拯救你国的芯片行业？芯片靠研发，研发靠人才，人才靠教育，教育靠学区房。给孩子买了学区房，让孩子获得优质教育。孩子获得优质教育，成了高端人才。毕业后从事芯片研发，研发出了顶尖的芯片出售赚了钱，再给孩子的孩子买学区房……发展路线非常明确！ #地产兴邦

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39095426-d4cd1230-4672-11e8-9b01-351eefdc8bc8.png)

**Comment by AnyWAT** [comment]
😱转：手机造不出芯片，但却能检测屏蔽所谓的敏感词；互联网没有根服务器，但却能搞出阻碍信息流动的防火墙；国际上喊不能诉诸武力，却在国内对民众拳脚相向；而当国内无数的孩子缴不起学费之时，你却又在国际上到处援助。增进福祉发展人类文明的工作从来不做，反人类的事情却刻刻不停，这就是你――乌托邦！

**Comment by AnyWAT** [comment]
🤣转：几千年来，这个民族就把耍无赖叫做智慧。
![image](https://user-images.githubusercontent.com/37962734/39100900-3bc692a8-46c4-11e8-8a2c-ccde4e0bce2b.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39104575-ed75998a-46e3-11e8-9a19-730816fbcb34.png)
![image](https://user-images.githubusercontent.com/37962734/39104579-f48eb6b6-46e3-11e8-8626-b672b28cf5c1.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39105208-364822e2-46e7-11e8-84b7-23209c408f6a.png)
![image](https://user-images.githubusercontent.com/37962734/39105214-3ca28efc-46e7-11e8-8c0a-6868588330df.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/39133706-64153628-4747-11e8-893c-c475f9a60707.png)
![image](https://user-images.githubusercontent.com/37962734/39133719-6af5d362-4747-11e8-8791-6a28cf468107.png)
![image](https://user-images.githubusercontent.com/37962734/39133540-08065ace-4747-11e8-898d-55eead842b4a.png)
![image](https://user-images.githubusercontent.com/37962734/39133549-0f4c9366-4747-11e8-8755-c41b7ea740e4.png)
