### ISSUE TITLE
GG了吗  

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#10530]
一律失败

![Uploading QQ截图20180422191440.png…]()
![Uploading QQ截图20180422191447.png…]()
![Uploading QQ截图20180422191652.png…]()

**Comment by GoodSake** [comment]
厉害了，我的3.7.5。速度绝对嘎嘎的！！哟西哟西


![snap2](https://user-images.githubusercontent.com/19205130/39094518-352aa3e6-4663-11e8-899b-fd42f9dbe4ba.png)

**Comment by klcb2010** [comment]
楼上兄弟发给我包可以吗

**Comment by klcb2010** [comment]
![qq 20180422191434](https://user-images.githubusercontent.com/32628414/39094633-31563fc6-4665-11e8-9688-15125238425d.png)
![qq 20180422191447](https://user-images.githubusercontent.com/32628414/39094634-3e482a3c-4665-11e8-8574-da91f5182616.png)
![qq 20180422191652](https://user-images.githubusercontent.com/32628414/39094635-440f085a-4665-11e8-92f9-ed4ab3192cdd.png)
智能路由测试成功  其他模式测试失败  但是IPv6一直失败

**Comment by AnyWAT** [comment]
😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引

**Comment by klcb2010** [comment]
感谢楼上   臭大街 厉害了
