### ISSUE TITLE
GAEProxy 配置中无高级选项

### ISSUE THREAD

**Issue by nanyang9** [XX-net/XX-Net#10536]
![image](https://user-images.githubusercontent.com/38664057/39136978-1045b2e0-474f-11e8-8079-3c4a8c36316b.png)

求助，已开启IPV6，但XXNET中无法开启ipv6选项。

**Comment by nanyang9** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:112
ipv4-status: OK
ipv6-status: OK
connected-link: new:2
worker: h1:21 h2:0
scan-ip-thread-num: 10
ip-quality: 664
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
@SeaHOH 冒充大佬，已过11小时，是你先说还是。。。😜

**Comment by nanyang9** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced可以点开，如下
![image](https://user-images.githubusercontent.com/38664057/39198294-47268b02-4819-11e8-947f-e541c8b63d2b.png)

netsh int ipv6 show teredo 运行结果：
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

状态页：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:42
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:15 h2:0
scan-ip-thread-num: 10
ip-quality: 1049
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

这样就可以吗？但是ipv6数量很少，怎么办？先谢谢大神的解答了！

**Comment by AnyWAT** [comment]
NAT : restricted (port)貌似不太正常？服务器名称 : teredo.remlab.net 的锅？管理权限运行
netsh int ipv6 set teredo enterpriseclient default
scan-ip-thread-num: 10 及ipv6数量很少，在臭大街法则内有解释 https://github.com/XX-net/XX-Net/issues/10515#event-1587262313
