### ISSUE TITLE
WIN10一直连接尚未建立。

### ISSUE THREAD

**Issue by Felixchen1024** [XX-net/XX-Net#10532]
使用的是最新版，有类似问题，参考了无效，也尝试重新开启IPV6很多次（参考https://github.com/XX-net/XX-Net/wiki/IPv6-Win10），仍然无效。
诊断信息如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:22 ipv4:0 ipv6:21
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 624
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by Felixchen1024** [comment]
类型                    : client (Group Policy)
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
类型 : client (Group Policy)：仅此1/4项为组策略设置🤣
结束进程 pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行
netsh int ipv6 set teredo enterpriseclient default
😜试试臭大街法则：https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by AnyWAT** [comment]
完整组策略设置
类型 : client (Group Policy)
服务器名称 : teredo.remlab.net (Group Policy)
客户端刷新间隔 : 30 秒 (Group Policy)
客户端端口 : unspecified (Group Policy)

**Comment by AnyWAT** [comment]
#8915 tertdo.bat 自动（或手动）优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by Felixchen1024** [comment]
++++++++++ping testing+++++++++

teredo.remlab.net 289 ms
teredo2.remlab.net 276 ms
teredo-debian.remlab.net 289 ms
teredo.ngix.ne.kr 54 ms
teredo.trex.fi 287 ms
teredo.autotrans.consulintel.com 55 ms
teredo.managemydedi.com 54 ms
teredo.ipv6.microsoft.com 54 ms
win10.ipv6.microsoft.com 9999 ms
teredo.iks-jena.de 235 ms
win1710.ipv6.microsoft.com 9999 ms

+++++++最佳teredo为： teredo.ipv6.microsoft.com +++++++
确定。

**Comment by AnyWAT** [comment]
54 ms😱

**Comment by Felixchen1024** [comment]
测试完还是连接尚未建立。~。~||

**Comment by SeaHOH** [comment]
都说了，那个脚本其实没用。。。

>先前修改的ipv6组策略退回到默认值的全部“未配置”

这个倒是很必要

**Comment by Felixchen1024** [comment]
组策略已经全部恢复默认了，还是连接不上，其他电脑就OK，有点奇怪

**Comment by AnyWAT** [comment]
选另外54ms 的，传说那个已废
😜测试个78毛（屁用没有），👍手动检查IP

**Comment by Felixchen1024** [comment]
老铁，你没贴内容-。-

**Comment by Felixchen1024** [comment]
改成手动，仅IPV6，依旧不行

**Comment by Felixchen1024** [comment]
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
行了，退回你先前状态吧
管理权限运行
netsh int ipv6 set teredo client teredo.remlab.net
886👌

**Comment by Felixchen1024** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.managemydedi.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10530#event-1587827557

**Comment by Felixchen1024** [comment]
"仅IPv6" 不可用，请检查。OMG...

**Comment by Felixchen1024** [comment]
哥们你那边方便远程不，要不远程一下，teamviewer

**Comment by SeaHOH** [comment]
IPv6 不光是 teredo 而已，下面这个同样适用于 Win10。
https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引

如果要测试 teredo，这里有个脚本可用。 #10328

**Comment by Felixchen1024** [comment]
哎，依旧不行，太奇怪了

**Comment by SeaHOH** [comment]
>哥们你那边方便远程不，要不远程一下，teamviewer

其实可以这样，但是我是不会这么做的。。。

**Comment by Felixchen1024** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.ngix.ne.kr
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

**Comment by Felixchen1024** [comment]
自己办公室一台和家里2台基本就默认安装就OK，这台新的办公笔记本死活不行，有点奇怪

**Comment by AnyWAT** [comment]
再回看：+XX-Net诊断信息

**Comment by Felixchen1024** [comment]
**1、IPV6设置好是这样的：**
C:\WINDOWS\system32>ping teredo.managemydedi.com

正在 Ping teredo.managemydedi.com [42.123.125.237] 具有 32 字节的数据:
来自 42.123.125.237 的回复: 字节=32 时间=59ms TTL=53
来自 42.123.125.237 的回复: 字节=32 时间=58ms TTL=53
请求超时。
来自 42.123.125.237 的回复: 字节=32 时间=62ms TTL=53

42.123.125.237 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 58ms，最长 = 62ms，平均 = 59ms

**2、打开start.bat之后是这样的：**
C:\WINDOWS\system32>ping teredo.managemydedi.com
Ping 请求找不到主机 teredo.managemydedi.com。请检查该名称，然后重试。

什么情况。。。

**Comment by Felixchen1024** [comment]
IPv4 域名连接测试 |   | 成功 (0.914s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 失败 (0.158s)
双栈域名连接测试 |   | 成功 (0.915s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (1.919s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (0.701s)
无域名 IPv6 连接测试 |   | 失败 (0.012s)
IPv6 大数据包传输测试 |   | 失败 (0.300s)
测试运营商 DNS 是否接入 IPv6 |   | 成功 (0.705s)
查询 IPv4 运营商 |   | 成功 (0.746s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 失败 (0.312s)

IPV6不能使用？

**Comment by SeaHOH** [comment]
你实在是想用 IPv6 的话，说说 #10328 测试的结果是什么？

**Comment by Felixchen1024** [comment]
是否先暂时关闭 teredo 客户端（IPv6）再进行测试？（Y/N）n
('try bind local port:', 4385)
Starting probe NAT type...
NAT 类型是 restricted。
Starting evaluate servers...
157.56.149.60 ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com', 'win1711.ipv6.microsoft.com'] 229ms
195.140.195.140 ['teredo.trex.fi'] 296ms
217.17.192.217 ['teredo.iks-jena.de'] 468ms
83.170.6.76 ['teredo.remlab.net', 'teredo-debian.remlab.net'] timedout
42.123.125.237 ['teredo.ngix.ne.kr', 'teredo.autotrans.consulintel.com', 'teredo.managemydedi.com', 'teredo.ipv6.microsoft.com'] timedout

经检测，推荐服务器是 ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com', 'win1711.ipv6.microsoft.com'].
你想要将 teredo 服务器设置为本测试的推荐值吗？（Y/N）

PS:是我服务器没选对？

**Comment by SeaHOH** [comment]
检测看起来没问题。
你开防火墙没有？

**Comment by SeaHOH** [comment]
这几个都可以用
>157.56.149.60 ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com', 'win1711.ipv6.microsoft.com'] 229ms
195.140.195.140 ['teredo.trex.fi'] 296ms
217.17.192.217 ['teredo.iks-jena.de'] 468ms

**Comment by Felixchen1024** [comment]
有开防火墙，WIN10自带的防火墙

**Comment by AnyWAT** [comment]
🙃兜了一大圈，下图重点文字解决：
![image](https://user-images.githubusercontent.com/37962734/39162481-46eca246-47a8-11e8-9b6a-4ede7e5f9ec7.png)

**Comment by Felixchen1024** [comment]
尴尬了，重启又挂了。。@AnyWAT

类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:...
   默认网关. . . . . . . . . . . . . : ::
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

XX-Net Status:(你可以尝试 开启IPv6 或 使用X-Tunnel。???)

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:172 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by Felixchen1024** [comment]
感谢两位老司机啦，目前没连上的情况下，运行脚本改一下服务器，然后重启XXNET一般可以连上了
