### ISSUE TITLE
【已解决】3.11.9，Google youtube 都不能登陆，求救

### ISSUE THREAD

**Issue by ysjlion** [XX-net/XX-Net#10537]
我是3.11.9的版本，按照#10349 正确设置也没用，浏览器提示cookie禁用，我cookie一直都开的，什么毛病？

![qq 20180424103338](https://user-images.githubusercontent.com/15059695/39163035-3078d324-47ab-11e8-8faf-acc0d72ff15c.png)
![qq 20180424103349](https://user-images.githubusercontent.com/15059695/39163046-39fccc5c-47ab-11e8-8831-236d676f9280.png)
![qq 20180424103449](https://user-images.githubusercontent.com/15059695/39163025-25faa44a-47ab-11e8-9b29-e4dd41e60852.png)
疑难杂症啊~~

**Comment by ezhyg** [comment]
我的都挂了
IPv4 状态 | Fail
-- | --
IPv6 状态 | Fail

**Comment by ysjlion** [comment]
@ezhyg 直接挂了好修，疑难杂症难治

**Comment by SeaHOH** [comment]
```
accounts.google.com
.youtube.com
```
在智能代理页面中设置直连，然后代理端口切换到智能代理。

**Comment by ysjlion** [comment]
@SeaHOH 😭智能代理页面在哪，xxnet里没有啊

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/Smart-Router-模块

**Comment by ysjlion** [comment]
@SeaHOH 我X-Tunnel和Smart Router模块都没开，Smart Router从来没用过，汗~
是不是直连框里填那两个网址，然后SwitchyOmega新建代理模式监听8086？

**Comment by SeaHOH** [comment]
不用 X-Tunnel 可以不开，但 Smart Router 还是比较好用的。
>是不是直连框里填那两个网址，然后SwitchyOmega新建代理模式监听8086？

是的，整个情景模式也可以。

**Comment by ysjlion** [comment]
@SeaHOH  大神，还是没用，切换8086，谷歌主页可进，点击sign in就说无法连接了，哪里出错了吗？

点击sign in无法连接（回到8087又可以，但还是无法登录）：
![qq 20180424115843](https://user-images.githubusercontent.com/15059695/39165485-3ca9f3c4-47b7-11e8-8baa-33f89c6bc4a1.png)

刚新建的8086模式，没错吧
![qq 20180424115923](https://user-images.githubusercontent.com/15059695/39165504-4c27c0ba-47b7-11e8-8ea7-99c38b81d08d.png)

**Comment by ysjlion** [comment]
@SeaHOH 我试了，代理情景为8086，删除直连两个网址，sign in登录页面可以进，但输入帐号密码后还是提示cookie的信息。如果添加直连，登录页面又无法访问，等于accounts.google.com就没走代理？不解

**Comment by ysjlion** [comment]
@SeaHOH
Smart router 的日志：

Apr 24 12:25:06.419 - [DEBUG] domain user direct to accounts.google.com:443 except:ConnectFail()

Apr 24 12:25:06.419 - [INFO] domain user ['direct'] to accounts.google.com:443 fail

Apr 24 12:25:06.434 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:07.100 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:07.102 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:07.316 - [DEBUG] domain user direct to accounts.google.com:443 except:ConnectFail()

Apr 24 12:25:07.316 - [INFO] domain user ['direct'] to accounts.google.com:443 fail

Apr 24 12:25:07.355 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:07.691 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:07.926 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:07.927 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:08.183 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:08.205 - [DEBUG] host:clients4.google.com:443 do gae

Apr 24 12:25:09.413 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:09.558 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:11.424 - [DEBUG] domain user direct to accounts.google.com:443 except:ConnectFail()

Apr 24 12:25:11.424 - [INFO] domain user ['direct'] to accounts.google.com:443 fail

Apr 24 12:25:12.459 - [DEBUG] domain user direct to accounts.google.com:443 except:ConnectFail()

Apr 24 12:25:12.459 - [INFO] domain user ['direct'] to accounts.google.com:443 fail

Apr 24 12:25:15.276 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:16.607 - [DEBUG] host:api.shodan.io:443 do gae

Apr 24 12:25:16.622 - [DEBUG] host:api.shodan.io:443 do gae

**Comment by SeaHOH** [comment]
专门重新登录了一次，大概是这个原因：
不要用智能代理了，还是先前那样用就行。
但是要把 `myaccount.google.com` 也加入你顶楼贴的最后一个 json 里面。

**Comment by SeaHOH** [comment]
```
.googleusercontent.com
www.google.com
apis.google.com
```
这几个也加入试试
其他也有遇到这个的，一般是换其他代理登录，然后切换回来。

**Comment by ysjlion** [comment]
@SeaHOH 不行，唉不知道什么问题，估计还是有bug，我用goproxy的quic就能登录，先用着吧，有点不方便，等更新修复了 @xxnet

**Comment by SeaHOH** [comment]
我正在查，暂时看不出来。

**Comment by SeaHOH** [comment]
贴个 gae_proxy 的日志看看，要登录的那段。

**Comment by ysjlion** [comment]
@SeaHOH
这是从打开谷歌首页，进去sign in，输入帐号密码登录，显示cookie信息的日志的那段：


Apr 24 14:47:01.227 - [DEBUG] recheck_ip:2001:3b8:101:3a::11 restore ok

Apr 24 14:47:01.227 - [DEBUG] 2001:3b8:101:3a::11 worker close:keep alive

Apr 24 14:47:01.882 - [DEBUG] create_ssl update ip:2001:c28:1:38::e time:4007 h2:0 sni:meat-wood-evening.ml, host:

Apr 24 14:47:02.258 - [DEBUG] recheck_ip:2001:b032:101:1::10 restore ok

Apr 24 14:47:02.258 - [DEBUG] 2001:b032:101:1::10 worker close:keep alive

Apr 24 14:47:04.476 - [DEBUG] create_ssl update ip:2001:3b8:201:8::12 time:4414 h2:0 sni:wealthcontract.us, host:wujiaqian2.appspot.com

Apr 24 14:47:06.738 - [DEBUG] DIRECT GET https://www.google.com/

Apr 24 14:47:07.236 - [DEBUG] GAE POST /chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D from:127.0.0.1:51975

Apr 24 14:47:08.095 - [INFO] DIRECT t:1357 s:65447 200 www.google.com /

Apr 24 14:47:08.451 - [DEBUG] create_ssl update ip:2001:b032:5d01::11 time:1207 h2:0 sni:specialisthorror.ml, host:

Apr 24 14:47:08.496 - [DEBUG] create_ssl update ip:2001:3b8:101:3a::11 time:1739 h2:0 sni:definitionindicationsecretary.net, host:

Apr 24 14:47:08.675 - [INFO] GAE t:1437 s:448 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D 0:start_request,0:get_task(14),0:get_worker(0):2001:b032:8100::10,0:h1_req,1:h1_req_sended,1434:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:613],:0

Apr 24 14:47:08.677 - [DEBUG] GAE POST /chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D from:127.0.0.1:51975

Apr 24 14:47:08.946 - [DEBUG] create_ssl update ip:2001:b000:182:c100::13 time:1202 h2:0 sni:advantagead.net, host:

Apr 24 14:47:09.031 - [DEBUG] DIRECT GET https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/

Apr 24 14:47:09.084 - [DEBUG] create_ssl update ip:2001:b032:5d01::c time:1197 h2:0 sni:rent.dance.net, host:

Apr 24 14:47:10.113 - [INFO] GAE t:1435 s:595 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D 0:start_request,0:get_task(1),0:get_worker(0):2001:b032:8100::10,0:h1_req,0:h1_req_sended,1432:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:716],:1

Apr 24 14:47:10.115 - [DEBUG] GAE POST /chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D from:127.0.0.1:51975

Apr 24 14:47:10.346 - [DEBUG] create_ssl update ip:2001:b032:8102:1::c time:1164 h2:0 sni:affair.pitch.com, host:signupforafreetrialf.appspot.com

Apr 24 14:47:10.885 - [DEBUG] create_ssl update ip:2001:b032:8102:1::10 time:1199 h2:0 sni:matter.hearing.ml, host:frtspot.appspot.com

Apr 24 14:47:11.354 - [DEBUG] create_ssl update ip:2001:b032:c100:2::13 time:1167 h2:0 sni:otherpossessionmemory.org, host:maxqq0.appspot.com

Apr 24 14:47:11.549 - [INFO] GAE t:1433 s:537 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D 0:start_request,0:get_task(1),0:get_worker(0):2001:b032:8100::10,0:h1_req,0:h1_req_sended,1432:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:676],:0

Apr 24 14:47:11.614 - [DEBUG] create_ssl update ip:2001:b032:2101::e time:1134 h2:0 sni:bitter-airline.com, host:dellqx8.appspot.com

Apr 24 14:47:12.506 - [DEBUG] create_ssl update ip:2001:2f8:0:15::f time:4236 h2:0 sni:forever.championship.org, host:

Apr 24 14:47:12.836 - [INFO] DIRECT t:3805 s:327019 200 accounts.google.com /ServiceLogin?hl=en&passive=true&continue=https://www.google.com/

Apr 24 14:47:13.038 - [DEBUG] GAE POST /tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:52020

Apr 24 14:47:13.665 - [INFO] GAE t:626 s:39 POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome 0:start_request,0:get_task(2),0:get_worker(0):2001:b032:8100::10,0:h1_req,0:h1_req_sended,624:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:545],:0

Apr 24 14:47:13.682 - [DEBUG] report_connect_fail:2001:b032:8102:1::e

Apr 24 14:47:13.682 - [DEBUG] connect 2001:b032:8102:1::e fail:error("conn fail, sni:task.procedure.manufacturer.net, top:signupforafreetrialf.appspot.com e:timeout('timed out',)",)

Apr 24 14:47:14.943 - [WARNING] 2001:b032:8102:1::c host:signupforafreetrialf.appspot.com head fail status:503

Apr 24 14:47:14.943 - [DEBUG] report_connect_fail:2001:b032:8102:1::c

Apr 24 14:47:15.335 - [DEBUG] DIRECT POST https://accounts.google.com/_/signin/sl/lookup?hl=en&_reqid=53236&rt=j

Apr 24 14:47:15.730 - [INFO] DIRECT t:394 s:1132 200 accounts.google.com /_/signin/sl/lookup?hl=en&_reqid=53236&rt=j

Apr 24 14:47:16.097 - [DEBUG] GAE POST /tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:52020

Apr 24 14:47:16.544 - [DEBUG] create_ssl update ip:2001:b032:5d01::e time:1205 h2:0 sni:grandmotherpain.us, host:

Apr 24 14:47:16.703 - [DEBUG] recheck_ip:2001:b032:8102:1::c restore ok

Apr 24 14:47:16.703 - [DEBUG] 2001:b032:8102:1::c worker close:keep alive

Apr 24 14:47:17.046 - [DEBUG] create_ssl update ip:2001:b032:2101::12 time:1206 h2:0 sni:kitchen-spare-culture.net, host:

Apr 24 14:47:17.073 - [DEBUG] DIRECT POST https://accounts.google.com/_/signin/sl/challenge?hl=en&_reqid=153236&rt=j

Apr 24 14:47:17.296 - [DEBUG] create_ssl update ip:2001:b032:c100:1::12 time:1195 h2:0 sni:good-meal.ml, host:twitter1-1239.appspot.com

Apr 24 14:47:17.516 - [DEBUG] create_ssl update ip:2001:b000:188:c100::f time:1176 h2:0 sni:parentpromisetear.ml, host:

Apr 24 14:47:17.574 - [INFO] DIRECT t:500 s:201 200 accounts.google.com /_/signin/sl/challenge?hl=en&_reqid=153236&rt=j

Apr 24 14:47:17.583 - [DEBUG] DIRECT POST https://accounts.google.com/_/common/diagnostics/?hl=en&_reqid=253236&rt=j

Apr 24 14:47:17.608 - [DEBUG] DIRECT GET https://accounts.google.com/CheckCookie?hl=en&chtml=LoginDoneHtml&continue=https%3A%2F%2Fwww.google.com%2F&gidl=EgIIAA

Apr 24 14:47:17.768 - [DEBUG] create_ssl update ip:2001:b032:2101::13 time:1166 h2:0 sni:safety-gear.ml, host:rowtheboat22.appspot.com

Apr 24 14:47:18.275 - [DEBUG] create_ssl update ip:2001:b032:7101:1::10 time:1159 h2:0 sni:championownerconnection.net, host:signupforafreetriale.appspot.com

Apr 24 14:47:18.367 - [INFO] GAE t:2270 s:43 POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome 0:start_request,0:get_task(3),0:get_worker(0):2001:b032:2101::e,520:h1_req,0:h1_req_sended,1746:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:197],:1

Apr 24 14:47:18.505 - [INFO] DIRECT t:921 s:63 200 accounts.google.com /_/common/diagnostics/?hl=en&_reqid=253236&rt=j

Apr 24 14:47:19.240 - [DEBUG] create_ssl update ip:2001:8002:e21:ef03::10 time:1192 h2:0 sni:profile.focus.suggestion.com, host:

Apr 24 14:47:19.261 - [DEBUG] create_ssl update ip:2001:b032:8103:1::13 time:1174 h2:0 sni:vehiclerush.net, host:

Apr 24 14:47:19.705 - [DEBUG] create_ssl update ip:2001:b032:8102:1::c time:1187 h2:0 sni:march-sale-brown.us, host:

Apr 24 14:47:19.765 - [DEBUG] create_ssl update ip:2001:b000:1e0:c101::c time:1178 h2:0 sni:quit.expression.resist.net, host:

Apr 24 14:47:20.282 - [DEBUG] create_ssl update ip:2001:8002:e21:e101::d time:1190 h2:0 sni:wing-target-entry.org, host:

Apr 24 14:47:20.795 - [INFO] DIRECT t:3187 s:6426 400 accounts.google.com /CheckCookie?hl=en&chtml=LoginDoneHtml&continue=https%3A%2F%2Fwww.google.com%2F&gidl=EgIIAA

Apr 24 14:47:22.593 - [DEBUG] GAE POST /chrome-sync/command/?client=Google+Chrome&client_id=923%2BXvMRUDKMPpJdqwXL%2BQ%3D%3D from:127.0.0.1:52100

**Comment by ysjlion** [comment]
json里加入了：
  "hosts_direct_endswith": [
    "accounts.google.com", 
    "myaccount.google.com", 
    ".googleusercontent.com", 
    "www.google.com", 
    "apis.google.com"
  ]

**Comment by SeaHOH** [comment]
我已经看到了。上面这段日志先删掉，ID 没隐藏。

**Comment by SeaHOH** [comment]
Ok，终于搞明白了。专门把我的工具也改成 IPv6 来测试的。。。
```json
{
"hosts_gae": [
"accounts.google.com"
],
"hosts_direct": [
"www.google.com",
"www.youtube.com"
]
}
```

**Comment by SeaHOH** [comment]
我以前一直以为直连就能行，没想到。。。
关键是我换一下上网方式比较麻烦，就没实际试过 IPv6。

**Comment by hjfeng1988** [comment]
```
{
"hosts_gae": [
"accounts.google.com"
],
"hosts_direct_endswith": [
"www.google.com",
".youtube.com"
]
}
```

这一段放哪里来着，没看明白。

**Comment by luyuanshao** [comment]
同样的问题，我也想知道这段放在哪里。

**Comment by SeaHOH** [comment]
`data/gae_proxy/config.json` 注意格式，改错启动不了，自己谷歌 `json 格式 检查`。

建议不会的改这个文件 `code/default/gae_proxy/local/config.py`，格式要求没那么严格，照着旁边改就行。

**Comment by hjfeng1988** [comment]
搞定，可以登录了。thanks

**Comment by zk-kevin** [comment]
@SeaHOH @hjfeng1988 @luyuanshao 请问我在data/gae_proxy/ 下没找到config.json 是什么情况？同时code/default/gae_proxy/local/config.py 用什么进行修改？

**Comment by ysjlion** [comment]
@zk-kevin 没有json重新下载最新版再运行，都可用记事本编辑

**Comment by zk-kevin** [comment]
@ysjlion 问题已解决，非常感谢

**Comment by SeaHOH** [comment]
借个楼， AnyWAT 下面有回复
161eca3670f9575a87ae1496d1f889c07a6a1c57

**Comment by lsq726** [comment]
改错的确启动不了..config.json config.py都没改正确..汗...

**Comment by yydxwt** [comment]
@SeaHOH 改了依旧不行　我是重装浏览器　youtube就登不上去了　google可以

**Comment by SeaHOH** [comment]
先登录 google，然后 youtube 点登录。

**Comment by xiaoteai** [comment]
@SeaHOH   能出墙  等不了 账号 挺闹心的   能不能来个 有图有长相

**Comment by SeaHOH** [comment]
>Ok，终于搞明白了。专门把我的工具也改成 IPv6 来测试的。。。
我以前一直以为直连就能行，没想到。。。
关键是我换一下上网方式比较麻烦，就没实际试过 IPv6。

实在登录不了的，登录时切换代理。

**Comment by xiaoteai** [comment]
换了 多走一步 验证邮箱  最后一步 not

**Comment by lsq726** [comment]
@SeaHOH 能 细讲一下怎么修改么?

因为改了了config.json 或config.py 都启动不了..xx

**Comment by SeaHOH** [comment]
>实在登录不了的，登录时切换代理。

恢复修改 @lsq726

**Comment by SeaHOH** [comment]
等待更新

**Comment by yydxwt** [comment]
@SeaHOH  解决了　把xx-net的旧IP都删了　重新扫描就好了

**Comment by horigen** [comment]
在3.12.11遇到同样的重新定向问题，尝试了很多方法无效，最后通过在config.json中加入如下代码解决：
  "hosts_direct": [
    "accounts.google.com",
    "mail.google.com"
  ],
  "hosts_gae": [
  ]
