### ISSUE TITLE
一直显示连接尚未建立

### ISSUE THREAD

**Issue by gankbd** [XX-net/XX-Net#10531]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3013 ipv4:22 ipv6:10
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1066
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by QGB** [comment]
连接服务器失败：session server login fail:602

**Comment by gankbd** [comment]
请问怎么解决？

**Comment by SeaHOH** [comment]
>ipv6-status: Fail

https://github.com/XX-net/XX-Net/wiki/IPv6-Win7-小白指引

**Comment by XiGui2017** [comment]
试试将DNS改为9.9.9.9

**Comment by AnyWAT** [comment]
WIN10一直连接尚未建立。 #10532
