### ISSUE TITLE
完全不用上传你的任何账户信息，因为这个根本就是假的

### ISSUE THREAD

**Issue by milophen** [XX-net/XX-Net#1053]
![default](https://cloud.githubusercontent.com/assets/4685617/9923610/9b66ddc6-5d29-11e5-9ed1-cfedde978c02.png)
随便输入一串字母都会显示为working appids，不知道作者收集大家的账户做什么。

**Comment by milophen** [comment]
大家不要再上当了。

**Comment by milophen** [comment]
![Uploading 新建位图图像.png…]()

**Comment by pnjgyl** [comment]
呵呵, appid保存在本地你为什么说作者"收集"呢??????你看哪行代码收集了?
还有你随便输的appid能用吗?你确定都能用吗? 
麻烦您先验证再做结论. 麻烦您做结论的时候顺手贴下证据. 阴谋论可以用来解释和证明一切事物, 好吗?

**Comment by xxnet** [comment]
对于这种不了解清楚不文明讨论的，只能作为五毛攻击进行block

**Comment by milophen** [comment]
刚才那两个应该出现在not exist apps下吧？怎么判断的？我哈希一串字母都可以。

**Comment by pnjgyl** [comment]
作者大大不好意思, 虽然close了. 但我还是想回复一下.

我随便试了一个appid, 的确会放在working里面. 如下
Property	Value
working appids	  uiuyhiu87876987980tewr
Out of Quota appids	
Not Exist appids	
而且会有link, 如下
Property	Value
Google IP num	2955
100th IP handshake(ms)	4795
connected link(帮助)	8,1
scaning ip thread num	0
block stat(帮助)	OK

但是问题来了, 我们可以翻墙了吗? no! 为什么, 因为appid根本就不可用, 访问Google的时候提示 :无法连接到代理服务器ERR_PROXY_CONNECTION_FAILED, 并且日志也会报错的create ssl fail之类的. 这样子你懂了吗楼主? 
我们只能推论出 working appids  和 Not Exist appids 这个地方的判断有问题, 而不能判断出
"完全不用上传你的任何账户信息，因为这个根本就是假的" 这种推论, 这样可以说服你了?????
