### ISSUE TITLE
为什么最新版Chrome 直连不能播放中国大学Mooc 网站的视频课？

### ISSUE THREAD

**Issue by atozlearn** [XX-net/XX-Net#10545]
https://www.icourse163.org/
中国大学Mooc 这不是在墙内 吗？chrome更新之后需要goagent 代理才能看？
如果打开XX -Net 直连就不可以看，显示：**网络不给力，请重试** 换个浏览器都可流畅播放，网络绝对没问题。
这是为什么？大神们求解~ 

**Google Chrome 已是最新版本
版本 66.0.3359.117（正式版本） （64 位）**

**Comment by wszgrcy** [comment]
可以,正常,不用任何工具

**Comment by SeaHOH** [comment]
CERT_SYMANTEC_LEGACY
赛门铁克

**Comment by shenthought** [comment]
今天测试又正常了_(:з)∠)_

**Comment by atozlearn** [comment]
我把SwitchyOmega 拓展删了又装一遍，正常了。好像先前用某个模式播放看到资源未加载，添加了什么模式，代理规则被我改混了。

**Comment by SeaHOH** [comment]
v.stu.126.net
这个证书是赛门铁克颁发的，记得之前谷歌的声明不？

**Comment by atozlearn** [comment]
停止信任赛门铁克所有证书？

CERT_SYMANTEC_LEGACY
你上面这条评论是什么意思？可以手动导入证书解决这种资源未加载的问题？
