### ISSUE TITLE
最新版Chrome好像无法导入证书，大家是这样的情况吗？

### ISSUE THREAD

**Issue by kaishuibaicai** [XX-net/XX-Net#10547]
昨天随手点了个检查最新版的Chrome， 估计浏览器后台更新了，今天再打开，之前的证书就掉了，手动装，提示安装成功，但是证书列表里并没有相关证书。 该怎么办呢？

**Comment by SeaHOH** [comment]
系统？

**Comment by kaishuibaicai** [comment]
是win10的系统 64位

**Comment by SeaHOH** [comment]
重新管理员权限运行一次 XX-Net

**Comment by ORO44** [comment]
是用SwitchyOmega的吗？是的话把调成代理模式试试，我的用自动代理也是会出现证书失败。

**Comment by kaishuibaicai** [comment]
哈哈，是的原来浏览器升级之后，switchyOmega须要重新调到代理模式，哈哈。、
