### ISSUE TITLE
最近才发现的问题，用goagent和xx-net上twitter

### ISSUE THREAD

**Issue by sonomon** [XX-net/XX-Net#10542]
无法使用搜索功能，搜索什么都是无搜索结果，公众app或者我自己申请的app都是这样。
同理，4shared下载东西会出现Signature is invalid。
换其他梯子则一切正常。
是证书的问题，还是部分网站把这种翻墙方式拉黑了？
![qq 20180424161756](https://user-images.githubusercontent.com/29676038/39174851-5ce94648-47db-11e8-8a7a-d7e3df02bf01.png)
![qq 20180424161930](https://user-images.githubusercontent.com/29676038/39174857-6038fb86-47db-11e8-9761-f4276eb5cfad.png)

还补充一下，最近goagent似乎彻底跪了，以前勉强能搜索出几个ip来用，现在只能上google，其他网站均加载不出来，日志上是白字的502错误。
以前也碰到过goagent只能上google，其他网站502，重新部署app就好了，现在该无效的还是无效。
经过反复搜索，个人认为是搜索到的google ip，443端口关闭了。
![qq 20180424162146](https://user-images.githubusercontent.com/29676038/39175025-d51b39e6-47db-11e8-9c26-ae1243bbb79c.png)

**Comment by SeaHOH** [comment]
搜索没结果是 twitter 针对 GAE 平台的策略。

至于 goagent，你居然还能用？？！IPv4 还是 IPv6？
IPv4 的话，麻烦发个 IP 我研究一下。

**Comment by SeaHOH** [comment]
不会是 SNI 吧。。。那就算了

**Comment by sonomon** [comment]
@SeaHOH 172.217.161.150|172.217.161.41|172.217.166.168|172.217.166.177|172.217.166.129|172.217.161.69|172.217.161.73|172.217.166.118|172.217.166.54|172.217.166.86|172.217.164.86|108.177.122.119|216.58.215.214|172.217.13.22|216.58.215.22|172.217.14.118|216.58.215.118|172.217.17.7|216.58.215.86|172.217.168.168|172.217.168.226|172.217.168.194|172.217.168.214|172.217.162.41|216.58.207.246|172.217.162.86|172.217.169.130|172.217.169.98
还是GoGoTester跑出来的ip，不过不同地区不同网络并不通用吧，我公司跑出来的ip拿回家就没用了，得重新跑。
谷歌没压力，其他网站就歇菜。
![qq 20180424164525](https://user-images.githubusercontent.com/29676038/39176302-106042d2-47df-11e8-897c-ef5961e79fab.png)
![qq 20180424164259](https://user-images.githubusercontent.com/29676038/39176308-13245b3e-47df-11e8-8727-9ce70dc8db87.png)

**Comment by SeaHOH** [comment]
居然不是 SNI，我来看看，这届墙不行啊。

**Comment by SeaHOH** [comment]
这不是很熟悉嘛，墙怎么了？？

**Comment by SeaHOH** [comment]
@sonomon 不介意要重新部署 AppID 的话，可以用我的工具，点头像可以看到。

**Comment by sonomon** [comment]
@SeaHOH  还是部署的问题吗，goagent确实无法部署了，xx-net部署了也没有卵用，是GotoX吗，我试一试

**Comment by sonomon** [comment]
@SeaHOH 那就没办法了，goagent自带工具已经无法部署了，必定404，也许可以想办法用google自带的工具？
听你的语气似乎goagent已经死了很久了，但我因为一个游戏的原因是一个重度翻墙爱好者，从2012年到今天几乎没有怎么中断过，goagent在我手上彻底没法用的也就是3月末期的事。

**Comment by sonomon** [comment]
@SeaHOH 那就没办法了，goagent自带工具已经无法部署了，必定404，也许可以想办法用google自带的工具？
听你的语气似乎goagent已经死了很久了，但我因为一个游戏的原因是一个重度翻墙爱好者，从2012年到今天几乎没有怎么中断过，goagent在我手上彻底没法用的也就是3月末期的事。

**Comment by sonomon** [comment]
@SeaHOH 我重新分别用goproxy和xx-net部署了一下两个app，按理来说xx-net也是用的goagent，但依旧悲催的不行。。。

**Comment by sonomon** [comment]
@SeaHOH 我重新分别用goproxy和xx-net部署了一下两个app，按理来说xx-net也是用的goagent，但依旧悲催的不行。。。

**Comment by SeaHOH** [comment]
你没看见发布页的介绍么？有提供部署工具。

**Comment by SeaHOH** [comment]
>goagent在我手上彻底没法用的也就是3月末期的事。

这批 IP 一直没遭封么，大家居然没发现。。。

**Comment by xugaohui** [comment]
@sonomon 扫描ip建议用这个 https://github.com/Kisesy/gscan_quic/releases

**Comment by asmosn** [comment]
@sonomon 搞毛啊！还在用360浏览器？360公司是GFW主力帮手

**Comment by xugaohui** [comment]
这个贴子不错,收集好上面的ip段.
再补充下
108.177.122.0/24
172.217.13.0/24
172.217.14.0/24
172.217.15.0/24
172.217.16.0/24
172.217.17.0/24
172.217.161.0/24
172.217.162.0/24
172.217.163.0/24
172.217.164.0/24
172.217.166.0/24
172.217.168.0/24
172.217.169.0/24
216.58.207.0/24
216.58.215.0/24
tls模式上面ip段有.quic就很多ip段有.

**Comment by caitianzhu** [comment]
User Agent Switcher 切换苹果，安卓的UA就可以搜索了

**Comment by gggccc44** [comment]
我就一直用360se啊，还有火狐，谷歌原生那种ui太丑，难用，其他第三方谷歌内核的也是谷歌ui丑的b爆

**Comment by no-name2017** [comment]
居然还有人觉得美丑比安全更重要的，厉害了，无解

**Comment by roc1010kmt** [comment]
twitter還沒有ipv6地址呢吧？

**Comment by wpyok500** [comment]
tls的ip，现在gogent，goprxy除了google、youtube、谷歌自家的东西，像faocebook、twitter都会502 Bad Gateway 
![image](https://user-images.githubusercontent.com/14154547/39680756-c734fd8a-51d6-11e8-96d0-0bdae5b892af.png)

**Comment by gggccc44** [comment]
xx-net上推用火狐没问题（火狐别用墙内版，我都用的便携版），企鹅家的管家确实是垃圾

![default](https://user-images.githubusercontent.com/1776304/39920594-38456ade-554a-11e8-8068-3644bd4fbf45.jpg)


@no-name2017 你认为安全不一定就安全，关键看你怎么用，要搞事用Tor Browser
