### ISSUE TITLE
新发布的版本使用后

### ISSUE THREAD

**Issue by hongkonghot** [XX-net/XX-Net#10558]
等待扫描IP，建议开启IPv6。

IPv4 状态 | OK
IPv6 状态 | OK

等待很久后依然 IPv6 IP数 | 0 

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.iks-jena.de
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.10.101:50252
外部 NAT 映射    : **************:26017

**Comment by SeaHOH** [comment]
如果是升级保留配置，删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

**Comment by xpf7622** [comment]
IP v4  V6 OK ,CA失败，重新导入后，还是不行。是不是新版本没更新CA文件？

**Comment by xxnet** [comment]
​CA 文件是在第一次启动时生成的，升级不会修改CA文件。
CA失败，先看看代理是否正常，请贴出诊断信息分析

**Comment by SeaHOH** [comment]
关闭后仍可回复
