### ISSUE TITLE
安卓网页版推特无法加载图片和视频了？你们正常吗？

### ISSUE THREAD

**Issue by asmosn** [XX-net/XX-Net#10553]
不知是xndroid原因还是推特网也原因？

**Comment by asmosn** [comment]
![screenshot_2018-04-26-16-34-14-599_com yandex browser alpha](https://user-images.githubusercontent.com/9925193/39296550-cb05b1c2-4973-11e8-9987-0f2820d6d725.png)

**Comment by asmosn** [comment]
貌似浏览器的原因

**Comment by asmosn** [comment]
有可能，也可能是推特网站后台更新导致，因为我手机之前看推特都正常

**Comment by AnyWAT** [comment]
除非版本缺陷，这错那误貌似代理速度的锅😜试试🤣臭大街法则 https://github.com/XX-net/XX-Net/issues/10515#event-1587262313

**Comment by xxnet** [comment]
@AnyWAT
​规律明显的，一般和速度没有关系。

@Arphox
 Twitter 显示异常，一般是css或js 加载出问题。
 在浏览器中按F12，调出调试窗口，切换到网络，然后刷新页面，看哪个资源没有加载成功

**Comment by carlchan99** [comment]
反馈一下，我在ubuntu中删除adobe-flashplugin、adobe-flash-properties-gtk、adobe-flash-properties-kde，现在chromium中twitter能播放视频了，应该是现在的网页（html5？）无须adobe-flash的插件吧。

**Comment by AnyWAT** [comment]
网页（html5？）无须adobe-flash的插件👍
