### ISSUE TITLE
全局PAC智能代理无效

### ISSUE THREAD

**Issue by wygbio** [XX-net/XX-Net#10552]
以前的版本不安装插件，直接选“全局PAC智能代理”即可，最近的版本问什么要“检查浏览器代理设置”，必须选全局通过GAEProxy才能上网？

**Comment by Liu-KL** [comment]
![image](https://user-images.githubusercontent.com/33389391/39309811-752196c2-499b-11e8-90e4-965c7d626edd.png)

**Comment by Liu-KL** [comment]
我也是这个问题。。。还不知道怎么解决

**Comment by AnyWAT** [comment]
前提：http://127.0.0.1:8085/?module=launcher&menu=config 启用 Smart Router：ON

**Comment by SeaHOH** [comment]
显示**请检查代理设置**是否影响实际使用？

**Comment by atozlearn** [comment]
没启用插件时候，只开XX-Net 全局代理模式，可以访问谷歌。
启用插件，同时XX-net 全局代理，插件如选择【直接连接】模式就会出现“请检查浏览器代理设置" 的提醒。这时候翻不出去，改成【系统代理】或者【GAE】的就可以了。

**Comment by SeaHOH** [comment]
>127.0.0.1:8086/proxy.pac这个文件还有但怎样就是连接不上

上个图吧，没看明白说的啥。连接不上什么？

**Comment by dylanleesky** [comment]
@SeaHOH    奇了怪了。。。我折腾一圈，把Omega插件清了。重新安装，重新设置规则，XX开启智能路由功能，能获取到，关了智能路由，却获取不到。。。。有些莫名其妙。。。目录中搜索proxy.pac有好几个，data中有，code/版本号目录中也有。。。但0.1:8086下的就是木有。。。
![1](https://user-images.githubusercontent.com/14555503/39405228-2f581f22-4bd4-11e8-8159-049a240b7f3e.png)

**Comment by SeaHOH** [comment]
当前版本，PAC 由智能路由模块提供。

**Comment by dylanleesky** [comment]
@atozlearn  
直接连接，意思就是不通过代理，直接连接互联网；
智能PAC是通过内置规则自动连代理或者直接连接互联网；
GAE就是全局，不管什么地址，统统走代理。

所以，直接连接是不走代理的当然就会无法出国喽。
XX的全局代理，就是修改的IE的局域网设置，绝大部分软件的联网模式默认是按照IE的设置进行联网。但现在很多浏览器为了自己的稳定性，默认是不管IE代理设置如何直接连接互联网。chrome，火狐，默认是按照IE设置，插件里设置直接，就是跳过默认设置（IE的），自成联网体系。

**Comment by dylanleesky** [comment]
@SeaHOH  那3.10.4呢？上周还好好的呢，从来都是取消代理或者智能PAC模式（电脑垃圾总感觉智能路由会增大CPU消耗），但今天就忽然发现智能模式不行了。前几天倒是没怎么上网所以不清楚具体由哪天开始出错的。

**Comment by AnyWAT** [comment]
目录中搜索proxy.pac有好几个，data中😜木😜有
XX开启智能路由功能，能获取到，关了智能路由，却获取不到：
前提：http://127.0.0.1:8085/?module=launcher&menu=config 模块管理，启用 Smart Router：ON，否则，下图划线部分8086端口被禁用
![image](https://user-images.githubusercontent.com/37962734/39405326-20116ff8-4bd6-11e8-8857-4e55d9317e9d.png)

**Comment by dylanleesky** [comment]
@AnyWAT    哎呦我去，那不对啊。上周我很肯定我一直用的就是pac模式联网的，并且没有开启智能路由模块啊。而且版本依旧是3.10.4的。XX全局智能PAC模式。联网正常的啊

**Comment by SeaHOH** [comment]
我觉得你可能是记错或搞混了。

**Comment by AnyWAT** [comment]
😂启用 Smart Router：OFF，全局PAC智能代理不行，浏览器内PAC代理🆗

**Comment by dylanleesky** [comment]
@SeaHOH 不会，这个我很肯定我用的是3.10.4或者更高不超过3.11.9的版本。我的历史版本中最低的就是3.10.4，并且早先由于和本机获取路由的IP6地址不兼容等等问题我一直固定使用的就是3.10.4。应该是有其他原因。我现在断网切回原先的系统中看下IE代理设置和谷歌插件的设置地址，或许能找到原因，但也有可能和现在的系统设置一样。

**Comment by dylanleesky** [comment]
@SeaHOH 这个应该不会的，我的omega设置默认是系统代理，XX今天之前一直是智能PAC，期间访问谷歌啥的一切正常。昨天在重做号的win10系统上安装的chrome，今天登陆账号同步浏览器数据时才发现自动模式无法联网，这才发现出了这个问题。XX的code目录里一直是3.10.4的目录名，这个是我手动当初改的。今天怀疑文件丢失啥的，重新放了一份原始3.10.4的文件进去，所以多了一个def的，这个def也是10.4的。。。可以看文件属性，也是22号生成的。所以这个可佐证我的记忆无错。而且今天在win10中打开xx后的默认设置也是智能pac，并且没有开智能路由模块这也能说明我之前用的一直是智能PAC模式。
至于为啥它能获取到8086端口的文件为啥后期也能使用智能pac，就当莫明奇妙吧。大神们没必要在这里费心了。这都是小问题不是啥大问题，虽然，我有些小纠结。着实不想开路由，因为感觉它会增加CPU等资源的消耗。。
![5](https://user-images.githubusercontent.com/14555503/39405634-097fe38c-4bdb-11e8-8c2e-db5720891e19.png)
![6](https://user-images.githubusercontent.com/14555503/39405635-0a8798e2-4bdb-11e8-9818-1d6be76ba1c0.png)

**Comment by AnyWAT** [comment]
着实不想开路由，因为感觉它会增加CPU等资源的消耗。。😂时常卡顿

**Comment by dylanleesky** [comment]
差不多就这感觉😂，在公司用一般的电脑这个模式联网时不顺畅，，，我家的电脑配置垃圾，一个破奔腾chrome窗口开十几个就开始卡U.这个智能路由一看规则那么繁琐，在加上在公司用着不顺畅，所以家里电脑就没开过智能路由，除了刚刚测试时。

**Comment by SeaHOH** [comment]
@dylanleesky 
你这是保存到浏览器配置里面，所以不开启智能代理也能使用。

**Comment by SeaHOH** [comment]
关闭后仍可回复
