### ISSUE TITLE
登陆谷歌账号显示  糟糕 您的浏览器似乎仅用了cookie

### ISSUE THREAD

**Issue by ppeng** [XX-net/XX-Net#10550]
![default](https://user-images.githubusercontent.com/16084934/39280015-492f512e-492f-11e8-9627-21215a3fcdda.JPG)
昨天还一切正常，不知道今天怎么了。不知道是什么的原因，过来请教一下。

**Comment by foho8080** [comment]
看这个  https://github.com/XX-net/XX-Net/issues/10537

**Comment by Daviddick** [comment]
我也出现了，求解决办法。换其他方式翻出去，登陆就没问题

**Comment by ppeng** [comment]
并不知道应该怎么办 @foho8080

**Comment by yydxwt** [comment]
我也是　重装了一下浏览器　youtube不能登陆了
