### ISSUE TITLE
Thinkpad Win10必须开机后必须重启IPv6才生效？

### ISSUE THREAD

**Issue by misterpoesy** [XX-net/XX-Net#10554]
ThinkPad，正常开机时“IPv6 状态 | Fail”，重启之后基本上都正常，每次都必须重启啊......
是不是ThinkPad的急速开机导致有什么东西未加载？

**Comment by GoodSake** [comment]
win8飘过

**Comment by liyq0307** [comment]
我也遇到过，应该怎么搞？

**Comment by AnyWAT** [comment]
试试：先禁用再启用网络

**Comment by dhxy5117** [comment]
@misterpoesy 我是T470 win10,情况和你一样，但是不用重启，禁用再启用就行了
netsh interface Teredo set state disable
netsh interface Teredo set state type=default
netsh interface teredo set state enterpriseclient server=default

**Comment by AnyWAT** [comment]
LS 试试三合一：管理权限运行 netsh int ipv6 set teredo enterpriseclient default

**Comment by xxnet** [comment]
​@QuocTroy
  成都电信的能封teredo GAE了？
  一个连接都没有建立起来吗？
  把诊断信息和GAE日志贴出来看

**Comment by AlyoshaMa** [comment]
1. 服务->IP helper->重启
2. 禁止网络适配器-->再开启网络适配器---->打开xx-net---> 链接成功or 失败  lol

**Comment by QuocTroy** [comment]
@xxnet 抱歉前几天有事，一直没上GitHub。诊断信息你看吧：
————————————————————————————————
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​试试 最新版  3.11.10

**Comment by LegendTian** [comment]
@xxnet 3.11.10也是一样，我得thinkpadx1 新版本也得重启打开ip转换服务
