### ISSUE TITLE
win10 XX-Net过一段时间要重新启动一下才能使用

### ISSUE THREAD

**Issue by ftgqzhengkai** [XX-net/XX-Net#10556]
最近2台电脑上都是这样，每次用一段时间，就会自动死了，要重新启动，IPv6 IP数最高也就500了！！！
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:4 used:undefined
worker: h1:47 h2:0
scan-ip-thread-num: 176
ip-quality: 279
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
等待新版发布
还有，不要追求 IP 数，这个并不是越多越好。
