### ISSUE TITLE
length of URL too long 是怎么回事？

### ISSUE THREAD

**Issue by DipperTheCoder** [XX-net/XX-Net#10569]
![default](https://user-images.githubusercontent.com/30572520/39403258-9989c6d2-4ba9-11e8-8423-6f6acb9febca.PNG)

如图
是从一个网站“Send to Messenger”时出现的

**Comment by SeaHOH** [comment]
GAE 平台有 URL 长度限制，facebook 又无法直连，你这个连接只能走 X-Tunnel 之类的其它代理了。

**Comment by SeaHOH** [comment]
不过看起来是重复重定向造成的，检测一下 cookies 是否开启以及正确。
