### ISSUE TITLE
[发布] 3.11.10 修复GAE_proxy 无法登陆google

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#10561]
新版特性：
* 修复bug： GAE_proxy 无法登陆google youtube
* X-Tunnel 性能优化

[下载](https://codeload.github.com/XX-net/XX-Net/zip/3.11.10)
已推送测试版更新

**Comment by proudmoore6770** [comment]
youtube gmail 都登不了。。。谢谢了 稳定版本什么时候出来？

**Comment by xxnet** [comment]
同样的代码，等大家反馈稳定了，就推送稳定升级。

你如果不放心，就另外下载一个试试。

**Comment by 722tzz** [comment]
之前通过在config中增加
"hosts_direct_endswith": [
    "www.google.com", 
    ".youtube.com"
  ]
解决的，升级后需要把config文件改回去吗？

**Comment by xxnet** [comment]
最新版3.11.10吗

**Comment by xpf7622** [comment]
IPV6 老是fail，怎么回事，不稳定。一会儿好，一会儿fail.

**Comment by xxnet** [comment]
​你是什么地区？
估计是受到干扰了。

可以试试增加扫描线程

**Comment by lsq726** [comment]
挺好..老版本都无法部署服务器端..这个版本可以用了.

**Comment by xxnet** [comment]
挺好..老版本都无法部署服务器端..这个版本可以用了.
>
谢谢反馈

**Comment by no-name2017** [comment]
回报X大，xndroid更新xx最新版后，IPV6搜索不到ip，IPV4倒是搜索到一个，能翻，哈哈

**Comment by xxnet** [comment]
​@no-name2017
  同样网络环境下，PC能搜到ipv6吗

**Comment by HustCoderHu** [comment]
要重新部署到 gae上吗

**Comment by SeaHOH** [comment]
没有公告更新服务端就无需重新部署。

**Comment by no-name2017** [comment]
@xxnet 回报X大，电脑上最新版xx能搜索到IPv6的ip，一切正常，就是xndroid里搜索不到ip（只搜到一个IPv4能翻，IPv6一个都没有），系统是安卓4.4，xndroid是最新的测试版1.1.10

**Comment by AnyWAT** [comment]
安卓4.4.2，xndroid1.1.9，XX-Net3.10.4退回到3.8.4（没有智能路由的最高版本），xndroid首页关闭“自动扫描线程”，最大扫描线程数50（如不能维持稳定：IP延时偏小且基本不变，有效IP数趋近IP总数上限自定义500，就再增大），仅IPv6：一切正常，你可自由访问互联网😂

**Comment by no-name2017** [comment]
老手机经不起root折腾了，看来还是想其他办法吧

**Comment by liumahao** [comment]
3.11.10 
连打开国内网站，比如贴吧，B站，虎牙等视频网站都会卡，无论是挂GP还是XT自动切换还是全局代理
换回老版本正常

**Comment by SeaHOH** [comment]
@liumahao 
老版本是哪个版本？GP 和 XT 是什么？
国内网站应该直连，3.11.10 相比 3.11.9 并未修改智能代理相关代码。

**Comment by AnyWAT** [comment]
GP：GoagProxy
XT：XX-Net

**Comment by liumahao** [comment]
3.11.7之前的版本

2018-04-30 12:05 GMT+08:00 SeaHOH <notifications@github.com>:

**Comment by SeaHOH** [comment]
和 3.11.7 相比，多了个 https 连接不使用 GAE 的选项，默认是使用的。
但这和国内网站有什么关系，GoProxy 就更扯不到一起。
请按照 https://github.com/XX-net/XX-Net/wiki/设置代理 ，检查你的设置。

**Comment by liumahao** [comment]
我回退到以前版本就正常了，只是上来汇报一下这个情况

在 2018年4月30日 下午2:05，SeaHOH <notifications@github.com>写道：

**Comment by SeaHOH** [comment]
>连打开国内网站，比如贴吧，B站，虎牙等视频网站都会卡，无论是挂GP还是XT自动切换还是全局代理

这句看不明白，到底是怎么使用的？
为什么国内网站会走代理？为什么会出现 GP？

@liumahao 非常感谢你，但既然是说明情况，请提供更详细的信息。

**Comment by liumahao** [comment]
所以我也不清楚啊，如果我不开XX-NET，SwithyOmega选直接连接，打开贴吧和B站等和以前都没有问题

但是如果开了XX-NET，取消全局代理，
SwithyOmega选GP或XT的自动切换，打开贴吧和B站会非常慢，先会跳转到无法连接到此网页，之后又会自动刷新出来正常的网页
但是如果用3.11.7或者现在用的3.10.4，就没有上述问题


在 2018年4月30日 下午4:58，SeaHOH <notifications@github.com>写道：

**Comment by SeaHOH** [comment]
@liumahao 
能展示下你的 SwithyOmega 截图吗？只要情景模式“GAE-Proxy自动切换”就行。

**Comment by liumahao** [comment]
2018-04-30 17:29 GMT+08:00 SeaHOH <notifications@github.com>:

**Comment by SeaHOH** [comment]
邮件发不了截图

**Comment by ynbsyz2018** [comment]
WIN10 升级到1803后 IPV6开启失败

**Comment by SeaHOH** [comment]
@liumahao 没看到么，那个啥，使用邮件回复发不了截图。

**Comment by SeaHOH** [comment]
@ynbsyz2018 试试下面这个工具
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6#工具

**Comment by ynbsyz2018** [comment]
@SeaHOH 
我的操作环境一直是可以直接打开XXNET就开启IPV6的，现在我已经回退到老版本WIN10，是可以直接开启IPV6的
但是WIN10会强制升级，郁闷

**Comment by SeaHOH** [comment]
那是切换服务器的工具

**Comment by ynbsyz2018** [comment]
好的，多谢，我自己慢慢研究
