### ISSUE TITLE
广东联通光纤，teredo全军覆没，挂VPN才能连接

### ISSUE THREAD

**Issue by bitternolis** [XX-net/XX-Net#10568]
广东联通光纤在最近一次检机后就变成这样了

**Comment by SeaHOH** [comment]
试一下 #10328

**Comment by bitternolis** [comment]
('try bind local port:', 3432)
Starting probe NAT type...
当前设备可能无法正常使用 teredo 隧道，NAT 类型是 offline！

经检测，推荐服务器是 None.

**Comment by SeaHOH** [comment]
看看你的路由器是不是公网 IP

**Comment by SeaHOH** [comment]
或者最近改过防火墙、路由器设置？

**Comment by bitternolis** [comment]
只有检机的时候联通工作人员远程登陆过光猫

**Comment by AnyWAT** [comment]
offline 试试先禁用再启用网络

**Comment by bitternolis** [comment]
我觉得投诉可能没用，一定会让办专线的

**Comment by bitternolis** [comment]
以前应该也是内网，路由ip一直在变的

**Comment by SeaHOH** [comment]
你又不能操作路由器，看不到设置，`offline`这个没法搞。

**Comment by SeaHOH** [comment]
要不设置为仅 IPv4，估计还能扫出几个 IP。

**Comment by xxnet** [comment]
​最近一次检机，是上面检查吗？

**Comment by SeaHOH** [comment]
只能说，广州真危险，新疆也是。

**Comment by Just2co** [comment]
@bitternolis 如果是新疆那还不好说，广东的话，管制没那么厉害的，多半是你系统哪里没弄好，teredo隧道就是专为多层nat网络环境设计的，跟你有没有公网IP没多大关系，四五层路由下面照样可以时用IPV6，前提是你能连上teredo服务器。你找到你本地连接，然后右键属性，把IPV6前面的勾选去掉，然后禁用启用网卡，然后打开gpedit.msc组策略编辑器，进去把IPV6网络相关的3项设置好，然后重启电脑，应该就可以用了！

**Comment by AnyWAT** [comment]
不支持：然后打开gpedit.msc组策略编辑器，进去把IPV6网络相关的3项设置好，然后重启电脑，应该就可以用了！
使用ping超时的微软服务器（系统默认）优先，或许更稳定！(win7除外？用Win10系统的即可)
管理权限运行 netsh int ipv6 set teredo enterpriseclient default

**Comment by SeaHOH** [comment]
你们等人家回复好不好

**Comment by ARCHOTZ** [comment]
test-ipv6.com上，如果你检测时是xx/14基本都不行，xx/11就基本可以，一般重启路由器可以连上，动不了路由器就没办法了。

**Comment by bitternolis** [comment]
……那个，几天后terodo又能连上了。

**Comment by bitternolis** [comment]
是这样的，
几天之后，网络环境可能有些变化。
内网ip似乎是固定的27.40.XXX.X，但是公网ip变了。
之后就能连上terodo服务器了。
或许某些ip无法连接到teredo？

**Comment by SeaHOH** [comment]
应该是在调整网络，这是正常的运营过程，但出于什么目的，是否故意封锁就不得而知了。

其实现在能连接 teredo 服务器，很可能是有人投诉的结果。

**Comment by no-name2017** [comment]
是最新版吗？你延迟那么低？

**Comment by Just2co** [comment]
延迟不算低了，我这里一般在300毫秒上下，低于这个延迟的非常稀少，大部分都是300多，看油管有时候可以飙到8兆bps，大部分时候都是2~3兆bps，流畅看网页跟油管1080P是没问题的。

**Comment by caitianzhu** [comment]
win10.ipv6.microsoft.com
teredo-debian.remlab.net
出现问题就互换服务器，我只用这两个，再到所有控制面板项\网络连接（禁用/启用）在用的连接。- -我是这样解决抽风的

**Comment by bitternolis** [comment]
好了，现在已完全恢复正常了……以后出问题了再来报吧

**Comment by SeaHOH** [comment]
可能是正常调整吧，也没见其他人出来说类似情况。
