### ISSUE TITLE
间断性的“显示连接尚未建立”

### ISSUE THREAD

**Issue by kfmyj** [XX-net/XX-Net#10567]
最近刚刚安装电信宽带，他们光猫做路由，并且无法管理其光猫。现在经常性出现显示尚未建立。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:490
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 324
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​scan-ip-thread-num: 150
先改小试试

connected-link: new:0 used:undefined

undefined 是bug，要看看代码

把gae的日志贴出来分析

**Comment by kfmyj** [comment]
我先改小值，测试一下，现在状态一切正常，等出现问题我再贴日志出来，让各位大佬帮忙分析一下。

**Comment by kfmyj** [comment]
ntp%26pfname%3D%26rpctoken%3D79721489&error=There%20was%20an%20error%20during%20the%20transport%20or%20processing%20of%20this%20request.%20Error%20code%20%3D%20103%2C%20Path%20%3D%20%2Fu%2F0%2F_%2FNotificationsOgbUi%2Fdata%2Fbatchexecute&line=Not%20available"

Apr 28 20:55:10.042 - [WARNING] send response fail

Apr 28 20:55:10.043 - [WARNING] send response fail

Apr 28 20:55:10.043 - [WARNING] send response fail

Apr 28 20:55:10.044 - [WARNING] send response fail

Apr 28 20:55:10.046 - [WARNING] send response fail

Apr 28 20:55:10.047 - [WARNING] send response fail

Apr 28 20:55:11.265 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:11.265 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/rpc

Apr 28 20:55:15.839 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:15.839 - [WARNING] gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644

Apr 28 20:55:15.939 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:15.939 - [WARNING] gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653

Apr 28 20:55:15.940 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653"

Apr 28 20:55:15.940 - [WARNING] GAE GET https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653 request fail:"600:gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920060653"

Apr 28 20:55:15.941 - [WARNING] send response fail

Apr 28 20:55:15.943 - [WARNING] send response fail

Apr 28 20:55:16.774 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:16.774 - [WARNING] gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3D

Apr 28 20:55:20.690 - [DEBUG] GAE GET /mail/u/14/feed/atom/?ibxr=0×tamp=1524920120657 from:127.0.0.1:9438

Apr 28 20:55:22.976 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:22.976 - [WARNING] gae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=c

Apr 28 20:55:25.703 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:25.703 - [WARNING] gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920120657

Apr 28 20:55:31.300 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:31.300 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/rpc

Apr 28 20:55:45.713 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:45.713 - [WARNING] gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920120657

Apr 28 20:55:45.915 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:45.916 - [WARNING] gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644

Apr 28 20:55:45.916 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644"

Apr 28 20:55:45.916 - [WARNING] GAE GET https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644 request fail:"600:gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644gae_exception:'600:fetch gae fail' https://mail.google.com/mail/u/14/feed/atom/?ibxr=0×tamp=1524920090644"

Apr 28 20:55:45.916 - [WARNING] send response fail

Apr 28 20:55:45.916 - [WARNING] send response fail

Apr 28 20:55:46.826 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:46.826 - [WARNING] gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3D

Apr 28 20:55:46.826 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3Dgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3Dgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3D"

Apr 28 20:55:46.826 - [WARNING] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3D request fail:"600:gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3Dgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3Dgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=sF5MfIf2YSDrRCiwQTzEmg%3D%3D"

Apr 28 20:55:50.672 - [DEBUG] GAE GET /mail/u/14/feed/atom/?ibxr=0×tamp=1524920150656 from:127.0.0.1:9454

Apr 28 20:55:53.067 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:53.067 - [WARNING] gae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=c

Apr 28 20:55:53.067 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=cgae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=cgae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=c"

Apr 28 20:55:53.067 - [WARNING] GAE POST https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=c request fail:"600:gae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=cgae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=cgae_exception:'600:fetch gae fail' https://notifications.google.com/u/0/_/NotificationsOgbUi/data/batchexecute?f.sid=9018285979305942029&hl=zh-CN&soc-app=208&soc-platform=1&soc-device=1&_reqid=372367&rt=c"

Apr 28 20:55:53.067 - [WARNING] send response fail

Apr 28 20:55:53.067 - [WARNING] send response fail

Apr 28 20:55:55.042 - [DEBUG] create ssl timeout fail.

Apr 28 20:55:55.719 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Apr 28 20:55:55.719 - [WARNING] gae_exception:'600:fetch gae fail'

**Comment by kfmyj** [comment]
@xxnet 日志贴出来了，帮忙看一下，谢谢！

**Comment by SeaHOH** [comment]
似乎是 teredo 不稳定。

**Comment by kfmyj** [comment]
@SeaHOH 那这个是电信商的问题？各位大佬有木有解决办法了？@@

**Comment by SeaHOH** [comment]
换一个服务器试试

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6

查看 teredo 相关，有介绍如何更换服务器。

**Comment by kfmyj** [comment]
@SeaHOH 好的，我换服务器试一下，谢谢。

**Comment by SeaHOH** [comment]
关闭后仍可回复
