### ISSUE TITLE
从未开启IPv6的网络环境（移动网）转移到已开启IPv6的网络环境（教育网）后必须重启电脑？

### ISSUE THREAD

**Issue by TieBaMma** [XX-net/XX-Net#10560]
如题。平时因为要频繁移动，笔记本一般都是休眠，可一但在未开启IPv6的网络环境中连过了网，返回教育网后IPv6的状态就必然为fail。目前只找到了重启电脑这一个解决方法，但每回都要重启实在太累了……不知是否有更简单一些的方法？

以下为诊断信息：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:500
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 583
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
禁用启用适配器？

**Comment by TieBaMma** [comment]
重启ip helper后顺利连上。（计算机管理->服务和应用程序->服务------IP helper->重启）
