### ISSUE TITLE
请教一下xx-net切换版本的策略

### ISSUE THREAD

**Issue by no-name2017** [XX-net/XX-Net#10571]
在Xndroid1.1.9版本里自带的xx-net 3.10.4里，选择“全部已发布版本”，然后点击ZIP压缩包为什么不会开始下载？挂了代理也一样不行，请问是不是xx-net升级的时候执行的是其他链接呢？

**Comment by SeaHOH** [comment]
你没 root 实在是没啥好办法，就你的网络而言。
要不试试连接到不同的网络。

**Comment by no-name2017** [comment]
好吧，谢谢SeaHOH 大佬
