### ISSUE TITLE
XX-Net 3.11.10 无法扫描到ip

### ISSUE THREAD

**Issue by sxfsirg** [XX-net/XX-Net#10570]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
>ipv6-status: Fail
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6

**Comment by sxfsirg** [comment]
试过了，没效果

**Comment by SeaHOH** [comment]
里面有两个工具，尝试一下。

**Comment by AnyWAT** [comment]
原来可以用，升级之后不行了：貌似 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced
IP段列表(支持格式)缩减了？

**Comment by AnyWAT** [comment]
🤐

**Comment by sxfsirg** [comment]
@SeaHOH 试过了，不行

**Comment by sxfsirg** [comment]
@AnyWAT IP段列表默认的没有调过

**Comment by AnyWAT** [comment]
不是你，是TA😝

**Comment by SeaHOH** [comment]
显示的结果是什么么？这两个工具都会测试 teredo 状态。

**Comment by sxfsirg** [comment]
@SeaHOH 感谢SeaHOH，用你的https://github.com/XX-net/XX-Net/issues/10328，问题解决了
