### ISSUE TITLE
求推荐一个能装xx-net的路由器

### ISSUE THREAD

**Issue by retmania** [XX-net/XX-Net#10575]
不知道是不是该发这里，求一个路由

要能装xx-net，有千兆口，别的没有任何需求，便宜点就行

**Comment by no-name2017** [comment]
路由器装了，手机app也翻不了墙吧？

**Comment by xuanxuaner** [comment]
ASUS AC66U正在用，能刷梅林，tomato，openwrt的都可以

**Comment by SeaHOH** [comment]
@AnyWAT 某些 App 会忽略系统代理设置，而且也不是都会承认所有系统中存在的证书。

**Comment by SeaHOH** [comment]
应该是使用 XX-Net 的转发功能，这样所有流量都会通过代理。
