### ISSUE TITLE
Google地圖無法刪除和保持地點

### ISSUE THREAD

**Issue by imldf** [XX-net/XX-Net#10572]
最近使用Google地圖發現無法刪除和保存地點，我記得使用以前版本的時候是沒有問題的，目前測試了3.11.10、3.11.4、3.10.4這三個自己覺得好用的版本都出現上述問題。不知道是什麽問題？

**Comment by SeaHOH** [comment]
请先用其它代理或浏览器尝试，确定问题区间。
合理利用浏览器的 `F12` 网络活动查看功能。

**Comment by SeaHOH** [comment]
关闭后仍可回复
