### ISSUE TITLE
能够换IP吗？

### ISSUE THREAD

**Issue by viponedream** [XX-net/XX-Net#10587]
一个IP，给网站被屏蔽了，能不能重新换一个？
有的网站能够识别出来，所以可能要换一换

**Comment by whhxmwhh** [comment]
我看到的是ip延时500ms就fail。能否把这个提高到900ms呢？

**Comment by SeaHOH** [comment]
@viponedream GAE 出口无法改变，X-Tunnel 可以切换。
https://github.com/XX-net/XX-Net/wiki/X-Tunnel-use-special-server

@whhxmwhh 没懂，哪里的延时，什么东西 fail？

**Comment by SeaHOH** [comment]
关闭后仍可回复
