### ISSUE TITLE
[江湖告急]换路由器后变成"仅IPV6"不可用

### ISSUE THREAD

**Issue by 2609665** [XX-net/XX-Net#10580]
因为换了个路由器后变成client (Group lolicy)  XX-NET一直是ipv6不可用的状态
本来A机,B机都安装XX-NET使用相同的配置和appid   都使用正常!
====================分割线=============================
换了路由器后,A机,B机都是"仅IPV6"不可用的状态,无法使用.
后来我把A机的Smart Router模块关闭后,A机正常了,使用正常.
![0k](https://user-images.githubusercontent.com/20493163/39462959-c2d0e3b4-4d47-11e8-990f-1cd3bf755e92.jpg)

B机相同设置后问题依旧,还是无法使用.
![qq 20180501135506](https://user-images.githubusercontent.com/20493163/39462975-dd34b208-4d47-11e8-88d5-134aae45b494.jpg)
上图后补的之前是client (Group lolicy)
改了组策略 teredo状态和teredo默认限定后变成
![not ok](https://user-images.githubusercontent.com/20493163/39463078-65609a70-4d48-11e8-9de9-ce1c9c8abda5.png)
这时XX-NET状态还是"仅IPV6"不可用无法使用,
![qq](https://user-images.githubusercontent.com/20493163/39463208-2931f0ca-4d49-11e8-897e-01bb409480d7.png)
B机通过A机代理是可以使用的!
哪位大佬给指点一下B机如何解决!先谢谢了!!!已经搞的我有点懵逼了!

**Comment by SeaHOH** [comment]
建议不要使用组策略来设置，不方便修改和确认问题。

先取消组策略设置，然后使用这里的脚本来设置。
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6#工具

**Comment by 2609665** [comment]
@SeaHOH不是我要用组策略来设置的,本来我也一直用的enable_ipv6.bat来开启IPV6的.
因为不用组策略开那个teredo默认限定的话就是这个dormant状态!

**Comment by SeaHOH** [comment]
尝试下没坏处，我说的并不是 enable_ipv6.bat 这个脚本。

**Comment by 2609665** [comment]
好吧!我自己解决了!刚才用disable_ipv6.bat禁用了一下ipv6再重新enable_ipv6.bat  现在OK了  唉我真是太蠢了!!!很少用到disable_ipv6.bat..     @SeaHOH 还是谢谢您的解答了
