### ISSUE TITLE
在ubuntu 18.04  + chrome + gae_proxy， 无法使用。

### ISSUE THREAD

**Issue by dgm3000** [XX-net/XX-Net#10585]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  使用 3.11.10版本 与 3.11.7版本

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  已看，无帮助。

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  已看，无ubuntu下提问，

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
无帮助

* 简单描述遇到的问题：
每当浏览器访问127.0.0.1：8087 或者点击 chrome 插件的gae_proxy按钮， 均报以下错误：
5月 01 22:27:44.00 [gae_proxy][DEBUG] Browse localhost by proxy
5月 01 22:27:44.00 [simple_http_server][ERROR] handler:Exception('unknown method:',) cmd:GET path:/proxy.pac from:127.0.0.1:52480
5月 01 22:27:44.00 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "/home/lm/liuming/XX-Net/code/3.11.10/python27/1.0/lib/noarch/simple_http_server.py", line 166, in handle_one_request
    self.do_GET()
  File "/home/lm/liuming/XX-Net/code/3.11.10/gae_proxy/local/proxy_handler.py", line 203, in do_METHOD
    return self.forward_local()
  File "/home/lm/liuming/XX-Net/code/3.11.10/gae_proxy/local/proxy_handler.py", line 98, in forward_local
    response = simple_http_client.request(self.command, self.path, request_headers, payload)
  File "/home/lm/liuming/XX-Net/code/3.11.10/python27/1.0/lib/noarch/simple_http_client.py", line 515, in request
    return client.request(method, url, headers, body, read_payload)
  File "/home/lm/liuming/XX-Net/code/3.11.10/python27/1.0/lib/noarch/simple_http_client.py", line 437, in request
    raise Exception("unknown method:%s" % upl.scheme)
Exception: unknown method:

* 做过哪些尝试：
同样的脚本在win10下无异常。

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by SeaHOH** [comment]
请确定设置是否一致
![x2scrap2](https://user-images.githubusercontent.com/8470820/39479848-050ba1ca-4d56-11e8-96da-6492bfd04d81.png)
