### ISSUE TITLE
智能路由访问Keepa失败，直连可以连接

### ISSUE THREAD

**Issue by momo1101** [XX-net/XX-Net#10589]
Keepa直连可达，GAE不可达
经尝试：PAC模式可以正常打开，智能路由模式不能正常打开

PAC中是否走GAE的选择是对的。不知道智能路由是什么原理，能否把Keepa从路由中改为不走GAE

**Comment by SeaHOH** [comment]
请贴一点访问 Keepa 时智能路由的日志。

**Comment by xxnet** [comment]
​把keepa的域名，放入智能路由的直连列表中就好

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by momo1101** [comment]
> 请贴一点访问 Keepa 时智能路由的日志。


Nov 30 16:05:23.158 - [DEBUG] gae /apps/cloud/?app=keepaWebsite&version=1.6 not support WebSocket
Nov 30 16:05:24.087 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:25.531 - [DEBUG] host:cdn.keepa.com:443 do gae
Nov 30 16:05:25.537 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:25.850 - [DEBUG] host:clients4.google.com:443 do gae
Nov 30 16:05:26.136 - [DEBUG] host:cdn.keepa.com:443 do gae
Nov 30 16:05:26.185 - [DEBUG] host:cdn.keepa.com:443 do gae
Nov 30 16:05:26.204 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:26.221 - [DEBUG] gae /apps/cloud/?app=keepaWebsite&version=1.6 not support WebSocket
Nov 30 16:05:27.020 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:27.374 - [DEBUG] host:cdn.keepa.com:443 do gae
Nov 30 16:05:27.679 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:27.679 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:28.196 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:28.226 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:28.663 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:28.673 - [DEBUG] gae /apps/cloud/?app=keepaWebsite&version=1.6 not support WebSocket
Nov 30 16:05:28.682 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:32.668 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:32.675 - [DEBUG] host:keepa.com:443 do gae
Nov 30 16:05:32.682 - [DEBUG] gae /apps/cloud/?app=keepaWebsite&version=1.6 not support WebSocket
Nov 30 16:05:33.604 - [DEBUG] host:16.client-channel.google.com:443 do gae
Nov 30 16:05:39.610 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:39.621 - [DEBUG] gae /apps/cloud/?app=keepaWebsite&version=1.6 not support WebSocket
Nov 30 16:05:41.665 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:41.692 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:42.486 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:43.225 - [DEBUG] host:dyn.keepa.com:443 do gae
Nov 30 16:05:43.235 - [DEBUG] gae /apps/cloud/?app=keepaWebsite&version=1.6 not support WebSocket

**Comment by SeaHOH** [comment]
> ​把keepa的域名，放入智能路由的直连列表中就好
