### ISSUE TITLE
安卓火狐浏览器如何导入证书，，没找到入口

### ISSUE THREAD

**Issue by digkeeper** [XX-net/XX-Net#10581]
如题

**Comment by SeaHOH** [comment]
请善用 wiki 和 issues 搜索。
https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA

**Comment by digkeeper** [comment]
我说的是火狐安卓浏览器导入证书，教程里是安卓本身导入证书

**Comment by SeaHOH** [comment]
点网页中的 CA 连接，直接导入。

**Comment by digkeeper** [comment]
我是用局域网,xxnet文件夹里新建manual.ini 文件
[listen]
ip = 0.0.0.0
[pac]
ip = 0.0.0.0
让手机火狐浏览器代理浏览器的ip和端口 8087上，你说的点击导入我试过了， 上google.com类似的网站就会出现此连接不受信任

**Comment by SeaHOH** [comment]
等我安个火狐试试

**Comment by SeaHOH** [comment]
刚试过了，点击状态页面的 CA 链接，
火狐弹窗确认窗口，选择用于信任网站，
然后正常浏览谷歌。

**Comment by digkeeper** [comment]
奇了怪了，我的安卓火狐浏览器点击根本没有弹窗让我确认，不过还是谢谢你

**Comment by digkeeper** [comment]
点击直接就弹出这句 this certificate is already installed as a certificate authority
