### ISSUE TITLE
升级win10 1803之后。。IP变少了

### ISSUE THREAD

**Issue by yeezylife** [XX-net/XX-Net#10584]
![tim 20180501170253](https://user-images.githubusercontent.com/30175425/39467692-f4e0771a-4d61-11e8-961c-b6ecb776d6d2.png)

IP一从500个 下降到一二十个。 扫到500个之后，过一会又变成一二十个。。
IPV6测试里显示运营商（ISP）是 Google LLC。。  之前我记得是teredo啊

**Comment by SeaHOH** [comment]
因为这个网站测试时不要设置代理才准确。
