### ISSUE TITLE
求助 更新完win10 1804之后 ipv6 Fail

### ISSUE THREAD

**Issue by iloveinter44** [XX-net/XX-Net#10596]
ipconfig里面有2001开头地址 但是xx-net显示ipv6fail

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : 2001:*******************************(Preferred)
   Link-local IPv6 Address . . . . . : fe80::***************************(Preferred)
   Default Gateway . . . . . . . . . : ::
   NetBIOS over Tcpip. . . . . . . . : Disabled

**Comment by iloveinter44** [comment]
补充teredo状态:

Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : win10.ipv6.microsoft.com.
Client Refresh Interval : 20 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : managed
NAT                     : restricted (port)
NAT Special Behaviour   : UPNP: No, PortPreserving: No
Local Mapping           : 10.211.55.5:50480

**Comment by whhxmwhh** [comment]
看来win10 是垃圾。准备换win7

**Comment by SeaHOH** [comment]
>xxnet-version: 3.11.10

到底回滚没有？很疑惑。

**Comment by kkdrfyb** [comment]
我也是，不过懒得回滚系统了，准备买个vpn账号，xx-net太折腾了

**Comment by xc1988** [comment]
我这里倒是一切正常

**Comment by yydxwt** [comment]
不用回滚　每次升级把就ip都删了从新扫描　或者下新版本另建目录　把老版本删了

**Comment by zzuzjl** [comment]
@kkdrfyb 终身VPN只需9.9美元，购买地址：https://stacksocial.com/sales/ra4w-vpn-lifetime-subscription?rid=4992791  （有韩国日本香港新加坡美国英国等20多国服务器，实测OpenVPN UDP模式可用）
