### ISSUE TITLE
无法在C盘运行

### ISSUE THREAD

**Issue by LHTXQ** [XX-net/XX-Net#10592]
* 简单描述遇到的问题：无法在C盘运行（win10  1803），只有一块硬盘一个分区，现在只能插U盘使用。

* 做过哪些尝试：更改权限、关闭defender的文件保护

* 请贴出相关的日志：windows script host:操作已被用户取消。行64

**Comment by LHTXQ** [comment]
已解决：在U盘上首次运行后复制文件到C盘就可以正常运行了。

**Comment by SeaHOH** [comment]
可能真是权限问题

**Comment by LHTXQ** [comment]
安装某些软件就不会有问题，如游戏。但安装快捷键驱动时只有把安装包放在其它盘安装才可以，这是win10的限制还是1803跟新后才有的问题，有遇到相同问题的人吗？
