### ISSUE TITLE
gaeproxy状态显示尝试开启ipv6，尝试开启返回“ 未能解析服务器名”

### ISSUE THREAD

**Issue by drykimi** [XX-net/XX-Net#10591]
May 03 13:38:07.452 - [DEBUG] create ssl timeout fail.
May 03 13:38:16.939 - [WARNING] not enough ip
May 03 13:38:16.986 - [WARNING] not enough ip
May 03 13:38:26.941 - [WARNING] not enough ip
May 03 13:38:26.987 - [WARNING] not enough ip
May 03 13:38:30.866 - [DEBUG] create ssl timeout fail.
May 03 13:38:36.944 - [WARNING] not enough ip
May 03 13:38:36.996 - [WARNING] not enough ip
May 03 13:38:46.954 - [WARNING] not enough ip
May 03 13:38:47.001 - [WARNING] not enough ip
May 03 13:38:56.956 - [WARNING] not enough ip
May 03 13:38:57.006 - [WARNING] not enough ip
May 03 13:39:06.960 - [WARNING] not enough ip
May 03 13:39:07.008 - [WARNING] not enough ip
May 03 13:39:16.961 - [WARNING] not enough ip
May 03 13:39:17.009 - [WARNING] not enough ip
May 03 13:39:26.970 - [WARNING] not enough ip
May 03 13:39:27.018 - [WARNING] not enough ip
May 03 13:39:31.507 - [DEBUG] create ssl timeout fail.
May 03 13:39:36.980 - [WARNING] not enough ip
May 03 13:39:37.023 - [WARNING] not enough ip
May 03 13:39:41.133 - [DEBUG] create ssl timeout fail.
May 03 13:39:46.986 - [WARNING] not enough ip
May 03 13:39:47.024 - [WARNING] not enough ip
May 03 13:39:53.273 - [DEBUG] GAEProxy web_control 127.0.0.1:60324 POST /config?cmd=get_config
May 03 13:39:53.273 - [DEBUG] GAEProxy Web_control 127.0.0.1:60321 GET /scan_ip?cmd=get_range
May 03 13:39:53.274 - [INFO] load ip range file:E:\Program Files (x86)\XX-Net-3.11.10\code\3.11.10\gae_proxy\local\ip_range.txt
May 03 13:39:56.995 - [WARNING] not enough ip
May 03 13:39:57.026 - [WARNING] not enough ip

**Comment by sanmingzi** [comment]
Sometimes we can not search the IPv4 google ips, we should enable ipv6.

[使用Teredo隧道,提前感受IPv6](https://www.longsays.com/844.html)

我们可以通过这个[test-ipv6](http://test-ipv6.com/)来测试自己的机器是否已经支持IPv6。访问网站之后，如果看到：

```
你在網際網路上的IPv6位址 2001:0:53aa:64c:45c:28d7:3550:ba9c
你的 IPv6 連線服務是透過: Teredo
測試 IPv6 (跳過DNS)
成功 (0.240s) 使用 ipv6 Teredo
```

如果机器还不支持IPv6，可参考下述方法开启IPv6

- 使用管理员身份运行cmd
- netsh interface teredo set state server=teredo.remlab.net
- netsh int ter set state enterpriseclient
- netsh interface ipv6 show teredo

如果上述方法失败，尝试将teredo.remlab.net更换成其他的teredo地址。

- teredo.remlab.net/teredo-debian.remlab.net (法国) (Miredo 默认设置)
- teredo.autotrans.consulintel.com (西班牙)
- teredo.ipv6.microsoft.com (美国 雷蒙德) (Windows XP/2003/Vista/7/2008 系统默认设置)
- teredo.ngix.ne.kr (韩国)
- teredo.managemydedi.com (美国 芝加哥)

**Comment by whhxmwhh** [comment]
你的运营商（ISP）是 Amazon.com, Inc.
没有检测到 IPv6 地址 [更多信息]
你似乎只能连接 IPv4 互联网，不能访问纯 IPv6 网站。
为了保证最佳的网络性能和连接性，向你的运营商咨询原生 IPv6 事宜吧。 [更多信息]
本站现已支持 HTTPS。 [更多信息]
你的 DNS 服务器（可能由运营商提供）没有接入或没有配置 IPv6，将来这可能会妨碍你访问纯 IPv6 网站。 [更多信息]

**Comment by whhxmwhh** [comment]
這個怎麼破呢？


Microsoft Windows [版本 10.0.15063]
(c) 2017 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>netsh interface teredo set state server=teredo.ngix.ne.kr
确定。
C:\WINDOWS\system32>netsh int ter set state enterpriseclient
确定。
C:\WINDOWS\system32>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.ngix.ne.kr
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能解析服务器名
C:\WINDOWS\system32>ping teredo.ngix.ne.kr
Ping 请求找不到主机 teredo.ngix.ne.kr。请检查该名称，然后重试。
C:\WINDOWS\system32>netsh interface teredo set state server=teredo.ipv6.microsoft.com
确定。
C:\WINDOWS\system32>netsh int ter set state enterpriseclient
确定。
C:\WINDOWS\system32>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能解析服务器名
C:\WINDOWS\system32>


這個怎麼破呢？

**Comment by sanmingzi** [comment]
@whhxmwhh 
It seems that your machine can not access the teredo server host "teredo.ipv6.microsoft.com", this is the default teredo server. You can change the teredo server host with this command:

netsh interface teredo set state server=teredo.remlab.net

There are some teredo server hosts, you can try all of them until you get the IPv6.

- teredo.remlab.net/teredo-debian.remlab.net (法国) (Miredo 默认设置)
- teredo.autotrans.consulintel.com (西班牙)
- teredo.ipv6.microsoft.com (美国 雷蒙德) (Windows XP/2003/Vista/7/2008 系统默认设置)
- teredo.ngix.ne.kr (韩国)
- teredo.managemydedi.com (美国 芝加哥)

**Comment by sanmingzi** [comment]
@whhxmwhh 
I have test the list of teredo server hosts and update it. This list is avalible.

- teredo.remlab.net
- teredo2.remlab.net
- teredo-debian.remlab.net

**Comment by SeaHOH** [comment]
@whhxmwhh 更换 DNS 服务器，或者使用反污染工具。

**Comment by whhxmwhh** [comment]
thank  you。
谢谢。我去找个dns先。。

**Comment by SeaHOH** [comment]
关闭后仍可回复
