### ISSUE TITLE
求助：mac系统，启动xx-net之后，自动修改系统的代表为http://127.0.0.1:8086/proxy.pac 但这个文件并不能访问

### ISSUE THREAD

**Issue by imyangdy** [XX-net/XX-Net#10595]
如题：
自己想修改，xx-net也会修改回来，所以：
想用自己导出来的pac文件都不行，所以safari浏览器无法翻墙
一、有没有办法修改回来系统代表
二、或者自己可以手动加上http://127.0.0.1:8086/proxy.pac这个文件，因为自己在本地配置的文件，是这个地址http://127.0.0.1/proxy.pac 是没有端口号的

**Comment by imyangdy** [comment]
@xxnet @xx-Chen 大神请指点一下，mac系统为10.12.6 ，xx_net版本为3.7.12

**Comment by SeaHOH** [comment]
代理菜单不要选择 `pac`，选 `disable` 即可。

**Comment by imyangdy** [comment]
@SeaHOH 好了，safari可以上了，但奇怪的是chrome还是要用SwitchyOmega才能上，按理说，应该会自动走系统的代理pac文件才对，如果我把SwitchyOmega插件停用了，就翻不了

**Comment by SeaHOH** [comment]
那就使用吧
