### ISSUE TITLE
求助 ipv6数量少 并且状态时不时就fail

### ISSUE THREAD

**Issue by LakyTT** [XX-net/XX-Net#10605]
![4i36o xf g0cap8 k gk3 6](https://user-images.githubusercontent.com/30133809/39659739-e2291b56-5061-11e8-8362-004000d605be.png)

是在是太难过了 求助啊

**Comment by vikima** [comment]
我最近也发现了。IP越来越少，是不是得像个别的办法了。

**Comment by LakyTT** [comment]
@vikima s是的 不知道怎么弄

**Comment by SeaHOH** [comment]
无法改变客观因素，可尝试以下操作：
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
