### ISSUE TITLE
昨天开始ip6状态就一直是fail了....求救😭用不了了

### ISSUE THREAD

**Issue by menglala** [XX-net/XX-Net#10600]
按开启ip6的教程，teredo网址进不去下载...😭

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6#工具

试试这个工具

**Comment by menglala** [comment]
https://zh.wikipedia.org/zh-hans/Teredo隧道  这个网站都进不去😭

**Comment by retmania** [comment]
我也是看这里的朋友说的，把本地连接里的ipvy勾子消掉，再也没fail过

**Comment by SeaHOH** [comment]
重点在工具
https://github.com/XX-net/XX-Net/issues/10282

**Comment by dylanleesky** [comment]
@SeaHOH 我win10系统，依旧是3.10.4为主，昨天重置了系统，默认网卡开启的IPv6，然后XX就显示IP6OK，Python索要权限导入证书没放行，上谷歌正常，然后放行了权限，重启后，IP6有成FAIL了，关闭网卡的IP6，状态OK。今天，开机，开启xx，状态fail，关闭网卡ip6，依旧fail并且上不去外网，切3.11.9，来回开关网卡的IP6都不行，没办法，网路选项中重置网络，重启，OK 、、、
看这情况，这应该是XX的问题吧？刚把xx设为绿色模式了。不知道下次重启后状态是否OK 。
最近没时间研究就不讨论（不在线啦，哈）。。。
这次来这里是找设置IP资源上限方法的。

**Comment by SeaHOH** [comment]
关闭后仍可回复
