### ISSUE TITLE
ip 转换配置服务自动关闭 导致 IPV6 fail 

### ISSUE THREAD

**Issue by winters-z** [XX-net/XX-Net#10604]
![1](https://user-images.githubusercontent.com/32010503/39659448-cea3daa0-505a-11e8-8631-c75ecabfc20a.png)

**Comment by SeaHOH** [comment]
这个，没问题就关闭啦。

**Comment by AnyWAT** [comment]
😜貌似自动与自动（触发器启动）有不同：前者一直运行，后者运行后待工作完成即停止
![default](https://user-images.githubusercontent.com/37962734/39747255-540e877c-52df-11e8-8e36-1f55d108b7ad.png)
![default](https://user-images.githubusercontent.com/37962734/39747291-707bee72-52df-11e8-958f-041931cf6aea.png)

**Comment by zhouhuajdsh** [comment]
这个服务和IPV6不相关，关闭不影响ipv6。我从来没开启过，正常使用XXnet》ipv6

**Comment by AnyWAT** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by LegendTian** [comment]
我也有这个问题，经常开机后无法登陆xxnet，服务里一看是ip转换关闭了，开启后重启电脑ip转换正常，xxnet正常。有没有便捷的解决方法？
