### ISSUE TITLE
可以登陆YouTube，但是只能加载一个框架，不能加载任何内容

### ISSUE THREAD

**Issue by Thierryy** [XX-net/XX-Net#10607]
可以登陆YouTube，但是只能加载一个框架，不能加载任何内容。已经升级到xx-net最新版，登陆其他外网没有任何问题。

**Comment by SeaHOH** [comment]
F12 查看加载状态，截图、日志。。。

**Comment by Thierryy** [comment]
![image](https://user-images.githubusercontent.com/11756812/39660864-39ce7064-507a-11e8-856e-8ae64b985057.png)

**Comment by SeaHOH** [comment]
禁用了js？

**Comment by SeaHOH** [comment]
拦截了 js？

**Comment by carlchan99** [comment]
前些天我用chormium浏览器也碰到过此问题，各种清除cookie、缓存、浏览记录及禁用插件等，后来不知是哪个步骤生效，或是网络状况改善，就恢复正常了。btw，我是用chormium浏览器。碰到这类奇形怪状的问题，换其他浏览器试一试，能翻墙已属不易，无须纠结。

**Comment by Thierryy** [comment]
应该是缓存的问题，清除了缓存后就恢复正常了
