### ISSUE TITLE
一直显示“请检查浏览器代理设置。”，证书状态和浏览器代理设置都是fail

### ISSUE THREAD

**Issue by sakura00** [XX-net/XX-Net#10614]
**XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:322
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:13 h2:0
scan-ip-thread-num: 50
ip-quality: 1105
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false**

**Comment by SeaHOH** [comment]
>一直显示“请检查浏览器代理设置。”

那你到底检查过没呢？
https://github.com/XX-net/XX-Net/wiki/使用Firefox浏览器#设置代理
https://github.com/XX-net/XX-Net/wiki/使用Firefox浏览器#手动导入证书

**Comment by l17es** [comment]
估计是证书没导入，去看下wiki里的浏览器的证书导入就好了

**Comment by sakura00** [comment]
我之前导入过证书了，浏览器代理设置也按照步骤完成了都是这个样子

**Comment by sakura00** [comment]
而且右键XXnet图标，再左键全局只能PAC代理没有用，一直是取消全局代理

**Comment by retmania** [comment]
我也是这样，手动导入证书也没用，但是用管理员身份运行start.bat就可以了

可能是更新了win10 1803的问题？

**Comment by sakura00** [comment]
用管理员身份运行start.bat也没有用啊，都几天了还是没解决。。。求助大神啊

**Comment by l17es** [comment]
日志上看就是证书的问题，不如尝试换一下旧版本的？

**Comment by sakura00** [comment]
不仅仅如此，XXNET的状态一直是请检查浏览器代理设置，IPV4 IPV6都正常

**Comment by sakura00** [comment]
你的意思是需要安装SwitchyOmega扩展吗？

**Comment by sakura00** [comment]
还有一点是SwitchyOmega如何调度代理？。。。

**Comment by sakura00** [comment]
@SeaHOH ,已解决，谢谢。
确实需要通过第三方扩展来调度代理模式，但是switchomega里的情景模式只有GAE-Proxy可行，其他模式下XXNET都显示“请检查浏览器代理设置”

**Comment by SeaHOH** [comment]
安装好后，导入 XX-Net 目录下的 SwitchyOmega 的设置。

**Comment by sakura00** [comment]
之前WIN7系统下一直用的自带的全局PAC智能代理没有用第三方扩展，WIN 10系统下不行。

**Comment by SeaHOH** [comment]
Win 10 的系统代理似乎有特别的地方，某些情况下无法通过 XX-Net 来修改。
