### ISSUE TITLE
[发布] 3.11.12 实现windows 下 teredo的开启傻瓜操作

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#10611]
3.11.10 经过测试反馈稳定，已推送稳定版更新。

~3.11.11 实现了Windows下teredo的启用操作。~
3.11.11 新增功能有 bug，请下载 3.11.12。
目前只提供新用户下载，不推送老用户更新。
需要的请手动下载。

**Comment by SeaHOH** [comment]
Win 8 和 Win 10 系统需要启动的服务与之前的系统似乎有些区别，
希望有人能提供这部分服务的名称。

**Comment by caofengzi** [comment]
真正有用的東西卻沒有人提供了。

**Comment by xxnet** [comment]
​看过Win7/Win8/Win10的 IPHelper的依赖服务，可以按Win10的来统一处理，不需要区别对待。

**Comment by SeaHOH** [comment]
有人报告 #10604 ，我也没用 Win 10，所以才这么提一下。

**Comment by kaigedong** [comment]
Mac High Sierra（10.13.4） 下载了 , 手动下载了xx-net 3.11.11，完全打不开。

**Comment by SeaHOH** [comment]
@kaigedong 3.11.10 能正常运行吗？

**Comment by kaigedong** [comment]
@SeaHOH 没有问题，3.11.10 是正常的~

**Comment by SeaHOH** [comment]
那么请重新下载，正确的大小是 13,436,147 字节，sha256 hash 是 `83609D4E0C494DAEBA42B1E48CC4EC26D092C4D859ACB661F4B0A603E8D5C1CA` 。

**Comment by NuclearBlast** [comment]
我显示隧道是开启的，但依然FAIL

**Comment by cctoking** [comment]
设置 IP转换配置服务为 自动 依旧显示 "仅IPv6" 不可用，请检查。

**Comment by SeaHOH** [comment]
@NuclearBlast 你可以再次执行启用操作，或切换服务器。

**Comment by SeaHOH** [comment]
3.11.11 新增功能有 bug，请下载 3.11.12。
