### ISSUE TITLE
外部计算机管理8085

### ISSUE THREAD

**Issue by litongjava** [XX-net/XX-Net#10615]
我在ubuntn 14.04上安装xx-net,xx-net启动后,监听的管理短是
127.0.0.1:8085
我其他计算机上无法管理 8085.我该如何修改参数,可以在其他计算机管理xx-net

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/中文文档#系统管理 - Launcher

**Comment by SeaHOH** [comment]
关闭后仍可回复
