### ISSUE TITLE
开XXNET以后是所有流量都走代理吗？

### ISSUE THREAD

**Issue by l17es** [XX-net/XX-Net#10616]
情况是这样的，开XXNET之后的网易云音乐听在线音乐很卡，我去看了下日志，看到了很多网易服务器的请求，想问一下，我这是全局代理了吗？

日志如下：
5月 07 18:58:10.30 - [INFO] GAE t:615 s:121 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4000:3b::8,0:h1_req,0:h1_req_sended,614:response_begin,0:h1_get_head,0:h1_finish[SP:655],0:get_response,:0

5月 07 18:58:10.31 - [INFO] GAE t:1247 s:50301 GET http://p1.music.126.net/d3VhdNBocwwEBncqS94Haw==/109951163250385714.jpg?param=194y194 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401e:2f::a,0:h1_req,0:h1_req_sended,452:response_begin,0:h1_get_head,0:get_response,793:h1_finish[SP:40752],:0

5月 07 18:58:10.31 - [DEBUG] GAE GET /zm4AM_j-NUPjsChEvLoYuw==/109951163005891388.jpg?param=335y188 from:127.0.0.1:48842

5月 07 18:58:10.33 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48806

5月 07 18:58:10.36 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48808

5月 07 18:58:10.38 - [INFO] GAE t:695 s:802 GET http://p1.music.126.net/Mn2sf8IAsqmTFeIlLyl24Q==/109951163281443383.jpg?param=40y40 0:start_request,0:get_task(0),0:get_worker(0):2001:ee0:3201:e::e,0:h1_req,0:h1_req_sended,694:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1867],:0

5月 07 18:58:10.43 - [DEBUG] GAE GET /pTxolef7nMgLEa4letcR5w==/18876415625929592.jpg?param=335y188 from:127.0.0.1:48834

5月 07 18:58:10.50 - [INFO] GAE t:960 s:13425 GET http://p1.music.126.net/X9OzXHl3XPy-25oMqnSwWw==/18511377767129900.jpg?param=194y194 0:start_request,0:get_task(0),0:get_worker(0):2a00:1450:4017:f::a,0:h1_req,0:h1_req_sended,566:response_begin,0:h1_get_head,0:get_response,392:h1_finish[SP:14500],:0

5月 07 18:58:10.50 - [DEBUG] GAE GET /3sjJytyYy6lGr_AaAS0AzQ==/109951163286748402.jpg?param=80y80 from:127.0.0.1:48840

5月 07 18:58:10.52 - [INFO] GAE t:1856 s:107 POST https://open.yixin.im/oauth/token 0:start_request,0:get_task(0),0:get_worker(0):2405:4800:100:29::f,0:h1_req,0:h1_req_sended,1854:response_begin,0:h1_get_head,0:h1_finish[SP:172],0:get_response,:0

5月 07 18:58:10.54 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48798

5月 07 18:58:10.63 - [INFO] GAE t:948 s:386 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:10::9,289:h1_req,0:h1_req_sended,657:response_begin,0:h1_get_head,0:h1_finish[SP:1017],0:get_response,:0

5月 07 18:58:10.77 - [INFO] GAE t:1239 s:12 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400b:d::9,0:h1_req,0:h1_req_sended,1238:response_begin,0:h1_get_head,0:h1_finish[SP:207],0:get_response,:0

5月 07 18:58:10.87 - [INFO] GAE t:1159 s:18217 GET http://p1.music.126.net/_DjyoQL6PB2M8_n9BsuxWA==/109951163286875314.jpg?param=335y188 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400a:8::8,0:h1_req,0:h1_req_sended,1035:response_begin,0:h1_get_head,0:get_response,122:h1_finish[SP:16145],:0

5月 07 18:58:10.87 - [DEBUG] GAE GET /U_yV6w5y_ptPBmIpAV6U3g==/109951163286707228.jpg?param=80y80 from:127.0.0.1:48832

5月 07 18:58:11.04 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48804

5月 07 18:58:11.08 - [INFO] GAE t:718 s:1504 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401e:2f::a,0:h1_req,0:h1_req_sended,703:response_begin,0:h1_get_head,0:get_response,14:h1_finish[SP:2485],:0

5月 07 18:58:11.15 - [INFO] GAE t:1098 s:14346 GET http://p1.music.126.net/aKhNwmPi_ugeqBapJuDj-A==/109951163286812981.jpg?param=335y188 0:start_request,0:get_task(0),0:get_worker(0):2001:16a0:202:101::c,0:h1_req,0:h1_req_sended,1072:response_begin,0:h1_get_head,0:get_response,25:h1_finish[SP:13497],:0

5月 07 18:58:11.17 - [DEBUG] GAE GET /3yrr0Dnciz6ixJ-Vs0u3TQ==/109951163286558110.jpg?param=540y200&quality=100 from:127.0.0.1:48838

5月 07 18:58:11.19 - [INFO] GAE t:2132 s:66974 GET http://p1.music.126.net/X3ioD4a3Sw8Vsuv4OLaZ_Q==/18797250788974371.jpg?param=194y194 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:1a::13,908:h1_req,0:h1_req_sended,435:response_begin,0:h1_get_head,0:get_response,788:h1_finish[SP:55144],:0

5月 07 18:58:11.19 - [DEBUG] GAE GET /7c1Mb3dZLgdrROj_WE0MTA==/109951163286554241.jpg?param=540y200&quality=100 from:127.0.0.1:48836

5月 07 18:58:11.29 - [INFO] GAE t:419 s:2052 GET http://p1.music.126.net/U_yV6w5y_ptPBmIpAV6U3g==/109951163286707228.jpg?param=80y80 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:14::9,0:h1_req,0:h1_req_sended,385:response_begin,0:h1_get_head,0:get_response,33:h1_finish[SP:6044],:0

5月 07 18:58:11.30 - [DEBUG] GAE GET /8dk0aPBeR6_QTIUdgtD_qA==/109951163286668076.jpg?param=540y200&quality=100 from:127.0.0.1:48832

5月 07 18:58:11.36 - [INFO] GAE t:864 s:1719 GET http://p1.music.126.net/3sjJytyYy6lGr_AaAS0AzQ==/109951163286748402.jpg?param=80y80 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:15::c,0:h1_req,0:h1_req_sended,848:response_begin,0:h1_get_head,0:get_response,14:h1_finish[SP:2549],:0

5月 07 18:58:11.45 - [INFO] GAE t:1140 s:26865 GET http://p1.music.126.net/zm4AM_j-NUPjsChEvLoYuw==/109951163005891388.jpg?param=335y188 0:start_request,0:get_task(0),0:get_worker(0):2001:12e0:803:3::22,0:h1_req,0:h1_req_sended,723:response_begin,0:h1_get_head,0:get_response,417:h1_finish[SP:23995],:0

5月 07 18:58:11.61 - [INFO] GAE t:1276 s:22479 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401e:2f::b,0:h1_req,0:h1_req_sended,1082:response_begin,0:h1_get_head,0:get_response,193:h1_finish[SP:17845],:0

5月 07 18:58:11.90 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48806

5月 07 18:58:12.06 - [INFO] GAE t:1623 s:39554 GET http://p1.music.126.net/pTxolef7nMgLEa4letcR5w==/18876415625929592.jpg?param=335y188 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4000:34::a,0:h1_req,0:h1_req_sended,1216:response_begin,0:h1_get_head,0:get_response,405:h1_finish[SP:24709],:0

5月 07 18:58:12.06 - [INFO] GAE t:1025 s:2192 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:10::9,0:h1_req,0:h1_req_sended,1024:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:2411],:0

5月 07 18:58:12.19 - [INFO] scan_ip add ip:2607:f8b0:400a:e::9 time:276 h2:0

5月 07 18:58:12.19 - [INFO] remove_slowest_ip:2607:f8b0:400f:d::a handshake_time:1118, fails:0

5月 07 18:58:12.20 - [INFO] GAE t:1024 s:73381 GET http://p1.music.126.net/3yrr0Dnciz6ixJ-Vs0u3TQ==/109951163286558110.jpg?param=540y200&quality=100 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4000:3a::c,0:h1_req,0:h1_req_sended,359:response_begin,0:h1_get_head,0:get_response,664:h1_finish[SP:72157],:0

5月 07 18:58:12.21 - [INFO] GAE t:1016 s:58068 GET http://p1.music.126.net/7c1Mb3dZLgdrROj_WE0MTA==/109951163286554241.jpg?param=540y200&quality=100 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400b:d::9,0:h1_req,0:h1_req_sended,421:response_begin,0:h1_get_head,0:get_response,594:h1_finish[SP:57619],:0

5月 07 18:58:12.24 - [INFO] GAE t:1701 s:18348 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2405:4800:100:29::f,0:h1_req,0:h1_req_sended,1309:response_begin,0:h1_get_head,0:get_response,391:h1_finish[SP:10955],:0

5月 07 18:58:12.25 - [INFO] GAE t:1955 s:22846 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2600:2:300:1::d,0:h1_req,0:h1_req_sended,1463:response_begin,0:h1_get_head,0:get_response,491:h1_finish[SP:11834],:0

5月 07 18:58:12.27 - [DEBUG] create_ssl update ip:2001:ee0:3201::e time:1837 h2:0 sni:xnet-203218.appspot.com, host:xnet-203218.appspot.com

5月 07 18:58:12.28 - [INFO] GAE t:978 s:63003 GET http://p1.music.126.net/8dk0aPBeR6_QTIUdgtD_qA==/109951163286668076.jpg?param=540y200&quality=100 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4000:3b::8,0:h1_req,0:h1_req_sended,375:response_begin,0:h1_get_head,0:get_response,602:h1_finish[SP:64953],:0

5月 07 18:58:12.53 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48788

5月 07 18:58:12.65 - [DEBUG] create_ssl update ip:2800:e0:c74::13 time:1212 h2:0 sni:xxnet02-201516.appspot.com, host:xxnet02-201516.appspot.com

5月 07 18:58:12.66 - [DEBUG] create_ssl update ip:2402:800:6350:14::d time:1723 h2:0 sni:xxnet01-201500.appspot.com, host:xxnet01-201500.appspot.com

5月 07 18:58:13.05 - [INFO] GAE t:1148 s:18591 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:14::9,0:h1_req,0:h1_req_sended,883:response_begin,0:h1_get_head,0:get_response,264:h1_finish[SP:16437],:0

5月 07 18:58:14.05 - [INFO] GAE t:1515 s:18353 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:10::9,0:h1_req,0:h1_req_sended,843:response_begin,0:h1_get_head,0:get_response,671:h1_finish[SP:12300],:0

5月 07 18:58:14.52 - [INFO] scan_ip add ip:2607:f8b0:400a:14::c time:279 h2:0

5月 07 18:58:14.52 - [INFO] remove_slowest_ip:2800:e0:c74::13 handshake_time:1169, fails:0

5月 07 18:58:16.51 - [INFO] scan_ip add ip:2607:f8b0:4006:3f::a time:447 h2:0

5月 07 18:58:16.51 - [INFO] remove_slowest_ip:2402:800:6350:14::d handshake_time:1168, fails:0

5月 07 18:58:16.54 - [DEBUG] create_ssl update ip:2001:ee0:3201:2::12 time:4090 h2:0 sni:xxnet01-201500.appspot.com, host:xxnet01-201500.appspot.com

5月 07 18:58:16.77 - [DEBUG] create_ssl update ip:2607:f8b0:400a:e::9 time:715 h2:0 sni:shopping.map.weekend.org, host:

5月 07 18:58:17.92 - [INFO] scan_ip add ip:2607:f8b0:400a:5::10 time:283 h2:0

5月 07 18:58:17.93 - [INFO] remove_slowest_ip:2001:ee0:3201:2::12 handshake_time:1189, fails:0

5月 07 18:58:18.30 - [DEBUG] report_connect_fail:2a00:1450:400e:4c::19

5月 07 18:58:18.30 - [DEBUG] connect 2a00:1450:400e:4c::19 fail:error('certificate is none, sni:xxnet02-201516.appspot.com',)

5月 07 18:58:18.69 - [INFO] scan_ip add ip:2a00:1450:400a:2::13 time:449 h2:0

5月 07 18:58:18.70 - [INFO] remove_slowest_ip:2a00:1450:400e:4c::19 handshake_time:680, fails:1

5月 07 18:58:20.30 - [DEBUG] GAE POST /api/linux/forward from:127.0.0.1:48788

5月 07 18:58:20.89 - [INFO] GAE t:593 s:1504 POST http://music.163.com/api/linux/forward 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4002:10::9,0:h1_req,0:h1_req_sended,584:response_begin,0:h1_get_head,0:get_response,7:h1_finish[SP:3011],:0

**Comment by l17es** [comment]
系统环境：DEEPIN 15.5

**Comment by dahai058** [comment]
我也用网易云音乐，如果是pac智能模式应该不会走代理。

**Comment by l17es** [comment]
我是linux，没地方调整这个

**Comment by xxnet** [comment]
​用8086端口，智能代理就好了

**Comment by l17es** [comment]
OK了，原来我之前用的都是8087端口，所以才走的全局代理。。。，用了自动代理 http://127.0.0.1:8086/proxy.pac 就好了。
