### ISSUE TITLE
说个不是问题的问题（win10新版本，ipv6相关）

### ISSUE THREAD

**Issue by operammm** [XX-net/XX-Net#10613]
我的win10更新到1803，ipv6就一直显示无网络访问权限了。1709是正常的。
运行了一下XX-Net\code\default\gae_proxy\local\ipv6_tunnel\enable_ipv6.bat这个文件。
虽然以太网的状态仍然是IPv6无网络访问权限，不过xx-net至少能用了。
完全不明白为啥。据说1803对ipv6有一些新的调整？

**Comment by AnyWAT** [comment]
没感觉出来：据说1803对ipv6有一些新的调整？
1709是正常的：以太网的状态是（原生）IPv6有网络访问权限？
1709、1803以太网的状态均是IPv6无网络访问权限，不过通过IPv6隧道的xx-net一直能用
