### ISSUE TITLE
部署了多次APPID，这次为啥不弹出窗口了。

### ISSUE THREAD

**Issue by xpf7622** [XX-net/XX-Net#10629]
今天部署APPID, 但没有弹出窗口。明明我的chrome已经设置允许localhost:8085 弹出窗口，但就是没有弹出窗口，XX-状态显示：XX-Net 3.11.10，一切正常，你可以访问真正的互联网了。
诊断信息如下：

XX-Net Status:

sys-platform: x86_64, Linux-4.13.0-39-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018
os-release: 4.13.0-39-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:1 ipv6:326
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:6 h2:0
scan-ip-thread-num: 98
ip-quality: 291
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
@ORO44 上面的状态哪里不正常？
