### ISSUE TITLE
下载 torbrowser 被篡改

### ISSUE THREAD

**Issue by 253681319** [XX-net/XX-Net#10623]
下 https://dist.torproject.org/torbrowser/7.5.3/
hash对不上，pgp验证不通过，细思极恐，小伙伴们试试。

**Comment by SeaHOH** [comment]
发这里的原因是？

**Comment by 253681319** [comment]
@SeaHOH 通过xx下的啊，你试试

**Comment by SeaHOH** [comment]
哦，你没写清楚。

通过哪个通道下载的，GAE 还是 X-Tunnel？

**Comment by 253681319** [comment]
@SeaHOH  GAE

**Comment by SeaHOH** [comment]
刚刚试过，没有问题，怀疑是你的 IP 数量过少或延迟太高，导致 autorange 合并出错。

其实这个地址可以直连。

**Comment by 253681319** [comment]
@SeaHOH 有可能是这个问题，最后发现可以直连的，thanks！
