### ISSUE TITLE
苹果如何翻墙？

### ISSUE THREAD

**Issue by ywcnba** [XX-net/XX-Net#10626]
xx-net可以用来苹果翻墙吗？

**Comment by SeaHOH** [comment]
不知道你说的苹果是？
请自行搜索 `ios`、`mac`、`ipad` 等关键字。

**Comment by ilovebamboo** [comment]
用来做什么？

**Comment by ywcnba** [comment]
# @SeaHOH ios

**Comment by ywcnba** [comment]
@ilovebamboo 使用外国的app呗

**Comment by erdcy** [comment]
@ywcnba 
SeaHOH正解，就是这两步，第一步可以通过电子邮件把CA发到ios上，然后打开邮件附件；第二步好像是在设置，通用，描述文件和设备管理，信任证书。

**Comment by SeaHOH** [comment]
关闭后仍可回复
