### ISSUE TITLE
维基解密中文网上不去怎么解

### ISSUE THREAD

**Issue by lh471921250** [XX-net/XX-Net#10627]
如题
维基解密中文网地址：https://wikileaks.org.cn/
显示这样

![qq 20180508174304](https://user-images.githubusercontent.com/14818014/39750277-6d1d6b04-52e7-11e8-86a6-c59666c2dc06.png)
PS：xx-net是可以正常使用的。

**Comment by SeaHOH** [comment]
服务器在国内，你可以尝试全局 gae 代理来访问它。

**Comment by bitternolis** [comment]
同样打不开这网站，无论gae全局代理或者x-tunnel东京|芝加哥结点，都无法访问。可能这网站服务器自己的问题？

**Comment by SeaHOH** [comment]
服务器 IP 在国内

**Comment by imldf** [comment]
这个没有中文网吧，怕是钓鱼
