### ISSUE TITLE
流量用完

### ISSUE THREAD

**Issue by xpf7622** [XX-net/XX-Net#10624]
我下载量很少，十个左右appid，没怎么下，就提示流量用完。是不是XX-net把我的appid当作公用的了？

**Comment by SeaHOH** [comment]
贴 GAEProxy状态统计信息

**Comment by xpf7622** [comment]
在什么地方找？

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/配置页面简介
