### ISSUE TITLE
3.11.11 IPv6 自助开启不起作用

### ISSUE THREAD

**Issue by cctoking** [XX-net/XX-Net#10622]
## _已经更新到了最新版本 卸载重新安装过没用.

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:45 ipv4:0 ipv6:22
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 26
ip-quality: 1183
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
不用修改主楼，请跟帖。
上面说的自助开启尝试过没有？

**Comment by cctoking** [comment]
尝试下载3.11.11测试版本依旧 "仅IPv6" 不可用，请检查。

**Comment by SeaHOH** [comment]
IPv6 Fail 旁边难道没有链接吗？

**Comment by cctoking** [comment]
没有. 我复制过来这段就是原文 （"仅IPv6" 不可用，请检查。）后面没其他东西.很奇怪我前几天还在用但是突然就这样了.

**Comment by cctoking** [comment]
根据你提供的帖子下方的一个回复 试了设置 IPV6配置转换 为‘自动’依旧无法使用

**Comment by SeaHOH** [comment]
点击“高级”，再点“ IPv6 隧道”。

**Comment by cctoking** [comment]
点击“高级”，再点“ IPv6 隧道”。 显示禁用 我选择启动显示IPv6 tunnel is enabled, please reboot system.但是此时下方依旧显示'已禁用' 重启系统后依旧显示 "仅IPv6" 不可用，请检查。

**Comment by cctoking** [comment]
如果选择更换服务器的时候又显示 Don't epeated, please retry in 3 minutes later....但是3分钟后依旧是Don't epeated, please retry in 3 minutes later.

**Comment by SeaHOH** [comment]
没有出现 CMD 窗口吗？

**Comment by cctoking** [comment]
没有

**Comment by SeaHOH** [comment]
感谢反馈，原来我搞了个大 bug。。。

**Comment by SeaHOH** [comment]
已修复，新下载 3.11.12 版本。

**Comment by cctoking** [comment]
搜索不到相关31112版本的下载噢是需要等一等吗...还是谢谢你们的及时回复 困扰好久天天都在折腾

**Comment by SeaHOH** [comment]
点上方 code，再点 releases。

**Comment by cctoking** [comment]
没看到3.11.12 就下载了测试版3.11.13 现在点击启动有CMD 。但是重启后 问题依旧存在仅“IPV6” 不可用

**Comment by SeaHOH** [comment]
以前成功使用过 IPv6 吗？
你先用这个测试一下 #10328 ，把结果贴出来。

**Comment by cctoking** [comment]
我之前一直再用XX 不过我最近出这个问题后尝试过这个设置不知道是否有影响？http://bbs.pcbeta.com/viewthread-1580771-1-1.html
类型                    : disabled (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by SeaHOH** [comment]
你的组策略强制关闭了 teredo，把组策略恢复到未设置状态。

**Comment by SeaHOH** [comment]
运行 gpedit.msc，找到“IPv6 转换技术”，按照下图把右边恢复成未配置状态。
![x2scrap2](https://user-images.githubusercontent.com/8470820/39871296-dde582f0-5453-11e8-8a00-99a4869a6df1.png)

**Comment by cctoking** [comment]
看来我遇到BUG黑洞 ...全部设置为 未配置后 重启 尝试修复IPV6 再重启 问题依旧存在.放弃了 还是谢谢！

**Comment by cctoking** [comment]
找到问题根源了 Teredo状态 设置成-已启用-默认状态 问题解决！

**Comment by SeaHOH** [comment]
你之前恢复未配置状态后，没有再重新运行启用脚本吗？

**Comment by cctoking** [comment]
有
