### ISSUE TITLE
怎么可以cmd也可以上？现在只是 浏览器可以

### ISSUE THREAD

**Issue by paihuai00** [XX-net/XX-Net#10636]
没有在issues得到解决方法，想询问一下，是否可以？
![image](https://user-images.githubusercontent.com/20215838/39792022-3477dc6e-5371-11e8-854a-692e8cbefa96.png)

 怎么可以Cmd也连接外网啊？  现在只是 google浏览器能上

**Comment by SeaHOH** [comment]
关闭后仍可回复
