### ISSUE TITLE
如图 无法勾选选全局通过GAE 和其它任何菜单 

### ISSUE THREAD

**Issue by lt201081** [XX-net/XX-Net#10638]
![default](https://user-images.githubusercontent.com/31964103/39792612-09345674-5374-11e8-804d-af0d417134a2.png)

属性 | 值
-- | --
XX-Net Version | 3.11.10
Python Version | 2.7.13
OpenSSL Version | 16.0.0 TLSv1_2 h2:alpn
System Platform | AMD64, Windows-10-10.0.17134
OS System | Windows
OS Version | 10.0.17134
OS Release | 10
OS Detail | Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language | zh_CN
Architecture | 32bit,WindowsPE
Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by lt201081** [comment]
现在只能通过浏览器 插件Proxy SwitchyOmega  来实现切换 暂时空运正常使用

**Comment by SeaHOH** [comment]
#10620 #10609
