### ISSUE TITLE
X-Tunnel 用不了啊

### ISSUE THREAD

**Issue by ORO44** [XX-net/XX-Net#10634]
去买了试一下，结果还没有自己配置的GaeProxy的速度快。google，youtueb经常显示：相应时间过长无法访问此网站。。。。。。就同时开Google和YouTube，就要加载个一两分钟。。。居然还默认先使用本地APPID流量。。。就在刚才google也彻底上不去了

**Comment by ORO44** [comment]
ps:我使用的是X-Tunel代理模式。不是gae

**Comment by ORO44** [comment]
重启了N次XX-Net都不行，最后重启电脑后终于可以用了。。。。。。

**Comment by xxnet** [comment]
​X-Tunnel的相应速度是会慢一点的，GAE的速度，比直连都要快，即使没有墙。

公共appid的流量很多，不过暂时是没有区分，所以x-tunnel也会用你私人的appid流量，如果你设置了私人的appid。

**Comment by webCnZ** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
不能使用，求助

**Comment by SeaHOH** [comment]
使用 releases 页面的最新测试版本。
IPv6 Fail 时点“尝试修复”，再点“切换 teredo 服务器”。

**Comment by SeaHOH** [comment]
关闭后仍可回复
