### ISSUE TITLE
提示无效的 无效AppID 

### ISSUE THREAD

**Issue by lt201081** [XX-net/XX-Net#10631]
提示无效的 无效AppID

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/10533#issuecomment-383509145
善用搜索和标签

**Comment by lt201081** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
解决不了 ！



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年5月8日 23:49，SeaHOH<notifications@github.com> 写道： 


#10533 (comment)
善用搜索和标签

**Comment by SeaHOH** [comment]
那你多写点情况说明，这一句，我也只能这样回。
