### ISSUE TITLE
3.10.4 目前还是最NB的，之后所有版本，我这里都无法播放油管视频。

### ISSUE THREAD

**Issue by laowalter** [XX-net/XX-Net#10648]
3.10.4 目前还是最NB的，之后所有版本，我这里都无法播放油管视频，使得我在学习科学的过程中，不得不使用3.10.4.

之后的版本，包括最新的3.11.3都是可以进入播放页面，但却永远出现播放加载的那个“圈圈”，那个“圈圈”绕啊绕啊，页面的其他内容都出来了，但是它还在绕啊绕啊绕，换到3.10.4, 奇迹就立刻出现了。

btw，我是用linux。

**Comment by whhxmwhh** [comment]
哈哈。你的跟我很像哦。只是网络问题与xxnet无关的。
家里的xxnet一直飞快的。
换新的版本有修复ipv6 的工具很实用。
不行了点击几下。重启系统就好了。。希望能加入解决DNS干扰的更好。。

**Comment by laowalter** [comment]
试过无数遍了,只能用3.10.4。很遗憾，新版本与我无关。

**Comment by MadMaxPayne8964** [comment]
然而我这里3.10.4一个月前就彻底废了不能用了，延迟9999，IP数目飞快掉到个位数。3.11之后版本可用，虽然延迟高

**Comment by ouqiuming** [comment]
为什么还用xxnet  SSR资源那么多

**Comment by SeaHOH** [comment]
@laowalter 
问题找到了，你的 `*.googlevideo.com` 是直连，但是我没明白怎么会这样。
你的 data 文件夹内有修改过的 config.json？

**Comment by laowalter** [comment]
@SeaHOH, 谢谢，正如你说的，我在config.json中有 

 `"hosts_direct_endswith": [
    ".appspot.com",
    ".googlevideo.com"
  ]`
在3.10.4后的版本开始读config.json了，所以，这个配置就一直起作用，记得当时不知是哪位老兄在issues上建议的。 去掉了这个配置，现在在3.11.4上一切正常了。谢谢！ xx-net 确实很棒！

**Comment by SeaHOH** [comment]
这是害人啊，又没有做 host 域名对应。
