### ISSUE TITLE
[发布] 3.11.13 修复3.11.12版本无法登陆x-tunnel

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#10646]
修复3.11.12版x-tunnel无法登陆。

需要解决deflate编码乱码的，也可以升级到这个版本。

**Comment by yoholo** [comment]
3.11.13版本没有导入证书操作，自行导入后重启正常，但是重启几次后又出现“请导入浏览器CA证书。”

**Comment by SeaHOH** [comment]
你说的“没有导入证书操作”是指 XX-Net 启动时没有弹出请求权限来导入证书的窗口吗？

**Comment by yoholo** [comment]
是的 重启后出现没有导入证书现象 删data还是这样

**Comment by SeaHOH** [comment]
已修复。
你可以手动更新，或者暂时不更新使用 bat 文件启动也行。

**Comment by thurse** [comment]
3.11.13 google翻译无法使用，提示翻译时出错

**Comment by SeaHOH** [comment]
@thurse 把相关日志贴到 #10661
