### ISSUE TITLE
为啥我的ip数量总是少的可怜啊，而且延迟还很高的啊

### ISSUE THREAD

**Issue by zhuhaxixiong** [XX-net/XX-Net#10640]
![image](https://user-images.githubusercontent.com/28261361/39799421-bbe0c920-5396-11e8-99fe-696dd8467883.png)

**Comment by foho8080** [comment]
我這裡ip數500 延遲700多

**Comment by dahai058** [comment]
3百多不高，能正常使用就行了。

**Comment by xdg92** [comment]
我刚才延迟1500多，照料能看YT，但网页就打开很慢。今天情况反着来。

**Comment by SeaHOH** [comment]
你这简直太正常了，好多人羡慕的。
