### ISSUE TITLE
最新版在Win10 下无法启用teredo，但是enable_ipv6.bat 可以

### ISSUE THREAD

**Issue by XXfuns** [XX-net/XX-Net#10649]
刚装的Win10系统，最新版本17134，iso的链接：
ed2k://|file|cn_windows_10_consumer_editions_version_1803_updated_march_2018_x64_dvd_12063766.iso|4714162176|FB8C05DE594CD7E58D88993652DD2102|/

在Web界面上启用Ipv6，试了2次都没有成功，重启也不行。
后来执行ipv6_tunnel目录下的enable_ipv6.bat就可以了。

下面是是诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
xxnet-version: 3.11.13
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:67 ipv4:0 ipv6:25
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:7 h2:0
scan-ip-thread-num: 10
ip-quality: 1006
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
网页 UI 点击启用时，是否有 CMD 窗口弹出？

**Comment by XXfuns** [comment]
有的，提示也挺正常的，但是没有效果。

**Comment by SeaHOH** [comment]
有点奇怪，除了设置 teredo 服务器这句，运行的内容基本上相同。

**Comment by SeaHOH** [comment]
你先在网页 UI 中点一次“切换服务器”，看看完成后 teredo 状态是否正常。

如果不正常，管理员权限运行这条和 enable_ipv6.bat 里一样的命令来恢复。
`netsh interface teredo set state type=enterpriseclient servername=teredo.remlab.net.`

**Comment by XXfuns** [comment]
“切换服务器”之后依然正常。

之前执行ipv6_tunnel目录下的enable_ipv6.bat 之前，设备管理器里找不到Teredo网卡，执行后就找到了，也不用重启，ipv6立即就通了。

**Comment by SeaHOH** [comment]
“切换服务器”也正常。
点网页按钮和直接点 bat 文件，除了 `ipconfig /flushdns` 的位置不同，其它一模一样。

会不会是凑巧前两次刚好因为其它原因导致不成功？

**Comment by beiking** [comment]
我看了代码，简单修复了下，Win7下解决问题。
common.py
39行：return server[0]

win10.py
115行：Reg add HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f
118行：Reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters /v DisabledComponents /t REG_DWORD /d 0 /f
建议 HKEY_LOCAL_MACHINE 都简写成 HKLM
178行：r = run("ipconfig /all")

@SeaHOH 看下，我改的有没问题。

**Comment by XXfuns** [comment]
我恢复来 刚装好的状态，“切换服务器”的时候，抛了异常：

May 11 10:34:08.126 [simple_http_server][ERROR] handler:IndexError('list index out of range',) cmd:GET path:/module/gae_proxy/control/ipv6_tunnel?cmd=set_best_server from:127.0.0.1:58494
May 11 10:34:08.126 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "C:\xxnet\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 166, in handle_one_request
    self.do_GET()
  File "C:\xxnet\code\default\launcher\web_control.py", line 128, in do_GET
    controler.do_GET()
  File "C:\xxnet\code\default\gae_proxy\local\web_control.py", line 155, in do_GET
    return self.req_ipv6_tunnel_handler()
  File "C:\xxnet\code\default\gae_proxy\local\web_control.py", line 721, in req_ipv6_tunnel_handler
    result = ipv6_tunnel.set_best_server(is_local)
  File "C:\xxnet\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 252, in set_best_server
    % (client_type(), best_server()))
  File "C:\xxnet\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 173, in client_type
    ip = [line for line in run("route print").split("\r\n") if " 0.0.0.0 " in line][0].split()[-2]
IndexError: list index out of range


看了代码，试着执行route print，输出是这样的：

C:\Users\win>route print
===========================================================================
接口列表
  4...08 00 27 cf 5a b8 ......Intel(R) PRO/1000 MT Desktop Adapter
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  1    331 ::1/128                  在链路上
  1    331 ff00::/8                 在链路上
===========================================================================
永久路由:
  无
-----------------------------------------------------------------

**Comment by SeaHOH** [comment]
@beiking 
感谢！又帮我找出来了，自己实在是看不到。。。

@XXfuns
我会尝试忽略这个错误，不过你的路由是不是有问题？怎么只有 IPv4 环回地址。

**Comment by beiking** [comment]
178行，，你原先写成了 ifconfig /all

**Comment by SeaHOH** [comment]
哦，原来是这样，眼瞎得厉害。。。

不过这个终于不是我的锅啦，其实这个函数是没有使用的。甩锅~

开个玩笑，缓解下我内心的尴尬。你真是细心，谢谢啦。

**Comment by XXfuns** [comment]
@SeaHOH
 之前是网线没有插好的情况，才会没有 0.0.0.0的路由。

插上网线后是这样：
C:\Users\win>route print
===========================================================================
接口列表
  4...08 00 27 cf 5a b8 ......Intel(R) PRO/1000 MT Desktop Adapter
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0         10.0.2.2        10.0.2.15     25
         10.0.2.0    255.255.255.0            在链路上         10.0.2.15    281
        10.0.2.15  255.255.255.255            在链路上         10.0.2.15    281
       10.0.2.255  255.255.255.255            在链路上         10.0.2.15    281
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上         10.0.2.15    281
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上         10.0.2.15    281
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  1    331 ::1/128                  在链路上
  4    281 fe80::/64                在链路上
  4    281 fe80::cccc:d8cc:fcd7:3eb/128
                                    在链路上
  1    331 ff00::/8                 在链路上
  4    281 ff00::/8                 在链路上
===========================================================================
永久路由:
  无

重新执行启用后，没有再抛之前的异常了，在Web下面的输出中，发一个可疑的输出：
C:\Windows\system32>netsh interface ipv6 show prefixpolicy
找不到下列命令: interface ipv6 show prefixpolicy。

下面是启用的日志：
C:\Windows\system32>ipconfig /all

Windows IP 配置

主机名 . . . . . . . . . . . . . : DESKTOP-D8J3MG6
主 DNS 后缀 . . . . . . . . . . . :
节点类型 . . . . . . . . . . . . : 混合
IP 路由已启用 . . . . . . . . . . : 否
WINS 代理已启用 . . . . . . . . . : 否
DNS 后缀搜索列表 . . . . . . . . : Home

以太网适配器 以太网:

连接特定的 DNS 后缀 . . . . . . . : Home
描述. . . . . . . . . . . . . . . : Intel(R) PRO/1000 MT Desktop Adapter
物理地址. . . . . . . . . . . . . : 08-00-27-CF-5A-B8
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是
本地链接 IPv6 地址. . . . . . . . : fe80::cccc:d8cc:fcd7:3eb%4(首选)
IPv4 地址 . . . . . . . . . . . . : 10.0.2.15(首选)
子网掩码 . . . . . . . . . . . . : 255.255.255.0
获得租约的时间 . . . . . . . . . : 2018年5月11日 17:35:00
租约过期的时间 . . . . . . . . . : 2018年5月12日 17:35:02
默认网关. . . . . . . . . . . . . : 10.0.2.2
DHCP 服务器 . . . . . . . . . . . : 10.0.2.2
DHCPv6 IAID . . . . . . . . . . . : 67633191
DHCPv6 客户端 DUID . . . . . . . : 00-01-00-01-22-87-17-6F-08-00-27-CF-5A-B8
DNS 服务器 . . . . . . . . . . . : 192.168.0.1
TCPIP 上的 NetBIOS . . . . . . . : 已启用

C:\Windows\system32>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型 : disabled
服务器名称 : win1711.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : offline
错误 : 无


C:\Windows\system32>netsh interface ipv6 show route

发布 类型 跃点数 前缀 索引 网关/接口名称
------- -------- --- ------------------------ --- ------------------------
否 系统 256 ::1/128 1 Loopback Pseudo-Interface 1
否 系统 256 fe80::/64 4 以太网
否 系统 256 fe80::cccc:d8cc:fcd7:3eb/128 4 以太网
否 系统 256 ff00::/8 1 Loopback Pseudo-Interface 1
否 系统 256 ff00::/8 4 以太网


C:\Windows\system32>netsh interface ipv6 show interface

Idx Met MTU 状态 名称
--- ---------- ---------- ------------ ---------------------------
1 75 4294967295 connected Loopback Pseudo-Interface 1
4 25 1500 connected 以太网


C:\Windows\system32>netsh interface ipv6 show prefixpolicy
找不到下列命令: interface ipv6 show prefixpolicy。

C:\Windows\system32>netsh interface ipv6 show address

接口 1: Loopback Pseudo-Interface 1

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite ::1

接口 4: 以太网

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite fe80::cccc:d8cc:fcd7:3eb%4


C:\Windows\system32>route print
===========================================================================
接口列表
4...08 00 27 cf 5a b8 ......Intel(R) PRO/1000 MT Desktop Adapter
1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标 网络掩码 网关 接口 跃点数
0.0.0.0 0.0.0.0 10.0.2.2 10.0.2.15 25
10.0.2.0 255.255.255.0 在链路上 10.0.2.15 281
10.0.2.15 255.255.255.255 在链路上 10.0.2.15 281
10.0.2.255 255.255.255.255 在链路上 10.0.2.15 281
127.0.0.0 255.0.0.0 在链路上 127.0.0.1 331
127.0.0.1 255.255.255.255 在链路上 127.0.0.1 331
127.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 10.0.2.15 281
255.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
255.255.255.255 255.255.255.255 在链路上 10.0.2.15 281
===========================================================================
永久路由:
无

IPv6 路由表
===========================================================================
活动路由:
接口跃点数网络目标 网关
1 331 ::1/128 在链路上
4 281 fe80::/64 在链路上
4 281 fe80::cccc:d8cc:fcd7:3eb/128
在链路上
1 331 ff00::/8 在链路上
4 281 ff00::/8 在链路上
===========================================================================
永久路由:
无

C:\Windows\system32>goto :eof

**Comment by SeaHOH** [comment]
谢谢，这回大概正常了。 :trollface:

**Comment by XXfuns** [comment]
用新版 3.11.14就好了，谢谢 @SeaHOH
​
