### ISSUE TITLE
导入 switchyomega 后更新情景模式，显示更新时网络错误

### ISSUE THREAD

**Issue by lifeacg** [XX-net/XX-Net#10643]
switchyomega将switchyomega.bak导入之后，更新情景模式时，规则列表下面有行字，修改网址后尚未下载更新，因此规则列表过时。我点更新情景模式后，先似乎更新时网络错误

**Comment by lifeacg** [comment]
我点更新情景模式后，显示更新时网络错误。我的网络时没问题的，这是怎么回事？求教各位大神

**Comment by SeaHOH** [comment]
请确保能正常访问 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by SebastianYan** [comment]
我也遇到了这个问题，现在还没解决

**Comment by AnyWAT** [comment]
貌似有代理本身正常的前提👀

**Comment by alexwongdl** [comment]
可以正常访问 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt，但是报同样的错误

**Comment by shangguanchenxin** [comment]
我也遇到这个问题，IE浏览器的时候，firefox就没问题。

**Comment by shangguanchenxin** [comment]
> [https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt%EF%BC%8C%E4%BD%86%E6%98%AF%E6%8A%A5%E5%90%8C%E6%A0%B7%E7%9A%84%E9%94%99%E8%AF%AF)

对，IE浏览器是压根无法正常访问[https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt%EF%BC%8C%E4%BD%86%E6%98%AF%E6%8A%A5%E5%90%8C%E6%A0%B7%E7%9A%84%E9%94%99%E8%AF%AF)

**Comment by shangguanchenxin** [comment]
> 可以正常访问 [https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt，但是报同样的错误](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt%EF%BC%8C%E4%BD%86%E6%98%AF%E6%8A%A5%E5%90%8C%E6%A0%B7%E7%9A%84%E9%94%99%E8%AF%AF)

对，IE浏览器是压根无法正常访问对，IE浏览器是压根无法正常访问[https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt]

**Comment by shangguanchenxin** [comment]
无法正常访问[https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt，是因为什么呢？

**Comment by Piggerfly** [comment]
可以访问txt但是仍然更新错误是为什么呐
