### ISSUE TITLE
为什么GAEProxy 状态信息说我的ipv6开启，但是网络共享中心我的是关闭的

### ISSUE THREAD

**Issue by 2465068058** [XX-net/XX-Net#10655]
GAEProxy 状态信息：

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK

网络共享中心：
ipv6连接：   无网络访问权限。‘

**Comment by SeaHOH** [comment]
无需理会，XX-Net 能用就好。
