### ISSUE TITLE
创建appid时，https://console.cloud.google.com/start打不开

### ISSUE THREAD

**Issue by syjy2** [XX-net/XX-Net#10658]
之前有创建过，现在想多创建几个，但是创建appid时，https://console.cloud.google.com/start 打不开，所以第一步就卡住了。。。

**Comment by xpf7622** [comment]
我的 也是打开半截，就进行不下去了，貌似速度太慢。

**Comment by RudolphBrown** [comment]
这个需要修改hosts以及改ipv6,现在ipv4貌似使用不了.

**Comment by syjy2** [comment]
我开启了ipv6，电脑也可以翻墙，就是打不开创建appid的网站，是不是把这个通道关了？

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/39953404-e8c2e2b8-55dd-11e8-8832-1b334f1b0783.png)

**Comment by syjy2** [comment]
网址是什么呢？图片上后面的看不到了

**Comment by SeaHOH** [comment]
就是这个网址自动跳转的，用 Chrome 试试。

**Comment by AnyWAT** [comment]
网址是什么呢：就是顶楼的

**Comment by syjy2** [comment]
可能我浏览器问题，麻烦各位了，我用手机能打开这个网站，但是在手机界面里没有创建新appid的按钮。。。。就是没有那个“+”，有点崩溃

**Comment by syjy2** [comment]
已解决。。原来是我xx-net版本问题，谢谢各位
