### ISSUE TITLE
13修复后，显示 连接尚未建立。

### ISSUE THREAD

**Issue by hongkonghot** [XX-net/XX-Net#10652]
IPv4 状态 | OK
IPv6 状态(如何开启) | OK

IPv6 隧道 | 已启用

就是显示 连接尚未建立。

另外截取了部分 GAEProxy 日志：

May 10 20:43:23.656 - [WARNING] gae_exception:'600:fetch gae fail' https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/pms/img/st.gif?ts=31a1&sid=jh0itpn30l4&page=9_3242&pid=241&p=9&dv=6&px=1366*768&ver=5&cmd=open

May 10 20:43:23.656 - [WARNING] gae_exception:'600:fetch gae fail' https://gsp0.baidu.com/5aAHeD3nKhI2p27j8IqW0jdnxx1xbK/tb/pms/img/st.gif?ts=31a2&t=exception&sid=jh0itpn30l4&page=9_3242&pid=170&dv=7&p=9&msg=passport%20is%20not%20defined&js=indexher%3Astatic%2Fjs%2Flogin.js&ln=58&flag=catch

May 10 20:43:26.059 - [WARNING] task POST None /_gh/ timeout

May 10 20:43:26.060 - [DEBUG] GAE_Exception 600 'fetch gae fail'

May 10 20:43:26.060 - [WARNING] gae_exception:'600:fetch gae fail' https://www.alimama.com/favicon.ico

May 10 20:43:27.862 - [WARNING] task POST None /_gh/ timeout

May 10 20:43:27.864 - [DEBUG] GAE_Exception 600 'fetch gae fail'

May 10 20:43:27.865 - [WARNING] gae_exception:'600:fetch gae fail' http://bbs.bt5156.com/favicon.ico

全部是 GAE_Exception 600 ，什么情况？

**Comment by xxnet** [comment]
​发多一些日志出来

**Comment by hongkonghot** [comment]
@xxnet 重启了一下 xxnet ，日志内容变了：


May 10 21:06:30.715 - [INFO] ------------------------------------------------------

May 10 21:06:30.715 - [INFO] Python Version : 2.7.13

May 10 21:06:30.715 - [INFO] OS : Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

May 10 21:06:30.715 - [INFO] Listen Address : 127.0.0.1:8087

May 10 21:06:30.715 - [INFO] GAE APPID : xxxxxx

May 10 21:06:30.715 - [INFO] ------------------------------------------------------

May 10 21:06:31.340 - [DEBUG] Importing CA

May 10 21:06:31.340 - [DEBUG] Removing windows CA

May 10 21:06:31.371 - [DEBUG] Begin to import Windows CA

May 10 21:06:31.387 - [INFO] SSL use version:TLSv1_2

May 10 21:06:31.387 - [INFO] OpenSSL support alpn

May 10 21:06:31.387 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-master\code\default\gae_proxy\local\ip_range.txt

May 10 21:06:31.387 - [INFO] load ip_list num:60, target num:60

May 10 21:06:31.403 - [INFO] SSL use version:TLSv1_2

May 10 21:06:31.403 - [INFO] server 127.0.0.1:8087 started.

May 10 21:06:31.528 - [DEBUG] network IPv4 is ok, cost:907 ms

May 10 21:06:32.533 - [DEBUG] create_ssl update ip:2404:4408:2:5100::c time:1128 h2:0 sni:training.obligation.march.com, host:

May 10 21:06:32.973 - [DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=c7af811d-952a-4483-96bf-44a6d9b80274&version=3.11.13&platform=Windows-8.1-6.3.9600

May 10 21:06:33.238 - [DEBUG] create_ssl update ip:2800:200:2008:5c0::c time:1834 h2:0 sni:xxxxxx.appspot.com, host:xxxxxx.appspot.com

May 10 21:06:34.271 - [DEBUG] create_ssl update ip:2a05:fdc0:2200::f time:722 h2:0 sni:actionreference.us, host:

May 10 21:06:34.585 - [INFO] DIRECT t:1611 s:1674 200 xxnet-update.appspot.com /update.json?uuid=c7af811d-952a-4483-96bf-44a6d9b80274&version=3.11.13&platform=Windows-8.1-6.3.9600

May 10 21:06:34.948 - [DEBUG] create_ssl update ip:2001:8f0:103:104::e time:943 h2:0 sni:chance.equipment.net, host:

May 10 21:06:35.015 - [DEBUG] create_ssl update ip:2a05:fdc0:2200::13 time:723 h2:0 sni:xxxxxx.appspot.com, host:xxxxxx.appspot.com

May 10 21:06:35.705 - [INFO] scan_ip add ip:2001:b032:101:1::13 time:825 h2:0

May 10 21:06:35.709 - [DEBUG] create_ssl update ip:2001:8002:e21:ef03::e time:1916 h2:0 sni:xxxxxx.appspot.com, host:xxxxxx.appspot.com

May 10 21:06:38.065 - [DEBUG] network IPv6 is ok, cost:7444 ms

May 10 21:06:38.514 - [DEBUG] report_connect_fail:2001:b000:1e0:c100::e

May 10 21:06:38.514 - [DEBUG] connect 2001:b000:1e0:c100::e fail:error('certificate is none, sni:xxxxxx.appspot.com',)

May 10 21:06:39.529 - [DEBUG] create_ssl update ip:2610:28:42c:100::e time:5274 h2:0 sni:xxxxxx.appspot.com, host:xxxxxx.appspot.com

May 10 21:06:40.012 - [DEBUG] create_ssl update ip:2001:b000:182:c100::e time:5198 h2:0 sni:xxxxxx.appspot.com, host:xxxxxx.appspot.com

May 10 21:06:41.583 - [DEBUG] create_ssl update ip:2001:2f8:0:15::d time:1306 h2:0 sni:anything-mode-key.us, host:

May 10 21:06:43.749 - [INFO] scan_ip add ip:2001:b032:2101::c time:687 h2:0

May 10 21:06:45.715 - [DEBUG] GAEProxy web_control 127.0.0.1:6320 POST /config?cmd=get_config

May 10 21:06:47.548 - [DEBUG] GAEProxy web_control 127.0.0.1:6322 POST /config?cmd=get_config

May 10 21:06:47.550 - [DEBUG] GAEProxy Web_control 127.0.0.1:6322 GET /scan_ip?cmd=get_range

May 10 21:06:47.550 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-master\code\default\gae_proxy\local\ip_range.txt

May 10 21:06:49.413 - [DEBUG] create_ssl update ip:2001:b032:101:1::13 time:1826 h2:0 sni:hospitaltermrefrigerator.ml, host:

May 10 21:06:51.008 - [DEBUG] report_connect_fail:2001:b032:2101::c

May 10 21:06:51.008 - [DEBUG] connect 2001:b032:2101::c fail:error('certificate is none, sni:xxxxxx.appspot.com',)

May 10 21:06:52.024 - [INFO] scan_ip add ip:2001:b032:5d01::12 time:1094 h2:0

May 10 21:06:52.064 - [INFO] scan_ip add ip:2001:d08:12:204::11 time:677 h2:0

May 10 21:06:54.419 - [DEBUG] create_ssl update ip:2001:d08:11:204::12 time:1406 h2:0 sni:xxxxxx.appspot.com, host:xxxxxx.appspot.com

May 10 21:07:00.426 - [DEBUG] report_connect_fail:2001:d08:10:207::13

May 10 21:07:00.426 - [DEBUG] connect 2001:d08:10:207::13 fail:error("conn fail, sni:servicepressuresky.net, top: e:timeout('timed out',)",)

May 10 21:07:01.886 - [INFO] scan_ip add ip:2001:b000:188:c101::f time:954 h2:0

May 10 21:07:02.892 - [INFO] scan_ip add ip:2001:b032:3900:1::c time:1052 h2:0

May 10 21:07:04.186 - [WARNING] h1 2001:d08:11:204::12 HEAD keep alive request fail:Exception('time out',)

May 10 21:07:04.186 - [WARNING] 2001:d08:11:204::12 trace: 0:connect, 3532:init, 2009:head,:5631, processed:0, transfered:0, sni:xxxxxx.appspot.com

May 10 21:07:04.186 - [DEBUG] 2001:d08:11:204::12 worker close:down fail

May 10 21:07:04.186 - [DEBUG] report_connect_fail:2001:d08:11:204::12

May 10 21:07:35.390 - [DEBUG] GAEProxy web_control 127.0.0.1:6320 POST /config?cmd=get_config

May 10 21:07:35.392 - [DEBUG] GAEProxy Web_control 127.0.0.1:6320 GET /scan_ip?cmd=get_range

May 10 21:07:35.392 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-master\code\default\gae_proxy\local\ip_range.txt

May 10 21:07:50.000 - [DEBUG] GAEProxy web_control 127.0.0.1:6320 POST /config?cmd=get_config

May 10 21:07:50.002 - [DEBUG] GAEProxy Web_control 127.0.0.1:6320 GET /scan_ip?cmd=get_range

May 10 21:07:50.002 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-master\code\default\gae_proxy\local\ip_range.txt

May 10 21:07:52.804 - [DEBUG] GAEProxy web_control 127.0.0.1:6320 POST /config?cmd=get_config

May 10 21:08:06.724 - [DEBUG] GAEProxy web_control 127.0.0.1:6320 POST /config?cmd=get_config

May 10 21:08:15.046 - [DEBUG] GAEProxy web_control 127.0.0.1:6321 POST /config?cmd=get_config

May 10 21:08:15.049 - [DEBUG] GAEProxy Web_control 127.0.0.1:6321 GET /scan_ip?cmd=get_range

May 10 21:08:15.049 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-master\code\default\gae_proxy\local\ip_range.txt

May 10 21:08:17.518 - [DEBUG] GAEProxy web_control 127.0.0.1:6322 POST /config?cmd=get_config

May 10 21:08:28.092 - [DEBUG] GAEProxy web_control 127.0.0.1:6322 POST /config?cmd=set_config

May 10 21:08:32.035 - [DEBUG] GAEProxy web_control 127.0.0.1:6321 POST /config?cmd=set_config

May 10 21:08:39.696 - [DEBUG] GAEProxy web_control 127.0.0.1:6982 POST /config?cmd=get_config

May 10 21:08:46.560 - [DEBUG] GAEProxy web_control 127.0.0.1:6983 POST /config?cmd=get_config

May 10 21:09:28.283 - [DEBUG] create ssl timeout fail.

May 10 21:09:32.202 - [DEBUG] create ssl timeout fail.

May 10 21:09:43.799 - [DEBUG] GAEProxy web_control 127.0.0.1:6320 POST /config?cmd=get_config

May 10 21:09:43.802 - [DEBUG] GAEProxy Web_control 127.0.0.1:6320 GET /scan_ip?cmd=get_range

May 10 21:09:43.802 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-master\code\default\gae_proxy\local\ip_range.txt

May 10 21:10:28.389 - [DEBUG] create ssl timeout fail.

May 10 21:10:32.350 - [DEBUG] create ssl timeout fail.

**Comment by SeaHOH** [comment]
你用的全局代理吗？
请切换到智能代理或 pac。
国内这些网站页面连接太多了，可能是这个原因造成 gae_proxy 不响应。

**Comment by xc1988** [comment]
我偶尔遇到这种情况  要重启一下路由器 就好了..不知道为什么

**Comment by xxnet** [comment]
​有些路由器容许的连接数有限，太多链接就会卡机，需要重启路由器。
xx-net 已经有链接数限制，但也有可能会触发路由器问题。
有些路由器负责拨号，重启路由器会让ISP重启分配资源，也有效果。
