### ISSUE TITLE
miredo不稳定

### ISSUE THREAD

**Issue by RudolphBrown** [XX-net/XX-Net#10669]
linux下支持ipv6的miredo程序总是一下子就不工作了,在GAE模块状态栏,ipv6状态显示fail.

解决的方法是找到它并杀死它,意外发现这个程序杀一次就会重启一个进程.

有办法让它稳定下吗？

harry@harry-TM1613 ~ $ ps aux | grep miredo
root      4007  0.0  0.0  26244  1944 ?        Ss   10:29   0:00 miredo
miredo   12823  0.0  0.0 130856   928 ?        Sl   19:00   0:00 miredo
root     12825  0.0  0.0   8608   800 ?        S    19:00   0:00 /usr/lib/x86_64-linux-gnu/miredo/miredo-privproc 9
harry    12850  0.0  0.0  15964  1092 pts/0    S+   19:00   0:00 grep --color=auto miredo
harry@harry-TM1613 ~ $ sudo kill -9 12823
harry@harry-TM1613 ~ $ ps aux | grep miredo
root      4007  0.0  0.0  26244  1956 ?        Ss   10:29   0:00 miredo
miredo   12939  0.0  0.0 270152   928 ?        Sl   19:00   0:00 miredo
root     12941  0.0  0.0   8608   744 ?        S    19:00   0:00 /usr/lib/x86_64-linux-gnu/miredo/miredo-privproc A
harry    13027  0.0  0.0  15964  1024 pts/0    S+   19:00   0:00 grep --color=auto miredo

**Comment by xxnet** [comment]
什么linux？
试试重启miredo服务

**Comment by RudolphBrown** [comment]
重启可以,但是就是得一段时间重启一次.
Linux Mint 18.1 Cinnamon 64-bit

**Comment by xxnet** [comment]
​有两种可能:
1. Linux版本问题
2. Teredo 受网络影响干扰断开

**Comment by SeaHOH** [comment]
关闭后仍可回复
