### ISSUE TITLE
无法播放或下载openload源的视频

### ISSUE THREAD

**Issue by z10ym** [XX-net/XX-Net#10665]
在线播放openload视频会显示the media could not be loaded,either because the serve or network failed  or because the format is not supported.
反复刷新播放有几率能正常播放。
获取视频链接到idm下载会显示“服务器响应您没有权限下载此文件 备注 http/1.1 403 ok”
类似的情况还出现在另一个国外视频网盘上
已经配置了自己的gae id，年初用的goagent也能正常使用（当然现在黄红一片了），看油管也没有问题
是openload禁了gae类代理的ip段还是代理访问速度不够导致无法加载抑或是其他原因呢？
求大佬解惑，不胜感激

**Comment by tcwilliy** [comment]
直连就行
