### ISSUE TITLE
5月12日16时 X-Tunnel 发生故障 2小时，有丢失流量的请发邮件

### ISSUE THREAD

**Issue by RudolphBrown** [XX-net/XX-Net#10667]
购买流量的页面进不去....

可能是密码不对,并没有找到修改的途径,想请问一下这种情况如何解决.

---
​X-tunnel 服务端今天下午4点出故障，导致无法登陆，下午6点多已修复，抱歉。
有用户反馈流量丢失，如果遇到这种情况，请给xxnet.dev@gmail.com发邮件。

**Comment by jon945** [comment]
我也是，今天突然就登录不了啦，3.11.14的版本

**Comment by jon945** [comment]
May 12 17:33:08.775 - [WARNING] front retry center.xx-net.net/login
May 12 17:33:10.203 - [WARNING] front retry center.xx-net.net/login
May 12 17:33:11.635 - [WARNING] front retry center.xx-net.net/login
May 12 17:33:13.653 - [WARNING] api:/login fail:status:602 t:34
May 12 17:33:13.653 - [WARNING] x-tunnel request_balance fail when create_conn:status:602
May 12 17:33:13.653 - [DEBUG] session not running, try login..
May 12 17:33:14.071 - [WARNING] front retry center.xx-net.net/login
May 12 17:33:15.507 - [WARNING] front retry center.xx-net.net/login
May 12 17:33:16.953 - [WARNING] front retry center.xx-net.net/login
May 12 17:33:18.371 - [WARNING] front retry center.xx-net.net/login

**Comment by SeaHOH** [comment]
先尝试删除 data/x-tunnel 里面的 *ip_list.txt 文件，然后重启 XX-Net。
如果还是不行，请先使用 gae_proxy。

**Comment by iTreeBear** [comment]
删除 data/x-tunnel 里面的 *ip_list.txt 文件，还是不行，同样的日志报错

**Comment by iTreeBear** [comment]
gae_proxy也不能用哦

**Comment by RudolphBrown** [comment]
gae_proxy 可以使用,但是youtube视频无法观看,走一小段就报错error,所以想改用x-tunnel.

即使数据清除,重启后发现还是正在登录,登录按钮显示“请稍后”,卡住了.

**Comment by xxnet** [comment]
​X-tunnel 服务端今天下午4点出故障，导致无法登陆，下午6点多已修复，抱歉。
有用户反馈流量丢失，如果遇到这种情况，请给xxnet.dev@gmail.com发邮件。

**Comment by liangliangge521** [comment]
今天已经恢复了
