### ISSUE TITLE
[发布] 3.11.14 修复并增加 teredo 隧道相关

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#10663]
请到 Releases 页面下载 3.11.14 测试版

修复了设置 teredo 服务器错误
增加了测试 teredo 可用性按钮

**Comment by Tim-Xue** [comment]
那个，我想问一下：我连学校的校园网的话，ipv6提示无法连接，但是连自己手机热点没有问题，这是什么原因？

**Comment by Tim-Xue** [comment]
在cmd命令下吗？

**Comment by SeaHOH** [comment]
可以保存为两个 bat 文件，然后管理员权限运行。
分别尝试，不要两个一起运行了。

**Comment by Tim-Xue** [comment]
那个只试了第一个，到目前为止都正常。。谢谢大佬。

**Comment by Tim-Xue** [comment]
那个海大，昨天用了你上面的方法ipv6正常了一天，刚刚又崩了，然后我切回手机热点，发现ipv6还是fail。这咋办？

**Comment by SeaHOH** [comment]
下载 Source code (zip)  即可

**Comment by imldf** [comment]
3.11.14版本 Google翻译无法使用，显示翻译出错
![001](https://user-images.githubusercontent.com/33856971/40154611-b7d423be-59c1-11e8-84da-a1dfac928fac.PNG)

**Comment by pendave** [comment]
![4p yl3 j xv88 du mgyf](https://user-images.githubusercontent.com/1331881/40154607-b07656c8-59c1-11e8-9263-7103f6cecacf.png)
不错啊 在界面里直接调试ipv6 和 teredo 了
restart the system 的意思是 然后退出xxnet重新运行？我做了 非常好 就正常了！

**Comment by SeaHOH** [comment]
@imldf 
已修复，但未发布新版，需要下载 master branches。

**Comment by yidasanqian** [comment]
@SeaHOH 状态提示"仅IPv6" 不可用，请检查。

诊断信息：
`XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.11.14
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true`

**Comment by SeaHOH** [comment]
尝试修复。。。

**Comment by yidasanqian** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant
