### ISSUE TITLE
问下大家移动宽带用xxnet上youtube速度如何？手动捂脸。。

### ISSUE THREAD

**Issue by anonymousvic** [XX-net/XX-Net#10660]
坐标华东沿海

以前看1080P@60fps都基本流畅，现在720P@30fps都卡死。。你们2M/s的下载速度是啥宽带？

我其实想下载之后再看，用IDM可以探测到，就是点了下载之后，IDM没速度（已挂127.0.0.1:8087），有也非常慢，几K到几十K。。

命令行的you-get和GUI-youget都试了，只能用 -i 命令获取标签，基本下不下来。。

移动宽带这么鸡肋的吗。。有没有优化的办法啊

**Comment by mustango** [comment]
之前试过把hosts改了https://github.com/lennylxx/ipv6-hosts 
打开一个视频后，然后把代理关了，YouTube速度瞬间上去了，直到看完这个视频为止
![snipaste_20180511_173755](https://user-images.githubusercontent.com/3320257/39918291-9935c152-5542-11e8-9b01-95d31224ff5d.png)
注意观察开关代理前后ip变化https://redirector.googlevideo.com/report_mapping

**Comment by JramerEG** [comment]
我也超级慢

**Comment by NuclearBlast** [comment]
时断时续，一断我就打卡issues，刚才断了一下想回这个贴，回头一看又连上了，差点忘了发帖=。=

**Comment by xiaoteai** [comment]
![jk61p zb4g f uhy j 8m 4](https://user-images.githubusercontent.com/10782704/39973158-dadad71a-574e-11e8-9487-9cbb3ff0b736.jpg)

**Comment by RudolphBrown** [comment]
之前版本还好，现在时断时续，应该是墙又升级了吧。
