### ISSUE TITLE
不能使用google翻译

### ISSUE THREAD

**Issue by xc1988** [XX-net/XX-Net#10661]
![image](https://user-images.githubusercontent.com/13324648/39921225-af1c9e0a-554c-11e8-934a-b71d2cfe4259.png)
公司跟家里都试了..

**Comment by SeaHOH** [comment]
请贴出对应的 gae_proxy 日志

**Comment by XuYuanchi** [comment]
同样无法使用谷歌翻译

**Comment by xc1988** [comment]
May 12 14:47:10.284 - [DEBUG] network IPv4 is ok, cost:689 ms

May 12 14:47:10.537 - [INFO] ------------------------------------------------------

May 12 14:47:10.537 - [INFO] Python Version : 2.7.13

May 12 14:47:10.537 - [INFO] OS : Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

May 12 14:47:10.537 - [INFO] Listen Address : 127.0.0.1:8087

May 12 14:47:10.537 - [INFO] GAE APPID : xc1988-xxnet|qyxugou|xc182341|xc80923|xcdp1988|xiaocaidun

May 12 14:47:10.537 - [INFO] ------------------------------------------------------

May 12 14:47:10.762 - [DEBUG] Importing CA

May 12 14:47:10.762 - [DEBUG] Removing windows CA

May 12 14:47:10.777 - [DEBUG] Begin to import Windows CA

May 12 14:47:10.777 - [INFO] SSL use version:TLSv1_2

May 12 14:47:10.777 - [INFO] OpenSSL support alpn

May 12 14:47:10.793 - [INFO] load ip range file:D:\Program Files (x86)\XX-Net\code\3.11.13\gae_proxy\local\ip_range.txt

May 12 14:47:10.793 - [INFO] load ip_list num:500, target num:500

May 12 14:47:10.809 - [INFO] SSL use version:TLSv1_2

May 12 14:47:10.809 - [INFO] server 127.0.0.1:8087 started.

May 12 14:47:11.523 - [DEBUG] create_ssl update ip:2607:f8b0:4005:1e::a time:713 h2:0 sni:whereas-reach.ml, host:

May 12 14:47:11.900 - [DEBUG] create_ssl update ip:2800:200:2008:10c5::10 time:1091 h2:0 sni:xc80923.appspot.com, host:xc80923.appspot.com

May 12 14:47:12.746 - [DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=259d6dcf-459c-4dc9-be94-cf5919e785f0&version=3.11.13&platform=Windows-10-10.0.17134

May 12 14:47:13.231 - [INFO] scan_ip add ip:2607:f8b0:4006:37::a time:307 h2:0

May 12 14:47:13.231 - [INFO] remove_slowest_ip:2001:16d8:4:7::d handshake_time:1085, fails:1

May 12 14:47:13.580 - [DEBUG] create_ssl update ip:2607:f8b0:401c:5::8 time:677 h2:0 sni:xcdp1988.appspot.com, host:xcdp1988.appspot.com

May 12 14:47:14.066 - [INFO] DIRECT t:1319 s:1674 200 xxnet-update.appspot.com /update.json?uuid=259d6dcf-459c-4dc9-be94-cf5919e785f0&version=3.11.13&platform=Windows-10-10.0.17134

May 12 14:47:14.107 - [DEBUG] GAEProxy web_control 127.0.0.1:49509 POST /config?cmd=get_config

May 12 14:47:14.109 - [DEBUG] GAEProxy Web_control 127.0.0.1:49509 GET /scan_ip?cmd=get_range

May 12 14:47:14.109 - [INFO] load ip range file:D:\Program Files (x86)\XX-Net\code\3.11.13\gae_proxy\local\ip_range.txt

May 12 14:47:14.135 - [DEBUG] create_ssl update ip:2607:f8b0:401c:6::8 time:678 h2:0 sni:xc80923.appspot.com, host:xc80923.appspot.com

May 12 14:47:14.415 - [DEBUG] GAE POST /tbproxy/af/query?client=Chromium from:127.0.0.1:49523

May 12 14:47:14.881 - [INFO] GAE t:466 s:28 POST https://clients1.google.com/tbproxy/af/query?client=Chromium 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:5::8,0:h1_req,1:h1_req_sended,287:response_begin,0:h1_get_head,0:h1_finish[SP:1141],0:get_response,:176

May 12 14:47:15.087 - [DEBUG] create_ssl update ip:2607:f8b0:4006:37::a time:816 h2:0 sni:intentionpollution.net, host:

May 12 14:47:15.256 - [DEBUG] create_ssl update ip:2607:f8b0:401c:2c::a time:674 h2:0 sni:xiaocaidun.appspot.com, host:xiaocaidun.appspot.com

May 12 14:47:15.773 - [DEBUG] create_ssl update ip:2607:f8b0:4007:2a::b time:2005 h2:0 sni:recipe-long.com, host:

May 12 14:47:15.842 - [INFO] scan_ip add ip:2804:a8:b800:600::f time:542 h2:0

May 12 14:47:15.842 - [INFO] remove_slowest_ip:2607:f8b0:4006:2f::a handshake_time:1085, fails:1

May 12 14:47:16.794 - [DEBUG] create_ssl update ip:2607:f8b0:401c:3::7 time:2020 h2:0 sni:committee-night.ml, host:

May 12 14:47:17.572 - [DEBUG] GAE POST /log?format=json&authuser=0 from:127.0.0.1:49469

May 12 14:47:17.729 - [DEBUG] GAE GET /translate_a/single?client=t&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&source=btn&ssel=0&tsel=0&kc=0&tk=660502.812024&q=test from:127.0.0.1:49528

May 12 14:47:17.862 - [INFO] GAE t:289 s:131 POST https://play.google.com/log?format=json&authuser=0 0:start_request,0:get_task(3),0:get_worker(0):2607:f8b0:401c:5::8,1:h1_req,0:h1_req_sended,286:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:2195],:0

May 12 14:47:18.958 - [INFO] GAE send ungziped deflate data to browser t:1228 s:2782 GET https://translate.google.com/translate_a/single?client=t&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&source=btn&ssel=0&tsel=0&kc=0&tk=660502.812024&q=test 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:2c::a,0:h1_req,0:h1_req_sended,394:response_begin,0:h1_get_head,0:get_response,831:h1_finish[SP:2707],:1

May 12 14:47:19.097 - [DEBUG] GAE POST /log?auth=SAPISIDHASH%20cd8aeafafbc499dd55134336d3b744f6d49f7056&authuser=0&format=json from:127.0.0.1:49469

May 12 14:47:19.109 - [DEBUG] GAE GET / from:127.0.0.1:49528

May 12 14:47:19.379 - [DEBUG] create_ssl update ip:2806:1040:cfff:5::c time:782 h2:0 sni:xiaocaidun.appspot.com, host:xiaocaidun.appspot.com

May 12 14:47:19.433 - [INFO] GAE t:335 s:131 POST https://play.google.com/log?auth=SAPISIDHASH%20cd8aeafafbc499dd55134336d3b744f6d49f7056&authuser=0&format=json 0:start_request,0:get_task(1),1:get_worker(0):2607:f8b0:401c:2c::a,0:h1_req,0:h1_req_sended,327:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1914],:2

May 12 14:47:19.534 - [DEBUG] GAE POST /log?auth=SAPISIDHASH%20cd8aeafafbc499dd55134336d3b744f6d49f7056&authuser=0&format=json from:127.0.0.1:49469

May 12 14:47:19.641 - [DEBUG] create_ssl update ip:2804:a8:b800:600::f time:1562 h2:0 sni:xc182341.appspot.com, host:xc182341.appspot.com

May 12 14:47:20.038 - [DEBUG] network IPv6 is ok, cost:10444 ms

May 12 14:47:20.172 - [DEBUG] create_ssl update ip:2607:f8b0:4009:3b::a time:1068 h2:0 sni:xc182341.appspot.com, host:xc182341.appspot.com

May 12 14:47:20.363 - [INFO] GAE t:1253 s:68788 GET https://translate.google.com/ 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:5::8,0:h1_req,1:h1_req_sended,332:response_begin,0:h1_get_head,0:get_response,918:h1_finish[SP:55344],:0

May 12 14:47:20.365 - [DEBUG] create_ssl update ip:2806:1040:cfff:5::e time:764 h2:0 sni:qyxugou.appspot.com, host:qyxugou.appspot.com

May 12 14:47:20.491 - [INFO] scan_ip add ip:2804:7f1:a000:cace::13 time:573 h2:0

May 12 14:47:20.492 - [INFO] remove_slowest_ip:2804:14d:baf9:9::c handshake_time:1082, fails:1

May 12 14:47:20.534 - [DEBUG] GAE GET /translate_a/single?client=t&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&source=bh&ssel=0&tsel=0&kc=1&tk=660502.812024&q=test from:127.0.0.1:49528

May 12 14:47:20.612 - [INFO] GAE t:1078 s:131 POST https://play.google.com/log?auth=SAPISIDHASH%20cd8aeafafbc499dd55134336d3b744f6d49f7056&authuser=0&format=json 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:6::8,770:h1_req,0:h1_req_sended,304:response_begin,0:h1_get_head,0:h1_finish[SP:2065],0:get_response,:0

May 12 14:47:20.666 - [DEBUG] GAE POST /u/0/_/og/botguard/get?rt=j&sourceid=51 from:127.0.0.1:49569

May 12 14:47:20.680 - [DEBUG] GAE POST /u/0/_/notifications/count from:127.0.0.1:49570

May 12 14:47:20.851 - [INFO] GAE send ungziped deflate data to browser t:315 s:2818 GET https://translate.google.com/translate_a/single?client=t&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&source=bh&ssel=0&tsel=0&kc=1&tk=660502.812024&q=test 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:2c::a,0:h1_req,1:h1_req_sended,299:response_begin,0:h1_get_head,0:get_response,13:h1_finish[SP:10647],:2

May 12 14:47:20.921 - [DEBUG] GAE GET /favicon.ico from:127.0.0.1:49528

May 12 14:47:21.014 - [INFO] scan_ip add ip:2607:f8b0:4002:37::8 time:381 h2:0

May 12 14:47:21.016 - [INFO] remove_slowest_ip:2404:6800:400c:3::8 handshake_time:1082, fails:1

May 12 14:47:21.099 - [DEBUG] GAE POST /log?format=json&authuser=0 from:127.0.0.1:49469

May 12 14:47:21.194 - [INFO] GAE t:528 s:4279 POST https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=51 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:5::8,0:h1_req,0:h1_req_sended,525:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:9013],:0

May 12 14:47:21.251 - [DEBUG] GAE POST /log?format=json&authuser=0 from:127.0.0.1:49574

May 12 14:47:21.482 - [INFO] GAE t:381 s:131 POST https://play.google.com/log?format=json&authuser=0 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4009:3b::a,0:h1_req,1:h1_req_sended,365:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1708],:15

May 12 14:47:21.489 - [DEBUG] GAE POST /log?format=json&authuser=0 from:127.0.0.1:49469

May 12 14:47:21.514 - [INFO] GAE t:833 s:50 POST https://ogs.google.com/u/0/_/notifications/count 0:start_request,0:get_task(0),0:get_worker(0):2806:1040:cfff:5::e,0:h1_req,0:h1_req_sended,831:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1037],:0

May 12 14:47:21.609 - [INFO] GAE t:687 s:5032 GET https://translate.google.com/favicon.ico 0:start_request,0:get_task(0),0:get_worker(0):2806:1040:cfff:5::c,0:h1_req,0:h1_req_sended,368:response_begin,0:h1_get_head,0:get_response,318:h1_finish[SP:7839],:0

May 12 14:47:21.820 - [INFO] GAE t:568 s:131 POST https://play.google.com/log?format=json&authuser=0 0:start_request,0:get_task(0),0:get_worker(0):2800:200:2008:10c5::10,0:h1_req,0:h1_req_sended,565:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1109],:3

May 12 14:47:21.871 - [DEBUG] create_ssl update ip:2001:4958:300:500::f time:816 h2:0 sni:xiaocaidun.appspot.com, host:xiaocaidun.appspot.com

May 12 14:47:21.900 - [DEBUG] GAE GET /translate_a/single?client=t&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&source=btn&ssel=0&tsel=0&kc=0&tk=660502.812024&q=test from:127.0.0.1:49528

May 12 14:47:22.115 - [INFO] GAE t:625 s:131 POST https://play.google.com/log?format=json&authuser=0 0:start_request,0:get_task(0),0:get_worker(0):2804:a8:b800:600::f,0:h1_req,0:h1_req_sended,622:response_begin,0:h1_get_head,0:h1_finish[SP:1004],0:get_response,:2

May 12 14:47:22.240 - [INFO] GAE send ungziped deflate data to browser t:339 s:2772 GET https://translate.google.com/translate_a/single?client=t&sl=en&tl=zh-CN&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&source=btn&ssel=0&tsel=0&kc=0&tk=660502.812024&q=test 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:2c::a,0:h1_req,0:h1_req_sended,320:response_begin,0:h1_get_head,0:get_response,16:h1_finish[SP:9810],:3

May 12 14:47:22.380 - [DEBUG] create_ssl update ip:2607:f798:1e:1000::12 time:839 h2:0 sni:qyxugou.appspot.com, host:qyxugou.appspot.com

May 12 14:47:22.464 - [DEBUG] create_ssl update ip:2804:7f1:a000:cace::13 time:1205 h2:0 sni:xiaocaidun.appspot.com, host:xiaocaidun.appspot.com

May 12 14:47:22.731 - [DEBUG] create_ssl update ip:2607:f8b0:4002:37::8 time:1556 h2:0 sni:xcdp1988.appspot.com, host:xcdp1988.appspot.com

May 12 14:47:22.780 - [DEBUG] GAE POST /chrome-sync/dev/command/?client=Chromium&client_id=CFaJTYde2EnbSVeS5xdGzQ%3D%3D from:127.0.0.1:49582

May 12 14:47:23.189 - [INFO] GAE t:408 s:2678 POST https://clients4.google.com/chrome-sync/dev/command/?client=Chromium&client_id=CFaJTYde2EnbSVeS5xdGzQ%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:5::8,1:h1_req,0:h1_req_sended,401:response_begin,0:h1_get_head,0:get_response,3:h1_finish[SP:7686],:0

May 12 14:47:23.193 - [DEBUG] GAE POST /chrome-sync/dev/command/?client=Chromium&client_id=CFaJTYde2EnbSVeS5xdGzQ%3D%3D from:127.0.0.1:49582

May 12 14:47:23.361 - [DEBUG] create_ssl update ip:2607:f8b0:4006:30::8 time:819 h2:0 sni:bag.upper.block.com, host:

May 12 14:47:23.479 - [DEBUG] GAE POST /log?format=json&authuser=0 from:127.0.0.1:49469

May 12 14:47:23.575 - [INFO] GAE t:381 s:587 POST https://clients4.google.com/chrome-sync/dev/command/?client=Chromium&client_id=CFaJTYde2EnbSVeS5xdGzQ%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:401c:2c::a,0:h1_req,0:h1_req_sended,378:response_begin,0:h1_get_head,0:get_response,1:h1_finish[SP:2689],:2

May 12 14:47:23.837 - [INFO] GAE t:357 s:131 POST https://play.google.com/log?format=json&authuser=0 0:start_request,0:get_task(0),0:get_worker(0):2806:1040:cfff:5::e,0:h1_req,1:h1_req_sended,348:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1786],:3

May 12 14:47:23.845 - [DEBUG] create_ssl update ip:2620:11a:a022::22 time:2478 h2:0 sni:xiaocaidun.appspot.com, host:xiaocaidun.appspot.com

**Comment by SeaHOH** [comment]
已定位，请等待修复。

**Comment by SeaHOH** [comment]
@xxnet 先这么处理了，后续是否采取直接解压的方法来测试？

**Comment by xxnet** [comment]
猜测确实有很多漏的情况，直接解压会最可靠，而且是Native实现，性能应该也问题不大才对。
还是直接解压测试吧，如果解压成功，就直接返回解压后的数据，浏览器不必再解压一次。

**Comment by SeaHOH** [comment]
python zlib 流式

**Comment by SeaHOH** [comment]
是否采取流式解压？
现在是解压后一次性写入浏览器，好处是有 `Content-Length`，流式则无法提供长度信息。

**Comment by timaxell** [comment]
我3.11.14也遇到了，以前版本无此现象。

**Comment by thurse** [comment]
292:request,:20071, processed:3, transfered:1871, sni:thurse12.appspot.com

May 14 10:25:43.066 - [WARNING] retry_task_cb: POST None/_gh/

May 14 10:25:43.066 - [WARNING] POST None/_gh/ response_fail:retry timeout:20

May 14 10:25:43.066 - [DEBUG] 2001:ee0:3203:1::c worker close:down fail

May 14 10:25:43.986 - [WARNING] 2001:b032:c100:2::13 h1_request:Exception('time out',) inactive_time:21 task.timeout:20

May 14 10:25:43.986 - [WARNING] 2001:b032:c100:2::13 trace: 0:connect, 3408:init, 1766:request, 822:Res, 0:head, 507:head end, 0:request,:21074, processed:1, transfered:12520, sni:thurse48.appspot.com

May 14 10:25:43.986 - [WARNING] retry_task_cb: POST None/_gh/

May 14 10:25:43.986 - [WARNING] POST None/_gh/ response_fail:retry timeout:21

May 14 10:25:43.986 - [DEBUG] 2001:b032:c100:2::13 worker close:down fail

May 14 10:25:46.283 - [DEBUG] create_ssl update ip:2800:3f0:4001:e::12 time:3554 h2:0 sni:thurse28.appspot.com, host:thurse28.appspot.com

May 14 10:25:46.529 - [DEBUG] recheck_ip:2405:200:1612:1716::c restore ok

May 14 10:25:46.530 - [DEBUG] 2405:200:1612:1716::c worker close:keep alive

May 14 10:25:46.713 - [DEBUG] report_connect_fail:2a00:1450:4015:d::14

May 14 10:25:46.713 - [DEBUG] connect 2a00:1450:4015:d::14 fail:error("conn fail, sni:thurse10.appspot.com, top:thurse10.appspot.com e:timeout('timed out',)",)

**Comment by xxnet** [comment]
之前有一次改版，采用等所有数据下载完后，一次性给浏览器发送数据，结果很多用户反馈体验差了。

​流式压缩确实能够提高浏览器响应速度，提高体验。

如果流式压缩能够及时的抛出异常，就尽量用流式解压缩，不知道好不好实现。

Content-Length 不是问题，只要符合标准，浏览器能处理好。

服务端代码也要改过来，服务端因为urlfetch是一次性获取，就不必流式压缩，容易处理，你改好了我先把公共appid给升级了

**Comment by SeaHOH** [comment]
修改后，服务端版本号是否增加？
其实服务端不改基本上也不会遇到类似特例。

**Comment by xxnet** [comment]
​服务端版本号增加吧，因为：
1. 毕竟是正式发布出去的版本，虽然没有宣传要升级服务端。
2. 服务端的升级频率极低，到目前为止才改动几次。
3. 修改版本号没有什么成本

**Comment by SeaHOH** [comment]
客户端看看有没有什么差错，没有实际试过。

**Comment by xxnet** [comment]
刚才测试发现deflate解压失败不会抛异常，临时根据返回加了一个判断解决了。
这个判断没有什么依据，需要继续测试。

**Comment by xxnet** [comment]
​已发新版 #10715，暂时需要手动下载，请帮忙测试、反馈：


https://github.com/XX-net/XX-Net/archive/3.11.15.zip

**Comment by liuliuquick** [comment]
把http改成https://translate.google.com
