### ISSUE TITLE
3.11.14 ipv6总是断掉IP数很少，怎么解？

### ISSUE THREAD

**Issue by zangyijun** [XX-net/XX-Net#10672]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
xxnet-version: 3.11.14
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:77
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 1325
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by shenzhenmouse21** [comment]
怎么获取3.11.14版？谢谢！

**Comment by SeaHOH** [comment]
@zangyijun 请确定是否网络本身的原因，如尝试先前的版本。

@shenzhenmouse21 releases 页面下载 zip 包。
