### ISSUE TITLE
这4种代理我应该选哪个呢

### ISSUE THREAD

**Issue by clipperL** [XX-net/XX-Net#10679]
这有4种代理方式，GAEProxy、X-Tunnel、智能路由、PAC智能，不知道怎么选。
大佬们，麻烦指导下，谢谢啦

**Comment by QuocTroy** [comment]
一般情况选GAEProxy，需要配合浏览器插件使用

**Comment by clipperL** [comment]
@QuocTroy 我切换到 GAEProxy，可以用，我用的 Chrome 浏览器，我没装插件。
我之前一直用 PAC 智能。

**Comment by QuocTroy** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3
wiki文档自己去看吧

**Comment by clipperL** [comment]
https://github.com/XX-net/XX-Net/wiki/%E6%89%98%E7%9B%98%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95
这份文档上没有写“X-Tunnel、智能路由”。

**Comment by xxnet** [comment]
上面的Wiki已更新，截图哪位帮忙更新下

**Comment by clipperL** [comment]
@xxnet 话说怎么更新 Wiki？用 git 吗？

**Comment by clipperL** [comment]
@xxnet 我把图片上传到简书上了，您决定要不要用。
![1.png](https://upload-images.jianshu.io/upload_images/782269-3b9f6caa057cde5d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by xxnet** [comment]
![image](https://user-images.githubusercontent.com/10395528/40096200-6aae0fec-5902-11e8-8284-4912989f4cd2.png)
已更新上去了，谢谢 @clipperL

**Comment by clipperL** [comment]
@xxnet 不客气。
