### ISSUE TITLE
前天开始IPv6经常失败，用新增的自助开启每次都需要重启系统

### ISSUE THREAD

**Issue by yueyangzl** [XX-net/XX-Net#10676]
济南校园网，不过本身不支持IPv6，每次开启一段时间后都会自动关闭，之前是手动运行脚本开启不需要重启系统（现在手动运行依然都不需要），但是用这个新增功能每次都会要求重启系统……

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.14
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:263
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:24 h2:0
scan-ip-thread-num: 60
ip-quality: 285
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by myjlpt** [comment]
ipv6隧道，+HOSTS大法最快稳狠

**Comment by yfor1008** [comment]
我的也是，需要重启系统才可以，我是电信的网

**Comment by SeaHOH** [comment]
只要点击运行“启用”就会提醒重启系统，这个操作不需要反复进行，一般切换服务器并等待一两分钟即可。

**Comment by yueyangzl** [comment]
@SeaHOH 但是不重启的话，用“启用”跟更换服务器开启不了IPv6啊

**Comment by SeaHOH** [comment]
什么情况，你每天都要重新启用？
一般来说，启用过后不需要**再次**进行启用操作。

**Comment by yueyangzl** [comment]
@SeaHOH 不至于每天，因为不是一直在用，但是用一段时间关闭下次再打开的时候IPv6就失效了，前几天尤甚。今天中午又试了，不重启还是无效，重启后到现在一直正常，重启软件试了也没有关闭，不知道能持续多久。

**Comment by yueyangzl** [comment]
@SeaHOH ……这个我知道。

**Comment by SeaHOH** [comment]
那我就不是很懂了，运行的命令除了设置服务器和最后没提示重启外（只是没提示，以后会加上）都一样，为什么会有需要重启才能分出的差别。

**Comment by lt201081** [comment]
我的也是这个情况

**Comment by yuzhounh** [comment]
我也是这个情况。开启后用着用着，不知道什么时候就又被关闭了。我是用下面这个链接中的命令行的方式来开启的。

IPv6 Win10 · XX-net/XX-Net Wiki https://github.com/XX-net/XX-Net/wiki/IPv6-Win10

**Comment by yuzhounh** [comment]
很有可能是下面这个问题。可以试试。上面的链接中也提到了这个问题。

最新：WIN10如果出现不定时ipv6通道Fail，XX-NET中断连接的处理办法（有效） · Issue #8709 · XX-net/XX-Net https://github.com/XX-net/XX-Net/issues/8709

**Comment by lt201081** [comment]
之前使用的时候就是禁用的

在 2018年5月18日 上午9:26，Jing Wang <notifications@github.com>写道：
