### ISSUE TITLE
出现如下错误：Welcome to the Go language's HTTP/2 demo & interop server.

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#1067]

**Comment by sham7god** [comment]
我的系统为win7 64位，每次打开xx-net的start.sh文件时，都是office word那二货打开，怎么破？童鞋们？

**Comment by xxnet** [comment]
用 start.vbs或 start.bat 启动

2015-09-19 11:27 GMT+08:00 sham7god <notifications@github.com>:

**Comment by fletchere** [comment]
@xxnet 我是linux，应该是用start.sh。
