### ISSUE TITLE
进程pythonw.exe一直占网速

### ISSUE THREAD

**Issue by aaronkaiyangg** [XX-net/XX-Net#10673]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  实用的最新版本，之前的版本也遇到过此类问题

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  
看过
* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  
看过
* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

查阅过
* 简单描述遇到的问题：

可以正常使用，就是打开不一会儿，大概三五分钟时间，进程pythonw.exe这个进程就一直占网速1m/s以上不开网页也是，重启xx过着终结进程就不占网速了，但是重启之后几分钟又恢复原样
* 做过哪些尝试：

重启电脑，重启ipv6，重启xx
* 请贴出对应模块的状态页

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:127
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:84 h2:0
scan-ip-thread-num: 200
ip-quality: 1226
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

* 请贴出相关的日志
日志好像没什么贴的。。。

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by xxnet** [comment]
​scan-ip-thread-num: 200
先降低扫描线程试试

**Comment by SeaHOH** [comment]
>Appids_Out_Of_Quota: true

结合描述，似乎有后台跑流量。

**Comment by xxnet** [comment]
​有可能
worker: h1:84
一般有大量请求时，链接数会增加。

看看GAE日志，都有什么请求

**Comment by SeaHOH** [comment]
关闭后仍可回复
