### ISSUE TITLE
请教这是出了什么问题，如何解呢

### ISSUE THREAD

**Issue by zfgswsh** [XX-net/XX-Net#10683]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.7.18
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:2596 ipv4:0 ipv6:1725
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 386
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
请更新到 3.11.14

**Comment by zfgswsh** [comment]
我曾经更新过新的版本，但是使用后它的IPV6的数量只500，我现用的有2000个，所以又用回到老版上。另外就是用电信手机移动热点也连接不上。

**Comment by SeaHOH** [comment]
老版本连热点能正常使用？
