### ISSUE TITLE
3.11.10中的“系统设置”-“版本”-“自动升级到”显示问题

### ISSUE THREAD

**Issue by msghost** [XX-net/XX-Net#10681]
* 简单描述遇到的问题：
在“自动升级到”下拉列表中，有“通知稳定版”、“通知测试版”选项，对应WIKI没有这两项。
不知道“通知稳定版”是不是就是wiki中的“长期稳定版”

* 请贴出对应模块的状态页
![default](https://user-images.githubusercontent.com/16555025/39974527-07df3f5a-575c-11e8-9088-68df4ea210e7.png)
![default](https://user-images.githubusercontent.com/16555025/39974558-32e21ede-575c-11e8-9183-9d983b1edb31.png)

**Comment by AnyWAT** [comment]
稳定/测试版：自动升级到。。。
通知稳定/测试版：只提示通知不自动升级
