### ISSUE TITLE
Win10 1803 上start.vbs无法开机自启

### ISSUE THREAD

**Issue by TsanChao** [XX-net/XX-Net#10689]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  是的

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  是的

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  是的  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
 是的

* 简单描述遇到的问题：
 start.vbs在win10 1803上无法开机自启

* 做过哪些尝试：
鼠标双击start.vbs系统无反应，也没有XX-Net进程启动。
鼠标右键start.vbs，管理员权限不可选。

* 请贴出对应模块的状态页
No status

* 请贴出相关的日志
No logs

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by SeaHOH** [comment]
1. 检查下载的 XX-Net 压缩包是否完整正确
1. 检查 vbs 文件关联是否正确
1. 请确认是否只在 1803 上无法启动
1. 用安全软件检查是否有病毒木马
