### ISSUE TITLE
cannot connect MacOS

### ISSUE THREAD

**Issue by Fawkes7** [XX-net/XX-Net#10699]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by Fawkes7** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-17.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
os-release: 17.4.0
os-detail: Release:10.13.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6
xxnet-version: 3.11.10
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3105 ipv4:6 ipv6:2842
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 265
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
