### ISSUE TITLE
建议：数据备份

### ISSUE THREAD

**Issue by xiaoas** [XX-net/XX-Net#10694]
因为每次关机/睡眠之后xx-net都会出问题 丢失很多扫到的ip 希望要是能隔一段时间把扫到的ip写到文件里再flush一下就好了

**Comment by xiaoas** [comment]
没有吧 我是说扫到一半结束进程的那种 你要不试试 如果有直接写入的话或许是我瞎bb了？或者是要flush一下

**Comment by xxnet** [comment]
有扫描到ip，就会标记需要保存文件。
每10秒检查一次是否需要保存文件，​并进行flush ：

https://github.com/XX-net/XX-Net/blob/9a0fd47dd640ab8ef0bf93590fa2d2981030447a/code/default/python27/1.0/lib/noarch/front_base/ip_manager.py#L215
