### ISSUE TITLE
求助:miredo服务经常崩,重启也时好时坏.

### ISSUE THREAD

**Issue by RudolphBrown** [XX-net/XX-Net#10690]
5月 15 09:27:44.69 - [INFO] load ip range file:/home/harry/Desktop/app/XX-Net-3.11.10/code/default/gae_proxy/local/ip_range.txt
5月 15 09:27:44.83 - [DEBUG] report_connect_fail IPv6 continue_fail_count:660
5月 15 09:27:44.83 - [DEBUG] report_connect_fail network fail
5月 15 09:27:44.83 - [DEBUG] connect 2607:f8b0:4009:34::8 network fail
5月 15 09:27:44.96 - [DEBUG] GAE POST /tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38376
5月 15 09:27:45.10 - [DEBUG] report_connect_fail IPv6 continue_fail_count:661
5月 15 09:27:45.10 - [DEBUG] report_connect_fail network fail
5月 15 09:27:45.10 - [DEBUG] connect 2607:f8b0:4008:27::7 network fail

ip_range.txt:
108.177.111.0-108.177.112.255
108.177.122.0-108.177.122.255
172.217.0.0-172.217.31.255
172.217.160.0-172.217.175.255
172.217.194.0-172.217.195.255
216.58.192.0-216.58.223.255

发现错误出现的上一步载入Ip_range,请问这个有优化的空间吗？感谢.

**Comment by SeaHOH** [comment]
ip_range.txt 是 IPv4，和你的情况无关，请参考 #10682 。
