### ISSUE TITLE
感谢，用了自己APPiD,可以看视频了，但是偶尔刷新会出现问题

### ISSUE THREAD

**Issue by barnettzane** [XX-net/XX-Net#107]
目前是使用局域网设置中的自动配置脚本。
http://127.0.0.1:8086/proxy.pac

但是有时打开页面会出现“ 请重新部署服务端: http://127.0.0.1:8085/?module=goagent&menu=deploy”

使用Proxy SwitchySharp 插件会不会好点。能不能指点下 switchysharp 具体如何设置呢？

**Comment by xxnet** [comment]
请使用最新版本，已经修复这个问题。

自动升级，待1.7.1 稳定了，就部署自动升级

在 2015年4月3日 上午7:55，barnettzane <notifications@github.com>写道：
