### ISSUE TITLE
我完全按照教程装的，用的火狐浏览器，但是装完打开google还是不行么

### ISSUE THREAD

**Issue by sailorcode** [XX-net/XX-Net#10703]
是不是ipv4后面的数字大于1才能用啊
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | Fail (尝试修复)
IPv4 IP数 | 0
IPv6 IP数 | 0
XX-Net 状态 | 工作
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 10

**Comment by SeaHOH** [comment]
如果是 Windows，点击“尝试修复”尝试开启 IPv6。

**Comment by sailorcode** [comment]
是的,开了ipv6就行了
