### ISSUE TITLE
请指条明路，谢谢!

### ISSUE THREAD

**Issue by shenzhenmouse21** [XX-net/XX-Net#10700]
经常显示：连接尚未建立。
而且无法用teredo.bat更改teredo服务器。
请各位指条解决的方向，谢谢！
> XX-Net Status:
> 
> sys-platform: AMD64, Windows-10-10.0.17134
> os-system: Windows
> os-version: 10.0.17134
> os-release: 10
> os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
> architecture: 32bit,WindowsPE
> browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36
> xxnet-version: 3.11.10
> python-version: 2.7.13
> openssl-version: 16.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: auto
> gws-ip-num: total:500 ipv4:0 ipv6:294
> ipv4-status: OK
> ipv6-status: Fail
> connected-link: new:0
> worker: h1:0 h2:0
> scan-ip-thread-num: 50
> ip-quality: 596
> is-idle: 0
> proxy_state: OK
> ca_state: OK
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false

**Comment by xxnet** [comment]
用​ 3.10.14版，进入：
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel
点启用。

**Comment by SeaHOH** [comment]
补充一点，如果修改过组策略，请恢复到未设置状态。

**Comment by shenzhenmouse21** [comment]
ok，升级到3.11.14版本后，有不错的改善，但依然会出现”连接尚未建立“的情况，尝试点击Ipv6的”尝试修复“按钮，点击”启用“后，提示reboot system。请问是重启操作系统么？有没有其它可用的办法？谢谢！

**Comment by shenzhenmouse21** [comment]
目前的情况是IPV6隧道已启用，但是xxnet依然“连接尚未建立”，然后点击“测试teredo可用性”，显示“teredo test result is unknown.”
请问上述情况有什么解决思路么？再谢！
`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.11.14
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:202
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by shenzhenmouse21** [comment]
收到，谢谢!

**Comment by SeaHOH** [comment]
对，遇到 IPv6  Fail 的时候先尝试更换服务器。

**Comment by shenzhenmouse21** [comment]
收到，再次非常感谢！

**Comment by SasamiMasakiJurai** [comment]
teredo的污染在加强 

这个无解 

而且现在teredo服务器太少
