### ISSUE TITLE
ubuntu 18.04怎么开机启动?

### ISSUE THREAD

**Issue by wsgdlhy** [XX-net/XX-Net#10706]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by xxnet** [comment]
​wiki里有大部分的问题解答：

https://github.com/XX-net/XX-Net/wiki/%E5%9C%A8Linux%E4%B8%8B%E5%A6%82%E4%BD%95%E5%B0%86XX-Net%E4%BD%9C%E4%B8%BA%E5%90%8E%E5%8F%B0%E6%9C%8D%E5%8A%A1%E5%90%AF%E5%8A%A8

**Comment by RudolphBrown** [comment]
我是在系统里搜索开机启动程序，也可以在文件里设置，随便百度一下就有。
