### ISSUE TITLE
今天XXNET出现了很多奇怪症状

### ISSUE THREAD

**Issue by LeoWang0812** [XX-net/XX-Net#1070]
1：IE浏览器即使没有设置代理服务器，打开网页的时候也会提示代理服务器没响应，除非在打开XXNET的情况下才能正常浏览网页。（XXNET开启的是取消全局代理模式）。
2：英雄联盟连接不上服务器，QQ群文件群公告等都打不开。
3：2.3.0,2.4.0两个版本都无法切换代理模式，点击无反应，只有2.0.5可以成功切换。

以上，请问哪位有类似症状或者有解决办法？

**Comment by LeoWang0812** [comment]
现在我即使没有开全局代理，IE还是可以访问被墙网站。。证明模式切换已经没用了。

**Comment by aOJzQT** [comment]
这里试了**2.4.0**的情况，`浏览器 IE 11` ，以下功能均无问题
* 全局GAEProxy
* 全局Pac
* 取消全局

**Comment by alresvor** [comment]
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections
把上面注册表里的键值全部删掉试试，放心删，系统会自动生成的。。。
