### ISSUE TITLE
依然未能解决的soundcloud上传问题

### ISSUE THREAD

**Issue by DipperTheCoder** [XX-net/XX-Net#10701]
之前发过这样一个反馈，#10450 ，最下面有人提出了解决方案，但是因为当时有事忘了过来处理，最后问题也关闭了。
之所以说依然未能解决，是因为这个太过奇葩的现象困扰了我很多年：为什么上传的瞬间会突破带宽限制，将一首十几兆的音乐在一两秒内上传完毕，360流量计里显示是突然速度极快，soundcloud里也是瞬间上传完毕。
但是！！！
实际上根本没有传好，会一直卡在这个状态，就没然后了。下面就会发现svchost.exe以30~200k/s的速度在上传不知道什么东西，并且不会停止，等很久曲子也不会有进展，极偶尔的瞬间还会出现每秒十几兆。
希望开发组能看下是怎么回事，说这么多，实际测试下应该就明白了，随便找个曲子上传试试，不用提交。
另外上次#10450 里有人提到解决办法是把网址加入规则，首先我试了下不管用，如果使用全局XX-NET代理是不是就与规则无关了呢？因为我就是加了规则后还不管用就全局了，如果是这样那可需要麻烦开发组看下到底是怎么回事了

-------
刚刚我试了下X-TUNNEL，居然也是这种情况，但不同的是可以上传成功，感觉很奇怪

**Comment by xxnet** [comment]
​这类问题可能是兼容性问题，最简单的解放方法是用X-tunnel

**Comment by DipperTheCoder** [comment]
@xxnet 传曲子还好，文件不大，但是往youtube传视频时，文件很大，进度来来回回没时候完，很不稳定，X-tunnel的流量莫名其妙就白跑掉很多

**Comment by xxnet** [comment]
​X-tunnel 流量要多预留几倍出来，因为GFW缘故，底层经常重传要消耗多流量。
要传Youtube最好购买套餐，流量很足的。

**Comment by SeaHOH** [comment]
关闭后仍可回复
