### ISSUE TITLE
google无法搜索，可以打开谷歌的网页，但是无法搜索，有下面提示，怎么办啊

### ISSUE THREAD

**Issue by panjinhua** [XX-net/XX-Net#10702]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

IP 地址：107.178.193.185
时间：2018-05-16T08:36:26Z
网址：https://www.google.com/search?source=hp&ei=gu37Wrr7DcbZjwT4yZiADg&q=%E4%BA%BA%E7%B1%BB&oq=%E4%BA%BA%E7%B1%BB&gs_l=psy-ab.3...2439.6009.0.6357.14.12.0.0.0.0.541.541.5-1.1.0....0...1c.1j4.64.psy-ab..13.1.541...0j0i131k1.0.-WIB7qR0myM

我用的手机无线网，大部分时间是正常的，但有时候就出现上面情况了，到底是怎么回事啊？

**Comment by SeaHOH** [comment]
建议登录谷歌帐号。
如果这种情况很少出现，请忽略并重新请求。

**Comment by panjinhua** [comment]
谷歌账号我是登陆了的。这种情况确实少出现，但是一旦出现了，意味着几个小时或者一天或者几天都是这样，重新请求也是没用的。
真是头疼啊。。。。。。

**Comment by xxnet** [comment]
​出现时清理历史记录看看

**Comment by xxnet** [comment]
可以在设置页面上加一个框，管理直连的域名。
遇到问题可以自己处理。

json格式的配置文件编辑确实容易出错。

**Comment by SeaHOH** [comment]
不过这样就成了要设置两次，gae 是一次，gae 直连或代理又是一次。
能不能把这个逻辑重组一下，放到同一层级来设置。

**Comment by xxnet** [comment]
​直连的列表保存放在原来的地方，只是提供一个Web控制的界面。

其他逻辑不必修改。

**Comment by xxnet** [comment]
> ​智能代理（或代理插件）把一个谷歌域名设置成 gae_proxy，
智能代理应该能自动解决，不需要手动设置。
代理插件，一般用PAC解决，也不需要设置。

>新界面再设置一次是走 GAE 还是直连
这只有在出问题时才需要去设置，一般默认就可以了。
之前有想过如何自动判断，自动切换到直连。
首先需要重现Google 识别到异常流量，看他返回什么，然后根据这个返回特征，自动切换到直连。

**Comment by SeaHOH** [comment]
好像是 404、ipv4 sorry

**Comment by xxnet** [comment]
​
把scholar.google.com从direct里去掉，就可以测试了。

返回是503,
内容包含下面的链接：
http://support.google.com/websearch/answer/86640

后续的处理策略：
把域名放入直连列表中，等用户自己刷新。
