### ISSUE TITLE
无法使用已购买的X-tunnel流量

### ISSUE THREAD

**Issue by wyzardwyz** [XX-net/XX-Net#10716]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.14
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:70 h2:0
scan-ip-thread-num: 10
ip-quality: 546
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

告诉我请检查浏览器设置

**Comment by xxnet** [comment]
​X-Tunnel 的状态页和日志贴来看

**Comment by slowvic** [comment]
借楼问下：为什么X-tunnel必须开着状态页，不然一会就自动登出了...

**Comment by xxnet** [comment]
​应该不会的，你可以把X-Tunnel的日志贴出来看

**Comment by slowvic** [comment]
May 19 09:12:08.851 - [DEBUG] roundtrip time:25320 cost:25033 transfer_no:1191 send:0 rcv:21

May 19 09:12:14.949 - [DEBUG] roundtrip time:25283 cost:25010 transfer_no:1193 send:27 rcv:21

May 19 13:49:25.646 - [DEBUG] x_tunnel force update info

May 19 13:49:25.981 - [INFO] session timeout, reset it.

May 19 13:49:25.981 - [INFO] start close all connection

May 19 13:49:25.981 - [DEBUG] stop all connection finished

May 19 13:49:25.981 - [INFO] WaitQueue stop

May 19 13:49:25.984 - [INFO] WaitQueue stop finished

May 19 13:49:25.985 - [DEBUG] session stopped.

May 19 13:49:26.419 - [INFO] login_session lutvvuwh time:434 msg:Success

May 19 13:49:27.048 - [INFO] session started.

May 19 13:49:27.062 - [INFO] socks5 ('127.0.0.1', 54645) connect to www.google-analytics.com:443 conn_id:1

May 19 13:49:27.145 - [INFO] api:/login success t:1497

May 19 13:49:27.145 - [INFO] request_balance host:v5.xx-net.net port:443 balance:0.000000 quota:1178951914877.000000

日志里面可以看到会话超时了

**Comment by xxnet** [comment]
​过段时间没有连接，会超时是正常的。

上面的日志是重连成功

**Comment by slowvic** [comment]
会话重连我知道。
我的意思是，因为闲置断开连接，过段时间恢复使用，此时会重新登录，这个登录操作不是应该在后台执行的么？为什么我过段时间点开X-Tunnel 配置，页面会显示正在登录？
这样很容易让人误解，以为断开后必须打开这个配置页面才能自动重登。

**Comment by xxnet** [comment]
​是会后台重新登陆的。
点开X-Tunnel配置页面也会触发重新登陆。

有时确实会无法连接，登陆配置页面可以确认是否能够登陆。
