### ISSUE TITLE
请问Twitter搜不到内容跟代理有关吗？

### ISSUE THREAD

**Issue by Illchange** [XX-net/XX-Net#10710]
从一年多前就开始搜不到内容，只能搜到用户然后进去才可以看推，试过开VPN或者无痕浏览都是这样，用户登录退出也一样，搜索设置也只有敏感或屏蔽内容无关系，请问是什么问题，与那个hosts文件有关吗？因为我steam有时经常错误118 改了一下好，请问Twitter要怎么改？
![twitter](https://user-images.githubusercontent.com/29409529/40177895-741e42fc-5a12-11e8-96ef-0878f8aecf0d.PNG)
还有tumblr一直都不能上去，只要尝试登陆或注册就会显示“登录出现了错误，请稍后再试。”这个我也不知道什么问题了

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Limitation

**Comment by Illchange** [comment]
上面的网站说较老的桌面浏览器，我的事chrome有按时更新应该不会有问题吧，然后user-agent，我在扩张程序装过一个切换器但是没变，还是说要更新user-agent？不太懂
我今天试了X-tunnel可以上但是只有200m

**Comment by SeaHOH** [comment]
>Twitter 无法搜索内容

关注点是这个吧，下面是可能的解决方案。

**Comment by ytbcn** [comment]
https://mobile.twitter.com/search?q=Tesla&src=typed_query&f=live

**Comment by Illchange** [comment]
哈哈这也可以，谢谢
我以为只有付费X-tunnel才可解决，没想到
