### ISSUE TITLE
用GAE时google虚拟云端硬盘客户端，上传不了文件，用X-Tunnel就没问题，这个有解吗？

### ISSUE THREAD

**Issue by iopxiang** [XX-net/XX-Net#10718]
如题
是Gsuit的云端硬盘客户端

* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by SeaHOH** [comment]
上传时的 gae_proxy 日志，方便的话贴出来。

**Comment by xxnet** [comment]
GAE天然缺乏兼容性，投入精力只能解决一个平台，经常还解决不了。
​上传的实现经常用到特殊的HTTP实现方式，以做好重传、交互等特性，一般推荐用X-Tunnel。

**Comment by SeaHOH** [comment]
可能和 之前提到的 channel binding 有关

**Comment by iopxiang** [comment]
google backup and sync上传就没问题

**Comment by SeaHOH** [comment]
有日志吗，这样才能分析问题。
不然就用 X-Tunnel。

**Comment by Eri5Ch** [comment]
GD windows桌面版很久很久之前就不能用了...

**Comment by iopxiang** [comment]
@Eri5Ch 这可不是gd桌面版，这是将gsuit的无限容量网盘挂载为本地盘符
