### ISSUE TITLE
点击立即更新情景模式时 出现网络错误

### ISSUE THREAD

**Issue by Lx91** [XX-net/XX-Net#10714]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by SeaHOH** [comment]
请确认代理设置正确

**Comment by emilyty** [comment]
出现了相同的问题。是按照步骤执行的。

**Comment by SeaHOH** [comment]
更新地址是否能访问？？
请确认代理设置正确，可以访问更新地址。

**Comment by SmartMapple** [comment]
同样遇到这个问题

**Comment by alexwongdl** [comment]
同样遇到这个问题，有人能解答吗
