### ISSUE TITLE
啥时候出￥支付

### ISSUE THREAD

**Issue by liule0228** [XX-net/XX-Net#10711]
啥时候上￥支付啊。。没有$啊

**Comment by Gongqiao24** [comment]
github 一直有JC在巡..你挂个支付宝 微信二维码  顺藤摸瓜就找到本人。。

**Comment by xxnet** [comment]
​注册paypal，会自动换美元的

**Comment by no-name2017** [comment]
我现在买正版AV都用paypal，再不注册paypal就过时了哈！
