### ISSUE TITLE
每次启动xxnet就开始get ip

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#1072]
每次启动时都要get ip，需要很长时间，而且完成之后也不能使用。关闭后重新打开又开始get ip。
版本是2.4，之前2.3也是这样，但是1.12没有问题。系统是win10 64位。不管是否部署appid都没有用
Sep 19 18:56:05 - [INFO] detect Win10, enable connect concurent control.
Sep 19 18:56:05 - [INFO] load ip range file:E:\����\����\XX-Net-2.3.0\data\gae_proxy\ip_range.txt
Sep 19 18:56:05 - [INFO] load google ip_list num:3000, gws num:3000
Sep 19 18:56:05 - [INFO] SSL use version:TLSv1
Sep 19 18:56:06 - [INFO] ------------------------------------------------------ GAEProxy Version : gae_proxy (python/2.7.9) Listen Address : 127.0.0.1:8087 GAE APPID : zzgldr|zzgldr1|zzgldr2 Pac Server : http://127.0.0.1:8086/proxy.pac ------------------------------------------------------
Sep 19 18:56:07 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Sep 19 18:56:08 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=8e79b13d-ce68-42cc-b417-f4568c60570c&version=2.3.0
Sep 19 18:56:08 - [DEBUG] get ip:210.61.221.168 t:180
Sep 19 18:56:08 - [DEBUG] get ip:222.255.120.5 t:358
Sep 19 18:56:08 - [DEBUG] get ip:208.117.236.172 t:521
Sep 19 18:56:08 - [DEBUG] get ip:85.182.250.173 t:534
Sep 19 18:56:08 - [DEBUG] get ip:64.15.116.148 t:541
Sep 19 18:56:08 - [DEBUG] get ip:128.0.169.250 t:554
Sep 19 18:56:08 - [DEBUG] get ip:128.0.169.205 t:558
Sep 19 18:56:08 - [DEBUG] get ip:128.0.169.243 t:567
Sep 19 18:56:08 - [DEBUG] get ip:128.0.169.239 t:573
Sep 19 18:56:08 - [DEBUG] get ip:128.0.169.233 t:588
Sep 19 18:56:09 - [INFO] GAE CONNECT www.googleapis.com:443
Sep 19 18:56:09 - [DEBUG] GAE CONNECT POST https://www.googleapis.com/oauth2/v4/token
Sep 19 18:56:09 - [DEBUG] get ip:128.0.169.230 t:605
Sep 19 18:56:09 - [DEBUG] get ip:128.0.169.204 t:611
Sep 19 18:56:09 - [DEBUG] get ip:208.117.224.157 t:708
Sep 19 18:56:09 - [DEBUG] get ip:210.153.73.84 t:846
Sep 19 18:56:09 - [DEBUG] get ip:84.235.77.251 t:918
Sep 19 18:56:09 - [DEBUG] get ip:216.58.213.59 t:918

**Comment by xxnet** [comment]
收到反馈，现在2.1.2 还能用吗？

2015-09-19 19:03 GMT+08:00 zzgpku <notifications@github.com>:

**Comment by zzgpku** [comment]
没有用过2.1.2，用的2.3、2.4都不行，重新下载2.4还是不行，先挂goagent再开xxnet就没有get ip，关掉goagent后就又不行了，难道是网的原因。。。

**Comment by zzgpku** [comment]
前来反馈，将ipv6=0改为1之后就能用了，估计ipv4的地址无法获取到
