### ISSUE TITLE
问题反馈: qq.com等系列网站直接连接解析不通

### ISSUE THREAD

**Issue by mtgitnerd** [XX-net/XX-Net#10725]
目前受影响网站：
qq.com
wx.qq.com
v.qq.com
表现形式：图片加载不出，视频放不了

**Comment by SeaHOH** [comment]
日志

**Comment by mtgitnerd** [comment]
直接连接，没有日志，就只有现象，图片不断的转圈，加载不出，视频不播放T_T

**Comment by SeaHOH** [comment]
怎么直连的，不是智能代理？

**Comment by mtgitnerd** [comment]
是的，直接连接选项，求助，目前主要是影响微信网页版，及腾讯视频

**Comment by mtgitnerd** [comment]
就是添加条件：直接连接

**Comment by SeaHOH** [comment]
智能代理的日志

**Comment by mtgitnerd** [comment]
没有启用只能路由

**Comment by SeaHOH** [comment]
？？你回答“是的”让我怎么理解。。。
浏览器插件添加的？跟 XX-Net 有什么关系？

**Comment by mtgitnerd** [comment]
switchomega

**Comment by SeaHOH** [comment]
是 SwitchyOmega，所以说跟 XX-Net 有关么？
你检查下系统 DNS 设置吧。
