### ISSUE TITLE
最近连接不上

### ISSUE THREAD

**Issue by wkc1203** [XX-net/XX-Net#10724]
May 19 12:48:07.938 - [DEBUG] report_connect_fail:2404:6800:400b:2c::7

May 19 12:48:07.979 - [DEBUG] connect 2404:6800:400e:8::b fail:timeout('timed out',)

May 19 12:48:07.979 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

May 19 12:48:07.980 - [DEBUG] report_connect_fail:2404:6800:400e:8::b

May 19 12:48:08.365 - [DEBUG] GAE_Exception 600 'fetch gae fail'

May 19 12:48:08.365 - [WARNING] gae_exception:'600:fetch gae fail' http://google.com/

May 19 12:48:08.365 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' http://google.com/"

May 19 12:48:08.365 - [WARNING] GAE GET http://google.com/ request fail:"600:gae_exception:'600:fetch gae fail' http://google.com/"

May 19 12:48:09.943 - [DEBUG] network IPv6 is ok, cost:1963 ms

May 19 12:48:10.944 - [DEBUG] connect 2a00:1450:400a:7::16 fail:timeout('timed out',)

May 19 12:49:31.780 - [WARNING] h1 head send len:0 51 2a00:1450:400a:7::c

May 19 12:49:31.780 - [DEBUG] http://google.com/ response_fail:retry timeout:462

May 19 12:49:31.780 - [DEBUG] report_connect_fail:2a00:1450:400a:7::c

May 19 12:49:31.811 - [DEBUG] connect 2607:f8b0:4012:f::a fail:timeout('timed out',)

May 19 12:49:31.811 - [DEBUG] report_connect_fail:2607:f8b0:4012:f::a

May 19 12:49:32.392 - [DEBUG] create_ssl update ip:2800:3f0:4001:4::a time:4109 h2:0

May 19 12:49:33.314 - [DEBUG] connect 2607:f8b0:4002:15::8 fail:timeout('timed out',)

May 19 12:49:33.314 - [DEBUG] report_connect_fail:2607:f8b0:4002:15::8

May 19 12:49:33.817 - [DEBUG] connect 2a00:1450:4001:45::7 fail:timeout('timed out',)

May 19 12:49:33.817 - [DEBUG] report_connect_fail:2a00:1450:4001:45::7

May 19 12:49:34.392 - [DEBUG] create_ssl update ip:2a00:1450:4003:10::e time:723 h2:0

May 19 12:49:35.461 - [DEBUG] 2607:f8b0:401a:1::7 worker close:idle timeout

May 19 12:49:36.387 - [DEBUG] connect 2607:f8b0:4008:26::8 fail:timeout('timed out',)

May 19 12:49:36.387 - [DEBUG] report_connect_fail:2607:f8b0:4008:26::8

May 19 12:49:36.427 - [DEBUG] connect 2607:f8b0:4012:a::8 fail:timeout('timed out',)

May 19 12:49:36.427 - [DEBUG] report_connect_fail:2607:f8b0:4012:a::8

May 19 12:49:36.509 - [WARNING] h1 head send len:0 51 2800:3f0:4001:4::a

May 19 12:50:31.629 - [WARNING] h1 head send len:0 51 2a00:1450:4003:6::a

May 19 12:50:31.629 - [DEBUG] report_connect_fail:2a00:1450:4003:6::a

May 19 12:50:31.725 - [DEBUG] connect 2a00:1450:400a:1::16 fail:timeout('timed out',)

May 19 12:50:31.725 - [DEBUG] report_connect_fail:2a00:1450:400a:1::16

May 19 12:50:31.768 - [DEBUG] connect 2607:f8b0:400a:e::7 fail:timeout('timed out',)

May 19 12:50:31.768 - [DEBUG] report_connect_fail:2607:f8b0:400a:e::7

May 19 12:50:31.834 - [DEBUG] connect 2607:f8b0:4000:39::a fail:timeout('timed out',)

May 19 12:50:31.834 - [DEBUG] report_connect_fail:2607:f8b0:4000:39::a

May 19 12:50:32.631 - [WARNING] h1 head send len:0 53 2a00:1450:4020:19::b

May 19 12:50:32.631 - [DEBUG] report_connect_fail:2a00:1450:4020:19::b

May 19 12:50:33.375 - [DEBUG] connect 2607:f8b0:4012:e::11 fail:timeout('timed out',)

May 19 12:50:33.375 - [DEBUG] report_connect_fail:2607:f8b0:4012:e::11

May 19 12:50:33.457 - [DEBUG] connect 2404:6800:400c:1::c fail:timeout('timed out',)

May 19 12:50:33.457 - [DEBUG] report_connect_fail:2404:6800:400c:1::c

May 19 12:50:33.499 - [DEBUG] connect 2a00:1450:4011:1c::13 fail:timeout('timed out',)

May 19 12:50:33.499 - [DEBUG] report_connect_fail:2a00:1450:4011:1c::13

May 19 12:50:33.787 - [DEBUG] connect 2607:f8b0:4002:2e::7 fail:timeout('timed out',)

May 19 12:50:33.787 - [DEBUG] report_connect_fail:2607:f8b0:4002:2e::7

May 19 12:50:33.905 - [WARNING] h1 head send len:0 64 2404:6800:400c:9::a

May 19 12:50:33.905 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

May 19 12:50:33.905 - [DEBUG] report_connect_fail:2404:6800:400c:9::a

May 19 12:50:34.755 - [DEBUG] connect 2a00:1450:4002:10::a fail:timeout('timed out',)

May 19 12:50:34.755 - [DEBUG] report_connect_fail IPv6 continue_fail_count:12

May 19 12:50:34.755 - [DEBUG] report_connect_fail:2a00:1450:4002:10::a

May 19 12:50:34.906 - [WARNING] h1 head send len:0 54 2404:6800:400c:a::b

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

**Comment by justbboychou** [comment]
和你一样..一直显示连接IPV6 fail ..而且首页IPv6 IP数一直显示1000多.. 经过排查.. 
首页IPv6 IP显示数是假的..
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描  后重新扫出来的IP就可以用了..
