### ISSUE TITLE
vmware虚拟机中ubuntu如何使用主机XX-Net翻墙？

### ISSUE THREAD

**Issue by TsanChao** [XX-net/XX-Net#10728]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
是  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
主机是windows10，现已实现xx-net翻墙。
虚拟机的ubuntu使用vmware的NAT方式，但是虚拟机无法翻墙。
如何让虚拟机的ubuntu使用主机的网络翻墙，而不单独再配置一次？

**Comment by SeaHOH** [comment]
只是个网络设置，去 vmware 社区询问更方便。
