### ISSUE TITLE
送X-Tunnel流量，已送完

### ISSUE THREAD

**Issue by beast1776** [XX-net/XX-Net#10726]
已送完

**Comment by waeart** [comment]
感谢赠送，谢谢。
ucv87464@sawoe.com

**Comment by beast1776** [comment]
ucv87464@sawoe.com
已送

**Comment by IkariKhara** [comment]
gwcd56946qq.com
万分感谢！ごちそうさまございます！

**Comment by waeart** [comment]
他丢了个@在前面qq.com吧。
谢谢，赠送的流量已收到。

**Comment by for1uck** [comment]
lg12a1@hainan.net
Thanks!

**Comment by beast1776** [comment]
gwcd56946qq.com 已送10G
@waeart 你说的对，我看漏了

**Comment by beast1776** [comment]
lg12a1@hainan.net 已送10G

**Comment by aixiu** [comment]
4815563@gmail.com
。。。

**Comment by beast1776** [comment]
4815563@gmail.com 已送10G

**Comment by SaDanic** [comment]
fanzbiao@gmail.com
谢谢了

**Comment by IkariKhara** [comment]
不好意思失误了，已收到，谢谢! @beast1776

**Comment by tommyclerk** [comment]
371488193@qq.com
非常感谢~

**Comment by beast1776** [comment]
fanzbiao@gmail.com 已送10G
371488193@qq.com 已送10G

**Comment by zmhby** [comment]
zmhsmcc@gmail.com
谢谢楼主分享，谢谢！

**Comment by beast1776** [comment]
2752913003@qq.com 已送10G

**Comment by beast1776** [comment]
2752913003@qq.com 已送10G

**Comment by zmhby** [comment]
再次表示感谢！

**Comment by DawsonLi** [comment]
xiaokulou06@gmail.com
非常感谢！

**Comment by tokitsumakaze** [comment]
sawamura_spencer_eriri@yahoo.co.jp

**Comment by clsteam** [comment]
bioaurora@webmail.hzau.edu.cn
谢谢楼主！！！
Thank you.

**Comment by csherry1231** [comment]
csherry1231@gmail.com
Thank you very much!

**Comment by zuyoushen** [comment]
wangwang1001@gmail.com
谢谢

**Comment by dadi101** [comment]
lidadivip@gmail.com
多谢了

**Comment by lushilei** [comment]
lushieli1993@gmail.com xieixedalao

**Comment by beast1776** [comment]
xiaokulou06@gmail.com
sawamura_spencer_eriri@yahoo.co.jp
bioaurora@webmail.hzau.edu.cn
csherry1231@gmail.com
wangwang1001@gmail.com
lidadivip@gmail.com
cx960306@gmail.com
en-oxy@outlook.com
已各送10G

**Comment by beast1776** [comment]
@lushilei 你没注册吧，lushieli1993@gmail.com无效

**Comment by clsteam** [comment]
已收到，谢谢！！

**Comment by XuYuanchi** [comment]
suyanchi@qq.com
感谢！

**Comment by lushilei** [comment]
失误，lushilei1993@gmai.com
谢谢大佬

**Comment by csherry1231** [comment]
已收到，感谢大佬！

**Comment by beast1776** [comment]
suyanchi@qq.com
lushilei1993@gmail.com
已各送10G

**Comment by xiaocaoqwe** [comment]
已收到，感谢

**Comment by DawsonLi** [comment]
收到，再次感谢！

**Comment by m9080212** [comment]
m9080212@gmail 
谢谢 :D

**Comment by skydream9900** [comment]
skydream8866@gmail.com

thanks a lot!

**Comment by Hackxy** [comment]
不知道还有送的没  ID：  hackxy@gmail.com
不管如何，先谢谢了

**Comment by QuocTroy** [comment]
897256315@outlook.com
感谢大佬😁

**Comment by bj301cn** [comment]
bj.301cn@gmail.com
谢谢！

**Comment by tokitsumakaze** [comment]
感激不尽！

**Comment by skydream9900** [comment]
请大家不要给的dingsr1985@163.com发邮件送流量，我不是作者本人，我也是要流量的，谢谢！

**Comment by beast1776** [comment]
m9080212@gmail.com
hack.xy@gmail.com
897256315@outlook.com
已各送10G，其它有两个ID最近几个小时注册的，为公平起见，就不送了
还能送两个：）

**Comment by AlexanderShang** [comment]
谢谢楼主
alexshang843537710@163.com

**Comment by dearmaximus** [comment]
6570855@qq.com
谢谢分享

**Comment by guoguo5211314** [comment]
hhwyl1983@gmail.com  谢谢楼主

**Comment by lshilshi** [comment]
ep.ye@qq.com
看看楼主还有有剩余没有
谢谢分享！

**Comment by SingleHe** [comment]
LargerStudent@Gmail.com   好人一生平安~

**Comment by beast1776** [comment]
alexshang843537710@163.com
935352@qq.com
已各送10G，已送完：D

**Comment by huangkio** [comment]
谢 huangkaiu@gmail.com
