### ISSUE TITLE
不用翻墙可以访问BBC，CNN了

### ISSUE THREAD

**Issue by no-name2017** [XX-net/XX-Net#10731]
![rtyrturturturturtutyutyi](https://user-images.githubusercontent.com/30927426/40270256-2b29f590-5bbc-11e8-899c-d7200f9373f5.jpg)

消息来自twitter，试了一下确实没问题，google貌似还不行。

**Comment by MadMaxPayne8964** [comment]
大惊小怪，英文版的BBC和CNN一直可以直连

**Comment by no-name2017** [comment]
看来是有人搞乌龙了

**Comment by caofengzi** [comment]
訪問中文版試試。bbc.com/zhongwen/

**Comment by dahai058** [comment]
放开油管推特才是硬道理

**Comment by no-name2017** [comment]
放开是不可能的，再过50年都不可能
