### ISSUE TITLE
xx-net局域网代理设置不保存，是哪里的问题呢？（如图）

### ISSUE THREAD

**Issue by Clairestar** [XX-net/XX-Net#10732]
![tim 20180520092005](https://user-images.githubusercontent.com/39448505/40274693-d5f4d73a-5c0f-11e8-998c-ffd20e0c8ef8.jpg)
![tim 20180520092037](https://user-images.githubusercontent.com/39448505/40274694-d659bd9e-5c0f-11e8-8670-adfb36bc6e9b.jpg)

* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

@woosley

**Comment by SeaHOH** [comment]
测试失败，你确定IP、类型和端口都填对了？

**Comment by Clairestar** [comment]
端口改为8086保存成功，但IP迅间就掉完了，不知是什么原因 @SeaHOH

**Comment by SeaHOH** [comment]
你知道你在干嘛？这是前置代理设置，你需要吗？

**Comment by Clairestar** [comment]
当然，开通后局域网都能通过此代理了，今天手机vpn设置此代理成功了，但关闭后就再也连不上了，不知问题出在哪

**Comment by SeaHOH** [comment]
那你设置成 8086？？这是 XX-Net 智能代理的默认端口。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/允许其它设备使用代理
还有不懂看这个，关闭后仍可回复。
