### ISSUE TITLE
所有版本都无法启动

### ISSUE THREAD

**Issue by 5513541651321** [XX-net/XX-Net#10736]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  是

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
无法启动，所有版本都无法启动！

连状态页面都无法显示！

**Comment by xiaoas** [comment]
额 或许你可以试试.bat 看看有没有log

**Comment by 5513541651321** [comment]
start.vbs 
start.bat
所有版本的这两个文件我都是过，没用！
我也是正常使用3.11.14的时候，升级3.11.15，升完之后都正常，可关掉之后，过会再用的时候就这样了，教程上的所有方法都试过了，都没用，我怀疑是不是我的系统文件出问题了。

**Comment by 5513541651321** [comment]
晕死，无缘无故自己又好了！！！
