### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by 13451368543** [XX-net/XX-Net#10730]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

xx-net下载到5兆多时就自动重新下载

**Comment by SeaHOH** [comment]
默认源码下载不支持续传，是否上传一个？ @xxnet

**Comment by xxnet** [comment]
​不明白，能否详细解析

**Comment by SeaHOH** [comment]
上传的附件可以使用续传

**Comment by SeaHOH** [comment]
>xx-net下载到5兆多时就自动重新下载

这句有歧义，我是理解成下载 XX-Net 源码。
