### ISSUE TITLE
版本3.11.15，win7 64bit使用正常，但每次开机弹窗，不知道怎么关掉弹窗

### ISSUE THREAD

**Issue by Dexilc** [XX-net/XX-Net#10742]
![default](https://user-images.githubusercontent.com/24988478/40307434-26701f28-5d35-11e8-9de4-72d0049ffe49.PNG)
记事本打开后内容如下：（MAC地址已删除）
D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config RpcEptMapper start= auto 
[SC] OpenService 失败 5:

拒绝访问。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start RpcEptMapper 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config DcomLaunch start= auto 
[SC] OpenService 失败 5:

拒绝访问。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start DcomLaunch 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config RpcSs start= auto 
[SC] OpenService 失败 5:

拒绝访问。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start RpcSs 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config nsi start= auto 
[SC] ChangeServiceConfig 成功

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start nsi 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config Winmgmt start= auto 
[SC] ChangeServiceConfig 成功

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start Winmgmt 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config Dhcp start= auto 
[SC] ChangeServiceConfig 成功

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start Dhcp 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config WinHttpAutoProxySvc start= auto 
[SC] ChangeServiceConfig 成功

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start WinHttpAutoProxySvc 

SERVICE_NAME: WinHttpAutoProxySvc 
        TYPE               : 20  WIN32_SHARE_PROCESS  
        STATE              : 2  START_PENDING 
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 1196
        FLAGS              : 

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc config iphlpsvc start= auto 
[SC] ChangeServiceConfig 成功

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>sc start iphlpsvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>goto :eof 

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 reset 
正在重置 接口，完成!
正在重置 前缀策略，完成!
正在重置 路由，完成!
重新启动计算机来完成此操作。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>ipconfig /flushdns 

Windows IP 配置

已成功刷新 DNS 解析缓存。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>goto :eof 

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface teredo set state type=enterpriseclient servername=teredo.remlab.net. 
确定。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy 2001::/16 35 1 
确定。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy 2002::/16 30 2 
确定。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy 2001::/32 25 2 
确定。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>Reg add HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f 
操作成功完成。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>Reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters /v DisabledComponents /t REG_DWORD /d 0 /f 
操作成功完成。

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>goto :eof 

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>ipconfig /all 

Windows IP 配置

   主机名  . . . . . . . . . . . . . : TP-20161114
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

无线局域网适配器 无线网络连接:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Intel(R) WiFi 链接 5100 AGN
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.101(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年5月19日 9:19:34
   租约过期的时间  . . . . . . . . . : 2018年5月19日 17:19:34
   默认网关. . . . . . . . . . . . . : 192.168.1.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
   DNS 服务器  . . . . . . . . . . . : 114.114.114.114
                                       1.1.1.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 本地连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Intel(R) 82567LM Gigabit Network Connection
   物理地址. . . . . . . . . . . . . :xxxxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

移动宽带适配器 移动宽带连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Qualcomm HS-USB Mobile Broadband Device 9202
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 Bluetooth 网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Bluetooth 设备(个人区域网)
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::473:29b:5c82:b9a0%18(首选) 
   默认网关. . . . . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 184549376
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-20-6E-B5-61-00-26-C6-4F-0C-12
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

隧道适配器 isatap.{F9402A4E-C50C-44A8-949F-CE02B27D686D}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 isatap.{7848AB23-5F08-4465-A15A-C2473F73BDBE}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter #2
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 isatap.{93E8553A-2A89-48E1-8062-E37B5DE9D559}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter #3
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 isatap.{E08D38CE-5302-4A17-B401-C08E542060B3}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter #4
   物理地址. . . . . . . . . . . . . : xxxxxxxxxxxxxxxxxxxxxxxxxx
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 show teredo 
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 show route 

发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        手动        256  ::/0                       18  Teredo Tunneling Pseudo-Interface
否        手动        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        手动        256  fe80::/64                  15  本地连接
否        手动        256  fe80::/64                  12  Bluetooth 网络连接
否        手动        256  fe80::/64                  18  Teredo Tunneling Pseudo-Interface
否        手动        256  fe80::5efe:192.168.1.101/128   20  isatap.{7848AB23-5F08-4465-A15A-C2473F73BDBE}
否        手动        256  fe80::473:29b:5c82:b9a0/128   18  Teredo Tunneling Pseudo-Interface
否        手动        256  fe80::1cb3:aba9:2903:1ee4/128   12  Bluetooth 网络连接
否        手动        256  fe80::f54b:1a46:754b:d8a7/128   15  本地连接
否        手动        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        手动        256  ff00::/8                   18  Teredo Tunneling Pseudo-Interface
否        手动        256  ff00::/8                   15  本地连接
否        手动        256  ff00::/8                   12  Bluetooth 网络连接

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 show interface 

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 18          50        1280  connected     Teredo Tunneling Pseudo-Interface
 23          50        1280  disconnected  isatap.{F9402A4E-C50C-44A8-949F-CE02B27D686D}
 15           5        1500  disconnected  本地连接
 20          50        1280  disconnected  isatap.{7848AB23-5F08-4465-A15A-C2473F73BDBE}
 21          50        1280  disconnected  isatap.{93E8553A-2A89-48E1-8062-E37B5DE9D559}
 22          50        1280  disconnected  isatap.{E08D38CE-5302-4A17-B401-C08E542060B3}
 12          50        1500  disconnected  Bluetooth 网络连接

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 show prefixpolicies 
查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        35      1  2001::/16
        30      2  2002::/16
        25      2  2001::/32

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>netsh interface ipv6 show address 

接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 18: Teredo Tunneling Pseudo-Interface

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite fe80::473:29b:5c82:b9a0%18

接口 15: 本地连接

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::f54b:1a46:754b:d8a7%15

接口 20: isatap.{7848AB23-5F08-4465-A15A-C2473F73BDBE}

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::5efe:192.168.1.101%20

接口 12: Bluetooth 网络连接

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::1cb3:aba9:2903:1ee4%12

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>route print 
===========================================================================
接口列表
 19...00 26 c6 4f 0c 12 ......Intel(R) WiFi 链接 5100 AGN
 15...00 22 68 20 84 0f ......Intel(R) 82567LM Gigabit Network Connection
 14...00 a0 c6 00 00 00 ......Qualcomm HS-USB Mobile Broadband Device 9202
 12...0c 60 76 8b 10 5f ......Bluetooth 设备(个人区域网)
  1...........................Software Loopback Interface 1
 18...00 00 00 00 00 00 00 e0 Teredo Tunneling Pseudo-Interface
 23...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 20...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #2
 21...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #3
 22...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #4
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.1.1    192.168.1.101     25
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    306
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    306
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    306
      192.168.1.0    255.255.255.0            在链路上     192.168.1.101    281
    192.168.1.101  255.255.255.255            在链路上     192.168.1.101    281
    192.168.1.255  255.255.255.255            在链路上     192.168.1.101    281
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    306
        224.0.0.0        240.0.0.0            在链路上     192.168.1.101    281
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    306
  255.255.255.255  255.255.255.255            在链路上     192.168.1.101    281
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 如果跃点数网络目标      网关
 18    306 ::/0                     在链路上
  1    306 ::1/128                  在链路上
 18    306 fe80::/64                在链路上
 18    306 fe80::473:29b:5c82:b9a0/128
                                    在链路上
  1    306 ff00::/8                 在链路上
 18    306 ff00::/8                 在链路上
===========================================================================
永久路由:
  无

D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local>goto :eof

**Comment by SeaHOH** [comment]
不知道你怎么搞的，建议删除后重新下载。

**Comment by SeaHOH** [comment]
关闭后仍可回复
