### ISSUE TITLE
MacOS 后台启动 Start

### ISSUE THREAD

**Issue by yxr877431436** [XX-net/XX-Net#10743]
MacOS运行 Start 之后自动打开终端，终端关闭时进程自动结束，如何在 MacOS 上后台运行 Start  ，而不打开终端。

**Comment by rmouse** [comment]
最新版已修复

**Comment by jack89757** [comment]
@rmouse 最新的就是3.11.15啊，就这个版本出的问题啊，终端没法后台

**Comment by windend** [comment]
Mac 最新版运行start后，terminal一直运行，确实没有启动后台运行，启动栏也没有启动

**Comment by valasco** [comment]
早先的版本运行.sh文件可以，现在必须点start文件，而且不能关闭~在设置里面设置了开机自启也没用~或许是我等小白不会，最好是出个教程出来啊~

**Comment by SeaHOH** [comment]
MacOS 是不是升级了？
