### ISSUE TITLE
IPv6 隧道 已启用，状态页显示 IPv6 状态 Fail

### ISSUE THREAD

**Issue by Antecer** [XX-net/XX-Net#10749]
在 “IPv6 隧道” 选项卡点击启用，输出如下信息，一大堆 拒绝访问，有没有办法解决？

`
C:\WINDOWS\system32>sc config RpcEptMapper start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start RpcEptMapper 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config DcomLaunch start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start DcomLaunch 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config RpcSs start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start RpcSs 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config nsi start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start nsi 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config Winmgmt start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start Winmgmt 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config Dhcp start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start Dhcp 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config WinHttpAutoProxySvc start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start WinHttpAutoProxySvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config iphlpsvc start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start iphlpsvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>goto :eof 

C:\WINDOWS\system32>netsh interface ipv6 reset 
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

C:\WINDOWS\system32>ipconfig /flushdns 

Windows IP 配置

已成功刷新 DNS 解析缓存。

C:\WINDOWS\system32>goto :eof 

C:\WINDOWS\system32>netsh interface teredo set state type=enterpriseclient servername=teredo.remlab.net. 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy 2001::/16 35 1 
确定。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy 2002::/16 30 2 
确定。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy 2001::/32 25 2 
确定。

C:\WINDOWS\system32>Reg add HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f 
操作成功完成。 

C:\WINDOWS\system32>Reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters /v DisabledComponents /t REG_DWORD /d 0 /f 
操作成功完成。 

C:\WINDOWS\system32>goto :eof 

C:\WINDOWS\system32>ipconfig /all 

Windows IP 配置

主机名 . . . . . . . . . . . . . : Antecer-PC
主 DNS 后缀 . . . . . . . . . . . : 
节点类型 . . . . . . . . . . . . : 混合
IP 路由已启用 . . . . . . . . . . : 否
WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller Flight
物理地址. . . . . . . . . . . . . : 1C-6F-65-2D-4A-8E
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是
IPv4 地址 . . . . . . . . . . . . : 192.168.1.10(首选) 
子网掩码 . . . . . . . . . . . . : 255.255.255.0
获得租约的时间 . . . . . . . . . : 2018年5月18日 10:20:31
租约过期的时间 . . . . . . . . . : 2018年5月24日 08:03:55
默认网关. . . . . . . . . . . . . : 192.168.1.1
DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
DNS 服务器 . . . . . . . . . . . : 192.168.1.1
TCPIP 上的 NetBIOS . . . . . . . : 已启用

以太网适配器 蓝牙网络连接 2:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network) #2
物理地址. . . . . . . . . . . . . : 00-1A-7D-DA-71-13
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

隧道适配器 Teredo Tunneling Pseudo-Interface:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
DHCP 已启用 . . . . . . . . . . . : 否
自动配置已启用. . . . . . . . . . : 是

C:\WINDOWS\system32>netsh interface ipv6 show teredo 
Teredo 参数
---------------------------------------------
类型 : client (Group Policy) 
服务器名称 : teredo.remlab.net.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : qualified
客户端类型 : teredo client
网络 : unmanaged
NAT : cone
NAT 特殊行为 : UPNP: 是，PortPreserving: 否
本地映射 : 192.168.1.10:62722
外部 NAT 映射 : 111.10.179.239:22679

C:\WINDOWS\system32>netsh interface ipv6 show route 

发布 类型 跃点数 前缀 索引 网关/接口名称
------- -------- --- ------------------------ --- ------------------------
否 手动 256 ::/0 11 Teredo Tunneling Pseudo-Interface
否 系统 256 ::1/128 1 Loopback Pseudo-Interface 1
否 手动 256 2001::/32 11 Teredo Tunneling Pseudo-Interface
否 系统 256 2001:0:53aa:64c:204c:a768:90f5:4c10/128 11 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::/64 10 蓝牙网络连接 2
否 系统 256 fe80::/64 11 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::204c:a768:90f5:4c10/128 11 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::8d04:1416:238f:c26d/128 10 蓝牙网络连接 2
否 系统 256 ff00::/8 1 Loopback Pseudo-Interface 1
否 系统 256 ff00::/8 10 蓝牙网络连接 2
否 系统 256 ff00::/8 11 Teredo Tunneling Pseudo-Interface

C:\WINDOWS\system32>netsh interface ipv6 show interface 

Idx Met MTU 状态 名称
--- ---------- ---------- ------------ ---------------------------
11 75 1280 connected Teredo Tunneling Pseudo-Interface
10 65 1500 disconnected 蓝牙网络连接 2
1 75 4294967295 connected Loopback Pseudo-Interface 1

C:\WINDOWS\system32>netsh interface ipv6 show prefixpolicies 
查询活动状态...

优先顺序 标签 前缀
---------- ----- --------------------------------
50 0 ::1/128
40 1 ::/0
35 4 ::ffff:0:0/96
35 1 2001::/16
30 2 2002::/16
25 2 2001::/32
3 13 fc00::/7
1 12 3ffe::/16
1 11 fec0::/10
1 3 ::/96

C:\WINDOWS\system32>netsh interface ipv6 show address 

接口 11: Teredo Tunneling Pseudo-Interface

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
公用 首选项 infinite infinite 2001:0:53aa:64c:204c:a768:90f5:4c10
其他 首选项 infinite infinite fe80::204c:a768:90f5:4c10%11

接口 10: 蓝牙网络连接 2

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::8d04:1416:238f:c26d%10

接口 1: Loopback Pseudo-Interface 1

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite ::1

C:\WINDOWS\system32>route print 
===========================================================================
接口列表
14...1c 6f 65 2d 4a 8e ......Realtek PCIe GBE Family Controller Flight
10...00 1a 7d da 71 13 ......Bluetooth Device (Personal Area Network) #2
1...........................Software Loopback Interface 1
11...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标 网络掩码 网关 接口 跃点数
0.0.0.0 0.0.0.0 192.168.1.1 192.168.1.10 25
10.134.235.5 255.255.255.255 在链路上 127.0.0.1 76
127.0.0.0 255.0.0.0 在链路上 127.0.0.1 331
127.0.0.1 255.255.255.255 在链路上 127.0.0.1 331
127.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
192.168.1.0 255.255.255.0 在链路上 192.168.1.10 281
192.168.1.10 255.255.255.255 在链路上 192.168.1.10 281
192.168.1.255 255.255.255.255 在链路上 192.168.1.10 281
224.0.0.0 240.0.0.0 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 192.168.1.10 281
255.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
255.255.255.255 255.255.255.255 在链路上 192.168.1.10 281
===========================================================================
永久路由:
无

IPv6 路由表
===========================================================================
活动路由:
接口跃点数网络目标 网关
11 331 ::/0 在链路上
1 331 ::1/128 在链路上
11 331 2001::/32 在链路上
11 331 2001:0:53aa:64c:204c:a768:90f5:4c10/128
在链路上
11 331 fe80::/64 在链路上
11 331 fe80::204c:a768:90f5:4c10/128
在链路上
1 331 ff00::/8 在链路上
11 331 ff00::/8 在链路上
===========================================================================
永久路由:
无
`

**Comment by SeaHOH** [comment]
>服务的实例已在运行中

这方面没有毛病，而且你的 teredo 已经连接上了。

**Comment by zqchina** [comment]
http://test-ipv6.com/
测试无法通过?
貌似跟我碰到的问题一样

**Comment by Antecer** [comment]
然而就是IPv6状态Fail，从而无法联网。

**Comment by zqchina** [comment]
@Antecer 
论坛里找了半天,好像这个问题还没有人知道解决办法.

**Comment by Antecer** [comment]
@zqchina 我照这个做了一遍，最后一次重启后，打开XX-net看到IPv6状态OK，兴奋了没到10秒，又变成Fail了。。。

`
管理员模式运行disable_ipv6.bat。（如是用的组策略模式，请把所有更改过的组策略改成未配置）

删除regedit：计算机\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ 下面的Tcpip6和TCPIP6TUNNEL两个选项。（改动注册表之前请备份）

在自动禁用或重新启用 IPv6 或其组件下载 "在非隧道接口和 IPv6 隧道接口上重新启用 IPv6" ，运行后重启电脑

启动XX-Net，IPv6 隧道 选项卡内点击启动，然后重启。
`

**Comment by SeaHOH** [comment]
再重新打印下 ipconfig /all ，看看有没有变化。

**Comment by Antecer** [comment]
@SeaHOH 貌似没太大的变化

`
PS C:\WINDOWS\system32> ipconfig /all

Windows IP 配置

   主机名  . . . . . . . . . . . . . : Antecer-PC
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller Flight
   物理地址. . . . . . . . . . . . . : 1C-6F-65-2D-4A-8E
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.10(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年5月23日 17:12:15
   租约过期的时间  . . . . . . . . . : 2018年5月24日 17:12:17
   默认网关. . . . . . . . . . . . . : 192.168.1.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
   DNS 服务器  . . . . . . . . . . . : 192.168.1.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 蓝牙网络连接 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network) #2
   物理地址. . . . . . . . . . . . . : 00-1A-7D-DA-71-13
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:53aa:64c:c8f:a5b2:90f5:4c10(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::c8f:a5b2:90f5:4c10%11(首选)
   默认网关. . . . . . . . . . . . . : ::
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

PS C:\WINDOWS\system32> netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.1.10:52519
外部 NAT 映射    : 111.10.179.239:23117
`

**Comment by Antecer** [comment]
@SeaHOH  仍然IPv6 Fail

**Comment by SeaHOH** [comment]
搞不懂微软黑科技

**Comment by ChenyangS** [comment]
关闭网卡里的IPv6

**Comment by zqchina** [comment]
@Antecer

**Comment by zqchina** [comment]
@Antecer

**Comment by zqchina** [comment]
@Antecer

**Comment by zqchina** [comment]
@Antecer 禁用ipv

**Comment by zqchina** [comment]
@Antecer 禁用,删注册表,我的问题还是一样,

**Comment by zqchina** [comment]
@ChenyangS 网卡里关闭IPv6,我的还是没解决.

**Comment by zqchina** [comment]
Ethernet adapter Local Area Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection (3) I218-LM
   Physical Address. . . . . . . . . : 50-7B-9D-04-52-5F
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Wireless Network Connection:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Intel(R) Dual Band Wireless-N 7265
   Physical Address. . . . . . . . . : 4C-34-88-1D-9F-20
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::ccb8:da82:3987:a717%11(Preferred) 
   IPv4 Address. . . . . . . . . . . : 192.168.0.100(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Thursday, May 24, 2018 1:45:49 AM
   Lease Expires . . . . . . . . . . : Thursday, May 24, 2018 3:55:52 AM
   Default Gateway . . . . . . . . . : 192.168.0.253
   DHCP Server . . . . . . . . . . . : 192.168.0.253
   DNS Servers . . . . . . . . . . . : 2001:4860:4860::8888
                                       2001:4860:4860::8844
                                       114.114.114.114
                                       180.76.76.76
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : 2001:0:53aa:64c:2c3b:e562:8c18:f4f9(Preferred) 
   Link-local IPv6 Address . . . . . : fe80::2c3b:e562:8c18:f4f9%27(Preferred) 
   Default Gateway . . . . . . . . . : ::
   NetBIOS over Tcpip. . . . . . . . : Disabled

Tunnel adapter isatap.{3B0597F8-8EDC-4CEC-A175-B1DFEBD4A7A1}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{98E78549-9575-417F-8CF7-95CC44ABD1D0}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #3
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : teredo.remlab.net.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : unmanaged
NAT                     : symmetric (address)
NAT Special Behaviour   : UPNP: No, PortPreserving: No
Local Mapping           : 192.168.0.100:56574
External NAT Mapping    : 115.231.11.6:6813


Publish  Type      Met  Prefix                    Idx  Gateway/Interface Name
-------  --------  ---  ------------------------  ---  ------------------------
No       Manual    256  ::/0                       27  Teredo Tunneling Pseudo-Interface
No       Manual    256  ::1/128                     1  Loopback Pseudo-Interface 1
No       Manual    8    2001::/32                  27  Teredo Tunneling Pseudo-Interface
No       Manual    256  2001:0:53aa:64c:2c3b:e562:8c18:f4f9/128   27  Teredo Tunneling Pseudo-Interface
No       Manual    256  fe80::/64                  17  Local Area Connection
No       Manual    256  fe80::/64                  11  Wireless Network Connection
No       Manual    256  fe80::/64                  27  Teredo Tunneling Pseudo-Interface
No       Manual    256  fe80::5efe:169.254.40.42/128   28  isatap.{3B0597F8-8EDC-4CEC-A175-B1DFEBD4A7A1}
No       Manual    256  fe80::5efe:192.168.0.100/128   29  isatap.{98E78549-9575-417F-8CF7-95CC44ABD1D0}
No       Manual    256  fe80::204f:3bb2:5359:282a/128   17  Local Area Connection
No       Manual    256  fe80::2c3b:e562:8c18:f4f9/128   27  Teredo Tunneling Pseudo-Interface
No       Manual    256  fe80::ccb8:da82:3987:a717/128   11  Wireless Network Connection
No       Manual    256  ff00::/8                    1  Loopback Pseudo-Interface 1
No       Manual    256  ff00::/8                   17  Local Area Connection
No       Manual    256  ff00::/8                   11  Wireless Network Connection
No       Manual    256  ff00::/8                   27  Teredo Tunneling Pseudo-Interface


Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 11          20        1500  connected     Wireless Network Connection
 17           5        1500  disconnected  Local Area Connection
 27          50        1280  connected     Teredo Tunneling Pseudo-Interface
 28          50        1280  disconnected  isatap.{3B0597F8-8EDC-4CEC-A175-B1DFEBD4A7A1}
 29          50        1280  disconnected  isatap.{98E78549-9575-417F-8CF7-95CC44ABD1D0}

Querying active state...

Precedence  Label  Prefix
----------  -----  --------------------------------
        35      1  2001::/16
        30      2  2002::/16
        25      2  2001::/32


Interface 1: Loopback Pseudo-Interface 1

Addr Type  DAD State   Valid Life Pref. Life Address
---------  ----------- ---------- ---------- ------------------------
Other      Preferred     infinite   infinite ::1

Interface 11: Wireless Network Connection

Addr Type  DAD State   Valid Life Pref. Life Address
---------  ----------- ---------- ---------- ------------------------
Other      Preferred     infinite   infinite fe80::ccb8:da82:3987:a717%11

Interface 17: Local Area Connection

Addr Type  DAD State   Valid Life Pref. Life Address
---------  ----------- ---------- ---------- ------------------------
Other      Deprecated    infinite   infinite fe80::204f:3bb2:5359:282a%17

Interface 27: Teredo Tunneling Pseudo-Interface

Addr Type  DAD State   Valid Life Pref. Life Address
---------  ----------- ---------- ---------- ------------------------
Public     Preferred     infinite   infinite 2001:0:53aa:64c:2c3b:e562:8c18:f4f9
Other      Preferred     infinite   infinite fe80::2c3b:e562:8c18:f4f9%27

Interface 28: isatap.{3B0597F8-8EDC-4CEC-A175-B1DFEBD4A7A1}

Addr Type  DAD State   Valid Life Pref. Life Address
---------  ----------- ---------- ---------- ------------------------
Other      Deprecated    infinite   infinite fe80::5efe:169.254.40.42%28

Interface 29: isatap.{98E78549-9575-417F-8CF7-95CC44ABD1D0}

Addr Type  DAD State   Valid Life Pref. Life Address
---------  ----------- ---------- ---------- ------------------------
Other      Deprecated    infinite   infinite fe80::5efe:192.168.0.100%29

===========================================================================
Interface List
 17...50 7b 9d 04 52 5f ......Intel(R) Ethernet Connection (3) I218-LM
 11...4c 34 88 1d 9f 20 ......Intel(R) Dual Band Wireless-N 7265
  1...........................Software Loopback Interface 1
 27...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
 28...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 29...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #3
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    192.168.0.253    192.168.0.100     20
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
      192.168.0.0    255.255.255.0         On-link     192.168.0.100    276
    192.168.0.100  255.255.255.255         On-link     192.168.0.100    276
    192.168.0.255  255.255.255.255         On-link     192.168.0.100    276
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link     192.168.0.100    276
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link     192.168.0.100    276
===========================================================================
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
 27    306 ::/0                     On-link
  1    306 ::1/128                  On-link
 27     58 2001::/32                On-link
 27    306 2001:0:53aa:64c:2c3b:e562:8c18:f4f9/128
                                    On-link
 11    276 fe80::/64                On-link
 27    306 fe80::/64                On-link
 27    306 fe80::2c3b:e562:8c18:f4f9/128
                                    On-link
 11    276 fe80::ccb8:da82:3987:a717/128
                                    On-link
  1    306 ff00::/8                 On-link
 11    276 ff00::/8                 On-link
 27    306 ff00::/8                 On-link
===========================================================================
Persistent Routes:
  None

**Comment by serverLua** [comment]
我也是这个毛病，更新了Windows就好了
同样弄不懂微软黑科技

**Comment by liuliuquick** [comment]
更新一下GFWlist.text ，我就是这样解决的。

**Comment by Antecer** [comment]
@liuliuquick IPv6 Fail 和这个有关吗？扯淡的吧...
顺便表示，这个文件每天都有自动更新的。

**Comment by xylona1900** [comment]
楼主你的问题解决了吗？我现在也遇到了这个问题，而且我用的校园网，Windows前两天也自动更新了。。。

**Comment by Antecer** [comment]
@SeaHOH 问题解决了吗？刚看到话题被关闭。

**Comment by SeaHOH** [comment]
并没有，没发现啥特别的情况，先关闭。
如果你有更多信息提供，直接贴过来就好。

**Comment by SeaHOH** [comment]
#11023 也许可以参考下
