### ISSUE TITLE
升级最新的win10后，x-Tunnel连接不上，也上不了google了？？？？

### ISSUE THREAD

**Issue by clsteam** [XX-net/XX-Net#10744]
最近更新了一下win10系统，3月份的win10有了大更新，但是更新之后发现xxnet用不了了，这是什么原因吗，需要关闭ipv6吗，我尝试过关闭，但是也没有起作用呀？
各位大佬有什么解决办法吗？？ths

**Comment by SeaHOH** [comment]
把 gae_proxy、X-Tunnel 的状态和日志都贴一下。

**Comment by LifeRyan420** [comment]
我的也出问题了，但是我的关了ipv6以后就能用了

**Comment by YoungJAF** [comment]
同样的问题
