### ISSUE TITLE
使用代理后新闻图片不能显示

### ISSUE THREAD

**Issue by xiaoxiaobingguai** [XX-net/XX-Net#10753]
![image](https://user-images.githubusercontent.com/22107779/40409328-1aa8e88c-5e9d-11e8-8792-3c8b67e25800.png)

**Comment by serverLua** [comment]
chrome系浏览器用switchyomega导入官方配置文件后用gae/smart router自动切换，以后自动添加直连和其他规则

**Comment by xiaoxiaobingguai** [comment]
感谢@serverLua
