### ISSUE TITLE
点击桌面图标无法打开xx-net

### ISSUE THREAD

**Issue by zongyanke** [XX-net/XX-Net#10759]
win10无法打开xx-net最新稳定版，能用但是点击桌面图标无反应，托盘里xx-net的图标闪了一下就不见了，只能手动管理员运行start.bat，每次都需要这样，请问怎么回事呢？

**Comment by xxnet** [comment]
​你下载的是哪个版本？

你试试命令行cmd 下执行start.bat，看日志有输出什么

另外把诊断信息贴出来。

**Comment by zongyanke** [comment]
谢谢您的回复，我现在用的是3.12.0版本
下面是我执行start.bat的结果，执行完有一个python的界面闪一下就消失掉了，xx-net也没有正常启动

​
在管理员界面下输出信息跟上面是一致的，但是弹出的界面不会闪一下就消失掉，而是正常工作，xx-net也正常启动，下面是弹出的界面

​
如果把xx-net整个文件解压到桌面，那么点击桌面图标是可用的，xx-net正常启动，但是如果把文件解压到其他路径，那么点击桌面图标无效
另请问诊断信息在哪里可以看到

2018-05-24 11:33 GMT+08:00 Michael.X <notifications@github.com>:

**Comment by SeaHOH** [comment]
不要用邮件回复，图片传不过来。

**Comment by zongyanke** [comment]
谢谢，确实是我的账户权限问题，问题已经解决
