### ISSUE TITLE
X-tunnel可以全局代理么

### ISSUE THREAD

**Issue by xinl22** [XX-net/XX-Net#10754]
感觉只能在浏览器上设置代理，比如说要同步Google drive文件夹可以做到么

**Comment by SeaHOH** [comment]
这种问题一般是先设置成系统代理试试看，
尝试无用后再搜索，比如 `如何设置 Google drive 代理`。

**Comment by serverLua** [comment]
要全局代理的话（所有连接都走X-Tunnel）直接托盘图标设置就好了

**Comment by xinl22** [comment]
@serverLua mac 客户端托盘图标没有X-tunnel全局代理这一项。。

**Comment by SeaHOH** [comment]
Enable Global X-Tunnel
