### ISSUE TITLE
最近半个月XX奇慢无比

### ISSUE THREAD

**Issue by XX-NETGOOD** [XX-net/XX-Net#10768]
IPV6状态经常Fail
IPV6数量波动很大.基本维持在80可用
延迟最近半个月也是高得离谱基本维持在1300-1500
最让人难以忍受的是连接15分钟左右IPV6就会fail.然后只能等待恢复连接
速度也很慢youtube140P都不能流畅播放
X-TUNNEL是也奇慢无比勉强流畅播放144P打开网页速度能急死人。
出现这种情况只在最近半个月

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:111
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 1145
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

属性 | 值
-- | --
请求数 | 1595
响应时间 | 246
往返数 | 22310
较慢 | 1322
重传 | 1248
超时 | 10
当前速度 | Up: 0.0 B/s / Down: 80.0 B/s
使用总量 | Up: 4.7 MB / Down: 338.8 MB

属性 | 值
-- | --
Score | 553
成功数 | 12202
失败数 | 5767
工作数 | 24
使用总量 | Up: 2.6 MB / Down: 207.7 MB

属性 | 值
-- | --
Score | 2509
成功数 | 5908
失败数 | 330
工作数 | 1
使用总量 | Up: 1.7 MB / Down: 87.6 MB

属性 | 值
-- | --
Score | 386000
成功数 | 1422
失败数 | 134
工作数 | 2
使用总量 | Up: 477.7 KB / Down: 43.5 MB

属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0 / Down: 0

属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0.0 B / Down: 0.0 B

**Comment by xxnet** [comment]
​几个通道都出现一定比例的失败，确实会慢。
又不是完全不能用，这种干扰很折腾人。

你是哪个城市、什么ISP？
不用梯子上github等墙外网站，会不会也很慢？

**Comment by XX-NETGOOD** [comment]
湖北武汉电信.不用梯子上github速度很快目测延时100ms左右.最近网络真的很折腾.使用XX4年以来最难受的半个月.延时高一些无所谓，经常性断连（大概15分钟到半小时就会出现）.ipv6 teredo大半时间在Fail状态.X-TUNNEL也不稳定，甚至有些时可能我喝完一杯水页面还没有加载（有点夸张哈）

**Comment by XX-NETGOOD** [comment]
这种状态大概还要维持多久.ipv4时代那会真的一去不复返吗？10000+IP 170延时.稳定可靠高效@ xxnet

**Comment by cloudydayoffice** [comment]
我是广州电信的，同样的感受，间断性断线，重启没事，网速慢，连上的时候看YouTube 480p可以，但是会自动断

**Comment by xxnet** [comment]
​感觉是整个teredo断开了，和ip策略还不是相关。
好像sni的处理有关系，还在研究中

**Comment by SeaHOH** [comment]
我的 teredo 已经被折腾挂了，又不想重启机器，暂时不会测试 IPv6 sni 相关。

**Comment by SasamiMasakiJurai** [comment]
关键是污染速度加快了

而且国内已经建立了ipv6根服务器

以后越来越麻烦了
