### ISSUE TITLE
3.12 ipv6 一下能用一下不能用

### ISSUE THREAD

**Issue by colorsakura** [XX-net/XX-Net#10761]
XX-Net Status:

sys-platform: x86_64, Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
os-system: Linux
os-version: #1 SMP Mon May 21 23:36:36 UTC 2018
os-release: 3.10.0-862.3.2.el7.x86_64
os-detail: Dist:CentOS Linux; Version:7.5.1804; ID:Core
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.12.0
python-version: 2.7.5
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:478
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:28 h2:0
scan-ip-thread-num: 100
ip-quality: 283
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by colorsakura** [comment]
能用时的信息
XX-Net Status:

sys-platform: x86_64, Linux-3.10.0-862.3.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
os-system: Linux
os-version: #1 SMP Mon May 21 23:36:36 UTC 2018
os-release: 3.10.0-862.3.2.el7.x86_64
os-detail: Dist:CentOS Linux; Version:7.5.1804; ID:Core
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.12.0
python-version: 2.7.5
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:487
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:12 h2:0
scan-ip-thread-num: 100
ip-quality: 321
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by whhxmwhh** [comment]
哈哈。您试试删除安全证书重新来解压。应该是很棒的。
墙升高了。。我们的程序猿更厉害。
哈哈技术约束需要技术来解决！
程序猿辛苦了！～
