### ISSUE TITLE
购买x-tunnel之前的几点疑问

### ISSUE THREAD

**Issue by zhaofeihao** [XX-net/XX-Net#10763]
1. miredo和tuntaposx都安装不上，无法开启IPv6是否会对网速有影响？
2.目前在试用xtunnel一开始送的500m流量，较为不稳定，网速也慢，购买后是否也是这样？
3.购买年度套餐使用上限是1200g？

**Comment by zhaofeihao** [comment]
@xxnet

**Comment by zhaofeihao** [comment]
emmm，Macbook pro 10.13.3

**Comment by xxnet** [comment]
1. 开启Ipv6对网速有帮助的
2. 购买流量后不会限速，但网速本身和各地网络状况有关
3. 年套餐使用上限 1200G，一般都足够用的
