### ISSUE TITLE
打开Google很慢

### ISSUE THREAD

**Issue by Allen201705** [XX-net/XX-Net#10772]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  已经是最新版本。
* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
已经看过。
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

####
在chrome上已经安装插件SwichyOmega；GAE AppID已经运行过。
刚安装上XX-Net打开Google很慢，其实是偶尔正常偶尔慢，主要是慢的次数更多。

下面是运行start.bat的日志：
May 25 17:36:47.293 [cloudflare_front][DEBUG] connect 104.19.68.195 fail:error('certificate is none, sni:oienfamilychiropractic.com',)
May 25 17:36:47.539 [gae_proxy][WARNING] not enough ip
May 25 17:36:47.760 [cloudfront_front][INFO] scan_ip add ip:52.46.6.4 time:1210 h2:1
May 25 17:36:47.762 [cloudfront_front][INFO] remove_slowest_ip:216.137.57.169 handshake_time:1355, fails:0
May 25 17:36:51.541 [gae_proxy][WARNING] task POST None /_gh/ timeout
May 25 17:36:51.542 [gae_proxy][DEBUG] GAE_Exception 600 'fetch gae fail'
May 25 17:36:51.543 [gae_proxy][WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
May 25 17:36:52.232 [tls_relay][WARNING] not enough ip
May 25 17:36:54.787 [cloudflare_front][DEBUG] report_connect_fail:104.28.162.42
May 25 17:36:54.789 [cloudflare_front][DEBUG] connect 104.28.162.42 fail:error('certificate is none, sni:ohmygeez.com',)
May 25 17:36:56.232 [gae_proxy][DEBUG] create ssl timeout fail.
May 25 17:36:56.234 [cloudflare_front][DEBUG] create ssl timeout fail.
May 25 17:36:56.235 [tls_relay][DEBUG] create ssl timeout fail.
May 25 17:36:56.591 [gae_proxy][WARNING] not enough ip
May 25 17:36:57.370 [gae_proxy][WARNING] task GET xxnet-update.appspot.com /update.json?uuid=62c8a7af-4d0c-4994-ac2d-0d17a8feb7aa&version=3.11.15&platform=Windows-10-10.0.16299 timeout
May 25 17:36:57.373 [launcher][WARNING] check_update fail:HTTPError()
May 25 17:36:57.374 [launcher][INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to D:\迅雷下载\XX-Net-3.11.15\XX-Net-3.11.15\data\downloads\version.txt, retry:0
May 25 17:36:57.382 [gae_proxy][DEBUG] create ssl timeout fail.
May 25 17:36:57.542 [gae_proxy][WARNING] not enough ip
May 25 17:36:57.849 [cloudfront_front][INFO] scan_ip add ip:54.192.49.235 time:297 h2:0
May 25 17:36:57.851 [cloudfront_front][INFO] remove_slowest_ip:54.230.208.234 handshake_time:314, fails:1
May 25 17:36:59.287 [cloudfront_front][INFO] scan_ip add ip:54.240.189.254 time:213 h2:1
May 25 17:36:59.288 [cloudfront_front][INFO] remove_slowest_ip:54.230.0.169 handshake_time:1276, fails:0
May 25 17:37:02.149 [cloudfront_front][INFO] scan_ip add ip:54.182.253.74 time:339 h2:1
May 25 17:37:02.151 [cloudfront_front][INFO] remove_slowest_ip:52.46.6.4 handshake_time:1210, fails:0
May 25 17:37:05.807 [cloudfront_front][INFO] scan_ip add ip:216.137.36.8 time:247 h2:1
May 25 17:37:05.809 [cloudfront_front][INFO] remove_slowest_ip:54.239.152.54 handshake_time:838, fails:0
May 25 17:37:06.593 [gae_proxy][WARNING] not enough ip
May 25 17:37:07.545 [gae_proxy][WARNING] not enough ip
May 25 17:37:11.830 [cloudfront_front][INFO] scan_ip add ip:52.84.185.167 time:237 h2:1
May 25 17:37:11.834 [cloudfront_front][INFO] remove_slowest_ip:13.33.67.26 handshake_time:760, fails:0
May 25 17:37:16.595 [gae_proxy][WARNING] not enough ip
May 25 17:37:17.548 [gae_proxy][WARNING] not enough ip
May 25 17:37:17.888 [cloudfront_front][INFO] scan_ip add ip:54.182.205.72 time:240 h2:0
May 25 17:37:17.889 [cloudfront_front][INFO] remove_slowest_ip:54.230.87.12 handshake_time:699, fails:0
May 25 17:37:20.563 [cloudfront_front][INFO] scan_ip add ip:52.222.238.62 time:453 h2:1
May 25 17:37:20.565 [cloudfront_front][INFO] Adjust scan thread num from 5 to 4
May 25 17:37:20.566 [cloudfront_front][INFO] remove_slowest_ip:13.35.45.209 handshake_time:644, fails:0
May 25 17:37:21.571 [gae_proxy][WARNING] task POST None /_gh/ timeout
May 25 17:37:21.572 [gae_proxy][DEBUG] GAE_Exception 600 'fetch gae fail'
May 25 17:37:21.576 [gae_proxy][WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
May 25 17:37:21.577 [gae_proxy][DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"
May 25 17:37:21.579 [gae_proxy][WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"
May 25 17:37:21.582 [gae_proxy][WARNING] send response fail
May 25 17:37:22.360 [cloudfront_front][INFO] scan_ip add ip:52.85.154.15 time:392 h2:0
May 25 17:37:22.363 [cloudfront_front][INFO] Adjust scan thread num from 4 to 0
May 25 17:37:22.366 [cloudfront_front][INFO] remove_slowest_ip:52.84.241.193 handshake_time:567, fails:0
May 25 17:37:23.422 [gae_proxy][WARNING] network IPv6 fail
May 25 17:37:26.598 [gae_proxy][WARNING] not enough ip
May 25 17:37:27.550 [gae_proxy][WARNING] not enough ip
May 25 17:37:36.600 [gae_proxy][WARNING] not enough ip
May 25 17:37:37.552 [gae_proxy][WARNING] not enough ip
May 25 17:37:46.602 [gae_proxy][WARNING] not enough ip
May 25 17:37:47.555 [gae_proxy][WARNING] not enough ip
May 25 17:37:51.601 [gae_proxy][DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:64766
May 25 17:37:56.604 [gae_proxy][WARNING] not enough ip
May 25 17:37:56.688 [gae_proxy][DEBUG] create ssl timeout fail.
May 25 17:37:57.556 [gae_proxy][WARNING] not enough ip
May 25 17:37:57.692 [gae_proxy][DEBUG] create ssl timeout fail.
May 25 17:38:06.607 [gae_proxy][WARNING] not enough ip
May 25 17:38:06.653 [gae_proxy][WARNING] task POST None /_gh/ timeout
May 25 17:38:06.657 [gae_proxy][DEBUG] GAE_Exception 600 'fetch gae fail'
May 25 17:38:06.660 [gae_proxy][WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
May 25 17:38:07.558 [gae_proxy][WARNING] not enough ip

**Comment by SeaHOH** [comment]
关掉 gae_proxy 模块

**Comment by SeaHOH** [comment]
cloudfront 和 cloudflare 看起来都很好，就是 gae_proxy 没 IP。

**Comment by xxnet** [comment]
​是啊，如果GAE不能使用，可以用x-tunnel
