### ISSUE TITLE
x-tunnel年付账号，最近老是显示流量用完，流量由之前1200G变成100M？

### ISSUE THREAD

**Issue by alexyuan2013** [XX-net/XX-Net#10778]
去年12月买的年付，15刀
最近发现流量由之前的1000多G变成200M，前些天每天用完了会自动变回200M，最近发现每天又变成了100M，用完了还是可以用。
可是今天突然间不能用了，流量显示为0，想问下是什么原因？

**Comment by xxnet** [comment]
​请给xxnet.dev@gmail.com发邮件，告知x-tunnel帐号

**Comment by ahyiru** [comment]
我也遇到了，去年12月买的，今天发现没流量了，又重新买了一年的，是怎么回事？

**Comment by zengyu24** [comment]
我也是上个月才买的一年，今天看清零 100M了

**Comment by xxnet** [comment]
​已经批量修复了
