### ISSUE TITLE
近期搜索不到内容

### ISSUE THREAD

**Issue by wangqinfei** [XX-net/XX-Net#10770]
按照这两个链接操作
https://github.com/XX-net/XX-Net/wiki/How-to-use
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Chrome%E6%B5%8F%E8%A7%88%E5%99%A8

搜索内容后的提示（这里是搜索的promise）
600:gae_exception:'600:fetch gae fail' https://www.google.com.hk/search?q=promisegae_exception:'600:fetch gae fail' https://www.google.com.hk/search?q=promisegae_exception:'600:fetch gae fail' https://www.google.com.hk/search?q=promise

用的是GAE-PROXY，以前使用都正常，近期使用出现了如上问题！

**Comment by SeaHOH** [comment]
状态，和更多日志。

**Comment by xxnet** [comment]
​试试浏览器里输入
https://www.google.com/ncr
