### ISSUE TITLE
请问Eagleget如何设置XX的自动代理？

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#10773]
问题如题。全局手动设置服务主机端口没有问题。因为Eagleget不像IDM可以自动从IE获取http://127.0.0.1:8086/proxy.pac。所以手动指定到XX-Net-3.11.10\code\default\smart_router\local\proxy.pac。但没有反应需要代理的地址还是不行，但全局就可以。是否我设置有误，请指教

**Comment by SeaHOH** [comment]
Eagleget 不支持 pac 配置，用 8086 就行。

**Comment by kitkw** [comment]
@SeaHOH 这样子哦！！还有每次用IDM下载需要代理的东西，都是正常下载几分钟后就0网速，必需重启XXNET 才正常 。一直反复如此，不停重启xx。    要怎样解决？？

**Comment by kitkw** [comment]
@SeaHOH 哦！谢谢。等下试试看
