### ISSUE TITLE
半年多没碰电脑，变化好大啊，匪子把墙修到天上去了？

### ISSUE THREAD

**Issue by lefantian** [XX-net/XX-Net#10775]
ipv4都失效了吗，现在都要用ipv6了，好高大上的感觉，而且慢的不要不要的，折腾一天好不容易
才把 xxnet调试好，这才翻上来看看，帮忙看看我这算正常了吗？还能更好吗？我是辽宁联通。

![2018-05-25_223421](https://user-images.githubusercontent.com/13671136/40550805-bf951d44-606d-11e8-8704-cf7293601309.jpg)

![2018-05-25_223436](https://user-images.githubusercontent.com/13671136/40550827-c95c3e7a-606d-11e8-9047-a50ca175d9ea.jpg)

![2018-05-25_224128](https://user-images.githubusercontent.com/13671136/40550878-e7560406-606d-11e8-8272-017e22caff20.jpg)

* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by caofengzi** [comment]
不要有太高的奢求，xx以及所有參與的開發者已經盡力了，能夠翻就行了，總比不能翻好，ip不在與數量而在於精。

**Comment by lefantian** [comment]
是的，非常感谢一直在维护xxnet技术人员，只是好久没用了，想发帖出来了解一下

**Comment by lefantian** [comment]
是的，非常感谢一直在维护xxnet技术人员，只是好久没用了，想发帖出来了解一下

**Comment by xxnet** [comment]
​诊断信息看是正常的。
速度慢，可以试试IPv6隧道里，切换服务器看看

**Comment by xdg92** [comment]
呵呵，和楼主一样能翻 ，但速度跟  IPV4没法比。

**Comment by nedved888** [comment]
原生ipv6美滋滋，比ipv4快，开发作者辛苦了，点赞！
