### ISSUE TITLE
IP6开启，部署了但是连不上google帮我看看么

### ISSUE THREAD

**Issue by zhishihuanjue** [XX-net/XX-Net#10782]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv4
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

访问google返回信息
600:gae_exception:'600:fetch gae fail' https://www.google.com.hk/gae_exception:'600:fetch gae fail' https://www.google.com.hk/gae_exception:'600:fetch gae fail' https://www.google.com.hk

**Comment by SeaHOH** [comment]
等待扫描。
另，建议更新。
