### ISSUE TITLE
googleplay没法搜索？

### ISSUE THREAD

**Issue by asmosn** [XX-net/XX-Net#10781]
app链接页面能代开 ，但是搜索就出现图中页面，有遇到这问题的吗？
![qq 20180526190517](https://user-images.githubusercontent.com/9925193/40575455-cf449562-6117-11e8-9e20-d8a978723231.png)

**Comment by SeaHOH** [comment]
请删除自定义 play.google.com 设置

**Comment by SeaHOH** [comment]
play.google.com 无法通过 GAE 平台进行搜索，所以默认设置是直连。
config.js 如果自定义了走 GAE 就会这样。
