### ISSUE TITLE
双击start.vbs什么反应也没有。。。

### ISSUE THREAD

**Issue by qianmiandenvgui** [XX-net/XX-Net#10787]
双击start.vbs什么反应也没有，，也没看到进程里有新运行的程序。。。。找了半天也没发现原因在哪里。。。可能会是什么原因呢？不光打不开，，右键——编辑  也没反应
版本3.12.0

**Comment by SeaHOH** [comment]
文件关联被修改，估计你的电脑还中毒了。

**Comment by qianmiandenvgui** [comment]
可以排除中毒情况。。电脑上还有3.9.几的版本 可以打开  3.10.几的三个版本 双击没反应。。。

**Comment by SeaHOH** [comment]
>文件关联被修改

这才是重点好不好

**Comment by qianmiandenvgui** [comment]
旧版本的可以运行  关联肯定没有问题吧。。我也查看了关联了  是对的 windows based script host

**Comment by qianmiandenvgui** [comment]
看到一个类似的帖子，用你发的 打印测试   试过了 可以在一个窗口里显示出来 打印测试

**Comment by SeaHOH** [comment]
XP？

**Comment by qianmiandenvgui** [comment]
win 10 ltsb   谢谢你一直都在回复啦  我还是找不到是因为什么  发这个帖子的前一天其实还可以用的。我也只是时间久了 开电脑看看有没有xxnet 的新版本 下载了 然后就关了电脑了。。第二天开机就遇到这么个情况
系统还原到了之前几天的状态， 可以用了。。。莫名其妙

**Comment by SeaHOH** [comment]
还原后，3.10.* 之后的版本就可以正常运行了？

**Comment by qianmiandenvgui** [comment]
我试了11.15  现在用12.0 都可以 10的那几个删掉了。。还原前也下了11.15 一样打不开。。。

**Comment by SeaHOH** [comment]
先关闭，有问题可以继续在此回复。
