### ISSUE TITLE
3.12.0使用感受交流

### ISSUE THREAD

**Issue by cloudydayoffice** [XX-net/XX-Net#10780]
使用了新版后一个下午，断线状况没有，也流畅，就是ins搜不出东西（估计网站问题）

不知道你们有什么感受

**Comment by bitternolis** [comment]
500ip ，延迟300

**Comment by whhxmwhh** [comment]
IPv4 状态	OK
IPv6 状态(如何开启)	OK
IPv4 IP数	0
IPv6 IP数	501
XX-Net 状态	工作
IP延迟	592
延时1000我都 可以接受的。只要能稳定链接就好.
