### ISSUE TITLE
xxnet部署APPID！！求救 

### ISSUE THREAD

**Issue by wangzhantao** [XX-net/XX-Net#10785]
![1](https://user-images.githubusercontent.com/39663127/40582390-a5d264bc-61a7-11e8-8be2-7b9afefb89c0.png)
![2](https://user-images.githubusercontent.com/39663127/40582391-a60c546a-61a7-11e8-889b-30fd23d8225a.png)

**Comment by SeaHOH** [comment]
好像是没有权限删除旧的过期令牌导致，尝试重新用管理员权限运行 XX-Net。
