### ISSUE TITLE
启动一段时间后，总是会显示连接尚未建立，看日志里面一堆exception和timeout还有fail

### ISSUE THREAD

**Issue by spenserwong** [XX-net/XX-Net#10799]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:498
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 523
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

**Comment by spenserwong** [comment]
@SeaHOH 谢谢，在试了

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
