### ISSUE TITLE
个别 youtube 视频无法播放

### ISSUE THREAD

**Issue by iopxiang** [XX-net/XX-Net#10798]
我发现梁静茹的《铁汉》播放不了，别的视频都没问题。连接如下 https://www.youtube.com/watch?v=ggOxahTrsm0
现在防火长城已经做得这么精细了吗？

* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by MadMaxPayne8964** [comment]
我可以播放
