### ISSUE TITLE
IPV6 顯示FAIL

### ISSUE THREAD

**Issue by zhangzongyao** [XX-net/XX-Net#10797]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？最新版本
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）看過

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:500
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 315
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by hudingyin** [comment]
Restart your computer

**Comment by SeaHOH** [comment]
手动升级到最新版（3.12.0）尝试切换服务器
