### ISSUE TITLE
Macbook air 无法部署服务端，系统版本是10.10.2 ，使用的是xx-net1.7.1,小区宽带是长城宽带

### ISSUE THREAD

**Issue by zwjing** [XX-net/XX-Net#108]
Macbook air 无法部署服务端，系统版本是10.10.2 ，使用的是xx-net1.7.1,小区宽带是长城宽带，显示的内容为下方所示，求大家帮忙解决啊
Apr  3 23:11:51 - ============  Begin upload  ============
appid:zwjing341 

Apr  3 23:11:51 - Application: zwjing341
Apr  3 23:11:51 - Host: appengine.google.com
Apr  3 23:11:51 - Rolling back the update.
Apr  3 23:11:51 - upload  fail: ''

Apr  3 23:11:51 - Retry again.

GoAgent状态信息
Property	Value
Sys Platform	darwin
OS System	Darwin
OS version	Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64
OS release	14.1.0
OS detail	Release:10.10.2; Version:('', '', '') Machine:x86_64
architecture	64bit
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18
XX-Net Version	1.7.1
Launcher Version	1.2.0
GoAgent Version	3.1.44
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087
working appids	
Out of Quota appids	
Not Exist appids	gmail.com|zwjing34
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	3000

日志页
Apr 3 23:11:39 - [DEBUG] GoAgent Web_control 127.0.0.1:59629 "GET /deploy?cmd=get_log 
Apr 3 23:11:51 - [DEBUG] GoAgent web_control 127.0.0.1:59648 POST /deploy?cmd=deploy 
Apr 3 23:11:51 - [INFO] deploy begin.
Apr 3 23:11:51 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:51 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:51 - [DEBUG] ssl_pool.get:210.158.146.121 handshake:186
Apr 3 23:11:51 - [DEBUG] ssl conn_num:5
Apr 3 23:11:51 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:52 - [DEBUG] GoAgent Web_control 127.0.0.1:59653 "GET /deploy?cmd=get_log 
Apr 3 23:11:52 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:52 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:52 - [DEBUG] ssl_pool.get:114.4.41.234 handshake:268
Apr 3 23:11:52 - [DEBUG] ssl conn_num:4
Apr 3 23:11:52 - [DEBUG] sort ip time:5
Apr 3 23:11:52 - [DEBUG] get ip:210.158.146.121 t:186
Apr 3 23:11:53 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:53 - [DEBUG] create_ssl update ip:210.158.146.121 time:209
Apr 3 23:11:53 - [DEBUG] GoAgent Web_control 127.0.0.1:59657 "GET /deploy?cmd=get_log 
Apr 3 23:11:54 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:54 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:54 - [DEBUG] ssl_pool.get:210.158.146.121 handshake:209
Apr 3 23:11:54 - [DEBUG] ssl conn_num:4
Apr 3 23:11:54 - [DEBUG] get ip:114.4.41.234 t:268
Apr 3 23:11:54 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:54 - [DEBUG] create_ssl update ip:114.4.41.234 time:272
Apr 3 23:11:54 - [DEBUG] GoAgent Web_control 127.0.0.1:59660 "GET /deploy?cmd=get_log 
Apr 3 23:11:55 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:55 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:55 - [DEBUG] ssl_pool.get:114.4.41.238 handshake:271
Apr 3 23:11:55 - [DEBUG] ssl conn_num:4
Apr 3 23:11:55 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:55 - [DEBUG] get ip:114.4.41.238 t:271
Apr 3 23:11:55 - [DEBUG] GoAgent Web_control 127.0.0.1:59666 "GET /deploy?cmd=get_log 
Apr 3 23:11:56 - [DEBUG] create_ssl update ip:114.4.41.238 time:291
Apr 3 23:11:56 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:56 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:56 - [DEBUG] ssl_pool.get:114.4.41.234 handshake:272
Apr 3 23:11:56 - [DEBUG] ssl conn_num:4
Apr 3 23:11:56 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:56 - [DEBUG] GoAgent Web_control 127.0.0.1:59668 "GET /deploy?cmd=get_log 
Apr 3 23:11:57 - [DEBUG] get ip:210.158.146.249 t:309
Apr 3 23:11:57 - [DEBUG] create_ssl update ip:210.158.146.249 time:282
Apr 3 23:11:57 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:57 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:57 - [DEBUG] ssl_pool.get:210.158.146.249 handshake:282
Apr 3 23:11:57 - [DEBUG] ssl conn_num:4
Apr 3 23:11:57 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:57 - [DEBUG] GoAgent Web_control 127.0.0.1:59674 "GET /deploy?cmd=get_log 
Apr 3 23:11:58 - [DEBUG] get ip:210.158.146.219 t:351
Apr 3 23:11:58 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:11:58 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:11:58 - [DEBUG] ssl_pool.get:114.4.41.238 handshake:291
Apr 3 23:11:58 - [DEBUG] ssl conn_num:3
Apr 3 23:11:58 - [DEBUG] get ip:114.4.41.229 t:352
Apr 3 23:11:58 - [DEBUG] GoAgent Web_control 127.0.0.1:59680 "GET /deploy?cmd=get_log 
Apr 3 23:11:58 - [DEBUG] create_ssl update ip:210.158.146.219 time:261
Apr 3 23:11:59 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:11:59 - [DEBUG] create_ssl update ip:114.4.41.229 time:272
Apr 3 23:11:59 - [DEBUG] GoAgent Web_control 127.0.0.1:59682 "GET /deploy?cmd=get_log 
Apr 3 23:12:00 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:12:00 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:12:00 - [DEBUG] ssl_pool.get:210.158.146.219 handshake:261
Apr 3 23:12:00 - [DEBUG] ssl conn_num:4
Apr 3 23:12:00 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:12:00 - [DEBUG] get ip:114.4.41.245 t:423
Apr 3 23:12:00 - [DEBUG] create_ssl update ip:114.4.41.245 time:301
Apr 3 23:12:00 - [DEBUG] GoAgent Web_control 127.0.0.1:59685 "GET /deploy?cmd=get_log 
Apr 3 23:12:01 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:12:01 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:12:01 - [DEBUG] ssl_pool.get:114.4.41.229 handshake:272
Apr 3 23:12:01 - [DEBUG] ssl conn_num:4
Apr 3 23:12:01 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:12:01 - [DEBUG] get ip:106.162.198.89 t:425
Apr 3 23:12:01 - [DEBUG] GoAgent Web_control 127.0.0.1:59691 "GET /deploy?cmd=get_log 
Apr 3 23:12:02 - [INFO] GAE CONNECT appengine.google.com:443 
Apr 3 23:12:02 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=zwjing341
Apr 3 23:12:02 - [DEBUG] ssl_pool.get:114.4.41.245 handshake:301
Apr 3 23:12:02 - [DEBUG] ssl conn_num:3
Apr 3 23:12:02 - [DEBUG] get ip:210.245.14.172 t:491
Apr 3 23:12:02 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 3 23:12:02 - [DEBUG] GoAgent Web_control 127.0.0.1:59694 "GET /deploy?cmd=get_log 
Apr 3 23:12:02 - [DEBUG] create_ssl update ip:210.245.14.172 time:571
Apr 3 23:12:03 - [DEBUG] create_ssl 106.162.198.89 fail:timed out c:0 h:0
Apr 3 23:12:03 - [INFO] remove ip:106.162.198.89 left amount:2999 gws_num:2999
Apr 3 23:12:03 - [DEBUG] sort ip time:8
Apr 3 23:12:03 - [DEBUG] get ip:210.158.146.121 t:209
Apr 3 23:12:04 - [DEBUG] get ip:199.87.241.51 t:519
Apr 3 23:12:04 - [DEBUG] create_ssl update ip:199.87.241.51 time:514
Apr 3 23:12:05 - [DEBUG] create_ssl update ip:210.158.146.121 time:990

**Comment by yqfang** [comment]
No usable appid left, add new appid to continue use GoAgent, 没填appid? 或者 appid 不可用 ? 去:　https://appengine.google.com/　看一下你 appId 的 status
