### ISSUE TITLE
智能路由和PAC代理的区别是啥

### ISSUE THREAD

**Issue by hdcscy** [XX-net/XX-Net#10800]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  是的。

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
 是的。

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by xxnet** [comment]
​PAC 是固定的黑/白名单列表
智能路由是先参考黑名单和白名单，再动态检测判断、学习，效果会更好更准确。

**Comment by hdcscy** [comment]
非常感谢您的回答！ @xxnet
