### ISSUE TITLE
捐献了appid十几个小时过去了，还没收到回信，大家有遇到这种情况吗？

### ISSUE THREAD

**Issue by swinL** [XX-net/XX-Net#10808]
如题:
       这是第二次捐献appid，十几个小时过去了还没收到回信，过程是这样的:
1.本人于  5月26日 捐赠appid邮件发送过了几天没收到回信，就去排查了下，是我忘记设置了捐献appid的所属权了 ，然后就配置了下，重新发送了信息，过去了十几个小时还没收到回信，有遇到类似情况的吗？
下面是邮件时间和说明：
![image](https://user-images.githubusercontent.com/27482687/40696708-812c17f8-63f9-11e8-9ff1-84491460e279.png)

有老铁能告知下 处理方法吗？

**Comment by AnyWAT** [comment]
😜急于使用？提供账号接收。。。

**Comment by swinL** [comment]
@AnyWAT  
账号  lh409527144@gmail.com 多谢！
