### ISSUE TITLE
Appid部署成功，但是配置时提示无效

### ISSUE THREAD

**Issue by goodhuntin** [XX-net/XX-Net#10807]
日志中提示部署成功了，但是检测无效

**Comment by SeaHOH** [comment]
https://你的appid.appspot.com/ 查看是否部署成功

**Comment by goodhuntin** [comment]
提示Hello,world，应该是部署失败了
必须按照google的教程一步一步来么？我记得运行gcloud app deploy app.yaml appid的时候提示需要billing-enable，然后无法运行，有简单点的步骤么？

**Comment by SeaHOH** [comment]
参考 #4720

**Comment by goodhuntin** [comment]
运行gcloud app deploy时候提示需要app.yaml，输入y后又提示
This looks like a Python app.  If so, please enter the command to run 
 the app in production (enter nothing if it's not a python app):
我怎么知道应该输入什么命令?难道不是应该教程告诉我么？

**Comment by SeaHOH** [comment]
#10533 这个就是参考 4720 解决的，其中稍微整理了一下。

主要是你没有严格按照教程来，所以才有这种问题。

**Comment by SeaHOH** [comment]
关闭后仍可回复
