### ISSUE TITLE
看到网上说的新屏蔽技术对XX的影响大吗？

### ISSUE THREAD

**Issue by zhenmeikeai** [XX-net/XX-Net#10806]
![1](https://user-images.githubusercontent.com/39674202/40664375-63ce97e2-638d-11e8-865f-f33a6544fc7a.jpg)
还有下面的评论真的能定位吗？
![2](https://user-images.githubusercontent.com/39674202/40664938-9fbcb9d6-638e-11e8-9996-d9de0097086e.png)

**Comment by xxnet** [comment]
​这个技术主要是针对SS的，对XX-Net影响不大

**Comment by MSTWHD** [comment]
我前段时间开始用SSR了，昨天之前一直是流畅观看油管1080P60FPS和twitch源的，但从昨晚开始，打开网页都非常吃力了，视频最低清晰度都卡成PPT，不知道还要持续多久，难受。

**Comment by MSTWHD** [comment]
不过XX目前还可以流畅观看油管1080P60FPS，观看twitch直播效果也不错。
