### ISSUE TITLE
 python2.7 的requests中 用这个的gaeproxy代理不工作

### ISSUE THREAD

**Issue by swinL** [XX-net/XX-Net#10805]
有人在 python2.7 的requests中 用这个的gaeproxy代理成功过的吗？我弄了几天没成功，谷歌方法试了好几个都没成功

我使用X-TUNNEL就好了
代理设置片段代码:
![image](https://user-images.githubusercontent.com/27482687/40660083-9d0829a2-6382-11e8-9f8b-6a17f4c17259.png)
大码部分是 登录代理的用户和密码，用户和密码里面是常规的字母和阿拉伯数字

使用gae-proxy运行直接报错:
 Max retries exceeded with url: /huxing (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by swinL** [comment]
![image](https://user-images.githubusercontent.com/27482687/40660246-03be2a16-6383-11e8-802e-abf39c207379.png)
调用

**Comment by swinL** [comment]
@SeaHOH   我是要爬一个网站的信息，但是对方网站有基于ip反爬的机制 想用这个gae_proxy代理IP过去
![image](https://user-images.githubusercontent.com/27482687/40696388-42cc0db6-63f8-11e8-91f6-cd13af34688b.png)
![image](https://user-images.githubusercontent.com/27482687/40696408-524a7e80-63f8-11e8-8072-158669c9240b.png)
这个地方的设置 不是用于用户验证的吗

**Comment by SeaHOH** [comment]
所以这个用户验证是在哪里？gae_proxy 是不需要用户验证的。

**Comment by swinL** [comment]
@SeaHOH  我直接去掉了 用户和密码  配置那里也修改成和 X-TUNNEL 配置一样了 还是不行

**Comment by SeaHOH** [comment]
> 所以这个用户验证是在哪里？

对方网站？
如果是，直接访问，浏览器会跳出验证框。

**Comment by swinL** [comment]
不是对方网站的认证 ，这个是我在xx-net中的设置

**Comment by SeaHOH** [comment]
再次说明一下：
gae_proxy 是不需要用户验证的，因为根本就没有这种设置。
