### ISSUE TITLE
XX-Net 3.12 访问BBC和DW的问题

### ISSUE THREAD

**Issue by ghost** [XX-net/XX-Net#10817]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by hellodongfang** [comment]
XX-Net 3.12 不能访问bbc.com和dw.com, 错误如下：

未发送任何数据。
ERR_EMPTY_RESPONSE

**Comment by SeaHOH** [comment]
日志

**Comment by xiaoyaooo** [comment]
Jun 01 18:18:59.767 - [DEBUG] http ('127.0.0.1', 14236) connect to www.dw.com:80 GET /

Jun 01 18:18:59.768 - [DEBUG] host:www.dw.com:80 do gae

Jun 01 18:19:00.179 - [ERROR] domain host:www.dw.com:80 rule:gae except:ValueError('need more than 0 values to unpack',)

Jun 01 18:19:00.179 - [ERROR] Except stack:Traceback (most recent call last): File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\smart_router\local\smart_route.py", line 374, in try_loop do_gae(sock, host, port, client_address, left_buf) File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\smart_router\local\smart_route.py", line 343, in do_gae req.do_METHOD() File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\gae_proxy\local\proxy_handler.py", line 252, in do_METHOD return self.go_AGENT() File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\gae_proxy\local\proxy_handler.py", line 300, in go_AGENT gae_handler.handler(self.command, self.host, self.url, request_headers, payload, self.wfile) File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\gae_proxy\local\gae_handler.py", line 612, in handler CMF, FLG = bytearray(decoded_data0[:2]) ValueError: need more than 0 values to unpack

Jun 01 18:19:00.348 - [DEBUG] http ('127.0.0.1', 14238) connect to www.dw.com:80 GET /

Jun 01 18:19:00.349 - [DEBUG] host:www.dw.com:80 do gae

Jun 01 18:19:00.363 - [DEBUG] host:api.userstyles.org:443 do gae

Jun 01 18:19:00.787 - [ERROR] domain host:www.dw.com:80 rule:gae except:ValueError('need more than 0 values to unpack',)

Jun 01 18:19:00.787 - [ERROR] Except stack:Traceback (most recent call last): File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\smart_router\local\smart_route.py", line 374, in try_loop do_gae(sock, host, port, client_address, left_buf) File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\smart_router\local\smart_route.py", line 343, in do_gae req.do_METHOD() File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\gae_proxy\local\proxy_handler.py", line 252, in do_METHOD return self.go_AGENT() File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\gae_proxy\local\proxy_handler.py", line 300, in go_AGENT gae_handler.handler(self.command, self.host, self.url, request_headers, payload, self.wfile) File "E:\Users\lenovo\Desktop\XX-Net-master\XX-Net-master\code\3.12.0\gae_proxy\local\gae_handler.py", line 612, in handler CMF, FLG = bytearray(decoded_data0[:2]) ValueError: need more than 0 values to unpack

**Comment by SeaHOH** [comment]
@xiaoyaooo 麻烦测试下 3.12.1 版本是否正确修复，我这里未修复版本无法复现问题。

**Comment by xiaoyaooo** [comment]
@SeaHOH 3.12.1版本修复了，tks
