### ISSUE TITLE
127.0.0.1:8085今天突然打不开了...

### ISSUE THREAD

**Issue by xuzhuo99hy** [XX-net/XX-Net#10819]
xx-net的主页面 访问不了了

**Comment by SeaHOH** [comment]
代理设置是否排除 127.0.0.1？
是否有 python 的进程？
是更新过后无法打开吗？检查是否更新完整。
操作系统是什么？XX-Net 版本？
data 文件夹是否有 `.log` 日志文件？

**Comment by xuzhuo99hy** [comment]
没有使用其他代理
有python的进程,  
操作系统是win7的,
最近这周没有更新, xx-net版本是 XX-Net-3.11.14
data\launcher下有个"launcher.log"文件

**Comment by xuzhuo99hy** [comment]
May 31 16:39:49.566 - [DEBUG] good, xxnet:8085 clear!
May 31 16:39:49.566 - [DEBUG] finished confirm_xxnet_exit
May 31 16:39:50.750 - [INFO] module gae_proxy started
May 31 16:39:50.750 - [INFO] start gae_proxy time cost:1181 ms
May 31 16:39:50.887 - [INFO] module x_tunnel started
May 31 16:39:50.887 - [INFO] start x_tunnel time cost:137 ms
May 31 16:39:51.024 - [INFO] module smart_router started
May 31 16:39:51.024 - [INFO] start smart_router time cost:136 ms
May 31 16:39:51.024 - [INFO] begin to start web control
May 31 16:39:51.025 - [INFO] server 127.0.0.1:8085 started.
May 31 16:39:51.029 - [INFO] launcher web control started.
May 31 16:39:52.069 - [INFO] get uuid:57c955a0-5566-491f-bf3c-88a604ebc36c
May 31 16:39:53.065 - [WARNING] check_update fail:URLError(error(10061, ''),)
May 31 16:39:53.066 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to D:\installed\XX-Net-3.11.14\data\downloads\version.txt, retry:0
这个是退出后启动的日志

**Comment by SeaHOH** [comment]
退出 XX-Net，如有无法结束的 python 进程，用任务管理器强制结束。
然后再打开试试。

**Comment by xuzhuo99hy** [comment]
可以了  杀掉进程就好了
