### ISSUE TITLE
请问gae配置中的使用ipv6开关去哪儿了？

### ISSUE THREAD

**Issue by sxqqslf** [XX-net/XX-Net#10811]
ipv6-win7-小白指南中的第七步，<高级选项>在3.11.10中没有，做完前面的操作后，显示连接尚未建立，ipv6：failed
PS：用的学校的网络；另外请问 “有效的Teredo接口名称”可以用哪条命令获取，显示在结果的哪一列中

**Comment by SeaHOH** [comment]
现在默认会使用 IPv6，最新版高级页面可以管理 teredo 隧道。
