### ISSUE TITLE
win10 system new vision 3.11.15无法开启ipv6，已尝试#10282的方法依旧无法使用ipv6

### ISSUE THREAD

**Issue by allanharper** [XX-net/XX-Net#10814]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by swinL** [comment]
尝试下这个命令 看看  我之前也遇到过 执行下面这个命令后，重新开启就好了
netsh int ipv6 set teredo client teredo.remlab.net
有时候也不行 ，过几个小时或者一天后 自己又好了，是有点奇怪

**Comment by SeaHOH** [comment]
请手动升级到最新版（3.12.0）再次尝试

**Comment by allanharper** [comment]
@SeaHOH 已更新，但是线路不太稳定。一会可以一会全断

**Comment by SeaHOH** [comment]
不稳定很正常，之前遇到过到 teredo 服务器的 udp 包全部失败的情况。
