### ISSUE TITLE
关于XX-Net支持的应用的问题

### ISSUE THREAD

**Issue by cngoodboy** [XX-net/XX-Net#10810]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？是。

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）？是。

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：XX-Net支持的应用有哪些？是仅仅支持浏览器还是什么？

**Comment by SeaHOH** [comment]
点击上方 wiki 链接了解

**Comment by cngoodboy** [comment]
没有找到

**Comment by SeaHOH** [comment]
一个 http 1.1，一个 socks，通用特性就不说了，局限性 wiki 里面都有介绍。
