### ISSUE TITLE
XX-net 3.11.15 在Ubuntu上  下载的大文件验证码总是不对

### ISSUE THREAD

**Issue by xpf7622** [XX-net/XX-Net#10816]
布置后，在ubuntu 16.04上无论终端（export htts_proxy=127.0.0.1:8087 export http_proxy=127.0.0.1:8087）还是浏览器下载大文件（>200M,估计值），md5验证码总是不对。下五六便都不对。
但在windows下，3.10版本就好多了。
不知是不是XX-net的问题。

**Comment by SeaHOH** [comment]
看看 #10479，跟你这个差不多，但我试过没法复现。

**Comment by SeaHOH** [comment]
也许可以尝试把 autorange 的线程改小一点。

**Comment by xpf7622** [comment]
autorange 在哪儿改？

**Comment by SeaHOH** [comment]
AUTORANGE_THREADS
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by xpf7622** [comment]
@SeaHOH  这个配置我也配过，把哪个值降低点？没有autorange参数。

**Comment by xpf7622** [comment]
https://oceandata.sci.gsfc.nasa.gov/ocssw/  去这个网址下几个bundle，就知道了。基本上下五六次都对不上sha256

**Comment by SeaHOH** [comment]
改小试试 `AUTORANGE_THREADS`
贴图你也看到了，反正我是无法复现此问题。

**Comment by SeaHOH** [comment]
还有问题吗？如果改小行得通麻烦说下。

**Comment by SeaHOH** [comment]
@xpf7622
