### ISSUE TITLE
mac总显示not enough ip

### ISSUE THREAD

**Issue by Avenray** [XX-net/XX-Net#10818]
小白问个问题，mac总显示not enough ip，应该怎么办呢？
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
xxnet-version: 3.12.0
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
