### ISSUE TITLE
知乎上不去

### ISSUE THREAD

**Issue by 10lumiya10** [XX-net/XX-Net#10813]
如图，zhi知乎显示流量异常，但是我没代理知乎，知乎给的ip也不知道哪里来的
![image](https://user-images.githubusercontent.com/36228639/40724684-346000fa-6454-11e8-9941-5abdd314efc3.png)
![image](https://user-images.githubusercontent.com/36228639/40724813-8d129960-6454-11e8-8364-e8e9c31a2dd2.png)
![image](https://user-images.githubusercontent.com/36228639/40724853-a33ed7da-6454-11e8-8652-c724f4bee6d5.png)
这是知乎的问题还是其他的什么问题啊

**Comment by victor-siu** [comment]
我也遇上了同樣的問題，連顯示的IP地址也與上圖一樣。

**Comment by byxn** [comment]
上知乎不用代理也这样吗

**Comment by victor-siu** [comment]
沒用任何代理也是這樣。

**Comment by SeaHOH** [comment]
似乎和 XX-Net 无关
