### ISSUE TITLE
浏览器代理和CA证书都是Fail怎么解决？

### ISSUE THREAD

**Issue by 3356689061** [XX-net/XX-Net#10820]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:57 ipv4:0 ipv6:21
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:10 h2:0
scan-ip-thread-num: 10
ip-quality: 1375
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
能否正常使用。
如不能，请检查代理设置。

**Comment by whhxmwhh** [comment]
删除原来旧的证书。重新下载安装xx-net。
会自动安装证书的。
