### ISSUE TITLE
XX-Net wiki 文件命名在windows中无效（致使git无法检出）

### ISSUE THREAD

**Issue by c0001** [XX-net/XX-Net#10825]
你好 XX-net 的 Maintainer:

由于网络问题，我通过克隆XX-Net的wiki的git repo来学习和查阅新特性，但是在最新的commit中我无法在windows平台上（win10-170134）检出一个文件： 

GoAgent-manual-config-(-data\gae_proxy\config.json-).textile

我认为这是文件名命名在win的ntfs文件系统上非法造成的（linux上正常）。

整个git检出错误信息是：
```
 error: unable to create file GoAgent-manual-config-(-data\gae_proxy\config.json-).textile: No such file or directory
Updating fdc4afe..c2160ed
```
希望修复

**Comment by SeaHOH** [comment]
已删除。
wiki 是开放的，谁都可以进行编辑，当你遇到不正确的信息时可以自行修改。

**Comment by c0001** [comment]
@SeaHOH  谢谢修复， 请问你说的开放就是说wiki的repo的pr是不需要审核的吗？

**Comment by SeaHOH** [comment]
直接编辑、添加、删除都可以。
不要搞破坏哈，恢复起来还是要费手脚的。
