### ISSUE TITLE
Youtube 504 Time out，其他网站正常

### ISSUE THREAD

**Issue by QGB** [XX-net/XX-Net#10834]
proxy][WARNING] IP:2806:1050:cfff:4::11 host:www.youtube.com not support GAE, server type:HTTP server (unknown) status:403
Jun 02 00:12:07.265 [gae_proxy][INFO] remove ip:2806:1050:cfff:4::11 left amount:8999 target_num:8999
Jun 02 00:12:07.265 [gae_proxy][DEBUG] 2806:1050:cfff:4::11 worker close:
Jun 02 00:12:07.266 [gae_proxy][WARNING] read fail, ip:2806:1050:cfff:4::11, chunk:0 url:GET www.youtube.com/results?search_query=David%20DB%20Baumgold%20&pbjreload=10 task.timeout:57 e:error(9, 'Bad file descriptor'

504 GAEProxy Proxy Time out
连接超时，先休息一会再来！

重启xxnet，检查ip 无效

**Comment by SeaHOH** [comment]
版本以及 config.json 内容

**Comment by QGB** [comment]
@SeaHOH    一顿乱搜，问题解决了
主要是参考  #5704
成功的config.json

{
  "listen_ip": "0.0.0.0", 
  "max_scan_ip_thread_num": 55, 
"hosts_gae":[

],
"hosts_gae_endswith":[
	"accounts.google.com",
	"mail.google.com",
	".youtube.com"
],
"hosts_direct":[
	
],  
 "hosts_direct_endswith": [
    ".appspot.com"
],
  "max_good_ip_num": 9000, 
  "use_ipv6": "force_ipv6", 
  "auto_adjust_scan_ip_thread_num": 0
}

**Comment by just4id** [comment]
公共AppID?

**Comment by SeaHOH** [comment]
哦，你之前是加了直连对吧。
现在似乎是有点问题，不过我没有使用 IPv6，等有空的时候会做个测试。

**Comment by QGB** [comment]
@SeaHOH   这是个什么情况  

Jun 02 20:45:05.103 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "G:\QGB\software\xxnet\code\3.11.7\python27\1.0\lib\noarch\simple_http_server.py", line 166, in handle_one_request
    self.do_GET()
  File "G:\QGB\software\xxnet\code\3.11.7\gae_proxy\local\proxy_handler.py", line 200, in do_METHOD
    return self.forward_local()
  File "G:\QGB\software\xxnet\code\3.11.7\gae_proxy\local\proxy_handler.py", line 112, in forward_local
    self.wfile.write("".join(out_list))
TypeError: sequence item 4: expected string, memoryview found

**Comment by SeaHOH** [comment]
你需要更新版本

**Comment by SeaHOH** [comment]
刚试过直连也没问题，不知道你之前是怎么回事。
