### ISSUE TITLE
X-Tunnel登录提示  登录失败：status:602，现在521了

### ISSUE THREAD

**Issue by AndyZhaofeng** [XX-net/XX-Net#10838]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  用的最新版

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
提示没有账户，到了明年4月还是多少，具体我忘了。
un 02 09:57:10.262 - [WARNING] Socks4 connect fail, no conn_id

Jun 02 09:57:11.174 - [DEBUG] session not running, try to connect

Jun 02 09:57:11.175 - [WARNING] create conn fail

Jun 02 09:57:11.177 - [DEBUG] x-tunnel no account

Jun 02 09:57:12.179 - [DEBUG] x-tunnel no account

Jun 02 09:57:13.183 - [DEBUG] x-tunnel no account

Jun 02 09:57:14.187 - [DEBUG] session not running, try to connect

Jun 02 09:57:14.187 - [WARNING] Socks4 connect fail, no conn_id

**Comment by SeaHOH** [comment]
#10822
