### ISSUE TITLE
x-tunnel 3.12.0无法登录

### ISSUE THREAD

**Issue by superwjc** [XX-net/XX-Net#10831]
x-tunnel日志，一直重复如下：
un 01 14:57:58.177 - [INFO] xxnet_version:3.12.0

Jun 01 14:57:58.178 - [INFO] server 127.0.0.1:1080 started.

Jun 01 14:57:58.178 - [INFO] Socks5 server listen:127.0.0.1:1080.

Jun 01 14:57:58.575 - [DEBUG] x_tunnel force update info

Jun 01 14:58:04.681 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:06.899 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:12.936 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:15.150 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:21.180 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:23.388 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:29.433 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:58:31.442 - [WARNING] api:/login fail:status:602 t:32

Jun 01 14:59:03.420 - [DEBUG] session not running, try login..

Jun 01 14:59:03.671 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:59:09.699 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:59:16.717 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:59:23.745 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:59:30.849 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:59:37.954 - [WARNING] front retry center.xx-net.net/login

Jun 01 14:59:39.959 - [WARNING] api:/login fail:status:602 t:36

Jun 01 14:59:39.959 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

**Comment by SeaHOH** [comment]
#10822
