### ISSUE TITLE
昨天刚买的流量，今天就一直登录不上去tunnel，显示602，更新版本也下载不下来。

### ISSUE THREAD

**Issue by katyuan88** [XX-net/XX-Net#10833]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by SeaHOH** [comment]
#10822
