### ISSUE TITLE
X-tunnel登录失败：status:602

### ISSUE THREAD

**Issue by greatgary** [XX-net/XX-Net#10848]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by hushicai** [comment]
+1

**Comment by Noodles007** [comment]
+1

**Comment by hushicai** [comment]
重新注册也用不了。。

**Comment by SeaHOH** [comment]
#10822
