### ISSUE TITLE
最近谷歌搜索有时会出现error502错误

### ISSUE THREAD

**Issue by shihuibei** [XX-net/XX-Net#1084]
Property	Value
XX-Net Version	2.0.5
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

Property	Value
Google IP num	338
100th IP handshake(ms)	1700
connected link(帮助)	15,4
scaning ip thread num	50
block stat(帮助)	OK
![1](https://cloud.githubusercontent.com/assets/11963248/9984171/bf3b1f0e-6045-11e5-8c0c-dc7a3ea8abf7.png)

**Comment by EmmieMcDonald** [comment]
同问题，还有的时候谷歌搜索无限载入打不开

**Comment by MargaretCat** [comment]
同问...

**Comment by shinji-ikari** [comment]
最近一直出现502之外,今天还一直ERROR 404
有谁解决了么?

**Comment by MargaretCat** [comment]
有人解决了吗？我重启一下GoAgent有时候能好一下 但是不一会就又出现502了

**Comment by simonasd** [comment]
是偶发性的问题，还是始终无法解决？我遇到过类似的问题，但是是偶发，且多与Google.hk有关。尝试先访问https://www.google.com/ncr，再进行搜索就没有问题了。

**Comment by xxnet** [comment]
最新的版本把google 相关的访问，默认都是用gae的方式，而不是direct，这能比较有效避开一些问题。

在 2015年10月10日 下午4:45，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 恩，正在測試最新版。youtube已經默認選用1080p的解析度了，很流暢。這之前大概空轉了10個小時，IP掃描線程25，目前可用IP約350個，100th延時約260。

**Comment by shinji-ikari** [comment]
是2.5.3测试版还是2.5.1稳定版?
XX-NET自动更新到了2.5.1 还是同样 404
先访问https://www.google.com/ncr ,也试了,之后点刷新直接404.

**Comment by simonasd** [comment]
@shinji-ikari 我测试了253版。换用新版后从零开始扫描IP，似乎会更好一些。还没有遇到过404，不知道和地区网络环境是否有关。

**Comment by shinji-ikari** [comment]
@simonasd  3Q.折腾了半天还是404之后,直接把整个文件夹删掉了.重新下了个2.5.1用,一开始又重新提示不安全连接.弄完之后重新上传部署APP什么的.弄好之后.目前使用正常.还没出现404或者502.

**Comment by simonasd** [comment]
@shinji-ikari 恭喜。虽然不愿意承认，但有时候简单直接的清空重来反倒是最有效的。
