### ISSUE TITLE
"连接尚未建立。"

### ISSUE THREAD

**Issue by Mark486** [XX-net/XX-Net#10840]
IPV6状态正常
IPV6IP数一千多个
就是一直显示“连接尚未建立。”
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
xxnet-version: 3.11.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2000 ipv4:0 ipv6:1402
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 309
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by serverLua** [comment]
worker的h1池和h2池连接数都为0，建议用“高级”-“检查IP”功能来查看IP是否有效，如果有效就重启XX-Net，无效的话删除xx-net安装目录下data/gae_proxy目录中的good_ip.txt并重启xx-net等待重新扫描ip

**Comment by hongkonghot** [comment]
把 tcp/ipv6 前面的勾选去掉，再运行一下启用ipv6，试一下

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

**Comment by mogwaiwxg** [comment]
求助，按照您的这操作之后，显示“你可以尝试 开启IPv6 或 使用X-Tunnel。” IPV6彻底Fail了，请问该如何解决， 谢谢！@SeaHOH

**Comment by SeaHOH** [comment]
@mogwaiwxg 这个操作和 IPv6 Fail 并不相关，你可以尝试切换 teredo 服务器。
