### ISSUE TITLE
3.12.1问题   第一个为使用教育专网的网线连接的诊断页码 第二个为使用无线wifi的诊断结果。一个可以连接ip6另一个不可以，未知原因

### ISSUE THREAD

**Issue by allanharper** [XX-net/XX-Net#10847]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
xxnet-version: 3.12.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:392
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:21 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: trueXX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
xxnet-version: 3.12.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:459 ipv4:0 ipv6:456
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:34 h2:0
scan-ip-thread-num: 10
ip-quality: 318
is-idle: 0
proxy_state: OK
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by allanharper** [comment]
网线ipv6测试
IPv4 域名连接测试 |   | 成功 (0.659s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 失败 (0.218s)
双栈域名连接测试 |   | 成功 (0.653s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.537s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (0.440s) 使用 ipv4
无域名 IPv6 连接测试 |   | 超时 (15.013s)
IPv6 大数据包传输测试 |   | 失败 (0.228s)
测试运营商 DNS 是否接入 IPv6 |   | 成功 (1.582s) 使用 ipv4
查询 IPv4 运营商 |   | 成功 (1.039s) 使用 ipv4 ASN 4538
查询 IPv6 运营商 |   | 失败 (0.258s)
无线ipv6测试
IPv4 域名连接测试	 	
成功 (0.438s) 使用 ipv4
IPv6 域名连接测试	 	
成功 (0.391s) 使用 ipv6
双栈域名连接测试	 	
成功 (2.280s) 使用 ipv4
双栈域名大数据包传输测试	 	
成功 (2.175s) 使用 ipv4
无域名 IPv4 连接测试	 	
成功 (0.446s) 使用 ipv4
无域名 IPv6 连接测试	 	
成功 (0.360s) 使用 ipv6
IPv6 大数据包传输测试	 	
成功 (0.201s) 使用 ipv6
测试运营商 DNS 是否接入 IPv6	 	
成功 (2.176s) 使用 ipv4
查询 IPv4 运营商	 	
成功 (0.523s) 使用 ipv4 ASN 4538
查询 IPv6 运营商	 	
成功 (0.212s) 使用 ipv6 ASN 23910

**Comment by SeaHOH** [comment]
教育网如果有 IPv6 我建议你禁用 teredo 隧道

**Comment by allanharper** [comment]
谢谢。目前问题基本解决，忘记给予xxnet管理员权限。现在正常。。。。。。再拜
