### ISSUE TITLE
IPhone Twitter 客户端无法链接服务器

### ISSUE THREAD

**Issue by cicite** [XX-net/XX-Net#10850]
如题，在局域网中，使用IPhone的youtube客户端是正常的，但是Twitter连不上。

**Comment by SeaHOH** [comment]
不保证独立客户端能正常使用，浏览器是没问题的。

**Comment by cicite** [comment]
理解，客户端有其特殊协议。已经很不错。

**Comment by untitled2014** [comment]
兄弟咋设置的iPhone啊

**Comment by serverLua** [comment]
电脑运行xx-net，开启远程访问，然后自己配置静态IP，手机代理设置成这个IP就行了

**Comment by cicite** [comment]
在iPhone打开safari至8085，然后download ca安装证书，然后在通用关于本机将证书设为完全信任。最后将Wi-Fi加入代理设置。

**Comment by carlchan99** [comment]
我用twitter官方客户端也无法使用，是用第三方--Tweetbot（软件得付费10多元）。

**Comment by cicite** [comment]
第三方软件不太敢用。btw在iphone和ipad端用浏览器也登陆不了twitter，不知道为什么。

**Comment by SeaHOH** [comment]
@cicite 把登录时日志的日志发来看看

**Comment by cicite** [comment]
@SeaHOH  我刚才成功的在手机上用浏览器登陆twitter了。所以前面的描述是错误的，抱歉。
twitter的客户端确实有问题存在。请见log，现在浏览器能上已经不错了，功德无量！

log是linux format, 在windows最好用sublime 打开。
[twitterclient.log](https://github.com/XX-net/XX-Net/files/2079195/twitterclient.log)

**Comment by SeaHOH** [comment]
App 真的是无能为力

**Comment by cicite** [comment]
完全同意！特别理解。：）
