### ISSUE TITLE
紧急！！！3.12.1最新版的X-TUNNEL不能登录，报错

### ISSUE THREAD

**Issue by iTreeBear** [XX-net/XX-Net#10859]
3.12.1 X-TUNNEL不能登录，报错，日志如下：
Jun 03 21:46:22.298 - [INFO] server 127.0.0.1:1080 started.
Jun 03 21:46:22.298 - [INFO] Socks5 server listen:127.0.0.1:1080.
Jun 03 21:46:35.976 - [DEBUG] x-tunnel web_control 127.0.0.1:52150 POST /login
Jun 03 21:46:36.528 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:39.247 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:40.888 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:43.203 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:44.502 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:45.970 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:47.284 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:49.614 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:50.925 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:52.239 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:53.568 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:55.897 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:57.850 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:46:59.195 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:47:00.509 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:47:02.868 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:47:04.196 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:47:05.510 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:47:06.822 - [WARNING] front retry center.xx-net.net/login
Jun 03 21:47:08.839 - [WARNING] api:/login fail:status:602 t:32

**Comment by xiaoyaooo** [comment]
好像是认证服务器出问题了吧，不光新版登陆不了
