### ISSUE TITLE
XX.NET / X-Tunnel 无法使用，登陆失败，status:602

### ISSUE THREAD

**Issue by scaummb** [XX-net/XX-Net#10857]
1. use the latest version software,cannot connect the server....

2. X-Tunnel log:
Jun 03 17:53:27.431 - [INFO] xxnet_version:3.12.1

Jun 03 17:53:27.433 - [INFO] server 127.0.0.1:1080 started.

Jun 03 17:53:27.433 - [INFO] Socks5 server listen:127.0.0.1:1080.

Jun 03 17:53:34.286 - [DEBUG] x-tunnel web_control 127.0.0.1:51098 POST /login

Jun 03 17:53:36.974 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:38.331 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:40.679 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:42.043 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:43.406 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:44.770 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:47.124 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:48.479 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:49.831 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:51.186 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:53.537 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:55.033 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:56.394 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:53:57.740 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:54:04.786 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:54:06.787 - [WARNING] api:/login fail:status:602 t:32
---------------------------------------------

3. CloudflareFront Log

Jun 03 17:53:27.313 - [INFO] SSL use version:TLSv1_2

Jun 03 17:53:27.314 - [INFO] OpenSSL support alpn

Jun 03 17:53:27.315 - [INFO] load ip range file:D:\DownloadFiles\XX-Net-3.12.1\code\default\x_tunnel\local\cloudflare_front\ip_range.txt

Jun 03 17:53:27.317 - [INFO] load ip_list num:99, target num:99

Jun 03 17:53:28.480 - [INFO] load D:\DownloadFiles\XX-Net-3.12.1\data\x_tunnel\cloudflare_domains.json success

Jun 03 17:53:28.488 - [INFO] updated cloudflare front domains from github.

Jun 03 17:53:39.555 - [DEBUG] report_connect_fail:190.93.247.123

Jun 03 17:53:39.556 - [DEBUG] connect 190.93.247.123 fail:error('certificate is none, sni:tenniscahul.com',)

Jun 03 17:53:46.840 - [DEBUG] report_connect_fail:104.19.128.160

Jun 03 17:53:46.841 - [DEBUG] connect 104.19.128.160 fail:error('certificate is none, sni:enteha.net',)

Jun 03 17:53:54.211 - [DEBUG] report_connect_fail:141.101.114.208

Jun 03 17:53:54.211 - [DEBUG] connect 141.101.114.208 fail:error('certificate is none, sni:naaktesexivrouwen.tk',)

Jun 03 17:54:01.574 - [DEBUG] report_connect_fail:104.16.172.76

Jun 03 17:54:01.574 - [DEBUG] connect 104.16.172.76 fail:error('certificate is none, sni:cherrypimpsmodels.com',)

Jun 03 17:54:08.854 - [DEBUG] report_connect_fail:190.93.244.171

Jun 03 17:54:08.855 - [DEBUG] connect 190.93.244.171 fail:error('certificate is none, sni:gotoworld.tk',)

Jun 03 17:54:16.132 - [DEBUG] report_connect_fail:104.16.55.95

Jun 03 17:54:16.132 - [DEBUG] connect 104.16.55.95 fail:error('certificate is none, sni:cnk8081toloac.ga',)

Jun 03 17:54:23.512 - [DEBUG] report_connect_fail:198.41.221.229

Jun 03 17:54:23.513 - [DEBUG] connect 198.41.221.229 fail:error('certificate is none, sni:nationalsfanaticsjersey.com',)

Jun 03 17:54:30.984 - [DEBUG] report_connect_fail:104.18.54.33

Jun 03 17:54:30.984 - [DEBUG] connect 104.18.54.33 fail:error('certificate is none, sni:growbitonline.com',)

Jun 03 17:54:34.291 - [DEBUG] create ssl timeout fail.

Jun 03 17:54:38.346 - [DEBUG] report_connect_fail:190.93.246.98

Jun 03 17:54:38.346 - [DEBUG] connect 190.93.246.98 fail:error('certificate is none, sni:3idarchitecture.com.au',)
---------------------------------------------------

4. CloudfrontFront Log
Jun 03 17:53:27.347 - [INFO] SSL use version:TLSv1_2

Jun 03 17:53:27.357 - [INFO] OpenSSL support alpn

Jun 03 17:53:27.358 - [INFO] load ip range file:D:\DownloadFiles\XX-Net-3.12.1\code\default\x_tunnel\local\cloudfront_front\ip_range.txt

Jun 03 17:53:27.360 - [INFO] load ip_list num:100, target num:100

Jun 03 17:53:39.685 - [DEBUG] report_connect_fail:52.85.76.223

Jun 03 17:53:39.685 - [DEBUG] connect 52.85.76.223 fail:error(' certificate is none, sni:www.stack-sonar.com',)

Jun 03 17:53:47.084 - [DEBUG] report_connect_fail:13.32.201.11

Jun 03 17:53:47.084 - [DEBUG] connect 13.32.201.11 fail:error(' certificate is none, sni:d3cbihxaqsuq0s.cloudfront.net',)

Jun 03 17:53:54.445 - [DEBUG] report_connect_fail:52.222.213.62

Jun 03 17:53:54.445 - [DEBUG] connect 52.222.213.62 fail:error(' certificate is none, sni:sidecar.gitter.im',)

Jun 03 17:54:01.773 - [DEBUG] report_connect_fail:52.85.186.202

Jun 03 17:54:01.773 - [DEBUG] connect 52.85.186.202 fail:error(' certificate is none, sni:dpstvy7p9whsy.cloudfront.net',)

Jun 03 17:54:09.224 - [DEBUG] report_connect_fail:52.84.98.224

Jun 03 17:54:09.225 - [DEBUG] connect 52.84.98.224 fail:error(' certificate is none, sni:screenshots.en.sftcdn.net',)

Jun 03 17:54:16.688 - [DEBUG] report_connect_fail:54.182.3.236

Jun 03 17:54:16.688 - [DEBUG] connect 54.182.3.236 fail:error(' certificate is none, sni:tap-secure.rubiconproject.com',)

Jun 03 17:54:24.138 - [DEBUG] report_connect_fail:54.239.168.30

Jun 03 17:54:24.138 - [DEBUG] connect 54.239.168.30 fail:error(' certificate is none, sni:www.amazon.co.jp',)

Jun 03 17:54:31.591 - [DEBUG] report_connect_fail:54.230.53.209

Jun 03 17:54:31.592 - [DEBUG] connect 54.230.53.209 fail:error(' certificate is none, sni:dsms0mj1bbhn4.cloudfront.net',)

Jun 03 17:54:34.294 - [DEBUG] create ssl timeout fail.

Jun 03 17:54:40.082 - [DEBUG] report_connect_fail:52.85.205.250

Jun 03 17:54:40.083 - [DEBUG] connect 52.85.205.250 fail:error(' certificate is none, sni:assets.bounceexchange.com',)

----------------------------------
5. TLS-RelayFront Log
Jun 03 17:53:27.385 - [INFO] SSL use version:TLSv1_2

Jun 03 17:53:27.386 - [INFO] OpenSSL support alpn

Jun 03 17:53:35.290 - [WARNING] not enough ip

Jun 03 17:53:46.293 - [WARNING] not enough ip

Jun 03 17:53:57.295 - [WARNING] not enough ip

Jun 03 17:54:08.297 - [WARNING] not enough ip

Jun 03 17:54:19.299 - [WARNING] not enough ip

Jun 03 17:54:30.301 - [WARNING] not enough ip

Jun 03 17:54:34.291 - [DEBUG] create ssl timeout fail.

--------------------------------------
6. HerokuFront Log
Jun 03 17:53:27.413 - [INFO] SSL use version:TLSv1_2

Jun 03 17:53:27.414 - [INFO] OpenSSL support alpn

Jun 03 17:53:27.415 - [INFO] load ip_list num:75, target num:75

-----------------------------------------
7. 被逼无奈，所以正在用GAEProxy ，，，

**Comment by SeaHOH** [comment]
#10822 
我也没法，等 xxnet 处理。

**Comment by jessicapd** [comment]
brokertunnel也无法建，ping不通。因为是电信进来又加了路由器......郁闷了
