### ISSUE TITLE
XX-Net 只能使用系统代理，不能使用自动切换和proxy

### ISSUE THREAD

**Issue by step10900** [XX-net/XX-Net#10858]
![image](https://user-images.githubusercontent.com/13678439/40885852-f41e3b00-6760-11e8-941e-eaf4172320e8.png)win10  XX-Net 3.11.15 ,只能使用系统代理，而使用自动切换时，不能代理，shi选着proxy选项也不能代理。为什么?谢谢
![image](https://user-images.githubusercontent.com/13678439/40885864-1fcd8792-6761-11e8-8614-26963bb13d3f.png)

**Comment by SeaHOH** [comment]
建议你更新配置，位置在 SwitchyOmega 目录，wiki 里有写。

**Comment by step10900** [comment]
谢谢，已解决

SeaHOH <notifications@github.com> 于2018年6月3日周日 下午8:48写道：
