### ISSUE TITLE
3.11.15 x-tunnel 登录失败：status:602

### ISSUE THREAD

**Issue by bamboo1117** [XX-net/XX-Net#10855]
Jun 03 15:57:28.003 - [INFO] xxnet_version:3.11.15
Jun 03 15:57:28.006 - [INFO] server 127.0.0.1:1080 started.
Jun 03 15:57:28.006 - [INFO] Socks5 server listen:127.0.0.1:1080.
Jun 03 15:57:43.578 - [DEBUG] x-tunnel web_control 127.0.0.1:60261 POST /login
Jun 03 15:57:48.580 - [WARNING] get_front fail
Jun 03 15:57:54.581 - [WARNING] get_front fail
Jun 03 15:58:00.581 - [WARNING] get_front fail
Jun 03 15:58:12.499 - [DEBUG] x-tunnel web_control 127.0.0.1:60419 POST /login
Jun 03 15:58:14.405 - [WARNING] api:/login fail:status:521 t:30
Jun 03 15:58:20.120 - [WARNING] get_front fail
Jun 03 15:58:26.120 - [WARNING] get_front fail
Jun 03 15:58:32.121 - [WARNING] get_front fail
Jun 03 15:58:38.121 - [WARNING] get_front fail
Jun 03 15:58:44.121 - [WARNING] get_front fail
Jun 03 15:58:45.122 - [WARNING] api:/login fail:status:602 t:32
Jun 03 15:59:47.734 - [DEBUG] x-tunnel web_control 127.0.0.1:60262 POST /login
Jun 03 15:59:54.050 - [WARNING] get_front fail
Jun 03 16:00:00.051 - [WARNING] get_front fail
Jun 03 16:00:06.051 - [WARNING] get_front fail
Jun 03 16:00:12.051 - [WARNING] get_front fail
Jun 03 16:00:18.052 - [WARNING] get_front fail
Jun 03 16:00:19.052 - [WARNING] api:/login fail:status:602 t:31

**Comment by SeaHOH** [comment]
#10822
