### ISSUE TITLE
3.12.1 X-Tunnel 失败

### ISSUE THREAD

**Issue by 23Ben** [XX-net/XX-Net#10856]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  3.12.1
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
gae正常，X-Tunnel连不上

Jun 03 16:55:16.241 - [INFO] xxnet_version:3.12.1

Jun 03 16:55:16.241 - [INFO] server 127.0.0.1:1080 started.

Jun 03 16:55:16.241 - [INFO] Socks5 server listen:127.0.0.1:1080.

Jun 03 16:55:16.804 - [DEBUG] session not running, try login..

Jun 03 16:55:20.092 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:21.686 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:24.192 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:25.605 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:26.946 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:28.289 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:31.541 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:33.688 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:35.784 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:38.868 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:40.448 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:42.027 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:45.098 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:46.671 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:48.784 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:50.786 - [WARNING] api:/login fail:status:602 t:33

Jun 03 16:55:50.786 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

Jun 03 16:55:50.792 - [DEBUG] x_tunnel force update info

Jun 03 16:55:51.383 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:51.787 - [DEBUG] session not running, try login..

Jun 03 16:55:52.244 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:53.489 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:53.586 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:54.930 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:55.577 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:57.015 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:58.657 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:55:59.995 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:00.087 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:01.417 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:02.077 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:02.996 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:04.430 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:05.079 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:06.508 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:07.846 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:08.173 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:09.628 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:09.989 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:11.882 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:12.564 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:13.914 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:16.234 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:18.983 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:19.304 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:21.330 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:21.385 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:22.882 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:23.483 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:24.883 - [WARNING] api:/login fail:status:602 t:34

Jun 03 16:56:25.685 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:26.872 - [DEBUG] x_tunnel force update info

Jun 03 16:56:27.687 - [WARNING] api:/login fail:status:602 t:35

Jun 03 16:56:27.687 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

Jun 03 16:56:27.954 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:28.687 - [DEBUG] session not running, try login..

Jun 03 16:56:29.319 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:29.775 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:31.137 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:31.400 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:33.240 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:34.480 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:35.817 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:35.828 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:37.173 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:37.989 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:39.237 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:39.335 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:41.682 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:42.329 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:43.826 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:43.877 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:45.244 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:46.945 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:47.557 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:49.902 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:50.039 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:51.383 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:52.909 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:53.400 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:54.902 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:54.994 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:56:56.996 - [WARNING] api:/login fail:status:602 t:30

Jun 03 16:56:58.030 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:57:00.101 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:57:02.178 - [WARNING] front retry center.xx-net.net/login

Jun 03 16:57:04.180 - [WARNING] api:/login fail:status:602 t:35

Jun 03 16:57:04.180 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

Jun 03 16:57:05.181 - [DEBUG] session not running, try to connect

Jun 03 17:11:38.315 - [DEBUG] x_tunnel force update info

Jun 03 17:11:38.607 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:11:39.897 - [WARNING] front retry center.xx-net.net/login

Jun 03 17:11:41.474 - [WARNING] front retry center.xx-net.net/login

几个前段的状态。

属性 | 值
-- | --
Score | 356
成功数 | 316
失败数 | 35
工作数 | 51
使用总量 | Up: 0.0 B / Down: 0.0 B

属性 | 值
-- | --
Score | 610
成功数 | 0
失败数 | 0
工作数 | 1
使用总量 | Up: 0.0 B / Down: 0.0 B

属性 | 值
-- | --
Score | 337000
成功数 | 0
失败数 | 0
工作数 | 1
使用总量 | Up: 0.0 B / Down: 0.0 B

属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0 / Down: 0

属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0.0 B / Down: 0.0 B

**Comment by SeaHOH** [comment]
#10822
