### ISSUE TITLE
3.12.1 播放youtube视频依然时不时有停顿，是否可以通过增加配置文件选项解决延时问题？

### ISSUE THREAD

**Issue by cicite** [XX-net/XX-Net#10851]
3.12.1 播放youtube视频依然时不时有停顿，不得不退回3.10.4。
不知道在3.10.4之后有什么机制的改变，是否可以通过增加配置文件选项解决延时问题？

**Comment by SeaHOH** [comment]
修改太多，不好确定。
你可以自己修改 gae_proxy 的 config.py 文件来测试。

**Comment by cicite** [comment]
Ok. Will try!
