### ISSUE TITLE
我得气疯了...IPv6真的这么不省心吗...

### ISSUE THREAD

**Issue by serverLua** [XX-net/XX-Net#10854]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

![image](https://user-images.githubusercontent.com/25174488/40884139-0578c41c-6741-11e8-952c-6f16ef6bfb07.png)

刚启动时还好,2~3秒后就炸了,ipv6显示fail,重启后如上图,unknown是什么鬼

ipconfig内容更让我摸不着头脑
以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv4 地址 . . . . . . . . . . . . : 192.168.100.102
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.100.1

以太网适配器 蓝牙网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器 本地连接* 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

隧道适配器怎么变成本地连接*10了？

netsh
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.100.102:55167
外部 NAT 映射    : 183.193.142.148:5205

nat居然是symmetric
以前还好好的
状态居然是qualified？？！！
还让不让我活了？！

**Comment by serverLua** [comment]
OMG----又来。。。
[image](https://imgchr.com/i/CTE89x)

**Comment by serverLua** [comment]
OMG----又来了......
[image](https://s1.ax1x.com/2018/06/03/CTE89x.png)

**Comment by serverLua** [comment]
OMG----又来了......
[img](https://s1.ax1x.com/2018/06/03/CTE89x.png)

**Comment by serverLua** [comment]
OMG----又来了......
**:[img](https://s1.ax1x.com/2018/06/03/CTE89x.png)**

**Comment by serverLua** [comment]
OMG......
![img](https://s1.ax1x.com/2018/06/03/CTE89x.png)

**Comment by SeaHOH** [comment]
每次更新都有说明更新内容。
IPv6 现状如此。

**Comment by BBC202** [comment]
我的mac突然打开就上不了，
显示网络无法连接，请检查网络和防火墙设置。

求大神帮忙，我连复制的错误信息都发不出来

**Comment by tmttmd** [comment]
用的长城宽带，总之我用ipv6就是一卡一卡的，看视频是不可能的了，因为会经常断，只能浏览一下网页

**Comment by SeaHOH** [comment]
@BBC202 搜索 mac miredo 相关问题，我没有使用 mac 系统。

**Comment by cloudydayoffice** [comment]
@tmttmd 你是哪里的长城呢？

**Comment by AnyWAT** [comment]
👀羞于启齿的臭大街法则，不保证正常100%，至少不低于90%吧🤣

**Comment by tmttmd** [comment]
@cloudydayoffice 广州的

**Comment by cloudydayoffice** [comment]
我正想换长城··· @tmttmd  前两年用长城还好，最近真的是多事之秋
