### ISSUE TITLE
无法登陆谷歌，SwitchOmega显示2个资源未加载

### ISSUE THREAD

**Issue by SimPin** [XX-net/XX-Net#10860]
无法登陆谷歌，SwitchOmega显示2个资源未加载，分别为：*.google.com 和 *.gstatic.com。
其他网站访问正常。
请问大家是怎么回事？

**Comment by SeaHOH** [comment]
SwitchyOmega 目录下有配置好的设置，可以导入使用。

**Comment by SimPin** [comment]
已导入并选择“GAE-Proxy自动切换“，还是无法登陆谷歌，请问如何解决。

**Comment by AnyWAT** [comment]
👀将未加载资源添加到走GAE

**Comment by SimPin** [comment]
@AnyWAT 你好，添加到GAE后还是不行。谷歌登陆界面那，输入账号点下一步没反应。

**Comment by SeaHOH** [comment]
状态信息
点下一步时的日志

**Comment by SimPin** [comment]
@SeaHOH 请问是这个吗
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
xxnet-version: 3.12.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:31
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:10 h2:0
scan-ip-thread-num: 100
ip-quality: 1389
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
还有点下一步没反应时的日志

**Comment by SimPin** [comment]
@SeaHOH 是这个吗？
Jun 04 22:35:54.556 - [DEBUG] create_ssl update ip:2a00:1298:8010::d time:1312 h2:0 sni:zhoumeng10081.appspot.com, host:zhoumeng10081.appspot.com

Jun 04 22:35:55.540 - [DEBUG] report_connect_fail:2001:8002:e21:e101::10

Jun 04 22:35:55.540 - [DEBUG] connect 2001:8002:e21:e101::10 fail:error("conn fail, sni:xx-net-188801.appspot.com, top:xx-net-188801.appspot.com e:timeout('timed out',)",)

Jun 04 22:35:56.071 - [DEBUG] report_connect_fail:2001:13d2:801::12

Jun 04 22:35:56.071 - [DEBUG] connect 2001:13d2:801::12 fail:error("conn fail, sni:xxnet-20171610.appspot.com, top:xxnet-20171610.appspot.com e:timeout('timed out',)",)

Jun 04 22:35:58.977 - [INFO] scan_ip add ip:2620:11a:a012:1::12 time:453 h2:0

Jun 04 22:35:58.977 - [INFO] remove_slowest_ip:2001:13d2:801::12 handshake_time:3060, fails:2

Jun 04 22:36:00.148 - [DEBUG] create_ssl update ip:2404:4408:2:5100::f time:9607 h2:0 sni:bypassgfw2-1374.appspot.com, host:bypassgfw2-1374.appspot.com

Jun 04 22:36:00.335 - [DEBUG] report_connect_fail:2804:d40:82:f001::c

Jun 04 22:36:00.335 - [DEBUG] connect 2804:d40:82:f001::c fail:error("conn fail, sni:taste-concern-beer.com, top: e:timeout('timed out',)",)

Jun 04 22:36:02.085 - [WARNING] task POST None /_gh/ timeout

Jun 04 22:36:02.085 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 22:36:02.085 - [WARNING] gae_exception:'600:fetch gae fail' https://r17---sn-ni57dn7s.gvt1.com/edgedl/widevine-cdm/1.4.8.1008-win-x64.zip?cms_redirect=yes&ip=117.139.221.88&ipbits=0&mm=28&mn=sn-ni57dn7s&ms=nvh&mt=1528122810&mv=m&pl=19&shardbypass=yes

Jun 04 22:36:02.710 - [WARNING] 2a05:fdc0:2200::11 h1_request:Exception('time out',) inactive_time:91 task.timeout:20

Jun 04 22:36:02.710 - [WARNING] 2a05:fdc0:2200::11 trace: 0:connect, 3046:init, 1031:request, 1781:Res, 0:head, 514:head end, 0:request, 1688:Res, 0:request, 1139:Res, 13528:request, 1139:Res, 108:request, 8561:Res, 62470:request,:20713, processed:5, transfered:527768, sni:xxnet-ian01.appspot.com

Jun 04 22:36:02.710 - [WARNING] retry_task_cb: POST None/_gh/

Jun 04 22:36:02.710 - [WARNING] POST None/_gh/ response_fail:retry timeout:20

Jun 04 22:36:02.710 - [DEBUG] 2a05:fdc0:2200::11 worker close:down fail

Jun 04 22:36:07.381 - [DEBUG] report_connect_fail:2620:11a:a012:1::12

Jun 04 22:36:07.381 - [DEBUG] connect 2620:11a:a012:1::12 fail:error("conn fail, sni:door.drink.org, top: e:timeout('timed out',)",)

Jun 04 22:36:08.458 - [DEBUG] GAE GET https://accounts.google.com/ServiceLogin?hl=zh-CN&passive=true&continue=https%3A%2F%2Fwww.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin from:127.0.0.1:54047

Jun 04 22:36:10.208 - [INFO] gae_handler send to browser return error(10053, '') 'https://accounts.google.com/ServiceLogin?hl=zh-CN&passive=true&continue=https%3A%2F%2Fwww.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin', len:334204, sended:108618

Jun 04 22:36:10.614 - [DEBUG] report_connect_fail:2804:214:800f:a::e

Jun 04 22:36:10.614 - [DEBUG] connect 2804:214:800f:a::e fail:error("conn fail, sni:xxnet-wich1.appspot.com, top:xxnet-wich1.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:12.317 - [DEBUG] create_ssl update ip:2404:4408:2:5100::12 time:1780 h2:0 sni:makelshadow32e70fd.appspot.com, host:makelshadow32e70fd.appspot.com

Jun 04 22:36:14.004 - [DEBUG] report_connect_fail:2804:d40:85:6002::d

Jun 04 22:36:14.004 - [DEBUG] connect 2804:d40:85:6002::d fail:error("conn fail, sni:my-project-9-1470318330078.appspot.com, top:my-project-9-1470318330078.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:14.426 - [DEBUG] report_connect_fail:2804:238:2:7::11

Jun 04 22:36:14.426 - [DEBUG] connect 2804:238:2:7::11 fail:error("conn fail, sni:while-responsibility-phase.us, top: e:timeout('timed out',)",)

Jun 04 22:36:14.520 - [DEBUG] report_connect_fail:2001:16a0:202:106::c

Jun 04 22:36:14.520 - [DEBUG] connect 2001:16a0:202:106::c fail:error("conn fail, sni:fzongxxx.appspot.com, top:fzongxxx.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:15.035 - [DEBUG] report_connect_fail:2804:214:800f:1::f

Jun 04 22:36:15.035 - [DEBUG] connect 2804:214:800f:1::f fail:error("conn fail, sni:xxnet-dbd07.appspot.com, top:xxnet-dbd07.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:15.207 - [INFO] GAE t:6749 s:334208 GET https://accounts.google.com/ServiceLogin?hl=zh-CN&passive=true&continue=https%3A%2F%2Fwww.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin 0:start_request,0:get_task(6),0:get_worker(0):2a00:1298:8010::e,0:h1_req,0:h1_req_sended,1062:response_begin,0:h1_get_head,0:get_response,5686:h1_finish[SP:49614],:0

Jun 04 22:36:16.067 - [DEBUG] report_connect_fail:2620:11a:a018:2::c

Jun 04 22:36:16.067 - [DEBUG] connect 2620:11a:a018:2::c fail:error("conn fail, sni:advance-casing-181213.appspot.com, top:advance-casing-181213.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:16.316 - [DEBUG] GAE GET https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-53985811×tamp=1528122976289 from:127.0.0.1:54215

Jun 04 22:36:16.582 - [DEBUG] report_connect_fail:2804:7f2:1000:cade::c

Jun 04 22:36:16.582 - [DEBUG] connect 2804:7f2:1000:cade::c fail:error("conn fail, sni:xxnet-h2.appspot.com, top:xxnet-h2.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:16.816 - [INFO] GAE t:500 s:1351 GET https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-53985811×tamp=1528122976289 0:start_request,0:get_task(7),0:get_worker(0):2a00:1298:8010::e,0:h1_req,0:h1_req_sended,500:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:3536],:0

Jun 04 22:36:17.660 - [DEBUG] create_ssl update ip:2001:13d2:802::c time:9186 h2:0 sni:xxnet-idforxxnet-8.appspot.com, host:xxnet-idforxxnet-8.appspot.com

Jun 04 22:36:18.081 - [DEBUG] create_ssl update ip:2404:4408:5:5101::f time:1765 h2:0 sni:xxnet-87.appspot.com, host:xxnet-87.appspot.com

Jun 04 22:36:19.113 - [DEBUG] create_ssl update ip:2404:4408:5:5101::d time:1766 h2:0 sni:xxnet-190210.appspot.com, host:xxnet-190210.appspot.com

Jun 04 22:36:21.190 - [DEBUG] report_connect_fail:2001:d08:11:20a::10

Jun 04 22:36:21.190 - [DEBUG] connect 2001:d08:11:20a::10 fail:error('certificate is none, sni:my-project-xxnet4-183914.appspot.com',)

Jun 04 22:36:21.269 - [DEBUG] report_connect_fail:2804:214:800f:1::13

Jun 04 22:36:21.269 - [DEBUG] connect 2804:214:800f:1::13 fail:error('certificate is none, sni:xxnet-iceliquid26.appspot.com',)

Jun 04 22:36:21.471 - [DEBUG] report_connect_fail:2804:d40:8c:7002::c

Jun 04 22:36:21.471 - [DEBUG] connect 2804:d40:8c:7002::c fail:error("conn fail, sni:backspirit.com, top: e:timeout('timed out',)",)

Jun 04 22:36:21.565 - [DEBUG] report_connect_fail:2804:7f2:1000:cace::f

Jun 04 22:36:21.565 - [DEBUG] connect 2804:7f2:1000:cace::f fail:error("conn fail, sni:shounan1984.appspot.com, top:shounan1984.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:21.847 - [DEBUG] report_connect_fail:2001:8002:e21:ef03::c

Jun 04 22:36:21.847 - [DEBUG] connect 2001:8002:e21:ef03::c fail:error("conn fail, sni:appid-2-192801.appspot.com, top:appid-2-192801.appspot.com e:timeout('timed out',)",)

Jun 04 22:36:22.081 - [DEBUG] report_connect_fail:2001:f90:9:6::e

Jun 04 22:36:22.081 - [DEBUG] connect 2001:f90:9:6::e fail:error("conn fail, sni:xxnet-61.appspot.com, top:xxnet-61.appspot.com e:timeout('timed out',)",

**Comment by SeaHOH** [comment]
似乎不是代理的问题，你把 google 相关 cookies 删除后再试试。
再不行就新建个 data/gae_proxy/config.json，内容如下：
```json
{
    "hosts_direct": [
        "play.google.com",
        "scholar.google.com",
        "scholar.google.com.hk",
        "appengine.google.com",
        "accounts.google.com"
    ],
    "hosts_gae": [
        "mail.google.com"
    ]
}
```
如果这还不行，建议你换 Chrome。

**Comment by SimPin** [comment]
@SeaHOH 换了 Chrome，终于可以登陆谷歌了。谢谢！
