### ISSUE TITLE
TIM無法通過代理登陸

### ISSUE THREAD

**Issue by TIMcatnotlogin** [XX-net/XX-Net#10864]
公司限制了部分程序連接外網，包括QQ，TIM。

之前用 X-Tunnel 通過 SOCKS5 代理可以登陸，現在 X-Tunnel 用不了，自然就無法登陸。

試著 TIM登陸設置裡設置成HTTP代理，填寫了127.0.0.1 端口8085~8087，點測試後顯示成功連接代理，
可是登陸時就是無法登陸，錯誤代碼1000。

請問有是哪一個步驟操作錯誤了？
還是還有什麼要點？

懇請幫幫忙。謝謝！

**Comment by TIMcatnotlogin** [comment]
TIM 代理 登陸

**Comment by TIMcatnotlogin** [comment]
TIM 代理 登陸

**Comment by AnyWAT** [comment]
👀現在 X-Tunnel 可用了

**Comment by TIMcatnotlogin** [comment]
是可以了，TIM也連上了，但一會就斷線，重新登陸也不是每次都行。
