### ISSUE TITLE
X-Tunnel能正常使用，但是不能登录？

### ISSUE THREAD

**Issue by 10lumiya10** [XX-net/XX-Net#10866]
今天开机发现X-Tunnel在工作，以为已经解决问题了，但是看了下日志，发现还是登录不了，这是什么操作？
![image](https://user-images.githubusercontent.com/36228639/40897602-955f0dfe-67ee-11e8-83ac-72ec54d0ed93.png)

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/issues/10868
