### ISSUE TITLE
Tampermonkey導出備份到google drive出錯

### ISSUE THREAD

**Issue by gggccc44** [XX-net/XX-Net#10869]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  幾個版本都一樣

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
當然啊

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

大概出錯的內容

Jun 04 14:06:03.419 - [WARNING] task POST None /_gh/ timeout

Jun 04 14:06:03.419 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 14:06:03.419 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart

Jun 04 14:06:03.419 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipartgae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipartgae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"

Jun 04 14:06:03.420 - [WARNING] GAE POST https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart request fail:"600:gae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipartgae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipartgae_exception:'600:fetch gae fail' https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"

Jun 04 14:06:03.424 - [WARNING] send response fail 

下載是沒問題的，其實這問題老早就有，不過我一般換梯子解決，今天搜了下貌似沒人反饋就說下

備份文件是壓縮為zip的沒超過10M

剛又試了幾次，貌似有時候能傳上去但是還是返回錯誤信息，不知道什麼鬼，www.googleapis.com改直連也一樣

**Comment by SeaHOH** [comment]
@xxnet 可能是超时时间不够，建议包含上传数据时增加超时时间。

**Comment by SeaHOH** [comment]
xxnet 正在处理 X-Tunnel 可能忙不过来。
你用下面这个修改试试，能否成功上传。

修改 gae_proxy/local/gae_handler.py 文件，
找到 request_gae_proxy 函数的 `for timeout in timeouts:` 位置
在前面增加两行：
```py
    if body:
        timeouts = [timeout + 10 for timeout in timeouts]
```

这个主要是不知道你用的什么版本，反正这么修改就可以，如果 +10 不行，改成 +20 再试试。

**Comment by xxnet** [comment]
网站上传经常用了很多技巧，难以通用解决，建议用x-tunnel
目前x-tunnel基本恢复了

**Comment by gggccc44** [comment]
@SeaHOH 好的我試試

我也是偶然想起就反饋下，有其他梯子可以解決

**Comment by SeaHOH** [comment]
这个修改已加入 3.12.2，可以更新试试。
