### ISSUE TITLE
这是什么情况？X-Tunnel正常应该7月份到期，还有160多G

### ISSUE THREAD

**Issue by superabe** [XX-net/XX-Net#10867]
<img width="726" alt="screen shot 2018-06-04 at 1 18 06 pm" src="https://user-images.githubusercontent.com/3632587/40899575-431ee558-67fa-11e8-8ea7-475955f83e61.png">

**Comment by iamlbk** [comment]
同问, 我记得应该是12月才过期, 应该还有八九百G, 现在只剩91M了...

**Comment by superwjc** [comment]
同问，5月30日$15购买1年的1200G套餐，6月1日下午开始无法登录，现在刚刚打开，只显示100M
<img width="738" alt="1" src="https://user-images.githubusercontent.com/39140710/40902768-beaa60e6-6807-11e8-90de-884c978b6f81.png">
<img width="740" alt="2" src="https://user-images.githubusercontent.com/39140710/40902807-dd4d869a-6807-11e8-8a2e-dbd88c3a295b.png">

**Comment by xinl22** [comment]
我也是，5.21开的三个月的，现在显示6.28就到期了

2018-May-20 18:42:14 | action:charge; amount:4.5;

到期时间 | 剩余流量
-- | --
2018-06-28 | 289.52 GB [转让]

**Comment by SeaHOH** [comment]
#10868

**Comment by decemer** [comment]
不稳定就不要收费啦
