### ISSUE TITLE
3.11.10无法登陆google和gmail等

### ISSUE THREAD

**Issue by dayuzheng** [XX-net/XX-Net#10879]
3.11.10不能使用gmail
试过在config.json中添加命令，结果失败
然后在smart router规则中的直连添加accounts.google.com和.youtube.com.开启模块后
使用google和搜索没有问题，点击gmail后跳到accounts.google.com就打不开网页

请问一下这是为什么？

谢谢

**Comment by allanharper** [comment]
请xxnet使用管理员模式启动，我的问题是这样解决的/

**Comment by dayuzheng** [comment]
xxnet是vbs文件，请问一下该怎么使用管理员模式启动？我右键没有找到有这个选项。
谢谢

**Comment by allanharper** [comment]
xxnet桌面图标就可以

**Comment by SeaHOH** [comment]
建议升级

**Comment by dayuzheng** [comment]
检查下来提示是最新版，不过我看公告是到3.12,手动下载升级吗？

**Comment by SeaHOH** [comment]
手动可以，升级页面也有高级选项可以直接升级。

**Comment by dayuzheng** [comment]
已升级到最新版，一样的情况，哎。
不过还是谢谢楼上了。

**Comment by SeaHOH** [comment]
#10860 有个现成的 config.json

**Comment by dayuzheng** [comment]
还是不行。不过后来我换成了chrome就可以登录了。原先用的是opera浏览器。
换成chrome后，导入omega配置，发现和原先opera不同的地方是chrome我用的是8087端口，而原先opera我用的是8086端口。不知道和这个有没有关系。
不过现在使用chrome后又出现问题了。就是输入用户名和密码后gmail说我没启用cookie无法登陆，可是我明明是启用cookie的，请问下这是怎么回事？

谢谢

**Comment by SeaHOH** [comment]
把 也换成直连试试
```json
{
    "hosts_direct": [
        "play.google.com",
        "scholar.google.com",
        "scholar.google.com.hk",
        "appengine.google.com",
        "accounts.google.com",
        "mail.google.com"
    ],
    "hosts_gae": []
}
```

**Comment by dayuzheng** [comment]
奇怪了，还是不行。
输入密码后就跳到这个界面了。但是我的cookie确实是开着的。
![opera snapshot_2018-06-06_201148_accounts google com](https://user-images.githubusercontent.com/33861757/41037434-ec45b446-69c5-11e8-9142-8c96445f860a.png)

**Comment by SeaHOH** [comment]
我专门切到 IPv6，反反复复登录退出，只有一次登录 gmail 失败，
而且也不是提示 cookies，是提示出现错误。
就是 3.12.1 的默认设置。

**Comment by SeaHOH** [comment]
关闭后仍可回复
