### ISSUE TITLE
为什么我注册tunnel，我的Outlook邮箱被注册使用了，这该怎么办，qq邮箱登录时发生用户名或登录密码错误。

### ISSUE THREAD

**Issue by katyuan88** [XX-net/XX-Net#10878]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by allanharper** [comment]
你自己用注册了呗。。。

**Comment by katyuan88** [comment]
没有，我刚开始用的是qq邮箱注册的，outlook从来没注册过，今天用qq的时候不行，然后重新用outlook注册。显示被注册，搞得一头雾水。

**Comment by katyuan88** [comment]
没有，我刚开始用的是qq邮箱注册的，outlook从来没注册过，今天用qq的时候不行，然后重新用outlook注册。显示被注册，搞得一头雾水。

**Comment by allanharper** [comment]
理论上是的，要不然你outlook被盗了

**Comment by tianyajuechen** [comment]
@allanharper tunnel随便个邮箱就能注册，都不用验证的。

**Comment by SeaHOH** [comment]
用当事邮箱发邮件给 xxnet.dev@gmail.com 要求重置密码。

**Comment by katyuan88** [comment]
好吧。

**Comment by AnyWAT** [comment]
qq邮箱登录时发生用户名或登录密码错误👀貌似服务器不正常了，并非真正用户名或登录密码错误👀

**Comment by katyuan88** [comment]
H好的。

**Comment by no-name2017** [comment]
Outlook不是没被墙吗？这玩意还是不要注册的好
