### ISSUE TITLE
刚买了包年的流量，流量也没了，谷歌也上不去了

### ISSUE THREAD

**Issue by daisy19880411** [XX-net/XX-Net#10877]
2018年05月12日 刚买了一年的流量，（Plan: Yearly, account: daisy19880411@gmail.com, Receipt No: 5218-3932-1590-9892）。但是在tunnel里面看可用的流量，只剩免费赠送的100M的了，而且谷歌也无法访问。这种情况已经持续好几天了，请问是怎么回事呢？

**Comment by JemmyLuck** [comment]
同样问题，不久前购买了包年流量，前几天我不能登录x-tunnel，也上不了google。今天能登录了，但是流量只有送的100m了

**Comment by daisy19880411** [comment]
看来不是我自己的问题 应该系统暂时出bug了 我们耐心等会就好了

**Comment by AndyZhaofeng** [comment]
我在2018-3-13号买的流量，今天显示没了。

**Comment by x8655424** [comment]
同样的问题，前几天刚买的流量也全没了

**Comment by zeitgeist8080** [comment]
308038858@qq.com 1080G 流量消失了

**Comment by reclusegit** [comment]
我也出现这样情况，200多G消失了，麻烦查询下账户状态：recluse.zhang@gmail.com

**Comment by SeaHOH** [comment]
过几天会发公告，到时统一处理。

**Comment by reclusegit** [comment]
已恢复，谢谢。
