### ISSUE TITLE
更新到最新版后 IPV6 又fail了  尚未建立连接

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#10872]
更新到最新版后win10 教育版 IPV6 又fail了 改组建策略也不行了，也禁用了本地连接里的ipv6协议各种方法都试了不行，广州电信校园网
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
是
* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.12.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Logo XX-Net 3.12.1
resize-window
 

# **GAEProxy 日志**
Jun 04 20:50:17.207 - [DEBUG] connect 2a00:1450:4011:1e::11 network fail

Jun 04 20:50:17.723 - [DEBUG] report_connect_fail IPv6 continue_fail_count:548

Jun 04 20:50:17.723 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:17.724 - [DEBUG] connect 2607:f8b0:4002:2e::9 network fail

Jun 04 20:50:18.149 - [DEBUG] report_connect_fail IPv6 continue_fail_count:549

Jun 04 20:50:18.149 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:18.149 - [DEBUG] connect 2607:f8b0:401a:27::c network fail

Jun 04 20:50:18.737 - [DEBUG] report_connect_fail IPv6 continue_fail_count:550

Jun 04 20:50:18.737 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:18.737 - [DEBUG] connect 2607:f8b0:4000:a::22 network fail

Jun 04 20:50:19.292 - [WARNING] task POST None /_gh/ timeout

Jun 04 20:50:19.293 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 20:50:19.293 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Jun 04 20:50:19.294 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Jun 04 20:50:19.294 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chromegae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Jun 04 20:50:19.299 - [WARNING] send response fail

Jun 04 20:50:19.600 - [WARNING] task POST None /_gh/ timeout

Jun 04 20:50:19.601 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 20:50:19.602 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token

Jun 04 20:50:19.602 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token"

Jun 04 20:50:19.603 - [WARNING] GAE POST https://www.googleapis.com/oauth2/v4/token request fail:"600:gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token"

Jun 04 20:50:19.801 - [WARNING] task POST None /_gh/ timeout

Jun 04 20:50:19.801 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 20:50:19.801 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token

Jun 04 20:50:19.801 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token"

Jun 04 20:50:19.801 - [WARNING] GAE POST https://www.googleapis.com/oauth2/v4/token request fail:"600:gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token"

Jun 04 20:50:20.106 - [WARNING] task POST None /_gh/ timeout

Jun 04 20:50:20.106 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 20:50:20.106 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token

Jun 04 20:50:20.106 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token"

Jun 04 20:50:20.106 - [WARNING] GAE POST https://www.googleapis.com/oauth2/v4/token request fail:"600:gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/tokengae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token"

Jun 04 20:50:20.743 - [DEBUG] report_connect_fail IPv6 continue_fail_count:551

Jun 04 20:50:20.743 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:20.744 - [DEBUG] connect 2a00:1450:400a:6::c network fail

Jun 04 20:50:20.756 - [DEBUG] report_connect_fail IPv6 continue_fail_count:552

Jun 04 20:50:20.756 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:20.756 - [DEBUG] connect 2001:16a0:202:10a::11 network fail

Jun 04 20:50:21.258 - [WARNING] network IPv6 fail

Jun 04 20:50:23.085 - [DEBUG] report_connect_fail IPv6 continue_fail_count:553

Jun 04 20:50:23.086 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:23.086 - [DEBUG] connect 2a00:1450:4003:11::d network fail

Jun 04 20:50:23.286 - [DEBUG] report_connect_fail IPv6 continue_fail_count:554

Jun 04 20:50:23.286 - [DEBUG] report_connect_fail network fail

Jun 04 20:50:23.286 - [DEBUG] connect 2604:d600:0:4::13 network fail

Jun 04 20:50:23.962 - [WARNING] task POST None /_gh/ timeout

Jun 04 20:50:23.962 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 04 20:50:23.962 - [WARNING] gae_exception:'600:fetch gae fail' https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumProfileSyncService,counter:3,load_time_ms:211604&json=standard

Jun 04 20:50:23.962 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumProfileSyncService,counter:3,load_time_ms:211604&json=standardgae_exception:'600:fetch gae fail' https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumProfileSyncService,counter:3,load_time_ms:211604&json=standardgae_exception:'600:fetch gae fail' https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumProfileSyncService,counter:3,load_time_ms:211604&json=standard"

Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : teredo2.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified

**Comment by SeaHOH** [comment]
点击切换 teredo 服务器

**Comment by LN-VIVI** [comment]
@SeaHOH   更换了还是不行，
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified


++++++++++UDP connection testing+++++++++

teredo.remlab.net:3544 is accessible
teredo2.remlab.net:3544 is accessible
teredo-debian.remlab.net:3544 is accessible
teredo.ngix.ne.kr:3544 isn't accessible
teredo.trex.fi:3544 is accessible
teredo.autotrans.consulintel.com:3544 isn't accessible
teredo.managemydedi.com:3544 isn't accessible
teredo.ipv6.microsoft.com:3544 is accessible
win10.ipv6.microsoft.com:3544 is accessible
teredo.iks-jena.de:3544 is accessible
win1710.ipv6.microsoft.com:3544 is accessible

++++++++++ping testing+++++++++

teredo.remlab.net 229 ms
teredo2.remlab.net 207 ms
teredo-debian.remlab.net 229 ms
teredo.trex.fi 262 ms
teredo.ipv6.microsoft.com 9999 ms
win10.ipv6.microsoft.com 9999 ms
teredo.iks-jena.de 237 ms
win1710.ipv6.microsoft.com 9999 ms

改了也不行

**Comment by LN-VIVI** [comment]
teredor test result is unknown.

qualified: False
_
<img width="467" alt="3" src="https://user-images.githubusercontent.com/18262731/40920764-1275025c-6840-11e8-99ce-95506e762e7a.png">



_

**Comment by LN-VIVI** [comment]
@ghost大神求助

**Comment by LN-VIVI** [comment]
@pendave 大神求助

**Comment by SeaHOH** [comment]
就在这个页面点击，不要用其它的脚本。

**Comment by LN-VIVI** [comment]
@SeaHOH 不行哇

**Comment by LN-VIVI** [comment]
Starting...
Config servers...
Reset IPv6...
Set IPv6 Tunnel...

**Comment by SeaHOH** [comment]
**切换**

**Comment by LN-VIVI** [comment]
@SeaHOH 没其他办法吗？

**Comment by LN-VIVI** [comment]
@SeaHOH    点了禁用  一直这样没反应 C:\Windows\system32>netsh interface teredo set state disable

**Comment by SeaHOH** [comment]
你到底点没点切换按钮？

**Comment by LN-VIVI** [comment]
@SeaHOH 按啦
@xxnet
@Michael.X

**Comment by LN-VIVI** [comment]
你可以尝试 开启IPv6 或 使用X-Tunnel。
用新版本都扫不到可用IP了
旧版本也用不了

**Comment by LN-VIVI** [comment]
@SeaHOH 我QQ1642319208 求救

**Comment by SeaHOH** [comment]
点击启用，再重启电脑。
重启后如果还没正常，再点击切换。

主要是你先前胡乱操作一通，不然不用重启。

**Comment by LN-VIVI** [comment]
@SeaHOH ，五一前在学校电信网络用XXnet是能用的，后来五一放假在家的时候用的是移动光迁，也能用，网络比学校快，放假后回到学校我有一个多月的时间没用了，而且校园网客户端也重新升级了，我发现迅雷好多东西都下不了了之前校园网客户端没升级前能下好多东西的，前几天想用外网发现用不了，就升级咯，以前用不了的时候我尝试很多方法，也用了tertdo.bat改tertdo服务器，改了都能用，

但是现在用最新版本XX-net怎么也扫不出可用IP,IPV4 IPV6都扫不出来，改了tertdo服务器也不管用，之前一直都是通过改组策略之后再用tertdo.bat改tertdo服务器，都能成功，# 可是现在不管用了，# 我也用过微软 的在自动禁用或重新启用 IPv6 或其组件下载 "XXXXXXXXXXX重新启用 IPv6"     都没有

**Comment by SeaHOH** [comment]
只能给你讲，版本可以随便选，不信你试试。

**Comment by whhxmwhh** [comment]
楼上朋友。您辛苦了。只能怪网络狡猾。
还有就是可以试试完全删除证书然后重新导入证书。
反正我的是ok了

**Comment by LN-VIVI** [comment]
@whhxmwhh     
请问怎么删？

**Comment by AnyWAT** [comment]
CA证书状态(下载) | OK👀删个大头🤣
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by SeaHOH** [comment]
从头到尾都没看见你按照指导处理，尽扯些无关的。
你扯这么多，还不如按我说的做。

**Comment by whhxmwhh** [comment]
可惜有不行。稳定运行3天左右

XX-Net Status:

sys-platform: x86, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.12.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:398
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 43
ip-quality: 625
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by whhxmwhh** [comment]
我是完全删除干净了。

**Comment by SeaHOH** [comment]
不是这个原因，只要你们不重复利用 data 文件夹，就会重新生成新证书。

**Comment by LN-VIVI** [comment]
@SeaHOH 点击切换也不管用啊！所以现在要怎么办？我已经绝望了，不会是网络的问题吧？

**Comment by LN-VIVI** [comment]
@SeaHOH  其他版本也不行啊！我已经搞了好几天，系统问题？

**Comment by LN-VIVI** [comment]
@AnyWAT 
PS C:\Windows\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3137 ipv4:1 ipv6:2054
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by LN-VIVI** [comment]
我现在连X-Tunnel都登陆不了，一登就 602

**Comment by whhxmwhh** [comment]
不是系统的问题。是你的网络环境问题的。
这个真的没办法事情。

**Comment by whhxmwhh** [comment]
我家里的网络，xx可好用了。在单位就一直fail。

**Comment by SeaHOH** [comment]
>teredor test result is unknown.
qualified: False
NAT type: symmetric

这个测试结果，加上切换后也始终连不上，说明你的网络环境如此，没法使用 teredo。

可以再最后尝试下微软服务器
`netsh interface teredo set state type=enterpriseclient servername=win10.ipv6.microsoft.com.`

**Comment by LN-VIVI** [comment]
@SeaHOH 用手机开热点
netsh int ipv6 show teredo出现
qualified: True
NAT type: restricted

**Comment by LN-VIVI** [comment]
eredo 参数
--------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo2.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by SeaHOH** [comment]
怎么又出现组策略了，玩不来建议不要设置组策略。

手机热点能连上说明系统没问题，上面让你换微软试试，试过没。

**Comment by LN-VIVI** [comment]
@SeaHOH 不行

**Comment by LN-VIVI** [comment]
@SeaHOH   netsh interface teredo set state type=enterpriseclient servername=win10.ipv6.microsoft.com
用这个没反应，要等很久

**Comment by LN-VIVI** [comment]
@SeaHOH  刚用你netsh interface teredo set state type=enterpriseclient servername=win10.ipv6.microsoft.com  这个粘贴进去没反应

**Comment by LN-VIVI** [comment]
@SeaHOH   现在的状况是手机开热点
WiFi网络  本地ipv6的√已取消
我刚刚把注册列计算机\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ 下面的Tcpip6和TCPIP6TUNNEL两个选项。删除了
又用了微软在前缀策略中优先使用 IPv4 over IPv6.diagcab重启了
现在
 C:\Windows\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified

**Comment by LN-VIVI** [comment]
@SeaHOH 告诉我该怎么做  ，手机网络也是广州电信4G
PS C:\Windows\system32> ipconfig /all

Windows IP 配置

   主机名  . . . . . . . . . . . . . : VIVI
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   物理地址. . . . . . . . . . . . . : 1E-30-7E-CF-31-70
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Qualcomm Atheros AR9485WB-EG Wireless Network Adapter
   物理地址. . . . . . . . . . . . . : BC-30-7E-CF-31-70
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.43.131(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年6月5日 18:21:28
   租约过期的时间  . . . . . . . . . : 2018年6月5日 19:21:29
   默认网关. . . . . . . . . . . . . : 192.168.43.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.43.1
   DNS 服务器  . . . . . . . . . . . : 192.168.43.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用
teredo test result is usable.
qualified: True
NAT type: restricted

teredo test result is usable. and the berst server is teredo.remlab.net.

**Comment by SeaHOH** [comment]
我都不知道你搞了些什么其它设置，不过看这个结果应该是可用了。
手动设置成`teredo.remlab.net.`试试。

**Comment by LN-VIVI** [comment]
@SeaHOH 绝望了！当前设备可能无法正常使用 teredo 隧道，NAT 类型是 symmetric！
你想要继续进行测试吗？（Y/N）Y
Starting evaluate servers...
157.56.149.60 ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com', 'win1711.ipv6.microsoft.com'] 217ms
83.170.6.76 ['teredo.remlab.net', 'teredo-debian.remlab.net'] 233ms
217.17.192.217 ['teredo.iks-jena.de'] 249ms
195.140.195.140 ['teredo.trex.fi'] 249ms

**Comment by SeaHOH** [comment]
不要 @ 我了，自己折腾其实挺好，我也是这么过来的。

**Comment by LN-VIVI** [comment]
用ipconfig/all   
为什么我的电脑没有出现隧道适配器？

**Comment by LN-VIVI** [comment]
@SeaHOH

**Comment by AnyWAT** [comment]
貌似：
在前缀策略中优先使用 IPv4 over IPv6.diagcab❌
在前缀策略中优先使用 IPv6 over IPv4.diagcab💯
👀正如：S1-S4是禁用IPv6，X1-X4是启用IPv6？

**Comment by LN-VIVI** [comment]
@SeaHOH 我感觉是系统问题，这次我真的不能自救了

**Comment by LN-VIVI** [comment]
@SeaHOH 我发现一个问题，我用ipconfig/all，
并没有出现隧道适配器的信息，倒是发现一个问题
![qq 20180607202734](https://user-images.githubusercontent.com/18262731/41099496-4e415512-6a91-11e8-974d-4666bd34d991.jpg)
<img width="576" alt="4" src="https://user-images.githubusercontent.com/18262731/41099498-4eb5a746-6a91-11e8-98ca-a0be1abd83a8.png">


这是别人电脑
上的
![qq 20180607203039](https://user-images.githubusercontent.com/18262731/41099706-e303a7c2-6a91-11e8-8e3e-98a29b5de845.jpg)

**Comment by SeaHOH** [comment]
不开启 teredo 隧道就不会有这个 interface，真的不要 @ 我了，谢谢。
