### ISSUE TITLE
启动xx-net后163邮箱上传附件提示服务器连接失败

### ISSUE THREAD

**Issue by jia-zh** [XX-net/XX-Net#10870]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by SeaHOH** [comment]
信息太少，参考 #10875 看是否同样情况。

**Comment by SeaHOH** [comment]
关闭后仍可回复
