### ISSUE TITLE
X-tunnel 忘记密码

### ISSUE THREAD

**Issue by bamboo1117** [XX-net/XX-Net#10874]
记得之前是用Q邮注册买的流量，现在登录时提示账户或密码不正确，也没有地方找回密码，现在注册时都提示不要用中国服务器的邮箱，所以也无从验证是否已经注册过这个邮箱..
p.s.gmail邮箱可以登录但是只有100mb，有点不确定当时用哪个邮箱注册的

**Comment by tmttmd** [comment]
我现在就是用的qq邮箱，请问用大陆的邮箱有什么问题，会影响使用效果吗?

**Comment by zengqlleo** [comment]
我的QQ邮箱也显示用户密码不正确，非常蛋疼

**Comment by allanharper** [comment]
同样忘记。。。

**Comment by SeaHOH** [comment]
用注册邮箱给 xxnet.dev@gmail.com 发邮件要求重置密码。
