### ISSUE TITLE
部署不了+fanqiang 不稳定

### ISSUE THREAD

**Issue by BBC202** [XX-net/XX-Net#10883]
![b56c96bc-821d-4d4c-a913-d1ba2235e02b](https://user-images.githubusercontent.com/35576431/40976177-d3019052-68ff-11e8-9038-435258d057e3.png)
部署没反应，
MAC的 xx-net  经常不稳定

**Comment by SeaHOH** [comment]
把你的翻译软件关掉

**Comment by BBC202** [comment]
@SeaHOH 。。。这个有关联吗？
![image](https://user-images.githubusercontent.com/35576431/40978124-5c5da688-6905-11e8-86a4-aada04861f43.png)
看了之前的那些部署的，照着做了  还是不行。。。  这个弹窗就是不出来

**Comment by SeaHOH** [comment]
换个浏览器试试，或者重新设置一下默认浏览器。

**Comment by BBC202** [comment]
@SeaHOH 谢谢你，换浏览器就部署成功了可以了。

请问miredo一时黄灯，一时绿灯是否需要重新安装？？

然后，如何看miredo版本？

**Comment by BBC202** [comment]
好的。。。 第一次用MAC设置。。不会用
![image](https://user-images.githubusercontent.com/35576431/40981347-49cb2344-690d-11e8-8030-b593792887c6.png)
我用的是这个，你说的是切换这个吗？  哪一个会好一点？
![image](https://user-images.githubusercontent.com/35576431/40981399-65ff7592-690d-11e8-8853-f4de27d223a0.png)

**Comment by SeaHOH** [comment]
要不你换个 Windows，这样简单点。
不行的话，建议你使用其它使用更方便的代理。

**Comment by BBC202** [comment]
:flushed:公司的电脑是win，我个人的是mac。。，就是mac不太稳定

**Comment by SeaHOH** [comment]
感觉你对基础概念和原理都不太了解，而我又没有 Mac 使用经验，所以无法给你更好的建议。

换个更简单的工具是最经济的做法，如果你愿意折腾的话，可以在问题区搜索 Mac miredo 相关问题，
遇到不懂的概念和操作，先用谷歌搜索一下，无法理解再跟帖提问。

**Comment by BBC202** [comment]
确实是不太了解呢，

是我太猴急了:grinning:
我还是得先看看基础的原理:joy:

不过有时候帖子上的操作确实是有些看不懂的地方。

嘛~还是感谢你的解答，谢谢。
