### ISSUE TITLE
更新到最新版之后  用不了了   localhost打不开

### ISSUE THREAD

**Issue by blazert** [XX-net/XX-Net#10881]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  是最新版  3.12.1

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
看过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

更新最新的版本之后  localhost:8085  和 127.0.0.1:8085都打不开
代理也用不了   重新下载新版本  也一样的问题  打不开

**Comment by SeaHOH** [comment]
杀死所有 python 进程，重新运行。

**Comment by blazert** [comment]
@SeaHOH  试过了  重启电脑了 都不行了

**Comment by SeaHOH** [comment]
你的是 Mac 系统？

**Comment by blazert** [comment]
@SeaHOH  不是的   是win10

**Comment by SeaHOH** [comment]
任务管理器中是否有 python 进程？
双击 bat 文件看看有什么输出。可以加一行`pause`防止窗口关闭。

**Comment by blazert** [comment]
@SeaHOH  进程有的   bat输出
`Jun 05 16:12:37.338 [launcher][INFO] use build-in openssl lib
Jun 05 16:12:37.339 [launcher][INFO] start XX-Net 3.12.1
Jun 05 16:12:37.340 [launcher][DEBUG] start confirm_xxnet_exit
Jun 05 16:12:38.359 [launcher][DEBUG] good, xxnet:8085 clear!
Jun 05 16:12:38.360 [launcher][DEBUG] finished confirm_xxnet_exit
Jun 05 16:12:38.574 [gae_proxy][INFO] ------------------------------------------------------
Jun 05 16:12:38.576 [gae_proxy][INFO] Python Version     : 2.7.13
Jun 05 16:12:38.578 [gae_proxy][INFO] OS                 : Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Jun 05 16:12:38.578 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
Jun 05 16:12:38.578 [gae_proxy][INFO] Using public APPID
Jun 05 16:12:38.579 [gae_proxy][INFO] ------------------------------------------------------
Jun 05 16:12:38.595 [gae_proxy][DEBUG] Importing CA
Jun 05 16:12:38.596 [gae_proxy][DEBUG] Removing windows CA
Jun 05 16:12:38.791 [gae_proxy][DEBUG] Begin to import Windows CA
Jun 05 16:12:38.852 [gae_proxy][INFO] SSL use version:TLSv1_2
Jun 05 16:12:39.080 [gae_proxy][DEBUG] network IPv4 is ok, cost:700 ms
Jun 05 16:12:39.398 [gae_proxy][INFO] OpenSSL support alpn
Jun 05 16:12:39.399 [gae_proxy][INFO] load ip range file:D:\软件工具\XX-Net-3.12.1\code\default\gae_proxy\local\ip_range.txt
Jun 05 16:12:39.403 [gae_proxy][INFO] load ip_list num:500, target num:500
Jun 05 16:12:39.404 [gae_proxy][INFO] Adjust scan thread num from 10 to 4
Jun 05 16:12:39.408 [gae_proxy][INFO] SSL use version:TLSv1_2
Jun 05 16:12:39.411 [gae_proxy][INFO] server 127.0.0.1:8087 started.
Jun 05 16:12:39.479 [launcher][INFO] module gae_proxy started
Jun 05 16:12:39.479 [launcher][INFO] start gae_proxy time cost:1115 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Jun 05 16:12:39.509 [cloudflare_front][INFO] load D:\软件工具\XX-Net-3.12.1\data\x_tunnel\cloudflare_domains.json success
Jun 05 16:12:39.510 [cloudflare_front][INFO] SSL use version:TLSv1_2
Jun 05 16:12:39.513 [cloudflare_front][INFO] OpenSSL support alpn
Jun 05 16:12:39.514 [cloudflare_front][INFO] load ip range file:D:\软件工具\XX-Net-3.12.1\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
Jun 05 16:12:39.516 [cloudflare_front][INFO] load ip_list num:50, target num:50
Jun 05 16:12:39.523 [cloudfront_front][INFO] SSL use version:TLSv1_2
Jun 05 16:12:39.538 [cloudfront_front][INFO] OpenSSL support alpn
Jun 05 16:12:39.538 [cloudfront_front][INFO] load ip range file:D:\软件工具\XX-Net-3.12.1\code\default\x_tunnel\local\cloudfront_front\ip_range.txt
Jun 05 16:12:39.541 [cloudfront_front][INFO] load ip_list num:100, target num:100
Jun 05 16:12:39.547 [tls_relay][INFO] SSL use version:TLSv1_2
Jun 05 16:12:39.547 [tls_relay][INFO] OpenSSL support alpn
Jun 05 16:12:39.553 [heroku_front][INFO] SSL use version:TLSv1_2
Jun 05 16:12:39.554 [heroku_front][INFO] OpenSSL support alpn
Jun 05 16:12:39.555 [heroku_front][INFO] load ip_list num:75, target num:75
Jun 05 16:12:39.560 [x_tunnel][INFO] use config_path:D:\软件工具\XX-Net-3.12.1\data\x_tunnel\client.json
Jun 05 16:12:39.561 [x_tunnel][INFO] X-Tunnel window:16777216
Jun 05 16:12:39.562 [x_tunnel][INFO] xxnet_version:3.12.1
Jun 05 16:12:39.565 [x_tunnel][INFO] server 127.0.0.1:1080 started.
Jun 05 16:12:39.565 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
Jun 05 16:12:39.660 [launcher][INFO] module x_tunnel started
Jun 05 16:12:39.661 [launcher][INFO] start x_tunnel time cost:180 ms
Jun 05 16:12:39.710 [smart_router][INFO] Load file:D:\软件工具\XX-Net-3.12.1\code\default\smart_router\local\gfw_black_list.txt
Jun 05 16:12:39.719 [smart_router][INFO] Load file:D:\软件工具\XX-Net-3.12.1\code\default\smart_router\local\gfw_white_list.txt
Jun 05 16:12:39.719 [smart_router][INFO] Load file:D:\软件工具\XX-Net-3.12.1\code\default\smart_router\local\advertisement_list.txt
Jun 05 16:12:39.727 [smart_router][DEBUG] use local DNS server:114.114.114.114
Jun 05 16:12:39.731 [smart_router][INFO] server 127.0.0.1:8086 started.
Jun 05 16:12:39.732 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
Jun 05 16:12:39.733 [smart_router][INFO] start DNS server at 127.0.0.1:53
Jun 05 16:12:39.810 [launcher][INFO] module smart_router started
Jun 05 16:12:39.810 [launcher][INFO] start smart_router time cost:146 ms
Jun 05 16:12:39.811 [launcher][INFO] begin to start web control
Jun 05 16:12:39.813 [launcher][INFO] server 127.0.0.1:8085 started.
Jun 05 16:12:39.814 [launcher][INFO] launcher web control started.
Jun 05 16:12:39.889 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:1f::9 time:474 h2:0 sni:hair-equivalent-bottom.net, host:
Jun 05 16:12:39.889 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:1f::7 time:473 h2:0 sni:silent-octagon-198615.appspot.com, host:silent-octagon-198615.appspot.com
Jun 05 16:12:40.879 [gae_proxy][DEBUG] network IPv6 is ok, cost:2498 ms
Jun 05 16:12:40.880 [launcher][INFO] get uuid:e713f5f4-8ff4-4328-8872-550ac7ad622d
Jun 05 16:12:42.088 [gae_proxy][INFO] scan_ip add ip:2620:11a:a01a::23 time:416 h2:0
Jun 05 16:12:42.092 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:400a:1::a handshake_time:578, fails:1
Jun 05 16:12:42.582 [gae_proxy][INFO] scan_ip add ip:2800:3f0:4001:d::d time:505 h2:0
Jun 05 16:12:42.584 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:400d:3::14 handshake_time:953, fails:0
Jun 05 16:12:46.384 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:1f::9 time:487 h2:0 sni:project202001.appspot.com, host:project202001.appspot.com
Jun 05 16:12:46.679 [gae_proxy][DEBUG] create_ssl update ip:2620:11a:a01a::23 time:786 h2:0 sni:entrance.district.it.org, host:
Jun 05 16:12:48.503 [gae_proxy][INFO] scan_ip add ip:2001:ee0:3202:6::e time:578 h2:0
Jun 05 16:12:48.514 [gae_proxy][INFO] remove_slowest_ip:2a02:28:1:8::12 handshake_time:924, fails:0
Jun 05 16:12:50.825 [gae_proxy][INFO] scan_ip add ip:2404:6800:400e:c::a time:424 h2:0
Jun 05 16:12:50.834 [gae_proxy][INFO] remove_slowest_ip:2a02:2000:1:e101::f handshake_time:811, fails:0
Jun 05 16:12:51.943 [gae_proxy][INFO] scan_ip add ip:2405:4800:100:26::10 time:539 h2:0
Jun 05 16:12:51.947 [gae_proxy][INFO] Adjust scan thread num from 4 to 3
Jun 05 16:12:51.948 [gae_proxy][INFO] remove_slowest_ip:2620:11a:a01a::23 handshake_time:786, fails:0
Jun 05 16:12:53.171 [gae_proxy][DEBUG] create_ssl update ip:2600:6:400:1::10 time:489 h2:0 sni:exercise.low.fruit.org, host:
Jun 05 16:12:53.290 [gae_proxy][DEBUG] create_ssl update ip:2404:6800:400e:c::a time:897 h2:0 sni:my-project-012-1332.appspot.com, host:my-project-012-1332.appspot.com
Jun 05 16:12:53.767 [gae_proxy][INFO] scan_ip add ip:2600:3:200:1::12 time:302 h2:0
Jun 05 16:12:53.771 [gae_proxy][INFO] remove_slowest_ip:2404:6800:400e:c::a handshake_time:897, fails:0
JJun 05 16:13:01.893 [launcher][WARNING] check_update fail:URLError(error(10060, ''),)
Jun 05 16:12:59.144 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4011:33::19 time:2927 h2:0
Jun 05 16:13:16.909 [launcher][INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to D:\软件工具\XX-Net-3.12.1\data\downloads\version.txt, retry:0
Jun 05 16:12:59.779 [gae_proxy][DEBUG] create_ssl update ip:2600:6:400:1::10 time:486 h2:0 sni:jzxm02.appspot.com, host:jzxm02.appspot.com
Jun 05 16:12:59.917 [gae_proxy][DEBUG] create_ssl update ip:2600:3:200:1::12 time:740 h2:0 sni:armybudgetlife.us, host:
Jun 05 16:13:02.944 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4020:1a::a time:351 h2:0
Jun 05 16:13:16.926 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:4011:33::19 handshake_time:2927, fails:0
Jun 05 16:13:16.927 [gae_proxy][INFO] remove_slowest_ip:2001:13d2:801::11 handshake_time:748, fails:0
Jun 05 16:13:16.929 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4006:3c::6 handshake_time:748, fails:0
Jun 05 16:13:18.649 [gae_proxy][DEBUG] create_ssl update ip:2a00:1450:4020:1a::a time:735 h2:0 sni:xxnet-ff2.appspot.com, host:xxnet-ff2.appspot.com
Jun 05 16:13:19.311 [gae_proxy][DEBUG] create_ssl update ip:2001:6c8:180::d time:1397 h2:0 sni:effort-lip-basis.us, host:
Jun 05 16:13:25.807 [gae_proxy][DEBUG] create_ssl update ip:2600:6:400:1::10 time:493 h2:0 sni:dimension-shot.org, host:
Jun 05 16:13:25.978 [gae_proxy][INFO] scan_ip add ip:2804:a8:c800:200::c time:526 h2:0
Jun 05 16:13:25.986 [gae_proxy][INFO] remove_slowest_ip:2001:6c8:180::d handshake_time:891, fails:0
Jun 05 16:13:26.223 [gae_proxy][INFO] scan_ip add ip:2404:6800:400b::9 time:1038 h2:0
Jun 05 16:13:26.225 [gae_proxy][INFO] remove_slowest_ip:2404:6800:400b::9 handshake_time:1038, fails:0
Jun 05 16:13:26.668 [gae_proxy][DEBUG] create_ssl update ip:2001:6c8:180::d time:2015 h2:0 sni:home1-175814.appspot.com, host:home1-175814.appspot.com
Jun 05 16:13:28.365 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:400a:e::18 time:239 h2:0
Jun 05 16:13:28.369 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:4011:44::18 handshake_time:747, fails:0
Jun 05 16:13:32.455 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:e::18 time:640 h2:0 sni:languagedeliverylog.com, host:
Jun 05 16:13:33.144 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4005:1a::6 time:473 h2:0 sni:xx-net-donation04.appspot.com, host:xx-net-donation04.appspot.com
Jun 05 16:13:38.953 [gae_proxy][DEBUG] create_ssl update ip:2600:6:400:1::10 time:486 h2:0 sni:photo.weakness.com, host:
Jun 05 16:13:39.418 [gae_proxy][INFO] scan_ip add ip:2800:3f0:4002:15::a time:624 h2:0
Jun 05 16:13:39.421 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:4007:4::b handshake_time:747, fails:0
Jun 05 16:13:41.755 [gae_proxy][DEBUG] create_ssl update ip:2800:3f0:4001:d::d time:2608 h2:0 sni:xxnet-2016km.appspot.com, host:xxnet-2016km.appspot.com
Jun 05 16:13:45.449 [gae_proxy][DEBUG] create_ssl update ip:2600:6:400:1::10 time:490 h2:0 sni:punch.house.ml, host:
Jun 05 16:13:46.488 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:400a:f::e time:282 h2:0
Jun 05 16:13:46.491 [gae_proxy][INFO] remove_slowest_ip:2800:3f0:4001:d::d handshake_time:1005, fails:0
Jun 05 16:13:47.980 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4004:35::9 time:341 h2:0
Jun 05 16:13:47.986 [gae_proxy][INFO] remove_slowest_ip:2607:f798:1e:220::c handshake_time:747, fails:0
Jun 05 16:13:48.851 [gae_proxy][DEBUG] create_ssl update ip:2804:a8:c800:200::c time:1092 h2:0 sni:anti-wand22.appspot.com, host:anti-wand22.appspot.com
Jun 05 16:13:49.635 [gae_proxy][INFO] scan_ip add ip:2404:6800:400b:2d::b time:431 h2:0
Jun 05 16:13:49.639 [gae_proxy][INFO] remove_slowest_ip:2804:a8:c800:200::c handshake_time:1026, fails:0
Jun 05 16:13:50.703 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4015:e::17 time:417 h2:0
Jun 05 16:13:50.708 [gae_proxy][INFO] remove_slowest_ip:2600:4:400:4::f handshake_time:747, fails:0
Jun 05 16:13:52.090 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:f::e time:638 h2:0 sni:riverorganization.us, host:
Jun 05 16:13:52.339 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4012:11::9 time:437 h2:0
Jun 05 16:13:52.342 [gae_proxy][INFO] remove_slowest_ip:2806:1050:cfff:6::f handshake_time:746, fails:0
Jun 05 16:13:55.357 [gae_proxy][INFO] scan_ip add ip:2804:14c:5bf9:4::e time:502 h2:0
Jun 05 16:13:55.363 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4017:2a::c handshake_time:746, fails:0
Jun 05 16:13:55.530 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4004:35::9 time:674 h2:0 sni:planar-name-127306.appspot.com, host:planar-name-127306.appspot.com
Jun 05 16:14:03.171 [gae_proxy][DEBUG] create_ssl update ip:2404:6800:400b:2d::b time:1633 h2:0 sni:xxnet-tn04.appspot.com, host:xxnet-tn04.appspot.com
Jun 05 16:14:03.724 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4015:e::17
Jun 05 16:14:03.725 [gae_proxy][DEBUG] connect 2a00:1450:4015:e::17 fail:error('certificate is none, sni:ground-medium.us',)
Jun 05 16:14:04.936 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4004:35::a time:270 h2:0
Jun 05 16:14:04.942 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:4015:e::17 handshake_time:417, fails:1
Jun 05 16:14:05.548 [gae_proxy][INFO] scan_ip add ip:2a00:1450:400d:c::14 time:424 h2:0
Jun 05 16:14:05.556 [gae_proxy][INFO] remove_slowest_ip:2404:6800:400b:2d::b handshake_time:931, fails:0
Jun 05 16:14:06.413 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4004:35::a time:681 h2:0 sni:atmosphereorderopening.org, host:
Jun 05 16:14:10.560 [gae_proxy][INFO] scan_ip add ip:2001:ee0:3206:c::e time:684 h2:0
Jun 05 16:14:10.566 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4017:2b::a handshake_time:746, fails:0
Jun 05 16:14:13.312 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4012:11::9 time:888 h2:0 sni:dot.score.association.net, host:
Jun 05 16:14:14.801 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:400d:c::14
Jun 05 16:14:14.802 [gae_proxy][DEBUG] connect 2a00:1450:400d:c::14 fail:error('certificate is none, sni:xxnet-tiny002.appspot.com',)
Jun 05 16:14:17.295 [gae_proxy][DEBUG] create_ssl update ip:2600:6:400:1::10 time:488 h2:0 sni:tassader007.appspot.com, host:tassader007.appspot.com
Jun 05 16:14:18.972 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4002:8::a time:371 h2:0
Jun 05 16:14:18.976 [gae_proxy][INFO] remove_slowest_ip:2a00:1450:400d:c::14 handshake_time:424, fails:1
Jun 05 16:14:20.405 [gae_proxy][DEBUG] create_ssl update ip:2405:4800:100:26::10 time:1088 h2:0 sni:mention-suit-solution.com, host:
Jun 05 16:14:21.030 [gae_proxy][INFO] scan_ip add ip:2001:850:3110:304::1c time:359 h2:0
Jun 05 16:14:21.036 [gae_proxy][INFO] remove_slowest_ip:2405:4800:100:26::10 handshake_time:1039, fails:0
Jun 05 16:14:23.121 [gae_proxy][INFO] scan_ip add ip:2404:6800:4004:16::7 time:427 h2:0
Jun 05 16:14:23.127 [gae_proxy][INFO] remove_slowest_ip:2607:f8b0:4012:11::9 handshake_time:888, fails:0
Jun 05 16:14:24.255 [gae_proxy][DEBUG] create_ssl update ip:2001:850:3110:304::1c time:952 h2:0 sni:light-ether-147016.appspot.com, host:light-ether-147016.appspot.com
Jun 05 16:14:27.182 [gae_proxy][DEBUG] create_ssl update ip:2a00:1450:4002:8::a time:772 h2:0 sni:fix.preparation.com, host:
Jun 05 16:14:30.352 [gae_proxy][INFO] scan_ip add ip:2806:1050:cfff:4::11 time:381 h2:0
Jun 05 16:14:30.362 [gae_proxy][INFO] remove_slowest_ip:2001:850:3110:304::1c handshake_time:859, fails:0
Jun 05 16:14:31.205 [gae_proxy][DEBUG] create_ssl update ip:2404:6800:4004:16::7 time:941 h2:0 sni:fqlbshen.appspot.com, host:fqlbshen.appspot.com
Jun 05 16:14:34.263 [gae_proxy][DEBUG] create_ssl update ip:2804:14c:5bf9:4::e time:1065 h2:0 sni:cheek.talk.net, host:
`

**Comment by SeaHOH** [comment]
看起来很正常，你的代理设置是不是有问题，检查下。

**Comment by beiking** [comment]
如果是edge浏览器，出于安全原因默认是打不开 localhost 和 127.0.0.1 的

需要管理员命令行执行
CheckNetIsolation.exe loopbackexempt -a -p=S-1-15-2-3624051433-2125758914-1423191267-1740899205-1073925389-3782572162-737981194

**Comment by blazert** [comment]
@beiking  使用的是chrome 不是edge

**Comment by SeaHOH** [comment]
系统代理设置，有个排除例外输入框，
里面有没有 127.0.0.1 和 localhost？没有请加上。

**Comment by blazert** [comment]
@SeaHOH  试过了  排序在外了   还是打不开

**Comment by SeaHOH** [comment]
直接关闭代理能否访问 8085？
检查下防火墙。

**Comment by SeaHOH** [comment]
@blazert 能用不？

**Comment by blazert** [comment]
@SeaHOH   可以用了   系统重装了下

**Comment by SeaHOH** [comment]
估计还是代理设置的问题。
虽然重装也是个办法，不过也太夸张了。

**Comment by ccitt** [comment]
控制面板->系统和安全->Windows Defender 防火墙->"允许应用通过Windows Defender 防火墙进行通讯"->"把pythonw那项都打上√后，点击右上角更改设置"即可。
