### ISSUE TITLE
流量显示异常

### ISSUE THREAD

**Issue by 782738120** [XX-net/XX-Net#10889]
2018-03-19我购买了一年的流量，最近显示我的流量变成了0，无法使用Google。今天2018-06-06我又购买了三个月的流量，原来的流量又能用了。。。相当于今天的钱白花了。。账号：782738120@qq.com

**Comment by 782738120** [comment]
> [`__`](

- 

- [ ] 1. url

)

**Comment by SeaHOH** [comment]
之前的公告没注意看么，收到了攻击导致计算错误，等过几天搞定了会再发公告。
到时候你发邮件到 xxnet.dev@gmail.com 说明情况，确认后进行退款。

**Comment by xxnet** [comment]
​流量已经恢复

**Comment by SeaHOH** [comment]
@782738120 
发邮件到 xxnet.dev@gmail.com 说明情况，确认后进行退款。
