### ISSUE TITLE
托盘那个勾为什么会自动消失

### ISSUE THREAD

**Issue by 81880** [XX-net/XX-Net#10888]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**Comment by SeaHOH** [comment]
如果你的是 Win10，且保持更新，这可能是一个 bug，暂时无法解决。

**Comment by 81880** [comment]
是win7。

**Comment by SeaHOH** [comment]
请提供详细描述
