### ISSUE TITLE
无法登陆XX-Net 3.12.1

### ISSUE THREAD

**Issue by downloadluna** [XX-net/XX-Net#10887]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  Yes

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
Yes

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

无论是采用命令行运行Start文件，还是直接双击Start文件，无法登陆且弹出XX-Net控制界
日志显示如下：
【采用命令行运行】
Last login: Wed Jun  6 10:12:25 on ttys000
MacBook-Pro:~ ***$ cd /Users/***/Desktop/XX-Net-3.12.1
MacBook-Pro:XX-Net-3.12.1 ***$ ./start
XX-Net version:3.12.1
Run XX-Net in background.
MacBook-Pro:XX-Net-3.12.1 ***$ 

【直接双击Start文件】
Last login: Wed Jun  6 10:13:59 on ttys000
/Users/***/Desktop/XX-Net-3.12.1/start ; exit;
MacBook-Pro:~ ***$ /Users/***/Desktop/XX-Net-3.12.1/start ; exit;
XX-Net version:3.12.1
Run XX-Net in background.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

完全无法翻墙。
请问，是否有人遇到过这种问题，如何解决？非常感谢

**Comment by SeaHOH** [comment]
贴下 launcher.log

**Comment by downloadluna** [comment]
@SeaHOH  请问什么是launcher.log? 我这边双击start后，原先的登陆界面弹不出来。上面贴出来的是命令行显示出来的类容。

**Comment by SeaHOH** [comment]
在 data/launcher 文件夹

**Comment by downloadluna** [comment]
@SeaHOH 不好意思，我没有在我下载的XX-Net-3.12.1文件夹下看到data/launcher文件夹。并且我用的是MacOS系统，在我的系统下也没有看到/data/launcher文件夹。是否您指的是Win系统？

**Comment by SeaHOH** [comment]
下载 3.12.2 试试

**Comment by downloadluna** [comment]
@SeaHOH  我下载3.12.2，点击start后，命令行显示的依旧是如下内容：
Last login: Thu Jun  7 19:06:02 on ttys000
/Users/***/Desktop/Submission/ENI_JCLP/XX-Net-3.12.2/start ; exit;
***-MacBook-Pro:~ ***$ /Users/***/Desktop/Submission/ENI_JCLP/XX-Net-3.12.2/start ; exit;
XX-Net version:3.12.2
Run XX-Net in background.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

然后chrome无法弹出xx-net的登陆界面。

**Comment by SeaHOH** [comment]
按  #10794 处理下看能启动不。

**Comment by SeaHOH** [comment]
还有问题吗？
关闭后仍可回复
