### ISSUE TITLE
GitHub 无法创建新项目 Something went wrong

### ISSUE THREAD

**Issue by clipperL** [XX-net/XX-Net#10894]
![image](https://user-images.githubusercontent.com/24283006/41028040-1dd49d62-69ab-11e8-9e50-121bae626d9f.png)

模式：智能路由代理、
版本：3.12.1

状态：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.12.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:246
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:undefined
worker: h1:62 h2:0
scan-ip-thread-num: 10
ip-quality: 450
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

日志：
[日志.txt](https://github.com/XX-net/XX-Net/files/2075414/default.txt)

**Comment by SeaHOH** [comment]
GAE 平台不支持 websockets，你可以按 F12 看看是哪个连接出问题。

**Comment by clipperL** [comment]
websockets，不太了解是什么，太深奥了，放弃了。

**Comment by xueyaping** [comment]
切换到PAC代理模式就可以了
