### ISSUE TITLE
请问下 appid 什么时候需要重新部署

### ISSUE THREAD

**Issue by qidanei624** [XX-net/XX-Net#10897]
我看了下 ，上次部署时间是 2016 . 3月，  需要重新部署appid吗？
另外我的延迟 1100+， 这个重新部署appid 会有改善吗？

**Comment by SeaHOH** [comment]
更新只是修复 bug，不会减少延迟。
重新部署很简单，建议你更新。

**Comment by wantno** [comment]
无法部署，程序里面的部署根本用不了啊。。。。

**Comment by AnyWAT** [comment]
XX-Net：全局通过GAEProxy 代理，chrome 代理插件：采用系统代理（或禁用插件）
XX-Net 正常后才操作👀
