### ISSUE TITLE
关于超额ID的问题

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#10899]
超额的这个ID，是不是就不要了？重新部署之后也还是超额
![image](https://user-images.githubusercontent.com/37856464/41082072-a0090b1a-6a5f-11e8-97e8-d04152e960c9.png)

**Comment by milanthree** [comment]
![image](https://user-images.githubusercontent.com/37856464/41082501-2ba8e6da-6a61-11e8-98c4-9aabe127b748.png)
前段实例实用小时数已达到上限

**Comment by SeaHOH** [comment]
你的请求次数太多，消耗了可运行时间。
配额每天只会会刷新一次，重新部署不会刷新配额。
