### ISSUE TITLE
Microsoft GitHub 已经开始审查, 请立即迁移至 GitLab

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net#10893]
https://news.ycombinator.com/item?id=17245018

**Comment by dou4cc** [comment]
那条新闻被改掉了, 具体见存档: https://wxw.moe/@dou4cc/100156683972251921

**Comment by imldf** [comment]
xx-net 也该转移了吧，不然被犹大出卖的概率很大呀！

**Comment by dou4cc** [comment]
@imldf 请不要污蔑犹太人.

**Comment by xxnet** [comment]
​注册了一个gitlab，作为备份，以防万一

https://gitlab.com/XX-net/XX-Net

**Comment by dou4cc** [comment]
@xxnet 不搞个 group 吗?

**Comment by xxnet** [comment]
​搞了一个，放着备用
https://gitlab.com/xxnet

**Comment by no-name2017** [comment]
跟着x大走了

**Comment by imldf** [comment]
@dou4cc  犹大是出卖耶稣的门徒，不是说犹太人。
