### ISSUE TITLE
[已解决]安装xx-net后无法访问10.0.0.* 网段

### ISSUE THREAD

**Issue by TinyBai** [XX-net/XX-Net#10890]
[已解决]VPN导致问题，与xx-net无关

问题：
部署稳定版xx-net后无法访问10.0.0.*，但可打开web配置页面
![01](https://user-images.githubusercontent.com/29816141/41019133-f9cb6ed4-698f-11e8-88e3-49ef75ca710b.PNG)
![02](https://user-images.githubusercontent.com/29816141/41019139-fe0679f8-698f-11e8-8a36-1b1663d31c26.PNG)
怀疑是代理问题，因为启用VPN后可访问

环境：
win10 1803
XX-Net版本 3.11.15
已关闭smart router

尝试步骤：
1.已确认系统代理为空并取消xxnet全局代理
![03](https://user-images.githubusercontent.com/29816141/41019517-97f045b6-6991-11e8-8580-3358596b1d76.PNG)
2.已尝试网络重置
3.已尝试移除xx-net并重置网络
4.chrome浏览器直连，换edge仍旧无妨访问
5.已关闭防火墙
6.无其他防火墙及杀毒软件
7.hosts无问题

诊断日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:45
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 16
ip-quality: 1195
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

感谢协助！

**Comment by SeaHOH** [comment]
10.0.0.0/8 属于私有网络，你所在的网络配置有这个地址，且有路由通路，才能访问到。
这个地址有何用处，你应该去询问告诉你使用它的人。

再一个就是，IP 无需解析，域名解析后就是 IP。

**Comment by TinyBai** [comment]
@SeaHOH 
感谢回复与指正！实际上是我的路由器网段在10.0.0.*上，同网络下其他设备都能正常访问路由器后台以及NAS，只有这台电脑在安装xxnet之后无法访问10.0.0.*网段。启用VPN后能够访问，所以感觉还是哪里设置问题，可是排除法也做的差不多了
所以还是疑惑到底怎么解决这个问题，又不想重置系统……也许跟启用了ipv6有关？

**Comment by SeaHOH** [comment]
VPN 后面的网络不一定和你想要访问的网络相同，私有网络地址是可以随意组网的，道理同 192.168.0.0/16。
检查你的默认网关设置，以及相关系统服务是否开启。
如果你认为和 IPv6 有关，可以重置或禁用它，虽然我不这么认为。

**Comment by TinyBai** [comment]
@SeaHOH 
多谢耐心回复
附ipconfig如下，网关是正确的，检查服务也无异常
其中local area connection 10、11不知道是否与xxnet有关，在网络设置里并看不到这些适配器
![04](https://user-images.githubusercontent.com/29816141/41047297-dafef3c8-69de-11e8-8ca0-59d1c568406e.PNG)

**Comment by SeaHOH** [comment]
是路由器地址吗？能 ping 通吗？

**Comment by TinyBai** [comment]
@SeaHOH 
是我自己疏忽了，忘了考虑VPN本身的问题，与XX-net无关
卸载重装VPN后问题解决，再次感谢耐心回复！
fixed #10890
