### ISSUE TITLE
enable_ipv6.bat修改优先级的时候，有些前缀的元素不见了，只剩3个

### ISSUE THREAD

**Issue by iopxiang** [XX-net/XX-Net#10892]
PS C:\WINDOWS\system32> netsh interface ipv6 set prefixpolicy ::1/128 50 0
找不到元素。

PS C:\WINDOWS\system32> netsh interface ipv6 set prefixpolicy ::/0 40 1
找不到元素。

PS C:\WINDOWS\system32> netsh interface ipv6 set prefixpolicy ::/96 20 3
找不到元素。

PS C:\WINDOWS\system32> netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 10 4
找不到元素。

大家有这个问题吗？跑完之后优先级也并没有改过来，还是ipv4 优先，大家有这个问题吗？用的是win10 1803

C:\WINDOWS\system32> netsh int ipv6 show prefix
查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        35      6  2001::/16
        30      2  2002::/16
        25      5  2001::/32

**Comment by SeaHOH** [comment]
是的，很久之前就这样，不过似乎影响不大。
等会儿我把缺失的补上。

**Comment by iopxiang** [comment]
@SeaHOH 但是优先级没有改过来啊  而且我有原生ipv6，但总是ipv4优先解析

**Comment by SeaHOH** [comment]
```
netsh interface ipv6 add prefixpolicy ::1/128 50 0
netsh interface ipv6 set prefixpolicy ::1/128 50 0
netsh interface ipv6 add prefixpolicy ::/0 40 1
netsh interface ipv6 set prefixpolicy ::/0 40 1
netsh interface ipv6 add prefixpolicy 2001::/16 35 6
netsh interface ipv6 set prefixpolicy 2001::/16 35 6
netsh interface ipv6 add prefixpolicy 2002::/16 30 2
netsh interface ipv6 set prefixpolicy 2002::/16 30 2
netsh interface ipv6 add prefixpolicy 2001::/32 25 5
netsh interface ipv6 set prefixpolicy 2001::/32 25 5
netsh interface ipv6 add prefixpolicy ::/96 20 3
netsh interface ipv6 set prefixpolicy ::/96 20 3
netsh interface ipv6 add prefixpolicy ::ffff:0:0/96 10 4
netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 10 4
```
这个是补齐后的，你试试有用没，应该是原生优先。
不过你为什么要运行这个脚本还不关闭隧道？

**Comment by iopxiang** [comment]
谢谢  因为我有时候要在没有原生ipv6的环境用
