### ISSUE TITLE
可否加入原版Goagent的[dns]选项？开这个后Youtube视频比较快

### ISSUE THREAD

**Issue by AlanTR** [XX-net/XX-Net#109]
proxy.ini之类的找了一圈没看到这种配置文件

**Comment by xxnet** [comment]
不知原理是什么，能否介绍一下？

2015-04-04 6:32 GMT-04:00 AlanTR <notifications@github.com>:

**Comment by yfdyh000** [comment]
goagent的DNS好像是基于黑名单IP吧，而那个方法现在已经失效了，目前污染是返回随机IP。

我推荐 https://github.com/chengr28/Pcap_DNSProxy ，能解决用国外DNS时返回外国CDN IP的问题，只是配置有点繁琐，但也功能强大。

**Comment by xxnet** [comment]
Windows下需要安装pcap，增加门槛。

这种方法也容易被GFW的升级而失效吧。
  GFW模拟得更像的返回结果，不会太难吧。



在 2015年4月5日 上午9:48，YFdyh000 <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
只是向他推荐，没说集成，集成的难度也太大了。

我觉得不必附带这个功能，因为目前不能达到良好的效果。顶多做一个非标准端口的转发，但那样就有外国CDN IP的问题，而且需要用户设置DNS，软件没启动还会导致无法打开网页。
失效不太容易吧，至少非标准端口目前没封（据说），而且它还支持加密的DNSCurve。

**Comment by xxnet** [comment]
加密的DNS 就不需要pcap了。
其实解决问题，只需要一个方案就好了。
没有深入研究过这个项目。

谢谢你的信息

在 2015年4月5日 上午10:14，YFdyh000 <notifications@github.com>写道：

**Comment by AlanTR** [comment]
呃，不太方便就算了。。360清晰度一样可以看来自我的华为手机-------- 原始邮件 --------主题：Re: [XX-Net] 可否加入原版Goagent的[dns]选项？开这个后Youtube视频比较快 (#109)发件人：xxnet 收件人：XX-net/XX-Net 抄送：AlanTR Windows下需要安装pcap，增加门槛。



这种方法也容易被GFW的升级而失效吧。

  GFW模拟得更像的返回结果，不会太难吧。







在 2015年4月5日 上午9:48，YFdyh000 <notifications@github.com>写道：
