### ISSUE TITLE
请问XXNET可以在EDGE上运行吗

### ISSUE THREAD

**Issue by AnLvNing** [XX-net/XX-Net#10909]
如题，或者说可以通过别的什么软件来实现吗。

**Comment by tcwilliy** [comment]
用neow 设置全局代理，把要直连和代理分别加到两个记事本中就可以实现自动代理，我这就是这么做的 很好用

**Comment by tcwilliy** [comment]
或者全局使用智能路由模式，也很好用

**Comment by AnLvNing** [comment]
有教程吗，新手不太会

**Comment by AnyWAT** [comment]
https://github.com/wooowooo/MEOW

**Comment by SeaHOH** [comment]
不就是个浏览器吗，设置代理不久好了，没搞懂你们要干嘛。

**Comment by AnLvNing** [comment]
对，但是WIKI里只有通过chrome和火狐浏览器设置代理的教程，我的意思是有没有其他浏览器设置代理的教程。

**Comment by SeaHOH** [comment]
托盘工具就能设置系统代理，edge 使用系统代理设置，没有然后了。

**Comment by AnLvNing** [comment]
OK，谢谢了。
