### ISSUE TITLE
已经安装登陆XX-NET但是不能科学上网

### ISSUE THREAD

**Issue by Allen201705** [XX-net/XX-Net#10906]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  已经是最新版本

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
诊断日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:500
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 605
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by Allen201705** [comment]
现在又可以了上Google了。。。。
怎么才能让它稳定科学上网呢？

**Comment by SeaHOH** [comment]
保证 IPv6 正常即可，Fail 时点击尝试修复，然后点击更换 teredo 服务器。

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 10
👀貌似就凭这点就难以正常、更别说稳定🤣

**Comment by SeaHOH** [comment]
主要是隧道本身有影响，我设置成下面这样也挺好用
max_scan_ip_thread_num: 5
max_good_ip_num: 30
