### ISSUE TITLE
刚发布的 3.12.2 第二版，每次启动时都要重新导入一次证书。

### ISSUE THREAD

**Issue by hongkonghot** [XX-net/XX-Net#10900]
刚发布的 3.12.2 第二版，每次启动时都要重新导入一次证书。

**Comment by SeaHOH** [comment]
WIndows？请确认给予权限确定。

**Comment by hongkonghot** [comment]
最近的新版本已经解决了证书问题

**Comment by AnyWAT** [comment]
刚发布的 3.12.2 第二版（😜特供？还是3.12.2本身？），每次启动时都要重新导入一次证书。
最近的新版本（🤣不就是3.12.2？）已经解决了证书问题
——1与3楼自戕😱

**Comment by hongkonghot** [comment]
同一个版本号也会多次更新啊！那要怎么形容中间新发的没有变更版本号的程序呢？

**Comment by zuyoushen** [comment]
经测试，win7和win10下，每次启动xx-net都出现导入证书提示，以前只提示一次后，就不再提示。包括最新的clone or download.
![2](https://user-images.githubusercontent.com/13383429/41495405-01015d82-7159-11e8-8fba-8f6f42cae01a.PNG)

**Comment by SeaHOH** [comment]
3.12.12 和 master 都这样？
从哪个版本开始的？

**Comment by SeaHOH** [comment]
不要用管理员权限运行 XX-Net。

**Comment by zuyoushen** [comment]
是的，从3.12.12开始，3.12.12 和 master 都这样。没有用管理员权限运行 XX-Net。就是全新安装时，用管理员运行一次BAT文件，生成桌面快捷方式后，双击运行或是开机运行。

**Comment by AnyWAT** [comment]
手动下载解压，与若干前版本在同一 code 下的Win10 正常👀

**Comment by zuyoushen** [comment]
XX-NET功能一切正常
![3](https://user-images.githubusercontent.com/13383429/41497211-70389fec-7183-11e8-8c7d-ed17290eb392.PNG)

**Comment by zuyoushen** [comment]
> 手动下载解压，与若干前版本在同一 code 下的Win10 正常👀
都是全新手动下载解压，全新安装，目录内无其它版本xxnet

**Comment by SeaHOH** [comment]
试试之前的版本

**Comment by zuyoushen** [comment]
> 试试之前的版本
全新下载安装3.12.1 删除原先的快捷方式和系统证书。运行后没有再次启动提示。
![4](https://user-images.githubusercontent.com/13383429/41497443-eb2239d0-7187-11e8-8b2a-3920e487288b.PNG)

**Comment by SeaHOH** [comment]
再重复操作一次，这次换成 3.12.2。

**Comment by zuyoushen** [comment]
分别全新下载3.12.2和master 压缩包，操作和我上面说的一样，3.12.2再次启动后无提示，但master 再次启动后有提示。

3.12.2首次运行图

![5](https://user-images.githubusercontent.com/13383429/41498256-8ecf2792-719b-11e8-94e9-a397593d2276.PNG)
master再次运行提示图

![7](https://user-images.githubusercontent.com/13383429/41498262-a945e4c6-719b-11e8-8267-05aacac2da33.PNG)

**Comment by SeaHOH** [comment]
知道了，谢谢你帮忙测试。
master 属于还没发布的版本，一般没必要更新到这个版本，因为有时候可能会有 bug。

**Comment by SeaHOH** [comment]
第二次运行 master 版本应该就没有提示了，这个版本才有相关修改。

**Comment by zuyoushen** [comment]
> 知道了，谢谢你帮忙测试。
master 属于还没发布的版本，一般没必要更新到这个版本，因为有时候可能会有 bug。

不客气，应该说谢谢的是我们这群使用者！是你们的辛勤劳作，才让我们有选择的余地。
有时候看到master 有更新，就想下栽下来尝试下。
![default](https://user-images.githubusercontent.com/13383429/41499321-9e22c180-71b0-11e8-8216-56cc940d89c5.png)
