### ISSUE TITLE
无法部署APPENGINE，chrome浏览器。

### ISSUE THREAD

**Issue by wantno** [XX-net/XX-Net#10901]
换了，猎豹也是一样。

**Comment by wantno** [comment]
我现在的服务端版本是3.3.1，

**Comment by wantno** [comment]
部署服务端时候，在google上确认完权限后跳转回来后localhost:8080出错

**Comment by AnyWAT** [comment]
localhost:8080出错👀不是8085？
XX-Net：全局通过GAEProxy 代理，chrome 代理插件：采用系统代理（或禁用插件）

**Comment by qidanei624** [comment]
那个 stylish，  tampermonkey， ublock等影响网页的扩展先禁用掉， 
然后那个autoproxy扩展设置成 全局

**Comment by wantno** [comment]
谢谢楼上的，浏览器禁止了。问题解决了。
