### ISSUE TITLE
IPV6启用失败

### ISSUE THREAD

**Issue by stefchiu** [XX-net/XX-Net#10916]
刚升到3.12.1的时候点启用是可以的，重启之后显示“已禁用”，然后就再启用不了了，每次点了都提示初次设置让我重启。

C:\WINDOWS\system32>sc config RpcEptMapper start= auto
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start RpcEptMapper
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config DcomLaunch start= auto
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start DcomLaunch
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config RpcSs start= auto
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start RpcSs
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config nsi start= auto
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start nsi
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config Winmgmt start= auto
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start Winmgmt
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config Dhcp start= auto
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start Dhcp
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config WinHttpAutoProxySvc start= auto
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start WinHttpAutoProxySvc
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config iphlpsvc start= auto
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start iphlpsvc
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>goto :eof

C:\WINDOWS\system32>netsh interface ipv6 reset
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

C:\WINDOWS\system32>ipconfig /flushdns

Windows IP 配置

已成功刷新 DNS 解析缓存。

C:\WINDOWS\system32>goto :eof

C:\WINDOWS\system32>netsh interface teredo set state type=enterpriseclient servername=win10.ipv6.microsoft.com.
确定。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::1/128 50 0
找不到元素。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::/0 40 1
找不到元素。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy 2001::/16 35 6
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy 2002::/16 30 2
确定。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy 2001::/32 25 5
确定。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::/96 20 3
找不到元素。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 10 4
找不到元素。

C:\WINDOWS\system32>Reg add HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f
操作成功完成。

C:\WINDOWS\system32>Reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters /v DisabledComponents /t REG_DWORD /d 0 /f
操作成功完成。

C:\WINDOWS\system32>goto :eof

C:\WINDOWS\system32>ipconfig /all

Windows IP 配置

主机名 . . . . . . . . . . . . . : Stef-PC
主 DNS 后缀 . . . . . . . . . . . :
节点类型 . . . . . . . . . . . . : 混合
IP 路由已启用 . . . . . . . . . . : 否
WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 Local Area Connection:

连接特定的 DNS 后缀 . . . . . . . :
描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
物理地址. . . . . . . . . . . . . : FC-AA-14-A5-2C-16
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是
IPv4 地址 . . . . . . . . . . . . : 192.168.1.108(首选)
子网掩码 . . . . . . . . . . . . : 255.255.255.0
获得租约的时间 . . . . . . . . . : 2018年6月8日 17:41:35
租约过期的时间 . . . . . . . . . : 2154年7月17日 16:15:02
默认网关. . . . . . . . . . . . . : 192.168.1.1
DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
DNS 服务器 . . . . . . . . . . . : 192.168.1.1
8.8.8.8
TCPIP 上的 NetBIOS . . . . . . . : 已启用

隧道适配器 Local Area Connection* 10:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . :
描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
DHCP 已启用 . . . . . . . . . . . : 否
自动配置已启用. . . . . . . . . . : 是

C:\WINDOWS\system32>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型 : enterpriseclient (Group Policy)
服务器名称 : win10.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : probe (cone)
客户端类型 : teredo client
网络 : managed

C:\WINDOWS\system32>netsh interface ipv6 show route

发布 类型 跃点数 前缀 索引 网关/接口名称
------- -------- --- ------------------------ --- ------------------------
否 系统 256 ::1/128 1 Loopback Pseudo-Interface 1
否 系统 256 fe80::/64 12 Local Area Connection* 10
否 系统 256 fe80::3008:411d:25f0:259b/128 12 Local Area Connection* 10
否 系统 256 ff00::/8 1 Loopback Pseudo-Interface 1
否 系统 256 ff00::/8 12 Local Area Connection* 10

C:\WINDOWS\system32>netsh interface ipv6 show interface

Idx Met MTU 状态 名称
--- ---------- ---------- ------------ ---------------------------
12 75 1280 disconnected Local Area Connection* 10
1 75 4294967295 connected Loopback Pseudo-Interface 1

C:\WINDOWS\system32>netsh interface ipv6 show prefixpolicies
查询活动状态...

优先顺序 标签 前缀
---------- ----- --------------------------------
35 6 2001::/16
30 2 2002::/16
25 5 2001::/32

C:\WINDOWS\system32>netsh interface ipv6 show address

接口 12: Local Area Connection* 10

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::3008:411d:25f0:259b%12

接口 1: Loopback Pseudo-Interface 1

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite ::1

C:\WINDOWS\system32>route print
===========================================================================
接口列表
8...fc aa 14 a5 2c 16 ......Realtek PCIe GBE Family Controller
1...........................Software Loopback Interface 1
12...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标 网络掩码 网关 接口 跃点数
0.0.0.0 0.0.0.0 192.168.1.1 192.168.1.108 35
127.0.0.0 255.0.0.0 在链路上 127.0.0.1 331
127.0.0.1 255.255.255.255 在链路上 127.0.0.1 331
127.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
192.168.1.0 255.255.255.0 在链路上 192.168.1.108 291
192.168.1.108 255.255.255.255 在链路上 192.168.1.108 291
192.168.1.255 255.255.255.255 在链路上 192.168.1.108 291
224.0.0.0 240.0.0.0 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 192.168.1.108 291
255.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
255.255.255.255 255.255.255.255 在链路上 192.168.1.108 291
===========================================================================
永久路由:
无

IPv6 路由表
===========================================================================
活动路由:
接口跃点数网络目标 网关
1 331 ::1/128 在链路上
1 331 ff00::/8 在链路上
===========================================================================
永久路由:
无

C:\WINDOWS\system32>goto :eof

**Comment by abigbone** [comment]
重置Win10组策略

这里需要三个命令配合完成，首先可以重置用户策略（执行后无说明）：

rd /s /q "%windir%\System32\GroupPolicyUsers"

然后可以重置本地组策略，包括计算机配置和用户配置（执行后无说明）：

rd /s /q "%windir%\System32\GroupPolicy"

这两个执行之后，使用如下强制更新命令让上述重置操作生效（执行成功后会有提示）：

gpupdate /force

**Comment by SeaHOH** [comment]
@abigbone 
你这个太过了，建议手动完成操作。

**Comment by abigbone** [comment]
可能很多人不了解组策略，反而设置了很多错误项

**Comment by SeaHOH** [comment]
正因为不了解，你这样删除不考虑后果吗？
我已经添加了只重置 teredo 的相关检测。下个版本就能用上。
