### ISSUE TITLE
XX在往连接池里疯狂塞ip，连接池都比ip数总数都多了。。。

### ISSUE THREAD

**Issue by 10lumiya10** [XX-net/XX-Net#10912]
![image](https://user-images.githubusercontent.com/36228639/41186738-3cfcbb3c-6bce-11e8-93aa-c535be1eb2e5.png)
然后墙翻不出去了。。。

**Comment by 10lumiya10** [comment]
重启过XX以后恢复正常了

**Comment by SeaHOH** [comment]
是否修改过 config.json 自定义设置？
也可能是你的代理请求过多？
下次再出现这种情况，可以把当时的日志贴过来。

**Comment by 10lumiya10** [comment]
![image](https://user-images.githubusercontent.com/36228639/42407988-92957224-81f8-11e8-9307-9c2088be5e8d.png)

重启过一次xx了，不过还是这样


日志：
Jul 07 15:11:43.046 - [WARNING] not enough ip

Jul 07 15:11:43.535 - [DEBUG] finished scan all exist ip

Jul 07 15:11:43.580 - [DEBUG] 2607:f798:14:3e::c worker close:keep alive

Jul 07 15:11:46.443 - [DEBUG] 2804:7f4:6803:cace::f worker close:keep alive

Jul 07 15:11:49.463 - [WARNING] not enough ip

Jul 07 15:11:50.327 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.327 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.327 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.328 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.328 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.328 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.328 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.329 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.329 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.329 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.329 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.329 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.329 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.329 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.330 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.331 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.330 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.331 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=15

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=16

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=12

Jul 07 15:11:50.331 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=13

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.331 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=21

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=18

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.332 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=17

Jul 07 15:11:50.333 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=22

Jul 07 15:11:50.333 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=15"

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=23

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=20

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=19

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=24

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=28

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=26

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=25

Jul 07 15:11:50.333 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=16"

Jul 07 15:11:50.333 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=27

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=29

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=30

Jul 07 15:11:50.334 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=12"

Jul 07 15:11:50.334 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=13"

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=35

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=31

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=33

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=32

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=37

Jul 07 15:11:50.334 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=21"

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=36

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=34

Jul 07 15:11:50.334 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=38

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=18"

Jul 07 15:11:50.335 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=41

Jul 07 15:11:50.335 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=42

Jul 07 15:11:50.335 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=40

Jul 07 15:11:50.335 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=39

Jul 07 15:11:50.335 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=45

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=17"

Jul 07 15:11:50.335 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=43

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=22"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=23"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=20"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=19"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=24"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=28"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=26"

Jul 07 15:11:50.335 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=25"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=27"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=29"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=30"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=35"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=31"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=33"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=32"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=37"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=36"

Jul 07 15:11:50.336 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=34"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=38"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=41"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=42"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=40"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=39"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=45"

Jul 07 15:11:50.337 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=43"

Jul 07 15:11:51.359 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:51.360 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:51.360 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:51.360 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:51.360 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:51.360 - [WARNING] task POST None /_gh/ timeout

Jul 07 15:11:51.360 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:51.360 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:51.360 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:51.360 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:51.360 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:51.360 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 07 15:11:51.361 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=49

Jul 07 15:11:51.361 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=50

Jul 07 15:11:51.361 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=47

Jul 07 15:11:51.361 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=48

Jul 07 15:11:51.362 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=44

Jul 07 15:11:51.362 - [WARNING] gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=46

Jul 07 15:11:51.362 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=49"

Jul 07 15:11:51.362 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=50"

Jul 07 15:11:51.362 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=47"

Jul 07 15:11:51.362 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=48"

Jul 07 15:11:51.362 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=44"

Jul 07 15:11:51.362 - [DEBUG] GAE_Exception 600 u"gae_exception:'600:fetch gae fail' http://jp1.xx-net.net/data?tid=46"

Jul 07 15:11:54.819 - [DEBUG] create_ssl update ip:2a00:1e48:99:17::c time:1766 h2:0 sni:lift.club.ticket.net, host:

Jul 07 15:11:55.819 - [WARNING] not enough ip

Jul 07 15:11:59.464 - [WARNING] not enough ip

Jul 07 15:12:05.820 - [WARNING] not enough ip

Jul 07 15:12:09.465 - [WARNING] not enough ip

Jul 07 15:12:13.735 - [DEBUG] create_ssl update ip:2a00:1e48:99:17::c time:4253 h2:0 sni:aqueous-tesla-189209.appspot.com, host:aqueous-tesla-189209.appspot.com

Jul 07 15:12:15.813 - [WARNING] 2600:1:0:1e::e h1_request:Exception('time out',) inactive_time:70 task.timeout:45

Jul 07 15:12:15.813 - [WARNING] 2600:1:0:1e::e trace: 0:connect, 3707:init, 1036:request, 710:Res, 585:request, 25528:Res, 1:request,:45013, processed:2, transfered:338, sni:double-song-189210.appspot.com

Jul 07 15:12:15.813 - [WARNING] retry_task_cb: POST None/_gh/

Jul 07 15:12:15.813 - [WARNING] POST None/_gh/ response_fail:retry timeout:70

Jul 07 15:12:15.813 - [DEBUG] 2600:1:0:1e::e worker close:down fail

Jul 07 15:12:16.828 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 07 15:12:16.843 - [WARNING] not enough ip

Jul 07 15:12:16.890 - [DEBUG] network IPv4 is ok, cost:62 ms

Jul 07 15:12:19.466 - [WARNING] not enough ip

Jul 07 15:12:26.846 - [WARNING] not enough ip

Jul 07 15:12:29.467 - [WARNING] not enough ip

Jul 07 15:12:36.849 - [WARNING] not enough ip

**Comment by 10lumiya10** [comment]
姑且升级成3.12.7后正常了。。。

**Comment by SeaHOH** [comment]
测试版就这样。
不过后面这个问题和标题没关系，你可以到对应发布跟帖，或单独发个问题。
