### ISSUE TITLE
关于xxnet安卓版

### ISSUE THREAD

**Issue by AnLvNing** [XX-net/XX-Net#10918]
显示一切正常，但是用浏览器打开墙外网站时会显示该网站的安全证书有问题，，点击继续后页面无法正常访问

**Comment by SeaHOH** [comment]
状态页和浏览器错误提示，分别截个图看看。

**Comment by AnLvNing** [comment]
我这里无法上传图片。。。。

**Comment by AnLvNing** [comment]
![1528693674763](https://user-images.githubusercontent.com/33977540/41213531-70d767aa-6d35-11e8-8d65-ad18a5abbc18.jpg)
![1528693728122](https://user-images.githubusercontent.com/33977540/41213563-9e10cea0-6d35-11e8-89f6-11e8cff5f530.jpg)

**Comment by SeaHOH** [comment]
这那张图是同一个浏览器？

**Comment by AnLvNing** [comment]
不是，第一个图是xxnetapp页面的截图，后面那个是用手机自带的浏览器浏览的截图

**Comment by SeaHOH** [comment]
用自带浏览器访问 http://127.0.0.1:8085/module/gae_proxy/control/download_cert 安装证书。

**Comment by AnLvNing** [comment]
OK,好像好了....是因为手机自带浏览器不信任证书吗

**Comment by SeaHOH** [comment]
大概是吧。
