### ISSUE TITLE
XX-net 无法启动

### ISSUE THREAD

**Issue by Wybxc** [XX-net/XX-Net#10917]
环境 Windows 7 SP1 32 位，版本 3.12.2。
打开 XX-net 目录下的 `start.vbs` 无反应，并且运行`code\default\python27\1.0\python.exe`出现命令行后立刻关闭。
我在电脑中安装了 Python3，并且设置了`%PYTHONHOME%`环境变量，不知道是否有关系。

**Comment by SeaHOH** [comment]
下载不完整？
sha256：9477ED60C31A3ED0CE98D0728A232ACAFFFB5BBCF2350810D4282D2E41EB00E8

**Comment by Wybxc** [comment]
谢谢，已经自行解决了。原因是我把`%PYTHONPATH%`和`%PYTHONHOME%`设置到了 Python3 的路径。
在命令行里依次执行以下代码就可以了。
```
SET PYTHONPATH=
SET PYTHONHOME=
start.vbs
```
但是保存成一个批处理就不行，不知道原因是什么。

**Comment by SeaHOH** [comment]
是比较奇怪，运行 code\default\python27\1.0\python.exe 应该不会关闭才对。

**Comment by linhaigoo** [comment]
我也发现了是环境变量的问题
加入到vbs的里面去执行就好了
```
Set oShell = CreateObject ("Wscript.Shell")
oShell.Environment("Process")("PYTHONPATH")=""
oShell.Environment("Process")("PYTHONHOME")=""
oShell.Run strArgs, isConsole(), false
```
