### ISSUE TITLE
教程最后一步：如何判断appid部署成功出现问题

### ISSUE THREAD

**Issue by luo-zhijian** [XX-net/XX-Net#10915]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
按照教程https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids操作，前面均正常【设置AppID的App引擎这个地方选择位置成功，后面和教程里不大一样。查看过https://github.com/XX-net/XX-Net/issues/4720，第四步提到选择完毕算建立完成，所以这个地方应该没错】，其他正常。
![AppID的App引擎](https://user-images.githubusercontent.com/35712718/41191581-6e87676e-6c24-11e8-9c84-c25952ca4d27.png)

但是## **最后一步——如何判断appid部署成功**提示：

_该网页无法正常运作
xx-net1-*&%￥#@%#.appspot.com 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS_

再次重复部署服务器，配置appid依旧这种情况
![判断appid部署](https://user-images.githubusercontent.com/35712718/41191539-c25dd126-6c23-11e8-9082-5aacb979909d.png)
谢谢！
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:50 h2:1
scan-ip-thread-num: 10
ip-quality: 332
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
每个帐号可以建多个 AppID，而且可以删除重建新的，你完全可以把名称发出来。

**Comment by SeaHOH** [comment]
不回复我就关啦
关闭后仍可回复
