### ISSUE TITLE
x-tunnel 3.12.2，账号可以登录，但是频繁出现602状态，需要经常重新关闭再打开

### ISSUE THREAD

**Issue by superwjc** [XX-net/XX-Net#10919]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  是

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

重启之后可以短暂代理上网，但稍后又会出现602状态，并且Google总需要人机身份验证。
服务器是自动选择

**Comment by AnyWAT** [comment]
👀如是Windows无需退出即可运行（挤出前面的）
😜保持正常并稳定的臭大街法则：
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting 
😂关闭”自动调整扫描线程数”，😘增大“最大扫描线程数”到能维持接近并达到“IPv6 IP数”及较小的“IP延迟”，😍"IP模式"仅IPv6为佳，😊“连接池”较小或中断后的重开，最好“检查IP”，😁结合：（开机）启动XX-Net 前即运行以下bat（内容）可观察变化过程，状态 dormant 即已开始正常化。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop
😭可了解到底是IPv6隧道还是XX-Net 的问题。😜

**Comment by SeaHOH** [comment]
把 X-Tunnel 状态全部贴出来

另，如果使用 gae_front 需要注意 teredo 间隔性抽风。
我的情况是一般一俩分钟后 UDP 封包即可回复正常，但是需要重新更换服务器。

**Comment by SeaHOH** [comment]
请尝试 3.12.4，并开启 gae_proxy 模块。

**Comment by wuliaoC** [comment]
为什么我没全局设置

**Comment by AnyWAT** [comment]
V 3.12.5 gae_proxy 模块增加全局设置级别用于调整参数，可在网页界面中设置 https://github.com/XX-net/XX-Net/releases

**Comment by Chriszhung** [comment]
改了data/gae_proxy\config.json 添加
"max_good_ip_num": 550后，xxnet启动全红字，按任意键继续，就退出了

**Comment by Chriszhung** [comment]
[image: 捕获.JPG]

AnyWAT <notifications@github.com> 于2018年10月20日周六 下午11:25写道：

**Comment by AnyWAT** [comment]
没图片，纯文字即可

**Comment by Chriszhung** [comment]
没图？插入邮件中的
{
  "max_scan_ip_thread_num": 200,
  "auto_adjust_scan_ip_thread_num": 0,
  "connect_receive_buffer": 524288
}

AnyWAT <notifications@github.com> 于2018年10月20日周六 下午11:49写道：

**Comment by AnyWAT** [comment]
{
  "max_good_ip_num": 550,
  "max_scan_ip_thread_num": 200,
  "auto_adjust_scan_ip_thread_num": 0,
  "connect_receive_buffer": 524288
}

😱 "max_scan_ip_thread_num": 200 太大，50-100？

**Comment by Chriszhung** [comment]
没改过，安装后就是这样

AnyWAT <notifications@github.com> 于 2018年10月21日周日 00:01写道：

**Comment by AnyWAT** [comment]
是说 "max_scan_ip_thread_num": 200 太大，50-100？
😜扯，程序默认值为10
