### ISSUE TITLE
最近两天使用x-tunnel老是会出现get_front fail报警情况

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#10929]
如题，时不时就会出现get_front fail报警

**Comment by milanthree** [comment]
![image](https://user-images.githubusercontent.com/37856464/41328115-06f73552-6ef9-11e8-9574-c0dc32ce1cb9.png)

**Comment by milanthree** [comment]
@SeaHOH 有效

**Comment by SeaHOH** [comment]
请尝试 3.12.4，并开启 gae_proxy 模块。
