### ISSUE TITLE
IPV6   fail的办法。我只是要保存一下。谢谢管理

### ISSUE THREAD

**Issue by whhxmwhh** [XX-net/XX-Net#10928]
所以，如果重复启用IP6 失败不妨重置一下组策略，
`重置Win10组策略
这里需要三个命令配合完成，首先可以重置用户策略（执行后无说明）：

rd /s /q "%windir%\System32\GroupPolicyUsers"

然后可以重置本地组策略，包括计算机配置和用户配置（执行后无说明）：

rd /s /q "%windir%\System32\GroupPolicy"

这两个执行之后，使用如下强制更新命令让上述重置操作生效（执行成功后会有提示）：

gpupdate /force`

然后进入
D:\XX-Net-2018\code\3.12.2\gae_proxy\local\ipv6_tunnel 路径自己调整
依次执行disable_ipv6.bat 和 enable_ipv6.bat ，然后可能就好了

**Comment by AnyWAT** [comment]
然后可以重置本地组策略，包括计算机配置和用户配置（执行后无说明）：👀到时候是否还认识当前用户及其应用设置？🙃

**Comment by SeaHOH** [comment]
不要保存在这里，请换个方式。
因为这个命令范围涉及过大，我把你这个编辑删除了。
