### ISSUE TITLE
x-tunnel登录上去总需要半天时间，有时候登不上去，登上去了过一会又掉了，打开的网页也不是太稳定，怎么办。

### ISSUE THREAD

**Issue by katyuan88** [XX-net/XX-Net#10923]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
其它几条通道不是很稳定，建议开启 IPv6 使用 gae 作为 X-Tunnel 的 front，增加总体稳定性。

**Comment by milanthree** [comment]
经常会get_front fail报警

**Comment by SeaHOH** [comment]
是的，通道不太稳定。
删除 data 目录的 *_ip_list.txt 和 good_ip.txt 重新运行会有一点改善。

**Comment by SeaHOH** [comment]
请尝试 3.12.4，并开启 gae_proxy 模块。
