### ISSUE TITLE
IPv6总是动不动自己就断开了，wiki里面的步骤我都走了，用GAE也能正常一会，但是不一会就自己掉了

### ISSUE THREAD

**Issue by superdopenoob** [XX-net/XX-Net#10927]

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10919#issuecomment-396069177 👀臭大街法则

**Comment by superdopenoob** [comment]
那位兄弟给的网址没法用。。。。。。。http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting
