### ISSUE TITLE
× 3.12.1 更新到3.12.2时，出错。

### ISSUE THREAD

**Issue by xpf7622** [XX-net/XX-Net#10921]
12.2.1 更新到12.2.2时，出错。提示：Download Checksum Fail. 咋回事？
windows 10.

**Comment by SeaHOH** [comment]
刷新 XX-Net UI，重新下载。

**Comment by YJ0** [comment]
@SeaHOH 不行，行不通，有下载地址吗？

**Comment by SeaHOH** [comment]
releases 页面 3.12.2
sha256：9477ED60C31A3ED0CE98D0728A232ACAFFFB5BBCF2350810D4282D2E41EB00E8

**Comment by nickwenchester** [comment]
不管是自动更新或者手动管理都升级不了
