### ISSUE TITLE
xx-net3.11以后的版本IP数下掉，滚回3.10.4就好了

### ISSUE THREAD

**Issue by kk363109309** [XX-net/XX-Net#10920]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by fenghua35** [comment]
3.10.4版本可以说是最经典的版本了,我一直都在用。IP多、延迟低、速度快。比其它版本好太多。

**Comment by kk363109309** [comment]
是啊，关键是我经常下载视频，其他版本的总是下载视频不全，草草结束。
