### ISSUE TITLE
能翻墙，但为什么ping出现请求超时

### ISSUE THREAD

**Issue by kaoson** [XX-net/XX-Net#10924]
1. test-ipv6.com测试只有一项经常不正常，即：
**无域名 IPv6 连接测试 失败**

2. 在cmd或Windows PowerShell中ping任何IPV6的地址出现**请求超时**！

PS C:\WINDOWS\system32> ping ipv6.google.com
正在 Ping ipv6.l.google.com [203.98.7.65] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。
203.98.7.65 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

PS C:\WINDOWS\system32> ping -6 ipv6.google.com
正在 Ping ipv6.l.google.com [2404:6800:4005:802::200e] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

3. WLAN状态IPV6连接显示为**无网络访问权限**。

4. **翻墙基本正常**，只是chrome搜索时，会时不时的使用**ipv4.google.com**开头的域名，导致搜索失败，出现如下提示：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

IP address: 35.187.132.29
Time: 2018-06-11T17:29:28Z
URL: https://www.google.com/search?newwindow=1&hl=en&biw=1280&bih=677&ei=VKkeW_vWDMiMjwScgYqoDg&q=xx-net+ping+%22%E8%AF%B7%E6%B1%82%E8%B6%85%E6%97%B6%22++site%3Agithub.com&oq=xx-net+ping+%22%E8%AF%B7%E6%B1%82%E8%B6%85%E6%97%B6%22++site%3Agithub.com&gs_l=psy-ab.12...0.0.0.2082516.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.ivV3wsipBOY

**Comment by FirstJavaMaster** [comment]
xx-net不支持ping

**Comment by kaoson** [comment]
@FirstJavaMaster 是么，那test-ipv6.com测试出现“**无域名 IPv6 连接测试 失败**”是怎么回事呢？还有WLAN状态IPV6连接显示为“**无网络访问权限**”，这个咋解决？

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/41271247-0d3fb450-6e42-11e8-9957-0ff06b31c4fa.png)
还有WLAN状态IPV6连接显示为“无网络访问权限”，这个咋解决？——使用XX-Net 正常啊，需要解决么，除非你的网络有原生IPv6（而不是现在的IPv4👀）

**Comment by FirstJavaMaster** [comment]
@kaoson 
使用xx时总是要把网络和共享中心里,对应网络适配器中的IPV6协议关掉的:[Win10 不定时 IPv6 通道 Fail，XX-NET中断连接](https://github.com/XX-net/XX-Net/issues/8709).防止此功能和teredo抢夺网络通道.
关掉IPV6协议后,网络状态IPV6连接自然就显示为“无网络访问权限”,这是正常现象,不会影响xx的功能.
基本设置到此步就可以了,不过如果非要让IPV6显示正常的话,需要做更多配置,暂时没有研究过.

至于ping命令为什么不能用,应该是更深层的问题了.考虑到"又不是不能用"以及"IPV6正在推广,将来会可以通过正常渠道(直接从服务商那里获取)",所以没有深究

**Comment by SeaHOH** [comment]
只要不影响你们使用，就不要纠结这么多。
因为影响因素太多，费力找出来有没啥大用。

**Comment by kaoson** [comment]
@FirstJavaMaster 我是想在windows下弄个纯IPV6环境，即IPV6 only环境，有没有办法？需要路由器支持吗？对这些东西很外行，请多赐教。

**Comment by SeaHOH** [comment]
纯 IPv6 需要运营商支持，你的支持吗？
