### ISSUE TITLE
【mac】双击start，出现XX-Net version:3.12.2 Run XX-Net in background.不出现导航栏，无法打开配置页面

### ISSUE THREAD

**Issue by AnthonyAn** [XX-net/XX-Net#10922]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
最新版本

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
查过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
无法打开

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
上传 data/launcher/launcher.log 文件看看

**Comment by AnthonyAn** [comment]
已经解决了，用python2.7手动运行就可以了。

**Comment by SeaHOH** [comment]
10908
如果你安装有 python3，可以配置 alias python2。

**Comment by dwalkertb** [comment]
在xx-net文件夹下，没有发现data文件夹，更没有data/launcher/launcher.log文件，版本为最新的3.12.10
