### ISSUE TITLE
大佬我从3.10.8转回3.10.4以后 出现了dormant的问题

### ISSUE THREAD

**Issue by liushuiguadanbo** [XX-net/XX-Net#10938]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

IPV6 一直显示Fail  然后Teredo里一直显示 dormant是怎么回事I呀

**Comment by SeaHOH** [comment]
建议升级测试版，windows 可根据页面指示自助开启 IPv6。
