### ISSUE TITLE
浏览器配置好代理，XX-NET进不了起始页面，老版新版都是一直显示失败，如何破解？

### ISSUE THREAD

**Issue by langzc520** [XX-net/XX-Net#10930]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
已经是最新版XX-Net-3.12.1

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看过无解

如题：浏览器配置好代理，XX-NET进不了起始页面，老版新版都是一直显示失败，如何破解？

![image](https://user-images.githubusercontent.com/13818772/41329322-9b5c95b0-6eff-11e8-9510-a59ea1dcca85.png)

**Comment by SeaHOH** [comment]
确保代理设置正确
https://github.com/XX-net/XX-Net/wiki/How-to-use

**Comment by langzc520** [comment]
代理设置是正确的，进程中有 pythonw.exe.主页还是显示不了。

**Comment by SeaHOH** [comment]
你截个代理设置的图看看

**Comment by langzc520** [comment]
![tim 20180613170111](https://user-images.githubusercontent.com/13818772/41341155-9d8bf3e0-6f2b-11e8-8429-a45bb5293c5f.png)

**Comment by SeaHOH** [comment]
能访问其它网站不？
看看端口是否正确监听
Windows
netstat -nao | findstr "0.0.0.0:8085"
Linux
netstat -pan | grep 8085

**Comment by langzc520** [comment]
其他网站都是正常的，很奇怪更新到chrome67最新版，再更新XX-NET最新版就不行了。
 TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       536
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:5040           0.0.0.0:0              LISTENING       7564
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING       688
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING       1424
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING       1212
  TCP    0.0.0.0:49669          0.0.0.0:0              LISTENING       3152
  TCP    0.0.0.0:49670          0.0.0.0:0              LISTENING       760
  TCP    0.0.0.0:49673          0.0.0.0:0              LISTENING       768
  TCP    127.0.0.1:1080         0.0.0.0:0              LISTENING       11844
  TCP    127.0.0.1:8085         0.0.0.0:0              LISTENING       11844
  TCP    127.0.0.1:8086         0.0.0.0:0              LISTENING       11844
  TCP    127.0.0.1:8087         0.0.0.0:0              LISTENING       11844
  TCP    127.0.0.1:51175        127.0.0.1:8086         SYN_SENT        2608
  TCP    192.168.226.31:139     0.0.0.0:0              LISTENING       4

**Comment by SeaHOH** [comment]
换个浏览器能用吗？

**Comment by langzc520** [comment]
我用Firefox试试

**Comment by SeaHOH** [comment]
杀死 python 进程，重启试试。

**Comment by langzc520** [comment]
杀死 python 进程，重启试试，各种方法都是试了，以前每次更新都没有问题，目前mac没有更新还可以正常使用。更新的两台pc都不行了。

**Comment by SeaHOH** [comment]
你说的是哪个 issuse，没找到，引用一下。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/41367688-5122c83e-6f72-11e8-9712-bcf1975de5a8.png)
😜或许这“3个资源未加载”中就有 127.0.0.1 等你决定走“直接连接”呢
翻帖子看有网友使用switchomega里的情景模式只有GAE-Proxy可行，其他模式下XXNET都显示“请检查浏览器代理设置”👀很可能有“某资源 *.deja.com 未加载” 走GAE-Proxy 即🆗

**Comment by SeaHOH** [comment]
如果修改过情景模式才可能，一般没人改吧，改了也会说出来。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10927#issuecomment-396661097 👀臭大街法则

**Comment by SeaHOH** [comment]
使用 Teredo 必须开启防火墙。
把出站连接放行即可，还有不要修改自带核心规则。

**Comment by langzc520** [comment]
![tim 20180614120102](https://user-images.githubusercontent.com/13818772/41394075-2f331c6a-6fdb-11e8-9052-5f69e6848b50.png)

**Comment by langzc520** [comment]
![image](https://user-images.githubusercontent.com/13818772/41394259-ef662522-6fdb-11e8-9b3d-326efa27a6c6.png)

**Comment by SeaHOH** [comment]
对了，没啥其它问题。
防火墙不能忘，这个算常识吧。

题外话一下，访问测试 ipv6-test 要直连才能看出效果，你现在测试的是 GAE 代理出口。

**Comment by langzc520** [comment]
直接连接不行，检测不到ipv6

**Comment by langzc520** [comment]
对，就是Win10最新防火墙的问题，没有放行python，谢谢你耐心解答。
