### ISSUE TITLE
Firforx配置了Omega，只有firefox能翻墙，Chrome无法访问，是不是没有正确开启全局代理？

### ISSUE THREAD

**Issue by Tatamethues** [XX-net/XX-Net#10931]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

版本3.12.2
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
后台管理页面全部显示正常，但是只能从firefox翻墙，chrome无法使用。貌似没有成功设置全局代理
![screenshot_20180613_132642](https://user-images.githubusercontent.com/34636866/41331823-9de4df82-6f0d-11e8-8cd6-bc158f8a80ff.png)

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/How-to-use

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/41331839-ba0278f0-6f0d-11e8-8ed1-1ab932829637.png)
![default](https://user-images.githubusercontent.com/37962734/41331884-fd7ffddc-6f0d-11e8-89b7-e1ca7beb2541.png)

**Comment by SeaHOH** [comment]
![1528868100015](https://user-images.githubusercontent.com/8470820/41332037-94f46d3a-6ecb-11e8-8ab1-eda1e0b60fb8.png)

**Comment by Tatamethues** [comment]
@SeaHOH  我的意思是不是系统代理有问题？因为终端里下载一些被墙的东西仍然会出错。这个问题应该不是浏览器的关系吧

**Comment by SeaHOH** [comment]
导入配置文件！

**Comment by Tatamethues** [comment]
@SeaHOH 额，可能我没说清楚，我chrome安装了omega是可以翻墙的，但是代理只局限在浏览器，没有变成系统代理。

**Comment by SeaHOH** [comment]
自己看 wiki，你的问题都有说明。
