### ISSUE TITLE
XX-Net有IOS版本吗？

### ISSUE THREAD

**Issue by Simpleness123** [XX-net/XX-Net#10948]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
没有

**Comment by Simpleness123** [comment]
现在用iPad，用不了好难受啊

发自我的 iPad

**Comment by SeaHOH** [comment]
虽然没有 ios 版本，但是就像所有代理一样，可以运行在其它设备上，没必要非放在本机。

**Comment by gggccc44** [comment]
goagent時代有過，需越獄，當時挺好用

現在嘛，沒電腦的話，ios還是用小火箭之類吧，或者弄個梅林之類的路由器
