### ISSUE TITLE
ipv6 突然凉

### ISSUE THREAD

**Issue by 201585052** [XX-net/XX-Net#10946]
我们学校教育网是有ipv6的 然后照着mac配置isatop那一套
IP4="我的IPv4地址" # 这里不能有空格

sudo ifconfig gif0 create
sudo ifconfig gif0 tunnel $IP4 166.111.21.1
sudo ipconfig set gif0 MANUAL-V6 2402:f000:1:1501:200:5efe:$IP4 64
sudo route add -inet6 ::/0 -interface gif0
（当然方法一也试过了），
本来是可以上外网的，也上了一阵子了，今天突然就不好使了，可能是隧道的问题？还是我们学校ipv6突然有问题还是？？？orz，还是我弄错了
求大佬指教～不胜感激

**Comment by SeaHOH** [comment]
不是很懂，不过还可以用其它隧道，比如 miredo。

**Comment by 201585052** [comment]
自己搭vps 有教程吗？

**Comment by 201585052** [comment]
mac 弄miredo的教程好像 不太懂55555

**Comment by SeaHOH** [comment]
vps 和 miredo 都有教程，你在这里或谷歌搜索都行。

**Comment by 201585052** [comment]
谢谢～

**Comment by SeaHOH** [comment]
关闭后仍可回复
