### ISSUE TITLE
win10 ipv6不好用，测试teredo信息如下

### ISSUE THREAD

**Issue by yu0425** [XX-net/XX-Net#10947]
qualified: True
NAT type: restricted
best server is: win10.ipv6.microsoft.com.

**Comment by yu0425** [comment]
Jun 17 19:49:54.266 - [INFO] xxnet_version:3.12.2

Jun 17 19:49:54.267 - [INFO] server 127.0.0.1:1080 started.

Jun 17 19:49:54.267 - [INFO] Socks5 server listen:127.0.0.1:1080.

Jun 17 19:49:56.945 - [DEBUG] x_tunnel force update info

Jun 17 19:50:01.975 - [WARNING] get_front fail

Jun 17 19:50:07.979 - [WARNING] get_front fail

Jun 17 19:50:13.983 - [WARNING] get_front fail

Jun 17 19:50:19.988 - [WARNING] get_front fail

Jun 17 19:50:25.994 - [WARNING] get_front fail

Jun 17 19:50:26.994 - [WARNING] api:/login fail:status:602 t:30

Jun 17 19:50:40.676 - [DEBUG] x_tunnel force update info

Jun 17 19:50:45.681 - [WARNING] get_front fail

**Comment by yu0425** [comment]
X tunnel也不好使。。。

**Comment by SeaHOH** [comment]
尝试删除 data 目录的 *_ip_list.txt 和 good_ip.txt，然后重新运行 XX-Net。
