### ISSUE TITLE
ipv6已经三天start pending，freegate却480p不卡

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#10953]
云南大理电信ipv6已经三天start pending，freegate却480p不卡，没想到自由门的速度已经这么牛了！

![snap1](https://user-images.githubusercontent.com/19205130/41531020-a32cdc54-7324-11e8-89d2-550ae26e5587.png)

**Comment by SeaHOH** [comment]
你肯定没重启过系统

**Comment by GoodSake** [comment]
禁用网卡再启用就好了，只是乘机看看别的软件发展的怎么样了，哈哈。每天40GB下载youtube还是得GAE啊。

![snap2](https://user-images.githubusercontent.com/19205130/41607794-729a1ec6-7419-11e8-9fad-7c86aad1209c.png)

**Comment by no-name2017** [comment]
赶紧试试自由门先，不过好像确实有些地区使用自由门速度很快，一直都这样
