### ISSUE TITLE
突然之间xx-net下用firefox访问任何网站都出现“您的连接并不安全”

### ISSUE THREAD

**Issue by imudie** [XX-net/XX-Net#10954]
突然之间的意思是“十分钟前还可以，现在不行”。
不管是“全局PAC”还是“全局GAE”，访问谷歌、youtube甚至百度，都会出现“您的连接并不安全”。
一下操作均无法恢复正常：
1，删除浏览器CA证书并且重新导入。
2，删除date里的ca证书后重新生成再导入浏览器。
3，彻底重装火狐。
PS.我使用的xx-net版本比较老旧，为3.6.13。一直都畅通无阻，今天突然梗塞，让人悲痛。
请高手们指点一下有什么招可以救这只火狐。

目前用chrome依然十分流畅，只是有时候需要下载一点youtube的视频，用火狐比较方便。

**Comment by SeaHOH** [comment]
重新导入火狐证书的正确方法：
1. 删除旧证书
1. 重启火狐
1. 导入新证书

**Comment by AnyWAT** [comment]
👀试试：菜单——帮助——以安全模式重新启动——禁用所有扩展。。。

**Comment by imudie** [comment]
@SeaHOH  没用啊。无数次操作了，刚才看了您的回复后不死心又操作一次，显示：
**建立安全连接失败

连接 www.google.com.hk 时发生错误。 对等端的证书有一个无效的签名。 错误代码: SEC_ERROR_BAD_SIGNATURE**

**Comment by imudie** [comment]
@AnyWAT 试过了，一样显示：

建立安全连接失败

连接 www.google.com.hk 时发生错误。 对等端的证书有一个无效的签名。 错误代码: SEC_ERROR_BAD_SIGNATURE

**Comment by imudie** [comment]
感谢楼上各位
我换成3.11.15，就正常了。
依然一头雾水，但是对于技术菜鸟来说，只能这样了。

**Comment by zanewayne78** [comment]
自签证书中间好像换过一次，好久不用了不太清楚

**Comment by AnyWAT** [comment]
貌似换汤不换药（仅文件名有变而证书实质未变？），以3.8.5与3.8.6为界
