### ISSUE TITLE
XX net能否在原生ipv6和隧道之间自由切换？

### ISSUE THREAD

**Issue by fredericky123** [XX-net/XX-Net#10958]
RT,由于经常需要在原生ipv6和隧道之间的网络环境中使用，xx net能否实现首先自动检测是否有原生ivp6，有的话就用原生ipv6，没有的话再走隧道？
非常感谢

**Comment by SeaHOH** [comment]
3.12.2 的启用命令设置了你要求的优先级。

**Comment by fredericky123** [comment]
多谢海少！现在还停留在3.11.15,升级试试！
