### ISSUE TITLE
X-TUNNE连不上nicovideo

### ISSUE THREAD

**Issue by 10lumiya10** [XX-net/XX-Net#10966]
![image](https://user-images.githubusercontent.com/36228639/41658308-8f1640a2-74c8-11e8-8839-1b50370a6c18.png)

"server_host": "jp1.xx-net.net"   选日本线路时602
![image](https://user-images.githubusercontent.com/36228639/41658464-feec80bc-74c8-11e8-887b-5b8c1021cfb4.png)

xx网速太慢加载不了，想看nico生放怎么办

**Comment by xxnet** [comment]
​jp1 服务器出问题了， 已经重启，谢谢反馈。

**Comment by 10lumiya10** [comment]
还是602啊...

**Comment by xxnet** [comment]
​确实有问题，再试试，应该好了。

**Comment by 10lumiya10** [comment]
话说为什么niconico用X-TUNNE不换日区就上不去啊

**Comment by xxnet** [comment]
​这个网站限定了日本ip才能上

**Comment by SeaHOH** [comment]
这没必要解释吧，都能看生配信，难道还看不懂网站提示。
