### ISSUE TITLE
"客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新"是什么意思？

### ISSUE THREAD

**Issue by sysserkl** [XX-net/XX-Net#10969]
是指服务器端需要重新部署吗？

**Comment by SeaHOH** [comment]
你为什么要单独发个问题？
就是字面意思
客户端是 3.11.12 之前的版本不用更新服务端
服务器是 3.3.2 之前的版本不用更新服务端

**Comment by SeaHOH** [comment]
不过这都不重要了，因为这个测试版已经过期了。
我们正在不断改进，请关注最新版本。
