### ISSUE TITLE
视频问题

### ISSUE THREAD

**Issue by gdsteven** [XX-net/XX-Net#10965]
google driver视频在线可以播放，但下载回来后播放一部分后就不动了，以前版本,视频下载回来都正常的,应该不是视频本身问题，因为都是同样的制作方法压制的。

**Comment by SeaHOH** [comment]
版本、日志

**Comment by gdsteven** [comment]
3.11.10版

**Comment by SeaHOH** [comment]
没有日志分析不了

**Comment by SeaHOH** [comment]
先关闭，如果你找到日志了，也可以直接发在这里。

**Comment by gdsteven** [comment]
https://drive.google.com/drive/folders/1hInQWBccfSlZj4F0RzSfsZOhk0VnxaaX 这个地址，第七集时候下回来都是正常的，后面貌似XX-NET自动升级了，下载回来只能播一部分就不动了，不知是否视频问题，你可以试试看
