### ISSUE TITLE
8086的pac如何共享

### ISSUE THREAD

**Issue by luweitest** [XX-net/XX-Net#10961]
查看过 Wiki 
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
没有提到怎么设置，config.py里也没有。以前可以在manual.ini里的[pac]段设置的。

**Comment by xiaozijun** [comment]
你要怎么共享？是在Lan里面吗？

**Comment by luweitest** [comment]
是的，像8087一样改成在0.0.0.0监听

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/允许其它设备使用代理

**Comment by luweitest** [comment]
可以了，谢谢 SeaHOH！看来这个开关的文字可以修改一下
