### ISSUE TITLE
尚未建立连接      等待扫描IP，建议开启IPv6。  IPv6 IP数 | 0 

### ISSUE THREAD

**Issue by QGB** [XX-net/XX-Net#10975]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | OK
IPv4 IP数 | 0
IPv6 IP数 | 0
XX-Net 状态 | 工作
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 55

netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.2.136:52187
外部 NAT 映射    : 222.247.147.55:21879

**Comment by QGB** [comment]
IPv4 域名连接测试 |   | 成功 (1.947s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 失败 (0.878s)
双栈域名连接测试 |   | 成功 (1.610s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (1.396s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (1.094s) 使用 ipv4
无域名 IPv6 连接测试 |   | 成功 (1.184s) 使用 ipv6 Teredo
IPv6 大数据包传输测试 |   | 失败 (0.847s)
测试运营商 DNS 是否接入 IPv6 |   | 失败 (0.864s)
查询 IPv4 运营商 |   | 成功 (1.890s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 失败 (2.041s)

**Comment by SeaHOH** [comment]
修改路由器 NAT 设置，保证端口映射工作正常，最好能将使用 teredo 的机器 IP 设置为 DMZ。
是使用中的路由器，用作交换机（不使用 WAN 口）的路由器不算。

**Comment by zfcarpe** [comment]
更新到最新版本。
关闭teredo, 启动isatap（如果是教育网用户的话）。
我的问题是这么解决的

**Comment by SunYufei** [comment]
我从3.8.7更新到3.12.2后就能连上了
