### ISSUE TITLE
ipv6突然用不了了

### ISSUE THREAD

**Issue by houhuliang** [XX-net/XX-Net#10973]
昨天还是好的，今天突然发现不能用了

Property | Value
-- | --
XX-Net Version | 3.4.0
Python Version | 2.7.3
OpenSSL Version | 0.12 TLSv1 h2:no
System Platform | x86_64, Linux-3.2.0-29-generic-x86_64-with-Ubuntu-12.04-precise
OS System | Linux
OS Version | #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012
OS Release | 3.2.0-29-generic
OS Detail | Dist:Ubuntu; Version:12.04; ID:precise
Language | en_US
Architecture | 64bit,ELF
Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0

Jun 22 11:51:48.712 - [DEBUG] get ip:2a00:1e48:99:16::c t:703
Jun 22 11:51:48.928 - [DEBUG] connect 2a00:1e48:99:17::10 fail:[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')] cost:717 h:0
Jun 22 11:51:48.929 - [DEBUG] report_connect_fail network fail
Jun 22 11:51:48.929 - [DEBUG] get ip:2a00:1e48:1:f::e t:739
Jun 22 11:51:48.933 - [DEBUG] connect 2a00:1450:4011:1e::17 fail:[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')] cost:724 h:0
Jun 22 11:51:48.933 - [DEBUG] report_connect_fail network fail
Jun 22 11:51:48.934 - [DEBUG] get ip:2a00:1e48:1:26::e t:763
Jun 22 11:51:49.047 - [DEBUG] network is ok, cost:931 ms
Jun 22 11:51:49.212 - [DEBUG] get ip:2a00:1e48:99:17::13 t:726
Jun 22 11:51:49.428 - [DEBUG] connect 2a00:1e48:99:16::c fail:[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')] cost:715 h:0
Jun 22 11:51:49.428 - [DEBUG] report_connect_fail:2a00:1e48:99:16::c
Jun 22 11:51:49.429 - [DEBUG] get ip:2607:f8b0:4016:5::c t:2828
Jun 22 11:51:49.667 - [DEBUG] connect 2a00:1e48:1:f::e fail:[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')] cost:738 h:0

**Comment by Elvisass** [comment]
+1
IP数直接掉到1或者0，现在test-ipv6都ping不通……

**Comment by AnyWAT** [comment]
XX-Net Version | 3.4.0 😱最新3.12.2
现在test-ipv6都ping不通……🙃多此一举
👍 #10919 臭大街法则👀

**Comment by xxnet** [comment]
('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed'
google升级了证书。

你的版本太老了，请升级到最新版本
