### ISSUE TITLE
Gmail更新新版了，但是多刷新几次看几个邮件就会出现重新定向报错

### ISSUE THREAD

**Issue by UltraDWS** [XX-net/XX-Net#10978]
如题，Gmail升级新版了好像对新版3.12.2兼容不太友好，多刷新几次就报错重新定向链接太多，需要清理cookies，清理完用一会邮箱又会出现这个问题。

**Comment by SeaHOH** [comment]
Gmail 无需刷新，只要页面打开就会自动更新数据。

**Comment by Eri5Ch** [comment]
在用3.11.15 发现同样的错误 Gmail打开不了 ...

**Comment by xxnet** [comment]
新版gmail 不能用Direct。
要把​mail.google.com 从直连中去除

**Comment by agutools** [comment]
Xndroid中怎么设置呢？

**Comment by SeaHOH** [comment]
已发布 3.12.4 修复

**Comment by horigen** [comment]
在3.12.11遇到同样的重新定向问题，尝试了很多方法无效，最后通过在config.json中加入如下代码解决：
"hosts_direct": [
    "accounts.google.com",
    "mail.google.com"
  ],
  "hosts_gae": [
  ]
