### ISSUE TITLE
请问为什么突然连接不了了

### ISSUE THREAD

**Issue by J-zin** [XX-net/XX-Net#10976]
Jun 22 16:05:09.805 - [DEBUG] connect 2a00:1450:401f:37::7 fail:timeout('timed out',)

Jun 22 16:05:09.805 - [DEBUG] report_connect_fail:2a00:1450:401f:37::7

Jun 22 16:05:10.145 - [DEBUG] connect 2a00:1450:4005:3::10 fail:timeout('timed out',)

Jun 22 16:05:10.145 - [DEBUG] report_connect_fail:2a00:1450:4005:3::10

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
试试删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
如果还是没用，估计就是干扰。

**Comment by J-zin** [comment]
等待扫描IP，建议开启IPv6。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by J-zin** [comment]
删除后重连结果如下：
等待扫描IP，建议开启IPv6。
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
我的ipv6测试结果如下：


发送自 Windows 10 版邮件应用

发件人: SeaHOH
发送时间: 2018年6月22日 16:18
收件人: XX-net/XX-Net
抄送: J-zin; Author
主题: Re: [XX-net/XX-Net] 请问为什么突然连接不了了 (#10976)

试试删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
如果还是没用，估计就是干扰。

**Comment by MaoJianwei** [comment]
这几天确实用不了了，教育网原生v6也用不了XX_NET了，GG...

**Comment by huanguolin** [comment]
+1

**Comment by AnyWAT** [comment]
👀试试臭大街法则😜 #10919

**Comment by dahai058** [comment]
我这里3.8.4昨天不能用了，升级3.12.2正常了。而且油管720p真意想不到。希望能稳定就好

**Comment by xxnet** [comment]
是google升级证书了，新版3.12.2 是OK的

**Comment by xxnet** [comment]
​已经推送 3.12.2 稳定版更新
