### ISSUE TITLE
没有PayPal账户，请问X-Tunnel支持虚拟货币支付吗？ETH，BTC等都可以

### ISSUE THREAD

**Issue by flyq** [XX-net/XX-Net#10974]
没有PayPal账户，请问X-Tunnel支持虚拟货币支付吗？ETH，BTC等都可以

**Comment by xxnet** [comment]
​比特币地址：1CJHmCuVAcDj2PNka6RDAHSWRb4RQSxXRC
转帐后，给 xxnet.dev@gmail.com 发邮件，告知x-tunnel 帐号
