### ISSUE TITLE
速度超慢几乎没法上，升级为最新版 3.12.2

### ISSUE THREAD

**Issue by viponedream** [XX-net/XX-Net#10972]
但是反倒不正常了。
ipv4  ip数为0
IPv6 IP数 才 45， 记得以前都有几百的。
现在根本就连不上。

XX-Net Version | 3.12.2

IPv4 状态 | OK
-- | --
IPv6 状态(如何开启) | OK
IPv4 IP数 | 0
IPv6 IP数 | 45
XX-Net 状态 | 工作
IP延迟 | 1072

**Comment by AnyWAT** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
IPv4 IP数 | 0
IPv6 IP数 | 500
XX-Net 状态 | 工作
IP延迟 | 265
连接池(帮助) | 新:0 h1:10 h2:2
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 169

**Comment by whhxmwhh** [comment]
换个轮子就会跑的快。

**Comment by zhencaihao** [comment]
我这里昨天晚上用着还不卡呢。今天就不好用了，打开状态一看ip就这么点了，原来有500个的，延迟也就300左右。
![qq 20180622114205](https://user-images.githubusercontent.com/19796493/41757124-a81e2678-7612-11e8-9801-776b58fc92f4.jpg)
