### ISSUE TITLE
youtube上面看视频好卡啊，720p以上根本没法看，有没有大神能帮帮忙

### ISSUE THREAD

**Issue by wssjp** [XX-net/XX-Net#10982]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

否
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
youtube上面看视频好卡啊，720p以上根本没法看

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by wssjp** [comment]
Jun 23 00:58:29.745 - [DEBUG] create_ssl update ip:2a00:1450:4001:45::9 time:796 h2:0 sni:nifty-state-207714.appspot.com, host:nifty-state-207714.appspot.com

Jun 23 00:58:29.856 - [DEBUG] create_ssl update ip:2a00:1450:4001:6b::7 time:729 h2:0 sni:nifty-state-207714.appspot.com, host:nifty-state-207714.appspot.com

Jun 23 00:58:30.561 - [DEBUG] create_ssl update ip:2607:f798:1e:1000::f time:1112 h2:0 sni:durable-footing-208016.appspot.com, host:durable-footing-208016.appspot.com

Jun 23 00:58:33.856 - [INFO] scan_ip add ip:2405:4800:100:4::13 time:703 h2:0

Jun 23 00:58:33.859 - [INFO] remove_slowest_ip:2607:f798:1e:1000::f handshake_time:901, fails:0

Jun 23 00:58:35.487 - [INFO] scan_ip add ip:2804:14d:10f9:1::d time:513 h2:0

Jun 23 00:58:35.490 - [INFO] remove_slowest_ip:2a00:1450:4001:45::9 handshake_time:796, fails:0

Jun 23 00:58:35.718 - [DEBUG] create_ssl update ip:2607:f8b0:4004:30::b time:730 h2:0 sni:floor-boot-sleep.org, host:

Jun 23 00:58:36.731 - [DEBUG] create_ssl update ip:2a00:1450:400d:7::17 time:858 h2:0 sni:durable-footing-208016.appspot.com, host:durable-footing-208016.appspot.com

Jun 23 00:58:37.040 - [INFO] scan_ip add ip:2001:56a:2:8::11 time:420 h2:0

Jun 23 00:58:37.042 - [INFO] remove_slowest_ip:2a00:1450:400d:7::17 handshake_time:858, fails:0

Jun 23 00:58:37.253 - [INFO] scan_ip add ip:2804:a8:8000:801::d time:587 h2:0

Jun 23 00:58:37.256 - [INFO] remove_slowest_ip:2607:f8b0:4004:30::b handshake_time:730, fails:0

Jun 23 00:58:38.320 - [INFO] scan_ip add ip:2a00:1e48:1:35::d time:845 h2:0

Jun 23 00:58:38.323 - [INFO] remove_slowest_ip:2a00:1e48:1:35::d handshake_time:845, fails:0

**Comment by SeaHOH** [comment]
#10963
