### ISSUE TITLE
在远程无X的linux上部署时，能否在log中或者直接给出 authenticate url ?

### ISSUE THREAD

**Issue by cicite** [XX-net/XX-Net#10983]
在远程无X的linux上部署时, 没有X，不能直接弹出浏览器的授权的对话框，需要在本地用打开一个浏览器授权，但是找到远端log部署时的那个授权url很麻烦，能够直接在8085中给出部署时用的那个url授权链接？

**Comment by SeaHOH** [comment]
本地部署一次就好
