### ISSUE TITLE
IPV6 是不是也全歇了!  大伙安好?

### ISSUE THREAD

**Issue by GerGitHub** [XX-net/XX-Net#10984]
# IPV6 是不是也全歇了？？？

### XX扫了一天 ,得到“good ip num:0 , bad ip num:0”

+ 从2018-6-20开始，之前还能10个左右的good ip

**Comment by SunYufei** [comment]
我更新到3.12.2后就能扫到新IP了

**Comment by GoodSake** [comment]
我的3.7.5似乎是ssl证书出问题了，换了3.12.2又一切都好了，哈哈哈！
