### ISSUE TITLE
[发布] 3.12.3 速度有所改善

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#10987]
## 新版改进：
* 修复智能路由中的硬编码端口
* 改进页面提示
* 改进证书导入 (win)
* 添加 teredo 组策略检查和重置 (win)
* 增大套接字接收缓冲 (连接带宽上限)
* 优化移动网络参数
* 其它小问题修复

---

主要是速度方面的改善，和针对适合 Xndroid 使用的参数做了单独修改。
其它还微调了几个参数。
证书可能会提醒一次，点击确定即可。

---

无法登录谷歌账户问题已在 3.12.4 中修复

**Comment by 308901951** [comment]
youbube明显快了，点开视频评论就开了，以前要等等

**Comment by no-name2017** [comment]
感谢海大，先下载测试看看

**Comment by beiking** [comment]
![qq 20180623170549](https://user-images.githubusercontent.com/12060194/41807929-0be3b05a-7709-11e8-9881-7d6b87301217.png)

3.12.3 开Gmail 提示，一致重试。

**Comment by xxnet** [comment]
刚才测试了，​mail.google.com 这个域名不能走Direct
大海你试试

**Comment by SeaHOH** [comment]
为什么我的就没事，奇怪，还有其他人出现这个错误吗？
![x2scrap2](https://user-images.githubusercontent.com/8470820/41810430-ae6788fe-76ed-11e8-8410-fdbd59229bef.png)

**Comment by SeaHOH** [comment]
@beiking 你先自己改下配置，我再看看。

**Comment by AnyWAT** [comment]
登录正常，只是无法使用新版😜
![default](https://user-images.githubusercontent.com/37962734/41810587-aafb32ec-7733-11e8-95dc-0967172aede8.png)

**Comment by SeaHOH** [comment]
刚完整试了下，无法登录 Gmail，但是登录后使用没问题。

**Comment by SeaHOH** [comment]
情况都不一样。。。

**Comment by AnyWAT** [comment]
@ncmon #10919

**Comment by beiking** [comment]
去掉直连后，
GMail
![111](https://user-images.githubusercontent.com/12060194/41815329-0a8f638e-779a-11e8-9816-339f7cb35570.png)
该网页无法正常运作
mail.google.com 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS

**Comment by yeezylife** [comment]
看YouTube速度明显变快了  自动清晰度都会选择更高的清晰度了  体验提升明显 coooool！

**Comment by Eri5Ch** [comment]
另外 从其他版本升到12.X版 需要更新服务器端吗???

**Comment by AnyWAT** [comment]
9494🙃

**Comment by Eri5Ch** [comment]
12.3反馈
1.服务器端从3.2.6(16年4月26日)版本开始就一直没有更新过 客户端一直更新 一直正常能用, 升级到此版本后google账号不能登陆,老提示cookie没有启用, ie也是同样的提示, 退回到11.15, 又正常了.
2.本版看youtube明显有好转, 只是有个断流问题, 黑屏1s左右, 视频又接上了.
3.gmail有打不开的现象, 具体楼上有反馈.

**Comment by SeaHOH** [comment]
这么说来 accounts 和 mail 必须一直才能通过安全验证。
然后，某些情况下直连无法验证。

看来要改回去。

**Comment by Eri5Ch** [comment]
我又重新下载了12.3 然后公共ID重新更新了服务端, 现在没有提示cookie错误,只是gmail提示错误,但是可以打开邮件
辛苦各位开发者
![capture](https://user-images.githubusercontent.com/12391921/41817258-e36b9cf2-77c9-11e8-8297-cd3a4409f136.JPG)

**Comment by SeaHOH** [comment]
@Eri5Ch 退出后还能再登录吗？

**Comment by XueTeng2** [comment]
速度提升很明显，感谢贡献！

**Comment by Eri5Ch** [comment]
我没敢退出去 暂时这么用着吧

youtube断流问题没有改善哦, 继续加油!谢谢你们...

**Comment by imldf** [comment]
3.12.3版本  Gmail 有问题  3.12.0版本没问题
![capture](https://user-images.githubusercontent.com/33856971/41819951-3273e714-77fc-11e8-8212-82a9d7e6a7cf.PNG)

**Comment by 308901951** [comment]
3.12.3谷歌帐号登录不了，你的浏览器似乎禁用了COOKIE

**Comment by SeaHOH** [comment]
晚上发个新版修复

**Comment by SeaHOH** [comment]
@yeezylife 麻烦你分别给几个两种情况的网址

**Comment by huangkio** [comment]
看youtuber的速度能到2m/s ?

**Comment by abigbone** [comment]
> ![g](https://user-images.githubusercontent.com/12060194/41807975-ab3819b6-7709-11e8-8b42-aac1fbdb2b4f.png)
> 
> 3.12.3 开Gmail 提示，一直重试。

我一直都不能打开gmail  ，已经2个月没收邮件了，除非走独立VPN 看验证内容。

**Comment by SeaHOH** [comment]
你难道都没升级么？
