### ISSUE TITLE
3.12IPv6一直顯示fail

### ISSUE THREAD

**Issue by okaylabababa** [XX-net/XX-Net#10990]
一直用3.11.10 一打開enable_ipv6.bat IPv6就會顯示ok 就基本能用
今天自動更新3.12 完全不能用了 IPv6一直顯示fail 怎麼也不行 高級那裡寫著IPv6已開啟 但IPv6一直顯示fail
這問題怎麼解決

**Comment by AnyWAT** [comment]
试试先禁用再启用网络？

**Comment by SeaHOH** [comment]
意思和楼上差不多，不过是在高级、隧道页面点击一次禁用、启用。
更新到 3.12.3 执行最好，有状态检测的修改。

**Comment by okaylabababa** [comment]
禁用 啟用 還是fail
![default](https://user-images.githubusercontent.com/32033614/41812298-f81635ee-7752-11e8-84f6-8bbb4f40e3cc.PNG)

**Comment by SeaHOH** [comment]
没看明白，这两张图中间除了版本变化还有什么其它操作吗？

**Comment by okaylabababa** [comment]
3.11.10就是打開enable_ipv6.bat就ok了
3.12掛了一晚上還是fail

**Comment by SeaHOH** [comment]
就是说你换回 3.11.10 后，又运行了一次 enable_ipv6.bat？

**Comment by 5yl2** [comment]
一模一样的问题。我的版本是3.11.10

3.11.10需要10-15分钟重新运行一下enable_ipv6.bat，但好歹运行后一直能用。换到3.12.3后完全挂了。

**Comment by Jakhun** [comment]
更新后出现类似问题 我用的是校园网原生IPV6 
版本3.11.10时，需要禁用本地连接的IPV6协议，不然IPV6会自动关闭。
更新到3.12后，一定要在本地连接开启IPV6协议才可以，即便开启了有时候也出现了FAIL的情况，需要在本地连接关闭再开启IPV6协议才可以。而3.11.10禁用本地连接IPV6协议后，就没出现FAIL的情况。

**Comment by okaylabababa** [comment]
不允行enable_ipv6.bat  3.11.10也是fail
