### ISSUE TITLE
升级到最新版3.12.2，发现chrome账户登录失效，而且无法登录，是怎么回事？

### ISSUE THREAD

**Issue by EliteOtaku** [XX-net/XX-Net#10992]
IPv4 状态 | OK
-- | --
IPv6 状态(如何开启) | OK
IPv4 IP数 | 0
IPv6 IP数 | 444
XX-Net 状态 | 工作
IP延迟 | 983
连接池(帮助) | 新:2 h1:51 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
IP扫描线程数(设置) | 200
=================
因为我最近用goproxy，昨天goproxy频繁出现握手加密超时后，怀疑被干扰了，就拿xxnet回来用，发现gmail无法登录，后来查找论坛，搞定了，但chrome浏览器无法登录ID了，尝试登录ID，点next后，出现

出了点问题
抱歉，出了点问题。请重试。

=================
我怀疑是不是accounts.google.com和xxnet哪里有冲突了，请指点一下，谢谢。

**Comment by EliteOtaku** [comment]
补充一下，Gmail不停提示错误 对不起…系统遇到问题 (#500)，而且无法显示邮件内容……

**Comment by EliteOtaku** [comment]
说无法加载您请求的内容

**Comment by EliteOtaku** [comment]
https://github.com/XX-net/XX-Net/issues/10860

按此条修改config.json后解决！

**Comment by Blucezhang** [comment]
为什么一直登录不上去呢？
