### ISSUE TITLE
xxnet和goproxy为何在观看youtbue时速度差别如此大？

### ISSUE THREAD

**Issue by EliteOtaku** [XX-net/XX-Net#10996]
首先，绝非是吹捧goproxy，我最早翻墙就是用xxnet的，后来因为自启动时，xxnet总需要点一下确定，感觉有点麻烦，刚好看到了goproxy(quic版)，就顺便试了下，发现goproxy观看youtube的速度异常流畅，我只是2M的小宽带，看youtube1080P的流畅程度，比看国内的视频网站还更流畅，简直不可思议。

而且，我给xxnet和goproxy配置的都是自己申请的APP ID，最近几天，goproxy一直显示握手加密超时故障，自己搜索了好久也没发现好的解决方案，就顺便回来试试xxnet，然后发现xxnet浏览网页依然么问题，可观看youtube的流畅还是有点问题，这中间到底有什么差异呢？能否请程序员稍微解释一下？谢谢。

**Comment by SeaHOH** [comment]
你用的是 teredo 隧道？受服务器和线路影响，有些网络建立的隧道质量太差，带宽很小。
还有就是套接字接收缓冲过小，限制了单连接的带宽，不过已经在 3.12.3 中增大了。
其它可能还有影响因素吧，比如 XX-Net 连接过多是否影响隧道稳定，你先前用的 IPv4 连接状况比较好之类。

**Comment by EliteOtaku** [comment]
是的，服务器是remlab的那个，我试试改为微软的，看看能否改善。

另外我一升级3.12.3测试版就报错，也不知道怎么回事

**Comment by EliteOtaku** [comment]
你好，修改ipv6服务器为win10.microsoft.com之后，观看速度有所提示，之前只有200-300k，现在可以有500-1000k，但不是特别稳定，已经可以比较流畅的看720P，我相当满足了，谢谢。

**Comment by EliteOtaku** [comment]
昨晚我升级时，确实有出错，但没有保留截图日志，因为刚好着急翻墙查资料，所有重新删除安装过了。刚刚又试了一下，已经正常无报错了。

**Comment by EliteOtaku** [comment]
另外，刚刚升级到3.12.3后，发现youtube的速度有进一步提升，已经可以达到2000-3000k了。

**Comment by wha4up** [comment]
goproxy貌似被作者删了？

**Comment by EliteOtaku** [comment]
是的，据说被喝茶了

**Comment by no-name2017** [comment]
不懂别乱说，Goproxy作者没被请喝茶，造谣可耻

**Comment by standritsu** [comment]
3.12.3我看youtube可以过万k，不过会看着看着突然停一下，然后又重新缓存
