### ISSUE TITLE
部分域名需要选择 *.google.com域名的google ip

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#110]
偶然发现的，比如 https://chart.apis.google.com/
chart.apis.google.com 使用了无效的安全证书。

该证书仅对下列名称有效：
……

Apr 05 09:43:59 - [DEBUG] tcp conn 210.245.14.182 time:78
Apr 05 09:44:00 - [DEBUG] FWD CONNECT chart.apis.google.com:443 with closed

https://210.245.14.182/ 的证书没有这个域名。版本1.7.1。

**Comment by xxnet** [comment]
证书是Google自己颁发的。
估计这个域名需要特别处理，经过GAE去访问才行。

2015-04-04 21:47 GMT-04:00 YFdyh000 <notifications@github.com>:

**Comment by yfdyh000** [comment]
并不是这样，估计是挑选IP时出现了问题，没有检查IP的证书覆盖范围。
Google也有很多种SSL证书的，有些IP的证书范围较小， https://www.google.com/ https://g.cn/ https://www.google.com.hk 等域名用的证书的覆盖范围（DNS可选名称）都有不同。
我访问 https://apis.google.com/ 遇到的那个IP的证书应该就没问题，它第一条是 *.google.com。而我遇到的这个IP第一条是google.com。

但也很奇怪，google.com不包括*.google.com吗，不知道是怎么定义的。

**Comment by xxnet** [comment]
你是对的，你可以试试提交一个修复。
谢谢！

在 2015年4月5日 上午10:11，YFdyh000 <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
有空我会试试的。
另外，建议善用右侧的Github Labels功能，把已确认的技术问题（Bug）、求助等区分开。

**Comment by xxnet** [comment]
谢谢提示，我还没有注意到这个功能，学习学习

2015-04-05 10:19 GMT-04:00 YFdyh000 <notifications@github.com>:

**Comment by xxnet** [comment]
刚才挂上ShadowSocks去访问，也是提示证书有问题。
从浏览器看颁发的证书，是google发给*.google.com，按道理有效的。
难道*只能匹配一级子域名，是Google的问题？

我试过Chrome和Firefox都是提示有问题。

**Comment by yfdyh000** [comment]
好像确实不是xx-net的问题，用ss的确也有问题。网上搜索 `https://chart.apis.google.com` 发现也有报告该问题的：
1. https://groups.google.com/forum/#!topic/google-maps-js-api-v3/ngFlTc5KH0k
2. http://security.stackexchange.com/questions/26049/chrome-ssl-warning-you-cannot-proceed-because-the-website-operator-has-request

具体原因还没弄懂，不知道第二个链接中第二个回答说的是否正确，只匹配一层。有可能是谷歌证书的问题，也许这服务就只提供http。[ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=chart.apis.google.com)也是报不匹配的，应该是谷歌方面的问题吧。

顺带一提，我是在Firefox的浏览器控制台中发现的这个错误。也许是Gmail调用的。

----
另外，可考虑依此做一个增强，可测试和选择指定证书名的模块结构，未来可用作测试其他网站的IP池（比如Github、比如Gmail的IMAP等端口）并选择一个最快的FWD（并较快的超时值）。

**Comment by xxnet** [comment]
有考虑过，但是性价比不高。

其他有足够ip的域名不多，很容易封锁。
只有google的ip足够多，最重要的是有GAE免费代理引擎。



在 2015年4月8日 上午3:03，YFdyh000 <notifications@github.com>写道：

**Comment by LGA1150** [comment]
chart.apis.google.com 并不包括在 *.google.com 内
作为取代，Google使用了 chart.googleapis.com
详情见 https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.json 第267行
