### ISSUE TITLE
[发布] 3.12.4 调整 gae_proxy 参数

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#11009]
## 新版改进：
* 修复 3.12.3 无法登录谷歌帐号
* 调整 gae_proxy 模块参数

---

这次参数调整是考虑到似乎针对 IPv6 隧道的干扰开始增多，
希望能改善这些用户的使用体验，
主要改变是降低了最大 IP 数上限。

对网络质量好的用户应该没有太多影响，
网络质量不佳的用户看**持续可使用时间**是否有所改善，失败警告是否减少。

觉得效果不好，也可以自己修改参数，希望大家测试下。
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

稳定版升级上来的用户，证书可能会提醒一次，点击确定即可。

**Comment by panpeach** [comment]
Android中，升级到3.12.4，速度很快，延时100，但IP总数只有100，请问在Android如何调整IP上限？

**Comment by yeezylife** [comment]
显示best server是win10.ipv6.microsoft.com  但是点更换teredo服务器会换成teredo.remlab.net
好像跟之前不一样 请问是有意为之吗

**Comment by SeaHOH** [comment]
不是，可能哪里出错了。
你复制日志或截张图我看看。

**Comment by AnyWAT** [comment]
@panpeach ？修改 data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/config.json

**Comment by yeezylife** [comment]
![1](https://user-images.githubusercontent.com/30175425/41859499-e1494248-78ce-11e8-9fa3-55d9565956fa.png)
![2](https://user-images.githubusercontent.com/30175425/41859506-e4a7452a-78ce-11e8-86da-d17c9da33386.png)
如图所示，我先点测试，跟之前一样best server是win10.ipv6.microsoft.com
然后我手贱点了次更换变成teredo.remlab.net了。。

**Comment by SeaHOH** [comment]
这样啊，这是正常的。
我还以为是同一次操作中出现了不一致的结果。

因为服务器延时可能会变化，尤其是你连续测试的时候。
你过几分钟再更换一次估计还能变化。
只要能用就不要在意。

**Comment by SeaHOH** [comment]
更换服务器时，无需先测试，直接点击更换就行。

**Comment by yeezylife** [comment]
好的，感谢回复。不瞒你说我这人有点强迫症

**Comment by yonghuming9** [comment]
### **嗯，这次版本V 3.12.4体验不错。**
### **开网页，看youtube流畅。**
### **给赞。**
👍👍

**Comment by xc1988** [comment]
还是要每天重启路由器才能脸上IPV6 囧。

**Comment by whhxmwhh** [comment]
Teredo 隧道  会休眠   要怎么处理。。才不让她睡着了？

**Comment by AnyWAT** [comment]
Teredo 隧道 会休眠？😱运行（对你来说绝不是第一次见到的🙃）以下bat（内容）
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by okaylabababa** [comment]
還是fail 究竟3.11.10和3.12有什麼分別

**Comment by okaylabababa** [comment]
![default](https://user-images.githubusercontent.com/32033614/41892151-b5a8287c-7949-11e8-9cd2-7e6b40994346.PNG)
連接明明說合格 但還是fail

**Comment by SeaHOH** [comment]
休眠状态只需要有 IPv6 连接发出即会恢复连接服务器，通常出现在 XX-Net 刚启动时。

IP 数不是关键，主要看使用体验有没有降低，如果比之前更差，请说一下。

3.11.10 和 3.12.2 的区别是 IPv6 隧道的优先级稍有不同，现在的是：
原生（非本地、即使无法访问公网） > 6to4 > teredo

**Comment by SeaHOH** [comment]
@okaylabababa 你的网络大概是什么配置？

**Comment by okaylabababa** [comment]
我也不知道什麼配置 中國移動10m吧

**Comment by SeaHOH** [comment]
@okaylabababa 尝试调整优先级
```
netsh interface ipv6 add prefixpolicy 2001::/16 25 6
netsh interface ipv6 set prefixpolicy 2001::/16 25 6
netsh interface ipv6 add prefixpolicy 2002::/16 30 2
netsh interface ipv6 set prefixpolicy 2002::/16 30 2
netsh interface ipv6 add prefixpolicy 2001::/32 35 5
netsh interface ipv6 set prefixpolicy 2001::/32 35 5
```

**Comment by shpherd** [comment]
以前3.10.4使用，昨天发现不扫描IP了。今天升级3.12.4，XX-NET不能启动，好像要修改什么文件的启动，刚才在WIKI没找到，请给出修改链接。

**Comment by shpherd** [comment]
Jun 26 20:39:20.371 [launcher][INFO] use build-in openssl lib
Jun 26 20:39:20.372 [launcher][INFO] start XX-Net 3.12.4
Jun 26 20:39:20.373 [launcher][DEBUG] start confirm_xxnet_exit
Jun 26 20:39:21.374 [launcher][DEBUG] good, xxnet:8085 clear!
Jun 26 20:39:21.375 [launcher][DEBUG] finished confirm_xxnet_exit
Jun 26 20:39:22.391 [launcher][ERROR] start module gae_proxy fail:Extra data:
ne 6 column 1 - line 21 column 2 (char 119 - 282)
Jun 26 20:39:22.396 [launcher][ERROR] Except stack:Traceback (most recent call
ast):
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\launcher\module_in
.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['lo
l', 'start'], -1)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\__
it__.py", line 2, in <module>
    import apis
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\ap
.py", line 2, in <module>
    from front import front, direct_front
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\fr
t.py", line 7, in <module>
    import check_local_network
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\ch
k_local_network.py", line 28, in <module>
    from config import config
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\co
ig.py", line 232, in <module>
    config = Config(config_path)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\co
ig.py", line 180, in __init__
    self.load()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\co
ig.py", line 183, in load
    super(Config, self).load()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\n
rch\front_base\config.py", line 88, in load
    super(ConfigBase, self).load()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\n
rch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\j
n\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\j
n\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 6 column 1 - line 21 column 2 (char 119 - 282)

Jun 26 20:39:22.401 [launcher][ERROR] launcher except:ValueError('Extra data:
ne 6 column 1 - line 21 column 2 (char 119 - 282)',)
Jun 26 20:39:22.404 [launcher][ERROR] Except stack:Traceback (most recent call
ast):
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\launcher\start.py"
line 247, in <module>
    main()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\launcher\start.py"
line 226, in main
    module_init.start_all_auto()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\launcher\module_in
.py", line 113, in start_all_auto
    start(module)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\launcher\module_in
.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['lo
l', 'start'], -1)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\__
it__.py", line 2, in <module>
    import apis
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\ap
.py", line 2, in <module>
    from front import front, direct_front
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\fr
t.py", line 7, in <module>
    import check_local_network
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\ch
k_local_network.py", line 28, in <module>
    from config import config
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\co
ig.py", line 232, in <module>
    config = Config(config_path)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\co
ig.py", line 180, in __init__
    self.load()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\gae_proxy\local\co
ig.py", line 183, in load
    super(Config, self).load()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\n
rch\front_base\config.py", line 88, in load
    super(ConfigBase, self).load()
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\n
rch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\j
n\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\64bit software\chrome plugins\XX-Net\code\3.12.4\python27\1.0\lib\j
n\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 6 column 1 - line 21 column 2 (char 119 - 282)

Press Enter to continue...

**Comment by SeaHOH** [comment]
@shpherd 配置文件错误，请删除错误的 config.json。

**Comment by shpherd** [comment]
谢谢，搞定

**Comment by okaylabababa** [comment]
@SeaHOH 在哪裡輸入這些東西

**Comment by SeaHOH** [comment]
管理员权限的命令行

**Comment by yonghuming9** [comment]
发现重要问题，V 3.12.4过一会IPv6就自动没了。
怎么多年第一次出现这样的问题。

速度倒是挺快，但IPv6间隙断开是个大问题。
还是要从新退回安装XX-Net-3.12.0版本，这个版本不会自动断开IPv6。

你仔细参考一下这个版本

**Comment by XndroidDev** [comment]
@panpeach   能正常使用的话没有必要修改上线.  另外, 你手机网络提供了原始ipv6 吗, 哪个地区的哪家网络供应商

**Comment by SeaHOH** [comment]
>发现重要问题，V 3.12.4过一会IPv6就自动没了。

是如何表现的，麻烦详细说说，间隔、持续时长、隧道状态变化等。
如果可能描述下你的所在地区和网络服务商。

> 还是要从新退回安装XX-Net-3.12.0版本，这个版本不会自动断开IPv6。

你确定 3.12.0 版本不会断开？
其实上面说了，这个版本改参数的目的就是尝试解决 IPv6 间歇性断流，只是这段时间的调试中就出现过好几次，平时我是用的其它工具，所以这个概率算是挺大了。

不排除速度过快也能导致断流，但是请仔细观察后再回答，我会把这里的反馈作为继续调整的参考。

**Comment by panpeach** [comment]
@XndroidDev，魔都电信，移动数据下启动Xndroid时，提示原生IPV6可用，自动禁用了teredo，但始终连接不上。非得在启动组件里，去除勾选“IPV6可用时禁用teredo”，重启应用后立即就能连上。
家中wifi情况下启动Xndroid，并没提示“原生IPV6可用”，但速度也蛮快。

![1](https://user-images.githubusercontent.com/13916352/41951091-bf3154f6-79fb-11e8-91fa-fc4e87ceebad.jpg)

**Comment by SeaHOH** [comment]
看来移动 IPv6 的确不行，下个版本增加个调整优先级的按钮。

**Comment by xc1988** [comment]
空闲之后 不能自动恢复...

**Comment by SeaHOH** [comment]
空闲还是 teredo 休眠状态？休眠只要访问 IPv6 网络几秒就能恢复。

**Comment by nickwenchester** [comment]
还是有Download Checksum Fail的问题啊，求修复

**Comment by nickwenchester** [comment]
![1111](https://user-images.githubusercontent.com/33549603/41985320-96263efe-7a65-11e8-8bab-0a11f3e0e021.PNG)

**Comment by yonghuming9** [comment]
回忆 总结，总结 在回忆。老朽慢慢道来。
win10系统，山东电信200m光纤。

在3.12.4使用下，

**Comment by xc1988** [comment]
@SeaHOH 
显示是  XX-Net 状态 空闲
然后翻不了了 要重启XX-net才行

**Comment by AnyWAT** [comment]
3.12.0与之前的版本 隧道锁定。3.12.4隧道用段时间会变动。大概10分钟与30分钟之间跳动。😜貌似没发现（软件自动更换服务器）

**Comment by okaylabababa** [comment]
@SeaHOH 我學上面把屬性裡ipv6的勾去掉就顯示ok了 你看看這有沒有關係

**Comment by AnyWAT** [comment]
😜无线网络属性内取消勾选 IPv6 协议（貌似对有线网络无效）

**Comment by SeaHOH** [comment]
初步判断，速度（真正的连接速度，非直观感受到的下载速度）过快会导致隧道连接失败。

**Comment by SeaHOH** [comment]
下个版本会在设置页面增加个调节选项，从保守到激进给出几个档次的连接配置。
时间应该就在一周内，如果我没有其它特别要忙的事情。

**Comment by SeaHOH** [comment]
@xc1988
空闲是正常状态，就是说没有收到代理请求。
你看看其它状态正常不。

**Comment by yonghuming9** [comment]
(3.12.0与之前的版本 隧道锁定。3.12.4隧道用段时间会变动。大概10分钟与30分钟之间跳动。)
用段时间会变动，我的意思是没有了，跳动间隔10到30分钟隧道就没了。
哈哈 我的表述有问题。


记得xx之前是保留6000ip，后来3000，再后来500，
SeaHOH 调到100。
这一点和我不谋而合，我在两年前一直就是用的300，去年调到200。线程数5。


大概的原理我说一下不知对不对。


代码里有使用每一个ip时间的参数规定。
大概意思就是你储存的ip数量越多，除了浪费占用资源之外，让你的速度也慢。

当你第一次启动xx的时候，他会从第一个ip进行使用，每隔一个时间段会换一个ip。如果换的这个ip健壮，你的上网速度就快。若换到下一个ip不健壮你上网的速度也就慢。
好比看视频一会720p，一会480，一会240。

当你退出了xx，在用的时候再启动，他又会从第一个ip用起，依次替换使用。


为什么说占用浪费资源呢。
如果你保留储存了一万个ip，，，哎，，这里不知道怎样描述才能描述的更具体，

好比你跑步吧，每一步一个坐标要跑一万步，正好一圈，也就是一万个坐标。

你第一次跑跑了50步，累了要休息，后面还有9000多个坐标。

第二次跑跑了两百步，后面还是有9000多个坐标

第三次，第四次，永远1/10，3/10。


张三同学给自己画的面积小，每次都能跑一圈，不管是早上跑，还是中午跑，还是晚上跑。

只要启动，张三就能跑一圈。他画的面积只有一百步，也就是一百个坐标，他在跑的过程当中，发现每一个坐标有损坏或不清晰了，他就会丢掉更换。因为它的面积小，每次都能跑一圈，换起来不累效率高，那么它的坐标都是新鲜的。
反之，，
哎，不说了大概意思储存多了，跑不了一圈，日而日久占用资源，所谓的僵尸ip。因为我们每次只能跑半圈或者跑一小会儿，整个草场我们霸占着又跑不动，整个健身房那么多器材我们霸占着。我们每次健身只会用到其中几个器材。



整个停车场是我的你们别用，两万台车也是我的你们别用。都是我的，都是我的。



顺便说一下。
还有人调扫描线程数，一调就是上百调，还有几百往上调，先不说懂不懂代码后面协议的原理。千丝万缕啊。

只想说，
你妈同意吗？你家庭成员同意吗，是不是你家买的带宽给你一个人买的。

还有你自己配置的电脑和你家成员另外几台电脑愿意吗？
你的光猫你的交换机路由器同意吗？
是不是都是顶呱呱的硬件？

你的带宽和你家的各种硬件能不能扛得动这两千斤？



好了，好了，打住，憋了几年的事，今天大概说一点，一吐为快。
平时偶尔上来看下帖子。以上说的都是自己的理解不对的地方纠正啊。

**Comment by yonghuming9** [comment]
其实xx大神和SeaHOH大神，在ip数量上和扫描线程数上，或者其他的设置参数上都说过同样一句话。
没多大意义。

哈哈，大神们太忙，没有时间啰嗦。

每次简单明了几句话作回答，其实大神们的简单一两句话里面包含了很多含义，因为涉及到技术层面，软体硬体层面，所谓隔行如隔山，真正展开解释，不是一两句的事。

索性一两句概括。大概意思就是你们私下的动作没意义。

**Comment by AnyWAT** [comment]
总IP数的变迁：3000-6000-100-500-100
![default](https://user-images.githubusercontent.com/37962734/42035877-8a9bf748-7b16-11e8-9779-160d32fe5541.png)
最大扫描线程数 (0~200)👌
![default](https://user-images.githubusercontent.com/37962734/42035927-a9cc8cea-7b16-11e8-8e49-3d2fc1da095b.png)

**Comment by xc1988** [comment]
@SeaHOH 显示空闲状态的时候，证书会显示Fail。然后必须要重启XX才可以

**Comment by imldf** [comment]
3.12.4版本 Google地图一直显示“正在加载”，好像永远加载不完一样。
![001](https://user-images.githubusercontent.com/33856971/42126473-e1340022-7cbb-11e8-8644-11e4f6bba3c8.PNG)

**Comment by SeaHOH** [comment]
@imldf 
一切正常，可能你的代理设置有问题。
`F12`查看那个资源不能加载。

**Comment by imldf** [comment]
@SeaHOH   应该是无法加载登陆信息吧，不知道为什么
![002](https://user-images.githubusercontent.com/33856971/42130817-2dd4b4ec-7d22-11e8-8b5b-088ba3b3752d.PNG)

**Comment by SeaHOH** [comment]
![x2scrap2](https://user-images.githubusercontent.com/8470820/42131174-3c56a296-7ceb-11e8-9b4a-037c245e8257.png)

**Comment by imldf** [comment]
@SeaHOH 
你说的那个不懂看，不过我讲的问题今天自然好了，也不知道为什么
