### ISSUE TITLE
Google 更新服务器证书, 请问这个是什么原理啊, 哪个文件来连接google服务器?有大神解释一下麽

### ISSUE THREAD

**Issue by tess1199** [XX-net/XX-Net#11004]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
#11010
