### ISSUE TITLE
请问怎么关闭日志, 活着debug改成info或者warn, 这样能节省点系统资源吧,老机器卡

### ISSUE THREAD

**Issue by tess1199** [XX-net/XX-Net#11006]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
不要显示窗口，不要长期打开网页查看状态，只是写入日志，这样也卡？
你是不是调过扫描线程？

**Comment by tess1199** [comment]
> 是的, 以前打开很多网页都基本不占cpu, 现在的版本打开两三个网页就一直10%以上的cpu

**Comment by SeaHOH** [comment]
你是不是调过扫描线程？

**Comment by SeaHOH** [comment]
可以把没使用的模块关闭，比如只开启 gae_proxy，配合代理扩展一般使用没啥问题。
其它参数可以自定义，AppID 设置页面附带的连接介绍了如何配置。

**Comment by SeaHOH** [comment]
尝试下 3.12.5 版本的新增的被动级别，应该消耗很少。
