### ISSUE TITLE
3.12.3速度不错

### ISSUE THREAD

**Issue by fenghua35** [XX-net/XX-Net#11002]
新版本的速度很快了,经典版本3.10.4版已经不可用,大家还是用最新版吧。
服务器建议用 teredo.trex.fi 或 teredo-debian.remlab.net .感觉比较稳定、延时低些。

**Comment by MitchellClark666** [comment]
mark

**Comment by whhxmwhh** [comment]
正在检查网络-----合格（已连接）-----这个功能不错。

**Comment by whhxmwhh** [comment]
ip数量变化太可怕了。。个位数，2位数，3位数跳变。

**Comment by wqwin** [comment]
X-TUNNEL稳定多了，间歇性抽风也少了

**Comment by zzd2358** [comment]
快
