### ISSUE TITLE
teredor test result is usable. and the best server is win10.ipv6.microsoft.com.

### ISSUE THREAD

**Issue by FirstJavaMaster** [XX-net/XX-Net#11012]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是的,目前最新版3.12.2

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看过,但是没有具体的解决办法

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
如下图
![image](https://user-images.githubusercontent.com/22362110/41886368-9f1eb744-792e-11e8-89e4-556836a5f0b3.png)

点击按钮后,等待几十秒,上方显示
`teredor test result is usable. and the best server is win10.ipv6.microsoft.com.`

下方显示
```
qualified: True
NAT type: restricted
best server is: win10.ipv6.microsoft.com.
```

这应该是测试没有成功吧,这样一来除非手动命令行,否则只能使用win10.ipv6.microsoft.com了.

+ 没有更改过策略组
+ https://test-ipv6.com 测试 无域名 IPv6 连接测试 部分失败.
+ xx-net "状态"页IPV6状态正常

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
没啥事不用测试，直接更换即可。
你这个结果是正常的，重复一遍：已限制类型是正常可用的。
