### ISSUE TITLE
装了xx-net 后Safari和App Store等应用无法使用

### ISSUE THREAD

**Issue by zhihuihuashen** [XX-net/XX-Net#11019]
iMac,10.12.6.装了xx-net后，成功启动。chrome浏览器，Safari浏览器，App Store软件墙内墙外皆能正常使用。但是不启动xx-net，Safari浏览器任何网站（不管墙内墙外）都无法访问，App Store，OA都无法使用。

**Comment by SeaHOH** [comment]
果然这种问题没人愿意回答么。
就是啥，搜索下代理设置，你就应该明白为什么了。
具体操作，就是每次退出前，取消代理设置。

**Comment by Gongqiao24** [comment]
取消全局代理就好了..其实用这个模式和智能模式也是一样///不过智能模式App Store会提示没有网络。。
