### ISSUE TITLE
miredo 链接不上

### ISSUE THREAD

**Issue by diehardhan** [XX-net/XX-Net#11014]
上午还连上了一下,突然就断了,以为一会会好,但并没有.
sudo service miredo restart
无效
重启电脑  
无效

ipv6状态一直是fail
已升级到3.12.2
ifconfig  也无法看到虚拟网卡

ubuntu 18.04  

DNS也更换为119.29.29.29
miredo 服务器也更换为:  teredo.remlab.net.

-home:~/XX-NET/XX-Net-3.3.1/code/3.12.2/gae_proxy/local/ipv6_tunnel$ sudo python pteredor.py
[sudo] han 的密码： 
('try bind local port:', 3708)
Starting probe NAT type...
当前设备可能无法正常使用 teredo 隧道，NAT 类型是 offline！

经检测，推荐服务器是 None.
按回车键结束……

 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
1. 检查下 iptable 设置是不是有变化。
2. 检查路由器 NAT 设置是否正常。
3. 如果都正常，估计是网络问题，换个网络可以确认。

**Comment by diehardhan** [comment]
几天没回公司,今天过来又一切正常了,估计是网络问题了
