### ISSUE TITLE
ipv6-status: Fail

### ISSUE THREAD

**Issue by zhangzongyao** [XX-net/XX-Net#11015]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by blob2015** [comment]
:grinning: 大海兄说，你这人怎么这样啊

**Comment by whhxmwhh** [comment]
网络封锁严重罢了。没法用ipv6 也没法用隧道来穿越罢了。我的网络也是这样。你换个梯子吧。

**Comment by whhxmwhh** [comment]
![ipv6](https://user-images.githubusercontent.com/7959854/41951162-101269be-79fc-11e8-95b9-260c0cc1779d.JPG)
![qipv6](https://user-images.githubusercontent.com/7959854/41951169-1786bccc-79fc-11e8-8a7c-56e0bea63c07.JPG)
ipv6很头大。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/41954080-f484c682-7a0b-11e8-9eb8-99ee7ff6358d.png)

**Comment by SeaHOH** [comment]
你们不要来秀啊，本来还想警告他说再不回复我就屏蔽他，这样我都不好下手了。

**Comment by zhangzongyao** [comment]
大哥，抱歉。我有回復您嘗試了很多版本和修復都無效呀，一直IPv6 隧道啟用不了
----- 原始邮件 -----
发件人：SeaHOH <notifications@github.com>
收件人：XX-net/XX-Net <XX-Net@noreply.github.com>
抄送人：zhangzongyao <zongyao_1987@sina.com>,  Author <author@noreply.github.com>
主题：Re: [XX-net/XX-Net] ipv6-status: Fail (#11015)
日期：2018年06月27日 13点41分

你们不要来秀啊，本来还想警告他说再不回复我就屏蔽他，这样我都不好下手了。

&mdash;

**Comment by SeaHOH** [comment]
IPv6 问题某些情况下还是比较复杂的，你光是给个 fail 状态完全没有意义。

提供的测试功能你用过没？结果是啥？
你做过哪些操作和尝试？
你的路由和 PC 设置是否检查过？

**Comment by zhangzongyao** [comment]
sir,謝謝您的回復。我有點小白之前完全按照教程一步一步來，現在突然不能上了刪掉換版本及討論我也看了很多實在找不到解決的辦法。測試功能也用了，結
果如下， 盡管知道測試結果失敗可還是找不到解決方案。
1.測試teredo：
qualified: False
NAT type: offline
no server detected, return default: teredo.remlab.net.
2.僅測試teredo可用性：
qualified: False
NAT type: offline
3.僅測試teredo服務器：
no server detected, return default: teredo.remlab.net.
4.更換teredo服務器：
no server detected, return default: teredo.remlab.net.
另外啟用、禁用都試了結果IPv6 隧道還是“已禁用”狀態（重新运行enable_ipv6.bat也沒用）
----- 原始邮件 -----
发件人：SeaHOH <notifications@github.com>
收件人：XX-net/XX-Net <XX-Net@noreply.github.com>
抄送人：zhangzongyao <zongyao_1987@sina.com>,  State change <state_change@noreply.github.com>
主题：Re: [XX-net/XX-Net] ipv6-status: Fail (#11015)
日期：2018年06月28日 15点08分

IPv6 问题某些情况下还是比较复杂的，你光是给个 fail 状态完全没有意义。
提供的测试功能你用过没？结果是啥？

你做过哪些操作和尝试？

你的路由和 PC 设置是否检查过？

&mdash;

**Comment by SeaHOH** [comment]
都不要你检测路由了，三两句估计你也弄不明白，把网线直接插到路由器上，不要用无线网卡。
检查下 Windows 防火墙是否开启，没有，请打开。
查看组策略是否启用，恢复到未设置状态。

**Comment by zhangzongyao** [comment]
好的，我再試試。感謝！
----- 原始邮件 -----
发件人：SeaHOH <notifications@github.com>
收件人：XX-net/XX-Net <XX-Net@noreply.github.com>
抄送人：zhangzongyao <zongyao_1987@sina.com>,  State change <state_change@noreply.github.com>
主题：Re: [XX-net/XX-Net] ipv6-status: Fail (#11015)
日期：2018年07月03日 15点47分

都不要你检测路由了，三两句估计你也弄不明白，把网线直接插到路由器上，不要用无线网卡。

检查下 Windows 防火墙是否开启，没有，请打开。

查看组策略是否启用，恢复到未设置状态。

&mdash;
