### ISSUE TITLE
qualified: True NAT type: restricted

### ISSUE THREAD

**Issue by ax003** [XX-net/XX-Net#11011]
现在一直取不到IPV6地址，IPv6状态fail

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 192.168.X.X:55933
外部 NAT 映射    : XXX.XXX:55933

测试teredo可用性就出现这个结果。

qualified: True
NAT type: restricted

难道ipv6这样就算一直失败？

**Comment by SeaHOH** [comment]
`ipconfig /all`
这个命令显示 teredo 没有分配到 IPv6 地址吗？

那么，点击启用，重启一次机器看看。

**Comment by ax003** [comment]
按二楼的办法搞定了，状态OK，不过扫不到IP

**Comment by SeaHOH** [comment]
看谷歌换新证书的公告没，用更新下版本。

**Comment by ax003** [comment]
已经更新到了3.12.4，还是没有

**Comment by ax003** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
xxnet-version: 3.12.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:559 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
你等了多久还没扫到？

**Comment by ax003** [comment]
20分钟了，一个也没有

**Comment by SeaHOH** [comment]
直连 test-ipv6.com 测试什么结果。

如果结果正常，换个服务器如果还不行，麻烦说下你的地区和网络服务商，估计是开始了。

**Comment by ax003** [comment]
一只检测不到ipv6，我是北京联通

**Comment by SeaHOH** [comment]
那么这就不是最坏的状况。

试试在路由器的 NAT 设置中，把你运行 XX-Net 的机器的 IP 设置为 DMZ 主机。
然后把服务器换成任意非当前连接的其它 teredo 服务器。

**Comment by AnyWAT** [comment]
本地映射 : 192.168.X.X:55933
外部 NAT 映射 : XXX.XXX:55933
神奇的55933，貌似从未遇见过一致的情况😜

**Comment by SeaHOH** [comment]
一致就是 cone，很正常，直连公网都是这种，还有某些转发也能做到这种效果，比如 DMZ。

**Comment by unclebily** [comment]
我也是联通，情况跟楼主情况有点像。电脑网线直连联通的光猫时，Teredo状态是休眠，怎么弄都不行，然后我把网线插到路由上，通过路由连光猫，teredo状态就正常了，XX-Net就正常翻墙了。怀疑联通的光猫里是不是有什么设置需要改变。

**Comment by SeaHOH** [comment]
@ax003 能用 IPv6 了吗？参考 #11023 看看情况是否相似。
