### ISSUE TITLE
申請了6個AppIDs，其中三個失效了（死了），只有另外的三個可用。如何恢復（救活）？

### ISSUE THREAD

**Issue by XiYanZi23** [XX-net/XX-Net#11018]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by yeezylife** [comment]
。。怎么还能失效的 我这25个用了好几年了

**Comment by SeaHOH** [comment]
访问 https://你的appid.appspot.com/ 查看是否存在、是否部署了服务端。

**Comment by XiYanZi23** [comment]
@SeaHOH 
> 访问https://你的appid.appspot.com/查看是否存在、是否部署了服务端。
连接超时，先休息一会再来！
