### ISSUE TITLE
Chrome浏览器无法登录TweetDeck

### ISSUE THREAD

**Issue by salma62** [XX-net/XX-Net#11027]
从周一开始无法登录TweetDeck这个Twitter客户端网站，升级到了最新版本的XX-Net也不能上，TweetDeck网站页面显示：
Sorry, something went wrong. Please try again later. (SyntaxError: Unexpected token � in JSON at position 0)
换了IE就可以上了，请问是什么问题？

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:102
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:29 h2:1
scan-ip-thread-num: 8
ip-quality: 332
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
可能是网页编码问题，我并不想注册 Twitter，你能把相关 gae_proxy 日志和登录请求返回的响应（浏览器 F12 可查看）发一下吗？

**Comment by salma62** [comment]
不好意思，因为试了公用ID发现好用，又想起很久没有重新部署服务端了，部署后没问题了
