### ISSUE TITLE
最近很不稳定啊

### ISSUE THREAD

**Issue by zjsx** [XX-net/XX-Net#11021]
X-Tunnel 配置
连接服务器失败：session server login fail:602

**Comment by zjsx** [comment]
XX-Net 3.12.4版本，GAEProxy这边ipv6怎么也开不了
IPv6 状态(如何开启) Fail (尝试修复)
x-tunnel也经常连不上

**Comment by zjsx** [comment]
已经回滚到3.12.2，x-tunnel还是连接失败

登录失败：status:602

**Comment by kukumaya** [comment]
IPv6一直无法开启，昨天还好的，今天突然就不行了，无奈

**Comment by ncmon** [comment]
X-Tunnel 不是要收费的吗

**Comment by milanthree** [comment]
X-Tunnel确实又开始登不上去了，是不是又被攻击了

**Comment by AnyWAT** [comment]
GAE正常，X-Tunnel 才正常
![default](https://user-images.githubusercontent.com/37962734/41965187-94ecbdc4-7a2e-11e8-90ba-533d5120cd1f.png)

**Comment by SeaHOH** [comment]
> XX-Net 3.12.4版本，GAEProxy这边ipv6怎么也开不了
> IPv6 状态(如何开启) Fail (尝试修复)

点击测试，看看什么情况，顺便问下你的 网络服务商。

> X-Tunnel确实又开始登不上去了，是不是又被攻击了

可能吧，没有使用不清楚。

> X-Tunnel 不是要收费的吗

有提供一些免费流量。
