### ISSUE TITLE
XX-NET从3.6.8升级到3.12.4，一直显示请检查浏览器代理设置！

### ISSUE THREAD

**Issue by xuyan1985** [XX-net/XX-Net#11025]
XX-NET从3.6.8升级到3.12.4，一直显示请检查浏览器代理设置！浏览器升级了，CA证书也重新装了还是没用，网站倒是都可以看 不受影响，请问这是为什么？

**Comment by AnyWAT** [comment]
浏览器代理插件：添加未加载资源内的（检测代理项）*.deja.com 走GAE

**Comment by whhxmwhh** [comment]
https://github.com/XX-net/XX-Net/issues/10058“结束进程 pythonw.exe，重启XX、扫描下即可”

**Comment by whhxmwhh** [comment]
http://ju.outofmemory.cn/entry/94277
其实都是ipv4的网络使用ipv6的原因。大家多找找方法来这里交流一下吧。
上面那个方法可用，但是一会儿又fail了。用这个再试试。

**Comment by xuyan1985** [comment]
楼上的大神，我没懂，咋操作。。。

**Comment by SeaHOH** [comment]
使用智能代理 8086 端口即可

**Comment by xuyan1985** [comment]
是8087改成8086吗？还是？。。。

**Comment by AnyWAT** [comment]
智能代理：Smart-Router
3.6.8或以前的旧版，采用的是你会添加的 *.twitter.com 作为XX-Net 检测（代理正常与否的）项，从某版本开始被 *.deja.com 替代（就不会添加了？）

**Comment by senlinhuahua** [comment]
ok
