### ISSUE TITLE
可否借用下Smart Router的源代码？

### ISSUE THREAD

**Issue by serverLua** [XX-net/XX-Net#11028]
想借鉴一下，以此写个独立软路由练练手

**Comment by serverLua** [comment]
@SeaHOH @xxnet ?

**Comment by dou4cc** [comment]
License 是 BSD: https://github.com/XX-net/XX-Net/blob/master/code/default/LICENSE.txt

**Comment by xxnet** [comment]
​开源嘛，可以站在前人的肩膀上前行。
大家互相学习。
BSD 的License 是很开发的了，用于商业也行。
有什么问题可以提出来探讨改进。

**Comment by serverLua** [comment]
谢谢

**Comment by xxnet** [comment]
​可以直接在XX-Net上面改，让Smart-Router能够直接独立工作。
就像GAE_proxy也是可以直接独立工作的一样。

前面有提到一个需求，SmartRouter能够指定外部的代理服务，比如SSR或v2ray，而不是绑定X-Tunnel，这个改动不算太难。
