### ISSUE TITLE
3.12.4 使用反馈

### ISSUE THREAD

**Issue by fredericky123** [XX-net/XX-Net#11020]
这个版本速度非常赞，目前仅遇到一个问题：不时地连接中断，目前的解决办法是重新连接网络又能恢复使用，但出现频率也不低，一上午能出现两三次，不知是个案还是众案？

**Comment by wushibinbilly** [comment]
我的就是容易中断，重启下xx-net就提示正常上网了，每次都这样，搞的每次要用Google的时候就重启一下xx-net, 好麻烦

**Comment by fredericky123** [comment]
问题类似，主要出现在一段时间不用google，再次搜索时，会有这个问题

**Comment by SeaHOH** [comment]
问个可能有点麻烦的问题，能不能退回 3.12.2 使用一段时间，看是否会出现相同状况。

**Comment by fredericky123** [comment]
回滚试一下再来反馈

**Comment by xiaonanhailili** [comment]
我这里出现IPV6地址突然减少至100左右,并且同样出现不定时中断

**Comment by fredericky123** [comment]
@xiaonanhailili 3.12.4是设置为100 请看版本更新日志

**Comment by xiaonanhailili** [comment]
我也想看,可惜你没写出来3.12.4是设置为100,releases没看到写过.0.0

**Comment by fredericky123** [comment]
@xiaonanhailili 这是海少发布的哈，我只是小弱，“调整 gae_proxy 模块参数”，看get到的自然就明白了

**Comment by xiaonanhailili** [comment]
吐血.....

**Comment by xiaonanhailili** [comment]
对了,我这里会时不时的出现证书需要重新部署,关闭XX_NET重启才能使用

**Comment by lh471921250** [comment]
这个问题最近几个版本都出现过,说明这个问题没得到好的解决.

**Comment by SeaHOH** [comment]
> 这个问题最近几个版本都出现过,说明这个问题没得到好的解决.

是指证书错误还是连接不上 GAE？

**Comment by SeaHOH** [comment]
@fredericky123 看来的确如此，等 3.12.2 的结果哈，明天发就行。

**Comment by fredericky123** [comment]
@SeaHOH 正在体验3.12.2中哈，明天见分晓。

**Comment by fredericky123** [comment]
@SeaHOH 使用了一上午，没有出现中断的问题，不过3.12.2吃内存比较多，3.12.4的改善还是有效果的

**Comment by xiaonanhailili** [comment]
@SeaHOH 有两种:1.是在所有设置都有效的情况下突然中断链接2.CA证书状态突然失效,需要关闭重启XX-net

**Comment by sky123456789sky** [comment]
同问题 看Y2B不时中断

**Comment by SeaHOH** [comment]
收到，正在整理。

**Comment by AnyWAT** [comment]
CA证书状态突然失效👀浏览器代理插件：添加未加载资源内的（XX-Net 检测项？）*.deja.com 走GAE（8087及1080自动切换都如此，哪怕早已存在此规则🙃）或刷新网页，或关闭网页再恢复

**Comment by sichaoguo21** [comment]
ipv6 IP有，开机后初期可以使用，后面就连不上了，而IP可用数不变，另外和shadowsocks同时时候后，本来可用的xx-net又无效了，需重启电脑才恢复。有朋友遇到这种情况吗？

**Comment by AnyWAT** [comment]
软件默认总IP数100下曾见识有效IP数趋近0后倒自动逐步恢复，但连接池趋近0、无法再增大，修改总IP数后再次运行多一个XX-Net。。。😜增大总IP数为500后貌似没发生两种趋近于0的情况

**Comment by Eri5Ch** [comment]
@SeaHOH 还发现一个问题 不知道算不算一个bug

超额appid在提示页面不能自动恢复,必须重启xxnet才可以.

这个问题可以复现.

**Comment by SeaHOH** [comment]
@Eri5Ch 你可以单独提出这个问题备忘，但是暂时不会修复。

**Comment by Eri5Ch** [comment]
@SeaHOH  如果只是显示超额 appid 而实际并不影响的话倒是无关紧要...

**Comment by frankruizhi** [comment]
系统空闲是个啥意思

![image](https://user-images.githubusercontent.com/25580946/42266265-7fee7ea6-7fa8-11e8-94b1-c5b0573a5eb5.png)

**Comment by csy-650203** [comment]
为什么XX-NET显示：XX-Net 3.12.4，一切正常，你可以访问真正的互联网了。 还是不能翻墙啊
访问YouTube显示：
600:gae_exception:'602:ip not support GAE' https://www.google.co.uk/search?q=YouTube&oq=YouTube&aqs=chrome.0.69i59j69i60.8134j0j7&sourceid=chrome&ie=UTF-8gae_exception:'602:ip not support GAE' https://www.google.co.uk/search?q=YouTube&oq=YouTube&aqs=chrome.0.69i59j69i60.8134j0j7&sourceid=chrome&ie=UTF-8gae_exception:'602:ip not support GAE' https://www.google.co.uk/search?q=YouTube&oq=YouTube&aqs=chrome.0.69i59j69i60.8134j0j7&sourceid=chrome&ie=UTF-8
