### ISSUE TITLE
Teredo 隧道状态为：休眠（未连接），测试Teredo显示结果为：qualified: True，

### ISSUE THREAD

**Issue by unclebily** [XX-net/XX-Net#11031]
之前一直好着呢，现在IPV6状态一直是Fail。请大神看看怎么回事？为什么Teredo 隧道状态一直是：休眠（未连接）？

日志
Jun 28 15:03:22.888 - [DEBUG] network IPv4 is ok, cost:1253 ms

Jun 28 15:03:22.888 - [INFO] ------------------------------------------------------

Jun 28 15:03:22.888 - [INFO] Python Version : 2.7.13

Jun 28 15:03:22.888 - [INFO] OS : Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

Jun 28 15:03:22.888 - [INFO] Listen Address : 127.0.0.1:8087

Jun 28 15:03:22.888 - [INFO] GAE APPID : wangbily|wangbily1|wangbily2|wangbily3|wangbily4

Jun 28 15:03:22.888 - [INFO] ------------------------------------------------------

Jun 28 15:03:24.251 - [DEBUG] Importing CA

Jun 28 15:03:24.251 - [DEBUG] Begin to import Windows CA

Jun 28 15:03:24.267 - [DEBUG] XX-Net CA already exists

Jun 28 15:03:24.282 - [DEBUG] XX-Net CA already exists

Jun 28 15:03:24.282 - [INFO] SSL use version:TLSv1_2

Jun 28 15:03:24.298 - [INFO] OpenSSL support alpn

Jun 28 15:03:24.298 - [INFO] load ip range file:E:\CrossWall\XX-Net-3.11.3\code\3.12.3\gae_proxy\local\ip_range.txt

Jun 28 15:03:24.298 - [INFO] load ip_list num:100, target num:100

Jun 28 15:03:24.376 - [INFO] SSL use version:TLSv1_2

Jun 28 15:03:24.391 - [INFO] server 127.0.0.1:8087 started.

Jun 28 15:03:24.673 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38769

Jun 28 15:03:24.673 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38772

Jun 28 15:03:24.673 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38770

Jun 28 15:03:24.673 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38771

Jun 28 15:03:24.813 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38773

Jun 28 15:03:24.829 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome from:127.0.0.1:38774

Jun 28 15:03:26.064 - [DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=d9a39500-fc15-4bf1-a943-6faf68466b61&version=3.12.3&platform=Windows-10-10.0.17134

Jun 28 15:03:29.377 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:29.377 - [DEBUG] connect 2607:f8b0:400f:11::7 network fail

Jun 28 15:03:29.392 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:29.392 - [DEBUG] connect 2607:f8b0:4005:1a::6 network fail

Jun 28 15:03:29.673 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:29.673 - [DEBUG] connect 2607:f8b0:401c:12::c network fail

Jun 28 15:03:30.202 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:30.202 - [DEBUG] connect 2607:f8b0:401c:24::8 network fail

Jun 28 15:03:30.708 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:30.708 - [DEBUG] connect 2607:f8b0:4007:2b::c network fail

Jun 28 15:03:31.066 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:31.066 - [DEBUG] connect 2607:f8b0:401c:b::9 network fail

Jun 28 15:03:31.208 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:31.208 - [DEBUG] connect 2607:f8b0:4007:2d::b network fail

Jun 28 15:03:31.574 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:31.574 - [DEBUG] connect 2607:f8b0:401c:24::c network fail

Jun 28 15:03:31.711 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:31.711 - [DEBUG] connect 2607:f8b0:4005:c::7 network fail

Jun 28 15:03:32.087 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:32.087 - [DEBUG] connect 2607:f8b0:401c:27::9 network fail

Jun 28 15:03:32.224 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

Jun 28 15:03:32.224 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:32.224 - [DEBUG] connect 2607:f8b0:400a::16 network fail

Jun 28 15:03:32.587 - [DEBUG] report_connect_fail IPv6 continue_fail_count:12

Jun 28 15:03:32.587 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:32.587 - [DEBUG] connect 2607:f8b0:401c:10::9 network fail

Jun 28 15:03:32.722 - [DEBUG] report_connect_fail IPv6 continue_fail_count:13

Jun 28 15:03:32.722 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:32.722 - [DEBUG] connect 2607:f8b0:401c:2d::6 network fail

Jun 28 15:03:33.078 - [DEBUG] report_connect_fail IPv6 continue_fail_count:14

Jun 28 15:03:33.078 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:33.078 - [DEBUG] connect 2607:f8b0:401d:2::c network fail

Jun 28 15:03:33.227 - [DEBUG] report_connect_fail IPv6 continue_fail_count:15

Jun 28 15:03:33.227 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:33.227 - [DEBUG] connect 2607:f8b0:4007:2a::9 network fail

Jun 28 15:03:33.586 - [DEBUG] report_connect_fail IPv6 continue_fail_count:16

Jun 28 15:03:33.586 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:33.586 - [DEBUG] connect 2607:f8b0:4017:33::a network fail

Jun 28 15:03:33.718 - [DEBUG] report_connect_fail IPv6 continue_fail_count:17

Jun 28 15:03:33.718 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:33.718 - [DEBUG] connect 2607:f8b0:400a:9::16 network fail

Jun 28 15:03:34.091 - [DEBUG] report_connect_fail IPv6 continue_fail_count:18

Jun 28 15:03:34.091 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:34.091 - [DEBUG] connect 2607:f8b0:401c:1e::9 network fail

Jun 28 15:03:34.227 - [DEBUG] report_connect_fail IPv6 continue_fail_count:19

Jun 28 15:03:34.227 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:34.227 - [DEBUG] connect 2607:f8b0:400a:7::7 network fail

Jun 28 15:03:34.583 - [DEBUG] report_connect_fail IPv6 continue_fail_count:20

Jun 28 15:03:34.583 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:34.583 - [DEBUG] connect 2600:6:300:9::f network fail

Jun 28 15:03:35.104 - [DEBUG] report_connect_fail IPv6 continue_fail_count:21

Jun 28 15:03:35.104 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:35.104 - [DEBUG] connect 2607:f8b0:401c:2d::a network fail

Jun 28 15:03:35.606 - [DEBUG] report_connect_fail IPv6 continue_fail_count:22

Jun 28 15:03:35.606 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:35.606 - [DEBUG] connect 2607:f8b0:400f:11::7 network fail

Jun 28 15:03:37.323 - [DEBUG] GAE GET https://translate.googleapis.com/translate_a/l?client=gtx&hl=zh-CN&cb=_callbacks____0jiy7d2r0 from:127.0.0.1:39015

Jun 28 15:03:45.405 - [DEBUG] report_connect_fail IPv6 continue_fail_count:23

Jun 28 15:03:45.405 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:45.405 - [DEBUG] connect 2607:f8b0:400f:11::7 network fail

Jun 28 15:03:45.420 - [DEBUG] report_connect_fail IPv6 continue_fail_count:24

Jun 28 15:03:45.420 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:45.420 - [DEBUG] connect 2607:f8b0:4005:1a::6 network fail

Jun 28 15:03:45.698 - [DEBUG] report_connect_fail IPv6 continue_fail_count:25

Jun 28 15:03:45.698 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:45.698 - [DEBUG] connect 2607:f8b0:401c:12::c network fail

Jun 28 15:03:46.208 - [DEBUG] report_connect_fail IPv6 continue_fail_count:26

Jun 28 15:03:46.208 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:46.208 - [DEBUG] connect 2607:f8b0:401c:24::8 network fail

Jun 28 15:03:46.716 - [DEBUG] report_connect_fail IPv6 continue_fail_count:27

Jun 28 15:03:46.716 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:46.716 - [DEBUG] connect 2607:f8b0:4007:2b::c network fail

Jun 28 15:03:47.081 - [DEBUG] report_connect_fail IPv6 continue_fail_count:28

Jun 28 15:03:47.081 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:47.081 - [DEBUG] connect 2607:f8b0:401c:b::9 network fail

Jun 28 15:03:47.210 - [DEBUG] report_connect_fail IPv6 continue_fail_count:29

Jun 28 15:03:47.210 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:47.210 - [DEBUG] connect 2607:f8b0:4007:2d::b network fail

Jun 28 15:03:47.578 - [DEBUG] report_connect_fail IPv6 continue_fail_count:30

Jun 28 15:03:47.578 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:47.578 - [DEBUG] connect 2607:f8b0:401c:24::c network fail

Jun 28 15:03:47.719 - [DEBUG] report_connect_fail IPv6 continue_fail_count:31

Jun 28 15:03:47.719 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:47.719 - [DEBUG] connect 2607:f8b0:4005:c::7 network fail

Jun 28 15:03:48.098 - [DEBUG] report_connect_fail IPv6 continue_fail_count:32

Jun 28 15:03:48.098 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:48.098 - [DEBUG] connect 2607:f8b0:401c:27::9 network fail

Jun 28 15:03:48.227 - [DEBUG] report_connect_fail IPv6 continue_fail_count:33

Jun 28 15:03:48.227 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:48.227 - [DEBUG] connect 2607:f8b0:400a::16 network fail

Jun 28 15:03:48.596 - [DEBUG] report_connect_fail IPv6 continue_fail_count:34

Jun 28 15:03:48.596 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:48.596 - [DEBUG] connect 2607:f8b0:401c:10::9 network fail

Jun 28 15:03:48.739 - [DEBUG] report_connect_fail IPv6 continue_fail_count:35

Jun 28 15:03:48.739 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:48.739 - [DEBUG] connect 2607:f8b0:401c:2d::6 network fail

Jun 28 15:03:49.081 - [DEBUG] report_connect_fail IPv6 continue_fail_count:36

Jun 28 15:03:49.081 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:49.081 - [DEBUG] connect 2607:f8b0:401d:2::c network fail

Jun 28 15:03:49.230 - [DEBUG] report_connect_fail IPv6 continue_fail_count:37

Jun 28 15:03:49.230 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:49.230 - [DEBUG] connect 2607:f8b0:4007:2a::9 network fail

Jun 28 15:03:49.589 - [DEBUG] report_connect_fail IPv6 continue_fail_count:38

Jun 28 15:03:49.589 - [DEBUG] report_connect_fail network fail

Jun 28 15:03:49.589 - [DEBUG] connect 2607:f8b0:4017:33::a network fail

Jun 28 15:03:49.680 - [WARNING] task POST None /_gh/ timeout

Jun 28 15:03:49.680 - [WARNING] task POST None /_gh/ timeout

Jun 28 15:03:49.681 - [WARNING] task POST None /_gh/ timeout

Jun 28 15:03:49.681 - [WARNING] task POST None /_gh/ timeout

Jun 28 15:03:49.681 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 28 15:03:49.681 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 28 15:03:49.682 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 28 15:03:49.682 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jun 28 15:03:49.682 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Jun 28 15:03:49.682 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Jun 28 15:03:49.682 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Jun 28 15:03:49.683 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

**Comment by SeaHOH** [comment]
你这是刚启动吧，等一会应该就连上了。

**Comment by unclebily** [comment]
已经解决：电脑网线直连联通的光猫时，Teredo状态是休眠，怎么弄都不行，然后我把网线插到路由上，通过路由连光猫，teredo状态就正常了，XX-Net就正常翻墙了。怀疑联通的光猫里是不是有什么设置需要改变。

**Comment by SeaHOH** [comment]
一直是路由拨号吗？
如果是，这就是正常现象。
如果是光猫拨号，就有点想不通了。
