### ISSUE TITLE
关于WIN10 IPV6总是关闭

### ISSUE THREAD

**Issue by 244671360** [XX-net/XX-Net#11033]
我的电脑上的XX-NET在某次更新以后IPV6状态经常显示断开，不知道什么时候又会变成OK。偶然我发现打开蓝灯可以让IPV6状态变成OK。。。比自带的调试管用多了。。。不知道什么原理，反馈一下

**Comment by whhxmwhh** [comment]
太棒了。要试试。

**Comment by chen0791cx** [comment]
我的也是 突然就斷 非要重啟電腦

**Comment by gdsteven** [comment]
这个问题以前WIN10有，现在好像已经没这问题了，如果netsh interface teredo show state 显示隧道不可用，控制台上重启下iphlpsvc就好了, net stop iphlpsvc , net start iphlpsvc

**Comment by yeezylife** [comment]
我是win10  刚刚IPV6自己就挂了 我都没关机 下午都还行。。我换了个teredo服务器就好了。
