### ISSUE TITLE
Youtube 一直报错...本来画面是1080...然后突然黑屏..然后自动切换到360..然后报错..

### ISSUE THREAD

**Issue by Gongqiao24** [XX-net/XX-Net#11030]
![213](https://user-images.githubusercontent.com/20225809/42017360-4ac0282c-7ae1-11e8-843e-26568bcfe0d3.png)
最新版3.12.4...

**Comment by Gongqiao24** [comment]
@SeaHOH 这个问题只存在1080...低画质没有这个问题。。。

**Comment by UltraDWS** [comment]
相同问题+1

**Comment by tatiyixi** [comment]
相同问题+1

**Comment by cngoodboy** [comment]
是公共APPID吗

**Comment by ablebodied** [comment]
YouTube确实会中断，不过速度提升很明显，1080P都可以看了

**Comment by xiaopiniu20** [comment]
这两天表现很正常，也不知道什么原因。前几天播放YouTube会时不时断掉。

**Comment by Buccaneer01** [comment]
除了报错，还会突然黑屏，然后等几秒缓存下来了继续播放，不如缓存不下来，就是这个报错了
自己的appid，480p

**Comment by SeaHOH** [comment]
#11106
测试下是否完全修复
