### ISSUE TITLE
系统不稳定，检查所有ip时过几分钟就崩溃

### ISSUE THREAD

**Issue by Jerryliukz** [XX-net/XX-Net#11032]
不论ip数量少还是多，只要检查所有ip，过几分钟必定崩溃；不检查的话也时有崩溃现象发生……应该不是我的pc内存不够……

**Comment by SeaHOH** [comment]
这个功能很久没变动过了，可能不适合现在的状况。
有空的时候会检查下，暂时不用这个也没关系，作用不大。

**Comment by Jerryliukz** [comment]
不检查ip的话……ip延迟得有1000+，而且可用ip只有个位数……

**Comment by SeaHOH** [comment]
你的版本是？建议更新 3.12.2 稳定版。
我这里延迟也比较高，但是数量还是有的。

**Comment by Jerryliukz** [comment]
我是3.12.4……

**Comment by Jerryliukz** [comment]
看着总数3000+的ip却只有个位数或者十几个就闹心，忍不住检查一番

**Comment by AnyWAT** [comment]
既然不时忍不住检查一番，总数3000+的ip貌似太大，500足以，并满足：关闭”自动调整扫描线程数“，
最大扫描线程数150以上，即可维持有效IP数趋近总IP数且较小的IP延时👀

**Comment by Jerryliukz** [comment]
维持不了……总ip数一直很少所以我才调大了总ip数和扫描线程……

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11009#issuecomment-401075455

**Comment by AnyWAT** [comment]
检查所有ip时过几分钟就崩溃：系统还是XX-Net ？（Win10 内存3GB的路过😂）
