### ISSUE TITLE
如何撤销软件（start.bat文件）对电脑的更改？

### ISSUE THREAD

**Issue by onemans-battle** [XX-net/XX-Net#11034]
使用XX-Net-3.12.2 系统Windows10。
文档中并没有给出程序对电脑进行更改后如何撤销的说明。就我看到的，start.bat会自动导入根证书，配置本地代理。退出程序后本地代理的配置依然处于使用状态，导致无法正常访问web,需要手动关闭。另外，我想使用X-tunnel，不想导入根证书。请问如何“卸载”start.bat所做的所有更改呢？
目前删除了根证书、取消了全局代理，不知道start.bat还做了什么其他修改系统的事以及如何清理？

**Comment by AnyWAT** [comment]
🤣貌似目前只有GAE正常X-tunnel才正常，GAE就得用证书。。。
![default](https://user-images.githubusercontent.com/37962734/42053831-383d535a-7b45-11e8-979a-883688b87a31.png)

**Comment by onemans-battle** [comment]
非常感谢两位！
