### ISSUE TITLE
这是表示帖子正在被审核吗?

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net#11046]
![](https://user-images.githubusercontent.com/7764678/42126091-a8e713e6-7cb4-11e8-9f2d-bed58faad9ad.png)

好一会儿才好.

**Comment by dou4cc** [comment]
@Microsoft

**Comment by AnyWAT** [comment]
RT @who Win10 1803回滚1709，再也不瞎更新了…😑 https://twitter.com/i/status/1013065716545679361
