### ISSUE TITLE
文件包解压失败

### ISSUE THREAD

**Issue by huhjgiiii** [XX-net/XX-Net#11045]
请问怎么解决  不能完全解压文件包

这个压缩文件格式未知或者数据已经被损坏		XX-Net-3.12.2\code\default\python27\1.0\lib\darwin\cryptography\hazmat\bindings\_openssl.so		F:\XX-Net-3.12.2.zip		
换用WINRAR显示不可预料的压缩文件末端，用ARAR修复也无效
重下安装包也没用  2天了  每天都试过

**Comment by AnyWAT** [comment]
文件正常
![default](https://user-images.githubusercontent.com/37962734/42123677-c89c9eda-7c88-11e8-87ae-b59d9407bed0.png)
重下安装包也没用 2天了 每天都试过：不如XX-Net 运行正常，待IP延时较小且连接池较大后。。。

**Comment by huhjgiiii** [comment]
![default](https://user-images.githubusercontent.com/40713104/42124155-4caba85e-7c90-11e8-9fb7-6caffcc9e065.PNG)
文件大小都不一样，哪里出问题了，我昨天晚上还专门去网吧试了下，也不行

**Comment by AnyWAT** [comment]
请问，下载文件时的代理软件？

**Comment by huhjgiiii** [comment]
反馈下：解决了，用谷歌浏览器下载，解压出来正常了。用360浏览器下载后，解压就失败，其他浏览器暂时没有试。但是我第一次用XX-NET也是通过360浏览器下载的，当时是3.6版本，可以正常解压 。

**Comment by AnyWAT** [comment]
360浏览器😝 https://github.com/XX-net/XX-Net/issues/10957

**Comment by blob2015** [comment]
测试下hash值最简单明了

**Comment by Acytoo** [comment]
跟浏览器关系不大，网络波动的问题，传输数据时出错了
