### ISSUE TITLE
最新3.12.4，看youtube频繁卡顿，还卡掉。。。

### ISSUE THREAD

**Issue by gang0122** [XX-net/XX-Net#11049]
最新3.12.4，看youtube频繁卡顿，时常“出了点问题，请稍后重试”，然后刷新就能继续用。ip数量倒是挺正常，帮我看看到底是怎么回事。
最近一次youtube卡掉的日志：
Jul 01 13:41:00.171 - [WARNING] task POST None /_gh/ timeout 

Jul 01 13:41:00.171 - [DEBUG] GAE_Exception 600 'fetch gae fail' 

Jul 01 13:41:00.171 - [WARNING] gae_exception:'600:fetch gae fail' https://www.youtube.com/watch?v=WofngI1Hx30 

Jul 01 13:41:00.586 - [DEBUG] GAE GET https://r5---sn-vgqskn76.googlevideo.com/videoplayback?ipbits=0&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&ei=Xmk4W-ahLYaZjAT19IDoDw&ip=107.178.195.132&pl=28&itag=243&requiressl=yes&fexp=23709359&expire=1530445246&sparams=aitags,clen,dur,ei,expire,gcr,gir,id,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mip,mm,mn,ms,mv,pl,requiressl,source&key=cms1&mime=video%2Fwebm&dur=6592.833&keepalive=yes&lmt=1530109648519680&fvip=5&gcr=us&signature=4BB8C35679A74E6CFD4CB89E31089215C24B1F4B.4DD822079B20A1A80F325DB7FC3BEC6386D0B401&source=youtube&c=WEB&id=o-ALo7fQ6bXx9LGpk6pMs6ZfaFb2icp3ni7iK4CJV58_1S&clen=322574760&gir=yes&alr=yes&cpn=uPlDPin19rE0lUmw&cver=2.20180628&redirect_counter=1&rm=sn-qxoy76&cms_redirect=yes&ipbypass=yes&mip=107.178.194.76&mm=31&mn=sn-vgqskn76&ms=au&mt=1530423574&mv=m&range=69768655-69940737&rn=19&rbuf=4054 from:127.0.0.1:57072 

Jul 01 13:41:00.610 - [WARNING] 2600:6:300:9::e h1_request:Exception('time out',) inactive_time:21 task.timeout:15 

Jul 01 13:41:00.610 - [WARNING] 2600:6:300:9::e trace: 0:connect, 572:init, 443:request, 1142:Res, 124:request, 228:Res, 779:request, 235:Res, 3001:request, 262:Res, 1533:request, 236:Res, 1565:request, 241:Res, 1220:request, 279:Res, 1214:request, 236:Res, 1457:request, 351:Res, 947:request, 585:Res, 585:request, 268:Res, 1140:request, 225:Res, 924:request, 522:Res, 695:request, 552:Res, 643:request, 388:Res, 693:request, 584:Res, 3081:request, 279:Res, 815:request, 365:Res, 822:request, 226:Res, 1329:request, 271:Res, 759:request, 226:Res, 898:request, 270:Res, 2541:request, 7684:Res, 75:request, 685:Res, 666:request, 362:Res, 693:request, 533:Res, 1087:request, 316:Res, 1887:request, 851:Res, 878:request, 440:Res, 1724:request, 276:Res, 1000:request, 470:Res, 1587:request, 750:Res, 1408:request, 719:Res, 1234:request, 240:Res, 2008:request, 582:Res, 1353:request, 523:Res, 876:request, 645:Res, 542:request, 687:Res, 941:request, 229:Res, 2606:request, 460:Res, 3503:request, 573:Res, 4361:request, 225:Res, 1570:request, 475:Res, 3304:request, 528:Res, 4891:request, 266:Res, 2174:request, 381:Res, 2296:request, 786:Res, 4197:request, 650:Res, 4825:request, 634:Res, 4115:request, 2217:Res, 1384:request, 266:Res, 2161:request, 859:Res, 1786:request, 226:Res, 1427:request, 588:Res, 2012:request, 292:Res, 1773:request, 230:Res, 1406:request, 373:Res, 1096:request, 375:Res, 701:request, 617:Res, 645:request, 638:Res, 5723:request, 442:Res, 4069:request, 705:Res, 778:request, 273:Res, 4986:request, 680:Res, 8818:request, 597:Res, 516:request, 237:Res, 9156:request, 626:Res, 3111:request, 578:Res, 2414:request, 284:Res, 13471:request, 569:Res, 544:request, 227:Res, 902:request, 290:Res, 2742:request, 229:Res, 4612:request, 228:Res, 6931:request, 339:Res, 1292:request, 269:Res, 4118:request, 354:Res, 991:request, 432:Res, 1228:request, 413:Res, 720:request, 337:Res, 1435:request, 444:Res, 1010:request, 674:Res, 1465:request, 366:Res, 1065:request, 289:Res, 1524:request, 638:Res, 1276:request, 724:Res, 554:request, 338:Res, 1237:request, 394:Res, 796:request, 271:Res, 880:request, 229:Res, 5957:request,:15537, processed:90, transfered:23257462, sni:gang012208.appspot.com 

Jul 01 13:41:00.610 - [WARNING] retry_task_cb: POST None/_gh/ 

Jul 01 13:41:00.610 - [WARNING] POST None/_gh/ response_fail:retry timeout:15 

Jul 01 13:41:00.611 - [DEBUG] 2600:6:300:9::e worker close:down fail

**Comment by SeaHOH** [comment]
暂时退回稳定版，过两天发新版本。
