### ISSUE TITLE
PHP空间问题

### ISSUE THREAD

**Issue by supvesonico** [XX-net/XX-Net#1104]
状态页：Property    Value
XX-Net Version  2.3.0
Python Version  2.7.9
Sys Platform    linux2
OS System   Linux
OS version  #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)
OS release  3.16.0-4-686-pae
OS detail   Dist:debian; Version:8.2; ID:
language    zh_CN
architecture    32bit,ELF
Browser     Mozilla/5.0 (X11; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.2.1

php日志页：Sep 24 10:18:54 - [INFO] ------------------------------------------------------
PHP proxy Version : 3.2.3 (python/2.7.9 gevent/1.0.1 pyopenssl/0.14)
PHP Listen : 127.0.0.1:8088
## PHP FetchServers : ['https://xxnet-supvesonico.rhcloud.com/xxnet/index.php']

Sep 24 10:18:54 - [DEBUG] init_ca
Sep 24 10:19:01 - [DEBUG] PHP web_control 127.0.0.1:36583 POST /config?cmd=get_config
Sep 24 10:19:23 - [DEBUG] PHP web_control 127.0.0.1:36765 POST /config?cmd=get_config
Sep 24 10:20:07 - [DEBUG] qname= reply_server='114.114.114.114' record iplist=['54.165.171.56']
Sep 24 10:20:10 - [INFO] 127.0.0.1:35729 "STRIP CONNECT www.google.co.jp:443 HTTP/1.1" - -
Sep 24 10:20:10 - [INFO] 127.0.0.1:35731 "STRIP CONNECT twitter.com:443 HTTP/1.1" - -
Sep 24 10:20:10 - [INFO] 127.0.0.1:35732 "STRIP CONNECT twitter.com:443 HTTP/1.1" - -
Sep 24 10:20:30 - [INFO] 127.0.0.1:35875 "STRIP CONNECT twitter.com:443 HTTP/1.1" - -
Sep 24 10:20:50 - [INFO] 127.0.0.1:36035 "STRIP CONNECT twitter.com:443 HTTP/1.1" - -

证书全部导入，GAE浏览google等网页也非常正常，唯独php127.0.0.1:8088走的时候访问页面出现错误：安全连接失败

载入页面时到 www.google.co.jp 的连接被中断。

```
您尝试查看的页面无法显示，因为已收到数据的可靠性无法证实。
请联系网站的所有者，告知他们这个问题。
```

请问有人遇到过类似问题吗？php空间让朋友尝试，相同空间密码他没有问题～

**Comment by xxnet** [comment]
PHP代理有独立的证书，目前没有合并，因此要注意导入 data/php_proxy/CA.crt 到浏览器

在 2015年9月24日 上午9:45，supvesonico <notifications@github.com>写道：

**Comment by supvesonico** [comment]
证书已导入，然而还是不行……

**Comment by xxnet** [comment]
把完整的日志贴出来，你上面的日志里没有收到浏览器请求

2015-09-25 16:43 GMT+08:00 supvesonico <notifications@github.com>:

**Comment by supvesonico** [comment]
Sep 25 20:42:46 - [INFO] 127.0.0.1:58621 "STRIP CONNECT www.google.co.jp:443 HTTP/1.1" - -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58621)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/sonico/Download/XX-Net-2.3.0/php_proxy/local/proxylib.py", line 619, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/sonico/Download/XX-Net-2.3.0/php_proxy/local/proxy.py", line 763, in __init__
    SimpleProxyHandler.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/sonico/Download/XX-Net-2.3.0/php_proxy/local/proxylib.py", line 1295, in handle_one_request
    return BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/sonico/Download/XX-Net-2.3.0/php_proxy/local/proxylib.py", line 1326, in do_METHOD
    return plugin.handle(self, **action[1])
  File "/home/sonico/Download/XX-Net-2.3.0/php_proxy/local/proxylib.py", line 726, in handle
    self.do_ssl_handshake(handler)
  File "/home/sonico/Download/XX-Net-2.3.0/php_proxy/local/proxylib.py", line 713, in do_ssl_handshake
    ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
-------------------------------------------------------分割线----------------------------------------------------------------
1L贴的就是全部日志了……这个是终端运行的报错，大致意思应该就是这个SSLContext没有定义了～我曾经试着将XX-net里面的py文件cp到/usr/lib/python2.7/目录里，结果就是php服务直接无法启动，再次观察终端日志发现是python的依赖被破坏了～

**Comment by xxnet** [comment]
怀疑系统自带的gevent 库不支持ssl，你试试删除系统的gevent库， XX-Net有自带的库。

2015-09-25 19:46 GMT+08:00 supvesonico <notifications@github.com>:

**Comment by supvesonico** [comment]
remove了系统的gevent库之后会报错，说请安装gevent;这个怎么解决呢？

**Comment by xxnet** [comment]
gevent 是有些坑的，为了一点性能带来挺多问题的。
改天重写整个php 模块吧。

现在的解决的思路：
1. 试试系统默认最新的gevent，可以试试pip 的方式安装
2. 到gevent官网，下载最新版本的版本
3. 试试goproxy/ 原版的goagent

不行就只能等重写一个了


2015-09-26 21:11 GMT+08:00 supvesonico <notifications@github.com>:

**Comment by supvesonico** [comment]
pip编译install了gevent之后确实不报错了然而：
Sep 29 17:13:10 - [WARNING] GET "http://127.0.0.1:8083/log?cmd=get_new&last_no=2" failed SSLError('The read operation timed out',)

Sep 29 17:13:10 - [INFO] 127.0.0.1:52880 "STRIP CONNECT www.google.co.jp:443 HTTP/1.1" - -

Sep 29 17:13:18 - [WARNING] GET "https://www.google.co.jp/?gws_rd=ssl" failed SSLError('The read operation timed out',)
新的日志警告而且是打不开……

**Comment by supvesonico** [comment]
自己偶尔折腾了一下还好现在可以打开并且浏览google以及twitter了，然而youtube还是不行……
最后问一下这个速度比较慢……是正常的吗？（比GAE还慢……）

**Comment by xxnet** [comment]
是正常的，因为host一般只有1个ip，全部流量在一个ip，限制很多

在 2015年9月29日 下午4:30，supvesonico <notifications@github.com>写道：
