### ISSUE TITLE
3.12.4 google 文档可以打开无法编辑，换ssr就正常了。

### ISSUE THREAD

**Issue by illtree** [XX-net/XX-Net#11055]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
给点对应的日志。。。

**Comment by SeaHOH** [comment]
#11438
