### ISSUE TITLE
部署自己得APPID 但是在同意授权后 得到的是405 然后就没法继续部署了

### ISSUE THREAD

**Issue by 1747672002** [XX-net/XX-Net#11059]
部署自己得APPID的时候，提示登录google账号，登录后，又让授权，点击授权后，页面就出现一段json
{"error":405,"message":"No routing path can be found for the request."}
然后就没办法继续部署了 请问哪位大佬知道这个问题该怎么解决

**Comment by SeaHOH** [comment]
对应连接的日志

**Comment by 1747672002** [comment]
已经解决了，问题原因是我这边本地的端口号被占中了 谢谢你的关心帮助 ^_^
