### ISSUE TITLE
，，

### ISSUE THREAD

**Issue by yonghuming9** [XX-net/XX-Net#11056]
，，

**Comment by Zmm1977** [comment]
真乃人才也！

**Comment by AnyWAT** [comment]
👀貌似 cacert.pem 没按 https://github.com/XX-net/XX-Net/issues/11010 处理？

**Comment by fredericky123** [comment]
效果何如？

**Comment by AnyWAT** [comment]
👀连接池趋近0计1次

**Comment by yonghuming9** [comment]
@fredericky123 
速度快慢，最终取决于自家的带宽与ip质量。
我这里目前还行，电信。


@AnyWAT 
一直盯着那里看啥呢，，

你重新下载一份，第一个包打包时没在意，里面有我的缓存，刚才又重新上传了一份新的。

**Comment by liuliuquick** [comment]
不错，是从3.10.4改过来的，但是又增加了congfig.json,方便了多appid用户。

**Comment by AnyWAT** [comment]
基于XX-Net-3.12.0原版，自用做的调试——是从3.10.4改过来的？
增加了congfig.json。。。莫名其妙🤣

**Comment by AnyWAT** [comment]
疑点：XX-Net-3.12.0文件时间为 5/24 11:20 而 XX-Net-3.12.0.1文件时间为 5/23 20:20

**Comment by asmosn** [comment]
IP很少，用不了一会儿断开

**Comment by yonghuming9** [comment]
@asmosn
![2](https://user-images.githubusercontent.com/40242830/42297712-f55733b4-8033-11e8-8388-1ad905aa9d7f.jpg)


我这里很稳定
![232](https://user-images.githubusercontent.com/40242830/42297753-3fc487c6-8034-11e8-9d72-8c472968635e.jpg)

找个30分钟以上的长视频测试
https://www.youtube.com/channel/UCHAVHbV2Xan9029VEhT-8iQ/videos

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/42298634-93100c52-8039-11e8-9292-467110bd2fa4.png)
楼主可以试试3.12.4，说不定效果更好

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/42300279-432ce58a-8042-11e8-8160-d478981dc0b7.png)

**Comment by liuliuquick** [comment]
下载视频不全，还是3.10.4好用。

**Comment by aoisola1987** [comment]
卤煮怎么删了？
