### ISSUE TITLE
每次用google搜东西都要机器人验证，都要点图片，请问怎么解决

### ISSUE THREAD

**Issue by DestinyZou** [XX-net/XX-Net#11050]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by blob2015** [comment]
先看看自己是否安装了会自动链接的扩展，比如某些seo插件等等，如果可以，自己看看都有那些连接

**Comment by Eri5Ch** [comment]
请认真阅读wiki

https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
