### ISSUE TITLE
求助。。。装了两天了 还是“仅IPv6” 不可用

### ISSUE THREAD

**Issue by lukfeiyee** [XX-net/XX-Net#11052]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。
有大神能帮忙看一下吗？我真的是完全看不懂。。。。
诊断信息：XX-Net Status:

sys-platform: x86_64, Darwin-16.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
os-release: 16.4.0
os-detail: Release:10.12.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.4
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

Jul 02 23:21:45.597 - [DEBUG] create ssl timeout fail.

Jul 02 23:21:46.704 - [DEBUG] create ssl timeout fail.

Jul 02 23:21:48.636 - [WARNING] not enough ip

Jul 02 23:21:50.669 - [WARNING] not enough ip

Jul 02 23:21:58.638 - [WARNING] not enough ip

Jul 02 23:22:00.670 - [WARNING] not enough ip

Jul 02 23:22:08.641 - [WARNING] not enough ip

Jul 02 23:22:10.675 - [WARNING] not enough ip

Jul 02 23:22:18.643 - [WARNING] not enough ip

Jul 02 23:22:20.676 - [WARNING] not enough ip

Jul 02 23:22:28.644 - [WARNING] not enough ip

Jul 02 23:22:30.679 - [WARNING] not enough ip

Jul 02 23:22:38.648 - [WARNING] not enough ip

Jul 02 23:22:40.681 - [WARNING] not enough ip

Jul 02 23:22:45.946 - [DEBUG] create ssl timeout fail.

Jul 02 23:22:47.553 - [DEBUG] create ssl timeout fail.

Jul 02 23:22:48.653 - [WARNING] not enough ip

Jul 02 23:22:50.686 - [WARNING] not enough ip

Jul 02 23:22:58.654 - [WARNING] not enough ip

Jul 02 23:23:00.687 - [WARNING] not enough ip

Jul 02 23:23:08.656 - [WARNING] not enough ip

Jul 02 23:23:10.688 - [WARNING] not enough ip

Jul 02 23:23:18.657 - [WARNING] not enough ip

Jul 02 23:23:20.694 - [WARNING] not enough ip

Jul 02 23:23:28.275 - [DEBUG] GAEProxy web_control 127.0.0.1:58800 POST /config?cmd=get_config

Jul 02 23:23:28.658 - [WARNING] not enough ip

Jul 02 23:23:29.151 - [DEBUG] GAEProxy web_control 127.0.0.1:58752 POST /config?cmd=get_config

Jul 02 23:23:30.052 - [DEBUG] GAEProxy web_control 127.0.0.1:64203 POST /config?cmd=get_config

Jul 02 23:23:30.053 - [DEBUG] GAEProxy Web_control 127.0.0.1:58752 GET /scan_ip?cmd=get_range

@Jul 02 23:23:30.053 - [INFO] load ip range file:/Users/lufeier/Downloads/XX-Net-3.12.4/code/default/gae_proxy/local/ip_range.txt

Jul 02 23:23:30.695 - [WARNING] not enough ip

Jul 02 23:23:38.659 - [WARNING] not enough ip

Jul 02 23:23:40.698 - [WARNING] not enough ip

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Mac
问题讨论里面搜索也行
