### ISSUE TITLE
问个 一直存在的小问题，

### ISSUE THREAD

**Issue by yonghuming9** [XX-net/XX-Net#11065]
@xxnet @SeaHOH
谷歌浏览器，这个问题一直存在，请看图 和 路径。

.TMP后缀
![default](https://user-images.githubusercontent.com/40242830/42367499-08d72df0-8137-11e8-9a10-5615ab0edd7e.jpg)

表现在点击 高级 里的项就会产生
![1](https://user-images.githubusercontent.com/40242830/42367472-edab787e-8136-11e8-8010-07ce8428b5ed.jpg)

即使清除数据也在，需要手动删除，每天会产生，日久会累积很多。
![2](https://user-images.githubusercontent.com/40242830/42367593-5451e7fc-8137-11e8-89fd-d5f36e853123.jpg)

----------

请大家看看图中的自己路径 是否和我一样产生很多 .TMP 后缀。
不知是谷歌浏览器问题还是XX-Net问题 ？

**Comment by yonghuming9** [comment]
原始是这样 才对
![default](https://user-images.githubusercontent.com/40242830/42368534-dce3a6bc-8139-11e8-9d2f-f46a51b8519f.jpg)

**Comment by AnyWAT** [comment]
Click&Clean https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod

**Comment by yonghuming9** [comment]
呵，什么年代了，还用这玩意“Click&Clean”

**Comment by SeaHOH** [comment]
你的 Chrome 是一直更新的吗？什么时候出现这个问题的？
建议在`设置`=>`其他人`中新添个用户试试。
![x2scrap2](https://user-images.githubusercontent.com/8470820/42369123-8235941e-80f8-11e8-9c02-8a44ef54e2c3.png)

**Comment by yonghuming9** [comment]
![884401](https://user-images.githubusercontent.com/40242830/42369460-a059eba4-813c-11e8-9eac-bd2c347afb81.jpg)

**Comment by yonghuming9** [comment]
难道你们点XX-Net 高级 里的项不会产生？？
我就不信，，

**Comment by yonghuming9** [comment]
其实，好像是 连接启动 了本地的html

**Comment by fredericky123** [comment]
天啊 我也有！
![image](https://user-images.githubusercontent.com/13982749/42370382-3110b98c-813f-11e8-9ab9-fea17dbf631f.png)

**Comment by yonghuming9** [comment]
眼见为实，录给动画大家看


![3332221111](https://user-images.githubusercontent.com/40242830/42371932-7754c77c-8143-11e8-805c-622fb6ae7d1d.gif)

**Comment by yonghuming9** [comment]
动画怎么这么慢啊，录制的时候很快

**Comment by SeaHOH** [comment]
添加个新用户试试
