### ISSUE TITLE
等待扫描IP，建议开启IPv6。求解决~

### ISSUE THREAD

**Issue by ChrisX17** [XX-net/XX-Net#11067]
今天突然出现这种情况，求解决

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:0
ipv4-status: unknown
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
ipv4-status: unknown
ipv6-status: OK
🙌

**Comment by ChrisX17** [comment]
ipv4正常了，但还是原来的问题。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.11.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴运行 netsh int ipv6 show teredo 结果（无需IP地址的2行）

**Comment by AnyWAT** [comment]
再启动一个XX-Net（挤出貌似已不正常的），如不行，先禁用再启用网络

**Comment by ChrisX17** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : dormant

**Comment by AnyWAT** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient default 更换系统默认服务器

**Comment by ChrisX17** [comment]
管理员执行命令后还是enterpriseclient

**Comment by ChrisX17** [comment]
取消勾选IPv6协议在哪里操作？

**Comment by AnyWAT** [comment]
网络设置

**Comment by ChrisX17** [comment]
关闭之后再开启还是不行

**Comment by AnyWAT** [comment]
用最新版本3.12.8？

**Comment by ChrisX17** [comment]
更新完成后可以了，谢谢
