### ISSUE TITLE
还没修复啊。。。12.7 依旧报错。。。也是看一会 黑屏 然后报错。。没人和我一样吗？

### ISSUE THREAD

**Issue by Gongqiao24** [XX-net/XX-Net#11068]
![11111](https://user-images.githubusercontent.com/20225809/42387365-ae3fabd6-8174-11e8-8e19-758a00334cec.png)

**Comment by Gongqiao24** [comment]
现在还好 不是每个视频都报错..

**Comment by Gongqiao24** [comment]
![1231231](https://user-images.githubusercontent.com/20225809/42387951-86c80394-8176-11e8-94e6-ae4a64423ec4.png)
@SeaHOH

**Comment by SeaHOH** [comment]
各人网络不同，看发布说明调小接收缓冲，当然速度也会有所降低。

**Comment by Gongqiao24** [comment]
@SeaHOH 所以说我现在要再调小一点咯？？默认是256？？

**Comment by Gongqiao24** [comment]
@SeaHOH 无论是64还是2048.。。调了都是会出错。。

**Comment by yeezylife** [comment]
会不会是你自己的问题呀 我昨天看1080P 60帧 一个视频看了半小时没断流

**Comment by SeaHOH** [comment]
估计还是网络本身的原因，下个版本会把范围放宽至 8-2048KB。

**Comment by standritsu** [comment]
只能调低缓冲牺牲速度了，超过3000k在我这比较容易黑，不过goproxy两万都没事，同是ipv6

**Comment by standritsu** [comment]
@SeaHOH TLS，ipv6不能用quic吧

**Comment by SeaHOH** [comment]
还是 XX-Net 的处理有问题，3.10.4 后改动太大，实在没时间去排查。

**Comment by ablebodied** [comment]
我的也是这样的问题

**Comment by SeaHOH** [comment]
#11106
测试下是否完全修复

**Comment by AnyWAT** [comment]
https://github.com/out0fmemory/Goproxy-Always-Available/issues/21
