### ISSUE TITLE
[发布]3.12.8 增加全局设置级别 (gae_proxy)

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#11061]
## 新版改进（3.12.5）：
* gae_proxy 模块增加全局设置级别用于调整参数，可在网页界面中设置
* 增加自定义连接缓冲大小设置以适应不同的网络状况，同上
* 增加 IPv6 优先级调整功能按钮 (win)
* 修复空闲状态时自动调整扫描可能导致扫描停止
* 修复 teredo 组策略检查和重置无法正常工作 (win)
* 修复一些小错误

## 新版改进（3.12.6）：
* 修复 3.12.5 gae_proxy 直连失败

## 新版改进（3.12.7）：
* 修复 3.12.6 gae_proxy GAE 失败

## 新版改进（3.12.8）：
* 调整参数
* 优化 IP 扫描策略

---

1. 从`被动`到`极端`一共 5 个级别，必须把选项上面的按钮切换成`ON`状态，才能提交修改设置。
因为设置级别只是把几个参数用一个级别来调整，你仍然可以单独设置其中的某个参数，这时会导致实际参数和设置级别不符。

1. 设置级别主要是调整连接池和 IP 扫描参数。
从`被动`到`正常`级别，在代理未使用的时候连接池趋向 0，已调整代码尽可能不影响随时重新使用。绝大部分用户使用这 3 档即可。
`积极`级别开始会保持一定的连接池数量，但是**不适合** IPv6 隧道短时间内频繁通断的情况。
`极端`级别未充分测试，不过大部分参数与原来相比，超出并不多。

1. 如 IP 数量始终达不到上限（`被动`60、`极端`200、其它 100）可尝试调大扫描线程。
空闲时，IP 数量会在 60-100% 范围波动，属于正常现象。
除非知道修改后的效果，否则不建议手动修改配置文件，只需选择这几个级别即可。

1. 连接缓冲，这个比较重要，反映到最大连接带宽。提交时无需切换按钮成`ON`状态。
当你的 IPv6 连接频繁地表现出不稳定时，可尝试减小这个参数。但是，如果网络条件确实对 IPv6 不友好，调整这个参数起到的作用就很有限。

1. 以上调节只能尽可能提高 XX-Net 本身的可靠性，以达到顺畅使用不稳定的 IPv6 隧道的目的。
如果网络状况实在太差，XX-Net 也无法正常使用。

1. 最后再提一句，不要纠结参数和状态的数值大小，使用体验才是根本，不顺畅了再去调节。
同时，记得参考上一条。

---

反正调试就搞了很久，但是受时间和实际网络限制还是不能完全兼顾所有的状况，有发现不对劲的地方请及时反馈。

**Comment by lldtcy** [comment]
@SeaHOH 托盘切换问题依旧，不过我发现了，的确是跟最新版的WIN10拨号程序有关系。如接路由器上网就一切正常。

**Comment by SeaHOH** [comment]
点击`分类_bug`标签，你会看到这个问题并没有进展，发布说明里面也没说解决了啊。

**Comment by whhxmwhh** [comment]
×
Switch prefix policies fail, you must authorized as admin.

**Comment by whhxmwhh** [comment]
Switch prefix policies is complete.
正在检查网络

**Comment by yeezylife** [comment]
那这个“连接缓冲”如果调大会产生什么效果呢

**Comment by yonghuming9** [comment]
### **哇塞👍，哇塞👍，哇塞👍**

### **思路清晰，编程功底扎实。**

### **既能有效拿出方案，又能凭借能力实现方案。**

正常模式下，30分钟以上的视频暂无断流。
![1](https://user-images.githubusercontent.com/40242830/42356939-df63e668-8107-11e8-91bb-2d7611a207d4.jpg)

**Comment by SeaHOH** [comment]
> 那请问这个“连接缓冲”如果调大会产生什么效果呢

网络状况好的情况下会增加连接的最大下载带宽，状况不好时反而可能影响 teredo 隧道连接的稳定性（对原生连接的负面影响不大），然后就是内存使用会增加。

> 正常模式下，测试30分钟以上的 缓冲暂无回流 视频暂无断流。

其实不一定，主要还是看网络状况，不同时间段网络状况差别很大，这是我这几天观察到的。
地域差别我就不清楚了，没那个条件测试。

**Comment by fredericky123** [comment]
12.5使用反馈：访问谷歌学术，出现ERR_CONTENT_DECODING_FAILED

**Comment by SeaHOH** [comment]
哦，完全没注意直连，等会儿就修复。

**Comment by yonghuming9** [comment]
@SeaHOH
![default](https://user-images.githubusercontent.com/40242830/42359663-ea49d03e-8115-11e8-93b9-4d8c85bb71ab.jpg)

这两句俺没懂啥意思？
网络状况好与不好 是指自家的网络状况还是IPv6隧道网络状况？

如果指的是自家宽带，那俺家买的是200M的光纤，是不是就可以把缓冲往上增加？
如果指的是IPv6隧道网络状况，那只能碰运气 碰时间段了。。。

一问一答，普及小白。

**Comment by SeaHOH** [comment]
这句对任意网络都适用，但主要是指 teredo 隧道的情况，因为它的封包都是 UDP，如果隧道承载的流量过大它只是丢包而不会限制流量，严重时可导致隧道连接中断。

**Comment by standritsu** [comment]
摸索了一下，建议开一个youtube视频，最好是帧速率高的，缓冲够快就调高设置级别，缓冲速度不够就慢慢调低直到网速足够为止，然后慢慢加大接收缓冲，直到会出现断流为止。

**Comment by yonghuming9** [comment]
正在看你给的“分块传输原理"  https://en.wikipedia.org/wiki/Chunked_transfer_encoding

看了半天还是没理清逻辑之间。
太绕

**Comment by ablebodied** [comment]
配置文件里面的参数的意义哪里可以看到呢？

**Comment by huangkio** [comment]
3.12.7 google账号无法登录，大家有这种情况吗

**Comment by SeaHOH** [comment]
> 配置文件里面的参数的意义哪里可以看到呢？

顾名思义，或者看源码理解。

> 总IP数只有100，怎么设置的更多啊

手动修改配置文件，不建议修改，改扫描线程就足够应付默认设置覆盖不到的情况。

> 3.12.7 google账号无法登录，大家有这种情况吗

能正常登录

**Comment by asmosn** [comment]
哟西！ IP200+/延迟600-。googleplay页面也正常了
