### ISSUE TITLE
[方法]GAE APP绑定域名和自动签发的证书

### ISSUE THREAD

**Issue by happy1234367** [XX-net/XX-Net#11064]
# 部署APPID时地区选美国中部的，不要选亚洲，会出现莫名其妙的不稳定，不要选欧洲，经常超时；不知道美国是哪里就算了吧
# [原文点击这里，下面的内容作为讨论和问题吧，谢谢](https://github.com/happy1234367/ssl/wiki/Way)
# [*常见问题](https://github.com/happy1234367/ssl/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by SeaHOH** [comment]
记得会验证是否正常使用（好像就是需要提供网页服务），不然可能会收回域名，有什么对策吗？

**Comment by happy1234367** [comment]
@SeaHOH 谢谢关注。
最近tk域名似乎十分不严（不涉及侵权就不收回），去年我的tk转发到百度，一年不访问，tk都不管。如果实在不行的话......假如把网页访问服务端时候的那个message变得很长，伪装成一个只有文字的网站，也许可以？
![image](https://user-images.githubusercontent.com/25525577/42367600-59239528-8137-11e8-94c5-551a21d5edf5.png)

**Comment by happy1234367** [comment]
~~国外的DNS服务器解析一般比较慢~~,
### 使用国内的DNS服务器进行解析

> 国内的DNSPOD服务器可以为个人或非盈利机构免费解析。
### 在[这](www.dnspod.cn)，用QQ注册一个新用户
- 然后回到dottk你的主页
- 依次点击上方Services>My domains>下方manage domain
![image](https://user-images.githubusercontent.com/25525577/42368203-02207e06-8139-11e8-8685-060b7225183d.png)
- 然后management tools>nameservers>use custom nameservers
![image](https://user-images.githubusercontent.com/25525577/42368457-a8405b1c-8139-11e8-9957-e81746565f36.png)
![image](https://user-images.githubusercontent.com/25525577/42368494-c19280ea-8139-11e8-804d-cdf8bb08db0a.png)
- f1g1ns1.dnspod.net和f1g1ns2.dnspod.net这两个地址如图填入。点击蓝色更改键。

**Comment by fredericky123** [comment]
能否顺带科普下绑定域名和证书有何好处？效果很明显吗？非常感谢！

**Comment by happy1234367** [comment]
@fredericky123 [效果](https://plus.google.com/113984721138789488972/posts/1K8N496TNpa)

**Comment by fredericky123** [comment]
@happy1234367 感谢，动手试一试！

**Comment by fredericky123** [comment]
感觉这个功能可以整合进XX net的ipv4大法，类似于填appid一样填写自己的域名，成为继ipv6的又一方式。如果有专人负责就好了

**Comment by SeaHOH** [comment]
教程不完整

**Comment by happy1234367** [comment]
重要技巧：买免费域名一次可以买一大堆，批量生产

**Comment by happy1234367** [comment]
@SeaHOH 正在补

**Comment by happy1234367** [comment]
# 正在往下写，有兴趣可以自己研究下，谢谢理解

**Comment by happy1234367** [comment]
# 教程中的dns生效太慢，正在改

**Comment by happy1234367** [comment]
@SeaHOH @SeaHOH 这个方法写的可能差不多了，麻烦您看看有没有错误的地方，或者提一点建议，谢谢！

**Comment by SeaHOH** [comment]
好像 XX-Net 的服务端需要修改才能绑 CDN，你测试过吗？

**Comment by wooowooo** [comment]
用**国内**的dnspod没问题吗？

**Comment by SeaHOH** [comment]
普通人用下问题不大，但是最好不要用。

**Comment by happy1234367** [comment]
@SeaHOH 谢谢，一会增加个使用dottk自带dns的方法。另外目前这个方法只适合用g0proxy，如果xx后期也考虑增加个方法应该也不错，域名我（们）多捐一些

**Comment by happy1234367** [comment]
# 紧急修改
# DNSPOD A记录有限制，所以马上改

**Comment by happy1234367** [comment]
# 已经更新，使用tk自带DNS

**Comment by happy1234367** [comment]
@xxnet 这个方法不需要lP，直接直连gae，单线程可以较流畅播放2K视频

**Comment by SeaHOH** [comment]
用的就是谷歌给你分配的那几个 IP。

**Comment by SunZhizhong** [comment]
这个原理是通过SSL加密的方式绕过墙么？有机会可以详细解释一下这个方式的工作原理么？还有这个功能可不可以用类似模块的方式基层到XXNET中？谢谢。

**Comment by GLingDroid** [comment]
这个手机上不行啊，有没有高手弄一下。
原先quic是可以的

现在是这样：（xxx.tk是隐藏掉了自定义的域名）
好像dial时怎么往自个儿ipv6的本地地址查询这个域名呢？


I0708 05:10:56.112290   25850 dialer2.go:97] MULTIDIALER DialTLS("tcp", "xxx.tk:443") with good_addrs=0, bad_addrs=0
W0708 05:10:56.114585   25850 gaetransport.go:128] GAE *http.Transport.RoundTrip("https://xxx.tk/_gh/") error: dial tcp: lookup xxx.tk on [::1]:53: read udp [::1]:54088->[::1]:53: read: connection refused
W0708 05:10:56.114821   25850 gae.go:594] 127.0.0.1:51839 "GAE FETCH GET https://www.google.com/ HTTP/1.1" error: *net.OpError(dial tcp: lookup xxx.tk on [::1]:53: read udp [::1]:54088->[::1]:53: read: connection refused)
E0708 05:10:56.114986   25850 handler.go:96] 127.0.0.1:51839 Filter RoundTrip *gae.Filter error: dial tcp: lookup xxx.tk on [::1]:53: read udp [::1]:54088->[::1]:53: read: connection refused

**Comment by hg123** [comment]
我在手机上运行出现的错误是
X509 failed to load system roots and no roots provided

**Comment by happy1234367** [comment]
@GLingDroid force ipv6改为false，disable ipv6改为true试试

**Comment by GLingDroid** [comment]
一样的报错，
在试参数过程中，好像是这个域名查询不到为空的信息。

Android 7.1系统上移动网络时的默认dns无法更改，可能有关，
或者不能做像这样的域名alias，
或者因为用到droidproxy有关。

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/42418598-60d01fda-82d6-11e8-96d2-0126a6493b62.png)
点击自定义网域没反应，尝试了好几个代理，都无法切换到下一步骤 sad

**Comment by panpeach** [comment]
@happy1234367  
试注册了一个Freenom.com免费域名，按教程已成功，youtube速度在3000~15000之间变动。
请教几个问题：
1，一个邮箱可注册多个域名？还是一个邮箱只能注册一个域名？注册时电话可乱写么？
2，一个google账号有12个 AppID，一个AppID绑定一个自定义网域，还是12个AppID绑定同一个网域？
3，因为每个AppID每天有流量限制，若每个AppID只能绑定一个自定义网域，那么流量不够用还得注册
     多个免费域名，每个AppID绑定一个免费域名，是不是这样啊？
4，你说能批量生产注册免费域名，怎么搞啊？能不能出个注册机？

**Comment by SeaHOH** [comment]
@panpeach 
1. 可以注册多个，电话这个不一定，不要求电话验证的一般可以乱填，花钱买的**重要域名**一定要填真实信息。

1. 必须不同。

1. 同上。

1. 不要搞事，小心大家都没得用。

**Comment by GLingDroid** [comment]
手机上的问题可以通过删除freen0m的AAAA的记录解决。。。

freen0m一个账号可以免费注册4个.tk域名。。。

这个方法有最后一个问题就是没法上g00gle学术，验证码也刷不出来。。。期待能有方法至少刷出验证码。。。

**Comment by panpeach** [comment]
@SeaHOH 谢谢解答，知道了，再去注册几个免费域名，用一段时间看看是否稳定。
PS，其实速度和我再用的IPV6差不多，只是不用找IP，这点很方便。

**Comment by GLingDroid** [comment]
手机上还是没有解决，过段时间就又自个儿dial [::1]:53: 了。。。
得在pc上用一下，然后手机能正常dial ipv4的了，诡异啊。。。

**Comment by GLingDroid** [comment]
不对，终于抓到怎么回事了。。。
手机得开热点才能正常dial，否则就dial本地ipv6地址的53端口。。。

这是闹哪样啊。。。

**Comment by GLingDroid** [comment]
这种问题很有可能是跟手机rom有关了，
不知道其他在手机上用此方法的，有没有同样问题。

**Comment by panpeach** [comment]
第一个邮箱注册了25个域名（额满）。且25个App全部绑定成功，每个域名单独测试能翻。
再用第二个邮箱注册域名，收到短信验证点击链接继续填写资料继续注册，提示错误死活无法注册。
换个邮箱再注册，收到短信验证，点击链接进去填写资料后，还是显示错误注册失败。
IP，邮箱，资料电话等都换过，就连一个域名都不能注册，不知道哪里不对劲，厥倒。

**Comment by SeaHOH** [comment]
记得清除 cookies，还有 IP 地址不要是同一个。

**Comment by fredericky123** [comment]
为什么删了

**Comment by SeaHOH** [comment]
其实这并不是个新方法，很多年前就能用了，哪个愿意义务劳动重新写下也行。
