### ISSUE TITLE
600:gae_exception:'602:ip not support GAE'

### ISSUE THREAD

**Issue by l3125831q** [XX-net/XX-Net#11071]
600:gae_exception:'602:ip not support GAE' http://XXX  gae_exception:'602:ip not support GAE' http://XXX
打开网页时，只显示这么一串，怎么办？

**Comment by SeaHOH** [comment]
版本？
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 试试。

**Comment by AnyWAT** [comment]
貌似连接池较小或IP延时较大的锅，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#global_setting 关闭“自动调整扫描线程数”，检查IP

**Comment by l3125831q** [comment]
@AnyWAT 全局设置“被动”后提交，切回来又变成正常了，"总IP数"增大为默认100的3-5倍  这个没找到啊

**Comment by AnyWAT** [comment]
提交设置级别 OFF改为ON再提交才行，"总IP数"得修改配置文件 config.json

**Comment by l3125831q** [comment]
@AnyWAT 我把原来的XX-net删了，又下了个新的，就可以了，谢谢了
