### ISSUE TITLE
cookie有问题啊

### ISSUE THREAD

**Issue by GLingDroid** [XX-net/XX-Net#11076]
比如你退出google的登入了，gae通过隧道走ipv6就没法再登入了，提示浏览器没打开cookie。
实际浏览器cookie当然打开的。

我是google长时间没登入自动退出登入状态了，现在想蹬入就出现这个问题。
试了下github用gae时是同样情况，github不用gae时就没问题，然后直连登入后，再切gae，它的登入状态是虚假的，要发issue时就失败了。

xx版本是3.12.3 ，pc的chrome ，ie 和android 都是同样的问题。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/releases
![default](https://user-images.githubusercontent.com/37962734/42412123-fc204634-8238-11e8-99cb-ab3b8b370828.png)

**Comment by GLingDroid** [comment]
呃。。。
唔。。。

sorry，没留意更新。。。

**Comment by SeaHOH** [comment]
测试版不用在意，但稳定版最好设定通知下。

**Comment by SeaHOH** [comment]
嗯，你这个好像超出稳定版了。。。
