### ISSUE TITLE
IPv6不能用很久了，有些teredo服务器都不存在了居然还ping的通

### ISSUE THREAD

**Issue by hugohehuan** [XX-net/XX-Net#11075]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
否
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

用一个国外网站查询到两个常见的teredo服务器IP如下

> Your Results:
> teredo.ngix.ne.kr > Not found
> teredo.managemydedi.com > Not found 

但是，nslookup可以查出来，也能ping通，1.1.1.1、8.8.8.8都不靠谱

> 服务器:  1dot1dot1dot1.cloudflare-dns.com
> Address:  1.1.1.1
> 
> 非权威应答:
> 名称:    teredo.managemydedi.com
> Address:  221.179.46.194

> 服务器:  google-public-dns-a.google.com
> Address:  8.8.8.8
> 
> 非权威应答:
> 名称:    teredo.managemydedi.com
> Address:  221.179.46.194

而且这个IP的ping值相当低

> 您查询的IP:221.179.46.194
> 本站数据：广东省广州市  移动参考数据1：广东广州  移动参考数据2：重庆市 移动

呵呵

**Comment by SeaHOH** [comment]
你这是 DNS 污染
https://github.com/XX-net/XX-Net/blob/b129a350d159e71d2e01e9424db23021f219d18a/code/default/gae_proxy/local/ipv6_tunnel/pteredor.py#L59-L77
