### ISSUE TITLE
请问通过xx-net下载文件，大文件经常损坏，是硬伤吗？

### ISSUE THREAD

**Issue by lenceliu** [XX-net/XX-Net#11072]
下载大一点的文件经常是损坏的，是xxnet硬伤，还是我的网络问题呢？

**Comment by liuliuquick** [comment]
我用3.10.4才不会视频下载不全。

**Comment by SeaHOH** [comment]
实际上我用最新版下载大文件也不会错误，估计是网络不好时，哪里没有处理好。
3.10.4 到 3.10.5 修改太多，位置不好找。

**Comment by SeaHOH** [comment]
#11106
测试下是否完全修复
