### ISSUE TITLE
闲置一段时间之后 会出现“连接尚未建立”

### ISSUE THREAD

**Issue by yeezylife** [XX-net/XX-Net#11074]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.12.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:101
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 232
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
----------------------------------------------------------------------------------------------
今天已经出现两次了，昨天也出现过这问题。重开一次XXnet就能正常使用了  这是啥问题。。
我目前使用的是最新测试版3.12.7   用的时候挺正常 但是闲置一段时间就容易出现这情况

**Comment by SeaHOH** [comment]
3.12.5 版本开始改成不使用代理时趋向于 0 连接池，因为空闲时基于连接池的 IP 存活率太低。

但是还有点小问题，正在测试修改，估计明天就能发新版。

**Comment by yeezylife** [comment]
我自己随便调了一下 似乎和全局设置的等级没太大关系  我用“正常”和“积极”都会出现这个情况

**Comment by SeaHOH** [comment]
确实和全局设置级别关系不大，就是这样设计的，根据网络状况不同会有不同表现，总体是不使用代理时趋向于 0 连接池。
这是测试版，现在还有比较明显的 bug，等会儿发个新版，估计就不会再出现`空闲`和`尚未连接`时不能使用代理的情况。

**Comment by SeaHOH** [comment]
全局设置级别`正常`以前，根据网络状况不同会有不同表现，总体是不使用代理时趋向于 0 连接池。
全局设置级别`正常`以后，根据网络状况不同会有不同表现，总体是会一直保持一定数量的连接池。

这是测试版，现在还有比较明显的 bug，等会儿发个新版，估计就不会再出现`空闲`和`尚未连接`时不能使用代理的情况。

**Comment by zzgpku** [comment]
从3.12.4之后的版本一直都有这个问题，现在在用3.12.2没有问题

**Comment by AnyWAT** [comment]
貌似“被动”但关闭了“自动调整扫描线程数”且增大“最大扫描线程数”（以维持有效IP数趋近或达到“总IP数”），未见趋向于 0 连接池。
