### ISSUE TITLE
求问，miredo安装好能上网之后，能重新打开系统保护吗？

### ISSUE THREAD

**Issue by VVingerfly** [XX-net/XX-Net#11073]
miredo安装好了，xxnet没问题，能上网了。

现在能重新打开系统保护吗？
还是要一直保持系统保护状态关闭？？？

请问大家知道吗？？

**Comment by SeaHOH** [comment]
试下呗。

**Comment by erdcy** [comment]
@VVingerfly 楼主写个miredo教程吧 
鼓掌……鼓掌……鼓掌……

**Comment by VVingerfly** [comment]
@erdcy 照着https://github.com/XX-net/XX-Net/wiki/IPv6-Mac这个文档做的
