### ISSUE TITLE
SMART ROUTER 是否可以考虑加入HTTP拆包 以反运营商HTTP劫持

### ISSUE THREAD

**Issue by myjlpt** [XX-net/XX-Net#11089]
RT

最近江苏这边联通运营上劫持，测试拆包试了，可以欺骗。当然有部分拆包似乎不响应。自己能力有限。(劫持就算了还是明文的,客户信息，账号，注册证件都一览无余)
SMART ROUTER是否可以尝试下？

**Comment by SeaHOH** [comment]
没看懂，一般明文可以劫持，加密不行。
你的意思具体是什么？

还有就是这种劫持 ISP 不会修改你的数据，如果有修改多半不是 ISP 的手段。
ISP 一般只是劫持首次访问和无法解析的域名。

**Comment by myjlpt** [comment]
@SeaHOH 
请看这里
https://github.com/GameXG/ProxyClient/issues/9

我在看ttl 反劫持 这个貌似效果更好，但应该影响连接速度

**Comment by SeaHOH** [comment]
没必要折腾这，就是我上面说的最后一条。
电信的可以自己登录关闭，联通不清楚，实在不行打电话让他关掉也行。

**Comment by myjlpt** [comment]
没用，你电话之后最多好两个月，1个季度。还恢复劫持.这种劫持我是一年3个电话。算下时间基本都是1个季度吧。

**Comment by SeaHOH** [comment]
反复多次就投诉呗，不然就换 ISP。

**Comment by myjlpt** [comment]
我这不就是想，既然拆包有用，而且几乎不消耗资源，是否可以尝试下实现。这样就不要我加前置了。而且这个前置不稳定。
