### ISSUE TITLE
xxnet-version: 3.12.8  感觉是稳定了。

### ISSUE THREAD

**Issue by whhxmwhh** [XX-net/XX-Net#11085]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

XX-Net Status:

sys-platform: x86, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:5
worker: h1:21 h2:0
scan-ip-thread-num: 1
ip-quality: 290
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by whhxmwhh** [comment]
Teredo 隧道	合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)
这个是关键。只要这个隧道合格的就可以飞。

**Comment by ablebodied** [comment]
YouTubeh还会失败吗？

**Comment by GoodSake** [comment]
youtube 480p流畅。すげえ!
