### ISSUE TITLE
为啥按照臭大街法则设置了，有效IP还是一直100，延迟很多呢？小白一枚！完全不理解照搬设置。

### ISSUE THREAD

**Issue by aswellashaha** [XX-net/XX-Net#11083]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:90
ipv4-status: OK
ipv6-status: OK
connected-link: new:3
worker: h1:6 h2:0
scan-ip-thread-num: 180
ip-quality: 531
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/42420338-f4baeb10-82f6-11e8-9549-6d17f454a5d0.png)
![default](https://user-images.githubusercontent.com/37962734/42420367-3488ac78-82f7-11e8-9d99-21bb7605bfd9.png)

**Comment by hongkonghot** [comment]
应该是程序限定的数，我也是100，但感觉足够用了
