### ISSUE TITLE
老是显示 "仅IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by sky2917** [XX-net/XX-Net#11088]
老是显示 "仅IPv6" 不可用，请检查。重新启用 IPv6 隧道，重启电脑，又连上了。但一会又断，还是显示 "仅IPv6" 不可用，请检查。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:15
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1713
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**日志：**

Jul 09 12:15:43.949 - [WARNING] network IPv6 fail

Jul 09 12:15:43.963 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2721

Jul 09 12:15:43.963 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:43.963 - [DEBUG] connect 2806:10a0:cfff:5::c network fail

Jul 09 12:15:44.470 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2722

Jul 09 12:15:44.470 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:44.470 - [DEBUG] connect 2600:1:200::e network fail

Jul 09 12:15:47.219 - [WARNING] task POST None /_gh/ timeout

Jul 09 12:15:47.219 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 09 12:15:47.219 - [WARNING] gae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM

Jul 09 12:15:50.938 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2723

Jul 09 12:15:50.939 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:50.940 - [DEBUG] connect 2001:1970:1:2053::10 network fail

Jul 09 12:15:50.945 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2724

Jul 09 12:15:50.945 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:50.945 - [DEBUG] connect 2607:f8b0:4000:3e::9 network fail

Jul 09 12:15:52.803 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2725

Jul 09 12:15:52.803 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:52.803 - [DEBUG] connect 2001:b032:3900:1::f network fail

Jul 09 12:15:52.990 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2726

Jul 09 12:15:52.990 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:52.990 - [DEBUG] connect 2a00:1450:4002:4::9 network fail

Jul 09 12:15:53.367 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2727

Jul 09 12:15:53.367 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:53.367 - [DEBUG] connect 2a00:1450:4002:5::7 network fail

Jul 09 12:15:53.585 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2728

Jul 09 12:15:53.585 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:53.586 - [DEBUG] connect 2001:b032:a501::e network fail

Jul 09 12:15:53.849 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2729

Jul 09 12:15:53.850 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:53.850 - [DEBUG] connect 2a02:8200:1:3::c network fail

Jul 09 12:15:53.967 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2730

Jul 09 12:15:53.967 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:53.967 - [DEBUG] connect 2001:13d0:0:e::e network fail

Jul 09 12:15:54.369 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2731

Jul 09 12:15:54.369 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:54.369 - [DEBUG] connect 2001:d08:11:204::13 network fail

Jul 09 12:15:54.514 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2732

Jul 09 12:15:54.514 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:54.514 - [DEBUG] connect 2001:13d0:0:d::d network fail

Jul 09 12:15:54.974 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2733

Jul 09 12:15:54.974 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:54.974 - [DEBUG] connect 2806:10a0:cfff:5::c network fail

Jul 09 12:15:54.985 - [WARNING] network IPv6 fail

Jul 09 12:15:55.495 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2734

Jul 09 12:15:55.495 - [DEBUG] report_connect_fail network fail

Jul 09 12:15:55.495 - [DEBUG] connect 2600:1:200::e network fail

Jul 09 12:15:57.666 - [DEBUG] create ssl timeout fail.

Jul 09 12:15:58.789 - [WARNING] task POST None /_gh/ timeout

Jul 09 12:15:58.789 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 09 12:15:58.789 - [WARNING] gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=K1K3ncppQvcXYA9Oovb6BQ%3D%3D

Jul 09 12:16:01.846 - [WARNING] task POST None /_gh/ timeout

Jul 09 12:16:01.846 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 09 12:16:01.846 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Jul 09 12:16:01.954 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2735

Jul 09 12:16:01.954 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:01.955 - [DEBUG] connect 2001:1970:1:2053::10 network fail

Jul 09 12:16:01.957 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2736

Jul 09 12:16:01.957 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:01.957 - [DEBUG] connect 2607:f8b0:4000:3e::9 network fail

Jul 09 12:16:03.816 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2737

Jul 09 12:16:03.817 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:03.817 - [DEBUG] connect 2001:b032:3900:1::f network fail

Jul 09 12:16:04.004 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2738

Jul 09 12:16:04.004 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:04.004 - [DEBUG] connect 2a00:1450:4002:4::9 network fail

Jul 09 12:16:04.397 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2739

Jul 09 12:16:04.397 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:04.397 - [DEBUG] connect 2a00:1450:4002:5::7 network fail

Jul 09 12:16:04.609 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2740

Jul 09 12:16:04.609 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:04.609 - [DEBUG] connect 2001:b032:a501::e network fail

Jul 09 12:16:04.647 - [DEBUG] GAE GET https://twitter.com/i/timeline?composed_count=0&include_available_features=1&include_entities=1&include_new_items_bar=true&interval=10000&latent_count=0&min_position=1016153051223060482&oldest_unread_id=0 from:127.0.0.1:64031

Jul 09 12:16:04.863 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2741

Jul 09 12:16:04.863 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:04.863 - [DEBUG] connect 2a02:8200:1:3::c network fail

Jul 09 12:16:04.979 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2742

Jul 09 12:16:04.979 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:04.979 - [DEBUG] connect 2001:13d0:0:e::e network fail

Jul 09 12:16:05.397 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2743

Jul 09 12:16:05.397 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:05.397 - [DEBUG] connect 2001:d08:11:204::13 network fail

Jul 09 12:16:05.533 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2744

Jul 09 12:16:05.534 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:05.534 - [DEBUG] connect 2001:13d0:0:d::d network fail

Jul 09 12:16:05.988 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2745

Jul 09 12:16:05.988 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:05.988 - [DEBUG] connect 2806:10a0:cfff:5::c network fail

Jul 09 12:16:06.002 - [WARNING] network IPv6 fail

Jul 09 12:16:06.519 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2746

Jul 09 12:16:06.519 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:06.519 - [DEBUG] connect 2600:1:200::e network fail

Jul 09 12:16:12.960 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2747

Jul 09 12:16:12.963 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:12.963 - [DEBUG] connect 2001:1970:1:2053::10 network fail

Jul 09 12:16:12.974 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2748

Jul 09 12:16:12.975 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:12.975 - [DEBUG] connect 2607:f8b0:4000:3e::9 network fail

Jul 09 12:16:14.830 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2749

Jul 09 12:16:14.830 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:14.830 - [DEBUG] connect 2001:b032:3900:1::f network fail

Jul 09 12:16:15.020 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2750

Jul 09 12:16:15.020 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:15.020 - [DEBUG] connect 2a00:1450:4002:4::9 network fail

Jul 09 12:16:15.421 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2751

Jul 09 12:16:15.421 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:15.421 - [DEBUG] connect 2a00:1450:4002:5::7 network fail

Jul 09 12:16:15.615 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2752

Jul 09 12:16:15.615 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:15.615 - [DEBUG] connect 2001:b032:a501::e network fail

Jul 09 12:16:15.877 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2753

Jul 09 12:16:15.877 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:15.877 - [DEBUG] connect 2a02:8200:1:3::c network fail

Jul 09 12:16:15.992 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2754

Jul 09 12:16:15.992 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:15.992 - [DEBUG] connect 2001:13d0:0:e::e network fail

Jul 09 12:16:16.415 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2755

Jul 09 12:16:16.415 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:16.415 - [DEBUG] connect 2001:d08:11:204::13 network fail

Jul 09 12:16:16.548 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2756

Jul 09 12:16:16.548 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:16.548 - [DEBUG] connect 2001:13d0:0:d::d network fail

Jul 09 12:16:16.999 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2757

Jul 09 12:16:16.999 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:16.999 - [DEBUG] connect 2806:10a0:cfff:5::c network fail

Jul 09 12:16:17.007 - [WARNING] network IPv6 fail

Jul 09 12:16:17.550 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2758

Jul 09 12:16:17.550 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:17.550 - [DEBUG] connect 2600:1:200::e network fail

Jul 09 12:16:19.679 - [WARNING] task POST None /_gh/ timeout

Jul 09 12:16:19.679 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 09 12:16:19.679 - [WARNING] gae_exception:'600:fetch gae fail' https://twitter.com/i/timeline?composed_count=0&include_available_features=1&include_entities=1&include_new_items_bar=true&interval=10000&latent_count=0&min_position=1016153051223060482&oldest_unread_id=0

Jul 09 12:16:23.977 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2759

Jul 09 12:16:23.978 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:23.979 - [DEBUG] connect 2001:1970:1:2053::10 network fail

Jul 09 12:16:23.986 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2760

Jul 09 12:16:23.986 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:23.986 - [DEBUG] connect 2607:f8b0:4000:3e::9 network fail

Jul 09 12:16:24.947 - [DEBUG] GAE POST https://www.google-analytics.com/r/collect from:127.0.0.1:64247

Jul 09 12:16:25.837 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2761

Jul 09 12:16:25.837 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:25.838 - [DEBUG] connect 2001:b032:3900:1::f network fail

Jul 09 12:16:26.033 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2762

Jul 09 12:16:26.034 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:26.034 - [DEBUG] connect 2a00:1450:4002:4::9 network fail

Jul 09 12:16:26.433 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2763

Jul 09 12:16:26.433 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:26.433 - [DEBUG] connect 2a00:1450:4002:5::7 network fail

Jul 09 12:16:26.627 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2764

Jul 09 12:16:26.627 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:26.627 - [DEBUG] connect 2001:b032:a501::e network fail

Jul 09 12:16:26.890 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2765

Jul 09 12:16:26.890 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:26.890 - [DEBUG] connect 2a02:8200:1:3::c network fail

Jul 09 12:16:27.005 - [DEBUG] report_connect_fail IPv6 continue_fail_count:2766

Jul 09 12:16:27.005 - [DEBUG] report_connect_fail network fail

Jul 09 12:16:27.005 - [DEBUG] connect 2001:13d0:0:e::e network fail

Jul 09 12:16:27.317 - [WARNING] task POST None /_gh/ timeout

Jul 09 12:16:27.317 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 09 12:16:27.317 - [WARNING] gae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM

Jul 09 12:16:27.317 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnMgae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnMgae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM"

Jul 09 12:16:27.317 - [WARNING] GAE POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM request fail:"600:gae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnMgae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnMgae_exception:'600:fetch gae fail' https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJGWWtwSzhFdFR4TVJSd19fN01mRWx3NS1xSWJrQ1gzcjJwNmVLYzU4RGF0MUJmcWtOa3g0OEZMNEp0d1NwWHlFcG9Cdl83OVY2N3J0UXh1NFdIWTJaa3lMMGVpX2JSQUxNSHhFcmh0OXd2bTlLb1VVRWpsVXdWSXoxOXRTOHBSRzcwVExMVl9tTzBEQ3A3S1VUSnB1RVM0MjlZeWFSQ1ctNFFoNDlDSmtkUFljNUlrdjgaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM"

**Comment by SeaHOH** [comment]
升级 3.12.8，可尝试调节参数，如果还是这样建议换其它工具，近来 IPv6 隧道连接不稳定。

**Comment by AnyWAT** [comment]
老是显示 "仅IPv6" 不可用，请检查——
禁用再启用网络，或再次运行一个XX-Net（挤出貌似已不正常的），手动检查IP
关闭“自动调整扫描线程数”，适当增大“最大扫描线程数”以维持较小的IP延时。。。

**Comment by aliasch** [comment]
也出现同样的问题。
