### ISSUE TITLE
这个缓存是干嘛用的？

### ISSUE THREAD

**Issue by acrossabc** [XX-net/XX-Net#11080]
很久没怎么上XXNET，前天更新了下版本。
这个缓存是用在哪些方面呢/
![r4r32rwr35wt4wt4tswt4w6wg4w6w](https://user-images.githubusercontent.com/16570906/42416803-03a594fa-82ab-11e8-8b8a-7b081be8847e.JPG)

**Comment by SeaHOH** [comment]
看发布说明
