### ISSUE TITLE
检查IP的功能有问题吧

### ISSUE THREAD

**Issue by jyuan15** [XX-net/XX-Net#11086]
导入后，“待测IP数”和“有效IP数”几乎一样多，开始测试后，二者同时减少。

正常情况不应该是“待测IP数”逐渐减少、“有效IP数”从0逐渐增加吗？

**Comment by SeaHOH** [comment]
手动检查功能估计是坏的，之前有人提过，还没检查。

**Comment by SeaHOH** [comment]
可能是你的 IP 问题。
我认为这个功能暂时没有啥大用处了，反正 IP 一直能扫，如果网络不行，再检查也没用。
