### ISSUE TITLE
所有设置完之后，仍连不上网，打开时显示一串代码，跪求解答

### ISSUE THREAD

**Issue by xiaohuaihuaihuai** [XX-net/XX-Net#11093]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

所有设置完之后，仍连不上网，打开时显示一串代码。如600:gae_exception:'600:fetch gae fail' https://www.google.com.hk/webhp?hl=zh-CN&sourceid=cnhp&gws_rd=sslgae_exception:'600:fetch gae fail' https://www.google.com.hk/webhp?hl=zh-CN&sourceid=cnhp&gws_rd=sslgae_exception:'600:fetch gae fail' https://www.google.com.hk/webhp?hl=zh-CN&sourceid=cnhp&gws_rd=ssl   跪求大佬们解答，感激不尽
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by xiaohuaihuaihuai** [comment]
IPv6 状态(如何开启)  Fail

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
贴运行 netsh int ipv6 show teredo 结果
![default](https://user-images.githubusercontent.com/37962734/42447536-d198bf98-83ac-11e8-93de-483f4bc3a584.png)

**Comment by xiaohuaihuaihuai** [comment]
对的  可能有一些简单的都不太了解  希望您能谅解

**Comment by xiaohuaihuaihuai** [comment]
我的运行结果图一直上传失败 伤心

**Comment by AnyWAT** [comment]
第一次使用：运行 
![default](https://user-images.githubusercontent.com/37962734/42448381-8e3c2318-83af-11e8-8d31-6be9f7c721c0.png)
上传图片、下载文件需代理
复制、粘贴纯文本即可

**Comment by xiaohuaihuaihuai** [comment]
以太网适配器 本地连接*:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Juniper Network Connect Virtual Adapter
   物理地址. . . . . . . . . . . . . : 00-FF-B0-8A-98-03
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 无线网络连接 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Virtual WiFi Miniport Adapter
   物理地址. . . . . . . . . . . . . : 2E-D0-5A-93-A9-5B
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 无线网络连接:

   连接特定的 DNS 后缀 . . . . . . . : nano.hit.edu.cn
   描述. . . . . . . . . . . . . . . : Qualcomm Atheros AR9485 Wireless Network Adapter
   物理地址. . . . . . . . . . . . . : 2C-D0-5A-93-A9-5B
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::1509:eac4:e621:1ab7%12(首选) 
   IPv4 地址 . . . . . . . . . . . . : 10.3.15.139(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年7月9日 星期一 AM 9:38:06
   租约过期的时间  . . . . . . . . . : 2018年7月17日 星期二 PM 15:37:53
   默认网关. . . . . . . . . . . . . : 10.3.15.1
   DHCP 服务器 . . . . . . . . . . . : 10.3.15.1
   DHCPv6 IAID . . . . . . . . . . . : 304926810
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-17-A2-6B-2B-3C-97-0E-FC-86-C3
   DNS 服务器  . . . . . . . . . . . : 101.198.199.200
                                       114.114.114.114
   主 WINS 服务器  . . . . . . . . . : 10.3.15.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 本地连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Qualcomm Atheros AR8162/8166/8168 PCI-E Fast Ethernet Controller (NDIS 6.20)
   物理地址. . . . . . . . . . . . . : 3C-97-0E-FC-86-C3
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无


发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        手动        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        手动        256  fe80::/64                  11  本地连接
否        手动        256  fe80::/64                  15  本地连接*
否        手动        256  fe80::/64                  12  无线网络连接
否        手动        256  fe80::/64                  13  无线网络连接 2
否        手动        256  fe80::1509:eac4:e621:1ab7/128   12  无线网络连接
否        手动        256  fe80::7539:a583:2bc1:d929/128   13  无线网络连接 2
否        手动        256  fe80::788c:88aa:342d:98a3/128   15  本地连接*
否        手动        256  fe80::91ad:6f23:e6bd:1960/128   11  本地连接
否        手动        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        手动        256  ff00::/8                   11  本地连接
否        手动        256  ff00::/8                   15  本地连接*
否        手动        256  ff00::/8                   12  无线网络连接
否        手动        256  ff00::/8                   13  无线网络连接 2


Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 12          25        1500  connected     无线网络连接
 11           5        1500  disconnected  本地连接
 13           5        1500  disconnected  无线网络连接 2
 15          10        1400  disconnected  本地连接*

查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        50      0  ::1/128
        40      1  ::/0
        35      6  2001::/16
        30      2  2002::/16
        25      5  2001::/32
        20      3  ::/96
        10      4  ::ffff:0:0/96


接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 12: 无线网络连接

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite fe80::1509:eac4:e621:1ab7%12

接口 11: 本地连接

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::91ad:6f23:e6bd:1960%11

接口 13: 无线网络连接 2

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::7539:a583:2bc1:d929%13

接口 15: 本地连接*

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::788c:88aa:342d:98a3%15

===========================================================================
接口列表
 15...00 ff b0 8a 98 03 ......Juniper Network Connect Virtual Adapter
 13...2e d0 5a 93 a9 5b ......Microsoft Virtual WiFi Miniport Adapter
 12...2c d0 5a 93 a9 5b ......Qualcomm Atheros AR9485 Wireless Network Adapter
 11...3c 97 0e fc 86 c3 ......Qualcomm Atheros AR8162/8166/8168 PCI-E Fast Ethernet Controller (NDIS 6.20)
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0        10.3.15.1      10.3.15.139     25
        10.3.15.0    255.255.255.0            在链路上       10.3.15.139    281
      10.3.15.139  255.255.255.255            在链路上       10.3.15.139    281
      10.3.15.255  255.255.255.255            在链路上       10.3.15.139    281
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    306
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    306
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    306
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    306
        224.0.0.0        240.0.0.0            在链路上       10.3.15.139    281
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    306
  255.255.255.255  255.255.255.255            在链路上       10.3.15.139    281
===========================================================================
永久路由:

**Comment by xiaohuaihuaihuai** [comment]
运行完弹出一个文档  是上述结果

**Comment by AnyWAT** [comment]
上述结果太杂，只（已）看：netsh int ipv6 show teredo 结果
不是提示重启机器？

**Comment by xiaohuaihuaihuai** [comment]
对的  提示重启计算机完成此操作   意思是重启完之后就可以用了吗？

**Comment by AnyWAT** [comment]
如重启后不正常，再 netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by xiaohuaihuaihuai** [comment]
好的   谢谢啦  感激不尽

**Comment by xiaohuaihuaihuai** [comment]
再次感谢您的耐心解答，重启之后可以用了。非常感谢

**Comment by xiaohuaihuaihuai** [comment]
你好！我在问一个小问题，andriod可以用吗？

**Comment by AnyWAT** [comment]
https://github.com/XndroidDev/Xndroid

**Comment by xiaohuaihuaihuai** [comment]
谢谢
