### ISSUE TITLE
Ipv6，时不时不可用！按照之前的方法配置完，每次需要重启，然后几分钟就又不行了。。。求解

### ISSUE THREAD

**Issue by paihuai00** [XX-net/XX-Net#11096]
诊断信息如下：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.15 Safari/537.36
xxnet-version: 3.12.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xiaoyinping** [comment]
把你的xx-net删掉，Proxy SwitchyOmega也删掉，然后重新下载安装后，就好了！！！！

**Comment by AnyWAT** [comment]
完全不必重启机器，大不了重开一个XX-Net （挤出貌似已不正常的）
关闭“自动调整扫描线程数”、适当增大“最大扫描线程数”（到足以维持较小的IP延时及较大的连接池，有效IP数趋近或达到总IP数），检查IP（去伪存真？）

**Comment by paihuai00** [comment]
试了  还是不行额。。。。

**Comment by rootsun** [comment]
同样问题，同求助
删除XX-NET和Proxy SwitchOmega都试了，还是几分种就掉，然后过一段时间IPV6又回来，如此循环。

**Comment by AnyWAT** [comment]
几分种就掉，然后过一段时间IPV6又回来，如此循环——关闭“自动调整扫描线程数”，适当增大“扫描线程数”以自动维持：较小的IP延时、较大的垃圾池、有效IP数趋近或达到总IP数。。。
