### ISSUE TITLE
3.12.8版本 youtube的问题依旧没有解决

### ISSUE THREAD

**Issue by YunXuyun** [XX-net/XX-Net#11094]
问题有两个：
1.看视频容易突然卡顿，然后直接报错
2.有些体积较大的高清视频下载每次都会出错，导致合并后的视频文件打不开。我记得我以前用的3.9.X版本没有这种问题的啊？

**Comment by xxbbrother** [comment]
一样问题报错

**Comment by SeaHOH** [comment]
是的，并没有说已经解决了。
发现个 3.12.15 引入的 bug。

另外，代码在 3.10.5 时重构过，而且网络稳定时是正常地，找不到是哪里的问题。
近来干扰范围扩大，所以才爆发出来。

然后，我突然发现个不同的地方，正在测试，明天发个新版试试。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/42482359-b4e0443a-8419-11e8-81f3-751ff14a0922.png)

**Comment by SeaHOH** [comment]
@AnyWAT 
下个版本修复

**Comment by SeaHOH** [comment]
#11106
测试下是否完全修复
