### ISSUE TITLE
Switch prefix policies fail, you must authorized as admin.

### ISSUE THREAD

**Issue by wolfmarelalala** [XX-net/XX-Net#11095]
3.12.8 switch teredo时会出现提示，我一直用的管理员账号，之前也没遇到这个问题。该怎么处理？

**Comment by SeaHOH** [comment]
本机？UAC 确认窗口弹出来没有？
话说你有原生 IPv6 嘛，没有就不需要点这个。

**Comment by wolfmarelalala** [comment]
激活ipv6隧道也是一样的提示，UAC窗口弹出来了。在两台电脑上试过了

**Comment by SeaHOH** [comment]
没法重现，不知道为什么。

你点击“是”，然后下方日志窗口也是空白吗？

**Comment by wolfmarelalala** [comment]
![qq 20180705172046](https://user-images.githubusercontent.com/25559910/42493994-87d5a70e-8451-11e8-8ea5-9322af9979f1.png)
点击激活ipv6后

**Comment by SeaHOH** [comment]
明显没有授权成功，下方没有相关日志。

**Comment by no-name2017** [comment]
我也遇到了这个问题，3.12.3版本可以切换，最新版本的不行

**Comment by no-name2017** [comment]
Set teredo server fail, you must authorized as admin.

best server is: teredo.XXXXXXXXX

可以测试到服务器，就是换不成功，防火墙都允许了

**Comment by AnyWAT** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient teredo.XXXXXXXXX

**Comment by no-name2017** [comment]
@AnyWAT 嗯，只能手动了吧，感谢老哥

**Comment by SeaHOH** [comment]
@no-name2017 你点击 UAC 弹窗允许运行没有？

**Comment by ezhouwei** [comment]
Jul 11 22:30:17.578 - [WARNING] elevate e:TypeError("'NoneType' object is not iterable",) 
Jul 11 22:30:17.578 - [INFO] ipv6_tunnel switch enable, result: Enable IPv6 tunnel fail, you must authorized as admin. 
弹窗什么的不存在的....

**Comment by changshunxu520** [comment]
这个问题就这么解决了？还是新版本里解决了？弹不出弹窗的

**Comment by SeaHOH** [comment]
肯定是新版本啦，我又不能修改你的计算机。
