### ISSUE TITLE
闲置一段时间不用之后，会导致证书失效而登不上去

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#11100]
![image](https://user-images.githubusercontent.com/37856464/42490489-203f4cfc-8443-11e8-89ae-462bf2905767.png)
![image](https://user-images.githubusercontent.com/37856464/42490496-2a19cd2e-8443-11e8-82b1-ab1c86a06693.png)

**Comment by SeaHOH** [comment]
把自动调整线程打开即可

**Comment by milanthree** [comment]
@SeaHOH 好的，感谢

**Comment by AnyWAT** [comment]
把自动调整线程打开即可——鄙人得与此反着来😂
