### ISSUE TITLE
提个建议，，，赞成的给个大拇指   👍

### ISSUE THREAD

**Issue by yonghuming9** [XX-net/XX-Net#11107]
@SeaHOH @XXNet
### 设计好了，放在这里，自愿打赏，条件好的就多打赏点，不好的就少打赏点。
![1](https://user-images.githubusercontent.com/40242830/42509227-d27d6aea-847d-11e8-884f-5da9838cfdc0.jpg)

**Comment by yonghuming9** [comment]
### 估计没人跟帖，一看，一撇嘴，全跑了，，，，




不愿少吃一个冰棒的，那就继续免费用吧。没事  没事

**Comment by longwusha** [comment]
个人倒是不介意打赏，毕竟确实很好用很有用

**Comment by xiaoyaooo** [comment]
提供国内账号风险比较大吧。。。太容易追溯了，考虑到现在的环境，或许对开发者不太友好。。。当然如果能有比较好的匿名渠道我也还是很希望能打赏一些的

**Comment by SeaHOH** [comment]
#10974

**Comment by yonghuming9** [comment]
@SeaHOH
你给的连接地址里的内容一句没看懂，https://github.com/XX-net/XX-Net/issues/10974

又是ETH，又是BTC。又是比特币。
比特币倒听说过，
总而言之如果会这些，那还谈什么国外账号。那不分分钟就会注册国外账号了。
说你什么好呢，，，只能说年轻人太前卫了。
你所懂的知识，好比牛和琴。
白弹。

**Comment by xiaoyaooo** [comment]
@yonghuming9 
海大给这个地址无非就是提供一个匿名转账的地址，毕竟这个帖子还会有其他人看到，
有愿意并且知道怎么比特币转账的话，可以这么去打赏，只是一种可行的方法而已。
你说的银行卡账户是不可能的了，gov的人也不是吃干饭的，之前已经有别的项目的开发者被请去喝茶了，在这种地方留实名制的银行账户真的就是自找麻烦了

**Comment by acrossabc** [comment]
虽然不是IT领域的，但是国内账号肯定是无任何防御力的，国外的账号如何不太了解。

**Comment by erdcy** [comment]
公布国内账号或许不是好主意，不过bitcoin也不是人人都有啊。

**Comment by myjlpt** [comment]
内置个比特扫描，自愿开启。不就好了。还有个蠢办法。作者在港注册个皮包公司，然后。...........

**Comment by SeaHOH** [comment]
其实这个问题最开始就讨论过，有意帮助本项目的自己了解下 wiki，都有说明。
https://github.com/XX-net/XX-Net/wiki/How-to-contribute

**Comment by yeezylife** [comment]
人家是为了匿名  你要公布银行卡 第二天就被抓了
