### ISSUE TITLE
启动迅雷会关闭ipv6？

### ISSUE THREAD

**Issue by ibtrobin** [XX-net/XX-Net#11105]
使用的是XX-Net   3.12.2版，
发现IPv6 状态不时关闭，各种方法都解决不了
今天偶然发现好像和迅雷有关，
用的是迅雷极速版，发现启动后ipv6就fail，关闭迅雷一段时间后好像就ok，
有遇到类似情况吗，请问如何解决

**Comment by SeaHOH** [comment]
这个可能是挤占带宽造成掉线

**Comment by ibtrobin** [comment]
应该不是，启动迅雷就fail，根本没有开始下载，所以不存在挤占

**Comment by sjfirefox** [comment]
3.12.7，迅雷极速版-绿色去广告，满速也不会ipv6 fail。
之前不行，一开迅雷很快就会fail。

**Comment by beerlover086** [comment]
XX-Net3.12.8
迅雷极速版，开启下载会导致IPV6关闭，退出迅雷，然后重新启动IPV6，XX-Net恢复正常。
试了三次，都是如此。
启动迅雷极速版但不开启下载，则XX-Net使用正常。
其他版本XX-Net，没测试，但以前使用迅雷的过程中，好像没没有对3.12.8影响这么大。
@SeaHOH ，你可以尝重现。
迅雷极速版：https://pan.baidu.com/s/1NkxWyGNV4S1pftmxy3QdKw 密码: 3qgj
VT：https://www.virustotal.com/#/file/dca1261c9aa0fa65ff2da6b4b4bb787128f31eda39cc33d19b6a5da530b7db47/detection

**Comment by milanthree** [comment]
是会挂掉的，我一般用迅雷的时候，会先把XX-NET断开，用完之后再开启

**Comment by SeaHOH** [comment]
渣雷什么的，知道就行，用是不可能的。
也懒得装虚拟机，好麻烦。

**Comment by beerlover086** [comment]
@milanthree
以前的XX-Net版本，用迅雷没碰到过IPV6关闭。
我个人是从3.12.8这个版本，才开始出现这个问题
你以前遇到过这种情况么？

**Comment by ibtrobin** [comment]
以前偶尔断线不确定是不是迅雷引起的，现在的版本反复试确定迅雷问题，开迅雷就掉，退出迅雷重启模块就ok，好像不下载也掉，只要启动迅雷就掉

**Comment by milanthree** [comment]
@ghost
具体是哪个版本，我也记不太清楚了；不过我觉得这个不是啥大问题，使用迅雷的时候先断开xx-net一会儿也没多大关系

**Comment by XX-NETGOOD** [comment]
我的雷开机自启.25m/s满速下载ipv6 Teredo也未见何影响.更多的时候是Teredo服务器完全连不上.压根ping不通.蛋疼的很

**Comment by myjlpt** [comment]
Mydm走起
