### ISSUE TITLE
Mac无法启动xx-net

### ISSUE THREAD

**Issue by capitata** [XX-net/XX-Net#11108]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是
3.12.2出现问题，重新下载解压，运行无效；下载2.12.8运行，问题依旧

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
双击start后，terminal显示如下，实际xx-net未能启动，系统托盘无图标，无法翻墙，设置页不弹出，地址栏输入设置页地址－无法连接服务器
terminal显示：
/XX-Net-3.12.8/start ; exit;
XX-Net version:3.12.8
Run XX-Net in background.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

没有data文件夹，无法贴出log文件。搜索类似issue尝试解决，均无效，包括：

＃10887，#10540（在.bash_profile当中追加内容，并更改LANG 变量）：
export LANG="en_US.UTF-8" 更改为 export LANG="zh_CN.UTF-8"

＃10908 (定义python2指向) 过程如下：
alias python2='/usr/bin/python2.7'
 sudo ./start
Password:
XX-Net version:3.12.8
Run XX-Net in background.

请帮助排查原因，没有google过不下去。。。谢谢。
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
data/launcher 文件夹下的日志

**Comment by capitata** [comment]
您的意思是再找旧版本试试？我找找看

**Comment by jsnjycwyz** [comment]
同样的问题，直接complete，楼主解决了吗

**Comment by capitata** [comment]
没解决，刚试了最新版12.10，还是一样

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/10908#issuecomment-406511099

**Comment by capitata** [comment]
嗯，按照＃10908替换start文件解决了，谢谢管理员
