### ISSUE TITLE
GFW大规模封锁443端口？

### ISSUE THREAD

**Issue by gfw-breaker** [XX-net/XX-Net#11109]
这两天在海外VPS上搭建网站，配置完SSL后测试访问，没过一会就发现443端口被封了，准确地讲是SSL连接被重置。
不清楚是不是GFW升级了可以自动检测。有同胞知道吗？

**Comment by SasamiMasakiJurai** [comment]
有些ip段是被封禁的 换ip段吧

**Comment by myjlpt** [comment]
貌似不是封死，是随机干扰。昨天不能的IP今天又可以了。断断续续

**Comment by gfw-breaker** [comment]
@SeaHOH   搞清楚了，干扰了原来域名的SSL，换了个域名就OK了。奇怪的是，我做的两个网站都是Web代理，一个是被DNS污染，另一个被SSL干扰。
@myjlpt 确实， 有些IP和端口不是永远封禁，每到开会和大事件时有很多会被临时封一下。前天是709案三周年。

**Comment by SeaHOH** [comment]
VPS 这里没啥人关注，我先关掉啦。
