### ISSUE TITLE
哪位大神遇到过这个异常 600 

### ISSUE THREAD

**Issue by JokingLove** [XX-net/XX-Net#11101]
###  浏览器访问推特错误信息：
600:gae_exception:'600:fetch gae fail' https://twitter.com/gae_exception:'600:fetch gae fail' https://twitter.com/gae_exception:'600:fetch gae fail' https://twitter.com/
### Cloudflare 前端日志：
Jul 10 14:23:08.310 - [INFO] SSL use version:TLSv1_2
Jul 10 14:23:08.313 - [INFO] OpenSSL support alpn
Jul 10 14:23:08.314 - [INFO] load ip range file:D:\dev\tools\XX-Net-3.12.2\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
Jul 10 14:23:08.318 - [INFO] load ip_list num:99, target num:99
Jul 10 14:23:09.178 - [INFO] load D:\dev\tools\XX-Net-3.12.2\data\x_tunnel\cloudflare_domains.json success
Jul 10 14:23:09.359 - [INFO] updated cloudflare front domains from github.
Jul 10 14:23:19.150 - [DEBUG] report_connect_fail:190.93.247.123
Jul 10 14:23:19.151 - [DEBUG] connect 190.93.247.123 fail:error('certificate is none, sni:aahms.net',)
Jul 10 14:23:26.447 - [DEBUG] report_connect_fail:104.19.128.160
Jul 10 14:23:26.449 - [DEBUG] connect 104.19.128.160 fail:error('certificate is none, sni:alkes.me',)
Jul 10 14:23:33.735 - [DEBUG] report_connect_fail:141.101.114.208
Jul 10 14:23:33.736 - [DEBUG] connect 141.101.114.208 fail:error('certificate is none, sni:vyabooks.ml',)
Jul 10 14:23:41.028 - [DEBUG] report_connect_fail:104.16.172.76
Jul 10 14:23:41.030 - [DEBUG] connect 104.16.172.76 fail:error('certificate is none, sni:tenniscahul.com',)
Jul 10 14:23:48.319 - [DEBUG] report_connect_fail:190.93.244.171
Jul 10 14:23:48.320 - [DEBUG] connect 190.93.244.171 fail:error('certificate is none, sni:removie.gq',)
Jul 10 14:23:50.912 - [DEBUG] create_ssl update ip:104.16.55.95 time:582 h2:1 sni:bookshopinindia.com, host:tangg.tk
Jul 10 14:23:51.837 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:23:51.838 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(37),0:get_worker(0):104.16.55.95,0:h2_req,3:start send header,0:start send left body,272:h2_get_head,2:get_response,:0
Jul 10 14:23:59.903 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:23:59.912 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(8),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,272:h2_get_head,8:get_response,:0
Jul 10 14:24:06.029 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:06.030 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(6),0:get_worker(0):104.16.55.95,0:h2_req,1:start send header,0:start send left body,266:h2_get_head,1:get_response,:0
Jul 10 14:24:15.819 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:15.822 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(9),0:get_worker(0):104.16.55.95,0:h2_req,3:start send header,0:start send left body,269:h2_get_head,3:get_response,:0
Ju 10 14:24:22.150 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:22.153 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(6),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,274:h2_get_head,3:get_response,:0
Jul 10 14:24:23.093 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:23.095 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(0),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,267:h2_get_head,2:get_response,:0
Jul 10 14:24:27.742 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:27.743 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(4),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,266:h2_get_head,2:get_response,:0
Jul 10 14:24:29.239 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:29.240 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(1),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,267:h2_get_head,2:get_response,:0
Jul 10 14:24:29.864 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:29.883 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(0),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,287:h2_get_head,3:get_response,:15
Jul 10 14:24:34.647 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:34.674 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,1:get_task(4),0:get_worker(0):104.16.55.95,0:h2_req,0:start send header,0:start send left body,274:h2_get_head,28:get_response,:0
Jul 10 14:24:36.006 - [WARNING] task GET dns.xx-net.net /query?domain=clients1.google.com timeout
Jul 10 14:24:36.022 - [WARNING] GET tangg.tk/query?domain=clients1.google.com status:521 trace:0:start_request,0:get_task(1),0:get_worker(0):104.16.55.95,0:h2_req,1:start send header,0:start send left body,266:h2_get_head,16:get_response,:0

**Comment by SeaHOH** [comment]
X-Tunnel 的前端扫描使用了 gae_proxy 模块的配置，之后会尝试分离。

**Comment by JokingLove** [comment]
@SeaHOH  gae_proxy 在哪开启，怎么确定是否开启了，我不太懂额，在哪有说明文档，我看着操作一下，谢谢  😅

**Comment by JokingLove** [comment]
@AnyWAT 这个是启用的，还有一个日志，你帮我看看
![image](https://user-images.githubusercontent.com/18134074/42499260-e7e6dc30-8460-11e8-9dfc-84cc61fa5651.png)

**Comment by AnyWAT** [comment]
还有一个日志：彼此彼此，忽略。
IPv6正常，GAE才正常。
GAE正常，X-Tunnel 就正常。

**Comment by JokingLove** [comment]
### 诊断信息是这样的：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:143 ipv4:0 ipv6:4
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 2311
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by JokingLove** [comment]
###  诊断信息是这样的：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:143 ipv4:0 ipv6:4
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 2311
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by JokingLove** [comment]
###  诊断信息是这样的：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:143 ipv4:0 ipv6:4
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 2311
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by JokingLove** [comment]
###  诊断信息是这样的：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3423.2 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:143 ipv4:0 ipv6:4
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 2311
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
use-ipv6: auto——仅IPv6
scan-ip-thread-num: 10——适当增大“最大扫描线程数”（到能自动维持：较小的IP延时、较大的连接池、有效IP数趋近或达到总IP数）
ip-quality: 2311——较小约为1/10
