### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by asd2323208** [XX-net/XX-Net#11111]
start.bat打开就一闪而过，CMD打开提示ImportError: No module named site
刚下的新鲜版本，系统为W7X64，已经尝试安装新版python

错误图https://i.loli.net/2018/07/11/5b44e38818b31.jpg

**Comment by asd2323208** [comment]
使用测试版3.12.8已打开，如果是个例的话我就关了吧

**Comment by SeaHOH** [comment]
估计是你安装有 Python 造成的，新版已修复。
