### ISSUE TITLE
绑定域名、证书的方法失效及解决方法

### ISSUE THREAD

**Issue by happy1234367** [XX-net/XX-Net#11118]
![image](https://user-images.githubusercontent.com/25525577/42551013-967e0bf0-8507-11e8-9e39-12c46bb24fd0.png)
# 十分不好意思，前几天刚写完教程40小时，就发现这个方法很疑似被干扰，直接删除了教程。现在一看，全是i/o超时，tk域名打不开（如上图），不得不令人感叹

**Comment by happy1234367** [comment]
解决：

**Comment by zzgpku** [comment]
咋解决。。。
