### ISSUE TITLE
请问各位大佬，出现这种600  602 是怎么回事呀？

### ISSUE THREAD

**Issue by gybwyy** [XX-net/XX-Net#11112]
打开谷歌网站就出现这个，

600:gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
xxnet-version: 3.12.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:72
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 340
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

部分日志
Jul 11 00:59:19.801 - [WARNING] 2607:f8b0:401e:2d::9 host:xxnet-200811.appspot.com head fail status:404

Jul 11 00:59:19.801 - [DEBUG] report_connect_fail:2607:f8b0:401e:2d::9

Jul 11 00:59:19.811 - [WARNING] 2607:f8b0:4006:35::9 host:xxnet-200811.appspot.com head fail status:404

Jul 11 00:59:19.812 - [DEBUG] report_connect_fail:2607:f8b0:4006:35::9

Jul 11 00:59:20.942 - [DEBUG] recheck_ip:2607:f8b0:4006:35::9 restore ok

Jul 11 00:59:20.944 - [DEBUG] 2607:f8b0:4006:35::9 worker close:keep alive

Jul 11 00:59:20.984 - [DEBUG] recheck_ip:2607:f8b0:401e:2d::9 restore ok

Jul 11 00:59:20.985 - [DEBUG] 2607:f8b0:401e:2d::9 worker close:keep alive

Jul 11 00:59:22.074 - [DEBUG] recheck_ip:2804:214:800f:1::d restore ok

Jul 11 00:59:33.561 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 11 00:59:33.664 - [DEBUG] network IPv4 is ok, cost:102 ms

Jul 11 00:59:36.081 - [DEBUG] report_connect_fail:2404:4408:5:5101::f

Jul 11 00:59:37.694 - [DEBUG] recheck_ip:2404:4408:5:5101::f restore ok

Jul 11 00:59:43.516 - [DEBUG] recheck_ip:2804:7f3:9005:cace::c restore ok

Jul 11 00:59:49.113 - [DEBUG] recheck_ip:2804:d40:82:d001::f restore ok

Jul 11 00:59:54.874 - [DEBUG] recheck_ip:2804:7f3:9003:cace::13 restore ok

Jul 11 01:00:00.569 - [DEBUG] recheck_ip:2804:7f1:a005:cacf::10 restore ok

Jul 11 01:00:06.441 - [DEBUG] recheck_ip:2804:7f3:9000:cace::11 restore ok

Jul 11 01:00:12.128 - [DEBUG] recheck_ip:2804:7f1:a006:cacf::e restore ok

Jul 11 01:00:17.884 - [DEBUG] recheck_ip:2804:7f1:a000:cace::d restore ok

Jul 11 01:00:23.812 - [DEBUG] recheck_ip:2804:7f3:9003:cace::12 restore ok

Jul 11 01:00:25.259 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 11 01:00:25.348 - [DEBUG] network IPv4 is ok, cost:88 ms

Jul 11 01:00:29.688 - [DEBUG] recheck_ip:2804:7f2:1001:cade::11 restore ok

Jul 11 01:00:35.515 - [DEBUG] recheck_ip:2804:7f3:9000:cace::c restore ok

Jul 11 01:00:41.345 - [DEBUG] recheck_ip:2804:d50:84:3003::12 restore ok

Jul 11 01:00:47.602 - [DEBUG] recheck_ip:2804:7f7:f000:cade::12 restore ok

Jul 11 01:01:01.617 - [DEBUG] report_connect_fail:2001:8002:e22:ef01::10

Jul 11 01:01:03.540 - [DEBUG] recheck_ip:2001:8002:e22:ef01::10 restore ok

Jul 11 01:01:09.345 - [DEBUG] recheck_ip:2804:7f7:f002:cade::f restore ok

Jul 11 01:01:15.025 - [DEBUG] recheck_ip:2804:238:2:7::f restore ok

有点烧脑，不止如何处理，已经升级到最新了

**Comment by SeaHOH** [comment]
网页正常吗，正常就不要管它，不正常刷新看看。

**Comment by gybwyy** [comment]
@SeaHOH 
不正常，直接打不开的 小哥哥

**Comment by SeaHOH** [comment]
所有网页都这样？

**Comment by gybwyy** [comment]
@SeaHOH 
需要翻墙的网站都这样 比如说谷歌 优酷等等

**Comment by SeaHOH** [comment]
感觉像假的，没遇到过全是这样的，偶尔一个还有可能。
你用的运营商是哪家？
还有，优酷翻墙是哪样？

**Comment by gybwyy** [comment]
@SeaHOH 
抱歉啊  说错了应该是油管，本机 陕西省西安市 教育网

**Comment by AnyWAT** [comment]
貌似或其实就是代理速度慢（IP延时较大、连接池较小）的锅。
https://github.com/XX-net/XX-Net/issues/11096

**Comment by gybwyy** [comment]
@SeaHOH @AnyWAT 
已经阵亡，现在打开github也需要把xxnet关了 才能上网。难受

**Comment by AnyWAT** [comment]
*.github.com 走“直接连接”，其它与 github 相关走代理

**Comment by SeaHOH** [comment]
教育网啊，你是直接用的教育网 IPv6 还是开启的隧道？
如果是原生，你换成其它隧道试试，比如 teredo。

**Comment by naemlich** [comment]
lz我也遇到了一样的问题，请问现在解决了吗？

**Comment by SeaHOH** [comment]
已查明是 ID 问题，需正确部署。

**Comment by gybwyy** [comment]
直接卸载重装，就行了。



在 2018年9月23日，下午6:58，naemlich <notifications@github.com<mailto:notifications@github.com>> 写道：


lz我也遇到了一样的问题，请问现在解决了吗？

**Comment by AnyWAT** [comment]
别介，不如先试试：或机器重启、或退出再重开、或按 https://github.com/XX-net/XX-Net/issues/11112#issuecomment-404042632 根本解决问题所在😂
@nlpsuge netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by 1721565844** [comment]
600:gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/
