### ISSUE TITLE
前两天还好用 今天一打开xx-net 显示请检查浏览器代理设置。

### ISSUE THREAD

**Issue by github-qn** [XX-net/XX-Net#11117]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
IPv4 IP数 | 0
IPv6 IP数 | 67
XX-Net 状态 | 工作
IP延迟 | 914
连接池(帮助) | 新:0 h1:29 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
IP扫描线程数(设置) | 10

**Comment by github-qn** [comment]
![Uploading image.png…]()

**Comment by github-qn** [comment]
Jul 11 12:10:55.638 - [DEBUG] report_connect_fail:2001:f90:8:6::10

Jul 11 12:10:55.638 - [DEBUG] connect 2001:f90:8:6::10 fail:error("conn fail, sni:lndlqn2.appspot.com, top:lndlqn2.appspot.com e:timeout('timed out',)",)

Jul 11 12:10:57.119 - [DEBUG] report_connect_fail:2400:c700:1000:3::d

Jul 11 12:10:57.119 - [DEBUG] connect 2400:c700:1000:3::d fail:error("conn fail, sni:lndlqn8.appspot.com, top:lndlqn8.appspot.com e:timeout('timed out',)",)

Jul 11 12:10:57.620 - [DEBUG] report_connect_fail:2001:4958:300:500::10

Jul 11 12:10:57.620 - [DEBUG] connect 2001:4958:300:500::10 fail:error("conn fail, sni:lndlqn6.appspot.com, top:lndlqn6.appspot.com e:timeout('timed out',)",)

Jul 11 12:10:58.120 - [DEBUG] report_connect_fail:2607:f8b0:401c:29::c

Jul 11 12:10:58.120 - [DEBUG] connect 2607:f8b0:401c:29::c fail:error("conn fail, sni:lndlqn7.appspot.com, top:lndlqn7.appspot.com e:timeout('timed out',)",)

Jul 11 12:10:58.813 - [DEBUG] create_ssl update ip:2001:8002:e21:e101::10 time:1171 h2:0 sni:lndlqn10.appspot.com, host:lndlqn10.appspot.com

Jul 11 12:10:59.520 - [DEBUG] report_connect_fail:2001:8c0:9802:1::11

Jul 11 12:10:59.520 - [DEBUG] connect 2001:8c0:9802:1::11 fail:error("conn fail, sni:border-significance-welcome.org, top: e:timeout('timed out',)",)

Jul 11 12:11:04.582 - [DEBUG] create_ssl update ip:2800:af0:0:5::11 time:3061 h2:0 sni:software.childhood.rate.net, host:

Jul 11 12:11:06.144 - [DEBUG] create_ssl update ip:2001:8002:e52:ef02::d time:1328 h2:0 sni:lndlqn9.appspot.com, host:lndlqn9.appspot.com

Jul 11 12:11:11.825 - [DEBUG] create_ssl update ip:2001:8002:e52:e001::11 time:1239 h2:0 sni:assistanceexpertappeal.org, host:

Jul 11 12:11:13.478 - [DEBUG] create_ssl update ip:2001:d08:10:204::12 time:1331 h2:0 sni:lndlqn9.appspot.com, host:lndlqn9.appspot.com

Jul 11 12:11:19.067 - [DEBUG] create_ssl update ip:2001:8002:e52:e001::d time:1239 h2:0 sni:expression-honey.org, host:

Jul 11 12:11:24.478 - [DEBUG] report_connect_fail:2405:4800:100:38::f

Jul 11 12:11:24.478 - [DEBUG] connect 2405:4800:100:38::f fail:error("conn fail, sni:lndlqn.appspot.com, top:lndlqn.appspot.com e:timeout('timed out',)",)

Jul 11 12:11:26.312 - [DEBUG] create_ssl update ip:2001:8002:e52:e001::13 time:1241 h2:0 sni:employmentdeparture.ml, host:

Jul 11 12:11:31.479 - [DEBUG] report_connect_fail:2620:11a:a02d::17

Jul 11 12:11:31.479 - [DEBUG] connect 2620:11a:a02d::17 fail:error("conn fail, sni:lndlqn2.appspot.com, top:lndlqn2.appspot.com e:timeout('timed out',)",)

Jul 11 12:11:33.225 - [DEBUG] create_ssl update ip:2a02:2000:1:e101::10 time:910 h2:0 sni:yellow-respond-theory.org, host:

**Comment by github-qn** [comment]
这两天电脑用360更新一些win7 补丁

**Comment by github-qn** [comment]
刚发现用gae-proxy能上 用gae-proxy自动切换不行

**Comment by github-qn** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:359 ipv4:0 ipv6:171
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:48 h2:0
scan-ip-thread-num: 10
ip-quality: 809
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by silencefun** [comment]
我也偶尔会出现这个问题，
我的解决办法是：不用关闭，直接再双击运行就好了，可以试一下

**Comment by dylanleesky** [comment]
用XX的伙计们请远离360....我上次用了360扫描系统，废了我将近三千的资源。
