### ISSUE TITLE
xxnet  能在YouTube上传视频吗

### ISSUE THREAD

**Issue by laspery** [XX-net/XX-Net#11119]
xxnet  能在YouTube上传视频吗

我上传一直在加载  但可以浏览视频

**Comment by SeaHOH** [comment]
没试过，你按`F12`选择`网络`或`network`标签，看哪些 url 阻塞或失败。

**Comment by laspery** [comment]
应该是上传大小的限制问题 ，能够看到有url请求失败，但也没办法  。

**Comment by shpherd** [comment]
instagram上不去。以前可以直接上，现在gae也上不去
