### ISSUE TITLE
【想法】将程序按操作系统位数分类

### ISSUE THREAD

**Issue by zhanghua000** [XX-net/XX-Net#11116]
我想为什么不把这个软件做成32位与64位分开的，32位用32位的python，64位的用64位的python，这样至少看起来效率会高一点？

**Comment by SeaHOH** [comment]
一个词：麻烦。你先烦我后烦。

**Comment by whhxmwhh** [comment]
哇，原来还有可能是这个原因。我用的32位的。

**Comment by zhanghua000** [comment]
好吧，请忽略这个想法。
