### ISSUE TITLE
whatsapp 网页版的二维码刷新不出来

### ISSUE THREAD

**Issue by cloudydayoffice** [XX-net/XX-Net#11125]
之前3.10 版本的时候还是可以的，升级到3.11之后到现在的版本一直都不行，有哪位大神能够有办法解决？

**Comment by cloudydayoffice** [comment]
不要水啊~~~哪位知道是什么原因？假如有翻墙路由器没有这个问题的，但是单用XXnet就会了

**Comment by SeaHOH** [comment]
都不知道你什么意思，这玩意儿要翻墙？

**Comment by cloudydayoffice** [comment]
![_20180713144820](https://user-images.githubusercontent.com/37390427/42676911-82aa8454-86ac-11e8-9311-1763b8393f4d.jpg)

WhatsApp是一个即时聊天软件，以前的版本，网页版能直接出现二维码，现在就不能.

假如我用了翻墙路由器的网络就可以出现二维码

**Comment by SeaHOH** [comment]
> 这玩意儿要翻墙？

不就是 WhatsApp 嘛，直连不好吗？

**Comment by cloudydayoffice** [comment]
已经要翻墙了快一年了

**Comment by SeaHOH** [comment]
web.whatsapp.com 主站翻墙，其它直连。

**Comment by SeaHOH** [comment]
其实 web.whatsapp.com IPv6 直连能用的

**Comment by cloudydayoffice** [comment]
app 要vpn才能 上

web.whatsapp.com 用了XXnet还是出不来，但是我有带翻墙的路由器，用它能出来

IPV6 如何直连？

**Comment by SeaHOH** [comment]
搜索如何使用 IPv6 优先连接网络，或者用 hosts 文件也行。

**Comment by cloudydayoffice** [comment]
是这样设置吗？  还是不行，哪里没做到位？
![_20180713154943](https://user-images.githubusercontent.com/37390427/42679760-9ec6f0ec-86b5-11e8-8433-cedd8211fd89.jpg)

**Comment by cloudydayoffice** [comment]
![11](https://user-images.githubusercontent.com/37390427/42684427-a7f4ec8e-86c2-11e8-8649-11b0e366924c.jpg)
![22](https://user-images.githubusercontent.com/37390427/42684428-a84e590e-86c2-11e8-9c82-11917dca25f5.jpg)

大神，有哪里做得不对吗？还是不行

**Comment by SeaHOH** [comment]
好像没错，如果你那里无法直连，ws 就只能走 X-Tunnel 了。

**Comment by cloudydayoffice** [comment]
好吧，非常感谢你的帮忙！

**Comment by hanzxh** [comment]
“SwitchyOmega 情景模式就可以用，在自动切换规则里面添加w*.web.whatsapp.com直连就行。”

这个用不了，还有其他方案吗？求解。电脑是win7的，shadowsocks的安装包好像不能用（手机能用，买了账号的）
x-tunnel的话要另买账号吧？感觉没必要，因为现在除了whatsappweb，其他一切正常，搞得我有点想买台笔记本装win10和shadowsock专门聊whatsapp用了...
shadowsocks的话，switchyomega是可以这样操作的，xxnet这样不行，不知道有没有大神会解决

ipv6优先，是不是就相当于GAE不切换，国内网站会变慢？求ipv6操作办法

我也是小白，也花了钱，也自己在琢磨技术。求解

**Comment by AnyWAT** [comment]
@hanzxh Releases · shadowsocks/shadowsocks-windows - https://github.com/shadowsocks/shadowsocks-windows/releases
Home · XX-net/XX-Net Wiki - https://github.com/XX-net/XX-Net/wiki

**Comment by SeaHOH** [comment]
可能有 DNS 污染，我不太确定，因为我安装有反污染工具。
>shadowsocks的话，switchyomega是可以这样操作的，xxnet这样不行

但是按你的描述，逻辑不通，直连是不受工具影响的。

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by hetaiqing** [comment]
LZ，你们解决了这个xxnet不能上whatsapp了吗？还在迷糊啊~求打救
