### ISSUE TITLE
IDM不能下載YouTube上的視頻

### ISSUE THREAD

**Issue by canghai569** [XX-net/XX-Net#11124]
![20180712083402](https://user-images.githubusercontent.com/29430525/42606506-9f205dcc-85b0-11e8-8423-a3158512205c.png)
Jul 12 08:45:37.183 - [WARNING] task POST None /_gh/ timeout

Jul 12 08:45:37.183 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 12 08:45:37.184 - [WARNING] gae_exception:'600:fetch gae fail' https://r4---sn-vgqsrnee.googlevideo.com/videoplayback?aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&mime=video%2Fwebm&c=WEB&itag=248&ipbits=0&sparams=aitags,clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mip,mm,mn,ms,mv,pcm2,pl,requiressl,source&keepalive=yes&requiressl=yes&id=o-AN0KPC5f5iH7nXpHqSGNVKbyAKaGaibT-eudxUHiMV0q&dur=228.853&fexp=23709359,23745105&lmt=1531254132529581&ip=107.178.195.211&key=cms1&fvip=4&source=youtube&pl=28&ei=mqRGW9eVD-HXjAShg7DgCQ&pcm2=no&expire=1531377914&clen=60869678&gir=yes&alr=yes&signature=5B25B025BC9317080333A9E7D656A99BBEDF0987.690140B32D947704EF09F17C1C181540BC2DA332&cpn=U17sgpdQAse-H1bn&cver=2.20180710&redirect_counter=1&rm=sn-vgqyr7z&cms_redirect=yes&ipbypass=yes&mip=35.187.132.91&mm=31&mn=sn-vgqsrnee&ms=au&mt=1531356244&mv=m&req_id=22074bda2ed7f516&rn=2

Jul 12 08:45:37.427 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 12 08:45:37.528 - [WARNING] 2620:11a:a018:2::d h1_request:Exception('time out',) inactive_time:17 task.timeout:15

Jul 12 08:45:37.529 - [WARNING] 2620:11a:a018:2::d trace: 0:connect, 1425:init, 2404:request, 546:Res, 502:request, 766:Res, 401:request, 541:Res, 1039:request, 610:Res, 520:request, 1559:Res, 59:request, 545:Res, 1164:request,:15434, processed:6, transfered:72168, sni:fishing-character.net

Jul 12 08:45:37.530 - [WARNING] retry_task_cb: POST None/_gh/

Jul 12 08:45:37.530 - [WARNING] POST None/_gh/ response_fail:retry timeout:15

Jul 12 08:45:37.531 - [DEBUG] 2620:11a:a018:2::d worker close:down fail

Jul 12 08:45:37.629 - [INFO] RangeFetch 0-1157709 started('https://r4---sn-vgqsrnee.googlevideo.com/videoplayback?aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&mime=video%2Fwebm&c=WEB&itag=248&ipbits=0&sparams=aitags,clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mip,mm,mn,ms,mv,pcm2,pl,requiressl,source&keepalive=yes&requiressl=yes&id=o-AN0KPC5f5iH7nXpHqSGNVKbyAKaGaibT-eudxUHiMV0q&dur=228.853&fexp=23709359,23745105&lmt=1531254132529581&ip=107.178.195.211&key=cms1&fvip=4&source=youtube&pl=28&ei=mqRGW9eVD-HXjAShg7DgCQ&pcm2=no&expire=1531377914&clen=60869678&gir=yes&alr=yes&signature=5B25B025BC9317080333A9E7D656A99BBEDF0987.690140B32D947704EF09F17C1C181540BC2DA332&cpn=U17sgpdQAse-H1bn&cver=2.20180710&redirect_counter=1&rm=sn-vgqyr7z&cms_redirect=yes&ipbypass=yes&mip=35.187.132.91&mm=31&mn=sn-vgqsrnee&ms=au&mt=1531356244&mv=m&range=24397967-25555676&rn=16&rbuf=9566')
幫看看哪裡出問題了

**Comment by SeaHOH** [comment]
隧道断了，等一会儿。
还有，关闭多线程，XX-Net 会自动启用，当然默认设置下载速度不会太快。

**Comment by conray002** [comment]
突然之间发现，IDM下载youtube的时候，提示无下载。更新了IDM各种版本软件，设置了代理，各种尝试还是不行。

后来无意中发现，原来是chrome的广告插件屏蔽了youtube的广告。

下载youtube视频，看一看youtube的广告合情合理。所以大家知道怎么办了。把youtube放到广告的白名单上（之后停止运行屏蔽软件，我的是Adguard）即可解决。

最后还是回到原来的层面来看这个问题，世间万物为一个整体，你中有我，我中有你。任何人在特别极端的情况下都不能形成合理的稳定结构。

捡别人家的鸡蛋，先喂点粮食不过分吧。

下载最新的IDM破解版本https://www.cmdpe.com/post/53.html

https://macace.lanzouc.com/b0131835c
导出代码：29cx
