### ISSUE TITLE
xx-net 3.12.9 GAEProxy 高级配置（全局设置）提交设置级别

### ISSUE THREAD

**Issue by snipertulip** [XX-net/XX-Net#11127]
config 被重置
good ip 被重置100

**Comment by SeaHOH** [comment]
就是这样，看 3.12.8 发布说明。

**Comment by whhxmwhh** [comment]
现在用跳转了。明天测试一下了。

**Comment by snipertulip** [comment]
哪里有说明，没有看到，几百ip，就这样设置一下，全没了，大师，这个不改怎么体验

**Comment by AnyWAT** [comment]
高级配置（全局设置）提交后再人工修改 config.json 几百（千）ip 随你愿
