### ISSUE TITLE
dropbox无法上传文件，文件86M

### ISSUE THREAD

**Issue by houhuliang** [XX-net/XX-Net#11129]
Jul 12 14:41:26.685 [gae_proxy][WARNING] gae_exception:'600:fetch gae fail' https://bolt.dropbox.com/2/notify/subscribe
Jul 12 14:41:27.000 [gae_proxy][WARNING] 2620:11a:a019:1::22 h1_request:Exception('time out',) inactive_time:56 task.timeout:25
Jul 12 14:41:27.001 [gae_proxy][WARNING] 2620:11a:a019:1::22 trace: 0:connect, 16715:init, 0:head, 1695:head end, 31100:request,:25356, processed:0, transfered:0, sni:use-person-set.org
Jul 12 14:41:27.001 [gae_proxy][WARNING] retry_task_cb: POST None/_gh/
Jul 12 14:41:27.001 [gae_proxy][WARNING] POST None/_gh/ response_fail:retry timeout:25

**Comment by houhuliang** [comment]
Property | Value
-- | --
XX-Net Version | 3.12.9
Python Version | 2.7.3
OpenSSL Version | 16.0.0 TLSv1_2 h2:npn
System Platform | x86_64, Linux-3.2.0-29-generic-x86_64-with-Ubuntu-12.04-precise
OS System | Linux
OS Version | #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012
OS Release | 3.2.0-29-generic
OS Detail | Dist:Ubuntu; Version:12.04; ID:precise
Language | en_US
Architecture | 64bit,ELF

**Comment by SeaHOH** [comment]
上传限制大概在 30MB，大于此数值可以换用 X-Tunnel。

**Comment by houhuliang** [comment]
之前版本100M都能上传成功。。。

**Comment by SeaHOH** [comment]
你换老版本试试，参照之前的公告进行修改就能用。

**Comment by SeaHOH** [comment]
> 参照之前的公告进行修改就能用。

**Comment by SeaHOH** [comment]
关闭后仍可回复
