### ISSUE TITLE
[发布] 3.12.9 修复大文件错误

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#11123]
## 新版改进：
* 增加运行环境兼容性检查和建议 (win)
* 修复下载大文件时数据错误
* 修复无法提升权限错误 (win)

**Comment by limosky** [comment]
3.12.9有下面这个问题，显示都是正常的，但是一直无法连接，相比而言旧版本只是teredo偶尔断开一会儿。
600:gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/

下面是状态信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:33
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 20
ip-quality: 506
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by h188cm** [comment]
还是3.12.2稳定啊，又换回稳定版了，哈哈

**Comment by AnyWAT** [comment]
楼主 Appids_Out_Of_Quota: true 有ID没流量了？

**Comment by SeaHOH** [comment]
@limosky 
主要是 IPv6 联通性测试的问题。
通报 11 次才会启动测试，视使用状况大约耗时 1-6 分钟。
测试有 4 个地址，确定网络失败会有 1 分钟左右的延迟。

**Comment by limosky** [comment]
@AnyWAT 是的，有APPID没有流量了，又加了几个，一开始还可以正常使用，突然就完全无法工作了，到现在还没有恢复。看样子要降回稳定版本试试了

**Comment by AnyWAT** [comment]
看样子要降回稳定版本试试了——或许再开一个XX-Net（挤出貌似已吧正常的）也行

**Comment by okaylabababa** [comment]
感覺鏈接池有點低 3.12.9只有1和2 前兩個版本能有20以上的

**Comment by 2609665** [comment]
好像12.9谷歌验证的图片刷新不出来,用回12.8就好了

**Comment by Eri5Ch** [comment]
就使用情况看 是目前频繁更新后的最稳定版本 y2b断流问题也解决了

**Comment by SeaHOH** [comment]
这个版本造成了 X-Tunnel 可能会登录失败，已经修复，暂时不发布，再等等看还有没有 bug。
