### ISSUE TITLE
AppID 能批量申请项目吗  一个一个的点 太麻烦了

### ISSUE THREAD

**Issue by csx43600121** [XX-net/XX-Net#11126]
现在我遇到一个问题   APPID 我现在能创建无限个ID  可是我现在手动一个一个创建 是不是太慢了 ，还耽误我正常的工作  大家有没有批量创建APPID的方法 和 工具？

**Comment by limosky** [comment]
600:gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/
