### ISSUE TITLE
仅ipv6不可用

### ISSUE THREAD

**Issue by geq1fan** [XX-net/XX-Net#11128]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
xxnet-version: 3.12.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:29
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1039
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by geq1fan** [comment]
十分钟断一次

**Comment by SeaHOH** [comment]
对，你的网络就是这样。

**Comment by wingguo** [comment]
gae高级中将扫描IP参数都设置为最高，等一会即可

**Comment by geq1fan** [comment]
所以是网络不稳定的原因吗？

**Comment by oushii** [comment]
没法用啊，gae高级中将扫描IP参数都设置为最高，还是不行，让开启ipv6或者xtunnel

**Comment by SeaHOH** [comment]
可以换回旧版本试试，我觉得不会有改善。

**Comment by BeerPong** [comment]
我这几天也是，总是隔一会儿就ipv6不可用，后来关了TIM就好了很多，不知道是否企鹅搞得鬼

**Comment by AnyWAT** [comment]
十分钟断一次：试试关闭”自动调整扫描线程数“，scan-ip-thread-num: 10：适当增大此值，得以自动维持较小的IP延时、较大的连接池。。。（亲历：先前某版本总 IP 数100有连接池趋近0而不再。。。）

**Comment by BeerPong** [comment]
@AnyWAT
试过的，关闭自动扫描，也增大扫描线程了，但没用
关了TIM就好多了，ipv6不可用基本没了

**Comment by AnyWAT** [comment]
关闭自动扫描，也增大扫描线程了，但没用——或许还不够大

**Comment by yhbjz252** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:25
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1002
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
