### ISSUE TITLE
Android版xx无法启动

### ISSUE THREAD

**Issue by 102464** [XX-net/XX-Net#11120]
couldn't find libpython3.5m.so

**Comment by 102464** [comment]
An error occured while trying to load the application libraries. Please try again and/or reinstall.
Error: Dalvik.System.PathClassLoader[DexPathList[[zip file: "/data/app/xxnet.net-1/base.apk"],nativeLibraryDirectories=[/data/app/xxnet-net-1/lib/arm,/system/fake-libs, /data/app/xxnet.net-1/base.apk!/lib/armeabi,/system/lib, /vendor/lib]]] couldn't find "libpython3.5m.so"

**Comment by SeaHOH** [comment]
推荐 https://github.com/XndroidDev/Xndroid

**Comment by 102464** [comment]
也启动不了，提示：fqrouter意外退出

**Comment by 102464** [comment]
系统是android-x86 7.1 r2

**Comment by SeaHOH** [comment]
你可以继续换用其它工具，或者给 Xndroid 报错也行。
