### ISSUE TITLE
配置页面打不开

### ISSUE THREAD

**Issue by zhoukangg** [XX-net/XX-Net#11131]
更新了一下之后，后端启动正常，但是打不开配置页面，也不能翻墙(mac）

**Comment by houhuliang** [comment]
估计端口没有配置对

**Comment by houhuliang** [comment]
查看端口设置

**Comment by zhoukangg** [comment]
怎样查看端口设置呢（8085端口没有被占用），3.11.X的版本好使，3.12.X的不好使，我刚刚把版本退回11的了

**Comment by huangazhuang** [comment]
我也进不了了。。

**Comment by ablebodied** [comment]
我也是偶尔进不了，退出重新打开才行，chrome能进的概率比IE，Edge大很多，IE、Edge打不开而chrome有可能打开

**Comment by AnyWAT** [comment]
长时间中断后，如果刚运行XX-Net 立马点击“设置”会报错，貌似程序还没准备好？
