### ISSUE TITLE
最新稳定版和最新测试版安装文件都无法顺利下载

### ISSUE THREAD

**Issue by 111Moderato** [XX-net/XX-Net#11134]
最新稳定版和最新测试版都无法顺利下载，这是什么问题，换了电脑换了网络都不行？

**Comment by AnyWAT** [comment]
下载、上图需代理

**Comment by hongkonghot** [comment]
试了一下，我这里不存在你说的问题，是不是和运营商有关系？

**Comment by liuliuquick** [comment]
这是3.10版本之后版本的硬伤，我都试过了，还是用回3.10.4版本。

**Comment by 111Moderato** [comment]
总是下一半就停止重新下载

**Comment by SeaHOH** [comment]
你是指下载安装 XX-Net 用的 zip 文件？这确实是个问题。
之前的设计没考虑到续传，也许以后可以加上续传支持，就是不知道需求大不大。

**Comment by 111Moderato** [comment]
那个zip文件我用手机下载了传到电脑上解压缩也不行，说是文件损坏

**Comment by SeaHOH** [comment]
这个问题，其他用户也有提到过，不过数量不多，一般建议用代理下载。

**Comment by 111Moderato** [comment]
迅雷下载没法下，不过今天试了好多次，终于在浏览器里下载成功了，这回中间没有网速为0的情况，谢谢各位帮忙解答问题啦，我现在已经可以顺利翻墙了

**Comment by AnyWAT** [comment]
😜静候“。。。0的”“佳音”
