### ISSUE TITLE
快捷方式打开文件位置定位到 wscript.exe

### ISSUE THREAD

**Issue by toobed** [XX-net/XX-Net#11135]
C:\Windows\System32 的 wscript.exe
这是为什么？

**Comment by AnyWAT** [comment]
参照修改即可
![default](https://user-images.githubusercontent.com/37962734/42700307-ef1e719c-86f5-11e8-9e39-0ae2b2981b49.png)

**Comment by SeaHOH** [comment]
#10777 
我觉得没啥大问题，如果你认为哪里不对，妨碍使用，可以提出来。

**Comment by AnyWAT** [comment]
原来有更新

**Comment by toobed** [comment]
谢谢以上，没问题就好，我不懂电脑，以为被病毒感染了
