### ISSUE TITLE
捐献appid之后好几天没有收到回信？？

### ISSUE THREAD

**Issue by 11lookpig23** [XX-net/XX-Net#11139]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by 11lookpig23** [comment]
![image](https://user-images.githubusercontent.com/24631324/42724258-96e89b0e-87a1-11e8-8ace-1fc27e71bd33.png)

**Comment by SeaHOH** [comment]
估计私事太忙，还没看到吧。

**Comment by dou4cc** [comment]
满 15 天请告知.

**Comment by AnyWAT** [comment]
😢莫非。。。

**Comment by SeaHOH** [comment]
知道的你是在关心，不知道的还以为你是在咒人。
光我就被你喝了两次茶。。。

**Comment by AnyWAT** [comment]
光我就被你喝了两次茶：神马意思？因鄙人的贴么？

**Comment by AnyWAT** [comment]
喝茶辛苦但光荣😜

**Comment by dou4cc** [comment]
谁删的贴?

**Comment by dou4cc** [comment]
@SeaHOH 你登出账号看一下, 非 XX-net 组织的成员看不到谁删的贴.

**Comment by SeaHOH** [comment]
我删的

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/42733781-35f535cc-886a-11e8-9b65-4ae6128968ab.png)

**Comment by dou4cc** [comment]
@AnyWAT 这个 "XX-net" 是组织上的账号, 不是 X 大本人.

**Comment by dou4cc** [comment]
@SeaHOH 你订阅一下 @xxnet 的 RSS, 确实不妙: https://github.com/xxnet.atom

**Comment by dou4cc** [comment]
@yeahwu 的归来是很不寻常的: https://github.com/yeahwu.atom

**Comment by SeaHOH** [comment]
真没必要讲这些，都有这个意识，如果真喝茶去了，过几天大家就都知道了。

**Comment by zentst** [comment]
@11lookpig23
请问下后面有回复吗？我的也是一直都没有
