### ISSUE TITLE
3.12.8或3.12.9版不可用

### ISSUE THREAD

**Issue by HUChengdu** [XX-net/XX-Net#11133]
3.12.4可用，3.12.4以上版本不可用。3.12.4以上版本连接池始终为0.
3.12.4版本YOUTUBE无法搜索，谷歌学术可使用。

**Comment by AnyWAT** [comment]
用不了半天又断开了——试了：关闭“自动调整扫描线程数”、适当增大“最大扫描线程数”？
连接缓冲调成8都没用——貌似反了：调大才好？

**Comment by yeezylife** [comment]
“合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)”
我没反，你反了。  另外聊天间我的连接池又活了。。今天这样死死活活四五遍了。。但是大部分要用的时候醒不来

**Comment by AnyWAT** [comment]
我没反，你反了——鄙人的几乎从不见“死死活活四五遍”

**Comment by yeezylife** [comment]
人家作者写的“仍然连接不上？等一会儿，或者尝试降低连接缓冲数值”阿

**Comment by AnyWAT** [comment]
几乎（没有100%至少99%）时刻正常可用的还需“等一会儿”？

**Comment by SeaHOH** [comment]
我只想说，你们可以退回之前任意一个版本使用体验，看看有何变化。
