### ISSUE TITLE
谁能告诉我安卓版本到底怎么用，延迟9999

### ISSUE THREAD

**Issue by oushii** [XX-net/XX-Net#11130]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by oushii** [comment]
XX-Net Status:

sys-platform: armv7l, Linux-4.4.23+-armv7l-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Thu May 31 19:28:43 CST 2018
os-release: 4.4.23+
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.0.0; STF-AL00 Build/HUAWEISTF-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36
xxnet-version: 3.12.9
python-version: 2.7.2
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zentst** [comment]
用Xndroid比较方便，已经集成xxnet
