### ISSUE TITLE
ipv6状态显示fail

### ISSUE THREAD

**Issue by Lina0000** [XX-net/XX-Net#11136]
“尝试修复ipv6“并且重启了好几次，一直还是连不上，具体信息如下，望大神们帮忙，以及能否将解决方案解释的易懂一些，纯小白完全不懂。。。。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:29
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1647
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

![default](https://user-images.githubusercontent.com/41202630/42710918-a544e6aa-8718-11e8-8713-9ad49aac3fe9.png)
![default](https://user-images.githubusercontent.com/41202630/42710938-baea8406-8718-11e8-8915-972a9b53033c.png)

**Comment by AnyWAT** [comment]
#10919 臭大街法则
