### ISSUE TITLE
求救啊，teredo服务器一直连不上，ipv6不可用，已经从新版3.12.9退到3.12.2

### ISSUE THREAD

**Issue by 1human** [XX-net/XX-Net#11141]
在高级界面里 检查服务器啥的都出这个 no server detected, return default: teredo.remlab.net.

手动cmd 切换地址，进 xxnet一检查又换成remlab了
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.59 Safari/537.36
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:101 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 1human** [comment]
在高级界面里  检查服务器啥的都出这个   no server detected, return default: teredo.remlab.net.

**Comment by SeaHOH** [comment]
@nly4lov 讲真，你先用一段时间旧版本再来反馈。

**Comment by nly4lov** [comment]
@SeaHOH 用了好久啦，一直ok的

**Comment by SeaHOH** [comment]
@nly4lov 3.12.9 出不去有什么症状？你切换一下版本回到 3.12.4 立刻就能翻了？

**Comment by nly4lov** [comment]
@SeaHOH 翻不出的时候，什么google首页啦，fb啦，tt啦，一律打不开的，说是什么gae无法什么的。没记
删除12.9的东西，把12.4的再解压回来，立马ok
