### ISSUE TITLE
ipv6状态显示fail

### ISSUE THREAD

**Issue by kylewuwu** [XX-net/XX-Net#11144]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
试过

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
IPV6 fail  , 我这边点 IPv6 隧道 下的启用 报错  
![xxnet](https://user-images.githubusercontent.com/4123688/42735092-2bad9110-8881-11e8-810f-fd7ae2d8dbd5.JPG)

我再重新 IP Helper  过一会儿就正常了

想问下 这个错误是不是  IPv6 的启动脚本 里有错误，还是和我的电脑不兼容 我用的是 win7  旗舰版

**Comment by SeaHOH** [comment]
麻烦上传下 gae_proxy\local\ipv6_tunnel\enable_ipv6_temp.bat 这个文件

**Comment by kylewuwu** [comment]
我有2个版本 一个 3.12.4   一个 3.12.9 


[ipv6.zip](https://github.com/XX-net/XX-Net/files/2195830/ipv6.zip)

**Comment by SeaHOH** [comment]
已修复，过两天发布。

**Comment by asmosn** [comment]
请问新的bat文件启用IPV6还是会重置teredo服务器吗？我现用的bat禁用再启用后teredo服务器总是还原成微软那个（老是连不上）

**Comment by SeaHOH** [comment]
![ff](https://user-images.githubusercontent.com/8470820/42741204-c1bdb522-889f-11e8-92e2-ebba766c4655.png)
