### ISSUE TITLE
x-tunnel登录失败

### ISSUE THREAD

**Issue by ItHaC** [XX-net/XX-Net#11140]
请问登录x-tunnel总是显示：登录失败：except:TypeError('sequence item 0: expected string, memoryview found',) 要如何解决？谢谢

**Comment by SeaHOH** [comment]
把日志也贴一下

**Comment by ItHaC** [comment]
是这个么？
Jul 15 19:53:13.841 - [WARNING] create conn fail

Jul 15 19:53:13.954 - [ERROR] order e:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 19:53:13.955 - [ERROR] Except stack:Traceback (most recent call last): File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\proxy_session.py", line 751, in call_api data=upload_post_data, timeout=5) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\front_dispatcher.py", line 111, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\cloudflare_front\front.py", line 86, in request content = response.task.read_all() File "C:\ļ\XX-Net-3.9.6\code\3.12.9\python27\1.0\lib\noarch\front_base\http_common.py", line 131, in read_all return "".join(out) TypeError: sequence item 0: expected string, memoryview found

Jul 15 19:53:13.955 - [WARNING] x-tunnel request_balance fail when create_conn:except:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 19:53:13.955 - [DEBUG] session not running, try login..

Jul 15 19:53:14.119 - [DEBUG] session not running, try to connect

Jul 15 19:53:14.119 - [WARNING] Socks4 connect fail, no conn_id

Jul 15 19:53:14.233 - [ERROR] order e:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 19:53:14.234 - [ERROR] Except stack:Traceback (most recent call last): File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\proxy_session.py", line 751, in call_api data=upload_post_data, timeout=5) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\front_dispatcher.py", line 111, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\cloudflare_front\front.py", line 86, in request content = response.task.read_all() File "C:\ļ\XX-Net-3.9.6\code\3.12.9\python27\1.0\lib\noarch\front_base\http_common.py", line 131, in read_all return "".join(out) TypeError: sequence item 0: expected string, memoryview found

Jul 15 19:53:14.234 - [WARNING] x-tunnel request_balance fail when create_conn:except:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 19:53:14.399 - [DEBUG] session not running, try to connect

Jul 15 19:53:14.399 - [WARNING] create conn fail

Jul 15 19:53:14.680 - [DEBUG] session not running, try to connect

Jul 15 19:53:14.680 - [WARNING] create conn fail

Jul 15 19:53:14.956 - [DEBUG] session not running, try to connect

Jul 15 19:53:14.956 - [WARNING] create conn fail

Jul 15 19:53:15.236 - [DEBUG] session not running, try to connect

Jul 15 19:53:15.236 - [WARNING] Socks4 connect fail, no conn_id

Jul 15 19:53:16.574 - [WARNING] get_front fail

Jul 15 19:53:16.885 - [WARNING] get_front fail

Jul 15 19:57:02.399 - [DEBUG] x_tunnel force update info

Jul 15 19:57:02.764 - [ERROR] order e:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 19:57:02.765 - [ERROR] Except stack:Traceback (most recent call last): File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\proxy_session.py", line 751, in call_api data=upload_post_data, timeout=5) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\front_dispatcher.py", line 111, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\cloudflare_front\front.py", line 86, in request content = response.task.read_all() File "C:\ļ\XX-Net-3.9.6\code\3.12.9\python27\1.0\lib\noarch\front_base\http_common.py", line 131, in read_all return "".join(out) TypeError: sequence item 0: expected string, memoryview found

**Comment by SeaHOH** [comment]
麻烦你测试一下是否修复好了。

**Comment by ItHaC** [comment]
我重启后它一直显示正在登录

**Comment by ItHaC** [comment]
刚刚显示：连接服务器失败：TypeError('sequence item 0: expected string, memoryview found',)

**Comment by ItHaC** [comment]
Jul 15 21:43:54.901 - [ERROR] order e:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 21:43:54.903 - [ERROR] Except stack:Traceback (most recent call last): File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\proxy_session.py", line 751, in call_api data=upload_post_data, timeout=5) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\front_dispatcher.py", line 111, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "C:\ļ\XX-Net-3.9.6\code\3.12.9\x_tunnel\local\cloudflare_front\front.py", line 86, in request content = response.task.read_all() File "C:\ļ\XX-Net-3.9.6\code\3.12.9\python27\1.0\lib\noarch\front_base\http_common.py", line 131, in read_all return "".join(out) TypeError: sequence item 0: expected string, memoryview found

Jul 15 21:43:54.903 - [WARNING] x-tunnel request_balance fail when create_conn:except:TypeError('sequence item 0: expected string, memoryview found',)

Jul 15 21:43:55.903 - [DEBUG] session not running, try to connect

Jul 15 21:43:55.903 - [WARNING] Socks4 connect fail, no conn_id

**Comment by SeaHOH** [comment]
这是客户端错误，需要重新下载 master 分支。

**Comment by SeaHOH** [comment]
或者只是替换我修改的那个文件也行。

**Comment by ItHaC** [comment]
重新装一下可以么？

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/raw/master/code/default/python27/1.0/lib/noarch/front_base/http_common.py

**Comment by ItHaC** [comment]
我找了一下，我似乎没有front_base的文件夹，我下载后放进去可以么？

**Comment by SeaHOH** [comment]
>C:\ļ\XX-Net-3.9.6\code\3.12.9\python27\1.0\lib\noarch\front_base\http_common.py

肯定有啊，就是网址一样的路径，就是 3.12.9 这个文件夹下的。

**Comment by ItHaC** [comment]
谢谢，我可以登录了
