### ISSUE TITLE
搬走吧, Microsoft GitHub 二审查

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net#11143]
![](https://pbs.twimg.com/media/DiJA7HsWAAAY2kM.jpg:large)

就改了下 Wiki 就这样了.

**Comment by SeaHOH** [comment]
你修改了什么内容？

**Comment by dou4cc** [comment]
一直不搬的话, 真的怕哪天从 Releases 下到动过手脚的包. 项目放微软, HTTPs 明文给谷歌, 可以说是很应景了.

**Comment by SeaHOH** [comment]
这种情况我并不是首次遇到，但 XX-Net 这里我是第一次，如果以后频繁发生这种情况肯定会搬。

**Comment by dou4cc** [comment]
改下 README.md 让大家收集这些情况?

**Comment by SeaHOH** [comment]
没必要，如果真的大量审查，自然就知道了。

**Comment by dou4cc** [comment]
有急事找我的话别发邮件了, 我的微软邮箱主要是收订阅的, 不太打算换. 直接 Telegram 上私聊吧.
