### ISSUE TITLE
使用chrome67版本之后，使用出现问题。

### ISSUE THREAD

**Issue by wangbodzh** [XX-net/XX-Net#11148]
1.localhost:8085打不开，端口并没用被其他程序占用。
2.SwitchyOmega.crx没办法正常安装了。

不知道是不是chrome的问题。。。

**Comment by Jack-ban** [comment]
https://www.leiphone.com/news/201806/z0QLIHYBXmGjnDPT.html
不知道是不是这个原因。道理上，你也没必要离线安装。你直接去chrome商店下载不久好了。

**Comment by wangbodzh** [comment]
通过开发者模式还是能成功安装的，但是①问题没办法解决。。。
点击右下角的xx-net后，浏览器里的http://localhost:8085/会无法打开

**Comment by wangbodzh** [comment]
不行。。。

**Comment by SeaHOH** [comment]
你的代理设置截个图

**Comment by wangbodzh** [comment]
github可能抽风了，我不能上传图片。。。
托盘图标里的5种代理模式我都选过了，http://127.0.0.1:8085/都是打不开的，会变成“无法访问此网站”

**Comment by SeaHOH** [comment]
换个浏览器能打开吗？你这标题是不是不对？
建议你重新下载 XX-Net 运行。

**Comment by AnyWAT** [comment]
上传图片貌似需代理
