### ISSUE TITLE
IPv4 Fail?! 发生什么了？

### ISSUE THREAD

**Issue by serverLua** [XX-net/XX-Net#11145]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
![image](https://user-images.githubusercontent.com/25174488/42739966-e219d25a-88d2-11e8-9311-f1b9014029ec.png)

不知是否会影响正常使用

**Comment by serverLua** [comment]
刚启动时电脑没连WiFi，连上以后IPv4就变成Fail了

**Comment by Acytoo** [comment]
可能是因为你的有效ipv4地址为0， 不过进一步确认需要你提供log

**Comment by AnyWAT** [comment]
难道楼上的有效ipv4地址不为0？

**Comment by AnyWAT** [comment]
甭管它发生了神马，重开一个XX-Net（挤出已运行的）再看？

**Comment by dylanleesky** [comment]
不管IP4资源是否为0，都不应该显示状态为fail，这个代表着本机IPv4地址错误或者未获得啊。

**Comment by Acytoo** [comment]
好久不用xx了，现在都扫不到ipv4了吗？

**Comment by AnyWAT** [comment]
近1年扫不到ipv4了

**Comment by SeaHOH** [comment]
> 刚启动时电脑没连WiFi，连上以后IPv4就变成Fail了
