### ISSUE TITLE
IPV6状态突然就变成Fail了

### ISSUE THREAD

**Issue by xwysun** [XX-net/XX-Net#11151]
类型                    : enterpriseclient
服务器名称              : teredo.iks-jena.de
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (secondary server)
客户端类型              : teredo client
网络                    : managed

想问一下 probe怎么变成qualified
版本是3.12.7

**Comment by AnyWAT** [comment]
贴XX-Net 诊断信息
状态 : probe (secondary server) 貌似到了 secondary 一定时间仍然好不了就GG了
（关闭使用XX-Net 的浏览器、退出XX-Net ），先禁用再启用网络
