### ISSUE TITLE
经常显示好多未加载项目，要多次添加条件才行，怎么回事？

### ISSUE THREAD

**Issue by kli-nlpr** [XX-net/XX-Net#11156]
、
![qq 20180718143944](https://user-images.githubusercontent.com/13194870/42864341-abc3dcc4-8a98-11e8-9efd-1ab0e2755c95.png)

**Comment by dylanleesky** [comment]
同问。我也是，并且应该走代理的*.google.com都要手动加规则。
我感觉这个Omega插件没有以前的老版proxy好用稳定。

**Comment by Jack-ban** [comment]
和插件没有什么关系，它只是起到一个路由的作用。真正原因可能在于封锁较严的情况下，响应时间变长，导致浏览器认为丢包连接不上。所以插件那里才会显示资源未加载。

**Comment by dylanleesky** [comment]
@Jack-ban 但是切换成全局代理就没事，再也不出现这个提示。只有智能路由或者自动代理模式才会出现。而以前用的旧版proxy插件就没出现过这个情况、

**Comment by dylanleesky** [comment]
@kli-nlpr 另外，楼主啊，你那是360浏览器？？？~~~都能翻墙了干嘛不装原版chrome？360俩浏览器实际并不好用。我这留的国内浏览器只有搜狗。不管哪里都比360的好用。

**Comment by dylanleesky** [comment]
@kli-nlpr 那只是相对良心。前段时间，我用360扫描了一遍系统，修复系统，其实就是处理可能存在的流氓插件，结果是删掉了我的XX快捷方式和XX目录中的vbs文件。然后在随后的10分钟内，我三千个（XX状态显示实际有效2980多，）资源全部报废。然后让我花了好久的时间才恢复基本联网，而在扫描之前，我看youtube开1080P网速直接顶满。从来没出现过卡顿的情况。而现在，顶多一百个IP资源就算多了。再也达不到那个让我飞的状态了。

**Comment by kli-nlpr** [comment]
@dylanleesky 不要装安全卫士。。

**Comment by dylanleesky** [comment]
@kli-nlpr 我只是临时用它扫描一遍流氓。火绒防护流氓不行。只能用大流氓治小流氓，这次用360我第一件事就是把XX整体加密打包。然后过了一遍用其他软件卸载360清理残留。在恢复xx，就没事了。

**Comment by kli-nlpr** [comment]
@dylanleesky  360眼里，咱们fq就是错。。

**Comment by dylanleesky** [comment]
@kli-nlpr 我那会儿发的帖子 你可以看看， #10158   。我翻墙，1不卖国，2不造反，3不宣扬极端主义。就是喜欢去youtube上看看无广告还流畅的高清视频、去谷歌上搜搜游戏资讯、（其实学会翻墙就是因为当初要用的一个作弊器只有那个被屏蔽的老外的论坛上才有，不得不学会了翻墙，当时用的是goagent）、看看脸书给我推荐的马来学生妹、看看推特里老外的逗逼互怼。如今加上个看看某些“负能量”的国内新闻。

**Comment by asmosn** [comment]
我也有貼主這個問題！老是重複提示，不選擇的話感覺影響加載速度甚至打不開網頁。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/9033

**Comment by SeaHOH** [comment]
不要乱 @
