### ISSUE TITLE
启用IPV6，一段时间后fail，需要再次启用IPV6

### ISSUE THREAD

**Issue by fasdjfrkg** [XX-net/XX-Net#11153]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.12.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:70
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 10
ip-quality: 515
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

使用@beiking 提供的IPV6配置工具，启用IPV6后能连上，使用一段时间后，变成“"仅 IPv6" 不可用，请检查。”，再次启用又可连上。
望解答！

**Comment by AnyWAT** [comment]
参考：#10919 臭大街法则

**Comment by SeaHOH** [comment]
你再次启用花了多少时间？
真的不需要再次启用，不信你就等几分钟。
