### ISSUE TITLE
請問怎麼添加或更改xx-net內置的ipv6服務器

### ISSUE THREAD

**Issue by twuten** [XX-net/XX-Net#11155]
我現在使用的3.12.9版本，只能使用ipv6連接google和facebook,但經常ipv6 fail.按照wiki裡說的禁用ipv6協議後還是有這樣的問題。只是間歇時間長點。現在我想把gaeproxy高級配置裡的默認服務器teredo.remlab.net的改成德國或者芬蘭的服務器。請問我該修改電腦上的哪個文件。昨天已經修改了3.12.9\gae_proxy\local\ipv6_tunnel\下的 enable_ipv6.bat enable_ipv6_temp.bat ipv6.txt都不管用。

**Comment by AnyWAT** [comment]
改用XXXXX服务器：管理权限运行 netsh int ipv6 set teredo enterpriseclient XXXXX 
几乎不见 ipv6 fail ：参考 #10919 臭大街法则

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/blob/fc423b877e7aebd66c8ae13df8a966b73c2d208e/code/default/gae_proxy/local/ipv6_tunnel/common.py#L96-L98
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6#工具
