### ISSUE TITLE
google无法上传图片识图

### ISSUE THREAD

**Issue by tooyangtoonaive** [XX-net/XX-Net#11166]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:500 ipv4:0 ipv6:501
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:31 h2:0
scan-ip-thread-num: 51
ip-quality: 279
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

上传图片网页提示
600:gae_exception:'600:fetch gae fail' https://www.google.com/searchbyimage/uploadgae_exception:'600:fetch gae fail' https://www.google.com/searchbyimage/uploadgae_exception:'600:fetch gae fail' https://www.google.com/searchbyimage/upload

日志
Jul 19 22:29:55.505 - [DEBUG] GAE POST https://www.google.com/searchbyimage/upload from:127.0.0.1:62957

Jul 19 22:29:55.532 - [INFO] scan_ip add ip:2a00:1450:400d:1::a time:399 h2:0

Jul 19 22:29:55.533 - [INFO] remove_slowest_ip:2a00:1450:400d:1::a handshake_time:399, fails:0

Jul 19 22:29:56.022 - [DEBUG] create_ssl update ip:2607:f8b0:401c:2::c time:511 h2:0 sni:x.appspot.com, host:x.appspot.com

Jul 19 22:29:56.792 - [DEBUG] create_ssl update ip:2607:f8b0:400a:e::7 time:779 h2:0 sni:x.appspot.com, host:x.appspot.com

Jul 19 22:29:56.796 - [INFO] scan_ip add ip:2800:3f0:4001:c::17 time:575 h2:0

Jul 19 22:29:56.798 - [INFO] remove_slowest_ip:2607:f8b0:400a:e::7 handshake_time:752, fails:0

Jul 19 22:29:56.820 - [INFO] scan_ip add ip:2607:f8b0:4017:2b::c time:329 h2:0

Jul 19 22:29:56.822 - [INFO] remove_slowest_ip:2800:3f0:4001:c::17 handshake_time:575, fails:0

Jul 19 22:29:56.889 - [INFO] scan_ip add ip:2804:14c:deff::11 time:1210 h2:0

Jul 19 22:29:56.890 - [INFO] remove_slowest_ip:2804:14c:deff::11 handshake_time:1210, fails:0

Jul 19 22:29:57.189 - [INFO] scan_ip add ip:2806:10a8:cfff:5::13 time:431 h2:0

Jul 19 22:29:57.191 - [INFO] remove_slowest_ip:2607:f8b0:401c:2::c handshake_time:511, fails:0

Jul 19 22:29:57.193 - [INFO] scan_ip add ip:2607:f8b0:401a:25::c time:391 h2:0

Jul 19 22:29:57.195 - [INFO] remove_slowest_ip:2806:10a8:cfff:5::13 handshake_time:431, fails:0

Jul 19 22:29:57.219 - [INFO] scan_ip add ip:2a00:1450:4014:2::a time:409 h2:0

Jul 19 22:29:57.220 - [INFO] remove_slowest_ip:2a00:1450:4014:2::a handshake_time:409, fails:0

Jul 19 22:29:57.253 - [INFO] scan_ip add ip:2a00:1450:4003:2::7 time:552 h2:0

Jul 19 22:29:57.255 - [INFO] remove_slowest_ip:2a00:1450:4003:2::7 handshake_time:552, fails:0

Jul 19 22:29:57.561 - [INFO] scan_ip add ip:2804:2bf0:0:1::c time:588 h2:0

Jul 19 22:29:57.564 - [INFO] remove_slowest_ip:2804:2bf0:0:1::c handshake_time:588, fails:0

Jul 19 22:29:57.586 - [INFO] scan_ip add ip:2001:918:ffaa:8::f time:522 h2:0

Jul 19 22:29:57.588 - [INFO] remove_slowest_ip:2001:918:ffaa:8::f handshake_time:522, fails:0

Jul 19 22:29:58.222 - [INFO] scan_ip add ip:2607:f8b0:401d:6::7 time:226 h2:0

Jul 19 22:29:58.223 - [INFO] remove_slowest_ip:2607:f8b0:401a:25::c handshake_time:391, fails:0

Jul 19 22:29:58.277 - [INFO] scan_ip add ip:2405:4800:100:2f::e time:632 h2:0

Jul 19 22:29:58.279 - [INFO] remove_slowest_ip:2405:4800:100:2f::e handshake_time:632, fails:0

Jul 19 22:29:58.382 - [INFO] scan_ip add ip:2607:f8b0:401a:4::8 time:348 h2:0

Jul 19 22:29:58.383 - [INFO] remove_slowest_ip:2607:f8b0:401a:4::8 handshake_time:348, fails:0

Jul 19 22:29:58.405 - [INFO] scan_ip add ip:2800:380:5000:7::1b time:1289 h2:0

Jul 19 22:29:58.407 - [INFO] remove_slowest_ip:2800:380:5000:7::1b handshake_time:1289, fails:0

Jul 19 22:29:58.899 - [INFO] scan_ip add ip:2806:1040:cfff:1::c time:332 h2:0

Jul 19 22:29:58.902 - [INFO] remove_slowest_ip:2806:1040:cfff:1::c handshake_time:332, fails:0

Jul 19 22:29:59.066 - [INFO] scan_ip add ip:2a00:1450:4003:3::c time:548 h2:0

Jul 19 22:29:59.067 - [INFO] remove_slowest_ip:2a00:1450:4003:3::c handshake_time:548, fails:0

Jul 19 22:29:59.192 - [INFO] scan_ip add ip:2a00:1450:4011:3f::17 time:484 h2:0

Jul 19 22:29:59.193 - [INFO] remove_slowest_ip:2a00:1450:4011:3f::17 handshake_time:484, fails:0

Jul 19 22:29:59.215 - [DEBUG] create_ssl update ip:2607:f8b0:400a:17::a time:1517 h2:0 sni:research.queen.org, host:

Jul 19 22:29:59.331 - [INFO] scan_ip add ip:2400:d800:3:560::d time:539 h2:0

Jul 19 22:29:59.333 - [INFO] remove_slowest_ip:2607:f8b0:400a:17::a handshake_time:773, fails:0

Jul 19 22:29:59.532 - [INFO] scan_ip add ip:2a00:1450:4011:4b::19 time:500 h2:0

Jul 19 22:29:59.534 - [INFO] remove_slowest_ip:2400:d800:3:560::d handshake_time:539, fails:0

Jul 19 22:29:59.629 - [INFO] scan_ip add ip:2001:4958:300:502::f time:304 h2:0

Jul 19 22:29:59.630 - [INFO] remove_slowest_ip:2a00:1450:4011:4b::19 handshake_time:500, fails:0

Jul 19 22:29:59.667 - [INFO] scan_ip add ip:2a00:1450:400b:5::e time:661 h2:0

Jul 19 22:29:59.669 - [INFO] remove_slowest_ip:2a00:1450:400b:5::e handshake_time:661, fails:0

Jul 19 22:29:59.769 - [INFO] scan_ip add ip:2001:ee0:3204:7::d time:604 h2:0

Jul 19 22:29:59.770 - [INFO] remove_slowest_ip:2001:ee0:3204:7::d handshake_time:604, fails:0

Jul 19 22:29:59.901 - [INFO] scan_ip add ip:2804:7f1:a005:cacf::11 time:525 h2:0

Jul 19 22:29:59.903 - [INFO] remove_slowest_ip:2804:7f1:a005:cacf::11 handshake_time:525, fails:0

Jul 19 22:30:00.230 - [INFO] scan_ip add ip:2404:6800:400b:6::7 time:478 h2:0

Jul 19 22:30:00.231 - [INFO] remove_slowest_ip:2404:6800:400b:6::7 handshake_time:478, fails:0

Jul 19 22:30:00.236 - [INFO] scan_ip add ip:2a02:8400:0:110::f time:1407 h2:0

Jul 19 22:30:00.237 - [INFO] remove_slowest_ip:2a02:8400:0:110::f handshake_time:1407, fails:0

Jul 19 22:30:00.311 - [INFO] scan_ip add ip:2001:ee0:3200:f::f time:780 h2:0

Jul 19 22:30:00.312 - [INFO] remove_slowest_ip:2001:ee0:3200:f::f handshake_time:780, fails:0

Jul 19 22:30:00.511 - [WARNING] 2600:5:100:1::e h1_request:Error([('SSL routines', 'ssl3_write_pending', 'bad write retry')],) inactive_time:8 task.timeout:15

Jul 19 22:30:00.511 - [WARNING] 2600:5:100:1::e trace: 0:connect, 3237:init, 387:request,:5000, processed:0, transfered:0, sni:warcraftzc.appspot.com

Jul 19 22:30:00.511 - [WARNING] retry_task_cb: POST None/_gh/

Jul 19 22:30:00.511 - [DEBUG] 2600:5:100:1::e worker close:down fail

**Comment by SeaHOH** [comment]
请先尝试最新稳定版

**Comment by tooyangtoonaive** [comment]
@SeaHOH 
使用3.12.10依然不行，而且使用goole搜索，相比3.11.15秒开，新版更慢

Jul 22 13:50:08.590 - [INFO] GAE t:5042 s:22558 GET https://www.google.com.hk/xjs/_/js/k=xjs.s.zh_TW.6s34iRdpjjM.O/am=IIswG0MAkP9TGEgUaAUjLCCBgiAC/rt=j/d=1/exm=sx,sb,cdos,elog,hsm,jsa,r,d,csi/ed=1/dg=0/rs=ACT90oEq8jpJAh3tGBK8JnH8FJp5U-wA-Q/m=aa,foot,ipv6,mu,qi,d3l?xjs=s1 0:start_request,0:get_task(1),4447:get_worker(4):2001:578:2a:302::10,0:h1_req,0:h1_req_sended,364:response_begin,0:h1_get_head,0:get_response,231:h1_finish[SP:38404],:0

Jul 22 13:50:09.703 - [DEBUG] create_ssl update ip:2607:f8b0:4006:36::8 time:741 h2:0 sni:emergency.review.ml, host:x.appspot.com

Jul 22 13:50:11.047 - [DEBUG] GAEProxy web_control 127.0.0.1:50481 POST /config?cmd=get_config

Jul 22 13:50:11.569 - [DEBUG] create_ssl update ip:2607:f8b0:400f:12::b time:865 h2:0 sni:boringreserve.org, host:x.appspot.com

Jul 22 13:50:12.616 - [DEBUG] recheck_ip:2607:f8b0:401e:2b::b restore ok

Jul 22 13:50:14.153 - [DEBUG] create_ssl update ip:2607:f8b0:401e:27::8 time:1057 h2:0 sni:miss-ground-slice.net, host:

Jul 22 13:50:16.181 - [DEBUG] GAE POST https://www.google.com.hk/searchbyimage/upload from:127.0.0.1:50531

Jul 22 13:50:16.212 - [DEBUG] create_ssl update ip:2607:f8b0:401e:27::7 time:1058 h2:0 sni:couple-instruction-parent.org, host:

Jul 22 13:50:17.949 - [DEBUG] recheck_ip:2607:f8b0:4006:33::c restore ok

Jul 22 13:50:18.826 - [DEBUG] create_ssl update ip:2607:f8b0:400f:f::9 time:1256 h2:0 sni:courtplate.ml, host:warcraftzc.appspot.com

Jul 22 13:50:21.495 - [WARNING] task POST None /_gh/ timeout

Jul 22 13:50:21.495 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Jul 22 13:50:21.495 - [WARNING] gae_exception:'600:fetch gae fail' https://www.google.com.hk/searchbyimage/upload

**Comment by AnyWAT** [comment]
使用3.12.10，增大全局缓冲、设置优先级（这——神马鬼？）、设置（增大）扫描线程、关闭自动调整扫描线程有效（🤫不会立竿见影）
![default](https://user-images.githubusercontent.com/37962734/43043015-53f8d860-8dbc-11e8-808d-e245d50845d2.png)

**Comment by AnyWAT** [comment]
600:gae_exception:'600:fetch gae fail——貌似连接池较少、IP延时大等代理速度不够的锅

**Comment by SeaHOH** [comment]
POST（上传）如果速度太慢，结果会被超时抛弃。

你们就不要追求啥瞬开了，延迟小点秒开还是可以的。
说个事实，自从全面限制了连接池后，teredo 隧道的状况好转了许多。
推测是大量 XX-Net 客户端通过无效的连接池数量（仅建立连接但是根本就没有使用）占用了 teredo 隧道服务器大量连接数，导致被连接 IP 被隧道服务器暂时封锁（也可能是哪里崩溃或其它原因，反正表现地像封锁）。
