### ISSUE TITLE
浏览器提示仅ipv6不可用，尝试修复后无效

### ISSUE THREAD

**Issue by a1798636524** [XX-net/XX-Net#11162]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
诊断信息如上
Jul 19 10:24:28.524 - [DEBUG] connect 2607:f8b0:4005:1a::a blocked: network fail

Jul 19 10:24:29.029 - [DEBUG] connect 2600:6:400:1::12 blocked: network fail

Jul 19 10:24:29.539 - [DEBUG] connect 2607:f8b0:400a:9::7 blocked: network fail

Jul 19 10:24:30.095 - [DEBUG] connect 2607:f8b0:400b:10::c blocked: network fail

Jul 19 10:24:30.546 - [DEBUG] connect 2607:f8b0:4006:3b::8 blocked: network fail

Jul 19 10:24:31.103 - [DEBUG] connect 2001:1970:1:2052::d blocked: network fail

Jul 19 10:24:31.568 - [DEBUG] connect 2620:11a:a02d::1a blocked: network fail

Jul 19 10:24:32.077 - [DEBUG] connect 2607:f798:1e:20::12 blocked: network fail

Jul 19 10:24:32.571 - [DEBUG] connect 2001:4958:300:4f3::11 blocked: network fail

Jul 19 10:24:33.099 - [DEBUG] create ssl timeout fail.

Jul 19 10:24:53.219 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 19 10:24:53.444 - [DEBUG] network IPv4 is ok, cost:223 ms

Jul 19 10:25:00.454 - [DEBUG] report_connect_fail IPv6 continue_fail_count:18

Jul 19 10:25:36.601 - [DEBUG] GAEProxy web_control 127.0.0.1:61695 POST /config?cmd=get_config

Jul 19 10:25:39.013 - [DEBUG] GAEProxy web_control 127.0.0.1:61695 POST /config?cmd=get_config

Jul 19 10:25:39.017 - [DEBUG] GAEProxy Web_control 127.0.0.1:61695 GET /scan_ip?cmd=get_range

Jul 19 10:25:39.018 - [INFO] load ip range file:D:\Program Files\XX-Net-3.12.0\code\3.12.10\gae_proxy\local\ip_range.txt

Jul 19 10:25:40.841 - [DEBUG] GAEProxy Web_control 127.0.0.1:61695 GET /ipv6_tunnel?cmd=get_priority

Jul 19 10:25:40.843 - [DEBUG] GAEProxy Web_control 127.0.0.1:61693 GET /ipv6_tunnel?cmd=get_log

Jul 19 10:25:41.099 - [DEBUG] netsh state: Teredo --------------------------------------------- : enterpriseclient : teredo.remlab.net. ͻˢ¼ : 30 ͻ˶˿ : unspecified ״̬ : qualified ͻ : teredo client : unmanaged NAT : cone NAT Ϊ : UPNP: PortPreserving: ӳ : 192.168.0.103:64475 ⲿ NAT ӳ : 120.0.69.250:64475

Jul 19 10:25:44.467 - [DEBUG] report_connect_fail IPv6 continue_fail_count:19

Jul 19 10:25:51.044 - [DEBUG] GAEProxy Web_control 127.0.0.1:61755 GET /check_ip?cmd=get_process

Jul 19 10:25:52.048 - [DEBUG] GAEProxy Web_control 127.0.0.1:61755 GET /check_ip?cmd=get_process

Jul 19 10:25:53.056 - [DEBUG] GAEProxy Web_control 127.0.0.1:61755 GET /check_ip?cmd=get_process

Jul 19 10:25:54.056 - [DEBUG] GAEProxy Web_control 127.0.0.1:61755 GET /check_ip?cmd=get_process

Jul 19 10:25:54.475 - [DEBUG] GAEProxy Web_control 127.0.0.1:61755 GET /check_ip?cmd=start

Jul 19 10:25:54.477 - [DEBUG] start scan all exist ip, num:100

Jul 19 10:25:55.061 - [DEBUG] GAEProxy Web_control 127.0.0.1:61755 GET /check_ip?cmd=get_process

Jul 19 10:25:55.588 - [DEBUG] report_connect_fail IPv6 continue_fail_count:20

Jul 19 10:25:56.369 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:25:57.078 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:25:58.070 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:25:59.071 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:00.064 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:01.077 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:02.081 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:03.082 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:04.086 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:04.624 - [INFO] Adjust scan thread num from 0 to 10

Jul 19 10:26:04.627 - [DEBUG] finished scan all exist ip

Jul 19 10:26:05.088 - [DEBUG] GAEProxy Web_control 127.0.0.1:61824 GET /check_ip?cmd=get_process

Jul 19 10:26:06.396 - [DEBUG] GAEProxy Web_control 127.0.0.1:61902 GET /check_ip?cmd=get_process

Jul 19 10:26:07.096 - [DEBUG] GAEProxy Web_control 127.0.0.1:61902 GET /check_ip?cmd=get_process

Jul 19 10:26:08.100 - [DEBUG] GAEProxy Web_control 127.0.0.1:61902 GET /check_ip?cmd=get_process

Jul 19 10:26:09.101 - [DEBUG] GAEProxy Web_control 127.0.0.1:61902 GET /check_ip?cmd=get_process

Jul 19 10:26:10.106 - [DEBUG] GAEProxy Web_control 127.0.0.1:61902 GET /check_ip?cmd=get_process

Jul 19 10:26:11.093 - [DEBUG] GAEProxy Web_control 127.0.0.1:61904 GET /check_ip?cmd=get_process

Jul 19 10:26:12.480 - [DEBUG] GAEProxy Web_control 127.0.0.1:61904 GET /deploy?cmd=get_log

Jul 19 10:26:28.469 - [WARNING] network IPv6 fail

Jul 19 10:26:48.678 - [DEBUG] report_connect_fail IPv6 continue_fail_count:21

Jul 19 10:26:58.719 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 19 10:26:59.007 - [DEBUG] network IPv4 is ok, cost:287 ms

Jul 19 10:27:32.707 - [DEBUG] report_connect_fail IPv6 continue_fail_count:22

Jul 19 10:28:07.788 - [DEBUG] GAEProxy web_control 127.0.0.1:62456 POST /config?cmd=get_config

Jul 19 10:28:09.639 - [DEBUG] GAEProxy Web_control 127.0.0.1:62456 GET /ipv6_tunnel?cmd=get_priority

Jul 19 10:28:09.642 - [DEBUG] GAEProxy Web_control 127.0.0.1:62455 GET /ipv6_tunnel?cmd=get_log

Jul 19 10:28:11.127 - [DEBUG] netsh state: Teredo --------------------------------------------- : enterpriseclient : teredo.remlab.net. ͻˢ¼ : 30 ͻ˶˿ : unspecified ״̬ : qualified ͻ : teredo client : unmanaged NAT : cone NAT Ϊ : UPNP: PortPreserving: ӳ : 192.168.0.103:64475 ⲿ NAT ӳ : 120.0.69.250:64475

Jul 19 10:28:16.692 - [WARNING] network IPv6 fail

Jul 19 10:28:16.726 - [DEBUG] report_connect_fail IPv6 continue_fail_count:23

Jul 19 10:29:00.773 - [DEBUG] report_connect_fail IPv6 continue_fail_count:24

Jul 19 10:29:21.300 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Jul 19 10:29:21.536 - [DEBUG] network IPv4 is ok, cost:233 ms
这是最新的日志

**Comment by a1798636524** [comment]
属性 | 值
-- | --
Teredo 隧道 | 合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)

**Comment by a1798636524** [comment]
还是一直提示仅ipv6不可用，该怎么办

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）

**Comment by EverFAITH** [comment]
C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.iks-jena.de.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

**Comment by EverFAITH** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:17
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:19 h2:0
scan-ip-thread-num: 50
ip-quality: 1148
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by EverFAITH** [comment]
我也出现仅IPV6不可用的情况。

**Comment by AnyWAT** [comment]
出现仅IPV6不可用：
1、重开一个XX-Net（可挤出貌似已不正常的），稍侯，不行
2、禁用再启用网络。。。
