### ISSUE TITLE
3.9.6版本开启IPV6后，ipv6状态时而OK时而Fail

### ISSUE THREAD

**Issue by 211Yang** [XX-net/XX-Net#11165]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
试过，最新版本xx-net启动不了。

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
查看过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: x86_64, Darwin-16.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64
os-release: 16.7.0
os-detail: Release:10.12.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3624 ipv4:64 ipv6:1966
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 283
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

截图如下：
![Uploading 7F55C107-309F-4782-B84A-A8C8602165A1.png…]()

**Comment by 211Yang** [comment]
![7f55c107-309f-4782-b84a-a8c8602165a1](https://user-images.githubusercontent.com/5978235/42944076-4388f090-8b97-11e8-8df4-000ec33c10c1.png)

**Comment by 211Yang** [comment]
这是诊断信息：
XX-Net Status:

sys-platform: x86_64, Darwin-16.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64
os-release: 16.7.0
os-detail: Release:10.12.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3624 ipv4:10 ipv6:2224
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 280
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 211Yang** [comment]
![image](https://user-images.githubusercontent.com/5978235/42944546-853dd3d8-8b98-11e8-8258-4a61b06e610e.png)
miredo是开启的

**Comment by SeaHOH** [comment]
你换哪个版本都一样，你的网络环境如此。

**Comment by 211Yang** [comment]
@SeaHOH 网络环境有什么问题？

**Comment by whhxmwhh** [comment]
网络的污染严重。鱼儿看不清方向。

**Comment by xiayh04** [comment]
同样问题, 等待大神解答

**Comment by SeaHOH** [comment]
是说可能是隧道连接受到干扰不稳定。
尝试切换其它 mode，应该还有个`client`。

**Comment by hzq21** [comment]
DNS被污染了。。

**Comment by hzq21** [comment]
DNS污染严重了。。可能。
