### ISSUE TITLE
3.12.10 版本使用长城宽带，有效 IPv6 IP 数只有几。

### ISSUE THREAD

**Issue by tatiyixi** [XX-net/XX-Net#11169]
3.12.10 版本使用长城宽带，有效 IPv6 IP 数只有几。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:6
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:4 h2:0
scan-ip-thread-num: 10
ip-quality: 1240
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by fengqx88** [comment]
可能跟网络有关，网络好的地方IPV6会多，飘忽不定，大多数可以用，偶尔会0

**Comment by waitingHao** [comment]
长城宽带不行，以前用长城ipv6根本用不了，换电信就可以了。
