### ISSUE TITLE
3.12.10版本，可以用google，可以登录google邮箱，就是不能打开邮件

### ISSUE THREAD

**Issue by yfor1008** [XX-net/XX-Net#11161]
如题，诊断信息如下：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:21 h2:0
scan-ip-thread-num: 30
ip-quality: 264
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
我说的是你点击邮件时的日志

**Comment by yfor1008** [comment]
Jul 19 10:09:31.819 - [INFO] scan_ip add ip:2a00:1450:4011:47::14 time:438 h2:0

Jul 19 10:09:31.819 - [INFO] remove_slowest_ip:2a00:1450:4011:47::14 handshake_time:438, fails:0

Jul 19 10:09:31.934 - [INFO] scan_ip add ip:2a02:240:0:2::e time:745 h2:0

Jul 19 10:09:31.935 - [INFO] remove_slowest_ip:2a02:240:0:2::e handshake_time:745, fails:0

Jul 19 10:09:32.356 - [DEBUG] GAE POST https://mail.google.com/mail/u/0/?ui=2&ik=f73a968e90&jsver=mvEgwuExeUY.zh_CN.&cbl=gmail_fe_180712.09_p2&rid=mail%3Ao.b444.1.0&at=AF6bupPBywwRLsBuwW_MgRUbXd22H6j4aw&view=up&act=oepca&_reqid=736371&nsc=1&mb=0&rt=j from:127.0.0.1:29290

Jul 19 10:09:32.680 - [INFO] scan_ip add ip:2001:ee0:3201:3::f time:584 h2:0

Jul 19 10:09:32.681 - [INFO] remove_slowest_ip:2001:ee0:3201:3::f handshake_time:584, fails:0

Jul 19 10:09:32.762 - [INFO] scan_ip add ip:2800:3f0:4001:1c::a time:564 h2:0

Jul 19 10:09:32.763 - [INFO] remove_slowest_ip:2800:3f0:4001:1c::a handshake_time:564, fails:0

Jul 19 10:09:32.954 - [DEBUG] create_ssl update ip:2620:11a:a00a::21 time:595 h2:0 sni:white-reserve-classic.us, host:xxnet-07-147002.appspot.com

Jul 19 10:09:32.978 - [INFO] GAE t:621 s:411 POST https://mail.google.com/mail/u/0/?ui=2&ik=f73a968e90&jsver=mvEgwuExeUY.zh_CN.&cbl=gmail_fe_180712.09_p2&rid=mail%3Ao.b444.1.0&at=AF6bupPBywwRLsBuwW_MgRUbXd22H6j4aw&view=up&act=oepca&_reqid=736371&nsc=1&mb=0&rt=j 0:start_request,0:get_task(64),0:get_worker(0):2607:f8b0:401c:1::a,1:h1_req,0:h1_req_sended,619:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:1383],:0

Jul 19 10:09:33.154 - [INFO] scan_ip add ip:2001:ee0:3206::e time:546 h2:0

Jul 19 10:09:33.154 - [INFO] remove_slowest_ip:2620:11a:a00a::21 handshake_time:595, fails:0

Jul 19 10:09:33.305 - [INFO] scan_ip add ip:2804:7f7:f000:cade::12 time:570 h2:0

Jul 19 10:09:33.305 - [INFO] remove_slowest_ip:2804:7f7:f000:cade::12 handshake_time:570, fails:0

Jul 19 10:09:33.401 - [DEBUG] create_ssl update ip:2607:f8b0:401c:2f::6 time:541 h2:0 sni:confidencemachine.org, host:xxnet-pltznpgu.appspot.com

Jul 19 10:09:34.190 - [INFO] scan_ip add ip:2620:11a:a00a::1b time:220 h2:0

Jul 19 10:09:34.191 - [INFO] remove_slowest_ip:2001:ee0:3206::e handshake_time:546, fails:0

Jul 19 10:09:35.800 - [INFO] scan_ip add ip:2a00:1450:400d:3::7 time:385 h2:0

Jul 19 10:09:35.801 - [INFO] remove_slowest_ip:2607:f8b0:401c:2f::6 handshake_time:541, fails:0

Jul 19 10:09:35.872 - [INFO] scan_ip add ip:2a00:1450:4011:2c::13 time:445 h2:0

Jul 19 10:09:35.873 - [INFO] remove_slowest_ip:2a00:1450:4011:2c::13 handshake_time:445, fails:0

**Comment by SeaHOH** [comment]
日志看起来是正常的，只能 F12 netwok 看哪个网址加载失败，估计你代理设置不正确。

**Comment by yfor1008** [comment]
代理设置应该没有问题吧，打开邮箱时，有这个错误：
`Uncaught SyntaxError: Unexpected end of input`

**Comment by SeaHOH** [comment]
> 只能 F12 netwok 看哪个网址加载失败
> Uncaught SyntaxError: Unexpected end of input

页面加载不全

**Comment by yfor1008** [comment]
我清除了chrome的所有浏览器数据，就可以了

**Comment by SeaHOH** [comment]
估计 有错误的 js 文件被缓存

**Comment by yfor1008** [comment]
@SeaHOH  谢谢！！！
