### ISSUE TITLE
windows 3.12.10启动不了 状态页打不开

### ISSUE THREAD

**Issue by wangjiepower** [XX-net/XX-Net#11163]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

Jul 19 15:37:38.216 - [INFO] use build-in openssl lib
Jul 19 15:37:38.221 - [INFO] start XX-Net 3.12.10
Jul 19 15:37:38.221 - [DEBUG] start confirm_xxnet_exit
Jul 19 15:37:38.243 - [DEBUG] <0>: try to terminate xxnet:8085
Jul 19 15:37:40.259 - [DEBUG] good, xxnet:8085 clear!
Jul 19 15:37:40.259 - [DEBUG] finished confirm_xxnet_exit
Jul 19 15:37:51.481 - [INFO] module gae_proxy started
Jul 19 15:37:51.481 - [INFO] start gae_proxy time cost:11220 ms
Jul 19 15:37:51.636 - [INFO] module x_tunnel started
Jul 19 15:37:51.636 - [INFO] start x_tunnel time cost:154 ms
Jul 19 15:37:51.768 - [INFO] module smart_router started
Jul 19 15:37:51.768 - [INFO] start smart_router time cost:131 ms
Jul 19 15:37:51.768 - [INFO] begin to start web control
Jul 19 15:37:51.770 - [INFO] server 127.0.0.1:8085 started.
Jul 19 15:37:51.770 - [INFO] launcher web control started.
Jul 19 15:37:52.859 - [INFO] get uuid:0fba8746-466b-4eaa-ab8c-7e7d79c1835e
Jul 19 15:38:13.865 - [WARNING] check_update fail:URLError(error(10060, ''),)
Jul 19 15:38:13.865 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to D:\Program Files\XX-Net-3.12.10\data\downloads\version.txt, retry:0

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
你下载的时候验证过没有？
sha256:`8a387db84763bb016c43d969f91e08b33c323f803279f294dc5f373abde4f0ba`

**Comment by wangjiepower** [comment]
验证过，sha256一致的，3.11.15的版本是可用的，新的版本都是启动不了

**Comment by wangjiepower** [comment]
win10的系统，日志没有了，有个现象就是3.11.15启动的时候会提示启动pythonw，其它版本没有
另外，启动新版本时会提示移除老版本的CA

**Comment by maxjove** [comment]
一样 ,从 3.12.9开始就启动不了, 目前只能用3.12.8

**Comment by SeaHOH** [comment]
@maxjove 你的系统是？有启动失败的日志`data\launcher`吗？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/releases V 3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）

**Comment by wangjiepower** [comment]
@AnyWAT 就是客户端更新了启动不了

**Comment by 5513541651321** [comment]
我和你是一样的问题，关闭防火墙就OK了！

**Comment by wangbodzh** [comment]
@wangjiepower
亲测，关闭防火墙能解决问题。

**Comment by SeaHOH** [comment]
防火墙还是打开的好，出站放行即可。
第一次运行或升级后，防火墙提示监听请求，允许即可。

**Comment by wangjiepower** [comment]
关掉可行

**Comment by SeaHOH** [comment]
>还有，防火墙检查过没有？

还以为不是防火墙的原因，上面不是提醒你检查了嘛。

**Comment by wangjiepower** [comment]
@SeaHOH 出站放行针对pythonw.exe?没有看到提示监听请求

**Comment by wangjiepower** [comment]
@SeaHOH 是的，不好意思，忘了检查

**Comment by SeaHOH** [comment]
首次运行会监听的程序 Win7 会提示，Win10 不清楚。

放行出站是必须的，由于更新会导致位置变化，所以出站全部放行比较简单。
如果不想这样，只能手动添加针对单一位置的放行规则。

**Comment by wangjiepower** [comment]
了解了，谢谢

**Comment by AnyWAT** [comment]
Win10 至少在 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel 点击测试时有弹窗
