### ISSUE TITLE
QQ浏览器始终 “浏览器代理设置和CA”fail

### ISSUE THREAD

**Issue by diyd123** [XX-net/XX-Net#11160]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
最新的 3.12.10 版本 ，使用win自带ie 可用 ，QQ浏览器 不行 始终“浏览器代理设置	Fail
CA 证书状态(下载)	Fail”重置 重装 所有可行设置均设置过，包括浏览器的设置 重装。求解决办法

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: x86, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5702.400 QQBrowser/10.2.1893.400
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:79
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 486
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by whhxmwhh** [comment]
换谷歌浏览器

**Comment by diyd123** [comment]
换浏览器是一个回事，但是可以用的 突然之间不能用了怎么解决？

**Comment by SeaHOH** [comment]
> 但是可以用的 突然之间不能用了

什么版本，什么情况下能用？

**Comment by diyd123** [comment]
xxnet 和qq浏览器都是最新版本，直接运行start.bat 跳转到网页 直接显示fail。 换了自带IE或其他浏览器均无这个问题，跳转页面 自动可以访问真正的互联网。

**Comment by SeaHOH** [comment]
你还是没解释你自己说的“突然之间不能用了”。
而且你这个描述，明显是浏览器，或者浏览器配置错误，建议先重置配置。

**Comment by diyd123** [comment]
突然之间不能用就是  头一天还很正常，第二天按正常步骤 登录 显示 两个fail ，期间没有任何浏览器设置操作， 查阅相关所有关于这个的操操作，如 重装xxnet/qq浏览器， 下载ca ，删除原有证书，清缓存等所有可知的设置/配置，没有任何解决办法， 不知道是QQ浏览器当方面阻拦了还是怎么  ，其余浏览器 都没有任何问题 都是一样配置OK，直接登录google

**Comment by SeaHOH** [comment]
你的 QQ 浏览器是登录的吧，退出登录，重置配置，重启浏览器。

**Comment by whhxmwhh** [comment]
QQ 浏览器建议完全卸载了。他会收集你的翻墙办法。然后提供给墙公司，墙公司针对情况进行加高砖头。

**Comment by timaxell** [comment]
这等于是把可以直连的IP报告给腾讯，帮封锁者添砖加瓦搜集数据。
那么反感 Chrome 吗？硬要用QQ浏览器？

**Comment by zzgpku** [comment]
推荐使用cent browser
