### ISSUE TITLE
mac下miredo中的状态标示一直是红色

### ISSUE THREAD

**Issue by lluoyulin** [XX-net/XX-Net#11178]
qualified: True
NAT type: restricted
best server is: teredo.remlab.net.
这是测试出来的结果，这是什么原因？

**Comment by SeaHOH** [comment]
搜索 mac miredo，尝试切换服务器。

**Comment by lluoyulin** [comment]
@SeaHOH miredo默认服务器地址是teredo.remlab.net，我在miredo里面修改过其他地址还是不行，都还是红色

**Comment by SeaHOH** [comment]
> 搜索 mac miredo

有人说删除后新建个连接可能会恢复正常。

**Comment by SeaHOH** [comment]
teredo 隧道连接
