### ISSUE TITLE
托盘图标右键菜单问题

### ISSUE THREAD

**Issue by EliteOtaku** [XX-net/XX-Net#11174]
估计是个bug，虽然可以正常使用，但是必须通过switchy omega，在托盘图标右键菜单，永远都是固定在“取消全局代理”这个选择上，点击选择其他都无效，不知道为什么。

因为最近想切换到smart router上去，取代以前的switchy omega，但是现在即使关闭switchy omega后打开smart router，也无法翻墙。

感觉有可能是个bug，但日志一切正常，也不知道在哪里可以查看。

**Comment by SeaHOH** [comment]
Win10？

**Comment by EliteOtaku** [comment]
是的，win10 64位，最新补丁

**Comment by SeaHOH** [comment]
#10620
