### ISSUE TITLE
ipv6状态更新不及时

### ISSUE THREAD

**Issue by zegzhi** [XX-net/XX-Net#11171]
最新几个测试版才开始遇到的问题。
因为网络原因 ipv6 会不定时中断，但是在ipv6恢复的时候 xxnet 的状态还是显示 `"仅 IPv6" 不可用，请检查。`，并且代理无法使用 。需要等待很长时间或者手动重启软件才会恢复。

相关截图：
![tim 20180721132003](https://user-images.githubusercontent.com/16538800/43032467-1900f648-8cea-11e8-99f2-0dead175dbf5.png)
![tim 20180721132048](https://user-images.githubusercontent.com/16538800/43032469-1faad1da-8cea-11e8-9ad1-b5a61c0b17fb.png)

**Comment by AnyWAT** [comment]
#10919 臭大街法则几乎没有“不定时中断”

**Comment by SeaHOH** [comment]
状态更新一直都是不精确的，你可以测试下以前的版本。
