### ISSUE TITLE
安卓平台版本疑问

### ISSUE THREAD

**Issue by wtr19941227** [XX-net/XX-Net#11179]
XX-Net Status:

sys-platform: armv8l, Linux-4.4.78-13776057-armv8l-with
os-system: Linux
os-version: #1 SMP PREEMPT Wed Jun 20 09:44:50 KST 2018
os-release: 4.4.78-13776057
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.0.0; SM-G9500 Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36
xxnet-version: 3.6.3

python-version: 2.7.2
openssl-version: 0.14 TLSv1_2 h2:no

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
放弃安卓？https://github.com/XndroidDev/Xndroid

**Comment by AnyWAT** [comment]
xxnet-version: 3.6.3——我真的需要等两个小时？——🤣或许再翻10倍也枉然？
![default](https://user-images.githubusercontent.com/37962734/43044473-126845b2-8dd9-11e8-8c4c-9e5203fc027a.png)

**Comment by wtr19941227** [comment]
@AnyWAT  多谢   但您给出新的链接中来下载的东西真的好慢啊  才几k的下载速度

**Comment by AnyWAT** [comment]
貌似本网下载、上图需代理

**Comment by wtr19941227** [comment]
很棒  已经开始使用了  网速很快
