### ISSUE TITLE
3.12.10 http服务没有启动，没法改配置

### ISSUE THREAD

**Issue by Kyrosee** [XX-net/XX-Net#11175]
3.12.10 http服务没有启动，无法访问http://127.0.0.1:8085，没法改配置，任务栏看不到XXNET的图标
但是任务管理器有python.exe,而且能正常翻墙，咋回事呢？

**Comment by SeaHOH** [comment]
你是怎么启动 XX-Net 的？
你的代理设置是怎样的？截个图。

**Comment by Kyrosee** [comment]
找到问题了，是系统的一个进程暂用了8085端口导致服务器没法启动！
