### ISSUE TITLE
好长时间不登陆了，一直显示连接尚未建立。

### ISSUE THREAD

**Issue by homeVersion** [XX-net/XX-Net#11183]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1701 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: Connect Blocked, 0 seconds to wait.
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
参考 #10919 臭大街法则

**Comment by SeaHOH** [comment]
看公告

**Comment by AnyWAT** [comment]
由于之前谷歌服务器全面部署新证书，旧版本 XX-Net 无法验证。
请升级到修复了证书问题的稳定版本 3.12.2。

实在想用旧版本的用户，可以这么做：

替换新的 gae_proxy/local/cacert.pem 文件。
还在使用 ini 配置的版本，在上面这个文件夹搜索No intermediate CA was found，将上面一行的< 3 换成< 2。
使用 json 配置的版本，在 config.py 文件，修改min_intermediate_CA参数为2。

**Comment by AnyWAT** [comment]
没在公告内：https://github.com/XX-net/XX-Net/releases V 3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
