### ISSUE TITLE
xx-net,wujie下载youtube都出错，freegate竟然没出错。。。

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#11187]
xx-net,wujie下载youtube都出错，freegate竟然没出错。。

freegateV7.64威武了，哈哈哈

**Comment by AnyWAT** [comment]
5年不关机才V5🤣

**Comment by AnyWAT** [comment]
转：推荐2个支持1000+网站视频解析下载的网站，https://goo.gl/EmAZVr  https://goo.gl/RCVNMp
