### ISSUE TITLE
"仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by tycoontin** [XX-net/XX-Net#11186]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是，并尝试了开启IPv6的-win7的方法。
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged
-------------------------------------------------------------------------------------------------------------------
XX-Net Status:
sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
………………………………………………………………………………………………………………………………………………………………………

**Comment by bluechang** [comment]
同上

IPv6：[8425](https://github.com/XX-net/XX-Net/issues/8425)

XX-Net Status:

sys-platform: x86_64, Darwin-17.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
os-release: 17.7.0
os-detail: Release:10.13.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 254
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by tycoontin** [comment]
qualified: False
NAT type: offline
no server detected, return default: teredo.remlab.net.
………………………………………………………………………………………………………………………………………………………………………
不行。

**Comment by zhanghua000** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:64
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 535
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
同上
在等待较长的一段时间（约10分钟）后可以恢复正常。
