### ISSUE TITLE
怎么设置能支持Web登陆 discordapp.com

### ISSUE THREAD

**Issue by earthGavinLee** [XX-net/XX-Net#11189]
使用最新版本一直无法登陆 discordapp.com
![screenshot from 2018-07-24 21-33-03](https://user-images.githubusercontent.com/8288083/43141715-33d0f616-8f89-11e8-9f14-7fd83e0e999c.png)

**Comment by SeaHOH** [comment]
这个网站无需翻墙

**Comment by earthGavinLee** [comment]
``

**Comment by earthGavinLee** [comment]
我这里已经被墙了

**Comment by SeaHOH** [comment]
DNS 污染

**Comment by MeABc** [comment]
discordapp.com 这个网站应该是被墙了。GFWList 收录了（间接确定大部份地区被墙）。

**Comment by MeABc** [comment]
XX-NET 没有用 gfwlist.txt 吗?

**Comment by MeABc** [comment]
看到这个 issue 有两个想法：
1、xx-net 应有不用重启就可以让  gfwlist.txt 列表生效的方法。（或许已有）。这样就不会有大量用户反映此类问题。
2、依赖 xx-net 大量的用户基数， 应该有明显的链接引导用户去 https://github.com/gfwlist/gfwlist 反映情况。这是一个多赢的结果。

**Comment by SeaHOH** [comment]
smart router 模块并未设计有更新  gfwlist 的功能，但是它支持反 DNS 污染。
SwitchyOmega 自动切换规则支持自动更新 gfwlist。

所以上面这位肯定没有用 smart router 或 SwitchyOmega 自动切换规则。
