### ISSUE TITLE
我想問一下 推特搜索不了和論壇登錄了馬上退出是什麼問題

### ISSUE THREAD

**Issue by okaylabababa** [XX-net/XX-Net#11180]
這些問題一直都有的 最近上不了的論壇多了 登錄了刷新就沒登錄的狀態
推特也搜不到
![default](https://user-images.githubusercontent.com/32033614/43047693-cc118ec2-8e0d-11e8-8b56-fe3e8873cdf0.PNG)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/10502

**Comment by okaylabababa** [comment]
@AnyWAT 論壇馬上登出的問題 有這種情況嗎

**Comment by AnyWAT** [comment]
参考 #10919 臭大街法则
