### ISSUE TITLE
win10更新了1083后 6to4tunnel的功能模块貌似被移除了？

### ISSUE THREAD

**Issue by cccwhatuneed** [XX-net/XX-Net#11197]
建立隧道的命令 显示 没有为设备信息集或元素选择驱动程序

没了6to4tunnel显然是不能用ipv6了

显然就会...

**Comment by cccwhatuneed** [comment]
如何手动添加这个模块？

或者更新回滚回旧版？

**Comment by cccwhatuneed** [comment]
还是 命令模式 有变化了？ 似乎不大可能......

此模块被意外摘除了...?

**Comment by SeaHOH** [comment]
没图，你在这里猜还不如找Windows售后。
https://support.microsoft.com/zh-cn/contactus/

**Comment by AnyWAT** [comment]
https://support.microsoft.com/zh-cn/help/929852/
