### ISSUE TITLE
打开pornhub总是提示Is undergoing maintenance（正在维护）

### ISSUE THREAD

**Issue by pb919** [XX-net/XX-Net#11190]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:12 h2:0
scan-ip-thread-num: 20
ip-quality: 296
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

日志：
Jul 24 22:02:24.381 - [INFO] GAE t:5707 s:0 GET https://ds.phncdn.com/www-static/images/pornhub_logo.png?cache=XXXXXXXX 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4007:2f::7,0:h1_req,1:h1_req_sended,5703:response_begin,0:h1_get_head,0:h1_finish[SP:35],0:get_response,:0

Jul 24 22:02:24.429 - [INFO] GAE t:5704 s:0 GET https://ds.phncdn.com/www-static/images/maintenance/logosprite.png?cache=2018062803 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4017:32::9,0:h1_req,0:h1_req_sended,5703:response_begin,0:h1_get_head,0:h1_finish[SP:35],0:get_response,:0

Jul 24 22:02:24.554 - [INFO] scan_ip add ip:2404:6800:400b:2c::8 time:486 h2:0

Jul 24 22:02:24.554 - [INFO] remove_slowest_ip:2607:f8b0:400b:e::8 handshake_time:300, fails:1

Jul 24 22:02:24.577 - [INFO] scan_ip add ip:2620:11a:a018:2::10 time:472 h2:0

Jul 24 22:02:24.577 - [INFO] remove_slowest_ip:2a00:1450:4005:c::c handshake_time:552, fails:0

Jul 24 22:02:24.678 - [INFO] GAE t:5953 s:10 GET https://ds.phncdn.com/cdn_files/images/pornhub_logo.png 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4007:1c::9,0:h1_req,0:h1_req_sended,5950:response_begin,0:h1_get_head,1:h1_finish[SP:39],0:get_response,:1

Jul 24 22:02:24.828 - [INFO] GAE t:6112 s:0 GET https://ds.phncdn.com/www-static/images/maintenance/robot.png 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4009:33::a,0:h1_req,0:h1_req_sended,6110:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:36],:3 

![20180724221802](https://user-images.githubusercontent.com/19345028/43145033-0871e856-8f91-11e8-8b23-54e97eba0747.JPG)

**Comment by goldenfreemanchina** [comment]
+1 猜测是屏蔽了来自谷歌服务器的流量...那位用VPN试一下就知道了；

**Comment by pb919** [comment]
@goldenfreemanchina 我测试用X-Tunnel和小飞机打开都没问题

**Comment by tcwilliy** [comment]
用gop 的php可以打开，所有的gae都不能打开

**Comment by xieliyang** [comment]
我也有同样的问题，怎么解决？

**Comment by ymlin168** [comment]
在pornhub頁面右上的地區部份，把cn改成en
記得AdBlock要關掉，否則會變不能播放
