### ISSUE TITLE
Mac下miredo一直是黄灯，无法开启ipv6

### ISSUE THREAD

**Issue by cryschao** [XX-net/XX-Net#11194]
之前可以使用Miredo，偶尔出现黄灯，切换一下Autoclient和Client就可以解决。但是这次切换一直是黄灯。

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
GAEProxy 状态信息

连接尚未建立。
状态

属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	Fail (尝试修复)
IPv4 IP数	0
IPv6 IP数	61
XX-Net 状态	工作
IP延迟	1727
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	Fail
CA证书状态(下载)	Fail
IP扫描线程数(设置)	10
配置

属性	值
代理监听	127.0.0.1:8087
IP模式	自动
前置代理	禁用
AppID

属性	值
工作AppID	你正使用公共AppID。
系统信息

属性	值
XX-Net Version	3.12.2
Python Version	2.7.10
OpenSSL Version	16.0.0 TLSv1 h2:alpn
System Platform	x86_64, Darwin-17.6.0-x86_64-i386-64bit
OS System	Darwin
OS Version	Darwin Kernel Version 17.6.0: Tue May 8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
OS Release	17.6.0
OS Detail	Release:10.13.5; Version:('', '', '') Machine:x86_64
Language	zh_CN
Architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36 QQBrowser/4.3.4986.400

Jul 25 11:17:44.839 - [WARNING] network IPv6 fail
Jul 25 11:17:44.984 - [DEBUG] report_connect_fail IPv6 continue_fail_count:536
Jul 25 11:17:44.984 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:44.984 - [DEBUG] connect 2804:a8:c000:400::d network fail
Jul 25 11:17:45.463 - [DEBUG] report_connect_fail IPv6 continue_fail_count:537
Jul 25 11:17:45.463 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:45.464 - [DEBUG] connect 2804:d40:8c:7002::e network fail
Jul 25 11:17:45.957 - [DEBUG] report_connect_fail IPv6 continue_fail_count:538
Jul 25 11:17:45.958 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:45.958 - [DEBUG] connect 2400:d800:3:510::13 network fail
Jul 25 11:17:46.436 - [DEBUG] report_connect_fail IPv6 continue_fail_count:539
Jul 25 11:17:46.436 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:46.436 - [DEBUG] connect 2a02:ce0:1:a7::e network fail
Jul 25 11:17:46.967 - [DEBUG] report_connect_fail IPv6 continue_fail_count:540
Jul 25 11:17:46.967 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:46.967 - [DEBUG] connect 2804:214:800f:f::e network fail
Jul 25 11:17:51.813 - [DEBUG] report_connect_fail IPv6 continue_fail_count:541
Jul 25 11:17:51.814 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:51.814 - [DEBUG] connect 2001:1438:1:1::10 network fail
Jul 25 11:17:51.834 - [DEBUG] report_connect_fail IPv6 continue_fail_count:542
Jul 25 11:17:51.834 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:51.834 - [DEBUG] connect 2001:b032:101:1::11 network fail
Jul 25 11:17:53.927 - [DEBUG] report_connect_fail IPv6 continue_fail_count:543
Jul 25 11:17:53.927 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:53.928 - [DEBUG] connect 2001:b032:101:1::10 network fail
Jul 25 11:17:53.953 - [DEBUG] report_connect_fail IPv6 continue_fail_count:544
Jul 25 11:17:53.953 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:53.954 - [DEBUG] connect 2001:8002:e21:ef03::c network fail
Jul 25 11:17:54.439 - [DEBUG] report_connect_fail IPv6 continue_fail_count:545
Jul 25 11:17:54.439 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:54.439 - [DEBUG] connect 2001:4e8:0:b042::c network fail
Jul 25 11:17:55.096 - [DEBUG] report_connect_fail IPv6 continue_fail_count:546
Jul 25 11:17:55.096 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:55.096 - [DEBUG] connect 2607:f798:1e:20::f network fail
Jul 25 11:17:55.471 - [DEBUG] report_connect_fail IPv6 continue_fail_count:547
Jul 25 11:17:55.471 - [DEBUG] report_connect_fail network fail
Jul 25 11:17:55.471 - [DEBUG] connect 2607:fb90:8f0:20::f network fail
Jul 25 11:17:55.827 - [WARNING] network IPv6 fail

感谢~

**Comment by sophiesugar** [comment]
me to

**Comment by SeaHOH** [comment]
1. 重新拨号试试
1. 换一个服务器
1. 继续等待。。。
