### ISSUE TITLE
"仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by Dexilc** [XX-net/XX-Net#11191]
1.版本为最新版
![1](https://user-images.githubusercontent.com/24988478/43150422-7857876a-8f9c-11e8-9f6b-00e468da9fa9.png)
2.路由器开启Upnp
![2](https://user-images.githubusercontent.com/24988478/43150552-c5e2e2f4-8f9c-11e8-8a63-2755bded4e51.png)
3.运营商
你的运营商（ISP）是 TOPWAY-NET ShenZhen Topway Video Communication Co. Ltd，深圳天威宽带，据说很垃圾
试过各种命令，还是没成功，前几天还好好的
4.诊断日志
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:41
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 763
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
当显示 IPv6 fail 时，访问 http://test-ipv6.com/ 查看。

**Comment by Dexilc** [comment]
已经访问过，运营商信息就是从那复制过来的
![4](https://user-images.githubusercontent.com/24988478/43153743-b802dd80-8fa4-11e8-9a00-15e08a8642c8.png)

![3](https://user-images.githubusercontent.com/24988478/43153727-ae590f16-8fa4-11e8-9357-673f948afad4.png)

**Comment by SeaHOH** [comment]
这不很正常嘛，就是隧道断开了。
你可以在`IPv6 隧道`页面点击`测试`按钮，如果能通过，切换下服务器就好了，否则只能等待。

**Comment by sophiesugar** [comment]
me to 
天威宽带

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）可识别 Teredo 隧道是否正常

**Comment by SeaHOH** [comment]
> 会不会跟运营商有关系，换别的运营商就是正常的

不排除这种可能，不过可以尝试下重新拨号。

**Comment by Dexilc** [comment]
@sophiesugar 你的IPv6能正常使用吗

**Comment by MatchaZcc** [comment]
问个问题，3.12.10 有个IPV6隧道，是不是直接在这里就可以用了。
我用的是很早的版本，那时是自己手动配置的。

**Comment by SeaHOH** [comment]
@MatchaZcc 反正都是中文，你看着点吧，现在可以保证点不坏。

**Comment by Dexilc** [comment]
用SSR了,版本更新后再试试

**Comment by daxinnan** [comment]
我最近也碰到了这个问题，请问该怎么尝试解决呢
```
XX-Net Status:

sys-platform: x86_64, Linux-4.18.0-13-generic-x86_64-with-Ubuntu-18.10-cosmic
os-system: Linux
os-version: #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018
os-release: 4.18.0-13-generic
os-detail: Dist:Ubuntu; Version:18.10; ID:cosmic
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/72.0.3626.119 Chrome/72.0.3626.119 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.15+
openssl-version: 18.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 21
ip-quality: 265
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
