### ISSUE TITLE
youtube只能正常打开一页，再多开就不显示页面，switch提示googlevideo无法加载

### ISSUE THREAD

**Issue by wantno** [XX-net/XX-Net#11193]
youtube首页可以正常进去，只要打开两页以上视频的时候只能播放视频，页面的其他区域都是灰色块。这时候switch显示googlevideo.com无法加载。
可是如果只打开一个视频，就可以正常加载，评论什么的也都能看了。
你们有这样的情况吗？
怎么解决啊？

**Comment by AnyWAT** [comment]
貌似与软件进一步限制了“连接池”相关？

**Comment by SeaHOH** [comment]
把 config.json（记得删除 ID）、状态统计和同时打开多个页面的日志都发过来。

**Comment by wantno** [comment]
config.json文件
{
  "connect_receive_buffer": 2097152, 
  "GAE_APPIDS": [

  ]
}

**Comment by wantno** [comment]
我去。。。。好使了，不那样了。上午时候是我提问那样的问题。
现在再打开又没问题了。。。。。。

**Comment by SeaHOH** [comment]
可能哪里没处理好，以后遇到了记得第一时间保存日志和状态数据。
谢谢你的反馈。
