### ISSUE TITLE
XX-Net 3.12.10，一切正常，你可以访问真正的互联网了。但无法访问谷歌网站

### ISSUE THREAD

**Issue by NeoWang2017** [XX-net/XX-Net#11201]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:25
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:12 h2:0
scan-ip-thread-num: 10
ip-quality: 1013
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

![image](https://user-images.githubusercontent.com/25607993/43191971-e9c693b8-902e-11e8-85b7-e70281b849f6.png)

**Comment by AnyWAT** [comment]
臭大街 #10919

**Comment by SeaHOH** [comment]
谷歌搜索能用吗？看你这个似乎隧道质量不太好，可尝试增大扫描线程数量。
