### ISSUE TITLE
点击  IPv6 隧道   下面的  启用  会在 安装目录 的根目录生成一个 Program，重启电脑，开机会莫名其妙的 提示要打开这个文件， 打开 XXNET  显示 IPv6 Fail 

### ISSUE THREAD

**Issue by kylewuwu** [XX-net/XX-Net#11202]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

点击  IPv6 隧道   下面的  启用  会在 安装目录 跟目录生成一个 Program，重启电脑，开机会莫名其妙的 提示要打开这个文件， 打开 XXNET  显示 IPv6 Fail 

[Program.TXT](https://github.com/XX-net/XX-Net/files/2227771/Program.TXT)

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
看到了，谢谢你的反馈。
当初微软设计 cmd 命令语法的人简直有病。

**Comment by SeaHOH** [comment]
暂时不会发新版，你可以手动更新这个文件，或者移动 XX-Net 至不包含空格的路径。
