### ISSUE TITLE
win下提示appid流量用完，mac下正常

### ISSUE THREAD

**Issue by billowqiu** [XX-net/XX-Net#11207]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

最近突然出现以下提示：

”工作 AppID | 您的 AppID 流量已用完，请部署更多 AppID。”

按照实际使用情况来说，不太可能，因为我部署了两个appid，平时也就需要翻墙的时候用一下。

**Comment by SeaHOH** [comment]
同一时间，两种不同的状态？
建议你先登录后台查看配额，你不是有俩 ID 嘛，说不定就是其中一个用完了。

**Comment by billowqiu** [comment]
这周开始就好了。。。
