### ISSUE TITLE
本地电脑用xxnet搭建的GAE proxy怎么给局域网的其他电脑用

### ISSUE THREAD

**Issue by kennywgx** [XX-net/XX-Net#11209]
场景：局域网内有电脑A和电脑B和手机C，A部署了XX-net，并且可以翻墙，请问怎么实现让B和C设置A的内网ip代理之后也可以翻墙，求大神！

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/wiki/AllowRemoteConnectToWebControl

**Comment by kennywgx** [comment]
@AnyWAT 搞定了，谢谢
