### ISSUE TITLE
为什么打不开网页？

### ISSUE THREAD

**Issue by Evanwenguang** [XX-net/XX-Net#11208]
![image](https://user-images.githubusercontent.com/41722908/43246038-fdf3f4ac-90e2-11e8-8afd-727405d02e80.png)
![image](https://user-images.githubusercontent.com/41722908/43246083-19aed4e6-90e3-11e8-9e8f-43368719f937.png)

**Comment by AnyWAT** [comment]
或许X-Tunnel 还未正常（并不是启动XX-Net 后即刻可正常，也许永远不正常）
IPv6正常，GAE正常
GAE正常，X-Tunnel 正常
参考 #10919 臭大街法则
