### ISSUE TITLE
有一年没有用了，最近回归，好奇什么时候又好了啊。谢谢大佬

### ISSUE THREAD

**Issue by Snowzyk** [XX-net/XX-Net#11203]
小弟我也算老用户了，一年前好像是19da的原因xxnet挂掉了，然后我无奈转投VULTR, 最近这个vps也不灵光，我回来看了下，居然xxnet又好了，不过好像不像之前那么稳定，不过依然非常感谢作者以及修复问题的大佬，希望xxnet继续发扬光大! 
我看到和IPV6有关系？那我没开也可以的啊，是开了更好吗，什么意思呢？望解答谢谢。
另外问下有用vultr的朋友你们的还好用吗，好像这一周都非常慢，我用的纽约的服务器，啥原因啊

**Comment by 2378** [comment]
xnet 一直都沒掛 掛的是"环境“
vultr 是真挂了 日本新加坡ip被封（某些地区） 欧洲西海岸的速度也不行

**Comment by Snowzyk** [comment]
谢谢大佬答复 
环境 不太懂哈 anyway能用就好
vultr真的是 才充的钱哎 不过我发现用移动手机流量走没事  电信的宽带就被ban
