### ISSUE TITLE
无法下载稳定版3.12.10

### ISSUE THREAD

**Issue by answer1** [XX-net/XX-Net#11206]
各位大神，最近发现GAE用不了，我的是3.6.15版本，今天想更新到最新版3.12.10，结果一直显示Download Fail，这个应该不需要翻墙就能更新了吧。请问有什么解决办法么？
诊断信息：XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
xxnet-version: 3.6.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12345 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 1
block-stat: Connect Blocked, 2 seconds to wait.
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

<img width="460" alt="1" src="https://user-images.githubusercontent.com/32611849/43242373-4be57c0e-90d3-11e8-99c7-6ad153ee91fb.png">

<img width="654" alt="2" src="https://user-images.githubusercontent.com/32611849/43242368-3fb5760a-90d3-11e8-8610-d23653080c93.png">
还有一部分日志也贴出来：
Jul 26 12:47:54.078 - [DEBUG] report_connect_fail:2607:f8b0:4002:12::15

Jul 26 12:47:56.249 - [DEBUG] 2404:6800:400b:11::11 fail:timeout('timed out',)

Jul 26 12:47:56.249 - [DEBUG] report_connect_fail:2404:6800:400b:11::11

Jul 26 12:47:58.081 - [DEBUG] 2404:6800:400a:9::c fail:timeout('timed out',)

Jul 26 12:47:58.081 - [DEBUG] report_connect_fail:2404:6800:400a:9::c

Jul 26 12:47:58.721 - [DEBUG] ip:2607:f8b0:400a:c::19 real fail

Jul 26 12:48:00.261 - [DEBUG] 2607:f8b0:4016:15::d fail:timeout('timed out',)

Jul 26 12:48:00.261 - [DEBUG] report_connect_fail:2607:f8b0:4016:15::d

Jul 26 12:48:02.083 - [DEBUG] 2a00:1450:400d:d::14 fail:timeout('timed out',)

Jul 26 12:48:02.083 - [DEBUG] report_connect_fail:2a00:1450:400d:d::14

Jul 26 12:48:03.721 - [DEBUG] ip:2607:f8b0:4016:8::17 real fail

Jul 26 12:48:04.264 - [DEBUG] 2404:6800:400f:9::b fail:timeout('timed out',)

Jul 26 12:48:04.264 - [DEBUG] report_connect_fail:2404:6800:400f:9::b

Jul 26 12:48:04.317 - [DEBUG] sort ip time:51ms

Jul 26 12:48:06.085 - [DEBUG] 2607:f8b0:4002:5::c fail:timeout('timed out',)

Jul 26 12:48:06.085 - [DEBUG] report_connect_fail:2607:f8b0:4002:5::c

Jul 26 12:48:06.907 - [DEBUG] connect 2607:f8b0:4009:2d::8 fail:[('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')] cost:822 h:0

Jul 26 12:48:06.907 - [DEBUG] report_connect_fail:2607:f8b0:4009:2d::8

Jul 26 12:48:08.322 - [DEBUG] 2607:f8b0:4016:7::19 fail:timeout('timed out',)

Jul 26 12:48:08.322 - [DEBUG] report_connect_fail:2607:f8b0:4016:7::19

Jul 26 12:48:08.723 - [DEBUG] ip:2607:f8b0:4002:32::9 real fail

**Comment by AnyWAT** [comment]
人工下载（貌似需代理）、解压。。。
xxnet-version: 3.6.15
公告。。。#11183

**Comment by SeaHOH** [comment]
添加了一个 7z 包，支持续传，以后稳定版都会加上。

**Comment by answer1** [comment]
谢谢。我目前解压了XX-Net-3.12.10.zip，另外一个XX-Net-3.12.10.tar.gz没动。请问两个压缩包有什么区别呢？需要都解压么？ @SeaHOH （不会引用回复，只能@你了）

**Comment by AnyWAT** [comment]
貌似同一内容的不同压缩格式（文件）而已，需要都解压么？

**Comment by SeaHOH** [comment]
内容都一样，7z 那个支持续传，仅此而已。

**Comment by answer1** [comment]
好的。新版本还是挺简单的，就是IP数固定在100，好像没以前多。另外老版本的文件删掉没影响吧？

**Comment by SeaHOH** [comment]
点发布标签自行查看，老版本你随意。
