### ISSUE TITLE
Ipv6不定期Fail，禁用本地连接Ipv6协议不起作用

### ISSUE THREAD

**Issue by futureprecd** [XX-net/XX-Net#11204]
这两个月以来时不时出现Ipv6状态Fail，这两天尤为频繁，将客户端和SwitchyOmega都卸载了重装，客户端更到最新，所有的都配置好了，然而还是Fail，禁用本地连接Ipv6协议也没用。
此外，每次打开chrome，SwitchyOmega都必须手动切换为Gae-Proxy自动切换，否则国内网都上不了。卸载SwitchyOmega之前就存在此问题，卸载重装之后还是有问题。

**Comment by AnyWAT** [comment]
时不时出现Ipv6状态Fail——参考 #10919 臭大街法则
（从XX-Net目录下导入）SwitchyOmega（的设置）貌似从3.9.6开始默认被设定 Smart-Router，如图修改。。。
![default](https://user-images.githubusercontent.com/37962734/43212747-6daee418-9067-11e8-8dcc-e826073532fb.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43212928-dd111ee8-9067-11e8-8cc9-9a0afeb95bdb.png)

**Comment by futureprecd** [comment]
@AnyWAT emmm不管打不打开这个模块，只要SwitchyOmega的模式不是Gae-Proxy自动切换，国内网都连不上去。。。所以每次打开chrome之后都得手动调整，臭大街法则我明天试试吧。 Thx ~

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43214368-98ebf0f4-906b-11e8-813f-56bd6b501d0e.png)
