### ISSUE TITLE
求大神支招

### ISSUE THREAD

**Issue by TomeTiger** [XX-net/XX-Net#11219]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
首次使用？贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）

**Comment by TomeTiger** [comment]
![0 b1bidv3n ailtf9da h5j](https://user-images.githubusercontent.com/26940255/43308964-ebb397c4-91b5-11e8-983e-f438b4b399c9.png)
并非首次使用，升级到3.12后就不能用了，谢谢大神 @AnyWAT

**Comment by AnyWAT** [comment]
IPv6组策略宜退回到默认设置（全部未设置），程序内或命令行可快速更换服务器。（现在是非完全的组策略2参数，完全是前5行的5参数）
is-idle: 1
Appid_Working: false ——未工作，再开一个XX-Net（挤出貌似已不正常的），稍侯，如不行
关闭浏览器、退出XX-Net，禁用再启用网络。。。
参考 #10919 臭大街法则

**Comment by AnyWAT** [comment]
正常后 https://github.com/XX-net/XX-Net/issues/11183 没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）

**Comment by TomeTiger** [comment]
这样操作了，但是咩结果啊大神
还是显示：
Teredo 隧道 | 离线（无法连接）
-- | --

**Comment by AnyWAT** [comment]
贴 netsh int ipv6 show teredo 运行结果（无需IP地址的2行）

**Comment by SeaHOH** [comment]
> Teredo 隧道 | 离线（无法连接）

这就是现在最后的结果了

然后，你可以试试重新拨号。

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo
顺道检验是否取消了组策略
