### ISSUE TITLE
SMART ROUTER模块如何配置hosts文件内的内容

### ISSUE THREAD

**Issue by duqingjiao** [XX-net/XX-Net#11218]
很多破解软件，是把 授权网站在 hosts内指定为127.0.0.1
，使用SMART ROUTER模块的智能代理后，软件破解失效了。麻烦大家说一下都是怎么配置的，谢谢

**Comment by SeaHOH** [comment]
没仔细看过这部分，不太清楚。
不过你可以放入 smart_router\local\gfw_white_list.txt 试试看。
