### ISSUE TITLE
"仅 IPv6" 不可用，请检查

### ISSUE THREAD

**Issue by guo333323** [XX-net/XX-Net#11212]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:55 ipv4:0 ipv6:54
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 506
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
Appid_Working: false ——报错：（某？）Appid 没工作
再开一个XX-Net（挤出貌似已不正常的），稍侯，不行
关闭浏览器、退出XX-Net ，禁用再启用网络
参考 #10919 臭大街法则

**Comment by retmania** [comment]
我也是啊，我就什么都不管，一会儿可能就正常了，一直时好时坏

**Comment by AnyWAT** [comment]
一直好一直好一直好
