### ISSUE TITLE
一切正常，但就是打不开翻墙网页

### ISSUE THREAD

**Issue by luogx10517** [XX-net/XX-Net#11216]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:80
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:51 h2:0
scan-ip-thread-num: 1
ip-quality: 427
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: true
Appids_Not_Exist: true
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
Appid_Working: false ——报错：（某？）Appid 没工作
Appids_Out_Of_Quota: true ——报错：（某？）Appid 没流量了
Appids_Not_Exist: true ——报错：（某？）Appid 不存在
Using_Public_Appid: true ——在使用公共Appid

**Comment by AnyWAT** [comment]
一切正常，但就是打不开翻墙网页——参考 #10919 臭大街法则

**Comment by SeaHOH** [comment]
@luogx10517 状况是否有变化？
如果还是这样，麻烦贴出日志，还有代理设置。

**Comment by luogx10517** [comment]
@ SeaHOH：我用QQ电脑管家的修复网络功能，查出DNS被修改，我改成系统默认，不设置数值，重启XX-net，又恢复正常了。谢谢关注。

**Comment by luogx10517** [comment]
DNS被修改成8.8.8.8

**Comment by AnyWAT** [comment]
貌似DNS被修改成8.8.8.8也不一定会死吧？
