### ISSUE TITLE
YouTube变成空白界面

### ISSUE THREAD

**Issue by zhanghua000** [XX-net/XX-Net#11229]
今天闲来无事清除了chrome的缓存，结果YouTube变成空白的了。诡异的是在清除数据之前是正常的。附图。
![image](https://user-images.githubusercontent.com/17194552/43364876-dcf53f7a-9355-11e8-850b-0fd36f9f63cc.png)

**Comment by snipertulip** [comment]
@zhanghua000 我的谷歌相册也是的，Smarter-Router模式

**Comment by zhanghua000** [comment]
更诡异的是如果直接输视频地址，播放是正常的

**Comment by AnyWAT** [comment]
参考下 #10919 臭大街法则，或许就不会了？

**Comment by zhanghua000** [comment]
谢谢@AnyWAT 的方法，现在已经恢复正常。
