### ISSUE TITLE
Miredo一直是黄灯

### ISSUE THREAD

**Issue by 102464** [XX-net/XX-Net#11228]
设置里miredo是黄灯，终端里输入sudo miredo显示：
Error: cannot open device file /dev/tun0 (Resource busy)
IPv6 tunneling will not work.

**Comment by 2378** [comment]
ifconfig teredo 呢  最好说下发行版

**Comment by 102464** [comment]
我的是mac os x 10.13系统

**Comment by dutudvd** [comment]
> 设置里miredo是黄灯，终端里输入sudo miredo显示：
> Error: cannot open device file /dev/tun0 (Resource busy)
> IPv6 tunneling will not work.

try to restart
