### ISSUE TITLE
Youtube 首页是空白的，什么原因？

### ISSUE THREAD

**Issue by MitchellClark666** [XX-net/XX-Net#11225]
Youtube 首页是空白的，什么原因？

![default](https://user-images.githubusercontent.com/13077075/43352073-53786b92-9250-11e8-9842-2e73c94d5c07.PNG)

**Comment by 2378** [comment]
猜测墙有动作，电信ipv6骨干网已经完成，相应的“技术”应该也完成了

**Comment by dahai058** [comment]
最喜欢看文昭谈古论今，这两天油管界面确有不稳，有时打开首页都是英文视频。

**Comment by AnyWAT** [comment]
貌似至今未遇到Youtube 首页是空白的，或许是因为遵循了 #10919 臭大街法则？

**Comment by yongqingxie** [comment]
我这里是看了2部视频后 IPV6直接断开链接了.....fuck

**Comment by goldenfreemanchina** [comment]
@AnyWAT   呵呵...来自stone记的问候...试试周周侃和书斋夜话
