### ISSUE TITLE
Chrome请检查浏览器代理设置

### ISSUE THREAD

**Issue by Qun384232347** [XX-net/XX-Net#11226]
本来好好的。 突然就提示请检查浏览器代理设置，，，
其他浏览器都是好的。 只有Chrome不正常。 
证书也从新下了。 还是没用啊。

**Comment by HelloMaster1954** [comment]
chrome的代理插件可否截图看一下？

**Comment by Qun384232347** [comment]
我就没用代理插件啊. 平时就是手选全局或者智能. 就直接翻了

**Comment by AnyWAT** [comment]
FireFox 没有、Chrome 偶有“未加载资源”127.0.0.1走“直接连接”的无理要求。
无论何种代理情景模式，“未加载资源” *.deja.com 走GAE才证书正常。
以上，用代理扩展才看得见😜
