### ISSUE TITLE
mac上为什么使用了xx-net，shadowsocks还有V2RayX就是用不了了？

### ISSUE THREAD

**Issue by Apathy94** [XX-net/XX-Net#11224]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by Apathy94** [comment]
而且使用XX-net，显示是已经连接，但是我登录谷歌的时候登陆不了
600:gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/

**Comment by SeaHOH** [comment]
shadowsocks 也不行？

**Comment by meilianwei** [comment]
我遇到过类似的问题，我的解决办法是：切换到全局模式关掉SwitchyOmega，在登陆youtube成功。

**Comment by Apathy94** [comment]
@SeaHOH  下午试了一下shadowsocks是可以的！但是V2RayX还是不行！

**Comment by Apathy94** [comment]
@meilianwei 遇到gae_exception:602问题是这么解决的就可以了？

**Comment by SeaHOH** [comment]
V2RayX 要看你用的是哪种代理。
可能就是单纯缺 IP，或 IP 质量不行。
你的 XX-Net 版本是多少？

**Comment by SeaHOH** [comment]
状态也贴一下

**Comment by Apathy94** [comment]
@SeaHOH 我用的是3.12.10
这是使用GAEproxy的状态
XX-Net Status:

sys-platform: x86_64, Darwin-17.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
os-release: 17.7.0
os-detail: Release:10.13.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.15
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:36
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 10
ip-quality: 787
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Apathy94** [comment]
@meilianwei 试了一下你的方法，还是不行

**Comment by SeaHOH** [comment]
看起来应该能用，尝试增大扫描线程。

**Comment by SeaHOH** [comment]
由于个别 ISP 干扰太大，程序自动判断连接联通性可能延迟 5 分钟以上，甚至无法判断。
一般看有效 IP 数，70 以上应该比较正常。
还有，如果正在使用代理，但是连接池始终没有增加，且数值很小，多半就是 IPv6 连接断开了。

**Comment by Apathy94** [comment]
@SeaHOH 增大了扫描线程，还是出现了错误“600:gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/”

**Comment by Apathy94** [comment]
@SeaHOH 明白了！XX-net貌似好了，我把我同学给我的AppID删了，使用默认的AppID，就可以了。难道说是因为我同学给我的AppID 过期了？

**Comment by yutianzeabc** [comment]
@Apathy94  也许服务端版本没更新？

**Comment by Apathy94** [comment]
@yutianzeabc OK
