### ISSUE TITLE
如何自动将新版本变成default并且删除旧版本

### ISSUE THREAD

**Issue by wuyu112233** [XX-net/XX-Net#11237]
每次更新，都会变成多个版本
已尝试，在只有一个版本时，将保留旧版本数设置为0，再点击更新，无效
下方切换版本区域仍然是3.12.2(default)+3.12.10
如果点击删除3.12.2，就会弹出删除失败
此时重启xxnet，变成只有3.12.10，并且可能出现无法正常使用的现象
code目录下default文件夹消失

难道只能手动下载新版本，每次都重新设置吗？
或者说，有办法备份设置，这样我可以放心手动重新下载

**Comment by SeaHOH** [comment]
没这个功能，你需要手动更改文件夹名称和 version.txt 内容。

**Comment by AnyWAT** [comment]
手动下载新版本，需要重新设置吗？解压前退出XX-Net、删掉除 data 外的其它目录，code目录下永远是 default 😜
