### ISSUE TITLE
需要屏蔽一些关键词和网页请求（技术类问题）

### ISSUE THREAD

**Issue by waitfor2long** [XX-net/XX-Net#11236]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

用的最新版的
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

是的
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

无
* 如果问题得到解决，请务必回复相关情况，谢谢。

现在用的是最新的版本，很好用，最近想要屏蔽一些关键词和网页，但是我在gae_handler.py里怎么都打印不出response, 请问返回的请求是在哪里获取？

**Comment by SeaHOH** [comment]
想做内容过滤？不建议在 XX-Net 内部处理。
1. 编码问题
2. 流式返回
3. 内容长度，或者说是内容结束判断

处理这些问题需要相当多的修改。
其实可以采用浏览器扩展的形式，此时已经是解码状态，也不存在长度问题。

**Comment by waitfor2long** [comment]
好的，谢谢，不太懂这个，所以问一下可能 性，既然不容易就算了，谢谢
