### ISSUE TITLE
cetnos7安装xxnet给局域网做代理无法使用

### ISSUE THREAD

**Issue by leiyu1139** [XX-net/XX-Net#11235]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
已经更新到最新版本

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
查了

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
这个是诊断信息：
XX-Net Status:

sys-platform: x86_64, Linux-3.10.0-862.9.1.el7.x86_64-x86_64-with-centos-7.5.1804-Core
os-system: Linux
os-version: #1 SMP Mon Jul 16 16:29:36 UTC 2018
os-release: 3.10.0-862.9.1.el7.x86_64
os-detail: Dist:CentOS Linux; Version:7.5.1804; ID:Core
architecture: 64bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.5
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:77
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 510
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

环境：同一局域网里，centos7（装有XXNET的一台服务器A），客户端电脑B。
客户端电脑B的SwitchyOmega配置：
![image](https://user-images.githubusercontent.com/19724032/43372781-161cf3e8-93d7-11e8-9c1b-a80939a974c5.png)
调试过程发现电脑B使用智能路由模式，无法访问谷歌。而且Smart Router 日志一直没变化：
![image](https://user-images.githubusercontent.com/19724032/43372788-4ad95da6-93d7-11e8-829e-57723a662ca1.png)
同样的，使用 GAE-Proxy-Linux自动切换也一样不能用。
![image](https://user-images.githubusercontent.com/19724032/43372808-8b75613e-93d7-11e8-93e6-81ab20c1c550.png)
xxnet的一些配置如下：
![image](https://user-images.githubusercontent.com/19724032/43372831-b9783d4a-93d7-11e8-9e90-af4710c24425.png)
GAEPROXY状态：
![image](https://user-images.githubusercontent.com/19724032/43372841-d5074394-93d7-11e8-8175-476afc7867d0.png)
证书已经下载安装，但是还是提示fail。另外服务器A的端口已经开放。
![image](https://user-images.githubusercontent.com/19724032/43372904-6f540cde-93d8-11e8-8467-d31cc7907d4a.png)

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by leiyu1139** [comment]
8086udp tcp也有开放

**Comment by AnyWAT** [comment]
能将服务器A当作一般电脑看待么？如是，继续
scan-ip-thread-num: 1——明显不好！参考：几乎分分钟一直好的 #10919 臭大街法则
proxy_state: Fail
ca_state: Fail——貌似 Smart Router 并不理想，建议添加情景模式 http://x.x.x.x:8086/proxy.pac 或用 GAE-Proxy 自动切换，添加“未加载资源” *.deja.com 走GAE-Proxy

**Comment by leiyu1139** [comment]
已经根据您的提示修改了IP扫描xianc线程，关闭了自动调整扫描线程数，现在如下图。
![image](https://user-images.githubusercontent.com/19724032/43379351-8dd6c3ba-93fe-11e8-932a-830b2436f0f0.png)
情景模式我已经有添加了一个，根据AE-Proxy 自动切换修改了一份AE-Proxy-Linux 自动切换模式，但是在此模式下还是无法实现代理。

**Comment by leiyu1139** [comment]
GAE-Proxy的端口不是8087么

**Comment by 821938089** [comment]
1、centos7是装的服务器版吗？没有桌面吧
2、检查下SwitchyOmega的代理服务器ip有没有搞错（用这个ip 连服务器的ssh）
3、你是怎么打开XX-Net后台的？后台地址是？
4、尝试使用直接的ip代理，不用Smart Router是否正常？
5、使用电脑B访问Smart Router 的代理IP，浏览器的反映是？（或使用tcping是否有响应）
6、ping服务器A的ip是否有响应？

**Comment by leiyu1139** [comment]
1是服务器版，无桌面。
2、ip核对过，是192.168.29.2，并且也是使用这个ip连服务器的ssh。
3、同样192.168.29.2：8085
4、有尝试过GAE自动切换，不行、设置如下
![image](https://user-images.githubusercontent.com/19724032/43379798-d3b5af98-9400-11e8-9311-f5dbe8b03682.png)
5、服务器A上有自建的几个服务，如FTP、samba、dns服务、nginx+MySQL+Apache+tomcat。。。等服务均正常。
6、ping服务器a肯定有响应。

**Comment by AnyWAT** [comment]
楼上截图不是 GAE自动切换 而是 GAE （全局代理）

**Comment by leiyu1139** [comment]
GAE自动切换
![image](https://user-images.githubusercontent.com/19724032/43380059-120c10c4-9402-11e8-9c01-f179f4a4e93d.png)
![image](https://user-images.githubusercontent.com/19724032/43380071-1fefbb1e-9402-11e8-9685-933b8f9bca80.png)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43380240-fbb3f750-9402-11e8-97ac-a47bb5e468e1.png)
改本地127.0.0.1为某个网络IP的 GAE（全局代理：全部8087）而已，黄色区域还合适么？
![default](https://user-images.githubusercontent.com/37962734/43380349-6c185504-9403-11e8-8db5-ddbc1b87413b.png)
GAE自动切换是2项：要么直连，要么8087

**Comment by AnyWAT** [comment]
强烈建议添加情景模式 http://192.168.29.2:8086/proxy.pac

**Comment by leiyu1139** [comment]
建议添加情景模式 http://192.168.29.2:8086/proxy.pac
这个是怎么添加？

**Comment by leiyu1139** [comment]
![image](https://user-images.githubusercontent.com/19724032/43380916-764b737e-9405-11e8-983f-1260e2761c95.png)
改成这样？

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43381003-bbb4d496-9405-11e8-9a2f-fedefa63301c.png)

**Comment by AnyWAT** [comment]
客户端电脑B：采用GAEPROXY需要先导入证书 https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1

**Comment by 821938089** [comment]
使用电脑B浏览器访问192.168.29.2:8086，然后看Smart Router的日志有反应吗？

**Comment by 821938089** [comment]
电脑B的ip地址是多少？

**Comment by leiyu1139** [comment]
已经修改了这个设置。

![image](https://user-images.githubusercontent.com/19724032/43381944-daf7ed68-9408-11e8-80ca-4d2526d67448.png)

**Comment by leiyu1139** [comment]
使用电脑B浏览器访问192.168.29.2:8086，然后看Smart Router的日志有反应吗？
这个有反应。

**Comment by leiyu1139** [comment]
还有个条件也说一下，我现在的电脑是在外网通过服务器A搭建的vpn 来访问，vpn已连接，并且能够正常访问29.2（服务器A）上的所有资源、服务。

**Comment by leiyu1139** [comment]
会不会和vpn有关？

**Comment by leiyu1139** [comment]
使用情景模式 http://192.168.29.2:8086/proxy.pac   规则更新成功，但是依然无法访问谷歌。

**Comment by 821938089** [comment]
1.点击SwitchyOmega应用图标，弹出应用的代理选择后浏览器全屏截图
2.截图浏览器应用列表
3.用浏览器打开谷歌后浏览器截图
4.你用的什么浏览器？

**Comment by leiyu1139** [comment]
![image](https://user-images.githubusercontent.com/19724032/43382323-1052a880-940a-11e8-96a4-9ae5d363ee4c.png)

使用情景模式 http://192.168.29.2:8086/proxy.pac 规则更新成功，但是依然无法访问谷歌，且SMART ROUTER日志有变化。。

**Comment by 821938089** [comment]
试下不用SwitchyOmega，直接用系统的代理

**Comment by AnyWAT** [comment]
在外网通过服务器A搭建的vpn 来访问，vpn已连接，并且能够正常访问29.2（服务器A）上的所有资源、服务—— http://127.0.0.1:8085/?module=launcher&menu=config （前置）代理？

**Comment by leiyu1139** [comment]
使用http://192.168.29.2:8086/proxy.pacf访问谷歌时，Smart Router 日志有这一段：
![image](https://user-images.githubusercontent.com/19724032/43392641-e33ea43a-9426-11e8-9dd9-996879de00fa.png)

**Comment by leiyu1139** [comment]
（前置）代理我翻阅了wiki issue，大家都说不用配置，开启个远程就行。

**Comment by leiyu1139** [comment]
使用http://192.168.29.2:8086/proxy.pacf访问谷歌时，Smart Router 日志有这一段：
说明这个链接应该是通的，端口应该也是对的，但是不知道什么原因导致无法访问谷歌。浏览器是谷歌
![image](https://user-images.githubusercontent.com/19724032/43392770-43bf5e3a-9427-11e8-8443-ec30783b7402.png)
![image](https://user-images.githubusercontent.com/19724032/43392795-5886955e-9427-11e8-84a6-fc3a28568451.png)
![image](https://user-images.githubusercontent.com/19724032/43392829-70621d06-9427-11e8-89ae-91af3560c478.png)

**Comment by AnyWAT** [comment]
爬楼细看有关“公告”：服务端没重新部署到3.3.5（以前3.3.2？）貌似只能用老版本！

**Comment by leiyu1139** [comment]
或许与此有关？#11183 没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
PS：给局域网做代理，用没（进一步）限制了垃圾池的老版本（😜推荐3.10.4😜按前述公告内修改2文件）会更好？
老版本也有试过，这个环境从年初就开始搞了，但是一直没搞成，版本也一直更新，估计和版本没大关系吧？、、

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43393360-59f1781c-9429-11e8-9eb6-75acbffd1613.png)
V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）😜更新后是3.3.5😱

**Comment by AnyWAT** [comment]
老版本也有试过，这个环境从年初就开始搞了——😜推荐3.10.4😜按前述公告内修改2文件）会更好？😜这是6月初发生的事😭

**Comment by AnyWAT** [comment]
如果你的ID服务端不是3.3.5，用XX-Net 3.12.10，即使没其他任何问题，貌似也应不正常！😂

**Comment by AnyWAT** [comment]
老版本也有试过，这个环境从年初就开始搞了——（前置）代理的锅？

**Comment by 821938089** [comment]
试下用公网ip直接连服务器，不绕vpn，在代理输入服务器公网ip和端口。

**Comment by AnyWAT** [comment]
代理、证书的2Fail，浏览器扩展也会影响，如
![default](https://user-images.githubusercontent.com/37962734/43395237-f3f7cafa-942f-11e8-93a5-e744b74f0776.png)
在默认的Whitelist Site 时就Fail，但Blacklist Site 时就OK

**Comment by leiyu1139** [comment]
首先感谢楼上两位的热心回答！
其次：
我访问appspot.com访问不成功。通过本机搭建的xxnet也一样访问不成功。不知道是不是我的操作问题。
另外：
1、老版本也有试过，这个环境从年初就开始搞了，但是一直没搞成——😜推荐3.10.4😜按 #11183 公告内修改2文件）会更好？😜这是6月初才发生的事😭
答：这个公告刚刚看了下，感觉应该不是这个问题 吧？？？！！！
2、试下用公网ip直接连服务器，不绕vpn，在代理输入服务器公网ip和端口。
答：这个也有试过，通过个人注册的域名指向、公网IP等方式直接访问，均无法解决。已确认ip和端口正确。
3、代理、证书的2Fail，浏览器扩展也会影响，如
default
在默认值的Whitelist Site 时就Fail，但Blacklist Site 时就OK（x.x.x.x:8085）
答：这个如果是插件影响的话，那么本机搭建的xxnet则应该也是不正常。
但是现实是，本机搭建的正常，通过服务器A上的xxnet则不行。

**Comment by leiyu1139** [comment]
另外：刚刚在局域网里通过笔记本C一样通过服务器A的xxnet代理，依然无法访问谷歌。。。。

**Comment by leiyu1139** [comment]
centos的防火墙开启了nat有影响么，就是VPN服务器的转发。

**Comment by 821938089** [comment]
试下用系统的代理，不用浏览器拓展。
用的时候用公网ip并且关掉vpn。
方不方便发下服务器ip，不方便就算了。

**Comment by AnyWAT** [comment]
访问appspot.com访问不成功——用浏览器通过（正常的？）😜GAE_Proxy😜代理访问 myid.appspot.com

**Comment by AnyWAT** [comment]
貌似校园网需要（前置）代理。。。

**Comment by leiyu1139** [comment]
把原来的文件删除了，重新下载了源代码，并解压，发现好像有问题，大家帮忙分析下，具体如下：
[root@***** XX_Net]# ./start
XX-Net version:3.12.10
Jul 30 22:43:01.972 [launcher][INFO] Using PyGTK as the GUI Backend.
Jul 30 22:43:02.012 [launcher][WARNING] import pynotify fail, please install pyt                                                                                                                                                          hon-notify if possible.
Jul 30 22:43:02.062 [launcher][INFO] Gtk.StatusIcon used.
Jul 30 22:43:02.076 [launcher][INFO] use build-in openssl lib
Jul 30 22:43:02.076 [launcher][INFO] start XX-Net 3.12.10
Jul 30 22:43:02.076 [launcher][DEBUG] start confirm_xxnet_exit
Jul 30 22:43:02.077 [launcher][DEBUG] good, xxnet:8085 clear!
Jul 30 22:43:02.077 [launcher][DEBUG] finished confirm_xxnet_exit
Jul 30 22:43:02.141 [gae_proxy][INFO] ------------------------------------------                                                                                                                                                          ------------
Jul 30 22:43:02.141 [gae_proxy][INFO] Python Version     : 2.7.5
Jul 30 22:43:02.141 [gae_proxy][INFO] OS                 : Dist:CentOS Linux; Ve                                                                                                                                                          rsion:7.5.1804; ID:Core
Jul 30 22:43:02.141 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
Jul 30 22:43:02.141 [gae_proxy][INFO] Using public APPID
Jul 30 22:43:02.141 [gae_proxy][INFO] ------------------------------------------                                                                                                                                                          ------------
Jul 30 22:43:02.143 [gae_proxy][DEBUG] Importing CA
Jul 30 22:43:02.216 [gae_proxy][DEBUG] network IPv4 is ok, cost:136 ms
Jul 30 22:43:02.257 [gae_proxy][INFO] Database $HOME/.pki/nssdb cert exist
Jul 30 22:43:02.258 [gae_proxy][DEBUG] Begin importing CA to Firefox
Jul 30 22:43:02.258 [gae_proxy][INFO] Removing old cert to Firefox in /root/.moz                                                                                                                                                          illa/firefox/gstnt4gn.default
GoAgent XX-Net - GoAgent                                     C,,
Jul 30 22:43:02.324 [gae_proxy][INFO] Add new cert to Firefox in /root/.mozilla/                                                                                                                                                          firefox/gstnt4gn.default
Jul 30 22:43:02.359 [gae_proxy][INFO] SSL use version:TLSv1_2
Jul 30 22:43:02.360 [gae_proxy][INFO] OpenSSL support alpn
Jul 30 22:43:02.360 [gae_proxy][INFO] load ip range file:/home/*******/XX_Net/co                                                                                                                                                          de/default/gae_proxy/local/ip_range.txt
Jul 30 22:43:02.361 [gae_proxy][INFO] load ip_list num:57, target num:57
Jul 30 22:43:02.363 [gae_proxy][INFO] SSL use version:TLSv1_2
Jul 30 22:43:02.364 [gae_proxy][INFO] server 127.0.0.1:8087 started.
Jul 30 22:43:02.441 [launcher][INFO] module gae_proxy started
Jul 30 22:43:02.442 [launcher][INFO] start gae_proxy time cost:363 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Jul 30 22:43:02.465 [cloudflare_front][INFO] load /home/*******/XX_Net/data/x_tu                                                                                                                                                          nnel/cloudflare_domains.json success
Jul 30 22:43:02.466 [cloudflare_front][INFO] SSL use version:TLSv1_2
Jul 30 22:43:02.469 [cloudflare_front][INFO] OpenSSL support alpn
Jul 30 22:43:02.469 [cloudflare_front][INFO] load ip range file:/home/*******/XX                                                                                                                                                          _Net/code/default/x_tunnel/local/cloudflare_front/ip_range.txt
Jul 30 22:43:02.474 [cloudflare_front][INFO] load ip_list num:99, target num:99
Jul 30 22:43:02.478 [cloudfront_front][INFO] SSL use version:TLSv1_2
Jul 30 22:43:02.487 [cloudfront_front][INFO] OpenSSL support alpn
Jul 30 22:43:02.487 [cloudfront_front][INFO] load ip range file:/home/*******/XX                                                                                                                                                          _Net/code/default/x_tunnel/local/cloudfront_front/ip_range.txt
Jul 30 22:43:02.489 [cloudfront_front][INFO] load ip_list num:100, target num:10                                                                                                                                                          0
Jul 30 22:43:02.493 [tls_relay][INFO] SSL use version:TLSv1_2
Jul 30 22:43:02.493 [tls_relay][INFO] OpenSSL support alpn
Jul 30 22:43:02.495 [heroku_front][INFO] SSL use version:TLSv1_2
Jul 30 22:43:02.495 [heroku_front][INFO] OpenSSL support alpn
Jul 30 22:43:02.496 [heroku_front][INFO] load ip_list num:75, target num:75
Jul 30 22:43:02.498 [x_tunnel][INFO] use config_path:/home/*******/XX_Net/data/x                                                                                                                                                          _tunnel/client.json
Jul 30 22:43:02.498 [x_tunnel][INFO] X-Tunnel window:16777216
Jul 30 22:43:02.499 [x_tunnel][INFO] xxnet_version:3.12.10
Jul 30 22:43:02.500 [x_tunnel][INFO] server 127.0.0.1:1080 started.
Jul 30 22:43:02.500 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
Jul 30 22:43:02.598 [launcher][INFO] module x_tunnel started
Jul 30 22:43:02.599 [launcher][INFO] start x_tunnel time cost:156 ms
Jul 30 22:43:02.625 [smart_router][INFO] Load file:/home/*******/XX_Net/code/def                                                                                                                                                          ault/smart_router/local/gfw_black_list.txt
Jul 30 22:43:02.633 [smart_router][INFO] Load file:/home/*******/XX_Net/code/def                                                                                                                                                          ault/smart_router/local/gfw_white_list.txt
Jul 30 22:43:02.633 [smart_router][INFO] Load file:/home/*******/XX_Net/code/def                                                                                                                                                          ault/smart_router/local/advertisement_list.txt
Jul 30 22:43:02.639 [smart_router][DEBUG] use local DNS server:192.168.29.2
Jul 30 22:43:02.639 [smart_router][DEBUG] use local DNS server:192.168.29.1
Jul 30 22:43:02.640 [smart_router][INFO] server 127.0.0.1:8086 started.
Jul 30 22:43:02.640 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
Jul 30 22:43:02.640 [smart_router][WARNING] bind DNS 127.0.0.1:53 fail
Jul 30 22:43:02.640 [smart_router][INFO] start DNS server at 127.0.0.1:8053
Jul 30 22:43:02.725 [launcher][INFO] module smart_router started
Jul 30 22:43:02.726 [launcher][INFO] start smart_router time cost:126 ms
Jul 30 22:43:02.727 [launcher][INFO] begin to start web control
Jul 30 22:43:02.727 [launcher][INFO] server 127.0.0.1:8085 started.
Jul 30 22:43:02.729 [launcher][INFO] launcher web control started.
Jul 30 22:43:03.443 [gae_proxy][DEBUG] network IPv6 is ok, cost:1363 ms
Jul 30 22:43:03.759 [launcher][INFO] get uuid:278c4e98-b1f2-4711-9730-f7cf372b14                                                                                                                                                          f5
Jul 30 22:43:03.794 [gae_proxy][DEBUG] DIRECT GET https://xxnet-update.appspot.c                                                                                                                                                          om/update.json?uuid=278c4e98-b1f2-4711-9730-f7cf372b14f5&version=3.12.10&platfor                                                                                                                                                          m=Linux-3.10.0-862.9.1.el7.x86_64-x86_64-with-centos-7.5.1804-Core from:127.0.0.                                                                                                                                                          1:54164
^CJul 30 22:43:04.744 [launcher][DEBUG] start to terminate smart_router module
Jul 30 22:43:04.745 [launcher][DEBUG] module smart_router stopping
Jul 30 22:43:04.745 [launcher][INFO] module smart_router stopped
Jul 30 22:43:04.745 [launcher][DEBUG] start to terminate gae_proxy module
Jul 30 22:43:04.746 [gae_proxy][INFO] start to terminate GAE_Proxy
Jul 30 22:43:04.746 [gae_proxy][INFO] terminate
Jul 30 22:43:04.746 [gae_proxy][INFO] terminate
Jul 30 22:43:04.748 [launcher][DEBUG] module gae_proxy stopping
Jul 30 22:43:04.749 [launcher][INFO] module gae_proxy stopped
Jul 30 22:43:04.750 [launcher][DEBUG] start to terminate x_tunnel module
Jul 30 22:43:04.750 [cloudflare_front][INFO] terminate
Jul 30 22:43:04.751 [cloudfront_front][INFO] terminate
Jul 30 22:43:04.752 [heroku_front][INFO] terminate
Jul 30 22:43:04.753 [tls_relay][INFO] terminate
Jul 30 22:43:04.757 [x_tunnel][INFO] Close Socks5 server
Jul 30 22:43:04.758 [x_tunnel][INFO] Stopping session
Jul 30 22:43:04.760 [launcher][DEBUG] module x_tunnel stopping
Jul 30 22:43:04.761 [launcher][INFO] module x_tunnel stopped

**Comment by 821938089** [comment]
你指的问题是什么？
除了报了2个错之外没问题啊

**Comment by leiyu1139** [comment]
昨晚经过源码的重新搭建，现在已经可以实现局域网代理、浏览器使用自动切换模式或者智能路由模式都可以正常访问谷歌。但是http://ip:8086/proxy.pac方式好像不行。
特别感谢“821938089”、“AnyWAT”两位的热心帮助！
另外本次问题的原因其实还是不明确，在想是不是当初旧版本升级上来的时候出现了某些冲突导致的？！
另外，“AnyWAT”提到的“给局域网做代理，IP总数100是否太小？”这个问题要怎么解决？IP总数好像改不了吧？

**Comment by leiyu1139** [comment]
我指的问题就是报错的那两个会不会有影响，但是目前看来好像并没有太多影响，可以正常使用、、、

**Comment by AnyWAT** [comment]
可以正常访问谷歌——仍旧没开前置代理？
貌似最大扫描线程数取200太大？
修改总IP数（据臭大街法则，偶有可能要手动检查IP，太大不好）：
3.10.4及以往版本，data\gae_proxy\manual.ini 添加
[google_ip]
max_good_ip_num = XXX
3.10.5及以后版本，data\gae_proxy\config.json 添加
"max_good_ip_num": XXX （注意json文件格式、全英文标点。。。）

**Comment by leiyu1139** [comment]
。。。一波未平一波又起
![image](https://user-images.githubusercontent.com/19724032/43431234-6a9fa94c-949f-11e8-8a8a-bf1e79de3be2.png)

**Comment by SeaHOH** [comment]
这个必须本机操作，需要允许弹窗并使用 AppID 所属谷歌账户授权。

**Comment by SeaHOH** [comment]
不要求在特定机器操作，任意机器只要上传一次即可在所有地方使用。

**Comment by AnyWAT** [comment]
貌似更新版本

**Comment by 821938089** [comment]
AnyWAT 的方法也可以。
IP总数修改方法：
用编辑器打开\XX-Net-3.12.10\code\default\gae_proxy\local\config.py
跳到第181行或查找“max_good_ip_num”
将后面的100数值修改成想要的数值（最大17740），保存。
重启XX-Net
ps：数值不要太大，不然要经常进行手动检查ip，大约300-400即可，太大会造成不扫描ip。
若多人同时使用应对连接池相应设置进行修改。

**Comment by AnyWAT** [comment]
编辑 config.py ，一旦更新XX-Net 版本又得来一遍
若多人同时使用应对连接池相应设置进行修改——3.10.4默认可近100

**Comment by leiyu1139** [comment]
1、不要求在特定机器操作，任意机器只要上传一次即可在所有地方使用。
貌似是这样，我重启xxnet后就提示已有自己的appid了。
2、编辑 config.py ，一旦更新XX-Net 版本又得来一遍
若多人同时使用应对连接池相应设置进行修改——3.10.4默认可近100（总IP数500时😜默认值6000？）
这个我是编辑data/gae_proxy/config.json文件。已经改到512了，连接池改成512.目前使用感觉还好。
3、怎么感觉GitHub这两天访问好慢。。。

**Comment by AnyWAT** [comment]
怎么感觉GitHub这两天访问好慢——貌似 *.github.com 走直连，其它与 github 才代理，会感觉快些？

**Comment by AnyWAT** [comment]
试了试Smart Router 智能代理，貌似同样的配置，Smart Router 配置缓存内3.12.10版本有很多 unknown 但3.10.4几乎没有。。。

**Comment by SeaHOH** [comment]
不具备普遍性。
关闭后仍可回复。
