### ISSUE TITLE
连接尚未建立。 (正常)

### ISSUE THREAD

**Issue by ChrisX17** [XX-net/XX-Net#11232]
已更新到3.10.2，浏览器代理设置和CA证书状态一直是fail，之前出现过AppID流量用完的情况（只部署了一个AppID）,现在遇到了这个问题，求解决，谢谢~
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:91
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 26
ip-quality: 594
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
gws-ip-num: total:undefined ——未定义，神马情况？
浏览器代理设置和CA证书状态一直是fail——浏览器代理扩展“未加载资源”：*.deja.com 走 GAE

**Comment by ChrisX17** [comment]
什么意思...

**Comment by ChrisX17** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:90
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 414
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
什么意思...没任何意思，答非所问😱

**Comment by twofisher** [comment]
设置级别为“积极”，缓冲区128试一试

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/11238#issuecomment-409482189
