### ISSUE TITLE
ubuntu16.04 使用的几个问题

### ISSUE THREAD

**Issue by Heisenberg1997** [XX-net/XX-Net#11230]
第一个是在进行./start后 一直是进行扫描 开始的时候是ipv4的啥啥啥 后来自己瞎弄了一下一个虚拟网卡,然后成了ipv6  能不能切换回来啊?还是说GAE_proxy只支持ipv6啊?
第二个是我以前在win下部署过id 后来废置了一段时间 再在Ubuntu下部署的时候一直是部署不上的.也没有弹窗出来,
第三个是我使用GAE_proxy的时候一直说是升级到ipv6什么的,但是昨天的时候是提示可以科学上网的?
是不是需要先弄ipv6,用那提供的方法解决弹窗问题,在可以使用GAE_proxy啊?
非常感谢各位dalao了!!!

**Comment by Heisenberg1997** [comment]
解决了!
先解决了IPV6,之后将自己部署的ID改为了公共ID,就可以了,但是自己部署的ID还是没有办法使用,可能与没有弹出窗口有关

**Comment by Heisenberg1997** [comment]
部署问题解决了 以前在win下部署过的可以继续使用,但是新部署的因为一直不能弹窗进行授权就无法使用!

**Comment by goldenfreemanchina** [comment]
@Heisenberg1997   留着data文件夹，下次使用基本可以0配置的；^_^

![1](https://user-images.githubusercontent.com/6322013/43652687-7f49b064-9778-11e8-9284-64c7f6f09890.PNG)

还有，本机推荐第二个命令行减少日志文件；

BTW：现在不是已经18.04.1了么？

**Comment by Heisenberg1997** [comment]
@goldenfreemanchina 恩谢谢了 现在已经大概搞明白了 自己部署的也可以使用了  但是新部署的还是无法弹窗 
对 已经18.04 了但是一个做机器人的通讯系统没有升到18  就一直在使用16的
那个考虑关闭Issues是干什么的啊
如果我的Python升级到3.xx 会不会对这个有影响啊

**Comment by SeaHOH** [comment]
保留两个版本就行
