### ISSUE TITLE
根据@theintercept 的报道，谷歌正研发一个符合中国网络审查要求的搜索引擎

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#11246]
https://twitter.com/amnestychinese/status/1024664919600332800 
根据@theintercept （ https://twitter.com/theintercept ）的报道，谷歌正研发一个符合中国网络审查要求的搜索引擎。”如果谷歌为了进入市场而默许中国的极端网络审查，这将会是互联网自由的黑暗一天。我们很难想象这样的做法怎样符合谷歌 Do the Right Thing 的口号。”
https://twitter.com/patrickpoon/status/1024646257849991168
https://t.co/gUoUFB011m

**Comment by AnyWAT** [comment]
https://medium.com/@iyouport/%E5%BF%AB%E8%AE%AF-%E4%B8%8D%E4%BD%9C%E6%81%B6-%E5%8F%98-%E4%BD%9C%E5%A4%A7%E6%81%B6-%E8%B0%B7%E6%AD%8C%E6%AD%A3%E5%9C%A8%E4%B8%8E%E5%8C%97%E4%BA%AC%E6%94%BF%E6%9D%83%E6%97%A0%E7%BC%9D%E8%A1%94%E6%8E%A5-67c81a36e29b 快讯：“不作恶”变“作大恶”，谷歌正在与北京政权无缝衔接

**Comment by AnyWAT** [comment]
https://twitter.com/DonEvansWm/status/1024658292331569153 谷歌并没有“挺住”过，它从来都是监视机器，文中有介绍当初谷歌为何离开中国，与中国用户的认识不同；另见这篇文章：解释了为什么硅谷巨头并没有“变坏”而是本来就是做恶用的 https://medium.com/@iyouport/%E4%BA%92%E8%81%94%E7%BD%91%E7%A9%B6%E7%AB%9F%E6%98%AF%E4%BB%80%E4%B9%88-%E6%9D%A5%E8%87%AA-%E7%9B%91%E8%A7%86%E8%B0%B7-%E6%83%8A%E4%BA%BA%E7%9A%84%E5%90%AF%E7%A4%BA-cdd6b5b6bd9d … 我们不是谷歌黑，而是反对任何监视审查，该报道来自独立媒体“拦截”就是第一个帮斯诺登曝光的那家媒体

**Comment by AnyWAT** [comment]
https://twitter.com/DonEvansWm/status/1024660626189180928 喜欢 Android 但讨厌 Google 的隐私侵犯？这里有办法：https://t.co/Kotn5vPYh4

**Comment by AnyWAT** [comment]
RT @lifetimeuscn 谷歌将在中国推出搜索引擎。通俗表达：谷歌满足中共的要求，将不会让中国人搜索到一些事情的真相。当谷歌在中国搜索收入达到一定程度后，中共会迫使所有境外谷歌搜索也得满足中共。好莱坞就是个例证，不仅输华影片要经得起审查，非入华影片也不能乱说乱动。

**Comment by AnyWAT** [comment]
RT @williamlong 据国外媒体Intercept报道，谷歌计划在中国推出符合中国法律规定的搜索引擎，该搜索服务将主动封锁那些“不存在的网站”，并对“人权”、“民主”、“宗教”等敏感搜索词的结果进行过滤。据悉，谷歌这一计划代号为Dragonfly（蜻蜓），开始于去年，并在去年12月谷歌CEO会见中国高层后得到加速推进。

**Comment by rothen80** [comment]
据证券日报给出的报道称，他们从相关部门获悉，有关谷歌或重返中国的传闻并不属实

**Comment by SeaHOH** [comment]
https://db833953.google.cn/search?gws_rd=cr&q=github
谁知道这是什么？

**Comment by asmosn** [comment]
借贴主的八卦话题请教大佬们个问题…安卓修改并使用过Tumblr hosts后再改回安卓原始hosts，开SSR就打不开汤不热了(改hosts以前可以打开并登录)，这是hosts没还原彻底还是什么其他原因？

**Comment by AnyWAT** [comment]
关于目前 GFW(墙) 的封锁方式TCP封锁(阻断)猜想 | 逗比根据地 https://doub.io/sxsx-14/ 本文最后更新于 2018年8月2日 17:59 可能会因为没有更新而失效。

**Comment by northsheep** [comment]
审查不审查倒无所谓，翻了墙不止谷歌一家。比较关心的是，阉割版的谷歌，或者是 @SeaHOH 所提到的db833953，它们的ip能不能被GAE类翻墙软件顺利使用。

**Comment by AnyWAT** [comment]
转：美国国务院周四的声明，称如果谷歌以审查版本的形式进入中国，将被美国政府视为最新的中国实施非贸易壁垒的证据

**Comment by AnyWAT** [comment]
转：在 The Intercept 曝光搜索巨人准备在中国推出符合审查要求的搜索应用之后，Google 正努力控制泄密和内部的愤怒。在 Google 的 8.8 万名雇员中，只有数百人知道这项代号为 Dragonfly 的计划。在计划曝光之后，Google 的管理人员关闭了对相关文件的内部访问。
https://www.solidot.org/story?sid=57450

**Comment by AnyWAT** [comment]
转：人民日报在社交媒体平台上刊登了一篇标题为“Stability prerequisite for China’s internet opening up”（《稳定是中国互联网开放的重要前提》）的文章指出：“欢迎 Google回到中国大陆，但前提是得遵守政府相关的法律政策。” https://t.co/3NAY77mz0T
![default](https://user-images.githubusercontent.com/37962734/43760064-a45b78a0-9a53-11e8-8207-e912731a7597.png)
转：【李彦宏回应“谷歌返华”传言：非常有信心再赢一次】针对人民日报欢迎谷歌回归，李彦宏在朋友圈表示，中国的科技公司今天有足够的能力和信心，在与国际企业的良性竞争中变得更强，共享全球化红利。“如果Google决定回到中国，我们非常有信心再PK一次，再赢一次。”

**Comment by SeaHOH** [comment]
段子就用不着一起转过来啦。

**Comment by AnyWAT** [comment]
【中国母根服务器开始使用？】 世界最大局域网成形？ #母根服务器 https://www.rfa.org/mandarin/yataibaodao/meiti/ql1-08102018100048.html …

**Comment by AnyWAT** [comment]
转：Intercept 继续爆料：Google 通过国内的 http://265.com  重构自己的搜索数据库；其 App 过滤机制可以不显示任何敏感搜索词；或向第三方开放黑名单更新的 API……这一条太可怕了。 https://twitter.com/bluebird0605/status/1027376611606183936

**Comment by AnyWAT** [comment]
RT @williamlong 纽约时报：谷歌员工抗议为中国开发审查版搜索引擎https://cn.nytimes.com/technology/20180817/google-employees-protest-search-censored-china/ …

**Comment by AnyWAT** [comment]
转：谷歌公司总部，现在，八月十七日，正在进行着，对谷歌高层的抗议，对谷歌员工的声援与呼应： 伟大谷歌，不要作恶！
![default](https://user-images.githubusercontent.com/37962734/44295479-39248680-a2dc-11e8-86e4-42ea12c84030.png)

**Comment by AnyWAT** [comment]
转：一直觉得 Google 基于 UDP 的 QUIC 协议很不错，自己实现了类似 TCP + TLS 的功能，然而最近突然发现有个大问题……就是这货信息泄漏相当严重。例如最近 System WebView 换成 Chrome 后支持了 QUIC 协议，SNI 先不说，这还能从握手包里抓出发出这个请求的 Apps 包名，这完全就是让 GFW 有机可乘…… 
![default](https://user-images.githubusercontent.com/37962734/44298549-bde0c600-a317-11e8-8429-1057d5923577.png)

**Comment by SeaHOH** [comment]
要明白 QUIC 的开发目标是什么，不知道的话请搜索。

另外，早就讲过，没有什么不作恶，这只是一家美国商业公司而已。

**Comment by SeaHOH** [comment]
加密请期待 TLS1.3 + ESNI

**Comment by AnyWAT** [comment]
@chengr28 😂

**Comment by SeaHOH** [comment]
28 小朋友居然也讲这种话，QUIC 根本就不是为增强加密而开发。

**Comment by AnyWAT** [comment]
https://www.fuckbaidu.vip/

**Comment by chengr28** [comment]
@SeaHOH 个人是觉得 QUIC 的主要目标是基于 UDP 创造一个可以增强性能（可能是他们觉得 TCP + TLS + .. 不符合时代的要求）的新协议，安全性应该不是首要考虑的因素，比起 TLS 略逊一筹。以 IETF 那边的态度看，这个协议更多是提供新的思路，不是（起码不是专门）为应对审查而做的研究，这段话纯粹是陈述 Google 设计这个协议时设计不周的问题，没有证据表明 Google 是故意这样做的。

这是纯技术的问题，绝对没有其它意思 ~~报道出现了偏差可是要负责的~~

**Comment by SeaHOH** [comment]
确实是存技术问题。
但是这发言还是不小心带上了些许倾向性，这就是 AnyWAT 会转发的原因。
不过这也是难免，GFW 祸害无穷，已经扭曲了这个社会，大家不经意间就会受到影响。

**Comment by chengr28** [comment]
嘛，说话完全不带立场其实是不太可能的事情……

**Comment by SeaHOH** [comment]
突然想到有这样一句话：当你把话讲出来，它就不属于你了。我对这样的现实深感无力。
