### ISSUE TITLE
3.12.10版本，进youtube和其他网站挺好，但是进BitMex实时性网站主页能进，交易页面不行？？

### ISSUE THREAD

**Issue by RaguelFoReveR** [XX-net/XX-Net#11242]
* 最新版本为3.12.10？

* 查过没找到。

* 如题目所言：

* Aug 01 15:18:21.593 - [WARNING] task POST None /_gh/ timeout
Aug 01 15:18:21.593 - [DEBUG] GAE_Exception 600 'fetch gae fail'
Aug 01 15:18:21.593 - [WARNING] gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916
Aug 01 15:18:21.593 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916"
Aug 01 15:18:21.593 - [WARNING] GAE GET https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916 request fail:"600:gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916gae_exception:'600:fetch gae fail' https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonpdd6e5c2e90724910993a31626d3a6f6b&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700916"
Aug 01 15:18:21.953 - [WARNING] 2607:f8b0:4002:37::a h1_request:Exception('time out',) inactive_time:34 task.timeout:30
Aug 01 15:18:21.953 - [WARNING] 2607:f8b0:4002:37::a trace: 0:connect, 13644:init, 0:head, 319:head end, 26131:request, 402:Res, 4371:request, 358:Res, 3314:request, 335:Res, 4625:request, 635:Res, 1419:request, 799:Res, 2330:request, 493:Res, 2684:request, 822:Res, 598:request, 361:Res, 655:request, 342:Res, 2052:request, 460:Res, 1342:request, 341:Res, 930:request, 458:Res, 1690:request, 457:Res, 11203:request, 544:Res, 3037:request,:30465, processed:14, transfered:49449, sni:repair.dot.ability.ml
Aug 01 15:18:21.953 - [WARNING] retry_task_cb: POST None/_gh/
Aug 01 15:18:21.953 - [WARNING] POST None/_gh/ response_fail:retry timeout:30
Aug 01 15:18:21.953 - [DEBUG] 2607:f8b0:4002:37::a worker close:down fail
Aug 01 15:18:25.271 - [DEBUG] recheck_ip:2a02:2d8:0:2001::f restore ok
Aug 01 15:18:27.424 - [DEBUG] GAE GET https://tch894884.tch.quora.com/up/chan40-8888/updates?&callback=jsonp63fab8583da0465dae206ce2503df220&min_seq=4445956056&channel=main-w-dep4205-3084684336219395224&hash=9088676247620776737&_=1533107700917 from:127.0.0.1:54265
Aug 01 15:18:27.425 - [INFO] Adjust scan thread num from 1 to 2
Aug 01 15:18:28.011 - [DEBUG] create_ssl update ip:2607:f8b0:4005:1e::8 time:582 h2:0 sni:letterpridecurve.us, host:xxnet-donate-2.appspot.com
Aug 01 15:18:28.981 - [DEBUG] create_ssl update ip:2001:6c8:180:5::e time:1055 h2:0 sni:candidatebreadkeep.net, host:xx-net-5-182618.appspot.com
Aug 01 15:18:30.783 - [INFO] scan_ip add ip:2607:f8b0:401c:1b::a time:243 h2:0
Aug 01 15:18:30.784 - [INFO] remove_slowest_ip:2a00:1450:400f:c::a handshake_time:4454, fails:0
Aug 01 15:18:36.145 - [INFO] scan_ip add ip:2620:11a:a012:2::e time:1226 h2:0
Aug 01 15:18:36.161 - [INFO] remove_slowest_ip:2404:6800:400c:9::7 handshake_time:1030, fails:0。

**Comment by goldenfreemanchina** [comment]
-_-...先不说技术原理...题主你敢不敢吧支付宝挂一个代理付款???

再说，逆查你的流量，会被认为1，交易机器人；2，你被流量劫持；这两种原因都不会让你完成交易的；(我国的网银即便垃圾哦，都有这样的功能呢？！)

**Comment by RaguelFoReveR** [comment]
上楼您好，再请教一下，为什么挂lantern可以进行交易？而且我在的炒币群里很多人都是挂VPN的，自己搭梯子的也有，不过少。但是也行，不知咱XX-net能不能实现呢？当然你说的很在理，这样操作确实有很大的问题。那么，从浅的技术原理能谈谈吗？谢谢了~

**Comment by SeaHOH** [comment]
GAE 平台作为代理并不可靠，请使用 X-Tunnel。

**Comment by RaguelFoReveR** [comment]
问题已得到上楼大神解决，非常感谢您！
