### ISSUE TITLE
转让X-Tunnel流量，需要的留个邮箱吧～

### ISSUE THREAD

**Issue by littlen9ne** [XX-net/XX-Net#11248]
目前就我自己的Mac翻不出去，尝试用了X-Tunnel，其他的已经完整配置了GAEPROXY。
话说Mac用那个看不到的Miredo安装了之后，合盖再开就不能用了不知道为什么。

还有1000GB流量。
今年11月到期，我自己是用不完了。
有需要流量的下面留个邮箱账号吧，我看到了转给你们。

**Comment by Illchange** [comment]
我要 谢谢

**Comment by Illchange** [comment]
我以前用台机现在换了笔记本，好像又要设置很多东西才能用代理，但还要先去谷歌设置appid，而且不能看推特。。所以我挺需要的，谢谢你啦

**Comment by AnyWAT** [comment]
台机能用的appid，笔记本、安卓照样拿来旧能用，台机到笔记本基本上如法炮制（文件复制。。。就行？）

**Comment by 41fun** [comment]
zhazhashanee@gmail.com，非常感谢！

**Comment by erikhuang** [comment]
erik.huang.cn@gmail.com，非常感谢，正缺流量

**Comment by ConanWu** [comment]
457907449@qq.com
多谢大神

**Comment by wgqwgqwgq** [comment]
196304611@qq.com
多谢分享

**Comment by guo333323** [comment]
guo333323@sina.cn
多谢分享

**Comment by littlen9ne** [comment]
@Illchange 给个邮箱地址。
@ConanWu @wgqwgqwgq 邮箱地址不存在。
@41fun @erikhuang @guo333323 转了，有一个可能转了两份儿哈哈哈。

**Comment by littlen9ne** [comment]
@AnyWAT 我在mac下可以用XTUNNEL顺利出去，单GAEPROXY就不行，因为打开IPV6失败。好像这两个不关联。。

**Comment by Jack-ban** [comment]
@littlen9ne 我理解的不错的话，x-tunnel除了gae的通道外，还有两个通道，根据介绍为了保密性中间还中转了一次。有些地方网络环境稍微好点，没有gae的情况下也是可以用的。

**Comment by Jack-ban** [comment]
我这边环境就不怎么好，但是还能用用。现在每天youtube歌单循环，也才用了70G。你们谁有需要的，我再贡献100G吧，9月24日就到期了，估计是用不完了。

**Comment by scris** [comment]
scrisqiu@hotmail.com 谢谢了 @littlen9ne

**Comment by cmw2051** [comment]
cmw2051@gmail.com  谢谢，试试最近的效果咋样

**Comment by AnyWAT** [comment]
@Illchange 合盖再开就不能用了不知道为什么——莫非与Windows系统相似，关闭“自动调整扫描线程数”，适当增大扫描线程数。。。（ #10919 臭大街法则）不然，时不时不正常了

**Comment by ConanWu** [comment]
zjjwulin@gmail.com
谢谢大神

**Comment by ConanWu** [comment]
zjjwulin@gmail.com
谢谢大神

**Comment by ConanWu** [comment]
zjjwulin@gmail.com
谢谢大神

**Comment by ConanWu** [comment]
zjjwulin@gmail.com
谢谢大神

**Comment by cmw2051** [comment]
@littlen9ne  gae上不去，xtunnel也用不了吗？

**Comment by AnyWAT** [comment]
@ConanWu 网络卡顿，同样内容自动来个N次😜

**Comment by AnyWAT** [comment]
@cmw2051 如是Win系统，（gae上不去）或许XX3.8.5版更正常，见 https://github.com/XX-net/XX-Net/issues/11227#issuecomment-408832973 截图

**Comment by cmw2051** [comment]
@AnyWAT  白天不太稳定，晚上能好很多，白天用个十几分钟，不是IP没了，就是连接池没了，关了xx之后，过段时间再启动就正常。。目前3.10.12我用的更稳定些，3.8.5扫的IP不行，用起来明显感觉不如新版。。

**Comment by 42dream** [comment]
henryttcg@gamil.com，谢谢了！

**Comment by AnyWAT** [comment]
不是IP没了，就是连接池没了——参考 #10919 臭大街法则：一直行、一直行、一直行！

**Comment by yorgol** [comment]
yorgol@qq.com.谢谢了哈

**Comment by huangkio** [comment]
huangkaiu@gmail.com
谢

**Comment by ConanWu** [comment]
zjjwulin@hotmail.com
谢谢大神

**Comment by zuyoushen** [comment]
wangwang1001@gmail.com
谢谢了

**Comment by Illchange** [comment]
1843946931@qq.com

**Comment by cwy158** [comment]
goodycwy@gmail.com 谢谢了

**Comment by Jack-ban** [comment]
这里一共统计到8个人，没有了吗？欺负我数学不好。100/8多难除尽啊。算了，每人12.5G吧。
各位注意查收好了。
henryttcg@gamil.com 额。。。。咱gmail能不写错吗
yorgol@qq.com 1843946931@qq.com 账户不存在
其他均已转让。
![image](https://user-images.githubusercontent.com/17838717/43681907-ad516eda-9894-11e8-9ca7-0b16faca60a7.png)

**Comment by Jack-ban** [comment]
他们分完了流量，仍然不散，眼睛都望着我的X-tunnel状态页面。我立刻着了慌，撑开手掌将流量值那一行盖住，抬起头說道，「不多了，我已经不多了。」手指开了条缝又看一看流量，自己摇头说，「不多不多！多乎哉？不多也。」
@ZorrowHu 你的账户也是不存在。

**Comment by K3info** [comment]
段子都写上了_(:3 」∠ )_
eva001@hainan.net
感谢~

**Comment by yjj008818** [comment]
yjj008818@gmail.com留个邮箱试试能否转接成功！

**Comment by InoriHimea** [comment]
icarus347@gmail.com
感谢

**Comment by wchyumo2009** [comment]
还有么？conghui1988@gmail.com

**Comment by cmw2051** [comment]
@Jack-ban 今天发现又多了流量，果断过来看看咋了，谢了。。。最近翻墙封的狠啊

**Comment by yorgol** [comment]
gqg912@gmail.com,谢谢哈

**Comment by Chenlin0226** [comment]
emmm, 请问现在还有吗? 303555058@qq.com 
ps 我之前尝试捐赠appid可是邮件没有回复, 急需谢谢了!

**Comment by AnyWAT** [comment]
貌似 @qq.com 被认为非法😜

**Comment by Chenlin0226** [comment]
谢谢了,之前一直不知道. 我重新注册了一个,可以吗? madalice0226@gmail.com

**Comment by AnyWAT** [comment]
10000MB到账？

**Comment by Chenlin0226** [comment]
已收到! 太谢谢你啦!

**Comment by fujiajun** [comment]
justwantyuri@gmail.com  谢谢 想多试试网速情况

**Comment by nsfwdocnet** [comment]
joiedevivre@null.net
谢谢

**Comment by cjpmuchan** [comment]
muhaohnu@gmail.com 谢谢

**Comment by SeaHOH** [comment]
@littlen9ne 赠送完毕后请关闭此 issues

**Comment by littlen9ne** [comment]
还不太懂。。恩楼上能转成功的都转了，剩下的流量我就自己用了。

**Comment by littlen9ne** [comment]
还不太懂。。恩楼上能转成功的都转了，剩下的流量我就自己用了。

**Comment by nsfwdocnet** [comment]
已到账，谢谢

**Comment by randolfly** [comment]
emmm,谢谢啦！
如果不忙的话，转randolfzrq@gmail.com
