### ISSUE TITLE
命令行下载软件，证书报错

### ISSUE THREAD

**Issue by largewhale** [XX-net/XX-Net#11259]
今天在弄wine的东西，一碰到下载软件，就报GoAgent证书错。如下

------------------------------------------------------
Executing load_aliww 
Executing cd /home/whale/.cache/winetricks/aliww
Downloading https://download.alicdn.com/wangwang/AliIM2016_taobao(8.60.01C).exe to /home/whale/.cache/winetricks/aliww
--2018-08-04 16:53:32--  https://download.alicdn.com/wangwang/AliIM2016_taobao(8.60.01C).exe
正在連接 127.0.0.1:8087... 連上了。
錯誤: 无法验证 download.alicdn.com 的由 “CN=GoAgent XX-Net,OU=GoAgent Root - 1525770792,O=GoAgent,L=Cernet,ST=Internet,C=CN” 颁发的证书:
  无法本地校验颁发者的权限。
如果不想用安全模式連接 download.alicdn.com，請使用 ‘--no-check-certificate’ 選項
——————————————————————————————
系统：UBUNTU 18.04
xx浏览器上网正常。
 
这个要怎么解决？？

PS： 之前，用命令行添加wineHQ软件源的时候，报127.0.0.1：8087的连接错，通过将Goagent的CA.crt证书复制到/usr/share/ca-certificates下，已经解决。

**Comment by 821938089** [comment]
命令行是什么

**Comment by largewhale** [comment]
linux终端，命令行操作

**Comment by largewhale** [comment]
@SeaHOH 看了winetricks的script，证书报错问题，实际是由执行wget下载时，调用xxnet做系统代理引起。但已经把证书放入/usr/share/ca-certificates，为何还是报错？

**Comment by SeaHOH** [comment]
你是否重新生成过 CA 证书，检查是否一致。

**Comment by 821938089** [comment]
试下全新下载一个xx-net打开，然后等他导入证书，然后把原来的ip导入到这个xx-net里。

这个貌似不用挂代理吧，挂代理反而会更慢啊。

我想问下你是如何设置系统代理的，我是Ubuntu 16.04的，在系统设置里的那个代理好像是无效的。

**Comment by largewhale** [comment]
@SeaHOH /usr/share/ca-certificates下的CA证书是从xx目录里复制过去的，我不知道你说的一致性是指哪两个证书？我不是很理解你的意思。

因为搞不定证书验证的问题，只能把系统的代理关闭了，暂时解决使用的问题。貌似这个wget的系统代理也是默认打开的吧？因为很少用命令行下载，以前也没有注意过。

@821938089 我就是在/etc/wgetrc中与proxy有关的几行做了写编辑，很简单的。18.04是起作用的。

**Comment by SeaHOH** [comment]
update-ca-certificates 呢，执行过没？

**Comment by largewhale** [comment]
@SeaHOH 没执行过。

**Comment by SeaHOH** [comment]
关闭后仍可回复
