### ISSUE TITLE
一切正常，你可以访问真正的互联网了。 不能访问 报错600 :ip not support GAE 扫描到88个有效ipv6

### ISSUE THREAD

**Issue by oh-jy** [XX-net/XX-Net#11252]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
600:gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/

GAEProxy 状态信息
XX-Net 3.12.10，一切正常，你可以访问真正的互联网了。

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 88
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 610
连接池(帮助) | 新:2 h1:1 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 107

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by 821938089** [comment]
把ip全部重新检查一次再等待扫描出ip。
