### ISSUE TITLE
关于GAE下的proxy.pac的问题

### ISSUE THREAD

**Issue by majiancy** [XX-net/XX-Net#1125]
我在ubuntu上使用2.3稳定版本，为了方便使用，用自己的APPID部署，并使用PAC的方式实现代理。
前两天，发现有些网站在.pac文件中没有，于是自行在./data/GAE/目录下修改proxy.pac文件实现添加，然后重新load一次就可以使用了。
但重启机器和XX-Net后发现，我添加的域名不见了，还需要重新添加。
请教如何破？

**Comment by alresvor** [comment]
也许是被自动更新给更新掉了
在 ./data/GAE/目录下 下新建配置文件 config.ini 在里面写上
[pac]
enable = 1
ip = 127.0.0.1
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
expired = 9999999999999

expired 是重点，这个是自动更新间隔时间

**Comment by xxnet** [comment]
看来PAC也要提供自定义了才好

2015-09-29 11:35 GMT+08:00 R·Shishioh <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet 其实pac缺的挺多的，要说起来，最好能在配置页面提供一个添加网址的功能，然后生成新的pac放在data目录。如果有心也可以提供“提交网址”功能——或者提交到其他的gfwlist之类的项目也行。

**Comment by xxnet** [comment]
@simonasd
    确实不错，这个功能是很有必要

在 2015年10月7日 下午4:38，simonasd <notifications@github.com>写道：

**Comment by AnyWAT** [comment]
https://github.com/xyuanmu/XX-Mini 将下列内容添加进 manual.ini 后，并不像Mini 能更新 proxy.pac，奇怪🤣，莫非插件的PAC代理根本就不需要文件 proxy.pac ？（改名文件，代理正常，文件多余😂）
;pac 自动配置脚本
[pac]
;是否启用
enable = 1
;监听地址，如果需要允许局域网/公网使用，设为0.0.0.0，同时设置 [listen] ip = 0.0.0.0 否则无效
ip = 127.0.0.1
;默认使用8086作为代理端口，如有需要可以修改
port = 8086
;pac 文件名
file = proxy.pac
;是否开启广告拦截模式
admode = 1
;广告拦截规则订阅地址
adblock = https://easylist-downloads.adblockplus.org/easylistchina.txt
;被墙网站规则订阅地址
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
;更新时间，以秒计算
expired = 86400
