### ISSUE TITLE
XX TUNNEL密码找回邮件没有人回复

### ISSUE THREAD

**Issue by ZhouJingJes** [XX-net/XX-Net#11251]
我订购的XX TUNNEL密码丢了，已经用我的注册邮箱给xxnet.dev@gmail.com发了两封邮件请重置密码，过去十几天了还是没有人回复。。。

**Comment by AnyWAT** [comment]
貌似大佬一直不在线😱

**Comment by 821938089** [comment]
把ip全部重新检查一次再等待扫描出ip。

**Comment by zhenquanwang** [comment]
你的问题解决了吗？我也是忘记密码了。刚买了一年的流量。
