### ISSUE TITLE
建议有能力的还是自建代理，一年费用也就10美元

### ISSUE THREAD

**Issue by zengsher** [XX-net/XX-Net#11260]
具体是用美帝 virmath 最低端的 OpenVZ Linux VPS，年付费用10美金，一个月流量250G
需要一点基础的 Linux 知识，根据教程自行编译python3 + shadowsocks 服务端，用 ss 作为代理
搭好之后 PC + 手机端使用都完全没压力，不存在 twitter 证书问题，其他平台也应该可以，虽然没亲测
而且还可以可以设置多个通道账户，分享给别人使用

--利益无关

**Comment by 2378** [comment]
virmach听说速度起伏很大，是不是真的？贴主

**Comment by zengsher** [comment]
@2378 我用着没问题，可能和服务器所在的地区有关，我的在芝加哥。这个你可以选择月付1美元体验一个月。

**Comment by 2378** [comment]
谢谢分享，我手头还有，，，

**Comment by 2378** [comment]
谢谢分享，我手头还有，，，

**Comment by 2378** [comment]
谢谢分享，我手头还有，，，

**Comment by 2378** [comment]
谢谢分享，我手头还有，，，

**Comment by Alexkington** [comment]
SS被封太严重

**Comment by wuwuti** [comment]
可能并非能力问题。一旦注册，相当于上了船，小命就交给船长了。还是自由自在的比较好。

**Comment by 2378** [comment]
依楼上的说法，上了谷歌这条船，小命同样不是自己的，，，
“自由自在” 难道是说那些，手头上一堆肉机跳板，干啥都走深网的牛人吗
