### ISSUE TITLE
miredo能不能设置多个服务器切换,或者有什么方法可以断线重连?

### ISSUE THREAD

**Issue by wszgrcy** [XX-net/XX-Net#11262]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

就是最新
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

看过,但是多miredo就是介绍安装
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

ipv6有时抽风掉线,这时候等一会有可能就好了,或者重启等一会........
百度了下,可以设置miredo的服务器,我在电脑上跑了下,找了个最好的地址改了,重启后,发现时间长还会不时掉线,但是电脑上就没这个问题(win10黑科技?)
linux版本
XX-Net Status:

sys-platform: aarch64, Linux-3.14.29-aarch64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #211 SMP PREEMPT Fri Jun 1 11:12:20 MSK 2018
os-release: 3.14.29
os-detail: Dist:Ubuntu; Version:18.04; ID:bionic
architecture: 64bit,
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.15rc1
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 297
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by wszgrcy** [comment]
我不介意自己写shell脚本来做切换,但是切换仍然需要一定时间,不知道遇到过这个问题的高手是怎么解决的

**Comment by AnyWAT** [comment]
既然能自己写shell脚本来做切换，（类比）参考下 #10919 臭大街法则

**Comment by wszgrcy** [comment]
@AnyWAT 不知道什么原因引起的......这才是问题.因为同样的服务器,电脑用没问题,linux下总是时不时的掉线.

**Comment by AnyWAT** [comment]
试试：
关闭“自动调整扫描线程数”
gws-ip-num: total:100——增大总IP数3-5倍
scan-ip-thread-num: 200——传说太大（小）也不好。。。

**Comment by 821938089** [comment]
可以试下出问题时kill掉miredo的进程在重新启动。

你的脚本切换大概需要多长时间呢？

**Comment by SeaHOH** [comment]
干脆虚拟机装个 Win7。
