### ISSUE TITLE
简单问下能用gae但不能正常用xx-tunel日怎么个情况？

### ISSUE THREAD

**Issue by qjwshz** [XX-net/XX-Net#11263]
* 按理来说，gae能用，xx-tunel也应该能用(不一定100%)。昨天我还能用tunnel, 时好时坏。今天是彻底不能用了。但gae-proxy自动 切换档位则正常穿墙。

我是怕ip死得太快，能用tunnel就用tunnel. 牺牲一定速度换取安全性。

没错吧，老铁们。

你们那边如何，怎么个用法的？

**Comment by AnyWAT** [comment]
X-Tunnel 好/坏？观察 http://127.0.0.1:8085/?module=x_tunnel&menu=status GAE 前端

**Comment by SeaHOH** [comment]
参考下这个解决方案 #11227
