### ISSUE TITLE
使用腾讯阿里的dns会影响梯子么？

### ISSUE THREAD

**Issue by ShadowEmbrace** [XX-net/XX-Net#11266]
很久以前用过8.8.8.8，后来不行了就一直用的电信默认的，用国外的dns总感觉速度有影响，如果我改成腾讯的那个119.29.29.29会不会影响梯子？倒不是担心换了我爬不了墙，那样换回来就行了，我担心的是它记录梯子行为搞得梯子废掉了。。。

**Comment by 821938089** [comment]
如果是xx-net，那是不会影响的。

**Comment by ShadowEmbrace** [comment]
那就好，感觉有些网站打开有点卡，换个dns试试

**Comment by ShadowEmbrace** [comment]
试完了，电信的可以流畅看油管，企鹅的会中断。。。还是继续默认吧。。。

**Comment by dylanleesky** [comment]
114.114.114.119，号称安全防病毒的，自称不会记录用户的任何解析记录。
腾讯你觉得它作为中国大陆最大的社交软件，言论管控的重点对象，会不和GFW有合作？

1.1.1.1估计已经被污染，1.0.0.1虽然慢了，但解析的地址却是真的。和国外一个解析网址的网站的显示解析IP相同，1.1.1.1的就不同了。

**Comment by AnyWAT** [comment]
IPv4 IPv6都使用 OpenDNS
