### ISSUE TITLE
关于光猫桥接与WiFi翻墙的问题

### ISSUE THREAD

**Issue by wialny** [XX-net/XX-Net#11268]
抱歉, 这个和XX-Net没有关系, 但我实在找不到讨论的地方, 所以特来请教而各位
事情是这样的, 眼看某游戏PC解锁在即, 在听闻是P2P联网后, 想把自己家的网从NAT3改成NAT1
于是就把光猫改成了桥接, 当然也成功的实现了NAT1. 
可问题就来了, 我的手机无法翻墙了. 
奇怪的是用WiFi不行, 但换成流量就可以. 期间SSRR在手机后台保持连接状态, 所以应该能排除SSRR和手机的问题.
更奇怪的是, 此时我的PC依然可以翻墙, 无论是SS还是XX-Net都流畅无比. 所以又排除了路由器的问题
那么请问问题到底出在哪呢? 难道是光猫? 我现在改回光猫拨号后手机又可以翻墙了
我除了把光猫从PPPoE改成桥接以及路由器从固定ip改成PPPoE外, 其他包括WiFi, 局域网, DNS, 防火墙, NAT转发等设置全都没有动过啊, 光猫和路由器各自的局域网ip地址也没改动. 手机上的WiFi设置更是没有改动过

简单的说就是 
光猫负责拨号时, 路由器有线无线都能翻墙, NAT为3
光猫桥接, 路由器负责拨号时, 有线可翻墙, 无线却不行(手机使用流量可以), NAT为1
设置除了桥接和拨号外, 其他都没有改动

**Comment by 821938089** [comment]
手机用什么翻墙？

**Comment by wialny** [comment]
@821938089 
> 手机用什么翻墙？

SSRR https://github.com/shadowsocksrr/shadowsocksr-android 

因为切换为流量以及光猫拨号时都能成功翻墙, 所以应该不是SSRR的问题

**Comment by wialny** [comment]
@821938089 

抱歉我现在不在家里, 没法给出log

googleplay里原版的SS似乎很久没更新了, 因为不支持最新的加密协议还有混淆什么的, 所以很早前就换用SSR了. 而SSR删项目后就换用SSRR到现在.

**Comment by 821938089** [comment]
原版SS一直在更新啊。
https://github.com/shadowsocks/shadowsocks-android

**Comment by wialny** [comment]
@821938089 

好的, 那我半夜回家再试试. 谢谢

**Comment by wialny** [comment]
@821938089 

那个Googleplay里的SS, 我看到的是旧版, 可能是因为我手机是安卓4.3的原因吧. 从GitHub下载最新的版本无法安装, 点击apk就闪退


另外SSRR的log我不知道要怎么提取, 就算我关闭重开, 它里面已经有很长很长的记录, 却没有时间戳, 我无法判断哪些是我当前的记录.
感觉这问题可能只有换路由器才可能解决吧.

**Comment by panpeach** [comment]
本人一直光猫桥接，无论是SSRR、XX-Net、v2ray等，无线有线都能用，
路由器中DHCP服务器，指定DNS服务器。

**Comment by disarrow** [comment]
同问题，等个老哥解决下

**Comment by stormeyes** [comment]
有过类似的问题, 同一局域网下PC和手机有一个可以一个不行, 多半是DNS的问题, 有问题的那个上网终端, 使用IP访问一下网站, 看看有没有问题就知道了

**Comment by wialny** [comment]
@stormeyes 

我手机和电脑的DNS设置是一样的. 
而且最近我该用V2RAY了, 也尝试过把光猫改桥接, 结果意外的是这回手机没问题了, 反而PC只能访问国外网站了(无论是否走代理), 而国内的网站直连打不开(走代理可以)
反正我是放弃了, 还是改回了光猫拨号
