### ISSUE TITLE
请问xx-net能不能逆方向，从国外连接到国内？

### ISSUE THREAD

**Issue by imldf** [XX-net/XX-Net#11264]
有哪位知道吗？有没有办法设置？

**Comment by imldf** [comment]
@SeaHOH  我的意思是如果人在国外，需要VPN打开国内的一些网站，也需要国内的IP。xx-net能不能实现在国外翻回国内？

**Comment by imldf** [comment]
@821938089  xx-net 的服务器地址可以换成国内吗？ 如果不行的话，在国外很多中国网站打不开的

**Comment by imldf** [comment]
有墙的地方，不管是出还是进，都不容易。相对研究出的比较多，进的需求就少了。只有一些人在国外，但是国内还有一些事务需要处理的人才需要翻回国。我就是在考虑这个问题。

**Comment by 821938089** [comment]
不可以，谷歌云数据出口在美国，只能用中国的代理软件去访问。

**Comment by 821938089** [comment]
其实国外访问国内远比国内访问国外容易，但是如果是网站的限制那就没办法了，很少网站会限制访问。

**Comment by 2378** [comment]
如果贴主是想在海外看youku
chrome有个插件Unblock Youku 可以试试
要不就用“阿里云”自建

**Comment by imldf** [comment]
@2378 不是那些娱乐的需求，而是考虑到一些财务问题，例如银行系统的安全登陆等等。

**Comment by imldf** [comment]
看来只能找一些比较有保障的vpn ，并且在中国大陆有服务器的才行。但是很多大品牌的vpn在大陆都没有服务器，估计是这方面被限制了。

**Comment by 2378** [comment]
果如阿里云自建，也无法满足你的安全要求，恐怕只能找人代劳了

**Comment by SeaHOH** [comment]
涉及资金和重要资料等请不要使用基于 GAE 平台的代理。
X-Tunnel 倒是可以使用。
