### ISSUE TITLE
关于导入导出IP和指定IP地址的问题

### ISSUE THREAD

**Issue by InoriHimea** [XX-net/XX-Net#11265]
3-5月的时候ipv4大概100个，ipv6有1000多个
现在基本就只有ipv6了，而且只有100个，不知道为什么一下子少了那么多，不过速度好像比以前快了，我用的最新版的。
然后，在这100个ipv6地址，通过写了一个工具，然后分别查询他们的地址归属，有日本，亚太地区，欧洲，美国等等不同的地方，但是通过whois查询的ip地址始终是美国，请问这个能不能指定使用哪个地区的ip地址呢！

**Comment by InoriHimea** [comment]
[ip分类.txt](https://github.com/XX-net/XX-Net/files/2260336/ip.txt)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11244#event-1771522519
https://github.com/XX-net/XX-Net/issues/11253#issuecomment-410173516

**Comment by 821938089** [comment]
在xx-net目录中搜索ipv6_list.txt，用工具一个个查归属地并按文件格式分类存放，要扫描哪个归属地的ip就把文件内容换成相应归属地的ip即可。

**Comment by 821938089** [comment]
ip总数只有100个的原因是总数的限制，你可以修改，但不建议修改，太大会导致不扫描。

**Comment by InoriHimea** [comment]
@821938089 名字不变嘛，单独弄出来？

**Comment by InoriHimea** [comment]
@821938089 我没有放入美国的IP地址，结果里面既然还是美国的IP地址，而且，替换源文件格式也保持一致的不知道为啥没有生效

**Comment by InoriHimea** [comment]
@821938089 而且生效的好像是配置文件中的good_ip.txt文件，而且默认会按照延迟排序，强制的，就算给其他地域的给放到第一个来，它也照样会重新排一遍序，而且也已经给ipv6_list.txt的文件按国家分为多个，但是居然还是美国ip开头，也是不明觉厉！

**Comment by InoriHimea** [comment]
@821938089 成功了，重新下了一个，然后放进去日本的ipv6地址段，也全部扫描到了，但是，出口的ipv4还是美国的
![default](https://user-images.githubusercontent.com/33611921/43756576-ecdaec52-9a47-11e8-9ebd-aadec928be07.PNG)

**Comment by SeaHOH** [comment]
这个旧的就关闭啦。
其实要原生的 IPv6 这样才有点用，只能减小延迟，出口是没法改变的。
