### ISSUE TITLE
小bug,从谷歌搜索界面进入谷歌图片时显示重定向循环

### ISSUE THREAD

**Issue by Dannywanxyz** [XX-net/XX-Net#1126]
![image](https://cloud.githubusercontent.com/assets/13790928/10157188/3fcf0a0c-66ba-11e5-9204-d17060c886dc.png)

**Comment by redfrog999** [comment]
我用2.5.0测试下来没有任何问题。另外，新版本配合去除掉伪Google IP段之后的ip_range速度真不错。

**Comment by Dannywanxyz** [comment]
去除伪Google IP段之后的ip_range怎么操作？

**Comment by Dannywanxyz** [comment]
![image](https://cloud.githubusercontent.com/assets/13790928/10157564/a25af854-66bd-11e5-8e0c-e26831d623c5.png)
点击左侧Chris paul会产生重定向错误

**Comment by Dannywanxyz** [comment]
直接谷歌图片搜索没有问题，我的版本是2.3.0

**Comment by redfrog999** [comment]
我用2.5.0无法重现你的错误，点击了所有链接，都是一点就开了，你不妨用2.5.0版试试，另外网络环境不同也会出现各种问题。

去除伪GoogleIP，整合IP段，看这里 https://groups.google.com/forum/#!topic/fqlt/E6KbwkINUSk，去除掉这些IP段，扫描效率和使用体验都有提升，你可以试试。
