### ISSUE TITLE
关于 XX-Net 中 GitLab 拼写和链接错误

### ISSUE THREAD

**Issue by shalahu** [XX-net/XX-Net#11267]
XX-Net@GitLib =》 XX-Net@GitLab

https://gitlib.com/XX-net/XX-Net => https://gitlab.com/XX-net/XX-Net

![default](https://user-images.githubusercontent.com/1332899/43696183-6f343386-996f-11e8-9e66-adf292640fb1.png)

**Comment by SeaHOH** [comment]
#11176
