### ISSUE TITLE
请问应该如何把自己的appid捐赠给X-Tunnel?

### ISSUE THREAD

**Issue by Chenlin0226** [XX-net/XX-Net#11277]
大家好, 新人一枚, 网上看到说捐赠appid可以有流量 , 已经在Google上把一个project的member里面设置了xxnet.service@gmail.com为owner, 但owner边上显示邀请已发等待验证, 没有收到赠送的流量, 是我有步骤出错了嘛?

请问有捐赠的具体教程吗, 谢谢各位!

附: X-tunnel 账号 303555058@qq.com.

**Comment by AnyWAT** [comment]
貌似 @qq.com 被认为非法😜

**Comment by Chenlin0226** [comment]
十分感谢!我已经修改了邮箱!

**Comment by Chenlin0226** [comment]
十分感谢!我已经修改了邮箱!
