### ISSUE TITLE
IPV6无法连接

### ISSUE THREAD

**Issue by luweitest** [XX-net/XX-Net#11273]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
3.12.10

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
今天突然出现的，之前是3.12.2，升级到最新版无用。
刚换服务器的时候，IPV6显示合格一会儿，然后无效：
C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 10.121.40.37:60917
外部 NAT 映射    : 112.16.69.70:36624

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问主 teredo 服务器

C:\Users\Administrator>netsh int ipv6 show int

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 16          50        1280  connected     Teredo Tunneling Pseudo-Interface
 15          30        1500  disconnected  本地连接 3
 14          30        1400  disconnected  本地连接 2

C:\Users\Administrator>netsh int ipv6 show route

发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        手动        8    ::/0                       16  Teredo Tunneling Pseudo-Interface
否        手动        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        手动        8    2001::/32                  16  Teredo Tunneling Pseudo-Interface
否        手动        256  2001:0:c38c:c38c:3475:70ef:8fef:bab9/128   16  Teredo
 Tunneling Pseudo-Interface
否        手动        256  fe80::/64                  14  本地连接 2
否        手动        256  fe80::/64                  15  本地连接 3
否        手动        256  fe80::/64                  16  Teredo Tunneling Pseudo-Interface
否        手动        256  fe80::2ff:35ff:fe8a:c9c5/128   14  本地连接 2
否        手动        256  fe80::2ff:8aff:fe74:87e9/128   15  本地连接 3
否        手动        256  fe80::3475:70ef:8fef:bab9/128   16  Teredo Tunneling
Pseudo-Interface
否        手动        256  ff00::/8                    1  Loopback Pseudo-Interf
ace 1
否        手动        256  ff00::/8                   16  Teredo Tunneling Pseud
o-Interface
否        手动        256  ff00::/8                   15  本地连接 3
否        手动        256  ff00::/8                   14  本地连接 2

**Comment by AnyWAT** [comment]
参考 #10919 臭大街法则

**Comment by luweitest** [comment]
基本都试过了，有些无关的如增加扫描线程没有试。和#10919不同的是我的一直连不上，不是不稳定的问题。开始的“合格”显示只是假象，netsh int ipv6 show teredo 一直运行下去很快就会显示状态offline。
再贴一些信息：
-------------------------------------------------------------------
GAEProxy 状态信息
"仅 IPv6" 不可用，请检查。
状态
属性 	值
IPv4 状态 	OK
IPv6 状态(如何开启) 	Fail (尝试修复)
有效 IPv4 IP 数 	0
有效 IPv6 IP 数 	4
总 IP 数 	100
XX-Net 状态 	空闲
IP 延迟 	774
连接池(帮助) 	新:0 h1:0 h2:0
浏览器代理设置 	OK
CA 证书状态(下载) 	OK
IP 扫描线程数(设置) 	5
配置
属性 	值
代理监听 	0.0.0.0:8087
IP 模式 	仅 IPv6
前置代理 	禁用
AppID
属性 	值
工作 AppID 	你正使用公共 AppID。
系统信息
属性 	值
XX-Net Version 	3.12.10
Python Version 	2.7.13
OpenSSL Version 	16.0.0 TLSv1_2 h2:alpn
System Platform 	x86, Windows-7-6.1.7601-SP1
OS System 	Windows
OS Version 	6.1.7601
OS Release 	7
OS Detail 	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Language 	zh_CN
Architecture 	32bit,WindowsPE
Browser 	Mozilla/5.0 (Windows NT 6.1; rv:61.0) Gecko/20100101 Firefox/61.0
-------------------------------------------------------------------

日志：
--------------------------------------------------------------------
Aug 08 09:33:40.438 - [DEBUG] network IPv4 is ok, cost:2473 ms

Aug 08 09:33:41.898 - [INFO] ------------------------------------------------------

Aug 08 09:33:41.898 - [INFO] Python Version : 2.7.13

Aug 08 09:33:41.898 - [INFO] OS : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0

Aug 08 09:33:41.898 - [INFO] Listen Address : 0.0.0.0:8087

Aug 08 09:33:41.899 - [INFO] Using public APPID

Aug 08 09:33:41.899 - [INFO] ------------------------------------------------------

Aug 08 09:33:43.324 - [DEBUG] Importing CA

Aug 08 09:33:43.324 - [DEBUG] Begin to import Windows CA

Aug 08 09:33:43.354 - [DEBUG] XX-Net CA already exists

Aug 08 09:33:43.400 - [DEBUG] network IPv6 is ok, cost:5353 ms

Aug 08 09:33:43.409 - [DEBUG] XX-Net CA already exists

Aug 08 09:33:43.413 - [INFO] SSL use version:TLSv1_2

Aug 08 09:33:43.441 - [INFO] OpenSSL support alpn

Aug 08 09:33:43.459 - [INFO] load ip range file:E:\green\XX-Net\data\gae_proxy\ip_range.txt

Aug 08 09:33:43.461 - [ERROR] load ip range:<...ip list snipped...> fail:ValueError('too many values to unpack',)

Aug 08 09:33:43.476 - [ERROR] Except stack:Traceback (most recent call last): File "E:\green\XX-Net\code\3.12.10\python27\1.0\lib\noarch\front_base\ip_source.py", line 81, in load_ip_range begin, end = utils.split_ip(line) File "E:\green\XX-Net\code\3.12.10\python27\1.0\lib\noarch\utils.py", line 108, in split_ip begin, end = strline.split("-") ValueError: too many values to unpack

Aug 08 09:33:43.492 - [INFO] load ip_list num:100, target num:100

Aug 08 09:33:43.501 - [INFO] SSL use version:TLSv1_2

Aug 08 09:33:43.512 - [INFO] server 0.0.0.0:8087 started.

Aug 08 09:33:46.126 - [DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=05321b62-9ad4-49fb-aa4d-e670ae8d00d2&version=3.12.10&platform=Windows-7-6.1.7601-SP1 from:127.0.0.1:59775

Aug 08 09:33:47.132 - [INFO] scan_ip add ip:2800:3f0:4001:15::7 time:579 h2:0

Aug 08 09:33:47.132 - [INFO] remove_slowest_ip:2001:4e8:0:b03e::13 handshake_time:871, fails:2

Aug 08 09:33:47.218 - [INFO] scan_ip add ip:2405:4800:100:25::13 time:679 h2:0

Aug 08 09:33:47.219 - [INFO] remove_slowest_ip:2a00:1450:4015:d::16 handshake_time:1371, fails:1

Aug 08 09:33:47.597 - [DEBUG] create_ssl update ip:2404:6800:400c:2::b time:1467 h2:0 sni:drop.crazy.net, host:

Aug 08 09:33:48.542 - [DEBUG] create_ssl update ip:2804:d40:8c:b002::d time:1911 h2:0 sni:profitdoctor.us, host:

Aug 08 09:33:52.138 - [DEBUG] report_connect_fail:2001:8002:e21:e101::11

Aug 08 09:33:52.138 - [DEBUG] connect 2001:8002:e21:e101::11 fail:error("conn fail, sni:push-version-customer.com, top: e:timeout('timed out',)",)

Aug 08 09:34:00.780 - [DEBUG] GAEProxy web_control 127.0.0.1:59780 POST /config?cmd=get_config

Aug 08 09:34:02.828 - [DEBUG] GAEProxy Web_control 127.0.0.1:59780 GET /ipv6_tunnel?cmd=get_priority

Aug 08 09:34:02.833 - [DEBUG] GAEProxy Web_control 127.0.0.1:59782 GET /ipv6_tunnel?cmd=get_log

Aug 08 09:34:03.474 - [DEBUG] netsh state: Teredo --------------------------------------------- : enterpriseclient : win10.ipv6.microsoft.com ͻˢ¼ : 30 ͻ˶˿ : unspecified ״̬ : qualified ͻ : teredo client : managed NAT : symmetric (port) NAT Ϊ : UPNP: PortPreserving: ӳ : 10.121.40.37:57788 ⲿ NAT ӳ : 101.68.65.115:1927

Aug 08 09:34:46.148 - [WARNING] task GET xxnet-update.appspot.com /update.json?uuid=05321b62-9ad4-49fb-aa4d-e670ae8d00d2&version=3.12.10&platform=Windows-7-6.1.7601-SP1 timeout

Aug 08 09:34:49.766 - [WARNING] 2404:6800:400c:2::b h1_request:Exception('time out',) inactive_time:63 task.timeout:60

Aug 08 09:34:49.766 - [WARNING] 2404:6800:400c:2::b trace: 0:connect, 1476:init, 1105:request,:61055, processed:0, transfered:0, sni:drop.crazy.net

Aug 08 09:34:49.766 - [WARNING] retry_task_cb: GET xxnet-update.appspot.com/update.json?uuid=05321b62-9ad4-49fb-aa4d-e670ae8d00d2&version=3.12.10&platform=Windows-7-6.1.7601-SP1

Aug 08 09:34:49.766 - [WARNING] GET xxnet-update.appspot.com/update.json?uuid=05321b62-9ad4-49fb-aa4d-e670ae8d00d2&version=3.12.10&platform=Windows-7-6.1.7601-SP1 response_fail:retry timeout:63

Aug 08 09:34:49.766 - [DEBUG] 2404:6800:400c:2::b worker close:down fail

Aug 08 09:36:27.427 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

Aug 08 09:36:51.457 - [DEBUG] report_connect_fail IPv6 continue_fail_count:12

Aug 08 09:37:15.483 - [DEBUG] report_connect_fail IPv6 continue_fail_count:13

Aug 08 09:37:29.450 - [WARNING] network IPv6 fail

Aug 08 09:37:34.467 - [DEBUG] report_connect_fail IPv6 continue_fail_count:14

Aug 08 09:37:38.509 - [WARNING] network IPv6 fail

Aug 08 09:38:13.498 - [DEBUG] report_connect_fail IPv6 continue_fail_count:15

Aug 08 09:38:52.555 - [DEBUG] report_connect_fail IPv6 continue_fail_count:16

Aug 08 09:38:54.529 - [WARNING] network IPv6 fail

Aug 08 09:39:21.589 - [DEBUG] report_connect_fail IPv6 continue_fail_count:17

Aug 08 09:40:05.627 - [DEBUG] report_connect_fail IPv6 continue_fail_count:18

Aug 08 09:40:21.566 - [WARNING] network IPv6 fail

Aug 08 09:40:44.632 - [DEBUG] report_connect_fail IPv6 continue_fail_count:19

Aug 08 09:41:29.638 - [DEBUG] report_connect_fail IPv6 continue_fail_count:20

Aug 08 09:41:31.325 - [WARNING] network IPv6 fail

Aug 08 09:41:58.671 - [DEBUG] report_connect_fail IPv6 continue_fail_count:21

Aug 08 09:42:42.684 - [DEBUG] report_connect_fail IPv6 continue_fail_count:22

Aug 08 09:42:56.619 - [WARNING] network IPv6 fail

Aug 08 09:43:16.707 - [DEBUG] report_connect_fail IPv6 continue_fail_count:23

Aug 08 09:44:00.730 - [DEBUG] report_connect_fail IPv6 continue_fail_count:24

Aug 08 09:44:17.808 - [WARNING] network IPv6 fail

Aug 08 09:44:34.764 - [DEBUG] report_connect_fail IPv6 continue_fail_count:25

Aug 08 09:45:18.787 - [DEBUG] report_connect_fail IPv6 continue_fail_count:26

Aug 08 09:45:32.753 - [WARNING] network IPv6 fail

Aug 08 09:45:47.811 - [DEBUG] report_connect_fail IPv6 continue_fail_count:27

Aug 08 09:46:31.851 - [DEBUG] report_connect_fail IPv6 continue_fail_count:28

Aug 08 09:46:33.888 - [WARNING] network IPv6 fail

Aug 08 09:46:43.814 - [DEBUG] GAEProxy Web_control 127.0.0.1:60667 GET /ipv6_tunnel?cmd=get_priority

Aug 08 09:46:43.821 - [DEBUG] GAEProxy Web_control 127.0.0.1:60668 GET /ipv6_tunnel?cmd=get_log

Aug 08 09:46:44.826 - [DEBUG] netsh state: Teredo --------------------------------------------- : enterpriseclient : win10.ipv6.microsoft.com ͻˢ¼ : 30 ͻ˶˿ : unspecified ״̬ : probe (primary server) ͻ : teredo client : managed

Aug 08 09:47:05.882 - [DEBUG] report_connect_fail IPv6 continue_fail_count:29

Aug 08 09:47:09.926 - [WARNING] network IPv6 fail

Aug 08 09:47:34.113 - [DEBUG] report_connect_fail IPv6 continue_fail_count:30

.........................

**Comment by AnyWAT** [comment]
#10919 臭大街法则：分分钟一直好、一直好、一直好！何来“有些无关的”？没见无关的 #10184 ？

**Comment by AnyWAT** [comment]
进一步细究 #10184 有求助的基本要求，或许解决“一直连不上”

**Comment by luweitest** [comment]
今天重试又自己好了，或许是teredo被干扰。上来结案，看到一堆和我相同的问题，所以应该不是我个案。国内什么时候干脆封了ipv6隧道也未可知。

ps:我也算老手了，增加扫描线程我认为和teredo不稳定就是无关的，甚至只会起反效果，没有必要尝试。如果说的不对请高手指正。而且那个臭大街法则我看起来都还是觉得挺乱的，新手更不用讲。最好还是能整理一个按部就班的排查树写到wiki里面去吧

**Comment by AnyWAT** [comment]
欢迎随时回来😝

**Comment by SeaHOH** [comment]
@luweitest 可能的情况太多，无法整理出完整清晰的排查程序。

@AnyWAT 回答讨论问题时请符合主题，不要生搬硬套，各人的网络和使用环境是不同的。
