### ISSUE TITLE
teredo参数是disabled

### ISSUE THREAD

**Issue by sxd0071** [XX-net/XX-Net#11281]

**Comment by AnyWAT** [comment]
先禁用再启用网络

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by sxd0071** [comment]
@AnyWAT

**Comment by sxd0071** [comment]
@AnyWAT 
![20180809171003](https://user-images.githubusercontent.com/38394243/43889632-44473280-9bb4-11e8-98ec-e1b3b22e2eb0.png)

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient 157.56.149.60 
参考 #10919 臭大街法则

**Comment by sxd0071** [comment]
@AnyWAT 
![20180809172820](https://user-images.githubusercontent.com/38394243/43890565-a531b4d8-9bb6-11e8-82ad-f541baaa5c5e.png)

**Comment by sxd0071** [comment]
@AnyWAT GAE-proxy也可以用臭大街法则吗？？？我看不懂啊啊啊啊啊啊

**Comment by AnyWAT** [comment]
关闭使用代理的浏览器、关闭XX-Net，再管理权限运行。。。或
进一步 #10184 内提及的“先禁用再启用网络”？

**Comment by AnyWAT** [comment]
分分钟（XX-Net ）一直好的臭大街法则😜
