### ISSUE TITLE
一直 连接尚未建立。 (正常)

### ISSUE THREAD

**Issue by yorgol** [XX-net/XX-Net#11282]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

是的
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

看过
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
一直连接尚未建立，但现实个方面都正常

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:70
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 271
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

错误日志：

Aug 09 17:51:13.704 - [WARNING] GAE POST https://www.google-analytics.com/collect request fail:"600:gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Aug 09 17:51:13.806 - [WARNING] task POST None /_gh/ timeout

Aug 09 17:51:13.806 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Aug 09 17:51:13.806 - [WARNING] gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect

Aug 09 17:51:13.806 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Aug 09 17:51:13.806 - [WARNING] GAE POST https://www.google-analytics.com/collect request fail:"600:gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Aug 09 17:51:22.245 - [WARNING] task POST None /_gh/ timeout

Aug 09 17:51:22.245 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Aug 09 17:51:22.245 - [WARNING] gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect

Aug 09 17:51:22.245 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Aug 09 17:51:22.245 - [WARNING] GAE POST https://www.google-analytics.com/collect request fail:"600:gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collectgae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Aug 09 17:51:28.274 - [DEBUG] create ssl timeout fail.

Aug 09 17:51:48.557 - [DEBUG] create ssl timeout fail.

Aug 09 17:52:29.154 - [DEBUG] create ssl timeout fail.

Aug 09 17:52:49.439 - [DEBUG] create ssl timeout fail.

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
参考： #10919 臭大街法则：检查IP 或重开一个XX-Net（挤出貌似已不正常的）

**Comment by SeaHOH** [comment]
#11238
