### ISSUE TITLE
弹窗授权后, 服务部署显示成功, 但配置 appid 显示 appid 无效

### ISSUE THREAD

**Issue by ZiYang233** [XX-net/XX-Net#11283]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids 如何判断appid部署成功

**Comment by ZiYang233** [comment]
成功部署后, 顶部有提示

**Comment by SeaHOH** [comment]
这个提示并不准确，以日志为准。
