### ISSUE TITLE
savefrom插件工作不正常了，但是在把XX-net关了，开无界就又正常了

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#11290]
savefrom插件工作不正常了，但是把XX-net关了，开无界就又正常了

在XX-net下文件大小信息都显示不出来了，是一个叹号！只是没法用savefrom插件了，其他都正常。

XX-net 3.12.11 大小信息是叹号了，下载也是错误，无法下载了。
![snap1](https://user-images.githubusercontent.com/19205130/43971081-667d8f94-9d02-11e8-9253-4085fcfcfec4.png)
无界浏览 18.02 大小信息正常，下载也没问题。
![snap2](https://user-images.githubusercontent.com/19205130/43971177-b200fc30-9d02-11e8-940e-edf7e4b335ee.png)

无界和IDM在8084，Chrome和XX-net在8087。需要下载的时候把Chrome改成8084，下载任务添加好后切回8087继续在线看，同时8084上的无界和IDM在下载。这样其实挺好的，推荐！

**Comment by SeaHOH** [comment]
请提供详细信息

**Comment by GoodSake** [comment]
截了图片了，看看还需要什么信息

**Comment by SeaHOH** [comment]
你这视频也开的太多了吧，试试每次少开点。
还需要相关日志才能确定问题。

**Comment by AnyWAT** [comment]
只关心楼主的不关机已进行到X/5年😜

**Comment by SeaHOH** [comment]
关闭后仍可回复
