### ISSUE TITLE
能正常连上，状态正常，就是无法打开网页

### ISSUE THREAD

**Issue by nbwxbo** [XX-net/XX-Net#11295]
刚才突然断了一下。与昨天中午类似。能正常连上，状态正常，就是无法打开网页
![ggggg](https://user-images.githubusercontent.com/31100197/43993268-407fbd7e-9dbd-11e8-8c6d-8941e2fc6c93.JPG)
l浏览器显示
![tttt](https://user-images.githubusercontent.com/31100197/43993273-4b626778-9dbd-11e8-9c96-373ee51eb940.JPG)

**Comment by nbwxbo** [comment]
刚才恢复了几分钟，又断了。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43993361-bc10f128-9dbe-11e8-8299-177071a4932f.png)
若非人为设置为1，一定是没关闭“自动调整扫描线程数”！

**Comment by nbwxbo** [comment]
谢楼上的。关闭后，变为10了。还是网页打不开。直连模式后，可以正常打开非屏蔽网站的，说明电脑浏览器正常的。

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip 点击“检查IP”

**Comment by 2609665** [comment]
![qq 20180812135955](https://user-images.githubusercontent.com/20493163/43999126-72c381fa-9e38-11e8-8aab-28e345a59b88.jpg)
抽疯...非要让我重启一下XX

**Comment by SeaHOH** [comment]
可能是短时间内打开网页比较多，连接池里面有失效 IP 来不及清理。
