### ISSUE TITLE
xx-net真的是越来越慢了，看来到了忍痛放弃的时候！

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#11291]

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/43979440-5d3aa6f4-9d1d-11e8-98d6-b7a70f3b2f0b.png)

**Comment by souths** [comment]
楼上的方法有效

**Comment by ablebodied** [comment]
按照这个改，之前的设置会被覆盖掉了，希望改进一下

**Comment by AnyWAT** [comment]
参考 https://github.com/XX-net/XX-Net/issues/11287#issuecomment-412443944 上一楼，貌似3.12.11默认一切正常

**Comment by AnyWAT** [comment]
搜索 config.json

**Comment by nly4lov** [comment]
> 关闭“自动调整扫描数线程”，基本保持IP延时280

关闭“自动调整扫描数线程”，基本保持IP延时280？ip延时去哪里设置？

**Comment by AnyWAT** [comment]
那是关闭某开关后(因网络变化而有时间性的、但远优于未关闭的）个人结果，老面孔貌似不该有“ip延时去哪里设置？”的古怪😂
想再小点？可适当增大总IP数。。。#10184

**Comment by AnyWAT** [comment]
欢迎5年不关机的老铁 @GoodSake 参考下2楼😂

**Comment by lzq8143** [comment]
> 有线网络，无原生 IPv6 的隧道（WAN口 IP地址：10.* 高手云：纯 IPv4内网中的内网） 理由充分否：[#11376 (comment)](https://github.com/XX-net/XX-Net/issues/11376#issuecomment-425376757) 至少效果是：几乎分分钟正常、电脑唤醒后代理立马正常
> 设置级别：正常 （默认）
> 连接接收缓冲大小：256-384 （默认128）
> 貌似重点：关闭“自动调整扫描数线程”，基本保持IP延时280 想再小点？可适当增大总IP数及“最大扫描线程数”（太大不好？如520/39，延时233-266） 不能“自动维持”较小IP延时或有效IP趋近总IP数后，宜适当增大扫描线程，尤其很有 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip 检查IP的必要，观察IP延时、连接池的变化（如连接池归零或待测IP数1-2分钟后固定不再减小，宜刷新或新开需代理网页，或再运行一个XX-Net （可以挤出貌似已不正常的），或更换服务器
> PS：最大扫描线程数随时间、网络状态的变化而调整（或大或小，太小或太大都不好？）
> ![default](https://user-images.githubusercontent.com/37962734/43979440-5d3aa6f4-9d1d-11e8-98d6-b7a70f3b2f0b.png)
> ![default](https://user-images.githubusercontent.com/37962734/44709026-347d8080-aadb-11e8-89d9-200e418cd892.png)
> （开机）启动XX-Net 前即运行以下 bat（批处理内容）可观察变化过程，状态 dormant 即已开始正常化，（随时运行，凭此判断是隧道还是XX-Net 的问题，最佳）启动XX-Net 数秒隧道即可正常。
> :loop
> ipconfig /flushdns
> netsh int teredo show state
> ping 127.0.0.1 > null
> goto loop
> 
> PS：[#11336 (comment)](https://github.com/XX-net/XX-Net/issues/11336#issuecomment-415939174) 2018.9.17 按 @jor74092 添加了一行 ipconfig /flushdns 功能增强了
> 软件规则：有效 IP数到总 IP数后，超过则剔除延时高的 IP https://github.com/xyuanmu/XX-Mini
> GAE日志明显：remove_slowest_ip 而不是打开了某开关的 recheck_ip
> 可以自设定总 IP 数 xxx，3.10.5 以前版本，data\gae_proxy\manual.ini 添加
> [google_ip]
> max_good_ip_num = xxx
> 3.10.5 开始，data\gae_proxy\config.json 添加下面内容在大括号内中括号之外的最后一行文本之前，
> "max_good_ip_num": xxx，
> 或
> 添加下面内容在大括号内中括号之外的最后一行文本之后，作为新的最后一行，原最后一行末得加英文逗号
> "max_good_ip_num": xxx
> 
> Teredo 隧道到底是离线还是与XX-Net 无法连接，貌似上面的批处理简洁明了。。。
> 如批处理结果显示隧道正常，但连接池或 IP归零，或刷新或新开需代理的网页、或手动检查 IP、或再开一个XX-Net（省掉退出，直接挤掉先前貌似已不正常的）、或更换服务器（重要：近几天Win10系统的默认服务器用域名都无法连接，但用 IP却立马连上）。
> 如隧道不正常，或先禁用再启用网络、或更换服务器、或重启机器。
> Win10 启用系统默认服务器，管理权限运行：netsh int ipv6 set teredo enterpriseclient default
> 可用服务器域名或 IP替代上面的 default（貌似Win7下的 default 不行）
> 目前机器是运行了 https://github.com/chengr28/Pcap_DNSProxy （的，算广告么？）
> PS：初次启用Pcap_DNSProx 前需禁用Smart Router 模块或退出XX-Net 以释放53端口。往后软件随开机启动占用53，XX-Net 自动53不行换作8053

这太专业了，小白看不懂。XXNET这是要把我们都逼成网络高手么？

**Comment by AnyWAT** [comment]
代码老白的经历😂
