### ISSUE TITLE
文件无法下载

### ISSUE THREAD

**Issue by ntw20wddj** [XX-net/XX-Net#11296]
速度非常慢，然后下一点点就下不动了，怎么回事？谁能提供一个其他下载链接

**Comment by tmttmd** [comment]
我下载也是很不稳定，中途会变为0kb/s，不过只要有耐心等，最后还是能下完的

**Comment by AnyWAT** [comment]
貌似第一个 .7z 支持续传 https://github.com/XX-net/XX-Net/issues/11206
