### ISSUE TITLE
打开要翻墙的网站始终出现ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Testrfr2018** [XX-net/XX-Net#11299]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是，但是查不到相关问题

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

在XX-net模式下，打开youtube，twitter等网站，网页直接变成空白页，显示www.youtube.com未发送任何数据(ERR_EMPTY_RESPONSE)。刷新还是空白页。好像从3.12.8开始就有这种现象，之前都没有。
————————————————————————————————
GAEProxy 状态信息
"仅 IPv6" 不可用，请检查。
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	Fail (尝试修复)
有效 IPv4 IP 数	0
有效 IPv6 IP 数	1
总 IP 数	100
XX-Net 状态	工作
IP 延迟	9999
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	OK
CA 证书状态(下载)	OK
IP 扫描线程数(设置)	100
配置
属性	值
代理监听	127.0.0.1:8087
IP 模式	仅 IPv6
前置代理	禁用

有使用APPID

系统信息
属性	值
XX-Net Version	3.12.11
Python Version	2.7.13
OpenSSL Version	16.0.0 TLSv1_2 h2:alpn
System Platform	AMD64, Windows-10-10.0.17134
OS System	Windows
OS Version	10.0.17134
OS Release	10
OS Detail	Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
————————————————————————————————
诊断信息：
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
——————————————————————————————
在高级页面启用ipv6隧道时，一直正在检查网络，且出现记录：
best server is: teredo.iks-jena.de

C:\game\XX-Net-3.12.10\code\3.12.11\laucher>sc config RpcEptMapper start = auto [SC] OpenService 失败 5:

拒绝访问。

C:\game\XX-Net-3.12.10\code\3.12.11\laucher>sc start RpcEptMapper  [SC] OpenService 失败 1056:

服务的实例已在运行中。

………（同理
设置DcomLauch失败，拒绝访问
设置RpcSs失败，拒绝访问
设置WinHttpAutoProxySvc失败，拒绝访问）
…………

C:\game\XX-Net-3.12.10\code\3.12.11\laucher>netsh interface ipv6 reset
……其中有一步：正在重置，失败。拒绝访问。

求教大佬，谢谢。

**Comment by CYACN** [comment]
你IPv6崩了，换个服务器吧
工具:https://github.com/XX-net/XX-Net/issues/10282

**Comment by Testrfr2018** [comment]
谢谢，但是用了这个工具启用ipv6也还是没效果……

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by Testrfr2018** [comment]
C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
——————————————————————————————————————
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Testrfr2018** [comment]
过一会就变成这样了：
C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 100 ——太大（传说也不好）3.12.11 默认的10就够 https://github.com/XX-net/XX-Net/issues/11291#issuecomment-412445618
状态 : probe (primary server)——貌似进一步就🆗

**Comment by SeaHOH** [comment]
隧道不稳定而已，尝试重新拨号，实在不行只有换 ISP（实际上换个工具还简单点）。

**Comment by AnyWAT** [comment]
隧道不稳定而已——试试：是否 #10184 3-4项后就好些？

**Comment by Testrfr2018** [comment]
抱歉，一天很晚才下班，时间较少。先谢谢各位大佬，我先试下。

**Comment by AnyWAT** [comment]
貌似安卓没有代理设置的App见识了“未发送任何数据(ERR_EMPTY_RESPONSE)”，尽管同时有代理设置的App的XX-Net 代理一切正常。

**Comment by z1x1ang** [comment]
尝试将代理规则设置成绕过局域网和大陆模式
