### ISSUE TITLE
如何让电脑上的应用调用自带浏览器时也能科学上网？

### ISSUE THREAD

**Issue by egg347** [XX-net/XX-Net#11292]
用Chrome+XX-net可以科学上网。
问题如题所示，比如以前（不知道现在如何了）steam上社区是没法直接上的，我都是用Chrome上。
我现在遇到的情况是是，虽然安装了免费版的VS community，但是其实它默认30天试用，时间到了之后要登录自己的账号获得新的权限才能继续免费用。但是，VS会调用内部的浏览器，所以一直登不上账号。怎么办？

**Comment by AnyWAT** [comment]
？如何为 Windows 10 UWP 应用设置代理 https://zhuanlan.zhihu.com/p/29989157

**Comment by egg347** [comment]
已解决- -不是这个代理问题吧应该。。找了一个帖子。好像是VS这个有问题- -
