### ISSUE TITLE
youtube显示白板，其他网站正常，有知道原因的吗？

### ISSUE THREAD

**Issue by krollMJ** [XX-net/XX-Net#11307]
youtube显示白板，其他网站googl、wikipedia、通通正常，有知道原因的吗？

XX-Net 3.12.11，使用全局GAE代理，youtube没开广告过滤。

两天前还正常显示的，难道是youtube自己的问题吗？

![www youtube com](https://user-images.githubusercontent.com/28785430/44021986-e42e9efc-9f18-11e8-985b-9dd9ade14925.PNG)

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip 检查IP后再试？

**Comment by AnyWAT** [comment]
两天前还正常显示的，难道是youtube自己的问题吗？——怀疑：运行一定时间后IP延时跑大、有效IP数及连接池跑小？

**Comment by krollMJ** [comment]
@AnyWAT 

今天已经检查过IP了。

其他网站都正常显示，就油管不正常。

前两天还是用的3.11.2，今天用不了。。就升到3.12.11了。

**Comment by AnyWAT** [comment]
今天已经检查过IP了。——不正常就检查，对比下前述3参数在检查前后的变化

**Comment by SeaHOH** [comment]
尽量不要使用全局 gae_proxy 代理

**Comment by krollMJ** [comment]
@AnyWAT  就是发现问题，就马上检查IP了。其他的就不知道咋办了。

@SeaHOH 有些网站不用全局gae就打不开。油管我是gae和pac都试过了，以前都可以，今天都不可以。


GAEProxy 状态信息
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 96
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 315
连接池(帮助) | 新:0 h1:21 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 130

**Comment by AnyWAT** [comment]
检查IP后再试？——其他的就不知道咋办了。
IP 扫描线程数(设置) | 130——太大（传说也不好），3.12.11默认的10就🆗

**Comment by krollMJ** [comment]
@SeaHOH 
另外，我用Google搜索，直接进入油管播放界面，视频可以播放，网页其他部分依旧是白板。
这又是啥原因？

**Comment by krollMJ** [comment]
@AnyWAT 
@SeaHOH 

好了，我前面是用的Chrome。
现在用Edge+gae打开油管就正常了，pac打不开。
跟前段时间Chrome打开B站白板的问题，简直一毛一样。现在B站已经修复这个问题了。
果然是油管自己的问题，等修复吧。

**Comment by foho8080** [comment]
這個正常 我有時都這樣顯示,過幾分鐘就正常

**Comment by AnyWAT** [comment]
😜 刚试：Chrome 68.0.3440.106 屏幕右下角托盘 “全局PAC智能代理”，完全没有“youtube显示白板”

**Comment by AnyWAT** [comment]
换个浏览器好了——清理浏览器缓存呢？

**Comment by krollMJ** [comment]
的确是油管的问题。

昨天用Chrome打开youtube显示白板。
我哪也没动，然后今天正常显示了。
用了2小时了，一直显示正常。


GAEProxy 状态信息
XX-Net 3.12.11，一切正常，你可以访问真正的互联网了。
状态
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 85
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 319
连接池(帮助) | 新:0 h1:29 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by krollMJ** [comment]
@AnyWAT 哈哈，即使只有我一个人不能用，就不是问题了吗？

那你如何解释，昨天Chrome错误，Edge正常？
又如何解释释，昨天Chrome错误，今天正常？

类似没解决的问题，还有一个汤姆热，Chrome一直首次登入错误。
用Edge首次登入就一遍过。
用Chrome首次登入，起码得二三十次才能登入。

**Comment by AnyWAT** [comment]
清理下浏览器缓存？
