### ISSUE TITLE
感觉 Teredo 是个坑啊。。

### ISSUE THREAD

**Issue by zengsher** [XX-net/XX-Net#11308]
**是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？**
3.12.11

**是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？**
看过

**描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：**

C:\WINDOWS\system32>netsh int ipv6 show teredo state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.1.19:54229
外部 NAT 映射    : XXXXXXXXXX

**C:\Users\zengs>ping -6 [2001:470:1:18::125] -t**

正在 Ping 2001:470:1:18::125 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
请求超时。
来自 2001:470:1:18::125 的回复: 时间=467ms
来自 2001:470:1:18::125 的回复: 时间=207ms
来自 2001:470:1:18::125 的回复: 时间=208ms
来自 2001:470:1:18::125 的回复: 时间=208ms
来自 2001:470:1:18::125 的回复: 时间=208ms
来自 2001:470:1:18::125 的回复: 时间=208ms
请求超时。
来自 2001:470:1:18::125 的回复: 时间=207ms
来自 2001:470:1:18::125 的回复: 时间=208ms
来自 2001:470:1:18::125 的回复: 时间=208ms
来自 2001:470:1:18::125 的回复: 时间=208ms
来自 2001:470:1:18::125 的回复: 时间=226ms
来自 2001:470:1:18::125 的回复: 时间=215ms
来自 2001:470:1:18::125 的回复: 时间=207ms
请求超时。
请求超时。
请求超时。
请求超时。

**Comment by zengsher** [comment]
每次配置好，有效时间就几分钟，甚至一分钟不到，都轮不到 xx-net 来用，它自己就能跑死
是不是因为Teredo 的中继服务器是在国外，流量被干扰了？

**Comment by zengsher** [comment]
@AnyWAT 这个不用脚本监测，我有实际看过。
修改过teredo 服务器地址之后，第一时间不会生效，状态是 probe，之后变成 qualified ，下面也会显示映射的地址，这时可以 ping ipv6 的地址了，也可以通过 test-ipv6.com 的测试，xx-net 显示 ipv6 可用（我推测 xx-net 也是通过 ping 来判断可用与否的）。
不久之后就 ping 不通了，test-ipv6.com 测试挂了，xx-net显示 ipv6 fail。**但是这时用命令 netsh int ipv6 show teredo state 查看 teredo 状态，和之前能通的时候没有任何变化。**
据此我推测是受到了干扰。如果隧道的中继服务器（转发服务器）在国外的话，数据流应该是这样的
xx-net----pc本地Teredo客户端----(GFW)----Teredo中继服务器----Google app engine----网站
是不是意味着我们的翻墙动作完全暴露在GFW的监视之下？

**Comment by AnyWAT** [comment]
😭不识码就不说了，总之：几乎分分钟一直🆗

**Comment by AnyWAT** [comment]
在 teredo.remlab.net 和 default 之间切换——除此之外还有几个可用。貌似 win10.ipv6.microsoft.com. 、win1710.ipv6.microsoft.com. 、win1711.ipv6.microsoft.com. 都指向了157.56.149.60

**Comment by SasamiMasakiJurai** [comment]
最近不同地区污染加剧的结果

魔都6in4和6to4全线崩溃

随着国内ipv6的提速

估计其他都会如此

**Comment by SeaHOH** [comment]
@SasamiMasakiJurai 跟其它使用 IP 41 协议的隧道不同，Teredo 的封包要稍微复杂点。

**Comment by SasamiMasakiJurai** [comment]
@SeaHOH 

我软路由里面原先集成的是6to4

之前还可以连通ipv6

上个月开始已经全部抓瞎了

自从国内开始构建ipv6网络后

很多都污染了

貌似ipv6的dns已经大面积污染了。。。。。。。

江浙一些地方已经可以获取原生ipv6地址了

魔都还没放开

**Comment by SeaHOH** [comment]
换 teredo 吧，41 协议太简单了，封包跟 IPv6 没啥差别，分析很容易。

**Comment by SasamiMasakiJurai** [comment]
@SeaHOH 

openwrt无法使用teredo

无解

**Comment by SeaHOH** [comment]
最起码可以在常用设备上独立运行

**Comment by SasamiMasakiJurai** [comment]
@SeaHOH 

我现在整个翻墙都是集成在路由里面了

这样可以全屋翻墙

目前自建服务器和ssr在用

**Comment by SeaHOH** [comment]
哦。。。非常棒

**Comment by AnyWAT** [comment]
全屋翻墙——😜难道没门？
