### ISSUE TITLE
teredo隧道休眠

### ISSUE THREAD

**Issue by sxd0071** [XX-net/XX-Net#11304]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
参考 https://github.com/XX-net/XX-Net/issues/11287#issuecomment-412443944 上一楼，貌似3.12.11默认一切正常

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）证明 teredo隧道休眠？

**Comment by zangkong** [comment]
> netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）证明 teredo 隧道休眠？

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:59
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 314
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


更新3.113.1后经常隧道休眠

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 结果
![default](https://user-images.githubusercontent.com/37962734/50401739-d54f2480-07cb-11e9-87d8-55af90a61587.png)
[隧道是否正常](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204)
