### ISSUE TITLE
【求助】访问 [本地PAC] 地址提示 <拒绝连接请求>

### ISSUE THREAD

**Issue by CYACN** [XX-net/XX-Net#11300]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
设置PAC代理无效
访问http://127.0.0.1:8086/proxy.pac
提示127.0.0.1 拒绝了我们的连接请求。
诊断信息
XX-Net Status:
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:11 h2:0
scan-ip-thread-num: 1
ip-quality: 63
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by CYACN** [comment]
已重置防火墙，无效

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 模块管理 全ON？

**Comment by CYACN** [comment]
部分日志：
Aug 12 20:24:15.065 - [DEBUG] launcher web_control 127.0.0.1:10381 GET /proxy.pac 
Aug 12 20:24:15.065 - [INFO] 127.0.0.1:10381 "GET /proxy.pac HTTP/1.1" 404 -

**Comment by CYACN** [comment]
@AnyWAT AnyWAT 谢谢，开启AutoRoute后问题已解决
话说在Issue中怎么回复他人留言

**Comment by CYACN** [comment]
好像不能，我Close了啊……

**Comment by SeaHOH** [comment]
> 话说在Issue中怎么回复他人留言

没这功能，一般引用或直接 @。
