### ISSUE TITLE
经常出现尚未建立连接，ipv6不可用是什么问题

### ISSUE THREAD

**Issue by sunshineyi26** [XX-net/XX-Net#11316]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 3
ip-quality: 404
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
IPv6 隧道不稳定

**Comment by sunshineyi26** [comment]
楼上有什么解决办法吗

**Comment by RoderickQiu** [comment]
@AnyWAT 都ipv6 fail了就和这个关系不大了吧 其实最近部分地区teredo&GAE我觉得真的不稳定 我也用了半年多XXNet了 最开始GAE都是很好的 7月以后GAE就经常抽风了 已经纯XTunnel了 现在没有任何问题^_^

**Comment by AnyWAT** [comment]
纯XTunnel了 现在没有任何问题——好厉害👍
X-Tunnel 共5前端，貌似除了GAE其它4个一般GG了。
IPv6隧道正常，GAE才正常
GAE正常，X-Tunnel 才正常
😜几乎分分钟一直好的臭大街法则 #10919  参考： #10184

**Comment by SeaHOH** [comment]
再强调下，各人网络环境不同，仅此而已。

**Comment by catast-hf** [comment]
请问，Windows10，xx-net页面无法打开，显示无法访问此网站
127.0.0.1 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

**Comment by SeaHOH** [comment]
> 检查代理服务器和防火墙

还有，商店应用需要破解允许本地代理。
