### ISSUE TITLE
有效IPv6 IP 数不少，

### ISSUE THREAD

**Issue by qinweifu** [XX-net/XX-Net#11319]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

XX-Net Status:

sys-platform: x86_64, Darwin-17.6.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
os-release: 17.6.0
os-detail: Release:10.13.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:86
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 459
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
--

**Comment by RoderickQiu** [comment]
首先ipv6就fail了……还有1线程又是什么鬼……
