### ISSUE TITLE
teredo如果被封怎么办？

### ISSUE THREAD

**Issue by luweitest** [XX-net/XX-Net#11312]
就那么几个服务器，早晚封掉，有没有对策？

**Comment by AnyWAT** [comment]
😱网信办鲁炜账号？

**Comment by SeaHOH** [comment]
不会封

**Comment by 2609665** [comment]
鲁炜不是调到秦城了么?

**Comment by 2378** [comment]
封了，那是落人口实
但干扰不会停的，分地区～我这里基本无福消受:turtle:

**Comment by erdcy** [comment]
试试he.net的free ipv6 tunnel，前提是：
1，有公网ip，中国电信可以打客服电话索要，其他运营商不清楚；
2，ip地址可以被ping（有些运营商封了ping）。
理论上满足上述条件就可以通过he.net的免费服务实现原生ipv6，如果有一台openwrt路由器，可以给局域网内所有终端分配原生ipv6地址，google有很多教程。

**Comment by luweitest** [comment]
为什么么不会封呢，现在有什么应用必须得teredo？ @SeaHOH 
如果teredo封了，这些tunnel 应该也差不多 @erdcy

**Comment by SeaHOH** [comment]
Xbox

**Comment by erdcy** [comment]
上网的方法层出不穷，xx不就是goagent不好用以后出现的嘛，怕断了线，随时找好备用方法啊。
