### ISSUE TITLE
XXNET连接不稳定

### ISSUE THREAD

**Issue by Asura003** [XX-net/XX-Net#11315]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

1
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

1
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

在一切正常和连接尚未建立之间来回切换，无法打开网页

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:520 ipv4:0 ipv6:493
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 345
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 10 不正常时可适当增大，并检查IP。。。

**Comment by AnyWAT** [comment]
弃用 ISP 商 DNS ，指定 IPv4 及 IPv6 DNS ？

**Comment by AnyWAT** [comment]
在一切正常和连接尚未建立之间来回切换——重开XX-Net（挤出已疯了的那个？）
