### ISSUE TITLE
XXnet一切正常，但无法访问墙外网站

### ISSUE THREAD

**Issue by Isaac1573** [XX-net/XX-Net#11317]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XXnet显示一切正常，但打开网页均显示ip not support GAE' 
例如打开Youtube：
600:gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/

日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:520 ipv4:0 ipv6:179
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:1 h2:0
scan-ip-thread-num: 30
ip-quality: 513
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
* 如果问题得到解决，请务必回复相关情况，谢谢。

之前一帖中建议调整IP数及扫描线程，尝试许久始终无法成功访问。单开一帖求解决办法。

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
