### ISSUE TITLE
经常出现1006

### ISSUE THREAD

**Issue by xzhe57** [XX-net/XX-Net#11311]
- 

![erep](https://user-images.githubusercontent.com/36105596/44079167-f88dac72-9fda-11e8-825b-7403f0700484.jpg)

**Comment by xzhe57** [comment]
版本3.12.2，最近几天越来越频繁出现，请教大神

**Comment by SeaHOH** [comment]
>has banned your IP address

这不是写得很明白？
不知道和 XX-Net 有何关系？你把后面的 IP 擦掉了，我也不清楚是不是 GAE 的出口 IP。

**Comment by SeaHOH** [comment]
关闭后仍可回复
