### ISSUE TITLE
请求python2.7 指教 ！！！

### ISSUE THREAD

**Issue by fuckchinaOK** [XX-net/XX-Net#11321]
我要在特定的网站（http://**.gsxt.gov.cn）收集资料，但手工收集太慢了。 所以希望能用python2.7 来做一些事。

我要的资料就是指定“特定关键词”自动收集（企业名称，法人，年报中的邮箱/电话/住址。）然后保存到 xlsx 表格文件或txt文本。

我是python2.7 新手，请教高手们，我需要学习python2.7的哪些库？或哪些知识？能做到我的要求。

--------------------------------------网站分析/浏览器F12记录-------------------------------------------
http://gd.gsxt.gov.cn

search_form		searchForm   post  /corp-query-search-1.html
search	keyword searchword

查询按钮  btn_query

http://gd.gsxt.gov.cn/js/subpubsys_homepage.js    ( 这个JS 控制输入? )
http://gd.gsxt.gov.cn/js/geetest/gt.js			( 这个JS 验证? )

省份	province  440000/450000,460000,470000.....

地区选择 ads-sci-list  area selected
data-value="0"    /默认0是全部		data-value="440100" , 后面440100会增长  440200,440300...

状态选择 ads-sci-title   cStatus selected   data-value="0" /默认0是全部, 增长1,2,3....

搜索结果列表页面 search_list_item db 
(每页10个结果)
(	点击链接，进入详细页 href=	)   

公司名字 f20

法人 div-user2 		 fa fa-user2 ml20   	   g3

odd	even

搜索结果页数选择  pagination

首页 href="javascript:turnOverPage(0)"
当前页 current
href="javascript:turnOverPage(*)"     /*号,1,2,3....

年报  annual_menu_table
	查看	jumpToAnnualDetail(this)	clickToDetail
			地址	addrForColor1	addr
			电话	telForColor1	tel
			邮件	emailForColor1	email

---------------------------------------------分析完毕------------------------------------

**Comment by zengsher** [comment]
google，百度 爬虫都有结果吧，没必要来发 issue。

**Comment by fuckchinaOK** [comment]
谢谢回复，你说的搜索引擎，关键它们爬的不是我要的"指定关键词"。
例如  site:gd.gsxt.gov.cn
在google ， 总数才2条记录。

例如  site:sh.gsxt.gov.cn
这个在google，虽然比2条多一点，但真不是我要的结果。

**Comment by zengsher** [comment]
1、通过搜索引擎找爬虫知识；
2、根据得到的知识编写脚本；
3、利用脚本爬取你要的数据。

**Comment by SeaHOH** [comment]
花钱雇人
没钱自学
