### ISSUE TITLE
用一会就检查ca证书

### ISSUE THREAD

**Issue by wuliaoC** [XX-net/XX-Net#11329]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:44
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:4 h2:0
scan-ip-thread-num: 200
ip-quality: 624
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 200 太大（传说也不好） #11291 
用一会就检查ca证书——代理扩展图标上数字内有未加载资源？*.deja.com 走GAE（貌似软件检测。。。）
或关闭网页再“恢复关闭的标签页”

**Comment by SeaHOH** [comment]
CA 证书不是帅哥美女，如果使用正常就不用老是盯着它看。

**Comment by xiaoteai** [comment]
Xndroid  CA证书无法 正确安装  手机的版本  解释一下
