### ISSUE TITLE
升完级就不能用了。。

### ISSUE THREAD

**Issue by prkom** [XX-net/XX-Net#11322]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
就是最新版的。

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
按照流程走过一遍了

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 2
ip-quality: 518
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
is-idle: 1
Appid_Working: false ——空闲（假死）了，没缓过气来？貌似问题在：
scan-ip-thread-num: 2 ——打开了某开关 #11291
