### ISSUE TITLE
Your AppID out of quota, Please deploy more AppID.

### ISSUE THREAD

**Issue by TerryBryant** [XX-net/XX-Net#11328]
我的流量被偷了吗？这几天都没用GAE，天天用x-tunnel，结果告诉我账号流量用光了？？

我可是部署了七八个账号啊，而且账号的流量是每天都会更新的

感觉有点过分了，请问有人知道是怎么回事吗。。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/x-tunnel使用教程
>更多前端，更快更稳定
目前支持GAE, cloudflare, heroku
客户端根据速度，智能调度。

你关闭 gae_proxy 模块没有？

**Comment by TerryBryant** [comment]
@SeaHOH 没，我用的linux，后台一直在运行

**Comment by SeaHOH** [comment]
使用 gae 前端当然会消耗 gae 流量。

**Comment by TerryBryant** [comment]
没有啊，我在SwitchyOmega里面一直用的都是x-tunnel自动切换，根本没有用gae-proxy代理。x-tunnel走的是我购买的100G流量啊，这跟gae里面我部署的8个账号，每天8G流量有什么关系？

**Comment by SeaHOH** [comment]
>目前支持GAE, cloudflare, heroku
客户端根据速度，智能调度

X-Tunnel 会使用 gae 前端

**Comment by TerryBryant** [comment]
好吧，原来是这个机制，怪不得我现在xtunnel也用不了了

**Comment by SeaHOH** [comment]
GAE 流量会比 X-Tunnel 流量大一些，但应该不会大太多。
你到[后台](https://console.cloud.google.com/)查看过没有？到底是否是流量配额耗完。

**Comment by TerryBryant** [comment]
我查了其中几个app engine quota，Outgoing Bandwidth和Incoming Bandwidth都是“0.02 of 1 GB”，但Frontend Instance Hours占满了，显示的是“28.04 of 28 Instance Hours”，请问这个是什么意思啊？

**Comment by SeaHOH** [comment]
运行时间被消耗完毕，你的 XX-Net 是否长期运行？
建议自己部署的 AppID 不要一次性填写完毕，分成三四个一批，用完才更换。

**Comment by TerryBryant** [comment]
是的，我的linux一般不关机，xxnet也就跟着一直在后台跑。。看来要换部署方式了，谢谢大佬解答！！！@SeaHOH

**Comment by SeaHOH** [comment]
主要是 X-Tunnel 为了保持在线会持续间隔时间发送数据包。
如果单用 gae_proxy 不使用 X-Tunnel，或者 X-Tunnel 不使用 GAE 前端，都不存在此问题。

**Comment by TerryBryant** [comment]
是的，有时候gae不稳定，我就切换到x-tunnel上，后来就出现了这个配额耗尽的情况。话说“ X-Tunnel 不使用 GAE 前端”，这个要怎么设置啊？

**Comment by AnyWAT** [comment]
？ https://github.com/XX-net/XX-Net/issues/11280

**Comment by TerryBryant** [comment]
@AnyWAT OK，多谢！
