### ISSUE TITLE
最新版3.12.11，仅IPV6不可用，请检查

### ISSUE THREAD

**Issue by suifengshiqu** [XX-net/XX-Net#11326]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

最新版3.12.11，仅IPV6不可用，请检查，尝试了开启IPV6和自带的enable_ipv6.bat运行后还是提示这个

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

看过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3521.2 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by suifengshiqu** [comment]
PS C:\Windows\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
能否把——类型 : enterpriseclient (Group Policy) 最后的括号及内容去掉😜？
（关闭使用代理的浏览器、退出XX-Net，）使用系统默认服务器：
管理权限运行 netsh int ipv6 set teredo enterpriseclient default

**Comment by AnyWAT** [comment]
或 157.56.149.60 替换上面的 default

**Comment by suifengshiqu** [comment]
参考这个设置重复了两次以后现在可以正常访问了
1.“Windows + X”，选择“命令提示符（管理员）”或者“Windows PowerShell（管理员）”

2.输入“ipconfig /release6“并回车，释放iPv6地址（丢弃已过期的iPv6地址）

3.输入“ipconfig /renew6”并回车，稍等几秒到一分钟，iPv6连接即可变为：Internet。

作者：Micro井
链接：https://www.jianshu.com/p/b63354431d62
來源：简书
简书著作权归作者所有，任何形式的转载都请联系作者获得授权并注明出处。
