### ISSUE TITLE
频繁的版本更新，每次下载都十分困难

### ISSUE THREAD

**Issue by DicTag** [XX-net/XX-Net#11324]
一般打开网页就登录失败，602，一看果然又要更新了，无论git的clone还是公告的各种入口下载基本每次都超时，每次都是(无论是否开着XX-net，配不配全局，用tunnel还是gae，浏览器代理是否开着，试过各种组合，也试过开着别的代理，在能上外网的情况下，在git也下载不了）尝试无数次有很小的概率能成功下载，下载完最新版也不一定能用，主要是根本下不了。自从付费后，几乎没有几次成功上过外网，特殊时期就算了，网络环境有问题还是什么情况。系统win7,另一台win10连无线基本上也这样的情况，电信给的网速300M...来个人帮帮我吧。。大半年过去了，买的流量几乎要烂掉，希望得到指导，谢谢。

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 通用——以绿色方式运行(帮助)ON
版本——自动升级到：通知测试/稳定版或不升级
手动下载 .7z（支持续传）、解压。。。妥帖👍
600 or 602 貌似打开了某开关的锅 #11291

**Comment by DicTag** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DicTag** [comment]
下载仍然很困难，试了数次，跑到50%左右 failed...,好像有一次说下载完成，但下完不知道去哪了。。
抱歉 #11291 这个issue的解决方式没看懂，是在哪里设置开关的。。

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting

**Comment by AnyWAT** [comment]
下完不知道去哪了——全（电脑）城😝搜索下载文件？

**Comment by DicTag** [comment]
找到了XX-Net-master\data\downloads，只是448k，好像打不开。。是不是不正常。。。orz

**Comment by DicTag** [comment]
"尤其很有检查IP的必要",点“检查IP"选项卡下面“开始”就是什么都没有然后就自动停止了，上面三行0，。。。好像之前一直默认用tunnel, gae很早就放弃了，等下重新部署下试试

**Comment by AnyWAT** [comment]
X-Tunnel 共5前端，貌似除了GAE其它4个一般GG了。
IPv6隧道正常，GAE才正常
GAE正常，X-Tunnel 才正常

**Comment by DicTag** [comment]
soga,..谢谢，有空再研究下#10184吧。。那个说的手动下载，是指的“版本——自动升级到：通知测试/稳定版或不升级”这个页面下面“手动管理”这里的吗？经常是直转圈圈连进度都没有。。还有gae页面的clone也试过，都下不下来。。感觉被嫌弃了。。（所以还是说得在能偶尔连上外网的时候才能下载。。或者我的打开方式有哪里不对)

**Comment by AnyWAT** [comment]
手动（代理正常时）下载： http://127.0.0.1:8085/?module=launcher&menu=config 版本——手动管理 (高级) ——点击“全部已发布版本”
自己琢磨😱
![default](https://user-images.githubusercontent.com/37962734/44221718-e00e0300-a1b4-11e8-98a9-c58a183e7072.png)

**Comment by AnyWAT** [comment]
gae很早就放弃了——貌似得用公共AppID按前述方法先救活3.12.9，再部署（更新）私有AppID

**Comment by RoderickQiu** [comment]
gae好tunnel才好这真的不一定 部分地区cloudflare可以用的啦
楼主其实可以再添置一个备选方案 betternet你可以试一下（我在iOS上有用它们的产品，翻是绝对能翻了 至于隐私安全问题 就不清楚了 不过一般用gae的人也多半不care这个）

**Comment by AnyWAT** [comment]
一般、一般、一般😂

**Comment by DicTag** [comment]
今天换了台电脑下载十分顺畅了，更新后立马就能谷哥了，不过上不了github,,,,然后想起以前hosts配了一堆乱七八糟的都删了就完全好了。。晚上回去看看是不是那台也是hosts问题。。。傻了。。。

**Comment by AnyWAT** [comment]
@SeaHOH 😱不会吧？
![default](https://user-images.githubusercontent.com/37962734/44248128-5a716e00-a21b-11e8-8c72-6b29b9893616.png)

**Comment by SeaHOH** [comment]
@AnyWAT 完全不知所云

**Comment by AnyWAT** [comment]
👍心地纯真的大海G

**Comment by SeaHOH** [comment]
你说的这个事情和 XX-Net 有关吗？想表达个什么意思？

**Comment by SeaHOH** [comment]
本业搬砖，关我PI事，而且你这故事没头没尾。
