### ISSUE TITLE
有人用树莓派3B实现XX-NET透明代理服务器吗？

### ISSUE THREAD

**Issue by windlab2020** [XX-net/XX-Net#11331]
我已经实现了树莓派本身的科学上网问题，也实现了其它设备（例如手机）通过树莓派的wifi实现国内的网站上网。但现在卡在了手机或其它设备无法通过树莓派的wifi实现科学上网。曾经尝试过使用iptables做NAT转发，但一直不成功，现在求教各位大侠，必须用redsocks+修改data/smart_router/config.json这一种方法吗？还有其它方法吗？有没有哪位大侠在树莓派上实现了XX-net透明代理的，可以分享一下配置方法，不胜感谢！！

我的局域网段信息如下：
Newifi Lan 路由器： 192.168.99.1 
Newifi Lan dhcp:192.168.99.100- 192.168.99.249/255.255.255.0

Raspberry pi eth0: 192.168.99.153
Raspberry pi wlan0: 192.168.4.1

**Comment by AnyWAT** [comment]
？https://github.com/XX-net/XX-Net/issues/11293#issuecomment-413783718

**Comment by SeaHOH** [comment]
只能转发 Smart-Router，其它端口不支持。

**Comment by AnyWAT** [comment]
@SeaHOH 是说XX-Net 系统代理（如同Win系统托盘勾选）“全局Smart-Router 代理”才行？

**Comment by SeaHOH** [comment]
说的是透明转发，之前发布的 issues 里面有相关内容，和代理设置无关。
