### ISSUE TITLE
谷歌浏览器 ca证书 fail

### ISSUE THREAD

**Issue by jintianee** [XX-net/XX-Net#11334]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
使用的是最新3.12.11

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看了

* 是否以相关关键词搜索过类似 issues？
搜了

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:54
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 494
is-idle: 1
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jintianee** [comment]
证书是导入了的

**Comment by jintianee** [comment]
照您说的做了 还是fail

**Comment by jintianee** [comment]
重启电脑后ok了

**Comment by AnyWAT** [comment]
👀莫非私有AppID（服务端）不是新版3.3.5？如是利用公共ID，再部署（升级服务端）

**Comment by AnyWAT** [comment]
重启电脑后ok了——如是，貌似先禁用再启用网络即可🆗
