### ISSUE TITLE
原生ipv6网络下Chrome浏览器代理设置和CA证书状态都是fail

### ISSUE THREAD

**Issue by zhixin12** [XX-net/XX-Net#11336]
更新了最新版本之后xx-net就不能使用了。发现是两个fail的问题。（能直接上ipv6）

Chrome是最新版本。发现在打开xx-net时打开Chrome，然后此时switchomega设置GAE可以翻墙，但是如果改成直接连接之后，过一会再切换回GAE 模式，就会出现浏览器代理设置和CA证书状态Fail。

尝试过ctrl+F5刷新，以及删除certs下的证书及CA证书重新导入。

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 243
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![20180820183719](https://user-images.githubusercontent.com/23091319/44335811-2363bc80-a4a8-11e8-8aa2-17611ad22895.png)

**Comment by AnyWAT** [comment]
switchomega 时而 GAE 时而直连，不就是 GAE 自动切换？
删除certs下的证书及CA证书重新导入——费力不讨好
is-idle: 1——检查IP，同时新开需代理的网页，或再开一个XX-Net（挤出貌似已吧正常的）

**Comment by AnyWAT** [comment]
更新了最新版本之后xx-net就不能使用了——私有AppID（服务端）不会不是3.3.5新版？

**Comment by zhixin12** [comment]
之前的几个版本都可以，就是最近的两个版本出现了问题。
然后xx-net在刚打开Chrome时就直接选择GAE或者自动切换时可以的，但是等过一会的话再选择就不行了。
也就是当浏览器代理设置和CA证书状态是OK的时候可以使用，状态时Fail的时候就不能使用

**Comment by zhixin12** [comment]
is-idle: 1——检查IP，同时新开需代理的网页，或再开一个XX-Net（挤出貌似已不正常的）

这个我再打开一个xx-net还是不行。

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by AnyWAT** [comment]
switchomega （手动）时而 GAE 时而直连，不如就一直用情景模式：GAE 自动切换？

**Comment by zhixin12** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）

这个是什么意思，因为目前可以直接上ipv6，所以之前没有运行过这个。

**Comment by AnyWAT** [comment]
目前可以直接上ipv6 ——才知道，没有此经历，还真是浪费大家的精力。Sorry，一切白说😭

**Comment by AnyWAT** [comment]
建议主题：原生IPv6 网络浏览器代理设置和CA证书状态都是fail

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/44337308-ca4a5780-a4ac-11e8-818e-e12a0404d542.png)

**Comment by zhixin12** [comment]
sorry，是我描述有问题了。想问一下，删除软件再解压运行的话还需要重新部署APPID吗

**Comment by AnyWAT** [comment]
保留 data 目录，不用重新部署APPID

**Comment by zhixin12** [comment]
我把data保留之后，删掉之前的文档，重新解压之后发现还是不行

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/44337993-20b89580-a4af-11e8-8c09-63ce0824ebd9.png)
没经历，乱说😜

**Comment by AnyWAT** [comment]
（不短时间的）直连：貌似软件检测代理及证书的（？）、非走GAE不正常的 *.deja.com 走不通，2Fail了😂

**Comment by azizyu** [comment]
我的也是这种情况，浏览器代理设置和证书状态都显示fail，删掉重装，电脑重启都试过没用，请问你找到解决方案了吗？

**Comment by zhixin12** [comment]
不知道怎么解决== @azizyu

**Comment by jor74092** [comment]
不管使用的是不是原生ipv6还是teredo，这都与证书是不是Fail没有直接关系。

proxy_state: Fail
ca_state: Fail
这两项与WIN系统和XX有关。

ipv4-status: OK
ipv6-status: OK
这两项是不是OK与网络有关。如果ipv6不是OK状态，就检查teredo或原生ipv6是否出问题了。

**Comment by AnyWAT** [comment]
worker: h1:0 h2:0 ——连接池
is-idle: 1 ——XX-Net 空闲（没工作）
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）
这个是什么意思——在 CMD 窗口内运行。。。
（开机）启动XX-Net 前即运行以下 bat（批处理内容）可观察变化过程，状态 dormant 即已开始正常化，（随时运行，凭此判断是隧道还是XX-Net 的问题，最佳）启动XX-Net 数秒隧道即可正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by jor74092** [comment]
:loop
ipconfig /flushdns
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

批处理中加一行ipconfig /flushdns
/flushdns        清除 DNS 解析程序缓存。

每次显示teredo状态前清除一次DNS缓存，如果teredo服务器出现问题获取不到连接地址，即刻就能呈现出问题，比设置“客户端刷新间隔”反应还快。

**Comment by jor74092** [comment]
如DNS污染严重，获取ipv6地址时就会变得异常不稳定，通过加ipconfig /flushdns的批处理，实时呈现在刷新DNS缓存后teredo状态，比设置“客户端刷新间隔”显示异常状态反应还快。

**Comment by Eri5Ch** [comment]
打开智能路由模块试试

**Comment by AnyWAT** [comment]
如DNS污染严重——弃用系统默认的LSP商IPv4及IPv6 DNS，采用如
![default](https://user-images.githubusercontent.com/37962734/45431201-bf649a80-b6d9-11e8-8204-75318a08e075.png)

**Comment by AnyWAT** [comment]
@jor74092 经32Win10PRO/1809测试，添加了 ipconfig /flushdns 的功能貌似比不加时强大多了。。。👍
