### ISSUE TITLE
安卓：代理服务器拒绝连接（火狐浏览器）

### ISSUE THREAD

**Issue by whytakemyname** [XX-net/XX-Net#11339]
xxnet安卓最新版本。
(根据教程的代理方法设置后成功上网。(教程地址[https://github.com/XX-net/XX-Net/wiki/How-to-use#android])
其方法如下：
(Firefox安卓浏览器可以使用Pan插件(默认代理方式为SS)，类似pc版的autoproxy插件，可以在about:config 设置代理方式为GoAgent.
**如果不使用代理插件,可在地址栏输入 about:config ,搜索 proxy.type 将5改成1 ,然后搜索 proxy.http ，在上面横线填上 127.0.0.1 下面横线填上 8087**)
改过之后是成功上网了，但是退出xxnet后除了百度外，很对网址都打不开，显示为：代理服务器拒绝连接
![1](https://user-images.githubusercontent.com/34732308/44375129-9dd22200-a524-11e8-9d9a-dc806bc6421f.jpg)
想咨询求助一下，像我这样的，除了每次都要把浏览器about:config设置再改一下才能正常上网。有没有不用每次改火狐浏览器代理的方法。
17年的帖子有说用插件的，（内容为：Firefox安卓浏览器可以使用Pan插件(默认代理方式为SS)，类似pc版的autoproxy插件，可以在about:config 设置代理方式为GoAgent.）可是提到的pan插件因为太老不能在火狐浏览器上安装了。更加新的switchyomega插件在安卓火狐上又不知道该怎么设置。
求助！感谢！
@SeaHOH
@onplus
@Sasami@Masaki@Jurai@SasamiMasakiJurai
还有各位大神
求助！！！

**Comment by SeaHOH** [comment]
导入 SwitchyOmega 设置 https://github.com/XX-net/XX-Net/raw/master/SwitchyOmega/OmegaOptions.bak

**Comment by whytakemyname** [comment]
你好，导入之后仍然无效（在线导入和把代码编成bak文件都试过）。导入后所有网页显示代理服务器拒绝连接。退出软件后仍然所有网页显示代理服务器拒绝连接。

**Comment by SeaHOH** [comment]
导入后还要设置。
默认情景模式是`Smart-Router`，需开启 Smart-Router 模块。
或者修改为`GAE-Proxy自动切换`模式，能否看见 UI 我不清楚，因为没有用这个。

**Comment by whytakemyname** [comment]
昨天就用的Windows版的bak文件，但是不行。你的可以。十分感谢。赞！！

**Comment by whytakemyname** [comment]
我的可以上网，但是软件不能设置。
![tim 20180821170328](https://user-images.githubusercontent.com/34732308/44392212-42c01f80-a564-11e8-8bfe-02900fd1dfd7.jpg)
