### ISSUE TITLE
Windows10，显示无法访问 127.0.0.1

### ISSUE THREAD

**Issue by catast-hf** [XX-net/XX-Net#11332]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
Windows10，xx-net页面无法打开，显示

>无法访问此网站 
127.0.0.1 的响应时间过长。 
请试试以下办法：  
检查网络连接 
检查代理服务器和防火墙 
运行 Windows 网络诊断 ERR_CONNECTION_TIMED_OUT。

尝试了许多方法，但是还是没能解决，希望能得到各位大神的帮助，谢谢！

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/11316#issuecomment-414039402

**Comment by a1798636524** [comment]
楼主找到办法了吗，我的也是这样

**Comment by serverLua** [comment]
用localhost代替一下试试？

**Comment by AnyWAT** [comment]
莫非浏览器代理扩展图标上出现（未加载资源）数字，其内包括了127.0.0.1？走“直接连接”😜

**Comment by a1798636524** [comment]
不行，这三种方法都试过了

**Comment by a1798636524** [comment]
@AnyWAT 大神，该怎么办

**Comment by AnyWAT** [comment]
重启浏览器或电脑？

**Comment by catast-hf** [comment]
这些办法都试过了，都不行，另外您之前说的localhost，出现如下情况，我按照网上的教程修复，无法修复，请教一下如何解决。

正在 Ping DESKTOP-K7oR5258 [::1] 具有 32 字节的数据:
一般故障。
一般故障。
一般故障。
一般故障。

::1 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)@AnyWAT

**Comment by AnyWAT** [comment]
另外您之前说的localhost——拉郎配😜

**Comment by catast-hf** [comment]
不好意思，没搞懂您的意思。

**Comment by AnyWAT** [comment]
😝爬楼，到底是谁说的。。。
本地无法打开localhost或127.0.1解决方案 - CSDN博客 https://blog.csdn.net/qq_35168386/article/details/61416842

**Comment by catast-hf** [comment]
能帮忙解决一下localhost问题？谢谢 @AnyWAT

**Comment by catast-hf** [comment]
好的，谢谢，我试试

**Comment by catast-hf** [comment]
localhost解决了，但是xx-net还是无法访问此网站，显示的是：
localhost 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

> @AnyWAT 大神，如何解决！都要被这个给搞疯了

**Comment by AnyWAT** [comment]
貌似启用了代理的浏览器，在代理未到某地步时的反应，再开一个XX-Net（挤出貌似已吧正常的）

**Comment by binbin000** [comment]
https://github.com/XX-net/XX-Net/issues/10881#issuecomment-394632759

**Comment by a1798636524** [comment]
我的谷歌chrome只有一条而且启用了

**Comment by AnyWAT** [comment]
笨法：关闭浏览器、退出XX-Net，重置防火墙，运行XX-Net，弹出窗口放行？

**Comment by AnyWAT** [comment]
任务管理器——性能——打开资源监视器——
![default](https://user-images.githubusercontent.com/37962734/44666487-18320300-aa4b-11e8-8e18-6ca73eddddca.png)

**Comment by AnyWAT** [comment]
😱小鬼再次来袭：（未启动浏览器）开启XX-Net 后不见托盘图标，不见 53/8085/8086
![image](https://user-images.githubusercontent.com/37962734/44892010-0daa8e80-ad15-11e8-806c-93afde4c7538.png)

**Comment by xxnet** [comment]
遇到这种情况，可以看看 data/launcher/launcher.log日志有什么线索

**Comment by SeaHOH** [comment]
看不出原因，经常遇到，重启就好。
只是因为我测试时启动次数太多。

**Comment by xxnet** [comment]
有时是原来的进程没有退出，会占用端口

**Comment by ccitt** [comment]
控制面板->系统和安全->Windows Defender 防火墙->"允许应用通过Windows Defender 防火墙进行通讯"->"把pythonw那项都打上√后，点击右上角更改设置"即可。

**Comment by AnyWAT** [comment]
有贴图的2楼，完全与防火墙无关：正常前后没动防火墙设置😂

**Comment by AnyWAT** [comment]
因证书文件关系，不在同一目录下的3.8.5正常
![image](https://user-images.githubusercontent.com/37962734/46899306-45842480-cec4-11e8-84b8-28085a473b25.png)
