### ISSUE TITLE
无法访问外网，显示602:ip not support GAE，600错误。

### ISSUE THREAD

**Issue by whytakemyname** [XX-net/XX-Net#11335]
软件是最新版本，软件状态正常。
重启过软件，试过其他连接（代理）方式，都不行
问题如图：
谷歌和youtube和其他所有外网都是如图中所示
无法发图，文字粘贴吧。
600:gae_exception:'602:ip not support GAE' https://www.google.com/?gl=us&hl=en&gws_rd=cr,ssl&pws=0gae_exception:'602:ip not support GAE' https://www.google.com/?gl=us&hl=en&gws_rd=cr,ssl&pws=0gae_exception:'602:ip not support GAE' https://www.google.com/?gl=us&hl=en&gws_rd=cr,ssl&pws=0

GAEProxy 状态信息
XX-Net 3.12.11，一切正常，你可以访问真正的互联网了。
属性  |  值

IPv4 状态 | OK
IPv6 状态 | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 99
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 573
连接池(帮助) | 新:0 h1:1 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 4

诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:95
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:3 h2:0
scan-ip-thread-num: 9
ip-quality: 574
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
求大神解答
@SeaHOH

**Comment by AnyWAT** [comment]
连接池太小、IP延时太大的锅？检查IP。。。 #11291

**Comment by AnyWAT** [comment]
随时修正的结果🤣
![default](https://user-images.githubusercontent.com/37962734/44307608-af59e380-a3d7-11e8-8cc1-ef1970fb4e5b.png)
![default](https://user-images.githubusercontent.com/37962734/44307583-39ee1300-a3d7-11e8-87ea-4842b570a90c.png)

**Comment by whytakemyname** [comment]
设置
 IP 最大扫描线程数为 150
自动调整扫描线程数 关闭
连接接收缓冲大小 384，级别为正常
检查ip为
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 150
ip-quality: 252
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
故障依旧，无法连接外网。个人感觉“602ip not support GAE”，应该是和gae有关，但是没学过相关知识，不知道如何操作

**Comment by AnyWAT** [comment]
当然，除了 #11291 还有参考 #10184
仔细推敲带黄色划线那图文字。。。
个人感觉“602ip not support GAE”，应该是和gae有关——不识码的几次经历，就是连接池太小、IP延时太大的锅🤣

**Comment by whytakemyname** [comment]
谢谢关注。
是自己的appid，但是至于服务端版本次就不知道了。是今天刚建的，想必是最新版。另外黄字我看了好几遍。主要包括：检查ip，调大最大扫描线程数，关闭自动调整扫描线程数，调大连接接收缓冲大小 。目的是为了减少延时。不知道我遗漏了哪些。另外，我感觉延时的话可能就是加载慢些，但是我这个打开之后5秒内必定出现602错误。过程中没有任何一般网卡是的文字显现慢的情况，延时大概250左右。连接池这个概念就不很明白了。麻烦了

**Comment by AnyWAT** [comment]
带黄色划线那图所有文字。。。
![default](https://user-images.githubusercontent.com/37962734/44308017-0e235b00-a3e0-11e8-82a8-212c0fde8ced.png)

**Comment by AnyWAT** [comment]
连接池这个概念就不很明白了——鄙人也不明白，但会观察检查IP前后的各参数变化🙃

**Comment by whytakemyname** [comment]
不明白你要表达什么
连接池   新:1 h1:1 h2:0
参数变化我也看了，不过除了上面的改动外其他的我也不会设置，无奈。
连接池后的“帮助”连概念也没解释太清，不过倒是算懂了

**Comment by AnyWAT** [comment]
A：如此这般确实较好，至少比B的情况妙
B：会怎做？
![default](https://user-images.githubusercontent.com/37962734/44308402-a83ad180-a3e7-11e8-95df-abf9ba564e0d.png)
🤣不过除了上面的改动外其他的我也不会设置，无奈——推敲前述 #10184

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11287#issuecomment-414047755

**Comment by whytakemyname** [comment]
好的，谢谢你了。看看其他人有解决方式没吧，昨天摆弄了一下午也没成功，就浪费在这个问题上了。

**Comment by AnyWAT** [comment]
😝再说得3岁孩都明白：参考 https://github.com/XX-net/XX-Net/issues/11287#issuecomment-414047755 及 #10184 ，后者的2、项你的做法。。。

**Comment by whytakemyname** [comment]
改DNS 
该注册表项
取消勾选 IPv6 协议
开启ipv4ipv6转换。还有上面我试过的方法均无效。
文章中的方法很乱，费劲才看懂，另外你的回复也很不清晰，语句略有不通，只能猜测。不管怎么样还是谢谢了。看文章加自己试又花了两个小时，唉

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

**Comment by whytakemyname** [comment]
搜索了所有出现这种状况的贴子，全部都没有得到解决。如果出现了这种问题，请卸载重装，如问题依旧，可以考虑直接放弃。给出这条建议，只当是为了后来的人造福，不要像我一样浪费时间了。这种问题的帖子（包括谷歌，百度及本站）大概近二十个（从16年以来），只有一个是重装解决了，其余的和我一样试过各种办法均未解决（我是试过办法最多的）；我试过的方法如上面那位的回答及我的回答所述。若仍有不屈不挠者，建议尝试其他方法。

**Comment by AnyWAT** [comment]
搜索了所有出现这种状况的贴子，全部都没有得到解决。——如果最后是别人的解决建议，贴主不再回复，一般认为不是🆗只是没后话了？😜
我试过的方法。。。貌似 #10184 😂
![default](https://user-images.githubusercontent.com/37962734/44322974-7460ba00-a482-11e8-9769-a5d7793df477.png)

**Comment by whytakemyname** [comment]
不是，主要没学过编程，里面的步骤看不懂。其实看不懂倒没什么，主要是文章条理不够清晰，很晦涩。我按照里面的方法操作的，虽然并不懂什么意思，但保证操作是无误的，问题的确没有解决。花了一个下午加半个上午的确是浪费时间。当然了，确实花了时间还没找对地方。所以建议碰到这种问题的直接重装，不要再琢磨了，这也是前车之鉴，并无恶意。当然，想彻底解决的自然可以多下些功夫，但一般人来的话有违效率。最后感谢你的帮助，自己涉猎不足，难以解决，实属无奈。

**Comment by AnyWAT** [comment]
😂成十上百的用户貌似只有几个，你乃其一。。。

**Comment by SeaHOH** [comment]
那啥，上面这位确实表达不清晰，不过他精力实在太好，而且某些时候也能点到要点（虽然看起来很乱）。

还有，我也不是啥创始。

最后再问下，你的问题解决了吗？

**Comment by AnyWAT** [comment]
纯粹不识码的老白“剽窃”他人、总结经验，又非著书立说，更别说成十上百的用户貌似只有几个（一位数？）🤣

**Comment by SeaHOH** [comment]
没看出来吗？我现在已经不直接吐槽你了，只是在跟 whytakemyname 交流而已。

**Comment by whytakemyname** [comment]
问题解决了，我卸载重装了。
注意：插件要卸载
软件要卸载
上面两个卸载之后用ccleaner彻底清理一遍（不清理可能重装之后也没用）
关机（不建议重启电脑）
开机并正常安装软件
成功！
我看到的同样问题里anywat都有参与回答，个人感觉其答案和602：ip不支持gae这个问题没什么关联（妄自揣度，不过其热心可鉴）。但是似乎大家都没有得到解决。可能都不得其要领。
另外能碰到这个问题真的惨啊。
重申：建议重装，仍失败建议放弃！或试用seahoh的办法（我未试）

**Comment by AnyWAT** [comment]
非清晰表达：插件要卸载——插件多了去😂
经验，遇见过才有。
![default](https://user-images.githubusercontent.com/37962734/44326257-a9bed500-a48d-11e8-9f3e-7cb3173b4283.png)
随即自己解决😂

**Comment by AnyWAT** [comment]
删除 data/gae_proxy/good_ip.txt 的实质貌似与检查IP相当？

**Comment by SeaHOH** [comment]
@AnyWAT 既然问了，我就再解释下。
1. 分段，不要各种操作描述写到一堆，显得没有条理。
1. 不要使用你自己发明的缩写替代操作描述，别人看不懂。
1. 确定你的回答和提问相关，不浪费大家的精力。
1. 表情符号不要泛滥，没人会准确理解你要表达的情绪。

**Comment by SeaHOH** [comment]
> 删除 data/gae_proxy/good_ip.txt 的实质貌似与检查IP相当？

道理一样，但具体操作后，结果可能不同，直接删除更保险。

**Comment by AnyWAT** [comment]
结果可能不同认可，也许更彻底
1、2、不接受，除非有截图明证：。。。何况成十上（数？）百。。。

**Comment by whytakemyname** [comment]
相比想必检查ip和我所想的不太一样，我用的是诊断和观察。另外板块好像设置的发图有权限？想发图发不了图。另外想借搂问一下问题的标签怎么添加。别人的都有“需要帮助”“need help"的标签（label)自己搜索教程和琢磨了半天也不会。同理还有上传图片。遇到问题一般都是自己摸索，实在不行才求助，这两个虽然简单却并不会，见笑

**Comment by AnyWAT** [comment]
上图、下载需代理，标签作为用户想太远😜

**Comment by SeaHOH** [comment]
发图无需权限。
按下`F12`切换到`网络`标签，然后把图片拖入编辑框，此时可观察到失败的网络请求。

标签是由拥有授权的用户（管理者）添加。

**Comment by whytakemyname** [comment]
原来如此，感谢两位的帮助。稍后会自己关闭问题。
