### ISSUE TITLE
SwitchyOmega这个插件突然就被chrome卸载了，重新安装提示 “已尝试对扩展程序降级”

### ISSUE THREAD

**Issue by mmz0717** [XX-net/XX-Net#11345]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
到商店安装

**Comment by mmz0717** [comment]
在扩展程序里面找不到，搜索竟然能搜到！
