### ISSUE TITLE
为什么不开xxnet不启动的时候也能科学上网？

### ISSUE THREAD

**Issue by lbgzmhl** [XX-net/XX-Net#11346]
不知道发生了什么，hosts也没问题，重新启动之后，没开xxnet照样能上google和youtube
但是anaconda镜像连不上国内的了，想取消全局代理没反应，没有对勾。。。。。。管理员运行之后，也不能改变代理方式，我想取消掉xxnet怎么弄？

**Comment by jor74092** [comment]
【测试】
把hosts备份后暂时移除，将现有ipv4的dns备份后改用114或119或223的，开机启动项除了输入法和杀毒软件外全部停用，服务中除了系统服务外只要有第三方与网络有关的服务项全部停用，重启电脑，直接开浏览器，看看还能不能直接访问google和youtube，如还能访问就说明原生ipv6起作用了。

**Comment by AnyWAT** [comment]
修改文件设置替换图标右键菜单 #11293 (comment)
