### ISSUE TITLE
问个很奇怪的问题，除了谷歌浏览器可以正常访问，其他浏览器均不能上网

### ISSUE THREAD

**Issue by uone0513** [XX-net/XX-Net#11344]
全新的系统，win10 ，装好后，所有浏览器上网都是正常的（国内网），装完xxnet，问题来了，除了谷歌可以访问浏览国内网，其他浏览器全部不能访问国内网站，本人xxnet和相关翻墙插件的使用和配置没问题，用了很多次，这是第一次碰到这种情况，必须全局代理，才能正常访问，照理国内的不用使用代理，直接连接就行，ie，edge，火狐，都不行，相关的什么代理设置，去掉勾选啊，自动检测代理啊，这种设置，已经开关无数次了，各种设置都试过，都不行。然后，关闭xxnet也不行，感觉是第一次启动xxnet后是不是修改了系统哪里的设置，不知道大家有无遇到过这种情况，我本人也是第一次遇到，晕死，折腾了几天了

**Comment by uone0513** [comment]
![qq 20180822145158](https://user-images.githubusercontent.com/32754032/44447568-2df29300-a61b-11e8-8a40-d9185b2408b7.png)
而且这个代理设置的各种可能性我全部试过了，上下全部勾选，只勾选上面的，或者只勾选下面，全部不勾选，都试过了……

**Comment by SeaHOH** [comment]
没使用过 Win10，不过我看别人的设置是这样的，你这个跟 Win7 一个样，是不是还要进行以下设置？
![](https://user-images.githubusercontent.com/38067374/39720698-cd752852-526f-11e8-9d57-ec685c13855e.PNG)

**Comment by AnyWAT** [comment]
😝同一设置在IE与系统位置的不同尔尔

**Comment by uone0513** [comment]
@SeaHOH 所有的我可以尝试的设置选项，全部试过，包括您上面的截图状态，不过还是谢谢您的热心解答！

**Comment by SeaHOH** [comment]
突然想起还没检查防火墙

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by AnyWAT** [comment]
貌似今天Windows10更新到了1809/17754.1
