### ISSUE TITLE
Windows 原生 IPv6 经常断线，重启后恢复

### ISSUE THREAD

**Issue by lindenbroom** [XX-net/XX-Net#11343]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
最新版 3.12.11

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
看过，没解决问题

* 是否以相关关键词搜索过类似 issues？
搜索过，没解决

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

有原生ipv6，xxnet可以正常工作，但上网一段时间后ipv6就断线了，导致xxnet提示： "仅 IPv6" 不可用，请检查。

Teredo 隧道状态是 “休眠（未连接）”

更换Teredo服务器， 结果是 “no server detected, return default: teredo.remlab.net.”

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
正常使用时，`休眠`会自动恢复服务器连接。
你这个是休眠时刚好遇到了无法连接服务器的情况。
可以等一会儿看能否恢复，或者尝试重新拨号并更换服务器。

**Comment by lindenbroom** [comment]
@SeaHOH 谢谢
我用的是原生ipv6，把Teredo隧道禁用了xxnet也能上网

ipv6断线后，运行code\default\gae_proxy\local\ipv6_tunnel文件夹下的enable_ipv6.bat
启用 Teredo 隧道，到现在几个小时了一直是休眠状态（把xxnet退出重启也一样）：
netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by lindenbroom** [comment]
@SeaHOH 
不好意思，我可能没说清楚
原生ipv6用一会儿就断线（不知道什么原因，重启电脑又可以用了），所以我还是想在原生ipv6断线时切换到teredo隧道，可是Teredo一直是休眠状态，更换服务器时提示 “no server detected, return default: teredo.remlab.net.”

**Comment by SeaHOH** [comment]
使用测试按钮，如果不同时间，多次测试结果都不通过，就证明你的网络无法连接 teredo 服务器。

另，你所谓原生 IPv6 是指 ISP 分配给你的吗？
这种一般是不会断线的，可以通过 ping  IPv6 地址来测试。
故障可以报修。

**Comment by lindenbroom** [comment]
谢谢，那可能是我网络无法连接 teredo 服务器 :-(
IPv6是公司内网自动获取的（设置的自动获取ipv6地址和dns服务器地址，也同时开了ipv4），
用这个网站测试的 http://test-ipv6.com/，时好时坏，ipv6断了重启电脑后又能连

**Comment by SeaHOH** [comment]
> 故障可以报修

**Comment by ablebodied** [comment]
我这里也是 原生ipv6 经常断开，网管说是win10的问题，用Ubuntu貌似确实是没啥问题，也是无语了
