### ISSUE TITLE
600:gae_exception:'600:fetch gae fail'

### ISSUE THREAD

**Issue by DaisyLoveU** [XX-net/XX-Net#11349]
XX-Net 3.12.11，一切正常，你可以访问真正的互联网了。  
希望大佬帮帮忙呢！ 问题可能主要是，我下载了idm绿色版，点击了绿化，成功后，就科学上网失败了
但是打开https://www.youtube.com/后，界面是这样滴：  
600:gae_exception:'600:fetch gae fail' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/  

双击xx-net.exe后，在X-Tunel配置页面，一直处于正在登录中...

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:1 h2:0
scan-ip-thread-num: 10
ip-quality: 399
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

Cloudflare前端 日志：
Aug 23 10:29:48.357 - [INFO] load E:\google_ee\XX-Net-master\XX-Net-master\data\x_tunnel\cloudflare_domains.json success

Aug 23 10:29:48.357 - [INFO] SSL use version:TLSv1_2

Aug 23 10:29:48.357 - [INFO] OpenSSL support alpn

Aug 23 10:29:48.357 - [INFO] load ip range file:E:\google_ee\XX-Net-master\XX-Net-master\code\3.12.11\x_tunnel\local\cloudflare_front\ip_range.txt

Aug 23 10:29:48.357 - [INFO] load ip_list num:50, target num:50

Aug 23 10:29:54.762 - [DEBUG] report_connect_fail:104.17.91.235

Aug 23 10:29:54.762 - [DEBUG] connect 104.17.91.235 fail:error('certificate is none, sni:mcareview.ga',)

Aug 23 10:30:02.166 - [DEBUG] report_connect_fail:104.25.143.174

Aug 23 10:30:02.166 - [DEBUG] connect 104.25.143.174 fail:error('certificate is none, sni:trustedcasementwindows.com',)

Aug 23 10:30:09.436 - [DEBUG] report_connect_fail:190.93.247.85

Aug 23 10:30:09.436 - [DEBUG] connect 190.93.247.85 fail:error('certificate is none, sni:growbitonline.com',)

Aug 23 10:30:12.746 - [DEBUG] create_ssl update ip:104.25.64.230 time:1275 h2:1 sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:35.439 - [WARNING] task POST center.xx-net.net /login timeout

Aug 23 10:30:35.439 - [WARNING] req /login get response timeout

Aug 23 10:30:35.627 - [WARNING] h2 timeout 104.25.64.230 task_trace:0:start_request,0:get_task(41),0:get_worker(0):104.25.64.230,0:h2_req,2:start send header,0:start send left body,0:end send left body,5074:get_response,:188 worker_trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:35.627 - [WARNING] POST center.xx-net.net/login response_fail:timeout

Aug 23 10:30:36.628 - [WARNING] h2 timeout 104.25.64.230 task_trace:0:start_request,0:get_task(41),0:get_worker(0):104.25.64.230,0:h2_req,2:start send header,0:start send left body,0:end send left body,5074:get_response,188:timeout,:1000 worker_trace: continue_timeout:1, processed:0, h2.stream_num:1, sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:37.631 - [WARNING] h2 timeout 104.25.64.230 task_trace:0:start_request,0:get_task(41),0:get_worker(0):104.25.64.230,0:h2_req,2:start send header,0:start send left body,0:end send left body,5074:get_response,188:timeout,1000:timeout,:1003 worker_trace: continue_timeout:2, processed:0, h2.stream_num:2, sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:38.632 - [WARNING] h2 timeout 104.25.64.230 task_trace:0:start_request,0:get_task(41),0:get_worker(0):104.25.64.230,0:h2_req,2:start send header,0:start send left body,0:end send left body,5074:get_response,188:timeout,1000:timeout,1003:timeout,:1000 worker_trace: continue_timeout:3, processed:0, h2.stream_num:2, sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:39.634 - [WARNING] h2 timeout 104.25.64.230 task_trace:0:start_request,0:get_task(41),0:get_worker(0):104.25.64.230,0:h2_req,2:start send header,0:start send left body,0:end send left body,5074:get_response,188:timeout,1000:timeout,1003:timeout,1000:timeout,:1002 worker_trace: continue_timeout:4, processed:0, h2.stream_num:2, sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:40.634 - [WARNING] h2 timeout 104.25.64.230 task_trace:0:start_request,0:get_task(41),0:get_worker(0):104.25.64.230,0:h2_req,2:start send header,0:start send left body,0:end send left body,5074:get_response,188:timeout,1000:timeout,1003:timeout,1000:timeout,1002:timeout,:1000 worker_trace: continue_timeout:5, processed:0, h2.stream_num:2, sni:switchsitiosweb.com, host:movistar.gq

Aug 23 10:30:40.634 - [WARNING] retry_task_cb: POST center.xx-net.net/login

Aug 23 10:30:40.636 - [DEBUG] 104.25.64.230 _consume_single_frame:ConnectionResetError(), inactive time:27

Aug 23 10:30:40.637 - [DEBUG] 104.25.64.230 worker close:active timeout

Aug 23 10:30:40.637 - [DEBUG] 104.25.64.230 worker close:ConnectionReset:ConnectionResetError()

Aug 23 10:30:42.484 - [WARNING] task POST center.xx-net.net /login timeout

Aug 23 10:30:42.484 - [WARNING] req /login get response timeout

Aug 23 10:30:46.740 - [DEBUG] report_connect_fail:104.25.64.230

Aug 23 10:30:46.740 - [DEBUG] connect 104.25.64.230 fail:error("conn fail, sni:oienfamilychiropractic.com, top:movistar.gq e:timeout('timed out',)",)

Aug 23 10:30:54.074 - [DEBUG] report_connect_fail:104.20.163.91

Aug 23 10:30:54.074 - [DEBUG] connect 104.20.163.91 fail:error('certificate is none, sni:annuiities.tk',)

Aug 23 10:31:01.403 - [DEBUG] report_connect_fail:162.159.132.33

Aug 23 10:31:01.403 - [DEBUG] connect 162.159.132.33 fail:error('certificate is none, sni:vilvulei.com',)

Aug 23 10:31:08.738 - [DEBUG] report_connect_fail:141.101.113.106

Aug 23 10:31:08.738 - [DEBUG] connect 141.101.113.106 fail:error('certificate is none, sni:coaerse.ga',)

Aug 23 10:31:16.083 - [DEBUG] report_connect_fail:104.23.98.18

Aug 23 10:31:16.083 - [DEBUG] connect 104.23.98.18 fail:error('certificate is none, sni:jualautoclave.com',)

Aug 23 10:31:23.361 - [DEBUG] report_connect_fail:104.18.213.60

Aug 23 10:31:23.361 - [DEBUG] connect 104.18.213.60 fail:error('certificate is none, sni:absolutewhores.com',)

Aug 23 10:31:30.395 - [DEBUG] report_connect_fail:141.101.114.215

Aug 23 10:31:30.395 - [DEBUG] connect 141.101.114.215 fail:error("conn fail, sni:glsservices.ca, top:tangg.tk e:timeout('timed out',)",)

Aug 23 10:31:37.714 - [DEBUG] report_connect_fail:141.101.113.225

Aug 23 10:31:37.714 - [DEBUG] connect 141.101.113.225 fail:error('certificate is none, sni:switchsitiosweb.com',)

Aug 23 10:31:42.028 - [DEBUG] create ssl timeout fail.

Aug 23 10:31:46.044 - [DEBUG] report_connect_fail:172.64.50.59

Aug 23 10:31:46.044 - [DEBUG] connect 172.64.50.59 fail:error('certificate is none, sni:studentbay.online',)

Aug 23 10:31:53.238 - [DEBUG] report_connect_fail:190.93.244.94

Aug 23 10:31:53.238 - [DEBUG] connect 190.93.244.94 fail:error('certificate is none, sni:nationalsfanaticsjersey.com',)

Aug 23 10:32:00.410 - [DEBUG] report_connect_fail:190.93.247.123

Aug 23 10:32:00.411 - [DEBUG] connect 190.93.247.123 fail:error('certificate is none, sni:365bootstrap.com',)

Aug 23 10:32:07.743 - [DEBUG] report_connect_fail:104.19.128.160

Aug 23 10:32:07.743 - [DEBUG] connect 104.19.128.160 fail:error('certificate is none, sni:notariax.com',)

Aug 23 10:32:15.036 - [DEBUG] report_connect_fail:141.101.114.208

Aug 23 10:32:15.037 - [DEBUG] connect 141.101.114.208 fail:error('certificate is none, sni:growbitonline.com',)

Aug 23 10:32:22.305 - [DEBUG] report_connect_fail:104.16.55.95

Aug 23 10:32:22.305 - [DEBUG] connect 104.16.55.95 fail:error('certificate is none, sni:removie.gq',)

Aug 23 10:32:29.321 - [DEBUG] report_connect_fail:104.16.172.76

Aug 23 10:32:29.321 - [DEBUG] connect 104.16.172.76 fail:error("conn fail, sni:phoom.in.th, top:xxxooo.gq e:timeout('timed out',)",)

Aug 23 10:32:36.502 - [DEBUG] report_connect_fail:190.93.244.171

Aug 23 10:32:36.503 - [DEBUG] connect 190.93.244.171 fail:error('certificate is none, sni:spankysteens.com',)

Cloudfront前端 日志：
Aug 23 10:29:48.357 - [INFO] SSL use version:TLSv1_2

Aug 23 10:29:48.373 - [INFO] OpenSSL support alpn

Aug 23 10:29:48.373 - [INFO] load ip range file:E:\google_ee\XX-Net-master\XX-Net-master\code\3.12.11\x_tunnel\local\cloudfront_front\ip_range.txt

Aug 23 10:29:48.373 - [INFO] load ip_list num:100, target num:100

Aug 23 10:29:54.824 - [DEBUG] create_ssl update ip:52.85.186.202 time:5377 h2:0 sni:dpstvy7p9whsy.cloudfront.net, host:

Aug 23 10:30:02.166 - [WARNING] task POST center.xx-net.net /login timeout

Aug 23 10:30:02.166 - [WARNING] req /login get response timeout

Aug 23 10:30:09.576 - [DEBUG] report_connect_fail:52.222.250.198

Aug 23 10:30:09.576 - [DEBUG] connect 52.222.250.198 fail:error(' certificate is none, sni:tracking-protection.cdn.mozilla.net',)

Aug 23 10:30:18.019 - [DEBUG] report_connect_fail:52.84.98.224

Aug 23 10:30:18.019 - [DEBUG] connect 52.84.98.224 fail:error(' certificate is none, sni:d1bxh8uas1mnw7.cloudfront.net',)

Aug 23 10:30:19.944 - [WARNING] 52.85.186.202 h1_request:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],) inactive_time:30 task.timeout:5

Aug 23 10:30:19.944 - [WARNING] 52.85.186.202 trace: 0:connect, 5408:init, 2241:request,:22862, processed:0, transfered:0, sni:dpstvy7p9whsy.cloudfront.net

Aug 23 10:30:19.945 - [WARNING] retry_task_cb: POST center.xx-net.net/login

Aug 23 10:30:19.945 - [WARNING] POST center.xx-net.net/login response_fail:retry timeout:22

Aug 23 10:30:19.945 - [DEBUG] 52.85.186.202 worker close:down fail

Aug 23 10:30:20.949 - [DEBUG] 52.85.186.202 worker close:exit

Aug 23 10:30:25.320 - [DEBUG] report_connect_fail:54.182.3.236

Aug 23 10:30:25.320 - [DEBUG] connect 54.182.3.236 fail:error(' certificate is none, sni:z-na.amazon-adsystem.com',)

Aug 23 10:30:27.616 - [DEBUG] report_connect_fail:54.192.156.130

Aug 23 10:30:27.616 - [DEBUG] connect 54.192.156.130 fail:error('check sni:ib.3lift.com fail, alt_names:()',)

Aug 23 10:30:34.937 - [DEBUG] report_connect_fail:54.239.168.30

Aug 23 10:30:34.937 - [DEBUG] connect 54.239.168.30 fail:error(' certificate is none, sni:firefoxusercontent.com',)

Aug 23 10:30:42.263 - [DEBUG] report_connect_fail:13.33.136.237

Aug 23 10:30:42.263 - [DEBUG] connect 13.33.136.237 fail:error(' certificate is none, sni:hello.myfonts.net',)

Aug 23 10:30:49.630 - [DEBUG] report_connect_fail:54.239.223.124

Aug 23 10:30:49.630 - [DEBUG] connect 54.239.223.124 fail:error(' certificate is none, sni:d6tizftlrpuof.cloudfront.net',)

Aug 23 10:30:58.115 - [DEBUG] report_connect_fail:54.239.221.183

Aug 23 10:30:58.115 - [DEBUG] connect 54.239.221.183 fail:error(' certificate is none, sni:cdn.heapanalytics.com',)

Aug 23 10:31:04.478 - [DEBUG] create ssl timeout fail.

Aug 23 10:31:05.544 - [DEBUG] report_connect_fail:54.230.53.209

Aug 23 10:31:05.544 - [DEBUG] connect 54.230.53.209 fail:error(' certificate is none, sni:segments.company-target.com',)

Aug 23 10:31:12.907 - [DEBUG] report_connect_fail:52.85.205.250

Aug 23 10:31:12.907 - [DEBUG] connect 52.85.205.250 fail:error(' certificate is none, sni:www.amazon.fr',)

Aug 23 10:31:20.315 - [DEBUG] report_connect_fail:54.192.15.87

Aug 23 10:31:20.315 - [DEBUG] connect 54.192.15.87 fail:error(' certificate is none, sni:addons-amo.cdn.mozilla.net',)

Aug 23 10:31:27.523 - [DEBUG] report_connect_fail:52.222.254.41

Aug 23 10:31:27.523 - [DEBUG] connect 52.222.254.41 fail:error(' certificate is none, sni:widget.intercom.io',)

Aug 23 10:31:34.548 - [DEBUG] report_connect_fail:54.239.221.234

Aug 23 10:31:34.548 - [DEBUG] connect 54.239.221.234 fail:error("conn fail, sni:cdn.segment.com, top: e:timeout('timed out',)",)

Aug 23 10:31:44.961 - [DEBUG] report_connect_fail:13.33.37.53

Aug 23 10:31:44.961 - [DEBUG] connect 13.33.37.53 fail:error(' certificate is none, sni:d301sr5gafysq2.cloudfront.net',)

Aug 23 10:31:52.411 - [DEBUG] report_connect_fail:54.240.190.18

Aug 23 10:31:52.411 - [DEBUG] connect 54.240.190.18 fail:error(' certificate is none, sni:api.demandbase.com',)

Aug 23 10:32:02.607 - [DEBUG] report_connect_fail:13.33.186.188

Aug 23 10:32:02.607 - [DEBUG] connect 13.33.186.188 fail:error(' certificate is none, sni:content-signature.cdn.mozilla.net',)

Aug 23 10:32:05.220 - [DEBUG] create ssl timeout fail.

Aug 23 10:32:10.227 - [DEBUG] report_connect_fail:54.239.223.103

Aug 23 10:32:10.227 - [DEBUG] connect 54.239.223.103 fail:error(' certificate is none, sni:www.stack-sonar.com',)

Heroku前端 日志：
Aug 23 10:29:48.389 - [INFO] SSL use version:TLSv1_2

Aug 23 10:29:48.404 - [INFO] OpenSSL support alpn

Aug 23 10:29:48.404 - [INFO] load ip_list num:75, target num:75

TLS-Relay前端 日志：
Aug 23 10:29:48.389 - [INFO] SSL use version:TLSv1_2

Aug 23 10:29:48.389 - [INFO] OpenSSL support alpn

Aug 23 10:29:50.432 - [WARNING] not enough ip

Aug 23 10:30:01.444 - [WARNING] not enough ip

Aug 23 10:30:12.467 - [WARNING] not enough ip

Aug 23 10:30:23.484 - [WARNING] not enough ip

Aug 23 10:30:34.502 - [WARNING] not enough ip

Aug 23 10:30:45.518 - [WARNING] not enough ip

Aug 23 10:30:49.676 - [DEBUG] create ssl timeout fail.

Aug 23 10:30:56.529 - [WARNING] not enough ip

Aug 23 10:31:07.546 - [WARNING] not enough ip

Aug 23 10:31:18.555 - [WARNING] not enough ip

Aug 23 10:31:29.567 - [WARNING] not enough ip

Aug 23 10:31:40.581 - [WARNING] not enough ip

Aug 23 10:31:50.831 - [DEBUG] create ssl timeout fail.

Aug 23 10:31:51.582 - [WARNING] not enough ip

Aug 23 10:32:02.594 - [WARNING] not enough ip

Aug 23 10:32:13.601 - [WARNING] not enough ip

Aug 23 10:32:24.604 - [WARNING] not enough ip

Aug 23 10:32:35.605 - [WARNING] not enough ip

Aug 23 10:32:46.615 - [WARNING] not enough ip

Aug 23 10:32:51.616 - [DEBUG] create ssl timeout fail.

**Comment by SeaHOH** [comment]
> 双击xx-net.exe后

本仓库发布的版本没有此文件，请检查是否包含木马或病毒。

**Comment by AnyWAT** [comment]
600:gae_exception:'600:fetch gae fail' ——9成9是连接池太小的锅
双击xx-net.exe后——不会是操作系统默认的资源管理器“隐藏文件后缀”的自我发挥（自以为是 .exe？）
在X-Tunel配置页面，一直处于正在登录中...——在GAE等前端未正常前的正常反应
scan-ip-thread-num: 10 ——或适当增大后检查IP（观察检查前后连接池的变化）
Appids_Out_Of_Quota: true ——至少有AppID的流量玩完
