### ISSUE TITLE
在每次重启电脑后，IPV6都要显示不可用（正常先关机再开机没问题，但是只要选择了“重新启动”，就会出这样的问题）

### ISSUE THREAD

**Issue by WBinyv** [XX-net/XX-Net#11341]
在每次重启电脑后，IPV6都要显示不可用（正常先关机再开机没问题，但是只要选择了“重新启动”，就会出这样的问题）

**Comment by SeaHOH** [comment]
是否由电脑拨号？
什么设备和系统？
重新启动后，teredo 是什么状态？

    Windows 运行命令 `netsh interface ipv6 show teredo`
    Miredo 运行命令`sudo systemctl status miredo.service`

**Comment by WBinyv** [comment]
连接的wifi
windows10 dell xps 15（笔记本）

**Comment by WBinyv** [comment]
Teredo Parameters
---------------------------------------------
Type                    : disabled
Server Name             : win1710.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : offline
Error                   : none

**Comment by WBinyv** [comment]
显示的是
"Force-IPv6" not available, Please check.

**Comment by WBinyv** [comment]
我就在昨天重装了一次系统，但还是有这个问题

**Comment by SeaHOH** [comment]
估计你的系统有问题，只能每次出现`Type : disabled`时按以下方法开启隧道。
在网页界面`高级` `IPv6 隧道`执行`切换服务器`。

**Comment by WBinyv** [comment]
不行啊，没用
我的系统是dell官方下载的，应该没问题。
我目前只找到了一种解决这个问题的方法，就是在try repair中选择enable ，再重启（现在可以直接重启），就正常了。

大佬我还有个问题，就是switchy omega 如何调出“外部情景模式”？以前可以，但现在就算代理被侵占了也不行（它教程是这么写的）求大佬帮助

**Comment by WBinyv** [comment]
他不会变啊，会一直显示"Force-IPv6" not available, Please check.

**Comment by AnyWAT** [comment]
Type : disabled
Server Name : win1710.ipv6.microsoft.com. ——关闭浏览器、退出XX-Net，管理权限运行
netsh int ipv6 set teredo enterpriseclient default

**Comment by AnyWAT** [comment]
（开机）启动XX-Net 前即运行以下 bat（批处理内容）可观察变化过程，状态 dormant 即已开始正常化，（随时运行，凭此判断是隧道还是XX-Net 的问题，最佳）启动XX-Net 数秒隧道即可正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by WBinyv** [comment]
当xx-net不可用时，显示的
C:\Users\WBinyv\Desktop>goto loop

C:\Users\WBinyv\Desktop>netsh int teredo show state
Teredo Parameters
---------------------------------------------
Type                    : disabled
Server Name             : win1711.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : offline
Error                   : none

**Comment by AnyWAT** [comment]
#10184 确保2注册表项及系统服务IP Helper、Ipv6 自动转换？

**Comment by gdsteven** [comment]
直接管理员命令行执行
net stop iphlpsvc
net start iphlpsvc

这种现象时不时都会发生的，今天的微软已经不是以前的微软了

**Comment by AnyWAT** [comment]
（前面不识，忽略😂）ntpdate time.windows.com ——貌似 ubuntu 系统时间与 windows 时间服务器上的不一样？

**Comment by AnyWAT** [comment]
@WBinyv 同样的SwitchyOmega 2.5.20，“外部情景模式” 于Firefox、MyChrome 没有，ChromePortable 则有
