### ISSUE TITLE
这流量不科学啊。。。

### ISSUE THREAD

**Issue by templarzq** [XX-net/XX-Net#11348]
之前一直好好的，昨天突然就appid流量用光了。。啥情况
![default](https://user-images.githubusercontent.com/18200917/44500891-75c9f680-a6bd-11e8-9606-2f96c20ca87a.png)

**Comment by templarzq** [comment]
早上看还好好的，过一会就这样了。啥也没干呢
![default](https://user-images.githubusercontent.com/18200917/44500970-bcb7ec00-a6bd-11e8-96a3-9b1ac9677705.png)

**Comment by okaylabababa** [comment]
我也是 我也沒用過 但是看見負就很緊張

**Comment by SeaHOH** [comment]
关于 GAE 配额请登录[后台](https://console.cloud.google.com/)查看查看具体原因。https://github.com/XX-net/XX-Net/issues/11328#issuecomment-413770477

还有，最好更新到最新服务器端。 #10895

X-Tunnel 情况不清楚。

**Comment by SeaHOH** [comment]
关闭后仍可回复
