### ISSUE TITLE
xndroid下，手机可以正常使用youtube，浏览器浏览墙外网站，但facebook、twitter等客户端无法登录，一直是网络错误。

### ISSUE THREAD

**Issue by csqring** [XX-net/XX-Net#11351]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by cpf1972** [comment]
我的是用浏览器可以访问youtube,但YouTube的app不访问

**Comment by SeaHOH** [comment]
自己看上方 wiki，gae_proxy 有局限性，可以使用 X-Tunnel。
记得 Xndroid 首页就有说明。

**Comment by AnyWAT** [comment]
貌似比官方好用的 twitter 第三方客户端 Twidere for Twitter 正常
