### ISSUE TITLE
GAEProxy 状态正常，显示600:gae_exception:'602:ip not support GAE'，求助

### ISSUE THREAD

**Issue by DaisyLoveU** [XX-net/XX-Net#11350]
TLS-Relay前端 日志：
Aug 23 11:07:21.488 - [INFO] SSL use version:TLSv1_2
Aug 23 11:07:21.488 - [INFO] OpenSSL support alpn
Aug 23 11:07:23.567 - [WARNING] not enough ip
Aug 23 11:07:34.589 - [WARNING] not enough ip
Aug 23 11:07:45.593 - [WARNING] not enough ip
Aug 23 11:07:56.605 - [WARNING] not enough ip
Aug 23 11:08:07.621 - [WARNING] not enough ip
Aug 23 11:08:18.626 - [WARNING] not enough ip
Aug 23 11:08:22.845 - [DEBUG] create ssl timeout fail.

Aug 23 11:09:42.157 - [WARNING] not enough ip
Aug 23 11:09:53.161 - [WARNING] not enough ip
Aug 23 11:10:04.163 - [WARNING] not enough ip
Aug 23 11:10:15.176 - [WARNING] not enough ip
Aug 23 11:10:26.201 - [WARNING] not enough ip
Aug 23 11:10:37.210 - [WARNING] not enough ip
Aug 23 11:10:41.429 - [DEBUG] create ssl timeout fail.

Heroku前端 日志：
Aug 23 11:07:21.504 - [INFO] SSL use version:TLSv1_2
Aug 23 11:07:21.504 - [INFO] OpenSSL support alpn
Aug 23 11:07:21.504 - [INFO] load ip_list num:75, target num:75

Cloudfront前端 日志：
Aug 23 11:07:21.472 - [INFO] SSL use version:TLSv1_2
Aug 23 11:07:21.472 - [INFO] OpenSSL support alpn
Aug 23 11:07:21.472 - [INFO] load ip range file:E:\google_ee\XX-Net-master\XX-Net-master\code\3.12.11\x_tunnel\local\cloudfront_front\ip_range.txt
Aug 23 11:07:21.472 - [INFO] load ip_list num:100, target num:100
Aug 23 11:07:22.855 - [DEBUG] report_connect_fail:13.33.186.188
Aug 23 11:07:22.855 - [DEBUG] connect 13.33.186.188 fail:error("check sni:gwiq-v2.globalwebindex.net fail, alt_names:('mediatek.com',)",)
Aug 23 11:07:30.321 - [DEBUG] report_connect_fail:54.239.223.103
Aug 23 11:07:30.321 - [DEBUG] connect 54.239.223.103 fail:error(' certificate is none, sni:articles-images.sftcdn.net',)
Aug 23 11:07:37.807 - [DEBUG] report_connect_fail:216.137.39.228
Aug 23 11:07:37.807 - [DEBUG] connect 216.137.39.228 fail:error(' certificate is none, sni:boudja.com',)
Aug 23 11:07:45.236 - [DEBUG] report_connect_fail:52.222.253.157
Aug 23 11:07:45.236 - [DEBUG] connect 52.222.253.157 fail:error(' certificate is none, sni:shim.btrll.com',)
Aug 23 11:07:55.714 - [DEBUG] report_connect_fail:13.32.244.70
Aug 23 11:07:55.714 - [DEBUG] connect 13.32.244.70 fail:error(' certificate is none, sni:d3tglifpd8whs6.cloudfront.net',)
Aug 23 11:08:03.144 - [DEBUG] report_connect_fail:54.192.35.105
Aug 23 11:08:03.144 - [DEBUG] connect 54.192.35.105 fail:error(' certificate is none, sni:edge.api.brightcove.com',)
Aug 23 11:08:10.557 - [DEBUG] create_ssl update ip:13.33.74.158 time:5391 h2:0 sni:d2wy8f7a9ursnm.cloudfront.net, host:

Cloudflare前端 日志：
Aug 23 11:07:21.457 - [INFO] load E:\google_ee\XX-Net-master\XX-Net-master\data\x_tunnel\cloudflare_domains.json success
Aug 23 11:07:21.457 - [INFO] SSL use version:TLSv1_2
Aug 23 11:07:21.457 - [INFO] OpenSSL support alpn
Aug 23 11:07:21.457 - [INFO] load ip range file:E:\google_ee\XX-Net-master\XX-Net-master\code\3.12.11\x_tunnel\local\cloudflare_front\ip_range.txt
Aug 23 11:07:21.457 - [INFO] load ip_list num:50, target num:50
Aug 23 11:07:22.969 - [DEBUG] report_connect_fail:104.31.212.74
Aug 23 11:07:22.969 - [DEBUG] connect 104.31.212.74 fail:error("conn fail, sni:atrociaty.ga, top:book-mark.ml e:Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],)",)
Aug 23 11:07:33.393 - [DEBUG] create_ssl update ip:172.64.131.130 time:8367 h2:1 sni:charlestonbusiness.tk, host:xxxooo.gq
Aug 23 11:07:43.437 - [DEBUG] 172.64.131.130 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:18
Aug 23 11:07:43.437 - [DEBUG] 172.64.131.130 worker close:ConnectionReset:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)
Aug 23 11:07:43.438 - [DEBUG] http2 172.64.131.130 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)
Aug 23 11:07:43.438 - [DEBUG] 172.64.131.130 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)
Aug 23 11:07:50.572 - [DEBUG] report_connect_fail:172.64.131.130
Aug 23 11:07:50.572 - [DEBUG] connect 172.64.131.130 fail:error("conn fail, sni:snappmobile.net, top:mostlygood.ga e:timeout('timed out',)",)
Aug 23 11:07:57.589 - [DEBUG] report_connect_fail:104.25.31.47
Aug 23 11:07:57.589 - [DEBUG] connect 104.25.31.47 fail:error("conn fail, sni:3idstudios.com.au, top:sawfish.tk e:timeout('timed out',)",)
Aug 23 11:08:07.779 - [DEBUG] report_connect_fail:190.93.245.165
Aug 23 11:08:07.779 - [DEBUG] connect 190.93.245.165 fail:error('certificate is none, sni:cherrypieteens.com',)
Aug 23 11:08:10.488 - [DEBUG] create_ssl update ip:162.159.228.151 time:667 h2:1 sni:estafasbancarias.es, host:tangg.tk
Aug 23 11:09:41.696 - [DEBUG] POST tangg.tk/login status:200 trace:0:start_request,0:get_task(139),0:get_worker(0):162.159.228.151,0:h2_req,2:start send header,0:start send left body,0:end send left body,549:h2_get_head,0:get_response,:2

X-Tunnel 日志：
Aug 23 11:07:21.504 - [INFO] xxnet_version:3.12.11
Aug 23 11:07:21.504 - [INFO] server 127.0.0.1:1080 started.
Aug 23 11:07:21.504 - [INFO] Socks5 server listen:127.0.0.1:1080.
Aug 23 11:07:22.547 - [DEBUG] x_tunnel force update info
Aug 23 11:07:27.602 - [WARNING] get_front fail
Aug 23 11:07:33.643 - [WARNING] get_front fail
Aug 23 11:07:36.122 - [WARNING] front retry center.xx-net.net/login
Aug 23 11:07:38.605 - [WARNING] front retry center.xx-net.net/login
Aug 23 11:07:41.054 - [WARNING] front retry center.xx-net.net/login
Aug 23 11:07:44.545 - [WARNING] front retry center.xx-net.net/login
Aug 23 11:07:53.945 - [WARNING] front retry center.xx-net.net/login
Aug 23 11:07:55.949 - [WARNING] api:/login fail:status:602 t:33
Aug 23 11:09:41.140 - [DEBUG] x_tunnel force update info
Aug 23 11:09:41.697 - [INFO] api:/login success t:555
Aug 23 11:09:41.697 - [INFO] update xt_server v18.xx-net.net:443
Aug 23 11:09:41.698 - [INFO] request_balance host:v18.xx-net.net port:443 balance:0.000000 quota:499966901.000000

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 289
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

日志如上，打开youtube.com后，界面为：
600:gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/

有遇到相同情况的issue，但是下方无人解答，还请大佬们帮忙解决问题，感激聆啼

**Comment by SeaHOH** [comment]
>602:ip not support GAE

删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

X-Tunnel 可观察状态页面，可参考 #11227 关闭不能使用的前端，增加稳定性。

**Comment by DaisyLoveU** [comment]
@SeaHOH  你好，已执行操作：  
- 删除data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。
- X-Tunnel 下观察状态页面：
 （算了，发不了截图，github不知道怎么发疯，图片上传不到仓库）
 GAE 前端 socre不是False，成功数0，失败数0，工作数3
 Cloudflare 前端 socre不是False， 成功/失败/工作数：1/0/1
 Cloudfront 前端 socre不是False，成功/失败/工作数：0/0/1
 Heroku 前端/TLS_Relay 前端 score为False，成功/失败/工作数：0/0/0
 X-Tunnel日志：
 Aug 23 14:35:02.575 - [INFO] xxnet_version:3.12.11  
 Aug 23 14:35:02.577 - [INFO] server 127.0.0.1:1080 started.  
 Aug 23 14:35:02.577 - [INFO] Socks5 server listen:127.0.0.1:1080.  
 Aug 23 14:35:03.621 - [DEBUG] x_tunnel force update info  
 Aug 23 14:35:05.107 - [INFO] api:/login success t:1485  
 Aug 23 14:35:05.107 - [INFO] update xt_server v12.xx-net.net:443  
Aug 23 14:35:05.107 - [INFO] request_balance host:v12.xx-net.net port:443 balance:0.000000  quota:499883154.000000  
- 修改 data\x_tunnel\client.json 配置：  
 在json文件中添加  
 {  
  "enable_cloudflare": 0,  
  "enable_cloudfront": 0,  
  "enable_heroku": 0,  
  "enable_tls_relay": 0  
 }后，重新打开XX-net，不显示网页界面，存在pythonnw一直扫描ip  

**望大佬帮忙解决**

**Comment by SeaHOH** [comment]
没让你照搬 X-Tunnel 配置，先恢复并运行一段时间。
然后再观察哪个前端使用的流量较多，且成功数多，就保持这个前端开启，把其它关闭。

**Comment by DaisyLoveU** [comment]
@SeaHOH   竟然，让它歇了一会，自己好了。。。。。  
**让我这个门外汉被这波随缘剑法秀到了。。23333333**
  
**感谢您的热心帮助，么么哒**

**Comment by SeaHOH** [comment]
> 删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

说明这个操作已经起了作用。
