### ISSUE TITLE
4k videodownloader代理应该如何设置

### ISSUE THREAD

**Issue by ImperatorLelouch** [XX-net/XX-Net#11359]
4k videodownloader不能用ssr，按下图设置，可以解析youtube链接但下载或报错，请问各位大佬如何解决
![image](https://user-images.githubusercontent.com/11747811/44564658-c1040800-a796-11e8-9efc-425da45d69c0.png)
![image](https://user-images.githubusercontent.com/11747811/44564684-f3ae0080-a796-11e8-939c-9688f20d37bc.png)

**Comment by GoodSake** [comment]
无界试了吗，我现在下载youtube视频都是用的无界，XX-net无法下载了。。。

**Comment by ImperatorLelouch** [comment]
谢谢，不过不太想用轮子的东西

**Comment by jor74092** [comment]
用SSR的全局代理模式，不要用PAC和其他模式。
4k软件中不启用代理，这样试过吗？
或者在4k软件中使用SSR的socks5代理方式，两种方法都试试。

**Comment by InoriHimea** [comment]
下载u2b的视频？我直接用IDM的

**Comment by leywey0129** [comment]
麻烦能否用justmysocks的来做一个截图示例，详细分享下应该怎样填写，我试了很多次都不行，网上也没有具体的案例来说明如何填写！
