### ISSUE TITLE
2.5.0 WebUI 无法在其它机器上打开？

### ISSUE THREAD

**Issue by baoyankun** [XX-net/XX-Net#1135]
2.5.0 运行在 192.168.1.106 上，本机可以打开 127.0.0.1:8085，而在 192.168.1.100 上打不开 192.168.1.106:8085 (This website is not available.)

谢谢！

**Comment by baoyankun** [comment]
找到问题了:
tcp        0      0 127.0.0.1:8085          0.0.0.0:*               LISTEN      4747/python2
webui 只监听 127.0.0.1？如何改成 0.0.0.0 呢？

**Comment by xxnet** [comment]
系统的设置里有

2015-09-30 16:25 GMT+08:00 baoyankun <notifications@github.com>:

**Comment by baoyankun** [comment]
问题是 192.168.1.106 是单板机，无 Xorg，我是用 w3m 确认本机能打开的
因此无法在本机启动 127.0.0.1:8085 来配置

**Comment by baoyankun** [comment]
修改 web_control.py 解决了

**Comment by xxnet** [comment]
下次升级还会别覆盖，你下次可以修改data/launcher/config.yaml
  launcher: {allow_remote_connect: 0, control_port: 8085}

  allow_remote_connect 改为1

或者在PC上设置好了，再拷贝过去。

2015-09-30 18:07 GMT+08:00 baoyankun <notifications@github.com>:

**Comment by baoyankun** [comment]
@xxnet 谢谢，解决了
