### ISSUE TITLE
XX-Net修改浏览器UA导致Firefox无法在AMO安装扩展

### ISSUE THREAD

**Issue by Jerry-1984** [XX-net/XX-Net#11367]
当前系统win10X64，XX-Net版本3.12.11，Firefox62。
一旦启用XX代理就会导致Firefox访问AMO无法安装扩展，显示如图。
![amo](https://user-images.githubusercontent.com/31561637/44625053-9f8b5380-a931-11e8-8427-219bda527953.jpg)

**Comment by AnyWAT** [comment]
当前系统win10X32，XX-Net版本3.12.11，Firefox61.0.2（代理使用中）
![default](https://user-images.githubusercontent.com/37962734/44625507-fe56ca00-a93d-11e8-8020-ea1d1d754139.png)

**Comment by SeaHOH** [comment]
@Jerry-1984 mozilla 的限制，wiki 里面有讲过，直连或者用 X-Tunnel 就行。

@AnyWAT 注意你的证书标签，并没有使用 gae_proxy 代理。

**Comment by AnyWAT** [comment]
后面改用了 gae_proxy 代理，结果如前

**Comment by SeaHOH** [comment]
@AnyWAT 清除缓存

**Comment by AnyWAT** [comment]
浏览器扩展 gae_proxy 代理，清除缓存，重启，结果如前

**Comment by AnyWAT** [comment]
只能用于FireFox —获取FireFox ：楼主的浏览器被识别为非FireFox ？

**Comment by SeaHOH** [comment]
你肯定没有清除干净缓存
![x2scrap2](https://user-images.githubusercontent.com/8470820/44626092-5d005180-a906-11e8-98f1-436c9b168196.png)

**Comment by DianJakaWidiawan** [comment]
ハハハ
