### ISSUE TITLE
XX-Net 3.12.11，一切正常，你可以访问真正的互联网了。。但是还是不能访问google

### ISSUE THREAD

**Issue by zhangchutian** [XX-net/XX-Net#11365]
600:gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:12
ipv4-status: OK
ipv6-status: OK
connected-link: new:3
worker: h1:1 h2:0
scan-ip-thread-num: 10
ip-quality: 1072
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

日志要完整，前面缺了，老是这一条无助于根本上解决问题。

**Comment by zhangchutian** [comment]
可以重新上网了。thank you
