### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by gdsteven** [XX-net/XX-Net#11363]
是否能把微软的更新域默认加入到白名单里面？
windowsupdate.com;
microsoft.com;
windows.com

最近WIN10总是更新不了，日志提示故障存储段错误，各种办法都用了就差点重装了，最后无意间发现竟然是XX-NET设置了IE代理，因为不用IE，XX-NET菜单上也显示取消全局代理的，上网一切都正常，怎么也不会想到是全局代理造成更新不了，可能XX-NET下载二进制文件是有问题的，象英睿达官网经常不代理都上不去，挂XX-NET下载那个CSE，两百多M，通过XX-NET下载到31M就“正常”结束了，啥错误都不报，可下载的软件是无法用的，经过多次试验，XX-NET下载比较大的二进制文件是有问题的，总是能下载成功，但下载的文件是损坏的，汗~~

**Comment by SeaHOH** [comment]
微软的域名可不止这点。
可以使用 SwitchyOmega 配合 gfwlist，不要系统代理。
