### ISSUE TITLE
安卓版：显示”致命错误“

### ISSUE THREAD

**Issue by whytakemyname** [XX-net/XX-Net#11360]
安卓最新版。可以正常上网，但是无法进入软件主页面。
打开后显示”致命错误“，点击对话框中退出后直接退出软件，点击其他地方无效。
![44392212-42c01f80-a564-11e8-8bfe-02900fd1dfd7](https://user-images.githubusercontent.com/34732308/44582776-43abb800-a7d5-11e8-83d1-1227c8378523.jpg)
求解

**Comment by SeaHOH** [comment]
https://github.com/XndroidDev/Xndroid/issues
