### ISSUE TITLE
centos7+miredo 不稳定,总是掉线的解决办法

### ISSUE THREAD

**Issue by wyudiupup** [XX-net/XX-Net#11374]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
y

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
y

* 是否以相关关键词搜索过类似 issues？
y

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
no

* 如果问题得到解决，请务必回复相关情况，谢谢。
问题已经解决。本issue主要是为了分享一下我是如何解决这个问题的。

1、在部署在centos7上之前我使用的方式是直接将xxnet安装在win10的机器上，那么这时候的问题就是：每次我关机在启动机器时，ipv6都需要重启开启。然后机器也要重启，这点很难受。浪费时间。于是 我想到了将xxnet部署在一台centos7上的想法。
2、在centos7上遇到的问题：所有的一切都可以正常使用。也可以google。但是唯独一点，miredo很不稳定。每次一断网我发现总是miredo没有办法找到有效的ipv6，然后重启miredo或者在等一段时间之后miredo在重新连上已是十年后**逃：)**。
3、解决办法：将miredo安装成服务。首先我们从阿里镜像（https://opsx.alibaba.com/mirror）中搜索并下载相应的rpm包miredo-1.2.5-1.el7.rf.x86_64.rpm 。使用rpm命令安装完成之后：rpm -ql miredo 我们可以找到/usr/lib64/systemd/system/miredo.service。然后将此文件复制到：cp 
 /usr/lib64/systemd/system/miredo.service /usr/lib/systemd/system/miredo.service
4、到此我们就可以使用systemctl enable miredo来开机启动miredo了。
5、下面重中之重：如何保证miredo的稳定，root登录。crontab -e  然后输入*/5 * * * * service status miredo 就可以了。
6、其中的原理我不是很清除，但是现在我的miredo已经连续稳定工作30+小时没断过一次。之前在xxnet设置的线程数降下来还是稳定。希望可以帮到大家。

**Comment by zengsher** [comment]
vps 桥接，不失为一种解决方案
不过国内 vps 价格偏贵，不适合大众
如果是国外的 vps，又用不着这个了
最后，在国内 vps 上跑 xx-net ，不怕被查吗~

**Comment by SeaHOH** [comment]
VPS 上有其它更合适的工具，使用跟方便，无需 XX-Net。

**Comment by wyudiupup** [comment]
平时基本只是用google查一些问题。用不到vps。稳定的xxnet足够用了。 @zengsher

**Comment by wyudiupup** [comment]
@SeaHOH 大佬知道原因吗？为什么service status miredo 就可以是miredo稳定。这不合理啊

**Comment by zengsher** [comment]
不用 vps 你的 centos 哪来的~ 自用的电脑吗~ @wyudiupup

**Comment by SeaHOH** [comment]
@wyudiupup 
不好意思，没有仔细看你分享的经验。
不过这个原理我也不清楚。

**Comment by wz7465** [comment]
miredo应该不会稳定，只是作为一项服务在挂掉后系统会自动尝试恢复链接，所以感觉稳定

**Comment by SeaHOH** [comment]
@wyudiupup 还行吗？不行我就关闭了，或者就像楼上说的，你修改下描述。
