### ISSUE TITLE
手机版运行出现致命错误 

### ISSUE THREAD

**Issue by wuliaoC** [XX-net/XX-Net#11375]
unexpected exception calling start activity from outside of an Activity context requires the flag activity new task flag

**Comment by SeaHOH** [comment]
请使用 [Xndroid](https://github.com/XndroidDev/Xndroid/)

**Comment by XndroidDev** [comment]
下载最新版
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk
