### ISSUE TITLE
Cannot create PID file /usr/local/var/run/miredo.pid:权限不够

### ISSUE THREAD

**Issue by Howe829** [XX-net/XX-Net#11378]
系统：DeepinOS 15.6桌面版
ifconfig可以看到teredo网卡
但是XX-NET状态显示“IPV6不可用”
终端sudo miredo 报错：
Cannot create PID file /usr/local/var/run/miredo.pid:
 权限不够
请帮忙解决一下，谢谢！

**Comment by SeaHOH** [comment]
如果是空密码，请设置一个。
如果你不记得密码，别人也没法。

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by Howe829** [comment]
> 关闭后仍可回复
原因找到了，miredo是在运行的。所以无法创建新的PID。但是就是ifconfig 可以看到teredo网卡，xxｎet的显示却是ipv6不可用，这个不知道是什么原因。

**Comment by SeaHOH** [comment]
可以使用 http://test-ipv6.com/ 测试

**Comment by Howe829** [comment]
> 可以使用 http://test-ipv6.com/ 测试

测试结果是没有ipv6,可是终端ifconfig是有teredo网卡的。。。

**Comment by SeaHOH** [comment]
kill 掉，重新运行试试。
或者，你是不是没有正确安装？

**Comment by Howe829** [comment]
> kill 掉，重新运行试试。
> 或者，你是不是没有正确安装？

kill 掉重启时出现 " Unsupported symmetric NAT detected."，ifconfig 还是有teredo，然后ipv6测试地址还是测试失败。。

**Comment by SeaHOH** [comment]
> " Unsupported symmetric NAT detected."

这种 NAT 类型只有 Windows 才支持，你需要改变它。
如果是运营商提供的，需要改成公网 IP，
否则，修改路由器设置，把此台设备（配置成固定 IP）设置为 DMZ 主机。

**Comment by llqll** [comment]
> > kill 掉，重新运行试试。
> > 或者，你是不是没有正确安装？
> 
> kill 掉重启时出现 " Unsupported symmetric NAT detected."，ifconfig 还是有teredo，然后ipv6测试地址还是测试失败。。
你好，问题解决了没有，我也出现了相同的问题，怎么解决啊

**Comment by SeaHOH** [comment]
看上一条，写得很清楚。
