### ISSUE TITLE
3.12.11版本 WIN10 IPV6无法用

### ISSUE THREAD

**Issue by hmsfeng** [XX-net/XX-Net#11371]
3.12.11版本 WIN10 IPV6无法用
测试teredo结果：
qualified: True
NAT type: restricted
best server is: win10.ipv6.microsoft.com.
但在状态里显示：IPv6 状态(如何开启)	Fail (尝试修复)

IPV6网页测试结果
IPv4 域名连接测试	 	
成功 (0.975s) 使用 ipv4
IPv6 域名连接测试	 	
失败 (0.013s)
双栈域名连接测试	 	
成功 (0.501s) 使用 ipv4
双栈域名大数据包传输测试	 	
成功 (0.517s) 使用 ipv4
无域名 IPv4 连接测试	 	
成功 (0.460s) 使用 ipv4
无域名 IPv6 连接测试	 	
失败 (0.005s)
IPv6 大数据包传输测试	 	
失败 (0.014s)
测试运营商 DNS 是否接入 IPv6	 	
成功 (0.714s) 使用 ipv4
查询 IPv4 运营商	 	
成功 (0.254s) 使用 ipv4 ASN 4134
查询 IPv6 运营商	 	
失败 (0.011s)

求大神解决

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by hmsfeng** [comment]
C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.9.1.1000 Chrome/39.0.2146.0 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by RoderickQiu** [comment]
“proxy state fail”
“ca state fail”
这两项先解决了看看？

**Comment by SeaHOH** [comment]
试试重新拨号，如果是路由器拨号就重启路由器。

**Comment by hmsfeng** [comment]
C:\Users\Administrator>netsh int ipv6 show teredo state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

是不是最后NAT特殊行为这里有问题？

**Comment by AnyWAT** [comment]
2个否的一直正常
类型 : enterpriseclient (Group Policy)
服务器名称 : teredo.remlab.net (Group Policy)
——何时又变成 Group Policy 😜

**Comment by hmsfeng** [comment]
我是用组策略方法的，不知道为啥变成这个

**Comment by hmsfeng** [comment]
网上搜了很多方法，均测试不行，哎，为啥就用ipv6呢？

**Comment by AnyWAT** [comment]
貌似可完全抛弃（刚开始使用隧道的）测试：正常前不通测也白测，正常后已通还用得着测？
🤣同时尽量不用貌似能开启但无法修复发组策略 #10184

**Comment by hmsfeng** [comment]
C:\Users\Administrator>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
但在XX-NET测试Teredo出现如下现象：
qualified: False
NAT type: symmetric
best server is: teredo.remlab.net.

**Comment by AnyWAT** [comment]
（开机）启动XX-Net 前即运行以下 bat（批处理内容）可观察变化过程，状态 dormant 即已开始正常化，（随时运行，凭此判断是隧道还是XX-Net 的问题，最佳）启动XX-Net 数秒隧道即可正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by turnipwang** [comment]
1. 单击“开始”，单击“运行”，键入“regedit”，然后单击“确定”
2. 找到下面的注册表子项，然后单击它：
HKEY_LOCAL_MACHINE\ System\CurrentControlSet\Services\Rasman\Parameters
3. 在“编辑”菜单上，单击“新建”->“DWORD值”
4. 在“名称”框中，键入“ProhibitIpSec”
5. 在“数值数据”框中，键入“1”，然后单击“确定”
6. 退出注册表编辑器，然后重新启动计算机

我在试其他东西的修改偶然修复的，你可以试下

**Comment by hmsfeng** [comment]
试了你的方法，还是一样的问题。
隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:53aa:64c:30f7:1408:3f57:c924(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::30f7:1408:3f57:c924%15(首选)
   默认网关. . . . . . . . . . . . . : ::
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

C:\Users\Administrator>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant


C:\Users\Administrator>ping -6 ipv6.test-ipv6.com

正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
来自 2001:470:1:18::4:230 的回复: 时间=198ms

2001:470:1:18::4:230 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 1，丢失 = 3 (75% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 198ms，最长 = 198ms，平均 = 198ms

C:\Users\Administrator>ping -6 ipv6.test-ipv6.com

正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:
来自 2001:470:1:18::4:230 的回复: 时间=202ms
来自 2001:470:1:18::4:230 的回复: 时间=246ms
来自 2001:470:1:18::4:230 的回复: 时间=263ms
来自 2001:470:1:18::4:230 的回复: 时间=198ms

2001:470:1:18::4:230 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 198ms，最长 = 263ms，平均 = 227ms

C:\Users\Administrator>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
但在XX-NET测试Teredo仍出现如下现象：
qualified: True
NAT type: restricted
best server is: win10.ipv6.microsoft.com.

**Comment by AnyWAT** [comment]
试了你的方法，还是一样的问题。——你是 @turnipwang ？
如不是，（继续 ping -6 ipv6.test-ipv6.com 。。。）则无语了🤐

**Comment by hmsfeng** [comment]
@AnyWAT  能否给出个终极操作，另外你的回复不要有图形可以么，看着别扭。

**Comment by hmsfeng** [comment]
@AnyWAT  能否给出个终极操作，另外你的回复不要有图形可以么，看着别扭。

**Comment by AnyWAT** [comment]
求助于人，不（知道配合）按建议操作，继续自以为是，确实别扭，少见的别扭😭
终极操作：要么继续自玩，要么告别XX-Net 👀

**Comment by hmsfeng** [comment]
你的方法我也试过啊，你也没有具体流程，做到哪一步就给出哪些特征说明成功了，不然都是懵的

**Comment by SeaHOH** [comment]
@hmsfeng 你的设备完全正常，但是你换了好几次网络环境吧。
1. 点击`禁用`按钮
1. 点击`更换服务器`按钮
1. 如果一分钟后隧道仍然不正常，重新拨号或者换一个网络环境，重复以上操作

**Comment by turnipwang** [comment]
我刚发现。。我是切换到WIFI连接才可以的。。有线不行。。

**Comment by AnyWAT** [comment]
没有无线的台机一直行😂

**Comment by hmsfeng** [comment]
手机上的安卓版本是没问题的，正常联网
