### ISSUE TITLE
有效ipv6数很少 扫描线程只有1 这是啥情况

### ISSUE THREAD

**Issue by ppeng** [XX-net/XX-Net#11372]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:73
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 1
ip-quality: 427
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
设计如此。
使用上有什么不方便么？

**Comment by ppeng** [comment]
@SeaHOH 以前都是1000个左右现在变100个左右了 我以为设置的不对呢

**Comment by SeaHOH** [comment]
可以切换`自动调整扫描线程`开关，对比使用效果选择是否开启。
