### ISSUE TITLE
全新安装，部署后，使用一段时间后，就无法访问youtub。总是出现浏览器代理设置fail，证书fail问题

### ISSUE THREAD

**Issue by imelee** [XX-net/XX-Net#11383]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是的

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是
* 是否以相关关键词搜索过类似 issues？

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:90
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 491
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
#11291

**Comment by SeaHOH** [comment]
把无法访问时的日志贴出来

**Comment by imelee** [comment]
@SeaHOH  
Aug 29 19:35:26.817 - [DEBUG] recheck_ip:2620:11a:a01a::18 restore ok

Aug 29 19:35:32.291 - [DEBUG] recheck_ip:2001:b032:2101::e restore ok

Aug 29 19:35:41.549 - [DEBUG] recheck_ip:2001:b032:8102:1::11 restore ok

Aug 29 19:35:55.554 - [DEBUG] report_connect_fail:2800:380:5000:9::11

Aug 29 19:36:01.763 - [DEBUG] recheck_ip:2800:380:5000:9::11 restore ok

Aug 29 19:36:08.246 - [DEBUG] recheck_ip:2404:6800:4005:10::8 restore ok

Aug 29 19:36:22.249 - [DEBUG] report_connect_fail:2402:800:6150:1::d

Aug 29 19:36:24.015 - [DEBUG] recheck_ip:2402:800:6150:1::d restore ok

Aug 29 19:36:29.615 - [DEBUG] recheck_ip:2404:6800:400c:9::b restore ok

Aug 29 19:36:43.620 - [DEBUG] report_connect_fail:2400:d800:3:497::11

Aug 29 19:36:46.341 - [DEBUG] recheck_ip:2400:d800:3:497::11 restore ok

Aug 29 19:36:51.952 - [DEBUG] recheck_ip:2404:6800:400c:b::7 restore ok

Aug 29 19:36:57.582 - [DEBUG] recheck_ip:2404:6800:400c:3::7 restore ok

Aug 29 19:37:11.587 - [DEBUG] report_connect_fail:2001:ee0:3204:2::10

Aug 29 19:37:13.875 - [DEBUG] recheck_ip:2001:ee0:3204:2::10 restore ok

Aug 29 19:37:19.515 - [DEBUG] recheck_ip:2404:6800:400c::c restore ok

Aug 29 19:37:33.519 - [DEBUG] report_connect_fail:2001:2f8:0:15::f

Aug 29 19:37:35.383 - [DEBUG] recheck_ip:2001:2f8:0:15::f restore ok

Aug 29 19:37:40.973 - [DEBUG] recheck_ip:2001:f90:8:6::10 restore ok

Aug 29 19:37:54.978 - [DEBUG] report_connect_fail:2804:854:15::e

Aug 29 19:37:56.912 - [DEBUG] recheck_ip:2804:854:15::e restore ok

Aug 29 19:38:02.541 - [DEBUG] recheck_ip:2404:6800:4008:12::7 restore ok

Aug 29 19:38:08.203 - [DEBUG] recheck_ip:2001:f18:113:14::e restore ok

Aug 29 19:38:22.208 - [DEBUG] report_connect_fail:2400:d800:3:452::f

Aug 29 19:38:23.932 - [DEBUG] recheck_ip:2400:d800:3:452::f restore ok

Aug 29 19:38:29.483 - [DEBUG] recheck_ip:2404:6800:400c:a::7 restore ok

Aug 29 19:38:34.959 - [DEBUG] recheck_ip:2001:b032:8102:1::12 restore ok

Aug 29 19:38:41.024 - [DEBUG] recheck_ip:2405:4800:100:34::13 restore ok

Aug 29 19:38:46.618 - [DEBUG] recheck_ip:2404:6800:4008::8 restore ok

Aug 29 19:38:52.731 - [DEBUG] recheck_ip:2405:4800:100:1c::d restore ok

Aug 29 19:39:06.734 - [DEBUG] report_connect_fail:2001:d08:11:204::e

Aug 29 19:39:09.749 - [DEBUG] recheck_ip:2001:d08:11:204::e restore ok

**Comment by SeaHOH** [comment]
> 把无法访问时的日志贴出来

**Comment by imelee** [comment]
@SeaHOH 你是说第一次出现问题的时候的日志？后面自己折腾了2次，没有了，只有现在这个时间的日志，就是一直出现浏览器设置和证书fail，状态确显示空闲

**Comment by SeaHOH** [comment]
看不明白吗？访问一次网页就行了。

**Comment by imelee** [comment]
@SeaHOH 我新开一个
Aug 29 19:52:51.324 - [INFO] ------------------------------------------------------

Aug 29 19:52:51.324 - [INFO] Python Version : 2.7.13

Aug 29 19:52:51.324 - [INFO] OS : Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

Aug 29 19:52:51.324 - [INFO] Listen Address : 127.0.0.1:8087

Aug 29 19:52:51.324 - [INFO] GAE APPID : imelee-1066|imelee-1019|imeleevorlon|imeleevorlon1|imeleevorlon2|vorlon-3|vorlon-1066|vorlon-4|vorlon-1|vorlon-2|vorlon-5|vorlon-6

Aug 29 19:52:51.324 - [INFO] ------------------------------------------------------

Aug 29 19:52:51.645 - [DEBUG] Importing CA

Aug 29 19:52:51.645 - [DEBUG] Begin to import Windows CA

Aug 29 19:52:51.651 - [DEBUG] XX-Net CA already exists

Aug 29 19:52:51.652 - [INFO] SSL use version:TLSv1_2

Aug 29 19:52:51.653 - [INFO] OpenSSL support alpn

Aug 29 19:52:51.654 - [INFO] load ip range file:F:\shadowsocks-windows-rm\XX-Net-3.12.11\code\default\gae_proxy\local\ip_range.txt

Aug 29 19:52:51.655 - [INFO] load ip_list num:100, target num:100

Aug 29 19:52:51.655 - [INFO] Adjust scan thread num from 20 to 3

Aug 29 19:52:51.661 - [INFO] SSL use version:TLSv1_2

Aug 29 19:52:51.664 - [INFO] server 127.0.0.1:8087 started.

Aug 29 19:52:52.137 - [DEBUG] network IPv4 is ok, cost:1274 ms

Aug 29 19:52:53.130 - [DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=36413706-6cb1-45ab-9e02-eac2059e3ca8&version=3.12.11&platform=Windows-10-10.0.17134 from:127.0.0.1:11457

Aug 29 19:52:53.134 - [DEBUG] connect 2600:2:300:1::11 blocked: network fail

Aug 29 19:52:53.636 - [DEBUG] connect 2806:1040:cfff:2::d blocked: network fail

Aug 29 19:52:54.138 - [DEBUG] connect 2610:28:42c:100::c blocked: network fail

Aug 29 19:52:54.640 - [DEBUG] connect 2404:6800:400b:2::a blocked: network fail

Aug 29 19:52:55.142 - [DEBUG] connect 2607:f798:14:44::13 blocked: network fail

Aug 29 19:52:55.644 - [DEBUG] connect 2001:b000:188:c101::12 blocked: network fail

Aug 29 19:52:56.146 - [DEBUG] connect 2001:b032:101:1::13 blocked: network fail

Aug 29 19:52:56.648 - [DEBUG] connect 2001:b032:7100:1::f blocked: network fail

Aug 29 19:52:57.150 - [DEBUG] connect 2620:11a:a01a::18 blocked: network fail

Aug 29 19:52:57.651 - [DEBUG] connect 2001:b032:2101::e blocked: network fail

Aug 29 19:53:00.449 - [DEBUG] network IPv6 is ok, cost:9577 ms

Aug 29 19:53:00.941 - [INFO] scan_ip add ip:2800:e0:c74::10 time:1740 h2:0

Aug 29 19:53:00.942 - [INFO] remove_slowest_ip:2800:e0:c74::10 handshake_time:1740, fails:0

Aug 29 19:53:05.845 - [INFO] scan_ip add ip:2405:4800:100:18::e time:620 h2:0

Aug 29 19:53:05.846 - [INFO] remove_slowest_ip:2607:fa48:70:9::c handshake_time:885, fails:0

Aug 29 19:53:06.213 - [DEBUG] create_ssl update ip:2610:28:42c:100::c time:1070 h2:0 sni:radio.climate.voice.net, host:

Aug 29 19:53:07.661 - [INFO] DIRECT t:14530 s:1674 200 xxnet-update.appspot.com /update.json?uuid=36413706-6cb1-45ab-9e02-eac2059e3ca8&version=3.12.11&platform=Windows-10-10.0.17134

Aug 29 19:53:08.244 - [DEBUG] create_ssl update ip:2001:b000:188:c101::12 time:970 h2:0 sni:company.touch.carry.org, host:

Aug 29 19:53:08.617 - [DEBUG] create_ssl update ip:2001:b032:101:1::13 time:965 h2:0 sni:area-employment-cookie.net, host:

Aug 29 19:53:09.137 - [DEBUG] report_connect_fail:2600:2:300:1::11

Aug 29 19:53:09.137 - [DEBUG] connect 2600:2:300:1::11 fail:error("conn fail, sni:phasedimension.ml, top: e:timeout('timed out',)",)

Aug 29 19:53:09.639 - [DEBUG] report_connect_fail:2806:1040:cfff:2::d

Aug 29 19:53:09.639 - [DEBUG] connect 2806:1040:cfff:2::d fail:error("conn fail, sni:stealdevelopmentshoot.us, top: e:timeout('timed out',)",)

Aug 29 19:53:10.644 - [DEBUG] report_connect_fail:2404:6800:400b:2::a

Aug 29 19:53:10.644 - [DEBUG] connect 2404:6800:400b:2::a fail:error("conn fail, sni:platform.anxiety.information.org, top: e:timeout('timed out',)",)

Aug 29 19:53:11.146 - [DEBUG] report_connect_fail:2607:f798:14:44::13

Aug 29 19:53:11.146 - [DEBUG] connect 2607:f798:14:44::13 fail:error("conn fail, sni:industryupper.org, top: e:timeout('timed out',)",)

Aug 29 19:53:12.696 - [INFO] scan_ip add ip:2800:2d20:100b:e::13 time:2736 h2:0

Aug 29 19:53:12.698 - [INFO] Adjust scan thread num from 3 to 10

Aug 29 19:53:12.709 - [INFO] remove_slowest_ip:2800:2d20:100b:e::13 handshake_time:2736, fails:0

Aug 29 19:53:13.153 - [DEBUG] report_connect_fail:2620:11a:a01a::18

Aug 29 19:53:13.153 - [DEBUG] connect 2620:11a:a01a::18 fail:error("conn fail, sni:writing-produce-prize.com, top: e:timeout('timed out',)",)

Aug 29 19:53:13.200 - [DEBUG] create_ssl update ip:2001:b032:7100:1::f time:5424 h2:0 sni:purple.shock.hate.us, host:

Aug 29 19:53:15.234 - [INFO] scan_ip add ip:2a02:8400:0:11a::d time:655 h2:0

Aug 29 19:53:15.235 - [INFO] remove_slowest_ip:2620:11a:a01a::18 handshake_time:493, fails:1

Aug 29 19:53:17.018 - [INFO] scan_ip add ip:2402:800:6350:11::f time:600 h2:0

Aug 29 19:53:17.019 - [INFO] remove_slowest_ip:2001:b032:7100:1::f handshake_time:991, fails:0

Aug 29 19:53:18.654 - [INFO] scan_ip add ip:2a04:ae39:204:1::d time:574 h2:0

Aug 29 19:53:18.656 - [INFO] remove_slowest_ip:2001:b000:188:c101::12 handshake_time:970, fails:0

Aug 29 19:53:21.784 - [INFO] scan_ip add ip:2402:800:6150:3::10 time:574 h2:0

Aug 29 19:53:21.785 - [INFO] remove_slowest_ip:2001:b032:101:1::13 handshake_time:965, fails:0

Aug 29 19:53:27.767 - [INFO] scan_ip add ip:2001:ee0:3200:1::11 time:575 h2:0

Aug 29 19:53:27.769 - [INFO] Adjust scan thread num from 10 to 9

Aug 29 19:53:27.769 - [INFO] remove_slowest_ip:2607:f798:14:44::13 handshake_time:462, fails:1

Aug 29 19:53:28.226 - [INFO] scan_ip add ip:2a02:a000:1:204::f time:489 h2:0

Aug 29 19:53:28.228 - [INFO] Adjust scan thread num from 9 to 8

Aug 29 19:53:28.228 - [INFO] remove_slowest_ip:2404:6800:400b:2::a handshake_time:430, fails:1

Aug 29 19:53:35.565 - [INFO] scan_ip add ip:2001:ee0:3201:1::11 time:690 h2:0

Aug 29 19:53:35.567 - [INFO] remove_slowest_ip:2610:28:42c:100::c handshake_time:890, fails:0

Aug 29 19:53:42.861 - [INFO] scan_ip add ip:2402:800:6150:8::d time:582 h2:0

Aug 29 19:53:42.862 - [INFO] remove_slowest_ip:2806:1040:cfff:2::d handshake_time:386, fails:1

Aug 29 19:53:48.380 - [INFO] scan_ip add ip:2001:1a68:0:25::11 time:1544 h2:0

Aug 29 19:53:48.381 - [INFO] remove_slowest_ip:2001:1a68:0:25::11 handshake_time:1544, fails:0

Aug 29 19:53:57.015 - [INFO] scan_ip add ip:2001:1970:1:2052::12 time:296 h2:0

Aug 29 19:53:57.016 - [INFO] remove_slowest_ip:2600:2:300:1::11 handshake_time:321, fails:1

Aug 29 19:54:02.553 - [INFO] scan_ip add ip:2001:ee0:3202:5::10 time:549 h2:0

Aug 29 19:54:02.554 - [INFO] Adjust scan thread num from 8 to 4

Aug 29 19:54:02.555 - [INFO] remove_slowest_ip:2001:4958:300:4f1::d handshake_time:304, fails:1

**Comment by SeaHOH** [comment]
完全没有使用痕迹，检查你的代理设置。

**Comment by imelee** [comment]
@SeaHOH  那就无法解释了!如果是我代理的问题，开始就无法看yutub了，是在看了2个视频后，在第三个视频过程中突然视频就卡住了，然后才出的这个问题。这过程中一直没有改动代理，都是switchomega管理的。之后就再也无法连通

**Comment by SeaHOH** [comment]
有什么好解释的，日志里面完全没有使用痕迹，检查你的 SwitchyOmega。

**Comment by AnyWAT** [comment]
🤣
![default](https://user-images.githubusercontent.com/37962734/44787916-1a22d000-abcb-11e8-922a-085add6b2b12.png)

**Comment by SeaHOH** [comment]
关闭后仍可回复
