### ISSUE TITLE
ipv6 fail

### ISSUE THREAD

**Issue by fallenangeltcc** [XX-net/XX-Net#11386]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by fallenangeltcc** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）

**Comment by hgjinfan** [comment]
![default](https://user-images.githubusercontent.com/16183461/44840383-7a6d4c80-ac73-11e8-8bbb-cdbea581b9b1.PNG)

**Comment by AnyWAT** [comment]
楼上貌似隧道正常，浏览器扩展情景模式：GAE （全局或自动切换）， #11291

**Comment by hgjinfan** [comment]
![1](https://user-images.githubusercontent.com/16183461/44841161-4b57da80-ac75-11e8-871c-50a09220d1b1.PNG)
我的有效ip数总是0

**Comment by AnyWAT** [comment]
最好增大总IP数3-5倍。。。 #11291 
新开一个XX-Net （挤出貌似已不正常的），检查IP，新开或刷新需代理网页

**Comment by fallenangeltcc** [comment]
@AnyWAT 
best server is: teredo.remlab.net.

C:\windows\system32>sc config RpcEptMapper start= auto 
[SC] OpenService 失败 5:

拒绝访问。


C:\windows\system32>sc start RpcEptMapper 
[SC] StartService 失败 1056:

服务的实例已在运行中。

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及同一时间的XX-Net 诊断信息

**Comment by SeaHOH** [comment]
关闭后仍可回复
