### ISSUE TITLE
tumblr看不了，但是另一台电脑又能

### ISSUE THREAD

**Issue by meexho** [XX-net/XX-Net#11380]
都是相同的版本，但是一台能用xx-net看得了。这台又不行，有谁知道吗

**Comment by SeaHOH** [comment]
完全没有信息量，请补充。

**Comment by AnyWAT** [comment]
😜除了自己还有谁知道？
貌似 tumblr 看不了但XX-Net 代理正常（稍微动下脑子，测试下其它需代理网页即知）
😂莫非最大的可能就是：楼主在一号二用（而不能）？

**Comment by meexho** [comment]
uwp都已经开了代理了，

**Comment by AnyWAT** [comment]
现在猜想：一平板的XX-Net（代理）不正常或网络本身就不正常😂

**Comment by meexho** [comment]
x-tunnel能上切换到gae模式就挂了，另一台gae模式是可以的。隧道应该没问题

**Comment by meexho** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:40
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 40
ip-quality: 492
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by meexho** [comment]
类型                    : client (Group Policy)
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

**Comment by AnyWAT** [comment]
二平板不会使用同样几个AppID？
gws-ip-num: total:100 ipv4:0 ipv6:40——貌似扫描线程不够大：没能维持有效IP数达总IP数？
同一网络下？二平板的XX-Net 设置一样？

**Comment by SeaHOH** [comment]
根本没讲清楚。
运行了几个 XX-Net？
在哪些设备上运行的？
在不能访问的设备上，换一个浏览器测试，能否正常访问？

**Comment by SeaHOH** [comment]
关闭后仍可回复
