### ISSUE TITLE
teredo 没有ip

### ISSUE THREAD

**Issue by guozilong110** [XX-net/XX-Net#11387]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
yes

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
yes

* 是否以相关关键词搜索过类似 issues？
yes

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
ifconfig 
          teredo    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          UP POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)
eth0和lo 都有ipv6的地址

* 如果问题得到解决，请务必回复相关情况，谢谢。
配置文件添加,启动解决
ServerAddress teredo.remlab.net
ServerAddress2 83.170.6.76

**Comment by SeaHOH** [comment]
> eth0和lo 都有ipv6的地址

什么设备分配的？能访问公网？

**Comment by SeaHOH** [comment]
关闭后仍可回复
