### ISSUE TITLE
推特搜索页不显示结果

### ISSUE THREAD

**Issue by northsheep** [XX-net/XX-Net#11384]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是。

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是。

* 是否以相关关键词搜索过类似 issues？
是。按照 https://github.com/XX-net/XX-Net/issues/9938 的说明，切换到Smart-Router模式，问题仍在。

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

用XX-Net ，在推特中搜某关键字，显示没有结果：
![image](https://user-images.githubusercontent.com/13964012/44784439-48e77900-abc0-11e8-9dae-407fa39f0532.png)

用lantern 时的搜索结果：
![image](https://user-images.githubusercontent.com/13964012/44784491-703e4600-abc0-11e8-99f4-3dfe25489b19.png)

**状态页**

状态
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 294
连接池(帮助) | 新:0 h1:8 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 200

配置
属性 | 值
-- | --
代理监听 | 0.0.0.0:8087
IP 模式 | 仅 IPv6
前置代理 | 禁用

系统信息
属性 | 值
-- | --
XX-Net Version | 3.12.11
Python Version | 2.7.13
OpenSSL Version | 16.0.0 TLSv1_2 h2:alpn
System Platform | AMD64, Windows-8.1-6.3.9600
OS System | Windows
OS Version | 6.3.9600
OS Release | 8.1
OS Detail | Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language | zh_CN
Architecture | 32bit,WindowsPE
Browser | Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**日志**

Aug 29 19:13:38.119 - [DEBUG] x_tunnel not running

Aug 29 19:13:38.119 - [INFO] Load file:D:\system_tool\fxxk_GFW\XX-Net\code\default\smart_router\local\gfw_black_list.txt

Aug 29 19:13:38.119 - [INFO] Load file:D:\system_tool\fxxk_GFW\XX-Net\code\default\smart_router\local\gfw_white_list.txt

Aug 29 19:13:38.119 - [INFO] Load file:D:\system_tool\fxxk_GFW\XX-Net\code\default\smart_router\local\advertisement_list.txt

Aug 29 19:13:38.135 - [DEBUG] use local DNS server:192.168.100.1

Aug 29 19:13:38.135 - [DEBUG] use local DNS server:192.168.168.1

Aug 29 19:13:38.135 - [INFO] server 127.0.0.1:8086 started.

Aug 29 19:13:38.135 - [INFO] Proxy server listen:127.0.0.1:8086.

Aug 29 19:13:38.135 - [INFO] start DNS server at 127.0.0.1:53

Aug 29 19:13:42.832 - [DEBUG] host:clients4.google.com:443 do gae

Aug 29 19:13:45.442 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:45.444 - [DEBUG] host:clients4.google.com:443 do gae

Aug 29 19:13:45.447 - [DEBUG] host:abs.twimg.com:443 do gae

Aug 29 19:13:45.458 - [DEBUG] host:pbs.twimg.com:443 do gae

Aug 29 19:13:45.800 - [DEBUG] host:clients4.google.com:443 do gae

Aug 29 19:13:45.844 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:46.818 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:46.834 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:48.505 - [DEBUG] recev 12 from:114.114.114.114 domain:www.google-analytics.com. org:www.google-analytics.com

Aug 29 19:13:48.505 - [DEBUG] local dns www.google-analytics.com recv www.google-analytics.com. cname:www-google-analytics.l.google.com from:114.114.114.114

Aug 29 19:13:48.506 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:48.539 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:48.570 - [DEBUG] host:syndication.twitter.com:443 do gae

Aug 29 19:13:48.575 - [DEBUG] host:www.google-analytics.com:443 direct connect 203.208.51.78 success

Aug 29 19:13:48.575 - [INFO] domain www.google-analytics.com:443 direct

Aug 29 19:13:48.578 - [DEBUG] host:analytics.twitter.com:443 do gae

Aug 29 19:13:48.590 - [DEBUG] host:api.twitter.com:443 do gae

Aug 29 19:13:48.623 - [DEBUG] host:api.twitter.com:443 do gae

Aug 29 19:13:49.102 - [INFO] block advertisement cm.g.doubleclick.net:443

Aug 29 19:13:49.248 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:50.914 - [DEBUG] host:api.github.com:443 do gae

Aug 29 19:13:50.917 - [DEBUG] host:twitter.com:443 do gae

Aug 29 19:13:57.319 - [DEBUG] domain host:abs.twimg.com:443 try gae, GetReqTimeout:11891

Aug 29 19:13:57.319 - [DEBUG] domain host:pbs.twimg.com:443 try gae, GetReqTimeout:11881

Aug 29 19:13:57.319 - [DEBUG] host:clients4.google.com:443 do gae

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by zengsher** [comment]
既然已经返回 No results ...
说明不是网络的锅
或许是针对不同地区搜索结果有区别？

**Comment by SeaHOH** [comment]
原因及解决方法见 wiki GAE 平台限制。

**Comment by northsheep** [comment]
按照 https://github.com/XX-net/XX-Net/wiki/GoAgent-Limitation ，用 m.twitter.com 代替。谢谢 @SeaHOH 。
