### ISSUE TITLE
设置AppID的App引擎的地图一直不显示

### ISSUE THREAD

**Issue by ydl825312** [XX-net/XX-Net#11381]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是
mac平台
我已经试了不同的梯子 换了无数SS账号 试过蓝灯 但是教程那个让我选择区域的地图一直不显示（下图）
![image](https://user-images.githubusercontent.com/12187279/44779531-4e3dc700-abb2-11e8-9a86-7023bd7bd095.png)
教程说是梯子问题 但是我试了无数个 也换了不同浏览器 甚至开虚拟机用IE试 同样不行……

**Comment by ydl825312** [comment]
求帮助呀

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids/b7e7d1ea13f5d8c578fbe7b1a16240bc4494eb45
参考此页面使用 shell 部署，之前被删掉了，难怪你没看见。
