### ISSUE TITLE
设置全局PAC代理后会自动跳到取消全局代理

### ISSUE THREAD

**Issue by SandroGong** [XX-net/XX-Net#11399]
之前开着XX-Net的全局PAC代理时，开了下BT下载，导致IPV6连不上，于是我改了ipv6的最大扫描数，也改了ipv6隧道为切换到teredo优先（后来改回来了），然后也运行过几次目录下的diasble_ipv6和enable_ipv6的bat文件，后来知道BT会对IPV6有影响后，就关了XX-Net再下载；
之后一旦电脑下载过东西（就连开机后先不开XX-Net下载，下载完再开XX-Net；而且即使是很小的通过浏览器下载的文件），XX-Net就会在一段时间后，从全局PAC代理自动跳回到取消全局代理；而且当开着XX-Net时，每次一开始下载，会马上跳回到取消全局代理选项上；
查了很长时间也没找到原因，版本是3.12.11
我的XX-Net的状态：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:92
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:13 h2:0
scan-ip-thread-num: 1
ip-quality: 548
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

还有就是我的注册表
![qq 20180901152720](https://user-images.githubusercontent.com/42886357/44943612-956ac880-adfb-11e8-82e6-5668d6366440.png)
机器上的国产软件只有QQ

另外，已经试过出这个问题后，全部删除了之前的XX-Net，重新下载了新的3.12.11，但还是有这个问题

**Comment by SeaHOH** [comment]
感觉就是 #10620 这个 bug，你那个 PAC 只是显示，系统代理应该没有设置成功。
你可以任意点击一个其它代理模式，如果真是这个 bug，那么过一会儿就会恢复成`取消全局代理`。

**Comment by SeaHOH** [comment]
那就不是了，有点奇怪，第一次遇到过这样的反馈。

可能真是其它软件修改的，你试试不要启动国产软件，如果这些国产软件有开机启动和系统服务也暂时禁用，然后再试一下。

**Comment by SandroGong** [comment]
试过关QQ和AVAST（包括开机启动，但是avast没办法关开机启动，只能开机的时候他的所有防护盾都是关掉的），结果还是没用。
我估计应该是 系统对代理的上传下载传输进行了限制的感觉，但是不知道在什么地方去查看设置

**Comment by SeaHOH** [comment]
会不会是 PAC 本身的原因？
你把`XX-Net IP:8086/proxy.pac`下载储存到本地文件夹，然后到系统代理设置面板，手动填入这个 PAC 文件的地址。看看这样是否还会自动关闭。

**Comment by SandroGong** [comment]
不好意思问一下，是从http://127.0.0.1:8086/proxy.pac这上面下么？

**Comment by SandroGong** [comment]
最新情况： smarter router现在是过非常长（平均时长大于设置PAC时）会有切换回 取消全局变量的情况

**Comment by SeaHOH** [comment]
> 我下载了这个pac文件，在系统代理里填写这个文件的地址（file：///XX/XX格式）

这是浏览器使用的格式，直接 X:\XXX\proxy.pac 就行。

**Comment by SandroGong** [comment]
试过了，用X:\XXX\proxy.pac 还是和填File那个格式一样的情况（另外，我下的是http://127.0.0.1:8086/proxy.pac 的pac文件）
还有，我现在 smarter router也会 跳回 取消全局变量了，这样是不是说，就和那个bug就可能是一个原理了？

**Comment by SandroGong** [comment]
>很久不用，记错了。就是file:///XX/XX格式，不过你似乎写成了了中文冒号。

为了确保万无一失，我再试了试，这次确定是英文的冒号，好像还是没用

**Comment by SeaHOH** [comment]
搞不懂，真是那个 bug 也没法解决。

**Comment by SandroGong** [comment]
恩，我现在就只能用的时候切换一下了（笑）
只能看后面的版本吧（我昨天甚至都重置了网络了，netsh winsock那个）
总之，就再等等，辛苦你们了，这天朝的鬼网络...

**Comment by SeaHOH** [comment]
估计以后也解决不了，似乎是操作系统 bug，而非 XX-Net 的 bug。

**Comment by SandroGong** [comment]
恩，只能看了，有时候，有些bug基本就是莫名其妙的随着一个系统更新或者什么的就好了；
只能期望了...

**Comment by AnyWAT** [comment]
试试只读 data\launcher\config.yaml 文件？

**Comment by SandroGong** [comment]
> 试试只读 data\launcher\config.yaml 文件？

把这个文件设为只读吗？

**Comment by SandroGong** [comment]
Sep 02 16:27:52.180 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x045DE058>

顺带，在laucher文件夹里看了下error.log，貌似是今天报的，不知道有没有帮助；

**Comment by SandroGong** [comment]
试过只读文件了，也不行...

**Comment by SandroGong** [comment]
最新情况更新：大前天的时候，貌似**这个bug自动好了**，我测试了3天，现在不会自动跳到取消全局变量上了，即使我进行下载也不会跳到取消全局变量上；所以现在我估计这个问题可能根本和系统没关系，也许是和ipv6或teredo服务器隧道的稳定性有关，或者和我这边网络运营商（电信）的网络有关大概（个人猜测，也许前段电信的网络正好在搞什么设置）

**Comment by SeaHOH** [comment]
所谓跳设置，就是 XX-Net 自动读取注册表设置，然后把结果显示出来。
XX-Net 只会在启动时修改一次，之后除非手动不会修改系统代理。
所以说，如果不是其它软件修改的，那么这很大可能就是操作系统的锅。

**Comment by SandroGong** [comment]
哦。。。那么就有可能是突然间不知道是那个东西把我的注册表相关值又重置回去了，所以bug才自己又好了；
反正现在没问题了就好，之前看了下事件查看器，看到DCOM错误，本来还在想这个会不会有关联，想去搞一下，现在不用了。
总之，谢谢解答。

**Comment by SandroGong** [comment]
再次更新：这次我可以确定原因了，和更新后自动重启有关，我9/13的时候，系统自动更新后，自动重启了， 重启后，这个问题又出现了，看来就是系统的锅了。

**Comment by AnyWAT** [comment]
32位Win10 1809/？-？？-17744-17754 几次更新都没问题（开启了以绿色方式运行 http://127.0.0.1:8085/?module=launcher&menu=config ）

**Comment by SandroGong** [comment]
@AnyWAT  我是64位 win10pro 1803，更新的kb4457128，kb4456655，kb4457146； 不过我没开绿色方式运行，还有就是 他是自动重启的，此时我应该正好 XX-net 开着，然后重启回来后，就出这个问题了(我没随机开启，所以重启后会显示XX-net的设置页面，同时 其他网页开始是处于已与网络断开状态，要刷新才会出来）
实际到底是什么情况，我就无法分清了，也许更新时触发了什么，至少原来更新我也是没问题的

**Comment by AnyWAT** [comment]
试试打开以绿色方式运行？
开了下BT下载——程序内有代理设置？

**Comment by AnyWAT** [comment]
😂XX-Net 启动和退出前与后、发现代理设置有自动变化之后检查下 data\launcher\config.yaml 文件内容：
proxy: disable（/pac/smart_router/x_tunnel/gae）
如同Win 系统底部托盘的几个：取消全局（/全局PAC/全局智能路由/全局X-Tunnel/全局GAE）

**Comment by SandroGong** [comment]
哦。。。原来是这样，那手动改 enable会有效吗？
还有目前反正开启了更新后重启须提示，调整了活动时间（虽然应该还是有几率在我没注意到情况下重启），后面应该不大会出问题；
另，win10这点做的还真是不舒服；重启有时都不提示一下。。。

**Comment by AnyWAT** [comment]
😜上上楼有写 enable ？

**Comment by SandroGong** [comment]
理解错。。。但是按理来说，如果这个不是设置为 pac或其他什么的话，如果只是disable，不应该是每次启动XX-net就会是自动选在取消全局变量上么。。。但是现在XX-net会记忆我上次的设置啊。。。

**Comment by AnyWAT** [comment]
XX-net启动时应该会读取这个config文件的配置。。。下次再启动时，。。。也就是此时不会去读config这个文件了咯？——前后逻辑不一致，混乱😂
3天前升级的1809/10.0.17754.1 ，今天又到10.0.17758.1 😝

**Comment by SandroGong** [comment]
@AnyWAT   我把config的**只读**属性去掉了（上次为了解决问题把它设过只读），然后我看到proxy哪一项会随着上一次退出设定的进行更改了。。。也就是说如果我是以PAC状态退出的，去查看config是时，proxy一项已经改成pac了。。。这样逻辑终于通了....

**Comment by SandroGong** [comment]
> Win10 系统安装 Python3.7 后，选用其它全局代理时，系统托盘XX-Net 图标总停留在勾选先前常用的“取消全局代理”，但在文件 config.yaml 内会及时有正常反应，软件重启后还是如此：图标勾选项固定，不能反应实际情况😱
> 想对比下不在同一目录下的3.8.5版，有鬼：安装 Python3.7 之前几天的 config.yaml 竟然
> popup_webui: 0, proxy: x_tunnel, xxnet_port: 8087} 貌似以前一直如下才是
> popup_webui: 0, proxy: disable}

所以是python版本和win10之间兼容的锅？
反正 目前 我这边是时好时坏，没有固定的，有时出这个问题不管，晚点差不多半夜的时候 自己好了...很神奇
