### ISSUE TITLE
不知为何我在配置文件中加入总ip数配置你无效

### ISSUE THREAD

**Issue by InoriHimea** [XX-net/XX-Net#11391]
![1](https://user-images.githubusercontent.com/33611921/44888339-2c078e80-ad03-11e8-81c2-b8f0cc37fa73.PNG)
![2](https://user-images.githubusercontent.com/33611921/44888342-33c73300-ad03-11e8-9706-dde79964f0d3.PNG)
到头来还是100

**Comment by AnyWAT** [comment]
"max_good_ip_num"

**Comment by InoriHimea** [comment]
@AnyWAT 哈哈，看看我的眼神，多么锐利 /斜眼笑
