### ISSUE TITLE
IOS11.3 安装了CA证书 仍不能连GaeProxy

### ISSUE THREAD

**Issue by Li-Aaron** [XX-net/XX-Net#11397]
按照wiki方法安装了证书
尝试ipad/iphone版本的safari/chrome/firefox均不能正常联网
提示有两种，
1.无法与服务器建立安全链接
2.此链接非私人链接(此网站可能在冒充“www.****.com”来窃取您的个人或财务信息（这种情况可以强制进入网页）——应为CA证书不受信
XX-net网页提示请导入浏览器CA证书
尝试重启无效

**Comment by SeaHOH** [comment]
#11408
这个 issues 虽然是先发，但是没有回复，就关闭了。
