### ISSUE TITLE
建议3.12.11

### ISSUE THREAD

**Issue by 1721970914** [XX-net/XX-Net#11393]
GAEProxy 配置页面添加：如果显示无效APPID，请阅读https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids
我这一个第一个APPID存在它是16年还是17年创建的
而后续3个APPID是新创建的，但我沿用以前的方式（创建项目就选择了地区）所以并没选择第一种语言挑服务器就配置服务器
前天第一个配额超出，然后完全没法用，第二天也是
最后配置到今天刚才都没用，公共APPID重新看配额，发现没有只能看帮助，就找了wiki
照着wiki解决了

**Comment by SeaHOH** [comment]
> GAEProxy 配置页面添加：如果显示无效APPID，请阅读......

这个可以有。


> 前天第一个配额超出，然后完全没法用，第二天也是

配额重置是美国时间零点。

> 在“状态”工作APPID可以看到这个其实没有工作的APPID

有延迟，实际调用时才会触发检测。
