### ISSUE TITLE
忘记密码了，怎么办？

### ISSUE THREAD

**Issue by zhenquanwang** [XX-net/XX-Net#11396]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/9591#issuecomment-359999332

**Comment by zhenquanwang** [comment]
发邮件了，可惜没人理我。。。真晕，客服这么差！！
