### ISSUE TITLE
XXnet好像把百度网盘给影响了，我开xxnet就上不了百度网盘。

### ISSUE THREAD

**Issue by wantno** [XX-net/XX-Net#11395]
有没有人也是我这样啊？xxnet结束进程后就可以正常上百度网盘了。

**Comment by aixiu** [comment]
不开全局，打开智能试试。！~

**Comment by AnyWAT** [comment]
莫非使用了托盘右键菜单最上的2个？（圈出的3个应不会出现楼主的情况？）如使用浏览器代理扩展，宜与“取消全局代理”配套
![image](https://user-images.githubusercontent.com/37962734/44941747-4d857a80-add6-11e8-92a1-1617494a1168.png)

**Comment by wantno** [comment]
谢谢啊。。。。解决了。竟然弄了这低级错误。
