### ISSUE TITLE
X-TUNNEL 是否存在被撞库危险呢？

### ISSUE THREAD

**Issue by lnsane** [XX-net/XX-Net#11398]
发现登录没有任何严重码阶段，一旦被撞库，会产生大量账号密码泄露？

**Comment by lnsane** [comment]
而且发现一旦密码没有存在修改密码的接口，这样的安全隐患，应该及时考虑。
望解答

**Comment by RoderickQiu** [comment]
这个风险确实存在。
不过，我估计xxnet应该只有不多于10万用户，其中使用x-tunnel的就更少了，对黑客撞库来讲并没有很大的价值。
而且估计开发者添加这个接口也要一定时间精力、暂时没那么多时间吧？

**Comment by RoderickQiu** [comment]
但是能改肯定是好的
还有密码应该加密保存

**Comment by 2378** [comment]
稍对S工库有点认识的人，也不会把密码设得太简单吧

**Comment by SeaHOH** [comment]
只包含两个隐私信息，邮箱和密码。
与其它账户体系一致，双方都存在撞库风险；不一致，显然没影响。

单说 X-Tunnel 本身，如果保护不当被黑了，然后流量没了，责任在 xxnet，可以要求恢复。
但是，其实这根本不是问题，要黑肯定不是为了你那点流量和隐私，你们应该懂的。
