### ISSUE TITLE
登陆不了facebook

### ISSUE THREAD

**Issue by szh7379** [XX-net/XX-Net#114]
火狐chrome都不行，应该是代理的问题了。还有能加上PAC模式吗，日志里好像有自动下载gfwlist，为什么不加上自动代理，enable后，一看是全局啊

**Comment by xxnet** [comment]
登录问题，问题已经确认，之前的版本反而没有问题。
我尽快研究解决。

在 2015年4月6日 上午7:52，Zhen Sun <notifications@github.com>写道：

**Comment by xxnet** [comment]
已经解决 1.7.2修复，请下载新版测试。
稳定后会推送自动升级
