### ISSUE TITLE
请问在什么模式下效果最理想？

### ISSUE THREAD

**Issue by Tristanovo** [XX-net/XX-Net#11402]
是全局自能路由代理还是用取消全局代理配合代理切换插件效果好？
如果用第二种的话还会同步扩展和书签吗？chrome
还有第三个问题，就是每次打开浏览器那个代理切换插件都是默认选到smart-router上，这个和proxy比有什么好处吗？
谢谢

**Comment by tmttmd** [comment]
当然是用插件最好了，可以自己设置走代理的网站，智能路由具体有什么用我也不太清楚，猜测可能是综合了x-tunnel和GAE，可以两者间自动切换，并且带有一个截拦广告我也是现在每次打开浏览器都会默认切换到智能路由，感觉上使用智能路由时打开部分网站时会慢一点，如我直连打开github比智能路由要快所以现在一般都是用自动切换模式的，以上纯属个人经验。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/9501

**Comment by SeaHOH** [comment]
各有各的缘法
