### ISSUE TITLE
求助：ios10 无法使用XX-net远程代理

### ISSUE THREAD

**Issue by jhhuang96** [XX-net/XX-Net#11408]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E277 Safari/602.1
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:7 h2:0
scan-ip-thread-num: 1
ip-quality: 601
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
----------------------------------------------------------------------------------------------------------------
①完成ios设备的证书导入
②在通用设置里已经信任证书
③.在xx-net\data\gae_proxy\建立manual.ini的文件
④Safari 打开http://192.168.X.XXX:8086/proxy.pac 能看到内容
⑤在ios-wifi设置里已经添加HTTP代理--自动--URL：http://192.168.X.XXX:8086/proxy.pac

But！！！！！
当我打开http://192.168.X.XXX:8085提示证书fail，浏览器代理设置fail。
（PS：电脑端的XX-net版本为3.12.11）

**Comment by SeaHOH** [comment]
能访问谷歌不？

**Comment by jhhuang96** [comment]
@SeaHOH  不可以诶

**Comment by AnyWAT** [comment]
😜貌似从3.10.5开始不再支持 manual.ini

**Comment by jhhuang96** [comment]
@AnyWAT 我是自己创建的manual.ini。  意思是3.10.5之后，自己创建的manual.ini也法没用ios设备远程代理了吗？ 我需要降级xx-net的版本？

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/为其他设备提供代理服务

**Comment by SeaHOH** [comment]
好像不是上面这个问题，iPhone 已成功远程连接。

**Comment by SeaHOH** [comment]
日志贴出来看看

**Comment by jhhuang96** [comment]
@SeaHOH 
Sep 02 12:48:43.772 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=y%2BedZnDZ70t60fYbcgFq9g%3D%3D from:127.0.0.1:5415
Sep 02 12:48:44.111 - [INFO] GAE t:338 s:857 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=y%2BedZnDZ70t60fYbcgFq9g%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2001:569:2:a::10,0:h1_req,0:h1_req_sended,335:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:3750],:1
Sep 02 12:48:44.112 - [DEBUG] recheck_ip:2405:4800:100:4::d restore ok
Sep 02 12:48:44.319 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=y%2BedZnDZ70t60fYbcgFq9g%3D%3D from:127.0.0.1:5415
Sep 02 12:48:44.639 - [INFO] GAE t:319 s:869 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=y%2BedZnDZ70t60fYbcgFq9g%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2620:11a:a00e:2::1f,0:h1_req,0:h1_req_sended,318:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:3999],:0
Sep 02 12:48:44.846 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=y%2BedZnDZ70t60fYbcgFq9g%3D%3D from:127.0.0.1:5415

**Comment by SeaHOH** [comment]
好像正常，这是从 iPhone 使用的日志吗？
要不你重启下 XX-Net，把 PC 上其它浏览器全部关闭，然后用 iPhone 访问下谷歌，再把所有日志贴出来。

**Comment by AnyWAT** [comment]
1、如果通过不再支持的 manual.ini 设置而不是 https://github.com/XX-net/XX-Net/issues/11408#issuecomment-417904546 操作，貌似不会正常？检验：贴 data\launcher\config.yaml 及 data\gae_proxy\config.json 内容（马赛克隐私部分）
2、试试关闭某开关 #11291

**Comment by jhhuang96** [comment]
@SeaHOH 
Sep 02 13:11:15.028 - [INFO] remove_slowest_ip:2806:10a8:cfff:5::13 handshake_time:851, fails:0
Sep 02 13:11:15.957 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11
Sep 02 13:11:16.348 - [DEBUG] report_connect_fail IPv4 continue_fail_count:12
Sep 02 13:11:16.984 - [INFO] scan_ip add ip:2001:918:ffaa:3::f time:552 h2:0
Sep 02 13:11:16.984 - [INFO] remove_slowest_ip:2a02:2518:4:875::f handshake_time:835, fails:0
Sep 02 13:11:17.090 - [DEBUG] network IPv4 is ok, cost:1132 ms

**Comment by SeaHOH** [comment]
> 你重启下 XX-Net，把 PC 上其它浏览器全部关闭，然后用 iPhone 访问下谷歌，再把所有日志贴出来。

**Comment by SeaHOH** [comment]
访问脸书也可以，但是需要完整日志， iPhone 这么难用么？

**Comment by carlchan99** [comment]
代理设为192.168.X.XXX，端口设为8086或8087，不要用pac自动代理试一试。
