### ISSUE TITLE
两个appid一个超额之后另一个不能访问google

### ISSUE THREAD

**Issue by zhangchutian** [XX-net/XX-Net#11400]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3493.3 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:27
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 572
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

600:gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/

**Comment by SeaHOH** [comment]
日志不完整

**Comment by zhangchutian** [comment]
Sep 01 18:51:07.881 - [DEBUG] network IPv6 is ok, cost:5788 ms

Sep 01 18:51:09.800 - [DEBUG] network IPv4 is ok, cost:8424 ms

Sep 01 18:51:26.164 - [INFO] ------------------------------------------------------

Sep 01 18:51:26.164 - [INFO] Python Version : 2.7.13

Sep 01 18:51:26.164 - [INFO] OS : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0

Sep 01 18:51:26.164 - [INFO] Listen Address : 127.0.0.1:8087

Sep 01 18:51:26.164 - [INFO] GAE APPID : this-is-my-project-213706 | certain-beach-213706

Sep 01 18:51:26.164 - [INFO] ------------------------------------------------------

Sep 01 18:51:27.787 - [DEBUG] Importing CA

Sep 01 18:51:27.787 - [DEBUG] Begin to import Windows CA

Sep 01 18:51:28.333 - [DEBUG] XX-Net CA already exists

Sep 01 18:51:28.364 - [INFO] SSL use version:TLSv1_2

Sep 01 18:51:28.379 - [INFO] OpenSSL support alpn

Sep 01 18:51:28.379 - [INFO] load ip range file:D:\xxnet\XX-Net-3.12.11\code\default\gae_proxy\local\ip_range.txt

Sep 01 18:51:28.442 - [INFO] load ip_list num:100, target num:100

Sep 01 18:51:28.520 - [INFO] SSL use version:TLSv1_2

Sep 01 18:51:28.520 - [INFO] server 127.0.0.1:8087 started.

Sep 01 18:51:32.732 - [INFO] scan_ip add ip:2001:ee0:3202:1::11 time:577 h2:0

Sep 01 18:51:32.732 - [INFO] remove_slowest_ip:2800:370:10:16::f handshake_time:939, fails:13

Sep 01 18:51:32.810 - [INFO] scan_ip add ip:2001:16a0:102:106::10 time:592 h2:0

Sep 01 18:51:32.810 - [INFO] remove_slowest_ip:2402:800:6350:1::12 handshake_time:1417, fails:11

Sep 01 18:51:36.361 - [INFO] scan_ip add ip:2804:14c:87f9:3::d time:556 h2:0

Sep 01 18:51:36.361 - [INFO] remove_slowest_ip:2001:16a0:202:10b::c handshake_time:1087, fails:12

Sep 01 18:51:38.559 - [DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=d89f84a9-8e09-41f2-b68b-743f8c3b863c&version=3.12.11&platform=Windows-7-6.1.7601-SP1 from:127.0.0.1:49405

Sep 01 18:51:39.365 - [INFO] scan_ip add ip:2607:f798:1e:1400::e time:368 h2:0

Sep 01 18:51:39.365 - [INFO] remove_slowest_ip:2001:16a0:202:107::11 handshake_time:1085, fails:12

Sep 01 18:51:40.501 - [DEBUG] create_ssl update ip:2001:ee0:3202:3::c time:1427 h2:0 sni:kitchen-voice.ml, host:

Sep 01 18:51:41.085 - [DEBUG] create_ssl update ip:2001:ee0:3202:1::11 time:1000 h2:0 sni:consist.sweet.range.us, host:

Sep 01 18:51:42.123 - [INFO] DIRECT t:3563 s:1674 200 xxnet-update.appspot.com /update.json?uuid=d89f84a9-8e09-41f2-b68b-743f8c3b863c&version=3.12.11&platform=Windows-7-6.1.7601-SP1

Sep 01 18:51:44.515 - [DEBUG] create_ssl update ip:2607:f8b0:400f:e::b time:5949 h2:0 sni:satisfaction.impact.entry.com, host:

Sep 01 18:51:44.598 - [DEBUG] report_connect_fail:2804:14c:87f9:3::d

Sep 01 18:51:44.598 - [DEBUG] connect 2804:14c:87f9:3::d fail:error("conn fail, sni:sectorpsychologystep.us, top: e:timeout('timed out',)",)

Sep 01 18:51:44.789 - [INFO] scan_ip add ip:2402:800:6350:9::10 time:564 h2:0

Sep 01 18:51:44.790 - [INFO] remove_slowest_ip:2001:8002:e21:e101::e handshake_time:1518, fails:0

Sep 01 18:51:44.823 - [INFO] scan_ip add ip:2402:800:6350:13::13 time:588 h2:0

Sep 01 18:51:44.823 - [INFO] remove_slowest_ip:2001:2f8:0:15::10 handshake_time:1996, fails:0

Sep 01 18:51:46.154 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token from:127.0.0.1:49445

Sep 01 18:51:46.998 - [DEBUG] create_ssl update ip:2607:f798:1e:1400::e time:823 h2:0 sni:refrigerator-lack-area.net, host: certain-beach-213706.appspot.com

Sep 01 18:51:47.220 - [INFO] scan_ip add ip:2607:f798:1e:400::e time:293 h2:0

Sep 01 18:51:47.220 - [INFO] remove_slowest_ip:2610:28:42c:100::e handshake_time:888, fails:0

Sep 01 18:51:47.626 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt from:127.0.0.1:49451

Sep 01 18:51:47.741 - [DEBUG] create_ssl update ip:2402:800:6350:9::10 time:1057 h2:0 sni:following.apartment.ml, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:48.106 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:48.106 - [WARNING] APPID ' certain-beach-213706' out of Quota, remove it. 2607:f798:1e:1400::e

Sep 01 18:51:48.106 - [WARNING] report_out_of_quota: certain-beach-213706

Sep 01 18:51:48.106 - [DEBUG] 2607:f798:1e:1400::e worker close:appid out of quota: certain-beach-213706

Sep 01 18:51:48.106 - [DEBUG] GAE_Exception 604 'appid out of quota: certain-beach-213706'

Sep 01 18:51:48.106 - [WARNING] gae_exception:'604:appid out of quota: certain-beach-213706' https://www.googleapis.com/oauth2/v4/token

Sep 01 18:51:48.467 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:48.469 - [WARNING] IP:2402:800:6350:9::10 not support GAE, headers:{'Date': 'Sat, 01 Sep 2018 10:51:32 GMT', 'Content-Length': '1555', 'Referrer-Policy': 'no-referrer', 'Content-Type': 'text/html; charset=UTF-8', 'Connection': 'close'} status:400

Sep 01 18:51:48.470 - [DEBUG] report_connect_fail:2402:800:6350:9::10

Sep 01 18:51:48.658 - [DEBUG] create_ssl update ip:2402:800:6350:13::13 time:1086 h2:0 sni:reputation-safety-option.com, host: certain-beach-213706.appspot.com

Sep 01 18:51:48.985 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token from:127.0.0.1:49468

Sep 01 18:51:49.034 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token from:127.0.0.1:49469

Sep 01 18:51:49.035 - [DEBUG] 2607:f798:1e:1400::e worker close:exit

Sep 01 18:51:49.547 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:49.547 - [WARNING] APPID ' certain-beach-213706' out of Quota, remove it. 2402:800:6350:13::13

Sep 01 18:51:49.547 - [WARNING] report_out_of_quota: certain-beach-213706

Sep 01 18:51:49.547 - [DEBUG] 2402:800:6350:13::13 worker close:appid out of quota: certain-beach-213706

Sep 01 18:51:49.547 - [DEBUG] GAE_Exception 604 'appid out of quota: certain-beach-213706'

Sep 01 18:51:49.547 - [WARNING] gae_exception:'604:appid out of quota: certain-beach-213706' https://www.googleapis.com/oauth2/v4/token

Sep 01 18:51:49.688 - [DEBUG] 2402:800:6350:13::13 worker close:exit

Sep 01 18:51:49.688 - [DEBUG] GAE POST https://accounts.google.com/ListAccounts?gpsia=1&source=durations_metrics,counter:3,load_time_ms:16417&json=standard from:127.0.0.1:49473

Sep 01 18:51:50.106 - [DEBUG] recheck_ip:2402:800:6350:9::10 restore ok

Sep 01 18:51:50.106 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:50.106 - [DEBUG] 2402:800:6350:9::10 worker close:ip not support GAE

Sep 01 18:51:50.106 - [DEBUG] GAE_Exception 602 'ip not support GAE'

Sep 01 18:51:50.106 - [WARNING] gae_exception:'602:ip not support GAE' https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

Sep 01 18:51:50.122 - [WARNING] 2402:800:6350:9::10 h1_request:error(9, 'Bad file descriptor') inactive_time:2 task.timeout:30

Sep 01 18:51:50.122 - [WARNING] 2402:800:6350:9::10 trace: 0:connect, 1073:init, 348:request, 361:Res, 3:request,:1651, processed:1, transfered:1645, sni:following.apartment.ml

Sep 01 18:51:50.122 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:50.122 - [DEBUG] 2402:800:6350:9::10 worker close:down fail

Sep 01 18:51:50.219 - [INFO] scan_ip add ip:2001:ee0:3204:5::d time:578 h2:0

Sep 01 18:51:50.219 - [INFO] remove_slowest_ip:2001:8002:e22:ef01::e handshake_time:1375, fails:11

Sep 01 18:51:50.406 - [DEBUG] create_ssl update ip:2607:f798:1e:400::e time:780 h2:0 sni:bonusconference.net, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:50.780 - [DEBUG] 2402:800:6350:9::10 worker close:exit

Sep 01 18:51:51.799 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:51.799 - [WARNING] IP:2607:f798:1e:400::e not support GAE, headers:{'Date': 'Sat, 01 Sep 2018 10:51:36 GMT', 'Content-Length': '1555', 'Referrer-Policy': 'no-referrer', 'Content-Type': 'text/html; charset=UTF-8', 'Connection': 'close'} status:400

Sep 01 18:51:51.799 - [DEBUG] report_connect_fail:2607:f798:1e:400::e

Sep 01 18:51:52.111 - [DEBUG] create_ssl update ip:2001:8002:e51:ef02::d time:1973 h2:0 sni:appearancedescription.com, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:52.362 - [DEBUG] create_ssl update ip:2607:f798:1e:1400::e time:804 h2:0 sni:patient.woman.com, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:52.946 - [DEBUG] recheck_ip:2607:f798:1e:400::e restore ok

Sep 01 18:51:52.946 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:52.946 - [DEBUG] 2607:f798:1e:400::e worker close:ip not support GAE

Sep 01 18:51:52.946 - [DEBUG] GAE_Exception 602 'ip not support GAE'

Sep 01 18:51:52.946 - [WARNING] gae_exception:'602:ip not support GAE' https://www.googleapis.com/oauth2/v4/token

Sep 01 18:51:52.961 - [WARNING] 2607:f798:1e:400::e h1_request:error(9, 'Bad file descriptor') inactive_time:1 task.timeout:30

Sep 01 18:51:52.961 - [WARNING] 2607:f798:1e:400::e trace: 0:connect, 812:init, 1105:request, 256:Res, 0:request,:1161, processed:1, transfered:1645, sni:bonusconference.net

Sep 01 18:51:52.961 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:52.961 - [DEBUG] 2607:f798:1e:400::e worker close:down fail

Sep 01 18:51:53.106 - [DEBUG] report_connect_fail:2001:16a0:202:101::13

Sep 01 18:51:53.106 - [DEBUG] connect 2001:16a0:202:101::13 fail:error("conn fail, sni:whole-loan.us, top:this-is-my-project-213706 .appspot.com e:timeout('timed out',)",)

Sep 01 18:51:53.475 - [DEBUG] 2607:f798:1e:400::e worker close:exit

Sep 01 18:51:53.560 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:53.561 - [WARNING] IP:2001:8002:e51:ef02::d not support GAE, headers:{'Date': 'Sat, 01 Sep 2018 10:51:38 GMT', 'Content-Length': '1555', 'Referrer-Policy': 'no-referrer', 'Content-Type': 'text/html; charset=UTF-8', 'Connection': 'close'} status:400

Sep 01 18:51:53.562 - [DEBUG] report_connect_fail:2001:8002:e51:ef02::d

Sep 01 18:51:53.614 - [DEBUG] report_connect_fail:2001:16a0:202:10c::f

Sep 01 18:51:53.614 - [DEBUG] connect 2001:16a0:202:10c::f fail:error("conn fail, sni:god.quarter.org, top:this-is-my-project-213706 .appspot.com e:timeout('timed out',)",)

Sep 01 18:51:53.833 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:53.833 - [WARNING] IP:2607:f798:1e:1400::e not support GAE, headers:{'Date': 'Sat, 01 Sep 2018 10:51:38 GMT', 'Content-Length': '1555', 'Referrer-Policy': 'no-referrer', 'Content-Type': 'text/html; charset=UTF-8', 'Connection': 'close'} status:400

Sep 01 18:51:53.834 - [DEBUG] report_connect_fail:2607:f798:1e:1400::e

Sep 01 18:51:54.113 - [DEBUG] report_connect_fail:2001:16a0:102:106::10

Sep 01 18:51:54.113 - [DEBUG] connect 2001:16a0:102:106::10 fail:error("conn fail, sni:playliterature.net, top:this-is-my-project-213706 .appspot.com e:timeout('timed out',)",)

Sep 01 18:51:54.672 - [DEBUG] report_connect_fail:2001:16a0:102:10a::13

Sep 01 18:51:54.672 - [DEBUG] connect 2001:16a0:102:10a::13 fail:error("conn fail, sni:royal.singer.ml, top:this-is-my-project-213706 .appspot.com e:timeout('timed out',)",)

Sep 01 18:51:54.732 - [DEBUG] create_ssl update ip:2001:ee0:3204:5::d time:1054 h2:0 sni:nurse-shoulder.org, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:54.990 - [DEBUG] recheck_ip:2607:f798:1e:1400::e restore ok

Sep 01 18:51:54.992 - [DEBUG] 2607:f798:1e:1400::e worker close:ip not support GAE

Sep 01 18:51:54.992 - [DEBUG] GAE_Exception 602 'ip not support GAE'

Sep 01 18:51:54.993 - [WARNING] 2607:f798:1e:1400::e h1_request:error(9, 'Bad file descriptor') inactive_time:1 task.timeout:30

Sep 01 18:51:54.993 - [WARNING] 2607:f798:1e:1400::e trace: 0:connect, 1632:init, 388:request, 270:Res, 0:request,:1158, processed:1, transfered:1645, sni:patient.woman.com

Sep 01 18:51:54.993 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:54.993 - [WARNING] retry but responsed. POST None/_gh/

Sep 01 18:51:54.993 - [WARNING] gae_exception:'602:ip not support GAE' https://www.googleapis.com/oauth2/v4/token

Sep 01 18:51:55.045 - [WARNING] stack:'[\' File "D:\\\\xxnet\\\\XX-Net-3.12.11\\\\code\\\\default\\\\python27\\\\1.0\\\\lib\\\\threading.py", line 774, in __bootstrap\\n self.__bootstrap_inner()\\n\', \' File "D:\\\\xxnet\\\\XX-Net-3.12.11\\\\code\\\\default\\\\python27\\\\1.0\\\\lib\\\\threading.py", line 801, in __bootstrap_inner\\n self.run()\\n\', \' File "D:\\\\xxnet\\\\XX-Net-3.12.11\\\\code\\\\default\\\\python27\\\\1.0\\\\lib\\\\threading.py", line 754, in run\\n self.__target(*self.__args, **self.__kwargs)\\n\', \' File "D:\\\\xxnet\\\\XX-Net-3.12.11\\\\code\\\\default\\\\python27\\\\1.0\\\\lib\\\\noarch\\\\front_base\\\\http1.py", line 112, in work_loop\\n self.request_task(task)\\n\', \' File "D:\\\\xxnet\\\\XX-Net-3.12.11\\\\code\\\\default\\\\python27\\\\1.0\\\\lib\\\\noarch\\\\front_base\\\\http1.py", line 157, in request_task\\n self.retry_task_cb(task)\\n\', \' File "D:\\\\xxnet\\\\XX-Net-3.12.11\\\\code\\\\default\\\\python27\\\\1.0\\\\lib\\\\noarch\\\\front_base\\\\http_dispatcher.py", line 268, in retry_task_cb\\n st = traceback.extract_stack()\\n\']'

Sep 01 18:51:55.045 - [DEBUG] 2607:f798:1e:1400::e worker close:down fail

Sep 01 18:51:55.181 - [DEBUG] 2607:f798:1e:1400::e worker close:exit

Sep 01 18:51:55.273 - [DEBUG] create_ssl update ip:2402:800:6350:13::13 time:1092 h2:0 sni:conversationguitar.us, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:55.331 - [DEBUG] recheck_ip:2001:8002:e51:ef02::d restore ok

Sep 01 18:51:55.333 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:55.333 - [DEBUG] 2001:8002:e51:ef02::d worker close:ip not support GAE

Sep 01 18:51:55.333 - [DEBUG] GAE_Exception 602 'ip not support GAE'

Sep 01 18:51:55.333 - [WARNING] gae_exception:'602:ip not support GAE' https://accounts.google.com/ListAccounts?gpsia=1&source=durations_metrics,counter:3,load_time_ms:16417&json=standard

Sep 01 18:51:55.334 - [WARNING] 2001:8002:e51:ef02::d h1_request:error(9, 'Bad file descriptor') inactive_time:2 task.timeout:20

Sep 01 18:51:55.334 - [WARNING] 2001:8002:e51:ef02::d trace: 0:connect, 2019:init, 1016:request, 389:Res, 2:request,:1769, processed:1, transfered:1646, sni:appearancedescription.com

Sep 01 18:51:55.334 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:55.334 - [DEBUG] 2001:8002:e51:ef02::d worker close:down fail

Sep 01 18:51:56.430 - [DEBUG] create_ssl update ip:2620:11a:a018:2::e time:1748 h2:0 sni:world.campaign.period.ml, host:this-is-my-project-213706 .appspot.com

Sep 01 18:51:57.055 - [DEBUG] report_connect_fail:2001:16a0:102:108::f

Sep 01 18:51:57.055 - [DEBUG] connect 2001:16a0:102:108::f fail:error("conn fail, sni:draw-wheel-night.net, top:this-is-my-project-213706 .appspot.com e:timeout('timed out',)",)

Sep 01 18:51:57.206 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:57.206 - [WARNING] IP:2402:800:6350:13::13 not support GAE, headers:{'Date': 'Sat, 01 Sep 2018 10:51:41 GMT', 'Content-Length': '1555', 'Referrer-Policy': 'no-referrer', 'Content-Type': 'text/html; charset=UTF-8', 'Connection': 'close'} status:400

Sep 01 18:51:57.206 - [DEBUG] report_connect_fail:2402:800:6350:13::13

Sep 01 18:51:57.572 - [WARNING] task POST None /_gh/ timeout

Sep 01 18:51:57.572 - [WARNING] IP:2620:11a:a018:2::e not support GAE, headers:{'Date': 'Sat, 01 Sep 2018 10:51:42 GMT', 'Content-Length': '1555', 'Referrer-Policy': 'no-referrer', 'Content-Type': 'text/html; charset=UTF-8', 'Connection': 'close'} status:400

Sep 01 18:51:57.572 - [DEBUG] report_connect_fail:2620:11a:a018:2::e

Sep 01 18:51:59.021 - [DEBUG] recheck_ip:2620:11a:a018:2::e restore ok

Sep 01 18:51:59.021 - [WARNING] retry_task_cb: POST None/_gh/

Sep 01 18:51:59.021 - [DEBUG] 2620:11a:a018:2::e worker close:ip not support GAE

Sep 01 18:51:59.021 - [DEBUG] GAE_Exception 602 'ip not support GAE'

Sep 01 18:51:59.021 - [WARNING] gae_exception:'602:ip not support GAE' https://www.googleapis.com/oauth2/v4/token

**Comment by zhangchutian** [comment]
这些日志信息可以吗

**Comment by SeaHOH** [comment]
我刚用你这两个 ID 试了一下，能正常识别出超配额 ID，剩下一个 ID 自动调用，能正常访问谷歌。

你这样操作一下：删除 data/gae_proxy/good_ip.txt 重启 XX-Net 等待扫描。

**Comment by zhangchutian** [comment]
删除good_ip之后重启xxnet。还是不可以访问google
600:gae_exception:'600:fetch gae fail' https://www.google.com/gae_exception:'602:ip not support GAE' https://www.google.com/gae_exception:'600:fetch gae fail' https://www.google.com/

**Comment by SeaHOH** [comment]
有点奇怪，你重新配置 ID 试试，去除那个超额的。

**Comment by SeaHOH** [comment]
美国时间零点

**Comment by SeaHOH** [comment]
没法复现，关了哈。还有问题可以直接回复。
