### ISSUE TITLE
收到g的邮件称app engine的版本过期，不再支持，若不升级将关闭。。。

### ISSUE THREAD

**Issue by GLingDroid** [XX-net/XX-Net#11401]
Hello Google App Engine Standard Environment Customer,

We’re writing to let you know that we are deprecating Go 1.6 and Go 1.8 support on App Engine, and new deployments using these language versions will no longer be available on November 1, 2018.

Go 1.6 and 1.8 are no longer supported and do not receive updates or security fixes from the open source Go Programming Language project. Per our deprecation policy, we will stop accepting new deployments that use these unsupported language versions on November 1, 2018.

What do I need to know?
Starting on November 1, 2018, you will no longer be able to deploy new versions of App Engine Standard applications that use Go 1.6 or Go 1.8. Applications that have already been deployed using Go 1.6 or Go 1.8 will continue to run for now. However, we recommend re-deploying with a supported language version in all cases.

We are in the process of scheduling the shut down of already deployed applications that use Go 1.6 and 1.8 in 2019. Later this year, we will be making a separate announcement.

What do I need to do?
Please re-deploy your App Engine Standard applications using Go 1.9 before November 1, 2018. You can learn more about upgrading your application at the Go Release History site, in particular about adopting the context package introduced to the standard library in Go 1.7.

The following projects linked with your account use a version of Go on App Engine that are affected by this deprecation:

这里是受影响的appid

If you have any questions or require assistance, please reply to this email to contact Google Cloud Support.

Thank you for being a valued App Engine customer.

当初用g0pr0xy重新部署过一次，后来xxnet不重新部署一直可用就没管。
可看了下，好像app engine的服务端都是python的，g0pr0xy的服务端上传源码那边就一个 gae.go啊，
访问 https://(具体的appid).appengine.com给出的是这样：
{
    "type": "appengine(go1.8.3 (appengine-20170809), linux/amd64)",
    "host": "(具体的appid).appspot.com",
    "software": "Google App Engine/1.9.54",
    "error": "API error 7 (urlfetch: DNS_ERROR)"
}
访问 https://(具体的appid).appspot.com/ 给出的是这样：
{
	"server": "goproxy r101 (go1.8.3 (appengine-20170809), linux/amd64)"
	"latest": "",
	"deploy": "2017-10-15T11:00:18Z",
	"message": "unable check goproxy latest version, please try after 5 minutes."
}

所以这到底是针对服务端还是客户端啊？ 
有哪些影响？需要用xxnet重新部署么？

**Comment by yeezylife** [comment]
关注 我查了下邮箱好像没收到类似消息

**Comment by SeaHOH** [comment]
人家邮件讲得很明白，是 Go 语言，这和 XX-Net 没关系，重新部署就行。
