### ISSUE TITLE
xvideo上的视频没有播放键

### ISSUE THREAD

**Issue by duabaoji** [XX-net/XX-Net#11419]
YouTube没有问题。就这个站的视频点进去就只有个jpg。。

**Comment by fewewf** [comment]
兄弟，我3，4天前就发现了。。

**Comment by GoodSake** [comment]
网址是啥？

**Comment by cxz111111** [comment]
斗宗强者，竟恐怖如斯！

**Comment by SeaHOH** [comment]
嗯，没法，请求播放器网址大机率失败，原因未知。

**Comment by AnyWAT** [comment]
😜试了试，视频列表（本身？）没有播放键，鼠标悬停会播放动画，点开后有播放键呢。当然，默认被扩展诸如 ScriptSafe 控制而画面不能正常显示而已。。。

**Comment by yydxwt** [comment]
点进去也不会播放的　以前能播放也不能调节音量大小　只能打开或关闭声音　直接访问时可以调节　这两种访问方式显示的播放控件是不一样的

**Comment by linronaldo** [comment]
我也有同样的问题 还以为是我的浏览器的java 还是flash的问题呢

**Comment by AnyWAT** [comment]
就这个站的视频点进去就只有个jpg。。——莫非与近期大陆区的必装国内版的Adobe Flash Player 有关？

**Comment by reniastyc** [comment]
> 
> 
> 就这个站的视频点进去就只有个jpg。。——莫非与近期大陆区的必装国内版的Adobe Flash Player 有关？

兄弟解决了吗？

**Comment by AnyWAT** [comment]
😜没，也基本不到那网，再说 X-Tunnel 是🆗的

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/45589231-df53c280-b954-11e8-87c1-cbea062649b0.png)

**Comment by 2609665** [comment]
@duabaoji 播放键已经恢复了~

**Comment by AnyWAT** [comment]
😂原来被楼上私藏了？

**Comment by linronaldo** [comment]
到底咋回事儿



Sent from myMail for iOS


Thursday, 20 September 2018, 14:32 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by SeaHOH** [comment]
多半是网站自己限制的，或者设置错误。
