### ISSUE TITLE
mac使用start启动后，不用了需要关闭吗？怎么关闭？

### ISSUE THREAD

**Issue by HuangYangYang1** [XX-net/XX-Net#11416]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by Pd69bq** [comment]
杀的话以前的版本在进程中会有一个proxy.py 我看现在的start脚本里是nohup ${PYTHON} code/${VERSION}/launcher/start.py $@>/dev/null 2>&1 &
那么应该可以ps -ef |grep start.py来找 就是不知道start.py会不会调用其它的脚本

**Comment by SeaHOH** [comment]
8085 点退出，直接发`/quit`也行。

**Comment by HuangYangYang1** [comment]
你们好，我昨天发现，start后状态栏会有一个新的图标，右键关闭就可以了，谢谢你们
