### ISSUE TITLE
日亚会员音乐听不了，说有地域限制，还有些其他网站也是，必须用境外的IP地址才能上，用收费的VPN时查看自己的IP是境外的，XX-NET能做到吗？具体要怎么操作？

### ISSUE THREAD

**Issue by sd6644773** [XX-net/XX-Net#11410]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by Huanglongchun** [comment]
全局应该就可以，再在百度搜索ip，应该会显示境外ip

**Comment by sd6644773** [comment]
谢谢 试过了   美国IP

**Comment by SeaHOH** [comment]
关闭后仍可回复
