### ISSUE TITLE
重新部署

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#11420]
我有16个gmail，每个有12个appid。听说600错误是没重新部署的原因引发的。
我决定重新部署所有appid:
1. 打开XX-Net 3.12.11.
2. 将第1个gmail的12个appid以appid1|appid2...appid12填写到xx-net的部署服务端->授权->GAE AppID，然后点击开始部署，xx-net暂停，弹出登陆gmail页面，登陆到第1个gmail账号，xx-net继续部署了。
...
3. 16个gmail的appid重新部署完成！

**Comment by AnyWAT** [comment]
🤣600错误是连接池太小或延时太大的锅
使用XX-Net 某以后版本，appid（服务端）需更新到3.3.5

**Comment by AnyWAT** [comment]
😜问了几次也不见回：5年不关机。。。

**Comment by SeaHOH** [comment]
看来没法白得把石锤

**Comment by AnyWAT** [comment]
开机去了🙃
