### ISSUE TITLE
有效 IPv6 IP 数 只有1

### ISSUE THREAD

**Issue by answer1** [XX-net/XX-Net#11423]
昨天开始外网上不去，显示“XX-Net 3.12.11，一切正常，你可以访问真正的互联网了，”打开google、youtube都出现“600:gae_exception”，有效 IPv6 IP数 = 1，IP延迟 9999。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
一部分日志：
Aug 05 11:20:20.892 - [DEBUG] report_connect_fail:2001:b000:182:c101::10

Aug 05 11:20:20.893 - [DEBUG] connect 2001:b000:182:c101::10 fail:error("conn fail, sni:reviewsingleperformance.ml, top: e:timeout('timed out',)",)

Aug 05 11:20:21.170 - [DEBUG] report_connect_fail:2001:b032:5d01::f

Aug 05 11:20:21.170 - [DEBUG] connect 2001:b032:5d01::f fail:error("conn fail, sni:knowledgehead.com, top:excellent-bolt-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:21.232 - [WARNING] task POST None /_gh/ timeout

Aug 05 11:20:21.232 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Aug 05 11:20:21.232 - [WARNING] gae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.ico

Aug 05 11:20:21.232 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.ico"

Aug 05 11:20:21.232 - [WARNING] GAE GET https://www.youtube.com/favicon.ico request fail:"600:gae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.ico"

Aug 05 11:20:21.233 - [WARNING] send response fail

Aug 05 11:20:21.233 - [WARNING] send response fail

Aug 05 11:20:21.584 - [DEBUG] report_connect_fail:2001:b032:c100:2::c

Aug 05 11:20:21.585 - [DEBUG] connect 2001:b032:c100:2::c fail:error("conn fail, sni:injuryfigure.us, top: e:timeout('timed out',)",)

Aug 05 11:20:22.155 - [DEBUG] report_connect_fail:2001:8002:e22:ef03::11

Aug 05 11:20:22.156 - [DEBUG] connect 2001:8002:e22:ef03::11 fail:error("conn fail, sni:bluefriend.org, top:my-project-4-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:22.329 - [WARNING] task POST None /_gh/ timeout

Aug 05 11:20:22.329 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Aug 05 11:20:22.329 - [WARNING] gae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.ico

Aug 05 11:20:22.329 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.ico"

Aug 05 11:20:22.329 - [WARNING] GAE GET https://www.youtube.com/favicon.ico request fail:"600:gae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.icogae_exception:'600:fetch gae fail' https://www.youtube.com/favicon.ico"

Aug 05 11:20:22.331 - [WARNING] send response fail

Aug 05 11:20:22.754 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

Aug 05 11:20:22.757 - [DEBUG] report_connect_fail:2001:b000:1e0:c100::e

Aug 05 11:20:22.757 - [DEBUG] connect 2001:b000:1e0:c100::e fail:error("conn fail, sni:campaign.habit.rip.net, top: e:timeout('timed out',)",)

Aug 05 11:20:23.461 - [DEBUG] network IPv6 is ok, cost:703 ms

Aug 05 11:20:23.553 - [DEBUG] report_connect_fail:2001:b032:8100::11

Aug 05 11:20:23.553 - [DEBUG] connect 2001:b032:8100::11 fail:error("conn fail, sni:televisioncallking.us, top:my-project-5-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:23.860 - [DEBUG] report_connect_fail:2001:b032:5d01::13

Aug 05 11:20:23.860 - [DEBUG] connect 2001:b032:5d01::13 fail:error("conn fail, sni:subjectweirdswitch.org, top: e:timeout('timed out',)",)

Aug 05 11:20:24.368 - [DEBUG] report_connect_fail:2001:b000:1e0:c100::10

Aug 05 11:20:24.369 - [DEBUG] connect 2001:b000:1e0:c100::10 fail:error("conn fail, sni:smoke.pool.cut.org, top:my-project-4-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:24.721 - [DEBUG] report_connect_fail:2001:b032:7100:1::c

Aug 05 11:20:24.721 - [DEBUG] connect 2001:b032:7100:1::c fail:error("conn fail, sni:elevator-half.ml, top: e:timeout('timed out',)",)

Aug 05 11:20:24.937 - [DEBUG] report_connect_fail:2001:b000:182:c100::c

Aug 05 11:20:24.938 - [DEBUG] connect 2001:b000:182:c100::c fail:error("conn fail, sni:replacementsail.net, top:aidoudou-162808.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:25.721 - [DEBUG] report_connect_fail:2001:b000:1e0:c101::c

Aug 05 11:20:25.721 - [DEBUG] connect 2001:b000:1e0:c101::c fail:error("conn fail, sni:review-independence-pen.net, top: e:timeout('timed out',)",)

Aug 05 11:20:26.228 - [DEBUG] report_connect_fail:2001:b000:1e0:c100::d

Aug 05 11:20:26.228 - [DEBUG] connect 2001:b000:1e0:c100::d fail:error("conn fail, sni:inspectorfeelingpark.org, top:warm-dynamics-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:26.828 - [DEBUG] report_connect_fail:2001:b032:5d00::d

Aug 05 11:20:26.828 - [DEBUG] connect 2001:b032:5d00::d fail:error("conn fail, sni:personal.research.ml, top: e:timeout('timed out',)",)

Aug 05 11:20:27.151 - [WARNING] not enough ip

Aug 05 11:20:27.335 - [DEBUG] report_connect_fail:2001:ee0:3201:7::12

Aug 05 11:20:27.335 - [DEBUG] connect 2001:ee0:3201:7::12 fail:error("conn fail, sni:savings-agreement-bottom.com, top:elaborate-helix-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:27.689 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

Aug 05 11:20:27.690 - [DEBUG] report_connect_fail:2400:d800:3:482::f

Aug 05 11:20:27.690 - [DEBUG] connect 2400:d800:3:482::f fail:error("conn fail, sni:hang-master-value.ml, top: e:timeout('timed out',)",)

Aug 05 11:20:28.337 - [DEBUG] network IPv6 is ok, cost:646 ms

Aug 05 11:20:28.766 - [DEBUG] report_connect_fail:2001:8002:e21:e101::e

Aug 05 11:20:28.767 - [DEBUG] connect 2001:8002:e21:e101::e fail:error("conn fail, sni:confidencebootcut.net, top: e:timeout('timed out',)",)

Aug 05 11:20:28.767 - [DEBUG] report_connect_fail:2001:b032:7100:1::f

Aug 05 11:20:28.767 - [DEBUG] connect 2001:b032:7100:1::f fail:error("conn fail, sni:devil-reach-screw.net, top:my-project-4-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:29.781 - [DEBUG] report_connect_fail:2607:f8b0:400a:9::f

Aug 05 11:20:29.781 - [DEBUG] connect 2607:f8b0:400a:9::f fail:error("conn fail, sni:network-number.ml, top: e:timeout('timed out',)",)

Aug 05 11:20:29.781 - [DEBUG] report_connect_fail:2404:6800:400a:a::9

Aug 05 11:20:29.782 - [DEBUG] connect 2404:6800:400a:a::9 fail:error("conn fail, sni:limit.debt.respect.ml, top:aidoudou-162808.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:30.719 - [WARNING] not enough ip

Aug 05 11:20:30.800 - [DEBUG] report_connect_fail:2001:8002:e21:ef01::12

Aug 05 11:20:30.801 - [DEBUG] connect 2001:8002:e21:ef01::12 fail:error("conn fail, sni:a-aspect-bat.us, top: e:timeout('timed out',)",)

Aug 05 11:20:30.801 - [DEBUG] report_connect_fail:2804:14d:14f9:7::13

Aug 05 11:20:30.802 - [DEBUG] connect 2804:14d:14f9:7::13 fail:error("conn fail, sni:hookgene.com, top:my-project-4-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:33.842 - [DEBUG] report_connect_fail:2404:6800:400c:2::9

Aug 05 11:20:33.842 - [DEBUG] connect 2404:6800:400c:2::9 fail:error("conn fail, sni:waithurryjoke.com, top: e:timeout('timed out',)",)

Aug 05 11:20:33.843 - [DEBUG] report_connect_fail:2001:d08:10:207::12

Aug 05 11:20:33.844 - [DEBUG] connect 2001:d08:10:207::12 fail:error("conn fail, sni:tacklesecurity.ml, top:my-project-5-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:33.844 - [DEBUG] report_connect_fail:2001:16a0:202:106::11

Aug 05 11:20:33.845 - [DEBUG] connect 2001:16a0:202:106::11 fail:error("conn fail, sni:devilgainanybody.us, top: e:timeout('timed out',)",)

Aug 05 11:20:35.874 - [DEBUG] report_connect_fail:2405:4800:100:38::10

Aug 05 11:20:35.874 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

Aug 05 11:20:35.874 - [DEBUG] connect 2405:4800:100:38::10 fail:error("conn fail, sni:entertainment.nurse.com, top:excellent-bolt-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:35.876 - [DEBUG] report_connect_fail:2607:f8b0:400a:1::13

Aug 05 11:20:35.876 - [DEBUG] connect 2607:f8b0:400a:1::13 fail:error("conn fail, sni:imagination-bug.net, top:excellent-bolt-162811.appspot.com e:timeout('timed out',)",)

Aug 05 11:20:36.471 - [DEBUG] network IPv6 is ok, cost:595 ms

Aug 05 11:20:37.161 - [WARNING] not enough ip

Aug 05 11:20:37.793 - [DEBUG] create ssl timeout fail.

Aug 05 11:20:40.729 - [WARNING] not enough ip

Aug 05 11:20:47.173 - [WARNING] not enough ip

Aug 05 11:20:50.740 - [WARNING] not enough ip

Aug 05 11:20:57.186 - [WARNING] not enough ip

Aug 05 11:21:00.754 - [WARNING] not enough ip

Aug 05 11:21:04.998 - [DEBUG] create ssl timeout fail.

Aug 05 11:21:06.982 - [DEBUG] create ssl timeout fail.

Aug 05 11:21:07.197 - [WARNING] not enough ip

Aug 05 11:21:10.767 - [WARNING] not enough ip

Aug 05 11:21:17.209 - [WARNING] not enough ip

Aug 05 11:21:18.778 - [DEBUG] create ssl timeout fail.

Aug 05 11:21:20.777 - [WARNING] not enough ip

Aug 05 11:21:27.221 - [WARNING] not enough ip

Aug 05 11:21:30.788 - [WARNING] not enough ip

Aug 05 11:21:37.231 - [WARNING] not enough ip

Aug 05 11:21:39.168 - [DEBUG] create ssl timeout fail.

Aug 05 11:21:40.800 - [WARNING] not enough ip

Aug 05 11:21:47.241 - [WARNING] not enough ip

Aug 05 11:21:50.808 - [WARNING] not enough ip

Aug 05 11:21:57.248 - [WARNING] not enough ip

Aug 05 11:22:00.817 - [WARNING] not enough ip

Aug 05 11:22:06.202 - [DEBUG] create ssl timeout fail.

Aug 05 11:22:07.263 - [WARNING] not enough ip

Aug 05 11:22:08.205 - [DEBUG] create ssl timeout fail.

Aug 05 11:22:10.830 - [WARNING] not enough ip

Aug 05 11:22:12.110 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Aug 05 11:22:13.155 - [DEBUG] network IPv4 is ok, cost:1042 ms

**Comment by SeaHOH** [comment]
你这跟没有差不多。
IPv6 是原生还是隧道？
不太可能是原生，应该还没封 IP。
建议使用 Teredo，或者换一个 Teredo 服务器。

**Comment by answer1** [comment]
我的应该是隧道吧，这个是使用了Teredo么。

**Comment by AnyWAT** [comment]
遵循了 #11291 的此刻🤣
gws-ip-num: total:520 ipv4:0 ipv6:520
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:45 h2:3
scan-ip-thread-num: 39
ip-quality: 253

**Comment by answer1** [comment]
已经切换到“Teredo 隧道优先”，还是没有变化。

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）

**Comment by answer1** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

**Comment by AnyWAT** [comment]
有效 IPv6 IP 数 只有1——或许再开一个XX-Net（可挤出前面貌似已累晕死？d）

**Comment by answer1** [comment]
意思是指重新双击打开程序？也没作用。

**Comment by SeaHOH** [comment]
再讲一次，换服务器。

**Comment by AnyWAT** [comment]
试试新大陆：管理权限运行 netsh int ipv6 set teredo enterpriseclient win1807.ipv6.microsoft.com.

**Comment by answer1** [comment]
两个代码都管理权限运行了，隧道也点击更换服务器，scan-ip-thread-num调到了一个中间值40，还是不行。我再试试更改DNS吧。

**Comment by SeaHOH** [comment]
没啥新大陆，`winxxxx.ipv6.microsoft.com`全是`onpremby2.ipv6.microsoft.com.akadns.net`。
`win10.ipv6.microsoft.com`这个才和其它不一样。

**Comment by AnyWAT** [comment]
两个代码都管理权限运行了，隧道也点击更换服务器——3次操作。。。😭

**Comment by SeaHOH** [comment]
自动切换后，如果服务器没变，请手动切换。

**Comment by answer1** [comment]
每次都不管用，就一个一个试了呀

**Comment by AnyWAT** [comment]
😂并非立竿见影，得检查IP或退出XX-Net、删除 good_ip.txt 后再开

**Comment by answer1** [comment]
难难难。。

**Comment by SeaHOH** [comment]
你还是试试有没有原生算了，好多地方都通了，看 #11411，不会设置路由器就 google。

**Comment by answer1** [comment]
恢复正常了，不过不确定哪一步操作对了：
重新安装了火狐浏览器，
电脑时间调回正常（刚发现之前取消了自动调整时间，一直定在8月份），
证书也重新导入（在证书管理器中选中"证书机构"，点击“导入”，之前都是手动导入）。
有几次Ipv6状态出现fail，隧道提示离线，手动切换能继续用。

**Comment by AnyWAT** [comment]
貌似系统时间不对，软件可能会不正常

**Comment by AnyWAT** [comment]
teredo.ngix.ne.kr和teredo.autotrans.consulintel.com早就关闭了。https://github.com/XX-net/XX-Net/issues/11411#issuecomment-418559738
teredo.ngix.ne.kr 19 ms 
teredo.autotrans.consulintel.com 5 ms

**Comment by SeaHOH** [comment]
@AnyWAT 你既然不信，为什么不试一试呢？

**Comment by AnyWAT** [comment]
楼主还好么？试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。
