### ISSUE TITLE
提示：目前国内大部分地区都开通了原生ipv6

### ISSUE THREAD

**Issue by SasamiMasakiJurai** [XX-net/XX-Net#11428]
目前很多地方都开通了原生ipv6

因此

推荐各位先进光猫查看下是否分配到了原生ipv6

如果有

那么可以设置光猫桥接到路由

由路由直接拨号并分配内网ipv6地址

这样可以省去因为微软隧道时断时续造成的麻烦

PS

国内ipv6污染已经很严重了

不要妄想有了ipv6地址就可以直接爬墙

另外

ipv6的dns污染已经开始进行中了

**Comment by SeaHOH** [comment]
提醒一点就是，别做违反法律的事，这个比精确制导还精确。

**Comment by SasamiMasakiJurai** [comment]
真要全匿名还是蛮复杂的

不过一般浏览还行 

不要长时间大流量的使用

例如看视频啥的

否则特征太明显了

很容易被封ip段

**Comment by timaxell** [comment]
现在支持外网IPv6的家用路由器普及了吗？
至少我手上的几个老TP-LINK/儿子水星/儿子迅捷的原版固件都不支持。斐讯K1/K2原版固件也不支持。
貌似有些国内品牌的国际版支持IPv6国内版就不支持。
路由器支持IPv6只是固件原因吧，是否和硬件无关？貌似看到很老的SoC的路由器第三方固件也声称可以支持IPv6
不爱用来源不明的改版非官方固件【除非是华硕半官方潘多拉或者是DD官方网站直接支持的型号，可是性价比都极低】

**Comment by SasamiMasakiJurai** [comment]
ipv6支持只是固件原因

其实只要知道处理器型号就可以自己安装openwrt固件了

**Comment by MitchellClark666** [comment]
> 目前很多地方都开通了原生ipv6
> 
> 因此
> 
> 推荐各位先进光猫查看下是否分配到了原生ipv6
> 
> 如果有
> 
> 那么可以设置光猫桥接到路由
> 
> 由路由直接拨号并分配内网ipv6地址
> 
> 这样可以省去因为微软隧道时断时续造成的麻烦
> 
> PS
> 
> 国内ipv6污染已经很严重了
> 
> 不要妄想有了ipv6地址就可以直接爬墙
> 
> 另外
> 
> ipv6的dns污染已经开始进行中了

你好，对路由器有什么要求吗？是否要有双拨号功能的？我的电脑直连光猫拨号，支持ipv6；但是路由器直连光猫，就不支持ipv6了。该怎么办呢？路由器型号：（思科 cisco CVR100W Wireless-N VPN Router）

**Comment by SasamiMasakiJurai** [comment]
> > 目前很多地方都开通了原生ipv6
> > 因此
> > 推荐各位先进光猫查看下是否分配到了原生ipv6
> > 如果有
> > 那么可以设置光猫桥接到路由
> > 由路由直接拨号并分配内网ipv6地址
> > 这样可以省去因为微软隧道时断时续造成的麻烦
> > PS
> > 国内ipv6污染已经很严重了
> > 不要妄想有了ipv6地址就可以直接爬墙
> > 另外
> > ipv6的dns污染已经开始进行中了
> 
> 你好，对路由器有什么要求吗？是否要有双拨号功能的？我的电脑直连光猫拨号，支持ipv6；但是路由器直连光猫，就不支持ipv6了。该怎么办呢？路由器型号：（思科 cisco CVR100W Wireless-N VPN Router）

你这款路由是支持ipv6的

官方说明手册

https://www.cisco.com/c/dam/en/us/td/docs/routers/csbr/cvr100w/administration/guide/CVR100W_AG_OL-26942_02.pdf

第54页开始有详细说明的

你可以按照手册操作

另外

你这个路由已经停产了。。。。。。。

如果可以的话 换一个新的吧
