### ISSUE TITLE
firefox升級版本後不能用PAN 只能用SwitchyOmega 

### ISSUE THREAD

**Issue by foho8080** [XX-net/XX-Net#11425]
firefox升級版本後不能用PAN 只能用SwitchyOmega  SwitchyOmega怎樣導入firefox和怎樣設置

**Comment by AnyWAT** [comment]
1、https://addons.mozilla.org/zh-CN/firefox/addon/switchyomega/?src=search 安装 Proxy SwitchyOmega
2、导入XX-Net 目录下的 OmegaOptions.bak
3、about:preferences 常规——网络代理——设置：自动检测此网络的代理设置

**Comment by SeaHOH** [comment]
导入 XX-Net 设置看 wiki，扩展用法自行搜索。

**Comment by bennettmon** [comment]
请问switch插件里gae，smart，x-tunnel这几个选项的区别在哪里啊
