### ISSUE TITLE
kat.cr打不开

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#1143]
GAEProxy状态信息

系统版本

Property	Value
XX-Net Version	2.5.0
Python Version	2.7.9
Sys Platform	AMD64, Windows-7-6.1.7601-SP1
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	553
100th IP handshake(ms)	1567
connected link(帮助)	10,26
scaning ip thread num	200
block stat(帮助)	OK

EBUG] GAE CONNECT GET https://kat.cr/
Oct 02 11:17:57 - [DEBUG] ssl_pool.get:1.255.22.147 handshake:121
Oct 02 11:18:02 - [INFO] scan_ip add ip:202.248.151.59 time:766
Oct 02 11:18:03 - [DEBUG] get ip:1.255.22.213 t:112
Oct 02 11:18:03 - [DEBUG] get ip:1.255.22.147 t:121
Oct 02 11:18:03 - [DEBUG] get ip:1.255.22.238 t:144
Oct 02 11:18:03 - [DEBUG] create_ssl update ip:1.255.22.213 time:198
Oct 02 11:18:03 - [DEBUG] get ip:110.164.9.142 t:210
Oct 02 11:18:03 - [DEBUG] create_ssl update ip:1.255.22.238 time:131
Oct 02 11:18:03 - [DEBUG] get ip:110.164.9.213 t:213
Oct 02 11:18:03 - [DEBUG] get ip:118.98.106.133 t:230
Oct 02 11:18:03 - [DEBUG] create_ssl update ip:1.255.22.147 time:434
Oct 02 11:18:03 - [DEBUG] get ip:110.164.9.173 t:259
Oct 02 11:18:03 - [DEBUG] get ip:1.255.22.166 t:443
Oct 02 11:18:03 - [DEBUG] create_ssl update ip:110.164.9.142 time:278
Oct 02 11:18:03 - [DEBUG] create_ssl update ip:110.164.9.213 time:210
Oct 02 11:18:04 - [DEBUG] create_ssl update ip:110.164.9.173 time:328
Oct 02 11:18:04 - [DEBUG] create_ssl update ip:118.98.106.133 time:553
Oct 02 11:18:05 - [DEBUG] create_ssl update ip:1.255.22.166 time:1299
Oct 02 11:18:10 - [DEBUG] head request BadStatusLine fail:BadStatusLine("''",)
Oct 02 11:18:28 - [WARNING] gae_handler.handler send response fail. t:59 e:error(10053, '') https://kat.cr/
Oct 02 11:18:28 - [WARNING] APPID error:502 url:https://kat.cr/
Oct 02 11:18:28 - [WARNING] gae_handler err:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry') time:59 https://kat.cr/
Oct 02 11:18:28 - [WARNING] socket error:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry')
Oct 02 11:18:29 - [INFO] GAE CONNECT kat.cr:443
Oct 02 11:18:29 - [DEBUG] GAE CONNECT GET https://kat.cr/
Oct 02 11:18:29 - [DEBUG] ssl_pool.get:1.255.22.213 handshake:107
Oct 02 11:18:45 - [DEBUG] get ip:1.255.22.238 t:131
Oct 02 11:18:45 - [DEBUG] create_ssl update ip:1.255.22.238 time:141
Oct 02 11:18:46 - [INFO] scan_ip add ip:188.21.9.139 time:1218
Oct 02 11:18:50 - [DEBUG] get ip:1.255.22.213 t:198
Oct 02 11:18:50 - [DEBUG] get ip:110.164.9.213 t:210
Oct 02 11:18:50 - [DEBUG] create_ssl update ip:1.255.22.213 time:110
Oct 02 11:18:51 - [DEBUG] create_ssl update ip:110.164.9.213 time:210
Oct 02 11:18:56 - [DEBUG] get ip:1.255.22.238 t:141
Oct 02 11:18:56 - [DEBUG] get ip:110.164.9.142 t:278
Oct 02 11:18:56 - [DEBUG] create_ssl update ip:1.255.22.238 time:127
Oct 02 11:18:56 - [DEBUG] get ip:110.164.9.173 t:328
Oct 02 11:18:56 - [WARNING] gae_handler.handler send response fail. t:59 e:error(10053, '') https://kat.cr/
Oct 02 11:18:56 - [WARNING] APPID error:502 url:https://kat.cr/
Oct 02 11:18:56 - [WARNING] gae_handler err:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry') time:59 https://kat.cr/
Oct 02 11:18:56 - [WARNING] socket error:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry')
Oct 02 11:18:56 - [DEBUG] get ip:1.255.22.147 t:434
Oct 02 11:18:56 - [DEBUG] app head fail status:404
Oct 02 11:18:56 - [DEBUG] head request fail:Exception('app check fail',)
Oct 02 11:18:56 - [DEBUG] app head fail status:404
Oct 02 11:18:56 - [DEBUG] head request fail:Exception('app check fail',)
Oct 02 11:18:56 - [DEBUG] get ip:118.98.106.133 t:553
Oct 02 11:18:56 - [DEBUG] create_ssl update ip:110.164.9.142 time:216
Oct 02 11:18:56 - [DEBUG] create_ssl update ip:1.255.22.147 time:135
Oct 02 11:18:56 - [DEBUG] get ip:118.98.106.201 t:663
Oct 02 11:18:57 - [DEBUG] get ip:58.27.27.198 t:750
Oct 02 11:18:57 - [DEBUG] create_ssl update ip:110.164.9.173 time:326
Oct 02 11:18:57 - [DEBUG] get ip:202.248.151.59 t:766
Oct 02 11:18:57 - [DEBUG] create_ssl update ip:118.98.106.133 time:210
Oct 02 11:18:57 - [DEBUG] get ip:103.11.30.28 t:772
Oct 02 11:18:57 - [DEBUG] create_ssl update ip:202.248.151.59 time:190
Oct 02 11:18:57 - [DEBUG] create_ssl update ip:58.27.27.198 time:344
Oct 02 11:18:59 - [DEBUG] head request BadStatusLine fail:BadStatusLine("''",)
Oct 02 11:19:00 - [DEBUG]LOG_EXCEPT: create_ssl update ip:103.11.30.28 time:2811, Except:[Errno 9] Bad file descriptor
Oct 02 11:19:01 - [DEBUG] create_ssl update ip:118.98.106.201 time:4562

**Comment by alresvor** [comment]
kat.cr 并没有被墙，请用PAC模式或者取消代理

**Comment by cdmask** [comment]
是没有被墙，但是打开相当相当慢，上海电信，你懂的

**Comment by simonasd** [comment]
Oct 02 11:18:28 - [WARNING] APPID error:502 url:https://kat.cr/

APPID error:502是不是APPID的流量用完了

**Comment by vstephenzhou** [comment]
大部分站的镜像 xx-net访问无压力 : https://unblocked-pw.github.io/

**Comment by vstephenzhou** [comment]
大部分站的镜像 xx-net访问无压力 : https://unblocked-pw.github.io/

**Comment by vstephenzhou** [comment]
大部分站的镜像 xx-net访问无压力 : https://unblocked-pw.github.io/

**Comment by majiancy** [comment]
我这里kat不需要代理，上海移动

**Comment by cdmask** [comment]
@simonasd 用完了不是提示什么quota之类的吗

**Comment by cdmask** [comment]
@majiancy 移动 联通都好链接 电信不一样

**Comment by cdmask** [comment]
@vstephenzhou  谢谢你提供的镜像

**Comment by simonasd** [comment]
@cdmask 我只是隐约有个印象，以前goagent时代遇到过5xx错误，好像是流量用完了的原因。

**Comment by cdmask** [comment]
@simonasd 看来是老江湖啊。

**Comment by simonasd** [comment]
@cdmask 享受诸位大神的劳动成果多年，如是而已。
