### ISSUE TITLE
怎么IPv6 状态(如何开启)	频繁出现fail？

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#11435]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:74
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:5 h2:0
scan-ip-thread-num: 10
ip-quality: 630
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by shpherd** [comment]
teredor test result is unknown.

**Comment by shpherd** [comment]
看了11427，重新启动并设置策略又能用了，什么时候断再观察

**Comment by AnyWAT** [comment]
想正常，IPv6组策略退回到默认的全部未设置，参考 #11291

**Comment by SeaHOH** [comment]
只和网络状况有关，可尝试重新拨号。
