### ISSUE TITLE
Chrome检查更新时出错：无法启动更新检查（错误代码为 3: 0x80004002 -- system level）。

### ISSUE THREAD

**Issue by JackNewage** [XX-net/XX-Net#11439]
- 是从谷歌官网下载的Chrome（非offline版本）
- 代理的全局模式已经开启
- 普通用户权限运行的Chrome，并非安全模式，并非管理员权限运行
- 已经尝试过卸载重新安装，但是一打开chrome://help依旧是下面这副模样↓
![45250730-28f84800-b36c-11e8-8ca8-89fdc75fd074](https://user-images.githubusercontent.com/42512196/45254903-ba8aa880-b3b2-11e8-8824-69e9bc3b0ffa.png)
- 我的Chrome好像就从没更新成功过。。。。尝试了Google出来的各种办法，之间也换过代理尝试，都不可以。好像遇到（错误代码为 3: 0x80004002 -- system level）的人也不少，可是并没有搜索到什么有用的解决办法。还求猿们指路

**Comment by Eri5Ch** [comment]
不知道从那个版本开始也出现这种错误
不过提示的是error 7 无法验证下载文件...

**Comment by zegzhi** [comment]
Chrome更新并不需要代理，可以连接国内的服务器。
我之前有一段时间也遇到过升级失败，只要关掉Chrome用管理员权限运行就好了。

**Comment by Eri5Ch** [comment]
没有解决这个问题...
![capture](https://user-images.githubusercontent.com/12391921/45663403-cc99e300-bb38-11e8-80e3-93c17af0399e.JPG)

**Comment by AnyWAT** [comment]
试试开启系统代理全局GAE 。。。

**Comment by Kingziqiang** [comment]
请问这个问题是如何解决的？？

**Comment by JackNewage** [comment]
3L和5L的方法试过了，还是不可以😢

**Comment by Eri5Ch** [comment]
我解决了我的chrome不能更新的问题.

**Comment by JackNewage** [comment]
> 我解决了我的chrome不能更新的问题.

你咋解决的

**Comment by Eri5Ch** [comment]
系统google更新服务无故被停止了 想办法重启更新服务就好了 不过这个服务经常被停止了 目前还不知道为何 @JackNewage

**Comment by AnyWAT** [comment]
绿色免费的 Autoruns 或许可帮到你

**Comment by JackNewage** [comment]
之前看到过这个解决办法，也尝试过了重启服务，可还是不可以……@Eri5Ch

**Comment by Johnserf-Seed** [comment]
解决导致 Chrome 无法成功更新的问题
如果在计算机上更新 Chrome 时遇到问题，您可能会看到以下错误消息：

更新失败：管理员已停用更新
更新失败（错误：3 或 11）：检查更新时出错，无法访问更新服务器
更新失败（错误：4 或 10）：检查更新时出错，无法启动更新检查
更新失败（错误：7 或 12）：检查更新时出错，下载失败
此计算机将不会再收到 Chrome 更新，因为 Windows XP 和 Windows Vista 不再受支持
Google Chrome 可能无法进行自动更新。
提示“更新失败”的其他错误
请尝试以下解决方法。

重新下载 Chrome
您的计算机上可能缺少某些文件。要解决相应问题，请按照以下步骤操作：

卸载 Chrome。
确保您的计算机符合系统要求。
重新下载 Chrome，然后尝试重新安装。如果您仍然看到错误消息，请尝试以下方法：
在 Windows 设备上，尝试使用独立的安装程序。
在 Mac 设备上，重新下载 Google 软件更新，然后尝试重新安装。
如果您无法在计算机上完成上述步骤，请与拥有计算机管理员权限的人员联系来完成 Chrome 更新。

检查防病毒软件、防火墙或家长控制设置
检查防病毒软件、防火墙或家长控制软件的设置。

确保这些设置未阻止软件更新连接网络。
确保这些设置未屏蔽 tools.google.com 和 dl.google.com。
重新启动计算机
计算机上的更新操作可能尚未完成。请尝试重新启动计算机，然后重新更新 Chrome。

检查是否存在恶意软件
可能是垃圾软件导致 Chrome 无法正常更新。

**Comment by AllWeKnow** [comment]
同求,我也出现这个问题

**Comment by hfj8210** [comment]
请问解决了吗？我的也是这个问题，之前可以正常更新，也不知道什么时候突然就不行了。
