### ISSUE TITLE
google play和youtube被限制使用移动网络，只能wifi要怎么破，网页不受限制。只是app

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#11432]
重新做了一下系统后，发现google play只能用wifi了。把设置里面找了个底朝天，也没有任何效果。什么移动网络权限全部没有问题。。。。还有国内的app也没有问题，。。。愁死人了

app里面可以打开，可以进入页面。就是不能下载，好像被限制大流量应用了

**Comment by zengsher** [comment]
虽然你编辑了两次，但我还是没看懂，有几个关键性的问题

1、重做了系统，什么系统，安卓？PC？
2、翻墙的方式
3、翻墙软件的日志
4、只有 google play 和 youtube 的 app 上不了，还是其他的都不行，浏览器呢

从你目前的描述粗略判断看是运营商的问题

**Comment by yuyistar** [comment]
@zengsher 手机android系统，双清之后。ssr的翻墙模式，不知道哪里找日志。youtube正常了。现在就是google商店不可以。但是三星商店是可以用移动网络下载的。网页浏览器youtube也正常。

**Comment by zengsher** [comment]
额，ssr 的问题在这里说显然不太合适，不过无所谓了

1、youtube 正常，但是 google 商店不行，应该和运营商无关了，因为要封肯定是一起封
2、ssr 的服务端是你自己的还是买的别人的，如果是自己的，可以看到服务端日志，有助于定位问题
3、可能是 google 服务套件没装好，试试检查升级一下，app 版本和套件版本要匹配才行的
4、也有可能是你设置的代理方式有问题，导致 youtube 和 google 商店流量出口的方式不一样

**Comment by AnyWAT** [comment]
近似替代 google play 的 https://m.apkpure.com 或 https://apkpure.com
