### ISSUE TITLE
teredo隧道一直处于离线状态，这个应该怎么解决？

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#11430]
![image](https://user-images.githubusercontent.com/37856464/45194522-05f36880-b286-11e8-8709-274a3ac575bf.png)

请教大神！

**Comment by AnyWAT** [comment]
先禁用再启用网络或重启路由器

**Comment by milanthree** [comment]
@AnyWAT 已解决，感谢，之前一直用的原生的IPV6，不知道为什么最近突然挂了

**Comment by J-zin** [comment]
@milanthree 
你好 请问你是怎么解决的

**Comment by AnyWAT** [comment]
楼上与楼主的情况不一样呢🤣
