### ISSUE TITLE
"仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by aliasch** [XX-net/XX-Net#11431]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: unknown
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 285
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by J-zin** [comment]
我刚刚也与遇到这个问题了

**Comment by J-zin** [comment]
Sep 07 11:04:36.538 - [DEBUG] report_connect_fail IPv6 continue_fail_count:665

Sep 07 11:04:36.538 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:36.538 - [DEBUG] connect 2a00:1450:4011:4c::15 network fail

Sep 07 11:04:36.618 - [DEBUG] report_connect_fail IPv6 continue_fail_count:666

Sep 07 11:04:36.618 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:36.618 - [DEBUG] connect 2a00:1450:4011:40::20 network fail

Sep 07 11:04:37.042 - [DEBUG] report_connect_fail IPv6 continue_fail_count:667

Sep 07 11:04:37.042 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:37.042 - [DEBUG] connect 2001:1438:1:1::f network fail

Sep 07 11:04:37.114 - [DEBUG] report_connect_fail IPv6 continue_fail_count:668

Sep 07 11:04:37.114 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:37.114 - [DEBUG] connect 2a00:1450:4014:2::b network fail

Sep 07 11:04:37.490 - [DEBUG] report_connect_fail IPv6 continue_fail_count:669

Sep 07 11:04:37.490 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:37.490 - [DEBUG] connect 2001:12e0:804:5::d network fail

Sep 07 11:04:37.599 - [DEBUG] report_connect_fail IPv6 continue_fail_count:670

Sep 07 11:04:37.599 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:37.599 - [DEBUG] connect 2001:b032:8100::13 network fail

Sep 07 11:04:38.471 - [DEBUG] report_connect_fail IPv6 continue_fail_count:671

Sep 07 11:04:38.471 - [DEBUG] report_connect_fail network fail

Sep 07 11:04:38.471 - [DEBUG] connect 2001:67c:f8:fffd::c network fail

Sep 07 11:04:38.561 - [DEBUG] report_connect_fail IPv6 continue_fail_count:672

Sep 07 11:04:38.561 - [DEBUG] report_connect_fail network fail

**Comment by J-zin** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.11.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:400
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 455
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
（开机）启动XX-Net 前即运行以下 bat（批处理内容）可观察变化过程，状态 dormant 即已开始正常化，（随时运行，凭此判断是隧道还是XX-Net 的问题，最佳）启动XX-Net 数秒隧道即可正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by SeaHOH** [comment]
话说你们看不见“**尝试修复**”几个字嘛？

@J-zin 你这是被其他人或者软件关掉了。

@aliasch 你呢？

**Comment by SeaHOH** [comment]
@aliasch 点击测试按钮

**Comment by AnyWAT** [comment]
状态 dormant 即已😜开始😜正常化

**Comment by J-zin** [comment]
@AnyWAT @SeaHOH 
你们好 现在运行结果是这个了  但是还是无法建立连接

![1536291119 1](https://user-images.githubusercontent.com/30493522/45197070-efeba500-b291-11e8-8056-66d64c08f47d.jpg)

**Comment by AnyWAT** [comment]
最佳启动XX-Net 数秒隧道即可正常——不行再开一个XX-Net（挤出前面的）

**Comment by SeaHOH** [comment]
不要玩这个 loop 了，没有用，只是看当前服务器是否连接成功。

直接点击测试按钮，可以测试多个服务器。

**Comment by J-zin** [comment]
@SeaHOH 
这是点击测试teredo后的结果
![1536291676 1](https://user-images.githubusercontent.com/30493522/45197298-00e8e600-b293-11e8-8a9d-fc9e50cf9d24.jpg)

**Comment by AnyWAT** [comment]
可观察变化过程——天下奇谈，如此操作竟然“没有用”🤣

**Comment by SeaHOH** [comment]
才发现你的版本没有升级，请升级。

**Comment by J-zin** [comment]
(⊙﹏⊙)。。。刚刚突然蓝屏  然后重启就好了。。

**Comment by AnyWAT** [comment]
😜机器重启、软件重装乃解决软件问题的最后。。。

**Comment by J-zin** [comment]
unbelievable😜😜😜

**Comment by AnyWAT** [comment]
Win10 也蓝屏？😱

**Comment by J-zin** [comment]
嗯哼 this is twice time

**Comment by htclyh** [comment]
我刚才也遇到这问题，重装了新版本后运行start.bat，就好了~

**Comment by AnyWAT** [comment]
楼主的一定时间后不正常症结：scan-ip-thread-num: 1 打开了某开关的锅 #11291

**Comment by aliasch** [comment]
@AnyWAT 谢谢。现在正常了。如再出问题，我尝试您说的方法。不过老实说，我还不太清楚具体的操作。我到时候仔细看看#11291的说明吧。我记得说，校园网，本身就是原生IPV6的。之前偶尔出问题，有时是通过降版本来处理的。

再次感谢。

**Comment by SeaHOH** [comment]
> 楼主的一定时间后不正常症结：scan-ip-thread-num: 1 打开了某开关的锅 #11291

Bug 会修复，经验会过时，你说的这个 3.12.11 已经修复，不要老是提，没用。

**Comment by AnyWAT** [comment]
也说3.12.11 😂 https://github.com/XX-net/XX-Net/issues/11291#issuecomment-412445618

**Comment by SeaHOH** [comment]
smart_route 调用 gae_proxy API 的 bug，写得很明白了。

**Comment by AnyWAT** [comment]
老白不懂。
刚发完上贴，有效IP归零，几个来回整不好，一度怀疑被楼上黑了😜😭
断网后正常🤣

**Comment by SeaHOH** [comment]
> 电脑断网后正常

什么操作？重新拨号了？

**Comment by AnyWAT** [comment]
（隧道一直批处理显示正常）禁用再启用网络、启动XX-Net
