### ISSUE TITLE
teredo 参数显示disable

### ISSUE THREAD

**Issue by sxd0071** [XX-net/XX-Net#11433]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
> 是否以相关关键词搜索过类似 issues？

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by SeaHOH** [comment]
再不回复就关掉啦

**Comment by AnyWAT** [comment]
关了也能回，别吓人😂

**Comment by SeaHOH** [comment]
关闭标准大概以下几点：
1. 已解决，但是没普遍参考价值。
1. 已解决，但是内容已经过时。
1. 未解决，但是没有提供有价值的信息，且长时间不回复。
1. 无关内容。
