### ISSUE TITLE
哪款路由器能跑xxnet

### ISSUE THREAD

**Issue by Bohan-Song** [XX-net/XX-Net#11442]
我看到教程里面有写在路由上跑，有没有用过的 求推荐款路由器

**Comment by Acytoo** [comment]
netgear r7000

**Comment by SasamiMasakiJurai** [comment]
目前没有路由可以装xxnet

**Comment by Bohan-Song** [comment]
@erdcy  我对路由不怎么懂，大佬能直接给我推荐个型号吗

**Comment by erdcy** [comment]
@Bohan-Song
论坛里好像看到有网友用过梅林，搜搜嘛，看看有没有成功的。
公司有个linksys的1900acs，性能不错，但没试过跑xx，因为ipv6搞不定。
不过说实话，花那么多钱买个路由器跑，还不如租个vps搭一个代理，稳定可靠，还不花电费。

**Comment by asd2003asd** [comment]
树莓派3最理想

**Comment by erdcy** [comment]
旧手机是个好主意，可以马上试试，如果性能不错，放在路由器旁边，就是个翻墙代理了，电视盒子也可以试试。
树莓派平台也许是一个不错的选择，性能不错，有线网络，功耗不高，而且独立运行，可以搜搜有没有网友成功部署过。

**Comment by SasamiMasakiJurai** [comment]
你们先考虑下通道行不

目前路由上无法运行通道

这个已经试验过了

除非你有原生ipv6

否则基本是失败的

**Comment by erdcy** [comment]
目前电信开始部署ipv6了
另外，只要路由器wan口ip可ping，也可以用he.net提供的tunnel获取ipv6，openwrt和梅林应该设置起来很方便。

**Comment by Acytoo** [comment]
不建议使用树莓派，以前用树莓派搭过nas给室友隔壁宿舍分享*电影，结果不是很好。路由器还是要稳定的好，而树莓派还是不够稳定，而且带机量也不如大型路由器，用树莓派还要搭配一个好一点的网卡，不然会很卡。当然如果楼主没有太高的要求，那树莓派真是性价比超高的选择。

**Comment by SasamiMasakiJurai** [comment]
he已经完全污染了

电信ipv6部署看地方的

有些地方ipv6还是有问题的

最后openwrt那个xx-net说明是我写的

里面还是有问题

如果不会编程的话

还是不要瞎尝试

**Comment by erdcy** [comment]
he用了一年多了，tunnel没重新create过，endpoint也没换过，一直正常工作。
另外，6plat不知道还能不能申请隧道，官网显示通过邮件申请，感兴趣可以试试。

**Comment by SasamiMasakiJurai** [comment]
你能用不代表其他人能用

he污染不是一天两天了

最简单的例子

目前各地都在推ipv6

但是魔都一点动静都没

你能想象的到吗

呵呵

**Comment by erdcy** [comment]
你不能用不代表其他人不能用
各地用he的人不是一个两个了
who cares 魔都有没有动静
提供一个思路给坛友
呵呵

**Comment by SasamiMasakiJurai** [comment]
我只知道大部分都不能用

谢谢

he的污染不是一天两天了

ipv6污染和ipv6 dns污染也基本部署完毕了

你还是多多关心下吧

呵呵

**Comment by Bohan-Song** [comment]
@Acytoo 我就一个手机，有时候还有个笔记本，最多两个设备，经常浏览网页还有Gmail什么的，不看视频不下东西，不知道树莓派稳定不，我担心会死机…不知道这玩意性能怎么样

**Comment by AnyWAT** [comment]
手机与笔记本任一个运行XX-Net，可提供代理服务给另外一个或其它新成员😂

**Comment by Acytoo** [comment]
这样的话足够了，性能足够了。但正如楼上所说，同一wifi环境下，不同的设备可以互相提供代理的。

**Comment by erdcy** [comment]
@Bohan-Song
无论选哪个平台，最好能在虚拟机上先试试。每种平台对xx的支持都不太一样，除非你很熟悉Linux，可以自己调试和编译。

**Comment by LeifChi** [comment]
天邑电信猫可以用 我用过  直连原生的

**Comment by erdcy** [comment]
@LeifChi 原生的好用吗？我这里电信原生的没有he的好用，所以把原生的禁用了。

**Comment by LeifChi** [comment]
跟上国内一样快  四川天颐的某款光猫

erdcy <notifications@github.com> 于2019年8月16日周五 上午11:34写道：
