### ISSUE TITLE
使用xx-net百分浏览器日本亚马逊商品添加购物车总是失败，用百度浏览器海外加速就正常能购物？

### ISSUE THREAD

**Issue by mxzxck** [XX-net/XX-Net#11447]
使用xx-net百分浏览器（360浏览器医生一样）日本亚马逊商品添加购物车总是失败，用百度浏览器海外加速就正常能购物。有朋友知道原因吗。

**Comment by SeaHOH** [comment]
涉及资金交易请使用 X-Tunnel，gae_proxy 并不安全，而且很多限制。

**Comment by asmosn** [comment]
這些國產瀏覽器都為工信部搜集翻牆隱私，還敢用？

**Comment by mxzxck** [comment]
谢谢了.
