### ISSUE TITLE
Gmail 你们可以打开吗， google + 可以正常浏览，就是邮件打不开

### ISSUE THREAD

**Issue by abigbone** [XX-net/XX-Net#11443]
# 已更新最新版
gmail  你们能正常打开使用嘛？

> 

`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:20 h2:1
scan-ip-thread-num: 1
ip-quality: 802
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by SeaHOH** [comment]
请贴出访问失败时的日志

**Comment by SeaHOH** [comment]
关闭后仍可回复
