### ISSUE TITLE
捐赠账号

### ISSUE THREAD

**Issue by san1256** [XX-net/XX-Net#11444]
捐赠了账号没有10GB流量怎么回事？
是捐赠给xxnet.service@gmail.com吗？

**Comment by SeaHOH** [comment]
如果不是急用这么多流量，其实每天都有少量流量赠送，足够一般使用。

**Comment by san1256** [comment]
那个流量每天好像只有100MB怕超出了。。。

**Comment by AnyWAT** [comment]
😜留下账号来点？
