### ISSUE TITLE
在梅林固件准备安装xxnet 后来一直显示 Wait 1 second... 求助。。。

### ISSUE THREAD

**Issue by 729940557** [XX-net/XX-Net#11452]
ASUSWRT-Merlin RT-AC86U 384.6-0 Wed Jul 25 16:37:39 UTC 2018
dq@RT-AC86U-5410:/tmp/home/root# sh /tmp/install_xxnet.sh
 Info:  This script was created by ryzhov_al and TeHashX modified by wxing82
 Info:  Thanks @zyxmon & @ryzhov_al for New Generation Entware
 Info:  and @Rmerlin for his awesome firmwares
/tmp/install_xxnet.sh: line 19: XX-Net: not found
 Info:  Script modifies only "entware-ng" folder on the chosen drive,
 Info:  This script will guide you through the Entware-NG
 Info:  no other data will be touched. Existing installation will be
 Info:  replaced with this one. Also some start scripts will be installed,
 Info:  the old ones will be saved on partition where Entware-NG is installed
 Info:  like /tmp/mnt/sda1/jffs_scripts_backup.tgz

This is unsupported platform, sorry.
 Info:  Looking for available partitions...
[1] --> /
[2] --> /dev
[3] --> /proc
[4] --> /var
[5] --> /sys
[6] --> /sys/kernel/debug
[7] --> /bootfs
[8] --> /dev/pts
[9] --> /data
[10] --> /tmp
[11] --> /jffs
[12] --> /tmp/mnt/sda1
 =>  Please enter partition number or 0 to exit
[0-12]: 9
 Info:  /data selected.

 * Warning:  Found previous entware-ng installation, saving...
mv: recursion detected, omitting directory '/data/-bak_2018-05-05_14-00'
 * Warning:  Found previous entware-ng.arm installation, saving...
mv: recursion detected, omitting directory '/data/-bak_2018-05-05_14-00/data'
 Info:  Creating /data/ folder...
mkdir: can't create directory '/data/': File exists
 Info:  Creating /tmp/opt symlink...
 Info:  Creating /jffs scripts backup...
tar: /jffs/scripts/*: No such file or directory
tar: error exit delayed from previous errors
 Info:  Modifying start scripts...
start to install entware-ng
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
/tmp/install_xxnet.sh: line 204: opkg: not found
Router model
RT-AC86U-5410
---------
SWAP FILE
---------
Choose swap file size (Highly Recommended)
1. 256MB
2. 512MB (recommended)
3. 1024MB
4. Skip this step, I already have a swap file / partition
   or I don't want to create one right now
Enter your choice [ 1 - 4 ] 2
 Info:  Creating a 512MB swap file...
 Info:  This could take a while, be patient...
dd: writing '/opt/swap': No space left on device
220746+0 records in
220745+0 records out
Setting up swapspace version 1, size = 226038784 bytes
mkswap: short write
chmod: /opt/swap: No space left on device
swapon: /opt/swap: Invalid argument
Press [Enter] key to continue...
/tmp/install_xxnet.sh: line 267: can't create /opt/bin/services: nonexistent directory
chmod: /opt/bin/services: No such file or directory

Congratulations! If there are no errors above then Entware-NG is successfully initialized.

Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues

>>>>>>>>>>>>>>>>Now we will install XX-Net on your Router<<<<<<<<<<<<<<<<<

 Info:  install pyopenssl...
/tmp/install_xxnet.sh: line 302: opkg: not found
 Info:  Download latest XX-Net...
/opt/tmp/master.zip: No such file or directory
 Info:  Installing the XX-Net...
unzip: can't open /opt/tmp/master.zip[.zip]
 Info:  Installing Bash...
/tmp/install_xxnet.sh: line 308: opkg: not found
 Info:  Try to run the XX-Net for testing...
bash: can't open '/opt/xxnet/start'
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
Wait 1 second...
XX-Net data files have not been created. Please check your settings

**Comment by SasamiMasakiJurai** [comment]
can't open '/opt/xxnet/start'

无法执行命令

需要安装前置插件的

目前路由安装xx-net很麻烦

还是不要折腾了
