### ISSUE TITLE
最新版突然遇到证书没有导入的问题

### ISSUE THREAD

**Issue by Farb** [XX-net/XX-Net#11459]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
已经是最新版

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
查看过

* 是否以相关关键词搜索过类似 issues？
搜索过，有人也遇到过

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:94
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 1
ip-quality: 857
is-idle: 0
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by Farb** [comment]
现在正在按照https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA，重新手动导入证书，
但为什么会突然出现这个问题？

**Comment by Farb** [comment]
手动导入go-agent证书之后，重启浏览器就可以了。昨天升级了系统，是否升级系统导致了证书丢失？？？[笑哭]

**Comment by AnyWAT** [comment]
如果不是丢失，那就仅仅是时间的问题，扫描多了些连接池后才正常而已
scan-ip-thread-num: 1——明显地某开关的软件默认值 #11291

**Comment by SeaHOH** [comment]
可能只是检测错误而已，毕竟这个检测机制受外因影响太多。
一般直接使用，不用看这个证书状态，只有报证书错误时才说明证书丢失或没导入，否则就是正常的。

**Comment by StellaMeow** [comment]
前两天都用得好好的，今天突然提示“请导入浏览器 CA 证书。”导入了还是显示这句话，没法翻墙了。。

**Comment by AnyWAT** [comment]
切换代理扩展到GAE-Proxy 一定时间

**Comment by StellaMeow** [comment]
重启了两次自动好了，我也不知道咋回事_(:зゝ∠)_
