### ISSUE TITLE
在xp系统ip数不断减少至fail，在安卓闲置后不能恢复

### ISSUE THREAD

**Issue by Mybestway** [XX-net/XX-Net#11455]
原生ipv6，只要一连接代理，ip就不断下降直至0，fail，用隧道模式也一样。在同一局域网，安卓6.0下可用（安装xndroid后升级xxnet到最新版），但有时空闲后不能恢复工作。

XX-Net Status:

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1; rv:51.0) Gecko/20100101 Firefox/51.0
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:137 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Sep 12 12:39:35.376 - [DEBUG] report_connect_fail IPv6 continue_fail_count:119

Sep 12 12:39:35.376 - [DEBUG] report_connect_fail:2607:f798:1e:402::f

Sep 12 12:39:35.376 - [DEBUG] connect 2607:f798:1e:402::f fail:error("conn fail, sni:assistant.beach.function.org, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:35.860 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:35.860 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:35.875 - [DEBUG] report_connect_fail IPv6 continue_fail_count:120

Sep 12 12:39:35.875 - [DEBUG] report_connect_fail:2001:578:2a:302::10

Sep 12 12:39:35.875 - [DEBUG] connect 2001:578:2a:302::10 fail:error("conn fail, sni:consist.stop.control.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:36.375 - [DEBUG] report_connect_fail IPv6 continue_fail_count:121

Sep 12 12:39:36.375 - [DEBUG] report_connect_fail:2001:1358:10:1::d

Sep 12 12:39:36.375 - [DEBUG] connect 2001:1358:10:1::d fail:error("conn fail, sni:versioncoursedelivery.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:36.843 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:36.843 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:36.874 - [DEBUG] report_connect_fail IPv6 continue_fail_count:122

Sep 12 12:39:36.874 - [DEBUG] report_connect_fail:2804:a8:d000:100::13

Sep 12 12:39:36.874 - [DEBUG] connect 2804:a8:d000:100::13 fail:error("conn fail, sni:knifesonunion.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:37.374 - [DEBUG] report_connect_fail IPv6 continue_fail_count:123

Sep 12 12:39:37.374 - [DEBUG] report_connect_fail:2001:4c48:13::d

Sep 12 12:39:37.374 - [DEBUG] connect 2001:4c48:13::d fail:error("conn fail, sni:presentationcheekenergy.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:37.858 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:37.858 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:37.873 - [DEBUG] report_connect_fail IPv6 continue_fail_count:124

Sep 12 12:39:37.873 - [DEBUG] report_connect_fail:2a00:1450:4019:4::b

Sep 12 12:39:37.873 - [DEBUG] connect 2a00:1450:4019:4::b fail:error("conn fail, sni:logjobrestaurant.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:38.404 - [DEBUG] report_connect_fail IPv6 continue_fail_count:125

Sep 12 12:39:38.404 - [DEBUG] report_connect_fail:2001:ee0:3203:6::f

Sep 12 12:39:38.404 - [DEBUG] connect 2001:ee0:3203:6::f fail:error("conn fail, sni:power.emergency.ml, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:38.841 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:38.856 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:39.855 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:39.855 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:40.854 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:40.854 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:40.870 - [DEBUG] report_connect_fail IPv6 continue_fail_count:126

Sep 12 12:39:40.870 - [DEBUG] report_connect_fail:2607:f8b0:400a:2::10

Sep 12 12:39:40.870 - [DEBUG] connect 2607:f8b0:400a:2::10 fail:error("conn fail, sni:recognition.district.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:41.369 - [DEBUG] report_connect_fail IPv6 continue_fail_count:127

Sep 12 12:39:41.369 - [DEBUG] report_connect_fail:2600:2:300:1::12

Sep 12 12:39:41.369 - [DEBUG] connect 2600:2:300:1::12 fail:error("conn fail, sni:lady-familiar-evidence.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:41.838 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:41.853 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:41.869 - [DEBUG] report_connect_fail IPv6 continue_fail_count:128

Sep 12 12:39:41.869 - [DEBUG] report_connect_fail:2001:4958:300:527::10

Sep 12 12:39:41.869 - [DEBUG] connect 2001:4958:300:527::10 fail:error("conn fail, sni:recover-shoulder.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:42.368 - [DEBUG] report_connect_fail IPv6 continue_fail_count:129

Sep 12 12:39:42.368 - [DEBUG] report_connect_fail:2607:f8b0:400a:5::16

Sep 12 12:39:42.368 - [DEBUG] connect 2607:f8b0:400a:5::16 fail:error("conn fail, sni:collection.quarter.ml, top*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:42.852 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:42.852 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:42.868 - [DEBUG] report_connect_fail IPv6 continue_fail_count:130

Sep 12 12:39:42.868 - [DEBUG] report_connect_fail:2607:fb90:8f0:2::e

Sep 12 12:39:42.868 - [DEBUG] connect 2607:fb90:8f0:2::e fail:error("conn fail, sni:activitycommitteeholiday.ml, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:43.367 - [DEBUG] report_connect_fail IPv6 continue_fail_count:131

Sep 12 12:39:43.367 - [DEBUG] report_connect_fail:2405:200:1607:743::f

Sep 12 12:39:43.367 - [DEBUG] connect 2405:200:1607:743::f fail:error("conn fail, sni:schemesystemtrainer.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:43.835 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:43.851 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:43.866 - [DEBUG] report_connect_fail IPv6 continue_fail_count:132

Sep 12 12:39:43.866 - [DEBUG] report_connect_fail:2607:f798:14:3e::13

Sep 12 12:39:43.866 - [DEBUG] connect 2607:f798:14:3e::13 fail:error("conn fail, sni:brave-climate.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:44.366 - [DEBUG] report_connect_fail IPv6 continue_fail_count:133

Sep 12 12:39:44.366 - [DEBUG] report_connect_fail:2405:200:1607:2934::12

Sep 12 12:39:44.366 - [DEBUG] connect 2405:200:1607:2934::12 fail:error("conn fail, sni:example-pair-psychology.ml, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:44.834 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:44.850 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:44.865 - [DEBUG] report_connect_fail IPv6 continue_fail_count:134

Sep 12 12:39:44.865 - [DEBUG] report_connect_fail:2001:56a:2:14::c

Sep 12 12:39:44.865 - [DEBUG] connect 2001:56a:2:14::c fail:error("conn fail, sni:somewhere.beyond.shame.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:45.162 - [WARNING] task POST None /_gh/ timeout

Sep 12 12:39:45.162 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Sep 12 12:39:45.162 - [WARNING] gae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.x

Sep 12 12:39:45.162 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.xgae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.xgae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.x"

Sep 12 12:39:45.162 - [WARNING] GAE GET https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.x request fail:"600:gae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.xgae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.xgae_exception:'600:fetch gae fail' https://api.github.com/repos/XX-net/XX-Net/issues?page=1&labels=%E5%8F%91%E5%B8%83,3.12.x"

Sep 12 12:39:45.162 - [WARNING] send response fail

Sep 12 12:39:45.178 - [WARNING] send response fail

Sep 12 12:39:45.396 - [DEBUG] report_connect_fail IPv6 continue_fail_count:135

Sep 12 12:39:45.396 - [DEBUG] report_connect_fail:2405:200:1605:2934::d

Sep 12 12:39:45.396 - [DEBUG] connect 2405:200:1605:2934::d fail:error("conn fail, sni:penalty-roof-junior.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:45.833 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:45.833 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:46.832 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:46.848 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:46.848 - [DEBUG] report_connect_fail IPv6 continue_fail_count:136

Sep 12 12:39:47.831 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:47.846 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:47.862 - [DEBUG] report_connect_fail IPv6 continue_fail_count:137

Sep 12 12:39:47.862 - [DEBUG] report_connect_fail:2404:6800:4010:d::c

Sep 12 12:39:47.862 - [DEBUG] connect 2404:6800:4010:d::c fail:error("conn fail, sni:aspect-task-welcome.org, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:48.361 - [DEBUG] report_connect_fail IPv6 continue_fail_count:138

Sep 12 12:39:48.361 - [DEBUG] report_connect_fail:2a02:c7a:8000:f102::e

Sep 12 12:39:48.361 - [DEBUG] connect 2a02:c7a:8000:f102::e fail:error("conn fail, sni:shootdifficultydelivery.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:48.845 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:48.845 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:48.861 - [DEBUG] report_connect_fail IPv6 continue_fail_count:139

Sep 12 12:39:48.861 - [DEBUG] report_connect_fail:2607:f8b0:400a:3::10

Sep 12 12:39:48.861 - [DEBUG] connect 2607:f8b0:400a:3::10 fail:error("conn fail, sni:particular.father.pressure.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:49.360 - [DEBUG] report_connect_fail IPv6 continue_fail_count:140

Sep 12 12:39:49.360 - [DEBUG] report_connect_fail:2605:e300:800:2::f

Sep 12 12:39:49.360 - [DEBUG] connect 2605:e300:800:2::f fail:error("conn fail, sni:reflection-junior.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:49.844 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:49.844 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:49.860 - [DEBUG] report_connect_fail IPv6 continue_fail_count:141

Sep 12 12:39:49.860 - [DEBUG] report_connect_fail:2806:1020:cfff:6::e

Sep 12 12:39:49.860 - [DEBUG] connect 2806:1020:cfff:6::e fail:error("conn fail, sni:relationship-skill.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:50.359 - [DEBUG] report_connect_fail IPv6 continue_fail_count:142

Sep 12 12:39:50.359 - [DEBUG] report_connect_fail:2405:200:161f:1725::c

Sep 12 12:39:50.359 - [DEBUG] connect 2405:200:161f:1725::c fail:error("conn fail, sni:broadtongue.com, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:50.827 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:50.827 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:50.859 - [DEBUG] report_connect_fail IPv6 continue_fail_count:143

Sep 12 12:39:50.859 - [DEBUG] report_connect_fail:2607:f798:14:3e::e

Sep 12 12:39:50.859 - [DEBUG] connect 2607:f798:14:3e::e fail:error("conn fail, sni:pauseinflation.org, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:51.374 - [DEBUG] report_connect_fail IPv6 continue_fail_count:144

Sep 12 12:39:51.374 - [DEBUG] report_connect_fail:2001:16a0:102:10d::12

Sep 12 12:39:51.374 - [DEBUG] connect 2001:16a0:102:10d::12 fail:error("conn fail, sni:library-crash.net, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:51.826 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:51.826 - [DEBUG] Browse localhost by proxy

Sep 12 12:39:51.858 - [DEBUG] report_connect_fail IPv6 continue_fail_count:145

Sep 12 12:39:51.858 - [DEBUG] report_connect_fail:2607:fa48:70:9::e

Sep 12 12:39:51.858 - [DEBUG] connect 2607:fa48:70:9::e fail:error("conn fail, sni:writing-particular-recipe.org, top:*.appspot.com e:timeout('timed out',)",)

Sep 12 12:39:52.388 - [DEBUG] report_connect_fail IPv6 continue_fail_count:146

Sep 12 12:39:52.388 - [DEBUG] report_connect_fail:2a00:f46:0:1201::c

Sep 12 12:39:52.388 - [DEBUG] connect 2a00:f46:0:1201::c fail:error("conn fail, sni:drafttax.ml, top:*.appspot.com e:timeout('timed out',)",)

**Comment by SeaHOH** [comment]
你的代理设置没有排除本机地址。
至于连接不上 IP，属于网络问题，能报下地区和 ISP 嘛。

**Comment by SeaHOH** [comment]
还有访问 http://test-ipv6.com/ 看看结果

**Comment by SeaHOH** [comment]
看漏了 Xndroid 可用，那么就是防火墙设置错误。

**Comment by AnyWAT** [comment]
安卓6.0下可用，但有时空闲后不能恢复工作——试试：关闭自动调整扫描线程开关（2处），软件首页及XX-Net 的GAEPROXY各有一个功能相同的开关。并适当增大最大扫描线程数（以能自动维持较小的IP延时及有效IP数能达到总IP数时为最小值）

**Comment by SeaHOH** [comment]
>我这颗祖传大力丸，有病治病没病强身。。。

@AnyWAT 
小兄弟，能不能不要以不变应万变，又不是拍武侠玄幻。
注意版本，你说的那个 bug 只存在于之前几个版本的 smart_router 调用 gae_proxy 中。

**Comment by AnyWAT** [comment]
大海，实战经验之谈🤣

**Comment by SeaHOH** [comment]
我只看到了千篇一律的这种回复，起码 80% 以上，难道问题都一样？

**Comment by Mybestway** [comment]
@SeaHOH 没开防火墙，地区是华南电信

**Comment by SeaHOH** [comment]
网站测试呢？

**Comment by Mybestway** [comment]
test-ipv6.com测试结果：

你的公网 IPv4 地址是 113.69.×.×

你的公网 IPv6 地址是 240e:fe:82d9:c500:×:×:×:×

你的运营商（ISP）是 CHINANET-BACKBONE No.31,Jin-rong Street

你已接入 IPv6，因此我们增加了一个标签页，显示你能否访问其他 IPv6 网站。[更多信息]

你已经有 IPv6 地址了，但你的浏览器不太愿意用，这一点比较令人担心。 [更多信息]

本站现已支持 HTTPS。 [更多信息]

你的 DNS 服务器（可能由运营商提供）已经接入 IPv6 互联网了。


IPv4 域名连接测试 	  	
成功 (0.407s) 使用 ipv4
IPv6 域名连接测试 	  	
成功 (0.590s) 使用 ipv6
双栈域名连接测试 	  	
成功 (0.398s) 使用 ipv4
双栈域名大数据包传输测试 	  	
成功 (0.373s) 使用 ipv4
无域名 IPv4 连接测试 	  	
成功 (0.393s) 使用 ipv4
无域名 IPv6 连接测试 	  	
成功 (0.302s) 使用 ipv6
IPv6 大数据包传输测试 	  	
成功 (0.341s) 使用 ipv6
测试运营商 DNS 是否接入 IPv6 	  	
成功 (0.857s) 使用 ipv6
查询 IPv4 运营商 	  	
成功 (0.210s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 	  	
成功 (0.289s) 使用 ipv6 ASN 4134

**Comment by SeaHOH** [comment]
看起来挺正常，测试以下 IP 能否 ping 通：

2001:41d0:8:e8ad::1
2001:260:401:372::5f
2a02:188:3e00::32
2804:10:4068::202:82

**Comment by Mybestway** [comment]
@AnyWAT 多谢指教，刚才用你的方法，安卓手机里的xxnet空闲后能恢复工作了。再继续观察看以后是否还是能正常运行。
@SeaHOH 大海兄息怒，其实AnyWAT是热心人，这里不少菜鸟问题还是靠他帮忙解决的。

**Comment by AnyWAT** [comment]
root 后的安卓，可适当增大总IP数

**Comment by SeaHOH** [comment]
不要急着打脸，用段时间再说。

**Comment by Mybestway** [comment]
都能ping通。
其实xxnet以前都能正常运行，后来一段时间没用，再用就不行了，开始以为gfw干扰，但手机里又能用。
以前一直用XX-Net-3.7.12很正常，之后的XX-Net-3.7.15到XX-Net-3.11.7之前的版本都有这个问题，就是ip数不断下降至0，fail。我就跳过了这几个版本。XX-Net-3.11.7之后的版本又恢复正常了，一直到XX-Net3.12.11都正常。现在就是所有版本都会ip下降都0了

**Comment by AnyWAT** [comment]
现在就是所有版本都会ip下降都0了——网络环境变化？

**Comment by Mybestway** [comment]
我有几个xp系统都是这样，ip数下降到0。系统有新有旧。

**Comment by SeaHOH** [comment]
手机用的原生还是隧道？
如果是隧道，你先把原生禁用一下，就是取消网卡适配器中的 IPv6 协议。
可能优先级设置有不准确。

**Comment by Mybestway** [comment]
但手机能用啊。难道手机发送的和电脑发送的字节不一样

**Comment by SeaHOH** [comment]
少写了 PC，禁用 PC 原生。

**Comment by Mybestway** [comment]
手机支持原生，但xndroid似乎在用隧道。
禁用原生，是指手机吗？

**Comment by SeaHOH** [comment]
> 你先把 PC 的原生禁用一下，就是取消网卡适配器中的 IPv6 协议。
> 可能优先级设置有不准确。

**Comment by Mybestway** [comment]
电脑禁用了ipv6协议，开了隧道，但ip数还是下降
E:\myfile\桌面>netsh inter ipv6 show teredo state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          :default
客户端口                : default
状态                    : qualified
类型                    : teredo client
网络                    : unmanaged
NAT                     : restricted

那个总ip数是刚下载软件后第一次运行时候扫到的。现在有效ip数是2，但IPv6 状态还是fail了。有时是有效ip数还没到0就fail了

**Comment by SeaHOH** [comment]
打印下`route print`结果

**Comment by Mybestway** [comment]
E:\myfile\「开始」菜单>route print
===========================================================================
Interface List
0x1 ........................... MS TCP Loopback interface
0x2 ...00 50 56 c0 00 08 ...... VMware Virtual Ethernet Adapter for VMnet8
0x3 ...00 50 56 c0 00 01 ...... VMware Virtual Ethernet Adapter for VMnet1
0x4 ...00 21 5d 23 ×× ×× ...... Intel(R) WiFi Link 5100 AGN - 数据包计划程序微型
端口
===========================================================================
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    192.168.250.1  192.168.250.114      10
        127.0.0.0        255.0.0.0        127.0.0.1       127.0.0.1       1
    192.168.135.0    255.255.255.0    192.168.135.1   192.168.135.1       20
    192.168.135.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.135.255  255.255.255.255    192.168.135.1   192.168.135.1       20
    192.168.152.0    255.255.255.0    192.168.152.1   192.168.152.1       20
    192.168.152.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.152.255  255.255.255.255    192.168.152.1   192.168.152.1       20
    192.168.250.0    255.255.255.0  192.168.250.114  192.168.250.114      10
  192.168.250.114  255.255.255.255        127.0.0.1       127.0.0.1       10
  192.168.250.255  255.255.255.255  192.168.250.114  192.168.250.114      10
        224.0.0.0        240.0.0.0    192.168.135.1   192.168.135.1       20
        224.0.0.0        240.0.0.0    192.168.152.1   192.168.152.1       20
        224.0.0.0        240.0.0.0  192.168.250.114  192.168.250.114      10
  255.255.255.255  255.255.255.255    192.168.135.1   192.168.135.1       1
  255.255.255.255  255.255.255.255    192.168.152.1   192.168.152.1       1
  255.255.255.255  255.255.255.255  192.168.250.114  192.168.250.114      1
Default Gateway:     192.168.250.1
===========================================================================
Persistent Routes:
  None

E:\myfile\「开始」菜单>

**Comment by Mybestway** [comment]
E:\myfile\「开始」菜单>route print
===========================================================================
Interface List
0x1 ........................... MS TCP Loopback interface
0x2 ...00 50 56 c0 00 08 ...... VMware Virtual Ethernet Adapter for VMnet8
0x3 ...00 50 56 c0 00 01 ...... VMware Virtual Ethernet Adapter for VMnet1
0x4 ...00 21 5d 23 8d 4a ...... Intel(R) WiFi Link 5100 AGN - 数据包计划程序微型
端口
===========================================================================
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    192.168.250.1  192.168.250.114      10
        127.0.0.0        255.0.0.0        127.0.0.1       127.0.0.1       1
    192.168.135.0    255.255.255.0    192.168.135.1   192.168.135.1       20
    192.168.135.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.135.255  255.255.255.255    192.168.135.1   192.168.135.1       20
    192.168.152.0    255.255.255.0    192.168.152.1   192.168.152.1       20
    192.168.152.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.152.255  255.255.255.255    192.168.152.1   192.168.152.1       20
    192.168.250.0    255.255.255.0  192.168.250.114  192.168.250.114      10
  192.168.250.114  255.255.255.255        127.0.0.1       127.0.0.1       10
  192.168.250.255  255.255.255.255  192.168.250.114  192.168.250.114      10
        224.0.0.0        240.0.0.0    192.168.135.1   192.168.135.1       20
        224.0.0.0        240.0.0.0    192.168.152.1   192.168.152.1       20
        224.0.0.0        240.0.0.0  192.168.250.114  192.168.250.114      10
  255.255.255.255  255.255.255.255    192.168.135.1   192.168.135.1       1
  255.255.255.255  255.255.255.255    192.168.152.1   192.168.152.1       1
  255.255.255.255  255.255.255.255  192.168.250.114  192.168.250.114      1
Default Gateway:     192.168.250.1
===========================================================================
Persistent Routes:
  None

E:\myfile\「开始」菜单>

**Comment by Mybestway** [comment]
E:\myfile\「开始」菜单>route print

Interface List
0x1 ........................... MS TCP Loopback interface
0x2 ...00 50 56 c0 00 08 ...... VMware Virtual Ethernet Adapter for VMnet8
0x3 ...00 50 56 c0 00 01 ...... VMware Virtual Ethernet Adapter for VMnet1
0x4 ...00 21 5d 23 8d 4a ...... Intel(R) WiFi Link 5100 AGN - 数据包计划程序微型
端口

Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    192.168.250.1  192.168.250.114      10
        127.0.0.0        255.0.0.0        127.0.0.1       127.0.0.1       1
    192.168.135.0    255.255.255.0    192.168.135.1   192.168.135.1       20
    192.168.135.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.135.255  255.255.255.255    192.168.135.1   192.168.135.1       20
    192.168.152.0    255.255.255.0    192.168.152.1   192.168.152.1       20
    192.168.152.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.152.255  255.255.255.255    192.168.152.1   192.168.152.1       20
    192.168.250.0    255.255.255.0  192.168.250.114  192.168.250.114      10
  192.168.250.114  255.255.255.255        127.0.0.1       127.0.0.1       10
  192.168.250.255  255.255.255.255  192.168.250.114  192.168.250.114      10
        224.0.0.0        240.0.0.0    192.168.135.1   192.168.135.1       20
        224.0.0.0        240.0.0.0    192.168.152.1   192.168.152.1       20
        224.0.0.0        240.0.0.0  192.168.250.114  192.168.250.114      10
  255.255.255.255  255.255.255.255    192.168.135.1   192.168.135.1       1
  255.255.255.255  255.255.255.255    192.168.152.1   192.168.152.1       1
  255.255.255.255  255.255.255.255  192.168.250.114  192.168.250.114      1
Default Gateway:     192.168.250.1

Persistent Routes:
  None

**Comment by Mybestway** [comment]
Interface List
0x1 ........................... MS TCP Loopback interface
0x2 ...00 50 56 c0 00 08 ...... VMware Virtual Ethernet Adapter for VMnet8
0x3 ...00 50 56 c0 00 01 ...... VMware Virtual Ethernet Adapter for VMnet1
0x4 ...00 21 5d 23 ** ** ...... Intel(R) WiFi Link 5100 AGN - 数据包计划程序微型
端口

Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0    192.168.250.1  192.168.250.114      10
        127.0.0.0        255.0.0.0        127.0.0.1       127.0.0.1       1
    192.168.135.0    255.255.255.0    192.168.135.1   192.168.135.1       20
    192.168.135.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.135.255  255.255.255.255    192.168.135.1   192.168.135.1       20
    192.168.152.0    255.255.255.0    192.168.152.1   192.168.152.1       20
    192.168.152.1  255.255.255.255        127.0.0.1       127.0.0.1       20
  192.168.152.255  255.255.255.255    192.168.152.1   192.168.152.1       20
    192.168.250.0    255.255.255.0  192.168.250.114  192.168.250.114      10
  192.168.250.114  255.255.255.255        127.0.0.1       127.0.0.1       10
  192.168.250.255  255.255.255.255  192.168.250.114  192.168.250.114      10
        224.0.0.0        240.0.0.0    192.168.135.1   192.168.135.1       20
        224.0.0.0        240.0.0.0    192.168.152.1   192.168.152.1       20
        224.0.0.0        240.0.0.0  192.168.250.114  192.168.250.114      10
  255.255.255.255  255.255.255.255    192.168.135.1   192.168.135.1       1
  255.255.255.255  255.255.255.255    192.168.152.1   192.168.152.1       1
  255.255.255.255  255.255.255.255  192.168.250.114  192.168.250.114      1
Default Gateway:     192.168.250.1

Persistent Routes:
  None

**Comment by SeaHOH** [comment]
忘了你这是 XP，打印`netsh interface ipv6 show route`。

**Comment by AnyWAT** [comment]
电脑禁用了ipv6协议

**Comment by Mybestway** [comment]
E:\myfile\「开始」菜单>netsh interface ipv6 show route
正在查询活动状态...

发行     类型      Met   前缀                     索引  网关/接口名

no       Autoconf    10  ::/0                        7  Teredo Tunneling Pseudo-
Interface
no       Autoconf    10  2001::/32                   7  Teredo Tunneling Pseudo-
Interface

**Comment by SeaHOH** [comment]
其实你可以安个双系统，试试 win7。

**Comment by Mybestway** [comment]
谢谢大海兄答疑。
防火墙服务开了的。老机器，c盘小，装双系统又要折腾不少地方。其实xp做了点手脚还在更新。
我会试试你建议的方法，看隧道能不能获得地址。
还有，那原生的呢？

**Comment by AnyWAT** [comment]
😂隧道可参考：#10184 #11291

**Comment by SeaHOH** [comment]
> 还可以试试有线连接。

无线可能有影响，之前好像有过类似案例，具体的忘了。

**Comment by Mybestway** [comment]
多谢AnyWAT提示
