### ISSUE TITLE
出现Wrong password('') GoAgent proxy.ini password is wrong!

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#11456]
登陆油管推特google总出现Wrong password('')
GoAgent proxy.ini password is wrong!

3.11.2之后已经默认删除了自设密码。见https://console.cloud.google.com/debug

**Comment by AnyWAT** [comment]
貌似整个XX-Net 下都没有 proxy.ini
从3.10.5开始不再支持 ini ，而是 config.json

**Comment by shpherd** [comment]
XX-Net 3.12.10，一切正常，你可以访问真正的互联网了。
版本如上，这就蹊跷了。之前还是能科学上网的

**Comment by AnyWAT** [comment]
#11183 没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）

**Comment by SeaHOH** [comment]
密码仍然有效，修改 config.json，加入`GAE_PASSWORD`即可。

**Comment by erdcy** [comment]
@SeaHOH 什么密码？不是认证功能吧，记得以前说过xx-net没有保留go_agent的用户认证功能。

**Comment by SeaHOH** [comment]
以前主要是配合 rc4 作混淆，现在就只是一个简单的字符串比较，一般没啥用，sever 目录有说明。

**Comment by SunYongshuai** [comment]
> 貌似整个XX-Net 下都没有 proxy.ini（貌似Mini 版才有或你自建的？推荐自建不是 manual.ini？）
> GoAgent proxy.ini password is wrong!——莫非你的AppID还是GoAgent 版？
> 从3.10.5开始不再支持 ini ，而是 config.json（检查此文件内容？）

多个APPID密码不同怎么设置呢？
  2   "GAE_APPIDS": [
  3     "appid1",
  4     "appid2",
  5     "appid3",
  6     "appid4"
  7   ], 
  8   "GAE_PASSWORD": [                                                                                                                 
  9     "pw1", 
 10     "pw2",
 11     "pw3",
 12     "pw4"
 13   ]

这样定义吗？
非常感谢！

**Comment by SeaHOH** [comment]
`GAE_PASSWORD` 只能是字符串，所以无法设置不同的值。

**Comment by SunYongshuai** [comment]
I Just Try it! 所以，如果我有不同的APPID，密码不同，我应该怎么设置？

**Comment by SeaHOH** [comment]
更新服务端，使其保持一致。
