### ISSUE TITLE
重启电脑后需要重新扫描IP

### ISSUE THREAD

**Issue by subtank** [XX-net/XX-Net#11451]
隧道ipv6地址下xxnet需要重新扫描ip地址（删除goodip.txt文件）才能正常使用

**Comment by AnyWAT** [comment]
😂ipv6地址下=原生 ipv6下？

**Comment by subtank** [comment]
隧道。。。

**Comment by AnyWAT** [comment]
试试关闭某开关 #11291

**Comment by subtank** [comment]
关了的。依旧有问题。

**Comment by SeaHOH** [comment]
正常现象，建议开启自动调整扫描线程，以更快的触发 IP 更新，这样不删除旧 IP 也能在启动几分钟后正常使用。

**Comment by AnyWAT** [comment]
开启自动调整扫描线程，以更快的触发 IP 更新：个人理解，第一个逗号前后这二者是矛盾的😭

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Auto-adjust-scan-ip-thread-num
![default](https://user-images.githubusercontent.com/37962734/45337268-b8466b00-b5b9-11e8-802e-21d33b8953b7.png)

**Comment by AnyWAT** [comment]
开启自动调整扫描线程数后，貌似有效IP难以达到总IP数，与下图。。。
![default](https://user-images.githubusercontent.com/37962734/45337782-53d8db00-b5bc-11e8-8a20-710814d9a1ce.png)

**Comment by SeaHOH** [comment]
好吧，wiki 确实没有修改跟进，但是每次发布你都不看更新了什么吗？
发布个任务给你：就是修改这个 wiki 条目，最近的版本更新说明里面有，虽然没有很明显。而且我也给你讲过好几次了，关键字 recheck。

**Comment by AnyWAT** [comment]
今天又打开某开关测试了：
貌似软件在有效IP达到总IP数的约70%就开始调整扫描线程数，与以往的到100%不同：到100%后调整，才能做到与上贴黄色涂画文字描述的一致，否则：有效IP一直在减小（520到不足400），延时时常跑大，甚至到9999😜

**Comment by SeaHOH** [comment]
贴图，空口无凭，运行 10分钟，半小时，1小时。

**Comment by AnyWAT** [comment]
当时准备截图了，以为（说说就会信）多余，下回见

**Comment by SeaHOH** [comment]
我调试的结果。
在网络状态好时，延时基本和一直大线程狂扫差不多。
稍差好时，延时也就大上 100-300。
网络更糟时，延时也有 1000左右。
最差的就不说了，这个没救。

**Comment by AnyWAT** [comment]
请关闭你的防DNS污染再测试（一般人没有）😜

**Comment by SeaHOH** [comment]
你完全可以直接用 IP

**Comment by AnyWAT** [comment]
软件又没有告知大家直接用服务器 IP，故你的测试是不符合（一般人）软件使用条件的，不通用😂

**Comment by SeaHOH** [comment]
测试目的 IP 是合适的，一般使用不建议，因为说不准微软就换 IP 了。

**Comment by AnyWAT** [comment]
貌似逻辑不对：共性测试，应基于一般使用条件。故再次、最后一次请关闭你的防DNS污染软件再测试（一般人没有）😜

**Comment by SeaHOH** [comment]
这和测试模式完全无关，不知道你纠结什么，隧道断开用什么都没用。

**Comment by AnyWAT** [comment]
因你纠结：我这颗祖传大力丸，有病治病没病强身。。。并基于不同一般使用条件的你的测试结果，而否认我的基于每天运行不少于12小时的实战结论，如“臭大街法则”。。。😂

**Comment by SeaHOH** [comment]
你真是意志坚定
