### ISSUE TITLE
请问自己添加的appid越多，会速度越快么

### ISSUE THREAD

**Issue by lbgzmhl** [XX-net/XX-Net#11460]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
公共 ID 那么多，你觉得呢？
这不是 bbs，一般常识请看 wiki。
