### ISSUE TITLE
xndroid无法登录x tunnel，显示代码为status：601

### ISSUE THREAD

**Issue by paladinstorm** [XX-net/XX-Net#11464]
如题，版本最新。 
日志节选：
Sep 14 17:56:46.418 - [DEBUG] x-tunnel no account

Sep 14 17:56:46.928 - [DEBUG] x-tunnel no account

Sep 14 17:56:47.427 - [DEBUG] x-tunnel no account

Sep 14 17:56:47.930 - [DEBUG] session not running, try to connect

Sep 14 17:56:47.930 - [WARNING] create conn fail

Sep 14 17:56:48.429 - [DEBUG] session not running, try to connect

Sep 14 17:56:48.430 - [WARNING] create conn fail

**Comment by paladinstorm** [comment]
偶尔错误代码也是602

**Comment by AnyWAT** [comment]
手动检查IP或稍侯再登录。。。
😜想爽：https://github.com/XndroidDev/Xndroid/issues/169#issuecomment-420474279

**Comment by Chriszhung** [comment]
602登不上xtunnel

**Comment by AnyWAT** [comment]
貌似X-Tunnel 服务器已恢复😂

**Comment by Chriszhung** [comment]
半个月了，xtunnel一直不正常，什么时候能恢复？也不更新了吗？这个花得不值

**Comment by AnyWAT** [comment]
半个月来 xtunnel 偶尔不正常，此刻正常

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/11553#issuecomment-429343144

**Comment by SeaHOH** [comment]
没啥想法，我也没用过。
