### ISSUE TITLE
xndroid如何开启x tunnel？

### ISSUE THREAD

**Issue by paladinstorm** [XX-net/XX-Net#11463]
并未找到x tunnel的登录界面，在xx net首页的“使用x tunnel”超链接导向的是x tunnel的wiki页面。所以有大佬可以指点一下如何在xndroid上登录x tunnel吗？谢谢。

**Comment by AnyWAT** [comment]
xndroid 软件比XX-Net 多了个首页而已，只是屏幕大小的缘故，XX-net 的控制页没Win 版的清爽，但内容基本一致：屏幕左上角菜单——XX-Net 。。。

**Comment by paladinstorm** [comment]
@

> xndroid 软件比XX-Net 多了个首页而已，只是屏幕大小的缘故，XX-net 的控制页没Win 版的清爽（点击了某项可能要死劲向下划），但二者内容貌似基本一致：屏幕左上角三横菜单——XX-Net 。。。

谢谢
