### ISSUE TITLE
google要搞阉割版，那gae是不是就用不了了啊？

### ISSUE THREAD

**Issue by ShadowEmbrace** [XX-net/XX-Net#11467]
我要不要现在搞个备份方案啊~
另外这些年翻的数据会不会一起被转手。。。

**Comment by zengsher** [comment]
1、gae 并不是专门用来翻墙的，也不是专门给大陆提供的，只是谷歌的一个开放服务，除非谷歌把这个项目关了，不然还是能用
2、gae 从来都不是匿名的，你做了什么上面清清楚楚，只要不做违法的事，人也懒得查你

**Comment by ShadowEmbrace** [comment]
1、google也有很多不是专门给大陆用的功能在大陆是用不了的，一旦双方开始合作，封闭大陆访问就很可能成为谈判条件之一；
2、国内有些被请喝茶的其实明着说也没违法啊。

**Comment by Mexico-zyy** [comment]
现在有稳定版本吗？

发自我的 iPhone
