### ISSUE TITLE
最新的3.12.11上Xvideos无法播放视频

### ISSUE THREAD

**Issue by reniastyc** [XX-net/XX-Net#11466]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
最新版本

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
已经查看过

* 是否以相关关键词搜索过类似 issues？
没有找到易懂的解决方法

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
在该网站上视频只有封面图而无法播放。在七月左右尚能正常浏览

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11419#issuecomment-418610508
