### ISSUE TITLE
请问一台电脑开启xxnet之后，怎么让其他设备以这台做代理也能出去

### ISSUE THREAD

**Issue by lbgzmhl** [XX-net/XX-Net#11461]
看了[允许其它设备使用代理](https://github.com/XX-net/XX-Net/wiki/%E5%85%81%E8%AE%B8%E5%85%B6%E5%AE%83%E8%AE%BE%E5%A4%87%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%90%86)
没看懂。。。。
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
1、允许其它设备使用代理，即 http://127.0.0.1:8085/?module=launcher&menu=config 打开：允许远程访问控制页
2、https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1 采用GAEPROXY需要先导入证书

**Comment by Beyood** [comment]
![76t nc nqfvw7r6qxes77a0](https://user-images.githubusercontent.com/43511443/45925115-12dcb100-bf42-11e8-96c0-ffe64e0beff5.jpg)

**Comment by Beyood** [comment]
1.XXNET主机设置为全局PAC或智能路由
2.XXNET打开允许远程访问控制页
3.其它上网设备网络链接设置自动代理
4.其它上网设备网络链接自动代理地址填入 http://XXNET主机IP:8086/proxy,pac

**Comment by tedchina** [comment]
谢谢分享！
请问怎么在“其它上网设备”上面设置证书呢？否则不间断的证书提醒（Chrome甚至拒绝继续访问）也挺麻烦的。

**Comment by tedchina** [comment]
不好意思，看帖不仔细。
不过不知为何，昨晚试成功的今早反而一直失败，有机会再试吧。
