### ISSUE TITLE
能够登录其他网页，就是Google的无法登陆

### ISSUE THREAD

**Issue by xfLiSZ** [XX-net/XX-Net#11471]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by xfLiSZ** [comment]
Sep 17 15:26:37.775 - [DEBUG] create_ssl update ip:2001:b032:5d01::d time:1439 h2:0 sni:contribution-appointment-beach.com, host:ghq214301.appspot.com

Sep 17 15:26:38.326 - [DEBUG] create_ssl update ip:2001:b000:1e0:c100::13 time:1486 h2:0 sni:teacher.bar.ml, host:xxnet-f0rrest-cn10.appspot.com

Sep 17 15:26:38.814 - [DEBUG] create_ssl update ip:2001:b000:188:c100::f time:1473 h2:0 sni:witnessbaseballactor.net, host:flash-moonlight-123504.appspot.com

Sep 17 15:26:55.555 - [INFO] scan_ip add ip:2806:1020:cfff:6::11 time:307 h2:0

Sep 17 15:26:55.556 - [INFO] remove_slowest_ip:2001:1970:1:2054::11 handshake_time:867, fails:0

Sep 17 15:27:11.071 - [INFO] scan_ip add ip:2001:b032:8101::d time:534 h2:0

Sep 17 15:27:11.072 - [INFO] remove_slowest_ip:2001:4958:300:500::12 handshake_time:862, fails:0

Sep 17 15:27:45.165 - [DEBUG] report_connect_fail IPv4 continue_fail_count:11

Sep 17 15:27:45.322 - [DEBUG] network IPv4 is ok, cost:157 ms

Sep 17 15:27:47.162 - [DEBUG] report_connect_fail:2806:1020:cfff:6::11

Sep 17 15:27:47.987 - [INFO] scan_ip add ip:2001:b032:7101:1::e time:538 h2:0

Sep 17 15:27:47.988 - [INFO] remove_slowest_ip:2a00:23a0:1e5:3::10 handshake_time:357, fails:2

**Comment by AnyWAT** [comment]
gws-ip-num: total:100 ipv4:0 ipv6:83 有效 IP没达到总 IP数
scan-ip-thread-num: 1 貌似打开了某开关
is-idle: 1 已空闲
试试：关闭“自动调整扫描线程数”，检查 IP，同时刷新或新开需代理的网页

**Comment by SeaHOH** [comment]
是否手动修改过 config.json ？

**Comment by xfLiSZ** [comment]
没有修改过config.json

**Comment by SeaHOH** [comment]
换个浏览器试试

**Comment by AnyWAT** [comment]
proxy_state: Fail
ca_state: Fail 前面看漏了此2项目，此时宜（关闭浏览器、）退出XX-Net 再重开

**Comment by AnyWAT** [comment]
一般常用 GAE 自动切换
