### ISSUE TITLE
有3个appid，一个超额另外两个工作，但无法访问谷歌

### ISSUE THREAD

**Issue by k15257036** [XX-net/XX-Net#11479]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
当前版本3.2.11

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是的

* 是否以相关关键词搜索过类似 issues？
搜索，未找到解决方法

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
我的appid有三个，其中一个超额了，另外两个显示还在工作，但无法正常访问谷歌。这个情况以前也出现过一次。等到额度刷新后解决了。
XX-Net Status:
sys-platform: x86_64, Darwin-17.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
os-release: 17.7.0
os-detail: Release:10.13.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
xxnet-version: 3.12.11
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:1000 ipv4:0 ipv6:982
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 332
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

日志
Sep 18 23:17:35.240 - [WARNING] 2a02:a000:2:204::f host:fleet-scout-209805.appspot.com head fail status:404
Sep 18 23:17:35.240 - [DEBUG] report_connect_fail:2a02:a000:2:204::f
Sep 18 23:17:35.528 - [DEBUG] recheck_ip:2a02:a000:1:205::12 restore ok
Sep 18 23:17:36.196 - [WARNING] 2a02:8400:0:108::f host:ivory-program-209805.appspot.com head fail status:404
Sep 18 23:17:36.196 - [DEBUG] report_connect_fail:2a02:8400:0:108::f
Sep 18 23:17:36.532 - [DEBUG] recheck_ip:2a02:a000:2:204::f restore ok
Sep 18 23:17:36.533 - [DEBUG] 2a02:a000:2:204::f worker close:keep alive
Sep 18 23:17:37.865 - [DEBUG] recheck_ip:2a02:8400:0:108::f restore ok
Sep 18 23:17:37.866 - [DEBUG] 2a02:8400:0:108::f worker close:keep alive
Sep 18 23:17:41.549 - [DEBUG] recheck_ip:2a02:c7a:8000:1205::f restore ok
Sep 18 23:17:42.276 - [DEBUG] GAEProxy web_control 127.0.0.1:60465 POST /config?cmd=get_config
Sep 18 23:17:46.805 - [DEBUG] recheck_ip:2a02:8400:0:104::13 restore ok
Sep 18 23:17:52.241 - [DEBUG] recheck_ip:2a00:23a0:36::12 restore ok
Sep 18 23:17:53.412 - [DEBUG] GAE GET https://www.google.com.hk/ from:127.0.0.1:60786
Sep 18 23:17:54.248 - [DEBUG] create_ssl update ip:2404:6800:400b:2a::8 time:322 h2:0 sni:category.excuse.dirt.net, host:fleet-scout-209805.appspot.com
Sep 18 23:17:54.407 - [DEBUG] create_ssl update ip:2a00:1450:4007:2d::9 time:989 h2:0 sni:gas.kitchen.us, host:ivory-program-209805.appspot.com
Sep 18 23:17:55.609 - [WARNING] task POST None /_gh/ timeout
Sep 18 23:17:55.609 - [WARNING] IP:2404:6800:400b:2a::8 not support GAE, headers:{'Date': 'Tue, 18 Sep 2018 15:17:55 GMT', 'Content-Length': '1551', 'Alt-Svc': 'quic=":443"; ma=2592000; v="44,43,39,35"', 'Content-Type': 'text/html; charset=UTF-8'} status:404
Sep 18 23:17:55.609 - [DEBUG] report_connect_fail:2404:6800:400b:2a::8
Sep 18 23:17:56.174 - [DEBUG] recheck_ip:2404:6800:400b:2a::8 restore ok
Sep 18 23:17:56.175 - [DEBUG] 2404:6800:400b:2a::8 worker close:ip not support GAE
Sep 18 23:17:56.175 - [DEBUG] GAE_Exception 602 'ip not support GAE'
Sep 18 23:17:56.175 - [WARNING] gae_exception:'602:ip not support GAE' https://www.google.com.hk/
Sep 18 23:17:56.275 - [DEBUG] 2404:6800:400b:2a::8 worker close:exit
Sep 18 23:17:56.497 - [DEBUG] create_ssl update ip:2404:6800:400b:2f::8 time:318 h2:0 sni:funpiano.ml, host:ivory-program-209805.appspot.com
Sep 18 23:17:56.518 - [WARNING] task POST None /_gh/ timeout
Sep 18 23:17:56.518 - [WARNING] IP:2a00:1450:4007:2d::9 not support GAE, headers:{'Date': 'Tue, 18 Sep 2018 15:17:56 GMT', 'Content-Length': '1551', 'Alt-Svc': 'quic=":443"; ma=2592000; v="44,43,39,35"', 'Content-Type': 'text/html; charset=UTF-8'} status:404
Sep 18 23:17:56.518 - [DEBUG] report_connect_fail:2a00:1450:4007:2d::9
Sep 18 23:17:57.960 - [DEBUG] recheck_ip:2a00:1450:4007:2d::9 restore ok
Sep 18 23:17:57.962 - [DEBUG] 2a00:1450:4007:2d::9 worker close:ip not support GAE
Sep 18 23:17:57.962 - [DEBUG] GAE_Exception 602 'ip not support GAE'
Sep 18 23:17:57.963 - [WARNING] gae_exception:'602:ip not support GAE' https://www.google.com.hk/
Sep 18 23:17:58.069 - [WARNING] task POST None /_gh/ timeout
Sep 18 23:17:58.069 - [WARNING] IP:2404:6800:400b:2f::8 not support GAE, headers:{'Date': 'Tue, 18 Sep 2018 15:17:58 GMT', 'Content-Length': '1551', 'Alt-Svc': 'quic=":443"; ma=2592000; v="44,43,39,35"', 'Content-Type': 'text/html; charset=UTF-8'} status:404
Sep 18 23:17:58.069 - [DEBUG] report_connect_fail:2404:6800:400b:2f::8
Sep 18 23:17:58.176 - [DEBUG] recheck_ip:2806:1020:cfff:7::13 restore ok
Sep 18 23:17:58.381 - [DEBUG] 2a00:1450:4007:2d::9 worker close:exit
Sep 18 23:17:58.675 - [DEBUG] create_ssl update ip:2607:f8b0:4009:3b::c time:705 h2:0 sni:fact-future-buy.us, host:ivory-program-209805.appspot.com
Sep 18 23:17:58.906 - [DEBUG] recheck_ip:2404:6800:400b:2f::8 restore ok
Sep 18 23:17:58.907 - [DEBUG] 2404:6800:400b:2f::8 worker close:ip not support GAE
Sep 18 23:17:58.907 - [DEBUG] GAE_Exception 602 'ip not support GAE'
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
不存在`ivory-program-209805`这个 ID，请检查。

**Comment by AnyWAT** [comment]
gws-ip-num: total:1000 ipv4:0 ipv6:982 ——1000貌似有点大？有效 IP 数不能达到总 IP 数，打开了某开关的特征
scan-ip-thread-num: 1 ——如非人为设置为1，即打开了某开关的特征
recheck_ip ——打开了某开关的特征
😜关闭“自动调整扫描线程数”。。。

**Comment by AnyWAT** [comment]
gws-ip-num: total:1000 ipv4:0 ipv6:982 ——1000貌似有点大？（bu）有效 IP 数不能达到总 IP 数，打开了某开关的特征
scan-ip-thread-num: 1 ——如非人为设置为1，即打开了某开关的特征
recheck_ip ——打开了某开关的特征
😜关闭“自动调整扫描线程数”。。。

**Comment by AnyWAT** [comment]
gws-ip-num: total:1000 ipv4:0 ipv6:982 ——1000貌似有点大？有效 IP 数不能达到总 IP 数，打开了某开关的特征
scan-ip-thread-num: 1 ——如非人为设置为1，即打开了某开关的特征
recheck_ip ——打开了某开关的特征
😜关闭“自动调整扫描线程数”。。。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/45699962-f20d0800-bb9d-11e8-9425-7beb54e04f79.png)

**Comment by SeaHOH** [comment]
看清楚问题，再乱来就封你。

**Comment by AnyWAT** [comment]
何解？
![default](https://user-images.githubusercontent.com/37962734/45700196-7c556c00-bb9e-11e8-8e04-b24eca318cc2.png)

**Comment by SeaHOH** [comment]
结合问题描述、日志和https://github.com/XX-net/XX-Net/issues/11479#issuecomment-422443688 ，你觉得这是什么原因？

**Comment by AnyWAT** [comment]
不识代码，只解决被人删除的东东😜

**Comment by SeaHOH** [comment]
又没让你看代码，我写的中文你还看不懂吗？

以前也有人报告，但就是不爱贴完整的日志，我也懒得去追究根源。
这次有了完整的情况说明和日志，一下就发现根本原因。

**Comment by AnyWAT** [comment]
逻辑、逻辑、逻辑！
有ID能工作，正如楼主“有3个appid，一个超额另外两个工作，但无法访问谷歌”
故：根本原因——关闭某开关😂

**Comment by AnyWAT** [comment]
😝至于再三恶意地删除、“再乱来就封你”，不是讨论问题的态度？

**Comment by SeaHOH** [comment]
> 不存在`fleet-scout-209805` `ivory-program-209805`这两个 ID，请检查。

你果然看不懂中文么？？

**Comment by AnyWAT** [comment]
Appids_Not_Exist: false 😜重要！你的“不存在fleet-scout-209805 ivory-program-209805这两个 ID，请检查。”与软件自身判断有出入

**Comment by SeaHOH** [comment]
所以是 bug 啊，你真的看了嘛？？
![x2scrap2](https://user-images.githubusercontent.com/8470820/45701991-2a8df100-bb60-11e8-9fff-a9b0c2b24238.png)

**Comment by AnyWAT** [comment]
我基本上只看
netsh int ipv6 show teredo 运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by SeaHOH** [comment]
是让你看我的操作，标记、修复 bug。
这么明显的动作，你是在装傻嘛？？

**Comment by AnyWAT** [comment]
是傻，不明白。。。早看见，不是不识码人的事
Appid_Working: true 无法访问谷歌 及某些XX-Net 诊断信息的特征值。足以说明、解决。。。

**Comment by AnyWAT** [comment]
🙃贴主说话呀，正常了么？

**Comment by SeaHOH** [comment]
我已经说的这么明显了，诊断信息存在错误。
如果你还继续坚持装傻，就真有必要封你。

**Comment by AnyWAT** [comment]
封吧，你这个无赖😋

**Comment by SeaHOH** [comment]
不开玩笑，你真的看不懂我写的嘛？

**Comment by AnyWAT** [comment]
不明白，你要表达什么

**Comment by SeaHOH** [comment]
> 诊断信息存在错误

然后我修复了。
最后一次。

**Comment by AnyWAT** [comment]
诊断信息存在错误——XX-Net 诊断信息也错了？

**Comment by SeaHOH** [comment]
> 你自己都给别人科普过，访问验证下不就知道了。

你已经浪费我不少时间了。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/45703442-eb36c300-bba6-11e8-9541-d40e7dcf0994.png)
你已经浪费我不少时间了。——到底是谁、谁？

**Comment by AnyWAT** [comment]
😡你解决你的BUG，我解决你不承认的锅，互不相干，屡次删除别人的，到底谁在纠结谁？

**Comment by AnyWAT** [comment]
也来个“最后一次。”
据一年多的使用、观察经验：软件的”自动调整扫描线程数“，必须在有效 IP数达到总 IP数后才能（自动）启用，正如以前的版本，即使调整为0也能很好工作，没有现在的问题：有效 IP、连接池不断地掉，IP延时不停地涨，但扫描线程仍旧。。。直至玩完，代理不了了😂

**Comment by k15257036** [comment]
> 何解？
> ![default](https://user-images.githubusercontent.com/37962734/45700196-7c556c00-bb9e-11e8-8e04-b24eca318cc2.png)
> 🤣看清楚问题，再乱来就封你。
> 关闭“自动调整。。。”100%解决楼主问题🤣

昨晚提了问就睡觉去，感谢各位的回复，没能及时回复各位非常抱歉。

我已关闭“自动调整扫描线程数”，但问题仍然没有得到解决。

**Comment by k15257036** [comment]
> 不存在`fleet-scout-209805` `ivory-program-209805`这两个 ID，请检查。

<img width="658" alt="wx20180919-070307 2x" src="https://user-images.githubusercontent.com/32164570/45721315-2e5e5980-bbda-11e8-9cd9-2d2349d53285.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/32164570/45721426-a298fd00-bbda-11e8-9d95-65e4fdcfa1d9.png">


您好，我查看了一下，这两个ID在我的谷歌console里是存在的。请问您需要我向您提供哪些信息？

**Comment by k15257036** [comment]
> > 不存在`fleet-scout-209805` `ivory-program-209805`这两个 ID，请检查。
> 
> <img alt="wx20180919-070307 2x" width="658" src="https://user-images.githubusercontent.com/32164570/45721315-2e5e5980-bbda-11e8-9cd9-2d2349d53285.png">
> 
> <img alt="image" width="592" src="https://user-images.githubusercontent.com/32164570/45721426-a298fd00-bbda-11e8-9d95-65e4fdcfa1d9.png">
> 
> 您好，我查看了一下，这两个ID在我的谷歌console里是存在的。请问您需要我向您提供哪些信息？

当我在google console里查看项目时，超额的AppID显示正常，显示如下
<img width="856" alt="image" src="https://user-images.githubusercontent.com/32164570/45722600-b5620080-bbdf-11e8-9afb-66f993101ae0.png">

但是另外两个显示如下
<img width="592" alt="image" src="https://user-images.githubusercontent.com/32164570/45722520-5bf9d180-bbdf-11e8-8d0d-8a5c1cea95e8.png">

选择语言为python后，显示如下
<img width="845" alt="image" src="https://user-images.githubusercontent.com/32164570/45722548-76cc4600-bbdf-11e8-867a-cfd47d9c5168.png">

一直点continue，最终显示如下
<img width="845" alt="image" src="https://user-images.githubusercontent.com/32164570/45722568-9499ab00-bbdf-11e8-9cb0-f09797eed7e3.png">

无论怎么操作都无法显示成超额AppID显示的那个样子。
按tutorial走了一遍hello world，也没什么用

现在回想起来，超额的那个AppID是第一次创建的，后来因为老超额，就在隔后的某段时间里创建了后两个AppID，但因为一直是轻度使用所以也没发现问题。这几天又超额了，发现了这个问题。我觉得可能是我在配置后两个AppID时出现了问题。现在准备重新创建新的AppID试一试，结果我会贴在后面。

**Comment by k15257036** [comment]
重新创建了一个新的AppID，然后问题得到解决，可以重新访问真的互联网了。
现在分析出错原因：

场景：我有一个可正常访问谷歌学术（我自己的IPV6网能访问谷歌，但不能访问谷歌学术，所以拿谷歌学术作验证）的AppID A，因为额度不够，我又去google console创建了AppID B 和 C。是同时创建了两个AppID，出现了画面如下
![](https://user-images.githubusercontent.com/31188782/31053687-ac1721d8-a6d5-11e7-9d44-74c9797d6ae7.JPG)

之后，我又进入XX-net部署页面，输入A|B|C，开始部署。之后弹出窗口询问是否允许，点击允许。
进入配置页面，保存A|B|C，此时可以访问谷歌学术。

后来的事实证明，当A超额之后，B|C无法启用。
因为B|C一直显示要我创建“your first APP”，可以我并没有成功部署B|C。

现在终于理解了xx-net和google AppID的关系。创建好AppID后，是获得了一个谷歌的ID，但是还没有APP，因此需要xx-net来创建和部署这个APP，这个过程要在xx-net的部署页面实现。
部署成功后，这个APP就存在了，此时，要让你的xx-net和APP产生连接，这个过程要在xx-net的配置页面实现。
完成以上两个步骤，才能访问真的互联网。

再分析我的问题，我怀疑我再次部署A|B|C时出现了bug，并没有实现对B|C的部署，bug出现的原因可能是因为A已经部署过。我没有试过同时部署B|C是否能成功。
保险起见，将B和C分开单独部署比较好，不要采取B|C同时部署的形式。

至于Tutorial里的 Hello world，见鬼去吧🙂

再次感谢 @AnyWAT @SeaHOH

**Comment by AnyWAT** [comment]
我已关闭“自动调整扫描线程数”，但问题仍然没有得到解决。——因 worker: h1:0 h2:0 连接池已归零，宜检查IP、同时刷新或新开需代理的网页触发。。。才能复活 #11291 
关闭了某开关，才（几乎）不出现：
1、有效IP数达不到总IP数（达到后软件自动剔除延时大的 IP），并不断地减小
2、不断减小的连接池，甚至归零
3、不断增大的 IP延时
然后“假工作”，代理不正常，报错。。。

**Comment by AnyWAT** [comment]
你自己都给别人科普过，访问验证下不就知道了。——刚才明白☞
![image](https://user-images.githubusercontent.com/37962734/45726088-61134c80-bbf0-11e8-94b7-6036d809a160.png)

搞不懂你的回路。—— 明明 Appids_Not_Exist: false 到底谁的回路有无逻辑？

**Comment by fredericky123** [comment]
解决问题就直接干脆点，经常性看到any到处发那个经验贴，毫无实际意义，又看到在这里和海少争论，真是无聊，一看到那些乱七八糟的表情，那些乱七八糟的“某开关”就不爽，支持海少
