### ISSUE TITLE
经常断线

### ISSUE THREAD

**Issue by NEU20161241** [XX-net/XX-Net#11478]
启动XX-NET之后可以正常访问ipv6，但是一段时间后就使用不了"google"等，需要在网络连接的属性中重新取消勾选ipv6再勾选ipv6，可以重新访问。校内自带ipv6

**Comment by AnyWAT** [comment]
试试：关闭“自动调整扫描线程数”？类比（隧道下的） #11291

**Comment by SeaHOH** [comment]
@AnyWAT 情况完全不同，你不要误导他人。

@NEU20161241 连不上时，检查你的网络状态，如果不会分析可以把结果贴过来。
win：`ipconfig`
linux：`ifconfig`
http://test-ipv6.com/

**Comment by NEU20161241** [comment]
ipconfig 
Windows IP 配置


以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 8:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 2001:da8:9000:a261:38ec:430f:12d5:e9ec
   本地链接 IPv6 地址. . . . . . . . : fe80::38ec:430f:12d5:e9ec%5
   IPv4 地址 . . . . . . . . . . . . : 58.154.194.228
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : fe80::3a97:d6ff:fe51:a0a2%5
                                       58.154.194.254

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 2001:0:9d38:6ab8:141c:27c8:c565:3d1b
   本地链接 IPv6 地址. . . . . . . . : fe80::141c:27c8:c565:3d1b%12
   默认网关. . . . . . . . . . . . . :

**Comment by NEU20161241** [comment]
| 你的公网 IPv4 地址是 58.154.194.228(ERX-CERNET-BKB China Education and Research Network Center)
-- | --

**Comment by NEU20161241** [comment]
test-ipv6是 10/10 
因为刚刚我自己手动重启过

**Comment by SeaHOH** [comment]
连不上时再检查。
你可以把 teredo 关掉，看看到底学校提供的 IP 能否使用。
记得下次以其它字符替代 IP 后半部分。

**Comment by NEU20161241** [comment]
> 连不上时再检查。
> 你可以把 teredo 关掉，看看到底学校提供的 IP 能否使用。
> 记得下次以其它字符替代 IP 后半部分。

好的谢谢

**Comment by NEU20161241** [comment]
> 连不上时再检查。
> 你可以把 teredo 关掉，看看到底学校提供的 IP 能否使用。
> 记得下次以其它字符替代 IP 后半部分。

输入netsh interface teredo set state disable 并退出xx-net将switchomega调整为自动连接后，仍然可以访问谷歌，test-ipv6也是10/10, 不过似乎youtube上不去

**Comment by AnyWAT** [comment]
😂或许适用Hozz +  ipv6-hosts 大法上 youtube ？

**Comment by SeaHOH** [comment]
不用退 XX-Net，继续用就行。
楼上方法也不错，不过 twitter 估计不行，我没这样用，你可以试试。

**Comment by woyaohaohaoxuexi** [comment]
我也是一直遇到这个问题，现在修改了SwitchyOmega这个插件的初始情景模式为GAE-Proxy自动切换就好了

**Comment by NEU20161241** [comment]
你的公网 IPv4 地址是 58.154.***.***
你的运营商（ISP）是 ERX-CERNET-BKB China Education and Research Network Center
在你所在的地区，本站的测试结果并不可靠。
没有检测到 IPv6 地址 [更多信息]
你只接入了 IPv4 互联网，不能访问纯 IPv6 网站。
为了实现最佳的网络性能，向你的运营商咨询原生 IPv6 事宜吧。 [更多信息]
本站现已支持 HTTPS。 [更多信息]
你的 DNS 服务器（可能由运营商提供）已经接入 IPv6 互联网了。
--
以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 8:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 2001:da8:9000:a261:****:****:****:****
   本地链接 IPv6 地址. . . . . . . . : fe80::38ec:430f:****:******
   IPv4 地址 . . . . . . . . . . . . : 58.154.***.***
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 58.154.***.***


登陆使用了一段时间后，

现在是连不上的情况

**Comment by NEU20161241** [comment]
> 我也是一直遇到这个问题，现在修改了SwitchyOmega这个插件的初始情景模式为GAE-Proxy自动切换就好了

不是这个问题

**Comment by SeaHOH** [comment]
尝试运行以下命令，然后重启计算机。 
```bat
:: 重置 IPv6 设置
netsh interface ipv6 reset
```
如果这样还是老断，可能和路由器，或者 IP 分配设置有关。

**Comment by styrenes** [comment]
我也经常连不上。
有时看着一切都正常，就是翻不了墙。只好重起xxnet，坚持个几秒到几十分钟。

**Comment by spenserwong** [comment]
我也经常碰到这种断线的问题，一般重新启动一下XX-net就可以了，我的IPV6的状态好象是不太好，测试的很多项目都没通过
