### ISSUE TITLE
今天突然出现问题，求解决！

### ISSUE THREAD

**Issue by gitxxnet2018** [XX-net/XX-Net#11470]
以下为抓取的状态信息：

Sep 17 10:48:41.132 - [DEBUG] create ssl timeout fail.
Sep 17 10:49:15.333 - [WARNING] CONNECT mtalk.google.com port:5228 not support
Sep 17 10:49:41.242 - [DEBUG] create ssl timeout fail.
Sep 17 10:50:41.346 - [DEBUG] create ssl timeout fail.
Sep 17 10:51:41.549 - [DEBUG] create ssl timeout fail.
Sep 17 10:52:41.671 - [DEBUG] create ssl timeout fail.
Sep 17 10:53:42.396 - [DEBUG] create ssl timeout fail.
Sep 17 10:54:42.402 - [DEBUG] create ssl timeout fail.
Sep 17 10:55:29.399 - [WARNING] CONNECT mtalk.google.com port:5228 not support
Sep 17 10:55:42.827 - [DEBUG] create ssl timeout fail.
Sep 17 10:56:43.828 - [DEBUG] create ssl timeout fail.
Sep 17 10:57:08.842 - [DEBUG] GAE GET http://www.google.com.hk/ from:127.0.0.1:5126
Sep 17 10:57:23.943 - [WARNING] task POST None /_gh/ timeout
Sep 17 10:57:23.943 - [DEBUG] GAE_Exception 600 'fetch gae fail'
Sep 17 10:57:23.943 - [WARNING] gae_exception:'600:fetch gae fail' http://www.google.com.hk/
Sep 17 10:57:43.840 - [DEBUG] create ssl timeout fail.
Sep 17 10:57:43.955 - [WARNING] task POST None /_gh/ timeout
Sep 17 10:57:43.955 - [DEBUG] GAE_Exception 600 'fetch gae fail'
Sep 17 10:57:43.955 - [WARNING] gae_exception:'600:fetch gae fail' http://www.google.com.hk/
Sep 17 10:58:13.957 - [WARNING] task POST None /_gh/ timeout
Sep 17 10:58:13.957 - [DEBUG] GAE_Exception 600 'fetch gae fail'
Sep 17 10:58:13.957 - [WARNING] gae_exception:'600:fetch gae fail' http://www.google.com.hk/
Sep 17 10:58:13.957 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' http://www.google.com.hk/gae_exception:'600:fetch gae fail' http://www.google.com.hk/gae_exception:'600:fetch gae fail' http://www.google.com.hk/"
Sep 17 10:58:13.957 - [WARNING] GAE GET http://www.google.com.hk/ request fail:"600:gae_exception:'600:fetch gae fail' http://www.google.com.hk/gae_exception:'600:fetch gae fail' http://www.google.com.hk/gae_exception:'600:fetch gae fail' http://www.google.com.hk/"
Sep 17 10:58:13.957 - [WARNING] send response fail
Sep 17 10:58:13.957 - [WARNING] send response fail
Sep 17 10:58:44.556 - [DEBUG] create ssl timeout fail.
Sep 17 10:59:19.818 - [WARNING] CONNECT mtalk.google.com port:5228 not support
Sep 17 10:59:44.744 - [DEBUG] create ssl timeout fail.
Sep 17 11:00:45.622 - [DEBUG] create ssl timeout fail.

其他状态：

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 空闲
IP 延迟 | 475
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | Fail
**CA 证书状态(下载) | Fail**
IP 扫描线程数(设置) | 7

属性 | 值
-- | --
XX-Net 状态 | 空闲
浏览器代理设置 | Fail
CA 证书状态(下载) | Fail
系统代理 | 全局代理禁用

由于没法翻墙访问，github无法上传图片，哪位大侠能帮我诊断诊断！

**Comment by gitxxnet2018** [comment]
已经解决了，重新上传了证书并重启电脑后又正常了！

**Comment by AnyWAT** [comment]
重新上传（导入？）了证书：纯属多余😂 
XX-Net 状态 | 空闲
连接池(帮助) | 新:0 h1:0 h2:0 ——貌似某开关的锅 #11291
