### ISSUE TITLE
安卓手机使用xndroid，如何把服务器设置为美国的。

### ISSUE THREAD

**Issue by woyaohaohaoxuexi** [XX-net/XX-Net#11477]
在打开google play的时候，提示服务信息错误，在网上查了一下，可能是vpn的问题，如果vpn设置的是日本、美国的话，应该就可以了。想问下如何把服务器设置为美国。

**Comment by woyaohaohaoxuexi** [comment]
> 貌似不可能？
> 貌似使用其它设备的XX-Net 代理服务时 google play 即可正常
> google play 的近似替代 https://m.apkpure.com 或 https://apkpure.com
> 此时破电脑在使用破安卓提供的代理
> ![default](https://user-images.githubusercontent.com/37962734/45674863-88223d80-bb60-11e8-8dde-c43c5452ad08.png)

使用x-Tunnel代理可以吗？

**Comment by AnyWAT** [comment]
自己试，当时使用电脑的XX-Net 代理服务，google play 正常的更破安卓已挂😜

**Comment by woyaohaohaoxuexi** [comment]
> 自己试，当时使用电脑的XX-Net 代理服务，google play 正常的更破安卓（因硬件）已挂
> 剩下的破小米对 google 不友好，没法。。。

我去找下别的vpn吧。关于这方面的知识，如何去学习呀

**Comment by AnyWAT** [comment]
https://m.apkpure.com 上有的

**Comment by woyaohaohaoxuexi** [comment]
> https://m.apkpure.com 上有的

谢谢了，不过我还是想打开google play

**Comment by AnyWAT** [comment]
有了赛风等，或许 google play 会正常？

**Comment by woyaohaohaoxuexi** [comment]
> 有了（运行）赛风等，或许 google play 会正常？

赛风确实可以了，就是不太稳定

**Comment by woyaohaohaoxuexi** [comment]
> 有了（运行）赛风等，或许 google play 会正常？

你知道有哪些好用的vpn吗？不管付费还是免费的

**Comment by AnyWAT** [comment]
不知。不太稳定，试试里面的各设置？

**Comment by milanthree** [comment]
我手机用的express vpn，貌似还行，不过感觉有点小贵

**Comment by AnyWAT** [comment]
新发现 International Internet - https://dcamero.azurewebsites.net/
