### ISSUE TITLE
用管理员权限运行start.bat仍显示没有权限（代码800A0046）

### ISSUE THREAD

**Issue by Demon-crazy** [XX-net/XX-Net#11484]
求教。用管理员权限运行文件夹内的start.bat显示没有权限（代码800A0046），打开管理员权限的cmd运行仍显示没有权限（代码800A0046）。用搜索到的一些方法没有解决此问题。

**Comment by SeaHOH** [comment]
不要在系统盘运行

**Comment by Demon-crazy** [comment]
> 不要在系统盘运行

你好。之前所述是在非系统盘运行时发生的。

**Comment by SeaHOH** [comment]
文件夹权限截图来看下

**Comment by Demon-crazy** [comment]
> 文件夹权限截图来看下
[https://graph.baidu.com/resource/10bad39b590af139bf1f201537433308.jpg](url)
用户权限改了完全控制貌似也不行。

**Comment by SeaHOH** [comment]
其它用户组呢，有没有拒绝的。

**Comment by Demon-crazy** [comment]
> 其它用户组呢，有没有拒绝的。

没有。

**Comment by SeaHOH** [comment]
不懂。
试试重新解压到其它盘。

**Comment by Demon-crazy** [comment]
> 不懂。
> 试试重新解压到其它盘。

按使用方法操作是否有其他软件或环境的前置需求？

**Comment by Demon-crazy** [comment]
> 不懂。
> 试试重新解压到其它盘。

你好。尝试解压在其他盘未能解决问题。这是运行错误的截图。
[https://graph.baidu.com/resource/10760d48436d09a601c0f01537440373.jpg](url)

**Comment by SeaHOH** [comment]
> 按使用方法操作是否有其他软件或环境的前置需求？

Windows 开袋即食。


> 你好。尝试解压在其他盘未能解决问题。这是运行错误的截图。
> [https://graph.baidu.com/resource/10760d48436d09a601c0f01537440373.jpg](url)

建议你换个用户登录，比如原始管理员账户。

**Comment by Demon-crazy** [comment]
> > 按使用方法操作是否有其他软件或环境的前置需求？
> 
> Windows 开袋即食。
> 
> > 你好。尝试解压在其他盘未能解决问题。这是运行错误的截图。
> > [https://graph.baidu.com/resource/10760d48436d09a601c0f01537440373.jpg](url)
> 
> 建议你换个用户登录，比如原始管理员账户。

新建管理员账户或者使用内置管理员账户均出现同样提示。
目前对XX-net的并没有迫切的需求，暂时告一段落吧。感谢耐心回复！

**Comment by Demon-crazy** [comment]
> 还个办法，不用运行 VBS 脚本，直接用 bat。
> 
> ```batchfile
> @for /f %%i in (code\version.txt) do @set version=%%i
> @start "%~dp0code\%version%\python27\1.0\python.exe" "%~dp0code\%version%\launcher\start.py"
> ```

不好意思，因为之后没再登录了，没有看见回复。尝试复制代码新建bat，但用管理员权限运行提示找不到start.py；直接运行则红字报错。附上截图。
管理员权限运行：https://graph.baidu.com/resource/1e60e4d147c6b1c953ac201538742948.jpg
直接运行：https://graph.baidu.com/resource/1503ce54cf670004f20b101538742923.jpg

**Comment by SeaHOH** [comment]
是否丢失 code\version.txt，或者内容是空白？

**Comment by Demon-crazy** [comment]
> 是否丢失 code\version.txt，或者内容是空白？

没有丢失，打开里面只有一行default。

**Comment by SeaHOH** [comment]
换英文目录试试，不要有中文。

**Comment by Demon-crazy** [comment]
> 你是不是安装有 python？
> 前面加两句
> 
> ```batchfile
> SET PYTHONPATH=
> SET PYTHONHOME=
> ```

已解决。直接在start.py 的打开方式选择code文件夹下自带的python即可。

**Comment by SeaHOH** [comment]
> > 你是不是安装有 python？
> > 前面加两句
> > ```batchfile
> > SET PYTHONPATH=
> > SET PYTHONHOME=
> > ```
> 
> 已解决。直接在start.py 的打开方式选择code文件夹下自带的python即可。

不要这样干，会影响你正常使用安装版本，先前那个 bat 直接加上这两句即可。
