### ISSUE TITLE
手机使用xndroid，不能打开youtube app google商店也不能打开

### ISSUE THREAD

**Issue by zhqh68** [XX-net/XX-Net#11487]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
试过

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
查看过

* 是否以相关关键词搜索过类似 issues？

搜索过
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。
我的手机是华为荣耀v8，android版本是8.0，在使用xndroid(已经更新最新版本）翻墙时，用浏览器能打开youtube Google商店，但如果用youtube app google play app时不能打开，但用赛风能正常打开。

**Comment by AnyWAT** [comment]
https://github.com/XndroidDev/Xndroid 兼容性与局限性：注意一些APP(如 Twitter, Facebook 等)由于不信任GAE的证书,可能无法正常访问网络, 建议在浏览器中使用.
PS：貌似用其它设备的XX-Net 代理服务，不再有此局限😜

**Comment by SeaHOH** [comment]
#11058
