### ISSUE TITLE
谁能介绍一个收费的简单好用的翻墙软件

### ISSUE THREAD

**Issue by ncmon** [XX-net/XX-Net#11481]
有个朋友想翻墙看youtube，x—tunnel看视频速度不太流畅会卡而且paypal支付也不会用，谁能帮忙介绍一个自己用过收费比较稳定的电脑版翻墙软件

**Comment by akari263** [comment]
[自己组建SSR服务器，](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)
我用的是3.5美刀左右1个月，首次充值送25美刀，好像搬瓦工更便宜，唯一问题就是半个月左右服务器会被墙，要重新建立，虽然能无限制建立，不过每次要付0.01美刀

**Comment by zjgbql** [comment]
半个月被墙？看人品的！我用了几年了也不见被墙啊。

**Comment by akari263** [comment]
> 半个月被墙？看人品的！我用了几年了也不见被墙啊。

反正我8月份开始用，到现在大概被封了2个IP，不过也的确看人品，现在这个用了3周了

**Comment by milanthree** [comment]
用的express vpn，不过略贵，要快7美刀一个月了
