### ISSUE TITLE
透过XXNet git clone的时候总是莫名其妙断掉，有人遇到过类似问题么？

### ISSUE THREAD

**Issue by lancewoo** [XX-net/XX-Net#11480]
设置了XXNet做git的HTTP代理后，在clone的时候是很快，但是貌似每次到了30多兆的时候都自动断掉了。怀疑是不是XXNet的原因？如果不走代理，clone的会很慢，但是不会断掉。

有大神遇到过类似问题么，给指点一下？
谢谢！

`
$ git config --global http.proxy 127.0.0.1:8087
$ git config --global http.sslverify false
$ git clone https://github.com/google/ExoPlayer.git
Cloning into 'ExoPlayer'...
remote: Counting objects: 137157, done.
fatal: The remote end hung up unexpectedly.70 MiB | 684.00 KiB/s   
fatal: early EOF
fatal: index-pack failed
2018-09-19 09:44:20:~/work/projects/tmp`

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是。

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是。

* 是否以相关关键词搜索过类似 issues？
是。

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

Sep 19 09:39:17.873 - [INFO] ------------------------------------------------------

Sep 19 09:39:17.873 - [INFO] Python Version : 2.7.12

Sep 19 09:39:17.873 - [INFO] OS : Dist:Ubuntu; Version:16.04; ID:xenial

Sep 19 09:39:17.873 - [INFO] Listen Address : 127.0.0.1:8087

Sep 19 09:39:17.873 - [INFO] GAE APPID : 

Sep 19 09:39:17.874 - [INFO] ------------------------------------------------------

Sep 19 09:39:17.903 - [DEBUG] Importing CA

Sep 19 09:39:18.021 - [INFO] Database $HOME/.pki/nssdb cert exist

Sep 19 09:39:18.021 - [DEBUG] Begin importing CA to Firefox

Sep 19 09:39:18.021 - [INFO] Removing old cert to Firefox in /home//.mozilla/firefox/kobkscwk.default

Sep 19 09:39:18.030 - [INFO] Add new cert to Firefox in /home//.mozilla/firefox/kobkscwk.default

Sep 19 09:39:18.036 - [INFO] SSL use version:TLSv1_2

Sep 19 09:39:18.037 - [INFO] OpenSSL support alpn

Sep 19 09:39:18.037 - [INFO] load ip range file:/home//software/XX-Net-3.11.10/code/3.12.11/gae_proxy/local/ip_range.txt

Sep 19 09:39:18.038 - [INFO] load ip_list num:100, target num:100

Sep 19 09:39:18.039 - [INFO] Adjust scan thread num from 10 to 1

Sep 19 09:39:18.040 - [INFO] SSL use version:TLSv1_2

Sep 19 09:39:18.041 - [INFO] server 127.0.0.1:8087 started.

Sep 19 09:39:19.726 - [DEBUG] recheck_ip:2607:f8b0:4007:30::a restore ok

Sep 19 09:39:20.907 - [DEBUG] recheck_ip:2a00:1450:4017:8::b restore ok

Sep 19 09:39:24.410 - [DEBUG] recheck_ip:2607:f8b0:4005::a restore ok

Sep 19 09:39:29.343 - [DEBUG] recheck_ip:2607:f8b0:401c:8::b restore ok

Sep 19 09:39:34.579 - [DEBUG] recheck_ip:2607:f8b0:400a:1::6 restore ok

Sep 19 09:39:43.607 - [DEBUG] recheck_ip:2607:f8b0:4017:26::9 restore ok

Sep 19 09:39:48.528 - [DEBUG] recheck_ip:2607:f8b0:400a:14::9 restore ok

Sep 19 09:39:53.974 - [DEBUG] recheck_ip:2607:f8b0:4006:33::8 restore ok

Sep 19 09:39:59.720 - [DEBUG] recheck_ip:2607:f8b0:4006:31::9 restore ok

Sep 19 09:40:04.840 - [DEBUG] recheck_ip:2607:f8b0:4006:3b::7 restore ok

Sep 19 09:40:09.986 - [DEBUG] recheck_ip:2607:f8b0:401e:25::7 restore ok

Sep 19 09:40:19.081 - [DEBUG] recheck_ip:2607:f8b0:4004:32::b restore ok

Sep 19 09:40:24.547 - [DEBUG] recheck_ip:2607:f8b0:4000:3f::7 restore ok

Sep 19 09:40:29.694 - [DEBUG] recheck_ip:2001:4958:300:505::11 restore ok

Sep 19 09:40:35.120 - [DEBUG] recheck_ip:2607:f8b0:400b:10::9 restore ok

Sep 19 09:40:40.302 - [DEBUG] recheck_ip:2607:f8b0:4002:30::9 restore ok

Sep 19 09:40:45.643 - [DEBUG] recheck_ip:2607:f8b0:4012:10::6 restore ok

Sep 19 09:40:54.583 - [DEBUG] recheck_ip:2607:f8b0:4008:e::9 restore ok

Sep 19 09:40:59.795 - [DEBUG] recheck_ip:2604:d600:0:4::e restore ok

Sep 19 09:41:05.020 - [DEBUG] recheck_ip:2607:f8b0:4008:3::7 restore ok

Sep 19 09:41:10.551 - [DEBUG] recheck_ip:2607:f798:14:40::f restore ok

Sep 19 09:41:15.991 - [DEBUG] recheck_ip:2a00:1450:4009:12::9 restore ok

Sep 19 09:41:21.432 - [DEBUG] recheck_ip:2a00:1450:401f:6::9 restore ok

Sep 19 09:41:30.883 - [DEBUG] recheck_ip:2404:6800:400e:3::c restore ok

Sep 19 09:41:36.700 - [DEBUG] recheck_ip:2001:918:ffaa:8::f restore ok

Sep 19 09:41:42.498 - [DEBUG] recheck_ip:2001:850:3110:304::16 restore ok

Sep 19 09:41:48.161 - [DEBUG] recheck_ip:2806:1030:cfff:9::d restore ok

Sep 19 09:41:53.823 - [DEBUG] recheck_ip:2604:9f00:800:3::11 restore ok

Sep 19 09:41:59.654 - [DEBUG] recheck_ip:2a02:a000:2:204::f restore ok

Sep 19 09:42:09.288 - [DEBUG] recheck_ip:2a02:8400:0:11b::11 restore ok

Sep 19 09:42:14.955 - [DEBUG] recheck_ip:2604:9f00:800:2::c restore ok

Sep 19 09:42:25.101 - [DEBUG] recheck_ip:2a04:ae39:204:2::c restore ok

Sep 19 09:42:31.106 - [DEBUG] recheck_ip:2a02:2000:1:e101::11 restore ok

Sep 19 09:42:37.218 - [DEBUG] recheck_ip:2001:b032:101:1::d restore ok

Sep 19 09:42:47.045 - [DEBUG] recheck_ip:2a00:1450:4017:8::b restore ok

Sep 19 09:42:55.958 - [DEBUG] recheck_ip:2a00:1450:4022:2::9 restore ok

Sep 19 09:43:05.119 - [DEBUG] recheck_ip:2001:4c48:11::12 restore ok

Sep 19 09:43:05.461 - [DEBUG] GAE GET https://github.com/google/ExoPlayer.git/info/refs?service=git-upload-pack from:127.0.0.1:48382

Sep 19 09:43:10.198 - [INFO] GAE t:4735 s:79189 GET https://github.com/google/ExoPlayer.git/info/refs?service=git-upload-pack 0:start_request,0:get_task(227),1540:get_worker(1):2607:f8b0:401c:8::b,0:h1_req,0:h1_req_sended,2769:response_begin,0:h1_get_head,0:get_response,404:h1_finish[SP:25038],:0

Sep 19 09:43:10.251 - [DEBUG] GAE POST https://github.com/google/ExoPlayer.git/git-upload-pack from:127.0.0.1:48382

Sep 19 09:43:11.301 - [DEBUG] recheck_ip:2404:6800:4005:10::8 restore ok

Sep 19 09:43:12.499 - [DEBUG] report_connect_fail:2607:f8b0:4005::a

Sep 19 09:43:21.074 - [DEBUG] recheck_ip:2800:3f0:4001:15::9 restore ok

Sep 19 09:43:26.899 - [DEBUG] recheck_ip:2800:3f0:4001:13::7 restore ok

Sep 19 09:43:32.682 - [DEBUG] recheck_ip:2404:6800:400c:5::8 restore ok

Sep 19 09:43:38.538 - [DEBUG] recheck_ip:2800:3f0:4001:14::b restore ok

Sep 19 09:43:44.364 - [DEBUG] recheck_ip:2404:6800:4005:26::8 restore ok

Sep 19 09:43:50.189 - [DEBUG] recheck_ip:2404:6800:4005:10::c restore ok

Sep 19 09:44:04.300 - [DEBUG] recheck_ip:2a00:1450:4015:c::1c restore ok

Sep 19 09:44:10.531 - [DEBUG] recheck_ip:2001:12e0:803:1::d restore ok

Sep 19 09:44:16.481 - [DEBUG] recheck_ip:2804:7f1:a000:cace::11 restore ok

Sep 19 09:44:20.907 - [INFO] GAE t:70655 s:33549677 POST https://github.com/google/ExoPlayer.git/git-upload-pack 0:start_request,0:get_task(3),0:get_worker(0):2607:f8b0:401c:8::b,0:h1_req,1:h1_req_sended,20915:response_begin,0:h1_get_head,0:get_response,49736:h1_finish[SP:474848],:0

Sep 19 09:44:22.818 - [DEBUG] recheck_ip:2a00:1450:400e:20::9 restore ok

Sep 19 09:44:32.459 - [DEBUG] recheck_ip:2001:12e0:804:5::d restore ok

Sep 19 09:44:38.689 - [DEBUG] recheck_ip:2001:ee0:3200:6::12 restore ok

Sep 19 09:44:44.885 - [DEBUG] recheck_ip:2800:3f0:4001:12::14 restore ok

Sep 19 09:44:50.580 - [DEBUG] recheck_ip:2607:f8b0:4006:36::a restore ok

Sep 19 09:44:56.536 - [DEBUG] recheck_ip:2804:7f2:1000:cade::e restore ok

Sep 19 09:45:02.441 - [DEBUG] recheck_ip:2800:3f0:4003:b::a restore ok

Sep 19 09:45:12.446 - [DEBUG] recheck_ip:2001:ee0:3203:7::12 restore ok

Sep 19 09:45:18.793 - [DEBUG] recheck_ip:2405:4800:100:17::12 restore ok

Sep 19 09:45:25.135 - [DEBUG] recheck_ip:2800:2d20:200b:c::12 restore ok

Sep 19 09:45:37.454 - [DEBUG] recheck_ip:2800:e0:c73::12 restore ok

Sep 19 09:45:47.943 - [DEBUG] recheck_ip:2800:e0:c60::11 restore ok

Sep 19 09:45:54.223 - [DEBUG] recheck_ip:2400:d800:3:482::10 restore ok

Sep 19 09:45:59.653 - [DEBUG] recheck_ip:2001:4958:300:501::11 restore ok

Sep 19 09:46:05.685 - [DEBUG] recheck_ip:2001:8002:e51:ef02::12 restore ok

* 如果问题得到解决，请务必回复相关情况，谢谢。

谢谢！

**Comment by SeaHOH** [comment]
超过 32MB 的文件没法一次性下载，git 又不能分段，所以对大多数仓库而言，XX-Net 不适合作为代理。

**Comment by lancewoo** [comment]
"超过 32MB 的文件没法一次性下载" 
这是GAE的限制还是XXNet的限制？

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/45738482-2080f680-bc23-11e8-837a-bc4d02fd5cf7.png)
楼主是说这个，几秒的事😂
又见某开关的特征值：recheck_ip #11291

**Comment by lancewoo** [comment]
说的是git clone的时候走GAE代理，不是浏览器。

**Comment by lancewoo** [comment]
好吧，那就关闭这个问题了。
感谢释疑！ @SeaHOH
