### ISSUE TITLE
twitch被墙了，自动切换模式打不开

### ISSUE THREAD

**Issue by lparty** [XX-net/XX-Net#11485]
只能手动换模式打开，而且直播聊天间的聊天信息显示不了，希望能解决下，谢谢啦

**Comment by SeaHOH** [comment]
https://github.com/gfwlist/gfwlist 反馈请左转

**Comment by pig-let** [comment]
据说是上次直播一个什么游戏比赛，然后有个被淘汰的选手直接开枪射杀了几个人，所以就……
