### ISSUE TITLE
无法远程打开远程控制台

### ISSUE THREAD

**Issue by ahhh111222** [XX-net/XX-Net#11488]
路由器下局域网无法在别的机器，手机，打开控制台ip:/8085。远程已经打开。控制台状态Web 控制页	@127.0.0.1:8085

Sep 21 12:39:20.116 [launcher][DEBUG] start confirm_xxnet_exit
Sep 21 12:39:20.117 [launcher][DEBUG] good, xxnet:8085 clear!
Sep 21 12:39:20.117 [launcher][DEBUG] finished confirm_xxnet_exit
Sep 21 12:39:20.192 [gae_proxy][INFO] ------------------------------------------------------
Sep 21 12:39:20.192 [gae_proxy][INFO] Python Version     : 2.7.8
Sep 21 12:39:20.192 [gae_proxy][INFO] OS                 : Dist:debian; Version:squeeze/sid; ID:
Sep 21 12:39:20.192 [gae_proxy][INFO] Listen Address     : 0.0.0.0:8087
Sep 21 12:39:20.192 [gae_proxy][INFO] GAE APPID          : xxx
Sep 21 12:39:20.193 [gae_proxy][INFO] ------------------------------------------------------

Sep 21 12:39:20.325 [gae_proxy][INFO] SSL use version:TLSv1
Sep 21 12:39:20.326 [gae_proxy][INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.

Sep 21 12:39:20.339 [gae_proxy][INFO] SSL use version:TLSv1
Sep 21 12:39:20.341 [gae_proxy][INFO] server 0.0.0.0:8087 started.
Sep 21 12:39:20.364 [gae_proxy][DEBUG] network IPv4 is ok, cost:244 ms

Sep 21 12:39:20.425 [x_tunnel][INFO] X-Tunnel window:16777216
Sep 21 12:39:20.425 [x_tunnel][INFO] xxnet_version:3.12.2
Sep 21 12:39:20.426 [x_tunnel][INFO] server 127.0.0.1:1080 started.
Sep 21 12:39:20.426 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
Sep 21 12:39:20.525 [launcher][INFO] module x_tunnel started
Sep 21 12:39:20.525 [launcher][INFO] start x_tunnel time cost:132 ms

Sep 21 12:39:20.546 [smart_router][DEBUG] use local DNS server:192.168.1.200
Sep 21 12:39:20.546 [smart_router][INFO] server 127.0.0.1:8086 started.
Sep 21 12:39:20.546 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
Sep 21 12:39:20.546 [smart_router][WARNING] bind DNS 127.0.0.1:53 fail
Sep 21 12:39:20.546 [smart_router][INFO] start DNS server at 127.0.0.1:8053
Sep 21 12:39:20.643 [launcher][INFO] module smart_router started
Sep 21 12:39:20.643 [launcher][INFO] start smart_router time cost:117 ms
Sep 21 12:39:20.643 [launcher][INFO] allow remote access WebUI
Sep 21 12:39:20.643 [launcher][INFO] begin to start web control
Sep 21 12:39:20.643 [launcher][INFO] server 0.0.0.0:8085 started.
Sep 21 12:39:20.644 [launcher][INFO] launcher web control started.
Sep 21 12:39:21.808 [gae_proxy][DEBUG] network IPv6 is ok, cost:1653 ms

**Comment by ahhh111222** [comment]
好像ip:8085/控制台状态显示应该是Web 控制页 @0.0.0.1:8085，而我的Web 控制页 @127.0.0.1:8085。是这里的问题吗。

**Comment by AnyWAT** [comment]
少了某参数 
http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页 ON

**Comment by SeaHOH** [comment]
状态页显示监听地址 IP 是固定的`127.0.0.1`，不能作为参考。
从以下几方面检查：
1. 日志中查看监听地址。你这个是正确地。
1. 检查系统防火墙。
1. 检查路由器是否开启了`AP 隔离`功能。
1. 手机代理是否设置正确，你可以取消代理设置看能否连上。

**Comment by ahhh111222** [comment]
config.json 少了某参数 "listen_ip": "0.0.0.0" ？有加
http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页 ON 即可，已经设置
日志中查看监听地址。你这个是正确地。
检查系统防火墙。系统是ubuntu,无防火墙吧
检查路由器是否开启了AP 隔离功能。没有开
手机代理是否设置正确，你可以取消代理设置看能否连上。手机没设代理IP：8086/proxy.pac,连不上，设了也连不上。
我的系统是这样的，之前路由器因为IPv6打不开，后来桥接，就是光猫出来接lan,电脑接lan,电脑拨号ipv6成功打开。但是我其他的设备没法上网了，手机，ipad。
手头有一个闲置路由器，又接上，这次是路由，所有设备设静态地址上网。光猫出来桥接路由1，路由1接路由2wan,路由2提供wifi供设备上网，这次成功识别ipv6.是否第2个路由直接接光猫能否ipv6,我也没试

**Comment by SeaHOH** [comment]
。。。
为什么总是要问才说出来？

桥接后，如果路由器支持，就可以拨号 IPv6（其实ISP 配的光猫应该都支持，没见过不支持的）。
如果你弄不来，只会用 PC 拨号的话，可以考虑使用 Windows 的连接共享功能，需要再添一张网卡单独连其它路由器。具体连接和设置请谷歌。

**Comment by SeaHOH** [comment]
再给你个安全建议，PC 拨号时，一定要配置好防火墙，不然就等于开门迎客。

**Comment by ahhh111222** [comment]
你的意思是路由1lan接路由2wan,路由2拨号，路由2给电脑wifi(有无线网卡）。然后电脑再接路由1lan吗 ,配置我可以搞。
config.json
 "listen_ip": "0.0.0.0",
  "listen_port": 8087

对吗。用加“listen_port":8087吗

**Comment by ahhh111222** [comment]
非常感谢，我对ubuntu不怎么熟悉，拨号时，怎么配置防火墙。路由器里到是有防火墙，我都关了。本页对各个基本安全功能的开启与关闭进行设置。
状态检测防火墙（SPI）
  SPI 防火墙： 	启用   不启用
虚拟专用网络（VPN）
  PPTP 穿透： 	启用   不启用
  L2TP 穿透： 	启用   不启用
  IPSec 穿透： 	启用   不启用
应用层网关（ALG）
  FTP ALG： 	启用   不启用
  TFTP ALG： 	启用   不启用
  H323 ALG： 	启用   不启用
  RTSP ALG： 	启用   不启用

**Comment by ahhh111222** [comment]
把路由1 去掉
只用路由2，路由拨号，可以成功识别ipv6.
[](url)
![xx-net](https://user-images.githubusercontent.com/32612102/45877910-e2a0e100-bd8e-11e8-9a4f-540762f73119.png)

但是手机还是访问不了电脑IP：8085/

**Comment by SeaHOH** [comment]
正在写回复，结果你终于用路由拨号了。不过你似乎没有同时拨 IPv4？

路由的安全设置不要随便关闭，除非你理解这么做的意义。
桥接时，PC 拨号，路由器安全设置就没用了，必须在 PC 上运行防火墙。Linux 自带 iptales。

**Comment by ahhh111222** [comment]
之前也是用路由拨号，只是最初，路油1拨号时给大家上网，电脑XXnet，ipv6状态一直失败。后来桥接路由用电脑拨号ipv6就ok了。但是电脑拨号，我的其他设备无法上网。
之后，加了个路由器2，用路由2拨号，电脑xxnet，ipv6 ok。都能上网了，电脑用xxnet,手机用墙内。但是手机无法连接电脑ip:8085,想让电脑代理无法搞。
然后，今天把路由1去掉了，正常上网，路由1有没有都一样。路由2和猫是正常连接的，不桥接。
ubuntu的iptales，我回头google学吧

**Comment by ahhh111222** [comment]
不过你似乎没有同时拨 IPv4？这个真的不懂。只是用路由拨号，然后电脑连 wifi，xxnet,然后ok，你终于可以上网了。路由拨号 后，怎么ipv4,ipv6的不知道，ipv6ok了。好像之前有路由1的时候ipv4正常的。怎么去掉了，就没了
路由的安全设置不要随便关闭，也觉的不是这里的问题，但是我真的不懂，所以关了实验。
![xx-net](https://user-images.githubusercontent.com/32612102/45879365-bcca0b00-bd93-11e8-87d6-307bc5658c97.png)

**Comment by ahhh111222** [comment]
日志


Sep 21 19:47:52.019 - [INFO] ------------------------------------------------------

Sep 21 19:47:52.019 - [INFO] Python Version : 2.7.8

Sep 21 19:47:52.020 - [INFO] OS : Dist:debian; Version:squeeze/sid; ID:

Sep 21 19:47:52.020 - [INFO] Listen Address : 0.0.0.0:8087

Sep 21 19:47:52.020 - [INFO] GAE APPID : 省
Sep 21 19:47:52.020 - [INFO] ------------------------------------------------------

Sep 21 19:47:52.042 - [DEBUG] Importing CA

Sep 21 19:47:52.090 - [INFO] Database $HOME/.pki/nssdb cert exist

Sep 21 19:47:52.090 - [DEBUG] Begin importing CA to Firefox

Sep 21 19:47:52.091 - [INFO] Removing old cert to Firefox in /home/x/.mozilla/firefox/9hdpa2om.default

Sep 21 19:47:52.111 - [DEBUG] network IPv4 is ok, cost:178 ms

Sep 21 19:47:52.148 - [INFO] Add new cert to Firefox in /home/x/.mozilla/firefox/9hdpa2om.default

Sep 21 19:47:52.156 - [INFO] SSL use version:TLSv1

Sep 21 19:47:52.156 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.

Sep 21 19:47:52.156 - [INFO] load ip range file:/home/x/dos/XX-Net-3.12.2/code/default/gae_proxy/local/ip_range.txt

Sep 21 19:47:52.163 - [INFO] load ip_list num:500, target num:500

Sep 21 19:47:52.167 - [INFO] SSL use version:TLSv1

Sep 21 19:47:52.168 - [INFO] server 0.0.0.0:8087 started.

Sep 21 19:47:52.539 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:53.039 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:53.071 - [DEBUG] create_ssl update ip:2001:b032:5d01::10 time:902 h2:0 sni:%%%.appspot.com, host:%%%.appspot.com

Sep 21 19:47:53.081 - [DEBUG] create_ssl update ip:2001:b032:5d00::f time:912 h2:0 sni:weekresearch.net, host:

Sep 21 19:47:53.115 - [DEBUG] network IPv6 is ok, cost:1157 ms

Sep 21 19:47:53.543 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:54.047 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:54.552 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:55.056 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:56.876 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:57.380 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:57.884 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:58.386 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:58.891 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:59.395 - [DEBUG] Browse localhost by proxy

Sep 21 19:47:59.899 - [DEBUG] Browse localhost by proxy

**Comment by SeaHOH** [comment]
你先前那张图 IPv4 是 fail，现在的日志又 ok 了。

话说你搞得太乱了，用不着两个路由，除非单个功能不合适，两个刚好互补。
你用路由拨号，光猫设置肯定是桥接，不然拨不了。

安全设置的建议就是针对安全的，和 XX-Net 无关，没人喜欢裸奔吧。

**Comment by ahhh111222** [comment]
新思路，电脑有2个网卡，一个无线，一个机载。用的无线，禁了另个也无用。
ipv4和ipv6共存，是否导致混乱
以前ipv4的时候路由拨号，局域网好好的，手机访问没问题。后来ipv6就不行了，是否这俩个ipv4,ipv6需要协调。
楼上ipv4是随机的，有时是fail, 有时是ok,好像开机等一会就ok了

**Comment by SeaHOH** [comment]
路由拨号就好，不要乱搞。
看手机和 PC 的 IP 是否在同一网段，怀疑你开了两个 IP 配置服务，猫和路由各一个，有冲突。

**Comment by SeaHOH** [comment]
你这个情况没有普遍性，先关掉。
如果还有相关问题，可以直接回复。
