### ISSUE TITLE
密码呀密码

### ISSUE THREAD

**Issue by zhenquanwang** [XX-net/XX-Net#11491]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是
* 是否以相关关键词搜索过类似 issues？

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
否
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by zhenquanwang** [comment]
密码忘记了，发邮件到XXnet，半个月无响应，好不容易试回了密码，结果那边给把密码重置了，又上不了了。给我发了封邮件，但是是空的，现在又上不了了，真郁闷，又要等半个月。。。。

**Comment by AnyWAT** [comment]
😜一般 x_tunnel\client.json 不是保存了，每次还要输入？

**Comment by SeaHOH** [comment]
估计现在是隔段时间处理一次，所以只能等了。

**Comment by mmwchannel** [comment]
是发邮件给dev还是XX-NET啊？我发邮件给XX-NET提示我没有这个用户

**Comment by SeaHOH** [comment]
xxnet.dev@gmail.com

**Comment by zhenquanwang** [comment]
都快2个月了，也没人给处理。我可是买了一年的流量啊，真晕。。。。
