### ISSUE TITLE
大神来帮帮忙啊 ，多谢了！ 

### ISSUE THREAD

**Issue by qidanei624** [XX-net/XX-Net#11499]
【win7 64位 chrome浏览器：】
我用XX-Net，网关那里选上ipv6 ，填了opendns，   可以上google、youtube。
但是，导致解析国内网站很慢！ 贴吧之类的很慢很慢！
网关ipv6 dns设置为自动获取，就没事，只要填上  opendns、谷歌dns ，国内解析就很慢！

有什么解决方案吗？       我是小小白，希望大家详细指点下 =。=

**Comment by AnyWAT** [comment]
浏览器代理扩展选用"GAE自动切换"或“Smart-Router”，右键系统托盘XX-Net 图标，选用“取消全局代理”？
如没有使用代理扩展，后者选用最下面2个全局代理

**Comment by qidanei624** [comment]
@AnyWAT  我一直在用 【GAE自动切换】【 取消全局代理】模式

**Comment by AnyWAT** [comment]
【GAE自动切换】国内网站添加到切换规则：走直接连接

**Comment by qidanei624** [comment]
@AnyWAT 经测试和这个没关系啊，我把代理扩展禁用了也是很慢 =。=

**Comment by qidanei624** [comment]
@AnyWAT 反复测试了好多次，感觉跟扩展没关系，什么模式都用过，也禁用过扩展，还是很慢！

**Comment by qidanei624** [comment]
@AnyWAT  只有网关ipv6 dns设置为自动获取，或者取消 ipv6，才能解决问题！ =。=

**Comment by AnyWAT** [comment]
原生 ipv6 ？

**Comment by qidanei624** [comment]
@AnyWAT  另外 网关ipv6 dns设置为自动获取 + xxnet  也能上youtube， 这样是否安全？大家都说污染之类的，不是很清楚=。=

**Comment by qidanei624** [comment]
@AnyWAT   xxnet不是要选上 ipv6吗？

**Comment by AnyWAT** [comment]
貌似有人建议禁止（不选）

**Comment by AnyWAT** [comment]
或许有原生 IPv6才需要，没有就不需要

**Comment by qidanei624** [comment]
@AnyWAT 最后麻烦一下， 请问下怎么才能知道自己的是不是 原生 IPv6 ？

另外设置里 xxnet -> 高级 -> 【切换到原生 ipv6】这个选项是灰色的，点不了

**Comment by AnyWAT** [comment]
本人没有使用 IPv6
这个选项是灰色的，点不了——如果没有禁用 ipv6 协议，是否可认为没有原生 ipv6 ？

**Comment by AnyWAT** [comment]
我一直在用 【GAE自动切换】【 取消全局代理】模式——国内网站很慢，貌似只有发生在需要添加到走“直接连接”而未添加，走了代理？

**Comment by qidanei624** [comment]
@AnyWAT 真的非常感谢，根据上面的解答内容，我在去总结测试一下！
再次非常感谢解答！

**Comment by AnyWAT** [comment]
【取消全局代理】在系统自带的浏览器内打开国内网站如不慢，在 chrome浏览器却慢，怀疑走了代理
