### ISSUE TITLE
google文档上传图片失败，可能是http put请求的问题

### ISSUE THREAD

**Issue by lishuai0214** [XX-net/XX-Net#11493]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
google文档中上传图片很容易失败，查看http请求后发现有一个put上传图片的请求经常失败，gae代理是不是不支持put请求。

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
GAE Fetch支持`PUT`，不支持`OPTIONS`，但 XX-Net 在本地伪造了`OPTIONS`回应。
注意是否和 IP 或 隧道质量有关，如果无关，请提供更详细的日志。

**Comment by SeaHOH** [comment]
我自己上传文档没遇到过失败。
关闭后仍可回复

**Comment by lishuai0214** [comment]
`Sep 27 21:46:43.991 - [WARNING] gae_exception:'600:fetch gae fail' https://0.docs.google.com/document/d/1qZ28Ndi6DJnjbEU56b3gaV844U7upz0N7lAJZ5lwuyk/bind?id=1qZ28Ndi6DJnjbEU56b3gaV844U7upz0N7lAJZ5lwuyk&sid=5df5d151b640ffe9&token=AC4w5VhCIwN3qNhgoyYIzZQt4hUGUx19Kg%3A1537971405507&ouid=109633417499795875633&includes_info_params=true&VER=8&lsq=1538055897314&u=17381378668477615499&vc=1&c=1&w=1&gsi=0&ssfi=84585&smv=4&cimpl=1&RID=rpc&SID=E77EC7C01EB78D64&CI=1&AID=6&TYPE=xmlhttp&zx=giy4hs3ak8yv&t=2`
报了很多这样的日志，也不知道是不是有关系，google文档一直显示在保存，最终就失败了

**Comment by SeaHOH** [comment]
上面这个请求确实是走 GAE，但是其它呢？
试一下下面这个设置
https://github.com/XX-net/XX-Net/issues/11438#issuecomment-419658090
