### ISSUE TITLE
IPv6 状态问题，

### ISSUE THREAD

**Issue by alexchan1016** [XX-net/XX-Net#11496]
属性 | 值
-- | --
Teredo 隧道 | 合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.11.19:62623
外部 NAT 映射    : 49.77.102.86:30103

IPV6就是连接不上。

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | Fail (尝试修复)
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 0
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 100

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by alexchan1016** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by alexchan1016** [comment]
切换到ipv6 优先


IPv4 域名连接测试 |   | 成功 (0.345s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 失败 (0.024s)
双栈域名连接测试 |   | 成功 (0.311s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.318s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (0.496s) 使用 ipv4
无域名 IPv6 连接测试 |   | 超时 (15.018s)
IPv6 大数据包传输测试 |   | 失败 (0.047s)
测试运营商 DNS 是否接入 IPv6 |   | 成功 (0.319s) 使用 ipv4
查询 IPv4 运营商 |   | 成功 (0.394s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 失败 (0.056s)

**Comment by SeaHOH** [comment]
换一个服务器试试，使用 wiki 里面提供工具的链接，因为 XX-Net 提供的切换总是选择最快的那个。

**Comment by alexchan1016** [comment]
一样，都是gae连不上，幸亏一早买了x-tunnel

**Comment by AnyWAT** [comment]
使用的代理扩展情景模式或全局代理？

**Comment by alexchan1016** [comment]
我最近下了个手机版，gae登录无问题，看来不是家里或者办公室网络的问题。

**Comment by SeaHOH** [comment]
Teredo 实现不同，系统不同。
你以前有正常使用过吗？话说 Win10 总是出些不明不白的问题。

**Comment by AnyWAT** [comment]
都是gae连不上，幸亏一早买了x-tunnel ——作为5个 x-tunnel 前端之一的 gae 不正常，而其它4个一般只有 Cloudflare 极其偶尔地正常。。。
use-ipv6: auto 改成 IPv6 与 切换到ipv6 优先 不同，后者不会是 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel 中的“切换到原生 ipv6 优先”？如是，则又一原生由无到有后XX-Net 不正常的。。。
gws-ip-num: total:0 ipv4:0 ipv6:0 某开关打开后很常见的归零而已，但 scan-ip-thread-num: 100 貌似没打开？
