### ISSUE TITLE
MAC 10.7.4  TypeError: update() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by janshebi** [XX-net/XX-Net#115]
版本：1.7.1 ，本人完全新手，麻烦大神手把手解答一下。谢谢。

**Comment by janshebi** [comment]
Last login: Mon Apr  6 21:20:54 on ttys000
kuruwamatoMacBook:~ Luck$ /Users/Luck/Downloads/XX-Net-1.7.1/start.command ; exit;
launcher version: 1.2.0
Traceback (most recent call last):
  File "launcher/start.py", line 61, in <module>
    main()
  File "launcher/start.py", line 56, in main
    from start import main as launcher_main
  File "/Users/Luck/Downloads/XX-Net-1.7.1/launcher/1.2.0/start.py", line 25, in <module>
    from mac_tray import sys_tray
  File "/Users/Luck/Downloads/XX-Net-1.7.1/launcher/1.2.0/mac_tray.py", line 89, in <module>
    sys_tray = Mac_tray()
  File "/Users/Luck/Downloads/XX-Net-1.7.1/launcher/1.2.0/mac_tray.py", line 26, in __init__
    super(Mac_tray, self).__init__("XX-Net", title="XX-Net", icon=icon_path, quit_button=None)
  File "/Users/Luck/Downloads/XX-Net-1.7.1/python27/1.0/lib/darwin/rumps/rumps.py", line 920, in __init__
    self._menu = Menu()
  File "/Users/Luck/Downloads/XX-Net-1.7.1/python27/1.0/lib/darwin/rumps/rumps.py", line 277, in __init__
    super(Menu, self).__init__()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 74, in __init__
TypeError: update() takes exactly 2 arguments (1 given)
logout

**Comment by xxnet** [comment]
请给出详细的日志，估计是个bug

2015-04-06 9:25 GMT-04:00 janshebi <notifications@github.com>:

**Comment by xxnet** [comment]
好吧，Mac 10.7的兼容问题。
你先用1.3.5的版本吧，后面再想办法。



2015-04-06 9:27 GMT-04:00 janshebi <notifications@github.com>:

**Comment by xxnet** [comment]
1.8.1 发布
重构了Mac下的托盘实现，取消了rumps的以来。

请测试

**Comment by janshebi** [comment]
1.8.4测试成功，但是只能打开google. 即便配置ID, 也会自动跳到没有配置ID。打不开facebook, youtube 提示没有配置ID.

Mac 版本 10.7.4

Apr 12 11:15:01 - [DEBUG] launcher web_control 127.0.0.1:52861 "GET / 
Apr 12 11:15:03 - [DEBUG] get ip:203.165.13.222 t:145
Apr 12 11:15:03 - [DEBUG] get ip:210.158.146.245 t:179
Apr 12 11:15:03 - [DEBUG] create_ssl update ip:210.158.146.245 time:193
Apr 12 11:15:03 - [DEBUG] get ip:210.61.221.152 t:323
Apr 12 11:15:03 - [DEBUG] get ip:213.158.11.53 t:418
Apr 12 11:15:04 - [DEBUG] get ip:213.158.11.251 t:444
Apr 12 11:15:04 - [DEBUG] create_ssl 203.165.13.222 fail:timed out c:0 h:0
Apr 12 11:15:04 - [DEBUG] get ip:210.61.221.148 t:528
Apr 12 11:15:04 - [DEBUG] create_ssl update ip:213.158.11.53 time:423
Apr 12 11:15:04 - [DEBUG] get ip:199.87.241.48 t:550
Apr 12 11:15:04 - [DEBUG] network is ok
Apr 12 11:15:05 - [DEBUG] create_ssl 210.61.221.152 fail:timed out c:0 h:0
Apr 12 11:15:05 - [DEBUG] network is ok
Apr 12 11:15:05 - [DEBUG] create_ssl update ip:199.87.241.48 time:502
Apr 12 11:15:05 - [DEBUG] get ip:121.78.74.110 t:551
Apr 12 11:15:05 - [DEBUG] get ip:194.78.99.224 t:569
Apr 12 11:15:05 - [DEBUG] create_ssl update ip:213.158.11.251 time:1501
Apr 12 11:15:05 - [DEBUG] create_ssl 213.158.11.251 fail: certficate is none c:209 h:1501
Apr 12 11:15:06 - [DEBUG] network is ok
Apr 12 11:15:06 - [DEBUG] create_ssl 210.61.221.148 fail:timed out c:0 h:0
Apr 12 11:15:06 - [DEBUG] network is ok
Apr 12 11:15:06 - [DEBUG] get ip:208.117.224.30 t:624
Apr 12 11:15:06 - [DEBUG] get ip:173.194.202.31 t:644
Apr 12 11:15:06 - [DEBUG] create_ssl update ip:194.78.99.224 time:533
Apr 12 11:15:07 - [DEBUG] create_ssl update ip:208.117.224.30 time:483
Apr 12 11:15:07 - [DEBUG] get ip:194.78.99.38 t:654
Apr 12 11:15:07 - [DEBUG] create_ssl update ip:173.194.202.31 time:518
Apr 12 11:15:07 - [DEBUG] get ip:194.78.99.46 t:658
Apr 12 11:15:07 - [DEBUG] create_ssl update ip:121.78.74.110 time:1501
Apr 12 11:15:07 - [DEBUG] create_ssl 121.78.74.110 fail: certficate is none c:348 h:1501
Apr 12 11:15:07 - [DEBUG] get ip:173.194.192.165 t:697
Apr 12 11:15:07 - [DEBUG] network is ok
Apr 12 11:15:07 - [DEBUG] create_ssl update ip:194.78.99.38 time:522
Apr 12 11:15:07 - [DEBUG] create_ssl update ip:194.78.99.46 time:532
Apr 12 11:15:08 - [DEBUG] get ip:64.15.119.211 t:789
Apr 12 11:15:08 - [DEBUG] get ip:41.206.96.93 t:866
Apr 12 11:15:08 - [DEBUG] create_ssl update ip:173.194.192.165 time:676
Apr 12 11:15:08 - [DEBUG] get ip:114.4.41.251 t:867
Apr 12 11:15:08 - [DEBUG] get ip:64.15.112.152 t:867
Apr 12 11:15:08 - [DEBUG] get ip:210.139.253.216 t:867
Apr 12 11:15:09 - [DEBUG] create_ssl update ip:64.15.119.211 time:699
Apr 12 11:15:09 - [DEBUG] get ip:64.15.116.216 t:867
Apr 12 11:15:09 - [DEBUG] create_ssl 41.206.96.93 fail:timed out c:0 h:0
Apr 12 11:15:09 - [DEBUG] network is ok
Apr 12 11:15:09 - [DEBUG] create_ssl 114.4.41.251 fail:timed out c:0 h:0
Apr 12 11:15:10 - [DEBUG] network is ok
Apr 12 11:15:10 - [DEBUG] get ip:64.15.124.122 t:868
Apr 12 11:15:10 - [DEBUG] create_ssl 64.15.112.152 fail:timed out c:0 h:0
Apr 12 11:15:10 - [DEBUG] network is ok
Apr 12 11:15:10 - [DEBUG] create_ssl 210.139.253.216 fail:timed out c:0 h:0
Apr 12 11:15:10 - [DEBUG] network is ok
Apr 12 11:15:10 - [DEBUG] get ip:74.125.136.137 t:869
Apr 12 11:15:10 - [DEBUG] create_ssl 64.15.116.216 fail:timed out c:0 h:0
Apr 12 11:15:11 - [DEBUG] network is ok
Apr 12 11:15:11 - [DEBUG] get ip:173.194.121.103 t:869
Apr 12 11:15:11 - [DEBUG] sort ip time:11
Apr 12 11:15:11 - [DEBUG] get ip:123.205.250.144 t:870
Apr 12 11:15:11 - [DEBUG] get ip:85.182.250.104 t:870
Apr 12 11:15:11 - [DEBUG] create_ssl 64.15.124.122 fail:timed out c:0 h:0
Apr 12 11:15:11 - [DEBUG] network is ok
Apr 12 11:15:12 - [DEBUG] get ip:213.240.44.24 t:870
Apr 12 11:15:12 - [DEBUG] create_ssl 74.125.136.137 fail:timed out c:0 h:0
Apr 12 11:15:12 - [DEBUG] network is ok
Apr 12 11:15:12 - [DEBUG] create_ssl 173.194.121.103 fail:timed out c:0 h:0
Apr 12 11:15:12 - [DEBUG] network is ok
Apr 12 11:15:12 - [DEBUG] get ip:216.58.209.77 t:869
Apr 12 11:15:12 - [DEBUG] create_ssl 123.205.250.144 fail:timed out c:0 h:0
Apr 12 11:15:12 - [DEBUG] network is ok
Apr 12 11:15:13 - [DEBUG] create_ssl 85.182.250.104 fail:timed out c:0 h:0
Apr 12 11:15:13 - [DEBUG] network is ok
Apr 12 11:15:13 - [DEBUG] get ip:216.58.211.19 t:869
Apr 12 11:15:13 - [DEBUG] create_ssl 213.240.44.24 fail:timed out c:0 h:0
Apr 12 11:15:13 - [DEBUG] network is ok
Apr 12 11:15:13 - [DEBUG] get ip:123.205.251.116 t:870
Apr 12 11:15:13 - [INFO] FWD CONNECT www.google.com:443 
Apr 12 11:15:13 - [DEBUG] get ip:216.58.219.67 t:870
Apr 12 11:15:13 - [INFO] FWD CONNECT www.google.com:443 
Apr 12 11:15:13 - [DEBUG] get ip:84.235.77.44 t:870
Apr 12 11:15:13 - [DEBUG] get ip:64.15.114.88 t:870
Apr 12 11:15:14 - [DEBUG] get ip:210.245.14.30 t:870
Apr 12 11:15:14 - [DEBUG] get ip:216.58.210.132 t:870
Apr 12 11:15:14 - [DEBUG] create_ssl 216.58.209.77 fail:timed out c:0 h:0
Apr 12 11:15:14 - [DEBUG] network is ok
Apr 12 11:15:14 - [DEBUG] get ip:111.168.255.44 t:871
Apr 12 11:15:14 - [DEBUG] get ip:216.58.216.177 t:871
Apr 12 11:15:14 - [DEBUG] get ip:64.233.191.145 t:871
Apr 12 11:15:14 - [DEBUG] get ip:210.245.14.148 t:871
Apr 12 11:15:14 - [DEBUG] get ip:208.117.224.133 t:871
Apr 12 11:15:14 - [DEBUG] tcp conn 216.58.219.67 fail t:1000
Apr 12 11:15:14 - [DEBUG] get ip:202.169.193.79 t:871
Apr 12 11:15:14 - [DEBUG] network is ok
Apr 12 11:15:14 - [DEBUG] create_ssl 216.58.211.19 fail:timed out c:0 h:0
Apr 12 11:15:14 - [DEBUG] tcp conn 84.235.77.44 fail t:1001
Apr 12 11:15:14 - [DEBUG] network is fail
Apr 12 11:15:14 - [DEBUG] report_connect_fail network fail
Apr 12 11:15:15 - [DEBUG] network is ok
Apr 12 11:15:15 - [DEBUG] get ip:216.58.216.219 t:871
Apr 12 11:15:15 - [DEBUG] ssl_pool.get:210.158.146.245 handshake:193
Apr 12 11:15:15 - [DEBUG] ssl conn_num:9
Apr 12 11:15:15 - [DEBUG] create_ssl 123.205.251.116 fail:timed out c:0 h:0
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] tcp conn 216.58.210.132 fail t:1001
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] get ip:216.58.208.207 t:871
Apr 12 11:15:15 - [DEBUG] get ip:208.117.224.243 t:871
Apr 12 11:15:15 - [DEBUG] tcp conn 111.168.255.44 fail t:1000
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] get ip:173.194.121.60 t:871
Apr 12 11:15:15 - [DEBUG] tcp conn 216.58.216.177 fail t:1001
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] fetch gae status:404 url:http://www.facebook.com/
Apr 12 11:15:15 - [WARNING] APPID 'hillarylu123' not exists, remove it.
Apr 12 11:15:15 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 12 11:15:15 - [DEBUG] create_ssl 64.15.114.88 fail:timed out c:0 h:0
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] get ip:216.58.221.223 t:871
Apr 12 11:15:15 - [DEBUG] create_ssl 210.245.14.30 fail:timed out c:0 h:0
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] tcp conn 64.233.191.145 fail t:1005
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] get ip:203.66.124.221 t:872
Apr 12 11:15:15 - [DEBUG] tcp conn 208.117.224.133 fail t:1000
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] ssl_pool.get:213.158.11.53 handshake:423
Apr 12 11:15:15 - [DEBUG] ssl conn_num:8
Apr 12 11:15:15 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 12 11:15:15 - [WARNING] gae_exception: 'http://www.facebook.com/favicon.ico'
Apr 12 11:15:15 - [DEBUG] ssl_pool.get:208.117.224.30 handshake:483
Apr 12 11:15:15 - [DEBUG] ssl conn_num:7
Apr 12 11:15:15 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 12 11:15:15 - [WARNING] gae_exception: 'http://www.facebook.com/favicon.ico'
Apr 12 11:15:15 - [DEBUG] ssl_pool.get:199.87.241.48 handshake:502
Apr 12 11:15:15 - [DEBUG] ssl conn_num:6
Apr 12 11:15:15 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 12 11:15:15 - [WARNING] gae_exception: 'http://www.facebook.com/favicon.ico'
Apr 12 11:15:15 - [WARNING] GAE 502 GET http://www.facebook.com/favicon.ico
Apr 12 11:15:15 - [DEBUG] get ip:210.158.146.245 t:193
Apr 12 11:15:15 - [DEBUG] tcp conn 202.169.193.79 fail t:1001
Apr 12 11:15:15 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:15 - [DEBUG] tcp conn 210.158.146.245 time:84
Apr 12 11:15:16 - [DEBUG] get ip:213.158.11.53 t:423
Apr 12 11:15:16 - [DEBUG] tcp conn 216.58.216.219 fail t:1001
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:16 - [DEBUG] create_ssl 210.245.14.148 fail:timed out c:0 h:0
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:16 - [DEBUG] get ip:199.87.241.48 t:502
Apr 12 11:15:16 - [DEBUG] get ip:194.78.99.224 t:533
Apr 12 11:15:16 - [DEBUG] tcp conn 216.58.208.207 fail t:1001
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:16 - [DEBUG] tcp conn 173.194.121.60 fail t:1001
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:16 - [DEBUG] tcp conn 199.87.241.48 time:242
Apr 12 11:15:16 - [DEBUG] get ip:213.158.11.143 t:872
Apr 12 11:15:16 - [DEBUG] tcp conn 216.58.221.223 fail t:1001
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:16 - [DEBUG] get ip:64.233.160.195 t:872
Apr 12 11:15:16 - [DEBUG] tcp conn 203.66.124.221 fail t:1001
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:16 - [DEBUG] create_ssl update ip:213.158.11.53 time:451
Apr 12 11:15:16 - [DEBUG] create_ssl 208.117.224.243 fail:timed out c:0 h:0
Apr 12 11:15:16 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:17 - [DEBUG] get ip:208.117.224.165 t:872
Apr 12 11:15:17 - [DEBUG] get ip:64.15.113.149 t:872
Apr 12 11:15:17 - [DEBUG] get ip:216.58.216.77 t:872
Apr 12 11:15:17 - [DEBUG] create_ssl update ip:194.78.99.224 time:1501
Apr 12 11:15:17 - [DEBUG] create_ssl 194.78.99.224 fail: certficate is none c:291 h:1501
Apr 12 11:15:17 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:17 - [DEBUG] create_ssl 213.158.11.143 fail:timed out c:0 h:0
Apr 12 11:15:18 - [DEBUG] network is ok
Apr 12 11:15:18 - [DEBUG] create_ssl 64.233.160.195 fail:timed out c:0 h:0
Apr 12 11:15:18 - [DEBUG] network is ok
Apr 12 11:15:18 - [DEBUG] create_ssl 208.117.224.165 fail:timed out c:0 h:0
Apr 12 11:15:18 - [DEBUG] network is ok
Apr 12 11:15:18 - [DEBUG] get ip:208.117.224.30 t:483
Apr 12 11:15:19 - [DEBUG] get ip:173.194.202.31 t:518
Apr 12 11:15:19 - [DEBUG] get ip:194.78.99.38 t:522
Apr 12 11:15:19 - [DEBUG] create_ssl 64.15.113.149 fail:timed out c:0 h:0
Apr 12 11:15:19 - [DEBUG] create_ssl 216.58.216.77 fail:timed out c:0 h:0
Apr 12 11:15:19 - [DEBUG] network is fail
Apr 12 11:15:19 - [DEBUG] report_connect_fail network fail
Apr 12 11:15:19 - [DEBUG] network is ok
Apr 12 11:15:19 - [DEBUG] get ip:194.78.99.46 t:532
Apr 12 11:15:19 - [DEBUG] create_ssl update ip:173.194.202.31 time:551
Apr 12 11:15:19 - [DEBUG] create_ssl update ip:194.78.99.38 time:549
Apr 12 11:15:20 - [DEBUG] get ip:173.194.192.165 t:676
Apr 12 11:15:20 - [DEBUG] get ip:64.15.119.211 t:699
Apr 12 11:15:20 - [DEBUG] create_ssl update ip:208.117.224.30 time:1352
Apr 12 11:15:20 - [DEBUG] get ip:106.162.216.98 t:872
Apr 12 11:15:20 - [DEBUG] get ip:210.245.14.123 t:872
Apr 12 11:15:21 - [DEBUG] create_ssl update ip:64.15.119.211 time:635
Apr 12 11:15:21 - [DEBUG] create_ssl update ip:210.245.14.123 time:322
Apr 12 11:15:21 - [DEBUG] sort ip time:7
Apr 12 11:15:21 - [DEBUG] get ip:216.58.212.102 t:874
Apr 12 11:15:22 - [DEBUG] get ip:1.179.248.25 t:873
Apr 12 11:15:22 - [DEBUG] create_ssl update ip:173.194.192.165 time:1781
Apr 12 11:15:22 - [DEBUG] create_ssl 106.162.216.98 fail:timed out c:0 h:0
Apr 12 11:15:22 - [DEBUG] get ip:216.58.208.7 t:873
Apr 12 11:15:22 - [DEBUG] network is ok
Apr 12 11:15:22 - [DEBUG] create_ssl update ip:194.78.99.46 time:1614
Apr 12 11:15:23 - [DEBUG] create_ssl 216.58.212.102 fail:timed out c:0 h:0
Apr 12 11:15:23 - [DEBUG] network is ok
Apr 12 11:15:23 - [DEBUG] get ip:208.117.228.217 t:873
Apr 12 11:15:23 - [DEBUG] get ip:213.240.44.22 t:873
Apr 12 11:15:23 - [DEBUG] get ip:173.194.118.81 t:873
Apr 12 11:15:23 - [DEBUG] create_ssl 1.179.248.25 fail:timed out c:0 h:0
Apr 12 11:15:23 - [DEBUG] network is ok
Apr 12 11:15:23 - [DEBUG] create_ssl 216.58.208.7 fail:timed out c:0 h:0
Apr 12 11:15:23 - [DEBUG] network is ok
Apr 12 11:15:24 - [DEBUG] get ip:123.205.250.185 t:873
Apr 12 11:15:24 - [DEBUG] create_ssl 208.117.228.217 fail:timed out c:0 h:0
Apr 12 11:15:24 - [DEBUG] network is ok
Apr 12 11:15:24 - [DEBUG] get ip:213.240.44.19 t:873
Apr 12 11:15:24 - [DEBUG] get ip:213.240.44.16 t:873
Apr 12 11:15:25 - [DEBUG] create_ssl 213.240.44.22 fail:timed out c:0 h:0
Apr 12 11:15:25 - [DEBUG] create_ssl 173.194.118.81 fail:timed out c:0 h:0
Apr 12 11:15:25 - [DEBUG] network is fail
Apr 12 11:15:25 - [DEBUG] report_connect_fail network fail
Apr 12 11:15:25 - [DEBUG] network is ok
Apr 12 11:15:25 - [DEBUG] create_ssl update ip:123.205.250.185 time:1278
Apr 12 11:15:25 - [DEBUG] get ip:210.158.146.245 t:169
Apr 12 11:15:26 - [DEBUG] forward local disconnected.
Apr 12 11:15:26 - [DEBUG] FWD CONNECT www.google.com:443 with closed
Apr 12 11:15:26 - [DEBUG] get ip:213.158.11.53 t:451
Apr 12 11:15:26 - [DEBUG] create_ssl update ip:210.158.146.245 time:175
Apr 12 11:15:26 - [DEBUG] get ip:199.87.241.48 t:484
Apr 12 11:15:26 - [DEBUG] create_ssl 213.240.44.19 fail:timed out c:0 h:0
Apr 12 11:15:26 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:26 - [DEBUG] create_ssl 213.240.44.16 fail:timed out c:0 h:0
Apr 12 11:15:26 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:26 - [DEBUG] get ip:194.78.99.224 t:633
Apr 12 11:15:26 - [DEBUG] create_ssl update ip:199.87.241.48 time:502
Apr 12 11:15:27 - [DEBUG] get ip:123.205.251.116 t:870
Apr 12 11:15:27 - [DEBUG] get ip:84.235.77.44 t:870
Apr 12 11:15:27 - [DEBUG] create_ssl update ip:213.158.11.53 time:1170
Apr 12 11:15:27 - [DEBUG] get ip:64.15.114.88 t:870
Apr 12 11:15:27 - [DEBUG] create_ssl update ip:194.78.99.224 time:546
Apr 12 11:15:27 - [DEBUG] get ip:210.245.14.30 t:870
Apr 12 11:15:28 - [DEBUG] get ip:216.58.210.132 t:870
Apr 12 11:15:28 - [DEBUG] get ip:111.168.255.44 t:871
Apr 12 11:15:28 - [DEBUG] create_ssl 123.205.251.116 fail:timed out c:0 h:0
Apr 12 11:15:28 - [DEBUG] network is ok
Apr 12 11:15:28 - [DEBUG] create_ssl 84.235.77.44 fail:timed out c:0 h:0
Apr 12 11:15:28 - [DEBUG] create_ssl 64.15.114.88 fail:timed out c:0 h:0
Apr 12 11:15:28 - [DEBUG] network is fail
Apr 12 11:15:28 - [DEBUG] report_connect_fail network fail
Apr 12 11:15:29 - [DEBUG] network is ok
Apr 12 11:15:29 - [DEBUG] create_ssl 210.245.14.30 fail:timed out c:0 h:0
Apr 12 11:15:29 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:29 - [DEBUG] get ip:194.78.99.38 t:549
Apr 12 11:15:29 - [DEBUG] create_ssl 216.58.210.132 fail:timed out c:0 h:0
Apr 12 11:15:29 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:29 - [DEBUG] get ip:173.194.202.31 t:551
Apr 12 11:15:30 - [DEBUG] create_ssl 111.168.255.44 fail:timed out c:0 h:0
Apr 12 11:15:30 - [DEBUG] report_connect_fail network fail recently
Apr 12 11:15:30 - [DEBUG] get ip:208.117.224.30 t:583
Apr 12 11:15:30 - [DEBUG] get ip:64.15.119.211 t:635
Apr 12 11:15:30 - [DEBUG] create_ssl update ip:194.78.99.38 time:541
Apr 12 11:15:30 - [DEBUG] create_ssl update ip:208.117.224.30 time:427
Apr 12 11:15:31 - [DEBUG] create_ssl update ip:173.194.202.31 time:718
A

**Comment by xxnet** [comment]
1.8.4是在配置上有问题的，1.8.5修复了该问题

从日志看，你设置的appid是无效的，
你的appid是不是没有部署过？



2015-04-11 23:19 GMT-04:00 janshebi <notifications@github.com>:
