### ISSUE TITLE
求助开了XX-net后有道笔记无法联网怎么解决

### ISSUE THREAD

**Issue by ncmon** [XX-net/XX-Net#11500]
开xx-net的时候SwitchyOmega选的是gae自动切换其他软件都能正常使用只有这个有道笔记无法联网请教怎么才能正常使用呢。

**Comment by AnyWAT** [comment]
并非全智能的GAE自动切换需添加不在 gfwlist.txt 内的 *.youdao.com 或走GAE或走直连？
😜或许稍智能的 Smart-Router 更适合你？
