### ISSUE TITLE
三星手机升级最新版之后，就多了一个vpn设置，xx手机版不能用了

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#11506]
就是app不会自动在这个里面进行添加，而ssr就会自动添加，里面有一个始终保持连接选项需要打开，vpn才可以使用。而手动添加并不能关联到app，怎么解决。

![_20180927110235](https://user-images.githubusercontent.com/14964575/46121499-90583800-c246-11e8-974f-cf91868e707f.jpg)
![_20180927110243](https://user-images.githubusercontent.com/14964575/46121501-90f0ce80-c246-11e8-82bc-13e2ab783114.jpg)
![_20180927110341](https://user-images.githubusercontent.com/14964575/46121502-90f0ce80-c246-11e8-9296-86b87ff08c6f.jpg)

就是app不会自动在这个里面进行添加，而ssr就会自动添加，里面有一个始终保持连接选项需要打开，vpn才可以使用。而手动添加并不能关联到app，怎么解决。

**Comment by SeaHOH** [comment]
请向 https://github.com/XndroidDev/Xndroid/issues 反馈
