### ISSUE TITLE
只有200个ipv6  导入6000条   重启后还是只有200条

### ISSUE THREAD

**Issue by xxlwylwy** [XX-net/XX-Net#11509]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

最新版本

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

没有这个

* 是否以相关关键词搜索过类似 issues？

搜不到

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

只有200个ipv6  导入6000条   重启后还是只有200条

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
这个问题挺好搜索 #11253

**Comment by xxlwylwy** [comment]
修改data\gae_proxy\config.json

  "max_good_ip_num": 200,
