### ISSUE TITLE
停用一年之后，今天突然好了，原因不明。

### ISSUE THREAD

**Issue by R3TIR33** [XX-net/XX-Net#11507]
xx-net 停用大约一年了，一直不能用，今天抱着侥幸的心理输入下列语句，竟然一切都正常了，太不可思议了，完全不知道原因。谢谢开发者的工作。

netsh int ipv6 set teredo natawareclient default

**Comment by AnyWAT** [comment]
xx-net 版本？Win10 无疑😂
