### ISSUE TITLE
用了代理还是被自动跳转网页要怎么破？

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#11502]
事情是这样的，我想去https://hyperice.com/hypervolt这个网站海淘，但是即使打开了代理，还是被自动跳回到中国官网，这个应该怎么破。难道我代理是国外的ip也不行吗

**Comment by zzgpku** [comment]
![image](https://user-images.githubusercontent.com/14359560/45941572-60741f00-c011-11e8-9beb-b31114ef8dd3.png)
并没有跳转
