### ISSUE TITLE
【集思广益】使用Docker部署XX-Net遇到技术难题，内无法正常启用IPv6

### ISSUE THREAD

**Issue by CoderIvan** [XX-net/XX-Net#11516]
XX-Net Status:

sys-platform: x86_64, Linux-4.9.93-linuxkit-aufs-x86_64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #1 SMP Wed Jun 6 16:55:56 UTC 2018
os-release: 4.9.93-linuxkit-aufs
os-detail: Dist:Ubuntu; Version:18.04; ID:bionic
architecture: 64bit,
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.15rc1
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

## 问题描述
DockerFile文件在[Repositorie](https://github.com/CoderIvan/My-XX-Net)

部署成功后，一直显示
![image](https://user-images.githubusercontent.com/7960859/46252367-7fa00000-c49a-11e8-9b7b-0d518b783976.png)

![image](https://user-images.githubusercontent.com/7960859/46252482-a7439800-c49b-11e8-9edc-968c42cddf19.png)

怀疑是在容器中IPv6无法正常使用

**Comment by zhmars** [comment]
哪种 ipv6，原生 or 隧道?

**Comment by CoderIvan** [comment]
> 哪种 ipv6，原生 or 隧道?

装了miredo的，应该是你说的隧道

**Comment by zhmars** [comment]
所以 miredo 有检查过吗 ，能不能获取到地址？

**Comment by CoderIvan** [comment]
> 所以 miredo 有检查过吗 ，能不能获取到地址？

找到解决方式，谢谢

**Comment by SeaHOH** [comment]
如果不是本机，建议安装其它工具，兼容性更好，使用也方便。

**Comment by ahhh111222** [comment]
是否装了miredo就跟有没有IPv6没有关系，为什么还会有ipv6失效

**Comment by ChLang0508** [comment]
请问一下你这是怎么解决的，最近遇到同样的问题
