### ISSUE TITLE
一直没有ipv6 的ip数

### ISSUE THREAD

**Issue by hauchenjiang** [XX-net/XX-Net#11512]
帮帮忙呀。谢谢啦！！！

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | OK
IPv4 IP数 | 0
IPv6 IP数 | 0
XX-Net 状态 | 工作
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
IP扫描线程数(设置) | 150
屏蔽状态(帮助) | OK

**Comment by hauchenjiang** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:3795 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
xxnet-version: 3.10.4 ——比3.12.2旧的老版本
没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
https://github.com/XX-net/XX-Net/issues/11010 有 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

**Comment by hauchenjiang** [comment]
> gws-ip-num: total:3795 太大没必要（不像 IPv4时，现在波动大，也许此时有用，彼刻就不行了），1000左右足以
> scan-ip-thread-num: 150 貌似1/3足矣
> xxnet-version: 3.10.4 ——比3.12.2旧的老版本
> 没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）😂对你 Using_Public_Appid: true 不需要此步
> #11010 有 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

哇完美解决！非常感谢！
