### ISSUE TITLE
如何修改每次启动XX-Net SwitchyOmega都默认选的情景模式为smartRouter 想改为GAE-Proxy自动切换

### ISSUE THREAD

**Issue by ZhuoSiChen** [XX-net/XX-Net#11510]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是
* 是否以相关关键词搜索过类似 issues？

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
#11440
