### ISSUE TITLE
win10系统ipv6无法启用，以前可以

### ISSUE THREAD

**Issue by rockrat** [XX-net/XX-Net#11517]
Windows PowerShell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。

PS C:\WINDOWS\system32> // 设置 Teredo 服务器，默认为：win10.ipv6.microsoft.com
// : 无法将“//”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次。
所在位置 行:1 字符: 1
+ // 设置 Teredo 服务器，默认为：win10.ipv6.microsoft.com
+ ~~
    + CategoryInfo          : ObjectNotFound: (//:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>   netsh interface teredo set state enterpriseclient server=default
确定。

PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>   // 测试 IPv6 连接
// : 无法将“//”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次。
所在位置 行:1 字符: 3
+   // 测试 IPv6 连接
+   ~~
    + CategoryInfo          : ObjectNotFound: (//:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>   ping -6 ipv6.test-ipv6.com

正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

2001:470:1:18::4:230 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，
PS C:\WINDOWS\system32>   ping -6 [2001:470:1:18::125]

正在 Ping 2001:470:1:18::125 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

2001:470:1:18::125 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>   // 重置 IPv6 配置
// : 无法将“//”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次。
所在位置 行:1 字符: 3
+   // 重置 IPv6 配置
+   ~~
    + CategoryInfo          : ObjectNotFound: (//:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>   netsh interface ipv6 reset
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>  // 第一种：修改 Teredo 服务器为 teredo.remlab.net
// : 无法将“//”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次。
所在位置 行:1 字符: 2
+  // 第一种：修改 Teredo 服务器为 teredo.remlab.net
+  ~~
    + CategoryInfo          : ObjectNotFound: (//:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>   netsh interface teredo set state server=teredo.remlab.net // 第一种：修改 Teredo 服务器为 tere
do.remlab.net
此命令提供的语法不正确。请查看帮助以获取正确的语法信息。

用法: set state [[type]=disabled|client|enterpriseclient|natawareclient|server|default]
             [[servername=]<hostname>|<IPv4 address>|default]
             [[refreshinterval=]<integer>|default]
             [[clientport=]<integer>|default]
             [[servervirtualip=]<IPv4 address>|default]

参数:

       标记                值
       type              - 为以下值之一:
                           disabled: 禁用 Teredo 服务。
                           client: 启用 Teredo 客户端。
                           enterpriseclient: 跳过受管理的网络检测。
                           natawareclient: 启用 Teredo 客户端并标识 NAT 类型。
                           server: 启用 Teredo 服务器。
                           default: 默认状态为 client。
       servername        - Teredo 服务器的名称或 IPv4 地址。
       refreshinterval   - 客户端刷新间隔(以秒计)。
       clientport        - 客户端 UDP 端口(或者由系统选择)。
       servervirtualip   - 服务器虚拟 IP 的 IPv4 地址。
                           如果以 teredo 客户端的身份运行则不适用。

备注: 设置 Teredo 状态。
      参数的值 "default" 可将其设置为系统默认值。
      "type=server" 选项仅适用于服务器 SKU。

示例:

       set state disable
       set state client teredo.ipv6.microsoft.com. 60 34567

PS C:\WINDOWS\system32>   netsh interface teredo set state server=teredo.remlab.net
确定。

PS C:\WINDOWS\system32>  // 第一种：修改 Teredo 服务器为 teredo.remlab.net
// : 无法将“//”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次。
所在位置 行:1 字符: 2
+  // 第一种：修改 Teredo 服务器为 teredo.remlab.net
+  ~~
    + CategoryInfo          : ObjectNotFound: (//:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>   netsh interface teredo set state server=teredo.remlab.net
确定。

PS C:\WINDOWS\system32> // 第二种：先卸载当前 Teredo 适配器再重新启用
// : 无法将“//”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次。
所在位置 行:1 字符: 1
+ // 第二种：先卸载当前 Teredo 适配器再重新启用
+ ~~
    + CategoryInfo          : ObjectNotFound: (//:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>   netsh interface Teredo set state disable
确定。

PS C:\WINDOWS\system32>   netsh interface Teredo set state type=default
确定。

PS C:\WINDOWS\system32>   ping -6 ipv6.test-ipv6.com

正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

2001:470:1:18::4:230 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>

**Comment by rockrat** [comment]
额  突然又好了，谢谢了

**Comment by AnyWAT** [comment]
没有突然的好因没有突然的坏，几乎分分钟正常：需关闭某开关 #11291
