### ISSUE TITLE
Chrome上导入证书添加信任仍然显示证书错误

### ISSUE THREAD

**Issue by jd1412** [XX-net/XX-Net#11524]
Chrome上导入证书添加信任仍然显示证书错误：
![image](https://user-images.githubusercontent.com/30342224/46475836-999c5400-c7b4-11e8-8a5a-a93a9604717d.png)
给证书所有信任之后，还是不行：
![image](https://user-images.githubusercontent.com/30342224/46475894-bafd4000-c7b4-11e8-95a7-0795bba5a58a.png)

但是firefox上已经能够访问google了，就是这个chrome的证书哪里有问题
![image](https://user-images.githubusercontent.com/30342224/46475968-f861cd80-c7b4-11e8-8e29-56ec28fccede.png)

**Comment by jd1412** [comment]
![image](https://user-images.githubusercontent.com/30342224/46476043-33fc9780-c7b5-11e8-90ba-b1edbcc240be.png)

**Comment by SeaHOH** [comment]
你用的什么系统？
如果之前导入过 XX-Net 证书，请检查是否一致，如果不确定可以删掉重新导入。

**Comment by jd1412** [comment]
问题已经解决了，具体什么原因不知道，一开始的时候是那个插件装不上去，后面打开了开发者模式之后还是装不上，最后清除浏览器缓存之后，把插件装上了，然后直接证书就可以用了
我用的系统是kali Linux，证书删掉重新导入也不行，就装SwitchyOmega这个之后就好了

**Comment by SeaHOH** [comment]
你这是代理问题，无关证书。。。
