### ISSUE TITLE
XX-Net托盘菜单变灰

### ISSUE THREAD

**Issue by CoffeeWu** [XX-net/XX-Net#11529]
系统是最新的mac mojave，XX-Net 3.12.11，一直都可以用的，现在都可以用chrome切换代理来用。
问题1：
最近发现XX-Net的系统托盘菜单，除了“Config”，“Reset each module”，“Quit”之外，其他菜单都变成灰色不可点击了，试过把XX-Net文件夹全删了，重新安装菜单没问题，但配置完AppID重启电脑，菜单又变成灰色了。
问题2:
“Quit”菜单也不可以退出，只能到“Config”页面退出。
问题3:
有命令行方式切换全局代理的吗(还有退出)？有的话就不纠结上面2个问题了，反正是能用的。
先谢谢各位了

**Comment by SeaHOH** [comment]
1 可能是 bug 或兼容性问题。
2 3 没有相应的终端命令，但是退出可以使用网络请求，参见`Quit`的超链接。

**Comment by CoffeeWu** [comment]
找到问题1的原因了，原来我有一次用其他VPN没有退出，网络连接里那个VPN“按需连接”，所以开机默认是连着VPN的，难怪问题出现时“Good IPv6 Number”一直是满的，我还奇怪网络怎么突然变好呢。
其他VPN影响了XX-Net检测网络状态，托盘菜单“connection:”的值是“none”，正常应该是“Wi-Fi”之类的。
