### ISSUE TITLE
新装Win10，启动XX-NET更改默认浏览器，无法重置。

### ISSUE THREAD

**Issue by iLuXing** [XX-net/XX-Net#11536]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
新装的win10 1803，版本号17134.320
运行XX-NET后，自启动页面是用Edge打开的，但是我的默认浏览器是QQ浏览器。
当我打开「设置」更改「默认应用」时，界面会一卡一卡的，像是不停在刷新。
更改默认浏览器操作也是点了没反应，即便是换成Internet Explorer。

过后，我试着重启电脑，再重复上述更改操作，也是无济于事。
最后，还是切换到安全模式，才将默认浏览器更改回来。
但一运行XX-NET，上述问题又出现了。

一开始，我以为是我打开方式不对，或者系统安装有问题。
我又试着重置系统，还原所有设置etc...
还是没有用。

* 如果问题得到解决，请务必回复相关情况，谢谢。
好的

**Comment by SeaHOH** [comment]
先声明一句：XX-Net 不会修改代理和证书之外的系统设置。

建议你从官方渠道获取系统安装文件。

**Comment by iLuXing** [comment]
我安装的版本就是全新win10，而且重置操作也是通过系统自带的功能，删除全部个人数据。

**Comment by SeaHOH** [comment]
请问，你是从何处获取的 Win10 安装文件？

**Comment by iLuXing** [comment]
> 请问，你是从何处获取的 Win10 安装文件？

当时，win7自动下载的win10。

**Comment by SeaHOH** [comment]
不对吧，免费升级已经停止了。
你是之前预订过 Win10 升级等到了系统推送，还是自己下载工具升级的？
预订过的才是官方升级，其它工具不一定。

**Comment by iLuXing** [comment]
> 不对吧，免费升级已经停止了。
> 你是之前预订过 Win10 升级等到了系统推送，还是自己下载工具升级的？
> 预订过的才是官方升级，其它工具不一定。

我当时就是免费升级呀……
然后重置系统来着……
正版安装，不是ghost什么的……

现在又发现所有默认应用都无法设置了，估计不是XX-NET的事。
但确实是XX-NET安装完后第一时间看的，因为我重置完先装的XX-NET验证的。

**Comment by SeaHOH** [comment]
>    新装的win10 1803，版本号17134.320

你说的新装是好久？免费升级早就已经结束了。
还是说，你说的新装是重置系统？不是很明白。
建议你找微软技术支持。
