### ISSUE TITLE
我的win10 ipv6 一直开不起来 设置后测试也0/10

### ISSUE THREAD

**Issue by Illchange** [XX-net/XX-Net#11539]
netsh int ipv6 show route

发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        手动        256  ::/0                       19  fe80::1
否        手动        256  ::/0                       14  Teredo Tunneling Pseudo-Interface
否        系统        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        手动        256  2001::/32                  14  Teredo Tunneling Pseudo-Interface
否        系统        256  2001:0:53aa:64c:801:aaf5:8be5:305b/128   14  Teredo Tunneling Pseudo-Interface
否        系统        256  fe80::/64                  15  以太网
否        系统        256  fe80::/64                  16  蓝牙网络连接
否        系统        256  fe80::/64                  20  WLAN 2
否        系统        256  fe80::/64                  19  WLAN
否        系统        256  fe80::/64                  22  本地连接* 4
否        系统        256  fe80::/64                  24  本地连接* 5
否        系统        256  fe80::/64                  14  Teredo Tunneling Pseudo-Interface
否        系统        256  fe80::801:aaf5:8be5:305b/128   14  Teredo Tunneling Pseudo-Interface
否        系统        256  fe80::2917:4ba8:d461:8ad0/128   24  本地连接* 5
否        系统        256  fe80::61d7:d2b1:1ada:b165/128   15  以太网
否        系统        256  fe80::d1f9:e392:1a43:bdf0/128   19  WLAN
否        系统        256  fe80::d944:d060:1deb:e374/128   22  本地连接* 4
否        系统        256  fe80::d94c:356b:c9de:2b18/128   20  WLAN 2
否        系统        256  fe80::f0e4:c253:d78f:164c/128   16  蓝牙网络连接
否        系统        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        系统        256  ff00::/8                   15  以太网
否        系统        256  ff00::/8                   16  蓝牙网络连接
否        系统        256  ff00::/8                   20  WLAN 2
否        系统        256  ff00::/8                   19  WLAN
否        系统        256  ff00::/8                   22  本地连接* 4
否        系统        256  ff00::/8                   24  本地连接* 5
否        系统        256  ff00::/8                   14  Teredo Tunneling Pseudo-Interface

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11511#issuecomment-425631370

**Comment by SeaHOH** [comment]
> 否 系统 256 fe80::2917:4ba8:d461:8ad0/128 24 本地连接* 5
> 否 系统 256 fe80::61d7:d2b1:1ada:b165/128 15 以太网
> 否 系统 256 fe80::d1f9:e392:1a43:bdf0/128 19 WLAN
> 否 系统 256 fe80::d944:d060:1deb:e374/128 22 本地连接* 4
> 否 系统 256 fe80::d94c:356b:c9de:2b18/128 20 WLAN 2
> 否 系统 256 fe80::f0e4:c253:d78f:164c/128 16 蓝牙网络连接

取消勾选适配器的 IPv6 项目
![x2scrap2](https://user-images.githubusercontent.com/8470820/46594092-657ca800-cac0-11e8-8a64-5222454fb75f.png)
