### ISSUE TITLE
校园网加xx-net之后校园网连接谷歌速度变慢，且不能看维基百科

### ISSUE THREAD

**Issue by Stevengmk** [XX-net/XX-Net#11538]
在使用xx-net之前校园网能够正常翻墙
但是使用xx-net之后校园网翻墙速度变慢，而且维基百科等其他国外网站无法打开。

**Comment by SeaHOH** [comment]
> 在使用xx-net之前校园网能够正常翻墙

？？你为什么要使用 XX-Net？

**Comment by Stevengmk** [comment]
> > 在使用xx-net之前校园网能够正常翻墙
> 
> ？？你为什么要使用 XX-Net？

回家翻墙

**Comment by SeaHOH** [comment]
请回家后再运行，网络条件不同，现在能用回家也不一定能用。

**Comment by Acytoo** [comment]
在你使用xxnet前,所谓fq是使用ipv6通道连接google, wikipedia等,实际上是直连的.使用了xxnet后如果你使用全局或者软件带的默认rules(如proxyomega等),是将以前直连的链接也转为xxnet,网速自然变慢,关于这点你可以google搜索一下ip,看看有与没有开启xxnet得到的ip地址是不是不同来验证.如果ip不同,需要设置自己的规则,将有ipv6的网站直连以加快连接速度.

    另外,问一下开发者,xxnet有没有dns转发功能? 

不知道你fq与没有fq间有没有清除dns缓存,至少在我们学校最近dns服务器有问题,有时候不能正确解析.

**Comment by SeaHOH** [comment]
关闭后仍可回复
