### ISSUE TITLE
Mac用xx-net好不稳定啊

### ISSUE THREAD

**Issue by iAPPOpen** [XX-net/XX-Net#11537]
通过miredo的方式使用，非常不稳定，比较小白，请问Mac难道只能通过这一种方法使用吗，为什么Windows只要执行一个批处理就可以使用而macOS需要安装APP，是Mac这部分功能缺失吗。
而且miredo我安装的是那个老版本，而官网似乎有一个1.2.3的新版，可是看了一圈看不懂这东西怎么下载怎么安装，哪位知道啊

**Comment by SeaHOH** [comment]
关于 teredo 和 miredo 的介绍，可以自行搜索。
https://www.remlab.net/miredo/ 最新版是 1.2.6，需要自行编译，或者搜索 github 的其它仓库。

**Comment by zhenthoe** [comment]
我的也是，测试出四个服务器，也近一个星期没法用了，不知道怎么办

**Comment by iAPPOpen** [comment]
> 关于 teredo 和 miredo 的介绍，可以自行搜索。
> https://www.remlab.net/miredo/ 最新版是 1.2.6，需要自行编译，或者搜索 github 的其它仓库。

怎么编译，复杂吗，你用的是1.2.6吗，稳定吗

**Comment by SeaHOH** [comment]
没用过，不清楚 Mac 的具体安装流程。

> 搜索 github 的其它仓库

你还可以先搜索本 issues。
