### ISSUE TITLE
youtube播放问题

### ISSUE THREAD

**Issue by HustCoderHu** [XX-net/XX-Net#11531]
全局gae播放正常
SwitchyOmega用xxnet自动切换时，播放窗口中间就一个点击开始播放的标志，标志后方有转圈

**Comment by Acytoo** [comment]
可能是视频的实际地址没有加入到proxy的list中,switchOmega点开有没有fail?把fail的那几个域名加入proxy的list中试一试.

**Comment by AnyWAT** [comment]
标志后方有转圈——貌似暂停再播放能正常，播完后继续播放其它不再转圈？

**Comment by HustCoderHu** [comment]
> 可能是视频的实际地址没有加入到proxy的list中,switchOmega点开有没有fail?把fail的那几个域名加入proxy的list中试一试.

被你说对了，ty
