### ISSUE TITLE
好久没更新啦，x tunnel模式不能用了已经

### ISSUE THREAD

**Issue by miragele** [XX-net/XX-Net#11543]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
貌似X-Tunnel 服务器已恢复😂

**Comment by Beyood** [comment]
Smart Router经常503，要清空域名缓存。dns污染加重？

**Comment by AnyWAT** [comment]
貌似X-Tunnel 服务器又坏了😂

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/11553#issuecomment-429343144
