### ISSUE TITLE
X-tunnel今天一直登陆不上去

### ISSUE THREAD

**Issue by milanthree** [XX-net/XX-Net#11549]
![image](https://user-images.githubusercontent.com/37856464/46716578-28b6d980-cc97-11e8-804c-fbdc957ae776.png)

**Comment by AnyWAT** [comment]
可以啊，莫非姿势不对？😂

**Comment by milanthree** [comment]
现在可以登陆上去了，2点之前一直登不上去，试了好几次

**Comment by AnyWAT** [comment]
此刻如还不正常，
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/11553#issuecomment-429343144
