### ISSUE TITLE
升级win10之后无法连接ipv6

### ISSUE THREAD

**Issue by 1813195468** [XX-net/XX-Net#11540]
如题，从win7升级到win10之后就无法连接了

属性 | 值
-- | --
Teredo 隧道 | 离线（无法连接）

**Comment by 1813195468** [comment]
> 或许 [#11511 (comment)](https://github.com/XX-net/XX-Net/issues/11511#issuecomment-425631370)

里面的方法都试过，没有效果

**Comment by SeaHOH** [comment]
贴`ipconfig /all`的结果

**Comment by 1813195468** [comment]
> 贴`ipconfig /all`的结果

Windows IP 配置

   主机名  . . . . . . . . . . . . . : DESKTOP-SEJIMBT
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe FE Family Controller
   物理地址. . . . . . . . . . . . . : 00-30-18-A2-5B-66
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.31(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年10月8日 14:35:28
   租约过期的时间  . . . . . . . . . : 2018年10月9日 14:35:27
   默认网关. . . . . . . . . . . . . : 192.168.1.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
   DNS 服务器  . . . . . . . . . . . : 192.168.1.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

**Comment by AnyWAT** [comment]
里面的方法都试过，没有效果：贴运行 netsh int ipv6 show teredo 结果（无需IP地址的2行）

**Comment by SeaHOH** [comment]
看样子并没有启用 teredo，楼上命令的结果呢？

**Comment by SeaHOH** [comment]
不知道你的网络是否有变化，点击`测试 teredo`按钮是什么结果？

**Comment by 1813195468** [comment]
可以等一下吗，我刚卸载更新中

**Comment by 1813195468** [comment]
可以等一下吗，我刚卸载更新中

**Comment by 1813195468** [comment]
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

>           ipconfig /all 的结果未免太少了😂
> 里面的方法都试过，没有效果：贴运行 netsh int ipv6 show teredo 结果（无需IP地址的2行）

Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by SeaHOH** [comment]
果然是没启用嘛，点一下启用啊。

**Comment by 1813195468** [comment]
> 果然是没启用嘛，点一下启用啊。


Teredo 隧道 | 离线（无法连接）
-- | --



Teredo 隧道 | 离线（无法连接）
-- | --

**Comment by 1813195468** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by 1813195468** [comment]
> 果然是没启用嘛，点一下启用啊。

点击以后

Starting...
Config servers...
Reset IPv6...
Set IPv6 Tunnel...
Over
Reboot system at first time!
请按任意键继续. . .

**Comment by SeaHOH** [comment]
然后等几分钟，或者重启也行。

**Comment by 1813195468** [comment]
好的，我这就重启试试

**Comment by 1813195468** [comment]
>           然后等几分钟，或者重启也行。

重启后自动变回禁用

**Comment by SeaHOH** [comment]
bug10，又遇到这种了。。。
还是试试有没有原生 IPv6，或者干脆用回 Win7 算了（虚拟机也行）。

**Comment by 1813195468** [comment]
>           bug10，又遇到这种了。。。
> 还是试试有没有原生 IPv6，或者干脆用回 Win7 算了（虚拟机也行）。

在后续版可以被修复吗？

**Comment by SeaHOH** [comment]
我是不用 Win10 的，也不知道微软搞了些什么，无能为力。
真的建议使用虚拟机。

**Comment by 1813195468** [comment]
>           我是不用 Win10 的，也不知道微软搞了些什么，无能为力。
> 真的建议使用虚拟机。

好吧，感谢你的帮助，谢谢！
