### ISSUE TITLE
XX-Net开启后用一段时间就IPv6 Fail

### ISSUE THREAD

**Issue by asd8299128** [XX-net/XX-Net#11551]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:15
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 100
ip-quality: 826
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

用的是GAEProxy，一开始打开正常，能上外网，但用不了多久，就突然Fail，换其他IPv6 服务器，等了数分钟后也不行，但是关掉XX-Net重新打开又好了，然后过一段时间又来！死循环……好烦~前段时间还不会这样的啊

**Comment by SeaHOH** [comment]
降低扫描线程

**Comment by SeaHOH** [comment]
开启自动调整扫描线程
降低扫描线程到 50 以下
重启后等到 IP 数大于 50 再开始使用
如果数量无法达到，慢慢调大扫描线程，最好不要超过 100

**Comment by asd8299128** [comment]
> 
> 
> 开启自动调整扫描线程
> 降低扫描线程到 50 以下
> 重启后等到 IP 数大于 50 再开始使用
> 如果数量无法达到，慢慢调大扫描线程，最好不要超过 100

好的，我试试看

**Comment by SeaHOH** [comment]
关闭后仍可回复
