### ISSUE TITLE
X-Tunnel 配置  连接服务器失败：session server login fail:602

### ISSUE THREAD

**Issue by fc4desmondyyy** [XX-net/XX-Net#11553]
节后发现不对劲了，全局通过GAEproxy没问题，全局通过Xtunnel就不行了，账号都登录不进去，显示连接服务器失败：session server login fail:602

我看前面几篇好像也有人遇到了相似的问题？

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:21 h2:0
scan-ip-thread-num: 2
ip-quality: 503
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![default](https://user-images.githubusercontent.com/44060927/46807229-05c21d80-cd9c-11e8-85a2-944ccad95171.jpg)
![1](https://user-images.githubusercontent.com/44060927/46807232-08bd0e00-cd9c-11e8-9ccb-73d6f372efb0.jpg)
![2](https://user-images.githubusercontent.com/44060927/46807239-0bb7fe80-cd9c-11e8-8444-94121c9f2319.jpg)

**Comment by fc4desmondyyy** [comment]
补充一点，刚打开XX-net时，xtunnel是可以登录成功的，并且还显示了余额和流量，但紧接着过10秒左右，就会显示session server login fail:602。之后再登录就一直处于正在登录请稍后的状态。

**Comment by fc4desmondyyy** [comment]
刷新以后就能正常个10秒，然后又会跳602
X-Tunnel 日志：

Oct 11 22:51:49.359 - [INFO] api:/login success t:626

Oct 11 22:51:49.359 - [INFO] request_balance host:v17.xx-net.net port:443 balance:0.000000 quota:1195973987217.000000

Oct 11 22:51:52.011 - [WARNING] front retry v17.xx-net.net/data

Oct 11 22:51:52.636 - [WARNING] front retry v17.xx-net.net/data

Oct 11 22:51:53.012 - [WARNING] login session fail, status:602

Oct 11 22:51:55.614 - [WARNING] front retry v17.xx-net.net/data

Oct 11 22:51:56.671 - [WARNING] front retry v17.xx-net.net/data

Oct 11 22:51:57.671 - [WARNING] login session fail, status:602

Oct 11 22:51:59.223 - [WARNING] front retry v17.xx-net.net/data

Oct 11 22:52:00.258 - [WARNING] front retry v17.xx-net.net/data

**Comment by milanthree** [comment]
是的，不知道啥原因，我昨天一直登不上去，今天还是这情况

**Comment by AnyWAT** [comment]
此刻 xtunnel 服务器不正常😂

**Comment by fc4desmondyyy** [comment]
也不知道咋回事，一顿瞎操作暂时解决了：
wiki页面中，找到xtunnel有个高级操作，指定日本服务器的，把代码复制到client.json文件里，
重启程序发现xxnet软件怎么也打不开
然后关闭360
然后把client.json文件刚加的那段代码删掉，恢复成一开始的
然后重启程序这时候发现能打开了，并且能够连上xtunnel
瞎猫碰到死耗子吧。。。360的锅？不太清楚。

**Comment by suixin233** [comment]
和楼上同样的问题，指定日本服务器之后好了。
方法如下：
```
修改 data/x_tunnel/client.json 在{ 后面，加入下面两行：
"server_host": "jp1.xx-net.net",
"server_port": 443,
```
唯一需要注意的是，要保证{}内每一行（除了最后一行）的最后有逗号。

**Comment by AnyWAT** [comment]
全英文标点符号😂
是服务器正常了还是指定服务器的效果？正如此刻服务器正常中😜

**Comment by suixin233** [comment]
我猜是指定服务器的效果，因为把加入的两行删了之后重启xxnet，问题也没有再次出现。

> 不是在 http://127.0.0.1:8085/?module=x_tunnel&menu=config "设置"处可设置？
> 全英文标点符号😂
> 是服务器正常了还是指定服务器的效果？正如此刻服务器正常中😜

**Comment by AnyWAT** [comment]
我猜是指定服务器的效果，因为把加入的两行删了之后重启xxnet，问题也没有再次出现。——貌似逻辑有问题：
我猜是指定服务器的效果，因为把加入的两行删了之后重启xxnet，问题😜再次😜出现。

**Comment by milanthree** [comment]
> 我猜是指定服务器的效果，因为把加入的两行删了之后重启xxnet，问题也没有再次出现。——貌似逻辑有问题，如果
> 我猜是指定服务器的效果，因为把加入的两行删了之后重启xxnet，问题😜再次😜出现。
> 才对吧？

像我没有对client.json的文件进行任何操作，直接就是指定服务器，然后就正常了

**Comment by AnyWAT** [comment]
对 client.json 的文件进行正确操作，与控制页内直接指定服务器完全等效

**Comment by Chriszhung** [comment]
这是要挂的节奏

**Comment by Shi-Su-Yu** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: force_ipv6
gws-ip-num: total:undefined good:undefined
network-status: undefined
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
It's XX-Net & SS DEAD time，此刻骑着斑马来的😂
昨天也是大概22时开始DEAD，约半小时后恢复😱

**Comment by SeaHOH** [comment]
@Shi-Su-Yu 你这是没有 IPv6 环境，有点奇怪的是你这复制的信息咋和别人不一样？

>lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK

>ipv6-status: force_ipv6
gws-ip-num: total:undefined good:undefined
network-status: undefined

**Comment by AnyWAT** [comment]
貌似 @Shi-Su-Yu 的上面后2行状态不是第一次见了

**Comment by yuebe** [comment]
现在这样解决不了

**Comment by whatiscospai** [comment]
status:602
