### ISSUE TITLE
以下這些地址哪個好用

### ISSUE THREAD

**Issue by foho8080** [XX-net/XX-Net#11555]
win10.ipv6.microsoft.com(這個好像不行)
teredo.ipv6.microsoft.com
teredo.remlab.net
teredo2.remlab.net
debian-miredo.progsoc.org
teredo.ginzado.ne.jp
teredo.iks-jena.de

**Comment by AnyWAT** [comment]
人工试试即知，管理权限运行
netsh int ipv6 set teredo enterpriseclient default （系统默认，或楼上地址替代 default ）

**Comment by SeaHOH** [comment]
直接点击测试按钮就好，如果可用，日志会记录一个响应最快的服务器地址。
