### ISSUE TITLE
好长一段时间没更新了！！给查水表了吗？？

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#11558]
3.12.11  最近运行一段时间容易IPV6失效，重启软件后正常。问题反复。。。。。。。。。。。

**Comment by GoodSake** [comment]
哈哈哈，嗯，是不太稳定。。

**Comment by AnyWAT** [comment]
😜关闭某开关：分分钟正常、电脑唤醒后代理立马正常的 #11291

**Comment by okaylabababa** [comment]
> 😜关闭某开关：分分钟正常、电脑唤醒后代理立马正常的 #11291

什麼是某開關

**Comment by wolfmarelalala** [comment]
xtunnel有段时间不能用了

**Comment by AnyWAT** [comment]
时常不正常而已，此刻（控制页内指定最后的服务器）正常😂

**Comment by zoggee** [comment]
> 3.12.11 最近运行一段时间容易IPV6失效，重启软件后正常。问题反复。。。。。。。。。。。

目前暂时正常,等待持续的稳定！

**Comment by AnyWAT** [comment]
😂坚持3楼的操作，基本持续的稳定！

**Comment by Alobe007** [comment]
低调有利生存。
