### ISSUE TITLE
vimeo修改hosts直连 问题

### ISSUE THREAD

**Issue by fzxj520** [XX-net/XX-Net#11556]
vimeo修改hosts直连以前非常好用
问题来了
怎么解决？？？播放界面全黑无播放图标进度条？？？网站都能上 但是不能开始播放
通过其他代理测试，可以显示播放界面，一旦开播放就关闭代理， 视频数据依然在走，照样可以继续观看

**Comment by mlleemiles** [comment]
http://savevideo.me/ 可以获取地址直接观看

**Comment by SeaHOH** [comment]
建议参考`F12 网络状态`自行修改代理扩展的自动规则。

**Comment by fzxj520** [comment]
> http://savevideo.me/可以地址电子杂志直接观看

这个可以   但是必须下载  不能在线看

**Comment by fzxj520** [comment]
> 参考建议`F12 网络状态`自行修改代理扩展的自动规则。
谢谢  你这个是什么意思    那个地方修改代理规则啊？ 这个好像和XX-Net没关系

**Comment by SeaHOH** [comment]
网上搜一搜，啥都有了，而且 SwitchyOmega 本身也有教程。
比如红色失败那条，就可以加入自动代理，其它还有一直无法完成的请求，显示为非数字。

**Comment by fzxj520** [comment]
> 网上搜一搜，啥都有了，而且 SwitchyOmega 本身也有教程。
> 比如红色失败那条，就可以加入自动代理，其它还有一直无法完成的请求，显示为非数字。

谢谢 确实不太懂这个 因为SwitchyOmega设置走XX-Net代理  是不能访问vimeo的     
我是通过修改hosts访问vimeo的 以前都好好的现在 就是不显示播放界面

**Comment by fzxj520** [comment]
？？？？？？？？？？？？没办法了吗？？？？？？？？？？？？

**Comment by SeaHOH** [comment]
> 比如红色失败那条，就可以加入自动代理

**Comment by fzxj520** [comment]
试过的 加上 也是不行
