### ISSUE TITLE
连接服务器失败：session server login fail:602

### ISSUE THREAD

**Issue by SenTomoHiro** [XX-net/XX-Net#11550]
国庆之后就这样了，用的是付费的X-TUNNEL流量，连X-TUNNEL账号都登不进去

**Comment by AnyWAT** [comment]
X-TUNNEL 此刻可以啊 https://github.com/XX-net/XX-Net/issues/11549#issuecomment-428461049
scan-ip-thread-num: 10 或许翻倍好点？
ip-quality: 1308 上面改进后此值或许会去掉大头？ #11291

**Comment by SeaHOH** [comment]
贴 X-Tunnel 状态

**Comment by SenTomoHiro** [comment]
> 贴 X-Tunnel 状态


属性 | 值
-- | --
请求数 | 732
响应时间 | 0
往返数 | 271
较慢 | 0
重传 | 0
超时 | 120
当前速度 | Up: 0.0 B/s / Down: 0.0 B/s
使用总量 | Up: 28.3 KB / Down: 65.0 KB

**Comment by SenTomoHiro** [comment]
> X-TUNNEL 此刻可以啊 [#11549 (comment)](https://github.com/XX-net/XX-Net/issues/11549#issuecomment-428461049)
> scan-ip-thread-num: 10 或许翻倍好点？
> ip-quality: 1308 上面改进后此值或许会去掉大头？ #11291

你说的那个是GAEPROXY的设置吧，我的情况是直接连X-TUNNEL都登陆不上，提示session server login fail:602

**Comment by SeaHOH** [comment]
从状态看，客户端工作正常。可能有以下两种原因：
1. 帐号或密码错误；
2. 服务器错误或丢失数据。

**Comment by SeaHOH** [comment]
漏看了一点：你试试停用`Cloudfront 前端`，方法可以在 issues 中搜到。

**Comment by AnyWAT** [comment]
X-TUNNEL 有GAE 及其它4个前端，貌似一般正常的除了GAE 就只有 cloudflare ，流量前者占99%，后者1%
可以说：GAE正常，X-TUNNEL才正常（😂登录不上是因为近几天服务器时常出错？）
关闭无效前端 https://github.com/XX-net/XX-Net/issues/11227#issuecomment-408638834

**Comment by milanthree** [comment]
又登陆不上去了
![image](https://user-images.githubusercontent.com/37856464/46775203-cd3d2800-cd38-11e8-91ba-d44b5345398d.png)

已关闭不用前端
![image](https://user-images.githubusercontent.com/37856464/46775219-e2b25200-cd38-11e8-8028-28889b481197.png)

**Comment by AnyWAT** [comment]
此刻X-TUNNEL服务器正常，因你的GAE不正常？

**Comment by milanthree** [comment]
> 此刻X-TUNNEL服务器正常，因你的GAE不正常？

GAE的日志，好像确实不正常，但又不知道是什么原因
![tim 20181011095843](https://user-images.githubusercontent.com/37856464/46776113-c6b0af80-cd3c-11e8-8141-02d1bf10da65.png)

**Comment by milanthree** [comment]
> GAE日志明显：recheck_ip 而不是关闭了某开关的 remove_slowest_ip
> #11291 几乎分分钟正常、唤醒后立马代理正常。。。

GAE正常之后，tunnel的状态还是fail
![image](https://user-images.githubusercontent.com/37856464/46777777-522d3f00-cd43-11e8-858b-4831fca444b8.png)

![image](https://user-images.githubusercontent.com/37856464/46777785-5c4f3d80-cd43-11e8-8343-e693bc6e89ad.png)

**Comment by AnyWAT** [comment]
退出XX-Net，删除 data\x_tunnel 目录内除 client.json 外的其它文件，再开XX-Net？

**Comment by DicTag** [comment]
同样的问题，可帮忙看看吗？602 登录不了。。


Teredo 隧道 | 合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:91
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:23 h2:0
scan-ip-thread-num: 1
ip-quality: 436
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true



 X-Tunnel 状态信息： （后面四个都关了，不关也是false)
 全局
属性	值
请求数	203
响应时间	0
往返数	0
较慢	0
重传	0
超时	10
当前速度	Up: 0.0 B/s / Down: 0.0 B/s
使用总量	Up: 0.0 B / Down: 0.0 B
GAE 前端
属性	值
Score	268
成功数	77
失败数	0
工作数	20
使用总量	Up: 0.0 B / Down: 0.0 B
Cloudflare 前端
属性	值
Score	
成功数	
失败数	
工作数	
使用总量	
Cloudfront 前端
属性	值
Score	
成功数	
失败数	
工作数	
使用总量	
Heroku 前端
属性	值
Score	
成功数	
失败数	
工作数	
使用总量	
TLS_Relay 前端
属性	值
Score	
成功数	
失败数	
工作数	
使用总量

**Comment by AnyWAT** [comment]
楼上至少从 https://github.com/XX-net/XX-Net/issues/11550#issuecomment-428790294 看起😂
