### ISSUE TITLE
共享后手机智能PAC

### ISSUE THREAD

**Issue by Srantoew** [XX-net/XX-Net#11562]
电脑连接后共享给手机，怎么在手机上设置智能PAC，（国内的直连，别的走代理）？
Wlan代理设置：手动 192.168.1.103 端口8087，全部都是走代理的

手机能打开：http://192.168.1.103:8086/proxy.pac
Wlan代理设置：自动 网址http://192.168.1.103:8086/proxy.pac，直连不走代理，谷歌打不开

**Comment by AnyWAT** [comment]
貌似得打开8086端口： http://127.0.0.1:8085/?module=launcher&menu=config 模块管理——启用 Smart Router
