### ISSUE TITLE
貌似很少人用xxnet，都去用ss ssr和v2ray了……

### ISSUE THREAD

**Issue by iambonboncat** [XX-net/XX-Net#11565]
貌似很少人用xxnet，都去用ss ssr和v2ray了……

**Comment by jecshcier** [comment]
配置起来复杂吧

**Comment by ablebodied** [comment]
那几个都要收费啊

**Comment by AnyWAT** [comment]
😂免费也有，在隔壁 https://github.com/Alvin9999/new-pac/wiki 或许可分解出。。。

**Comment by Acytoo** [comment]
如果你有edu的邮箱,在DO上可以拿到50刀的优惠, 这样使用5刀一个月的服务器(一个月有1T的流量,而且有ipv6的地址)能用十个月. 我周围的同学有很多都是这么干的. 还有一些借助websock搭建的ss,可以免费搭建一个ssserver,推荐一下:[shadowsocks-over-websocket](https://github.com/VincentChanX/shadowsocks-over-websocket)

# 千万不要用DO的服务器挖矿.

**Comment by SasamiMasakiJurai** [comment]
v2ray目前还不普及

主要是目前还无法完全集成到路由里面

ss ssr普及主要是基本可以集成到路由里面造成的

而且v2ray和其他同类的都是用go语言编辑

造成有一定复杂性

普通用户和初学者还无法完全掌握

**Comment by akari263** [comment]
> v2ray目前还不普及
> 
> 主要是目前还无法完全集成到路由里面
> 
> ss ssr普及主要是基本可以集成到路由里面造成的
> 
> 而且v2ray和其他同类的都是用go语言编辑
> 
> 造成有一定复杂性
> 
> 普通用户和初学者还无法完全掌握

v2ray可以集成到路由里面，但因为占空间比较大，一般都是大内存（rom）或者硬改rom的路由能用。

**Comment by Acytoo** [comment]
> 而且v2ray和其他同类的都是用go语言编辑
> 
> 造成有一定复杂性
> 
> 普通用户和初学者还无法完全掌握

v2ray的ss部分和ss的实现方法一样,其他的,只是加的头不一样,伪装成不同的协议,有点语言基础看golang很简单的.
普通用户其实不需要懂的那么多,跟着wiki复制粘贴就可以了, 我觉得v2ray不普及是因为和ss使用起来区别不大, 而ss社区大一些, 比较成熟,就懒得换了.

**Comment by iambonboncat** [comment]
> 如果你有edu的邮箱,在DO上可以拿到50刀的优惠, 这样使用5刀一个月的服务器(一个月有1T的流量,而且有ipv6的地址)能用十个月. 还有amazon和google的学生主机优惠都可以免费用一年. 我周围的同学有很多都是这么干的. 还可以借助websock搭建的ss,可以免费搭建一个ssserver,推荐一下:[shadowsocks-over-websocket](https://github.com/VincentChanX/shadowsocks-over-websocket)
> 
> # 千万不要用DO的服务器挖矿.
> ## 即使不是学生也有很多操作可以拿到EDU邮箱的

heroku貌似封杀了用来做ss ssr 和 v2ray的了
