### ISSUE TITLE
chrome 69.0.3497.100 for mac没法拖拽安装switchyomega

### ISSUE THREAD

**Issue by lbx6z** [XX-net/XX-Net#11560]
<img width="1199" alt="2018-10-13 10 42 18" src="https://user-images.githubusercontent.com/6837297/46906642-4e630d80-cf39-11e8-83cd-0f38cdc69641.png">

**Comment by Jack-ban** [comment]
这个是从68版本开始加了限制，为了防止第三方网站的扩展危及浏览器本身，禁止离线安装扩展。你可以将xx-net开启全局翻墙，然后进入chrome商店搜索一下这个扩展再安装。至于配置文件嘛，还是正常导入即可。

**Comment by Archer-zty** [comment]
打开“开发者模式”，重启下Chrome应该就行

**Comment by lbx6z** [comment]
> 打开“开发者模式”，重启下Chrome应该就行

@Archer-zty 目测不行

**Comment by lbx6z** [comment]
@Jack-ban 已安装成功，感谢！
