### ISSUE TITLE
XXnet的 smart router如何才能排除lastpass？

### ISSUE THREAD

**Issue by alexchan1016** [XX-net/XX-Net#11567]
如果不设置，一开始lastpass会走代理，如何排除掉？

不代理的地址列表
这个地方如何设置？
```
*.lastpass.com
*.lastpass.com*
```
我这样设置好像不行

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=smart_router&menu=config 规则——直连：.lastpass.com ——提交？

**Comment by SeaHOH** [comment]
Chrome 和 Firefox 中，开头的`.`只匹配所有下级名称。
Chrome 支持`*`通配符，Firefox 不支持。

**Comment by alexchan1016** [comment]
> Chrome 和 Firefox 中，开头的`.`只匹配所有下级名称。
> Chrome 支持`*`通配符，Firefox 不支持。

谢谢指导，我用的就是chrome

**Comment by SeaHOH** [comment]
> 我用的就是chrome

设置规则是正确地，你看看是不是还有其它域名需要设置。
