### ISSUE TITLE
XX-NETX-Tunnel流量不能用，只能用AppID

### ISSUE THREAD

**Issue by HASEEMEIZU** [XX-net/XX-Net#11564]
XX-NETX-Tunnel流量不能用，X-Tunnel登陆不上，登陆上一会就掉，显示602，以前用的水星路由器可以用，坏了，换成华硕路由器后就不能上X-Tunnel流量，只能用AppID

**Comment by HASEEMEIZU** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:64
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:52 h2:0
scan-ip-thread-num: 10
ip-quality: 882
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11558#issuecomment-430256934 及以上😂

**Comment by milanthree** [comment]
1、指定tunnel服务器；
2、线程设置30左右；
3、有原生IPV6切换成原生的(好像一般win10的系统就有原生的？)；
4、关闭自动扫描线程；

**Comment by milanthree** [comment]
> 😜原生 IPV6前提：1、ISP商是否提供；2、路由器是否支持

一般移动或者电信会提供吧？

**Comment by AnyWAT** [comment]
移动网前些天问维护，还没听说呢
