### ISSUE TITLE
今早XXNET突然IPv6 fail了

### ISSUE THREAD

**Issue by lzq8143** [XX-net/XX-Net#11569]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

今早XXNET突然IPv6 fail了，到现在也连不上。在我登录github时提示我“您提供的密码由于您或其他人在其他服务上重复使用该密码而被报告为已泄密。”，台式与笔记本共用一个google帐号，与这有关么？

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by asmosn** [comment]
和你一樣，這兩天Teredo大半時間都離線，廣東地區

**Comment by gLoCk27** [comment]
和你一樣，這兩天Teredo彻底離線，廣東地區

**Comment by SeaHOH** [comment]
@gLoCk27 彻底？估计是网络 NAT 类型有变化。
可以告诉 ISP 客服，工作上某些软件使用不正常，申请提供公网 IP，或者能提供 IPv6 也勉强（此处作勉为其难的口气）可以。

> 在我登录github时提示我“您提供的密码由于您或其他人在其他服务上重复使用该密码而被报告为已泄密。”，台式与笔记本共用一个google帐号，与这有关么？

建议更换密码

**Comment by liule0228** [comment]
是不是被集体屏蔽了，我的也是能用一会就不能用了，换个隧道又能用一会就又不能用了

**Comment by duabaoji** [comment]
同fail。平常修复可行，这次修复也没办法了。

**Comment by AnyWAT** [comment]
显示（GAE）一切正常，x-tunnel 或许并不正常，http://127.0.0.1:8085/?module=x_tunnel&menu=status 有速度或流量，且 http://127.0.0.1:8085/?module=x_tunnel&menu=config 成功登录、刷新该网页也不出602才全正常😂

**Comment by AnyWAT** [comment]
@Chriszhung
x-tunnel 比较正常，源于：
1、不选自动，指定任一个服务器？
2、禁用早已失效的 http://127.0.0.1:8085/?module=x_tunnel&menu=status 最后3个前端？

**Comment by SasamiMasakiJurai** [comment]
隧道污染加剧

记得之前提起过

不过好些地方有原生ipv6了

可以看看是不是可以获取原生ipv6

**Comment by lzq8143** [comment]
没改变任何设置，这几天又恢复正常了。

**Comment by AnyWAT** [comment]
@lzq8143 下次再出状况，最好不用新贴而在此贴继续，好有比较😂

**Comment by duabaoji** [comment]
今天我来试了一下正常了。沿海的联通网。之前重置了系统也没啥用。。只好转投酸酸乳几天。
