### ISSUE TITLE
换了几个teredo隧道都fail谁有给力的teredo

### ISSUE THREAD

**Issue by liule0228** [XX-net/XX-Net#11577]
* teredo.remlab.net / teredo-debian.remlab.net (法国) (Miredo 默认设置) 
* teredo.autotrans.consulintel.com (西班牙) 
* teredo.ipv6. microsoft .com (美国 雷蒙德) (Windows XP/2003/Vista/7/2008 系统默认设置) 
* teredo.ngix.ne.kr (韩国) 
* teredo.managemydedi.com (美国 芝加哥)
这些都试过了不能用

**Comment by 2378** [comment]
先测试isp是否针对udp qos或者干扰或者深度检查
严重的地区 别说teredo
magnet kadnet 都连不上

**Comment by liule0228** [comment]
怎么测试

**Comment by liule0228** [comment]
> 先测试isp是否针对udp qos或者干扰或者深度检查
> 严重的地区 别说teredo
> magnet kadnet 都连不上

怎么测试

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6#工具

第一个工具已经集成到 XX-Net 里面了，第二个能自己选择服务器。

**Comment by 2378** [comment]
怎么测～～不清楚你的环境

我是直接netcat往vps传包
话说回头，都有vps了，也不在乎teredo死活了
