### ISSUE TITLE
这几天一直掉线，连上十几分钟就失效。

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#11570]
基本配置：
系统：macOS Mojave10.14
python：2.7.10
OpenSSL: 18.0.0 TLSv1 h2:alpn
XX-Net：3.12.11
Miredo：1.2.6
tun&tap：2018年9月30日的tun-signed.text和tap-signed.text
XX-Net是最终版本，用sourcetree更新的
Miredo是结合judy编译的
tun-signed.text和tap-signed.text是从Tunnelblick里拷贝出来最新的
运行sudo miredo start开始没问题，可以正常使用，但一会就显示：
Oct 20 02:08:38  miredo[99798] <Info>: No reply from Teredo server
Oct 20 02:08:38  miredo[99798] <Notice>: Lost Teredo connectivity
Oct 20 02:08:38  miredo[99798] <Notice>: Teredo pseudo-tunnel stopped
Oct 20 02:08:43  miredo[99798] <Debug>:  packet dropped because tunnel down
已经修改了miredo.conf里的ServerAddress为teredo.iks-jena.de
另外延迟大概在1100左右

重新编译了一下，可能是之前先安装了老版的tun导致的，这次先启动：
sudo kextload /library/extensions/tap-signed.kext
sudo kextload /library/extensions/tun-signed.kext
重新make install已经可以了，不过延迟的问题还是没有解决。

**Comment by SeaHOH** [comment]
能否把步骤写一下？好多人都不会。

**Comment by causlayer** [comment]
参考https://www.macx.cn/thread-1884503-1-1.html
我只是针对tap&tun和miredo版本做了升级。
文件我传不上来，这里做下说明吧
一.tap&tun我是从Tunnelblick里拷贝出来最新的，操作参考
sudo mkdir -p /Library/Extensions
sudo cp -pR tap-signed.kext /Library/Extensions/
sudo cp -pR tun-signed.kext /Library/Extensions/
sudo chown -R root:wheel /Library/Extensions/tap-signed.kext
sudo chown -R root:wheel /Library/Extensions/tun-signed.kext
sudo kextload /Library/Extensions/tap-signed.kext/
sudo kextload /Library/Extensions/tun-signed.kext/
二.升级miredo到1.2.6
从网上下载的miredo1.2.6，注意修改相关位置再操作./autogen.sh：
1.修改configure.ac文件
(1) AM_GNU_GETTEXT_VERSION后面的版本号，brew info gettext查看
(2) 因为使用了judy,168行后需增加judy路径，使程序能够找到judy.h
if test "x${with_Judy}" != "xyes" ; then
        CFLAGS="$CFLAGS -I${with_Judy}/include"
        LDFLAGS="$LDFLAGS -L${with_Judy}/lib"
    fi
2.修改Makefile.am文件
AUTOMAKE_OPTIONS后面修改版本号,brew info automake查看
3.修改src/relayd.c文件
设定初始值
#ifndef MSG_NOSIGNAL
#define MSG_NOSIGNAL 0 /* Uho */
#endif
三.miredo安装完成后注释掉/usr/local/miredo/share/doc/miredo/examples/miredo.conf和/usr/local/miredo/etc/miredo/miredo.conf 文件中的InterfaceName  teredo

以上就是从源码安装需要注意的几个地方，希望能对使用macbook的朋友有所帮助。

**Comment by HowardZit** [comment]
救救孩子吧老哥，给个打包好的东西吧，谢谢🙏🙏🙏

**Comment by erpapa** [comment]
根据楼主的方案，给出一个miredo源代码压缩包，10.14测试正常使用！！！
[miredo-1.2.6.zip](https://github.com/XX-net/XX-Net/files/2505086/miredo-1.2.6.zip)

1.下载zip包，解压
`
cd ~Downloads
unzip ~/Downloads/miredo-1.2.6.zip
`
2.cd到源代码目录
`
cd miredo-1.2.6
 `
3.安装brew，已安装的可以略过。
`
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 `
4.miredo依赖gettext，使用brew安装gettext
目前版本是0.19.8.1，已在autogen.sh指定头文件路径，不用在configure.ac添加代码,
configure.ac我只改了AM_GNU_GETTEXT_VERSION后的版本号0.19.8.1。
`
brew install gettext
`
5.修改Makefile.am文件AUTOMAKE_OPTIONS后的版本号，我这里是1.16.1_1，
如果没有安转automake，需要先安装automake。
`
brew install automake
`
6.安装Judy，cd到libjudy目录
`
cd libjudy
./configure
make
make check
make install
`
安装完毕，回到上级目录
`
cd ..
`
7.编译miredo
`
./configure
make
sudo make install
`
8.关于注释掉那两个conf文件里的代码行，路径和我这里不一样，因人而异吧
9.关于两个kext文件，我是直接加载的，以下是启动脚本，放到xx-net目录下即可。

启动xx-net的命令行如下：
`
./auto_start.sh
`

**Comment by erpapa** [comment]
> 救救孩子吧老哥，给个打包好的东西吧，谢谢🙏🙏🙏

可以看看我的步骤

**Comment by HowardZit** [comment]
> > 救救孩子吧老哥，给个打包好的东西吧，谢谢🙏🙏🙏
> 
> 可以看看我的步骤

谢谢老哥，我按照步骤操作之后，报这个错：
kext (kmod) start/stop routine failed

**Comment by phoenixzzan** [comment]
> 根据楼主的方案，给出一个miredo源代码压缩包，10.14测试正常使用！！！
> [miredo-1.2.6.zip](https://github.com/XX-net/XX-Net/files/2505086/miredo-1.2.6.zip)
> 
> 1.下载zip包，解压
> 
> ```
> cd ~Downloads
> unzip ~/Downloads/miredo-1.2.6.zip
> ```
> 2.cd到源代码目录
> 
> ```
> cd miredo-1.2.6
> ```
> 3.安装brew，已安装的可以略过。
> 
> ```
> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
> ```
> 4.miredo依赖gettext，使用brew安装gettext
> 目前版本是0.19.8.1，已在autogen.sh指定头文件路径，不用在configure.ac添加代码,
> configure.ac我只改了AM_GNU_GETTEXT_VERSION后的版本号0.19.8.1。
> 
> ```
> brew install gettext
> ```
> 5.修改Makefile.am文件AUTOMAKE_OPTIONS后的版本号，我这里是1.16.1_1，
> 如果没有安转automake，需要先安装automake。
> 
> ```
> brew install automake
> ```
> 6.安装Judy，cd到libjudy目录
> 
> ```
> cd libjudy
> ./configure
> make
> make check
> make install
> ```
> 安装完毕，回到上级目录。
> 
> ```
> cd ..
> ```
> 7.编译miredo
> 
> ```
> ./configure
> make
> sudo make install
> ```
> 8.关于注释掉那两个conf文件里的代码行，路径和我这里不一样，因人而异吧。
> 
> 9.关于两个kext文件，我是直接加载的，以下是启动脚本，放到xx-net目录下即可。
> [auto_start.sh.zip](https://github.com/XX-net/XX-Net/files/2505127/auto_start.sh.zip)
> 
> 启动xx-net的命令行如下：
> 
> ```
> ./auto_start.sh
> ```

10.14.3 捣腾一天终于上了。也是对于小白估计还要再写明白些吧。

**Comment by phoenixzzan** [comment]
使用两天下来还是不稳定，IPV6 经常 fail 

XX-Net Status:

sys-platform: x86_64, Darwin-18.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
os-release: 18.2.0
os-detail: Release:10.14.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:39
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:9
scan-ip-thread-num: 1
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false
