### ISSUE TITLE
刚开了会VPN关了XXNET  然后退出VPN再开XXNET就不能用了

### ISSUE THREAD

**Issue by untitled2014** [XX-net/XX-Net#11574]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:98
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 457
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xiaoas** [comment]
看状态页第一行
状态页上如果显示的是请设置代理 那就是代理不对
否则可能是vpn退出的时候没有关闭代理 在系统中重新设置

**Comment by untitled2014** [comment]
> 看状态页第一行
> 状态页上如果显示的是请设置代理 那就是代理不对
> 否则可能是vpn退出的时候没有关闭代理 在系统中重新设置

是 请检查浏览器代理设置。 自动检测 设置脚本和手动设置代理都开了 重启电脑了还是用不了XXNET

**Comment by xiaoas** [comment]
用chrome 和switchyomega
或者右下角icon设置全局代理呢

**Comment by untitled2014** [comment]
> 用chrome 和switchyomega
> 或者右下角icon设置全局代理呢
右下角全局GAE 全局PAC   switchyomega是GAE自动切换  
第一行提示 系统空闲。 (正常)  下边

浏览器代理设置 | Fail
-- | --
CA 证书状态(下载) | Fail

**Comment by untitled2014** [comment]
> 用chrome 和switchyomega
> 或者右下角icon设置全局代理呢

重新导入证书  

CA 证书状态(下载) | Fail
-- | --

**Comment by xiaoas** [comment]
这都是正常的
你如果右下角icon设置全局GAE代理
或者switchyomega中走127.0.0.1:8087
无法访问外网？

**Comment by untitled2014** [comment]
> 这都是正常的
> 你如果右下角icon设置全局GAE代理
> 或者switchyomega中走127.0.0.1:8087
> 无法访问外网？

是的 开VPN之前还是好的

**Comment by xiaoas** [comment]
GAEPROXY的相关日志截个图
你重启过还无法访问外网多半还是没设置好
如果浏览器要卡很久才会报错 那等一会再试试

**Comment by xiaoas** [comment]
crap...不是这个页面
首先你截图之前记得要ctrl+F5
其次你代理没有开 你真的尝试了我说的两种方法么？
这样 你在系统的局域网代理界面 手动讲代理设置为127.0.0.1:8087 然后尝试用ie访问google

**Comment by untitled2014** [comment]
> crap...不是这个页面
> 首先你截图之前记得要ctrl+F5
> 其次你代理没有开 你真的尝试了我说的两种方法么？
> 这样 你在系统的局域网代理界面 手动讲代理设置为127.0.0.1:8087 然后尝试用ie访问google

谢谢 问题已经解决了  原来是一个去优酷和爱奇艺广告的插件冲突了 把那插件关掉就显示正常了

**Comment by xiaoas** [comment]
这样么。。。学到了
我好菜啊.jpg

**Comment by untitled2014** [comment]
> 这样么。。。学到了
> 我好菜啊.jpg

非常感谢你耐心回答，我才菜。。自己乱整把自己整的上不了外网了，还好现在搞好了

**Comment by AnyWAT** [comment]
问题已经解决了 原来是一个去优酷和爱奇艺广告的插件冲突了 把那插件关掉就显示正常了——或许只是时间上的巧合而已，试试：再打开它😂
貌似症结在：打开了某开关后的不时连接池归零😜 参考：#11291
![image](https://user-images.githubusercontent.com/37962734/47266425-d44e0c80-d568-11e8-9e33-7b4dc6386b68.png)

**Comment by untitled2014** [comment]
> 问题已经解决了 原来是一个去优酷和爱奇艺广告的插件冲突了 把那插件关掉就显示正常了——或许只是时间上的巧合而已，试试：再打开它😂
> 貌似症结在：打开了某开关后的不时连接池归零😜 参考：#11291
> ![image](https://user-images.githubusercontent.com/37962734/47266425-d44e0c80-d568-11e8-9e33-7b4dc6386b68.png)
厉害了老哥 虽然没到230多延迟  现在390延迟也不错了 按你方法之前5 600多延迟

**Comment by AnyWAT** [comment]
@mymixing 是误操作还是有意为之？点击以下链接出404😂
https://github.com/XX-net/XX-Net/issues/11575
https://github.com/XX-net/XX-Net/issues/11576

**Comment by AnyWAT** [comment]
@mymixing 是误操作还是有意为之？点击以下链接出404😂
https://github.com/XX-net/XX-Net/issues/11575
https://github.com/XX-net/XX-Net/issues/11576

**Comment by AnyWAT** [comment]
@mymixing 是误操作还是有意为之？点击以下链接出404😂
https://github.com/XX-net/XX-Net/issues/11575
https://github.com/XX-net/XX-Net/issues/11576

**Comment by AnyWAT** [comment]
说了点关于特权的被删不留痕，厉害😥

**Comment by AnyWAT** [comment]
😂很傻8，不到一定级别点击链接404，那你又提示干嘛？
![image](https://user-images.githubusercontent.com/37962734/47277086-0dc95b00-d5ef-11e8-9342-116de33100e5.png)
