### ISSUE TITLE
为什么google搜索页面能打开，但是一输入搜索内容Google一下他就转啊转加载不出来

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#11579]
为什么google搜索页面能打开，但是一输入搜索内容Google一下他就转啊转加载不出来
， 然后就跳出504
![default](https://user-images.githubusercontent.com/18262731/47302961-5fa4cc00-d655-11e8-88fa-5b4008937e8a.png)

XX-Net 3.12.11，一切正常，你可以访问真正的互联网了
属性 | 值
-- | --
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	OK
有效 IPv4 IP 数	0
有效 IPv6 IP 数	99
总 IP 数	100
XX-Net 状态	工作
IP 延迟	464
连接池(帮助)	新:0 h1:18 h2:0
浏览器代理设置	OK
CA 证书状态(下载)	OK
IP 扫描线程数(设置)	4

Oct 22 23:52:09.356 - [DEBUG] create_ssl update ip:2607:f8b0:4004:2d::a time:960 h2:0 sni:stripstorage.org, host:huan1998.appspot.com

Oct 22 23:52:09.431 - [INFO] scan_ip add ip:2001:8002:e22:ef03::11 time:663 h2:0

Oct 22 23:52:09.432 - [INFO] Adjust scan thread num from 4 to 5

Oct 22 23:52:09.433 - [INFO] remove_slowest_ip:2607:f8b0:4004:2d::a handshake_time:872, fails:0

Oct 22 23:52:10.764 - [DEBUG] GAE GET https://www.google.com/chromesuggestions?t=1 from:127.0.0.1:7458

Oct 22 23:52:11.360 - [INFO] GAE t:595 s:1550 GET https://www.google.com/chromesuggestions?t=1 0:start_request,0:get_task(2),1:get_worker(0):2607:f8b0:4017:3c::6,0:h1_req,0:h1_req_sended,588:response_begin,0:h1_get_head,0:get_response,1:h1_finish[SP:3042],:2

Oct 22 23:52:11.380 - [DEBUG] report_connect_fail:2607:f8b0:4005:1b::a

Oct 22 23:52:11.380 - [DEBUG] connect 2607:f8b0:4005:1b::a fail:error("conn fail, sni:presentationrecognition.us, top:huan2018.appspot.com e:timeout('timed out',)",)

Oct 22 23:52:11.395 - [INFO] scan_ip add ip:2001:2f8:0:15::e time:634 h2:0

Oct 22 23:52:11.396 - [INFO] Adjust scan thread num from 5 to 6

Oct 22 23:52:11.396 - [INFO] remove_slowest_ip:2607:f8b0:401a:3::a handshake_time:863, fails:0

Oct 22 23:52:11.882 - [DEBUG] report_connect_fail:2607:f8b0:401d:1c::8

Oct 22 23:52:11.882 - [DEBUG] connect 2607:f8b0:401d:1c::8 fail:error("conn fail, sni:wind-cap-community.com, top:huan2010.appspot.com e:timeout('timed out',)",)

Oct 22 23:52:14.070 - [WARNING] 2001:4958:300:4f3::c host:hu98.appspot.com head fail status:404

Oct 22 23:52:14.070 - [DEBUG] report_connect_fail:2001:4958:300:4f3::c

Oct 22 23:52:14.780 - [INFO] scan_ip add ip:2404:6800:400c:4::b time:603 h2:0

Oct 22 23:52:14.781 - [INFO] remove_slowest_ip:2001:4958:300:4f3::c handshake_time:794, fails:1

Oct 22 23:52:15.193 - [DEBUG] 2001:4958:300:4f3::c worker close:keep alive

Oct 22 23:52:16.088 - [INFO] scan_ip add ip:2001:40a8:4400:12::c time:585 h2:0

Oct 22 23:52:16.088 - [INFO] Adjust scan thread num from 6 to 5

Oct 22 23:52:16.088 - [INFO] remove_slowest_ip:2607:f8b0:401d:1c::8 handshake_time:351, fails:1

Oct 22 23:52:16.678 - [INFO] scan_ip add ip:2804:14d:14f9:7::10 time:720 h2:0

Oct 22 23:52:16.679 - [INFO] remove_slowest_ip:2607:f8b0:4005:1b::a handshake_time:342, fails:1

Oct 22 23:52:22.001 - [WARNING] 2607:f8b0:4004:2d::a host:hu98.appspot.com head fail status:404

Oct 22 23:52:22.001 - [DEBUG] report_connect_fail 2607:f8b0:4004:2d::a not exist

Oct 22 23:52:23.340 - [DEBUG] 2607:f8b0:4004:2d::a worker close:keep alive

Oct 22 23:52:31.354 - [INFO] scan_ip add ip:2607:f8b0:4004:31::b time:386 h2:0

Oct 22 23:52:31.355 - [INFO] Adjust scan thread num from 5 to 4

Oct 22 23:52:31.355 - [INFO] remove_slowest_ip:2607:f8b0:4007:2f::7 handshake_time:837, fails:0

Oct 22 23:52:32.062 - [INFO] scan_ip add ip:2a00:1450:4011:43::15 time:608 h2:0

Oct 22 23:52:32.063 - [INFO] Adjust scan thread num from 4 to 3

Oct 22 23:52:32.063 - [INFO] remove_slowest_ip:2804:214:800f:11::d handshake_time:772, fails:0

Oct 22 23:52:34.186 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=fbqjIU7nWLLoiMiQS6no7A%3D%3D from:127.0.0.1:7464

Oct 22 23:52:34.525 - [INFO] GAE t:338 s:1279 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=fbqjIU7nWLLoiMiQS6no7A%3D%3D 0:start_request,0:get_task(23),0:get_worker(0):2607:f8b0:4017:3c::6,0:h1_req,2:h1_req_sended,326:response_begin,0:h1_get_head,0:get_response,2:h1_finish[SP:5066],:5

Oct 22 23:52:34.536 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=fbqjIU7nWLLoiMiQS6no7A%3D%3D from:127.0.0.1:7464

Oct 22 23:52:34.872 - [INFO] GAE t:335 s:532 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=fbqjIU7nWLLoiMiQS6no7A%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:4017:14::a,0:h1_req,0:h1_req_sended,325:response_begin,0:h1_get_head,1:h1_finish[SP:2850],0:get_response,:7

Oct 22 23:52:35.076 - [DEBUG] create_ssl update ip:2607:f8b0:401d:2::b time:881 h2:0 sni:improvement.service.trick.ml, host:huani2011.appspot.com

Oct 22 23:52:39.696 - [DEBUG] report_connect_fail:2607:f8b0:4002:2d::6

Oct 22 23:52:39.696 - [DEBUG] connect 2607:f8b0:4002:2d::6 fail:error("conn fail, sni:army-pride.net, top:huan2018.appspot.com e:timeout('timed out',)",)

**Comment by LN-VIVI** [comment]
![qq 20181022235931](https://user-images.githubusercontent.com/18262731/47303492-99c29d80-d656-11e8-87c7-75b8b4d00280.jpg)
![Uploading QQ截图20181022235952.jpg…]()

**Comment by LN-VIVI** [comment]
![qq 20181022235952](https://user-images.githubusercontent.com/18262731/47303524-b068f480-d656-11e8-8071-081f9a2147bf.jpg)

**Comment by LN-VIVI** [comment]
@woosley @AnyWAT

**Comment by AnyWAT** [comment]
Adjust scan thread num from 4 to 5
Adjust scan thread num from 5 to 6
Adjust scan thread num from 6 to 5
Adjust scan thread num from 5 to 4
Adjust scan thread num from 4 to 3
貌似开启了某开关？😜参考：#11291

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by LN-VIVI** [comment]
> 关闭某开关、增大扫描线程，检查 IP或退出XX-Net，删除 good_ip.txt 再启动XX-net
> netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:98
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:20 h2:0
scan-ip-thread-num: 1
ip-quality: 377
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

XX-Net 3.12.11，一切正常，你可以访问真正的互联网了。
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	OK
有效 IPv4 IP 数	0
有效 IPv6 IP 数	99
总 IP 数	100
XX-Net 状态	工作
IP 延迟	377
连接池(帮助)	新:0 h1:15 h2:0
浏览器代理设置	OK
CA 证书状态(下载)	OK
IP 扫描线程数(设置)	1
配置
属性	值
代理监听	127.0.0.1:8087
IP 模式	仅 IPv6
前置代理	禁用

**Comment by LN-VIVI** [comment]
@AnyWAT

**Comment by SeaHOH** [comment]
访问 https://www.google.com/ncr#hl=zh_CN 一次
然后，hu98 这个 ID 不存在，或没部署。

**Comment by AnyWAT** [comment]
Windows-10：系统默认服务器或许更好，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
IP 扫描线程数(设置) 1😥貌似仍没关闭某开关呢，不听建议还 @个PP 😡

**Comment by AnyWAT** [comment]
类型 : enterpriseclient (Group Policy) 命令 netsh int ipv6 set teredo enterpriseclient default 在退回到 ipv6组策略前或许无效🙃

**Comment by LN-VIVI** [comment]
@AnyWAT 哪个开关？不是一直都这样吗
![qq 20181023010551](https://user-images.githubusercontent.com/18262731/47306794-f70f1c80-d65f-11e8-9d70-e855b1f587ee.jpg)
![qq 20181023010619](https://user-images.githubusercontent.com/18262731/47306795-f7a7b300-d65f-11e8-92ff-4846f0df2f68.jpg)

**Comment by AnyWAT** [comment]
只知道：打开了某开关，才会出现 scan-ip-thread-num: 1 （IP 扫描线程数(设置) 1）

**Comment by LN-VIVI** [comment]
这样子打开页面速度更慢，百兆光纤诶__

**Comment by AnyWAT** [comment]
莫非有原生 IPv6 ？没经历，逃。。。

**Comment by LN-VIVI** [comment]
@SeaHOH  那是我为了防止你们盗用ID所以把部分字母删了，我部署了10个Id诶😜

**Comment by LN-VIVI** [comment]
> 莫非有原生 IPv6 ？没经历，逃。。。

哈哈哈哈哈哈哈哈哈，还不睡

**Comment by LN-VIVI** [comment]
> @SeaHOH 那是我为了防止你们盗用ID所以把部分字母删了，我部署了10个Id诶😜

妈耶，用着用着他会自己ipv6 fail

**Comment by AnyWAT** [comment]
再次说下：增大总 IP数及线程数，再增大连接接收缓冲大小

**Comment by LN-VIVI** [comment]
> 莫非有原生 IPv6 ？没经历，逃。。。

妈耶，用着用着他会自己ipv6 fail

**Comment by SeaHOH** [comment]
> host:「总之你随便哪个 ID 吧」.appspot.com head fail status:404
访问连接不管用么？

**Comment by AnyWAT** [comment]
莫非关闭了某开关但没提交？

**Comment by LN-VIVI** [comment]
> > host:「总之你随便哪个 ID 吧」.appspot.com head fail status:404
> 
> 访问连接不管用么？

这次好了，现在就剩 ipv6用着用着他会自己 fail的问题了

**Comment by LN-VIVI** [comment]
> 再开一个，挤出已不正常的

用了 netsh int ipv6 set teredo enterpriseclient default 就好le

**Comment by LN-VIVI** [comment]
have a good night ! thanks! @AnyWAT

**Comment by AnyWAT** [comment]
也有助：增大总 IP数及线程数，或可增大连接接收缓冲大小

**Comment by SeaHOH** [comment]
> 再次说下：增大总 IP数及线程数，或可增大连接接收缓冲大小

相反的操作会更稳定，信不信随便。

> 
> 属性 	值
> Teredo 隧道 	离线（无法连接）

这种情况，重新拨号，或者重启路由能快速恢复。

**Comment by LN-VIVI** [comment]
@SeaHOH    @AnyWAT 原来大神们都是不用睡觉的233333333333333，我先睡了

**Comment by ezhyg** [comment]
超时得厉害

**Comment by ezhyg** [comment]
谷歌动不动就504了

**Comment by AnyWAT** [comment]
几乎没见过😁
