### ISSUE TITLE
如何在树莓派3B上实现翻墙代理？

### ISSUE THREAD

**Issue by panghu1986** [XX-net/XX-Net#11581]
那位能帮忙指导一下，如何实现在树莓派上使用XX-net翻墙。

**Comment by Acytoo** [comment]
如果是把树莓派当成主机（个人电脑）使用的话，就按照linux的方法就好。
下载并解压，或者git clone， cd到xx-net的目录，
执行
```
./start
```
就可以了

**Comment by g8up** [comment]
启动后没看到系统托盘的图标。如何设置为全局代理呢？
