### ISSUE TITLE
twitter 视频无法播放，有遇到相同情况的吗？

### ISSUE THREAD

**Issue by alexbyrant** [XX-net/XX-Net#11589]
twitter 视频无法播放，有遇到相同情况的吗？
![image](https://user-images.githubusercontent.com/28650185/47554691-73458080-d93c-11e8-845f-6e24decaab83.png)

**Comment by AnyWAT** [comment]
视频无法播放无非代理速度不够，试试：#11291

**Comment by alexbyrant** [comment]
好像不起作用，还是无法播放Twitter视频。youtube等视频没有问题，原生ipv6

**Comment by SeaHOH** [comment]
参考开发者工具（F12）的网络页面记录来调整你的代理设置或规则。

**Comment by alexbyrant** [comment]
控制台反馈的信息：

Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See <URL> for more details

**[Intervention] Slow network is detected. See** https://www.chromestatus.com/feature/5636954674692096 **for more details. Fallback font will be used while loading:** https://abs.twimg.com/a/1540404891/font/edge-icons-Regular.woff

**Refused to load the script '**https://cm.g.doubleclick.net/pixel?google_nid=twitter_dbm&google_cm&tpm_cb=partnerIdSyncComplete&_=1540562908927**' because it violates the following Content Security Policy directive: "script-src** https://ssl.google-analytics.com https://twitter.com **'unsafe-eval'** https://*.twimg.com https://api.twitter.com https://analytics.twitter.com https://publish.twitter.com https://ton.twitter.com https://syndication.twitter.com **'nonce-KrTFldRWkdDTbGosneDI5A=='** https://www.google.com https://platform.twitter.com https://www.google-analytics.com **blob: 'self'".**

**Uncaught SyntaxError :** abs.twimg.com/k/en/13.hls.js.en.d49d8b4158cafa581d94.js:2 
**Unexpected token :**

**Comment by AnyWAT** [comment]
电脑官网浏览可打开“含有视频的推文：自动播放视频”（提前、及时缓存加载？）
[Intervention] Slow network is detected.——符合（可长时间缓存加载的）youtube等视频没有问题，无法播放Twitter视频？😂

**Comment by SeaHOH** [comment]
并不需要控制台信息，只要观察网络请求失败的记录即可。
开启开发者工具的情况下刷新页面才能记录。

**Comment by SeaHOH** [comment]
关闭后仍可回复

**Comment by zeiyu314** [comment]
同样的情况，youtube4K流畅，然而推特就是图片和视频不能加载。
