### ISSUE TITLE
一直显示系统空闲正常。但是连不上网，而且证书和浏览器代理全fail是什么情况呀

### ISSUE THREAD

**Issue by hauchenjiang** [XX-net/XX-Net#11585]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:77
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 565
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
代理是怎么设置的，你确定正确吗？

**Comment by AnyWAT** [comment]
代理设置不正确也就太白了，😱小概率。。。
worker: h1:0 h2:0 引发😂证书和浏览器代理全fail 
scan-ip-thread-num: 1 😜见证某特征值 N+1
试试：#11291
