### ISSUE TITLE
为什么windows下面打开后没有托盘，也进不了原来的管理页面

### ISSUE THREAD

**Issue by dirtyluke** [XX-net/XX-Net#11583]

**Comment by AnyWAT** [comment]
😂因为整了什么使windows下面打开后没有托盘？

**Comment by dirtyluke** [comment]
@AnyWAT 
uncaught Exception, type=<type 'exceptions.IOError'> value=[Errno 0] Error traceback:<traceback object at 0x0456ABE8>

**Comment by AnyWAT** [comment]
不正常的现在与上次正常时的内容。。。无语了
启动XX-Net 3-5分钟后，Win10 任务管理器——性能——打开资源管理器——勾选 pythonw.exe，查看下面各端口是否齐全，没有托盘或许是8085被占用
![default](https://user-images.githubusercontent.com/37962734/47614123-93f50e00-dad5-11e8-8bb5-a4fab4fe17af.png)

**Comment by SeaHOH** [comment]
手动修改了配置吧。
关闭后仍可回复
