### ISSUE TITLE
斐讯 k2p 刷入 padavan 固件，ipv6

### ISSUE THREAD

**Issue by MitchellClark666** [XX-net/XX-Net#11596]
斐讯 k2p 刷入 padavan 固件，可以支持 ipv6 了。

![1](https://user-images.githubusercontent.com/13077075/47605711-acfdb080-da3c-11e8-9548-64eee8775c54.JPG)

![2](https://user-images.githubusercontent.com/13077075/47605712-ad964700-da3c-11e8-83fa-05f648229fd6.JPG)

**Comment by lsq726** [comment]
用的什么方案?

**Comment by lsq726** [comment]
刚好k2p+padavan

**Comment by SasamiMasakiJurai** [comment]
他这个是当地运营商已经下发ipv6地址了

只要路由支持ipv6就可以自动获得地址

**Comment by lsq726** [comment]
> 他这个是当地运营商已经下发ipv6地址了
> 
> 只要路由支持ipv6就可以自动获得地址

哦原来如此..羡慕嫉妒

**Comment by SasamiMasakiJurai** [comment]
> > 他这个是当地运营商已经下发ipv6地址了
> > 只要路由支持ipv6就可以自动获得地址
> 
> 哦原来如此..羡慕嫉妒

你也可以看看自己的

现在好些地方已经有原生ipv6了

**Comment by Sakuyaaaaaa** [comment]
你是K2P拨号还是光猫拨号？我光猫拨号，连接的k2p一直无法连接v6
