### ISSUE TITLE
又602了

### ISSUE THREAD

**Issue by DicTag** [XX-net/XX-Net#11593]
用的tunnel， 经常602.
不用的4个前端已经关了。。
Teredo 隧道 | 合格（已连接）
自动调整扫描线程数是off。。
还需要什么信息我再贴上来。。
求大神支招QAQ

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
3.12.11

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
y

* 是否以相关关键词搜索过类似 issues？
y

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:72
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:undefined
worker: h1:12 h2:0
scan-ip-thread-num: 140
ip-quality: 356
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by DicTag** [comment]
这个问题又是好几天了，几乎每次登录都是602，而且即使显示登录成功，打开外网还是上不了，再回到登录界面看到已经跳成602了。。如此反复。。。买的年流量95%要烂掉Orz

**Comment by DicTag** [comment]
#11553 按这个解决了。指定服务器可行。

**Comment by DicTag** [comment]
好吧，5分钟又不行了。。。╮(╯▽╰)╭

**Comment by AnyWAT** [comment]
use-ipv6: auto 改成：仅 IPv6
gws-ip-num: total:undefined ipv4:0 ipv6:72 貌似总 IP数为100？
scan-ip-thread-num: 140 基于上面的总 IP数为100，此140大了些，去整为40-50？
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）

**Comment by AnyWAT** [comment]
保留Cloudflare 前端，X-Tunnel 代理无干预运行数小时的结果：
![image](https://user-images.githubusercontent.com/37962734/47579061-92b0cd80-d97d-11e8-8db8-5695c890ecce.png)

**Comment by Eusen** [comment]
感觉蓝灯挺好用的，这个虽然免费，有点麻烦 ╮(╯-╰)╭

**Comment by AnyWAT** [comment]
买的年流量95%要烂掉了谁赔？😂

**Comment by milanthree** [comment]
切换成原生IPV6？

**Comment by AnyWAT** [comment]
总IP数怎么修改：https://github.com/XX-net/XX-Net/issues/11291#issuecomment-427615357
截图正常8，只是鄙人的PortPreserving: 否
Win7 Win10开全局貌似都没问题。。。开启后在 IE 内查看代理设置，如有则应正常

**Comment by AcTarjan** [comment]
我也是这种问题，登录后开x-tunnel自动切换然后就602，怎么样x-tunnel代表可用啊？？？

**Comment by AnyWAT** [comment]
1、登录 x-tunnel 账户后刷新也立马登入
2、http://127.0.0.1:8085/?module=x_tunnel&menu=status 全局及GAE 前端2栏有流量发生及速度等
