### ISSUE TITLE
光猫桥接/路由模式对IPV6开启的影响……

### ISSUE THREAD

**Issue by zongdream** [XX-net/XX-Net#11590]
针对IPV6连接不畅的问题，建议最好确保光猫是桥接模式，如果光猫设置为路由模式，再连接外部路由器的形式上网，应该会导致IPV6经常性连接不畅……我这里的情况就是这样，时好时坏，直到今天心血来潮彻底修改公司光猫为桥接模式后，IPV6通路好像才稳定……

**Comment by SeaHOH** [comment]
视设备而定吧，不能一概而论。

**Comment by SasamiMasakiJurai** [comment]
首先

有些地方光猫是服务改桥接的

并且

目前国内在推广SDN网关

如果你所在地是SDN网关

那么是无法修改桥接的
