### ISSUE TITLE
在翻墙环境下无法注册google账号

### ISSUE THREAD

**Issue by dovisutu** [XX-net/XX-Net#11592]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
在汇报前已经使用最新3.12.11尝试

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
查看过，暂无合理解决方案

* 是否以相关关键词搜索过类似 issues？
搜索到类似issue，但方法在这里无效

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
问题：在使用GAYProxy代理时注册google账号时即使输入出生日期大于18仍然无法注册，提示（年龄未达要求）在参照类似issue的解决方案改用X-Tunnel代理时无法进入注册界面。（均使用SwichyOmega代理）
经确认在GAYProxy环境下各项指标正常，但在X-Tunnel下浏览器代理设置于CA证书状态为Fail，同时前置代理也为Fail。
诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:94
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:8 h2:0
scan-ip-thread-num: 7
ip-quality: 529
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by dovisutu** [comment]
补充1：连接池h1在0~20间波动，但h2恒为01（在X-Tunnel下）

**Comment by SeaHOH** [comment]
参考 https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file 的格式进行以下配置：
```json
{
    "hosts_direct": [
        "play.google.com",
        "scholar.google.com",
        "scholar.google.com.hk",
        "appengine.google.com",
        "accounts.google.com",
        "mail.google.com"
        ],
    "hosts_gae": []
}
```

如果还是不行，可以临时使用 VPN 或 SS 等其它代理注册。

**Comment by SeaHOH** [comment]
注册成功，你使用的是什么方法或代理？

**Comment by dovisutu** [comment]
注册使用的是按照方法更改了配置的GAEProxy代理

**Comment by SeaHOH** [comment]
恢复配置试试

**Comment by dovisutu** [comment]
谢谢，在恢复设置后可以正常使用了
