### ISSUE TITLE
502 Local URLFetch 'http://www.youtube.com/' failed

### ISSUE THREAD

**Issue by bernardatgh** [XX-net/XX-Net#116]
请帮忙看看是什么问题

GoAgent状态信息
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.3.6
Launcher Version	1.0.8
GoAgent Version	3.1.40
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159|diydgod|diydgod1|diydgod2|diydgod3|diydgod4|diydgod5|diydgod6|diydgod7|diydgod8|diydgod9|ihacat002|ihacat003|ihacat004|ihacat005|ihacat006|ihacat007|ihacat008|ihacat009|ihacat010|zsq4115|zsq25251|zsq00112|kwmmfsa|hfmsgae|pzmslunli|pzmslunli2|pzmslunli3
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	

Apr 07 14:09:07 - [DEBUG]LOG_EXCEPT: get ip:64.15.126.200 t:872, Except:[Errno 9] Bad file descriptor
Apr 07 14:09:07 - [DEBUG] get ip:81.175.29.185 t:872
Apr 07 14:09:07 - [DEBUG] get ip:64.233.163.152 t:872
Apr 07 14:09:07 - [DEBUG] get ip:208.117.224.189 t:873
Apr 07 14:09:07 - [DEBUG] get ip:208.117.229.184 t:873
Apr 07 14:09:07 - [DEBUG] tcp conn 216.58.211.198 fail t:1000
Apr 07 14:09:07 - [DEBUG] tcp conn 64.15.116.58 fail t:1000
Apr 07 14:09:07 - [DEBUG] tcp conn 64.233.167.81 fail t:1000
Apr 07 14:09:07 - [DEBUG] tcp conn 210.158.146.110 fail t:1008
Apr 07 14:09:07 - [DEBUG] tcp conn 173.194.121.109 fail t:1000
Apr 07 14:09:07 - [DEBUG] get ip:213.158.11.151 t:873
Apr 07 14:09:07 - [DEBUG] get ip:213.158.11.32 t:873
Apr 07 14:09:07 - [DEBUG] create_ssl 64.15.114.91 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:07 - [DEBUG] get ip:203.211.0.25 t:873
Apr 07 14:09:07 - [DEBUG] get ip:173.194.214.102 t:874
Apr 07 14:09:07 - [DEBUG] get ip:64.15.126.134 t:874
Apr 07 14:09:07 - [DEBUG] get ip:64.233.176.94 t:874
Apr 07 14:09:07 - [DEBUG] create_ssl 208.117.229.30 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] tcp conn 216.58.211.19 fail t:1007
Apr 07 14:09:08 - [DEBUG] get ip:213.158.11.221 t:874
Apr 07 14:09:08 - [DEBUG] tcp conn 74.125.69.149 fail t:1000
Apr 07 14:09:08 - [DEBUG] tcp conn 203.211.0.39 fail t:1000
Apr 07 14:09:08 - [DEBUG] get ip:173.194.42.73 t:874
Apr 07 14:09:08 - [DEBUG] tcp conn 64.233.162.116 fail t:1000
Apr 07 14:09:08 - [DEBUG] create_ssl 74.125.141.196 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] get ip:74.125.192.60 t:874
Apr 07 14:09:08 - [DEBUG] create_ssl 208.117.224.165 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] create_ssl 173.194.121.60 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] get ip:1.179.248.163 t:875
Apr 07 14:09:08 - [DEBUG] create_ssl 64.15.126.200 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] tcp conn 64.233.163.152 fail t:1000
Apr 07 14:09:08 - [DEBUG] create_ssl 208.117.224.189 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] create_ssl 81.175.29.185 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] get ip:64.15.119.141 t:875
Apr 07 14:09:08 - [DEBUG] create_ssl 208.117.229.184 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] tcp conn 213.158.11.151 fail t:1000
Apr 07 14:09:08 - [DEBUG] get ip:203.165.14.237 t:875
Apr 07 14:09:08 - [DEBUG] create_ssl 213.158.11.32 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:08 - [DEBUG] get ip:64.233.184.144 t:875
Apr 07 14:09:08 - [DEBUG] tcp conn 203.211.0.25 fail t:1000
Apr 07 14:09:08 - [DEBUG] tcp conn 173.194.214.102 fail t:1000
Apr 07 14:09:08 - [DEBUG] tcp conn 64.15.126.134 fail t:1000
Apr 07 14:09:08 - [DEBUG] tcp conn 64.233.176.94 fail t:1000
Apr 07 14:09:08 - [DEBUG] get ip:64.15.119.203 t:875
Apr 07 14:09:08 - [DEBUG] get ip:208.117.227.151 t:877
Apr 07 14:09:09 - [DEBUG] get ip:210.139.253.93 t:877
Apr 07 14:09:09 - [DEBUG] get ip:123.205.251.116 t:877
Apr 07 14:09:09 - [DEBUG] get ip:64.15.119.214 t:877
Apr 07 14:09:09 - [DEBUG] get ip:106.162.198.103 t:877
Apr 07 14:09:09 - [DEBUG] tcp conn 213.158.11.221 fail t:1000
Apr 07 14:09:09 - [DEBUG] tcp conn 173.194.42.73 fail t:1000
Apr 07 14:09:09 - [DEBUG] get ip:216.58.211.187 t:877
Apr 07 14:09:09 - [DEBUG] get ip:199.87.241.56 t:877
Apr 07 14:09:09 - [DEBUG] tcp conn 74.125.192.60 fail t:997
Apr 07 14:09:09 - [DEBUG] get ip:210.245.14.99 t:878
Apr 07 14:09:09 - [DEBUG] get ip:216.58.221.36 t:878
Apr 07 14:09:09 - [DEBUG] tcp conn 1.179.248.163 fail t:1000
Apr 07 14:09:09 - [DEBUG] get ip:111.168.255.114 t:878
Apr 07 14:09:09 - [DEBUG] get ip:64.233.171.137 t:878
Apr 07 14:09:09 - [DEBUG] get ip:173.194.204.191 t:878
Apr 07 14:09:09 - [DEBUG]LOG_EXCEPT: get ip:74.125.229.27 t:878, Except:[Errno 9] Bad file descriptor
Apr 07 14:09:09 - [DEBUG] tcp conn 64.15.119.141 fail t:1000
Apr 07 14:09:09 - [DEBUG] get ip:106.162.192.153 t:878
Apr 07 14:09:09 - [DEBUG] get ip:123.205.251.88 t:878
Apr 07 14:09:09 - [DEBUG] get ip:210.245.14.162 t:878
Apr 07 14:09:09 - [DEBUG] tcp conn 203.165.14.237 fail t:1000
Apr 07 14:09:09 - [DEBUG] get ip:216.58.216.131 t:878
Apr 07 14:09:09 - [DEBUG] create_ssl 64.233.184.144 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:09 - [DEBUG] create_ssl 64.15.119.203 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:09 - [DEBUG] tcp conn 208.117.227.151 fail t:1000
Apr 07 14:09:10 - [DEBUG] tcp conn 210.139.253.93 fail t:1000
Apr 07 14:09:10 - [DEBUG] tcp conn 123.205.251.116 fail t:1000
Apr 07 14:09:10 - [DEBUG] tcp conn 64.15.119.214 fail t:1000
Apr 07 14:09:10 - [DEBUG] tcp conn 106.162.198.103 fail t:1000
Apr 07 14:09:10 - [DEBUG] tcp conn 216.58.211.187 fail t:1001
Apr 07 14:09:10 - [DEBUG] create_ssl 199.87.241.56 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] create_ssl 210.245.14.99 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] create_ssl 216.58.221.36 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] tcp conn 111.168.255.114 fail t:1000
Apr 07 14:09:10 - [DEBUG] create_ssl 64.233.171.137 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] create_ssl 74.125.229.27 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] create_ssl 173.194.204.191 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] create_ssl 106.162.192.153 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] tcp conn 123.205.251.88 fail t:1000
Apr 07 14:09:10 - [DEBUG] tcp conn 210.245.14.162 fail t:997
Apr 07 14:09:10 - [DEBUG] create_ssl 216.58.216.131 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:10 - [DEBUG] get ip:210.158.146.218 t:252
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.240 t:521
Apr 07 14:09:11 - [DEBUG] get ip:210.158.146.106 t:524
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.241 t:629
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.212 t:629
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.216 t:631
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.249 t:632
Apr 07 14:09:11 - [DEBUG] get ip:210.158.146.216 t:632
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.234 t:638
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.245 t:639
Apr 07 14:09:11 - [DEBUG] get ip:210.245.14.35 t:644
Apr 07 14:09:11 - [DEBUG] tcp conn 210.158.146.218 fail t:1001
Apr 07 14:09:11 - [DEBUG] get ip:114.4.41.227 t:645
Apr 07 14:09:11 - [DEBUG] get ip:210.158.146.245 t:717
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.240 fail t:1000
Apr 07 14:09:12 - [DEBUG] get ip:114.4.41.218 t:723
Apr 07 14:09:12 - [DEBUG] tcp conn 210.158.146.106 fail t:1001
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.241 fail t:1000
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.212 fail t:1000
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.216 fail t:1000
Apr 07 14:09:12 - [DEBUG] get ip:114.4.41.229 t:782
Apr 07 14:09:12 - [DEBUG] get ip:208.117.224.145 t:862
Apr 07 14:09:12 - [DEBUG] get ip:208.117.228.89 t:862
Apr 07 14:09:12 - [DEBUG] get ip:123.205.251.84 t:862
Apr 07 14:09:12 - [DEBUG] get ip:80.64.175.123 t:862
Apr 07 14:09:12 - [DEBUG] get ip:64.233.161.133 t:863
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.249 fail t:998
Apr 07 14:09:12 - [DEBUG] get ip:208.117.253.120 t:863
Apr 07 14:09:12 - [DEBUG] get ip:216.58.216.186 t:863
Apr 07 14:09:12 - [DEBUG] get ip:210.139.253.35 t:863
Apr 07 14:09:12 - [DEBUG] get ip:216.58.211.198 t:863
Apr 07 14:09:12 - [DEBUG] get ip:210.158.146.110 t:863
Apr 07 14:09:12 - [DEBUG] tcp conn 210.158.146.216 fail t:1001
Apr 07 14:09:12 - [DEBUG] get ip:64.233.167.81 t:864
Apr 07 14:09:12 - [DEBUG] get ip:64.15.116.58 t:866
Apr 07 14:09:12 - [DEBUG]LOG_EXCEPT: get ip:173.194.121.109 t:866, Except:[Errno 9] Bad file descriptor
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.234 fail t:1000
Apr 07 14:09:12 - [DEBUG] tcp conn 114.4.41.245 fail t:999
Apr 07 14:09:12 - [DEBUG] get ip:64.15.114.91 t:868
Apr 07 14:09:12 - [DEBUG] create_ssl 210.245.14.35 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:12 - [DEBUG] create_ssl 114.4.41.227 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:12 - [DEBUG] tcp conn 210.158.146.245 fail t:1002
Apr 07 14:09:13 - [DEBUG] get ip:208.117.229.30 t:869
Apr 07 14:09:13 - [DEBUG] get ip:216.58.211.19 t:869
Apr 07 14:09:13 - [DEBUG] tcp conn 114.4.41.218 fail t:1002
Apr 07 14:09:13 - [DEBUG] get ip:74.125.69.149 t:869
Apr 07 14:09:13 - [DEBUG] tcp conn 114.4.41.229 fail t:1001
Apr 07 14:09:13 - [DEBUG] get ip:203.211.0.39 t:869
Apr 07 14:09:13 - [WARNING] create tcp connection fail.
Apr 07 14:09:13 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 07 14:09:13 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 07 14:09:13 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 07 14:09:13 - [WARNING] create tcp connection fail.
Apr 07 14:09:13 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 07 14:09:13 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 07 14:09:13 - [WARNING] create tcp connection fail.
Apr 07 14:09:13 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 07 14:09:13 - [DEBUG] tcp conn 208.117.224.145 fail t:1002
Apr 07 14:09:13 - [DEBUG] tcp conn 208.117.228.89 fail t:1001
Apr 07 14:09:13 - [DEBUG] tcp conn 123.205.251.84 fail t:1000
Apr 07 14:09:13 - [DEBUG] get ip:74.125.141.196 t:869
Apr 07 14:09:13 - [DEBUG] create_ssl 80.64.175.123 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] create_ssl 64.233.161.133 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] create_ssl 208.117.253.120 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] tcp conn 216.58.216.186 fail t:1002
Apr 07 14:09:13 - [DEBUG] create_ssl 210.139.253.35 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] create_ssl 216.58.211.198 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] get ip:64.233.162.116 t:871
Apr 07 14:09:13 - [DEBUG] create_ssl 210.158.146.110 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] get ip:173.194.121.60 t:871
Apr 07 14:09:13 - [DEBUG] get ip:208.117.224.165 t:872
Apr 07 14:09:13 - [DEBUG] create_ssl 64.233.167.81 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] tcp conn 64.15.116.58 fail t:1001
Apr 07 14:09:13 - [DEBUG] get ip:64.15.126.200 t:872
Apr 07 14:09:13 - [DEBUG] create_ssl 173.194.121.109 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:13 - [DEBUG] tcp conn 64.15.114.91 fail t:1000
Apr 07 14:09:13 - [DEBUG] get ip:81.175.29.185 t:872
Apr 07 14:09:13 - [DEBUG] get ip:64.233.163.152 t:872
Apr 07 14:09:13 - [DEBUG] get ip:208.117.224.189 t:873
Apr 07 14:09:14 - [DEBUG] tcp conn 208.117.229.30 fail t:1001
Apr 07 14:09:14 - [DEBUG] tcp conn 216.58.211.19 fail t:1009
Apr 07 14:09:14 - [DEBUG] get ip:208.117.229.184 t:873
Apr 07 14:09:14 - [DEBUG] tcp conn 74.125.69.149 fail t:1000
Apr 07 14:09:14 - [DEBUG] get ip:213.158.11.151 t:873
Apr 07 14:09:14 - [DEBUG] get ip:213.158.11.32 t:873
Apr 07 14:09:14 - [DEBUG] tcp conn 203.211.0.39 fail t:1003
Apr 07 14:09:14 - [DEBUG] get ip:203.211.0.25 t:873
Apr 07 14:09:14 - [DEBUG] tcp conn 74.125.141.196 fail t:1000
Apr 07 14:09:14 - [DEBUG] get ip:173.194.214.102 t:874
Apr 07 14:09:14 - [DEBUG] get ip:64.15.126.134 t:874
Apr 07 14:09:14 - [DEBUG] get ip:64.233.176.94 t:874
Apr 07 14:09:14 - [DEBUG] get ip:213.158.11.221 t:874
Apr 07 14:09:14 - [DEBUG] get ip:173.194.42.73 t:874
Apr 07 14:09:14 - [DEBUG]LOG_EXCEPT: get ip:74.125.192.60 t:874, Except:[Errno 9] Bad file descriptor
Apr 07 14:09:14 - [DEBUG] tcp conn 64.233.162.116 fail t:1000
Apr 07 14:09:14 - [DEBUG] get ip:1.179.248.163 t:875
Apr 07 14:09:14 - [DEBUG] tcp conn 173.194.121.60 fail t:1000
Apr 07 14:09:14 - [DEBUG] tcp conn 208.117.224.165 fail t:1000
Apr 07 14:09:14 - [DEBUG] get ip:64.15.119.141 t:875
Apr 07 14:09:14 - [DEBUG] get ip:203.165.14.237 t:875
Apr 07 14:09:14 - [DEBUG] tcp conn 64.15.126.200 fail t:1000
Apr 07 14:09:14 - [DEBUG] get ip:64.233.184.144 t:875
Apr 07 14:09:14 - [DEBUG] get ip:64.15.119.203 t:875
Apr 07 14:09:14 - [DEBUG] get ip:208.117.227.151 t:877
Apr 07 14:09:14 - [DEBUG] get ip:210.139.253.93 t:877
Apr 07 14:09:14 - [DEBUG] create_ssl 81.175.29.185 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:14 - [DEBUG] tcp conn 64.233.163.152 fail t:993
Apr 07 14:09:14 - [DEBUG] create_ssl 208.117.224.189 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] tcp conn 208.117.229.184 fail t:1001
Apr 07 14:09:15 - [DEBUG] tcp conn 213.158.11.151 fail t:995
Apr 07 14:09:15 - [DEBUG] tcp conn 213.158.11.32 fail t:1001
Apr 07 14:09:15 - [DEBUG] tcp conn 203.211.0.25 fail t:1000
Apr 07 14:09:15 - [DEBUG] create_ssl 173.194.214.102 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] create_ssl 64.233.176.94 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] tcp conn 64.15.126.134 fail t:1001
Apr 07 14:09:15 - [DEBUG] create_ssl 213.158.11.221 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] create_ssl 173.194.42.73 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] create_ssl 74.125.192.60 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] create_ssl 1.179.248.163 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] tcp conn 64.15.119.141 fail t:1003
Apr 07 14:09:15 - [DEBUG] create_ssl 203.165.14.237 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] create_ssl 64.15.119.203 fail:Error connecting to HTTP proxy 127.0.0.1:1080: [Errno 10061] c:0 h:0
Apr 07 14:09:15 - [DEBUG] tcp conn 64.233.184.144 fail t:1013
Apr 07 14:09:15 - [DEBUG] tcp conn 210.139.253.93 fail t:998
Apr 07 14:09:15 - [DEBUG] tcp conn 208.117.227.151 fail t:997
Apr 07 14:09:16 - [DEBUG] get ip:123.205.251.116 t:877
Apr 07 14:09:16 - [DEBUG] get ip:64.15.119.214 t:877
Apr 07 14:09:16 - [DEBUG] get ip:106.162.198.103 t:877
Apr 07 14:09:16 - [DEBUG] get ip:216.58.211.187 t:877
Apr 07 14:09:16 - [DEBUG] get ip:199.87.241.56 t:877
Apr 07 14:09:16 - [DEBUG] get ip:210.245.14.99 t:878
Apr 07 14:09:16 - [DEBUG] get ip:216.58.221.36 t:878
Apr 07 14:09:16 - [DEBUG] get ip:111.168.255.114 t:878
Apr 07 14:09:16 - [DEBUG] get ip:210.158.146.218 t:252
Apr 07 14:09:16 - [DEBUG] get ip:114.4.41.240 t:521
Apr 07 14:09:16 - [DEBUG] get ip:210.158.146.106 t:524
Apr 07 14:09:16 - [DEBUG] get ip:114.4.41.241 t:629
Apr 07 14:09:17 - [DEBUG] tcp conn 123.205.251.116 fail t:999
Apr 07 14:09:17 - [DEBUG] get ip:114.4.41.212 t:629
Apr 07 14:09:17 - [DEBUG] tcp conn 64.15.119.214 fail t:1007
Apr 07 14:09:17 - [DEBUG] get ip:114.4.41.216 t:631
Apr 07 14:09:17 - [DEBUG] tcp conn 106.162.198.103 fail t:998

**Comment by xxnet** [comment]
这个问题1.7.x已经解决，请下载最新版。
这几天没有问题就会推送新版自动升级。

2015-04-07 2:11 GMT-04:00 bernardatgh <notifications@github.com>:
