### ISSUE TITLE
增加 ipv6 数后，XX-net 就打不开

### ISSUE THREAD

**Issue by MitchellClark666** [XX-net/XX-Net#11601]
参考 #10184 二楼
在config.json 添加 "max_good_ip_num": 200,
XX-net 就打不开了啊，请问是什么原因呢？

![default](https://user-images.githubusercontent.com/13077075/47657507-2bd52380-dbcc-11e8-9d63-000311a2c186.JPG)

**Comment by AnyWAT** [comment]
去掉14行末的逗号😂

**Comment by MitchellClark666** [comment]
> 去掉14行末的逗号（收尾中、大括号前最后一行没有标点）😂

感谢老铁，可以使用了
