### ISSUE TITLE
使用pac智能代理时，游览器智能代理设置fail

### ISSUE THREAD

**Issue by wangshantao** [XX-net/XX-Net#11605]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
3.12.11

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
Y

* 是否以相关关键词搜索过类似 issues？
与#9126情况一样，但是我用的是最新版本。之前的版本似乎没这个问题

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
使用pac智能代理时，游览器智能代理设置fail。与#9126情况完全一样

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:1 h2:0
scan-ip-thread-num: 9
ip-quality: 442
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
使用pac智能代理时，游览器智能代理设置fail。与#9126情况完全一样：无法使用全局PAC智能代理 
😂前者是非系统全局的浏览器内，后者乃系统全局
SwitchyOmega 可自建PAC情景模式：http://127.0.0.1:8086/proxy.pac
proxy_state: Fail
ca_state: Fail
临时切换到 GAE-Proxy自动切换，添加SwitchyOmega 内（貌似软件检测代理、证书的）未加载资源 *.deja.com 走GAE-Proxy
Appids_Out_Of_Quota: true
Using_Public_Appid: true
在用公共 ID但（某 ID）流量用尽？不会要软件重开才自动换 ID？

**Comment by SeaHOH** [comment]
开启 smart_router 模块没有？

**Comment by wangshantao** [comment]
> 开启 smart_router 模块没有？

开启以后正常了。
