### ISSUE TITLE
总是时不时就断开，能找到的方法都试过了，还是不行，请帮忙看看

### ISSUE THREAD

**Issue by hisenko1** [XX-net/XX-Net#11603]
如题，请帮忙看看，日志太长了，我转成了文件上传，日志包括出问题和正常后的情况。

再次感谢！
[日志.txt](https://github.com/XX-net/XX-Net/files/2528927/default.txt)

`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:37
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:10 h2:0
scan-ip-thread-num: 10
ip-quality: 711
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by AnyWAT** [comment]
能找到的方法都试过了也许没救了😂
几乎从不时不时就断开的 #11291

**Comment by SeaHOH** [comment]
首先，不要使用全局 GAE 代理，使用自动规则或者智能代理端口；
其次，出现长时间 IPv6 失败时，试试重新拨号，或者重启路由器。

**Comment by gosex** [comment]
把 代理服务器 换成 手动 的试试，
至少比自动的稳定 ：）

**Comment by AnyWAT** [comment]
😂楼主是GAE不正常，楼上说的貌似有关GAE之后的X-Tunnel
