### ISSUE TITLE
Appid创建时的区域选择问题

### ISSUE THREAD

**Issue by YunXuyun** [XX-net/XX-Net#11607]
很久以前创建的appid选的都是区域都是us-central，翻墙出来之后是美国ip
今天换了新帐号之后创建appid，区域选了asia-east1，但是翻墙出来之后查询本机ip地址为何还是显示为美国？
想请教下这是怎么回事？

**Comment by SeaHOH** [comment]
就是这么回事，代理出口不会变，只有那一个。

**Comment by YunXuyun** [comment]
@SeaHOH 谢谢解答~
