### ISSUE TITLE
Mac 系统, 升级 python 3.7 版本之后, 删除了系统自带的 2.7, 从此可以打开 start, 但是菜单栏无法显示 X 的标志

### ISSUE THREAD

**Issue by syliuguang** [XX-net/XX-Net#11606]
Mac 系统, 升级 python 3.7 版本之后, 删除了系统自带的 2.7, 从此可以打开 start, 但是菜单栏无法显示 X 的标志. 因此无法设置自动或者全局代理. 不知道怎么设置.

**Comment by SeaHOH** [comment]
XX-Net 尚未支持 Python3 的稳定版本，之前那个已经没有开发了。

> Mac 系统, 升级 python 3.7 版本之后, 删除了系统自带的 2.7, 从此可以打开 start

如果你确定 XX-Net 代理模块已正常运行，那么这个描述就是错误的。

**Comment by AnyWAT** [comment]
Windows 10系统也是，手动解决：在 IE内设置系统全局代理（如在系统设置内设置则无需填写协议），设置正确会在XX-Net 菜单栏准确显示 X 的标志
全局GAE：HTTP 8087
全局X-TUNNEL：HTTP 1080
全局智能路由：HTTP 8086
全局PAC：http://127.0.0.1:8086/proxy.pac
取消全局代理：。。。

**Comment by syliuguang** [comment]
谢谢，我已经冲刷系统了，现在又可以像以前那样打开 xxnet 了， 大不了以后不用终端打开 python 3.7 了。
