### ISSUE TITLE
今天XX-Net无法使用

### ISSUE THREAD

**Issue by h188cm** [XX-net/XX-Net#11604]
最近更新放慢了？

**Comment by AnyWAT** [comment]
更新也有计划、快慢？😂试试：#11291

**Comment by Sirius21c** [comment]
一直断啊......

**Comment by AnyWAT** [comment]
据说 #11291 随时连上，不手动退出就一直（😂代理正常）下不来🤣

**Comment by SeaHOH** [comment]
网络状况如此，XX-Net 没有需要更新的地方。
因为 GWF 还没有封 v6 IP，所以只要你有 IPv6 连接就能使用。

参考过往 issue 检查调整系统、路由器以及 Modem 的设置，确保 IPv6 连接正常。

楼上这位一直以为大家和他在一个局域网内。

**Comment by AnyWAT** [comment]
如此看来，内网中的内网才是好网🤣

**Comment by SeaHOH** [comment]
> 好网

到底是哪个说的这个话，慢慢找，我还没有删除过多少自己写的东西。
不懂的东西真的不要装，显得肤浅。
