### ISSUE TITLE
证书时不时的Fail，请问是什么问题？

### ISSUE THREAD

**Issue by rambosir** [XX-net/XX-Net#11609]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:89
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 33
ip-quality: 536
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 如果问题得到解决，请务必回复相关情况，谢谢。

![image](https://user-images.githubusercontent.com/1431989/47828672-0e1be000-ddbf-11e8-8bb5-fdb5ba68cc69.png)

**Comment by SeaHOH** [comment]
你是如何设置的代理？对使用有不良影响吗？

**Comment by rambosir** [comment]
> 你是如何设置的代理？对使用有不良影响吗？
![image](https://user-images.githubusercontent.com/1431989/47833299-fb140a80-ddd4-11e8-97bc-a5f0db4dccf7.png)
![image](https://user-images.githubusercontent.com/1431989/47833317-13842500-ddd5-11e8-9e9a-d2a4086318ee.png)

证书Fail时，无法正常使用（google无法访问）。

ps：平时一般就用google搜搜资料而已

**Comment by SeaHOH** [comment]
从目前提供的信息来看，无法找到符合的解释。
如果你还有相关信息，可以继续贴在这里。

**Comment by AnyWAT** [comment]
截图SwitchyOmega 的图标上没有附加数字，检查GAE自动切换下的 *.deja.com 必走GAE 
scan-ip-thread-num: 33 ——貌似已关闭某开关？
gws-ip-num: total:undefined ipv4:0 ipv6:89 ——undefined 至少是100，但有效89没达到总数100，与上面某开关已关闭不符，或应再增大扫描线程数（保证自动维持有效等于总 IP数）？
worker: h1:0 h2:0 ——貌似程序已晕，或手动检查 IP，不行则再启动一个（省事：可挤出前面已晕那个）

**Comment by Zhangpanx** [comment]
安装了证书后没遇到过这个问题

**Comment by AnyWAT** [comment]
ON 改成 OFF
总 IP数才100，最大扫描线程数30-50足矣
参考：#11291

**Comment by AnyWAT** [comment]
遵循 #11291 ，开机不足10分钟的效果：
![default](https://user-images.githubusercontent.com/37962734/47891116-c3689980-de8c-11e8-91e1-5078fc7f44f6.png)

**Comment by SeaHOH** [comment]
如果证书 Fail 是自己恢复的，你没有进行过证书相关操作，那么按以下操作试试。
新建个 Chrome 用户，然后只安装 SwitchyOmega，看看是否会继续出现证书 Fail。

**Comment by SeaHOH** [comment]
关闭后仍可回复
