### ISSUE TITLE
显示“一切正常，你可以访问真正的互联网了”，但实际上连不上

### ISSUE THREAD

**Issue by sky2917** [XX-net/XX-Net#11619]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:9
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:5 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Nov 02 21:29:05.774 - [DEBUG] report_connect_fail:2607:f8b0:401c:5::7

Nov 02 21:29:05.774 - [DEBUG] connect 2607:f8b0:401c:5::7 fail:error("conn fail, sni:pension-horror.org, top:theta-trees-178408.appspot.com e:timeout('timed out',)",)

Nov 02 21:29:05.774 - [DEBUG] recheck_ip:2800:200:2008:10c4::f restore ok

Nov 02 21:29:05.775 - [DEBUG] 2800:200:2008:10c4::f worker close:keep alive

Nov 02 21:29:07.301 - [DEBUG] report_connect_fail:2001:4e8:0:b045::10

Nov 02 21:29:07.301 - [DEBUG] connect 2001:4e8:0:b045::10 fail:error("conn fail, sni:nature-weird-difference.com, top:theta-trees-178408.appspot.com e:timeout('timed out',)",)

Nov 02 21:29:07.859 - [DEBUG] GAE GET https://twitter.com/ from:127.0.0.1:51616

Nov 02 21:29:08.371 - [WARNING] task POST None /_gh/ timeout

Nov 02 21:29:08.371 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Nov 02 21:29:08.371 - [WARNING] gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatus

Nov 02 21:29:08.371 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatusgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatusgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatus"

Nov 02 21:29:08.371 - [WARNING] GAE POST https://clients4.google.com/chrome-sync/experimentstatus request fail:"600:gae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatusgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatusgae_exception:'600:fetch gae fail' https://clients4.google.com/chrome-sync/experimentstatus"

Nov 02 21:29:09.106 - [WARNING] 2001:8002:e21:ef01::11 h1_request:Exception('time out',) inactive_time:19 task.timeout:15

Nov 02 21:29:09.106 - [WARNING] 2001:8002:e21:ef01::11 trace: 0:connect, 2342:init, 1086:request,:16000, processed:0, transfered:0, sni:kidmovieboot.org

Nov 02 21:29:09.106 - [WARNING] retry_task_cb: POST None/_gh/

Nov 02 21:29:09.106 - [WARNING] POST None/_gh/ response_fail:retry timeout:237

Nov 02 21:29:09.106 - [DEBUG] 2001:8002:e21:ef01::11 worker close:down fail

Nov 02 21:29:10.356 - [DEBUG] GAE GET https://www.youtube.com/ from:127.0.0.1:51630

Nov 02 21:29:11.344 - [WARNING] 2001:8002:e21:ef01::f h1_request:Exception('time out',) inactive_time:20 task.timeout:15

Nov 02 21:29:11.344 - [WARNING] 2001:8002:e21:ef01::f trace: 0:connect, 3488:init, 1083:request,:16084, processed:0, transfered:0, sni:theory.passion.engineering.com

Nov 02 21:29:11.344 - [WARNING] retry_task_cb: POST None/_gh/

Nov 02 21:29:11.344 - [WARNING] POST None/_gh/ response_fail:retry timeout:229

Nov 02 21:29:11.344 - [DEBUG] 2001:8002:e21:ef01::f worker close:down fail

Nov 02 21:29:11.604 - [WARNING] task POST None /_gh/ timeout

Nov 02 21:29:11.604 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Nov 02 21:29:11.604 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/oauth2/v4/token

Nov 02 21:29:11.678 - [DEBUG] GAE GET https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA== from:127.0.0.1:51645

Nov 02 21:29:12.789 - [WARNING] 2a02:ce0:1:25::c h1_request:Exception('time out',) inactive_time:42 task.timeout:40

Nov 02 21:29:12.789 - [WARNING] 2a02:ce0:1:25::c trace: 0:connect, 1048:init, 1065:request,:40009, processed:0, transfered:0, sni:nurse.platform.net

Nov 02 21:29:12.789 - [WARNING] retry_task_cb: POST None/_gh/

Nov 02 21:29:12.789 - [WARNING] POST None/_gh/ response_fail:retry timeout:247

Nov 02 21:29:12.789 - [DEBUG] 2a02:ce0:1:25::c worker close:down fail

Nov 02 21:29:12.815 - [WARNING] task POST None /_gh/ timeout

Nov 02 21:29:12.815 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Nov 02 21:29:12.815 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA==

Nov 02 21:29:12.815 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA==gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA==gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA=="

Nov 02 21:29:12.815 - [WARNING] GAE GET https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA== request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA==gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA==gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZjETdXQjUiykjLch9HWgkIy32YfgcJCMtywL2YiQjLcML84YkFA=="

Nov 02 21:29:13.551 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token from:127.0.0.1:51662

Nov 02 21:29:13.625 - [WARNING] not enough ip

Nov 02 21:29:14.229 - [WARNING] task POST None /_gh/ timeout

Nov 02 21:29:14.230 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Nov 02 21:29:14.230 - [WARNING] gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3

Nov 02 21:29:14.230 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3"

Nov 02 21:29:14.230 - [WARNING] GAE POST https://android.clients.google.com/c2dm/register3 request fail:"600:gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3gae_exception:'600:fetch gae fail' https://android.clients.google.com/c2dm/register3"

Nov 02 21:29:14.692 - [DEBUG] GAE GET https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZwxW6vVdYDI8jLd0fyRQkIy3XvitLJCMt_adG1CQU from:127.0.0.1:51670

Nov 02 21:29:15.099 - [WARNING] 2001:8002:e21:ef01::c h1_request:Exception('time out',) inactive_time:18 task.timeout:15

Nov 02 21:29:15.099 - [WARNING] 2001:8002:e21:ef01::c trace: 0:connect, 1655:init, 1052:request,:16121, processed:0, transfered:0, sni:salt.investment.com

Nov 02 21:29:15.099 - [WARNING] retry_task_cb: POST None/_gh/

Nov 02 21:29:15.099 - [WARNING] POST None/_gh/ response_fail:retry timeout:232

Nov 02 21:29:15.099 - [DEBUG] 2001:8002:e21:ef01::c worker close:down fail

Nov 02 21:29:15.990 - [INFO] scan_ip add ip:2806:1050:cfff:6::c time:1351 h2:0

Nov 02 21:29:15.990 - [INFO] remove_slowest_ip:2607:f8b0:401c:5::7 handshake_time:806, fails:8

Nov 02 21:29:16.956 - [WARNING] task POST None /_gh/ timeout

Nov 02 21:29:16.956 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Nov 02 21:29:16.956 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZ0qvq9y3Z5P8jLch9HWgkIy32YfgcJCMtywL2YiQjLSubt4YkFA==

**Comment by SeaHOH** [comment]
> gws-ip-num: total:100 ipv4:0 ipv6:9

可用 IP 数量太少

**Comment by sky2917** [comment]
> > gws-ip-num: total:100 ipv4:0 ipv6:9
> 
> 可用 IP 数量太少

那该怎么设置呢？

**Comment by SeaHOH** [comment]
如果一直这样少，请逐渐提高扫描线程数直到 IP 能维持 50 个以上，扫描数尽量不要超过 100。

**Comment by SeaHOH** [comment]
关闭后仍可回复
