### ISSUE TITLE
某些网站的证书安全问题

### ISSUE THREAD

**Issue by winters-z** [XX-net/XX-Net#11617]
如图，有些网站显示有证书安全问题，可以不管他么
<img width="274" alt="default" src="https://user-images.githubusercontent.com/32010503/47908348-ff6d2000-dec7-11e8-8711-c05f5dc32ea8.png">
![1](https://user-images.githubusercontent.com/32010503/47908358-0300a700-dec8-11e8-9588-4955c4a3274c.png)

**Comment by AnyWAT** [comment]
全自动可疑证书吊销工具/全自動可疑憑證撤銷工具: Revoke China certificates. https://github.com/chengr28/RevokeChinaCerts

**Comment by winters-z** [comment]
OK 谢谢
