### ISSUE TITLE
如何在第一次启动前禁止自动升级？

### ISSUE THREAD

**Issue by ivysrono** [XX-net/XX-Net#1161]
check_update: dont-check
webgui修改后是这个参数，但是如何在启动前内置？
有时候来不及改就已经在升级了。

**Comment by simonasd** [comment]
土办法：断网（物理断网或防火墙限制）状态下运行，修改设置，然后再联网。

便捷方法：在data中预置一个设置为dont-check的config文件

麻烦的方法：修改launcher文件夹下的py，改变更新设置的默认值。

**Comment by renyouguo** [comment]
@simonasd 
        update_rule = config.get(["update", "check_update"], "dont-check")
是不是这样改？

**Comment by simonasd** [comment]
@renyouguo 是的，修改之后，默认设置就变成不更新了

**Comment by renyouguo** [comment]
谢谢。
    if config.get(["modules", "launcher", "popup_webui"], 0) == 1:
最后的== 1:是否要修改？

**Comment by simonasd** [comment]
@renyouguo 改了 == 1就改变判断的逻辑了。 get(A , B)中的B就是默认值，需要的话修改这个即可。

**Comment by renyouguo** [comment]
谢谢。
最后还有个开机自启没找到在哪里。

**Comment by simonasd** [comment]
@renyouguo 添加/删除自启的代码在web_control.py中调用的。当修改相关设置时触发。你可以模仿那个代码来自行调用，放到你需要的地方。
