### ISSUE TITLE
请问这个是什么问题？

### ISSUE THREAD

**Issue by branifern** [XX-net/XX-Net#11610]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:66
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:11 h2:0
scan-ip-thread-num: 1
ip-quality: 515
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
gws-ip-num: total:100 ipv4:0 ipv6:66
scan-ip-thread-num: 1
试试关闭某开关 #11291

**Comment by branifern** [comment]
> gws-ip-num: total:100 ipv4:0 ipv6:66
> scan-ip-thread-num: 1
> 试试关闭某开关 #11291

我关闭了自动调整扫描数线程，最大扫描线程数30，但是还是不行怎么办

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by branifern** [comment]
> netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

什么意思啊

**Comment by AnyWAT** [comment]
命令提示符 cmd 内运行 netsh int ipv6 show teredo

**Comment by branifern** [comment]
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 192.168.1.4:59250
外部 NAT 映射    : 125.122.14.79:59250



XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 201
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by branifern** [comment]
> 命令提示符 cmd 内运行 netsh int ipv6 show teredo

类型 : enterpriseclient
服务器名称 : win1711.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : qualified
客户端类型 : teredo client
网络 : managed
NAT : restricted (port)
NAT 特殊行为 : UPNP: 否，PortPreserving: 是
本地映射 : 192.168.1.4:59250
外部 NAT 映射 : 125.122.14.79:59250

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 201
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
外部 NAT 映射 : 125.122.14.79:59250 暴露隐私

**Comment by branifern** [comment]
> 外部 NAT 映射 : 125.122.14.79:59250 暴露隐私

那要怎么办啊

**Comment by AnyWAT** [comment]
删楼或编辑楼贴，楼贴右上角3点

**Comment by branifern** [comment]
> 删楼或编辑楼贴，楼贴右上角3点

删掉了，但是问题怎么解决

**Comment by AnyWAT** [comment]
但是问题怎么解决—— #11291 基本已说，重点：关闭某开关（有人忘记提交，等于没操作😂）
is-idle: 1
proxy_state: Fail
ca_state: Fail
貌似程序已晕，再开一个XX-Net（省事：可挤出已晕的前面那个）

**Comment by branifern** [comment]
> 但是问题怎么解决—— #11291 基本已说，重点：关闭某开关（有人忘记提交，等于没操作😂）
> is-idle: 1
> proxy_state: Fail
> ca_state: Fail
> 貌似程序已晕，再开一个XX-Net（省事：可挤出已晕的前面那个）

开关我是提交的，再开一个的话就是现在这个要保留吗

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com.
管理权限运行 netsh int ipv6 set teredo enterpriseclient default
再运行 netsh int ipv6 show teredo 自己看结果是否与第一行一样？

**Comment by AnyWAT** [comment]
再开一个的话就是现在这个要保留吗——省事（不用结束😂）：可挤出已晕的前面那个

**Comment by branifern** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com.
> 管理权限运行 netsh int ipv6 set teredo enterpriseclient default
> 再运行 netsh int ipv6 show teredo 自己看结果是否与第一行一样？

服务器名称是一样的

**Comment by AnyWAT** [comment]
#11291 已说：关闭某开关、增大总 IP数（相应地增大扫描线程数）、增大连接接收缓冲大小
遵循了 #11291 ，刚刚开机不到10分钟的效果：
![default](https://user-images.githubusercontent.com/37962734/47891765-95d11f80-de8f-11e8-8146-496af326b9a3.png)

**Comment by branifern** [comment]
> 我关闭了自动调整扫描数线程，最大扫描线程数30，但是还是不行怎么办—— #11291 已说：关闭某开关、增大总 IP数（相应地增大扫描线程数）、增大连接接收缓冲大小
> [#11609 (comment)](https://github.com/XX-net/XX-Net/issues/11609#issuecomment-435254400)

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:5 h2:0
scan-ip-thread-num: 100
ip-quality: 240
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


开了第二个还是不行啊

**Comment by AnyWAT** [comment]
gws-ip-num: total:100 ipv4:0 ipv6:100 增大总 IP数
scan-ip-thread-num: 100 适用于较大的总 IP数，否则对总 IP数100来说太大？
proxy_state: Fail
ca_state: Fail——SwitchyOmega 的图标上有没有附加数字？检查GAE自动切换下的 *.deja.com 必走GAE

**Comment by AnyWAT** [comment]
ip-quality: 515 顶楼改进前
ip-quality: 240 上面改进后
😂

**Comment by branifern** [comment]
> gws-ip-num: total:100 ipv4:0 ipv6:100 增大总 IP数（如想性能更好些）
> scan-ip-thread-num: 100 适用于较大的总 IP数，否则对总 IP数100来说太大？
> proxy_state: Fail
> ca_state: Fail——SwitchyOmega 的图标上有没有附加数字？使用、检查GAE自动切换下的（貌似检测系统代理及证书的） *.deja.com 必走GAE

那怎么增大总ip数

**Comment by AnyWAT** [comment]
那怎么增大总ip数—— #10184 二楼
最后一条是说切换到GAE自动切换模式吗——使用（、检查）GAE自动切换下。。。

**Comment by branifern** [comment]
> 那怎么增大总ip数—— #10184 二楼
> 最后一条是说切换到GAE自动切换模式吗——使用（、检查）GAE自动切换。。。

我在我的10.4版本里面没有找到manual.ini

**Comment by AnyWAT** [comment]
没有 manual.ini 自建一个纯文本文件
没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
https://github.com/XX-net/XX-Net/issues/11010 替换新的 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

**Comment by branifern** [comment]
> 没有 manual.ini 自建一个纯文本文件
> 没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
> #11010 替换新的 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

请问manual.ini这个文件要建立在哪个文件夹下面，我版本已经是最新的了，你之前说的让我再开一个哪个版本比较低，是要把那个版本的证书文件替换成最新的证书文件对吗

**Comment by AnyWAT** [comment]
xxnet-version: 3.12.11 https://github.com/XX-net/XX-Net/issues/11610#issue-376235009
xxnet-version: 3.10.4 https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435558854
我版本已经是最新的了。。。😂
貌似程序已晕（空闲），手动扫描 IP，不行再开一个XX-Net（省事：可挤出已晕的前面那个）https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435255920
再开一个的话就是现在这个要保留吗——省事（不用结束先前的😂）：可挤出已晕的前面那个 https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435256626
🤣省事（不用结束先前的😂，再开一个😜同一目录下的同版本的 😜XX-Net）：可挤出已晕的前面那个 😱

**Comment by branifern** [comment]
> xxnet-version: 3.12.11 [#11610 (comment)](https://github.com/XX-net/XX-Net/issues/11610#issue-376235009)
> xxnet-version: 3.10.4 [#11610 (comment)](https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435558854)
> 我版本已经是最新的了。。。😂
> 貌似程序已晕（空闲），手动扫描 IP，不行再开一个XX-Net（省事：可挤出已晕的前面那个）[#11610 (comment)](https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435255920)
> 再开一个的话就是现在这个要保留吗——省事（不用结束先前的😂）：可挤出已晕的前面那个 [#11610 (comment)](https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435256626)
> 🤣省事（不用结束先前的😂，再开一个😜同一目录下的同版本的 😜XX-Net）：可挤出已晕的前面那个 😱

关键是我再开同一个目录下的同一个版本他就连通之前的那个一起闪退之后就打不开了，要重启才可以

**Comment by AnyWAT** [comment]
不会吧，试试结束进程 pythonw.exe 再运行

**Comment by branifern** [comment]
> 不会吧，试试结束进程 pythonw.exe 再运行

还是不行，要不您加我QQ帮我远程操作一下吧

**Comment by AnyWAT** [comment]
不用流氓QQ
先闪退后慢出

**Comment by branifern** [comment]
> 不会吧，试试结束进程 pythonw.exe 再运行。
> 不对，你重启可以就应没有后面的问题——除非你修改 config.json 格式有问题，贴 config.json 内容（抹去 ID 隐私，保留全部行末标点）

你之前说的manual.ini我都不知道在哪个文件夹下面建立

**Comment by branifern** [comment]
> 不用流氓QQ
> 先闪退后慢出

闪退了之后就你再打开就只能开启一个，

**Comment by AnyWAT** [comment]
你之前说的manual.ini我都不知道在哪个文件夹下面建立——#10184 说的清楚，3.10.5之前版本才要 manual.ini，3.10.5开始用 config.json
闪退了之后就你再打开就只能开启一个——你想要几个？😝

**Comment by branifern** [comment]
> 你之前说的manual.ini我都不知道在哪个文件夹下面建立——#10184 说的清楚，3.10.5之前版本才要 manual.ini，3.10.5开始用 config.json
> 闪退了之后就你再打开就只能开启一个——你想要几个？😝

你不是说再开一个把之前的顶掉，我以为之前那个会一直在，因为以前比较低的版本能同时开好几个并且不闪退

**Comment by AnyWAT** [comment]
以前比较低的版本能同时开好几个并且不闪退——没见过😭

**Comment by branifern** [comment]
> 以前比较低的版本能同时开好几个并且不闪退——没见过😭
[](url)

**Comment by branifern** [comment]
> 把收尾括号移到最末行，（不算收尾括号的）倒数第二行的0后加英文逗号（复制40后的即可）
> 隐私、隐私、隐私😜

![1541231981 1](https://user-images.githubusercontent.com/22998155/47949642-a235a500-df81-11e8-94d9-41e25be634b8.jpg)
是zheyan这样吗，但是改了之后没用啊

**Comment by AnyWAT** [comment]
修改软件一般做法：退出软件、修改文件、打开软件。
（😂别人有用，自己是否方法不对？）没重启没用？

**Comment by branifern** [comment]
> 修改软件一般做法：退出软件、修改文件、打开软件。
> （😂别人有用，自己是否方法不对？）没重启没用？

我肯定重启的啊，不然哪有这么慢回复你

**Comment by AnyWAT** [comment]
贴如下图
![image](https://user-images.githubusercontent.com/37962734/47949764-8206e580-df83-11e8-9e68-9ff0e2ebe3e0.png)

**Comment by branifern** [comment]
> 贴如下图
> ![image](https://user-images.githubusercontent.com/37962734/47949764-8206e580-df83-11e8-9e68-9ff0e2ebe3e0.png)

这是什么意思啊，

**Comment by branifern** [comment]
> 截你的图（屏）来（证实）看你说的无用是个怎么样的状况，还能有什么意思？

![1541233768 1](https://user-images.githubusercontent.com/22998155/47949926-a9f74880-df85-11e8-8220-01a8d8f941d0.jpg)
d大佬你是不是搞错了，我一直是这样的，哪有截给你那个图

**Comment by branifern** [comment]
> 截你的图（屏）来（证实）看你说的无用是个怎么样的状况，还能有什么意思？
> 😂这是什么意思啊，10分钟过去仍不见贴图。。。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:520 ipv4:0 ipv6:520
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:19 h2:0
scan-ip-thread-num: 40
ip-quality: 345
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
老调重弹：
proxy_state: Fail
ca_state: Fail——SwitchyOmega 的图标上有没有附加数字？使用、检查GAE自动切换下的（貌似检测系统代理及证书的） *.deja.com 必走GAE
如说是上面的操作，但依旧2个Fail，代理设置截图证明😂

**Comment by branifern** [comment]
> 老调重弹：
> proxy_state: Fail
> ca_state: Fail——SwitchyOmega 的图标上有没有附加数字？使用、检查GAE自动切换下的（貌似检测系统代理及证书的） *.deja.com 必走GAE
> 如说是上面的操作，但依旧2个Fail，代理设置截图证明😂

有数字37 
![1541236089 1](https://user-images.githubusercontent.com/22998155/47950292-1b85c580-df8b-11e8-8412-bf133391ad31.jpg)

**Comment by AnyWAT** [comment]
有数字37，9成以上内有 *.deja.com 必走GAE

**Comment by branifern** [comment]
> 有数字37，9成以上内有 *.deja.com 必走GAE

这要怎么修改，

**Comment by AnyWAT** [comment]
右键 SwitchyOmega 图标——选项——左键左侧情景模式：GAE自动切换，找到 *.deja.com
![image](https://user-images.githubusercontent.com/37962734/47950319-951db380-df8b-11e8-9cdc-08889c50122b.png)

**Comment by branifern** [comment]
> 右键 SwitchyOmega 图标——选项——左键左侧情景模式：GAE自动切换，找到 *.deja.com
> ![image](https://user-images.githubusercontent.com/37962734/47950319-951db380-df8b-11e8-9cdc-08889c50122b.png)

![1541237335 1](https://user-images.githubusercontent.com/22998155/47950479-00688500-df8e-11e8-855c-45701e8bbeba.jpg)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/47950549-c186ff00-df8e-11e8-801b-a3314aac5408.png)

**Comment by branifern** [comment]
> ![default](https://user-images.githubusercontent.com/37962734/47950575-1aef2e00-df8f-11e8-8c0f-6c066efb1788.png)
> 😂处女行？爬楼再看上上楼

你之前说9成里面有，我以为是删除已经有的意思，你截的图删除符号高亮的我以为你说也是删除的意思，原来是添加那我理解错了

**Comment by AnyWAT** [comment]
为了保险，添加 127.0.0.1 走“直接连接”
2个Fail 或代理不正常的时候，左键SwitchyOmega 的图标上的附加数字，分别指定走神马。。。

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/47951050-5d683900-df96-11e8-9db4-9e582eac8217.png)
左键“N个资源未加载”，分别指定走神马，再刷新控制页。。。

**Comment by branifern** [comment]
> ![default](https://user-images.githubusercontent.com/37962734/47951050-5d683900-df96-11e8-9db4-9e582eac8217.png)
> 左键“N个资源未加载”，分别指定走神马，再刷新控制页。。。

![1541241105 1](https://user-images.githubusercontent.com/22998155/47951083-c0f26680-df96-11e8-89c2-d1beadd2c201.jpg)
请问控制页又是哪个

**Comment by AnyWAT** [comment]
取消勾选A项，“添加条件”，添加条件上面的下拉菜单，走神马C。。。
取消勾选B项，“添加条件”，添加条件上面的下拉菜单，走神马D。。。
不会没导入XX-Net 证书？

**Comment by branifern** [comment]
> 取消勾选A项，“添加条件”，添加条件上面的下拉菜单，走神马C。。。
> 取消勾选B项，“添加条件”，添加条件上面的下拉菜单，走神马D。。。
> 不会没导入XX-Net 证书？

取消勾选，走A，添加条件之后还是会变成未加载项，数字变为21
已导入XX-Net-3.12.11\XX-Net-3.12.11\data\gae_proxy文件夹你的CA.crt文件，从当前计算机和本地都导入了一遍，还是不行

**Comment by AnyWAT** [comment]
控制页 http://127.0.0.1:8085 都不行，关闭它再打开，再不行，重启浏览器——第一次使用？

**Comment by AnyWAT** [comment]
再不行，浏览器所有扩展截图

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/47951270-68709880-df99-11e8-970d-690d563493c2.png)

**Comment by branifern** [comment]
> 再不行，浏览器所有（已启用的）扩展截图
> XX-Net 托盘图标采用“取消全局代理”
![1541242822 1](https://user-images.githubusercontent.com/22998155/47951373-bd60de80-df9a-11e8-9c50-a9ae1c767dcd.jpg)
取消全局代理的话就什么都打不开了

**Comment by AnyWAT** [comment]
第三次问：第一次使用？
不明白上面图标1、3、6是神马
奇怪：取消全局代理的话就什么都打不开了——那用的啥全局代理？既然如此，禁用 SwitchyOmega 或选用“系统代理”

**Comment by branifern** [comment]
> 第三次问：第一次使用？（至少对方带问号的应该回应下8？）
> 不明白上面图标1、3、6是神马
> 奇怪：取消全局代理的话就什么都打不开了——那用的啥全局代理？既然如此，禁用扩展 SwitchyOmega 或选用“系统代理”

不是第一次使用，自从出这个软件我就开始使用了，除了刚出ipv6的时候不好用，之后按照官方方法之后都是好用的，就最近不知道怎么的不好用了，
![1541243439 1](https://user-images.githubusercontent.com/22998155/47951479-40ceff80-df9c-11e8-88ca-94b9dd272225.jpg)
![1541243467 1](https://user-images.githubusercontent.com/22998155/47951483-4af0fe00-df9c-11e8-9c3a-73d9bae4af97.jpg)

**Comment by branifern** [comment]
> > 第三次问：第一次使用？（至少对方带问号的应该回应下8？）
> > 不明白上面图标1、3、6是神马
> > 奇怪：取消全局代理的话就什么都打不开了——那用的啥全局代理？既然如此，禁用扩展 SwitchyOmega 或选用“系统代理”
> 
> 不是第一次使用，自从出这个软件我就开始使用了，除了刚出ipv6的时候不好用，之后按照官方方法之后都是好用的，就最近不知道怎么的不好用了，我以为你问我是不是第一次使用是在嘲讽我第一次用这个软件吗，感觉你什么都不懂的意思
> ![1541243439 1](https://user-images.githubusercontent.com/22998155/47951479-40ceff80-df9c-11e8-88ca-94b9dd272225.jpg)
> ![1541243467 1](https://user-images.githubusercontent.com/22998155/47951483-4af0fe00-df9c-11e8-9c3a-73d9bae4af97.jpg)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/47951512-94414d80-df9c-11e8-833a-4cf9413ddfdb.png)
同一功能、不同版本的扩展都打开了😜删除1.10.6 旧版😱

**Comment by AnyWAT** [comment]
取消全局代理就一直卡主不加载了，那用的啥全局代理？
XX-Net 托盘图标采用“取消全局代理”， SwitchyOmega 选用GAE自动切换，清理浏览器缓存。。。重启浏览器

**Comment by AnyWAT** [comment]
在 IE内或系统设置内设置或清空代理，清空代理与XX-Net 托盘图标采用“取消全局代理”效果一致，如图
![default](https://user-images.githubusercontent.com/37962734/47951802-e5534080-dfa0-11e8-95ad-197d71c73a5d.png)

**Comment by branifern** [comment]
> 爬楼是什么意思——回看楼上（对方的东东，或有修改）
> 取消全局代理就一直卡主不加载了，😂不加载神马？那用的啥全局代理？
> XX-Net 托盘图标采用“取消全局代理”， SwitchyOmega 选用GAE自动切换，清理浏览器缓存。。。重启浏览器

![1541245686 1](https://user-images.githubusercontent.com/22998155/47951866-dcaf3a00-dfa1-11e8-8ba0-769e80add4df.jpg)
![1541245705 1](https://user-images.githubusercontent.com/22998155/47951868-dd47d080-dfa1-11e8-9fb5-c0e58a647115.jpg)
![1541245745 1](https://user-images.githubusercontent.com/22998155/47951869-dd47d080-dfa1-11e8-9eba-780447719de7.jpg)
![1541245767 1](https://user-images.githubusercontent.com/22998155/47951870-dd47d080-dfa1-11e8-8131-16f961964b66.jpg)
还是不行

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 可改成中文
还是不行：没说是否清理浏览器。。。
既然如此，禁用扩展 SwitchyOmega 或选用“系统代理”，XX-Net 托盘图标采用“全局GAE代理”

**Comment by AnyWAT** [comment]
目前2Fail，怎会部署？
![default](https://user-images.githubusercontent.com/37962734/47951934-f00ed500-dfa2-11e8-9092-e7918a161b72.png)

**Comment by branifern** [comment]
> 在 IE内或系统设置内设置或禁用代理，禁用代理与XX-Net 托盘图标采用“取消全局代理”效果一致，如图
> ![default](https://user-images.githubusercontent.com/37962734/47951802-e5534080-dfa0-11e8-95ad-197d71c73a5d.png)
> 可以贴你的上图，看出用的啥全局代理😂





> 目前2Fail，怎会部署？
> ![default](https://user-images.githubusercontent.com/37962734/47951934-f00ed500-dfa2-11e8-9092-e7918a161b72.png)

他就是这么显示的我也不知道为什么

**Comment by branifern** [comment]
> 在 IE内或系统设置内设置或禁用代理，禁用代理与XX-Net 托盘图标采用“取消全局代理”效果一致，如图
> ![default](https://user-images.githubusercontent.com/37962734/47951802-e5534080-dfa0-11e8-95ad-197d71c73a5d.png)
> 可以贴你的上图，看出用的啥全局代理😂

![1541246352 1](https://user-images.githubusercontent.com/22998155/47951999-8f33cc80-dfa3-11e8-920c-a2d071a91826.jpg)

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/47951971-585db680-dfa3-11e8-9c70-b94510d9f3fa.png)
老调重弹：
2个Fail 或网页代理不正常的时候，左键SwitchyOmega 图标上的附加数字（里面会有127.0.0.1 ，*.deja.com 等），分别指定走神马，再刷新控制页。。。
添加（可在你上图的菜单上复制未加载资源地址） *.localhost 走“直接连接”

**Comment by branifern** [comment]
> http://127.0.0.1:8085/?module=launcher&menu=config 可改成中文
> 还是不行：没说是否清理浏览器。。。
> 既然如此，禁用扩展 SwitchyOmega 或选用“系统代理”，XX-Net 托盘图标采用“全局GAE代理”

已经是中文的了

**Comment by AnyWAT** [comment]
爬上楼

**Comment by AnyWAT** [comment]
老调加新：没条必回😜，回答完、经确认后再操作
1、第二/三次：别说没有更新（服务端）：#11183 (comment)
2、CMD 运行 certmgr.msc 删除所有XX-Net 证书，再按下图加载证书
https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435578340

**Comment by branifern** [comment]
> 老调加新：没条必回😜，回答完、经确认后再操作
> 1、第二/三次：别说没有更新（服务端）：#11183 (comment)
> 2、CMD 运行 certmgr.msc 删除所有XX-Net 证书，再按下图加载证书
> [#11610 (comment)](https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435578340)

更新服务端是什么意思，直接下载XX-Net-3.12.11.7z解压然后打开吗

**Comment by branifern** [comment]
> 老调加新：没条必回😜，回答完、经确认后再操作
> 1、第二/三次：别说没有更新（服务端）：#11183 (comment)
> 2、CMD 运行 certmgr.msc 删除所有XX-Net 证书，再按下图加载证书
> [#11610 (comment)](https://github.com/XX-net/XX-Net/issues/11610#issuecomment-435578340)

我的版本已经是最近的还要怎么更新服务端，没懂你的服务端是什么意思

**Comment by AnyWAT** [comment]
更新服务端是什么意思——算了，一定没有做：使用公共ID即可，要做也得使用公共ID或其它软件代理
哪一楼的图——点击链接即知（因上面的问题引发2Fail 的原因？或许这步可免）
![default](https://user-images.githubusercontent.com/37962734/47952562-5b10d980-dfac-11e8-870c-15fc463929e9.png)
😂累了，886

**Comment by branifern** [comment]
> 更新服务端是什么意思——算了，一定没有做：使用公共ID即可，要做也得使用公共ID或其它软件代理
> 哪一楼的图——点击链接即知（因上面的问题引发2Fail 的原因？或许这步可免）
> ![default](https://user-images.githubusercontent.com/37962734/47952562-5b10d980-dfac-11e8-870c-15fc463929e9.png)
> 😂累了，886
这全部的楼大部分你说的术语我都不是很懂，说白话或直接说名字不可以吗，
刚说完每条必回就马上打脸
更新服务端，我真的不知道你说的服务端是什么东西
在上一搂你说的2、CMD 运行 certmgr.msc 删除所有XX-Net 证书，再按下图加载证书
#11610 (comment)这里哪里有明确的哪一楼就是这整一个帖子，
感觉你老是绕来绕去，本来方便的远程控制，你教我一下我就知道怎么做的，本来就是给别人方便的工具里非得搞的这么复杂，你累我也累，何必呢

**Comment by SeaHOH** [comment]
把同步助手关掉试试

**Comment by branifern** [comment]
> 把同步助手关掉试试

可以了，大神好厉害

**Comment by branifern** [comment]
> 把同步助手关掉试试

请问为什么之前没有这种情况，我刚更新最新版本的时候也没有问题，

**Comment by SeaHOH** [comment]
这个是改代理实现的，最好不要和代理同时使用。

**Comment by SeaHOH** [comment]
话说你的隧道质量还行，建议改回启用自动调整扫描线程数，线程最大 50 以下。
IP 总数太大反而不好用，建议 200 以下。

**Comment by branifern** [comment]
> 话说你的隧道质量还行，建议改回启用自动调整扫描线程数，线程最大 50 以下。
> IP 总数太大反而不好用，建议 200 以下。

好的，大神真厉害
