### ISSUE TITLE
有原生IPV6 ，但是XX-net上面的切换到原生IPV6是灰色的，不能点击

### ISSUE THREAD

**Issue by zhishuixue** [XX-net/XX-Net#11621]
有原生IPV6 ，但是XX-net上面的切换到原生IPV6是灰色的，不能点击

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
禁用隧道即可。
这个功能没有作用，最新的源码中已经移除了。

**Comment by zhishuixue** [comment]
禁用了IPV6，显示IPV6 fail

**Comment by zhishuixue** [comment]
IP隧道里禁用！！

**Comment by SeaHOH** [comment]
你这可能是个假 IPv6，通过了 http://test-ipv6.com 测试吗？

**Comment by zhishuixue** [comment]
状态里面的IPV6状态  fail




IPv4 状态 | OK
IPv6 状态(如何开启)





IPv4 状态 | OK
IPv6 状态(如何开启)




IPv4 状态 | OK
IPv6 状态(如何开启)

**Comment by zhishuixue** [comment]
Test with IPv4 DNS record |   | ok (0.008s) using ipv4
-- | -- | --
Test with IPv6 DNS record |   | bad (0.013s)
Test with Dual Stack DNS record |   | ok (0.475s) using ipv4
Test for Dual Stack DNS and large packet |   | ok (0.473s) using ipv4
Test IPv4 without DNS |   | ok (0.489s) using ipv4
Test IPv6 without DNS |   | bad (0.009s)
Test IPv6 large packet |   | bad (0.018s)
Test if your ISP's DNS server uses IPv6 |   | bad (0.042s)
Find IPv4 Service Provider |   | ok (0.316s) using ipv4 ASN 4134
Find IPv6 Service Provider |   | bad (0.014s)

**Comment by zhishuixue** [comment]
无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : 1x1 11bgn Wireless LAN PCI Express Half Mini Card Adapter
   物理地址. . . . . . . . . . . . . : A4-17-31-F5-BE-AB
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::6c65:48cd:12cd:4b41%20(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.116(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年11月3日 10:08:18
   租约过期的时间  . . . . . . . . . : 2018年11月4日 10:08:18
   默认网关. . . . . . . . . . . . . : 192.168.1.12
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.12
   DHCPv6 IAID . . . . . . . . . . . : 346298161
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-22-8E-A4-19-3C-97-0E-7D-BF-28
   DNS 服务器  . . . . . . . . . . . : 2001:470:20::2
                                       202.101.224.69
                                       202.101.224.68

**Comment by SeaHOH** [comment]
> 本地链接 IPv6 地址. . . . . . . . : fe80::6c65:48cd:12cd:4b41%20(首选)

没有 IPv6，这是本地链接地址。

**Comment by zhishuixue** [comment]
TCP/IP协议里面是不是取消勾选IPV6协议

**Comment by zhishuixue** [comment]
不知道为什么在家里的网络就是一直IPV6是FAIL的。

要贴什么日志吗？

SEAHOH帮我看看。

**Comment by SasamiMasakiJurai** [comment]
看你的ipv6 test结果

你根本咩有原生ipv6.......................
