### ISSUE TITLE
最近猪圈墙上又添砖了么?

### ISSUE THREAD

**Issue by 2609665** [XX-net/XX-Net#11620]
今天youtube   144p都卡的不要不要的3秒一停5秒一卡.
1.1.1.1如今也ping不通了 8.8.8.8基本也跟废了一样    8.8.4.4丢包严重     1.0.0.1勉强使用!
XXnet连接延迟也不高基本都是230±      就是会经常断!~

**Comment by AnyWAT** [comment]
Pcap_DNSProxy 是一个基于 WinPcap/LibPcap 用于过滤 DNS 投毒污染的工具，提供便捷和强大的包含正则表达式的修改 Hosts 的方法，以及对 DNSCurve/DNSCrypt 协议、并行和 TCP 协议请求的支持。多服务器并行请求功能，更可提高在恶劣网络环境下域名解析的可靠性 https://github.com/chengr28/Pcap_DNSProxy/blob/master/README.zh-Hans.md

**Comment by Acytoo** [comment]
不同的地区不同，但总体Google的dns是用不了的，如果没有及其特殊的需求，114的就很好。如果真的有需求，建议你换到linux，有个工具叫proxychains，完全转换你的网络环境。

## 另外楼主的比喻非常不恰当。

应该是有统一的出口限速。
