### ISSUE TITLE
Mac下不能用  图标一直是灰色

### ISSUE THREAD

**Issue by Bohan-Song** [XX-net/XX-Net#11624]
XX-Net Status:

sys-platform: x86_64, Darwin-17.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
os-release: 17.5.0
os-detail: Release:10.13.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:3000
network-status: unknown
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by Bohan-Song** [comment]
本地网络状态 | unknown

**Comment by SeaHOH** [comment]
> xxnet-version: 3.3.1

升级

**Comment by Bohan-Song** [comment]
版本搞错。。。
