### ISSUE TITLE
不废话，google上不去，youtube搜索用不了 怎么办？

### ISSUE THREAD

**Issue by mtgitnerd** [XX-net/XX-Net#11625]
访问google https://www.google.com/ncr 没问题，搜索东西就完蛋了
经常性504，求解

**Comment by SeaHOH** [comment]
配置、日志

**Comment by mtgitnerd** [comment]
配置如下
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 306
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 1

**Comment by mtgitnerd** [comment]
Nov 04 13:47:38.119 - [WARNING] task GET www.google.com /sorry/index?continue=https://www.google.com/search%3Fnewwindow%3D1%26source%3Dhp%26ei%3D5IfeW_fjL6KHrwSc0qGICQ%26q%3Dsdn%26oq%3Dsdn%26gs_l%3Dpsy-ab.3..0l2j0i131k1j0l2j0i131k1j0j0i131k1j0l2.13789.14288.0.14915.3.3.0.0.0.0.424.424.4-1.1.0....0...1c.1j4.64.psy-ab..2.1.423....0.h1BciphyRJU&q=EhAgAQAAU6oGTBT6r-WOFAsCGPaP-t4FIhkA8aeDS1Gzn4bOcu5f5e6wVd9b1AIyDgP-MgFy timeout

Nov 04 13:47:38.120 - [WARNING] IP:2607:f8b0:4004:35::8 host:www.google.com not support GAE, server type:HTTP server (unknown) status:503

Nov 04 13:47:38.121 - [INFO] remove ip:2607:f8b0:4004:35::8 left amount:98 target_num:98

Nov 04 13:47:38.122 - [DEBUG] 2607:f8b0:4004:35::8 worker close:

Nov 04 13:47:38.122 - [WARNING] read fail, ip:2607:f8b0:4004:35::8, chunk:0 url:GET www.google.com/sorry/index?continue=https://www.google.com/search%3Fnewwindow%3D1%26source%3Dhp%26ei%3D5IfeW_fjL6KHrwSc0qGICQ%26q%3Dsdn%26oq%3Dsdn%26gs_l%3Dpsy-ab.3..0l2j0i131k1j0l2j0i131k1j0j0i131k1j0l2.13789.14288.0.14915.3.3.0.0.0.0.424.424.4-1.1.0....0...1c.1j4.64.psy-ab..2.1.423....0.h1BciphyRJU&q=EhAgAQAAU6oGTBT6r-WOFAsCGPaP-t4FIhkA8aeDS1Gzn4bOcu5f5e6wVd9b1AIyDgP-MgFy task.timeout:56 e:error(9, 'Bad file descriptor')

Nov 04 13:47:38.123 - [WARNING] 2607:f8b0:4004:35::8 trace: 0:connect, 1790:init, 276:request,:299, processed:0, transfered:0, sni:give-clothes.org

**Comment by mtgitnerd** [comment]
配置默认，没有特殊的

**Comment by mtgitnerd** [comment]
然后页面就504 gaeproxy time out

**Comment by SeaHOH** [comment]
好像是配额用完了没检测出来。
下载这个修复版本 https://github.com/XX-net/XX-Net/issues/11479#ref-commit-038b421

**Comment by mtgitnerd** [comment]
我用的就是最新版 3.2.11 呀？

**Comment by mtgitnerd** [comment]
我用的就是最新的源码3.2.11

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/archive/master.zip
这个才是最新
