### ISSUE TITLE
您的 AppID 流量已用完，请部署更多 AppID

### ISSUE THREAD

**Issue by keyoushi** [XX-net/XX-Net#11623]
升级到 3.12.11，突然出现“您的 AppID 流量已用完，请部署更多 AppID ”的提示，然后就无法再使用了，部署的10个ID全部显示为超额，以前从来没有遇到过这种事情，难道是ID现在限制流量了？还是其它原因造成的？有大神给解释一下么？多谢！

**Comment by SeaHOH** [comment]
自己登录 https://console.cloud.google.com/ 查看限额使用状况

**Comment by jyning12** [comment]
> 自己登录 https://console.cloud.google.com/ 查看限额使用状况

我都打不开这个链接是怎么回事
