### ISSUE TITLE
XX-Net部署服务端的时候点了开始部署无任何反应，小白求救，弄了一整天了没弄明白

### ISSUE THREAD

**Issue by jihongyuanqi** [XX-net/XX-Net#11635]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
建议你就用公共 ID 算了，反正差别不大。

**Comment by jihongyuanqi** [comment]
类似问题都搜过了  没解决 只差这里了 别的地方都弄好了  部署的时候点不点没反应，也不弹出来那个授权页面，小白一个 不知道怎么贴出来截图。。。。

**Comment by jihongyuanqi** [comment]
类似问题都搜过了  没解决 只差这里了 别的地方都弄好了  部署的时候点不点没反应，也不弹出来那个授权页面，小白一个 不知道怎么贴出来截图。。。。

**Comment by jihongyuanqi** [comment]
类似问题都搜过了  没解决 只差这里了 别的地方都弄好了  部署的时候点不点没反应，也不弹出来那个授权页面，小白一个 不知道怎么贴出来截图。。。。

**Comment by jihongyuanqi** [comment]
额  那公共的跟自己的那个有啥区别吗  我现在总自己断一会，过一段时间才会好

> 建议你就用公共ID算了，反正差别不大。

额  那公共的跟自己的那个有啥区别吗  我现在总自己断一会，过一段时间才会好

**Comment by AnyWAT** [comment]
😂莫非雷同：关于更新后的google id部署问题 #11649
我现在总自己断一会，过一段时间才会好：试试 #11291
