### ISSUE TITLE
teredo隧道已经连接上仍然无法使用ipv6

### ISSUE THREAD

**Issue by xlhd19980327** [XX-net/XX-Net#11633]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。
Teredo 隧道状态显示：合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)，但是xxnet仍然报错："仅 IPv6" 不可用，请检查。使用test-ipv6网站显示无ipv6访问，不知道到底有什么问题？

teredo状态为：
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : win10.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : unmanaged
NAT                     : restricted
NAT Special Behaviour   : UPNP: No, PortPreserving: Yes
Local Mapping           : 192.168.*.*:*
External NAT Mapping    : 61.49.*.*:*

诊断信息为：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 441
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

ipconfig /all 运行结果：（部分已打码，若须提供请提出相关请求，本人网络小白所以不是很清楚哪儿不该打码）

Windows IP Configuration

   Host Name . . . . . . . . . . . . : ***
   Primary Dns Suffix  . . . . . . . : 
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : DHCP HOST

Wireless LAN adapter 无线网络连接 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft Virtual WiFi Miniport Adapter #2
   Physical Address. . . . . . . . . : 36-E6-*-*-*-*
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter 无线网络连接 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft Virtual WiFi Miniport Adapter
   Physical Address. . . . . . . . . : 36-E6-*-*-*-*
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter 无线网络连接:

   Connection-specific DNS Suffix  . : DHCP HOST
   Description . . . . . . . . . . . : Intel(R) Dual Band Wireless-AC 3160
   Physical Address. . . . . . . . . : 34-E6-*-*-*-*
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::39f0:6526:a852:33d2%14(Preferred) 
   IPv4 Address. . . . . . . . . . . : 192.168.*.*(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : 2018年11月6日 09:07:40
   Lease Expires . . . . . . . . . . : 2018年11月6日 17:04:47
   Default Gateway . . . . . . . . . : 192.168.*.*
   DHCP Server . . . . . . . . . . . : 192.168.*.*
   DHCPv6 IAID . . . . . . . . . . . : 372565677
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1C-E6-B8-79-68-F7-28-CE-39-69
   DNS Servers . . . . . . . . . . . : 202.106.*.*
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter 本地连接:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection (3) I218-V
   Physical Address. . . . . . . . . : 68-F7-28-*-*-*
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter
   Physical Address. . . . . . . . . : 0A-00-27-*-*-*
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::855c:841c:*:*(Preferred) 
   IPv4 Address. . . . . . . . . . . : 192.168.*.*(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 
   DHCPv6 IAID . . . . . . . . . . . : 571080743
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1C-E6-B8-79-68-F7-28-CE-39-69
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.{06024CD8-DB1E-4877-9CDF-7E0D6CB3E1DD}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.DHCP HOST:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : DHCP HOST
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #4
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{412908FD-E145-47E7-B43B-209BCC4A13E4}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #7
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{0FFC30BD-CE23-4414-910F-DC03EBE64645}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #12
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::2c03:3716:*:*(Preferred) 
   Default Gateway . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 1073741824
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1C-E6-B8-79-68-F7-28-CE-39-69
   NetBIOS over Tcpip. . . . . . . . : Disabled

Tunnel adapter isatap.{3C189F9D-324D-48F4-8D0B-FA8350DF665F}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #14
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

**Comment by SeaHOH** [comment]
贴出 `ipconfig /all` 结果
IP 打码后半部

**Comment by xlhd19980327** [comment]
> 贴出 `ipconfig /all` 结果
> IP 打码后半部

您好，已补充~

**Comment by SeaHOH** [comment]
1. 网络中心，更改适配器设置，把所有适配器的 IPv6 项目**取消勾选**，然后禁用再启用所有适配器。

1. XX-Net IPv6 隧道设置，点击禁用，运行完成后再点击切换服务器，等待一分钟。

如果这样还不行，再贴一次`ipconfig /all`，只打码 IP 的后半部。

**Comment by SeaHOH** [comment]
关闭后仍可回复
