### ISSUE TITLE
小白自己动手 3分钟一键搭建最新 V2ray爬墙教程

### ISSUE THREAD

**Issue by ProgramFreedom** [XX-net/XX-Net#11636]
https://t.co/xtMz3ukEri

**Comment by WorkShop-Office** [comment]
Sent from my Redmi 4AOn Nov 6, 2018 4:09 PM, ProgramFreedom <notifications@github.com<mailto:notifications@github.com>> wrote:


https://t.co/xtMz3ukEri

**Comment by WorkShop-Office** [comment]
✌️



Sent from my Redmi 4A
On ProgramFreedom <notifications@github.com>, Nov 6, 2018 4:09 PM wrote:

https://t.co/xtMz3ukEri

**Comment by SasamiMasakiJurai** [comment]
我只想说

这类广告太多了

基本都是一个模板复制黏贴

然后推广购买vps

要知道这类服务器基本都是大批大批直接封ip的
