### ISSUE TITLE
总是出现代理设置失败和证书状态失败的问题，但是可以Google

### ISSUE THREAD

**Issue by Farb** [XX-net/XX-Net#11630]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是最新的版本

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是的

* 是否以相关关键词搜索过类似 issues？
是的

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
Nov 05 13:31:32.747 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:32.806 - [INFO] scan_ip add ip:2800:3f0:4001:d::6 time:625 h2:0

Nov 05 13:31:32.806 - [INFO] remove_slowest_ip:2800:3f0:4001:d::6 handshake_time:625, fails:0

Nov 05 13:31:33.144 - [INFO] scan_ip add ip:2405:4800:100:1::11 time:2368 h2:0

Nov 05 13:31:33.145 - [INFO] remove_slowest_ip:2405:4800:100:1::11 handshake_time:2368, fails:0

Nov 05 13:31:33.191 - [INFO] scan_ip add ip:2001:ee0:3204:4::10 time:552 h2:0

Nov 05 13:31:33.191 - [INFO] remove_slowest_ip:2001:ee0:3204:4::10 handshake_time:552, fails:0

Nov 05 13:31:33.279 - [INFO] scan_ip add ip:2a00:1450:4009:4f::6 time:367 h2:0

Nov 05 13:31:33.279 - [INFO] remove_slowest_ip:2a00:1450:4011:4a::15 handshake_time:490, fails:0

Nov 05 13:31:33.334 - [INFO] scan_ip add ip:2a02:8400:0:106::10 time:509 h2:0

Nov 05 13:31:33.334 - [INFO] remove_slowest_ip:2a02:8400:0:106::10 handshake_time:509, fails:0

Nov 05 13:31:33.747 - [INFO] GAE t:1000 s:588 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(1),0:get_worker(0):2001:4e8:0:b045::e,0:h1_req,0:h1_req_sended,998:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:984],:0

Nov 05 13:31:33.749 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:33.818 - [INFO] scan_ip add ip:2804:14d:aef9:3::d time:646 h2:0

Nov 05 13:31:33.819 - [INFO] remove_slowest_ip:2804:14d:aef9:3::d handshake_time:646, fails:0

Nov 05 13:31:33.864 - [INFO] scan_ip add ip:2405:4800:100:19::d time:536 h2:0

Nov 05 13:31:33.864 - [INFO] remove_slowest_ip:2405:4800:100:19::d handshake_time:536, fails:0

Nov 05 13:31:33.917 - [INFO] scan_ip add ip:2806:1040:cfff:9::c time:1082 h2:0

Nov 05 13:31:33.917 - [INFO] remove_slowest_ip:2806:1040:cfff:9::c handshake_time:1082, fails:0

Nov 05 13:31:34.224 - [INFO] scan_ip add ip:2400:d800:3:500::13 time:2296 h2:0

Nov 05 13:31:34.224 - [INFO] remove_slowest_ip:2400:d800:3:500::13 handshake_time:2296, fails:0

Nov 05 13:31:34.398 - [INFO] scan_ip add ip:2800:3f0:4001:1e::8 time:615 h2:0

Nov 05 13:31:34.398 - [INFO] remove_slowest_ip:2800:3f0:4001:1e::8 handshake_time:615, fails:0

Nov 05 13:31:34.536 - [INFO] scan_ip add ip:2a00:1450:4015:f::20 time:1026 h2:0

Nov 05 13:31:34.536 - [INFO] remove_slowest_ip:2a00:1450:4015:f::20 handshake_time:1026, fails:0

Nov 05 13:31:34.614 - [INFO] GAE t:865 s:436 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(1),0:get_worker(0):2607:f8b0:401c:10::8,0:h2_req,0:start send header,0:start send left body,0:end send left body,862:h2_get_head,0:get_response,0:h2_finish[SP:835060],:1

Nov 05 13:31:34.616 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:34.939 - [INFO] GAE t:322 s:436 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2001:4e8:0:b045::e,0:h1_req,0:h1_req_sended,320:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:2591],:0

Nov 05 13:31:35.129 - [INFO] scan_ip add ip:2001:12e0:803:35::10 time:625 h2:0

Nov 05 13:31:35.129 - [INFO] remove_slowest_ip:2001:12e0:803:35::10 handshake_time:625, fails:0

Nov 05 13:31:35.522 - [INFO] scan_ip add ip:2405:200:1611:1716::12 time:706 h2:0

Nov 05 13:31:35.523 - [INFO] remove_slowest_ip:2405:200:1611:1716::12 handshake_time:706, fails:0

Nov 05 13:31:35.737 - [INFO] scan_ip add ip:2a00:23a0:1e5:1::15 time:693 h2:0

Nov 05 13:31:35.737 - [INFO] remove_slowest_ip:2a00:23a0:1e5:1::15 handshake_time:693, fails:0

Nov 05 13:31:37.490 - [INFO] scan_ip add ip:2607:f8b0:4000:42::a time:372 h2:0

Nov 05 13:31:37.491 - [INFO] remove_slowest_ip:2001:4600:9:308::e handshake_time:487, fails:0

Nov 05 13:31:38.111 - [INFO] scan_ip add ip:2001:578:2a:203::f time:302 h2:0

Nov 05 13:31:38.111 - [INFO] remove_slowest_ip:2607:f8b0:4002:38::a handshake_time:412, fails:0

Nov 05 13:31:38.269 - [INFO] scan_ip add ip:2804:7f2:1000:cade::11 time:626 h2:0

Nov 05 13:31:38.269 - [INFO] remove_slowest_ip:2804:7f2:1000:cade::11 handshake_time:626, fails:0

Nov 05 13:31:38.476 - [INFO] scan_ip add ip:2607:f8b0:401a:1::a time:332 h2:0

Nov 05 13:31:38.476 - [INFO] remove_slowest_ip:2607:f8b0:4002:23::8 handshake_time:409, fails:0

Nov 05 13:31:38.659 - [INFO] scan_ip add ip:2a00:1450:4002:1a::a time:426 h2:0

Nov 05 13:31:38.659 - [INFO] remove_slowest_ip:2a00:1450:4002:1a::a handshake_time:426, fails:0

Nov 05 13:31:38.986 - [INFO] scan_ip add ip:2001:12e0:803:7::c time:585 h2:0

Nov 05 13:31:38.987 - [INFO] remove_slowest_ip:2001:12e0:803:7::c handshake_time:585, fails:0

Nov 05 13:31:38.998 - [INFO] scan_ip add ip:2001:ee0:3203::d time:546 h2:0

Nov 05 13:31:38.998 - [INFO] remove_slowest_ip:2001:ee0:3203::d handshake_time:546, fails:0

Nov 05 13:31:39.388 - [INFO] scan_ip add ip:2a00:7700:8800:1::f time:2026 h2:0

Nov 05 13:31:39.388 - [INFO] remove_slowest_ip:2a00:7700:8800:1::f handshake_time:2026, fails:0

Nov 05 13:31:39.724 - [INFO] scan_ip add ip:2800:2d20:200b:c::10 time:1632 h2:0

Nov 05 13:31:39.724 - [INFO] remove_slowest_ip:2800:2d20:200b:c::10 handshake_time:1632, fails:0

Nov 05 13:31:40.927 - [INFO] scan_ip add ip:2a00:1450:4011:43::23 time:516 h2:0

Nov 05 13:31:40.927 - [INFO] remove_slowest_ip:2a00:1450:4011:43::23 handshake_time:516, fails:0

Nov 05 13:31:41.149 - [INFO] scan_ip add ip:2a02:2788:fff0:9::e time:419 h2:0

Nov 05 13:31:41.149 - [INFO] remove_slowest_ip:2a02:2788:fff0:9::e handshake_time:419, fails:0

Nov 05 13:31:41.807 - [INFO] scan_ip add ip:2607:f8b0:4002:15::b time:421 h2:0

Nov 05 13:31:41.807 - [INFO] remove_slowest_ip:2607:f8b0:4002:15::b handshake_time:421, fails:0

Nov 05 13:31:42.557 - [INFO] scan_ip add ip:2a00:1450:4001:52::c time:3490 h2:0

Nov 05 13:31:42.557 - [INFO] remove_slowest_ip:2a00:1450:4001:52::c handshake_time:3490, fails:0

Nov 05 13:31:42.840 - [INFO] scan_ip add ip:2a02:cb80:2720:2::e time:922 h2:0

Nov 05 13:31:42.840 - [INFO] remove_slowest_ip:2a02:cb80:2720:2::e handshake_time:922, fails:0

Nov 05 13:31:42.847 - [INFO] scan_ip add ip:2806:1040:cfff:6::f time:1421 h2:0

Nov 05 13:31:42.847 - [INFO] remove_slowest_ip:2806:1040:cfff:6::f handshake_time:1421, fails:0

Nov 05 13:31:43.150 - [INFO] scan_ip add ip:2806:1018:cfff:3::11 time:405 h2:0

Nov 05 13:31:43.150 - [INFO] remove_slowest_ip:2806:1018:cfff:3::11 handshake_time:405, fails:0

Nov 05 13:31:43.753 - [INFO] scan_ip add ip:2806:2f0:90ff:1::f time:474 h2:0

Nov 05 13:31:43.753 - [INFO] remove_slowest_ip:2806:2f0:90ff:1::f handshake_time:474, fails:0

Nov 05 13:31:44.127 - [INFO] scan_ip add ip:2804:7f2:1001:cade::f time:650 h2:0

Nov 05 13:31:44.128 - [INFO] remove_slowest_ip:2804:7f2:1001:cade::f handshake_time:650, fails:0

Nov 05 13:31:44.418 - [INFO] scan_ip add ip:2001:818:e4f2:1::12 time:418 h2:0

Nov 05 13:31:44.418 - [INFO] remove_slowest_ip:2001:818:e4f2:1::12 handshake_time:418, fails:0

Nov 05 13:31:45.076 - [INFO] scan_ip add ip:2405:4800:100:34::13 time:543 h2:0

Nov 05 13:31:45.076 - [INFO] remove_slowest_ip:2405:4800:100:34::13 handshake_time:543, fails:0

Nov 05 13:31:45.082 - [INFO] scan_ip add ip:2800:3f0:4001:c::8 time:615 h2:0

Nov 05 13:31:45.082 - [INFO] remove_slowest_ip:2800:3f0:4001:c::8 handshake_time:615, fails:0

Nov 05 13:31:45.437 - [INFO] scan_ip add ip:2620:11a:a01a::18 time:1255 h2:0

Nov 05 13:31:45.437 - [INFO] remove_slowest_ip:2620:11a:a01a::18 handshake_time:1255, fails:0

Nov 05 13:31:45.683 - [INFO] scan_ip add ip:2001:4e8:0:b03e::f time:253 h2:0

Nov 05 13:31:45.683 - [INFO] remove_slowest_ip:2607:f8b0:4002:23::9 handshake_time:401, fails:0

Nov 05 13:31:45.736 - [INFO] scan_ip add ip:2a00:1450:4002:11::a time:450 h2:0

Nov 05 13:31:45.736 - [INFO] remove_slowest_ip:2a00:1450:4002:11::a handshake_time:450, fails:0

Nov 05 13:31:45.762 - [INFO] scan_ip add ip:2a00:1450:4022:1::7 time:470 h2:0

Nov 05 13:31:45.763 - [INFO] remove_slowest_ip:2a00:1450:4022:1::7 handshake_time:470, fails:0

Nov 05 13:31:45.951 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:46.365 - [INFO] scan_ip add ip:2607:f8b0:401e:2b::9 time:858 h2:0

Nov 05 13:31:46.365 - [INFO] remove_slowest_ip:2607:f8b0:401e:2b::9 handshake_time:858, fails:0

Nov 05 13:31:46.365 - [INFO] scan_ip add ip:2001:d08:12:204::d time:732 h2:0

Nov 05 13:31:46.365 - [INFO] remove_slowest_ip:2001:d08:12:204::d handshake_time:732, fails:0

Nov 05 13:31:46.379 - [INFO] scan_ip add ip:2607:f8b0:4000:3b::c time:363 h2:0

Nov 05 13:31:46.379 - [INFO] remove_slowest_ip:2a00:1450:4001:6c::9 handshake_time:401, fails:0

Nov 05 13:31:46.468 - [INFO] GAE t:516 s:6510 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(11),0:get_worker(0):2607:f8b0:401c:10::8,0:h2_req,1:start send header,0:start send left body,0:end send left body,287:h2_get_head,0:get_response,226:h2_finish[SP:30566],:0

Nov 05 13:31:46.477 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:46.517 - [DEBUG] create_ssl update ip:2001:4e8:0:b03e::f time:562 h2:0 sni:grass-class-building.org, host:gae-farb3.appspot.com

Nov 05 13:31:46.797 - [INFO] GAE t:319 s:525 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2001:4e8:0:b045::e,0:h1_req,0:h1_req_sended,317:response_begin,0:h1_get_head,0:get_response,1:h1_finish[SP:2890],:0

Nov 05 13:31:46.798 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:46.987 - [INFO] scan_ip add ip:2a00:12a8:1100:3::13 time:460 h2:0

Nov 05 13:31:46.987 - [INFO] remove_slowest_ip:2001:4e8:0:b03e::f handshake_time:562, fails:0

Nov 05 13:31:47.083 - [INFO] GAE t:284 s:436 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2607:f8b0:400f:13::a,0:h1_req,0:h1_req_sended,282:response_begin,0:h1_get_head,0:h1_finish[SP:2936],0:get_response,:0

Nov 05 13:31:47.257 - [INFO] scan_ip add ip:2a00:1450:400f:5::a time:491 h2:0

Nov 05 13:31:47.258 - [INFO] remove_slowest_ip:2a00:1450:400f:5::a handshake_time:491, fails:0

Nov 05 13:31:47.539 - [DEBUG] create_ssl update ip:2607:f8b0:4005:1c::9 time:584 h2:0 sni:general.afternoon.signal.com, host:gae-farb2.appspot.com

Nov 05 13:31:47.742 - [INFO] scan_ip add ip:2a00:23a0:1e5:2::19 time:367 h2:0

Nov 05 13:31:47.743 - [INFO] remove_slowest_ip:2607:f8b0:4005:1c::9 handshake_time:584, fails:0

Nov 05 13:31:48.011 - [INFO] scan_ip add ip:2607:f8b0:4002:20::9 time:434 h2:0

Nov 05 13:31:48.011 - [INFO] remove_slowest_ip:2a00:12a8:1100:3::13 handshake_time:460, fails:0

Nov 05 13:31:48.063 - [INFO] scan_ip add ip:2405:4800:100:38::11 time:619 h2:0

Nov 05 13:31:48.063 - [INFO] remove_slowest_ip:2405:4800:100:38::11 handshake_time:619, fails:0

Nov 05 13:31:48.701 - [INFO] scan_ip add ip:2001:ee0:3201:1::12 time:555 h2:0

Nov 05 13:31:48.701 - [INFO] remove_slowest_ip:2001:ee0:3201:1::12 handshake_time:555, fails:0

Nov 05 13:31:49.293 - [INFO] scan_ip add ip:2607:f8b0:4002:28::17 time:1457 h2:0

Nov 05 13:31:49.293 - [INFO] remove_slowest_ip:2607:f8b0:4002:28::17 handshake_time:1457, fails:0

Nov 05 13:31:49.364 - [INFO] scan_ip add ip:2806:1030:cfff:1::12 time:400 h2:0

Nov 05 13:31:49.364 - [INFO] remove_slowest_ip:2607:f8b0:4002:20::9 handshake_time:434, fails:0

Nov 05 13:31:49.695 - [INFO] scan_ip add ip:2607:f8b0:4021:1f::9 time:1552 h2:0

Nov 05 13:31:49.695 - [INFO] remove_slowest_ip:2607:f8b0:4021:1f::9 handshake_time:1552, fails:0

Nov 05 13:31:49.763 - [INFO] scan_ip add ip:2607:f8b0:400a:17::c time:226 h2:0

Nov 05 13:31:49.763 - [INFO] remove_slowest_ip:2404:6800:400b:6::9 handshake_time:400, fails:0

Nov 05 13:31:49.826 - [INFO] scan_ip add ip:2620:11a:a014:3::f time:6198 h2:0

Nov 05 13:31:49.826 - [INFO] remove_slowest_ip:2620:11a:a014:3::f handshake_time:6198, fails:0

Nov 05 13:31:49.826 - [INFO] scan_ip add ip:2600:4:500::f time:444 h2:0

Nov 05 13:31:49.827 - [INFO] remove_slowest_ip:2600:4:500::f handshake_time:444, fails:0

Nov 05 13:31:50.133 - [INFO] scan_ip add ip:2607:f8b0:4004:2b::a time:1911 h2:0

Nov 05 13:31:50.133 - [INFO] remove_slowest_ip:2607:f8b0:4004:2b::a handshake_time:1911, fails:0

Nov 05 13:31:50.155 - [INFO] scan_ip add ip:2001:1700:b00::10 time:428 h2:0

Nov 05 13:31:50.155 - [INFO] remove_slowest_ip:2001:1700:b00::10 handshake_time:428, fails:0

Nov 05 13:31:50.840 - [INFO] scan_ip add ip:2a00:1450:4001:60::6 time:1391 h2:0

Nov 05 13:31:50.840 - [INFO] remove_slowest_ip:2a00:1450:4001:60::6 handshake_time:1391, fails:0

Nov 05 13:31:50.996 - [INFO] scan_ip add ip:2a00:1450:4022:7::a time:588 h2:0

Nov 05 13:31:50.996 - [INFO] remove_slowest_ip:2a00:1450:4022:7::a handshake_time:588, fails:0

Nov 05 13:31:51.322 - [INFO] scan_ip add ip:2804:14c:5bf9:4::10 time:1144 h2:0

Nov 05 13:31:51.322 - [INFO] remove_slowest_ip:2804:14c:5bf9:4::10 handshake_time:1144, fails:0

Nov 05 13:31:51.455 - [DEBUG] report_connect_fail:2001:4e8:0:b03e::12

Nov 05 13:31:51.455 - [DEBUG] connect 2001:4e8:0:b03e::12 fail:error("conn fail, sni:airline-singer-hello.org, top:gae-farb3.appspot.com e:timeout('timed out',)",)

Nov 05 13:31:51.748 - [INFO] scan_ip add ip:2402:800:6350:14::d time:573 h2:0

Nov 05 13:31:51.748 - [INFO] remove_slowest_ip:2001:4e8:0:b03e::12 handshake_time:258, fails:1

Nov 05 13:31:51.838 - [INFO] scan_ip add ip:2607:f8b0:4000:45::7 time:305 h2:0

Nov 05 13:31:51.838 - [INFO] remove_slowest_ip:2402:800:6350:14::d handshake_time:573, fails:0

Nov 05 13:31:52.457 - [DEBUG] report_connect_fail:2607:f8b0:4000:48::8

Nov 05 13:31:52.457 - [DEBUG] connect 2607:f8b0:4000:48::8 fail:error("conn fail, sni:queen.guide.org, top:gae-farb1.appspot.com e:timeout('timed out',)",)

Nov 05 13:31:52.519 - [DEBUG] report_connect_fail:2607:f8b0:4000:42::9

Nov 05 13:31:52.519 - [DEBUG] connect 2607:f8b0:4000:42::9 fail:error("conn fail, sni:facepotatolink.us, top:gae-farb1.appspot.com e:timeout('timed out',)",)

Nov 05 13:31:52.938 - [INFO] scan_ip add ip:2607:f8b0:401a:24::b time:303 h2:0

Nov 05 13:31:52.938 - [INFO] remove_slowest_ip:2607:f8b0:4000:42::9 handshake_time:291, fails:1

Nov 05 13:31:52.941 - [INFO] scan_ip add ip:2001:56a:2:6::f time:253 h2:0

Nov 05 13:31:52.941 - [INFO] remove_slowest_ip:2607:f8b0:4000:48::8 handshake_time:290, fails:1

Nov 05 13:31:53.022 - [INFO] scan_ip add ip:2800:5f0:800:5::d time:567 h2:0

Nov 05 13:31:53.023 - [INFO] remove_slowest_ip:2800:5f0:800:5::d handshake_time:567, fails:0

Nov 05 13:31:53.052 - [INFO] scan_ip add ip:2a00:1450:4011:4b::20 time:2236 h2:0

Nov 05 13:31:53.052 - [INFO] remove_slowest_ip:2a00:1450:4011:4b::20 handshake_time:2236, fails:0

Nov 05 13:31:53.070 - [INFO] scan_ip add ip:2a00:1450:4001:5e::7 time:405 h2:0

Nov 05 13:31:53.070 - [INFO] remove_slowest_ip:2a00:1450:4001:5e::7 handshake_time:405, fails:0

Nov 05 13:31:53.183 - [INFO] scan_ip add ip:2a00:1450:4012::22 time:2098 h2:0

Nov 05 13:31:53.184 - [INFO] remove_slowest_ip:2a00:1450:4012::22 handshake_time:2098, fails:0

Nov 05 13:31:54.087 - [INFO] scan_ip add ip:2001:ee0:3200:10::c time:536 h2:0

Nov 05 13:31:54.087 - [INFO] remove_slowest_ip:2001:ee0:3200:10::c handshake_time:536, fails:0

Nov 05 13:31:54.426 - [INFO] scan_ip add ip:2607:f8b0:4000:4c::6 time:291 h2:0

Nov 05 13:31:54.426 - [INFO] remove_slowest_ip:2001:3b8:201:8::11 handshake_time:400, fails:0

Nov 05 13:31:55.031 - [INFO] scan_ip add ip:2402:800:6350:c::c time:809 h2:0

Nov 05 13:31:55.031 - [INFO] remove_slowest_ip:2402:800:6350:c::c handshake_time:809, fails:0

Nov 05 13:31:55.040 - [INFO] scan_ip add ip:2804:14c:59f9:3::c time:680 h2:0

Nov 05 13:31:55.040 - [INFO] remove_slowest_ip:2804:14c:59f9:3::c handshake_time:680, fails:0

Nov 05 13:31:55.285 - [INFO] scan_ip add ip:2804:7f2:1001:cade::f time:2295 h2:0

Nov 05 13:31:55.285 - [INFO] remove_slowest_ip:2804:7f2:1001:cade::f handshake_time:2295, fails:0

Nov 05 13:31:56.296 - [INFO] scan_ip add ip:2402:800:6150:c::10 time:558 h2:0

Nov 05 13:31:56.297 - [INFO] remove_slowest_ip:2402:800:6150:c::10 handshake_time:558, fails:0

Nov 05 13:31:57.126 - [INFO] scan_ip add ip:2001:2f8:0:15::c time:1807 h2:0

Nov 05 13:31:57.126 - [INFO] remove_slowest_ip:2001:2f8:0:15::c handshake_time:1807, fails:0

Nov 05 13:31:58.086 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:58.455 - [INFO] scan_ip add ip:2a00:1450:4017:2::a time:458 h2:0

Nov 05 13:31:58.456 - [INFO] remove_slowest_ip:2a00:1450:4017:2::a handshake_time:458, fails:0

Nov 05 13:31:58.622 - [DEBUG] create_ssl update ip:2607:f8b0:400a:17::c time:532 h2:0 sni:welcome.review.us, host:gae-farb3.appspot.com

Nov 05 13:31:58.645 - [INFO] GAE t:559 s:6361 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(11),0:get_worker(0):2607:f8b0:401c:10::8,0:h2_req,1:start send header,0:start send left body,0:end send left body,332:h2_get_head,0:get_response,221:h2_finish[SP:30450],:2

Nov 05 13:31:58.652 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:58.792 - [INFO] scan_ip add ip:2a00:1450:4011:41::17 time:557 h2:0

Nov 05 13:31:58.793 - [INFO] remove_slowest_ip:2a00:1450:4011:41::17 handshake_time:557, fails:0

Nov 05 13:31:58.886 - [INFO] scan_ip add ip:2a02:240:0:2::c time:771 h2:0

Nov 05 13:31:58.886 - [INFO] remove_slowest_ip:2a02:240:0:2::c handshake_time:771, fails:0

Nov 05 13:31:58.938 - [INFO] scan_ip add ip:2a02:8400:0:108::c time:487 h2:0

Nov 05 13:31:58.938 - [INFO] remove_slowest_ip:2607:f8b0:400a:17::c handshake_time:532, fails:0

Nov 05 13:31:58.974 - [INFO] GAE t:322 s:526 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):2001:4e8:0:b045::e,0:h1_req,0:h1_req_sended,319:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:2881],:0

Nov 05 13:31:58.975 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D from:127.0.0.1:51204

Nov 05 13:31:59.148 - [DEBUG] create_ssl update ip:2001:56a:2:6::f time:559 h2:0 sni:discount.initiative.us, host:gae-farb3.appspot.com

Nov 05 13:31:59.267 - [INFO] GAE t:292 s:436 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=yIajOF2R0oql3nMk9bzSMQ%3D%3D 0:start_request,0:get_task(0),1:get_worker(0):2607:f8b0:400f:13::a,0:h1_req,0:h1_req_sended,289:response_begin,0:h1_get_head,0:get_response,0:h1_finish[SP:2885],:1

Nov 05 13:32:00.453 - [INFO] scan_ip add ip:2a00:1450:401e:28::a time:428 h2:0

Nov 05 13:32:00.453 - [INFO] remove_slowest_ip:2001:56a:2:6::f handshake_time:559, fails:0

Nov 05 13:32:00.897 - [INFO] scan_ip add ip:2a00:1450:400e:4e::9 time:407 h2:0

Nov 05 13:32:00.898 - [INFO] remove_slowest_ip:2a02:8400:0:108::c handshake_time:487, fails:0

Nov 05 13:32:01.462 - [INFO] scan_ip add ip:2001:ee0:3205:3::c time:535 h2:0

Nov 05 13:32:01.462 - [INFO] remove_slowest_ip:2001:ee0:3205:3::c handshake_time:535, fails:0

Nov 05 13:32:01.561 - [INFO] scan_ip add ip:2a02:2788:fff0:9::d time:450 h2:0

Nov 05 13:32:01.561 - [INFO] remove_slowest_ip:2a02:2788:fff0:9::d handshake_time:450, fails:0

Nov 05 13:32:01.898 - [INFO] scan_ip add ip:2a00:1450:400e:23::c time:529 h2:0

Nov 05 13:32:01.898 - [INFO] remove_slowest_ip:2a00:1450:400e:23::c handshake_time:529, fails:0

Nov 05 13:32:01.939 - [INFO] scan_ip add ip:2620:11a:a00e::16 time:409 h2:0

Nov 05 13:32:01.939 - [INFO] remove_slowest_ip:2a00:1450:401e:28::a handshake_time:428, fails:0

Nov 05 13:32:01.972 - [INFO] scan_ip add ip:2001:4958:300:4f1::e time:1002 h2:0

Nov 05 13:32:01.972 - [INFO] remove_slowest_ip:2001:4958:300:4f1::e handshake_time:1002, fails:0

Nov 05 13:32:01.985 - [INFO] scan_ip add ip:2800:3f0:4004:6::a time:619 h2:0

Nov 05 13:32:01.985 - [INFO] remove_slowest_ip:2800:3f0:4004:6::a handshake_time:619, fails:0

Nov 05 13:32:02.034 - [INFO] scan_ip add ip:2a00:1450:4022:2::c time:560 h2:0

Nov 05 13:32:02.034 - [INFO] remove_slowest_ip:2a00:1450:4022:2::c handshake_time:560, fails:0

Nov 05 13:32:02.429 - [INFO] scan_ip add ip:2607:f8b0:4017:2b::a time:415 h2:0

Nov 05 13:32:02.429 - [INFO] remove_slowest_ip:2607:f8b0:4017:2b::a handshake_time:415, fails:0

Nov 05 13:32:02.512 - [INFO] scan_ip add ip:2a00:1450:4001:57::7 time:450 h2:0

Nov 05 13:32:02.512 - [INFO] remove_slowest_ip:2a00:1450:4001:57::7 handshake_time:450, fails:0

Nov 05 13:32:02.866 - [INFO] scan_ip add ip:2a00:1450:4020:18::9 time:373 h2:0

* 如果问题得到解决，请务必回复相关情况，谢谢。

![image](https://user-images.githubusercontent.com/7587900/47979632-0b8ef280-e0ff-11e8-824c-921b199c295b.png)

![image](https://user-images.githubusercontent.com/7587900/47979681-4729bc80-e0ff-11e8-91f1-69b7c22c0e0a.png)

**Comment by Farb** [comment]
设置代理模式如下图：
![image](https://user-images.githubusercontent.com/7587900/47979715-704a4d00-e0ff-11e8-97be-6a87e9f6b0dd.png)

**Comment by SeaHOH** [comment]
能正常使用就不用管，这个这是没有检测对而已。
