### ISSUE TITLE
xx-net login session fail, status:602

### ISSUE THREAD

**Issue by Andandson** [XX-net/XX-Net#11632]
xx-net 年费，最近2周gaeproxy正常，xx-tunnel却无法登陆。显示“连接服务器失败：session server login fail:602”
已关闭4个前段，只留下GAE, 仍然无法登陆。
日志显示为
“
Nov 06 12:59:13.348 - [WARNING] front retry v17.xx-net.net/data

Nov 06 12:59:16.694 - [WARNING] front retry v17.xx-net.net/data

Nov 06 12:59:19.997 - [WARNING] front retry v17.xx-net.net/data

Nov 06 12:59:21.003 - [WARNING] login session fail, status:602
”
![qq 20181106130218](https://user-images.githubusercontent.com/44795616/48043864-d4cee000-e1c3-11e8-86a9-3f30f04109df.jpg)

求解

**Comment by SeaHOH** [comment]
指定使用一个服务器，轮流试试。

**Comment by Andandson** [comment]
> 指定使用一个服务器，轮流试试。

感谢。换了日本端口，可以用了。
