### ISSUE TITLE
请问各位大佬，极路由能否部署xxnet？求指教

### ISSUE THREAD

**Issue by Chuang2016** [XX-net/XX-Net#11631]
如题

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SasamiMasakiJurai** [comment]
目前路由内基本无法部署

**Comment by 2378** [comment]
软路由可以，v4还没挂绝的时候就玩过了
现在如果没有原生v6也是徒劳，曲线方案是ubuntu+vmware+lede，不过atom系列的软路由是带不动的，
总体来说不划算
