### ISSUE TITLE
你们是故意把GAE的ipv4 功能关了来推销X tunnel嘛？

### ISSUE THREAD

**Issue by GucciChen** [XX-net/XX-Net#11647]
我在加拿大，由于有些原因需要用GAE连接！但我发现很久之前你们似乎就在GAE 的IPV4上动了手脚啊。扫描不到IP不是真的没有，而是你们本来的列表里就没有！自己用很老的版本把里面的IP地址扣出来放进新版本里还是能正常使用！传回国依旧能用！你们这样是在变相推销X-tunnel吗？现在要用GAE XX就提示我要用ipv6.可我就要用IPV4啊！你们这样弄到底什么意思呢？

**Comment by GucciChen** [comment]
而且现在你们设置只保留200个ipv4地址！你这是变向逼我们去用收费的X-tunnel啊！以前的版本都是3000个IP的！现在真是想赚钱想疯了吗？

**Comment by GucciChen** [comment]
我又试出来问提了！说什么smart router会自动尝试直连！我开smart router 故意把尝试GAE关了，开了尝试直连！结果加拿大会上不了谷歌！！！你们绝对是变相想办法赚钱！GAE被你们搞的这么缩水明显就是想让人花钱买X-tunnel！！！

**Comment by seabeagle** [comment]
这是开源免费项目，你不感谢热心码农的付出就算了，嫌不好用就别用。ipv4枯竭你以为是几个程序员就能做出来的？我不是程序员，只是使用者。

**Comment by 2378** [comment]
这贴可以删了   @大海兄

**Comment by endlessX** [comment]
在海外的用goproxy不就行了，自己扫自己用

**Comment by SeaHOH** [comment]
> 这贴可以删了

不急，我正在扫谷歌官方 IPv4，现在结果是 100+。线程开得小，今晚才能扫完。

估计最后数量和四月份差不多，完全不够用。有兴趣的可以去翻 ip_range.txt 的 history commits。

**Comment by AnyWAT** [comment]
🤣删的锅度除了删。。。可由大家评说，删它干嘛，何况说的不是事实？删反而。。。

**Comment by GucciChen** [comment]
我没说错干嘛删?Smartrouter 直连海外上不了谷歌，这是在搞笑吗?没测试过ipv4的人不就上当觉得不能用只能用X-tunnel了吗？捐一个appid就一年给X-tunnel2G流量，我一个appid一天就能用一个G，而且在IPV4下完全国内也能用！扫描线程也不像以前那样透明！你如果不设置很多，IPV4默认每次扫一个IP！范围还被删除了这么多，扫的到IPV4见鬼了！明明是暗箱操作篇要搞的好像是IPV4 GAE不能用了！为什么我不能说呢？

**Comment by 2378** [comment]
为什么说删了。。。加拿大扫不到IPV4 ？ 加拿大也有GFW ？
就国内这环境 重心早已转到V6 
不更新V4列表 是欠着你了？ 
你倒是给大家 解释解释什么叫 “动手脚” “变相推销”

**Comment by 2378** [comment]
@SeaHOH  
大海兄 我估计你扫出来意义也不大 
只要流量一大 没两天就封 
环境好的也许能多享受几天
我这里估计秒挂 就算用Z都能几百瞬见归零

**Comment by 2378** [comment]
还是别讲了，道路以目就好:no_mouth:

**Comment by GucciChen** [comment]
你们自己下一个3.12.0试试，在用旧的IP_RANGE，你就知道了，测了很多旧的版本。3.9.6甚至IP都不能扫，但一直在post 一个dejia.com:80 和以恶搞dejia.com:443。不知道在干嘛，最新版本扫IP就说延迟高，不能用，只留200个，你用3.12.0扫扫看你就会发现差别多大！

**Comment by GucciChen** [comment]
> @SeaHOH
> 大海兄 我估计你扫出来意义也不大
> 只要流量一大 没两天就封
> 环境好的也许能多享受几天
> 我这里估计秒挂 就算用Z都能几百瞬见归零

你自己下个3.12.0试试看，我国内刚远程搞定！开局五分钟，720P视频照样放！

**Comment by GucciChen** [comment]
> 还是别讲了，道路以目就好😶

不信自己去试。3.9.6不能扫IP，一直在POST一个域名，3.12.0.现在我上海电信的电脑就能放720P的youtube。扫了五分钟！

**Comment by AnyWAT** [comment]
某些或许与此相关：
https://github.com/XX-net/XX-Net/issues/11183#issuecomment-407650866 及下一楼
没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
https://github.com/XX-net/XX-Net/issues/11010 替换新的 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

**Comment by GucciChen** [comment]
> 某些或许与此相关：
> [#11183 (comment)](https://github.com/XX-net/XX-Net/issues/11183#issuecomment-407650866) 及下一楼
> 没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
> #11010 替换新的 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

我用最新版部署的服务端。但是用的却是3.12.0.刚才试了一下1080p. 虽然现在才扫到30个IP，但2M/s 一点压力都没有！还有就是我想知道为什么3.9.6不能扫描IP 却一直在POST 一个域名呢？

**Comment by SeaHOH** [comment]
@GucciChen 
不知道 dejia.com 是什么玩意儿，这就对了。
因为你根本就不关心 XX-Net 本身，关注的用户一眼就能看出来。

**Comment by AnyWAT** [comment]
dejia.com 貌似软件检测代理、证书专用。。。

**Comment by GucciChen** [comment]
刚才看了一眼，50个了，扫的很快，挂一晚上非常轻松就能几百个，但是3.12.0只能存500个IP，也不像之前的能寸3000个IP ，而且看了下config.json 没找到哪里改GOOD IP 存3000个

**Comment by GucciChen** [comment]
我绑了30个appid，我记得以前测试是APPID越多速度越快，如果之绑一个就会很卡，我的账号能建立100个appid，但因为懒我就设置了30个

**Comment by AnyWAT** [comment]
3.12.0只能存500个IP，也不像之前的能寸3000个IP ——软件版本不一，默认总 IP数可能不同
而且看了下config.json 没找到哪里改GOOD IP 存3000个——追加设置修改默认值 #10184 二楼

**Comment by GucciChen** [comment]
> 3.9.6不能扫描IP——见前述修改文件。。。
> dejia.com 貌似软件检测代理、证书专用。。。

我想找一个能用ipv4 ipv6而且能正常扫IP的版本，最新版我试下来扫起来还是有问题的。。。x

> 3.12.0只能存500个IP，也不像之前的能寸3000个IP ——软件版本不一，默认总 IP数可能不同
> 而且看了下config.json 没找到哪里改GOOD IP 存3000个——追加设置修改默认值 #10184 二楼

谢谢，我现在就去追加！

**Comment by GucciChen** [comment]
> > 3.9.6不能扫描IP——见前述修改文件。。。
> > dejia.com 貌似软件检测代理、证书专用。。。
> 
> 我想找一个能用ipv4 ipv6而且能正常扫IP的版本，最新版我试下来扫起来还是有问题的。。。x
> 
> > 3.12.0只能存500个IP，也不像之前的能寸3000个IP ——软件版本不一，默认总 IP数可能不同
> > 而且看了下config.json 没找到哪里改GOOD IP 存3000个——追加设置修改默认值 #10184 二楼
> 
> 谢谢，我现在就去追加！
{
  "max_scan_ip_thread_num": 100, 
  "auto_adjust_scan_ip_thread_num": 0, 
  "GAE_APPIDS": [

  ], 
  "use_ipv6": "force_ipv4"
  "max_good_ip_num": 3000
}
里面是这样的。。。加完开不出来了。。。。。

**Comment by GucciChen** [comment]
好了。。。加到上面就行了，谢谢

**Comment by GucciChen** [comment]
> @GucciChen
> 不知道 dejia.com 是什么玩意儿，这就对了。
> 因为你根本就不关心 XX-Net 本身，关注的用户一眼就能看出来。

我比较关注实际使用性。。。编程没学好，代码看不懂。不过现在这样到处拼拼凑凑还真搞出了一个国内秒下秒用的~幸运

**Comment by SeaHOH** [comment]
跟代码屁关系没有，所有这些内容都有公告。

**Comment by GucciChen** [comment]
> 跟代码屁关系没有，所有这些内容都有公告。

哦~反正我用最新版本部署服务端，再用3.12.0关闭升级使用，绑了30个appid.实测上海电信一点问题都没有，ipv4虽然显延迟700左右，但网页还是秒开，youtube 1080P视频也不会卡，360显示每秒可以到2M/S！希望加强IPV4的使用。。。。从刚开始到，100扫描线程，扫到80个ip，延迟700.但完全不影响使用。。

**Comment by AnyWAT** [comment]
😂奇怪，貌似下面第一行末缺失了英文逗号，也正常？
"use_ipv6": "force_ipv4"
"max_good_ip_num": 3000

**Comment by Eri5Ch** [comment]
最近还算是很稳定吧...
LZ有点度君子之腹了...

**Comment by SeaHOH** [comment]
扫描设置：
```
connect timeout: 1.5s
handshake timeout: 2.5s
http timeout: 4s
```
还使用了三个 cn-ip-list 来排除 IP

扫描结果：
1. 谷歌官方 IPv4，571 万。
   - ip: 410+
   - range: 33
   - cost time < 500ms: 0%
   - cost time < 1000ms: 6.5%
   - cost time > 1500ms: 39.5%
   - cost time > 2000ms: 14.9%
   - gws: 56.4%
   - gvs: 36.9%
   - sffe: 6.7%
1. XX-Net 旧 IPv4 列表，98 万。
   - ip: 1630+ 包含官方 270
   - range: 195 包含官方 23
   - 以下数据因为不小心丢失前面部分记录，只统计了最后 900 个
   - cost time < 500ms: 4.1%
   - cost time < 1000ms: 16.9%
   - cost time > 1500ms: 50.6%
   - cost time > 2000ms: 24.9%
   - gws: 35.4%
   - gvs: 23.5%
   - sffe: 41.1%

官方服务器经常会调整变动，GGC 变动较少。
因为超时设置和 GFW 等因素，实际 IP 数量应该更多，但质量只会更差，无责任猜测不多于 15% 。
以上时间数据只是扫描可用性，实际使用代理时表现会更差，至少 +100ms，多就直接超时失败。

我也不下结论，觉得可以用的，自己替换列表、修改配置即可。

最后提一点就是，五月初开始，以上数据全部为 0。

**Comment by jasonliul** [comment]
Angry IP Scanner
https://angryip.org/download/#windows

LOL, 不要妄想, 使用Angry IP Scanner的web detect, 很早以前就没有gws, gvs了, 仅仅sffe可用. 

随便挑一些最新变更的字段, 现在已经无法检出sffe.

IP v4 仅仅使用quic还算可用, 不过XX是不是基于go的, 没有现成代码可以参考.

**Comment by CHN008** [comment]
感觉楼主的说法很搞笑。国内现在基本上扫不到可用的ipv4了

**Comment by SeaHOH** [comment]
上海电信国际精品网。。。

**Comment by GucciChen** [comment]
> 感觉楼主的说法很搞笑。国内现在基本上扫不到可用的ipv4了

搞笑？你自己试了吗？我这边试下来就是可以用的

**Comment by cainiaowu** [comment]
觉得推销自己fork一个啊，代码开源，不爽自己写。

**Comment by chinaniupai** [comment]
表示联通给IPV6了

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11920  Teredo 隧道用服务器 IP地址的远远稳定于用域名。
 【（并不保证你也正常的）傻瓜步骤：https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 】3.12.0也正常
![image](https://user-images.githubusercontent.com/37962734/50567716-1ffc0e00-0d83-11e9-9049-ce2c6f83feee.png)
