### ISSUE TITLE
无法使用IPv6地址远程访问

### ISSUE THREAD

**Issue by njzjz** [XX-net/XX-Net#11641]
电信原生ipv6，ipv6地址无需路由器设置端口转发。
但只能通过ipv4地址远程访问，ipv6地址无法远程访问，非常不便。

**Comment by SeaHOH** [comment]
麻烦测试一下，四个服务器都试一遍，没有错误我再 merge 到 master。

**Comment by SeaHOH** [comment]
再提醒一下，XX-Net 不提供安全认证，所以要在外网使用请考虑风险，或者使用其它工具套一层安全认证。
