### ISSUE TITLE
开启IPV6teredo出现不能打开度娘等网页，但是能登录qq和听网易云音乐

### ISSUE THREAD

**Issue by OuyangIPC** [XX-net/XX-Net#11640]
各位大佬，你们好
       开启gaeproxy，发现ipv4没有可用ip了，于是按照提示尝试修复了ipv6，前几天没问题，今天突然出现不能打开网页的情况，浏览器是Firefox，电信网络，但是某些应用可以正常联网，并且影响了室友上网，我的网线是从室友的路由器分过来的。最后关闭了teredo才能正常上网。在此询问各位大佬这可能是什么原因造成的呢，或者你们有遇到这种情况吗

**Comment by SeaHOH** [comment]
端口不够用了？不太可能，只有几个人用吧。

扫描线程数太大？流量太大？有点可能。不要使用全局代理。

**Comment by OuyangIPC** [comment]
> 
> 
> 端口不够用了？不太可能，只有几个人用吧。
> 
> 扫描线程数太大？流量太大？有点可能。不要使用全局代理。

不知道端口够不够用，xxnet只有我一个人用，我们是共用的一个路由器，扫描线程数是1，平时也几乎不用，偶尔查查资料才用的。没有使用全局代理，switchomega使用的gae-proxy自动切换。

**Comment by OuyangIPC** [comment]
> 
> 
> 端口不够用了？不太可能，只有几个人用吧。
> 
> 扫描线程数太大？流量太大？有点可能。不要使用全局代理。

不知道端口够不够用，xxnet只有我一个人用，我们是共用的一个路由器，扫描线程数是1，平时也几乎不用，偶尔查查资料才用的。没有使用全局代理，switchomega使用的gae-proxy自动切换。

**Comment by SeaHOH** [comment]
这样会影响室友使用网络，关掉 XX-Net 就好了？有点神奇。

他的路由器这两天是否改动过配置？

**Comment by OuyangIPC** [comment]
> 
> 
> 这样会影响室友使用网络，关掉 teredo 就好了？有点神奇。
> 
> 他的路由器这两天是否改动过配置？

没有改过，我也觉得很神奇，对上级路由有了影响，室友还以为他的路由器坏了

**Comment by OuyangIPC** [comment]
由于开启了ipv6_tunnel，造成了公用的电信光猫网络问题，使得光猫路由器下的三个终端（我和另外两个室友）均不能正常打开网页，起初以为只是teredo的原因，昨天关闭了teredo今天仍然出现网页打不开的现象，室友就开始吐槽电信网络问题，我开始怀疑是否是我开启了IPV6的原因，终于，找到XX-Net-master\code\default\gae_proxy\local\ipv6_tunnel这个目录下有个批处理文件disable_ipv6.bat，管理员方式运行之后问题就解决了。
解决了不能上网的问题，但是目前不知道真正原因，暂时就这样吧。
