### ISSUE TITLE
我是UI设计，最近behance被封了，请问如何通过xx-net访问该网站？

### ISSUE THREAD

**Issue by leaf00** [XX-net/XX-Net#11656]
版本3.12.11
是否是通过Smart Router的规则设定https://www.behance.net/走GAEProxy？但是设置完却没有起作用。感谢回复

**Comment by SeaHOH** [comment]
倒是截个图啊。

另外，这个站点只是被 DNS 污染，设置 hosts 可以直连，以下 IP 任选一个。
Smart Router 的 DNS 服务也许也行，不过我没使用。
```
151.101.129.197
151.101.193.197
151.101.1.197
151.101.65.197
```

**Comment by suchot** [comment]
chrome里的SwitchyOmega不要选带后面自动切换选项的。选GAE-proxy或者Smart-Router就可以打开Behance。

**Comment by milanthree** [comment]
选则GAE-proxy或者X-tunnel就能打开了，不要选择自动切换

**Comment by AnyWAT** [comment]
不要选带后面自动切换选项的、不要选择自动切换——😂无非需在自动切换内手动添加切换规则：*.behance.net 走GAE ？
