### ISSUE TITLE
老铁们能不能分享点x-tunnel流量？共享了appid账号也没回我邮件啊

### ISSUE THREAD

**Issue by ppeng** [XX-net/XX-Net#11654]
hello老铁门 有多 流量的吗 现在比较需要 共享了两个AppID 也没回我邮件 也没给我流量  账号：ppengzhen1995@gmail.com   
谢谢啦

**Comment by AnyWAT** [comment]
有了😂

**Comment by ppeng** [comment]
> 有了😂

666谢谢``

**Comment by qibin8687** [comment]
> 
> 
> 已分享，流量太多用不完，都快到期了，其实我希望可以找两三个人一起买个一年，因为根本用不完

我自己搜索捐赠appid的问题找到此帖.请问我已经捐赠了appid且给邮箱发函告知自己的帐号和捐赠id了,怎么四天过去了没见自己的帐号流量增加呢?

如果流量用不完就分享一些给我吧:binarychee@gmail.com,不要多因为我主要也是用自己部署的appid翻墙.我只是想把xtunnel的玩法搞明白.

**Comment by ppeng** [comment]
> > 已分享，流量太多用不完，都快到期了，其实我希望可以找两三个人一起买个一年，因为根本用不完
> 
> 我自己搜索捐赠appid的问题找到此帖.请问我已经捐赠了appid且给邮箱发函告知自己的帐号和捐赠id了,怎么四天过去了没见自己的帐号流量增加呢?
> 
> 如果流量用不完就分享一些给我吧:[binarychee@gmail.com](mailto:binarychee@gmail.com),不要多因为我主要也是用自己部署的appid翻墙.我只是想把xtunnel的玩法搞明白.

已转让给你 注意查收 我自己不用了 换了付费机场
