### ISSUE TITLE
最近出现卡在设置界面转半天不动 浏览器为Chrome  70.0.3538.102 x64 请高人指点.

### ISSUE THREAD

**Issue by Nivenzl** [XX-net/XX-Net#11657]
最近出现卡在设置界面转半天不动 浏览器为Chrome  70.0.3538.102 x64 请高人指点. 尝试过删除重装 降版本 均未解决, 单位电脑一样的版本又不卡~

**Comment by AnyWAT** [comment]
卡在设置界面转半天不动——不就是在 http://127.0.0.1:8085/?module=x_tunnel&menu=config 登录X-Tunnel 但老登入不了，可以点击其它标签。。。
试试：https://github.com/XX-net/XX-Net/issues/11655#issuecomment-437725853

**Comment by Nivenzl** [comment]
@AnyWAT 感谢回复,这问题仅出现在使用Chrome 使用IE访问http://127.0.0.1:8085/又一切正常 目前仅是Chrome访问时候出现卡住,选项不能选的问题.

**Comment by Nivenzl** [comment]
是之前一直都是正常的 不知道什么原因最近Chrome卡住了 不能设置 运行没问题.故来请教一下.

**Comment by AnyWAT** [comment]
清理下Chrome 缓存？

**Comment by Nivenzl** [comment]
清理了 甚至重装过Chrome 仍然卡着不动.

**Comment by AnyWAT** [comment]
如果使用了代理扩展，或许未加载资源中有 127.0.0.1（直接连接）？

**Comment by Nivenzl** [comment]
这个有的.

**Comment by AnyWAT** [comment]
即使有，如果它出现在扩展图标上附加的数字中，貌似不点击、继续操作的话或许会卡死？

**Comment by Nivenzl** [comment]
应该不是SwitchyOmega 的问题 ,我觉得应该是Chrome 和XXNET之间的连接有问题.用IE正常.

**Comment by AnyWAT** [comment]
觉得应该是Chrome 和XXNET之间的连接有问题：试试禁用X-Tunnel 模块

**Comment by Nivenzl** [comment]
已禁用 但并没有好转.

**Comment by AnyWAT** [comment]
系统任务管理器——性能——打开资源管理器：检查端口？
![default](https://user-images.githubusercontent.com/37962734/48352231-34972080-e6c7-11e8-989d-5656812d4d34.png)

**Comment by Nivenzl** [comment]
实际是这样的
![image](https://github.com/Nivenzl/Picture/blob/master/sshot-1.png)

**Comment by AnyWAT** [comment]
在仍不正常的Chrome 内能否将代理扩展未加载资源截图（想知道是否有127.0.0.1）？

**Comment by Nivenzl** [comment]
代理禁用 用直连问题仍然如此~

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11657#issuecomment-437886666 不明白？

**Comment by Nivenzl** [comment]
已经添加 并且在禁用插件 且内部有127.0.0.1直接连接的情况下仍然如此 数字里面的提醒仍然没有用.

**Comment by Nivenzl** [comment]
@AnyWAT  问题解决: 最终罪魁祸首是Chrome Dashboard 这个扩展, 本来这个Chrome Dashboard 功能与Tampermonkey有类似 之前流氓并未伸手,在最近的更新后该扩展有劫持,最终你之前看到的数字指向的是这个插件目的链接.干掉这个插件后一切太平了**### ~~ 此帖终结~~**

**Comment by hcrcaaaa** [comment]
我也遇到过，折腾了一天，还还原了系统，都没用。最后，把扩展一项一项排除才成功。
