### ISSUE TITLE
怎样增加有效IP数？

### ISSUE THREAD

**Issue by hcrcaaaa** [XX-net/XX-Net#11661]
近期的有效IP数太少了
甚至是经常性的“有效IP为0”
请问怎样增加总IP数及有效IP数？
Teredo 隧道和原生IPV6都一样。
谢谢。

**Comment by AnyWAT** [comment]
参考：#11291
增加总IP数：#10184 二楼

**Comment by hcrcaaaa** [comment]
谢谢楼上的。还是不会弄。

**Comment by zzgpku** [comment]
主要需要加英文的逗号，以及代码的位置

**Comment by AnyWAT** [comment]
😜楼主。。。 https://github.com/XX-net/XX-Net/issues/11677#issuecomment-440211500
一劳永逸的不来，就来个貌似更简单但每个版本都要处理的。退出软件，修改以下的100为你所想（300-500足矣）
![image](https://user-images.githubusercontent.com/37962734/48767690-388ff780-ecf2-11e8-9434-f3cf3e5142d8.png)

**Comment by hcrcaaaa** [comment]
谢谢楼上的。马上试试。

**Comment by AnyWAT** [comment]
遵照 #11291 的此刻 
![image](https://user-images.githubusercontent.com/37962734/48767988-f74c1780-ecf2-11e8-8f18-972c103981e3.png)
