### ISSUE TITLE
智能路由模式win10应用商店打不开

### ISSUE THREAD

**Issue by MadMaxPayne8964** [XX-net/XX-Net#11666]
Nov 14 23:44:42.881 - [DEBUG] host:sin1-ib.adnxs.com:80 do gae

Nov 14 23:44:42.943 - [DEBUG] host:g.bing.com:443 do gae

Nov 14 23:44:42.959 - [DEBUG] host:g.bing.com:443 do gae

Nov 14 23:44:42.962 - [DEBUG] http ('127.0.0.1', 7739) connect to widgets.outbrain.com:80 GET /outbrain.js

Nov 14 23:44:42.963 - [DEBUG] host:widgets.outbrain.com:80 do gae

Nov 14 23:44:43.048 - [DEBUG] host:img-s-msn-com.akamaized.net:443 do gae

Nov 14 23:44:43.204 - [DEBUG] host:static-global-s-msn-com.akamaized.net:443 do gae

Nov 14 23:44:43.298 - [DEBUG] host:img-s-msn-com.akamaized.net:443 do gae

Nov 14 23:44:43.345 - [DEBUG] host:img-s-msn-com.akamaized.net:443 do gae

Nov 14 23:44:43.454 - [DEBUG] host:img-s-msn-com.akamaized.net:443 do gae

Nov 14 23:44:43.688 - [DEBUG] host:img-s-msn-com.akamaized.net:443 do gae

Nov 14 23:44:43.735 - [DEBUG] host:g.bing.com:443 do gae

Nov 14 23:44:43.782 - [DEBUG] host:g.bing.com:443 do gae

Nov 14 23:45:03.670 - [DEBUG] pipe close [127.0.0.1]:7508->service.weather.msn.cn[61.156.50.23]:443 run_time:59 upload:618,4 download:4638,5, by remote:0, left:0 e:'r'

Nov 14 23:45:03.670 - [DEBUG] pipe close [127.0.0.1]:7505->tile-service.weather.msn.cn[61.156.50.23]:443 run_time:59 upload:1051,5 download:12513,7, by remote:0, left:0 e:'r'

Nov 14 23:45:23.543 - [DEBUG] Web_control 127.0.0.1:7932 POST /cache

Nov 14 23:45:26.795 - [DEBUG] Web_control 127.0.0.1:7932 POST /rules

Nov 14 23:45:47.661 - [DEBUG] Web_control 127.0.0.1:7932 POST /rules

Nov 14 23:45:54.512 - [DEBUG] Web_control 127.0.0.1:7932 POST /config

Nov 14 23:45:55.421 - [DEBUG] Web_control 127.0.0.1:7932 POST /rules

Nov 14 23:45:57.409 - [DEBUG] Web_control 127.0.0.1:7932 POST /cache

Nov 14 23:48:52.104 - [DEBUG] Web_control 127.0.0.1:7932 POST /config

Nov 14 23:48:54.095 - [DEBUG] Web_control 127.0.0.1:7932 POST /rules

Nov 14 23:48:55.098 - [DEBUG] Web_control 127.0.0.1:7932 POST /cache

Nov 14 23:49:30.691 - [DEBUG] host:login.live.com:443 do gae

Nov 14 23:49:37.631 - [DEBUG] PAC GET /proxy.pac from:('127.0.0.1', 8746)
把微软相关的域名加入直连也打不开，只能选pac智能代理或者取消全局。但PAC模式PAC文件很久都没更新了，还是一年前的。

**Comment by AnyWAT** [comment]
貌似 win10系统自带应用如应用商店不受代理控制？win10 只能在浏览器内翻墙吗？ · Issue #1942 · XX-net/XX-Net - https://github.com/XX-net/XX-Net/issues/1942
貌似好用的PAC https://github.com/XX-net/XX-Net/issues/11669#issuecomment-439316327

**Comment by SeaHOH** [comment]
自行搜索`win10 商店 代理 破解`
