### ISSUE TITLE
傲游浏览器PAC代理，怎么添加代理IP

### ISSUE THREAD

**Issue by EQ1874** [XX-net/XX-Net#11669]
http://127.0.0.1:8086/proxy.pac

怎么编辑pac列表？增加使用代理的网站？

希望在wiki里增加傲游浏览器和其他浏览器的的代理设置教程

wiki里面没有PAC端口的介绍

**Comment by AnyWAT** [comment]
没使用傲游浏览器，或可一试：
傲游设置 pac 的格式是什么 - 问题反馈 - 傲游社区 http://bbs.maxthon.cn/thread-10136-1-1.html 即知：file:///c:/abc.pac
下载 http://127.0.0.1:8086/proxy.pac 纯文本编辑 pac 列表来增加使用代理的网站？
。。。。。。

**Comment by AnyWAT** [comment]
如支持网络文件，他人自己使用的白名单pac文件，不定时更新常见域名 https://github.com/MatcherAny/whitelist.pac 或看一试，首行的 var wall_proxy = "SOCKS5 127.0.0.1:1080;"; 
可能得改成 var wall_proxy = "HTTP 127.0.0.1:8087;";
编辑 pac 列表来增加使用代理的网站貌似没必要？主要不像 proxy.pac 简单能看懂😂

**Comment by EQ1874** [comment]
> http://127.0.0.1:8086/proxy.pac
> 
> 怎么编辑pac列表？增加使用代理的网站？
> 
> 希望在wiki里增加傲游浏览器和其他浏览器的的代理设置教程
> 
> wiki里面没有PAC端口的介绍

我用傲游，就是用http://127.0.0.1:8086/proxy.pac 的，没问题，就是不知道怎么增加规则

**Comment by EQ1874** [comment]
> 如支持网络文件，他人自身使用的白名单 pac 文件，不定时更新常见域名 https://github.com/MatcherAny/whitelist.pac 或可一试，首行的 var wall_proxy = "SOCKS5 127.0.0.1:1080;";
> 可能得改成 var wall_proxy = "HTTP 127.0.0.1:8087;";
> （作为本地文件使用）编辑 pac 列表来增加不使用代理的网站貌似没必要？主要不像 proxy.pac 简单能看（部分）懂

Chrome规则我知道改，我主要用的是傲游浏览器。

**Comment by AnyWAT** [comment]
> 我用傲游，就是用http://127.0.0.1:8086/proxy.pac 的，没问题，就是不知道怎么增加规则
貌似上面是（随时更新的？）网络 pac，怎么改？否则，试试2楼。。。
> Chrome规则我知道改，我主要用的是傲游浏览器。
3楼：（作为本地文件使用）编辑 pac 列表不正是适用于楼主的傲游浏览器？

**Comment by AnyWAT** [comment]
> 希望在wiki里增加傲游浏览器和其他浏览器的的代理设置教程

😂网络搜索。。。

**Comment by AnyWAT** [comment]
😱一票否决：Internet Explorer 11 的自动代理配置设置 https://docs.microsoft.com/zh-cn/internet-explorer/ie11-deploy-guide/auto-proxy-configuration-settings-for-ie11 重要提示
IE11 不再支持将文件服务器位置用于代理配置 (.pac) 文件。 若要继续使用 .pac 文件，则必须将它们保存在 Web 服务器上，并使用 URL（如 https://share/test.ins）引用它们。
即 file:///c:/abc.pac  已无效😂

**Comment by AnyWAT** [comment]
https://github.com/MatcherAny/whitelist.pac 在 IE 或系统设置内：
使用自动配置脚本 https://raw.githubusercontent.com/MatcherAny/whitelist.pac/master/whitelist.pac  
IE 代理不正常（WHY ？）但 Chrome 正常

**Comment by AnyWAT** [comment]
😂值得拥有？从gfwlist更新pac文件后，之前的编辑全部丢失。 https://github.com/shadowsocks/shadowsocks-windows/issues/2078
