### ISSUE TITLE
升级到XX-Net-3.12.10之后开机启动总是弹出打开方式对话框

### ISSUE THREAD

**Issue by iarander** [XX-net/XX-Net#11668]
![default](https://user-images.githubusercontent.com/37438849/48559082-d451ea00-e925-11e8-9883-4b2bef34941a.jpg)
看上去是一个，其实是四个对话框叠加！！！
![default](https://user-images.githubusercontent.com/37438849/48559164-fe0b1100-e925-11e8-81c3-c2d26c7b992f.jpg)
选择txt打开之后，是一个名字是“program”的文件
![program](https://user-images.githubusercontent.com/37438849/48559235-30b50980-e926-11e8-9f70-6768d0981e21.jpg)
这个文件的位置在D盘根目录
![program](https://user-images.githubusercontent.com/37438849/48559308-56daa980-e926-11e8-9482-7ec07506fb4e.jpg)
不止如此
program还出现在了打开方式和右键里
![program](https://user-images.githubusercontent.com/37438849/48559357-75d93b80-e926-11e8-92e3-d20d4d8d7644.jpg)
![program](https://user-images.githubusercontent.com/37438849/48559371-7d004980-e926-11e8-8c19-806dcde1d759.jpg)
连应用程序都不是，不可能打开任何文件
![default](https://user-images.githubusercontent.com/37438849/48559538-c781c600-e926-11e8-90c1-487784f17664.jpg)
平时用倒是没问题，只是每次开机要点四次关闭，不知道怎么才能不出现对话，还有怎么去掉对话框和右键的program？（系统是64位win7）

**Comment by SeaHOH** [comment]
更新 3.12.11
