### ISSUE TITLE
访问Google网站有时会提示不是私密连接

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1166]
证书路径： GeoTrust Global CA -> Google Internet Authority G2 -> *.googlevideo.com
而不是XX-Net颁发的证书
一般重启GAEProxy后可恢复正常
相关日志↓
Oct 08 09:56:07 - [INFO] FWD CONNECT www.google.com:443
Oct 08 09:56:07 - [DEBUG] get ip:1.255.33.74 t:96
Oct 08 09:56:07 - [DEBUG] tcp conn 1.255.33.74 time:49
Oct 08 09:56:07 - [DEBUG] forward local disconnected.
Oct 08 09:56:07 - [DEBUG] FWD CONNECT www.google.com:443 with closed
Oct 08 09:56:08 - [INFO] FWD CONNECT www.google.com:443
Oct 08 09:56:08 - [DEBUG] get ip:1.255.22.249 t:107
Oct 08 09:56:08 - [DEBUG] tcp conn 1.255.22.249 time:46
Oct 08 09:56:08 - [DEBUG] forward local disconnected.
Oct 08 09:56:08 - [DEBUG] FWD CONNECT www.google.com:443 with closed

又访问一次↓
Oct 08 09:57:15 - [INFO] FWD CONNECT www.google.com:443
Oct 08 09:57:15 - [DEBUG] get ip:1.255.22.207 t:84
Oct 08 09:57:15 - [DEBUG] tcp conn 1.255.22.207 time:44
Oct 08 09:57:15 - [DEBUG] forward local disconnected.
Oct 08 09:57:15 - [DEBUG] FWD CONNECT www.google.com:443 with closed

**Comment by xxnet** [comment]
你的版本是否太老了？
  目前的版本里已经不使用FWD很久了。

FWD是不替换证书的，但是gvs的证书无法工作在google.com 域名

2015-10-08 9:57 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
用的2.5.1，我也不知道为何会这样- -
直接在稳定版本列表里下载的，什么都没改动。

**Comment by Cat7373** [comment]
修改了下config.py的代码
xlog.info("[debug_fwd] start")
for k, v in self.CONFIG.items('hosts'):
    if v == "fwd":
        xlog.info("[debug_fwd] " + k)
        if k.startswith('.'):
            fwd_endswith.append(k)
        else:
            fwd_hosts.append(k)
    elif v == "direct":
        if k.startswith('.'):
            direct_endswith.append(k)
        else:
            direct_hosts.append(k)
    elif v == "gae":
        if k.startswith('.'):
            gae_endswith.append(k)
        else:
            gae_hosts.append(k)
xlog.info("[debug_fwd] end")
并没有输出任何fwd的东东- -
证明在刚启动的时候是没有问题的- -
并且每次出现这个问题都不是XX-Net刚启动的时候，而是天晓得啥时候就突然这样了。

**Comment by Cat7373** [comment]
在 web_control.py 的 req_status_handler 函数增加了以下代码：
"fwd_ips": "|".join(config.HOSTS_FWD),
"gae_ips": "|".join(config.HOSTS_GAE),
"direct_ips": "|".join(config.HOSTS_DIRECT)

**Comment by xxnet** [comment]
发了2.5.2 修改这个bug。

对于GAE不支持的Google 网站请求，会改为FWD模式。

但是FWD模式是不修改任何通讯过程，而gvs ip必须特殊的SSL握手才能工作。
因此改为DIRECT模式。

请测试能否解决你的问题

2015-10-08 21:08 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
问题完全是随机出现- -
我也不知道是怎么触发的- -
以后如果还遇到的话再提吧。。。
