### ISSUE TITLE
Mac运行xx-net后，浏览器没办法上网

### ISSUE THREAD

**Issue by VcrTing** [XX-net/XX-Net#11664]
Mac 系统，下载安装xx - net，运行了xx_net.sh脚本，也运行了start脚本，然后下载了火狐插件（因为谷歌导入不了压缩包自带的插件），然后导入了OmegaOptions.bak之后，浏览器无法上网。
不启动xx - net网站后台就无法上网！启动了xx - net 后台但是如果你要上的网站web服务器不在大陆的话就无法连接。
这是弄得我要重装系统啊？！！

**Comment by SeaHOH** [comment]
自行搜索 SwitchyOmega 用法
