### ISSUE TITLE
[发布] 3.13.0 [测试]

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#11677]
## What is new:
* fix gae error status check
* fix some bugs
* update ip list
* add support for multi-listen
* add priority option in auto-try direct setting (smart router)
* remove IPv6 priority setting (by invalid)

## 新版改进：
* 修复 gae 错误状态检测
* 修复一些错误
* 更新 IP 列表
* 增加支持同时监听多个端口
* 增加自动直连选项（智能代理）
* 移除 IPv6 优先级设置（无效）

---

https://github.com/XX-net/XX-Net/releases/download/3.13.0/XX-Net-3.13.0.7z
这个版本作为测试发布，但是没有推送，需自行下载安装。

1. 需要使用 IPv4 用户可以把扫描 IP 模式改成`自动`，如果长时间没有 IPv4 请改回`强制 IPv6`。
1. 此版本为测试 IPv4 锁定扫描线程上限 100，即使手工修改配置文件也是如此。
1. 同时也修复了一些错误，需要的用户请自行更新。

---

### IPv4 测试结果请到 #11744 反馈。

---

已知 bug：
- `allow_remote` 参数失效 #11689

**Comment by standritsu** [comment]
youtube速度比过去的快，最高到3万稳定1万4左右，硬刚1440p，早上的时候出现过总IP数从100缓缓下掉到80，然后又开始扫描到100，看log是xxnet自己一点点把总数限制下调的，不知道是不是正常

**Comment by xxnet** [comment]
赞

**Comment by xxnet** [comment]
好的，X-Tunnel 最近疏于管理，确实问题挺多，抱歉了大家。
接下来会花些时间处理改进的。

**Comment by AnyWAT** [comment]
有人休产假回来了😜

**Comment by milanthree** [comment]
大佬回来了

**Comment by hcrcaaaa** [comment]
用了一个多小时，IP延迟一直超1000。自动扫描下，没有IPV4.总IP能否改为超100？有效IP还是不多，检查IP总是马上就降到50，为何50以上不用检查？

**Comment by SeaHOH** [comment]
> 自动扫描下，没有IPV4.

分出大约 10% 的线程去扫描 IPv4，如果几十个小时也没有一个，说明你的网络无法直接访问谷歌的 IPv4。

> 总IP能否改为超100？

一直可以，参考之前 3.12.* 版本的发布说明。

> 用了一个多小时，IP延迟一直超1000。
> 有效IP还是不多，检查IP总是马上就降到50，为何50以上不用检查？

因为总是优先使用状况较好的 IP，所有在总数足够的情况下一直保持一个线程在检查，使用过程中也会剔除失效的 IP。
你需要的不是 IP 数量，而是延迟要小，这个可以设置，方法同上条。
而且 IP 延迟高并不一定使用体验会差，确实感到明显延迟才需要调节目标延迟`target_handshake_time`。

**Comment by hcrcaaaa** [comment]
菜鸟。学过#10184 按照要求添加了，不能启动。

**Comment by hongkonghot** [comment]
非常好用，本人机子上之前的问题全解决了！

**Comment by Alobe007** [comment]
终于有更新了。感谢各位大佬。希望今晚的异动能顶得住。

**Comment by hcrcaaaa** [comment]
有效IP已经超300了。一个这么好的工具，如果每天多次卡在“有效IP为0“那是一件很悲哀的事。

**Comment by SeaHOH** [comment]
网络状况不是太好的情况下获取较大数量的有效 IP，使用体验可能会很糟糕，无论是否关闭自动调整扫描线程数都是如此。

**Comment by hcrcaaaa** [comment]
“使用体验可能会很糟糕”好过“有效IP为0”。再说了，现在都是光纤，网络状况很少会不太好的。

**Comment by styrenes** [comment]
> “使用体验可能会很糟糕”好过“有效IP为0”。再说了，现在都是光纤，网络状况很少会不太好的。
> 请教，原生IPV6没有启用按钮了，是自动启用吗？

不同意阿，我们这里网速很慢

**Comment by SeaHOH** [comment]
> 请教，原生IPV6没有启用按钮了，是自动启用吗？



>     * 移除 IPv6 优先级设置（无效）

**Comment by SeaHOH** [comment]
> “使用体验可能会很糟糕”好过“有效IP为0”。再说了，现在都是光纤，网络状况很少会不太好的。

> 网络状况不是太好的情况下获取较大数量的有效 IP

注意前提，而且“有效IP为0”怎么会是**好**？

**Comment by h188cm** [comment]
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	Fail (尝试修复)
有效 IPv4 IP 数	1
有效 IPv6 IP 数	0
总 IP 数	1
XX-Net 状态	工作
IP 延迟	9999

**Comment by h188cm** [comment]
状态
属性	值
总 IP 数	1
待测 IP 数	0
有效 IP 数	1

**Comment by rambosir** [comment]
等release

**Comment by SeaHOH** [comment]
> 有没有可能用免费 CDN 给 GAE 做代理呢

可以，其它地方有相关教程，申请个免费域名就行。

**Comment by Eri5Ch** [comment]
测试结果这个版本搜的ip质量不如12.11呀~

**Comment by SeaHOH** [comment]
@AnyWAT 这是在测试 IPv4，请不要捣乱。

**Comment by AnyWAT** [comment]
偶有1个，然后又不见了

**Comment by GoodSake** [comment]
云南移动光纤，用了这个版本后600不见了，但是not enough ip啊。。。55555

![snap1](https://user-images.githubusercontent.com/19205130/48979777-880f6280-f0fa-11e8-8943-2608f104a050.jpg)

**Comment by SeaHOH** [comment]
@GoodSake 
> 如果长时间没有 IPv4 请改回`强制 IPv6`。

还可以增加扫描线程数

**Comment by standritsu** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 (如何开启) | OK
有效 IPv4 IP 数 | 433
有效 IPv6 IP 数 | 0
总 IP 数 | 500
XX-Net 状态 | 工作
IP 延迟 | 364
连接池 (帮助) | 新:0 h1:0 h2:20
浏览器代理设置 | OK
CA 证书状态 (下载) | OK
IP 扫描线程数 (设置) | 100

从昨天开始突然出现ipv4，索性关了ipv6，结果真的扫到

**Comment by changshunxu520** [comment]
> 属性	值
> IPv4 状态	OK
> IPv6 状态 (如何开启)	OK
> 有效 IPv4 IP 数	433
> 有效 IPv6 IP 数	0
> 总 IP 数	500
> XX-Net 状态	工作
> IP 延迟	364
> 连接池 (帮助)	新:0 h1:0 h2:20
> 浏览器代理设置	OK
> CA 证书状态 (下载)	OK
> IP 扫描线程数 (设置)	100
> 从昨天开始突然出现ipv4，索性关了ipv6，结果真的扫到

真心的想说IPV6掉的真是快啊，IPV4还是稳定不易掉

**Comment by Eri5Ch** [comment]
v4是没希望了
把goodip删掉之后 v6扫出来延迟在300左右 看yb 720问题不大了...
感谢一下

**Comment by SeaHOH** [comment]
主要还是网络不同，有些地方真是一点希望都没有。
之前开贴的加拿大上海人，他的网络就完美，又快又好。

## 此测试已经发布一个星期，在这条评论收集以下反馈：

- :smile: 有 IPv4 而且质量不错（在 IPv6 不稳定的情况下，如果 IPv4 的质量不错，其数量会稳定增加）
- :-1: 有 IPv4 但是质量很差
- :+1: 有 IPv4 但是不清楚质量如何
- :confused: 根本就没有 IPv4

**Comment by changshunxu520** [comment]
> 主要还是网络不同，有些地方真是一点希望都没有。
> 之前开贴的加拿大上海人，他的网络就完美，又快又好。
> 
> ## 此测试已经发布一个星期，在这条评论收集以下反馈：
> * 😄 有 IPv4 而且质量不错（在 IPv6 不稳定的情况下，如果 IPv4 的质量不错，其数量会稳定增加）
> * 👎 有 IPv4 但是质量很差
> * 👍 有 IPv4 但是不清楚质量如何
> * 😕 根本就没有 IPv4
我不想说什么,我使用IPV6以来从来就没有稳定过。每天要来来回回折腾好久，然后IPV6才有，半个小时之内就掉干净。这个版本IPV4回来以后真心的感觉稳定了很多。上图
![xx-net](https://user-images.githubusercontent.com/16171624/49052841-8479f980-f228-11e8-8139-5e37b793c9af.png)

**Comment by h188cm** [comment]
怎么上传反馈图片？

**Comment by standritsu** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 (如何开启) | OK
有效 IPv4 IP 数 | 26
有效 IPv6 IP 数 | 0
总 IP 数 | 500
XX-Net 状态 | 工作
IP 延迟 | 868
连接池 (帮助) | 新:1 h1:19 h2:0
浏览器代理设置 | OK
CA 证书状态 (下载) | OK
IP 扫描线程数 (设置) | 100

今天变成这样，留意h2链接没了，只剩下h1

**Comment by changshunxu520** [comment]
> 怎么上传反馈图片？
点击下图标红处上传图片
![qq 20181127140208](https://user-images.githubusercontent.com/16171624/49061904-1ac01680-f24d-11e8-9c31-2699e6369c5a.png)

**Comment by SeaHOH** [comment]
不要通过回复评论来反馈，直接点击添加表情反馈。
![1543301715746](https://user-images.githubusercontent.com/8470820/49064116-ac7f5200-f254-11e8-961e-a5dbfe575c95.png)

**Comment by h188cm** [comment]
感谢指导

![default](https://user-images.githubusercontent.com/3130862/49066287-9923b500-f25b-11e8-94e7-541fc9ed8986.PNG)

**Comment by sd613** [comment]
3.13版本，YouTube还好，就是Twitter打不开了。

**Comment by nsisy** [comment]
大家的CPU占用一般多少，我的怎么快30了，影响chrome浏览了，难倒是我的本子该退休了？

**Comment by nsisy** [comment]
奇怪啊，最近才出现的，浏览器鼠标点击都困难了，看了下python占用，长期在20%左右，郁闷，CPU是6年前的I5 2410M

**Comment by AnyWAT** [comment]
不会是在系统更新？

**Comment by nsisy** [comment]
升级了3.13好点了，至少鼠标滚轮，点击的正常了，占用貌似还是不少，至少15%以上

**Comment by SeaHOH** [comment]
@nsisy 连接池和扫描线程数是多少？

**Comment by nsisy** [comment]
> @nsisy 连接池和扫描线程数是多少？

连接池 新:1 h1:27 h2:0
扫描线程 40

**Comment by SeaHOH** [comment]
数据正常。
如果其它软件也是如此，建议你先检查下硬件设置。
如果没有发现问题，试试备份资料后重装系统。

**Comment by changshunxu520** [comment]
我想问一个问题，使用IPV4是需要消耗流量的。那么使用IPV6呢？最近更新android消耗了太多的浏览

**Comment by ginnycorn** [comment]
这个版本用智能路由模式经常国内网站打不开… 前一版一般都一直挂着智能路由好像没出现这个问题…

**Comment by SeaHOH** [comment]
> 这个版本用智能路由模式经常国内网站打不开… 前一版一般都一直挂着智能路由好像没出现这个问题…

这两天也有其他人提到过，确实修改过智能路由的代码尝试解决内存泄漏。
你们再遇到这个情况后，请把智能路由的日志贴出来反馈，我会尝试修复，如果最终无法定位解决也可以回滚这部分代码。

**Comment by terry19850829** [comment]
一直用着这个测试版，直接ipv4可以使用，今天突然提示要导入CA证书。

**Comment by terry19850829** [comment]
> 一直用着这个测试版，直接ipv4可以使用，今天突然提示要导入CA证书。

虽然提示要导入CA，但是使用还是ok的，

**Comment by terry19850829** [comment]
删除mac 系统证书里面的里goagent-xxnet的证书以后，重新启动自动导入以后也不能解决报找不到证书的问题。但是使用是ok的。

**Comment by SeaHOH** [comment]
正常使用就行。。。发觉真的是喜欢看这些，下个版本会改下 SwitchyOmega 规则。

**Comment by terry19850829** [comment]
> 正常使用就行。。。发觉真的是喜欢看这些，下个版本会改下 SwitchyOmega 规则。

就是给下反馈而已，正好看到这个issue的链接。

**Comment by SeaHOH** [comment]
@terry19850829 我只是在吐槽一直开着状态页的人，感觉数量不少，其实没必要。

**Comment by leoxxnet** [comment]
只能IPV4，能扫描到，延迟跟IPV6差不多
![image](https://user-images.githubusercontent.com/32661213/49873891-f0c74080-fe57-11e8-92be-9ffc20b4b289.png)
![image](https://user-images.githubusercontent.com/32661213/49873906-ffadf300-fe57-11e8-8562-bfedc32c55e4.png)

**Comment by gggccc44** [comment]
比较奇怪的是我在win7里面没ipv4，但是在mac虚拟机里面有，电信

**Comment by emodark** [comment]
期待大佬更新！

**Comment by YUFUXUECHI** [comment]
😕 根本就没有 IPv4

**Comment by changshunxu520** [comment]
> 这两天也有其他人提到过，确实修改过智能路由的代码尝试解决内存泄漏。

智能路由包括SwitchyOmega无法访问国内网站，目前是事实，请各位注意

**Comment by husitong** [comment]
😕 根本就没有 IPv4

**Comment by sd613** [comment]
不能翻墙下载的情况下，能否提供镜像下载？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11761#issuecomment-448866306

**Comment by SeaHOH** [comment]
无界、自由门，可作为后备梯子。
