### ISSUE TITLE
"仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by Microsky-ZH** [XX-net/XX-Net#11674]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:15
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 1097
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

>

**Comment by Microsky-ZH** [comment]
ipv6不稳定

**Comment by AnyWAT** [comment]
😂参考了 #11291 的还好
![image](https://user-images.githubusercontent.com/37962734/48668915-2d429d80-eb33-11e8-87f2-29e0bff4953c.png)

**Comment by Guanyu1** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv4
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

请求大神帮忙看看是什么问题？（Please the big god help me to deal this problem, thanks so much for your help）

**Comment by AnyWAT** [comment]
use-ipv6: force_ipv4 貌似 ipv4 只有天上有了😂

**Comment by Guanyu1** [comment]
兄弟，你的xx.net能正常使用吗，如果可以请帮帮忙 @AnyWAT

**Comment by AnyWAT** [comment]
没明白正常与否？再从3楼往下看。。。
netsh int ipv6 set teredo natawareclient default 对Win7不适用！

**Comment by hongkonghot** [comment]
win10 同样问题，管理员权限运行 netsh int ipv6 set teredo natawareclient default 无效，运行 #配置IPv6.bat 或 enable_ipv6.bat 可临时解决问题，但退出 xx-net 后重进，仍然显示 "仅 IPv6" 不可用，请检查。需要重新运行 #配置IPv6.bat 或 enable_ipv6.bat

**Comment by hongkonghot** [comment]
看了IPv6 Win10开启方法，特别重要：找到 网络和共享中心 - 更改适配器设置 - 本地连接（无线网络则找到WLAN或蓝牙网络连接）- 属性，把 IPv6协议 前面的勾去掉，确定。否则会出现一些奇怪的问题。已解决，问题成功联网

**Comment by Guanyu1** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv4
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


已经禁止IPV6了，还是不行。兄弟
话说是不是这个项目现在都用不了了 @hongkonghot

**Comment by Guanyu1** [comment]
我发现一个主要问题了，是不是因为我登录不了谷歌账号才导致登录不了APP engine，所以没流量，上不了网。难题啊，头疼@milanthree @hongkonghot

**Comment by AnyWAT** [comment]
> 话说是不是这个项目现在都用不了了

😝从4楼到上上楼，他人指出的错误依旧 https://github.com/XX-net/XX-Net/issues/11674#issuecomment-439676331

**Comment by Guanyu1** [comment]
兄弟，你的能用吗？可否QQ远程帮忙一下，不胜感激

**Comment by AnyWAT** [comment]
QQ那流氓，谁用😱

**Comment by zifengtcj** [comment]
状态--ipv6--修复 然后就正常了 我用的最新版

**Comment by Guanyu1** [comment]
兄弟，可以远程指导我一下不，成了，我会好好感谢你的 @zifengtcj
