### ISSUE TITLE
XX-net的proxy.pac是不是好久没更新了？

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#11684]
连reddit都没加进去啊。这个功能是弃用了么？

另外smart router的规则列表有办法让她自动跟gfwlist同步么？手动去加black list不现实吧？

**Comment by SeaHOH** [comment]
配合 SwitchyOmega 使用，它可以支持 gwflist。

**Comment by cym104** [comment]
你这是歧视我们这些不用chrome的么ヾ(•ω•`)o

**Comment by SeaHOH** [comment]
你什么浏览器？

**Comment by cym104** [comment]
Edge ... [捂脸]

**Comment by SeaHOH** [comment]
https://github.com/search?l=JavaScript&q=pac&type=Repositories
大部分针对 gfwlist 的 pac 都是通用的，你只需要修改其中的代理地址即可。

**Comment by standritsu** [comment]
Edge？握手，套一个FWlite在外面就行了

**Comment by cym104** [comment]
看起来只好用genpac手动生成了。
我看data/smart-router/local下的proxy.pac已经有genpac的文件头了。xx-net项目不能考虑直接把genpac包进来么？

**Comment by AnyWAT** [comment]
貌似 IE11已不支持本地 pac（FireFox 尚可），手动生成对Edge 有效？
支持 Socks5:1080 的在线白名单 pac https://github.com/MatcherAny/whitelist.pac

**Comment by cym104** [comment]
替换掉xx-net本身自带的那个pac就行了。
D:\Program Files (x86)\XX-Net\code\3.13.0\smart_router\local\proxy.pac
