### ISSUE TITLE
miredo 1.26.4/ubuntu 18.04/光猫拨号/ipv6/xx-net/tunnel/ipv6不成功（解决方法之一）

### ISSUE THREAD

**Issue by liurusi** [XX-net/XX-Net#11680]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
最新版 

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
看过wiki了

* 是否以相关关键词搜索过类似 issues？
对

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
己解决 ，写个记录在这里下次碰到了好找

miredo安装后
ifconfig可以看到teredo网卡，有公网ipv6，但xx-net显示ipv6 fail

解决办法：
在光猫和终端间加入路由路，放弃光猫拨号，经过两天谷歌大法，怀疑是mtu之类的问题？

* 如果问题得到解决，请务必回复相关情况，谢谢。
己解决 ，写个记录在这里下次碰到了好找

**Comment by 2378** [comment]
我的光猫用桥接模式，并未出现类似问题
