### ISSUE TITLE
Teredo 隧道	离线（无法连接）

### ISSUE THREAD

**Issue by h188cm** [XX-net/XX-Net#11683]
最新测试版，IPV6一个都扫描不到，仅有一个IPV4可用

**Comment by h188cm** [comment]
状态
属性	值
总 IP 数	1
待测 IP 数	0
有效 IP 数	1

**Comment by SeaHOH** [comment]
测试版反馈不要单独发，请跟帖。
估计你这个只是没有 IPv6 网络而已。

**Comment by h188cm** [comment]
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	Fail (尝试修复)
有效 IPv4 IP 数	1
有效 IPv6 IP 数	0
总 IP 数	1
XX-Net 状态	工作
IP 延迟	9999

**Comment by SeaHOH** [comment]
> Fail (尝试修复)

点击下呗

**Comment by AnyWAT** [comment]
Teredo 隧道到底是离线还是与XX-Net 无法连接，貌似 #11291 的批处理更能真实反应。如批处理结果显示隧道正常，仍旧扫描不到 IP，或手动检查 IP、或再开一个XX-Net（省去退出，直接挤掉先前貌似已不正常的）、或更换服务器（近几天Win10系统的默认服务器用域名都难正常，但用 IP却很正常😜）。
