### ISSUE TITLE
cloud shell可以打开，但是怎么修改成为可使用APPID？

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#11688]
对于无效APPID，根据#4720使用命令可修改正常。但是本人不熟悉设置方法，以下为输入后交互。
请问应使用什么命令？gcloud  app deploy
Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to ladder01-201802.
Use “gcloud config set project [PROJECT_ID]” to change to a different project.
shpherd@cloudshell:~ (ladder01-201802)$ gcloud config set  project ladder01-201802
Updated property [core/project].
shpherd@cloudshell:~ (ladder01-201802)$ gcloud  beta app create  --region  us-central
You are creating an app for project [ladder01-201802].
WARNING: Creating an App Engine application for a project is irreversible and the region
cannot be changed. More information about regions is at
<https://cloud.google.com/appengine/docs/locations>.
ERROR: (gcloud.beta.app.create) The project [ladder01-201802] already contains an App Engine application. You can deploy your application using `gcloud app deploy`.
shpherd@cloudshell:~ (ladder01-201802)$

Your Cloud Platform project in this session is set to ladder01-201802.
Use “gcloud config set project [PROJECT_ID]” to change to a different project.
shpherd@cloudshell:~ (ladder01-201802)$ gcloud config set  project ladder01
Updated property [core/project].
shpherd@cloudshell:~ (ladder01)$ gcloud beta  app  create --region us-central
You are creating an app for project [ladder01].
WARNING: Creating an App Engine application for a project is irreversible and the region
cannot be changed. More information about regions is at
<https://cloud.google.com/appengine/docs/locations>.
ERROR: (gcloud.beta.app.create) PERMISSION_DENIED: Operation not allowed
- '@type': type.googleapis.com/google.rpc.ResourceInfo
  description: The "appengine.applications.create" permission is required.
  resourceType: gae.api
shpherd@cloudshell:~ (ladder01)$

**Comment by SeaHOH** [comment]
`ladder01-201802`只需要部署后，再拆分流量。
`ladder01`不清楚，你是不是没有建立这个 project ID？如果有，检测一下它的权限设置。

**Comment by shpherd** [comment]
ladder01是 project，ladder01-201802是对应 project ID。
怎么检测权限和拆分流量？

**Comment by SeaHOH** [comment]
先在 XX-Net 中用 ID 部署，完成后再到对应 ID 后台修改，把流量拆分给 XX-Net 部署的 app（100%）。
![s_2018-11-23t10-02-40 616z](https://user-images.githubusercontent.com/8470820/48937780-24dece00-ef4a-11e8-9ef8-c605f07578c4.png)

**Comment by shpherd** [comment]
![default](https://user-images.githubusercontent.com/33240748/48946028-55813080-ef67-11e8-8c49-93ca6bb174cd.png)

**Comment by shpherd** [comment]
![default](https://user-images.githubusercontent.com/33240748/48946130-a7c25180-ef67-11e8-8d49-e3e4cc4d167e.png)

**Comment by SeaHOH** [comment]
> 先在 XX-Net 中用 ID 部署

**Comment by shpherd** [comment]
之前我的project和project id一样，早上试了下后者， https://无效appid.appspot.com有效。部署成功。可能之前没有region的bug已经被修复。gcloud app deploy可以看到region。gcloud app describe可以看到相关信息。
