### ISSUE TITLE
mac系统开启自动 GAEProxy 模式下, 合盖一夜差不多跑15%的电

### ISSUE THREAD

**Issue by syliuguang** [XX-net/XX-Net#11693]
首先感谢团队的辛勤努力, 之前用 xx-net 一直很方便, 因此就一直开着自动 GAEProxy 模式, 但是最近开始发现, 如果一直开着这个模式, mac 在合盖的时候就很耗电, 后来就在合盖之前关闭 xx-net, 只要关了下次打开的时候只掉百分之几的电. 但是我经常忘了关, 只要忘了关, 下次打开的时候电就只有百分之八十几.

我不知道是不是因为最近几代的 macos 都强调在合盖的时间进行一些低功耗的后台运行, 不知道能不能让  xx-net 取消合盖的后台运行功能, 因为合盖之后也不会用  xx-net.

**Comment by SeaHOH** [comment]
如果网络质量够好，开启`自动调整扫描线程数量`或者禁用扫描会减少功耗。
