### ISSUE TITLE
xxnet托盘图标弹不出来，点击start.vbs没反应，双击start.bat显示如下问题

### ISSUE THREAD

**Issue by franktsang** [XX-net/XX-Net#11692]
本来用的好好的，XXNET托盘图标一直可以弹出来，不知为什么，现在怎么使都弹不出来，帮忙看下怎么回事？
谢谢！

![_20181124153719](https://user-images.githubusercontent.com/22273863/48965877-e35d2a00-f000-11e8-912b-69c8c739f189.png)
![_20181124153727](https://user-images.githubusercontent.com/22273863/48965878-e3f5c080-f000-11e8-8202-2f2e5febeaa2.png)

**Comment by SeaHOH** [comment]
尽量不要手动修改配置文件，网页设置界面 基本上都能设置。
恢复或删除修改就能正常运行。

**Comment by zhiganghan** [comment]
请问 问题解决了吗

**Comment by SeaHOH** [comment]
> 恢复或删除修改就能正常运行。

**Comment by franktsang** [comment]
问题不知道算解决了没，我重新下载最新的测试版本就好了。但是前面我没有手动修改配置文件。
邮件回复了，被退回了。。。。 @zhiganghan

**Comment by SeaHOH** [comment]
如果没有自己修改过，那就要小心是不是硬盘要开始报废了。
可能性很大的，最好用磁盘工具检查一次，如果还有剩余保留空间就能自动屏蔽修复，避免加速报废。

**Comment by ablebodied** [comment]
我也遇到此问题了，3.13.0 版本，可以使用，但是配置界面及托盘图标都没了

**Comment by AnyWAT** [comment]
如果 x-tunnel 配置文件修改后格的式无误就不会有问题
