### ISSUE TITLE
状态页面全是空白，日志也是空白，如何查问题

### ISSUE THREAD

**Issue by Yamazakiwu** [XX-net/XX-Net#117]
GoAgent状态信息
Property    Value
Sys Platform  
OS System  
OS version  
OS release  
OS detail  
architecture  
Browser 
XX-Net Version  
Launcher Version  
GoAgent Version 
Python Version  
Proxy Listen  
working appids  
Out of Quota appids 
Not Exist appids  
PAC URL 
Google IP

**Comment by Yamazakiwu** [comment]
呃……复制下来没表格框，不过状态表格内全是空白。

**Comment by Ghostsnail** [comment]
没部署成功吧？APPID不对吧。。。

**Comment by bernardatgh** [comment]
我也碰到过，对比几次出现的情况，应该是win7系统未得到管理员权限或者未进行管理员权限的授权

**Comment by xxnet** [comment]
goagent模块启动不成功。

请在cmd命令行执行 start.bat
看看问题出在哪里

在 2015年4月8日 下午9:57，bernardatgh <notifications@github.com>写道：

**Comment by DDelon** [comment]
GoAgent窗口内容是什么？
状态页地址是什么域名？我看了下源代码localhost：8085不行，必须是127.0.0.1:8085

**Comment by 4yzero** [comment]
我也有这样的问题，而且在各个web页面点击按钮均无效。
系统win 32bit，firfox和IE都有同样问题。

另外，单位电脑是xp系统，与上一台电脑基本相同的firefox，使用完全正常！

**Comment by xxnet** [comment]
请下载1.8.6版本，状态页最下面有帮助链接，指导如何查问题

在 2015年4月13日 下午11:48，4yzero <notifications@github.com>写道：

**Comment by 4yzero** [comment]
其实我这里只是web 界面不能用，其他使用还都是正常的。
原版的goagent本来也是用手动配置的，换了xx后，有这么方便的GUI，居然不能用，很郁闷了……

楼上有人说“win7系统未得到管理员权限或者未进行管理员权限的授权”，我觉得是有可能的。
但具体问题出在哪里呢？

**Comment by xxnet** [comment]
web界面不能用，你试试用start.bat启动，然后点击页面上的链接，看看cmd窗口出现什么提示，把日志贴出来分析

在 2015年4月15日 上午7:00，4yzero <notifications@github.com>写道：

**Comment by 4yzero** [comment]
请帮忙分析，是不是那些warning有问题呢？

Apr 17 00:00:30 - [DEBUG] create_ssl update ip:61.19.1.148 time:493
Apr 17 00:00:31 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:31 - [DEBUG] ssl_pool.get:61.19.1.183 handshake:464
Apr 17 00:00:31 - [DEBUG] ssl conn_num:18
Apr 17 00:00:31 - [DEBUG] get ip:173.194.202.31 t:458
Apr 17 00:00:31 - [DEBUG] create_ssl update ip:61.19.1.237 time:597
Apr 17 00:00:31 - [DEBUG] get ip:61.19.1.232 t:563
Apr 17 00:00:31 - [DEBUG] get ip:61.19.1.216 t:580
Apr 17 00:00:31 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:31 - [DEBUG] ssl_pool.get:61.19.1.148 handshake:493
Apr 17 00:00:31 - [DEBUG] ssl conn_num:18
Apr 17 00:00:31 - [DEBUG] create_ssl update ip:173.194.202.31 time:452
Apr 17 00:00:31 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:31 - [DEBUG] ssl_pool.get:173.194.202.31 handshake:452
Apr 17 00:00:31 - [DEBUG] ssl conn_num:18
Apr 17 00:00:32 - [DEBUG] create_ssl update ip:61.19.1.232 time:588
Apr 17 00:00:32 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:32 - [DEBUG] ssl_pool.get:61.19.1.232 handshake:588
Apr 17 00:00:32 - [DEBUG] ssl conn_num:18
Apr 17 00:00:32 - [DEBUG] get ip:61.19.1.212 t:605
Apr 17 00:00:32 - [DEBUG] create_ssl update ip:61.19.1.216 time:610
Apr 17 00:00:32 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:32 - [DEBUG] ssl_pool.get:61.19.1.237 handshake:597
Apr 17 00:00:32 - [DEBUG] ssl conn_num:18
Apr 17 00:00:32 - [DEBUG] get ip:61.19.1.217 t:667
Apr 17 00:00:32 - [DEBUG] create_ssl update ip:61.19.1.212 time:550
Apr 17 00:00:33 - [DEBUG] get ip:64.233.162.87 t:710
Apr 17 00:00:33 - [DEBUG] get ip:78.37.100.219 t:798
Apr 17 00:00:33 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:33 - [DEBUG] ssl_pool.get:61.19.1.212 handshake:550
Apr 17 00:00:33 - [DEBUG] ssl conn_num:18
Apr 17 00:00:33 - [DEBUG] create_ssl update ip:61.19.1.217 time:574
Apr 17 00:00:33 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:33 - [DEBUG] ssl_pool.get:61.19.1.217 handshake:574
Apr 17 00:00:33 - [DEBUG] ssl conn_num:18
Apr 17 00:00:33 - [DEBUG] get ip:203.211.0.24 t:853
Apr 17 00:00:34 - [DEBUG] create_ssl update ip:64.233.162.87 time:699
Apr 17 00:00:34 - [DEBUG] create_ssl update ip:78.37.100.219 time:684
Apr 17 00:00:34 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:34 - [DEBUG] ssl_pool.get:61.19.1.212 handshake:605
Apr 17 00:00:34 - [DEBUG] ssl conn_num:19
Apr 17 00:00:34 - [DEBUG] get ip:61.19.1.167 t:438
Apr 17 00:00:34 - [WARNING] APPID error:400 url:http://127.0.0.1:8084/status
Apr 17 00:00:34 - [DEBUG] ssl_pool.get:61.19.1.216 handshake:610

**Comment by xxnet** [comment]
问题：
  你把127.0.0.1:8084这种请求，都转发给GoAgent代理了，应该在代理设置里忽略掉的。
一般用SwitchySharp就没有问题，如果是手动设置浏览器代理，需要把localhost/127.0.0.1 放入忽略列表。
 如果是IE，设置代理最下面有勾选忽略本地地址的。
 其他浏览器有让填忽略的地址。

2015-04-16 12:11 GMT-04:00 4yzero <notifications@github.com>:

**Comment by 4yzero** [comment]
我用的是win7+firefox+autofoxy，
单位的电脑用xp+同样设置的firefox+autofoxy，就没有这个问题

**Comment by 4yzero** [comment]
FF的network.proxy.no_proxies_on字段值是localhost, 127.0.0.1
应该是没问题

**Comment by bernardatgh** [comment]
未得到管理员权限授权或者证书导入仍提示错误的情况，在更新了新版之后已经解决
