### ISSUE TITLE
fedora29 报错No module named pycparser

### ISSUE THREAD

**Issue by duxingxia081** [XX-net/XX-Net#11703]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
<pre>[root@bogon XX-Net-3.3.1]# ./start
XX-Net version:3.12.11
Installing pyOpenSSL for your system... Please type in your password if requested
Nov 29 21:28:57.226 [launcher][INFO] import build-in openssl fail:ImportError(&apos;No module named pycparser&apos;,)
<font color="#CC0000">Nov 29 21:28:57.230 [launcher][ERROR] import system python-OpenSSL fail:ImportError(&apos;No module named pycparser&apos;,)</font>
<font color="#CC0000">Nov 29 21:28:57.231 [launcher][ERROR] Except stack:Traceback (most recent call last):</font>
<font color="#CC0000">  File &quot;code/3.12.11/launcher/start.py&quot;, line 175, in &lt;module&gt;</font>
<font color="#CC0000">    import OpenSSL</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/noarch/OpenSSL/__init__.py&quot;, line 8, in &lt;module&gt;</font>
<font color="#CC0000">    from OpenSSL import rand, crypto, SSL</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/noarch/OpenSSL/rand.py&quot;, line 12, in &lt;module&gt;</font>
<font color="#CC0000">    from OpenSSL._util import (</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/noarch/OpenSSL/_util.py&quot;, line 6, in &lt;module&gt;</font>
<font color="#CC0000">    from cryptography.hazmat.bindings.openssl.binding import Binding</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py&quot;, line 60, in &lt;module&gt;</font>
<font color="#CC0000">    class Binding(object):</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py&quot;, line 109, in Binding</font>
<font color="#CC0000">    libraries=_get_libraries(sys.platform)</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py&quot;, line 97, in build_ffi_for_binding</font>
<font color="#CC0000">    extra_link_args=extra_link_args,</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py&quot;, line 105, in build_ffi</font>
<font color="#CC0000">    ffi = FFI()</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/linux/cffi/api.py&quot;, line 52, in __init__</font>
<font color="#CC0000">    from . import cparser, model</font>
<font color="#CC0000">  File &quot;/home/weizh/tools/home/XX-Net-3.3.1/code/3.12.11/python27/1.0/lib/linux/cffi/cparser.py&quot;, line 6, in &lt;module&gt;</font>
<font color="#CC0000">    import pycparser</font>
<font color="#CC0000">ImportError: No module named pycparser</font>

Try install python-openssl

Press Enter to continue...
</pre>
<pre>[root@bogon XX-Net-3.3.1]# python --version
Python 2.7.15
</pre>
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
> Try install python-openssl

**Comment by duxingxia081** [comment]
> > Try install python-openssl

不行啊,fedora29好像没这个东西,下载不下来

**Comment by duxingxia081** [comment]
> `$ pip install pyopenssl`

感谢，可以了
