### ISSUE TITLE
任务管理器中auto proxy detection太多

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#11709]
![image](https://user-images.githubusercontent.com/14359560/49327108-a01e3080-f597-11e8-9420-47624728bba4.png)

有没有人出现过这种现象？

**Comment by AnyWAT** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1979

**Comment by zzgpku** [comment]
![image](https://user-images.githubusercontent.com/14359560/49327438-ba0e4200-f59c-11e8-9568-fee404f72912.png)
不愧是bug10

**Comment by tlanyan** [comment]
Hello，我（应该）已经解决SS中的这个问题，你们可参考：[系统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/)
