### ISSUE TITLE
XX NET无法启动

### ISSUE THREAD

**Issue by zhiganghan** [XX-net/XX-Net#11707]
XXNET突然无法启动，托盘不显示图标，但是进程中有显示程序。出现这个问题前，安了众多银行网银，请问是否有可能是这个原因。经过自己弄了几次，现在显示以下几个（如图所示），请大神指教。
![snipaste_2018-12-01_13-59-15](https://user-images.githubusercontent.com/14030875/49324934-ab5f6500-f573-11e8-9016-468fa73eb7b4.png)
![snipaste_2018-12-01_14-03-39](https://user-images.githubusercontent.com/14030875/49324935-af8b8280-f573-11e8-8a68-98e2d634c4dc.png)
![snipaste_2018-12-01_14-16-36](https://user-images.githubusercontent.com/14030875/49324936-b9ad8100-f573-11e8-9171-b9cbaa9285a6.png)

**Comment by SeaHOH** [comment]
终止进程，然后重新启动。
遇到 XX 证书相关提示一律选择`是`。

**Comment by hmsfeng** [comment]
右下角没有相应的图标是什么原因？网站也弹不出来
