### ISSUE TITLE
ip6状态正常，但是不能翻墙，请问问题出现在哪里？如何解决？

### ISSUE THREAD

**Issue by meintube** [XX-net/XX-Net#11705]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
貌似有效 IP数太小或 IP延迟太大？netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by AnyWAT** [comment]
貌似楼上的隧道正常，只是代理扩展未加载资源内有必须走GAE的 *.deja.com 未手动处理而已？

**Comment by nly4lov** [comment]
> 貌似楼上的隧道、代理正常，只是代理扩展未加载资源内有必须走GAE的 *.deja.com 未手动处理（哪怕已有此项切换规则，不再像没有前一样处理一下，网页加载能不中止已不错：貌似代理速度欠佳引起😂），显示不正常而已？

不明觉厉😂

**Comment by SeaHOH** [comment]
关闭后仍可回复
