### ISSUE TITLE
X-Tunnel流量快到期，1000G转让

### ISSUE THREAD

**Issue by daolaobzj** [XX-net/XX-Net#11715]
如标题，有需要的请留邮箱。每人100G.
##############################
送了8位朋友，还有200G被公司的同事预订了。

**Comment by hujiharaka** [comment]
hujiharaka@gmail.com

**Comment by alexbyrant** [comment]
kobebyrant236@gmail.com
十分感谢

**Comment by 80068** [comment]
bmwnnw@gmail.com
万分感谢

**Comment by hcrcaaaa** [comment]
hcrcaaaa@gmail.com
十万分感谢

**Comment by cuijianzhuang** [comment]
cui2421011864@gmail.com

**Comment by daolaobzj** [comment]
> 哇哇哇，我想要 感谢 [haohsfb@gmail.com](mailto:haohsfb@gmail.com)

已转

**Comment by daolaobzj** [comment]
> [hujiharaka@gmail.com](mailto:hujiharaka@gmail.com)

to account hujiharaka@gmail.com not exist 什么情况

**Comment by daolaobzj** [comment]
> [kobebyrant236@gmail.com](mailto:kobebyrant236@gmail.com)
> 十分感谢

已转

**Comment by daolaobzj** [comment]
> [bmwnnw@gmail.com](mailto:bmwnnw@gmail.com)
> 万分感谢

已转

**Comment by daolaobzj** [comment]
> [hcrcaaaa@gmail.com](mailto:hcrcaaaa@gmail.com)
> 十万分感谢

发生错误：to account hcrcaaaa@gmail.com not exist

**Comment by daolaobzj** [comment]
> [cui2421011864@gmail.com](mailto:cui2421011864@gmail.com)

已转

**Comment by GFconcept** [comment]
yihueicool@Gmail.com 谢谢！！！

**Comment by yuye12345chen** [comment]
yuye12345@gmail.com谢谢

**Comment by hahsfb** [comment]
> > 哇哇哇，我想要 感谢 [haohsfb@gmail.com](mailto:haohsfb@gmail.com)
> 
> 已转

> 恩恩,已收到,感谢感谢

**Comment by yjj008818** [comment]
yjj008818@gmail.com
感谢感谢

**Comment by alphabet719** [comment]
alphabet719@gmail.com
多谢！

**Comment by ablebodied** [comment]
wangablebodied@gmai.com    thanks

**Comment by gmaeric** [comment]
gmaeric@gmail.com

**Comment by lshilshi** [comment]
看来赶不上了……
ep.ye@qq.com

**Comment by amnaruto** [comment]
假装自己赶上了(掩耳盗铃脸)
licheng.cao@gmail.com

**Comment by wgqwgqwgq** [comment]
能给一点吗？感谢
qq196304611@gmail.com

**Comment by ParamontSandiago** [comment]
paramontsandiago@gmail.com,谢谢

**Comment by fhq8800** [comment]
fhq8800@gmail.com.THANKS
