### ISSUE TITLE
请问大神xhamsterlive.com怎么打开

### ISSUE THREAD

**Issue by mscaky** [XX-net/XX-Net#11711]
请问大神xhamsterlive.com怎么打开

**Comment by mscaky** [comment]
网页不完整，无法显示FLASH

**Comment by Acytoo** [comment]
用了Switch Omega插件了吗? 左键Switch Omega, 打开的菜单中,把连接失败的网站添加到proxy的规则中,或者干脆全局proxy规则好了.
![screenshot from 2018-12-03 16-19-18](https://user-images.githubusercontent.com/18031762/49361534-45134780-f717-11e8-9bcf-f72c1f7e9ab0.png)
大概就是这个意思

**Comment by mscaky** [comment]
你试试看，肯定还是不完整的

**Comment by Acytoo** [comment]
选全局代理好了,我在教室,还是不上黄网了

**Comment by mscaky** [comment]
有知道的大神指教吗？是否网页编码问题，还是浏览器问题

**Comment by SeaHOH** [comment]
直连就可以，不要什么都代理。
