### ISSUE TITLE
请问现在XX-net付费版，普通银行卡可以支付吗？

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#11716]
1.用哪个银行卡比较稳？例如：农行卡、工行卡、中行卡？
2.是否要对该卡开通网银？不开通网银可以支付吗？
3.是否需要把卡与贝宝绑定？
4.支付后要多久才能到帐？
5.支付期间是否有手续费？

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/x-tunnel使用教程#如何获得流量

还有就是，这个项目和谷歌真的没有啥合作，只是蹭了 GAE 的服务器而已。
