### ISSUE TITLE
使用X-TUNNEL的时候，为什么还会消耗我XX-net中appid的流量呢？

### ISSUE THREAD

**Issue by ranaldinioxu** [XX-net/XX-Net#11718]
我已经设置成X-TUNNEL的自动切换模式了，也将xx-net图标设置成“取消全局代理”了，但是我xx-net页面中的GAEPROXY中部署的appid的流量却一直在消耗。。。这是为啥？

**Comment by ranaldinioxu** [comment]
第一个问题，通过搜寻，已经明白了。x-tunnel肯定要走appid的流量的，要通过gae。
第二个问题呢？希望明白人解答下。

**Comment by AnyWAT** [comment]
> 有快速登陆X-TUNNEL的方法吗？

是说在 http://127.0.0.1:8085/?module=x_tunnel&menu=config 处久登不入么？可以点击其它标签卡，或收藏 http://127.0.0.1:8085/?module=gae_proxy&menu=status 然后每次点开收藏即可打开状态页。如果做到了 https://github.com/XX-net/XX-Net/issues/11719#issuecomment-444434059 貌似可加快。。。
https://github.com/MatcherAny/whitelist.pac 的白名单 auto switch 情景模式或许稍优于黑名单的 x-tunnel 自动切换？

**Comment by ranaldinioxu** [comment]
> > 有快速登陆X-TUNNEL的方法吗？
> 
> 是说在 http://127.0.0.1:8085/?module=x_tunnel&menu=config 处久登不入么？可以点击状态页其它标签卡，或收藏 http://127.0.0.1:8085/?module=gae_proxy&menu=status 然后每次点开收藏即可打开状态页。如果做到了 [#11719 (comment)](https://github.com/XX-net/XX-Net/issues/11719#issuecomment-444434059) 貌似可实质加快。。。
> https://github.com/MatcherAny/whitelist.pac 的白名单 auto switch 情景模式或许稍优于黑名单的 x-tunnel 自动切换？
不是指http://localhost:8085/?module=x_tunnel&menu=config这的登录。
我说的是chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/io中的设置，我每次登录xx-net后，都得来这里将“选项”中“从备份文件恢复”中导入“OmegaOptions.bak”文件，然后在切换到“x-tunnel自动切换形式”才能上网。。不导入文件，直接切换就不行。

**Comment by ranaldinioxu** [comment]
不是指http://localhost:8085/?module=x_tunnel&menu=config这的登录。
我说的是chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/io中的设置，我每次登录xx-net后，都得来这里将“选项”中“从备份文件恢复”中导入“OmegaOptions.bak”文件，然后在切换到“x-tunnel自动切换形式”才能上网。。不导入文件，直接切换就不行。

**Comment by ranaldinioxu** [comment]
不是指http://localhost:8085/?module=x_tunnel&menu=config 这的登录。
我说的是chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/io中的设置，我每次登录xx-net后，都得来这里将“选项”中“从备份文件恢复”中导入“OmegaOptions.bak”文件，然后在切换到“x-tunnel自动切换形式”才能上网。。不导入文件，直接切换就不行。

**Comment by AnyWAT** [comment]
好奇怪😱这样与其说“有快速登陆X-TUNNEL的方法吗？”，远不如说：SwitchyOmega 工作不正常。。。
或许 https://github.com/XX-net/XX-Net/issues/9501 ？
当然试试 https://github.com/MatcherAny/whitelist.pac 的白名单 auto switch 情景模式，简直相见恨晚😜

**Comment by AnyWAT** [comment]
如果每次“然后在SwitchyOmega中导入OmegaOptions.bak文件，再设置成x-tunnel自动切换，最后将xx-net图标设置成取消全局代理。。”“才能上网。。不导入文件，直接切换就不行。”——奇事😱

**Comment by ranaldinioxu** [comment]
ok了，多谢多谢！！！！
