### ISSUE TITLE
【小白】扫描了几个小时，一直是这个状态

### ISSUE THREAD

**Issue by lbx6z** [XX-net/XX-Net#1171]
【ubuntu 14.04】
sudo ./start.sh
……
……
Oct  8 19:23:50 - [DEBUG] get ip:202.169.175.108 t:243
Oct  8 19:23:50 - [DEBUG] get ip:202.169.173.203 t:244
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.17 time:196
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.6 time:197
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.32 time:196
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.27 time:207
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.8 time:207
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.48 time:203
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:202.169.173.203 time:253
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:202.169.175.108 time:247
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:202.28.85.89 time:213
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:202.169.173.240 time:255
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:202.28.85.71 time:212
Oct  8 19:23:51 - [DEBUG] create_ssl update ip:150.100.16.40 time:221
Oct  8 19:23:52 - [DEBUG] create_ssl update ip:202.28.85.44 time:219
Oct  8 19:23:52 - [DEBUG] create_ssl update ip:202.28.85.22 time:219
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] create_ssl update ip:150.100.16.29 time:232
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] create_ssl update ip:202.28.85.50 time:221
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] create_ssl update ip:150.100.16.53 time:198
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:52 - [DEBUG] get enough conn for gae
Oct  8 19:23:53 - [DEBUG] get enough conn for gae
Oct  8 19:23:53 - [DEBUG] get enough conn for gae
Oct  8 19:23:53 - [DEBUG] get enough conn for gae
Oct  8 19:23:53 - [DEBUG] get enough conn for gae
Oct  8 19:23:53 - [DEBUG] get enough conn for gae
Oct  8 19:23:53 - [DEBUG] get enough conn for gae
Oct  8 19:23:55 - [DEBUG] create_ssl 113.171.19.229 fail:timed out cost:4004 h:0
Oct  8 19:23:57 - [DEBUG] get enough conn for gae
Oct  8 19:24:03 - [INFO] scan_ip add ip:109.105.109.240 time:618
Oct  8 19:24:03 - [INFO] remove_slowest_ip:218.253.0.187 handshake_time:1238
……
……

该怎么解决？>.<

**Comment by Cat7373** [comment]
从你发的内容里看不出来有什么问题。。。

**Comment by xxnet** [comment]
浏览器没有设置代理

2015-10-08 22:29 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet 没有设置代理看来是一个常见的问题？除了之前说的安装后第一次运行自动设置全局PAC外，我觉得也可以做一个检测，一定时间内未受到代理请求，就在状态页面显示一个提示，同时标明当前的系统代理设置状况。

**Comment by xxnet** [comment]
也许来一个新手step by step 的引导，每一步，如何确认，通过了，再进入下一步。

在 2015年10月9日 下午10:49，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 嗯，可能当前的指引写得还是太分散，不够系统。找时间重整一下
