### ISSUE TITLE
mac X-tunnel 登录不稳定，登录上也不能访问google

### ISSUE THREAD

**Issue by JemmyLuck** [XX-net/XX-Net#11717]
mac系统为macOS Mojave(10.14.1)，xx-net为3.13.0。与windows台式机(有线)连接同一个路由器，windows能正常登录x-tunnel。windows台式机GAEPROXY和x-tunnel两种方式都可以访问外网。
而mac(无线连接)不仅常常不能登录x-tunnel，失败状态为status:602,就算登录上也不能访问google。mac要怎么设置吗？
以下是GAEPROXY的诊断信息：
XX-Net Status:

sys-platform: x86_64, Darwin-18.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
os-release: 18.2.0
os-detail: Release:10.14.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15
xxnet-version: 3.13.0
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by JemmyLuck** [comment]
付费包年用户发问了，管理员不解决吗？？？？？

**Comment by JemmyLuck** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | Fail (尝试修复)
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 0
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | Fail
CA 证书状态(下载) | Fail
IP 扫描线程数(设置) | [200]

**Comment by JemmyLuck** [comment]
属性 | 值
-- | --
代理监听 | 127.0.0.1:8087
IP 模式 | 自动
前置代理 | 禁用


属性 | 值
-- | --
代理监听 | 127.0.0.1:8087
IP 模式 | 自动
前置代理 | 禁用


属性 | 值
-- | --
XX-Net Version | 3.12.11
Python Version | 2.7.10
OpenSSL Version | 16.0.0 TLSv1 h2:alpn
System Platform | x86_64, Darwin-18.2.0-x86_64-i386-64bit
OS System | Darwin
OS Version | Darwin Kernel Version 18.2.0: Fri Oct 5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
OS Release | 18.2.0
OS Detail | Release:10.14.1; Version:('', '', '') Machine:x86_64
Language | zh_CN
Architecture | 64bit,
Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

**Comment by SeaHOH** [comment]
xxnet.dev@gmail.com

**Comment by rfcpdq** [comment]
同样付费包年用户……同样问题……
