### ISSUE TITLE
reddit上不了

### ISSUE THREAD

**Issue by skyremind** [XX-net/XX-Net#11713]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。
 google youtube等都能上 就reddit上不了

**Comment by yeezylife** [comment]
是不是更新了最新的测试版？   智能路由规则里。走GAE 加入这条“www.reddit.com”
最新的测试版智能路由貌似有bug  我用着用着上不去网了  重开一遍才行

**Comment by yeezylife** [comment]
> @yeezylife 有 bug 要报，我真的没有使用 XX-Net。

今天下午五六点又出现一次，具体表现为使用智能路由模式所有网页都打不开（包括国内网站）。。
我使用直连，GAE自动切换都能正常浏览相应网站。 
重启XXnet，或者关闭智能路由模块然后重新打开模块，智能路由模式就能正常联网了。昨天也出现过一次。  win10 1803 64bit，XX-Net 3.13.0

**Comment by SeaHOH** [comment]
还需要日志，单开个 issues。

**Comment by yeezylife** [comment]
看了看日志最早只有21：30左右的了 再出现类似情况我第一时间发
