### ISSUE TITLE
mac x-tunnel 无法正常使用

### ISSUE THREAD

**Issue by i5possible** [XX-net/XX-Net#11723]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
使用版本3.12.11

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？
查看过相关的的issues，"server_host": "v11.xx-net.net" 已添加，所有前端均异常，使用北美服务器，流量还有1100多GB未到期

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
X-Tunnel 状态信息
全局
属性	值
请求数	121
响应时间	0
往返数	1873
较慢	70
重传	4661
超时	7970
当前速度	Up: 0.0 B/s / Down: 0.0 B/s
使用总量	Up: 57.9 KB / Down: 3.4 MB
GAE 前端
属性	值
Score	False
成功数	0
失败数	0
工作数	0
使用总量	Up: 0.0 B / Down: 0.0 B
Cloudflare 前端
属性	值
Score	False
成功数	181
失败数	352
工作数	0
使用总量	Up: 57.9 KB / Down: 3.4 MB
Cloudfront 前端
属性	值
Score	False
成功数	0
失败数	65
工作数	2
使用总量	Up: 0.0 B / Down: 0.0 B
Heroku 前端
属性	值
Score	False
成功数	0
失败数	0
工作数	0
使用总量	Up: 0 / Down: 0
TLS_Relay 前端
属性	值
Score	False
成功数	0
失败数	0
工作数	0
使用总量	Up: 0.0 B / Down: 0.0 B

XX-Net Status:

sys-platform: x86_64, Darwin-17.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
os-release: 17.2.0
os-detail: Release:10.13.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by JemmyLuck** [comment]
同样问题，mac x-tunnel 登录成功完全靠运气，登录上也网速也非常慢。相同网络下windows台式机则可基本正常浏览网页。

**Comment by SeaHOH** [comment]
只有 Cloudflare 前端在工作，而且干扰大。
>ipv6-status: Fail

把 gae_proxy 调整好，这个要容易点。
