### ISSUE TITLE
ubuntu18.04+miredo+gae没成功过，可以ping通test-ipv6.com

### ISSUE THREAD

**Issue by WilliamShi** [XX-net/XX-Net#11728]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
y

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
y

* 是否以相关关键词搜索过类似 issues？
y

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
XX-Net Status:

sys-platform: x86_64, Linux-4.8.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #48-Ubuntu SMP Fri Mar 24 11:46:39 UTC 2017
os-release: 4.8.0-45-generic
os-detail: Dist:Ubuntu; Version:18.04; ID:bionic
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.12+
openssl-version: 17.5.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2997
network-status: unknown
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 321
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
你需要 ping 的是 v6.test-ipv6.com，之所以不成功的可能有：
1. 没安装到位。
1. NAT 类型不支持。
1. 有干扰。

**Comment by carlchan99** [comment]
命令行ifconfig看一下也没有teredo连接，没有的话运行一下sudo service miredo restart看看。

**Comment by WilliamShi** [comment]
> 你需要 ping 的是 v6.test-ipv6.com，之所以不成功的可能有：
> 
> 1. 没安装到位。
> 2. NAT 类型不支持。
> 3. 有干扰。

 v6.test-ipv6.com 这个也能ping通
没安装到位。
       可以说说看没安装到位有哪些大概率情况吗 ，因为我以前也用过没问题的，我是clone之后checkout了3.13.0用的
NAT 类型不支持。
       这个如果不支持的话是不是需要更换路由器，具体怎么看NAT是否支持啊，或者哪里有文档
有干扰。
       这个怎么办，自己安装dns么？
Thanks

**Comment by WilliamShi** [comment]
> 命令行ifconfig看一下也没有teredo连接，没有的话运行一下sudo service miredo restart看看。

能看到有ipv6地址，ping v6.test-ipv6.com也能通

**Comment by SeaHOH** [comment]
才发现你之前居然用那么旧的版本。

> 能看到有ipv6地址，ping v6.test-ipv6.com也能通

这样的话，网络应该没有问题了。
选个比较新的版本看能用不。

**Comment by carlchan99** [comment]
> > 命令行ifconfig看一下也没有teredo连接，没有的话运行一下sudo service miredo restart看看。
> 
> 能看到有ipv6地址，ping v6.test-ipv6.com也能通
注意到你xxnet的版本是3.3.1，这版本很老了吧，不妨用最新的几个版本试一试。====》这排除一下软件版本本身的问题。
我也是用ubuntu，在不同机子和不同的网络都有在用xxnet，下载后根据它的wiki简单配置一下，好像没有过什么波折，如有条件建议试一下在不同机子、不同网络下是不是有同样的问题。

**Comment by WilliamShi** [comment]
> > > 命令行ifconfig看一下也没有teredo连接，没有的话运行一下sudo service miredo restart看看。
> > 
> > 
> > 能看到有ipv6地址，ping v6.test-ipv6.com也能通
> > 注意到你xxnet的版本是3.3.1，这版本很老了吧，不妨用最新的几个版本试一试。====》这排除一下软件版本本身的问题。
> > 我也是用ubuntu，在不同机子和不同的网络都有在用xxnet，下载后根据它的wiki简单配置一下，好像没有过什么波折，如有条件建议试一下在不同机子、不同网络下是不是有同样的问题。

我用的是3.13.0和3.12.11，两个都试过，但不知为何显示的却是3.3.1

**Comment by WilliamShi** [comment]
> 才发现你之前居然用那么旧的版本。
> 
> > 能看到有ipv6地址，ping v6.test-ipv6.com也能通
> 
> 这样的话，网络应该没有问题了。
> 选个比较新的版本看能用不。

我正好想问这个问题，我用的是3.13.0和3.12.11，两个都试过，但不知为何显示的却都是3.3.1

**Comment by SeaHOH** [comment]
> 我正好想问这个问题，我用的是3.13.0和3.12.11，两个都试过，但不知为何显示的却都是3.3.1

不，我能肯定你贴的第一个结果是 3.3.1。
设置界面中可以切换版本。

**Comment by WilliamShi** [comment]
> > 我正好想问这个问题，我用的是3.13.0和3.12.11，两个都试过，但不知为何显示的却都是3.3.1
> 
> 不，我能肯定你贴的第一个结果是 3.3.1。
> 设置界面中可以切换版本

虽然问题已经关了，而且我下载了zip文件后，一切都ok了，但是我如果clone repository，然后checkout，无论我用较新的tag还是master都有问题，版本显示不对

**Comment by SeaHOH** [comment]
虽然不知道你具体怎么做的，但是你的方法肯定有哪里错误了，你只需要再 clone 一次不同的版本到同一个文件夹就会发现一些问题。

**Comment by WilliamShi** [comment]
> 虽然不知道你具体怎么做的，但是你的方法肯定有哪里错误了，你只需要再 clone 一次不同的版本到同一个文件夹就会发现一些问题。

找到问题了，不知道为什么version.txt被改成了3.3.1所以一直显示3.3.1，重新checkout version.txt就一切都好了。另外帮我看看下面我这个状态良好吗？谢谢


Property | Value
-- | --
IPv4 Status | OK
IPv6 Status(How enable) | OK
Good IPv4 Number | 0
Good IPv6 Number | 98
All IP Number | 100
XX-Net Status | working
IP Quality | 434
Connection Pool(Help) | new:0 h1:23 h2:1
Browser Proxy Setting | OK
CA status(Download) | OK
Number of IP-Scanning Threads(Settings) | 2
