### ISSUE TITLE
win10换到win7之后可用ip变成了0，和win10的IP段一样，win10的时候正常，换成win7就不能用了

### ISSUE THREAD

**Issue by wsjzjt** [XX-net/XX-Net#11734]
win10换到win7之后可用ip变成了0，和win10的IP段一样，win10的时候正常，换成win7就不能用了。

想问下有解决办法吗

**Comment by AnyWAT** [comment]
可用 ip 貌似并不能永保可用，如果此时再换到Win10，或许与Win7一样都不能用了😂
参考： #11291
