### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by 2458141652** [XX-net/XX-Net#11738]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
xxnet-version: 3.12.11
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 2
ip-quality: 452
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
worker: h1:0 h2:0 ——连接池归零
scan-ip-thread-num: 2 ——描述没关闭某开关
is-idle: 1 ——空闲
Appid_Working: false ——没工作
Appids_Out_Of_Quota: true ——有ID流量已完
https://github.com/XX-net/XX-Net/issues/11719#issuecomment-444434059

**Comment by 2458141652** [comment]
那请问如何配置呢？

**Comment by AnyWAT** [comment]
😱请高抬贵鼠，当光标成手型时。。。
