### ISSUE TITLE
怎么完全清除已安装版本？

### ISSUE THREAD

**Issue by JakeWoki** [XX-net/XX-Net#11730]
win10使用几个版本安装都无法切换代理模式，想清除干净再重新安装试试。注册表什么的有哪些要删除的？怎么才能完全清除干净？

**Comment by AnyWAT** [comment]
> win10使用几个版本安装都无法切换代理模式

安装了Python 3 的Win10也是无法在托盘图标切换，貌似与XX-Net 无关，因为同一文件夹下的XX-Net 在同一电脑的另一Win10或Win7系统下仍旧完全正常。手动设置正确即可
IE 内设置系统全局代理（如在系统设置内设置则无需填写协议）：
GAE HTTP 8087
X-TUNNEL HTTP 1080
智能路由 HTTP 8086
PAC http://127.0.0.1:8086/proxy.pac

**Comment by JakeWoki** [comment]
@AnyWAT 没看懂[/joy]Google Chrome怎么设置？

**Comment by AnyWAT** [comment]
> Google Chrome怎么设置？

意思是用代理扩展，配合“取消全局代理”嘛
