### ISSUE TITLE
XX-Net扫描IP不能区分无效IP

### ISSUE THREAD

**Issue by xyuanmu** [XX-net/XX-Net#1173]
最近使用XX-Net遇到这种情况，就是打开翻墙页面一片空白，怎么刷新都是空白，过一段时间恢复正常。这几天出现得更加频繁，看了日志和good_ip后发现原来是错误的gvs ip引起的，这些ip在checkgoogleip里测试全都在ip_tmperror.txt中，但是XX-Net却误判为gvs ip而且延时很低，使用后导致空白页面，例如下面列举的韩国和美国ip段。目前的做法就是发现这类ip再从ip库中删除，但是治标不治本，希望能判别这类ip提高扫描的准确性，不甚感激。
```
121.78.52.0-121.78.52.255
121.78.71.0-121.78.71.255
121.78.74.0-121.78.74.255
121.78.206.0-121.78.206.255
192.119.16.0-192.119.16.255
192.119.20.0-192.119.20.255
192.119.22.0-192.119.24.255
192.119.29.0-192.119.29.255
```

**Comment by Lrevor** [comment]
确实如此，有些IP的服务器 server_type:Apache，但是也被记录成gws了

Oct 09 11:28:59 - [INFO] ==>192.119.23.68
Oct 09 11:28:59 - [INFO] SSL use version:TLSv1_2
Oct 09 11:29:01 - [DEBUG] conn: 345  handshake:702
Oct 09 11:29:01 - [INFO] 192.119.23.68 CN:air101.sfo101.googlefiber.net
Oct 09 11:29:01 - [DEBUG] app check time:376
Oct 09 11:29:01 - [DEBUG] =======app check ok: 192.119.23.68
Oct 09 11:29:03 - [DEBUG] conn: 338  handshake:1539
Oct 09 11:29:03 - [INFO] 192.119.23.68 CN:air101.sfo101.googlefiber.net
Oct 09 11:29:03 - [INFO] server_type:Apache time:348
Oct 09 11:29:03 - [INFO] ========== 192.119.23.68 type:Apache domain:air101.sfo101.googlefiber.net handshake:1539

**Comment by xxnet** [comment]
确实，这些ip 对于不存在的地址也返回 200。

已经修复，发布新版2.5.3，请测试

2015-10-09 11:31 GMT+08:00 R·Shishioh <notifications@github.com>:

**Comment by xyuanmu** [comment]
@xxnet 太棒了，这次测试结果非常好，没有出现错误的ip了。

**Comment by AlephAlpha** [comment]
之前遇到的空白页原来是这么回事。谢谢。
