### ISSUE TITLE
谁能推荐一个靠谱的收费的shadowsock翻墙提供商？

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#11737]
目前正在使用的一家，说是将停止新购服务，只能用几个月了。感谢！

**Comment by gushaonan1991** [comment]
同问

**Comment by horizon0514** [comment]
搬瓦工，自己搭一个。

**Comment by gh030119** [comment]
我，速度一般12一个月
邮箱:hao@54sxh.cn

**Comment by CodeSheng** [comment]
我这速度很快，12/月 wx tuotujiasu

**Comment by farshidvahid** [comment]
感谢楼上两位！

**Comment by gh030119** [comment]
需要吗，要的话可以联系我的邮箱

**Comment by broardshore** [comment]
还是自己买虚机搭梯子的结点比较爽，一用就停不下来，目前本人用的是亚马逊的免费一年的服务，每个月上下共30G流量。

**Comment by farshidvahid** [comment]
> 还是自己买虚机搭梯子的结点比较爽，一用就停不下来，目前本人用的是亚马逊的免费一年的服务，每个月上下共30G流量。

感谢指点！但我真的是技术小白，youtube上看了一下教程，对我而言真的太复杂了。目前正使用Ghelper,还不错。实在不行再走这条路吧。

**Comment by gh030119** [comment]
我可以提供我的QQ或者微信都是1980835412




------------------ 原始邮件 ------------------
发件人: "farshidvahid"<notifications@github.com>; 
发送时间: 2019年6月12日(星期三) 下午2:09
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com>; 
抄送: "松小昊"<hao@54sxh.cn>; "Comment"<comment@noreply.github.com>; 
主题: Re: [XX-net/XX-Net] 谁能推荐一个靠谱的收费的shadowsock翻墙提供商？ (#11737)



 
还是自己买虚机搭梯子的结点比较爽，一用就停不下来，目前本人用的是亚马逊的免费一年的服务，每个月上下共30G流量。
  
感谢指点！但我真的是技术小白，youtube上看了一下教程，对我而言真的太复杂了。目前正使用Ghelper,还不错。实在不行再走这条路吧。

**Comment by gh030119** [comment]
需要的话联系我




------------------ 原始邮件 ------------------
发件人: "bs"<notifications@github.com>; 
发送时间: 2019年6月12日(星期三) 中午1:28
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com>; 
抄送: "松小昊"<hao@54sxh.cn>; "Comment"<comment@noreply.github.com>; 
主题: Re: [XX-net/XX-Net] 谁能推荐一个靠谱的收费的shadowsock翻墙提供商？ (#11737)




还是自己买虚机搭梯子的结点比较爽，一用就停不下来，目前本人用的是亚马逊的免费一年的服务，每个月上下共30G流量。

**Comment by gh030119** [comment]
我要求修改你的虚假言辞

**Comment by SeaHOH** [comment]
不要自爆，小心喝茶。

**Comment by gh030119** [comment]
> 不要自爆，小心喝茶。

这弄得我很难受呀
