### ISSUE TITLE
转增x-tunnel流量

### ISSUE THREAD

**Issue by nlpsuge** [XX-net/XX-Net#11739]
突然发现，流量还剩余非常多。想要的可以留下邮箱。我转赠给你们。

默认10G，更多更少需求的请说明。

PS：或许可以开发一个转增区这样的功能......

**Comment by alexbyrant** [comment]
kobebyrant236@gmail.com
十分感谢，好人一生平安

**Comment by cmw2051** [comment]
cmw2051@gmail.com   5g就好，谢谢

**Comment by aixiu** [comment]
4815563@gmail.com  好人一生平安

**Comment by nlpsuge** [comment]
@alexbyrant @aixiu @cmw2051 好了

**Comment by aixiu** [comment]
@nlpsuge thx!

**Comment by dragonstyle2** [comment]
394173771@qq.com  好人一生平安

**Comment by bb2bbdaye** [comment]
zhaojiangbao@gmail.com
祝你幸福

**Comment by ZhuBaohe** [comment]
ehoabuhz@gmail.com 谢谢楼主啦！

**Comment by amnaruto** [comment]
licheng.cao@gmail.com
我又来骗吃骗喝啦 :)

**Comment by nlpsuge** [comment]
@bb2bbdaye @ZhuBaohe @amnaruto ok
@dragonstyle2 帐号不存在

**Comment by ZhuBaohe** [comment]
> @bb2bbdaye @ZhuBaohe @amnaruto ok
> @dragonstyle2 帐号不存在

已经收到了，谢谢

**Comment by ConanWu** [comment]
zjjwulin@hotmail.com
谢谢

**Comment by lynAzrael** [comment]
lilinlee0716@gmail.com

**Comment by smeilence** [comment]
b592106229@gmail.com
感谢！

**Comment by kaka6119** [comment]
qym3779@gmail.com
 感谢分享

**Comment by dhxy5117** [comment]
dhxy5117@gmail.com 谢谢大哥哥

**Comment by wocaishiryr** [comment]
wocaishiryr@163.com
感谢感谢

**Comment by wocaishiryr** [comment]
wocaishiryr@outlook.com
感谢感谢

**Comment by wocaishiryr** [comment]
wocaishiryr@outlook.com这个账号的密码忘了,登不上去了
密码忘了能找回吗,用的google密码管理,但是好像没有保存;
新账号wocaishiryr@gmail.com

**Comment by sola86** [comment]
neilsola@gmail.com
感谢

**Comment by wpf940997721** [comment]
mr.wangpf@gmail.com   非常感谢

**Comment by wgqwgqwgq** [comment]
qq196304611@gmail.com感谢感谢

**Comment by wocaishiryr** [comment]
wocaishiryr@gmail.com 感谢

**Comment by huangya0201** [comment]
cyz0202@126.com 前来蹭流量，感谢

**Comment by hjr0** [comment]
hhhujr@gmail.com
Thx a lot!

**Comment by jxzswwk** [comment]
jxzswwk@gmail.com 蹭下流量，非常感谢。

**Comment by SeaHOH** [comment]
@nlpsuge 如不再赠送，请关闭。

**Comment by wchyumo2009** [comment]
conghui1988@gmail.com
多谢，随便来点

**Comment by fhq8800** [comment]
fhq8800@gmail.COM多谢

**Comment by HYL13** [comment]
kinghyl13@gmail.com 
多谢～

**Comment by jingyuzhu** [comment]
513029899@qq.com thx

**Comment by jxzswwk** [comment]
jxzswwk@gmail.com 非常感谢。

**Comment by nlpsuge** [comment]
@wocaishiryr 试试吧，应该可以找回密码的
