### ISSUE TITLE
PAC自动代理不能识别,请检查浏览器代理设置。

### ISSUE THREAD

**Issue by wiiii** [XX-net/XX-Net#11733]
![image](https://user-images.githubusercontent.com/16551444/49736316-bed1a500-fcc4-11e8-8ec4-39878d52dab2.png)
为什么我设置成pac自动代理,他就是检测不出啦xxnet,必须要全局代理才能连接?

**Comment by AnyWAT** [comment]
貌似软件检查代理及证书的 *.deja.com（必走GAE）没在PAC内。如代理正常可忽略😂
参照白名单 https://github.com/MatcherAny/whitelist.pac 的auto white 情景模式，并利用 http://127.0.0.1:8086/proxy.pac 可自建黑名单下的 auto switch 情景模式，随时添加并自动应用切换规则。
![default](https://user-images.githubusercontent.com/37962734/49737633-4d93f100-fcc8-11e8-8b87-1fd300527fe6.png)

**Comment by SeaHOH** [comment]
代理是拿来使用的，不是看着玩，能用不就好了。
下次更新会把 PAC 设置拿掉，直接用智能代理就行。
