### ISSUE TITLE
Windows下与系统已安装的Python冲突

### ISSUE THREAD

**Issue by kuletco** [XX-net/XX-Net#11731]
我是开发人员, 需要系统中配置Python环境, 当设置Python环境后, xx-net通过vbs脚本就无法启动了, 不过用start.bat脚本却能启动, 但是像启用ipv6等功能无法使用, 他们找的都是系统中的python而不是xx-net自带的python环境.

**Comment by SeaHOH** [comment]
你可以打开 start.bat 看看，有这么两句：
```bat
SET PYTHONPATH=
SET PYTHONHOME=
```

>  但是像启用ipv6等功能无法使用

如果你使用的 XX-Net 是较新的版本，因为环境变量会继承父进程，应该能正常运行才对。
