### ISSUE TITLE
Mac OS X 10.11出问题了

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#1174]
https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:07 - [DEBUG] create_ssl update ip:1.255.22.213 time:173
Oct 9 10:30:07 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:07 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:07 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:08 - [DEBUG] get ip:1.255.22.238 t:170
Oct 9 10:30:08 - [DEBUG] create_ssl update ip:1.255.22.238 time:170
Oct 9 10:30:08 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:08 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:08 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:08 - [DEBUG] get ip:87.245.196.141 t:1408
Oct 9 10:30:09 - [DEBUG] 1.255.22.236 fail
Oct 9 10:30:09 - [DEBUG] get ip:118.98.110.72 t:1408
Oct 9 10:30:09 - [DEBUG] create_ssl update ip:103.11.30.4 time:828
Oct 9 10:30:09 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:09 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:09 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:10 - [DEBUG] 128.0.169.238 fail
Oct 9 10:30:10 - [DEBUG] 144.131.80.212 fail
Oct 9 10:30:10 - [DEBUG] 62.24.158.216 fail
Oct 9 10:30:10 - [DEBUG] get ip:1.255.22.134 t:163
Oct 9 10:30:10 - [DEBUG] 177.35.203.54 fail
Oct 9 10:30:10 - [DEBUG] create_ssl update ip:1.255.22.134 time:163
Oct 9 10:30:10 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:10 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:10 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:10 - [DEBUG] get ip:1.255.22.211 t:165
Oct 9 10:30:10 - [DEBUG] get ip:1.255.22.166 t:166
Oct 9 10:30:10 - [DEBUG] 210.187.22.159 fail
Oct 9 10:30:10 - [DEBUG] create_ssl update ip:1.255.22.211 time:165
Oct 9 10:30:10 - [DEBUG] create_ssl update ip:1.255.22.166 time:158
Oct 9 10:30:10 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:10 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:10 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:10 - [DEBUG] 200.56.193.206 fail
Oct 9 10:30:10 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:10 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:10 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:10 - [DEBUG] get ip:1.255.22.249 t:167
Oct 9 10:30:10 - [DEBUG] get ip:1.255.22.207 t:169
Oct 9 10:30:11 - [DEBUG] get ip:1.255.22.230 t:170
Oct 9 10:30:11 - [DEBUG] 194.44.4.136 fail
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:1.255.22.207 time:157
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:11 - [DEBUG] get ip:1.255.22.250 t:174
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:1.255.22.249 time:279
Oct 9 10:30:11 - [DEBUG] get ip:1.255.22.145 t:182
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:1.255.22.230 time:166
Oct 9 10:30:11 - [DEBUG] get ip:118.98.111.135 t:328
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:1.255.22.250 time:161
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:1.255.22.145 time:149
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:11 - [DEBUG] get ip:118.98.111.132 t:243
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:118.98.111.135 time:251
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:11 - [DEBUG] get ip:175.28.1.153 t:266
Oct 9 10:30:11 - [DEBUG] get ip:118.98.111.139 t:337
Oct 9 10:30:11 - [DEBUG] get ip:118.98.106.201 t:288
Oct 9 10:30:11 - [DEBUG] create_ssl update ip:118.98.111.132 time:248
Oct 9 10:30:11 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:11 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:11 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:12 - [DEBUG] get ip:118.98.106.200 t:293
Oct 9 10:30:12 - [DEBUG] get ip:118.98.106.133 t:319
Oct 9 10:30:12 - [DEBUG] create_ssl update ip:175.28.1.153 time:287
Oct 9 10:30:12 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:12 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:12 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:12 - [DEBUG] get ip:222.165.163.178 t:1408
Oct 9 10:30:12 - [DEBUG] create_ssl update ip:118.98.106.201 time:286
Oct 9 10:30:12 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:12 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:12 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:12 - [DEBUG] create_ssl update ip:118.98.111.139 time:336
Oct 9 10:30:12 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:12 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:12 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:12 - [DEBUG] get ip:190.241.121.43 t:1408
Oct 9 10:30:12 - [DEBUG] get ip:119.110.118.133 t:1408
Oct 9 10:30:12 - [DEBUG] create_ssl update ip:118.98.106.200 time:403
Oct 9 10:30:12 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:12 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:12 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:12 - [DEBUG] create_ssl update ip:118.98.106.133 time:314
Oct 9 10:30:12 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:12 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:12 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:12 - [DEBUG] get ip:1.9.22.196 t:1408
Oct 9 10:30:12 - [DEBUG] 87.245.196.141 fail
Oct 9 10:30:12 - [DEBUG] get ip:31.210.208.216 t:1408
Oct 9 10:30:13 - [DEBUG] get ip:210.187.22.164 t:1408
Oct 9 10:30:13 - [DEBUG] get ip:1.255.22.174 t:152
Oct 9 10:30:13 - [DEBUG] get ip:1.255.22.214 t:153
Oct 9 10:30:13 - [DEBUG] create_ssl update ip:1.255.22.174 time:157
Oct 9 10:30:13 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:13 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:13 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:13 - [DEBUG] get ip:1.255.22.233 t:157
Oct 9 10:30:13 - [DEBUG] create_ssl update ip:1.255.22.214 time:171
Oct 9 10:30:13 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:13 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:13 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:13 - [DEBUG] 118.98.110.72 fail
Oct 9 10:30:13 - [DEBUG] get ip:1.255.22.203 t:158
Oct 9 10:30:13 - [DEBUG] create_ssl update ip:1.255.22.233 time:157
Oct 9 10:30:13 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:13 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:13 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:14 - [DEBUG] create_ssl update ip:1.255.22.203 time:160
Oct 9 10:30:14 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:14 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:14 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:14 - [DEBUG] get ip:1.255.22.147 t:163
Oct 9 10:30:14 - [DEBUG] get ip:64.233.188.188 t:185
Oct 9 10:30:14 - [DEBUG] get ip:58.27.27.197 t:280
Oct 9 10:30:14 - [DEBUG] create_ssl update ip:1.255.22.147 time:159
Oct 9 10:30:14 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:14 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:14 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:14 - [DEBUG] get ip:118.98.106.132 t:327
Oct 9 10:30:14 - [DEBUG] create_ssl update ip:64.233.188.188 time:205
Oct 9 10:30:14 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:14 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:14 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:15 - [DEBUG] get ip:103.7.200.79 t:347
Oct 9 10:30:15 - [DEBUG] create_ssl update ip:58.27.27.197 time:280
Oct 9 10:30:15 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:15 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:15 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:15 - [DEBUG] create_ssl update ip:118.98.106.132 time:310
Oct 9 10:30:15 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:15 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:15 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:15 - [DEBUG] create_ssl update ip:103.7.200.79 time:344
Oct 9 10:30:15 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Oct 9 10:30:15 - [DEBUG] GAE_Exception 1 'no appid can use'
Oct 9 10:30:15 - [WARNING] gae_exception:GAE_Exception() https://profile.ess.apple.com/WebObjects/VCProfileService.woa/wa/idsGetHandles
Oct 9 10:30:15 - [DEBUG] get ip:31.55.163.140 t:414
Oct 9 10:30:15 - [DEBUG] get ip:173.194.65.188 t:429
Oct 9 10:30:16 - [DEBUG] get ip:103.11.30.4 t:828
Oct 9 10:30:16 - [DEBUG] 222.165.163.178 fail

今天上午升级的，然后就这样了，已经重启等尝试，没有改变。
XX-Net Version	2.5.1
Python Version	2.7.10
Sys Platform	x86_64, Darwin-15.0.0-x86_64-i386-64bit
OS System	Darwin
OS version	Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64
OS release	15.0.0
OS detail	Release:10.11; Version:('', '', '') Machine:x86_64
language	
architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.5 Safari/537.36

Property	Value
Google IP num	3000
100th IP handshake(ms)	1478
connected link(帮助)	0,0
scaning ip thread num	43
block stat(帮助)	OK

**Comment by xxnet** [comment]
'no appid can use'

请检查你的appid

2015-10-09 10:32 GMT+08:00 causlayer <notifications@github.com>:

**Comment by causlayer** [comment]
appid是空的，我到配置里重新保存，再次运行，
working appids里会有我的appid,	
但马上我的appid就会跑到Out of Quota appids里，最后一个也不剩。

**Comment by causlayer** [comment]
好像是我appid流量的问题，换上默认的appid已经可以用了。
