### ISSUE TITLE
3.13.0 如何提高IP扫描线程！？

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#11752]
如题！设置是0-200 但最高于100就不生效了。。现在一个IP也没有 IPv4 v6 也一样0。 中午IPV4 竟然有40个

**Comment by kitkw** [comment]
如题！设置是0-200  但最高于100就不生效了。。现在一个IP也没有  IPv4 v6 也一样0。 中午IPV4 竟然有40个

**Comment by SeaHOH** [comment]
发布中有说明，请仔细查看。
