### ISSUE TITLE
延迟高，有效IP数非常少

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#11750]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AeneasZhu** [comment]
Google、Youtube基本上上不去，有效IP数只有一两个，延迟高达几千，怎么破？今晚突然这样，上午还好好的

**Comment by SeaHOH** [comment]
#11748

**Comment by AeneasZhu** [comment]
还是不行呀，今天一早打开了还是一样IP延迟9999

**Comment by AnyWAT** [comment]
3.13.1👍
