### ISSUE TITLE
2.5.3 版不可用

### ISSUE THREAD

**Issue by rarest** [XX-net/XX-Net#1175]
Oct 09 13:42:45 - [INFO] detect Win10, enable connect concurent control, interval:40
Oct 09 13:42:45 - [INFO] load ip range file:E:\Tools\XX-Net-2.5.3\gae_proxy\local\ip_range.txt
Oct 09 13:42:45 - [INFO] load google ip_list num:0, gws num:0
Oct 09 13:42:45 - [INFO] SSL use version:TLSv1
Oct 09 13:42:45 - [DEBUG] ## GAEProxy set keep_running: True
Oct 09 13:42:45 - [INFO] ------------------------------------------------------
Oct 09 13:42:45 - [INFO] Python Version : 2.7.9
Oct 09 13:42:45 - [INFO] Listen Address : 127.0.0.1:8087
Oct 09 13:42:45 - [INFO] GAE APPID : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Oct 09 13:42:45 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Oct 09 13:42:45 - [INFO] ------------------------------------------------------
Oct 09 13:42:45 - [INFO] no CA file exist
Oct 09 13:42:45 - [INFO] clean old site certs
Oct 09 13:42:45 - [INFO] generate CA file:E:\Tools\XX-Net-2.5.3\data\gae_proxy\CA.crt
Oct 09 13:42:45 - [INFO] create ca
Oct 09 13:42:45 - [INFO] server 127.0.0.1:8087 started.
Oct 09 13:42:45 - [INFO] server 127.0.0.1:8086 started.
Oct 09 13:42:46 - [INFO] GAE CONNECT clients2.google.com:443
Oct 09 13:42:47 - [DEBUG] GAE CONNECT POST https://clients2.google.com/domainreliability/upload
Oct 09 13:42:47 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Oct 09 13:42:47 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=164e1f99-d2dd-4803-a463-c59fe4911a3b&version=2.5.3
Oct 09 13:42:56 - [INFO] GAE CONNECT clients4.google.com:443
Oct 09 13:42:56 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=3l7MzBkfsTci2zGrBKKhpg%3D%3D
Oct 09 13:42:56 - [WARNING] no gws ip
Oct 09 13:43:02 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:02 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:02 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:02 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:06 - [WARNING] no gws ip
Oct 09 13:43:11 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:11 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:16 - [WARNING] no gws ip
Oct 09 13:43:17 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:17 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:17 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:17 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:26 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:26 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:26 - [WARNING] no gws ip
Oct 09 13:43:32 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:32 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:32 - [DEBUG] GAE_Exception 2 'try max times'
Oct 09 13:43:32 - [WARNING] gae_exception:GAE_Exception() https://clients2.google.com/domainreliability/upload
Oct 09 13:43:32 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:32 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:32 - [DEBUG] GAE_Exception 2 'try max times'
Oct 09 13:43:32 - [WARNING] gae_exception:GAE_Exception() https://xxnet-update.appspot.com/update.json?uuid=164e1f99-d2dd-4803-a463-c59fe4911a3b&version=2.5.3
Oct 09 13:43:36 - [WARNING] no gws ip
Oct 09 13:43:41 - [DEBUG] create ssl timeout fail.
Oct 09 13:43:41 - [DEBUG] create_ssl_connection fail
Oct 09 13:43:41 - [DEBUG] GAE_Exception 2 'try max times'
Oct 09 13:43:41 - [WARNING]LOG_EXCEPT: gae_exception:GAE_Exception() https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=3l7MzBkfsTci2zGrBKKhpg%3D%3D, Except:[Errno 9] Bad file descriptor
Oct 09 13:43:46 - [WARNING] no gws ip

**Comment by rarest** [comment]
GAEProxy状态信息

系统版本

Property	Value
XX-Net Version	2.5.3
Python Version	2.7.9
Sys Platform	AMD64, Windows-8-6.2.9200
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	8
状态

Property	Value
Google IP num	0
100th IP handshake(ms)	-1
connected link(帮助)	0,0
scaning ip thread num	50
block stat(帮助)	OK
Appid

Property	Value
working appids	xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Out of Quota appids	
Not Exist appids

**Comment by Cat7373** [comment]
你还没扫到可用的IP，多等会吧。

**Comment by xyuanmu** [comment]
建议升级的时候保留data文件夹，里面有配置以及扫好的ip

**Comment by Cat7373** [comment]
当我看到2.5.3的更新说明后，果断删了所有好IP重新扫了- -
虽然不知道影响有多大- -
反正我前两天刚从2.0.5更新到2.5.1，扫到的IP也不多- -

**Comment by rarest** [comment]
全新安装的啊

**Comment by rarest** [comment]
重新下载的2.5.3

**Comment by Cat7373** [comment]
@rarest 多等会，等扫到可用IP就可以用了。

**Comment by rarest** [comment]
@Cat7373 嗯，重新启动下电脑，再打开
Google IP num	3
100th IP handshake(ms)	-1
connected link(帮助)	11,14
scaning ip thread num	200
block stat(帮助)	OK

但100th IP handshake(ms)这个是否正常呢？

**Comment by Cat7373** [comment]
@rarest 这个是正常的，在你的可用IP数量不到101个的时候，这个数字会一直保持 -1
虽然写的是第100个，不过从代码来看，实际是101个。。。。。。

**Comment by rarest** [comment]
@Cat7373 嗯，多谢，另外具备什么条件才能学习xxnet的代码呢？我是搞c++的，做android和ios 版的    [美摄]app，不会python，还有python的版本为什么用2.7.9呢？而不是用最新的版本?

**Comment by Cat7373** [comment]
@rarest Python版本的问题，是因为Goagent就用的Python2.x
而2.x跟3.x有不少区别，因此用了2.x
以上为个人猜测- -

以及，Python很好学，尤其你又有编程基础- - 就更好学了- -

**Comment by rarest** [comment]
@Cat7373 扫描ip好慢啊，发现2.5.3为什么ip一上来是0个呢？直接2.4版本下载后打开有近3000个ip
Google IP num	5
100th IP handshake(ms)	-1
connected link(帮助)	10,60
scaning ip thread num	200
block stat(帮助)	OK

**Comment by rarest** [comment]
@Cat7373 嗯，有空学习下python

**Comment by Cat7373** [comment]
之前的版本出厂自带了3000个可用IP，后面的版本删掉了，因为这3000个几乎都被封干净了- -

**Comment by rarest** [comment]
不会相关部门也下个xxnet，找到那3000个ip直接干掉？

**Comment by Cat7373** [comment]
那谁知道呢

**Comment by xxnet** [comment]
@rarest
   python 推荐使用pycharm IDE，可以解析跳转和单步跟踪。
   研究xx-net 除了python
的语法（非常容易理解），另外需要SSL和HTTP协议的底层相关知识，遇到不理解的去看看RFC或者google就好了。

   欢迎参与项目开发

2015-10-09 15:32 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
@xxnet 其实我都是用Sublime_text的- -
反正我不主要用Python- -
懒得专门装个IDE- -

**Comment by xxnet** [comment]
工具是一个爱好问题，每个人有自己熟手的好工具。
其实pycharm也有不爽的时候，经常CPU跑高，占用资源多。
只是在语法解析和集成方面目前最好，适合我这种懒人使用。

sublime_text 专注于快，这点其实在编程中非常重要。

2015-10-09 15:39 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by rarest** [comment]
@xxnet @Cat7373 多谢指导，先装个pycharm IDE试试，有不懂的地方再向你们请教，对xx-net好用的软件表示感谢啊，希望越做越好啊！

**Comment by Dannywanxyz** [comment]
@Cat7373 是哪里人啊？

**Comment by Cat7373** [comment]
天朝

**Comment by Dannywanxyz** [comment]
@Cat7373 很少有妹子知道并且使用这个xxnet工具的

**Comment by Dannywanxyz** [comment]
@Cat7373 天朝哪里？

**Comment by Dannywanxyz** [comment]
@xxnet 我也是用pycharm IDE，公司其他同事也用的pycharm，挺好用的

**Comment by simonasd** [comment]
@Dannywanxyz  @Cat7373 众所周知的原因，建议大家尤其是贡献者尽量保持匿名。前车之鉴都知道，就不多提了。

@Cat7373 ，看了一下你的资料，存在被查水表的可能。（只是出于谨慎）如果想要避免，建议清理相关痕迹，然后换个马甲。
