### ISSUE TITLE
炸了?

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#11756]
有效ip 0， 搜不到ip ， ip延迟 9999

**Comment by Farewellly** [comment]
我也是，昨晚还用的好好的

**Comment by jibp** [comment]
今天一打开 就炸了 ，不行了

**Comment by josephly** [comment]
看来是个普遍现象，昨天好像就不行了

**Comment by zeitgeist8080** [comment]
不能用了

**Comment by dmankacio** [comment]
墙又变高了，MLGBD

**Comment by garbagezcx** [comment]
已经废了。

**Comment by zzgpku** [comment]
王炸

**Comment by XuJ0e** [comment]
我这边也是找到一个IP过一会儿又没有了

**Comment by SeaHOH** [comment]
#11748

**Comment by Peterpey** [comment]
我试过了 ip都挂了

**Comment by SeaHOH** [comment]
谁也没欠着谁，想着急就随便吧。
但是你们要想到开了这么多无用贴后，以后找点东西是多么的麻烦。

**Comment by Peterpey** [comment]
@SeaHOH   别浪费时间回复了， 赶紧想办法吧

**Comment by SeaHOH** [comment]
没欠你的哈

**Comment by Peterpey** [comment]
@SeaHOH   是，作为一个普通用户，我只是把遇到的问题提出来， 等待有责任心的app制作者或者管理员出来提供解决方法， 像你这样的，没谁会指望你。

**Comment by SeaHOH** [comment]
说得你好光明正大的样子。
我给这个帖子引用了它重复的问题，里面正在讨论，X 大也在想法给出解决方案，你为什么不过去参与呢？

**Comment by dmankacio** [comment]
这并不是梯子的问题好吗，就算不懂技术也应该懂得尊重和感恩吧，为什么有人会理直气壮的白吃萝卜还嫌辣？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11759#issuecomment-448854172

**Comment by Peterpey** [comment]
@dmankacio  哇 你好懂 sb
