### ISSUE TITLE
3.12.2 稳定版  今天炸了  

### ISSUE THREAD

**Issue by mionfan** [XX-net/XX-Net#11754]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by mionfan** [comment]
[WARNING] not enough ip  
准确说昨天晚上炸的  ipv6的有效IP都没用了。。。。

**Comment by mionfan** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 71
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 100

**Comment by zxk7516** [comment]
跟我一样，感觉是gfw2.0收网了。包子nb

**Comment by zqchina** [comment]
我的也一样。IPv6 IP数0.

**Comment by SeaHOH** [comment]
#11748

**Comment by mionfan** [comment]
看来都完了。。。。。。。。。。。。
