### ISSUE TITLE
状态正常，打开google失败

### ISSUE THREAD

**Issue by runthinker** [XX-net/XX-Net#11757]
600:gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/gae_exception:'602:ip not support GAE' https://www.google.com.hk/
提示这个

**Comment by Peterpey** [comment]
目前王炸

**Comment by charles203** [comment]
我也一样，难道是崩了

**Comment by vibb** [comment]
我也是一样，不知道如何解决

**Comment by SeaHOH** [comment]
#11748
