### ISSUE TITLE
# [求助] 8086 端口能不能通过修改config.json来实现，如何实现？

### ISSUE THREAD

**Issue by GerGitHub** [XX-net/XX-Net#11765]
## 开启端口问题

XX-Net 3.13.1 版本
平台 网件R7000 刷 Tomato AD

XX-Net 正常开启运行，首次运行先要WinSCP 进入，修改 */data/launcher/config.yaml
    allow_remote_connect: 0 , 将 0 改为 1
这样可以在浏览器输入 路由IP:8085 打开WEB网页

还要修改 */data/gae_proxy/config.json
添加
{
  "listen_ip": "0.0.0.0",
  "listen_port": 8087
}
这样才能开启8087 代理端口

## 问题：
8087可以通过修改*/data/gae_proxy/config.json 来开启，但8086本人却不知道如何开启，proxy.pac代理置也无法实现，还有CA.crt证书下载现在也不走8086端口下载了
目前的解决方法是在 python * /code/default/launcher/start.py  后面加上  -allow_remote， 但是这样有个问题就是把 */data/gae_proxy/config.json 也修改了，自己添回修改的内容也被删了；

**Comment by SeaHOH** [comment]
> 目前的解决方法是在 python * /code/default/launcher/start.py 后面加上 -allow_remote， 但是这样有个问题就是把 */data/gae_proxy/config.json 也修改了，自己添回修改的内容也被删了；

你是说 listen_ip 之外还修改了什么？

**Comment by GerGitHub** [comment]
> > 目前的解决方法是在 python * /code/default/launcher/start.py 后面加上 -allow_remote， 但是这样有个问题就是把 */data/gae_proxy/config.json 也修改了，自己添回修改的内容也被删了；
> 
> 你是说 listen_ip 之外还修改了什么？

如果只是在 config.json 设置 listen_ip :  0.0.0.0 也只是解决8087端口， 8086是没有开启的，只有启动命令后面加上 -allow_remote

**Comment by SeaHOH** [comment]
你不是说使用`-allow_remote`后修改了你的配置嘛，按设计只会修改 listen_ip，你的被修改了什么？

**Comment by GerGitHub** [comment]
主要目的是想不用 -allow_remote ，而是用配置gae_proxy 或 smart_router 下的 config.json 来启用8086端口，找了一圈，好像也对开启8086不知所以， -allow_remote似乎是唯一的办法；

**Comment by SeaHOH** [comment]
#11644
因为 8087 是默认值，所以任何时候保存配置时与默认值相同都会被删掉。

**Comment by GerGitHub** [comment]
> #11644
> 因为 8087 是默认值，所以任何时候保存配置时与默认值相同都会被删掉。

还有一个问题，原有的版本都是通过8086来下载证书和proxy.pac要配置代理，这样可以设置路由防火墙不在外网暴露8085的WEB管理，现在8086下无法下载证书，要通过8085，那这样8085端口就暴露出来了，那么外界就很容易通过IP:8085来到WEB管理页，那么你的google APPID, EMail,密码都可能被暴了；

**Comment by SeaHOH** [comment]
> #11644

单独配置看这里。。。

> 原有的版本都是通过8086来下载证书和proxy.pac要配置代理

现在默认也是 8086。
