### ISSUE TITLE
显示一切正常但不能访问网页怎么办？

### ISSUE THREAD

**Issue by Illchange** [XX-net/XX-Net#11760]
我试用其他翻墙VPN后 XXnet不能用了怎么办？
显示一切正常 但打不开youtube
600:gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/gae_exception:'602:ip not support GAE' https://www.youtube.com/

**Comment by SeaHOH** [comment]
下载新版

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
