### ISSUE TITLE
下载最新的3.13.1版本

### ISSUE THREAD

**Issue by LoryPang** [XX-net/XX-Net#11762]
我更新到最新版的3.13.1版本就OK了

**Comment by maoyali** [comment]
请问有没有最新的Android版的

**Comment by AnyWAT** [comment]
手动修改总 IP数默认的100为300-500？

**Comment by cccwhatuneed** [comment]
> 还是不行，看youtube几秒就卡住，ip数变成0，等一会扫出几个是，然后看youtube又是几秒变0

说明你没有正常更新成功

**Comment by StormragerCN** [comment]
新版一切正常

**Comment by chenroaming** [comment]
不行，ipv6地址为0

**Comment by navylover** [comment]
是的，我这也是一直为0，到底应该怎么办啊。

**Comment by chenroaming** [comment]
> 是的，我这也是一直为0，到底应该怎么办啊。

也不是一直为0，还会是个位数，不过一样上不了，估计GAE服务器有问题
