### ISSUE TITLE
搜索到可用IP后秒断

### ISSUE THREAD

**Issue by RealShine** [XX-net/XX-Net#11773]
长久以来都很好用，由昨天起无法正常使用，今天更新到最新版后情况依旧。表现如下：

每当搜索到可用IP，状态显示已经连通，但一两秒钟内就变成红字无法连通，有时很快又搜索到可用IP，又变成蓝字已经连通，但一两秒钟内又变成红字无法连通。即使显示有很多可用IP，情况依然如此，访问不了youtube，就算有十多个可用IP也会在短时间内变成零个。

我估计GFW能识别XXnet的连接特征强行中断连接。

附上诊断信息：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.3
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:3
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 990
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
试试 https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by RealShine** [comment]
> 试试 [#11769 (comment)](https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215)

按此方法已经能顺利访问油管。谢谢！

**Comment by SeaHOH** [comment]
请前往讨论，此处关闭。

**Comment by AnyWAT** [comment]
🤣参考神奇操作可有限恢复？https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
