### ISSUE TITLE
突然停电之后重启，firefox代理设置和证书状态全变成"fail"，无法改变

### ISSUE THREAD

**Issue by imudie123** [XX-net/XX-Net#11778]
昨日小区突然停电，20分钟之后电脑重启，
原来用得好好的firefox，代理设置和证书状态就一直显示"fail"，经过：
1，反复尝试firefox代理各种设置，无效。
2，删除证书、重新导入证书无效。
3，删除ca.crt、删除文件夹certs，以管理员身份运行xxnet，无效。
4，彻底删除firefox后重装，再设置代理导入证书，无效。
到底问题会出在哪里？还有什么方法是我没有试过的？请指点一下，不胜感激。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:92 ipv4:0 ipv6:92
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 265
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）

**Comment by imudie123** [comment]
#AnyWAT
C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.16.104:51962
外部 NAT 映射    : 120.36.234.228:22958

多谢！请帮忙看看！

**Comment by AnyWAT** [comment]
隐私 （无需IP地址的2行）

**Comment by imudie123** [comment]
@AnyWAT 

是在CMD里面运行netsh int ipv6 show teredo吗？

**Comment by AnyWAT** [comment]
试试（部分）：神奇操作，或许有救：https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by imudie123** [comment]
@AnyWAT 
并非没有Ip，只是firefox不能用，显示代理设置和证书状态"fail"
chrome，还是可以用的。

但是我比较习惯用firefox，想了解如何解决代理设置和证书状态fail的问题。
感谢！

**Comment by AnyWAT** [comment]
哦，问题更清晰——XX-Net 正常，只是FireFox 代理设置和证书状态"fail"
代理扩展或用浏览器内GAE（全局），最好用GAE-Proxy 自动切换（可自添加任意切换规则）
代理扩展图标一定有附加数字——未加载资源，或许有127.0.0.1及*.deja.com，前者必走“直接连接”，后者必走GAE（哪怕已添加过了，也得像没有一样再添加。。。）

**Comment by AnyWAT** [comment]
> 1，反复尝试firefox代理各种设置，无效。
> 2，删除证书、重新导入证书无效。
> 3，删除ca.crt、删除文件夹certs，以管理员身份运行xxnet，无效。
> 4，彻底删除firefox后重装，再设置代理导入证书，无效。

貌似以上操作纯属多余😂

**Comment by imudie123** [comment]
@AnyWAT

感谢，全局gae就好了。可惜只有2ip，还延迟9999。没办法使用。

还是要谢谢大佬。

**Comment by AnyWAT** [comment]
😱LS与7楼矛盾？重温6楼？
