### ISSUE TITLE
又炸了？

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#11774]
新版本3.13.1 已经玩不起来了， 有效ip0，搜不到ip，延迟9999

**Comment by StormshadowRay** [comment]
随随便便就扫出100个可用的，拿去吧。
2607:f8b0:4005:801::2014
2607:f8b0:4005:802::2014
2607:f8b0:4009:815::2014
2607:f8b0:400a:800::2014
2607:f8b0:4007:80b::2014
2607:f8b0:4005:804::2014
2607:f8b0:400b:808::2014
2607:f8b0:400a:803::2014
2607:f8b0:4009:816::2014
2607:f8b0:4006:812::2014
2607:f8b0:4004:80c::2014
2607:f8b0:4000:80d::2014
2607:f8b0:4007:809::2014
2607:f8b0:4004:802::2014
2a00:1450:400e:807::2014
2607:f8b0:4000:806::2014
2607:f8b0:400e:c03::99
2404:6800:4004:807::2014
2607:f8b0:4009:807::2014
2607:f8b0:4006:810::2014
2607:f8b0:4009:803::2014
2607:f8b0:4012:80a::2014
2607:f8b0:4006:813::2014
2607:f8b0:4006:819::2014
2607:f8b0:400b:80d::2014
2607:f8b0:4006:80f::2014
2a00:1450:400e:80d::2014
2404:6800:4004:808::2014
2607:f8b0:4009:810::2014
2607:f8b0:4007:80d::2014
2607:f8b0:4005:806::2014
2607:f8b0:4007:802::2014
2607:f8b0:4007:806::2014
2607:f8b0:400f:805::2014
2404:6800:4004:806::2014
2607:f8b0:4008:805::2014
2607:f8b0:4004:804::2014
2404:6800:4004:80f::2014
2607:f8b0:400b:80c::2014
2404:6800:4004:80b::2014
2607:f8b0:400f:804::2014
2404:6800:4004:80d::2014
2607:f8b0:4020:805::2014
2607:f8b0:4006:81a::2014
2607:f8b0:4004:80f::2014
2607:f8b0:4000:802::2014
2404:6800:4004:81b::2014
2607:f8b0:4000:817::2014
2607:f8b0:400b:809::2014
2a00:1450:400e:804::2014
2a00:1450:400e:80a::2014
2607:f8b0:4006:803::2014
2607:f8b0:400a:808::2014
2607:f8b0:4003:c05::99
2607:f8b0:4002:c06::99
2607:f8b0:4003:c01::99
2607:f8b0:4005:807::2014
2607:f8b0:4003:c00::99
2607:f8b0:4008:803::2014
2607:f8b0:4009:802::2014
2607:f8b0:4009:809::2014
2a00:1450:4013:c04::99
2607:f8b0:4003:c12::99
2607:f8b0:4007:80e::2014
2607:f8b0:400b:80e::2014
2607:f8b0:4009:811::2014
2607:f8b0:4020:807::2014
2404:6800:400a:80b::2014
2607:f8b0:4002:c08::99
2a00:1450:400e:802::2014
2607:f8b0:4005:805::2014
2607:f8b0:4006:814::2014
2607:f8b0:4020:804::2014
2607:f8b0:400f:806::2014
2607:f8b0:4000:812::2014
2607:f8b0:4009:80d::2014
2a00:1450:4013:c01::99
2404:6800:4004:819::2014
2607:f8b0:4007:800::2014
2607:f8b0:4009:80f::2014
2607:f8b0:4007:804::2014
2607:f8b0:4007:808::2014
2607:f8b0:4003:c15::99
2607:f8b0:400f:807::2014
2607:f8b0:4009:806::2014
2607:f8b0:4006:811::2014
2607:f8b0:4006:815::2014
2607:f8b0:400b:80f::2014
2607:f8b0:4003:c19::99
2607:f8b0:4006:802::2014
2607:f8b0:4008:80c::2014
2607:f8b0:4001:c0e::99
2607:f8b0:4000:811::2014
2607:f8b0:4000:813::2014
2607:f8b0:4001:c1b::99
2607:f8b0:4007:80c::2014
2607:f8b0:4003:c17::99
2607:f8b0:4006:80e::2014
2607:f8b0:4000:808::2014
2607:f8b0:4002:c07::99

**Comment by Peterpey** [comment]
不行啊 用不了

**Comment by StormshadowRay** [comment]
> LS无非是大佬 [#11748 (comment)](https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138) 透露的近1/4

没注意，是新版自己扫出来可用的

**Comment by StormshadowRay** [comment]
> 不行啊 用不了
应该先排除你ipv6的问题吧

**Comment by bayersys** [comment]
新版本3.13.1为什么docs.google.com　访问不了，其他的可以。

**Comment by AnyWAT** [comment]
> 没注意，是新版自己扫出来可用的

所以，“拿去吧”未必有效😂

**Comment by AnyWAT** [comment]
> 新版本3.13.1为什么docs.google.com　访问不了，其他的可以。

X-Tunnel 可以

**Comment by bayersys** [comment]
> > 新版本3.13.1为什么docs.google.com　访问不了，其他的可以。
> 
> X-Tunnel 可以

我选的ｇａｅ　ｓｍａｒｔｒｏｕｔｅｒ　，怎么办呢？谢谢。有办法么？

**Comment by AnyWAT** [comment]
神奇操作，或许有救：https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215
Chrome + SwitchyOmega：
X-Tunnel 用白名单的PAC
GAE 用黑名单的PAC

**Comment by bayersys** [comment]
GAE 用黑名单的PAC自动切换　是什么功能？谢谢。

**Comment by AnyWAT** [comment]
等同于原 GAE-Proxy 自动切换？

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
