### ISSUE TITLE
凉凉了

### ISSUE THREAD

**Issue by xinyan3** [XX-net/XX-Net#11777]
![image](https://user-images.githubusercontent.com/26141775/50320431-45795400-0507-11e9-8a85-55be517ea2a7.png)

没办法了。准备自己搭ss了

**Comment by AnyWAT** [comment]
神奇操作，或许有救：https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by xinyan3** [comment]
并没什么用。问题出在IP上，没IP资源（或者IP资源有限）

**Comment by AnyWAT** [comment]
> 并没什么用

想打开的网页正常就行，能有神马用呢😂

**Comment by xinyan3** [comment]
打不开好不好。还是在GFW内，没ip没梯子出去呀

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
