### ISSUE TITLE
新版本3.13.1为什么docs.google.com　访问不了。谢谢。

### ISSUE THREAD

**Issue by bayersys** [XX-net/XX-Net#11776]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by bayersys** [comment]
新版本3.13.1为什么docs.google.com　访问不了，其他的可以。
昨天更新到最新版本了，感谢大神们的努力，但是我打开忘得网盘，打开之前的ｄｏｃ发现打开不了了。但是能够预览。

**Comment by AnyWAT** [comment]
X-Tunnel 可以

**Comment by iso5354** [comment]
我用的新版本可以打开，就是比较慢

**Comment by bayersys** [comment]
> 我用的新版本可以打开，就是比较慢

iso5354 能告诉我个ｄｏｃｓ的地址么？谢谢哦
