### ISSUE TITLE
3.13.1  IP又越来越少了

### ISSUE THREAD

**Issue by mionfan** [XX-net/XX-Net#11771]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by mionfan** [comment]
性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 20
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 1151
连接池(帮助) | 新:1 h1:0 h2:17
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by SeaHOH** [comment]
不要开无意义的问题

**Comment by AnyWAT** [comment]
🤣参考神奇操作可有限恢复？https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by AnyWAT** [comment]
重点：巨硬服务器域名随时改变指向到其它 IP，正常的 IP基本稳定，不正常的隧道能连接但 IPv6状态始终Fail 无法OK（也保持不能用😂），如 [win1711.ipv6.microsoft.com. 40.81.250.180](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204)（此 IP或许能连但很糟糕！弃用或自测）
动手试试：https://github.com/XX-net/XX-Net/issues/12030#issuecomment-452940598
