### ISSUE TITLE
新版本3.13.1打不开谷歌学术，显示有异常流量

### ISSUE THREAD

**Issue by Lyh970515** [XX-net/XX-Net#11788]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11780#issuecomment-449242104

**Comment by Lyh970515** [comment]
> [#11780 (comment)](https://github.com/XX-net/XX-Net/issues/11780#issuecomment-449242104)

还是不行，异常流量

**Comment by AnyWAT** [comment]
不会是修改后没有重启软件？

**Comment by milanthree** [comment]
确实是上不了谷歌学术

**Comment by Lyh970515** [comment]
> 确实是上不了谷歌学术

推荐大家用镜像吧。。不然感觉没办法现在

**Comment by Forecasters** [comment]
我也打不开

**Comment by tess1199** [comment]
估计是故意的吧, 搜索也不行, 应该是遮蔽来自gae的流量了
没想到这公司越来越垃圾了

**Comment by Lyh970515** [comment]
> 估计是故意的吧, 搜索也不行, 应该是遮蔽来自gae的流量了
> 没想到这公司越来越垃圾了

我的搜索还行。。感觉这次更新完大家都是奇奇怪怪的，谷歌学术的话推荐镜像吧，亲测可用

**Comment by Eri5Ch** [comment]
这个版本估计有问题 学术上不去 gmail会提示 重新定向次数过多 清楚cookies 以前某个版本出现过这个错误

**Comment by lionisxn** [comment]
期盼早日解决啊？
