### ISSUE TITLE
3.13.1没有可用ip

### ISSUE THREAD

**Issue by Mark486** [XX-net/XX-Net#11789]
更新到13.1开始出现问题
总ip数归零

`>导入了另外一个issue下的回复，总ip数是470
然后可用ip数就归零并在14~0不断跳动，状态也会在一切正常尚未建立之间跳动切换，期间尝试清空code\3.13.1\gae_proxy\local下的ipv6-list.txt文件内容，再次打开还是一样的情况，非常绝望的
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Mark486** [comment]
导入了https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138
尝试切换了teredo服务器
不行啊啊啊啊啊

**Comment by cugxuetao** [comment]
看来不是我一个人。。。。3.13.1升级后可用IP为0

**Comment by AnyWAT** [comment]
神奇操作，或许有救？ https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by cuijianzhuang** [comment]
一样，求解

**Comment by 80068** [comment]
同样也是这个问题

**Comment by Mark486** [comment]
> 神奇操作，或许有救？ [#11769 (comment)](https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215)
没有尝试这个方法，只是一直挂着
很奇怪的刚才又重新可以用了，只是可用ip数量比较低（个位数）
观察一会再决定是否使用方法
ps方法看着好艰深，可否给个详细一点或者整合的方法（对不起，伸手党了）

**Comment by Mark486** [comment]
> 神奇操作，或许有救？ [#11769 (comment)](https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215)

emmmmmm刚打字完就又不行了，可用数量又掉到0~1并提示连接尚未建立
还烦请提供略微小白友好一点的方法？

**Comment by AnyWAT** [comment]
老白的使用情况，还能咋整？
或许重点在“神奇操作”，不行再追究0-5点？

**Comment by Mark486** [comment]
> 老白的使用情况，还能咋整？
> 或许重点在“神奇操作”，不行再追究0-5点？

导入ip后提示新增0个ip（之前已经导入过了）
手动检测后情况依旧
重启后依旧
病急乱投医试了一下步骤四（虽然也没看懂是个什么东东）
大概找到了64位release版本打开以后自动刷了两次dns缓存打开英文提示了一下无法连接控制服务器，如使用console mode请忽略blablabla
关了又参考其他答案尝试修改了扫描线程（改为两百）https://github.com/XX-net/XX-Net/issues/11783#issuecomment-449231470
没什么用（但没有改回来）
又把ip模式改成自动
iPv4开始有一两个可用v6可用仍是个位数浮动
能用了！（不知道和下载的步骤四的程序有无关系）
虽然很慢（v4可用一个v6时无时个位数），ip延迟在一千~两千
总ip数还是470（这个地方能增加数量并提高速度吗，请给个方案?谢谢啦）
Google搜索正常油管正常240p视频都会卡但能用
并很稳定（在我打字这半小时里一直没有太大变化）
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:1 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:2
scan-ip-thread-num: 200
ip-quality: 1549
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
请问有无可提升空间或者步骤四程序正确使用方法？
非常感谢

**Comment by AnyWAT** [comment]
> 大概找到了64位release版本。。。

原因：它与XX-Net 都用53端口，初次运行，禁用 Smart Router 模块或退出XX-Net，以释放53端口
往后它开机启动占用53，XX-Net 退而用8053

**Comment by AnyWAT** [comment]
> 导入ip后提示新增0个ip（之前已经导入过了）

不然怎能称“神奇”？不行时随时再导入😂

**Comment by AnyWAT** [comment]
> 手动检测后情况依旧

或再检查 IP——一般无需，油管时或许。。。

**Comment by Mark486** [comment]
> > 大概找到了64位release版本。。。
> 
> 原因：它与XX-Net 都用53端口，初次运行，禁用 Smart Router 模块或退出XX-Net，以释放53端口
> 往后它开机启动占用53，XX-Net 退而用8053
> 管理权限运行 ServiceControl.bat 。。。

嗯，虽然都有些懵但刚才发现好像又不行（快哭出声了）

重启等一会是“一切正常”有效v4没有，有效v6个位徘徊，但再次测试Google搜索并没有效果（看来个位数有效v6没用的？）
然后又刷到有效v4了（一个）（可用搜索）
然后又没有了（十分钟差不多？）（有效v4没有，有效v6个位徘徊且搜索用不了）
然后又有了（可用）
非常不稳定
有啥好方法大佬？(掩面哭
（另强推Disney•Pixar Short Film "Bao" 测试的时候发现的动画，小包子贼可爱！！）

**Comment by Mark486** [comment]
> > 大概找到了64位release版本。。。
> 
> 原因：它与XX-Net 都用53端口，初次运行，禁用 Smart Router 模块或退出XX-Net，以释放53端口
> 往后它开机启动占用53，XX-Net 退而用8053
> 管理权限运行 ServiceControl.bat 。。。

在我发现如上一条回复情况以后尝试使用你说的方法，关闭xx并管理员运行后依旧↓
Windows IP 配置

已成功刷新 DNS 解析缓存。


Windows IP 配置

已成功刷新 DNS 解析缓存。

[System Error] Service start error: The service process could not connect to the
 service controller[1063].
[Notice] Program will continue to run in console mode.
[Notice] Please ignore these error messages if you want to run in console mode.

**Comment by AnyWAT** [comment]
程序目录下没报错文件即正常
😂不会没设置网络连接内的 DNS：127.0.0.1

**Comment by Mark486** [comment]
> > 大概找到了64位release版本。。。
> 
> 原因：它与XX-Net 都用53端口，初次运行，禁用 Smart Router 模块或退出XX-Net，以释放53端口
> 往后它开机启动占用53，XX-Net 退而用8053
> 管理权限运行 ServiceControl.bat 。。。

以及最让我疑惑的是我的ip段那么长一段为什么总ip数如此之少（不到五百）
1.9.22.0-1.9.22.255
1.9.24.0-1.9.24.255
1.9.57.0-1.9.57.255
1.9.91.0-1.9.91.255
1.9.131.0-1.9.131.255
~~省略一大段~~
223.196.116.0-223.196.116.255
223.224.12.0-223.224.12.255
223.255.227.0-223.255.227.255
223.255.229.0-223.255.229.255

**Comment by AnyWAT** [comment]
😥自己回头看看大佬贴 IP处的文字。。。

**Comment by Mark486** [comment]
> 自己回头看看大佬贴 IP处的文字。。。 [Kisesy/gscan_quic#178 (comment)](https://github.com/Kisesy/gscan_quic/issues/178#issuecomment-449019253)

shiiiiiiiiiiit，真是自闭了

**Comment by Mark486** [comment]
> 自己回头看看大佬贴 IP处的文字。。。 [Kisesy/gscan_quic#178 (comment)](https://github.com/Kisesy/gscan_quic/issues/178#issuecomment-449019253)

真是疯了
刚才瞎搞搞搞出来Telnet，就把路由器设置成IP协议版本：  IPv4     IPv6   	√   IPv4/IPv6 |后
再换了一次teredo服务器
然后可用v6稳定在三十多！
![default](https://user-images.githubusercontent.com/21996475/50351770-1e119e00-057e-11e9-8eb7-f8c1f358786d.PNG)
![2](https://user-images.githubusercontent.com/21996475/50351774-1fdb6180-057e-11e9-9ada-d02dacc85394.PNG)
究竟是因为我换了服务器还是搞了路由器呢。。。。

**Comment by AnyWAT** [comment]
cmd 运行 netsh int ipv6 show teredo 显示服务器

**Comment by AnyWAT** [comment]
> 究竟是因为我换了服务器还是搞了路由器呢。。。。

服务器名称变了没，不说神马有无区别：变了，原来 win10microsoft

**Comment by Mark486** [comment]
> > 究竟是因为我换了服务器还是搞了路由器呢。。。。
> 
> 服务器名称变了没，不说神马有无区别：变了，原来 win10microsoft
> 
> 搞了路由器（貌似支持 IP6），但 ISP提供么？再说你现在用的是隧道
> 原生 IP6：#11797

跟他相同的isp，我估计是也行的，那现在如何测试是否支持原生？（ps大佬有没有赞助方式，太感谢了想赞助五毛钱的==）

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/50353566-9890ec80-0583-11e9-8479-c0efd03ce05d.png)

**Comment by AnyWAT** [comment]
> （ps大佬有没有赞助方式，太感谢了想赞助五毛钱的==）

大老白木有任何电子方式，谢谢😂

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
