### ISSUE TITLE
新版本3.13.1 google scholar打不开

### ISSUE THREAD

**Issue by ssimonhan** [XX-net/XX-Net#11781]
Our systems have detected unusual traffic from your computer network. Please try your request again later.

**Comment by SunYongshuai** [comment]
The same problem. And I want to know how to disable proxy in google scholar.

**Comment by SunYongshuai** [comment]
If you are in '.edu.cn' network it is no need to use proxy for google scholar, you can add ip of it to hosts to skip xxnet proxy. And it works for me.

**Comment by SunYongshuai** [comment]
![image](https://user-images.githubusercontent.com/25148301/50329450-58ede480-0532-11e9-88e7-0cfa7d3afab8.png)
If you can use scholar.google.com without proxy, you can add it to white_site as shown in picture. It works for me.

**Comment by ssimonhan** [comment]
> ![image](https://user-images.githubusercontent.com/25148301/50329450-58ede480-0532-11e9-88e7-0cfa7d3afab8.png)
> If you can use scholar.google.com without proxy, you can add it to white_site as shown in picture. It works for me.

I am in China. So I have to use proxy to open google scholar. Thanks, though.

**Comment by SunYongshuai** [comment]
> > ![image](https://user-images.githubusercontent.com/25148301/50329450-58ede480-0532-11e9-88e7-0cfa7d3afab8.png)
> > If you can use scholar.google.com without proxy, you can add it to white_site as shown in picture. It works for me.
> 
> I am in China. So I have to use proxy to open google scholar. Thanks, though.

I am in China, too. But some network like education network can open google scholar commonly. If you are student, you can have a try! It works for me.
Another hand, I add some websites in China to the white_site, it performances better. After all, proxy is slower than normal connect.

**Comment by HUSTwanglei** [comment]
> > > ![image](https://user-images.githubusercontent.com/25148301/50329450-58ede480-0532-11e9-88e7-0cfa7d3afab8.png)
> > > If you can use scholar.google.com without proxy, you can add it to white_site as shown in picture. It works for me.
> > 
> > 
> > I am in China. So I have to use proxy to open google scholar. Thanks, though.
> 
> I am in China, too. But some network like education network can open google scholar commonly. If you are student, you can have a try! It works for me.
> Another hand, I add some websites in China to the white_site, it performances better. After all, proxy is slower than normal connect.

not all network is directly connected to Google Scholar

**Comment by AnyWAT** [comment]
或许在：连接池 h1永远是 0 ？
https://github.com/XX-net/XX-Net/wiki/GoAgent-Connection-status 
![image](https://user-images.githubusercontent.com/37962734/50344482-2362ee80-0566-11e9-8560-669629a07942.png)

**Comment by ZhangAllen98** [comment]
> 连接池 h1永远是 0 ？

连接池显示，新:0 h1:0 h2:28

**Comment by ssimonhan** [comment]
> 或许在：连接池 h1永远是 0 ？
> https://github.com/XX-net/XX-Net/wiki/GoAgent-Connection-status
> ![image](https://user-images.githubusercontent.com/37962734/50344482-2362ee80-0566-11e9-8560-669629a07942.png)

yeah, the number of "h1" is always zero. Probably it is the problem.

**Comment by miumiu22** [comment]
I have the same problem. Does anyone figure out how to solve the problem?

**Comment by AnyWAT** [comment]
https://github.com/XndroidDev/Xndroid/issues/191#issuecomment-449705387
