### ISSUE TITLE
新版本3.13.1为什么docs.google.com　访问不了，谁来救救我。

### ISSUE THREAD

**Issue by bayersys** [XX-net/XX-Net#11780]
新版本3.13.1为什么docs.google.com　访问不了了，谁来帮帮我。

**Comment by milanthree** [comment]
可以呀，我这边没什么问题

**Comment by MadMaxPayne8964** [comment]
docs我这时好时坏，play和学术是肯定大家都不能用gae访问

**Comment by SunYongshuai** [comment]
![image](https://user-images.githubusercontent.com/25148301/50324510-48ca0b00-051a-11e9-891e-627abe43ce1b.png)
You can just remove #"docs.google.com" in code/default/gae-proxy/local/config.py > self.set_var("hosts_direct" it works for me!

**Comment by SeaHOH** [comment]
#11776

**Comment by iversonLv** [comment]
@SunYongshuai You are the man.
Thanks.

**Comment by SunYongshuai** [comment]
任意文本编辑器。
Windows：notepad++，vscode，sublime等
Linux：vim，nano，gedit，vscode，sublime等
如果你用Windows，实在不行可以用记事本！

**Comment by wtr19941227** [comment]
把文本中的#"docs.google.com"删除掉吗？

**Comment by SunYongshuai** [comment]
可以，或者直接像图片那样注释掉就行

**Comment by AnyWAT** [comment]
> 可以，或者直接像图片那样注释掉就行，默认是不带‘#’的

奇怪，没修改过的3.13.1，貌似与楼上的 https://github.com/XX-net/XX-Net/issues/11780#issuecomment-449242104 不一样？
![image](https://user-images.githubusercontent.com/37962734/50834516-26941200-138f-11e9-9bd2-6913922f806b.png)

**Comment by SunYongshuai** [comment]
@AnyWAT 我那是修改过的，其实是吧docs删掉或者注释掉，效果一样。行前‘#’是注释掉的意思，和删掉效果一样。

**Comment by wtr19941227** [comment]
![default](https://user-images.githubusercontent.com/34266103/50834675-acb05880-138f-11e9-8809-14706825f867.png)
为啥没有效果 我在"docs.google.com"前面加了#，还是没办法使用谷歌表格文档..

**Comment by wtr19941227** [comment]
需要重启XX-NET吗？

**Comment by SunYongshuai** [comment]
Of Course！同时记得保存哈！

**Comment by wtr19941227** [comment]
OK了，多谢大神！

**Comment by migilar** [comment]
> ![image](https://user-images.githubusercontent.com/25148301/50324510-48ca0b00-051a-11e9-891e-627abe43ce1b.png)
> You can just remove #"docs.google.com" in code/default/gae-proxy/local/config.py > self.set_var("hosts_direct" it works for me!

新版本3.13.1中config.py的“hosts_direct”已经不包含doc.google.com了，但我还是打不开google doc

请问有谁知道原因吗？谢谢

**Comment by AnyWAT** [comment]
IP 延迟过大或连接池过小？

**Comment by migilar** [comment]
> IP 延迟过大或连接池过小？

应该不是？我能打开youtube, twitter, google那些。以下是当前状态数据：
![image](https://user-images.githubusercontent.com/19563522/52930784-d1cbba00-3384-11e9-8ad0-e977e1ec3bd5.png)

**Comment by SunicYosen** [comment]
> > ![image](https://user-images.githubusercontent.com/25148301/50324510-48ca0b00-051a-11e9-891e-627abe43ce1b.png)
> > You can just remove #"docs.google.com" in code/default/gae-proxy/local/config.py > self.set_var("hosts_direct" it works for me!
> 
> 新版本3.13.1中config.py的“hosts_direct”已经不包含doc.google.com了，但我还是打不开google doc
> 
> 请问有谁知道原因吗？谢谢

config.py的“hosts_direct”已经不包含docs.google.com可以用的前提是不挂xxnet的proxy也可以用。你可以先确认不使用xxnet你是否可以用，如果不可以可能是网络代理商的问题了。

**Comment by migilar** [comment]
> > > ![image](https://user-images.githubusercontent.com/25148301/50324510-48ca0b00-051a-11e9-891e-627abe43ce1b.png)
> > > You can just remove #"docs.google.com" in code/default/gae-proxy/local/config.py > self.set_var("hosts_direct" it works for me!
> > 
> > 
> > 新版本3.13.1中config.py的“hosts_direct”已经不包含doc.google.com了，但我还是打不开google doc
> > 请问有谁知道原因吗？谢谢
> 
> config.py的“hosts_direct”已经不包含docs.google.com可以用的前提是不挂xxnet的proxy也可以用。你可以先确认不使用xxnet你是否可以用，如果不可以可能是网络代理商的问题了。

不使用xxnet也打不开，你是说这是网络运营商的问题吗？应该不可能啊，你直接可以打开吗？

**Comment by SunicYosen** [comment]
> > > > ![image](https://user-images.githubusercontent.com/25148301/50324510-48ca0b00-051a-11e9-891e-627abe43ce1b.png)
> > > > You can just remove #"docs.google.com" in code/default/gae-proxy/local/config.py > self.set_var("hosts_direct" it works for me!
> > > 
> > > 
> > > 新版本3.13.1中config.py的“hosts_direct”已经不包含doc.google.com了，但我还是打不开google doc
> > > 请问有谁知道原因吗？谢谢
> > 
> > 
> > config.py的“hosts_direct”已经不包含docs.google.com可以用的前提是不挂xxnet的proxy也可以用。你可以先确认不使用xxnet你是否可以用，如果不可以可能是网络代理商的问题了。
> 
> 不使用xxnet也打不开，你是说这是网络运营商的问题吗？应该不可能啊，你直接可以打开吗？
可以，不过很慢；我不用这个的～

**Comment by AnyWAT** [comment]
无代理打不开。有代理，地址栏输入 doc.google.com 中间有跳转地址 https://docs.google.com/document/u/0/?usp=direct_url ，最后 https://docs.google.com/document/u/0/ 正常
