### ISSUE TITLE
是否可以改进程序，共享ip扫描结果？

### ISSUE THREAD

**Issue by WangLarry** [XX-net/XX-Net#11786]
搭建一个服务器程序，客户端上传扫描结果，通过服务器相互共享给其他人

**Comment by SeaHOH** [comment]
各人网络条件不同，所以这么做没意义。

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
