### ISSUE TITLE
难道要放弃xx-net?

### ISSUE THREAD

**Issue by YuboWang123** [XX-net/XX-Net#11793]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
貌似扫描不到，但随时导入大佬提供的 IP还能基本正常呢😂

**Comment by tatiyixi** [comment]
> 貌似扫描不到，但随时导入大佬提供的 IP还能基本正常呢

请问IP在哪里？没了XX-NET还难过呀。上不了tw，看不了少康战情室。

**Comment by AnyWAT** [comment]
神奇操作，或许有救？ https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by robinlighting** [comment]
ip是有，但是地址池归零之后，ip就暴跌？有什么解决的方法？

**Comment by AnyWAT** [comment]
试试：连接池归零，或检查 IP，或再启动一个程序（可免退出），再导入 IP

**Comment by 80068** [comment]
今天一天试了很多次，均无效。都按照教程去做。丝毫没有看到任何改善。我估计教程上说的可能是和所在环境是否有IPV6有关。因为联通到现在也没给用户配置什么IPV6，另外就是联通本身有强大的后台和AI控管系统，所有这些找个小窍门再重新恢复的设置对联通没有意义。

另外就是这些小窍门操作很难复杂，有些需要多组代码调试，这个对于普通使用XX-NET的用户恐怕有很大难度。

没有XX-net整个外网全不能用。现在用网可倒好只有一个大内网：新浪、163、淘宝、百度、一个论坛。都在这了，这网还有什么可上的？有什么意思。完了，没有XX-Net彻底没网可上了。

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 296
总 IP 数 | 453
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:4
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 50

**Comment by AnyWAT** [comment]
> 因为联通到现在也没给用户配置什么IPV6

大佬说的无原生 IPv6的内网中的内网：
![image](https://user-images.githubusercontent.com/37962734/50348132-da656700-0572-11e9-8ebf-b28e7679c9e3.png)
故用隧道😂

**Comment by 80068** [comment]
@AnyWAT 不懈的指导，非常感谢！

对，无原生IPV6故用隧道，可是这回启动XX-net没1分钟就已经显示红字：无法连接。而且按教程中的做不是一次，反反复复很多次，修了很多次基本原样纹丝不动，说明这里不是上了一道锁了，肯定是好多层锁，而且这些锁网的网锁提前都经过反复测试，才同时使用的。不像上次开大会时不管怎么折腾，最后多多少少还能凑合用，这次是一点都不行。达到了暴风骤雨纹丝不动。这怎么办？

今天把路由器（联通WO36）的设置都打开仔细看了一遍，有IPV6的设置，但没有发现关于IPV6的开关功能按钮。

最终只能无计可施。

**Comment by AnyWAT** [comment]
> 已经显示红字

导入 IP。。。

**Comment by 80068** [comment]
@AnyWAT  IP导入了，还是没变化。

**Comment by AnyWAT** [comment]
回看“神奇操作”。。。0-5点有照做？
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by 80068** [comment]
好的，我看看

**Comment by AnyWAT** [comment]
代码老白，影响看贴，删楼。。。
http://127.0.0.1:8085/?module=gae_proxy&menu=status 页底“诊断信息”

**Comment by 80068** [comment]
@AnyWAT 
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by 80068** [comment]
这个应该是 诊断信息

**Comment by 80068** [comment]
@AnyWAT 
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
上上楼的第三行呢？

**Comment by 80068** [comment]
@AnyWAT 
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\Pamera>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 是
本地映射           : 192.168.50.169:50690
外部 NAT 映射    : 111.166.39.29:50690

**Comment by AnyWAT** [comment]
use-ipv6: force_ipv6 ——回看“神奇”修改成自动？
gws-ip-num: total:100 ipv4:0 ipv6:1——回看“神奇”修改100为300-500？
scan-ip-thread-num: 50——回看“神奇”修改为20左右？

**Comment by 80068** [comment]
好的，那我现在再试试

**Comment by no-name2017** [comment]
我的ip也全死，最新版

**Comment by 80068** [comment]
@AnyWAT 
https://github.com/chengr28/Pcap_DNSProxy 这个下载链接怎么下载不到呢？

**Comment by 80068** [comment]
@AnyWAT 这个下载链接怎么一直是下载等待呢？

**Comment by AnyWAT** [comment]
貌似 github 上图、下载需代理

**Comment by 80068** [comment]
@AnyWAT 下7z包也是显示【该网页无法运作】

**Comment by 80068** [comment]
@AnyWAT 来个百度盘的下载？ 这个下载是不是也被锁定了？

**Comment by AnyWAT** [comment]
😭省了吧，难道没有备用梯？

**Comment by AnyWAT** [comment]
有又怎样，能过来？😜木有

**Comment by kuchaguangjie** [comment]
说不定 以后 只能去 墙外了, 墙外的 世界 很美好:

![youtube](https://user-images.githubusercontent.com/4230959/50352957-b1000780-0581-11e9-9bcc-4df2fd57b591.jpg)

**Comment by no-name2017** [comment]
@80068 不用试了，他的方法我都尝试过了，没用

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/50355814-d80f0700-058a-11e9-81c6-f33ba8c39722.png)

**Comment by no-name2017** [comment]
@AnyWAT @SeaHOH @xxnet  大佬们，我发现问题确实出在teredo隧道上，用光猫拨号不经路由器，一切正常，AnyWAT你的方法无效，解决不了问题的。

**Comment by AnyWAT** [comment]
😂50M移动网线入户，没光猫、没原生IPv6、内网中的内网（10.*），有图没真相？

**Comment by AnyWAT** [comment]
> @80068 不用试了，他的方法我都尝试过了，没用

😱有人不同环境下的瞎套用？

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
