### ISSUE TITLE
xxnet满血复活

### ISSUE THREAD

**Issue by play903132** [XX-net/XX-Net#11794]
升级3.13.1之后，还是上不去，连接很不稳定，一会正常一会无连接，然后看了大家的帖子，很受启发。
先说下 ，宽带是电信   ，公网IP，路由器网件r7000桥接拨号，在路由器ipv6设置里，启用并选择自动检测 后 保存刷新，xxnet的IP刷刷的上来了。看图
![1](https://user-images.githubusercontent.com/11461738/50346548-b05d7600-056d-11e9-9034-564e1460271e.png)
![2](https://user-images.githubusercontent.com/11461738/50346550-b18ea300-056d-11e9-993d-36962e98684a.png)
![image](https://user-images.githubusercontent.com/11461738/50346592-d256f880-056d-11e9-9212-507030afa38f.png)

**Comment by play903132** [comment]
我这到底是不是ipv6啊  检测超时 代表什么意思

**Comment by justinlee2pro** [comment]
@play903132 联通200MB，TL-H69RT是没办法设IPV6吧，大侠？

**Comment by AnyWAT** [comment]
> 我这到底是不是ipv6啊

是说原生？前提：
1、ISP已提供 IPv6
2、路由器支持 IPv6
3、操作系统是否要设置？

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
