### ISSUE TITLE
发发牢骚, 3.5.5以来一直无限好用，3.13.1升级后20-21号极其不稳定，期待牛X发布补丁

### ISSUE THREAD

**Issue by justinlee2pro** [XX-net/XX-Net#11796]
静默等待中...

**Comment by AnyWAT** [comment]
😥默哀吧 https://github.com/Kisesy/gscan_quic/issues/178#issuecomment-449019253

**Comment by justinlee2pro** [comment]
> 坏消息： [Kisesy/gscan_quic#178 (comment)](https://github.com/Kisesy/gscan_quic/issues/178#issuecomment-449019253)
> 但： [#11759 (comment)](https://github.com/XX-net/XX-Net/issues/11759#issuecomment-448854172)

谢.........

**Comment by WangLarry** [comment]
我改用shadowsocks了，省心

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。

**Comment by justinlee2pro** [comment]
今天撤了路由，改连接光猫，一切都OK, 超快。
总IP:450, 有效IPV6: 120,  有效IPV4：1.
他奶奶的，没有这么流畅过。

**Comment by AnyWAT** [comment]
隧道：随时总IP:300, 有效IPV6: 300 的都没好意思说，哈哈
![image](https://user-images.githubusercontent.com/37962734/50572465-46aa5b00-0dfc-11e9-9a41-a0e73fb85004.png)
