### ISSUE TITLE
为何我一直OK，说不行的进来看看

### ISSUE THREAD

**Issue by jzmswe** [XX-net/XX-Net#11795]
1.不要安装国内安全软件，杀毒软件、防火墙。

2.不要同时使用迅雷等BT软件下载东西，如果刚在下载，退出后还不行，建议重启PC。

3.不要使用国内DNS，建议使用DnsJumper这个绿色小软件，更换国外最快DNS。

4.如果是内网，可能是别人在使用BT软件。

我从昨天开始用XX-NET到现在，一直U2B 1080P无压力。

上传APPID后，直接用的，没按那个救命贴操作。

**Comment by jzmswe** [comment]
我从昨天开始用XX-NET到现在，一直U2B 1080P无压力。

**Comment by justinlee2pro** [comment]
除了3不知道怎么设置，其他的和你的一样，这两天只有tunnel还可以用

**Comment by AnyWAT** [comment]
> 1.不要安装国内安全软件，杀毒软件、防火墙。

有微软自带

**Comment by tatiyixi** [comment]
腾讯的电脑管家算不算？

**Comment by tatiyixi** [comment]
腾讯的电脑管家算不算？

**Comment by tatiyixi** [comment]
腾讯的电脑管家算不算？

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
