### ISSUE TITLE
版本3.13.1 系统空闲。 (正常)但是用不了

### ISSUE THREAD

**Issue by inkforest** [XX-net/XX-Net#11792]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 99
总 IP 数 | 99
XX-Net 状态 | 空闲
IP 延迟 | 269
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | Fail
IP 扫描线程数(设置) | 100

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 269
is-idle: 1
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

用的是Chrome 重新导入过CA证书重启浏览器依旧没用，应该不是证书问题？虽然显示正常，但是调用代理的时候没有效果

**Comment by AnyWAT** [comment]
worker: h1:0 h2:0 ——连接池归零，再启动一个（可免退出）
Appids_Not_Exist: true ——有ID错误？

**Comment by inkforest** [comment]
> worker: h1:0 h2:0 ——连接池归零，再启动一个（可免退出）
> Appids_Not_Exist: true ——有ID错误？
> ca_state: Fail ——代理扩展图标附加数字，未加载资源内有必走GAE的 *.deja.com 未处理？

谢谢！我重新部署了一下id又好了……😵
另外有个神奇的事是，状态显示ipv6是OK的，但是测试teredo的时候是 qualified: False？

**Comment by AnyWAT** [comment]
不如运行：netsh int teredo show state

**Comment by inkforest** [comment]
> 不如运行：netsh int teredo show state

显示qualified。。。😵
还是感谢，终于可以上Google了

**Comment by iarander** [comment]
> > worker: h1:0 h2:0 ——连接池归零，再启动一个（可免退出）
> > Appids_Not_Exist: true ——有ID错误？
> > ca_state: Fail ——代理扩展图标附加数字，未加载资源内有必走GAE的 *.deja.com 未处理？
> 
> 谢谢！我重新部署了一下id又好了……
> 另外有个神奇的事是，状态显示ipv6是OK的，但是测试teredo的时候是 qualified: False？

小白请教怎么重新部署id啊

**Comment by AnyWAT** [comment]
已部署、成功使用过，不再需要。
http://127.0.0.1:8085/?module=gae_proxy&menu=config 填写并保存即可

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
