### ISSUE TITLE
最新版本终于正常了~IPV6

### ISSUE THREAD

**Issue by roy961** [XX-net/XX-Net#11797]
![default](https://user-images.githubusercontent.com/46003508/50348552-0b926700-0574-11e9-9b17-c4d30e90291f.PNG)
首先我的运营商（电信）是支持IPV6的，然后我在光猫里打开桥接（V4/V6)模式，然后
路由器里设置一下IPV6（NATIVE）模式，终于好使了~希望能坚持住！

**Comment by Mark486** [comment]
壮士！留下你的路由器型号！

**Comment by no-name2017** [comment]
为什么你们的光猫可以配置?是电信送的那个吗？

**Comment by gfvre123** [comment]
路由器不支持Ipv6，怎么办可以做映射吗

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
