### ISSUE TITLE
请求帮助，各项指标看似正常，实则没有可用IP，诊断信息如下

### ISSUE THREAD

**Issue by bossty** [XX-net/XX-Net#11798]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:70 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by bossty** [comment]
自己有部署APP_ID，之前一直正常，更新后就不行了，不知道是什么原因

**Comment by gukoo1002** [comment]
更新后，移动的也不行了，

**Comment by bossty** [comment]
我是电信的，看了其他回复，说是要路由器支持IPV6
可是我的可用IP有30几个呢，还是用不了，状态也显示正常。

**Comment by bossty** [comment]
> 更新后，移动的也不行了，

**Comment by yxqxhmln** [comment]
我是移动的，也是所有都正常，就是无法连接


属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | OK
IPv4 IP数 | 0
IPv6 IP数 | 182
XX-Net 状态 | 工作
IP延迟 | 100
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 0
屏蔽状态(帮助) | OK

**Comment by SeaHOH** [comment]
> gws-ip-num: total:70 ipv4:0 ipv6:0
> connected-link: new:0
> worker: h1:0 h2:0
> ip-quality: 9999

并不正常

**Comment by AnyWAT** [comment]
> 我是电信的，看了其他回复，说是要路由器支持IPV6

貌似原生 IPv6才是，隧道无需
随时导入 IP，或许有救？ https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
