### ISSUE TITLE
显示系统空闲，但是可以正常使用？

### ISSUE THREAD

**Issue by h188cm** [XX-net/XX-Net#11801]
如图，可以正常使用，谁能解释一下
![default](https://user-images.githubusercontent.com/3130862/50368600-6acc9780-05c5-11e9-8bbf-ae34ec8da4a6.PNG)

**Comment by Peterpey** [comment]
我 用不了...

**Comment by AnyWAT** [comment]
莫非用的X-Tunnel 代理？有3个IPv4，Cloudflare 前端正常，X-Tunnel 即正常。IPv6 状态Fail，GAE应不正常，貌似软件检测代理及证书，且必走GAE的 *.deja.com 不正常，所以浏览器代理设置及CA证书状态2个Fail 😋

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
