### ISSUE TITLE
Openwrt 18.06.1/Linksys WRT1200AC路由器/XX-Net 3.13.1正常运行

### ISSUE THREAD

**Issue by erdcy** [XX-net/XX-Net#11809]
# 只保证在以下条件成功运行：
1， 原生ipv6或者he.net提供的ipv6 free tunnel；
2， Openwrt 18.06.1；
3， Linksys WRT1200AC V1 双核1.3 GHz/512MB RAM 或类似配置路由器。

# 部署流程简述：
0， 扩展路由器存储空间，参考以下链接；
        https://openwrt.org/docs/guide-user/additional-software/extroot_configuration

1， putty方式或者luci方式安装软件包，以putty方式为例；
	opkg update
        opkg install python python-openssl python-pyopenssl

2， 用winscp将PC中已经设置好的XX-Net文件夹上传到路由器“/etc/”文件夹。这样操作有两个好处：一、路由器中goagent证书与PC一致，PC只需要导入一个证书，就可以切换使用PC本地XX-Net和路由器XX-Net；二、在PC上做好XX-Net设置，如允许远程访问控制页，代理监听 0.0.0.0:8087等，便于后续操作 ；

3， 在luci界面system->startup->local Startup中的exit 0前添加以下内容
        sh /etc/XX-Net/start &

4， 重启路由器，你可以访问真正的互联网了。

# 注：
1，以上部署流程拼凑于搜索结果，并未优化；
2，对上述路由器只做了12小时双PC油管直播测试，期间未见故障；
3，建议每日定时重启路由器。

# 附：
1，路由器负载，单台PC油管720p播放；
![image](https://user-images.githubusercontent.com/30851165/50371114-51d8dc00-05ef-11e9-8b58-beaf27d65498.png)

2， 油管播放截图
![untitled](https://user-images.githubusercontent.com/30851165/50371145-e2172100-05ef-11e9-86d7-c67006168473.png)

3，XX-Net状态

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 474
连接池(帮助) | 新:0 h1:0 h2:22
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 1

# 已知问题：
1，putty中运行reboot，路由器不响应。在自启动命令后加了一个“&"，crontab中的定时reboot，重启成功。

**Comment by agutools** [comment]
奇怪的是：有电信的原生ipv6（240e:61:906:6000::1/64，多拨多IP），ping6 www.163.com也正常（30ms+），但是XX-Net不能能识别，提示要开启IPv6。
X-Tunnel能正常登陆。

系统：OpenWrt 18.06.1 MIPS 24KEc V5.0
版本：XX-Net 3.13.1

**Comment by erdcy** [comment]
差异有以下几点，可以逐一尝试。
1，单拨；
2，电信原生ipv6和he.net free ipv6 tunnel共存；
3，电信ipv6有时可以分发给局域网终端，有时不能，原因不明，所以he.net的ipv6 free tunnel一直连着。

**Comment by hdrafyy** [comment]
小白表示看不懂！

**Comment by erdcy** [comment]
小众用法，只是给有相同需求的网友一个参考。

**Comment by sky123456789sky** [comment]
小白问一句 sh &有日志输出吗

**Comment by erdcy** [comment]
openwrt的system log可以看到日志，当然xxnet远程管理web页面也有日志输出。
