### ISSUE TITLE
上海移动，更新了13.1，一直提示等待扫描IP，手动换了几个隧道，连接池一直是0，很纠结

### ISSUE THREAD

**Issue by ksi1110** [XX-net/XX-Net#11806]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:3
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 2188
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ksit1110** [comment]
链接池一直是0

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945

**Comment by zhgna08** [comment]
前几天还好好的，这两天有效数几乎都是0，偶尔扫到几个，也很快就挂

**Comment by kst182** [comment]
是啊,最近这几天眼睁睁的看着ip从100几十秒就变成了0了,哭晕呀

**Comment by bmzk00** [comment]
> 如果手机通过vpn上网，并且手机做为热点，然后电脑连入手机，这样xxnet还能连上internet，不晓得为什么

很多地方的运营商已经为手机4G分配IPV6了

**Comment by AnyWAT** [comment]
> 前几天还好好的，这两天有效数几乎都是0，偶尔扫到几个，也很快就挂



> 是啊,最近这几天眼睁睁的看着ip从100几十秒就变成了0了,哭晕呀

瞧瞧 https://github.com/XX-net/XX-Net/issues/11821#issuecomment-449607389
