### ISSUE TITLE
3.13.1仍然无效

### ISSUE THREAD

**Issue by navylover** [XX-net/XX-Net#11800]
经两天测试，如果不是直连光猫，获取原生IPV6，在使用路由器的情况下，ip总数很快归零。
@AnyWAT 提供的方法都试过，没用~~~。
有什么应对措施吗?

**Comment by AnyWAT** [comment]
😂人、XX-Net（退出）歇息了5小时，电脑一直开着但隧道已休眠，打开XX-Net 隧道立马正常，“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。”

**Comment by Peterpey** [comment]
目前用不了，好像也就只有楼上@AnyWat 他一个人能正常使用。

**Comment by Peterpey** [comment]
google都上不去  就给我显示这个  600:gae_exception:'600:fetch gae fail'

**Comment by AnyWAT** [comment]
IP延迟超大或连接池太少，代理不正常的症状

**Comment by Peterpey** [comment]
反正 上不去 。。。

**Comment by AnyWAT** [comment]
开机后隧道或睡眠或已正常？

**Comment by asmosn** [comment]
不同地區情況不一樣，我這聯通手機可用，電信WiFi上不了

**Comment by nly4lov** [comment]
可用ip个位数

> 

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 5
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 1830
连接池(帮助) | 新:0 h1:0 h2:5
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by gfvre123** [comment]
> 经两天测试，如果不是直连光猫，获取原生IPV6，在使用路由器的情况下，ip总数很快归零。
> @AnyWAT 提供的方法都试过，没用~~~。
> 有什么应对措施吗?

把路由当交换机来用不可以吗

**Comment by kkkmzh** [comment]
昨天更了下还能用，今天又挂了

**Comment by imudie123** [comment]
完全没办法使用
偶尔扫到两三个ip
一访问网页，ip立刻就归零，提示等扫描ip。

**Comment by Peterpey** [comment]
同上

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11801 问楼主的3个有效 IP4是否导入 #11775 的结果。。。

**Comment by AnyWAT** [comment]
use-ipv6: force_ipv6——改为自动
导入  IP4 #11775
导入  IP6 https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138

**Comment by no-name2017** [comment]
@AnyWAT  我都跟你说了，你的方法没用，就靠改force_ipv6，检查ip，修改ip总数这些有用的话，就没人发issue了吧，你是机器人吗？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448793452 @xxnet

**Comment by SeaHOH** [comment]
#11764 
# 不要重复发帖

**Comment by AnyWAT** [comment]
> 目前用不了，好像也就只有楼上@AnyWAT 他一个人能正常使用。

是否因用了 https://github.com/chengr28/Pcap_DNSProxy 才这样？https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231

**Comment by AnyWAT** [comment]
> 
> 
> 目前用不了，好像也就只有楼上@AnyWAT 他一个人能正常使用。

试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名

**Comment by nly4lov** [comment]
我的ip数虽然是个位到10几个，但一直能翻哈哈

**Comment by AnyWAT** [comment]
貌似最佳：有效 IP数随时自动趋近、达到总 IP数：源于XX-Net 的[XX-Mini](https://github.com/xyuanmu/XX-Mini) 对 max_scan_ip_thread_num（总 IP数）的解释：[谷歌IP上限，超过则剔除延时高的IP](https://github.com/XX-net/XX-Net/issues/11376#issuecomment-425376757)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11647#issuecomment-450690575 3.12.0也正常

**Comment by AnyWAT** [comment]
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043
