### ISSUE TITLE
北京联通， 3.13.1，恢复

### ISSUE THREAD

**Issue by mercury2015** [XX-net/XX-Net#11807]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 71
总 IP 数 | 96
XX-Net 状态 | 工作
IP 延迟 | 660
连接池(帮助) | 新:0 h1:0 h2:20
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 100

昨天都是零，延迟四个九，今天完全恢复了。

**Comment by SongtaoGit** [comment]
我这不行。。你服务器ip用的哪个？

**Comment by AnyWAT** [comment]
#12043 自己【[找出并更换适用于自己的服务器]( )】
