### ISSUE TITLE
更新到3.13.1 然后重新开关teredo之后终于能用了

### ISSUE THREAD

**Issue by xiaoas** [XX-net/XX-Net#11808]
刚更新的时候还是不能用 试过重启 没用
然后发现test-ipv6.com测不到ipv6地址 于是又开关了一下终于好了
我觉得我傻了233 希望能对一些人有帮助
不过还是非常慢 也不稳定。。

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
