### ISSUE TITLE
天津联通，目前断断续续比昨天的一点没有好一些

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#11815]
适用3.13.1最新版，比昨天一点连不上好了不少，但还是断断续续，时断时续。特别是看Youtube时马上就非常明显卡死现象明显。望XX-net继续增强软件性能，避免被破解，影响使用。
![81](https://user-images.githubusercontent.com/19446969/50374097-af871b80-0623-11e9-9d21-355d9c72f1a4.jpg)

**Comment by userggg** [comment]
电信今天好点了，可用ip变多了 能正常使用。
![image](https://user-images.githubusercontent.com/38343486/50372539-fd435a00-060a-11e9-89c7-a1e74067ea3d.png)

**Comment by AnyWAT** [comment]
😜忘了说：没交代 h2：100何来？
