### ISSUE TITLE
mac os10.14 不能启动 start文件,怎么破?

### ISSUE THREAD

**Issue by tea8023sky** [XX-net/XX-Net#11813]
![image](https://user-images.githubusercontent.com/13936394/50372380-99b82d00-0608-11e9-8ea7-30aa5f1b219d.png)

**Comment by tea8023sky** [comment]
哪位大佬帮忙看看    小白在这先谢过了 .

**Comment by jiangjiong** [comment]
能打开了么？我的野启动不了，和你的问题一样。

**Comment by tea8023sky** [comment]
![image](https://user-images.githubusercontent.com/13936394/50752441-46d9a900-1289-11e9-8250-1d26d5db4b52.png)
cd 到如图所示的目录下    然后输入指令: python  start.py 就等它跑起来吧 ?
找了很久才发现. 希望对你有用.

**Comment by tea8023sky** [comment]
![image](https://user-images.githubusercontent.com/13936394/50752507-80121900-1289-11e9-8716-0e2ddb88e36b.png)
在控制台 cd 到如图所示的目录下,   然后  输入 python start.py 就等它跑起来吧

**Comment by tea8023sky** [comment]
> 能打开了么？我的也启动不了，和你的问题一样。

![image](https://user-images.githubusercontent.com/13936394/50752658-f7e04380-1289-11e9-8691-50af5783956a.png)
在控制台 cd 到如图所示的目录下, 然后 输入 python start.py 就等它跑起来吧

**Comment by jiangjiong** [comment]
> > 能打开了么？我的也启动不了，和你的问题一样。
> 
> ![image](https://user-images.githubusercontent.com/13936394/50752658-f7e04380-1289-11e9-8691-50af5783956a.png)
> 在控制台 cd 到如图所示的目录下, 然后 输入 python start.py 就等它跑起来吧

这是不是说，start文件本身有错误？
