### ISSUE TITLE
右键点击xxnet托盘图标无法选择代理方式

### ISSUE THREAD

**Issue by wangyou** [XX-net/XX-Net#1181]
系统版本
Property 	Value
XX-Net Version 	2.5.3
Python Version 	2.7.9
Sys Platform 	AMD64, Windows-8-6.2.9200
OS System 	Windows
OS version 	6.2.9200
OS release 	8
OS detail 	Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language 	zh_CN
architecture 	32bit,WindowsPE
Browser 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

右键点击托盘图标无法选择，怎么点都没办法更改，一直都是默认的………………

**Comment by simonasd** [comment]
@wangyou 比较常见的情况是权限问题。尝试以管理员身份运行，非管理员权限无法更改。

**Comment by wangyou** [comment]
我就是以管理员权限运行的，可是无论管理员运行start.lnk或者start.vbs，start.bat，还有桌面快捷方式都以管理员权限运行过，就这样也无法更改，怎么点击都无效……

**Comment by Lrevor** [comment]
以前用的时候成功过没有？
试试关掉xx-net，然后把这个注册表里面的键值全部删掉
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections

**Comment by wangyou** [comment]
在 win10 32位 系统成功过，可以选，昨天重装成64位win10之后就怎么也不行……刚才试了删除你说的注册表，然后删除xxnet文件夹，重新弄，还是不行……

**Comment by simonasd** [comment]
win10的问题不少啊，看来需要一个win10测试一下。

**Comment by wangyou** [comment]
有没有什么办法通过配置文件把全局pac代理设置成默认的呢？？？我是小白………………

**Comment by wangyou** [comment]
我看了wiki里面的https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file，没看懂，搞了半天也没作用……

**Comment by simonasd** [comment]
@wangyou 这个设置并不是保存在配置文件中的，而是当你单击时，修改操作系统的配置。你可以选择手动配置系统代理。简单来说就是：控制面板  -  网络和 Internet  -  Internet选项 - 连接 - 局域网设置，勾选“使用自动配置脚本”，填入http://127.0.0.1:8086/proxy.pac

我过几天在wiki写一个设置代理的图文指南吧。

**Comment by wangyou** [comment]
好的，谢谢，我去试试
