### ISSUE TITLE
3.13.1新版本，有IPv6，但是连接池一直为0，无法连接

### ISSUE THREAD

**Issue by CompleX0321** [XX-net/XX-Net#11824]
状态如图
![default](https://user-images.githubusercontent.com/40204679/50374160-e90c5680-0624-11e9-9178-f80ee1796af8.png)

一直显示系统空闲，但是连接不上，
重新配置过服务器，未果
请求帮助解决
谢谢

以下为诊断
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:454 ipv4:0 ipv6:34
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 1519
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
proxy_state: Fail
ca_state: Fail
选用正确的代理
worker: h1:0 h2:0
is-idle: 1
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel
1、如隧道不正常，控制页内更换服务器
2、如隧道正常，刷新或新开需代理的网页，或再启动一个XX-Net（可免退出先前的）

**Comment by CompleX0321** [comment]
不是很明白“选用正确的代理”如何操作
隧道合格
尝试方法2，未果
感谢帮助

**Comment by AnyWAT** [comment]
> 不是很明白“选用正确的代理”如何操作

描述+贴图：代理（扩展）的使用情况

**Comment by AnyWAT** [comment]
试试（再次）导入 IP https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945

**Comment by AnyWAT** [comment]
瞧瞧 https://github.com/XX-net/XX-Net/issues/11821#issuecomment-449607389

**Comment by Alobe007** [comment]
> 不是很明白“选用正确的代理”如何操作


如SwichOmega这种，设置不对，才会有proxy_state: Fail

**Comment by AnyWAT** [comment]
*.deja.com 必走GAE才代理、证书OK（如GAE正常时）

**Comment by CompleX0321** [comment]
@Alobe007 #
应该来说我用的是系统代理，firefox浏览器没有用插件
但是我以为错误是出现在连接池为0，wiki没有更多关于连接池的信息了
谢谢帮助

**Comment by CompleX0321** [comment]
> 
> 
> 试试：
> 1、（再次）导入 IP [#11800 (comment)](https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945)
> 2、传说中的网线网络禁用连接属性的 IPv6协议

尝试未果
有效ip有的，但是连接池一直为0，不明白原因
能否就连接池给与一些解释
谢谢

**Comment by AnyWAT** [comment]
> 应该来说我用的是系统代理，firefox浏览器没有用插件

无法添加貌似软件检测用的　*.deja.com 必走GAE，除非是“全局GAE”，否则代理、证书都Fail



> 能否就连接池给与一些解释

代码老白无解释。

试试：新版本解压到新位置（非系统盘），不带任何旧文件（仅有自己的 ID及X-Tunnel 账号密码需重新填写）

**Comment by AnyWAT** [comment]
> 有效ip有的，但是连接池一直为0，不明白原因

前提：隧道正常

**Comment by CompleX0321** [comment]
> 
> 
> > 应该来说我用的是系统代理，firefox浏览器没有用插件
> 
> 无法添加貌似软件检测用的　*.deja.com 必走GAE，除非是“全局GAE”，否则代理、证书都Fail
> 
> > 能否就连接池给与一些解释
> 
> 代码老白只抄袭、总结，无解释。
> 试试：新版本解压到新位置（非系统盘），不带任何旧文件（仅有自己的 ID及X-Tunnel 账号密码需重新填写）

隧道正常，决定尝试清理旧文件重新布置
请问是只要删除之前的解压文件夹就完成清理了吗？系统证书和浏览器证书需要清理吗？如果需要的话请问如何清理？
（感觉这段时间本身ip也不稳定，不确定是否是多种情况混合，个人技术不足，感谢帮助）
谢谢

**Comment by AnyWAT** [comment]
先不清理，解压到新位置（非系统盘）。

**Comment by CompleX0321** [comment]
> 
> 
> 先不清理，解压到新位置（非系统盘）。否则要说的也多了些😭

你好，尝试后无效，我依旧不理解连接池为0的原因和意义，并且认为问题就在这里

**Comment by CompleX0321** [comment]
如果真的是代理出现问题的话，我用的是系统全局代理（托盘全局pac智能代理），那就说明是脚本出现问题，这么说起来问10的确在无法使用当天进行过一次系统更新

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by AnyWAT** [comment]
> 问10的确在无法使用当天进行过一次系统更新

XX-Net 又不放在系统盘，应该没影响。

**Comment by CompleX0321** [comment]
> 
> 
> > 问10的确在无法使用当天进行过一次系统更新
> 
> XX-Net 又不放在系统盘，应该没影响。经常更新，已到Win10/1809 的都正常着呢
> 做事要懂得配合，尤其是网络协助。。。
> 贴命令提示符窗口内运行 netsh int ipv6 show teredo 的结果（无需IP地址的2行）及XX-Net 诊断信息

shell teredo 结果
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

诊断
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:480 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
正常前使用：系统托盘全局GAE代理（FireFox 自身的代理设置不会有错？）
scan-ip-thread-num: 1——貌似打开了“自动调整扫描线程数”，关闭，并改到最大的100
is-idle: 1——已空闲，手动检查 IP，不行，再启动一个XX-Net（可不用退出先前的）

**Comment by CompleX0321** [comment]
> 
> 
> 正常前使用：系统托盘全局GAE代理（FireFox 自身的代理设置不会有错？）
> scan-ip-thread-num: 1——貌似打开了“自动调整扫描线程数”，关闭，并改到最大的100
> is-idle: 1——已空闲，手动检查 IP，不行，再启动一个XX-Net（可不用退出先前的）

无效，暂时放弃，感谢，圣诞节快乐

**Comment by AnyWAT** [comment]
如不行，https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204 自己 PING下看哪个服务器快些，换掉。。。

**Comment by AnyWAT** [comment]
> 
> 
> 瞧瞧 [#11821 (comment)](https://github.com/XX-net/XX-Net/issues/11821#issuecomment-449607389)

从此贴追下去，那东东或许比直接修改DNS还好？
