### ISSUE TITLE
重新上传了也不行，，就用暂时蓝灯500M免费改MAC版吧，速度不错！！~以前打不开的也能开了！

### ISSUE THREAD

**Issue by husitong** [XX-net/XX-Net#11825]
重新上传了也不行，，就用暂时蓝灯500M免费改MAC版吧，速度不错！！~以前打不开的也能开了！

视频就。看不了啦~!

一直没IP也联不上，，

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945
