### ISSUE TITLE
删掉之前的版本重启电脑，下载安装新版本，依然无法使用IP数为0

### ISSUE THREAD

**Issue by wtr19941227** [XX-net/XX-Net#11838]
删除掉之前的版本，下载安装新版本，依然无法使用，IP数为0
![20181223141821](https://user-images.githubusercontent.com/34266103/50381296-646e1680-06be-11e9-8fda-d334f2065b40.png)

**Comment by wtr19941227** [comment]
可是 ipv6状态也是fail

**Comment by wtr19941227** [comment]
点击尝试修复 显示teredo隧道是 已禁用，点击启用，重启，无效果

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by wtr19941227** [comment]
我删除了之前的版本，是不是需要按照 如何开启Ipv6的说明，重新开启ipv6？

**Comment by AnyWAT** [comment]
已禁用
管理权限运行 netsh int ipv6 set teredo enterpriseclient
即可开启

**Comment by wtr19941227** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true


![20181223145120](https://user-images.githubusercontent.com/34266103/50381452-95e8e100-06c2-11e9-8b2a-bc54142d8281.png)

**Comment by AnyWAT** [comment]
ca_state: Fail 
> 删除掉之前的版本
data 目录删除了？证书随之也删除了？http://127.0.0.1:8085/?module=gae_proxy&menu=status CA 证书状态(下载)
Win10用系统默认服务器即可，管理权限运行
netsh int ipv6 set teredo natawareclient default

**Comment by wtr19941227** [comment]
尝试 没有效果啊

**Comment by wtr19941227** [comment]
没有效果啊
![20181223150530](https://user-images.githubusercontent.com/34266103/50381527-676c0580-06c4-11e9-830b-440c06514389.png)
![20181223150558](https://user-images.githubusercontent.com/34266103/50381528-6a66f600-06c4-11e9-9679-89cbea498c85.png)

**Comment by wtr19941227** [comment]
![20181223150908](https://user-images.githubusercontent.com/34266103/50381547-c3368e80-06c4-11e9-9702-a332d598b8fd.png)

**Comment by AnyWAT** [comment]
更换服务器

**Comment by AnyWAT** [comment]
Win10用系统默认服务器即可，管理权限运行
netsh int ipv6 set teredo natawareclient default
不行？管理权限运行
netsh int ipv6 set teredo natawareclient 157.56.149.60

**Comment by wtr19941227** [comment]
嗯嗯 多谢  没有更换服务器和以上操作  状态OK了，但是IP数量还是太少
![20181223151330](https://user-images.githubusercontent.com/34266103/50381574-946ce800-06c5-11e9-8a61-318bb0a802ac.png)

**Comment by AnyWAT** [comment]
2楼

**Comment by wtr19941227** [comment]
刚才仅有的几个IPV6又掉为0了，IPv6状态又Fail, 有IP的时候网页也加载不出来
可以通过 高级-导入IP 复制粘贴手动导入IP吗？

**Comment by wtr19941227** [comment]
证书通过首页CA证书状态（下载） 下载上了，状态显示OK

**Comment by AnyWAT** [comment]
> 可以通过 高级-导入IP 复制粘贴手动导入IP吗？

还能怎么？可把 IP4和 IP6保存在一个文本文件内。。。

**Comment by wtr19941227** [comment]
可是要导入的IP是啥？

**Comment by AnyWAT** [comment]
高抬贵鼠，点击链接😱

**Comment by wtr19941227** [comment]
尝试手动导入IP，无法导入，等了一段时间依然是成功导入0个
![20181223163705](https://user-images.githubusercontent.com/34266103/50382082-077c5b80-06d2-11e9-9ac3-a6793331f9a0.png)

**Comment by wtr19941227** [comment]
还有不知道为什么地址栏下边会显示“您必须登陆此网络才能访问互联网“以前是没有的

**Comment by AnyWAT** [comment]
> 等了一段时间依然是成功导入0个

如是已导入过就是这样的，但没看到有效数长了？


> “您必须登陆此网络才能访问互联网“

貌似代理速度不佳的结果

**Comment by wtr19941227** [comment]
并没有发现有效数长，我以前是没有手动导入过的。
速度很慢，网页根本加载不出

**Comment by wtr19941227** [comment]
现在页面上显示的状态应该都是OK的，只有IP和延迟有问题，怎么解决？
请问是否跟我用的是公共ID有关系呢？

**Comment by AnyWAT** [comment]
原来你复制 IP后动了格式：一个 IP一行

**Comment by wtr19941227** [comment]
啊  这样的啊  我试试看

**Comment by wtr19941227** [comment]
还是不行  导入了300多个 很快又降到0了
![Uploading QQ截图20181223171539.png…]()

**Comment by wtr19941227** [comment]
网页依然打不开

**Comment by wtr19941227** [comment]
总IP数是400多，但是可用的又掉到0个了，其他东西我没开着啊，只开着360

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:436 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
![11111111111111](https://user-images.githubusercontent.com/34266103/50382385-ee2add80-06d8-11e9-962c-da6df9fb624a.png)
![222222222222222](https://user-images.githubusercontent.com/34266103/50382386-f125ce00-06d8-11e9-89eb-eda54681fe30.png)

**Comment by wtr19941227** [comment]
另外那个帖子中提到的部署服务端，我没办法链接到谷歌的网络怎么部署呢？

**Comment by AnyWAT** [comment]
> 只开着360

![default](https://user-images.githubusercontent.com/37962734/50382446-326aad80-06da-11e9-9887-f97ca5121d2a.png)
这是。。。
貌似不卸载国祸，没辙😜

**Comment by wtr19941227** [comment]
前几天尝试打开过几次都是IP一会就掉光了，对XX-NET有点灰心了。今天本来打算找其他VPN的，突发奇想连接上网线尝试了一下，卧槽！！！神奇的事情发生了，IP噌噌往上涨，总IP数全部都是有效IP，而且持续稳定可用，到现在持续了20分钟，IP始终保持稳定，网速相当快！！！

**Comment by wtr19941227** [comment]
![qq 20190104104417](https://user-images.githubusercontent.com/34266103/50671766-e0e1ed00-100e-11e9-9a37-9c03a2395f0f.png)
