### ISSUE TITLE
反馈信息，一会一变这种问题太奇怪了

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#11849]
GAEProxy 状态信息。总在变换，太奇怪了。

蓝字：XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。

红字：连接尚未建立。

红字：等待扫描 IP，建议开启 IPv6。

红字：你可以尝试 开启IPv6 或 使用X-Tunnel。

归根结底就是不让你用，你就不能用了。没有为什么。人家电信都把技术都研究到封顶，也就是说都玩透了。XX-net虽然推出了各种改造方法，对用户来说也有一定的难度。

**Comment by 80068** [comment]
你看看，我刚说完这话，就能用了。你说说他们能不知道吗？ 他天天都在看着用户。

**Comment by carlchan99** [comment]
我用电信的，也是GAEProxy 状态信息频繁变换，而且终端显示大量的“[gae_proxy][WARNING] h2 timeout”信息，h2应该是连接池。

**Comment by 80068** [comment]
@carlchan99 看这意思，是统一模式，一会能连、一会不能连。没辙，等吧，看看后续有什么临时方法吧。

**Comment by AnyWAT** [comment]
😱 https://github.com/XX-net/XX-Net/issues/11848#issuecomment-449641050
隧道正常，不满意就再次导入 IP https://github.com/XX-net/XX-Net/issues/11846#issuecomment-449638761

**Comment by 80068** [comment]
@AnyWAT https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138

导入这个链接的IPV6地址了，但还是显示：连接尚未建立

**Comment by AnyWAT** [comment]
给你的导入 IP https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945 明显地有
use-ipv6: force_ipv6——改为自动 
不再次提醒，都不会自己处理😭

**Comment by 80068** [comment]
@AnyWAT 之前就是改的自动啊，IP也导入了。着刚看到：依然是链接尚未建立

**Comment by carlchan99** [comment]
经观察，“GAEProxy 状态信息频繁变换”，一会显示“一切正常”，下一秒出现“连接尚未建立”，是出现在“连接池”h1有个能用的ip，但马上立即就变成不能用（显示为0），如“连接池”h2有数字，则可能/可以保持几分钟正常。

另外，我两台机子，分别是电信和移动的线路，据我以往有观察到的情况，以前h2都是为0，只有h1有数字。这次大家大面积出现问题，我发现我这两台机子的“连接池”h2首次看到有连接数了，它是间歇性，最高好像是近20，但一会儿之后会掉及归零，掉的过程中看到终端显示大量的“[gae_proxy][WARNING] h2 timeout”信息，不论是用公共id还是重新部署的个人id都有此大量提示信息。

**Comment by AnyWAT** [comment]
貌似 h1永远为0，有高人 h2:100 https://github.com/XX-net/XX-Net/issues/11815#issuecomment-449556344
连接池(帮助) https://github.com/XX-net/XX-Net/wiki/GoAgent-Connection-status

**Comment by xylona1900** [comment]
我也遇到了这样的问题，我是校园网。。也重新导入IP了，还是坚持不了几分钟

**Comment by AnyWAT** [comment]
> 
> 
> 我也遇到了这样的问题，我是校园网。。也重新导入IP了，还是坚持不了几分钟

netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net 诊断信息

**Comment by xylona1900** [comment]
> > 我也遇到了这样的问题，我是校园网。。也重新导入IP了，还是坚持不了几分钟
> 
> 如果[隧道正常](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204)，试试增大扫描线程数或再次导入 IP，稍侯即可正常？[#11800 (comment)](https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945)

都按照issue里面的方法搞了还是掉啊
