### ISSUE TITLE
请问如何配置网站黑名单？有部分网站不想被访问

### ISSUE THREAD

**Issue by chuntju** [XX-net/XX-Net#11854]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
这里能行？不是写入系统 hosts 简单？
![default](https://user-images.githubusercontent.com/37962734/50389590-021d2080-0767-11e9-9dea-80c5e03fe677.png)

**Comment by chuntju** [comment]
> 这里能行？不是写入系统 hosts 简单？
> ![default](https://user-images.githubusercontent.com/37962734/50389590-021d2080-0767-11e9-9dea-80c5e03fe677.png)

写入host不起作用

**Comment by AnyWAT** [comment]
貌似写入后得 ipconfig /flushdns 后生效

**Comment by chuntju** [comment]
> 貌似写入后得 ipconfig /flushdns 才生效？

用了一个谷歌的插件解决了，访问黑名单时自动跳转到google.com
Website Blocker for Chrome
多谢你~
