### ISSUE TITLE
额.......一会复活，一会又挂。

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#11863]
真真的服了。一会复活，一会又挂。
![01](https://user-images.githubusercontent.com/39740368/50398693-8f3a9680-07b4-11e9-99a9-f9737a453817.jpg)
![02](https://user-images.githubusercontent.com/39740368/50398722-c90b9d00-07b4-11e9-8f53-16b99fe0529f.jpg)

**Comment by AnyWAT** [comment]
如果[隧道正常](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204)，试试增大扫描线程数或再次导入 IP，稍侯即可正常？https://github.com/XX-net/XX-Net/issues/11800#issuecomment-449539945

**Comment by robinlighting** [comment]
现在我什么都没做，又恢复了……………

**Comment by robinlighting** [comment]
很好玩，又恢复了。是不是软件有问题？
有没有很好的解释地址池的内容？感觉地址池有时候猛增到20-30之间，不一会就归零，再后IP地址猛掉。
![01](https://user-images.githubusercontent.com/39740368/50398868-fdcc2400-07b5-11e9-8949-9cf530a88c62.jpg)

**Comment by xzhe57** [comment]
我和你的状态一样，一会儿复活，一会儿挂

**Comment by AnyWAT** [comment]
是否因 https://github.com/chengr28/Pcap_DNSProxy 才不会“一会复活，一会又挂。”？https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231

**Comment by AnyWAT** [comment]
> 有没有很好的解释地址池的内容？

https://github.com/XX-net/XX-Net/wiki/GoAgent-Connection-status

**Comment by robinlighting** [comment]
Pcap_DNSProxy，我没有用。

> 是否因 https://github.com/chengr28/Pcap_DNSProxy 才不会“一会复活，一会又挂。”？[#11843 (comment)](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)

**Comment by robinlighting** [comment]
连接池(帮助) | 新:0 h1:0 h2:2
-- | --
折腾这么久，感觉连接池很重要，当h2很好的时候（20-40个），那个滑溜溜的程度，感觉就是在本机浏览网页。

当地址池归零，一夜回到“石器时代”。

**Comment by robinlighting** [comment]
> 是否因 https://github.com/chengr28/Pcap_DNSProxy 才不会“一会复活，一会又挂。”？[#11843 (comment)](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)

DNS，你这个倒是提醒了我，我这里设置8.8.8.8和8.8.4.4。
我改改DNS，恢复默认。试一下。

**Comment by robinlighting** [comment]
So, good。DNS改回默认。
![01](https://user-images.githubusercontent.com/39740368/50399294-64067600-07b9-11e9-9884-45bf8e58d8ac.jpg)
![02](https://user-images.githubusercontent.com/39740368/50399295-64067600-07b9-11e9-8923-f0d29093c96e.jpg)

**Comment by htpao2** [comment]
> 改回之后，在cmd里面输入ipconfig/flushdns，清理dns缓存，之后断线，一会再链接wifi。估计很多人可以出现奇迹。

没用

**Comment by AnyWAT** [comment]
> 
> 
> > 改回之后，在cmd里面输入ipconfig/flushdns，清理dns缓存，之后断线，一会再链接wifi。估计很多人可以出现奇迹。
> 
> 没用

 用了 https://github.com/chengr28/Pcap_DNSProxy 一直正常的呢？

**Comment by dirtyluke** [comment]
我这也是，大部分时间是IP延迟、没有有效IPV6
@SeaHOH 这里提个建议，不知道行不行，可以出一份`排障指南`，这份排障指南可以大致确定问题出在哪一环节，这样我们用的也比较清楚，反馈信息也清楚。这样的指南刚开始不用细到每一步，只需要能确定在哪一个环节出问题就可以，后面有需要再不断补充

**Comment by wendeben** [comment]
很不稳定

**Comment by dirtyluke** [comment]
@AnyWAT 你没仔细看，我说的是大部分时间，偶尔抽风好一下，另外你推荐的那个，应该是个DNS服务器把，没明白IP延迟9999和DNS服务器有什么关系

**Comment by AnyWAT** [comment]
总之，除了速度又好又差，没有你的情况，一直正常：https://github.com/XX-net/XX-Net/issues/11821#issuecomment-449607389

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。
