### ISSUE TITLE
更新到新版本3.13.1在之后，正常工作一段时间后，状态正常或空闲，有时会突然间 ipv6 fail

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#11862]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:80
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:33
scan-ip-thread-num: 100
ip-quality: 381
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by LN-VIVI** [comment]
![360 16240130669766](https://user-images.githubusercontent.com/18262731/50398548-636ae100-07b3-11e9-82d0-662807663f05.png)

**Comment by imudie123** [comment]
我是这样解决的：
退出XXNET
关闭浏览器。
然后重新启动XXNET就好了。

有效ip反复在3-90个之间摇摆，很不稳定的样子。

**Comment by LN-VIVI** [comment]
![360 16240130669766](https://user-images.githubusercontent.com/18262731/50422455-d47ac900-0885-11e9-9fb1-04bf03d141d2.png)
![360 17571115292665](https://user-images.githubusercontent.com/18262731/50422673-10625e00-0887-11e9-91bd-b59c780e09a2.png)
为啥更新之后好像更稳定了？

**Comment by LN-VIVI** [comment]
@AnyWAT   @SeaHOH

**Comment by LN-VIVI** [comment]
@AnyWAT @SeaHOH为啥更新之后好像更稳定了？

**Comment by AnyWAT** [comment]
> 为啥更新之后好像更稳定了？

没明白：貌似从开始看到的都是3.13.1，神马更新？上面那句与本贴标题貌似矛盾？

**Comment by LN-VIVI** [comment]
> > 为啥更新之后好像更稳定了？
> 
> 没明白：貌似从顶楼开始看到的都是3.13.1，神马更新？上面那句与本贴标题貌似矛盾？

之前用的是3.12版本，经常 fail 还经常打不开Google ，把扫描数扩大或者是缩小都是这样，更新之后好像更稳定了
