### ISSUE TITLE
什么情况？公司移动宽带  刚有几个有效ip6ip 能用，一下子又不行了

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#11873]
e.......什么情况？公司移动宽带  刚有几个有效ip6ip 能用，一下子又不行了，家里联通宽带一切正常
![1](https://user-images.githubusercontent.com/18262731/50410438-f8152380-0833-11e9-9522-f187dacb7348.png)

**Comment by diqiudiguo1** [comment]
我的也是，跑过来找方法。
