### ISSUE TITLE
昨天好一天，今天又坏了。天津联通。

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#11877]
连接尚未建立。
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	OK
有效 IPv4 IP 数	0
有效 IPv6 IP 数	1
总 IP 数	100
XX-Net 状态	工作
IP 延迟	1056
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	OK
CA 证书状态(下载)	OK
IP 扫描线程数(设置)	50

**Comment by 80068** [comment]
打开电脑一看XX-net，完了，彻底没有一点变好的意思。

**Comment by akira210271** [comment]
我也是天津联通

**Comment by akira210271** [comment]
手机用联通4G有时能获取很多ipv6的ip

**Comment by 80068** [comment]
前几个月是对蓝灯进行封锁，现在一看又把XX-net封锁，这网将来没法用了。恳请XX-net研发新软件。前几年是管不了XX-net，因为人家技术先进啊，现在是他们已经破解了XX-net，并且可以对XX-net随时关闭，随时开启。这问题也太严重了，不是用户改改软件后台就能解决的了。@xxnet
