### ISSUE TITLE
Unable to connect to 8085 from other pc from 2.5.0

### ISSUE THREAD

**Issue by cchalpha** [XX-net/XX-Net#1188]
从2.5.0开始无法从其他机器连接到8085端口，只绑定了本机的8085端口。
对于局域网应用，希望从其他机器登录web control管理。希望修复。

**Comment by xxnet** [comment]
要在系统的设置页面里打开开关，就可以从远程进行管理了。

在 2015年10月10日 上午11:11，Alfred Chen <notifications@github.com>写道：

**Comment by cchalpha** [comment]
有对应的配置文件可以直接修改吗？因为跑xxnet的是个树莓派，没有浏览器开设置页面。

**Comment by xxnet** [comment]
最简单的方法是在PC上跑，设置后，拷贝过去。

直接修改，请看data/launcher/config.yaml

在 2015年10月10日 下午5:11，Alfred Chen <notifications@github.com>写道：

**Comment by cchalpha** [comment]
data/launcher/config.yaml

launcher: {allow_remote_connect: 1, control_port: 8085, popup_webui: 0, show_systray: 0}
