### ISSUE TITLE
3.13.1能正常下载么？

### ISSUE THREAD

**Issue by higoge** [XX-net/XX-Net#11893]
我从下载地址https://github.com/XX-net/XX-Net/archive/3.13.1.zip下载到的包一直是9兆左右，实际大小是12M，从XX-net的自定义升级也是一样，下载后检测不通过，是Github的问题还是打包的问题？

**Comment by AnyWAT** [comment]
貌似此站上图、下载需代理
其它下载分享 https://github.com/XX-net/XX-Net/issues/11761
