### ISSUE TITLE
Teredo 隧道Win10用户的3.13.1版个人体验：几乎运行即正常，自动维持良好的工作状态

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#11892]
1、鉴于传说的全网不足500 IPv6，设置——[总 IP 数](https://github.com/XX-net/XX-Net/issues/11291 二楼)：300，IP 扫描线程数：100 并关闭“自动调整扫描线程数”（完全无代理需求时可打开），IP 模式：自动（可导入 IP4 #11775 ...）
2、辅以 https://github.com/chengr28/Pcap_DNSProxy 类[东东](https://github.com/XX-net/XX-Net/issues/11287#issuecomment-415963218)（[初次安装运行](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)，禁用 Smart Router 模块或退出XX-Net，以释放53端口）后果严重：基本没有彻底不能用，只有高低速度之分，哈哈哈
3、保证[隧道正常](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204)，有效 IP数基本自动等于总 IP数，开始运行时GAEProxy 状态自动从“尚未连接”到“系统正常（空闲）”，此时连接池依然是零，若有网页代理需求，立马显示“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。”同时连接池自然增长，刷新网页，代理逐步正常；没有网页代理需求时，会“XX-Net 状态”空闲，但有效 IP数及连接池不会是零。
4、如出现有效 IP数及连接池归零并不能自动维护、IP延迟较大，或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或[导入 IP6](https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138)再手动检查 IP，或再次启动程序（无需先退出）

附：
1、参照白名单 https://github.com/MatcherAny/whitelist.pac 的 auto switch 情景模式（貌似特别适用于X-Tunnel ），利用 http://127.0.0.1:8086/proxy.pac 创建 gfwlist.txt 下黑名单的情景模式：GAE_PAC的自动切换，此时方可自添加任意切换规则。。。Chrome+SwitchyOmega下采用此PAC自动切换（等同于原 GAE-Proxy 自动切换？）
2、如是已部署、成功使用过3.12.2的，无需再次（上传）部署，除非更新服务端（3.13.1并无公告此要求）
3、X-Tunnel 正常的前提：
1) 确保GAE或其它任一前端正常
2) 指定服务器（不选自动）
3) 关闭貌似已无效的后面3个前端（CloudFlare 偶尔有效：现因有 IPv4应基本有效，如 https://github.com/XX-net/XX-Net/issues/11801 。尤其在GAE偶尔无效时可做临时替补，其余3个的工作数或流量几乎永远是0） https://github.com/XX-net/XX-Net/issues/11227#issuecomment-408638834
![default](https://user-images.githubusercontent.com/37962734/50427541-f146e900-08e5-11e9-9c13-993a2c027d58.png)
PS：较 https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215 有些许修改

**Comment by LN-VIVI** [comment]
这么早

**Comment by Hunerk** [comment]
> 1、鉴于传说的全网不足500 IPv6，设置——总 IP 数：300，IP 扫描线程数：100 并关闭“自动调整扫描线程数”，IP 模式：自动
> 2、辅以 https://github.com/chengr28/Pcap_DNSProxy 类[东东](https://github.com/XX-net/XX-Net/issues/11287#issuecomment-415963218)（[初次安装运行](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)，禁用 Smart Router 模块或退出XX-Net，以释放53端口）后果严重：基本没有彻底不能用，只有高低速度之分，哈哈哈
> 3、保证[隧道正常](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204)，有效 IP数基本自动等于总 IP数，开始运行时GAEProxy 状态自动从“尚未连接”到“系统正常（空闲）”，此时连接池依然是零，若有网页代理需求，立马显示“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。”同时连接池自然增长，刷新网页，代理逐步正常；没有网页代理需求时，会“XX-Net 状态”空闲，但有效 IP数及连接池不会是零。
> 4、如出现有效 IP数及连接池归零并不能自动维护、IP延迟较大，或手动检查 IP，或[导入 IP6](https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138)再手动检查 IP，或再启动程序（无需先退出）
> 附：参照白名单 https://github.com/MatcherAny/whitelist.pac 的 auto switch 情景模式（貌似特别适用于X-Tunnel ），利用 http://127.0.0.1:8086/proxy.pac 创建 gfwlist.txt 下黑名单的情景模式：GAE_PAC的自动切换，此时方可自添加任意切换规则。。。Chrome+SwitchyOmega下采用此PAC自动切换（等同于原 GAE-Proxy 自动切换？）
> ![default](https://user-images.githubusercontent.com/37962734/50427541-f146e900-08e5-11e9-9c13-993a2c027d58.png)

你中文是体育老师教的吗？自己能看懂不，我是看不懂

**Comment by TYK-01** [comment]
我的原生IPV6,刚打开XX-Net正常，一段时间不用后，有效IP不掉，连接池归零，IPV6显示Fail，重新检查IP后正常！

**Comment by nsisy** [comment]
没毛用，先顶一下

**Comment by xc1988** [comment]
没有任何卵用

**Comment by YJ0** [comment]
已经确定是机器@AnyWAT

**Comment by ZOOWRIA** [comment]
> 
> 
> 试过了你N多种方法,每条都毛用,纯粹折腾..........直接换某灯了



我用路由开IPV6 现在隧道是休眠状态

可以随便上油管没问题

**Comment by ssjck** [comment]
> > 试过了你N多种方法,每条都毛用,纯粹折腾..........直接换某灯了
> 
> 我用路由开IPV6 现在隧道是休眠状态
> 
> 可以随便上油管没问题

不折腾了,现在用某灯用得好

**Comment by robinlighting** [comment]
楼主是不是机器人？

**Comment by AnyWAT** [comment]
> 
> 
> 楼主是不是机器人？

赚钱机器

**Comment by AnyWAT** [comment]
>  公司移动网 扫不出来 用了 https://github.com/chengr28/Pcap_DNSProxy 这方法也不行，换了3.13版之后扫出几个ip一下就没了 ，又换回3.12 扫都扫不出来

找让你版本换来换去的人去。。。
扫不出来 https://github.com/XX-net/XX-Net/issues/11892 4、如出现有效 IP数及连接池归零并不能自动维护、IP延迟较大，或手动检查 IP，或[导入 IP6](https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138)再手动检查 IP，或再次启动程序（无需先退出）

**Comment by LN-VIVI** [comment]
> 这方法也不行：多此法少下图（国产）的至少一直正常，嗯嗯


你是认真的吗？机器人？

**Comment by AnyWAT** [comment]
1、[无污染的DNS有利于](https://github.com/XX-net/XX-Net/issues/11287#issuecomment-415960977)。。。从4个8到4个1的DNS各种搜寻，进而是不再费事的 [Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy) 
2、较大的总 IP数配合较大的扫描线程数，得到较多的有效 IP数，进而是较小的 IP 延迟及较大的连接池，有利于。。。
3、源于XX-Net 的[XX-Mini](https://github.com/xyuanmu/XX-Mini) 对 max_scan_ip_thread_num（总 IP数）的解释：[谷歌IP上限，超过则剔除延时高的IP](https://github.com/XX-net/XX-Net/issues/11376#issuecomment-425376757)
4、网络的不断变化，XX-Net 软件默认总 IP 数也不断在变化：3000-6000-1000-500-300-100，貌似可用 IPv6也从1万大几到了不足500
5、为了较好的体验，各种尝试都是基于怎样才能保证：[超过则剔除延时高的IP](https://github.com/XX-net/XX-Net/issues/11376#issuecomment-425376757) https://github.com/XX-net/XX-Net/issues/10184 https://github.com/XX-net/XX-Net/issues/10515 https://github.com/XX-net/XX-Net/issues/10919 https://github.com/XX-net/XX-Net/issues/11291 https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11967
![image](https://user-images.githubusercontent.com/37962734/50589554-19c07b80-0ec2-11e9-9880-399604ad7bee.png)

安卓用户有人回应：https://github.com/XndroidDev/Xndroid/issues/193#issuecomment-450711257

**Comment by AnyWAT** [comment]
@yyuurrii34 Joined 3 hours ago 来。。。
