### ISSUE TITLE
（已赠完）转赠x-tunnel流量，有需要请提供邮箱。

### ISSUE THREAD

**Issue by msqin** [XX-net/XX-Net#11895]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by kitkw** [comment]
jamw@live.cn

**Comment by tatiyixi** [comment]
tatiyixi@21cn.com

**Comment by aeguicai** [comment]
1397862477@qq.com

**Comment by yanxiaoguang** [comment]
yoyoflash@gmail.com
多谢！

**Comment by fhq8800** [comment]
fhq800@gmail.COM        THANKYOU

**Comment by fhq8800** [comment]
fhq8800@gmail.COM   THANKYOU

**Comment by guanbaozi** [comment]
lanqiuxiake@gmail.com
多谢啦

**Comment by lkyyang** [comment]
xuefeng0507@gmail.com
谢谢！

**Comment by shukuang01** [comment]
shukuang003@gmail.com
Thanks very much

**Comment by shukuang01** [comment]
shukuang001@gmail.com
Thanks very much!

**Comment by LN-VIVI** [comment]
huangyuanwei1997@gmail.com

**Comment by yanxiaoguang** [comment]
已经收到，感谢！

msqin <notifications@github.com> 于2018年12月26日周三 下午1:29写道：

**Comment by northsheep** [comment]
northsheep.bfdy@gmail.com

多谢！

**Comment by GFconcept** [comment]
yihueicool@gmail.com THANKS

**Comment by msqin** [comment]
> [kobebyrant236@gmail.com](mailto:kobebyrant236@gmail.com)
> 还有流量可以转吗？十分感谢

已转

**Comment by msqin** [comment]
> [yihueicool@gmail.com](mailto:yihueicool@gmail.com) THANKS

已转

**Comment by msqin** [comment]
> northsheep.bfdy@gmail.com

已转

**Comment by msqin** [comment]
> huangyuanwei1997@gmail.com

已转

**Comment by jameskaxi** [comment]
还有吗？jameskaxi@gmail.com

**Comment by msqin** [comment]
@所有人. 有谁还需要的麻烦在我这条comment下按顺序写邮箱。大家给的邮箱太多，都找不过来了。
1.
2.
3.
4.
5.
按这个序号往下加吧，最多还能分享给10个人(每人6G左右)

**Comment by jameskaxi** [comment]
> @所有人. 有谁还需要的麻烦在我这条comment下按顺序写邮箱。大家给的邮箱太多，都找不过来了。
> 1.
> 2.
> 3.
> 4.
> 5.
> 按这个序号往下加吧，最多还能分享给10个人(每人6G左右)

1.  jameskaxi@gmail.com

**Comment by msgj10** [comment]
msgj101010@gmail.com
感谢！

**Comment by wanwiy** [comment]
115988808@qq.com

**Comment by 80068** [comment]
感谢楼主！
bmwnnw@gmail.com

**Comment by K3info** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net

**Comment by xzhe57** [comment]
buyan1957@gmail.com
谢谢！

**Comment by xzhe57** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net
4.buyan1957@gmail.com

**Comment by Mitchell08** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net
4.buyan1957@gmail.com
5.wyj2009sky@gmail.com

**Comment by magicso** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net
4.buyan1957@gmail.com
5.wyj2009sky@gmail.com
6.lincthen111@gmail.com

**Comment by pxw2012** [comment]
1.1239926626@qq.com

**Comment by Alan1996112** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net
4.buyan1957@gmail.com
5.wyj2009sky@gmail.com
6.lincthen111@gmail.com
7.alanuestc112@gmail.com

**Comment by aeguicai** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net
4.buyan1957@gmail.com
5.wyj2009sky@gmail.com
6.lincthen111@gmail.com
7.alanuestc112@gmail.com
8.ae_guicai@hotmail.com

**Comment by wg1992** [comment]
wanggang1992@gmail.com

**Comment by xp248187189** [comment]
248187189@qq.com 谢谢

**Comment by andychoume** [comment]
1.jameskaxi@gmail.com
2.115988808@qq.com
3.eva001@hainan.net
4.buyan1957@gmail.com
5.wyj2009sky@gmail.com
6.lincthen111@gmail.com
7.alanuestc112@gmail.com
8.ae_guicai@hotmail.com
9.w894061032@outlook.com

**Comment by alphabet719** [comment]
10.alphabet719@gmail.com 多谢！

**Comment by msqin** [comment]
> alphabet719@gmail.com

已转

**Comment by cliff111** [comment]
mineroba@outlook.com 谢谢
