### ISSUE TITLE
XX-net被点鑫、炼通禁止使用后更远期设想。

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#11890]
只能测试

**Comment by smallant** [comment]
傻不傻以后再说 关键是我们做技术的 不好弄

**Comment by 80068** [comment]
@AnyWAT 感谢，跪谢！
今天太晚了明天继续测试。

**Comment by AnyWAT** [comment]
试试：辅以此类东东？ https://github.com/chengr28/Pcap_DNSProxy （后果：没有彻底不能用，只有好次之分）

**Comment by 80068** [comment]
@AnyWAT 好的 明天试试看

**Comment by hugohehuan** [comment]
> 
> 
> 试试：辅以此类东东？ https://github.com/chengr28/Pcap_DNSProxy （后果：没有彻底不能用，只有好次之分）

已使用很久了，这次都没躲过去

**Comment by 80068** [comment]
今天白天试了，XX-net都导入还是不行，但某灯暂时可用，先用它。等XX-net后续看看有没有更好的解决方案。@AnyWAT

**Comment by AnyWAT** [comment]
> > 试试：辅以此类东东？ https://github.com/chengr28/Pcap_DNSProxy （后果：没有彻底不能用，只有好次之分）
> 
> 已使用很久了，这次都没躲过去

一直正常 https://github.com/XX-net/XX-Net/issues/11892
