### ISSUE TITLE
空闲时"仅 IPv6" 不可用

### ISSUE THREAD

**Issue by TYK-01** [XX-net/XX-Net#11896]
刚刚打开XX-NET时没问题，过一段时间显示"仅 IPv6" 不可用，请检查。
有效IP数不掉，连接池归零，IPV6状态显示Fail，有网络请求时也不恢复，检查一遍IP之后恢复正常，空闲一段时间之后又是如此，一直使用中无此问题（Youtube播放视频）。

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:85 ipv4:0 ipv6:65
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 684
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
试试：#11892

**Comment by AnyWAT** [comment]
> 试试：#11892

试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名
