### ISSUE TITLE
说一下从1.7X 回退 到1.5.5 后改善的地方

### ISSUE THREAD

**Issue by yqfang** [XX-net/XX-Net#119]
1. 1.5.x  看 youtube 的速度明显比最新的几个版本都要快
2. 使用 you-get 下载 youtube 视频时, 1.7 的几个版本都会出现 解析异常: https://github.com/soimort/you-get/issues/511

网络情况：中国电信10m

**Comment by xxnet** [comment]
在 2015年4月8日 上午11:16，yqfang <notifications@github.com>写道：

>
>    1. 1.5.x 看 youtube 的速度明显比最新的几个版本都要快
>
> 差别在ip_connect_interval，我下个版本改小，而且配置上可以手动调整。
以后有必要再调大。

**Comment by xxnet** [comment]
试试1.8.1版本（服务端要重新部署）
解决视频下载的问题。

速度方面，参数也有调过，希望能快些

**Comment by yqfang** [comment]
@xxnet  直接升级到1.82, 视频下载问题解决! ip_connect_interval 默认 为2,  但是速度依然不快而且不稳定, 设置为1 后, 有了很显著的改善, 特别是下载youtube 视频的速度, 可以和1.5x 并驾齐驱了. 网页访问的稳定性有待观察(出现过几次 502), ip_connect_interval 这个参数我猜测根据不同的网络环境且因人而异的, 所以可以调整设置很有必要! 这次改进很大, 非常感谢!

**Comment by yqfang** [comment]
@xxnet  严重推荐 ip_connect_interval 设置为1, 从未有过如此酣畅淋漓的感觉, 无论是 网页还是视频, 无论是速度或者稳定性!

**Comment by xxnet** [comment]
ip_connect_interval 这个参数我猜测根据不同的网络环境且因人而异

是的，有用户反馈调整为10后稳定，而更小的值性能更好。
所以特别留出来自己调整

在 2015年4月10日 上午12:55，yqfang <notifications@github.com>写道：

**Comment by yqfang** [comment]
好悲剧, 早上和下午都好好的, 现在一个网页都打不开, 有时查看了一下日志, 发现get ip 基本都是 fail 或者 timeout, 用回 1.5.5稍微好点（但有各种５０２错误）莫非是ip_connect_interval 设置过小触发了GFW 的某种ｉｐ封锁机制?

**Comment by yqfang** [comment]
第二天重新恢复稳定状态， 恢复 ip_connect_interval 为3 求一天稳定

**Comment by lele2010lele** [comment]
请问你用什么软件下载的YouTube视频啊

**Comment by xxnet** [comment]
ip_connect_interval 改大，10以上会好些，如果敏感的网络下。

说说你那边是什么网络吧，给大家参考

2015-04-11 1:30 GMT-04:00 lele2010lele <notifications@github.com>:

**Comment by yqfang** [comment]
@lele2010lele:  you-get, 并设置goagent代理

**Comment by yqfang** [comment]
1.8.5 在ip_connect_interval 默认为10的情况下已经很稳定了,暂时无欲无求~
