### ISSUE TITLE
这是不是说明 IPV6不管用啊？？

### ISSUE THREAD

**Issue by GFconcept** [XX-net/XX-Net#11900]
Pv4 域名连接测试 |   | 成功 (0.758s) 使用 ipv4
-- | -- | --
IPv6 域名连接测试 |   | 超时 (16.019s)
双栈域名连接测试 |   | 成功 (0.600s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.512s) 使用 ipv4
无域名 IPv4 连接测试 |   | 成功 (0.358s) 使用 ipv4
无域名 IPv6 连接测试 |   | 超时 (16.953s)
IPv6 大数据包传输测试 |   | 超时 (16.937s)
测试运营商 DNS 是否接入 IPv6 |   | 成功 (1.166s) 使用 ipv4
查询 IPv4 运营商 |   | 成功 (0.770s) 使用 ipv4 ASN 4837
查询 IPv6 运营商 |   | 超时 (15.065s)

**Comment by AnyWAT** [comment]
貌似从未使用过此检测，只要隧道正常，试试：https://github.com/XX-net/XX-Net/issues/11892

**Comment by xiaoas** [comment]
是啊。。。我也是 不知道咋解决

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11920 【（并不保证你也正常的）傻瓜步骤：https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 】
