### ISSUE TITLE
3.13.1版本问题严重 求更新

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#11918]
1： 几乎搜不到ip， 即使搜到了 也很快挂
2： server非常不稳定， 很难换到好server

求XX大更新

**Comment by Hunerk** [comment]
还不明白吗，已经挂了。出钱吧，墙已加高，免费的已经搞不定了，

**Comment by varicella** [comment]
你的网络问题，电脑连接手机热点，就可以啦

**Comment by zhencaoxing** [comment]
我的手机是移动的没问题，但是电信的光纤就不可以

**Comment by zhencaoxing** [comment]
IP昨天改成gae proxy 模块后调整了最大扫描线程100，自动扫描线程关闭，IP模式自动后正常了一天，然后今天早上又挂了

**Comment by xc1988** [comment]
最近风声紧

**Comment by AnyWAT** [comment]
试试：https://github.com/XX-net/XX-Net/issues/11920

**Comment by zhencaoxing** [comment]
> 貌似与3.13.1无关。试试：#11920
> 
> ![image](https://user-images.githubusercontent.com/37962734/50504321-c4423400-0aa7-11e9-8fde-78575516d7e6.png)

谢谢老兄提供的解决方案  完美解决

**Comment by zhencaoxing** [comment]
> 貌似与3.13.1无关。试试：#11920
> 
> ![image](https://user-images.githubusercontent.com/37962734/50504321-c4423400-0aa7-11e9-8fde-78575516d7e6.png)

谢谢老兄提供的解决方案  完美解决
