### ISSUE TITLE
3.13.1如何手动更新？

### ISSUE THREAD

**Issue by waylenz** [XX-net/XX-Net#11927]
我原有版本3.11.10,打开XX-net后无法使用，甚至访问不了github,而关闭XX-net可以上github。
关闭XX-net，我下载3.13.1，文件名XX-Net-3.13.1_2.7z。然而，怎么离线升级？
我理解在如下界面升级：　配置－》版本－》手动维护，里面并没有3.13.1版本
![image](https://user-images.githubusercontent.com/19546561/50533181-40e41980-0b5f-11e9-8ec2-b8dbc967da78.png)
关键是是下载的 .z文件怎么处理呢？ 我把它解压到code目录中，不识别

**Comment by cypcym** [comment]
页面右上角的 立即更新 ，试过没？

**Comment by AnyWAT** [comment]
> 甚至访问不了github,而关闭XX-net可以上github。
> 关闭XX-net，我下载3.13.1，文件名XX-Net-3.13.1_2.7z。然而，怎么离线升级？

貌似 github 上图、下载需代理，*.github.com 可直连，其它与 GitHub 有关走代理


> 关键是是下载的 .z文件怎么处理呢？ 我把它解压到code目录中，不识别

手动解压的结果，貌似不是3.13.1 而是 default

**Comment by AnyWAT** [comment]
> 页面右上角的 立即更新 ，试过没？

代理不正常，就是到猴年马月也不一定有结果。手动下载是正道

**Comment by waylenz** [comment]
> > 页面右上角的 立即更新 ，试过没？
> 
> 代理不正常，就是到猴年马月也不一定有结果。手动下载是正道

都说了，关闭代理能够正常下载，下载不是问题，这是截图，3.11.3是解压后的目录
![image](https://user-images.githubusercontent.com/19546561/50533972-ec956580-0b6f-11e9-86ae-9f96d103d77e.png)

**Comment by waylenz** [comment]
开了代理不能访问，而立即更新是在线下载并升级的，当然没有作用

**Comment by AnyWAT** [comment]
> > 关键是是下载的 .z文件怎么处理呢？ 我把它解压到code目录中，不识别
> 
> 手动解压的结果，貌似不是3.13.1 而是 default

貌似现在改 default 为3.13.1了，想运行它，改图中的 version.txt 文件内容：default 为 3.13.1

**Comment by waylenz** [comment]
问题解决了。
原来，下载的.z文件 **要解压覆盖原来的整个XX-net目录**才行，而不是在code目录中解压。如下图，压缩文件里面有个XX-Net-3.13.1文件夹，该文件夹的内容覆盖原来的XX-net目录内容，我的是D:\XX-Net-3.3.6。
![image](https://user-images.githubusercontent.com/19546561/50535132-9fba8a80-0b81-11e9-9377-c3a439ffc4d8.png)
感谢@AnyWAT的回答，虽然可能没有理解我的问题（我的问题是解压路径不对）

**Comment by AnyWAT** [comment]
> 我的问题是解压路径不对

从这里开始。。。解压到 code ——已用若干次了
![default](https://user-images.githubusercontent.com/37962734/50535306-bfeb4900-0b83-11e9-882b-09c254ac63a3.png)

**Comment by AnyWAT** [comment]
> 



> **要解压覆盖原来的整个XX-net目录**才行

也没错，全部文件更新，楼上有部分没有更新。2种做法，最后3.13.1（任何新解压版本）都在 code\default 下

**Comment by AnyWAT** [comment]
> 
> 
> > > 关键是是下载的 .z文件怎么处理呢？ 我把它解压到code目录中，不识别
> > 
> > 
> > 手动解压的结果，貌似不是3.13.1 而是 default
> 
> 貌似现在改文件夹 default 为3.13.1了，想运行它，改图中的 version.txt 文件内容：default 为 3.13.1

有错么，完全没有
