### ISSUE TITLE
重要：Win10近来Teredo 隧道用服务器 IP地址远远稳定于用域名。期待大家验证

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#11920]
- 软硬件及 ISP无变化，32Win10Pro 采用的系统默认服务器 [win1807.ipv6.microsoft.com. ](https://github.com/XX-net/XX-Net/issues/11423#issuecomment-418618922)可以说之前一直正常（在操作系统1809某个版本以前一直是  win1711.ipv6.microsoft.com. ），偶尔也换其它耍下。
- 貌似连续2天22时代理出问题的前一两天里，原来用得很正常的XX-Net 代理偶然会断掉且难以恢复，发现是隧道出了问题，用 netsh int ipv6 set teredo enterpriseclient default 也很难连接，再用 netsh int ipv6 set teredo enterpriseclient 157.56.149.60 却立马连接，XX-Net 也就正常了，并在某贴里说了此事（不是后面链接的那贴，应在此之前）。[随后一直用此 IP 服务器](https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449648369)，XX-Net 也一直正常。22时事件发生后，3.13.1版使用中才有后话：即使 DEAD Time 那几天，貌似隧道服务器一直正常。
- 昨晚到今天的多次测试，即使用域名可以连接隧道系统默认服务器，并可以一直[合格（已连接）](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel)——很奇怪，但XX-Net 却不正常，即使正常很快就：有效 IP数或连接池归零，[IPv6 状态Fail (尝试修复)](http://127.0.0.1:8085/?module=gae_proxy&menu=status)。貌似可以证实：Teredo 隧道用服务器 IP地址的远远稳定于用域名。（🤣提醒：1、完全没有要求大家都用 157.56.149.60 的意思，也许对你刚好就不合适！2、Win10系统默认服务器Ping 虽超时但或许更稳定，Ping值小的不一定能连接、也未必就好。。。）
- 操作方法：

https://github.com/XX-net/XX-Net/issues/11892#issue-394057094 二、操作：5、如隧道合格但。。。
或 https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204

**Comment by HUChengdu** [comment]
Working for me.THANKS!

**Comment by ARCHOTZ** [comment]
WINDOWS默认IPV6服务器IP ping过会出有下面这些。
157.56.149.60
157.56.144.215
157.56.106.184
65.55.158.118
157.56.106.189
94.245.121.251

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11922#issuecomment-450345399 AnyWAT ，你这人是什么情况。明明用不了，还净折腾。主要是表达的内容根本看不懂，就如同英文用ｇｏｏｇｌｅ翻译出来一样。 #11922

**Comment by AnyWAT** [comment]
> 请问 如何切换到 自己想要的隧道呢?

@Peterpey 顶楼第一行链接

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11958#issuecomment-450705403 你的网络属于以下哪类？看看隧道用服务器 IP地址远远稳定于用域名所适应的网络类型。谢谢！

**Comment by AnyWAT** [comment]
### 再次忠告：不只看 ping 得通与否、快与慢，能连接且 IPv6 状态 OK 才是真正的好。https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450720125
![image](https://user-images.githubusercontent.com/37962734/50572063-638e6080-0df3-11e9-8446-e5b723da534c.png)

**Comment by AnyWAT** [comment]
安卓用户有人回应：https://github.com/XndroidDev/Xndroid/issues/193#issuecomment-450711257

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11967
![image](https://user-images.githubusercontent.com/37962734/50589554-19c07b80-0ec2-11e9-9880-399604ad7bee.png)

安卓用户有人回应：https://github.com/XndroidDev/Xndroid/issues/193#issuecomment-450711257

**Comment by AnyWAT** [comment]
通过几天观察，Teredo 隧道用服务器 IP地址远远稳定于用域名只是表象，实质是巨硬服务器域名所对应的 IP时常变化，各 IP状态几乎一直稳定，才有用 IP的GAE几乎一直正常；用域名的偶尔中断后却能自动恢复，除非域名指向了某状态不佳的 IP，如 win1711.ipv6.microsoft.com. 40.81.250.180，此时隧道虽能连接，但 IPv6 状态始终 Fail 无法 OK。

**Comment by sudemo** [comment]
this one works . u are definitely not a robot
