### ISSUE TITLE
按照步骤设置好所有id 仍然无法观看视频 显示使用的是公用appid

### ISSUE THREAD

**Issue by yhfang** [XX-net/XX-Net#1194]
GAEProxy状态信息

系统版本

Property	Value
XX-Net Version	2.5.1
Python Version	2.7.6
Sys Platform	x86_64, Darwin-14.4.0-x86_64-i386-64bit
OS System	Darwin
OS version	Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64
OS release	14.4.0
OS detail	Release:10.10.4; Version:('', '', '') Machine:x86_64
language	zh_CN
architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	462
100th IP handshake(ms)	751
connected link(帮助)	0,0
scaning ip thread num	0
block stat(帮助)	OK
Appid

Property	Value
working appids	＊＊＊＊
Out of Quota appids	
Not Exist appids	

而日志一直显示
Oct 11 00:03:21 - [DEBUG]LOG_EXCEPT: GAEProxy web_control 127.0.0.1:55656 POST /config?cmd=set_config , Except:[Errno 5] Input/output error

**Comment by panzer1313208** [comment]
你自己部署自己的IP啊，公共IP本来就不能看youtube。

**Comment by simonasd** [comment]
公共APPID出于流量考虑，不允许看视频。但从你贴出的状态信息看，你使用的是个人ID。你说的“显示使用的是公用appid”是什么地方“显示”的？

（顺便说一下，出于隐私和安全考虑，请不要在公开场合写出自己的APPID，你可以用“个人appid”之类的字样替换掉）

另外，状态信息中“connected link(帮助) 0,0”说明你现在还没有和服务器建立连接。你现在能访问google或是facebook吗？如果不能，那么你可能需要删掉data目录下的good_ip.txt，然后开着XX-Net扫描IP一段时间。

**Comment by yhfang** [comment]
谢谢提醒。我无法登入youtube 也无法看别的网站的在线视频 YouTube显示的是
Hosts Deny('www.youtube.com')
共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问，请使用自己的appid 帮助

还有 我也注意到connected link为0，0 但是上Facebook都是可以的 不知道为什么

**Comment by simonasd** [comment]
@yhfang 真是奇怪，我现在也没什么头绪。要不你做个试验，退出XX-Net，打开GAE_proxy/local目录，编辑proxy.ini，把你的appid和密码等信息替换进去，然后再试？

怀疑是不是程序有什么bug，但得有时间读完代码，才能思考这个层次的问题了。

**Comment by xxnet** [comment]
你的现象似乎有两套系统在工作？
  看看日志，当你访问youtube的时候，GAE日志里有没有访问的记录？

在 2015年10月11日 下午4:00，simonasd <notifications@github.com>写道：

**Comment by yhfang** [comment]
@xxnet  @simonasd 我发现可能存在两套系统的问题 因为我同时下过2.5.0和2.5.1两个版本。我曾经先后使用过两版。现在我正在使用2.5.1 想把2.5.0删除时 发现2.5.0处于使用中。这是怎么回事。会不会我无法登入视频网站是因为我实际使用的是2.5.0版本？还有 如何可以完全退出旧版并卸载？

**Comment by yhfang** [comment]
@xxnet @simonasd 谢谢。我解决了 长期mac不关机导致软件滞留在系统 重启后解决。
