### ISSUE TITLE
彻底挂了

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#11958]
还有几个人能用的？ 举个手我看看

**Comment by AnyWAT** [comment]
经测试，https://github.com/XX-net/XX-Net/issues/11920#issuecomment-450306007 鄙人除了 65.55.158.118，其它5个 IP均可正常使用：
94.245.121.251 OK
157.56.106.184 OK
157.56.106.189 OK
157.56.144.215 OK
157.56.149.60   OK

**Comment by xugaohui** [comment]
免费的VPN Gate 很多.速度十分快,优拨土都是上万bps的速度.
搞这些东西浪费时间,网速也不行.不支持代理的软件也不好用.

**Comment by AnyWAT** [comment]
谢谢 https://github.com/XX-net/XX-Net/issues/11930 楼主  @leoxxnet，第一个。。。

**Comment by xdg92** [comment]
AnyWaT,不ping域名，直接命令提示行设置IPV6服务器IP可以吗？

**Comment by aoteman44** [comment]
我目前使用正常，我是这么做的：

在“全局设置”选项卡里-提交设置级别“极端”
然后去“IPv6 隧道”选项卡，点测试teredo，用管理员运行

netsh interface teredo set state server= x.x.x（上面测试得出的地址）

应该会有所改观。

**Comment by imudie123** [comment]
花点钱弄个VPS装SS，是比较稳妥的方法，其他都是辅助。

**Comment by Hanmeim** [comment]
emmmm我用的很稳啊，一百多可用ip，延迟基本500以下。。。
