### ISSUE TITLE
最近这些状况应该是GFW的问题

### ISSUE THREAD

**Issue by xyzde1988** [XX-net/XX-Net#11954]
我几天也是用IPV6连上一会儿就断了。AnyWAT发的那些方法，我看不懂，所以就没用他的方法做。
只是按照他说的用IP代替域名建立Teredo隧道，但是依然没有用。

我就用X-Tunnel过度，X-Tunnel也是一会儿好一会儿坏。而且我发现我上github也是有时能上有时上不了，就连steam也是这样。

然后就是今天，今天突然就IPV6能稳定连上了，X-Tunnel也非常稳定。一切都正常了。

有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 307
连接池(帮助) | 新:0 h1:0 h2:21

因为我这两天没有做任何设置上的更改，所以应该就是GFW的问题了。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11892 附：3、X-Tunnel 正常的前提：。。。
https://github.com/XX-net/XX-Net/issues/11920 【（并不保证你也正常的）傻瓜步骤：https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 】

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11922#issuecomment-450384702 已发现巨硬有变：。。。

**Comment by kwwgh** [comment]
我也是什么设置都没变，前几天断断续续，连接上也只能好几分钟，然后就掉没了。但今天一上午很稳定，IP虽然不多，但是连接稳定有20个，速度也挺快的。

**Comment by whogiawho** [comment]
今天蛮好用的。。。。 莫非的确和gfw有关？

**Comment by whogiawho** [comment]
今天蛮好用的。。。。 莫非的确和gfw有关？
