### ISSUE TITLE
lib里的google appengine库太老了吧，还是07年的

### ISSUE THREAD

**Issue by cainiaowu** [XX-net/XX-Net#1195]
google把performance里的instance_class改到app.yaml里去调了。

我想改F2还得重新手动传app.yaml。

**Comment by Sherman-Liu** [comment]
大部分人貌似没有调节这个的需求吧。

**Comment by simonasd** [comment]
不过如果能更新一下肯定没坏处

**Comment by xxnet** [comment]
看过新版的库，大了很多，所以如果没有出现非常的必要，就先不升级。

2015-10-11 12:46 GMT+08:00 simonasd <notifications@github.com>:

**Comment by cainiaowu** [comment]
唉，SDK升级了，老版本不再支持了。这回躲不了了。

**Comment by xxnet** [comment]
​ 搞定了， 2.9.4发布，采用新版的SDK部署，大家试试
