### ISSUE TITLE
攒了几十个ip，瞬间见光死

### ISSUE THREAD

**Issue by wangshantao** [XX-net/XX-Net#11969]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
y
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
y
* 是否以相关关键词搜索过类似 issues？
y
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
注意右下角时间
访问谷歌瞬间，ip全死，就能打开个谷歌首页。
![_20190103095807](https://user-images.githubusercontent.com/14883268/50621189-44044e80-0f3f-11e9-9594-101ebf38d841.png)
![_20190103095933](https://user-images.githubusercontent.com/14883268/50621192-4666a880-0f3f-11e9-8ced-065129225c20.png)
注：anyWay别无脑回复改Teredo隧道地址，我已经改过了。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11967 曾经与你持同样态度的。。。
![image](https://user-images.githubusercontent.com/37962734/50589554-19c07b80-0ec2-11e9-9880-399604ad7bee.png)
