### ISSUE TITLE
360 说是拦截了木马，有影响吗

### ISSUE THREAD

**Issue by new-xd** [XX-net/XX-Net#1197]
下面是360的拦截日志
时间	操作	说明	次数
  2015-10-11 10:41:10	  [已清除]	  发现木马：广告推广程序	  防护 1 次
详细描述：
木马名称：广告推广程序
所在路径：E:\software\XX-Net-2.5.1\python27\1.0\lib\win32\OpenSSL\crypto.pyd

**Comment by Sherman-Liu** [comment]
如果软件是直接从这里获取的Release，应该没有问题。

基本常识：不要在使用翻墙软件的电脑上安装国内管家或杀毒软件类应用，除非你想被请去喝茶。

**Comment by simonasd** [comment]
在[issue 714](714)中有类似的情况，同样也是360提示openssl库中的文件有问题。X大，给出了解释，网友也提供了检验文件是否被篡改过的方法。

当然很重要的一点是，不要使用以360为代表的国产安全软件。我想这应该是墙外网友的共识。

**Comment by xxnet** [comment]
这个文件是DLL格式，存在被病毒感染的可能。

XX-Net的这个文件是从python官网下载来的，可以对比MD5.
按道理360不会去把python官网下载的文件进行报毒，这点需要确认，
请在360报病毒的时候，计算这个文件的MD5和长度报上来。



在 2015年10月11日 下午12:50，simonasd <notifications@github.com>写道：

**Comment by new-xd** [comment]
后来我想对比这个文件的时候，发现360已经删干净了， 下次再看看吧。
目前用之前的文件，运行良好，没有问题。
