### ISSUE TITLE
求救！MacPro IPV6 不可用

### ISSUE THREAD

**Issue by HannaX** [XX-net/XX-Net#11994]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by HannaX** [comment]
如题，请教各位大大，虽然看过很多教程但大部分是基于windows系统的，且本人小白很多处理都一知半解，虚心求教，请大家帮忙看看怎么该怎么操作，感谢！

XX-Net Status:

sys-platform: x86_64, Darwin-18.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
os-release: 18.2.0
os-detail: Release:10.14.2; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:77
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 566
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by HannaX** [comment]
<img width="668" alt="wx20190106-115616 2x" src="https://user-images.githubusercontent.com/35716485/50731907-30a8eb80-11aa-11e9-85c1-400894287087.png">
<img width="1440" alt="wx20190106-115756 2x" src="https://user-images.githubusercontent.com/35716485/50731918-533b0480-11aa-11e9-9436-32838b6361c9.png">
附上截图，如图显示miredo是绿灯，但IPV6就是连不上……

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11992#issuecomment-451713325 试试：改域名为 IP
参照？👉https://github.com/XX-net/XX-Net/issues/11976#issuecomment-451345386

**Comment by HannaX** [comment]
@AnyWAT 改用IP有用，感谢！！！
<img width="668" alt="wx20190106-151456 2x" src="https://user-images.githubusercontent.com/35716485/50733290-fcdbbf00-11c5-11e9-9eb5-61e386f8179b.png">
<img width="910" alt="wx20190106-151520 2x" src="https://user-images.githubusercontent.com/35716485/50733294-036a3680-11c6-11e9-974b-c0fe75cb6764.png">

**Comment by archlinux2020** [comment]
请教下，你的miredo是怎么安上的，我的10.15.5安装不了miredo
