### ISSUE TITLE
确实恢复了，，，

### ISSUE THREAD

**Issue by 2378** [XX-net/XX-Net#11992]
公司电信专线，不清楚家用网络怎么样了。

![default](https://user-images.githubusercontent.com/24506320/50730954-f2083680-1193-11e9-8eb4-3406182b1147.PNG)

**Comment by AnyWAT** [comment]
> 公司电信专线，不清楚家用网络怎么样了。

移动家用一直正常呢

**Comment by Hunerk** [comment]
> > 公司电信专线，不清楚家用网络怎么样了。
> 
> 移动家用一直正常呢

电信家用一直挂的，

**Comment by quegfeng** [comment]
嗯嗯，确实貌似好像可以啦

**Comment by AnyWAT** [comment]
> 嗯嗯，确实貌似好像可以啦

原因或许在此：https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204
![image](https://user-images.githubusercontent.com/37962734/50731914-45857f00-11aa-11e9-891a-b1ef12df417a.png)

**Comment by cypcym** [comment]
貌视真的恢复了，最近一直挺好

**Comment by cupbk** [comment]
前些天突然能用，然后过了一天又不能用了。电信用户。
我一已经放弃折腾，准备花钱弄vps+ss

**Comment by FergonXie** [comment]
其实有 了xx-net这个工具，就不需要太多的折腾，毕竟有难题出现，作者都会很快更新。 
现在的问题，就要体现在 teredo 服务器的设定上， 点击更换 teredo 服务器再稍作等候，一般都会正常。

**Comment by 80068** [comment]
@FergonXie 
对，前几天这种手法确实可以正常，但现在却又不管用了。不知道是怎么回事。

**Comment by AnyWAT** [comment]
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043
