### ISSUE TITLE
macbook15.4自从更新到10.11EI captain 之后就没成功过

### ISSUE THREAD

**Issue by lele2010lele** [XX-net/XX-Net#1200]
系统版本

Property	Value
XX-Net Version	2.5.1
Python Version	2.7.10
Sys Platform	x86_64, Darwin-15.0.0-x86_64-i386-64bit
OS System	Darwin
OS version	Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64
OS release	15.0.0
OS detail	Release:10.11; Version:('', '', '') Machine:x86_64
language	zh_CN
architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	2918
100th IP handshake(ms)	100
connected link(帮助)	1,1
scaning ip thread num	0
block stat(帮助)	OK
<img width="949" alt="2015-10-11 1 57 24" src="https://cloud.githubusercontent.com/assets/10057760/10415168/19632a14-7020-11e5-9bed-12c0e6f7a945.png">

<img width="831" alt="2015-10-11 2 01 41" src="https://cloud.githubusercontent.com/assets/10057760/10415175/9ec54bf6-7020-11e5-81f7-5f4019bd7c31.png">

**Comment by xxnet** [comment]
试试把 data/gae_proxy/good_ip.txt 文件清空重新扫描
或者下载  2.5.3 版本重新启动扫描ip

2015-10-11 14:37 GMT+08:00 lele2010lele <notifications@github.com>:

**Comment by Marco11Nie** [comment]
我在用最新版，没问题

**Comment by lele2010lele** [comment]
怎么办啊@xxnet 
<img width="646" alt="2015-10-14 11 09 35" src="https://cloud.githubusercontent.com/assets/10057760/10474000/3afc769e-7264-11e5-9c04-a8230d42574a.png">

**Comment by xxnet** [comment]
发了2.5.4 版本，请测试

2015-10-14 11:11 GMT+08:00 lele2010lele <notifications@github.com>:

**Comment by lele2010lele** [comment]
@xxnet 还是不行


roperty	Value
XX-Net Version	2.5.4
Python Version	2.7.10
Sys Platform	x86_64, Darwin-15.0.0-x86_64-i386-64bit
OS System	Darwin
OS version	Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64
OS release	15.0.0
OS detail	Release:10.11; Version:('', '', '') Machine:x86_64
language	zh_CN
architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	0
100th IP handshake(ms)	-1
connected link(帮助)	0,0
scaning ip thread num	50
block stat(帮助)	OK

**Comment by lele2010lele** [comment]
是我的网络原因嘛？

**Comment by xxnet** [comment]
相同网络下，Windows或Linux能工作吗？

2015-10-15 16:34 GMT+08:00 lele2010lele <notifications@github.com>:

**Comment by lele2010lele** [comment]
我只有mac。。

**Comment by lele2010lele** [comment]
@xxnet win10在相同网络下依然如此

**Comment by xxnet** [comment]
会不会是你的网络问题？
  哪个地区？什么运营商？

2015-10-16 12:16 GMT+08:00 lele2010lele <notifications@github.com>:

**Comment by lele2010lele** [comment]
@xxnet 山东联通

**Comment by xxnet** [comment]
如果有机会，试试别的网络好不好，比如电信或者移动

2015-10-16 16:50 GMT+08:00 lele2010lele <notifications@github.com>:
