### ISSUE TITLE
迹象显示XX-net必须尽快换策略

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#12000]
其实折腾本来就挺麻烦的，今天又把XX-net打开了，发现又没法用了。
然后就按照上次能用的途径再折腾一次，结果根本就没用。还是不能用。
为什么上次的方法这次就不行了呢，按分析是，联通电信完全知晓你的XX-net
他高兴的时候就给你打开让你用用，不高兴的时候就给你关上。
完全主动权都在人家那里。

因为XX-net的技术比较复杂，但是对用户来说也是相对较为安全的。最后就是希望XX-net更新版本，逐渐改变软件的技术。不要停留在一种模式。那样就太容易被模仿。

**Comment by 80068** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:2 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by 2378** [comment]
抱怨的对象 不该是电信联通，而是“墙”

再说，哪有完全不暴露的流量，各种混淆伪装而已

**Comment by 80068** [comment]
实际上人家都是一家，只是名字不同，你想想。名字都是自己起的而已。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需IP地址的2行）

**Comment by 80068** [comment]
@AnyWAT  应该是这个
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by 80068** [comment]
"仅 IPv6" 不可用，请检查。
状态
属性	值
IPv4 状态	OK
IPv6 状态(如何开启)	Fail (尝试修复)
有效 IPv4 IP 数	0
有效 IPv6 IP 数	2
总 IP 数	100
XX-Net 状态	空闲
IP 延迟	881
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	OK
CA 证书状态(下载)	OK
IP 扫描线程数(设置)	100

**Comment by 80068** [comment]
天津联通 现在又开始限制XX-net了

**Comment by AnyWAT** [comment]
试试：管理权限 cmd 内运行 netsh int ipv6 set teredo enterpriseclient 157.56.149.60

**Comment by AnyWAT** [comment]
gws-ip-num: total:2 ipv4:0 ipv6:0 ——总 IP数不是设置的2吧？

**Comment by 80068** [comment]
@AnyWAT 真是雪中送炭，跪地感谢！暂时能用了。XX-Net。太好了，让人感动！

**Comment by 80068** [comment]
@AnyWAT 刚能用10分钟，又坏了，又用不了了。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204 命令提示符窗口更换 Teredo 隧道、批处理直接观察其即时状况

**Comment by AnyWAT** [comment]
> 刚能用10分钟，又坏了，又用不了了。

貌似没关闭“自动调整扫描线程数”开关？

**Comment by panghu1986** [comment]
深圳电信好像没啥问题啊。

AnyWAT <notifications@github.com> 於 2019年1月7日 週一 上午4:02寫道：

**Comment by 80068** [comment]
点仅测试teredo服务器，弹出这些：
teredor test result is unknown. and the best server is win1711.ipv6.microsoft.com.
更换teredo服务器，弹出这些：
Set teredo server is completed.

**Comment by AnyWAT** [comment]
来点逻辑，能给出答案后才继续：

> os-release: 8.1 的系统默认服务器是。。。【（并不保证你也正常的）傻瓜步骤：[#11930 (comment)](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507) 】

结果是。。。

**Comment by 80068** [comment]
@@AnyWAT 
Teredo 隧道 | 离线（无法连接）

**Comment by AnyWAT** [comment]
无语了。😱就是神叨叨，貌似也无逻辑，哪怕已被指引，仍无逻辑。。。

**Comment by StellaMeow** [comment]
> @AnyWAT 点仅测试teredo服务器，弹出这些：
> teredor test result is unknown. and the best server is win1711.ipv6.microsoft.com.
> 更换teredo服务器，弹出这些：
> Set teredo server is completed.

我也是这样

**Comment by AnyWAT** [comment]
仅测试teredo服务器貌似已不能适应当前状况，尤其是它给出 the best server is win1711.ipv6.microsoft.com. 但此时 IP被指向 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）的时候

【（并不保证你也正常的）傻瓜步骤：https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 】👍

**Comment by AnyWAT** [comment]
> 我也是这样 @80068

https://github.com/XX-net/XX-Net/issues/11930#issuecomment-452951890

**Comment by SkyYkb** [comment]
油·管·视频ID：KRQTXbvo6zI

**Comment by loy20002000** [comment]
这里还在收听的朋友可以核实一下，注意不要在排名靠前几页的帖子回复或是开新帖。


------------------

如果我说的是错的，请XX-NET账号使用者证明你就是XX本人。

在这里通报一个观察，不一定准确。

XX-NET项目可能以后再也不会更新了，就算更新也不要再使用了。我已经删除了所有XX的工具，包括手机版和PC版。因为XX-NET项目可能已经被中共接管了。理由如下：

1.最近我的帖子频繁被删除，哪怕是跟政治不沾边的也会被删。我谈论Google的安全性，日本网络的安全性，美国网络的监听，关中国政治什么事儿？
2.XX-NET几乎24小时在线，可以查看我的删帖时间记录。
3.老的讨论贴XX-NET通常会参与一些讨论，但上次更新到现在他参与过任何讨论么？
4.这种事情已经有先例。大家可以搜索[高铁 忘情]，这哥们的新浪blog就是被政府接管。他亲口确认。另外ss项目的删除也可以说明一些问题。
