### ISSUE TITLE
求助：有效IP过少

### ISSUE THREAD

**Issue by Mark486** [XX-net/XX-Net#12013]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:431 ipv4:0 ipv6:13
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:3
scan-ip-thread-num: 100
ip-quality: 1928
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false

![360 20190107225724617](https://user-images.githubusercontent.com/21996475/50774915-b8d4e100-12cf-11e9-8576-6a2a00fac7d4.jpg)

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需IP地址的2行）

**Comment by Mark486** [comment]
![360 20190107235741372](https://user-images.githubusercontent.com/21996475/50778194-4ae0e780-12d8-11e9-8e6a-754e8e619078.jpg)

**Comment by Mark486** [comment]
@AnyWAT 上面贴图有问题吗？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。【（并不保证你也正常的）傻瓜步骤：https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 】

**Comment by AnyWAT** [comment]
> 上面贴图有问题吗？

文本复制粘贴即可
