### ISSUE TITLE
本人电信网络，Teredo 隧道显示	合格（已连接），但是ipv6状态 fail，求帮助！！

### ISSUE THREAD

**Issue by HotView** [XX-net/XX-Net#12016]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。【（并不保证你也正常的）傻瓜步骤：https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 】

**Comment by HotView** [comment]
> 最近xxnet不稳定 可以试试ssr 这里送5GB流量 https://renzhecloud.com/auth/register?code=pAKT

怎么使用啊，没有连外网，教程打不开

**Comment by AnyWAT** [comment]
SSR 的同类 https://github.com/shadowsocks/shadowsocks-windows

**Comment by HotView** [comment]
> > 怎么使用啊，没有连外网，教程打不开
> 
> 😂俗称的机场主推销。。。

不懂...... 可否详细解释一下，刚翻墙的小白

**Comment by HotView** [comment]
> * 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
> * 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
> * 是否以相关关键词搜索过类似 issues？
> * 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
> * 如果问题得到解决，请务必回复相关情况，谢谢。

直连光猫原生ipv6速度起飞，换回teredo隧道各种掉ip。
经过对比初步判断目前限制连接稳定性的就是teredo隧道服务器这一步了。

建议稍微动动手，自己把几个服务器依次ping过去，不要依赖自动选择脚本。
比如我这边win10.ipv6.microsoft.com虽然能正确解析但是ping丢包率超过90%，这种情况下当然会掉ip。
换teredo.remlab.net测一下丢包率大约5%，延迟也还可以，可以把有效ip稳定在20多个。
teredo.iks-jena.de略逊，但是也不是不能用。
至于teredo.trex.fi，丢包率100%。

最后再次建议，家里运营商有原生ipv6的，请直连光猫，比换服务器好用多了。
愿意折腾的还可以试着让路由器支持IPv6。
这个回答相对比较适合我的问题

**Comment by AnyWAT** [comment]
> 自己把几个服务器依次ping过去

![image](https://user-images.githubusercontent.com/37962734/50816540-dbacd700-135b-11e9-8526-ea7f609b6226.png)

**Comment by HotView** [comment]
> > 自己把几个服务器依次ping过去
> 
> ![image](https://user-images.githubusercontent.com/37962734/50816540-dbacd700-135b-11e9-8526-ea7f609b6226.png)

能否问下什么是机场主推销么

**Comment by AnyWAT** [comment]
稀奇：XX-NET“测试teredo”认为win10.ipv6.microsoft.com最佳，其实ping不通 #11937

**Comment by HotView** [comment]
> 稀奇：XX-NET“测试teredo”认为win10.ipv6.microsoft.com最佳，其实ping不通 #11937

能否解释一下什么是白嫖机场，和机场主推销么？不方便可以私聊。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/50817080-a7d2b100-135d-11e9-9e2e-362c22d3574c.png)
