### ISSUE TITLE
电信原生ipv6  但是无法连接？

### ISSUE THREAD

**Issue by huohu4399** [XX-net/XX-Net#12014]
1 你的公网 IPv4 地址是 117.63.155.42
2 你的公网 IPv6 地址是 240e:ec:869a:f00:4a:232:f81f:cd9e
3 你的运营商（ISP）是 CHINANET-BACKBONE No.31,Jin-rong Street
4 在你所在的地区，本站的测试结果并不可靠。
5 通过 DNS 能够正常连接 IPv6，但指明 IP 地址的 URL 无法正常连接，虽然现在鲜有这种连接方式。
本站现已支持 HTTPS。 [更多信息]

你的 DNS 服务器（可能由运营商提供）没有接入或没有配置 IPv6，将来这可能会妨碍你访问纯 IPv6 网站。 [更多信息]

糟糕！IPv6 基本正常，但较大的数据包传输失败，这可能导致部分网站显示不全。询问你的运营商是不是 MTU 的问题，这可能与你的隧道有关。 检查你的防火墙，确保已放行 ICMPv6 消息（尤其是第 2 类，“数据包过大”）。 [更多信息]

1/10

实际使用XX的时候  就是一会儿现实已连接  一会儿又提示未连接   好不容易打电话给电信  弄到ipv6  没法用  快无语了

求大佬帮下  应该怎么设置

**Comment by AnyWAT** [comment]
有原生 IPv6的样子：https://github.com/XX-net/XX-Net/issues/11996#issuecomment-451727419
