### ISSUE TITLE
前几天用的好好地，怎么最近开始就ipv6 fail

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#12023]
best server is: win1711.ipv6.microsoft.com.

C:\WINDOWS\system32>sc config RpcEptMapper start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start RpcEptMapper 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config DcomLaunch start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start DcomLaunch 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config RpcSs start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start RpcSs 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config nsi start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start nsi 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config Winmgmt start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start Winmgmt 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config Dhcp start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start Dhcp 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config WinHttpAutoProxySvc start= auto 
[SC] OpenService 失败 5:

拒绝访问。

C:\WINDOWS\system32>sc start WinHttpAutoProxySvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>sc config iphlpsvc start= auto 
[SC] ChangeServiceConfig 成功

C:\WINDOWS\system32>sc start iphlpsvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。

C:\WINDOWS\system32>goto :eof 

C:\WINDOWS\system32>netsh interface ipv6 reset 
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

C:\WINDOWS\system32>ipconfig /flushdns 

Windows IP 配置

已成功刷新 DNS 解析缓存。

C:\WINDOWS\system32>netsh interface teredo set state type=enterpriseclient servername=win1711.ipv6.microsoft.com. 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy ::1/128 50 0 
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::1/128 50 0 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy ::/0 40 1 
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::/0 40 1 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy 2002::/16 30 2 
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy 2002::/16 30 2 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy 2001::/32 25 5 
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy 2001::/32 25 5 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy ::/96 20 3 
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::/96 20 3 
确定。

C:\WINDOWS\system32>netsh interface ipv6 add prefixpolicy ::ffff:0:0/96 10 4 
对象已存在。

C:\WINDOWS\system32>netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 10 4 
确定。

C:\WINDOWS\system32>Reg add HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f 
操作成功完成。 

C:\WINDOWS\system32>Reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters /v DisabledComponents /t REG_DWORD /d 0 /f 
操作成功完成。 

C:\WINDOWS\system32>goto :eof 

C:\WINDOWS\system32>ipconfig /all 

Windows IP 配置

主机名 . . . . . . . . . . . . . : FR9ALJCFH5WPCPM
主 DNS 后缀 . . . . . . . . . . . : 
节点类型 . . . . . . . . . . . . : 混合
IP 路由已启用 . . . . . . . . . . : 否
WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
物理地址. . . . . . . . . . . . . : 00-E0-4C-68-08-19
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是
本地链接 IPv6 地址. . . . . . . . : fe80::39b0:f357:15fb:1548%17(首选) 
IPv4 地址 . . . . . . . . . . . . : 192.168.2.105(首选) 
子网掩码 . . . . . . . . . . . . : 255.255.255.0
获得租约的时间 . . . . . . . . . : 2019年1月8日 23:06:04
租约过期的时间 . . . . . . . . . : 2155年2月15日 5:37:22
默认网关. . . . . . . . . . . . . : 192.168.2.1
DHCP 服务器 . . . . . . . . . . . : 192.168.2.1
DHCPv6 IAID . . . . . . . . . . . : 285270092
DHCPv6 客户端 DUID . . . . . . . : 00-01-00-01-21-66-08-FA-00-E0-4C-68-08-19
DNS 服务器 . . . . . . . . . . . : 192.168.2.1
TCPIP 上的 NetBIOS . . . . . . . : 已启用

以太网适配器 以太网 2:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
物理地址. . . . . . . . . . . . . : 00-FF-B5-7F-AF-C9
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

隧道适配器 Teredo Tunneling Pseudo-Interface:

连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
DHCP 已启用 . . . . . . . . . . . : 否
自动配置已启用. . . . . . . . . . : 是
IPv6 地址 . . . . . . . . . . . . : 2001:0:2877:d4c0:142b:f44a:87ab:f342(首选) 
本地链接 IPv6 地址. . . . . . . . : fe80::142b:f44a:87ab:f342%6(首选) 
默认网关. . . . . . . . . . . . . : ::
DHCPv6 IAID . . . . . . . . . . . : 
DHCPv6 客户端 DUID . . . . . . . : 00-01-00-01-21-66-08-FA-00-E0-4C-68-08-19
TCPIP 上的 NetBIOS . . . . . . . : 已禁用

C:\WINDOWS\system32>netsh interface ipv6 show teredo 
Teredo 参数
---------------------------------------------
类型 : enterpriseclient
服务器名称 : win1711.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : qualified
客户端类型 : teredo client
网络 : unmanaged
NAT : symmetric (port)
NAT 特殊行为 : UPNP: 否，PortPreserving: 否
本地映射 : 192.168.2.105:61670
外部 NAT 映射 : 

C:\WINDOWS\system32>netsh interface ipv6 show route 

发布 类型 跃点数 前缀 索引 网关/接口名称
------- -------- --- ------------------------ --- ------------------------
否 手动 256 ::/0 6 Teredo Tunneling Pseudo-Interface
否 系统 256 ::1/128 1 Loopback Pseudo-Interface 1
否 手动 256 2001::/32 6 Teredo Tunneling Pseudo-Interface
否 系统 256 2001:0:2877:d4c0:142b:f44a:87ab:f342/128 6 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::/64 17 以太网
否 系统 256 fe80::/64 6 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::142b:f44a:87ab:f342/128 6 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::39b0:f357:15fb:1548/128 17 以太网
否 系统 256 ff00::/8 1 Loopback Pseudo-Interface 1
否 系统 256 ff00::/8 17 以太网
否 系统 256 ff00::/8 6 Teredo Tunneling Pseudo-Interface

C:\WINDOWS\system32>netsh interface ipv6 show interface 

Idx Met MTU 状态 名称
--- ---------- ---------- ------------ ---------------------------
1 75 4294967295 connected Loopback Pseudo-Interface 1
6 75 1280 connected Teredo Tunneling Pseudo-Interface
17 35 1500 connected 以太网

C:\WINDOWS\system32>netsh interface ipv6 show prefixpolicies 
查询活动状态...

优先顺序 标签 前缀
---------- ----- --------------------------------
50 0 ::1/128
40 1 ::/0
30 2 2002::/16
25 5 2001::/32
20 3 ::/96
10 4 ::ffff:0:0/96
3 13 fc00::/7
1 12 3ffe::/16
1 11 fec0::/10

C:\WINDOWS\system32>netsh interface ipv6 show address 

接口 1: Loopback Pseudo-Interface 1

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite ::1

接口 6: Teredo Tunneling Pseudo-Interface

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
公用 首选项 infinite infinite 2001:0:2877:d4c0:142b:f44a:87ab:f342
其他 首选项 infinite infinite fe80::142b:f44a:87ab:f342%6

接口 17: 以太网

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite fe80::39b0:f357:15fb:1548%17

C:\WINDOWS\system32>route print 
===========================================================================
接口列表
17...00 e0 4c 68 08 19 ......Realtek PCIe GBE Family Controller
9...00 ff b5 7f af c9 ......TAP-Windows Adapter V9
1...........................Software Loopback Interface 1
6...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标 网络掩码 网关 接口 跃点数
0.0.0.0 0.0.0.0 192.168.2.1 192.168.2.105 35
127.0.0.0 255.0.0.0 在链路上 127.0.0.1 331
127.0.0.1 255.255.255.255 在链路上 127.0.0.1 331
127.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
192.168.2.0 255.255.255.0 在链路上 192.168.2.105 291
192.168.2.105 255.255.255.255 在链路上 192.168.2.105 291
192.168.2.255 255.255.255.255 在链路上 192.168.2.105 291
224.0.0.0 240.0.0.0 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 192.168.2.105 291
255.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
255.255.255.255 255.255.255.255 在链路上 192.168.2.105 291
===========================================================================
永久路由:
无

IPv6 路由表
===========================================================================
活动路由:
接口跃点数网络目标 网关
6 331 ::/0 在链路上
1 331 ::1/128 在链路上
6 331 2001::/32 在链路上
6 331 2001:0:2877:d4c0:142b:f44a:87ab:f342/128
在链路上
17 291 fe80::/64 在链路上
6 331 fe80::/64 在链路上
6 331 fe80::142b:f44a:87ab:f342/128
在链路上
17 291 fe80::39b0:f357:15fb:1548/128
在链路上
1 331 ff00::/8 在链路上
17 291 ff00::/8 在链路上
6 331 ff00::/8 在链路上
===========================================================================
永久路由:
无

**Comment by LN-VIVI** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:143 ipv4:0 ipv6:87
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by LN-VIVI** [comment]
@Anyway

**Comment by LN-VIVI** [comment]
@AnyWAT

**Comment by LN-VIVI** [comment]
@SeaHOH

**Comment by AnyWAT** [comment]
隧道结论：https://github.com/XX-net/XX-Net/issues/11920#issuecomment-452020543

**Comment by AnyWAT** [comment]
> @AnyWAT

https://github.com/XX-net/XX-Net/issues/11892#issuecomment-450047064 你是认真的吗？不会人类思考的机器人？

**Comment by LN-VIVI** [comment]
> > @AnyWAT
> 
> [#11892 (comment)](https://github.com/XX-net/XX-Net/issues/11892#issuecomment-450047064) 你是认真的吗？不会人类逻辑思维的机器人？

我怎么看不懂你在讲什么？
