### ISSUE TITLE
Teredo隧道已打开，但IPv6 状态失败是怎么回事？

### ISSUE THREAD

**Issue by flyin9sky** [XX-net/XX-Net#12027]
netsh interface Teredo show state
Teredo 参数
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

正常 ipconfig  /all显示有隧道适配器 Teredo Tunneling Pseudo-Interface: 且获取了2001开头IPv6 地址
ip helper服务正常

但xxnet的IPv6 状态为 | Fail (尝试修复) 且 test-ipv6.com测试 无域名IPv6连接测试 为超时 (16.677s)
请问这是什么情况？

**Comment by flyin9sky** [comment]
尝试更换Teredo 服务器为ip后IPv6 状态显示为OK，但依然不能正常使用
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> test-ipv6.com测试

多此一举



> 尝试更换Teredo 服务器为ip后IPv6 状态显示为OK，但依然不能正常使用

此刻：win1711.ipv6.microsoft.com. 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）
服务器改用域名为用 IP：https://github.com/XX-net/XX-Net/issues/11835#issuecomment-449646204 命令提示符窗口更换 Teredo 隧道、批处理直接观察其即时状况
隧道结论：https://github.com/XX-net/XX-Net/issues/11920#issuecomment-452020543
速度及稳定性较佳体验之秘籍：https://github.com/XX-net/XX-Net/issues/12000#issuecomment-451764203

**Comment by flyin9sky** [comment]
@AnyWAT 通过ping[https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450730285](url) 提供的ip加[https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507](url)的方法 成功扫描到了可用ipv6 可正常上网了

**Comment by flyin9sky** [comment]
@AnyWAT 通过ping [leoxxnet](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450730285) 提供的ip加 [AnyWAT](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507)  的方法 成功扫描到了可用ipv6 可正常上网了

**Comment by AnyWAT** [comment]
> [leoxxnet](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450730285) 提供的ip

😜始作俑者：WINDOWS默认IPV6服务器IP ping过会出有下面这些。（@ARCHOTZ）https://github.com/XX-net/XX-Net/issues/11920#issuecomment-450306007
