### ISSUE TITLE
teredo隧道用户搜不到足够IP可以点进来看看

### ISSUE THREAD

**Issue by burdenlee** [XX-net/XX-Net#12062]
1.控制面板-网络连接-以太网-（1）去掉microsoft网络适配器的√ （2）IPV6协议打√

2.“XX-Net-master\data\gae_proxy”找到config.json用笔记本方式打开添加："max_good_ip_num":300(经机器人提醒 300前面应该加一个空格)

3.xx-net的gaeproxy全局设置改成积极

4.扫描设置线程改成50 仅IPV6

5.修改tredo隧道的服务器地址为数字形式的地址

6.#12037 根据此贴操作 一定可以了。。

可能只需要其中两三步就能获取足够多的IP数 我也不确定 可以尝试一下 详细的操作方法在xx-net的issues搜索就行      <img src="http://wx4.sinaimg.cn/large/60d5bd8bgy1fz46gxk012j20q20ke0tu.jpg"/>

**Comment by robinlighting** [comment]
有时候也别怪那个机器人@anywat（虽然不知道“他”是不是真的机器人），但是他介绍的方法确实有效，而且我还采用了@yyuurrii34介绍的方法（用 ping -6 ipv6.test-ipv6.com -l 0 -t   保持稳定连通）。
在ISSUES里面有很多方法，可以都去试一下，就是比较折腾。
最理想的情况坐等X神更新。
![01](https://user-images.githubusercontent.com/39740368/51075147-cbca2580-16c2-11e9-804a-2cc99559abdd.jpg)
![02](https://user-images.githubusercontent.com/39740368/51075149-cd93e900-16c2-11e9-8e76-56846d096baf.jpg)

**Comment by treeyiki** [comment]
谢谢啊老哥。。。
我的可用ip数第一次上了三位数，我第一次可以看油管的1080p，之前从没有这么快过。。。
太神奇了

**Comment by treeyiki** [comment]
可是我为什么突然上不了gmail了。。。

**Comment by SaulZane** [comment]
真大哥，亲测可用。我做到前四项瞬间就能使用了。直接有效IPV6数到100了。坐标天津联通。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12043 3、辅以 [Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy) 类[东东](https://github.com/XX-net/XX-Net/issues/11287#issuecomment-415963218)（[初次安装运行](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)，先禁用 Smart Router 模块或退出XX-Net，以释放53端口）的隧道一直分分钟/24小时正常

![image](https://user-images.githubusercontent.com/37962734/51081331-3c575d80-1728-11e9-917f-fe14fe25b1c9.png)
![image](https://user-images.githubusercontent.com/37962734/51081336-5c871c80-1728-11e9-9a00-4b5836faa4b4.png)

**Comment by aeguicai** [comment]
好了啊！谢谢，这机器人的方法竟然可以，是不是微软做的机器人

**Comment by AnyWAT** [comment]
> 好了啊！谢谢，这机器人的方法竟然可以，是不是微软做的机器人

从必须开启 IPv6 隧道一年多以来，每天运行 XX-Net 不少于12小时，一直几乎分分钟/24小时正常的“机器人”

**Comment by giant-ant** [comment]
第二步，添加 "max_good_ip_num":300这一行后，xx-net就启动不了，这是什么情况？

**Comment by AnyWAT** [comment]
> 第二步，添加 "max_good_ip_num":300这一行后，xx-net就启动不了，这是什么情况？

#11291 二楼

**Comment by giant-ant** [comment]
> > 还是【在大括号外】
> 
> 厉害了。贴文件内容，马赛克 AppID
```
{
 "max_scan_ip_thread_num": 50, 
  "GAE_APPIDS": [
  

  ID已删


  ], 

  "auto_adjust_scan_ip_thread_num": 0
  "max_good_ip_num":300
}

```

**Comment by AnyWAT** [comment]
行末添加英文逗号
"auto_adjust_scan_ip_thread_num": 0,

**Comment by giant-ant** [comment]
> 行末添加英文逗号
> "auto_adjust_scan_ip_thread_num": 0,
> 300前添加英文空格
> "max_good_ip_num": 300

原来如此！！可以了。
多谢！

**Comment by burdenlee** [comment]
> 行末添加英文逗号
> "auto_adjust_scan_ip_thread_num": 0,
> 300前添加英文空格
> "max_good_ip_num": 300

呃 我没加空格不知道为什么如一楼的图也是没问题的。。好奇怪

**Comment by giant-ant** [comment]
> 行末添加英文逗号
> "auto_adjust_scan_ip_thread_num": 0,

关键是要在 
行末添加英文逗号
"auto_adjust_scan_ip_thread_num": 0,

**Comment by burdenlee** [comment]
> > 行末添加英文逗号
> > "auto_adjust_scan_ip_thread_num": 0,
> 
> 关键是要在
> 行末添加英文逗号
> "auto_adjust_scan_ip_thread_num": 0,

这个我倒发现了 但机器人回答比我快 因为我这句代码扔在倒数第二行 所以不需要逗号。。

**Comment by AnyWAT** [comment]
> 呃 我没加空格不知道为什么如一楼的图也是没问题的。。好奇怪

遵循软件自生成文件格式。。。

**Comment by AnyWAT** [comment]
> 这个我倒发现了 但机器人回答比我快 因为我这句代码扔在倒数第二行 所以不需要逗号。。

https://github.com/XX-net/XX-Net/issues/11291 或
添加下面内容在大括号内中括号之外的最后一行文本之后，作为新的最后一行，原最后一行末得加英文逗号
"max_good_ip_num": xxx

**Comment by burdenlee** [comment]
> > 这个我倒发现了 但机器人回答比我快 因为我这句代码扔在倒数第二行 所以不需要逗号。。
> 
> #11291 或
> 添加下面内容在大括号内中括号之外的最后一行文本之后，作为新的最后一行，原最后一行末得加英文逗号
> "max_good_ip_num": xxx

我想再问下为什么youtube facebook twitter都正常 就gmail的网站一直加载打不开

**Comment by AnyWAT** [comment]
@giant-ant https://github.com/XX-net/XX-Net/issues/12043#issuecomment-453380394 隐私！！！

**Comment by AnyWAT** [comment]
> 我想再问下为什么youtube facebook twitter都正常 就gmail的网站一直加载打不开

600 等许多报错源自代理速度不佳 
![image](https://user-images.githubusercontent.com/37962734/51084459-e05efa00-1764-11e9-9b5e-c6fa5f9380cd.png)

**Comment by Kashgar-Castle** [comment]
> 1.控制面板-网络连接-以太网-（1）去掉microsoft网络适配器的√ （2）IPV6协议打√
> 
> 2.“XX-Net-master\data\gae_proxy”找到config.json用笔记本方式打开添加："max_good_ip_num":300(经机器人提醒 300前面应该加一个空格)
> 
> 3.xx-net的gaeproxy全局设置改成积极
> 
> 4.扫描设置线程改成50 仅IPV6
> 
> 5.修改tredo隧道的服务器地址为数字形式的地址
> 
> 可能只需要其中两三步就能获取足够多的IP数 我也不确定 可以尝试一下 详细的操作方法在xx-net的issues搜索就行 ![](https://camo.githubusercontent.com/a561f75cef1cd80a46e48a3cb68124f596b8872b/687474703a2f2f7778342e73696e61696d672e636e2f6c617267652f3630643562643862677931667a343667786b3031326a32307132306b653074752e6a7067)

我的情况：
1. Win 10 下面 控制面板>网络和internet>网络连接>以太网，右击查看属性。“Microsoft网络适配器多路传送协议”原本就没勾选，“Internet协议版本6”一项原本就有勾选。如果您说的不是这两项，那我也不知道是什么。
2. 照做完毕。
3. 看不懂。在软件图标右键菜单和设置界面里找了半天也找不到“积极”两个字。
4. 照做完毕。
5. 还没试。
五步做了三步，结果是一切照旧。不知哪里做的不对。

**Comment by AnyWAT** [comment]
> 3\. 看不懂。在软件图标右键菜单和设置界面里找了半天也找不到“积极”两个字。

https://github.com/XX-net/XX-Net/issues/12043 当然，[GAEProxy 高级配置](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#global_setting)—设置级别：正常改作其它，适当增大连接接收缓冲大小、修改 GAEPROXY 其它参数默认值。。。

**Comment by burdenlee** [comment]
> > 1.控制面板-网络连接-以太网-（1）去掉microsoft网络适配器的√ （2）IPV6协议打√
> > 2.“XX-Net-master\data\gae_proxy”找到config.json用笔记本方式打开添加："max_good_ip_num":300(经机器人提醒 300前面应该加一个空格)
> > 3.xx-net的gaeproxy全局设置改成积极
> > 4.扫描设置线程改成50 仅IPV6
> > 5.修改tredo隧道的服务器地址为数字形式的地址
> > 可能只需要其中两三步就能获取足够多的IP数 我也不确定 可以尝试一下 详细的操作方法在xx-net的issues搜索就行 ![](https://camo.githubusercontent.com/a561f75cef1cd80a46e48a3cb68124f596b8872b/687474703a2f2f7778342e73696e61696d672e636e2f6c617267652f3630643562643862677931667a343667786b3031326a32307132306b653074752e6a7067)
> 
> 我的情况：
> 
> 1. Win 10 下面 控制面板>网络和internet>网络连接>以太网，右击查看属性。“Microsoft网络适配器多路传送协议”原本就没勾选，“Internet协议版本6”一项原本就有勾选。如果您说的不是这两项，那我也不知道是什么。
> 2. 照做完毕。
> 3. 看不懂。在软件图标右键菜单和设置界面里找了半天也找不到“积极”两个字。
> 4. 照做完毕。
> 5. 还没试。
>    五步做了三步，结果是一切照旧。不知哪里做的不对。

#12037 这个方法可行

**Comment by Kashgar-Castle** [comment]
> > 3. 看不懂。在软件图标右键菜单和设置界面里找了半天也找不到“积极”两个字。
> 
> #12043 当然，[GAEProxy 高级配置](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#global_setting)—设置级别：正常改作其它，适当增大连接接收缓冲大小、修改 GAEPROXY 其它参数默认值。。。

经你提示我找到“积极”俩字儿了，在GAEProxy-高级-设置级别的下拉菜单里。五步里完成了四步，然而并没有用。有效ipv6数还是只有两个。

**Comment by AnyWAT** [comment]
#12043 【[找出并更换适用于你的服务器]( )】（简化自【（并不保证你也正常的）[傻瓜步骤](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 ) 】 ）

**Comment by Kashgar-Castle** [comment]
> #12037 这个方法可行

谢谢告知。在有其他选择的情况下我不想大动干戈地运行本小白理解不了的命令。还是等着版主更新。

**Comment by Lex-Clan** [comment]
这方法挺管用的，就是有时候会无限请求超时

**Comment by AnyWAT** [comment]
> 这方法挺管用的，就是有时候会无限请求超时

可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。

**Comment by loy20002000** [comment]
这里还在收听的朋友可以核实一下，注意不要在排名靠前几页的帖子回复或是开新帖。


------------------

如果我说的是错的，请XX-NET账号使用者证明你就是XX本人。

在这里通报一个观察，不一定准确。

XX-NET项目可能以后再也不会更新了，就算更新也不要再使用了。我已经删除了所有XX的工具，包括手机版和PC版。因为XX-NET项目可能已经被中共接管了。理由如下：

1.最近我的帖子频繁被删除，哪怕是跟政治不沾边的也会被删。我谈论Google的安全性，日本网络的安全性，美国网络的监听，关中国政治什么事儿？
2.XX-NET几乎24小时在线，可以查看我的删帖时间记录。
3.老的讨论贴XX-NET通常会参与一些讨论，但上次更新到现在他参与过任何讨论么？
4.这种事情已经有先例。大家可以搜索[高铁 忘情]，这哥们的新浪blog就是被政府接管。他亲口确认。另外ss项目的删除也可以说明一些问题。

**Comment by wa008** [comment]
操作5，具体怎么操作呀

**Comment by AnyWAT** [comment]
> 操作5，具体怎么操作呀

> 5.修改tredo隧道的服务器地址为数字形式的地址

#12043 操作【[找出并更换适用于自己的服务器]( )】（简化自【（并不保证你也正常的）[傻瓜步骤](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507 ) 】 ）

**Comment by AnyWAT** [comment]
时过境迁。。。
Teredo 隧道：#12455 或原生：#12477
