### ISSUE TITLE
”who“ is AnyWAT

### ISSUE THREAD

**Issue by CompleX0321** [XX-net/XX-Net#12073]
As titled

**Comment by Peterpey** [comment]
Who cares

**Comment by cypcym** [comment]
AnyWAT是谁？
AnyWAT来自哪里？
AnyWAT要干什么？

**Comment by gitxxnet2018** [comment]
AnyWAT是个热心的人，但技术有限，只会引用别人的帖子，往往不能解决他人的具体问题，反而造成他人的困惑。

**Comment by AnyWAT** [comment]
> 虽然他写的东西很难看明白，但是的确帮我解决过两次问题。

> 但技术有限，只会引用别人的帖子，往往不能解决他人的具体问题，反而造成他人的困惑。

代码老白从必须开启 IPv6（隧道）一年多以来，每天基本运行 XX-Net 不少于12小时，一直几乎分分钟/24小时正常的“机器人”——（发帖）赚钱机器，非人！🤣被某些淫及巨硬“通缉”中。。。

**Comment by wangshantao** [comment]
只会复制粘贴的热心网友，对于不搜索issues的人还是有些帮助
对于搜索issues的人就是灾难，基本每个issues下都能看到他相似且表达不清晰的回复

**Comment by r6008** [comment]
整天除了巨硬，估计伟哥吃多了😂

**Comment by CompleX0321** [comment]
虽然的确有帮助解决问题的情况，但是总体上个人认为加剧了混乱程度
不管是发帖赚钱还是测试ai为目的
都感觉不甚舒适

**Comment by AnyWAT** [comment]
> 虽然的确有帮助解决问题的情况，但是总体上个人认为加剧了混乱程度
> 不管是发帖赚钱还是测试ai为目的
> 都感觉不甚舒适

又有得入数。。。

**Comment by AnyWAT** [comment]
哈哈 https://github.com/XX-net/XX-Net/issues/12326#issuecomment-470894677
