### ISSUE TITLE
有效 IPv6 IP 数為0了，不能上了，求解，谢谢了！

### ISSUE THREAD

**Issue by winnijie** [XX-net/XX-Net#12078]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by winnijie** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:99 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by cypcym** [comment]
worker：h1 ：0 h2：0 

个人猜测是terede服务器的问题；
如果得闲而且急用，可以尝试手动更换到另外的服务器

**Comment by AnyWAT** [comment]
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043

**Comment by dfsr** [comment]
我也是0了，也不能用了。

**Comment by jazzcat31** [comment]
有感还是要看ISP，公司里电信，已经totally放弃；家里移动宽带，真香

**Comment by Kashgar-Castle** [comment]
> GAEPROXY->高级->全局设置，连接接收缓冲池大小，增加至2048
> GAEPROXY->高级->扫描设置，关闭自动调整扫描线程数，设置最大扫描线程数为100
> 以上更改完毕后我这边一直都是满ipv6数

怎么在我这儿就没用呢

**Comment by Kashgar-Castle** [comment]
> > 怎么在我这儿就没用呢
> 
> 前提：你所采用的服务器如果对你够友好 #12043 【找出并更换适用于自己的服务器】（简化自【（并不保证你也正常的）[傻瓜步骤](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-450581507) 】 ）

年纪大了，懒得折腾。我觉得我以前在goagent, goproxy, shadowsocks上面花的时间都够多了，作为小白完全是在勉强自己。V2ray没弄成，也不打算穷究了。在有其他的工具的情况下，不打算为了一个软件大动干戈。

BTW, Goproxy到现在为止好像还是没有复活的办法。

**Comment by AnyWAT** [comment]
> 年纪大了，懒得折腾。

#12043 简单快速更换服务器——管理员 cmd：
netsh int ipv6 set teredo enterpriseclient x.x.x.x

**Comment by AnyWAT** [comment]
> V2ray没弄成，也不打算穷究了。

有免费版呀

> BTW, Goproxy到现在为止好像还是没有复活的办法。

+1，不过一直有正常的XX-Net 足矣

**Comment by change1984** [comment]
XXnet 不更新了吗 有效 IPv6 IP 数为零 没有解决办法了吗

**Comment by AnyWAT** [comment]
> XXnet 不更新了吗 有效 IPv6 IP 数为零 没有解决办法了吗

如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by change1984** [comment]
> XXnet 不更新了吗 有效 IPv6 IP 数为零 没有解决办法了吗
> 
> 如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3717.0 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:200 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by change1984** [comment]
> XXnet 不更新了吗 有效 IPv6 IP 数为零 没有解决办法了吗
> 
> 如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 200
XX-Net 状态 | 空闲
IP 延迟 | 2250

**Comment by AnyWAT** [comment]
#12043 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。

**Comment by change1984** [comment]
打听一下，现在的网络运营商给用户开始固定IP了吗 ？还是。。。。

**Comment by change1984** [comment]
> #12043 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。
打听一下，现在的网络运营商给用户开始固定IP了吗 ？还是。。。。

**Comment by change1984** [comment]
> #12043 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。


等待扫描 IP，建议开启 IPv6。
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 200
XX-Net 状态 | 空闲
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 50

**Comment by lindiboy** [comment]
[DEBUG] netsh state: Teredo --------------------------------------------- : enterpriseclient : win10.ipv6.microsoft.com. ͻˢ¼ : 30 ͻ˶˿ : unspecified ״̬ : qualified ͻ : teredo client : managed NAT : restricted (port) NAT Ϊ : UPNP: PortPreserving: ӳ : 192.168.1.3:58939 ⲿ NAT ӳ : 110.87.34.1:58939  这里乱码是什么？
我野是ip为0

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 或原生 #12477
