### ISSUE TITLE
Teredo 隧道合格已连接，但是测试teredo显示“qualified: False”，这是怎么回事啊？

### ISSUE THREAD

**Issue by imudie123** [XX-net/XX-Net#12072]
如图，好像挺矛盾的。

![default](https://user-images.githubusercontent.com/32681486/51086354-04c8cf80-1781-11e9-94d7-5b37dad4510c.PNG)

**Comment by whhxmwhh** [comment]
隧道机制被墙。

**Comment by AnyWAT** [comment]
> 软件自动选择的服务器，尤其是这个1711，大多数都用不了；

#12043 
![image](https://user-images.githubusercontent.com/37962734/51093540-9e26ce80-17df-11e9-8ac0-27357a076268.png)

**Comment by imudie123** [comment]
> 
> 
> 在我这边，软件自动选择的服务器，尤其是这个1711，大多数都用不了；
> 但手动切换到另外的，可以流畅运行。
> 楼主无聊了可以试试，不保证能用。

感激。俺随便切换几个之后，突然就可以用了。
