### ISSUE TITLE
ipv6开启脚本在执行python的时候报错

### ISSUE THREAD

**Issue by ccyr119** [XX-net/XX-Net#12074]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

Starting...
Config servers...
Reset IPv6...
Set IPv6 Tunnel...
  File "C:\Python34\lib\site.py", line 176
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
Over
Reboot system at first time!
请按任意键继续. . .

**Comment by AnyWAT** [comment]
貌似XX-Net 还不支持 python3

**Comment by ccyr119** [comment]
我本地安装的python3，不过xx-net->高级->ipv6隧道->启动这个按钮启动的脚本
enable_ipv6_temp.bat 在执行python脚本的时候少了一句SET PYTHONHOME=XXX
导致执行错误，手动执行enable_ipv6.bat是可以了，希望可以修复。

**Comment by SeaHOH** [comment]
没有从 start.bat 启动，所以环境变量没有继承。
