### ISSUE TITLE
现在创建新APPID需要信用卡了

### ISSUE THREAD

**Issue by wjqfsrm** [XX-net/XX-Net#12076]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
是

* 如果问题得到解决，请务必回复相关情况，谢谢。
是
![default](https://user-images.githubusercontent.com/39480049/51103491-d6e59880-181d-11e9-975b-1cf61d7c725e.PNG)
请问有解决方法吗

**Comment by MYCampanula** [comment]
而且中国的信用卡都不能用，visamastercard标识的也不行怎么破？

**Comment by AnyWAT** [comment]
https://github.com/lennylxx/ipv6-hosts/issues/287#issuecomment-466855104
