### ISSUE TITLE
求助，ipv6可用，但是有效ipv6数为0

### ISSUE THREAD

**Issue by yangyile2014** [XX-net/XX-Net#12087]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yangyile2014** [comment]
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by peqing** [comment]
@AnyWAT 我的是
==================================
类型     : enterpriseclient
服务器名称 : win10.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口  : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.4.133:52266
==================================
IPv4 状态 | OK
IPv6 状态 (如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 6
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 1077
==================================

我可以上网但是Gmail就打不开，提示：mail.google.com 将您重定向的次数过多。请问这么办啊？麻烦您了。

**Comment by peqing** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

================
使用的是chrome浏览器，SwitchyOmega扩展，情景模式： GAE-Proxy自动切换，刚刚还可以打开Google，现在IP数为0了。

**Comment by AnyWAT** [comment]
> 我可以上网但是Gmail就打不开，提示：mail.google.com 将您重定向的次数过多。

貌似 IP延时太大，代理速度不佳所致。可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。

> 刚刚还可以打开Google，现在IP数为0了。

没关闭“自动调整扫描线程数”？否则宜更换服务器 #12043

**Comment by AnyWAT** [comment]
@yangyile2014 
状态 : dormant ——隧道（长时间）休眠无法连接，宜更换服务器 #12043

**Comment by peqing** [comment]
Gmail是吧chrome配置清除，重新安装的，昨天开始还好，今天就不行 了，提示：mail.google.com 将您重定向的次数过多。

**Comment by AnyWAT** [comment]
> Gmail是吧chrome配置清除，重新安装的，昨天开始还好，今天就不行 了，提示：mail.google.com 将您重定向的次数过多。

大概率 IP延时太大，代理速度不佳所致。

**Comment by yangyile2014** [comment]
@AnyWAT 已经更换了所有ip，但是还是显示隧道（长时间）休眠，请问有什么办法

**Comment by AnyWAT** [comment]
试试：#12043 辅以。。。

**Comment by yangyile2014** [comment]
已解决，如果有跟我类似问题的，试着手动导入下ip #11748作者大大发的ipv6的ip列表，希望对你们也有效
