### ISSUE TITLE
如何解决有效IP数量少，IP延迟高，网速缓慢的问题

### ISSUE THREAD

**Issue by wtr19941227** [XX-net/XX-Net#12081]
![11](https://user-images.githubusercontent.com/34266103/51170081-838c4c80-18e8-11e9-9a0e-4cb574a6d613.png)
GAEProxy 状态稳定，有效IP数量虽然不会掉，但是数量特别少，IP延迟较高，网速慢，但是可以连接上。
请问如何提高有效IP数量？

诊断结果：XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:14
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:12
scan-ip-thread-num: 10
ip-quality: 1882
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 10——太小，增大5倍或以上，某开关关闭否？造成以下：
gws-ip-num: total:100 ipv4:0 ipv6:14——有效太小，最佳 gws-ip-num: total:100 ipv4:0 ipv6:100
ip-quality: 1882 ——太大
#12043 2、速度及稳定性较佳体验之秘籍：。。。

**Comment by wtr19941227** [comment]
好像不太行，增加了扫描线程数为100个，并且关闭自动扫描，手动检查IP。连接接受缓冲大小设置为2048kb，修改了一下config文件，现在有效IP数量反而不如之前多了，只有个位数了。。

**Comment by wtr19941227** [comment]
Teredo 隧道 | 休眠（未连接）
 
不知道跟这个有没有关系

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by wtr19941227** [comment]
![11](https://user-images.githubusercontent.com/34266103/51251670-d4796f00-19d4-11e9-8a1e-be07f5e09b78.png)

**Comment by AnyWAT** [comment]
有XX-Net 在运行，服务器不应该休眠，先禁用再启用网络。。。或更换服务器？

**Comment by AnyWAT** [comment]
> 连接接受缓冲大小设置为2048kb

貌似太大，“动作力度”太大，不一定就好？

**Comment by wtr19941227** [comment]
完了，这下彻底不能用了...
之前还有1个IPV6可以使用，这下...

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/51682818-4d0aac00-2023-11e9-8320-05e8b4f1c4b9.png)

**Comment by wtr19941227** [comment]
翻看之前给的导入IPV6地址的帖子，导入了几个IPV6，现在用可以使用了，不过只有20个有效IP

**Comment by AnyWAT** [comment]
移动内网，电脑与猫直连已有原生 IPV6，隧道原生只能二选一，隧道优于原生。禁用原生（协议）而用隧道，也可禁用隧道用原生勉强玩XX-Net https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671
