### ISSUE TITLE
有IPv6数但是一直连接不上

### ISSUE THREAD

**Issue by ArimaKisho** [XX-net/XX-Net#12086]
如下图所示，有IPv6数但是一直连接不上，求解。
![p09 6raebk r bf n8jc 0](https://user-images.githubusercontent.com/30823089/51219998-5f734e80-196e-11e9-90bb-afed55678a95.png)

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by ArimaKisho** [comment]
![image](https://user-images.githubusercontent.com/30823089/51288479-63b76e80-1a37-11e9-9fe9-2206ad166d49.png)
——————————————————————————————————————————————
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:78
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 394
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 1 ——没关闭某开关的特征值！
worker: h1:0 h2:0 ——某服务器能连但不能用！自己检测下：win1711.ipv6.microsoft.com. 的 IP是否40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）#12043

**Comment by AnyWAT** [comment]
> 可是IPv6数一直在降，求解。

服务器变了，原来所谓有效的未必还继续有效，除非归零不再增长才不正常

**Comment by ArimaKisho** [comment]
这么说还是需要换一个稳定点的服务器？

**Comment by AnyWAT** [comment]
【[找出并更换适用于自己的服务器]( )】

**Comment by ArimaKisho** [comment]
想问下以太网属性的IPv6到底要不要勾选。

**Comment by AnyWAT** [comment]
如用隧道且不设置 IPv6 DNS，可取消勾选

**Comment by tennyee** [comment]
麻烦看下我的怎么处理！也是天天断，IP数量非常少！
C:\Users\Administrator>netsh int ipv6 show teredo
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : 94.245.121.251
Client Refresh Interval : 30 seconds
Client Port             : 36723
State                   : qualified
Client Type             : teredo client
Network                 : managed
NAT                     : restricted
NAT Special Behaviour   : UPNP: No, PortPreserving: No

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:17
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 2361
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 20 ——貌似太小，参考：#12043 速度及稳定性较佳体验之秘籍
worker: h1:0 h2:0
ipv6-status: Fail ——【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】
