### ISSUE TITLE
X-TUNNEL不稳定问题反馈

### ISSUE THREAD

**Issue by dodg333** [XX-net/XX-Net#12080]
版本：3.13.1

最近购买了X-TUNNEL，按照设置一步步来的。
下载软件，登录，下载谷歌插件，下载导入文件，在插件的设置里面导入设置。
然后右键软件设置为“取消全局代理”

问题：
**前几天可以上网，最近一直不行了**

请问我哪里错了，我搜索过类似问题但是没有找到所以在这里问了。
请高手帮忙解答下，谢谢！

**Comment by dodg333** [comment]
谁能告诉我解决方法或者原因。是近期zf问题还是我操作的问题？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11892 3、X-Tunnel 正常的前提：。。。
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043

**Comment by dodg333** [comment]
> #11892 3、X-Tunnel 正常的前提：。。。
> Win32系统3.13.1隧道简单操作几乎启动即正常稳定 #12043

请教下我不太明白下面几句话的意思：

> X-Tunnel 正常的前提：
> 
> 确保GAE或其它任一前端正常
> 指定服务器（不选自动）scream2019.1.2新年新情况：。。。貌似自动亦可了？
> 关闭貌似已无效的后面3个前端（CloudFlare 偶尔有效：现因有 IPv4应基本有效，如 #11801 。尤其在GAE偶尔无效时可做临时替补，其余3个的工作数或流量几乎永远是0） #11227 (comment)
> 
首先，确认GAE或其他任一前端正常，GAE是指XX-NET里面左边菜单这个吗：GAEProxy。如果是，是需要显示“一切正常，你可以访问真正的互联网”，才表示正常吗？
任一前端是什么意思，前端在哪里？

不好意思，我不是电脑高手，我对这些设置不懂的

**Comment by AnyWAT** [comment]
> GAEProxy。如果是，是需要显示“一切正常，你可以访问真正的互联网”，才表示正常吗？

http://127.0.0.1:8085/?module=x_tunnel&menu=status 全局、GAE 前端、Cloudflare 前端。。。

> 任一前端是什么意思，前端在哪里？

> （CloudFlare 偶尔有效：现因有 IPv4应基本有效，如 #11801 。尤其在GAE偶尔无效时可做临时替补，其余3个的工作数或流量几乎永远是0）

**Comment by AnyWAT** [comment]
use-ipv6: force_ipv6——改为自动
导入 IP4 #11775
