### ISSUE TITLE
teredo隧道检测更换 需要更新 

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#12084]
目前版本不稳定 已经有1个月了， 问题在隧道， 不在ip， 希望下个版本能改进隧道的检测和更换， 因为每次都会换到相同的 不稳定的隧道， 导致 根本用不了.

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12077#issuecomment-454054480

**Comment by cypcym** [comment]
特别正确。
希望作者考虑下这个意见

**Comment by SeaHOH** [comment]
只能检测可连接性，检测稳定性是不太可能的，至少我想不到招。
