### ISSUE TITLE
等待扫描 IP，建议开启 IPv6。

### ISSUE THREAD

**Issue by lean5991** [XX-net/XX-Net#12096]
翻了好多条类似问题都没解决，特来发帖求解

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by liule0228** [comment]
无解，待解救

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by lipangbo** [comment]
兄弟，我也是这样 急。

**Comment by lean5991** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. 自己Ping 下，是否 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）#12043

**Comment by lean5991** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com. 自己Ping 下该域名，IP 是否 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）#12043
> 状态 : dormant ——休眠，隧道未正常连接
ping 结果：
40.119.212.192 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by lean5991** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com. 自己Ping 下该域名，IP 是否 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）#12043
> 状态 : dormant ——休眠，隧道未正常连接

ping 结果：
40.119.212.192 的 Ping 统计信息:
数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by AnyWAT** [comment]
Ping win1711.ipv6.microsoft.com. 自己Ping 下该域名，IP 是否 40.81.250.180

**Comment by AnyWAT** [comment]
以上 IP仅供参考，[以自己Ping 得为准](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-452953757)（重点：能正常工作的各巨硬服务器，貌似没有肉眼可辨的速度好坏之分；巨硬服务器域名随时改变指向到其它 IP）
![image](https://user-images.githubusercontent.com/37962734/51247586-8f4f4000-19c8-11e9-8f4b-22714fa82cca.png)

3、摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 才是真正的好。

**Comment by lean5991** [comment]
> Ping win1711.ipv6.microsoft.com. 自己Ping 下该域名，IP 是否 40.81.250.180

ping 出来 IP 非 40.81.250.180，结果是我刚刚发的那个

正在 Ping seawt1.ipv6.microsoft.com.akadns.net [40.119.212.192] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

40.119.212.192 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by lean5991** [comment]
> #12043 以上 IP仅供参考，[以自己Ping 得为准](https://github.com/XX-net/XX-Net/issues/11930#issuecomment-452953757)（重点：能正常工作的各巨硬服务器，貌似没有肉眼可辨的速度好坏之分；巨硬服务器域名随时改变指向到其它 IP）
> ![image](https://user-images.githubusercontent.com/37962734/51247586-8f4f4000-19c8-11e9-8f4b-22714fa82cca.png)
> 
> 3、摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 才是真正的好。

纯小白，表达不清楚见谅

**Comment by AnyWAT** [comment]
鄙人的貌似有防DNS污染Ping 得的结果
