### ISSUE TITLE
原生ipv6异常，转使用隧道，暂时恢复正常

### ISSUE THREAD

**Issue by dnfios** [XX-net/XX-Net#12093]
本人不是很了解相关方面知识，还望各位参考指正。近段时间原生ipv6表现异常（延迟增大，有效ip下降），虽仍可使用但效果较差。遂尝试使用隧道，目前使用正常。我是pc直连光猫，电信原生ipv6用户，隧道在之前为休眠状态，设置方法供各位参考：
一、“网络适配器”属性中，取消勾选“Internet协议版本6(TCP/IPV6)”
![default](https://user-images.githubusercontent.com/22696470/51227075-960c9180-198d-11e9-8e64-699ca6306514.png)
二、XX-Net---GAEProxy“高级配置”---“扫描设置”中，“IP模式”调整为“自动”
![default](https://user-images.githubusercontent.com/22696470/51227201-3793e300-198e-11e9-9365-f20527d43175.png)
三、使用效果
![default](https://user-images.githubusercontent.com/22696470/51227092-a91f6180-198d-11e9-9d16-b33575fb8180.png)

**Comment by AnyWAT** [comment]
貌似完全扫描不到 IPv4，“扫描设置”中，“IP模式”调整为“仅 IPv6”，可充分利用系统为 IPv4 预留的10%扫描。。。

**Comment by kelvin219** [comment]
试了这么多，唯有这个办法最有效 ，谢谢！！

**Comment by AnyWAT** [comment]
> 我是pc直连光猫，电信原生ipv6用户，隧道在之前为休眠状态

原生隧道二选一，正如现在取消勾选“Internet协议版本6(TCP/IPV6)”来禁用原生，使用原生貌似得禁用隧道：https://github.com/XX-net/XX-Net/issues/12043 netsh int ipv6 set teredo disable _即可禁用隧道_。（完全禁用或得由控制页内的“[禁用](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel)”完成 ）

**Comment by dnfios** [comment]
到今日，原生ipv6依旧异常，隧道更换过一次，有效的隧道会在半分钟左右把ip扫满，延迟也很低。
![2861](https://user-images.githubusercontent.com/22696470/52028336-9db16600-2549-11e9-8c21-c053a71b83d1.png)
