### ISSUE TITLE
求问为什么IPv4和v6都显示状态可以，但是有效的数目为0？

### ISSUE THREAD

**Issue by yetwanng** [XX-net/XX-Net#12095]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by cosmoson** [comment]
最近12号两会开始之后就都这样了，原生ipv6挂了，用以前任何办法都无效，提示“等待扫描 IP，建议开启 IPv6”。
只等坐等一周后两会开完看看能给恢复吗。目前只能先禁用ipv6应急一下没问题。就是在网络设置里取消勾选ipv6协议。强制只用v4+隧道就能上了。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by yetwanng** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）
C:\Users\ye>netsh int ipv6 show teredo
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient (Group Policy)
Server Name             : win1711.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo host-specific relay
Network                 : managed
NAT                     : symmetric (address)
NAT Special Behaviour   : UPNP: No, PortPreserving: Yes
Local Mapping           : 100.64.233.5:50685
External NAT Mapping    : 124.192.156.60:50685

**Comment by AnyWAT** [comment]
Local Mapping : -----
External NAT Mapping : ------隐私！
win1711.ipv6.microsoft.com. 自己检验下 IP是否 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）
【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】
