### ISSUE TITLE
XX-net挂了，推荐一个自用的SSR节点

### ISSUE THREAD

**Issue by stdbilly** [XX-net/XX-Net#12097]
速度很快
https://ssrbank.com/register?aff=21005

**Comment by BruceWang121** [comment]
![qq 20190116194055](https://user-images.githubusercontent.com/22629461/51247510-4eefc200-19c8-11e9-9aa5-f198d8c109eb.png)
看YouTube加载速度

**Comment by Hunerk** [comment]
免费的SSR一大片。

**Comment by Hunerk** [comment]
免费的SSR一大片。

**Comment by BruceWang121** [comment]
> 免费的SSR一大片。

免费的速度很慢啊

**Comment by hcrcaaaa** [comment]
收费的就免了。愿意使用收费的早就不折腾XX-NET

**Comment by Hunerk** [comment]
我的免费的不要太快哦

**Comment by Account2018** [comment]
@Hunerk  能说下你那几个备用的是什么吗？我也想多整几个备用的啊...谢谢。

**Comment by AnyWAT** [comment]
> 可能墙高了。隧道又被关了。

至此正常依旧。Teredo 隧道：#12455 或原生：￥12477
