### ISSUE TITLE
让有效 IPv6 IP 数回到100个的经验

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#12104]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 259
连接池(帮助) | 新:0 h1:0 h2:6
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 25

+++++

1、重新部署一下自己的服务端
2、重新激活一下ipv6
3、用管理员模式启动xx-net
4、退出360、金山、电脑管家等杀毒、网控软件。

然后，一切ok！有效 IPv6 IP 数回到100个！
10小时过去了，ip数还是保持在100个！
这办法，真的可行！

**Comment by Eugenejiang** [comment]
试了不行

**Comment by AnyWAT** [comment]
> 试了不行

重点在隧道：【[找出并更换适用于自己的服务器]( )】https://github.com/XX-net/XX-Net/issues/12043

**Comment by wuwuti** [comment]
从激活过程看，与以前是不同的，跳跃出的文字量非常打。。。看来版主提示更新是对的。
激活应采用外部软件。。。ipv6.bat，内部激活貌似没用。
选择服务器方面，也是让外部软件去做，tertdo.bat。内置的总是显示 win1710.ipv6.microsoft.com，也不灵。

**Comment by wuwuti** [comment]
> > 版主提示更新
> 
> 在哪？
> 
> > 内置的总是显示 win1710.ipv6.microsoft.com，也不灵。
> 
> win1710.ipv6.microsoft.com 的 IP为40.81.250.180或13.64.36.145或40.81.186.117时，貌似必GG
> ![image](https://user-images.githubusercontent.com/37962734/51361896-7485e400-1b0c-11e9-81a6-555c61e1bd61.png)

+++
软件提示
最新状态：2018-12-20
Google 更新服务器策略，请更新到3.13.1 及以上。
既然谷歌更新了服务器策略，那么就不只是更新xx-net软件，自己的服务端部署也一块顺手更新一下，岂非更踏实？

**Comment by wuwuti** [comment]
@AnyWAT   你错了。先看置顶的提示帖：
[发布] 3.13.1 解决Google 服务器更新导致无法工作
+++
3.13.1解决的是其自身与google之间的问题。
至于你的服务端，不在xx-net考虑范围。
谷歌更新
用户也顺手更新一下部署
只有好处，没坏处。

**Comment by AnyWAT** [comment]
> @AnyWAT 你错了。先看置顶的提示帖：
> [发布] 3.13.1 解决Google 服务器更新导致无法工作

[发布] 3.13.1 解决Google 服务器更新导致无法工作 #11759 请用户更新服务端（然而3.13.1并无公告此要求）？

**Comment by Eugenejiang** [comment]
我在翻墙状态下怎么都无法重新部署

**Comment by AnyWAT** [comment]
> 我在翻墙状态下怎么都无法重新部署

利用公共App ID待代理正常，在全局GAE代理下不行？

**Comment by wuwuti** [comment]
@Eugenejiang  打开xx-net，放在取消全局代理状态。然后用别的代理软件重新部署google客户端。

**Comment by Eugenejiang** [comment]
我在翻墙网络下重新部署成功，但是IPV6仍然是零

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息
