### ISSUE TITLE
无法使用：等待扫描IP，建议开启IPV6

### ISSUE THREAD

**Issue by wang3317198** [XX-net/XX-Net#12101]
诊断信息如下：：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by czhongm** [comment]
手动导入下ip #11748

**Comment by AnyWAT** [comment]
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043

**Comment by wang3317198** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 100.72.131.198:57835
外部 NAT 映射    : 183.161.193.222:18136

**Comment by wang3317198** [comment]
> 手动导入下ip [#11748](https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138)

手工导入后好了。。谢谢，好像是原100个ip全部挂了

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！
服务器名称 : win1711.ipv6.microsoft.com. 自己检测下 IP是否 40.81.250.180 或 40.81.186.117 或 13.64.36.145 均或许能连但很糟糕！弃用
#12043 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by AnyWAT** [comment]
> 客户端类型 : teredo host-specific relay

😱意外发现：开始是禁用原生 IPv6的正常隧道，有效 IP数/总 IP数之比=1，勾选网络属性内的 IPv6协议，在原生 IPv6连接上后，隧道就由 teredo client  变成了该种客户端类型，有效 IP数及连接池直线下降到接近0，IP延迟到9999。反之，取消勾选网络属性内的 IPv6协议以禁用原生，隧道变成 teredo client ，手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，恢复 。。。有效 IP数/总 IP数之比=1

😂原来楼主是没。。。
