### ISSUE TITLE
我也碰到了IPv6数量为0的情况，但是通过更换隧道后可通过Xtunnel翻墙

### ISSUE THREAD

**Issue by qibin8687** [XX-net/XX-Net#12105]
<img width="219" alt="2019-01-18_031523" src="https://user-images.githubusercontent.com/42291631/51342594-4930d400-1acf-11e9-8b08-03812e546ca4.png">
今天出现问题的，IPv6全部为0，所以就来论坛看看是不是普遍问题。然后根据教程更换了隧道。浏览器端proxy由从前的127.0.0.1:8087绑定为127.0.0.1:1080，目前访问无阻。只是，Gaeproxy还是如上图所示，即通过Gaeproxy渠道翻墙还是没辙的。目前这段时间是不是就用Xtunnel了？

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by whhxmwhh** [comment]
Microsoft Windows [版本 10.0.17134.523]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 10.0.0.3:52640
外部 NAT 映射    : 218.104.134.114:18022


C:\WINDOWS\system32>
希望能有帮助。墙一高隧道就堵了。

**Comment by whhxmwhh** [comment]
谢谢。最简便的办法。删除整个xxnet目录。重新解压安装（XX-Net-3.13.0.7z）。
正常了。
