### ISSUE TITLE
ipv6 通过测试，但 xx-net 依然显示 network IPv6 fail

### ISSUE THREAD

**Issue by chrisyue** [XX-net/XX-Net#12110]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12108#issuecomment-455407787

**Comment by chrisyue** [comment]
> [#12108 (comment)](https://github.com/XX-net/XX-Net/issues/12108#issuecomment-455407787)

啥意思？你引用的 issue 跟我的情况有何参考性？我又没用 miredo

另外你在 #12108 说用 test-ipv6.com 做测试多此一举，但无任何解释。我很好奇，如果获取访问 ipv6 网站的能力为先决条件，为什么此测试多此一举，能解释一下吗？

**Comment by AnyWAT** [comment]
> 啥意思？你引用的 issue 跟我的情况有何参考性？我又没用 miredo

network IPv6 fail 的重点在隧道，隧道的重点在于【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】https://github.com/XX-net/XX-Net/issues/12043

> 另外你在 #12108 说用 test-ipv6.com 做测试多此一举，但无任何解释。

https://github.com/XX-net/XX-Net/issues/12043
2、（隧道）摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！
3、摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 才是真正的好。

**Comment by chrisyue** [comment]
> > 啥意思？你引用的 issue 跟我的情况有何参考性？我又没用 miredo
> 
> network IPv6 fail 的重点在隧道，隧道的重点在于【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】#12043
> 
> > 另外你在 #12108 说用 test-ipv6.com 做测试多此一举，但无任何解释。
> 
> #12043
> 2、（隧道）摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！
> 3、摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 才是真正的好。

?? 
我都说我不用 Miredo 为啥还提隧道和 teredo 服务器，用 teredo 怎么连我本来就会。
另外关于摒弃测试的解释，能正面回答否

**Comment by AnyWAT** [comment]
以为你也隧道呢：（隧道）摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！
不用隧道，没有。。。Sorry
