### ISSUE TITLE
联通光纤静态ip地址 路由器如何开启ipv6的

### ISSUE THREAD

**Issue by friday7887** [XX-net/XX-Net#12114]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by czhongm** [comment]
路由器支持ipv6么？一般的家用的路由器都不支持，刷OpenWRT或者DD-WRT一般启用ipv6后不用什么特殊配置就可以用了。

**Comment by rbridomzmr** [comment]
路由器不支持IPV6也可以, 由光猫代替分配IPV6, https://github.com/XX-net/XX-Net/issues/12099?_pjax=%23js-repo-pjax-container#issuecomment-455737634
