### ISSUE TITLE
确认，用4G热点，gae正常

### ISSUE THREAD

**Issue by hujunyao** [XX-net/XX-Net#12113]
确认，如果是用正常光纤模式，xxnet找不到有效ip,但是只要用4G,打开热点，再上，同样的配置，什么都不需要操作，就能正常上网。ip瞬间满血。

**Comment by hujunyao** [comment]
实验基本说明  tunnel 不稳定 不是服务器问题，是中间被干扰造成的

**Comment by eljake58** [comment]
我之前就是
