### ISSUE TITLE
上海电信公网，GAE不行了。

### ISSUE THREAD

**Issue by youngwater** [XX-net/XX-Net#12116]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 10 秒
客户端端口                : unspecified
状态                    : dormant

IPv4 状态 | OK
-- | --
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 0
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

是不是电信把IPV6服务器都封了？

**Comment by AnyWAT** [comment]
状态 : dormant 更换服务器？
可试试：https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by bdtbbylzy** [comment]
同上海电信，同无法访问
应该不是ipv6上的原因，问题应该出在：没有能用的ip地址
因为上海电信本来就有原生ipv6，开不开teredo其实无所谓，开了反而干扰原生ipv6
反正我这里test-ipv6.com不开隧道，一直是10/10，完全正常
况且ipv6状态那里显示的是OK，只是有效ip数是0
报错：等待扫描 IP，建议开启 IPv6。
现在不知道具体是什么原因，希望开发人员继续帮助排查，感谢你们的付出

**Comment by bdtbbylzy** [comment]
贴下xx-net诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by bdtbbylzy** [comment]
teredo隧道信息：
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : win1807.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

**Comment by bdtbbylzy** [comment]
ping ipv6.test-ipv6.com 的结果：
正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:
来自 2001:470:1:18::4:230 的回复: 时间=167ms
来自 2001:470:1:18::4:230 的回复: 时间=178ms
来自 2001:470:1:18::4:230 的回复: 时间=174ms
来自 2001:470:1:18::4:230 的回复: 时间=148ms

2001:470:1:18::4:230 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 148ms，最长 = 178ms，平均 = 166ms

**Comment by AnyWAT** [comment]
原生与隧道只能二选一：如用隧道，网络连接属性内取消勾选 IPv6协议
原生ipv6异常，转使用隧道，暂时恢复正常 #12093
服务器名称 : win1807.ipv6.microsoft.com.——自己检查下，此域名服务器的 IP是否 40.81.250.180 或 40.81.186.117 或 13.64.36.145 #12043 
![image](https://user-images.githubusercontent.com/37962734/51425276-b732e380-1c14-11e9-84ba-ba7e07b7dc9a.png)

**Comment by youngwater** [comment]
ping win1807.ipv6.microsoft.com

正在 Ping seawt1.ipv6.microsoft.com.akadns.net [40.119.212.192] 具有 32 字节的数
据:
请求超时。
请求超时。
请求超时。
请求超时。

40.119.212.192 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，
--
Teredo 参数
--
类型                    : enterpriseclient
服务器名称              : win1807.ipv6.microsoft.com
客户端刷新间隔          : 10 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 是
本地映射           : 192.168.1.4:51726
外部 NAT 映射    : 222.64.173.71:51726
--
IPv4 状态 | OK
IPv6 状态(如何开启) | Fail (尝试修复)
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 1
XX-Net 状态 | 空闲
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10
--
这是使用隧道的结果。

请问，如果用DnsJumper有用吗？

**Comment by youngwater** [comment]
原生的不行，用隧道终于连上了。

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是


属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 13
总 IP 数 | 14
XX-Net 状态 | 工作
IP 延迟 | 1477
连接池(帮助) | 新:0 h1:0 h2:5

**Comment by asd1219** [comment]
应该是墙能准确的识别出gae的流量
去年有过几天，一用gae代理上网，可用ip就迅速降为0，重新拨号换本地ip后，可以再次正常使用
这次看来是墙大规模应用了这个规则

**Comment by AnyWAT** [comment]
LS是说原生？如是隧道。。。 https://github.com/XX-net/XX-Net/issues/12119

**Comment by AnyWAT** [comment]
就要乱搞加胡搞：项目已死，有事请烧香 #12130

**Comment by AnyWAT** [comment]
> 如果用DnsJumper有用吗？

没用过，https://github.com/XX-net/XX-Net/issues/12043 辅以 [Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy) 类[东东](https://github.com/XX-net/XX-Net/issues/11287#issuecomment-415963218)（[初次安装运行](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)，先禁用 Smart Router 模块或退出XX-Net，以释放53端口）

**Comment by AnyWAT** [comment]
> 客户端类型 : teredo host-specific relay

😱意外发现：开始是禁用原生 IPv6的正常隧道，有效 IP数/总 IP数之比=1，勾选网络属性内的 IPv6协议，在原生 IPv6连接上后，隧道就由 teredo client  变成了该种客户端类型，有效 IP数及连接池直线下降到接近0，IP延迟到9999。反之，取消勾选网络属性内的 IPv6协议以禁用原生，隧道变成 teredo client ，手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，恢复 。。。有效 IP数/总 IP数之比=1

😂原来有人没。。。
