### ISSUE TITLE
XX-Net用不了，谁帮忙看看哪里的问题

### ISSUE THREAD

**Issue by casezon** [XX-net/XX-Net#12123]
用不了，谁帮忙看看哪里的问题

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 10——适当增大。。。
worker: h1:0 h2:0——已归零
ip-quality: 9999——已最坏的极值，较佳300左右
gws-ip-num: total:100 ipv4:0 ipv6:1——有效太小
以上3项，或最大扫描线程数太小，或没关闭某开关，或服务器不佳。更换服务器？
https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】速度及稳定性较佳体验之秘籍
