### ISSUE TITLE
前几天能用的今天又用不了了

### ISSUE THREAD

**Issue by Phineario** [XX-net/XX-Net#12126]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 20 秒
客户端端口                : 10086
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

**Comment by Phineario** [comment]
换了好几个服务器都不行

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！

**Comment by Phineario** [comment]
> 本地映射 : -----
> 外部 NAT 映射 : -----隐私！

已删除，谢谢提醒

**Comment by AnyWAT** [comment]
> 换了好几个服务器都不行

判断标准：隧道能较快连接且 IPv6 状态(如何开启) 较快 OK
1、或许XX-Net 已”晕死“，免退出再启动一下
2、没关闭某开关？
3、更换服务器？

#12111 3.3DNS污染这一块是老生常谈了。—— https://github.com/XX-net/XX-Net/issues/12043 辅以 Pcap_DNSProxy 类东东

**Comment by mrsoshining** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

我的这两天也不行了，跟着几位大侠的步骤操作过，还是不行

**Comment by mrsoshining** [comment]
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 7164
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.0.106:7164
外部 NAT 映射    : 115.171.22.76:39155

**Comment by lefantian** [comment]
墙垒高了，看来只能期望xxnet后期更新能有突破

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！
scan-ip-thread-num: 30——适当增大？
https://github.com/XX-net/XX-Net/issues/12126#issuecomment-455857636

**Comment by lefantian** [comment]
> ## Teredo 参数
> 类型 : client
> 服务器名称 : teredo-debian.remlab.net
> 客户端刷新间隔 : 30 秒
> 客户端端口 : 7164
> 状态 : qualified
> 客户端类型 : teredo client
> 网络 : unmanaged
> NAT : restricted
> NAT 特殊行为 : UPNP: 是，PortPreserving: 否

最后两行IP删掉，隐私

**Comment by AnyWAT** [comment]
> os-release: 7

Win7没有系统服务：IP 转换配置服务，如能，最好固定电脑的内网 IP？

**Comment by mrsoshining** [comment]
> > ## Teredo 参数
> > 类型 : client
> > 服务器名称 : teredo-debian.remlab.net
> > 客户端刷新间隔 : 30 秒
> > 客户端端口 : 7164
> > 状态 : qualified
> > 客户端类型 : teredo client
> > 网络 : unmanaged
> > NAT : restricted
> > NAT 特殊行为 : UPNP: 是，PortPreserving: 否
> 
> 最后两行IP删掉，隐私

谢谢

**Comment by cosmoson** [comment]
> 墙垒高了，看来只能期望xxnet后期更新能有突破

兄弟正解，这论坛上各种方法都试了，都不行，不折腾了，唯一希望是等新版本。

**Comment by AnyWAT** [comment]
[（有意思：原来同一域名各地所对应的 IP可以是不同的。）](https://github.com/XX-net/XX-Net/issues/7482#issue-267047907)
