### ISSUE TITLE
为什么ipv6状态一开始都是ok过一会就fail了？

### ISSUE THREAD

**Issue by zhuwanling** [XX-net/XX-Net#12120]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
服务器 IP从运行正常变成到了隧道虽能连接，但 IPv6 状态始终 Fail 而无法 OK 的 IP？—— #12043 隧道结论
还是没关闭某开关？—— #12043 速度及稳定性较佳体验之秘籍

**Comment by robur02** [comment]
我这也是，一开始有几十个可用IP，用一会儿就降到0了。这墙是不是太智能了？

**Comment by AnyWAT** [comment]
LS是说原生？如是隧道。。。 https://github.com/XX-net/XX-Net/issues/12119 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by AnyWAT** [comment]
我现在一不行就用脚本更换隧道。。马上又好了——没不行的咋整还是不用咋整？😂
