### ISSUE TITLE
惨了，根据这篇文章一设置，XX完全不能用了，求恢复

### ISSUE THREAD

**Issue by imudie123** [XX-net/XX-Net#12128]
[https://github.com/XX-net/XX-Net/issues/12037#issue-397809215](url)
最近ip少，根据这个大佬的文章设置了一下，更改了服务器和端口，现在完全不能用了。不知道为啥。求重置方法，让电脑（win10家庭版）的ipv6设置恢复原状。
如今的情况：
![default](https://user-images.githubusercontent.com/32681486/51441525-897d9580-1d0d-11e9-8aeb-b9105ae2d321.PNG)

**诊断信息如下：**
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Eri5Ch** [comment]
给你说一个方法 参考wiki 跟着wiki仔细再设置一下

**Comment by imudie123** [comment]
> 
> 
> 给你说一个方法 参考wiki 跟着wiki仔细再设置一下

都重新设置来很多次了啊。
我现在只想求个方法，让Ipv6能恢复初始状态。
哎。

**Comment by AnyWAT** [comment]
> 更改了服务器和端口，现在完全不能用了

不能用因为 ipv6-status: Fail，改用服务器 x.x.x.x 并恢复默认刷新间隔及端口，管理权限 cmd：
netsh int ipv6 set teredo enterpriseclient x.x.x.x default default

**Comment by AnyWAT** [comment]
出现 probe (secondary server) 久不连接，说明此服务器你上不了

> 我现在只想求个方法，让Ipv6能恢复初始状态。

试试：程序目录内的 disable_ipv6.bat 再 enable_ipv6.bat

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 20——👎小气鬼！#12043 速度及稳定性较佳体验之秘籍。。。

**Comment by imudie123** [comment]
> 
> 
> scan-ip-thread-num: 20——👎小气鬼！#12043 速度及稳定性较佳体验之秘籍。。。

呐，我是看https://github.com/XX-net/XX-Net/issues/12037#issue-397809215设置的。目前挺稳定的，有时候我也会乱改成50-100，但是稳定的时候就先这么着吧。一会又折腾坏了，能把人急成膀胱炎。
