### ISSUE TITLE
google搜索需要验证码

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#1212]
![Uploading aa.jpg…]()
如下图所示。经常出现这种问题。基本上10次google搜索就需要2-3次输入验证码。请问这个问题怎么解决？感谢！

**Comment by Cat7373** [comment]
从未遇到过验证码- -

**Comment by farshidvahid** [comment]
图片传不上去。果壳网上有类似的讨论，上面有图片可以参看。
http://www.guokr.com/question/183861/

**Comment by cdmask** [comment]
遇到过好多次 不过最近好像又没怎么见到了

**Comment by shinji-ikari** [comment]
![7_nwf e wnzbl 2vqpw3yj4](https://cloud.githubusercontent.com/assets/12407493/10450641/326ea33a-71ce-11e5-8dbb-53194cadb7c2.png)
前几天才重新下载了2.5.1使用.不会出现谷哥404了.倒是时不时的出现这个问题.

**Comment by cdmask** [comment]
没有解决方案吗?

**Comment by cdmask** [comment]
@834

**Comment by cdmask** [comment]
#834

**Comment by simonasd** [comment]
@cdmask 参考 #834 和 #1303

**Comment by Godseeker** [comment]
我也被验证码困扰。求高手

**Comment by jzp820927** [comment]
设置直连规则
