### ISSUE TITLE
【最新发现】——如何让xx-net正常运转？

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#12133]
如何让xx-net正常运转？最新发现！
最关键的是选择teredo服务器。选对了，有效ip数立马上升到100个。
    1   teredo.remlab.net
    2   teredo2.remlab.net
    3   teredo-debian.remlab.net
    4   teredo.ngix.ne.kr
    5   teredo.trex.fi
    6   teredo.autotrans.consulintel.com
    7   teredo.managemydedi.com
    8   teredo.ipv6.microsoft.com
    9   win10.ipv6.microsoft.com
    10  teredo.iks-jena.de',
    11  win1710.ipv6.microsoft.com
上面这些服务器，有的完全失效，有的运转正常。
尝试手动选择试验一下就ok！

**Comment by wuwuti** [comment]
XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 236
连接池(帮助) | 新:0 h1:0 h2:20
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 100

**Comment by AnyWAT** [comment]
> 上面这些服务器，有的完全失效，有的运转正常。
> 尝试手动选择试验一下就ok！

https://github.com/XX-net/XX-Net/issues/12043 巨硬及其它服务器汇总

**Comment by hcrcaaaa** [comment]
怎样选择teredo服务器？

**Comment by pinoren** [comment]
> 怎样选择teredo服务器？

以下内容保存为 xxx.cmd，以管理员权限运行。

@echo off
:setteredo
set /p teredo=请输入要设置的Teredo服务器名称，然后回车。

echo Teredo服务器名：%teredo%

netsh interface teredo set state type=enterpriseclient servername=%teredo%.

pause

goto setteredo

**Comment by AnyWAT** [comment]
有人想的是自动给选个好用的。。。

**Comment by pinoren** [comment]
> 有人想的是自动给选个好用的。。。否则，管理员 cmd：netsh int ipv6 set teredo enterpriseclient x.x.x.x
> 貌似也不复杂？
> 摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 并能扫描出 IP才是真正的好。

道可道，非常道；名可名，非常名。
无名，天地之始，有名，万物之母。
故常无欲，以观其妙，常有欲，以观其徼。
此两者，同出而异名，同谓之玄，玄之又玄，众妙之门。

**Comment by pinoren** [comment]
> 有人想的是自动给选个好用的。。。否则，管理员 cmd：netsh int ipv6 set teredo enterpriseclient x.x.x.x
> 貌似也不复杂？
> 摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 并能扫描出 IP才是真正的好。

浔阳江头夜送客，枫叶荻花秋瑟瑟。主人下马客在船，举酒欲饮无管弦。醉不成欢惨将别，别时茫茫江浸月。
忽闻水上琵琶声，主人忘归客不发。寻声暗问弹者谁，琵琶声停欲语迟。移船相近邀相见，添酒回灯重开宴。千呼万唤始出来，犹抱琵琶半遮面。转轴拨弦三两声，未成曲调先有情。弦弦掩抑声声思，似诉平生不得志。低眉信手续续弹，说尽心中无限事。轻拢慢捻抹复挑，初为《霓裳》后《六幺》。大弦嘈嘈如急雨，小弦切切如私语。嘈嘈切切错杂弹，大珠小珠落玉盘。间关莺语花底滑，幽咽泉流冰下难。冰泉冷涩弦凝绝，凝绝不通声暂歇。别有幽愁暗恨生，此时无声胜有声。银瓶乍破水浆迸，铁骑突出刀枪鸣。曲终收拨当心画，四弦一声如裂帛。东船西舫悄无言，唯见江心秋月白。
沉吟放拨插弦中，整顿衣裳起敛容。自言本是京城女，家在虾蟆陵下住。十三学得琵琶成，名属教坊第一部。曲罢曾教善才服，妆成每被秋娘妒。五陵年少争缠头，一曲红绡不知数。钿头银篦击节碎，血色罗裙翻酒污。今年欢笑复明年，秋月春风等闲度。弟走从军阿姨死，暮去朝来颜色故。门前冷落鞍马稀，老大嫁作商人妇。商人重利轻别离，前月浮梁买茶去。去来江口守空船，绕船月明江水寒。夜深忽梦少年事，梦啼妆泪红阑干。
我闻琵琶已叹息，又闻此语重唧唧。同是天涯沦落人，相逢何必曾相识！我从去年辞帝京，谪居卧病浔阳城。浔阳地僻无音乐，终岁不闻丝竹声。住近湓江地低湿，黄芦苦竹绕宅生。其间旦暮闻何物？杜鹃啼血猿哀鸣。春江花朝秋月夜，往往取酒还独倾。岂无山歌与村笛？呕哑嘲哳难为听。今夜闻君琵琶语，如听仙乐耳暂明。莫辞更坐弹一曲，为君翻作《琵琶行》。感我此言良久立，却坐促弦弦转急。凄凄不似向前声，满座重闻皆掩泣。座中泣下谁最多？江州司马青衫湿。

**Comment by pinoren** [comment]
嗯，我想看看这种机器狗遇到大量的不相干关键字会从网上叼回来点什么内容来回复。

**Comment by AnyWAT** [comment]
原来是🐕，还以为是🐺呢。。。

**Comment by pinoren** [comment]
> 原来是，还以为是呢。。。

两个黄鹂鸣翠柳，一个AnyWAT吠青天。
论坛回复A I 写，没关键字全玩儿完。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/51509646-e031bf00-1e34-11e9-9fc9-8a5e132aa73f.png)

**Comment by hcrcaaaa** [comment]
> > 怎样选择teredo服务器？
> 
> 以下内容保存为 xxx.cmd，以管理员权限运行。
> 
> @echo off
> :setteredo
> set /p teredo=请输入要设置的Teredo服务器名称，然后回车。
> 
> echo Teredo服务器名：%teredo%
> 
> netsh interface teredo set state type=enterpriseclient servername=%teredo%.
> 
> pause
> 
> goto setteredo

可以发个正式的格式吗？如以服务器名"win10.ipv6.microsoft.com"为例。
谢谢。

**Comment by pinoren** [comment]
> > > 怎样选择teredo服务器？
> > 
> > 
> > 以下内容保存为 xxx.cmd，以管理员权限运行。
> > @echo off
> > :setteredo
> > set /p teredo=请输入要设置的Teredo服务器名称，然后回车。
> > echo Teredo服务器名：%teredo%
> > netsh interface teredo set state type=enterpriseclient servername=%teredo%.
> > pause
> > goto setteredo
> 
> 可以发个正式的格式吗？如以服务器名"win10.ipv6.microsoft.com"为例。
> 谢谢。

这个没有格式的呀，做成这个文件后，这个文件运行了你可以把你要改的服务器地址复制粘贴进去敲回车，然后就帮你改成你要的服务器地址啦！

**Comment by hcrcaaaa** [comment]
@echo off
:setteredo
set /p teredo=win10.ipv6.microsoft.com

echo Teredo win10.ipv6.microsoft.com：%teredo%

netsh interface teredo set state type=enterpriseclient servername=%teredo%.

pause

goto setteredo






==========
我这样保存了后打开没反应。

**Comment by pinoren** [comment]
> @echo off
> :setteredo
> set /p teredo=win10.ipv6.microsoft.com
> 
> echo Teredo win10.ipv6.microsoft.com：%teredo%
> 
> netsh interface teredo set state type=enterpriseclient servername=%teredo%.
> 
> pause
> 
> goto setteredo
> 
> ==========
> 我这样保存了后打开没反应。

扩展名要是.cmd，你可能是系统默认不限制扩展名，所以你保存的是 xxx.cmd.txt，双击后打开的就是记事本了。

**Comment by hcrcaaaa** [comment]
你帮我看下，我保存的内容会不会错？

**Comment by pinoren** [comment]
> 你帮我看下，我保存的内容会不会错？

你直接保存我发出来的内容不就可以了？等能正常运行后你把他改成朵儿花儿都没问题嘛。

**Comment by hcrcaaaa** [comment]
![Uploading QQ截图20190122111818.jpg…]()
