### ISSUE TITLE
项目已死，有事请烧香

### ISSUE THREAD

**Issue by gfvre123** [XX-net/XX-Net#12130]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by imudie123** [comment]
不会啊，俺这里还挺好用的。
![5](https://user-images.githubusercontent.com/32681486/51442286-699e9f80-1d16-11e9-9d82-66df0c0c9c77.PNG)
电信的。

**Comment by AnyWAT** [comment]
移动的。。。
![image](https://user-images.githubusercontent.com/37962734/51442306-95218a00-1d16-11e9-9648-483523fb6a50.png)
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by cypcym** [comment]
确实不够稳定，需要时常更换服务器。不过使用倒还是可以的。
实测广东电信、广东广电宽带，可以使用。
也许分地区吧，这个就不清楚了

**Comment by treeyiki** [comment]
我已经改用free vpn chromium了。这个实在是不稳定的很。。。。

**Comment by gibwise** [comment]
没有更新了 看来作者也要给过年了 推荐一个高速机场 VIP通道免费试用https://pro.eimi.me/auth/register?code=31lCzXGMMVcViZeZVpTKnuKBiyi6pvWT
