### ISSUE TITLE
IP迅速变成0，本来80多个

### ISSUE THREAD

**Issue by 2qq2qq** [XX-net/XX-Net#12132]
`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:93 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by 2qq2qq** [comment]
奇怪，现在我的ipv6又不行了。
明明我1小时前都用了几分钟的。

`C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : client (Group Policy)
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant`

**Comment by AnyWAT** [comment]
> 奇怪，现在我的ipv6又不行了。

状态 : dormant——锅之所在，貌似服务器名称 : win10.ipv6.microsoft.com. 对你不友好呢
如下才正宗的组策略呢：
类型 : client (Group Policy)
服务器名称 : win10.ipv6.microsoft.com. (Group Policy)
客户端刷新间隔 : 30 秒 (Group Policy)
客户端端口 : unspecified (Group Policy)
#12043 摒弃（并不完整的） IPv6 组策略法！【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by 2qq2qq** [comment]
现在是这样的了。但还是获取不到ip啊。

无域名 IPv6 连接测试 |   | 超时 (15.009s)
IPv6 大数据包传输测试 |   | 失败 (0.011s)

`类型                    : client (Group Policy)
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)`

**Comment by AnyWAT** [comment]
> 无域名 IPv6 连接测试 |   | 超时 (15.009s)
> IPv6 大数据包传输测试 |   | 失败 (0.011s)

https://github.com/XX-net/XX-Net/issues/12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启隧道以来，一直正常一直不用此玩意儿
类型 : client (Group Policy) ——IPv6 组策略退回到默认的全部“未配置”，对Win10，管理员 cmd：netsh int ipv6 set teredo natawareclient 
服务器名称 : win1711.ipv6.microsoft.com. ——自己检查下，看此服务器的 IP是否黄色的3个之一？
![image](https://user-images.githubusercontent.com/37962734/51454195-853d9080-1d7e-11e9-928b-aefddde067c8.png)

**Comment by 2qq2qq** [comment]
还是没搞好，有一条错误：
路由删除失败: 找不到元素

`route DELETE ::/0`

**Comment by AnyWAT** [comment]
你想干嘛？程序目录内先 disable_ipv6.bat，再 enable_ipv6.bat

**Comment by 2qq2qq** [comment]
先 disable_ipv6.bat，再 enable_ipv6.bat，结果如下：
`
Windows IP 配置

   主机名  . . . . . . . . . . . . . : DESKTOP-AM1AIHS
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   物理地址. . . . . . . . . . . . . : 50-46-5D-9E-8E-5A
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::796e:7fb9:77c4:5c1c%3(首选) 
   IPv4 地址 . . . . . . . . . . . . : 192.168.0.9(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2019年1月21日 11:17:54
   租约过期的时间  . . . . . . . . . : 2019年1月25日 8:56:56
   默认网关. . . . . . . . . . . . . : 192.168.0.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.0.1
   DHCPv6 IAID . . . . . . . . . . . : 105924189
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-20-C3-D5-BF-50-46-5D-9E-8E-5A
   DNS 服务器  . . . . . . . . . . . : 58.20.127.238
                                       58.20.127.170
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 蓝牙网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   物理地址. . . . . . . . . . . . . : 00-1A-7D-DA-71-0A
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器


发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        系统        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        系统        256  fe80::/64                   4  蓝牙网络连接
否        系统        256  fe80::/64                   3  以太网
否        系统        256  fe80::796e:7fb9:77c4:5c1c/128    3  以太网
否        系统        256  fe80::7c77:c893:94bd:e423/128    4  蓝牙网络连接
否        系统        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        系统        256  ff00::/8                    4  蓝牙网络连接
否        系统        256  ff00::/8                    3  以太网


Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
  3          35        1500  connected     以太网
  4          65        1500  disconnected  蓝牙网络连接

查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        50      0  ::1/128
        40      1  ::/0
        30      2  2002::/16
        25      5  2001::/32
        20      3  ::/96
        10      4  ::ffff:0:0/96
         3     13  fc00::/7
         1     12  3ffe::/16
         1     11  fec0::/10


接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 3: 以太网

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite fe80::796e:7fb9:77c4:5c1c%3

接口 4: 蓝牙网络连接

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::7c77:c893:94bd:e423%4

===========================================================================
接口列表
  3...50 46 5d 9e 8e 5a ......Realtek PCIe GBE Family Controller
  4...00 1a 7d da 71 0a ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.0.1      192.168.0.9     35
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      192.168.0.0    255.255.255.0            在链路上       192.168.0.9    291
      192.168.0.9  255.255.255.255            在链路上       192.168.0.9    291
    192.168.0.255  255.255.255.255            在链路上       192.168.0.9    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上       192.168.0.9    291
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上       192.168.0.9    291
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  1    331 ::1/128                  在链路上
  3    291 fe80::/64                在链路上
  3    291 fe80::796e:7fb9:77c4:5c1c/128
                                    在链路上
  1    331 ff00::/8                 在链路上
  3    291 ff00::/8                 在链路上
===========================================================================
永久路由:
  无
`

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 或原生 #12477 均正常中。。。
