### ISSUE TITLE
原生IPV6现在是不是有问题？

### ISSUE THREAD

**Issue by hrmlsr** [XX-net/XX-Net#12138]
两台电脑一台使用原生IPV6，一台使用隧道，使用同样的appid，原生IPV6的扫描不到IP，导入IP后只有十几个有效IP，使用隧道的很快扫描到300+IP，并保持200+有效，看了下原生IPV6那台的日志，大量的 fail:error、conn fail、timed out信息，但是直接PING对应的域名可以正常解析出IPV6地址并能ping通，有没有人知道是什么原因，如何解决？

**Comment by imudie123** [comment]
原生早就有问题了。你还能有十几个，我只能扫到一两个。

**Comment by ZOOWRIA** [comment]
隧道200+怎么做到的？

**Comment by AnyWAT** [comment]
> 如何解决？

https://github.com/XX-net/XX-Net/issues/12043 辅以 [Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy) 类[东东](https://github.com/XX-net/XX-Net/issues/11287#issuecomment-415963218)（[初次安装运行](https://github.com/XX-net/XX-Net/issues/11843#issuecomment-449628231)，先禁用 Smart Router 模块或退出XX-Net，以释放53端口）

> 隧道200+怎么做到的？

一般300左右，此刻200+：https://github.com/XX-net/XX-Net/issues/12043 速度及稳定性较佳体验之秘籍及辅以。。。

**Comment by qushaobo** [comment]
狗日的华为

**Comment by skyarover** [comment]
寡妇网升级了，IPV6被针对了
