### ISSUE TITLE
3.13.1版本等待扫描 IP，建议开启 IPv6 咋弄啊？

### ISSUE THREAD

**Issue by dayayayaya** [XX-net/XX-Net#12134]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by dayayayaya** [comment]
类型                    : enterpriseclient
服务器名称              : 157.56.149.60
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted


请问XX-Net 诊断信息在哪里看？

**Comment by AnyWAT** [comment]
状态 : qualified 及 ipv6-status: OK，貌似隧道已连接，但扫描不到 IP，貌似此服务器不适用于你？
https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by AnyWAT** [comment]
> os-release: 7

Win7没有系统服务：IP 转换配置服务。如可能，最好固定电脑的内网 IP？#10184 Ipv6 自动转换 | 💖闪闪的红星💖 - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by AnyWAT** [comment]
> 这个帖子的图片都加载不出来，看不懂啊...

重点在：
![image](https://user-images.githubusercontent.com/37962734/51456063-3cd6a080-1d87-11e9-875d-9ce66ed28914.png)

Win7没有系统服务：IP 转换配置服务。
![image](https://user-images.githubusercontent.com/37962734/51456180-b1a9da80-1d87-11e9-864c-406052e60aef.png)

**Comment by AnyWAT** [comment]
> 那咋整啊？

黄色文字。。。
![image](https://user-images.githubusercontent.com/37962734/51456572-2af5fd00-1d89-11e9-98a8-27cce07b9b9e.png)

**Comment by dayayayaya** [comment]
真的是超级复杂啊，我一个做设计真是为难我啊....

**Comment by AnyWAT** [comment]
> 真的是超级复杂啊，我一个做设计真是为难我啊....

哈哈哈，为难么？谁为难谁？像有的人删除不用不就结了？

**Comment by dayayayaya** [comment]
管理权限 cmd 内运行 netsh int ipv6 set teredo enterpriseclient 157.56.149.60

前几天用了这个方法，可以上了，今天打开又上不了....
12043那篇太复杂了，研究了一上午了，没看懂....

**Comment by AnyWAT** [comment]
> 前几天用了这个方法，可以上了，今天打开又上不了....

那就试试：退出XX-Net，删除 good_ip.txt 再启动。。。

**Comment by dayayayaya** [comment]
1.退出XX-Net，删除 good_ip.txt 再启动    没有用...
2.更换服务器，随即手动检查 IP。。。   看不懂...

真是折腾人啊

**Comment by boseliy** [comment]
我也是一样，不知道该怎么设置，你解决了吗？真是难为我了

**Comment by dayayayaya** [comment]
@boseliy  NO，今天又折腾一天，依旧是瘫痪状态....

**Comment by quegfeng** [comment]
自己做个批处理运行一下：@echo off

net start "ip helper"
netsh int ipv6 reset

netsh int teredo set state default
netsh int 6to4 set state default
netsh int isatap set state default
netsh int teredo set state server=teredo.iks-jena.de
netsh int ipv6 set teredo enterpriseclient
netsh int ter set state enterpriseclient
route DELETE ::/0
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
netsh int ipv6 set prefix 2002::/16 30 1
netsh int ipv6 set prefix 2001::/32 5 1
Reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f

netsh int teredo set state default
netsh int 6to4 set state default
netsh int isatap set state default
netsh int teredo set state server=teredo.iks-jena.de
netsh int ipv6 set teredo enterpriseclient
netsh int ter set state enterpriseclient
route DELETE ::/0
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
netsh int ipv6 set prefix 2002::/16 30 1
netsh int ipv6 set prefix 2001::/32 5 1
Reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f

ipconfig /all
ipconfig /flushdns
netsh int ipv6 show teredo
netsh int ipv6 show route
netsh int ipv6 show int
netsh int ipv6 show prefix
netsh int ipv6 show address
route print
cmd

细心的朋友们会发现为什么要执行两遍如下命令呢？

netsh int teredo set state default
netsh int 6to4 set state default
netsh int isatap set state default
netsh int teredo set state server=teredo.remlab.net
netsh int ipv6 set teredo enterpriseclient
netsh int ter set state enterpriseclient
route DELETE ::/0
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
netsh int ipv6 set prefix 2002::/16 30 1
netsh int ipv6 set prefix 2001::/32 5 1
Reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f
``
