### ISSUE TITLE
X-Tunnel没有流量了

### ISSUE THREAD

**Issue by yingerson** [XX-net/XX-Net#12139]
最近XXNET已经越来越不能用了，然后好不容易找回来X-Tunnel的用户名和密码可是只有100M流量了，还有什么好办法吗？

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 100
XX-Net 状态 | 空闲
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:1
浏览器代理设置 | Fail
CA 证书状态(下载) | Fail
IP 扫描线程数(设置) | 10

概况
账户
yingerson@gmail.com [登出]

余额
$ 0.00
流量
最近XXNET已经越来越不能用了，然后好不容易找回来X-Tunnel的用户名和密码可是只有100M流量了，还有什么好办法吗？

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 100
XX-Net 状态 | 空闲
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:1
浏览器代理设置 | Fail
CA 证书状态(下载) | Fail
IP 扫描线程数(设置) | 10

概况
账户
yingerson@gmail.com [登出]

余额
$ 0.00
流量

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器]( )】

**Comment by fhq8800** [comment]
那位大佬有用不完的，fhq8800@gmail.COM。谢谢

**Comment by liuhun2000** [comment]
同求，不求多，一二十G就可以，去年开通了xtunnel，1200G，结果太不稳定，一整年只用了估计不到100G吧，送了几百G出去，其他到期全废了。。只求留点用于不时之需，，immmmmi@gmail.com

**Comment by zhgna08** [comment]
买一点吧，也不贵，算是支持项目

**Comment by liuhun2000** [comment]
收到哪位大佬的20G，谢谢

**Comment by liuhun2000** [comment]
谢谢哪位大神送的流量！谢谢！

**Comment by Jogiter** [comment]
流量到期了，哪位大神赠送点流量给我，万分感谢
jogiter.g@gmail.com
