### ISSUE TITLE
电信原生IPv6，等待扫描 IP，建议开启 IPv6

### ISSUE THREAD

**Issue by cipherniu** [XX-net/XX-Net#12149]
大神帮忙看一眼吧
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by MadMaxPayne8964** [comment]
联通原生IPv6，也这样。teredo能苟延残喘下

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11759#issuecomment-454322008

**Comment by skyarover** [comment]
寡妇网已经升级了针对IPV6的策略
