### ISSUE TITLE
teredo 移动好像有特征码封禁

### ISSUE THREAD

**Issue by earthGavinLee** [XX-net/XX-Net#12143]
在不同的计算机和操作系统上运行teredo巨硬新设备会满血复活，但是用1天后。teredo可以获取IPV6但是无法ping通。在换一台计算机又能满血复活，一天后又会被BAN。这个特征码是什么？

**Comment by AnyWAT** [comment]
移动一直24X7几乎分分钟正常。https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by earthGavinLee** [comment]
被BAN的计算机反复测试，更换不同的巨硬服务器，Teredo的地址一直保持不变。感觉还是特征码被记住了？

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 2001:0:9d38:6ab8:246e:3d84:3f57:fe9a //此地址一致不变
   本地链接 IPv6 地址. . . . . . . . : fe80::246e:3d84:3f57:fe9a%21
   默认网关. . . . . . . . . . . . . :



C:\Users\Administrator>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 157.56.106.184
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by AnyWAT** [comment]
> IPv6 地址 . . . . . . . . . . . . : 2001:0:9d38:6ab8:246e:3d84:3f57:fe9a //此地址一致不变

没观察过。。。

> 服务器名称 : 157.56.106.184
> 状态 : dormant

（在有XX-Net 运行时）一直如此，扫描此服务器对你不友好（都无法连接），更换：摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 并能扫描出 IP才是真正的好。

**Comment by xc1988** [comment]
移动ipv6直连 都死透了

**Comment by q9020** [comment]
只能用轮子的凑合一下了，，
