### ISSUE TITLE
突然好了。你们呢？

### ISSUE THREAD

**Issue by punkzhang** [XX-net/XX-Net#12140]
3天前开始，IPv6扫出来一连网就挂。
今天都准备买VPS了。
开了测试一下，发现居然好了。
用的debian那个teredo服务器。
8844的DNS。

**Comment by AnyWAT** [comment]
24X7分分钟正常的都不好意思。。。

**Comment by zhgna08** [comment]
还是时好时坏，不知是什么原因

**Comment by lefantian** [comment]
还好，虽然IP不多，好歹今天能有了

**Comment by zhencaihao** [comment]
一个都没有，看来是没什么希望了。唉。

**Comment by northsheep** [comment]
我的xxnet已经完事了，和xtunnel混着用

**Comment by dayuii** [comment]
具体的步骤可否贴一下?

**Comment by dayuii** [comment]
我这里一直是这样的提示"
https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZ72Ys3Me_RR0jLUAE7JwkIy0c0sjAJCMtrqB_mCQjLdkTbPIkIy3ti66fJBQTGSdu5INrTLWuIy1mVgFXJCMtjoYoqCQU

2019-01-23 08:13:00.344 - [WARNING] not enough ip

2019-01-23 08:13:00.617 - [WARNING] task POST None /_gh/ timeout"

**Comment by dayuii** [comment]
> 我这里一直是这样的提示"
> https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZ72Ys3Me_RR0jLUAE7JwkIy0c0sjAJCMtrqB_mCQjLdkTbPIkIy3ti66fJBQTGSdu5INrTLWuIy1mVgFXJCMtjoYoqCQU
> 
> 2019-01-23 08:13:00.344 - [WARNING] not enough ip
> 
> 2019-01-23 08:13:00.617 - [WARNING] task POST None /_gh/ timeout"
连不上Google 获取不了ip

**Comment by sjfirefox** [comment]
直接挂了，一直是等待扫描 IP，建议开启 IPv6。
不管怎么改服务器IP还是改DNS什么的，都不行了。

**Comment by zhouwucheng** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:33 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
