### ISSUE TITLE
能上网了。贴一下方法！！！

### ISSUE THREAD

**Issue by Weijee** [XX-net/XX-Net#12144]
设为 Set Global GAEProxy Proxy
![image](https://user-images.githubusercontent.com/13539500/51581229-26a11f80-1f02-11e9-80d9-2d85206eb05f.png)

**Comment by YuboWang123** [comment]
试过 不行！

**Comment by AnyWAT** [comment]
貌似楼主是没有用代理扩展的浏览器能科学了。其它2个 Global 也可

**Comment by qq61328870** [comment]
非常感谢，按照你的方法我又可以翻墙了
