### ISSUE TITLE
换了Teredo改了文件还算凑乎能用

### ISSUE THREAD

**Issue by Ianwoo777** [XX-net/XX-Net#12157]
{
  "max_scan_ip_thread_num": 50, 
  "GAE_APPIDS": [
  。。。
  ], 
  "max_good_ip_num": 300, //蜜汁空格
  "setting_level": "extreme", 
  "auto_adjust_scan_ip_thread_num": 0
}
Teredo用了这个157.56.106.189

**Comment by AnyWAT** [comment]
"max_scan_ip_thread_num": 50, ——貌似太小？
