### ISSUE TITLE
等待扫描IP，建议开启 IPv6

### ISSUE THREAD

**Issue by min352** [XX-net/XX-Net#12155]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18317
os-system: Windows
os-version: 10.0.18317
os-release: 10
os-detail: Version:10-0; Build:18317; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by min352** [comment]
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 400 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by min352** [comment]
Teredo 隧道	离线（无法连接）

**Comment by min352** [comment]
qualified: True
NAT type: restricted
best server is: win1711.ipv6.microsoft.com.

**Comment by min352** [comment]
服务器 改不了 一直是 best server is: win1711.ipv6.microsoft.com.
