### ISSUE TITLE
等待扫描ipv6，有效ip数为0

### ISSUE THREAD

**Issue by beeblebum** [XX-net/XX-Net#12158]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:200 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

类型                    : enterpriseclient
服务器名称              : 157.56.106.189
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by beeblebum** [comment]
级别设置：极端
链接接收缓冲大小128
自动调整扫描线程：off
最大扫描线程数：100
ip模式：仅ipv6

**Comment by AnyWAT** [comment]
能同时贴出2大项内容，貌似从 #12043 而来：隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 并能扫描出 IP才是真正的好。IPv6 状态(如何开启)，如OK：恭喜，你成功了，随即手动检查 IP；如Fail 或不理想，重复上一步选用其它 IP直到正常、稳定。
1、手动检查 IP 或
2、无需退出再启动程序，或 
3、更换服务器

**Comment by AnyWAT** [comment]
> 最大扫描线程数：100

#12043 或需突破100的测试限制 code\版本号或 default\gae_proxy\local\ config.py https://github.com/XX-net/XX-Net/issues/12043#issuecomment-457047419
