### ISSUE TITLE
显示“”XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。“但是无法翻墙

### ISSUE THREAD

**Issue by wangxiaoxian** [XX-net/XX-Net#12152]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:98 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by wangxiaoxian** [comment]
有时候又显示“系统空闲。 (正常)”

**Comment by wangxiaoxian** [comment]
等待扫描 IP，建议开启 IPv6。

**Comment by AnyWAT** [comment]
> 有时候又显示“系统空闲。 (正常)”
> 等待扫描 IP，建议开启 IPv6。

貌似没关闭某开关？#12043

**Comment by langzc520** [comment]
在公司ipv6，99个ip可以正常科学上网，回到家用瞬间有效ip逐渐降为0，不用正常上网，怎么办呀？

**Comment by AnyWAT** [comment]
> 请教下怎么手动更换服务器？

Win32系统3.13.1隧道简单操作几乎启动即正常稳定 https://github.com/XX-net/XX-Net/issues/12043

**Comment by langzc520** [comment]
> > 请教下怎么手动更换服务器？
> 
> Win32系统3.13.1隧道简单操作几乎启动即正常稳定 #12043

我是win10 最新版 64位的系统，具体怎么操作？

**Comment by AnyWAT** [comment]
> 我是win10 最新版 64位的系统，具体怎么操作？

高抬贵鼠 👉 #12043

**Comment by langzc520** [comment]
> > 我是win10 最新版 64位的系统，具体怎么操作？
> 
> 高抬贵鼠 👉 #12043

懂了，里面写的比较复杂，慢慢学习了

**Comment by AnyWAT** [comment]
> 里面写的比较复杂

复杂？相比至少7-18岁学习，之后才开始“闷声大发财”捞钱钱。。。😂
