### ISSUE TITLE
中央开会了要加高墙，而且以后还会更高。

### ISSUE THREAD

**Issue by xyzde1988** [XX-net/XX-Net#12156]
昨天必应搜索就被墙了，这应该只是个开胃菜。
各位也要提前做好准备了。

**Comment by wang1092791404** [comment]
这墙也是服了

**Comment by xc1988** [comment]
必应也墙啊

**Comment by hujunyao** [comment]
这是要让科研人员 开发一个基于p2p的工具上网呀

**Comment by myjlpt** [comment]
LZ应该驱家做编辑去。这种标题风格如出一辙呀！

**Comment by jzmswe** [comment]
楼主移动网络吧，换DNS即可，有的美国DNS可用。如果是俄罗斯DNS，直接用，完全没问题。缺点就是比移动DNS打开网页慢点。
换可用DNS即可打开必应和别的一些网站。

**Comment by hujunyao** [comment]
> 楼主移动网络吧，换DNS即可，有的美国DNS可用。如果是俄罗斯DNS，直接用，完全没问题。缺点就是比移动DNS打开网页慢点。
> 换可用DNS即可打开必应和别的一些网站。

求操作步骤

**Comment by QGB** [comment]
> 这是要让科研人员 开发一个基于p2p的工具上网呀

bp2p

**Comment by hujunyao** [comment]
> DnsJumper

谢谢 一直都没baidu过 之前用google 不翻用bing 现在bing也死了

**Comment by AnyWAT** [comment]
> DnsJumper

https://github.com/XX-net/XX-Net/issues/12116#issuecomment-455953156

**Comment by iAPPOpen** [comment]
高好啊，高就是离倒不远了，越高越容易推这点物理常识大家都没有吗

**Comment by lefantian** [comment]
放心，离倒不远了

**Comment by weicen** [comment]
还是老老实实用ssr吧，速度还不错

**Comment by jzmswe** [comment]
越来越高，呵呵，人力、物力、财力，如果能做到，早就做了。而且现在贸易战，经济形式难道比往年更好？凡事动动脑子，不要人云亦云，更不要凭空想象。

**Comment by ZOOWRIA** [comment]
> 
> 
> 放心，离倒不远了

放心 没那么容易倒的

**Comment by loy20002000** [comment]
随时准备5个以上的翻墙工具,做中国的技术人员可真累.

**Comment by loy20002000** [comment]
上面有人看不起轮子.说真的,轮子的*无界一点通*真的好用,在低峰段能达到150KB.用户这么多还能达到这个速度,已经很牛逼了.vpn一片一片的倒,轮子还是有一定技术实力的.

这种东西以前我是不屑于用的，最近突然意识到一点，跟共产党讲道德是多余的。百度那么黑，坑钱害命的东西多到数不清，也没见共产党拿他怎么样。

**Comment by loy20002000** [comment]
第1天注册的回复，那么再唠叨两句。以下几个方法可以用必应。

1.修改hosts文件，网络上搜必应的IP地址，文件里有示例，这里就不多说了。

2.现在www2,www4,这俩打头的域名还可以用.只是CN打头和www打头的不能用了.

**Comment by StevenGold** [comment]
越是拼命加高墙，就越是把更多的人变成自己的敌人。自古及今，未有不亡之国，亦无不掘之墓，更没有可以永远加高而不坍塌的墙。王权没有永恒。墙垒得越高，崩塌时摔得越惨！

> > 放心，离倒不远了
> 
> 放心 没那么容易倒的

**Comment by YuboWang123** [comment]
看到拉磨多人跟我一样想法我就放心了

**Comment by JerryBaojin** [comment]
这个月30号，墙就没了

**Comment by ZOOWRIA** [comment]
> 
> 
> 越是拼命加高墙，就越是把更多的人变成自己的敌人。自古及今，未有不亡之国，亦无不掘之墓，更没有可以永远加高而不坍塌的墙。王权没有永恒。墙垒得越高，崩塌时摔得越惨！
> 
> > > 放心，离倒不远了
> > 
> > 
> > 放心 没那么容易倒的

49年到70年代末.........那墙真是历史高峰了, 也没见倒。 

以前能上YOUTUBE TWITTER INSTAGRAM的时候大家觉得正常，后来不能上了不也这么过来了吗 

反正国内有抖音、快手、今日头条 还要翻墙干什么

**Comment by ZOOWRIA** [comment]
> 
> 
> 上面有人看不起轮子.说真的,轮子的_无界一点通_真的好用,在低峰段能达到150KB.用户这么多还能达到这个速度,已经很牛逼了.vpn一片一片的倒,轮子还是有一定技术实力的.
> 
> 这种东西以前我是不屑于用的，最近突然意识到一点，跟共产党讲道德是多余的。百度那么黑，坑钱害命的东西多到数不清，也没见共产党拿他怎么样。

话说自从XX-NET不能用了之后我就是用无界+SWITCH OMEGA..........真的比XX-NET快很多啊......虽然我不喜欢无界那个有点土味的界面

**Comment by Peterpey** [comment]
干脆闭关锁国算了。。。

**Comment by dylanleesky** [comment]
> 越是拼命加高墙，就越是把更多的人变成自己的敌人。自古及今，未有不亡之国，亦无不掘之墓，更没有可以永远加高而不坍塌的墙。王权没有永恒。墙垒得越高，崩塌时摔得越惨！
> 
> > > 放心，离倒不远了
> > 
> > 
> > 放心 没那么容易倒的
就一个紧握军权，就不会倒的，民众再乱，赏一顿枪子过来还乱不？除非外部的国家级军队力量打进来。
看看国内贱民闹事有几个国家妥协的？退役兵一闹立马害怕赶紧处理。
