### ISSUE TITLE
联通gfw升级了，完全扫不到任何ip了

### ISSUE THREAD

**Issue by retmania** [XX-net/XX-Net#12150]
手机移动4g暂时完全没问题，一直100ip

我是电脑直连光猫的，原生ipv6，之前一直稳定100ip，下午突然就不行了

ps:ipv6状态是好的
![qq 20190123210126](https://user-images.githubusercontent.com/29533804/51608336-1e70d080-1f52-11e9-9677-fc4c1243a013.jpg)

**Comment by qushaobo** [comment]
狗日的华为

**Comment by qqgmail** [comment]
V4 V6都是IP，封起来多方便

**Comment by Buccaneer01** [comment]
23日凌晨，早晨甚至还一切正常，23日晚一看，IPV6全部挂了，不管是直接获取还是隧道，全部完蛋草。
凛冬已至

**Comment by zyjia** [comment]
上海联通也是这两天无法使用了

**Comment by lc1838228782** [comment]
山东联通也变0了

**Comment by AnyWAT** [comment]
平时：有效 IP数/总 IP数之比值=1
刚刚，有效 IP逐步在降，比值<0.5，最大扫描线程数从69增大到129，手动检查 IP，比值=1了。嘿嘿嘿
