### ISSUE TITLE
前天开始，一直："仅 IPv6" 不可用，请检查。"已试过很多都不行

### ISSUE THREAD

**Issue by florayym** [XX-net/XX-Net#12151]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:118 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by florayym** [comment]
打扰了，现在好了😂

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:119 ipv4:0 ipv6:16
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:6
scan-ip-thread-num: 50
ip-quality: 2140
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
前天开始，一直："仅 IPv6" 不可用，请检查。"已试过很多都不行 #12043 也试过？
