### ISSUE TITLE
帝都bgp机房貌似已恢复正常

### ISSUE THREAD

**Issue by 253681319** [XX-net/XX-Net#12161]
持续抽风个把月之后 ipv6回到30多个的样子

**Comment by cosmoson** [comment]
同在帝都，握个抓。昨天确实突然自动的就好了，但是今天一早发现又不行了，原生v6不能用，还是显示“等待扫描 IP，建议开启 IPv6。”

**Comment by wang1092791404** [comment]
win10系统正常使用

**Comment by retmania** [comment]
还是不行啊。。。北京联通

**Comment by cosmoson** [comment]
> 还是不行啊。。。北京联通

同样在帝都，和你一样，今天刚试了，还是不行，显示“等待扫描 IP，建议开启 IPv6。”
