### ISSUE TITLE
为什么要逼我用那些不该用的软件？

### ISSUE THREAD

**Issue by loy20002000** [XX-net/XX-Net#12166]

**Comment by mrsoshining** [comment]
ye shi keguan

**Comment by AnyWAT** [comment]
> 有缘分的时候几个小时都是100ip满，没有缘分的时候ipv6测试都没法通过。

Win32系统3.13.1隧道简单操作几乎启动即正常稳定 #12043 （隧道）摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启隧道以来，一直正常一直不用此玩意儿

**Comment by myjlpt** [comment]
舆论的力量真大。我质疑一个问题，你看到墙内消息是正的或反的。无论真假，墙外的就一定是真的吗？
当然墙内的官方真的很能扯谎，没落。

**Comment by 505030475** [comment]
可笑的浮萍，从来只看表象不看实质，你这群白痴让我明白为啥墙必须存在

**Comment by loy20002000** [comment]
舆论的力量真大。我质疑一个问题，你看到墙内消息是正的或反的。无论真假，墙外的就一定是真的吗？
当然墙内的官方真的很能扯谎，没落。



墙外假货多，youtube上90%是假货。我看的是少数真货，如高华，沈志华。

**Comment by loy20002000** [comment]
可笑的浮萍，从来只看表象不看实质，你这群白痴让我明白为啥墙必须存在



_


你能看透实质还来这里?这里是翻墙工具的评论区，能看透的人没有必要用xx。中国的政治薄熙来都看不透，你能？

**Comment by loy20002000** [comment]
啥叫"反动"有没有思考过这个词的意义


_

道者反之动。显然中共不是这个定义。

这个就不多说了，口水。

**Comment by iAPPOpen** [comment]
就像任何药都有副作用一样，墙是党的药而LZ这类人就是这剂药的副作用（将顺共变成反共让活在谎言中不自知的人意识到自己在母体中），而我也是副作用呢，以前那个忠党爱国的好少年一去永不回

**Comment by mercury2015** [comment]
>           舆论的力量真大。我质疑一个问题，你看到墙内消息是正的或反的。无论真假，墙外的就一定是真的吗？
> 当然墙内的官方真的很能扯谎，没落。

墙外不一定是真的，但至少有两方面意见的自由表达，然后可以通过自己的判断来决定对错，墙内只能一种声音，别人教你对错。

**Comment by 53195391** [comment]
唉,人生就像茶几,上面摆满杯具.

**Comment by myjlpt** [comment]
> > ```
> >       舆论的力量真大。我质疑一个问题，你看到墙内消息是正的或反的。无论真假，墙外的就一定是真的吗？
> > ```
> > 当然墙内的官方真的很能扯谎，没落。
> 
> 墙外不一定是真的，但至少有两方面意见的自由表达，然后可以通过自己的判断来决定对错，墙内只能一种声音，别人教你对错。

其实我所讲的这段话并没有讲完，可以引申多种思考。
我多讲一句“做好自己，勿要被（无论是墙内还是墙外）人利用。”

**Comment by hujunyao** [comment]
楼主，无界好用吗？ 之前一直坚持用开源软件，看样子要投降了。 不知道无界浏览器，好用吗，用过的人说一下看看呢？

**Comment by entao** [comment]
你是工程师吗 谁他妈的告诉你的华为手机的后门 傻逼

**Comment by loy20002000** [comment]
楼主，无界好用吗？ 之前一直坚持用开源软件，看样子要投降了。 不知道无界浏览器，好用吗，用过的人说一下看看呢？


_

无界最大的优点是稳定，我说的稳定不是指他速度有多快，我实际测试最快也就200k每秒。无界几乎在任何网络环境下都可以用，并且版本更新的特别快，我知道这个东西是05年的时候，这么多年长城防火墙却拿他一点办法也没有。

免费的VPN是很多的，无界最大的用处不是拿来上网，而是可以用这个梯子找免费的VPN。chrome插件,android官方手机软件商城,火狐狸插件,一搜一大把。

即便是收费的VPN也有很多免费服务，例如帖子里给出的windscribe，每个月有10g的免费流量，并且账号可以反复注册。也就是说流量是无上限的。(但是我并不推荐这样搞，如果这么做的人太多，这个公司限制注册，限制流量对谁都不好)

本来不该在这里讲这些，也是无奈啊。突然想起一句电影台词:我们的政府就是限制合法，保护非法。xx这种人畜无害的被搞得奄奄一息，却对轮子一点办法也没有。

**Comment by relaxya** [comment]
这不是广告帖么，怎么还有人在认真回复。。

**Comment by hehh2001** [comment]
美的灵魂是关不住的！好文章！！！！！！！！！！！！！！！！

**Comment by fengjie2018** [comment]
拙劣的广告。
我翻墙出去用Google搜索自由门和无界的官网下载了它的软件。
用卡巴斯基全方位安全软件扫描，均报病毒。
如果说360等大陆杀软不值得信任，那么卡巴斯基呢？
抛开一切政治的和意识形态的东西，这两个软件本身就有问题！

**Comment by AnyWAT** [comment]
貌似：报毒未必真有毒，不报未必真无毒？

**Comment by fengjie2018** [comment]
> 貌似：报毒未必真有毒，不报未必真无毒？

其中的风险绝不是一句未必就能掩盖的，自己的电脑中毒事小，成为别人向大陆渗透的跳板事大！
我应该相信楼猪的推荐？
还是相信自己的政府、相信著名的第三方杀毒软件？
显然后者更令人信任！

**Comment by loy20002000** [comment]
其中的风险绝不是一句未必就能掩盖的，自己的电脑中毒事小，成为别人向大陆渗透的跳板事大！
我应该相信楼猪的推荐？
还是相信自己的政府、相信著名的第三方杀毒软件？
显然后者更令人信任！

----------

这俩软件我没有用杀毒软件扫过，我电脑里只有360。我怕360上报，所以没有测试。不放心用手机版即可，安卓版是需要批准权限的，肯定安全。

用杀毒软件扫结论是病毒，这并不意外，也不能说明问题。卡巴斯基的误报率是所有杀毒软件中最高的，至少05-06年的时候是这么公认的，现在我电脑99%的情况是裸奔所以不太清楚。只要是封装过的有壳的，杀毒软件可能误判成危险程序，例如360可以把cracktro.com的demo判定成Trojan或Virus。

无界、自由门是老牌子了。如果有安全风险在外网怎么掩盖？我不是说这两货肯定安全，以常识来判断换你是轮子会把自己的翻墙工具安插木马或工具本身就是病毒么？

**Comment by Peytonlan** [comment]
支持下, 虽然对楼主有些措辞不太认可

在线杀毒
https://www.virustotal.com 支持url直接上传
http://www.virscan.org
虽然有个别软件报毒, 但卡巴斯基, 360都没报毒

始终无法理解, 为什么有些人可以为了一点蝇头小利, 出卖人性, 舍弃良知

**Comment by myjlpt** [comment]
@fengjie2018
轮子的东西，备用放一个还行吧。至于你说的报毒。自由门我用过，也一直备着，。怎么说呢，其实也不算毒，（如果精神上你抗拒，那也许它算毒）；因为这货有劫持动作，运行就劫持。那网络劫持似乎很多杀软报毒的。

**Comment by Emeryout19** [comment]
不用理會5毛，等趙太爺發不出工資的時候他們就會集體討薪然後親口嘗嘗社會主義鐵拳的味道

5毛的領導們以實際行動愛著美國，轉移資產妻女，孟晚舟一家在美加買房定居，是真正的裏通外國

封鎖信息，高壓統治的唯一目的是更加方便的控制和洗劫人民，他們早都留好退路，風向有變立馬逃跑，
留下受苦的是老百姓

他們不能代表中國，他們是中國人民的敵人

**Comment by hujunyao** [comment]
you can run linux version ul in a machine (as limited user) , then all you team members can use google by this proxy.  You DONOT need worry about virus . It works.

**Comment by duabaoji** [comment]
你既然那么看重党，也该去看看党在交接班时期出了什么事。高平陵了解一下。

**Comment by duabaoji** [comment]
@myjlpt 党是中共。形容修正派政变好比高平陵一般。现如今不都称二共么。

**Comment by dylanleesky** [comment]
我在10年左右会的翻墙，当时的原因很简单也很搞笑，玩的游戏下作弊器，国内论坛都没有，只有国外一个论坛有，但是那个论坛被墙了，于是，，，，我学会了翻墙。。。。

**Comment by dylanleesky** [comment]
我看到楼上竟然有人相信ZF。。。哈哈，笑死我了、。

**Comment by dylanleesky** [comment]
> 你是工程师吗 谁他妈的告诉你的华为手机的后门 傻逼，你动机是什么，找你的美爹去吧

360和GFW有合作，华为内置杀毒是360.按照360的尿性。不上传你点啥东西你信么？多了不说，app列表会上传的吧?app使用频率必然也会上传。还可以美其名曰收集使用习惯给你匹配更好的推荐。比如某毒老大的话。用户都是心甘情愿分享这些隐私数据的。

还有啊，有人指责华为怎样就一定是亲美么？按照你的逻辑，是不是你家人杀人了，警察来抓是不是你就认为警察是在跪舔邪恶的一方比如国家？呵呵。

**Comment by fengjie2018** [comment]
诸位听我一言，不要说我是什么五毛，我只是提出自己的建议。
况且，一上来就给我扣个五毛的帽子，不符合自由，不符合民主，不符合人权。
许你们说，不许我说啊？
不要相信在这里的人（包括我），因为“我是五毛”，因为这里人员太复杂。既然有我这种五毛，自然也有特务，间谍。
卡巴斯基误报高不高，你自己去百度，去Google。
不相信国内的杀软，也没关系。
反正国外杀软那么多，每一个都提供免费试用。卡巴斯基也能免费试用三十天，足够你去验证谁说的是真话。
你去比对，去探寻，哪个杀软值得信赖，然后去官网下载一个。
无界自由门什么的，下载下来用你的杀软扫一扫。
一件事情是真是假，你自己要去验证，去维基百科，那里的记载可靠一些。

我再补充一句，如果中共是邪灵，如果政府不能信任，你怎么会安安稳稳活到今天，你怎么会有机会在这里发评论，看撕逼？你会饱受迫害！你会吃不饱饭，你将陷入战争，妻离子散，家破人亡！我中国有没有在发展，有没有在进步，你真的看不到，感觉不到吗！

报毒是正常的？是杀毒软件和GFW合作？
屁话！！！
betternet  报不报毒？
windscribe  报不报毒？
hotspot  报不报毒？

hide me  报不报毒？
xxnet 报不报毒？
express vpn  报不报毒？
蓝灯、天行 报不报毒？

相反
无界/自由门呢？

请你不要只听人说，自己按我说的，找国内杀软也好，找国外试用版杀软也好，
一定要自己去验证一下！
一定要自己去验证一下！
一定要自己去验证一下！

如果我上边这些话还不能点醒你，我很遗憾。
绑定的邮箱老给我发这些破评论，真G2烦，这是我最后一次发言，你们好自为之吧。

**Comment by loy20002000** [comment]
@fengjie2018

诸位听我一言，不要说我是什么五毛，我只是提出自己的建议。
况且，一上来就给我扣个五毛的帽子，不符合自由，不符合民主，不符合人权。
许你们说，不许我说啊？

---------

我用在线查杀检测的结果如下（virustotal），ui、自由门、xx最新版都是检测压缩包，由于我的浏览器太老就不贴图了（我也不知道怎么贴）：

xx：

Antiy-AVL

VCS[Warning]/Email.Agent.1

Qihoo-360

virus.vbs.qexvmc.1075

在线360的检测结果与我机器上的360一致，只要用360扫全盘XX一定被报毒。如果有兴趣，我可以去Cracktro找几个肯定不是毒但360检测为Trojan的样本给你。




自由门：

DrWeb

Trojan.MulDrop7.64942

其他的在线工具都显示clean。




警告最多的是无界：

omodo

ApplicUnwnt@#1edp9906xa135

Cyren

W32/Trojan.YVKK-2398

DrWeb

Tool.UltraSurf.17

ESET-NOD32

a variant of Win32/UltraReach.AG potentially unsafe

Fortinet

Riskware/TinyDL

Ikarus

PUA.UltraReach

K7AntiVirus

Unwanted-Program ( 005025f81 )

K7GW

Unwanted-Program ( 005025f81 )

Kaspersky

not-a-virus:RiskTool.Win32.UltraSurf.zk

McAfee

Artemis!2E98FD31036A

NANO-Antivirus

Riskware.Win32.UltraSurf.fmiefw

Rising

Trojan.Occamy!8.F1CD/N3#94% (RDM+:cmRtazqtxeMR3KFVC+oh0d2cmaUR)

Sophos AV

Mal/TinyDL-T

TrendMicro-HouseCall

TROJ_GEN.R002H0CAI19

VBA32

BScope.Trojan.Downloader

ZoneAlarm

not-a-virus:RiskTool.Win32.UltraSurf.zk

带领360在3大评级进入前三的Bitdefender显示Clean。Kaspersky的评测是not-a-virus，但提示有风险。无界是否有安全风险是老生常谈的话题了，这帮开发者也一直在抗议。这个不是我能回答的。


-------------

你脑补的东西过多。

【我再补充一句，如果中共是邪灵，如果政府不能信任，你怎么会安安稳稳活到今天，你怎么会有机会在这里发评论，看撕逼？你会饱受迫害！你会吃不饱饭，你将陷入战争，妻离子散，家破人亡！我中国有没有在发展，有没有在进步，你真的看不到，感觉不到吗！】

你这里提到的这段我部分经历过，因为政治问题我没有读过大学。我父母和爷爷辈全部经历过，我爷爷被饿死，二姑妈被冷枪打死，三姑爹因为83严打的时候打麻将进了监狱就再也没出来。我母亲的奶奶被饿死，外公差点在文革时期被打死，大舅舅被领导陷害只能跟智力残障人士结婚否则就是10年牢狱。我父亲下岗，因为领导用他们的身份证贷款（1995年每人2万人民币），父亲不服就被踢出去了，连他的小徒弟都被踢出去。

我讲这么多自家事儿，你满意了么？

**Comment by loy20002000** [comment]
360和GFW有合作，华为内置杀毒是360.按照360的尿性。不上传你点啥东西你信么？多了不说，app列表会上传的吧?app使用频率必然也会上传。还可以美其名曰收集使用习惯给你匹配更好的推荐。比如某毒老大的话。用户都是心甘情愿分享这些隐私数据的。

还有啊，有人指责华为怎样就一定是亲美么？按照你的逻辑，是不是你家人杀人了，警察来抓是不是你就认为警察是在跪舔邪恶的一方比如国家？呵呵。

------

这里来一个比较拧巴的评论。

虽然华为有问题，但不能否认它依然是中国技术实力最雄厚的IT企业，也是唯一一家海外盈利能超过国内盈利的IT企业。所以美帝只怼他，对BAT压根没兴趣，因为这三家美帝全部放行他们也走不出去，典型的政策型企业。

讲个趣事，我知道的一家日企中了百度的招。浏览器被劫持还装了IE插件，我记得是hao123.com的主页（百度5年多没用过了，记不清了），PC里的百度流氓软件怎么也卸不掉。最搞的是这家会社压根不知道是什么时候中招的，因为他们内部是很严格的，不允许下载外部程序的。企业内技术人员搞了很久也没解决。24h后一个中国临时工见状自告奋勇解决这个难题，日本技术男一脸鄙视，因为这哥们N1都没过（日语水平考试），也没念过大学。事实是他的确解决了这个难题，用的方法是装360，360把百度杀得渣都不剩。因为这个事儿还得了5万日元的奖励。

百度的windows日语输入法、安卓日语输入法真心好用。但是呀，因为百度在日本名声太臭，用的人基本只局限于中国人。同样的腾讯、阿里在日本也是名声很差。

说这些我想表达的是，虽然bat市值很高，但是他们没有核心的竞争力。而华为至少是一家有核心技术，在海外有市场的公司。华为手机的监控行为虽然我很反感，但我并不希望它沉沦。因为华为如果倒了，中国就没有杀得出去的IT公司了。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12166#issuecomment-459958766
> 因为政治问题我没有读过大学。

https://github.com/XX-net/XX-Net/issues/12166#issuecomment-459964434
> 也没念过大学。

貌似同一人？

**Comment by hujunyao** [comment]
看了上面的评论 我问一个问题  我们使用的是linux版本的 在受限用户下的无界提供给研究小组上 Google，   这样就算这个软件有病毒，应该也没有什么安全风险吧？

**Comment by loy20002000** [comment]
#12166 (comment)

    因为政治问题我没有读过大学。

#12166 (comment)

    也没念过大学。

貌似同一人？


--------

不是的。我没有在日企用360的勇气。万一老问题解决了新问题出现，我就麻烦了。

这是一个还在读语言学校的小伙子，他的具体情况我也不太了解，只知道进入这家会社打工是家里亲戚帮忙。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/52164973-44a62580-2735-11e9-8646-89c078739ac1.png)
![image](https://user-images.githubusercontent.com/37962734/52164976-5a1b4f80-2735-11e9-9fcb-84afd2bd1fec.png)

**Comment by loy20002000** [comment]
看了上面的评论 我问一个问题 我们使用的是linux版本的 在受限用户下的无界提供给研究小组上 Google， 这样就算这个软件有病毒，应该也没有什么安全风险吧？

----------

说点我的看法，不一定对。

普通情况都是https连接吧，VPN一类的通道对加密数据没影响。加密是本地浏览器完成的，通过证书提供的秘钥，中间环节是不影响私密性的。这是非对称加密的基本特性。

当然本地安全性就不晓得了。windows受限用户或linux受限用户应该差不多，我认为是安全的。

**Comment by loy20002000** [comment]
@anywat

这里讲的就有点扯了。华为手机虽然核心部件基本靠进口，但是网络硬件设备这一块还是有核心技术的。曾经有人给我讲解过，我不是专业人士记不清了。这些东西网络上应该可以搜索到的。

**Comment by loy20002000** [comment]
中国共産党って本当にすごいね､中国人民って全部裏切り者と認定でもいいかも

党の敵はアメリカではなくて、人民しかいないと思ってる

でも残念だな、本物の裏切り者はほとんど党員じゃない?例えば王明とか張国焘とか趫紫陽とかの色々な老党員だった

ソ連の解体の原因って一体何ですか?高級官僚の裏切りだから

昆明の三零一事件について民間人の説が党内闘争もあって、なぜ徹底的な調査がなかったの?

小売の商売人って街並みの露店経営は違法と言われてるのに、Maria病院とか博愛病院とかの違法医療行為ってぜんぜん大丈夫と黙認してた

最も面白い事件といえば2006年の漢芯事件であり、数億人民円の詐欺行為なのに結局無罪に済んだ。およそ3ヶ月前、ある海外貿易の庶民って、ただ税の問題だけに10年の懲役と判決された。

もう21世紀なのに、中国の政治生態が満清のように続いていく。

今中国語の入力アプリがないから、日本語の言葉にのみを使えたけど

**Comment by loy20002000** [comment]
对无界和自由门有疑虑的同学，这里给大家通报一个新消息。

最近因为搜狗的流氓行为导致系统崩溃，重装后做了360的全盘扫描（离线，病毒库版本2019.2.2，杀毒引擎为最新版本）。无界u1901a、u1901，自由门fg764p、fg765p，都没有报毒。

**Comment by AnShengqiang** [comment]
拙劣的广告，这个人还说几年前就用xx-net，然而他的账号都是新注册，专门用来黑的。去他个人主页看看就知道了。

**Comment by AnyWAT** [comment]
https://pbs.twimg.com/media/DziZ9txUcAAMe0G.jpg 
![image](https://user-images.githubusercontent.com/37962734/52902085-b65a9500-3246-11e9-825e-752a1062c1c4.png)

**Comment by loy20002000** [comment]
@iAPPOpen

现在才看见你的回复居然改得这么长。

墙这种东西只能挡住不需要访问外网的人，有这个需求的人是挡不住的。例如自然杂志的官网，会自动推荐很多VPN给你。

实际上中共最大的威胁是主席台那些人，老百姓能干什么。每一次政策失误就害死一批人，没见谁起来造反。最典型的例子就是苏联的解体，没有戈尔巴乔夫和叶利钦的努力，老百姓什么也做不了。

**Comment by AnyWAT** [comment]
> 老百姓什么也做不了

貌似有图：许多老娘在街上劝说携木仓的孩子回家？

**Comment by loy20002000** [comment]
@anywat

实际上自打北宋以后，中央集权几乎是不可颠覆的。中共玩儿的不过是老祖宗玩剩下的。

北宋是宋徽宗推翻的，南宋是绥靖政策把自己搞翻的。明朝亡于东林党作乱，加上遇上一个白痴皇帝。清朝亡于袁世凯造反。

我党的宣传高估了人民的作用。64事件的时候都右成什么样子，小平同志一声令下问题解决。

**Comment by AnShengqiang** [comment]
这issue删了吧，开issue的这个人是刚建的小号，应该是境外势力专门来做思想渗透的。不要让政治污染了技术。

**Comment by loy20002000** [comment]
这issue删了吧，开issue的这个人是刚建的小号，应该是境外势力专门来做思想渗透的。不要让政治污染了技术。

-一-

翻墙软件区讲思想渗透，照你的逻辑xx就应该被抓起来。他还是做免费工具的呢。

**Comment by CharliesZhang** [comment]
无界自由门高清看youtube？？简直就是放屁！！！

**Comment by Zhicimmmm** [comment]
> 就像任何药都有副作用一样，墙是党的药而LZ这类人就是这剂药的副作用（这剂药其实只能让未“病变”的细胞不容易病变，而对已经病变的无任何作用，副作用就是将一些本来“正常”的甚至“有益”的细胞推向反面，将顺共变成反共让活在谎言中不自知的人意识到自己在母体中），而我也是副作用呢（此朝人没有民权导致一般人对政治没兴趣就像明天什么天气我们没有决定权我们的权利就只是可以在前一天听听天气预报（两会之类）而已，我以前自然也对什么政治国家这些半点兴趣没有，后来我的Google和YouTube这些常用网站不能用了渐渐知道了墙也知道了一些翻墙工具，翻墙工具的论坛中常常有人会“发牢骚”爆一些黑历史，如果一个人告诉你你此前所知的一切都是假的你自然会被吸引， 于是看了一些东西，三观十级地震，然后就变成了个可以说是反共的人吧，**所以真有意思，墙非但没有阻挡我看到那些黑历史反而是墙引导我看到了那些黑历史，如果没有墙我一辈子可能都不会看到这些**，所以是典型的副作用吧。不过看了很多真实历史之后**我深深的理解了为什么要建立墙，因为党的黑历史实在是太多太多了**，如果这些东西不拦着让国民知道了，一天都不可能容忍这样的政府存在），以前那个忠党爱国的好少年一去永不回

所以人民政府成立没有正当性，资产阶级政府合理上台是吧，您可真能代表14亿人了捏。

**Comment by Zhicimmmm** [comment]
> 不用理會5毛，等趙太爺發不出工資的時候他們就會集體討薪然後親口嘗嘗社會主義鐵拳的味道
> 
> 5毛的領導們以實際行動愛著美國，轉移資產妻女，孟晚舟一家在美加買房定居，是真正的裏通外國
> 
> 封鎖信息，高壓統治的唯一目的是更加方便的控制和洗劫人民，他們早都留好退路，風向有變立馬逃跑， 留下受苦的是老百姓
> 
> 他們不能代表中國，他們是中國人民的敵人

您可真能代表14亿中国人了捏
