### ISSUE TITLE
换家里wifi之后有效ipv6一直为0，手机热点正常。

### ISSUE THREAD

**Issue by simklot** [XX-net/XX-Net#12162]
已经尝试过[12043](https://github.com/XX-net/XX-Net/issues/12043)里面的所有服务器，均无效。

C:\windows\system32>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 157.56.149.60
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

手机热点：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:300 ipv4:0 ipv6:285
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:0 h2:12
scan-ip-thread-num: 20
ip-quality: 449
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

换家里wifi之后：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:300 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by darkforce82** [comment]
问题应该是出在ISP身上，我也再研究这问题 #12163

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 20 与 gws-ip-num: total:300 严重不匹配！还不知是否关闭了某开关？https://github.com/XX-net/XX-Net/issues/12043#issuecomment-457047419
