### ISSUE TITLE
！退钱！网速极慢，总是掉线，每次掉线都需要重启，有什么用？

### ISSUE THREAD

**Issue by DuCheng2018** [XX-net/XX-Net#12169]
最新的版本

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11892 X-Tunnel 正常的前提。。。
Win32系统3.13.1隧道简单操作几乎启动即正常稳定 #12043

**Comment by DuCheng2018** [comment]
> #11892 X-Tunnel 正常的前提。。。
> Win32系统3.13.1隧道简单操作几乎启动即正常稳定 #12043

WTF？并没什么用，你这个东西就是不稳定，

**Comment by cupbk** [comment]
既然你愿意花钱，可以自己搭建vps+ss，我现在就这样每个月花几刀买稳定，比现在的xxnet稳定得多。
xxnet是挺好的，但目前来看不太可能会恢复到以前速度，有翻墙需要的还是找个后备用吧。

**Comment by DuCheng2018** [comment]
> > WTF？并没什么用，你这个东西就是不稳定，
> 
> 代码老白的纯用户一枚。。。#12043 我的这个东西可以说是很稳定，只是“你这个东西就是不稳定”😂
> ![default](https://user-images.githubusercontent.com/37962734/51787878-09927800-21b2-11e9-8672-9c5616d8b024.png)

不管你是不是用户，总提示data not enough，什么鬼东西，太垃圾

**Comment by DuCheng2018** [comment]
![image](https://user-images.githubusercontent.com/33454805/51801255-314b1400-2276-11e9-860e-fb072516744c.png)

**Comment by gushaonan1991** [comment]
> 既然你愿意花钱，可以自己搭建vps+ss，我现在就这样每个月花几刀买稳定，比现在的xxnet稳定得多。
> xxnet是挺好的，但目前来看不太可能会恢复到以前速度，有翻墙需要的还是找个后备用吧。

请问您用的是哪家的 VPS？我用的 Vultr，不是很稳定，有推荐的么？

**Comment by cupbk** [comment]
我也是用vultr，你选哪个节点？https://www.vultr.com/faq/ 测速后选择适合你自己的

**Comment by gushaonan1991** [comment]
> 我也是用vultr，你选哪个节点？移动或者联通用户选美国节点比较好，电信比较麻烦要多选几个节点测试https://www.vultr.com/faq/ 测速后选择适合你自己的

嗯嗯，好的，多谢。我部署的日本的节点，看来要换一换了。

**Comment by gibwise** [comment]
我用的这个 VIP通道免费试用 https://pro.eimi.me/auth/register?code=31lCzXGMMVcViZeZVpTKnuKBiyi6pvWT

**Comment by bibichuan** [comment]
谷歌云是不是好点，就是感觉有点贵了。

**Comment by SeaHOH** [comment]
想退就发邮件问呗
