### ISSUE TITLE
捐贈了3个appid后發現...原來沒辦法收到流量啊.._T_T

### ISSUE THREAD

**Issue by rylkyo** [XX-net/XX-Net#12165]
最近部署APPID不成功.想用下x tunnel...然後發現只有170MB了...T_T...淚崩

**Comment by loy20002000** [comment]
就当做善事吧。APPID这种东西又不要钱，想部属多少都行呀。

x tunnel最好用收费的。捐赠得的流量太少了，根本不够用。

说实话作者的收费已经很良心了。很难找到比这个更便宜的收费服务了。

**Comment by wszgrcy** [comment]
想充值.结果发现充4.5刀真要跑境外充....要是能做微信或支付宝就好了.....真心懒得捣鼓这个东西

**Comment by AnyWAT** [comment]
> ....要是能做微信或支付宝就好了.....

安全！安全！！安全！！！

**Comment by ncmon** [comment]
多等等在发个邮件 我捐赠后等了一个月也给我充值上了

**Comment by loy20002000** [comment]
想充值.结果发现充4.5刀真要跑境外充....要是能做微信或支付宝就好了.....真心懒得捣鼓这个东西

---

如果有比特币就方便了。当然这个只是美好的愿景。
