### ISSUE TITLE
一切正常

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#12164]
XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 282

**Comment by kelvin219** [comment]
原声V6?DNS?设置参数？

**Comment by earthGavinLee** [comment]
应该是改巨硬服务器了。扫描一开。明天就会被BAN

**Comment by cosmoson** [comment]
坐标帝都，昨天原生v6突然好了，就像楼主这样一样。但今天一早发现又不行了，恢复了“等待扫描 IP，建议开启 IPv6。”状态

**Comment by aeguicai** [comment]
我也好了

**Comment by epsilono1** [comment]
我也好了，终于不用看“等待扫描 IP，建议开启 IPv6”的嘴脸了，哈哈

**Comment by cosmoson** [comment]
> 我也好了，终于不用看“等待扫描 IP，建议开启 IPv6”的嘴脸了，哈哈

楼上好了的兄弟是哪里的？坐标帝都？我今天刚试了还是不行，显示 “等待扫描 IP，建议开启 IPv6。”

**Comment by AnyWAT** [comment]
> 应该是改巨硬服务器了。扫描一开。明天就会被BAN

https://github.com/XX-net/XX-Net/issues/12179#issuecomment-458387241
