### ISSUE TITLE
Google Play (网页版) 部分网页无法正常显示

### ISSUE THREAD

**Issue by ccyr119** [XX-net/XX-Net#12168]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？ 3.13.1

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？ 是的

* 是否以相关关键词搜索过类似 issues？ 是的，貌似都没有解决。

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

可以正常显示的URL：
https://play.google.com/store/apps
https://play.google.com/store/apps/details?id=com.rovio.dream   （类似的具体的某个App的详情页都可以访问）
https://play.google.com/apps/publish

不正常显示的URL：
提示 ”抱歉，出现错误。请稍后重试。”
底部是Google Play的搜索框
https://play.google.com/apps
https://play.google.com/store
https://play.google.com/store/apps/category/GAME_STRATEGY   （类似的分类URL都不能访问）

**Comment by Alobe007** [comment]
同。应该不是XX的问题。
