### ISSUE TITLE
连接尚未建立怎么办？

### ISSUE THREAD

**Issue by lsl312** [XX-net/XX-Net#12160]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:79 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by lsl312** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : 8888
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by AnyWAT** [comment]
状态 : qualified ——已连接
ipv6-status: OK —— #12043 摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 并能扫描出 IP才是真正的好。IPv6 状态(如何开启)，如OK：恭喜，你成功了，随即手动检查 IP；如Fail 或不理想，重复上一步选用其它 IP直到正常、稳定。
1、手动检查 IP 或
2、无需退出再启动程序，或
3、更换服务器

**Comment by AnyWAT** [comment]
> 类型 : enterpriseclient (Group Policy)
> 服务器名称 : 83.170.6.76
> 客户端刷新间隔 : 30 秒
> 客户端端口 : 8888

完整的 IPv6 组策略是这样的——
类型 : enterpriseclient (Group Policy)
服务器名称 : 83.170.6.76 (Group Policy)
客户端刷新间隔 : 30 秒 (Group Policy)
客户端端口 : 8888 (Group Policy)
#12043 摒弃（并不完整的） IPv6 组策略法

**Comment by xylona1900** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——服务器陷阱！#12043

**Comment by xylona1900** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com. ——（几乎没正常的时候的）服务器陷阱！#12043

转到#12043后，
（一）准备工作的第5条，我在桌面建立xxx.bat隧道窗口，但是双击却打不开啊，所以我也没法实时查看隧道情况；
第6条，
λ ping teredo.remlab.net

正在 Ping teredo.remlab.net [83.170.6.76] 具有 32 字节的数据:
来自 83.170.6.76 的回复: 字节=32 时间=253ms TTL=46
来自 83.170.6.76 的回复: 字节=32 时间=252ms TTL=46
来自 83.170.6.76 的回复: 字节=32 时间=252ms TTL=46
来自 83.170.6.76 的回复: 字节=32 时间=251ms TTL=46

83.170.6.76 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 251ms，最长 = 253ms，平均 = 252ms

然后我略过了第7条到了操作部分。
（二）操作第1条，
λ netsh int ipv6 set teredo enterpriseclient teredo.remlab.net
确定。

我这样操作是正确的吗？控制页状态还是Fail，那么下一步我是继续ping可用ip和隧道吗？

**Comment by AnyWAT** [comment]
> 在桌面建立xxx.bat隧道窗口，但是双击却打不开啊

稀奇古怪。。。莫非文件后缀名不对？

> 下一步我是继续ping可用ip和隧道吗？

摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 并能扫描出 IP才是真正的好。。。IPv6 状态(如何开启)，如OK：恭喜，你成功了，随即手动检查 IP；如Fail 或不理想，重复上一步选用其它 IP直到正常、稳定。
