### ISSUE TITLE
https://scholar.google.com/ 谷歌学术无法访问

### ISSUE THREAD

**Issue by lee218** [XX-net/XX-Net#12178]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？
1 已经查询过相关问题，比如
https://github.com/XndroidDev/Xndroid/issues/191#issuecomment-449705387 
2 大概一两个月之前还能正常访问

**Comment by shpherd** [comment]
发帖前先在网站里查下。几年前此问题就回答了，XXnet受限，可访问镜像。

**Comment by loy20002000** [comment]
这个问题是无解的，虽然我们用的是Google的服务器访问Google的服务，但是Google方却把这当成拒绝服务攻击来处理。17年的时候上YouTube，有几个月连搜索都不能用。有一段时间甚至连Google搜索都不能用。

出现这个问题的原因是你使用的服务器与其他人高度重合，加之xx每三分钟就要切换一次IP，Google方就当成攻击来处理了。解决的方法也很简单，xx搜索的IP段避开热门服务器也就行了。

**Comment by SeaHOH** [comment]
如果**只是使用谷歌**，可以用我写的工具，现在可用 IP 特别多。

**Comment by shpherd** [comment]
> 如果**只是使用谷歌**，可以用我写的工具，现在可用 IP 特别多。

到 https://github.com/phuslu/goproxy-ci/releases/latest 下载 goproxy-gae-rXX.zip 服务端部署文件。
该链接打不开

**Comment by lee218** [comment]
了解，谢谢LS各位

**Comment by joychase** [comment]
试试ssr吧 注册送流量 https://www.ppyun.ml/auth/register?code=GjU2
https://www.1080.cloud/register?aff=12435
