### ISSUE TITLE
改完服务器，终于能用了，但有效ip一直不到10个，这个是怎么回事啊。

### ISSUE THREAD

**Issue by gang0122** [XX-net/XX-Net#12174]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by gang0122** [comment]
![1](https://user-images.githubusercontent.com/19601054/51795744-e30d2500-2223-11e9-8fa4-741581e960d5.JPG)
![2](https://user-images.githubusercontent.com/19601054/51795745-e6a0ac00-2223-11e9-8cfb-476119646498.JPG)

**Comment by gang0122** [comment]
![3](https://user-images.githubusercontent.com/19601054/51795772-0e900f80-2224-11e9-9315-40fbc2ca0078.JPG)
又出现了ipv6状态：fail 但还能用的情况。。。

**Comment by AnyWAT** [comment]
2楼：有效 IP及连接池太少，延时较大。或是最大扫描线程数20较小、甚至没关闭某开关的锅？ #12043 
关闭“自动调整扫描线程数”，最大扫描线程数以能自动维持：有效 IP数/总 IP数之比值=1 时为最小值。可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。

**Comment by loy20002000** [comment]
如果有原生6还是这样基本无解。如果用隧道的话，有人提供了一个思路，不断ping teredo服务器使得它一直激活。ipv4环境的问题是隧道被干扰，所以有效ip被错误的杀掉，实际上有效ip是很多很多的。

**Comment by gang0122** [comment]
> 如果有原生6还是这样基本无解。如果用隧道的话，有人提供了一个思路，不断ping teredo服务器使得它一直激活。ipv4环境的问题是隧道被干扰，所以有效ip被错误的杀掉，实际上有效ip是很多很多的。

我就是原生用不了有转回隧道的。。。（天津联通）
