### ISSUE TITLE
大家的xx还能用吗 我电信好像已经不行了 

### ISSUE THREAD

**Issue by entao** [XX-net/XX-Net#12177]
大家的xx还能用吗 我电信好像已经不行了 ，打开用很短时间一会就没有，换服务器也是一会，等等彻底不能用，已经没法用了。

**Comment by loy20002000** [comment]
肯定可以用。不过这里有一个问题，能不能一直稳定就难说了。

我昨天用了下手机版，有效IP原本是0，一分钟就到100了。不过这种好日子不常有。

**Comment by inkforest** [comment]
电信时好时坏吧。不用GAE那个端口的时候还能扫到80+的ip，一切到那个端口上谷歌就会马上掉到0，心累了

**Comment by gibwise** [comment]
可以试试下面的免费机场 注册全部送流量
https://web.ssvss.xyz/register?aff=14332
https://ssrbank.com/register?aff=24539
http://www.qinglouvpn.com/auth/register?code=FXFX
https://pro.eimi.me/auth/register?code=31lCzXGMMVcViZeZVpTKnuKBiyi6pvWT
https://www.ppyun.ml/auth/register?code=GjU2
https://lisuanlaoji.co/auth/register?code=Xd3H
https://eesile.org/auth/register?code=invited_by_1548586586YH
https://reg.mimi.ooo/MvMu5UTHXRo9OYmRRECMvJX8reSrSVPm
https://lostcloud.org/auth/register?code=R54CzG08frL04J5v
