### ISSUE TITLE
昨天还好 今天一直连不上

### ISSUE THREAD

**Issue by brandy1225** [XX-net/XX-Net#12179]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:98 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
+1 抑或 -1 ？

XX-Net Status:

sys-platform: x86, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:224 ipv4:0 ipv6:224
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:0 h2:55
scan-ip-thread-num: 139
ip-quality: 302
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gang0122** [comment]
+1

**Comment by AnyWAT** [comment]
> 客户端刷新间隔 有点长,我们都是30秒,降低刷新率看一下

以前一直30-60以内，现在测试中：貌似没看出任何不良影响

**Comment by AnyWAT** [comment]
> 为什么你是NAT : symmetric (address)，我们的是NAT : restricted呢

系统自动而来的：157.56.149.60 就是 symmetric (address)，157.56.106.189 或 217.17.192.217 就是 symmetric (port)
又没看到你等的  netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by joychase** [comment]
可以试试这个注册送流量https://www.1080.cloud/register?aff=12435

**Comment by joychase** [comment]
还有这个也是免费https://www.ppyun.ml/auth/register?code=GjU2
