### ISSUE TITLE
"仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by aliasch** [XX-net/XX-Net#12183]
之前在学校应该是默认有IPV6，一切正常，回家之后，就不正常了。
查看讨论组的主题，跟着操作，也无法解决问题。（例如：如何开启IPV6）
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6

看到AnyWat说的做法

贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）
--
结果如下：

Microsoft Windows [版本 10.0.17763.253]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.0.106:58074
外部 NAT 映射    : 223.74.49.218:8684

C:\WINDOWS\system32>

诊断信息如下：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

请教该如何操作，详细一点，不太明白原理，谢谢。

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——（几乎没有正常的时候的）服务器陷阱！
本地映射 : -----
外部 NAT 映射 : -----隐私！
scan-ip-thread-num: 10 ——太小，严重怀疑更没关闭某开关 #12043 
> 请教该如何操作，详细一点，不太明白原理，谢谢。

千万别与代码老白说：该如何操作，详细一点，不太明白原理，谢谢。

**Comment by aliasch** [comment]
https://github.com/XX-net/XX-Net/issues/10282
使用了上述页面的IPV6配置工具，启用IPV6之后，算正常了。不过不太稳定。
感谢。
