### ISSUE TITLE
我看了下日志，结果很蛋疼

### ISSUE THREAD

**Issue by qtiuto** [XX-net/XX-Net#12182]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
xxnet需要下载ip列表
然而ip列表是从谷歌下的
然后谷歌被墙了，然后无法下载ip列表
然后一直报no enough ip
一直检查原有的死ip

**除非一开始就有可用的ip,或者能上谷歌，否则就是个死循环**
谁提供下ip列表？

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by AnyWAT** [comment]
#12043 https://github.com/XX-net/XX-Net/issues/12179#issuecomment-458387241

**Comment by gibwise** [comment]
可以试试这个 注册试用高速通道https://pro.eimi.me/auth/register?code=31lCzXGMMVcViZeZVpTKnuKBiyi6pvWT

**Comment by loy20002000** [comment]
anywat说的对。你没用过xx吧，它提供受限制的Google project ID，只是不能看视频和刷图片而已。

墙变高了，这才是原因呀。

**Comment by AnyWAT** [comment]
> 墙变高了

没感觉到，依旧正常、稳定。
