### ISSUE TITLE
原生ipv6已经完全沦陷

### ISSUE THREAD

**Issue by smaller09** [XX-net/XX-Net#12189]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

原生ipv6已经完全沦陷
昨晚开始，导入的400多个IP完全失效
坐标020，移动宽带
现在已经转向ssr了
从goagent开始就一直用，希望不要永久沦陷了。

**Comment by AnyWAT** [comment]
移动 IPv4内网，从必须开启 IPv6隧道开始就一直24X7几乎分分钟正常、稳定 #12043 
对原生或许无此一说？ https://github.com/XX-net/XX-Net/issues/11759#issuecomment-448854172 
![image](https://user-images.githubusercontent.com/37962734/51800410-41a8c200-2269-11e9-837c-0dbd324dccc6.png)
（貌似目前原生并不优越于隧道😂）有些：原生ipv6异常，转使用隧道，暂时恢复正常 #12093

**Comment by Hunerk** [comment]
不要折腾了，开放IPV6就代表墙已对IPV6能Black了。
SSR 大把大把的。
但我用习惯XX了，还是用着的。当然方法还是有的，自己找找以前的发贴。

**Comment by MadMaxPayne8964** [comment]
GFW在IPv6下也部署路由黑洞了，虽然我有VPS，但GAE用了快十年，一直不放弃更多是情怀。原生IPv6需要tracert筛选可用IP，数目虽不多延迟也上千，但速度还可以。

**Comment by dylanleesky** [comment]
完了完了完了、、、我这的v6也废了。果然好好地忽然放行v6肯定就是有那个技术了。哎。。。

**Comment by loy20002000** [comment]
诶，如果有大量的访问外网需求还是用收费的吧，例如windscribe这种。某些国家的流媒体限制境外观看，如日本，用这种工具还能收到特别的惊喜。

只要人人都献出一点美刀，墙将失去它地意义。^ ^

**Comment by AnyWAT** [comment]
Pcap_DNSProxy + 原生ipv6 #12206
