### ISSUE TITLE
xxnet 3.12.11 X tunnel 不能访问 google scholar

### ISSUE THREAD

**Issue by vibb** [XX-net/XX-Net#12188]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by vibb** [comment]
Jan 30 21:29:07.015 - [INFO] https ('127.0.0.1', 62932) connect to scholar.google.com:443 conn_id:62

**Comment by SeaHOH** [comment]
https://www.semanticscholar.org/
>Semantic Scholar 是由微软联合创始人 Paul Allen 做的免费学术搜索引擎，其检索结果来自于期刊、学术会议资料或者是学术机构的文献。这个搜索引擎用上了机器学习的技术，希望减少个人的检索论文的时间。对于人们来说，Semantic Scholar 看上去最大的用处是有更多信息筛选的角度，包括论文的影响力，媒体报道、作者等，另外它直接提供图表预览，能方便使用者省下更多筛选的工作。

如果非要用谷歌，最好直连，可以试试我写的工具。
