### ISSUE TITLE
仅IPv6不可用问题的解决过程

### ISSUE THREAD

**Issue by zmx01403137** [XX-net/XX-Net#12198]
最近使用XX-Net 3.13.1时总是遇到"仅IPv6不可用"问题，希望以下解决过程对大家有帮助。

**步骤如下:**
1. 在系统网卡属性设置中，将 Internet Protocol Version 6 (TCP/IPv6) 勾选项去除。

2. 查看当前IPv6设置
$ netsh int ipv6 show teredo
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : win1711.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : managed
NAT                     : restricted (port)
NAT Special Behaviour   : UPNP: No, PortPreserving: No
Local Mapping           : 192.168.1.12:63977
External NAT Mapping    : xxx.xxx,xxx,xxx:46207

3. 更改IPv6设置
$ netsh int ipv6 set teredo natawareclient win10.ipv6.microsoft.com
不行的话，可以尝试更改成以下地址:
win1710.ipv6.microsoft.com
win1711.ipv6.microsoft.com
win1807.ipv6.microsoft.com
teredo.ipv6.microsoft.com
teredo.remlab.net
teredo2.remlab.net
teredo-debian.remlab.net
teredo.ngix.ne.kr
teredo.trex.fi
teredo.autotrans.consulintel.com
teredo.managemydedi.com

4. 验证更改结果
$ netsh int ipv6 show teredo
Teredo Parameters
---------------------------------------------
Type                    : natawareclient
Server Name             : win10.ipv6.microsoft.com
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : probe (primary server)
Client Type             : teredo client
Network                 : managed

**Comment by AnyWAT** [comment]
teredo.ipv6.microsoft.com. （已死）
teredo.ngix.ne.kr.  （已死）
teredo.autotrans.consulintel.com. （已死）
teredo.managemydedi.com. （？）
win1711.ipv6.microsoft.com. 与 win1807.ipv6.microsoft.com. 俩服务器陷阱！

**Comment by hzx505** [comment]
更换服务器ok，感谢分享
netsh int ipv6 set teredo natawareclient win10.ipv6.microsoft.com

**Comment by MadMaxPayne8964** [comment]
我这里是teredo早死挺了，一个都不能用。原生IPv6导入新IP段目前满血，不知道还能挣扎多久
