### ISSUE TITLE
哇 这是怎么了~ xxnet上不去鸟~~~

### ISSUE THREAD

**Issue by xuzhijiangx** [XX-net/XX-Net#12199]
内心隐约间感到一丝悲凉~

**Comment by xuzhijiangx** [comment]
有效 IPv6 IP 数  1
放下鼠标 先跳一段广场舞~蹦擦擦 蹦擦擦~

**Comment by maoyali** [comment]
我都没有有效IP。。。昨晚突然不能用了

**Comment by xuzhijiangx** [comment]
> 我都没有有效IP。。。昨晚突然不能用
哇~

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by AnyWAT** [comment]
> 太慢了！

关闭某开关并适当增加最大扫描线程数，使：有效 IP数/总 IP数之比值=1 #12043 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-458833682

**Comment by tq01o3n** [comment]
> > 太慢了！
> 
> #12043 关闭某开关并适当增加最大扫描线程数，（或更换服务器），随时：有效 IP数/总 IP数之比值=1 [#12043 (comment)](https://github.com/XX-net/XX-Net/issues/12043#issuecomment-458833682)
请问！
1，某开关是哪个？在哪里？
2，最大扫描线程数 (0~200)，我这里默认是100，我试图改200，再点提交，切换其他页面之后还是会变回100，退出xxnet再启动还是100，怎么回事？

**Comment by AnyWAT** [comment]
皆有答案，在那里 👉 #12043

**Comment by tq01o3n** [comment]
> 1&2皆有答案，在那里 👉 #12043

netsh int ipv6 set teredo disable _即可禁用隧道_。（完全禁用隧道或得由[控制页]“禁用”完成

这个就是关闭某开关吗？

第2项问题已搞定了，谢谢！！

**Comment by AnyWAT** [comment]
> 这个就是关闭某开关吗？

温故而知新。。。#12043

**Comment by tq01o3n** [comment]
> > 这个就是关闭某开关吗？
> 
> 温故而知新。。。#12043

太难了，不大看得懂

**Comment by tq01o3n** [comment]
> > 这个就是关闭某开关吗？
> 
> 温故而知新。。。#12043

自动调整扫描线程数，就是这个开关把？
