### ISSUE TITLE
mac系统运行

### ISSUE THREAD

**Issue by TonySteven7** [XX-net/XX-Net#12194]
mac系统小白一枚~~
可能是我之前设置的问题 导致我双击start是以文本编辑的形式打开的 想问下该用什么打开start 谢谢。。

**Comment by NAP-E** [comment]
右键用终端app打开就好了。

**Comment by ChenYu0302** [comment]
你解决了吗？我也是遇到这个问题

**Comment by TonySteven7** [comment]
> 你解决了吗？我也是遇到这个问题

我搞定了...你搞定没

**Comment by ChenYu0302** [comment]
> > 你解决了吗？我也是遇到这个问题
> 
> 我搞定了...你搞定没

没有，旧版本是可以双击运行的。
现在只能在终端输入命令行 python start.py ，但是这样就不可以后台运行了

**Comment by yangsl158** [comment]
到现在都没搞清楚怎么运行。。。研究了好久还是不行。。。

**Comment by TonySteven7** [comment]
> 到现在都没搞清楚怎么运行。。。研究了好久还是不行。。。

https://github.com/XX-net/XX-Net 在这个页面下 用Clone or Download这个按钮下载 下载下来的就一切正常 可以双击打开start 也不知道为什么 你试试。

**Comment by ChenYu0302** [comment]
> > 到现在都没搞清楚怎么运行。。。研究了好久还是不行。。。
> 
> https://github.com/XX-net/XX-Net 在这个页面下 用Clone or Download这个按钮下载 下载下来的就一切正常 可以双击打开start 也不知道为什么 你试试。

嗯可以了，之前是在下载页面下的7z压缩文件就无法运行

**Comment by yangsl158** [comment]
> > 到现在都没搞清楚怎么运行。。。研究了好久还是不行。。。
> 
> https://github.com/XX-net/XX-Net 在这个页面下 用Clone or Download这个按钮下载 下载下来的就一切正常 可以双击打开start 也不知道为什么 你试试。

哇，谢谢谢谢！！
