### ISSUE TITLE
已经扫描了2个多小时了，到底什么时候才结束啊？！！

### ISSUE THREAD

**Issue by lbx6z** [XX-net/XX-Net#1219]
ubuntu14.04 chrome，我是之前没添加代理的那个人，现在启动看起来很正常，不过就是扫描ip好慢啊！昨天晚上宿舍断电后跑到电脑没电；今天早上起来启动，又继续睡；为了不断网，还推迟了实习 >.< 实在不能忍啊

**Comment by lbx6z** [comment]
>>>>>>>>>>>>>>>>>>>>>.
Oct 14 08:48:44 - [INFO] PAC from:127.0.0.1:52052 GET /proxy.pac 
Oct 14 08:48:47 - [INFO] scan_ip add ip:103.11.30.41 time:688
Oct 14 08:51:46 - [INFO] scan_ip add ip:103.11.28.101 time:692
Oct 14 08:54:50 - [INFO] scan_ip add ip:202.248.151.30 time:657
Oct 14 08:56:36 - [INFO] scan_ip add ip:188.21.9.199 time:679
Oct 14 08:57:20 - [INFO] scan_ip add ip:186.73.79.39 time:589
Oct 14 09:05:41 - [INFO] scan_ip add ip:1.255.22.238 time:684
Oct 14 09:06:07 - [INFO] scan_ip add ip:103.11.28.118 time:694
Oct 14 09:06:27 - [INFO] scan_ip add ip:216.58.211.188 time:600
Oct 14 09:09:33 - [INFO] scan_ip add ip:103.11.28.164 time:703
Oct 14 09:16:36 - [INFO] scan_ip add ip:103.11.28.226 time:766
Oct 14 09:19:49 - [INFO] scan_ip add ip:103.11.28.177 time:755
Oct 14 09:23:35 - [INFO] scan_ip add ip:64.233.186.188 time:606
Oct 14 09:24:27 - [INFO] scan_ip add ip:61.238.203.11 time:351
Oct 14 09:24:33 - [INFO] scan_ip add ip:89.47.210.117 time:813
Oct 14 09:24:39 - [INFO] scan_ip add ip:103.11.28.112 time:688
Oct 14 09:25:18 - [INFO] scan_ip add ip:216.58.216.99 time:482
Oct 14 09:30:08 - [INFO] scan_ip add ip:60.199.175.159 time:235
Oct 14 09:33:55 - [INFO] scan_ip add ip:202.248.151.49 time:679
Oct 14 09:34:40 - [INFO] scan_ip add ip:60.199.175.186 time:206
Oct 14 09:35:53 - [INFO] scan_ip add ip:216.58.219.141 time:472
Oct 14 09:40:24 - [INFO] scan_ip add ip:103.11.28.86 time:778
Oct 14 09:44:51 - [INFO] scan_ip add ip:159.253.153.218 time:899
Oct 14 09:46:09 - [INFO] scan_ip add ip:103.11.28.230 time:798
Oct 14 09:47:25 - [INFO] scan_ip add ip:103.11.28.120 time:687
Oct 14 09:47:53 - [INFO] scan_ip add ip:1.255.22.174 time:660
Oct 14 09:54:13 - [INFO] scan_ip add ip:103.11.28.210 time:704
Oct 14 09:54:46 - [INFO] scan_ip add ip:103.11.28.175 time:939
Oct 14 09:56:47 - [INFO] scan_ip add ip:103.11.28.23 time:683
Oct 14 09:59:37 - [INFO] scan_ip add ip:216.58.219.225 time:538
Oct 14 10:09:34 - [INFO] scan_ip add ip:216.58.219.3 time:417
Oct 14 10:15:28 - [INFO] scan_ip add ip:202.248.151.40 time:623
Oct 14 10:16:51 - [INFO] scan_ip add ip:103.11.28.48 time:758
Oct 14 10:17:21 - [INFO] scan_ip add ip:1.255.22.203 time:662
Oct 14 10:18:18 - [INFO] scan_ip add ip:118.98.111.139 time:1180
Oct 14 10:18:21 - [INFO] scan_ip add ip:103.11.28.221 time:804
Oct 14 10:19:09 - [INFO] scan_ip add ip:115.254.97.7 time:421
Oct 14 10:20:14 - [INFO] scan_ip add ip:216.58.220.135 time:506
================================
每次的时间间隔，:-(

**Comment by xxnet** [comment]
已目前的策略，10个ip就可以慢慢用了，有20个高质量的ip,就可以很愉快的上网了呀

2015-10-14 10:24 GMT+08:00 lbx6z <notifications@github.com>:

**Comment by lianbookca** [comment]
只要把软件打开就自己 扫描 了吗 新手不懂

**Comment by lbx6z** [comment]
@xxnet 所以要咋关闭呢？ctrl-C？因为之前再windows上配置过，它很快就结束了～不过转到ubuntu后，就扫了好久。我从11:19开始扫，现在已经18:18了，还没停......

**Comment by xxnet** [comment]
可以不关闭扫描，不影响使用。

要关闭扫描，可以在设置页面里，扫描线程改为0

在 2015年10月14日 下午6:19，lbx6z <notifications@github.com>写道：

**Comment by damoyelang1992** [comment]
达到3000就不扫描了。短则一上午，长则几天
