### ISSUE TITLE
1.8.2无法打开 谷歌学术https://scholar.google.com/

### ISSUE THREAD

**Issue by lingchen04** [XX-net/XX-Net#122]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

IP 地址：107.178.200.243
时间：2015-04-10T03:44:41Z
网址：http://www.google.com/

**Comment by xxnet** [comment]
收到，下个版本修复

在 2015年4月9日 下午11:47，lingchen04 <notifications@github.com>写道：

**Comment by xxnet** [comment]
已修复

**Comment by Tee2018** [comment]
我是用目前最新的稳定版XX-Net-3.13.1 依然出现“我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？


IP 地址：107.178.194.115
时间：2019-01-22T08:50:35Z
网址：https://scholar.google.com/”
这个是什么原因呢？
