### ISSUE TITLE
总ip速降的解决过程

### ISSUE THREAD

**Issue by miketwes** [XX-net/XX-Net#12205]
版本XX-Net 3.13.1 

开始运行提示

等待扫描 IP，建议开启 IPv6

导入ip后,用了两天之后总ip速降直至0接着又是:

等待扫描 IP，建议开启 IPv6

改了[config.json](https://github.com/miketwes/XX-Net-Linux/blob/master/data/config.json)后,这几天总ip一直保持为388个

**Comment by sjfirefox** [comment]
这事赶上直播了？咋改？

**Comment by miketwes** [comment]
@sjfirefox  链接里的[config.json](https://github.com/miketwes/XX-Net-Linux/blob/master/data/config.json) 是已改好的

**Comment by miketwes** [comment]
[good_ip.txt](https://github.com/miketwes/XX-Net-Linux/blob/master/data/good_ip.txt) 里的ip用的还是@xxnet前些天扫出来的

**Comment by l-night** [comment]
已测试，IP数还是几个。。。
![2019-02-05 211756](https://user-images.githubusercontent.com/29896468/52275805-88926800-298b-11e9-9e98-c6499c33fcff.jpg)

**Comment by AnyWAT** [comment]
LS的总 IP数太大（何况大佬公布的才不足500），与扫描线程数不匹配，且关闭了某开关否？#12043

**Comment by hhurd1** [comment]
![fireshot _](https://user-images.githubusercontent.com/45315398/52396705-b98aae00-2aed-11e9-9882-8d5ea3c1a03a.png)
终于正常使用了。里边文件要改了下"GAE_APPIDS"里的ID，不然是用公用的

**Comment by Buccaneer01** [comment]
这是原生？还是隧道？

**Comment by tq01o3n** [comment]
> LS的总 IP数太大（何况大佬公布的才不足500），与扫描线程数不匹配，且关闭了某开关否？#12043

哪个某开关？在哪里？

**Comment by tq01o3n** [comment]
> [good_ip.txt](https://github.com/miketwes/XX-Net-Linux/blob/master/data/good_ip.txt) 里的ip用的还是@xxnet前些天扫出来的

good_ip.txt是哪个目录下的？我xxnet根目录下搜出来有好几个good_ip.txt

**Comment by drykimi** [comment]
> @sjfirefox 链接里的[config.json](https://github.com/miketwes/XX-Net-Linux/blob/master/data/config.json) 是已改好的

请问config.json在哪里改？

**Comment by miketwes** [comment]
已正常使用十几天,总ip只掉了两个

![2019-02-08_426x69](https://user-images.githubusercontent.com/6849681/52475301-106bb280-2bd6-11e9-847e-92f39474bf9b.png)

**Comment by AnyWAT** [comment]
原来是楼主自简化版 [XX-Net-Linux 3.13.1](https://github.com/miketwes/XX-Net-Linux)，😜一群Win 系统用户。。。
