### ISSUE TITLE
大家过年好！给xx-net技术团队及各位x友拜年！

### ISSUE THREAD

**Issue by mtgitnerd** [XX-net/XX-Net#12203]
感谢xx-net团队给大家带来真相和希望，愿项目长久存活，祝我们早日来到无须土番土蔷的美好世界！

**Comment by hubsocks** [comment]
然后google将明文数据传回镜内就安心了?做了什么不安心啊.一般就是人工方式封ip,这是技术方面理设有限.

**Comment by gibwise** [comment]
新年吉祥 万事如意 目前xxnet不好用了 推荐一个好用的注册送5GB流量 邀请有限
https://bighead.szccmdj.com.cn/register?aff=2533&code=259FDA005423
https://bighead.szccmdj.com.cn/register?aff=2533&code=A0A0DB86384C

**Comment by loy20002000** [comment]
@hubsocks

接受到的东西不重要，关键是发送的东西。

我国内的各类账号，差不多80%被盗。100%可以肯定不是本地的问题，之前一直在纯洁环境登录的（有Kaspersky之类两种以上杀毒护航）。后来想通了，是网络传输中间环节的问题。有些账号https链接都能被盗，我也是醉了。发生这种事情只能怀疑中国的互联网环境出现了与棱镜门一样的问题。

境外的账号，不论是Google还是其他，普遍用了10年往上，从来没有出现过被盗或几天不登录就变成别人所有物的情况。有些小站时至今日都是http，换在国内早被盗成广告机器人了。

**Comment by hubsocks** [comment]
@hubsocks 盗号应该是员工所为.棱镜门这个都成公开的事了.2345压缩软件装了之后,有一个服务进程,一直有网络发包.很多家里的宽带光猫是交压金租用的,为什么这么做呢?

**Comment by loy20002000** [comment]
@hubsocks 

盗号应该是员工所为.棱镜门这个都成公开的事了.2345压缩软件装了之后,有一个服务进程,一直有网络发包.很多家里的宽带光猫是交压金租用的,为什么这么做呢?

-----------

回复你之后，搜狗输入法给我自动装了个搜狗浏览器。我不爽给卸了后，不清楚原因是什么，我的系统崩溃了，连安全模式都进不去了。5、6天以前我装了个2010年的MS输入法，没卸搜狗输入法的时候一切正常，卸了之后系统一直蓝屏或者死机，要么就是系统完全没反应，我还以为是盗版系统缺少库文件，现在看来是它修改了一些系统的关键配置，甚至删除了一些关键的文件；最神奇的是重新安装之后马上恢复正常。现在只敢用智能ABC，悲剧呀。一年前一个加拿大的华侨跟我讲这玩意不安全，我还说这玩意儿肯定安全呢，真是报应。

昨天重新装了系统后，360真心霸道。我重新安装的软件在“控制面板---添加或删除软件”里居然没有卸载项，查注册表才知道XIEZAI项已经全部被360安全卫士删除或修改了。与他们关系密切的产品没有卸载的注册表项，关系比较远的修改成隐匿模式（如XUNLEI）。而用360自家工具打开所有项目的XIEZAI都有，但UC浏览器还是没有卸载项。

要不是老婆需要用国产软件，我早把国产软件统统请出电脑了。即便只装了有限的几个，居然还给我个这么大的惊喜。

**Comment by AnyWAT** [comment]
IObit Uninstaller
