### ISSUE TITLE
这几天有效ipv6数目没有，只有1，要怎么解决？

### ISSUE THREAD

**Issue by drykimi** [XX-net/XX-Net#12209]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by flixmary** [comment]
这个东西感觉要凉，但是奇怪的是我两个不同的电脑，一个从老版更新到新版，因为刚接触就用的，到现在还是杠杠的，直接打开，然后关闭配置的页面，直接右键科学上网，从来没出过问题。
一个我直接下的新版的，用来用去一直各种不稳定，要么就是弄的有效IP几百个，然后连上了，然后飞速降到0，要么就是被我弄的有效IP一直是1，要么就是一切正常有效IP也稳定，显示你能科学上网，但是实际就是无用，我也不知道为什么？
会不会和地区的网络有关？我两个电脑不同网络环境  头疼啊
实在不行那天试了下放弃很久的VPNGATE然后奇迹般的被我连了个稳定的，这两天又连不到好的服务器了
还是手机科学上网方便，好多免费的，不限流量，还特别稳定

**Comment by AnyWAT** [comment]
> 这个东西感觉要凉，

https://github.com/XX-net/XX-Net/issues/12189#issuecomment-459192395

**Comment by hubsocks** [comment]
VPNGATE是禁止中国ip连接的.对方服务器不充许的.少数也可以短时间连接.然后把你的ip列到黑白单的.但网上很多softether免费帐号.这个软件无安卓版.国内阿里云,腾讯云的免费socks5一些.有效期几天.速度快的可以达到5万以上.

**Comment by AnyWAT** [comment]
> 国内阿里云,腾讯云

https://github.com/shadowsocks/shadowsocks/issues/1180 有多少的人阿里云面临给封的危机啊

**Comment by hubsocks** [comment]
@AnyWAT 阿里搞技术不是google查资料?华为研究技术的不用google查资料?其它高速代理都是他们自己建的.youtube上的几个cctv官媒频道难道不是在国内上传视频的?

**Comment by drykimi** [comment]
C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 7164
状态                    : dormant

**Comment by AnyWAT** [comment]
> 状态 : dormant

隧道已连接👉 状态 : qualified
更换服务器？#12043
[XX-Net 诊断信息：]( )

XX-Net Status:

sys-platform: x86, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:224 ipv4:0 ipv6:224
ipv4-status: OK
ipv6-status: OK
connected-link: new:2
worker: h1:0 h2:45
scan-ip-thread-num: 139
ip-quality: 315
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by echovae** [comment]
一直在折腾，现在不想折腾了。最近在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by Buccaneer01** [comment]
感觉项目已经凉了，试了各种方式都不行，除夕那天下午，换隧道后曾经正常了几个小时。。。
有点像当年的goagent了，不过这次更绝，GAE看来是彻底废了

**Comment by AnyWAT** [comment]
建议LS细细品味4楼、2楼。。。

**Comment by AnyWAT** [comment]
> 感觉项目已经凉了，试了各种方式都不行，除夕那天下午，换隧道后曾经正常了几个小时。。。
> 有点像当年的goagent了，不过这次更绝，GAE看来是彻底废了

Teredo 隧道 #12455 或原生 #12477 均正常中。。。
