### ISSUE TITLE
求更新啊

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#12201]
已经过了这么久了   求更新啊

**Comment by MadMaxPayne8964** [comment]
xx大和海大顾不上，年底都比较忙。最近不好用不是软件本身的问题，不是更新能解决的

**Comment by dylanleesky** [comment]
党国恐怕已经把v6的墙给砌好。无比恐惧的白名单模式看样子也不远了。现在上网吧竟然都得人脸识别，新疆的那套也拿来内地了。我日！！！不知道多少年后上街得带身份证随时让警察查，手机里得安装主动监控软件，不装就拿下。

**Comment by dylanleesky** [comment]
> 党国恐怕已经把v6的墙给砌好。无比恐惧的白名单模式看样子也不远了。现在上网吧竟然都得人脸识别，新疆的那套也拿来内地了。我日！！！不知道多少年后上街得带身份证随时让警察查，手机里得安装主动监控软件，不装就拿下。
> 
> 专制统治下的人民才有安全感嘛~~~
> 
> 自由门最新版2019.2.2更新，很好用唷。

共享一份呗。最近太懒了，懒得在陷阱里找那一根绳子。

**Comment by hobartSimple** [comment]
求更新啊！连不上了
