### ISSUE TITLE
求分享IP

### ISSUE THREAD

**Issue by Peterpey** [XX-net/XX-Net#12202]
之前X大发的IP几乎全挂了 求大神分享一些IP
先谢谢啦

**Comment by myjlpt** [comment]
IP很多能用的并不太多了。貌似
............
你可以访问下XXNET-dev这个项目找找，应该有个库的，要自己扫一遍试试.

**Comment by wtr19941227** [comment]
同求分享IP，400多个IP几乎挂到个位数了。多谢

**Comment by myjlpt** [comment]
一部分江苏地区昨天扫出现在一直正常的你们试试吧
2607:f8b0:4002:c02::99|2607:f8b0:4002:c00::99|2607:f8b0:4002:c0c::99|2607:f8b0:4008:805::2014|2607:f8b0:4012:80b::2014|2607:f8b0:4006:803::2014|2607:f8b0:4012:808::2014|2607:f8b0:4012:80a::2014|2a00:1450:4009:809::2014|2a00:1450:4009:810::2014|2a00:1450:4007:80d::2014|2a00:1450:4001:816::2014|2a00:1450:400e:805::2014|2a00:1450:4001:819::2014|2a00:1450:4007:808::2014|2a00:1450:4017:80b::2014|2a00:1450:4003:807::2014|2a00:1450:4016:80b::2014|2a00:1450:4002:807::2014|2a00:1450:4002:80a::2014|2a00:1450:401b:802::2014|2404:6800:4005:802::2014|2800:3f0:4004:801::2014|2404:6800:4005:810::2014|2800:3f0:4001:807::2014|2a00:1450:4009:803::2014|2800:3f0:4002:809::2014|2404:6800:4006:808::2014|2404:6800:4001:803::2014|2607:f8b0:4007:800::2014|2607:f8b0:4007:80d::2014|2607:f8b0:4007:80b::2014|2607:f8b0:4005:80b::2014|2607:f8b0:4007:80e::2014|2607:f8b0:4005:801::2014|2607:f8b0:4005:802::2014|2607:f8b0:4005:806::2014|2607:f8b0:4005:80a::2014|2607:f8b0:400f:807::2014|2607:f8b0:4000:80e::2014|2607:f8b0:400f:800::2014|2607:f8b0:400e:c03::99|2607:f8b0:4000:806::2014|2607:f8b0:4000:812::2014|2607:f8b0:400a:803::2014|2607:f8b0:400f:805::2014|2607:f8b0:4000:817::2014|2607:f8b0:4003:c01::99|2607:f8b0:4003:c00::99|2607:f8b0:4003:c17::99|2607:f8b0:4003:c19::99|2607:f8b0:4000:813::2014|2607:f8b0:4003:c09::99|2404:6800:4007:80f::2014|2607:f8b0:4003:c15::99|2404:6800:4002:803::2014|2607:f8b0:4001:c0e::99|2607:f8b0:400b:80e::2014|2607:f8b0:4000:814::2014|2607:f8b0:4002:c09::99|2607:f8b0:400b:80d::2014|2607:f8b0:4009:810::2014|2607:f8b0:4009:811::2014|2607:f8b0:4002:c06::99|2607:f8b0:4009:80d::2014|2607:f8b0:4009:80f::2014|2607:f8b0:4007:80c::2014|2607:f8b0:4009:808::2014|2607:f8b0:4002:c07::99|2607:f8b0:4009:816::2014|2607:f8b0:4002:c08::99|2607:f8b0:4009:804::2014

**Comment by wtr19941227** [comment]
试着导入了一下，没有有效IP，马上就掉光了。怎么扫描IP呢，请教一下

**Comment by myjlpt** [comment]
目前江苏这边2607还是蛮稳定的，无论电信还是联通。电信400多，联通290多。不过貌似电信的400多还是比290多的联通连接快速。
重要的是不同的DNS貌似有不同效果。比如默认联通400MS 改114就398MS多，改180的百毒就290MS多。就这样。

**Comment by AnyWAT** [comment]
😥比对了下LS所提供的前后各5个 IP，全部是大佬公布的 https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138
