### ISSUE TITLE
现在有什么稳定的方法翻墙？付费免费都说下啊。

### ISSUE THREAD

**Issue by wantno** [XX-net/XX-Net#12200]
实在没办法了，来回折腾的不想闹心了，只要稳定就行啊。。。。。。

**Comment by loy20002000** [comment]
翻出去搜google的chrome插件或android的APK不就行了么？

**Comment by weicen** [comment]
ssr v2ray 很好用 免费节点很多

**Comment by Zmm1977** [comment]
我刚买了一年的搬瓦工。。。29美元一年。。。不折腾了

**Comment by gibwise** [comment]
有提供vps的吗 帮搭机场

**Comment by gibwise** [comment]
> 我刚买了一年的搬瓦工。。。29美元一年。。。不折腾了
可以开个节点吗

**Comment by tatiyixi** [comment]
用蓝灯吧。用了2个多月，还可以。

**Comment by varicella** [comment]
付费的很多啊，你随便一搜索就有了。貌似有3个还是挺好用的。

**Comment by GataNya** [comment]
可以试试下面机场服务https://s.hkssr.club
邀请码五个有限注册
aZ5qUBvUv0iOE77RXudXk0Cf
bu38r0QB8ghHdWQXn2maltCn
e67tIeeJVdLkrMueF5ZHC1lJ
IwIlkY8YoFDilhkbvDw410uz
Njh6WZ8EyyMXINvCmVpa1KjM

**Comment by hubsocks** [comment]
要求不高的,免费的国内的socks5 http代理很多,速度2万bps左右,可用几天就要换了.很多国内网站可以找到.然后检测那些有效.这里都是需要访问外网的公司或国企在使用.http代理有中央网信办审计,socks5就是没有的.清华大学也有一些高速代理.
如果这没些高速代理,那油土拨的cctv官方频道是鬼在上传视频?阿里云,腾迅云在国内梯子也很多.大公司程序员学技术也翻墙学习技术,要不然也不可能会编程.
简单的方法的.

**Comment by AnyWAT** [comment]
> 阿里云,腾迅云

https://github.com/shadowsocks/shadowsocks/issues/1180 有多少的人阿里云面临给封的危机啊

**Comment by echovae** [comment]
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。[http://jiasd.us/9449](url) （使用此链接，你我都能得到20%优惠）

**Comment by titiexe** [comment]
> 用蓝灯吧。用了2个多月，还可以。

蓝灯登国内网太慢，有时候翻出去也慢。不能手动换服务器是个缺点，其实还是xx好用。

**Comment by AnyWAT** [comment]
> 不能手动换服务器是个缺点

#12043 【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】

**Comment by littlebigdream** [comment]
要合用梯子吗？我自己买的服务器 自己搭自己用的 两年了，速度还行4m/s，18每月。VX：2312768839，加时备注。

**Comment by xxnet** [comment]
提醒大家，不要用微信、QQ交流，防止钓鱼
