### ISSUE TITLE
为什么我在校园网用的好好的，回家以后就不能用了

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12207]
我在学校用，XX-NET时，有效IPV6接近100，大年三十回家发现有效IP只有各位数，并且常常抽风，今天彻底上不去，是怎么回事呢？各种办法都试过了。

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | Fail (尝试修复)
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 5
总 IP 数 | 100
XX-Net 状态 | 空闲
IP 延迟 | 877
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by AeneasZhu** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.3.10:53142
外部 NAT 映射    : 116.22.164.133:19825

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！
服务器名称 : win1711.ipv6.microsoft.com. ——（几乎没有正常的时候的）服务器陷阱！#12043
XX-Net Status:

sys-platform: x86, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:224 ipv4:0 ipv6:224
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:0 h2:47
scan-ip-thread-num: 139
ip-quality: 335
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : 157.56.149.60
客户端刷新间隔          : 360 秒
客户端端口                : 
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
