### ISSUE TITLE
0

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#12216]

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/52531393-b1ca4400-2d4f-11e9-974b-49f4c0984b40.png)

**Comment by loy20002000** [comment]
用wujie，你个反党分子。。。哈哈

**Comment by hubsocks** [comment]
阿里云 ,腾讯云,大量国内socsk5高速代理可以翻墙,这么简单的方法你不用.

**Comment by iAPPOpen** [comment]
> 阿里云 ,腾讯云,大量国内socsk5高速代理可以翻墙,这么简单的方法你不用.

能详细说说吗，具体收费标准怎样，操作难吗

**Comment by hubsocks** [comment]
@iAPPOpen 
不用钱.就是百度一些国内socks5代理就可以了.可用时间几天.需要检测那些是有效的.每个地方连接情况都不相同的.
编号	IP地址	端口	连接	切换	大小	耗时	速度 ▼	地区	地址
9	111.223.75.178	8888	0.2383	0.3789	429479	4.6641	92.083	新加坡	未知
56	58.68.228.234	1234	0.2109	0.2500	353232	4.1563	84.988	北京市	北京蓝汛通信技术有限责任公司(BGP)
11	188.166.230.63	54321	0.4063	0.4648	367161	4.3672	84.073	新加坡	DigitalOcean数据中心
8	178.128.218.86	8000	2.0391	1.3633	413021	5.1133	80.774	希腊	未知
17	49.65.160.3	1080	0.3281	1.0313	350173	5.1445	68.067	江苏省南京市	电信
29	47.93.7.198	1089	0.0938	0.3242	331652	5.2070	63.693	北京市	阿里云
3	175.45.11.45	8082	0.3359	2.4258	59133	11.3438	5.213	香港	汇港电讯
7	114.4.132.43	443	0.5352	0.7617	467199	11.0508	42.277	印度尼西亚	未知
2	119.28.191.18	7070	1.4805	1.9180	472793	16.1758	29.228	香港	腾讯云
6	175.45.11.43	8082	0.2383	0.8477	103032	5.1602	19.967	香港	汇港电讯
4	175.45.11.44	8082	0.1914	0.3477	148050	11.3555	13.038	香港	汇港电讯
13	39.105.90.17	3389	0.1172	1.8438	418239	32.5039	12.867	香港	特别行政区

**Comment by AeneasZhu** [comment]
> @iAPPOpen
> 不用钱.就是百度一些国内socks5代理就可以了.可用时间几天.需要检测那些是有效的.每个地方连接情况都不相同的.
> 编号	IP地址	端口	连接	切换	大小	耗时	速度 ▼	地区	地址
> 9	111.223.75.178	8888	0.2383	0.3789	429479	4.6641	92.083	新加坡	未知
> 56	58.68.228.234	1234	0.2109	0.2500	353232	4.1563	84.988	北京市	北京蓝汛通信技术有限责任公司(BGP)
> 11	188.166.230.63	54321	0.4063	0.4648	367161	4.3672	84.073	新加坡	DigitalOcean数据中心
> 8	178.128.218.86	8000	2.0391	1.3633	413021	5.1133	80.774	希腊	未知
> 17	49.65.160.3	1080	0.3281	1.0313	350173	5.1445	68.067	江苏省南京市	电信
> 29	47.93.7.198	1089	0.0938	0.3242	331652	5.2070	63.693	北京市	阿里云
> 3	175.45.11.45	8082	0.3359	2.4258	59133	11.3438	5.213	香港	汇港电讯
> 7	114.4.132.43	443	0.5352	0.7617	467199	11.0508	42.277	印度尼西亚	未知
> 2	119.28.191.18	7070	1.4805	1.9180	472793	16.1758	29.228	香港	腾讯云
> 6	175.45.11.43	8082	0.2383	0.8477	103032	5.1602	19.967	香港	汇港电讯
> 4	175.45.11.44	8082	0.1914	0.3477	148050	11.3555	13.038	香港	汇港电讯
> 13	39.105.90.17	3389	0.1172	1.8438	418239	32.5039	12.867	香港	特别行政区

在哪里可以找到这些sock5?

**Comment by retmania** [comment]
你既然这么随便就跪了，去大街上跪着，赚来的钱买个梯子不好吗

**Comment by AnyWAT** [comment]
> 在哪里可以找到这些sock5?

https://github.com/XX-net/XX-Net/issues/12220#issuecomment-462260130

**Comment by 80068** [comment]
@AnyWAT 感谢回复，回来在试试。

标题、内容已经删了省着让他们天天看着。没劲。
