### ISSUE TITLE
最近经常出现 IP:xxx.xx.xx.xx not support GAE, server type:GFE/2.0

### ISSUE THREAD

**Issue by baoyankun** [XX-net/XX-Net#1221]
2.5.0 和 2.0.5 都有此现象

```
Oct 14 14:53:00 - [WARNING] fetch gae status:502 url:https://www.youtube.com/results?search_query
Oct 14 14:53:00 - [WARNING] IP:31.55.166.207 not support GAE, server type:GFE/2.0
```

**Comment by baoyankun** [comment]
Sorry, 先升级到 2.5.4 试试

**Comment by xxnet** [comment]
这个ip确实无法使用，怀疑只支持HTTP/2，可以找goproxy 试试这个ip

2015-10-14 15:02 GMT+08:00 baoyankun <notifications@github.com>:

**Comment by baoyankun** [comment]
谢谢，刚下载了 2.5.4 测试了一会，暂时未发现此问题。
抱歉。
其它 [WARNING] socket error:error(32, 'Broken pipe') 的警告估计是我运营商的问题了。
