### ISSUE TITLE
有效IP越来越少了，有没有靠谱的ssr推荐的

### ISSUE THREAD

**Issue by bubuchao** [XX-net/XX-Net#12213]
netsh int ipv6 show teredo 的结果如下
类型                    : natawareclient
服务器名称              : 157.56.149.60
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : cone
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:300 ipv4:0 ipv6:7
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:7
scan-ip-thread-num: 200
ip-quality: 2665
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
gws-ip-num: total:300 ipv4:0 ipv6:7 ——总 IP数改小为200-250，更换服务器？#12043

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by gibwise** [comment]
性价比不错https://lostcloud.org/auth/register?code=R54CzG08frL04J5v
