### ISSUE TITLE
我是感觉和地区的网络有关，我今天又换到另一台计算机的住处，这里没有任何问题，就是我说的，这个地方我用了N年，一直没问题，另一台计算机的网络环境不行，穿透不穿透都一样，感觉就是被上一级在BE

### ISSUE THREAD

**Issue by flixmary** [XX-net/XX-Net#12219]
> 有个屁用，连上一会马上降为0

有图无真相？不会是服务器不合适？是骡子是马，牵出来溜溜：
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

_Originally posted by @AnyWAT in https://github.com/XX-net/XX-Net/issues/12211#issuecomment-462009451_

**Comment by ChenYu0302** [comment]
我用的安卓端，连联通手机流量就正常，连移动光纤wifi就断

**Comment by hubsocks** [comment]
早说了租用的光猫有鬼,带远程控制功能.

**Comment by AeneasZhu** [comment]
我在学校使用就行，大年初一回家后就不能用了

**Comment by loy20002000** [comment]
早说了租用的光猫有鬼,带远程控制功能.

--------

光猫的问题不会是，以光猫的物理性能不可能做到指定抓取或指定过滤。

**Comment by hubsocks** [comment]
@loy20002000 性能是很低,但它可以记录内网mac,或收到 干扰指令后开始干扰.以前出的光猫不会

**Comment by loy20002000** [comment]
·@hubsocks

兄弟，你的说法我不敢说肯定不可能。以我的网络知识来说（曾经考过CCNP），在路由器上做手脚就OK了，这么做反而成本变高。

我举例来说明。

假设海外出口光缆只有一台路由器，政府禁止访问谷歌。有两招可以禁止访问。DNS污染可以返回错误的IP地址。如果客户端用正确ip地址走直接连通，只需要把谷歌的ip地址在路由表设置成无限长就行了（即不可访问）。由于大陆网络都没有办法连通谷歌，所以大陆所有路由器都显示为无限长。只需要修改一个路由器的设置就实现了国内所有路由器的路由表的修改。这么做最大的好处是不会增加额外的时间成本，也就是说block或ban以后的路由器转包时间与完全不设置是一样的。

实际上封锁对外连接的成本主要在两个，一是目标ip与无辜ip的分布情况，二是部分政府或国际组织的ip为翻墙提供便利。例如自由门为什么可以1年才更新一次，我虽然没有实测却可以肯定，他们利用了某些重要的ip，而这些ip中国政府不能封锁。

成本一决定了彻底堵住翻墙是不可能的，因为杀敌一千自损八百，分布决定了路由表的过滤效率。这个就不展开了。成本二则是中国的国际影响力不够的直接体现，假设IEEE的某个ip为自由门提供便利，中国政府敢封锁么？不敢，因为封锁了就意味着中国的科技与世界脱节。正如不翻墙就可以在github下载数不清的翻墙软件，是一个道理。

最终结论是：客户方过滤是否可以（例如传说中的绿坝一类）？当然可以，但是效率低得可怕。

**Comment by xugaohui** [comment]
@loy20002000 封ip成本最低,也简单,过些时间会解封.经常封错.也是常有的事情.应该还是人工在处理吧.很多人说抓包后分析干扰.这也有可能.它们都是用科来.有时遇到怀疑的,会用干扰的办法迫使上网的放弃,肯定不能在出口带宽那里干扰.那样对网络影响很多大.只能从光猫上做文章 ,这样就只影响一家的网络.移动的宽带就是一种vpn,光猫设置也有网关管理中心ip.
sourceforge.net之前一直可以打开的.现在还不是一样封了.github都有封的可能性.客户方就是360,百度 ,2345有一个服务进程.

**Comment by hubsocks** [comment]
不能封的可以网络攻击.让网络不稳定

**Comment by SeaHOH** [comment]
https://gfwrev.blogspot.com/
学习下，温故而知新。

**Comment by loy20002000** [comment]
@xugaohui

我不清楚光猫执行的是不是中国独特的标准，如果它仅仅起到调制解调器的作用，那么用户把它换了不就行了吗。

封IP这个事情既可以手工也可以自动。境外的某些反华团体肯定是手工封锁。对于IP特别多的目标，例如谷歌和大学一类，xx net怎么工作他就怎么工作。

干扰通信不需要在光猫做文章，在全民用电话线上网的时代，gmail就时断时续的了。

国内的互联网就是一个巨型的长城防火墙。只以封锁IP这件事情来说，在海底光缆出口的地方处理是最把稳的。例如我所使用的移动网络在两年前，居然把中国统计局和中国人民银行的网站给封了。

都说国产软件会限制翻墙或者这一类的事情，这是不太可能的。这跟阴谋论没分别了。

**Comment by AnyWAT** [comment]
> @loy20002000 性能是很低,但它可以记录内网mac,或收到 干扰指令后开始干扰.以前出的光猫不会

https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671 



> 正如不翻墙就可以在github下载数不清的翻墙软件，是一个道理。

貌似 github 上图、下载需代理

**Comment by loy20002000** [comment]
@anywat

我的翻墙软件大部分是在这里下的。地址是不是这里的我记不太清楚，反正肯定可以下。

另外用网络共享软件可以完美破封锁。用的那个叫什么忘记了，我记得好像是BT之父搞出来的。
