### ISSUE TITLE
X-TUNNEL 连接服务器失败：session server login fail:602

### ISSUE THREAD

**Issue by varicella** [XX-net/XX-Net#12218]
X-TUNNEL 连接服务器失败：session server login fail:602
是不是服务器过年了？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11769#issuecomment-448999215

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11892#issue-394057094 3、X-Tunnel 正常的前提：。。。

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）
