### ISSUE TITLE
隧道一直休眠，换了很多服务器也还是休眠

### ISSUE THREAD

**Issue by Ted12234** [XX-net/XX-Net#12212]

**Comment by Ted12234** [comment]
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : 157.56.144.215
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by Ted12234** [comment]
之前ipv6不正常，x-tunnel也还能用，现在也用不了了

**Comment by AnyWAT** [comment]
> 隧道一直休眠，换了很多服务器也还是休眠

或许XX-Net 已死，不用退出再启动。。。

**Comment by Ted12234** [comment]
> > 隧道一直休眠，换了很多服务器也还是休眠
> 
> 或许XX-Net 已死，不用退出再启动。。。
真的不能用了吗。。。

**Comment by AnyWAT** [comment]
> 真的不能用了吗。。。

😥或许（你机器内先前启动的那个）XX-Net 已死，不用退出再启动。。。
![image](https://user-images.githubusercontent.com/37962734/52521944-01f6c700-2cba-11e9-8d2f-cdbee376d196.png)

**Comment by AnyWAT** [comment]
> 隧道一直休眠，换了很多服务器也还是休眠

如果不是XX-Net 已晕死或机器系统有变动，隧道一直不能正常连接而休眠，换了很多服务器也还是休眠，或许真的你是用不了了😂
或可尝试软件目录内的 disable_ipv6.bat 再 enable_ipv6.bat

**Comment by Ted12234** [comment]
> > 隧道一直休眠，换了很多服务器也还是休眠
> 
> 如果不是XX-Net 已晕死或机器系统有变动，隧道一直不能正常连接而休眠，换了很多服务器也还是休眠，或许你是真的不能用了😂
> 或
> 1、退出软件，删除 good_ip.txt，更换（曾经正常使用的）服务器，直到服务器已连接，再启动 #12043
> 或
> 2、可尝试软件目录内的 disable_ipv6.bat 再 enable_ipv6.bat

谢谢大神，我试试吧

**Comment by gang0122** [comment]
把原生ipv6关了，就是本地连接——属性——把internet 协议版本6的√取消

**Comment by Ted12234** [comment]
> 把原生ipv6关了，就是本地连接——属性——把internet 协议版本6的√取消

这个方法试过了，不行。最后换了一个wifi发现又可以用了。

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by SeaHOH** [comment]
> > 把原生ipv6关了，就是本地连接——属性——把internet 协议版本6的√取消
> 
> 这个方法试过了，不行。最后换了一个wifi发现又可以用了。

只要是可以看见的设备连接，都要取消 IPv6 勾选。
