### ISSUE TITLE
这是怎么回事呢。一直建议打开ipv6

### ISSUE THREAD

**Issue by hauchenjiang** [XX-net/XX-Net#12214]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by hauchenjiang** [comment]
> 估计超5成是——服务器名称：win1711.ipv6.microsoft.com.
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

类型                    : enterpriseclient
服务器名称              : teredo.iks-jena.de.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
估计错误。
一直建议打开ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0 ——有效 IP数归零
worker: h1:0 h2:0 ——连接池归零
#12043 更换服务器！

**Comment by Mopoma** [comment]
我的解决方案如下：
管理员运行CMD
netsh interface teredo set state server=teredo.remlab.net
netsh interface Teredo set state disable
netsh interface Teredo set state type=default

ping -6 ipv6.test-ipv6.com

**Comment by hauchenjiang** [comment]
> 我的解决方案如下：
> 管理员运行CMD
> netsh interface teredo set state server=teredo.remlab.net
> netsh interface Teredo set state disable
> netsh interface Teredo set state type=default
> 
> ping -6 ipv6.test-ipv6.com

Ping 请求找不到主机 ipv6.test-ipv6.com。请检查该名称，然后重试。

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）
