### ISSUE TITLE
等待扫描 IP，建议开启 IPv6。

### ISSUE THREAD

**Issue by MrLinNing** [XX-net/XX-Net#12222]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是

![image](https://user-images.githubusercontent.com/24288811/52549633-0c76a500-2e0f-11e9-8ec8-f6e68716a665.png)
日志：
2019-02-11 14:59:32.766 - [INFO] xxnet_version:3.13.1

2019-02-11 14:59:32.766 - [INFO] server 127.0.0.1:1080 started.

2019-02-11 14:59:32.766 - [INFO] Socks5 server listen:127.0.0.1:1080.

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by MrLinNing** [comment]
![image](https://user-images.githubusercontent.com/24288811/52550040-4c3e8c00-2e11-11e9-8981-0e0a5e7826f0.png)

**Comment by MrLinNing** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
win1711.ipv6.microsoft.com. ——服务器陷阱！
scan-ip-thread-num: 10 ——太小？
#12043

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by cryflame** [comment]
同问，感觉是ip6的问题
