### ISSUE TITLE
网络一直是Unmanaged

### ISSUE THREAD

**Issue by ArimaKisho** [XX-net/XX-Net#12223]
![e d jbmn5l n3k z ms](https://user-images.githubusercontent.com/30823089/52558176-91bc8280-2e2c-11e9-96d8-4501d45216ae.png)

**Comment by AnyWAT** [comment]
貌似 unmanaged/managed 并不影响使用（😥见到此问题前几乎一直 managed，现在 unmanaged ）。

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）
