### ISSUE TITLE
求大神分享有效IP和扫描出IP的方法

### ISSUE THREAD

**Issue by wtr19941227** [XX-net/XX-Net#12224]
求助，求高人指点。

XX-NET有效原生IPV6只剩下可怜的个位数，靠几个IP苦苦支撑了一段时间，现在网速几乎到了要停滞的地步，感觉快要撑不下去了。

希望遇贵人指点迷津，让XX-NET得以复活。
![111](https://user-images.githubusercontent.com/34266103/52569977-5d0cf300-2e4d-11e9-854a-114a2f1a0b31.png)

分享扫描IP的方法，万分感谢，感激不尽！！！

**Comment by AnyWAT** [comment]
> 让XX-NET得以复活

https://github.com/XX-net/XX-Net/issues/12189#issuecomment-459192395

**Comment by MadMaxPayne8964** [comment]
有两个原生IPv6 IP段可用，不在3.3.1中430多个IP中包含，好多人都找出来了，原生还是比teredo稳

**Comment by wtr19941227** [comment]
请您稍微详细的讲解一下，还是不太懂怎么操作，麻烦了 @MadMaxPayne8964

**Comment by wtr19941227** [comment]
没有效果，使用隧道连接有效IP迅速将为0

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by cryflame** [comment]
同问，有效ip为0
