### ISSUE TITLE
其实mac版一直很稳定，PC上不知怎么的，找的IP一用就掉光。

### ISSUE THREAD

**Issue by Mart1n82** [XX-net/XX-Net#12221]
RT，同样是最新版，mac上用的是miredo，PC是用命令行更换的一样的隧道服务器。
      同一个网络里（移动、电信都试了），mac能很快找到IP，并成功连接，PC版能扫IP，但是一用就很快掉光。
 原因是什么啊，不解。

**Comment by AnyWAT** [comment]
> 但是一用就很快掉光

只能说明该服务器不适用于此环境下的该PC？mac 与PC同时使用的同一（批）AppID？
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by Mart1n82** [comment]
本来不想折腾了，就一直没有回复。
MAC一直能用，miredo连上就可以，如果不行就反复禁用2~3次就可以了。
昨天重装了下PC，一下子就连了上，速度还很快。今天再开机又是扫一两个IP然后又掉了，IP一直不超过5个，我就很好奇了，昨天一切是正常的，说明PC是可以用的。

PC与MAC两台机器均使用同一个路由器，使用同一批appID。


这是PC的。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


这是MAC的。
XX-Net Status:

sys-platform: x86_64, Darwin-17.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64
os-release: 17.7.0
os-detail: Release:10.13.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:12
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:2
scan-ip-thread-num: 10
ip-quality: 383
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Mart1n82** [comment]
PC与MAC两台机器均使用同一个路由器，使用同一批appID，使用同一个teredo服务器teredo.remlab.net。
PC是win10系统，用不了。mac稳如老狗。就纳闷了。到底是哪里不同啊。

**Comment by AnyWAT** [comment]
只说PC
> ipv6-status: OK

貌似隧道已连接，但
> gws-ip-num: total:100 ipv4:0 ipv6:0 
> worker: h1:0 h2:0

已双归零，或如已说的
> 只能说明该服务器不适用于此环境下的该PC？

或因还有
> scan-ip-thread-num: 10

太小，甚至没关闭某开关？才
> PC版能扫IP，但是一用就很快掉光。

#12043 [隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。
![image](https://user-images.githubusercontent.com/37962734/54087118-c881ac00-438a-11e9-9a78-f90fdfd9fa16.png)

**Comment by AnyWAT** [comment]
> PC与MAC两台机器均。。。使用同一批appID

或许也有影响？

**Comment by Mart1n82** [comment]
谢谢解答。
手动禁用重启隧道，禁用重启网卡，组策略禁用ipv6，更换常用的几个地址，组策略禁用ipv6什么的，这些大家经常提到的各种方法都试了。心累啊😱

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/54087491-37143900-438e-11e9-93b6-fc4fb5631148.png)

**Comment by AnyWAT** [comment]
> 心累啊😱

#12043 Win32系统3.13.1隧道简单操作几乎启动即正常稳定，可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。
![image](https://user-images.githubusercontent.com/37962734/54087616-8444da80-438f-11e9-860a-188eb3abfc54.png)

**Comment by AnyWAT** [comment]
> 组策略

#12043 摒弃 IPv6 组策略法。。。
