### ISSUE TITLE
现在买X-Tunnel有意义吗？

### ISSUE THREAD

**Issue by NGSW-R** [XX-net/XX-Net#12228]
如题，希望能够不限制流量或者时间。

**Comment by gibwise** [comment]
超实惠机场推荐https://web.ssvss.xyz/register?aff=13988

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by AnyWAT** [comment]
首先得保证X-Tunnel 能正常运行，https://github.com/XX-net/XX-Net/issues/11892 3、X-Tunnel 正常的前提：。。。

**Comment by NGSW-R** [comment]
> 首先得保证X-Tunnel 能正常运行，#11892 3、X-Tunnel 正常的前提：。。。
> 隧道参考：#12043

你说的都不是人话，我看不懂

**Comment by AnyWAT** [comment]
已B👌

**Comment by NGSW-R** [comment]
> > 你说的都不是人话，我看不懂
> 
> 狗咬吕洞宾。已B👌

B什么B，标点符号都不会用，就你自己看得懂

**Comment by NGSW-R** [comment]
> > 你说的都不是人话，我看不懂
> 
> （不懂人话之）狗咬吕洞宾。已B👌

傻吊玩意儿一个回复可以编辑3次，可见语言能力之差

**Comment by Hunerk** [comment]
> > > 你说的都不是人话，我看不懂
> > 
> > 
> > （不懂人话之）狗咬吕洞宾。已乙ok_hand
> 
> 傻吊玩意儿一个回复可以编辑3次，可见语言能力之差

还可以用用https://www.ssrtool.com/tool/free_ssr

**Comment by varicella** [comment]
我觉得购买挺好的，免费的的确比较折腾，有时间可以继续研究，但是如果平时工作比较忙，买一个还是挺好的，说实话不贵。安卓版的X大也在更新中，也可以同时使用。

**Comment by nbwxbo** [comment]
能用，有时候会断。做个备用应急也好。蓝灯这2天也不行了。

**Comment by nbwxbo** [comment]
哪个兄弟能推荐个，不限流量的，便宜点的，板瓦工这种现在太贵了。本人主要玩油管youtuber,google ad的

**Comment by NGSW-R** [comment]
> > > > 你说的都不是人话，我看不懂
> > > 
> > > 
> > > （不懂人话之）狗咬吕洞宾。已乙ok_hand
> > 
> > 
> > 傻吊玩意儿一个回复可以编辑3次，可见语言能力之差
> 
> [https://www.ssrtool.com/tool/free_ssr还可以用用](https://www.ssrtool.com/tool/free_ssr%E8%BF%98%E5%8F%AF%E4%BB%A5%E7%94%A8%E7%94%A8)

这种免费的SS就怕安全问题

**Comment by NGSW-R** [comment]
> 我觉得购买挺好的，免费的的确比较折腾，有时间可以继续研究，但是如果平时工作比较忙，买一个还是挺好的，说实话不贵。安卓版的X大也在更新中，也可以同时使用。

我试用过X-Tunnel，还可以，但是有时候也会断，就怕哪天被完全墙了就悲剧了

**Comment by bibichuan** [comment]
主要是速度怎么样，能不能达到ssr七八十的延迟？虽然捐了几个appid。但是在考虑买一个了。

**Comment by varicella** [comment]
没有下载过东西，一般主要用于查询资料，用着没觉得很慢，之前有时候会断线，最近好像还好。
