### ISSUE TITLE
中國開抓了！「翻牆」罰比吸毒還重

### ISSUE THREAD

**Issue by iAPPOpen** [XX-net/XX-Net#12220]
刚刚无意中看到了这个新闻，是2019年的新事情哦，大家关注下

越来越看不懂一些人的回帖了，家属通知书/处罚决定书的图片都拍上来了，连公安部门都在官方网站上官方公布的信息（[官方发布页面](http://www.gdgafz.alldayfilm.com/bookDetail.html?type=1&id=1134323)）为何那么多人说是假的还是一眼就看出是假的，请教他们哪里看出是假的又什么都不说，只能当是说不出了，既然说不出哪里假又非说是假的，这究竟是什么逻辑呢

更不懂的就是那些回复不超过十个字的人，只留下了自己的名字，其他什么都没说，尤其是沙发那个自称是从一个名叫“哪”的地方来的名叫“沙雕”的网友，这是什么意思，名字好听？or 刷帖？

**Comment by l3125831q** [comment]
哪来的沙雕？

**Comment by hubsocks** [comment]
youtube上的cctv官媒,各地方卫视频道难道不是翻墙上传视频?

**Comment by AeneasZhu** [comment]
> youtube上的cctv官媒,各地方卫视频道难道不是翻墙上传视频?

不是的，一些需要涉外的组织像胡主编、华为之类的，他们是没有墙的，直接上。运营商也有直接通道。所以法理上他们并没有翻墙，因为他们就没有墙。

**Comment by Buccaneer01** [comment]
这些体制内的应该有官方的大门走，用不着翻墙

**Comment by Peterpey** [comment]
@iAPPOpen  第一个就抓你!

**Comment by AnyWAT** [comment]
😂WJ发话了？

**Comment by 2378** [comment]
今天半元钱也上班了 :scream:

**Comment by loy20002000** [comment]
不是的，一些需要涉外的组织像胡主编、华为之类的，他们是没有墙的，直接上。运营商也有直接通道。所以法理上他们并没有翻墙，因为他们就没有墙。

------------------

这么做的成本太高，不可能。

华为之类在海外有专门的服务器，换言之他们是不对民间提供服务的翻墙通道搭建者。

做个简单的测试就知道了。用网易的邮件大师登陆Gmail，Google官方的记录是在日本登陆。

**Comment by loy20002000** [comment]
youtube已经有n多人辟谣了。这种谣言就别传播了。

2017年曾经我也很慌，到头来是被境外媒体给忽悠了。

**Comment by hubsocks** [comment]
@loy20002000 qq邮箱也是海外建服务器传用?那北大,清华很多http代理能访问境外.那怎么说?百度免费代理,很多阿里,腾讯云国内的8118端口都的代理都可以看优土拨,
QQ邮箱app,也有人说是直接连没封的境外gmail.com服务器.
http://ping.chinaz.com/gmail.com 你试试.显示国内能连接的gmail.com服务器.

**Comment by loy20002000** [comment]
·@hubsocks

刚刚测试完，用你给出的链接。全部超时。


Nature的官网只要检测到中国ip访问或是中文界面浏览器，经常发VPN的广告，从侧面说明对学术机构也是不例外的。

阿里、腾讯这种在出口海底光缆的地方有专门通道是可能的，但是能够享受这种待遇的公司不会多，哪怕是国内一线的学术机构也不太可能有。清华、北大的人搞研究也得翻墙。

中国的相关法律法规是禁止未经备案或审查的翻墙，不是禁止翻墙。只要向政府提交报告，能够证明自建VPN通道属于必须，翻墙是合法的。

**Comment by loy20002000** [comment]
@hubsocks

补充一个说明。

为什么我说成本太高，不可能。假设A有特别的对外通道，A必须做到对外数据的自查自处理，另外必要条件有二，一是政治靠山牢靠，二是必须具备大数据分析能力。长城防火墙都做不到的事情，没有几个企业敢建，就算国家放行自己这关都过不了。腾讯、阿里属于特例，因为他们跟政府的关系特殊，不然光他们的股东及资本构成就够两位大佬牢底坐穿了。

这就是谁主张谁负责，通过自己的通道走过滤效率能有长城防火墙的1%就烧高香了。合理的结论是，大部分国企或院校都是通过VPN的方式访问外网，这不单单是技术或财力的问题，涉及到政治问题。

另外，连政府部门也是大部分走境外中转，不可能走直连。原因很简单，这涉及到国家安全。以美帝的渗透能力和找BUG的能力，如果政府部门可以自由访问外网也就意味着这些单位随时会中枪。360几年前一直在查国内的安全漏洞网站，结论是80%up是政府部门网站。

**Comment by hubsocks** [comment]
@loy20002000 你留个邮箱.只要是搞开发的.研究技术.没有不上google的.公开的代理是可以用的.但这些是都是有将数据发到公安和网信办的.用来学技术,查资料,看视频没问题.一般应用是够的.要求太高又怕审计的,肯定不能用这些.

**Comment by hubsocks** [comment]
@loy20002000 留个你觉得安全的邮箱.可瞬间测试代理.

**Comment by AnyWAT** [comment]
> @loy20002000 你留个邮箱.只要是搞开发的.研究技术.没有不上google的.公开的代理是可以用的.但这些是都是有将数据发到公安和网信办的.用来学技术,查资料,看视频没问题.一般应用是够的.要求太高又怕审计的,肯定不能用这些.

https://github.com/XX-net/XX-Net/issues/12216#issuecomment-462200289 那这些呢？

**Comment by xaviercw** [comment]
智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。

**Comment by iAPPOpen** [comment]
> 智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。

请说出哪里看出是编的

**Comment by xaviercw** [comment]
> > 智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。
> 
> 请说出哪里看出是编的

智障说的话还要去深究？就当放屁就完事了。

**Comment by qiaojiamin** [comment]
抓就抓呗，如果抓到我了我就把你们这些翻墙的全都抖出去，哈哈哈

**Comment by pinoren** [comment]
墙是不存在的！所以不存在翻墙！

**Comment by whz14** [comment]
> > 智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。
> 
> 请说出哪里看出是编的

这个为什么是编的不是一眼就能看出来吗

**Comment by iAPPOpen** [comment]
> 智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。
> 
> 请说出哪里看出是编的
> 
> 这个为什么是编的不是一眼就能看出来吗

没看出啊，所以才问啊，这一眼到底是看哪里呢

**Comment by iAPPOpen** [comment]
> 智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。
> 
> 请说出哪里看出是编的
> 
> 智障说的话还要去深究？就当放屁就完事了。

说说不也就一句话的事还用深究什么，我对毒品和翻墙都不太了解所以看不出问题，请指教

**Comment by imagx** [comment]
反串黑！！

**Comment by pinoren** [comment]
> > 智障湾湾？编新闻也用点脑子行不行，真怀疑那边的教育水平。
> > 请说出哪里看出是编的
> > 智障说的话还要去深究？就当放屁就完事了。
> 
> 说说不也就一句话的事还用深究什么，我对毒品和翻墙都不太了解所以看不出问题，请指教假在哪里，我以后也好分辨

是台湾朋友么？这种新闻其实有时候也是真真假假不太好说，有些是因为使用爬墙工具干了不该干的事儿，然后才被请进去了，放一般情况下找个软件搜个视频多数也没什么，都是睁只眼闭只眼。有些朋友回复可能比较冲动，大概以为你是在幸灾乐祸的吧？嘿嘿

**Comment by Sickid** [comment]
SB

**Comment by suijiafeng** [comment]
可怕，吓得我马上去看YouTube压压惊

________________________________
寄件者: qiaojiamin <notifications@github.com>
寄件日期: 星期一, 2月 11, 2019 10:11 下午
收件者: XX-net/XX-Net
副本: Subscribed
主旨: Re: [XX-net/XX-Net] 中_抓了！「翻」P比吸毒重 (#12220)


抓就抓呗，如果抓到我了我就把你们这些翻墙的全都抖出去，哈哈哈

―

**Comment by waitingHao** [comment]
> youtube上的cctv官媒,各地方卫视频道难道不是翻墙上传视频?

企业可申请合法vpn

**Comment by xaviercw** [comment]
又是这个智障湾湾，现在湾湾人智商都这水平？可怕
