### ISSUE TITLE
XX-NET是不是凉了，有没有其它的替代

### ISSUE THREAD

**Issue by huguiqi** [XX-net/XX-Net#12227]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by Peterpey** [comment]
凉了

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）

**Comment by retmania** [comment]
凉了，你看AnyWAT都退役了！

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/52695675-1aabf900-2fa8-11e9-8010-62ef7a812fd2.png)

**Comment by gibwise** [comment]
超实惠机场推荐 1元一个月https://web.ssvss.xyz/register?aff=13988

**Comment by AeneasZhu** [comment]
用you2php自己搭建油管镜像

**Comment by hubsocks** [comment]
@AnyWAT 你该不会是用以前的老光猫吧,现在大多都是运营商送的光猫.网络环境大不一样了.

**Comment by AnyWAT** [comment]
此乃光猫第一图，以往无。https://github.com/XX-net/XX-Net/issues/12085#issuecomment-454386459

**Comment by dtccao** [comment]
> 此乃（连上门师傅都未曾听说 IPv6）光猫第一图，以往无。[#12085 (comment)](https://github.com/XX-net/XX-Net/issues/12085#issuecomment-454386459)

感谢~~看了你的文章，我的xx-net用到现在

**Comment by xc1988** [comment]
自己搭了个梯子用...

**Comment by wz7465** [comment]
机器人换个小马甲自吹自唱？
![default](https://user-images.githubusercontent.com/7801728/52764336-8f3f7000-305a-11e9-856f-122ffd0581f6.png)

**Comment by AnyWAT** [comment]
> 自吹自唱

天打雷劈小马甲！能有啥好处？

**Comment by wz7465** [comment]
是吗，果真如此，我又相信爱情了，情人节凌晨两点不睡觉，专门爬起来注册一个号，就是为了表达对机器人的爱，这绝壁是真爱啊

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12228#issuecomment-463495584 能出于自吹自唱之口？

**Comment by BruceWang121** [comment]
推荐一个SSR节点，速度很快
https://ssrbank.com/register?aff=21005

**Comment by gang0122** [comment]
> 超实惠机场推荐 1元一个月https://web.ssvss.xyz/register?aff=13988

我看充值怎么是12元一个月啊

**Comment by dtccao** [comment]
> 机器人换个小马甲自吹自唱？
> ![default](https://user-images.githubusercontent.com/7801728/52764336-8f3f7000-305a-11e9-856f-122ffd0581f6.png)

哈哈哈哈……我不是马甲，之前什么都不懂，看了AnyWAT的教程才学会了更换巨硬服务器。不过你有一点说对了，我半夜看到这个帖子还真的就是特地注册一个账号来感谢AnyWAT的。

**Comment by dtccao** [comment]
> 是吗，果真如此，我又相信爱情了，情人节凌晨两点不睡觉，专门爬起来注册一个号，就是为了表达对机器人的爱，这绝壁是真爱啊

怎么样？我凌晨2点就是不睡觉，你咬我啊~

**Comment by AnyWAT** [comment]
> 怎么样？我凌晨2点就是不睡觉，你咬我啊~

2:51路过

**Comment by wz7465** [comment]
😄 老顽童的左右互博练的不错

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/5114 肿么了？

**Comment by wz7465** [comment]
有一事不明，为何你每发一个帖子，事后都要重新修改？
难道否定之自我否定？左右大脑都在抢地盘？

**Comment by AnyWAT** [comment]
已B👌

**Comment by AnyWAT** [comment]
某淫同党？https://github.com/XX-net/XX-Net/issues/12043#issuecomment-466666547
