### ISSUE TITLE
 config.py 修改总IP数 启动不了了

### ISSUE THREAD

**Issue by lianbookca** [XX-net/XX-Net#12225]
![xxx](https://user-images.githubusercontent.com/15099252/52576877-f17e5200-2e5b-11e9-8d42-3fe1db064739.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/52578879-0eb51f80-2e60-11e9-852b-7d918c611ea0.png)
1、config.py 貌似没有此行？修改总 IP数后启动不了了：英文逗号与数字之间有半角空格！
2、self.set_var("max_good_ip_num", 520)
修改总 IP数为520已落后时代几个月：大佬公布的才不足500，貌似200-250才合适！

**Comment by lianbookca** [comment]
@AnyWAT   这个自己后加上去的 不行吗  要在原文件 里面修改啊？
 self.set_var("max_good_ip_num", 520)

**Comment by lianbookca** [comment]
@AnyWAT 貌似改好了 
instagram  你平常用吗   网页看缓冲图片 老是缓冲不出来

**Comment by lianbookca** [comment]
@AnyWAT  总数增加 对速度能加快吗？

**Comment by AnyWAT** [comment]
> instagram 你平常用吗 网页看缓冲图片 老是缓冲不出来

不用。貌似没达到速度及稳定性较佳状态，可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。#12043

**Comment by echovae** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://jiasd.us/9449 （使用此链接，你我都能得到20%优惠）
