### ISSUE TITLE
打开start.vbs的时候，提示“Windows 无法访问指定设备、路径或文件。你可能没有适当的权限访问该项目。” 

### ISSUE THREAD

**Issue by rimmygee** [XX-net/XX-Net#12231]
打开start.vbs的时候，提示
“[Window Title]
E:\Program Files\XX-Net\start.vbs

[Content]
Windows 无法访问指定设备、路径或文件。你可能没有适当的权限访问该项目。”

**Comment by AnyWAT** [comment]
貌似路径内有空格的影响？试试复制到不含空格的位置。或
等待其他人的回答。。。

**Comment by rimmygee** [comment]
> 貌似路径内有空格的影响？试试复制到不含空格的位置。或
> 等待其他人的回答。。。

不是空格的问题……，只能等等大佬了……。

**Comment by qqzwc** [comment]
> > 貌似路径内有空格的影响？试试复制到不含空格的位置。或
> > 等待其他人的回答。。。
> 
> 不是空格的问题……，只能等等大佬了……。

升级后指向的版本号文件夹不存在，手动修改一下快捷方式指向的路径就好了吧？

**Comment by rimmygee** [comment]
> > > 貌似路径内有空格的影响？试试复制到不含空格的位置。或
> > > 等待其他人的回答。。。
> > 
> > 
> > 不是空格的问题……，只能等等大佬了……。
> 
> 升级后指向的版本号文件夹不存在，手动修改一下快捷方式指向的路径
