### ISSUE TITLE
休眠了

### ISSUE THREAD

**Issue by leoxxnet** [XX-net/XX-Net#12239]
AnyWAT,急救一下

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![image](https://user-images.githubusercontent.com/32661213/52896899-d23f4600-3208-11e9-9e58-0499645f4ddc.png)
![image](https://user-images.githubusercontent.com/32661213/52896903-e420e900-3208-11e9-8a27-378c15de3323.png)

**Comment by AnyWAT** [comment]
有原生 IP6时，隧道会自动休眠，否则得更换隧道服务器

**Comment by SeaHOH** [comment]
休眠可能是因为有 IPv6 网卡连接
