### ISSUE TITLE
最新版 miredo 1.2.6安装之后系统偏好设置没有图标

### ISSUE THREAD

**Issue by SnowDade** [XX-net/XX-Net#12238]
小白一枚，根据官方mac开启ipv6的说明，下载了miredo 1.2.6安装包进行安装，安装成功后没有在系统偏好设置中看miredo的图标，之前根据issue里说应该有这个图标然后点进去变绿灯才算是开启ipv6了。1.我的安装是否成功？2.如果没有这个图标我如何开启miredo？

System Version：macOSMojave 10.14.3
XX-NET：3.13.1

**Comment by left0077** [comment]
同没有图标。
我使用了 `port install miredo` 命令安装 miredo ，每次使用 `sudo miredo` 命令开启 miredo ,
使用 `sudo pkill miredo `命令关闭 miredo 

System Version：macOSMojave 10.14.3
XX-NET：3.13.1

**Comment by yangsl158** [comment]
同没有。。好不容易可以打开 start文件，结果 ipv6搞不定了。。10.13的时候一直很顺利。
