### ISSUE TITLE
扫不到ip???

### ISSUE THREAD

**Issue by dragonwang2016** [XX-net/XX-Net#12237]
C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : 195.140.195.140 (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : 5009  (Group Policy)
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
这样扫不到ip,要怎么扫了？

**Comment by AnyWAT** [comment]
扫不到ip貌似因该隧道服务器不适合你，#12043 【[找出并更换适用于自己的服务器]( )】

**Comment by AnyWAT** [comment]
> 客户端类型 : teredo host-specific relay

😱意外发现：开始是禁用原生 IPv6的正常隧道，有效 IP数/总 IP数之比=1，勾选网络属性内的 IPv6协议，在原生 IPv6连接上后，隧道就由 teredo client  变成了该种客户端类型，有效 IP数及连接池直线下降到接近0，IP延迟到9999。反之，取消勾选网络属性内的 IPv6协议以禁用原生，隧道变成 teredo client ，手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，恢复 。。。有效 IP数/总 IP数之比=1

😂原来楼主是没。。。
