### ISSUE TITLE
400多ip，一个有效的都没有，哎

### ISSUE THREAD

**Issue by tudouniurou** [XX-net/XX-Net#12241]
![image](https://user-images.githubusercontent.com/47689916/52899043-4f29ea00-3220-11e9-9730-3df14f51f1ae.png)
![image](https://user-images.githubusercontent.com/47689916/52899047-6ff23f80-3220-11e9-82c0-6535e4d53008.png)
昨儿好不容易弄好，今儿又废了

**Comment by rykiechan** [comment]
https://github.com/XX-net/XX-Net/issues/12205我用着这里参数修改了之后。。比较稳定了。。用的是微软服务器。。有效ip0~60个。。。总ip300

**Comment by tudouniurou** [comment]
我就照这些改的，都是当天有效，第二天就不行。。。

**Comment by tudouniurou** [comment]
> [https://github.com/XX-net/XX-Net/issues/12205我用着这里参数修改了之后。。比较稳定了。。用的是微软服务器。。有效ip0~60个。。。总ip300](https://github.com/XX-net/XX-Net/issues/12205%E6%88%91%E7%94%A8%E7%9D%80%E8%BF%99%E9%87%8C%E5%8F%82%E6%95%B0%E4%BF%AE%E6%94%B9%E4%BA%86%E4%B9%8B%E5%90%8E%E3%80%82%E3%80%82%E6%AF%94%E8%BE%83%E7%A8%B3%E5%AE%9A%E4%BA%86%E3%80%82%E3%80%82%E7%94%A8%E7%9A%84%E6%98%AF%E5%BE%AE%E8%BD%AF%E6%9C%8D%E5%8A%A1%E5%99%A8%E3%80%82%E3%80%82%E6%9C%89%E6%95%88ip0~60%E4%B8%AA%E3%80%82%E3%80%82%E3%80%82%E6%80%BBip300)

我就照这些改的，都是当天有效，第二天就不行。。。

**Comment by AnyWAT** [comment]
更换个适用于自己的隧道服务器超简单，哎 #12043
![image](https://user-images.githubusercontent.com/37962734/52899244-d7a98a00-3222-11e9-90bf-4ee29a3eeaf3.png)

**Comment by tudouniurou** [comment]
> 更换个适用于自己的隧道服务器超简单，哎 #12043
> ![image](https://user-images.githubusercontent.com/37962734/52899244-d7a98a00-3222-11e9-90bf-4ee29a3eeaf3.png)

照你写的那几个服务器换好几个啦。。。
![image](https://user-images.githubusercontent.com/47689916/52899278-44248900-3223-11e9-9653-474be4d47cc1.png)

**Comment by AnyWAT** [comment]
看到大家都说不能用，建议修改一下Teredo连接方式。 #12243

**Comment by neunundneunzig** [comment]
依然不行

**Comment by AnyWAT** [comment]
> 依然不行

贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by neunundneunzig** [comment]
不用贴12043给我，各种服务器也都换过了
最好的情况就是能连上但是延迟高到一千左右

类型                    : enterpriseclient
服务器名称              : 195.140.195.140
客户端刷新间隔          : 30 秒
客户端端口                : 7125
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 是


XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:14
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 367
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
尽管：
> 不用贴12043给我，各种服务器也都换过了
> 最好的情况就是能连上但是延迟高到一千左右

虽然：
> 状态 : qualified

但是：
> ipv6-status: Fail
> worker: h1:0 h2:0

显然这违背了 #12043 里的某规则，比”延迟高到一千左右“差远了，自己再仔细品味 #12043 ，BYEBTE

**Comment by neunundneunzig** [comment]
> 尽管：
> 
> > 不用贴12043给我，各种服务器也都换过了
> > 最好的情况就是能连上但是延迟高到一千左右
> 
> 虽然：
> 
> > 状态 : qualified
> 
> 但是：
> 
> > ipv6-status: Fail
> > worker: h1:0 h2:0
> 
> 显然这违背了 #12043 里的某规则，比”延迟高到一千左右“差远了，自己再仔细品味 #12043 ，BYEBYE

状态随时都在变
我现在ipv6-status ok了，还是连不上
依然是worker: h1:0 h2:0

如果你无法提供解决方案
请不要回复

**Comment by tudouniurou** [comment]
啥也不动：
前儿能用，昨儿不能用，今儿又能用，晚上又不能用（打比方）
延迟300网速慢，延迟一千反而能看youtube720p甚至1080p
操
