### ISSUE TITLE
macOS Mojave突然间就打不开xx-net了

### ISSUE THREAD

**Issue by hyxgame007** [XX-net/XX-Net#12247]
之前运行的好好的，从上周三开始，在iTerm上面执行start，或者直接运行start都没反应，然后到进程里面去看，就会有N个python进程（运行几个就有几个python进程），但是xx-net主界面打不开。不知道大家有遇到过没。我重新下载重试也不行

**Comment by hyxgame007** [comment]
之前运行的好好的，从上周三开始，在iTerm上面执行start，或者直接运行start都没反应，然后到进程里面去看，就会有N个python进程（运行几个就有几个python进程），但是xx-net主界面打不开。不知道大家有遇到过没。我重新下载重试也不行

**Comment by hahaniu666** [comment]
我这直接都打不开，命令行也打不开start

**Comment by valasco** [comment]
https://github.com/XX-net/XX-Net/issues/11978，不知道我的遭遇对2楼有没有用~

**Comment by Mart1n82** [comment]
是你不是下载的最新版重新安装的？全部是不可执行文件？，把start用老版本替换一下就行了。

**Comment by valasco** [comment]
> 是你不是下载的最新版重新安装的？全部是不可执行文件？，把start用老版本替换一下就行了。

嗯，重新安装，指向文件提升权限，sudo运行文件（还是要指向文件）后面就可以开机自动运行

**Comment by SeaHOH** [comment]
一般情况，结束旧进程就恢复正常。
