### ISSUE TITLE
ip为0

### ISSUE THREAD

**Issue by gudongFox** [XX-net/XX-Net#12249]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by gudongFox** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

诊断信息：XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

cmd显示信息：
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——几乎没有正常时候的隧道服务器陷阱！#12043

**Comment by gudongFox** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com. ——几乎没有正常时候的隧道服务器陷阱！#12043

春节前能用，但春节上班后就不能用了，这个陷阱是怎么回事？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12043#issuecomment-453439858 
![image](https://user-images.githubusercontent.com/37962734/52936556-6dfebc80-3397-11e9-94ce-1bc91f83d117.png)

貌似再也没有这种时候了😂

**Comment by AnyWAT** [comment]
除非已有原生 IPv6，会将任何服务器——状态 : dormant
但原生的效果不好，故网络属性内取消勾选 IPv6协议以禁用

**Comment by gudongFox** [comment]
> 除非已有原生 IPv6，会将任何服务器——状态 : dormant
> 但原生的效果不好，故网络属性内取消勾选 IPv6协议以禁用

禁用以后，也连不上，在http://test-ipv6.com/上ipv6测试都通不过

**Comment by AnyWAT** [comment]
> 这个陷阱是怎么回事？

https://github.com/XX-net/XX-Net/issues/12043#issuecomment-455761696
![image](https://user-images.githubusercontent.com/37962734/52937378-ee262180-3399-11e9-8ec7-0a6a470af914.png)

**Comment by AnyWAT** [comment]
> 禁用以后，也连不上，在[http://test-ipv6.com/上ipv6测试都通不过](http://test-ipv6.com/%E4%B8%8Aipv6%E6%B5%8B%E8%AF%95%E9%83%BD%E9%80%9A%E4%B8%8D%E8%BF%87)

https://github.com/XX-net/XX-Net/issues/12043 
![image](https://user-images.githubusercontent.com/37962734/52937466-2299dd80-339a-11e9-874a-52800bac43a5.png)

**Comment by gudongFox** [comment]
> > 禁用以后，也连不上，在[http://test-ipv6.com/上ipv6测试都通不过](http://test-ipv6.com/%E4%B8%8Aipv6%E6%B5%8B%E8%AF%95%E9%83%BD%E9%80%9A%E4%B8%8D%E8%BF%87)
> 
> #12043
> ![image](https://user-images.githubusercontent.com/37962734/52937466-2299dd80-339a-11e9-874a-52800bac43a5.png)

禁用以后没法开启ipv6，ipv6状态始终fail

**Comment by AnyWAT** [comment]
> 禁用以后没法开启ipv6，ipv6状态始终fail

逃出了隧道服务器陷阱？贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by gudongFox** [comment]
> > 禁用以后没法开启ipv6，ipv6状态始终fail
> 
> 逃出了隧道服务器陷阱？贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.42.234:64861
外部 NAT 映射    : 119.86.108.223:18568

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！！！
服务器名称 : win1711.ipv6.microsoft.com. ——逃出了隧道服务器陷阱！！！😱

**Comment by gudongFox** [comment]
> > 禁用以后没法开启ipv6，ipv6状态始终fail
> 
> 逃出了隧道服务器陷阱？贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

我更换teredo隧道，提示说best server is: win1711.ipv6.microsoft.com.脑壳痛。。。

**Comment by AnyWAT** [comment]
> 我更换teredo隧道，提示说best server is: win1711.ipv6.microsoft.com.脑壳痛。。。

https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器]( )】

**Comment by gudongFox** [comment]
> > 我更换teredo隧道，提示说best server is: win1711.ipv6.microsoft.com.脑壳痛。。。
> 
> #12043 【找出并更换适用于自己的服务器】

这个怎么找？0.0

**Comment by AnyWAT** [comment]
> 这个怎么找？0.0

😥把 #12043 顶楼浏览几遍：温故而知新

**Comment by xpf7622** [comment]
扫描IP不少，一访问youtube，马上降为0.

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12254#issuecomment-465465444 貌似能随时：有效 IP数/总 IP数之比值=1，没有“扫描IP不少，一访问youtube，马上降为0.” #12043

**Comment by dwightchiang** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:57 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


Microsoft Windows [版本 10.0.17134.590]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

ipv6协议禁用了，dns也换了，代理服务器都试了好多，就是连不上，刚换完代理服务器，ipv6的数量上升一下就掉没了，连接池几乎为0

**Comment by AnyWAT** [comment]
不必重复发帖 https://github.com/XX-net/XX-Net/issues/12261#issuecomment-466251137
