### ISSUE TITLE
域名ip勤换，但teredo状态几乎全是probe或offline

### ISSUE THREAD

**Issue by titiexe** [XX-net/XX-Net#12256]
之前195.140.195.140地址很好用
从昨天起，更换过不少域名和ip地址，但teredo状态几乎全是probe
或者偶尔是offline

![_20190220102333](https://user-images.githubusercontent.com/28986668/53062637-6278d600-34fc-11e9-8e51-bcbe60cb0913.png)
![_20190220102802](https://user-images.githubusercontent.com/28986668/53062646-686eb700-34fc-11e9-99bf-acc82e525cb8.png)

有解吗？

@AnyWAT

**Comment by AnyWAT** [comment]
原生 IPv6效果较差，网络连接属性内取消勾选 IPv6协议。
或许有了光猫/原生还是网络变坏，无光猫/原生时很正常的巨硬 157.56.149.60、94.245.121.251、157.56.144.215 都连接不上了，157.56.106.184、157.56.106.189 正常、效果依旧。
