### ISSUE TITLE
其实对于非原生ipv6用户来说3.13.1版本也是可以用的

### ISSUE THREAD

**Issue by busterian** [XX-net/XX-Net#12252]
我原本是想发个攻略，但是想到xx-net原作者（或是团队）在发布3.13.1后遇到大面积无法正常访问的情况也没有出来补充或是回复不由想到或许作者面临压力无法把这个项目继续下去。借助git上一些帖子还是可以找到办法虽然没有以前那么好用，所以请尽力去扒贴吧。

**Comment by royceone** [comment]
请写一篇攻略吧，谢谢。原作者或者团队可能因为某些原因，受到了政治攻击以及物理攻击，请一起将作者的意志延续下去

**Comment by ksit1110** [comment]
请写个攻略吧

**Comment by fzudust** [comment]
赞
