### ISSUE TITLE
【求助】win10的3.13.1版本无法启动start.vbs

### ISSUE THREAD

**Issue by mahomeL** [XX-net/XX-Net#12255]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是
* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

launcher/config：
![2019-02-19_204835](https://user-images.githubusercontent.com/18021029/53016127-ca410980-3487-11e9-988f-f2ca918da239.png)

launcher.log：
![2019-02-19_204847](https://user-images.githubusercontent.com/18021029/53016140-d0cf8100-3487-11e9-82c5-0307fb8e5a14.png)

**Comment by AnyWAT** [comment]
试试：手动下载、解压到非系统盘的新位置，不要复制任何旧文件

**Comment by mahomeL** [comment]
> 试试：手动下载、解压到非系统盘的新位置，不要复制任何旧文件

我年前还能用，年后就无法启动了，今天重新下来了，还是不行，已尝试解压到其他盘

**Comment by mahomeL** [comment]
下图是年前年后的launcher.log
![2019-02-19_210921](https://user-images.githubusercontent.com/18021029/53017318-a8955180-348a-11e9-9a94-4a9fc0c6a85e.png)

**Comment by AnyWAT** [comment]
> 下图是年前年后的launcher.log

学舌而已，看不懂。https://github.com/XX-net/XX-Net/wiki/How-to-get-start-error-log

**Comment by mahomeL** [comment]
求助大佬们。。。。。。
![2019-02-19_212658](https://user-images.githubusercontent.com/18021029/53018361-222e3f00-348d-11e9-9f34-929366c785b3.png)

**Comment by mahomeL** [comment]
已通过系统还原解决此问题
