### ISSUE TITLE
谷歌搜索结果自动跳转为bing

### ISSUE THREAD

**Issue by StephenAnboer** [XX-net/XX-Net#12259]
我使用的最新版本，配合switchyomega使用的时候，导入的本项目备份配置，使用gae-proxy自动切换模式，当规则列表格式为auto-proxy的时候，用谷歌搜索，会自动跳转到https://www.search323892.xyz/search/un/?n=50&q= ，然后跳转到bing搜索，不知道是为什么。。每次我手动将auto-proxy切换为switchy后问题就会消失。但是每次自动更新完情景模式以后，规则列表格式就会又自动切换成auto-proxy，谷歌搜索结果又会自动跳转为bing，每次都必须手动切换为switchy。
不知道大大们是否了解这个问题。。。

**Comment by AnyWAT** [comment]
开始准备建议试试更新SwitchyOmega 到 2.5.20，看到 https://github.com/FelisCatus/SwitchyOmega/issues/1750 说的是 SwitchyOmega 2.5.20，这里的是导入的本项目备份配置。。。
莫非受自3.9.6 。。。https://github.com/XX-net/XX-Net/issues/9501
貌似 auto-proxy 是正常的。试试另类的 gae-proxy 自动切换模式：Auto GAE
1、新建情景模式——PAC情景模式，名称如 GAE PAC，PAC 网址：http://127.0.0.1:8086/proxy.pac
2、新建情景模式——自动切换模式，名称如 Auto GAE，其它如图示
![image](https://user-images.githubusercontent.com/37962734/53141396-e7cabc00-35ca-11e9-8c4f-e7ccef1596fb.png)
3、”应用选项“，完成。

**Comment by StephenAnboer** [comment]
谢谢大佬回复
我用的就是SwitchyOmega 2.5.20版本，#9501的问题我也更改过了，现在默认是gae自动切换模式。
我按照你说的，新建立自动切换模式Auto GAE，规则列表网址使用http://127.0.0.1:8086/proxy.pac ，貌似默认的规则列表格式是switchy，我先试试，看看能不能解决问题，然后再过来反馈一下。
非常感谢！！

**Comment by AnyWAT** [comment]
> 貌似默认的规则列表格式是switchy

但实质应是后者 autoproxy 而不是 switchy ！

**Comment by StephenAnboer** [comment]
> 
> 但实质应是后者 autoproxy 而不是 switchy ！

刚刚测试完毕，还是不行，还是会跳转。。。不知道应该怎么办了，也不知道是为什么。。。

**Comment by AnyWAT** [comment]
出门右拐，官方 https://github.com/FelisCatus/SwitchyOmega/issues/1750

**Comment by StephenAnboer** [comment]
> 😂出门右拐，官方 [FelisCatus/SwitchyOmega#1750](https://github.com/FelisCatus/SwitchyOmega/issues/1750)

经过一通折腾，现在列表格式是switchy的时候也会跳转了😂😂😂那个帖子没人回复，很尬尴
不过我发现smart router是可以 用，且没有问题的，暂时用这个模式吧

谢谢大大啦

**Comment by SeaHOH** [comment]
查马杀毒
