### ISSUE TITLE
常年602，请帮忙看下问题到底在 哪里

### ISSUE THREAD

**Issue by DicTag** [XX-net/XX-Net#12258]
之前换teredo服务器 有短暂的半天可以用，之后就一直不行了，
怎么换ip都是要么probe；
要么有效ip数很低甚至为0；
要么延迟很高；
要么参数看不出问题但根本上不去外网；
要么上了两分钟就断。。
登录页面永远是登录进自己的账号，几乎只要一刷新或者隔2分钟就会抛出602。。
每次都是几小时几小时地折腾，却毫无生机，快要丧尸战斗信心了。。
也猜测和网络环境有关，有时候在公司就很容易连上，家里至少一周没成功连上了。。
请各位大神再帮忙看看，问题到底出在哪？

* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
3.13.1

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

 netsh int teredo show stat类型                    : enterpriseclient
服务器名称              : 195.140.195.140
客户端刷新间隔          : 30 秒
客户端端口                : 35599
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:42 ipv4:0 ipv6:16
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:13
scan-ip-thread-num: 30
ip-quality: 1737
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
能同时贴出 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息，貌似从 #12043 而来，有云：温故而知新。。。
> 常年602，请帮忙看下问题到底在 哪里

REN ！！！_[动手完全在自己！]( )_

**Comment by DicTag** [comment]
> 能同时贴出 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息，貌似从 #12043 而来，有云：温故而知新。。。
> 
> > 常年602，请帮忙看下问题到底在 哪里
> 
> REN ！！！_动手完全在自己！_ [#12254 (comment)](https://github.com/XX-net/XX-Net/issues/12254#issuecomment-465465444)
> 
> > Using_Public_Appid: true
> 
> 这也能揭示点神马

Appid几年前建的，我记得那时候10G还是多少流量，买了X-tunnel有1200G(虽然经常上不去基本都烂掉了) 就不用自己的小水管了。
刚刚部署了自己Appid，貌似还是不行。
另外最近总是出现CA证书fail和 浏览器代理fail，重新下载证书导入但没用，重新配置SwitchOmega也没用。。。而且我记得有一天我什么都没动，同样的配置第二天又能连上了。

![aa](https://user-images.githubusercontent.com/12840690/53101783-668d0e00-3565-11e9-9a42-80de38530367.png)

**Comment by AnyWAT** [comment]
> 另外最近总是出现CA证书fail和 浏览器代理fail，重新下载证书导入但没用，重新配置SwitchOmega也没用。。。而且我记得有一天我什么都没动，同样的配置第二天又能连上了。

如是，除非代理选用不对，貌似连接池太小的锅。

![image](https://user-images.githubusercontent.com/37962734/53102408-853fd480-3566-11e9-8d3c-791a0801fa14.png)

**Comment by DicTag** [comment]
啊啊啊。。。刚刚代理改成了GAE-proxy，竟然能上google了。。youtube稍微慢点但也能上了。。。那我x-tunnel买的流量是假的吗？？？混乱了。。。那选GAE-proxy时候用的是1200G里面的么？！难道我一直都选错了？之前选tunnel也能用啊，不是tunnel是付费gae是免费的 这样的逻辑吗？
![image](https://user-images.githubusercontent.com/12840690/53102409-85d86b00-3566-11e9-95ec-ff5e446e353f.png)
![image](https://user-images.githubusercontent.com/12840690/53102424-8ffa6980-3566-11e9-87f6-6bce15b62cce.png)

**Comment by AnyWAT** [comment]
如用 X-Tunnel，出现CA证书fail和 浏览器代理fail 的锅在：代理扩展图标上的附加数字内，有 *.deja.com 必走 GAE 等待手工处理（哪怕已有此规则）
![image](https://user-images.githubusercontent.com/37962734/53102762-5118e380-3567-11e9-9440-82ff7054a8b7.png)

**Comment by DicTag** [comment]
> 如用 X-Tunnel，出现CA证书fail和 浏览器代理fail 的锅在：代理扩展图标上的附加数字内，有未加载资源 *.deja.com 必走 GAE 等待手工处理（哪怕已有此规则）
 
我现在代理选x-tunnel几乎上不了外网，所以点代理扩展上的数字就几乎把所有外网添加成gae规则了，
那最后不就变成了其实都在走gae吗？。。我买的tunnel有什么用呢。。。应该tunnel更好才对啊QAQ。
tunnel正常的前提：
1.现在看起来就gae正常
2.指定服务器 
![image](https://user-images.githubusercontent.com/12840690/53105045-5bd57780-356b-11e9-8606-02cde8e1f540.png)
3.3个常年坏的所以常年关的
![image](https://user-images.githubusercontent.com/12840690/53105024-55470000-356b-11e9-8128-8edac2f04e93.png)

**Comment by AnyWAT** [comment]
> 所以点代理扩展上的数字就几乎把所有外网添加成gae规则了，

不明觉厉

**Comment by DicTag** [comment]
> > 我现在代理选x-tunnel几乎上不了外网，所以点代理扩展上的数字就几乎把所有外网添加成gae规则了，
> 
> 不明觉厉：即使如此，也可再编辑修改

代理选x-tunnel时，比如我用google搜1，就刷不出页面，角标提醒资源未加载，手动添加规则；
去youtube亦如是，去twitter,去facebook都这样。。那最后岂不是满屏的规则了QAQ，我就是很郁闷tunnel为什么这么不待见我。。。
![g](https://user-images.githubusercontent.com/12840690/53106074-42cdc600-356d-11e9-8114-dd8f0b5beade.png)
![y](https://user-images.githubusercontent.com/12840690/53106085-46614d00-356d-11e9-9ae4-1e4c89630690.png)

![p](https://user-images.githubusercontent.com/12840690/53106095-4c572e00-356d-11e9-9f7d-ff84e677857a.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/53106489-22523b80-356e-11e9-8e23-17c798ce4ca4.png)
先点选黄色末端的三角，选对代理。。。再”添加条件“——大笨钟😂

**Comment by DicTag** [comment]
> > 我现在代理选x-tunnel几乎上不了外网，所以点代理扩展上的数字就几乎把所有外网添加成gae规则了，
> 
> 不明觉厉：即使如此，也可再编辑修改

很感谢你，今天还是有收获的，太晚了明天再战吧，明天也许又是新的局面了。。。
现在是gae模式再去看了下数据
![image](https://user-images.githubusercontent.com/12840690/53106556-43b32780-356e-11e9-992d-ddbfc3466ce0.png)
妈耶，这是对夜游神的奖励么。。。扶额。。。
