### ISSUE TITLE
IPV6 状态失败，试了很多方法都不行，求救大神！

### ISSUE THREAD

**Issue by 827934453** [XX-net/XX-Net#12269]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
ipv6-status: Fail ——服务器不合适
scan-ip-thread-num: 10 ——太小
https://github.com/XX-net/XX-Net/issues/12262#issuecomment-466606238 
如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【[找出并更换适用于自己的服务器]( )】#12043

**Comment by 827934453** [comment]
C:\Uers\Suiyoubi\ping -6 ipv6.test-ipv6.com
Ping请求找不到该主机ipv6.test-ipv6.com。请检查该名称，然后重试。

**Comment by 827934453** [comment]
类型：enterpriseclient
服务器名称：terdo.iks-jena.de.
客户端刷新间隔：30秒
客户端端口：unspercified
状态：offline
错误：无

试过切换100个IP地址，结果还是offline

**Comment by AnyWAT** [comment]
> C:\Uers\Suiyoubi\ping -6 ipv6.test-ipv6.com
> Ping请求找不到该主机ipv6.test-ipv6.com。请检查该名称，然后重试。

#12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启隧道以来，一直正常一直不用此玩意儿😡

**Comment by AnyWAT** [comment]
> 试过切换100个IP地址

大佬首现江湖😱

**Comment by AnyWAT** [comment]
😜海军兄的
> 服务器名称：terdo.iks-jena.de.

是怎么来的？拼写错误，应是：teredo.iks-jena.de.
![image](https://user-images.githubusercontent.com/37962734/53282026-ff41aa80-376c-11e9-9208-bf0005154f1e.png)

**Comment by 827934453** [comment]
拼写错误（手动滑稽），我今晚再试一试。


Mobil： 13286077742E-mail：huangxinglang@ronsen.com.cn
 发件人： AnyWAT发送时间： 2019-02-23 13:16收件人： XX-net/XX-Net抄送： 827934453; Author主题： Re: [XX-net/XX-Net] IPV6 状态失败，试了很多方法都不行，求救大神！ (#12269)????海军兄的



服务器名称：terdo.iks-jena.de.



是怎么来的？拼写错误，应是：teredo.iks-jena.de.
