### ISSUE TITLE
好几天了 一直连不上 什么问题

### ISSUE THREAD

**Issue by zhangbin0922** [XX-net/XX-Net#12262]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
不是撞大运：#12043

**Comment by zhangbin0922** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>* netsh int ipv6 show teredo
'*' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant


C:\Users\Administrator>

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——几乎没有正常的时候的隧道服务器陷阱！#12043

**Comment by hubsocks** [comment]
根本解决方法,退出XX-Net,再打开,马上就好了.3.13.1版的扫描线程要设为0.

**Comment by AnyWAT** [comment]
不是：
隧道服务器能连接 ，不是状态 : dormant，将最大扫描线程数设置为0，use-ipv6: force_ipv6——改为自动
导入 IP4 #11775
导入 IP6 https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138 
可以玩玩？

**Comment by AnyWAT** [comment]
> 根本解决方法,退出XX-Net,再打开,马上就好了.3.13.1版的扫描线程要设为0.

贴图，证明在正常用 win1711.ipv6.microsoft.com.

**Comment by hubsocks** [comment]
![fdfsdsd](https://user-images.githubusercontent.com/46856823/53215444-a3532500-368b-11e9-9bb8-e35b12aa0787.png)

**Comment by AnyWAT** [comment]
😜LS 能证明是在使用服务器 win1711.ipv6.microsoft.com. ？

**Comment by hubsocks** [comment]
@AnyWAT 原生ipv6比 Teredo 稳定的多. 不管那种方式,都会遇到XX-Net出错了ipv6错误,只要退出它,再打开马上就全好了.只能等作者修复这个bug了.

**Comment by AnyWAT** [comment]
> 原生ipv6比 Teredo 稳定的多.

😝https://github.com/XX-net/XX-Net/issues/12043#issuecomment-465050996

**Comment by Peterpey** [comment]
没什么问题 连不上是正常的

**Comment by zhangbin0922** [comment]
> 根本解决方法，退出XX型网，再打开，马上就好了.3.13.1版的扫描线程要设为0。

没用啊

**Comment by AnyWAT** [comment]
> 没用啊

Ta 宁愿用劣于隧道的原生。如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【[找出并更换适用于自己的服务器]( )】#12043

**Comment by xlwmin** [comment]
你可能需要看看这个
https://github.com/XX-net/XX-Net/issues/12271#issuecomment-466717894
