### ISSUE TITLE
换了路由器就不能用了

### ISSUE THREAD

**Issue by 1813195468** [XX-net/XX-Net#12270]
![2019-02-23 192127](https://user-images.githubusercontent.com/29517226/53285844-c02d4c80-37a0-11e9-9f3b-267637861a56.jpg)
![2019-02-23 192202](https://user-images.githubusercontent.com/29517226/53285846-c6232d80-37a0-11e9-8aa2-5b36cdad84ad.jpg)

**Comment by 1813195468** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:98 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by MadMaxPayne8964** [comment]
把路由UPNP打开试试

**Comment by 1813195468** [comment]
> 把路由UPNP打开试试

打开了但没有用啊

**Comment by 1813195468** [comment]
![2019-02-23 201717](https://user-images.githubusercontent.com/29517226/53286356-3a150400-37a8-11e9-962b-21f380a28dfa.jpg)

**Comment by 1813195468** [comment]
需不需要重新启动一下啊

**Comment by AnyWAT** [comment]
> 换了路由器就不能用了

实质是：隧道服务器不合适，与路由器无关 
https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671
https://github.com/XX-net/XX-Net/issues/12262#issuecomment-466606238
如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【[找出并更换适用于自己的服务器]( )】#12043

**Comment by 1813195468** [comment]
> 换了路由器就不能用了
> 
> 实质是：隧道服务器不合适，与路由器无关
> #12043 (comment)
> #12262 (comment)
> 如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【找出并更换适用于自己的服务器】#12043

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 1813195468** [comment]
换了隧道但是有效IP数量太少了

> 换了路由器就不能用了
> 
> 实质是：隧道服务器不合适，与路由器无关
> #12043 (comment)
> #12262 (comment)
> 如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【找出并更换适用于自己的服务器】#12043

**Comment by AnyWAT** [comment]
> 换了隧道但是有效IP数量太少了

![image](https://user-images.githubusercontent.com/37962734/53287277-d9d88f00-37b4-11e9-9cf0-d0df806d7a44.png)
![image](https://user-images.githubusercontent.com/37962734/53287291-02f91f80-37b5-11e9-9a38-ff7d42ac9538.png)

**Comment by 1813195468** [comment]
> 换了隧道但是有效IP数量太少了

用什么好用的隧道ip可以推荐下吗

win10.ipv6.microsoft.com. 157.56.106.189 （已变 157.56.149.60 ）
win1710.ipv6.microsoft.com. 157.56.106.189 （已变 157.56.144.215 ）
win1711.ipv6.microsoft.com. 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）已变 13.64.36.145 弃用
win1807.ipv6.microsoft.com. 40.81.250.180（此 IP或许能连但很糟糕！弃用或自测）已变 40.81.186.117 弃用
前三项曾经都指向了157.56.149.60 （目前仍正常。巨硬服务器域名所对应的 IP时常变化，但各 IP状态貌似一直稳定：可用的保持可用，不可用的保持不可用😂）下面不带域名者是由 @ARCHOTZ 所提供的巨硬服务器
157.56.149.60（与前述重复）
157.56.144.215
157.56.106.184
65.55.158.118（鄙人弃用，其它OK）
157.56.106.189（与前述重复）
94.245.121.251
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo2.remlab.net. 83.170.6.77
teredo-debian.remlab.net. 83.170.6.76
这些都试过了，都是ip一会就没了

**Comment by AnyWAT** [comment]
> 用什么好用的隧道ip可以推荐下吗

【[找出并更换适用于自己的服务器]( )】——能代劳？正用 195.140.195.140，效果图如前已发。

> 这些都试过了，都是ip一会就没了

https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671 早些天所知全部，已知：157.56.149.60、94.245.121.251、157.56.144.215、83.170.6.77 不适用于鄙人。

https://github.com/XX-net/XX-Net/issues/12269#issuecomment-466615623 今天认识一大海军兄，100个IP地址——（隧道服务器）大神首现江湖😱

**Comment by 1813195468** [comment]
> 用什么好用的隧道ip可以推荐下吗
> 
> 【找出并更换适用于自己的服务器】——能代劳？正用 195.140.195.140，效果图如前已发。
> 
> 这些都试过了，都是ip一会就没了
> 
> 已是所知全部。 #12043 (comment) 早些天已知：157.56.149.60、94.245.121.251、157.56.144.215、83.170.6.77 不再适用于鄙人——貌似可用服务器减少，网络恶化？
> #12269 (comment) 今天认识一大海军兄，100个IP地址——（隧道服务器）大神首现江湖😱

netsh int ipv6 set teredo enterpriseclient 195.140.195.140
命令行我输入是否正确

**Comment by AnyWAT** [comment]
> 命令行我输入是否正确

有 #12043 及下图（其实也是咕噜话）还提出如此问题，貌似
> 换了隧道但是有效IP数量太少了

不是服务器而是REN的问题😝
![image](https://user-images.githubusercontent.com/37962734/53287716-10190d00-37bb-11e9-99d3-d6025e279c6d.png)

**Comment by 1813195468** [comment]
> 命令行我输入是否正确
> 
> 有 #12043 及下图（其实也是咕噜话）还提出如此问题，貌似
> 
> 换了隧道但是有效IP数量太少了
> 
> 不是服务器、软件而是REN的问题😝（严重怀疑会按 #12043 设置、操作！）

可以给一下解决方法吗

**Comment by 1813195468** [comment]
![2019-02-24 125841](https://user-images.githubusercontent.com/29517226/53295339-10a1ba00-3834-11e9-8298-f46ca2bf3adf.jpg)
