### ISSUE TITLE
等待扫描ip,建议开启ipv6

### ISSUE THREAD

**Issue by zpc870921** [XX-net/XX-Net#12272]
好多天了，一直没解决

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xlwmin** [comment]
你可能需要看看这个
https://github.com/XX-net/XX-Net/issues/12271#issuecomment-466717894

**Comment by AnyWAT** [comment]
> 好多天了，一直没解决

无非是掉进了服务器陷阱——能连接但扫描不出 IP的推荐隧道：win1711.ipv6.microsoft.com.  https://github.com/XX-net/XX-Net/issues/12043#issuecomment-455761696 
![image](https://user-images.githubusercontent.com/37962734/53295534-611b1680-3838-11e9-85a6-3c140704178e.png)

**Comment by ZXJohn** [comment]
同问，什么情况啊，更新之后再也没连上过了
XX-Net Status:
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
