### ISSUE TITLE
xxnet连不上，试试lostcloud吧

### ISSUE THREAD

**Issue by jxst590966** [XX-net/XX-Net#12279]
https://lostcloud.org/auth/register?code=95IV5U0jW4m51243

**Comment by ksit1110** [comment]
这是什么东西？

**Comment by jackbaifool** [comment]
广告呀

**Comment by jxst590966** [comment]
说广告也没错，邀请一个人注册送5个G，新注册的用户也送5个G，反正我用着还行




在 2019-02-25 19:42:19，"jackbaifool" <notifications@github.com> 写道：


广告呀

**Comment by jxst590966** [comment]
FQ软件，邀请一个人注册送5个G，新注册的用户也送5个G，速度比xxnet要快





在 2019-02-25 14:16:22，"ksit" <notifications@github.com> 写道：


这是什么东西？
