### ISSUE TITLE
Ipv6的IP数只有十几个，可以连上但不稳定 怎么增加

### ISSUE THREAD

**Issue by Illchange** [XX-net/XX-Net#12271]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
（弃原生）用隧道 #12043

**Comment by xugaohui** [comment]
用原生ipv6和ipv4.目前原生ipv6总共可用ip不到10个，但比你用隧道稳定。ipv4也还有8个左右可以用。

**Comment by AnyWAT** [comment]
> 但比你用隧道稳定

哈——哈——哈 
https://github.com/XX-net/XX-Net/issues/12262#issuecomment-466254281
https://github.com/XX-net/XX-Net/issues/12262#issuecomment-466606238

**Comment by xugaohui** [comment]
你肯定不是用的移动宽带

**Comment by AnyWAT** [comment]
> 你肯定不是用的移动宽带

再来一次：https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671

**Comment by xugaohui** [comment]
你先证明你上面两百多个可以ip是移动宽带网。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11559#issuecomment-429531637
https://github.com/XX-net/XX-Net/issues/11559#issuecomment-429558285

**Comment by xugaohui** [comment]
这下你承认了不是在用移动宽带。

**Comment by AnyWAT** [comment]
> 这下你承认了不是在用移动宽带。

上上楼不是证明移动，是承认非移动？啥逻辑？😡

**Comment by xlwmin** [comment]
说的简单的，就是更换teredo服务器，经过我几天的测试
netsh int ipv6 set teredo enterpriseclient 195.140.195.140
netsh int ipv6 set teredo enterpriseclient 83.170.6.76
netsh int ipv6 set teredo enterpriseclient 157.56.106.184
netsh int ipv6 set teredo enterpriseclient 157.56.106.189

用这几个服务器轮流切换一下，就能保证IP稳定超过50（免费用户）

![2019-02-24_082813](https://user-images.githubusercontent.com/5059521/53293411-45027f80-380e-11e9-8074-95a6c742a2eb.png)

**Comment by AnyWAT** [comment]
#12043 如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【[找出并更换适用于自己的服务器]( )】
可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。
![image](https://user-images.githubusercontent.com/37962734/53295442-80b13f80-3836-11e9-836c-a293dce2fc63.png)
除非你使用的服务器像图中几个一样某天开始下线，否则天天正常没问题。
LS貌似最大扫描线程数太小，甚至没关闭某开关？才：
有效 IP数 < 总 IP数，连接池太小（ IP延迟倒还可以）

**Comment by xlwmin** [comment]
> #12043 如用隧道，禁用网络属性内的 IPv6 协议，关闭某开关，【找出并更换适用于自己的服务器】
> 可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。
> ![image](https://user-images.githubusercontent.com/37962734/53295442-80b13f80-3836-11e9-836c-a293dce2fc63.png)
> 除非你使用的服务器像图中几个一样某天开始下线，否则天天正常没问题。
> LS貌似最大扫描线程数太小，甚至没关闭某开关？才：
> 有效 IP数 < 总 IP数，连接池太小（ IP延迟倒还可以）

我其实不需要那么多IP和扫描，扫描本身我就设置的很小才10，不需要频繁扫描。

**Comment by enxia** [comment]
> 说的简单的，就是更换teredo服务器，经过我几天的测试
> **netsh int ipv6 set teredo enterpriseclient 195.140.195.140 netsh int ipv6 set teredo enterpriseclient 83.170.6.76 netsh int ipv6 set teredo enterpriseclient 157.56.106.184 netsh int ipv6 set teredo enterpriseclient 157.56.106.189**
> 
> 用这几个服务器轮流切换一下，就能保证IP稳定超过50（免费用户）
> 其中最稳定的是 **83.170.6.76**
> 
> ![2019-02-24_082813](https://user-images.githubusercontent.com/5059521/53293411-45027f80-380e-11e9-8074-95a6c742a2eb.png)

求问大神，如何改服务器呢

**Comment by xlwmin** [comment]
> > 说的简单的，就是更换teredo服务器，经过我几天的测试
> > **netsh int ipv6 set teredo enterpriseclient 195.140.195.140 netsh int ipv6 set teredo enterpriseclient 83.170.6.76 netsh int ipv6 set teredo enterpriseclient 157.56.106.184 netsh int ipv6 set teredo enterpriseclient 157.56.106.189**
> > 用这几个服务器轮流切换一下，就能保证IP稳定超过50（免费用户）
> > 其中最稳定的是 **83.170.6.76**
> > ![2019-02-24_082813](https://user-images.githubusercontent.com/5059521/53293411-45027f80-380e-11e9-8074-95a6c742a2eb.png)
> 
> 求问大神，如何改服务器呢

**打开命令行（管理员权限）：**
![2019-02-24_212221](https://user-images.githubusercontent.com/5059521/53299789-571a0780-387a-11e9-84fe-d874e7809621.png)

**Comment by Illchange** [comment]
> 说的简单的，就是更换teredo服务器，经过我几天的测试
> **netsh int ipv6 set teredo enterpriseclient 195.140.195.140 netsh int ipv6 set teredo enterpriseclient 83.170.6.76 netsh int ipv6 set teredo enterpriseclient 157.56.106.184 netsh int ipv6 set teredo enterpriseclient 157.56.106.189**
> 
> 用这几个服务器轮流切换一下，就能保证IP稳定超过50（免费用户）
> 其中最稳定的是 **83.170.6.76**
> 
> ![2019-02-24_082813](https://user-images.githubusercontent.com/5059521/53293411-45027f80-380e-11e9-8074-95a6c742a2eb.png)

非常感谢！
