### ISSUE TITLE
貌似墙又高了，表现为IP减少和Pythonw会经常被结束

### ISSUE THREAD

**Issue by Alobe007** [XX-net/XX-Net#12276]
移动宽带，3.13.1。以前的IP数一直是满的，延迟在200-400之间。很好用。前两天，没有动任何配置情况下，突发IP6数大大下降，延迟高到1000以上（尚可出去），且经常IPV6 Fail出不去。进光猫看，发现IPV6的连接信息全空了。问移动客服，只说在调整数据库，其它不知道。

尝试切换了多个Teredo服务器，有作用。看来一个办法是在封锁Teredo服务器。但估计还有其它，因为即使Teredo服务器可用，扫出的IP数也很难上去。现在的状况就是IP数少，延迟高。

还有个新情况就是Pythonw.exe经常会出问题被杀掉。以前从来没有过。

现在状况：
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:200 ipv4:0 ipv6:8
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:0 h2:7
scan-ip-thread-num: 30
ip-quality: 2734
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jackbaifool** [comment]
现在只能靠运气

**Comment by AnyWAT** [comment]
> 进光猫看，发现IPV6的连接信息全空了。问移动客服，只说在调整数据库，其它不知道。
> 尝试切换了多个Teredo服务器，有作用。

既用隧道，与原生 IPV6无关！网络属性内必须取消勾选 IPV6协议以禁用原生 ！https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671

> 因为即使Teredo服务器可用，扫出的IP数也很难上去。

如果能扫出 IP，说明服务器可用。可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。https://github.com/XX-net/XX-Net/issues/12043

> gws-ip-num: total:200 ipv4:0 ipv6:8
> worker: h1:0 h2:7
> scan-ip-thread-num: 30

200与30 不匹配，最后结果不佳：8和7

**Comment by Alobe007** [comment]
> > 进光猫看，发现IPV6的连接信息全空了。问移动客服，只说在调整数据库，其它不知道。
> 
> 既用隧道，与原生 IPV6无关！网络属性内必须取消勾选 IPV6协议以禁用原生 ！
属性里已经禁了。这里只是叙述一下发现问题后所看到的变化状况。

**Comment by Alobe007** [comment]
> > gws-ip-num: total:200 ipv4:0 ipv6:8
> > worker: h1:0 h2:7
> > scan-ip-thread-num: 30
> 
> 200与30 不匹配，是否关闭了某开关？最后结果不佳：8和7
可能是高级设置里，“设置级别”设为了“极端”的缘故。但这个设置似乎没有太大影响（8和7这是获取诊断信息时的状况，恰好比较差。一般在20个IP左右）。即使设成“正常”，也扫不满IP。例如现在我调成了“正常”，状况是：
有效 IPv6 IP 数 | 68
总 IP 数 | 100
IP 延迟 | 1164

**Comment by AnyWAT** [comment]
> 还有个新情况就是Pythonw.exe经常会出问题被杀掉。以前从来没有过。

早就有XX-Net 自动退出，偶尔遇到

**Comment by AnyWAT** [comment]
> 是否关闭了某开关？

关闭“自动调整扫描线程数”开关。



> 可能是高级设置里，“设置级别”设为了“极端”的缘故。但这个设置似乎没有太大影响（8和7这是获取诊断信息时的状况，恰好比较差。一般在20个IP左右）。即使设成“正常”，也扫不满IP。例如现在我调成了“正常”，状况是：

忽略“极端”与“正常”，#12043 [速度及稳定性较佳体验之秘籍]( )

**Comment by Alobe007** [comment]
> > 是否关闭了某开关？
> 
> 关闭“自动调整扫描线程数”开关。

关着的。

**Comment by Alobe007** [comment]
> > 可能是高级设置里，“设置级别”设为了“极端”的缘故。但这个设置似乎没有太大影响（8和7这是获取诊断信息时的状况，恰好比较差。一般在20个IP左右）。即使设成“正常”，也扫不满IP。例如现在我调成了“正常”，状况是：
> 
> 忽略“极端”与“正常”，#12043 速度及稳定性较佳体验之秘籍

多谢。照着去试试。

**Comment by Alobe007** [comment]
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : teredo-debian.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
**NAT                     : restricted**
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

这个restricted是否不正常？

**Comment by AnyWAT** [comment]
> 类型 : client
natawareclient 好过 enterpriseclient 好过 client，Win7不支持 natawareclient

> 这个restricted是否不正常？

以是否能扫出 IP为准。

**Comment by tongchao0713** [comment]
@AnyWAT，首先感谢哥们的热心，本人也是老白一个。可以说你是这个项目里当前最活跃的“老白”了，潜水很久，最近几个月xxnet出的各种问题，都用你的办法得到改善。但是一直有一个疑问：请问阁下的母语是否是中文，因为看到兄弟的帮助文章很多的语法有误，虽然也能看明白，但是看的很累。故有此一问。如有冒失之处请见谅，再次感谢你的热心与知识的分享~
