### ISSUE TITLE
XX-net无法播放NetFlix……

### ISSUE THREAD

**Issue by dtccao** [XX-net/XX-Net#12278]
XX-net无法播放NetFlix，每次都被重新定向到https://help.netflix.com/zh-tw/node/23742
问了NetFlix的客服他们说查到我的账户是在一台移动设备登录，而不是PC浏览器。

**Comment by gibwise** [comment]
可以试试下面机场 
https://lostcloud.org/auth/register?code=2su14C4q484g30Q0
https://bighead.szccmdj.com.cn/register?aff=2166&code=E35C0039DE2C
https://bighead.szccmdj.com.cn/register?aff=2166&code=A6A5D0481AB3
https://bighead.szccmdj.com.cn/register?aff=2166&code=A57E1A1AADA1
https://web.ssvss.xyz/register?aff=13988

**Comment by zmy0730** [comment]
> XX-net 无法播放 NetFlix，每次都被重新定向到 https://help.netflix.com/zh-tw/node/23742
> 问了 NetFlix 的客服他们说查到我的账户是在一台移动设备登录，而不是 PC 浏览器。

老哥你解决了没？这边我也是报错用XXnet看不了Netflix。。。咨询某宝居然客服告诉我是XXnet不支持。。 我只用XXnet...
