### ISSUE TITLE
用XX翻墙以后没法去日亚购物

### ISSUE THREAD

**Issue by niubi9527** [XX-net/XX-Net#12273]
网站打开都没问题速度也很快 就是点加入购物车或者现在购买就弹出错误 

ご迷惑をおかけしています！
お客様のリクエストの処理中にエラーが発生しました。できるだけ早くこの問題を解決いたします。注文手続きの途中でこのエラーが表示された場合は、注文は確定されていませんので、ご注意ください。ご不便をおかけして申し訳ございません。

网上搜了下说是梯子的问题 请问下该怎么解决啊？？

**Comment by AnyWAT** [comment]
如是GAE不行，试试X-Tunnel

**Comment by loy20002000** [comment]
这个错误提示等于什么也没有讲。

如果日语够OK的话，还是联系客服吧。
