### ISSUE TITLE
我有一个比较傻瓜的问题，希望得到解答。

### ISSUE THREAD

**Issue by moonpeng** [XX-net/XX-Net#12280]
> ```xx-net``` 我现在使用的是```X-Tunnel```情景模式，我现在有两个疑问。

- 那我还需要开启```IPv6```吗
- 我需要部署```GAE AppID```吗

_尴尬的是我上面2点都配置了，貌似感觉是快了点，这是我的心里作用吗？_

**Comment by AnyWAT** [comment]
X-Tunnel 正常的前提：GAE 前端或其它前端正常（其它除了Cloudflare，另外3个没有正常的时候，禁用）https://github.com/XX-net/XX-Net/issues/11892 X-Tunnel 正常的前提：。。。
GAE （前端）正常的前提：IPv6 隧道正常（开启 IPv6），原生远没有隧道的效果好
如果仅用X-Tunnel，即使公共GAE AppID有使用限制，貌似不需要部署GAE AppID？

**Comment by xiaoteai** [comment]
![a3 dm _ od8 5 qlzxg heb](https://user-images.githubusercontent.com/10782704/53351926-e0a20600-395c-11e9-874d-daeac1f0c40d.jpg)
Any WAT  完成了

**Comment by xiaoteai** [comment]
win10 的那个服务器 太恶心了 


          老是陷阱的 那个    帮我改为别的服务器 教程有吗

**Comment by xiaoteai** [comment]
AnyWAT 谢谢啊 给个回话

**Comment by hubsocks** [comment]
不用开启ipv6 ,目前ipv6看视频时Dropped Frames率值很高.软件易出错.
ipv4丢帧率很低.
公共appid只有每个帐号每天1G流量限制.xx-net刚出来时公共appid不能看视频,目前早以没这个限制了.
![111jpg](https://user-images.githubusercontent.com/46856823/53388510-6312e000-39c6-11e9-8970-6eec31a64be9.jpg)
ipv4丢帧率完胜ipv6,20/49451
![11111](https://user-images.githubusercontent.com/46856823/53388512-65753a00-39c6-11e9-9aab-ab068af9b529.png)

**Comment by AnyWAT** [comment]
> AnyWAT 谢谢啊 给个回话

也许只是你的视而不见：#12043

**Comment by AnyWAT** [comment]
> 不用开启ipv6 ,。。。ipv4丢帧率很低.

😱厉害，use-ipv6: force_ipv4

**Comment by SeaHOH** [comment]
那个谁，睁眼瞎还是脑袋不灵光？不要胡乱引用我的发言。

@hubsocks 你这个情况还可以，不过某些地区可能封锁的更严。
