### ISSUE TITLE
证书已导入，怎么还是显示：浏览器代理设置：Fail 、CA 证书状态(下载)：Fail呢？请教大侠们！谢谢！！！

### ISSUE THREAD

**Issue by ilgithubol** [XX-net/XX-Net#12283]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:7
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:5
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by vampirefu** [comment]
restart your PC  and have a try

**Comment by AnyWAT** [comment]
9成以上掉进了隧道服务器陷阱！#12043

**Comment by CompleX0321** [comment]
尝试使用托盘设置中的“全局通过GAEProexy代理”选项
更新3.13.1之后本人使用上一直需要这样

**Comment by SongtaoGit** [comment]
> 9成以上掉进了 win1711.ipv6.microsoft.com. 隧道服务器陷阱！#12043

我就是按照那个掉坑里了，怎么才能搞回来呢？求帮忙

**Comment by AnyWAT** [comment]
> 我就是按照那个掉坑里了，怎么才能搞回来呢？求帮忙

浏览 #12043 顶楼，即有答案

**Comment by fhq8800** [comment]
看不明白，我的一直都是这样，出墙也没问题。

**Comment by AnyWAT** [comment]
> 看不明白，我的一直都是这样，出墙也没问题。

是说现在使用陷阱也一直正常？截图证明是在陷阱 win1711.ipv6.microsoft.com. 里😥

**Comment by fhq8800** [comment]
![xxaxs505wcj85 px tlujp](https://user-images.githubusercontent.com/45731066/53695553-09f8e100-3df8-11e9-8003-ff5e1e60b92c.png)


> > 看不明白，我的一直都是这样，出墙也没问题。
> 
> 是说现在使用陷阱服务器也一直正常？截图证明是在陷阱 win1711.ipv6.microsoft.com. 里😥

![xxaxs505wcj85 px tlujp](https://user-images.githubusercontent.com/45731066/53695559-17ae6680-3df8-11e9-8461-eb07832cf7d8.png)

**Comment by AnyWAT** [comment]
文不对题，截图：cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by imelee** [comment]
同样出现浏览器代理设置，证书fail问题

**Comment by AnyWAT** [comment]
> 同样出现浏览器代理设置，证书fail问题

如果导入过证书、代理设置正确，首先解决GAE正常是重点：Teredo 隧道 #12455 或原生 #12477
正常后将并无证书、代理啥事😂
