### ISSUE TITLE
我不能离开Youtube

### ISSUE THREAD

**Issue by TonyCWong** [XX-net/XX-Net#12289]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by TonyCWong** [comment]
2019-02-27 22:14:18.611 - [DEBUG] network IPv6 is ok, cost:2002 ms

2019-02-27 22:14:22.507 - [WARNING] not enough ip

2019-02-27 22:14:27.129 - [WARNING] not enough ip

2019-02-27 22:14:32.508 - [WARNING] not enough ip

2019-02-27 22:14:37.131 - [WARNING] not enough ip

2019-02-27 22:14:42.509 - [WARNING] not enough ip

2019-02-27 22:14:47.131 - [WARNING] not enough ip

2019-02-27 22:14:52.510 - [WARNING] not enough ip

2019-02-27 22:14:56.808 - [DEBUG] create ssl timeout fail.

**Comment by TonyCWong** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by TonyCWong** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

我是原生IPV6

**Comment by AnyWAT** [comment]
#12043 原生远不如隧道 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671

**Comment by lianbookca** [comment]
@AnyWAT 为什么每次开机用XXE 隧道 都显示未知 要重新开一次那?

**Comment by AnyWAT** [comment]
不明确指的神马，贴图。。。
从不“要重新开一次那”
