### ISSUE TITLE
XTunnel多余流量谁有？

### ISSUE THREAD

**Issue by qibin8687** [XX-net/XX-Net#12282]
版里如果有人购买了XTunnel流量用不完的，赠送点给我：binarychee@gmail.com。谢谢。

**Comment by zhanglhz** [comment]
@qibin8687
 10G，请查收

**Comment by aserbao** [comment]
@zhanglhz zhuyongfu28@gmail.com 大佬😍😍😍😍😍

**Comment by qibin8687** [comment]
> 
> 
> @qibin8687
> 20G，请查收

收到了！实在感谢！论坛让我感受到了温暖！

**Comment by zhanglhz** [comment]
@aserbao 20G,请查收

**Comment by xihagithub** [comment]
@zhanglhz wt1768350715@163.com _大佬还有吗___

**Comment by wpf940997721** [comment]
@zhanglhz 感谢大佬  wpf940997721@gmail.com

**Comment by zhanglhz** [comment]
@xihagithub 你确认一下帐号，提示我这个帐号不存在。

**Comment by zhanglhz** [comment]
@wpf940997721 
先给你10G吧

**Comment by aserbao** [comment]
@zhanglhz 收到了，谢谢大佬。

**Comment by xihagithub** [comment]
@zhanglhz 没写错就是这个wt1768350715@163.com

**Comment by zhanglhz** [comment]
@xihagithub 

是X-Tunnel的帐号哦，我这里显示是没找到这个帐号

![image](https://user-images.githubusercontent.com/8307604/53464499-6de07a00-3a85-11e9-9fc1-25dc59de96aa.png)

**Comment by AnyWAT** [comment]
> @zhanglhz 没写错就是这个[wt1768350715@163.com](mailto:wt1768350715@163.com)

某些国内邮箱，或被XX-Net 不支持

**Comment by zhanglhz** [comment]
> > @zhanglhz 没写错就是这个[wt1768350715@163.com](mailto:wt1768350715@163.com)
> 
> 某些国内邮箱，或被XX-Net 不支持

应该是这个原因。

**Comment by wpf940997721** [comment]
> @wpf940997721
> 先给你10G吧
收到了，谢谢

**Comment by NanGangHuang** [comment]
h1570438765@gmail.com
求流量，谢谢大佬

**Comment by zhanglhz** [comment]
> [h1570438765@gmail.com](mailto:h1570438765@gmail.com)
> 求流量，谢谢大佬

10G，请查收

**Comment by NanGangHuang** [comment]
> > [h1570438765@gmail.com](mailto:h1570438765@gmail.com)
> > 求流量，谢谢大佬
> 
> 10G，请查收

已收到，膜拜中

**Comment by Illchange** [comment]
wsxm7911@yahoo.com
还有吗万分感谢

**Comment by Illchange** [comment]
> [wsxm7911@yahoo.com](mailto:wsxm7911@yahoo.com)
> 请问还有吗？万分感谢

**Comment by Illchange** [comment]
> > [h1570438765@gmail.com](mailto:h1570438765@gmail.com)
> > 求流量，谢谢大佬
> 
> 10G，请查收

请问大佬还有吗？万分感谢

**Comment by Jogiter** [comment]
jogiter.g@gmail.com     流量用不完的请也赠送点给我，万分感谢

**Comment by Ian-Luo** [comment]
马上没流量了，买了年套餐，还没到账。@zhanglhz 求点流量，感谢大佬! luoxw@hotmail.com
