### ISSUE TITLE
总ip数为0

### ISSUE THREAD

**Issue by xajhlhl** [XX-net/XX-Net#12286]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
#12043

**Comment by slulu164** [comment]
没有永远免费的ipv6稳定的服务器，所有的方法试过，稳定不了ip,用其他方式u2b 1080p无压力。

**Comment by AnyWAT** [comment]
#12043 能随时自动维持有效 IP数/总 IP数之比值=1，稳定不？
![image](https://user-images.githubusercontent.com/37962734/53491908-7ca14e00-3ad2-11e9-8f41-ed26f5f8f659.png)

**Comment by lianbookca** [comment]
> 
> 
> 没有永远免费的ipv6稳定的服务器，所有的方法试过，稳定不了ip,用其他方式u2b 1080p无压力。

其他事什么？
