### ISSUE TITLE
买了x-tunnel年费的2小时了还没到，xndroid还登录不上去

### ISSUE THREAD

**Issue by skywingXX** [XX-net/XX-Net#12281]
退款的心都有了

**Comment by AnyWAT** [comment]
大佬很忙，或许2天也到不了。留下账号来点？

**Comment by skywingXX** [comment]
> 大佬很忙，或许2天也到不了。留下账号先来点？

dalao  到账的话 xndroid能用吗

**Comment by AnyWAT** [comment]
能，流量不分系统。不是流量，还是你的 xndroid 不正常？

**Comment by skywingXX** [comment]
> 能，流量不分系统。不是流量，还是你的 xndroid 不正常？

刚下的xndroid1.1.6      xx-net显示3.7.16

**Comment by AnyWAT** [comment]
必须最新版1.3.0

**Comment by skywingXX** [comment]
> 必须最新版1.3.0

还别说pc端现在又登不上去

**Comment by skywingXX** [comment]
> 必须最新版1.3.0

非常不稳啊。

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

> 非常不稳啊。

必须关闭首页及与PC版相同位置的各1共2个自动扫描线程开关！

**Comment by skywingXX** [comment]
我pc可以连x-tunnel，但也不稳定；
gae的话基本就连不太上，都是没ip；
另外问一下xndroid怎么使用xtunnel，也要浏览器设置什么吗

**Comment by AnyWAT** [comment]
> 我pc可以连x-tunnel，但也不稳定；
> gae的话基本就连不太上，都是没ip；

贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

> 另外问一下xndroid怎么使用xtunnel，也要浏览器设置什么吗

https://github.com/XndroidDev/Xndroid

**Comment by skywingXX** [comment]
> 因为 GAE 不正常：GAE正常，x-tunnel 才正常 #11892 X-Tunnel 正常的前提：。。。
> 😥第二次：贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息
> 参考：#12043

都是没ip，另外现在tunnel没流量，不想搞了

**Comment by skywingXX** [comment]
大佬ip不够不怎么办，我从几个帖子复制了上百个ip，贴进去可用ip就一直掉。

**Comment by skywingXX** [comment]
XX-Net Status:

sys-platform: armv8l, Linux-4.4.78-perf-g92b7329-armv8l-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Tue Sep 25 23:43:55 CST 2018
os-release: 4.4.78-perf-g92b7329
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.0.0; MI 6 Build/OPR1-wesley_iui-18.10.09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.2
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

好不稳定。

**Comment by AnyWAT** [comment]
> > 另外问一下xndroid怎么使用xtunnel，也要浏览器设置什么吗
> 
> https://github.com/XndroidDev/Xndroid

第二次，没有第三次。

**Comment by skywingXX** [comment]
> > Android 8.0.0
> > 好不稳定。
> 
> > > 另外问一下xndroid怎么使用xtunnel，也要浏览器设置什么吗
> > 
> > 
> > https://github.com/XndroidDev/Xndroid
> 
> 第二次，没有第三次。

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by skywingXX** [comment]
说的简单点，就是更换teredo服务器，经过我几天的测试
**netsh int ipv6 set teredo enterpriseclient 195.140.195.140 netsh int ipv6 set teredo enterpriseclient 83.170.6.76 netsh int ipv6 set teredo enterpriseclient 157.56.106.184 netsh int ipv6 set teredo enterpriseclient 157.56.106.189**

用这几个服务器轮流切换一下，就能保证IP稳定超过50（免费用户）
其中最稳定的是 **83.170.6.76**

**Comment by AnyWAT** [comment]
> 类型 : enterpriseclient

貌似 win10 用 natawareclient 好过 enterpriseclient

> 服务器名称 : win10.ipv6.microsoft.com. 

完全可以试试用 IP取代域名，或更换其它服务器

> gws-ip-num: total:100 ipv4:0 ipv6:1
> worker: h1:0 h2:1
> ip-quality: 9999

较佳的结果是：
gws-ip-num: total:100 ipv4:0 ipv6:100
worker: h1:0 h2: 几十
ip-quality: 300左右

一切尽在：
> 参考：#12043

更换服务器、关闭某开关、网络属性内取消勾选 IPv6协议。。。

**Comment by skywingXX** [comment]
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> 状态 : qualified
> ipv6-status: OK

但依旧：
> gws-ip-num: total:100 ipv4:0 ipv6:0
> worker: h1:0 h2:0

且关闭某开关、网络属性内取消勾选 IPv6协议的状况没有说明。以下摘自 #12043
隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 并能扫描出 IP才是真正的好。
【 _从零开始，验证隧道服务器及你的设置。。。_ 】
隧道窗口内隧道已连接；退出软件，删除 good_ip.txt，启动软件。如果：
1、能扫描出 IP，说明该隧道服务器可用；
2、能随时自动维持有效 IP数/总 IP数之比值=1，说明设置较合适，应该 IP延迟会较小，连接池会较大。

**Comment by skywingXX** [comment]
感觉付费还这么多事搞。。还搞不定

自动调整扫描线程数OFF
最大扫描线程数 50
IP 模式 仅ipv6
网络取消勾选Microsoft网络设配器多路传输协议
勾选Internet协议版本6（TCP/IPv6）
删除good_ip.txt后重启
Teredo 参数
---------------------------------------------
类型                    : natawareclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

还会出现："仅 IPv6" 不可用，请检查。

**Comment by AnyWAT** [comment]
> gws-ip-num: total:4 ipv4:0 ipv6:0

不知运行了多久才 4个 https://github.com/XX-net/XX-Net/issues/12093#issuecomment-459199446 到今日，原生ipv6依旧异常，隧道更换过一次，有效的隧道会在半分钟左右把ip扫满，延迟也很低。

> scan-ip-thread-num: 50

摘自 #12043 适当增加[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)（网络好/差时可适当调小/大，自己调试；

**Comment by skywingXX** [comment]
> > gws-ip-num: total:4 ipv4:0 ipv6:0
> 
> 不知运行了多久才 4个 [#12093 (comment)](https://github.com/XX-net/XX-Net/issues/12093#issuecomment-459199446) 到今日，原生ipv6依旧异常，隧道更换过一次，有效的隧道会在半分钟左右把ip扫满，延迟也很低。
> 
> > scan-ip-thread-num: 50
> 
> 摘自 #12043 适当增加[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)（网络好/差时可适当调小/大，自己调试；。。。

按照#12062也没用  扫了都半个钟了

**Comment by AnyWAT** [comment]
> 按照 #12062 也没用 扫了都半个钟了

服务器不合适。。。

**Comment by skywingXX** [comment]
> > gws-ip-num: total:4 ipv4:0 ipv6:0
> 
> 不知运行了多久才 4个 [#12093 (comment)](https://github.com/XX-net/XX-Net/issues/12093#issuecomment-459199446) 到今日，原生ipv6依旧异常，隧道更换过一次，有效的隧道会在半分钟左右把ip扫满，延迟也很低。
> 
> > scan-ip-thread-num: 50
> 
> 摘自 #12043 适当增加[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)（网络好/差时可适当调小/大，自己调试；。。。

有个p用。主要还是要有效的隧道ip。换了个ip后：

有效 IPv6 IP 数 | 10
-- | --
总 IP 数 | 70
我觉得官方或者作者应该是要提供有效ip给付费用户的啊，而不是要自己去找

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/53414745-5d3eee00-3a0a-11e9-8cc4-77ad07964adb.png)

**Comment by marswow** [comment]
哇塞还有这么多人用xxnet........现在都是用shadowsocks、v2ray的，都是自己架设服务器，随便买个小鸡就是500G~1个T每个月的流量

**Comment by skywingXX** [comment]
> 哇塞还有这么多人用xxnet........现在都是用shadowsocks、v2ray的，都是自己架设服务器，随便买个小鸡就是500G~1个T每个月的流量

自己买服务器架不是要一年600+吗

**Comment by marswow** [comment]
@skywingXX 不用这么贵啊，找个便宜月付鸡或搬瓦工活动  价格撑死了不会到300块钱软妹币1年

**Comment by skywingXX** [comment]
> @skywingXX 不用这么贵啊，找个便宜月付鸡或搬瓦工活动 价格撑死了不会到300块钱软妹币1年

原本免费某灯偶尔能上，付费200多一年不知道稳不稳，贪便宜搞了这个还要自己搞这搞那。不过现在pc今天算是比较稳了 手机就不稳

**Comment by marswow** [comment]
@skywingXX 蓝灯被识别了，还是自己搞个小鸡玩吧

**Comment by lovethink2** [comment]
我也是付了年费，太不稳定了，一会能访问google一会不能访问、太不值了。 真想退了。

**Comment by skywingXX** [comment]
> 我也是付了年费，太不稳定了，一会能访问google一会不能访问、太不值了。 真想退了。

我已经自己搞了gcp  真香，速度直接宽带满值
