### ISSUE TITLE
AnyWAT老哥，进来下。

### ISSUE THREAD

**Issue by xiaozixun** [XX-net/XX-Net#12294]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 2
总 IP 数 | 35
XX-Net 状态 | 工作
IP 延迟 | 780
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 150

这是我现在的状态（2019年3月1日20:27:10），在几分钟之前ip还是1:1。

**Comment by AnyWAT** [comment]
台机，有线无线？
有没有相关锅：[收集反馈] QQprotect.exe 等国产软件貌似会影响XX-Net的运行 #10957

**Comment by xiaozixun** [comment]
> 台机，有线无线？
> 有没有相关锅：[收集反馈] QQprotect.exe 等国产软件貌似会影响XX-Net的运行 #10957

国产软件也全是关闭，只有一个chrome开着。
是连路由器的笔记本

**Comment by AnyWAT** [comment]
> 国产软件也全是关闭

某些软件仅关闭貌似没用，因其有服务开启。。。

> 是连路由器的笔记本

从前一贴的图看，是无线？

**Comment by xiaozixun** [comment]
> > 国产软件也全是关闭
> 
> 某些软件仅关闭貌似没用，因其有服务开启。。。
> 
> > 是连路由器的笔记本
> 
> 从前一贴的图看，是无线？
看了下进程和服务，应该是没有。
是无线网络

**Comment by AnyWAT** [comment]
试试 #12043 辅以。。。

**Comment by xiaozixun** [comment]
> > 看了下进程和服务，应该是没有。
> 
> 肉眼有限，绿色、免费 Autoruns 助你（取消疑似项前的勾选，再重启机器） https://filehippo.com/zh/search?q=Autoruns
> 
> ![image](https://user-images.githubusercontent.com/37962734/53638928-c9b42a00-3c62-11e9-873a-81ec71619401.png)
> 
> 试试 #12043 辅以。。。

查了一遍没问题，xx-net还是那个样子。

**Comment by AnyWAT** [comment]
> 查了一遍没问题，xx-net还是那个样子。

如是，更换服务器？

**Comment by xiaozixun** [comment]
> （貌似没辅以。。。）如是，更换服务器？

没得用，算了开ssr了。
谢谢了

**Comment by AnyWAT** [comment]
不会像手机一样，不在主窗口的应用被系统一定程度的限制。。。

**Comment by xiaozixun** [comment]
> 不会像手机一样，不在主窗口的应用被系统（或某软件）一定程度的限制。。。

应该没有吧，我印象中没出现过这种情况。

**Comment by hpain** [comment]
别看这个了，已死，也许作者认为不赚钱所以不干了，不过这可以理解

**Comment by AnyWAT** [comment]
除了可用的隧道服务器有所减少，用隧道的XX-Net 好着呢！https://github.com/XX-net/XX-Net/issues/12043

**Comment by xiaozixun** [comment]
> 别看这个了，已死，也许作者认为不赚钱所以不干了，不过这可以理解

讲道理，别人更新又不是什么法律规定的义务。何况作者也不靠这赚钱吧。

**Comment by pinoren** [comment]
楼主召唤机器人聊天干啥呢。。。
