### ISSUE TITLE
尴尬  我们的系统检测到您的计算机网络中存在异常流量

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#12293]
关于此网页

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的

![qq 20190228160823](https://user-images.githubusercontent.com/32628414/53550978-07398a00-3b73-11e9-94d6-cf491c776cb7.png)
![qq 20190228160835](https://user-images.githubusercontent.com/32628414/53550980-07d22080-3b73-11e9-89d3-53dea3db96a0.png)

**Comment by RollingIsland** [comment]
同问
