### ISSUE TITLE
今天突然正常了，IP不会狂掉了

### ISSUE THREAD

**Issue by huajian150** [XX-net/XX-Net#12297]
之前一直都是IP狂掉，把ANYWAT说的服务器换了遍，一直没什么用。

今天突然好了

![image](https://user-images.githubusercontent.com/20216637/53676686-e8f19c80-3ce0-11e9-9e6d-35af3566d215.png)

这是我的设置，留给没好的同学参考一下

![image](https://user-images.githubusercontent.com/20216637/53676689-f27b0480-3ce0-11e9-8070-bd59e035233e.png)

**Comment by robinlighting** [comment]
不知道为啥，上午正常，中午就这样。

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 2
总 IP 数 | 16
XX-Net 状态 | 工作
IP 延迟 | 758
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 200

**Comment by huajian150** [comment]
> 不知道为啥，上午正常，中午就这样。
> 
> ## Teredo 参数
> 类型 : enterpriseclient
> 服务器名称 : 83.170.6.76
> 客户端刷新间隔 : 30 秒
> 客户端端口 : unspecified
> 状态 : qualified
> 客户端类型 : teredo client
> 网络 : managed
> NAT : restricted
> NAT 特殊行为 : UPNP: 是，PortPreserving: 否
> 
> 属性	值
> IPv4 状态	OK
> IPv6 状态(如何开启)	OK
> 有效 IPv4 IP 数	0
> 有效 IPv6 IP 数	2
> 总 IP 数	16
> XX-Net 状态	工作
> IP 延迟	758
> 连接池(帮助)	新:0 h1:0 h2:0
> 浏览器代理设置	OK
> CA 证书状态(下载)	OK
> IP 扫描线程数(设置)	200

**Comment by AnyWAT** [comment]
IP会狂掉，貌似锅在：没关闭某开关、最大扫描线程数过小。。。
奇怪：楼主的
IPv4 状态 fail
IPv6 状态 ok

> 不知道为啥，上午正常，中午就这样。

如果较长时间没使用代理，或许管理员CMD运行以下2行后有救？
netsh int ipv6 set teredo disabled
netsh int ipv6 set teredo enterpriseclient

**Comment by huajian150** [comment]
> IP会狂掉，貌似锅在：没关闭某开关、最大扫描线程数过小。。。
> 奇怪：楼主的
> IPv4 状态 fail
> IPv6 状态 ok
> 
> > 不知道为啥，上午正常，中午就这样。
> 
> 如果较长时间没使用代理：连接池已归零，或许管理员CMD运行以下2行后有救？
> netsh int ipv6 set teredo disabled
> netsh int ipv6 set teredo enterpriseclient

我关闭自动扫描了，最大扫描也改过200，不能用的时候，依然不能用


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:47
ipv4-status: Fail
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:49
scan-ip-thread-num: 5
ip-quality: 371
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> 我关闭自动扫描了，

没看出来，除非 scan-ip-thread-num: 0，禁用隧道使用原生，导入大佬提供的。。。https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671 
![image](https://user-images.githubusercontent.com/37962734/53677896-535f0880-3cf2-11e9-8381-44f6381fff8f.png)

> ipv4-status: Fail
> ipv6-status: OK

如何做到的？难道是又一校园网：默认原生 ipv6通，ipv4 需在原生 ipv6通的情况下通过验证才通？https://github.com/XX-net/XX-Net/issues/12275#issuecomment-467035966

> scan-ip-thread-num: 5

过小

**Comment by AnyWAT** [comment]
如已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。
如用原生需禁用隧道，管理员CMD
netsh int ipv6 set teredo disabled

**Comment by robinlighting** [comment]
@AnyWAT

现在又正常了，虽然我用了你给的方法，也用了那个DNS软件，开始不懂怎么用那个DNS软件，我也是找了一大波网页，才知道怎么用那个DNS软件。

现在那些你说的黑名单软件我也全部关闭，而且有关的服务也关闭了。

但是有时候也不能用，在我不能用的时候我就重启路由器，还有猫也重启。

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 157.56.106.184
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 236
连接池(帮助) | 新:0 h1:0 h2:22
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 200

**Comment by AnyWAT** [comment]
> 也用了那个DNS软件，开始不懂怎么用那个DNS软件，我也是找了一大波网页，才知道怎么用那个DNS软件。

点开图中链接，就基本能用了
![image](https://user-images.githubusercontent.com/37962734/53678130-a25a6d00-3cf5-11e9-8c41-ac478d2dec09.png)

😱才发现，在与BLOCK者。。。

**Comment by AnyWAT** [comment]
> 我关闭自动扫描了，最大扫描也改过200，不能用的时候，依然不能用

不能用的时候再发帖。。。

**Comment by robinlighting** [comment]
哈哈哈哈哈，以前有误会吧！
你让我想起《我，机器人》这部电影里的二代机器人。

**Comment by AnyWAT** [comment]
楼主用的啥，竟然能
本地映射与外部 NAT 映射的端口一致？

**Comment by huajian150** [comment]
> 楼主用的啥，竟然能
> 本地映射与外部 NAT 映射的端口一致？

江苏电信，有公网地址，用的 Win10 
难道不应该一致吗？不都是这样吗
还有我的 IPV4 为啥 Fail ？

**Comment by AnyWAT** [comment]
> 江苏电信，有公网地址

有公网（IPv6）地址？资源 IPv4有限 IPv6无限，或许正是

> 还有我的 IPV4 为啥 Fail ？

的原因？

> 难道不应该一致吗？不都是这样吗

虽不是第一次见两端口一致，但见得多的一般是不同
