### ISSUE TITLE
兄弟们啊，你们的XX还有资源不？我的几个月了一个IP资源都没。。。

### ISSUE THREAD

**Issue by dylanleesky** [XX-net/XX-Net#12296]
最新版本，老旧的几个版本，都试了。IPV6测试都是ok。
但xx就是获取不到资源。。。。
![image](https://user-images.githubusercontent.com/14555503/53643819-ffabdb00-3c6f-11e9-9909-4d13fb8c81f5.png)
这到底啥情况、、、

我这是联通宽带。。。

**Comment by AnyWAT** [comment]
> 最新版本，老旧的几个版本，都试了。IPV6测试都是ok。

老旧貌似已死，IPV6测试纯属多余。关闭某开关、禁用原生而用隧道的 3.13.1 一直很正常 #12043 
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by robinlighting** [comment]
@AnyWAT兄，帮我看看。

电信外网

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 157.56.106.184
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

我现在还是上不了。

**Comment by robinlighting** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 0
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 200

**Comment by robinlighting** [comment]
搞不懂，重启了路由，又可以了。

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 13
总 IP 数 | 60
XX-Net 状态 | 工作
IP 延迟 | 1568
连接池(帮助) | 新:0 h1:0 h2:13
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 200

**Comment by lianbookca** [comment]
> 某开关

某开关 是什么东西？

**Comment by dylanleesky** [comment]
> > 最新版本，老旧的几个版本，都试了。IPV6测试都是ok。
> 
> 老旧的版本貌似已死透，IPV6测试纯属多余。关闭某开关、禁用原生而用隧道的 3.13.1 一直很正常 #12043
> 
> ![image](https://user-images.githubusercontent.com/37962734/53646505-51576400-3c76-11e9-88bc-d9adf64dee86.png)

看样子非得换隧道了。年前开着原生v6上谷歌不用代理都能访问，现在。。。只能通过其他工具了。。。

**Comment by AnyWAT** [comment]
> 看样子非得换隧道了。年前开着原生v6上谷歌不用代理都能访问，现在。。。

原生昙花一现，隧道优于原生。。。https://github.com/XX-net/XX-Net/issues/12043#issuecomment-465050996 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671

**Comment by AnyWAT** [comment]
> 某开关 是什么东西？

#12043 温故而知新

**Comment by AnyWAT** [comment]
> IP 扫描线程数(设置) | 200

或许200（动静）过大，被。。。
> 搞不懂，重启了路由，又可以了。

#12043 隧道显示正常但连接池或有效 IP数归零时：或更换隧道服务器，或先禁用再启用隧道，或先禁用再启用（电脑）网络，或免退出再次启动软件

**Comment by AnyWAT** [comment]
Teredo隧道：#12455 或
原生：#12477
