### ISSUE TITLE
一个多月了，一个commit都没有，作者还活着么

### ISSUE THREAD

**Issue by HustCoderHu** [XX-net/XX-Net#12292]

**Comment by AnyWAT** [comment]
#12043 除了可用隧道有减少，用隧道的XX-Net 好着呢。。。

**Comment by hubsocks** [comment]
稳的狠.63个ipv4
![3333333](https://user-images.githubusercontent.com/46856823/53561348-9a7dba00-3b89-11e9-9c89-8e870bca681b.jpg)
长时间使用不降速,python不会出错关闭.

**Comment by nly4lov** [comment]
有人说作者被抓进去了

**Comment by ksit1110** [comment]
> 稳的狠.63个ipv4
> ![3333333](https://user-images.githubusercontent.com/46856823/53561348-9a7dba00-3b89-11e9-9c89-8e870bca681b.jpg)
> 长时间使用不降速,python不会出错关闭.

很厉害，我每天都换隧道，能扫到很多ip，但是只要开外网，ip很快就消失，真心不知道你和anywat是怎么做到稳定隧道的，因为隧道就那么几个~~~~

**Comment by hubsocks** [comment]
@ksit1110 没用ipv6,纯ipv4的.隧道获取的ipv6,用tcping64全测,丢包严重,无论换那个隧道都一样.dropped Frames率很大.隧道获取的ip数量要多些.原生的只能获取到两个可用ip.但隧道ipv6丢帧率大于原生ipv6.

**Comment by ksit1110** [comment]
> @ksit1110 没用ipv6,纯ipv4的.隧道获取的ipv6,用tcping64全测,丢包严重,无论换那个隧道都一样.dropped Frames率很大.隧道获取的ip数量要多些.原生的只能获取到两个可用ip.但隧道ipv6丢帧率大于原生ipv6.

好尴尬，因为我ipv4一个也扫不到

**Comment by ksit1110** [comment]
> @ksit1110 没用ipv6,纯ipv4的.隧道获取的ipv6,用tcping64全测,丢包严重,无论换那个隧道都一样.dropped Frames率很大.隧道获取的ip数量要多些.原生的只能获取到两个可用ip.但隧道ipv6丢帧率大于原生ipv6.

能不能分享下方法，现在用的实在是太痛苦

**Comment by linxin6560** [comment]
你牛逼你去写啊

**Comment by AnyWAT** [comment]
> 很厉害，我每天都换隧道，能扫到很多ip，但是只要开外网，ip很快就消失，真心不知道你和anywat是怎么做到稳定隧道的，因为隧道就那么几个~~~~

#12043 禁用原生（协议）而用隧道、关闭某开关。。。都做到了？
![image](https://user-images.githubusercontent.com/37962734/53622504-f5b8b680-3c34-11e9-9d6f-32b905e810c9.png)

贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by xiaozixun** [comment]
其实我也很好奇anywat是怎么做到的。我有两台电脑，一台台式连网线、移动，一直不用管就能用。另一台笔记本连路由器、电信，不管怎么照着 12043做都是随缘状态（有时能用，有时不能用）。
至于hubsocks说的，我差不多有一年左右没有扫到ipv4了。

**Comment by AnyWAT** [comment]
> 另一台笔记本连路由器、电信，不管怎么照着 12043做都是随缘状态（有时能用，有时不能用）。

贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by xiaozixun** [comment]
> > 另一台笔记本连路由器，电信，不管怎么照着12043做都是随缘状态（有时能用，有时不能用）。
> 
> 贴cmd内运行netsh int ipv6 show teredo的结果（无需IP地址的2行）及XX-Net诊断信息

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
os-release: 7 或因缺少某系统（本身）服务劣于Win10？
scan-ip-thread-num: 10 ——明显不符合 #12043 。。。
没显示的关闭某开关、禁用原生（协议）就更无法。。。
> 不管怎么照着12043做

😝不成立！

**Comment by cross063x** [comment]
> 网络 : managed
NAT : restricted
---------------------------------------------
目测你有安装其他VPN软件，导致的问题
试了下你用的隧道服务器，可以正常使用
![1](https://user-images.githubusercontent.com/48123985/53637245-9ae78500-3c5d-11e9-87c4-81c34a3eb435.jpg)
![2](https://user-images.githubusercontent.com/48123985/53637246-9b801b80-3c5d-11e9-8e25-9a442be1f6fa.jpg)

**Comment by xiaozixun** [comment]
> os-release: 7 或因缺少某系统（本身）服务劣于Win10？
> scan-ip-thread-num: 10 ——明显不符合 #12043 。。。
> 没显示的关闭某开关、禁用原生（协议）就更无法。。。
> 
> > 照着12043做
> 
> 属吹水，不成立！

scan-ip-thread-num: 10         这个是因为当时我设置为此时，得到ip就是“有效 IP数/总 IP数之比值=1”
![default](https://user-images.githubusercontent.com/22409452/53637162-6a075000-3c5d-11e9-9681-0bcb1ce9268b.png)

![01](https://user-images.githubusercontent.com/22409452/53637229-9327e080-3c5d-11e9-9f77-a644ae51f966.png)
至于系统问题，那就真没办法，我总不能因为这个换了系统。

**Comment by xiaozixun** [comment]
> > 网络 : managed
> > NAT : restricted
> 
> 目测你有安装其他VPN软件，导致的问题
> 试了下你用的隧道服务器，可以正常使用
> ![1](https://user-images.githubusercontent.com/48123985/53637245-9ae78500-3c5d-11e9-87c4-81c34a3eb435.jpg)
> ![2](https://user-images.githubusercontent.com/48123985/53637246-9b801b80-3c5d-11e9-8e25-9a442be1f6fa.jpg)

XX-net和ssr冲突吗

**Comment by AnyWAT** [comment]
> scan-ip-thread-num: 10 这个是因为当时我设置为此时，得到ip就是“有效 IP数/总 IP数之比值=1”

#12043 适当增加[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)（网络好/差时可适当调小/大，自己调试；

> gws-ip-num: total:undefined ipv4:0 ipv6:44

？“有效 IP数/总 IP数之比值=1”

> XX-net和ssr冲突吗

默认时貌似与X-Tunel 有端口1080冲突

**Comment by AnyWAT** [comment]
> gws-ip-num: total:undefined ipv4:0 ipv6:44
> ipv4-status: OK
> ipv6-status: OK
> connected-link: new:0 used:undefined
> worker: h1:0 h2:18
> scan-ip-thread-num: 10
> ip-quality: 793

锅在 scan-ip-thread-num: 10 太小！

**Comment by xiaozixun** [comment]
> > scan-ip-thread-num: 10 这个是因为当时我设置为此时，得到ip就是“有效 IP数/总 IP数之比值=1”
> 
> #12043 适当增加[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)（网络好/差时可适当调小/大，自己调试；
> 
> > gws-ip-num: total:undefined ipv4:0 ipv6:44
> 
> ？“有效 IP数/总 IP数之比值=1”
> 
> > XX-net和ssr冲突吗
> 
> 默认时貌似与X-Tunel 有端口1080冲突

X-Tunel 这个模块我以及关闭了，只剩GAEPROXY模块了。

**Comment by AnyWAT** [comment]
> X-Tunel 这个模块我以及关闭了，只剩GAEPROXY模块了。

那就貌似没问题

**Comment by xiaozixun** [comment]
> > X-Tunel 这个模块我以及关闭了，只剩GAEPROXY模块了。
> 
> 那就貌似没问题


属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 3
总 IP 数 | 3
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:1
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 150

又炸了

**Comment by AnyWAT** [comment]
> 又炸了

此时应立马观察隧道的状态。。。

**Comment by xiaozixun** [comment]
> > 又炸了
> 
> 此时应立马观察隧道的状态。。。

去这里吧，隧道没问题
https://github.com/XX-net/XX-Net/issues/12294
