### ISSUE TITLE
最近mac miredo ipv6 经常断，你们有没有遇到过

### ISSUE THREAD

**Issue by hunshenshi** [XX-net/XX-Net#12298]
最近mac miredo ipv6 经常断，分配不到ipv6的地址，需要重启下无线开关 或者重启下miredo，更或者要重启下xx-net，

有类似情况不

**Comment by hunshenshi** [comment]
版本13.1

**Comment by AnyWAT** [comment]
没关闭”自动调整扫描线程数“开关？能随时自动维持[有效 IP数/总 IP数之比值=1]( )，说明设置较合适，应该 IP延迟会较小，连接池会较大。——另类系统的 #12043

**Comment by hunshenshi** [comment]
@AnyWAT  没有关闭，ipv6的状态是fail，miredo的灯为黄灯

**Comment by AnyWAT** [comment]
关闭它！控制页内先禁用再启用，或更换服务器。
