### ISSUE TITLE
XX-net是凉了吗？

### ISSUE THREAD

**Issue by ghost111999** [XX-net/XX-Net#12301]
我都好几个月没办法正常连接了，后来被迫只好找替代的梯子，用AWS免费的EC2自己搭了个SSR服务器，每个月只有15G流量，根本不敢放开了看视频。今天再次尝试XX-net，仍然不能连接IPv6，悲哉！

**Comment by FergonXie** [comment]
没凉呀，我的很正常。 
找个支持IPsec的路由器试试看，我之前70块钱买的路由器就支持（没想到...), 放在杂物堆好几年了。 华为游戏版的就不支持IPsec， 也坑了我好长一段时间。

**Comment by AnyWAT** [comment]
> 好几个月没办法正常连接了

贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by shpherd** [comment]
莫名其妙晚上正常

**Comment by MasterOogwayis** [comment]
和你的运营商有关系，我在公司全天满ip 100个，稳定不掉线。
回家只有几个ip还一直掉，或者根本连不上

**Comment by AnyWAT** [comment]
公司、家庭不同网络，或许更换服务器。。。

**Comment by phoenixzzan** [comment]
win10, MAC 10.14.3 都正常，这几天就是折腾了MAC一下也能稳上了。
先捋自己的问题，不能上难道大伙不会说吗

**Comment by dylanleesky** [comment]
> 我都好几个月没办法正常连接了，后来被迫只好找替代的梯子，用AWS免费的EC2自己搭了个SSR服务器，每个月只有15G流量，根本不敢放开了看视频。今天再次尝试XX-net，仍然不能连接IPv6，悲哉！

兄弟，给个教程呗。15G也够我用了。

**Comment by klcb2010** [comment]
> 我都好几个月没办法正常连接了，后来被迫只好找替代的梯子，用AWS免费的EC2自己搭了个SSR服务器，每个月只有15G流量，根本不敢放开了看视频。今天再次尝试XX-net，仍然不能连接IPv6，悲哉！

你用的 https://aws.amazon.com/cn/ec2/pricing/吗？  我的xxnet也没法使用了，以前隧道是已启用，没有正常使用过一次

**Comment by yintianyu** [comment]
我这里用着一直没有问题，速度很快

**Comment by cym104** [comment]
真的不如去用freegate了。流畅youtube

**Comment by ghost111999** [comment]
> > 好几个月没办法正常连接了
> 
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息
有效IP一直是0

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by ghost111999** [comment]
> > 我都好几个月没办法正常连接了，后来被迫只好找替代的梯子，用AWS免费的EC2自己搭了个SSR服务器，每个月只有15G流量，根本不敢放开了看视频。今天再次尝试XX-net，仍然不能连接IPv6，悲哉！
> 
> 兄弟，给个教程呗。15G也够我用了。

教程网上一搜一大堆，不过我部署服务器的时候也费了不少劲，按教程说的部署不成功，后来是用别人的脚本才部署成功了。

**Comment by ghost111999** [comment]
> > 我都好几个月没办法正常连接了，后来被迫只好找替代的梯子，用AWS免费的EC2自己搭了个SSR服务器，每个月只有15G流量，根本不敢放开了看视频。今天再次尝试XX-net，仍然不能连接IPv6，悲哉！
> 
> 你用的 [https://aws.amazon.com/cn/ec2/pricing/吗？](https://aws.amazon.com/cn/ec2/pricing/%E5%90%97%EF%BC%9F) 我的xxnet也没法使用了，以前隧道是已启用，没有正常使用过一次

是的，我用的是amazon的EC2免费服务，一年免费期过后再说吧

**Comment by AnyWAT** [comment]
@ghost111999 
> 及XX-Net 诊断信息

http://127.0.0.1:8085/?module=gae_proxy&menu=status 页底”诊断信息“
