### ISSUE TITLE
111111111111111111111

### ISSUE THREAD

**Issue by lianbookca** [XX-net/XX-Net#12302]
1111111111111111

**Comment by slulu164** [comment]
和你一样，感觉服务器 受到严重干扰。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12296#issuecomment-468935720 能有如此说法，
> 换了帖子里面 服务器 还是扫不到IP

也就不奇怪了😥

**Comment by lianbookca** [comment]
> 
> 
> [#12296 (comment)](https://github.com/XX-net/XX-Net/issues/12296#issuecomment-468935720) 能有如此说法，
> 
> > 换了帖子里面 服务器 还是扫不到IP
> 
> 也就不奇怪了😥继续 #12043 温故而知新

你这里面服务器 都不好使 在怎么看 也不好使啊？

**Comment by lianbookca** [comment]
> 
> 
> [#12296 (comment)](https://github.com/XX-net/XX-Net/issues/12296#issuecomment-468935720) 能有如此说法，
> 
> > 换了帖子里面 服务器 还是扫不到IP
> 
> 也就不奇怪了😥继续 #12043 温故而知新

你这里面服务器 都不好使 在怎么看 也不好使啊？

**Comment by lianbookca** [comment]
> 
> 
> 和你一样，感觉服务器 受到严重干扰。

那你怎么解决的？

**Comment by AnyWAT** [comment]
> 你这里面服务器 都不好使 在怎么看 也不好使啊？

关闭某开关 #12043 说得很清楚。（鄙人）所知全部服务器如没有1个合适，也就只好与隧道说byeBye了？

**Comment by AnyWAT** [comment]
> 和你一样，感觉服务器 受到严重干扰。

除了：貌似可用服务器减少，网络恶化？
隧道3.13.1版本一直正常。

**Comment by ksit1110** [comment]
已经试过了，如果你有公网IPV4地址，可以妥妥的用，但是如果你没有，类似中国移动根本拿不到公网地址的就真的算了吧，折腾不来。

**Comment by AnyWAT** [comment]
> 如果你有公网IPV4地址

移动网哪来的。。。一直正常ing

**Comment by AnyWAT** [comment]
Teredo 隧道：#12455 或
原生：#12477
