### ISSUE TITLE
AnyWAT我拜托你不要在这里BB了......

### ISSUE THREAD

**Issue by NGSW-R** [XX-net/XX-Net#12300]
别人不是傻子，要是按照你的方法有用早就解决了。
你那些不过是雕虫小技，墙真的要封XX-Net不过是手到擒来。

**Comment by CompleX0321** [comment]
本来就是为了自由开放，生气可以，但没必要，与其争论，给出帮助更善，尝试过后，好歹自知

**Comment by SeaHOH** [comment]
想象下：一个熊孩子闯进你刚整理完毕的房间。。。

**Comment by Peterpey** [comment]
@SeaHOH  你终于出现了 求更新啊啊啊啊啊啊啊

**Comment by slulu164** [comment]
@SeaHOH 跟这海少的节奏没错，辛苦了海少。
谢谢所有的参与者，谢谢！用的好不好，如引水，冷暖自知。给出的方法付出了劳动，应该给予尊重和感谢。谢谢热心解答的朋友，赞。

**Comment by MadMaxPayne8964** [comment]
> @SeaHOH 你终于出现了 求更新啊啊啊啊啊啊啊

原生IPv6被路由黑洞，teredo隧道被干扰，这非更新能解决的。如果有公网IPv4，可以试试6 to 4

**Comment by ksit1110** [comment]
试试自己搭建吧  没必要生气

**Comment by CompleX0321** [comment]
> 
> 
> 想象下：一个熊孩子闯进你刚整理完毕的房间。。。

求教整理房间

**Comment by SeaHOH** [comment]
说下不更新 gae_proxy 模块的原因：
1. 现在 GAE 服务器与普通服务器隔离，数量很少，因此容易屏蔽 IP。
1. 其它没屏蔽的普通服务器 IP 虽然可以直连，但是因为 XX-Net 的基础构架限制，不方便加入。

第一点没法解决，只能找漏；
第二点需要改很多，但我不会去做了（原因如下），有只需要使用谷歌的可以使用我写的另一个工具。

真的，人多了，什么样的都能碰到，我又没有足够的权限处理，所以不会在这里耗费更多。

**Comment by hubsocks** [comment]
@SeaHOH 纯ipv4的速度还能提高吗?现在优土泊老是在8000到13000之间,就上不去了.
连接接收缓冲大小 已经设为2048了.如果改更大,会好些吗?
![2222](https://user-images.githubusercontent.com/46856823/53690753-7699be80-3dab-11e9-9e04-8c9cc37749f7.jpg)

如果下次更新的话.把那个级别设置完全去掉了吧.

**Comment by ChenyangS** [comment]
完全自由的互联网时代结束了，免费的蛋糕没有了。

**Comment by SeaHOH** [comment]
> 纯ipv4的速度还能提高吗?现在优土泊老是在8000到13000之间,就上不去了.
> 连接接收缓冲大小 已经设为2048了.如果改更大,会好些吗?

还受到线路质量影响，不要再增大，没用。

> 如果下次更新的话.把那个级别设置完全去掉了吧.

为什么呢？如果是嫌设置麻烦，freegate 之类就特别简单，点开就能用。

**Comment by Peterpey** [comment]
@SeaHOH  "有只需要使用谷歌的可以使用我写的另一个工具" 
另一个工具是指哪个？ Github 有下载吗?

**Comment by wuyongwen** [comment]
是的，他没有进来这。。

**Comment by diyici18sui** [comment]
@Peterpey GotoX

**Comment by fhq8800** [comment]
他的方法挺管用的，我顶一下anywat

**Comment by cypcym** [comment]
> 他的方法挺管用的，我顶一下anywat

能不能麻烦您，说说到底是什么方法，怎么操作？
说实在的，他的帖子我看过好几次，但实在是没看懂

**Comment by AnyWAT** [comment]
> 他的方法挺管用的，我顶一下anywat

高高高手：https://github.com/XX-net/XX-Net/issues/12326#issuecomment-470378689
