### ISSUE TITLE
设置路由器IPsec穿透

### ISSUE THREAD

**Issue by 2579019321** [XX-net/XX-Net#12310]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by 2579019321** [comment]
RT-AC68U

**Comment by 2579019321** [comment]
路由器如何开启 ipsec穿透

**Comment by FergonXie** [comment]
不用去管它的，支持ipsec穿透，说明就支持ipv6了，应该就能正常了，作者就说明了失败 就是国内路由器大多不支持IPV6的原因 。 
你现在能正常翻墙了吗？

**Comment by AnyWAT** [comment]
移动网、撤下光猫后不支持 IPV6的路由器，即有原生 IPv6，但隧道远优于原生 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-465050996 
https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671
