### ISSUE TITLE
空闲，满满的power。一用，IP就猛掉。

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#12316]
![01](https://user-images.githubusercontent.com/39740368/53730685-a338fd80-3eb3-11e9-95bb-36805c0574e0.jpg)

![02](https://user-images.githubusercontent.com/39740368/53730686-a3d19400-3eb3-11e9-8f80-e8184613e235.jpg)

为啥？

**Comment by AnyWAT** [comment]
虽然 IP：100/100，但连接池才2，一用，IP就猛掉，连接池归零。并不满足 #12043 能随时自动维持[有效 IP数/总 IP数之比值=1]( )，说明设置较合适，应该 IP延迟会较小，连接池会较大。——哪里设置不妥？
[隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。
