### ISSUE TITLE
匪类们是不是在开两会

### ISSUE THREAD

**Issue by birds-flying** [XX-net/XX-Net#12312]
匪类们是不是在开两会, 搞的网络不太好啊!!!
有没有同感 ?

**Comment by loy20002000** [comment]
这两天无界和自由门都挂了。这种工具都能挂，墙确实是升高了。

**Comment by ghost111999** [comment]
是的，全世界最大的黑社会组织正在开黑帮大会

**Comment by loy20002000** [comment]
中共不是黑社会，这个定义不太恰当，毕竟是执政党么。

日本[暴力团]的说法比较妥当。

**Comment by jackbaifool** [comment]
大胆暴民小心被煽颠

**Comment by dylanleesky** [comment]
貌似前段时间皇帝微服私访河北了，然后河北就跟半戒严似的。进河北武警先上来查身份证。。。。。。不查还不知道皇帝来了，一查那架势，傻子都知道皇帝来了。不是皇帝也是宰相级别的。其他的一二品大员没那个本事让那个架势的查。、

**Comment by ShineZhang090** [comment]
他大概就是怕你们乱说话
