### ISSUE TITLE
浏览器代理设置fail CA fail

### ISSUE THREAD

**Issue by lhzgnd** [XX-net/XX-Net#12315]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
最新版本3.13.1

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 226
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
代理没选用对？
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by lhzgnd** [comment]
重新配置了代理，问题已经解决。
