### ISSUE TITLE
智能路由器与PAC模式有何区别？

### ISSUE THREAD

**Issue by qibin8687** [XX-net/XX-Net#12328]
这个问题有点白，也可能你们会让我去看基础说明或者搜索论坛官方贴。
我的XXnet部署了gae也开通了Xtunnel，不用omega这类的三方扩展。如果我设置智能路由器模式，且设置为“全部--》smartrouter”，是否软件就会自动调配两种翻墙方式？如果我设置为PAC模式，是否仅启用gae？

**Comment by xugaohui** [comment]
我也不懂，你把smart router关了，那http://127.0.0.1:8086/proxy.pac链接也无效了，需要手动创建相应的pac文件。也就是说smart router功能主要是这个链接的开关，其它功能用处不大。

**Comment by AnyWAT** [comment]
貌似把smart router关了，端口8086被禁用，http://127.0.0.1:8086/proxy.pac 自然无效？

**Comment by AnyWAT** [comment]
或许楼主得 http://127.0.0.1:8085/?module=smart_router&menu=config 添加（检测证书或代理的） .deja.com 走 GAEProxy 就完美了？

**Comment by qibin8687** [comment]
> 
> 
> 我也不懂，你把smart router关了，那[http://127.0.0.1:8086/proxy.pac链接也无效了，需要手动创建相应的pac文件。也就是说smart](http://127.0.0.1:8086/proxy.pac%E9%93%BE%E6%8E%A5%E4%B9%9F%E6%97%A0%E6%95%88%E4%BA%86%EF%BC%8C%E9%9C%80%E8%A6%81%E6%89%8B%E5%8A%A8%E5%88%9B%E5%BB%BA%E7%9B%B8%E5%BA%94%E7%9A%84pac%E6%96%87%E4%BB%B6%E3%80%82%E4%B9%9F%E5%B0%B1%E6%98%AF%E8%AF%B4smart) router功能主要是这个链接的开关，其它功能用处不大。

把smart router关了，http://127.0.0.1:8086/proxy.pac依旧有效。

**Comment by pudy** [comment]
我的理解，smart router会自动尝试直连，直连不通才会走pac规则？
Smart Router 配置 -> 缓存页 就是它尝试后的结果的缓存
