### ISSUE TITLE
teredo 服务器

### ISSUE THREAD

**Issue by CompleX0321** [XX-net/XX-Net#12326]
最近xx-net使用情况不良的解决方法好像都归结到了选择teredo服务器上，
那请问如何才能获取服务器的地址呢？

**Comment by CompleX0321** [comment]
另外，关于掉ip的问题，还有什么措施是应该做的吗？

**Comment by ksit1110** [comment]
无解~~~不过我晓得ANYWAT会告诉你方法的 哈哈哈

**Comment by MadMaxPayne8964** [comment]
我这teredo没一个能用，原生IPv6还有30多个挣扎可用

**Comment by milanthree** [comment]
teredo.trex.fi；我现在用的是这个，还挺稳定的，希望能解决你的问题

**Comment by largewhale** [comment]
静等Anywat回复

**Comment by hubsocks** [comment]
我也在等机器人叫你在cmd下运行什么命令,

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12311#event-2186074555 teredo.ipv6.microsoft.com
https://github.com/XX-net/XX-Net/issues/12329 XX-Net 3.13.1 版本, 454固定Ip, 稳定, 快速

**Comment by hijunling** [comment]
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by CompleX0321** [comment]
> 
> 
> teredo.trex.fi；我现在用的是这个，还挺稳定的，希望能解决你的问题



> 
> 
> 类型 : enterpriseclient
> 服务器名称 : teredo-debian.remlab.net.
> 客户端刷新间隔 : 30 秒
> 客户端端口 : unspecified
> 状态 : qualified
> 客户端类型 : teredo client
> 网络 : unmanaged
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 是，PortPreserving: 是

感谢两位的帮助，我尝试了两位提供的服务器，对于我的网络环境，teredo.trex.fi较为有效，大家可以尝试一下。

**Comment by CompleX0321** [comment]
虽然感谢帮助，但实际上并没有解决我所提出的问题。
服务器时好时坏，也有可能个人所知服务器全部失效，
但是作为一种应对措施，我想知道怎么去获取更多服务器，至少有东西可以给我一个不会代码的使用者去尝试，去操作，
如果题不达意，那某种意义上和嘲讽的某A是一样的，
不能解决问题，
更不利的是对环境造成的负面影响。

**Comment by sys07stone** [comment]
> teredo.trex.fi；我现在用的是这个，还挺稳定的，希望能解决你的问题

实测我也可用

**Comment by AnyWAT** [comment]
> 嘲讽的某A

https://github.com/XX-net/XX-Net/issues/12326#issuecomment-470378689 是嘲讽？
https://github.com/XX-net/XX-Net/issues/12337#issuecomment-470883880 这个呢？

**Comment by SeaHOH** [comment]
公共服务器就那么几个，这只是一种隧道类型而已。
