### ISSUE TITLE
XX-Net 3.13.1 版本, 454固定Ip,  稳定, 快速

### ISSUE THREAD

**Issue by miketwes** [XX-net/XX-Net#12329]
![2019-03-07_616x177](https://user-images.githubusercontent.com/6849681/53931025-77de2a80-40ce-11e9-9397-602a5b5b2046.png)

![2019-03-07_549x709](https://user-images.githubusercontent.com/6849681/53931512-685fe100-40d0-11e9-8192-12d1a481a6e9.png)

上一次测速:

![2019-03-07_668x531](https://user-images.githubusercontent.com/6849681/53931622-f4720880-40d0-11e9-89a1-85b20af66bc9.png)

**Comment by AnyWAT** [comment]
？操作在 https://github.com/XX-net/XX-Net/issues/12320 XX-Net 3.13.1 简化版最新实测
