### ISSUE TITLE
报告一下，XX-Net能用了，就是不知道能挺多久。

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#12322]
![01](https://user-images.githubusercontent.com/39740368/53805273-ac45cf80-3f84-11e9-82f3-50dec42b097c.jpg)
![02](https://user-images.githubusercontent.com/39740368/53805276-acde6600-3f84-11e9-9de0-f4c1c405c2aa.jpg)
![03](https://user-images.githubusercontent.com/39740368/53805278-ad76fc80-3f84-11e9-991e-109cf391b1f5.jpg)
![04](https://user-images.githubusercontent.com/39740368/53805279-ae0f9300-3f84-11e9-9009-280c57513bfc.jpg)
![05](https://user-images.githubusercontent.com/39740368/53805281-ae0f9300-3f84-11e9-83b0-347286e88988.jpg)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/53805802-2034a780-3f86-11e9-99a5-ad9c15292fc3.png)
![image](https://user-images.githubusercontent.com/37962734/53805861-4ce8bf00-3f86-11e9-9b6b-ae8860e29065.png)
😂与楼主比试下 IP延迟及连接池，也反映于有效 IP数/总 IP数之比值，貌似根在某开关的状态：如没关闭，即时最大扫描线程数200比69大许多也无济于事

**Comment by robinlighting** [comment]
原来你说的某开关是这个
https://user-images.githubusercontent.com/37962734/53805861-4ce8bf00-3f86-11e9-9b6b-ae8860e29065.png

**Comment by AnyWAT** [comment]
> 原来你说的某开关是这个

#12043 速度及稳定性较佳体验之秘籍：关闭“自动调整扫描线程数”，适当增加。。。

**Comment by AnyWAT** [comment]
😂英明楼主：#12093 原生ipv6异常，转使用隧道，暂时恢复正常 https://user-images.githubusercontent.com/22696470/51227201-3793e300-198e-11e9-9365-f20527d43175.png

**Comment by loy20002000** [comment]
ipv6 100满的飘过~~~

不过坚持不了太长时间。

**Comment by AnyWAT** [comment]
> 不过坚持不了太长时间。

有效 IP数/总 IP数之比值随时等于1，没有坚持不了。。。

**Comment by zhgna08** [comment]
是好是坏，应该不是设置问题

**Comment by AnyWAT** [comment]
> 是好是坏，应该不是设置问题

在关与不关，如此明显的差异明证下。。。
