### ISSUE TITLE
使用chrome打开youtube主页不能加载缩略图的问题。请教各位大神。

### ISSUE THREAD

**Issue by WBINGUO** [XX-net/XX-Net#12327]
情况是这样。
xxnet已经更新到最新，v6隧道起在路由器上。使用的时候出现了奇怪的问题。
使用chrome打开油管主页后，本应是缩略图的地方是灰色的框，不能加载。
但是用其他工具时，是可以正常打开的。
重要的是：用其他工具正常打开后，再用xxnet就可以正常打开油管并加载了。
然后，如果chrome清理了缓存，用xxnet就又不能加载了。
看了wiki并进行了搜索，没有发现有帮助的帖子。
只能来发帖请教各位大神了。
另外，xxnet下用火狐是可以正常打开的。所以应该是chrome的问题，不是xxnet的问题。。。。。。

**Comment by SeaHOH** [comment]
如果还想追究，请提供更多详细信息。
