### ISSUE TITLE
xx-tunnel 上不了 google sholar

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#12332]
另外一款花了400大元的翻墙软件所有IP挂掉，只好回来使用备用的xx-net。google，youtube都能顺利访问，速度很快，但google scholar无法访问。

目前版本3.13.1
系统win7

**Comment by xlss** [comment]
版本3.7.8也是其他网站都可以访问，最近一年都不能访问scholar，更新至3.13.1还是不行。
系统mac os 10.13.6
