### ISSUE TITLE
最近几天FQ的速度实在是不能更令人满意了啊！！

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#12335]
打开GG的速度飞一样。
![_20190308080446](https://user-images.githubusercontent.com/11325411/53997946-132bda00-4179-11e9-9f65-daef833b65bf.png)

**Comment by yangsl158** [comment]
为啥我的就一直是 "仅 IPv6" 不可用，请检查。
mac 上折腾了好久，之前已经可以了，这几天开始又一直不行了。。郁闷啊。

**Comment by zhgna08** [comment]
lz是用了哪个服务器，这么牛？

**Comment by nly4lov** [comment]
> 为啥我的就一直是 "仅 IPv6" 不可用，请检查。
> mac 上折腾了好久，之前已经可以了，这几天开始又一直不行了。。郁闷啊。

我也才好了一周不到，之前ipv6的ip数一直是个位数

**Comment by nly4lov** [comment]
> lz是用了哪个服务器，这么牛？

从哪里看是哪个服务器

**Comment by yangsl158** [comment]
其实，mac 上怎么换服务器我都还没找到。。。

**Comment by nly4lov** [comment]
> 其实，mac 上怎么换服务器我都还没找到。。。

我不是很确切知道怎么换服务器，即使是在win系统上

**Comment by yangsl158** [comment]
> > 其实，mac 上怎么换服务器我都还没找到。。。
> 
> 我不是很确切知道怎么换服务器，即使是在win系统上

没关系，我们再研究研究，谢谢啦~
