### ISSUE TITLE
XX-NET可能已经被中共接管

### ISSUE THREAD

**Issue by loy20002000** [XX-net/XX-Net#12330]
只是一个误会，bot而已。

**Comment by AnyWAT** [comment]
貌似删贴的是bot非大佬肉身 https://github.com/XX-net/XX-Net/commit/45367b47c981c278d08bb0b1e3417a647c983fd5#commitcomment-32623935

**Comment by loy20002000** [comment]
大哥，这位是 xxnet。

项目作者id是xx-net吧。这位是个爱好者。

**Comment by SeaHOH** [comment]
bot 无误。

单论记忆还是很好的。

**Comment by loy20002000** [comment]
@SeaHOH 

是根据关键字自动删帖的么？

我再去确认下。是github有这个功能，还是微软自动处理的呢？

**Comment by AnyWAT** [comment]
> 大哥，这位是 xxnet。
> 
> 项目作者id是xx-net吧。这位是个爱好者。

貌似你整反了，大佬刚回复 https://github.com/XX-net/XX-Net/commit/45367b47c981c278d08bb0b1e3417a647c983fd5#commitcomment-32630246

**Comment by loy20002000** [comment]
@AnyWAT

我也看到了。大号与小号的关系~~~

刚google了下，这里可以配置bot。我out了。

**Comment by AnyWAT** [comment]
难道 bot 就没有人为操作？貌似遇见过疑似人为。。。

**Comment by loy20002000** [comment]
难道我被封锁了么？

**Comment by loy20002000** [comment]
啊？居然没有。

**Comment by loy20002000** [comment]
我靠，没被吃。到底是哪个关键字出岔子了。触发条件究竟是啥子呢~~~

棱镜门[lengjingmen]

**Comment by loy20002000** [comment]
究竟哪些关键字会被搞掉呢？以下进行测试。我居然被删了超过10个帖子了，你妹的。

**Comment by loy20002000** [comment]
法轮功

**Comment by loy20002000** [comment]
党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
中共、胡锦涛、江泽民、习近平、长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
中共、胡锦涛、江泽民、习近平、长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
胡锦涛、江泽民、习近平、长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
习近平、长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
习近平

**Comment by loy20002000** [comment]
胡锦涛、江泽民、习阿平、长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
习北平、长城防火墙、XX-NET、网络右翼、民进党、党中央、你妹的，法轮功

**Comment by loy20002000** [comment]
习武的平

**Comment by loy20002000** [comment]
平近习

**Comment by loy20002000** [comment]
习大平

**Comment by loy20002000** [comment]
习近平

**Comment by loy20002000** [comment]
胡锦涛、江泽民

**Comment by loy20002000** [comment]
个人信息、监控

**Comment by loy20002000** [comment]
棱镜门、美国安全局、FBI、深网、日本雅虎、软银

**Comment by loy20002000** [comment]
胡大涛、江爱民、习小平

**Comment by loy20002000** [comment]
胡锦涛

**Comment by loy20002000** [comment]
江泽民

**Comment by loy20002000** [comment]
习近平

**Comment by loy20002000** [comment]
毛泽东

**Comment by loy20002000** [comment]
邓小平

**Comment by loy20002000** [comment]
赵紫阳

**Comment by loy20002000** [comment]
胡耀邦

**Comment by loy20002000** [comment]
包子、平西王、康师傅

**Comment by loy20002000** [comment]
你说的是不是明慧网的那些文章你觉得很多都不可信？法轮功如果不是祛病健身有奇效，一开始大家都对气功修炼不了解的时候会有那么多人炼吗？确实有很多人都是到医院治不好的疑难病甚至是绝症炼功以后都好了，现代科学还认识不到的东西太多了，过去《圣经》中不也记载过耶稣给人治病的事情吗？这方面真的希望你再多了解一下。还一个无界主页只是一个门户，那里转载的链接比如大纪元新唐人的新闻，如果哪条新闻你觉得是骂人造谣的，完全可以直接和网站编辑反馈，只要你说的正确我想他们会接受的，其他的一些媒体有可能是民运人士办的。不知道你看过九评共产党没有，那里说的都是历史真相。另外看你别的帖子好像你家人也一直受共产党的迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
大纪元新唐人的新闻，如果哪条新闻你觉得是骂人造谣的，完全可以直接和网站编辑反馈，只要你说的正确我想他们会接受的，其他的一些媒体有可能是民运人士办的。不知道你看过九评共产党没有，那里说的都是历史真相。另外看你别的帖子好像你家人也一直受共产党的迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
新唐人的新闻，如果哪条新闻你觉得是骂人造谣的，完全可以直接和网站编辑反馈，只要你说的正确我想他们会接受的，其他的一些媒体有可能是民运人士办的。不知道你看过九评共产党没有，那里说的都是历史真相。另外看你别的帖子好像你家人也一直受共产党的迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
九评共产党没有，那里说的都是历史真相。另外看你别的帖子好像你家人也一直受共产党的迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
共产党

**Comment by loy20002000** [comment]
唐

**Comment by loy20002000** [comment]
新唐

**Comment by loy20002000** [comment]
新唐人

**Comment by loy20002000** [comment]
大纪元

**Comment by loy20002000** [comment]
你说的是不是明慧网的那些文章你觉得很多都不可信？法轮功如果不是祛病健身有奇效，一开始大家都对气功修炼不了解的时候会有那么多人炼吗？

**Comment by loy20002000** [comment]
确实有很多人都是到医院治不好的疑难病甚至是绝症炼功以后都好了，现代科学还认识不到的东西太多了，过去《圣经》中不也记载过耶稣给人治病的事情吗？

**Comment by loy20002000** [comment]
这方面真的希望你再多了解一下。还一个无界主页只是一个门户，那里转载的链接比如大纪元新唐人的新闻，如果哪条新闻你觉得是骂人造谣的，完全可以直接和网站编辑反馈，只要你说的正确我想他们会接受的，其他的一些媒体有可能是民运人士办的。

**Comment by loy20002000** [comment]
不知道你看过九评共产党没有，那里说的都是历史真相。另外看你别的帖子好像你家人也一直受共产党的迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
另外看你别的帖子好像你家人也一直受共产党的迫害啊，为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

**Comment by loy20002000** [comment]
另外看你别的帖子好像你家人也一直受共产党的迫害啊

**Comment by dylanleesky** [comment]
> 为什么还对其党的真实面目认识不清呢？实在有些可叹了。如果还有问题请在这里回复。

认清也好，认不清也好。那又怎样呢？生活该怎样依旧怎样，闲暇之余骂两句。
有能力有眼光的早就花过钱了

**Comment by loy20002000** [comment]
@dylanleesky

这是复制另外一位网友的回复，他的回复被删除。我仅仅是测试一下哪些部分敏感。

**Comment by xxnet** [comment]
回复一下，为什么增加关键词过滤，主要是防刷屏，其中有广告，也有一些宣传。
   
历史原因，之前有些关键词没有必要的，刚才已经清理掉。

大家讨论注意保持理性，讲逻辑讲依据，互相尊重，骂人者警告、封号。

**Comment by AnyWAT** [comment]
给楼主提供个疑似证据😜 https://github.com/XX-net/XX-Net/issues/12043

![image](https://user-images.githubusercontent.com/37962734/54262088-54245400-45a8-11e9-9af3-3f988e1e735f.png)

**Comment by loy20002000** [comment]
@xxnet 

我还以为这个项目被接管了，我在很多老的帖子发贴警告。结果仅仅是个误会~~~

手机端和PC的XX都被我删除了，又得重新配置了。
