### ISSUE TITLE
"仅 IPv6" 不可用，请检查。             IPv6 状态(如何开启)	Fail (尝试修复)

### ISSUE THREAD

**Issue by murder1999** [XX-net/XX-Net#12333]
求解？

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 334
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by mmwchannel** [comment]
我也是这样的情况，昨天都还好的

**Comment by murder1999** [comment]
有点烦

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by murder1999** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by murder1999** [comment]
@AnyWAT

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——服务器陷阱！#12043

**Comment by daxinnan** [comment]
我用的Ubuntu，年前好好的，中间有一段时间临时只用了USB网络共享，后来换回正常的校园网，就不行了。
```
XX-Net Status:

sys-platform: x86_64, Linux-4.18.0-16-generic-x86_64-with-Ubuntu-18.10-cosmic
os-system: Linux
os-version: #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019
os-release: 4.18.0-16-generic
os-detail: Dist:Ubuntu; Version:18.10; ID:cosmic
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/72.0.3626.119 Chrome/72.0.3626.119 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.15+
openssl-version: 18.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 265
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by AnyWAT** [comment]
ipv6-status: Fail ——隧道不合适？
scan-ip-thread-num: 1 ——貌似没关闭某开关？
参考 #12043 禁用原生（IPv6协议）用隧道，【找出并更换适用于自己的服务器】
或禁用隧道勉强用原生 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671

**Comment by ezhyg** [comment]
前几天还有99IP，这几天连IPV6都失败了。看来TG是有目的的

**Comment by fengyuwuzu00** [comment]
C:\WINDOWS\system32>netsh int ipv6 show teredo state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed
求解？

**Comment by daxinnan** [comment]
> 我用的Ubuntu，年前好好的，中间有一段时间临时只用了USB网络共享，后来换回正常的校园网，就不行了。
> 
> ```
> XX-Net Status:
> 
> sys-platform: x86_64, Linux-4.18.0-16-generic-x86_64-with-Ubuntu-18.10-cosmic
> os-system: Linux
> os-version: #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019
> os-release: 4.18.0-16-generic
> os-detail: Dist:Ubuntu; Version:18.10; ID:cosmic
> architecture: 64bit,
> browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/72.0.3626.119 Chrome/72.0.3626.119 Safari/537.36
> xxnet-version: 3.13.1
> python-version: 2.7.15+
> openssl-version: 18.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: force_ipv6
> gws-ip-num: total:100 ipv4:0 ipv6:100
> ipv4-status: OK
> ipv6-status: Fail
> connected-link: new:0
> worker: h1:0 h2:0
> scan-ip-thread-num: 1
> ip-quality: 265
> is-idle: 1
> proxy_state: OK
> ca_state: OK
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false
> ```

今天又正常了，可能是昨天网络环境不正常吧

**Comment by murder1999** [comment]
@AnyWAT  朋友，现在状态是这样：

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.2.139:58601
外部 NAT 映射    : 221.15.24.230:44184


还有你之前的帖子，小白我看不懂啊

**Comment by murder1999** [comment]
@AnyWAT  我觉得是 服务器的原因，怎么将现在的服务器： win1711.ipv6.microsoft.com.    改成其他的能用的服务器？

你引用的帖子， 我看的一头雾水啊。能不能来个傻瓜式操作？

**Comment by AnyWAT** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

> 本地映射 : -----
> 外部 NAT 映射 : -----
> 
> 还有你之前的帖子，小白我看不懂啊

确实难懂，连（无需 IP地址的2行）都做不到！

😥温故而知新 #12043

**Comment by murder1999** [comment]
@AnyWAT
大佬忘记了 “明白一个东西的人不记得他当初不明白时的状态”
**另：问题已解决。确实是服务器的原因。**  

anyWAT 的帖子 #12043 是有效的，只不过行文确实写意，在下第二次看时才明白他说的啥😥。以下是换服务器的方法：

1. 调出控制台。输入以下代码测试出可用的服务器：
`ping teredo.iks-jena.de`
（注：“ping **teredo.iks-jena.de**”  中的**teredo.iks-jena.de**，是服务器的名字，这个“teredo.iks-jena.de”并不一定可用，你需要依次测试下面列表中的服务器，找出一个可用的：
- teredo.iks-jena.de
teredo.trex.fi
teredo.remlab.net
teredo2.remlab.net
teredo-debian.remlab.net）

2.若显示“**请求超时**”，则说明此服务器不可用，请在上表中**另选一个**服务器继续检测，直到显示：
`来自 217.17.192.217 的回复: 字节=32 时间=277ms TTL=47
来自 217.17.192.217 的回复: 字节=32 时间=277ms TTL=47
……`
之类的信息，这表示你测试的服务器可用了

3.在控制台中输入： `netsh int ipv6 set teredo enterpriseclient  **XXX** ` ，其中“XXX” 就是你刚才测试过的可用的服务器。例如：`netsh int ipv6 set teredo enterpriseclient  **teredo.iks-jena.de** `

4.显示“**确定**”。请重新查看XX-net，如果是服务器的原因，此时应该已经好了。

**Comment by AnyWAT** [comment]
> 若显示“**请求超时**”，则说明此服务器不可用，请在上表中**另选一个**服务器继续检测

违背：#12043 摒弃（巨硬的）服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 并能扫描出 IP才是真正的好。

**Comment by murder1999** [comment]
@AnyWAT

> 违背：#12043 摒弃（巨硬的）服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 IPv6 状态(如何开启) 较快 OK 并能扫描出 IP才是真正的好。
经验：能Ping 出 IP的即可尝试。。。

你说的对。这本来没有多少东西，只是你的#12043，是对的，但却像机器翻译一般，根本看不出你真正想表达的意思。十分建议你用markdown格式书写并重新修改叙述。当然，能够愿意回复帮助别人已经不可多求，我实在是强人所难。总之，谢谢。

**Comment by AnyWAT** [comment]
> 用markdown格式

不明觉厉。https://github.com/XX-net/XX-Net/issues/12043#issuecomment-470874479

**Comment by daxinnan** [comment]
一到晚上有效ip数就降到个位数。。

**Comment by AnyWAT** [comment]
> 一到晚上有效ip数就降到个位数。。

参考：#12043 速度及稳定性较佳体验之秘籍：。。。

**Comment by chuntju** [comment]
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

**Comment by chuntju** [comment]
> ipv6-status: Fail ——隧道不合适？
> scan-ip-thread-num: 1 ——貌似没关闭某开关？
> 参考 #12043 禁用原生（IPv6协议）用隧道，【找出并更换适用于自己的服务器】
> 或禁用隧道勉强用原生 [#12043 (comment)](https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671)



> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

辛苦大牛，帮忙看下这个是什么问题？多谢
【"仅 IPv6" 不可用，请检查。】

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——服务器陷阱！
#12043【[找出并更换适用于自己的服务器]( )】

**Comment by chuntju** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com. ——服务器陷阱！[#12333 (comment)](https://github.com/XX-net/XX-Net/issues/12333#issuecomment-470495513)
> #12043【找出并更换适用于自己的服务器】
> ![image](https://user-images.githubusercontent.com/37962734/54341908-1261df00-4676-11e9-8829-f0bba8020733.png)

**【已解决】已按照指导方法解决，但巨硬服务器一点都不硬，尝试了很多个才有一个可以。**

**Comment by AnyWAT** [comment]
> 【已解决】已按照指导方法解决，但巨硬服务器一点都不硬，尝试了很多个才有一个可以。

事物是不断变化的。。。
貌似仅剩2个可用：157.56.106.184 、157.56.106.189

**Comment by rwoue** [comment]
> @AnyWAT
> 大佬忘记了 “明白一个东西的人不记得他当初不明白时的状态”
> **另：问题已解决。确实是服务器的原因。**
> 
> anyWAT 的帖子 #12043 是有效的，只不过行文确实写意，在下第二次看时才明白他说的啥。以下是换服务器的方法：
> 
> 1. 调出控制台。输入以下代码测试出可用的服务器：
>    `ping teredo.iks-jena.de`
>    （注：“ping **teredo.iks-jena.de**”  中的**teredo.iks-jena.de**，是服务器的名字，这个“teredo.iks-jena.de”并不一定可用，你需要依次测试下面列表中的服务器，找出一个可用的：
> 
> * teredo.iks-jena.de
>   teredo.trex.fi
>   teredo.remlab.net
>   teredo2.remlab.net
>   teredo-debian.remlab.net）
> 
> 2.若显示“**请求超时**”，则说明此服务器不可用，请在上表中**另选一个**服务器继续检测，直到显示：
> `来自 217.17.192.217 的回复: 字节=32 时间=277ms TTL=47 来自 217.17.192.217 的回复: 字节=32 时间=277ms TTL=47 ……`
> 之类的信息，这表示你测试的服务器可用了
> 
> 3.在控制台中输入： `netsh int ipv6 set teredo enterpriseclient XXX ` ，其中“XXX” 就是你刚才测试过的可用的服务器。例如：`netsh int ipv6 set teredo enterpriseclient teredo.iks-jena.de `
> 
> 4.显示“**确定**”。请重新查看XX-net，如果是服务器的原因，此时应该已经好了。

天呐真的非常感谢，按照大佬你这个步骤我搞定了停工足足有三个月的xxnet！！（anywat大佬的帖子白过白纸的我实在参透不了

**Comment by rwoue** [comment]
> @AnyWAT
> 大佬忘记了 “明白一个东西的人不记得他当初不明白时的状态”
> **另：问题已解决。确实是服务器的原因。**
> 
> anyWAT 的帖子 #12043 是有效的，只不过行文确实写意，在下第二次看时才明白他说的啥。以下是换服务器的方法：
> 
> 1. 调出控制台。输入以下代码测试出可用的服务器：
>    `ping teredo.iks-jena.de`
>    （注：“ping **teredo.iks-jena.de**”  中的**teredo.iks-jena.de**，是服务器的名字，这个“teredo.iks-jena.de”并不一定可用，你需要依次测试下面列表中的服务器，找出一个可用的：
> 
> * teredo.iks-jena.de
>   teredo.trex.fi
>   teredo.remlab.net
>   teredo2.remlab.net
>   teredo-debian.remlab.net）
> 
> 2.若显示“**请求超时**”，则说明此服务器不可用，请在上表中**另选一个**服务器继续检测，直到显示：
> `来自 217.17.192.217 的回复: 字节=32 时间=277ms TTL=47 来自 217.17.192.217 的回复: 字节=32 时间=277ms TTL=47 ……`
> 之类的信息，这表示你测试的服务器可用了
> 
> 3.在控制台中输入： `netsh int ipv6 set teredo enterpriseclient XXX ` ，其中“XXX” 就是你刚才测试过的可用的服务器。例如：`netsh int ipv6 set teredo enterpriseclient teredo.iks-jena.de `
> 
> 4.显示“**确定**”。请重新查看XX-net，如果是服务器的原因，此时应该已经好了。

天呐真的非常感谢，按照大佬你这个步骤我搞定了停工足足有三个月的xxnet！！（anywat大佬的帖子白过白纸的我实在参透不了

**Comment by AnyWAT** [comment]
"仅 IPv6" 不可用，请检查。 #12355

**Comment by AnyWAT** [comment]
【更新】Teredo 隧道：#12455 或原生：#12477
近期后者更佳！
