### ISSUE TITLE
IPV6OK，连接池始终为零，已按着12043走过一遍，仍然没法用

### ISSUE THREAD

**Issue by TFNikolai** [XX-net/XX-Net#12349]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:454 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by TFNikolai** [comment]
希望各位大佬帮忙看一下，谢谢。

**Comment by AnyWAT** [comment]
已按着12043走过一遍，仍然没贴出隧道信息？

**Comment by TFNikolai** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 195.140.195.140
客户端刷新间隔          : 30 秒
客户端端口                : 7164
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否


> 已按着 #12043 走过一遍了，仍然没能贴出隧道信息？
> ![image](https://user-images.githubusercontent.com/37962734/54083075-fdc1d600-4359-11e9-8d0d-e5d4cf926ec3.png)
> [#12348 (comment)](https://github.com/XX-net/XX-Net/issues/12348#issuecomment-471253117)

**Comment by AnyWAT** [comment]
#12043 更新：[隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。
再不济，像隔壁软件的换端口回默认的未定义或其它4-5位数？

**Comment by AnyWAT** [comment]
> 客户端类型 : teredo host-specific relay

😱意外发现：开始是禁用原生 IPv6的正常隧道，有效 IP数/总 IP数之比=1，勾选网络属性内的 IPv6协议，在原生 IPv6连接上后，隧道就变成了该种客户端类型，有效 IP数及连接池直线下降到接近0，IP延迟到9999。反之，取消勾选网络属性内的 IPv6协议以禁用原生，恢复。。。
