### ISSUE TITLE
没有IP

### ISSUE THREAD

**Issue by cutecate** [XX-net/XX-Net#12341]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: unknown
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是
* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
> 没有IP

如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by cutecate** [comment]
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : win1711.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : managed
NAT                     : symmetric (port)
NAT Special Behaviour   : UPNP: No, PortPreserving: No

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12339#issuecomment-470941053
服务器名称 : win1711.ipv6.microsoft.com. ——掉入服务器陷阱：尽管隧道能连接（状态 : qualified ），但扫描不到 IP #12043

**Comment by cutecate** [comment]
参考#12043 解决？

**Comment by AnyWAT** [comment]
服务器陷阱：几乎没有正常的时候，但总是被推荐。命令行更换服务器

**Comment by Alobe007** [comment]
> ## Teredo Parameters
> Type : enterpriseclient
> Server Name : win1711.ipv6.microsoft.com.

可以肯定是这个Server有问题。我用这个从来没成过。换别的试试吧。
