### ISSUE TITLE
求助，ipv6 failed，但是手机端正常

### ISSUE THREAD

**Issue by yyngtx** [XX-net/XX-Net#12348]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by yyngtx** [comment]
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

==================================================

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:200 ipv4:0 ipv6:200
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 100
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


系统已经重做，故障依旧。如果使用原生ipv6，有效IP为0。

**Comment by oookooo** [comment]
https://github.com/XX-net/XX-Net/wiki/IPv6-Win10

建议直接用脚本 enable_ipv6.bat

**Comment by Alobe007** [comment]
> 服务器名称 : win10.ipv6.microsoft.com

这个服务器不可用。换其它的。

**Comment by AnyWAT** [comment]
> 系统已经重做，故障依旧。

小题大做？能同时贴出隧道及诊断信息，貌似见过 #12043 

> ipv6 failed，但是手机端正常

（非数据流量？）手机与电脑同一网络？同一隧道？[隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。

**Comment by AnyWAT** [comment]
此刻  ping win10.ipv6.microsoft.com 结果 40.81.120.221

> 这个服务器不可用。换其它的。

或许👍

**Comment by AnyWAT** [comment]
> 建议直接用脚本 enable_ipv6.bat 最简单的方法

如Win10系统有版本号系统更新，貌似会被系统默认关闭隧道，管理员 cmd：
netsh int ipv6 set teredo enterpriseclient _即可启用隧道_，（首次使用隧道或得由[控制页](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel)内的“[启用](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel)”完成 ）
netsh int ipv6 set teredo disable _即可禁用隧道_。（完全禁用隧道或得由[控制页](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel)内的“[禁用](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#ipv6_tunnel)”完成 ）

**Comment by yyngtx** [comment]
> > 系统已经重做，故障依旧。
> 
> 小题大做？能同时贴出隧道及诊断信息，貌似见过 #12043 或类似。。。
> 
> > （电脑）ipv6 failed，但是手机端正常
> 
> （非数据流量？）手机与电脑同一网络？同一隧道？
> #12043 更新：隧道显示正常但连接池或有效 IP数归零时：或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器，或免退出再次启动软件。。。

昨天突然不好用的。之前一直没问题。手机是处于同一局域网，应该不是同一个隧道吧。隧道禁用、禁用无效，更换隧道服务器无效，重启软件无效。

**Comment by AnyWAT** [comment]
> 昨天突然不好用的

与 #12043 巨硬服务器域名随时改变指向到其它（不可用）IP 吻合

> 更换隧道服务器无效

貌似还没【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】，试试 #12043 157.56.106.184、157.56.106.189、217.17.192.217、195.140.195.140

**Comment by yyngtx** [comment]
> > 昨天突然不好用的
> 
> 与 #12043 巨硬服务器域名随时改变指向到其它（不可用）IP 吻合
> 
> > 隧道禁用、禁用无效，更换隧道服务器无效，重启软件无效。
> 
> > 此刻  ping win10.ipv6.microsoft.com 结果 40.81.120.221
> 
> 貌似服务器无效，自然隧道禁用、启用无效，重启软件无效。还没【[找出并更换适用于自己的服务器](https://github.com/XX-net/XX-Net/issues/12043)】，试试 #12043 157.56.106.184、157.56.106.189、217.17.192.217、195.140.195.140、83.170.6.76 。。。

更换隧道服务器157.56.106.184瞬间就好了。。。。不过依然不知道手机端为什么没问题

感谢！

**Comment by AnyWAT** [comment]
> 不过依然不知道手机端为什么没问题

> 手机是处于同一局域网，应该不是同一个隧道吧

或许不是同一个隧道，或许WIFI 与直连的机制不同而。。。

**Comment by peterchan201604** [comment]
我的今天一天上线很稳定
