### ISSUE TITLE
请教如何设置xx-net的good_ip.txt文件的路径

### ISSUE THREAD

**Issue by oookooo** [XX-net/XX-Net#12346]
请教如何设置xx-net里   ”../data/gae_proxy/good_ip.txt“  文件的路径?
我使用OneDirve 同步xx-net  但是如果同时在两台电脑上开启xx-net的时候OneDrive会提示 ”good_ip.txt“ 无法写入，会不停生成格式为 ”good_ip-算机名-x.txt“ 的文件。  据我猜测问题应该是OneDrive服务器无法同时对两个计算机发去的修改写入同一文件造成的。想试着修改 ”good_ip.txt“ 到OneDrive以外的文件夹试试。不知能否通过设置 ”config.json“ 来实现修改 ”good_ip.txt“ 的路径？如果能改怎么设置？望指教

**Comment by AnyWAT** [comment]
貌似 IPv6 已与同一文件适用于任何网络、电脑的 IP4大不同，有必要同步？此机此时的 good_ip.txt 未必适用于此机彼时，也未必适用于此时的彼机，如果2台电脑的网络不同，还有同一服务器也未必同时适用于2台。#12043 设置合适 https://github.com/XX-net/XX-Net/issues/12093#issuecomment-459199446 有效的隧道会在半分钟左右把ip扫满，延迟也很低。

**Comment by AnyWAT** [comment]
good_ip：
IP4 #11775
IP6 https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138

**Comment by oookooo** [comment]
> 貌似的IPv6（隧道）已与同一文件适用于任何网络，电脑的以往IP4大不同，有必要同步？此机此时的good_ip.txt未必适用于此机彼时，也未必适用于此时的彼机，如果2台电脑的网络不同，还有同一隧道服务器也未必同时适用于2台。[＃12043](https://github.com/XX-net/XX-Net/issues/12043)设置合适，能随时自动维持有效IP数/总IP数之比值= 1，应该IP延迟会较小，连接池会较大。[＃12093（评论）](https://github.com/XX-net/XX-Net/issues/12093#issuecomment-459199446)有效的隧道会在半分钟左右把ip扫满，延迟也很低。

是不必要同步 就是因为不必要所有要修改 ”good_ip.txt“的路径 其实问题不在xx-net  我已经可以上真网了，主要是Onedrive 一直提示文件冲突 特烦

**Comment by AnyWAT** [comment]
修改 ”good_ip.txt“的路径，无非修改XX-Net 软件内部参数？
没太明白，把XX-Net 置于Onedrive 需要同步的硬盘系统之外，不就行了？

**Comment by oookooo** [comment]
> 修改“good_ip.txt”的路径，无非修改XX-Net软件内部参数？
> 没太明白，把XX-Net置于Onedrive需要同步的硬盘系统之外，不就行了？

我当然知道不把xx-net放在同步盘可以 ，出于折腾，也出于配置一次全部可以用的想法嘛，想捣鼓下”config.json“，既然拥有设置，改个文件路径一个不是麻烦事。

**Comment by AnyWAT** [comment]
> 既然拥有设置，改个文件路径应该不是麻烦事。

还没见过。Onedrive 能否排除同步某文件？

**Comment by oookooo** [comment]
> > 既然拥有设置，改个文件路径应该不是麻烦事。
> 
> 还没见过.Onedrive能否排除同步某文件？

OneDrive只能排除 文件夹 单文件不可以，而且也不能排除排除了，就相当删掉了。不像小乌龟可以任意选文件。

**Comment by SeaHOH** [comment]
改不了
