### ISSUE TITLE
买了一季度的X-Tunnel，但是看不到剩余流量！也看不到残余美刀  ：)  

### ISSUE THREAD

**Issue by XuQingJiaYi** [XX-net/XX-Net#12343]
有paypal交易单号，第一次用paypal，这个应该就是单号的一部分的吧
掉了一部分字母数字后的编号为0058V6355540M

**Comment by weicen** [comment]
我用的机场5元一个月400G流量比X-Tunnel爽多了，你可以试一下dmcloud.cf 邀请码B4705181B47D

**Comment by weicen** [comment]
另一个邀请码2862EABFBC66

**Comment by weicen** [comment]
还可以免费撸半个月哦

**Comment by XuQingJiaYi** [comment]
已经看到流量类，嘿嘿，谢谢！:)

**Comment by Potato133** [comment]
哪位大佬有X-Tunnel邀请码
