### ISSUE TITLE
xx-net不可用

### ISSUE THREAD

**Issue by 1990chs** [XX-net/XX-Net#12340]
北京电信，原生IPV6，但是最近用XX-net一直扫描不到有效IPV6地址，是不是被墙了？

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 98

**Comment by AnyWAT** [comment]
有原生的移动，隧道远优于原生 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671 🤣有原生 IPv6的勉强玩法：。。。
