### ISSUE TITLE
ipv6 过一会就Fail了（尝试修复），用enable_ipv6也不行. 切换服务器也不行

### ISSUE THREAD

**Issue by HuitMahoon** [XX-net/XX-Net#12354]
netsh int  teredo  show state这个指令出来的信息是：
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:5
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！
状态 : qualified ——貌似已连接
ipv6-status: Fail ——貌似扫描不到 IP
服务器名称 : win1710.ipv6.microsoft.com. ——服务器陷阱！
切换服务器也不行—— #12043 【[找出并更换适用于自己的服务器]( )】

**Comment by AnyWAT** [comment]
> ipv6 过一会就Fail了

#12043 关闭某开关！
