### ISSUE TITLE
CMCC-EDU 无法打开登录页了

### ISSUE THREAD

**Issue by kankan666** [XX-net/XX-Net#12350]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
使用XX-net以后，问题① CMCC-EDU登录页再也没法打开了；问题② 经常出现打开浏览器无法上网，通过腾讯电脑管家网络修复，显示DNS配置错误，修复后可上网。

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
貌似校园网？默认原生 IPv6连通，IPv4需验证后才连通？https://github.com/XX-net/XX-Net/issues/12275 使用后，校园网无法portal验证了。
XX-net 是使用原生 IPv6还是其它隧道？代理的设置、选用？

**Comment by kankan666** [comment]
XX-NET已经关闭了，CMCC-Edu（只有ipv4）没法打开登录页

**Comment by AnyWAT** [comment]
> * 使用XX-net以后，问题① CMCC-EDU登录页再也没法打开了；问题② 经常出现打开浏览器无法上网

> XX-net 是使用原生 IPv6还是其它隧道？代理的设置、选用？

回答：
> XX-NET已经关闭了，CMCC-Edu（只有ipv4）没法打开登录页

合适么？

**Comment by AnyWAT** [comment]
> XX-NET已经关闭了，CMCC-Edu（只有ipv4）没法打开登录页

http://ask.zol.com.cn/x/7899886.html 移动WLAN CMCC-EDU登陆界面肿么打开
