### ISSUE TITLE
发现一件诡异的现象：不要去看有效ip多少个！

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#12352]
过若干时间，点击托盘的xx图标，google chrome会弹出那个xx状态页面，总ip 100个，有效100个，然后有效的数字会立刻往下掉，有时候会掉到10几个甚至是1 个，这时候当然翻不出了。
赶紧关掉。过段时间再看又是100，发现你看它，又掉。。。。

这是啥情况？怕看吗？

**Comment by AnyWAT** [comment]
貌似最大扫描线程数小了点，主要是没关闭某开关？#12043 能随时自动维持有效 IP数/总 IP数之比值=1，说明设置较合适，应该 IP延迟会较小，连接池会较大。

**Comment by nly4lov** [comment]
> 貌似最大扫描线程数小了点，主要是没关闭某开关？#12043 能随时自动维持有效 IP数/总 IP数之比值=1，说明设置较合适，应该 IP延迟会较小，连接池会较大。

最大扫描线程是10....某开关是哪个开关？

**Comment by AnyWAT** [comment]
#12043 关闭“自动调整扫描线程数”，最大扫描线程数以能自动维持：有效 IP数/总 IP数之比值=1 时为最小值

**Comment by nly4lov** [comment]
@AnyWAT 那个关掉了呀。

**Comment by hubsocks** [comment]
@AnyWAT 软件内置总共才4百多个ipv6地址.你开这么多线程去扫,你电脑里面有地雷吧?
