### ISSUE TITLE
关闭xx-net之后，校园网登不上去

### ISSUE THREAD

**Issue by C01DZin** [XX-net/XX-Net#12368]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
试过

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

打开xx-net之后一切正常，但是关闭之后却无法连上原来不开xx-net就可以连上的校园网
输入网址后就显示网页不存在，无法访问之列的

**Comment by AnyWAT** [comment]
？使用后，校园网无法portal验证了。 #12275

**Comment by C01DZin** [comment]
应该是ipv6隧道，我看上面显示teredo是禁用的状态
