### ISSUE TITLE
[PowerShell脚本]检测通道ip,设置延迟最低的一个

### ISSUE THREAD

**Issue by wycaca** [XX-net/XX-Net#12361]
以下代码保存为.ps1文件
右键使用PowerShell运行

#requires -version 4.0
#requires #-runasadministrator

#管理员身份识别
$myWindowsID = [System.Security.Principal.WindowsIdentity]::GetCurrent();
$myWindowsPrincipal = New-Object System.Security.Principal.WindowsPrincipal($myWindowsID);
$adminRole = [System.Security.Principal.WindowsBuiltInRole]::Administrator;
if ($myWindowsPrincipal.IsInRole($adminRole)) {
    # $Host.UI.RawUI.WindowTitle = $myInvocation.MyCommand.Definition + “(Elevated)”;
    # $Host.UI.RawUI.BackgroundColor = 0;
    Clear-Host;
}
else {
    $newProcess = New-Object System.Diagnostics.ProcessStartInfo “PowerShell”;
    $newProcess.Arguments = “& ‘” + $script:MyInvocation.MyCommand.Path + “‘”
    $newProcess.Verb = “runas”;
    [System.Diagnostics.Process]::Start($newProcess);
    Exit;
}

$MaxThreadsNum = 8
$domains = "teredo.remlab.net",
"teredo2.remlab.net",
"teredo-debian.remlab.net",
"teredo.trex.fi",
"teredo.iks-jena.de",
"win10.ipv6.microsoft.com",
"win1710.ipv6.microsoft.com",
"win1711.ipv6.microsoft.com"

$Test = {
    Param (
        [String] $Domain
    )
    $a = Test-Connection $Domain -Count 1
    if ($a)
    {
        $RunResult = New-Object PSObject -Property @{
            Domain = $Domain
            IP     = $a.ipv4address.IPAddressToString
            Time   = $a.ResponseTime
        }
    }
    Return $RunResult
}

#资源池
$RunspacePool = [RunspaceFactory]::CreateRunspacePool(1, $MaxThreadsNum)
$RunspacePool.Open()
$Jobs = @()
Foreach ($domain in $domains)
{
    $Job = [powershell]::Create().AddScript($Test).AddArgument($domain)
    $Job.RunspacePool = $RunspacePool
    $Jobs += New-Object PSObject -Property @{
        Server = $domain
        Pipe   = $Job
        Result = $Job.BeginInvoke()
    }
}

#等待所有的job都完成
Write-Host "请稍等" -NoNewline
Do {
    Write-Host "." -NoNewline
    Start-Sleep -Seconds 1
} While ( $Jobs.Result.IsCompleted -contains $false)
"所有任务 completed!"

#输出结果
$Results = @()
ForEach ($Job in $Jobs) {
    $Results += $Job.Pipe.EndInvoke($Job.Result)

}
$Results = $Results | Sort-Object -Property Time
$Results
netsh interface teredo set state server= $Results[0].IP

**Comment by AnyWAT** [comment]
1、win1807.ipv6.microsoft.com ？
2、右键使用PowerShell 运行，点开立马自动退出，原来需要管理权限，对不是 administrator 的管理员。。。
3、延迟最低？貌似一直巨硬的 Ping超时但可用？。。。#12043 摒弃巨硬的服务器Ping 超时就不能用的错误认识，其它Ping 值小的不一定能连接、也未必就好，不（只）看 ping 得通与否、快与慢，隧道能较快连接且 [IPv6 状态(如何开启)](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 较快 OK 并能扫描出 IP才是真正的好。
