### ISSUE TITLE
手动更新teredo服务器没效果

### ISSUE THREAD

**Issue by haiyuancheng** [XX-net/XX-Net#12366]
C:\WINDOWS\system32>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 157.56.106.184
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

C:\WINDOWS\system32>netsh interface teredo set state enterpriseclient 157.56.106.184. default default default

**Comment by AnyWAT** [comment]
😱不是不明白，这世界变化快！貌似刚说的巨硬仅 157.56.106.184、157.56.106.189 可用，但此刻已不可用。至此，巨硬已无可用服务器？
> 手动更新teredo服务器没效果

https://github.com/XX-net/XX-Net/issues/12043 【[找出并更换适用于自己的服务器]( )】——继续。。。

**Comment by FergonXie** [comment]
不用折腾这个了，作者已经给出说明了，是因为国内大多路由器不支持IP6的原因 。 找个支持IP6的路由器就ok。 我就处于移动网，换个支持IP6的路由器，啥都不用折腾，非常稳定 。

**Comment by AnyWAT** [comment]
> 找个支持IP6的路由器就ok。 我就处于移动网，换个支持IPV6的路由器，啥都不用折腾，非常稳定 。

移动网、撤下光猫后不支持 IPV6的路由器，即有原生 IPv6，但隧道远优于原生 https://github.com/XX-net/XX-Net/issues/12043#issuecomment-465050996 
https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671

**Comment by wz7465** [comment]
春风终于吹到你那山沟沟了？ :smile:

**Comment by apersonlikesc** [comment]
这谁顶的住啊 ！
