### ISSUE TITLE
重新做回自由门徒，XX-NET，等你回来

### ISSUE THREAD

**Issue by jazzcat31** [XX-net/XX-Net#12360]
RT
xxnet和电信说拜拜，ipv6不可用，9999，红条，拜拜！

**Comment by AnyWAT** [comment]
移动隧道一直🆗，原生远不如隧道。

**Comment by jazzcat31** [comment]
> 移动隧道一直🆗，原生远不如隧道。

机器人大哥，感谢有你

**Comment by AnyWAT** [comment]
移动原生下的9999勉强可用，辅以 dnscrypt-proxy 更好？

**Comment by AnyWAT** [comment]
你看看淫家电信 https://github.com/XX-net/XX-Net/issues/12365#issuecomment-473138703

**Comment by CDCfishzz** [comment]
> RT
> xxnet和电信说拜拜，ipv6不可用，9999，红条，拜拜！

请指条路吧!!!!

**Comment by AnyWAT** [comment]
> 请指条路吧!!!!

已入门闭户听不见😂

**Comment by solohu** [comment]
> （正在）移动原生下（2-5个 IP）的9999勉强可用，貌似辅以 dnscrypt-proxy 更好

大神，dnscrypt-proxy 怎么使用？

**Comment by AnyWAT** [comment]
https://github.com/CNMan/dnscrypt-proxy-config

**Comment by jazzcat31** [comment]
> > RT
> > xxnet和电信说拜拜，ipv6不可用，9999，红条，拜拜！
> 
> 请指条路吧!!!!

fg766p, 利用omega新建代理端口

**Comment by qindy** [comment]
XX-NET不行了，我现在用lostcloud    https://lostcloud.org/auth/register?code=H48JjeS59229XP47

**Comment by AnyWAT** [comment]
> XX-NET不行了

![image](https://user-images.githubusercontent.com/37962734/54550240-9b667680-49e6-11e9-81ea-9c078301bea4.png)
