### ISSUE TITLE
xxnet每次更新能用几小时，之后就挂了是不是被跟踪了'

### ISSUE THREAD

**Issue by xby1003** [XX-net/XX-Net#12367]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
> 每次更新

更新神马？如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by xby1003** [comment]
可用ipv6掉到10以下！修复选项：“启用”，“更换teredo服务器”都试过了，还是连接不上！有哪位大神帮我看下，如何解决，

**Comment by AnyWAT** [comment]
👍https://github.com/XX-net/XX-Net/issues/12367#issuecomment-473256463

**Comment by xby1003** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 3
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 1036
连接池(帮助) | 新:0 h1:0 h2:2
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 50

类型                    : enterpriseclient
服务器名称              : 217.17.192.217
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 1189
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
>> 每次更新

> 更新神马？

难道就是

> 修复选项：“启用”，“更换teredo服务器”都试过了，

关闭了某开关？网络属性内取消了勾选 IPv6 协议？
#12043 [隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。

**Comment by xby1003** [comment]
大神们；上面是哪里出了问题还有办法解决吗？

**Comment by xby1003** [comment]
IPv6 协议已取消了勾选，关闭了某开关？不知道大神说的什么开关

**Comment by AnyWAT** [comment]
> 关闭了某开关？不知道大神说的什么开关

既如此，貌似没关。温故而知新 #12043

**Comment by AnyWAT** [comment]
> 大神们；上面是哪里出了问题还有办法解决吗？

 #12043 
![image](https://user-images.githubusercontent.com/37962734/54431205-bde75e00-4760-11e9-9cc0-f5d7271e5b2b.png)

**Comment by xby1003** [comment]
谢谢耐心回答问题，你说的#12034我都走过，按你说的我去关闭那个开关再试试， 再次谢谢

**Comment by xby1003** [comment]
发现一个问题，我已经更换了服务器， netsh int ipv6 show teredo后系统显示服务器名称为217.17.192.217 ，而控制页还是显示默认服务器win10.ipv6.microsoft.com，这又是那里的问题
服务器名称 : 217.17.192.217 ，
 best server is: win10.ipv6.microsoft.com

**Comment by AnyWAT** [comment]
> 控制页还是显示默认服务器

那只是推荐，千万别用。👍或（命令行）更换隧道服务器。。。

**Comment by AnyWAT** [comment]
> 这又是那里的问题

https://github.com/XX-net/XX-Net/issues/12043#issuecomment-455761696 
![image](https://user-images.githubusercontent.com/37962734/54433303-7cf24800-4766-11e9-96d6-a186a0010dc0.png)
