### ISSUE TITLE
xx-net什么时候能弄好啊?暂时只能用无界浏览了.

### ISSUE THREAD

**Issue by 53195391** [XX-net/XX-Net#12379]
无界最近疯了吗?直接可以搞到最大带宽了,刚才用idm下载了一个综艺节目,10m/s,简直了.

**Comment by AnyWAT** [comment]
选对了服务器，隧道一直正常呢

**Comment by starifly** [comment]
> 选对了服务器，隧道一直正常呢。#12378
> 贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

辛苦了

**Comment by xiaoxiongqianli** [comment]
Microsoft Windows [版本 10.0.17134.1]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 172.18.2.26:52767
外部 NAT 映射    : 120.202.26.175:52767
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:97 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by loy20002000** [comment]
@53195391

无界的带宽提升确实很变态，美中不足的是不够稳定。

**Comment by BGLongLong** [comment]
可以传下无界浏览给我吗 谢谢
