### ISSUE TITLE
有关隧道客户端类型 : teredo host-specific relay

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#12378]
意外发现：开始是禁用原生 IPv6的正常隧道，有效 IP数/总 IP数之比=1，勾选网络属性内的 IPv6协议，在原生 IPv6连接上后，隧道就由 teredo client  变成了该种客户端类型，有效 IP数及连接池直线下降到接近0，IP延迟到9999。反之，取消勾选网络属性内的 IPv6协议以禁用原生，隧道变成 teredo client ，手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，恢复 。。。有效 IP数/总 IP数之比=1

原来网络已支持原生 IPv6，隧道原生只能二选一。[如已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。]( ) #12043

**Comment by zhiganghan** [comment]
> 意外发现：开始是禁用原生 IPv6的正常隧道，有效 IP数/总 IP数之比=1，勾选网络属性内的 IPv6协议，在原生 IPv6连接上后，隧道就由 teredo client 变成了该种客户端类型，有效 IP数及连接池直线下降到接近0，IP延迟到9999。反之，取消勾选网络属性内的 IPv6协议以禁用原生，隧道变成 teredo client ，手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，恢复 。。。有效 IP数/总 IP数之比=1
> 
> 原来网络已支持原生 IPv6，隧道原生只能二选一。如已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。 #12043

技术小白。看不懂，哈哈哈

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12349#issuecomment-471273214
https://github.com/XX-net/XX-Net/issues/12237#issue-411026130
https://github.com/XX-net/XX-Net/issues/12171#issuecomment-457832830
https://github.com/XX-net/XX-Net/issues/12116#issuecomment-455766093
https://github.com/XX-net/XX-Net/issues/12101#issuecomment-455181472

**Comment by AnyWAT** [comment]
> 技术小白。看不懂，哈哈哈

所以嘛，你如 https://github.com/XX-net/XX-Net/issues/12372#issuecomment-473517967

![image](https://user-images.githubusercontent.com/37962734/54485729-cce12400-48b8-11e9-974b-5dc76153830d.png)

**Comment by Josephzcy** [comment]
@AnyWAT  ,您好，本人是这方面的小白，请问如何在网络属性内必须取消勾选 IPV6协议以禁用原生？谢谢赐教！

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12399#issuecomment-478028742
