### ISSUE TITLE
怎么手动修改teredo隧道服务器的地址？

### ISSUE THREAD

**Issue by HotView** [XX-net/XX-Net#12373]
自己手动试了几个teredo服务器，觉得速度可以，可以用。就想着把自己测试的服务器的地址写到配置文件中，我想手动将脚本里的默认的teredo服务器地址修改了，应该在哪个文件里操作啊？

**Comment by HotView** [comment]
我想问的是，如何在配置文件中，设置修改teeredo

**Comment by Tim-Xue** [comment]
你好，可以分享一下你测的teredo地址吗？

**Comment by Alobe007** [comment]
手动改完一直有效

**Comment by HotView** [comment]
> 手动改完一直有效

但是每次开机重启或者重启xx-net之后，又变为原来默认的teredo服务器了......

**Comment by AnyWAT** [comment]
> 但是每次开机重启或者重启xx-net之后，又变为原来默认的teredo服务器了......

系统内国产软件的保护？管理员命令行超简单：netsh int ipv6 set teredo enterpriseclient x.x.x.x
Win10：netsh int ipv6 set teredo natawareclient x.x.x.x

**Comment by AnyWAT** [comment]
> 你好，可以分享一下你测的teredo地址吗？

怕见光死😜

**Comment by HotView** [comment]
> > 你好，可以分享一下你测的teredo地址吗？
> 
> 怕见光死😜

teredo服务器修改之后，是不是关机重启什么的都不会改变呢？

**Comment by AnyWAT** [comment]
> teredo服务器修改之后，是不是关机重启什么的都不会改变呢？

正常情况下的确是如此哟
