### ISSUE TITLE
仅ipv6不能用 ipv6 fail not enough ip time out  

### ISSUE THREAD

**Issue by xiaoxiongqianli** [XX-net/XX-Net#12371]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xiaoxiongqianli** [comment]
Microsoft Windows [版本 10.0.17134.1]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\36092> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 172.18.5.61:57971
外部 NAT 映射    : 120.202.26.175:57971
长这样

**Comment by xiaoxiongqianli** [comment]
那个状态里这样
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！
> gws-ip-num: total:100 ipv4:0 ipv6:0
> worker: h1:0 h2:0

#12043 [隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。

**Comment by AnyWAT** [comment]
自己没耐心，还另起炉灶了，参考：AnyWAT不要回答 "仅 IPv6" 不可用，请检查， 我想寻求一个可靠的解决方法 #12050

![image](https://user-images.githubusercontent.com/37962734/54260685-951a6980-45a4-11e9-9afb-b461f279973e.png)

**Comment by xiaoxiongqianli** [comment]
???不是没耐心 我试了 还是不行呀

**Comment by AnyWAT** [comment]
> ???不是没耐心 我试了 还是不行呀

如仅说 157.56.106.184，“还是不行呀”是对的，因为：
已时过境迁。。。
![image](https://user-images.githubusercontent.com/37962734/54474760-e2f0d500-4823-11e9-9af6-95b408e1ec31.png)

但“又另起炉灶了”的事实说明。。。
难道就没有剩余一个。。。

**Comment by zhiganghan** [comment]
> 如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

X-TUNNEL能用。奇怪。为啥XX-NET不能用，什么问题？

**Comment by AnyWAT** [comment]
> X-TUNNEL能用。奇怪。为啥XX-NET不能用，什么问题？

选对服务器，隧道一直正常呢

**Comment by ZZJJZZKPI** [comment]
C:\Users\User> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : win1807.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

**Comment by ZZJJZZKPI** [comment]
我是这个情况喔。。一直没搞懂。。换了挺多服务器也不行

**Comment by ZZJJZZKPI** [comment]
@AnyWAT 大哥

**Comment by AnyWAT** [comment]
> 换了挺多服务器也不行

试试：217.17.192.217、195.140.195.140、83.170.6.76

**Comment by ZZJJZZKPI** [comment]
@AnyWAT 可以了，谢谢
