### ISSUE TITLE
XX-Net-3.13.1

### ISSUE THREAD

**Issue by lxf123a** [XX-net/XX-Net#12389]
XX-Net Status:

sys-platform: x86_64, Darwin-18.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
os-release: 18.2.0
os-detail: Release:10.14.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
参考：https://github.com/XX-net/XX-Net/issues/12387#issuecomment-474209360
