### ISSUE TITLE
百度网盘如何使用XX-NET代理

### ISSUE THREAD

**Issue by kankan666** [XX-net/XX-Net#12381]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
用的是校园网的纯ipv6内网

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/54489187-c4064780-48e4-11e9-8726-6c7087994129.png)
![image](https://user-images.githubusercontent.com/37962734/54489196-da140800-48e4-11e9-8458-602e8e30a3c5.png)
![image](https://user-images.githubusercontent.com/37962734/54489211-f9129a00-48e4-11e9-89d7-fef3f511e835.png)

以上，XX-Net 应取消全局代理
及“使用 IE代理”，此时XX-Net 应启用全局代理
设置貌似如此，不过都没用过，自己试试。。。

**Comment by AnyWAT** [comment]
迅雷 #12382 也是类似问题？如迅雷有代理设置，设置如上。如迅雷没有“使用 IE代理”或类似项，同样XX-Net 可启用全局代理。
