### ISSUE TITLE
刚开始一段时间能用，过一段时间证书错误

### ISSUE THREAD

**Issue by w786594** [XX-net/XX-Net#12386]
用的最新版本，每次都是刚开始一段时间能用，过一段时间证书错误，退出，重新启动xxnet又好了

**Comment by AnyWAT** [comment]
如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by w786594** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.50.87:53413
外部 NAT 映射    : 223.89.152.250:62715

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:99 ipv4:0 ipv6:99
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:0 h2:19
scan-ip-thread-num: 83
ip-quality: 353
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by w786594** [comment]
求大神指教一下，谢谢

**Comment by AnyWAT** [comment]
本地映射 : -----
外部 NAT 映射 : -----隐私！

#12043 试试其它服务器（IP）：217.17.192.217、195.140.195.140（在用）
