### ISSUE TITLE
求大神帮忙 ipv6 fail not enough ip 

### ISSUE THREAD

**Issue by xiaoxiongqianli** [XX-net/XX-Net#12385]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by nly4lov** [comment]
not enough ip是病句啊

**Comment by gmctl** [comment]
我的隧道都是通的；也尝试过换隧道，目前换的这个
```
C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant
```

##  XX-net 诊断状态
```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
收不到IP是哪个环节出了问题。。 xtunnel - httpproxy - gae 哪个环节没收到ip呢

**Comment by gmctl** [comment]
> 
> 
> 我的隧道都是通的；也尝试过换隧道，目前换的这个
> 
> ```
> C:\Windows\system32>netsh int ipv6 show teredo
> Teredo 参数
> ---------------------------------------------
> 类型                    : enterpriseclient
> 服务器名称              : teredo.remlab.net.
> 客户端刷新间隔          : 30 秒
> 客户端端口                : unspecified
> 状态                    : dormant
> ```
> 
> ## XX-net 诊断状态
> 
> ```
> XX-Net Status:
> 
> sys-platform: AMD64, Windows-10-10.0.16299
> os-system: Windows
> os-version: 10.0.16299
> os-release: 10
> os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
> architecture: 32bit,WindowsPE
> browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
> xxnet-version: 3.13.1
> python-version: 2.7.13
> openssl-version: 16.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: force_ipv6
> gws-ip-num: total:0 ipv4:0 ipv6:0
> ipv4-status: OK
> ipv6-status: OK
> connected-link: new:0
> worker: h1:0 h2:0
> scan-ip-thread-num: 10
> ip-quality: 9999
> is-idle: 0
> proxy_state: Fail
> ca_state: Fail
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false
> ```
> 
> 收不到IP是哪个环节出了问题。。 xtunnel - httpproxy - gae 哪个环节没收到ip呢


- [解决方案](https://github.com/XX-net/XX-Net/issues/8709)
我的这种情况是本地电信网络开启的ipv6和隧道通信通途，所以关闭本地的ipv6就行了。

**Comment by AnyWAT** [comment]
Teredo 隧道：#12455 或原生：#12477
