### ISSUE TITLE
ip6已启动，但状态处一直显示失败

### ISSUE THREAD

**Issue by wl520a** [XX-net/XX-Net#12380]
看了问题没找到解决方案，启动了隧道是绿色的，但IPv6 状态一直是失败的。

![image](https://user-images.githubusercontent.com/4980453/54486019-53980000-48bd-11e9-8460-93d1a3f41e29.png)

XX-Net Status:

sys-platform: x86_64, Darwin-18.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
os-release: 18.2.0
os-detail: Release:10.14.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.12.11
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:98
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 381
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> 启动了隧道，但ip6状态一直是失败的。

即使隧道已连接，ip6 状态 fail （连接池已归零）的症结仍在隧道：能连接但扫描不出 IP的陷阱。
参考 #12043 试试改用服务器 IP 或更换其它服务器

> scan-ip-thread-num: 1

貌似某开关的默认值症状，据Windows 经验，关闭它后性能会有提升：随时[有效 IP数/总 IP数之比值=1]( )。。。

**Comment by wl520a** [comment]
> > 启动了隧道是绿色的，但IPv6 状态一直是失败的。
> 
> 即使隧道已连接，ip6 状态 fail （连接池已归零）的症结仍在隧道：能连接但扫描不出 IP的陷阱。
> 参考 #12043 试试改用服务器 IP 或更换其它服务器
> 
> > scan-ip-thread-num: 1
> 
> 貌似某开关的软件默认值症状，据Windows 经验，关闭它后性能会有提升：随时有效 IP数/总 IP数之比值=1。。。

试了下更换其它服务器还是不行，不知是不是在这个局域网内被防火墙封了，等回去再试下

**Comment by AnyWAT** [comment]
> 试了下更换其它服务器还是不行

貌似巨硬已没有1个可用，也许只有 83.170.6.76、195.140.195.140、217.17.192.217 了

**Comment by wl520a** [comment]
嗯 现在免费的确实不稳定，还是给钱才靠谱

**Comment by AnyWAT** [comment]
> 不稳定

随时[有效 IP数/总 IP数之比值=1]( ) 才能有较佳体验

![image](https://user-images.githubusercontent.com/37962734/54573932-413ad500-4a29-11e9-8e8b-c61d4cc5145b.png)

**Comment by AnyWAT** [comment]
> 确实不稳定

参考：#12455
