### ISSUE TITLE
如何更换我的Teredo隧道

### ISSUE THREAD

**Issue by 2579019321** [XX-net/XX-Net#12388]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
如是Windows，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by ksit1110** [comment]
http://bbs.pcbeta.com/viewthread-1580771-1-1.html

参考下

**Comment by AnyWAT** [comment]
#12043 关闭某开关、禁用原生 IPv6，试试其它服务器（IP）：217.17.192.217、195.140.195.140（在用）、83.170.6.76

**Comment by hzq21** [comment]
以前在xx-net web端可以换，更新到最新提示路径错误，只能手动换

**Comment by Eri5Ch** [comment]
可以参考[wiki](https://github.com/XX-net/XX-Net/wiki/IPV6-Win7) 啊
