### ISSUE TITLE
x-tunnel 无法正常使用

### ISSUE THREAD

**Issue by xiaohuobanhahaha** [XX-net/XX-Net#12394]
XX-Net Status:

sys-platform: x86_64, Darwin-17.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
os-release: 17.2.0
os-detail: Release:10.13.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![Uploading 屏幕快照 2019-03-20 21.17.11.png…]()

![Uploading 屏幕快照 2019-03-20 21.17.45.png…]()

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12393#issuecomment-474675344

**Comment by xiaohuobanhahaha** [comment]
按照链接试了。miredo 面板是灰色的灯
Ipv6 状态能开启，使用x-tunnel 打开网页，
超过5分钟，Ip数量急剧减少，然后就扫描不到Ip地址了

XX-Net Status:

sys-platform: x86_64, Darwin-17.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
os-release: 17.2.0
os-detail: Release:10.13.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:91
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:38
scan-ip-thread-num: 8
ip-quality: 477
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
超过5分钟，Ip数量急剧减少，然后就扫描不到Ip地址了——网络属性内取消勾选 IPv6 协议
ipv6-status: OK 但 miredo 面板是灰色的灯（貌似隧道未连接？），矛盾？用的哪个服务器？
scan-ip-thread-num: 8 太小，并关闭某开关！#12043
proxy_state: Fail
ca_state: Fail 即使 X-Tunnel 代理，检测证书的 *.deja.com 也得走 GAE
以上均Windows 经验

![image](https://user-images.githubusercontent.com/37962734/54702238-73574e80-4b71-11e9-987d-7b2d798ff671.png)

（SS SSR的协议、端口与X-Tunnel 一致，即完全相当）

**Comment by xiaohuobanhahaha** [comment]
改了scanip的线程数，
加了deja.com的证书规则，设置为gaeproxy
服务器用的：teredo.remlab.net.
现在chrome状态是打不开google，但是数据还在跑..

XX-Net Status:

sys-platform: x86_64, Darwin-17.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
os-release: 17.2.0
os-detail: Release:10.13.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:27
scan-ip-thread-num: 1
ip-quality: 410
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 1 ——某开关打开的特征！[关闭“自动调整扫描线程数”！]( )
ipv6-status: OK， miredo 面板是？色的灯

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/54704181-3a20dd80-4b75-11e9-8c27-dcf817c127c4.png)

**Comment by xiaohuobanhahaha** [comment]
![屏幕快照 2019-03-21 01 08 19](https://user-images.githubusercontent.com/20666294/54704596-00040b80-4b76-11e9-978c-7695d2b5fe27.png)

![屏幕快照 2019-03-21 01 09 50](https://user-images.githubusercontent.com/20666294/54704620-0e522780-4b76-11e9-8520-66ba7a0e164a.png)

目前就这个 状态了。。

**Comment by AnyWAT** [comment]
服务器用的：teredo.remlab.net. 要用它，或改用其 IP，或用其它。。。

> gaeproxy可以挂appid用起来。x-tunnel模式打不开网页。

GAE正常，x-tunnel 才正常

**Comment by xiaohuobanhahaha** [comment]
![屏幕快照 2019-03-21 01 26 11](https://user-images.githubusercontent.com/20666294/54705745-7a358f80-4b78-11e9-8d5f-f184053b5c3d.png)
![屏幕快照 2019-03-21 01 25 53](https://user-images.githubusercontent.com/20666294/54705756-7c97e980-4b78-11e9-911b-52aa696a07d8.png)

**Comment by AnyWAT** [comment]
Windows 系统，貌似 natawareclient 好过 enterpriseclient 好过 client
![image](https://user-images.githubusercontent.com/37962734/54705755-7c97e980-4b78-11e9-949c-86526c46a828.png)

**Comment by AnyWAT** [comment]
更换服务器后，随即手动检查 IP（原来的 good IP 不再 good）

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11994#issuecomment-451713384 附上截图，如图显示miredo是绿灯，但IPV6就是连不上……服务器陷阱：隧道能连接，但 IPV6就是连不上，或能连但又扫描不到 IP

**Comment by AnyWAT** [comment]
miredo 面板是灰色的灯，即隧道未连接？但 ipv6-status: OK，怀疑是在使用原生 IPv6而不是隧道？
Windows 隧道原生只能二选一，用此禁彼。。。
