### ISSUE TITLE
ipv6不稳定，一会Ok一会fail

### ISSUE THREAD

**Issue by RedZhu1900** [XX-net/XX-Net#12393]
昨天还挺好的，今天重启mac后，ipv6就不正常了，一会ok(ok的时候也无法访问google)，一会fail
Miredo也是正常的，亮绿灯，switchyOmega模式为GAE-Proxy

XX-Net Status:

sys-platform: x86_64, Darwin-18.2.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
os-release: 18.2.0
os-detail: Release:10.14.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:3
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 10
ip-quality: 1000
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
某些服务器陷阱：能连接但扫描不出 IP。。。参考 #12043 试试：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76

**Comment by zhgna08** [comment]
217.17.192.217昨天好用，今天又扫不出有效ip了。

**Comment by AnyWAT** [comment]
> 昨天好用，今天又扫不出有效ip了。

不会吧？昨天能否做到：[有效 IP数/总 IP数=1]( ) ？
