### ISSUE TITLE
捣鼓了好久XX-Net还是不行找了个vpn挺好用的推荐给大家

### ISSUE THREAD

**Issue by linyilian1** [XX-net/XX-Net#12390]
注册送10G流浪，每天签到还会额外赠送流量，看youtube1080P完全没问题。
https://web2019.okss.xyz/#/auth/register?code=sUDc

**Comment by loy20002000** [comment]
又见广告帝。

WindScribe、无界、SetupVPN，这些都是免费的。实测可以达到2M字节/s以上。给我一个付费用不稳定VPN的理由先。

**Comment by linyilian1** [comment]
这个也不用钱，分享连接给别人注册会返现，而且我用着真的比你那些所谓免费的速度稳定多了。

**Comment by loy20002000** [comment]
@linyilian1

Windscribe是上Google首页推荐的VPN。

无界是与中共对抗超过15年的VPN，在这里有网友提供信息带宽最高可以到10M字节/s，我自己测试可以到45M比特/s。最慢也有100K字节/s。

SetupVPN是chrome商城唯一0差评免费VPN，已经运营三年多了。由于有新加坡这样的节点，访问YouTube都是读取新加坡本地镜像，1080P无压力（晚8：00——11：00除外）。

群众的眼睛是雪亮的，至少在免费服务这个方面。

**Comment by apaperumbrella** [comment]
> @linyilian1
> 
> Windscribe是上Google首页推荐的VPN。
> 
> 无界是与中共对抗超过15年的VPN，在这里有网友提供信息带宽最高可以到10M字节/s，我自己测试可以到45M比特/s。最慢也有100K字节/s。
> 
> SetupVPN是chrome商城唯一0差评免费VPN，已经运营三年多了。由于有新加坡这样的节点，访问YouTube都是读取新加坡本地镜像，1080P无压力（晚8：00——11：00除外）。
> 
> 群众的眼睛是雪亮的，至少在免费服务这个方面。

这些插件果然好用，谢谢大侠！

**Comment by lsq726** [comment]
谢谢分享，，已经厌倦了不稳定的翻墙。。现在用付费ssr

还是感谢xxnet和goagent
陪伴了这么多年。。谢谢。

**Comment by AnyWAT** [comment]
> 不稳定的翻墙

![image](https://user-images.githubusercontent.com/37962734/54861875-9bf76800-4d6c-11e9-8c0c-a09a0e2e8beb.png)

**Comment by vc321** [comment]
> 这个也不用钱，分享连接给别人注册会返现，而且我用着真的比你那些所谓免费的速度稳定多了。

您好，新的okss链接有吗，可以贴回复里，谢谢！~

**Comment by Riel1998** [comment]
老品牌速鹰666旗下的优质站, 比速鹰的节点快不少 ,主要还平价:https://jikebb.xyz/auth/register?code=EEOO

**Comment by shikukuya** [comment]
> > 这个也不用钱，分享连接给别人注册会返现，而且我用着真的比你那些所谓免费的速度稳定多了。
> 
> 您好，新的okss链接有吗，可以贴回复里，谢谢！~

https://okss.us/index.php/#/register?code=sUDc
