### ISSUE TITLE
Not Exist appids

### ISSUE THREAD

**Issue by nsdcsj** [XX-net/XX-Net#124]
A batch of appids were used, but in the status page, it was found many appids appear to be 'Not exist appids'. How to get this fixed?

**Comment by xxnet** [comment]
You need deploy the appids to GAE

First, clean the appids from setting page.
Then goto the deploy page, do the deploy.
After deploy success, set the appids to goagent again.



2015-04-11 2:06 GMT-04:00 nsdcsj <notifications@github.com>:

**Comment by nsdcsj** [comment]
i tried to deply appids, but there is no log come out in the page
![qq 20150411142624](https://cloud.githubusercontent.com/assets/11896645/7100487/c79b43fa-e056-11e4-999e-fed46415e330.png)

**Comment by xxnet** [comment]
状态页和日志也有显示信息吗？
如果没有，请试试：
https://github.com/XX-net/XX-Net/wiki/How-to-get-start-error-log

把启动日志发出来分析

2015-04-11 2:26 GMT-04:00 nsdcsj <notifications@github.com>:

**Comment by xxnet** [comment]
参考这个问题：
https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=dqujp3h61mgd&search=inbox&th=14c9d3d8fd511f31&cvid=30

2015-04-11 2:46 GMT-04:00 Net XX <xxnet.dev@gmail.com>:

**Comment by nsdcsj** [comment]
状态页见截图。问题系统是64位，不是32位唉。
![qq 20150411145421](https://cloud.githubusercontent.com/assets/11896645/7100534/ad0a1f62-e05a-11e4-950e-8756854f2260.png)
另外，日志太多，怎么导出？

**Comment by xxnet** [comment]
状态页有信息，说明GoAgent工作正常，可以直接看GoAgent日志页，不必通过CMD启动。

你先下载最新的1.8.3版本，然后在部署失败时把日志页面内容拷贝放上来分析

在 2015年4月11日 上午2:55，nsdcsj <notifications@github.com>写道：
