### ISSUE TITLE
谁能简单粗暴的告诉我这样怎么办 小白一个。。。。

### ISSUE THREAD

**Issue by zhangbin0922** [XX-net/XX-Net#12408]
一直是等待扫描 让我开启ipv6
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by zhangbin0922** [comment]
> 如用隧道，贴cmd内运行netsh int ipv6 show teredo的结果（无需IP地址的2行）

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant


C:\Users\Administrator>

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com.——（隧道即使能连接但 IPv6 状态Fail，即或OK也扫描不出 IP的）服务器陷阱！
状态 : dormant ——休眠，未连接
使用隧道，需网络属性内取消勾选 IPv6协议以禁用原生
#12043 命令行更换服务器：217.17.192.217、195.140.195.140、83.170.6.76

**Comment by zhangbin0922** [comment]
> 217.17.192.217,195.140.195.140,83.170.6.76

禁用了ipv6之后怎么具体操作啊。。。

**Comment by AnyWAT** [comment]
> 禁用了ipv6之后怎么具体操作啊。。。

高抬贵鼠👉 #12043 命令行更换服务器：217.17.192.217、195.140.195.140、83.170.6.76

**Comment by zhangbin0922** [comment]
> 服务器名称：win1711.ipv6.microsoft.com .--（隧道即使能连接但IPv6状态失败，即或OK也扫描不出IP的）服务器陷阱！
> 状态：休眠 - 休眠，未连接
> 使用隧道，需网络属性内取消勾选的IPv6的协议以禁用原生
> [＃](https://github.com/XX-net/XX-Net/issues/12043) 12043 命令行更换服务器：217.17.192.217,195.140.195.140,83.170.6.76

弄好了 感谢

**Comment by zhangbin0922** [comment]
> 8

连上不一会就又不好使了。。。。

**Comment by AnyWAT** [comment]
> 连上不一会就又不好使了。。。。

#12043 速度及稳定性较佳体验之秘籍（忽略巨硬。。。）
![image](https://user-images.githubusercontent.com/37962734/54900691-368fac80-4f0f-11e9-98e8-0b7a622dd8d5.png)

**Comment by AnyWAT** [comment]
如隧道已连接，use-ipv6: force_ipv6——改为自动
导入 IP4 #11775
导入 IP6 https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138
