### ISSUE TITLE
Gmail登陆不了，显示重定向

### ISSUE THREAD

**Issue by StephenAnboer** [XX-net/XX-Net#12406]
使用的xx-net 3.13.1，登录gmail的时候显示：

该网页无法正常运作 mail.google.com 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS

我看之前有人问这个问题，都是让升级最新版本试试，但是我已经在用最新版本了，不知道有没有什么解决办法

**Comment by AnyWAT** [comment]
GAE代理可以呢。或许 IP延迟较大而代理速度不佳？

**Comment by StephenAnboer** [comment]
不会用dnscyrypt-proxy，只是用默认的gae代理，清理了一下cookies，可以用了，但是过了一会儿就又不行了，还是显示 将您重定向的次数过多 。。

**Comment by AnyWAT** [comment]
> 不会用dnscyrypt-proxy

解压即用 https://github.com/CNMan/dnscrypt-proxy-config

**Comment by AnyWAT** [comment]
> 过了一会儿就又不行了，还是显示 将您重定向的次数过多 。。

#12043 可从 XX-Net 好坏3表征观察效果：有效 IP数/总 IP数之比值、IP 延迟、连接池。
![image](https://user-images.githubusercontent.com/37962734/54881267-33ea7400-4e89-11e9-97c6-ba1fdd929f9d.png)

**Comment by liamhui** [comment]
XX-Net Version | 3.15.9
-- | --

目前也遇到这个问题，GMAIL也是登录不了，

**Comment by xxnet** [comment]
实施先切换到x-tunnel登录，再切换回来
