### ISSUE TITLE
感谢xxnet，感谢goagent

### ISSUE THREAD

**Issue by lsq726** [XX-net/XX-Net#12402]
陪伴了我这么多年。。

其实我只是习惯用gg。仅此而已。。

什么时候不再需要翻墙。中国就有希望了。

现在已经用付费ssr。。

希望有一天我们不再需要翻墙。。谢谢。

**Comment by AnyWAT** [comment]
#12043 https://github.com/XX-net/XX-Net/issues/12390#issuecomment-475840069

**Comment by xpf7622** [comment]
以前xx非常好用，现在基本用不了了。难道是支持IPV6的路由器不成？

**Comment by hdrafyy** [comment]
的确好用！

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12399#issuecomment-475521767 原生昙花一现，隧道远优于原生。。。

**Comment by ezhyg** [comment]
谢谢开发者，用了很长一段时间，谢谢你们！

**Comment by hujunyao** [comment]
最近xxnet 好用了

**Comment by zhangbin0922** [comment]
> 最近的xxnet好用了
有效IPv6 IP数一直贼低 怎么破

**Comment by AnyWAT** [comment]
> 最近的xxnet好用了
> 有效IPv6 IP数一直贼低 怎么破

https://github.com/XX-net/XX-Net/issues/12408#issuecomment-476078266 还不能破，简单粗暴：删除弃用🤣
