### ISSUE TITLE
更换IPV6服务器，后依然不可用，求推荐新的Ipv6服务器

### ISSUE THREAD

**Issue by JhonZRoger** [XX-net/XX-Net#12409]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:3
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 895
is-idle: 0
proxy_state: 

ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by JhonZRoger** [comment]
![Uploading 捕获.PNG…]()

**Comment by AnyWAT** [comment]
图片链接被指向本贴，纯文本即可。

**Comment by AnyWAT** [comment]
担心（隧道即使能连接但 IPv6 状态Fail，即或OK也扫描不出 IP的）服务器陷阱！
使用隧道，需网络属性内取消勾选 IPv6协议以禁用原生
#12043 命令行更换服务器：217.17.192.217、195.140.195.140、83.170.6.76

**Comment by JhonZRoger** [comment]
![捕获](https://user-images.githubusercontent.com/38027976/54898339-d432ae00-4f06-11e9-83af-1482916e8ad8.PNG)

**Comment by AnyWAT** [comment]
> 更换IPV6服务器，后依然不可用，求推荐新的Ipv6服务器

已给出：
> #12043 命令行更换服务器：217.17.192.217、195.140.195.140、83.170.6.76

#12043 [隧道显示正常但连接池或有效 IP数归零时：]( )或手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
