### ISSUE TITLE
"仅 IPv6" 不可用

### ISSUE THREAD

**Issue by nickzhuang0613** [XX-net/XX-Net#12412]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
重复：一直显示等待扫描IP，建议开启IPV6 #12413

**Comment by bojowa** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true


这是啥情况，显示仅ipv6不可用

**Comment by AnyWAT** [comment]
如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by bojowa** [comment]
> 如用隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 192.168.0.157:55254
外部 NAT 映射    : 39.78.100.210:55254

**Comment by AnyWAT** [comment]
> 服务器名称 : win1711.ipv6.microsoft.com.

#12043 （隧道已连接但扫描不出 IP的）服务器陷阱！

> 本地映射 : ----
> 外部 NAT 映射 : -----

（无需 IP地址的2行）隐私！

**Comment by bojowa** [comment]
> > 服务器名称 : win1711.ipv6.microsoft.com.
> 
> #12043 （隧道已连接但扫描不出 IP的）服务器陷阱！命令行更换服务器。。。
> 
> > 本地映射 : ----
> > 外部 NAT 映射 : -----
> 
> （无需 IP地址的2行）隐私！

如何更换？更换到哪个？win10.ipv6.microsoft.com看起来不错

**Comment by AnyWAT** [comment]
> 如何更换？更换到哪个？win10.ipv6.microsoft.com看起来不错

#12043 命令行更换服务器，貌似巨硬服务器全部已残，唯有
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76

**Comment by bojowa** [comment]
隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:d911:c0d9:1464:337c:d8b1:9b2d(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::1464:337c:d8b1:9b2d%11(首选)
   默认网关. . . . . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 184549376
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-23-51-CF-95-E8-6A-64-2F-00-5A
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

并


Your IPv4 address on the public Internet appears to be 39.78.100.210
--Tests using this web site are unreliable from your location.

**Comment by bojowa** [comment]
http://test-ipv6.com/

No IPv6 address detected [more info]
--

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启 IPv6以来，一直正常一直不用此玩意儿

**Comment by bojowa** [comment]
> #12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启 IPv6以来，一直正常一直不用此玩意儿
> 如（或不确定）已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。
> 
> ![image](https://user-images.githubusercontent.com/37962734/54982126-fa2e8000-4fe4-11e9-9071-c2c7b43bfcdd.png)
> 
> ![image](https://user-images.githubusercontent.com/37962734/54982067-d66b3a00-4fe4-11e9-8a17-8be7563d08e8.png)

已经ok了，XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。
多谢你，么么哒
