### ISSUE TITLE
很久连不上了，麻烦各位大佬看看

### ISSUE THREAD

**Issue by YAPIA** [XX-net/XX-Net#12410]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

类型                    : enterpriseclient (Group Policy)
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.0.100:56266
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com. ——（隧道能连接但 IPv6 状态Fail，即或OK也扫描不出 IP的）服务器陷阱！#12043

**Comment by yyuurrii34** [comment]
#12103
#12037
啥也不多说，自己看，关于teredo隧道我在#12103作了详细分析。

**Comment by hubsocks** [comment]
@yyuurrii34 用teredo隧道想稳定连接google ipv6这路子行不通.就算获取到ip.只要一ping或开优土泊都是丢包很严重.good_ip.txt里面的ip顺序总是频繁排序.换现teredo用处不大.用ipv4速度还是很完美的.
你说的XX-Net扫描功能.我个人认识它不支持扫描ipv6范围.很多人叫它扫描,其实它总是读取内置或good_ip.txt的ip.然后随机测试是否有效.并没有扫描功能.大量测试发现扫描线程设为2000(修改文件)与0,并没任何区别.如果设置ipv6扫描范围,扫描线程为1,XX-Net直接出错.
还有用ipv4时.还是会出错python27关闭的错误.只有机率很低.
