### ISSUE TITLE
每天过来看看大家发的求助帖

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#12415]
然后一股满足感油然而生
![140eb8389b504fc21183036fe5dde71191ef6d98](https://user-images.githubusercontent.com/11325411/54965715-bcae0080-4fac-11e9-9f32-9cb56e11efe2.gif)

**Comment by AnyWAT** [comment]
其实，点开某人的 ID就能看看TA的历史求助帖😜

**Comment by nly4lov** [comment]
> 其实，点开某人的 ID就能看到TA的历史求助帖了😜

哈哈哈哈
![216c500fd9f9d72aee85a377d42a2834359bbb93](https://user-images.githubusercontent.com/11325411/54978376-25ac6d00-4fdb-11e9-886b-44ba6e8ac10d.jpg)
