### ISSUE TITLE
两个月没用XX-NET了，请问现在还能用吗？

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12417]
过年的时候xx-net突然用不了了，然后就用了其他的翻墙方法。现在想知道xx-net恢复了吗？还是IPV6数量还是那么少吗？

**Comment by AnyWAT** [comment]
貌似自3.13.1发布以来，官方没有。。。
除了能用的服务器越来越少，XX-NET一直正常呢 #12043

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12412#issuecomment-476524649

**Comment by gLoCk27** [comment]
一直很稳定地不能用了。

**Comment by AnyWAT** [comment]
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by hujunyao** [comment]
手机热点共享 一直能用
光纤，最近一段时间似乎好用了

**Comment by cypcym** [comment]
一直可以用，一直不稳定

**Comment by AnyWAT** [comment]
> 一直可以用，一直不稳定

#12043 速度及稳定性较佳体验之秘籍（忽略有关巨硬。。。）

**Comment by hanwei2008** [comment]
ubuntu16.04:

1)sudo vim /etc/miredo/miredo.conf
2)replace the server with "teredo-debian.remlab.net"

good luck!

**Comment by tedchina** [comment]
> 2)replace the server with "teredo-debian.remlab.net"
证明可用，谢谢楼上。。。
