### ISSUE TITLE
X-TUNNEL账户无法登陆了

### ISSUE THREAD

**Issue by varicella** [XX-net/XX-Net#12419]
是不是服务器坏了？一直无法登陆

**Comment by AnyWAT** [comment]
一直登录正常。貌似楼主 http://127.0.0.1:8085/?module=x_tunnel&menu=status 没一个前端正常？
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by Sys-Myl** [comment]
同样情况，一直显示正在登录...，这两天晚上都这样，白天是可以的，什么原因？

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1807.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
服务器名称 : win1807.ipv6.microsoft.com.——服务器陷阱！#12043
状态 : dormant——休眠，未连接。
gws-ip-num: total:undefined ipv4:0 ipv6:0——
worker: h1:0 h2:0——
隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。
