### ISSUE TITLE
一直显示等待扫描IP，建议开启IPV6

### ISSUE THREAD

**Issue by nickzhuang0613** [XX-net/XX-Net#12413]
一直显示等待扫描IP，建议开启IPV6，但是我的IPV6是打开的

![图片](https://user-images.githubusercontent.com/45776568/54939957-bb58e580-4f64-11e9-8248-b788301d2672.png)

隧道状态
![图片](https://user-images.githubusercontent.com/45776568/54940187-315d4c80-4f65-11e9-8d9a-47212fcf64e2.png)

诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
有关隧道客户端类型 : teredo host-specific relay #12378
