### ISSUE TITLE
IPV6 总数为什么只能到100

### ISSUE THREAD

**Issue by zengxiaoliang** [XX-net/XX-Net#12422]
类型                    : enterpriseclient
服务器名称              : 195.140.195.140
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)

总数只能到100 延迟400+

**Comment by AnyWAT** [comment]
> 总数只能到100 延迟400+

软件默认设置100而已，自设置也不宜超250，延迟倒可以稍减小 #12043 速度及稳定性较佳体验之秘籍（忽略巨硬相关。。。）
