### ISSUE TITLE
重装LTSC之后能扫到IP 但有效IP上到二三十开始掉0 然后升回1-2 

### ISSUE THREAD

**Issue by burdenlee** [XX-net/XX-Net#12420]
[**_issue.txt_**](https://github.com/XX-net/XX-Net/files/3013796/issue.txt)
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:65 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 3424
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
[Uploading issue.txt…]()

[XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:65 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 3424
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
[Uploading issue.txt…]()

![213](https://user-images.githubusercontent.com/46627154/55087443-13b6f100-50e5-11e9-8eef-7af4cdecf009.jpg)

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (address)
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by xugaohui** [comment]
呼叫机器人

**Comment by burdenlee** [comment]
@AnyWAT

**Comment by AnyWAT** [comment]
#12043 关闭某开关，如（或不确定）已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。
隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
如服务器使用域名不理想，可试试使用其 IP。。。

**Comment by AnyWAT** [comment]
> 重装LTSC之后能扫到IP 但有效IP上到二三十开始掉0 然后升回1-2

貌似先是隧道有效，后来是原生在起作用？

**Comment by burdenlee** [comment]
> > 重装LTSC之后能扫到IP 但有效IP上到二三十开始掉0 然后升回1-2
> 
> 貌似先是隧道有效，后来是原生在起作用？

说出来你可能不信 原来是网卡驱动的问题 可能是LTSC自带的驱动不完全适配或者版本号太低 反正更新显卡的驱动之后就可以翻墙了

**Comment by AnyWAT** [comment]
楼主有此问题么：https://www.ip.cn/ 测试本机的结果是 a.b.c.d，但命令行 netsh int ipv6 show teredo 的结果，外部 NAT 映射（ IP）：a.b.e.d，即有第三段数字不同 https://github.com/shadowsocks/shadowsocks-windows/issues/2230#issuecomment-477377371

**Comment by burdenlee** [comment]
> netsh int ipv6 show teredo

@AnyWAT  nooo 今天又不行了 看来跟驱动关系不大 现在情况仍然一样 你给的网址测试的地址跟Netsh命令行出来的地址是一样的a.b.c.d

**Comment by burdenlee** [comment]
> 楼主有此问题么：https://www.ip.cn/ 测试本机的结果是 a.b.c.d，但命令行 netsh int ipv6 show teredo 的结果，外部 NAT 映射（ IP）：a.b.e.d，即有第三段数字不同 [shadowsocks/shadowsocks-windows#2230 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2230#issuecomment-477377371)

尝试过 #10282 的脚本 仍然是总IP数不超过30 可用IP也30 然后掉到0

**Comment by burdenlee** [comment]
> > 楼主有此问题么：https://www.ip.cn/ 测试本机的结果是 a.b.c.d，但命令行 netsh int ipv6 show teredo 的结果，外部 NAT 映射（ IP）：a.b.e.d，即有第三段数字不同 [shadowsocks/shadowsocks-windows#2230 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2230#issuecomment-477377371)
> 
> 尝试过 #10282 的脚本更换过teredo的服务器地址为数字形式 仍然是总IP数不超过30 可用IP也30 然后掉到0

**Comment by burdenlee** [comment]
> 楼主有此问题么：https://www.ip.cn/ 测试本机的结果是 a.b.c.d，但命令行 netsh int ipv6 show teredo 的结果，外部 NAT 映射（ IP）：a.b.e.d，即有第三段数字不同 [shadowsocks/shadowsocks-windows#2230 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2230#issuecomment-477377371)

等待很久之后总IP跟可用又涨到54左右 但只要一尝试上youtube 就可用马上掉0

**Comment by AnyWAT** [comment]
#12043 关闭某开关、适当增大最大扫描线程数。
[关闭“自动调整扫描线程数”，最大扫描线程数以能自动维持：有效 IP数/总 IP数之比值=1 时为最小值]( )

![image](https://user-images.githubusercontent.com/37962734/55240593-2d3a7300-5274-11e9-8c51-7b3c230c3ce5.png)

**Comment by burdenlee** [comment]
> 楼主有此问题么：https://www.ip.cn/ 测试本机的结果是 a.b.c.d，但命令行 netsh int ipv6 show teredo 的结果，外部 NAT 映射（ IP）：a.b.e.d，即有第三段数字不同 [shadowsocks/shadowsocks-windows#2230 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2230#issuecomment-477377371)

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:1 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 60
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![QQ截图20190329224354](https://user-images.githubusercontent.com/46627154/55240732-886c6580-5274-11e9-865a-6cabce682570.jpg)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12420#issuecomment-477208136

**Comment by burdenlee** [comment]
> [#12420 (comment)](https://github.com/XX-net/XX-Net/issues/12420#issuecomment-477208136)

本来偷懒用的是电信光猫直接lan口接电脑 现在加了以前的路由器 xx-net又正常了

**Comment by AnyWAT** [comment]
电信光猫直接lan口接电脑+电脑网络属性内取消勾选 IPV6协议以禁用原生=以前（一般不支持 IPV6）的路由器接电脑

**Comment by burdenlee** [comment]
> 电信光猫直接lan口接电脑+电脑网络属性内取消勾选 IPV6协议以禁用原生=以前（一般不支持 IPV6）的路由器接电脑

![QQ截图20190330160151](https://user-images.githubusercontent.com/46627154/55273373-4808f800-5305-11e9-8f50-cf51f92e8955.jpg)

接了以前的路由器之后就变成restricted（port） 估计就是因为这个成功了。。

**Comment by AnyWAT** [comment]
> 接了以前的路由器之后就变成restricted（port）

貌似给说反了，光猫直连电脑才是如此，接了以前的路由器之后就变成 symmetric

**Comment by burdenlee** [comment]
> > 接了以前的路由器之后就变成restricted（port）
> 
> 貌似给说反了，光猫直连电脑才是如此，接了以前的路由器之后就变成 symmetric

呃 听说过四种NAT类型唯独就是restricted用不了teredo 本来symmetric也不行 但被哪个大佬搞到可以用了

**Comment by AnyWAT** [comment]
> 本来symmetric也不行

貌似一直 symmetric 的一直行

**Comment by burdenlee** [comment]
> > 本来symmetric也不行
> 
> 貌似一直 symmetric 的一直行（鄙人光猫电脑直连也如此）

我本来重装电脑前光猫直连也是symmertric 不知道为何重装后直连变成了restricted 现在加个路由器也行吧 能翻就好（还有想问问是不是每次退出xx-net后接下来每次都要重新更换teredo地址跟删除good_ip.txt里面的地址）

**Comment by AnyWAT** [comment]
不是
