### ISSUE TITLE
是不是需要购买X-TUNNEL了？XX-net没法用了

### ISSUE THREAD

**Issue by zhiganghan** [XX-net/XX-Net#12424]
如题

**Comment by burdenlee** [comment]
可以用 用不了是自己设置问题 为了省心买tunnel倒也不是不行 一般人哪有时间搞这搞那

**Comment by AnyWAT** [comment]
首先，X-Tunnel 共5个前端，貌似除了GAE前端（若干工作数）及Cloudflare 前端（仅1个工作数）正常，其它3个很长时间以来几乎从未正常过，一般（流量）使用总量9成以上通过GAE前端。如果“XX-net没法用了”即GAE前端失效，再Cloudflare 前端也失效的话，X-TUNNEL也会没法用的😥

**Comment by zhgna08** [comment]
X-TUNNEL这段时间还好，大部分时间可登可用，我是一直在买季度餐，虽然每次流量都用不了三分之一，但也算是对xx项目的支持吧。
