### ISSUE TITLE
大家好，我是ubuntu系统 。目前win7系统最新版本的xx-net可以正常连接，但是UBuntu  系统还是扫描不到ip,延迟1000多，请问关于此系统，针对xx-net的问题，有什么方法。目前已经试了禁用原生的方法和之前的初级解决方法和初级解决方案的指令，但是这些在ubuntu里面好像不对应，没有这样的指令，请教针对这两个方案，在ubuntu里面具体怎么操作。

### ISSUE THREAD

**Issue by Josephzcy** [XX-net/XX-Net#12425]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by FergonXie** [comment]
没安装miredo吧？ 或者说没启动miredo服务。 
或者缺少其它的依赖包， 除了wiki介绍的哪些，最好在终端观察一下sudo ./start 提示的erro信息，也会提示你安装缺少的依赖包。相对来说，ubuntu要麻烦一些，ferdora就简单。
