### ISSUE TITLE
呼吁大家去 996.ICU 点赞 https://github.com/996icu/996.ICU 

### ISSUE THREAD

**Issue by 253681319** [XX-net/XX-Net#12434]
https://github.com/996icu/996.ICU ，支持干翻一切不合法的行为！围观也是力量

**Comment by xu574329211** [comment]
https://github.com/996icu/996.ICU ，支持干翻一切不合法的行为！围观也是力量

**Comment by angal125511** [comment]
angal

**Comment by WweiaiI** [comment]
已star

**Comment by LeslieLamhub** [comment]
star

**Comment by MrYanZi** [comment]
企业的发展绝不是靠压榨员工的潜力来实现的，无论怎么掩饰，都改变不了其资本家的本质。如果企业想要长久的发展，优秀的企业文化才是留住人才的不二法门。。。。。。。
