### ISSUE TITLE
【已解决】可用的服务器（IP）仅剩。。。

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#12436]
😱貌似今天 teredo.trex.fi. 195.140.195.140 也连不上了，
teredo.iks-jena.de. 217.17.192.217 也是。
悲惨😭可用的服务器（IP）仅剩：
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76

**Comment by htpao2** [comment]
我这能用啊

**Comment by AnyWAT** [comment]
> 我这能用啊

已找到原因：与 dnscrypt-proxy 相关，以往一直 [cisco] DNS下3个隧道服务器正常，今天却有2个连不上了，重启了下 dnscrypt-proxy，自动改到了较快的 [cloudflare] DNS，此时那2个隧道服务器也能连上了😂
