### ISSUE TITLE
"仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by liule0228** [XX-net/XX-Net#12432]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 468
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by cuijianzhuang** [comment]
一样

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 1——默认打开某开关的特征，关闭它！#12043
worker: h1:0 h2:0——隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。

**Comment by gyfeng001** [comment]
如何修改服务器地址啊？

**Comment by AnyWAT** [comment]
> 如何修改服务器地址啊？

#12043

**Comment by hcw2175** [comment]
> scan-ip-thread-num: 1——默认打开某开关的特征，关闭它！#12043
> worker: h1:0 h2:0——隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
> 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。

感谢。`teredo.iks-jena.de`可用。

**Comment by liule0228** [comment]
> scan-ip-thread-num: 1——默认打开某开关的特征，关闭它！#12043
> worker: h1:0 h2:0——隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
> 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。



> scan-ip-thread-num: 1——默认打开某开关的特征，关闭它！#12043
> worker: h1:0 h2:0——隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
> 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。
离线（无法连接）

**Comment by liule0228** [comment]
> scan-ip-thread-num: 1——默认打开某开关的特征，关闭它！#12043
> worker: h1:0 h2:0——隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
> 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。

**Comment by AnyWAT** [comment]
> 离线（无法连接）

https://github.com/XX-net/XX-Net/issues/12043 隧道远优于原生。如（或不确定）已有原生 IPV6而用隧道，（电脑）网络属性内必须取消勾选 IPV6协议以禁用原生 。

**Comment by liule0228** [comment]
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.1.2:60166
外部 NAT 映射    : 120.193.204.36:44550


"仅 IPv6" 不可用，请检查。还是这个提示

**Comment by AnyWAT** [comment]
服务器名称 : win1711.ipv6.microsoft.com.——服务器陷阱！#12043

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12432#issuecomment-478351991 可用的服务器（IP）仅剩。。。 #12436
