### ISSUE TITLE
小白 很奇怪为什么一直没有有效ip 偶尔尝试连接上了也是延迟过千。。。

### ISSUE THREAD

**Issue by simcatSL** [XX-net/XX-Net#12439]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
#12043 关闭某开关，隧道远优于原生，如（或不确定）已有原生 IPV6而用隧道，（电脑）网络属性内必须取消勾选 IPV6协议以禁用原生。
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by sveinjoe** [comment]
关闭原生ipv6吧，使用teredo隧道来连是个好选择，大概是因为隧道加密了数据的原因，不那么容易被封包

**Comment by AnyWAT** [comment]
> 很奇怪为什么一直没有有效ip 偶尔尝试连接上了也是延迟过千

疑似效果？
![image](https://user-images.githubusercontent.com/37962734/55453974-a2a99900-5610-11e9-9add-1399f38bf368.png)

**Comment by AnyWAT** [comment]
楼上是用某脚本推荐的巨硬服务器（陷阱！），下图非巨硬，对比明显？
![image](https://user-images.githubusercontent.com/37962734/55454461-9aeaf400-5612-11e9-8560-4e82c52d2156.png)
