### ISSUE TITLE
ubuntu xxnet一直显示系统空闲，却一直连接不上国外网站

### ISSUE THREAD

**Issue by MrJCR** [XX-net/XX-Net#12431]
百度了好多，都没有答案，求指教
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by MrJCR** [comment]
XX-Net Status:

sys-platform: x86_64, Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
os-release: 4.15.0-47-generic
os-detail: Dist:Ubuntu; Version:18.04; ID:bionic
architecture: 64bit,
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
xxnet-version: 3.13.1
python-version: 2.7.15rc1
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:98 ipv4:0 ipv6:96
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 370
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by MrJCR** [comment]
求解

**Comment by AnyWAT** [comment]
scan-ip-thread-num: 1——默认打开某开关的特征，关闭它！#12043 
worker: h1:0 h2:0——隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。

**Comment by wa008** [comment]
+1，win10显示系统空闲（正常）。但无法访问国外网站

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:18
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 375
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


求解答

**Comment by MrJCR** [comment]
> +1，win10显示系统空闲（正常）。但无法访问国外网站
> 
> XX-Net Status:
> 
> sys-platform: AMD64, Windows-10-10.0.17763
> os-system: Windows
> os-version: 10.0.17763
> os-release: 10
> os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
> architecture: 32bit,WindowsPE
> browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
> xxnet-version: 3.13.1
> python-version: 2.7.13
> openssl-version: 16.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: force_ipv6
> gws-ip-num: total:100 ipv4:0 ipv6:18
> ipv4-status: OK
> ipv6-status: OK
> connected-link: new:0
> worker: h1:0 h2:0
> scan-ip-thread-num: 10
> ip-quality: 375
> is-idle: 1
> proxy_state: Fail
> ca_state: Fail
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false
> 
> 求解答
浏览器安装SwitchOmega插件，xxnet解压后里面有，但是我用不了，直接去github下载，然后打开SwitchOmega设置，导入文件(xxnet里面SwitchOmega的bak文件)，保存设置就好了

**Comment by AnyWAT** [comment]
> +1，win10显示系统空闲（正常）。但无法访问国外网站

如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by wa008** [comment]
> > +1，win10显示系统空闲（正常）。但无法访问国外网站
> 
> 如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

![E9)Y 20JLPTXQ%3Q2P35F~V](https://user-images.githubusercontent.com/29834520/55700332-753e6000-5a01-11e9-95c8-c781ec4af498.png)

**Comment by AnyWAT** [comment]
> scan-ip-thread-num: 10

适当增大扫描线程数，并关闭某开关：https://github.com/XX-net/XX-Net/issues/12455

> worker: h1:0 h2:0

https://github.com/XX-net/XX-Net/issues/12455 隧道显示正常但连接池或有效 IP数归零时。。。

如使用（服务器）域名不理想，可试试使用其 IP。。。
