### ISSUE TITLE
GAE状态信息以前就长期显示为"请检查代理服务器设置"，但是能用。最近一个多月尝试了#12403的方法，短期能用过，但是99%情况下用不了

### ISSUE THREAD

**Issue by maxflyer** [XX-net/XX-Net#12433]
请指导如何解决。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by maxflyer** [comment]
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76

这3个都试过，只有用83.170.6.76偶尔能连上

**Comment by maxflyer** [comment]
另外标题的表述可能有歧义，最近GAE的状态显示什么都有，不只是“请检查代理服务器设置”了

**Comment by AnyWAT** [comment]
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by maxflyer** [comment]
> 如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是


IP地址的两行是指最后两行吗

**Comment by AnyWAT** [comment]
> NAT : restricted (port)

貌似症结所在？
#12043 如（或不确定）已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。
或：光猫——（不支持 IPV6的）路由器——电脑

> 这3个都试过，只有用83.170.6.76偶尔能连上

![image](https://user-images.githubusercontent.com/37962734/55305704-18342e80-5484-11e9-846a-bc463dfba7e6.png)

**Comment by AnyWAT** [comment]
> gws-ip-num: total:100 ipv4:0 ipv6:0
> worker: h1:0 h2:0

隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。

**Comment by maxflyer** [comment]
> > NAT : restricted (port)
> 
> 貌似症结所在？[#12420 (comment)](https://github.com/XX-net/XX-Net/issues/12420#issuecomment-478218094) 电信光猫直接lan口接电脑+电脑网络属性内取消勾选 IPV6协议以禁用原生=以前（一般不支持 IPV6）的路由器接电脑
> #12043 如（或不确定）已有原生 IPV6而用隧道，网络属性内必须取消勾选 IPV6协议以禁用原生 。
> 或：光猫——（不支持 IPV6的）路由器——电脑

最近都是在办公室用电脑，都是通过路由器连接，路由器的具体情况我不太了解。以前在相同环境下可以正常使用xx-net。出现问题以后我根据教程取消勾选了WLAN属性中的，一度能用，后来就又不能用了。

**Comment by maxflyer** [comment]
> 
> > 这3个都试过，只有用83.170.6.76偶尔能连上
> 
> ![image](https://user-images.githubusercontent.com/37962734/55305704-18342e80-5484-11e9-846a-bc463dfba7e6.png)

正在尝试，已检测出ip但是有效ip为0

**Comment by AnyWAT** [comment]
> 一度能用，后来就又不能用了。

或许需要：https://github.com/CNMan/dnscrypt-proxy-config

**Comment by maxflyer** [comment]
> > 一度能用，后来就又不能用了。
> 
> 或许需要：https://github.com/CNMan/dnscrypt-proxy-config

没有看懂这个链接，下载了以后运行service-install.bat以后报错：
[2019-04-01 14:24:09] [FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch?

**Comment by AnyWAT** [comment]
主程序：https://github.com/jedisct1/dnscrypt-proxy/releases 仅默认设置，免。。。用
大佬配置：https://github.com/CNMan/dnscrypt-proxy-config 解压到主程序目录

**Comment by maxflyer** [comment]
> 主程序：https://github.com/jedisct1/dnscrypt-proxy/releases （改某文件名为默认配置，可免。。。用
> 大佬配置：https://github.com/CNMan/dnscrypt-proxy-config 解压到主程序目录。。。）
> 主程序刚发布最新版2.0.22

不明白是要把哪个文件的文件名改成什么...

**Comment by AnyWAT** [comment]
> 没有看懂这个链接，下载了以后运行service-install.bat以后报错：
> [2019-04-01 14:24:09] [FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch?

没改某文件名为默认配置，可免。。。用。。。

**Comment by maxflyer** [comment]
> > 没有看懂这个链接，下载了以后运行service-install.bat以后报错：
> > [2019-04-01 14:24:09] [FATAL] Unable to load the configuration file [dnscrypt-proxy.toml] -- Maybe use the -config command-line switch?
> 
> 没能加载配置文件 dnscrypt-proxy.toml：没为默认配置改某文件名，可免。。。用。。。

昨天后来没继续尝试，刚才把扫描设置中的IP模式从“仅IPv6”换成了“自动”，虽然不知道能坚持多久，但是现在能上了

**Comment by AnyWAT** [comment]
> 从“仅IPv6”换成了“自动”

貌似只有使用原生而非隧道才需要如此（分配10%的资源处理 IPv4），原生下有1-5个 IPv4可用，隧道下几乎没有

**Comment by maxflyer** [comment]
> > 从“仅IPv6”换成了“自动”
> 
> 貌似只有使用原生而非隧道才需要如此（分配10%的资源处理 IPv4），原生下有1-5个 IPv4可用，貌似隧道下从来就没有过 [#12043 (comment)](https://github.com/XX-net/XX-Net/issues/12043#issuecomment-464025671)
> #12436 悲惨😭可用的服务器（IP）仅剩。。。

![1](https://user-images.githubusercontent.com/49138034/55371686-ab776d80-5531-11e9-8821-9f5c0a65b918.png)
这样应该是没开吧？

当前状态如下：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:98 ipv4:0 ipv6:94
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:15
scan-ip-thread-num: 1
ip-quality: 361
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> gws-ip-num: total:98 ipv4:0 ipv6:94

ipv4:0

> scan-ip-thread-num: 1

貌似打开了某开关

**Comment by maxflyer** [comment]
> > gws-ip-num: total:98 ipv4:0 ipv6:94
> 
> ipv4:0
> 
> > scan-ip-thread-num: 1
> 
> 貌似打开了某开关

刚才又连不上了，关掉了这个开关重启下连上了半分钟以后又没ip了😔

**Comment by AnyWAT** [comment]
貌似关闭某开关，XX-Net 的性能才好呢：延迟较小、连接池较大
能连接时，没查看是否 NAT : restricted (port) ？

**Comment by maxflyer** [comment]
> 貌似关闭某开关，XX-Net 的性能才好呢：延迟较小、连接池较大
> 能连接时，没查看是否 NAT : restricted (port) ？

没有注意，在家一般能连，晚上回家了试试

**Comment by maxflyer** [comment]
> 貌似关闭某开关，XX-Net 的性能才好呢：延迟较小、连接池较大
> 能连接时，没查看是否 NAT : restricted (port) ？

类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

现在勉强能上，有效ip个位数

**Comment by maxflyer** [comment]
> > 貌似关闭某开关，XX-Net 的性能才好呢：延迟较小、连接池较大
> > 能连接时，没查看是否 NAT : restricted (port) ？
> 
> 没有注意，在家一般能连，晚上回家了试试

类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

家中状况，连接顺利

**Comment by AnyWAT** [comment]
或是公司网管厉害？

**Comment by maxflyer** [comment]
> 或是公司网络管控得厉害？

就是办公中网络搜索的需求大(￣▽￣)"

**Comment by AnyWAT** [comment]
试试：
1、https://github.com/XX-net/XX-Net/issues/12433#issuecomment-478452679 或
2、运行XX-Net 安卓版，再分享给电脑？

**Comment by AnyWAT** [comment]
不正常时：
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 否，PortPreserving: 是

正常时：
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 否，PortPreserving: 否

**Comment by maxflyer** [comment]
> 不正常时：
> 
> > NAT : restricted (port)
> > NAT 特殊行为 : UPNP: 否，PortPreserving: 是
> 
> 正常时：
> 
> > NAT : restricted (port)
> > NAT 特殊行为 : UPNP: 否，PortPreserving: 否

昨天用了这个：服务器能否连接、正常工作，与DNS相关：#12436 (comment)
不过后来一直在家用，看不出来效果，而且说实在的我也不知道我是不是正确使用了..
在公司偶尔正常时PortPreserving也显示过”是“，不过连接远不如家里显示”否“的时候稳定

**Comment by AnyWAT** [comment]
> 不知道我是不是正确使用了..

https://github.com/XX-net/XX-Net/issues/12435#issuecomment-478874060 及以后。。。

**Comment by maxflyer** [comment]
> > 不知道我是不是正确使用了..
> 
> [#12435 (comment)](https://github.com/XX-net/XX-Net/issues/12435#issuecomment-478874060) 及以后。。。

我运行了service-install.bat，提示看当时是正常运行了。但是我不知道是不是每次开机都要运行，还是运行一次以后就不用管了。什么时候要关，什么时候要重启，统统不知道

**Comment by AnyWAT** [comment]
> 我运行了service-install.bat，提示看当时是正常运行了。

大佬配置版目录下有 dnscrypt-proxy.log 文件（原程序默认配置没打开 log 记录）。。。

> 但是我不知道是不是每次开机都要运行，还是运行一次以后就不用管了。什么时候要关，什么时候要重启，统统不知道


正常运行后开机自启动，版本（exe文件）更新前关闭、更新后再开启，更新设置、规则 txt 后重启才生效。

**Comment by maxflyer** [comment]
> > 我运行了service-install.bat，提示看当时是正常运行了。
> 
> 大佬配置版目录下有 dnscrypt-proxy.log 文件（原程序默认配置没打开 log 记录）。。。
> 
> > 但是我不知道是不是每次开机都要运行，还是运行一次以后就不用管了。什么时候要关，什么时候要重启，统统不知道
> 
> 正常运行后开机自启动，版本（exe文件）更新前关闭、更新后再开启，更新设置、规则 txt 后重启才生效。

谢谢。
根据这几天的观察，在使用dnscrypt-proxy后已可以稳定地使用xx-net，感谢您的帮助

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12103#issuecomment-481098127

**Comment by AnyWAT** [comment]
Teredo 隧道：#12455 或
原生：#12477
