### ISSUE TITLE
N久不行了，貌似谷歌改策略之后就只能时断时续的上。。ipv6测试也提示不能连接了。。之前正常的

### ISSUE THREAD

**Issue by thundery1** [XX-net/XX-Net#12438]
下面是日志，请大侠帮忙看看
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> ipv6测试也提示不能连接了

#12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启 IPv6以来，一直正常一直不用此玩意儿
关闭某开关，隧道远优于原生，如（或不确定）已有原生 IPV6而用隧道，（电脑）网络属性内必须取消勾选 IPV6协议以禁用原生。
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by Alobe007** [comment]
感觉是被针对性地采取措施了。基本上，如果是新获得的广域网IP（光猫重起或重新拨号之类），可能会扫到一些可用IP（不会满，但可用。部分能通过检查）。一旦开始上网（如推），IP数就会持续掉落直到为0。

而XX的设置都不变情况下，如先用其它翻墙方式，出口翻成国外其它IP，则一切就会恢复正常，IP数持续上升直到满格。延迟也很低。因设置完全没变，所以应该不是Teredo服务器选择的问题。

**Comment by AnyWAT** [comment]
> 如果是新获得的广域网IP（光猫重起或重新拨号之类）

1、开机不久，运行 netsh int ipv6 show teredo 的结果，外部NAT映射的 IP：a.b.c.d
2、浏览器内 https://www.ip.cn 查询，您现在的 IP：a.b.c.d
重启 dnscrypt-proxy 后1、的 IP：a.b.c.d 但2、的 IP：a.e.f.d（属地与 a.b.c.d 相同）
曾经没注意是否 dnscrypt-proxy 自动更换了其它更快的DNS，1、的 IP：a.b.c.d 但2、的 IP：a.b.e.d（属地与 a.b.c.d 相同）

> 而XX的设置都不变情况下，如先用其它翻墙方式，出口翻成国外其它IP，则一切就会恢复正常，IP数持续上升直到满格。延迟也很低。因设置完全没变，所以应该不是Teredo服务器选择的问题。

服务器能否连接、正常工作，与DNS相关：https://github.com/XX-net/XX-Net/issues/12436#issuecomment-478861896

**Comment by Alobe007** [comment]
> > 如果是新获得的广域网IP（光猫重起或重新拨号之类）
> 
> 电脑直连光猫
> 1、开机不久，运行 netsh int ipv6 show teredo 的结果，外部NAT映射的 IP：a.b.c.d
> 2、浏览器内 https://www.ip.cn 查询，您现在的 IP：a.b.c.d
> 重启 dnscrypt-proxy 后1、的 IP：a.b.c.d 但2、的 IP：a.e.f.d（属地与 a.b.c.d 相同）
> 一定时间后的此刻1、2、的 IP又相同了（貌似 a.b.c.d ）
> [shadowsocks/shadowsocks-windows#2230 (comment)](https://github.com/shadowsocks/shadowsocks-windows/issues/2230#issuecomment-477377371) 曾经没注意是否 dnscrypt-proxy 自动更换了其它更快的DNS，1、的 IP：a.b.c.d 但2、的 IP：a.b.e.d（属地与 a.b.c.d 相同）
> 
> > 而XX的设置都不变情况下，如先用其它翻墙方式，出口翻成国外其它IP，则一切就会恢复正常，IP数持续上升直到满格。延迟也很低。因设置完全没变，所以应该不是Teredo服务器选择的问题。
> 
> 服务器能否连接、正常工作，与DNS相关：[#12436 (comment)](https://github.com/XX-net/XX-Net/issues/12436#issuecomment-478861896)
> DNS 等不变的情况下，有的服务器不可用，更换其它服务器或许能用（除非没禁用原生）

有启发。去试试这些。谢谢。

**Comment by AnyWAT** [comment]
🤣刚刚又：一定时间后的此刻2、的 IP又不同了 a.g.h.d，1、仍旧 a.b.c.d

**Comment by AnyWAT** [comment]
某脚本推荐的巨硬及非巨硬效果对比：https://github.com/XX-net/XX-Net/issues/12439#issuecomment-479340557

**Comment by asmosn** [comment]
試過很多次，Windows上徹底game over了，手機只有斷開wifi才偶爾能連上

**Comment by thundery1** [comment]
teredo的几个服务器能够ping通，但是设置之后提示NAT:端口被禁，端口冲突了么？怎么改端口？见下面：
++++++++++UDP connection testing+++++++++

teredo.remlab.net:3544 is accessible
teredo2.remlab.net:3544 is accessible
teredo-debian.remlab.net:3544 is accessible
teredo.ngix.ne.kr:3544 isn't accessible
teredo.trex.fi:3544 is accessible
teredo.autotrans.consulintel.com:3544 isn't accessible
teredo.managemydedi.com:3544 isn't accessible
teredo.ipv6.microsoft.com:3544 isn't accessible
win10.ipv6.microsoft.com:3544 is accessible
teredo.iks-jena.de:3544 is accessible
win1710.ipv6.microsoft.com:3544 is accessible

++++++++++ping testing+++++++++

teredo.remlab.net 247 ms
teredo2.remlab.net 351 ms
teredo-debian.remlab.net 246 ms
teredo.trex.fi 250 ms
win10.ipv6.microsoft.com 9999 ms
teredo.iks-jena.de 299 ms
win1710.ipv6.microsoft.com 9999 ms

+++++++最佳teredo为： teredo-debian.remlab.net +++++++
确定。

 请选择需要的操作
    1 netsh int ipv6 show teredo
    2 自动选择并设置teredo服务器
    3 手动选择并设置teredo服务器
    4 exit
请选择要进行的操作数字 ，然后按回车：1
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 10.196.98.21:52903
外部 NAT 映射    : *.*.*.*:52903

**Comment by AnyWAT** [comment]
> 但是设置之后提示NAT:端口被禁，端口冲突了么？

> NAT : restricted (port)

貌似不是所谓冲突，见友友也是此状态却正常：https://github.com/XX-net/XX-Net/issues/12433#issuecomment-478987109

**Comment by AnyWAT** [comment]
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 否，PortPreserving: 是

😱正是友友不正常时的状态：https://github.com/XX-net/XX-Net/issues/12433#issuecomment-479830187

**Comment by AnyWAT** [comment]
脚本最新版：https://github.com/XX-net/XX-Net/issues/10282
