### ISSUE TITLE
更改托盘浏览器代理无效，提示请检查浏览器代理设置

### ISSUE THREAD

**Issue by youngkang9998** [XX-net/XX-Net#12441]
sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:84
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:3
scan-ip-thread-num: 1
ip-quality: 513
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
（浏览器没用代理扩展？）系统托盘图标改到全局GAE或智能路由器即可，提示请检查浏览器代理设置或许因为：
> worker: h1:0 h2:3

连接池太小，由于

> scan-ip-thread-num: 1

明显是（软件默认值）打开了某开关的特征，试试 #12043 关闭某开关！连接池将增大、IP延迟将减小。
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by youngkang9998** [comment]
![image](https://user-images.githubusercontent.com/44439535/55677243-fec53380-5916-11e9-99b6-b3624c637af7.png)

**Comment by AnyWAT** [comment]
无需 IP地址的2行——隐私！
 #12043 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。
貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。
