### ISSUE TITLE
请大神帮帮忙，最近几个月感觉都极其不稳定

### ISSUE THREAD

**Issue by zcstkhk** [XX-net/XX-Net#12445]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:17
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:3
scan-ip-thread-num: 100
ip-quality: 975
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

**Comment by zcstkhk** [comment]
也很经常明明显示是一切正常，可以访问互联网了，但是就是翻不出去

**Comment by AnyWAT** [comment]
#12043 关闭某开关、网络属性内取消勾选 IP v6协议以禁用原生而使用隧道
如使用域名不理想，可试试使用其 IP。。。
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76

**Comment by xugaohui** [comment]
又见机器人在忽悠了,虽然界面上还保留有正常和极端选项存在，但新版本上它是没任何区别的。仅这个版本这样。

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/55663686-35864580-5854-11e9-9b1e-f7fe1b2851ea.png)
