### ISSUE TITLE
个别网站访问出现404？

### ISSUE THREAD

**Issue by XiangBicheng** [XX-net/XX-Net#12449]
其他网站访问均正常，但是访问经济学人网站的时候除了首页能正常打开以外，其他链接服务器均返回404(Page not found)。而且打开该网站的登陆页面，当我输入账号密码后，点击登陆后网页没有任何反应。不知道是什么原因？有遇到相同问题的兄弟吗？

**Comment by SeaHOH** [comment]
可能是网站本身限制
