### ISSUE TITLE
这是怎么回事呢？什么都打不开。

### ISSUE THREAD

**Issue by hawyrihby** [XX-net/XX-Net#12447]
600:gae_exception:'600:fetch gae fail' https://www.baidu.com/baidu?wd=grrg&tn=monline_dg&ie=utf-8gae_exception:'600:fetch gae fail' https://www.baidu.com/baidu?wd=grrg&tn=monline_dg&ie=utf-8gae_exception:'600:fetch gae fail' https://www.baidu.com/baidu?wd=grrg&tn=monline_dg&ie=utf-8

**Comment by AnyWAT** [comment]
#12043 关闭某开关，隧道远优于原生，如（或不确定）已有原生 IPV6而用隧道，（电脑）网络属性内必须取消勾选 IPV6协议以禁用原生。
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by hawyrihby** [comment]
是那个隧道服务器的问题。我换了你说的 日本就ok了。谢谢。
