### ISSUE TITLE
连接一直无法建立，ipv6正常但没有连接池

### ISSUE THREAD

**Issue by smalljust** [XX-net/XX-Net#12442]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:95 ipv4:0 ipv6:95
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 419
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

日志显示
2019-04-04 11:52:30.300 - [DEBUG] create ssl timeout fail.

2019-04-04 11:52:30.566 - [WARNING] task GET clients2.google.com /service/update2/crx?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D9.5.6.1%26uc&_=1554349825408 timeout

2019-04-04 11:52:30.566 - [WARNING] send response fail

2019-04-04 11:52:30.669 - [WARNING] task POST None /_gh/ timeout

2019-04-04 11:52:30.669 - [DEBUG] GAE_Exception 600 'fetch gae fail'

**Comment by AnyWAT** [comment]
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by zcstkhk** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否

**Comment by AnyWAT** [comment]
貌似掉入了服务器陷阱出不来了，所以再也没有后话🤣

**Comment by smalljust** [comment]
教育网没有使用teredo，用的是isatap通道

**Comment by AnyWAT** [comment]
https://github.com/tuna/ipv6.tsinghua.edu.cn/blob/master/isatap.md

**Comment by smalljust** [comment]
不好意思麻烦了 这几天申请了IPV6地址 现在可以用了

**Comment by AnyWAT** [comment]
😱到底是教育网，与平民网络是反的？屁民是禁用原生 IPv6才好用XX-Net #12455

**Comment by daniu88** [comment]
> 不好意思麻烦了这几天申请了IPV6地址现在可以用了

申请原生ipv6？还是怎么操作
