### ISSUE TITLE
1

### ISSUE THREAD

**Issue by dong1015787446** [XX-net/XX-Net#12448]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 2.7.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000,1347
connected-link: 0,0
scan-ip-thread-num: 50
ip-handshake-10: 128
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
> xxnet-version: 2.7.3

唯有最新版3.13.1工作正常

**Comment by dong1015787446** [comment]
> > xxnet-version：2.7.3
> 
> 唯有最新版3.13.1工作正常

好的 ，谢谢
