### ISSUE TITLE
选择【取消全局代理】后，无法上网了

### ISSUE THREAD

**Issue by EstellaZ** [XX-net/XX-Net#12443]
xx-net已为最新版3.13.1

在提出该问题前已查过相关问题的解决：找到Internet属性→连接→局域网设置→代理服务器 所有选项都打√了，但仍**未解决**我的问题

已尝试：【取消全局代理】+【重启各模块】-失败
重启电脑，重新打开xx-net,全局代理连接成功后再尝试取消 - 失败
选择【全局通过GAEProxy代理】时，连接正常。

总结：通过【…代理】，连接都正常，但是用自己原来的网就失败了。

请问还有什么办法？谢谢

**Comment by burdenlee** [comment]
...你不用代理怎么翻墙 如果你不想用xxnet自带的切换模式 可以用SwitchOmega xxnet文件夹里面自带了

**Comment by EstellaZ** [comment]
> ...你不用代理怎么翻墙 如果你不想用xxnet自带的切换模式 可以用SwitchOmega xxnet文件夹里面自带了

不是，我现在不需要翻墙了（就取消全局代理了），想用回原来的网，但连不上

**Comment by burdenlee** [comment]
不想用代理就把局域网设置里面的√全部取消

**Comment by EstellaZ** [comment]
> 不想用代理就把局域网设置里面的√全部取消
取消过了，还是不行（你说的局域网设置是我说的那个相关问题解决么？）

**Comment by EstellaZ** [comment]
> 不想用代理就把局域网设置里面的√全部取消

取消过了，还是不行（你说的局域网设置是我说的那个相关问题解决么？）

**Comment by EstellaZ** [comment]
可以了可以了，谢谢！（虽然我也不知道怎么就突然正常了（笑））

**Comment by AnyWAT** [comment]
选择【取消全局代理】后
1、检查 IE内的系统代理应如此
![image](https://user-images.githubusercontent.com/37962734/55554076-78d99a80-5714-11e9-95e3-de366f11978d.png)

2、如是Win10，系统代理设置应如此
![image](https://user-images.githubusercontent.com/37962734/55554182-bdfdcc80-5714-11e9-962c-0b1817dc24cc.png)

3、XX-Net 目录下 data\launcher\config.yaml 文件内应如此（proxy: disable）
![image](https://user-images.githubusercontent.com/37962734/55554422-4e3c1180-5715-11e9-9eb1-f73f9231bdb2.png)

**Comment by EstellaZ** [comment]
> 选择【取消全局代理】后
> 1、检查 IE内的系统代理应如此
> ![image](https://user-images.githubusercontent.com/37962734/55554076-78d99a80-5714-11e9-95e3-de366f11978d.png)
> 
> 2、如是Win10，系统代理设置应如此
> ![image](https://user-images.githubusercontent.com/37962734/55554182-bdfdcc80-5714-11e9-962c-0b1817dc24cc.png)
> 
> 3、XX-Net 目录下 data\launcher\config.yaml 文件内应如此（proxy: disable）
> ![image](https://user-images.githubusercontent.com/37962734/55554422-4e3c1180-5715-11e9-9eb1-f73f9231bdb2.png)


我是采用的第一个方法，都检查过局域网那边没有勾选，但依然不正常。后来我在回复楼上帮我解答的那个朋友的时候，突然就好了oz（方法应该没问题，可能我电脑反应比较慢，谢谢你们啊
