### ISSUE TITLE
ipv6打开之后，偶尔会自动关闭

### ISSUE THREAD

**Issue by wa008** [XX-net/XX-Net#12458]
昨天弄好了，但今天打开又不行了，又重新按照流程弄好之后，显示可以访问真正的互联网了，但打开youtube，仍然会超时打不开，再回头看xxnet的时候，就是（等待扫描 IP，建议开启 IPv6）或（者链接尚未建立），再去测试 http://test-ipv6.com ，不使用域名的 IPv6 测试就会显示超时，得重新从cmd中打开一下ipv6

**Comment by wa008** [comment]
本地网络的ipv6选项已经取消了，还是这个错误

**Comment by AnyWAT** [comment]
#12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启 IPv6以来，一直正常一直不用此玩意儿

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477
