### ISSUE TITLE
mac系统 IPv6不可用

### ISSUE THREAD

**Issue by kaoshen** [XX-net/XX-Net#12454]
XX-Net Status:

sys-platform: x86_64, Darwin-17.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
os-release: 17.4.0
os-detail: Release:10.13.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
貌似与操作系统无关？
1、隧道远优于原生。如（或不确定）已有原生 IPV6而用隧道，或路由器禁用原生 IPv6或（电脑）网络属性内必须取消勾选 IPV6协议以禁用原生 。
2、关闭“自动调整扫描线程数”，最大扫描线程数以能自动维持：有效 IP数/总 IP数之比值=1 时为最小值
3、貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。
4、隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。（Windows 系统：#12043）
