### ISSUE TITLE
ipv6仍旧无法开启

### ISSUE THREAD

**Issue by sherlockfuture** [XX-net/XX-Net#12451]
用的最新版本的xx-net
试过了“如何开启ipv6”里wins10的的开启方法，但是仍旧无法上网。
在取消全局代理的时候，完全用不了ipv6，但是在用全局pac智能代理的时候，偶尔的能上一两分钟gmail的官网。
希望能告诉我一下能怎么做
[ipv6-state2019-04-07_120814.txt](https://github.com/XX-net/XX-Net/files/3051207/ipv6-state2019-04-07_120814.txt)
[诊断信息.txt](https://github.com/XX-net/XX-Net/files/3051208/default.txt)
[日志.txt](https://github.com/XX-net/XX-Net/files/3051209/default.txt)

**Comment by AnyWAT** [comment]
#12043 关闭某开关，隧道远优于原生，如（或不确定）已有原生 IPV6而用隧道，（电脑）网络属性内必须取消勾选 IPV6协议以禁用原生。
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by OP83** [comment]
麻烦帮我看下，谢谢！没有原生ipv6，win7系统。
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by AnyWAT** [comment]
服务器名称 : win10.ipv6.microsoft.com.——（被推荐、隧道能连接但扫描不到 IP的）服务器陷阱！
#12043 命令行更换服务器
貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。

**Comment by OP83** [comment]
> 服务器名称 : win10.ipv6.microsoft.com.——（被推荐、隧道或能连接、甚或 IPv6但扫描不到 IP的）服务器陷阱！
> 隧道已连接——控制页内 IPv6已OK——能扫描出 IP，有前才有后。。。
> #12043 命令行更换服务器
> 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> teredo-debian.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。

用了你给的第一个IP，217那个，扫描出10几个IP，目前正常了，非常感谢！

**Comment by AnyWAT** [comment]
> 扫描出10几个IP

要求也忒低了 #12455

**Comment by sherlockfuture** [comment]
> > 扫描出10几个IP
> 
> 要求也忒低了 #12455

netsh int ipv6 set teredo enterpriseclient是运行这句话吗？我几个都试过了但是效果仍旧不理想，连不上。然后这个link连来连去好多啊，我感觉不太好对症下药了。

**Comment by sherlockfuture** [comment]
以及说现在的问题变成了有ip但是，
以下：

浏览器代理设置 | Fail
-- | --
CA 证书状态(下载) | Fail

**Comment by AnyWAT** [comment]
无非是代理的选用不合适？

**Comment by sherlockfuture** [comment]
> 无非是代理的选用不合适？
我听不懂哎。我应该去哪里进行什么修改吗

**Comment by sherlockfuture** [comment]
> 无非是代理的选用不合适？


我没有听懂哎。。我应该去修改什么设置吗？chrome的那个插件已经装好了，然后有效/总==1，但是上面那两项仍旧是fail

**Comment by sherlockfuture** [comment]
> 无非是代理的选用不合适？


现在能连上了，用google的插件。。但是为啥chrome可以，但是edge还是登不了外网啊？

**Comment by AnyWAT** [comment]
> 但是为啥chrome可以，但是edge还是登不了外网啊？

后者得使用“全局。。。”代理

**Comment by OP83** [comment]
> > 扫描出10几个IP
> 
> 要求也忒低了 #12455

请问隧道不能选好几个IP一起吗？一次只能用一个IP？一个IP太不稳定了，经常掉线。

**Comment by AnyWAT** [comment]
> 太不稳定了，经常掉线。

#12455
