### ISSUE TITLE
有效 IPv6 IP 数 很少或者为0，网时好时差是正常现象吗？

### ISSUE THREAD

**Issue by wa008** [XX-net/XX-Net#12459]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
偶尔如此还算正常。。。
https://github.com/XX-net/XX-Net/issues/12431#issuecomment-480690349 及所提及的 #12043

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477
