### ISSUE TITLE
IPV6数目在家广电网，一直20个以下上不了，在公司电信网络100满无问题

### ISSUE THREAD

**Issue by xiyaoeva** [XX-net/XX-Net#12450]
在家一打开google，ipv6数瞬间秒降！

XX-Net Status:

sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 1457
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xiyaoeva** [comment]
![66](https://user-images.githubusercontent.com/22384155/55678231-91220300-5928-11e9-9877-6b8fba3e4105.jpg)

**Comment by AnyWAT** [comment]
> IPV6数目在家广电网，一直20个以下上不了，在公司电信网络100满无问题

同一电脑不同网络，貌似隧道服务器。。。

> ipv6-status: Fail

尽管LS绿灯（隧道已连接），但此处Fail 貌似得更换服务器？
貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。

**Comment by AnyWAT** [comment]
> worker: h1:0 h2:0

参考：#12043 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。

**Comment by xiyaoeva** [comment]
> > IPV6数目在家广电网，一直20个以下上不了，在公司电信网络100满无问题
> 
> 同一电脑不同网络，貌似隧道服务器。。。或家庭网络已有原生 IPv6？用隧道必须（电脑上）禁用原生！
> 
> > ipv6-status: Fail
> 
> 尽管LS绿灯（隧道已连接），但此处Fail 貌似得更换服务器？
> 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> teredo-debian.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。

刚才试了试手动换且用ip地址，不管换哪个，都是ipv6数目涨一下然后立马下降，一直少于10个。。已经采用“极端”模式，手动检查IP，IP直接掉0－。－，怎么办怎么办。。，已经在终端手动启用和禁用隧道好几次了。。

![666](https://user-images.githubusercontent.com/22384155/55678405-c419c600-592b-11e9-9e17-9a3bab768bbe.jpg)
![66](https://user-images.githubusercontent.com/22384155/55678407-ca0fa700-592b-11e9-8809-7f3787407cb1.jpg)
![66](https://user-images.githubusercontent.com/22384155/55678412-dbf14a00-592b-11e9-81eb-f092320a6bc2.jpg)

**Comment by AnyWAT** [comment]
隧道已连接——控制页内 IPv6已OK——能扫描出 IP。。。
有前才有后。。。
> scan-ip-thread-num: 30

适当增大。。。
> 已经采用“极端”模式

更换模式后会默认打开某开关，#12043 关闭某开关！

**Comment by AnyWAT** [comment]
> 手动检查IP，IP直接掉0－。－，怎么办怎么办。。，已经在终端手动启用和禁用隧道好几次了。。

掉以后或许是一直的升，进行了某操作后得检查 IP、稍候——观察变化。。。

**Comment by xiyaoeva** [comment]
谢谢，我再试试

> > 手动检查IP，IP直接掉0－。－，怎么办怎么办。。，已经在终端手动启用和禁用隧道好几次了。。
> 
> （更换服务器后的）掉以后或许是一直的升，进行了某操作后得检查 IP、稍候——观察变化。。。
> 
> 参考：（以下的软件指XX-Net ）
> ![image](https://user-images.githubusercontent.com/37962734/55671866-28ef0500-58c7-11e9-80b9-da3d0bfc2c3c.png)

**Comment by nly4lov** [comment]
我在家是长宽，ip数倒是不少，但翻起来好慢；
在公司是电信，ip100，翻得较快
