### ISSUE TITLE
XX-Net依旧无法使用

### ISSUE THREAD

**Issue by Rookie14** [XX-net/XX-Net#12461]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:103 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

前天刚回来重新装了一下电脑，刚开始一切正常，但昨天就IPv6就变成0了，偶尔会有一两个，但总数不会上双，而且总是提示重新扫描IP，建议开启IPv6……年前也遇到过这样的问题，用一个软件就能恢复“#配置IPv6.bat”（具体是哪位大神的已记不清楚，抱歉！），还望高人指教，谢谢！

**Comment by AnyWAT** [comment]
#12455

**Comment by Rookie14** [comment]
>

> #12455

3、小心被XX-Net 或某脚本唯所谓延迟最小为佳的推荐：隧道或能连接、甚或 IPv6状态🆗但扫描不到 IP的服务器陷阱！貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。

按这个方法做了，但依旧无反应，IP数是103 ，比之前多了，但IPv6还是0

**Comment by AnyWAT** [comment]
本地映射 : ------
外部 NAT 映射 : ------隐私！

> 客户端类型 : teredo host-specific relay

有关隧道客户端类型 : teredo host-specific relay #12378

**Comment by Rookie14** [comment]
> 本地映射 : ------
> 外部 NAT 映射 : ------隐私！
> 
> > 客户端类型 : teredo host-specific relay
> 
> 有关隧道客户端类型 : teredo host-specific relay #12378
> ![image](https://user-images.githubusercontent.com/37962734/55773324-a16de580-5ac2-11e9-82cb-d7eecaee215f.png)
刚关IPv6协议的时候，弹出了4，之后有归零了……

**Comment by nly4lov** [comment]
可以参考下我的经历。https://github.com/XX-net/XX-Net/issues/12370

**Comment by AnyWAT** [comment]
> 刚关IPv6协议的时候，弹出了4，之后有归零了……

#12455 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。（Windows 系统更多。。。：#12043）

**Comment by Rookie14** [comment]
> > 刚关IPv6协议的时候，弹出了4，之后有归零了……
> 
> #12455 隧道显示正常但连接池或有效 IP数归零时：或手动检查 IP，或刷新/新开需代理的网页，或免退出再次启动软件，或（命令行）先禁用再启用隧道，或先禁用再启用（电脑）网络，或（命令行）更换隧道服务器。。。（Windows 系统更多。。。：#12043）

下午忙点儿别的事儿，现在好了……
![TIM截图20190409182414](https://user-images.githubusercontent.com/34498001/55793106-b6636c80-5af4-11e9-90c1-61090d93fe6b.png)
多谢！

**Comment by AnyWAT** [comment]
有效 IP数/总 IP数之比值=27/100——貌似扫描线程数太小？

**Comment by Rookie14** [comment]
> 有效 IP数/总 IP数之比值=27/100——貌似扫描线程数太小？

那种情况应该如何解决

**Comment by Buccaneer01** [comment]
偶尔能连上，1/N的概率。。。也是速度极慢，看油管各种中断

**Comment by AnyWAT** [comment]
> 偶尔能连上，1/N的概率。。。也是速度极慢，看油管各种中断

#12455 100%连上，100%的概率。。。尝试解决慢：参考 https://github.com/xyuanmu/XX-Mini
> ;下载分流，建议使用默认值
> [autorange]
> ;线程数，当观看视频不流畅可适当增加
> threads = 20
> ;分块大小，如果IP质量好可以修改 maxsize 为更大的数值
> maxsize = 548576

code\3.13.1\gae_proxy\local\config.py 内
![image](https://user-images.githubusercontent.com/37962734/55847083-98d8e600-5b7a-11e9-8bd0-268986fb8c75.png)

貌似 threads = 10 maxsize = 512x1024=524288
通过 data\gae_proxy\config.json 增加参数
"AUTORANGE_THREADS": xxx,
"AUTORANGE_MAXSIZE": yyy,
调试。。。

**Comment by AnyWAT** [comment]
> 那种情况应该如何挽救

首先得治：视而不见😂

**Comment by Rookie14** [comment]
> > 偶尔能连上，1/N的概率。。。也是速度极慢，看油管各种中断
> 
> #12455 服务器合适、其它设置合适，（随时）有效 IP数/总 IP数之比值=1，每次都能连上，几乎N/N的概率。。。尝试解决慢：参考 https://github.com/xyuanmu/XX-Mini
> 
> > ;下载分流，建议使用默认值
> > [autorange]
> > ;线程数，当观看视频不流畅可适当增加
> > threads = 20
> > ;分块大小，如果IP质量好可以修改 maxsize 为更大的数值
> > maxsize = 548576
> 
> ![image](https://user-images.githubusercontent.com/37962734/55847500-15b88f80-5b7c-11e9-8a91-40e5ed17ec7c.png)
> 
> code\3.13.1\gae_proxy\local\config.py 内
> ![image](https://user-images.githubusercontent.com/37962734/55847083-98d8e600-5b7a-11e9-8bd0-268986fb8c75.png)
> 
> 貌似 threads = 10 maxsize = 512x1024=524288
> 通过 data\gae_proxy\config.json 增加参数
> "AUTORANGE_THREADS": xxx,
> "AUTORANGE_MAXSIZE": yyy,
> 自己调试。。。（增大第一项，或减小第二项？）
> 增大第一项15-30倍，减小第二项为1/4-1/2，效果：[#12466 (comment)](https://github.com/XX-net/XX-Net/issues/12466#issuecomment-481584276)

   @AnyWAT    
按照这个改了但还是上不去，或者说不是特别稳定，是好是坏，该怎么解决。
![TIM截图20190411162757](https://user-images.githubusercontent.com/34498001/55942371-d6bb3480-5c76-11e9-8861-41355bc61df1.png)

**Comment by AnyWAT** [comment]
> 按照这个改了但还是上不去，或者说不是特别稳定，是好是坏，该怎么解决。

config.txt 是神马鬼？如直接修改 config.py，也是：只能动512、不能动1024呢
256 * 1024

**Comment by Rookie14** [comment]
编辑而已，之后再改回.py，其他的不会……

**Comment by Rookie14** [comment]
> > 按照这个改了但还是上不去，或者说不是特别稳定，是好是坏，该怎么解决。
> 
> config.txt 是神马鬼？如直接修改 config.py，也是：只能动512、不能动1024呢
> 256 * 1024

为了编辑，之后改回config.py（其他方法不会……）但我改回过来后还是很不稳定，这个怎么办。目前的状态就是一会儿能传图片，一会儿不能，能不稳定
不是搞这玩意的，绝对的老白……(●'◡'●)

**Comment by AnyWAT** [comment]
退出XX-Net，修改 config.py，（删除 config.pyc，）启动XX-Net

**Comment by AnyWAT** [comment]
> 还是很不稳定，这个怎么办。目前的状态就是一会儿能传图片，一会儿不能，很不稳定……即便能上也坚持不了多久

对比 #12455 告知已做到了哪些。。。

**Comment by Rookie14** [comment]
> > 但我改回过来后还是很不稳定，这个怎么办。目前的状态就是一会儿能传图片，一会儿不能，很不稳定……即便能上也坚持不了多久
> 
> 此处修改是应对看油管各种中断，与一会儿一会儿无关。
> 对比 #12455 告知已做到了哪些。。。

基本按部就班的检查了一遍，发现就总IP数这里没有调整还是原来的100，之后我把所有文章里提到要改的地方都改为1000，并重启了电脑（更新了一下），现在总IP数为120，但还是“连接尚未建立”，”有效 IPv6 IP 数“为2，”有效 IPv4 IP 数“为0，目前还是无法使用。
我把 config.py里提到的"max_good_ip_num"都改为了1000（是不是数字改的打了(lll￢ω￢)）

**Comment by Rookie14** [comment]
> 退出XX-Net，修改 config.py，（删除 config.pyc，）启动XX-Net

虽然开始删除 config.pyc但重启他还会生成，是每次都要删吗？……老白就需要您多指教，嘿嘿

**Comment by AnyWAT** [comment]
> 我把 config.py里提到的"max_good_ip_num"都改为了1000（是不是数字改的打了(lll￢ω￢)）

#12455 有明示🙃
。。。自己琢磨吧，无法帮忙了。。。

**Comment by Rookie14** [comment]
> > 我把 config.py里提到的"max_good_ip_num"都改为了1000（是不是数字改的打了(lll￢ω￢)）
> 
> #12455 有明示🙃
> 。。。自己琢磨吧，无法帮忙了。。。

改为250了，但怎么还是上不了网，提示显示“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。”

有效 IPv6 IP 数 | 7
-- | --
总 IP 数 | 208
没一会儿又变成“连接尚未建立。”
这个什么原因……

**Comment by AnyWAT** [comment]
> 这个什么原因……

如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by Rookie14** [comment]
> netsh int ipv6 show teredo

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : ——————
外部 NAT 映射    :————————
图片传不上，将就一下

**Comment by Rookie14** [comment]
> > netsh int ipv6 show teredo
> 
> ## Teredo 参数
> 类型 : enterpriseclient (Group Policy)
> 服务器名称 : teredo.remlab.net.
> 客户端刷新间隔 : 30 秒
> 客户端端口 : unspecified
> 状态 : qualified
> 客户端类型 : teredo client
> 网络 : managed
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 否，PortPreserving: 否
> 本地映射 : ——————
> 外部 NAT 映射 :————————
> ——————————————————————————————————————————————
> XX-Net Status:
> 
> sys-platform: AMD64, Windows-10-10.0.17763
> os-system: Windows
> os-version: 10.0.17763
> os-release: 10
> os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
> architecture: 32bit,WindowsPE
> browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
> xxnet-version: 3.13.1
> python-version: 2.7.13
> openssl-version: 16.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: auto
> gws-ip-num: total:220 ipv4:0 ipv6:4
> ipv4-status: OK
> ipv6-status: OK
> connected-link: new:0
> worker: h1:0 h2:0
> scan-ip-thread-num: 100
> ip-quality: 825
> is-idle: 1
> proxy_state: OK
> ca_state: OK
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false
> 图片传不上，将就一下，**“现在提示为“系统空闲(正常)”**

**Comment by AnyWAT** [comment]
> 图片传不上

哪里说要图片？

> 服务器名称 : teredo.remlab.net.

试试改用服务器 IP或其它服务器？

> gws-ip-num: total:220 ipv4:0 ipv6:4
> scan-ip-thread-num: 100

已100，但 total:220 ipv4:0 ipv6:4 不应该，莫非没关闭某开关？#12455

**Comment by AnyWAT** [comment]
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 否，PortPreserving: 否

不明为何 restricted (port) ，但可用，貌似没 symmetric 好（当然，被某脚本说后者不可使用）？
![image](https://user-images.githubusercontent.com/37962734/55952465-4556bd00-5c8c-11e9-8a08-fda60001f1af.png)

**Comment by nly4lov** [comment]
楼上二位的对话基本看不懂，但并不妨碍我fq翻的流畅![e105](https://user-images.githubusercontent.com/11325411/56004521-6821b980-5cfe-11e9-9ae6-3644832472e2.png)

**Comment by Rookie14** [comment]
> >试试改用服务器 IP或其它服务器？

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:249 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:2
scan-ip-thread-num: 100
ip-quality: 1141
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

已经更换了服务器，但还是不太理想，要每个都试一下吗？
![微信截图_20190414121720](https://user-images.githubusercontent.com/34498001/56088267-664b2800-5eaf-11e9-9b5b-83c2bb702657.png)

**Comment by AnyWAT** [comment]
贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及某开关状态（截图）

**Comment by Rookie14** [comment]
> netsh int ipv6 show teredo

![微信截图_20190414130459](https://user-images.githubusercontent.com/34498001/56088549-f8eec580-5eb5-11e9-9e13-cbf0c468f06b.png)

**Comment by AnyWAT** [comment]
> 类型 : enterpriseclient (Group Policy)

https://github.com/XX-net/XX-Net/issues/12043 摒弃 IPv6 组策略法：退回到默认的“未设置”

> 服务器名称 : teredo.trex.fi.

https://github.com/XX-net/XX-Net/issues/12455 如使用（服务器）域名不理想，可试试使用其 IP。。。（😡还要重复N次？）

> 贴。。。及某开关的先前使用状态（截图）

。。。

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477

**Comment by Rookie14** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:480 ipv4:1 ipv6:183
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false



现在是“IPv6 状态(如何开启)	Fail (尝试修复)“

**Comment by Rookie14** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:480 ipv4:2 ipv6:454
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

现在又不行了……那里的原因……@AnyWAT

**Comment by Rookie14** [comment]
> Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477

现在把Teredo 隧道关了，倒是可以登录youtube，但是特别的慢，总是卡。把画质调到最低才能流畅运行，但这实在无法看呀
![微信截图_20190421205054](https://user-images.githubusercontent.com/34498001/56470310-456a7000-6477-11e9-824a-b5e47fc72068.png)


![QQ截图20190417233629](https://user-images.githubusercontent.com/34498001/56470328-7d71b300-6477-11e9-857f-b9df20c56d2c.png)
