### ISSUE TITLE
未解决完的问题……

### ISSUE THREAD

**Issue by Rookie14** [XX-net/XX-Net#12462]
@AnyWAT
3、小心被XX-Net 或某脚本唯所谓延迟最小为佳的推荐：隧道或能连接、甚或 IPv6状态🆗但扫描不到 IP的服务器陷阱！貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de. 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo-debian.remlab.net. 83.170.6.76
如使用域名不理想，可试试使用其 IP。。。
这个已经用了， IP数变成了103，但并没有用，IPv6依旧是0

点错了……可删除

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12461#issuecomment-481096183

**Comment by Rookie14** [comment]
现在把Teredo 隧道关了，倒是可以登录youtube，但是特别的慢，总是卡。把画质调到最低才能运行（偶尔也卡），但这实在无法看呀！
不知道为什么把之前的帖子给关了，就用这个提问吧,
