### ISSUE TITLE
ipv6已经开启，为什么还要等待扫描？

### ISSUE THREAD

**Issue by daniu88** [XX-net/XX-Net#12469]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
或许掉进了服务器陷阱？#12455

**Comment by daniu88** [comment]
> 或许掉进了服务器陷阱？[＃12455](https://github.com/XX-net/XX-Net/issues/12455)

解决方案是什么呢？可以贴个连接吗？

**Comment by AnyWAT** [comment]
> 解决方案是什么呢？可以贴个连接吗？

高抬贵鼠 👉 ＃12455

**Comment by daniu88** [comment]
> > 解决方案是什么呢？可以贴个连接吗？
> 
> 视而不见。高抬贵鼠 👉 [＃12455](https://github.com/XX-net/XX-Net/issues/12455)

3，小心被XX-Net或某脚本唯所谓延迟最小为佳的推荐：隧道或能连接，甚或IPv6状态🆗但扫描不到IP的服务器陷阱！貌似巨硬服务器全部已残，唯有：
teredo.iks-jena.de。217.17.192.217 
teredo.trex.fi。195.140.195.140 
teredo.remlab.net。83.170.6.76 
teredo-debian.remlab.net。83.170.6.76 
如使用域名不理想，可试试使用其IP ...


每一个ip都试一遍？

**Comment by AnyWAT** [comment]
在其它贴看到，貌似教育网？https://github.com/XX-net/XX-Net/issues/12442#issuecomment-481589658

**Comment by AnyWAT** [comment]
> teredo.iks-jena.de。217.17.192.217
> teredo.trex.fi。195.140.195.140
> teredo.remlab.net。83.170.6.76
> teredo-debian.remlab.net。83.170.6.76

.变。有意无意（篡改）？

**Comment by daniu88** [comment]
> 在其它贴看到，貌似教育网？[＃12442（评论）](https://github.com/XX-net/XX-Net/issues/12442#issuecomment-481589658)


最开始就是跟着这贴操作的，后来你说掉入服务器陷阱，现在重新设置之后还是不可以


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by daniu88** [comment]
> > teredo.iks-jena.de.217.17.192.217 
> > teredo.trex.fi.195.140.195.140 
> > teredo.remlab.net.83.170.6.76 
> > teredo-debian.remlab.net.83.170.6.76
> 
> 变。有意无意（篡改）？

也没有用，现在都不跳出那个谷歌账户授权的页面了

**Comment by AnyWAT** [comment]
> 最开始就是跟着这贴操作的，后来你说掉入服务器陷阱，现在重新设置之后还是不可以

如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by AnyWAT** [comment]
> 也没有用，现在都不跳出那个谷歌账户授权的页面了

XX-Net 都不正常，跳出那个干嘛？

**Comment by daniu88** [comment]
> > 最开始就是跟着这贴操作的，后来你说掉入服务器陷阱，现在重新设置之后还是不可以
> 
> 没回答是否教育网，如用（远优于原生的）隧道，贴cmd内运行netsh int ipv6 show teredo的结果（无需IP地址的2行）

以管理员身份运行CMD命令，进入命令行模式，输入如下命令

netsh int ipv6 isatap set router isatap.tsinghua.edu.cn
netsh int ipv6 isatap set state enable


按照这两条命令，一条一条粘贴的，但是还是不行

**Comment by daniu88** [comment]
> 在其它贴看到，楼主貌似教育网？[#12442 (comment)](https://github.com/XX-net/XX-Net/issues/12442#issuecomment-481589658)

我用的是教育网，按照这两条命令敲的

以管理员身份运行CMD命令，进入命令行模式，输入如下命令

netsh int ipv6 isatap set router isatap.tsinghua.edu.cn
netsh int ipv6 isatap set state enable

应该是教育网吧？

**Comment by AnyWAT** [comment]
> 按照这两条命令，一条一条粘贴的，但是还是不行

侧面回答了是教育网，如 https://github.com/XX-net/XX-Net/issues/12442#issuecomment-482042183 
不好意思，没经历。。。废贴一条 https://github.com/XX-net/XX-Net/issues/12469#issuecomment-482042144

**Comment by daniu88** [comment]
> > 按照这两条命令，一条一条粘贴的，但是还是不行
> 
> 侧面回答了是教育网，如 [#12442 (comment)](https://github.com/XX-net/XX-Net/issues/12442#issuecomment-482042183)
> 不好意思，没经历。。。废贴一条 [#12469 (comment)](https://github.com/XX-net/XX-Net/issues/12469#issuecomment-482042144)

大哥，搞半天也不行吗？我这个问题怎么解决呢？能支招吗？

**Comment by AnyWAT** [comment]
> 没经历。。。

没经历。。。没经历。。。没经历。。。

**Comment by daniu88** [comment]
> > 没经历...
> 
> 没经历......没经历......没经历...

你的软件现在是正常的吗？怎么操作的

**Comment by daniu88** [comment]
> > 没经历...
> 
> 没经历......没经历......没经历...

服务器陷阱那个就是用教育网的通道就能解决么？还是怎样的呢？

**Comment by AnyWAT** [comment]
> 你的软件现在是正常的吗？怎么操作的

https://github.com/XX-net/XX-Net/issues/12442#issuecomment-481593158 平民非教育网络。。。
当然正常，一直分分钟正常，#12455 #12043 正常的操作经历。。。

> 服务器陷阱那个就是用教育网的通道就能解决么？还是怎样的呢？

你说呢？睁大双眼：
Teredo 隧道相关。。。 #12455
Win32系统3.13.1（Teredo）隧道简单操作几乎启动即正常稳定 #12043

**Comment by daniu88** [comment]
> > 你的软件现在是正常的吗？怎么操作的
> 
> [＃12442（comment）](https://github.com/XX-net/XX-Net/issues/12442#issuecomment-481593158)平民非教育网络... 
> 当然正常，一直分分钟正常，[＃12455 ](https://github.com/XX-net/XX-Net/issues/12455) [＃](https://github.com/XX-net/XX-Net/issues/12043)[12043](https://github.com/XX-net/XX-Net/issues/12455)正常的操作经历...
> ![图片](https://user-images.githubusercontent.com/37962734/55949022-497edc80-5c84-11e9-8c97-af6966a42e8c.png)
> 
> > 服务器陷阱那个就是用教育网的通道就能解决么？还是怎样的呢？
> 
> 你说呢？睁大双眼：
> Teredo隧道相关... [＃12455](https://github.com/XX-net/XX-Net/issues/12455)
> Win32系统3.13.1（Teredo）隧道简单操作几乎启动即正常稳定[＃12043](https://github.com/XX-net/XX-Net/issues/12043)
> 
> PS：发帖最好声明教育网......至少别人问起能立马确认...

帮助：



C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant




XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false




大哥，帮忙看看吧

**Comment by AnyWAT** [comment]
> 服务器名称 : teredo.remlab.net
> 状态 : dormant

隧道未连接，#12455 如（或不确定）已有原生 IPV6而用隧道，或路由器禁用原生 IPv6或（电脑）网络属性内取消勾选 IPV6协议以禁用原生 。。。如使用域名不理想，可试试使用其 IP或其它服务器。。。

但：
> ipv6-status: OK

神马鬼？隧道已连接——控制页内 IPv6状态🆗，否则貌似不成立😱

> scan-ip-thread-num: 10

增大5-10倍，并关闭某开关 #12455

> gws-ip-num: total:0 ipv4:0 ipv6:0
> worker: h1:0 h2:0
> is-idle: 1

#12455 隧道显示正常但连接池或有效 IP数归零时：。。。

**Comment by AnyWAT** [comment]
> > ipv6-status: OK
> 
> 神马鬼？隧道已连接——控制页内 IPv6状态🆗，否则貌似不成立😱

也许是教育网专用隧道已连接的效果？

**Comment by daniu88** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false






> > > ipv6-status：好的
> > 
> > 
> > 神马鬼？隧道已连接 - 控制页内IPv6状态🆗，否则貌似不成立😱
> 
> 也许是教育网专用隧道已连接的效果？如用teredo隧道，或许得先运行XX-Net目录内的disable_ipv6.bat再启用_ipv6.bat















C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant




XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by daniu88** [comment]
> > > ipv6-status：好的
> > 
> > 
> > 神马鬼？隧道已连接 - 控制页内IPv6状态🆗，否则貌似不成立😱
> 
> 也许是教育网专用隧道已连接的效果？如用teredo隧道，或许得先运行XX-Net目录内的disable_ipv6.bat再启用_ipv6.bat

大佬，还是等待扫描，怎么解决呢？

**Comment by AnyWAT** [comment]
> 大佬，还是等待扫描，怎么解决呢？

 大佬，你不识字么？
> 服务器名称 : win10.ipv6.microsoft.com.
> 状态 : dormant

> > 服务器名称 : teredo.remlab.net
> > 状态 : dormant
> 
> 隧道未连接，#12455 如（或不确定）已有原生 IPV6而用隧道，或路由器禁用原生 IPv6或（电脑）网络属性内取消勾选 IPV6协议以禁用原生 。。。如使用域名不理想，可试试使用其 IP或其它服务器。。。

#12455 小心被XX-Net 或某脚本唯所谓延迟最小为佳的推荐：隧道或能连接、甚或 IPv6状态🆗但扫描不到 IP的服务器陷阱！貌似巨硬服务器全部已残，唯有：。。。

> > scan-ip-thread-num: 10
> 
> 增大5-10倍，并关闭某开关 #12455

说过的问题依然存在，严重怀疑：不识字。。。886👌

**Comment by daniu88** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false



-------------------------------------

C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant



到底是什么情况啊啊啊啊啊啊

**Comment by daniu88** [comment]
> > 大佬，还是等待扫描，怎么解决呢？
> 
> 大佬，你不识字么？
> 
> > 服务器名称：win10.ipv6.microsoft.com。
> > 状态：休眠
> 
> > > 服务器名称：teredo.remlab.net 
> > > 状态：休眠
> > 
> > 
> > 隧道未连接，[＃12455](https://github.com/XX-net/XX-Net/issues/12455)如（或不确定）已有原生IPV6而用隧道，或路由器禁用原生IPv6或（电脑）网络属性内取消勾选IPV6协议以禁用原生...如使用域名不理想，可试试使用其IP或其它服务器...
> 
> [＃12455](https://github.com/XX-net/XX-Net/issues/12455)小心被XX-Net或某脚本唯所谓延迟最小为佳的推荐：隧道或能连接，甚或IPv6状态🆗但扫描不到IP的服务器陷阱！貌似巨硬服务器全部已残，唯有：......
> 
> > > scan-ip-thread-num：10
> > 
> > 
> > 增大5-10倍，并关闭某开关[＃12455](https://github.com/XX-net/XX-Net/issues/12455)
> 
> > > gws-ip-num：total：0 ipv4：0 ipv6：0 
> > > worker：h1：0 h2：0 
> > > is-idle：1
> > 
> > 
> > [＃12455](https://github.com/XX-net/XX-Net/issues/12455)隧道显示正常但连接池或有效IP数归零时：...
> > 首要：隧道能连接
> 
> 除了[＃12455](https://github.com/XX-net/XX-Net/issues/12455)已说过，在此贴更是重复（[＃12455](https://github.com/XX-net/XX-Net/issues/12455)）说过的问题依然存在，严重怀疑：不识字... 886👌（😜没条理的文科生？）

大哥，帮忙看看吧

**Comment by AnyWAT** [comment]
> 服务器名称 : 83.170.6.76
> 状态 : dormant

隧道未连接，换另外2个？如 195.140.195.140。禁用原生没？

**Comment by daniu88** [comment]
> > 服务器名称：83.170.6.76 
> > 状态：休眠
> 
> 隧道未连接，换另外2个？如195.140.195.140禁用原生没？
> 
> > use-ipv6：force_ipv6
> 
> 或改用自动

-----------------------------------

大神，完美解决了。
有两个问题阻碍我部署：
1、是win10原生ipv6没有关闭。这里贴一个百家号帖子：https://baijiahao.baidu.com/s?id=1611375634981908298&wfr=spider&for=pc

2、关闭“ 自动调整扫描线程数 ”，最大扫描线程数以能自动维持100-150左右：[http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting](url)

谢谢大神~~~~

**Comment by AnyWAT** [comment]
😱3-5分钟的事情花了近3天🤣

**Comment by daniu88** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 98
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false




-----------------------------------



C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.iks-jena.de
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是




-------------------------------------------

部署得上完全靠运营，大佬帮我看看哇~~~~

**Comment by daniu88** [comment]
> 😱3-5分钟的事情花了近3天🤣 [＃12469（评论）](https://github.com/XX-net/XX-Net/issues/12469#issuecomment-482018184)


---------------------------------------------------

这个导入证书导入在哪个目录，好不容易部署好了，连一会儿就挂了

https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA

这个证书的图片显示不了，也看不了。

**Comment by daniu88** [comment]
> 😱3-5分钟的事情花了近3天🤣 [＃12469（评论）](https://github.com/XX-net/XX-Net/issues/12469#issuecomment-482018184)


--------------------------
部署时间特别长，不知道是什么情况哇 @AnyWAT

**Comment by AnyWAT** [comment]
> NAT : restricted (port)
> NAT 特殊行为 : UPNP: 否，PortPreserving: 是

https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890 同一机器不同网络下的XX-Net 正常/不正常的NAT及特殊行为。。。

> 这个导入证书导入在哪个目录，好不容易部署好了，连一会儿就挂了
> 
> https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA

部署？温故而知新👆

> 这个证书的图片显示不了，也看不了。

不明觉厉。。。

> 部署时间特别长，不知道是什么情况哇

部署还是所谓（XX-Net）正常？

**Comment by daniu88** [comment]
> > NAT：限制（端口）
> > NAT特殊行为：UPNP：否，PortPreserving：是
> 
> [＃12455（评论）](https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890)同一机器不同网络下的XX-Net正常/不正常的NAT及特殊行为...（没救了😱）
> 
> > 这个导入证书导入在哪个目录，好不容易部署好了，连一会儿就挂了
> > https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA
> 
> 部署还是名词引用错误？否则，XX-Net正常前能部署个头？导入证书导入...温故而知新（自供链接）👆
> 
> > 这个证书的图片显示不了，也看不了。
> 
> 不明觉厉...
> 
> > 部署时间特别长，不知道是什么情况哇
> 
> 部署还是所谓（XX-净）正常？
> 
> PS：真 - 大 - （ancunbensidenatou）牛🙃
> 证据 - 
> ![图片](https://user-images.githubusercontent.com/37962734/56086183-e65b9880-5e83-11e9-8ce8-0eeb182fcff9.png)
> 
> > 😱3-5分钟的事情花了近3天🤣 [＃12469（评论）](https://github.com/XX-net/XX-Net/issues/12469#issuecomment-482018184)
> 
> ![图片](https://user-images.githubusercontent.com/37962734/56086197-202c9f00-5e84-11e9-8b44-a56537c268d6.png)

昨天链接上了一会儿，后来又不行了

**Comment by AnyWAT** [comment]
同为校园网。。。#12474

**Comment by daniu88** [comment]
> > > NAT：限制（端口）
> > > NAT特殊行为：UPNP：否，PortPreserving：是
> > 
> > 
> > [＃12455（评论）](https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890)同一机器不同网络下的XX-Net的正常/不正常的NAT及特殊行为......（没救了😱）
> > > 这个导入证书导入在哪个目录，好不容易部署好了，一会儿连就挂了
> > > https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA
> > 
> > 
> > 部署还是名词引用错误？否则，XX-Net的正常前能部署个头？导入证书导入...温故而知新（自供链接）👆
> > > 这个证书的图片显示不了，也看不了。
> > 
> > 
> > 不明觉厉...
> > > 部署时间特别长，不知道是什么情况哇
> > 
> > 
> > 部署还是所谓（XX-净）正常？
> > PS：真 - 大 - （ancunbensidenatou）牛🙃
> > 证据 - 
> > ![图片](https://user-images.githubusercontent.com/37962734/56086183-e65b9880-5e83-11e9-8ce8-0eeb182fcff9.png)
> > > 😱3-5分钟的事情花了近3天🤣 [＃12469（评论）](https://github.com/XX-net/XX-Net/issues/12469#issuecomment-482018184)
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/37962734/56086197-202c9f00-5e84-11e9-8b44-a56537c268d6.png)
> 
> 昨天链接上了一会儿，后来又不行了


-----------------------------
-----------------------------
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:5
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:2
scan-ip-thread-num: 88
ip-quality: 968
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


---------------------------------------------------

C:\Users\hasee\Desktop>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

-------------------------------------------------------------


各种不稳定，又要开始扫描ipv6了


> 同为校园网。。。#12474

-----------------------------
-----------------------------
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:5
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:2
scan-ip-thread-num: 88
ip-quality: 968
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


---------------------------------------------------

C:\Users\hasee\Desktop>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

-------------------------------------------------------------


各种不稳定，又要开始扫描ipv6了

**Comment by daniu88** [comment]
> 为同[校园](https://github.com/XX-net/XX-Net/issues/12474)网... [＃12474](https://github.com/XX-net/XX-Net/issues/12474)

----------------------------------------------------------
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 80
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false





=================================
C:\Users\hasee\Desktop>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是



=================================

大哥这个能连上全部靠运气怎么弄？

**Comment by daniu88** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 80
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by daniu88** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 80
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477
