### ISSUE TITLE
非常好奇为啥大佬们不更新了

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12466]
13.1之后就没有更新了，可是墙越来越高，翻过去的难度也越来越大。大佬都去哪了？

**Comment by AnyWAT** [comment]
翻过去的难度也越来越大？#12455

**Comment by MadMaxPayne8964** [comment]
teredo不稳定，原生ipv6被路由黑洞，ipv4被封光。这已经超出了开发者的掌控，没必要更新

**Comment by AeneasZhu** [comment]
除了那几个常见的linux服务器，还有别的teredo隧道吗？

**Comment by AnyWAT** [comment]
有吗？私用，不公开😝

**Comment by hubsocks** [comment]
![3](https://user-images.githubusercontent.com/46856823/55866309-ac07a800-5bb2-11e9-954f-3898826a5e76.png)
![rdd](https://user-images.githubusercontent.com/46856823/55866310-ac07a800-5bb2-11e9-9ab7-a157464b3c10.png)
ipv4还是可以用的。只是最近速度慢了。之前一直能保持9000以上。
如果还有更新的话。希望能解决python27出错关闭的问题，还有去掉一些用不上的功能。

**Comment by AeneasZhu** [comment]
> ![3](https://user-images.githubusercontent.com/46856823/55866309-ac07a800-5bb2-11e9-954f-3898826a5e76.png)
> ![rdd](https://user-images.githubusercontent.com/46856823/55866310-ac07a800-5bb2-11e9-9ab7-a157464b3c10.png)
> ipv4还是可以用的。只是最近速度慢了。之前一直能保持9000以上。
> 如果还有更新的话。希望能解决python27出错关闭的问题，还有去掉一些用不上的功能。

怎么配置IPV4?求教

**Comment by AnyWAT** [comment]
> 怎么配置IPV4?求教

![image](https://user-images.githubusercontent.com/37962734/55869438-14598800-5bb9-11e9-8d69-70c19f539f82.png)

貌似自动还能扫描出几个，仅。。。怕怕。。。

**Comment by ablebodied** [comment]
最新版本的ipv6失效重新恢复后提示网络无法连接，要重启应用才行，我记得以前是可以自动恢复的

**Comment by AnyWAT** [comment]
> 最新版本的ipv6失效重新恢复后提示网络无法连接

不明觉厉。。。

> 要重启应用才行，我记得以前是可以自动恢复的

#12455

**Comment by ablebodied** [comment]
> > 最新版本的ipv6失效重新恢复后提示网络无法连接
> 
> 不明觉厉。。。
> 
> > 要重启应用才行，我记得以前是可以自动恢复的
> 
> #12455

我的意思是我的ipv6有时候会断开，搞一下ipv6恢复了，但是xx-net 的状态不能自己恢复，只能重启xx-net，觉得麻烦而已，记得之前可以自动探测到自己就恢复了

**Comment by AnyWAT** [comment]
貌似 #12455 内的隧道（IP）连接后几乎不会自己断开。。。隧道显示正常但连接池或有效 IP数归零时。。。

**Comment by zhgna08** [comment]
最近X-TUNNEL也经常断了

**Comment by xiaozixun** [comment]
> > > 最新版本的ipv6失效重新恢复后提示网络无法连接
> > 
> > 
> > 不明觉厉。。。
> > > 要重启应用才行，我记得以前是可以自动恢复的
> > 
> > 
> > #12455
> 
> 我的意思是我的ipv6有时候会断开，搞一下ipv6恢复了，但是xx-net 的状态不能自己恢复，只能重启xx-net，觉得麻烦而已，记得之前可以自动探测到自己就恢复了

我的也是，非得重启下enable_ipv6.bat再能使用。

**Comment by AnyWAT** [comment]
> 我的也是，非得重启下enable_ipv6.bat再能使用。

一般首次使用才需要，除非系统（国产）“保护"了神马。试试：#12455 
![image](https://user-images.githubusercontent.com/37962734/55948377-f3f60000-5c82-11e9-88e9-d5ab1818b854.png)

**Comment by xiaozixun** [comment]
> > 我的也是，非得重启下enable_ipv6.bat再能使用。
> 
> 一般首次使用才需要，除非系统（国产）“保护"了神马。试试：#12455
> ![image](https://user-images.githubusercontent.com/37962734/55948377-f3f60000-5c82-11e9-88e9-d5ab1818b854.png)

我的是盗版win7，应该是这个缘故。
图中的操作全都试过，无效。用了https://github.com/XX-net/XX-Net/issues/12370的办法才能使用。

**Comment by AnyWAT** [comment]
> 我的是盗版win7，

😜11-12年的老机都洗白了，没在前2年免费7升10。。。

**Comment by xiaozixun** [comment]
> > 我的是盗版win7，
> 
> 11-12年的老机都洗白了，没在前2年免费7升10。。。

机子太老，懒得管。什么时候炸了买台新的。
话说，我又开始这个连接池为0的错误了。
感觉不是或不单是电脑问题，可能是运营商在作怪。

**Comment by AnyWAT** [comment]
> 可能是运营商在作怪

https://github.com/XX-net/XX-Net/issues/12455 或辅以 https://github.com/CNMan/dnscrypt-proxy-config

**Comment by xiaozixun** [comment]
> > 可能是运营商在作怪
> 
> #12455 或辅以 https://github.com/CNMan/dnscrypt-proxy-config

你能不能拷贝一份你的dnscrypt？我按照说明用了之后无效。

**Comment by AnyWAT** [comment]
> 你能不能拷贝一份你的dnscrypt？我按照说明用了之后无效。

参考：https://github.com/XX-net/XX-Net/issues/12433#issuecomment-479866925

**Comment by xiaozixun** [comment]
> > 你能不能拷贝一份你的dnscrypt？我按照说明用了之后无效。
> 
> 参考：[#12433 (comment)](https://github.com/XX-net/XX-Net/issues/12433#issuecomment-479866925)

我就是看着这个操作的。此外https://github.com/XX-net/XX-Net/issues/12103#issuecomment-481098127  的方法我无法重现。

**Comment by AnyWAT** [comment]
> 我按照说明用了之后无效。

贴 dnscrypt-proxy.log 从最后一行往前到倒数第一个 Stopped 部分

**Comment by xiaozixun** [comment]
> > 我按照说明用了之后无效。
> 
> 贴 dnscrypt-proxy.log 从最后一行往前到倒数第一个 Stopped 部分

我之前无效果的时候已经删掉了，只是在这里说一说情况：
我的就是和Alobe007一样，经历了：完全正常、时好时坏、短期正常、不能用。
至于现在此时就是突然可用，但真正要使用时或正在使用时又没了。所以我才在前面说可能是运营商的问题或我电脑的问题。
这只是说一说我自己的情况，希望能为更多人提供下思路。

**Comment by AnyWAT** [comment]
> 完全正常、时好时坏、短期正常、不能用

及时观察隧道、控制页内 IPv6、有效 IP数及连接池状况

**Comment by Alobe007** [comment]
再提供一个被施加针对性措施的证据：完全一样的系统和设置（就是同一台笔记本），去连接了另一个不常用的网络（并且确定这家人从来不翻墙），立刻满IPv6，无论怎么用，一点不掉。

**Comment by Alobe007** [comment]
而且这家的网络还是经过了一次中继，不是相同网段。说明和NAT，DMZ之类都没有关系。

**Comment by AnyWAT** [comment]
> 说明和NAT。。。之类都没有关系。

否认 https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890 同一机器不同网络下的XX-Net 正常/不正常的NAT及特殊行为：https://github.com/XX-net/XX-Net/issues/12433#issuecomment-479830187

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477

**Comment by Alobe007** [comment]
时间线推断，大概率应该是被茶了吧（包括告之可能受邀）。毕竟作为开发人员，网上蛛丝马迹比较容易被寻到。即使人在海外，亲属也是要考虑到。

所以还是散了吧，寻找其它方式。

感谢默默付出的各位大佬们。

**Comment by AnyWAT** [comment]
#12485
