### ISSUE TITLE
需要导入其他不同的IP吗？

### ISSUE THREAD

**Issue by wa008** [XX-net/XX-Net#12463]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

可用IP一直很少，有时候为0，极其不稳定
总IP数是100和300区别大吗，求大佬们设置的IP都是啥，不知道问题是不是在IP的设置上？

**Comment by AnyWAT** [comment]
> 需要导入其他不同的IP吗？
> 求大佬们设置的IP都是啥

不明觉厉（2次）。。。

> 总IP数是100和300区别大吗

区别有，但更重要的是，为毛：

> 可用IP一直很少，有时候为0，极其不稳定

随时有效 IP数（2+232）/总 IP数234=1，XX-Net 好坏其它2表征：IP延迟及连接池。。。

![image](https://user-images.githubusercontent.com/37962734/55774635-928a3180-5ac8-11e9-9f45-eed49edbb065.png)

**Comment by AnyWAT** [comment]
> 可用IP一直很少，有时候为0，极其不稳定

如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by wa008** [comment]
> > 可用IP一直很少，有时候为0，极其不稳定
> 
> 如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

![Uploading QIAF}Y8HZS[WVC8HP0MQZ`T.png…]()

**Comment by wa008** [comment]
> > 可用IP一直很少，有时候为0，极其不稳定
> 
> 如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

![Uploading QIAF}Y8HZS[WVC8HP0MQZ`T.png…]()
