### ISSUE TITLE
“等待扫描IP，建议开启 IPv6。”请大神帮忙看看，拜谢

### ISSUE THREAD

**Issue by horizon0916** [XX-net/XX-Net#12471]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by horizon0916** [comment]
> 如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）
您好，请问是这样吗？
![微信截图_20190413211045](https://user-images.githubusercontent.com/49540859/56080232-b636da00-5e30-11e9-83e2-cc7574e2e340.png)

**Comment by AnyWAT** [comment]
隧道未连接。。。#12455

**Comment by horizon0916** [comment]
> 隧道未连接。。。#12455

请问应该如何开启隧道？最好有相关流程，本人电脑小白，专业的看不太懂，望不吝赐教，谢谢

**Comment by AnyWAT** [comment]
#12455 温故而知新，几遍就看自己。。。

**Comment by horizon0916** [comment]
> #12455（顶楼）温故而知新，几遍就看自己。。。

您好，我尝试了四个不同的teredo地址，之后再运行netsh int ipv6 show teredo命令，但依然均显示dormant，不知是什么问题

**Comment by AnyWAT** [comment]
> 但依然均显示dormant，不知是什么问题

#12455 如使用域名不理想，可试试使用其 IP。。。

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477
