### ISSUE TITLE
IPV6一直无法开启，求赐教

### ISSUE THREAD

**Issue by MedicalKong** [XX-net/XX-Net#12478]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 498
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
隧道：#12455 或
原生：#12477

**Comment by graffinchai** [comment]
> 隧道：#12455 或
> 原生：#12477

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 148
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


-----------------------------------------------------------------------------------------------------

best server is: win1711.ipv6.microsoft.com.

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config RpcEptMapper start= auto 
[SC] OpenService 失败 5:

拒绝访问。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start RpcEptMapper 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config DcomLaunch start= auto 
[SC] OpenService 失败 5:

拒绝访问。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start DcomLaunch 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config RpcSs start= auto 
[SC] OpenService 失败 5:

拒绝访问。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start RpcSs 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config nsi start= auto 
[SC] ChangeServiceConfig 成功

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start nsi 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config Winmgmt start= auto 
[SC] ChangeServiceConfig 成功

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start Winmgmt 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config Dhcp start= auto 
[SC] ChangeServiceConfig 成功

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start Dhcp 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config WinHttpAutoProxySvc start= auto 
[SC] OpenService 失败 5:

拒绝访问。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start WinHttpAutoProxySvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc config iphlpsvc start= auto 
[SC] ChangeServiceConfig 成功

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>sc start iphlpsvc 
[SC] StartService 失败 1056:

服务的实例已在运行中。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>goto :eof 

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 reset 
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>ipconfig /flushdns 

Windows IP 配置

已成功刷新 DNS 解析缓存。

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>goto :eof 

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>"C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\python27\1.0\pythonw.exe" "C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local\ipv6_tunnel\win_reset_gp.py" 

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface teredo set state type=enterpriseclient servername=win1711.ipv6.microsoft.com. 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy ::1/128 50 0 
对象已存在。



C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy ::1/128 50 0 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy ::/0 40 1 
对象已存在。



C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy ::/0 40 1 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy 2002::/16 30 2 
对象已存在。



C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy 2002::/16 30 2 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy 2001::/32 25 5 
对象已存在。



C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy 2001::/32 25 5 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy ::/96 20 3 
对象已存在。



C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy ::/96 20 3 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 add prefixpolicy ::ffff:0:0/96 10 4 
对象已存在。



C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 set prefixpolicy ::ffff:0:0/96 10 4 
确定。


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>Reg add HKLM\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f 
操作成功完成。 

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>Reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters /v DisabledComponents /t REG_DWORD /d 0 /f 
操作成功完成。 

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>goto :eof 

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>ipconfig /all 

Windows IP 配置

主机名 . . . . . . . . . . . . . : MRQ6WPTZ9JJIQ4R
主 DNS 后缀 . . . . . . . . . . . : 
节点类型 . . . . . . . . . . . . : 混合
IP 路由已启用 . . . . . . . . . . : 否
WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Realtek PCIe GbE Family Controller
物理地址. . . . . . . . . . . . . : 30-5A-3A-EE-AC-E2
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 10:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Microsoft Hosted Network Virtual Adapter
物理地址. . . . . . . . . . . . . : 4A-C2-DD-99-58-DD
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 11:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
物理地址. . . . . . . . . . . . . : 1A-C2-DD-99-58-DD
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 12:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
物理地址. . . . . . . . . . . . . : 2A-C2-DD-99-58-DD
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

以太网适配器 以太网 4:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
物理地址. . . . . . . . . . . . . : 00-FF-EF-C0-A0-98
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN:

连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Qualcomm Atheros AR956x Wireless Network Adapter
物理地址. . . . . . . . . . . . . : 28-C2-DD-99-58-DD
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是
IPv4 地址 . . . . . . . . . . . . : 10.110.12.74(首选) 
子网掩码 . . . . . . . . . . . . : 255.255.192.0
获得租约的时间 . . . . . . . . . : 2019年4月19日 上午 12:54:02
租约过期的时间 . . . . . . . . . : 2019年4月20日 上午 12:54:02
默认网关. . . . . . . . . . . . . : 10.110.0.1
DHCP 服务器 . . . . . . . . . . . : 202.204.40.114
DNS 服务器 . . . . . . . . . . . : 8.8.8.8
8.8.4.4
TCPIP 上的 NetBIOS . . . . . . . : 已启用

以太网适配器 蓝牙网络连接:

媒体状态 . . . . . . . . . . . . : 媒体已断开连接
连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
物理地址. . . . . . . . . . . . . : 28-C2-DD-99-58-DC
DHCP 已启用 . . . . . . . . . . . : 是
自动配置已启用. . . . . . . . . . : 是

隧道适配器 Teredo Tunneling Pseudo-Interface:

连接特定的 DNS 后缀 . . . . . . . : 
描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
DHCP 已启用 . . . . . . . . . . . : 否
自动配置已启用. . . . . . . . . . : 是
IPv6 地址 . . . . . . . . . . . . : 2001:0:2851:fab4:c42:124:f591:f3b5(首选) 
本地链接 IPv6 地址. . . . . . . . : fe80::c42:124:f591:f3b5%14(首选) 
默认网关. . . . . . . . . . . . . : ::
DHCPv6 IAID . . . . . . . . . . . : 201326592
DHCPv6 客户端 DUID . . . . . . . : 00-01-00-01-23-5A-27-86-30-5A-3A-EE-AC-E2
TCPIP 上的 NetBIOS . . . . . . . : 已禁用

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 show teredo 
Teredo 参数
---------------------------------------------
类型 : enterpriseclient
服务器名称 : win1711.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : dormant


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 show route 

发布 类型 跃点数 前缀 索引 网关/接口名称
------- -------- --- ------------------------ --- ------------------------
否 手动 256 ::/0 14 Teredo Tunneling Pseudo-Interface
否 系统 256 ::1/128 1 Loopback Pseudo-Interface 1
否 手动 256 2001::/32 14 Teredo Tunneling Pseudo-Interface
否 系统 256 2001:0:2851:fab4:c42:124:f591:f3b5/128 14 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::/64 22 以太网 4
否 系统 256 fe80::/64 10 以太网
否 系统 256 fe80::/64 12 蓝牙网络连接
否 系统 256 fe80::/64 23 本地连接* 10
否 系统 256 fe80::/64 19 本地连接* 11
否 系统 256 fe80::/64 18 本地连接* 12
否 系统 256 fe80::/64 14 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::f7:d598:7f79:920d/128 22 以太网 4
否 系统 256 fe80::c42:124:f591:f3b5/128 14 Teredo Tunneling Pseudo-Interface
否 系统 256 fe80::11b4:50ee:5615:7ede/128 18 本地连接* 12
否 系统 256 fe80::5555:f99c:b05b:2b44/128 23 本地连接* 10
否 系统 256 fe80::610b:e8bf:c648:90aa/128 19 本地连接* 11
否 系统 256 fe80::613f:e11f:4535:666b/128 12 蓝牙网络连接
否 系统 256 fe80::dda0:89f0:7ace:6ab9/128 10 以太网
否 系统 256 ff00::/8 1 Loopback Pseudo-Interface 1
否 系统 256 ff00::/8 22 以太网 4
否 系统 256 ff00::/8 10 以太网
否 系统 256 ff00::/8 12 蓝牙网络连接
否 系统 256 ff00::/8 23 本地连接* 10
否 系统 256 ff00::/8 19 本地连接* 11
否 系统 256 ff00::/8 18 本地连接* 12
否 系统 256 ff00::/8 14 Teredo Tunneling Pseudo-Interface


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 show interface 

Idx Met MTU 状态 名称
--- ---------- ---------- ------------ ---------------------------
1 75 4294967295 connected Loopback Pseudo-Interface 1
14 75 1280 connected Teredo Tunneling Pseudo-Interface
12 65 1500 disconnected 蓝牙网络连接
23 25 1500 disconnected 本地连接* 10
10 5 1500 disconnected 以太网
19 25 1500 disconnected 本地连接* 11
18 25 1500 disconnected 本地连接* 12
22 35 1500 disconnected 以太网 4


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 show prefixpolicies 
查询活动状态...

优先顺序 标签 前缀
---------- ----- --------------------------------
50 0 ::1/128
40 1 ::/0
30 2 2002::/16
25 5 2001::/32
20 3 ::/96
10 4 ::ffff:0:0/96


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>netsh interface ipv6 show address 

接口 1: Loopback Pseudo-Interface 1

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 首选项 infinite infinite ::1

接口 14: Teredo Tunneling Pseudo-Interface

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
公用 首选项 infinite infinite 2001:0:2851:fab4:c42:124:f591:f3b5
其他 首选项 infinite infinite fe80::c42:124:f591:f3b5%14

接口 12: 蓝牙网络连接

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::613f:e11f:4535:666b%12

接口 23: 本地连接* 10

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::5555:f99c:b05b:2b44%23

接口 10: 以太网

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::dda0:89f0:7ace:6ab9%10

接口 19: 本地连接* 11

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::610b:e8bf:c648:90aa%19

接口 18: 本地连接* 12

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::11b4:50ee:5615:7ede%18

接口 22: 以太网 4

地址类型 DAD 状态 有效寿命 首选寿命 地址
--------- ----------- ---------- ---------- ------------------------
其他 反对 infinite infinite fe80::f7:d598:7f79:920d%22


C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>route print 
===========================================================================
接口列表
10...30 5a 3a ee ac e2 ......Realtek PCIe GbE Family Controller
23...4a c2 dd 99 58 dd ......Microsoft Hosted Network Virtual Adapter
19...1a c2 dd 99 58 dd ......Microsoft Wi-Fi Direct Virtual Adapter
18...2a c2 dd 99 58 dd ......Microsoft Wi-Fi Direct Virtual Adapter #2
22...00 ff ef c0 a0 98 ......TAP-Windows Adapter V9
20...28 c2 dd 99 58 dd ......Qualcomm Atheros AR956x Wireless Network Adapter
12...28 c2 dd 99 58 dc ......Bluetooth Device (Personal Area Network)
1...........................Software Loopback Interface 1
14...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标 网络掩码 网关 接口 跃点数
0.0.0.0 0.0.0.0 10.110.0.1 10.110.12.74 55
10.110.0.0 255.255.192.0 在链路上 10.110.12.74 311
10.110.12.74 255.255.255.255 在链路上 10.110.12.74 311
10.110.63.255 255.255.255.255 在链路上 10.110.12.74 311
127.0.0.0 255.0.0.0 在链路上 127.0.0.1 331
127.0.0.1 255.255.255.255 在链路上 127.0.0.1 331
127.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 127.0.0.1 331
224.0.0.0 240.0.0.0 在链路上 10.110.12.74 311
255.255.255.255 255.255.255.255 在链路上 127.0.0.1 331
255.255.255.255 255.255.255.255 在链路上 10.110.12.74 311
===========================================================================
永久路由:
无

IPv6 路由表
===========================================================================
活动路由:
接口跃点数网络目标 网关
14 331 ::/0 在链路上
1 331 ::1/128 在链路上
14 331 2001::/32 在链路上
14 331 2001:0:2851:fab4:c42:124:f591:f3b5/128
在链路上
14 331 fe80::/64 在链路上
14 331 fe80::c42:124:f591:f3b5/128
在链路上
1 331 ff00::/8 在链路上
14 331 ff00::/8 在链路上
===========================================================================
永久路由:
无

C:\Users\Administrator\Desktop\XX-Net-3.13.1\code\default\gae_proxy\local>goto :eof

**Comment by graffinchai** [comment]
> 隧道：#12455 或
> 原生：#12477

您好，我翻了其他贴也是解决不了IPv6 状态Fail的问题，不管是开启了IP 转换配置服务还是IP Helper，同时IP 转换配置服务开启后，马上就会自动关闭，不管怎么弄都无法取得ipv6，谢谢

**Comment by AnyWAT** [comment]
逐项对比 #12455

**Comment by MedicalKong** [comment]
> > IP 转换配置服务开启后，马上就会自动关闭
> 
> （#10184）正常！但掉入了服务器陷阱！
> 自己逐条对比 #12455 1-4项（新情况，貌似得追加第7项）
> 多余的“本地连接”、“以太网”舍不得删除？

大神，是按照你的执行命令跑一次吗？

**Comment by MedicalKong** [comment]
我看不懂啊，该怎么做啊？还是不行

**Comment by AnyWAT** [comment]
> 我看不懂啊，该怎么做啊？还是不行

如用（Teredo ）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息
