### ISSUE TITLE
网络时断时续怎么办。。。

### ISSUE THREAD

**Issue by zhangbin0922** [XX-net/XX-Net#12470]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:99 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 1756
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zhangbin0922** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.1.4:59879
外部 NAT 映射    : 111.25.214.28:9315


C:\Users\Administrator>

**Comment by AnyWAT** [comment]
如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by zhangbin0922** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.1.4:59879
外部 NAT 映射    : 111.25.214.28:9315


C:\Users\Administrator>

> 如用（远优于原生的）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

贴了。。

**Comment by AnyWAT** [comment]
无需 IP地址的2行——疑似！

除了：
> NAT : restricted

没辙，貌似没问题？#12455

**Comment by zhangbin0922** [comment]
> 无需IP地址的2行 - 隐私！
> 
> 除了：
> 
> > NAT：受限制
> 
> 没辙，貌似没问题？[＃12455](https://github.com/XX-net/XX-Net/issues/12455)

啊啊啊啊啊啊啊 就是一整ipv6数就开始掉 一掉就上不了网 然后等好久好一会再掉。。。。

**Comment by AnyWAT** [comment]
> 貌似没问题？#12455

貌似已关闭某开关、禁用原生？试试：更换其它服务器
或：http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#global_setting 设置级别：改正常为极端。注意此后又会默认打开某开关，关闭它！

**Comment by AnyWAT** [comment]
笔记本如可能，试试有线网络？#12455 #12043 均基于有线网络。。。

**Comment by Blucezhang** [comment]
我还是付费用户啊，感觉今年用起来比较慢啊

**Comment by AnyWAT** [comment]
> 我还是付费用户啊，感觉今年用起来比较慢啊

检查下 http://127.0.0.1:8085/?module=x_tunnel&menu=config 设置——服务器：是否也3个？
如是，禁用后3个貌似一直无效的前端 https://github.com/XX-net/XX-Net/issues/11227#issuecomment-408638834 ，参考 #12455 将GAE（前端）性能。。。

**Comment by AnyWAT** [comment]
Youtube 视频播放效果：原生IPv6好过Teredo 隧道 #12477
