### ISSUE TITLE
Gmail经常上不去，别的网站可以

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12479]
Gmail经常登不上，偶尔还可以，即便登上了也很慢，远不如YouTube, Google等，大佬们是怎么解决的？

**Comment by AnyWAT** [comment]
貌似楼主的XX-Net 性能不佳，隧道 #12455 或原生 #12477 均正常

**Comment by hubsocks** [comment]
XX-Net有些谷歌网站连不了。作者已经说明了这个问题了。有时可以连gmail.com,不行时换其它软件。
