### ISSUE TITLE
不打开xxnet的时候感觉百度变慢了

### ISSUE THREAD

**Issue by wa008** [XX-net/XX-Net#12473]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

我xxnet设置好了，但平常不需要fq的时候，我就没打开xxnet，这时候访问百度，或者其他网页（csdn，kaggle），感觉网速变慢了，特别是百度，慢了很多，是跟什么设置有关系吗，还是我应该一直开着xxnet？求大佬们解答

**Comment by AnyWAT** [comment]
代理设置及使用情况？
