### ISSUE TITLE
推荐 XX-Net 的替代 GotoX

### ISSUE THREAD

**Issue by miketwes** [XX-net/XX-Net#12476]
[ XX-Net](https://github.com/XX-net/XX-Net/)  和 [GotoX](https://github.com/SeaHOH/GotoX) 同样都修改自 goagent, 简单易用.

以 下是本人使用 GotoX 时对 GotoX/config/Config.ini 的一点修改:

    [listen]
    debuginfo = 0

    [gae]
    appid = yourappid1|yourappid2

    [link]
    profile = ipv6
    
    [iplist]
    # google_2p = www.google.com
    # google_cn = www.g.cn|www.google.cn|firebase.google.cn|developers.google.cn    
    google_gae = 
    google_gws = 2607:f8b0:4012:809::2014|2607:f8b0:4009:813::2014|2a00:1450:400e:801::2014|2800:3f0:4001:801::2014|2a00:1450:4001:816::2014|2404:6800:4005:802::2014|2404:6800:4003:804::2014|2a00:1450:4003:804::2014|2404:6800:4003:c02::99|2607:f8b0:4006:801::2014|2404:6800:4005:80d::2014|2a00:1450:4016:806::2014|2a00:1450:4014:80d::2014|2a00:1450:4009:800::2014|2a00:1450:400c:c0c::99|2404:6800:4005:811::2014|2a00:1450:4010:c05::99|2a00:1450:4003:806::2014|2607:f8b0:400b:80d::2014|2800:3f0:4004:801::2014|2a00:1450:4017:809::2014|2a00:1450:4010:c0e::99|2404:6800:4009:803::2014|2a00:1450:4007:815::2014|2404:6800:4009:800::2014|2800:3f0:4001:803::2014|2a00:1450:4009:80d::2014|2607:f8b0:4002:c0c::99|2a00:1450:4009:80e::2014|2a00:1450:4009:813::2014|2a00:1450:4014:800::2014|2607:f8b0:4007:80d::2014|2404:6800:4005:80f::2014|2404:6800:4004:819::2014|2800:3f0:4001:80d::2014|2607:f8b0:4004:802::2014|2800:3f0:4002:808::2014|2404:6800:4009:80c::2014|2404:6800:4009:80b::2014|2a00:1450:4002:80b::2014|2607:f8b0:4012:804::2014|2a00:1450:4001:81d::2014|2800:3f0:4001:810::2014|2607:f8b0:4006:80e::2014|2a00:1450:4001:819::2014|2a00:1450:4013:c07::99|2404:6800:4012:1::2014|2607:f8b0:4000:80f::2014|2404:6800:4005:801::2014|2404:6800:4002:80a::2014|2a00:1450:4019:800::2014|2404:6800:4006:804::2014|2404:6800:4004:81b::2014|2a00:1450:4002:800::2014|2607:f8b0:4012:80a::2014|2607:f8b0:400f:806::2014|2a00:1450:4017:805::2014|2a00:1450:400e:809::2014|2607:f8b0:400b:80e::2014|2607:f8b0:4003:c04::99|2404:6800:4002:802::2014|2800:3f0:4001:80b::2014|2a00:1450:4001:81c::2014|2607:f8b0:4005:808::2014|2404:6800:4003:c00::99|2800:3f0:4005:402::2014|2607:f8b0:4008:811::2014|2a00:1450:4006:806::2014|2a00:1450:4001:818::2014|2404:6800:4004:808::2014|2a00:1450:4002:802::2014|2404:6800:4007:802::2014|2a00:1450:4002:80a::2014|2a00:1450:400d:806::2014|2a00:1450:4009:811::2014|2404:6800:4003:80a::2014|2404:6800:4005:80e::2014|2607:f8b0:4008:805::2014|2c0f:fb50:4003:801::2014|2607:f8b0:4008:806::2014|2a00:1450:400c:c00::99|2607:f8b0:4004:80b::2014|2a00:1450:4007:810::2014|2a00:1450:4001:81a::2014|2607:f8b0:4000:80d::2014|2a00:1450:4010:c07::99|2a00:1450:4019:803::2014|2607:f8b0:4003:c09::99|2a00:1450:4001:825::2014|2800:3f0:4003:c01::99|2800:3f0:4001:808::2014|2a00:1450:4001:817::2014|2607:f8b0:4005:80b::2014|2a00:1450:4003:802::2014|2607:f8b0:4008:80e::2014|2607:f8b0:4008:80d::2014|2607:f8b0:4007:801::2014|2607:f8b0:4005:804::2014|2a00:1450:4010:c0a::99|2a00:1450:400d:803::2014|2607:f8b0:4009:807::2014|2607:f8b0:4004:803::2014|2800:3f0:4001:809::2014|2a00:1450:400e:807::2014|2a00:1450:4005:803::2014|2607:f8b0:4006:818::2014|2800:3f0:4001:817::2014|2607:f8b0:400f:807::2014|2a00:1450:401b:801::2014|2607:f8b0:400a:809::2014|2404:6800:4008:803::2014|2a00:1450:400d:807::2014|2607:f8b0:4000:816::2014|2a00:1450:400d:809::2014|2800:3f0:4001:816::2014|2a00:1450:4006:808::2014|2a00:1450:4002:801::2014|2404:6800:4006:805::2014|2a00:1450:400e:80b::2014|2404:6800:4008:c00::99|2607:f8b0:4020:804::2014|2800:3f0:4002:80b::2014|2607:f8b0:4005:80a::2014|2404:6800:4001:806::2014|2a00:1450:4013:c04::99|2800:3f0:4001:807::2014|2607:f8b0:4009:80d::2014|2a00:1450:4007:811::2014|2607:f8b0:400d:c01::99|2a00:1450:4002:805::2014|2800:3f0:4004:809::2014|2800:3f0:4005:403::2014|2404:6800:4003:808::2014|2a00:1450:4009:803::2014|2a00:1450:4018:803::2014|2607:f8b0:4007:808::2014|2404:6800:4005:800::2014|2404:6800:4005:805::2014|2607:f8b0:4004:80c::2014|64:ff9b::acd9:c299s 1|2a00:1450:400a:801::2014|2607:f8b0:4009:801::2014|2a00:1450:4009:810::2014|2607:f8b0:4007:80c::2014|2404:6800:4006:80a::2014|2a00:1450:4016:809::2014|2a00:1450:4010:c03::99|2607:f8b0:4003:c15::99|2a00:1450:4009:808::2014|2a00:1450:4006:801::2014|2a00:1450:4003:803::2014|2404:6800:4008:802::2014|2607:f8b0:4002:c07::99|2a00:1450:400f:80b::2014|2a00:1450:401b:803::2014|2a00:1450:4009:801::2014|2607:f8b0:400e:c09::99|2404:6800:4009:801::2014|2404:6800:4009:805::2014|2404:6800:4004:81a::2014|2607:f8b0:4004:801::2014|2607:f8b0:4000:817::2014|2607:f8b0:4000:80c::2014|2607:f8b0:4004:80f::2014|2607:f8b0:4003:c17::99|2607:f8b0:4009:803::2014|2404:6800:4006:807::2014|2607:f8b0:400a:808::2014|2607:f8b0:400b:80f::2014|2a00:1450:4009:812::2014|2404:6800:4002:803::2014|2607:f8b0:4020:807::2014|2a00:1450:4016:80a::2014|2800:3f0:4001:805::2014|2607:f8b0:4009:810::2014|2a00:1450:4018:802::2014|2800:3f0:4005:401::2014|2607:f8b0:4003:c12::99|2607:f8b0:4012:805::2014|2404:6800:4007:80f::2014|2607:f8b0:400d:c0f::99|2607:f8b0:4004:805::2014|2a00:1450:4019:801::2014|2404:6800:4006:808::2014|2404:6800:4005:804::2014|2c0f:fb50:4002:802::2014|2a00:1450:401a:805::2014|2a00:1450:4003:80b::2014|2a00:1450:4016:807::2014|2607:f8b0:4004:800::2014|2a00:1450:400e:80d::2014|2404:6800:400a:807::2014|2607:f8b0:4008:810::2014|2607:f8b0:400d:c0b::99|2a00:1450:4007:809::2014|2a00:1450:4017:804::2014|2607:f8b0:4002:c06::99|2404:6800:4004:818::2014|2607:f8b0:4001:c0e::99|2607:f8b0:4001:c1b::99|2a00:1450:4013:c01::99|2800:3f0:4001:814::2014|2404:6800:4007:807::2014|2607:f8b0:400f:800::2014|2404:6800:4004:80b::2014|2a00:1450:401b:805::2014|2607:f8b0:4007:806::2014|2607:f8b0:4005:807::2014|2a00:1450:4003:801::2014|2a00:1450:4006:802::2014|2607:f8b0:4009:80c::2014|2800:3f0:4004:807::2014|2607:f8b0:4009:812::2014|2404:6800:4009:807::2014|2607:f8b0:4008:803::2014|2a00:1450:4005:80a::2014|2a00:1450:4016:808::2014|2800:3f0:4001:80f::2014|2404:6800:4008:c04::99|2a00:1450:4002:808::2014|2404:6800:4001:800::2014|2800:3f0:4002:804::2014|2a00:1450:4013:c03::99|2404:6800:4004:800::2014|2a00:1450:4017:80a::2014|2607:f8b0:400f:805::2014|2607:f8b0:4009:80a::2014|2a00:1450:4017:807::2014|2a00:1450:400e:805::2014|2a00:1450:4005:800::2014|2a00:1450:4007:816::2014|2a00:1450:4003:809::2014|2a00:1450:4001:824::2014|2607:f8b0:4003:c00::99|2a00:1450:400c:c04::99|2404:6800:4004:807::2014|2404:6800:4005:806::2014|2607:f8b0:4002:c00::99|2404:6800:4001:80f::2014|2607:f8b0:4009:811::2014|2a00:1450:4010:c09::99|2607:f8b0:4006:810::2014|2607:f8b0:4002:c08::99|2a00:1450:4009:804::2014|2a00:1450:400e:806::2014|2a00:1450:4016:800::2014|2404:6800:4002:804::2014|2a00:1450:4009:807::2014|2607:f8b0:400a:800::2014|64:ff9b::4a7d:1899s 1|2a00:1450:4010:c0b::99|2800:3f0:4002:809::2014|2607:f8b0:4006:814::2014|2800:3f0:4004:800::2014|2a00:1450:401b:807::2014|2607:f8b0:400b:809::2014|2607:f8b0:4009:809::2014|2a00:1450:4009:80f::2014|2a00:1450:4007:813::2014|2607:f8b0:4002:c09::99|2404:6800:4003:802::2014|2a00:1450:4003:807::2014|2a00:1450:4001:820::2014|2607:f8b0:4006:803::2014|2404:6800:4009:802::2014|2607:f8b0:4006:815::2014|2a00:1450:4009:814::2014|2a00:1450:401b:806::2014|2607:f8b0:4000:811::2014|2404:6800:4012::2014s|2a00:1450:4007:817::2014|2404:6800:4009:80a::2014|2607:f8b0:4005:806::2014|2a00:1450:401b:800::2014|2a00:1450:400e:802::2014|2404:6800:4006:803::2014|2404:6800:4007:80b::2014|2607:f8b0:4009:80b::2014|2607:f8b0:4009:802::2014|2800:3f0:4002:805::2014|2404:6800:4004:80e::2014|2607:f8b0:4000:806::2014|2404:6800:4005:80c::2014|2607:f8b0:4012:80b::2014|2607:f8b0:4004:804::2014|2404:6800:4003:807::2014|2607:f8b0:4000:813::2014|2404:6800:4005:808::2014|2800:3f0:4001:80a::2014|2607:f8b0:4009:806::2014|2404:6800:4001:801::2014|2607:f8b0:4000:808::2014|2a00:1450:4019:802::2014|2404:6800:4004:806::2014|2a00:1450:400d:805::2014|2607:f8b0:4009:80f::2014|2a00:1450:400f:806::2014|2a00:1450:4007:80e::2014|2404:6800:4007:801::2014|2607:f8b0:4006:80f::2014|2a00:1450:401b:802::2014|2a00:1450:400d:808::2014|2404:6800:400a:806::2014|2607:f8b0:4000:804::2014|2800:3f0:4001:815::2014|2404:6800:400a:80b::2014|2607:f8b0:4009:815::2014|2a00:1450:400e:804::2014|2a00:1450:4013:c00::99|2607:f8b0:4008:813::2014|2404:6800:4001:80c::2014|2a00:1450:4001:80b::2014|2404:6800:4001:803::2014|2a00:1450:4018:800::2014|2a00:1450:400f:809::2014|2607:f8b0:4003:c05::99|2a00:1450:400c:c07::99|2a00:1450:401b:804::2014|2a00:1450:4003:805::2014|2404:6800:4001:804::2014|2a00:1450:4001:81b::2014|2a00:1450:4010:c02::99|2607:f8b0:4009:804::2014|2607:f8b0:4002:c02::99|2404:6800:4008:c07::99|2a00:1450:4001:806::2014|2a00:1450:4002:807::2014|2a00:1450:4007:808::2014|2607:f8b0:4003:c19::99|2a00:1450:400f:80c::2014|2607:f8b0:4003:c01::99|2607:f8b0:4005:802::2014|2404:6800:4004:80c::2014|2607:f8b0:4006:804::2014|2404:6800:4009:804::2014|2a00:1450:400e:808::2014|2607:f8b0:4007:80e::2014|2a00:1450:400a:802::2014|2a00:1450:4001:815::2014|2404:6800:4009:808::2014|2404:6800:4005:80a::2014|2a00:1450:400f:808::2014|2a00:1450:4001:808::2014|2404:6800:4009:80e::2014|2a00:1450:4016:80b::2014|2404:6800:4005:80b::2014|2a00:1450:4007:80c::2014|2607:f8b0:4006:819::2014|2607:f8b0:400b:80c::2014|2a00:1450:4002:809::2014|2607:f8b0:4000:814::2014|2404:6800:4009:809::2014|2404:6800:4005:810::2014|2607:f8b0:4007:804::2014|2a00:1450:4006:807::2014|2a00:1450:400f:80a::2014|2607:f8b0:400f:804::2014|2607:f8b0:4007:800::2014|2607:f8b0:4004:80e::2014|2a00:1450:4009:80c::2014|2607:f8b0:4000:812::2014|2404:6800:4001:80d::2014|2404:6800:4007:808::2014|2404:6800:4005:807::2014|2a00:1450:4014:80c::2014|2607:f8b0:4000:815::2014|2800:3f0:4003:c00::99|2a00:1450:400f:807::2014|2404:6800:4009:806::2014|2a00:1450:4017:80b::2014|2800:3f0:4004:806::2014|2404:6800:4005:803::2014|2607:f8b0:4000:80e::2014|2607:f8b0:400a:803::2014|2a00:1450:4007:805::2014|2404:6800:4008:c01::99|2404:6800:4009:80d::2014|2404:6800:400a:80c::2014|2a00:1450:400e:80a::2014|2607:f8b0:4006:811::2014|2a00:1450:4016:80d::2014|2607:f8b0:4000:802::2014|2404:6800:4004:809::2014|2a00:1450:4007:812::2014|2404:6800:4004:80a::2014|2a00:1450:4017:806::2014|2a00:1450:4017:808::2014|2800:3f0:4002:80a::2014|2a00:1450:4005:80b::2014|2a00:1450:4002:806::2014|2607:f8b0:4006:802::2014|2800:3f0:4001:802::2014|2607:f8b0:4005:805::2014|2a00:1450:4007:814::2014|2607:f8b0:4008:802::2014|2800:3f0:4004:805::2014|2a00:1450:4007:80a::2014|2a00:1450:4009:802::2014|2607:f8b0:4004:811::2014|2404:6800:4003:c01::99|2404:6800:4007:800::2014|2a00:1450:4001:821::2014|2404:6800:4004:801::2014|2607:f8b0:4008:80c::2014|2404:6800:4004:80f::2014|2607:f8b0:400e:c03::99|2404:6800:4003:c04::99|2404:6800:4006:802::2014|2607:f8b0:4006:81a::2014|2800:3f0:4001:806::2014|2a00:1450:4009:815::2014|2607:f8b0:4007:802::2014|2404:6800:4008:801::2014|2607:f8b0:4002:c03::99|2a00:1450:400e:803::2014|2607:f8b0:4007:80b::2014|2a00:1450:4007:80f::2014|2607:f8b0:4004:80d::2014|2800:3f0:4004:808::2014|2a00:1450:4010:c0f::99|2a00:1450:4009:809::2014|2404:6800:4006:806::2014|2404:6800:4003:c03::99|2404:6800:4004:80d::2014|2607:f8b0:4006:813::2014|2a00:1450:4010:c08::99|2607:f8b0:4009:808::2014|2a00:1450:4017:800::2014|2a00:1450:4014:801::2014|2a00:1450:4003:80a::2014|2607:f8b0:4020:805::2014|2607:f8b0:4012:808::2014|2a00:1450:400e:80c::2014|2a00:1450:4001:81f::2014|2800:3f0:4001:80c::2014|2607:f8b0:4007:809::2014|2607:f8b0:4006:812::2014|2a00:1450:4010:c0d::99|2607:f8b0:400b:808::2014|2a00:1450:4007:80d::2014|2800:3f0:4005:400::2014|2a00:1450:4017:801::2014|2607:f8b0:4006:800::2014|2607:f8b0:4009:816::2014|2404:6800:400a:808::2014|2607:f8b0:400a:804::2014|2607:f8b0:4004:810::2014|2c0f:fb50:4002:803::2014|2a00:1450:400c:c08::99|2800:3f0:4003:c02::99|2404:6800:4009:810::2014|2404:6800:4005:809::2014|2a00:1450:4010:c01::99|2607:f8b0:4005:801::2014
    
    [filter]
    action = 4

    [picker/gae]
    enable = 0

    [picker/gws]
    enable = 0

**Comment by miketwes** [comment]
![2019-04-15_734x68](https://user-images.githubusercontent.com/6849681/56106265-e9818200-5f72-11e9-8f11-0d3f5b200787.png)

![2019-04-15_378x263](https://user-images.githubusercontent.com/6849681/56106348-3d8c6680-5f73-11e9-8269-fc95d5d6965a.png)

**Comment by SeaHOH** [comment]
从技术上讲，XX 要好得多；功能上，是侧重不同；使用上，也是 XX 要简单得多。
所以，这绝不是 XX 的替代。

使用它需要一点基础的网络知识，操作上不像 XX 这么傻瓜化，
所以对那种特小白的很不友好，没有专门推荐过就是因为这。
