### ISSUE TITLE
什么情况？有过几次了

### ISSUE THREAD

**Issue by AnyWAT** [XX-net/XX-Net#12485]
可固定到任务栏的原装快捷方式被32Win10Pro几次报毒😱 @xxnet 

![image](https://user-images.githubusercontent.com/37962734/56401701-cca7c000-628c-11e9-8604-a9bd060443e0.png)
![image](https://user-images.githubusercontent.com/37962734/56401731-f5c85080-628c-11e9-98a5-76ba18962337.png)
![image](https://user-images.githubusercontent.com/37962734/56401900-b817f780-628d-11e9-99ef-36fa6b24c8ed.png)
![image](https://user-images.githubusercontent.com/37962734/56401921-d120a880-628d-11e9-8b5f-6efe568930e2.png)

Function CurrentPath()
    strPath = Wscript.ScriptFullName
    Set objFSO = CreateObject("Scripting.FileSystemObject")
    Set objFile = objFSO.GetFile(strPath)
    CurrentPath = objFSO.GetParentFolderName(objFile)
End Function

Function CurrentVersion()
    strCurrentPath = CurrentPath()
    strVersionFile = strCurrentPath & "/code/version.txt"

    Set fso = CreateObject("Scripting.FileSystemObject")
    If (fso.FileExists(strVersionFile)) Then

        Set objFileToRead = CreateObject("Scripting.FileSystemObject").OpenTextFile(strVersionFile,1)
        CurrentVersion = objFileToRead.ReadLine()

        version_path = strCurrentPath & "/code/" & CurrentVersion & "/launcher/start.py"
        If( Not fso.FileExists(version_path) ) Then
            CurrentVersion = "default"
        End If

        objFileToRead.Close
        Set objFileToRead = Nothing
    Else
       CurrentVersion = "default"
    End If

End Function

Function isConsole()
    Set objArgs = Wscript.Arguments
    'WScript.Echo objArgs.Count
    'WScript.Echo objArgs(0)
    isConsole = 0
    If objArgs.Count > 0 Then
        if objArgs(0) = "console" Then
            isConsole = 1
        End If
    End If
End Function

strCurrentPath = CurrentPath()
strVersion = CurrentVersion()
Dim strArgs
quo = """"

If isConsole() Then
    python_cmd = "python.exe"
Else
    python_cmd = "pythonw.exe"
End If

strExecutable = quo & strCurrentPath & "\code\" & strVersion & "\python27\1.0\" & python_cmd & quo
strArgs = strExecutable & " " & quo & strCurrentPath & "\code\" & strVersion & "\launcher\start.py" & quo
'WScript.Echo strArgs

Set oShell = CreateObject ("Wscript.Shell")
oShell.Run strArgs, isConsole(), false

**Comment by xxnet** [comment]
开源的代码，不可能有问题的，上面也没有被改过。

估计是有人恶意投诉导致的。

大家试试向微软提交报告：
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by AnyWAT** [comment]
万分感谢！
