### ISSUE TITLE
求点流量，1个G就行，谢谢大神

### ISSUE THREAD

**Issue by wpf940997721** [XX-net/XX-Net#12480]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by wpf940997721** [comment]
邮箱 wpf940997721@gmail.com

**Comment by AnyWAT** [comment]
已出。。。

**Comment by wpf940997721** [comment]
> 已出。。。

非常感谢

**Comment by qibin8687** [comment]
我也想求点流量，量不在多，有效期长点最好！当然，也不强求，有就不错了，谢谢各位好汉！
binarychee@gmail.com

**Comment by github20190416** [comment]
同求

**Comment by qibin8687** [comment]
> 
> 
> 我也想求点流量，量不在多，有效期长点最好！当然，也不强求，有就不错了，谢谢各位好汉！
> [binarychee@gmail.com](mailto:binarychee@gmail.com)

已经有好汉给我续上啦！2.87G到今年年底，嘿嘿

**Comment by zxmb** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

**Comment by galaxy9064** [comment]
同求大神转一些长期流量，平时用的不多，1G就行。或者可以按流量和剩余时间分担费用，目前的套餐实在是用不了那么多，买了感觉有些浪费。xiphias14@gmail.com
