### ISSUE TITLE
部署到局域网某台电脑，ip设置0.0.0.0，其他电脑通过这台代理会出现隐私错误？

### ISSUE THREAD

**Issue by netcan** [XX-net/XX-Net#1248]
部署到局域网某台电脑，ip设置0.0.0.0，然后路由器转发，其他电脑已安装证书连接会出现隐私错误？

**Comment by xyuanmu** [comment]
手动导入证书，XX-Net\data\gae_proxy\CA.crt，右键 - 安装证书

**Comment by xxnet** [comment]
其他电脑需要导入这台电脑XX-net 目录下 data/gae_proxy/CA.crt 证书

在 2015年10月19日 下午3:48，Netcan <notifications@github.com>写道：

**Comment by netcan** [comment]
哦，可以了，谢谢，原来证书是生成的。。

**Comment by tigeryangjin** [comment]
请问，iphone如何导入证书？
