### ISSUE TITLE
还是无法使用

### ISSUE THREAD

**Issue by mawuxiaoqu** [XX-net/XX-Net#12486]
类型                    : enterpriseclient (Group Policy)
服务器名称              : 83.170.6.76 (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 是

路由器已经开启dmz和upnp 网卡已关闭ipv6 无论换那个teredo基本情况一样，都是几分钟才扫描到ip，但是一开需要代理的网站有效ip就会变成0，然后在等几分钟又有有效ip，但开网页一样又变成0了

**Comment by AnyWAT** [comment]
> 路由器已经开启dmz

https://github.com/XX-net/XX-Net/issues/12043#issuecomment-453709169

> NAT : restricted
> NAT 特殊行为 : UPNP: 否，PortPreserving: 是

https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890 同一机器不同网络下的XX-Net 正常/不正常的NAT及特殊行为。。。

**Comment by mawuxiaoqu** [comment]
![1](https://user-images.githubusercontent.com/49009544/56403721-4d6aba00-6295-11e9-8580-e6906ca83018.png)
![2](https://user-images.githubusercontent.com/49009544/56403722-4d6aba00-6295-11e9-8786-e3c77abb7afa.png)
路由器室已经全部开启了的，
teredo的几个ip我也全部试过还是一样的情况

**Comment by AnyWAT** [comment]
> 类型 : enterpriseclient (Group Policy)
> 服务器名称 : 83.170.6.76 (Group Policy)

试试去掉括号及其内容？完整的应该其后面2参数也得带括号。。。

> teredo的几个ip我也全部试过还是一样的情况

更换服务器后得随即检查 IP、稍候。。。
隧道不行，或使用原生？

**Comment by hubsocks** [comment]
teredo本来就是应用不需要DMZ,upnp就能连接ipv6的。当下通过teredo连接ipv6封锁干扰很严重。xx-net用ipv4没任何问题。

**Comment by AnyWAT** [comment]
> 当下通过teredo连接ipv6封锁干扰很严重

扫描出 IP很慢或许就是其一。或借鉴 #12477 之4、将XX-Net3.12.2或以前版本、简化前的。。。（刚测试，貌似有效果：其它任何参数不变，扫描出 IP的速度明显加快，与以前正常时相当）

**Comment by Alobe007** [comment]
就是这样，通病。基本都是去年底今年初开始的。
估计这段时间，运营商那里部署了什么新玩艺儿。
貌似办法是：一旦检测到某用户用XX连接外网，就封一段时间该用户扫到或可用的IP。所以改天再来时，好像又有可用IP了。但一连外网，会再次逐个减少直至为0。
运营商友好型的或暂没有被针对的，就一切正常。

**Comment by Upreak-Jkee** [comment]
也许是年纪大了，渐渐变得懒得折腾，喜欢简单、稳定、不张扬的一切。
推荐一个服务，“加速度”，一年才百来块钱。
我用了2个月，挺稳定的。使用此链接，你我都能得到20%的优惠
http://jiasd.us/9449

**Comment by Upreak-Jkeey** [comment]
也许是年纪大了，渐渐变得懒得折腾，喜欢简单、稳定、不张扬的一切。
推荐一个服务，“加速度”，一年才百来块钱。
我用了2个月，挺稳定的。使用此链接，你我都能得到20%的优惠
http://t.cn/EJ1yQN8

**Comment by zhangjiefengd** [comment]
试试

**Comment by mawuxiaoqu** [comment]
关闭了dmz后就可以正常使用了...好奇怪 就是现在下bt端号没有开放很慢

**Comment by AnyWAT** [comment]
> 关闭了dmz后就可以正常使用了...好奇怪

https://github.com/XX-net/XX-Net/issues/12037#issuecomment-453085047
https://github.com/XX-net/XX-Net/issues/12085#issuecomment-454386459
https://github.com/XX-net/XX-Net/issues/12085#issuecomment-454447946

**Comment by AnyWAT** [comment]
@jiao142857 https://github.com/XX-net/XX-Net/issues/12103#issuecomment-485279938
netsh interface ipv6 show interface interface="Teredo Tunneling Pseudo-Interface" 默认， 隧道一直正常XX-Net 一直正常。。。

![image](https://user-images.githubusercontent.com/37962734/56488905-82377500-6512-11e9-9f20-9268bec100e8.png)

**Comment by jiao142857** [comment]
> netsh interface ipv6 show interface interface="Teredo Tunneling Pseudo-Interface" 默认， 一直“当前设备可能无法正常使用 teredo 隧道，NAT 类型是 symmetric！”，但隧道（#12455）一直正常XX-Net 一直正常。。。也可正常玩玩原生：#12477
还有一个重要的原因:路由器或者光猫.
    我用的是联通,原来邻居也是联通(同一个人给安装的,时间前后不知道)但最近修路他家好像断线了,我只好在issues里找找方法(上边的那些命令等).
    但是我今天又找到一位"慷慨"的邻居他家是电信的,还是用你的那些设置好了...

**Comment by AnyWAT** [comment]
貌似有参数会变，已看到3个数——可访问时间 : 7500 毫秒，前述图示21500，第二次介于前二者之间。
