### ISSUE TITLE
我开启IPV6的方法和无法扫描求组大神

### ISSUE THREAD

**Issue by squallyang520** [XX-net/XX-Net#12489]
没这么用过这套留言讨论板，不知道贴图的格式对不对。

首先描述一下上网环境。
电信ADSL光纤上网。因为家里的路由器不支持IPV6，直接笔记本接网线到光猫上拨号上网。
然后死活宽带拨号获取不到IPV6，打开https://test-ipv6.com
测试失败无IPV6。
后来百度了N多帖子。有说去光猫里折腾的。
找电信客服要了工程管理账号密码进入光猫的配置段（不是光猫上贴的账号密码，那个无效）
开启了拨号上网IPV4&IPV6的双策略。

然后拨号如下图所示，直接提示有IPV6地址，

<a href="https://imgchr.com/i/EFn9r4"><img src="https://s2.ax1x.com/2019/04/21/EFn9r4.md.png" alt="EFn9r4.png" border="0" /></a>

打开https://test-ipv6.com/
测试通过10/10。
<a href="https://imgchr.com/i/EFuctI"><img src="https://s2.ax1x.com/2019/04/21/EFuctI.md.png" alt="EFuctI.png" border="0" /></a>
然后XXNET是最新的3.13.1版解压缩右键管理员运行bat加载的。

可是诊断信息一直如下所示。无论等多久都无法扫描到任何IP。
求助大神。。。我没有用私人的ID用的公用ID是因为我也搞不清我自己的部署服务端是否是最新的端了。想重新用公共ID部署一下。

以前我直接光猫拨号没获取到IPV6反倒有一两次扫到IP。但是非常不稳定。
所以今天想更新一下部署端，结果从早上折腾到现在。
现在是ADSL直接拨号获取到IPV6也扫不到IP了。。。彻底懵了。。。

一直红字提示
等待扫描 IP，建议开启 IPv6。求助！

<img src="https://s2.ax1x.com/2019/04/21/EFKtbQ.png" alt="EFKtbQ.png" border="0" />
------------------------------------------------
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by AnyWAT** [comment]
Teredo 隧道：#12455

**Comment by AnyWAT** [comment]
> 为我也搞不清我自己的部署服务端是否是最新的端了

😱时光倒流了么？https://github.com/XX-net/XX-Net/issues/12488#issuecomment-485223617

**Comment by squallyang520** [comment]
谢谢你哈，我不是攻城狮自己DIY能力也有限的很。。。很吃力的在折腾电脑。。。
我现在显示
Teredo 隧道 | 休眠（未连接）
看了你的贴子估计是这里出的毛病。。。
但是还没看明白该怎么搞😱

**Comment by AnyWAT** [comment]
> 但是还没看明白该怎么搞😱

Teredo 隧道：#12455 
1、2、3、。。。
或
原生：#12477
1、2、3、。。。

**Comment by hubsocks** [comment]
Teredo 隧道 和原生ipv6连谷歌ipv6都是工信部最点审查对像。ipv6更有利于审查。今后强化IPv6网络就绪专项行动。你觉得你能稳定连接谷歌？

**Comment by squallyang520** [comment]
小白表示看过了AnyWAT的诸多帖子后已经是一脸懵逼了。。。。
不明觉厉。。。。
虽然不明白但是还是觉得很厉害。。。。
我发现我的智商处在看视频操作的步骤了。。。
找不到地方充智商。。。看来我要放弃XXnet了。。。

**Comment by boxsnake** [comment]
@squallyang520 AnyWAT的回答大多数文不达意，感觉像是个未完成的人工智障AI。如果你能理解它的话，那你的理解能力才是真的有问题了。

**Comment by boxsnake** [comment]
> 小白表示看过了AnyWAT的诸多帖子后已经是一脸懵逼了。。。。
> 不明觉厉。。。。
> 虽然不明白但是还是觉得很厉害。。。。
> 我发现我的智商处在看视频操作的步骤了。。。
> 找不到地方充智商。。。看来我要放弃XXnet了。。。

@squallyang520 AnyWAT的回答，感觉大部分不知道从哪里抄来的，还有自己造的乱七八糟的句式和词语。看起来很高大上，但是实际就是蒙到了60%的东西和提问者问的有点关系。

**Comment by boxsnake** [comment]
你可以看下自己的服务器是不是微软的ipv6.microsoft开头那个。微软的服务器是Windows自带的默认服务器，但是无法ping通，也无法当XX-Net的IPv6 Teredo隧道使用。

**Comment by AnyWAT** [comment]
原来是厉害的码农😱

**Comment by yyuurrii34** [comment]
原生ipv6别做梦，已人原理上断定。
https://user-images.githubusercontent.com/46563122/54895232-94b19500-4ef9-11e9-9d37-43faab50cf36.jpg

**Comment by AnyWAT** [comment]
> 原生ipv6别做梦，已从原理上断定。

![image](https://user-images.githubusercontent.com/37962734/56482740-50191980-64f8-11e9-9db2-58edc6824b3b.png)

https://github.com/XX-net/XX-Net/issues/12486#issuecomment-485296360 关闭了dmz后就可以正常使用了...好奇怪

**Comment by boxsnake** [comment]
https://github.com/XX-net/XX-Net/issues/11931#issuecomment-450510349
https://github.com/XX-net/XX-Net/issues/11931#issuecomment-450510447

**Comment by boxsnake** [comment]
@squallyang520 
打开批处理模式，命令行输入其中一条：
```bash
netsh interface teredo set state enterpriseclient server=teredo.trex.fi
netsh interface teredo set state enterpriseclient server=teredo.iks-jena.de
netsh interface teredo set state enterpriseclient server=teredo.remlab.net
netsh interface teredo set state enterpriseclient server=teredo2.remlab.net
netsh interface teredo set state enterpriseclient server=teredo-debian.remlab.net
```

**Comment by taoeternal2018** [comment]
> @squallyang520
> 管理员模式打开命令行提示符（`cmd.exe`），命令行输入其中一条：
> 
> ```shell
> netsh interface teredo set state enterpriseclient server=teredo.trex.fi
> netsh interface teredo set state enterpriseclient server=teredo.iks-jena.de
> netsh interface teredo set state enterpriseclient server=teredo.remlab.net
> netsh interface teredo set state enterpriseclient server=teredo2.remlab.net
> netsh interface teredo set state enterpriseclient server=teredo-debian.remlab.net
> ```

Cool! That works for me, thank you so much
