### ISSUE TITLE
这几天经常会自动退出

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#12493]
xxtunel, 3.13.1 版（最新版），win7系统。

从前天开始，经常会自动退出，说什么python程序被迫中断之类的。

而且最近的速度也不稳定，时断时续。后一个问题可以忍受，前一个怎么破解？

**Comment by AnyWAT** [comment]
偶尔自动退出，不明，再启动即可。速度也不稳定？不必忍受：#12455
