### ISSUE TITLE
ivp6总数怎么增加

### ISSUE THREAD

**Issue by wzzseu** [XX-net/XX-Net#12497]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12455#issue-430262132 点击链接：增大[总 IP数](https://github.com/XX-net/XX-Net/issues/11291#%E8%87%AA%E8%AE%BE%E6%80%BBIP%E6%95%B0)为[200-250](https://github.com/XX-net/XX-Net/issues/12184#issuecomment-458495848)，
