### ISSUE TITLE
CA证书显示失败，导入也没用

### ISSUE THREAD

**Issue by smallstone000** [XX-net/XX-Net#12494]
![无标ssss题](https://user-images.githubusercontent.com/49931421/56629977-1bd16480-6682-11e9-8b23-604d00491eb8.png)

**Comment by smallstone000** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:95 ipv4:0 ipv6:95
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 346
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> CA证书显示失败，导入也没用

与导不导入无关，或因

> worker: h1:0 h2:0

貌似验证证书的 *.deja.com 无法通过GAE检测。其它 https://github.com/XX-net/XX-Net/issues/12483#issuecomment-486052268
