### ISSUE TITLE
感谢AnyWAT热心教导。XXnet3.13.1用不了的直接进来看看就好。

### ISSUE THREAD

**Issue by squallyang520** [XX-net/XX-Net#12490]
我首次知道XXnet是在2015年吧，风风雨雨也四年多了。其实我用的不是很多，就是同步Google收藏夹和偶尔上个油管。
自从去年IPV4被封杀，IPV6我就折腾了好久。因为不是常用，1月用个2-3次。
再加上爱追最新的WIN10重装系统。多次有装好系统怎么都弄不出IPV6的情况。
今天又花了一天的时间在折腾这东西。。。

以往XXnet，右键管理员运行bat，自动装证书，手动装个SwitchyOmega。导入自己的ID，放个一会就好了。

在此十分感谢AnyWAT热心教导，翻看了他很多帖子。。。
发现XXnet已经越来越复杂了。。。我电信ADSL拨号有原生IPv6的都无法无脑使用了。。。。

不是很适合我们这种动手能力和理解能力相对不足的人。。。。

感谢AnyWAT热心教导。拜拜了XXnet。。。有空回来看看。

**Comment by lefantian** [comment]
不知道现在那种好用，好像很多付费的也不是很稳定，现在xxnet大不如从前了，大神们也累了，真是土匪有技术谁也挡不住

**Comment by AnyWAT** [comment]
> 好像很多付费的也不是很稳定

如果 http://127.0.0.1:8085/?module=x_tunnel&menu=config 设置：服务器也只是那3个（原来2个，近期增加了1个？），想稳定，得保证GAE（前端）稳定，禁用后3个无效的前端 #12455

**Comment by AnyWAT** [comment]
> 再加上爱追最新的WIN10重装系统。多次有装好系统怎么都弄不出IPV6的情况。

https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481141623

**Comment by AnyWAT** [comment]
> XXnet3.13.1用不了的直接进来看看就好

#12488
#12489

**Comment by yyuurrii34** [comment]
原生ipv6别做梦，已从原理上断定。
https://user-images.githubusercontent.com/46563122/54895232-94b19500-4ef9-11e9-9d37-43faab50cf36.jpg
#12103

**Comment by AeneasZhu** [comment]
XX-NET还是能用的，速度勉强凑合。墙越来越高了，各大公益机场挤满了翻墙难民，SSR节点都不稳定。稍微有点动手能力的推荐VPN Gate 吧，速度还行。这里贴个镜像站点http://74.208.111.92:40863/cn/

PS.2019有各种周年纪念日，墙的高度可能会创新高，多准备几款梯子备用。现在在墙外的推荐安装TOR作为备用，速度是慢，但是坚挺。

**Comment by AnyWAT** [comment]
> 原生ipv6别做梦，已从原理上断定。

![image](https://user-images.githubusercontent.com/37962734/56482740-50191980-64f8-11e9-9db2-58edc6824b3b.png)

https://github.com/XX-net/XX-Net/issues/12477#issuecomment-484742198 

https://github.com/XX-net/XX-Net/issues/12486#issuecomment-485296360 关闭了dmz后就可以正常使用了...好奇怪

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 或
原生：#12477

**Comment by FergonXie** [comment]
我的网络环境是移动宽带，一直以来都非常稳定，win7、fedora、ubuntu下都一样。 而且，路由器dmz和UPnP都是关闭的。

**Comment by AnyWAT** [comment]
> 我的网络环境是移动宽带，一直以来都非常稳定，win7、fedora、ubuntu下都一样。 而且，路由器dmz和UPnP都是关闭的。

只有Win7/10与你同乐😂

**Comment by urugang** [comment]
没明白为什么原理上断定原生没戏。
虽然我这确实是原生不行，teredo可用。
