### ISSUE TITLE
自己搭了一个ssr服务端

### ISSUE THREAD

**Issue by gfvre123** [XX-net/XX-Net#12498]
花了几百大洋买了一个服务器，要用的朋友可以加我

**Comment by Justes** [comment]
大佬怎么加你啊？

**Comment by gfvre123** [comment]
你加我微信：gfvre

**Comment by Justes** [comment]
用户不存在

**Comment by gfvre123** [comment]
微信号：gfvre123

**Comment by yyuurrii34** [comment]
ssr也差不多快挂了。推荐使用trojan-gfw和v2ray+websocks+tls+http/2

**Comment by errolyan** [comment]
添加不上您。我手机微信：13075851954




------------------ 原始邮件 ------------------
发件人: "gfvre123"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 下午4:50
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [XX-net/XX-Net] 自己搭了一个ssr服务端 (#12498)




你加我微信：gfvre
