### ISSUE TITLE
BJ移动宽带分配原生IPv6地址造成的问题及解决方案

### ISSUE THREAD

**Issue by EvenDorton** [XX-net/XX-Net#12491]
**首**先北漂真惨，受自建公寓拆迁、隔断房查治等“感人“政策的影响，我也经历了两次自己搬家，房租水涨船高，用的网络也从300M独享联通到100M有线电信到100M无线移动。。。
**联**通原生IPv6，电信isatap到Tsinghua，移动Teredo，前两周用的挺好（移动网络Teredo延迟真的非常不错)，这两周不知道怎么回事有IPv6数量，但一连接就自己掉没...
本地连接IPv6状态也是Internet，我稍微思索了一下，然后进光猫看了看，发现BJ地区移动已经分配IPv6地址了，所以问题就发生了，这是运营商给你的毒苹果，我fo了，所以解决也挺简单的，光猫关闭IPv6的获取
![图](https://user-images.githubusercontent.com/14258692/56491396-f118cc00-651a-11e9-8bd8-64e9507a90e2.png)

**Comment by AnyWAT** [comment]
移动光猫直接电脑，Teredo 隧道：#12455 或原生：#12477
