### ISSUE TITLE
路由器的upnp似乎是必要的

### ISSUE THREAD

**Issue by souyaf** [XX-net/XX-Net#12503]
在公司一直没什么问题，但在家布置一直用不起，折腾了很久，印象中看wiki的时候提到路由器的UPnp功能似乎是有影响的（因为公司的路由器通常要好一些，但自己在家用的未必有这功能，我98元tplink就不行），下决心换了个路由器，结果一样的配置就能使用了。当然未必是UPNP功能起了作用，我用的是菊花厂pro2（不知道有没有广告费用）
服务器用的是下图的，默认的WIN7服务器都不能用了，在公司用的也是这个。不是专业的，小白，仅供参考
![image](https://user-images.githubusercontent.com/49990134/56747512-b3cd6c00-67b0-11e9-81b8-90ada0bc881d.png)
![image](https://user-images.githubusercontent.com/49990134/56747734-16bf0300-67b1-11e9-84d9-75c55343a531.png)

**Comment by AeneasZhu** [comment]
我的是校园网可以用，但4G热点和家庭网不行

**Comment by souyaf** [comment]
好像也不是这个问题，IP又全部掉光了，不知道是啥原因，因为过了12点了？

**Comment by AnyWAT** [comment]
> 好像隧道不是很稳定

基本稳定 #12455

**Comment by souyaf** [comment]
> 好像隧道不是很稳定，但连接上之后就能用了

又不行了，用了半小时后IP就掉光了，不停的看teredo状态可以看到隧道不是很稳定，时断时续，有时显示无法通过UDP连接teredo服务器。在连接上后又恢复了一会，又刷满了IP，之后就一直不行了，这个时候反而一直显示隧道是正常的，搞不懂哪里出了问题，什么也没调整，就好像GFW也在调试一样，用了一会就挂了

**Comment by AnyWAT** [comment]
如用（Teredo ）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by souyaf** [comment]
> > 好像隧道不是很稳定，但连接上之后就能用了
> 
> 又不行了，用了半小时后IP就掉光了，不停的看teredo状态可以看到隧道不是很稳定，时断时续，有时显示无法通过UDP连接teredo服务器。在连接上后又恢复了一会，又刷满了IP，之后就一直不行了，这个时候反而一直显示隧道是正常的，搞不懂哪里出了问题，什么也没调整，就好像GFW也在调试一样，用了一会就挂了

又可以用了，看来只是不太稳定，总体上换了路由之后比原来好了很多，之前完全用不了

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12490#issuecomment-486902620
