### ISSUE TITLE
校园网最后阵地沦陷--真的不能再用了

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12504]
家庭网不能用，4G热点断断续续不能用，今天连XX-NET最后一块阵地校园网也失守了，换哪一个服务器都不行。虽然有别的可以替代，但对XX-NET还是有一种说不出的难以割舍之情。大佬们也已经不更新了，只剩下我们这些门外汉摸着石头瞎捣弄。从13.1开始，就隐约感觉到XX-NET的大限将至，但每天仍不停捣弄，希望再多用一天。

GoAgent伴随了我整个大学时光，感觉是时候真的说再见了。

希望这一次XX-NET再一次狠狠打我脸，没多久又好起来

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ablebodied** [comment]
唉，果然不是我自己的原因，IP直往下掉，之前400，现在300还往下掉，来的好突然

**Comment by AnyWAT** [comment]
> XX-NET的大限将至

😱真的么？正常的Teredo 隧道：#12455 或原生：#12477

**Comment by Akalusi** [comment]
坐标广州校园网，昨天晚上开始的确不能用了

**Comment by AeneasZhu** [comment]
> 坐标广州校园网，昨天晚上开始的确不能用了，但是现在又可以了

感觉校园网完全沦陷是迟早的事，4G已经不行了

**Comment by ablebodied** [comment]
IP确实少了，不过还能用，不过照今年这局势，很可能撑不过今年了，好难受

**Comment by yyuurrii34** [comment]
#12103 
注意我画的原理图。已从原理上论断isatap和原生ipv6是不可行的。

**Comment by AnyWAT** [comment]
> IP确实少了

貌似最开始可扫满400左右，现在只能不超过250

> 从原理上。。。原生ipv6是不可行的

实际上呢：https://github.com/XX-net/XX-Net/issues/12477#issuecomment-485324506

**Comment by AeneasZhu** [comment]
> 坐标广州校园网，昨天晚上开始的确不能用了，但是现在又可以了

昨天下午开始能用，今天又不行了
