### ISSUE TITLE
年初开始就无法使用了，总是ipv6不可用。

### ISSUE THREAD

**Issue by ancientmodern2099** [XX-net/XX-Net#12502]
年初开始就无法使用了，总是ipv6不可用。每次刚开xxnet都会提示可以访问真正的互联网了，但是ipv6数只有几个，谷歌都上不去。电脑重装过，还是不行。

本人菜鸟，也试过论坛的方法都不行，求指教求帮助。

**Comment by AnyWAT** [comment]
如用（Teredo ）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）及XX-Net 诊断信息

**Comment by ancientmodern2099** [comment]
Type                    : enterpriseclient
Server Name             : teredo.remlab.net
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : managed
NAT                     : cone
NAT Special Behaviour   : UPNP: Yes, PortPreserving: Yes

**Comment by ancientmodern2099** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:3
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:3
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
> Server Name : teredo.remlab.net
> scan-ip-thread-num: 10

以上或需改进？#12455

**Comment by ancientmodern2099** [comment]
请问怎么改进啊，每次都是xxnet刚启动时可以上去一下谷歌，然后就翻不出去了。。。看了12455，看不太懂啊。

**Comment by AnyWAT** [comment]
> Server Name : teredo.remlab.net

https://github.com/XX-net/XX-Net/issues/12455 3、如使用域名不理想，可试试使用其 IP。。。#12043

> scan-ip-thread-num: 10

https://github.com/XX-net/XX-Net/issues/12455 2、关闭。。。点击（有色文字）。。。

**Comment by ancientmodern2099** [comment]
可以加QQ远程帮忙设置一下吗，本人菜鸟，帖子里的语言真的看不懂。。。

**Comment by ancientmodern2099** [comment]
系统是64位

**Comment by AnyWAT** [comment]
> 系统是64位

也许无关。。。如——管理员 cmd：
netsh int ipv6 set teredo enterpriseclient 83.170.6.76

**Comment by AnyWAT** [comment]
如已有原生 IPV6，也可试试原生：#12477

**Comment by ancientmodern2099** [comment]
我只想上个谷歌学术，好难。。。真不会设置，求帮忙啊。

**Comment by AnyWAT** [comment]
> 谷歌学术

https://github.com/XX-net/XX-Net/issues/12416#issuecomment-476933025

**Comment by dabi3ng** [comment]
你就按机器人大大说的，管理员运行cmd，然后输入
netsh int ipv6 set teredo enterpriseclient 83.170.6.76
再刷新试试

**Comment by gfvre123** [comment]
> 好吧，彻底放弃了。

ssr客户端有没有

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）
