### ISSUE TITLE
绿灯亮， 但是ipv6 fail

### ISSUE THREAD

**Issue by eljake58** [XX-net/XX-Net#12500]
XX-Net Status:

sys-platform: x86_64, Darwin-17.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
os-release: 17.7.0
os-detail: Release:10.13.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:22 ipv4:0 ipv6:22
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 331
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/8045#issuecomment-483097448

**Comment by eljake58** [comment]
> [#8045 (comment)](https://github.com/XX-net/XX-Net/issues/8045#issuecomment-483097448)
> #12455 貌似巨硬服务器全部已残，唯有：
> teredo.iks-jena.de. 217.17.192.217
> teredo.trex.fi. 195.140.195.140
> teredo.remlab.net. 83.170.6.76
> teredo-debian.remlab.net. 83.170.6.76
> 如使用域名不理想，可试试使用其 IP。。。

绿灯不是表示连上服务器了吗

**Comment by AnyWAT** [comment]
> 绿灯不是表示连上服务器了吗

也许是，但
#12455 （隧道或能连接、）甚或 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗但扫描不到 IP的服务器陷阱！

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）
