### ISSUE TITLE
"仅 IPv6" 不可用，请检查。IPv6 状态(如何开启)	Fail (尝试修复)合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)

### ISSUE THREAD

**Issue by Robot20200229** [XX-net/XX-Net#12509]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:76 ipv4:0 ipv6:47
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 984
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by Robot20200229** [comment]
我是笔记本通过手机移动卡共享热点上网的

**Comment by AnyWAT** [comment]
> scan-ip-thread-num: 20
> 服务器名称 : win1711.ipv6.microsoft.com.

。。。。。。
#12455
