### ISSUE TITLE
这段时间老是不能FQ!!!

### ISSUE THREAD

**Issue by hai1212** [XX-net/XX-Net#12508]
交替显示“连接尚未建立”和“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了”，单打不开谷歌。然后IP狂减，最后变0，总数100，然后就是“等待扫描IP，建议开启IPV6。IPV6正常。

**Comment by AnyWAT** [comment]
试试：#12455

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）
