### ISSUE TITLE
XX-NET好久没更新了，放弃了吗？

### ISSUE THREAD

**Issue by WindSpeak** [XX-net/XX-Net#12515]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 或原生 #12477 均正常中。。。

**Comment by AeneasZhu** [comment]
校园网（我们是电信）勉强还能支撑，但连上去后过一段时间会疯狂掉ip，然后就断了。

**Comment by qucanswo** [comment]
完全可以使用的话没必要更新，不同地区可能使用起来体验不同。

**Comment by qucanswo** [comment]
> Teredo 隧道 #12455 或原生 #12477 均正常中。。。

Anywat老兄可以，一直在帮别人而且方法真的很有用。但是有些时候一些人比较焦虑，急着翻墙没时间仔细看你说的话，所以会喷你。

**Comment by LET19** [comment]
不同的网络环境真的体验千差万别。我三大运营商的4G网、公司、家里宽带都试过，差别很大，不同时间的使用体验也不一样。但是基本上来说，不管什么网络环境，每次长时间使用后必然会出现一段时间的科学上网中断。teredo服务器真的只是个ipv4向ipv6过渡的的东西，别太依赖单一科学上网手段。上网翻出去后多看看一些新技术，未雨绸缪没错的。

**Comment by AnyWAT** [comment]
> 但是基本上来说，不管什么网络环境，每次长时间使用后必然会出现一段时间的科学上网中断。

> Teredo 隧道 #12455 或原生 #12477 均正常中。。。

隧道偶尔（如XX-Net 自动退出），原生貌似木有

**Comment by LET19** [comment]
> > 但是基本上来说，不管什么网络环境，每次长时间使用后必然会出现一段时间的科学上网中断。
> 
> > Teredo 隧道 #12455 或原生 #12477 均正常中。。。
> 
> 隧道偶尔（如XX-Net 自动退出，再启动或需折腾即好），原生貌似木有

以前原生ipv6貌似不用xx net也能直接翻吧？
现在我4g网有原生ipv6了，但是用原生就没成功过

**Comment by AnyWAT** [comment]
原生即时：
![image](https://user-images.githubusercontent.com/37962734/57291544-3e3b9700-70f2-11e9-8ad8-350b8e8f67f9.png)

**Comment by LET19** [comment]
> 原生 #12477 即时：
> ![image](https://user-images.githubusercontent.com/37962734/57291544-3e3b9700-70f2-11e9-8ad8-350b8e8f67f9.png)
哦哦，可能是我配置问题，有空再试试。
原生需要在网络连接适配器那里开启ipv6的协议吗？

**Comment by AnyWAT** [comment]
> 原生需要在网络连接适配器那里开启ipv6的协议吗？

没有（像隧道）说禁用，当然。。。

**Comment by LET19** [comment]
> > 原生需要在网络连接适配器那里开启ipv6的协议吗？
> 
> 没有（像隧道）说禁用，当然（没协议何来原生？）。。。

嗯嗯，那我理解的没错。之前也是这么弄得。晚上回家再试试吧。谢谢大佬

**Comment by tt12354** [comment]
能用为什么要更新

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12477 8、因自身扫描不出 IP，借助 https://github.com/Kisesy/gscan_quic 可扫描出 IPv4/6 再导入。。。此后有效 IPv4/6 数及连接池较上图所示结果或翻番，IP延迟或有减小。一次导入经数小时运行后基本稳定在：总 IP 数540左右，有效 IPv4数50左右，IPv6还只是那2个。

**Comment by LET19** [comment]
> #12477 8、因自身扫描不出 IP，借助 https://github.com/Kisesy/gscan_quic 可扫描出 IPv4/6 再导入。。。此后有效 IPv4/6 数及连接池较上图所示结果或翻番，IP延迟或有减小。一次导入经数小时运行后基本稳定在：总 IP 数540左右，有效 IPv4数50左右，IPv6还只是那2个。

为啥这个gscan_quic我扫不出IP呢
![image](https://user-images.githubusercontent.com/33142139/58164719-edfb3200-7cb8-11e9-940c-c55db4b5e035.png)
需要配置什么参数吗？

**Comment by AnyWAT** [comment]
> 需要配置什么参数吗？

当然。对比下 config.user.json 

![image](https://user-images.githubusercontent.com/37962734/58165413-54348480-7cba-11e9-9069-5d6f42ac79d6.png)
