### ISSUE TITLE
teredo隧道一直是休眠（未连接）  ipv6  test能ping通隧道服务器也没问题  帮忙看下

### ISSUE THREAD

**Issue by liule0228** [XX-net/XX-Net#12514]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
如用（Teredo ）隧道，贴 cmd 内运行 netsh int ipv6 show teredo 的结果（无需 IP地址的2行）

**Comment by AnyWAT** [comment]
> teredo隧道一直是休眠（未连接） ipv6 test能ping通隧道服务器也没问题

#12455 隧道已连接（非其它如休眠！）——控制页内 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗——能扫描出 IP——XX-Net 才正常：有前才能有后。。。

**Comment by liule0228** [comment]
原声ip'v

> > teredo隧道一直是休眠（未连接） ipv6 test能ping通隧道服务器也没问题
> 
> #12455 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！
> 隧道已连接（非其它如休眠！）——控制页内 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗——能扫描出 IP——XX-Net 才正常：有前才能有后。。。
> 要么没禁用原生 IPv6，要么掉入了（巨硬）服务器陷阱？

原生ipv6没有禁用，谢谢

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）

**Comment by youngcrazyboy** [comment]
换teredo隧道服务器就行了，有些服务器连上了也不能用不知道为啥
管理员CMD 输入netsh interface teredo set state server=  
等号后面用这两个服务器teredo.remlab.net或者teredo.trex.fi。我的是移动网用这两个都可以就是晚上有点不稳定要刷新好几次才能出网页
