### ISSUE TITLE
SwitchOmega点击选项后，页面是空白的，怎么回事

### ISSUE THREAD

**Issue by SpecialYy** [XX-net/XX-Net#12518]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
😂出门右拐 https://github.com/FelisCatus/SwitchyOmega

**Comment by nly4lov** [comment]
chrome版本太高，omega版本不够高。
如果你的版本高于69，请卸载后，先安装69，
链接：https://pan.baidu.com/s/1rtRC3nXnhfdeXs4cipdcgw 密码：cqlv
omega最新版本：
链接：https://pan.baidu.com/s/1UzkxIK2YJOmToch4j3JTeA 密码：kxyc

**Comment by AnyWAT** [comment]
> chrome版本太高，omega版本不够高。

奇怪，难道平时只有前者升级，后者没有？（😂或许刚好相反，平时升级只有后者而没有前者？）

**Comment by nly4lov** [comment]
> > chrome版本太高，omega版本不够高。
> 
> 奇怪，难道平时只有前者升级，后者没有？（😂或许刚好相反，平时升级只有后者而没有时常升级不正常的前者？）

我前一段时间频繁重装系统（是为了解决一个闪屏的现象），也遇到了他这个空白的问题。后来就是降低Chrome版本解决的

**Comment by AnyWAT** [comment]
因 chrome 时常升级不正常，早弃用安装版而转用便携版了
