### ISSUE TITLE
自己的搭建ssr服务器，

### ISSUE THREAD

**Issue by gfvre123** [XX-net/XX-Net#12510]
找人分摊流量费，要用的朋友加我微信，主要是找人分摊费用，人数有限，人够了就不加了

**Comment by gfvre123** [comment]
我微信：gfvre123

**Comment by AnyWAT** [comment]
自己搭了一个ssr服务端 #12498

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf（使用此链接，你我都能得到20％优惠）

**Comment by hellojiang1** [comment]
james1403222764
