### ISSUE TITLE
还有其他可用的Teredo服务器吗

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12519]
teredo.iks-jena.de 217.17.192.217
teredo.trex.fi. 195.140.195.140
teredo.remlab.net. 83.170.6.76
teredo2.remlab.net. 83.170.6.77
teredo-debian.remlab.net. 83.170.6.76

常用的这几个已经很不稳定了，经常掉线，还有别的teredo服务器吗？

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）

**Comment by AeneasZhu** [comment]
> 可能是年纪大，渐渐变得懒得折腾了。
> 现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）

我还年轻，至少还能折腾10年。怎么能向GFW屈服！！

**Comment by Upreak-Jkeey** [comment]
> > 可能是年纪大，渐渐变得懒得折腾了。
> > 现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf （使用此链接，你我都能得到20%优惠）
> 
> 我还年轻，至少还能折腾10年。怎么能向GFW屈服！！

不是不折腾，而是把折腾放在更加值得折腾的事情上。 ；） @AeneasZhu

**Comment by hubsocks** [comment]
有其它teredo服务器也没用。现在是针对数据包的特征主动攻击，导致连接不稳定。微软迫于压力主动限制自家的teredo服务器了。但google ipv4依然十分稳定。

**Comment by AeneasZhu** [comment]
> 有其它teredo服务器也没用。现在是针对数据包的特征主动攻击，导致连接不稳定。微软迫于压力主动限制自家的teredo服务器了。但google ipv4依然十分稳定。

怎么用google ipv4

**Comment by hubsocks** [comment]
@AeneasZhu ipv4就是用机器人大哥的方法。设置IP 段列表为机器人大哥的，IP 模式为仅ipv6

**Comment by AnyWAT** [comment]
> IP 模式为仅ipv6

仅ipv4

**Comment by hubsocks** [comment]
打错字了，IP 模式为仅ipv4

**Comment by jianeddie** [comment]
teredo.trex.fi

我换了这个，ip基本虽然掉得厉害，但基本维持100+，连接池10+
