### ISSUE TITLE
为什么我的笔记本在公司不能上网（电信），家里不能上网（移动），连隔壁家电信可以？？

### ISSUE THREAD

**Issue by zhuchuanlong1988** [XX-net/XX-Net#12516]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:33
scan-ip-thread-num: 1
ip-quality: 289
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zhuchuanlong1988** [comment]
ip都是满格。。。有懂的，感谢，和路由器有关系。。。。

**Comment by AnyWAT** [comment]
貌似处于正常状态？

> ip都是满格。。。

貌似用的隧道而非原生

> use-ipv6: force_ipv6

改为自动，或许能扫描出 IPv4

> scan-ip-thread-num: 1

如非手工设定为1，貌似默认打开了某开关的特征值

同一电脑（及软件设置），公司电信、家庭移动不正常，隔壁电信正常，或许公司与隔壁并非同一 ISP，主要是隔壁可能（用的老路由器？）而没有原生 IPv6 ？
Teredo隧道：#12455 或原生：#12477

**Comment by zhuchuanlong1988** [comment]
@AnyWAT 没有设置啥东西，很久没关注了。就是最近移动的不能用，隔壁，老家乡下农村。路由器我看了下是FAST，FW316R，连他家就满格上网。

**Comment by AnyWAT** [comment]
> 路由器我看了下是FAST，FW316R，

（孤陋寡闻）不明觉厉。。。

> 家庭移动经历——Teredo隧道：#12455 或原生：#12477

乡下农村近邻，光猫、有原生 IPv6，即使同城同一 ISP，也号称光纤入户但没光猫，（不支持 IPv6的路由器）就没有原生。

**Comment by AnyWAT** [comment]
> 就是最近移动的不能用

貌似锅在是否禁用原生？

**Comment by xc1988** [comment]
移动原生IPV6好像不能用了
