### ISSUE TITLE
连接尚未建立。

### ISSUE THREAD

**Issue by yan0512** [XX-net/XX-Net#12528]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:28
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 837
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
Teredo 隧道：#12455 或原生：#12477

**Comment by xugaohui** [comment]
又在忽悠了。你如果关了ipv4，还说隧道和原生可用？

**Comment by AnyWAT** [comment]
> 又在忽悠了。你如果关了ipv4，还说隧道和原生可用？

https://github.com/XX-net/XX-Net/issues/12529#issuecomment-491479382 到底谁在咋呼？
