### ISSUE TITLE
xx-net 3.13.1无法运行

### ISSUE THREAD

**Issue by zhimingcio** [XX-net/XX-Net#12523]
重装的win7系统，首次运行xx-net后，在浏览器中启用teredo后重启，再次运行xx-net无法运行，管理员权限运行xx-net.bat文件，报错如下（已经完整下载3.13.1压缩包，本地解压缩后运行）：（求解决办法）

![捕获](https://user-images.githubusercontent.com/42328395/57283810-910d5280-70e2-11e9-943a-b193701b038c.JPG)
![捕获2](https://user-images.githubusercontent.com/42328395/57283812-91a5e900-70e2-11e9-801d-be7a18c74bc9.JPG)

**Comment by SeaHOH** [comment]
不要使用 Windows 记事本编辑任何 XX-Net 相关文件。
