### ISSUE TITLE
"仅 IPv6" 不可用，请检查。teredo测试 qualified：false，网络小白。

### ISSUE THREAD

**Issue by Andywang089** [XX-net/XX-Net#12526]
teredo测试结果如下：
qualified: False
NAT type: symmetric
best server is: win1711.ipv6.microsoft.com.
XX-Net Status:
诊断信息如下：
sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:50
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 457
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Andywang089** [comment]
截止目前貌似已经解决，说下大概的操作
无法连接后在页面点击修复进入如何开启ipv6的页面，根据个人情况选择ipv6-win10，使用powershell根据页面介绍一步一步进行操作。
1、// 设置 Teredo 服务器，默认为：win10.ipv6.microsoft.com
  netsh interface teredo set state enterpriseclient server=default
  
2、 // 测试 IPv6 连接
  ping -6 ipv6.test-ipv6.com
  ping -6 [2001:470:1:18::125]
3、  // 重置 IPv6 配置
  netsh interface ipv6 reset
发现测试ipv6过程，全部是请求超时，丢失率100%（先忽略，进行执行下面的操作）
4、重启系统
通过命令ipconfig /all 查看ipv6 teredo tunneling ...是以2001开头， 访问http://test-ipv6.com测试结果显示ipv6设置不正确。
5、 ipv6 为0 继续尝试修改teredo服务器：修改 Teredo 服务器为 teredo.remlab.net
  netsh interface teredo set state server=teredo.remlab.net
经过第5步操作，立马连接成功，目前比较稳定。
手动设置teredo服务器比较靠谱。@anyWAT的一些见解还是很有用的，就是小白看起来需要有耐心。

没有原生ipv6的情况，就是设置teredo隧道实现ipv6，有隧道情况，其实可以关掉网络属性里面的ipv6。

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 （或原生 #12477 ）
摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启 IPv6以来，一直正常一直不用此玩意儿：IPv6 正常前测也白测，正常后更无需再测！
隧道已合格（连接）——控制页内 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗——能扫描出 IP——XX-Net 才正常：有前才能有后。。。

**Comment by AnyWAT** [comment]
> best server is: win1711.ipv6.microsoft.com.

> 1、// 设置 Teredo 服务器，默认为：win10.ipv6.microsoft.com
> netsh interface teredo set state enterpriseclient server=default

https://github.com/XX-net/XX-Net/issues/12455 小心被XX-Net 或某脚本唯所谓延迟最小为佳的推荐：。。。服务器陷阱！

**Comment by Andywang089** [comment]
> > best server is: win1711.ipv6.microsoft.com.
> 
> > 1、// 设置 Teredo 服务器，默认为：win10.ipv6.microsoft.com
> > netsh interface teredo set state enterpriseclient server=default
> 
> #12455 小心被XX-Net 或某脚本唯所谓延迟最小为佳的推荐：。。。服务器陷阱！貌似巨硬服务器全部已残，唯有：。。。
> 
> > 2、 // 测试 IPv6 连接
> > ping -6 ipv6.test-ipv6.com
> > ping -6 [2001:470:1:18::125]
> > 3、 // 重置 IPv6 配置
> > netsh interface ipv6 reset
> > 发现测试ipv6过程，全部是请求超时，丢失率100%（先忽略，进行执行下面的操作）
> > 4、重启系统
> > 通过命令ipconfig /all 查看ipv6 teredo tunneling ...是以2001开头， 访问[http://test-ipv6.com测试结果显示ipv6设置不正确。](http://test-ipv6.com%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C%E6%98%BE%E7%A4%BAipv6%E8%AE%BE%E7%BD%AE%E4%B8%8D%E6%AD%A3%E7%A1%AE%E3%80%82)
> 
> [#12525 (comment)](https://github.com/XX-net/XX-Net/issues/12525#issuecomment-490438319) 已告知，还纯粹绕弯弯。。。直接命令行更换（非巨硬）服务器 （操作见 #12043）

“操作见#12043”这是什么意思，我点击#12043转到#12043页面，没看到如何操作啊。麻烦直接告诉我怎么设置，我点进去没有看到如何设置

**Comment by SeaHOH** [comment]
删掉了他 30 天的所有 comments，issue 只是 edit，想看的话请点击 edited 查看。

**Comment by Andywang089** [comment]
怎么点击edited查看，我对这个GitHub不太了解，还请指教
