### ISSUE TITLE
昏了，刚买了300G X-Tunnel流量回来发现不仅所有前端都false连账号都登陆不了了

### ISSUE THREAD

**Issue by happyvsp** [XX-net/XX-Net#12539]
![QQ截图20190517021011](https://user-images.githubusercontent.com/15385502/57877175-ba984d80-7849-11e9-8b4d-7035f9dd09d5.png)
![QQ截图20190517021508](https://user-images.githubusercontent.com/15385502/57877176-bb30e400-7849-11e9-91ee-f6ac9c147c20.png)
![QQ截图20190517021520](https://user-images.githubusercontent.com/15385502/57877177-bbc97a80-7849-11e9-9dd2-74d5a12294ca.png)
![QQ截图20190517021653](https://user-images.githubusercontent.com/15385502/57877217-dac80c80-7849-11e9-9f2a-123afff54e41.png)

**Comment by AnyWAT** [comment]
1、禁用后3个貌似早已无效的前端 https://github.com/XX-net/XX-Net/issues/11227#issuecomment-408638834
2、强化主力前端 GAE：Teredo 隧道 #12455 或原生 #12477

**Comment by LET19** [comment]
X-tunnel有时候确实抽风，但基本过个几分钟就能登陆了。我ji几个月前充的300G流量现在还在用呢。
![image](https://user-images.githubusercontent.com/33142139/58156825-9a351c80-7ca9-11e9-9c88-faf592341f46.png)

**Comment by LET19** [comment]
![image](https://user-images.githubusercontent.com/33142139/58156907-c94b8e00-7ca9-11e9-95d3-8567a31ab484.png)

**Comment by LET19** [comment]
![image](https://user-images.githubusercontent.com/33142139/58156951-e4b69900-7ca9-11e9-9eda-b0de58e5e7bf.png)

**Comment by tpddy** [comment]
这算啥 我买了一年的  不怎么会配置 搞得一塌糊涂   1200G流量一点没用
![image](https://user-images.githubusercontent.com/46946960/58295719-358dd500-7e03-11e9-9dd7-9c3590f3d3e9.png)
后来烦了 因为服务一会连得上 一会连不上 自己就搭了个梯子  现在自己用用  速度比之前好多了 
![image](https://user-images.githubusercontent.com/46946960/58295829-974e3f00-7e03-11e9-9175-84dbfc2e797c.png)

**Comment by g8up** [comment]
我买了一个月的流量，因为 x-tunnel 线路不是很稳定，现在用了8G。
眼看今天到期。。。
---
我如果把流量转给其他帐号，期限会延长吗？

**Comment by AnyWAT** [comment]
> x-tunnel 线路不是很稳定

主力前端GAE稳定，x-tunnel 就稳定

**Comment by LET19** [comment]
> 这算啥 我买了一年的 不怎么会配置 搞得一塌糊涂 1200G流量一点没用
> ![image](https://user-images.githubusercontent.com/46946960/58295719-358dd500-7e03-11e9-9dd7-9c3590f3d3e9.png)
> 后来烦了 因为服务一会连得上 一会连不上 自己就搭了个梯子 现在自己用用 速度比之前好多了
> ![image](https://user-images.githubusercontent.com/46946960/58295829-974e3f00-7e03-11e9-9175-84dbfc2e797c.png)

请教一下，老铁用的啥VPS啊，谷歌云、搬瓦工？

**Comment by tpddy** [comment]
用的服务器是亚马逊的免费服务器   自己在网上找的教程搭的ssr

**Comment by LET19** [comment]
> 用的服务器是亚马逊的免费服务器 自己在网上找的教程搭的ssr

申请的免费服务器是国际版的亚马逊云服务吗？

**Comment by tpddy** [comment]
嗯

**Comment by LET19** [comment]
> 嗯

好的，谢谢哈
