### ISSUE TITLE
找到暂时代替的方式，不知道是否安全

### ISSUE THREAD

**Issue by imyangdy** [XX-net/XX-Net#12532]
下了一个翻墙软件vpn plus,速度还可以，昨晚看youtu 720没啥问题，只是安全不知道怎么样，不知道有没有大神研究过，有了解的可以说说
优点：完全不用注册，没有流量限制，速度还行，稳定性对我这种偶尔查查资料的人来的可以
缺点：不能区分墙内墙外，统一都是vpn访问。安全性有等研究

**Comment by wangchenwc** [comment]
> 下了一个翻墙软件vpn plus,速度还可以，昨晚看youtu 720没啥问题，只是安全不知道怎么样，不知道有没有大神研究过，有了解的可以说说
> 优点：完全不用注册，没有流量限制，速度还行，稳定性对我这种偶尔查查资料的人来的可以
> 缺点：不能区分墙内墙外，统一都是vpn访问。安全性有等研究

从哪下载的？
