### ISSUE TITLE
XXnet总 IP 数永远最多只有100，怎么回事呢？

### ISSUE THREAD

**Issue by kkwking123** [XX-net/XX-Net#12530]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是
* 是否以相关关键词搜索过类似 issues？

是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
> XXnet总 IP 数永远最多只有100，怎么回事呢？

不很正常，是软件参数就得有个默认值？至于怎么修改，#12455 顶楼内有答案。

**Comment by Upreak-Jkeey** [comment]
可能是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://3.ly/nFf（使用此链接，你我都能得到20％优惠）
