### ISSUE TITLE
求点流量， 谢谢大神啊，好人一生平安

### ISSUE THREAD

**Issue by wpf940997721** [XX-net/XX-Net#12536]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by wpf940997721** [comment]
邮箱 wpf940997721@gmail.com   好人一生平安

**Comment by CleverZCW** [comment]
已给 请查收

**Comment by wpf940997721** [comment]
> 已给 请查收
非常感谢

**Comment by yulu2000cn** [comment]
yulu2000cn@gmail.com
同求一点流量，感谢~~

**Comment by g8up** [comment]
@yulu2000cn 个你转了点。要到期了，发现我还剩好多，用了不到 8/300，你看看接收的流量，期限会不会延长些。

**Comment by i-jiangxun** [comment]
heyguy1217@gmail.com
同求一点流量，大神好人一生平安~~

**Comment by NanGangHuang** [comment]
> @yulu2000cn 个你转了点。要到期了，发现我还剩好多，用了不到 8/300，你看看接收的流量，期限会不会延长些。

h1570438765@gmail.com
求点流量啊
