### ISSUE TITLE
IPV 6 Fail

### ISSUE THREAD

**Issue by jimmychen312** [XX-net/XX-Net#12537]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:460 ipv4:4 ipv6:224
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
Teredo 隧道：#12455 或
原生：#12477

**Comment by jimmychen312** [comment]
win10如何开启IPV6及WIN10无法上ipv6的解决方法
提示：本文基于Teredo隧道开启IPv6，其他开启IPv6的方法暂待完善。
特别重要：找到 网络和共享中心 - 更改适配器设置 - 本地连接（无线网络则找到WLAN或蓝牙网络连接）- 属性，把 IPv6协议 前面的勾去掉，确定。否则会出现一些奇怪的问题。
命令行：
•	Win+X 打开CMD 或 Windows PowerShell（管理员），输入命令：
•	  // 设置 Teredo 服务器，默认为：win10.ipv6.microsoft.com  
•	  netsh interface teredo set state enterpriseclient server=default
•	  
•	  // 测试 IPv6 连接  
•	  ping -6 ipv6.test-ipv6.com  
•	  ping -6 [2001:470:1:18::125]
•	
•	  // 重置 IPv6 配置  
  netsh interface ipv6 reset
•	重启系统
•	通过命令ipconfig /all 查看当前网络信息，看到 Teredo Tunneling Pseudo-Interface 有以 2001 开头的IPv6地址即可。 启动IE浏览器，访问 http://test-ipv6.com 或 http://ipv6.test-ipv6.com，如果选项卡 “测试项目” 下面的 “不使用域名的 IPv6 测试” 显示成功，则隧道建立成功。Chrome浏览器的测试结果可能和IE不一样，请注意
•	如果经过上面操作后仍无法启用 IPv6，可能是 Teredo 服务器无法正常连接，也可能是 Windows 自身配置问题，可尝试以下两种方法：
•	  // 第一种：修改 Teredo 服务器为 teredo.remlab.net  
•	  netsh interface teredo set state server=teredo.remlab.net
•	
•	  // 第二种：先卸载当前 Teredo 适配器再重新启用  
•	  netsh interface Teredo set state disable  
•	  netsh interface Teredo set state type=default  
  ping -6 ipv6.test-ipv6.com
 
组策略方法:
建议不要混用两种方法
•	Win+R 打开 组策略 gpedit.msc
 
•	打开 “计算机配置” - “管理模板” - “网络” - “TCPIP 设置” - “IPv6 转换技术” ，
“6to4 状态” 和 “ISATAP 状态” 都配置为 “已禁用状态” ，
“Teredo 状态” 配置为 “企业客户端”，“Teredo 默认限定” 配置为 “已启用状态”
 
 

提示：如按照教程设置无效出现其他莫名其妙的问题，建议：
•	管理员模式运行disable_ipv6.bat。（如是用的组策略模式，请把所有更改过的组策略改成未配置）
删除regedit：计算机\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ 下面的Tcpip6和TCPIP6TUNNEL两个选项。（改动注册表之前请备份）
•	在自动禁用或重新启用 IPv6 或其组件下载 "在非隧道接口和 IPv6 隧道接口上重新启用 IPv6" ，运行后重启电脑，然后按照组策略教程再重做一遍。（切记：组策略方法开启IPv6必须指定服务器名称）
•	文章开头提示的：禁用IPv6协议。

WIN10无法上ipv6，解决方法，亲测有效

1、看到了微软官网的修复工具，现在将源地址发出来：https://support.microsoft.com/en-us/kb/929852；
2、进入官网后，选择Re-enable IPv6 相关的工具，可以博主是下载了第一个：Re-enable IPv6和第五个：Re-enable IPv6 on nontunnel interfaces and on IPv6 tunnel interfaces。博主确实是找到这两个界面下载的，不知道为啥csdn上传该资源文件上传不了，楼下有评论说找不到，这里贴出我打开界面
 
3、下载完成后，先不急着运行。先打开注册表，打开cmd，输入regedit。
 
弹出的对话框中，找到 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\然后将ipv6相关的注册表删除，博主这里删除了Tcpip6、TCPIP6TUNNEL。
4、然后再分别运行上面下载的两个工具，之后重新启动电脑。
5、这时候，可以惊奇的发现，可以上ipv6了。终于解决这个奇怪的问题了。
 
如果有什么问题，可以评论。希望大家可以愉快的使用ipv6，目前ipv6是针对一些教育网的。


链接：http://www.365jz.com/article/24427 
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
