### ISSUE TITLE
谷歌日历无法打开，被墙了？

### ISSUE THREAD

**Issue by snipertulip** [XX-net/XX-Net#12542]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
3.13.1 
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
 是

* 是否以相关关键词搜索过类似 issues？
 是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

Request URL: https://calendar.google.com/calendar/_/scs/calendar-static/_/js/k=calendar.matsync.zh_CN.E7DMgjOoV8g.O/am=J8hWACACQA/d=0/rs=ANwU0p63_VeMDq0O7vpxng939eBwRBYo1A/m=sy7f,sypo,xDNx2e,wI7Sfc,ws9Tlc,CEoGje,sybk,essential,wqUujb,syc0,syc1,fLjFze,syjp,XdwRcf,syhl,nnalD,A717ie,FgpcFd,sy9u,sy9t,sy9v,sybj,sybl,sybm,sybh,sybn,sybi,essential_contactstore,syt6,sysw,sytw,sysd,syu1,AUvahe,sys5,sysq,syt9,sysc,syt3,sysx,syt5,syta,syti,sysi,sytz,syu6,syt2,sytk,syu9,sysb,sysf,sytg,syu5,syub,syty,syu7,syu4,syua,syuc,syud,sysj,syu2,syu3,syu8,syue,syug,sytx,syuf,zgOZub,sysg,syse,sysh,sysa,syut,sys6,syuz,syv2,sytv,syu0,syv3,sysy,syv4,syv5,x0hdXb,syuu,syv9,syva,vkbece,syuv,syvd,syvf,aEDxtf,sysu,syst,syss,sytj,syth,syka,sysr,sytc,sytm,sytl,sytn,syto,syui,syul,syt0,sytf,syuj,syus,syte,syuy,sytb,syv0,syvb,EN4Nve,KFgze,syt8,syun,syur,nOmB,dYtHvc,sy9g,BOjYxd,syhq,ThOSZc,syhr,PdC5mc,UNJwlc,syk0,GitpOb,syhb,FMjyU,L8FcAb,syj8,awTRx,syho,syhp,s4C1Cc,P3hjJe,sy18,synk,zUR36c,sy84,PLDzxe,syke,hjO17e,sy82,sy81,syl3,syr3,O6y8ed,IT2TV,Y9atKf,s39S4,fGUTQ,syh0,IzsqCe,hylsNc,syaj,Lu0iNb,SnIWac,syiu,syiv,Sh7lt,xqP6lb,KcjkC,QC8KLc,syk7,YM8Hab,syro,xQtZb,sy83,sy8x,sy8y,synr,syr2,L1AAkb,doKs4c,syjm,XVMNvd,syhz,syk1,syk2,syk3,syk4,syk6,syk8,BGXdz,ZxeXO,zEDUhe,MTcl1c,syhw,syna,wIdADb,MAHkAd,agSc2b,sEuMgc,syjq,syjr,z7IBkc,xIN43b,syhm,syhn,x7YzCb,SPG3Nc,dM3pQb,rHjpXd,syns,syr6,aW3pY,syjj,fGz4jc,sybs,mUolKf,DAxamb,o02Jie,lPoiHb,syik,Al8QNd,Tm61M,synb,RbcEVb,QIPWlf,sy99,sy9b,sy8w,sy9a,sys8,sys9,sysk,sys7,WjopWe,DHcGce,sye,syi,syg,syf,syj,sy7,syh,syc,syk,syl,syp,syq,syu,sy9,syb,sym,syn,syr,syv,sya,syd,sy8,syo,sys,syt,syw,sy6,sydf,sy63,sydg,emb,emg,emh,emd,sydn,TdBHGc,xPfONd,syx,sy2q,syy,sy22,sy2s,sy36,sy2w,sy10,sy23,sy37,sy39,sy8k,sy8h,sy8j,sy94,sy9m,sy8i,sy9d,syfi,syfk,syml,symm,symn,symo,M7KqCd,sy5,syl1,syl2,yf2Bs,TPXyQb,pB6Zqd,jhlE0d,sy1j,sy1v,sy2h,sy16,sy15,sy24,sy25,sy1h,sy1o,sy1f,sy29,sy2a,sy2i,sy17,sy21,sy26,sy1i,sy1n,sy28,sy2b,sy1t,sy2j,sy1e,sy27,sy2c,sy3k,sy2v,sy2k,sy3a,sy2n,sy3f,sy5p,sy5j,sy3x,sy2d,sy2f,sy2z,sy3o,sy3r,sy3b,sy3g,sy5o,sy5u,sy5l,sy3y,sy4l,sy13,sy1u,sy2e,sy2g,sy2p,sy2y,sy3c,sy32,sy2m,sy3n,sy3s,sy4m,sy5v,sy2l,sy38,sy3d,sy3e,sy3h,sy5n,sy3t,sy5t,sy5w,sy4k,sy53,sy51,sy4s,sy4w,sy4x,sy2o,sy3i,sy3j,sy3u,sy5x,sy4r,sy4t,em1k,ems,emr,ema,em10,emm,em11,sy3v,em5,em6,sy4q,sy4v,sy5m,syj9,vfhCmb,sysl,altG5b,sy40,sy41,sycw,sykd,sykh,SREA4b,sykl,vYINnd,sy7y,syfc,xAEm8d,sy8l,g9KmBc,sy42,sy4y,emt,sy4g,Y7w6af,sy43,sy12,sy44,sy45,sy46,sy50,sycc,syce,emv,sykm,VPsqtd,tPPmqb,sy7m,sy9e,sy9f,zbML3c,syap,syfr,syii,m9ZsQc,x1qUyd,syg5,FjKUHb,Nzssqd,sypj,LtvFIe,sysp,O0NJ3e,FUSkNe,sycx,bhA77,sybd,syam,sybe,syf6,y7aHAb,syi0,ZuRj2d,syki,Yq8ehd,jlkyXc,sGxtVc,syjy,syjz,CIRzC,syne,synf,syng,synd,XGW6Td,sykf,p6vRGe,sy7z,syjf,sy80,sygj,sylb,syly,sylz,sym0,sym1,E6Pgeb,syi1,syov,qqCxRb,syen,EIl99d,syko,sykn,sykr,QIIFof,FsujTe,sykg,PP7LR,KmXCTe,Fd8jcd,ASWikd,sy19,syz,sy4i,sy4n,sy1l,sy5k,sy4o,sy14,sy3l,sy1g,syht,syhu,syhx,sy4z,sy64,sypv,sy1k,syhv,syhy,em0,em7,em1,em2,syqd,syqf,Vpwp5d,PWEGNe,sldVDd,raWRAc,sync,sUpSld,sypw,syqq,syqr,rBHmpf

net::ERR_EMPTY_RESPONSE

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
#12455 或 #12477 （XX-Net 性能较佳）下的Goagent 代理可以
![image](https://user-images.githubusercontent.com/37962734/58062200-09c4e200-7bac-11e9-98a6-e1c76495e7ec.png)

**Comment by snipertulip** [comment]
GAE-Proxy不行呢

**Comment by snipertulip** [comment]
> #12455 或 #12477 （XX-Net 性能较佳）下的Goagent（X-Tunnel ）代理可以
> ![image](https://user-images.githubusercontent.com/37962734/58062200-09c4e200-7bac-11e9-98a6-e1c76495e7ec.png)

GAE-Proxy不行呢

**Comment by AnyWAT** [comment]
> Goagent

😥此Goagent 即指 GAE-Proxy

**Comment by snipertulip** [comment]
xx-net\data\gae_proxy\config.json

  "hosts_direct":[
    "www.google.com"
  ] 

问题已解决，因url超长出现的问题
