### ISSUE TITLE
为什么pornhub能上，但上一两分钟开始报错？Python Urlfetch Error: 'GET'

### ISSUE THREAD

**Issue by burdenlee** [XX-net/XX-Net#12545]
![QQ截图20190524230638](https://user-images.githubusercontent.com/46627154/58337651-db2f5b80-7e78-11e9-852d-393ba687b86c.jpg)

其他网站正常无问题

Python Urlfetch Error: 'GET'
ConnectionClosedError('Connection closed unexpectedly by server at URL: https://www.pornhub.com/video/search?search=%E7%AC%AC%E4%B8%80%E5%9D%8A',), timeout=15
ConnectionClosedError('Connection closed unexpectedly by server at URL: https://www.pornhub.com/video/search?search=%E7%AC%AC%E4%B8%80%E5%9D%8A',), timeout=30

**Comment by AnyWAT** [comment]
> 为什么pornhub能上，但上一两分钟开始报错？
> 其他网站正常无问题

是么，如U2B呢？或需提升XX-Net 性能：Teredo 隧道 #12455 或原生 #12477

**Comment by burdenlee** [comment]
> > 为什么pornhub能上，但上一两分钟开始报错？
> > 其他网站正常无问题
> 
> 是么，其它视频网如U2B呢？貌似有效 IP数不够大或连接池不足？或仅需提升XX-Net 性能：Teredo 隧道 #12455 或原生 #12477

youtbe720P无压力，

**Comment by AnyWAT** [comment]
貌似（随时）[有效 IP数/总 IP数之比值=1](http://127.0.0.1:8085/?module=gae_proxy&menu=status) 时性能较佳。或许GAE被该网屏蔽之类，X-Tunnel 正常。

**Comment by xugaohui** [comment]
@burdenlee ipv4早上1440无压力,油管1万多.晚上只有5K左右
![快照1](https://user-images.githubusercontent.com/18757174/58367997-e934b900-7f18-11e9-83e5-6f5ea54001fe.png)
GAE APP绑定免费域名这方法也不错.速度1万到2万之间,但每天晚上只有1千左右.优点是设置简单,拖时视频进度明显大xx-net快很多.

**Comment by burdenlee** [comment]
> @burdenlee ipv4早上1440无压力,油管1万多.晚上只有5K左右
> ![快照1](https://user-images.githubusercontent.com/18757174/58367997-e934b900-7f18-11e9-83e5-6f5ea54001fe.png)
> GAE APP绑定免费域名这方法也不错.速度1万到2万之间,但每天晚上只有1千左右.优点是设置简单,拖时视频进度明显大xx-net快很多.

呃，我只能获得IPV6，你说的绑定免费域名是什么意思呀？

**Comment by xugaohui** [comment]
@burdenlee 搜 GAE APP绑定免费域名和SSL证书
速度快,不会有xx-net拖动视频进度时转几圈开始播放,然后转二圈.再继续播放.晚上速度明显不如早上.

**Comment by dabi3ng** [comment]
貌似就pornhub有这个问题，我跟楼主情况一样。

**Comment by retmania** [comment]
说明你只能坚持一两分钟

多练练凯格尔运动

**Comment by maoyuan121** [comment]
看一两分钟就得了

**Comment by Tpwick123** [comment]
似乎是屏蔽广告插件的问题，把abp和uBlock Origin关掉就行了。。。。
