### ISSUE TITLE
Teredo 隧道	离线（无法连接）

### ISSUE THREAD

**Issue by lindiboy** [XX-net/XX-Net#12543]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
看过不是wifi

* 是否以相关关键词搜索过类似 issues？
没有

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
好
* 如果问题得到解决，请务必回复相关情况，谢谢。
好

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:442 ipv4:0 ipv6:415
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 100
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

类型                    : enterpriseclient (Group Policy)
服务器名称              : win10.ipv6.microsoft.com (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

类型                    : enterpriseclient (Group Policy)
服务器名称              : win10.ipv6.microsoft.com (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (secondary server)
客户端类型              : teredo client
网络                    : managed

我用策略法
原来Teredo是可以连接。
连不上后我换了“服务器名称”下面都试过不行。
后来删了good_ip.txt，改了回dns 8.8.8.8 和 8.8.4.4 还是不行。偶尔连上也扫不到ip。 

teredo.trex.fi
teredo.remlab.net
teredo.iks-jena.de
win10.ipv6.microsoft.com

现在我导入了不少ip还是不行

2019-05-23 12:49:29.066 - [DEBUG] connect 2a00:1450:4010:c05::99 blocked: network fail
2019-05-23 12:49:31.071 - [DEBUG] connect 2a00:1450:4003:806::2014 blocked: network fail
2019-05-23 12:49:31.071 - [DEBUG] connect 2607:f8b0:400b:80d::2014 blocked: network fail
2019-05-23 12:49:31.071 - [DEBUG] connect 2800:3f0:4004:801::2014 blocked: network fail
2019-05-23 12:49:31.071 - [DEBUG] connect 2a00:1450:4010:c0e::99 blocked: network fail
2019-05-23 12:49:34.980 - [WARNING] network IPv6 fail

**Comment by AnyWAT** [comment]
> gws-ip-num: total:442 ipv4:0 ipv6:415

总数超250，不佳。。。
> scan-ip-thread-num: 1

没关闭某开关，不佳。。。
> 服务器名称 : win10.ipv6.microsoft.com

巨硬服务器陷阱，si ！

以上判断，据自 #12455

**Comment by lindiboy** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.trex.fi (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

ip检查后 变成 0 了

**Comment by AnyWAT** [comment]
> ip检查后 变成 0 了

改变了服务器，正常，应有从0变非0的时候。。。

**Comment by lindiboy** [comment]
扫不到，怀疑被屏蔽了。这几天是518，明天看下。

**Comment by AnyWAT** [comment]
[潜规则：]( )隧道已合格（连接）——控制页内 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗——能扫描出 IP——XX-Net 才正常：有前才能有后

或可试试原生：#12477

**Comment by lindiboy** [comment]
智能路由器重启时候发现，得到ipv6的地址了。 没在意打10000好重置，结果ipv6的地址没了。通道正常使用了。

**Comment by AnyWAT** [comment]
😱原来使用隧道但没：
#12455 如（或不确定）已有原生 IPV6而用隧道，或路由器禁用原生 IPv6，或（电脑）网络属性内取消勾选 IPV6协议以禁用原生 。

**Comment by AnyWAT** [comment]
> 智能路由器重启时候发现，得到ipv6的地址了。 没在意打10000好重置，结果ipv6的地址没了。通道正常使用了。

光猫（直连电脑）重启后，观察光猫：IPv6 的正常（得到地址）比 IPv4 晚约12-15分钟。仅光猫后的路由器重启，貌似 IPv6 也滞后 IPv4？
