### ISSUE TITLE
为什么我用gmail账号申请的appid无法部署

### ISSUE THREAD

**Issue by corykang** [XX-net/XX-Net#1254]
系统版本：
XX-Net Version	2.5.5
Python Version	2.7.9
Sys Platform	AMD64, Windows-7-6.1.7601-SP1

部署gmail账号注册的appid状态：
Google IP num	58
100th IP handshake(ms)	-1
connected link(帮助)	0,0
提示timeout

而部署原outlook邮箱创建的appid状态：
Google IP num	62
100th IP handshake(ms)	-1
connected link(帮助)	11,60

**Comment by simonasd** [comment]
看描述不太明白你的问题所在。可以详细描述一下吗？

参考：[部署相关问题](https://github.com/XX-net/XX-Net/wiki#gae%E9%83%A8%E7%BD%B2%E6%95%85%E9%9A%9C)

**Comment by xyuanmu** [comment]
登录 https://appengine.google.com 看看是否running

![appengine](https://cloud.githubusercontent.com/assets/12442896/10662374/b70b1668-78e6-11e5-9cbb-39735086132b.png)

**Comment by dlhseu** [comment]
status 显示的None Deployed，而且现在建立app和教程的界面不太一样啊

**Comment by corykang** [comment]
部署服务端后再配置GAEProxy，问题得到解决。谢各位。
