### ISSUE TITLE
xxnet1.13.1 关闭xxnet后其他软件上不了网，xxnet设置为关闭全局代理，然后浏览器用的插件，每次fq完把xxnet关掉，甚至不关，其他软件都上不了网

### ISSUE THREAD

**Issue by nofogsky1996** [XX-net/XX-Net#12544]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
> 其他软件都上不了网

退出XX-Net 后检查 IE或系统设置内的代理设置是否取消或清空
