### ISSUE TITLE
为什么我的全局代理关闭不了

### ISSUE THREAD

**Issue by summerli248** [XX-net/XX-Net#12548]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
如某某安装过Python3，XX-Net 的代理菜单就失去控制了。只有在 IE或操作系统设置内处理，或修改 config.yaml 文件。。。
> 为什么我的全局代理关闭不了

😂不知到底对Ta 干了神马？

**Comment by summerli248** [comment]
不太懂怎么搞

**Comment by AnyWAT** [comment]
贴不能关闭时的 data\launcher\config.yaml 文件内容

**Comment by AnyWAT** [comment]
proxy: disable 即“取消全局代理”
proxy: gae 即 全局 GAE
proxy: x_tunnel 即 全局 X-Tunnel
proxy: pac 即 全局 PAC

**Comment by AnyWAT** [comment]
IE 内设置系统全局代理（如在系统设置内设置则无需填写协议）：
1、GAE HTTP 8087
2、X-TUNNEL HTTP 1080
3、智能路由 HTTP 8086
4、PAC http://127.0.0.1:8086/proxy.pac
5、关闭系统全局代理
以上分别对应托盘图标5个（取消）代理模式
