### ISSUE TITLE
GoAgent配置文件说明 我的怎么只要修改了 为什么xxnet启动不了

### ISSUE THREAD

**Issue by LoveFForever** [XX-net/XX-Net#12547]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
还有个问题  
 就是下面写的，那么修改下面的哪个文件也可以  比如说设置最大IP数  good ip数 

请参考：
code/default/gae_proxy/local/config.py
以及
code/default/python27/1.0/lib/noarch/front_base/config.py

**Comment by AnyWAT** [comment]
> 怎么只要修改了 为什么xxnet启动不了 

只因文件（全英文标点）格式、参数等有问题

> 设置最大IP数 good ip数

#12455 顶楼有答案

**Comment by SeaHOH** [comment]
不要使用 Windows 记事本编辑任何 XX-Net 相关文件。
