### ISSUE TITLE
连接总是断断续续

### ISSUE THREAD

**Issue by zycxzy** [XX-net/XX-Net#12540]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:74 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

类型                    : enterpriseclient
服务器名称              : 83.170.6.76
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

普民网络，已禁用原生IPV6 ，连接总是断断续续，即使连接时也无法保证 有效 IP数/总 IP数之比值=1 ，连接池总是很小，过一会有效IP就没了，连接池也为0.试着调了 突破100的测试限制 的限制，貌似没起什么用，辅以 https://github.com/CNMan/dnscrypt-proxy-config也没起作用。手动检查 IP、重启软件就管一阵作用。

**Comment by AnyWAT** [comment]
> scan-ip-thread-num: 10

貌似没按 #12455 呢。。。

**Comment by zycxzy** [comment]
> > scan-ip-thread-num: 10
> 
> 貌似没按 #12455 呢。。。才10😱还“突破100的测试限制 的限制”
> 
> > NAT : restricted (port)
> 
> 或许更适合原生 #12477 ？



XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:156 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

我再试试原生

**Comment by AnyWAT** [comment]
> 辅以 https://github.com/CNMan/dnscrypt-proxy-config 也没起作用。

[改进用法在此](https://github.com/XX-net/XX-Net/issues/12477#issuecomment-487908266)

**Comment by zycxzy** [comment]
![1](https://user-images.githubusercontent.com/50544753/57971550-1be32c80-79c2-11e9-867f-314e89abc638.jpg)

![3](https://user-images.githubusercontent.com/50544753/57971552-1be32c80-79c2-11e9-98f3-4d25be4785f0.jpg)


![2](https://user-images.githubusercontent.com/50544753/57971622-ff93bf80-79c2-11e9-9d12-ba275add6181.jpg)

 是这样配置吗

**Comment by AnyWAT** [comment]
> 改进用法在此

![image](https://user-images.githubusercontent.com/37962734/57971701-f525f580-79c3-11e9-8aa2-ef6d6de5ac20.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/57973440-78067a80-79db-11e9-8f06-552afd61ac89.png)
