### ISSUE TITLE
绿灯亮，但是ipv6 fail

### ISSUE THREAD

**Issue by eljake58** [XX-net/XX-Net#12541]
XX-Net Status:

sys-platform: x86_64, Darwin-17.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
os-release: 17.7.0
os-detail: Release:10.13.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
服务器或参数。。。#12455

**Comment by valasco** [comment]
这段时间估计封的严，我mojave现在默认的teredo也是绿灯OK，最多一开始能上过几分钟照样IPV6失败，win下依旧teredo离线，其他OK。无所谓了！

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 或原生 #12477 均正常中。。。
