### ISSUE TITLE
折腾不出来了

### ISSUE THREAD

**Issue by hongshiba** [XX-net/XX-Net#12552]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:30 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 1359
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

类型                    : enterpriseclient
服务器名称              : 217.17.192.217
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 是

**Comment by AnyWAT** [comment]
> sys-platform: AMD64,

无线网络？https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890 2、同一机器不同网络下的XX-Net 正常/不正常的NAT及特殊行为：。。。
或换有线或换网？以往正常时是咋样的 NAT？

**Comment by hongshiba** [comment]
> > sys-platform: AMD64,
> > NAT : cone
> > NAT 特殊行为 : UPNP: 是，PortPreserving: 是
> 
> （笔记本）无线网络？[#12455 (comment)](https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890) 2、同一机器不同网络下的XX-Net 正常/不正常的NAT及特殊行为：。。。
> 或换有线或换网？以往正常时就没观察是咋样的 NAT？（😥无笔本更无笔本无线的遭遇。。。）
> 
> > scan-ip-thread-num: 20
> 
> 不知总 IP数多少，但至少可增大扫描线程数。。。
> 或试原生：#12477

你好，是台式机来的。。接的有线，有无线网卡
IP总数储备到了4000多，扫描下来寥寥无几

**Comment by hongshiba** [comment]
> > > sys-platform: AMD64,
> > > NAT : cone
> > > NAT 特殊行为 : UPNP: 是，PortPreserving: 是
> > 
> > 
> > （笔记本）无线网络？[#12455 (comment)](https://github.com/XX-net/XX-Net/issues/12455#issuecomment-481110890) 2、同一机器不同网络下的XX-Net 正常/不正常的NAT及特殊行为：。。。
> > 或换有线或换网？以往正常时就没观察是咋样的 NAT？（😥无笔本更无笔本无线的遭遇。。。）
> > > scan-ip-thread-num: 20
> > 
> > 
> > 不知总 IP数多少，但至少可增大扫描线程数。。。
> > 或试原生：#12477
> 
> 你好，是台式机来的。。接的有线，有无线网卡
> IP总数储备到了4000多，扫描下来寥寥无几

对了，公网ip,无原生ipv6,联通

**Comment by AnyWAT** [comment]
> IP总数储备到了4000多，扫描下来寥寥无几

貌似自扫描不到但导入有效的原生做法。可自扫描到但导入无效的隧道是无需储备的。
#12455 增大[总 IP数](https://github.com/XX-net/XX-Net/issues/11291#%E8%87%AA%E8%AE%BE%E6%80%BBIP%E6%95%B0)为[200-250](https://github.com/XX-net/XX-Net/issues/12184#issuecomment-458495848)，或许有益较佳的体验——指：data\gae_proxy\config.json 文件内有 "max_good_ip_num": xxx,
与神马储备毫不搭界。

> 对了，公网ip,无原生ipv6,联通

#12455 如（或不确定）已有原生 IPV6而用隧道，或路由器禁用原生 IPv6，或（电脑）网络属性内取消勾选 IPV6协议以禁用原生 。
