### ISSUE TITLE
没有有用的隧道服务器了吗？

### ISSUE THREAD

**Issue by w100208** [XX-net/XX-Net#12550]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:90 ipv4:0 ipv6:80
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 8
ip-quality: 474
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

试了主题帖的所有域名和IP，结果都是这样：
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问辅助 teredo 服务器

**Comment by AnyWAT** [comment]
因使用原生而禁用了隧道
类型 : disabled
状态 : offline
一旦（命令行）启用隧道，用某观察隧道变化的批处理（#12043）查看，立马
状态 : dormant
貌似——没有有用的隧道服务器了吗？——不成立😥

**Comment by valasco** [comment]
按照目前这种状态，在不更新后面是绝对要挺尸了~

**Comment by w100208** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.2.166:61292
外部 NAT 映射    : 113.247.34.206:26452

看来服务器还有用，只是很不稳定。

**Comment by AnyWAT** [comment]
> 本地映射 : -----
> 外部 NAT 映射 : -----

隐私。。。
#12455 
![image](https://user-images.githubusercontent.com/37962734/58427077-1d52da00-80d1-11e9-97c2-20b3a39170da.png)

**Comment by AnyWAT** [comment]
> 按照目前这种状态，在不更新后面是绝对要挺尸了~

情况是比3-5个月前更严峻，至少巨硬服务器全灭了，但
Teredo 隧道 #12455 或原生 #12477 仍旧正常中。。。
