### ISSUE TITLE
smart router 显示双fail

### ISSUE THREAD

**Issue by ElderTitanFish** [XX-net/XX-Net#12558]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:46
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:39
scan-ip-thread-num: 30
ip-quality: 625
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ElderTitanFish** [comment]
小白一枚，买了300G x-tunnel,切换成只能路由墙内都链接不上了

**Comment by AnyWAT** [comment]
> ca_state: Fail
> 切换成只能路由

http://127.0.0.1:8085/?module=smart_router&menu=config 规则——走 GAEProxy—— .deja.com——（页底）提交

> gws-ip-num: total:100 ipv4:0 ipv6:46
> scan-ip-thread-num: 30

有效 IP数没能达到总 IP数，宜增大最大扫描线程数 #12455

**Comment by SeaHOH** [comment]
代理设置有问题，建议使用 SwitchyOmega 来调度。
