### ISSUE TITLE
哎呦 好可怜

### ISSUE THREAD

**Issue by LoveFForever** [XX-net/XX-Net#12559]
![截屏图片](https://user-images.githubusercontent.com/22911218/58760938-0ef13c00-8571-11e9-8fd7-3ddc2e82d2da.jpg)
没有IP用了 隧道也不行 。。。

**Comment by AnyWAT** [comment]
特殊时期，貌似原生更佳😂 https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839

**Comment by xugaohui** [comment]
xx-net 用仅ipv4这次不受任何影响.
goproxy绑定域名也很好用.

**Comment by LoveFForever** [comment]
> 
> 
> 特殊时期，貌似原生更佳😂 [#12556 (comment)](https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839)

感谢 原生也不可以 今天隧道可以了

**Comment by LoveFForever** [comment]
> 
> 
> xx-net 用仅ipv4这次不受任何影响.
> goproxy绑定域名也很好用.

绑定域名的话 XXNET不是不能用？？？还是需要下个goproxy
