### ISSUE TITLE
2019年5月31日。早上9点。全国大范围断网然后恢复之后。仅IPV6不可用。就开始出现了。

### ISSUE THREAD

**Issue by kyhong2019** [XX-net/XX-Net#12556]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by kyhong2019** [comment]
您们出现了这样的情况吗？然后XX-net就不可用了？

**Comment by kyhong2019** [comment]
"仅 IPv6" 不可用，请检查。

**Comment by AnyWAT** [comment]
用原生的没感觉。
Teredo 隧道 #12455 或原生 #12477

**Comment by superlucky8848** [comment]
我自己的VPS和购买的VPN全都不行了，出了什么事吗？

**Comment by kyhong2019** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:6
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1509
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by kyhong2019** [comment]
> 我自己的VPS和购买的VPN全都不行了，出了什么事吗？
2019年5月31日。早上9点。全国大范围断网。你懂的。长城什么墙

**Comment by Wicky07** [comment]
> 我自己的VPS和购买的VPN全都不行了，出了什么事吗？

我也是，用的ssr+自建，6.1早上五点还能用，刷了下看到推特封了一批号，睡一觉起来，连不上ping不通了，好气啊。不知道过了 你懂得 那一天后还能不能上。

**Comment by Tommycm** [comment]
用ipv6 teredo 方式已经没用了，不知道还会更新不？

**Comment by vingo** [comment]
是啊，不晓得啥情况

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497948427

原生即时：
![image](https://user-images.githubusercontent.com/37962734/58757076-aafe5180-8537-11e9-98a6-6b59d4321698.png)

**Comment by mangwei** [comment]
如果你用点心，就知道每年6月前几天，以及开人大等全国人民会议时候，封锁以及禁言是最强大的。。。。原因自己都能想到。

**Comment by yangshuochina** [comment]
ss的vps ip被封了，试试好久没用的xxnet竟然还能用，虽然速度慢了一点，感谢。

**Comment by AnyWAT** [comment]
> 虽然速度慢了一点

提升性能：https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497948427

**Comment by wha4up** [comment]
其实有什么不能公开的

**Comment by esvvv** [comment]
> 其实有什么不能公开的

问题的关键在于，有些该死的人活得太长，不该死的英年早逝，你我就成了夹在这阴阳两界之间，注定要为此消耗余生的可悲之人。聪明的抓住机会早就走了，迟钝的儿女也在国外了，剩下的就是无能为力和不知不觉之人。

**Comment by sveinjoe** [comment]
> 用原生的没感觉。
> Teredo 隧道 #12455 或原生 #12477

原生不是早就不行了吗？

**Comment by AnyWAT** [comment]
> 原生不是早就不行了吗？

不行时还没原生，有原生后、此刻依旧行😂

**Comment by liushengyi** [comment]
> ss的vps ip被封了，试试好久没用的xxnet竟然还能用，虽然速度慢了一点，感谢。

我的ss ip突然也ping不通了

**Comment by youngwater** [comment]
@AnyWAT 
上海电信的，teredo扫到几个后，一会又没了，teredo隧道也会失效，更换后能好一会。
使用dnscrypt-proxy+原生ipv6，好像扫不出IP。
要怎么弄，先用gscan-quic扫出导入吗，导入后还开扫描吗？用IPV6还是4？

**Comment by AnyWAT** [comment]
> 使用dnscrypt-proxy+原生ipv6，好像扫不出IP。
> 要怎么弄，先用gscan-quic扫出导入吗，导入后还开扫描吗？用IPV6还是4？

自身扫描不出但导入 IP有效的原生：#12477

**Comment by youngwater** [comment]
gscan-quic扫出513个ipv4，但不能用，不到半小时全掉光。
@AnyWAT，ipv6有iprange文件吗？

**Comment by AnyWAT** [comment]
> ipv6有iprange文件吗？

貌似没用。
![image](https://user-images.githubusercontent.com/37962734/58876616-3bd45900-8701-11e9-848e-30a206662d47.png)
不知从哪里下载的 [gscan_quic_config.zip](https://github.com/XX-net/XX-Net/files/3252164/gscan_quic_config.zip)，里面的 iprange_tls.txt 即旧版XX-Net 内的 ipv6_list.txt 但去掉除 IP之外其它参数后的 ipv6 集合——作为 iprange_quic.txt

**Comment by AnyWAT** [comment]
> gscan-quic扫出513个ipv4，但不能用，不到半小时全掉光。

关闭“[自动调整扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)”，[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)设置为0，并尽量不要手动[检查 IP](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#check_ip)

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12515#issuecomment-494734967 2.2、复制XX-Net 下的 ip_range.txt（貌似 #12477 4、将XX-Net3.12.2或以前版本的 ip_range.txt。。。为佳？）过来改名为 iprange_quic.txt

**Comment by youngwater** [comment]
@AnyWAT 谢谢。
正在扫ipv6，目前扫到了2个，还没试。
早上开始扫的ipv4，到傍晚把扫到结果导入后，逐渐掉光，dnscrypt-proxy一直在用，xx扫描线程也设为0了。
后来又扫了下ipv4，发现基本都是timeout，中间取消了，改成扫ipv6了。

**Comment by AnyWAT** [comment]
> 后来又扫了下ipv4，发现基本都是timeout，中间取消了，改成扫ipv6了。

貌似多次扫 ipv4 有益，扫 ipv6 无意😜

> 最后一次扫描是上月22日😂

貌似若干天内扫描过5回左右

**Comment by LET19** [comment]
> ss的vps ip被封了，试试好久没用的xxnet竟然还能用，虽然速度慢了一点，感谢。

xx-net一直都能用，只是不稳定，时断时续。
