### ISSUE TITLE
ID流量

### ISSUE THREAD

**Issue by xiaohezhu** [XX-net/XX-Net#12555]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by kyhong2019** [comment]
2019年5月31日。早上。全国大范围断网然后恢复之后。仅IPV6不可用。就开始出现了。
