### ISSUE TITLE
放弃半年后回来 还是ipv6几秒就停

### ISSUE THREAD

**Issue by Illchange** [XX-net/XX-Net#12557]
按照win7小白指引的教程做 成功开启ipv6获得几十个IP
也都是过几秒就变成个位数 然后就fail
可以上youtube几秒 好累

**Comment by Illchange** [comment]
![asdasd](https://user-images.githubusercontent.com/29409529/58749636-f6264f00-84ba-11e9-83b5-0b9ed0bc1146.png)
![asdassd](https://user-images.githubusercontent.com/29409529/58749637-f6bee580-84ba-11e9-9f89-260c0b8a55d0.png)

**Comment by AnyWAT** [comment]
> 放弃半年后回来 还是ipv6几秒就停

貌似越来越严峻，但
Teredo 隧道 #12455 或原生 #12477 依旧正常中。。。

**Comment by kyhong2019** [comment]
"仅 IPv6" 不可用，请检查。

**Comment by gLoCk27** [comment]
各种方法都试过了
依然：
"仅 IPv6" 不可用，请检查。

好累，现在使用付费的v2ray来这里看看。

**Comment by AnyWAT** [comment]
原生此刻：
![image](https://user-images.githubusercontent.com/37962734/59080053-57b24780-8919-11e9-9a62-0fd5bcabca93.png)
