### ISSUE TITLE
请问一下  xx-net工作原理是怎么样的呢

### ISSUE THREAD

**Issue by mingrihuaqiluo** [XX-net/XX-Net#12569]
1 . xx-net工作原理是怎么样的呢 
2 . 和前身GoAgent 的工作原理是一样吗
3 .xx-net工作原理的架构   , 和 基于shadowsocks的 CS架构 
优劣势分别在哪里呢

**Comment by hubsocks** [comment]
和前身GoAgent 的工作原理一样,劣势是数据传输是一段一段的.不是持续高速稳定的.只适合看带缓冲功能的在线视频,
后来的goproxy就没这个问题了.

**Comment by AnyWAT** [comment]
因在XX-Net 3.13.1发布前几天的”Google 更新服务器策略“，goproxy 再也玩不活了😥

**Comment by hubsocks** [comment]
goproxy 关闭ipv6后现在没任何问题,现在主要用这个.
xx-net 虽然有6百多个ipv4,但还是作为备用.

**Comment by LoveFForever** [comment]
> goproxy

goproxy哪里下载啊 哥们

**Comment by AnyWAT** [comment]
> goproxy哪里下载啊

也不知你楼上用的哪个。貌似有：
1、停更的GoProxy r1623：https://github.com/goproxy0/goproxy/releases
2、停更的接替release1632：https://github.com/out0fmemory/Goproxy-Always-Available/releases
3、在更但对用户来说（还需编译）的半成品：https://github.com/shell909090/goproxy/releases

**Comment by hubsocks** [comment]
r1651最终版

**Comment by AnyWAT** [comment]
> r1651最终版

这个？https://github.com/goproxy0/prom-releases
