### ISSUE TITLE
6月3日购买xx-tunnel，未到账

### ISSUE THREAD

**Issue by CraftLCL** [XX-net/XX-Net#12563]
6月3日购买xx-tunnel，到现在6月4日未到账。已发送邮件给xxnet.dev@gmail.com，至今也没有回复。

**Comment by AnyWAT** [comment]
先来点儿？

**Comment by lovethink2** [comment]
这个XX-Net还有人维护么？我买的1年的 xx-tunnel感觉很不稳定。有时候不能连。真的是骗钱呀。

**Comment by AnyWAT** [comment]
特殊时期，貌似原生更佳 #12477
禁用貌似早已无效的后3个前端：https://github.com/XX-net/XX-Net/issues/11227#issuecomment-428787512
