### ISSUE TITLE
想问下怎么允许其他设备使用x_tunnel?

### ISSUE THREAD

**Issue by MaJie414** [XX-net/XX-Net#12567]
想用xdm 下载youtube视频，怎么设置可以使用x_tunnel?
![image](https://user-images.githubusercontent.com/22385389/58923311-b2a93a80-8771-11e9-9cbf-ba0d4cd01ef5.png)

**Comment by AnyWAT** [comment]
第二行：
127.0.0.1:1080
或许填写在第一行也可？
https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B 支持的代理协议：
SOCKS | 127.0.0.1 | 1080
HTTP | 127.0.0.1 | 1080

**Comment by AnyWAT** [comment]
> 想问下怎么允许其他设备使用x_tunnel?

貌似标题与内容不符，宜软件替代设备？
