### ISSUE TITLE
有ipv6地址，ipv6却是fail，重新连接WiFi会正常一会然后又Fail

### ISSUE THREAD

**Issue by inkforest** [XX-net/XX-Net#12560]
XX-Net Status:

sys-platform: x86_64, Linux-4.18.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019
os-release: 4.18.0-20-generic
os-detail: Dist:Ubuntu; Version:18.04; ID:bionic
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.15rc1
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:64 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:23
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

2019-06-02 22:38:37.823 - [DEBUG] GAE POST https://clients4.google.com/**** from:127.0.0.1:44468

2019-06-02 22:38:38.204 - [INFO] GAE t:381 s:481 POST https://clients4.google.com/***,372:h2_get_head,0:get_response,1:h2_finish[SP:461566],:1

2019-06-02 22:38:38.256 - [DEBUG] report_connect_fail IPv6 continue_fail_count:94

2019-06-02 22:38:38.257 - [DEBUG] report_connect_fail:2a00:1450:4002:80a::2014

2019-06-02 22:38:38.257 - [DEBUG] connect 2a00:1450:4002:80a::2014 fail:error("conn fail, sni:None, top:sy-1201.appspot.com e:timeout('timed out',)",)

2019-06-02 22:38:38.466 - [WARNING] network IPv6 fail

日志如上，就是前一秒是能用的。。。突然就fail了。

**Comment by AnyWAT** [comment]
特殊时期，貌似原生更佳😂 https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839

**Comment by Tommycm** [comment]
你把good ip 删掉，让重新扫描出新的ip，会撑一会时间能上

**Comment by inkforest** [comment]
> 特殊时期，貌似原生更佳 [#12556 (comment)](https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839)

我用的就是原生的...而且貌似windows上可以正常使用，linux就莫名其妙的不行。。。
有懂linux的老哥吗

**Comment by mrsoshining** [comment]
帮我看看，最近总是不行，"仅 IPv6" 不可用，请检查。

IPv6 状态(如何开启) Fail

--
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455

**Comment by AnyWAT** [comment]
> 我用的就是原生的..

顶楼是（自身扫描不出但导入 IP有效的）原生状态？如是，对比 https://github.com/XX-net/XX-Net/issues/12477 则以下谬矣：
> use-ipv6: force_ipv6

Auto 或 force_ipv4
> scan-ip-thread-num: 200

0或2-3（如已借助 https://github.com/Kisesy/gscan_quic 可扫描出 IPv4/6 再导入。。。）

**Comment by FergonXie** [comment]
我这边最近两天也出现状况了。上youtube有效ip狂掉， 看一两个视频后，就提示ipv6 failed 。然后就只能等ip扫描。  感觉就象被跟踪了一样。 访问其它网址，好象就没什么问题。

**Comment by AnyWAT** [comment]
> 我这边最近两天也出现状况了。上youtube有效ip狂掉， 看一两个视频后，就提示ipv6 failed 。

原生木有

**Comment by belleyeah** [comment]
@AnyWAT, 请问原生ipv6，如何扫描ip？谢谢。

**Comment by AnyWAT** [comment]
> 请问原生ipv6，如何扫描ip？谢谢。

本笨老汉无辙，只有等你来。。。
