### ISSUE TITLE
大佬们 问个问题 IP数足够 但是ip延迟很高 咋回事

### ISSUE THREAD

**Issue by LoveFForever** [XX-net/XX-Net#12565]
检查ip后 ip延迟会好 但是过一会又变高了 

这是怎么回事啊

![截屏图片](https://user-images.githubusercontent.com/22911218/58873901-f3656d00-86f9-11e9-8ba6-e959b6d93837.jpg)
![QQ截图20190604183254](https://user-images.githubusercontent.com/22911218/58873906-f4969a00-86f9-11e9-8169-d78d256710c9.png)

**Comment by AnyWAT** [comment]
> 检查ip后 ip延迟会好 但是过一会又变高了
> 这是怎么回事啊

#12455 尽管有效 IP数/总 IP数之比值=191/200<1，还不能随时剔除延时较大的 IP，但 IP延迟261貌似蛮可以了。
1、如[最大扫描线程数]( )还不到200，可增大它
2、辅以 dnscrypt-proxy
3、试试 [IP 模式]( )：自动。
4、如用 X-Tunnel，禁用貌似早已无效的后3个前端：https://github.com/XX-net/XX-Net/issues/11227#issuecomment-428787512
5、https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839 特殊时期，貌似原生更佳 #12477
