### ISSUE TITLE
3.13.1 mac 闪退

### ISSUE THREAD

**Issue by qqgu** [XX-net/XX-Net#12566]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by qqgu** [comment]
运行start 输出，
XX-Net version:3.13.1
Run XX-Net in background.
但是直接退出，并没有任何任务出现。
查看launcher.log
2019-06-04 22:37:57.851 - [INFO] use build-in openssl lib
2019-06-04 22:37:57.854 - [INFO] start XX-Net 3.13.1
2019-06-04 22:37:57.854 - [DEBUG] start confirm_xxnet_exit
2019-06-04 22:37:57.855 - [DEBUG] good, xxnet:8085 clear!
2019-06-04 22:37:57.855 - [DEBUG] finished confirm_xxnet_exit
所以是直接闪退。Mac OSX 版本 10.14 (18A391)

**Comment by qqgu** [comment]
SeaHOH 在issue #10908中提出的解决方案
> https://github.com/XX-net/XX-Net/raw/mac-patch/start
> 试试替换根目录下这个文件
但是链接下载已经失效。
@SeaHOH

**Comment by qqgu** [comment]
@SeaHOH  在issue #10908中提出的解决方案

    https://github.com/XX-net/XX-Net/raw/mac-patch/start
    试试替换根目录下这个文件
但是链接下载已经失效。

**Comment by SeaHOH** [comment]
> 但是链接下载已经失效。

因为已经合并到 master。

https://developer.apple.com/documentation/macos_release_notes/macos_10_15_beta_release_notes#3318257
你是否升级了开发者预览？

**Comment by qqgu** [comment]
> > 但是链接下载已经失效。
> 
> 因为已经合并到 master。

合并到master 但是新版的3.13.1 版本还是闪退。我追溯到这个闪退的问题最初的版本是3.12.0 于是我用3.11 的版本设置成功，然后在3.11版本的基础上升级到了3.13这样就可以使用了。

具体什么原因我不清楚，但是这样问题解决了！
