### ISSUE TITLE
恢复了。

### ISSUE THREAD

**Issue by sky2917** [XX-net/XX-Net#12562]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by 2378** [comment]
好了多久，是不是墙累了，歇会

今天这种敏感日子ss+obfs流量一大都卡顿

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839 特殊时期，貌似原生更佳 #12477

**Comment by xugaohui** [comment]
特殊时期，貌似xx-net ipv4 更佳

**Comment by AnyWAT** [comment]
> 貌似xx-net ipv4 更佳

隧道模式可偶尔扫描到几个 IPv4 但随时失效，原生模式倒是以 IPv4 为主（能基本稳定的才2个 IPv6），故：貌似原生更佳 #12477

**Comment by AnyWAT** [comment]
> 恢复了。

经测试，貌似只是部分。仍然较以往长些时间才扫描到“总 IP数”，却“永远无法”[有效 IP数/总 IP数之比值=1]( )，无法随时剔除延时较大的 IP，性能不可能最佳 #12455

**Comment by AnyWAT** [comment]
想超900的 IP 延迟减半甚至3折么：
1、需[突破100的测试限制](https://github.com/XX-net/XX-Net/issues/11704#issuecomment-442873376) （code\版本号或 default\gae_proxy\local\ config.py），改100为400
2、无法在控制页内修改[最大扫描线程数](http://127.0.0.1:8085/?module=gae_proxy&menu=advanced#scan_setting)超过软件上限200，修改 data\gae_proxy\config.json 文件，免退出再次启动软件即可
