### ISSUE TITLE
X-tunnel疯狂弹出pythonw.exe停止工作

### ISSUE THREAD

**Issue by Skuyar** [XX-net/XX-Net#12573]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

X-tunnel，疯狂弹出pythonw.exe停止工作，基本不能用了快，重启过几分钟又弹出来，到底是什么原因啊。。。

**Comment by AnyWAT** [comment]
> X-tunnel，疯狂弹出pythonw.exe停止工作

与 https://github.com/XX-net/XX-Net/issues/12570#issuecomment-499329801
> 额，不太明白，我是买了tunnel的流量套餐，直接开SwitchyOmga插件就用了，

说法不一😱

**Comment by AnyWAT** [comment]
既然
> 疯狂弹出pythonw.exe停止工作

说明运行了XX-Net，Teredo 隧道 #12455 或原生 #12477
特殊时期，貌似原生更佳😂

**Comment by 2378** [comment]
国产垃圾软件造成的吧，今晚墙好像是累瘫了，明文传输2个小时后才出现干扰

**Comment by Skuyar** [comment]
> > X-tunnel，疯狂弹出pythonw.exe停止工作，
> 
> 与 [#12570 (comment)](https://github.com/XX-net/XX-Net/issues/12570#issuecomment-499329801)
> 
> > 额，不太明白，我是买了tunnel的流量套餐，直接开SwitchyOmga插件就用了，
> 
> 自己前后说法不一（矛盾）😱
> 还重复发帖，不是在同一贴中将情况讲透说明，更。。。

。。。哪儿矛盾了，说的就是办公室电脑win7总是弹出这个问题啊，那个话题本来准备删除的，看到你回复了，就没删而已。。。总之感谢你的回复吧
