### ISSUE TITLE
test-ipv6.com没有检测到 IPv6 地址

### ISSUE THREAD

**Issue by 361450843** [XX-net/XX-Net#12577]

**Comment by AnyWAT** [comment]
> test-ipv6.com没有检测到 IPv6 地址

#12043 摒弃 test-ipv6.com 测试，纯属多此一举，徒劳无功！自必须开启 IPv6以来，一直正常一直不用此玩意儿。 IPv6 正常前测也白测，正常后更无需再测！隧道已连接——控制页内 IPv6状态🆗——能扫描出 IP——XX-Net 才正常：有前才能有后。。。

继续：Teredo 隧道 #12455 或原生 #12477 貌似近期原生更佳

**Comment by zmy0730** [comment]
@AnyWAT 
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:451 ipv4:0 ipv6:250
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
求问下大佬，我这种状态  试过很多遍导入IP 达到451个了 还是显示"仅 IPv6" 不可用，请检查。
这怎么破  感谢。。

**Comment by AnyWAT** [comment]
如是隧道模式，对比 #12455 

> gws-ip-num: total:451 ipv4:0 ipv6:250

总 IP数不宜超过200-250
> use-ipv6: force_ipv6

Auto 更佳，或许能扫描出几个 IPv4
> scan-ip-thread-num: 1

没关闭某开关的特征值？关闭它！
> 试过很多遍导入IP 

导入对能自扫描出 IP的隧道模式无效！
隧道已连接——控制页内 IPv6状态🆗——能扫描出 IP——XX-Net 才正常：有前才能有后。。。
#12477 近期不能自扫描但导入IP有效的原生更佳

**Comment by jihabo** [comment]
> 如是隧道模式，对比 #12455
> 
> > gws-ip-num: total:451 ipv4:0 ipv6:250
> 
> 总 IP数不宜超过200-250
> 
> > use-ipv6: force_ipv6
> 
> Auto 更佳，或许能扫描出几个 IPv4
> 
> > scan-ip-thread-num: 1
> 
> 没关闭某开关的特征值？关闭它！
> 
> > 试过很多遍导入IP
> 
> 导入对能自扫描出 IP的隧道模式无效！
> 隧道已连接——控制页内 IPv6状态🆗——能扫描出 IP——XX-Net 才正常：有前才能有后。。。
> 
> > 这怎么破
> 
> 参照 #12455 操作！
> #12477 近期不能自扫描但导入IP有效的原生更佳

请问文中提到的几行命令，
在哪里查看呀？
比如gws-ip-num: total:451 ipv4:0 ipv6:250
