### ISSUE TITLE
谷歌文档打不开，504 gaeproxy time out

### ISSUE THREAD

**Issue by akiritoa** [XX-net/XX-Net#12572]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是，3.13.1

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

是，好像gae对部分网站不支持，但前段时间能上，想知道过几天能不能上去

* 是否以相关关键词搜索过类似 issues？

是，没有搜到想要的答案

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

有的网站用http进不去，用https就进去了，这个是都进不去，显示504 gaeproxy time out
其他网站正常，用的teredo隧道

* 如果问题得到解决，请务必回复相关情况，谢谢。

嗯

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839 特殊时期，貌似原生更佳 #12477
或仅GAE代理谷歌文档打不开？

**Comment by akiritoa** [comment]
仅GAE代理谷歌文档打不开

**Comment by AnyWAT** [comment]
不是还有X-Tunnel ？
