### ISSUE TITLE
几乎几分钟就会自动退出一次

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#12576]
最近几天另外一个主梯子又不能用了。只好再次使用xx-tunnel，居然可以用，真是感谢！

但从昨天开始，长则半个小时，短则不到一分钟，就会自动退出。

版本就是最新的13.3.1，系统win7。

难道真的没人更新xx-tunnel了吗？

有人有更可靠的收费梯子推荐吗？感谢！

**Comment by AnyWAT** [comment]
> 几乎几分钟就会自动退出一次

#12477 原生模式貌似没遇见。。。近些天原生好过隧道
> 难道真的没人更新xx-tunnel了吗？

即使近些天也正常呢

**Comment by farshidvahid** [comment]
算了算了，国人搭的梯子还是不靠谱。花了9.9美元买了个洋人搭的梯子，速度杠杠的。好在包年的话，也就是70多美元。并不比我买的那个国产梯子（每年400；几乎每逢重要节日都会停工）贵太多。

**Comment by farshidvahid** [comment]
国产货还是不靠谱啊，连尼玛梯子都不例外。哈哈哈哈哈哈。真是让人无奈。

**Comment by AnyWAT** [comment]
自必须开启 IPv6近2年来，隧道（或原生）一直正常。。。路过🤣
