### ISSUE TITLE
X-tunnel总是运行一段时间被退出是什么原因。

### ISSUE THREAD

**Issue by Skuyar** [XX-net/XX-Net#12570]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

家里电脑win10，公司win7，运行一段时间公司电脑会弹出程序由于某些原因停止运行的通知，家里的是悄无声息的就退出了。。这是什么问题啊

**Comment by AnyWAT** [comment]
只是偶尔，不明😂

**Comment by Skuyar** [comment]
> 只是偶尔，不明
> 总是。。。是否2系统有共同的国产。。。
> 忘了说，系统开销比隧道模式小些的原生模式自动退出的概率低很多，尤其近几天在性能上后者优于前者 [#12556 (comment)](https://github.com/XX-net/XX-Net/issues/12556#issuecomment-497999839)

额，不太明白，我是买了tunnel的流量套餐，直接开SwitchyOmga插件就用了，原生是指什么？

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12539#issuecomment-493186111
