### ISSUE TITLE
一直是“等待扫描 IP，建议开启 IPv6”，请教是怎么回事呀？

### ISSUE THREAD

**Issue by jihabo** [XX-net/XX-Net#12579]
前几个月，忽然就不好用了。
最近有时间，想搞的明白一些，
潜水看了一些大家的讨论，
虽然好像XXNET没以前那么好用，但应该还是可以用，
我这有问题，应该是哪里设置不对。
但看了一些帖子，尤其是AnyWAT大神的讲解，
发现自己对于网络方面了解的还是太少，
很多地方都看不懂，
干脆鼓起勇气发个贴请教一下！

**Comment by jihabo** [comment]
![QQ图片20190610135229](https://user-images.githubusercontent.com/51581040/59175167-16bf6a80-8b87-11e9-8287-e378e7ae5ff6.png)

**Comment by jihabo** [comment]
![QQ图片20190610135525](https://user-images.githubusercontent.com/51581040/59175238-6c941280-8b87-11e9-86f2-9a2593c1c8e6.png)

这个状态页面里，
IPV6的状态经常Fail的，
偶尔显示OK，但也一样完全连不上。

**Comment by jihabo** [comment]
![QQ图片20190610135958](https://user-images.githubusercontent.com/51581040/59175417-0c51a080-8b88-11e9-903a-79f32fa6c493.png)

**Comment by jihabo** [comment]
其实也看了一些说明和讲解的，
但是自己真是挺笨的没搞懂，
比如Any大神经常提到的12444贴，
里面第3条里的几个地址，我一直没搞明白要怎么用，在哪里用，
比如这个teredo.iks-jena.de. 217.17.192.217

**Comment by jihabo** [comment]
其实也看了一些说明和讲解的，
但是自己真是挺笨的没搞懂，
比如Any大神经常提到的12455贴，
里面第3条里的几个地址，我一直没搞明白要怎么用，在哪里用，
比如这个teredo.iks-jena.de. 217.17.192.217

**Comment by 361450843** [comment]
没有有用的隧道

**Comment by jihabo** [comment]
> 没有有用的隧道

请问有什么解决办法吗？

**Comment by AnyWAT** [comment]
> 里面第3条里的几个地址，我一直没搞明白要怎么用，在哪里用，
> 比如这个teredo.iks-jena.de. 217.17.192.217

#12455 （_[Windows 系统更多]( )。。。_：#12043）—— #12043 。。。
😱摒弃 IPv6 组策略法。。。否则，自己在 IPv6组策略内实现隧道服务器的改变

**Comment by AnyWAT** [comment]
> > 没有有用的隧道
> 
> 请问有什么解决办法吗？

如电脑已有原生 IPv6，近期原生好过隧道。

**Comment by jihabo** [comment]
> > 里面第3条里的几个地址，我一直没搞明白要怎么用，在哪里用，
> > 比如这个teredo.iks-jena.de. 217.17.192.217
> 
> #12455 （_Windows 系统更多。。。_：#12043）—— #12043 。。。
> 😱摒弃 IPv6 组策略法。。。否则，自己在 IPv6组策略内实现隧道服务器的改变

多谢Any大神的及时雨，
不过我很多地方都看不懂啊，

比如你上面说的摒弃IPv6组策略法，
摒弃是什么意思呀？
放弃不用？那然后下一步又怎么办呢？

“自己在IPv6组策略内事先隧道服务器的改变”
这个IPv6组策略，是在哪里呢？
右键网络属性，和XXNET的页面设置里，都没找到。。。

**Comment by AnyWAT** [comment]
> 这个IPv6组策略，是在哪里呢？
> 右键网络属性，和XXNET的页面设置里，都没找到。。。

回忆自己第一次用组策略开启 IPv6。。。
全部退回到未设置前的“未配置”（？）。。。

**Comment by AnyWAT** [comment]
退出XX-Net，删除（原生下的）good_ip.txt 运行隧道模式约5分钟效果：
![image](https://user-images.githubusercontent.com/37962734/59178406-7a4e9580-8b91-11e9-9bae-e8784a8c01e3.png)

**Comment by qibin8687** [comment]
那个机器人的回复我反正是看不懂。通过APPid的途径翻墙我是不指望了，我通过捐赠APPid获得xtunnel免费流量，一直正常翻墙，2018年至今从未收到过影响，比SSR还稳定.楼主有兴趣可以照xtunnel的说明页操作即可，一般一周内收到邮件告知流量发放到账，一个id给10g流量。

**Comment by jihabo** [comment]
> > > 没有有用的隧道
> > 
> > 
> > 请问有什么解决办法吗？
> 
> 如电脑已有原生 IPv6，近期原生 #12477 好过隧道。原生即时：
> 
> ![image](https://user-images.githubusercontent.com/37962734/59176871-eb3f7e80-8b8c-11e9-8b96-0a0404aa298d.png)
再弱弱的请教一下：
如何判断自己是原生模式，还是隧道模式呀？

**Comment by AnyWAT** [comment]
> 如何判断自己是原生模式，还是隧道模式呀？

温故知新：#12455 12477

**Comment by AnyWAT** [comment]
典型的隧道：回忆自己第一次用组策略开启 IPv6。。。（😥只会进不会退？做了即遗忘？）

![image](https://user-images.githubusercontent.com/37962734/59180827-7e31e600-8b98-11e9-9a2d-c5dcd3c1263a.png)

**Comment by AnyWAT** [comment]
超开马力，已运行超1小时，虽已达总 IP数，但仍未达以往3-5分钟即可的（随时）[有效 IP数/总 IP数之比值=1](http://127.0.0.1:8085/?module=gae_proxy&menu=status)，此刻仍然：原生好过隧道

![image](https://user-images.githubusercontent.com/37962734/59182023-3bbdd880-8b9b-11e9-91d0-249b8ed3d5c1.png)

**Comment by jihabo** [comment]
> 超开马力，已运行超1小时，虽已达总 IP数，但仍未达以往3-5分钟即可的（随时）[有效 IP数/总 IP数之比值=1](http://127.0.0.1:8085/?module=gae_proxy&menu=status)，此刻仍然：原生好过隧道
> 
> ![image](https://user-images.githubusercontent.com/37962734/59182023-3bbdd880-8b9b-11e9-91d0-249b8ed3d5c1.png)
> 
> 比较下：[#12579 (comment)](https://github.com/XX-net/XX-Net/issues/12579#issuecomment-500315341)

多谢Any大神指点，
这么多内容，够我消化一阵子的了，
我先慢慢对着研究一下，

现在是不是可以确定我的IPv6是正常打开的，
只是隧道选择问题？

**Comment by dabi3ng** [comment]
1. 控制面板的网络连接里，右键点你已经连接的网络，属性，把ipv6前面的对勾取消掉。
2. 管理员运行cmd，直接敲netsh int ipv6 set teredo enterpriseclient 195.140.195.140

再等一会试试看吧，我是这样基本就能连上的。

**Comment by jihabo** [comment]
> 1. 控制面板的网络连接里，右键点你已经连接的网络，属性，把ipv6前面的对勾取消掉。
> 2. 管理员运行cmd，直接敲netsh int ipv6 set teredo enterpriseclient 195.140.195.140
> 
> 再等一会试试看吧，我是这样基本就能连上的。

多谢解答！
请问是下面图里的这个选项么？
![QQ图片20190611191318](https://user-images.githubusercontent.com/51581040/59267983-3f765b80-8c7e-11e9-8cf4-5fc226e6a981.png)

我把上面这个图，IPV6前面的勾去掉，
然后重启，再打开XXNET，好像还是老样子，
详见下图，

这几天绝大部分时间连不上，好像都是这个页面，
无限刷network fail.....
（偶尔能连上一小小会）
![QQ图片20190611174216](https://user-images.githubusercontent.com/51581040/59268100-9419d680-8c7e-11e9-9f46-b87b5c3d58ae.png)

**Comment by jihabo** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:450
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 100
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

贴下这个不知道有用么，最后一片false，
看着好扎心呀....

**Comment by AnyWAT** [comment]
> 好扎心呀....

> use-ipv6: force_ipv6
> gws-ip-num: total:undefined ipv4:0 ipv6:450
> scan-ip-thread-num: 1

确实扎心，以上相应违背 #12455 
自动
总 IP数200-250
关闭某开关

**Comment by dabi3ng** [comment]
> XX-Net Status:
> 
> sys-platform: AMD64, Windows-10-10.0.17763
> os-system: Windows
> os-version: 10.0.17763
> os-release: 10
> os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
> architecture: 32bit,WindowsPE
> browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
> xxnet-version: 3.13.1
> python-version: 2.7.13
> openssl-version: 16.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: force_ipv6
> gws-ip-num: total:undefined ipv4:0 ipv6:450
> ipv4-status: OK
> ipv6-status: Fail
> connected-link: new:0 used:undefined
> worker: h1:0 h2:0
> scan-ip-thread-num: 1
> ip-quality: 100
> is-idle: 1
> block-stat: undefined
> proxy_state: Fail
> ca_state: Fail
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false
> 
> 贴下这个不知道有用么，最后一片false，
> 看着好扎心呀....

我也不是很懂哈，不过你后面proxy_state和ca_state都是fail，你重新导入一下证书试试？

**Comment by dabi3ng** [comment]
> > 1. 控制面板的网络连接里，右键点你已经连接的网络，属性，把ipv6前面的对勾取消掉。
> > 2. 管理员运行cmd，直接敲netsh int ipv6 set teredo enterpriseclient 195.140.195.140
> > 
> > 再等一会试试看吧，我是这样基本就能连上的。
> 
> 多谢解答！
> 请问是下面图里的这个选项么？
> ![QQ图片20190611191318](https://user-images.githubusercontent.com/51581040/59267983-3f765b80-8c7e-11e9-8cf4-5fc226e6a981.png)
> 
> 我把上面这个图，IPV6前面的勾去掉，
> 然后重启，再打开XXNET，好像还是老样子，
> 详见下图，
> 
> 这几天绝大部分时间连不上，好像都是这个页面，
> 无限刷network fail.....
> （偶尔能连上一小小会）
> ![QQ图片20190611174216](https://user-images.githubusercontent.com/51581040/59268100-9419d680-8c7e-11e9-9f46-b87b5c3d58ae.png)

你说偶尔能连上一小会，我感觉上是设置应该没问题，就是可用的ipv6个数不够导致，不过前两天确实封锁的很严重，掉ip掉的很快，最近两天比较稳定。至于195.140.195.140这个服务器是我个人试过比较好用，也不一定非用这个，你可以试试别的服务器，方法还是管理员cmd，netsh int ipv6 set teredo enterpriseclient后面换别的服务器就好啦。地址你就看看大佬原来的帖子，比如
#12043 #11920 #11892

**Comment by AnyWAT** [comment]
> 不过你后面proxy_state和ca_state都是fail，你重新导入一下证书试试？

如代理设置正确，与证书无关，锅在：
>> worker: h1:0 h2:0

> 原来的帖子，比如
#12043 #11920 #11892

时过境迁。。。

**Comment by dabi3ng** [comment]
> > 不过你后面proxy_state和ca_state都是fail，你重新导入一下证书试试？
> 
> 如已导入过证书且代理设置正确，与证书无关，锅在：
> 
> > > worker: h1:0 h2:0
> 
> 根在：
> 
> > （貌似导入得来的450，何处说要导入了？）
> 
> 自作主张，（能扫描但导入无效的）隧道、（不能扫描但导入有效的）原生方法混用，不遵循：#12455
> 潜规则：隧道已合格（连接）——控制页内 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗——能扫描出 IP——XX-Net 才正常：有前才能有后
> 
> > 原来的帖子，比如
> > #12043 #11920 #11892
> 
> 时过境迁。。。（至少巨硬服务器全部已残）不然还更新干嘛？

195.140.195.140还是很好用的，话说大佬发点新的服务器来用用呀。

**Comment by AnyWAT** [comment]
> 发点新的服务器来用用呀

你来发明吧。。。

**Comment by jesse8899** [comment]
> 1. 控制面板的网络连接里，右键点你已经连接的网络，属性，把ipv6前面的对勾取消掉。
> 2. 管理员运行cmd，直接敲netsh int ipv6 set teredo enterpriseclient 195.140.195.140
> 
> 再等一会试试看吧，我是这样基本就能连上的。
感谢，试了这个方法可行

**Comment by jihabo** [comment]
> > 不过你后面proxy_state和ca_state都是fail，你重新导入一下证书试试？
> 
> 如已导入过证书且代理设置正确，与证书无关，锅在：
> 
> > > worker: h1:0 h2:0
> 
> 根在：
> 
> > （貌似导入得来的450，何处说要导入了？）
> 
> 自作主张，（能扫描但导入无效的）隧道、（不能扫描但导入有效的）原生方法混用，不遵循：#12455
> 潜规则：隧道已合格（连接）——控制页内 [IPv6状态](http://127.0.0.1:8085/?module=gae_proxy&menu=status)🆗——能扫描出 IP——XX-Net 才正常：有前才能有后
> 
> > 原来的帖子，比如
> > #12043 #11920 #11892
> 
> 时过境迁。。。（至少巨硬服务器全部已残）不然还更新干嘛？

大神息怒，
真的不是自作主张呀，
“导入IP”纯粹是因为病急乱投医 (ㄒoㄒ)，
而且真的也不清楚有什么具体作用，以及影响，
看到有人说好用就抓来用了......
这个把good_ip.txt 删了，就可以重置IP数了吧？

另外我这边“IP扫描线程数设置”默认一直锁定100，
手动改成200的上限，点提交后，还是自动变成100，
就更不用说，改成您提到的突破200上限了。
是咋回事捏？
