### ISSUE TITLE
LTSC2019 拨号上网 无法正确设置代理

### ISSUE THREAD

**Issue by smalljust** [XX-net/XX-Net#12574]
新装的系统，XX-net始终显示为取消全局代理，点其他的几个代理无反应。

状态页面为：

浏览器代理设置 | Fail
CA 证书状态(下载) | Fail
系统代理 | 全局 PAC 代理

系统代理已设置，但没有作用。(不排除是Windows的bug)
![捕获](https://user-images.githubusercontent.com/46310942/59048478-7f24f800-88b8-11e9-9cd0-0e70439d0145.PNG)

**Comment by AnyWAT** [comment]
孤陋寡闻：LTSC2019 是神马？
截图上有：http://127.0.0.1:8086/proxy.pac 莫非没启用Smart Router 模块（禁用端口8086）而选用过全局PAC代理后出的故障？
检查 config.yaml 文件，https://github.com/XX-net/XX-Net/issues/12548#issuecomment-496851203

**Comment by smalljust** [comment]
对就是win10 LTSC2019 已查明是拨号上网的锅 直接上网可正常使用

**Comment by AnyWAT** [comment]
不会是网络连接的中文名称“宽带连接”引发？试试英文。。。

**Comment by smalljust** [comment]
可能  但是不想折腾了QAQ
