### ISSUE TITLE
显示 PYTHONW.EXE以停止工作！！！！

### ISSUE THREAD

**Issue by GFconcept** [XX-net/XX-Net#12589]
好不容易连上会 传输大小都是几十B  连KB都不到！！！！！

**Comment by GFconcept** [comment]
显示 PYTHONW.EXE以停止工作！！！！

**Comment by AnyWAT** [comment]
> 传输大小都是几十B 连KB都不到

几M都有

> 显示 PYTHONW.EXE以停止工作

隧道偶有，原生极少。机器上木有某些国产？再次启动即可。

**Comment by GFconcept** [comment]
装有360浏览器  和火绒杀毒软件 但是以前也装了的   没发生过这情况  就是这段时间才开始的 打开不到一会就退出了！！ 还有 禁用了那三个前端后 直接没法启动了！！！

**Comment by GFconcept** [comment]
进程：GAEProxy 无响应, 可能已退出。

**Comment by GFconcept** [comment]
![QQ截图20190614185409](https://user-images.githubusercontent.com/12656650/59504575-d557f380-8ed5-11e9-9315-d8c897a58e7f.jpg)

**Comment by GFconcept** [comment]
弄了一天了 就有那么 一小会能上去 而且IP满满~

**Comment by GFconcept** [comment]
还有就是这个提示 草  连接服务器失败：session server login fail:602

**Comment by AnyWAT** [comment]
> 装有360浏览器 和火绒杀毒软件 但是以前也装了的 没发生过这情况 就是这段时间才开始的 打开不到一会就退出了！！ 还有 禁用了那三个前端后 直接没法启动了！！！

此一时彼一时。。。
禁用了那三个前端，因修改的全英文标点等文件格式错误而。。。

> 连接服务器失败：session server login fail:602

因XX-Net 不正常，连接池归零。。。

**Comment by GFconcept** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 706
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
