### ISSUE TITLE
披露一个骗子

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#12584]
Github ID： gh030119； 邮箱：hao@54sxh.cn

去年在这里发帖，询问有没有靠谱收费梯子推荐，这个人冒出来自我推荐。参见：https://github.com/XX-net/XX-Net/issues/11737

前几天因为所有梯子都挂掉，xx-tunnel又经常退出，就联系了他，说好了5块钱试用一周。结果支付宝转了5块钱后，丫就再也不回我的消息了。

肯定是个骗子无疑。请大家提高警惕！

**Comment by oneapp1e** [comment]
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 http://t.cn/AiCgMp29  试试这个

**Comment by intelligentqi** [comment]
试试这个 http://t.cn/AiCgFLiY

**Comment by farshidvahid** [comment]
感谢楼上两位。先收藏了。

**Comment by gh030119** [comment]
我去你再说一遍，你是不是要我把截图发出来

**Comment by gh030119** [comment]
![8TN82OM)D3O4W(0F{Q6F23](https://user-images.githubusercontent.com/30427262/59547106-ba37c300-8f6b-11e9-8e68-a2f056084f96.png)
我不想说什么截图为证好吧，不说假话

**Comment by gh030119** [comment]
> Github ID：gh030119;邮箱：[hao@54sxh.cn](mailto:hao@54sxh.cn)
> 
> 去年在这里发帖，询问有没有靠谱收费梯子推荐，这个人冒出来自我推荐。参见：[＃11737](https://github.com/XX-net/XX-Net/issues/11737)
> 
> 前几天因为所有梯子都挂掉，XX-隧道又经常退出，就联系了他，说好了5块钱试用一周。结果支付宝转了5块钱后，丫就再也不回我的消息了。
> 
> 肯定是个骗子无疑。请大家提高警惕！

心知肚明好吧，良心人不做亏心事

**Comment by farshidvahid** [comment]
请大家直接看截图好了。

**Comment by farshidvahid** [comment]
![aa](https://user-images.githubusercontent.com/13399800/59550185-7dcf8b80-8f9a-11e9-9989-d31c853bd609.png)
![bb](https://user-images.githubusercontent.com/13399800/59550189-83c56c80-8f9a-11e9-8e61-e58e8771216e.png)

**Comment by farshidvahid** [comment]
第一次联系你，我的邮件都没被“误判”为垃圾邮件；转给你钱后，在已经联系了十几次后，就进入垃圾邮件了。牛逼，智能邮箱。

**Comment by gh030119** [comment]
那我问你我给没给你连接方式------------------ 原始邮件 ------------------
发件人: "farshidvahid"<notifications@github.com>
发送时间: 2019年6月15日(星期六) 晚上6:26
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com>;
抄送: "gh030119"<hao@54sxh.cn>;"Comment"<comment@noreply.github.com>;
主题: Re: [XX-net/XX-Net] 披露一个骗子 (#12584)



第一次联系你，我的邮&#x4EF6;都没被“误判”为垃圾邮&#x4EF6;；转给你钱后，在已经联系了十几次后，就进入垃圾邮&#x4EF6;了。牛逼，智能邮箱。
 
&mdash;

**Comment by farshidvahid** [comment]
我给出截图里，有一个链接，但那是收钱用的。你收完钱后，我再联系你，要你提供shdowsocks的IP，就再也没消息了。什么进入垃圾邮箱这么逊的理由你也编得出来。如果我不发这个帖子，你会邮件向我道歉，而且编这么逊的理由吗？5块钱真的我不在乎。我给地铁口的乞丐都十块。只是被骗的感觉实在不爽，也使得我对部分中国人存有更大的戒备之心。不和你撕逼了，不值得。我相信看了我的原版截图的人，只要稍微具备理智，就知道你是个骗钱的。这就足够了。

**Comment by gh030119** [comment]
ssr://OjgzODg6b3JpZ2luOmFlcy0yNTYtY2ZiOnBsYWluOi8_b2Jmc3BhcmFtPSZwcm90b3BhcmFtPSZyZW1hcmtzPVZXNTBhWFJzWldRJmdyb3VwPQ
来来来你用这个链接付钱试试

**Comment by gh030119** [comment]
只要通过这个链接转给我我百倍返还

**Comment by gh030119** [comment]
ssr开头是快速导入链接好吧

**Comment by gh030119** [comment]
![Screenshot_2019-06-15-18-49-45-31](https://user-images.githubusercontent.com/30427262/59550547-6e524180-8f9e-11e9-85b5-a593cb2a106f.png)
复制点击懂？
右键小飞机-服务器-剪切板导入你不懂？
稍微知道ssr连接的都知道有ssr连接地址这个东西吧

**Comment by gh030119** [comment]
![S512O01A$T N55N}0AMB0BC](https://user-images.githubusercontent.com/30427262/59550582-dc970400-8f9e-11e9-8847-e145b4984726.png)

**Comment by gh030119** [comment]
不瞎？
