### ISSUE TITLE
这几天teredo隧道用户无法接入IPV6啊？

### ISSUE THREAD

**Issue by 361450843** [XX-net/XX-Net#12580]

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12579#issuecomment-500315341
继续扯，从 https://github.com/XX-net/XX-Net/issues/12577 到 https://github.com/XX-net/XX-Net/issues/12578 到这里。。。

**Comment by htpao2** [comment]
AnyWAT
我从6月4日开始ip大量下降，6日开始怎么换服务器也连不上【teredo服务器正常】，好像连不上连接池
今天突然连的上，就是ip上不去
![Annotation 2019-06-10 154031](https://user-images.githubusercontent.com/45194070/59180387-67d75a80-8b97-11e9-9094-860ae5f09fd4.png)

**Comment by AnyWAT** [comment]
近期原生好过隧道。如坚持用隧道，仍旧是 #12455 但得加码：突破软件最大扫描线程数200或许有惊喜 https://github.com/XX-net/XX-Net/issues/12562#issuecomment-499087184 有图为证：https://github.com/XX-net/XX-Net/issues/12579#issuecomment-500332575

**Comment by jihabo** [comment]
> 近期原生好过隧道。如坚持用隧道，仍旧是 #12455 但得加码：突破软件最大扫描线程数200或许有惊喜 [#12562 (comment)](https://github.com/XX-net/XX-Net/issues/12562#issuecomment-499087184) 有图为证：[#12579 (comment)](https://github.com/XX-net/XX-Net/issues/12579#issuecomment-500332575)
> 或许得再次改小总 IP数了😱

![QQ图片20190616170209](https://user-images.githubusercontent.com/51581040/59561970-e5e4a700-9058-11e9-89f3-dfdca97d96ab.png)
请问这个默认的100，
我手动改了好几次200，
然后点提交，
但都不生效，一直锁定100，是什么原因呀？
