### ISSUE TITLE
关于连接池的问题

### ISSUE THREAD

**Issue by Rookie14** [XX-net/XX-Net#12583]
4、5月份到时候捣鼓一段时间XX-Net,但还是不太成功。后来由于工作太忙也就没怎么管它，现在感觉有这么几点总是解决不了，还是请高人指教！
1、在网页显示“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。”依旧无法使用Google及YouTube，我感觉原因就在于连接池数量太少，“新:0 h1:0 h2:7”，上不了双 恐怕都是白扯，即便上双也是不行““新:0 h1:0 h2:35”，（刚才就是这样，我想发个截图都提示“Something went really wrong,and we can't process that file.Try again”）。
2、下载了gscan_quic，也用它筛出一些IP，现在每次显示一切正常但实际并不理想。我的IP源是从IP 段列表里找的，因为我真的不知道去哪里找这玩意，还希望了解指条明路……
3、有效IP/总IP=1，这一步感觉好难实现，筛出来IP不同时间段总是再掉，无法保证两者比值为1。
4、前两天，尤其是高考之前我连GitHub都登录不了，好像提示什么意外断开，需要不停的刷新才能打开网站，也看过网站里的帖子，特殊时期特殊对待吗，可以理解。后来我用最原始的方法——修改hosts，把这个小坎儿迈过去了，但它不像过去可以解决登录Google的问题，改hosts只能解决登录GitHub的问题……(lll￢ω￢)也许还是方法不对
5、dnscrypt-proxy感觉打开也没多大作用，莫非是要放到那个子目录下面？可能没找对路子，还请说的再详细详细些，毕竟是个老白……
6、像config.json文件及config.py这类的文件都已经调整过，是不是要不停地试，从而选出最佳配置？那样的话关键没有那么多时间……

其实，我觉得目前归根结底的问题就是**连接池——IP源**，**连接池——IP源**，**连接池——IP源**！！！请问这个问题怎么解决

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:404 ipv4:76 ipv6:6
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:5
scan-ip-thread-num: 10
ip-quality: 2070
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : 195.140.195.140
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : ——————————
外部 NAT 映射    : ——————————

**Comment by SeaHOH** [comment]
看你只提到两个网站，如果不介意些许折腾的话，可以使用另一个我写的工具，谷歌可以开箱即用，其它看情况修改配置。

**Comment by Rookie14** [comment]
> 看你只提到两个网站，如果不介意些许折腾的话，可以使用另一个我写的工具，谷歌可以开箱即用，其它看情况修改配置。

请问工具名称是什么？

**Comment by AnyWAT** [comment]
> 2、下载了gscan_quic，也用它筛出一些IP，现在每次显示一切正常但实际并不理想。我的IP源是从IP 段列表里找的，因为我真的不知道去哪里找这玩意，还希望了解指条明路……
> 3、有效IP/总IP=1，这一步感觉好难实现，筛出来IP不同时间段总是再掉，无法保证两者比值为1。

🤣不要将隧道 #12455 与原生 #12477 两种模式的方法混用！

> 1、在网页显示“XX-Net 3.13.1，一切正常，你可以访问真正的互联网了。”依旧无法使用Google及YouTube，我感觉原因就在于连接池数量太少，“新:0 h1:0 h2:7”，上不了双 恐怕都是白扯，即便上双也是不行““新:0 h1:0 h2:35”，（刚才就是这样，我想发个截图都提示“Something went really wrong,and we can't process that file.Try again”）。
> 4、前两天，尤其是高考之前我连GitHub都登录不了，好像提示什么意外断开，需要不停的刷新才能打开网站，也看过网站里的帖子，特殊时期特殊对待吗，可以理解。后来我用最原始的方法——修改hosts，把这个小坎儿迈过去了，但它不像过去可以解决登录Google的问题，改hosts只能解决登录GitHub的问题……(lll￢ω￢)也许还是方法不对

😥（任意网址）通则：直连不行试试代理？

> gws-ip-num: total:404 ipv4:76 ipv6:6
> scan-ip-thread-num: 10

是否遵循了 #12455 
古云：温故知新。。。

**Comment by AnyWAT** [comment]
> 5、dnscrypt-proxy感觉打开也没多大作用，莫非是要放到那个子目录下面？可能没找对路子，还请说的再详细详细些，毕竟是个老白……
> 还是请高人指教！

😱一边。。。一边自以为是。。。

**Comment by YangZhengHuan** [comment]
能告诉我怎么上YouTube吗，我这个一直还是不行呀

**Comment by AnyWAT** [comment]
> 能告诉我怎么上YouTube吗，我这个一直还是不行呀

歧义：不会上YB？XX-Net 不行上不了YB？
Teredo 隧道 #12455 或原生 #12477 近期原生更佳，对YB更是。

**Comment by YangZhengHuan** [comment]
@AnyWAT 不好意思刚才没说清楚，再弱弱的问一下，怎么购买收费的版本，能给一个url吗

**Comment by AnyWAT** [comment]
不知神马收费的版本，版主在2楼🙃

**Comment by SeaHOH** [comment]
> 请问工具名称是什么？

点我的头像就能看到，不直接推荐是因为不如 XX-Net 易用。

> upside_down_face纯老白用户不知神马收费的版本，版主在2楼

你不就是嘛，反正挺能扯的。

**Comment by hubsocks** [comment]
@Rookie14 你这搞的太复杂了.xx-net直接把IP 模式改为仅ipv4.马上问题全部解决了.
如果你不想用xx-net, 用goproxy,绑定免费域名,禁用ipv6,速度也还可以.
封锁高峰期就百度一下清华大学,中科院的代理,检测上能用的.晚上电脑上油管上看2k视频完全没问题.

**Comment by AnyWAT** [comment]
> 用goproxy,

怎么搞定诸如：
502 Bad Gateway
This HTTP request has a Host header that is not covered by the TLS certificate used. Due to an infrastructure change, this request cannot be processed.

**Comment by AnyWAT** [comment]
@xxnet @xx-net 
截图留存，到底谁扯：

![image](https://user-images.githubusercontent.com/37962734/59505746-e1918000-8ed8-11e9-9185-f0abead9f387.png)

**Comment by xxnet** [comment]
抱歉各位，近期个人事务繁忙，没有精力参与太多。

但我不希望看到大家都出于好心，却自己斗起来。

天道灰暗，心存梦想的人们，更加要团结。

先感谢各位对社区的热心和贡献，没有你们大家的付出，社区就是冰冷的一堆代码而已。

如何让社区发挥力量，大家一起摸索，争论也可以，大家理智、冷静讨论。
@AnyWAT  感谢你的热心
如果能够用清晰的语言来沟通更好，用有逻辑性的语言来表达，很重要！
一开始可能不习惯，可以写完文字再改多两遍，慢慢就会好。
还有，请尊重其他人。
请给我发邮件 xxnet.dev@gmail.com，我希望能够再和你讨论。

**Comment by valasco** [comment]
目前的几个源都快没鸟用了....在mojave下就算miredo是OK的，但是xx-net照样掉IP数直至0.然后gameover~主程序不更新啥都是白搭...还好主要也就是看看政治相声和听听几个人的驰放，其他不用~
