### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 15816703013** [XX-net/XX-Net#12582]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by 15816703013** [comment]
![image](https://user-images.githubusercontent.com/22829665/59254195-527b3280-8c62-11e9-9059-0e176ecfdfc9.png)

**Comment by AnyWAT** [comment]
Teredo隧道 #12455 或原生 #12477 近期后者更佳

**Comment by 15816703013** [comment]
如何更改Teredo隧道


15816703013@163.com
 
发件人： AnyWAT
发送时间： 2019-06-11 16:36
收件人： XX-net/XX-Net
抄送： davis chen; Author
主题： Re: [XX-net/XX-Net] 无法使用 (#12582)
Teredo隧道 #12455 或原生 #12477 近期后者更佳

**Comment by AnyWAT** [comment]
> 如何更改Teredo隧道

#12455 —— #12043

**Comment by 15816703013** [comment]
能否远程协助下，小白一个完全不懂



15816703013@163.com
 
发件人： AnyWAT
发送时间： 2019-06-11 17:02
收件人： XX-net/XX-Net
抄送： davis chen; Author
主题： Re: [XX-net/XX-Net] 无法使用 (#12582)
如何更改Teredo隧道
#12455 —— #12043

**Comment by 15816703013** [comment]
电脑有安装TeamViewer



15816703013@163.com
 
发件人： AnyWAT
发送时间： 2019-06-11 17:02
收件人： XX-net/XX-Net
抄送： davis chen; Author
主题： Re: [XX-net/XX-Net] 无法使用 (#12582)
如何更改Teredo隧道
#12455 —— #12043

**Comment by intelligentqi** [comment]
试试这个http://t.cn/AiCgFLiY

**Comment by 15816703013** [comment]
跟XX-NET是一样的后台吗？XX-NET我刚买的会员




15816703013@163.com
 
发件人： intelligentqi
发送时间： 2019-06-13 16:00
收件人： XX-net/XX-Net
抄送： davis chen; Author
主题： Re: [XX-net/XX-Net] 无法使用 (#12582)
试试这个http://t.cn/AiCgFLiY

**Comment by intelligentqi** [comment]
> 跟XX-NET是一样的后台吗？XX-NET我刚买的会员 15816703013@163.com 发件人： intelligentqi 发送时间： 2019-06-13 16:00 收件人： XX-net/XX-Net 抄送： davis chen; Author 主题： Re: [XX-net/XX-Net] 无法使用 (#12582) 试试这个http://t.cn/AiCgFLiY — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

不是
