### ISSUE TITLE
github都要翻墙了。

### ISSUE THREAD

**Issue by FergonXie** [XX-net/XX-Net#12596]
* X-Tunnel 支付相关问题请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by FergonXie** [comment]
是不是香港搞反送中导致的？

**Comment by broardshore** [comment]
并没有
