### ISSUE TITLE
xx-net频繁崩溃，请问有错误日志嘛？我搜了一下文件目录，没看到记录软件崩溃日志的地方

### ISSUE THREAD

**Issue by Jack-ban** [XX-net/XX-Net#12598]
软件又好久没有更新了，但是`windows10 `的更新倒是特别频繁。不知道是不是对新系统的兼容性不好，时常会出现软件崩溃闪退的情况。
之前留意过，在笔记本合盖睡眠重新开启电脑后，有相当的概率在使用一段时间后自动闪退。但是最近发现似乎并没有什么直接联系。比如上述情况闪退后，我自己重新启动`xx-net`。有时候还是会闪退，频率也不算高，无法稳定复现场景。
所以问一下哪里是存放错误日志的，之后可以一并贴上供大佬们分析。
以下是系统信息：
```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
目前主力是使用`x-tunnel`，纯`GAE`在我这边已经好久没有搜索到有效`IP`。让我比较头疼的是，几个前端服务器时常连接不上。基本上其实就一个`Cloudflare`前端能用，完全不能用的已经禁用，留了一个时断时续的`Cloudfront`。

**Comment by hubsocks** [comment]
@SeaHOH 希望能解决pythonw.exe关闭的问题.有时一天要来几次,估计是某个多线程出错就这样了.扫描设为2,ip模式为仅ipv4,只有是与8087通讯就有可能出错.

**Comment by SeaHOH** [comment]
日志存放于 data/launcher 文件夹。
如果是休眠或更新造成的，只改代码可能没法解决。
可以尝试使用最新的 python 版本，现在是 2.7.16。

**Comment by Jack-ban** [comment]
@SeaHOH 我看过这个文件，但是当时崩溃的时候，该文件显示的修改时间是好几天前的。所以当时我觉得可能不是这个。内容我贴出来。你帮忙看看吧。
```
May 03 21:41:56.406 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x04DCAA80>May 12 19:29:52.473 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x3254E0D0>
```

**Comment by SeaHOH** [comment]
贴出完整日志，只有最后一行没用。

**Comment by Jack-ban** [comment]
额。这个就是`error.log`的完整内容呀。
你难道要`launcher.log`的内容。
[launcher.log](https://github.com/XX-net/XX-Net/files/3314958/launcher.log)
也不知道里面有没有什么个人敏感文件。如果有的话，提醒我删除掉吧。
我一直以为，`error`里面存在的是崩溃日志，`launcher`里面是运行过程中连接的情况。
最近倒是没有发生过崩溃，即使我合盖休眠之后也一样。没理由是偶发事件呀，前一个多星期就是这样的。

**Comment by SeaHOH** [comment]
最早只记录到 14 号，没发现崩溃相关信息。
launcher 就是主线程，负责加载子模块，并记录运行状况，一般情况下不会记录到个人信息。

Windows 下这种崩溃，一般都是 Win10，谨慎系统更新，关注硬件驱动更新。

**Comment by Jack-ban** [comment]
好的。还有一个文件，也不知怎么被命名为`launcher.log.1`。改了后缀名上传成功。劳烦你在帮忙看看有没有崩溃日志。

[launcher1.log](https://github.com/XX-net/XX-Net/files/3315125/launcher1.log)

**Comment by SeaHOH** [comment]
看起来记录不到相关日志，这是正常的。
比较可靠的记录下崩溃信息的方法是使用控制台版本的 python.exe，崩溃时会在控制台显示错误信息。

**Comment by SeaHOH** [comment]
`launcher.log.1` 是一种被称为`rotating`的日志记录方式所使用的文件名称格式。

**Comment by Jack-ban** [comment]
多谢指教。如果没有什么其他的，可以关掉这个话题了。

**Comment by SeaHOH** [comment]
OK。

微软更新策略过于激进，可能对过去发布的程序会有一些不兼容。
你可以尝试自行替换 XX-Net 内置的 python 版本，也许会有改善。
