### ISSUE TITLE
曾经非常好用的XX-NET现在是用不上了。

### ISSUE THREAD

**Issue by onetree79** [XX-net/XX-Net#12591]
原来用XX-net，免费，速度还快，可是现在呢，大国的网络环境实在是太差了。
原先XX-NET是出国的主力，现在却没法用了。折腾了好几次，放弃了。
后来就是在google+上找免费的ssr，但是也不稳定，说不定是什么时候就挂了，
再后来，google+也关了。原来可以用的几个SSR也用不了。
最近一个多月，都没有出去了。
前两天没办法买了SSR，流量少，还好能用的。付费的确实比较好，速度快，也不知道能坚持多久。
今天刚发现一个加速器（就是代理），因为有活动，推荐可以送流量的。
在这里我就厚脸皮分享下了，速度挺快的。安卓版，也有免费的线路，不过还是付费线路快。
[点击这里下载](https://aff.antss007.com/aff/gVZ4)
最好是安卓手机，方便，也有电脑版和苹果版的
如果这条信息对你有用，请在安装应用后，填写推荐码：gVZ4
活动时间有限，推荐10人，就可以不限流量了。
也不知道这只羊能坚持到什么时候。呵呵。。。。。

**Comment by AnyWAT** [comment]
Teredo 隧道 #12455 或原生 #12477 近期后者更佳

**Comment by AnyWAT** [comment]
😱这也删，有码犹兵，无耻之尤！

**Comment by styrenes** [comment]
gae bu xing le .
tunnel hai xing.

**Comment by broardshore** [comment]
偶尔搜索点儿东西用setupvpn插件，一般用ss居多，节点是自己搭的。如果要下载东西、看视频就随时到一个免费节点网站弄几个免费节点专门用来下载。
