### ISSUE TITLE
代理取消全局代理

### ISSUE THREAD

**Issue by XiangBicheng** [XX-net/XX-Net#12590]
当勾选取消全局代理后，使用chrome浏览网站时，仍然表现为是在通过xx-net访问网站，比如国内网站延迟较高、YouTube可以直接访问等表现，如何解决?

**Comment by Tpwick123** [comment]
装Proxy SwitchyOmega
然后导入配置文件就是了

**Comment by XiangBicheng** [comment]
但是我不是问怎么使用啊，我是想知道怎么解决这个问题。

**Comment by AnyWAT** [comment]
不想装Proxy SwitchyOmega，试试：清除 chrome 缓存或重启浏览器

**Comment by Tpwick123** [comment]
> 但是我不是问怎么使用啊，我是想知道怎么解决这个问题。

确认一下这个
![4361](https://user-images.githubusercontent.com/45484188/59512593-9f256e80-8eeb-11e9-8651-0b6388014b25.png)

就是用这个来搞啊
![12](https://user-images.githubusercontent.com/45484188/59512402-405ff500-8eeb-11e9-9731-0f29310b877b.png)
要直连就点直接连接就是
要xx-net代理就用这个gae-proxy

实在不行pac
