### ISSUE TITLE
购买季度套餐后流量没有增加

### ISSUE THREAD

**Issue by Felixchen1024** [XX-net/XX-Net#12593]
购买季度流量，可是并没有增加。登录邮箱与PAYPAL付款的邮箱不是同一个，是否是因为这个原因呢？

**Comment by SeaHOH** [comment]
请给 xxnet.dev@gmail.com 发邮件描述情况，并附上交易单号。

**Comment by Felixchen1024** [comment]
已发邮件，麻烦查收下。

**Comment by SeaHOH** [comment]
这不是我的，@xxnet 会处理。

**Comment by Illchange** [comment]
paypal怎么用 我添加了银联卡但支付不了

**Comment by Felixchen1024** [comment]
我也是昨天刚注册的，添加的是招商信用卡，可以正常支付，你可以参考下

Illchange <notifications@github.com> 于2019年6月17日周一 下午8:18写道：

**Comment by Felixchen1024** [comment]
@xxnet 你好，请问有收到邮件吗？流量还未到账，剩余流量马上用完了，麻烦看到了回复个

**Comment by xxnet** [comment]
@Felixchen1024 
 已经给你回信了

**Comment by Felixchen1024** [comment]
10G流量已收到，十分感谢~！

2019-06-18 17:20 GMT+08:00, Michael.X <notifications@github.com>:

**Comment by folime** [comment]
所以只能用中国内地只有招商银行的卡才能支付吗
