### ISSUE TITLE
ipv6服务器不能用了

### ISSUE THREAD

**Issue by rainchen1024** [XX-net/XX-Net#12594]
用xx-net很久了，一直很稳定，但是最近不知道怎么就不能用了，幸好找了一个又稳定又免费的软件，[点击下载](https://aff.antss007.com/aff/hurh)，有人用的话记得填我的邀请码：hurh ,邀请10个人永久无线流量。

**Comment by panghu1986** [comment]
费那事干嘛，推荐你用一个吧，非常好用，免费的机场。
https://bighead.szccmdj.com.cn/   每天登陆送1-5GB不等。基本上沟通，套餐也非常便宜。

注册码：3DC583B09747

rainchen1024 <notifications@github.com> 於 2019年6月17日 週一 下午8:26寫道：
