### ISSUE TITLE
为啥GFW只在敏感日子发飙而不能在平是也保持发飙的状态？

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12604]
GFW是怎么攻击这些代理工具的？为啥只在人大会、党代会、国殇日、沦陷日等重要时间发飙？如果在这些敏感日子可以瘫痪大部分代理工具的话，为什么平时却不大范围打击呢，而只在那些敏感日子攻击？

**Comment by broardshore** [comment]
我感觉就和每逢节日，不管是企业还是政府部门，领导们检查、抽查的时候的做事的样子

**Comment by SeaHOH** [comment]
https://hikinggfw.org/blocked_sites 这里指出了其中三种拦截方式。
如果你真的有兴趣了解其中原理，请使用网页搜索引擎，这方面的解析文章已经有很多。

至于后一个问题，这就涉及到经济和政治方面，付出、收益、效率、后果，具体分析也可以参考网上相关文章。

**Comment by 2378** [comment]
油管那个光头说，只要华为连续被制裁半年，GFW就会开始瘫痪～

**Comment by SeaHOH** [comment]
有其它更合适的平台，没必要在这里讨论这种问题，这里主要是解决技术问题。
