### ISSUE TITLE
坐标上海电信 有100个IP可用

### ISSUE THREAD

**Issue by drioou** [XX-net/XX-Net#12605]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 100
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 360
连接池(帮助) | 新:0 h1:0 h2:27
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 1

**Comment by A372872** [comment]
求分享IP_range,谢谢
