### ISSUE TITLE
浙江海宁一家外贸企业因涉嫌FQ被问责。。。

### ISSUE THREAD

**Issue by jazzcat31** [XX-net/XX-Net#12606]
RT

https://zj.zjol.com.cn/news/1221188.html

**Comment by SeaHOH** [comment]
旧闻

**Comment by 2378** [comment]
就上个周的事，不算旧闻吧 :confused:

**Comment by SeaHOH** [comment]
这里不是信息发布平台。
ps：浙江新闻发布的这条新闻已经被和谐，正经地做法怎么也该给出存档快照，或增加引用其它来源。
