### ISSUE TITLE
一切正常，但是打不开国外网站

### ISSUE THREAD

**Issue by jackzhum** [XX-net/XX-Net#12602]
一切正常，但是还是不能上网。版本为最新版。

诊断日志：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:106 ipv4:0 ipv6:106
ipv4-status: OK
ipv6-status: OK
connected-link: new:13
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 286
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
看起来是 IP 连接不顺畅。
1. 你可以参考置顶贴，增加使用那里提到的可用新 IP。
1. 再参考之前的发布说明，调整最大 IP 数到 200 - 300，扫描线程 5 - 10。

**Comment by jackzhum** [comment]
@SeaHOH 感谢!我去试试

**Comment by belleyeah** [comment]
@SeaHOH, 请问参考哪个置顶帖？谢谢！

**Comment by SeaHOH** [comment]
完整看一遍那个发布贴
