### ISSUE TITLE
“start”已损坏，打不开。 您应该将它移到废纸篓。

### ISSUE THREAD

**Issue by zDaoYang** [XX-net/XX-Net#12609]
如图
![image](https://user-images.githubusercontent.com/26763518/60241929-0af1d900-98e7-11e9-9a73-df4ca713f3bf.png)

**Comment by SeaHOH** [comment]
善用搜索
https://www.google.com/search?oe=utf-8&q=已损坏，打不开。您应该将它移到废纸篓
