### ISSUE TITLE
请大神评估一下我的IPV6状况！

### ISSUE THREAD

**Issue by jihabo** [XX-net/XX-Net#12603]
![QQ图片20190620090336](https://user-images.githubusercontent.com/51581040/59811002-7dd4e000-933a-11e9-870f-c5d0669d8cb1.png)

![QQ图片20190620090620](https://user-images.githubusercontent.com/51581040/59811046-b83e7d00-933a-11e9-891e-1513300e7e23.png)

![59175417-0c51a080-8b88-11e9-903a-79f32fa6c493](https://user-images.githubusercontent.com/51581040/59811192-59c5ce80-933b-11e9-83de-5e75f029b9e0.png)

前两张是http://test-ipv6.com的测试结果。

**Comment by jihabo** [comment]
![QQ图片20190620091719](https://user-images.githubusercontent.com/51581040/59811435-89c1a180-933c-11e9-9ac6-f05951d9596f.png)

XXNET设置页里的IPV6状态，
经常一直显示Fail。
偶尔IPV6状态显示OK，但也连不上....
（下面那两个Fail，浏览器代理设置，和CA证书的，
以前好用的时候也都是Fail，所以我就一直没在意。）

**Comment by jihabo** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:450
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 100
is-idle: 1
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

再补个XXNET里的状态列表，
完全看不懂....

请大神指点迷津呀(ㄒoㄒ)

**Comment by SeaHOH** [comment]
test-ipv6 结果很清楚：
虽然可以连接上 IP，但没法传数据，没法正常使用。

处理方法：
1. 更换 teredo 服务器
1. 使用其它类型的隧道
1. 尝试 IPv4
1. 使用 XX-Net 之外的其它方法

**Comment by gmctl** [comment]
上面兄弟总结得很完整

**Comment by jihabo** [comment]
> test-ipv6 结果很清楚：
> 虽然可以连接上 IP，但没法传数据，没法正常使用。
> 
> 处理方法：
> 
> 1. 更换 teredo 服务器
> 2. 使用其它类型的隧道
> 3. 尝试 IPv4
> 4. 使用 XX-Net 之外的其它方法

感谢大神的几条锦囊妙计，
可我除了第4个，
其他的都不明白怎么弄呀(ㄒoㄒ)

**Comment by SeaHOH** [comment]
> 可我除了第4个，
> 其他的都不明白怎么弄呀(ㄒoㄒ)

看 https://github.com/XX-net/XX-Net/wiki/如何开启IPv6 ，有方法，有工具。

IPv4 还需要**增加**导入一些 IP，看置顶的那个版本更新，可以找到一些 IP。
