### ISSUE TITLE
ipv6死活开启不了？

### ISSUE THREAD

**Issue by Testrfr2018** [XX-net/XX-Net#12607]
一步一步按照教程做，但是搞了1天还没弄好，不知道是不是ipv6没开启成功，所以状态fail。请各位大佬支招，谢谢：

![捕获3](https://user-images.githubusercontent.com/38790034/59971485-723e1f00-95af-11e9-81bd-8d4cc1dee16a.JPG)
![捕获4](https://user-images.githubusercontent.com/38790034/59971487-884bdf80-95af-11e9-8554-9d3e11636c9d.JPG)

IPv4 域名连接测试 |   | 成功 (0.282s) 使用 ipv4
IPv6 域名连接测试 |   | 失败 (0.009s)
双栈域名连接测试 |   | 成功 (0.267s) 使用 ipv4
双栈域名大数据包传输测试 |   | 成功 (0.520s) 使用 ipv4
无域名 IPv4 连接测试 |   | 跳过 (0.470s)
无域名 IPv6 连接测试 |   | 跳过 (9.683s)
IPv6 大数据包传输测试 |   | 失败 (0.017s)
测试运营商 DNS 是否接入 IPv6 |   | 失败 (0.366s)
查询 IPv4 运营商 |   | 成功 (0.251s) 使用 ipv4 ASN 4134
查询 IPv6 运营商 |   | 失败 (0.013s)

路由器是R7000无线上网、用的电信光猫。已经禁用了原生ipv6。

IPv4 状态 | OK
IPv6 状态(如何开启) | Fail (尝试修复)
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 12
XX-Net 状态 | 空闲
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 100

XX-Net Version | 3.13.1
Python Version | 2.7.13
OpenSSL Version | 16.0.0 TLSv1_2 h2:alpn
System Platform | AMD64, Windows-10-10.0.17134
OS System | Windows
OS Version | 10.0.17134
OS Release | 10
Language | zh_CN
Architecture | 32bit,WindowsPE
Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by SeaHOH** [comment]
不一定非要用 teredo，还有其它各种类型的隧道，而且现在的光猫都有分配原生 IPv6。

**Comment by Testrfr2018** [comment]
> 不一定非要用 teredo，还有其它各种类型的隧道，而且现在的光猫都有分配原生 IPv6。

谢谢，确实有原生，但是原生的有墙……而且没有找到原生IPV6 FQ的教程。

**Comment by Testrfr2018** [comment]
扫描了一天，终于有20个有效IP了，感觉应该是IP太少导致fail。

**Comment by SeaHOH** [comment]
那么你的测试没做对，test-ipv6 必须直连，不能用代理，不然测试的就是代理。
