### ISSUE TITLE
IPV6测试可用，但是IP延迟9999，建议开启IPV6？

### ISSUE THREAD

**Issue by libitya** [XX-net/XX-Net#12615]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

救命。。。。

**Comment by SeaHOH** [comment]
#12610 和你的情况类似，可以参考 https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262 的操作。

**Comment by libitya** [comment]
> #12610 和你的情况类似，可以参考 [#12610 (comment)](https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262) 的操作。

其实IP延迟9999是啥情况？现在证书也OK，就是IP延迟9999
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv4
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
没有 IP 啊，怎么可能会正常工作。
你可以在置顶贴里面找一遍，有一些可用 IP。

**Comment by libitya** [comment]
> 没有 IP 啊，怎么可能会正常工作。
> 你可以在置顶贴里面找一遍，有一些可用 IP。

关闭网络协议得ipv6后变得可用了....原理不明

**Comment by libitya** [comment]
现在情况大概跟#12610一样了，就十来秒能用，后面就直接9999了 。。。。降低扫描条数或者修改config.json问题依旧

**Comment by libitya** [comment]
> 没有 IP 啊，怎么可能会正常工作。
> 你可以在置顶贴里面找一遍，有一些可用 IP。

现在情况大概跟https://github.com/XX-net/XX-Net/issues/12610#issue-461938462一样了，就十来秒能用，后面就直接9999了 。。。。降低扫描条数或者修改config.json问题依旧

**Comment by libitya** [comment]
[#12610](url)

**Comment by libitya** [comment]
> 没有 IP 啊，怎么可能会正常工作。
> 你可以在置顶贴里面找一遍，有一些可用 IP。

现在情况跟[#12610 ](url)一样了，就十来秒能用，后面直接“仅IPV6不可用”，降低扫描IP条数或者修改config.json问题依旧

**Comment by SeaHOH** [comment]
> 关闭网络协议得ipv6后变得可用了

之前是原生 IPv6，关闭后是 teredo 隧道。

情况严重的话，禁用自动扫描，手动替换 good_ip.txt 中的 IP，并参照 https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262 第 2 条操作，其它连接参数也调低点。

**Comment by libitya** [comment]
> > 关闭网络协议得ipv6后变得可用了
> 
> 之前是原生 IPv6，关闭后是 teredo 隧道。
> 
> 情况严重的话，禁用自动扫描，手动替换 good_ip.txt 中的 IP，并参照 [#12610 (comment)](https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262) 第 2 条操作，其它连接参数也调低点。
[#12610](url)第二条修改config.json是参照第二条里config.py中参数改json里的吗？

**Comment by SeaHOH** [comment]
是的，先设置为**被动**级别，扫描线程数设为 0，关闭自动调整，然后关闭 XX-Net 再调整。
config.py 有注释，参数名是比较直白的英文，理解上应该没问题。
