### ISSUE TITLE
关于在openSUSE上使用XX-net的问题

### ISSUE THREAD

**Issue by yipeterhan** [XX-net/XX-Net#12617]
openSUSE我真的试了很多办法……自己也不太会用这个系统，可以说是小白吧。
现在就是唯一一个问题，如何在openSUSE上开启teredo，剩下的真的就没啥了感觉……
之前看到有说miredo的，然而miredo怎么用……

**Comment by SeaHOH** [comment]
步骤和 #11570 差不多吧，反正是要自己编译。

这些问题已经讨论烂了，请通过 issues 附带的标签和搜索功能查询阅读。
如：https://github.com/XX-net/XX-Net/labels/分类_知识
