### ISSUE TITLE
咨询一个技术问题，为什么走http代理需要导入证书，x_tunnel走sock5代理不需要导入证书

### ISSUE THREAD

**Issue by UchihaKutter** [XX-net/XX-Net#12614]
最近手机已经root, 证书已导入系统信任，但是还是有一些app无法翻墙，原因是这些app不信任gae证书，但是走x_tunnel就可以，这里有个技术问题，为什么走http代理需要导入证书，x_tunnel走sock5代理不需要导入证书。

**Comment by SeaHOH** [comment]
这和 http、sock 等协议无关，根本原因在于 gae_proxy 中使用了**中间人**(**攻击**)方法，所以这里需要一个可信 CA 来签名(代理方)和验证(用户方)。

![](https://cloud.githubusercontent.com/assets/195836/4602738/ac950aba-5149-11e4-8976-a2606ba08e05.png)

为什么要纠结这种问题，这么长时间都没人能解决，说明它确实是个问题。

**Comment by UchihaKutter** [comment]
> 这和 http、sock 等协议无关，根本原因在于 gae_proxy 中使用了**中间人**(**攻击**)方法，所以这里需要一个可信 CA 来签名(代理方)和验证(用户方)。
> 
> ![](https://cloud.githubusercontent.com/assets/195836/4602738/ac950aba-5149-11e4-8976-a2606ba08e05.png)
> 
> 为什么要纠结这种问题，这么长时间都没人能解决，说明它确实是个问题。

那再请教一下，为什么gae_proxy 中使用了中间人(攻击)方法，这样做的目的在于加密内容吗，x_tunnel没有采用中间人(攻击)方法就可以翻墙，那它的内容是不是没有加密过

**Comment by SeaHOH** [comment]
你一直问还不如直接动手搜索。
https://www.google.com/search?oe=utf-8&q=中间人攻击
https://www.google.com/search?oe=utf-8&q=代理+原理+方式

**Comment by UchihaKutter** [comment]
> 你一直问还不如直接动手搜索。
> [https://www.google.com/search?oe=utf-8&q=中间人攻击](https://www.google.com/search?oe=utf-8&q=%E4%B8%AD%E9%97%B4%E4%BA%BA%E6%94%BB%E5%87%BB)
> [https://www.google.com/search?oe=utf-8&q=代理+原理+方式](https://www.google.com/search?oe=utf-8&q=%E4%BB%A3%E7%90%86+%E5%8E%9F%E7%90%86+%E6%96%B9%E5%BC%8F)

我搜索了一下，但是我有个疑问，为什么gae会采用中间人攻击方法，不采用隧道代理方式，这样的话不会出现手机app不信任证书这种情况

**Comment by SeaHOH** [comment]
**免费** GAE 就这样，毕竟这也是谷歌的一大业务。

**Comment by UchihaKutter** [comment]
> **免费** GAE 就这样，毕竟这也是谷歌的一大业务。

从技术上来讲，gae采用隧道代理方式有没有可行性

**Comment by SeaHOH** [comment]
还没看明白吗，这不是技术问题，**免费** GAE 不提供隧道(套接字)支持。

**Comment by UchihaKutter** [comment]
> GAE 不提供隧道(套接字)支持
你是指google app engine 平台不支持隧道(套接字)支持吗

**Comment by UchihaKutter** [comment]
> 还没看明白吗，这不是技术问题，**免费** GAE 不提供隧道(套接字)支持。

明白了，gae免费应用用不了socket

**Comment by SeaHOH** [comment]
> 你是指google app engine 平台不支持隧道(套接字)吗

花钱就可以。。。你是真看不懂嘛。
