### ISSUE TITLE
这几天IPV6连接断断续续的，有时可用有时不能用，现在又不能用了。有没有稳定的办法？

### ISSUE THREAD

**Issue by liuye1992** [XX-net/XX-Net#12616]
IPV6服务器重启动过好多次，显示Teredo 隧道合格，但依然连不上，
日志：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:86 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
你这情况比  #12610 还要好些，但是也可以参照 https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262 的方法修改参数。

**Comment by liuye1992** [comment]
> 你这情况比 #12610 还要好些，但是也可以参照 [#12610 (comment)](https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262) 的方法修改参数。

昨天都改过了，依然不行。现在ipv6状态就是一直失败。

**Comment by SeaHOH** [comment]
可以使用原生或其它隧道。

**Comment by liuye1992** [comment]
> 可以使用原生或其它隧道。

怎么设置？
更换过几次服务器 还是不行

**Comment by SeaHOH** [comment]
其它隧道 wiki 里面有方法。https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
原生可以翻看其它 issue，但是必需要运营商和设备都支持。

上面都不会的话，可以使用一些免费 SS 服务，github 上可以搜到一大堆这种项目。

**Comment by liuye1992** [comment]
> 其它隧道 wiki 里面有方法。[https://github.com/XX-net/XX-Net/wiki/如何开启IPv6](https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6)
> 原生可以翻看其它 issue，但是必需要运营商和设备都支持。
> 
> 上面都不会的话，可以使用一些免费 SS 服务，github 上可以搜到一大堆这种项目。

这个我早看了没用，另外用的是中国移动，估计没有原生的。
ss服务是vpn么？可以推荐一个？

**Comment by SeaHOH** [comment]
https://github.com/search?q=ss+分享

**Comment by liuye1992** [comment]
> [https://github.com/search?q=ss+分享](https://github.com/search?q=ss+%E5%88%86%E4%BA%AB)

原来还是vpn 这种原来部署过，速度很慢还得找节点。在墙内基本找不到。

**Comment by SeaHOH** [comment]
给你个手把手教程+全套傻瓜化下载合集，仔细看完哈，还不会我就没法了，你也不用再问。
https://github.com/Alvin9999/new-pac/wiki

**Comment by liuye1992** [comment]
> 给你个手把手教程+全套傻瓜化下载合集，仔细看完哈，还不会我就没法了，你也不用再问。
> https://github.com/Alvin9999/new-pac/wiki

多谢了

**Comment by hubsocks** [comment]
![22222222222](https://user-images.githubusercontent.com/46856823/60593780-0beaa500-9dd6-11e9-96c8-8da327ef9200.png)
这些天晚上高峰时段xx-net速度下降很多.如上图.有时会降到油管只有1千多K,120秒也难缓冲满.
晚上goproxy就不如xx-net了.油管只有1千多K,白天速度还可以.
ss被人工收集vps的ip段,再封锁.
其它隧道能容易找到的,也不行.它要求外网ipv4有开ICMP,运营商赌死这条路了.
微软为了自己在H利益,直接把数据转发服务器关闭了.
晚上高峰时段要4K油管就用爬虫搜代理.爬虫要自带测速度功能的才可以,

**Comment by CZtomato** [comment]
> 给你个手把手教程+全套傻瓜化下载合集，仔细看完哈，还不会我就没法了，你也不用再问。
> https://github.com/Alvin9999/new-pac/wiki

瞅了下有个什么神韵晚会，这好像是轮子做的？

**Comment by myjlpt** [comment]
@CZtomato  关于神韵，貌似正面，负面的评论都不少。外网好坏参半。大陆这边几乎清一色就不说了。但是外网相较几个比较还算有点名气的心理学，生物，历史学家的博文抨击恐怕不会是空穴来风。或被人教唆。

**Comment by jianeddie** [comment]
尝试下更换公用的dns

**Comment by ksit1110** [comment]
同移动   已经很久没用了  尝试更换现有的隧道都不行
