### ISSUE TITLE
在xxnet未启动时电脑自动打开代理设置，卸载删除后依然无法解决

### ISSUE THREAD

**Issue by cutesummer** [XX-net/XX-Net#12612]
xxnet未启动，但系统的代理设置总是自动打开，导致每隔一会儿就无法上网。
卸载和删除xxnet文件夹依旧无效。

尝试过：重置网络设置，重置浏览器，关闭账户同步，安装其他代理软件，修改注册表。

![Snipaste_2019-06-29_11-33-37](https://user-images.githubusercontent.com/31730806/60379223-c8a0d700-9a61-11e9-8908-557dd71c2c5a.png)

**Comment by SeaHOH** [comment]
既然 XX-Net 能启用代理设置，正常来讲就能关闭，如果不能，这就该是其它问题吧。
你是刚更新了系统吗？

**Comment by cutesummer** [comment]
是刚更新了系统。xxnet即便删除干净，也在不停的自动打开代理设置------------------ 原始邮件 ------------------发件人: SeaHOH  <notifications@github.com>发送时间: 2019年6月29日 12:06收件人: XX-net/XX-Net <XX-Net@noreply.github.com>抄送: cutesummer <zxygirl622@163.com>, Author <author@noreply.github.com>主题: 回复：[XX-net/XX-Net] 在xxnet未启动时电脑自动打开代理设置，卸载删除后依然无法解决 (#12612)既然 XX-Net 能启用代理设置，正常来讲就能关闭，如果不能，这就该是其它问题吧。
你是刚更新了系统吗？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/XX-net/XX-Net/issues/12612?email_source=notifications\u0026email_token=AHSCY5XO3LPBZ5UWGQVA2PTP43NUDA5CNFSM4H4JQGRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY3Q2HI#issuecomment-506924317",
"url": "https://github.com/XX-net/XX-Net/issues/12612?email_source=notifications\u0026email_token=AHSCY5XO3LPBZ5UWGQVA2PTP43NUDA5CNFSM4H4JQGRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY3Q2HI#issuecomment-506924317",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Hlinbit** [comment]
我也这个问题，简直让人崩溃

**Comment by SeaHOH** [comment]
说过很多次了，谨慎对待 Win10 的升级。
不要吃螃蟹，等段时间再看情况是否可以安全升级。

**Comment by cutesummer** [comment]
> 说过很多次了，谨慎对待 Win10 的升级。
> 不要吃螃蟹，等段时间再看情况是否可以安全升级。

在升级之前问题已经存在了……
这个“说过很多次”也太像教训人了吧😶
我试了很多方法都无效，猜测应该是设置自动代理的文件还在电脑上的缘故，但并找不到在哪里……

**Comment by SeaHOH** [comment]
>在升级之前问题已经存在了……

我问升级肯定是针对你出现这个问题的时间点。

>我试了很多方法都无效，猜测应该是设置自动代理的文件还在电脑上的缘故，但并找不到在哪里……

XX-Net 不会在本身的文件夹外存放除快捷方式、CA 证书之外的任何文件。
只是出现这个问题的时候刚好是设置为 XX-Net 代理，如果是其它代理地址，情况也会如此。

>这个“说过很多次”也太像教训人了吧no_mouth

不是随口习惯哈，其它问题我也没这样说过。
真的真的很多人都在说 Win10 更新问题，很多很多次，血淋淋的教训看得见。

**Comment by LingrenKong** [comment]
Windows10确实太有毒了，不知道什么时候就被升级了。
不过即使是非Windows软件，如果不打开XX-net也会有这个问题（比如说mathpix snipping tool的软件访问互联网失败）

**Comment by SeaHOH** [comment]
> 不过即使是非Windows软件，如果不打开XX-net也会有这个问题（比如说mathpix snipping tool的软件访问互联网失败）

MAC 也没法修改代理设置？没有收到过相关反馈，请给出详细信息。

**Comment by LingrenKong** [comment]
> > 不过即使是非Windows软件，如果不打开XX-net也会有这个问题（比如说mathpix snipping tool的软件访问互联网失败）
> 
> MAC 也没法修改代理设置？没有收到过相关反馈，请给出详细信息。

抱歉我没有说清楚，我是Windows电脑
运行XX-net情况下，除了应用商店都没有问题
但是停止运行XX-net后无法使用部分需要联网的应用程序（这个应用应该是把软件供应方的API打包添加了UI界面，必须联网使用）；尝试过重置网络设置，重置之后无法连接，依然需要用XX-net启动才可以使用。
非常感谢

**Comment by SeaHOH** [comment]
重置网络设置不等于重置代理设置。
看到上面那个设置界面没？取消代理设置就行。

不建议使用托盘工具提供的**全局代理**功能，一般用 SwitchyOmega 就行。

**Comment by LingrenKong** [comment]
> 重置网络设置不等于重置代理设置。
> 看到上面那个设置界面没？取消代理设置就行。

非常感谢，问题解决了

**Comment by SeaHOH** [comment]
这个问题没法解决，就这样。
