### ISSUE TITLE
绿灯就是爬不过去

### ISSUE THREAD

**Issue by jackbaifool** [XX-net/XX-Net#12611]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:22038 ipv4:0 ipv6:21503
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 100
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
#12610 和你的情况类似，可以参考 https://github.com/XX-net/XX-Net/issues/12610#issuecomment-506702262 的操作。
