### ISSUE TITLE
谁可以教教goproxy怎么用呀？看到很多大佬都在用goproxy

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12628]
XX-NET对网络条件要求太苛刻了，看到有很多大佬在用goproxy，但去了goproxy仓库看了看，感觉太硬核了，对于这种小白来说，看了简直就是一脸懵逼。有大佬可以说明一下怎么用吗？

**Comment by peach5460** [comment]
你得先有个服务器

**Comment by hubsocks** [comment]
goproxy 现在每天晚上高峰时段很卡.早上油管有6000K以上.到下午就越来越慢了.和xx-net情况差不多.
两个软件都是用ipv4才可以有这样的速度.
今天发现大批vpn(非vps)的ip解封了.

**Comment by 2378** [comment]
M大接手后的版本叫zebra ，实际效果也是看脸， 何况谷歌那种随时交投名状的态度
