### ISSUE TITLE
有时候很奇葩，这算不算是BUG？

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#12621]
“IPv6 状态”显示fail，但是还可以访问google，这算不算是BUG？

![01](https://user-images.githubusercontent.com/39740368/60595750-3dfe0600-9dda-11e9-9543-49d1620c66ec.jpg)

![02](https://user-images.githubusercontent.com/39740368/60595757-422a2380-9dda-11e9-9d34-96e7b08bcf20.jpg)

![03](https://user-images.githubusercontent.com/39740368/60595773-46564100-9dda-11e9-8460-ffb39602946c.jpg)

**Comment by hubsocks** [comment]
这个本来就不准确.还有一个CA 证书状态也经常是失败的.也不影响使用.
![快照1](https://user-images.githubusercontent.com/46856823/60596186-0cd20580-9ddb-11e9-83c7-a3b2a90e30dc.png)
