### ISSUE TITLE
X-Tunnel能不能退钱啊

### ISSUE THREAD

**Issue by ZhangQi-HUST** [XX-net/XX-Net#12626]
前几天还可以用一下下，偶尔有个服务器能连上，这几天完全都登录不上去了
1200G连到现在还有1199G呢
求问怎么退钱？

**Comment by SeaHOH** [comment]
问 xxnet.dev@gmail.com

**Comment by TracyBin** [comment]
同问，x-tuunel经常掉线，有时候谷歌打不开，现在变成了偶尔能打开

**Comment by SeaHOH** [comment]
自己发邮件去问

**Comment by TracyBin** [comment]
要问了有回复还来这里问？

**Comment by SeaHOH** [comment]
你似乎没搞清主次关系，邮件都没回复，这里能有？

**Comment by kuchaguangjie** [comment]
全球 大批 VPN 被 中资 收购, 不知道 xxnet 在不在 被 "收购" 之列 !!!
