### ISSUE TITLE
mac版和win版是一样的吗？

### ISSUE THREAD

**Issue by WindSpeak** [XX-net/XX-Net#12624]
找了很久，好像只有一个版本，但下载的版本在mac里扩展程序装不上

**Comment by WindSpeak** [comment]
大佬们发表一下高见呀

**Comment by SeaHOH** [comment]
不懂你说的什么，请详细描述。

**Comment by WindSpeak** [comment]
就是说mac系统用的xx-net版本是和windows系统用的xx-net版本一样吗？因为我在页面上只看到一个文件下载，没有区分win版和mac版，但我下了mac版好像装不了

**Comment by SeaHOH** [comment]
MAC 和 Windows 使用的文件都放在一起，解压缩后直接运行。
https://github.com/XX-net/XX-Net/wiki/How-to-get-start-error-log#mac和linux平台

**Comment by WindSpeak** [comment]
![image](https://user-images.githubusercontent.com/33273193/60764434-4b5a0f80-a0bc-11e9-97a8-6a03a7bae795.png)
可是在安装扩展程序的时候会报错，我连续下载了好几次都是这样

**Comment by SeaHOH** [comment]
安装商店版本，或者使用开发者模式。
