### ISSUE TITLE
已解决, 升级port

### ISSUE THREAD

**Issue by GaryHos** [XX-net/XX-Net#12639]
同样的问题，最新版 miredo 1.2.6安装之后系统偏好设置没有图标，没人解决？
macOS Mojave10.14.5

**Comment by 2378** [comment]
自己搜索论坛吧，记得有讨论过，至于miredo哪有什么最新版，6年前就是126了

**Comment by GaryHos** [comment]
但是以前的帖子没看解决啊。
有一个方法，
sudo port install miredo
结果: Error: Port miredo not found

**Comment by GaryHos** [comment]
users:~ user$ port search miredo
Warning: Can't open index file for source: rsync://rsync.macports.org/macports/release/tarballs/ports.tar
Error: search for name miredo failed: No index(es) found! Have you synced your port definitions? Try running 'port selfupdate'.
No match for miredo found
