### ISSUE TITLE
chrome浏览器的swichyOmega扩展程序安装后，页面空白并报代码错误错

### ISSUE THREAD

**Issue by never990504** [XX-net/XX-Net#12637]
TypeError: Illegal invocation: Function must be called on an object of type StorageArea//error
TypeError: Illegal invocation: Function must be called on an object of type ChromeSetting //error
[1] Unhandled rejection:
The specified value "!" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers. //warning
The specified value "!" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers. //warning
Uncaught TypeError: Cannot read property 'bind' of undefined//error
Uncaught TypeError: Cannot read property 'bind' of undefined//error
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.//error

**Comment by never990504** [comment]
下载的是13.1测试版

**Comment by tedchina** [comment]
现在应该只能通过Chrome App Store搜索安装吧（Store需要翻墙，鸡和蛋的问题）。

**Comment by 2378** [comment]
13.1测试版 是什么鬼 最新的2.5.20

![2](https://user-images.githubusercontent.com/24506320/61244990-11ed6800-a77e-11e9-975e-9891bfdf8532.PNG)

**Comment by SeaHOH** [comment]
估计是在说 XX-Net 3.13.1，什么都来这里问。
其实好用的搜索引擎还是有很多的，要学会使用它们。

https://nova.rambler.ru
https://bird.so/
https://sg.search.yahoo.com
https://www.qwant.com
https://so.mezw.com
https://www.ecosia.org
https://duckduckgo.com
