### ISSUE TITLE
ipv6总是不可用，在如何开启里面试了全部方法也没用

### ISSUE THREAD

**Issue by xtdxb** [XX-net/XX-Net#12631]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:11 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by 2378** [comment]
要么是电脑里有什么垃圾国软，要么就是你的网络环境彻底玩完，其实一月5刀也不贵

**Comment by webwolf0** [comment]
螞蟻加速，目前最好用的VPN，可購買也可免費用：https://ant.antss018.com/aff/m8yJ
電腦瀏覽器裏面要手動設置局域網：127.0.0.1:1080

下面的這些ipv6隧道還能用,不過我這裏延遲1000以上。
DOS裏面輸入格式：netsh interface teredo set state server=teredo-debian.remlab.net
teredo.iks-jena.de
teredo.trex.fi
teredo.remlab.net
teredo-debian.remlab.net

**Comment by xtdxb** [comment]
https://ant.antss018.com/aff/m8yJ这个网址怎么进不去啊
还有下面的dos怎么改啊
本人小白不太懂

**Comment by xtdxb** [comment]
@webwolf0
