### ISSUE TITLE
XX-net 最近用不了

### ISSUE THREAD

**Issue by sxd0071** [XX-net/XX-Net#12636]
* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，不遵守规则的提问会被自动关闭。
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:13
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 1
ip-quality: 1490
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 2378** [comment]
知足吧，最近才用不了。不过明显ipv6-status: Fail

**Comment by XiXiRuPan** [comment]
connect  ::2014 blocked: network fail

**Comment by SeaHOH** [comment]
> connect ::2014 blocked: network fail

你自己导入的 IP 吗？这地址根本不对。

**Comment by LeifChi** [comment]
听说老美查谷歌了  被渗

**Comment by gaopengpian** [comment]
有个免费的VPN可用：http://t.cn/Ailcgy1V

**Comment by sharwinmail** [comment]
我目前也靠一家带有免费节点的vpn,  http://t.cn/AiWgJhBc.免费的延迟大点但至少能用.

**Comment by sharwinmail** [comment]
我目前也用的免费上的外网.免费虽然延迟大点但还能用,希望能长久.  http://t.cn/AiWgJhBc

**Comment by mantout** [comment]
试试这个
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 http://t.cn/AijIDygU
