### ISSUE TITLE
反馈：一会正常，一会ipv6状态fail，但是检查IP，立马就正常。

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#12632]
一会正常，一会ipv6状态fail，但是检查IP，立马就正常。

![01](https://user-images.githubusercontent.com/39740368/60957489-540a4a00-a337-11e9-9c4c-215c67f100a1.jpg)

![02](https://user-images.githubusercontent.com/39740368/60957496-579dd100-a337-11e9-8b9d-f67d9babb835.jpg)

![03](https://user-images.githubusercontent.com/39740368/60957509-5a98c180-a337-11e9-9abb-0fecc9680972.jpg)

**Comment by SeaHOH** [comment]
能用就不要折腾，状态检测不是绝对准确，连接不稳定时会有误差。

**Comment by myjlpt** [comment]
大陆114等DNS开始作恶，请更换腾讯或阿里DNS。不要用宽带商提供，公众不要用114 ，百度180目前没用发现，。。。有条件还是用8.8.8.8吧
