### ISSUE TITLE
xtunnel不能上pixiv

### ISSUE THREAD

**Issue by qq392784506** [XX-net/XX-Net#12644]
xtunnel能上google，油管，就是上不了pixiv，服务器都换过几遍了，显示err-connection-close
尝试使用host，解析是对的，但是部分页面能上，部分不能。显示err-connection-reset
一顿操作以后，host全部失效，完全上不去了。

所以想问为什么xtunnel上不去pixiv

**Comment by SeaHOH** [comment]
#12635
