### ISSUE TITLE
七月份起goagent再次正常工作；Xtunnel更是从未出过问题

### ISSUE THREAD

**Issue by qibin8687** [XX-net/XX-Net#12647]
江苏电信，ipv6开启，teredo隧道开启。今年年初时goagent歇了半年，而我自去年起一直启用Xtunnel翻墙几乎毫无障碍，唯一的障碍就是流量快光了得上论坛来求点馈赠。如今goagent也恢复了，几乎每次开机可用ipv6数量都在大几十个。所以我看论坛上各位一直控诉各种不行，甚为不解。

**Comment by SeaHOH** [comment]
网络环境不同而已，千变万化没个准，没必要专门开贴讲这种事，真的很占地方。
