### ISSUE TITLE
请教各位大佬关于国产浏览器的问题。推荐个“安全”的双核浏览器。

### ISSUE THREAD

**Issue by dylanleesky** [XX-net/XX-Net#12640]
说个题外话，XX目前也没法好好用了，这里就当大家的沟通圣地吧。

本来一直用的国产浏览器是搜狗浏览器，但目前搜狗浏览器各种作死。。。
现在连账号都登陆不上了。

得换浏览器了啊。。。chrome同步不畅。所以要有个能同步书签的浏览器。
QQ浏览器后台驱动鬼知道干嘛的不敢用，
数字卫士是不用了，不知道数字的极速浏览器敢不敢用？

**Comment by dylanleesky** [comment]
火狐不好用，不管旧版新版的都不好用实在不如chrome。。。
opera没同步的插件。。。
UC，猎豹，两大垃圾还不如数字。求大佬推荐。。。

**Comment by 2378** [comment]
除了 firefox、chrome 真不知道推荐什么

至于同步不畅，从没有出现过

**Comment by AeneasZhu** [comment]
“国产”和“安全”是一对矛盾的词儿，你要么选择“国产”，要么选择“安全”

**Comment by SeaHOH** [comment]
你这是没必要的问题，请不要使用国产浏览器等软件，或者分开不要和翻墙软件同时使用。
