### ISSUE TITLE
校园网DrCom升级客户端，teredo隧道已经废掉

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12649]
这几天学校升级了多点客户端，恢复网络后发现teredo隧道已经无法使用。

**Comment by 2378** [comment]
有偶无独，前几日宽带莫名断线几小时，原以为是线路调整什么的

事后通过内部朋友了解到，机房有设备升级

**Comment by AeneasZhu** [comment]
> 有偶无独，前几日宽带莫名断线几小时，原以为是线路调整什么的
> 
> 事后通过内部朋友了解到，机房有设备升级

我在公司了的网络却还能正常走隧道，公司也是用电信的。是因为公司有公网IP吗？

**Comment by 2378** [comment]
就teredo而言，公网IP不是必要条件，关键这年头能分配公网iP的不是专线至少也是商务套餐

好处就是少过几层NAT自然也少些“旁路”设备，而这些设备（你懂的）电信员工都不允许碰的

**Comment by AeneasZhu** [comment]
> 就teredo而言，公网IP不是必要条件，关键这年头能分配公网iP的不是专线至少也是商务套餐
> 
> 好处就是少过几层NAT自然也少些“旁路”设备，而这些设备（你懂的）电信员工都不允许碰的

现在还有其他方法吗？teredo隧道彻底不行了吗？

**Comment by 2378** [comment]
我是没办法，我这去年就用不了了。不过关于dr.com认证，学生党讨论很多的，你自己逛逛，或许有突破呢
