### ISSUE TITLE
xx-net 显示正常，但有效ipv6数很少，甚至为0，上不了网，是不是跟teredo的服务器有关呢

### ISSUE THREAD

**Issue by longdrake** [XX-net/XX-Net#12652]
xx-net 显示正常，但有效ipv6数很少，甚至为0，上不了网，是不是跟teredo的服务器有关呢？
还有xx-net显示可以访问真正的互联网了，如果没开VPN的话，也是上不了网，开了shadowsocks后，设置switchyomega为GAE proxy自动切换，里面的GAE proxy服务设置为socket5，再填入shadowsocks的代理端口 ，那这样访问谷歌成功，是说明这已经通过xxnet访问这网站了吗？如何获取当前的IP呢，我查了下IP，还是显示我本地的网络IP位置。

**Comment by 2378** [comment]
说得够混乱的 建议switchy单独设置 $$代理 GAE代理  VPN代理 

这样你就知道哪个工作正常了

**Comment by 2378** [comment]
补充一点，如果你的vpn客户端只支持纯vpn协议的（PPTP, L2TP等） switchy也支持不了
