### ISSUE TITLE
X-Tunnel流量还没有到账，发了邮件也没有用

### ISSUE THREAD

**Issue by 837852427** [XX-net/XX-Net#12656]
![](https://mail.qq.com/cgi-bin/viewfile?f=E762A41AEE1D13DD0596D0E8F4BD24ACB7EB933735434B68B42C128C13428FC1C67F9215BA840FF4C1D37FB249EEB20AB8ABB1891C280463CD93FC006378DE1B03985B5E43A93EC247FED164254F8A40B85A46108F495AAC243F34D358D69269&mailid=ZC1824-wUpwkpSRmcH5d0Ybh2hlI97&sid=uDNX1dPs6rKLGSh1&net=889192575)

**Comment by 837852427** [comment]
![](https://s2.ax1x.com/2019/07/25/eZXQcn.png)

**Comment by sharwinmail** [comment]
可能店家目前比较忙,可以先用用免费节点http://t.cn/AijfDzA8   
先顶着,默认是收费线路只有300M,点线路地址更改成公共免费线路就没有限制了.
已经用了2个月了.目前还可以.

**Comment by SeaHOH** [comment]
到帐后请关闭 issue，发邮件才是解决问题的正确方法，邮件发了都没法解决，你发这里就能？
