### ISSUE TITLE
勾选smart route模式墙内网站浏览不畅？

### ISSUE THREAD

**Issue by qibin8687** [XX-net/XX-Net#12667]
首先，我是可以翻墙的。无论GAE模式还是Xtunnel模式均可以。我习惯使用xxnet自己的代理模式，不借助诸如omegaswitch这样的三方扩展。xxnet我通常选择“全局pac代理”模式，同时在控制面板中smart route选项中pac策略勾选为“黑名单--GAE”、下方诸如“尝试直连”“尝试直连时优先使用ipv6”等每个选项均打开。那么这种状态下，火狐、centbrowser浏览器墙内墙外模式浏览均非常顺畅。
现在问题在于GAE略有不稳，偶尔地xxnet控制面板中会“证书失败”或“浏览器代理设置失败”也就是连不上。那么此时我在控制面板中smart route选项中pac策略勾选为“黑名单--Xtunnel”就又可以流畅翻墙了。不过，每次碰到这种情况我都需要手动设置。
你一定会问：smart route不就是自动判断是否需要翻墙、翻墙时走哪条渠道翻墙吗？直接勾选它不就完事儿了？确实是有问题的：如果勾选“全局--smart route”，会神奇地出现墙内网站页面下载不全或直接打不开。这个问题在centbrowser上表现得特别明显，火狐还好。我不懂为什么不同的浏览器会表现不同程度的受阻？论坛上有人碰到过这种问题吗？我想应该有高手处理过这样的问题。

**Comment by SeaHOH** [comment]
内置规则没人更新，建议使用 SwitchyOmega，使用更方便，也不会遇到 Win10 的代理设置 bug。
