### ISSUE TITLE
可以请各位大佬帮我看一下咩？ IPV6一直是fail...

### ISSUE THREAD

**Issue by hasukyuu** [XX-net/XX-Net#12666]
按照Win10开启IPV6的教程试了一下好像还是不可以QAQ

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
https://github.com/XX-net/XX-Net/issues/12370

**Comment by cxzcui** [comment]
按理来说没有ipv6的话v4也可以获取到地址，但我的也连不上，现在已经转战蚂蚁加速了，速度快得多http://t.cn/AiYExEEO
