### ISSUE TITLE
IP6一直fail，各种办法都试过了完全没用，有时候偶尔能连上一会儿

### ISSUE THREAD

**Issue by liuqy123** [XX-net/XX-Net#12663]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:15 ipv4:0 ipv6:4
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 1306
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : restricted
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.0.102:53013
外部 NAT 映射    : 125.120.4.195:19445

感觉越来越没法用了，之前还能上一会儿

**Comment by 2378** [comment]
杭州电信的朋友，你好:relaxed:

**Comment by AeneasZhu** [comment]
隧道我在公司可以，在别的地方就不行了。校园网7月前还行，7月后校园网升级隧道也被封了。应该是和本地运营商有关。

**Comment by dxdvid** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:12
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1500
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
这是我的状态，已经持续一个多月的，一起连不上

**Comment by liuqy123** [comment]
> 隧道我在公司可以，在别的地方就不行了。校园网7月前还行，7月后校园网升级隧道也被封了。应该是和本地运营商有关。

问题是我用笔记本在其他地方上也是同样的毛病

**Comment by SeaHOH** [comment]
尝试使用微软以外的 teredo 服务。

**Comment by liuqy123** [comment]
> 尝试使用微软以外的 teredo 服务。

事实上我一开用的就不是微软的，按照ISSue里的各种方法试了之后反而总IP更少了，有效IP到是一样都是2.3个，过一会儿直接变0

**Comment by SeaHOH** [comment]
你能看到，很多人的求助问题我根本就没有回复。为什么？因为没有提供足够的信息以供判断。
所以，我只是根据你提供的信息来给出相应的意见。

**Comment by liuqy123** [comment]
> 你能看到，很多人的求助问题我根本就没有回复。为什么？因为没有提供足够的信息以供判断。
> 所以，我只是根据你提供的信息来给出相应的意见。
那么大佬需具体需要什么样的信息呢？
