### ISSUE TITLE
关于部署APPId一直出不来弹出页面

### ISSUE THREAD

**Issue by errorcode300** [XX-net/XX-Net#12660]
关于部署APPId一直出不来弹出页面，已经允许弹出窗体，也没有其他阻止弹出页面的拓展程序。
目前只能用谷歌访问助手上下搜索引擎以及邮箱，git，其他受限严重。

**Comment by SeaHOH** [comment]
现在没必要自己部署，公共 ID 根本用不完。

**Comment by errorcode300** [comment]
咦！我每次用XX—net的时候都是重新部署AppID，求告知公共ID，顺便问下公共ID是有别的大佬已经部署好的？不需要自己部署？

**Comment by SeaHOH** [comment]
自己看上方 wiki。
