### ISSUE TITLE
3种XX-NET备用神器之自己搭建SSR/V2RAY/BROOK教程，2k无压力

### ISSUE THREAD

**Issue by doublelove666** [XX-net/XX-Net#12671]
[自建SSR服务器教程 ](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)  [免费ss/ssr账号获取（限速100kb/s）](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7)

[自建v2ray服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

[自建Brook服务器教程 ](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAbrook%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)

**Comment by doublelove666** [comment]
![2k](https://user-images.githubusercontent.com/53819260/62536700-30c4b300-b881-11e9-8a68-0a843bfd2fdb.png)

**Comment by SeaHOH** [comment]
#12512
