### ISSUE TITLE
以前直连光猫，现在装了路由器，就扫不到可用ip了

### ISSUE THREAD

**Issue by imudie999** [XX-net/XX-Net#12676]
**之前电脑直连光猫，XXnet还能用得很顺畅。
昨天在电脑和光猫之间装了个路由器，就扫不到可用的IP了。
抓图和诊断信息如下**

![zhenduan1](https://user-images.githubusercontent.com/53925827/62751710-48758480-ba97-11e9-88ba-1943f3b55018.JPG)
![zhenduan2](https://user-images.githubusercontent.com/53925827/62751720-4e6b6580-ba97-11e9-9689-0e56557efe34.JPG)
`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:65 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 25
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by SeaHOH** [comment]
把路由器进线插到 LAN 口试试，同时需要关闭路由器自带的 DHCP 功能。

如果路由器 IP 和光猫 IP 冲突，还需要在进行这些操作之前修改路由器的 IP。
如：光猫、路由器 IP 同是 192.168.1.1，修改路由器 IP 为 192.168.1.*，* 为 1 之外的其它数值。

**Comment by imudie999** [comment]
> 
> 
> 把路由器进线插到 LAN 口试试，同时需要关闭路由器自带的 DHCP 功能。
> 
> 如果路由器 IP 和光猫 IP 冲突，还需要在进行这些操作之前修改路由器的 IP。
> 如：光猫、路由器 IP 同是 192.168.1.1，修改路由器 IP 为 192.168.1._，_ 为 1 之外的其它数值。

**多谢回复。
经过一番盲目折腾，目前有30多个可用ip。
我只是关了路由上的Upnp，开了DMZ。先将就用着。**

![xxnet](https://user-images.githubusercontent.com/53925827/62920344-138b6980-bdd8-11e9-94df-5588e03e88d4.JPG)

**Comment by SeaHOH** [comment]
开 DMZ 也行，不过要指定对 IP，还要做好防火墙配置。。

**Comment by dylanleesky** [comment]
路由不支持或者没开IPV6服务吧？现在的光猫拨号应该可以获取到IPV6地址的。路由没有开的话就会短掉IPV6。
