### ISSUE TITLE
请问.突然间有效ip是0怎么解决.

### ISSUE THREAD

**Issue by l14557504y** [XX-net/XX-Net#12686]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:98 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by l14557504y** [comment]
之前用了很长时间了. 就前2天开始就用不了. 
移动网络.估计是内网.开不了原生
ip总数是原来是100+.  后来就是变成0.  延迟9999.

配置里 Teredo显示休眠. 测试Teredo服务器.win710. ping是40左右.其他都是300+.

隔壁插件扫出来的ipv4有效地址.添加后也全都用不了.

也不知道怎么解决. 算大半个小白.求高手指引.或其他的科学上网. 

找了很多. 什么无界,自由. 特别卡. 用半分钟就掉了. 要么其他要收费.难受

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
使用以上链接中的脚本工具，手动切换微软以外的服务器。
如果这样也不行，可能你的网络结构有变。

其它工具请自行尝试。

**Comment by l14557504y** [comment]
> [https://github.com/XX-net/XX-Net/wiki/如何开启IPv6的](https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6)
> 使用以上链接中的脚本工具，手动切换微软以外的服务器。
> 如果这样也不行，可能你的网络结构有变。
> 
> 其它工具请自行尝试。


  这个脚本试过. 看样子是凉凉了. 还是表示感谢

**Comment by Upreak-Jkeey** [comment]
也许是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://wz4.in/0i5q8（使用此链接，你我都能得到20%优惠）

**Comment by Upreak-Jkeey** [comment]
也许是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://wz4.in/0i5q8  （使用此链接，你我都能得到20%优惠）
