### ISSUE TITLE
发现 XXtunnel 一上这个网站就熄火咋办？“www.behance.net”？？？

### ISSUE THREAD

**Issue by GFconcept** [XX-net/XX-Net#12682]
发现 XXtunnel 一上这个网站就熄火咋办？“www.behance.net”？？？

**Comment by SeaHOH** [comment]
为什么要使用代理，直连不好吗？
如果有 DNS 污染，启用 DoH 就好。

**Comment by GFconcept** [comment]
> 为什么要使用代理，直连不好吗？
> 如果有 DNS 污染，启用 DoH 就好。
直连上不了啊 ？？ DOH在哪里啊？？

**Comment by SeaHOH** [comment]
https://www.google.com/search?q=如何启用DoH
