### ISSUE TITLE
启动问题：状态页显示空白

### ISSUE THREAD

**Issue by corykang** [XX-net/XX-Net#1268]
版本：XX-Net-2.5.5
OS：Windows7 x64
log.log部分信息：
Oct 24 01:01:03 - [ERROR] start module gae_proxy fail:DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
Oct 24 01:01:04 - [INFO] get uuid:838bf3b2-8208-4178-8f10-d76203efd621
Oct 24 01:01:05 - [WARNING] check_update fail:URLError(error(10061, 'No connection could be made because the target machine actively refused it'),)
Oct 24 01:30:27 - [ERROR] stop module gae_proxy fail:'imp'
Oct 24 01:30:27 - [ERROR] stop module gae_proxy fail:'imp'
可能起因：最近朋友在电脑上修改过注册表、禁用了部分系统服务
进展：启动了部分系统服务，可以使用Lantern、psiphon3、自由门翻墙，但XX-Net依旧无法部署
谢谢~

**Comment by xyuanmu** [comment]
查看 Windows Modules Installer 服务是否被禁用，改为手动启动。

**Comment by corykang** [comment]
@xyuanmu 打开services，Windows Modules Installer 并没有禁用啊。
status:started;
startup type:Manual

**Comment by corykang** [comment]
2015.10.25 0:50更新：
Error message: "Side-by-side configuration is incorrect"
The machine is missing the correct C++ runtime components for your type of system. (x86 or x64).
Installing the following update resolved the issue.
http://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/error-the-application-has-failed-to-start-because/df019c0d-746e-42d0-ad68-465e18e3f3ef?auth=1
问题依旧，状态页仍然是空白。
继续努力ing,有懂的小伙伴们指点下~

**Comment by jzp820927** [comment]
估计是不是升级包不完整，重新下载完整包试试

**Comment by corykang** [comment]
@jzp820927 谢谢，但和升级包并没有关系

**Comment by xyuanmu** [comment]
提示很明确了，你盆友没安装Microsoft Visual C++ 2008 或者2010

**Comment by corykang** [comment]
安装了，但问题依旧

2015-10-25 9:11 GMT+08:00 xyuanmu <notifications@github.com>:

**Comment by corykang** [comment]
2015.10.26 14:10更新
使用SecurityCheck、MiniToolBox得到如下信息

1、My computer's time, date, and timezone are all correct
2、MTB.txt部分信息
========================= Event log errors: ===============================

Application errors:
==================
Error: (10/26/2015 01:51:24 PM) (Source: SideBySide) (User: )
Description: Activation context generation failed for 

"Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"1".
Dependent Assembly 

Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could 

not be found.
Please use sxstrace.exe for detailed diagnosis.



System errors:
=============
Error: (10/25/2015 08:20:31 AM) (Source: Service Control Manager) (User: )
Description: The Net.Tcp Listener Adapter service depends the following service: NetTcpPortSharing. This service might not 

be installed.

Error: (10/25/2015 08:20:31 AM) (Source: Service Control Manager) (User: )
Description: The Net.Pipe Listener Adapter service depends the following service: was. This service might not be installed.


Error: (10/25/2015 08:20:31 AM) (Source: Service Control Manager) (User: )
Description: The Net.Msmq Listener Adapter service depends the following service: msmq. This service might not be 

installed.

Error: (10/25/2015 08:20:20 AM) (Source: Service Control Manager) (User: )
Description: The PnP-X IP Bus Enumerator service terminated with the following error: 
%%-2147023728

Error: (10/25/2015 08:19:59 AM) (Source: NETLOGON) (User: )
Description: This computer is configured as a member of a workgroup, not as
a member of a domain. The Netlogon service does not need to run in this
configuration.

3、checkup.txt信息
 Results of screen317's Security Check version 1.011 --- 10/21/15  
 Windows 7 Service Pack 1 x64 (UAC is enabled)  
[b][u]``````````````Antivirus/Firewall Check:``````````````[/b][/u] 
 [color=red][b]Windows Security Center service is not running! This report may not be accurate![/b][/color] 
 [size=1]WMI entry may not exist for antivirus; attempting automatic update.[/size] 
[b][u]`````````Anti-malware/Other Utilities Check:`````````[/b][/u] 
 [color=red][b]Java version 32-bit out of Date![/b][/color] 
 Google Chrome (47.0.2526.8) 
[b][u]````````Process Check: objlist.exe by Laurent````````[/b][/u]  
[b][u]`````````````````System Health check`````````````````[/b][/u] 
 Total Fragmentation on Drive C: 1% 
[b][u]````````````````````End of Log``````````````````````[/b][/u] 
回头研究下，有知道的提示一下那就更好，thx~

**Comment by corykang** [comment]
哦，太棒了，问题解决了。
主要原因：missing the correct C++ runtime components【见4L】
主要问题：我安装的是x64，因为我的OS是x64，实际上还需要Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148，安装完后部署成功

**Comment by kkpig** [comment]
非常感谢 迷茫了半天终于在这里找到方法了 需要Microsoft Visual C++ 2008 Redistributable - x86 ，建议写入README.MD里面
