### ISSUE TITLE
请问CHROME显示SwitchyOmega为滥用程序如何解决？

### ISSUE THREAD

**Issue by mogwaiwxg** [XX-net/XX-Net#12688]
早上开机后发现代理程序不见了，打开扩展程序面板后发现CHROME显示其为滥用程序，点击修复后下载失败，直接面板里也没有了，去应用商店里下载也是失败，把原来的CRX文件拖进去显示程序包无效，请大神帮忙解答一下，谢谢！

**Comment by libing125** [comment]
为什么关了？

**Comment by BuBu0816** [comment]
请问解决了吗，我也是扩展程序无效无法安装
