### ISSUE TITLE
无法将扫描线程提升至30以上

### ISSUE THREAD

**Issue by KsRyY** [XX-net/XX-Net#12687]
无论如何在扫描线程界面上如何调高数值刷新后也最高只有30.

版本：直接从github main branch下载的zip，显示3.13.1

**Comment by SeaHOH** [comment]
增大扫描线程对于 IPv6 没啥意义，数下自带的 IPv6 有多少就明白了。
在谷歌修改服务器策略的当下，XX-Net 并没有跟进区分 IP 类别，对于扫描 IPv4 来讲，其实也是白耗功夫居多。

如果你非要增加扫描线程，可以自行修改源代码，参考最新的 commit。

**Comment by KsRyY** [comment]
好的
