### ISSUE TITLE
IP 扫描线程数 修改不了，保存后刷新又回到默认值100，怎么回事？

### ISSUE THREAD

**Issue by wwqq33** [XX-net/XX-Net#12685]
现在ip扫不到 我想调大点 100m应该能承受200吧？
怎么现在调整不动啊?是最新版本3.13.1。Windows 10 64位系统

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:36
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 403
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by wwqq33** [comment]
[GAEProxy 日志.txt](https://github.com/XX-net/XX-Net/files/3507980/GAEProxy.txt)

日志文件 图片上去不了 算了。。

**Comment by SeaHOH** [comment]
现在普通的 gws 服务 IP 已经不再提供 gae 服务，而 XX-Net 中内置的 IPv6 数量仅 400+。
如果不打算使用 IPv4，就根本没必要增加扫描线程。

**Comment by wwqq33** [comment]
> 
> 
> 现在普通的 gws 服务 IP 已经不再提供 gae 服务，而 XX-Net 中内置的 IPv6 数量仅 400+。
> 如果不打算使用 IPv4，就根本没必要增加扫描线程。

好吧  谢谢解答
