### ISSUE TITLE
敢问如何退款？

### ISSUE THREAD

**Issue by timelord11th** [XX-net/XX-Net#12680]
发了邮件无人回复，paypal上申请亦无回应。

**Comment by SeaHOH** [comment]
所谓无回复回应是指多长时间？
如果超过一周，完全不反对你这么质疑。

**Comment by timelord11th** [comment]
自申请退款日2019年08月07日始，到今天2019年08月21日，差不多两个星期吧，仍然没有回复邮件。

**Comment by timelord11th** [comment]
自申请退款日2019年08月07日始，到今天2019年08月21日，差不多两个星期吧，仍然没有回复邮件。

SeaHOH <notifications@github.com> 于2019年8月10日周六 下午10:22写道：

**Comment by SeaHOH** [comment]
所以早就提醒过，购买之前先测试，你们不听我也没法。
慢慢等吧，估计心思已经不在这里，可能一俩月才看一次吧。
但系统本身还能勉强运作，等这个系统崩溃后，资金应该还有剩余。
至于下一个系统的头绪，我都没见过，大机率是流产了。
之后的打算没打听过，真想了解的还是建议发邮件去问，收得多了，公开回复的可能就大了。

**Comment by SaromChars** [comment]
什么鬼，试用可以用，一充钱就连接不上？？？

**Comment by SeaHOH** [comment]
稍微靠谱点的试用姿势：
1. 在不同的时段使用
1. 访问几个典型的和自己常用的站点
1. 连续使用几天
1. 有条件的还可以在不同网络环境中试用

经过以上试用步骤，还会出现“试用可以用，一充钱就连接不上”？？

**Comment by SaromChars** [comment]
送的100m可以用。。。但登陆一直603.....重启之后很久才连上

**Comment by SaromChars** [comment]
> 送的100m可以用。。。但登陆一直603.....重启之后很久才连上

不对，是602....用一会又断开了。。。

**Comment by SeaHOH** [comment]
事实就是你根本就用不了，去退款吧。

**Comment by Dexilc** [comment]
我也是，退款申请邮件发了至少2周了，没人应

**Comment by yeahwu** [comment]
602,看到602就头大

**Comment by shellyzhang2019** [comment]
请问，我今天冲的钱没有到账是怎么回事啊

**Comment by shellyzhang2019** [comment]
我的邮箱lingtongz@163.com,作者我给你发邮件了啊

**Comment by SeaHOH** [comment]
@shellyzhang2019 为什么给我发，你智商欠费吗？我可没收你的钱。

**Comment by SeaHOH** [comment]
@shellyzhang2019 已经回复你了，我觉得 wiki 写得很清楚，那里写的可不是我的邮箱。不要老是发邮件问我，不识字还是怎的？

**Comment by shellyzhang2019** [comment]
嗯嗯，我刚刚才看到，对此表示抱歉

发送自 Windows 10 版邮件应用

发件人: SeaHOH
发送时间: 2019年10月12日 21:13
收件人: XX-net/XX-Net
抄送: shellyzhang2019; Mention
主题: Re: [XX-net/XX-Net] 敢问如何退款？ (#12680)

@shellyzhang2019 已经回复你了，我觉得 wiki 写得很清楚，那里写的可不是我的邮箱。不要老是发邮件问我，不识字还是怎的？

**Comment by Dexilc** [comment]
谢谢，今天收到了退款通知
