### ISSUE TITLE
XX-NET彻底歇菜了吗？

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12699]
IPv4 状态 | OK
-- | --
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 485
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 0

有效IP均为0，国殇日三十周年都没这么彻底。XX-NET彻底凉了？还是HK那边的原因，压力太大，朝廷顶不住？亦或是本朝建朝70周年大阅兵，提前进入修罗维稳模式？

**Comment by imudie999** [comment]
现在确实全部为0了。
下午还可以用。

**Comment by Suns3tz** [comment]
我也凉了

**Comment by lefantian** [comment]
错杀一千不放一个，墙已成了山

**Comment by Eri5Ch** [comment]
第一次出现这个情况 全部为0了。。。

**Comment by wangling12** [comment]
应该是70周年了吧

**Comment by imudie999** [comment]
但是如果是真的，“某门”应该更早被封啊。
我刚才试了一下，“某门”还可以用。
说不定是哪里故障了。

**Comment by AeneasZhu** [comment]
> 但是如果是真的，“某门”应该更早被封啊。
> 我刚才试了一下，“某门”还可以用。
> 说不定是哪里故障了。

SSR机场这几天也不稳定，断断续续的。无界和自由门以前用过，但广告太烦了，就不用了。Chrome一些免费VPN插件也纷纷挂掉。

本朝阅兵是全国子民的事呀。。。。。。。。

**Comment by SeaHOH** [comment]
要吐槽，不需要新开贴，你看别人都知道跟帖。
Duplicate of #12690
