### ISSUE TITLE
等待扫描 IP，建议开启 IPv6。

### ISSUE THREAD

**Issue by AvigatorC** [XX-net/XX-Net#12691]
原生ipv6，前几天开始就提示“等待扫描 IP，建议开启 IPv6，断断续续的可以用。今天彻底连不上了。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by MARILYNHAN** [comment]
8月份之前用的学校原生IPV6用的好好的，最近也是突然不能用了，不知道为啥。

**Comment by AvigatorC** [comment]
今天又能用了...搞不懂...更新了一下版本

**Comment by Upreak-Jkeey** [comment]
也许是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://wz4.in/0i5q8  （使用此链接，你我都能得到20%优惠）

**Comment by cuilincui** [comment]
> 今天又能用了...搞不懂...更新了一下版本

更新什么版本？

**Comment by belleyeah** [comment]
@AvigatorC，请问更新了什么版本？

**Comment by SeaHOH** [comment]
要吐槽，不需要新开贴，你看别人都知道跟帖。 
Duplicate of #12690
