### ISSUE TITLE
ipv6 状态OK但是有效ip为0，总ip数98，显示等待扫描ip，建议开启ipv6

### ISSUE THREAD

**Issue by klc197** [XX-net/XX-Net#12690]
诊断信息如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:98 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by klc197** [comment]
刚才还好好的，突然掉线了，XX-net版本是3.13.1

**Comment by ztz1995** [comment]
同！完全一样的状况

**Comment by klc197** [comment]
好久没出问题了，以前这种问题我都是安装新版本的XX-net就行，可现在XX-net新版本好久没有更新了

**Comment by HCOOLi** [comment]
同

**Comment by laolongboy** [comment]
+1

**Comment by ablebodied** [comment]
ipv6貌似彻底跪了，ip为0

**Comment by rexwang011** [comment]
出现了完全一样的情况

**Comment by windzlife** [comment]
一样啊

**Comment by rexwang011** [comment]
难道xx-net被封了？

**Comment by infnight** [comment]
同一个夜晚，同一个情况...

**Comment by awlways** [comment]
同啊

**Comment by h1525** [comment]
手动添加一些
2404:6800:4005:810::2014|2404:6800:4008:c01::99|2404:6800:4005:80f::2014|2404:6800:4005:807::2014|2607:f8b0:4007:802::2014|2404:6800:4008:801::2014|2404:6800:4005:80d::2014|2404:6800:4004:80d::2014|2404:6800:400a:80c::2014|2404:6800:4004:81b::2014|2607:f8b0:4000:806::2014|2404:6800:4003:c04::99|2404:6800:4001:80f::2014|2404:6800:4009:80e::2014|2404:6800:4007:80b::2014|2404:6800:4009:808::2014|2a00:1450:4009:814::2014|2a00:1450:4001:80b::2014|2a00:1450:4001:808::2014|2a00:1450:4001:806::2014|2a00:1450:4016:80a::2014|2a00:1450:400a:802::2014|2a00:1450:4002:807::2014|2a00:1450:4016:80d::2014|2a00:1450:401b:804::2014|2a00:1450:401b:806::2014|2a00:1450:4003:80a::2014|2a00:1450:400d:809::2014|2a00:1450:401b:803::2014|2a00:1450:400d:805::2014|2a00:1450:4003:802::2014|2a00:1450:4003:801::2014|2a00:1450:4017:80b::2014|2a00:1450:4017:809::2014|2a00:1450:400f:80c::2014|2a00:1450:4010:c07::99|2a00:1450:4017:807::2014|2a00:1450:4010:c0e::99|2a00:1450:4017:801::2014|2a00:1450:4017:806::2014|2a00:1450:4017:808::2014|2a00:1450:4010:c0a::99|2a00:1450:400f:809::2014|2a00:1450:400f:80b::2014|2800:3f0:4001:807::2014|2800:3f0:4001:814::2014|2800:3f0:4001:80a::2014|2800:3f0:4001:810::2014|2800:3f0:4001:815::2014|2800:3f0:4004:806::2014|2800:3f0:4001:809::2014|2800:3f0:4001:80f::2014|2800:3f0:4004:809::2014|2800:3f0:4004:807::2014|2800:3f0:4002:805::2014|2a00:1450:4010:c0b::99|2a00:1450:4017:80a::2014|2a00:1450:4010:c01::99|2a00:1450:4014:80d::2014|2800:3f0:4004:805::2014|2800:3f0:4002:804::2014|2a00:1450:400f:808::2014|2a00:1450:400e:804::2014|2607:f8b0:400e:c09::99|2800:3f0:4002:808::2014|2800:3f0:4001:803::2014|2404:6800:4002:804::2014|2800:3f0:4001:802::2014|2a00:1450:4010:c03::99|2800:3f0:4004:801::2014|2a00:1450:400e:809::2014|2800:3f0:4002:80a::2014|2800:3f0:4001:816::2014|2800:3f0:4004:808::2014|2800:3f0:4002:809::2014|2800:3f0:4004:800::2014|2404:6800:4009:80a::2014|2404:6800:4009:803::2014|2607:f8b0:400a:800::2014

**Comment by qizhiyanhuang** [comment]
广州+1

**Comment by huqiyii** [comment]
凉了

**Comment by qizhiyanhuang** [comment]
还有没有走ipv6的VPN，求大佬推荐

**Comment by elliott10** [comment]
昨晚开始的，同 "等待扫描 IP，建议开启 IPv6"，实际开启了IPv6，但数列为0

**Comment by h1525** [comment]
https://github.com/XX-net/XX-Net/issues/11748#issuecomment-448822138
这里有不少ipv6的地址，不过同样无效。

**Comment by miketwes** [comment]
我用的是 [XX-Net-Linux 3.13.1](https://github.com/miketwes/XX-Net-Linux):
Mini version of [XX-Net](https://github.com/XX-net/XX-Net) for Linux user.
流畅上网, 感觉很好用

**Comment by ablebodied** [comment]
> 我用的是 [XX-Net-Linux 3.13.1](https://github.com/miketwes/XX-Net-Linux)(Mini version of [XX-Net](https://github.com/XX-net/XX-Net) for Linux user).
> 流畅上网, 感觉很好用, 上网IP一直是454个固定IP.

这个确实可以用，希望大神更新一下xx-net吧，这个貌似只支持Linux。话说这个IP数量 准吗？我这里命令行也显示454啊，这个没有web配置界面，只能简单的用一下

**Comment by FisherXT** [comment]
[https://github.com/miketwes/XX-Net-Linux](url)
用这个repo里的good_ip.txt替换win版的就能正常使用了
我win7测试成功了

**Comment by jianshengWu** [comment]
一样

**Comment by elliott10** [comment]
> [https://github.com/miketwes/XX-Net-Linux](url)
> 用这个repo里的good_ip.txt替换win版的就能正常使用了
> 我win7测试成功了

我把那个repo的ip都导入还是没用，应该目前网络环境下以前可用的ip失效了

**Comment by jianshengWu** [comment]
我的诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.20 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:99 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by FisherXT** [comment]
> > [https://github.com/miketwes/XX-Net-Linux](url)
> > 用这个repo里的good_ip.txt替换win版的就能正常使用了
> > 我win7测试成功了
> 
> 我把那个repo的ip都导入还是没用，应该目前网络环境下以前可用的ip失效了

5分钟前还可以，现在回复的时候仅存的一个可用ip也失效了

**Comment by yohnung** [comment]
又挂了一个？？？！！！

**Comment by jianshengWu** [comment]
你的意思是不说xx-net已经被封了？

**Comment by jianshengWu** [comment]
前几天也出现了类似问题，但后来又好了，现在有这么多人都没用了，看来是好不了了

**Comment by Jing--Li** [comment]
我也是啊，今天早上来了就不行了，之前退出XX-Net，重新启动一下就好了，这次不行了，总是这样！

**Comment by springzfx** [comment]
都一样

**Comment by FSRyan** [comment]
哎~，同是天涯沦落人啊

**Comment by realtainyi** [comment]
fail

**Comment by tommy951113** [comment]
一样

**Comment by Kosmas131** [comment]
+1

**Comment by hanswxj** [comment]
一样

**Comment by indy369** [comment]
碰到了一样的情况，还有没有可以用ipv6的工具。

**Comment by infnight** [comment]
实在受不了了，自己搭了梯子，告辞。

**Comment by qizhiyanhuang** [comment]
> 实在受不了了，自己搭了梯子，告辞。

有可靠、性价比高的可推荐吗

**Comment by cupbk** [comment]
你们还能用到现在，我在年初就用不了了，所以只好自己花钱搭梯子，然后经历vps涨价，爬墙成本越来越高。感谢xxnet的开发者，以后也不会有这么方便的工具了。

**Comment by AnyWAT** [comment]
原生 IPv6 https://github.com/XX-net/XX-Net/issues/12477

![image](https://user-images.githubusercontent.com/37962734/63634407-ab1a7300-c688-11e9-985d-30df468159e6.png)
![image](https://user-images.githubusercontent.com/37962734/63634422-dac97b00-c688-11e9-891d-94df2eac626e.png)

**Comment by 6keduo** [comment]
我也遇到相同状况，但是仍然可以使用，就是IP数量少很多……

**Comment by 6keduo** [comment]
> > > [https://github.com/miketwes/XX-Net-Linux](url)
> > > 用这个repo里的good_ip.txt替换win版的就能正常使用了
> > > 我win7测试成功了
> > 
> > 
> > 我把那个repo的ip都导入还是没用，应该目前网络环境下以前可用的ip失效了
> 
> 5分钟前还可以，现在回复的时候仅存的一个可用ip也失效了

重新再次替换IP即可恢复使用，1~4个可用IP……

**Comment by jianshengWu** [comment]
现在好了，但是有效ipv6数量很少

**Comment by jianshengWu** [comment]
又没了

**Comment by jianshengWu** [comment]
有什么解决方法吗

**Comment by infnight** [comment]
> > 实在受不了了，自己搭了梯子，告辞。
> 
> 有可靠、性价比高的可推荐吗

亚马逊或者谷歌服务器，先白piao一年再说，教程网上一搜一大把。

**Comment by AeneasZhu** [comment]
目前用6plat平台将IPV4转IPV6，比隧道要稳定一些，但今天也不行了，IP数量直线下降。目测是和香港的局势有关，朝廷不想让墙内的P民知道香港那边的真相，但查封力度不如国殇日三十周年那么高。

**Comment by AeneasZhu** [comment]
这种情况应该过一段时间会有好转，今年XX-NET半死不活，死而复生好多次了。

**Comment by Lancenas** [comment]
ipv6墙建好了，xx-net基本走到头了

**Comment by Lisco** [comment]
xx_net凉了吗

**Comment by vanilla62302266** [comment]
我这也一样的问题。。。

**Comment by MARILYNHAN** [comment]
同样的问题，哭了，

**Comment by Freedominthesky** [comment]
看来是真凉了。

**Comment by NMBranger** [comment]
同样的问题，教育网，ipv6通着

**Comment by qiang92** [comment]
> > > > [https://github.com/miketwes/XX-Net-Linux](url)
> > > > 用这个repo里的good_ip.txt替换win版的就能正常使用了
> > > > 我win7测试成功了
> > > 
> > > 
> > > 我把那个repo的ip都导入还是没用，应该目前网络环境下以前可用的ip失效了
> > 
> > 
> > 5分钟前还可以，现在回复的时候仅存的一个可用ip也失效了
> 
> 重新再次替换IP即可恢复使用，1~4个可用IP……

有效

**Comment by ablebodied** [comment]
应该是ipv6 墙修好了，基本凉凉了，勉强可以一两个IP撑着，估计也用不久了

**Comment by 6keduo** [comment]
已完全恢复……100个有效IP地址……

**Comment by Jing--Li** [comment]
已完全恢复……100个有效IP地址……

**Comment by Upreak-Jkeey** [comment]
也许是年纪大，渐渐变得懒得折腾了。
现在在用加速度，半年了还蛮稳定的。价格也实惠，一年100来块。http://wz4.in/0i5q8  （使用此链接，你我都能得到20%优惠）

**Comment by ablebodied** [comment]
还真恢复了，不过感觉应该用不了多久了，估计是在测试新技术导致前几天失效

**Comment by ablebodied** [comment]
貌似又跪了，你们呢？

**Comment by AeneasZhu** [comment]
> 貌似又跪了，你们呢？


属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 3
有效 IPv6 IP 数 | 1
总 IP 数 | 468
XX-Net 状态 | 工作
IP 延迟 | 585
连接池(帮助) | 新:0 h1:0 h2:3
浏览器代理设置 | OK
CA 证书状态(下载) | OK

原生IPV6也不行了

**Comment by ablebodied** [comment]
> > 貌似又跪了，你们呢？
> 
> 属性	值
> IPv4 状态	OK
> IPv6 状态(如何开启)	OK
> 有效 IPv4 IP 数	3
> 有效 IPv6 IP 数	1
> 总 IP 数	468
> XX-Net 状态	工作
> IP 延迟	585
> 连接池(帮助)	新:0 h1:0 h2:3
> 浏览器代理设置	OK
> CA 证书状态(下载)	OK
> 原生IPV6也不行了

很显然是墙封堵了ipv6，真是邪恶

**Comment by Jing--Li** [comment]
又不能用了！

**Comment by Freedominthesky** [comment]
散了散了吧，付费VPN走起吧。

**Comment by rexwang011** [comment]
今天早上还能用，中午的时候又不行了

**Comment by AeneasZhu** [comment]
IPv4 状态 | OK
-- | --
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 484
XX-Net 状态 | 工作
IP 延迟 | 9999

油管720P居然还能流畅。。。。。

**Comment by Alberthoya** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 98
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by Alberthoya** [comment]
用不了

**Comment by boluoweifenda** [comment]
> > > [https://github.com/miketwes/XX-Net-Linux](url)
> > > 用这个repo里的good_ip.txt替换win版的就能正常使用了
> > > 我win7测试成功了
> > 
> > 
> > 我把那个repo的ip都导入还是没用，应该目前网络环境下以前可用的ip失效了
> 
> 5分钟前还可以，现在回复的时候仅存的一个可用ip也失效了

me too...................

**Comment by lefantian** [comment]
有一片大陆与世隔绝，有事托梦

**Comment by AzureStar5** [comment]
有没有大神有其他的利用教育网IP v6成功连接的方法？

**Comment by ablebodied** [comment]
> 有没有大神有其他的利用教育网IP v6成功连接的方法？

ipv6封堵了，教育网应该也一样

**Comment by erdcy** [comment]
今晚出现了相同情况
XX-Net Status:

sys-platform: armv7l, Linux-4.14.95-armv7l-with-libc
os-system: Linux
os-version: #0 SMP Mon Jan 28 08:54:32 2019
os-release: 4.14.95
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.15
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:89 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Eri5Ch** [comment]
没招了 等待吧

**Comment by AvigatorC** [comment]
这几天时行时不行，给我人整傻了

**Comment by jon945** [comment]
ipv6不行了，但是付费的x-tunnel怎么也不行了呢？不是说x-tunnel不完全依赖ipv6吗？还是说服务器完全都没用了

**Comment by AeneasZhu** [comment]
沦陷日大阅兵临近了，维稳模式启动

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/12700

**Comment by AnyWAT** [comment]
XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 沦陷日大阅兵临近了，维稳模式启动

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> ipv6不行了，但是付费的x-tunnel怎么也不行了呢？不是说x-tunnel不完全依赖ipv6吗？还是说服务器完全都没用了

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 这几天时行时不行，给我人整傻了

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 没招了 等待吧

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 有一片大陆与世隔绝，有事托梦

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 用不了

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 又不能用了！

XX-net/XX-Net#12700

**Comment by AnyWAT** [comment]
> 今天早上还能用，中午的时候又不行了

XX-net/XX-Net#12700

**Comment by valasco** [comment]
吐槽下，全部显示OK，但是超1H仍旧是等待扫描，且扫描默认最大30，所以有人说这软件挺尸了.....

**Comment by chrisyaooo** [comment]
> 沦陷日大阅兵临近了，维稳模式启动

跟70周年有关系吗，64那几天xx是不是也不能用？
