### ISSUE TITLE
 [发布] 3.13.2 解决 Google 证书更新导致无法工作 

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#12705]
v3.13.3 #12718

---
# What is new:
* This version has update for google's new certificate.
* And a few bugfix.

# 新版特性
* 这个版本更新了google 使用的新证书。
* 以及一些错误修复。

---
https://github.com/XX-net/XX-Net/releases/download/3.13.2/XX-Net-3.13.2.7z

**Comment by fhq8800** [comment]
快一年才更新一个版本。

**Comment by 6keduo** [comment]
更新后又可以用了，只是有效IP目前只有1个……

**Comment by lefantian** [comment]
感谢！！！！！！！！！

**Comment by ablebodied** [comment]
希望可以用啊

**Comment by hzq21** [comment]
目前挂下tg可以。。

**Comment by ctrlands** [comment]
刚试了一下, 又可以愉快的访问404网站了，感谢

**Comment by Eri5Ch** [comment]
艾玛 复活了 谢谢谢谢。。。

**Comment by windzlife** [comment]
可以用了


属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 1
总 IP 数 | 454
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:1
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by J-zin** [comment]
为什么我还是不可以呀 有效ipv6数 是0

**Comment by klc197** [comment]
还是不行啊。。。

**Comment by AeneasZhu** [comment]
喜大普奔，举国同庆！

**Comment by jk9781** [comment]
有效 IPv6 IP 数 100。满血复活，感谢！

**Comment by fgit49153** [comment]
@SeaHOH 用start.bat启动，怎么关闭，每次启动后自动设置的IE代理，如图，启动后自动勾选，现在想要它不自动勾选
![2019-08-31 10_04_43-Window](https://user-images.githubusercontent.com/38448223/64057957-cf210b80-cbd6-11e9-8421-19c43747587d.jpg)

**Comment by ql-jie** [comment]
又可以用了，非常感激！

**Comment by erdcy** [comment]
@hzq21 挂pc版的tg吗？

**Comment by gh2020gh** [comment]
请问如果是zebra或者goproxy要如何替换新的Google证书？谢谢。

**Comment by SeaHOH** [comment]
> 请问如果是zebra或者goproxy要如何替换新的Google证书？谢谢。

@MeABc 有没有时间更新一下？

---
希望不大，很久没看见他在 github 活动了。

**Comment by myjlpt** [comment]
那个上面不能用的，删除之前的CA证书，重新导入试试。我这边这么做正常了

**Comment by AeneasZhu** [comment]
今天又不行了

**Comment by J-zin** [comment]
又崩了。。。

**Comment by windzlife** [comment]
今天 又不行了？？？


属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 0
有效 IPv6 IP 数 | 0
总 IP 数 | 100
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10

**Comment by liangliangge521** [comment]
好的谢谢

**Comment by Quantum2Bits** [comment]
有效 IPv4 IP 数 	0
有效 IPv6 IP 数 	0
又不行了。

**Comment by 6keduo** [comment]
可以用，需要重新再贴一次IP地址（454那个）

**Comment by J-zin** [comment]
@6keduo 怎么重新贴啊

**Comment by Tpwick123** [comment]
> @SeaHOH 用start.bat启动，怎么关闭，每次启动后自动设置的IE代理，如图，启动后自动勾选，现在想要它不自动勾选
> ![2019-08-31 10_04_43-Window](https://user-images.githubusercontent.com/38448223/64057957-cf210b80-cbd6-11e9-8421-19c43747587d.jpg)

是开了全局GAEProxy代理吗？

**Comment by 6keduo** [comment]
> @6keduo 怎么重新贴啊

[https://github.com/miketwes/XX-Net-Linux/tree/master/data](url)其中的 “good_ip.txt”

**Comment by hzq21** [comment]
> @hzq21 挂pc版的tg吗？

嗯

**Comment by 6keduo** [comment]
> @6keduo 怎么重新贴啊

https://github.com/miketwes/XX-Net-Linux/tree/master/data其中的 “good_ip.txt”

**Comment by 6keduo** [comment]
> @6keduo 怎么重新贴啊

https://github.com/miketwes/XX-Net-Linux/tree/master/data

复制“good_ip.txt”中的IP地址……

**Comment by J-zin** [comment]
@6keduo 厉害 可以啦

**Comment by AeneasZhu** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 2
有效 IPv6 IP 数 | 0
总 IP 数 | 456
XX-Net 状态 | 工作
IP 延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:1
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 30

只要有IPV4就能翻墙？

**Comment by vanilla62302266** [comment]
> @6keduo 厉害 可以啦

请问贴到哪里呀？

**Comment by J-zin** [comment]
XX-Net-3.13.2\data\gae_proxy\good_ip.txt
@vanilla62302266

**Comment by vanilla62302266** [comment]
> XX-Net-3.13.2\data\gae_proxy\good_ip.txt
> @vanilla62302266



> XX-Net-3.13.2\data\gae_proxy\good_ip.txt
> @vanilla62302266

谢谢，弄好了，虽然只有一个有效ip

**Comment by fkrsr** [comment]
这个ip的地域差异太大了。同一台电脑，都是原生教育网ipv6。在帝都学校只有1个ip偶尔能用，假期回家十几个ip非常稳定。

**Comment by AeneasZhu** [comment]
216.58.215.56
216.58.215.251
216.58.215.251
216.58.215.91
216.58.215.255
216.58.215.254
108.177.122.200
216.58.215.252
108.177.122.197
108.177.122.201
108.177.111.103
108.177.122.167
216.58.223.254
216.58.223.251
108.177.122.166
216.58.223.248
216.58.223.222
108.177.122.181
216.58.223.224
216.58.223.225
216.58.223.220
216.58.223.235
216.58.223.223
2404:6800:4005:811::2014
2607:f8b0:4012:804::2014
2a00:1450:400f:80b::2014
2404:6800:4004:80f::2014
2800:3f0:4003:c00::99
2404:6800:4005:807::2014
2a00:1450:400f:807::2014
2404:6800:4004:807::2014
2404:6800:4005:80f::2014
2800:3f0:4003:c01::99
2404:6800:4005:809::2014
2a00:1450:4001:81f::2014
2a00:1450:400f:80c::2014
2800:3f0:4003:c02::99
2404:6800:4005:800::2014
2404:6800:4005:810::2014
2a00:1450:4017:806::2014
2a00:1450:4007:80f::2014
2404:6800:4005:802::2014
2a00:1450:4010:c08::99
2a00:1450:400f:806::2014
2404:6800:4005:80b::2014
2a00:1450:4007:80d::2014
2a00:1450:4001:818::2014
2404:6800:4003:c04::99
2a00:1450:400f:808::2014
2404:6800:4008:803::2014
2404:6800:4006:805::2014
2404:6800:4008:801::2014
2404:6800:4003:c00::99
2404:6800:4006:806::2014
2404:6800:4004:806::2014
2404:6800:4008:802::2014
2404:6800:4006:803::2014
2607:f8b0:4004:803::2014
2607:f8b0:400b:808::2014
2607:f8b0:4004:802::2014
2404:6800:4004:80c::2014
2a00:1450:4007:80c::2014
2607:f8b0:4004:811::2014
2607:f8b0:400b:809::2014
2800:3f0:4001:808::2014
2607:f8b0:4004:800::2014
2a00:1450:4007:813::2014
2404:6800:4004:80d::2014
2607:f8b0:400b:80f::2014
2607:f8b0:4004:80e::2014
2800:3f0:4001:817::2014
2404:6800:4004:81b::2014
2800:3f0:4001:807::2014
2800:3f0:4001:80f::2014
2800:3f0:4001:803::2014
2a00:1450:4002:806::2014
2a00:1450:4007:815::2014
2800:3f0:4001:80a::2014
2800:3f0:4001:801::2014
2a00:1450:4002:802::2014
2a00:1450:4007:812::2014
2a00:1450:4017:800::2014
2800:3f0:4001:805::2014
2800:3f0:4001:809::2014
2a00:1450:4002:80b::2014
2800:3f0:4001:810::2014
2a00:1450:4017:801::2014
2800:3f0:4001:80b::2014
2a00:1450:4002:808::2014
2800:3f0:4001:802::2014
2a00:1450:4017:804::2014
2800:3f0:4001:806::2014
2a00:1450:4017:808::2014
2404:6800:4004:800::2014
2404:6800:4012::2014
2a00:1450:4007:811::2014
2404:6800:4004:81a::2014
2607:f8b0:400a:808::2014
2a00:1450:4007:808::2014
2607:f8b0:400a:800::2014
2607:f8b0:4000:802::2014
2607:f8b0:400a:803::2014
2a00:1450:400a:801::2014
2607:f8b0:4000:817::2014
2607:f8b0:4000:80e::2014
2a00:1450:401b:801::2014
2404:6800:4004:80a::2014
2a00:1450:400a:802::2014
2607:f8b0:4000:816::2014
2a00:1450:401b:804::2014
2a00:1450:401b:807::2014
2a00:1450:4001:821::2014
2607:f8b0:4000:80f::2014
2a00:1450:401b:805::2014
2a00:1450:401b:806::2014
2607:f8b0:4000:811::2014
2a00:1450:401b:802::2014
2404:6800:4005:80a::2014
2a00:1450:400e:805::2014
2607:f8b0:4012:80a::2014
2607:f8b0:400e:c03::99
2a00:1450:400e:80c::2014
2607:f8b0:4004:80b::2014
2607:f8b0:4007:80e::2014
2607:f8b0:4012:805::2014
2607:f8b0:4007:802::2014
2607:f8b0:4004:80d::2014
2a00:1450:400e:80a::2014
2607:f8b0:4012:80b::2014
2607:f8b0:4007:80b::2014
2a00:1450:400d:807::2014
2607:f8b0:4004:80f::2014
2607:f8b0:4007:800::2014
2a00:1450:400e:803::2014
2607:f8b0:4012:809::2014
2607:f8b0:4004:805::2014
2a00:1450:400d:806::2014
2607:f8b0:4000:808::2014
2a00:1450:400d:803::2014
2607:f8b0:4012:808::2014
2404:6800:4006:804::2014
2a00:1450:4003:809::2014
2404:6800:4006:802::2014
2800:3f0:4002:804::2014
2404:6800:4006:807::2014
2a00:1450:4003:80b::2014
2a00:1450:4010:c0b::99
2404:6800:4006:808::2014
2800:3f0:4002:80a::2014
2a00:1450:4003:806::2014
2404:6800:400a:80b::2014
2a00:1450:4010:c0d::99
2800:3f0:4002:805::2014
2404:6800:4003:802::2014
2a00:1450:4003:803::2014
2404:6800:400a:807::2014
2800:3f0:4002:80b::2014
2404:6800:4003:c01::99
2404:6800:4003:c03::99
2800:3f0:4002:808::2014
2800:3f0:4001:80c::2014
2a00:1450:4010:c07::99
2800:3f0:4002:809::2014
2a00:1450:4010:c0e::99
2a00:1450:4007:816::2014
2404:6800:4002:802::2014
2a00:1450:4010:c05::99
2a00:1450:4014:80c::2014
2a00:1450:4001:81d::2014
2404:6800:4005:801::2014
2a00:1450:4001:824::2014
2404:6800:4005:80c::2014
2404:6800:4004:808::2014
2a00:1450:4001:81b::2014
2a00:1450:4001:81a::2014
2a00:1450:4003:801::2014
2a00:1450:4001:816::2014
2a00:1450:4003:805::2014
2800:3f0:4001:815::2014
2a00:1450:4001:806::2014
2a00:1450:4003:802::2014
2607:f8b0:4006:812::2014
2607:f8b0:4006:813::2014
2404:6800:4005:808::2014
2607:f8b0:4006:815::2014
2607:f8b0:4006:819::2014
2607:f8b0:4006:810::2014
2c0f:fb50:4002:802::2014
2a00:1450:4009:80c::2014
2a00:1450:400c:c08::99
2c0f:fb50:4002:803::2014
2a00:1450:4009:80f::2014
2a00:1450:400c:c0c::99
2a00:1450:4009:804::2014
2a00:1450:400c:c04::99
2a00:1450:4007:809::2014
2a00:1450:400c:c00::99
2800:3f0:4005:401::2014
2404:6800:4004:809::2014
2800:3f0:4005:402::2014
2a00:1450:4014:800::2014
2a00:1450:4014:80d::2014
2800:3f0:4005:400::2014
2a00:1450:4014:801::2014
2607:f8b0:4007:80c::2014
2607:f8b0:4006:802::2014
2a00:1450:400d:808::2014
2607:f8b0:4006:80e::2014
2404:6800:4003:808::2014
2a00:1450:400d:805::2014
2607:f8b0:4002:c06::99
2607:f8b0:4006:801::2014
2607:f8b0:4002:c00::99
2607:f8b0:4006:803::2014
2a00:1450:4010:c03::99
2a00:1450:401b:803::2014
2a00:1450:4010:c09::99
2a00:1450:401b:800::2014
2607:f8b0:4002:c0c::99
2a00:1450:4017:809::2014
2607:f8b0:4007:809::2014
2a00:1450:4010:c01::99
2607:f8b0:4008:806::2014
2607:f8b0:4009:807::2014
2607:f8b0:4008:80c::2014
2a00:1450:4017:805::2014
2800:3f0:4004:809::2014
2607:f8b0:4009:801::2014
2607:f8b0:4009:810::2014
2607:f8b0:4008:80d::2014
2800:3f0:4004:801::2014
2607:f8b0:400f:806::2014
2607:f8b0:400f:800::2014
2a00:1450:4001:815::2014
2404:6800:4001:800::2014
2a00:1450:4001:808::2014
2404:6800:4001:80d::2014
2a00:1450:4003:80a::2014
2607:f8b0:4002:c09::99
2a00:1450:4017:80a::2014
2607:f8b0:4005:804::2014
2607:f8b0:400a:809::2014
2607:f8b0:4005:808::2014
2607:f8b0:4005:807::2014
2a00:1450:4009:80d::2014
2a00:1450:4009:800::2014
2607:f8b0:4009:80d::2014
2a00:1450:400e:804::2014
2404:6800:4005:806::2014
2607:f8b0:4009:816::2014
2607:f8b0:4009:806::2014
2a00:1450:400e:806::2014
2a00:1450:400e:808::2014
2a00:1450:4001:825::2014
2607:f8b0:4005:80b::2014
2a00:1450:4001:817::2014
2a00:1450:4002:801::2014
2607:f8b0:4001:c0e::99
2a00:1450:400e:809::2014
2a00:1450:4002:807::2014
2607:f8b0:4001:c1b::99
2a00:1450:4002:80a::2014
2607:f8b0:4006:80f::2014
2a00:1450:400e:80d::2014
2607:f8b0:4006:800::2014
2a00:1450:4002:800::2014
2607:f8b0:4006:81a::2014
2607:f8b0:4020:807::2014
2404:6800:4003:c02::99
2607:f8b0:4009:80f::2014
2607:f8b0:4008:802::2014
2607:f8b0:400f:804::2014
2607:f8b0:400f:807::2014
2404:6800:4004:818::2014
2404:6800:4005:803::2014
2404:6800:4003:804::2014
2607:f8b0:4002:c08::99
2607:f8b0:4007:801::2014
2607:f8b0:4007:804::2014
2404:6800:4002:80a::2014
2404:6800:4005:804::2014
2404:6800:4002:804::2014
2404:6800:4008:c04::99
2404:6800:4008:c00::99
2607:f8b0:4000:80d::2014
2607:f8b0:4008:813::2014
2607:f8b0:4008:803::2014
2a00:1450:400f:809::2014
2a00:1450:4007:810::2014
2404:6800:4004:80b::2014
2a00:1450:4009:809::2014
2404:6800:4005:80e::2014
2404:6800:4005:80d::2014
2607:f8b0:4008:810::2014
2a00:1450:4001:820::2014
2607:f8b0:4005:801::2014
2a00:1450:4010:c0f::99
2a00:1450:400d:809::2014
2404:6800:400a:80c::2014
2404:6800:400a:808::2014
2a00:1450:4009:801::2014
2a00:1450:4009:807::2014
2607:f8b0:4007:808::2014
2607:f8b0:4006:818::2014
2a00:1450:4009:814::2014
2607:f8b0:4003:c01::99
2a00:1450:4002:809::2014
2607:f8b0:4003:c17::99
2607:f8b0:4003:c04::99
2a00:1450:4002:805::2014
2607:f8b0:4003:c09::99
2607:f8b0:4003:c15::99
2607:f8b0:4003:c05::99
2a00:1450:4006:806::2014
2a00:1450:4009:815::2014
2a00:1450:4006:808::2014
2607:f8b0:4000:813::2014
2404:6800:4007:801::2014
2607:f8b0:4000:804::2014
2404:6800:4007:808::2014
2607:f8b0:4003:c19::99
2a00:1450:4005:803::2014
2404:6800:4004:80e::2014
2404:6800:4007:802::2014
2a00:1450:4005:800::2014
2a00:1450:4005:80a::2014
2607:f8b0:4000:806::2014
2a00:1450:4018:802::2014
2404:6800:4009:80a::2014
2a00:1450:4018:800::2014
2a00:1450:4018:803::2014
2404:6800:4009:807::2014
2607:f8b0:4009:802::2014
2607:f8b0:4009:80b::2014
2404:6800:4012:1::2014
2404:6800:4009:800::2014
2607:f8b0:4009:811::2014
2a00:1450:400f:80a::2014
2607:f8b0:4000:812::2014
2607:f8b0:4000:814::2014
2607:f8b0:4009:815::2014
2a00:1450:4009:802::2014
2a00:1450:4009:812::2014
2a00:1450:4009:803::2014
2607:f8b0:4009:804::2014
2a00:1450:4005:80b::2014
2a00:1450:4009:810::2014
2404:6800:4004:819::2014
2a00:1450:401a:805::2014
2a00:1450:4006:802::2014
2a00:1450:4006:801::2014
2a00:1450:4007:80e::2014
2a00:1450:4007:80a::2014
2a00:1450:4007:817::2014
2a00:1450:4013:c01::99
2a00:1450:4013:c07::99
2a00:1450:4013:c04::99
2404:6800:4009:804::2014
2607:f8b0:400b:80e::2014
2607:f8b0:400b:80d::2014
2607:f8b0:400b:80c::2014
2607:f8b0:4000:80c::2014
2404:6800:4001:801::2014
2404:6800:4001:804::2014
2404:6800:4001:803::2014
2404:6800:4001:80c::2014
2607:f8b0:4009:80a::2014
2a00:1450:4009:811::2014
2404:6800:4009:810::2014
2404:6800:4009:809::2014
2404:6800:4009:80d::2014
2404:6800:4009:806::2014
2607:f8b0:4008:811::2014
2404:6800:4009:80c::2014
2a00:1450:4017:807::2014
2800:3f0:4005:403::2014
2607:f8b0:4002:c02::99
2607:f8b0:4000:815::2014
2a00:1450:4007:805::2014
2a00:1450:400e:80b::2014
2404:6800:4009:802::2014
2404:6800:4009:80b::2014
2404:6800:4009:801::2014
2404:6800:4003:807::2014
2404:6800:4009:808::2014
2607:f8b0:4020:804::2014
2a00:1450:4010:c02::99
2a00:1450:4001:819::2014
2607:f8b0:4005:806::2014
2607:f8b0:400a:804::2014
2a00:1450:4009:808::2014
2a00:1450:4009:80e::2014
2607:f8b0:4007:806::2014
2607:f8b0:4004:810::2014
2404:6800:4001:80f::2014
2a00:1450:4016:80d::2014
2607:f8b0:4009:808::2014
2a00:1450:4016:806::2014
2607:f8b0:4020:805::2014
2a00:1450:4019:803::2014
2a00:1450:4019:800::2014
2a00:1450:4019:802::2014
2607:f8b0:4008:805::2014
2404:6800:4004:801::2014
2607:f8b0:4003:c00::99
2607:f8b0:4003:c12::99
2404:6800:4009:80e::2014
2607:f8b0:4004:801::2014
2800:3f0:4001:80d::2014
2607:f8b0:4008:80e::2014
2a00:1450:4010:c0a::99
2a00:1450:4006:807::2014
2a00:1450:4016:80b::2014
2a00:1450:4016:800::2014
2607:f8b0:4007:80d::2014
2800:3f0:4004:800::2014
2a00:1450:4017:80b::2014
2800:3f0:4004:808::2014
2800:3f0:4004:806::2014
2800:3f0:4004:807::2014
2404:6800:4006:80a::2014
2404:6800:4008:c01::99
2404:6800:4008:c07::99
2404:6800:4002:803::2014
2a00:1450:400e:807::2014
2607:f8b0:4009:803::2014
2607:f8b0:4004:80c::2014
2a00:1450:4009:813::2014
2a00:1450:4001:81c::2014
2607:f8b0:4009:813::2014
2607:f8b0:4009:809::2014
2800:3f0:4001:814::2014
2a00:1450:400c:c07::99
2607:f8b0:400f:805::2014
2404:6800:4001:806::2014
2404:6800:4007:800::2014
2800:3f0:4004:805::2014
2404:6800:4007:807::2014
2404:6800:4007:80f::2014
2a00:1450:4016:80a::2014
2a00:1450:400e:801::2014
2a00:1450:4007:814::2014
2607:f8b0:400d:c0f::99
2404:6800:4005:805::2014
2a00:1450:4013:c00::99
2a00:1450:4013:c03::99
2607:f8b0:4009:80c::2014
2800:3f0:4001:816::2014
2c0f:fb50:4003:801::2014
2607:f8b0:4004:804::2014
2607:f8b0:4009:812::2014
2607:f8b0:4006:814::2014
2a00:1450:4019:801::2014
2607:f8b0:4002:c03::99
2404:6800:4007:80b::2014
2404:6800:4009:803::2014
2607:f8b0:4006:804::2014
2607:f8b0:4002:c07::99
2607:f8b0:4005:802::2014
2607:f8b0:4005:80a::2014
2a00:1450:400e:802::2014
64:ff9b::4a7d:1899
2607:f8b0:4005:805::2014
64:ff9b::acd9:c299
2a00:1450:4001:80b::2014
2607:f8b0:4006:811::2014
2607:f8b0:400d:c0b::99
2607:f8b0:400d:c01::99
2a00:1450:4003:807::2014
2404:6800:400a:806::2014
2a00:1450:4003:804::2014
2404:6800:4009:805::2014
2a00:1450:4016:808::2014
2a00:1450:4016:807::2014
2a00:1450:4016:809::2014
2404:6800:4003:80a::2014
2607:f8b0:400e:c09::99
216.58.193.212
216.58.192.148
172.217.10.20
172.217.31.212
172.217.18.244
216.58.211.244
172.217.27.116
216.58.207.52
216.58.211.212
216.58.212.244
216.58.197.52
172.217.29.244
172.217.0.148
216.58.203.84
216.58.208.148
172.217.11.52
172.217.167.180
172.217.10.212
172.217.22.212
172.217.10.52
216.58.219.212
172.217.160.148
108.177.15.153
216.58.192.244
209.85.200.153
172.217.28.20


这些IP可以撑一会

**Comment by yangsl158** [comment]
奇怪。。。自动更新一直无法成功，手动下载又一直下不下来。。

**Comment by dxdvid** [comment]
> 奇怪。。。自动更新一直无法成功，手动下载又一直下不下来。。

我的也无法自动更新，手动下载下来了，丢到下载目录中，无法直接加载。现在是要重新部署吗？
