### ISSUE TITLE
windows start.bat 无法打印日志

### ISSUE THREAD

**Issue by Tim-Xue** [XX-net/XX-Net#12706]
windows start.bat 无法打印日志
@SeaHOH 
![捕获](https://user-images.githubusercontent.com/38043364/64003999-098b9980-cb40-11e9-8815-2220f0d73471.PNG)

**Comment by AzureStar5** [comment]
同样的问题，求教

**Comment by tofu23** [comment]
我也是这问题，哭了，老版本都没有的。需要改动什么吗？
