### ISSUE TITLE
无法使用扫不到Ip的看看这个帖子啊，改一下config.py就好了

### ISSUE THREAD

**Issue by imudie123** [XX-net/XX-Net#12703]
看一下：
https://github.com/XX-net/XX-Net/issues/12700

**Comment by erdcy** [comment]
A big thumb for you

**Comment by alalaaaa** [comment]
ipv6有效地址只有1个，ipv6有效地址是怎么获得的？gogotester不是不能扫描ipv6么

**Comment by erdcy** [comment]
照着 #12700 操作一下就可以用了
