### ISSUE TITLE
Miredo无法下载且镜像仓库里不存在

### ISSUE THREAD

**Issue by chorylee001** [XX-net/XX-Net#12707]
MacOS Mojave 10.14.5下安装miredo尝试开启ipv6失败。
按照教程里的下载链接：http://www.deepdarc.com/miredo-osx-prerelease2.pkg.zip ，该链接已无法访问。

查找miredo相关开源代码：https://github.com/bit/miredo-osx/releases ，该编译过后的几个版本包也无法访问。

一个月前该问题被解答过：https://github.com/XX-net/XX-Net/issues/12648 ，建议使用apt-get install miredo进行安装无效，提示：Couldn't find package miredo。

请问现在还有公共的miredo资源吗？还请帮忙提供个开放链接，谢谢各位了。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues?q=is:issue+miredo+label:分类_知识
这是之前如何编译的经验贴。
