### ISSUE TITLE
更新的最新版本后，打开后没反应

### ISSUE THREAD

**Issue by tofu23** [XX-net/XX-Net#12710]
就只显示了这么一句话就没别的了
WARNING: root: Load Crypto. Cipher. ARC4 Failed. Use Pure Python Instead.

之前老版本虽然连不上，但是你能看到很多文字一直在动，红字，绿字什么的。现在都没了。求助大神！

**Comment by tofu23** [comment]
![搜狗截图20190831014634](https://user-images.githubusercontent.com/46002134/64041767-df16fc00-cb92-11e9-9a3e-05eaa98c6c5f.png)

**Comment by hubsocks** [comment]
可以用,只是没用任何输出信息
过了一会就出现这个错误信息,但还是可以继续使用.
![快照2](https://user-images.githubusercontent.com/46856823/64056872-2cae5b80-cbc9-11e9-982d-58a5d4ff2c90.png)
![快照3](https://user-images.githubusercontent.com/46856823/64056873-2fa94c00-cbc9-11e9-886d-2ba9d66fc23b.png)

**Comment by SeaHOH** [comment]
Duplicate of #12706
