### ISSUE TITLE
Teredo 隧道	休眠（未连接）

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#12713]
Teredo 隧道  已开启  也尝试更换服务器  但 一直是  休眠（未连接）状态

**Comment by qucanswo** [comment]
重启各模块试试

**Comment by iamdurui** [comment]
一直是红色的，重启各模块好几次了啊，

**Comment by kitkw** [comment]
不行 Teredo 隧道一直是   休眠（未连接）  但状态显示 是OK   ?!同时显示  等待扫描 IP，建议开启 IPv6。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6
