### ISSUE TITLE
中国移动网络XX-NET不能翻墙?

### ISSUE THREAD

**Issue by AeneasZhu** [XX-net/XX-Net#12714]
以前学校用的是电信网络，开teredo隧道结合XX-NET快的飞起，但暑假期间学校改用移动网络，XX-NET就不能走teredo隧道了，即便有时偶尔成功，速度也非常感人，甚至结合6plat代理原生IPV6也不行。我手机是电信的，笔记本连接手机热点后用XX-NET也很顺利（结合6plat）。

是因为中国移动的墙更高、更厚吗？

**Comment by SeaHOH** [comment]
这些电信公司都很大，各部分的网络条件不可能一样。
如果在这里搜索一下，就能看到有许多人的使用感受和你正好相反。

**Comment by CleverZCW** [comment]
有这个可能 我在家手机热点是联通网络的话速度飞快  公司是电信网络也是速度飞快  只有在家的宽带是移动的  完全连不上  可以说移动真的是辣鸡的一批

**Comment by xiaozixun** [comment]
这个真的只看脸，我用的移动和电信，两个都是随缘链接。

**Comment by AeneasZhu** [comment]
> 有这个可能 我在家手机热点是联通网络的话速度飞快 公司是电信网络也是速度飞快 只有在家的宽带是移动的 完全连不上 可以说移动真的是辣鸡的一批

是的，我在公司也是电信，进teredo隧道速度飞快。学校以前电信也是飞快，暑假换成了移动就根本连不上
