### ISSUE TITLE
[发布] 3.13.3 修复控制台窗口日志输出

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#12718]
# What is new:
* Fix the console window log output.

# 新版特性
* 修复控制台窗口日志输出。

---
https://github.com/XX-net/XX-Net/releases/download/3.13.3/XX-Net-3.13.3.7z

**Comment by klc197** [comment]
big thumb for you

**Comment by FisherXT** [comment]
感谢开发团队，满血复活

**Comment by qizhiyanhuang** [comment]
great

**Comment by ZuluSierraHotel** [comment]
感谢大佬！！！

**Comment by lefantian** [comment]
感谢感谢感谢！！

**Comment by ablebodied** [comment]
这次确实可用IP又上去了

**Comment by yangsl158** [comment]
诶，为啥我的又是“连接尚未建立”。。

**Comment by iamdurui** [comment]
teredo tunnel一直链接不上，怎么解决啊？

**Comment by iamdurui** [comment]
升级之后还不如昨天的3.13.2版本呢？今天一直是链接不上啊

**Comment by lefantian** [comment]
又不能连接了，是不是跟更新有关系呢，对github.com的访问也变得困难了。使用的是黑龙江电信。

**Comment by SeaHOH** [comment]
>     修复控制台窗口日志输出。

看不懂这句话，又觉得这版有问题的，完全可以不升级。

**Comment by sky123456789sky** [comment]
3.13.3 装在两台不同宽带的不同路由器上 一台梅林一台OP     SMART ROUTER功能 大概使用几小时就会抽风 然后国内网页都会溜一圈美国再回来 重启又可以用几个小时 没升级前无此情况 请大大出手查下BUG

**Comment by SeaHOH** [comment]
@sky123456789sky 没有修改过相关代码，请自行排查使用设置和环境。

**Comment by jk9781** [comment]
3.13.3连不上，退回上一版了。。。

**Comment by SeaHOH** [comment]
> 3.13.3连不上，退回上一版了。。。

然后就能连上？有些时候我实在是怀疑有些人的年龄，基本的逻辑都不讲了么。

**Comment by sky123456789sky** [comment]
找到问题了 这不是新版本的问题 此问题一直存在 XX装在路由器 运营商会在10天左右断开你的宽带连接 重新拨号后 XX的SMART ROUTER便会抽风 导致国内网站全部不能访问 只能访问国外站点 重启SMART ROUTER模块可以恢复 不知道大大还有兴趣修复吗

**Comment by SeaHOH** [comment]
鉴于各种现状，大的改动和修复我是不会再做了。

**Comment by Shu1110** [comment]
> > 3.13.3连不上，退回上一版了。。。
> 
> 然后就能连上？有些时候我实在是怀疑有些人的年龄，基本的逻辑都不讲了么。
哈哈哈，本来是想来看有没有人提供能正常翻墙的方法。结果看到大佬的回复，看上瘾了，哈哈哈。真的是标准程序员语气啦~（悄悄说：现在翻每个帖子就是为了找大佬的回复，嘻嘻）
