### ISSUE TITLE
"Force-IPv6" not available, Please check.

### ISSUE THREAD

**Issue by baobao219** [XX-net/XX-Net#12715]
XX-Net Status:

sys-platform: x86_64, Darwin-18.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
os-release: 18.7.0
os-detail: Release:10.14.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
xxnet-version: 3.13.1
python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:53
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 784
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

这是什么原因呢，通过ifconfig -a 可以看到ipv6地址

**Comment by SeaHOH** [comment]
IPv6 地址种类很多，这样写没人能帮到你。
估计你的 miredo 根本就没正常工作吧。
