### ISSUE TITLE
好神奇，为什么更新后我能用阿？

### ISSUE THREAD

**Issue by djay1126** [XX-net/XX-Net#12728]
![QQ截图20190905132643](https://user-images.githubusercontent.com/37871408/64314332-42fd5280-cfe1-11e9-8a3b-e449a3c2f2a5.jpg)

？？？

**Comment by taoeternal2018** [comment]
命令行里输入一下 netsh int ipv6 show teredo，看看服务器名称是什么？

**Comment by Yanxingang** [comment]
类型                    : disabled
服务器名称              : win1807.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by taoeternal2018** [comment]
> 类型 : disabled
> 服务器名称 : win1807.ipv6.microsoft.com.
> 客户端刷新间隔 : 30 秒
> 客户端端口 : unspecified
> 状态 : offline
> 错误 : 无

你这个能用吗 我用你这个还是刷不出可用ipv6 看来跟网络还有关系

**Comment by StephenAnboer** [comment]
是不是因为ip扫描设置里面，IP段列表全是ipv4地址？？？
你的高级，扫描设置里，ip段列表是什么？

**Comment by nly4lov** [comment]
我也能用啊。

> C:\Users\syd>netsh int ipv6 show teredo
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient
Server Name             : teredo.remlab.net.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : qualified
Client Type             : teredo client
Network                 : managed
NAT                     : symmetric (port)
NAT Special Behaviour   : UPNP: No, PortPreserving: No
Local Mapping           : 192.168.0.107:56348
External NAT Mapping    : 59.61.43.107:3846

**Comment by hubsocks** [comment]
@nly4lov 福建省厦门市 电信
