### ISSUE TITLE
更新完就不能用了，一直显示建议开启ipv6

### ISSUE THREAD

**Issue by StephenAnboer** [XX-net/XX-Net#12727]
更新完就不能用了，一直显示建议开启ipv6，但是ipv6已经开了，显示的也是ok，不知道怎么回事

**Comment by snipertulip** [comment]
> 更新完就不能用了，一直显示建议开启ipv6，但是ipv6已经开了，显示的也是ok，不知道怎么回事

扫到的新ip，秒射，直接失效
