### ISSUE TITLE
可以用的ip一直是0啊，  几个版本都升级了的， 大半年了吧， 都没有办法用了

### ISSUE THREAD

**Issue by qeqeqe236** [XX-net/XX-Net#12721]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7600-SP0
os-system: Windows
os-version: 6.1.7600
os-release: 7
os-detail: Version:6-1; Build:7600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by phoenixzzan** [comment]
https://github.com/XX-net/XX-Net/wiki/IPV6-Win7
