### ISSUE TITLE
您的项目试图通过将一个项目分为多个项目来规避我们的配额限制，因此该项目已被暂停

### ISSUE THREAD

**Issue by dfg45ryh5rw3** [XX-net/XX-Net#12729]
谷歌现在似乎严格了, 以前建的appID好多被封,
登录邮箱才发现8月26日就开始给我发一堆警告邮件

**Comment by snipertulip** [comment]
> 谷歌现在似乎严格了, 以前建的appID好多被封,
> 登录邮箱才发现8月26日就开始给我发一堆警告邮件

我的怎么没有收到

**Comment by snipertulip** [comment]
> 谷歌现在似乎严格了, 以前建的appID好多被封,
> 登录邮箱才发现8月26日就开始给我发一堆警告邮件

收到启发，立马规则运行：被动模式扫描，GAE AppID使用一个，有效隧道ip6有了十几个IP，足够查资料了，不知道能不能长时间挺住

**Comment by burdenlee** [comment]
没发现..用了10个id

**Comment by dfg45ryh5rw3** [comment]
可能是我建的比较多, 普通用户没受到影响
下面是邮件翻译


尊敬的开发，
--
我们最近已经检测到您的谷歌云项目xxxx（xxxx）已通过规避作为一个多个项目，我们的配额限制，并违反了我们的服务条款。您的项目xxxx（xxxx）已暂停
如果您认为此悬浮液错误应用，请提交申诉 。请注意，您应该作为项目业主访问上诉页面登录。有关提交申诉或想了解更多的帮助，更多有关过程检查违反政策常见问题 。
请注意，您可能已经收到，我们将暂停该项目，如果你不改正违规行为的警告。如果您没有收到一个警告，那是因为你的项目的行为严重的服务或其他用户的干扰。谷歌被迫暂停项目，以保护系统的完整性。
请花一点时间来审查服务的谷歌云平台条款中， 可接受使用政策和适用的服务条款针对特定谷歌API使用的是这样，你不违反我们的未来条款和政策。

**Comment by snipertulip** [comment]
> 可能是我建的比较多, 普通用户没受到影响
> 下面是邮件翻译
> 
> ## 尊敬的开发，
> 我们最近已经检测到您的谷歌云项目xxxx（xxxx）已通过规避作为一个多个项目，我们的配额限制，并违反了我们的服务条款。您的项目xxxx（xxxx）已暂停
> 如果您认为此悬浮液错误应用，请提交申诉 。请注意，您应该作为项目业主访问上诉页面登录。有关提交申诉或想了解更多的帮助，更多有关过程检查违反政策常见问题 。
> 请注意，您可能已经收到，我们将暂停该项目，如果你不改正违规行为的警告。如果您没有收到一个警告，那是因为你的项目的行为严重的服务或其他用户的干扰。谷歌被迫暂停项目，以保护系统的完整性。
> 请花一点时间来审查服务的谷歌云平台条款中， 可接受使用政策和适用的服务条款针对特定谷歌API使用的是这样，你不违反我们的未来条款和政策。

你一个账户建了多少个appid?

**Comment by akiritoa** [comment]
我只建了两个，好像都被暂停了。。

**Comment by dfg45ryh5rw3** [comment]
> > 可能是我建的比较多, 普通用户没受到影响
> > 下面是邮件翻译
> > ## 尊敬的开发，
> > 我们最近已经检测到您的谷歌云项目xxxx（xxxx）已通过规避作为一个多个项目，我们的配额限制，并违反了我们的服务条款。您的项目xxxx（xxxx）已暂停
> > 如果您认为此悬浮液错误应用，请提交申诉 。请注意，您应该作为项目业主访问上诉页面登录。有关提交申诉或想了解更多的帮助，更多有关过程检查违反政策常见问题 。
> > 请注意，您可能已经收到，我们将暂停该项目，如果你不改正违规行为的警告。如果您没有收到一个警告，那是因为你的项目的行为严重的服务或其他用户的干扰。谷歌被迫暂停项目，以保护系统的完整性。
> > 请花一点时间来审查服务的谷歌云平台条款中， 可接受使用政策和适用的服务条款针对特定谷歌API使用的是这样，你不违反我们的未来条款和政策。
> 
> 你一个账户建了多少个appid?

我好几个账号, 建了一堆
