### ISSUE TITLE
IPv6状态为OK, 同时显示连接尚未建立

### ISSUE THREAD

**Issue by litongjava** [XX-net/XX-Net#12722]
诊断信息如下
```
XX-Net Status:

sys-platform: x86_64, Linux-4.13.9-300.fc27.x86_64-x86_64-with-debian-8.11
os-system: Linux
os-version: #1 SMP Mon Oct 23 13:41:58 UTC 2017
os-release: 4.13.9-300.fc27.x86_64
os-detail: Dist:debian; Version:8.11; ID:
architecture: 64bit,ELF
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.9
openssl-version: 16.0.0 TLSv1_2 h2:npn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:14 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
```
Graproxy==>状态==>IPv6状态为OK, 同时显示连接尚未建立。

**Comment by langbao** [comment]
同样的问题

**Comment by vanilla62302266** [comment]
我这也是，升级前还好的，升级到3.13.3就出现这个问题了

**Comment by vanilla62302266** [comment]
诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7600-SP0
os-system: Windows
os-version: 6.1.7600
os-release: 7
os-detail: Version:6-1; Build:7600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:302 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by vanilla62302266** [comment]
重启若干次以后好了
