### ISSUE TITLE
不要说什么隧道问题，隧道好好的，也扫不到ip

### ISSUE THREAD

**Issue by imudie999** [XX-net/XX-Net#12731]
![隧道2](https://user-images.githubusercontent.com/53925827/64355443-d2335600-d033-11e9-94a0-8944ecd8b0c2.JPG)

**永远都是“等待扫描 IP，建议开启 IPv6。”**

**Comment by StephenAnboer** [comment]
我也是。。但是ipv6是好好的

**Comment by burdenlee** [comment]
路由器打开UPNP

**Comment by StephenAnboer** [comment]
是不是因为ip扫描设置里面，IP段列表全是ipv4地址？？？

**Comment by snipertulip** [comment]
> ![隧道2](https://user-images.githubusercontent.com/53925827/64355443-d2335600-d033-11e9-94a0-8944ecd8b0c2.JPG)
> 
> **永远都是“等待扫描 IP，建议开启 IPv6。”**

 [https://github.com/XX-net/XX-Net/issues/12729](url)
个人appid使用一个，扫描被动模式，1-20 IP之间徘徊

**Comment by imudie999** [comment]
> 
> 
> 路由器打开UPNP

没用啊。不管是开UPNP，还是开DMZ，都没用。

**Comment by imudie999** [comment]
> 
> 
> > ![隧道2](https://user-images.githubusercontent.com/53925827/64355443-d2335600-d033-11e9-94a0-8944ecd8b0c2.JPG)
> > **永远都是“等待扫描 IP，建议开启 IPv6。”**
> 
> [https://github.com/XX-net/XX-Net/issues/12729](url)
> 个人appid使用一个，扫描被动模式，1-20 IP之间徘徊

该了，还是扫不出来。

**Comment by ksit1110** [comment]
ISP是移动的？

**Comment by maxphoenixwayne** [comment]
我也是一样的问题，一直没有IPv6

**Comment by SeaHOH** [comment]
说过了，所有 teredo 都不行就用其它隧道，还不行就换其它代理工具，不要来这里开些没用的问题。
