### ISSUE TITLE
还是老问题“等待扫描ip，请开启ipv6”，刚打开时是总ip453，可用ipv6是9，后来倒数到0

### ISSUE THREAD

**Issue by klc197** [XX-net/XX-Net#12738]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:453 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by klc197** [comment]
已经5天没上YouTube了，难受

**Comment by patrott** [comment]
用这个可以上YouTube看4K视频：[快速翻墙教程](https://github.com/xiaoming2028/kexueshangwang/wiki)
