### ISSUE TITLE
换teredo也刷不出几个有效IP的同学尝试一下换路由器 或者本来连有线改用wifi

### ISSUE THREAD

**Issue by taoeternal2018** [XX-net/XX-Net#12737]
升级最新版本后 发现怎么换teredo也刷不出IPV6的IP，以前一直好好的，今天心血来潮，把有线改成连wifi 有效IP直接90+，又可以愉快的翻墙了，感谢作者提供这么优秀的工具
![ipv6](https://user-images.githubusercontent.com/29194973/64488869-4c0b4f80-d27f-11e9-9ce7-29eec20295f5.jpg)

**Comment by taoeternal2018** [comment]
![ipv6 2](https://user-images.githubusercontent.com/29194973/64488950-6c87d980-d280-11e9-95e5-c81d08d743df.jpg)

**Comment by Eri5Ch** [comment]
嗯 没错 光猫直连的路由器刷不出ip 然后又加了一个路由器 才顺利刷出ip 具体原因没有搞清楚。。。

**Comment by akiritoa** [comment]
前几天能用，昨天晚上突然不能用了。。一直外接路由，难道是路由被禁了

**Comment by valasco** [comment]
> 前几天能用，昨天晚上突然不能用了。。一直外接路由，难道是路由被禁了

的确，前天晚上爽，昨天晚上基本换teredo也没用！

**Comment by patrott** [comment]
xx-net 不稳定，为什么不试试这个更稳定的呢？[稳定SSR机场搭建](https://github.com/xiaoming2028/kexueshangwang/wiki)

**Comment by SeaHOH** [comment]
这个方法看起来很玄学，真的有用吗？

**Comment by taoeternal2018** [comment]
确实有点玄学了 我连另外路由器也时好时坏，关掉吧，免得误导人
