### ISSUE TITLE
【咨询】原生ipv6无可用IP，HE Tunnel无ipv6无网络连接

### ISSUE THREAD

**Issue by jc3213** [XX-net/XX-Net#12735]
如标题所示

1）路由器Tomato OS，设置IPV6走DHCPv6 with PD能分配到IPV6地址，然后过一段时间就可以开始访问IPV6网站或者ping IPV6地址。 https://test-ipv6.com 现实拥有ipv6环境。 但是XX-NET所有IP无法连接，IP数直接降低为0。删除`goodip.txt`后，无法获取新得ip。

2）路由器设置 IPV6走6in4 Tunnel，设置好各种信息跟DDNS后，Windows本地连接显示IPV6 无网络连接。https://test-ipv6.com 显示无IPV6地址（但是本地连接有），你的ISP的DNS支持IPV6 。XX-NET提示IPV6 Fail。无法ping任何IPV6地址也无法打开任何IPV6网站。

附加说明：前天之前一直好好得。昨天早上也是这样，然后HE做了2个Tunnel不停切换，重启路由器折腾了1小时左右恢复了。今天早上起来折腾到现在无解，不知道是HE的TunnelBroker哪出了问题？

**Comment by jc3213** [comment]
PS：可以的话推荐个便宜的爬墙工具，主要去nyaa上下下种子，以及上上推跟P站

**Comment by jc3213** [comment]
@SeaHOH @xxnet

**Comment by hubsocks** [comment]
@jc3213 估计又是懒得看以前的贴子.公信步专门封锁针对各种方式连接 google的ipv6,就算你连上google的ipv6,也是不稳定.
但连接google ipv4一直没有封锁.因为那些可连接的ipv4同时也是gmail.com 的重要服务.国内也是很多公司需要的用.
很多高校有高速代理,自己编写爬虫代理加检测功能的软件,不断爬网页.可长期有免费直连国内的高速墙使用.
goproxy绑定免费域名.使用ipv4也可以继续使用.

**Comment by jc3213** [comment]
@hubsocks 我更想知道的是HE的Tunnel直接导致整个我这边IPV6环境彻底爆炸的原因。Windows显示IPV6没有网络连接就不说了，ping也不通，任何ipv6相关全部无法访问。但是换回ISP原生IPV6除了谷歌外一切正常。

PS：goproxy我看有好几个项目。不知道你说的哪个？

**Comment by SeaHOH** [comment]
如果你不需要登录 twitter，那么可以尝试一下我自用的工具。主要是用各种手段直连，点头像就可以找到。

**Comment by jc3213** [comment]
我发现这个问题是DNS导致得，HE自带得IPV6 DNS不可用（任何环境都ping不通）直接导致使用HE Tunnel的话IPV6彻底崩溃。添加了百度DNS后恢复。至于推荐的工具，回头研究一下。我最主要还是去nyaa下种子，其他需求并不大（还有在线漫画网站一些用的图床是被屏蔽的，但并不是特别多）
