### ISSUE TITLE
启动错误 10107

### ISSUE THREAD

**Issue by HarrrrryLi** [XX-net/XX-Net#1273]
![default](https://cloud.githubusercontent.com/assets/10751513/10713668/52c6b0bc-7afe-11e5-9f18-63b4728b391e.PNG)
双击start后  无法正常启动   也无法运行XX_NET  错误代码10107

**Comment by xxnet** [comment]
参考这里：
http://stackoverflow.com/questions/14281591/python-socket-bound-on-0-0-0-0-cant-connect-via-127-0-0-1

可能是什么安全软件再干扰，停掉可能的安全监控软件试试

2015-10-25 9:54 GMT+08:00 Awful-fresh-hand <notifications@github.com>:
