### ISSUE TITLE
分享个日本的SSR节点

### ISSUE THREAD

**Issue by hubnncly** [XX-net/XX-Net#12747]
账号不是我的，我是从TG群里面找来的，我自己测试了能用，会用的应该知道怎么用
ssr://MTM5LjE2Mi4xMjIuMTIxOjQ2NDM0Om9yaWdpbjphZXMtMjU2LWNmYjpwbGFpbjpSMkZLWkRaMGNqWTBOVEZILz9vYmZzcGFyYW09JnJlbWFya3M9VTFOUzU2dVo3N3lhYUhSMGNEb3ZMM1F1WTI0dlFXazVlSEpzYkVj
![111](https://user-images.githubusercontent.com/55238801/64867469-0cbe7380-d670-11e9-8cbc-65fcdd35ed3c.jpg)

**Comment by faywon** [comment]
这东西怎么用？

**Comment by 2378** [comment]
ssr://139.162.122.121:46434:origin:aes-256-cfb:plain:R2FKZDZ0cjY0NTFH/?obfsparam=&remarks=U1NS56uZ77yaaHR0cDovL3QuY24vQWk5eHJsbEc

个人分享的一般不用，实在要用宁可用公开的

分享个站点好了 https://free-ss.site/ 虽说是重点打击对象，关键量大/更新快，撑个一两天没问题

健身教练让我们传播真相，好像难度有点大，传播点梯子还是可以的

**Comment by SeaHOH** [comment]
单独分享一个影响似乎不太好，关闭此问题。
