### ISSUE TITLE
使用最新版xx时有些奇怪的问题

### ISSUE THREAD

**Issue by gh2020gh** [XX-net/XX-Net#12745]
youtube的评论永远在加载，无法显示。切换到全局代理也不行。使用其他方式访问youtube是没有问题的，之前使用zebra也是可以正常显示评论的。
无法正常登录twitter.com，点击登录后永远在加载，如果刷新页面，会同时处于已登录和未登录的状态，具体表现为登录状态显示为未登录，无法进行查看私信等登陆后的操作，但是private状态的好友的页面是可以看到的。切换全局也是一样。但是可以几乎正常的登录mobile.twitter.com。

诊断信息：
xxnet-version: 3.13.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:22 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 953
is-idle: 1
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by akiritoa** [comment]
ipv6没有问题，但经常连不上，ipv4你是怎么设置的？

**Comment by SeaHOH** [comment]
关于 GAE 代理的缺陷，请查看 wiki 说明，这并不是一种完备的代理方式。

**Comment by klc197** [comment]
为什么你的可以啊？我这边一直等待扫描ip呢
