### ISSUE TITLE
浏览器代理设置和CA 证书状态(下载)一直是Fail

### ISSUE THREAD

**Issue by 595840875** [XX-net/XX-Net#12741]
浏览器代理设置和CA 证书状态(下载)一直是Fail，其余一切正常，重启刷新都没用。

**Comment by Campanula26** [comment]
你有没有有效的IPV6的IP和IPV4的IP呀...

**Comment by freenet1900** [comment]
建议你试试这个：[SSR科学上网教程](https://github.com/xiaoming2028/kexueshangwang/wiki)

**Comment by 595840875** [comment]
> 你有没有有效的IPV6的IP和IPV4的IP呀...

一开始会有，然后过几分钟就会减到0了
