### ISSUE TITLE
等待扫描 IP，建议开启 IPv6

### ISSUE THREAD

**Issue by StephenAnboer** [XX-net/XX-Net#12758]
大家都是ip地址少，或者有效ip少，但是我打开一直显示总ip1，然后一直提示等待扫描 IP，建议开启 IPv6，也就是说没有开始扫描，不知道是为什么。

诊断信息如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:1 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by StephenAnboer** [comment]
<img width="442" alt="111" src="https://user-images.githubusercontent.com/23215828/64967990-03354580-d8d4-11e9-8482-68274f8fa649.png">

**Comment by qizuoda** [comment]
遇到了同样的问题，也不能用了

**Comment by chaoroujiayou** [comment]
虽然显示ipv6正常.在任务管理器输入netsh int teredo show state也显示正常， 但是ping -6 ipv6.test-ipv6.com的时候会发现有时候能ping通有时候不可以。这应该是teredo 不稳定的原因吧，我尝试了好多
teredo也是这样，不知道是因为teredo服务器的原因，还是墙的原因，有没有兄弟解答一下。

**Comment by StephenAnboer** [comment]
> 虽然显示ipv6正常.在任务管理器输入netsh int teredo show state也显示正常， 但是ping -6 ipv6.test-ipv6.com的时候会发现有时候能ping通有时候不可以。这应该是teredo 不稳定的原因吧，我尝试了好多
> teredo也是这样，不知道是因为teredo服务器的原因，还是墙的原因，有没有兄弟解答一下。

我的应该是没有问题的，ipv6的网站都可以用，ssr的ipv6服务器也没问题，不知道是为什么

**Comment by awdawd2012** [comment]
这个比较好用 https://ant.antss026.com/aff/4Dwe

**Comment by ajajbjbj123** [comment]
遇到了同样的问题，多重启几次后来用能用了，你是不是用了过期或者无效的APPID？
