### ISSUE TITLE
这个真支持http2么

### ISSUE THREAD

**Issue by kxmp** [XX-net/XX-Net#12754]
H2只是连接池2号 跟h2没半点关系是吧....
我看浏览器里面写的资源访问协议还是h1.1的...(我当然开的是h2页面)

但是我看到这地方提到http2 这又是咋回事
https://github.com/XX-net/XX-Net/issues/6665

2019-09-13 21:22:16
我打开网络嗅探
抓到了所有ssl握手
里面的确是alpn h2排第一
然后我有用curl拉取了下一个页面
```
...
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
...
> GET / HTTP/1.1
> Host: t.co

```
最后下面的get还是1.1
当然curl现在都是也h2优先的.

这是使用另一个代理
下面的Get是h2的
```
> GET / HTTP/2
> Host: t.co
> User-Agent: curl/7.65.1
```

**Comment by SeaHOH** [comment]
支持 HTTP/2 是指 XX-Net 连接 GAE IP，你的浏览器连接 XX-Net 仍然是 HTTP/1.*。

**Comment by kxmp** [comment]
为什么都能连接gae走h2
却自己不能传输h2数据呢... 

希望早日支持H2

**Comment by SeaHOH** [comment]
> 为什么都能连接gae走h2
> 却自己不能传输h2数据呢...

因为没必要

**Comment by kxmp** [comment]
传输不了h2的话 多路复用优势没法体现啊.
一个页面要是有一大堆缩略图的话 h2没连接数限制 那样速度很快.
h1 over h2的话 最后感觉速度还和h1一样了....
这个场景当然还得是h2的网站才行了.

**Comment by SeaHOH** [comment]
首先，如果你所有网站都使用 gae_proxy 代理，即使是 HTTP/2 速度也会变慢；
其次，只要你使用扩展来调度代理，那么直连的网站就不受 XX-Net 限制；
再者，只要 gae_proxy 代理的负载还在合理范围内，而浏览器本身是支持并发请求的，两者之间的传输时间又可以算是 0，用不用 HTTP/2 实际上的体验区别也就不大；
最后，想要使用 HTTP/2 就必须是 HTTPS 类型的代理，虽然浏览器可能已经支持了，但是大部分其它软件都还不支持它，所以不仅增加了实现上的麻烦，还会出现兼容性问题。

HTTP/2 的优势只体现在访问远程服务，你在本地使用代理根本没必要用 HTTP/2 连接。

**Comment by kxmp** [comment]
说是那么说啊 你自己刷个缩略图差别一下就出来了.
目前chrome限制高延时连接了所以你测不出来 h2会被继续限制连接数 要改参数才可以
firefox倒是可以

看来这h2只能等待其他高人出手了!!

**Comment by kxmp** [comment]
这是Http1.1代理的测试记录

HTTP/1.1 200 Connection established
Proxy-Agent: Privoxy/3.0.23

**HTTP/2 200**
date: Mon, 16 Sep 2019 03:18:25 GMT
content-type: text/html

**Comment by SeaHOH** [comment]
我已经强调了很多次，免费 GAE 应用有非常大的限制，GAE 代理是一种有缺陷的代理，是不完备的。
X-Tunnel 才是真正的有完整功能的代理，你可以试试。
