### ISSUE TITLE
凉了吗？50+的总IP，99999的延迟。。。

### ISSUE THREAD

**Issue by faywon** [XX-net/XX-Net#12753]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:58 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 10
ip-quality: 1263
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

各位大佬帮忙看看吧

**Comment by EQ1874** [comment]
也是，凉了。。。

**Comment by faywon** [comment]
50多个ip，有效的只有一个，延迟99999，凉了吗？

**Comment by jon945** [comment]
最近凉的有点彻底了，不管是GAEProxy还是xtunnel，不知道大神还有没有办法救回来……

**Comment by akiritoa** [comment]
中午回春返照了，现在又气息奄奄了

**Comment by Quantum2Bits** [comment]
xx-net 如果能支持域名绑定就复活了。以前的版本至此php的还能用在php的主机上。

**Comment by xugaohui** [comment]
绑定域名现在速度也不好了。
