### ISSUE TITLE
teredo隧道合格但gae_proxy一直显示IPv6失败

### ISSUE THREAD

**Issue by Grey111222** [XX-net/XX-Net#12751]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:1 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by akiritoa** [comment]
我前几天用不了，今天好了。不知道和重新设置路由器有没有关系，你今天可以运行xxnet试试

**Comment by SeaHOH** [comment]
这只是 XX-Net 尝试访问内置的 IPv6 主机失败，不能说明说明问题，即使显示成功也不一定能连接谷歌 IP。
