### ISSUE TITLE
把路由器恢复出厂设置之后能连一小会儿

### ISSUE THREAD

**Issue by akiritoa** [XX-net/XX-Net#12755]
最近一直用不了xxnet。看issues里面有说是运营商或路由器的问题，所以就试了试重启路由器和恢复出厂设置这两个操作。第一个操作没有导致任何变化发生，第二个操作会让电脑能用xxnet一段时间，但1小时内又无法连接了。
请问这种情况大概是什么原因导致的

**Comment by SeaHOH** [comment]
这个东西最好不要乱动，有些设置重置后不一定适合当前的连接使用方式，不懂的人按你这么操作了然后造成网络故障怎么办？
