### ISSUE TITLE
X-tunnel 无法设置 polipo http 代理

### ISSUE THREAD

**Issue by lkyhfx** [XX-net/XX-Net#12764]
下面是我的polipo配置文件
环境：
ubuntu 19.04
```
# This file only needs to list configuration variables that deviate
# from the default values.  See /usr/share/doc/polipo/examples/config.sample
# and "polipo -v" for variables you can tweak and further information.

logSyslog = true
logFile = /var/log/polipo/polipo.log

socksParentProxy="127.0.0.1:1080"
socksProxyType=socks5
```

**Comment by SeaHOH** [comment]
设置看起来是正确的，不明白无法设置是何意，请详细描述你的问题，并提供相关信息。

**Comment by lkyhfx** [comment]
按上面的设置设置polipo后，打开polipo，用SwitchOmega设置代理为 http locahost:8123后，打开网页错误，提示ERR_TUNNEL_CONNECTION_FAILED。使用SwitchOmega代理socks5://localhost:1080可以正常打开网页

**Comment by SeaHOH** [comment]
两者都有日志，难道你都不看的吗？请确认问题是发生在 XX-Net 再来提问。

**Comment by lkyhfx** [comment]
[polipo.log](https://github.com/XX-net/XX-Net/files/3624828/polipo.log)
这个polipo的日志，直接连接xxnet可以使用。我想问一下xxnet用的是socks5吗？还是其他协议？

**Comment by SeaHOH** [comment]
>Polipo is no longer maintained

建议换用其它类似工具。

> xxnet用的是socks5吗？还是其他协议？

同一个端口同时支持 HTTP、SOCKS4/5。

**Comment by lkyhfx** [comment]
`socksProxyType=socks5`修改成`socksProxyType=socks4a`后可解决
