### ISSUE TITLE
v2ray环境下 xxnet可以扫描到ip 切换到xxnet ip瞬间掉完。

### ISSUE THREAD

**Issue by diyici18sui** [XX-net/XX-Net#12768]
本机同时安装xxnet和v2ray 
另外安装了pcap_dnsproxy 已经把dns查询变成了udp
发现一个奇怪现象，在用v2ray的时候，xx-net不关，让其在后台扫描ip，过一段时间，IP能达到可用值，这是切换到xx-net 也能使用，如图
![image](https://user-images.githubusercontent.com/33658823/65219043-5a146800-daea-11e9-8d67-c130366dedc9.png)
但是切换到xx-net后 没几秒钟，马上ip掉光。似乎是本机到谷歌服务器之间有很强的干扰，判断到有流量就进行干扰。。。
本人小白，请大神分析下

**Comment by yeahwu** [comment]
你挂着代理扫IP，能扫几千个无用的IP，扫IP不要挂代理。

**Comment by SeaHOH** [comment]
他想表达的意思是，IP 能连接，但是只能连接很短的时间。
我觉得这是错觉。。。
