### ISSUE TITLE
跟国庆有关系吗？

### ISSUE THREAD

**Issue by 990753707** [XX-net/XX-Net#12763]
ip一直0到2之间徘徊。
是要国庆了，“严打”一下吗？

**Comment by nly4lov** [comment]
必须有啊。过了这段时间就会好的。

**Comment by Arronlong** [comment]
这段时间的确扫描不到ip，找了一个软件先凑合着用，速度还可以，免费，无需注册：https://ant.antss028.com/aff/4YfV

**Comment by qucanswo** [comment]
应该没有关系，除非有些人利用这个工具做一些不利于国家的事情。
