### ISSUE TITLE
【需求】如何在局域网内的另一台服务器上运行xx-net？

### ISSUE THREAD

**Issue by Ozgay** [XX-net/XX-Net#1277]
我把xx-net运行在局域网内一台小服务器上，遇到4个问题：
1，8087端口只在127.0.0.1上侦听。（已通过修改proxy.ini里的[listen] ip = 0.0.0.0 解决）
2，pac端口只在127.0.0.1上侦听。（已通过修改proxy.ini里的 [pac] ip = 0.0.0.0 解决）
3，配置页面无法访问，我推测也是只打开了127.0.0.1的8085端口，请问在哪里可以修改？
4，如果在putty中运行start.sh，退出putty之后进程就结束了，可否在start.sh中加入nohup？

**Comment by Ozgay** [comment]
“4，如果在putty中运行start.sh，退出putty之后进程就结束了，可否在start.sh中加入nohup？”
可以照着抄 goagent/local/proxy.sh

**Comment by xyuanmu** [comment]
3. 你试试改改 XX-Net\launcher\web_control.py  412-417行：
```python
    if allow_remote:
        host_addr = "0.0.0.0"
    else:
        host_addr = "127.0.0.1"
```
为
```
    host_addr = "0.0.0.0"
```

**Comment by Ozgay** [comment]
下面还有几个硬编码的127.0.0.1也要改吗？

**Comment by xyuanmu** [comment]
不用，改了以后监听8085端口的已经是0.0.0.0
![xx-net](https://cloud.githubusercontent.com/assets/12442896/10747403/aab84960-7c8f-11e5-911c-2dcd6e843c67.png)

**Comment by xyuanmu** [comment]
晕死，今天才知道，原来有设置的：http://127.0.0.1:8085/?module=launcher&menu=config
![xx-net](https://cloud.githubusercontent.com/assets/12442896/10899976/4c2b62ac-8215-11e5-97eb-610ef3ba2e00.png)

**Comment by a1exlism** [comment]
感谢分享，一直在找关于这个的方法

**Comment by Ozgay** [comment]
#!/bin/sh
#
# xx_net init script
#

### BEGIN INIT INFO
# Provides:          xx_net
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Monitor for xx_net activity
### END INIT INFO

# **NOTE** bash will exit immediately if any command exits with non-zero.
set -e

PACKAGE_NAME=xx_net
PACKAGE_DESC="xx_net proxy server"
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${PATH}

start() {
    echo -n "Starting ${PACKAGE_DESC}: "
    if hash python2 2>/dev/null; then
        nohup python2 launcher/start.py 2>&1 | /usr/bin/logger -t ${PACKAGE_NAME} &
    else
        nohup python launcher/start.py 2>&1 | /usr/bin/logger -t ${PACKAGE_NAME} &
    fi
    echo "${PACKAGE_NAME}."
}

stop() {
    echo -n "Stopping ${PACKAGE_DESC}: "
    
    if hash python2 2>/dev/null; then
	    kill -9 `ps aux | grep 'python2 launcher/start.py' | grep -v grep | awk '{print $2}'` || true
    else
        kill -9 `ps aux | grep 'python launcher/start.py' | grep -v grep | awk '{print $2}'` || true
    fi
    echo "${PACKAGE_NAME}."
}

restart() {
    stop
    sleep 1
    start
}

usage() {
    N=$(basename "$0")
    echo "Usage: [sudo] $N {start|stop|restart}" >&2
    exit 1
}

if [ "$(id -u)" != "0" ]; then
    echo "please use sudo to run ${PACKAGE_NAME}"
    exit 0
fi

# `readlink -f` won't work on Mac, this hack should work on all systems.
cd $(python -c "import os; print os.path.dirname(os.path.realpath('$0'))")

case "$1" in
    # If no arg is given, start the goagent.
    # If arg `start` is given, also start goagent.
    '' | start)
        start
        ;;
    stop)
        stop
        ;;
    #reload)
    restart | force-reload)
        restart
        ;;
    *)
        usage
        ;;
esac

exit 0


#根据goagent的脚本改成的，xx-net后台启动脚本，放在start.sh同一个目录下运行。
