### ISSUE TITLE
回来看看，顺便分享goproxy-php代理方法和goproxy绑定域名走gae代理教程

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#12778]
最近被xx-net的602折腾得头大，于是试了试goproxy，打开goproxy，看到终端上那跳动的一串串白字，简直，热泪盈眶！
一段时间没上来，goproxy没了，gogotunnel没了，goagent没了，lantern也快废了，都不知道该说啥了。好了，下面是教程：
https://www.yeahwu.com/posts/b30843c5.html

**Comment by Quantum2Bits** [comment]
请问有那些网站可以部署php服务器？

**Comment by nly4lov** [comment]
去看了一下，好麻烦，还是等xx过了国庆看看再说

**Comment by yeahwu** [comment]
@2378 在http代理，基本全线阵亡的情况下，heroku给免费用就不错了，只要不滥用，一般不会封号的。至少俺两年前部署的app还在。

**Comment by hubsocks** [comment]
goproxy 绑定免费域名比你这个方法要解法的多.

**Comment by yeahwu** [comment]
@hubsocks 好吧，明天就把绑定域名教程补上！

**Comment by StephenAnboer** [comment]
这个可以只走ipv6吗

**Comment by yeahwu** [comment]
更新goproxy绑定域名，走gae代理的方法，仍然是上面的链接。速度还不错。
@StephenAnboer 理论上走gae代理可以走ipv6，因为绑定域名后有AAAA解析记录。

**Comment by hubsocks** [comment]
@yeahwu AAAA解析到google ipv6,由于墙的原因.实际还是远不如ipv4稳定,同网络环境下,绑定域名还是比xx-net走ipv4慢了一倍.早期绑定域名时速度十分快.教程一公开,速度马上不行了.

**Comment by yeahwu** [comment]
@hubsocks GAE ​IPv4差不多死翘翘了，本来这种http代理就是苟延残喘状态，像这种php和绑定域名方法都是离奇的复杂，一般人还真玩不转，且用且珍惜吧！

**Comment by SeaHOH** [comment]
其实 IPv4 还是能扫出 IP 的，只是可能各地区能联通的 IP 不太一样，前几天扫了下，我这里能连接的大概有 150 左右。

**Comment by SeaHOH** [comment]
一般也用不着，大部分网站直连就成。
至于死的快，还没看出来，联通率主要还是看时间段，每天固定几个时间段丢包会严重些，IPv4 和 IPv6 都这样。

**Comment by loveinlastnight** [comment]
测试了下，白天还可以。晚上容易卡顿。不知道heroku能够挺得住不。
不知道heroku好久会被墙了呢。

**Comment by hubsocks** [comment]
google的gae ip4并不是固定不变,经常有删除或新增的.前几天测试共发现有662个证书的cn值为*.appspot-preview.com的,ip有较大的变化.只要知道google ipv4的ip地址最后一节数值的规律,很容易得出全部书证是*.appspot-preview.com的服务端.把这些单个ip提交到IP 段列表.扫描线程4个就十分稳定好用了.

**Comment by SeaHOH** [comment]
就九个数字嘛，不过你这种方法很费事，还要自己重写 IP 列表，限制扫描程序比较简单，不用改列表。

**Comment by yeahwu** [comment]
@loveinlastnight heroku因为Amazon Cloud的原因，处于半墙状态，有些IP被墙。
@hubsocks google的v4 IP，就像女人的奶子，挤挤总是有的，只是越来越难挤了。

**Comment by jap33** [comment]
应用的某个版本正在使用已弃用的 Go 版本。请在 2019 年 10 月 1 日之前升级。了解详情 。
朋友们这个怎么办？

**Comment by yeahwu** [comment]
@jap33 你这没头没尾的，看不懂！

**Comment by yeahwu** [comment]
遗憾，heroku已不支持Dropbox同步了，话说当年俺的app就是Dropbox同步上去的。
https://devcenter.heroku.com/changelog-items/1451

**Comment by jap33** [comment]
两年前部署的appGo 版本太底已弃用。请在 2019 年 10 月 1 日之前升级。将 App Engine 应用迁移至 Go 1.12 。怎么更新。

**Comment by yeahwu** [comment]
@jap33 我也是两年前在heroku用dropbox部署的，怎么没这种提示？是不是你该重新部署一下！

**Comment by 10362227** [comment]
弄了下域名设置，不能翻墙。访问域名显示
“{
	"server": "goproxy 1.0"
	"latest": "",
	"deploy": "2019-09-26T15:24:38Z",
	"message": "unable check goproxy latest version, please try after 5 minutes."
}”

**Comment by yeahwu** [comment]
@10362227 其实这个域名绑定还是有一个弊端的，就是你要找到有效的ghs ip，也就是域名的A记录里要填能ping得通的ghs ip，建议还是用heroku吧！

**Comment by Quantum2Bits** [comment]
请问这些有效的 ghs ip 就是xx-net所要扫的ip吗？

**Comment by yeahwu** [comment]
@Quantum2Bits 现在这个办法行不通了，Google只能映射固定IP，更改不了ghs IP，不同与xx用的IP

**Comment by StephenAnboer** [comment]
尝试了一下，貌似不行
 MULTIDIALER: LookupAlias("google_hk") have no good ips

**Comment by loveinlastnight** [comment]
的确，绑定域名已经不能用了。

**Comment by hubsocks** [comment]
绑定域名的方法完全没有问题.只是楼主关于 gae.user.json里面"SiteToAlias": 和	"ForceGAE": 这里修改没有说清楚.翻看以前的问题.
xx-net用ipv4 在三家运营商环境下都有近百个可用ip.

**Comment by yeahwu** [comment]
@hubsocks 你说的是SiteToAlias留空和ForceGAE填上域名是吧？没用的，现在的问题是，
```

216.239.32.21
216.239.34.21
216.239.36.21
216.239.38.21
```
上面这些ghs ip都被封死了，包括ipv6 ip也是封的死死的。有效的ghs ip，google又不能映射上去，比如下面有效的ghs ip
```
74.125.24.121
74.125.31.121
74.125.128.121
74.125.129.121
74.125.130.121
```
这才是主要问题

**Comment by SeaHOH** [comment]
各地状况不尽相同，有些还是能用的。
还有个办法就是再加个 CDN。

**Comment by loveinlastnight** [comment]
![image](https://user-images.githubusercontent.com/50778952/65852665-640b5600-e389-11e9-8da5-206378d93d73.png)

**Comment by loveinlastnight** [comment]
来自 2001:4860:4802:32::15 的回复: 时间=303ms
来自 2001:4860:4802:32::15 的回复: 时间=304ms
来自 2001:4860:4802:32::15 的回复: 时间=303ms
来自 2001:4860:4802:32::15 的回复: 时间=303ms

通的，也不行。

GoProxy Version    : r1632 (go/b17470d windows/amd64)
GoProxy Profile    : Default
Listen Address     : 127.0.0.1:8087
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://127.0.0.1:8087/proxy.pac50
2019/09/30 16:42:26 Start loading IP Range file:./iprange.conf
2019/09/30 16:42:26 Start scanning available IP
2019/09/30 16:42:52 Scanned 1000 IPs, Found 0 records
2019/09/30 16:43:17 Scanned 2000 IPs, Found 0 records
2019/09/30 16:43:42 Scanned 3000 IPs, Found 0 records

**Comment by hubsocks** [comment]
@loveinlastnight 用r1651的版本.找完整的教程.ipv4移动光纤没问题

**Comment by jap33** [comment]
r1651的版本在那？这两天用xx部署了11个app，还有14个怎么也部署不了。

**Comment by jap33** [comment]
> 
> 
> r1651的版本在那？这两天用xx部署了11个app，还有14个怎么也部署不了。话说扫了两天只有一个ip也没法用了。

**Comment by addsun** [comment]
gop用了好几年了，绑上域名，找ip，妥妥的。heroku方案慢，不如部署v2ray。

**Comment by yeahwu** [comment]
俺这边加上CDN都找不到IP，倒是heroku上前年部署的app到现在都跑得稳稳的。

**Comment by loveinlastnight** [comment]
@hubsocks 你把1651版本链接发下啊，还有那个完整教程。

**Comment by loveinlastnight** [comment]
![image](https://user-images.githubusercontent.com/50778952/65910116-a15cfb80-e3fc-11e9-99b8-bfc19c1e01c6.png)

绑米问题终解决，原因是 r1632，改换r1623OK。

**Comment by litongjava** [comment]
我感觉和厉害,但是我看不太懂,作者能不能写一遍详细的文档讲解一下

**Comment by lxf1009** [comment]
我用你的教程绑域名可以用，youtube看HD挺快，但是上instagram的时候主页加载很快，点击进入别人主页的时候就特别慢，要一两分钟，这是什么原因？

**Comment by yeahwu** [comment]
@lxf1009 目测应该是gae本身的问题，这种http代理本身有许多缺陷。所以将就用吧！

**Comment by lxf1009** [comment]
@yeahwu 频繁出现这种错误代码
W1013 08:32:03.446450    1648 gaetransport.go:126] GAE *http.Transport.RoundTrip
("https://clients3.google.com/generate_204") error: context deadline exceeded

**Comment by ysjlion** [comment]
@yeahwu 好像部署不了了，按紫色按钮跳转heroku后提示：No app.json located in the repo URL provided. Make sure that an app.json file exists in the project root directory。这个什么情况，不支持go了？
