### ISSUE TITLE
敢问大神还有哪些teredo服务器，以下的我这边能用的在一个星期前都不稳定了

### ISSUE THREAD

**Issue by 308901951** [XX-net/XX-Net#12773]
teredo.remlab.net

teredo2.remlab.net

teredo-debian.remlab.net

teredo.trex.fi

teredo.iks-jena.de

win10.ipv6.microsoft.com

win1710.ipv6.microsoft.com

win1711.ipv6.microsoft.com

win1807.ipv6.microsoft.com

teredo.managemydedi.com 

teredo.ngix.ne.kr 

teredo.autotrans.consulintel.com 

teredo.ginzado.ne.jp

**Comment by hubsocks** [comment]
多翻旧 Issues 就知道答案了.就算你出巨资自建teredo服务器都没丝毫作用.原因是ipv6从技术原理上决定了它很容易被公性步检测.连ipv6是没问题.但连google的ipv6,你想多了.连通3秒断你5秒.

**Comment by awdawd2012** [comment]
暂时用这个吧https://ant.antss028.com/aff/6hyt，现在还能出国

**Comment by 308901951** [comment]
今天基本正常了，还是老服务器

**Comment by whogiawho** [comment]
很难找到新的，这些算很全的了
