### ISSUE TITLE
第一步以管理员身份运行 start.bat 提示 找不到 python27.dll

### ISSUE THREAD

**Issue by ABSmiLT** [XX-net/XX-Net#12777]
环境： Windows 10
xx-net： 2019.09.21 从 GitHub 直接下载，应该是 3.13.3

错误：

---------------------------
python.exe - 系统错误
---------------------------
由于找不到 python27.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
---------------------------
确定   
---------------------------

进入子目录 code/default/python27/1.0/ 是有 python27.dll 的。
虽然系统没有安装 python27，但是目录自带了 python27.dll 应该可以识别到啊？

**Comment by ABSmiLT** [comment]
将 python27.dll 复制到 xxnet 一级目录下 以及 system32 目录下，错误提示不变，实在是太奇怪了。。

**Comment by nly4lov** [comment]
把它拷进\XX-Net\code\default\python27\1.0这个路径下就应该好了

**Comment by SeaHOH** [comment]
请确定不是系统问题后重新下载。

**Comment by ABSmiLT** [comment]
> 把它拷进\XX-Net\code\default\python27\1.0这个路径下就应该好了

多谢，不过这个默认路径里面本来就是有 python27.dll 文件的（见我问题描述）

**Comment by ABSmiLT** [comment]
> 请确定不是系统问题后重新下载。

你好，重新下载之后问题依旧，不知道这个会有哪些可能的系统问题？
Windows10 系统，相对比较干净，个人感觉系统问题可能性也不大。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/5463#issuecomment-312131225
你是不是这样运行的？

**Comment by ABSmiLT** [comment]
![image](https://user-images.githubusercontent.com/8147261/65433830-56694400-de50-11e9-8cfd-519b1491fb56.png)
在仔细看了 #5463 后，重新尝试：
1. 删除之前的解压缩出来的文件夹；
2. 用 7-zip 解压缩到 system32 下自定义文件夹；
3. 右键 以管理员身份运行 start.bat，仍然出现问题所述错误；
4. 在路径下按住 shift 右键，启动 powershell，运行 start.bat，结果如上图；
5. 以管理员身份运行 powershell，定位路径到 xxnet 目录下，再运行 start.bat，结果依旧。
PS. OS环境： Windows 专业版 1803

**Comment by ABSmiLT** [comment]
@SeaHOH

**Comment by ABSmiLT** [comment]
我突然意识到，可能和 system32 路径有关，重新解压到非系统盘某路径，可以执行通过这第一步。
不过这个问题以前是没有的，我前几年 xxnet 一直都是放这个文件目录下，甚至应该在 Windows 10 环境下也这样部署过。
FYI @SeaHOH

**Comment by miketwes** [comment]
看看是不是python27.dll版本的问题

**Comment by ABSmiLT** [comment]
@miketwes 多谢啦，见我上一条 comment，问题已解决。
