### ISSUE TITLE
刚买了xtunnel季套餐，但是可用流量仍然显示只有460M，这是为什么呢？

### ISSUE THREAD

**Issue by cititude** [XX-net/XX-Net#12776]
如题

**Comment by CharliesZhang** [comment]
最近也想买的，你这个问题解决了么，

**Comment by cititude** [comment]
> 最近也想买的，你这个问题解决了么，

没有。。。已经发了邮件了还没收到回复。。。

**Comment by jon945** [comment]
你的xtunnel通道还能用吗？我这边ipv6扫不出来，xtunnel也跟着阵亡

**Comment by cititude** [comment]
还能用

---原始邮件---
发件人: "jon945"<notifications@github.com&gt;
发送时间: 2019年9月21日(星期六) 中午11:53
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com&gt;;
抄送: "cititude"<3223781449@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [XX-net/XX-Net] 刚买了xtunnel季套餐，但是可用流量仍然显示只有460M，这是为什么呢？ (#12776)



你的xtunnel通道还能用吗？我这边ipv6扫不出来，xtunnel也跟着阵亡

**Comment by CharliesZhang** [comment]
> > 最近也想买的，你这个问题解决了么，
> 
> 没有。。。已经发了邮件了还没收到回复。。。

如果你的可以了，能在这里说一下吗，最近找了不少vpn都不是很理想

**Comment by cititude** [comment]
> > > 最近也想买的，你这个问题解决了么，
> > 
> > 
> > 没有。。。已经发了邮件了还没收到回复。。。
> 
> 如果你的可以了，能在这里说一下吗，最近找了不少vpn都不是很理想

现在不能用了。。。

**Comment by CharliesZhang** [comment]
> > > > 最近也想买的，你这个问题解决了么，
> > > 
> > > 
> > > 没有。。。已经发了邮件了还没收到回复。。。
> > 
> > 
> > 如果你的可以了，能在这里说一下吗，最近找了不少vpn都不是很理想
> 
> 现在不能用了。。。

好吧 ，真是fuck
