### ISSUE TITLE
连不上两个礼拜了，真的很难受

### ISSUE THREAD

**Issue by meidong007** [XX-net/XX-Net#12774]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by meidong007** [comment]
之前联通不行，移动行，现在移动也不行了

**Comment by burdenlee** [comment]
等101这几天过去了就好了。。

**Comment by yeahwu** [comment]
翻墙要抱着佛系心态，俺都半年没爬过去了！:smeil:

**Comment by awdawd2012** [comment]
暂时用这个吧 https://ant.antss028.com/aff/6hyt
现在还能出国，比其他的要稳定些

**Comment by LoveFForever** [comment]
> 
> 
> 暂时用这个吧 https://ant.antss028.com/aff/6hyt
> 现在还能出国，比其他的要稳定些

呦嗨 还带小尾巴 呵呵呵呵呵

**Comment by nly4lov** [comment]
> 暂时用这个吧 https://ant.antss028.com/aff/6hyt
> 现在还能出国，比其他的要稳定些

@yeahwu 有人发广告

**Comment by ablebodied** [comment]
最近突然ipv4地址有几十个可以用了，ipv6为0

**Comment by hubsocks** [comment]
![快照1](https://user-images.githubusercontent.com/46856823/65399957-196e6480-ddf2-11e9-84fa-6bd1440c2268.png)
没见ipv4增多,反而比昨天少了20个,看来最近墙又加高了.

**Comment by yeahwu** [comment]
实在不行，借heroku来玩玩php模式，十一这么热闹，总得出来转转嘛。

**Comment by whogiawho** [comment]
ipv4玩完了都现在
