### ISSUE TITLE
Using GAEProxy to surf the Internet, everything is ok, but still can't get online, ask why, thank you

### ISSUE THREAD

**Issue by yyysjz1997** [XX-net/XX-Net#12789]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by X-Amoi** [comment]
can't connect the service host

**Comment by valasco** [comment]
> can't connect the service host

is there anyway to find the host and edit it to help xx-net connect the server？
