### ISSUE TITLE
求助XX显示一切正常却上不了网

### ISSUE THREAD

**Issue by Ps-Algia** [XX-net/XX-Net#12783]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by miketwes** [comment]
可以参考一下这个配置和Ip数据:

ip data(in floder data/):

https://github.com/miketwes/XX-Net-Linux/tree/master/GotoX/data

config/Config.ini:

https://github.com/miketwes/XX-Net-Linux/blob/master/GotoX/Config.ini

**Comment by Ps-Algia** [comment]
> 可以参考一下这个配置和叶数据：
> 
> ip数据（在floder数据中/）：
> 
> https://github.com/miketwes/XX-Net-Linux/tree/master/GotoX/data
> 
> 配置/的Config.ini：
> 
> https://github.com/miketwes/XX-Net-Linux/blob/master/GotoX/Config.ini

看不懂。。。。。

**Comment by daxinnan** [comment]
> 可以参考一下这个配置和Ip数据:
> 
> ip data(in floder data/):
> 
> https://github.com/miketwes/XX-Net-Linux/tree/master/GotoX/data
> 
> config/Config.ini:
> 
> https://github.com/miketwes/XX-Net-Linux/blob/master/GotoX/Config.ini

可以教教么

**Comment by miketwes** [comment]
> > 可以参考一下这个配置和Ip数据:
> > ip data(in floder data/):
> > https://github.com/miketwes/XX-Net-Linux/tree/master/GotoX/data
> > config/Config.ini:
> > https://github.com/miketwes/XX-Net-Linux/blob/master/GotoX/Config.ini
> 
> 可以教教么

1 . 下 载
https://github.com/SeaHOH/GotoX

2. 用https://github.com/miketwes/XX-Net-Linux/tree/master/GotoX/data文件夹替换GotoX/data文件夹

3.用https://github.com/miketwes/XX-Net-Linux/blob/master/GotoX/Config.ini文件替换GotoX/config/Config.ini文件, 用XX-net的公用appid替换其中的yourappid

4. 开启ipv6, cd GotoX && python3 start.py, 正常上网后再上传服务端,https://github.com/SeaHOH/GotoX/tree/gaeserver.goproxy, 之后改用自己的appid

**Comment by SeaHOH** [comment]
@miketwes 请删掉，我不想面对太多非目标用户。谢谢。

**Comment by miketwes** [comment]
> @miketwes 请删掉，我不想面对太多非目标用户。谢谢。

Has deleted.

**Comment by akiritoa** [comment]
> > @miketwes 请删掉，我不想面对太多非目标用户。谢谢。
> 
> Has deleted.

想问下这个“非目标用户”是什么意思？
