### ISSUE TITLE
求助，关闭xx-net之后整个上不了网

### ISSUE THREAD

**Issue by KDL-in** [XX-net/XX-Net#12781]
我现在不知道该咋办
校园网，关闭之后就直接连不了网
为啥不给个卸载呢。。。

我之前用过xx-net，觉得不稳定，后来换了个。最近过节，上不了，所以回来用，怎么就不行了呢

**Comment by yeahwu** [comment]
你这个应该是勾选了全局代理导致的，internet选项/连接/局域网设置/把里面的小勾勾全部去掉！

**Comment by Lxj1025979917** [comment]
取消全局代理

**Comment by KDL-in** [comment]
原因找到了，是chrome里插件的问题，插件有bug，想卸载的时候记得把插件里的代理设置关了再卸载
