### ISSUE TITLE
DDNS IPV6一直很稳 就是延迟一直在370左右

### ISSUE THREAD

**Issue by shenyiwd** [XX-net/XX-Net#12780]
可是好像从几个月之前开始pornhub视频就放不了了…
你们有这个问题吗

**Comment by zmy0730** [comment]
老哥也看PH啊  嘿嘿  
我试过很多办法，重装FLASH播放器，重装CHROME，都无法播放。。不仅是PH播放不了，同样的几个网站都是一直在缓冲，播放不了，换了其他工具可看，认为是XXnet本身不停找IP换IP的方法导致的。。。
纯小白，还请大佬答疑

**Comment by 2378** [comment]
还有心思看Phub :eyes: ，万一到时候物理断网，等着过三胖国的日子吧

**Comment by valasco** [comment]
难道现在用这个还能翻出去？我这边偶尔能翻下，坚持不过5min必断！

**Comment by Quantum2Bits** [comment]
DDNS IPV6 怎么用啊？ 大神科普一下把。

**Comment by ablebodied** [comment]
能发一下教程么

**Comment by hubsocks** [comment]
@shenyiwd 350延迟已经是超级好了,油管致少也有2万的速度了.
这里延迟8百多.油管才7千多的速度.
![快照1](https://user-images.githubusercontent.com/46856823/65586483-d4475f80-dfb6-11e9-9d1c-820034b5fc32.png)

**Comment by yeahwu** [comment]
哎，想当年延迟大于50ms的IP，直接扫进垃圾堆。超过200ms基本就没法用了。现如今都这延迟了，还高兴成这样。墙真的能改变一个人的需求！记得当年有一款扫IP软件叫“fuck 方滨兴”，扫IP贼好用。
