### ISSUE TITLE
公共appid

### ISSUE THREAD

**Issue by daxinnan** [XX-net/XX-Net#12788]
请问XX-net的公共appid是什么，是指之前自己捐赠的那些吗，还是有哪些appid专门当做公共功能使用？

**Comment by miketwes** [comment]
public appid:

https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/appids.txt

在用自己的appid部署服务端之前, XX-Net使用public appid, 建议使用public appid的时候多填几个, 个别public appid可能已实效
