### ISSUE TITLE
goproxy/zebra用户怎么转到xx-net来现在?

### ISSUE THREAD

**Issue by masktao** [XX-net/XX-Net#12798]
9月20号zebra无法使用,有效Ip为0.如今发现quic模式无法实用,tls模式只能只用tls1.2版本.1.3也无法使用.去app engine页面发现提示如下:
应用的某个版本正在使用已弃用的 Go 版本。请在 2019 年 10 月 1 日之前升级
感觉是服务端太老,没有维护,没法升级导致
如果goproxy/zebra服务端无法升级更新?现在怎么转到xx-net来?
尝试在config添加id和password,导致xx-net无法实用,是否要重新部署xx-net服务端?

**Comment by Eri5Ch** [comment]
不必费劲了 xx也不能用了。。。

**Comment by masktao** [comment]
@Eri5Ch xx可以用,默认什么不用改,就可以直接用,默认用ipv6就可以连上,只是速度不理想

**Comment by FergonXie** [comment]
现在xxnet可以用了。从近期的表现来看， 什么翻墙技术都是扯淡，一切都在我党的控制之下。

**Comment by jap33** [comment]
可是可以用了就一个ip。

**Comment by masktao** [comment]
@FergonXie xx因为一直在维护,更新升级,所以使用效果对网站兼容性稳如狗, 用goproxy/zebra主要可以用自己的appid
国庆节用xx一点问题都没有

**Comment by valasco** [comment]
> @FergonXie xx因为一直在维护,更新升级,所以使用效果对网站兼容性稳如狗, 用goproxy/zebra主要可以用自己的appid
> 国庆节用xx一点问题都没有

嗯，果然一直在维护...
