### ISSUE TITLE
如何强制avast走跳墙路线？

### ISSUE THREAD

**Issue by nsdcsj** [XX-net/XX-Net#128]
一直用的avast被墙 升级病毒库可以在其程序里设置代理走xx （跟浏览器通过switchsharp类似） 但是注册账户及其它动作就不能通过其内部代理来改动了 怎么能让它全走xx （换个问题 就是怎么让某个程序的上网路线全走xx）

**Comment by lele2010lele** [comment]
全局代理或者去程序里设置代理服务器地址啊
