### ISSUE TITLE
3.13.3 "仅 IPv6" 不可用，请检查。

### ISSUE THREAD

**Issue by zg112414** [XX-net/XX-Net#12808]
以前一直使用3.11，不能用了就更新到3.13.3，一直不能正常使用。
一直显示 "仅 IPv6" 不可用，请检查。

IP6隧道 显示 

Teredo 隧道 | 合格（已连接） (仍然连接不上？等一会儿，或者尝试降低连接缓冲数值)
-- | --

诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:99 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

请老师们看看，有没有拯救的方法。
谢谢，祝各位老师万事如意！

**Comment by SeaHOH** [comment]
设置，仅 IPv6 改成自动。

**Comment by zg112414** [comment]
> 设置，仅 IPv6 改成自动。

试过了没用。

**Comment by zg112414** [comment]
通过手动切换Teredo隧道解决了。用这个文件可以手动切换：#配置IPv6.bat

**Comment by my3188** [comment]
> 哪个文件，能分享一下吗？
