### ISSUE TITLE
又发现了个诡异的问题~

### ISSUE THREAD

**Issue by diyici18sui** [XX-net/XX-Net#12806]
最新版3.13.3
teredo服务器一直是83.170.6.76
目前浏览器用switchyomega，xx-net设置的是取消全局
前一阵一直不可用
控制台显示ipv6不可用
偶然间xx-net设置成了全局通过Gae代理，有了少量ip可用（2-6），可以正常谷歌油管
![image](https://user-images.githubusercontent.com/33658823/66814701-a5932800-ef69-11e9-9176-017c36384de1.png)

切换回取消全局，ip瞬间掉光。。。
这什么情况？
![image](https://user-images.githubusercontent.com/33658823/66815121-4d105a80-ef6a-11e9-8713-3cd87d6b5cd3.png)

**Comment by super-lixuequan** [comment]
早都有问题了,哎 现在无法使用了

**Comment by hugetiny** [comment]
应该不是切换问题，就是因为不稳定

**Comment by awdawd2012** [comment]
现在好像没法用了

**Comment by SeaHOH** [comment]
hugetiny 说得对，都是错觉。
