### ISSUE TITLE
无法配置 appid

### ISSUE THREAD

**Issue by jiucenglou** [XX-net/XX-Net#12815]
* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？ 是

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？ 是

* 是否以相关关键词搜索过类似 issues？ 是

在朋友的电脑上:
        可以访问 myid.appspot.com, 可以返回 GoAgent... 信息

在自己的电脑上, 打开 XX-Net 之后:
        可以打开 Google, Facebook, Google Cloud Platform (console.cloud.google.com)
        无法访问 myid.appspot.com...
        使用 WebUI 输入后, 提示 "无效的AppID：myid，使用前请先部署。"

GAE 诊断信息附在最后, 请问应该怎么做, 才能配置 appid ? 比如, 能否跳过检测 myid.appspot.com 呢 ?

PS: 不知道如何通过写 config.json 文件配置, 下面的 config.json 直接导致 XX-Net 异常
```
{
  "GAE_APPIDS" : ["myid"]
}
```

```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:454 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
```

**Comment by SeaHOH** [comment]
> 使用 WebUI 输入后, 提示 "无效的AppID：myid，使用前请先部署。"

提示很到位啊，你是怎么理解的？如果实在理解不能，可以留空，wiki 也写了，留空自动使用公共 ID。

**Comment by jiucenglou** [comment]
部署的方式: 

并不是使用的 XX-Net 的 WebUI, 而是等待 XX-Net 利用公共 AppID 得以打开 Google 后, 在 Google Cloud Platform (console.cloud.google.com) 里面运行网页 Console, wget 下载 master.zip 并解压, 修改 uploader.py 去掉设置 proxy 那一行, 然后运行命令行部署的.

因为在朋友的电脑上可以访问 myid.appspot.com, 可以返回 GoAgent... 信息, 所以猜测是部署成功了.

很奇怪, 自己的电脑上 XX-Net 利用公共 AppID 得以打开 Google, 却打不开了 myid.appspot.com ? 请问这种 "部分成功" 是否有解决的办法 ? o_O

**Comment by SeaHOH** [comment]
访问 gcloud 查看

**Comment by jiucenglou** [comment]
> > 使用 WebUI 输入后, 提示 "无效的AppID：myid，使用前请先部署。"
> 
> 提示很到位啊，你是怎么理解的？如果实在理解不能，可以留空，wiki 也写了，留空自动使用公共 ID。

因为在朋友的电脑上可以访问 myid.appspot.com, 可以返回 GoAgent... 信息, 所以猜测是部署成功了, 应该可以配置才对 ?

很奇怪, 自己的电脑上 XX-Net 利用公共 AppID 得以打开 Google, 却打不开了 myid.appspot.com ? 请问这种 "部分成功" 是否有类似的经历 或 解决的办法 ? o_O

**Comment by jiucenglou** [comment]
> 访问 gcloud 查看

在日志查看器中, 分别查看了 GAE 引用, GCS 存储分区, Google 项目, 感觉都是部署时留下的痕迹, 并没有发现与配置或访问 appspot 有关的信息, 请问还可以去哪里查看日志, 或解决这个问题 ?

**Comment by jiucenglou** [comment]
> 访问 gcloud 查看

抱歉, 上面说的不准确: 在日志查看器中查看 GAE 应用 这一项时, 根据时间, 能发现在朋友的电脑上访问 myid.appspot.com 的日志, 但是在自己的电脑上试图访问 myid.appspot.com 没有任何条目.

请问, 这是说明 XX-Net 利用公共 AppID 得以打开 Google, 却打不开 myid.appspot.com 么 ? 
请问 XX-Net 访问 myid.appspot.com 是为了验证部署是否成功, 还是必须需要与这个地址通讯 ?

**Comment by jiucenglou** [comment]
:D myid 配置成功了 !
但是, myid.appspot.com 还是不能访问
而且没有及时注意到在配置成功的瞬间, 是否 myid.appspot.com 是否能访问...

**Comment by jiucenglou** [comment]
此外, 通过对比 XX-Net 配置成功后的文件内容, 遇到的手动编辑 config.json 不被识别的问题也知道原因了: 手动编辑时, 用了 UTF8 BOM. :D

**Comment by SeaHOH** [comment]
> 请问 XX-Net 访问 myid.appspot.com 是为了验证部署是否成功, 还是必须需要与这个地址通讯 ?

两者都要，公共 ID 也是如此。
不过从你的描述看起来它们表现并不一致，试试填入公共 ID 是什么反应，ID 保存在
gae_proxy\local\appids.txt，或者你可以反过来，把它的内容替换成你的 ID。

如果你不执着于自己的 ID，用公共的就好。

**Comment by jiucenglou** [comment]
> > 请问 XX-Net 访问 myid.appspot.com 是为了验证部署是否成功, 还是必须需要与这个地址通讯 ?
> 
> 两者都要，公共 ID 也是如此。
> 不过从你的描述看起来它们表现并不一致，试试填入公共 ID 是什么反应，ID 保存在
> gae_proxy\local\appids.txt，或者你可以反过来，把它的内容替换成你的 ID。
> 
> 如果你不执着于自己的 ID，用公共的就好。

谢谢您的看法 !

忽然意识到: 

如果一定要访问 appspot 才能使用被部署的 GAE, 那么, 我在打开 XX-Net 后之所以能够上 Google, 很有可能不是由于成功联系到 公共 GAE... 

不确定的原因是: 我从某个 issue 里面看到可以把 https://github.com/miketwes/XX-Net-Linux/blob/master/data/good_ip.txt 下载到 data\gae_proxy, 能上网也有可能是它的原因是么 ? :D

**Comment by jiucenglou** [comment]
根据 诊断信息, ipv6 有效地址 = 1, 看来 应该并没有 成功利用 GAE (公共或私有)...  :D

```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:454 ipv4:0 ipv6:1
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by SeaHOH** [comment]
#12759

**Comment by jiucenglou** [comment]
> #12759

请问 "扫描模式里的IPV6改为自动" 具体是什么选项 ? 我没能找到完全一致的文字
例如, 是 XX-Net WebUI 导航窗格 下的 Smart Router -> 配置 -> 自动尝试直连时优先使用 ipv6 么 ?

**Comment by jiucenglou** [comment]
> #12759

抱歉, 找到了, 是 XX-Net WebUI 导航窗格 下的 GAEProxy -> 高级 -> 扫描设置 -> ip模式
, 现在已经是 仅 IPV6 了 :D

**Comment by jiucenglou** [comment]
> #12759

抱歉, 误会了, 现在我把它改为 自动, 重启后 试试.... 谢谢时间和帮助 !

**Comment by jiucenglou** [comment]
> #12759

切换为 自动后, 1 段时间内不能上 Google. 1 小时后可以上 Google了, 但是状况与 仅扫描 IPV6 时一样, 仅有 1 个 IPV6 地址
