### ISSUE TITLE
XX-Net 3.13.3`扫描不到ipv4.请朋友们解惑，谢谢

### ISSUE THREAD

**Issue by freesiimo** [XX-net/XX-Net#12822]
v6模式无法使用，用XX-Net 3.13.3 扫描ipv4,扫描模式为仅ipv4
扫描30多个小时未见可用ip,
        # ip_manager
        self.set_var("max_scan_ip_thread_num", 100)用的默认线程扫描
修改到100.无作用。谢谢各位朋友的解答，谢谢！

**Comment by dovisutu** [comment]
我估摸着ipv4早就不可以用了？好像

**Comment by ablebodied** [comment]
国庆后，我这里现在只有v4的地址，没有v6的地址；之前v4几乎不能用，用的v6；很奇怪

**Comment by dovisutu** [comment]
emm...反正我这里v6可以慢慢涨起来，v4铁定没有
xx显示v6不可用不一定是不可用，我这边正常配置有时候会有不可用的提示，但是还是正常使用（除了延迟1062以外）

**Comment by valasco** [comment]
这软件这样子还是希望快点完蛋的好~彻底完了，也就不用还心心恋恋的回头来看一下！估计我这个回帖之后会被标上closed！

**Comment by nly4lov** [comment]
> 这软件这样子还是希望快点完蛋的好~彻底完了，也就不用还心心恋恋的回头来看一下！估计我这个回帖之后会被标上closed！

你这些话不说也行，自己悄咪咪的消失就好了。

**Comment by valasco** [comment]
那我要不消失呢？难不成你准备下口了？

**Comment by valasco** [comment]
> > 这软件这样子还是希望快点完蛋的好~彻底完了，也就不用还心心恋恋的回头来看一下！估计我这个回帖之后会被标上closed！
> 
> 你这些话不说也行，自己悄咪咪的消失就好了。

那我要不消失呢？难不成你准备下口了？

**Comment by nly4lov** [comment]
> > > 这软件这样子还是希望快点完蛋的好~彻底完了，也就不用还心心恋恋的回头来看一下！估计我这个回帖之后会被标上closed！
> > 
> > 
> > 你这些话不说也行，自己悄咪咪的消失就好了。
> 
> 那我要不消失呢？难不成你准备下口了？

我们人类不像你这种动物是吃屎的

**Comment by valasco** [comment]
> > > > 这软件这样子还是希望快点完蛋的好~彻底完了，也就不用还心心恋恋的回头来看一下！估计我这个回帖之后会被标上closed！
> > > 
> > > 
> > > 你这些话不说也行，自己悄咪咪的消失就好了。
> > 
> > 
> > 那我要不消失呢？难不成你准备下口了？
> 
> 我们人类不像你这种动物是吃屎的

嗯，不是吃屎长大的，怎么张嘴就喷粪啊？唐氏婴儿！嘴上还沾着粪吧？
