### ISSUE TITLE
Win10专业版1803科学上网需要安装Teredo Tunneling Pseudo-Interface，但却找不到方法！ 

### ISSUE THREAD

**Issue by tmzgsantui** [XX-net/XX-Net#12823]
如题。
网上搜索到的信息显示，这个网络适配器是关键：Teredo Tunneling Pseudo-Interface。可我没找到有效的安装方法，就更别说后续的安装、设置了。
求大神告知，多谢！

**Comment by tmzgsantui** [comment]
刚刚升级了路由软件，已经可以直接支持IPv6了。我想，这也就不需要teredo了。是这样吗？
另外，部署APPID，所用的字符窜是名称还是ID呢？
谢谢。

**Comment by tmzgsantui** [comment]
我的路由、电脑设置均显示可以连通IPv6了，可XX-Net的GAEProxy状态信息仍显示：等待扫描 IP，建议开启 IPv6。请问这是为什么？！

**Comment by tmzgsantui** [comment]
http://www.test-ipv6.com/网站测试结果是：你的 DNS 服务器（可能由运营商提供）已经接入 IPv6 互联网了。

**Comment by tmzgsantui** [comment]
哪位大神可以帮忙啊？！

**Comment by valasco** [comment]
没必要折腾了，这软件对大部分人来讲已经是僵尸状态了！

**Comment by tmzgsantui** [comment]
> 
> 
> 没必要折腾了，这软件对大部分人来讲已经是僵尸状态了！

这位朋友有好建议吗？
