### ISSUE TITLE
心力交瘁，所以这个到底还活着么

### ISSUE THREAD

**Issue by DicTag** [XX-net/XX-Net#12831]
已经是最新版；看过issues；状态不想贴了，似乎一直在变化，不是602，就是ipV6不可用，或者刚说“你现在可以访问真正的互联网“了然后一上google立马可用ip变成0。或者好不容易好了半天，第二天又挂了。。这两年一直是这样的状态。

我承认每次发问前应该先搜类似的issue是基本的礼仪，我搜了，可能并不是所有的都看得懂，能看懂的都尝试了。每次都要尝试很久，今天又折腾3个小时，依然丝毫没有起色。。

1.某人一直强调的 某开关，我从来都没有开过
2.json里面不可用的前端也都关了
3.teredo能查得到的都换过了
4.今天有些配置似乎保存不了，比如最大扫描线程数，好像看到有人说新版本是限定了的
5.一些偏方也尝试了下，什么指定日本服务器啥的，没啥卵用还会造成打不开

我也不知道是我网络真的差到极点了还是哪里操作不对或者电脑货路由有什么设置不对，每次（真的是每次）想上个外网都那么难，搜issue和提问也很累，我承认我不是专业的，有些东西我也看不懂，我也不知道怎么尝试原生的ipv6，我也不知道teredo如果都挂了我怎么去尝试其他的隧道。。。真的很心累。。我不是不愿意花钱啊，买了两年的tunnel流量全都烂了。。不知道是不是如果没点专业知识的就不配用这个，很多回答看的一头雾水。。而且每次这样大把大把时间浪费最终还用不了，我真的消耗不起了。。也许我真的应该去租个服务器搭纸飞机
![Snipaste_2019-10-29_23-04-46](https://user-images.githubusercontent.com/12840690/67786690-46293200-faaa-11e9-8431-8d0953b16631.jpg)

**Comment by 2378** [comment]
https://free-ss.site/ 拿去 量大

**Comment by hubsocks** [comment]
@DicTag  你从来没看issues吧,xx-net 用ipv4速度秒杀各种收费ssr.
@2378 打开这个网页后,我知道你这些数据是怎么来的了. 那vip的信息能提取出来吗?

**Comment by jap33** [comment]
活着

**Comment by jap33** [comment]
> 
> 
> 活着用ipv4速度扛扛的，

**Comment by DicTag** [comment]
> @DicTag 你从来没看issues吧,xx-net 用ipv4速度秒杀各种收费ssr.
> @2378 打开这个网页后,我知道你这些数据是怎么来的了. 那vip的信息能提取出来吗?

首先请你不要武断地下结论，完全不负责任就给人扣个帽子，说我从来没看过issue，那我改配置改json写命令换teredo尝试各种偏方都是自己拍大腿想出来的吗？你怕不是连我的描述都没看完？连SeaHoH都说个人网络存在差异，你如果有真诚的建议就好好说，不想说就别说。

**Comment by DicTag** [comment]
> 本来 xx 是傻瓜化的设计，但是没有持续维护更新，肯定就会出现现在这种种问题。
> 其实如果你花费了但使用率特别低，我建议找 xx 退款，发邮件问呗。
> 
> 另外，各人网络条件不同，不要逮住一个工具不放，试试其它看看有没有合适的。

谢谢你的回复，昨天万念俱灰的时候我真的想给个痛快话吧，今天翻wiki又看到之前没试过的等下再试试，再不行就不强求了。然后看你说到退款，我反而突然有点怀念这两年来折腾的日子了，虽然还是小白啥都没会，还是感恩大家的无私分享。

**Comment by DicTag** [comment]
> > 活着用ipv4速度扛扛的，

你用的是付费x-tunnel吗，还是免费的？

**Comment by dovisutu** [comment]
确实个人网络有差异，xx现在能不能用比较随缘，我以前3.11之后就一直调隧道一直调v6一直不稳定，最近重新下回来3.13开开就能用了...
活着还是活着的，只不过网络环境差就基本没救了
> 现在还是想先找个其他的ladder备用，要不然更新都更不下来

**Comment by lkyyang** [comment]
> https://free-ss.site/ 拿去 量大

请问这上面的服务器需要一个一个试，然后手动添加吗？

**Comment by 2378** [comment]
@lkyyang 这些适合拿来应急，都能用，具体看个人线路。

**Comment by fhq8800** [comment]
别浪费流量，
fhq8800@gmail.com 
。这个确实是线路问题，我在老家也是死连不上，一到城市，鸡血狂喷

**Comment by jianeddie** [comment]
https://github.com/Alvin9999/new-pac/wiki

换这个吧，多个选择，偶尔用用还是足够，可以自己提取里面的科学软件，配合SwitchyOmega，哪个速度快用哪个，xxnet我算是放弃了

**Comment by DicTag** [comment]
> https://github.com/Alvin9999/new-pac/wiki
> 
> 换这个吧，多个选择，偶尔用用还是足够，可以自己提取里面的科学软件，配合SwitchyOmega，哪个速度快用哪个，xxnet我算是放弃了

非常感谢！

**Comment by jjjyyyllll** [comment]
https://dwz.cn/bNCjFwUW 试试这个 注册给1元买7天很快
