### ISSUE TITLE
3.13.3switchyOmega.crx chrome扩展程序无效

### ISSUE THREAD

**Issue by BuBu0816** [XX-net/XX-Net#12837]
以前一直用3.13.1最近好久没用电脑打算更新3.13.3，下载新的安装包重新开始安装后卡在扩展程序，switchyomega.crx的谷歌扩展一直安装不了，显示扩展程序无效（crx header invalid），修改后缀为rar解压后以解压后的压缩包形式导入结果显示有错误，给出一堆错误代码（但是我看不太懂）

想问一下有没有人同样遇到过这种问题？大家有没有有效的解决方法
不胜感激

**Comment by BuBu0816** [comment]
给出的错误：

TypeError: Illegal invocation: Function must be called on an object of type StorageArea
TypeError: Illegal invocation: Function must be called on an object of type ChromeSetting
[1] Unhandled rejection: TypeError: Illegal invocation: Function must be called on an object of type ChromeSetting
The specified value "!" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
The specified value "!" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
Uncaught TypeError: Cannot read property 'bind' of undefined
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by BuBu0816** [comment]
今天有重新更新google，之前用的是哪个版本不太清楚了

**Comment by AgoniNemo** [comment]
因为谷歌73变换了 crx3 的签名   
最新下载[SwitchyOmega](https://gofinall.com/files/SwitchyOmega-v2.5.20.crx)

**Comment by BuBu0816** [comment]
> 因为谷歌73变换了 crx3 的签名
> 最新下载SwitchyOmega

感谢，已解决
