### ISSUE TITLE
软件会强制覆盖电脑的代理设置吗？

### ISSUE THREAD

**Issue by LiCasey** [XX-net/XX-Net#12845]
偶尔有的时候，我点了了托盘菜单“关闭全局代理”，过一会还是会自动设置上代理
再关，过一会还会自己设置

甚至把软件关了以后还会继续自动设置代理，过一会一次，如果要正常上网必须到网络设置里自己关代理，而且过一会就要手动关一次

关个十几次就好了……但是就很影响心情

感觉是某个进程退出的时候没关干净，但是也不知道应该怎么关……

有没有人遇到这个问题……

**Comment by LiCasey** [comment]
Duplicate of #12807 

发现有人问过这个问题了，不过这个issue里的方法还没试，回头有空试一下

**Comment by SeaHOH** [comment]
系统 bug，不建议使用 Windows 托盘提供的代理设置功能。

**Comment by g8up** [comment]
没遇到过。你如果怀疑进程没退出。可以到任务管理器里看下有没有`python.exe`相关的进程，十有八九是xx-net的，关闭即可。（供参考）
