### ISSUE TITLE
无法访问config页面

### ISSUE THREAD

**Issue by yipeterhan** [XX-net/XX-Net#12849]
不知道为什么突然就无法访问localhost了……127.0.0.1：8085也不行，issue里描述的几个方法都试过了，host也改了，iis也开了……

问题更新：好吧是我蠢了，最终试下来既不是host的问题也不是防火墙的问题，是浏览器的问题。127.0.0.1：8085在edge上能打开，连同因特尔的驱动与支持助手。这些在chrome上统统打不开……这到底在哪设置啊……求问大神……

**Comment by SeaHOH** [comment]
检查防火墙设置
