### ISSUE TITLE
【推荐】一键快速科学上网工具

### ISSUE THREAD

**Issue by vwin2006** [XX-net/XX-Net#12857]
XX-Net已经有一两周用不了，最近看朋友推荐了这款工具，快速又稳定。希望能帮到需要的同学。
[一键快速科学上网工具](https://github.com/xiaoming2028/FreeNet/wiki/VPS%E4%B8%80%E9%94%AE%E8%84%9A%E6%9C%AC%E6%90%AD%E5%BB%BASSR%E6%95%99%E7%A8%8B%EF%BC%8CYoutube%E7%9C%8B4k%E8%A7%86%E9%A2%91%E6%97%A0%E5%8E%8B%E5%8A%9B)

**Comment by SeaHOH** [comment]
#12770
