### ISSUE TITLE
我看tunnel也彻底死了吧

### ISSUE THREAD

**Issue by hurricanesh** [XX-net/XX-Net#12850]
今天一天连登录都登录不上去，别说翻墙了。

这几年翻墙翻的太累了，买的vpn速度倒是很快，但是付了一年的费用只用了一个月就被封了。我自己有两台海外的服务器，用ssh tunnel速度也极慢，只能偶尔收发邮件应应急。最近专门买了个vps设置vpn也是慢的没法用。

那些建墙的人真不怕报应，佩服，给我多少钱我都不会做这种缺德事。

**Comment by hurricanesh** [comment]
如果谁知道哪里的vps能搭建速度很快的vpn，请告知。如果已经搭好愿意分享的话，我愿意共担费用。请不要推荐专门的翻墙服务，这种早晚必封，无数不怕报应的人天天就想着怎么把网络封的更死。

**Comment by xugaohui** [comment]
电脑，手机上都是用的xx-net。速度很好，早上2k油管完全没问题，晚上10点也有4000k.方法多看 issue 。编个程序，多线程建立tcp连接，然后握手，判断服务端的cn值，很简单的。其实github有这方面的源码。

**Comment by 2378** [comment]
手上有vps，为什么不搭个机场，非要建vpn ？

**Comment by ablebodied** [comment]
@xugaohui  可以详细指导一下吗？

**Comment by yeahwu** [comment]
x-tunnel是通过gae转发的，也就是说，需要ip才能连接。如果没有可用ip自然是连接不上。

**Comment by Dexilc** [comment]
反正我花钱买的x-tunnel流量白白浪费了，根本没用上

**Comment by g8up** [comment]
@Dexilc 求施舍点流量。
我之前也是买了3个月，只用了不到10个G。

**Comment by Dexilc** [comment]
@g8up sorry, 买的时候还是夏季，就算有也已经过期,而且我发了退款邮件，开发者已经退款了，谢谢开发者，很久没用XX-net了，现在改用v2ray
