### ISSUE TITLE
求助 ipv6连不上 真的各种方法都试过了 4.0.3 mac10.15.4 谢谢大神

### ISSUE THREAD

**Issue by 5000e1** [XX-net/XX-Net#12853]
XX-Net Status:

sys-platform: x86_64, Darwin-19.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
os-release: 19.0.0
os-detail: Release:10.15.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
xxnet-version: 3.13.3

python-version: 2.7.16
openssl-version: 16.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 5000e1** [comment]
QAQ

**Comment by Cenler** [comment]
QAQ

**Comment by liuxiaodong528** [comment]
+1

**Comment by SkillUsing** [comment]
+1 QAQ

**Comment by xxnet** [comment]
将python 更新到 python2.7.17
https://www.python.org/downloads/release/python-2717/

**Comment by 5000e1** [comment]
> 将python 更新到 python2.7.17 https://www.python.org/downloads/release/python-2717/

您好 请问一下为什么我已经下载了并安装了 但是刷新页面 还是显示2.7.16

**Comment by 5000e1** [comment]
> 将python 更新到 python2.7.17 https://www.python.org/downloads/release/python-2717/

我现在好像可以用了 但是ipv6还是显示失败 不知道为什么 麻烦您看一下 谢谢🙏
XX-Net Status:

sys-platform: x86_64, Darwin-19.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
os-release: 19.3.0
os-detail: Release:10.15.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
xxnet-version: 3.15.10

python-version: 2.7.16
openssl-version: 19.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 5000e1** [comment]
mac10.15.4

XX-Net Status:

sys-platform: x86_64, Darwin-19.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
os-release: 19.4.0
os-detail: Release:10.15.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
xxnet-version: 3.15.10

python-version: 2.7.16
openssl-version: 19.0.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 5000e1** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-19.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
os-release: 19.4.0
os-detail: Release:10.15.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
xxnet-version: 4.0.3
python-version: 3.7.0
openssl-version: 19.1.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by 5000e1** [comment]
并且更新后图标没了

**Comment by maomao8341** [comment]
同样，是好是坏，搞死都没办法

**Comment by maomao8341** [comment]
路由器小米，想要原生ipv6 于是网线改从lan口连接，还是不行，是好是坏，求大神赐教
