### ISSUE TITLE
XX-net算是被彻底放弃了吗？

### ISSUE THREAD

**Issue by Thierryy** [XX-net/XX-Net#12855]
现在基本不能用了，XX-net偶尔会有一个可用ip，XX-tunnel也是经常连不上服务器。XX-net终究逃不过被墙的命运吗，还是大神们不想再维护了？都好久没更新了。
============================================================
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:101 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 30
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by vwin2006** [comment]
好像两周之前就用不了了，找了其他的工具代替了。[一键上网工具](https://github.com/xiaoming2028/FreeNet/wiki/Hostinger%E4%B8%80%E9%94%AE%E8%84%9A%E6%9C%AC%E6%90%AD%E5%BB%BASSR%E6%95%99%E7%A8%8B%EF%BC%8CVPS%E6%90%AD%E5%BB%BASS%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B)

**Comment by krollMJ** [comment]
土匪猖狂，凉凉纪念。

**Comment by Harveychn** [comment]
试试这个加速器吧，免费而且手机端也有客户端 ，速度挺快的 https://my.lausera.com/aff/RYC3
