### ISSUE TITLE
XX-Net开发维护者是不是被请喝茶了？SSR如何？好用吗？我折腾了半天，没成功啊！

### ISSUE THREAD

**Issue by tmzgsantui** [XX-net/XX-Net#12856]
油管上有一个帅哥视频，介绍如何使用SSR的（不过已经几个月没动静了，估计也被请喝茶了）：https://www.youtube.com/watch?v=kehR-6gDf7c&list=PLSIgtoxrUoAbCqF3usk9Q1lqJnGjy_8dk

我照着他的提示，捣鼓了半天，SSR还是不行啊！谁能给点指教啊？不过，将SSR和自由门结合使用，倒是速度蛮快，好像比单独使用自由门更快。:-(

**Comment by 2378** [comment]
ssr用AEAD加密算法，传统AES加密至少有10%几率能被墙识别

**Comment by 2378** [comment]
当然，不论怎么加密混淆都逃不过物理限速，记得10几大那时，三条梯子几乎瘫痪，油管勉强144p

**Comment by ablebodied** [comment]
试试v2ray吧，试试[一键脚本](https://github.com/233boy/v2ray/wiki/V2Ray%E6%90%AD%E5%BB%BA%E8%AF%A6%E7%BB%86%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B)

**Comment by tmzgsantui** [comment]
XX-Net还有戏吗？什么时候有人续上？

**Comment by 2378** [comment]
xnet能不能用，全靠个人环境。至于大佬X，人家早就肉翻了，喝茶这种鸟事还是担心下自己吧

**Comment by tmzgsantui** [comment]
我要更新一下：刚才再次单独打开SSR，多换了几个服务器，现在看起来又可以了。共需要的朋友参考，祝各位好运！

**Comment by 2378** [comment]
哎~说到喝茶，怀念一下Lu大

**Comment by ablebodied** [comment]
唉，像在梦里，21世纪了没想到还是Big Qing Dynasty

**Comment by oldedifier** [comment]
试试这个吧，[vps一键安装SS](https://github.com/xiaoming2028/FreeNet/wiki/VPS%E4%B8%80%E9%94%AE%E8%84%9A%E6%9C%AC%E6%90%AD%E5%BB%BASSR%E6%95%99%E7%A8%8B%EF%BC%8CYoutube%E7%9C%8B4k%E8%A7%86%E9%A2%91%E6%97%A0%E5%8E%8B%E5%8A%9B)

**Comment by jjjyyyllll** [comment]
> 油管上有一个帅哥视频，介绍如何使用SSR的（不过已经几个月没动静了，估计也被请喝茶了）：https://www.youtube.com/watch?v=kehR-6gDf7c&list=PLSIgtoxrUoAbCqF3usk9Q1lqJnGjy_8dk
> 
> 我照着他的提示，捣鼓了半天，SSR还是不行啊！谁能给点指教啊？不过，将SSR和自由门结合使用，倒是速度蛮快，好像比单独使用自由门更快。:-(

https://dwz.cn/bNCjFwUW  试试这个 注册给1元买7天很快
