### ISSUE TITLE
请给我PAYPAL账户发送一个4.5美元的订单我要购买季卡

### ISSUE THREAD

**Issue by wangmengyu** [XX-net/XX-Net#12864]
我试了下
登录PAYPAL之后
用XX-NET发起支付还是需要我填入卡号
然后还没办法支付，支付按钮点不动
能不能直接发送一个收款单给我，我自己去PAYPAL上面付，成功以后帮我续费3个月呢
谢谢

**Comment by SeaHOH** [comment]
支付问题建议你直接发邮件问，如果你测试过还能顺畅使用的话。

**Comment by wangmengyu** [comment]
谢谢。我最终是尝试非登录方式，选择下面一个按钮：直接使用卡支付，支付成功的，这应该是中国PAYPAL的一个BUG
