### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by 964606561** [XX-net/XX-Net#12862]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:5
scan-ip-thread-num: 30
ip-quality: 294
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 964606561** [comment]
找到网络和internet设置  点击代理选项 打开使用代理服务器 地址填127.0.0.1 端口8087

**Comment by 964606561** [comment]
补充：如果使用google浏览器 配置好服务器之后关掉Google助手

**Comment by RoverLion** [comment]
现在不是很好用了感觉，试试这个，个人感觉挺好用的 https://my.laihuluwa.com/aff/R6Ys
可以试试

**Comment by Harveychn** [comment]
感觉这个工具没人在维护了，试试这个加速器吧，免费而且手机端也有客户端 ，速度挺快的 https://my.lausera.com/aff/RYC3
