### ISSUE TITLE
建议：停止自动更改系统的代理

### ISSUE THREAD

**Issue by hurricanesh** [XX-net/XX-Net#12870]
xx-net自动修改系统的代理，每次用IE或者用系统代理的软件都需要修改，造成很多不便。如果需要用的话手工改一次也挺方便的。

能不能停止修改系统的IP？留给用户去操作。谢谢！

**Comment by nly4lov** [comment]
右击系统托盘图标你就明白了

**Comment by icecubez** [comment]
我遇到的问题是windows下，无论关掉xx-net与否，总是自动打开代理服务器，每隔一段时间要手动关掉代理服务器，人快崩溃了.......
