### ISSUE TITLE
xx-net访问pinterest首页不正常

### ISSUE THREAD

**Issue by tq01o3n** [XX-net/XX-Net#12873]
xx-net访问pinterest首页不正常，一直显示中间的登录或注册小窗口，进不去，标签栏上的圈圈每隔几秒转一次，说明一直在刷新，我试图用ssr访问pinterest很正常，一直是登录状态，回到xx-net就不正常，用GAEProxy，PAC代理模式都不行，怎么回事呢？

XX-Net
![Annotation 2020-01-07 134842](https://user-images.githubusercontent.com/15064148/71871909-c678ad00-3155-11ea-9ed5-94e920cc6521.jpg)
 Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
xxnet-version: 3.13.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:100
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:35
scan-ip-thread-num: 200
ip-quality: 217
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
我跟你一样。

**Comment by Michael-X-Net** [comment]
GAE会存在兼容性问题。
这种情况下用x-Tunnel 应该就可以了

**Comment by tq01o3n** [comment]
不愿意用有偿

发自我的 iPhone

**Comment by tq01o3n** [comment]
用SSR就正常， 但速度太慢了
