### ISSUE TITLE
建议：将高级设置的IP模式改为自动，IPv4可用，可看视频

### ISSUE THREAD

**Issue by ashley1226** [XX-net/XX-Net#12872]
建议：将高级设置的IP模式改为自动，IPv4可用，可看视频
之前把IP模式改了，结果这两天发现虽然只有两个IP，但是竟然可以看视频，可以试试看。

**Comment by nly4lov** [comment]
我早就这样设置了，ipv6有20个左右ip，4一个也没。看youtube啥的挺费劲

**Comment by ablebodied** [comment]
ipv4 确实在增多，现在有一百多了，原生ipv6基本完蛋了

**Comment by lefantian** [comment]
是的，这样确实能扫到ipv4，但是时有时无

可是xx好长时间没跟新了啊，开发的大佬是不是已经放弃了？

**Comment by Harveychn** [comment]
感觉这个工具没人在维护了，试试这个加速器吧，免费而且手机端也有客户端 ，速度挺快的 https://my.lausera.com/aff/RYC3
