### ISSUE TITLE
满血复活！感谢团队！报告一个再次出现的漏洞^_^

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#12884]
漏洞是：启动以后，默认状态是“取消全局代理”，且不能改变！
必须在【internet设置/连接/局域网设置】中手工填写127.0.0.1:8087代理服务器才行！
这个漏洞，在版本3.13.2中出现过，3.13.3版本中修复了。
现在3.13.4中又出现了。
虽说不是大问题，但每次手工填写很是麻烦，当退出xxnet，还得去手工取消代理。。。
总之，是麻烦。

**Comment by freeflysky** [comment]
感谢感恩作者的坚持和付出，为谷歌学术和Google earth 建模而来，学术研究被逼上了绝路。

**Comment by tq01o3n** [comment]
> 网络设置/局域网/代理服务器

这个是win10里?还是哪里?

**Comment by tq01o3n** [comment]
> 能用了！感谢团队！反映一个再次出现的漏洞^_^
> +++
> 漏洞是：启动以后，默认状态是“取消全局代理”，且拒绝改变！
> 必须在【网络设置/局域网/代理服务器】手工填写127.0.0.1:8087才行！
> 这个漏洞，在版本3.13.2中出现过，3.13.3版本中修复了。
> 现在3.13.4中又出现了。
> 虽说不是大问题，但每次手工填写很是麻烦，当退出xxnet，还得去手工取消代理。。。
> 总之，是麻烦。
网络设置/局域网/代理服务器
这个是win10里?还是哪里?

**Comment by belleyeah** [comment]
新版本3.14在哪里下载？网站上还是3.13.

**Comment by belleyeah** [comment]
找到了，https://codeload.github.com/XX-net/XX-Net/zip/3.13.4 
果然复活啦！！！

**Comment by xxnet** [comment]
没有重新这个bug，有其他人遇到这个问题的吗？

这个版本没有改动到相关代码，很奇怪。

**Comment by SeaHOH** [comment]
这只是 windows 本身的 bug 而已。

**Comment by wuwuti** [comment]
> 没有重新这个bug，有其他人遇到这个问题的吗？ 这个版本没有改动到相关代码，很奇怪。

确实奇怪！
我现在一直在手工填写。
3.13.3确实没这个问题。

**Comment by wuwuti** [comment]
> 这只是 windows 本身的 bug 而已。

但是，前一个版本没这个问题啊——同一个电脑，同样的win10.。。。应该排除win本身的bug~

**Comment by latiaoer** [comment]
![Screenshot_2020-01-22-15-13-38-853_com android browser](https://user-images.githubusercontent.com/36580639/72876206-f5377b80-3d30-11ea-96c3-5fdc609548df.jpg)
quora手机网页排版有问题

**Comment by SeaHOH** [comment]
> 但是，前一个版本没这个问题啊——同一个电脑，同样的win10.。。。应该排除win本身的bug~

你可以切换版本测试。
