### ISSUE TITLE
申请退款已有3个月有余，但是至今未收到退款。

### ISSUE THREAD

**Issue by yaoliweb** [XX-net/XX-Net#12889]
你好，我2019年10月10日通过paypal花了4.5刀买了流量，后来发现xx-net被封，于是在2019年10月23日申请退款，但是至今未收到退款。请官方解决。

**Comment by xxnet** [comment]
给xxnet.dev@gmail.com发邮件吧，会退款的
一般从paypal上发起退款就行了，有其他情况给xxnet.dev@gmail.com 发邮件
