### ISSUE TITLE
我的xtunnel显示还有很多流量，但是如何使用？？

### ISSUE THREAD

**Issue by lmw17009** [XX-net/XX-Net#12882]
我的xtunnel显示还有很多流量，但是如何使用？？
总共还有900GB的流量，
![360截图20200118090344811](https://user-images.githubusercontent.com/36779275/72655734-7dd0b780-39d1-11ea-93d5-a753397f7dd6.jpg)
我现在不知道是用的xxnet的还是xtunnel的功能。
上面标注的转让请问如何转让，有需要的人没有哦。
因为我发现目前还能看YouTube，但是又没使用上这个流量。

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B

**Comment by fhq8800** [comment]
转点给我把，谢谢。输入对方账号就可以转让。fhq8800@gmail.com

**Comment by tiantainxiangshang01** [comment]
转点给我把，谢谢!!!f
ksdfkjewi@hotmail.com

**Comment by lgxnas** [comment]
谢谢，转点给我吧 lgxlyh@gmail.com

**Comment by smith221** [comment]
我也需要，只有xtunnel可以代理DROPBOX。
转些给我吧，谢谢！
lanjinhui12@gmail.com

**Comment by Dexilc** [comment]
davidchen1011@gmail.com能否转些，谢谢

**Comment by powerzhengh** [comment]
您好！如果有多余的流量，愿意转让些的话，不胜感激。谢谢
powerzhengh@gmail.com

**Comment by hahsfb** [comment]
还有流量么[😂]，谢谢啦
haohsfb@gmail.com

**Comment by vicentory** [comment]
请转让一点流量，谢谢，xiao199188@gmail.com

**Comment by 100725** [comment]
还可以转让吗，谢谢 Olivia100725@gmail.com
