### ISSUE TITLE
大佬帮忙看看实例小时数的问题

### ISSUE THREAD

**Issue by lgxnas** [XX-net/XX-Net#12891]
* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？
是的,正在使用3.13.4
* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？
是的,未找到相关记录
* 是否以相关关键词搜索过类似 issues？
是的,也许版本不同,不能找到解决方案
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
** 昨天的小时数为50小时,目前关闭了Appid **
今天7小时显示已使用17小时数
![F322392A-82E7-48A2-A2C3-C802C9887465](https://user-images.githubusercontent.com/44049217/73000149-66635580-3e3b-11ea-9ba7-172eec6e010f.jpeg)

XX-Net Status:

sys-platform: x86_64, Linux-4.15.17-1-pve-x86_64-with-debian-9.4
os-system: Linux
os-version: #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200)
os-release: 4.15.17-1-pve
os-detail: Dist:debian; Version:9.4; ID:
architecture: 64bit,
browser: Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/79.0.3945.73 Mobile/15E148 Safari/604.1
xxnet-version: 3.13.4

python-version: 2.7.13
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:76 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:18
scan-ip-thread-num: 10
ip-quality: 997
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，不遵守规则的提问会被自动关闭。

**Comment by lgxnas** [comment]
昨天显示17小时,今天实际记录是30小时,真是不懂

**Comment by xxnet** [comment]
实际记录在哪里看到的？

**Comment by lgxnas** [comment]
因为看到有金额,就查了下是什么费用,结果是流量0.4G,但是实例小时数超过28了,忘记当时在哪里查到,明天再在电脑上看看

**Comment by lgxnas** [comment]
> 实际记录在哪里看到的？

因为看到有金额,就查了下是什么费用,结果是流量0.4G,但是实例小时数超过28了,忘记当时在哪里查到,明天再在电脑上看看

**Comment by xxnet** [comment]
根据这个文档：
https://cloud.google.com/appengine/docs/standard/payment-instrument
设置支付帐号后的appid 依然可以做到免费。

但是google 设置了门槛，自己去把实例数控制好：
参考这里：
https://cloud.google.com/appengine/docs/standard/python/config/appref#scaling_elements
https://cloud.google.com/appengine/docs/standard/python/config/setting-autoscaling-params-in-explorer

**Comment by lgxnas** [comment]
> 根据这个文档： https://cloud.google.com/appengine/docs/standard/payment-instrument 设置支付帐号后的appid 依然可以做到免费。 但是google 设置了门槛，自己去把实例数控制好： 参考这里： https://cloud.google.com/appengine/docs/standard/python/config/appref#scaling_elements https://cloud.google.com/appengine/docs/standard/python/config/setting-autoscaling-params-in-explorer

非常感谢
