### ISSUE TITLE
久违的XX-Net据说可用了，很高兴，特来求教！

### ISSUE THREAD

**Issue by tmzgsantui** [XX-net/XX-Net#12895]
数年前用过，后来一度不能联网，也就中断使用了几年。已经忘了如何设置APPID、代理，请指教。
多谢！

**Comment by tmzgsantui** [comment]
自我更新以下：不需要设置代理，用智能路由代理一般都可以墙内墙外兼顾，速度还可以。

**Comment by taoeternal2018** [comment]
偶尔碰到管控严格的时候还是会刷不到ip，有时甚至持续时间很长比如1~2个月，但是稍松一点就能用，还是很不错的，感谢作者

**Comment by QiTianzu** [comment]
一年没用了，今天又用上了

**Comment by KsRyY** [comment]
我这边IP好像都以ipv4为主，ipv6倒是不怎么好使

**Comment by zhaoruihao** [comment]
我也是一年多没用了，最近突然发现X大回来了，开心，感谢X大

**Comment by pldeom** [comment]
能用了，但永远要低调！
