### ISSUE TITLE
如何能扫描到 IPv6 地址？

### ISSUE THREAD

**Issue by tmzgsantui** [XX-net/XX-Net#12897]
我的XX-Net状态是：

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 99
有效 IPv6 IP 数 | 0
总 IP 数 | 100
XX-Net 状态 | 空闲
IP 延迟 | 358
连接池(帮助) | 新:0 h1:0 h2:2

请教。

**Comment by AnyWAT** [comment]
貌似：原生时，IPv6 少或 0，IPv4 多；隧道时，IPv4 少或 0，IPv6 多。

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6
