### ISSUE TITLE
首先感谢开发团队的更新，确实满血复活，速度很好，就是pinterest出现反复登录的问题，不知道其他小伙伴有没有遇到一样的问题？

### ISSUE THREAD

**Issue by uone0513** [XX-net/XX-Net#12890]
pinterest出现反复登录的问题，不知道其他小伙伴有没有遇到一样的问题？

**Comment by uone0513** [comment]
刚刚又发现，tumblr也登不上……

**Comment by lgxnas** [comment]
Cannot contact reCAPTCHA. Check your connection and try again.

**Comment by uone0513** [comment]
> 
> 
> Cannot contact reCAPTCHA. Check your connection and try again.

出现过要求人机验证，但是还是登不了……

**Comment by uone0513** [comment]
tumblr用setupvpn登录一下，然后关闭，切换到xxnet再打开就好了，但是pinterest用这个方法不行，依然提示你需要登录，且登录不上，没有任何提示，登录后，直接跳回登录界面让你再次登录

**Comment by GFconcept** [comment]
PIN 只能用XXtunnel登录才行！！！！

**Comment by uone0513** [comment]
> 
> 
> PIN 只能用XXtunnel登录才行！！！！

好的，了解了，谢谢~

**Comment by tq01o3n** [comment]
> > PIN 只能用XXtunnel登录才行！！！！
> 
> 好的，了解了，谢谢~

xxtunnel没有免费的把?

**Comment by SeaHOH** [comment]
每日免费 500MB
