### ISSUE TITLE
提示 请检查浏览器代理设置      状态显示：浏览器代理设置和CA 证书状态 两个都是Fail

### ISSUE THREAD

**Issue by sparksustc** [XX-net/XX-Net#12893]
这个问题和代理有关，或者和CA证书有关。

前者的解决方案是：托盘图标处设置“取消全局代理”；同时检查chrome浏览器的SwitchyOmega是否是最新版本。如果不是，可以删除之后重新安装一下这个插件。（2020.1.26这次的故障就是真实的浏览器代理设置问题，因为chrome下的切换插件版本太老，不兼容xx-net 3.13.4，更新插件之后就好了）

后者的解决方案是：删除证书，重新安装。

**Comment by SeaHOH** [comment]
能用就行，不用老是看它，连接状况差时会误判。
