### ISSUE TITLE
Google Cloud Platform创建项目需要信用卡咋整？

### ISSUE THREAD

**Issue by zyqlerry** [XX-net/XX-Net#12899]
现在创建项目需要提供一个真实的信用卡号，好像还需要扣除一点费用来验证卡的真实性。有大佬支支招吗
![image](https://user-images.githubusercontent.com/34573872/73342734-20364800-42ba-11ea-9067-4914f7cd94c8.png)

**Comment by MadMaxPayne8964** [comment]
绑卡，国内visa双币卡可用

**Comment by B1ran** [comment]
> 绑卡，国内visa双币卡可用

请问master的双币可以不？

**Comment by tennyee** [comment]
我的http://127.0.0.1:8085/的界面没有让创建信用卡的地方怎么办？我的版本每次更新都不见这个页面有更新，而我给朋友装的这个软件，明显看着这个界面不一样。

**Comment by zyqlerry** [comment]
> 我的[http://127.0.0.1:8085/的界面没有让创建信用卡的地方怎么办？我的版本每次更新都不见这个页面有更新，而我给朋友装的这个软件，明显看着这个界面不一样。](http://127.0.0.1:8085/%E7%9A%84%E7%95%8C%E9%9D%A2%E6%B2%A1%E6%9C%89%E8%AE%A9%E5%88%9B%E5%BB%BA%E4%BF%A1%E7%94%A8%E5%8D%A1%E7%9A%84%E5%9C%B0%E6%96%B9%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F%E6%88%91%E7%9A%84%E7%89%88%E6%9C%AC%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E9%83%BD%E4%B8%8D%E8%A7%81%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E6%9C%89%E6%9B%B4%E6%96%B0%EF%BC%8C%E8%80%8C%E6%88%91%E7%BB%99%E6%9C%8B%E5%8F%8B%E8%A3%85%E7%9A%84%E8%BF%99%E4%B8%AA%E8%BD%AF%E4%BB%B6%EF%BC%8C%E6%98%8E%E6%98%BE%E7%9C%8B%E7%9D%80%E8%BF%99%E4%B8%AA%E7%95%8C%E9%9D%A2%E4%B8%8D%E4%B8%80%E6%A0%B7%E3%80%82)

在“配置”和“部署服务端”里面可以部署自己的appid，appid在谷歌的Google Cloud Platform上创建项目得到，而问题是现在创建项目需要信用卡。如果你只是用公共appid就不存在这这些问题，祝您愉快！😘

**Comment by luweitest** [comment]
我昨天刚试过创建，可以不要进入信用卡的下一步，只要有了appID就可以部署了。wiki里那一步可以省去

**Comment by pch9527** [comment]
已测试：在云平台上创建完id后，忽略绑卡页面，直接到XX-net下就可以正常部署

**Comment by tennyee** [comment]
> > 我的[http://127.0.0.1:8085/的界面没有让创建信用卡的地方怎么办？我的版本每次更新都不见这个页面有更新，而我给朋友装的这个软件，明显看着这个界面不一样。](http://127.0.0.1:8085/%E7%9A%84%E7%95%8C%E9%9D%A2%E6%B2%A1%E6%9C%89%E8%AE%A9%E5%88%9B%E5%BB%BA%E4%BF%A1%E7%94%A8%E5%8D%A1%E7%9A%84%E5%9C%B0%E6%96%B9%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F%E6%88%91%E7%9A%84%E7%89%88%E6%9C%AC%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E9%83%BD%E4%B8%8D%E8%A7%81%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E6%9C%89%E6%9B%B4%E6%96%B0%EF%BC%8C%E8%80%8C%E6%88%91%E7%BB%99%E6%9C%8B%E5%8F%8B%E8%A3%85%E7%9A%84%E8%BF%99%E4%B8%AA%E8%BD%AF%E4%BB%B6%EF%BC%8C%E6%98%8E%E6%98%BE%E7%9C%8B%E7%9D%80%E8%BF%99%E4%B8%AA%E7%95%8C%E9%9D%A2%E4%B8%8D%E4%B8%80%E6%A0%B7%E3%80%82)
> 
> 在“配置”和“部署服务端”里面可以部署自己的appid，appid在谷歌的Google Cloud Platform上创建项目得到，而问题是现在创建项目需要信用卡。如果你只是用公共appid就不存在这这些问题，祝您愉快！😘

我是很早就绑定了appid，现在没有新增appid的计划，也就是不用再重复你的步骤了，对吧。

**Comment by zyqlerry** [comment]
> > > 我的[http://127.0.0.1:8085/的界面没有让创建信用卡的地方怎么办？我的版本每次更新都不见这个页面有更新，而我给朋友装的这个软件，明显看着这个界面不一样。](http://127.0.0.1:8085/%E7%9A%84%E7%95%8C%E9%9D%A2%E6%B2%A1%E6%9C%89%E8%AE%A9%E5%88%9B%E5%BB%BA%E4%BF%A1%E7%94%A8%E5%8D%A1%E7%9A%84%E5%9C%B0%E6%96%B9%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F%E6%88%91%E7%9A%84%E7%89%88%E6%9C%AC%E6%AF%8F%E6%AC%A1%E6%9B%B4%E6%96%B0%E9%83%BD%E4%B8%8D%E8%A7%81%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E6%9C%89%E6%9B%B4%E6%96%B0%EF%BC%8C%E8%80%8C%E6%88%91%E7%BB%99%E6%9C%8B%E5%8F%8B%E8%A3%85%E7%9A%84%E8%BF%99%E4%B8%AA%E8%BD%AF%E4%BB%B6%EF%BC%8C%E6%98%8E%E6%98%BE%E7%9C%8B%E7%9D%80%E8%BF%99%E4%B8%AA%E7%95%8C%E9%9D%A2%E4%B8%8D%E4%B8%80%E6%A0%B7%E3%80%82)
> > 
> > 
> > 在“配置”和“部署服务端”里面可以部署自己的appid，appid在谷歌的Google Cloud Platform上创建项目得到，而问题是现在创建项目需要信用卡。如果你只是用公共appid就不存在这这些问题，祝您愉快！😘
> 
> 我是很早就绑定了appid，现在没有新增appid的计划，也就是不用再重复你的步骤了，对吧。

对！

**Comment by heavenkiller2018** [comment]
> 我昨天刚试过创建，可以不要进入信用卡的下一步，只要有了appID就可以部署了。wiki里那一步可以省去
> Duplicate of #12907

具体是怎样操作的？绑卡那一步省不了啊？

**Comment by zyqlerry** [comment]
> > 我昨天刚试过创建，可以不要进入信用卡的下一步，只要有了appID就可以部署了。wiki里那一步可以省去
> > Duplicate of #12907
> 
> 具体是怎样操作的？绑卡那一步省不了啊？

按正常操作创建，当出现需要绑卡的时候取消掉，虽然绑卡取消掉了，但你会发现右上角那个铃铛点开里面显示已经部署
