### ISSUE TITLE
请教：哪里可以下载安卓版XX-Net？

### ISSUE THREAD

**Issue by tmzgsantui** [XX-net/XX-Net#12900]
如题。
现在的手机安卓系统已经到9.1版了，要兼容的XX-Net。
谢谢。

**Comment by AlephAlpha** [comment]
https://github.com/XndroidDev/Xndroid

**Comment by tmzgsantui** [comment]
谢谢楼上！
刚才安装了，来说说使用体验。
1、对于一般的墙外网页，可以浏览，只是加载页面时常常提示安全警告：该证书并非来自可信的授权中心。是否继续加载？
2、最重要的阿谷、油管应用，都不能访问，提示没有联网。
本人手机系统本已完美整合阿谷各套件，用其他代理可以打开上述两应用的。

望指教！

**Comment by tmzgsantui** [comment]
> 
> 
> https://github.com/XndroidDev/Xndroid

谢谢楼上！
刚才安装了，来说说使用体验。
1、对于一般的墙外网页，可以浏览，只是加载页面时常常提示安全警告：该证书并非来自可信的授权中心。是否继续加载？
2、最重要的阿谷、油管应用，都不能访问，提示没有联网。
本人手机系统本已完美整合阿谷各套件，未root，用其他代理可以打开上述两应用的。

望指教！

**Comment by latiaoer** [comment]
需要root后导入为系统证书。此软件只支持浏览器。

**Comment by tmzgsantui** [comment]
> 
> 
> 需要root后导入为系统证书。此软件只支持浏览器。

可惜。
我的手机已经完美整合阿谷套件，无需root。如果root了，以后的升级可能有麻烦。
多谢告知！

**Comment by tmzgsantui** [comment]
> 
> 
> 需要root后导入为系统证书。此软件只支持浏览器。

再请问一句：高人会开发无需root，可完美支持网页、视频，不无故弹出安全警告的安卓版XX-Net吗？

**Comment by xxnet** [comment]
用X-Tunnel模式就不需要root，没有安全警告

**Comment by tmzgsantui** [comment]
> 
> 用X-Tunnel模式就不需要root，没有安全警告
谢谢告知。
请问如何使用X-Tunnel模式，使用它需要具备什么条件？用它是否可以打开油管视频？

**Comment by tmzgsantui** [comment]
顶起来，呵呵。

**Comment by tmzgsantui** [comment]
我再顶起来

**Comment by SeaHOH** [comment]
Xndroid 那边应该有说明，发问前先看 wiki。
