### ISSUE TITLE
3.14.0在运行一段时间后会自动无响应退出

### ISSUE THREAD

**Issue by Hyperkopite** [XX-net/XX-Net#12905]
我相信我不是一个人

**Comment by Hyperkopite** [comment]
我只能自己写了个守护进程，循环检测到退出就自动重开。。。

**Comment by xxnet** [comment]
你试试用start.bat启动，如果退出看看窗口显示什么信息

**Comment by Hyperkopite** [comment]
我试了一下，无响应自动退出后那个bat窗口也跟着关闭了，看了一下唯一的一个error.log也没有退出时候的记录。

**Comment by Hyperkopite** [comment]
> 你试试用start.bat启动，如果退出看看窗口显示什么信息

我试了一下，无响应自动退出后那个bat窗口也跟着关闭了，看了一下唯一的一个error.log也没有退出时候的记录。

**Comment by xxnet** [comment]
请问你是什么操作系统？

你可以先开cmd 命令窗口，这样就不会在退出时关闭窗口。
然后用cd 命令切换到XX-Net目录，执行start.bat启动

**Comment by Hyperkopite** [comment]
试了一下在cmd，powershell里面启动都是会打开一个独立的窗口，不能像普通程序一样直接在命令行下运行，因为vbs脚本调用了python.exe。算了我先用着自己的临时办法吧。

**Comment by Hyperkopite** [comment]
> 请问你是什么操作系统？ 你可以先开cmd 命令窗口，这样就不会在退出时关闭窗口。 然后用cd 命令切换到XX-Net目录，执行start.bat启动

我是win10 professional 我试了一下在cmd和powershell里面运行start.bat后都会打开一个独立窗口，跟之前一样，估计是因为start.vbs调用了python.exe。算了我先用着我自己的临时办法吧。

**Comment by Nitrome47** [comment]
+1，我也出现了两次这种情况。

**Comment by charles203** [comment]
我还是3.13.4，也是很快就会自动退出

**Comment by Hyperkopite** [comment]
有相同问题的同学可以尝试临时解决办法，等待大佬修复
https://github.com/Hyperkopite/XX-Net-deamon

**Comment by xxnet** [comment]
目前怀疑是自带python的问题，有能力的可以试试下载个最新的python，用新的python来启动试试

**Comment by Hyperkopite** [comment]
> 目前怀疑是自带python的问题，有能力的可以试试下载个最新的python，用新的python来启动试试

XX-Net是基于PYTHON 2 开发的吗？用python 3运行会不会有问题？作者辛苦了！

**Comment by xxnet** [comment]
是用python 2开发的，用python3不能运行。

python官网最新python 2版本是 2.7.17，XX-Net自带的版本是2.7.13
也许官网的新版修复了这个问题

**Comment by charles203** [comment]
应该是的，我用.bat运行，一会儿就提示python遇到错误需要关闭，然后就关了

**Comment by xxnet** [comment]
有发现什么重新的规律吗？
放着不访问网站会出现吗？
或者访问某个特定的网站就会出问题？

会不会是360之类的搞鬼？

**Comment by Wangqkoe** [comment]
@xxnet 应该不是360的问题，我电脑只用了win10自带的防病毒也发生了这种问题。把安装目录下data文件夹删除然后重新运行start.vbs可以治标不治本。

**Comment by Nitrome47** [comment]
暂时没发现规律，只出现了两次并没有记录下情况，有一次我比较确定是开着Chrome浏览器放着不管时出现的问题，第一次不记得当时的状况，这两天又没有出现同样的问题。我电脑上没有装第三方杀毒软件，只有WIN10自带的防病毒系统。

**Comment by ablebodied** [comment]
我也有自动退出的情况，不过就发生过一次，之后还未遇到，没有安装360之类的

**Comment by xxnet** [comment]
刚发布3.14.1，请大家试试效果

**Comment by Hyperkopite** [comment]
> 刚发布3.14.1，请大家试试效果

问题还是存在，但还好，也不是也别影响使用
