### ISSUE TITLE
可否隐藏客户端IP地址

### ISSUE THREAD

**Issue by icehong** [XX-net/XX-Net#12909]
访问某些网站时， 网页当前能显示出访问者所在IP地址。

 既然是中转的， 是否可以在GAE代理时去掉客户端IP地址，达到隐藏IP的效果。

**Comment by xxnet** [comment]
GAE代理无法隐藏，可参考这个文档：

https://cloud.google.com/appengine/docs/flexible/python/reference/request-headers

**Comment by icehong** [comment]
受教了。
