### ISSUE TITLE
更新后的3.13.4版本下载后解压缩错误，有一样的么

### ISSUE THREAD

**Issue by winters-z** [XX-net/XX-Net#12901]
![x](https://user-images.githubusercontent.com/32010503/73441357-d9b21d80-438d-11ea-8f64-0a83a90dd55e.png)

**Comment by xxnet** [comment]
试试重新下载，因为github经常被干扰。

**Comment by winters-z** [comment]
找到另一个下载源 12.8M 的是完整的，前面那个下载了只有 8M

**Comment by winters-z** [comment]
![image](https://user-images.githubusercontent.com/32010503/73446497-d754c100-4397-11ea-92df-78e676320159.png)
复活了
