### ISSUE TITLE
[发布] 3.14.2 修复3.14.1 无法部署服务端问题

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#12917]
新版修复 3.14.2版本无法部署服务端问题

https://github.com/XX-net/XX-Net/releases/tag/3.14.2

**Comment by erdcy** [comment]
楼主有空的话，把OpenWRT上不能运行的问题也解决了吧，感谢感谢！以前可以运行，用了应该超过一年了，最近因为路由器外置u盘坏了，换了u盘，重刷了系统，就不能运行了，信息如下。
————————————————————————————————————————————
sh /etc/XX-Net/start
XX-Net version:3.14.1
It is OpenWrt.
It is openwrt.
2020-02-09 10:40:06.763 [launcher][INFO] This is Android or IOS or router.
2020-02-09 10:40:07.648 [launcher][INFO] import build-in openssl fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
2020-02-09 10:40:07.719 [launcher][ERROR] import system python-OpenSSL fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
2020-02-09 10:40:07.720 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 177, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found

Try install python-openssl

Press Enter to continue...
————————————————————————————————————————————
python，python-opnessl，python-pyopenssl都装了，OpenWRT版本与能运行时的版本是一样的。

**Comment by uone0513** [comment]
首先感谢楼主不断的更新，就是很早之前使用xxnet的时候pinterest登录啥的都是好的，现在满血复活后完全登不上，有网友说必须要用X-Tunnel才行，可我切换了还是登不上，不知道是不是个案？PS：用setupvpn就可以登上

**Comment by xxnet** [comment]
> 楼主有空的话，把OpenWRT上不能运行的问题也解决了吧，感谢感谢！以前可以运行，用了应该超过一年了，最近因为路由器外置u盘坏了，换了u盘，重刷了系统，就不能运行了，信息如下。
> ————————————————————————————————————————————
> sh /etc/XX-Net/start
> XX-Net version:3.14.1
> It is OpenWrt.
> It is openwrt.
> 2020-02-09 10:40:06.763 [launcher][INFO] This is Android or IOS or router.
> 2020-02-09 10:40:07.648 [launcher][INFO] import build-in openssl fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
> 2020-02-09 10:40:07.719 [launcher][ERROR] import system python-OpenSSL fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
> 2020-02-09 10:40:07.720 [launcher][ERROR] Except stack:Traceback (most recent call last):
> File "code/default/launcher/start.py", line 177, in
> import OpenSSL
> File "/usr/lib/python2.7/site-packages/OpenSSL/**init**.py", line 8, in
> File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in
> File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in
> File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in
> ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found
> 
> Try install python-openssl
> 
> Press Enter to continue...
> ————————————————————————————————————————————
> python，python-opnessl，python-pyopenssl都装了，OpenWRT版本与能运行时的版本是一样的。

看日志应该是OpenWRT上的pyOpenSSL模块无法工作，似乎和XX-Net 没有关系。

可以自己写一个小python代码验证：
------------------------------------
import OpenSSL
------------------------------------

然后运行这个代码

**Comment by xxnet** [comment]
> 首先感谢楼主不断的更新，就是很早之前使用xxnet的时候pinterest登录啥的都是好的，现在满血复活后完全登不上，有网友说必须要用X-Tunnel才行，可我切换了还是登不上，不知道是不是个案？PS：用setupvpn就可以登上

x-tunnel 登录pinterest刚测试过没有问题啊

**Comment by erdcy** [comment]
> > 楼主有空的话，把OpenWRT上不能运行的问题也解决了吧，感谢感谢！以前可以运行，用了应该超过一年了，最近因为路由器外置u盘坏了，换了u盘，重刷了系统，就不能运行了，信息如下。
> > ————————————————————————————————————————————
> > sh /etc/XX-Net/start
> > XX-Net version:3.14.1
> > It is OpenWrt.
> > It is openwrt.
> > 2020-02-09 10:40:06.763 [launcher][INFO] This is Android or IOS or router.
> > 2020-02-09 10:40:07.648 [launcher][INFO] import build-in openssl fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
> > 2020-02-09 10:40:07.719 [launcher][ERROR] import system python-OpenSSL fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
> > 2020-02-09 10:40:07.720 [launcher][ERROR] Except stack:Traceback (most recent call last):
> > File "code/default/launcher/start.py", line 177, in
> > import OpenSSL
> > File "/usr/lib/python2.7/site-packages/OpenSSL/**init**.py", line 8, in
> > File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in
> > File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in
> > File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in
> > ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found
> > Try install python-openssl
> > Press Enter to continue...
> > ————————————————————————————————————————————
> > python，python-opnessl，python-pyopenssl都装了，OpenWRT版本与能运行时的版本是一样的。
> 
> 看日志应该是OpenWRT上的pyOpenSSL模块无法工作，似乎和XX-Net 没有关系。
> 
> ## 可以自己写一个小python代码验证：
> ## import OpenSSL
> 然后运行这个代码

呵呵，我是编程小白。楼主，是python-pyopenssl有问题，还是python-openssl有问题？我找个别的版本装上试试。

**Comment by xxnet** [comment]
应该是python-pyopenssl

**Comment by erdcy** [comment]
> 应该是python-pyopenssl

谢谢！我想办法试试旧版本的。

**Comment by cctoking** [comment]
请问在哪里下载3.14.2版本,自动更新只能到3.14.1

**Comment by uone0513** [comment]
> 
> 
> > 首先感谢楼主不断的更新，就是很早之前使用xxnet的时候pinterest登录啥的都是好的，现在满血复活后完全登不上，有网友说必须要用X-Tunnel才行，可我切换了还是登不上，不知道是不是个案？PS：用setupvpn就可以登上
> 
> x-tunnel 登录pinterest刚测试过没有问题啊

是不是右键选择 全局通过x-tunnel代理，就算切换了？然后我切了还是登不上，虽然我没有购买过，但里面有100M的流量，而且切换后登录，流量也确实减少了，不知道啥问题了，现在不用x-tunnel是不是没有办法直接登录了呀？为啥最早的时候都好的呀，哈，实在不行就用其他办法算了，再次感谢楼主的解答和不断更新，辛苦啦~~

**Comment by AllisonShare** [comment]
下载到最后就失败
