### ISSUE TITLE
8086口是真的socks proxy吗

### ISSUE THREAD

**Issue by luweitest** [XX-net/XX-Net#12918]
WindowsXP SP3， XX-net 3.14
代理设为8086口，类型socks5，网页可以连接，但无法pop3收邮件

**Comment by xxnet** [comment]
8086 是智能路由模块的端口，要用作pop3，你需要确认x-tunnel能够工作。
pop3建议用1080端口吧，先确认x-tunnel能够工作

**Comment by luweitest** [comment]
On 2020-2-9 13:31, Michael.X wrote:
> 8086 是智能路由模块的端口，要用作pop3，你需要确认x-tunnel能够工作。
> pop3建议用1080端口吧，先确认x-tunnel能够工作
> 
x-tunnel模块是默认关闭的，我理解它是一个收费服务模块
是不是说这个Smart Router模块的socks代理只是转发，http的转发到GAE 
Proxy，http以外的请求转发到x-tunnel？

-- 
Regards,
Lu Wei
IM:	xmpp:luweitest@riotcat.org
PGP:	0xA12FEF7592CCE1EA

**Comment by xxnet** [comment]
是的，GAE处理不了的请求转发到x-tunnel

**Comment by luweitest** [comment]
谢谢解释
