### ISSUE TITLE
pythonw.exe 已停止工作

### ISSUE THREAD

**Issue by 102464** [XX-net/XX-Net#12911]
pythonw.exe 已停止工作
Windows 可以联机检查该问题的解决方案

使用X-Tunnel没几分钟就出这个，然后就显示GAEProxy退出了，重启XX-Net后错误复现。
MacOS系统上也出这个问题，运行一个小时左右就segmentation fault

电脑上没有安装任何国产杀毒软件（任何杀毒软件都没装）

这是怎么回事怎么解决

**Comment by 102464** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
xxnet-version: 3.13.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:35 ipv4:24 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:6
scan-ip-thread-num: 1
ip-quality: 2088
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
正在努力重现中，已经有不少人报这个问题

**Comment by 102464** [comment]
0x73000068 处有未经处理的异常(在 pythonw.exe 中): 0xC0000005: 执行位置 0x73000068 时发生访问冲突。 出现了 

问题签名:
  问题事件名称:	BEX
  应用程序名:	pythonw.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5855a390
  故障模块名称:	StackHash_0a9e
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常偏移:	73000068
  异常代码:	c0000005
  异常数据:	00000008
  OS 版本:	6.1.7601.2.1.0.256.4
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by xxnet** [comment]
查了StackHash_0a9e，是关于内存保护问题，也就是代码区被覆盖，看来是python版本的漏洞。

https://social.technet.microsoft.com/Forums/ie/en-US/3932e3eb-c034-4eb7-aa06-4a0a8e6ea493/fault-module-namestackhash0a9e?forum=w7itprogeneral


我会尽快把python更新到最新版

**Comment by xxnet** [comment]
刚发布了新版，更新内置的Python
#12915 
请测试

**Comment by 102464** [comment]
昨天开了一晚上，今天又遇到已停止响应的问题，但报错信息改变了
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	pythonw.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5dab7714
  故障模块名称:	_openssl.pyd
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5da86b9f
  异常代码:	c0000005
  异常偏移:	00089377
  OS 版本:	6.1.7601.2.1.0.256.4
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

貌似是openssl的问题

**Comment by 102464** [comment]
问题还是没有解决，仍然还是崩溃

**Comment by xxnet** [comment]
问题出在OpenSSL，Windows10的用户有没有遇到？
目前听到的基本是Win7的用户

**Comment by AnyWAT** [comment]
天天使用贵软件的Windows10 近年各版本一直偶尔自动退出
