### ISSUE TITLE
有没有成功下载了安装包的中国用户，可以共享使用吗，国内速度感人……

### ISSUE THREAD

**Issue by XieZengYu** [XX-net/XX-Net#12923]
码云的仓库已经4年没用更新了，现在使用修改host的方法也无法下载，速度很慢，并且下载不了几M就中断，无法续传，希望有安装包的大佬可以共享一下……

**Comment by xxnet** [comment]
改进方向：可以考虑把python模块剥离出去，客户端用vbs下载python环境。
有谁能帮忙写这个vbs脚本的吗？

**Comment by namenulll** [comment]
https://jia666-my.sharepoint.com/:u:/g/personal/hkkqcw0z8_xkx_me/EQPSXqf1VKdFt_cYhFuvNUoBOkQEqYz_4y5Dt0NBj8ja_Q?e=SJ3nda

**Comment by gly11** [comment]
https://gitee.com/gly11/XX-Net

**Comment by XieZengYu** [comment]
谢谢各位大佬！

**Comment by XieZengYu** [comment]
码云的下载链接还是github的，希望能同步一个国内仓

**Comment by gly11** [comment]
> 码云的下载链接还是github的，希望能同步一个国内仓

码云你点下载zip就很快了
