### ISSUE TITLE
pteredor.py 作者帮我解答一下好吗？

### ISSUE THREAD

**Issue by RomanSmile** [XX-net/XX-Net#12930]
为什么运行脚本测试每次都是
   ``win10.ipv6.microsoft.com
    win1710.ipv6.microsoft.com
    win1711.ipv6.microsoft.com
最快，真的更换了这几个服务器系统，会报告网络不可达？？？
这三个服务器真的还活着吗？？？

**Comment by SeaHOH** [comment]
你该去问微软客服，我这里测试结果是不稳定，跟你的测试结果完全不同。

**Comment by SeaHOH** [comment]
每次测试间隔 5 分钟以上，如频繁测试导致服务器连接问题，可重启光猫或系统。

**Comment by RomanSmile** [comment]
我这里有两条线路可以测试
电信-联通
除了.microsoft.com
其余的都是稳定只要更换.microsoft.com整个隧道瘫痪

**Comment by RomanSmile** [comment]
``l@l:~/pteredor$ python pteredor.py -h -p 54301

pteredor [-p <port>] [-P <port>] [-h] [<server1> [<server2> [...]]]
      -p  设置本地客户端端口。
      -P  设置远程服务端端口。
      -h  显示本帮助信息。

          Teredo server 是一个主机名，可以使用域名或 IP。


('try bind local port:', 54301)
Starting probe NAT type...
NAT 类型是 restricted。
Starting evaluate servers...
40.81.120.44 ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com'] 254ms
83.170.6.76 ['teredo.remlab.net', 'teredo-debian.remlab.net'] 255ms
40.74.3.100 ['win1711.ipv6.microsoft.com'] 255ms
217.17.192.217 ['teredo.iks-jena.de'] 315ms
195.140.195.140 ['teredo.trex.fi'] 327ms
217.31.202.18 ['teredo.nic.cz'] 347ms

经检测，推荐服务器是 ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com'].
按回车键结束……

**Comment by SeaHOH** [comment]
Miredo？debian 的测试结果只差 1 ms！既然其它都稳定，为什么你要用微软的服务器？？？
实在想用，建议换 bug10，还连不上就找客服。

**Comment by RomanSmile** [comment]
@SeaHOH 
首先感谢你的回答，很久了我都在怀疑微软的服务器可用性，用了许多工具测试他们的端口是关闭的，
而不是过滤，一次次的测试我只是满心的疑惑，所以才来你这里，想从你这里得到解答，告诉我他们为什么在你的测试是存活的，然后来弥补我的无知，我也曾经仔细的阅读了有关RFC_4380，得知他们是受限制的锥接口，隧道的快慢完全取决隧道服务器速度，如果你愿意抽出你的宝贵时间，告诉我一些你的测试经验，分享一下，

**Comment by xugaohui** [comment]
@RomanSmile  我完全不懂这方面的，一点点看法，要用 udp 连接才能知道端口有没有开。大多数工具是针对tcp的。那还是编程吧。速度恰巧完全不与隧道服务器速度有关。而是另一个有公网ipv4的数据转发服务器速度有关。还是抓包分析吧。

**Comment by SeaHOH** [comment]
这个工具的由来，只是为了终结关于服务器是否可用的口水战，因为很多人都像你一样去测 TCP 端口是否关闭。隧道速度的问题正如 xugaohui 所讲，和服务器无关，没法简单测试，我也是在编写过程中了解到的。虽然 teredo 是微软开发的，但是它的服务并不是完全遵循标准，使用了扩展的规范。

不知道你到底想要做什么。如果想了解运作机制，建议你再**认真阅读** RFC 文档或其它相关文档，读 pteredor 的源码也行（根据用途只实现了网络类型测试）；如果只是使用，就挨个试一遍，哪个好用就用它，没必要太折腾。

**Comment by SeaHOH** [comment]
另，关于所谓受限类型，这里的受限并非你所理解的功能受限不完全，而是意为可遵守一定之规范（同守法公民），非受限类型无法遵守此规范，则不能使用依此规范建立的功能。
