### ISSUE TITLE
GAEProxy是否会给请求内容添加UTF-8 BOM(Byte Order Mark)

### ISSUE THREAD

**Issue by KsRyY** [XX-net/XX-Net#12931]
我在使用GAEProxy上namae.dev这个网站上的时候发现了一个奇怪的问题：
不用GAEProxy一切正常
使用GAEProxy以后出问题：由于这个网页要动态发送请求然后解析返回的JSON，网站上所有的需要解析json的地方都会报：`SyntaxError: Unexpected token � in JSON at position 0`。由于这个问题出在返回位置0，我怀疑GAEProxy给返回的内容加上了一个UTF-8 BOM，而原有的请求已经有一个BOM，浏览器在解析响应的时候只会去掉一个BOM，然后造成JSON的解析错误

**Comment by xxnet** [comment]
从以为知道的应该是不会，但是不GAE不兼容是常见的，具体每个网站的原因不同。
遇到不兼容情况建议用X-tunnel

**Comment by KsRyY** [comment]
OK，谢谢
