### ISSUE TITLE
tor为什么无法把GAEProxy作为前端代理。why gae can't work as fronthal proxy for tor

### ISSUE THREAD

**Issue by arora123you** [XX-net/XX-Net#12934]
参考问题：https://github.com/XX-net/XX-Net/issues/8964
Reference issue: https://github.com/XX-net/XX-Net/issues/8964

目前我尝试了在tor浏览器中使用http/https协议连接127.0.0.1:8087，已达到将gae作为tor前置代理的目的，但一直没有连接成功。

我知道tor浏览器连接成功的条件是在无数的tor服务器节点间形成一条链路。是不是GAE proxy的ip地址一直在变动，导致tor无法形成稳定的链路，导致tor无法联通？是否还有其它原因？

有没有精通网络和GAE原理的大佬来解释一下啊~谢谢！

In order to use goagent as the fronthal proxy for tor browser ,I have tried to connect to 127.0.0.1:8087 using the http/https protocol.  It never succeeded.

I know that the condition for the successful connection of the tor browser is to form a link between countless tor server nodes. Is it possible that since the IP address of the GAE proxy keeps changing, Tor fail to find a stable route through the tor nodes? Or are there any other reasons?

Can anybody who is familar with the principles of network and GAEProxy please explain it? Appreciations!

**Comment by arora123you** [comment]
我刚刚又想了一下，觉得问题可能出在Tor不应该放在XX net后面。如果这样的话tor要从墙内通过桥翻墙找到tor relay再从墙外翻回来连我本机xx-net的代理端口，所以速度肯定慢。所以tor应该设为xx net的前置代理。可不知道为什么很多帖子里都说xx net / shawdow socks要放在tor前面

**Comment by xugaohui** [comment]
多重梯子的速度都不好，大多时候更慢。

**Comment by xxnet** [comment]
比较可靠的是用x-tunnel作为tor的前置.
GAE可能存在问题是因为GAE不是标准的https代理。
