### ISSUE TITLE
[发布] 3.15.1 精简下载包

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#12939]
因为墙对github的干扰影响了安装包下载，新版删除了python运行环境，在第一次启动时通过脚本进行下载。

下载地址：
https://github.com/XX-net/XX-Net/releases/download/3.15.1/XX-Net-3.15.1.7z   
https://github.com/XX-net/XX-Net/archive/3.15.1.zip  

精简之前7M，精简后的安装包只有850k。
第一次因为要下载解压python环境，启动会比较慢，请大家测试。

**Comment by OneCam-hot** [comment]
脚本：D:\Program Files\XX-Net\start.vbs
行：78
字符：5
错误：系统未找到指定的资源

代码：800C0005
源：msxml3.dll
![图片1](https://user-images.githubusercontent.com/61073376/74581585-1582ef00-4fec-11ea-8adc-b32212447a69.png)

**Comment by xxnet** [comment]
这个版本不 支持XP

**Comment by AeneasZhu** [comment]
可否直接把3.14.2的python包直接放在3.15的code/default里面？下载速度太慢了

**Comment by OneCam-hot** [comment]
> 这个版本不 支持XP

Win7 x64

**Comment by nasa217** [comment]
兄弟们，这个本人不成啊，基本上，大陆北京时间上午9点以前，下载速度还不错。还是把python放里面把，我这个启动了四十分钟也没动弹，始终不走路。

**Comment by xxnet** [comment]
观察 data/download目录，看等哪个文件时间长

**Comment by cnlog** [comment]
内置py环境的装U盘到那都可以用的。py如果没镜像，下载走都走不动。要不弄两个版本，精简版的给第一次安装的用，如果已经装XX的，升级的时候通过代理是没速度问题的。现在的问题是老账号没绑卡到时候会不会给停了......。

**Comment by whalien520** [comment]
错误：系统未找到指定的资源

代码：800C0005
源：msxml3.dll

win7 32位

**Comment by nasa217** [comment]
错误：系统未找到指定的资源

代码：800C0005
源：msxml3.dll
win10 1903 64位

**Comment by allen226973** [comment]
还是集成吧，根本下载不动。

**Comment by timaxell** [comment]
3.15.0和3.15.1用chrome dev直接下载，chrome下载页面【失败 - 检测到病毒】，windows 10 企业版 安全中心 已检测到威胁Trojan:Script/Foretype.A!ml，警报级别 严重，之前的3.14最后一个版本没有报毒

**Comment by xxnet** [comment]
根据反馈发了新版，请参考 #12941
