### ISSUE TITLE
哪位大神能帮忙看看怎么解决?

### ISSUE THREAD

**Issue by fhk579** [XX-net/XX-Net#12932]
XX-Net Status:

sys-platform: x86_64, Linux-4.14.162-x86_64-with-libc
os-system: Linux
os-version: #0 SMP Mon Jan 6 16:47:09 2020
os-release: 4.14.162
os-detail: Dist:; Version:; ID:
architecture: 64bit,
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
xxnet-version: 3.14.2

python-version: 2.7.17
openssl-version: 19.1.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:56 ipv6:4
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 916
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by fhk579** [comment]
运行环境是:openwrt19.07.0+(xx-net3.14.2)。不能上外网，其它正常

**Comment by erdcy** [comment]
一般来说是这两项：
1，客户端是否安装了证书；
2，监听ip是否修改为0.0.0.0。
p.s. 请教一个问题：运行前在OpenWRT环境，除了安装python，还安装了什么软件？

**Comment by fhk579** [comment]
python-pyopenssl

**Comment by fhk579** [comment]
监听ip是否修改为0.0.0.0

在什么地方能改呢？

**Comment by erdcy** [comment]
修改/XX-Net/data/gae_proxy/config.json
打开看就明白了
p.s. 我以前一直以为要装python-openssl

**Comment by fhk579** [comment]
试了不行，一改，xx-net运行就报错

**Comment by erdcy** [comment]
先检查一下是不是修改的时候出现了语法错误
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by gayhub-dev** [comment]
启动时加 -allow_remote 参数, 我也是在别的issue里面看到的===

**Comment by SeaHOH** [comment]
> 启动时加 -allow_remote 参数

非本机使用必须如此，还需确保导入证书和代理设置正确，
