### ISSUE TITLE
频繁闪退

### ISSUE THREAD

**Issue by faintfigure** [XX-net/XX-Net#12945]
3.14.1版本看油管视频经常系统托盘自动就没了，更新最新3.15.3仍存在此现象，请问是何原因？

**Comment by spenserwong** [comment]
还是3.14.0好用，不会自动退出

**Comment by snipertulip** [comment]
> 3.14.1版本看油管视频经常系统托盘自动就没了，更新最新3.15.3仍存在此现象，请问是何原因？

win10 也是

**Comment by xxnet** [comment]
这个问题挺严重的，目前怀疑是windows版本的 cryptograhy 模块有bug。
下面想到一个临时办法，start.vbs 启动进入循环模式，如果异常退出就自动重启。

实现的技巧：
launcher/start.py 在启动时创建一个临时文件，退出时删除。
如果非正常推出，start.vbs就自动重启。

**Comment by hubsocks** [comment]
每个版本都会有python关闭的错误.

**Comment by xxnet** [comment]
参考这里：
https://www.cnblogs.com/hushaojun/p/6388153.html

在出问题时生成dump文件，发给我分析 xxnet.dev@gmail.com

**Comment by hubsocks** [comment]
@xxnet TA分享了1个文件给你，在奶牛快传首页（cowtransfer.com）输入取件码：4e59ku (24小时内有效) 查看文件列表，或直接点击取件链接: https://c-t.work/s/d9d7afd1f15344 查看文件列表   dump文件

**Comment by SeaHOH** [comment]
不要用国内服务，直接发邮件。

**Comment by xxnet** [comment]
是的，请发邮件

**Comment by xxnet** [comment]
#12954 
发布了3.15.4 ,采用一个临时解决方案，python异常退出时，启动脚本自动重启python
