### ISSUE TITLE
win10系统V3.15.1 开始到 V3.15.3 运行时报错

### ISSUE THREAD

**Issue by qhdhjb** [XX-net/XX-Net#12942]
如题：
<img src="https://s2.ax1x.com/2020/02/16/3SgxU0.jpg" alt="3SgxU0.jpg" border="0" />
https://imgchr.com/i/3SgxU0

**Comment by xxnet** [comment]
3.15.3 要从下载页面下，
https://github.com/XX-net/XX-Net/blob/master/code/default/download.md

你下的是源代码，缺python环境

**Comment by qhdhjb** [comment]
按照您提供的网址下了，windows版正常使用，通用精简版报错，现在在单位。但昨晚在家里时，精简版也能正常使用，就是要下载东西等的时间久一点。

**Comment by xxnet** [comment]
因为精简版的下载python脚本被识别为病毒，所以去掉了精简版下载python的功能

**Comment by qhdhjb** [comment]
@xxnet 谢谢

**Comment by LN-VIVI** [comment]
@xxnet 我下了3.14.0能用，然后下载3.15.9打开那vbs就没反应了，也是因为下载的是精简版吗？

**Comment by xxnet** [comment]
是的，你试试下载 7z的版本

**Comment by LN-VIVI** [comment]
> 是的，你试试下载 7z的版本

谢谢
