### ISSUE TITLE
关于start.vbs

### ISSUE THREAD

**Issue by KJGKMTZB** [XX-net/XX-Net#12948]
为什么我打不开start.vbs，系统一直告诉我它找不到指定的文件，求解，谢谢

**Comment by Rven71** [comment]
我win10之前也出现过重装系统解决了

**Comment by KJGKMTZB** [comment]
> 我win10之前也出现过重装系统解决了

orz，谢谢

**Comment by fredyzhang5532** [comment]
我更新了最新版本，也是这个情况

**Comment by yukyukbaby** [comment]
> 我win10之前也出现过重装系统解决了

我昨天新买的 电脑 自带win10 不想重装。。。。原来win7是可以用的。。。win10 就安装不了……

**Comment by xxnet** [comment]
Windows用户一定用从下载页面下载：
https://github.com/XX-net/XX-Net/blob/master/code/default/download.md

**Comment by yukyukbaby** [comment]
> Windows用户一定用从下载页面下载： https://github.com/XX-net/XX-Net/blob/master/code/default/download.md

是的呀，稳定版和测试版都试了，还是提示找不到指定文件哦

**Comment by yukyukbaby** [comment]
> Windows用户一定用从下载页面下载： https://github.com/XX-net/XX-Net/blob/master/code/default/download.md

start.vbs文件里第66行，运行有错误

**Comment by kk363109309** [comment]
我知道是怎么回事！下载的文件被精简了！你把原来的文件夹python27复制进去覆盖替换就可以了。

**Comment by yukyukbaby** [comment]
> 我知道是怎么回事！下载的文件被精简了！你把原来的文件夹python27复制进去覆盖替换就可以了。

不缺这个文件呀，精简版里也有27啊~  我装的是稳定版呢

**Comment by tigerokkk** [comment]
![image](https://user-images.githubusercontent.com/6767329/74765075-e1465180-52bd-11ea-86c8-874b582ca6df.png)
python的路径不对。 而且是2.0版

**Comment by xxnet** [comment]
这个版本：
https://github.com/XX-net/XX-Net/releases/download/3.15.3/XX-Net-3.15.3.7z
或者：
https://github.com/XX-net/XX-Net/archive/3.14.0.zip

**Comment by yukyukbaby** [comment]
> 这个版本： https://github.com/XX-net/XX-Net/releases/download/3.15.3/XX-Net-3.15.3.7z 或者： https://github.com/XX-net/XX-Net/archive/3.14.0.zip
感谢你的回复，昨天都试啦，我从白天试到晚上，下载页最新版本都试过了，还是不行。不过我把旧电脑（win7）使用过的3.14版本复制到现在的电脑中（win10）可以使用了~

**Comment by kk363109309** [comment]
你有没有发现，3.15.3版本中文件夹python27大小逼原来的变小了吗？那就是问题所在。

**Comment by yukyukbaby** [comment]
> 你有没有发现，3.15.3版本中文件夹python27大小逼原来的变小了吗？那就是问题所在。

啊呀 ，没留意看这个呢，好嘛~

**Comment by wangxiaotian2527** [comment]
有一个解决办法，下载最新版了之后，把\XX-Net-master\code文件夹中的default文件夹和version.txt两个文件，复制到之前能用的旧版本里，就搞定了（我之前的旧版本还是3.13.3）

**Comment by wangxiaotian2527** [comment]
有一个解决办法，下载最新版了之后，把\XX-Net-master\code文件夹中的default文件夹和version.txt两个文件，复制到之前能用的旧版本里对应的code文件夹下边覆盖，就搞定了（我之前的旧版本还是3.13.3）

**Comment by AnyWAT** [comment]
修改桌面快捷方式 XX-Net 的属性：起始位置只保留 X:\XX-Net（去掉过往版本的多余参数 \code\default 或版本号\launcher ）后再运行。

**Comment by xxnet** [comment]
新版 3.15.7 版本修复了启动问题，请帮忙测试
@yukyukbaby

**Comment by xxnet** [comment]
#12977
