### ISSUE TITLE
ipv6 一直显示Fail尝试无数次已经一年多了还是无法开启请求好心人赐教，谢谢！

### ISSUE THREAD

**Issue by cmq2981159** [XX-net/XX-Net#12946]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
xxnet-version: 3.14.0

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:52 ipv4:51 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:1
worker: h1:0 h2:33
scan-ip-thread-num: 10
ip-quality: 276
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by tmttmd** [comment]
现在ipv4很好用了，ip充足，v6我这边广东电信原生支持但没卵用，搜不到ip，用v4速度就很快了
