### ISSUE TITLE
[发布] 3.15.3 改进精简包

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#12941]
#12939 
改进3.15.1 遇到的问题：
+ Win7 有些版本无法下载https
+ 下载脚本报病毒

改进:
+ 为windows版本提供最基本的python环境，安装包 5M
 代码中不包含python环境.
 非windows版本只有 830K

+ 浏览器插件在启动后再下载。
+ gae lib在部署时才下载

Windows版本：
https://github.com/XX-net/XX-Net/releases/download/3.15.3/XX-Net-3.15.3.7z

Mac/Linux 平台版本：
https://github.com/XX-net/XX-Net/archive/3.15.3.zip

**Comment by zhencaihao** [comment]
你好，我下载了3.15.3版本。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
xxnet-version: 3.15.3

python-version: 2.7.17
openssl-version: 19.1.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:69 ipv4:67 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:2
scan-ip-thread-num: 10
ip-quality: 725
is-idle: 1
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


设置全局通过 gaeproxy代理 无法上网怎么办？尝试打开github显示如下内容:
600:gae_exception:'602:ip not support GAE' https://github.com/XX-net/XX-Net/issuesgae_exception:'602:ip not support GAE' https://github.com/XX-net/XX-Net/issuesgae_exception:'602:ip not support GAE' https://github.com/XX-net/XX-Net/issues

![QQ截图20200217221146](https://user-images.githubusercontent.com/19796493/74661264-91d72700-51d2-11ea-82c6-d9f1b21c3967.jpg)

**Comment by zhencaihao** [comment]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态(如何开启) | OK
有效 IPv4 IP 数 | 74
有效 IPv6 IP 数 | 0
总 IP 数 | 77
XX-Net 状态 | 空闲
IP 延迟 | 809
连接池(帮助) | 新:0 h1:0 h2:1
浏览器代理设置 | OK
CA 证书状态(下载) | OK
IP 扫描线程数(设置) | 10
