### ISSUE TITLE
我更新了一下最新版本，反而出错了。。

### ISSUE THREAD

**Issue by yangsl158** [XX-net/XX-Net#12959]
我更新了一下最新版本，反而出错了。。
> 错误：文件未找到
> 代码：800A0035
> 求解答。。
>
>
> 更新到哪个版本？
手动下载还是在web里操作更新的？

两种方法都试过了。。刚才折腾了好久。
最新的情况是：设置开机启动，那么启动的时候就会出现代码800A004C的错误，如果手动启动就可以正常用。

_Originally posted by @xxnet in https://github.com/XX-net/XX-Net/issues/12954#issuecomment-589556187_

**Comment by AnyWAT** [comment]
症结：旧快捷方式的起始位置 X:\XX-Net\code\default 或版本号\launcher 
修改为 X:\XX-Net 才能适应近期版本
