### ISSUE TITLE
XX-net可以安装在路由器上面吗？

### ISSUE THREAD

**Issue by hdrafyy** [XX-net/XX-Net#12952]
手机版的好像可以正常使用了，不知道路由器上面能不能安装使用！

**Comment by xxnet** [comment]
有的，你找找wiki里的文章

**Comment by hdrafyy** [comment]
> 有的，你找找wiki里的文章

里面是有安装在路由器上面的文章，不过老毛子系统的没有，刚刚好我用的是这个系统，看来这外计划得打水漂了。

**Comment by xxnet** [comment]
XX-Net基于python，对路由器性能要求比较高，内存最少64M吧

**Comment by erdcy** [comment]
不同路由器固件、性能和硬件等差异太大，跑XX-Net的方法因“器”而异。
在issues里搜搜“潘多拉”，有几篇帖子，不一定适用你的路由器，但可以借鉴。
搜搜“路由器”、“openwrt”、“梅林”等关键词，有一些帖子可以作为参考。
