### ISSUE TITLE
以前的ip段都死灰复燃了

### ISSUE THREAD

**Issue by masktao** [XX-net/XX-Net#12967]
![image](https://user-images.githubusercontent.com/13614353/75121616-9d45b900-56d0-11ea-9df8-9242c0ad2fb4.png)
ipv6数量在慢慢下降,v4稳稳不动

**Comment by hubsocks** [comment]
google当前总共只有ipv4 gae服务器710个左右.ipv6想稳定传输基本不可能了.

**Comment by liuji789** [comment]
为啥你的ip数这么多，自己填的吗？
