### ISSUE TITLE
各位大佬，我的Mac有IPv6，为什么状态还是Fail？

### ISSUE THREAD

**Issue by jiangjiong** [XX-net/XX-Net#12963]
如图所示，我的理解就是本机已经分配到IPv6地址了吧？
<img width="780" alt="屏幕快照 2020-02-22 下午2 39 38" src="https://user-images.githubusercontent.com/7520208/75088000-21d5f180-5582-11ea-8bdb-b4606ece4a9f.png">

<img width="1439" alt="屏幕快照 2020-02-22 下午2 40 06" src="https://user-images.githubusercontent.com/7520208/75087998-1aaee380-5582-11ea-9e91-a93a488477d2.png">

**Comment by xxnet** [comment]
目前IPv6基本不可用，IPv4能用就可以了
