### ISSUE TITLE
各位大佬，能教教我怎么获取appid吗【我已经注册了GE的账号，也新建了几个项目，但就是没办法配置到服务器端】

### ISSUE THREAD

**Issue by luoshu9** [XX-net/XX-Net#12975]
大家好，是这样的
我先是激活了GM的账号，然后按照中文文档里面的说明进行配置项目至服务器端，但始终返回提示
“将该目录部署为App Engine应用程序需要文件。”
我不知道xx-net那个是应该上载的文件连接，我也去查询了相关教程，很遗憾，都没有找到结果，所以我来寻求各位大佬的帮助。
![~U6O1HP}B1GYGQ{UD%KLB0M](https://user-images.githubusercontent.com/44226510/75309723-d9257d80-588c-11ea-9712-ee8cbfafc298.png)

**Comment by Sharedaily** [comment]
教程里写的很清楚,你没弄懂而已.书读百遍其义自见,你仔细读读.
不然就弄个X-tunnel代理鼓励这个软件团队!

**Comment by Sharedaily** [comment]
X-tunnel代理买了也不贵

**Comment by luoshu9** [comment]
好的，谢谢大佬回答我，我这就去多看看

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Sharedaily <notifications@github.com>
发送时间: Wednesday, February 26, 2020 1:37:25 PM
收件人: XX-net/XX-Net <XX-Net@noreply.github.com>
抄送: luoshu9 <zhaozikun1@outlook.com>; Author <author@noreply.github.com>
主题: Re: [XX-net/XX-Net] 各位大佬，能教教我怎么获取appid吗【我已经注册了GE的账号，也新建了几个项目，但就是没办法配置到服务器端】 (#12975)


教程里写的很清楚,你没弄懂而已.书读百遍其义自见,你仔细读读.
不然就弄个X-tunnel代理鼓励这个软件团队!

―

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids
难道这教程还不够详细吗？

**Comment by dajunzhang1127** [comment]
![image](https://user-images.githubusercontent.com/31927114/75408857-fd975d80-5951-11ea-98c0-b55e9120d845.png)
点击下一步出现结算账户怎么搞定？

**Comment by yeahwu** [comment]
点击取消，已经创建成功了。

**Comment by haning123** [comment]
属性 | 值
-- | --
IPv4状态 | 好
IPv6状态（如何开启） | 好
有效的IPv4 IP数 | 1000
有效的IPv6 IP数 | 0
总IP数 | 1000
XX网状态 | 工作
IP延迟 | 178
连接池（帮助） | 新：0 h1：0 h2：20
浏览器代理设置 | 好
CA证书状态（下载） | 好
IP扫描线程数（设置）
