### ISSUE TITLE
几年前部署过的，今天更新一下，居然可以用！

### ISSUE THREAD

**Issue by iambonboncat** [XX-net/XX-Net#12979]
几年前部署过的，今天更新一下，居然可以用！只是速度比其他科学上网方式慢，不过免费，不用租用vps可以用已经不错了。

**Comment by iambonboncat** [comment]
作为备用方式，还是不错的选择。

**Comment by liamhui** [comment]
我的也可以。非常不错。

**Comment by gayhub-dev** [comment]
部署时选择asiaeast-2可以直连HK的数据中心,爽歪歪,我都快把gce的小鸡抛弃了

**Comment by iambonboncat** [comment]
> 部署时选择asiaeast-2可以直连HK的数据中心,爽歪歪,我都快把gce的小鸡抛弃了

我还正想翻资料看看能不能部署到hk，因为以前部署的好像都是用us的。不知道能不能一半是hk，一半是us，嘻嘻。

**Comment by iambonboncat** [comment]
好多年前部署过，现在都忘了怎么部署了，有没有相关教程？

**Comment by xxnet** [comment]
参考这里：
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

**Comment by iambonboncat** [comment]
> 参考这里： https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

如果部署10个us，再部署10个hk，一起用会出现什么情况？

**Comment by xxnet** [comment]
没有试过，估计没有差别

**Comment by iambonboncat** [comment]
> 没有试过，估计没有差别

试了一下，一般使用没问题，但是对于ip地区有要求的网页好像不太好，毕竟一会儿us，一会儿hk，而且ip一直在变

**Comment by xxnet** [comment]
用iplocation.net 看出口Ip是不是差别很大

**Comment by gayhub-dev** [comment]
> > 部署时选择asiaeast-2可以直连HK的数据中心,爽歪歪,我都快把gce的小鸡抛弃了
> 
> 我还正想翻资料看看能不能部署到hk，因为以前部署的好像都是用us的。不知道能不能一半是hk，一半是us，嘻嘻。

你连的ip地理位置在哪里部署时就选哪里,这样理论上是最快的,比如看youtube的时候,如果你连的ip是hk的,而你部署选的也在hk,那么相当于同城就不用再绕半个地球到美国了,这东西的原理和反代类似

**Comment by xxnet** [comment]
之前实际测试的不是这样的，google 在全球有一套神奇的网络系统，不管接入ip在哪里，TLS握手之后连接到GAE引擎的时间都极短。
