### ISSUE TITLE
[发布] 3.15.7 修复开机启动问题

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#12976]
主要改进：
+ 修复开机启动脚本问题
+ 默认PAC模式，不影响Windows Store
  老版本升级上来需要手动切换到PAC模式
+ 改进的智能路由模式，主要优化改进DNS解析模块
+ 优化升级支持
  从 3.14.x 上级上来目前还需要手动关闭系统代理，再手动启动start.vbs

暂时是测试版本

**Comment by Sharedaily** [comment]
有更新啦,支持!

**Comment by B1ran** [comment]
最近更新频率很高啊，支持一下！！！

**Comment by qhdhjb** [comment]
python环境下载只有在其他代理开启成功，能fq后才能下载，否则新版程序首次运行时报错。

**Comment by aixiu** [comment]
暂时观望， 3.14.2 目前正常，前两天升到3.15.4 升级完启动不了。报错！~！

**Comment by chenhanchia** [comment]
xx-net download python environment fail
操作系统server 2016
昨天还是好的，今天突然启动不了

**Comment by zhaoruihao** [comment]
劳模，感谢x大

**Comment by hdrafyy** [comment]
看到你就高兴，辛苦了！

**Comment by yeahwu** [comment]
复活了，露个脸！

**Comment by Sharedaily** [comment]
点个关注不迷路!

**Comment by timaxell** [comment]
最近频繁升级更新，辛苦了，非常感谢。
局域网环境下首次启动 xx-net download py环境 fail
首次启动需要互联网，但这个工具多数情况是在不能直连互联网的环境下使用的。
能否像前几次更新那样提供两个压缩包，一个含py，一个不含，各取所需。

**Comment by Litangren** [comment]
一、3.15.7系统自动更新后乱来，不停下载更新，不停打开状态页面。
二、3.15.8.zip 不能下载。

**Comment by xxnet** [comment]
> 一、3.15.7系统自动更新后乱来，不停下载更新，不停打开状态页面。
> 二、3.15.8.zip 不能下载。
>
 3.15.8 已经可以下载了。

同时Windows完整7z 版本也提供下载了。

前面测试版自动升级会造成无法启动，不能启动的请重新下载 3.15.8版本运行。

**Comment by xxnet** [comment]
已经发布 3.15.9 #12977

**Comment by hrxgg520** [comment]
怎么从旧版本升级呢？

**Comment by xxnet** [comment]
请参考wiki文档：
https://github.com/XX-net/XX-Net/wiki/Auto-update
