### ISSUE TITLE
xx-net download python environment fail

### ISSUE THREAD

**Issue by l3125831q** [XX-net/XX-Net#12974]
打开后弹出 xx-net download python environment fail

**Comment by xxnet** [comment]
先用稳定版，测试版有bug，正在调试

**Comment by xxnet** [comment]
新版 #12976 发布，解决这个问题，请测试 @l3125831q

**Comment by htpao2** [comment]
> 新版[＃12976](https://github.com/XX-net/XX-Net/issues/12976)发布，解决这个问题，请测试@ l3125831q

![捕](https://user-images.githubusercontent.com/45194070/75403086-9a053400-5941-11ea-9212-ef3c59a1c460.PNG)
后悔更了3.15.8怎么把版本切回去啊

**Comment by xxnet** [comment]
重新下载一个版本，稳定使用请下载稳定版 3.14.x

有时间请帮忙测试 3.15.9

**Comment by xxnet** [comment]
#12977

**Comment by htpao2** [comment]
3.15.9暂时没问题
![获](https://user-images.githubusercontent.com/45194070/75408756-abeed300-5951-11ea-9249-b260481237f8.PNG)

**Comment by AnyWAT** [comment]
> 后悔更了3.15.8怎么把版本切回去啊

修改 code\version.txt 的内容为欲运行的版本号后再启动程序。
