### ISSUE TITLE
GoAgent 服务端已经在 2020-02-24 07:56:35 升级到 3.3.5 版本, 请更新您的客户端。怎么回事？

### ISSUE THREAD

**Issue by xpf7622** [XX-net/XX-Net#12978]
“https://myid.appspot.com/”根据文档，我用 自己的ID更换前面url中的myid. 访问后，出现：
GoAgent 服务端已经在 2020-02-24 07:56:35 升级到 3.3.5 版本, 请更新您的客户端。
是不是xx-net 要升级到3.3.5版本的python才行。

**Comment by AnyWAT** [comment]
> 请更新您的客户端

XX-Net 不低于V 3.12.1 即可 https://github.com/XX-net/XX-Net/releases?after=3.12.10
“修复 deflate 检查，客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新”

**Comment by xpf7622** [comment]
我用的是最新的3.15.9呀。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AnyWATghost"<notifications@github.com&gt;; 
发送时间: 2020年2月27日(星期四) 下午2:48
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com&gt;; 
抄送: "阿猫"<88128971@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [XX-net/XX-Net] GoAgent 服务端已经在 2020-02-24 07:56:35 升级到 3.3.5 版本, 请更新您的客户端。怎么回事？ (#12978)



 
请更新您的客户端
  
XX-Net 不低于V 3.12.1 即可 https://github.com/XX-net/XX-Net/releases?after=3.12.10
 “修复 deflate 检查，客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新”

**Comment by SeaHOH** [comment]
所谓“请更新您的客户端”，只是一句例行公事。
