### ISSUE TITLE
启动提示：“xx-net download python environment fail”

### ISSUE THREAD

**Issue by genliu777** [XX-net/XX-Net#12984]
首先感谢xxnet group的努力，又可以过河了！

试了3.14及最新的3.15各版本，在启动start.bat时，会弹出对话框：“xx-net download python environment fail”。点击确定后，一切归于全无！亦即没有正常运行xxnet。我的系统是win7 64位。由于没有正常启动，也就没有相关的信息可以提供的了！

**Comment by lijianwei2019** [comment]
python没有下载完成

**Comment by genliu777** [comment]
> python没有下载完成

???, xxnet的包是从这里下载的，怎么会有python下载没有完成的事情呢？难道说包里没有？

**Comment by genliu777** [comment]
> python没有下载完成

额外说一句，经常用python写东西，现在我的电脑上有python3.7，64bit。

**Comment by AnyWAT** [comment]
貌似 XX-Net 只支持 Python Version 2.7.17（V3.14.1才更新不久，以往更低）

> ???, xxnet的包是从这里下载的，怎么会有python下载没有完成的事情呢？难道说包里没有？

V3.15.2（及以后版本？）更新：提供完全版打包下载和精简版链接
.7z——完全版？
.zip——精简版？
V3.15.0 新版改动：
精简安装包
删除内置的python运行环境，Windows环境下在第一次启动时下载安装.

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/releases?after=3.15.1

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/releases?after=3.15.1

**Comment by sd613** [comment]
我也是同样问题，在github下载的安装包里没有发现python文件夹。后来把以前老版本的XXNET里的python文件夹复制过去就OK了。不知道这是下载文件故意如此还是BUG?

**Comment by lijianwei2019** [comment]
@genliu777 @sd613 是故意的。为了减少安装包体积，启动后自动下载python2.7环境文件。

**Comment by sd613** [comment]
这样会产生一个问题，有可能python的下载链接因为需要翻qiang而无法下载，而GITHUB是可以不用翻就能上的。

**Comment by lijianwei2019** [comment]
@sd613 是的。所以作者又编译了7z版本。现在有两个版本。一个是含python。另一个是精简版。

**Comment by genliu777** [comment]
> @sd613 是的。所以作者又编译了7z版本。现在有两个版本。一个是含python。另一个是精简版。

点击7z版本下载，网页打不开

**Comment by lijianwei2019** [comment]
@genliu777 我这里电信正常下载。

**Comment by genliu777** [comment]
> 我也是同样问题，在github下载的安装包里没有发现python文件夹。后来把以前老版本的XXNET里的python文件夹复制过去就OK了。不知道这是下载文件故意如此还是BUG?

下载的3.15.10版本，在\XX-Net-3.15.10\code\default文件夹中有python27文件夹，但还是遇到同样的问题。即使用你这个办法，从老版本，比如3.12版中拷贝python27过来覆盖，也是无济于事！

**Comment by AnyWAT** [comment]
貌似缺失的是新目录 Z:\XX-Net\python27 文件夹？

**Comment by AnyWAT** [comment]
>20M 的新目录 Z:\XX-Net\python27 文件夹

**Comment by genliu777** [comment]
没办法，只能用平板下载7z版的，现在可以了！

**Comment by jessicapd2020** [comment]
我也遇到了这个问题。有人解决了吗？

**Comment by xxnet** [comment]
出现这个问题都是Win7的系统吗？有没有更新到最新补丁？

**Comment by xxnet** [comment]
还不能启动的试试这个链接：
https://github.com/XX-net/XX-Net/releases/download/3.15.10/XX-Net-3.15.10.7z

**Comment by B1ran** [comment]
有这个问题的可以尝试下载完整版，然后把和start.bat同目录中的python27目录复制到对应目录再启动应该就正常了（注意：不是code目录下的python27）。btw，我是win10并安装了python3.7.1

**Comment by jessicapd2020** [comment]
I had download the version 7z and it works. Sorry that I might download the lit version which cause the problem. Thanks for your help!

发件人: Michael.X [mailto:notifications@github.com]
发送时间: 2020年3月3日 12:48
收件人: XX-net/XX-Net
抄送: Lina Zhou; Comment
主题: Re: [XX-net/XX-Net] 启动提示：“xx-net download python environment fail” (#12984)

出现这个问题都是Win7的系统吗？有没有更新到最新补丁？

**Comment by jessicapd2020** [comment]
Thanks!

发件人: B1ran [mailto:notifications@github.com]
发送时间: 2020年3月3日 15:09
收件人: XX-net/XX-Net
抄送: Lina Zhou; Comment
主题: Re: [XX-net/XX-Net] 启动提示：“xx-net download python environment fail” (#12984)


有这个问题的可以尝试下载完整版，然后把和start.bat同目录中的python27目录复制到对应目录再启动应该就正常了（注意：不是code目录下的python27）。btw，我是win10并安装了python3.7.1
