### ISSUE TITLE
关于IPV6

### ISSUE THREAD

**Issue by faintfigure** [XX-net/XX-Net#12989]
电信的光纤宽带，已开通IPV6，通过超级管理员密码在光猫里已开启IPv6。
在路由器里开通IPv6时可获得原生IPV6，XXNET的GAE前端有效IPV6 IP数为零。如果路由器里关了V6，有效数就上来了。问是否开启IPV6？

**Comment by chinaniupai** [comment]
路由器里关了V6，有效数就上来了？？？关了v6还哪来的v6的IP？难道是隧道？

**Comment by xxnet** [comment]
请贴出两个状态下GAE的状态信息

**Comment by SeaHOH** [comment]
原生优先级大于隧道，那样好用就那样。
