### ISSUE TITLE
求助一下各位，新版xx-net，选择smart-router模式，显示很多资源未加载，怎么办呢。

### ISSUE THREAD

**Issue by liamhui** [XX-net/XX-Net#12982]
[https://imgchr.com/i/3sQ854](url)
[https://imgchr.com/i/3sQ854](url)

这是图片，各位可以看看。

**Comment by xxnet** [comment]
智能路由模块的域名解析还有问题，正在改进中。

**Comment by liamhui** [comment]
嗯嗯，好的

**Comment by xxnet** [comment]
刚发布了 3.15.10 ，请下载测试

看看能否解决你的问题。
如果问题依旧，请把智能路由的日志发给 xxnet.dev@gmail.com 分析

**Comment by yeezylife** [comment]
smart-router一直上不去reddit。。

**Comment by liamhui** [comment]
感谢！
