### ISSUE TITLE
xxnet开了一个小时都没有扫到ip，线程数开的200

### ISSUE THREAD

**Issue by xianyu1919810** [XX-net/XX-Net#12998]
附上一部分日志
Mar 06 10:16:06.478 - [WARNING] no enough ip

Mar 06 10:16:56.951 - [DEBUG] create ssl timeout fail.

Mar 06 10:16:56.955 - [WARNING] no enough ip

Mar 06 10:16:57.102 - [DEBUG] create ssl timeout fail.

Mar 06 10:16:57.102 - [DEBUG] GAE_Exception 1 'no ssl_sock'

Mar 06 10:16:57.102 - [WARNING] get worker fail:GAE_Exception()

Mar 06 10:16:57.102 - [DEBUG] response_fail:get worker fail:GAE_Exception()

Mar 06 10:16:57.103 - [DEBUG] GAE_Exception 601 'fetch gae fail:601'

Mar 06 10:16:57.103 - [WARNING] gae_exception:GAE_Exception() https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

Mar 06 10:16:57.103 - [DEBUG] GAE_Exception 600 'gae_exception:GAE_Exception() https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt'

Mar 06 10:16:57.104 - [WARNING] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt request fail:GAE_Exception()

Mar 06 10:16:57.105 - [WARNING] pac_update download gfwlist fail:HTTPError()

Mar 06 10:16:57.455 - [WARNING] no enough ip

Mar 06 10:16:57.957 - [WARNING] no enough ip

Mar 06 10:16:58.456 - [WARNING] no enough ip

Mar 06 10:16:58.957 - [WARNING] no enough ip

Mar 06 10:16:59.457 - [WARNING] no enough ip

Mar 06 10:16:59.963 - [WARNING] no enough ip

Mar 06 10:17:00.463 - [WARNING] no enough ip

Mar 06 10:17:00.964 - [WARNING] no enough ip

Mar 06 10:17:01.464 - [WARNING] no enough ip

Mar 06 10:17:01.965 - [WARNING] no enough ip

Mar 06 10:17:02.465 - [WARNING] no enough ip

Mar 06 10:17:56.954 - [DEBUG] create ssl timeout fail.

Mar 06 10:17:56.955 - [WARNING] no enough ip

Mar 06 10:17:57.455 - [WARNING] no enough ip

Mar 06 10:17:57.955 - [WARNING] no enough ip

Mar 06 10:17:58.455 - [WARNING] no enough ip

Mar 06 10:17:58.955 - [WARNING] no enough ip

Mar 06 10:17:59.455 - [WARNING] no enough ip

Mar 06 10:17:59.955 - [WARNING] no enough ip

Mar 06 10:18:00.455 - [WARNING] no enough ip

Mar 06 10:18:00.955 - [WARNING] no enough ip

Mar 06 10:18:01.469 - [WARNING] no enough ip

Mar 06 10:18:01.969 - [WARNING] no enough ip

Mar 06 10:18:02.472 - [WARNING] no enough ip

Mar 06 10:18:02.972 - [WARNING] no enough ip

Mar 06 10:18:03.475 - [WARNING] no enough ip

Mar 06 10:18:03.975 - [WARNING] no enough ip

Mar 06 10:18:04.476 - [WARNING] no enough ip

Mar 06 10:18:04.976 - [WARNING] no enough ip

Mar 06 10:18:05.476 - [WARNING] no enough ip

Mar 06 10:18:05.977 - [WARNING] no enough ip

Mar 06 10:18:06.476 - [WARNING] no enough ip

Mar 06 10:18:56.956 - [DEBUG] create ssl timeout fail.

Mar 06 10:18:56.960 - [WARNING] no enough ip

Mar 06 10:18:57.460 - [WARNING] no enough ip

Mar 06 10:18:57.960 - [WARNING] no enough ip

Mar 06 10:18:58.460 - [WARNING] no enough ip

Mar 06 10:18:58.960 - [WARNING] no enough ip

Mar 06 10:18:59.460 - [WARNING] no enough ip

Mar 06 10:18:59.961 - [WARNING] no enough ip

Mar 06 10:19:00.461 - [WARNING] no enough ip

Mar 06 10:19:00.961 - [WARNING] no enough ip

Mar 06 10:19:20.705 - [INFO] PAC from:127.0.0.1:57935 GET /proxy.pac

Mar 06 10:19:20.710 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('F:\\Astar VPN1.0.3\\XX-Net-3.2.9\\data\\gae_proxy\\proxy.pac')

Mar 06 10:19:21.710 - [WARNING] pac_update download gfwlist fail:URLError(error(10061, ''),)

Mar 06 10:19:56.959 - [DEBUG] create ssl timeout fail.

Mar 06 10:19:56.960 - [WARNING] no enough ip

Mar 06 10:19:57.460 - [WARNING] no enough ip

Mar 06 10:19:57.964 - [WARNING] no enough ip

Mar 06 10:19:58.465 - [WARNING] no enough ip

Mar 06 10:19:58.965 - [WARNING] no enough ip

Mar 06 10:19:59.465 - [WARNING] no enough ip

Mar 06 10:19:59.966 - [WARNING] no enough ip

Mar 06 10:20:00.467 - [WARNING] no enough ip

Mar 06 10:20:00.968 - [WARNING] no enough ip

Mar 06 10:20:01.470 - [WARNING] no enough ip

Mar 06 10:20:01.969 - [WARNING] no enough ip

Mar 06 10:20:02.470 - [WARNING] no enough ip

Mar 06 10:20:02.971 - [WARNING] no enough ip

Mar 06 10:20:03.471 - [WARNING] no enough ip

Mar 06 10:20:03.974 - [WARNING] no enough ip

Mar 06 10:20:04.475 - [WARNING] no enough ip

Mar 06 10:20:04.976 - [WARNING] no enough ip

Mar 06 10:20:05.478 - [WARNING] no enough ip

Mar 06 10:20:05.978 - [WARNING] no enough ip

Mar 06 10:20:06.478 - [WARNING] no enough ip

Mar 06 10:20:56.975 - [DEBUG] create ssl timeout fail.

Mar 06 10:20:56.977 - [WARNING] no enough ip

Mar 06 10:20:57.478 - [WARNING] no enough ip

Mar 06 10:20:57.980 - [WARNING] no enough ip

Mar 06 10:20:58.480 - [WARNING] no enough ip

Mar 06 10:20:58.981 - [WARNING] no enough ip

Mar 06 10:20:59.481 - [WARNING] no enough ip

Mar 06 10:20:59.981 - [WARNING] no enough ip

Mar 06 10:21:00.481 - [WARNING] no enough ip

Mar 06 10:21:00.994 - [WARNING] no enough ip

Mar 06 10:21:01.494 - [WARNING] no enough ip

Mar 06 10:21:01.994 - [WARNING] no enough ip

Mar 06 10:21:02.495 - [WARNING] no enough ip

Mar 06 10:21:03.002 - [WARNING] no enough ip

Mar 06 10:21:03.502 - [WARNING] no enough ip

Mar 06 10:21:04.008 - [WARNING] no enough ip

Mar 06 10:21:04.513 - [WARNING] no enough ip

Mar 06 10:21:05.013 - [WARNING] no enough ip

Mar 06 10:21:05.513 - [WARNING] no enough ip

Mar 06 10:21:06.013 - [WARNING] no enough ip

Mar 06 10:21:06.523 - [WARNING] no enough ip

Mar 06 10:21:56.977 - [DEBUG] create ssl timeout fail.

Mar 06 10:21:56.978 - [WARNING] no enough ip

Mar 06 10:22:56.978 - [DEBUG] create ssl timeout fail.

Mar 06 10:22:56.980 - [WARNING] no enough ip

Mar 06 10:22:57.504 - [WARNING] no enough ip

Mar 06 10:22:58.004 - [WARNING] no enough ip

Mar 06 10:22:58.504 - [WARNING] no enough ip

Mar 06 10:22:59.004 - [WARNING] no enough ip

Mar 06 10:22:59.504 - [WARNING] no enough ip

Mar 06 10:23:00.004 - [WARNING] no enough ip

Mar 06 10:23:00.504 - [WARNING] no enough ip

Mar 06 10:23:01.004 - [WARNING] no enough ip

Mar 06 10:23:01.504 - [WARNING] no enough ip

Mar 06 10:23:02.004 - [WARNING] no enough ip

Mar 06 10:23:02.506 - [WARNING] no enough ip

Mar 06 10:23:03.030 - [WARNING] no enough ip

Mar 06 10:23:03.530 - [WARNING] no enough ip

Mar 06 10:23:04.030 - [WARNING] no enough ip

Mar 06 10:23:04.536 - [WARNING] no enough ip

Mar 06 10:23:05.036 - [WARNING] no enough ip

Mar 06 10:23:05.536 - [WARNING] no enough ip

Mar 06 10:23:06.036 - [WARNING] no enough ip

Mar 06 10:23:06.536 - [WARNING] no enough ip

Mar 06 10:23:56.980 - [DEBUG] create ssl timeout fail.

Mar 06 10:24:56.980 - [DEBUG] create ssl timeout fail.

Mar 06 10:24:56.981 - [WARNING] no enough ip

Mar 06 10:24:57.481 - [WARNING] no enough ip

Mar 06 10:24:57.982 - [WARNING] no enough ip

Mar 06 10:24:58.485 - [WARNING] no enough ip

Mar 06 10:24:58.983 - [WARNING] no enough ip

Mar 06 10:24:59.484 - [WARNING] no enough ip

Mar 06 10:24:59.985 - [WARNING] no enough ip

Mar 06 10:25:00.519 - [WARNING] no enough ip

Mar 06 10:25:01.018 - [WARNING] no enough ip

Mar 06 10:25:01.518 - [WARNING] no enough ip

Mar 06 10:25:02.018 - [WARNING] no enough ip

Mar 06 10:25:02.518 - [WARNING] no enough ip

Mar 06 10:25:03.018 - [WARNING] no enough ip

Mar 06 10:25:03.518 - [WARNING] no enough ip

Mar 06 10:25:04.021 - [WARNING] no enough ip

Mar 06 10:25:04.521 - [WARNING] no enough ip

Mar 06 10:25:05.021 - [WARNING] no enough ip

Mar 06 10:25:05.521 - [WARNING] no enough ip

Mar 06 10:25:06.021 - [WARNING] no enough ip

Mar 06 10:25:06.528 - [WARNING] no enough ip

Mar 06 10:25:56.980 - [DEBUG] create ssl timeout fail.

Mar 06 10:25:56.984 - [WARNING] no enough ip

Mar 06 10:25:57.484 - [WARNING] no enough ip

Mar 06 10:25:57.984 - [WARNING] no enough ip

Mar 06 10:26:27.336 - [INFO] PAC from:127.0.0.1:58487 GET /proxy.pac

Mar 06 10:26:27.341 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('F:\\Astar VPN1.0.3\\XX-Net-3.2.9\\data\\gae_proxy\\proxy.pac')

Mar 06 10:26:28.430 - [WARNING] pac_update download gfwlist fail:URLError(error(10061, ''),)

**Comment by xianyu1919810** [comment]
系统参数
XX-Net Version | 3.2.9
-- | --
Python Version | 2.7.11
OpenSSL Version | 16.0.0 TLSv1_2 h2:alpn
System Platform | AMD64, Windows-7-6.1.7601-SP1
OS System | Windows
OS Version | 6.1.7601
OS Release | 7
OS Detail | Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Language | zh_CN
Architecture | 32bit,WindowsPE
Browser | Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.6788.400 QQBrowser/10.3.2816.400

**Comment by hubsocks** [comment]
扫描设置里面的IP 段列表改为:
https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/gae_proxy/local/ip_range.txt
里面的内容.
IP 模式为仅ipv4

**Comment by xxnet** [comment]
该升级了 3.2.9 太老了

**Comment by xianyu1919810** [comment]
可以发一个百度云或者蓝奏云链接吗？我的压缩包下载全是损坏的，谢谢！

**Comment by xxnet** [comment]
3.15.10 Windows版本文件下载后多大？


可以试试mac版本，下载包很小，不过不确定后面能否下载到py27环境，都试试吧

**Comment by xianyu1919810** [comment]
1.33mb，两个都是，而且Python27环境下载都是失败

**Comment by xianyu1919810** [comment]
1.33mb，两个都是，而且Python27环境下载都是失败

**Comment by xianyu1919810** [comment]
1.33mb，两个都是，而且Python27环境下载都是失败

**Comment by xxnet** [comment]
这个地址能下载到吗？
https://github.com/XX-net/XX-Net/releases/download/3.15.10/XX-Net-3.15.10.7z
