### ISSUE TITLE
关了路由里ipv6就偶尔能扫到IPV6，开了就扫不到，而且今天ipv4 ip越来越少

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#12992]
这是开了之后的
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
xxnet-version: 3.15.10

python-version: 2.7.17
openssl-version: 19.1.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:16 ipv4:16 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:3
scan-ip-thread-num: 10
ip-quality: 784
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by LN-VIVI** [comment]
@xxnet

**Comment by LN-VIVI** [comment]
关了之后的XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.18362
os-system: Windows
os-version: 10.0.18362
os-release: 10
os-detail: Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
xxnet-version: 3.15.10

python-version: 2.7.17
openssl-version: 19.1.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:51 ipv4:12 ipv6:25
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:3
scan-ip-thread-num: 20
ip-quality: 1251
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
第二个状态能扫描到ipv6，但是速度没有地一个好？
两个状态里IPV6都是OK。

猜测：
1. 你机器上装了teredo，所以关了路由器的ipv6，依然有ipv6，可以扫描到ipv6，但是teredo 速度比较慢
2. 开了路由器ipv6，猜测优先级比teredo高，所以ipv6走了原生路由器的，但是被GFW封了

你可以开cmd窗口，执行
ipconfig /all 看有没有teredo网卡

**Comment by LN-VIVI** [comment]
> 第二个状态能扫描到ipv6，但是速度没有地一个好？ 两个状态里IPV6都是OK。 猜测： 1. 你机器上装了teredo，所以关了路由器的ipv6，依然有ipv6，可以扫描到ipv6，但是teredo 速度比较慢 2. 开了路由器ipv6，猜测优先级比teredo高，所以ipv6走了原生路由器的，但是被GFW封了 你可以开cmd窗口，执行 ipconfig /all 看有没有teredo网卡

有的 
隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:c38c:。。。。。。。a(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::1071:93ce:2。。。。。(首选)
   默认网关. . . . . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 218103801
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-25-4B-78-7B-F7-75-A4-04-34-6E
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

**Comment by LN-VIVI** [comment]
有的今天ipv4 ip只有4

   主机名  . . . . . . . . . . . . . : LAPTOP
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : lan

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . : lan
   描述. . . . . . . . . . . . . . . : Realtek PCIe GbE Family Controller
   物理地址. . . . . . . . . . . . . : F8-75-A4-04-34-6E
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::ec52:.......e%17(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.123.6(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2020年3月7日 14:48:34
   租约过期的时间  . . . . . . . . . : 2020年3月8日 14:48:34
   默认网关. . . . . . . . . . . . . : 192.168.123.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.123.1
   DHCPv6 IAID . . . . . . . . . . . : 1169463
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-25-4B-78-7B-F8-75-A4-04-34-6E
   DNS 服务器  . . . . . . . . . . . : 192.168.123.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

无线局域网适配器 WLAN:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : lan
   描述. . . . . . . . . . . . . . . : Intel(R) Wireless
   物理地址. . . . . . . . . . . . . : 7C-B2-7D-F9-B0-E6
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   物理地址. . . . . . . . . . . . . : 7C-B2-7D-F9-B0-E8
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   物理地址. . . . . . . . . . . . . : 7E-B2-7D-F9-B0-E6
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 蓝牙网络连接 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network) #2
   物理地址. . . . . . . . . . . . . : 7C-B2-7D-F9-B0-E9
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:c38c........b5:9e1b(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::148c:d4.............e1b%14(首选)
   默认网关. . . . . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 218103808
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-25-4B-78-7B-F8-75-A4-04-34-6E
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用
@xxnet

**Comment by SeaHOH** [comment]
整体如此，不是你个人原因。
