### ISSUE TITLE
XX-Net 3.15.10  一切正常, 十分感谢开发者

### ISSUE THREAD

**Issue by miketwes** [XX-net/XX-Net#12999]
![2020-03-06_579x758](https://user-images.githubusercontent.com/6849681/76050316-f8fe2500-5fa1-11ea-8752-5567f4d1e07e.png)

**Comment by ShadowEmbrace** [comment]
看了你的反馈之后我升级了，升级之前ipv4掉到了20（昨天是100），升级之后46，我感觉我又要把ipv6隧道开起来了~

**Comment by zhencaihao** [comment]
我这里昨天还是100的，今天早上打开就变成只有5、6个ip了，到现在也才只有33个。

**Comment by xianyu1919810** [comment]
可以发个云盘链接吗？我这里下载包都是坏的，谢谢铁汁

**Comment by hdrafyy** [comment]
这个是安卓版的吗？

**Comment by zhaoruihao** [comment]
今天可用ip骤降

**Comment by hrxgg520** [comment]
为什么我用这个版本扫描不到ip呢？

**Comment by Alobe007** [comment]
> 今天可用ip骤降

确实。

**Comment by xxnet** [comment]
要准备备用方案了

**Comment by pch9527** [comment]
最近这几天ipv4可用数  突然将至个位数  墙外网站加载图片都变得很慢。。。
