### ISSUE TITLE
下载后无法运行

### ISSUE THREAD

**Issue by 100725** [XX-net/XX-Net#12993]
win7.   尝试下载了xx-net3.15.10.7z 、3.15.10.5z都无法运行，点击运行后都闪出这个就没了（录屏后截的图）
![0](https://user-images.githubusercontent.com/61739298/75776458-0a231800-5d8f-11ea-9740-714cc553f910.PNG)

**Comment by Sharedaily** [comment]
实在没办法就用旧版本,目前3.14版是很稳定的,.

**Comment by xxnet** [comment]
看上去系统把vbs给禁用了

**Comment by 100725** [comment]
@xxnet 那怎么解决，求教

**Comment by 100725** [comment]
试了3.14情况一样

**Comment by 100725** [comment]
已解决，感谢

**Comment by xxnet** [comment]
怎么解决的，分享一下

**Comment by 100725** [comment]
我解压出的错，真不好意思，打扰了------------------ 原始邮件 ------------------
发件人: "Michael.X"<notifications@github.com>
发送时间: 2020年3月5日(星期四) 上午9:01
收件人: "XX-net/XX-Net"<XX-Net@noreply.github.com>;
抄送: "100725"<3380743642@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [XX-net/XX-Net] 下载后无法运行 (#12993)


怎么解决的，分享一下 
 
&mdash;
