### ISSUE TITLE
PHP 代理支持

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13]
为了访问某些屏蔽GAE代理的网站，找PHP空间搭一个PHP代理。

把PHP模块加回来。

**Comment by newcastlecy** [comment]
建议 添加 PHP 代理支持

**Comment by xxnet** [comment]
PHP版支持也不那么难，但是要融合进去，并且可扩增，正在设计一套更好的方案。
或许先上一个简单的方案，完整的方案后面再出吧。
  PHP先独立一个端口，在浏览器里用SwitchyProxy来设定规则切换。

**Comment by newcastlecy** [comment]
可以，目前有些网站屏蔽GAE，像原版有8088这个端口，SwitchyProxy可以配置

**Comment by xxnet** [comment]
已经实现
