### ISSUE TITLE
NewSensation网站的视频流无法播放

### ISSUE THREAD

**Issue by ArchNew** [XX-net/XX-Net#130]
我试了一下，Youtube什么的都能正常播放视频，就是NewSensation的无法播放。严格来讲，视频播放按键都无法点击。网站地址：http://www.newsensations.com/tour_ns/index.php （警告：是成人网站）
我用的是今天新下的XX-NET，操作系统是win7，浏览器是Chrome

**Comment by fhzyfjy** [comment]
无法看视频是XX的一个顽疾。目前作者还无法解决。其实大部分人都是想用该软件看视频的。

**Comment by xxnet** [comment]
刚才试了下，可以播放，可能在新版里已经修复，请测试
