### ISSUE TITLE
感谢开发者，但是microsoft账户登录、更新3.15时候有问题

### ISSUE THREAD

**Issue by Ja1Zhou** [XX-net/XX-Net#13006]
第一个问题是在gae proxy状态下试图登录microsoft账户时候，即使密码是对的也会无法登录 而关闭代理则解决问题

另一个问题是，windows通过复制整个XX-net文件夹使用的XX-net在local配置页面更新之后直接无法启动了，start.vbs失效

**Comment by xxnet** [comment]
第一个问题是兼容性，先手动处理，以后方向是改进smart_router，做到自动处理。

第二个问题，从理论上XX-Net整个文件夹是可以移动的，之前出现过目录中有中文或者空格出问题，你先检查一下

**Comment by Ja1Zhou** [comment]
明白了，是用户名空格的问题，谢谢~
