### ISSUE TITLE
X-tunnel一直无法登陆

### ISSUE THREAD

**Issue by brightp125** [XX-net/XX-Net#13012]
1.X-tunnel一直无法登陆，而且一直显示的是请稍后
2.正常启用之后，访问Google很慢，根本没有办法上YouTube
3.关于代理插件我感觉没有起到很大的用处
（本人小白，如果问的问题有违反什么规则的话请见谅，也希望了解的大神朋友们帮帮我）

**Comment by anothersin** [comment]
刚买了一年，感觉还不如免费的

**Comment by brightp125** [comment]
> 刚买了一年，感觉还不如免费的

why？咋回事，不会吧

**Comment by anothersin** [comment]
> > 刚买了一年，感觉还不如免费的
> 
> why？咋回事，不会吧

比较慢 今天下午到现在都连不上

**Comment by hzx505** [comment]
刚刚买了3个月 可看 youtube

**Comment by ShadowEmbrace** [comment]
免费的昨晚开始也很慢了，ip都快没了
