### ISSUE TITLE
请教win10 原生ipv6情况下 teredo隧道问题

### ISSUE THREAD

**Issue by Ja1Zhou** [XX-net/XX-Net#13010]
如题，我有原生ipv6地址，不过也启用了teredo，但是一直是休眠状态
test-ipv6.com告诉我我的运营商是原生ipv6运营商，而非teredo隧道
请问这种情况下想用ipv6 ip一定要禁用原来的ipv6服务嘛？
或者怎么解决呢？

**Comment by SeaHOH** [comment]
原生优先级大于隧道，所以 teredo 会休眠。自己按需选用即可。
