### ISSUE TITLE
部署服务器失败

### ISSUE THREAD

**Issue by git-light** [XX-net/XX-Net#13016]
在网页http://localhost:8085/?module=gae_proxy&menu=deploy部署，没有任何反应

根据手册到code\default\gae_proxy\server目录下运行uploader.bat “appid” -debug
但是发现，..\..\python27\1.0\python.exe 文件不存在，报错如下：
'..\..\python27\1.0\python.exe' 不是内部或外部命令，也不是可运行的程序

进入..\..\python27\1.0目录查看，只有lib目录，没有exe文件

从较早版本XX-Net-3.13.1拷贝对应python.exe到对应目录，依然报错，报错信息如下：
ImportError: No module named site

请大神帮忙看下，是否python.exe 1.0的下载出了问题，还是哪里的问题

**Comment by git-light** [comment]
问题已经找到了，就是更新lib.zip的问题，按照日志报错下载3.15.0版本的lib.zip拷贝到data\downloads目录，然后再运行deploy就可以部署了，虽然现在还是报错，但是是代理网络太慢的原因，这个问题后面应该能解决

**Comment by xxnet** [comment]
确认bug。
bat的python路径没有更新，已经改好提交代码了
