### ISSUE TITLE
华为中兴动作好快.

### ISSUE THREAD

**Issue by hubsocks** [XX-net/XX-Net#13017]
已公开的ipv4封了.没公开的继续可以用.也可能是因为是晚上时段的原因

**Comment by ablebodied** [comment]
这两天ipv4数量明显下降，不知道过段时间是不是又没了

**Comment by bluesdog** [comment]
前天1300，今天130，明天估计13。
永远这样，来多少杀多少，还是继续用VPN吧。

**Comment by SeaHOH** [comment]
毫无意义，请不要把这里当作胡乱发泄的场所。

**Comment by maoxt** [comment]
> 
> 
> 已公开的ipv4封了.没公开的继续可以用.也可能是因为是晚上时段的原因

一样 一个ip都没有了 😔
