### ISSUE TITLE
xxnet 不能上instagram和pornhub

### ISSUE THREAD

**Issue by tofu23** [XX-net/XX-Net#13015]
这个是一直存在的问题，IG的官网首页能刷，但如果你要点进某个人主页，他就会显示502，偶尔运气好能出来，不过几率为0.01大概。。P站是完全进不去。
IG还可以用扩展解决，但是P站有解决办法吗？
另外最近几天越来越难翻了，要等超久才能连上，哭泣。
谢谢

**Comment by 2609665** [comment]
如果是用自己的appid部署的完全没问题，公用的就不清楚了（视频类的应该是不行吧）。

**Comment by Sharedaily** [comment]
公用的不能进入任意视频网站和耗流量大的图片网站.
我试了,自己部署的话完全没问题的

**Comment by tofu23** [comment]
> 公用的不能进入任意视频网站和耗流量大的图片网站.
> 我试了,自己部署的话完全没问题的

不行啊 我自己部署的也不行 但是可以看youtube。一直都这样 我是移动 不知道这是不是原因。

**Comment by 2609665** [comment]
那也可能SwitchyOmega规则设置的问题吧   XX全局试试看能不能打开

**Comment by liamcos** [comment]
> IG还可以用扩展解决

请问是哪个拓展解决的？

**Comment by ablebodied** [comment]
我的pornhub也不行，能上但是视频看不了，自己的id

**Comment by SeaHOH** [comment]
Duplicate of #12987 #13002
