### ISSUE TITLE
appid部署问题求助

### ISSUE THREAD

**Issue by 100725** [XX-net/XX-Net#13011]
官方教程里没有出现需要启用结算功能，但我跳不过去。
![1](https://user-images.githubusercontent.com/61739298/76157811-3d77f500-6149-11ea-9ee6-0a4c1860f319.png)

![2](https://user-images.githubusercontent.com/61739298/76157877-66e55080-614a-11ea-8bb5-b80657e6aa82.png)

![3](https://user-images.githubusercontent.com/61739298/76157901-a4e27480-614a-11ea-83b4-17c2bbde5a15.png)

本人无信用卡，也无银行账户

**Comment by 100725** [comment]
已解决，无需回复我。
若需要请将此贴删除，或告诉我怎么删。谢谢。

**Comment by brightp125** [comment]
怎么解决的呢，我也有同样的困惑

**Comment by 100725** [comment]
我认为不用管它，直接把APPID复制去xxnet部署

**Comment by 100725** [comment]
![捕获](https://user-images.githubusercontent.com/61739298/76160154-a455d800-6162-11ea-8932-2a78383179c0.PNG)

抱歉我没注意到这个。em，请问用没绑信用卡的appid捐赠以获取X-Tunnel流量的方式可行吗

**Comment by Ja1Zhou** [comment]
绑定信用卡的意思是一定要启用，官方教程感觉比较老了

**Comment by qhdhjb** [comment]
到这一步足够了，关掉当前窗口，已经可以使用了

**Comment by 100725** [comment]
是有点老了，界面和步骤顺序不大一样。不想另开帖子了。就在这里问一下，看了置顶我似乎得去给我的上个issue打个已解决的label，奈何实在是找不到在哪打，有人知道吗

**Comment by 100725** [comment]
在白天的时候不管是之前公用的还是我刚刚申请的appid都网页不怎么打得开，晚上却比较流畅，是不是哪里落了什么。（以及，我没开IPv6。）

**Comment by 100725** [comment]
> 到这一步足够了，关掉当前窗口，已经可以使用了

的确，已试可用，感谢。

**Comment by 100725** [comment]
APPID属性里有“工作”和“无效”，“”无效“”是指我得重新部署 ，还是说appid会自动轮换，现在没用上。

**Comment by qhdhjb** [comment]
新开通的appid吗？如果是新的应该是要部署的，开启ssr,保证能fq,打开部署页面，重新部署，很快会部署成功。填入自己的appid就可以了

**Comment by 100725** [comment]
我一次性八个一起部署和保存总是弄不上去，只好只存两个，然后有时两个都工作，有时一个工作一个无效。无效那个要重新部署吗。

**Comment by brightp125** [comment]
这个需要用ssr吗，在哪？ Biai Kau 邮箱：brightp545@gmail.com 签名由 网易邮箱大师 定制 在2020年03月08日 21:01，qhdhjb 写道： 新开通的appid吗？如果是新的应该是要部署的，开启ssr,保证能fq,打开部署页面，重新部署，很快会部署成功。填入自己的appid就可以了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by qhdhjb** [comment]
不管什么工具，先要能fq，然后才能部署

**Comment by SeaHOH** [comment]
不用部署，留空使用公共 ID 即可。

**Comment by hhhhhhpk** [comment]
> 到这一步足够了，关掉当前窗口，已经可以使用了

不行……到这一步回头点开还是没有部署。

**Comment by 100725** [comment]
部署服务端显示部署完成后，在配置那里又说是“”无效的AppID“，重新部署试了几遍还是没用。目前只有我的第一个AppID能用。访问【假设你的appid是 myid  用浏览器通过GAE_Proxy代理访问 myid.appspot.com”】说的网址也只有第一个才有正确反馈

**Comment by 100725** [comment]
完成的部署日志总出现这个2020-03-10 13:04:22,059 - root - INFO - Deploy failed appid list:
