### ISSUE TITLE
xx-net又被封了？

### ISSUE THREAD

**Issue by zqchina** [XX-net/XX-Net#13028]
上海，长城宽带，前两天开始IPV4归0，IPV6还能用，昨天开始IPV6也不行了，连接池归0，呜呼！！！

**Comment by xxnet** [comment]
GAE 没ip就用X-Tunnel，免费用户每天100M流量，有能力就赶快买套餐，准备涨价了。
提高价格一方面可以使用更好的服务器资源，保证服务质量，另一方面也是为了支持免费用户。

**Comment by lefantian** [comment]
黑龙江电信还好， 两种ip都有两位数尚且可用

**Comment by AeneasZhu** [comment]
> GAE 没ip就用X-Tunnel，免费用户每天100M流量，有能力就赶快买套餐，准备涨价了。 提高价格一方面可以使用更好的服务器资源，保证服务质量，另一方面也是为了支持免费用户。

敢问x-tunnel支持RMB支付吗？没有美刀

**Comment by AeneasZhu** [comment]
> 黑龙江电信还好， 两种ip都有两位数尚且可用

貌似各地电信的GAE IP都比较给力

**Comment by xxnet** [comment]
注册paypal消费可自动换美刀，paypal是全世界最早和最大的支付平台。
