### ISSUE TITLE
X-TUNNEL可登录，但是基本无速度

### ISSUE THREAD

**Issue by Tiebat** [XX-net/XX-Net#13030]
X-TUNNEL是可以登录的，但是基本没有速度，什么都打不开。用的最新版本。坐标是在010地区。家用300M的光纤。问问大家是不是也有这种情况？

**Comment by mochen91** [comment]
一样，021，祖国大地一片红

**Comment by 2handshake** [comment]
028一样

**Comment by xxnet** [comment]
新版在路上了，给收费用户一个单独的服务器ip，晚点发布

**Comment by xxnet** [comment]
可以登录但没有速度的看过来，新版改进对收费用户有改进。
#13034

这个版本改进稳定性，下一个大版本再改进性能。

**Comment by mochen91** [comment]
> 可以登录但没有速度的看过来，新版改进对收费用户有改进。
> #13034
> 
> 这个版本改进稳定性，下一个大版本再改进性能。

Cloudflare前端还是一片红，但能动。红多绿少。

**Comment by ncmon** [comment]
> 可以登录但没有速度的看过来，新版改进对收费用户有改进。
> #13034
> 
> 这个版本改进稳定性，下一个大版本再改进性能。

新版本发布了吗   用tunnel延迟还是很高啊  有时候返回数都是3万多看360P都很卡

**Comment by pch9527** [comment]
我这边X-Tunnel的速度并不比GAE快多少  还是V2Ray用得省心
