### ISSUE TITLE
[发布] 3.16.0 更新TLS-Relay

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13034]
本次更新为X-Tunnel模块的TLS-Relay前端协议进行改进，增加稳定性。
性能后面再进行改进。

建议付费用户更新到最新版本。

**Comment by iSuperYang** [comment]
新版本 win10自带杀毒软件会报毒

**Comment by faintfigure** [comment]
已经更新3.16.0，但是目前前端主要还是走的Cloudflare，GAE前端不走流量，IPV6是fail；手机端IPV6可用，有效数很多，同样在一个内网条件下，请问是Teredo服务器设置的问题吗？

**Comment by pch9527** [comment]
赶紧修复一下无法部署的BUG吧   3.14.1的问题又重现了

**Comment by MaxYe0725** [comment]
3.16.0更新后，x-tunnel无法登陆status：602

**Comment by xxnet** [comment]
请把 x-tunnel 的状态和日志发 xxnet.dev@gmail.com

**Comment by pshendelzare01** [comment]
> 赶紧修复一下新版本无法部署的BUG吧 3.14.1的问题又重现了

部署不了

**Comment by pch9527** [comment]
> > 赶紧修复一下新版本无法部署的BUG吧 3.14.1的问题又重现了
> 
> 部署不了

3.16.0之前的几个版本也一直存在无法部署的问题
很显然作者现在的精力都放在收费模块x-tunnel上了

**Comment by xxnet** [comment]
4月1日后要绑定银行卡，否则这些appid都没法用，目前这个还没有解决呢

**Comment by xxnet** [comment]
正在升级到 python3，部署到时候在研究办法吧

**Comment by pch9527** [comment]
希望下个月谷歌官方不要彻底封杀非绑卡用户= =！GAE代理要是因为这个原因流产就太可惜了

**Comment by deniaBella** [comment]
> 4月1日后要绑定银行卡，否则这些appid都没法用，目前这个还没有解决呢

请问确定吗? 我查到的应该是4月30号

![2020-02-27_004042_shutdown](https://user-images.githubusercontent.com/62793964/77821435-2fecd400-7125-11ea-8d03-9afda5b0a3f7.jpg)

**Comment by xxnet** [comment]
哦，记错了，那就还有一个月时间
