### ISSUE TITLE
我朋友刚刚下载的 3.16稳定版X-Tunnel 怎么注册不了啊？

### ISSUE THREAD

**Issue by wwqq33** [XX-net/XX-Net#13038]
安装好后 直接进入X-Tunnel配置界面 她用谷歌账号 注册不了 为什么啊？老显示未知错误。。她想直接买流量的，说xx-net比她用的速度快

**Comment by xxnet** [comment]
注册不了提示了什么，把 X-Tunnel的状态页和下面的几个日志都贴出来看看
或者发邮件给 xxnet.dev@gmail.com

**Comment by wwqq33** [comment]
> 
> 注册不了提示了什么，把 X-Tunnel的状态页和下面的几个日志都贴出来看看 或者发邮件给 [xxnet.dev@gmail.com](xxnet.dev@gmail.com)

我用我的电脑帮她注册了一下，然后用她的电脑登陆就好了。。她可能是WiFi链接的电脑，信号不好，登录也要半天才能登上，过会还会自动退出登录状态。。等她换有线上网，有问题再发邮件请教。
