### ISSUE TITLE
3.16.1在win10 64bit 1909版本下依旧是自动退出重启。。。

### ISSUE THREAD

**Issue by UltraDWS** [XX-net/XX-Net#13056]
如题，用回3.14.0只有罕见自动退出，但用最新的3.16.1就会在页面跳转重新指向的时候经常性自动退出重启。啊。。。略头疼啊_(:з)∠)_，我还是暂时换回3.14.0吧

**Comment by nly4lov** [comment]
用哪个也没有自动退出的。估计是你系统的问题吧。

**Comment by UltraDWS** [comment]
> 用哪个也没有自动退出的。估计是你系统的问题吧。

我觉得你应该用关键词“退出、自动退出”查一下不久之前别人提交的issue反馈，不止我一个人，也不止我这一个版本的系统出现了自动退出的问题，在已发布的历史版本里，也有X大为了解决这个问题而添加的自动重启功能。你没有问题不代表别人没有问题，更何况从3.14.1开始到现在最新版3.16.1一直都是测试版状态。

**Comment by xxnet** [comment]
#13063 
试试 4.0.0版本会不会退出

**Comment by UltraDWS** [comment]
> #13063
> 试试 4.0.0版本会不会退出

X大效率牛啤，4.0.2都来了，已经用上了目前看来很稳定，还没试过大量重新定向下的峰值稳定性，有空作死试一试，然后UI上面系统那一栏好像是不是字符出错了，成了“,SYSTEM”。

**Comment by xxnet** [comment]
,SYSTEM 确实是bug，修改代码时IDE自动插入了个逗号
谢谢提醒
