### ISSUE TITLE
流量又要没了，求送流量？

### ISSUE THREAD

**Issue by yingerson** [XX-net/XX-Net#13053]
不知不解决，X-tunnel流量就快要用完了，自从使用XXNET，感觉世界的大门始终还是留有一条缝给我的，没有XXNET感觉就像是井底之蛙了，求好心人赠送点流量，感激不尽！

是否试过最新的版本？是

是否查看过 Wiki？是

是否以相关关键词搜索过类似 issues？是

描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

如果问题得到解决，请务必回复相关情况，谢谢。

即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。
![20200322200100](https://user-images.githubusercontent.com/5210386/77248897-173d7380-6c78-11ea-9c90-87bc35794760.png)

**Comment by joychase** [comment]
速度不错的新选择
2020.cfssr.xyz/auth/register?code=5sas

**Comment by yingerson** [comment]
收到流量，感谢各位好心人！
