### ISSUE TITLE
[发布] 4.0.2， 修复CPU高问题

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13079]
发布链接：
https://github.com/XX-net/XX-Net/releases/tag/4.0.2

修复前面版本CPU高的问题。

**Comment by nasa217** [comment]
新版本部署appid不能行，win10 1903

**Comment by jc3213** [comment]
我这里3.16.x跟4.0.x都随机遇到了无法关闭电脑得问题，卡在“正在关机”界面。

当时得软件环境进行修改了得就xx-net 3.14.2升级到3.16.1，Steam更新，显卡驱动更新。因此我尝试
过卸载Steam并重装，安装旧版本驱动等。多次排查以后还是遇到这个问题。

升级xx-net4.0.0用得时候发现无法访问推特，然后接着就遇到CPU占用高，xx-net假死了，然后用任务管理器终止得时候发现xx-net无限启动。只能通过对着图标右键退出才能退出。

我现在又退回3.14.2了，具体还要再体验一下。

**Comment by wuwuti** [comment]
反馈：安装6小时了。目前没发现任何问题。

**Comment by wuwuti** [comment]
@xxnet 
反馈：安装6小时了。目前没发现任何问题。

**Comment by xxnet** [comment]
部署功能暂时还没有实现，需要换掉整个部署库。

卡重启问题在前面帖子讨论了，希望4.0.2能够解决，看更多人来反馈。

**Comment by loveinlastnight** [comment]
4.02还是无法部署啊。新版还是用老的服务端吗？

**Comment by xxnet** [comment]
服务端代码没有变，暂时没有部署功能。

你目前的部署方法：
1. 用 3.14.x部署
2. 自己下载gcloud 挂上代理部署

**Comment by loveinlastnight** [comment]
那就不用重新部署了哦

**Comment by jap33** [comment]
有效 IP 数会卡死不动。

**Comment by pch9527** [comment]
3.14.1 是无法部署的
3.14.0和3.14.2可以

**Comment by xxnet** [comment]
有效 IP 数会卡死不动，具体表现是怎样的？

**Comment by jap33** [comment]
3.16.0以前刚用时打开网页都会卡一下有效 IP 数会下降、连接稳定后有点回升。这版卡一下有效 IP 数不会下降还是打开那么多，检查ip结果死了一大片。有效 IP 数显示不出。

**Comment by ino1988** [comment]
windows10无法自动下载Python环境，手工下载  https://raw.githubusercontent.com/XX-net/XX-Net-dev/master/download/py3.8.2.zip  报404 not found。
为什么？我用的链接有问题吗？

**Comment by xxnet** [comment]
这个部分还没有改，你直接下载windows版本才对

**Comment by xxnet** [comment]
已发布 4.0.3版
#13097
