### ISSUE TITLE
[BUG?] 3.16.1随机导致Windows无法关机卡在“正在关机”界面……

### ISSUE THREAD

**Issue by jc3213** [XX-net/XX-Net#13081]
XX-NET：3.16.1
OS： Windows 10 Enterprise LTSC 2019

症状：
我这里3.16.x随机遇到了无法关闭电脑得问题，卡在“正在关机”界面。

排查：
当时得软件环境进行修改了得就xx-net 3.14.2升级到3.16.1，Steam更新，显卡驱动更新。因此我尝试
过卸载Steam并重装，安装旧版本驱动等。多次排查以后还是遇到这个问题。

升级xx-net4.0.0用得时候发现无法访问推特，然后接着就遇到CPU占用高，xx-net假死了，然后用任务管理器终止的时候发现xx-net自动启动。再次用任务管理器关闭xx-net，然后xx-net再次启动。无限循环，只能通过对着图标右键退出才能退出。

推测：
不知道是不是这个跟Windows得关机冲突了？导致Windows尝试关闭xx-net，xx-net认为自己意外终止重新启动。然后两者冲突最终卡住最后的关机环节。

追加描述：
卡住的时候硬盘应该是无读写状态（灯不闪），这个状态下热启动或者按住电源键关机会导致开机的时候也卡很长一段时间硬盘无读写，接着才开始读写进入系统。但是通过CrystalDiskInfo之类软件查看硬盘S.M.A.R.T.S值，并未发现任何异常增加的数值。

后记：
我现在又退回3.14.2了，具体还要再体验一下。

意见：
这个xx-net的自动重启功能能否做个开关什么的选项？至少可开可关而不是强制使用到我这里想排查都只能往低版本降。

吐槽：
至少这个关不了机的问题是真的吓人。11点准备睡觉，突然关不了机了。睡觉也别睡了。难受。

**Comment by SeaHOH** [comment]
这个功能原本是应对 python2 崩溃，鉴于微软积极参与 python 生态，新版本崩溃概率会很少，可以移除此功能。

**Comment by jc3213** [comment]
补充说明下事情经过：
3月27日，当天更新得3.16.1。晚上9点因为Steam升级遇到BUG，导致Steam界面没有启动无法玩游戏尝试重启解决问题。【卡关机界面，热启动。卡开机】，进系统，Steam正常了，可以玩游戏了，稍微测试了一下，并上了会网，【关机，又卡了。按电源关机】，睡觉。睡不着，【1点起床开机，同样卡开机】，仅卸载Steam跟驱动。重装了445.75驱动。关机【正常】。
第二天（3月28日）开机，重新安装Steam，正常使用。晚上10点左右害怕抽风，直接尝试重启，【卡关机画面。热启动，卡开机】，进系统。彻底卸载Steam，重装了442.59驱动。继续上网。大概11点【关机，继续卡，强行关机。】
第三天（3月29日）升级了xx-net 4.0.0，跟445.78hf驱动。遭遇4.0.0 CPU高占用，发现任务管理器无法终止xx-net，产生pythonw.exe无限重启得怪问题。又因为4.0.0无法访问twitter，并且google开始要求绑信用卡，考虑停用xx-net。然后删除了xx-net相关得东西。【中午11点重启，正常】，【晚上关机，正常】。

这个问题应该不是100%复现。我大概总结了一下复现方法：
1） 关闭Windows 10的快速启动。
2） 使用XX-NET 3.16.1，并正常使用过程中遇到XX-NET崩溃并自动重启。（3.14.2则是崩溃了自动停止）。
3） 关机或重启时就会有很高得几率遇到这个问题。

**Comment by jc3213** [comment]
> 这个功能原本是应对 python2 崩溃，鉴于微软积极参与 python 生态，新版本崩溃概率会很少，可以移除此功能。

我前天（28号）尝试了各种手段。关机前把所有能关得程序比如浏览器，QQ，Steam啥得都关了。唯独xx-net因为没考虑太多没手动关。然后重启就遇到无限卡“正在关机”得问题。

我能指名xx-net有问题也是因为这里。我日常使用得软件，能手动关闭得都关了。其他也就个开着RPC的ARIA2，这个东西我用了几年了都没卡过关机。最近做了软件修改得就这么些东西。排除到最后只有xx-net了。

**Comment by xxnet** [comment]
收到反馈，下一个版本把检测到异常自动重启的功能先取消了。

CPU高的问题已经定位到了，已经发布在4.0.2中。

Windows卡重启的问题我也遇到过，python进程卡住不退出，进程管理器无法关闭python进程。
尝试过各种kill命令无法都没有效果只能硬件重启，4.0.2 暂时没有遇到这个问题，继续观察

**Comment by jc3213** [comment]
> 收到反馈，下一个版本把检测到异常自动重启的功能先取消了。 CPU高的问题已经定位到了，已经发布在4.0.2中。 Windows卡重启的问题我也遇到过，python进程卡住不退出，进程管理器无法关闭python进程。 尝试过各种kill命令无法都没有效果只能硬件重启，4.0.2 暂时没有遇到这个问题，继续观察

我个人认为也许有人觉得有用？做个开关啥的会不会更好？或许这个功能还能完善？当然这得看你那边是否方便继续开发了。

我最初遇到这个卡重启是真的吓坏了。还以为硬件炸了，排查了两三天才发现是xx-net的pythonw.exe无限自我复活。我还是等xx-net取消自动重启功能再说吧。一朝被蛇咬十年怕井绳，我现在怕了。

PS：GAE绑定信用卡有什么教程么？从GCP进去选地区没有中国大陆，即使选香港下面也要求信用卡的地址跟填写地址一样。顿时方了

**Comment by xxnet** [comment]
先取消自动重启，有必要时再改成开关模式。

前面有人绑定银行卡成功了，希望有经验的出来分享一下

**Comment by xxnet** [comment]
卡死不能重启的问题和操作系统密切相关，网上有讨论和映射网络磁盘有关
可以看看是不是有关系 @jc3213

**Comment by jc3213** [comment]
然而我并没有映射过磁盘。可以说我的使用习惯几年没变过。也就更新3.16.1以后连续两天遇到卡死。。

当然，也有开机后重启不卡死的时候，所以我也说了这个问题不是100%能重现。应该是pythonw.exe多次崩溃或者重度使用过后导致的。具体原因我更不清楚了。因为连错误记录都没有。就直接关机行为无限杀死pythonw.exe，而pyhonw.exe无限复活自己。

再就是，我发出issue时也提到，我关闭了【快速启动】。我更怀疑是大多数人因为开着快速启动，进程不是被终止而是被休眠（Hibernate）才没有卡死。如果单纯的taskkill都能让进程无限复活驻留内存的话，这个行为说严重点跟恶意软件乃至病毒一样。

**Comment by leinadzaid21** [comment]
3月27日，当天更新得3.16.1。晚上9点因为Steam升级遇到BUG，导致Steam界面没有启动无法玩游戏尝试重启解决问题。【卡关机界面，热启动。卡开机】，进系统，Steam正常了，可以玩游戏了，稍微测试了一下，并上了会网，【关机，又卡了。按电源关机】，睡觉。睡不着，【1点起床开机，同样卡开机】，仅卸载Steam跟驱动。重装了445.75驱动。关机【正常】。  第二天（3月28日）开机，重新安装Steam，正常使用。晚上10点左右害怕抽风，直接尝试重启，【卡关机画面。热启动，卡开机】，进系统。彻底卸载Steam，重装了442.59驱动。继续上网。大概11点【关机，继续卡，强行关机。】  第三天（3月29日）升级了xx-net 4.0.0，跟445.78hf驱动。遭遇4.0.0 CPU高占用，发现任务管理器无法终止xx-net，产生pythonw.exe无限重启得怪问题。又因为4.0.0无法访问twitter，并且google开始要求绑信用卡，考虑停用xx-net。然后删除了xx-net相关得东西。【中午11点重启，正常】，【晚上关机，正常】。
这个问题应该不是100%复现。我大概总结了一下复现方法：  1） 关闭Windows 10的快速启动。  2） 使用XX-NET 3.16.1，并正常使用过程中遇到XX-NET崩溃并自动重启。（3.14.2则是崩溃了自动停止）。  3） 关机或重启时就会有很高得几率遇到这个问题。

**Comment by leinadzaid21** [comment]
>  3月27日，当天更新得3.16.1。晚上9点因为Steam升级遇到BUG，导致Steam界面没有启动无法玩游戏尝试重启解决问题。【卡关机界面，热启动。卡开机】，进系统，Steam正常了，可以玩游戏了，稍微测试了一下，并上了会网，【关机，又卡了。按电源关机】，睡觉。睡不着，【1点起床开机，同样卡开机】，仅卸载Steam跟驱动。重装了445.75驱动。关机【正常】。
>  第二天（3月28日）开机，重新安装Steam，正常使用。晚上10点左右害怕抽风，直接尝试重启，【卡关机画面。热启动，卡开机】，进系统。彻底卸载Steam，重装了442.59驱动。继续上网。大概11点【关机，继续卡，强行关机。】
>  第三天（3月29日）升级了xx-net 4.0.0，跟445.78hf驱动。遭遇4.0.0 CPU高占用，发现任务管理器无法终止xx-net，产生pythonw.exe无限重启得怪问题。又因为4.0.0无法访问twitter，并且google开始要求绑信用卡，考虑停用xx-net。然后删除了xx-net相关得东西。【中午11点重启，正常】，【晚上关机，正常】。
> 这个问题应该不是100%复现。我大概总结了一下复现方法：
>  1） 关闭Windows 10的快速启动。
>  2） 使用XX-NET 3.16.1，并正常使用过程中遇到XX-NET崩溃并自动重启。（3.14.2则是崩溃了自动停止）。
>  3） 关机或重启时就会有很高得几率遇到这个问题。

**Comment by jc3213** [comment]
@xxnet 我更怀疑是重启逻辑带来的问题。我怀疑这个逻辑把系统关机时带来的终止请求也当作【异常终止】，所以对自身进程进行了重启。最简单明了的判断就是任务管理器无法杀死这个进程。要关闭xx-net新版，必须右键点击图标，选择退出xx-net才能真正的彻底退出。

因为【快速启动】在关机时采取的是休眠而不是终止。因此大多数人不会在关机时被卡，所以我觉得这是本BUG汇报数量少的原因。而在【重启计算机】时，则是终止程序，最终导致pythonw.exe跟shutdown.exe进行无限博弈导致卡死。这里你自己也说遇到过 https://github.com/XX-net/XX-Net/issues/13081#issuecomment-606089473 

这也是我目前觉得最有力的说法，也是我请求增加开关的原因。除非崩溃问题从根本被解决，这个功能可以说还是有需求的。但是它同样是有风险的，有瑕疵的。这类功能最好做个开关默认关闭，并告诫用户所存在的风险。

PS：可以的话让3.16.1~4.0.2之间版本的用户在pyhonw.exe多次崩溃重启后，让他们不通过右键退出法退出xx-net，而是开着xx-net直接重启计算机试试看多少人卡住，稍微抽个样看看吧？

**Comment by jc3213** [comment]
@leinadzaid21 不知道你想表达什么？

**Comment by xxnet** [comment]
如果只是启动逻辑问题，可以先手动关掉 cscript进程，就不会再重启了

**Comment by jc3213** [comment]
具体是什么原因我也排查不了。一个没环境，二是也不太懂Python（准确的说我的开发环境是HTML跟Javascript）。

只是能确定这个问题是由xx-net带来的，那就只有等待修复了。如果无从修复那么就坚持老版本，虽然偶尔崩溃，但是我的使用强度并不高，因此基本没太大问题。

**Comment by xxnet** [comment]
重新看你最早的描述，原来真的就是自动重启惹的祸。
你只要在Web界面最右上角点退出按钮，或者托盘右键退出就可以正常退出了。

**Comment by xxnet** [comment]
#13097 

已发布4.0.3，可以试试新版有没有效果
