### ISSUE TITLE
[BUG]Smart Router Configuration

### ISSUE THREAD

**Issue by snipertulip** [XX-net/XX-Net#13086]
Smart Router Configuration Page

System: win10
XX-Net VER: 4.0.2

Auto-Try Direct
Use IPv6 preferentially when Auto-Try Direct
Auto-Try GAEProxy
Enable Fake CA
Block Advertisement

设置后重新加载页面显示不对
返回数据调用判断不一致
返回数据：{
"auto_direct": "True",
"auto_direct6": "False",
"auto_gae": "True",
"block_advertisement": "True",
"country": "CN",
"enable_fake_ca": "True",
"pac_policy": "black_GAE"
}
显示页面
config_general.html
```
//line 77:
            success: function (result) {
                if (result['auto_direct'] != 0) {  // “False" <<------
                    $("#auto-direct").parent().removeClass('switch-off');
                    $("#auto-direct").parent().addClass('switch-on');

                    $("#auto-direct").prop('checked', true);
                }
```

**Comment by xxnet** [comment]
确认bug，下个版本修复

**Comment by xxnet** [comment]
#13097 
问题已修复，请测试
