### ISSUE TITLE
视频暂停或者快进之后提示没有找到资源

### ISSUE THREAD

**Issue by damoyelang1992** [XX-net/XX-Net#1308]
视频暂停或者快进之后提示没有找到资源，常见youtube

**Comment by xyuanmu** [comment]
你用的是什么浏览器，是否阻止cookie，我这里一直都没出现这现象，而且这两天速度非常稳定。
![Youtube](https://cloud.githubusercontent.com/assets/12442896/10873089/df1607a6-8149-11e5-9e91-0d3cd95ed01f.jpg)

**Comment by damoyelang1992** [comment]
google chrome，不阻止Cookie
