### ISSUE TITLE
从任意网站执行一段代码即可获取appid列表以及密码

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1309]
在任意网页，首先保证已经引入jQuery，然后执行如下代码即可：
$.get('http://127.0.0.1:8085/module/gae_proxy/control/config?cmd=get_config', function(data) {
    var json = JSON.parse(data);
    console.log(json.appid);
    console.log(json.password);
});

类似的问题还有很多，Web页面里有大量GET请求，比如各个模块的开关、托盘图标是否显示的开关等。
最简单的解决方案是来源地址检测。
以及，感觉这个请求没必要返回真实密码吧- -
某些有安全限制的网页可能不行，比如github。
@xxnet

**Comment by xyuanmu** [comment]
我的appid是放到manual.ini，因为当初就想到会返回appid的问题，刚访问该地址的时候果然密码和appid是空的，放到config.ini里的id和密码暴露无疑。

**Comment by xxnet** [comment]
恩，刚测试了，来源地址检测，原来是有的，可惜没有测试，代码中有bug。
  已经修复，下次发布加上。

之前PAC内部有一个本地文件泄露，已经堵上了。


在 2015年11月2日 下午2:06，xyuanmu <notifications@github.com>写道：

**Comment by Cat7373** [comment]
@xxnet 最近是在忙么- -
还是在憋大更新- -
或者在看Google回归后的变动- -
好久没有更新惹- -

**Comment by xxnet** [comment]
最近墙也没有怎么动作，就先研究别的东西了，等有需要再更新吧。

在 2015年11月2日 下午10:18，Cat73 <notifications@github.com>写道：
