### ISSUE TITLE
[BUG]GAEProxy Advanced Configuration

### ISSUE THREAD

**Issue by snipertulip** [XX-net/XX-Net#13093]
System: Microsoft Windows [Version 10.0.18363.720]
XX-Net: 4.0.2

GAEProxy Advanced Configuration
IPv6 Tunnel 隧道已经连接成功的情况下，始终显示unkown

**Comment by xxnet** [comment]
能扫描到ipv6地址吗？

我这边测试没有重新问题

**Comment by snipertulip** [comment]
> 能扫描到ipv6地址吗？
> 
> 我这边测试没有重现问题

有ipv6地址，就是显示状态不正常
（我发现没有绑定银行卡的appid，还可以用么，4月1日限制假的？）

**Comment by xxnet** [comment]
有IPv6地址不一定能访问IPv6网络。

找找测试ipv6的网站测试

**Comment by snipertulip** [comment]
> 有IPv6地址不一定能访问IPv6网络。 找找测试ipv6的网站测试

XX-Net Version : 4.0.3
System Platform : Windows-10-10.0.18362-SP0

IPv6 Tunnel
Teredo Tunnel | unkown
phython3 一直以来的问题，貌似还有些bug
\code\default\gae_proxy\local\ipv6_tunnel\common.py
line146:
def get_line_value(r, n):

r = r.decode('utf-8') python3 bytes, str转换函数
rls = r.split("\r\n")

**Comment by xxnet** [comment]
这个bug，晚点发版本修复
