### ISSUE TITLE
[发布] 4.0.3 修复几个bug

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13097]
https://github.com/XX-net/XX-Net/releases/tag/4.0.3

更新：
- 修复智能路由无法修改配置
- 修复无法切换到允许远程控制
- 改进Windows启动脚本，避免阻止重启系统

**Comment by nly4lov** [comment]
![80](https://user-images.githubusercontent.com/11325411/78313840-b7559f80-758a-11ea-8a5b-014a68448ef2.gif)

**Comment by Sharedaily** [comment]
我想问一下部署APPID的问题解决了吗?今天试了下貌似还是无反应.

**Comment by yangsl158** [comment]
好奇怪，我明明下载更新到 python3了，怎么还是提示我环境失败呢。。。而且我退回3.16.1也出现这个提示了。。

**Comment by taoeternal2018** [comment]
大概一周了3.14/3.16都翻不动 换4.03 总算“XX-Net 4.0.3，一切正常，你可以访问真正的互联网了。” 感谢xxnet

**Comment by 5000e1** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-19.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
os-release: 19.4.0
os-detail: Release:10.15.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
xxnet-version: 4.0.3
python-version: 3.7.0
openssl-version: 19.1.0 TLSv1 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xxnet** [comment]
已发布 4.0.4
