### ISSUE TITLE
几个问题报告下

### ISSUE THREAD

**Issue by ji-hoom** [XX-net/XX-Net#131]
最新版本xx-net 家里和办公室系统都是win8.1 x64 解压后运行start快捷方式后 CA证书貌似不会自动导入，后来我在goagent date 找到CA证书手动导入才行。Chrome我用的是SwitchyOmega 使用的xxnet里面的备份导入的配置，基本没什么问题。但是使用IE11，办公室电脑好像没什么问题，家里面却死活不能翻墙，设置都是一样的 internet选项-连接-局域网设置-代理服务器地址 127.0.0.1 端口8087。这个问题挺奇怪的 想请版主分析分析看看

**Comment by xxnet** [comment]
把家里电脑的状态页和日志发出来看看

在 2015年4月12日 上午8:20，ji-hoom <notifications@github.com>写道：
