### ISSUE TITLE
smart_route and gae_proxy not work, version 4.0.3 on ubuntu 18

### ISSUE THREAD

**Issue by m17design** [XX-net/XX-Net#13109]
smart_route and gae_proxy not work, and no config page (on port 8085) works.

logs show some error in py files, see below:

Apr 05 04:16:19 rock64 start[14507]: 2020-04-05 04:16:00.538 [smart_router][ERROR] any err:TypeError("a bytes-like object is required, not 'str'",)
Apr 05 04:16:19 rock64 start[14507]: 2020-04-05 04:16:00.540 [smart_router][ERROR] Except stack:Traceback (most recent call last):
Apr 05 04:16:19 rock64 start[14507]:   File "/XX-Net/code/default/smart_router/local/proxy_handler.py", line 75, in handle
Apr 05 04:16:19 rock64 start[14507]:     self.http_handler()
Apr 05 04:16:19 rock64 start[14507]:   File "/XX-Net/code/default/smart_router/local/proxy_handler.py", line 329, in http_handler
Apr 05 04:16:19 rock64 start[14507]:     host, port = netloc_to_host_port(o.netloc)
Apr 05 04:16:19 rock64 start[14507]:   File "/XX-Net/code/default/smart_router/local/smart_route.py", line 122, in netloc_to_host_port
Apr 05 04:16:19 rock64 start[14507]:     if ":" in netloc:
Apr 05 04:16:19 rock64 start[14507]: TypeError: a bytes-like object is required, not 'str'

**Comment by xxnet** [comment]
bug 已确认，晚点发版本修复

**Comment by xxnet** [comment]
#13112

已发表 4.0.4
