### ISSUE TITLE
Teredo 隧道 显示【未知】是怎么回事?

### ISSUE THREAD

**Issue by iSuperYang** [XX-net/XX-Net#13103]

**Comment by iSuperYang** [comment]
![2020-04-04_001717](https://user-images.githubusercontent.com/30848787/78383645-4d310f00-760b-11ea-8ad8-1e2b7364a31f.png)

**Comment by iSuperYang** [comment]
无论禁用或者是开启，这里都是显示 未知。

**Comment by xxnet** [comment]
问题已经找到了 python3 升级带来的问题，代码已经push到github，下一个版本解决
