### ISSUE TITLE
4.0.3 只能使用隧道teredo.remlab.net.

### ISSUE THREAD

**Issue by 34923611** [XX-net/XX-Net#13106]
![image](https://user-images.githubusercontent.com/32702294/78422225-5dd79880-7690-11ea-8628-50520b9b87bb.png)

no server detected, return default: teredo
内置自动测试更换貌似失效了 只能使用隧道teredo.remlab.net 命令行更换其他隧道后无法连接

**Comment by snipertulip** [comment]
反映过bug，回复测试未重现。。。
我这边一直用的teredo.remlab.net，就算连接成功了，我这边还是显示“未知”

**Comment by snipertulip** [comment]
> ![image](https://user-images.githubusercontent.com/32702294/78422225-5dd79880-7690-11ea-8628-50520b9b87bb.png)
> 
> no server detected, return default: teredo
> 内置自动测试更换貌似失效了 只能使用隧道teredo.remlab.net 命令行更换其他隧道后无法连接

我也是命令设置的，你用teredo.remlab.net连接成功后，上面显示“未知”吗？

**Comment by 34923611** [comment]
> > ![image](https://user-images.githubusercontent.com/32702294/78422225-5dd79880-7690-11ea-8628-50520b9b87bb.png)
> > no server detected, return default: teredo
> > 内置自动测试更换貌似失效了 只能使用隧道teredo.remlab.net 命令行更换其他隧道后无法连接
> 
> 我也是命令设置的，你用teredo.remlab.net连接成功后，上面显示“未知”吗？

只能连teredo.remlab.net 显示合格 但是这个teredo.remlab.net延迟非常高

**Comment by xxnet** [comment]
#13112 
修复相关代码，请测试

**Comment by Harveychn** [comment]
本人已经弃坑了
可以试试这个 加速器 https://cov.laihuluwa.com/aff/RYC3 免费的
