### ISSUE TITLE
X-Tunnel 状态需要申请appid吗

### ISSUE THREAD

**Issue by kehui12345** [XX-net/XX-Net#13117]
如题，不会折腾，只用X-Tunnel，需要appid吗？另外，路由器设置是否支持X-Tunnel模式

**Comment by xxnet** [comment]
X-tunnel 不需要注册appid，不折腾

路由器上跑x-tunnel是可以的，需要性能高的硬件

**Comment by kehui12345** [comment]
哪些牌子的路由可以支持？

**Comment by xxnet** [comment]
内存 128M 最少，CPU尽量快，可以参考这个文章

https://10-0-0-0-1.org/reviews/routers/openwrt/

**Comment by xxnet** [comment]
发现联想新路由不错，内存够大

**Comment by kehui12345** [comment]
OK，谢谢
