### ISSUE TITLE
[BUG]GAEProxy Advanced Configuration

### ISSUE THREAD

**Issue by snipertulip** [XX-net/XX-Net#13111]
XX-Net Version : 4.0.3
System Platform :  Windows-10-10.0.18362-SP0

IPv6 Tunnel
Teredo Tunnel | unkown
phython3 一直以来的问题，貌似还有些bug
\code\default\gae_proxy\local\ipv6_tunnel\common.py
line146:
def get_line_value(r, n):
+   r = r.decode('utf-8')    python3 bytes, str转换函数
     rls = r.split("\r\n")

**Comment by xxnet** [comment]
已发布 4.0.4 修复
