### ISSUE TITLE
[4.0.4] Unhandled exception at 0x7342B1C7 (_openssl.cp38-win32.pyd) in pythonw.exe

### ISSUE THREAD

**Issue by wangyugui** [XX-net/XX-Net#13126]
[XX-Net-windows-4.0.4] Unhandled exception at 0x7342B1C7 (_openssl.cp38-win32.pyd) in pythonw.exe

Detail:
Unhandled exception at 0x7342B1C7 (_openssl.cp38-win32.pyd) in pythonw.exe: 0xC0000005: Access violation reading location 0x00000018. occurred

OS: Windows7 x64

Best Regards
Wang Yugui

**Comment by xxnet** [comment]
openssl 存在bug导致异常退出。
解决方案是换掉pyOpenSSL

**Comment by myjlpt** [comment]
是的这个问题我这边也复现了。但更换哪个？之前的3.7版本？也是一样的。

**Comment by xxnet** [comment]
有计划用pyo3 编译 rustls库。
需要投入精力

**Comment by wangyugui** [comment]
maybe python3.6.x is more stable?

**Comment by xxnet** [comment]
从目前收集到的core dump分析，问题出在pyOpenSSL相关的库，和python本身关系不大

**Comment by xxnet** [comment]
#13143 
试试新版 4.0.5

**Comment by wangyugui** [comment]
@xxnet 
4.0.5版本仍然会发生_openssl.cp38-win32.pyd Exception，好像几率稍稍少了点，没有大的改观。

**Comment by xxnet** [comment]
看来还是没有解决

**Comment by xxnet** [comment]
发布4.4.0, 用python内置ssl，请大家测试还有没有异常退出 #13298

**Comment by wangyugui** [comment]
异常退出的问题，目前为止，4.4.0版没有再发生。
多谢！

**Comment by xxnet** [comment]
希望这次解决了。
