### ISSUE TITLE
GAE appid绑定结算账户后，有什么办法能避免收费?

### ISSUE THREAD

**Issue by yetanotherface** [XX-net/XX-Net#13145]
请问各位，appid绑定结算账户以后，如果想避免收费，是不是要用google cloud 重新部署？
部署时app.yaml怎么写才能避免收费？

**Comment by XLX** [comment]
> 请问各位，appid绑定结算账户以后，如果想避免收费，是不是要用google cloud 重新部署？
> 部署时app.yaml怎么写才能避免收费？

首先我看绑定后有1年试用期，1年时间应该肯定有比较完善的处理方案了吧

然后关于app.yaml，我看好像只能设置最大实例数，详见这里：
https://cloud.google.com/appengine/docs/standard/payment-instrument#limiting_your_costs

**Comment by yetanotherface** [comment]
@XLX  
你指的是1年试用期送的300美元都可以用于GAE流量？
另外，限制实例数对控制流量的意义是什么？

**Comment by shareppz** [comment]
没有绑定信用卡，目前APPID还能使用，你们呢

**Comment by klcb2010** [comment]
> 
> 
> 没有绑定信用卡，目前APPID还能使用，你们呢

可用 奇怪了  ，难道是针对新用户

**Comment by yDan** [comment]
正常使用中，没有绑卡

**Comment by jap33** [comment]
只用来看油管别乱用。
