### ISSUE TITLE
google ipV6段支持的格式

### ISSUE THREAD

**Issue by yetanotherface** [XX-net/XX-Net#13156]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Scan-Ip-Range-Format

wiki中只是列举了ipv4范围格式，请问xx-net支持的ipv6范围格式是什么？

我试了好多种都不行，如nslookup查询出来的address/prefix-length格式，请各位给个正确的例子。

**Comment by gayhub-dev** [comment]
ipv6不支持前端添加，请直接将可用ip按照特定格式加到ipv6_range.txt中

**Comment by yetanotherface** [comment]
@gayhub-dev 谢谢回复。
只用ipv6的话，是不是在加了data/gae_proxy/ipv6_range.txt后，还得在前端把IP range list置空？
另外，我想只用纯ipv6，是因为就算前端显示上千个good ipv4的ip，但实际效果很差，经常访问超时，可能的是什么原因？

**Comment by gayhub-dev** [comment]
> @gayhub-dev 谢谢回复。
> 只用ipv6的话，是不是在加了data/gae_proxy/ipv6_range.txt后，还得在前端把IP range list置空？
> 另外，我想只用纯ipv6，是因为就算前端显示上千个good ipv4的ip，但实际效果很差，经常访问超时，可能的是什么原因？

不用，模式设置force ipv6即可，ipv4效果差大概率是ip连接性不够好,想要获得较好的速度ip的握手时间最好<200ms，当然<100ms最好，此外还要考虑ip的实际链路速率，这个指标和tcp握手时间没有必然联系，只是理论上握手时间越短连接速度越快，这得看运营商的心情了

**Comment by yetanotherface** [comment]
@gayhub-dev 谢谢回复。有没有什么资料或工具能帮助找到连接性好的ipv4和ipv6？
