### ISSUE TITLE
IPv6、IPv4均正常，就是无法连接，4.0.4和4.0.5都有这个问题

### ISSUE THREAD

**Issue by goalkeeper24** [XX-net/XX-Net#13188]
信息正常就是无法连接，诊断信息如下：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
xxnet-version: 4.0.5
python-version: 3.8.2
openssl-version: 19.1.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:89 ipv4:1 ipv6:88
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 18
ip-quality: 863
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Rven71** [comment]
我的也是连不上IP为0

**Comment by ohzxc** [comment]
今晚突然连不上了

**Comment by yupeach** [comment]
> 今晚突然连不上了

不知发生了什么事情。。。印象中今天下午之前都很容易扫到IP，现在都是0。。。
对了，朋友你是哪个省份的？

**Comment by kwwgh** [comment]
我也跟楼上一样，傍晚跑个步回来就不能用了，GAE连接数为0。不知道是不是因为google那个需要绑定卡的原因，我没绑。准备开始用X-tunnel了

**Comment by snsnselaoyeye** [comment]
我也是，昨晚才发现的，前几天还愉快的看youtube呢。我是很早之前自己开的APPID，很久没上这，也是昨天才知道现在APPID需要绑定银行卡了，如果不行，只能放弃了。哎 郁闷

**Comment by excellenttank** [comment]
我也不能用了，昨天突然不能用了，gogo tester也扫不到任何IP

**Comment by ohzxc** [comment]
> 我也跟楼上一样，傍晚跑个步回来就不能用了，GAE连接数为0。不知道是不是因为google那个需要绑定卡的原因，我没绑。准备开始用X-tunnel了

不是没绑卡的原因。我已经绑过

**Comment by ohzxc** [comment]
> > 今晚突然连不上了
> 
> 不知发生了什么事情。。。印象中今天下午之前都很容易扫到IP，现在都是0。。。
> 对了，朋友你是哪个省份的？

湖南长沙

**Comment by kwwgh** [comment]
> > 我也跟楼上一样，傍晚跑个步回来就不能用了，GAE连接数为0。不知道是不是因为google那个需要绑定卡的原因，我没绑。准备开始用X-tunnel了
> 
> 不是没绑卡的原因。我已经绑过

哈，那是不是意味着GAE还有恢复的可能性？等待作者大大解答。
不过我已经买tunnel的流量了，就当支持作者吧。

**Comment by enhvjf** [comment]
会不会是因为两会的原因？上次十九大也是这样。我用校园网扫不到ip，但是用手机数据给电脑开热点就能扫到。

**Comment by yupeach** [comment]
> 湖南长沙
那意味着跟地区无关了，还是比较乐观的。。。估计过段时间又能扫到IP

**Comment by yupeach** [comment]
> > > 今晚突然连不上了
> > 
> > 
> > 不知发生了什么事情。。。印象中今天下午之前都很容易扫到IP，现在都是0。。。
> > 对了，朋友你是哪个省份的？
> 
> 湖南长沙

那意味着跟地区无关了，还是比较乐观的。。。估计过段时间又能扫到IP

**Comment by xxnet** [comment]
问题出在google 上。
google 改成对一个appid支持不同版本同时工作，所以有的appid需要换一个域名，前面加上 "1-dot-"

大家可以自己先试试，因为之前没有考虑到这种情况，所以客户端代码不会自动切换，而陷入无法工作状态。
等我扫描所有公共id之后发一个新版本

**Comment by boycc1974** [comment]
v6还能连上，速度感人

**Comment by xxnet** [comment]
发布 #13191 

公共的appid已经更新。
私人的appid还需要自己测试更新
