### ISSUE TITLE
下的最新版为啥还提示xx-net download python environment fail, please download windows version

### ISSUE THREAD

**Issue by pixelmemento** [XX-net/XX-Net#13258]

**Comment by ss-salo** [comment]
> * closed by Python/3.8.3 Github-Bot/0.2, reason: empty content, you can reopen it yourself after write issue content..

could you please explain it more clearly?i can't understand what you mean.

**Comment by ss-salo** [comment]
> * closed by Python/3.8.3 Github-Bot/0.2, reason: empty content, you can reopen it yourself after write issue content..
I already know the answer to this question, don't open the zip package directly, just unzip it and run VBS.
