### ISSUE TITLE
GAEPROXY 部署appid失败

### ISSUE THREAD

**Issue by zuohl** [XX-net/XX-Net#13264]
查看接口返回 File is not a zip file,使用的是4.1.2版本

XX-Net Version | 4.1.2
-- | --
Python Version | 3.8.2
OpenSSL Version | 19.1.0 TLSv1_2 h2:alpn
System Platform | AMD64, Windows-10-10.0.19041-SP0
OS System | Windows
OS Version | 10.0.19041
OS Release | 10
OS Detail | Version:10-0; Build:19041; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language | zh_CN
Architecture | 32bit,WindowsPE
Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by xxnet** [comment]
参考这里了吗？
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2GAE-APPID

问题是怎样的，请截屏

**Comment by zuohl** [comment]
> 参考这里了吗？ https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2GAE-APPID 问题是怎样的，请截屏

我知道啥问题了.因为4.0.5里面有部署服务端的功能,但是实际又不可用,所以出现该问题,我更新到4.1.2直接没这个入口了.我已经解决了.感谢
