### ISSUE TITLE
devenv.exe (Visual Studio 2017)占了1080端口，如何修改X-Tunnel的端口号？

### ISSUE THREAD

**Issue by 102464** [XX-net/XX-Net#13287]
C:\Users\Win7>netstat -ano | finstr 1080
...
TCP    127.0.0.1:61036        127.0.0.1:1080         FIN_WAIT_2      84344
TCP    127.0.0.1:61158        127.0.0.1:1080         ESTABLISHED     52716
TCP    127.0.0.1:61183        127.0.0.1:1080         ESTABLISHED     52716
TCP    127.0.0.1:61285        127.0.0.1:1080         ESTABLISHED     52716
TCP    127.0.0.1:61451        127.0.0.1:1080         FIN_WAIT_2      13088
TCP    127.0.0.1:61550        127.0.0.1:1080         ESTABLISHED     52716
...
C:\Users\Win7>tasklist | findstr 52716
devenv.exe                   52716 Console                    1    643,688 K
C:\Users\Win7>tasklist | findstr 48360
ServiceHub.IdentityHost.e    48360 Console                    1     46,104 K

查看了data/x-tunnel/client.json， 没有修改端口的配置，有什么方法可以修改端口号？

**Comment by XLX** [comment]
我前段时间也遇到了类似问题，后来研究出方法改端口号才解决的

方法一：直接改代码
修改 code\default\x_tunnel\local\client.py 搜索 1080 改成新端口号
（不太推荐，因为更新版本后可能需要重新修改）

方法二：改配置文件
修改 data\x_tunnel\client.json 加一条配置 "socks_port": 新端口号
注意要符合 JSON 语法，不同数据之间英文逗号分隔，另外端口号是整型所以不加双引号
（推荐，更新后不用重新修改）

**Comment by 102464** [comment]
已解决，谢谢！
