### ISSUE TITLE
部署问题：The read operation timed out

### ISSUE THREAD

**Issue by daociyiyou** [XX-net/XX-Net#133]
Apr 12 21:53:36 - Application: *****
Apr 12 21:53:36 - Host: appengine.google.com
Apr 12 21:53:36 - Rolling back the update.
Apr 12 21:53:56 - upload  fail: The read operation timed out

Apr 12 21:53:56 - Retry again.

一直都是这样，google ip 使用频率限制也改到20了

**Comment by xxnet** [comment]
通过XX-Net，你可以访问appengine.google.com和www.google.com网站吗？

2015-04-12 10:18 GMT-04:00 daociyiyou <notifications@github.com>:

**Comment by daociyiyou** [comment]
刚开始不行，后来又可以了，但是有时候可以，有时候不行。

**Comment by daociyiyou** [comment]
刚开始不行，后来又可以了，但是有时候可以，有时候不行。

**Comment by daociyiyou** [comment]
一开始不行，后来又可以了，但是有时候可以，有时候不行。

刚刚又不行了，重新部署下显示这个
Apr 14 09:18:50 - Host: appengine.google.com
Apr 14 09:18:50 - Rolling back the update.
Apr 14 09:18:54 - Error 502: --- begin server output ---

**Comment by xxnet** [comment]
请试试最新版 1.8.6

2015-04-13 21:21 GMT-04:00 daociyiyou <notifications@github.com>:

**Comment by randoloh820911** [comment]
Apr 18 09:58:50 - Retry again.

Apr 18 09:58:51 - Application: ******
Apr 18 09:58:51 - Host: appengine.google.com
Apr 18 09:58:51 - Rolling back the update.
Apr 18 09:59:11 - upload  fail: The read operation timed out

参考前面的回复,可以打开https://www.google.com.hk/?gws_rd=cr
无法打开https://appengine.google.com/
求助,谢谢!

**Comment by xxnet** [comment]
请看看GoAgent的日志

怀疑你设置了无效的appid

2015-04-17 22:07 GMT-04:00 randoloh820911 <notifications@github.com>:

**Comment by fleebeatle** [comment]
在win7上部署成功了，今天MacBook升级10.11.2后，GoAgent突然用不了，与是部署XX-net，但是一直不成功。我是开了VPN部署的，Google engine可以上。具体信息如下：

系统信息：
Property	Value
XX-Net Version	2.6.2
Python Version	2.7.10
Sys Platform	x86_64, Darwin-15.2.0-x86_64-i386-64bit
OS System	Darwin
OS version	Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64
OS release	15.2.0
OS detail	Release:10.11.2; Version:('', '', '') Machine:x86_64
language	zh_CN
architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36

同样无法部署：
Dec 9 18:42:32 - Application: ****
Dec 9 18:42:32 - Host: appengine.google.com
Dec 9 18:42:32 - Rolling back the update.
Dec 9 18:42:52 - upload fail: ('The read operation timed out',)

Dec 9 18:42:52 - Retry 23 time...

**Comment by xxnet** [comment]
看看你的状态页

2015-12-09 18:50 GMT+08:00 fleebeatle <notifications@github.com>:

**Comment by fleebeatle** [comment]
现在又好了，，，不知道为什么。。
