### ISSUE TITLE
建议XX-Net以后的版本可以加入IP自动检查功能的开关

### ISSUE THREAD

**Issue by iSuperYang** [XX-net/XX-Net#13306]
![2020-07-25_081008](https://user-images.githubusercontent.com/30848787/88444198-932a1100-ce4e-11ea-8478-c2f81b18085f.png)

IP失效的太快了，失效后不能自动消除失效的IP。需要进入界面手动检查IP。

希望可以加入一个定时自动检查IP的开关。

**Comment by stopislam** [comment]
我觉得是不是应该加入流量混淆，IP封的太快。

**Comment by xxnet** [comment]
检查一遍之后有什么效果？

如果检查一遍只是知道哪些ip失效那是没有必要的，对使用没有影响。
自动检查会增加连接数，形成明显的行为特征，容易被识别出来。
手动检查偶尔进行就没有问题。

**Comment by iSuperYang** [comment]
@xxnet 不检查会这样卡死。断开连接。 检查后才能恢复，以前IP掉的慢，没有这个问题，现在IP掉的速度很快，会经常卡死，100个IP检查后还是20多个，过一会又到100个，20分钟左右又会卡死断开连接，再次检查又变成20多个IP才能恢复连接，恢复连接后过一会又变成100个，这样循环。要经常手动打开界面去检测它才行。
![2020-07-26_092549](https://user-images.githubusercontent.com/30848787/88469254-136d7680-cf22-11ea-83a9-3145010a9448.png)

**Comment by xxnet** [comment]
问题可能是因为Google 域名特殊处理的策略有问题。

试试编辑data/gae_proxy/config.json
写入一下内容：
{
  "google_endswith": []
}

看能不能解决问题

**Comment by hellowx** [comment]
这好像和线路有关。电信线路会掉速明显，手动检查后会提速，但不久还会掉速。而移动线路没感觉，正常。

**Comment by iSuperYang** [comment]
@xxnet 新版本的4.4.1解决了此问题，感谢感谢！

**Comment by xxnet** [comment]
好的 @iSuperYang
