### ISSUE TITLE
为什么显示一切正常却还连不上网？

### ISSUE THREAD

**Issue by frediui** [XX-net/XX-Net#13343]
为什么显示“XX-Net 4.4.2，一切正常，你可以访问真正的互联网了。”
但是还连不上任何一个网址？

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17763-SP0
os-system: Windows
os-version: 10.0.17763
os-release: 10
os-detail: Version:10-0; Build:17763; Platform:2; CSD:; ServicePack:0-0; Suite:400; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
xxnet-version: 4.4.2
python-version: 3.8.2
openssl-version: OpenSSL 1.1.1d  10 Sep 2019 TLSv1_3 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:99 ipv4:0 ipv6:20
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 1
ip-quality: 1140
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by tq01o3n** [comment]
自己看ping多少?

**Comment by xxnet** [comment]
试试  4.4.3  
#13348
