### ISSUE TITLE
设置代理时SwitchyOmega中的规则列表网址加载不出来

### ISSUE THREAD

**Issue by jrjacky** [XX-net/XX-Net#13355]
设置代理时SwitchyOmega中的规则列表网址：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 加载不出来，导致无法更新情景模式
![](https://s1.ax1x.com/2020/08/22/ddw3Mn.jpg)

**Comment by alexwongdl** [comment]
请问是怎么解决的
