### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by shizhongyu** [XX-net/XX-Net#1335]
Nov 07 14:26:49 - ============ Begin upload ============ 
Nov 07 14:26:49 - ============ Begin upload ============
appid:zhongyu-1103

Nov 07 14:26:49 - Application: zhongyu-1103
Nov 07 14:26:49 - Host: appengine.google.com
Nov 07 14:26:49 - Rolling back the update.
Nov 07 14:27:12 - upload fail: The read operation timed out

Nov 07 14:27:12 - Retry 1 time...

Nov 07 14:27:12 - Application: zhongyu-1103
Nov 07 14:27:12 - Host: appengine.google.com
Nov 07 14:27:12 - Rolling back the update.
Nov 07 14:27:33 - upload fail: The read operation timed out

Nov 07 14:27:33 - Retry 2 time...

Nov 07 14:27:34 - Application: zhongyu-1103
Nov 07 14:27:34 - Host: appengine.google.com
Nov 07 14:27:34 - Rolling back the update.
Nov 07 14:27:54 - upload fail: The read operation timed out

Nov 07 14:27:54 - Retry 3 time...

Nov 07 14:27:56 - Application: zhongyu-1103
Nov 07 14:27:56 - Host: appengine.google.com
Nov 07 14:27:56 - Rolling back the update.
Nov 07 14:28:16 - upload fail: The read operation timed out

Nov 07 14:28:16 - Retry 4 time...

Nov 07 14:28:19 - Application: zhongyu-1103
Nov 07 14:28:19 - Host: appengine.google.com
Nov 07 14:28:19 - Rolling back the update.
Nov 07 14:28:39 - upload fail: The read operation timed out

Nov 07 14:28:39 - Retry 5 time...

Nov 07 14:28:43 - Application: zhongyu-1103
Nov 07 14:28:43 - Host: appengine.google.com
Nov 07 14:28:43 - Rolling back the update.
Nov 07 14:29:03 - upload fail: The read operation timed out

Nov 07 14:29:03 - Retry 6 time...

Nov 07 14:29:08 - Application: zhongyu-1103
Nov 07 14:29:08 - Host: appengine.google.com
Nov 07 14:29:08 - Rolling back the update.
Nov 07 14:29:28 - upload fail: The read operation timed out

Nov 07 14:29:28 - Retry 7 time...

Nov 07 14:29:34 - Application: zhongyu-1103
Nov 07 14:29:34 - Host: appengine.google.com
Nov 07 14:29:34 - Rolling back the update.
Nov 07 14:29:54 - upload fail: The read operation timed out

Nov 07 14:29:54 - Retry 8 time...

Nov 07 14:30:01 - Application: zhongyu-1103
Nov 07 14:30:01 - Host: appengine.google.com
Nov 07 14:30:01 - Rolling back the update.
Nov 07 14:30:21 - upload fail: The read operation timed out

Nov 07 14:30:21 - Retry 9 time...

Nov 07 14:30:29 - Application: zhongyu-1103
Nov 07 14:30:29 - Host: appengine.google.com
Nov 07 14:30:29 - Rolling back the update.
Nov 07 14:30:49 - upload fail: The read operation timed out

Nov 07 14:30:49 - Retry 10 time...

Nov 07 14:30:58 - Application: zhongyu-1103
Nov 07 14:30:58 - Host: appengine.google.com
Nov 07 14:30:58 - Rolling back the update.
Nov 07 14:31:18 - upload fail: The read operation timed out

Nov 07 14:31:18 - Retry 11 time...

Nov 07 14:31:28 - Application: zhongyu-1103
Nov 07 14:31:28 - Host: appengine.google.com
Nov 07 14:31:28 - Rolling back the update.
Nov 07 14:31:48 - upload fail: The read operation timed out

Nov 07 14:31:48 - Retry 12 time...

Nov 07 14:31:59 - Application: zhongyu-1103
Nov 07 14:31:59 - Host: appengine.google.com
Nov 07 14:31:59 - Rolling back the update.
Nov 07 14:32:19 - upload fail: The read operation timed out

Nov 07 14:32:19 - Retry 13 time...

Nov 07 14:32:31 - Application: zhongyu-1103
Nov 07 14:32:31 - Host: appengine.google.com
Nov 07 14:32:31 - Rolling back the update.

**Comment by xyuanmu** [comment]
可以使用自带的appid访问：appengine.google.com 吗？先用自带的id等扫描到足够的IP再试试。

**Comment by Zhangxiaoran** [comment]
没有扫描到IP，我的也是这种情况，不知道怎么解决

**Comment by xxnet** [comment]
先扫描到ip，可以访问google了，再去部署服务端

在 2015年11月8日 上午12:24，Zhangxiaoran <notifications@github.com>写道：
