### ISSUE TITLE
如何关闭 gae_proxy 只用x-tunnel？ 

### ISSUE THREAD

**Issue by liaoliaowuchen** [XX-net/XX-Net#13361]
gae_proxy基本不能用2-3年了，我已经习惯只用x-tunnel。原来的config.yaml，设置
gae_proxy: {auto_start: 0, show_detail: 1}，停掉gae_proxy, 以免浪费cpu资源。
刚刚升级4.5.1，找不到config.yaml。在config.json中，也找不到配置项。请给个办法。谢谢

**Comment by miketwes** [comment]
可以试将 XX-Net/code/default/launcher/module_init.py 中的

`for module in config.all_modules:` 
改为:
`for module in ["launcher", "x-tunnel", "smart_router"]:`
或:
` for module in ["launcher", "x-tunnel"]:`

**Comment by liaoliaowuchen** [comment]
不行。如果这样修改，x-tunnel的账号登录就卡死了。

**Comment by miketwes** [comment]
> 不行。如果这样修改，x-tunnel的账号登录就卡死了。

没有用过 x-tunnel, 你可以试一下gae_proxy 版本的 [XX-Net](https://github.com/miketwes/XX-Net-mini), 我一直在用

**Comment by liaoliaowuchen** [comment]
不行。gae_proxy我以前一直用，部署了20个appid。后来有一天ip就都失效了。虽然有一阵可以找到一些，但过一阵就失效。后来使用x-tunnel，基本上就没有问题，就是停顿几分钟连一次，不过查资料足够用了。就再也不想费事使用gae了

**Comment by xxnet** [comment]
只需要把gae_proxy的扫描线程改成0或1就可以基本不浪费CPU资源。
完全不启动的设置是修改 data/launcher/config.json
中间放一行：
  "enable_gae_proxy": 0,
注意json格式

下一个版本会允许在web界面上关闭gae_proxy

**Comment by liaoliaowuchen** [comment]
这方法有效！谢谢了！
顺便赞一下4.5.1的x-tunnel，好像解决了原来停顿几分钟没有相应的问题！
