### ISSUE TITLE
能否加上【局域网共享】的选项？

### ISSUE THREAD

**Issue by think2011** [XX-net/XX-Net#134]
也就是原来的设置为IP，0.0.0.0，从而其他设备、电脑可以访问有部署goAgent的服务。

**Comment by xxnet** [comment]
需要的请自己修改 goagent/x.x.x/local/proxy.ini
 因为需要导入证书，很不方便，喜欢折腾的可以手动改，就不把这个设置暴露给普通用户了。


在 2015年4月12日 下午12:11，曾浩 <notifications@github.com>写道：

**Comment by think2011** [comment]
@xxnet  明白了，谢谢！
