### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by c2xvi** [XX-net/XX-Net#13420]

**Comment by xxnet** [comment]
只需要把 Xndroid项目升级到python3，然后默认改为X-tunnel就可以了。
这是要做的，只是最近比较忙

**Comment by Chem2080** [comment]
> 只需要把 Xndroid项目升级到python3，然后默认改为X-tunnel就可以了。 这是要做的，只是最近比较忙

彳亍，我自己去试试

**Comment by xxnet** [comment]
Cool!
有啥问题可以一起探讨。

**Comment by Chem2080** [comment]
> Cool! 有啥问题可以一起探讨。

So,Python运行库怎么更新呢？

**Comment by Chem2080** [comment]
现在只要更新一下运行库就可以解决很多问题了

**Comment by xxnet** [comment]
可以参考这里：
https://github.com/kivy/python-for-android
