### ISSUE TITLE
Xtunnel无法登录

### ISSUE THREAD

**Issue by Chem2080** [XX-net/XX-Net#13468]
这几天X-Tunnel根本没法登录(Xndroid1.3.2)，一直显示[Debug]get front fail，什么状况呢？
补充一下，坐标杭州

**Comment by Chem2080** [comment]
win在更新4.5.3之后手机还是不行

**Comment by xxnet** [comment]
windows 上的4.5.3 能用不？

**Comment by Chem2080** [comment]
> windows 上的4.5.3 能用不？

现在没有win设备，难说

**Comment by FriendLinksChem2080** [comment]
@xxnet 现在手机上根本没法用，试过了好几种网络环境，估计只有win可以了
