### ISSUE TITLE
dalao们，我问一下，在China的银行里办理的visa卡可以搞gae吗？

### ISSUE THREAD

**Issue by Chem2080** [XX-net/XX-Net#13479]
dalao们，我问一下，在China的银行里办理的visa卡可以搞gae吗？

**Comment by whylalacantuse** [comment]
https://github.com/XX-net/XX-Net/issues/13413#issuecomment-723184366
可以看看这个，不知道现在能不能行。
另，visa也得看是不是信用卡，看评论里说的似乎只有信用卡才行
