### ISSUE TITLE
请教有关谷歌搜索的问题

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#13471]
www.google.com/ncr

平时我都是用上面的链接来进入google搜索。

自从用x-tunnel之后发现一些变化。

以前用GAEPROXY，是这样的界面（图1）。
![01](https://user-images.githubusercontent.com/39740368/106293053-85839700-6288-11eb-8b7d-5ac82c05a443.jpg)

但是用了x-tunnel之后，就变成了这样的界面（图2）。
![02](https://user-images.githubusercontent.com/39740368/106293119-97653a00-6288-11eb-971b-657e96bbc569.jpg)

但是搜索结果来说，我比较倾向于用GAEPROXY进入谷歌搜索出来的结果。

请问有什么方法，用x-tunnel也可以进入图1的界面？

谢谢。

还有在搜索出来的结果，在页面的下方，也有不同。

用GAEPROXY进入谷歌搜索，搜索结果下面显示：Unknown - Use precise location

用x-tunnel进入谷歌搜索，搜索结果下面显示：United States - From your Internet address - Use precise location

**Comment by xxnet** [comment]
X-tunnel 默认的出口ip是美国，你可以试试切换到日本或者德国的ip

**Comment by robinlighting** [comment]
> X-tunnel 默认的出口ip是美国，你可以试试切换到日本或者德国的ip

X大，用X-tnunel怎么切换日本IP或者德国IP？谢谢。

**Comment by robinlighting** [comment]
刚刚试了一下，X-tunnel换了服务器，还是一样。

得不到GAEPROXY的效果。

**Comment by xxnet** [comment]
GAEProxy 是直连的，Google 可以看到ip是中国的。
你可以试试用SwichyOmega 智能切换，访问www.google.com时用GAE，自己设定规则.

**Comment by robinlighting** [comment]
嗯嗯，谢谢。
