### ISSUE TITLE
快到期了，送些x-tunnel流量吧

### ISSUE THREAD

**Issue by whylalacantuse** [XX-net/XX-Net#13477]
每人50或100G，留下自己需要的流量和邮箱，按先后顺序发放，送完为止

**Comment by robinlighting** [comment]
coydonlighting-robin@outlook.com

50G

谢谢.

**Comment by Zac-Blacker** [comment]
blackyelement@Gmail.com
想要100g
非常感谢！

**Comment by whylalacantuse** [comment]
> [coydonlighting-robin@outlook.com](mailto:coydonlighting-robin@outlook.com)
> 
> 50G
> 
> 谢谢.

已发送，看到后可以回复一下我发的这个流量的到期时间吗？

**Comment by robinlighting** [comment]
> > [coydonlighting-robin@outlook.com](mailto:coydonlighting-robin@outlook.com)
> > 50G
> > 谢谢.
> 
> 已发送，看到后可以回复一下我发的这个流量的到期时间吗？

到期时间 2021-3-2

**Comment by whylalacantuse** [comment]
> 
> 到期时间 2021-3-2

谢谢，祝你冲浪愉快

**Comment by kfmyj** [comment]
goodmyj@gmail.com 想要50G，谢谢

**Comment by vswe2000** [comment]
92chenzhong@gmail.com
想要50G, 感谢

**Comment by luweitu** [comment]
992671990@qq.com
想要50G，谢谢大佬

**Comment by Sharedaily** [comment]
学生党,最近查找资料多,1天100M也不够.希望大佬送50G.
QQ邮箱(推荐):2748139943@qq.com
gmail邮箱:pan.speedx@gmail.com

**Comment by leo07046219** [comment]
散财童子 哈哈，看到晚了，刚入了300G

**Comment by whylalacantuse** [comment]
> 散财童子 哈哈，看到晚了，刚入了300G

哈哈，反正快过期了我也用不了到时浪费了，不如福利朋友们

**Comment by lzxqaq** [comment]
现在还有吗。。。lzxqaq@outlook.com,50G,非常感谢。

**Comment by kaka6119** [comment]
qym3779@gmail.com   50G 感谢大佬分享

**Comment by runck** [comment]
longhutiger@foxmail.com
50G够用了，感谢朋友分享！

**Comment by lan954** [comment]
lanjinhui12#gmail.com
谢谢！

**Comment by neorexer** [comment]
sfdrex@gmail.com 谢谢大佬

**Comment by RorschachXu** [comment]
1341675496x@gmail.com

**Comment by RorschachXu** [comment]
1341675496x@gmail.com
50G或100G都行，谢谢大佬

**Comment by RorschachXu** [comment]
收到了，谢谢！

**Comment by cslxiao** [comment]
还有剩的吗？50/100均可，谢谢（cslxiao@163.com）

**Comment by PPXZ1** [comment]
请问还有吗  valamoglis@gmail.com

**Comment by whylalacantuse** [comment]
> 请问还有吗 [valamoglis@gmail.com](mailto:valamoglis@gmail.com)

还有，但是这两天服务器抽风，给不了

**Comment by TIGERUNNAMED** [comment]
大佬还有吗，求50，谢谢了 94917148@bupt.edu.com

**Comment by whylalacantuse** [comment]
> 大佬还有吗，求50，谢谢了 [94917148@bupt.edu.com](mailto:94917148@bupt.edu.com)

你能正常使用x-tunnel吗？。。我这几天不知道为啥用不了

**Comment by hyrulegangster** [comment]
link@imail.anonaddy.com 感谢楼主 50G就够

**Comment by tq01o3n** [comment]
tq01o3n@gmail.com,谢谢!50G就够了

**Comment by wgqwgqwgq** [comment]
196304611@qq.com 谢谢

**Comment by whylalacantuse** [comment]
由于服务器故障，似乎送了好多给同一个人。。已经没有了
