### ISSUE TITLE
给其他设备代理问题

### ISSUE THREAD

**Issue by xiaozixun** [XX-net/XX-Net#13499]
* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？
是
* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？
是
* 是否以相关关键词搜索过类似 issues？
是
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，不遵守规则的提问会被自动关闭。

我想给我的mate40 pro上的每夜版火狐代理，操纵步骤是这样的
1.先在http://127.0.0.1:8085/开启了“允许远程访问控制页”；
2.在wifi设置的代理中改成了自动（http://电脑ip:8086/proxy.pac）
3.为手机导入/data/gae_proxy证书（用于vpn和应用和wlan都试过，都是单独）；
4.修改/data/gae_proxy与/data/smart_router的config.json和manual.ini；
5.访问http://电脑ip:8086/proxy.pac（可以访问）；
6.访问谷歌连接超时（证书用于wlan）或代理服务器拒绝连接（证书用于vpn和应用）
7.试图把wifi设置改成手动（电脑ip:8087）则显示不安全。
我看了几个issues，有个提到说安卓7以上就不支持用户证书了，是这个原因吗？还是我json和ini设置有问题？
下面是我的设置
/smart_router

config.json：
{
  "auto_direct6": 1,
  "dns_bind_ip": "0.0.0.0",
  "proxy_bind_ip": "0.0.0.0"
}

manual.ini：
[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
adblock = http://adblock-chinalist.googlecode.com/svn/trunk/adblock.txt
; this project have stopped.
expired = 86400

[listen] 
ip = 0.0.0.0

/gae_proxy

config.json

{
  "GAE_APPIDS": [
    "我的id",
  ],
  "listen_ip": "0.0.0.0"
}

manual.ini同smart_router的设置

**Comment by fx606** [comment]
LAN分享连接使用X-tunnel最简单，只要在手机或pad的proxy参数设置 127.0.0.1：1080  立马搞定。

**Comment by xiaozixun** [comment]
> 
> 
> LAN分享连接使用X-tunnel最简单，只要在手机或pad的proxy参数设置 127.0.0.1：1080 立马搞定。

我只是想知道gae的设置是怎么回事
