### ISSUE TITLE
流量快到期了，有需要的吗？

### ISSUE THREAD

**Issue by dousee163** [XX-net/XX-Net#13516]
留一下信箱

**Comment by 1540915215** [comment]
刚好流量快用完了，谢谢！dongping1996@gmail.com

**Comment by dousee163** [comment]
> 刚好流量快用完了，谢谢！[dongping1996@gmail.com](mailto:dongping1996@gmail.com)

已转100GB

**Comment by diddo-y** [comment]
谢谢！sagaromance@gmail.com

**Comment by dousee163** [comment]
> sagaromance@gmail.com

100G

**Comment by ga9vac** [comment]
感谢大佬，asusc99@gmail.com

**Comment by dousee163** [comment]
> asusc99@gmail.com

100G

**Comment by ga9vac** [comment]
谢谢

dousee163 ***@***.***> 于2021年5月6日周四 下午1:59写道：

**Comment by MyGhost233** [comment]
q123456789@gmail.com 十分感谢！

**Comment by dousee163** [comment]
> q123456789@gmail.com

100G

**Comment by luweitu** [comment]
刚看到，正好需要，谢谢大佬。。992671990@qq.com

**Comment by wangtingit** [comment]
善良的大佬，给你点赞，感谢 wt.smiles@gmail.com

**Comment by dousee163** [comment]
> 善良的大佬，给你点赞，感谢 [wt.smiles@gmail.com](mailto:wt.smiles@gmail.com)

100G
