### ISSUE TITLE
有没有大佬可以送点流量 万分感谢

### ISSUE THREAD

**Issue by excellenttank** [XX-net/XX-Net#13512]
谢谢  账号:zhuguailover@gmail.com

**Comment by dousee163** [comment]
已转 100G

**Comment by excellenttank** [comment]
> 已转 100G

非常感谢

**Comment by Redamancys** [comment]
用这个https://github.com/dodois/Doisnet 也不错啊，目前好像是免费的，而且不限流量

**Comment by odin1314** [comment]
odin1573@hotmail.com  万分感谢，^_^
