### ISSUE TITLE
以前部署过APPID，现在能否只是更新一下就可以了？

### ISSUE THREAD

**Issue by chen5410178** [XX-net/XX-Net#13539]
**请问，有没有可以直接更新的教程？**

**Comment by nly4lov** [comment]
我一直是这么干的：新版本下载来，解压，覆盖到原来的目录。并没有重新部署。

**Comment by chen5410178** [comment]
前面用自己的APPID就是提示没有部署，最后尝试了几天又可以设置自己的APPID了。

**Comment by nly4lov** [comment]
> 前面用自己的APPID就是提示没有部署，最后尝试了几天又可以设置自己的APPID了。

忘了说，每次覆盖后，首次要右键管理员运行start.bat

**Comment by gxggsrmyy** [comment]
@xxnet   gae服务端还是 python2 开发的，有打算升级到 python3 吗？python2 官方已经不支持了，说不定哪天google 就不支持用python2 部署服务端了
