### ISSUE TITLE
本项目里的win32_proxy_manager.py作为module在别的Python 程序里使用的问题

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net#13534]
我把本项目里的[win32_proxy_manager.py](https://github.com/XX-net/XX-Net/blob/master/code/default/lib/win32/win32_proxy_manager.py)作为module在别的Python 程序里使用，代码里只用到
`win32_proxy_manager.set_proxy('http://127.0.0.1:23006/proxy.pac')`
但设置后pac规则感觉无法立即生效，所以想请问一下是不是还要通知系统设置已变更才行呢？这又要怎么做？

**Comment by SeaHOH** [comment]
尝试子进程方式调用而不是直接调用。

**Comment by redstoneleo** [comment]
@SeaHOH 调用哪个子进程？win32_proxy_manager.py就是个module啊

**Comment by SeaHOH** [comment]
把你上面的代码单独写个脚本，然后在主进程中通过 Popen 调用。

**Comment by redstoneleo** [comment]
> 把你上面的代码单独写个脚本，然后在主进程中通过 Popen 调用。

我看本项目的代码也是import的方式使用的。

@xxnet 能否指点一下？谢谢！

**Comment by xxnet** [comment]
这个代码是7年前弄的了，我也忘记细节了。
我看了下代码，win32_proxy_manager 内部已经调用windll.wininet.InternetSetOptionW
通知系统变更代理了。
所以理论上是可以直接调用工作的。

这个文件最后有
`
if __name__ == "__main__":
    set_proxy("127.0.0.1:8087")
`
这个文件是可以独立执行的，你可以先试一下。

我无法直接给出答案说你遇到的问题在哪里，这里给出研究的思路：
从可以工作的版本出发，比如XX-Net 原版，确认切换代理可以工作。
然后通过逐步剔除其他部分、测试，看哪一步，或哪一些改动会导致无法工作。
