### ISSUE TITLE
mac 10.14.6+4.5.3+py 3.9.6 无法启动

### ISSUE THREAD

**Issue by inforli** [XX-net/XX-Net#13531]
Last login: Tue Jul  6 11:46:17 on ttys000
muzideMacBook-Pro:~ Muzi$ /Users/Muzi/Downloads/FQ/XX-Net-4.5.3/start ; exit;
XX-Net version:4.5.3
Run XX-Net in background.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

![WechatIMG27](https://user-images.githubusercontent.com/32029571/124539859-d2c7ee00-de50-11eb-97b7-0265387da3c5.jpeg)

**Comment by inforli** [comment]
@SeaHOH

**Comment by SeaHOH** [comment]
进 data 文件夹找到日志文件贴出来，如果是小问题可以帮忙解决。

**Comment by inforli** [comment]
处理好了，1080端口被占用了，关了就可以了


发自我的iPhone
