### ISSUE TITLE
连接服务器失败：session server login fail:602

### ISSUE THREAD

**Issue by Master-OAP** [XX-net/XX-Net#13543]
2021-07-24 21:16:50.757 - [WARNING] front retry v17.xx-net.org/data

2021-07-24 21:16:51.764 - [WARNING] login session fail, status:602
今天不知道为什么突然gg了
我现在勉强能整个issue，文档看过了，没找到方法

**Comment by BigGun-Z** [comment]
作者大大救一下🥺

**Comment by BigGun-Z** [comment]
邮箱是zhangzihaozzzzzz@gmail.com

**Comment by DanaYe** [comment]
> 作者大大救一下🥺

我昨天也是，一直连不上。后来Teredo使用默认隧道，X-Tunnel 设置里选择Chicago服务器就可以了，如果实在不行，你试试我这个

**Comment by DanaYe** [comment]
X-Tunnel 服务器设置，可以直接在XX-Net\data\x_tunnel\client.js里添加一句"server_host": "v13.xx-net.org"

**Comment by BigGun-Z** [comment]
换成chicago有用
谢谢！！！

**Comment by meixiaba** [comment]
> "server_host": "v13.xx-net.org"

谢谢

**Comment by wfdubowen** [comment]
我是换成了Miami的服务器也可以

**Comment by DanaYe** [comment]
> 我是换成了Miami的服务器也可以

好的，留着备用。因为我换成日本那个就不行，所以就没敢试其他的了

**Comment by Phil-Chang** [comment]
换成chicago也不行了，还有别的招么？

**Comment by xintianweng412** [comment]
> 我是换成了Miami的服务器也可以
我现在是什么服务器都登不上去了 ，你们呢

**Comment by Master-OAP** [comment]
我换方案了，这个便宜但是不稳定，整了个贵点的

**Comment by DanaYe** [comment]
> 我换方案了，这个便宜但是不稳定，整了个贵点的

推荐一下呀~我之前用的【谷歌上网助手】里买的会员，倒是挺稳定
