### ISSUE TITLE
突然提示请检查浏览器代理设置，证书已经导入

### ISSUE THREAD

**Issue by 120003808** [XX-net/XX-Net#13556]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134-SP0
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
xxnet-version: 4.5.3
python-version: 3.8.2
openssl-version: OpenSSL 1.1.1d  10 Sep 2019 TLSv1_3 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1216 ipv4:353 ipv6:35
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:19
scan-ip-thread-num: 200
ip-quality: 733
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
我的也是。代理直接切换到XX，就蓝了。然后仍然翻不出
