### ISSUE TITLE
gae_exception: '605:status:500'

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#13554]
状态显示正常但是开任何网页都显示 ‘605:status:500’

2021-08-14 08:08:23.242 - [WARNING] gae_exception:**'605:status:500'** https://apituner.ecbsn.com/apituner/v1/store/reward/list?channel=4

2021-08-14 08:08:23.242 - [WARNING] GAE GET https://apituner.ecbsn.com/apituner/v1/store/reward/list?channel=4 request **fail:'605:status:500'**

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.19041-SP0
os-system: Windows
os-version: 10.0.19041
os-release: 10
os-detail: Version:10-0; Build:19043; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.25 Safari/537.36 Edg/93.0.961.18
xxnet-version: 4.5.3
python-version: 3.8.2
openssl-version: OpenSSL 1.1.1d  10 Sep 2019 TLSv1_3 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:907 ipv4:318 ipv6:183
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:0 h2:38
scan-ip-thread-num: 118
ip-quality: 737
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by shaboyi999** [comment]
same......

**Comment by ksi1110** [comment]
一样，看日志很多载入都会报500

**Comment by silentzpf** [comment]
从昨天晚上开始的~日志里面大多数都会报500错误~

**Comment by Phil-Chang** [comment]
一样的问题

**Comment by sky123456789sky** [comment]
same

**Comment by lyfbuaa** [comment]
一样

**Comment by husitong** [comment]
一样的问题

**Comment by snoopy3841** [comment]
你们的浏览器代理和ca证书也是fail吗

**Comment by husitong** [comment]
OK的也没用

**Comment by husitong** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.19041-SP0
os-system: Windows
os-version: 10.0.19041
os-release: 10
os-detail: Version:10-0; Build:19042; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
xxnet-version: 4.5.3
python-version: 3.8.2
openssl-version: OpenSSL 1.1.1d  10 Sep 2019 TLSv1_3 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:100 ipv4:14 ipv6:84
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:20
scan-ip-thread-num: 73
ip-quality: 474
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by asd1219** [comment]
这个500错误，应该是gae端的问题

**Comment by pinocc01** [comment]
problem +1

**Comment by htpao2** [comment]
+1

**Comment by 6keduo** [comment]
+1

**Comment by hzx505** [comment]
+1

**Comment by miketwes** [comment]
同样的问题，快速刷新几次就好了

**Comment by ridforge** [comment]
部署的ID是不是有问题啊换公共appID可以上但自己的appID全部没法用甚至配置不上

**Comment by pudy** [comment]
同样的现象，昨天突然出现的，本来最新特别稳定来着

**Comment by machao1989** [comment]
+1

**Comment by tzabcd** [comment]
+1,  显示状态正常， 605:status:500

**Comment by ksi1110** [comment]
各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了

**Comment by pinocc01** [comment]
> 各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了

这么说好像是Google方面的问题了，是自己的appid死了。。。

**Comment by qizhiyanhuang** [comment]
> 各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了

怎么测试

**Comment by ksi1110** [comment]
> > 各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了
> 
> 怎么测试

最简单方法：假设你的appid是 myid，用浏览器通过GAE_Proxy代理访问 myid.appspot.com, 如果出现”GoAgent 服务端已经在 xxxxxxx 升级到 3.3.1 版本, 请更新您的客户端。”这样的字眼，就说明部署成功，否则需要重新部署。
这个是部署id时候的测试方法，或者登陆console.cloud.google.com，查看已经部署的应用状态，连接和trace，或者cloudshell查看，正在研究中~~~

**Comment by qizhiyanhuang** [comment]
> > > 各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了
> > 
> > 
> > 怎么测试
> 
> 最简单方法：假设你的appid是 myid，用浏览器通过GAE_Proxy代理访问 myid.appspot.com, 如果出现”GoAgent 服务端已经在 xxxxxxx 升级到 3.3.1 版本, 请更新您的客户端。”这样的字眼，就说明部署成功，否则需要重新部署。
> 这个是部署id时候的测试方法，或者登陆console.cloud.google.com，查看已经部署的应用状态，连接和trace，或者cloudshell查看，正在研究中~~~

thx，等待大佬新发现

**Comment by tzabcd** [comment]
貌似不是appid的问题啊, 因为使用公用的appid 问题还是一样的

**Comment by pinocc01** [comment]
> 貌似不是appid的问题啊, 因为使用公用的appid 问题还是一样的

刚开始看到本帖，把自己的appid删了使用公用id，代理还能工作，大概半个小时后公用id也死了，当然现在还是死的

**Comment by robinlighting** [comment]
此类的问题，以前也出现过。坐等X大更新吧。
![1](https://user-images.githubusercontent.com/39740368/129469049-31b58f57-4af5-4904-a5aa-78191bf8096c.jpg)

**Comment by pinocc01** [comment]
应该是账号没有绑定信用卡的云服务都被禁了。。
虽然早就说要禁，实际上这几天才执行
现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活

**Comment by Quantum2Bits** [comment]
> 应该是账号没有绑定信用卡的云服务都被禁了。。
> 虽然早就说要禁，实际上这几天才执行
> 现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活

是的

**Comment by lyfbuaa** [comment]
咋办，验证码这个不好弄啊？

**Comment by snipertulip** [comment]
> 各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了

我进去看了一下，实例都没有了。服务里面还能看到代码

**Comment by iSuperYang** [comment]
部署验证提示：status:500

**Comment by cym104** [comment]
#应该是账号没有绑定信用卡的云服务都被禁了。。
#虽然早就说要禁，实际上这几天才执行
#现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活

感谢提醒，原来是我光顾着创建了结算账号，却忘了把结算账号关联到项目上

**Comment by sky123456789sky** [comment]
已经关联了还是不行啊

**Comment by cym104** [comment]
> 已经关联了还是不行啊

那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到项目/appid上就好了

**Comment by robinlighting** [comment]
> > 已经关联了还是不行啊
> 
> 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了

那就奇怪了。

我的没有绑定信用卡，只能上油管和谷歌搜索，但是速度比较慢。

其他的都是显示500

**Comment by cym104** [comment]
我的现在已经完全正常了

**Comment by cym104** [comment]
> > > 已经关联了还是不行啊
> > 
> > 
> > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> 
> 那就奇怪了。
> 
> 我的没有绑定信用卡，只能上油管和谷歌搜索，但是速度比较慢。
> 
> 其他的都是显示500

我的现在已经完全正常了

**Comment by sky123456789sky** [comment]
我的也可以了 但是不知道扣费不？如果扣费 还不如买个机场划算

**Comment by smallstone000** [comment]
> 我的也可以了 但是不知道扣费不？如果扣费 还不如买个机场划算

怎么弄的

**Comment by smallstone000** [comment]
> > 各位可以测试下各自部署的appid，我部署的12个应用里面只有2个还存活，其他全部连不上了
> 
> 我进去看了一下，实例都没有了。服务里面还能看到代码

我刚才看了下，我的appid全都无效了

**Comment by Quantum2Bits** [comment]
> > 已经关联了还是不行啊
> 
> 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了

最多能绑定几个app？

**Comment by cym104** [comment]
> > > 已经关联了还是不行啊
> > 
> > 
> > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> 
> 最多能绑定几个app？

默认一个结算账户可以绑3个appid，但是一个账户下的结算账户的数量没限制。

**Comment by sky123456789sky** [comment]
> > 我的也可以了 但是不知道扣费不？如果扣费 还不如买个机场划算
> 
> 怎么弄的

把结算账户绑上 然后删掉不起作用的实例

**Comment by gitzxqjy** [comment]
> > 已经关联了还是不行啊
> 
> 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了

我五个appid里面有一个没有关联，就不断出现这个错误代码，看了大家的帖子，把那个没关联的给关联上就好了。

**Comment by gxggsrmyy** [comment]
@xx-net gae服务端还是 python2 开发的，有打算升级到 python3 吗？python2 官方已经不支持了，说不定哪天google 就不支持用python2 部署服务端了

**Comment by gxggsrmyy** [comment]
@xxnet     gae服务端还是 python2 开发的，有打算升级到 python3 吗？python2 官方已经不支持了，说不定哪天google 就不支持用python2 部署服务端了

**Comment by ablebodied** [comment]
same

**Comment by iSuperYang** [comment]
> > > 已经关联了还是不行啊
> > 
> > 
> > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> 
> 我五个appid里面有一个没有关联，就不断出现这个错误代码，看了大家的帖子，把那个没关联的给关联上就好了。

如何关联?有教程吗？

**Comment by iSuperYang** [comment]
> > 应该是账号没有绑定信用卡的云服务都被禁了。。
> > 虽然早就说要禁，实际上这几天才执行
> > 现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活
> 
> 感谢提醒，原来是我光顾着创建了结算账号，却忘了把结算账号关联到项目上

你是怎么关联的?

**Comment by cym104** [comment]
> > > 应该是账号没有绑定信用卡的云服务都被禁了。。
> > > 虽然早就说要禁，实际上这几天才执行
> > > 现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活
> > 
> > 
> > 感谢提醒，原来是我光顾着创建了结算账号，却忘了把结算账号关联到项目上
> 
> 你是怎么关联的?

项目橄榄页面上左边边栏选结算

**Comment by smallstone000** [comment]
> > > > 应该是账号没有绑定信用卡的云服务都被禁了。。
> > > > 虽然早就说要禁，实际上这几天才执行
> > > > 现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活
> > > 
> > > 
> > > 感谢提醒，原来是我光顾着创建了结算账号，却忘了把结算账号关联到项目上
> > 
> > 
> > 你是怎么关联的?
> 
> 项目橄榄页面上左边边栏选结算

能帮我弄个appid吗，没有visa信用卡怎么弄，原来的全都无效了

**Comment by candy870313** [comment]
> 
> 
> > > > > 应该是账号没有绑定信用卡的云服务都被禁了。。
> > > > > 虽然早就说要禁，实际上这几天才执行
> > > > > 现在不仅仅是要绑卡，还要有国外的手机号收验证码才能激活
> > > > 
> > > > 
> > > > 感谢提醒，原来是我光顾着创建了结算账号，却忘了把结算账号关联到项目上
> > > 
> > > 
> > > 你是怎么关联的?
> > 
> > 
> > 项目橄榄页面上左边边栏选结算
> 
> 能帮我弄个appid吗，没有visa信用卡怎么弄，原来的全都无效了

+1

**Comment by gxggsrmyy** [comment]
@xxnet gae服务端还是 python2 开发的，有打算升级到 python3 吗？python2 官方已经不支持了，说不定哪天google 就不支持用python2 部署服务端了

**Comment by string-fat** [comment]
实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。

**Comment by Phil-Chang** [comment]
这个绑定以后不会自动扣费吧

**Comment by EOE0102** [comment]
> 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。

确实可以的，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。只不过地址怎么填？虚假地址有影响吗？

**Comment by z10ym** [comment]
> > > > 已经关联了还是不行啊
> > > 
> > > 
> > > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> > 
> > 
> > 最多能绑定几个app？
> 
> 默认一个结算账户可以绑3个appid，但是一个账户下的结算账户的数量没限制。

试了一下用同一张万事达建多个结算账户，后面的账户都自动锁了，要上传身份证才解锁TAT

**Comment by Quantum2Bits** [comment]
> > > > > 已经关联了还是不行啊
> > > > 
> > > > 
> > > > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> > > 
> > > 
> > > 最多能绑定几个app？
> > 
> > 
> > 默认一个结算账户可以绑3个appid，但是一个账户下的结算账户的数量没限制。
> 
> 试了一下用同一张万事达建多个结算账户，后面的账户都自动锁了，要上传身份证才解锁TAT

是在同一个用户（邮箱地址）下建立多个结算帐号吗？

**Comment by z10ym** [comment]
> > > > > > 已经关联了还是不行啊
> > > > > 
> > > > > 
> > > > > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> > > > 
> > > > 
> > > > 最多能绑定几个app？
> > > 
> > > 
> > > 默认一个结算账户可以绑3个appid，但是一个账户下的结算账户的数量没限制。
> > 
> > 
> > 试了一下用同一张万事达建多个结算账户，后面的账户都自动锁了，要上传身份证才解锁TAT
> 
> 是在同一个用户（邮箱地址）下建立多个结算帐号吗？

对，我是在同一个邮箱下想建立新的结算账户失败了。并且成功的那个账户也只能绑定三个APPID，我看上面有人可以绑定5个，不知道和信用卡类型有没有关系。

**Comment by cym104** [comment]
> > > > > > > 已经关联了还是不行啊
> > > > > > 
> > > > > > 
> > > > > > 那不清楚了，我的是把有效的结算账户（已经绑定信用卡）关联到所有的项目/appid上就好了
> > > > > 
> > > > > 
> > > > > 最多能绑定几个app？
> > > > 
> > > > 
> > > > 默认一个结算账户可以绑3个appid，但是一个账户下的结算账户的数量没限制。
> > > 
> > > 
> > > 试了一下用同一张万事达建多个结算账户，后面的账户都自动锁了，要上传身份证才解锁TAT
> > 
> > 
> > 是在同一个用户（邮箱地址）下建立多个结算帐号吗？
> 
> 对，我是在同一个邮箱下想建立新的结算账户失败了。并且成功的那个账户也只能绑定三个APPID，我看上面有人可以绑定5个，不知道和信用卡类型有没有关系。

我用的visa卡

**Comment by cloudf85** [comment]
梯子没有了怎么google

**Comment by 6keduo** [comment]
还有其他利用ipv6的免费方法可用，就此告别xxnet了……

**Comment by snipertulip** [comment]
用 X-Tunnel Proxy 啊

**Comment by lyfbuaa** [comment]
这边X-Tunnel 也用不了了

**Comment by iSuperYang** [comment]
> 还有其他利用ipv6的免费方法可用，就此告别xxnet了……

有什么方法，能提供下吗？

**Comment by lyfbuaa** [comment]
“免费层级”用量限制
App Engine 	

    每天 28 个“F”实例小时
    每天 9 个“B”实例小时
    每天 1 GB 出站流量

Google Cloud 免费层级仅适用于标准环境。

**Comment by 6keduo** [comment]
> > 还有其他利用ipv6的免费方法可用，就此告别xxnet了……
> 
> 有什么方法，能提供下吗？

网上都有啊，与XXNET几乎一样省事，甚至更简单。比如Proxifier等……

**Comment by lyfbuaa** [comment]
> > 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。
> 
> 绑定成功，又可以用了
> 
> Q：国内手机能绑卡吗？
> A：国内手机可以绑定的。左侧栏“结算”栏进入，创建结算账户的时候，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。
> Q：只不过地址怎么填？虚假地址有影响吗？
> A：刚才绑上信用卡了，虚假地址不影响绑卡，我地区选择注重隐私保护的德国，乱打了个地名就通过了。google应该也不会没事就要你地址隐私。
> Q：信用卡怎么办？
> A：信用卡方面，国内各大银行都可以开通mastercard的（国内的银联信用卡没测试。记得办一张卡要一周，挂号信送家里，要本人亲自接收）。绑上后会扣款1元再取消扣款，检查信用卡可用情况。
> Q：要付钱的吗？
> A：看了协议，续费方面Google还是会免费用的，不会扣费，除非自己去点付费套餐。以后说不准。

“免费层级”用量限制
App Engine

每天 28 个“F”实例小时
每天 9 个“B”实例小时
每天 1 GB 出站流量

Google Cloud 免费层级仅适用于标准环境。

**Comment by lyfbuaa** [comment]
> > > 还有其他利用ipv6的免费方法可用，就此告别xxnet了……
> > 
> > 
> > 有什么方法，能提供下吗？
> 
> 网上都有啊，与XXNET几乎一样省事，甚至更简单。比如Proxifier等……

firefox 免费vpn扩展

**Comment by tq01o3n** [comment]
mark

**Comment by cccwhatuneed** [comment]
不会绑信用卡 白嫖了这么多年 正式告别xx-net...

感谢项目组 这么多年的付出

farewell

**Comment by cym104** [comment]
> Proxifier

想要靠谱又免费的翻墙工具，还得靠法轮功。

**Comment by ablebodied** [comment]
有没有人遇到这样的问题？怎么解决的？
> 启用了结算功能的项目已达数量上限。如果需要为更多项目启用结算功能，您可以申请提高结算功能配额。

**Comment by ablebodied** [comment]
有没有人遇到这样的问题？怎么解决的？
> 启用了结算功能的项目已达数量上限。如果需要为更多项目启用结算功能，您可以申请提高结算功能配额。

**Comment by jaryway** [comment]
同 visa 也是只能绑定三个。不过可以提交 提额申请，提交后很快会收到结果，收到结果后等一个小时自动提额了。一下提额了50个 😂

![image](https://user-images.githubusercontent.com/5987056/132130772-7cb70e4d-6083-4d0e-b21d-319045f71417.png)

**Comment by pudy** [comment]
> > > 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。
> > 
> > 
> > 绑定成功，又可以用了
> > Q：国内手机能绑卡吗？
> > A：国内手机可以绑定的。左侧栏“结算”栏进入，创建结算账户的时候，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。
> > Q：只不过地址怎么填？虚假地址有影响吗？
> > A：刚才绑上信用卡了，虚假地址不影响绑卡，我地区选择注重隐私保护的德国，乱打了个地名就通过了。google应该也不会没事就要你地址隐私。
> > Q：信用卡怎么办？
> > A：信用卡方面，国内各大银行都可以开通mastercard的（国内的银联信用卡没测试。记得办一张卡要一周，挂号信送家里，要本人亲自接收）。绑上后会扣款1元再取消扣款，检查信用卡可用情况。
> > Q：要付钱的吗？
> > A：看了协议，续费方面Google还是会免费用的，不会扣费，除非自己去点付费套餐。以后说不准。
> 
> “免费层级”用量限制
> App Engine
> 
> 每天 28 个“F”实例小时
> 每天 9 个“B”实例小时
> 每天 1 GB 出站流量
> 
> Google Cloud 免费层级仅适用于标准环境。

请问1G流量超了，会不会自动扣费

**Comment by meidong007** [comment]
> > > > 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。
> > > 
> > > 
> > > 绑定成功，又可以用了
> > > Q：国内手机能绑卡吗？
> > > A：国内手机可以绑定的。左侧栏“结算”栏进入，创建结算账户的时候，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。
> > > Q：只不过地址怎么填？虚假地址有影响吗？
> > > A：刚才绑上信用卡了，虚假地址不影响绑卡，我地区选择注重隐私保护的德国，乱打了个地名就通过了。google应该也不会没事就要你地址隐私。
> > > Q：信用卡怎么办？
> > > A：信用卡方面，国内各大银行都可以开通mastercard的（国内的银联信用卡没测试。记得办一张卡要一周，挂号信送家里，要本人亲自接收）。绑上后会扣款1元再取消扣款，检查信用卡可用情况。
> > > Q：要付钱的吗？
> > > A：看了协议，续费方面Google还是会免费用的，不会扣费，除非自己去点付费套餐。以后说不准。
> > 
> > 
> > “免费层级”用量限制
> > App Engine
> > 每天 28 个“F”实例小时
> > 每天 9 个“B”实例小时
> > 每天 1 GB 出站流量
> > Google Cloud 免费层级仅适用于标准环境。
> 
> 请问1G流量超了，会不会自动扣费

怎么上网站绑卡，现在网站都打不开

**Comment by zhudongya** [comment]
> > > > 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。
> > > 
> > > 
> > > 绑定成功，又可以用了
> > > Q：国内手机能绑卡吗？
> > > A：国内手机可以绑定的。左侧栏“结算”栏进入，创建结算账户的时候，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。
> > > Q：只不过地址怎么填？虚假地址有影响吗？
> > > A：刚才绑上信用卡了，虚假地址不影响绑卡，我地区选择注重隐私保护的德国，乱打了个地名就通过了。google应该也不会没事就要你地址隐私。
> > > Q：信用卡怎么办？
> > > A：信用卡方面，国内各大银行都可以开通mastercard的（国内的银联信用卡没测试。记得办一张卡要一周，挂号信送家里，要本人亲自接收）。绑上后会扣款1元再取消扣款，检查信用卡可用情况。
> > > Q：要付钱的吗？
> > > A：看了协议，续费方面Google还是会免费用的，不会扣费，除非自己去点付费套餐。以后说不准。
> > 
> > 
> > “免费层级”用量限制
> > App Engine
> > 每天 28 个“F”实例小时
> > 每天 9 个“B”实例小时
> > 每天 1 GB 出站流量
> > Google Cloud 免费层级仅适用于标准环境。
> 
> 请问1G流量超了，会不会自动扣费

超了流量肯定会被自动扣费，要不然让绑定信用卡干啥。以前1G流量超过之后google会停止APP，现在超流量后不会停止app，而是直接扣钱了。所以还是小心点用。

**Comment by pudy** [comment]
> > > > > 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。
> > > > 
> > > > 
> > > > 绑定成功，又可以用了
> > > > Q：国内手机能绑卡吗？
> > > > A：国内手机可以绑定的。左侧栏“结算”栏进入，创建结算账户的时候，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。
> > > > Q：只不过地址怎么填？虚假地址有影响吗？
> > > > A：刚才绑上信用卡了，虚假地址不影响绑卡，我地区选择注重隐私保护的德国，乱打了个地名就通过了。google应该也不会没事就要你地址隐私。
> > > > Q：信用卡怎么办？
> > > > A：信用卡方面，国内各大银行都可以开通mastercard的（国内的银联信用卡没测试。记得办一张卡要一周，挂号信送家里，要本人亲自接收）。绑上后会扣款1元再取消扣款，检查信用卡可用情况。
> > > > Q：要付钱的吗？
> > > > A：看了协议，续费方面Google还是会免费用的，不会扣费，除非自己去点付费套餐。以后说不准。
> > > 
> > > 
> > > “免费层级”用量限制
> > > App Engine
> > > 每天 28 个“F”实例小时
> > > 每天 9 个“B”实例小时
> > > 每天 1 GB 出站流量
> > > Google Cloud 免费层级仅适用于标准环境。
> > 
> > 
> > 请问1G流量超了，会不会自动扣费
> 
> 怎么上网站绑卡，现在网站都打不开

我用的手机上的免费vpn在手机上操作的，比如老王vpn

**Comment by pudy** [comment]
> > > > > 实测回来了，绑定银行卡就可以用了，一个付款帐号只能绑定5个APPID，接收验证码的手机号可以是中国的，信用卡绑定了之后好像就不能解了。
> > > > 
> > > > 
> > > > 绑定成功，又可以用了
> > > > Q：国内手机能绑卡吗？
> > > > A：国内手机可以绑定的。左侧栏“结算”栏进入，创建结算账户的时候，第一步选地区确实没有中国，但是第二步选电话号码，拉到最后就可以选+86的手机号了。
> > > > Q：只不过地址怎么填？虚假地址有影响吗？
> > > > A：刚才绑上信用卡了，虚假地址不影响绑卡，我地区选择注重隐私保护的德国，乱打了个地名就通过了。google应该也不会没事就要你地址隐私。
> > > > Q：信用卡怎么办？
> > > > A：信用卡方面，国内各大银行都可以开通mastercard的（国内的银联信用卡没测试。记得办一张卡要一周，挂号信送家里，要本人亲自接收）。绑上后会扣款1元再取消扣款，检查信用卡可用情况。
> > > > Q：要付钱的吗？
> > > > A：看了协议，续费方面Google还是会免费用的，不会扣费，除非自己去点付费套餐。以后说不准。
> > > 
> > > 
> > > “免费层级”用量限制
> > > App Engine
> > > 每天 28 个“F”实例小时
> > > 每天 9 个“B”实例小时
> > > 每天 1 GB 出站流量
> > > Google Cloud 免费层级仅适用于标准环境。
> > 
> > 
> > 请问1G流量超了，会不会自动扣费
> 
> 超了流量肯定会被自动扣费，要不然让绑定信用卡干啥。以前1G流量超过之后google会停止APP，现在超流量后不会停止app，而是直接扣钱了。所以还是小心点用。

我看Google政策貌似写的是免费试用账号不激活，赠送的$300用完了不会扣费。
当然我没验证过，还是小心为好，总之结算账号freetrail状态先别激活。
