### ISSUE TITLE
gae_exception: '605:status:500'的解决方案

### ISSUE THREAD

**Issue by belleyeah** [XX-net/XX-Net#13564]
其实就是google的策略正式实施了：所有appid都需要绑定信用卡，否则会被暂停服务。
在左侧的‘billing’，用国内的手机和带visa标志的信用卡（单币信用卡不行）。可以顺利添加结算账户。然后绑定3个appid即可。（无须重新部署），绑定后3个appid自动重新启动服务。
如果不放心，可以随时停止结算账户。

**Comment by cofe123** [comment]
那如何防止流量超标呢...
还有绑定3个后，10个全部生效?

**Comment by belleyeah** [comment]
> 那如何防止流量超标呢...
> 还有绑定3个后，10个全部生效?

1，还不知道。大家如有好办法也提出。
2，只有绑定的3个即时生效。

**Comment by 2378** [comment]
鉴于当下环境，给大家提个醒
当年第一个吃GAE螃蟹的大神phuslu早已喝茶删档
2年多前谷哥宣布绑卡政策，一众白嫖GAE项目或停更或关闭，也是那段时间蜻蜓计划曝光。
绑不绑卡，自行斟酌。

**Comment by cccwhatuneed** [comment]
> 那如何防止流量超标呢...
> 还有绑定3个后，10个全部生效?

Google不会管你流量是否超标 只会对超标的部分收费 你的应用只能是你自己设计检测流量
所以程序需要设计流量控制部分了

**Comment by nly4lov** [comment]
1，没有visa卡，2，既然都翻不出去了，即使有卡，也打不开绑卡页面了
完蛋了。

**Comment by 2378** [comment]
@nly4lov  有免费的短期通道，安全性无法验证，其实绑卡安全性也无法验证。用不用，自己斟酌吧

V/T/U/M |            Address |           Port |      Method |       Password |   |   |  

9↑/10↑/10↑/10↑  | 142.47.219.194 | 17478 | aes-256-cfb |  https://dlj.tf/ssrsub | 14:07:11 | CA |  
10↑/10↑/10↑/10↑ | 142.4.123.198  | 31131  | rc4 |               dongtaiwang.com | 14:07:09 | US |  
10↑/10↑/10↑/10↑ | 46.17.43.179    | 31131    | rc4 |              dongtaiwang.com 123abc | 14:07:11 | RU |  
10↑/10↑/10↑/10↑ | 89.163.214.9    | 31131 | rc4 |                dongtaiwang.com 123abc | 14:07:10 | DE |  
10↑/10↑/10↑/10↑ | 88.218.92.16    | 31131 | rc4 |                dongtaiwang.com 123abc | 14:07:10 | US |  
10↑/10↑/10↑/10↑ | 45.62.231.225  | 17478 | aes-256-cfb |  https://dlj.tf/ssrsub | 14:07:10 | CA |  
9↑/10↑/9↑/10↑     | 142.4.123.135  | 31131 | rc4 |                dongtaiwang.com | 14:07:09 | US |  
10↑/10↑/10↑/10↑ | 45.147.200.9    | 31131 | rc4 |                dongtaiwang.com 123abc | 14:07:05 | RU |  
10↑/10↑/10↑/10↑ | 198.200.51.18  | 31131 | rc4 |                 dongtaiwang.com | 14:07:09 | US |  
10↑/10↑/10↑/10↑ | 107.148.200.42 | 31131 | rc4 |               dongtaiwang.com | 14:07:10 | US |

**Comment by nly4lov** [comment]
> @nly4lov 有免费的短期通道，安全性无法验证，其实绑卡安全性也无法验证。用不用，自己斟酌吧
> 
> V/T/U/M | Address | Port | Method | Password |   |   |  
> 
> 9↑/10↑/10↑/10↑ | 142.47.219.194 | 17478 | aes-256-cfb | https://dlj.tf/ssrsub | 14:07:11 | CA |  
> 10↑/10↑/10↑/10↑ | 142.4.123.198 | 31131 | rc4 | dongtaiwang.com | 14:07:09 | US |  
> 10↑/10↑/10↑/10↑ | 46.17.43.179 | 31131 | rc4 | dongtaiwang.com 123abc | 14:07:11 | RU |  
> 10↑/10↑/10↑/10↑ | 89.163.214.9 | 31131 | rc4 | dongtaiwang.com 123abc | 14:07:10 | DE |  
> 10↑/10↑/10↑/10↑ | 88.218.92.16 | 31131 | rc4 | dongtaiwang.com 123abc | 14:07:10 | US |  
> 10↑/10↑/10↑/10↑ | 45.62.231.225 | 17478 | aes-256-cfb | https://dlj.tf/ssrsub | 14:07:10 | CA |  
> 9↑/10↑/9↑/10↑ | 142.4.123.135 | 31131 | rc4 | dongtaiwang.com | 14:07:09 | US |  
> 10↑/10↑/10↑/10↑ | 45.147.200.9 | 31131 | rc4 | dongtaiwang.com 123abc | 14:07:05 | RU |  
> 10↑/10↑/10↑/10↑ | 198.200.51.18 | 31131 | rc4 | dongtaiwang.com | 14:07:09 | US |  
> 10↑/10↑/10↑/10↑ | 107.148.200.42 | 31131 | rc4 | dongtaiwang.com | 14:07:10 | US |

谢谢，可是我没有可用的卡

**Comment by jaryway** [comment]
亲试，开通结算账户账户后最多只能绑定三个appid，不过可以**提交提额申请**，绑定更多的 appid，提交提额申请后会收到结果通知邮件，一个小时后额度就提升了，继续绑定即可。提额后还可以再添加appid，新增的appid自动绑定结算账户。

**Comment by jaryway** [comment]
绑卡后顺便把所有的服务都更新了一遍，xxnet又满血复活了。嘻嘻！

**Comment by zhudongya** [comment]
> 绑卡后顺便把所有的服务都更新了一遍，xxnet又满血复活了。嘻嘻！
小心超量被扣款啊。

**Comment by qq1097** [comment]
Can not open google web ,how to applic vist card?

**Comment by meidong007** [comment]
> 绑卡后顺便把所有的服务都更新了一遍，xxnet又满血复活了。嘻嘻！

打不开谷歌，你是怎么绑卡的

**Comment by jaryway** [comment]
> 打不开谷歌，你是怎么绑卡的

参考 @nly4lov 有免费的短期通道

**Comment by jessicapd2020** [comment]
> > 绑卡后顺便把所有的服务都更新了一遍，xxnet又满血复活了。嘻嘻！
> 
> 打不开谷歌，你是怎么绑卡的

我也有这个问题
