### ISSUE TITLE
最近是怎么了

### ISSUE THREAD

**Issue by zhangbin0922** [XX-net/XX-Net#13565]
全局pac代理不好使了 连接能连上 状态OK 但是就是上不了网

**Comment by Lancenas** [comment]
所有appid都需要绑定信用卡，否则会被暂停服务

**Comment by Lancenas** [comment]
所有appid都需要绑定信用卡，否则会被暂停服务

**Comment by xinmoming** [comment]
绑定信用卡就可以用了

**Comment by nly4lov** [comment]
https://github.com/XX-net/XX-Net/issues/13566#issue-981758817
