### ISSUE TITLE
购买的X-Tunnel，出现 “连接服务器失败：session server login fail:602” ，已经一个星期都没连上了

### ISSUE THREAD

**Issue by Varian020** [XX-net/XX-Net#13568]
已经一个多星期连不上了。更换服务器也没有用！

**Comment by xinmoming** [comment]
appid 绑定信用卡

**Comment by yuebe** [comment]
= = 口胡什么 x tunnel 要屁 appid

**Comment by yanjiuling** [comment]
尝试手动改选服务器试试，我是这样解决才可以用，现在的速度实在不行，梯子已经缺了半条腿。

**Comment by vinceliuice** [comment]
要是一直没法用就只能换梯子了

**Comment by csalhk** [comment]
> 尝试手动改选服务器试试，我是这样解决才可以用，现在的速度实在不行，梯子已经缺了半条腿。

你好，请问无法登录如何手动改选服务器？ 一直都是登录后在下拉菜单中选的。

**Comment by kwwgh** [comment]
我也是，之前还好，昨晚开始X-tunnel无法登录，到现在还没好。感觉这个项目确实没怎么维护了。

**Comment by vinceliuice** [comment]
谁有稳定实惠的梯子没，求推荐！

**Comment by bomeidesign** [comment]
我也是啊，无法链接啊，年会员呀，想看少康战情室，没法上去，超级难受的！！！！

**Comment by xintianweng412** [comment]
> 尝试手动改选服务器试试，我是这样解决才可以用，现在的速度实在不行，梯子已经缺了半条腿。

我之前还可以选择服务器，现在不知道为什么已经没法选择了。。。
麻烦可以看下miami的server是什么吗

**Comment by swjtu2004** [comment]
认证下就行

**Comment by ino1988** [comment]
> 
> 
> 认证下就行

大神，认证什么？怎么认证？能详细的介绍一下吗？
