### ISSUE TITLE
充值了的人真傻逼，哈哈哈用不了了吧

### ISSUE THREAD

**Issue by chinaniupai** [XX-net/XX-Net#13575]
笑死我了一群傻逼，冲你妈了个逼用不了了吧，想退款吗？退你妈了个逼退不了知道吗，有个傻狗说钱不能这么打水漂了，不好意思你的钱就是打水漂了。

**Comment by snipertulip** [comment]
搅屎棍

**Comment by zhudongya** [comment]
> 笑死我了一群傻逼，冲你妈了个逼用不了了吧，想退款吗？退你妈了个逼退不了知道吗，有个傻狗说钱不能这么打水漂了，不好意思你的钱就是打水漂了。

sha Jiba ren a

**Comment by Maogxer** [comment]
这人坏得要死。

**Comment by Yeahosi** [comment]
这是魔怔了？

**Comment by yanjiuling** [comment]
心智缺个腿

**Comment by swjtu2004** [comment]
依然可以用的

**Comment by bomeidesign** [comment]
就是用不了了，还依然可以用，搞笑，他说得是对的，X-TUNNEL年会员登录不上了！！！！！！

**Comment by swjtu2004** [comment]
> 就是用不了了，还依然可以用，搞笑，他说得是对的，X-TUNNEL年会员登录不上了！！！！！！

不会用就别用

**Comment by bomeidesign** [comment]
如果是免费的，教不教无所谓，因为没有义务。但我们一些人充了年会员的，你哪来的勇气讲我们别用？如果是软件作者，消费者看到你这个，谁还敢买呢，你还怎么赚钱？出问题没人处理，也不给个解决方案教程，让人家搞一下。市场上大把VPN，登录密码啥都不用管，就可以翻。你倒是充了2，3年会员呀，用不了看看你自己什么感受。说风凉话倒是轻松

**Comment by jessicapd2020** [comment]
> 依然可以用的

用不了啊，我也充钱的。

**Comment by chinaniupai** [comment]
> 如果是免费的，教不教无所谓，因为没有义务。但我们一些人充了年会员的，你哪来的勇气讲我们别用？如果是软件作者，消费者看到你这个，谁还敢买呢，你还怎么赚钱？出问题没人处理，也不给个解决方案教程，让人家搞一下。市场上大把VPN，登录密码啥都不用管，就可以翻。你倒是充了2，3年会员呀，用不了看看你自己什么感受。说风凉话倒是轻松

不知道什么叫GAE吗？goagent
