### ISSUE TITLE
服务器登录不上，不能用了啊，有能联系上作者的吗？

### ISSUE THREAD

**Issue by mochen91** [XX-net/XX-Net#13571]
服务器一直登录不上，作者是不是和当年网际快车的开发者一样去玩游戏了呀？从1月20日以后已经半年多没更新了，也没回答用户的问题了。
有没有可以联系上作者的，问问啥情况呀。
之前芝加哥的服务器还能用，现在也不能了，算是最后一块地也没了，全部失守，X-TUNNEL这就是彻底挂了呀。

**Comment by csalhk** [comment]
对，希望作者出来回复一下，都是充值了的

**Comment by swjtu2004** [comment]
软件还是能用的，没必要更新。这次是Google的原因。认证下就行
