### ISSUE TITLE
什么情况现在，不会是被请去喝咖啡了吧。

### ISSUE THREAD

**Issue by Yeahosi** [XX-net/XX-Net#13574]
翻墙现在是灰色地带，弄不好被抓了，不然不会这么久不更新呀。

**Comment by wfdubowen** [comment]
上个版本之后就好久没有更新了。。。现在处于登不上去的状态

**Comment by swjtu2004** [comment]
就是Google把没认证的id删了而已。认证下，一切如旧。

**Comment by ino1988** [comment]
> 
> 
> 就是Google把没认证的id删了而已。认证下，一切如旧。

你指的是google appid吗？

**Comment by navigator1886** [comment]
> 就是Google把没认证的id删了而已。认证下，一切如旧。
请问如何认证？绑定银行卡吗？

**Comment by wfdubowen** [comment]
> 证

X-Turnel上不去好久了

**Comment by swjtu2004** [comment]
> > 就是Google把没认证的id删了而已。认证下，一切如旧。
> > 请问如何认证？绑定银行卡吗？

对

**Comment by swjtu2004** [comment]
> appid

对

**Comment by tofu23** [comment]
> > > 就是Google把没认证的id删了而已。认证下，一切如旧。
> > > 请问如何认证？绑定银行卡吗？
> 
> 对

请问借记卡行么 还是必须信用卡 双币那种？ 要扣费么
