### ISSUE TITLE
俺来这里收留难民了！

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#13581]
x-tunnel不能用的朋友，不要急躁，耐心给xxnet发邮件说明情况，然后，到俺的坛子里寻找新的爬墙姿势。
不能因为爬墙这种小事，影响到生活或工作。另，坛子里好像有朋友分享自用梯子，大家找找看。
下面是俺坛子的链接，需要的可上去看看。
https://bbs.111111.online/

**Comment by hurricanesh** [comment]
很有用的论坛，谢谢分享！
