### ISSUE TITLE
一键生成的反馈模板。

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net#1358]
-----------问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1； Build:7601； Platform:2； CSD:Service Pack 1； ServicePack:1-0； Suite:256；  Suite:256； ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
xxnet-version: 2.6.0
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 258,256
connected-link: 0,0
ip-connect-interval: 8
scan-ip-thread-num: 0
ip-handshake-10: 1328
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by simonasd** [comment]
@xxnet 
刚刚pull的一键生成issue模板，效果如上所示，除了标题，其他信息都是自动填写的。

**Comment by xxnet** [comment]
cool！

日志的获取方法可以参考 logging.html
地址是：/module/gae_proxy/control/log，结果是一个JSON

2015-11-10 23:43 GMT+08:00 simonasd <notifications@github.com>:

**Comment by qq205633** [comment]
免费的软件已经有人开始卖了http://www.5b5l.com/Chrome/

**Comment by qwer123451** [comment]
免费的软件已经有人开始卖了！！！http://www.5b5l.com/Chrome/

**Comment by Cat7373** [comment]
@qwer123451 这个网页左上角有个淘宝店铺，打开后举报，完工。
