### ISSUE TITLE
！BUG?google學術打開后，搜索結果無法繼續打開？

### ISSUE THREAD

**Issue by PS0123456** [XX-net/XX-Net#1359]
https://scholar.google.com
比如TNF，任意點擊一個，都打不開，一直就時空白狀態
![2015-11-11_115644](https://cloud.githubusercontent.com/assets/13433663/11083523/4cc7c8ac-886b-11e5-9912-4f494f82e2cc.jpg)
![2015-11-11_115812](https://cloud.githubusercontent.com/assets/13433663/11083546/83812adc-886b-11e5-9f5b-bd1a484fe04d.jpg)
再比如，直接google 科学发现与技术发明，点击下面的谷歌学术，如图
![2015-11-11_120014](https://cloud.githubusercontent.com/assets/13433663/11083590/e1955d00-886b-11e5-8967-e10bb810c7cb.jpg)
![2015-11-11_120024](https://cloud.githubusercontent.com/assets/13433663/11083591/e1d65db4-886b-11e5-978b-6ab53afc9538.jpg)

已排除浏览器 原因，因为其他软件可以正常打开。
请问这事什么原因

**Comment by xxnet** [comment]
我这边 2.6.0 版本测试没有发现问题

在 2015年11月11日 下午12:02，PS0123456 <notifications@github.com>写道：

**Comment by xxnet** [comment]
你是什么版本，把状态页贴出来

在 2015年11月11日 下午2:35，Net XX <xxnet.dev@gmail.com>写道：

**Comment by PS0123456** [comment]
@xxnet 恩，我时2.55，我先试试2.6

**Comment by PS0123456** [comment]
@xxnet 恩，我时2.55，我先试试2.6

**Comment by PS0123456** [comment]
@xxnet 恩，我时2.55，我先试试2.6
