### ISSUE TITLE
今晚8点过3分（2021/10/01 20：03）突然连不上了。

### ISSUE THREAD

**Issue by Maogxer** [XX-net/XX-Net#13595]
> 2021-10-01 20:03:54.423 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:55.015 - [DEBUG] Conn session:bytearray(b'qwupknjq') conn:390 recv socket closed
> 
> 2021-10-01 20:03:55.015 - [DEBUG] Conn session:qwupknjq conn:390 stop:recv fail.
> 
> 2021-10-01 20:03:55.015 - [DEBUG] remove conn:390
> 
> 2021-10-01 20:03:56.155 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:56.155 - [WARNING] roundtrip time:35.373944 transfer_no:2492 send:595 status:602
> 
> 2021-10-01 20:03:56.186 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:56.186 - [WARNING] roundtrip time:35.374466 transfer_no:2493 send:643 status:602
> 
> 2021-10-01 20:03:56.486 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:56.486 - [WARNING] roundtrip time:35.376450 transfer_no:2494 send:571 status:602
> 
> 2021-10-01 20:03:56.486 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:56.486 - [WARNING] roundtrip time:35.347116 transfer_no:2495 send:571 status:602
> 
> 2021-10-01 20:03:57.454 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:57.454 - [WARNING] roundtrip time:35.376096 transfer_no:2496 send:70116 status:602
> 
> 2021-10-01 20:03:57.609 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:57.609 - [WARNING] roundtrip time:35.313878 transfer_no:2497 send:0 status:602
> 
> 2021-10-01 20:03:57.675 - [INFO] socks5 ('127.0.0.1', 49485) connect to www.youtube.com:443 conn_id:400
> 
> 2021-10-01 20:03:58.125 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:58.125 - [WARNING] roundtrip time:35.377973 transfer_no:2498 send:0 status:602
> 
> 2021-10-01 20:03:59.873 - [WARNING] get_front fail
> 
> 2021-10-01 20:03:59.873 - [WARNING] roundtrip time:35.331131 transfer_no:2499 send:4704 status:602
> 
> 2021-10-01 20:04:00.168 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:00.168 - [WARNING] roundtrip time:35.404273 transfer_no:2500 send:0 status:602
> 
> 2021-10-01 20:04:00.229 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:00.229 - [WARNING] roundtrip time:35.372081 transfer_no:2501 send:32 status:602
> 
> 2021-10-01 20:04:00.384 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:00.384 - [WARNING] roundtrip time:35.357547 transfer_no:2502 send:571 status:602
> 
> 2021-10-01 20:04:00.477 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:02.512 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:02.512 - [WARNING] roundtrip time:35.389814 transfer_no:2503 send:72496 status:602
> 
> 2021-10-01 20:04:04.528 - [DEBUG] Conn session:bytearray(b'qwupknjq') conn:392 recv socket closed
> 
> 2021-10-01 20:04:04.529 - [DEBUG] Conn session:qwupknjq conn:392 stop:recv fail.
> 
> 2021-10-01 20:04:04.529 - [DEBUG] remove conn:392
> 
> 2021-10-01 20:04:05.275 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:05.275 - [WARNING] roundtrip time:35.368888 transfer_no:2504 send:4736 status:602
> 
> 2021-10-01 20:04:06.532 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:06.579 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:06.579 - [WARNING] roundtrip time:35.371183 transfer_no:2505 send:571 status:602
> 
> 2021-10-01 20:04:07.541 - [WARNING] api:/login fail:status:602 t:30
> 
> 2021-10-01 20:04:07.866 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:07.866 - [WARNING] roundtrip time:35.344990 transfer_no:2506 send:72496 status:602
> 
> 2021-10-01 20:04:08.001 - [INFO] socks5 ('127.0.0.1', 53426) connect to www.youtube.com:443 conn_id:402
> 
> 2021-10-01 20:04:08.002 - [INFO] socks5 ('127.0.0.1', 52330) connect to www.youtube.com:443 conn_id:404
> 
> 2021-10-01 20:04:09.887 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:09.887 - [WARNING] roundtrip time:35.349921 transfer_no:2507 send:595 status:602
> 
> 2021-10-01 20:04:10.500 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:10.500 - [WARNING] roundtrip time:35.354743 transfer_no:2508 send:4736 status:602
> 
> 2021-10-01 20:04:12.287 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:12.287 - [WARNING] roundtrip time:35.400637 transfer_no:2509 send:571 status:602
> 
> 2021-10-01 20:04:13.539 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:13.539 - [WARNING] roundtrip time:35.351651 transfer_no:2510 send:72496 status:602
> 
> 2021-10-01 20:04:15.908 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:15.908 - [WARNING] roundtrip time:35.338937 transfer_no:2511 send:5331 status:602
> 
> 2021-10-01 20:04:18.203 - [DEBUG] Conn session:bytearray(b'qwupknjq') conn:394 recv socket closed
> 
> 2021-10-01 20:04:18.203 - [DEBUG] Conn session:qwupknjq conn:394 stop:recv fail.
> 
> 2021-10-01 20:04:18.203 - [DEBUG] remove conn:394
> 
> 2021-10-01 20:04:18.213 - [INFO] socks5 ('127.0.0.1', 60301) connect to mail.google.com:443 conn_id:406
> 
> 2021-10-01 20:04:18.530 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:18.530 - [WARNING] roundtrip time:35.352339 transfer_no:2512 send:571 status:602
> 
> 2021-10-01 20:04:18.717 - [WARNING] get_front fail
> 
> 2021-10-01 20:04:18.717 - [WARNING] roundtrip time:35.319665 transfer_no:2513 send:72496 status:602
>

**Comment by xxnet** [comment]
请贴出 cloudflare的日志

**Comment by Maogxer** [comment]
> 请贴出 cloudflare的日志

今天打开电脑，它自己又好了！
