### ISSUE TITLE
用着还可以，新朋友输这个邀请码我也可以获取新节点

### ISSUE THREAD

**Issue by 935352** [XX-net/XX-Net#13598]
https://github.com/dodois/Doisnet
用着还可以，新朋友输这个邀请码我也可以获取新节点 y691ad1f

**Comment by 935352** [comment]
> 用着还可以，新朋友输这个邀请码我也可以获取新节点 y691ad1f
> 
> _Originally posted by @935352 in [#13583 (comment)](https://github.com/XX-net/XX-Net/issues/13583#issuecomment-927340988)_

**Comment by SeaHOH** [comment]
Duplicate of #13583
