### ISSUE TITLE
无法下载vpngate

### ISSUE THREAD

**Issue by hzxie** [XX-net/XX-Net#136]
When I access following URL using GoAgent

```
http://download.vpngate.jp/common/cd.aspx/vpngate-client-2015.04.13-build-9546.132306.zip
```

I got an `502 UrlFetchError` with following error message:

```
Python Urlfetch Error: 'GET'

ResponseTooLargeError(), timeout=30
ResponseTooLargeError(), timeout=60
```

However, it works fine in `GoAgent PHP` Mode. I guess there's something wrong with GoAgent. Please fix it.

**Comment by xxnet** [comment]
What is you XX-Net version?

XX-Net 1.8.3 have fix the bug, need redeploy the server.
Please use the newest version


2015-04-13 2:52 GMT-04:00 Howard Shieh <notifications@github.com>:

**Comment by zjhzxhz** [comment]
1.8.4

**Comment by xxnet** [comment]
收到，我研究下

2015-04-13 5:25 GMT-04:00 Howard Shieh <notifications@github.com>:

**Comment by xxnet** [comment]
这个服务器网站不支持文件分块下载，而GAE分块大小受限。
 因此这个问题无法解决。
