### ISSUE TITLE
XX-Net的流量错误

### ISSUE THREAD

**Issue by zhiyiren2009** [XX-net/XX-Net#13630]
@SeaHOH @xxnet 
账号 xxnet-test-account@protonmail.com
测试前
![测试前](https://user-images.githubusercontent.com/91038573/148707724-636f1e65-f177-4c00-aafa-846a8a55bea1.png)
测速
![Speedtest](https://user-images.githubusercontent.com/91038573/148707729-5fae8589-3992-4575-a5d5-acca007ebda0.png)
测试后
![测试后](https://user-images.githubusercontent.com/91038573/148707732-cbc21752-e5ab-4635-bf21-7cac05be4bb9.png)

流量没有变化
如果不刷新会变成负数，刷新后重置到一个很小的数
![Screenshot from 2022-01-10 08-41-08](https://user-images.githubusercontent.com/91038573/148707798-1272b075-d81e-4a17-bed7-4059e566b117.png)

**Comment by zhiyiren2009** [comment]
[log.txt](https://github.com/XX-net/XX-Net/files/7836351/log.txt)

**Comment by zhiyiren2009** [comment]
![Screenshot from 2022-01-10 19-19-31](https://user-images.githubusercontent.com/91038573/148757922-14050e25-04f5-4c72-bfed-d15fea8e1830.png)
Ubuntu再现流量负数
`XX-Net Status:

sys-platform: x86_64, Linux-5.11.0-44-generic-x86_64-with-glibc2.29
os-system: Linux
os-version: #48~20.04.2-Ubuntu SMP Tue Dec 14 15:36:44 UTC 2021
os-release: 5.11.0-44-generic
os-detail: Ubuntu

architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
xxnet-version: 4.5.6

python-version: 3.8.10
openssl-version: OpenSSL 1.1.1f  31 Mar 2020 TLSv1_3 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:24 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:13
scan-ip-thread-num: 20
ip-quality: 1148
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true`

**Comment by SeaHOH** [comment]
搞不清，我并没有参与服务器开发。

**Comment by SeaHOH** [comment]
另外，wiki 页脚请删掉，推广可以，但在这里搞就失去推广的本意。

**Comment by zhiyiren2009** [comment]
这样可以无限刷吧？我用这个办法用0.01MiB看了整天的YT

**Comment by SeaHOH** [comment]
这个我先关掉，内容会编辑掉请不要在意，你暂时不要再发相同问题了。

**Comment by xxnet** [comment]
@zhiyiren2009  感谢反馈，能否给 xxnet.dev@gmail.com 发邮件，把详细情况描述一下，非常感谢啊！
