### ISSUE TITLE
[发布] 4.6.1 改进智能路由策略

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13641]
新版兼容 python 2.7.
性能上改进了智能路由策略，大家可以试试切换到 智能路由，端口 8086。
有遇到策略不好的请把路由日志发出来，或者发给xxnet.dev@gmail.com分析。

下载地址：
https://github.com/XX-net/XX-Net/releases/tag/4.6.1

**Comment by maysilence** [comment]
自动更新、手动更新，启动均失败，http://localhost:8085无法访问，windows 11系统。

**Comment by xxnet** [comment]
暂时先撤回

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/releases/tag/4.6.2

@maysilence  帮忙测试下 4.6.2 能否在win11下工作，感谢！

**Comment by maysilence** [comment]
您好，还是不行，连X的图标都出不来了，直接报错：
2022-01-27 19:47:22.833 [launcher][ERROR] start module gae_proxy fail:cannot import name 'ConnectionError' from 'six' (D:\XX-Net\python3.8.2\lib\six.py)
2022-01-27 19:47:22.835 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\4.6.2\launcher\module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\front.py", line 17, in <module>
    from .check_ip import CheckIp
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\check_ip.py", line 34, in <module>
    from six import ConnectionError, ConnectionResetError, BrokenPipeError
ImportError: cannot import name 'ConnectionError' from 'six' (D:\XX-Net\python3.8.2\lib\six.py)

2022-01-27 19:47:22.835 [launcher][ERROR] launcher except:ImportError("cannot import name 'ConnectionError' from 'six' (D:\\XX-Net\\python3.8.2\\lib\\six.py)")
2022-01-27 19:47:22.836 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\4.6.2\launcher\start.py", line 163, in <module>
    main()
  File "D:\XX-Net\code\4.6.2\launcher\start.py", line 141, in main
    module_init.start_all_auto()
  File "D:\XX-Net\code\4.6.2\launcher\module_init.py", line 121, in start_all_auto
    start(module)
  File "D:\XX-Net\code\4.6.2\launcher\module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\front.py", line 17, in <module>
    from .check_ip import CheckIp
  File "D:\XX-Net\code\4.6.2\gae_proxy\local\check_ip.py", line 34, in <module>
    from six import ConnectionError, ConnectionResetError, BrokenPipeError
ImportError: cannot import name 'ConnectionError' from 'six' (D:\XX-Net\python3.8.2\lib\six.py)

发件人: Michael.X ***@***.***>
发送时间: 2022年1月27日 19:31
收件人: XX-net/XX-Net ***@***.***>
抄送: maysilence ***@***.***>; Mention ***@***.***>
主题: Re: [XX-net/XX-Net] [发布] 4.6.1 改进智能路由策略 (Issue #13641)


https://github.com/XX-net/XX-Net/releases/tag/4.6.2<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Freleases%2Ftag%2F4.6.2&data=04%7C01%7C%7C38606308a81347a9225c08d9e1887ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788798657239162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qoT%2FKJFRdQL0dpFABolisbuqgVQc0Ffkb%2Fh%2FiY26CmA%3D&reserved=0>

@maysilence<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaysilence&data=04%7C01%7C%7C38606308a81347a9225c08d9e1887ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788798657239162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t%2FIBM7iHOq6inO0JGDNhp2bqQZ0937XCLb8prr0XDFI%3D&reserved=0> 帮忙测试下 4.6.2 能否在win11下工作，感谢！

―
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2F13641%23issuecomment-1023114064&data=04%7C01%7C%7C38606308a81347a9225c08d9e1887ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788798657239162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cUE1jINDD%2BJGNaVLeLWlbxvc4fm6W8Ken6a2OrJE7eU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEBKCWILYDOTTHVKYU7XOEDUYEUHLANCNFSM5M2RYXMA&data=04%7C01%7C%7C38606308a81347a9225c08d9e1887ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788798657239162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=odzD%2FyQ%2BWYXq6YZ6EmR7Xo2tTSAx9X87wiqs42AhmFw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C38606308a81347a9225c08d9e1887ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788798657239162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n838k6c5iD993dNdWafGENKP9d%2F09G1FRFtWccpM47o%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C38606308a81347a9225c08d9e1887ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788798657239162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KhWTGutKj3b5JmG%2BanD2ulW48iim5Ga7XWb1Ckj9AGk%3D&reserved=0>.

**Comment by xxnet** [comment]
@maysilence 
再试试 4.6.3
https://github.com/XX-net/XX-Net/releases/tag/4.6.3

辛苦了

**Comment by SeaHOH** [comment]
为什么不升级 Xndroid 内置 Python 呢？搞这个兼容好像更费劲些。

**Comment by maysilence** [comment]
还是不行
2022-01-27 22:43:07.202 [launcher][ERROR] start module gae_proxy fail:cannot import name 'ConnectionError' from 'six' (D:\XX-Net\python3.8.2\lib\six.py)
2022-01-27 22:43:07.205 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\4.6.3\launcher\module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\front.py", line 17, in <module>
    from .check_ip import CheckIp
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\check_ip.py", line 34, in <module>
    from six import ConnectionError, ConnectionResetError, BrokenPipeError
ImportError: cannot import name 'ConnectionError' from 'six' (D:\XX-Net\python3.8.2\lib\six.py)

2022-01-27 22:43:07.206 [launcher][ERROR] launcher except:ImportError("cannot import name 'ConnectionError' from 'six' (D:\\XX-Net\\python3.8.2\\lib\\six.py)")
2022-01-27 22:43:07.208 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\4.6.3\launcher\start.py", line 163, in <module>
    main()
  File "D:\XX-Net\code\4.6.3\launcher\start.py", line 141, in main
    module_init.start_all_auto()
  File "D:\XX-Net\code\4.6.3\launcher\module_init.py", line 121, in start_all_auto
    start(module)
  File "D:\XX-Net\code\4.6.3\launcher\module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\front.py", line 17, in <module>
    from .check_ip import CheckIp
  File "D:\XX-Net\code\4.6.3\gae_proxy\local\check_ip.py", line 34, in <module>
    from six import ConnectionError, ConnectionResetError, BrokenPipeError
ImportError: cannot import name 'ConnectionError' from 'six' (D:\XX-Net\python3.8.2\lib\six.py)

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Michael.X ***@***.***>
发送时间: Thursday, January 27, 2022 8:13:40 PM
收件人: XX-net/XX-Net ***@***.***>
抄送: maysilence ***@***.***>; Mention ***@***.***>
主题: Re: [XX-net/XX-Net] [发布] 4.6.1 改进智能路由策略 (Issue #13641)


@maysilence<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaysilence&data=04%7C01%7C%7C05629caa9f2a4e3f820008d9e18e7499%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788824222175465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6wNqaA67BtjhLoRQLxZFC57eyATrkll0BlHpY1d0yxY%3D&reserved=0>
再试试 4.6.3
https://github.com/XX-net/XX-Net/releases/tag/4.6.3<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Freleases%2Ftag%2F4.6.3&data=04%7C01%7C%7C05629caa9f2a4e3f820008d9e18e7499%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788824222175465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1VxUUkSkznnMB1I%2FtJ%2FFkaKbkVdMxFp0HFt%2FY7lbofA%3D&reserved=0>

辛苦了

―
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2F13641%23issuecomment-1023144779&data=04%7C01%7C%7C05629caa9f2a4e3f820008d9e18e7499%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788824222175465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iE4eZk12PHaXs3M2LytcmhM4LvdbNVRDSe%2Bi50jN%2BOg%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEBKCWMMVF2XLUBTECXDV73UYEZHJANCNFSM5M2RYXMA&data=04%7C01%7C%7C05629caa9f2a4e3f820008d9e18e7499%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788824222175465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RDwfYR2hgT1A5t1pMLpS%2BkMmHYA702ig5hz%2B%2Bj4FOs0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C05629caa9f2a4e3f820008d9e18e7499%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788824222175465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W6VaaWxQ4VyTONhB9mZ8JwbAQLo0NvEX7HVehvCdq%2FI%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C05629caa9f2a4e3f820008d9e18e7499%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788824222175465%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yfF7LwwWHSfW2AW%2BrXXeupPPW8LGEQAun4n3qruOyEg%3D&reserved=0>.

**Comment by xxnet** [comment]
@SeaHOH 
折腾了好久升级Xndroid的python3，已经搞定python 环境，但是 Xndroid 的很多内部的python代码是基于 gevent的，没有搞定gevent 编译到Android, 整个体系太大了，一时搞不定。
虽然兼容 python2 也折腾，但是还是在可控范围内。
正在做自动化测试，因为要测试多个python 版本，多种操作系统环境，手动测试太耗时间了，很难覆盖到。

**Comment by SeaHOH** [comment]
刚才我尝试从 Termux 里面安装 gevent，花了半个小时左右成功完成编译安装，这样就可以从这里提取安装好的 gevent 和依赖包括所有二进制文件。

**Comment by SeaHOH** [comment]
不过 Xndroid 组件也要进行 Python 3 兼容，但这个相对容易些。

**Comment by xxnet** [comment]
我也在Termux里编译成功了，但是启动python 然后import gevent 就会报错，不知道怎么解决，网上没有找到资料

**Comment by SeaHOH** [comment]
我这里正常 import 没报错，Python 是之前安装的 3.9.6，pip 也没有更新过。
要不你换个手机试试，或者我提出来给你也行？

**Comment by xxnet** [comment]
试了两个手机，python的版本都是 3.10.1
你能把 python 和相关的库打包发邮件给我吗？谢谢啦

**Comment by SeaHOH** [comment]
昨天折腾了一宿，发现几个坑，这里记录下。
顺便你也再试试，因为安装的包位置是确定的，但我不知道完整的 Python 都包含哪些文件，所以我只提取了 3.10.2 的 site-packages。

    # 更新默认组件，不然有些新的软件包会不兼容，导致无法正确调用，如果是编译工具就会编译失败
    pkg update
    # 更新已安装的软件包
    pkg upgrade
    # 更新过后还有问题，安装 gevent 还需要 binutils 才能编译成功，之前的 clang 没这回事
    pkg install binutils
    # 明确设置 Rust 编译的目标系统，不然会编译失败
    export CARGO_BUILD_TARGET=aarch64-linux-android

如果是全新安装，大概这样就行：

    pkg update
    pkg install binutils clang rust python
    pip install ...

之前没看过，昨天才发现 fqsocks 用了一堆不同的加密相关的包，到现在为止依赖及其庞大，估计需要剔除不需要的部分。这些依赖不可控，真不如重构。现在看来，倒回去兼容 Python 2 确实要单纯些。

**Comment by SeaHOH** [comment]
[site-packages_py310_aarch64_android.7z](https://github.com/XX-net/XX-Net/files/7965087/site-packages_py310_aarch64_android.7z.zip)
谷歌好像把邮件给屏蔽了，不让发压缩文件，简直有病。邮件内容应该还能看见吧。 @xxnet

**Comment by xxnet** [comment]
感谢感谢，文件可以下载，辛苦了！

刚刚把自动化测试脚本整理得差不多了， 我弄完自动化测试就开始弄手机版。

**Comment by SeaHOH** [comment]
邮件内容也屏蔽了吗？这里把要点复制下。

> 另外，刚才重新整理安装时，发现缺少两个包 spdy 和 netfilterqueue。
spdy 可以用 aioquic 替代，netfilterqueue 可以用 pcap-ct 替代，但都需要重构相应部分。

这两部分要替代实现和之前一样的功能可能要多废些功夫。安装的话我估计按上面的操作来是没问题的，就是要先安装 libpcap 之类的依赖这样。打包里面有些包最后成品用不上，应该是可以删掉的。

**Comment by xxnet** [comment]
邮件没收到，刚刚看了邮件垃圾箱也没有找到。

我的思路是尽量用原有的系统和代码，升级python 可谓伤筋动骨，成本太高了
先把原有系统跑起来，后面要升级再说。

**Comment by SeaHOH** [comment]
是的，我也是昨天才发现 fqsocks 居然这么多乱七八糟的依赖，尽是些加密相关的，严重冗余，尤其是过了这么些年还膨胀了。

谷歌总想搞事，也不知道 fqrouter 还能用到哪个版本，最好是找找看有没有其它有人维护的合适的开源框架。不一定非要 Python 作为主要功能实现，只要有基本的网络代理管理并方便接入就好，大不了就是转了一道后效率稍微低些。

**Comment by xxnet** [comment]
其实Android只需要把系统代理功能实现，把流量转发到 8086 端口就可以了，剩下原来 fqrouter的其他东西都可以不要了。
python4android 项目也是维护得很差，python 这几年在兼容性上折腾了太多精力，性能一直没有提升，反观 js
性能突破后，发展得太好了，虽然自身语法很差。
以后考虑的语言可能是Rust，构建大型项目没有瓶颈，缺点是门槛有点高。

**Comment by SeaHOH** [comment]
主要微软强势白嫖 Python 造成此局面，现在看来生态发展壮大，算是好处更多些，但也算不得大好。接下来就看之前 Rossum 的性能承诺 (实质上是微软的表态) 今年能否兑现，虽然并没有太多人期待，毕竟大家想要的还是完全干掉 GIL。

至于 Javascript 能发展到现在这样真真是个奇迹，就一缝合怪，各种层面都是。

**Comment by xxnet** [comment]
自动化测试花了几天时间，不过发现了很多小问题，如果不是自动化脚本，这些小问题要花很长时间才会暴露出来。
这算是最近的成果吧，以后再有开发测试效率提高很多。
