### ISSUE TITLE
求大神，openwrt安装并启动成功，x-tunnel登录成功，远程可访问，电脑用x-tunnel自动切换模式没有效果

### ISSUE THREAD

**Issue by excellenttank** [XX-net/XX-Net#13653]
openwrt安装并启动成功，x-tunnel登录成功，远程可访问，电脑用x-tunnel自动切换模式没有效果

**Comment by excellenttank** [comment]
![image](https://user-images.githubusercontent.com/16424424/153365337-d4890a8e-526f-401a-a7a8-3a58441023d7.png)

**Comment by xxnet** [comment]
电脑的代理ip要指向 192.168.1.1

爱折腾的可以试试全局智能代理：
./start set_iptables

4.6.8 版本的智能路由效果更好

**Comment by excellenttank** [comment]
> 电脑的代理ip要指向 192.168.1.1 爱折腾的可以试试全局智能代理： ./start set_iptables 4.6.8 版本的智能路由效果更好

需要后面加br-lan吗，
![image](https://user-images.githubusercontent.com/16424424/153382272-3bc09ee4-d340-4cf7-93c7-912e228ed058.png)
![0c78a88a31fddfd0fea9dc3f8e4a466](https://user-images.githubusercontent.com/16424424/153382492-cccc1484-10c4-4763-914f-a48ab562683c.png)
加上这句之后所有的设备都不能访问网络了包括手机
