### ISSUE TITLE
自动更新失败.手动更新也失败Download Checksum Fail.

### ISSUE THREAD

**Issue by jaxguo** [XX-net/XX-Net#13678]
![QQ截图20220323173816](https://user-images.githubusercontent.com/9720390/159669014-4a9c05fd-eb12-48e8-9aa7-46bcf01f8bdf.png)
4.7.3更新4.7.9 失败.提示Download Checksum Fail.

**Comment by whylalacantuse** [comment]
哪个平台的？直接下新版的解压用也不可以吗？

**Comment by xxnet** [comment]
刚刚检查了hash没有错的， 我这边试过了也可以升级。
可能就是下载的包确实不完整，重试应该能好.

当然手动下载一个新版解压是最简单的办法。
