### ISSUE TITLE
x-tunnel链接不稳定

### ISSUE THREAD

**Issue by fennafamearthlight** [XX-net/XX-Net#13682]
账户一会儿在线一会儿掉线
见下图
每秒钟都在已登录上和登录中切换

**Comment by fennafamearthlight** [comment]
![2](https://user-images.githubusercontent.com/62839087/161365065-0b07ec47-79ff-4daf-ba34-a6bf9e078f23.png)
![1](https://user-images.githubusercontent.com/62839087/161365069-0bc65dbd-0f8f-45c5-9ced-9204edf7c7ef.png)

**Comment by xxnet** [comment]
刚加了线路，你重启XX-Net 看看有没有改善
