### ISSUE TITLE
X-TUNNEL怎么付费？

### ISSUE THREAD

**Issue by leopardrone** [XX-net/XX-Net#13686]
我购买套餐说我账号没钱，但我不付费怎么有钱呢？怎么解决？？
![图像 1](https://user-images.githubusercontent.com/66026137/162579312-e8c1152c-e7df-41b1-8e25-06e4e42091cc.jpg)
![图像 2](https://user-images.githubusercontent.com/66026137/162579320-5dd7a320-2c8f-4f78-b41a-2bfa756c8158.jpg)

**Comment by xxnet** [comment]
抱歉，是服务器bug，目前已经修复了，请重试
