### ISSUE TITLE
windows上telegram设置代理是可以的 但是mac就一直在转圈

### ISSUE THREAD

**Issue by WuqingVika** [XX-net/XX-Net#13692]
代理是设成127.0.0.1:1080 

xxnet选择的是enable global smart-router

**Comment by xxnet** [comment]
mac 的 telegram 里有设置代理，选socks5类型。

xxnet里选enable global smart-router 不一定对telegram生效

**Comment by WuqingVika** [comment]
> mac 的 telegram 里有设置代理，选socks5类型。
> 
> xxnet里选enable global smart-router 不一定对telegram生效

好的 谢谢~~后来我是通过proxifier就可以了。谢谢~~
