### ISSUE TITLE
Mac OS 12.3.1无法运行

### ISSUE THREAD

**Issue by fanfanxiaozu** [XX-net/XX-Net#13693]
Start version:4.7.11
Darwin using embedded python.
Darwin
2022-04-30 09:48:16.923 defaults[1135:15070]
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist

默认为HANGUP参数为1，改成0之后才能看到日志，然后就会卡在上面的日志上
在这里control+c后才能继续运行

**Comment by xxnet** [comment]
你试试到目录下执行下面的命令：
python code/default/launcher/start.py

**Comment by xxnet** [comment]
已经找到问题了，下一个版本修复
