### ISSUE TITLE
用 XX-Net 向GItHub上push 代码有问题

### ISSUE THREAD

**Issue by liushiwei** [XX-net/XX-Net#137]
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.8.5
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087

Apr 13 17:40:30 - [INFO] GAE CONNECT github.com:443 
Apr 13 17:40:30 - [DEBUG] GAE CONNECT GET https://github.com/liushiwei/Herewego.git/info/refs?service=git-receive-pack
Apr 13 17:40:30 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:231
Apr 13 17:40:30 - [DEBUG] ssl conn_num:19
Apr 13 17:40:30 - [DEBUG] sort ip time:6
Apr 13 17:40:30 - [DEBUG] get ip:203.116.165.217 t:892
Apr 13 17:40:30 - [DEBUG] network is ok
Apr 13 17:40:30 - [INFO] GAE t:381 s:50 401 https://github.com/liushiwei/Herewego.git/info/refs?service=git-receive-pack
Apr 13 17:40:31 - [INFO] GAE CONNECT github.com:443 
Apr 13 17:40:31 - [DEBUG] GAE CONNECT GET https://github.com/liushiwei/Herewego.git/info/refs?service=git-receive-pack
Apr 13 17:40:31 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:231
Apr 13 17:40:31 - [DEBUG] ssl conn_num:19
Apr 13 17:40:31 - [DEBUG] create_ssl update ip:203.116.165.217 time:223
Apr 13 17:40:31 - [INFO] GAE t:789 s:350 200 https://github.com/liushiwei/Herewego.git/info/refs?service=git-receive-pack
Apr 13 17:40:31 - [INFO] GAE CONNECT github.com:443 
Apr 13 17:40:31 - [DEBUG] GAE CONNECT POST https://github.com/liushiwei/Herewego.git/git-receive-pack
Apr 13 17:40:33 - [DEBUG] ssl_pool.get:203.116.165.217 handshake:223
Apr 13 17:40:33 - [DEBUG] ssl conn_num:20
Apr 13 17:40:36 - [INFO] GAE CONNECT groups.google.com:443 
Apr 13 17:40:36 - [DEBUG] GAE CONNECT POST https://groups.google.com/forum/read?appversion=1&hl=zh-CN&authuser=0
Apr 13 17:40:36 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:231
Apr 13 17:40:36 - [DEBUG] ssl conn_num:19
Apr 13 17:40:36 - [DEBUG] get ip:210.158.146.208 t:231
Apr 13 17:40:36 - [DEBUG] create_ssl update ip:210.158.146.208 time:230
Apr 13 17:40:37 - [INFO] GAE t:783 s:32 200 https://groups.google.com/forum/read?appversion=1&hl=zh-CN&authuser=0
Apr 13 17:41:33 - [INFO] GAE CONNECT groups.google.com:443 
Apr 13 17:41:33 - [DEBUG] GAE CONNECT POST https://groups.google.com/forum/finfo_bkg?appversion=1&hl=zh-CN&authuser=0
Apr 13 17:41:33 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:41:33 - [DEBUG] ssl conn_num:20
Apr 13 17:41:33 - [WARNING] _request bad status line
Apr 13 17:41:33 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:231
Apr 13 17:41:33 - [DEBUG] ssl conn_num:19
Apr 13 17:41:33 - [DEBUG] sort ip time:3
Apr 13 17:41:33 - [DEBUG] get ip:203.116.165.217 t:223
Apr 13 17:41:34 - [INFO] GAE t:773 s:70 200 https://groups.google.com/forum/finfo_bkg?appversion=1&hl=zh-CN&authuser=0
Apr 13 17:41:35 - [DEBUG] create_ssl 203.116.165.217 fail:timed out c:0 h:0
Apr 13 17:41:35 - [DEBUG] network is ok
Apr 13 17:42:00 - [INFO] GAE CONNECT www.google.com:443 
Apr 13 17:42:00 - [DEBUG] GAE CONNECT GET https://www.google.com/complete/search?client=serp&hl=zh-CN&sugexp=msedr&gs_rn=64&gs_ri=serp&tok=2bzXBCjDBC3sLbDStihL4Q&pq=EmEditor&cp=34&gs_id=fl&q=%5BWARNING%5D%20_request%20bad%20status%20line&xhr=t
Apr 13 17:42:00 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:42:00 - [DEBUG] ssl conn_num:19
Apr 13 17:42:00 - [DEBUG] sort ip time:5
Apr 13 17:42:00 - [DEBUG] get ip:210.158.146.208 t:230
Apr 13 17:42:01 - [INFO] GAE CONNECT www.google.com:443 
Apr 13 17:42:01 - [INFO] GAE t:647 s:171 200 https://www.google.com/complete/search?client=serp&hl=zh-CN&sugexp=msedr&gs_rn=64&gs_ri=serp&tok=2bzXBCjDBC3sLbDStihL4Q&pq=EmEditor&cp=34&gs_id=fl&q=%5BWARNING%5D%20_request%20bad%20status%20line&xhr=t
Apr 13 17:42:01 - [DEBUG] GAE CONNECT GET https://www.google.com/search?newwindow=1&safe=strict&es_sm=122&q=%5BWARNING%5D+_request+bad+status+line&oq=%5BWARNING%5D+_request+bad+status+line&gs_l=serp.3...384832.384832.0.385486.1.1.0.0.0.0.0.0..0.0.msedr...0...1c..64.serp..1.0.0.hOD2GpjCzsg
Apr 13 17:42:01 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:42:01 - [DEBUG] ssl conn_num:19
Apr 13 17:42:01 - [INFO] check_ip add ip:61.219.131.118 time:158
Apr 13 17:42:02 - [INFO] GAE t:1167 s:26367 200 https://www.google.com/search?newwindow=1&safe=strict&es_sm=122&q=%5BWARNING%5D+_request+bad+status+line&oq=%5BWARNING%5D+_request+bad+status+line&gs_l=serp.3...384832.384832.0.385486.1.1.0.0.0.0.0.0..0.0.msedr...0...1c..64.serp..1.0.0.hOD2GpjCzsg
Apr 13 17:42:02 - [INFO] GAE CONNECT www.google.com:443 
Apr 13 17:42:02 - [DEBUG] GAE CONNECT GET https://www.google.com/images/nav_logo195.png
Apr 13 17:42:02 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:42:02 - [DEBUG] ssl conn_num:19
Apr 13 17:42:02 - [INFO] GAE CONNECT www.google.com:443 
Apr 13 17:42:02 - [DEBUG] GAE CONNECT GET https://www.google.com/xjs/_/js/sdch=d/k=xjs.s.zh_CN.d7_xsDqVdHs.O/m=sx,c,sb,cdos,cr,elog,jsa,r,hsm,d,csi/am=pET9LYYwlAXVBNQB/rt=j/d=1/t=zcms/rs=ACT90oH-5jf_0j4N_bv2cmZ3ig3RFO7kQg
Apr 13 17:42:02 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:233
Apr 13 17:42:02 - [DEBUG] ssl conn_num:18
Apr 13 17:42:02 - [DEBUG] get ip:210.158.146.245 t:233
Apr 13 17:42:02 - [INFO] GAE t:283 s:0 304 https://www.google.com/images/nav_logo195.png
Apr 13 17:42:03 - [INFO] GAE t:565 s:0 304 https://www.google.com/xjs/_/js/sdch=d/k=xjs.s.zh_CN.d7_xsDqVdHs.O/m=sx,c,sb,cdos,cr,elog,jsa,r,hsm,d,csi/am=pET9LYYwlAXVBNQB/rt=j/d=1/t=zcms/rs=ACT90oH-5jf_0j4N_bv2cmZ3ig3RFO7kQg
Apr 13 17:42:03 - [DEBUG] create_ssl update ip:210.158.146.208 time:2556
Apr 13 17:42:03 - [DEBUG] create_ssl update ip:210.158.146.245 time:519
Apr 13 17:42:03 - [INFO] GAE CONNECT www.google.com:443 
Apr 13 17:42:03 - [DEBUG] GAE CONNECT GET https://www.google.com/gen_204?v=3&s=web&imc=6&imn=6&imp=1&ei=kI8rVavDF9GxogTml4CQAg&e=201537,3300101,3300134,3300137,3300161,3310366,3310705,3700272,3700362,3700366,3700368,4011559,4019511,4020347,4023709,4025836,4028716,4028875,4028932,4029515,4029666,4029815,4030091,4030108,4031241,4031392,4031394,4031622,4031691,4031735,4031736,4031789,4032032,4032418,4032480,4032500,4032577,8300141,8500394,8501248,8501280,8501295,8501313,8501351,8501393,8501411,10200084,10200096,10201001&atyp=csi&adh=&xjs=init.53.24.sb.31.spch.7.dvl.5.m.4.foot.1&action=&srt=1272&rt=xjsls.105,prt.106,xjses.882,xjsee.951,xjs.957,ol.1032,iml.345,wsrt.1277,cst.59,dnst.0,rqst.1166,rspt.193,sslt.26,rqstt.79,unt.16,cstt.20,dit.1383
Apr 13 17:42:03 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:42:03 - [DEBUG] ssl conn_num:21
Apr 13 17:42:03 - [INFO] GAE CONNECT plus.google.com:443 
Apr 13 17:42:03 - [DEBUG] GAE CONNECT POST https://plus.google.com/u/0/_/n/gcosuc?origin=https%3A%2F%2Fwww.google.com
Apr 13 17:42:03 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:233
Apr 13 17:42:03 - [DEBUG] ssl conn_num:20
Apr 13 17:42:03 - [INFO] GAE t:241 s:0 204 https://www.google.com/gen_204?v=3&s=web&imc=6&imn=6&imp=1&ei=kI8rVavDF9GxogTml4CQAg&e=201537,3300101,3300134,3300137,3300161,3310366,3310705,3700272,3700362,3700366,3700368,4011559,4019511,4020347,4023709,4025836,4028716,4028875,4028932,4029515,4029666,4029815,4030091,4030108,4031241,4031392,4031394,4031622,4031691,4031735,4031736,4031789,4032032,4032418,4032480,4032500,4032577,8300141,8500394,8501248,8501280,8501295,8501313,8501351,8501393,8501411,10200084,10200096,10201001&atyp=csi&adh=&xjs=init.53.24.sb.31.spch.7.dvl.5.m.4.foot.1&action=&srt=1272&rt=xjsls.105,prt.106,xjses.882,xjsee.951,xjs.957,ol.1032,iml.345,wsrt.1277,cst.59,dnst.0,rqst.1166,rspt.193,sslt.26,rqstt.79,unt.16,cstt.20,dit.1383
Apr 13 17:42:03 - [INFO] GAE t:353 s:55 200 https://plus.google.com/u/0/_/n/gcosuc?origin=https%3A%2F%2Fwww.google.com
Apr 13 17:42:03 - [INFO] GAE CONNECT plus.google.com:443 
Apr 13 17:42:03 - [DEBUG] GAE CONNECT GET https://plus.google.com/u/0/_/notifications/frame?sourceid=1&hl=zh-CN&origin=https%3A%2F%2Fwww.google.com&uc=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.7rOxC4EUJrE.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTO4gz1Nv8SUg2RgiKkyXhOlRYFsWw
Apr 13 17:42:03 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:42:03 - [DEBUG] ssl conn_num:21
Apr 13 17:42:04 - [WARNING] _request bad status line
Apr 13 17:42:04 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:233
Apr 13 17:42:04 - [DEBUG] ssl conn_num:20
Apr 13 17:42:04 - [INFO] GAE t:447 s:9567 200 https://plus.google.com/u/0/_/notifications/frame?sourceid=1&hl=zh-CN&origin=https%3A%2F%2Fwww.google.com&uc=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.7rOxC4EUJrE.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTO4gz1Nv8SUg2RgiKkyXhOlRYFsWw
Apr 13 17:42:34 - [WARNING] _request bad status line
Apr 13 17:42:43 - [WARNING] gae_exception: 'https://github.com/liushiwei/Herewego.git/git-receive-pack'
Apr 13 17:42:43 - [DEBUG] ssl_pool.get:210.158.146.208 handshake:230
Apr 13 17:42:43 - [DEBUG] ssl conn_num:20
Apr 13 17:43:08 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 13 17:43:08 - [DEBUG] sort ip time:6
Apr 13 17:43:08 - [DEBUG] get ip:61.219.131.118 t:158
Apr 13 17:43:08 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 13 17:43:08 - [DEBUG] get ip:210.158.146.208 t:330
Apr 13 17:43:08 - [DEBUG] tcp conn 210.158.146.208 time:75
Apr 13 17:43:08 - [DEBUG] get ip:210.158.146.245 t:333
Apr 13 17:43:08 - [DEBUG] tcp conn 210.158.146.245 time:73
Apr 13 17:43:09 - [DEBUG] tcp conn 61.219.131.118 fail t:1000
Apr 13 17:43:09 - [DEBUG] network is ok
Apr 13 17:43:13 - [WARNING] _request bad status line
Apr 13 17:43:13 - [DEBUG] ssl_pool.get:210.158.146.245 handshake:233
Apr 13 17:43:13 - [DEBUG] get ip:111.168.255.148 t:398
Apr 13 17:43:13 - [DEBUG] ssl conn_num:19
Apr 13 17:43:14 - [DEBUG] create_ssl 111.168.255.148 fail:timed out c:0 h:0
Apr 13 17:43:14 - [DEBUG] network is ok
Apr 13 17:43:15 - [DEBUG] get ip:210.245.14.237 t:520
Apr 13 17:43:16 - [DEBUG] create_ssl update ip:210.245.14.237 time:849
Apr 13 17:43:18 - [DEBUG] forward local disconnected.
Apr 13 17:43:18 - [DEBUG] FWD CONNECT www.google-analytics.com:443 with closed
Apr 13 17:43:38 - [DEBUG] head request fail:IncompleteRead(0 bytes read)
Apr 13 17:43:38 - [INFO] GAE CONNECT groups.google.com:443 
Apr 13 17:43:38 - [DEBUG] GAE CONNECT POST https://groups.google.com/forum/msg_bkg?appversion=1&hl=zh-CN&authuser=0
Apr 13 17:43:38 - [DEBUG] ssl_pool.get:210.245.14.237 handshake:420
Apr 13 17:43:38 - [DEBUG] ssl conn_num:17
Apr 13 17:43:38 - [DEBUG] sort ip time:8
Apr 13 17:43:38 - [DEBUG] get ip:210.158.146.245 t:147
Apr 13 17:43:38 - [DEBUG] get ip:210.158.146.208 t:150
Apr 13 17:43:38 - [DEBUG] create_ssl update ip:210.158.146.245 time:276
Apr 13 17:43:38 - [DEBUG] get ip:203.66.124.168 t:522
Apr 13 17:43:38 - [DEBUG] create_ssl update ip:210.158.146.208 time:240
Apr 13 17:43:39 - [DEBUG] get ip:210.245.14.231 t:537
Apr 13 17:43:39 - [DEBUG] get ip:173.194.202.31 t:585
Apr 13 17:43:40 - [DEBUG] create_ssl update ip:210.245.14.231 time:476
Apr 13 17:43:40 - [INFO] GAE t:2042 s:34 200 https://groups.google.com/forum/msg_bkg?appversion=1&hl=zh-CN&authuser=0
Apr 13 17:43:40 - [DEBUG] create_ssl 203.66.124.168 fail:timed out c:0 h:0
Apr 13 17:43:40 - [DEBUG] network is ok
Apr 13 17:43:40 - [DEBUG] create_ssl update ip:173.194.202.31 time:584
Apr 13 17:43:42 - [DEBUG] head request fail:IncompleteRead(0 bytes read)
*************************************************************************************************************************
************************************************************************************************************************
上面是日志。下面是Git push的时候的返回。
$ git push
Password:
Counting objects: 23, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (13/13), 22.02 KiB, done.
Total 13 (delta 2), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

**Comment by xxnet** [comment]
收到，尽快研究

2015-04-13 5:47 GMT-04:00 liushiwei <notifications@github.com>:

**Comment by yqfang** [comment]
这个的确是个问题！

**Comment by xxnet** [comment]
测试过，如果大小不超过单次请求限制，是可以push的。

试试：
GIT_CURL_VERBOSE=1  git push -u origin master
会有详细的日志出现。



2015-04-14 0:18 GMT-04:00 yqfang <notifications@github.com>:

**Comment by xxnet** [comment]
下次抓日志时，不用有其他访问请求，好分析问题

在 2015年4月14日 上午5:05，Net XX <xxnet.dev@gmail.com>写道：

**Comment by xxnet** [comment]
前面修复了一个bug，POST附件超过16k有问题。
现在理论上限是10M，一般项目够了。
