### ISSUE TITLE
划转10G流量给需要的朋友

### ISSUE THREAD

**Issue by qibin8687** [XX-net/XX-Net#13709]
没有购买XTunnel收费服务的网友，可以给邮箱发函，说明你的注册名，我给你划转10g流量。今年10月到期。
我的邮箱：binarychee@gmail.com
----------------
如本帖不符站方利益，请直接删除，谢谢。

**Comment by qibin8687** [comment]
忘了说，不要回复本帖，直接发函。这里我不常来。

**Comment by qibin8687** [comment]
忘了说，不要回复本帖，直接发函。这里我不常来。

**Comment by xxnet** [comment]
新套餐模式启用了，目前流量转移功能已经取消了，请各位知晓。
