### ISSUE TITLE
4.8.0不显示套餐剩余

### ISSUE THREAD

**Issue by LeeLi888** [XX-net/XX-Net#13700]
4.5.4可以正常显示剩余流量，4.8.0就不显示了，而且好像登录不上去啊。

**Comment by nacl10h2o** [comment]
新版不显示剩余流量了，按官方的意思是分配的流量都够用，以后按月购买。你可以看一下登录界面的套餐选项。最近确实登不上去了，等等看

**Comment by Maogxer** [comment]
因为不限流量了啊！

**Comment by LeeLi888** [comment]
那现在不能赠送他人流量了吗

**Comment by xxnet** [comment]
是的，这个功能取消
