### ISSUE TITLE
请问为啥我购买了，为啥账号里面没有显示。

### ISSUE THREAD

**Issue by robinlighting** [XX-net/XX-Net#13721]
如题
![01](https://user-images.githubusercontent.com/39740368/171381739-2e42e872-1c43-4341-80a3-f733a52311d3.jpg)
![02](https://user-images.githubusercontent.com/39740368/171381750-d48ce679-f308-4a25-ba34-003621bcd46d.jpg)

**Comment by xxnet** [comment]
抱歉你的帐号出现异常，已经帮你恢复流量了。
