### ISSUE TITLE
XX-NET彻底不能用了吗？只有新版翻墙VPN了吗？

### ISSUE THREAD

**Issue by zhiganghan** [XX-net/XX-Net#13727]
之前买过XXtunel的套餐，后来到期了就用的免费流量。最近联系几天已经连不上了。请问XX-NET彻底不能用了吗？只有新版翻墙VPN了吗？

**Comment by xxnet** [comment]
GAE-Proxy 好久没有维护了，有很多问题，主要是Google 的策略调整了，已经不适合用了做梯子。
目前主要维护X-Tunnel，需要一些成本，所以需要购买套餐使用。

**Comment by zhiganghan** [comment]
> GAE-Proxy 好久没有维护了，有很多问题，主要是Google 的策略调整了，已经不适合用了做梯子。 目前主要维护X-Tunnel，需要一些成本，所以需要购买套餐使用。

您好，请教。没太搞懂。这个购买套餐是指的翻墙VPN这个套餐吗？购买了后原XXNET就可以继续使用吗？翻墙VPN是个独立的软件还是啥？没太懂之间关系

**Comment by xxnet** [comment]
抱歉，有点混乱了， 翻墙VPN (FQ-VPN) 是 XX-Net的新名字，同一套系统的，同一个套用户，相同套餐。
新注册的域名网站： https://fq-vpn.com 这个域名，考虑把FQ-VPN的logo改回XX-Net的logo

**Comment by JingHuangCN** [comment]
> 抱歉，有点混乱了， 翻墙VPN (FQ-VPN) 是 XX-Net的新名字，同一套系统的，同一个套用户，相同套餐。 新注册的域名网站： https://fq-vpn.com 这个域名，考虑把FQ-VPN的logo改回XX-Net的logo
您好！之前本来想购买xxnet套餐的，可是购买了2次都没有成功，支付的钱现在显示在账户里，账户里没有流量。这个应该怎么解决呢
![xx-net](https://user-images.githubusercontent.com/51557061/175224331-3fc25233-1cc8-486e-8899-518ca66dac00.png)

**Comment by JingHuangCN** [comment]
对的 XX-Net感觉是彻底用不了了 一直上不去。但是新版的还是用的XX-net？https://fq-vpn.com/profile的使用手册的链接还是xx-net。



在 2022-07-08 09:36:13，"zhiganghan" ***@***.***> 写道：

Closed #13727 as completed.
