### ISSUE TITLE
账号登录一会就自动下线

### ISSUE THREAD

**Issue by lxw-lxw** [XX-net/XX-Net#13731]
我的账号是 [lxianwei003@163.com](mailto:lxianwei003@163.com)
刚买了套餐，账号登录后，一会就掉线，变成 登录中；及时登录了 网速也比较满 忽高忽低，最高 1M/s 最低 0

**Comment by xxnet** [comment]
请按照这个公告操作：
https://github.com/XX-net/XX-Net/issues/13702
