### ISSUE TITLE
4.9.2 x-tunnel 超时的特别多,登陆也602

### ISSUE THREAD

**Issue by yz-xlame** [XX-net/XX-Net#13742]
4.9.2 x-tunnel 超时的特别多,登陆也602

**Comment by xxnet** [comment]
请把cloudflare 日志和帐号发邮件给 ***@***.***
我们给你一个独立的包

**Comment by yz-xlame** [comment]
有的时候又不太会,有的时候一直连不上

**Comment by yz-xlame** [comment]
> 请把flare日志和日志发邮件给***@****** 我们给你一个独立的包
看不到邮箱

**Comment by xxnet** [comment]
xxnet.dev@gmail.com
