### ISSUE TITLE
[发布] 新版 4.9.3 改进前端连接逻辑，增加状态收集功能

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13743]
最近墙似乎降了一点，不过我们继续改进。
先推送测试版更新，稳定了再推送稳定版更新。

**Comment by Shell1688** [comment]
mail.google.com 下“ 抱歉！無法載入您所選取的圖片。  ”     任何图片都无法正常显示

Michael.X ***@***.***> 於 2022年6月26日週日 上午10:17寫道：

**Comment by xxnet** [comment]
4.9.3 发布启动bug，已经发布 4.9.4
https://github.com/XX-net/XX-Net/issues/13744
