### ISSUE TITLE
XX-net 无法启动

### ISSUE THREAD

**Issue by spectrenever** [XX-net/XX-Net#13753]
系统 win7

之前自动更新4.9.1之后就出问题了，系统文件里面丢失了一个.dll之类的文件，我重新下载了一个，然后显示Python已停止工作。

Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3.8.2\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '\xc4N\u6778P'
  sys.base_prefix = '.'
  sys.base_exec_prefix = '.'
  sys.executable = '\xc4N\u6778P'
  sys.prefix = '.'
  sys.exec_prefix = '.'
  sys.path = [
    'D:\\Program Files (x86)\\XX-Net\\python3.8.2\\python38.zip',
    '.\\DLLs',
    '.\\lib',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the file
system encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001454 (most recent call first):
<no Python frame>

**Comment by xxnet** [comment]
Win7 用Win7 专用版本了吗？

**Comment by xxnet** [comment]
试试重新下载个 win7 版本
https://github.com/XX-net/XX-Net/releases/download/4.9.5/XX-Net-win7-4.9.5.7z

**Comment by spectrenever** [comment]
> 试试重新下载个 win7 版本 https://github.com/XX-net/XX-Net/releases/download/4.9.5/XX-Net-win7-4.9.5.7z

我又试了一次没有用
还是显示Python已停止工作，故障模块名称Python310.dll

**Comment by spectrenever** [comment]
我成免费用户了...
