### ISSUE TITLE
IP num/good 后面的good值不停的下降！

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#1375]
IP num/good	2478,240，当前是这样子，还在下降！

**Comment by Cat7373** [comment]
下降是正常情况，代表你有一些IP出现过不可用的情况。

**Comment by fletchere** [comment]
@Cat7373 我是担心是不是新版新添加的IP给墙盯上了，或者这个版本容易让IP泄露什么的！

**Comment by Cat7373** [comment]
并不是

**Comment by xxnet** [comment]
看看日志

2015-11-13 11:44 GMT+08:00 fletchere <notifications@github.com>:

**Comment by xxnet** [comment]
老的版本没有统计ip不可用的情况，升级时默认所有ip都是可用的，然后在实际使用中去检测和剔除。
你只要实际使用体验不受影响就好

2015-11-13 12:49 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
@xxnet 现行的IP替换方式是某个IP不可用的时候计数+1，IP满的时候剔除计数最多的IP？
没仔细去看代码- -

**Comment by xxnet** [comment]
目前的策略：

对于一个IP，连接失败时，失败计数+1，一旦连接成功，失败计数归零。


IP 满时，删除最差的ip，计算公式： 失败计数*1000+握手耗时

在 2015年11月13日 下午2:28，Cat73 <notifications@github.com>写道：

**Comment by fletchere** [comment]
@xxnet 谢谢xx大神，不影响使用，很流畅！只是有些担心而已！
