### ISSUE TITLE
最近发现 4.9.5 版本有内存溢出的情况,疯狂吃内存

### ISSUE THREAD

**Issue by jaxguo** [XX-net/XX-Net#13770]
不动就会一直涨,几分钟就上g
电脑版本是win11 
![Uploading image.png…]()

**Comment by jaxguo** [comment]
![Uploading image.png…]()

**Comment by jaxguo** [comment]
![QQ图片20220827125705](https://user-images.githubusercontent.com/9720390/187055542-22fda43e-9a68-41b1-9c2b-2ef19f8d5c7c.png)

**Comment by jaxguo** [comment]
重启电脑后问题没有复现...

**Comment by xxnet** [comment]
内存泄漏也有报告过，但是不好重现，有重新的时候再发

**Comment by jaxguo** [comment]
> 内存泄漏也有报告过，但是不好重现，有重新的时候再发

测试了几天, 在开启远程访问后,内存暴涨的现象就会出现.

**Comment by xxnet** [comment]
开启远程访问后，你是从远程访问还是本地访问会出现内存暴涨的？

理论上远程访问的逻辑是没有差别的，只是网络发送延迟有一点小差别，所以这个规律还有待观察。

**Comment by jaxguo** [comment]
> 开启远程访问后，你是从远程访问还是本地访问会出现内存暴涨的？
> 
> 理论上远程访问的逻辑是没有差别的，只是网络发送延迟有一点小差别，所以这个规律还有待观察。

![image](https://user-images.githubusercontent.com/9720390/188131354-80024709-1613-4046-b316-67bc48618fbd.png)
只是开启远程访问就会内存增长.

**Comment by jaxguo** [comment]
> 
找到问题了,我配置的远程访问端口是1080, 但是team viewer 这个软件有时候也会占用1080端口.关闭tv软件后,内存不再溢出.
那这个问题判断是几个软件抢端口导致的?

**Comment by xxnet** [comment]
有可能，有空研究下。
