### ISSUE TITLE
smart_router_warning.log 这个文件产生大量重复日志

### ISSUE THREAD

**Issue by niu541412** [XX-net/XX-Net#13777]
夜里零点之后家里宽带出了故障。光猫连不上外网，就去睡觉了。
今早起床网络恢复了，但发现自己macbook的硬盘被写满了。
其中smart_router_warning.log这个文件居然有90多GB。但不确认夜里写入的占比多少。
里面的内容似乎都是一样的，末尾的都是1ms写入一次。
![image](https://user-images.githubusercontent.com/3370897/188535448-2e3f9090-b504-48fb-a523-b95f91839735.png)
类似于
> 2022-09-06 10:08:50.469 - [ERROR] pipe except:ValueError('filedescriptor out of range in select()')
> 2022-09-06 10:08:50.470 - [ERROR] Except stack:Traceback (most recent call last):
>   File "/Users/myname/Documents/XX-Net/code/4.9.5/smart_router/local/pipe_socks.py", line 152, in pipe
>     r, w, error_set = select.select(self.read_set, self.write_set, self.error_set, 0.1)
> ValueError: filedescriptor out of range in select()
> 
> 2022-09-06 10:08:50.470 - [ERROR] pipe except:ValueError('filedescriptor out of range in select()')
> 2022-09-06 10:08:50.472 - [ERROR] Except stack:Traceback (most recent call last):
>   File "/Users/myname/Documents/XX-Net/code/4.9.5/smart_router/local/pipe_socks.py", line 152, in pipe
>     r, w, error_set = select.select(self.read_set, self.write_set, self.error_set, 0.1)
> ValueError: filedescriptor out of range in select()

**Comment by xxnet** [comment]
好的，谢谢反馈。
下个版本加上处理逻辑。
