### ISSUE TITLE
账号密码错误

### ISSUE THREAD

**Issue by IcedCoffeel** [XX-net/XX-Net#13796]
# 规则：
* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

# 提问模版：
- 操作系统：win10
- 客户端版本号：刚下载的最新的
- 问题现象：注册账号点了一下没什么反应，再点一下提示邮箱已经占用，去登陆提示账号密码错误，改密码还是账号密码错误
- 对应模块的日志：

**Comment by IcedCoffeel** [comment]
https://fq-vpn.com/profile在这里就能登录
换到http://localhost:8085/这里就登录不了，提示账号密码错误，真是离谱

**Comment by xxnet** [comment]
你可以试试找回密码的方式换个密码，不行的话把账号发 ***@***.*** 给你处理

**Comment by IcedCoffeel** [comment]
已经找回过一次账号密码了

**Comment by IcedCoffeel** [comment]
又尝试找回密码还是不能登陆，一直提示用户名密码不正确，心态爆炸

**Comment by xxnet** [comment]
给你复位密码了，私信给你了

**Comment by IcedCoffeel** [comment]
***@***.***

还是不行。。。。
________________________________
发件人: Michael.X ***@***.***>
发送时间: Sunday, October 16, 2022 2:41:55 PM
收件人: XX-net/XX-Net ***@***.***>
抄送: IcedCoffeel ***@***.***>; Author ***@***.***>
主题: Re: [XX-net/XX-Net] 账号密码错误 (Issue #13796)


给你复位密码了，私信给你了

―
