### ISSUE TITLE
使用XX-Net导致浏览器无法保存和加载一个python在线编辑器（codeskulptor）的文件

### ISSUE THREAD

**Issue by levonlin** [XX-net/XX-Net#138]
大神，我参加的一门mooc要用到这个在线编辑器，以前用3.23的goagent没有问题，改用XX-Net后每当我用XX-Net打开[codeskulptor](www.codeskulptor.org)里那些python文件时总会弹出不能加载或保存文件的alert。

之后chrome一直出现这个情况，换其他穿墙工具一样。然后我发现清空使用xx-net的历史记录后其他穿墙工具就可以加载那里的文件了，而XX-Net我更到1.85仍然不可以。

codeskulptor本身是使用google的一些api的，旧版的goagent也有人报告过这个问题，而之前我用3.23的goagent没有问题。下面是我的配置，希望大神能解决这个问题，thx:)

|Sys Platform	|win32|
|OS System	|Windows|
|OS version	|6.1.7601|
|OS release	|7|
|OS detail        |Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0|
|architecture	|32bitWindowsPE|
|Browser	|Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36|
|XX-Net Version	|1.8.5|
|Launcher Version	|1.3.0|
|GoAgent Version	|3.1.48|
|Python Version	|2.7.9|

**Comment by xxnet** [comment]
收到

在 2015年4月13日 上午8:01，levonlin <notifications@github.com>写道：

**Comment by xxnet** [comment]
新版已经解决

**Comment by levonlin** [comment]
万分感谢~

**Comment by levonlin** [comment]
大神，新版用了没几天，今天相同的问题又复发了，为何js还是会判断失误？

**Comment by xxnet** [comment]
具体什么提示？
我测试可以工作

在 2015年4月18日 上午10:53，levonlin <notifications@github.com>写道：

**Comment by levonlin** [comment]
打开初始页面没问题，但是一打开里面存好的程序譬如[这个](http://www.codeskulptor.org/#examples-spaceship_template.py)，就会弹出unable to load file:xxxx

**Comment by xxnet** [comment]
goagent/x.x.x/local/proxy.ini
加一行
.commondatastorage.googleapis.com = gae

我明天发新版带上

2015-04-18 21:36 GMT-04:00 levonlin <notifications@github.com>:
