### ISSUE TITLE
4.13.1 频繁崩溃

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#13821]
错误应用程序名称: pythonw.exe，版本: 3.10.4150.1013，时间戳: 0x623baa7b
错误模块名称: **boringssl.pyd**，版本: 0.0.0.0，时间戳: 0x636c2d71
异常代码: **0xc0000005**
错误偏移量: **0x00000000000447f6**
错误进程 ID: 0x9dc0
错误应用程序启动时间: 0x01d8f8a1688c5c05
错误应用程序路径: C:\Program Files (x86)\XX-Net\python3\pythonw.exe
错误模块路径: C:\Program Files (x86)\XX-Net\python3\lib\site-packages\boringssl.pyd
报告 ID: 0b01560f-cb56-4b47-9144-d0aeebaaa2a0
错误程序包全名: 
错误程序包相对应用程序 ID: 

错误应用程序名称: bad_module_info，版本: 0.0.0.0，时间戳: 0x00000000
错误模块名称: unknown，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0x00000000
错误偏移量: 0x0000000000000000
错误进程 ID: 0x9030
错误应用程序启动时间: 0x01d8f8a114b797c6
错误应用程序路径: bad_module_info
错误模块路径: unknown
报告 ID: 1dd6acad-82f2-493e-b097-d153900bbe6c
错误程序包全名: 
错误程序包相对应用程序 ID: 

错误应用程序名称: pythonw.exe，版本: 3.10.4150.1013，时间戳: 0x623baa7b
错误模块名称: **ntdll.dll**，版本: 10.0.19041.2130，时间戳: 0xb5ced1c6
异常代码: **0xc0000374**
错误偏移量: **0x00000000000ff6a9**
错误进程 ID: 0x8ad0
错误应用程序启动时间: 0x01d8f89ea06574ce
错误应用程序路径: C:\Program Files (x86)\XX-Net\python3\pythonw.exe
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: 1fa58459-7ff7-45b4-be71-792509de558f
错误程序包全名: 
错误程序包相对应用程序 ID: 

=============

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.19045-SP0
os-system: Windows
os-version: 10.0.19045
os-release: 10
os-detail: Version:10-0; Build:19045; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 64bit,WindowsPE
browser: 
xxnet-version: 4.13.1
python-version: 3.10.4
openssl-version: OpenSSL 1.1.1n  15 Mar 2022 TLS 1.3 h2:<bound method SSLContext.support_alpn_npn of <front_base.boringssl_wrap.SSLContext object at 0x000001B0FECA4A30>>
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:201 ipv4:11 ipv6:188
ipv4-status: OK
ipv6-status: OK
connected-link: new:2
worker: h1:0 h2:57
scan-ip-thread-num: 200
ip-quality: 144
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
@cym104 新版出来了，做了相应的改进，你测试下效果
