### ISSUE TITLE
android can't login

### ISSUE THREAD

**Issue by quan0725** [XX-net/XX-Net#13835]
android客户端无法登录  4.13.7
![Screenshot_20221201_152844](https://user-images.githubusercontent.com/8132575/204992678-e26ccbab-ae5e-428f-8ec2-ad1306338e71.jpg)
![Screenshot_20221201_152844](https://user-images.githubusercontent.com/8132575/204992730-b53d6fa7-9b3e-4c0e-9c3f-9ec0c6d949a3.jpg)

规则：
* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

# 提问模版：
- 操作系统：
- 客户端版本号：
- 问题现象：
- 对应模块的日志：

**Comment by xxnet** [comment]
是从 https://xx-net.com 下载的吗？
不是的话试试从这个网址上下载，原来的删除再重新安装

**Comment by quan0725** [comment]
从这个地址上重新下载了 怎么用呢 浏览器依然上不了google

在 2022-12-02 07:13:54，"Michael.X" ***@***.***> 写道：


是从 https://xx-net.com 下载的吗？
不是的话试试从这个网址上下载，原来的删除再重新安装

**Comment by nacl10h2o** [comment]
需要在界面右上角，“三”里面系统-配置-应用列表设置代理应用。

**Comment by nacl10h2o** [comment]
我有个问题，就是google商店的应用无法更新，但是Google商店能访问。

**Comment by xxnet** [comment]
@nacl10h2o  暂时不这次Google Play，可以先用 APKPure等第三方应用市场

**Comment by quan0725** [comment]
1 应用列表里没有浏览器呢
2 当我选择了应用 按下最底部的保存 提示重启vpn 怎么重启vpn呢
3 退出xx-net后再打开 白屏

在 2022-12-03 19:07:30，nacl10h2o ***@***.***> 写道：


需要在界面右上角，“三”里面系统-配置-应用列表设置代理应用。

**Comment by nacl10h2o** [comment]
@quan0725 
1.仔细找找，找你浏览器名称
2.保存完以后，往上滑，回到顶部，右上角“三”-退出。重启即可

**Comment by Maogxer** [comment]
用回 4.13.3，我4.13.7也登录不了。

**Comment by xxnet** [comment]
@Maogxer 
是否付费用户？
是否从https://xx-net.com 下载？

**Comment by Maogxer** [comment]
> @Maogxer 是否付费用户？ 是否从https://xx-net.com 下载？

多年付费用户。https://xx-net.com/ 和 Github 都有下载安装。
用 4.13.7 就登录不了，也试了其它版本，一直用4.13.3 就没有问题。

**Comment by xxnet** [comment]
@Maogxer 请把账号发到 xxnet.dev@gmail.com 我给你看一下，谢谢！
