### ISSUE TITLE
有些时候google会报证书错误，需要重开xx-net

### ISSUE THREAD

**Issue by ted423** [XX-net/XX-Net#1384]
我看了证书变成了googlevideo.com的证书

**Comment by xyuanmu** [comment]
这个证书是可以用的，打不开网页吗？

**Comment by simonasd** [comment]
重开即可恢复正常？试着删除data目录下的cert文件夹

**Comment by ted423** [comment]
googlevideo.com是youtube的证书啊

**Comment by sfagu** [comment]
也是这情况，删除cert好像可行

**Comment by ted423** [comment]
其实印象里以前goagent好像就有这问题来着

**Comment by sfagu** [comment]
总是重启gaeproxy就好一段时间，老是这么反复

**Comment by xxnet** [comment]
@sfagu
 你把日志贴出来看看

2015-11-20 8:16 GMT+08:00 sfagu <notifications@github.com>:

**Comment by ted423** [comment]
没有继续使用。。
