### ISSUE TITLE
4.8.0 之后的所有版本在使用GAE的时候都会出问题。

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#13861]
4.8.0 之后的所有版本（直到最新的5.0.5都包括在内）在使用GAE的时候都会遇到这么个问题：
xx-net刚启动的时候GAE一切正常，可以通过GAE上网。但在运行十几分钟到半个小时左右的时候就会出现连接池的三个数字都逐渐降到0而且不再增加。纵使这个时候还存在足够的有效 IP，也依旧无法再通过GAE上网。唯一的解决办法是重启xx-net。
直到4.8.0还是正常的。从4.8.1开始就出现了这个问题，一直延续到现在。
win10系统。
服务端已经重新部署成了新版的。
试过全新安装xx-net，问题依旧。

**Comment by cym104** [comment]
最新的507版本依然没有解决这个问题。

**Comment by xxnet** [comment]
好的，我看看.
最近一个没这个问题的是哪个版本？

**Comment by cym104** [comment]
> 好的，我看看. 最近一个没这个问题的是哪个版本？

4.8.0

**Comment by xxnet** [comment]
5.0.8 修复了一个GAE的问题

没有重现一楼出现的现象，不知道解决了没有，请测试

**Comment by xxnet** [comment]
把发病后出错日志发到  xxnet.dev@gmail.com

**Comment by cym104** [comment]
5.2.0竟然解决了这个问题！
https://github.com/XX-net/XX-Net/issues/13925
