### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by FlameRaptor** [XX-net/XX-Net#1387]
Nov 15 20:16:02 - ============ Begin upload ============
appid:alpha

Nov 15 20:16:02 - Application: alpha
Nov 15 20:16:02 - Host: appengine.google.com
Nov 15 20:16:02 - Rolling back the update.
Nov 15 20:16:02 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbuJyrLyV7V5IbN3edXIu3M5ZSHW2-QQ-3JYcdicagc0TYmoeBLkQt6cv1F1WM9uoScQRigY42ZQ35uMARfo-QCZ0wXBHMui5oeK-o0fHjQ_6IQ9xqv7iQdgzoCgnmQKXZs1-s-yl2DjlJ9GVKPf2HncSZ-brFynQb8RJPrcRC11IxskanMhX9O6Zy_KB5XMOVXag8XMPfDj8Sn-BQED_ja5A3Ty1QaJ9ZYtA-TOu0BASxjkdGo
Info=WebLoginRequired

Nov 15 20:16:02 - Invalid username or password.
Nov 15 20:16:02 - Error 403: --- begin server output ---
403 Forbidden: Forbidden
--- end server output ---
Nov 15 20:16:02 - upload fail: HTTP Error 403: Forbidden

Nov 15 20:16:02 - Auth fail. Please check you password.
Nov 15 20:16:02 - 登录失败，请检查你的帐号密码。
Nov 15 20:16:02 - 如果启用两阶段登录，请申请应用专用密码: https://security.google.com/settings/security/apppasswords
Nov 15 20:16:02 - 如果没有启用两阶段登录，请允许弱安全应用: https://www.google.com/settings/security/lesssecureapps
Nov 15 20:16:02 - =======================
Nov 15 20:16:02 - Deploy failed appid list:
Nov 15 20:16:02 - - alpha
Nov 15 20:16:02 - - bravo
Nov 15 20:16:02 - - charlie
Nov 15 20:16:02 - - ranger
Nov 15 20:16:02 - == END ==

200%确定没有开二步验证，开了弱安全

**Comment by xyuanmu** [comment]
试试，先关闭弱安全，再重新开启，看看能不能部署。
上个月我上传新密码的时候有一个帐号就是这样，若安全已经开启但是不能部署，我先关闭后开启就能部署了。

**Comment by FlameRaptor** [comment]
已解决，谢谢
