### ISSUE TITLE
【急】阿里云服务器开启XX-NET，流量瞬间就被打满，且CPU跟内存都会飙升。

### ISSUE THREAD

**Issue by chiefleo** [XX-net/XX-Net#13908]
操作系统：Alibaba Cloud Linux  3.2104 LTS 64位
CPU&内存：4核(vCPU)16 GiB
客户端版本号：5.1.1
问题现象：开启XX-NET，网络流量瞬间就被打满，且CPU、内存、硬盘读写都会飙升；因为网络带宽有限，1M带宽机器几秒内就假死；临时升级带宽到40M之后，XX_NET过一会仍然会假死，无法代理。
<img width="510" alt="image" src="https://user-images.githubusercontent.com/783905/232827073-498d5062-0e8d-4fa8-9e51-45dbd491f840.png">

之前（几个月的时间）的小问题是服务器跑一段时间之后，CPU、内存升的比较高，crontab设置定期重启之后，勉强还能用；
但最近一两周的问题是，只要一开XX-NET，网络流量瞬间就被打满，完全不能用了。
比较着急，恳请大神帮解决一下呢，谢谢。

**Comment by chiefleo** [comment]
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/783905/232829317-6f218eea-9b43-4921-a463-452141929285.png">

**Comment by chiefleo** [comment]
确认是XX-Net哈，只要把服务器一关，CPU、内存、网络流量瞬间就跌到很低了；
确实我本地MBP跑起来也没问题，有问题的只是阿里云服务器，不知道是不是什么软件冲突了，您方便telegram沟通一下吗？我提供更多的资料给您。

**Comment by xxnet** [comment]
发邮件到 xxnet.dev@gmail.com

**Comment by chiefleo** [comment]
好的  谢谢

**Comment by chiefleo** [comment]
在官方大大的热心协助下，问题解决，解决方案：关闭服务器8085远程端口，避免被公网扫描代理。

**Comment by chiefleo** [comment]
在官方大大的热心协助下，问题解决，解决方案：关闭服务器8085远程端口，避免被公网扫描代理。
