### ISSUE TITLE
退款申请

### ISSUE THREAD

**Issue by billybillywu** [XX-net/XX-Net#13900]
您好，我今天付费的，使用发现速度太慢，也没法访问chatgpt ，想申请退款，请问哪里退款，谢谢

**Comment by xxnet** [comment]
请发邮件到 ***@***.***

**Comment by Coding4Me** [comment]
@xxnet 麻烦问下， 能不能访问chatgpt？

**Comment by honghaier250** [comment]
![Snipaste_2023-05-09_17-23-34](https://user-images.githubusercontent.com/8481347/237054197-42ec4308-e78d-4152-a910-7d30b0c114c5.png)

**Comment by xxnet** [comment]
@honghaier250 已经给你退款了，请查收

**Comment by Pegasusagithub** [comment]
买来就没连上过，已经申请退款了，不知道能不能退
