### ISSUE TITLE
有没有考虑做成可自订AE的

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#1390]
让用户可选Google之外的AE

**Comment by xxnet** [comment]
有考虑，不过都需要收费

在 2015年11月16日 下午1:10，wooowooo <notifications@github.com>写道：

**Comment by wooowooo** [comment]
> 有考虑，不过都需要收费

我知道有来自英国的免费python平台,具体名字就不说了,说了怕被土啬掉.
使用这种小众的没有被关注的python平台部署goagent,就不需要扫描可用ip了.
其实这个也许不是xx-net是问题,是关于goagent的.如何把goagent中google的服务器地址改成其他AE地址?我自己不懂改
