### ISSUE TITLE
5.2.0 发现一个总掉线的bug！

### ISSUE THREAD

**Issue by angelop007** [XX-net/XX-Net#13928]
- 操作系统：Windows 10 专业版 22H2.19045.3086
- 客户端版本号：5.2.0
- 问题现象：总是软件登录成功后没多久，就各种断，连不上

1. 点击根目录start.bat，默认自动随机连接服务器节点。
2. 连上后google，youtube， github  一切正常。
3. 没过多久节点就断开了。
4. 关闭软件，或是关闭python的cmd窗口后，因为守护进程会再次启动起来，自动登录后，自动连接节点，又ok了，但是过一会又会挂。
5. 再关cmd窗口有彻底崩溃迹象。
6. 重新启动start.bat后又是如上反复的节点断连。。

PS：即便是连上 网速也是慢的没法玩。。。公司和家里都是陕西电信千兆带宽家里独享的，这慢的有点说不过去，今天晚上连个chrome的官网打开都要半分钟以上。貌似默认是法国节点，但是我更换了日本节点是能快一些，但是频断问题让人抓狂的没法用啊。。。

买了1个多月了，虽然补偿了一次从06-04号开始计算了，但是目前就没怎么稳定能持续使用的。。我想问下这问题还能处理不了？不能的话可以退钱么？就是看这个vpn都8年了，不容易支持下，试用时候还不错比较流畅的看youtube4k拖拽也就5秒左右就能续播，但是这付了费就这样的体验。。。

**Comment by xxnet** [comment]
抱歉，刚好遇上64，每年这个时间都会卡。

你账号发我邮箱 xxnet.dev@gmail.com 我给你看看

**Comment by angelop007** [comment]
这是来自QQ邮箱的假期自动回复邮件。

您好，我已收到您的邮件。
