### ISSUE TITLE
近期登陆不了处理办法

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13922]
还有无法登陆的，请上 xx-net.com  或 xxnet.pro 上获取令牌登陆
还不行就请把账号发邮件到 xxnet.dev@gmail.com

**Comment by AlephAlpha** [comment]
现在是能登录但上不了网。

**Comment by shishenzhezai** [comment]
https://xx-net.com/ 可能被墙了，chrome浏览器提示：无法访问此网站 ，ERR_CONNECTION_TIMED_OUT，这里是重庆电信

**Comment by ArchNew** [comment]
我能登录了才看到这条……

**Comment by tincochan** [comment]
前几天能上官网用令牌登陆， 但是隔天就马上登不上了。

**Comment by DURA18** [comment]
发了邮件，但是没有收到回复，账号也一直不能用

**Comment by jon945** [comment]
> 现在是能登录但上不了网。
> 
> 改用令牌登录后能上了。还是不行，只连上了很短一段时间。甚至不能稳定登录。

我也是，用令牌登录和用密码登录其实结果是一样的，一会就掉线了，再就是又要艰难的登录

**Comment by ghsybh** [comment]
官网看不了了，前几天令牌登录没一个小时就掉线了，赶紧解决呀

**Comment by xxnet** [comment]
抱歉各位，有些地区封锁比较严格，花了几天时间处理，刚刚已经发了新版了，今天会回复大家邮件。
 #13925
