### ISSUE TITLE
安卓上没办法使用

### ISSUE THREAD

**Issue by gxllw0** [XX-net/XX-Net#13921]
用的是安卓5.1.0，放后台再打开要重新登录，试着访问谷歌也没成功。手机的安卓版本是Android 13。已购XX-tunnel，电脑上可以正常使用。

**Comment by xxnet** [comment]
请上 xx-net.com  或 xxnet.pro 上获取令牌登陆
还不行就请把账号发邮件到 xxnet.dev@gmail.com

**Comment by gxllw0** [comment]
登录偶尔会成功，但成功登录也访问不了网站，放后台进程还在但是再打开要重新登录，不知道是哪步没做好，我电脑上是没有问题的。能不能出点详细的安卓教程。
