### ISSUE TITLE
可以登录，网速极慢

### ISSUE THREAD

**Issue by Averbakh** [XX-net/XX-Net#13939]
- 操作系统：Win11 22H2
- 客户端版本号：5.4.0
- 问题现象：可以登录，所有代理方式的网速都相当于没有。已经阅读网速缓慢通用解决方案，但没有配置gae的条件。此外用热点网速就正常，用wifi才没有速度。wifi本身没有网速问题。截图截到了比较“快”的瞬间，但平均下来只有几kBps
- 对应模块的日志：
![VCJ39H1(EE 
[log.txt](https://github.com/XX-net/XX-Net/files/12123255/log.txt)
QG6A X0$N0KM](https://github.com/XX-net/XX-Net/assets/140142809/61ccdb91-8470-479b-95a0-01db065b29ed)

**Comment by xxnet** [comment]
请把账号发 xxnet.dev@gmail.com
