### ISSUE TITLE
退款申请

### ISSUE THREAD

**Issue by wycbit** [XX-net/XX-Net#13937]
网速太慢，申请退款。

**Comment by github103** [comment]
<img width="360" alt="image" src="https://github.com/XX-net/XX-Net/assets/32588327/ea5f8f8f-3747-4fa7-a697-20d17db33262">

**Comment by wycbit** [comment]
谢谢，来信已收到，我会及时回复！

**Comment by wycbit** [comment]
我拉github代码都报超时。而且不超过七天。谢谢
