### ISSUE TITLE
令牌登陆报602

### ISSUE THREAD

**Issue by szxLH** [XX-net/XX-Net#13942]
- 操作系统：mac
- 客户端版本号：5.4.5
- 问题现象：只有令牌登陆，并且一直登陆不上去，报602
- 对应模块的日志：

**Comment by szxLH** [comment]
没有售后吗。。。😭😭😭

**Comment by shikicc** [comment]
> 没有售后吗。。。😭😭😭
我也一样，买了两年的登陆不上，给他们发邮件，也没有回复，我简直无语了！！！

**Comment by ikun-PurePasserby** [comment]
一样的602，发了邮件现在还没回复

**Comment by shikicc** [comment]
> 

不知道他们会不会解决问题
没有这个服务能力，就不要收费，收费了就要有点责任心，本来也是老用户，看推出了了收费版，我觉得应该会靠谱，竟然出现这种问题，我简直服了！联络无门！

**Comment by Pd69bq** [comment]
v5.4.5 遇到同樣的登錄602錯誤 v5.4.2已久正常

**Comment by xxnet** [comment]
抱歉，服务器出了点问题，现在已经修复了

**Comment by szxLH** [comment]
![图片](https://github.com/XX-net/XX-Net/assets/14286032/d07d3c2e-a6cb-4534-8515-3be6ffbead9a)
还是不行，帮忙退了吧，已经发过邮件了 @xxnet

**Comment by xxnet** [comment]
已经退款
