### ISSUE TITLE
访问chatgptg网站，提示Unable to load site

### ISSUE THREAD

**Issue by billybillywu** [XX-net/XX-Net#13955]
您好

我最近一直在使用Chat.openai.com 访问，然后这两天突然访问的时候，网页提示： unable to load site ,并给出了ip地址。我网上查了一下，感觉是ip被封了，这种xx-net不是使用混淆算法的吗？ ip应该每次都是不一样的，我如何才能解决这个问题呢？

**Comment by Tangor522** [comment]
我也是，2天了

**Comment by Pd69bq** [comment]
> If you are using a VPN, try turning it off.

[13952](https://github.com/XX-net/XX-Net/issues/13952)

**Comment by xxnet** [comment]
ChatGPT 问题已经修复，请大家测试
