### ISSUE TITLE
部署自己的appid之后访问youtube仍然显示"共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问"

### ISSUE THREAD

**Issue by genfrost** [XX-net/XX-Net#1396]
如题。状态页如下，xx-net版本是2.5.5。working appids中头两个appid是自己的。
谢谢。

系统版本

Property	Value
XX-Net Version	2.5.5
Python Version	2.7.9
Sys Platform	AMD64, Windows-7-6.1.7601-SP1
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	533
100th IP handshake(ms)	1415
connected link(帮助)	10,1
scaning ip thread num	50
block stat(帮助)	OK
Appid

Property	Value
working appids	gfwinder1|gfwind|xxnet-1|xxnet-4|xxnet-5|xxnet-6|xxnet-8|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-130|xxnet-131|xxnet-132|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-153|xxnet-154|xxnet-155|xxnet-157|xxnet-159
Out of Quota appids	xxnet-56|xxnet-7|xxnet-9|xxnet-133|xxnet-152|xxnet-79|xxnet-50|xxnet-85|xxnet-129|xxnet-3|xxnet-156|xxnet-158|xxnet-2
Not Exist appids

**Comment by xyuanmu** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=config
填到这里，不是修改proxy.ini

**Comment by xxnet** [comment]
怀疑是2.5.5的一个bug。

重启看看是不是能够正常

2015-11-17 15:38 GMT+08:00 genfrost <notifications@github.com>:

**Comment by xxnet** [comment]
xyuanmu 是对的，不要直接修改配置文件，web界面上可以直接设置

2015-11-17 16:21 GMT+08:00 xyuanmu <notifications@github.com>:

**Comment by genfrost** [comment]
@xyuanmu @xxnet 两位抱歉，我的appid打了码……发出来的文本里的id是改过的。
我的两个id已经部署过并且填在http://127.0.0.1:8085/?module=gae_proxy&menu=config的最前面了。
那么是否需要我提供真实的appid呢？

已经尝试过右键重启xx-net和重启电脑，问题仍然存在。上次见过问题存在然后消失可是没搞懂怎么消失的。

**Comment by xyuanmu** [comment]
如果已将appid填在：http://127.0.0.1:8085/?module=gae_proxy&menu=config 并保存，那么状态页，working appids 后面显示的应该就是你自己的appid，不需要重启xx-net的。

**Comment by Lrevor** [comment]
你把原来自带的都删掉，光留你自己的Appid

**Comment by genfrost** [comment]
嗯 原来问题是我没把旧的删掉只是把新的加在最前面……删掉后问题解决 多谢各位
