### ISSUE TITLE
全局PAC智能代理端口8086与123云盘冲突，如何修改智能代理端口8086？谢谢

### ISSUE THREAD

**Issue by mayichen1987** [XX-net/XX-Net#13970]
全局PAC智能代理端口8086与123云盘冲突，如何修改智能代理端口8086？谢谢

**Comment by CompleX0321** [comment]
https://github.com/XX-net/XX-Net/wiki/X-Tunnel-Config-file

**Comment by mayichen1987** [comment]
> https://github.com/XX-net/XX-Net/wiki/X-Tunnel-Config-file

谢谢。但是X Tunnel是1080口，我要改的是智能代理端口8086。

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/Change-Smart-Router-Config

**Comment by mayichen1987** [comment]
> https://github.com/XX-net/XX-Net/wiki/Change-Smart-Router-Config

谢谢大佬，解决了
