### ISSUE TITLE
5.9.0 gcloud 部署时发生的连接问题

### ISSUE THREAD

**Issue by mmsdmt** [XX-net/XX-Net#13999]
5.9.0发布后根据#13994中相关回复和Wiki尝试对服务端进行重新部署，但是出现了一些问题。

信用卡绑定和打开cloud build的权限，将"App Engine"后面改成“已启用”均已完成。

在输入gcloud auth login后，无法继续使用xx-net因为这时页面会自动跳转至localhost:8085，遂尝试利用其它vpn后可以通过跳转页面并在网页端显示"您现在已通过 gcloud CLI 身份验证！”。但是在CMD端显示以下信息：

ERROR: gcloud crashed (ConnectTimeout): HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C8F001FD90>, 'Connection to oauth2.googleapis.com timed out. (connect timeout=None)'))

用gcloud init 和 gcloud info --run-diagnostics检查发现是Network diagnostic failed，有如下信息:

ERROR: Reachability Check failed.
    httplib2 cannot reach https://accounts.google.com:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

    httplib2 cannot reach https://cloudresourcemanager.googleapis.com/v1beta1/projects:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

    httplib2 cannot reach https://www.googleapis.com/auth/cloud-platform:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

    httplib2 cannot reach https://dl.google.com/dl/cloudsdk/channels/rapid/components-2.json:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

    requests cannot reach https://accounts.google.com:
HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

    requests cannot reach https://cloudresourcemanager.googleapis.com/v1beta1/projects:
HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1beta1/projects (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

    requests cannot reach https://www.googleapis.com/auth/cloud-platform:
HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /auth/cloud-platform (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

    requests cannot reach https://dl.google.com/dl/cloudsdk/channels/rapid/components-2.json:
HTTPSConnectionPool(host='dl.google.com', port=443): Max retries exceeded with url: /dl/cloudsdk/channels/rapid/components-2.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

Network connection problems may be due to proxy or firewall settings.

不知道该如何解决这一问题？

**Comment by swjtu2004** [comment]
部署时候不要用xxnet翻墙，换个其他软件。

**Comment by mmsdmt** [comment]
> 部署时候不要用xxnet翻墙，换个其他软件。

感谢回复，后续换了nthlink后成功部署好了
