### ISSUE TITLE
导入证书时出错

### ISSUE THREAD

**Issue by cslxiao** [XX-net/XX-Net#1399]
Chrome浏览器导入证书时出错：
Certification Authority Import Error
The file contained multiple certificates, none of which were imported:
Equifax: Certificate already exists.
GeoTrust Global CA: Certificate already exists.

出现这个报错窗口

访问google时出现如下提示：
Your connection is not private

Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
Subject: *.google.com
Issuer: GoAgent XX-Net
Expires on: Nov 16, 2016
Current date: Nov 17, 2015
PEM encoded chain: -----BEGIN CERTIFICATE-----
MIIDczCCAlugAwIBAgIQWH2wIHT/slBu3oGEN6m2VTANBgkqhkiG9w0BAQsFADBz
MQswCQYDVQQGEwJDTjERMA8GA1UECBMISW50ZXJuZXQxDzANBgNVBAcTBkNlcm5l
dDEQMA4GA1UEChMHR29BZ2VudDEVMBMGA1UECxMMR29BZ2VudCBSb290MRcwFQYD
VQQDEw5Hb0FnZW50IFhYLU5ldDAeFw0xNTExMTcxMzIzMzdaFw0xNjExMTYxMzMz
MzdaMHgxCzAJBgNVBAYTAkNOMREwDwYDVQQIEwhJbnRlcm5ldDEPMA0GA1UEBxMG
Q2VybmV0MRcwFQYDVQQLEw5Hb0FnZW50IEJyYW5jaDEVMBMGA1UEAxQMKi5nb29n
bGUuY29tMRUwEwYDVQQKFAwqLmdvb2dsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCs0Vw514acKZQKncBif83Tqa6WXN8OKYULfI1eudGbykwM
qKDVZmF5NgpBlrsLoKL32t6FVYc+FjrHsIwZvEvOpCS2C0Lib1iGdhwG1CjvuiO5
+9AQqx4m3vvvYQ4rMCwljIvvBib6K7tcxj1rpFI8SI6lTQYAi6Ni2d3u+7Tmayvm
ZvmRJVr+F9UZ/EIcf84t5XZ9w9RgjCUrtYEW0OOj7nmvDLZY9XLQNYrwkNMqluHJ
tHqmD1n+2RqfdACLXzSo1cKEym3EiC+uTWWNODfO9HLtaNLsbc2bYgaTqEQ0McAf
tVmUC+xx7b8mau73/CDg+64xQrY03bDjsu92LweXAgMBAAEwDQYJKoZIhvcNAQEL
BQADggEBADo5F8HVPz8IDPgA0kHVImvIsiXukv/5sInT06yCZfLixI/ESnaNtLM2
dGeIWdsff+FNl0hbYSZnNRTNg377HnJJYTljY5dgCGa5/7ftSJyyQlBZ2ws+ORMP
nDjgpXdwKvtM23teWRivOoCFOpBrxB4R5smLU+NeIDtSOg/dso8qnjDBF/o3wK0x
mDEatL37eXex1QBeIdmrtbuQxJ5FWGIqAFG+e2POVfzklMVM8TnnzY3EpczsOtI2
ZdndgCk2lsJN3aFsNI/xfwUukcImTsBSs9HKQO+U1l3cLQhR4804bJwXPaTkk4wk
DwTW4XMrHeM+XyAf+c8mDfycpOBUc9Y=
-----END CERTIFICATE-----

求解！

**Comment by xxnet** [comment]
什么操作系统？
是手动导入吗？

手动导入，要先删除之前的GoAgent 相关证书。

2015-11-17 22:46 GMT+08:00 Liang XIAO <notifications@github.com>:
