### ISSUE TITLE
自定义DNS？

### ISSUE THREAD

**Issue by RWTighnari** [XX-net/XX-Net#13997]
请问可以自定义DNS吗？

**Comment by xxnet** [comment]
是自己选择DNS服务器，还是对特定的域名解析到特定的IP？
目前都不支持。

**Comment by RWTighnari** [comment]
未来有计划支持这两个功能吗？

**Comment by xxnet** [comment]
没有啊，太小众的需求了。
如果你特殊需要可以自己改代码，需要自己懂python
