### ISSUE TITLE
请添加代理支持，内网无法使用。

### ISSUE THREAD

**Issue by iiilii** [XX-net/XX-Net#14]

**Comment by xxnet** [comment]
是Socks4/Socks5 还是Http/https。

还有能否描述是什么公司还是学校，使用场景？

**Comment by iiilii** [comment]
内网http/https无法穿透，goagent原始版本是支持的。

**Comment by xxnet** [comment]
ok，稍等2周，我加上。

**Comment by xxnet** [comment]
代理功能加上了，支持HTTP/SOCKS4/SOCKS5，有问题请反馈

**Comment by iiilii** [comment]
**http代理功能正常，谢谢！** :smile:

> xxnet commented 16 days ago
> 代理功能加上了，支持HTTP/SOCKS4/SOCKS5，有问题请反馈
