### ISSUE TITLE
IOS端："XX-Net"Beta版已过期

### ISSUE THREAD

**Issue by tod111tod222** [XX-net/XX-Net#14008]
- 操作系统： IOS 16.7 
- 客户端版本号：  5.8.7 （最近提示升级5.9.0，每次都不成功）
- 问题现象：  不能打开XX-Net，提示："XX-Net"Beta版已过期。打开Testflight，要求输入邀请码。
- 日志文件：  打不开APP。

请问该如何解决。

**Comment by ssyy925** [comment]
碰到了同样的问题，求解决方案
![QQ图片20240213174758](https://github.com/XX-net/XX-Net/assets/157858119/6570c5c3-83a6-487c-8299-30e464793671)

**Comment by xxnet** [comment]
已经发新版了，重现按iOS下载链接安装就可以了
