### ISSUE TITLE
Pixel Android 14 卡读取 5.9.9 APK

### ISSUE THREAD

**Issue by superlucky8848** [XX-net/XX-Net#14011]
- 操作系统：  Android 14 (Pixel 4a) no root
- 客户端版本号：  APK包上写的5.9.9，APP信息页写的1.9.10
- 问题现象：  安装完成初次启动卡读取，应用只显示白色背景和旋转读取圈。是否初次启动需要外网环境？
- 日志文件：

**Comment by xxnet** [comment]
估计是apk包有bug无法启动，你可以先用这个版本：
https://github.com/XX-net/XX-Net/releases/tag/5.9.0

新版我尽快修复。

**Comment by xxnet** [comment]
修复了，还是原来的版本号，原来的下载地址
