### ISSUE TITLE
Iphone 版无法登入，显示Invalid token. App是最新版5.10.7

### ISSUE THREAD

**Issue by hadeschx** [XX-net/XX-Net#14038]
Iphone 版无法登入，显示Invalid token. App是最新版5.10.7，谢谢解答，之前是正常使用的

**Comment by entzug** [comment]
都有5.10.7了？
下载页面不是才5.9.10吗

**Comment by xxnet** [comment]
微信之类的软件传令牌经常丢失字符，换一种方式传到手机上
