### ISSUE TITLE
x-tunnel下的设置标签，服务器下拉除了自动以外，没有其他服务器，并且选择自动然后点击保存提示不行

### ISSUE THREAD

**Issue by rex54288** [XX-net/XX-Net#14035]
# 规则：
* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？
*是，搜索过，没有相关内容

* 是否以相关关键词搜索过类似 issues？
是，搜索过，没有相关内容

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

# 提问模版：
- 操作系统：  win10
- 客户端版本号：  5.9.10
- 问题现象：x-tunnel下的设置标签，服务器下拉除了自动以外，没有其他服务器，并且选择自动然后点击保存提示不行
大概是从2024年5月31号的22点多开始到第二天的00点40分之前，一直都是这样
![QQ图片20240531005110](https://github.com/XX-net/XX-Net/assets/34228393/1b57fe75-4424-4cd1-b5f9-f4a33c4b49b5)
然后在00点40分之后，出现过短暂的可以选择香港为服务器，过了几分钟又没了
用了快2年了吧，很好用，今天第一次出现这样的情况。还请麻烦帮忙看一下。
账号：cinderella.pain@gmail.com
- 日志文件：  
[log_files.zip](https://github.com/XX-net/XX-Net/files/15503217/log_files.zip)

# 日志文件获取方法：
访问 http://localhost:8085/?module=launcher&menu=about 或进入 [系统] -> [关于]
点 收集调试信息 后面的 [下载] 按钮。

**Comment by jiesniu** [comment]
some problem

**Comment by jiesniu** [comment]
same problm

**Comment by xxnet** [comment]
fixed
