### ISSUE TITLE
一键生成Issue被浏览器拦截弹出窗口

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1403]
建议除了弹出新窗口生成Issue之外，额外的在页面上显示一个URL，如果弹出窗口被拦截，也可以点击URL来打开。
前往Google论坛亦同。
或者这两个都用a标签来处理，地址动态生成，可以防止打不开的情况，样式处理成按钮即可。

**Comment by xxnet** [comment]
涂层方式，应该就不存在被拦截的情况了

在 2015年11月18日 下午12:19，Cat73 <notifications@github.com>写道：

**Comment by simonasd** [comment]
确实，我也遇到了这个问题，之前没有重视。这次一并改了。
