### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by kkhgsasas** [XX-net/XX-Net#14036]
xx-net 5.9.10 ,windows 11 23H2 从昨晚开始无法登录，显示602/登录没反应，account: gfghhf566@outlook.com

**Comment by kkhgsasas** [comment]
[log_files.zip](https://github.com/user-attachments/files/15544260/log_files.zip)

**Comment by kkhgsasas** [comment]
今天情況：连接服务器失败：session server login fail:602

**Comment by xxnet** [comment]
过了敏感时间就好了

**Comment by Druzan** [comment]
我的也是， 这几天一直不能用，每次都是602，怎么解决一下？
