### ISSUE TITLE
退款申请

### ISSUE THREAD

**Issue by alaywn** [XX-net/XX-Net#14094]
本人邮箱:alaywn@foxmail.com
于2024-12-23 17:56购买三个套餐，实际使用下来发现TG没法连接，寻求解决办法未果，故申请退款。发送邮件未见处理，故提交github。

**Comment by mendiudiu** [comment]
有没有人处理售后啊？

**Comment by mendiudiu** [comment]
这个有没有人处理啊？

**Comment by alaywn** [comment]
没人处理吗？

**Comment by xxnet** [comment]
邮件已经处理, 电报试试手动设置代理.
