### ISSUE TITLE
部署服务端的时候如果能同时设置密码就更好了

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#141]
现在的话似乎要自己手动去修改gae.py
加上个input能输入密码多爽的说- -

**Comment by xxnet** [comment]
密码可有可无，没有太大必要，没有什么需要保密的，反而增加出错的机会。
所以没有放界面上。

特别需要的，自己修改吧

在 2015年4月13日 下午4:50，Cat73 <notifications@github.com>写道：
