### ISSUE TITLE
扫描IP时连接数太大导致不能上网

### ISSUE THREAD

**Issue by wsxy162** [XX-net/XX-Net#1417]
默认的 最大扫描线程数 为50，但是在路由器中看到我的机器的连接数已经达到了上限1000，导致我不能正常上网。想问下这个 最大扫描线程数 是什么意思，又要怎么限定扫描IP时的连接数上限？

XX-Net Version 	2.6.2
Python Version 	2.7.10
Sys Platform 	x86_64, Linux-4.3.0-1-default-x86_64-with-SuSE-20151116-x86_64
OS System 	Linux
OS version 	#1 SMP PREEMPT Mon Nov 2 15:35:09 UTC 2015 (7b374a4)
OS release 	4.3.0-1-default
OS detail 	Dist:openSUSE ; Version:20151116; ID:x86_64

**Comment by panzer1313208** [comment]
你设置里面的最大扫描线程数是多少？50？

**Comment by wsxy162** [comment]
默认的设置50。

**Comment by panzer1313208** [comment]
什么牌子和型号的路由器？

**Comment by wsxy162** [comment]
房东的路由器，wayos系统的。是不是计算连接数的方法不一样？比如路由器的计算tcp连接的时间比xx-net的长？

**Comment by xxnet** [comment]
一般路由器的CPU慢很多，所以很多耗时都会比PC上高，导致计算tcp连接时间比pc上的长是正常现象

在 2015年11月20日 下午2:05，wsxy162 <notifications@github.com>写道：

**Comment by wsxy162** [comment]
我的网络连接是通过两级路由的，自己的路由器比较低端，但是wayos路由器和自己的路由器计算的连接数是一致的。现在开25条扫描线程，连接数在600+。理想状况下，是开50条扫描线程，连接数就多50条吗？

**Comment by xxnet** [comment]
tcp在完全关闭之前，可能也算入连接数，因为需要占用内核资源。
一个tcp扫描只有5秒，但是完全关闭可能是几分钟，所以连接数可能是扫描数的10倍，也是正常

在 2015年11月20日 下午2:33，wsxy162 <notifications@github.com>写道：

**Comment by wsxy162** [comment]
好吧，我就调低点线程。

**Comment by flybird821** [comment]
我也遇到同样的问题，同样也是用的两级路由。请问你调低之后问题解决了吗？

**Comment by wsxy162** [comment]
调成10了，IP数维持在2500左右。
