### ISSUE TITLE
Mac下pac的问题

### ISSUE THREAD

**Issue by xuhaoren2011** [XX-net/XX-Net#142]
Sys Platform    darwin
OS System   Darwin
OS version  Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
OS release  14.3.0
OS detail   Release:10.10.3; Version:('', '', '') Machine:x86_64
architecture    64bit
Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17
XX-Net Version  1.8.5
Launcher Version    1.3.0
GoAgent Version 3.1.48
Python Version  2.7.6

已设置开机自动启动。然而开机后pac总是不会自动工作，必须要先开启到全局模式再关掉，pac模式才正常。或是在系统设置里手动取消pac，apply后再重新启用，pac模式才正常。总之就是要先切换成别的模式（全局或无代理）再切回来才正常，但下一次重开机又要再搞一次。请问这是什么原因？

**Comment by xxnet** [comment]
要看看日志才行，请在刚开机后，pac模式无法工作时，把日志的内容贴上来分析



2015-04-13 17:34 GMT-04:00 xuhaoren2011 <notifications@github.com>:
