### ISSUE TITLE
连接VPN等操作后代理无法使用

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1422]
实际问题是使用网易UU加速器进行加速后，XX-Net必须重启才能用。
经过简单研究，大概是这种操作让本地监听的HTTP服务器失效了吧- -
希望能有个自动检测并重新监听的设计。

**Comment by Cat7373** [comment]
初步研究应该是simple_http_server.py里的HTTPServer里的socket失效的问题。

**Comment by xxnet** [comment]
用的人应该比较少吧，第一次听说，不知对翻墙有没有加速作用

simple_http_server.py里的HTTPServer里的socket失效，那么8085端口也无法访问是吧



2015-11-20 23:23 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
对 后台页面同样无法打开
以及我是用UU加速网游的。。。

**Comment by xxnet** [comment]
这种情况，在Wiki里加一条经验就好了吧，自动化检测成本有点高

在 2015年11月21日 下午3:50，Cat73 <notifications@github.com>写道：

**Comment by Cat7373** [comment]
其实Socket失效后accept会抛异常的- -
我来改改试试看- -
对Python不熟悉- -
Java里倒是常搞这类东东..

**Comment by xxnet** [comment]
好啊，你试试，python 比java简单

在 2015年11月21日 下午7:36，Cat73 <notifications@github.com>写道：

**Comment by Cat7373** [comment]
Nov 21 20:25:30 - [WARNING] socket(127.0.0.1:8087) accept fail(errno: 10022).
Nov 21 20:25:30 - [INFO] server 127.0.0.1:8087 restarted.
成功实现GAE部分的重启，后台还没有。

**Comment by xxnet** [comment]
赞

2015-11-21 20:28 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
后台好蛋疼- -
出现这种问题后打开控制台 控制台直接消失。。。

**Comment by Cat7373** [comment]
不能- - 我已经用文件搜索定位到了代码- -

**Comment by xxnet** [comment]
先打开cmd，在里面执行看看

**Comment by Cat7373** [comment]
照样消失0.0

**Comment by xxnet** [comment]
隐藏cmd窗口的代码只有一个地方：
  launcher/win_tray.py 105行
  ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(),
0)

 你把它注释掉看看

你点托盘图标时会调用一次

2015-11-21 21:07 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
感冒了... 状态不大好...
所以说为什么我不支持捕获了错误就不管了...
我的代码里捕获过的错误都会再输出一次...
SocketServer.py 291行...
捕获错误后直接return...

**Comment by Cat7373** [comment]
参考资料
https://docs.python.org/2/library/socket.html?highlight=accept#socket.error

Changed in version 2.6: socket.error is now a child class of IOError.
Python2.6已经将socket.error更新为IOError

**Comment by xxnet** [comment]
感冒了就先休息，喝几天水，不要太疲劳了，自然就好了

2015-11-21 22:31 GMT+08:00 Cat73 <notifications@github.com>:
