### ISSUE TITLE
Mac使用的流畅度不稳定

### ISSUE THREAD

**Issue by laozhu999** [XX-net/XX-Net#143]
由于GOAGENT在WINDOWS非常稳定，我没有使用xxnet, 而mac就只能使用xxnet， 问题是时同时不同，流畅度很不稳定，看了一下log， 很多fail， 估计还是ip的问题吧，还是想问 “如何加入个人ip？”

**Comment by xxnet** [comment]
请试试最新版本 1.8.6

有些参数在1.8.5就做调优了，采取保守策略，尽量稳定

在 2015年4月13日 下午8:51，laozhu999 <notifications@github.com>写道：

**Comment by laozhu999** [comment]
看720p有点累啊， window下的goagent 真的给力。4k也可以啊。
