### ISSUE TITLE
打开XX-NET后不翻墙网站打不开

### ISSUE THREAD

**Issue by zboyco** [XX-net/XX-Net#1431]
老大，你好。
      我打开XX-NET以后，设置取消全局代理，Chrome使用SwitchyOmega自动切换，刚开始正常，过一会之后，国内的网站（直接连接）全部打不开，不只是我打不开，家里局域网络内所有设备都不能打开国内网站了，但是我的电脑（开着XX-NET的电脑）还是能正常翻墙，翻墙的网站全部正常，然后我试了试把SwitchyOmega设置成全部使用代理上网，国内的网站也能访问了，就是必须要翻墙才能访问，局域网内其他设备依然不能上网。必须要把路由器重启，并且关掉XX-NET，然后才能正常访问国内的网站，再次打开XX-NET后，过一会又变成这种了。怎么回事呢？我记得第一天装上XX-NET的时候是正常的，没出现这种情况，用了两三天今天就这种了。
     XX-NET版本是2.6.2,和这个https://github.com/XX-net/XX-Net/issues/1352情况有点像，貌似比他还严重一些。

**Comment by xxnet** [comment]
从现象分析，怀疑是路由器的tcp连接数满了，而xx-net已经建好了几十个tcp，因此翻墙可以，而那些需要重新建立tcp的都不行。

实际xx-net保持的tcp数就几十个，但是tcp关闭后，为了保持路由，会持续几分钟到几十分钟，才会从路由器中删除。
如果路由器参数太保守，就会把链路映射表用完。

简单的策略，可以减少扫描线程数，比如5。
你的路由器是什么型号？如果可以换个好点的路由器试试

在 2015年11月21日 下午6:40，zboyco <notifications@github.com>写道：

**Comment by linhua55** [comment]
现象：只要打开XX-NET，不论SwitchyOmega是设置成自动切换还是全部使用代理上网，局域网内其他设备都不能上网。
分析：估计是打开XX-NET后，影响了路由器。减小扫描线程数试试。

**Comment by zboyco** [comment]
我的路由器是N3，是个小路由器，不过老大你说的这个情况我觉得也有可能，我试一试把扫描的线程数减小到5试试

**Comment by corykang** [comment]
同问啊，时常出现这问题，现在版本2.8.5，就是墙内网站统统上不去，客户端和墙外网站可以访问，困扰很久啦啊

**Comment by YuenJoshua** [comment]
现在解决了吗？我遇到同样的问题了。。修改线程数也不好使

**Comment by jzp820927** [comment]
请具体描述你的问题

**Comment by NuclearBlast** [comment]
目测跟路由器没有关系，同一局域网中其他设备都能正常上网，只有装了XX-NET的本机不翻墙就打不开网站

**Comment by jzp820927** [comment]
只有装了XX-NET的本机不翻墙就打不开网站，不太明白这句话是什么意思。是不是说，比如打开 XXNET 才能上网，XXNET 关了，就不能上网了？

**Comment by NuclearBlast** [comment]
是的，装了XXNET的电脑墙内墙外网站打不开，包括XXNET配置页面也打不开，但是开启XXNET代理可以上网，局域网内其他设备都可以正常上网，关闭XXNET后这种现象大概持续半个小时-一个小时自动消失

**Comment by NuclearBlast** [comment]
系统代理是指Switchy Sharp的代理设置吗？这个我一直是选择自动切换的，而且如果关闭XXNET我会全部改成直连，这个问题不是常见的，我很久没碰到过了，等下次再出现再给你提供更多细节吧

**Comment by jzp820927** [comment]
系统代理，简单点说，就是 IE 里面设置的代理，不是 Switchy Sharp 的代理设置
