### ISSUE TITLE
好像不能关闭cmd命令行窗口。goagent就可以关闭，希望有这个功能

### ISSUE THREAD

**Issue by weaming** [XX-net/XX-Net#144]

**Comment by blackangeldsf** [comment]
XX-NET只是调用了goanget的程序，我感觉不能关闭goagent的窗口吧。感觉关闭了也没必要，原来用goagent的时候不一直也是开着那个黑窗口么。

**Comment by Cat7373** [comment]
是可以关闭的
运行vbs后缀的启动文件即可
start.vbs（仅windows有效）

**Comment by DDelon** [comment]
GAE的proxy.ini 第四行 visible改成0

**Comment by weaming** [comment]
感谢 DDelon 的方法，可行，原装goagent我就改过，xxnet改了之后就不知怎么调出窗口了。还是喜欢不显示窗口。

**Comment by yjd** [comment]
我喜欢点下显示，再点不显示呵呵。偶尔看看状态。而不用开个标签打开配置页面。看日志。
