### ISSUE TITLE
2.7.0 linux 下不能启动

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#1446]
Nov 23 18:12:21 - [INFO] server 127.0.0.1:8087 started.
Nov 23 18:12:21 - [INFO] server 127.0.0.1:8086 started.
Nov 23 18:12:21 - [INFO] gae_proxy started
Nov 23 18:12:21 - [INFO] start gae_proxy time cost 445
Nov 23 18:12:21 - [INFO] begin to start web control
Nov 23 18:12:21 - [INFO] launcher web control started.
Nov 23 18:12:22 - [INFO] GAE CONNECT www.googleapis.com:443 
Nov 23 18:12:22 - [INFO] GAE CONNECT www.googleapis.com:443 
Nov 23 18:12:22 - [INFO] GAE CONNECT mtalk.google.com:5228 
Nov 23 18:12:22 - [DEBUG] GAE CONNECT POST https://www.googleapis.com/oauth2/v4/token
Nov 23 18:12:22 - [DEBUG] GAE CONNECT POST https://www.googleapis.com/oauth2/v4/token
Nov 23 18:12:22 - [INFO] GAE CONNECT accounts.google.com:443 
Nov 23 18:12:22 - [DEBUG] get ip:1.255.22.166 t:126
Nov 23 18:12:22 - [WARNING] parse request fail:)�

Nov 23 18:12:22 - [WARNING] unhandler cmd:None
[31740:31777:1123/181222:ERROR:connection_handler_impl.cc(395)] Received message of invalid type 84
Nov 23 18:12:22 - [DEBUG] get ip:1.255.22.250 t:133
Nov 23 18:12:22 - [DEBUG] GAE CONNECT POST https://accounts.google.com/ListAccounts?source=ChromiumBrowser&json=standard
Nov 23 18:12:22 - [DEBUG] get ip:175.28.1.153 t:160
Nov 23 18:12:22 - [DEBUG] get ip:118.98.106.71 t:168
Nov 23 18:12:22 - [DEBUG] create_ssl update ip:1.255.22.250 time:122
Nov 23 18:12:22 - [DEBUG] create_ssl update ip:175.28.1.153 time:98
Nov 23 18:12:22 - [DEBUG] create_ssl update ip:1.255.22.166 time:131
Nov 23 18:12:22 - [DEBUG] get ip:202.248.151.24 t:177
Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
./start.sh: line 10: 31665 Segmentation fault      (core dumped) python2 launcher/start.py
[user@host:XX-Net]$ [31740:31777:1123/181244:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -130
[user@hos:XX-Net]$ 
[user@hos:XX-Net]$ [31740:31740:1123/181257:ERROR:account_tracker.cc(357)] OnGetTokenFailure: Connection failed (-130).
[31740:31740:1123/181257:ERROR:account_tracker.cc(357)] OnGetTokenFailure: Connection failed (-130).
Fontconfig error: Cannot load default config file
[31740:31777:1123/181332:ERROR:connection_factory_impl.cc(367)] Failed to connect to MCS endpoint with error -130

**Comment by fletchere** [comment]
我把 2.6.2 的data文件夹复制到了 2.7.0，2.6.2没问题。

**Comment by xxnet** [comment]
怀疑是 launcher/start.py 里加的
----------------------------------------------------
threading.stack_size(64*1024)
----------------------------------------------------
你可以试试把它去掉，看看是否恢复正常。

如果回复正常，你再试试把这个数字改大到多少可以稳定工作。


另外把状态页贴出来看看


2015-11-23 18:19 GMT+08:00 fletchere <notifications@github.com>:

**Comment by fletchere** [comment]
@xxnet 试过很多参数，都不行，所以就没有多测试，反正删掉这行就可以。

**Comment by xxnet** [comment]
ok

在 2015年11月23日 下午6:39，fletchere <notifications@github.com>写道：

**Comment by xxnet** [comment]
把状态页发出来，看看是什么操作系统

在 2015年11月23日 下午9:57，Net XX <xxnet.dev@gmail.com>写道：

**Comment by fletchere** [comment]
@xxnet XX-Net Version	2.7.0
Python Version	2.7.10
Sys Platform	x86_64, Linux-4.2.5-1-ARCH-x86_64-with-glibc2.2.5
OS System	Linux
OS version	#1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015
OS release	4.2.5-1-ARCH
OS detail	Dist:; Version:; ID:
language	en_US
architecture	64bit,
Browser	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

**Comment by fletchere** [comment]
@xxnet 是arch linux最新版本。

**Comment by xxnet** [comment]
好的，我回头找个Arch 试试

2015-11-23 22:19 GMT+08:00 fletchere <notifications@github.com>:

**Comment by fletchere** [comment]
@xxnet 安装arch有个更轻松的脚本 github.com/helmuthdu/aui，如果嫌官方安装方法太麻烦的话，呵呵！

**Comment by GreatBigWhiteWorld** [comment]
确实是，命令行运行出现一个warning：
[WARNING] start module script not exist:/home/"myusername"/Apps/XX-Net-master/goagent/start.py

看了下，那个文件夹下确实没有start.py这个文件。

**Comment by fletchere** [comment]
这个问题，难道只有我一个人有吗？

**Comment by xxnet** [comment]
@fletchere
  已经发布2天，确实只有你报问题。

  Arch 还是比较小众，安装太麻烦，门槛自然就高，用户自然少。

2015-11-24 17:31 GMT+08:00 fletchere <notifications@github.com>:

**Comment by xxnet** [comment]
刚才看到第二个Arch 遇到问题的，改成 128*1024 就可以了，你试试这个参数

在 2015年11月24日 下午7:41，Net XX <xxnet.dev@gmail.com>写道：

**Comment by xxnet** [comment]
行不行给个反馈吧，下个版本可以放进去

2015-11-24 21:03 GMT+08:00 fletchere <notifications@github.com>:

**Comment by linhua55** [comment]
wait a minute

**Comment by GreatBigWhiteWorld** [comment]
我的升级到2.7.0也用不了啊。不过错误不太一样，可以启动，但是启动完ip num/good一直是0，0

用命令行启动显示一个warning

Nov 24 21:47:43 - [INFO] start XX-Net 2.7.0
Nov 24 21:47:43 - [DEBUG] start confirm_xxnet_exit
Nov 24 21:47:43 - [DEBUG] good, xxnet:8087 cleared!
Nov 24 21:47:43 - [DEBUG] good, xxnet:8085 clear!
Nov 24 21:47:43 - [DEBUG] finished confirm_xxnet_exit
Nov 24 21:47:43 - [INFO] load ip range file:/home/name/Apps/XX-Net-master/data/gae_proxy/ip_range.txt
Nov 24 21:47:43 - [INFO] load google ip_list num:3000, gws num:3000
Nov 24 21:47:43 - [INFO] SSL use version:TLSv1_2
Nov 24 21:47:43 - [DEBUG] ## GAEProxy set keep_running: True
Nov 24 21:47:43 - [INFO] ------------------------------------------------------
Nov 24 21:47:43 - [INFO] Python Version     : 2.7.9
Nov 24 21:47:43 - [INFO] OS                 : Dist:openSUSE ; Version:42.1; ID:x86_64
Nov 24 21:47:43 - [INFO] Listen Address     : 127.0.0.1:8087
Nov 24 21:47:43 - [INFO] GAE APPID          : 。。。
Nov 24 21:47:43 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Nov 24 21:47:43 - [INFO] ------------------------------------------------------
Nov 24 21:47:43 - [INFO] system cert exist
GoAgent XX-Net - GoAgent                                     C,,  
Nov 24 21:47:43 - [INFO] server 127.0.0.1:8087 started.
Nov 24 21:47:43 - [INFO] server 127.0.0.1:8086 started.
Nov 24 21:47:44 - [INFO] gae_proxy started
Nov 24 21:47:44 - [INFO] start gae_proxy time cost 265
Nov 24 21:47:44 - [WARNING] start module script not exist:/home/jake/Apps/XX-Net-master/goagent/start.py
Nov 24 21:47:44 - [INFO] start goagent time cost 0
Nov 24 21:47:44 - [INFO] begin to start web control
Nov 24 21:47:44 - [INFO] launcher web control started.

**Comment by CyrusYzGTt** [comment]
在 2015年11月24日 21:42, linhua55 写道:
>
> wait a minute
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1446#issuecomment-159270452>.
>
debian 8.2 amd64 运行正常，除了

XX-Net/php_proxy/local/proxy.py:91: UserWarning: libevent version
mismatch: system version is '2.0.21-stable' but this gevent is compiled
against '2.0.19-stable'
  __import__('gevent.monkey', fromlist=['.']).patch_all()

(process:4228): GLib-CRITICAL **: g_slice_set_config: assertion
'sys_page_size == 0' failed

**Comment by linhua55** [comment]
@xxnet 
Arch下改成128*1024 ，确实可以启动了，正常。

**Comment by xxnet** [comment]
@linhua55
  好的，我明天发一个新版修复

@GreatBigWhiteWorld
 你的是不是太老的版本升级的，重新下载一个版本试一下

@CyrusYzGTt
  你的gevent 版本问题，比较折腾，如果不是非常必须，不要去启用php_proxy

2015-11-24 21:56 GMT+08:00 linhua55 <notifications@github.com>:
