### ISSUE TITLE
挂机一天之后working appids一栏变空

### ISSUE THREAD

**Issue by thekingofcity** [XX-net/XX-Net#1447]
GAEProxy状态信息 

系统版本
Property
Value
XX-Net Version 2.5.5 
Python Version 2.7.9 
Sys Platform AMD64, Windows-2012Server-6.2.9200 
OS System Windows 
OS version 6.2.9200 
OS release 2012Server 
OS detail Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:272; ProductType:0 
language zh_CN 
architecture 32bit,WindowsPE 
Browser Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko 

设置
Property
Value
Proxy Listen 192.168.2.100:8087 
PAC URL http://192.168.2.100:8086/proxy.pac  
IPv6 0 
ip-connect-interval 8 

状态
Property
Value
Google IP num 2999 
100th IP handshake(ms) 1835 
connected link(帮助) 13,0 
scaning ip thread num 3 
block stat(帮助) OK 

Appid
Property
Value
working appids  
Out of Quota appids  
Not Exist appids 

working appids  显示为空
只有每次重启才会显示APPID

BTY 经常快到每日谷歌结算时就没有流量了 用公共APPID访问发现是上传流量满了 不知道怎么解决 没有挂任何已知用代理的应用程序 上个周末部署了一个新的APPID 也没有解决问题
日志页一直显示红色No usable appid left

感谢各位解答

**Comment by linhua55** [comment]
建议更新成稳定版，重新下载更新

**Comment by 1634814279** [comment]
原来几个星期内已经更新了 前段时间还是当前版本 我去试试

**Comment by Cat7373** [comment]
我都是25个APPID...

**Comment by 1634814279** [comment]
-----------问题描述：
更新到2.6.2一星期后 又出现同样问题 APPID消失 流量用尽
昨天都没怎么挂过代理 不可能耗尽流量的
Nov 29 10:28:27 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Nov 29 10:28:27 - [DEBUG] GAE_Exception 1 'no appid can use'

-----------诊断信息：
sys-platform: AMD64, Windows-2012Server-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 2012Server
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:272; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
xxnet-version: 2.6.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000,139
connected-link: 10,0
ip-connect-interval: 8
scan-ip-thread-num: 50
ip-handshake-10: 100
block-stat: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
不是流量耗尽，应该是appid丢失了，之前的版本有这种可能，最新版应该修复了。
你试试2.7.1吧

2015-11-29 10:30 GMT+08:00 1634814279 <notifications@github.com>:

**Comment by 1634814279** [comment]
好的 谢谢 已更新

**Comment by 1634814279** [comment]
-----------问题描述：
一星期后又出现同样问题 只有重启后才能解决问题
每隔一个星期就会丢失APPID

-----------诊断信息：
sys-platform: AMD64, Windows-2012Server-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 2012Server
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:272; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
xxnet-version: 2.7.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000,70
connected-link: 0,0
ip-connect-interval: 8
scan-ip-thread-num: 50
ip-handshake-10: 203
block-stat: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
ok，我回头再看看是不是哪里还有bug。

2015-12-08 18:44 GMT+08:00 1634814279 <notifications@github.com>:
