### ISSUE TITLE
能否汉化下托盘菜单呢？

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#145]
Windows下右下角的托盘菜单都是英文的。。。
多少给个选项能修改语言也好嘛- -
检测OS的语言自动设置就更好了

**Comment by xxnet** [comment]
试过中文，在win7下是乱码，就放弃了，有熟悉windows编程的帮忙搞下

在 2015年4月14日 上午12:20，Cat73 <notifications@github.com>写道：

**Comment by Cat7373** [comment]
为什么我自己改的就没事呢？
我自己改出来就是中文。。。
也没乱码
http://cat73.sinaapp.com/xx-net/1.jpg
http://cat73.sinaapp.com/xx-net/win_tray.py

**Comment by xxnet** [comment]
你把状态页贴出来看看，我这边win7显示乱码。

在 2015年4月14日 上午10:38，Cat73 <notifications@github.com>写道：

**Comment by xxnet** [comment]
怀疑是因为我用了英文版win7

在 2015年4月14日 下午10:03，Net XX <xxnet.dev@gmail.com>写道：

**Comment by Cat7373** [comment]
状态页是UTF-8
应该也不会受到系统语言的影响吧- -

**Comment by causlayer** [comment]
为何mac下只有5个选项，而windows却有6个呢

**Comment by xxnet** [comment]
window已经汉化了，Mac下还没有，Mac下的语言处理比较麻烦，慢慢来。
