### ISSUE TITLE
可以搞个项目主页

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1455]
https://github.com/Cat7373/remove-web-limits
github支持给每个项目设置项目主页，就如上面的项目。
可以用于引导安装等。
https://pages.github.com/

**Comment by yeahwu** [comment]
有点意思。

**Comment by xxnet** [comment]
独立的域名很容易被封吧

2015-11-24 12:48 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by Cat7373** [comment]
github.io是Github自己的东西- -
而且还带着https...

**Comment by xxnet** [comment]
前面的子域名，GFW可以直接过滤掉。

当然对墙外是有效的，也是不错的一个展示方式。

2015-11-24 19:37 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by yeahwu** [comment]
@xxnet 这东西一般人是用来搭建博客的，熟悉前端的也可以拿来做主页。因为支持md写法，做博客再合适不过。域名大抵就是下面这样子。
http://yeahwu.github.io/wu.

**Comment by xxnet** [comment]
很想写个英文版的主页，能否帮忙搞一个？

在 2015年11月24日 下午7:53，YeahWu <notifications@github.com>写道：

**Comment by yeahwu** [comment]
@xxnet 这东西我还没研究透捏，大大。再加上域名并没有带s，推广用，不合适吧。

**Comment by Cat7373** [comment]
https://yeahwu.github.io/wu/
谁说没有带s了..
@yeahwu

**Comment by yeahwu** [comment]
@Cat7373  好吧，女侠饶命，我错了！

**Comment by yeahwu** [comment]
@xxnet 下面几个项目是我收集的，可以作为主页模板参考，我其实是个菜鸟，不能帮上大大深感惶恐。
https://github.com/yeahwu/3-Jekyll
https://github.com/yeahwu/poole
https://github.com/yeahwu/jekyllthemes

**Comment by xxnet** [comment]
恩， 没事，有熟悉做主页的欢迎帮忙，项目需要更多人来出力协作，每个人都有自己的特长，尽自己的力量就好

在 2015年11月24日 下午8:15，YeahWu <notifications@github.com>写道：
