### ISSUE TITLE
在KDE plasma桌面环境 xx-net的状态栏不兼容

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [XX-net/XX-Net#1457]
现在KDE的版本5基本成标配了，最近升级到KDE 5 plasma后， xxnet的start.py漂浮成一个独立窗口了，貌似是无法嵌入到状态栏。之前kde4桌面都是正常工作的。

请问这个怎么解决？

**Comment by xxnet** [comment]
不同的窗口管理器需要逐个做适配，实在没有精力去搞，除非找到一个通用的解决方案。



在 2015年11月24日 下午1:26，GreatBigWhiteWorld <notifications@github.com>写道：

**Comment by GreatBigWhiteWorld** [comment]
@xxnet 可能是遇到了bug，这会儿图标又正常显示了。
