### ISSUE TITLE
求大神帮忙看看这几行代码什么意思

### ISSUE THREAD

**Issue by panzer1313208** [XX-net/XX-Net#1465]
![1b2ixh r ffd3_93yy3f](https://cloud.githubusercontent.com/assets/13449426/11366381/e52583c4-92e7-11e5-9bb4-aaae76198175.png)

**Comment by xxnet** [comment]
分段下载的日志，对视频或大文件下载时会启用这个特性

2015-11-24 20:14 GMT+08:00 panzer1313208 <notifications@github.com>:
