### ISSUE TITLE
cannot import module win32_proxy_manager 怎么回事呢

### ISSUE THREAD

**Issue by AsiaLi** [XX-net/XX-Net#1468]

**Comment by AsiaLi** [comment]
bug

**Comment by xxnet** [comment]
这个文件应该在python27/1.0/lib/win32 目录下的，你可以找找
会不会是下载不完整，重新下载一个试试

或者把详细日志贴上来

2015-11-25 9:34 GMT+08:00 limao <notifications@github.com>:

**Comment by AsiaLi** [comment]
果然是少了这个文件，现在好了。真奇怪什么时候丢失的
