### ISSUE TITLE
自动升级应该有校验机制

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1471]
比如每次更新版本的时候都用工具自动生成一个lst列表文件。
升级后自动验证，避免升级不完全的情况出现。

**Comment by xxnet** [comment]
恩，最理想情况下是PGP签名，不过发现实现非常复杂，暂时做不到。

目前已经简单处理了：下载后检查HTTP头返回的长度是否一致，解决GFW截断导致的问题。

但从老版本升级上来还是很可能会出现问题，只能在群里回答了。

发现升级系统很多坑，每次需要它的时候就出问题。

lst列表文件需要另外增加一个文件去校验，增加了发布的工作量。

在 2015年11月25日 下午12:39，Cat73 <notifications@github.com>写道：

**Comment by Cat7373** [comment]
表示常年关闭自动升级功能- -

**Comment by linhua55** [comment]
@xxnet
为什么需要PGP签名呢？简单的md5就可以了呀。只是为了完整性考虑，又不是防中间人。
升级和“安装器”可以做到一个的
1.先分平台下载lst列表文件。lst列表文件的第一行不妨就是此文件的md5值，让自己校验自己。
2.再根据lst文件下载所需的文件。

2015-11-25 13:03 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by xxnet** [comment]
PGP是考虑以后P2P 分发，哪天github被封了，就需要了。
md5 的方式，首先需要有一个信得过的提供方，墙都翻不了的时候，就无法访问任何可信的提供方时用。
目前确实没有需求，所以就简单做了，只要github还在就可以。

在 2015年11月25日 下午1:20，linhua55 <notifications@github.com>写道：

**Comment by xgqfrms** [comment]
great job！
