### ISSUE TITLE
求问关于ip的问题。

### ISSUE THREAD

**Issue by wan9wu** [XX-net/XX-Net#1483]
看说明XX-NET会自动测试ip的延时，然后优先连接低延时的ip地址，会把无法的连接的ip自动屏蔽。
那么问题来了，我这里上网需要过网关才能联网，有时候忘了过网关，一直开着电脑，XX-NET程序就会一直自动的测试连接，导致本来是可以连上的ip也被认为时无效的。现在我的ip数量一直是0，这种情况下应该怎么办呢？

**Comment by xxnet** [comment]
这种场景已经考虑到了，在删除ip之前，会进行简单的测试看网络是否完全不通。

你先扫点ip出来看看效果

在 2015年11月26日 下午2:39，wan9wu <notifications@github.com>写道：
