### ISSUE TITLE
No usable appid left, add new appid to continue use GAEProxy

### ISSUE THREAD

**Issue by barryljf** [XX-net/XX-Net#1489]
Nov 27 13:20:37 - [DEBUG] get ip:203.176.178.25 t:217
Nov 27 13:20:37 - [DEBUG] create_ssl update ip:1.255.22.211 time:156
Nov 27 13:20:37 - [DEBUG] get ip:203.176.178.22 t:219
Nov 27 13:20:37 - [DEBUG] get ip:203.176.178.5 t:220
Nov 27 13:20:37 - [DEBUG] get ip:203.176.178.32 t:223
Nov 27 13:20:38 - [DEBUG] get ip:203.176.178.21 t:225
Nov 27 13:20:38 - [DEBUG] get ip:203.176.178.47 t:225
Nov 27 13:20:38 - [DEBUG] create_ssl update ip:203.176.178.5 time:220
Nov 27 13:20:38 - [DEBUG] get ip:203.176.178.27 t:307
Nov 27 13:20:38 - [DEBUG] create_ssl update ip:203.176.178.22 time:342
Nov 27 13:20:38 - [DEBUG] create_ssl update ip:203.176.178.32 time:219
Nov 27 13:20:38 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Nov 27 13:20:38 - [ERROR] no appid can use
Nov 27 13:20:38 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Nov 27 13:20:38 - [ERROR] no appid can use
Nov 27 13:20:38 - [DEBUG] create_ssl update ip:203.176.178.27 time:317
Nov 27 13:20:38 - [DEBUG] create_ssl update ip:203.176.178.21 time:546
Nov 27 13:20:38 - [DEBUG] create_ssl update ip:203.176.178.47 time:424
Nov 27 13:20:39 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Nov 27 13:20:39 - [ERROR] no appid can use
Nov 27 13:20:40 - [DEBUG] create_ssl update ip:203.176.178.46 time:220
Nov 27 13:20:40 - [DEBUG] create_ssl update ip:203.176.178.25 time:227

状态

Property	Value
Google IP num	990
100th IP handshake(ms)	2440
connected link(帮助)	15,0
scaning ip thread num	50
block stat(帮助)	OK
Appid

Property	Value
working appids	
Out of Quota appids	
Not Exist appids	

我以前是可以用的，因为安装过wallproxy软件，不但wallproxy没有安装好，反而导致我的xx-net不能用了。我删除wallproxy后，重新安装xx-net也不行。部署服务端也部署不了，不知道怎么回事。谢谢！

**Comment by xyuanmu** [comment]
提示没有可用的appid，到这里添加你的appid：http://127.0.0.1:8085/?module=gae_proxy&menu=config
若不行，怀疑是ini配置文件出问题了，删掉 xx-net/data/gae_proxy 里的 config.ini重新配置下 xx-net。

**Comment by barryljf** [comment]
我添加了自己的appid后，提示：Not Exist appids栏里面，就有我自己添加的那些appid。

**Comment by xyuanmu** [comment]
你应该是部署过wallproxy，在浏览器输入：你的appid.appspot.com/_gh/ 看是否提示workss
如果没有重新上传一遍：http://127.0.0.1:8085/?module=gae_proxy&menu=deploy

**Comment by barryljf** [comment]
问题已经解决，谢谢！
