### ISSUE TITLE
XX-Net 部署appid时，同时作为当前工作appid，导致部署失败

### ISSUE THREAD

**Issue by siterkiso** [XX-net/XX-Net#149]
前提.10个ID都是RUNNING的状态.
开始部署.输入10个ID .邮箱 以及密码.
部署到第六个的时候 也停止了.等了很长时间一直卡在那里.也没说失败.
后来试了5个ID 部署..部署到第3个就停止了.一样的情况.
最后试了1个ID .成功了......

**Comment by xxnet** [comment]
注意部署时，appid不能同时作为工作appid使用

在 2015年4月14日 上午4:13，siterkiso <notifications@github.com>写道：

**Comment by siterkiso** [comment]
没有明白什么意思。不能同时作为工作ID。意思只能部署一个ID吗。

**Comment by xxnet** [comment]
意思是，如果你把某个appid设置为当前GoAgent的appid，同时通过这个GoAgent作代理，去部署这个appid，那就有问题。
  因为部署过程中，Appid是会被暂停的，导致部署中断。

如果是一批的话，也就很可能碰上上面的情况

2015-04-14 8:19 GMT-04:00 siterkiso <notifications@github.com>:
