### ISSUE TITLE
传一份good ip，感觉谷歌要回归了。

### ISSUE THREAD

**Issue by lindongbin** [XX-net/XX-Net#1495]
状态
Property    Value
IP num/good 3000,344
10th IP handshake(ms)   179

延迟越来越低，我是开了10线程，在办公室电脑上没关机过，扫几个月了

https://drive.google.com/file/d/0ByTeFLs7RHJYbk1VOWE5ZzBHUlU/view?usp=sharing

**Comment by xyuanmu** [comment]
![489546](https://cloud.githubusercontent.com/assets/12442896/11454947/d614c536-967d-11e5-8c8d-6d13e0243962.png)
经过几次的IP择优，现在已经有不少好IP，顺便共享下前几天整理的有谷歌IP的IP段，[ip_range.txt](https://gist.githubusercontent.com/xyuanmu/80cbe8bbb9f926f10889/raw/ip_range.txt)

**Comment by fatfattree** [comment]
谢谢分享~

**Comment by lushilei** [comment]
谢谢分享

**Comment by skykain** [comment]
谢谢分享

**Comment by yuhan3617** [comment]
可以私发一份吗？不知道为什么总是下不了。
yuhan117@outlook.com
