### ISSUE TITLE
保存个人appid后working appid仍然为公共appid

### ISSUE THREAD

**Issue by qingshuizhiren** [XX-net/XX-Net#1497]
如题,服务端部署已完成.然后配置appid,显示成功保存,然而状态界面的working appid仍然为公共appid,youtube也显示是公共appid.

**Comment by Cat7373** [comment]
重启一下试试看?

**Comment by caorun0728** [comment]
非常感谢你的回复，昨天已经被删除重新部署，一切完美，非常好用，只不过有一个问题，我有两个谷歌账号，如何同时部署两个？还是只要把appid填写就默认启用？

**Comment by xyuanmu** [comment]
@caorun0728 部署玩，同时填写进去即可，如果有设置RC4密码必须一致。

**Comment by qingshuizhiren** [comment]
@Cat7373 重启了,还是如此.

**Comment by Cat7373** [comment]
检查下xxnet下的data/gae_proxy/config.ini的内容，看看里面有没有你的appid

**Comment by caorun0728** [comment]
可以自行添加嘛？

**Comment by panzer1313208** [comment]
@qingshuizhiren 目测应该是浏览器问题，用chrome，然后把xxnet的XX-Net-2.7.1\data\gae_proxy\good_ip复制出来，然后删掉data文件夹，重新安装XXNET，然后重新配置Appid，然后把XXNET关了，把good_ip粘贴到data\gae_proxy文件夹下。

**Comment by qingshuizhiren** [comment]
@panzer1313208 多谢,已解决.不过我本来的就是chrome,所以不是很清楚是不是bug.
