### ISSUE TITLE
WebUI修改用户设置，和手动修改设置冲突

### ISSUE THREAD

**Issue by cxjava** [XX-net/XX-Net#150]
首先感谢作者这么活跃的更新这个项目！非常感谢！

在使用的时候发现不能正常的保存appid，如果在config.ini里面手动配置了，那么在web页面不能显示出来，如果这个时候在web页面点击保存，那么config.ini里面的password会被置空。

另外：

托盘的右键的翻译不准确，比如倒数第二个：reset GoAgent。如果能翻译成中文的就比较好了，这个相信应该不难，
这个托盘的基本属性和GoAgent有较大差别，比如双击是打开web的控制台，而GoAgent是打开console。建议作者修改这些操作行为和GoAgent类似，如果需要打开web控制台，可以在右键菜单里面添加一项即可，其他建议保存和GoAgent一样的行为。

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.8.5
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.9

**Comment by xxnet** [comment]
目前自动配置和手动配置，还没有很好的协调好。
 也许再增加一个手动配置文件，免得互相干扰。
 大家也可以一起想办法。

 暂时建议直接修改goagent/x.x.x/local/proxy.ini吧

在 2015年4月14日 上午5:24，cxjava <notifications@github.com>写道：

**Comment by yjd** [comment]
又有人跟我一样提，cmd窗口了-_-!!

**Comment by xxnet** [comment]
1.9.3引入一个新的机制：
 可以自己创建一个  data/goagent/manual.ini 
  把要改的参数，写到这个文件中，即不会受升级影响，也不会受Web_UI配置影响。
