### ISSUE TITLE
导出IP的时候是不是应该考虑加密呢？

### ISSUE THREAD

**Issue by laoshufeifei** [XX-net/XX-Net#1500]
导出IP的时候是不是应该考虑加密呢？
要不然岂不是很容易被封掉

**Comment by woaiwinnie2** [comment]
GFW想封自己开一个不就行了

**Comment by Cat7373** [comment]
这个没必要，Python很难真正实现加密，并且你的IP都是你自己扫出来的，也没有什么必要去加密。
以及加密也不会提升多少防封能力。
