### ISSUE TITLE
Connected Links 0,0 但却可以上网？？

### ISSUE THREAD

**Issue by thebestwayto** [XX-net/XX-Net#1501]
Total IP / Good IP	833,734
10th IP handshake(ms)	194
Connected Links (帮助)	0,0
Number of Threads Scaning IPs	50
Block Status (帮助)	OK
Nov 30 15:36:24 - [INFO] load ip range file:D:\XX-Net\data\gae_proxy\ip_range.txt
Nov 30 15:36:24 - [INFO] load google ip_list num:878, gws num:818
Nov 30 15:36:24 - [INFO] SSL use version:TLSv1
Nov 30 15:36:24 - [DEBUG] ## GAEProxy set keep_running: True
Nov 30 15:36:24 - [INFO] ------------------------------------------------------
Nov 30 15:36:24 - [INFO] Python Version : 2.7.9
Nov 30 15:36:24 - [INFO] Listen Address : 127.0.0.1:8087
Nov 30 15:36:24 - [INFO] GAE APPID : （此处省略）
Nov 30 15:36:24 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Nov 30 15:36:24 - [INFO] ------------------------------------------------------
Nov 30 15:36:24 - [INFO] server 127.0.0.1:8087 started.
Nov 30 15:36:24 - [INFO] server 127.0.0.1:8086 started.
Nov 30 15:36:44 - [INFO] scan_ip add ip:202.86.162.168 time:94
Nov 30 15:37:30 - [INFO] scan_ip add ip:66.102.12.100 time:779
Nov 30 15:37:54 - [INFO] scan_ip add ip:216.58.198.137 time:873
Nov 30 15:37:56 - [INFO] scan_ip add ip:67.218.93.181 time:702
Nov 30 15:38:36 - [INFO] scan_ip add ip:208.117.226.59 time:874
Nov 30 15:39:09 - [INFO] scan_ip add ip:85.187.222.27 time:875
Nov 30 15:39:46 - [INFO] scan_ip add ip:216.58.193.75 time:343
Nov 30 15:39:47 - [INFO] scan_ip add ip:173.194.55.184 time:437
Nov 30 15:40:17 - [INFO] scan_ip add ip:216.58.193.78 time:421
Nov 30 15:41:00 - [INFO] scan_ip add ip:173.194.53.244 time:510
Nov 30 15:41:10 - [DEBUG] GAEProxy web_control 127.0.0.1:6333 POST /config?cmd=get_config
Nov 30 15:41:21 - [INFO] scan_ip add ip:74.125.1.89 time:529
Nov 30 15:41:22 - [INFO] scan_ip add ip:180.188.250.24 time:815
Nov 30 15:41:25 - [DEBUG] GAEProxy web_control 127.0.0.1:6654 POST /config?cmd=get_config
Nov 30 15:41:31 - [INFO] scan_ip add ip:216.58.193.113 time:417
Nov 30 15:41:38 - [INFO] scan_ip add ip:180.188.250.48 time:740
Nov 30 15:41:47 - [INFO] scan_ip add ip:203.176.178.13 time:513
Nov 30 15:42:01 - [INFO] scan_ip add ip:173.194.132.199 time:603

**Comment by thebestwayto** [comment]
XX-Net Version	2.7.1

**Comment by xyuanmu** [comment]
没猜错的话，你没设置代理，至于外网可能是其他原因比如hosts

**Comment by thebestwayto** [comment]
不可能，我没改过hosts，代理也设置了

**Comment by thebestwayto** [comment]
ie是直接设置，chrome用的switchysharp，然而用两个上网都是这样子

**Comment by yeahwu** [comment]
嗯，这个屌！看来xx进化了。

**Comment by flame9468** [comment]
我也有这种情况

**Comment by xxnet** [comment]
看看GAE日志，是不是真的使用了GAE在翻墙？

2015-12-01 14:21 GMT+08:00 小光丨Tune丶 <notifications@github.com>:

**Comment by sun3596209** [comment]
Connected Links 这个参数的意思是什么？ 怎么表征网络状态的好坏？

**Comment by wenliyang** [comment]
LS提问前先去看Wiki
https://github.com/XX-net/XX-Net/wiki/GoAgent-Connection-status

**Comment by sun3596209** [comment]
@wenliyang 非常感谢， 做了伸手党了。

**Comment by thebestwayto** [comment]
@xxnet 
确实是用xx-net上网的，我已经确认过n遍了。
现在更新至2.7.3仍是同样问题
Dec 04 13:20:28 - [INFO] SSL use version:TLSv1
Dec 04 13:20:28 - [DEBUG] ## GAEProxy set keep_running: True
Dec 04 13:20:28 - [INFO] ------------------------------------------------------
Dec 04 13:20:28 - [INFO] Python Version : 2.7.9
Dec 04 13:20:28 - [INFO] Listen Address : 127.0.0.1:8087
Dec 04 13:20:28 - [INFO] GAE APPID : *****
Dec 04 13:20:28 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Dec 04 13:20:28 - [INFO] ------------------------------------------------------
Dec 04 13:20:28 - [INFO] server 127.0.0.1:8087 started.
Dec 04 13:20:28 - [INFO] server 127.0.0.1:8086 started.
Dec 04 13:20:30 - [INFO] PAC from:127.0.0.1:1144 GET /proxy.pac
Dec 04 13:20:35 - [INFO] PAC from:127.0.0.1:1266 GET /proxy.pac
Dec 04 13:20:35 - [INFO] PAC from:127.0.0.1:1267 GET /proxy.pac
Dec 04 13:20:41 - [INFO] PAC from:127.0.0.1:1372 GET /proxy.pac
Dec 04 13:20:41 - [INFO] PAC from:127.0.0.1:1373 GET /proxy.pac
Dec 04 13:20:42 - [INFO] PAC from:127.0.0.1:1375 GET /proxy.pac
Dec 04 13:20:45 - [INFO] PAC from:127.0.0.1:1375 GET /proxy.pac
Dec 04 13:20:58 - [INFO] PAC from:127.0.0.1:1375 GET /proxy.pac
Dec 04 13:21:08 - [INFO] PAC from:127.0.0.1:1807 GET /proxy.pac
Dec 04 13:26:40 - [INFO] PAC from:127.0.0.1:7807 GET /proxy.pac
Dec 04 13:26:41 - [INFO] PAC from:127.0.0.1:7807 GET /proxy.pac
Dec 04 13:27:30 - [INFO] PAC from:127.0.0.1:7807 GET /proxy.pac
Dec 04 13:27:35 - [INFO] PAC from:127.0.0.1:7807 GET /proxy.pac
Dec 04 13:27:45 - [INFO] PAC from:127.0.0.1:7807 GET /proxy.pac
Dec 04 13:28:22 - [INFO] scan_ip add ip:217.119.118.97 time:2736
Dec 04 13:28:22 - [INFO] remove_slowest_ip:61.91.18.136 handshake_time:3146, fails:8
Dec 04 13:29:45 - [INFO] scan_ip add ip:62.201.216.199 time:1575
Dec 04 13:29:45 - [INFO] remove_slowest_ip:61.91.18.143 handshake_time:3146, fails:8
Dec 04 13:30:28 - [INFO] PAC from:127.0.0.1:12059 GET /proxy.pac
Dec 04 13:30:28 - [INFO] PAC from:127.0.0.1:12060 GET /proxy.pac
Dec 04 13:30:28 - [WARNING] socket error:error(10054, 'An existing connection was forcibly closed by the remote host')
Dec 04 13:30:28 - [WARNING] socket error:error(10054, 'An existing connection was forcibly closed by the remote host')
Dec 04 13:31:48 - [INFO] PAC from:127.0.0.1:13508 GET /proxy.pac
Dec 04 13:31:56 - [INFO] PAC from:127.0.0.1:13702 GET /proxy.pac
Dec 04 13:32:00 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:26 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:26 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:26 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:26 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:27 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:27 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:27 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:27 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO]LOG_EXCEPT: PAC from:127.0.0.1:13770 GET /proxy.pac , Except:[Errno 9] Bad file descriptor
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:28 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac
Dec 04 13:32:44 - [INFO] PAC from:127.0.0.1:13770 GET /proxy.pac

**Comment by thebestwayto** [comment]
Total IP / Good IP	3000,326
10th IP handshake(ms)	95
Connected Links (帮助)	0,0
Number of Threads Scaning IPs	50
Block Status (帮助)	OK

**Comment by xxnet** [comment]
看日志只有pac的请求，而且频率高得不合理，反而没有翻墙的url请求。

你能访问twitter吗？试试不经过xx-net能不能访问。
中间观察GAE的日志。

另外建议你切换到GAE模式，不要用PAC模式对比。

xx-net内部设计，长时间没有翻墙请求，connected link 会降到0以节约资源。

2015-12-04 13:35 GMT+08:00 thebestwayto <notifications@github.com>:

**Comment by thebestwayto** [comment]
不经过xx-net 不能访问，此时日志没有任何新条目出现
GAE模式可访问，日志同样无变化（PAC from:127.0.0.1:13770 GET /proxy.pac 这句就不出现了）

**Comment by thebestwayto** [comment]
Total IP / Good IP	3000,341
10th IP handshake(ms)	95
Connected Links (帮助)	0,0
Number of Threads Scaning IPs	50
Block Status (帮助)	OK
XX-Net Version	2.7.3
Python Version	2.7.9
System Platform	AMD64, Windows-7-6.1.7601-SP1
OS System	Windows
OS Version	6.1.7601
OS Release	7
OS Detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Language	en_US
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36

**Comment by thebestwayto** [comment]
好吧、我知道问题了、刚刚查看了一下、发现运行了两个pythonw.exe 结束掉一个之后就回复正常了。
