### ISSUE TITLE
负的scan-ip-thread-num

### ISSUE THREAD

**Issue by benpigchu** [XX-net/XX-Net#1509]
如标题
-----------
诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
xxnet-version: 2.7.1
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3062,742
connected-link: 5,49
ip-connect-interval: 1000000000
scan-ip-thread-num: -50
ip-handshake-10: 600
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
GAE日志还在吗？

2015-12-01 18:51 GMT+08:00 Ben Pig Chu <notifications@github.com>:

**Comment by panzer1313208** [comment]
把xxnet删了，然后把浏览器换成chrome，然后重新解压XXNET，然后重新配置Appid，然后就正常了，不同的浏览器会对xxnet产生一些影响。

**Comment by panzer1313208** [comment]
甚至是出错，比如IP。

**Comment by xxnet** [comment]
2015-12-01 20:03 GMT+08:00 panzer1313208 <notifications@github.com>:

> 甚至是出错，比如IP。
>

有可以重现的规律吗？

**Comment by panzer1313208** [comment]
@xxnet 用IE浏览器的时候，你配置XXNET的Appid，你看看能配置上不。

**Comment by xxnet** [comment]
刚才测试了下，现象重现了。
不过对比日志和Chrome，发现是IE里的状态页会缓存上次的结果，而实际上appid已经更新了。
在IE里访问状态页面，按F5可以看到appid已经刷新了。

估计是XX-Net在返回状态页面时，需要明确告知浏览器这个页面的缓存控制策略。

2015-12-01 20:35 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet 你忽略了网吧的IE都是IE7或者IE8而不是IE11.

**Comment by xxnet** [comment]
老的IE不考虑支持了，太多特性有问题了，但是IE11能支持还是要支持。

当然还是推荐Chrome啦

2015-12-01 20:56 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet 对了，刚才我下载最新版的XXNET，不知道怎么回事配置Appid的时候显示发生未知错误

**Comment by panzer1313208** [comment]
Dec 01 21:07:10 - [ERROR] req_config_handler except:'ip_connect_interval'
Dec 01 21:07:10 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "C:\Users\����\Desktop\����\XX-Net-2.7.2\gae_proxy\local\web_control.py", line 492, in req_config_handler user_config.user_special.ip_connect_interval = int(self.postvars['ip_connect_interval'][0]) KeyError: 'ip_connect_interval' , Except:[Errno 9] Bad file descriptor
Dec 01 21:07:10 - [INFO] GAE 1876|193.51.224.186|94 t:6338 s:1674 hs:745 Spd:1673722 200 https://xxnet-update.appspot.com/update.json?uuid=73800e61-e5b9-44af-a91b-7610606d7930&version=2.7.2

**Comment by panzer1313208** [comment]
这是当时的日志。

**Comment by xxnet** [comment]
ok，应该是删除ui后的bug，我来处理

2015-12-01 21:07 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet 删除ui？指的是IP时间间隔和那个什么ms吗？

**Comment by xxnet** [comment]
是的，那些是比较老的设计了，目前已经没有必要了。

2015-12-02 18:08 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet OK,我会努力寻找BUG以及提出对xxnet有帮助的建议的！

**Comment by xxnet** [comment]
good！



2015-12-03 1:53 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by benpigchu** [comment]
版本更新后似乎已解决
