### ISSUE TITLE
ID都不存在是怎么回事

### ISSUE THREAD

**Issue by siterkiso** [XX-net/XX-Net#151]
Property 	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0
XX-Net Version	1.8.5
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	
Out of Quota appids	
Not Exist appids	xxxxxxxx10个ID
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2917
connected link	23
ip_connect_interval	10

**Comment by xxnet** [comment]
请把日志发出来分析

2015-04-14 9:22 GMT-04:00 siterkiso <notifications@github.com>:

**Comment by xxnet** [comment]
请确认这些appid都已经部署好了
