### ISSUE TITLE
经实践证明linux下这条命令是多余的,因为我压根就没安装上,但是xx跑得挺溜.

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1512]
ubuntu14.04,x86,火狐,下面第三个命令.
>ubuntu 下，需要安装
sudo apt-get install python-OpenSSL
sudo apt-get install libffi-dev
sudo pip install cryptography
sudo apt-get install -y python-gtk2

**Comment by yeahwu** [comment]
个人看法  python-OpenSSL 和 libffi-dev好像是ubuntu环境自带的.cryprography好像也是非必须安装的.
实际只安装gtk2,然后cd /    ./start.sh 就可以完美运行

**Comment by xxnet** [comment]
找到这个历史：

https://github.com/XX-net/XX-Net/issues/956

在 2015年12月2日 下午4:35，YeahWu <notifications@github.com>写道：

**Comment by yeahwu** [comment]
看来是历史遗留问题呀！哈哈

**Comment by youlv9966** [comment]
请问Ubuntu下怎么上传appid呐？web好像打不开…
