### ISSUE TITLE
youtube-dl下载问题

### ISSUE THREAD

**Issue by eta01** [XX-net/XX-Net#1513]
xx-net版本：2.7.3
用youtube-dl下载出现如下内容，之前没这问题，换别的视频也一样

D:\Downloads>"D:\Desktop\youtube-dl (1).exe" --proxy 127.0.0.1:8087 https://www.
youtube.com/watch?v=7atDQreame4
[youtube] 7atDQreame4: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SS
L: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

**Comment by linhua55** [comment]
youtube-dl --no-check-certificate --proxy 127.0.0.1:8087  "
https://www.youtube.com/watch?v=ARp8srHc3GA"
加入--no-check-certificate 选项

2015-12-02 15:50 GMT+08:00 eta01 <notifications@github.com>:

**Comment by eta01** [comment]
解决了，谢谢大神！

**Comment by laodaoduo** [comment]
$ youtube-dl -F https://www.youtube.com/watch?v=fLe_qO4AE-M
[youtube] fLe_qO4AE-M: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 65] No route to host> (caused by URLError(error(65, 'No route to host'),))

大神 指导下

**Comment by jzp820927** [comment]
youtube-dl --no-check-certificate --proxy 127.0.0.1:8087 https://www.youtube.com/watch?v=fLe_qO4AE-M

不用 -F

**Comment by laodaoduo** [comment]
这个方法 是要我开通什么代理服务吗

$ youtube-dl --no-check-certificate --proxy 127.0.0.1:8087 https://www.youtube.com/watch?v=fLe_qO4AE-M
[youtube] fLe_qO4AE-M: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 61] Connection refused> (caused by URLError(error(61, 'Connection refused'),))

**Comment by jzp820927** [comment]
直接下，肯定下不了啊，除非你在国外。

**Comment by laodaoduo** [comment]
我用的是蓝灯进行翻墙的 也不行吗

**Comment by jzp820927** [comment]
可以，如果是蓝灯，就下面的命令：
youtube-dl --no-check-certificate --proxy 127.0.0.1:8787 https://www.youtube.com/watch?v=fLe_qO4AE-M

**Comment by laodaoduo** [comment]
谢谢 这种方法可以了

**Comment by jzp820927** [comment]
就是嘛，只要参数正确，肯定不会有问题。

**Comment by thexueliang** [comment]
我用shadowsocks 也下不了 求解

**Comment by shawwokou123** [comment]
很不错
这个命令不用在人工选择video和audio。效率很高

2016-09-11 2:52 GMT+00:00 Will Liu <notifications@github.com>:

**Comment by jzp820927** [comment]
ss 的问题怎么跑这儿来问了

**Comment by lbjhzj** [comment]
请问用vpn，开全局模式，怎么还会出现No route to host的问题

**Comment by jzp820927** [comment]
先确保你的 VPN 可用，然后就直接下，不用设置代理
youtube-dl https://www.youtube.com/watch?v=fLe_qO4AE-M

**Comment by lbjhzj** [comment]
我刚刚用ipsec连接vpn可以使用了。但是用vpn客户端就不行，只能在chrome上看youtube，但是在终端里ping不通

**Comment by jzp820927** [comment]
那能不能下载呢？

**Comment by lbjhzj** [comment]
用ipsec连接vpn可以下载

**Comment by jzp820927** [comment]
可以下载就行了

**Comment by tisfeng** [comment]
使用了代理报下面这个玩意，递归深度？？ 哪位哥看看

youtube-dl --no-check-certificate --proxy 127.0.0.1:1086  'https://www.youtube.com/watch?v=qlfERBA8g9I'

 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 255, in __getattr__
    return getattr(self, attr)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 251, in __getattr__
    if attr[:12] == '_Request__r_':

RuntimeError: maximum recursion depth exceeded in cmp

**Comment by tisfeng** [comment]
还有一个。。。

> ERROR: Unable to download webpage:  (caused by BadStatusLine('\x05\x00\x05\x07\x00\x01',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
