### ISSUE TITLE
关于透明代理

### ISSUE THREAD

**Issue by koolca** [XX-net/XX-Net#1522]
在原版goagent 3.2.3中，有transport选项，开启后可支持透明代理（iptables）。xx-net何时加入该功能？
目前测试LOG：
Dec 3 21:07:06 - [INFO] GAE 16|61.238.203.11|14735 t:403 s:234 hs:56 302 http://www.google.com.hk/
Dec 3 21:07:06 - [WARNING] unhandler cmd:None
Dec 3 21:07:06 - [WARNING] unhandler cmd:None

**Comment by koolca** [comment]
我使用的方法是dnsmasq+iptables的方法，将google.com.hk解析到某个不用的ip，然后用iptables命令将此ip的连接转发到8087端口。貌似xx-net不识别，所以没有处理？

**Comment by xxnet** [comment]
是的，目前XX-Net 还没有加入这个特性，主要原因是需要导入证书，比较麻烦。
等解决这个问题后，会加入这个特性。

实现这个特性，就可以比较愉快的跑在OpenWrt上了。
希望春节前能实现这个目标，正在努力中。。。

在 2015年12月4日 下午2:31，koolca <notifications@github.com>写道：

**Comment by koolca** [comment]
谢谢xxnet回复。我现在是在R7000梅林固件上跑xx-net，工作正常。手动导入证书倒不是个问题，可惜普通代理模式下，手机终端的某些应用无法翻墙。

**Comment by xxnet** [comment]
是的，最重要的Google Play 无法使用，就无法安装app了。
解决的途径是需要一种通用的tcp透传方案，正在开发中

在 2015年12月4日 下午4:03，koolca <notifications@github.com>写道：

**Comment by linhua55** [comment]
@koolca
使用privoxy可以吗？
可参考
http://liberize.me/tech/raspberry-pi-transparent-proxy.html


在 2015年12月4日 下午4:14，Michael.X <notifications@github.com>写道：

**Comment by jiuxiaxixi** [comment]
现在加入了木有啊

**Comment by linhua55** [comment]
是 x_tunnel ，不过需要付费。  如果还是要用 原来的 ，在Android手机上使用 Xposed模块，理论上可以实现  “不用安装证书，并支持PAC代理”

   Google Play  下载安装App，调用的是 系统自带的下载器。 需要Android系统自带的下载器支持代理设置。
