### ISSUE TITLE
我部署的自己的appid，为什么不能看视频啊

### ISSUE THREAD

**Issue by rui401** [XX-net/XX-Net#1528]
“共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问”
今天第一次用，查了下好像说之前版本就已经解决了，为什么我这里还会出现？是不是因为我专案弄了两个就变成公共appid了么？

**Comment by wenliyang** [comment]
部署好你的appid后，修改设置，删除共用appid，只填你自己的appid进去

**Comment by rui401** [comment]
问题已解决，在date/gae_proxy 里添加了一个config.ini文件才解决，内容为
[gae]
appid = （替换）
password =
[proxy]
enable = 0
type = HTTP
host =
port =
user =
passwd =
[google_ip]
刚开始用并不知道这么多啊，希望以后在教程里能加入相关信息
