### ISSUE TITLE
可以不可以用电脑自己建立的热点分享翻墙通道？

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#1529]
电脑热点是用cmd指令 netsh wlan set hostednetwork 这个建立的热点分享（具体原理我并不懂，但是操作是这样操作的，http://jingyan.baidu.com/article/9f7e7ec0529ec16f281554ef.html）

请问这个热点可以用来分享电脑的翻墙给其他的设备吗？

**Comment by linhua55** [comment]
除了用这个指令，还得设置ICS。而ICS是NAT（网络地址转换）的一种实现方式。
可以的。
1、需要设置监听地址为0.0.0.0
2、客户设备所填服务器地址为电脑的无线网络地址（不是本地网络ip地址）
3、客户设备需要安装证书。

在 2015年12月4日 下午8:19，cdmask <notifications@github.com>写道：
