### ISSUE TITLE
新版Chrome(v42) 网址https旁有个打叉

### ISSUE THREAD

**Issue by cennong** [XX-net/XX-Net#153]
![qq 20150414224936](https://cloud.githubusercontent.com/assets/9492219/7139503/4564f41c-e2f9-11e4-912d-8a9ac282ef22.png)
为什么网址https旁有个打叉

**Comment by Cat7373** [comment]
因为你没导入证书
看图应该是Chrome
一般会自动导入
你打开后没重启过浏览器?
如果重启过还不行
请尝试手动导入证书

**Comment by Occhi14** [comment]
楼上Cat：
更新到42.0.2311.90 m (64-bit)，https全部有证书问题~

**Comment by Cat7373** [comment]
...
我的还是41.0.2272.118 m (64-bit)
刚刚打开关于一看
有更新
不知道是不是42版...

**Comment by Occhi14** [comment]
哇，你回复好快··什么情况··
那你试试看，稳定版的，我也是后半夜才看到更新的，更新过后，https就都失效了··

**Comment by Cat7373** [comment]
我更新完了 的确是42.0.2311.90 m (64-bit)
提示的是该网站使用的安全设置已过期
应该就是因为Goagent目前还在用TLS1.0的原因吧
如果能更新到TLS1.2应该就可以了
附图 http://cat73.sinaapp.com/xx-net/https.jpg
相关Issue https://github.com/XX-net/XX-Net/issues/154

**Comment by Occhi14** [comment]
Cat大师啊！我愿追随你！能否留下网络联系方式吖，QQ···微信什么的···

**Comment by xxnet** [comment]
找到这个信息：
https://support.servertastic.com/certificate-transparency/

解释是从2015年2月开始，Chrome启用公开证书验证。
所有公开有效的SSL证书，才会显示绿色。


GoAgent的证书是自己生成的，自然不会在公开证书列表中，所以显示叉叉。
但和证书错误又不一样，功能上还正常访问，只是显示一个红叉叉很不爽。

2015-04-14 19:36 GMT-04:00 朱雀 <notifications@github.com>:

**Comment by Occhi14** [comment]
辛苦啦，各位···

**Comment by chenjb7608** [comment]
没错！确实如此，看着有点不爽，呵呵……

**Comment by xxnet** [comment]
采用sha256编码，已经解决
请测试 1.8.11

**Comment by chenjb7608** [comment]
谢谢！您开发的XX-net真太牛X了！



chenjb7608@gmail.com
 
发件人： xxnet
发送时间： 2015-04-17 09:51
收件人： XX-net/XX-Net
抄送： chenjb7608
主题： Re: [XX-Net] 新版Chrome(v42) 网址https旁有个打叉 (#153)
采用sha256编码，已经解决
请测试 1.8.11
