### ISSUE TITLE
全局PAC代理能否设置使用自己的PAC?

### ISSUE THREAD

**Issue by swj1442291549** [XX-net/XX-Net#1536]

**Comment by swj1442291549** [comment]
是否可以导入SwitchyOmega中自定义的规则？

**Comment by sun3596209** [comment]
SwitchyOmega中添加的规则，应该只在chrome中有效

全局PAC需要用自己的规则

**Comment by swj1442291549** [comment]
那么全局pac中自己的规则如何自定义呢？能否有快捷的方式来和SwitchyOmega中添加的规则保持同步，毕竟自己定义的规则最适合自己。

**Comment by HUMORCE** [comment]
参考这里：
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by swj1442291549** [comment]
但是https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file 好像并没有说如何修改pac

**Comment by xxnet** [comment]
目前不能修改pac，目录下的pac会被自动更新。

自定义pac的想法已经有了，但还没有来得及实现，到时会是智能的代理中介。
暂时想自定义，建议使用SwitchyOmega，不过只对Chrome有效

2015-12-07 8:33 GMT+08:00 swj1442291549 <notifications@github.com>:

**Comment by ghostry** [comment]
@xxnet 我也想在pac里加自己的网址。现在实现自定义了吗

**Comment by jzp820927** [comment]
试试不就知道了

**Comment by AnyWAT** [comment]
浏览器扩展内可手动添加切换规则的AutoGAE（更新GAE PAC需启用Smart Router模块）。。。

![image](https://user-images.githubusercontent.com/37962734/54862066-c0087880-4d6f-11e9-9de9-7ff1d1bed124.png)
![image](https://user-images.githubusercontent.com/37962734/54862081-0cec4f00-4d70-11e9-826a-3e0f38726ec8.png)

**Comment by AnyWAT** [comment]
Chrome、FireFox 需编辑本地PAC文件才能添加切换规则的白名单PAC代理（需启用Smart Router模块）：
https://github.com/MatcherAny/whitelist.pac [下载到本地](https://raw.githubusercontent.com/MatcherAny/whitelist.pac/master/whitelist.pac)，编辑文件：改1080为8086，或添加自己的。。。
Chrome 浏览器扩展内创建PAC情景模式，PAC 网址：file:///盘符及目录/whitelist.pac
FireFox 内自动代理配置的 URL（PAC）：file:///盘符及目录/whitelist.pac
当然，还有常见的黑名单PAC代理：https://github.com/petronny/gfwlist2pac 同样得下载到本地，改1080为8086，或添加自己的。。。
