### ISSUE TITLE
能否支持TLS1.2呢

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#154]
如题 看着本地显示使用了过时的加密技术的提示很不爽- -
附图 http://cat73.sinaapp.com/xx-net/https.jpg
相关Issue https://github.com/XX-net/XX-Net/issues/153#issuecomment-93110239

**Comment by xxnet** [comment]
有考虑过，需要找支持TLS 1.2的 pyOpenSSL的版本，而且还要Windows/Mac/Linux三个平台。
折腾过2次，没有结果。

如果你能帮忙最好，而且二进制包要官方能够下载的，自己编译的容易被攻击有后门。



在 2015年4月14日 下午5:16，Cat73 <notifications@github.com>写道：
