### ISSUE TITLE
XX-Net怎样设置不让连某个网址？

### ISSUE THREAD

**Issue by neariver** [XX-net/XX-Net#1542]
如题，XX-Net内怎样设置不让连某个网址？例如不让连123.com，就像hosts设置127.0.0.1 123.com
这样的效果

**Comment by Cat7373** [comment]
在服务端文件上有个配置项，可以设置一下来实现这个效果。

**Comment by xyuanmu** [comment]
部署服务端之前修改 XX-Net\gae_proxy\server\gae gae.py，__hostsdeny__，修改完后再部署。

**Comment by neariver** [comment]
好像不行 是不是还要改什么？

__hostsdeny__ = (  已经加了 还是能上到

**Comment by xyuanmu** [comment]
加了网址，还要用自己的appid部署到服务端才会生效。

**Comment by neariver** [comment]
已经在用自己的appid，怎样部署到服务端？

**Comment by Cat7373** [comment]
直接重新部署一次即可
