### ISSUE TITLE
状态页的10th IP handshake实际显示的是第11个IP的时间

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1546]
如题(数组从0开始- -)

**Comment by yeahwu** [comment]
我就默默地看着你！:relaxed::relaxed:

**Comment by sun3596209** [comment]
激情四溢

**Comment by xyuanmu** [comment]
其实我也发现了，不过无所谓啦 :ghost:

**Comment by xxnet** [comment]
噢，数学没学好，我数学是体育老师教的

2015-12-08 10:12 GMT+08:00 xyuanmu <notifications@github.com>:

**Comment by yeahwu** [comment]
不要在意这些细节

**Comment by yeahwu** [comment]
不要在意这些细节，其实我感觉最好的版本是那种啥显示都没有，就一个大xx图标，然后还跑得飞快的版本，做为用户，只要点开xx图标就可以翻了，不需要关心什么id呀，ip呀，证书呀，插件呀。

**Comment by xxnet** [comment]
在 2015年12月8日 上午11:23，YeahWu <notifications@github.com>写道：

>
> 不要在意这些细节，其实我感觉最好的版本是那种啥显示都没有，就一个大xx图标，然后还跑得飞快的版本，做为用户，只要点开xx图标就可以翻了，不需要关心什么id呀，ip呀，证书呀，插件呀。
>
>
> I can't agree with you any more.

可以搞一个傻瓜的状态页：
   当前翻墙健康状态： 翻得很爽/爬得有点慢/爬不过去 之类的，然后把现在的状态页放到高级里面。

**Comment by yeahwu** [comment]
@xxnet  这是我喜欢的风格，比如说，前戏中，高潮中，早泄中，阳痿需要治疗……类似，:laughing::laughing:

**Comment by Cat7373** [comment]
喂不要在咱的Issue里说这么奇怪的东东啦！

**Comment by yeahwu** [comment]
哎，想当年俺是多么斯文的一个人，都是被你们祸害了。啥都不说了，继续装正经去吧。

**Comment by zhaipro** [comment]
我好像关注了一个贴吧。

**Comment by yeahwu** [comment]
贴吧，细节需求分得比较细，其实有些奇葩的问题，贴吧里都有答案，并不是没有可取之处。为什么很多人离不开百度？因为百度知道，贴吧，当年做得确实不错，有些问题还真得在里面找，比如我要下载新出的“疯狂的麦克斯”，知道里面可以搜到迅雷链。

**Comment by fuding** [comment]
又误进调情施工现场？。。。

**Comment by yeahwu** [comment]
这话说得，俺怪不好意思的。俺们这是相应裆的号召，团结友爱，联络感情！以后还是不到这里破坏你们一本正经的讨论了。打扰之处，望谅解！……额，其实打扰都打扰了，后面的都是屁话……

**Comment by simonasd** [comment]
楼上们真是够了。。。

话说回来，状态页是XX-Net的门面，所以还是一定要做好的~
