### ISSUE TITLE
需要治疗，x大

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1549]
如图
![xxx](https://cloud.githubusercontent.com/assets/13328328/11651813/9165eb2e-9dce-11e5-8772-d41f0f4cf7ad.JPG)

**Comment by xxnet** [comment]
好的

2015-12-08 17:10 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by xxnet** [comment]
具体是什么问题？

2015-12-08 17:49 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by yeahwu** [comment]
不好意思，在排查。稍候

Michael.X <notifications@github.com>于2015年12月8日 周二17:50写道：

**Comment by yeahwu** [comment]
谎报军情了，xx-net没有问题，浏览器的问题，新版浏览器又整了什么妖蛾子，插件丢失。正在攻克。

**Comment by xxnet** [comment]
ok

在 2015年12月9日 下午12:03，YeahWu <notifications@github.com>写道：

**Comment by yeahwu** [comment]
已攻克，chrome真鸡巴麻烦，又大，又丑的，又傲娇。下次改集成firefox了，省心点。
https://github.com/yeahwu/chrome-xx

**Comment by xxnet** [comment]
chrome 体验比较firefox 好

开发chrome的都是高大上的程序员，不觉得大，占用资源实在多

2015-12-10 11:41 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by yeahwu** [comment]
一直再用火狐，主要是火狐可以折腾脚本，用不惯chrome，比较了下chrome下的插件质量没有火狐的高，比如常用的adb。
因为为了这几个项目一直在折腾这两个浏览器，火狐提取后可以精简到80mb以内，chrome再怎么精简也有120mb以上，每次pull到github都费了老大的劲。
再就是插件集成的问题，由于chrome经常性更新，插件老是集成失败，经常要变换方法，火狐则简单得多。

2015-12-10 12:38 GMT+08:00 Michael.X <notifications@github.com>:
