### ISSUE TITLE
请在Launcher的Web控制端增加一个下载证书文件的链接

### ISSUE THREAD

**Issue by qnnnnez** [XX-net/XX-Net#1553]
这样导入证书会方便得多，特别对于一些移动设备，另外建议增强Web控制端的功能，比如增加重启XX-NET的功能，理由同上。

**Comment by xxnet** [comment]
1. 导入证书的链接已经有了，只需要放到web UI上。
2. 退出功能有了，可以把退出按钮改造成电源按钮：
  点击后，弹出浮层，是重启还是退出。

  python 重启自己，还是有点麻烦的，需要搞点小技巧，可能要先启动另一个进程，自己退出，再由另一个进程来启动xx-net

在 2015年12月8日 下午10:27，Wu Shuang <notifications@github.com>写道：

**Comment by panzer1313208** [comment]
![rjn 41jkd n g 4x8d yc](https://cloud.githubusercontent.com/assets/13449426/11680115/fb4ca484-9e90-11e5-8200-205108ea6deb.png)
@xxnet 你看看这个图标怎么样？是win10的。

**Comment by qnnnnez** [comment]
@xxnet 没有发现可以下载CA.crt的URL，8086端口似乎限制了只能获得proxy.pac。

**Comment by xxnet** [comment]
这个图标不错

在 2015年12月9日 下午4:22，panzer1313208 <notifications@github.com>写道：

**Comment by xxnet** [comment]
http://127.0.0.1:8085/module/gae_proxy/control/download_cert

在 2015年12月9日 下午7:38，Wu Shuang <notifications@github.com>写道：

**Comment by qnnnnez** [comment]
原来如此。谢谢了。
________________________________
发件人: Michael.X<mailto:notifications@github.com>
发送时间: ‎2015/‎12/‎9 22:59
收件人: XX-net/XX-Net<mailto:XX-Net@noreply.github.com>
抄送: Wu Shuang<mailto:qnnnnez@live.com>
主题: Re: [XX-Net] 请在Launcher的Web控制端增加一个下载证书文件的链接 (#1553)

http://127.0.0.1:8085/module/gae_proxy/control/download_cert

在 2015年12月9日 下午7:38，Wu Shuang <notifications@github.com>写道：

> @xxnet <https://github.com/xxnet>
> 没有发现可以下载CA.crt的URL，8086端口似乎限制了只能获得proxy.pac。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1553#issuecomment-163196848>.
>


---

**Comment by panzer1313208** [comment]
@xxnet 其实windows10还是不错的，毕竟新系统有点BUG也可以接受反正已经在开始修复了。

**Comment by xxnet** [comment]
win10 还卡声音吗？
  又段时间没有听到报告了

2015-12-09 23:35 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet 依旧卡声音。

**Comment by xxnet** [comment]
Win10 还是玩具系统，不适合高并发，不过大家居然也习惯了，好久不报问题，呵呵

2015-12-10 7:09 GMT+08:00 panzer1313208 <notifications@github.com>:
