### ISSUE TITLE
scaning ip thread num变负数

### ISSUE THREAD

**Issue by G-monitor** [XX-net/XX-Net#1559]
![image](https://cloud.githubusercontent.com/assets/11240579/11679572/e978e1f4-9e8c-11e5-91e5-efaec0f8960e.png)
我是在导入了
https://github.com/XX-net/XX-Net/issues/1495
提供的列表后，scaning ip thread num一直下降然后变成了负数
个人猜测是插♂入技巧不对导致的
PS：之后访问速度已慢成狗

补充：
quit之后重开就一直是0了
之前在设置里面线程开的是70，导入了之后从70下降到的-70

再补充：
Property	Value
XX-Net Version	2.6.2
Python Version	2.7.9
Sys Platform	AMD64, Windows-8-6.2.9200
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36

**Comment by xxnet** [comment]
肯定是扫描线程的计数有bug

你重新启动是否能恢复速度？

在 2015年12月9日 下午3:57，G-monitor <notifications@github.com>写道：

**Comment by G-monitor** [comment]
重新启动后扫描线程计数是0，访问网站的速度依旧非常感人
PS：目前已经重新解压覆盖重新扫描ip，正常使用了
PSPS：其实我是不是当时应该去任务管理器里面看pythonw.exe的线程数量

**Comment by xxnet** [comment]
线程数比较多，除了扫描线程，还有建立连接的线程数，不过还是可以参考的。

在 2015年12月9日 下午10:59，G-monitor <notifications@github.com>写道：

**Comment by panzer1313208** [comment]
@xxnet 大大啥时候发布新版本啊，扫描所有IP那个东西弄好了吗？

**Comment by G-monitor** [comment]
感觉是导入ip部分的问题。刚刚导入了几个ip之后扫描线程又变成0了，10th IP handshake(ms)是100
之前导入了之后也是这一项一直在整百数跳来跳去

**Comment by panzer1313208** [comment]
@G-monitor 这个版本貌似的确有BUG，@xxnet 大大你还记得上次我也反映过局域网代理设置之后，IP和线程都会变成0么？

**Comment by xxnet** [comment]
有可能，设置页面刚好被改过，清理掉一些过时的选项，不知哪里出了问题

在 2015年12月10日 下午4:15，panzer1313208 <notifications@github.com>写道：

**Comment by benpigchu** [comment]
#1509 也是这个问题，但是因为我当时不知道为什么，之后又没有出现这个问题，所以close掉了
刚才在2.7.3试了一下，好像已经修复了
