### ISSUE TITLE
1.8.7部署失败，提示upload  fail(已解决)

### ISSUE THREAD

**Issue by fmalee** [XX-net/XX-Net#156]
Apr 15 09:14:37 - Application: xxxx
Apr 15 09:14:37 - Host: appengine.google.com
Apr 15 09:14:37 - Rolling back the update.
Apr 15 09:14:49 - upload  fail: < urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol >
Apr 15 09:14:49 - Retry again.

一直这样的提示。
之前用的是1.8.4，状态页显示是1.8.3.
1.8.4用自带APPID部署成功。
升级1.8.7后部署失败。GAE访问没有问题。

补充：
使用全局代理也一样。

**Comment by fmalee** [comment]
原来是XX-NET默认不通过GAE部署。
在配置的高级里勾选“通过GAE部署"就OK。

**Comment by fmalee** [comment]
可是问题来了，第一次安装XX-NET的时候，用的APPID是自带的。我似乎也没有改过配置，但是能部署自己的ID。
是不是XX-NET默认的配置就是通过GAE部署的？

**Comment by xxnet** [comment]
把部署时，goagent的日志贴上来分析

2015-04-14 21:18 GMT-04:00 远方 <notifications@github.com>:

**Comment by xxnet** [comment]
是的，这是为了提高部署成功率，现在XX-Net是通过GAE进行部署的

在 2015年4月14日 下午9:35，远方 <notifications@github.com>写道：

**Comment by Cat7373** [comment]
已解决的问题在评论框下面有关闭问题喵~
