### ISSUE TITLE
Decoding Unicode is not supported error after i18n was added on Windows 7

### ISSUE THREAD

**Issue by mikedchavez1010** [XX-net/XX-Net#1561]
After the i18n module was added, the following error occurred when running on  Windows 7 (English version).

Dec 09 08:36:18 - [DEBUG] 222.165.163.111 close:slowest 1303
unicode err:TypeError('decoding Unicode is not supported',)
line can't decode:Dec 09 08:28:33 - [INFO] OS: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0

Except stack:Traceback (most recent call last):
  File "C:\apps\python\XX-Net\gae_proxy\local\xlog.py", line 154, in get_new_lines
    jd[i] = unicode(line, errors='replace')
TypeError: decoding Unicode is not supported

No such error at all on Ubuntu (English version), 32 or 64bit.

**Comment by mikedchavez1010** [comment]
It didn't re-occur when I tested again on an English Windows 7. No occurrence on Chinese Windows 7 at all.

**Comment by xxnet** [comment]
#1548 another bug report about the i18n log.

2015-12-10 9:24 GMT+08:00 mike <notifications@github.com>:

**Comment by mikedchavez1010** [comment]
Tried many times on different PCs or VMs, and this bug just didn't re-occur on Windows 7 (English or Chinese version). For those who encounter this bug, please re-start XX-Net to see if it'll occur again. Please DO leave your report so as to fix it ASAP.

**Comment by mikedchavez1010** [comment]
This bug has not surfaced yet once more in the following tests and development. Please let me know if you notice it.

**Comment by xxnet** [comment]
This bug has fixed in trunk.

I search the error text and get the solution.

2015-12-16 18:54 GMT+08:00 mike <notifications@github.com>:

**Comment by mikedchavez1010** [comment]
Since xxnet fixed this bug already, this issue is closed.
