### ISSUE TITLE
可以自动更新了么？

### ISSUE THREAD

**Issue by KevinLeung007** [XX-net/XX-Net#157]
我用的1.85，为什么没有自动更新到1.87呢？

**Comment by KevinLeung007** [comment]
好像证书也不会自动导入，访问Google，会提示签名错误。手动导入证书就好了。

**Comment by xxnet** [comment]
升级是服务端设置的，一直都有小bug，就觉得不升级好。
没遇到问题就不要天天升级，都没有什么特别新的特性。

版本管理没有做好，先手动吧


在 2015年4月14日 下午10:53，KevinLeung007 <notifications@github.com>写道：
