### ISSUE TITLE
xx-net 打不开http://google.com http://www.google.com 但是能打开https://www.google.com

### ISSUE THREAD

**Issue by ChinaPython** [XX-net/XX-Net#1573]
系统版本
Property 	Value
XX-Net Version 	2.7.3
Python Version 	2.7.10
System Platform 	x86_64, Linux-4.2.0-19-generic-x86_64-with-Ubuntu-15.10-wily
OS System 	Linux
OS Version 	#23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015
OS Release 	4.2.0-19-generic
OS Detail 	Dist:Ubuntu; Version:15.10; ID:wily
Language 	zh_CN
Architecture 	64bit,ELF
Browser 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

系统版本心虚如上   只能打开https://www.google.com,其他向http://google.com http://www.google.com https://google.com 都打不开，求大牛给解决方案，设置通配符也不行，或许自己写的不对，求科普， 已添加在线规则，更新都正常

**Comment by linhua55** [comment]
为何还要用http？
访问  http://www.google.com 会自动跳转到https的。

2015-12-11 22:59 GMT+08:00 zhaohui751 <notifications@github.com>:

**Comment by zhaohui751** [comment]
关键选择是不跳转除了手动输入https带别名的google外  输入其他三个不跳转@linhua55

**Comment by linhua55** [comment]
经测试，这些地址会跳转

http://www.google.com

http://google.com

https://google.com

测试环境  Archlinux+Firefox42.0

2015-12-11 23:07 GMT+08:00 zhaohui751 <notifications@github.com>:

**Comment by zhaohui751** [comment]
多谢大神，外删除从新换个版本试一下，，@linhua55

**Comment by cc1024** [comment]
打开data\gae_proxy 里config.ini 

[hosts]
www.google.com = direct

direct改为gae

**Comment by linhua55** [comment]
已在2.9.3测试版中解决

cc1024 <notifications@github.com>于2016年3月8日周二 下午4:56写道：
