### ISSUE TITLE
如何配置让YOUTUBE走PHP?

### ISSUE THREAD

**Issue by HUMORCE** [XX-net/XX-Net#1574]
在开启自动切换的前提下，
记得GOAGENT可以通过修改配置文件的方式让YOUTUBE走PHP PROXY

**Comment by HUMORCE** [comment]
暂时通过在 Switchy 自动切换规则添加网址正则：
https?://www\.youtube\.com/watch

也不知道是不是全部流量都跑PHP

**Comment by simonasd** [comment]
这是想要绕过国家检测吗？
