### ISSUE TITLE
建议支持 HTTP/2

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#1581]
根据 https://code.google.com/p/googleappengine/issues/detail?id=11805 和 https://tools.keycdn.com/http2-test 测试，appspot已支持。
库支持方面未了解。方向性提议和备忘。

**Comment by xxnet** [comment]
HTTP/2有考虑过，之前分析是这样：
好处：
+ ssl keep alive 不需要消耗appid的请求次数资源
   不过目前这方面问题不大

+ 而HTTP/2 最大的特点是一个tcp可以同时传输多个请求，这个对体验上有帮助，比如一个好的ip就可以提供非常好的上网体验。
  当然下载大文件（1M以上）是没有差别的。
  目前ip资源很多，所以从数量上解决了体验的问题。
  如果某一天ip资源变得非常稀少，这个特性就会变得很有价值。


+ 节约HTTP头的压缩
  目前已经压缩过，所以差别不大。

开发成本：
  目前已经有python实现的http/2客户端库
  不过为了可控性，只能参考，要深度定制，才能发挥最大化的性能。
  所以需要的工作不是简单的接入一个库就ok了，否则意义不大。
  这就需要花很多时间去研究学习http/2的协议和实现。



考虑到这个功能并不能从根本上解决问题，算是锦上添花的特性，而目前还一直在为手机版本在研究，所以并没有把这个工作排上日程。


2015-12-13 9:10 GMT+08:00 YFdyh000 <notifications@github.com>:

**Comment by linhua55** [comment]
GAE IP server 并不完全支持http2。
在测试页面填入gws ip 测试即可。

**Comment by renyouguo** [comment]
之前说已经放弃手机版本了……
其实目前各种手机工具，不要自己买服务器的，基本都有不能国内外分流的问题，不知能否解决。

**Comment by xxnet** [comment]
解决手机翻墙，是一个大工程，需要同时解决多个问题。
国内外分流只是其中一个，还不是最难的。

现在使用手机的场景和时间比电脑要多很多，手机再困难也要想办法解决。


在 2015年12月13日 下午1:57，renyouguo <notifications@github.com>写道：

**Comment by sun3596209** [comment]
坐等手机版本，挺需要的

**Comment by kxmp** [comment]
有ip现在支持h2了 不仅h2呢 还有tls1.3了
不太清楚是不是所有ip都那样

哎呀 这要是有什么码神过来 完善一下xxnet来个h2那就太爽了!!
