### ISSUE TITLE
使用proxychains打开emacs时出错

### ISSUE THREAD

**Issue by angel1a** [XX-net/XX-Net#1587]
小白一枚。我按照教程将proxychains.conf里的`socks4 127.0.0.1 9050`注释掉并改为`socks5 127.0.0.1 8087`，运行`proxychains4 open /Applications/Emacs.app`后，emacs报错。

Dec 14 09:55:48 - [INFO] scan_ip add ip:103.11.30.56 time:400
Dec 14 09:56:59 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 09:57:14 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 09:57:29 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 09:57:44 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 10:00:07 - [INFO] scan_ip add ip:115.178.27.47 time:374
Dec 14 10:00:42 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 10:00:57 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 10:01:12 - [WARNING] socket error:error(32, 'Broken pipe')
Dec 14 10:01:14 - [INFO] scan_ip add ip:103.11.28.69 time:654
Dec 14 10:01:27 - [WARNING] socket error:error(41, 'Protocol wrong type for socket')
Dec 14 10:01:34 - [INFO] scan_ip add ip:1.255.22.145 time:611
Dec 14 10:01:43 - [INFO] scan_ip add ip:115.178.27.36 time:234

是我proxychain设置的有问题吗？多谢解答

**Comment by jzp820927** [comment]
socks5 127.0.0.1 8087

**Comment by angel1a** [comment]
@jzp820927 多谢！我改成 http 127.0.0.1 8087后，依然报错：

Dec 14 10:19:41 - [INFO] GAE CONNECT melpa.org:80
Dec 14 10:19:41 - [WARNING] unhandler cmd:None
Dec 14 10:19:41 - [INFO] GAE CONNECT orgmode.org:80
Dec 14 10:19:41 - [WARNING] unhandler cmd:None
Dec 14 10:19:41 - [INFO] GAE CONNECT elpa.gnu.org:80
Dec 14 10:19:41 - [DEBUG] get ip:202.248.248.248 t:195
Dec 14 10:19:41 - [DEBUG] get ip:115.178.27.36 t:234
Dec 14 10:19:41 - [WARNING] unhandler cmd:None
Dec 14 10:19:41 - [DEBUG] 198.70.69.68 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 218.189.25.172 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 193.90.147.43 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 31.55.163.140 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 103.11.28.175 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 31.55.163.230 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 203.176.178.29 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 85.187.222.49 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 208.117.245.137 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 203.176.178.17 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 202.122.146.9 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 189.215.200.24 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 62.201.216.209 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 62.201.216.198 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 1.255.22.146 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 103.11.28.79 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 188.21.9.202 close:alive_timeout
Dec 14 10:19:41 - [DEBUG] 202.86.162.152 close:alive_timeout
Dec 14 10:19:41 - [INFO] GAE CONNECT melpa.org:80
Dec 14 10:19:41 - [WARNING] unhandler cmd:None
Dec 14 10:19:41 - [DEBUG] get ip:202.248.248.228 t:319
Dec 14 10:19:41 - [DEBUG] get ip:115.178.27.47 t:374
Dec 14 10:19:42 - [DEBUG] get ip:103.11.30.56 t:400
Dec 14 10:19:42 - [DEBUG] get ip:202.248.248.226 t:424
Dec 14 10:19:42 - [DEBUG] get ip:31.55.184.101 t:427
Dec 14 10:19:42 - [DEBUG] get ip:103.11.30.41 t:451
Dec 14 10:19:42 - [DEBUG] get ip:202.248.248.246 t:455
Dec 14 10:19:42 - [DEBUG] create_ssl update ip:115.178.27.36 time:566
Dec 14 10:19:42 - [DEBUG] get ip:208.117.245.137 t:468
Dec 14 10:19:42 - [DEBUG] get ip:203.176.178.13 t:471
Dec 14 10:19:42 - [DEBUG] create_ssl update ip:115.178.27.47 time:635
Dec 14 10:19:42 - [DEBUG] create_ssl update ip:202.248.248.228 time:636
Dec 14 10:19:42 - [DEBUG] create_ssl update ip:202.248.248.226 time:428
Dec 14 10:19:43 - [DEBUG] create_ssl update ip:103.11.30.41 time:493
Dec 14 10:19:43 - [DEBUG] create_ssl update ip:202.248.248.246 time:349
Dec 14 10:19:43 - [DEBUG] create_ssl update ip:103.11.30.56 time:609
Dec 14 10:19:43 - [DEBUG] create_ssl update ip:31.55.184.101 time:606
Dec 14 10:19:43 - [DEBUG] create_ssl update ip:203.176.178.13 time:436
Dec 14 10:19:43 - [DEBUG] create_ssl update ip:208.117.245.137 time:465
Dec 14 10:19:45 - [DEBUG] 202.248.248.248 fail:timeout('timed out',)
Dec 14 10:20:03 - [INFO] scan_ip add ip:103.11.28.120 time:572
Dec 14 10:20:36 - [DEBUG] get ip:218.189.25.172 t:148
Dec 14 10:20:36 - [DEBUG] get ip:202.86.162.152 t:226
Dec 14 10:20:36 - [DEBUG] get ip:203.176.178.17 t:481
Dec 14 10:20:36 - [DEBUG] get ip:31.55.163.140 t:484
Dec 14 10:20:36 - [DEBUG] get ip:201.157.30.34 t:487
Dec 14 10:20:36 - [DEBUG] create_ssl update ip:218.189.25.172 time:342
Dec 14 10:20:36 - [DEBUG] get ip:31.55.163.230 t:488
Dec 14 10:20:37 - [DEBUG] get ip:203.176.178.47 t:492
Dec 14 10:20:37 - [DEBUG] create_ssl update ip:202.86.162.152 time:390
Dec 14 10:20:37 - [DEBUG] get ip:193.90.147.43 t:506
Dec 14 10:20:37 - [DEBUG] get ip:202.122.146.9 t:511
Dec 14 10:20:37 - [DEBUG] get ip:64.15.120.38 t:512
Dec 14 10:20:37 - [DEBUG] get ip:103.11.28.15 t:520
Dec 14 10:20:37 - [DEBUG] create_ssl update ip:31.55.163.140 time:755
Dec 14 10:20:37 - [DEBUG] create_ssl update ip:201.157.30.34 time:751
Dec 14 10:20:38 - [DEBUG] create_ssl update ip:31.55.163.230 time:750
Dec 14 10:20:38 - [DEBUG] create_ssl update ip:193.90.147.43 time:644
Dec 14 10:20:38 - [DEBUG] create_ssl update ip:202.122.146.9 time:613
Dec 14 10:20:38 - [DEBUG] create_ssl update ip:203.176.178.17 time:1423
Dec 14 10:20:38 - [DEBUG] create_ssl update ip:103.11.28.15 time:558
Dec 14 10:20:39 - [DEBUG] create_ssl update ip:203.176.178.47 time:1780
Dec 14 10:20:41 - [DEBUG] 64.15.120.38 fail:timeout('timed out',)
Dec 14 10:20:47 - [INFO] scan_ip add ip:189.215.200.43 time:625
Dec 14 10:21:00 - [INFO] scan_ip add ip:208.65.153.39 time:744
Dec 14 10:21:04 - [INFO] scan_ip add ip:103.11.28.237 time:639
Dec 14 10:21:16 - [INFO] scan_ip add ip:103.11.28.43 time:582
Dec 14 10:21:31 - [DEBUG] get ip:125.160.59.37 t:535
Dec 14 10:21:31 - [DEBUG] get ip:103.11.28.149 t:547
Dec 14 10:21:31 - [DEBUG] get ip:203.176.178.29 t:557
Dec 14 10:21:31 - [DEBUG] get ip:167.206.252.73 t:567
Dec 14 10:21:31 - [DEBUG] get ip:217.119.118.111 t:572
Dec 14 10:21:31 - [DEBUG] get ip:103.11.28.120 t:572
Dec 14 10:21:31 - [DEBUG] get ip:103.11.28.94 t:574
Dec 14 10:21:31 - [DEBUG] get ip:103.11.28.43 t:582
Dec 14 10:21:32 - [DEBUG] get ip:103.11.28.14 t:587
Dec 14 10:21:32 - [DEBUG] get ip:103.11.28.105 t:590
Dec 14 10:21:32 - [DEBUG] get ip:1.255.22.146 t:598
Dec 14 10:21:32 - [DEBUG] create_ssl update ip:203.176.178.29 time:623
Dec 14 10:21:32 - [DEBUG] create_ssl update ip:217.119.118.111 time:716
Dec 14 10:21:32 - [DEBUG] create_ssl update ip:103.11.28.120 time:706
Dec 14 10:21:32 - [DEBUG] create_ssl update ip:103.11.28.94 time:681
Dec 14 10:21:32 - [DEBUG] create_ssl update ip:103.11.28.14 time:582
Dec 14 10:21:32 - [DEBUG] create_ssl update ip:103.11.28.43 time:651
Dec 14 10:21:33 - [DEBUG] create_ssl update ip:1.255.22.146 time:563
Dec 14 10:21:33 - [DEBUG] create_ssl update ip:103.11.28.105 time:645
Dec 14 10:21:34 - [DEBUG] create_ssl update ip:103.11.28.149 time:2831
Dec 14 10:21:35 - [DEBUG] 167.206.252.73 fail:timeout('timed out',)
Dec 14 10:21:37 - [DEBUG] create_ssl update ip:125.160.59.37 time:4307
Dec 14 10:21:37 - [DEBUG] 125.160.59.37 fail:error(' certficate is none',)
Dec 14 10:21:37 - [INFO] scan_ip add ip:189.247.134.197 time:625

**Comment by angel1a** [comment]
改用ShadowsocksX实现终端代理
