### ISSUE TITLE
导入XX-Net\data\goagent\good_ip.txt到原版goagent 3.2.3

### ISSUE THREAD

**Issue by yjd** [XX-net/XX-Net#159]
这个文件是不是都是可用的ip地址？
我写了个程序把这里面ip排序合并写到goagent 323的
proxy.user.ini 
[iplist]
google_hk = 这里
--------
不过还是很多黄字就是。有时候快有时候慢。
因为goagent没Cookie丢状态问题。暂时先用下。

**Comment by xxnet** [comment]
XX-Net 对ip是动态调整的。

这些ip有时好，有时不好，对XX-Net影响不大。
对goagent可能就没有那么好效果，你可以先按握手时间排序，握手时间小的，连通率也高。

**Comment by yjd** [comment]
是的，我正则匹配完再排序下快的放前面。不过过一段时间很多ip又黄了。
还是等xx-net解决了cookie。就省事了。

**Comment by Cat7373** [comment]
http://cat73.sinaapp.com/xx-net/good_ips_sort.html
试试这个小工具吧 把good_ip.txt的内容复制进去 点Sort按钮即可

**Comment by yjd** [comment]
我还是接这里咨询下问题：
xx-net--IP导入导出--导出goagent格式，有没有把快的ip放前面排序好再显示出来。

xx-net自带了这个功能，大家都省事了。

**Comment by yfdyh000** [comment]
@yjd 目测已经排序，检查第一项和最后一项IP的值就知道了。
exportip 直接从 gws_ip_list 生成，定期运行的 try_sort_ip_by_handshake_time 会生成和排序这个列表。

**Comment by xxnet** [comment]
目前没有，这个可以加上的

在 2015年5月29日 上午11:08，yjd <notifications@github.com>写道：

**Comment by xxnet** [comment]
抱歉，前面回答有误，目前已经有排序的。

在 2015年5月29日 上午11:45，Net XX <xxnet.dev@gmail.com>写道：

**Comment by yjd** [comment]
明白了收到。建议如果不是太麻烦的话可以在导出那个界面加个输 proxy.user.ini 路径的框。然后保存直接就给写到proxy.user.ini文件。全省了^_^。太麻烦就先搁着。

**Comment by yfdyh000** [comment]
修改其他目录的文件不合适吧，得检查判断多种情况，稍有失误就可能损坏文件，而且输入路径也并不轻松。还是手动比较好。

在 2015年6月2日 下午6:47，yjd <notifications@github.com>写道：

> 明白了收到。建议如果不是太麻烦的话可以在导出那个界面加个输 proxy.user.ini
> 路径的框。然后保存直接就给写到proxy.user.ini文件。全省了^_^。太麻烦就先搁着。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/159#issuecomment-107913834>.
>



-- 
Best regards,
YFdyh000.

**Comment by xxnet** [comment]
同意yfdyh， 既然是想手动修改参数，就算高级用户了，自己用工具去编辑就好了，不用在UI上留太多高级操作，影响普通用户的理解。

在 2015年6月2日 下午7:08，YFdyh000 <notifications@github.com>写道：
