### ISSUE TITLE
xx果然是业界良心哪，换了一个linux版本，居然有图标了，反观goproxy真是太粗糙了。如图

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1593]
![sex](https://cloud.githubusercontent.com/assets/13328328/11787043/c7b13bd4-a2c4-11e5-9f1b-2de798582287.JPG)

**Comment by xxnet** [comment]
trunk 上已经有支持ubuntu 的图标了，你可以找个ubuntu试试，昨晚才pull上来的

**Comment by yeahwu** [comment]
嗯，这个你找对人了！电脑上ubuntu，mint，centos都有。等下我试试去。
Michael.X <notifications@github.com>于2015年12月15日 周二07:33写道：

**Comment by yeahwu** [comment]
刚试用了一下ubuntu上的最新版xx，并没有出现期待的xx图标，然后速度挺好的，暂时没有出现什么问题，然后下面是吐槽部分。
1: 状态栏怎么整成这样（指标正常。）后面还带一个大句号？这样真的漂亮吗？
2: 主页中英文界面，看得我有点凌乱了，建议搞个全篇英文，逼格立马提升一个档次，中文部分可以收藏在wiki里面嘛。你这搞个中西合璧，掉价呀！
以上观点主要出自鄙人的审美态度，不喜勿喷！
下面说正事，关于ubuntu的安装命令
>sudo apt-get install python-OpenSSL
sudo apt-get install libffi-dev
sudo pip install cryptography
sudo apt-get install -y python-gtk2

上面这几条命令建议改成下面这几条
>sudo apt-get install python-OpenSSL
sudo apt-get install libffi-dev
sudo apt-get install -y python-gtk2
sudo apt-get install  libnss3-tools 

最后上图
![xx](https://cloud.githubusercontent.com/assets/13328328/11802875/368d4474-a330-11e5-899e-438cf04f7c1d.png)

**Comment by xxnet** [comment]
ubuntu 下需要安装 pyappindicator
​
国际化刚搭建起来，很多细节需要慢慢完善，再加上重构ui，确实有很多细节需要慢慢打磨。

ubuntu 的安装命令你直接在wiki上改吧，有谁遇到问题再处理就好。

对系统的使用入门wiki，可以分出来Windows/Linux/Mac三个，放在一起有点乱，普通用户只关心他目前的系统。

**Comment by simonasd** [comment]
@xxnet 就像我上次说的，Github自带的Wiki太简陋了，访问不便，维护也不便。不知道有什么好的思路没？

**Comment by xxnet** [comment]
github.io可以申请一个，自己搭建一个项目主页，把wiki放上去，不过要预备着被GFW封了。
自己维护成本不低，我们精力有限，尽量找简单的方式。

目前github偷懒凑合着用，而且没有被封，出问题无法翻墙也可以查。

维护方面，github的wiki本身也是wiki，应该可以找个工具拉回来自己慢慢改，改好了再提交上去。
访问方面，可以通过一些markdown的技巧来改进，加上一些图片来优化展示效果。

在 2015年12月15日 下午2:36，simonasd <notifications@github.com>写道：

**Comment by xxnet** [comment]
ubuntu 的tray 需要安装：
sudo apt-get install python-appindicator

在 2015年12月15日 下午3:08，Net XX <xxnet.dev@gmail.com>写道：

**Comment by yeahwu** [comment]
x大老是一本正经的，这让我压力很大呀！那好吧，我也正经一把，
个人感觉简单点好，不要给自己那么大压力，要在快乐中开发，你不能满足所有人，比如说小白请外这走，然后给你别人的集成包链接。特殊需求的请往这走，然后给个别人的封装包链接。类似
而你只需要把主干维护好就好了。
然后又是个人感觉，github作为主页再合适不过了，至少适合国情。另外整个花哨的主页也可以嘛，比如ss主页就挺好。然后，经过多次验证发现，git上的io页加载经常404,然后流量大的话，可能有打不开的情况。
最近个人感觉比较多，下面又是一个，至于说wiki页，因为不是主页，算是二房吧，二房丑就丑点嘛，能干就行！翻译过来就是能看就行嘛！
最后，凡是都有个最后嘛
x大你的项目关注度挺高的，朝廷可能已经盯上了，匿名，匿名。
还有你那条命令安装不上，其实ubuntu上已经开了终端，有没有xx图标，无伤大雅。
最最后
x大，我能在你的issues上讲黄段吗？

**Comment by xxnet** [comment]
社区只要求尊重人，不许骂人，其他随便。

一本正经的感觉，还是受老外社区影响，语言尽量的清晰准确，没有歧义，效率高，就成这样了。
各种切口，各种行话，都不好理解，容易歧义。

黄段子随便，以后搞个黄色视频分享区也可以😁

在 2015年12月15日 下午4:01，YeahWu <notifications@github.com>写道：

**Comment by yeahwu** [comment]
黄色视频分享也行！流氓，x大流氓，流氓，流氓

**Comment by xxnet** [comment]
当初取名xx ，就是留着这一手，哈哈哈

2015-12-15 16:31 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by yeahwu** [comment]
好吧，待有空我就召集波多野结衣，苍井空，麻仓优，古田美慧，天海翼……她们。

**Comment by handleft** [comment]
1. 赵国朝廷可能已经盯上 XXNet 了…希望@xxnet 做好“反社工”的工作。

2. 再弄一个wiki？不必要。够用就行。

**Comment by xxnet** [comment]
ubuntu 的tray 需要安装：
sudo apt-get install python-appindicator

Ubuntu 14/15上测试通过

在 2015年12月15日 下午4:57，handleft <notifications@github.com>写道：

**Comment by yeahwu** [comment]
刚试用了下，专家模式，创意满满，很棒！就是下面是吐槽部分
1:小白页面，字体可以更炫一点嘛。
2:专家模式页面，专家模式切换键能不能放在页面上部分。另外“（已经翻墙成功)”这个括号能不能去掉，以空格代替。
xx要说了，整天不帮忙，就知道找茬！哎，能力有限哪，望见谅。脸红，上图，上图
![zj](https://cloud.githubusercontent.com/assets/13328328/11833498/3d631f52-a3fe-11e5-861d-f9790d875c5b.JPG)

**Comment by simonasd** [comment]
@yeahwu 本项目急需前端人员，哈哈。

现在还是草稿状态，离发布还有一段时间，会逐渐修改的。

**Comment by yeahwu** [comment]
@simonasd 口无遮拦惯了，不要较真。谢谢你的努力

**Comment by xxnet** [comment]
我是用户啊，看到4行字，太多了，眼睛不知道盯哪里好，2秒过去了，还是没找到重点，好吧，我来看看说了什么，哦，说可以了，可是还没那么好，还要干嘛来着。。。

精简！精简！再精简，傻瓜嘛，一秒就要看明白，你看那360多简单，健康指数80%，一键优化，其他我也看不懂，也不想看，我是电脑白痴。。。

感谢@simonasd，辛苦了，咱程序员往后撤，产品经理上，有没有360出来的，过来干活，啊没有产品经理啊，没有咱慢慢琢磨吧，啦啦啦。。。。

2015-12-16 15:34 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by simonasd** [comment]
@yeahwu  哈哈，客气，我也不是一本正经的人，但我现在是地下工作者，我伪装的身份是一个一本正经的程序员。（手动斜眼）

@xxnet 同求产品和前端。我本来想做成你说的那个样子，奈何能力不够，所以就先打这么个草稿了。

**Comment by simonasd** [comment]
说到简化，lantern是另一个极端。双击运行程序，右下角出现图标，WebUi出现，告诉你可以上网了，并给出Facebook、Google等网站的链接。

如果一切顺利，那就万事大吉。但如果出现一些小问题，用户完全摸不着头脑。我们可以不做得那么极端，平衡一下。:)

**Comment by xxnet** [comment]
努力简单化，如果喜欢折腾，也可以折腾，向小米学习，论一个程序猿如何修炼成产品经理的苦逼之路

在 2015年12月16日 下午4:03，simonasd <notifications@github.com>写道：

**Comment by yeahwu** [comment]
我是不是进错地了，这还是xx吗？笑出屎来鸟！
我来给几个词参考一下“正常”“不正常”，“正在爬”“墙太高爬不过去”“爬过去了，耶耶耶”，“前戏”“高潮”“痿了”
>我是用户啊，看到4行字，太多了，眼睛不知道盯哪里好，2秒过去了，还是没找到重点，好吧，我来看看说了什么，哦，说可以了，可是还没那么好，还要干嘛来着。。。 精简！精简！再精简，傻瓜嘛，一秒就要看明白，你看那360多简单，健康指数80%，一键优化，其他我也看不懂，也不想看，我是电脑白痴。。。 感谢@simonasd，辛苦了，咱程序员往后撤，产品经理上，有没有360出来的，过来干活，啊没有产品经理啊，没有咱慢慢琢磨吧，啦啦啦。。。。

**Comment by simonasd** [comment]
@xxnet 其实思路是有的，就是不好实现，做出来太丑。

* 如果一切正常并且已经建立通讯，显示第一种界面。（文案可以类似于：翻过长城，放眼世界）
    * 存在一些无伤大雅的小问题，于下方小字提示，每个问题给出“修复”按钮，并给出一个“一键修复所有” 的按钮。
    * 如果IP质量不好，网速不行，给出小提示，并告诉用户，给我们一点时间，一切都会好的。

* 如果尚未建立通讯，显示第二种界面
    * 如果没有别的毛病，只是IP问题，请用户等待。
    * 如果有其他问题，提示，给出“修复”按钮，并给出一个“一键修复所有” 的按钮。

**Comment by yeahwu** [comment]
第一界面尽量简洁，然后实在有问题，不能建立链接。可以把专家按钮，显示为“找问题”，点击后可以切换到第二界面找问题，修复。

**Comment by xxnet** [comment]
- 每次只给最重要的一条信息反馈

          让用户每次专注在解决一个问题。
          一切没有问题，也要给一条反馈。

   - 给出问题，并给出解决方案的指引，指引也是链接，点击后展开



对于可用ip，我们给一个简单的数：大于10个可用ip，即可认为ip足够。
小于10个ip，提示等待扫描更多ip。

这样可以做直线逻辑判断，实现就非常简单，对用户也容易明白和专注解决问题。


在 2015年12月16日 下午4:22，YeahWu <notifications@github.com>写道：

**Comment by simonasd** [comment]
我来试试产品经理的思路，装得不像请指正。

1. 用户首次打开这个程序，是抱着直接能上Google的心态的。因此当我们弹出WebUI时，首先应该告诉用户，当前是否能上。如果不能，告诉他们首次运行需要初始化，让他等待。此时要让用户有心理准备，别等了5分钟上不了就关闭走人。

2. 首次建立连接后，可以弹出桌面通知，恭喜用户，并鼓励他尝试。

3. 说到这里，有些设置吧，我们之前本着尊重用户选择的原则，都藏起来了。我认为我们大可以替他们包办，不然无法实现操作的最简化。
    * 启动后自动设置系统PAC代理，除非用户在设置中禁止，或浏览器中装有代理切换插件。（可能需要的：管理员权限检测，浏览器是否安装代理切换插件的检测）
    * 首次启动，提示用户是否加入开机启动项。此处需要说明这样做的好处。
    * （可选）首次启动，检测浏览器类型，如果是Chrome\Firefox，提示是否安装插件
        * 如果此时已经能翻墙，可以在用户点击“是”之后，打开应用商店页面。

4. 其他操作，诸如部署个人APPID，可以采用分步引导，循循善诱。但不要在第一时间就把这个问题抛给用户，会打击小白的积极性。可以在“公共APPID因为……有所限制”的界面、部署界面等处触发。

思路大概是这样了，各位，代码能否实现，就看你们的了。

**Comment by xxnet** [comment]
在 2015年12月16日 下午4:38，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 
>能否自动判断Chrome插件？

我们的产品经理并不知道这些技术细节，他只是怀抱梦想。
>应该可以吧，如果还没有找到足够ip，应该也没有什么影响才对。

如果pac没有问题的话，能直连的网站应该都是直连的，因此当XX-Net存在问题无法上网时，也只会影响那些原本就上不去的网站。
>我还不知道好不好用呢，你就让我加入开机启动，是不是等我觉得好用了再说？

要不这样吧，在用户首次能翻之后弹出这个建议。告诉他，保持XX在后台运行，将来会越翻越快。而且我们是开源软件，你大可以对我们放心。

**Comment by wal139491** [comment]
我在ubuntu执行./start.sh提示：
[ERROR] bind to 127.0.0.1:8086 fail

error: [Errno 98] 地址已在使用
是为什么啊

**Comment by jzp820927** [comment]
8086 端口被其他进程占用

**Comment by JasonQWJ** [comment]
以为进错了地方。。。。
