### ISSUE TITLE
扫了半天的ip了,还翻不过去,求指导

### ISSUE THREAD

**Issue by lixi0912** [XX-net/XX-Net#1596]
-----------
问题描述：
早上到现在一直在扫ip，之前google有一会时间可以使用，后来一直timeout了。不知道是哪里有问题～
-----------

诊断信息：
sys-platform: x86_64, Darwin-14.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
os-release: 14.5.0
os-detail: Release:10.10.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
xxnet-version: 2.7.3
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 338,334
connected-link: 0,1
scan-ip-thread-num: 50
ip-handshake-10: 331
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
状态正常，把日志发出来看

2015-12-15 13:10 GMT+08:00 lixi <notifications@github.com>:

**Comment by lixi0912** [comment]
> 状态正常，把日志发出来看
@xxnet 是代理日志么？
[log.txt](https://github.com/XX-net/XX-Net/files/62107/log.txt)

**Comment by lixi0912** [comment]
截取了片段
>
Dec 15 11:37:55 - [DEBUG] get ip:78.11.253.240 t:1154
Dec 15 11:37:56 - [DEBUG] create_ssl update ip:67.218.93.150 time:539
Dec 15 11:37:57 - [DEBUG] create_ssl update ip:103.11.28.207 time:563
Dec 15 11:37:57 - [DEBUG] create_ssl update ip:208.117.246.165 time:518
Dec 15 11:37:57 - [DEBUG] create_ssl update ip:31.55.163.138 time:846
Dec 15 11:37:57 - [DEBUG] create_ssl update ip:193.90.147.14 time:569
Dec 15 11:37:57 - [DEBUG] create_ssl update ip:78.11.253.240 time:614
Dec 15 11:37:58 - [DEBUG] 203.176.178.22 fail:timeout('timed out',)
Dec 15 11:37:58 - [DEBUG] report_connect_fail network fail
Dec 15 11:37:58 - [DEBUG] 64.15.123.46 fail:timeout('timed out',)
Dec 15 11:37:58 - [DEBUG] report_connect_fail network fail
Dec 15 11:37:58 - [DEBUG] 208.65.154.101 fail:timeout('timed out',)
Dec 15 11:37:58 - [DEBUG] report_connect_fail network fail
Dec 15 11:38:06 - [WARNING] no enough ip
Dec 15 11:38:07 - [WARNING] no enough ip
Dec 15 11:38:20 - [INFO] scan_ip add ip:78.11.253.226 time:457
Dec 15 11:38:22 - [INFO] scan_ip add ip:180.188.250.21 time:474
Dec 15 11:38:49 - [DEBUG] get ip:203.176.178.22 t:358
Dec 15 11:38:49 - [DEBUG] get ip:78.11.253.226 t:457
Dec 15 11:38:49 - [DEBUG] get ip:180.188.250.21 t:474
Dec 15 11:38:49 - [DEBUG] 103.11.28.92 close:slowest 2209
Dec 15 11:38:49 - [DEBUG] 182.176.130.59 close:slowest 1600
Dec 15 11:38:49 - [DEBUG] get ip:64.15.123.46 t:474
Dec 15 11:38:49 - [DEBUG] 182.176.130.35 close:slowest 1548
Dec 15 11:38:49 - [DEBUG] get ip:208.65.154.101 t:645
Dec 15 11:38:49 - [DEBUG] get ip:182.176.130.35 t:1548
Dec 15 11:38:50 - [DEBUG] get ip:182.176.130.59 t:1600
Dec 15 11:38:50 - [DEBUG] create_ssl update ip:180.188.250.21 time:499
Dec 15 11:38:51 - [DEBUG] 182.176.130.25 close:slowest 1545
Dec 15 11:38:52 - [DEBUG] create_ssl update ip:182.176.130.35 time:1803
Dec 15 11:38:53 - [DEBUG] 203.176.178.22 fail:timeout('timed out',)
Dec 15 11:38:53 - [DEBUG] report_connect_fail network fail
Dec 15 11:38:53 - [DEBUG] create_ssl update ip:182.176.130.59 time:1782
Dec 15 11:38:53 - [DEBUG] 78.11.253.226 fail:timeout('timed out',)
Dec 15 11:38:53 - [DEBUG] report_connect_fail network fail
Dec 15 11:38:53 - [DEBUG] 64.15.123.46 fail:timeout('timed out',)
Dec 15 11:38:53 - [DEBUG] report_connect_fail network fail
Dec 15 11:38:53 - [DEBUG] 208.65.154.101 fail:timeout('timed out',)
Dec 15 11:38:53 - [DEBUG] report_connect_fail network fail
Dec 15 11:39:05 - [INFO] scan_ip add ip:78.11.253.222 time:554
Dec 15 11:39:22 - [INFO] scan_ip add ip:1.255.22.166 time:107
Dec 15 11:39:23 - [INFO] scan_ip add ip:67.218.93.133 time:523
Dec 15 11:39:35 - [INFO] scan_ip add ip:1.255.22.203 time:143
Dec 15 11:39:43 - [DEBUG] 189.215.200.46 close:slowest 1106
Dec 15 11:39:45 - [DEBUG] 182.176.130.35 close:slowest 1803
Dec 15 11:39:46 - [DEBUG] 182.176.130.59 close:slowest 1782
Dec 15 11:39:52 - [INFO] scan_ip add ip:200.28.0.11 time:829
Dec 15 11:40:08 - [INFO] scan_ip add ip:118.98.106.71 time:312
Dec 15 11:40:24 - [INFO] scan_ip add ip:103.16.205.30 time:308
Dec 15 11:40:29 - [INFO] scan_ip add ip:193.90.147.54 time:593
Dec 15 11:40:42 - [INFO] scan_ip add ip:202.248.248.247 time:170
Dec 15 11:40:48 - [INFO] scan_ip add ip:103.11.28.215 time:555
Dec 15 11:41:39 - [INFO] scan_ip add ip:142.163.38.136 time:524
Dec 15 11:41:55 - [INFO] scan_ip add ip:103.11.28.150 time:668
Dec 15 11:42:03 - [INFO] scan_ip add ip:89.201.175.183 time:732
Dec 15 11:42:47 - [INFO] scan_ip add ip:67.218.93.144 time:3771
Dec 15 11:43:05 - [INFO] scan_ip add ip:144.131.80.138 time:523
Dec 15 11:43:14 - [INFO] scan_ip add ip:180.188.250.47 time:500
Dec 15 11:43:26 - [INFO] scan_ip add ip:67.218.93.153 time:687
Dec 15 11:43:26 - [INFO] scan_ip add ip:103.11.28.246 time:492
Dec 15 11:43:38 - [DEBUG] 217.119.118.68 keep alive fail, time:62
Dec 15 11:43:38 - [DEBUG] 217.119.118.68 close:HEAD
Dec 15 11:43:59 - [INFO] scan_ip add ip:213.153.32.68 time:649
Dec 15 11:44:07 - [INFO] scan_ip add ip:189.215.200.54 time:742
Dec 15 11:44:38 - [INFO] scan_ip add ip:217.119.118.76 time:2575
Dec 15 11:44:41 - [INFO] scan_ip add ip:180.188.250.23 time:533
Dec 15 11:44:52 - [DEBUG] 62.201.216.197 keep alive fail, time:62
Dec 15 11:44:52 - [DEBUG] 62.201.216.197 close:HEAD
Dec 15 11:44:57 - [INFO] scan_ip add ip:217.119.118.85 time:807
Dec 15 11:45:25 - [INFO] scan_ip add ip:67.218.93.172 time:488
Dec 15 11:46:02 - [INFO] scan_ip add ip:217.119.118.113 time:753
Dec 15 11:46:02 - [DEBUG] 203.176.178.34 keep alive fail, time:62
Dec 15 11:46:02 - [DEBUG] 203.176.178.34 close:HEAD
Dec 15 11:46:03 - [DEBUG] 106.103.1.71 keep alive fail, time:62
Dec 15 11:46:03 - [DEBUG] 106.103.1.71 close:HEAD
Dec 15 11:46:03 - [DEBUG] 202.248.151.50 keep alive fail, time:62
Dec 15 11:46:03 - [DEBUG] 202.248.151.50 close:HEAD
Dec 15 11:46:06 - [DEBUG] 78.11.253.225 keep alive fail, time:62
Dec 15 11:46:06 - [DEBUG] 78.11.253.225 close:HEAD
Dec 15 11:46:07 - [DEBUG] 85.187.222.27 keep alive fail, time:62
Dec 15 11:46:07 - [DEBUG] 193.90.147.22 keep alive fail, time:62
Dec 15 11:46:07 - [DEBUG] 64.15.120.223 keep alive fail, time:62
Dec 15 11:46:07 - [DEBUG] 103.11.28.5 keep alive fail, time:62
Dec 15 11:46:07 - [DEBUG] 85.187.222.27 close:HEAD
Dec 15 11:46:07 - [DEBUG] 103.11.28.79 keep alive fail, time:62
Dec 15 11:46:07 - [DEBUG] 193.90.147.22 close:HEAD
Dec 15 11:46:07 - [DEBUG] 64.15.120.223 close:HEAD
Dec 15 11:46:07 - [DEBUG] 103.11.28.5 close:HEAD
Dec 15 11:46:07 - [DEBUG] 103.11.28.79 close:HEAD
Dec 15 11:46:08 - [DEBUG] 67.218.93.186 keep alive fail, time:62
Dec 15 11:46:08 - [DEBUG] 67.218.93.186 close:HEAD
Dec 15 11:46:10 - [DEBUG] 67.218.93.181 keep alive fail, time:62
Dec 15 11:46:10 - [DEBUG] 67.218.93.181 close:HEAD
Dec 15 11:46:11 - [DEBUG] 67.218.93.185 keep alive fail, time:62
Dec 15 11:46:11 - [DEBUG] 103.11.28.94 keep alive fail, time:62
Dec 15 11:46:11 - [DEBUG] 67.218.93.185 close:HEAD
Dec 15 11:46:11 - [DEBUG] 103.11.28.94 close:HEAD
Dec 15 11:46:12 - [DEBUG] 189.215.200.35 keep alive fail, time:62
Dec 15 11:46:12 - [DEBUG] 189.215.200.35 close:HEAD
Dec 15 11:46:13 - [DEBUG] 208.65.154.222 keep alive fail, time:62
Dec 15 11:46:13 - [DEBUG] 1.255.22.174 keep alive fail, time:62
Dec 15 11:46:13 - [DEBUG] 208.65.154.222 close:HEAD
Dec 15 11:46:13 - [DEBUG] 1.255.22.174 close:HEAD
Dec 15 11:46:19 - [DEBUG] 69.79.200.69 keep alive fail, time:62
Dec 15 11:46:19 - [DEBUG] 69.79.200.69 close:HEAD
Dec 15 11:46:21 - [DEBUG] 78.11.253.234 keep alive fail, time:62
Dec 15 11:46:21 - [DEBUG] 78.11.253.234 close:HEAD
Dec 15 11:46:22 - [INFO] scan_ip add ip:115.254.97.9 time:629
Dec 15 11:46:22 - [DEBUG] 216.58.199.38 keep alive fail, time:62
Dec 15 11:46:22 - [DEBUG] 216.58.199.38 close:HEAD
Dec 15 11:46:22 - [DEBUG] 202.248.248.219 keep alive fail, time:62
Dec 15 11:46:22 - [DEBUG] 202.248.248.219 close:HEAD
Dec 15 11:46:22 - [INFO] scan_ip add ip:193.90.147.18 time:571
Dec 15 11:46:23 - [DEBUG] 202.86.162.173 keep alive fail, time:62
Dec 15 11:46:23 - [DEBUG] 202.86.162.173 close:HEAD
Dec 15 11:46:24 - [DEBUG] 78.11.253.224 keep alive fail, time:62
Dec 15 11:46:24 - [DEBUG] 78.11.253.224 close:HEAD
Dec 15 11:46:25 - [DEBUG] 62.201.216.210 keep alive fail, time:62
Dec 15 11:46:25 - [DEBUG] 62.201.216.210 close:HEAD
Dec 15 11:46:26 - [DEBUG] 1.255.22.250 keep alive fail, time:62
Dec 15 11:46:26 - [DEBUG] 1.255.22.250 close:HEAD
Dec 15 11:46:28 - [DEBUG] 103.11.28.204 keep alive fail, time:62
Dec 15 11:46:28 - [DEBUG] 103.11.28.204 close:HEAD
Dec 15 11:46:29 - [DEBUG] 103.11.28.251 keep alive fail, time:62
Dec 15 11:46:29 - [DEBUG] 103.11.28.251 close:HEAD
Dec 15 11:46:29 - [DEBUG] 193.90.147.12 keep alive fail, time:62
Dec 15 11:46:29 - [DEBUG] 193.90.147.12 close:HEAD
Dec 15 11:46:31 - [INFO] scan_ip add ip:103.11.28.170 time:2175
Dec 15 11:46:31 - [DEBUG] 202.248.248.249 keep alive fail, time:62
Dec 15 11:46:31 - [DEBUG] 202.248.248.249 close:HEAD
Dec 15 11:46:32 - [DEBUG] 62.201.216.199 keep alive fail, time:62
Dec 15 11:46:32 - [DEBUG] 103.11.28.181 keep alive fail, time:62
Dec 15 11:46:32 - [DEBUG] 62.201.216.199 close:HEAD
Dec 15 11:46:32 - [DEBUG] 103.11.28.181 close:HEAD
Dec 15 11:46:33 - [DEBUG] 201.157.30.30 keep alive fail, time:62
Dec 15 11:46:33 - [DEBUG] 201.157.30.30 close:HEAD
Dec 15 11:46:34 - [INFO] scan_ip add ip:193.90.147.52 time:4317
Dec 15 11:46:35 - [DEBUG] 203.176.178.47 keep alive fail, time:62
Dec 15 11:46:35 - [DEBUG] 203.176.178.47 close:HEAD
Dec 15 11:46:36 - [DEBUG] 109.95.77.107 keep alive fail, time:62
Dec 15 11:46:36 - [DEBUG] 109.95.77.107 close:HEAD
Dec 15 11:46:40 - [DEBUG] 67.218.93.154 keep alive fail, time:62
Dec 15 11:46:40 - [DEBUG] 67.218.93.154 close:HEAD
Dec 15 11:46:41 - [DEBUG] 203.176.178.38 keep alive fail, time:62
Dec 15 11:46:41 - [DEBUG] 203.176.178.38 close:HEAD
Dec 15 11:46:43 - [DEBUG] 203.176.178.52 keep alive fail, time:62
Dec 15 11:46:43 - [DEBUG] 203.176.178.52 close:HEAD
Dec 15 11:46:44 - [DEBUG] 31.55.166.139 keep alive fail, time:62
Dec 15 11:46:44 - [DEBUG] 31.55.166.139 close:HEAD
Dec 15 11:46:47 - [DEBUG] 193.90.147.45 keep alive fail, time:62
Dec 15 11:46:47 - [DEBUG] 193.90.147.45 close:HEAD
Dec 15 11:46:49 - [DEBUG] 217.119.118.109 keep alive fail, time:62
Dec 15 11:46:49 - [DEBUG] 217.119.118.109 close:HEAD
Dec 15 11:46:49 - [DEBUG] 67.218.93.150 keep alive fail, time:62
Dec 15 11:46:49 - [DEBUG] 67.218.93.150 close:HEAD
Dec 15 11:46:50 - [INFO] scan_ip add ip:182.176.130.5 time:1003
Dec 15 11:46:50 - [DEBUG] 78.11.253.240 keep alive fail, time:62
Dec 15 11:46:50 - [DEBUG] 193.90.147.14 keep alive fail, time:62
Dec 15 11:46:50 - [DEBUG] 78.11.253.240 close:HEAD
Dec 15 11:46:50 - [DEBUG] 31.55.163.138 keep alive fail, time:62
Dec 15 11:46:50 - [DEBUG] 208.117.246.165 keep alive fail, time:62
Dec 15 11:46:50 - [DEBUG] 103.11.28.207 keep alive fail, time:62
Dec 15 11:46:50 - [DEBUG] 193.90.147.14 close:HEAD
Dec 15 11:46:50 - [DEBUG] 31.55.163.138 close:HEAD
Dec 15 11:46:50 - [DEBUG] 208.117.246.165 close:HEAD
Dec 15 11:46:50 - [DEBUG] 103.11.28.207 close:HEAD
Dec 15 11:46:51 - [DEBUG] 180.188.250.21 keep alive fail, time:62
Dec 15 11:46:51 - [DEBUG] 180.188.250.21 close:HEAD
Dec 15 11:46:53 - [DEBUG] 202.86.162.167 keep alive fail, time:62
Dec 15 11:46:53 - [DEBUG] 202.86.162.167 close:HEAD

**Comment by xxnet** [comment]
是不是浏览器代理没有设置？
日志里没有请求日志

2015-12-15 13:53 GMT+08:00 lixi <notifications@github.com>:

**Comment by lixi0912** [comment]
@xxnet 日志里就看到这些～

**Comment by lixi0912** [comment]
@xxnet  确实是代理的问题 :sweat_smile:
