### ISSUE TITLE
【意见征集】如果XX-Net推出“自动诊断”功能……

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net#1597]
如果XX-Net推出“自动诊断”功能，你们希望它能检测（甚至自动修复）哪些问题呢？

-----
目前的设想是提供一个“自动诊断问题”的按钮，用户点击后，系统自动【按顺序】诊断如下内容：
* IPV4网络是否可用（如果用户启用了IPV6，改为判断IPV6是否可用）
    * 如果不可用，提示用户检查网络和防火墙设置
* 是否能与GAE服务器建立通讯
    * 如果无法联通：判断是否有可用IP
        * 如果没有可用IP，提示用户耐心等待扫描
    * 如果有可用IP，则检测是否存在可用的APPID。
* 是否导入证书（尚未实现）
    * 如果没有，自动导入证书，并再次检测。
        * 如果还是没有证书，提示用户手动导入，并给出教程
* 是否正确设置代理
    * （目前已经能检测系统代理设置，尚未实现浏览器代理设置检测）
    * （一种可能的检测方法：打开一个子页面访问Facebook或其他非Google系的墙外https链接，如果未收到对应的代理请求，说明代理设置不正确。）

----
其他提议一并整理如下：
* 日志加入多语言支持，当操作系统语言为中文时，日志输出也为中文。
* 将WebUI的首页设计为非常简洁的“傻瓜化”页面，只显示最核心的信息，当检测到异常时，显示警告。
* 用户开启IPV6时，检测IPV6是否可用，如不可用，提示用户。
* 用户打开部署页面时，检测网络，如果无法链接GAE服务器，则部署相关功能不可用，并提示用户。

相关讨论：#1580 、https://github.com/XX-net/XX-Net/pull/1579 、https://github.com/XX-net/XX-Net/pull/1556

**Comment by xxnet** [comment]
很棒！

补充一点，检查appid是否可用。
另外整个诊断的流程需要仔细梳理，比如代理先检测，再判断目前ipv4/ipv6的连通性和设置是否正确。

还有实现的架构，在python端实现，如何把结果呈现到web端，并保持灵活性和美观？
当然可以先搭一个简陋的架构，慢慢完善。

在 2015年12月15日 下午2:25，simonasd <notifications@github.com>写道：

**Comment by yeahwu** [comment]
默默地支持，x大又抢我楼了！

**Comment by Cat7373** [comment]
三楼路过@yeahwu

**Comment by yeahwu** [comment]
哥脸红鸟，:kissing_heart::kissing_heart::kissing_heart::kissing_heart:

**Comment by yeahwu** [comment]
其实我感觉重点只有三个，ip，id，代理设置，至于ipv6只是小众，可以wiki里提一下就好了，证书在chrome下根本就不是问题，用火狐的基本上也知道怎么导入证书。

**Comment by sun3596209** [comment]
能否加入对已扫描的IP的延迟检测，好用的IP留下，延迟太高的IP自动清除掉。

**Comment by Cat7373** [comment]
@sun3596209 
没有必要加这种功能吧...
XX-Net 会自动用延迟最低的 IP 进行连接。

**Comment by yeahwu** [comment]
@Cat7373 每到夜深人静的时候，我就……
ps（这个时候xx已经睡了，我们可以可劲地嗨）

**Comment by Cat7373** [comment]
@yeahwu 
神马鬼！

**Comment by yeahwu** [comment]
人家是人，真真切切的男淫，好吧。今天和xx商量好了，打算开辟成人专区，妹子可好！

**Comment by Cat7373** [comment]
@yeahwu 
。。。话说你多大？

**Comment by yeahwu** [comment]
怎么？有企图？（禁不住紧了一下衣领）

**Comment by Cat7373** [comment]
所以说成人专区是神马鬼。

**Comment by yeahwu** [comment]
好吧，讨论代码，交换翻墙经验的地方，汗汗

**Comment by Cat7373** [comment]
0.0
Issue不就是讨论代码交流经验的！

**Comment by yeahwu** [comment]
不是，这地方太正经了。每个人都是好好学生模样，搞得我这不学无术的都不好意思在这里面待。

**Comment by ztjal** [comment]
都不好，就我个人，我更希望程序功能越来越少，代码越来越短，WEBUI扔掉，只要手动配置INI就够了。

**Comment by Cat7373** [comment]
@ztjal 
你可以只手动开启 GAE 部分。

**Comment by yeahwu** [comment]
嗯，专注gae就好了，我也是这么想的，可以把php扔掉。至于webui，感觉还是简化，保留。

**Comment by Cat7373** [comment]
要知道不是每一个用户都能做复杂的配置，大部分用户还是希望在网页上点点点就搞定问题的。

**Comment by yeahwu** [comment]
@Cat7373 嗯， 娘子，教训得是。

**Comment by xxnet** [comment]
都起来嗨！让你们那么晚睡！

@ztjal <https://github.com/ztjal>
直接进入gae_proxy，运行python start.py 就可以不启动界面了，你自己爱怎么配置就怎么配置，直接修改proxy.ini。
如果你喜欢，直接修改py更好。

PHP部分是差不多可以扔掉，重新写一个也很容易。

能来到这里讨论的至少还有个git帐号，而90%的使用者都是小白，能找到这个工具已经很不错，不能要求更多。

2015-12-15 23:53 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by panzer1313208** [comment]
@simonasd 个人感觉【自动诊断】这个名字好像不太准确，不如叫【自我诊断】？或者其他名字？

**Comment by Cat7373** [comment]
起来了0.0

**Comment by panzer1313208** [comment]
@simonasd 还有一个问题就是，很多人是先配置之后才部署Appid，这个应该想办法解决一下。

**Comment by xxnet** [comment]
配置appid的时候，后台检查appid是否有效，有一个无效的，设置失败。

类似的，启用ipv6的时候，也检查一遍是否有效，无效就提示设置失败。

在 2015年12月16日 上午8:52，panzer1313208 <notifications@github.com>写道：

> @simonasd <https://github.com/simonasd>
> 还有一个问题就是，很多人是先配置之后才部署Appid，这个应该想办法解决一下。
>
>
>

**Comment by xxnet** [comment]
刚刚在状态页面的“连接状态”里，增加了当前网络可用性的判断，这个信息在诊断时可以作为第一个判断依据。

在 2015年12月16日 上午9:26，Net XX <xxnet.dev@gmail.com>写道：

> 配置appid的时候，后台检查appid是否有效，有一个无效的，设置失败。
>
> 类似的，启用ipv6的时候，也检查一遍是否有效，无效就提示设置失败。
>
> 在 2015年12月16日 上午8:52，panzer1313208 <notifications@github.com>写道：
>
>> @simonasd <https://github.com/simonasd>
>> 还有一个问题就是，很多人是先配置之后才部署Appid，这个应该想办法解决一下。
>>
>>
>>
>

**Comment by simonasd** [comment]
@xxnet 发现您的用词突然活跃起来了，大概是@yeahwu 小朋友的功劳。哈哈。

不过要说起来，严谨和一本正经的语言，在预防社工方面是有帮助的。朝廷握有所有人的短信和即时通讯的聊天记录，完全【有能力】对重点怀疑对象（程序员、经常连接github的上网者）进行语言风格的检索。这种方法曾经被用于分析红楼梦是否由两名作者写作。

顺带多说一点个人的推测，它们应该可以根据Github上的提交时间，和你的上网记录中连接Github的时间进行匹配（Github通讯内容是加密的，但通讯发生的时间是可以被记录的）。

**Comment by xxnet** [comment]
是的，所以我之前都是合并到一起提交代码的，不过为了团队协作，还是要正常的提交代码，否则无法协调。
不过还是要多注意安全，各位也一样要注意。

在 2015年12月16日 上午9:37，simonasd <notifications@github.com>写道：

**Comment by yeahwu** [comment]
上来看看有没有人说我坏话😄😄
1:X大起得比鸡早，
2:我真不是小盆友了，“老”朋友更合适点。没办法，语言风格就是这样呀！
3:本来没有3的，为了工整嘛。“自动诊断”“自我诊断”这tm不就是一个意思嘛！建议就叫“诊断”好了。又不是造成语。
最后，凡事都有个最后嘛
为什么说扔掉PHP？第一，效率低。第二，用哪个免费空间都缺德。
我的话讲完了！

Michael.X <notifications@github.com>于2015年12月16日 周三09:41写道：

**Comment by out-sider** [comment]
说到自动诊断，这样的问题不知道你们考虑过没有：
当笔记本关闭wifi断开网络的时候，xxnet是不是会把正在测试的所有IP当作不可用的？
当我通过改IPV6的DNS翻墙的时候，因为连接的是国外服务器，整个ping值会提高很多，也会有些不稳定，这个时候是不是对xxnet的扫描也有影响？

要不要出现异常情况（比如连着几个IP都不好用）的时候ping一些国内网站来修正影响呢？如果国内的也ping不通，基本可以认为是整个电脑没法上网了，这个时候就停止扫描（一方面防止误伤，一方面降低加大扫描线程带来的性能问题），改为定时检查网络情况

当然，这个功能主要是针对经常移动的笔记本而言的，对台式机可能反而会不好。所以估计还得改web UI

不过功能加太多也不好，就太臃肿了。谢谢各位开发者的努力～你们的工作很棒!

**Comment by panzer1313208** [comment]
提到DNS我想起来了，用哪个DNS最好啊？不管是翻墙还是不翻墙，用哪个DNS最好？

**Comment by out-sider** [comment]
我用的是ipv6to ipv4的DNS,正常使用是校园网环境，绑定DNS的

**Comment by panzer1313208** [comment]
有没有ipv4可以用的啊？

**Comment by xxnet** [comment]
在 2015年12月16日 上午11:33，out-sider <notifications@github.com>写道：

> 说到自动诊断，这样的问题不知道你们考虑过没有：
> 当笔记本关闭wifi断开网络的时候，xxnet是不是会把正在测试的所有IP当作不可用的？
> 当我通过改IPV6的DNS翻墙的时候，因为连接的是国外服务器，整个ping值会提高很多，也会有些不稳定，这个时候是不是对xxnet的扫描也有影响？
>
>
> 要不要出现异常情况（比如连着几个IP都不好用）的时候ping一些国内网站来修正影响呢？如果国内的也ping不通，基本可以认为是整个电脑没法上网了，这个时候就停止扫描（一方面防止误伤，一方面降低加大扫描线程带来的性能问题），改为定时检查网络情况
>
说的不错，目前 就是这么干的，这个逻辑只在报告ip失效时起保护作用。

**Comment by zjhzxhz** [comment]
@yeahwu 但是对于有自己的VPS的人并不缺德呀~
虽然PHP模块效率低, 但是在配置页是可以禁用的.

然而, 这货在Debian下并不能用! 所以已经被我打入冷宫好多年了.
BTW, 你们 楼上很嗨夜生活很丰富嘛!

**Comment by yeahwu** [comment]
@zjhzxhz goproxy的php模式在ubuntu，linuxmint上都能用。当然用的免费空间，速度不快，但是可以救急。

**Comment by zjhzxhz** [comment]
@yeahwu 
是的, 但是现在人在学校表示翻墙无压力呀(并没有启用IP v6).
话说方滨兴就是我们楼上实验室的呢 - -|||

**Comment by panzer1313208** [comment]
@zjhzxhz 6666，上去用刀捅死他。

**Comment by zjhzxhz** [comment]
@panzer1313208 哈哈哈哈哈哈……并不敢~

**Comment by simonasd** [comment]
@zjhzxhz 同学，请注意保护自己的身份信息

**Comment by zjhzxhz** [comment]
@simonasd 已删除 :) 提醒的是~
不过要查水表应该也不会查到我吧~

**Comment by simonasd** [comment]
@zjhzxhz 待查列表上的排名情况，要看你接下来在各大非法代码项目上的努力程度了。你这个帐号个人信息太丰富，建议换个专用的马甲。

**Comment by yeahwu** [comment]
@zjhzxhz 看你这名字，浙江，杭州，后面是名字xhz。哎呀，我艹，我太机智鸟。

**Comment by panzer1313208** [comment]
@xxnet 大大现在xxnet怎么样了？什么时候发2.7.4啊

**Comment by lele2010lele** [comment]
好热闹

**Comment by xxnet** [comment]
自动诊断功能已经修改了，在trunk上。
修改：
+ 当前网络可用性检查;
+ 只要有1个可用ip即认为可以使用;
+ 检查浏览器代理设置
+ 检查浏览器证书导入

另外PAC，第一次启动自动切换到PAC模式，之后修改代理模式，会记录下来，下次启动会切换到上次退出的状态。

大家多测测，希望今天能发2.8.0

2015-12-18 0:21 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by yeahwu** [comment]
好吧，俺来试试，不过俺是那种“不要在意这些细节”的人，可能测了后多半没问题。

**Comment by panzer1313208** [comment]
@xxnet 我还是有那个问题，不显示日志。

**Comment by panzer1313208** [comment]
@xxnet 刚打开的时候显示，过一段时间就不显示了。而且高级页面我感觉应该把状态和版本显示出来。

**Comment by yeahwu** [comment]
出报告了，测试了火狐，IE11，由于电脑里没有chrome所以没有测试。
1：IE全局PAC代理鸟问题没有，搞得我找不到茬很郁闷哪！
2：火狐刚开始的时候PAC代理没办法连上，搞得我高兴了一把，哈哈，XX你栽在我手里了。结果，两个问题排除，又是鸟问题没有。A：火狐每次都要重新导入证书，而且导入之前要把老证书删除。B：火狐PAC全局代理，需要到，选项-高级-网络-设置-自动代理配置项填入http://127.0.0.1:8086/proxy.pac 
火狐插件调用，没问题。
最后，两个小问题，扫ip真有点慢，我这个急性子，直接导入good ip测试。
还有xx你这个下载链，我这边要挂代理下载，否则下不了。
还有上面说不显示日志，没有的事。

**Comment by yeahwu** [comment]
还有补充一下，刚发现的，这个ip怎么越跑越少哇，本来刚导入的时候有几百个，跑到现在就几十个了。连接池搞不好就00了。

**Comment by xxnet** [comment]
@YeahWu
  火狐的问题，自动诊断能不能正确反馈？

第二，ip怎么越跑越少，你把这批ip跑一遍一键检测，看有效的有多少。
  ip丢失的问题，我这边也出现过，似乎比较严重。

在 2015年12月18日 下午2:30，YeahWu <notifications@github.com>写道：

**Comment by panzer1313208** [comment]
@yeahwu 要不我把图片放上来？

**Comment by panzer1313208** [comment]
日志空白的同时，右键XXNET退出，XXNET会卡死。只能从进程里面结束。

**Comment by xxnet** [comment]
@panzer 你用start.bat启动，看看有没有什么异常，另外把状态页贴出来，贴图也可以

在 2015年12月18日 下午2:41，panzer1313208 <notifications@github.com>写道：

**Comment by yeahwu** [comment]
@xxnet 1:能自动反馈，是浏览器代理设置的问题，赞一个。
2:导入220个ip，刚开始的时候有效ip100多个，运行10分钟降到25个。

**Comment by panzer1313208** [comment]
@xxnet 问题就是我用start.bat启动之后，就没这个问题了。

**Comment by yeahwu** [comment]
刚对比了现在这版和2.6.2版，一样的问题，目测是ip的问题。和程序应该没多大关系。

**Comment by yeahwu** [comment]
火狐下测试，这些都能正确反馈
>+当前网络可用性检查; + 只要有1个可用ip即认为可以使用; + 检查浏览器代理设置 + 检查浏览器证书导入 另外PAC，第一次启动自动切换到PAC模式，之后修改代理模式，会记录下来，下次启动会切换到上次退出的状态。

**Comment by xxnet** [comment]
​这个版本不显示IP总量，只显示有效的ip数，免得带来困扰。
你看到25个，应该是有效的，从检测ip页面，应该能看到IP总量

**Comment by yeahwu** [comment]
@xxnet  哈哈，叉烧狗可以旧貌换新颜了，点赞，点赞！

**Comment by xxnet** [comment]
没有问题晚点发版本，让更多人来测试

2015-12-18 15:40 GMT+08:00 YeahWu <notifications@github.com>:

**Comment by jzp820927** [comment]
激动人心啊，好久没发布新测试版了。。。

**Comment by fuding** [comment]
期待推送

**Comment by simonasd** [comment]
@xxnet 好赞~

好处就不多说了，说一下遇到的问题：
1. 访问推特的检测可能有些太过频繁了，降低点频率可以减少开销。（此外，虽然推特没问题，如果换个小公司，直接就被咱们ddos了）
2. 目前这个页面在Chrome上要占用130M的内存，不知道是否可以改善？
3. 当浏览器代理设置不正确时，证书检测会同时fail。

**Comment by Cat7373** [comment]
@simonasd 
不到70MB的路过

**Comment by xxnet** [comment]
在 2015年12月18日 下午5:10，simonasd <notifications@github.com>写道：

> @xxnet <https://github.com/xxnet> 好赞~
>
> 好处就不多说了，说一下遇到的问题：
> 1. 访问推特的检测可能有些太过频繁了，降低点频率可以减少开销。（此外，虽然推特没问题，如果换个小公司，直接就被咱们ddos了）
>
这个访问是在GAE_proxy 内部处理掉了，没有去掉真正的twitter，做人不可以那么过分的。

> 2. 目前这个页面在Chrome上要占用130M的内存，不知道是否可以改善？
>
刚才打开Chrome内置的资源管理器的，空白的页面是20M，XX-Net的状态页是33M。你从哪里看130M的？
从系统的资源管理器吗？你对比个空白的页面看看。

> 3. 当浏览器代理设置不正确时，证书检测会同时fail。
>
当浏览器代理设置不正确时，证书检测应该不显示更好，我改改。

**Comment by simonasd** [comment]
@xxnet @Cat7373 

>你从哪里看130M的？

我用的Chrome的管理器。空白页面14.5M，这个issue页面50M。

认真观察了一下，状态信息页刚打开时45M，每次通讯检测都会增加数K到数十K的内存占用。点击配置、高级等页面都会大幅增加内存占用。标签页在前台时，内存只增不减，标签页切换到后台时会进行一次内存释放，回到45M左右，此后随通讯检测小幅增长。

所以这样说起来，并没有什么问题。有问题也是Chrome的内存管理问题。

>这个访问是在GAE_proxy 内部处理掉了

Cool！我还没看代码，不知道这个情况。

**Comment by z102944** [comment]
第一次进来，什么都看不懂，不明觉利

**Comment by xxnet** [comment]
​2.8.9 已经基本实现，做个总结吧

+ 诊断本地网络是否可用
  一切的前提
+ 可用ip数
  为了简化逻辑，只要有一个可用ip就算可用。
  感觉还需要多点ip才会稳定些，不过会变复杂，继续观察反馈再改进。
+ 已建立连接数
  在没有请求30分钟后，就不再建立连接，此处会有误会，不过反馈不多。
  想好再改进，比如30分钟后，不keep alive，而新连接只保持在1-2个
+ 检查浏览器代理设置
  目前有误报bug，原因未查明。
  浏览器发出请求，python端已受到请求，但是浏览器不接受数据，刷新一下又好了。
  反馈好几个这样的情况了
+ 检查证书导入情况
  ok
+ 检查appid
  是否流量不足
    这以来后端检测，如果appid多（比如公共appid 百多个）有一定延迟（1分钟多）
    目前基本可用
  使用公共appid的，提示申请自己的appid


展示方式也改了2-3次，感谢所有参与和贡献代码的同仁！
从新用户反馈看，比以往少了很多低级的问题反馈，效果显著。

目前在浏览器代理检测上还需研究完善。
AppId的申请、部署还太过繁琐，增加了新手使用的门槛。


总的来说，这是一次伟大的合作和改进。
再次代表用户感谢所有参与的贡献者。


Michael.X

**Comment by jzp820927** [comment]
老用户，发来贺电，新版改进成功！

**Comment by fuding** [comment]
来赞一个

**Comment by ztjal** [comment]
建议，不，不是建议，是必需，将自动检查，改为手动，不要自动。

**Comment by Cat7373** [comment]
@ztjal 
刚刚把乱七八糟的数据汇总到自动检查里，又要改回来咩- -
理由呢- -

**Comment by ztjal** [comment]
1，因为默认打开就是首页，不换代理就在那不停自检，会卡浏览器，很多时候只想看信息，又不需要切换代理。
2，这个功能只是吃力不讨好，劳民伤财的类型。
3，搞开发当然是让用户变得越蠢越好，但并不是所有的软件都是这样，这个软件就是这类。
自检功能是向易用性方面发展的，越易用代表越多小白可以用，越多小白用代表死得越快，旁边的两个倒了不会不知道吧。

**Comment by Cat7373** [comment]
坐等 X大 来发表意见。
@xxnet 
@yeahwu 
@simonasd

**Comment by yeahwu** [comment]
第一，第二可商榷，第三就是扯鸡巴蛋，旁边两个倒了，你要搞清楚是什么原因倒的？是小白造成的吗？好吧，你就不要打哑语了，不就是ss和goagent吗？
其实这两个倒了的根本原因，就是作者不维护了，管小白什么事？
还有其实这两货还在，ss还在推送，goagent对于小白来说门槛有点高。
最后，我是小白，我拥有和大神一样的翻墙权利。

最后来说说易用性，lantern的易用性更好，小白用户更多，它不是还没倒？

**Comment by yeahwu** [comment]
说到这里，国内这类翻墙软件，最大的硬伤，其实还是作者，还有运维。
再好的工具，作者没了，没有团队维护，最后都得倒

**Comment by Cat7373** [comment]
自检的问题可以考虑，第一次自检失败后，之后的自检间隔延长。

**Comment by ztjal** [comment]
树大招风，作者在国内，SS被请喝荼之后就删了，假定换成这个的作者呢，敢不从？
蓝灯是国外软件，和我想表达的没任何关系。

**Comment by yeahwu** [comment]
xx-net最大的意义就是面向小白，也是它最可爱的地方。

**Comment by jzp820927** [comment]
@ztjal 只要做好匿名，没什么可怕的，你懂的！

**Comment by panzer1313208** [comment]
@ztjal SS和GAE倒了？呵呵我群里还有人用呢。不维护不等于不能用。倒了一般是不能用的意思吧？

**Comment by panzer1313208** [comment]
@ztjal SS没人维护了，还有SSR呢。

**Comment by panzer1313208** [comment]
@ztjal @yeahwu 而且，要是说易用性，难道比得上hosts？hosts翻墙更特么简单。比ss还简单。ss还需要帐号呢。

**Comment by panzer1313208** [comment]
@ztjal SS删了么？只是源代码删了而已，SS照样可以继续用。SS不能用了，还有SSR可以用。

**Comment by simonasd** [comment]
诸位，我认为，基于GAE的翻墙工具，其定位就不是高水平用户。高端玩家有更好的选择，不赘述。

基于GAE的翻墙工具，优势在于Google数以百万计的庞大服务器群，和完全免费的策略（愿上帝保佑Google）。这意味着近乎为0的准入门槛，和相当高的稳定性——不怕GFW最简单粗暴的基于IP地址的屏蔽策略。基于Github的发布平台，利用的则是“依附的自由”，多数用户能直接地安全地访问Github，下载XX-Net。因此，这类工具就应该向所有水平的用户推广，我们要让所有想翻墙的人，都能访问自由的互联网，而不会为此感到懈怠、疲惫和不知所措。

在Hosts和Goagent的时代，我们害怕自己的IP列表被太多人使用而失效，XX-Net解决了这个问题。后台的代码确保了最大程度的稳定、静默，并能够提供尽可能良好的访问速度。在XX-Net的流量特征被识别之前，我们不必担心“树大招风”。

各位开发者，请保护好自己的匿名性。你我的人身安全，是目前XX-Net项目最脆弱的一环。（是的，我天天唠叨这个。）但就算这个项目的所有开发者都被捕了，开源的代码依旧会继续流传，被fork被改进。

**Comment by xxnet** [comment]
​大家有空多去看看代码，在我没被请喝茶之前来问我啊，我有问必答，哪天我不在了，你们可以接着干哈哈哈


或者我现在就不干了，大伙接着干吧，只要能接着干的人足够多，我就安全了

**Comment by yeahwu** [comment]
“我们要让所有想翻墙的人，都能访问自由的互联网，而不会为此感到懈怠、疲惫和不知所措。”sm讲得太好了。这个“自由地”要让更多小白涌入。
xx这个是在宣传分布式开发吗？可惜能力有限哪！
Michael.X <notifications@github.com>于2016年1月9日 周六17:47写道：

**Comment by panzer1313208** [comment]
@xxnet 大大，祝你永远不会被请喝茶。还有那个右键切换模式的问题我已经找到了。PPPOE拨号宽带。起作用的是IE选项里的设置，而不是局域网设置。是局域网设置上面那个设置按钮。而局域网设置是对路由器起作用的。宽带拨号用的是局域网设置上面那个设置里的。

**Comment by xxnet** [comment]
​@panzer
你看看Lantern还是SSR里哪个解决了这个问题的，我们抄过来就好了

**Comment by xxnet** [comment]
​看到 pull了

**Comment by simonasd** [comment]
@yeahwu 其实整个项目都是我一个人在开发，@xxnet、@simonasd、@panzer1313208以及@Cat7373等等都是不同的马甲号，用来参与不同的项目。不信我等一下换个账号跟你聊天。

**Comment by yeahwu** [comment]
@simonasd 这样也行？这我要借鉴哪，我那项目太冷清了，我也搞几个马甲去弄弄，显得火热嘛！
嗯，匿名是个高深的学问，1:偷网，2:变性，3:tor，4:现在要加上“马甲”了

**Comment by Cat7373** [comment]
@yeahwu 其实整个项目都是我一个人在开发，@xxnet、@simonasd、@panzer1313208以及@Cat7373等等都是不同的马甲号，用来参与不同的项目。不信我等一下换个账号跟你聊天。

**Comment by panzer1313208** [comment]
@xxnet 我又不懂代码。怎么看？

**Comment by xxnet** [comment]
​学吧，python 不难

**Comment by panzer1313208** [comment]
我还是继续玩LOL吧

**Comment by Cat7373** [comment]
@xxnet 
Python 本身是不难，但是一些库，没用过的时候还是比较难看懂的，需要去看半天文档才能看懂。
而且 XX-Net 的代码大多没有注释，从未接触过这个项目的人很难看懂代码。

**Comment by xxnet** [comment]
​感觉这里的难点不在于 python 语法本身，而在于各种知识点：

比如HTTP协议，SSL/TLS协议，需要深入理解原理和具体的实现流程，然后
自己去重新调用。

然后各种库的设计和使用方法，有时需要自己改库，已经自己改了好几个库。
各种操作系统的平台兼容。

然后是GAE平台的特性，google 都有文档，这些都需要花很多时间去看。

goagent服务端的设计，看源码就好了。

要把整个GAE模块的主流程看懂，这些功课需要做。
