### ISSUE TITLE
1.0.2 想升级到1.0.4 需要做什么

### ISSUE THREAD

**Issue by deary** [XX-net/XX-Net#16]
1.0.2 想升级到1.0.4  需要做什么

**Comment by xxnet** [comment]
下载新版本，重新配置吧，目前变动大，没有做模块化升级。

**Comment by streamgo** [comment]
正在测试最新版本中。已经在goagent中给你留言。是否说当前的自动升级功能是不可用的？我是指配置页面中的。

**Comment by deary** [comment]
@xxnet   需要重新上传吗

**Comment by streamgo** [comment]
我没有重新上传。直接用的我的3.2.*的版本的APPID。使用是正常的。

**Comment by xxnet** [comment]
还没有确认是否稳定，暂时没有推送更新。请先手动下载新版测试，等把多版本切换做好了，再作推送更新。
