### ISSUE TITLE
来回转换非Unicode字符使用区域会导致程序无法使用

### ISSUE THREAD

**Issue by soganotojiko** [XX-net/XX-Net#160]
状态页和日志页完全为空白

**Comment by xxnet** [comment]
“来回转换非Unicode字符使用区域" 是在操作系统的设置里吗？

状态页空白，状态页最下面一行有帮助，如何查问题的指引。
新版加上去的。


2015-04-15 0:45 GMT-04:00 soganotojiko <notifications@github.com>:

**Comment by xxnet** [comment]
试试打开cmd，命令行启动start.bat看看问题在哪里
状态页最下面一行字有帮助链接
