### ISSUE TITLE
打开谷歌学术显示计算机中存在异常流量

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#1617]
打开谷歌学术时网页出现如下提示，但其他网页和谷歌主页都没有问题。

我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

IP 地址：107.178.195.244
时间：2015-12-16T13:49:08Z
网址：http://www.google.com/

**Comment by zjhzxhz** [comment]
感觉应该是这个 IP 使用的人太多了吧？

**Comment by Kirajin** [comment]
也出现了这个情况，同问

**Comment by Kirajin** [comment]
不过只有.cn上不去..https://scholar.google.com/这个可以用的

**Comment by zzgpku** [comment]
现在又好了。。。

**Comment by lushilei** [comment]
这边也是，谷歌学术上不去

**Comment by lushilei** [comment]
大神解决一下吧
