### ISSUE TITLE
ip-handshake-10: -1

### ISSUE THREAD

**Issue by davidkunlamwong** [XX-net/XX-Net#1618]
---

问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

---

诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
xxnet-version: 2.7.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 0,0
connected-link: 0,0
scan-ip-thread-num: 50
ip-handshake-10: -1
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zjhzxhz** [comment]
请保持 XX-Net 处于开启状态，静候几小时。
由于刚安装，程序需要扫描可用 IP。

**Comment by david10208** [comment]
不不不 已经用了好久了 上午还好好的在上Gmail 然后重启以后突然就没有办法再上了 用start.bat运行一直显示黄色的no enough ip

**Comment by david10208** [comment]
已解决：删除2.7.3 重新安装2.3.0然后自动升级2.7.3 IP就不为0了 握手也不是-1了
