### ISSUE TITLE
xx估计睡觉鸟，我来打广告，各位开发者，程序猿，下面是集成tor的项目，没事去看看。匿名嘛，总是要的。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1627]
速度网友帮忙测试了，土鳖720p，真是糟蹋呀，居然用tor来看视频。好吧，下面是链接：
https://github.com/yeahwu/firefox-tor

**Comment by yeahwu** [comment]
XX-NET=叉烧狗，今天突然看见的，感觉怎么这么形象呢，:laughing::laughing::laughing::laughing:

**Comment by linhua55** [comment]
@yeahwu 
准确的说，应该是湘西网
www.xxnet.com.cn

**Comment by yeahwu** [comment]
我真不是来砸场子的，但是还是觉得叉烧狗贴切。
linhua55 <notifications@github.com>于2015年12月17日 周四19:14写道：

**Comment by simonasd** [comment]
@yeahwu 点赞。我去[粉碎棱镜](https://github.com/nylira/prism-break)那边拉几个老外过来参观参观。

**Comment by yeahwu** [comment]
@simonasd  哎呦，受宠若惊了！自己测试了下确实可以土鳖720p，下面附上韩国美眉热舞链接，大家试试。最后还是上图，上图 
https://www.youtube.com/watch?v=xTJDZEuxy8A
![habhan](https://cloud.githubusercontent.com/assets/13328328/11877664/bac6c0ec-a52b-11e5-89c5-609134b6dc0c.JPG)

**Comment by yeahwu** [comment]
测试的是前置lantern，前置ss由于是早期作品，再加上sock5的强加密，速度上可能不如前置lantern，特告知。

**Comment by jzp820927** [comment]
不知道电信网能不能达到这种速度。

**Comment by cobob** [comment]
tor  lantern  这些速度都太慢了 只能作为后备手段，况且你只是查阅一直资料的话，也不需要多么匿名

**Comment by yeahwu** [comment]
我就是电信的。

zxzz <notifications@github.com>于2015年12月18日 周五08:43写道：

**Comment by yeahwu** [comment]
为什么我发完一帖，问问题的都没了？xx你看，我这一帖相当于万灵药啊。

**Comment by skybai1987** [comment]
我用xx-net ，4k, 1080p, 都可以
