### ISSUE TITLE
代理网址都出现  "SSL 连接出错"

### ISSUE THREAD

**Issue by Cindaralle** [XX-net/XX-Net#163]
下面是出错信息

>SSL 连接出错

>隐藏详细信息
>无法与服务器建立安全连接。可能是服务器出现了问题，也可能是您没有服务器要求的客户端身份验证证书。
>错误代码：ERR_SSL_PROTOCOL_ERROR

证书已经安装,难道是我安装出错了??
求解决

**Comment by Cat7373** [comment]
应该是证书没装上去吧- -

**Comment by Cindaralle** [comment]
证书该怎么装呢?软件没有自动安装,我是手动安装的,受信任的根证书颁发机构,还是不可以啊

**Comment by Cat7373** [comment]
有的浏览器不使用OS的证书库
需要手动导入到浏览器里

**Comment by Cindaralle** [comment]
感谢你的解答,可是我实在没办法,我用的chrome,在浏览器也倒入了个遍,但始终无效.

**Comment by xxnet** [comment]
谁能整一份手动导入证书的图文wiki

问的人挺多的

**Comment by EuforiaARiA** [comment]
同样的症状，删除证书重新导入也不行，而且是一夜之间两台电脑都出问题。。

**Comment by EuforiaARiA** [comment]
已解决，广告拦截软件 阿呆喵 升级到2.0之后有些问题，暂时停用了

**Comment by wenhelinlu** [comment]
果然是阿呆喵的问题。
