### ISSUE TITLE
Windows 下一个奇怪的证书问题 

### ISSUE THREAD

**Issue by POTION4** [XX-net/XX-Net#1633]
Firefox 开了 XX-Net 之后，发现证书明明已经导入了却找不到，连外网 Untrusted connection. 
FoxyProxy, 添加例外很正常，但你没可能一个一个添加吧。。。有的还添加不了。 
真心奇怪。手动倒入不行，自动导入不行

附上error 
    Dec 18 22:56:16.398 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket obj
ect at 0x0B5460F0>) failed: [Errno 1] _ssl.c:1426: error:14094418:SSL routines:S
SL3_READ_BYTES:tlsv1 alert unknown ca path:ac.duckduckgo.com:443, errno:1
Dec 18 22:56:16.401 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\昊\Desktop\XX-Net\gae_proxy\local\proxy_handler.py", line 216,
in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\昊\Desktop\XX-Net\python27\1.0\lib\socket.py", line 476, in rea
dline
    data = self._sock.recv(self._rbufsize)
  File "C:\Users\昊\Desktop\XX-Net\python27\1.0\lib\ssl.py", line 241, in recv
    return self.read(buflen)
  File "C:\Users\昊\Desktop\XX-Net\python27\1.0\lib\ssl.py", line 160, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1426: error:14094418:SSL routines:SSL3_READ_BYTES:tls
v1 alert unknown ca
感谢你们~~

**Comment by linhua55** [comment]
重启浏览器，重新导入试试
另外路径名最好不要包含中文

**Comment by POTION4** [comment]
@linhua55 问题解决，有中文名证书不能自动导入，需要手动
我还以为导入了，摆弄了整晚……
