### ISSUE TITLE
[2.8.1]扫描并添加了非google的IP

### ISSUE THREAD

**Issue by xiuluo** [XX-net/XX-Net#1644]
![qq 20151219210328](https://cloud.githubusercontent.com/assets/2190708/11913117/2d57732c-a694-11e5-9f53-13435d89c622.png)
更新2.8.1之后，我看了一下扫描日志，发现扫描到了一些非google的IP，比如第一个http://postur.n1.is/，打开后是Outlook Web App，这些IP可以用吗？

**Comment by xiuluo** [comment]
Dec 19 20:56:12 - [INFO] Add 193.4.115.220 time:1017 CN:postur.n1.is 
Dec 19 20:57:31 - [INFO] Add 23.239.5.254 time:1828 CN:www.dsministries.com 
Dec 19 20:57:39 - [INFO] Add 89.25.215.4 time:812 CN:*.videostar.pl 
Dec 19 20:57:44 - [INFO] Add 88.217.135.76 time:723 CN:*.sdi-muenchen.de 
Dec 19 20:58:14 - [INFO] Add 89.201.175.229 time:2034 CN:*.eluxio.hr 
Dec 19 20:58:19 - [INFO] Add 110.164.8.29 time:296 CN:google.com 
Dec 19 20:58:56 - [INFO] Add 74.207.242.93 time:717 CN:*.wpengine.com 
Dec 19 20:59:11 - [INFO] Add 27.121.54.174 time:219 CN:tlc.tokai.jp 
Dec 19 21:00:34 - [INFO] Add 173.192.69.21 time:358 CN:www.emteasy.com 
Dec 19 21:01:09 - [INFO] Add 103.21.25.5 time:577 CN:*.hs.llnwd.net 
Dec 19 21:01:12 - [INFO] Add 189.199.19.102 time:1766 CN:email.mirage.mx 
Dec 19 21:03:09 - [INFO] Add 191.251.128.133 time:812 CN:crm.acao.com.br 
Dec 19 21:04:14 - [INFO] Add 196.0.3.9 time:3763 CN:*.utl.co.ug 
Dec 19 21:04:35 - [INFO] Add 217.163.7.65 time:780 CN:*.hanergy.co.uk 
Dec 19 21:04:47 - [INFO] Add 180.235.254.252 time:312 CN:www.marutake-corp.co.jp 

应该是bug吧

**Comment by xxnet** [comment]
目前的扫描会检测证书、appid可用性，只要能用，应该没有问题。

2015-12-19 21:12 GMT+08:00 Shura <notifications@github.com>:

**Comment by out-sider** [comment]
会不会是蜜罐？

**Comment by xxnet** [comment]
有证书检查，应该没有问题，不过还是研究下好。

很可能是Google把ip的证书签发给了客户的网站。

2015-12-19 22:42 GMT+08:00 out-sider <notifications@github.com>:

**Comment by xyuanmu** [comment]
@xiuluo 问一下你是否设置了前置代理？刚才试用了下2.8.1，扫描你日志IP所在IP段，一个都扫不出，但是日志中的IP是可以直接打开的。

**Comment by xiuluo** [comment]
@xyuanmu 没有设置，我是教育网

**Comment by xiuluo** [comment]
XX-Net Status：

sys-platform: AMD64, Windows-2012Server-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 2012Server
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:272; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.8.1
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 2999 / 606
network-status: true
connected-link: 6 / 50
scan-ip-thread-num: 100
ip-quality: 250
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
是挺奇怪的，刚刚测试了一下，这些IP不是GWS的IP，不知道你是怎么扫出来的！

**Comment by panzer1313208** [comment]
@jzp820927 我也扫出来了这些IP，我是最新测试版2.8.1

**Comment by jzp820927** [comment]
好吧，感觉是 XX 的 BUG

**Comment by xxnet** [comment]
确认是bug，扫描ip的代码重构了，没有检查证书导致。

好在使用ip的地方有检查，不会出现MITM攻击。
我发个版本修复

2015-12-20 16:57 GMT+08:00 zxzz <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet MITM是什么？

**Comment by xxnet** [comment]
MITM是中间人攻击
https://www.google.com/#q=mitm

2015-12-20 18:09 GMT+08:00 panzer1313208 <notifications@github.com>:

**Comment by panzer1313208** [comment]
@xxnet 也就是说可能导致gfw攻击youtube之类的网站？

**Comment by jzp820927** [comment]
中间人攻击就是通过伪造证书，对数据进行解惑，篡改。
