### ISSUE TITLE
配置界面appid未随manual.ini内容改变

### ISSUE THREAD

**Issue by byzod** [XX-net/XX-Net#1646]
-----------
问题描述：
在`\data\gae_proxy\manual.ini`内指定appid可以正常覆盖其余配置文件设置
但是不会在`http://127.0.0.1:8085/?module=gae_proxy&menu=config`体现，用户只能通过日志一开始的信息确认是否启用所指定id（并且很快就会被刷掉）

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.7.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 277,154
connected-link: 9,11
scan-ip-thread-num: 50
ip-handshake-10: 144
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xyuanmu** [comment]
你很喜欢暴露自己的appid么？你给的那个链接只会显示config.ini里的appid，再说2.7.3版本状态页也贴出Working App IDs了，新版本干脆不显示我觉得更好。

**Comment by byzod** [comment]
啊？哪里暴露了？我编辑掉

**Comment by xxnet** [comment]
不要在manual 里设置appid，因为web_ui不能修改/覆盖 manual.ini，如果显示出来，又如何修改？

因此manual只放一些非常高级的参数用，webui 能设置的，就不要放manual了。

2015-12-20 10:26 GMT+08:00 byzod <notifications@github.com>:

**Comment by xyuanmu** [comment]
@byzod 我的意思是只要知道工作的appid不是默认的就行了，为什么一定要显示出来。

**Comment by byzod** [comment]
@xxnet 
这么一说也有道理，只是设计理念不同罢
因为以前用goa都是把所有配置放proxy.user.ini里，这样重新部署客户端只需要复制一个文件就好了
