### ISSUE TITLE
以前用goagent,托盘右键选择代理,然后迅雷选择代理,可以下载.

### ISSUE THREAD

**Issue by mtvktvcn** [XX-net/XX-Net#165]
以前用goagent,托盘右键选择代理,然后迅雷选择代理,可以下载.
现在托盘选择set proxy
迅雷貌似也下载不了.
主要是用来下载youtube的影片.

**Comment by Cat7373** [comment]
手动在迅雷设置HTTP代理即可

**Comment by mtvktvcn** [comment]
之前是设置 使用IE代理 .
现在你说手动在迅雷设置 HTTP代理.还真不知道IP是多少啊.

**Comment by Cat7373** [comment]
127.0.0.1:8087

**Comment by mtvktvcn** [comment]
成功了.感谢楼上的指教.万分感谢.

**Comment by Cat7373** [comment]
评论框下面有关闭Issue喵!
解决了就关掉吧喵~
