### ISSUE TITLE
升級到2.8.2後所有appid全都不可用,連接池也是0/0

### ISSUE THREAD

**Issue by hoshinokana** [XX-net/XX-Net#1653]
XX-Net Status：

sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
xxnet-version: 2.8.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 605
network-status: true
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 171
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by wsgdlhy** [comment]
2.8.1或2.8.2都一样

**Comment by xxnet** [comment]
把日志发上来看看

2015-12-20 20:36 GMT+08:00 wsgdlhy <notifications@github.com>:

**Comment by linhua55** [comment]
虽然可以使用，但是一键生成的反馈中的`Appids_Not_Exist: true`
XX-Net Status：

sys-platform: x86_64, Linux-4.0.4-pf-x86_64-with-glibc2.2.5
os-system: Linux
os-version: #6 SMP PREEMPT Wed May 20 07:35:32 EEST 2015
os-release: 4.0.4-pf
os-detail: Dist:; Version:; ID:
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
xxnet-version: 2.8.2
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 3000 / 83
network-status: true
connected-link: 7 / 26
scan-ip-thread-num: 50
ip-quality: 301
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
**Appids_Not_Exist: true**
Using_Public_Appid: false

**Comment by linhua55** [comment]
发现问题：
appid名字周围有空格时，会把这个appid当作不存在
如   xxx | xxx |xxx | xxx

**Comment by WDZThorn** [comment]
我之前是 , 分割 appid 的，改成 | 正常了
