### ISSUE TITLE
Number of IP Decreases Rapidly

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#1654]
更新2.8.0后我的3000可用 IP 急转直下，只剩下了不到100.
I wonder what happened? It's a disaster!!

![screen shot 2015-12-20 at 23 39 30](https://cloud.githubusercontent.com/assets/1730504/11918599/10ab9b24-a773-11e5-9285-5b35fb18c07a.png)

**Comment by linhua55** [comment]
git同步到master后，刚一启动，
屏幕满是像
Dec 21 00:18:28.005 - [INFO] remove_slowest_ip:203.176.178.15 handshake_time:1406, fails:0
的信息，
而这个ip `203.176.178.15` 是可用的呀。

**Comment by xxnet** [comment]
2015-12-20 23:43 GMT+08:00 Haozhe Xie <notifications@github.com>:

> 更新2.8.0后我的3000可用 IP 急转直下，只剩下了不到100.
> I wonder what happened? It's a disaster!!
>
2.8.0 有bug，请使用2.8.2

**Comment by xxnet** [comment]
2015-12-21 0:22 GMT+08:00 linhua55 <notifications@github.com>:

> git同步到master后，刚一启动，
> 屏幕满是像
> Dec 21 00:18:28.005 - [INFO] remove_slowest_ip:203.176.178.15
> handshake_time:1406, fails:0
> 的信息，
> 而这个ip 203.176.178.15 是可用的呀。
>
这句日志是ip超出3000个，才会剔除最慢的
应该不会影响你的正常使用

**Comment by linhua55** [comment]
的确不影响正常使用

**Comment by zjhzxhz** [comment]
@xxnet 我昨天睡觉前更新了2.8.2, 并且导入了之前的备份(导入之后恢复IP数量至3000)
然后, 没几分钟, 发现IP数量又只剩下2600+, 并且还在继续减少 :)

**Comment by xxnet** [comment]
目前显示的是有效ip，不是总量，你那3000个是总量，只要不影响使用就好

在 2015年12月21日 下午2:12，Haozhe Xie <notifications@github.com>写道：

**Comment by zjhzxhz** [comment]
应该不是, 因为我导入的时候, 显示的是3000.
并且, 就学校目前的网络环境来看, 我的IP(有效/总)数量一直都是 3000, 3000.
然而更新到2.8.0+之后就开始一直减少.

**Comment by xxnet** [comment]
把包含ip被删除的日志发上来看看，看ip是什么原因被删除的

在 2015年12月21日 下午2:47，Haozhe Xie <notifications@github.com>写道：

**Comment by zjhzxhz** [comment]
那我晚上用Mac的时候看一下

2015-12-21 15:04 GMT+08:00 Michael.X <notifications@github.com>:

> 把包含ip被删除的日志发上来看看，看ip是什么原因被删除的
>
> 在 2015年12月21日 下午2:47，Haozhe Xie <notifications@github.com>写道：
>
> > 应该不是, 因为我导入的时候, 显示的是3000.
> > 并且, 就学校目前的网络环境来看, 我的IP(有效/总)数量一直都是 3000, 3000.
> > 然而更新到2.8.0+之后就开始一直减少.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/XX-net/XX-Net/issues/1654#issuecomment-166216312>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1654#issuecomment-166218562>.
>



-- 

谢浩哲

**Comment by zjhzxhz** [comment]
@xxnet 
我想我找到了问题所在, 当我断开 WiFi 连接的时候，它会认为 IP 不可用，然后移除 IP。
然后导致 IP 大量减少。

**Comment by xxnet** [comment]
确实​有这种情况，还需要继续优化算法来解决。
  每次去检测网络可用性，都需要消耗资源，需要平衡资源开销和丢失ip的损失。

**Comment by zjhzxhz** [comment]
可是当连接丢失的时候，损失 IP 的速度非常惊人。
比如当我需要带着我的笔记本去其他地方的时候，WiFi 就可能丢失。
是否可以考虑这样实现：当删除 IP 数量达到50个的时候，检查网络可用性。
若网络不可用，则停止删除。

**Comment by xxnet** [comment]
这个逻辑是有的，但是策略不够好，要优化

在 2015年12月22日 上午9:33，Haozhe Xie <notifications@github.com>写道：

**Comment by jzp820927** [comment]
能不能设计一个实时网络监控，类似系统服务那种，检测到断网，软件就停止工作，直到通网。

**Comment by xxnet** [comment]
是的，每删除一个ip都要可靠的验证过才行。


在 2015年12月22日 上午11:15，zxzz <notifications@github.com>写道：

**Comment by zjhzxhz** [comment]
@xxnet 
我又发现一个问题, 现在这个逻辑大大的有问题.
我中午离开实验室, 电脑自动待机了, 然后我下午回来的时候发现可用IP只剩下2740个(离开的时候是3000个).
这这这…… 太Bug了.
相比性能, 我觉得可用性更重要 :)

**Comment by xxnet** [comment]
估计是同一个问题导致的，待机后恢复，时间突然跳，而刚恢复电脑，网络需要几十秒来重新建立，这段时间丢失了ip。
实际上这些ip还在，但没有显示在可用里面。

从最终结果看，这个bug会导致最好的ip在网络异常时丢失，损失还是很大的。
已经着手在解决这个bug了，测试稳定可能需要2天时间。

在 2015年12月22日 下午3:50，Haozhe Xie <notifications@github.com>写道：

**Comment by xxnet** [comment]
@zjhzxhz  

无网络时，快速丢失可用ip
 这个问题已解决，请测试：

未发布新版本，可git pull或者通过这个链接下载：
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by zjhzxhz** [comment]
好的.

怎么感觉从前端工程师变成测试工程师了 →_→

2015-12-23 12:35 GMT+08:00 Michael.X <notifications@github.com>:

> @zjhzxhz <https://github.com/zjhzxhz>
>
> 无网络时，快速丢失可用ip
> 这个问题已解决，请测试：
>
> 未发布新版本，可git pull或者通过这个链接下载：
> https://github.com/XX-net/XX-Net/archive/master.zip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1654#issuecomment-166801423>.
>



-- 

谢浩哲

**Comment by zjhzxhz** [comment]
@xxnet 
你确定吗? 为什么我一运行IP就开始直线下降:
以下为Log:
```
Dec 23 15:15:36.407 - [INFO] load google ip_list num:3002, gws num:3000
Dec 23 15:15:36.407 - [INFO] Adjust scan thread num from 50 to 17
Dec 23 15:15:36.422 - [INFO] Adjust scan thread num from 17 to 0
Dec 23 15:15:36.458 - [DEBUG] ## GAEProxy set keep_running: True
Dec 23 15:15:36.459 - [INFO] ------------------------------------------------------
Dec 23 15:15:36.459 - [INFO] Python Version : 2.7.9
Dec 23 15:15:36.460 - [INFO] OS : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Dec 23 15:15:36.460 - [INFO] Listen Address : 0.0.0.0:8087
Dec 23 15:15:36.460 - [INFO] GAE APPID : zjhzxhz-xxnet
Dec 23 15:15:36.460 - [INFO] Pac Server : http://0.0.0.0:8086/proxy.pac
Dec 23 15:15:36.460 - [INFO] ------------------------------------------------------
Dec 23 15:15:36.498 - [DEBUG] start scan all exist ip, num:3002
Dec 23 15:15:37.587 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Dec 23 15:15:37.629 - [DEBUG] get ip:218.189.25.178 t:116
Dec 23 15:15:37.695 - [INFO] GAE CONNECT www.twitter.com:443
Dec 23 15:15:37.841 - [DEBUG] get ip:203.78.36.97 t:118
Dec 23 15:15:37.943 - [DEBUG] get ip:218.189.25.156 t:123
Dec 23 15:15:37.997 - [DEBUG] create_ssl update ip:218.189.25.178 time:246
Dec 23 15:15:38.044 - [DEBUG] get ip:218.189.25.157 t:123
Dec 23 15:15:38.060 - [INFO] scan_ip_worker exit
Dec 23 15:15:38.106 - [DEBUG] create_ssl update ip:203.78.36.97 time:177
Dec 23 15:15:38.154 - [DEBUG] get ip:203.78.36.98 t:124
Dec 23 15:15:38.195 - [DEBUG] create_ssl update ip:218.189.25.156 time:197
Dec 23 15:15:38.264 - [DEBUG] get ip:203.78.36.102 t:124
Dec 23 15:15:38.311 - [DEBUG] create_ssl update ip:218.189.25.157 time:188
Dec 23 15:15:38.373 - [DEBUG] get ip:203.78.36.68 t:125
Dec 23 15:15:38.436 - [DEBUG] create_ssl update ip:203.78.36.98 time:219
Dec 23 15:15:38.561 - [DEBUG] create_ssl update ip:203.78.36.68 time:141
Dec 23 15:15:38.654 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=a7f23fd0-e562-422f-b505-eb3004e049b5&version=2.8.2&platform=Windows-7-6.1.7601-SP1
Dec 23 15:15:38.748 - [DEBUG] create_ssl update ip:203.78.36.102 time:125
Dec 23 15:15:38.911 - [INFO] GAE 2208|203.78.36.68|105 t:256 s:1674 hs:141 200 https://xxnet-update.appspot.com/update.json?uuid=a7f23fd0-e562-422f-b505-eb3004e049b5&version=2.8.2&platform=Windows-7-6.1.7601-SP1
Dec 23 15:15:39.546 - [INFO] scan_ip_worker exit
Dec 23 15:15:39.546 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.420 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.435 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.436 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.436 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.436 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.436 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.436 - [INFO] scan_ip_worker exit
Dec 23 15:15:42.436 - [INFO] scan_ip_worker exit
Dec 23 15:16:01.106 - [INFO] PAC from:127.0.0.1:37841 GET /proxy.pac
Dec 23 15:16:01.151 - [INFO] PAC from:127.0.0.1:37843 GET /proxy.pac
Dec 23 15:16:15.189 - [INFO] GAE CONNECT mail.google.com:443
Dec 23 15:16:15.207 - [DEBUG] GAE CONNECT GET https://mail.google.com/mail/feed/atom?zx=gmc180561795932
Dec 23 15:16:15.207 - [DEBUG] ssl_pool.get:203.78.36.68 handshake:141
Dec 23 15:16:15.521 - [INFO] GAE 2208|203.78.36.68|2121 t:313 s:258 hs:141 200 https://mail.google.com/mail/feed/atom?zx=gmc180561795932
Dec 23 15:16:28.826 - [INFO] GAE CONNECT mtalk.google.com:5228
Dec 23 15:16:28.842 - [WARNING] parse request fail:)
Dec 23 15:16:30.732 - [DEBUG] get ip:218.189.25.132 t:125
Dec 23 15:16:30.841 - [DEBUG] get ip:218.189.25.135 t:125
Dec 23 15:16:30 - [DEBUG]LOG_EXCEPT: get ip:203.78.36.90 t:125, Except:[Errno 9] Bad file descriptor
Dec 23 15:16:31.059 - [DEBUG] create_ssl update ip:218.189.25.135 time:145
Dec 23 15:16:31.059 - [DEBUG] get ip:203.78.36.94 t:125
Dec 23 15:16:31.149 - [DEBUG] create_ssl update ip:203.78.36.90 time:134
Dec 23 15:16:31.254 - [DEBUG] create_ssl update ip:203.78.36.94 time:134
Dec 23 15:16:31.821 - [INFO] GAE CONNECT github.com:443
Dec 23 15:16:31.844 - [DEBUG] GAE CONNECT GET https://github.com/
Dec 23 15:16:31.845 - [DEBUG] ssl_pool.get:203.78.36.68 handshake:141
Dec 23 15:16:31.846 - [DEBUG] get ip:203.78.36.86 t:125
```

**Comment by zjhzxhz** [comment]
好像稳定了, 可用IP稳定在2720.
我再观察观察.

**Comment by zjhzxhz** [comment]
日志看似是正常的，但是 IP 就是在减少。之前的版本就不会这样。
启动之后 IP 一直减少，现在只剩下428个了。
刚打了一个电话回来，这可倒好，Connection Pool 都没有了(0, 0).
简直不能忍，我要回退了。

```
Dec 23 22:40:13.405 - [INFO] report_connect_fail:119.15.80.157
Dec 23 22:40:13.480 - [DEBUG] get ip:110.164.6.29 t:303
Dec 23 22:40:13.508 - [DEBUG] 103.16.207.23 fail:timeout('timed out',)
Dec 23 22:40:13.508 - [INFO] report_connect_fail:103.16.207.23
Dec 23 22:40:13.585 - [DEBUG] get ip:103.16.207.44 t:303
Dec 23 22:40:13.612 - [DEBUG] 114.4.41.210 fail:timeout('timed out',)
Dec 23 22:40:13.612 - [INFO] report_connect_fail:114.4.41.210
Dec 23 22:40:13.717 - [DEBUG] 103.16.207.74 fail:timeout('timed out',)
Dec 23 22:40:13.718 - [INFO] report_connect_fail:103.16.207.74
Dec 23 22:40:13.824 - [DEBUG] 110.164.8.174 fail:timeout('timed out',)
Dec 23 22:40:13.824 - [INFO] report_connect_fail:110.164.8.174
Dec 23 22:40:13.930 - [DEBUG] 115.178.27.5 fail:timeout('timed out',)
Dec 23 22:40:13.930 - [INFO] report_connect_fail:115.178.27.5
Dec 23 22:40:14.027 - [DEBUG] 110.164.10.210 fail:timeout('timed out',)
Dec 23 22:40:14.027 - [INFO] report_connect_fail:110.164.10.210
Dec 23 22:40:14.061 - [DEBUG] create_ssl update ip:110.164.6.29 time:454
Dec 23 22:40:14.137 - [DEBUG] 115.84.108.15 fail:timeout('timed out',)
Dec 23 22:40:14.137 - [INFO] report_connect_fail:115.84.108.15
Dec 23 22:40:14.240 - [DEBUG] 202.93.153.169 fail:timeout('timed out',)
Dec 23 22:40:14.240 - [INFO] report_connect_fail:202.93.153.169
Dec 23 22:40:14.317 - [DEBUG] 119.15.80.151 fail:timeout('timed out',)
Dec 23 22:40:14.317 - [INFO] report_connect_fail:119.15.80.151
Dec 23 22:40:14.698 - [DEBUG] ip:103.16.207.246 real fail
Dec 23 22:40:14.703 - [DEBUG] 103.16.207.8 fail:timeout('timed out',)
Dec 23 22:40:14.703 - [INFO] report_connect_fail:103.16.207.8
Dec 23 22:40:15.329 - [DEBUG] get ip:103.16.204.136 t:306
Dec 23 22:40:15.709 - [DEBUG] get ip:103.16.207.198 t:306
Dec 23 22:40:17.590 - [DEBUG] 103.16.207.44 fail:timeout('timed out',)
Dec 23 22:40:17.591 - [INFO] report_connect_fail:103.16.207.44
Dec 23 22:40:18.697 - [DEBUG] get ip:110.164.10.38 t:240
Dec 23 22:40:18.803 - [DEBUG] get ip:110.164.13.28 t:303
Dec 23 22:40:18.904 - [DEBUG] get ip:223.26.69.43 t:303
Dec 23 22:40:19.006 - [DEBUG] get ip:202.122.145.161 t:303
Dec 23 22:40:19.069 - [DEBUG] create_ssl update ip:110.164.10.38 time:239
Dec 23 22:40:19.332 - [DEBUG] 103.16.204.136 fail:timeout('timed out',)
Dec 23 22:40:19.333 - [INFO] report_connect_fail:103.16.204.136
Dec 23 22:40:19.703 - [DEBUG] ip:202.93.153.121 real fail
Dec 23 22:40:19.712 - [DEBUG] 103.16.207.198 fail:timeout('timed out',)
Dec 23 22:40:19.712 - [INFO] report_connect_fail:103.16.207.198
Dec 23 22:40:22.805 - [DEBUG] 110.164.13.28 fail:timeout('timed out',)
Dec 23 22:40:22.805 - [INFO] report_connect_fail:110.164.13.28
Dec 23 22:40:22.905 - [DEBUG] 223.26.69.43 fail:timeout('timed out',)
Dec 23 22:40:22.906 - [INFO] report_connect_fail:223.26.69.43
Dec 23 22:40:23.008 - [DEBUG] 202.122.145.161 fail:timeout('timed out',)
Dec 23 22:40:23.008 - [INFO] report_connect_fail:202.122.145.161
Dec 23 22:40:24.710 - [DEBUG] ip:110.164.12.215 real fail
Dec 23 22:40:29.717 - [DEBUG] ip:110.164.6.226 real fail
Dec 23 22:40:34.723 - [DEBUG] ip:110.164.6.221 real fail
Dec 23 22:40:39.730 - [DEBUG] ip:110.164.4.88 real fail
Dec 23 22:40:44.736 - [DEBUG] ip:110.164.12.104 real fail
Dec 23 22:40:49.742 - [DEBUG] ip:115.254.106.247 real fail
Dec 23 22:40:54.749 - [DEBUG] ip:110.164.4.148 real fail
Dec 23 22:40:57.296 - [DEBUG] 103.11.28.98 close:slowest 1091
Dec 23 22:40:57.906 - [DEBUG] get ip:218.189.25.157 t:126
Dec 23 22:40:58.006 - [DEBUG] get ip:218.189.25.156 t:127
Dec 23 22:40:58.108 - [DEBUG] create_ssl update ip:218.189.25.157 time:125
Dec 23 22:40:58.108 - [DEBUG] get ip:218.189.25.155 t:127
Dec 23 22:40:58.194 - [DEBUG] create_ssl update ip:218.189.25.156 time:126
Dec 23 22:40:58.298 - [DEBUG] create_ssl update ip:218.189.25.155 time:128
Dec 23 22:40:59.755 - [DEBUG] ip:202.58.96.240 real fail
Dec 23 22:41:02.827 - [DEBUG] 103.11.28.150 close:slowest 1056
Dec 23 22:41:03.669 - [DEBUG] 222.165.163.76 close:slowest 1063
Dec 23 22:41:04.761 - [DEBUG] ip:1.9.131.33 real fail
Dec 23 22:41:07.058 - [DEBUG] get ip:218.189.25.154 t:130
Dec 23 22:41:07.163 - [DEBUG] get ip:218.189.25.152 t:192
Dec 23 22:41:07.241 - [DEBUG] create_ssl update ip:218.189.25.154 time:124
Dec 23 22:41:07.328 - [DEBUG] 103.11.30.41 close:slowest 1056
Dec 23 22:41:07.354 - [DEBUG] create_ssl update ip:218.189.25.152 time:130
Dec 23 22:41:09.764 - [DEBUG] ip:223.26.69.39 real fail
Dec 23 22:41:12.372 - [DEBUG] 103.11.28.22 close:slowest 1005
```

**Comment by xxnet** [comment]
无法使用吗？
看日志是有建立连接的，而且还不少

在 2015年12月23日 下午11:27，Haozhe Xie <notifications@github.com>写道：

**Comment by zjhzxhz** [comment]
贴日志这会儿的确有连接.
当IP只剩400多的时候 Connection就为0了.

2015-12-24 9:19 GMT+08:00 Michael.X <notifications@github.com>:

> 无法使用吗？
> 看日志是有建立连接的，而且还不少
>
> 在 2015年12月23日 下午11:27，Haozhe Xie <notifications@github.com>写道：
>
> > 日志看似是正常的，但是 IP 就是在减少。之前的版本就不会这样。
> > 启动之后 IP 一直减少，现在只剩下428个了。
> > 刚打了一个电话回来，这可倒好，Connection Pool 都没有了(0, 0).
> > 简直不能忍，我要回退了。
> >
> > Dec 23 22:40:13.405 - [INFO] report_connect_fail:119.15.80.157
> > Dec 23 22:40:13.480 - [DEBUG] get ip:110.164.6.29 t:303
> > Dec 23 22:40:13.508 - [DEBUG] 103.16.207.23 fail:timeout('timed out',)
> > Dec 23 22:40:13.508 - [INFO] report_connect_fail:103.16.207.23
> > Dec 23 22:40:13.585 - [DEBUG] get ip:103.16.207.44 t:303
> > Dec 23 22:40:13.612 - [DEBUG] 114.4.41.210 fail:timeout('timed out',)
> > Dec 23 22:40:13.612 - [INFO] report_connect_fail:114.4.41.210
> > Dec 23 22:40:13.717 - [DEBUG] 103.16.207.74 fail:timeout('timed out',)
> > Dec 23 22:40:13.718 - [INFO] report_connect_fail:103.16.207.74
> > Dec 23 22:40:13.824 - [DEBUG] 110.164.8.174 fail:timeout('timed out',)
> > Dec 23 22:40:13.824 - [INFO] report_connect_fail:110.164.8.174
> > Dec 23 22:40:13.930 - [DEBUG] 115.178.27.5 fail:timeout('timed out',)
> > Dec 23 22:40:13.930 - [INFO] report_connect_fail:115.178.27.5
> > Dec 23 22:40:14.027 - [DEBUG] 110.164.10.210 fail:timeout('timed out',)
> > Dec 23 22:40:14.027 - [INFO] report_connect_fail:110.164.10.210
> > Dec 23 22:40:14.061 - [DEBUG] create_ssl update ip:110.164.6.29 time:454
> > Dec 23 22:40:14.137 - [DEBUG] 115.84.108.15 fail:timeout('timed out',)
> > Dec 23 22:40:14.137 - [INFO] report_connect_fail:115.84.108.15
> > Dec 23 22:40:14.240 - [DEBUG] 202.93.153.169 fail:timeout('timed out',)
> > Dec 23 22:40:14.240 - [INFO] report_connect_fail:202.93.153.169
> > Dec 23 22:40:14.317 - [DEBUG] 119.15.80.151 fail:timeout('timed out',)
> > Dec 23 22:40:14.317 - [INFO] report_connect_fail:119.15.80.151
> > Dec 23 22:40:14.698 - [DEBUG] ip:103.16.207.246 real fail
> > Dec 23 22:40:14.703 - [DEBUG] 103.16.207.8 fail:timeout('timed out',)
> > Dec 23 22:40:14.703 - [INFO] report_connect_fail:103.16.207.8
> > Dec 23 22:40:15.329 - [DEBUG] get ip:103.16.204.136 t:306
> > Dec 23 22:40:15.709 - [DEBUG] get ip:103.16.207.198 t:306
> > Dec 23 22:40:17.590 - [DEBUG] 103.16.207.44 fail:timeout('timed out',)
> > Dec 23 22:40:17.591 - [INFO] report_connect_fail:103.16.207.44
> > Dec 23 22:40:18.697 - [DEBUG] get ip:110.164.10.38 t:240
> > Dec 23 22:40:18.803 - [DEBUG] get ip:110.164.13.28 t:303
> > Dec 23 22:40:18.904 - [DEBUG] get ip:223.26.69.43 t:303
> > Dec 23 22:40:19.006 - [DEBUG] get ip:202.122.145.161 t:303
> > Dec 23 22:40:19.069 - [DEBUG] create_ssl update ip:110.164.10.38 time:239
> > Dec 23 22:40:19.332 - [DEBUG] 103.16.204.136 fail:timeout('timed out',)
> > Dec 23 22:40:19.333 - [INFO] report_connect_fail:103.16.204.136
> > Dec 23 22:40:19.703 - [DEBUG] ip:202.93.153.121 real fail
> > Dec 23 22:40:19.712 - [DEBUG] 103.16.207.198 fail:timeout('timed out',)
> > Dec 23 22:40:19.712 - [INFO] report_connect_fail:103.16.207.198
> > Dec 23 22:40:22.805 - [DEBUG] 110.164.13.28 fail:timeout('timed out',)
> > Dec 23 22:40:22.805 - [INFO] report_connect_fail:110.164.13.28
> > Dec 23 22:40:22.905 - [DEBUG] 223.26.69.43 fail:timeout('timed out',)
> > Dec 23 22:40:22.906 - [INFO] report_connect_fail:223.26.69.43
> > Dec 23 22:40:23.008 - [DEBUG] 202.122.145.161 fail:timeout('timed out',)
> > Dec 23 22:40:23.008 - [INFO] report_connect_fail:202.122.145.161
> > Dec 23 22:40:24.710 - [DEBUG] ip:110.164.12.215 real fail
> > Dec 23 22:40:29.717 - [DEBUG] ip:110.164.6.226 real fail
> > Dec 23 22:40:34.723 - [DEBUG] ip:110.164.6.221 real fail
> > Dec 23 22:40:39.730 - [DEBUG] ip:110.164.4.88 real fail
> > Dec 23 22:40:44.736 - [DEBUG] ip:110.164.12.104 real fail
> > Dec 23 22:40:49.742 - [DEBUG] ip:115.254.106.247 real fail
> > Dec 23 22:40:54.749 - [DEBUG] ip:110.164.4.148 real fail
> > Dec 23 22:40:57.296 - [DEBUG] 103.11.28.98 close:slowest 1091
> > Dec 23 22:40:57.906 - [DEBUG] get ip:218.189.25.157 t:126
> > Dec 23 22:40:58.006 - [DEBUG] get ip:218.189.25.156 t:127
> > Dec 23 22:40:58.108 - [DEBUG] create_ssl update ip:218.189.25.157
> time:125
> > Dec 23 22:40:58.108 - [DEBUG] get ip:218.189.25.155 t:127
> > Dec 23 22:40:58.194 - [DEBUG] create_ssl update ip:218.189.25.156
> time:126
> > Dec 23 22:40:58.298 - [DEBUG] create_ssl update ip:218.189.25.155
> time:128
> > Dec 23 22:40:59.755 - [DEBUG] ip:202.58.96.240 real fail
> > Dec 23 22:41:02.827 - [DEBUG] 103.11.28.150 close:slowest 1056
> > Dec 23 22:41:03.669 - [DEBUG] 222.165.163.76 close:slowest 1063
> > Dec 23 22:41:04.761 - [DEBUG] ip:1.9.131.33 real fail
> > Dec 23 22:41:07.058 - [DEBUG] get ip:218.189.25.154 t:130
> > Dec 23 22:41:07.163 - [DEBUG] get ip:218.189.25.152 t:192
> > Dec 23 22:41:07.241 - [DEBUG] create_ssl update ip:218.189.25.154
> time:124
> > Dec 23 22:41:07.328 - [DEBUG] 103.11.30.41 close:slowest 1056
> > Dec 23 22:41:07.354 - [DEBUG] create_ssl update ip:218.189.25.152
> time:130
> > Dec 23 22:41:09.764 - [DEBUG] ip:223.26.69.39 real fail
> > Dec 23 22:41:12.372 - [DEBUG] 103.11.28.22 close:slowest 1005
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/XX-net/XX-Net/issues/1654#issuecomment-166923990>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1654#issuecomment-167018195>.
>



-- 

谢浩哲

**Comment by xxnet** [comment]
​重启之后呢？
把连接为0时的日志贴出来

**Comment by zjhzxhz** [comment]
呃~ 没保存呢 - -|||
重启之后也这样……
我晚些时候看看能不能复现这个问题.

**Comment by xxnet** [comment]
重启之后连接数为0吗？
 那把重启之后的日志贴出来看
​

**Comment by zjhzxhz** [comment]
@xxnet 
我今天在实验室中用IP 数量逐渐恢复。
可能是最近寝室的网络不太好吧（汗）
