### ISSUE TITLE
2.7.3有300万ip，升级2.8.2后，复制过去的good_ip.txt没用？？？？

### ISSUE THREAD

**Issue by kapans** [XX-net/XX-Net#1656]
2.7.3的good_ip.txt有300万ip
升级2.8.2后
把good_ip.txt复制过去
但显示 IP数量 只有410

以前升级的时候都可以直接通过复制good_ip.txt获得ip的嘛
这次怎么不行了咧？

**Comment by linhua55** [comment]
可参考 #1654

**Comment by kapans** [comment]
#1654 也只提出了问题，没解决啊？

**Comment by linhua55** [comment]
等待有能力的人解决
提出确切、详细的问题是解决问题的第一步。

**Comment by xxnet** [comment]
总ip数意义不大，有意义的是可用ip数、ip质量。

新版不显示总ip数，因为没有意义，使用者只需要关注可用ip数，甚至不需要关心这些细节，只要能访问，够快就好。

​

**Comment by xxnet** [comment]
你怎么会有300万ip?

2.7.3也最多只保留3000个ip

在 2015年12月21日 上午9:36，linhua55 <notifications@github.com>写道：

**Comment by panzer1313208** [comment]
@xxnet 哈哈，其实总IP数还是有地方能看到的。

**Comment by kapans** [comment]
真有300万啊。。。
Property	Value
Total IP / Good IP	3000,446
10th IP handshake(ms)	133
Connected Links (帮助)	6,1
Number of Threads Scaning IPs	50
Block Status (帮助)	OK

**Comment by linhua55** [comment]
哈哈，3000 和446 是两个不同的数。
看来不能用逗号，应该用‘/’

**Comment by linhua55** [comment]
446表示good ip
对应于老版的good ip

**Comment by kapans** [comment]
谢谢，看来我是正常的。。。

**Comment by linhua55** [comment]
请关闭这个问题页
