### ISSUE TITLE
右下角托盘图标，右键菜单，每次都要点击两次，才起作用。

### ISSUE THREAD

**Issue by jzmswe** [XX-net/XX-Net#167]
配置里的前置代理设置好后，保存重启，就不用管了，以后每次只要在托盘图标中操作就行，但，问题出

来了，不管是托盘图标右键菜单设置全局代理，还是关闭代理，每次都要点击两次，比如设置全局代理，

右键菜单中点击一次，还要再点击一次才行。

Win 8.1 CHS 32 专业版，电话激活，系统补丁打到最新。

**Comment by Cat7373** [comment]
你的意思是 点击图标两次才出现菜单?

**Comment by jzmswe** [comment]
每次菜单都出现，但点击多次才起作用，有时点击多次也没用，要重启XX-Net才行，打开XX-Net10次，有7、8次会出现这种菜单无反应的情况。

**Comment by jzmswe** [comment]
点击菜单后，菜单消失，但菜单该起的作用没起。

**Comment by xxnet** [comment]
可以用start.bat启动，看看操作中有没有异常。

操作后，看看相关的注册表数据，看看有没有变更。

具体逻辑和注册表的项，你可以看看 launcher/x.x.x/win_tray.py源码，猜能猜出个大概

2015-04-16 2:57 GMT-04:00 jzmswe <notifications@github.com>:

**Comment by jzmswe** [comment]
用start.bat启动，还是不行，下面是win_tray.py里的内容：

#!/usr/bin/env python
# coding:utf-8


if __name__ == "__main__":
    import os, sys
    current_path = os.path.dirname(os.path.abspath(__file__))
    python_path = os.path.abspath( os.path.join(current_path, os.pardir, os.pardir, 'python27', '1.0'))
    noarch_lib = os.path.abspath( os.path.join(python_path, 'lib', 'noarch'))
    sys.path.append(noarch_lib)

import webbrowser
from systray import SysTrayIcon
import os
import ctypes
import _winreg as winreg


import module_init
import update
import logging

class Win_tray():
    def __init__(self):
        icon_path = os.path.join(os.path.dirname(__file__), "python.ico")
        self.systray = SysTrayIcon(icon_path, "XX-Net", self.make_menu(), self.on_quit, left_click=self.on_show)

        reg_path = r'Software\Microsoft\Windows\CurrentVersion\Internet Settings'
        self.INTERNET_SETTINGS = winreg.OpenKey(winreg.HKEY_CURRENT_USER,
            reg_path,
            0, winreg.KEY_ALL_ACCESS)

    def make_menu(self):
        menu_options = ((u"Config", None, self.on_show),
#                        ("检查", None, self.on_check_update),
                        (u"Set Global GoAgent Proxy", None, self.on_enable_proxy),
                        (u"Set Global PAC Proxy", None, self.on_enable_pac),
                        (u"Disable Global Proxy", None, self.on_disable_proxy),
                        (u"Reset GoAgent", None, self.on_restart_goagent))
        return menu_options

    def on_show(self, widget=None, data=None):
        self.show_control_web()


    def on_restart_goagent(self, widget=None, data=None):
        module_init.stop_all()
        module_init.start_all_auto()

    def on_check_update(self, widget=None, data=None):
        update.check_update()

    def set_register(self, reg_path, name, reg_type, value):
        #_, reg_type = winreg.QueryValueEx(INTERNET_SETTINGS, name)
        winreg.SetValueEx(reg_path, name, 0, reg_type, value)
        logging.info("set register path:%r name:%s type:%d value:%s", reg_path, name, reg_type, value)

    def on_enable_proxy(self, widget=None, data=None):
        self.set_register(self.INTERNET_SETTINGS, 'AutoConfigURL', 1, "") # disable auto proxy
        self.set_register(self.INTERNET_SETTINGS, 'ProxyEnable', 4, 1)
        self.set_register(self.INTERNET_SETTINGS, 'ProxyOverride', 1, '*.local;<local>')  # Bypass the proxy for localhost
        self.set_register(self.INTERNET_SETTINGS, 'ProxyServer', 1, '127.0.0.1:8087')

    def on_enable_pac(self, widget=None, data=None):
        self.set_register(self.INTERNET_SETTINGS, 'ProxyEnable', 4, 0) # disable goagent proxy
        self.set_register(self.INTERNET_SETTINGS, 'AutoConfigURL', 1, "http://127.0.0.1:8086/proxy.pac")

    def on_disable_proxy(self, widget=None, data=None):
        self.set_register(self.INTERNET_SETTINGS, 'ProxyEnable', 4, 0) # disable goagent proxy
        self.set_register(self.INTERNET_SETTINGS, 'AutoConfigURL', 1, "") # disable auto proxy

    def show_control_web(self, widget=None, data=None):
        webbrowser.open("http://127.0.0.1:8085/")

    def on_quit(self, widget, data=None):
        pass

    def serve_forever(self):
        self.systray._message_loop_func()

    def dialog_yes_no(self, msg="msg", title="Title", data=None, callback=None):
        res = ctypes.windll.user32.MessageBoxW(None, msg, title, 1)
        # Yes:1 No:2
        if callback:
            callback(data, res)
        return res

sys_tray = Win_tray()

def main():
    sys_tray.serve_forever()

if __name__ == '__main__':
    main()

**Comment by xxnet** [comment]
我把原理解释一下，你那边看看是什么现象：
windows通过注册表来设置全局代理。修改的是：
HKEY_CURRENT_USER ：Software\Microsoft\Windows\CurrentVersion\Internet Settings 下面的几个键值：
1. ProxyEnable 为1时，启用全局代理
2. AutoConfigURL 有内容时，启用PAC代理
为空时，就是取消代理。

你运行regedit，按上面的路径找到目录，然后观察：

鼠标右键操作XX-Net的菜单，切换不同状态，看有没有立即更新对应的键值。
如果有更新，看看IE是否能够正常工作。

如果没有更新，那么用start.bat重新启动XX-Net，看看每次点击右键时，出现什么日志。

**Comment by xxnet** [comment]
很可能是IE没有立即生效，需要重启或等一会。
右键菜单修改的是注册表，当时IE不会实时的去更新注册表的信息。
  我试过重启IE就生效了。
  你试试看是不是这个规律
