### ISSUE TITLE
不能访问youtube，提示APPID 'xxx' not exists, remove it.

### ISSUE THREAD

**Issue by jamzhou** [XX-net/XX-Net#168]
已经配置了appid了，可是在访问youtube是，日志显示
[WARNING] APPID 'xxx' not exists, remove it.
No usable appid left, add new appid to continue use GoAgent

我想可能是我的app engine里用的GoAgent版本不同，想通过XX-Net进行部署服务端，但也是不成功。
提示502 URLFetch failed。
我切换为VPN，再部署，报404 No usable Appid Exists

看看app engine里，的确是有这个新建的application的，而且部署走的是vpn，并不是走xx-net的。

**Comment by xxnet** [comment]
先使用公共appid部署，再设置使用appid

2015-04-15 23:43 GMT-04:00 JamZhou <notifications@github.com>:

**Comment by jamzhou** [comment]
谢谢，清空了appid后，尝试部署，部署成功了。感谢
