### ISSUE TITLE
Google 搜索出现 Invalid Firebase Request

### ISSUE THREAD

**Issue by WDZThorn** [XX-net/XX-Net#1680]
使用 Google 搜索，间接性的出现 Invalid Firebase Request。

XX-Net 版本  2.8.2
通过 git pull 升级

请问各路大神怎么解决这个问题

**Comment by xxnet** [comment]
可能是混入了无效的ip，试试这个trunk的版本：
https://github.com/XX-net/XX-Net/archive/master.zip

在 2015年12月23日 上午11:07，per3evere <notifications@github.com>写道：

**Comment by WDZThorn** [comment]
@xxnet 好的，多谢！
