### ISSUE TITLE
建议appid no exists的朋友删除203.208开头的ip段以及可用ip

### ISSUE THREAD

**Issue by pnjgyl** [XX-net/XX-Net#1686]
刚刚发生的, 所有appid不可用导致xx-net不可用了. 
查询日志的确有203.208, ip段也有203.208, 并且, good_ip.txt前十个都是这个段的ip. 
1 在ip段中删除, 
2 good_ip.txt中删除
之后, 所有appid正常, xx-net正常

**Comment by xyuanmu** [comment]
这段中国的IP害人不浅啊，xx-net的IP段里是没有的，网上不少地方有，出问题的也都是用了网上的IP段。

**Comment by pnjgyl** [comment]
嗯, 因为贪多, 只想着尽可能多点ip段, 看到有人分享就会加进我的ip段里...

**Comment by jzp820927** [comment]
建议在xx中增加检测 203.208 IP段的代码，发现这个IP段，直接程序内部删除，避免自己导入的第三方IP库包含国内IP导致的错误。

**Comment by xxnet** [comment]
最新版已经有处理这类IP的机制了：

这些IP的证书的Google的，HTTP头的Server字段也是 Google FrontEnd，
但访问GAE时返回404，这种情况和appid 不存在一样。

遇到404时，会找一个确认存在的appid验证，确认是ip问题还是appid的问题。

**Comment by jzp820927** [comment]
新版有IP检测机制就太好了，程序越来越完善了，不错！
