### ISSUE TITLE
证书已经导入，访问google、youtube、facebook等网站都是不安全的连接

### ISSUE THREAD

**Issue by wandy-wang** [XX-net/XX-Net#169]
![google](https://cloud.githubusercontent.com/assets/11928043/7174008/81383cb6-e433-11e4-8084-3ec32034a02c.png)

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/issues/154

**Comment by wandy-wang** [comment]
![default](https://cloud.githubusercontent.com/assets/11928043/7174197/222e1846-e436-11e4-9c5c-50db88f96546.PNG)
版本信息
