### ISSUE TITLE
我的appid一配置就自动清空，麻烦帮忙看下什么问题

### ISSUE THREAD

**Issue by axml** [XX-net/XX-Net#1696]
之前一直用的很好，不知道为什么今天开始我发现无法正常翻墙了，然后去看了下xx-net的状态，发现appid消失了，然后我重新配置保存，也是无法配置上，麻烦帮忙看看。
我截了一段我觉得有问题的日志，是我添加appid，到appid被移除的过程。是不是我的appid被封了？
Dec 24 08:11:21 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Dec 24 08:11:21 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Dec 24 08:11:21 - [DEBUG] 59.18.34.52 close:no appid
Dec 24 08:11:21 - [DEBUG] 202.86.162.153 close:no appid
Dec 24 08:11:21 - [DEBUG] GAE_Exception 1 'no appid can use'
Dec 24 08:11:21 - [DEBUG] GAE_Exception 1 'no appid can use'
Dec 24 08:11:21 - [WARNING] gae_exception:GAE_Exception() https://www.youtube.com/user/DotaCinema/playlists?view=1&sort=lad&flow=grid
Dec 24 08:11:21 - [WARNING] gae_exception:GAE_Exception() https://www.youtube.com/favicon.ico
Dec 24 08:11:21 - [DEBUG] create_ssl update ip:59.18.44.220 time:89
Dec 24 08:11:21 - [DEBUG] create_ssl update ip:59.18.44.213 time:88
Dec 24 08:11:21 - [DEBUG] GAEProxy web_control 127.0.0.1:6583 POST /config?cmd=set_config
Dec 24 08:11:21 - [INFO] load google ip_list num:2111, gws num:2111
Dec 24 08:11:21 - [DEBUG] create_ssl update ip:1.255.22.211 time:118
Dec 24 08:11:22 - [DEBUG] get ip:59.18.44.213 t:90
Dec 24 08:11:22 - [DEBUG] get ip:59.18.44.220 t:90
Dec 24 08:11:22 - [DEBUG] get ip:58.176.217.5 t:97
Dec 24 08:11:22 - [DEBUG] get ip:59.18.34.52 t:98
Dec 24 08:11:23 - [DEBUG] get ip:121.78.74.83 t:101
Dec 24 08:11:23 - [DEBUG] get ip:121.78.71.122 t:101
Dec 24 08:11:23 - [DEBUG] get ip:202.86.162.153 t:101
Dec 24 08:11:23 - [DEBUG] get ip:1.255.22.207 t:105
Dec 24 08:11:23 - [DEBUG] create_ssl update ip:202.86.162.153 time:106
Dec 24 08:11:23 - [DEBUG] get ip:1.255.22.203 t:105
Dec 24 08:11:24 - [DEBUG] get ip:1.255.22.211 t:118
Dec 24 08:11:24 - [DEBUG] create_ssl update ip:1.255.22.203 time:114
Dec 24 08:11:24 - [DEBUG] create_ssl update ip:1.255.22.211 time:105
Dec 24 08:11:24 - [DEBUG] create_ssl update ip:1.255.22.207 time:105
Dec 24 08:11:24 - [DEBUG] create_ssl update ip:121.78.71.122 time:103
Dec 24 08:11:24 - [DEBUG]LOG_EXCEPT: create_ssl update ip:121.78.74.83 time:101, Except:[Errno 9] Bad file descriptor
Dec 24 08:11:25 - [DEBUG] create_ssl update ip:59.18.34.52 time:97
Dec 24 08:11:25 - [DEBUG] create_ssl update ip:58.176.217.5 time:100
Dec 24 08:11:25 - [DEBUG] create_ssl update ip:59.18.44.220 time:89
Dec 24 08:11:26 - [DEBUG] create_ssl update ip:59.18.44.213 time:90
Dec 24 08:11:26 - [WARNING] read request line empty
Dec 24 08:11:35 - [DEBUG] create ssl timeout fail.
Dec 24 08:11:35 - [DEBUG] create_ssl_connection fail
Dec 24 08:11:35 - [WARNING] fetch gae status:503 url:https://clients4.google.com/chrome-sync/experimentstatus
Dec 24 08:11:35 - [WARNING] APPID 'axmlsmartdrv' out of Quota, remove it.
Dec 24 08:11:35 - [DEBUG] 59.18.44.213 close:get_timeout
Dec 24 08:11:35 - [ERROR] No usable appid left, add new appid to continue use GAEProxy

**Comment by xxnet** [comment]
​你是什么版面？

appid不会被封。

可以测试2.8.3版本

**Comment by Dannywanxyz** [comment]
很明显你的appid已经超过一天10G的配额啦
![image](https://cloud.githubusercontent.com/assets/13790928/11988168/335f0d4e-aa26-11e5-832c-0e72094f4135.png)
，是不是你看视频太多啦？

**Comment by axml** [comment]
那可能是我开了全局挂着steam下载了巫师……这个是不是过一天就能恢复了？

**Comment by Dannywanxyz** [comment]
@axml 是的，不过你可以去多申请几个appid

**Comment by Dannywanxyz** [comment]
@axml 建议你迅速把这个issue关掉，因为你的一个appid已经暴露了，而xx-net中部署appid是不需要密码的

**Comment by xxnet** [comment]
​我觉得有必要讨论appid暴露的影响。
appid暴露可能的问题：
1. 别人用你appid的流量
  这种情况下多申请几个就好了，一般也没有多少人去用别人的流量
2. 网站有可能根据你的appid，和你在这里讨论的email帐号关联起来
  可能你的cookie/flash/webrtc会更容易暴露行踪。
  另外，GAE本身并不是一个好的匿名工具，要匿名还是用tor

有没有漏了什么？

**Comment by axml** [comment]
@Dannywanxyz @xxnet 
感谢你们的帮助

**Comment by panzer1313208** [comment]
部署之后就可以直接配置了。
