### ISSUE TITLE
Win8 start.lnk 开启即报错

### ISSUE THREAD

**Issue by qhfls** [XX-net/XX-Net#17]
双击start.lnk 后：
![2015-02-05_105118](https://cloud.githubusercontent.com/assets/721889/6054235/af40465c-ad25-11e4-93d5-104a70e641f9.png)
即使赋予start.lnk 管理员权限，依然会有这个提示
![2015-02-05_105050](https://cloud.githubusercontent.com/assets/721889/6054247/c67b4aa6-ad25-11e4-9ef7-a4cd5740dd4a.png)
调试：
尝试将python27目录放入C:\Windows\System32下
![2015-02-05_105202](https://cloud.githubusercontent.com/assets/721889/6054279/1179efd0-ad26-11e4-8c1f-5c2c12f24986.png)
继续运行start.lnk，显示：
![2015-02-05_105227](https://cloud.githubusercontent.com/assets/721889/6054285/227b7556-ad26-11e4-9bcd-d535501f3eeb.png)
![2015-02-05_105240](https://cloud.githubusercontent.com/assets/721889/6054294/3a11edb2-ad26-11e4-8197-705005c94406.png)
尝试将python27.dll注册到系统
![2015-02-05_105336](https://cloud.githubusercontent.com/assets/721889/6054301/4eb63fa2-ad26-11e4-8341-68fac82bbf10.png)
但是不成功：
![2015-02-05_105350](https://cloud.githubusercontent.com/assets/721889/6054308/5a6dca04-ad26-11e4-99b2-2210ad5e9568.png)
以上，请问如何解决？

PS：系统信息
![2015-02-05_110642](https://cloud.githubusercontent.com/assets/721889/6054363/188aaf8e-ad27-11e4-9a52-8d8702e6c509.png)

**Comment by xxnet** [comment]
非常棒非常详细的反馈。

Win8.1 还没有测试，先找win7试试能不能跑。
目前只测试了Xp和win7 x64，估计有些地方不一样，我要调试一下，你先试试兼容模式行不行.

**Comment by qhfls** [comment]
兼容模式依然不可以

**Comment by clyquan** [comment]
右键点击快捷方式，查看属性，将其目标位置修改到pythonw.exe所在位置，如:
"%windir%\system32\cmd.exe " /c start "" "D:\Program Files\XX-Net-1.0.6\python27\1.0\pythonw.exe" "D:\Program Files\XX-Net-1.0.6\launcher\start.py"

**Comment by xxnet** [comment]
试过Win8.1 没有重现你提到的现象，你换个电脑试试

**Comment by qhfls** [comment]
按照clyquan的方法解决了，谢谢！
2015-2-13 下午3:39于 "xxnet" <notifications@github.com>写道：

**Comment by xxnet** [comment]
增加了两种启动方式：
start.vbs
start.bat
总有一个是能用的，哈哈
