### ISSUE TITLE
自动升级有用吗？

### ISSUE THREAD

**Issue by szh7379** [XX-net/XX-Net#170]
update貌似是closed啊，更新这么频繁每次都下好麻烦

**Comment by xxnet** [comment]
有问题再去升级，没问题就不用升级了。

有问题的，提bug或则在响应bug后面跟贴，有修复我会回复、修改状态，你就会收到邮件通知

2015-04-16 0:48 GMT-04:00 irlJi <notifications@github.com>:

**Comment by szh7379** [comment]
看每次更新都有修复的啊，不更新不行啊，以前遇到都以为是自己的问题

**Comment by xxnet** [comment]
遇到问题可以看看github讨论区有没有相关讨论。
自己测试过后，也可以反馈相关问题讨论

2015-04-16 4:01 GMT-04:00 irlJi <notifications@github.com>:
