### ISSUE TITLE
关于新的状态信息显示

### ISSUE THREAD

**Issue by benpigchu** [XX-net/XX-Net#1701]
总觉得显示详细信息的按钮太过显眼，把按钮改成普通链接样式是不是会好一点？
另外希望在详细信息内容中也显示默认的状态信息，并且提供关闭详细信息的按钮
同时希望能在系统设置中加入“默认显示详细信息”的选项

**Comment by xxnet** [comment]
非常同意。

现在的视觉效果和细节都不够好，这个版本就是把最基本的思路给实现了。
谁来把这个干了

**Comment by panzer1313208** [comment]
哈哈

**Comment by benpigchu** [comment]
看来已经有人开始做了 #1721
