### ISSUE TITLE
今天google上不了

### ISSUE THREAD

**Issue by Ericwise** [XX-net/XX-Net#1703]
![Uploading 屏幕快照 2015-12-24 下午2.06.04.png…]()
连接超时

Dec 24 14:06:24.786 - [WARNING] fetch gae status:503 url:http://www.gstatic.com/generate_204
Dec 24 14:06:24.786 - [WARNING] APPID 'xxnet-72' out of Quota, remove it.
Dec 24 14:06:24.786 - [WARNING] report_out_of_quota:xxnet-72

**Comment by fredericky123** [comment]
意思是流量用完了 每个appid每天1G流量 设置你自己的appid 减少公共appid资源
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

**Comment by Ericwise** [comment]
'xxnet-72'这个ID要我手动删除吗？

**Comment by fredericky123** [comment]
其实没必要  今天流量没了 明天会恢复 不如按教程你去申请自己的appid 没人会和你一起用 每天流量也用不完 再也不会担心此类问题

**Comment by Ericwise** [comment]
OK
