### ISSUE TITLE
connected-link一直为0,0，偶尔跳到0,1

### ISSUE THREAD

**Issue by xEchox** [XX-net/XX-Net#1706]
-----------问题描述：
是局域网环境，跳到0,1不会超过最多不会超过5分钟，一般30s就又变回0,0了。

-----------诊断信息：
sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.7.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 2137,2137
connected-link: 0,0
ip-connect-interval: 10
scan-ip-thread-num: 38
ip-handshake-10: 149
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xEchox** [comment]
Dec 24 16:53:28 - [DEBUG] get ip:223.62.225.27 t:149
Dec 24 16:53:29 - [DEBUG] get ip:202.248.248.231 t:150
Dec 24 16:53:32 - [DEBUG] 203.66.124.224 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 203.217.98.120 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 210.242.127.31 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 210.61.221.164 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 119.149.188.117 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 1.255.22.229 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 210.61.221.113 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 203.217.98.95 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 202.224.62.82 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:32 - [DEBUG] 223.62.225.27 fail:GeneralProxyError()
Dec 24 16:53:32 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:33 - [DEBUG] 202.248.248.231 fail:GeneralProxyError()
Dec 24 16:53:33 - [DEBUG] report_connect_fail network fail
Dec 24 16:53:34 - [DEBUG] get ip:116.93.47.13 t:74
Dec 24 16:53:34 - [DEBUG] get ip:61.245.3.249 t:151
Dec 24 16:53:34 - [DEBUG] get ip:1.255.33.228 t:153
Dec 24 16:53:34 - [DEBUG] create ssl timeout fail.
Dec 24 16:53:34 - [DEBUG] create_ssl_connection fail
Dec 24 16:53:34 - [DEBUG] get ip:210.61.221.181 t:154
Dec 24 16:53:34 - [DEBUG] get ip:61.245.3.234 t:157
Dec 24 16:53:34 - [DEBUG] create ssl timeout fail.
Dec 24 16:53:34 - [DEBUG] create_ssl_connection fail

**Comment by xxnet** [comment]
你设置了局域网代理了吗？​

**Comment by xEchox** [comment]
设置了，服务器类型是HTTP

**Comment by xxnet** [comment]
​先确认你的局域网代理可用

日志提示的就是代理异常

**Comment by xEchox** [comment]
嗯嗯，我这边代理确实老抽风，如果是代理不稳定的话就没其他方法解决是吧？

**Comment by xxnet** [comment]
局域网代理是上网的基础

**Comment by jap33** [comment]
作为验证问题，你可以试试修改 gae_proxy/local/proxy.ini [google_ip] max_links_per_ip = 1 <---- 改为3 试试效果。报告大大改为3不会为0了。

**Comment by xEchox** [comment]
@jap33 我明天去公司试试的~

@xxnet 下午谷歌联不上的时候，我还在看其他网站，就是需要走局域网代理，但不用走GAEProxy代理的网站，这些网站能打开说明当时局域网代理是好的，为什么谷歌联不上报的是代理异常呢？

**Comment by xxnet** [comment]
​有可能是XXNet对你局域网代理的支持有问题，或者设置有问题，这个不好说，没有更详细的信息
