### ISSUE TITLE
HTTPS不是绿色的，而是个红叉

### ISSUE THREAD

**Issue by jzmswe** [XX-net/XX-Net#171]
在讨论区看到，有人说证书是自己制作的，不是信任机构的，还有人说是CHROME更新到最新版的问题，那我用最新版的CHROME加GoAgent，HTTPS就是绿色的，XX-Net和GoAgent证书都是自己制作的，为何GoAgent没问题。

**Comment by wandy-wang** [comment]
为何

**Comment by PaulUlrik** [comment]
小白同问。同时感谢作者，目前没什么大问题。不过貌似谷歌网盘无法上传文件，不过我几天没更新了，我试试最新版行不行。

**Comment by xxnet** [comment]
好的，我研究下GoAgent，看看是不是有什么地方不同

在 2015年4月16日 上午5:35，PaulUlrik <notifications@github.com>写道：

**Comment by koptomato** [comment]
登录ins啊推特什么的也是红的，有点强迫症就看着不舒服==，辛苦作者了！

**Comment by xxnet** [comment]
解决了，证书采用SHA256签名就好了。
新版1.8.11请测试

**Comment by koptomato** [comment]
直接安装data-goagent-ca吗
