### ISSUE TITLE
昨天x大在我屏幕上扔一只苍蝇（后在手机上查看原来是倒赞），今把我的集成版chrome-xx状态栏改一下，如图。以示报复！

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1712]
![sexsex](https://cloud.githubusercontent.com/assets/13328328/12000911/deddf02e-ab19-11e5-97ab-51cc2d54a3da.JPG)

**Comment by yeahwu** [comment]
额，忘了。“大家圣诞快乐！”

**Comment by xxnet** [comment]
后面改成：累死我了，终于爬出来了！

**Comment by yeahwu** [comment]
@xxnet  哎呀，你说的怎么这么有道理呢？这就去改。

**Comment by panzer1313208** [comment]
@yeahwu 倒赞在哪里？

**Comment by yeahwu** [comment]
@panzer1313208  #1688

**Comment by Cat7373** [comment]
噗噗噗噗噗

**Comment by yeahwu** [comment]
@Cat7373  笑嘛呢？综上所述，x大还是很有幽默细胞的。

**Comment by panzer1313208** [comment]
@yeahwu 👎

**Comment by yeahwu** [comment]
你看这像不像苍蝇？
![se](https://cloud.githubusercontent.com/assets/13328328/12003594/2004d5b8-ab60-11e5-8cab-4f534ed03328.JPG)

**Comment by panzer1313208** [comment]
没。。。

**Comment by panzer1313208** [comment]
![58ee3d6d55fbb2fbfbbe131a4f4a20a44623dc25](https://cloud.githubusercontent.com/assets/13449426/12004363/e351d79a-ab8e-11e5-9689-b690677423fa.jpg)
![500fd9f9d72a60596292d7c82e34349b023bba65](https://cloud.githubusercontent.com/assets/13449426/12004364/e388d66e-ab8e-11e5-820b-04bc9da52839.jpg)
![78310a55b319ebc43bae33ca8226cffc1f17168a](https://cloud.githubusercontent.com/assets/13449426/12004365/e3a9b53c-ab8e-11e5-8301-dc1ce2d35dc0.jpg)
![bd315c6034a85edf44e71f0849540923dd5475b6](https://cloud.githubusercontent.com/assets/13449426/12004366/e3acc7b8-ab8e-11e5-9136-bfe73e4ecef8.jpg)
![fd039245d688d43f7d34718f7d1ed21b0ef43b2a](https://cloud.githubusercontent.com/assets/13449426/12004367/e3b0804c-ab8e-11e5-98b8-a3ad1f2dbdca.jpg)

**Comment by yeahwu** [comment]
我竟无言以对。
panzer1313208 <notifications@github.com>于2015年12月26日 周六05:10写道：

**Comment by fuding** [comment]
还好吃过早餐才开的计算机

**Comment by noname007** [comment]
我擦。。。

panzer1313208 <notifications@github.com>于2015年12月26日周六 上午5:10写道：

> [image: 58ee3d6d55fbb2fbfbbe131a4f4a20a44623dc25]
> <https://cloud.githubusercontent.com/assets/13449426/12004363/e351d79a-ab8e-11e5-9689-b690677423fa.jpg>
> [image: 500fd9f9d72a60596292d7c82e34349b023bba65]
> <https://cloud.githubusercontent.com/assets/13449426/12004364/e388d66e-ab8e-11e5-820b-04bc9da52839.jpg>
> [image: 78310a55b319ebc43bae33ca8226cffc1f17168a]
> <https://cloud.githubusercontent.com/assets/13449426/12004365/e3a9b53c-ab8e-11e5-8301-dc1ce2d35dc0.jpg>
> [image: bd315c6034a85edf44e71f0849540923dd5475b6]
> <https://cloud.githubusercontent.com/assets/13449426/12004366/e3acc7b8-ab8e-11e5-9136-bfe73e4ecef8.jpg>
> [image: fd039245d688d43f7d34718f7d1ed21b0ef43b2a]
> <https://cloud.githubusercontent.com/assets/13449426/12004367/e3b0804c-ab8e-11e5-98b8-a3ad1f2dbdca.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/1712#issuecomment-167262689>.
>
-- 
yangzz

**Comment by panzer1313208** [comment]
@yeahwu 这才是真正的苍蝇和苍蝇幼崽也就是蛆

**Comment by lele2010lele** [comment]
你们这是要大吃一顿还是大吃一顿？
