### ISSUE TITLE
部分地方在英文语言下仍显示中文

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1713]
目前发现的有:
* 右上角的退出与自适应宽度的鼠标悬停提示
* 左上角的Logo的鼠标悬停提示

**Comment by yeahwu** [comment]
妹子，果然用心哪！赞赞赞
不要在意这些细节……
最后，圣诞快乐……

**Comment by Cat7373** [comment]
@yeahwu 
果然是用心啊，3分钟内回复。

**Comment by yeahwu** [comment]
人家说，这就是“爱”

**Comment by fuding** [comment]
谨慎围观

**Comment by xyuanmu** [comment]
tong wei guan

**Comment by yeahwu** [comment]
我和她是清白的，比白开水还白！😅😅
xyuanmu <notifications@github.com>于2015年12月25日 周五22:30写道：

**Comment by xyuanmu** [comment]
dong de

**Comment by yeahwu** [comment]
还是喜欢你这语言风格，犹抱琵琶半遮面的，看着挺风骚的。
xyuanmu <notifications@github.com>于2015年12月25日 周五22:41写道：

**Comment by simonasd** [comment]
@Cat7373 这两个地方我很早以前就改了，不过前段时间一忙就忘了提pull了。
