### ISSUE TITLE
2.8.4 能不能加个选项一打开就直接看详细信息

### ISSUE THREAD

**Issue by Rongronggg9** [XX-net/XX-Net#1718]
---

问题描述：
2.8.4
能不能加个选项一打开就直接看详细信息。
我又不需要看自检。

---

诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
xxnet-version: 2.8.4
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 495
network-status: OK
connected-link: 3 / 48
scan-ip-thread-num: 54
ip-quality: 162
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Rongronggg9** [comment]
或者把自检信息加到详细信息上方。
我这人比较喜欢数据。

**Comment by xxnet** [comment]
​支持，我也有这个需求，谁来做？

**Comment by Rongronggg9** [comment]
作者好幽默~

**Comment by linhua55** [comment]
这个是非必需的功能，如果只是个人的需要，建议自己修改提交，甚至可以实现实时绘图的功能，这样数据看起来更直观。
其实能用就行了，没必要盯着数据看。

**Comment by fuding** [comment]
@xxnet 能否在高级里增加一键检测所有appid。
appid太多了，都不知道有那几个是没部署的。

**Comment by yeahwu** [comment]
还好我不认识字，所以webui对我来说都是多余的。其实想想lantern那个模式还是挺好的

**Comment by xyuanmu** [comment]
我也挺想显示详细信息的，这是我修改的效果，如果还行就合并吧：https://github.com/XX-net/XX-Net/pull/1721
![status](https://cloud.githubusercontent.com/assets/12442896/12005011/8ed36420-abc2-11e5-9bee-8222d97cadeb.jpg)

**Comment by Rongronggg9** [comment]
甚善
