### ISSUE TITLE
能不能增加原版goagent自带的认证功能？

### ISSUE THREAD

**Issue by jzp820927** [XX-net/XX-Net#172]
[listen]
username = ×××
password = ×××

因为要给1，2个朋友使用，为了安全，需要认证功能，能不能给加上？

**Comment by xxnet** [comment]
暂时没有考虑这个特性。

主要考虑到CA证书需要导入，不适合分享给其他电脑使用。
建议每个电脑都跑一个XX-Net

2015-04-16 4:07 GMT-04:00 蒋志鹏 <notifications@github.com>:
