### ISSUE TITLE
Mac 10.11.2 ／2.8.5 無法掃描IP 無法保存 APP ID  然後提示APP ID無效 請部署

### ISSUE THREAD

**Issue by riumiyama** [XX-net/XX-Net#1724]
![2015-12-26 13 39 09](https://cloud.githubusercontent.com/assets/16426076/12005204/32d7ba90-abdb-11e5-8755-72c36ff12913.png)
![2015-12-26 14 05 21](https://cloud.githubusercontent.com/assets/16426076/12005200/ddff2288-abda-11e5-9d8b-93f116b81e25.png)

**Comment by riumiyama** [comment]
![Uploading スクリーンショット 2015-12-26 14.05.21.png…]()

**Comment by linhua55** [comment]
無法保存 APP ID？什么意思
需要root权限吗？ 写文件失败？

**Comment by riumiyama** [comment]
不知道 點了 沒有反應   我是管理員登陸的

**Comment by riumiyama** [comment]
![Uploading スクリーンショット 2015-12-26 13.46.10.png…]()
