### ISSUE TITLE
求助！Ubuntu下chromium无法访问国外站点，firefox可以

### ISSUE THREAD

**Issue by dengfengdecao** [XX-net/XX-Net#1725]
我是将系统代理改为自动，地址：http://127.0.0.1:8086/proxy.pac

chromium不能访问google、youtube等国外站点，但firefox却可以。

XX-Net Status：

sys-platform: x86_64, Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty
os-system: Linux
os-version: #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015
os-release: 3.19.0-25-generic
os-detail: Dist:Ubuntu; Version:14.04; ID:trusty
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36
xxnet-version: 2.7.3
python-version: 2.7.6

ipv6-status: 0
gws-ip-num: 113,81
connected-link: 7,50
scan-ip-thread-num: 50
ip-handshake-10: 196
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by riumiyama** [comment]
證書導入沒有 我好久都沒用過Ubuntu了 都忘記了

**Comment by zjhzxhz** [comment]
请给出启动时的Log :)

**Comment by dengfengdecao** [comment]
ok了，我重新配置了一遍。。。
