### ISSUE TITLE
连接VPN等操作后代理无法使用

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1727]
问题同之前的Issue
https://github.com/XX-net/XX-Net/issues/1422
https://github.com/XX-net/XX-Net/pull/1433

**Comment by xxnet** [comment]
​问题又出现了吗？

补丁都在吧

**Comment by riumiyama** [comment]
我是  運行xx-net(全局關閉)   就無法連結VPN、QQ 也出現 無法接收圖片 的情況 不知道是怎麼回事

**Comment by xxnet** [comment]
​@riumiyama
  打开IE的代理设置，看看代理是否真的关闭了

**Comment by Memorycn** [comment]
我也是@riumiyama 这种情况，打开xxnet之后貌似系统默认代理就变成xxnet了 Internet选项里关闭了代理 xxnet里也选择了全局关闭 但就是打不开网页（加载非常缓慢）  退出后一切正常了

**Comment by xxnet** [comment]
Internet选项里关闭了代理，请截图上来看看。

​另外看看GAE的日志，浏览器的请求是不是到了XX里了？

**Comment by Cat7373** [comment]
Jan 02 00:22:16.346 - [WARNING] socket accept fail(errno: 10022).
Jan 02 00:22:16.354 - [WARNING] socket accept fail(errno: 10022).
Jan 02 00:22:16.360 - [INFO] restart socket server.
Jan 02 00:22:16.363 - [INFO] restart socket server.
Jan 02 00:22:16.373 - [INFO] server 127.0.0.1:8085 started.
Jan 02 00:22:16.401 - [INFO] server 127.0.0.1:8087 started.

状态页的确是重启成功了，但是 8087 却没有效果，无法通过代理访问网页，XX-Net 也没收到新的代理请求。

**Comment by Cat7373** [comment]
浏览器代理设置也显示 Fail

**Comment by xxnet** [comment]
​检查了代码，布丁一直在，但估计上次整理代码时，留下了bug，刚修改了，请测试trunk上的版本

这个问题是在启用VPN之后，本地监听的端口accept会失效。
  修改的代码，在重启监听端口之后，把accept线程退出了。

**Comment by Cat7373** [comment]
仍然不行，但是不知为何，看起来 8085 的启动代码跟 8086、8087 并无区别，但 8085 一直没有什么问题，而 8086、8087 却不行。

**Comment by xxnet** [comment]
​恩，确实很奇怪，理论上说是没有差别才对

**Comment by Cat7373** [comment]
我将 296 行的注释取消了，在连接 VPN 后 8085、8086 就再也不会出现这个输出了。

**Comment by Cat7373** [comment]
同时还发现，只有 8086、8087 会出现这个输出，访问 8085 时并不会出现这个输出。

**Comment by Cat7373** [comment]
刚刚想用 burp 做测试。。。
发现以前的破解居然过期了。。。
真是耽误事。。。

**Comment by Cat7373** [comment]
8085 没有新输出的原因应该是 keep-alive 了。

**Comment by Cat7373** [comment]
隐身模式发现，8085同样无法访问。

**Comment by Cat7373** [comment]
问题解决了。。。
稍后Pull
