### ISSUE TITLE
无法访问设置页面

### ISSUE THREAD

**Issue by httpe** [XX-net/XX-Net#173]
Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
3.19.3-3-ARCH
Archlinux, firefox, 使用Foxyproxy作为代理设置插件
设置代理为127.0.0.1:8087并设置不代理内部网络
但是如果访问设置页面（127.0.0.1:8085)的话，就会弹出如下文字：
Message From FetchServer
    Now you can visit some websites
    google.com
    mail.google.com

看起来是是相当于直接访问了goagent？
关掉代理则可以访问设置页面，这是什么原因呢？

日志中出现了：
Apr 17 08:43:16 - [WARNING] gae_handler err:error(32, 'Broken pipe') http://127.0.0.1:8084/status 
Apr 17 08:43:18 - [WARNING] APPID error:400 url:http://127.0.0.1:8085/

**Comment by Cat7373** [comment]
看起来似乎是你的代理设置失误导致的- -

**Comment by xxnet** [comment]
恩，“不代理内部网络”，没有起效果，你摸索看看要不要把8085/8084/8083端口加到127.0.0.1后面。
可以先试试127.0.0.1:8085

**Comment by httpe** [comment]
我这里添加了127.0.0.1：8085为黑名单还是不行…是代理插件的bug?
________________________________
发件人: xxnet<mailto:notifications@github.com>
发送时间: ‎2015/‎4/‎17 10:08
收件人: XX-net/XX-Net<mailto:XX-Net@noreply.github.com>
抄送: httpe<mailto:httpe@live.jp>
主题: Re: [XX-Net] 无法访问设置页面 (#173)

恩，“不代理内部网络”，没有起效果，你摸索看看要不要把8085/8084/8083端口加到127.0.0.1后面。
可以先试试127.0.0.1:8085

---

**Comment by httpe** [comment]
我貌似找到原因了：
https://getfoxyproxy.org/downloads.html
免费版（standard）竟然不支持“Proxy switching by local IP address”
直接使用firefox的代理设置没有发现上述问题。
