### ISSUE TITLE
XX-net如何更新，每次都要重新部署appid吗

### ISSUE THREAD

**Issue by wandy-wang** [XX-net/XX-Net#174]

**Comment by wandy-wang** [comment]
可以下载解压后与之前的文件夹合并吗

**Comment by Cat7373** [comment]
史上最最最最最简单的办法
删掉旧的 然后解压新的
打开Web配置页面
把appid跟密码填进去即可

**Comment by imhentai** [comment]
直接解压，然后覆盖就行了

**Comment by PaulUlrik** [comment]
嗯？难道删掉旧的之后不用再部署了吗？

**Comment by xxnet** [comment]
部署是服务端的操作，本地删除不影响服务端，因此，删除旧的，不必重新部署

2015-04-17 3:36 GMT-04:00 PaulUlrik <notifications@github.com>:

**Comment by streamgo** [comment]
覆盖原目录文件，或者删除原目录文件后解压文件，再重新填写APPID。这两种我都测试过，基本都使用正常的。

**Comment by PaulUlrik** [comment]
哦哦，那照这样来说，别人如果知道我的appid，只要我部署过了他们可以不用部署直接用我的id了对吧？

**Comment by Cat7373** [comment]
是这样的
我就做了一个 部署好之后压缩掉
然后发给几个朋友一起用
