### ISSUE TITLE
泥萌见过像 QQ 空间一样的 Issues 么？

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1754]
https://github.com/drduan/minggeJS/issues

感觉好有趣0.0

@yeahwu 

真的是我输了... 这货居然编辑我的回复↓
https://github.com/drduan/minggeJS/issues/201#issuecomment-167603202

好有趣的小工具↓
http://www.minggejs.org/mingge.html

**Comment by riumiyama** [comment]
噗 城裏人好會玩

**Comment by yeahwu** [comment]
为毛@我？搞得就像我是城里人似的！
你们城里人真会玩，连QQ空间这么高大上的东西都知道！为什么没有人告诉俺？
另外听说，QQ空间女不愁嫁，😄😄
riumiyama <notifications@github.com>于2015年12月29日 周二01:08写道：

**Comment by XadillaX** [comment]
从明哥空降过来😂

**Comment by hheedat** [comment]
明嫂好

**Comment by ming-ge** [comment]
老实说我从来没用过XX-Net，正因为我反感XX-Net。
为什么我反感，因为我完全有开发XX-Net的能力，XX-Net的底层我都了如指掌。
虽说我反感XX-Net，但是XX-Net却在测试界占有大量的用户份额，
之后我有个想法，不如重新开发一个属于自己思想，自己架构的XX-Net。
我给了他一个霸气的名字：MingGeXX-Net，
它的名字叫MingGeXX-Net，MingGe就是我的大名，一看到XX-Net名字，
就知道作者是我，知道它是国产的，让别人知道国产XX-Net一样做得很出色，出众。
我是MingGe，请支持国产minggeXX-Net，因为我们都是中国人。

**Comment by fuding** [comment]
：~）哈哈哈

**Comment by xyuanmu** [comment]
QQ空间是什么？

**Comment by yeahwu** [comment]
听说可以约到炮，谁tm带路。哥憋不住了😅
xyuanmu <notifications@github.com>于2015年12月29日 周二11:06写道：

**Comment by yeahwu** [comment]
话说明嫂，该你上场鸟。
Yeah Wu <wujiayu02@gmail.com>于2015年12月29日 周二11:09写道：

**Comment by CaoPeng** [comment]
这我也是醉了。。

**Comment by fengchang** [comment]
好有趣的小工具<----现在的猎头也是蛮拼的

**Comment by simonasd** [comment]
@Cat7373 有一种贵圈真乱的感觉。

**Comment by zhangchp** [comment]
贵圈真乱。。。
