### ISSUE TITLE
SwitchyOmega/wip.log 有何用呢?

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1759]
如题- -

**Comment by yeahwu** [comment]
俺不会告诉你，卵用没有。因为那样显得俺很没素质！

**Comment by panzer1313208** [comment]
呵呵，我只能告诉你，我没有SwitchyOmega，xxnet就不能用。

**Comment by panzer1313208** [comment]
@Cat7373 @yeahwu

**Comment by panzer1313208** [comment]
![m14 x71 s1gvbnw4 7t1r 1](https://cloud.githubusercontent.com/assets/13449426/12035518/a3be6174-ae78-11e5-836f-983180a0b184.png)

**Comment by panzer1313208** [comment]
根本不能切换。点了没反映。

**Comment by panzer1313208** [comment]
所以我如果没有SwitchyOmega，就不能用，当然了我可以从IE里设置全局，但是如果设置全局，那我还不如去用SS和VPN。

**Comment by yeahwu** [comment]
大哥，明嫂说的是wip.log 这个文件，你倒是说说这个文件有什么用？

**Comment by Cat7373** [comment]
明嫂什么鬼

**Comment by yeahwu** [comment]
大家不都这样喊你吗？汗

**Comment by panzer1313208** [comment]
@yeahwu wip.log是什么？
