### ISSUE TITLE
2.8.4 一直挂着不用，appid 的流量被自动耗光

### ISSUE THREAD

**Issue by zhuweijing** [XX-net/XX-Net#1766]
2.8.4 一直挂着不用，9 个 appid 的流量都被自动耗光了，
一开始是可以用的，每次挂的时间长了，流量就没了，
[WARNING] all appid out of quota, need 10 min to reset.

**Comment by xxnet** [comment]
​有开着浏览器吗？

开着浏览器，就会持续去keep alive，会消耗GAE的请求次数配额

**Comment by zhuweijing** [comment]
嗯，这个没有，我的 appid 是使用 goagent 2.3.2 部署上去的 ， 我刚试了一下，用回 goagent 2.3.2, ，goagent 可以用，不知道是不是配额恢复了， XX-Net 刚升级到了 2.8.9,

**Comment by zhuweijing** [comment]
不好意思，刚登录 appengine.google.com 确认了，全部 over quota, 用 goagent 那会一下行了，后面不行了，可能是浏览器的缓存？  GAE 有请求次数配额，我以为只是流量配额，长知识了 ^_^,  我昨晚好像的确开着浏览器，但没有打开国外网站，使用的是 firefox + foxyproxy standard, 使用基于其预定义模板的代理服务器.

**Comment by Cat7373** [comment]
自己部署了25个APPID...
从未耗光过- -

**Comment by CaoPeng** [comment]
个人电脑 win 3个
个人电脑Linux 3 个
工作电脑 3个  --> 下载了2G的youtube视频

流量貌似没耗光啊。

**Comment by zhuweijing** [comment]
嗯，我的好多次被耗光了，24 小时挂着的， 但并不是24小时打开浏览器在上网，我先观察和测试多几个版本再报告一下。

**Comment by liumuqi** [comment]
你开浏览器 是不是没有用switchyomega 插件，如果是 访问的所有 网页上的 请求会全部走 gae, 现在网页中的请求 会很多 ，还有
定时发送的，建议使用插件判断哪些网页不需要翻墙

2015-12-30 11:15 GMT+08:00 zhuweijing <notifications@github.com>:

**Comment by Ericwise** [comment]
对的，switchyomega 插件会区分是直连还是走代理

**Comment by zhuweijing** [comment]
![qq 20151230140525](https://cloud.githubusercontent.com/assets/8622390/12046987/8de41fe8-aefe-11e5-8c66-17eb4539cd9b.png)
我用的是这个，然后选择的 
![qq 20151230140725](https://cloud.githubusercontent.com/assets/8622390/12046992/ae783316-aefe-11e5-9fde-f7356a7fc687.png)
这样会区分直连还是走代理吗?  因为我这样子，访问国内网站是很快的，而且配额用完后，也是可以访问国内网站。

**Comment by zhuweijing** [comment]
挂着不怎么用，还是会被耗光 
![Uploading QQ截图20160104145218.png…](

**Comment by zhuweijing** [comment]
![Uploading QQ截图20160104145218.png…]()
还是会被耗光

**Comment by simonasd** [comment]
@zhuweijing 根据上图中的设置，你的浏览器会根据gfwlist来决定直连还是走代理。因此就像你说的一样，国内网站可以始终正常访问。

Github上传图片的问题，根据

><pre>[Uploading QQ截图20160104145218.png…]()</pre>

这条可以看出，你的图片正在上传，还没有传输完毕（也可能是上传出错了）。

**Comment by zhuweijing** [comment]
现在使用 XX-Net 重新部署 appid ，目前使用一天，正常，测试两天，应该可以关掉这个问题了，感谢作者，和各位贡献的大侠

**Comment by zhuweijing** [comment]
重新部署 appid 后，测试两天，正常。

**Comment by Cat7373** [comment]
@zhuweijing 
想了想可能是 XX-Net 测试网络时的代码的问题，XX-Net 的服务端自动过滤了这种请求，Goagent 却没有，所以出的这种问题吧。。。
没仔细看过这部分代码- -
只是个人猜测- -
