### ISSUE TITLE
"'module' object has no attribute 'load_sock'"

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#1767]
设置appid的时候，单击保存，提示发生未知错误。错误具体信息如题。

**Comment by xxnet** [comment]
​把状态页和日志贴出来

**Comment by zjhzxhz** [comment]
这……… 不是我的电脑~
电脑现在在实验室，更关键的是我直接该配置文件搞定了。
但是改配置文件的时候发现配置文件已经被程序设置了。
情况就是这么个情况，你看着办吧(笑)
