### ISSUE TITLE
能不能把托盘图标改成白底的……

### ISSUE THREAD

**Issue by httpe** [XX-net/XX-Net#177]
目前的托盘图标貌似是透明底色的？
在黑色背景的系统托盘下根本看不到图标……
所以求改个白色背景……

**Comment by evilstyle** [comment]
小图标直接用 python的图标吧。

**Comment by xxnet** [comment]
已经有twitter网友贡献了图标，一直忙于修复bug，下周我把图标换上。

2015-04-18 5:11 GMT-04:00 evilstyle <notifications@github.com>:

**Comment by xxnet** [comment]
新版换上了，两种颜色，应该好了。
不过浏览器需要大清理缓存，才能刷新网页的图标。
