### ISSUE TITLE
兄弟们，出来吹牛逼了！另外奉送福利一枚。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1777]
火狐43集成tor前置lantern。1：优化tor链路缺省。2：去除CNNIC证书。3：浏览器关闭RTC。4：更改默认搜索为DuckDuckGo。5：内置Everywhere安全插件。6：lantern最新源码编译。
项目地址：https://github.com/yeahwu/firefox-tor

**Comment by Cat7373** [comment]
前排沙发#1777

**Comment by yeahwu** [comment]
妹子，听说你变心了？我这心碎得不要、不要的

**Comment by simear2004** [comment]
楼主，你这么骚你老婆知道吗？

**Comment by yeahwu** [comment]
汗，你不说我老婆怎么知道？现在大概知道鸟。

**Comment by yeahwu** [comment]
@simear2004  你就这么确定我是个大老爷们？孩子呀，你还是太年轻！

**Comment by yeahwu** [comment]
匿名三部曲：蹭网，变性，tor……其他的，不解释。

**Comment by TonnyTonny** [comment]
感謝更新

**Comment by yeahwu** [comment]
@TonnyTonny  不客气！:blush::blush:

**Comment by Cat7373** [comment]
@yeahwu 
妹纸晚上好！

**Comment by yeahwu** [comment]
@Cat7373  亲，晚上好。约吗？

**Comment by Cat7373** [comment]
@yeahwu 
百合么？~

**Comment by yeahwu** [comment]
@Cat7373 我只听说过“野合”，百合又是什么玩意？你们城里人真会玩！不要引诱我哦，最近在看《Femme Fatales》，禁不起诱惑。

**Comment by xyuanmu** [comment]
进来就闻到百合花香，醉一个，话说今晚跨年。

**Comment by yeahwu** [comment]
@xyuanmu 腿太长，怕一下跨到2018，哈哈

**Comment by xyuanmu** [comment]
@yeahwu 嗯，一起迈向2018

**Comment by fuding** [comment]
百合现场 ~o~

**Comment by yeahwu** [comment]
看来大家都在等待2016的到来呀。
