### ISSUE TITLE
已经部署自己的ID, 仍出现‘共用appid因为资源有限’的问题

### ISSUE THREAD

**Issue by bluepp** [XX-net/XX-Net#178]
GoAgent状态信息
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.3.1
Launcher Version	1.0.5
GoAgent Version	3.1.38
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
GAE appid	bluepp|
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	3710
---------------------------------------------------------------------

已经部署自己的ID，但是仍然出现‘共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问，请使用自己的appid’这个message,何故？

**Comment by yfdyh000** [comment]
似乎多了一个竖线？

2015-04-18 0:33 GMT+08:00 bluepp <notifications@github.com>:

> GoAgent状态信息
> Property Value
> Sys Platform win32
> OS System Windows
> OS version 6.2.9200
> OS release 8
> OS detail Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0;
> Suite:768; ProductType:0
> architecture 32bitWindowsPE
> Browser Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/41.0.2272.118 Safari/537.36
> XX-Net Version 1.3.1
> Launcher Version 1.0.5
> GoAgent Version 3.1.38
> Python Version 2.7.9
> Proxy Listen 127.0.0.1:8087
> GAE appid bluepp|
> PAC URL http://127.0.0.1:8086/proxy.pac
> Google IP 3710
>
>
> 已经部署自己的ID，但是仍然出现‘共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问，请使用自己的appid’这个message,何故？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/178>.
>



-- 
Best regards,
YFdyh000.

**Comment by xxnet** [comment]
请升级新版

2015-04-17 13:32 GMT-04:00 YFdyh000 <notifications@github.com>:
