### ISSUE TITLE
强迫症问题

### ISSUE THREAD

**Issue by Rongronggg9** [XX-net/XX-Net#1780]
状态页
-
Appid

属性	值
当前工作AppID	
-
看！
"Appid"和"AppID"大小写不一致

**Comment by xyuanmu** [comment]
额，上面的id还没长大，没长大

**Comment by yeahwu** [comment]
是d没长大，dd没长大，别多想，就是个小dd。

**Comment by riumiyama** [comment]
D cup

**Comment by Rongronggg9** [comment]
你们……

**Comment by riumiyama** [comment]
@Rongronggg9  頭像很可愛 栗山未来可愛いねー(≧▽≦)

**Comment by Rongronggg9** [comment]
＠riumiyama ありがとうございます。
