### ISSUE TITLE
为何IP会大量减少呢?

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1781]
我是从很久之前就开始扫的 IP，更新都是手动下载更新包然后复制 data 文件夹而不是用自动更新。
最近发现更新后过几个小时、或者一两天，一开始的 460 个 IP 就会掉到 300 个左右。
最初发现后我都是重新复制原来的 data 文件夹解决，后来发现还是会掉。
不知是因为Bug丢IP，还是因为一些以前的 IP 时间过于久远失效了而被自动删除呢？
以及，在 IP 数量没有达到上限时，在什么情况下才会删除 IP？

**Comment by cobob** [comment]
IP一直在更新，因为很多IP随时都会失效。

**Comment by Cat7373** [comment]
也就是说，即使 IP 没有到达 IP 上限，失效的 IP 也会被删除么？

**Comment by Lrevor** [comment]
IP并没有删除，因为状态页显示的是"好IP"，就是good_ip.txt里末尾是0的IP

**Comment by Cat7373** [comment]
但是其实我看到 IP 保存的文件变小了- -

**Comment by Lrevor** [comment]
哦，是吗，我现在扫到6600多个IP了，一直都没发现这问题。。。

**Comment by linhua55** [comment]
@Cat7373 
可以在更新前备份一下，然后觉察到奇怪的问题出现后，再备份一下。
vim diff  这两个备份

**Comment by Cat7373** [comment]
有空我筛选下被删掉的 IP，看看是不是都是失效的吧- -

**Comment by Cat7373** [comment]
这里是筛选出来的一份被删除的 IP 列表，经过测试有不少甚至延迟都小于 100ms，只有少数几个是失效的。@xx-net
1.255.22.134,1.255.22.166,1.9.131.70,101.78.13.33,103.11.28.101,103.11.28.104,103.11.28.106,103.11.28.108,103.11.28.110,103.11.28.120,103.11.28.123,103.11.28.145,103.11.28.147,103.11.28.150,103.11.28.160,103.11.28.164,103.11.28.172,103.11.28.183,103.11.28.210,103.11.28.22,103.11.28.235,103.11.28.241,103.11.28.244,103.11.28.245,103.11.28.47,103.11.28.68,103.11.28.76,103.11.28.83,103.11.28.92,103.11.28.94,103.11.30.4,103.11.30.52,109.95.77.107,109.95.77.88,115.178.26.4,115.254.97.9,118.98.106.132,118.98.106.197,118.98.106.200,118.98.106.201,118.98.106.71,118.98.111.135,118.98.111.68,118.98.111.75,118.98.30.73,118.98.36.132,118.98.36.137,118.98.76.68,121.78.52.92,121.78.74.70,150.199.24.170,175.28.1.153,177.71.7.217,177.71.7.228,178.45.251.116,178.45.251.117,178.45.251.74,178.45.251.82,179.124.138.5,179.96.24.165,181.198.79.160,181.198.80.119,181.47.248.211,181.48.252.56,182.176.130.24,182.176.130.39,182.176.130.40,182.176.130.59,185.1.11.140,185.1.11.143,185.1.11.144,185.1.11.146,185.1.11.153,185.1.11.163,185.1.11.179,186.160.223.50,186.178.0.180,187.110.238.82,187.110.64.172,187.17.155.118,188.21.9.137,188.21.9.139,188.21.9.202,188.21.9.203,189.124.133.161,189.215.200.12,189.215.200.13,189.215.200.15,189.215.200.18,189.215.200.26,189.215.200.31,189.215.200.36,189.215.200.41,189.215.200.42,189.215.200.43,189.215.200.57,189.215.200.58,189.215.200.7,189.247.138.68,190.122.100.212,190.150.50.92,191.251.128.11,193.134.255.162,193.134.255.89,193.90.147.29,193.90.147.36,193.90.147.43,193.90.147.44,193.95.12.171,193.95.12.173,195.22.207.5,195.78.217.54,198.142.187.138,198.142.187.41,198.70.68.201,198.70.69.68,200.108.53.59,200.28.0.11,200.31.96.243,200.55.230.114,200.77.168.14,200.77.168.174,201.157.30.53,202.248.151.40,202.248.151.54,202.78.113.101,202.86.162.162,202.86.162.178,202.86.162.182,203.139.206.26,203.176.178.25,203.176.178.27,203.176.178.34,203.176.178.36,203.176.178.40,203.176.178.47,203.176.178.50,203.211.8.55,203.233.126.197,207.249.186.108,208.73.255.174,210.187.25.198,210.253.46.118,210.253.46.92,211.124.13.136,212.0.195.168,213.163.23.71,213.163.23.93,24.100.187.133,27.121.46.213,27.121.51.106,27.121.51.123,31.55.163.235,41.206.96.125,42.112.8.74,42.112.9.136,46.238.143.42,49.231.60.216,49.98.25.5,58.145.238.43,58.145.238.6,58.27.27.197,59.18.34.183,59.18.34.96,59.18.44.35,62.1.38.77,62.75.10.99,64.15.121.12,64.53.1.111,66.185.95.53,67.218.93.135,67.218.93.158,67.218.93.179,69.65.64.111,69.65.64.88,78.11.253.206,78.11.253.209,78.11.253.222,78.11.253.225,78.11.253.230,78.11.253.233,78.11.253.244,80.202.12.143,80.202.12.149,80.202.12.170,85.187.222.45,89.201.175.184,91.205.69.46

**Comment by Cat7373** [comment]
补一份原始数据（换行分割）
1.255.22.134
1.255.22.166
1.9.131.70
101.78.13.33
103.11.28.101
103.11.28.104
103.11.28.106
103.11.28.108
103.11.28.110
103.11.28.120
103.11.28.123
103.11.28.145
103.11.28.147
103.11.28.150
103.11.28.160
103.11.28.164
103.11.28.172
103.11.28.183
103.11.28.210
103.11.28.22
103.11.28.235
103.11.28.241
103.11.28.244
103.11.28.245
103.11.28.47
103.11.28.68
103.11.28.76
103.11.28.83
103.11.28.92
103.11.28.94
103.11.30.4
103.11.30.52
109.95.77.107
109.95.77.88
115.178.26.4
115.254.97.9
118.98.106.132
118.98.106.197
118.98.106.200
118.98.106.201
118.98.106.71
118.98.111.135
118.98.111.68
118.98.111.75
118.98.30.73
118.98.36.132
118.98.36.137
118.98.76.68
121.78.52.92
121.78.74.70
150.199.24.170
175.28.1.153
177.71.7.217
177.71.7.228
178.45.251.116
178.45.251.117
178.45.251.74
178.45.251.82
179.124.138.5
179.96.24.165
181.198.79.160
181.198.80.119
181.47.248.211
181.48.252.56
182.176.130.24
182.176.130.39
182.176.130.40
182.176.130.59
185.1.11.140
185.1.11.143
185.1.11.144
185.1.11.146
185.1.11.153
185.1.11.163
185.1.11.179
186.160.223.50
186.178.0.180
187.110.238.82
187.110.64.172
187.17.155.118
188.21.9.137
188.21.9.139
188.21.9.202
188.21.9.203
189.124.133.161
189.215.200.12
189.215.200.13
189.215.200.15
189.215.200.18
189.215.200.26
189.215.200.31
189.215.200.36
189.215.200.41
189.215.200.42
189.215.200.43
189.215.200.57
189.215.200.58
189.215.200.7
189.247.138.68
190.122.100.212
190.150.50.92
191.251.128.11
193.134.255.162
193.134.255.89
193.90.147.29
193.90.147.36
193.90.147.43
193.90.147.44
193.95.12.171
193.95.12.173
195.22.207.5
195.78.217.54
198.142.187.138
198.142.187.41
198.70.68.201
198.70.69.68
200.108.53.59
200.28.0.11
200.31.96.243
200.55.230.114
200.77.168.14
200.77.168.174
201.157.30.53
202.248.151.40
202.248.151.54
202.78.113.101
202.86.162.162
202.86.162.178
202.86.162.182
203.139.206.26
203.176.178.25
203.176.178.27
203.176.178.34
203.176.178.36
203.176.178.40
203.176.178.47
203.176.178.50
203.211.8.55
203.233.126.197
207.249.186.108
208.73.255.174
210.187.25.198
210.253.46.118
210.253.46.92
211.124.13.136
212.0.195.168
213.163.23.71
213.163.23.93
24.100.187.133
27.121.46.213
27.121.51.106
27.121.51.123
31.55.163.235
41.206.96.125
42.112.8.74
42.112.9.136
46.238.143.42
49.231.60.216
49.98.25.5
58.145.238.43
58.145.238.6
58.27.27.197
59.18.34.183
59.18.34.96
59.18.44.35
62.1.38.77
62.75.10.99
64.15.121.12
64.53.1.111
66.185.95.53
67.218.93.135
67.218.93.158
67.218.93.179
69.65.64.111
69.65.64.88
78.11.253.206
78.11.253.209
78.11.253.222
78.11.253.225
78.11.253.230
78.11.253.233
78.11.253.244
80.202.12.143
80.202.12.149
80.202.12.170
85.187.222.45
89.201.175.184
91.205.69.46

**Comment by matrixirtam** [comment]
版本多少啊 貌似最新2.8.9还可以 一直稳定增加中

**Comment by xxnet** [comment]
@​Cat

   你测试用的哪个 版本？
   前面的测试版本有这个bug，最新2.8.9应该好了

**Comment by Cat7373** [comment]
2.8.8复制过来的ip列表
2.8.9仍出现减少问题
之前几个版本也有这种情况

**Comment by xxnet** [comment]
​@Cat 把日志贴出来看看

**Comment by Cat7373** [comment]
我又不知道是什么时候丢的 IP。。。

**Comment by Cat7373** [comment]
我的意思是，XX-Net 在 IP 库没满的时候，什么情况下才会删除 IP？

**Comment by linhua55** [comment]
@Cat7373 
推荐用git进行更新，简单方便
1、git clone  xxx
2、复制原来的data文件夹
3、修改完自己的appid后，git add . && git commit 
4、更新用  git pull --rebase origin master

**Comment by xxnet** [comment]
​@Cat
现在不会删除ip，直到3000个。
现在感觉不需要保持那么多，1000个就差不多了吧。

这个数字属于底层算法的一部分，用户不必太关注，相对有意义的是有效Ip数

**Comment by Cat7373** [comment]
刚刚又成功触发了一次删除 IP 的问题，亲眼看着 IP 库文件从 1135 行掉到1080行，出现问题之前控制台里曾抛了个错误，结果我把控制台关了去日志文件里找，却没找到这个错误。。。。

**Comment by xxnet** [comment]
​考虑到隐私问题（GAE日志中有访问url），默认是没有开启GAE日志文件的。

你用的是哪个版本？

**Comment by Cat7373** [comment]
2.8.9
还是没搞明白触发方式。。。
只知道触发一次会瞬间少几十个 ip

**Comment by xxnet** [comment]
​你拔掉网线试试

目前设计，连续10个ip连接失败，就会开始探测网络可用性。
所以瞬间损失10个ip，而后会恢复回来的。

你可以创建一个data/gae_proxy/manual.ini
=============
[system]
log_file = 1
=============
来启用gae_proxy的日志

**Comment by Cat7373** [comment]
我是说存ip的文件里的ip少了。。。

**Comment by xxnet** [comment]
​查看源码，分析有可能的地方是认为ip不是google ip，而批量丢失很可能在批量下载的时候。

你把gae_proxy的日志文件启动起来，下次发现可以从日志中找原因

**Comment by Cat7373** [comment]
通过查看日志发现，是 google_ip.py 的 report_connect_fail 函数删除的 IP，触发时删除速度大概 1 秒 2 个 IP。

**Comment by Cat7373** [comment]
Jan 02 12:58:17.575 - [WARNING] IP:188.43.64.237 not support GAE, server type:GSE status:404
Jan 02 12:58:17.576 - [INFO] remove ip:188.43.64.237 left amount:1010 gws_num:1010

**Comment by Cat7373** [comment]
就是说，被删除的 IP 都是不支持 GAE 模式的么？

**Comment by linhua55** [comment]
>Jan 02 12:58:27.386 - [WARNING] IP:213.153.32.68 not support GAE, server type:GSE status:404
这个ip支持GAE呀

    ➜   curl -k  --resolve xxnet-13.appspot.com:443:213.153.32.68 https://xxnet-13.appspot.com/_gh/ --ciphers ECDHE-RSA-AES128-SHA
>GoAgent Python Server 3.2.0 works, deployed at 2015-03-28 08:15:22

**Comment by lele2010lele** [comment]
纯技术讨论，无法插话，看xx大神和cat如何带来福利

**Comment by Cat7373** [comment]
@xxnet 快速掉 IP 录像，最后还抛了个错- -
https://github.com/Cat7373/tmps/blob/master/xxnet.mp4

[使用的这个版本](https://github.com/XX-net/XX-Net/commit/0fd20cf84b2efe379fa15092519ebff9f2246975)

**Comment by Cat7373** [comment]
轻轻松松的掉到273个IP了0.0

**Comment by jzp820927** [comment]
我去，这IP掉的速度，可以赶上秒表了。。。

**Comment by Cat7373** [comment]
对了，录像的时候刚好在用工具下载东西，几乎占满了带宽。

**Comment by Cat7373** [comment]
网络状态一会unknow一会ok的

**Comment by linhua55** [comment]
@Cat7373 
https://github.com/XX-net/XX-Net/issues/3120#issuecomment-215940542
