### ISSUE TITLE
CentOS 下出现这个错误

### ISSUE THREAD

**Issue by s5248** [XX-net/XX-Net#1784]
sudo sh -x start.sh 
++ dirname start.sh
\+ SCRIPTPATH=.
\+ cd .
\+ hash python2
\+ python2 launcher/start.py
Jan  1 18:23:59 - [INFO] start XX-Net 2.7.3
Jan  1 18:23:59 - [DEBUG] start confirm_xxnet_exit
Jan  1 18:23:59 - [DEBUG] good, xxnet:8087 cleared!
Jan  1 18:23:59 - [DEBUG] good, xxnet:8085 clear!
Jan  1 18:23:59 - [DEBUG] finished confirm_xxnet_exit
Jan  1 18:23:59 - [ERROR] start module gae_proxy fail:invalid syntax (socks.py, line 213)
Traceback (most recent call last):
  File "/root/Downloads/XX-Net-master/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/root/Downloads/XX-Net-master/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/root/Downloads/XX-Net-master/gae_proxy/local/proxy.py", line 81, in <module>
    import proxy_handler
  File "/root/Downloads/XX-Net-master/gae_proxy/local/proxy_handler.py", line 13, in <module>
    from connect_manager import https_manager,forwork_manager
  File "/root/Downloads/XX-Net-master/gae_proxy/local/connect_manager.py", line 17, in <module>
    import socks
  File "/root/Downloads/XX-Net-master/python27/1.0/lib/noarch/socks.py", line 213
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

Jan  1 18:23:59 - [INFO] start gae_proxy time cost 15
Jan  1 18:23:59 - [INFO] begin to start web control
Jan  1 18:23:59 - [INFO] launcher web control started.
Jan  1 18:24:00 - [WARNING] request module:gae_proxy start fail
Jan  1 18:24:00 - [WARNING] request module:gae_proxy start fail
Jan  1 18:24:01 - [WARNING] request module:gae_proxy start fail
Jan  1 18:24:01 - [WARNING] request module:gae_proxy start fail
Jan  1 18:24:01 - [INFO] get uuid:7ebd3898-c9e3-469d-83e5-431c8864dccb
Jan  1 18:24:01 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Jan  1 18:24:01 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /root/Downloads/XX-Net-master/data/downloads/README.md, retry:0
Jan  1 18:24:02 - [WARNING] request module:gae_proxy start fail
Jan  1 18:24:03 - [WARNING] request module:gae_proxy start fail

**Comment by xxnet** [comment]
​这个错的太奇怪，很基本的python语法报错

只能自己折腾，看看其他版本怎样

或者直接./start.sh 启动

**Comment by baibaluo** [comment]
一样遇到这个错，因为centos6，自带的python版本为2.6，不支持1 in {1,2}这样的语法。

**Comment by xxnet** [comment]
​试试把 {} 换成 []

**Comment by calixs** [comment]
怎么弄好，我这也是同样的状况

**Comment by kingjia1989** [comment]
请问楼主解决了吗？

**Comment by rowanpang** [comment]
’if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:‘ ===》 换成'if type != socket.SOCK_STREAM and type != socket.SOCK_DGRAM:‘
