### ISSUE TITLE
导入 IP 时自动去重

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1785]
https://github.com/XX-net/XX-Net/issues/1781
在遇到这个问题时，我曾试着把旧的 IP 列表全部导入进去，结果 IP 数量直接翻倍，希望导入时能够自动去除 IP 库中已有的 IP。

**Comment by yeahwu** [comment]
有这种问题？其实我想说，gae老鸟就是矫情，多一个IP少几个IP这都不是事，又不是不能用。这就像当年看到goagent黄字就烦心的不要不要的，一定要找到原因，强迫症的表现。这样是不对的。
还有，gae的问题，其实还有蛮多。IP只是最显现的问题，深层一点的上传和下载；断流问题才是真烦心。

**Comment by Cat7373** [comment]
@yeahwu 
那只能说，这是一个优先级较低的问题，但并不表示这不是一个问题，有问题提出来，留到以后有空再解决，难道不应该酱紫咩？

**Comment by xyuanmu** [comment]
没记错的话导入IP是有去重的，不过会将延时重设为100。

**Comment by yeahwu** [comment]
@Cat7373 情绪化了，不好意思！确实有问题得提出来，我错了。

**Comment by xxnet** [comment]
​呵呵，心平气和，新的开始。

刚才测试2.8.9 导入一个已经存在的ip，显示导入0个ip，
导入一个原来不存在的ip，
第一次，显示导入1个ip，总ip数新增1个;
第二次，显示导入0个ip，总ip没有增加。

**Comment by Cat7373** [comment]
好吧，这个问题可能是前几个版本的，之前遇到过但是没提交，可能是已经修复过了。

**Comment by Cat7373** [comment]
当时我并未查看实际保存的 IP 数量，只是查看了状态页显示的 IP 数量，这样看来，是因为导入的 IP 已经存在时会导致延时被刷新，这才导致了数量瞬间大增的问题。

**Comment by xyuanmu** [comment]
@Cat7373 哦，我明白为什么IP突然大增了，状态页是显示fail time为0的IP，就是good_ip.txt每行最后一位数字，而导入重复的IP会将原有的数字清零所以状态页的IP数量会大增，实际数量要到高级 -> 检查所有IP里查看。这样有些不方便，还是觉得以前那种显示方式比较妥 总IP数/有效IP数，把逗号换成斜杠就不会误导人是千位分隔符了 @xxnet。
