### ISSUE TITLE
测试，我提供一个链接，大家用SwitchyOmega插件，点击xx-net全局下载，看能不能下载完整？

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1786]
我试过多次，每次都是下载到32mb就完成了，原文件60mb左右。下面是下载链
https://github.com/yeahwu/firefox-tor/archive/master.zip

**Comment by linhua55** [comment]
不能下载，提示
>Message From FetchServer
>
>    Python Urlfetch Error: 'GET'
>    ResponseTooLargeError(), timeout=19
>    ResponseTooLargeError(), timeout=38

**Comment by yeahwu** [comment]
好在github不用挂代理可以下载。反正用gae下这种大文件很容易出现问题，上传也类似。vps则没有问题。

**Comment by linhua55** [comment]
用aria2c下载工具挂xx-net的代理，可下载完整

**Comment by xxnet** [comment]
​github的下载链接测试过不支持分段下载的，而GAE下载大小是有限制的。

@linhua
  你用ariac 的命令是什么？下载后大小是多少？

**Comment by caofengzi** [comment]
俺用xx下載過很多次了，每次都是32m就完成下載了。

**Comment by fuding** [comment]
同样32m的路过

**Comment by linhua55** [comment]
@xxnet 

    aria2c --check-certificate=false --http-proxy=127.0.0.1:8087 https://github.com/yeahwu/firefox-tor/archive/master.zip

**Comment by yeahwu** [comment]
这就是一个悲催的现实呀！

**Comment by riumiyama** [comment]
只能下載32M

**Comment by panzer1313208** [comment]
下载东西还是去用SS吧
