### ISSUE TITLE
重装系统后再重用，不提示生成桌面快捷怎么办？

### ISSUE THREAD

**Issue by kszkcv** [XX-net/XX-Net#1795]
找不到快捷方式，每次都只能打开start的快捷方式

**Comment by Cat7373** [comment]
可以把start.vbs发送到桌面快捷方式解决

**Comment by zzgpku** [comment]
可以将start.vbs发送快捷方式到桌面，然后改一下名称，图标的话可以右键——属性——更改图标，找到xxnet的文件夹，XX-Net-2.8.0\launcher\web_ui\favicon.ico，里面有图标，这样就和它生成的一模一样了。

**Comment by kszkcv** [comment]
非常感谢Cat7373和zzgpku，已经成功解决！

**Comment by zjhzxhz** [comment]
Please close this issue
