### ISSUE TITLE
xx net 有对官方的 goagent 做特别修改还是只是一个前端性质的工具？

### ISSUE THREAD

**Issue by haobug** [XX-net/XX-Net#180]
如题

**Comment by yfdyh000** [comment]
很多改进，包括goagent的改进/部分重写+IP自动搜索+前端界面。具体见源码。

**Comment by haobug** [comment]
好的，我问这个问题就是确认一下是否需要重新上传你们这包里面的 server 端，
照你这么说，那就是需要了的说。

不过，按开源的惯例，这些改动，如果能合入上游的话，尽量提交给上游吧。

**Comment by haobug** [comment]
好的，我问这个问题就是确认一下是否需要重新上传你们这包里面的 server 端，
照你这么说，那就是需要了的说。

不过，按开源的惯例，这些改动，如果能合入上游的话，尽量提交给上游吧。

**Comment by yfdyh000** [comment]
服务端好像是兼容goagent的，所以直接配置原来的appid应该也行。
主要改动在客户端。服务端具体有什么改动，不太清楚。

goagent目前好像仅限于接受少量的维护，基本没有活跃的开发了。

**Comment by haobug** [comment]
了解情况了，感谢。

**Comment by simonasd** [comment]
@yfdyh000 您是否清楚XX-Net对goagent等其他GAE代理服务端的兼容情况？比如兼容goagent某版本到某版本的服务端？我好写进wiki中。从其他GAE代理转过来的用户应该比较关心这个问题。

**Comment by xxnet** [comment]
目前的GAE服务端代码，在goagent 3.2 上做了小改动，在访问大部分网页上是兼容的，可以互换。

只是少数视频网站上有差别，比如xvideo等视频网站：
xx-net 服务端代码中，针对视频文件过大，并且网站限速，导致超时的问题，采用主动切割的方式进行下载。


在 2015年7月12日 上午11:29，simonasd <notifications@github.com>写道：
