### ISSUE TITLE
使用 XX-net 一段时间后无法访问墙内网站。

### ISSUE THREAD

**Issue by piratf** [XX-net/XX-Net#1803]
-----------
问题描述：
经常在使用 XX-net 一段时间后无法访问墙内网站(无法访问不使用代理的网站，例如 Github等)，墙外正常。退出 XX-net 后几分钟墙内网络回复正常。
选项是取消全局代理。浏览器是 Chrome，切换代理用的是 SwitchyOmega
不清楚有没有已经存在的 Issue，翻了几页没找到相似的。
校园网，锐捷。

-----------
诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.8.9
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 208
network-status: Fail
connected-link: 8 / 39
scan-ip-thread-num: 50
ip-quality: 338
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by G-monitor** [comment]
可以参考#1431

**Comment by piratf** [comment]
感谢！@G-monitor
