### ISSUE TITLE
在Windows Server 2008 R2上运行失败

### ISSUE THREAD

**Issue by G-monitor** [XX-net/XX-Net#1808]
别人给了个空闲的阿里云，准备放这个上去给基友共享用。
然后出现了这个错误，使用的版本是2.7.3
因为同时在运行一些其他的windows程序所以也不方便换系统
干脆当作一个问题来提交好了=A=
系统是Windows Server 2008 R2 Standard（标准版）64位

>E:\XX-Net>SET PYTHONPATH=
>
>E:\XX-Net>"E:\XX-Net\python27/1.0/python.exe" "E:\XX-Net\launcher/start.py"
>Jan 04 04:23:41 - [INFO] start XX-Net 2.7.3
>Jan 04 04:23:41 - [DEBUG] start confirm_xxnet_exit
>Jan 04 04:23:42 - [DEBUG] good, xxnet:8087 cleared!
>Jan 04 04:23:43 - [DEBUG] good, xxnet:8085 clear!
>Jan 04 04:23:43 - [DEBUG] finished confirm_xxnet_exit
>Jan 04 04:23:43 - [ERROR] start module gae_proxy fail:DLL load failed: 应用程序
>无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或
>使用命令行 sxstrace.exe 工具。
>Traceback (most recent call last):
>  File "E:\XX-Net\launcher\module_init.py", line 37, in start
>    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
>l', 'start'], -1)
>  File "E:\XX-Net\gae_proxy\start.py", line 14, in <module>
>    import local.proxy as client
>  File "E:\XX-Net\gae_proxy\local\proxy.py", line 74, in <module>
>    from cert_util import CertUtil
>  File "E:\XX-Net\gae_proxy\local\cert_util.py", line 37, in <module>
>    import OpenSSL
>  File "E:\XX-Net\python27\1.0\lib\win32\OpenSSL\__init__.py", line 26, in <modu
>le>
>    from OpenSSL import crypto, rand, SSL
>ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有
>关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。
>
>Jan 04 04:23:43 - [INFO] start gae_proxy time cost 24
>Jan 04 04:23:43 - [INFO] begin to start web control
>Jan 04 04:23:43 - [INFO] launcher web control started.
>Jan 04 04:23:43 - [INFO] generate desktop shortcut
>Jan 04 04:23:43 - [WARNING] request module:gae_proxy start fail
>Jan 04 04:23:44 - [WARNING] request module:gae_proxy start fail

**Comment by xyuanmu** [comment]
安装vc++ 2008(x86)版本。

**Comment by G-monitor** [comment]
@xyuanmu 
已经安装了VC++2012的x64和x86版本
需要再安装一个VC++2008吗？

**Comment by G-monitor** [comment]
GG
安装了个2008后解决，这算什么鬼问题嘛=A=
感谢@xyuanmu

**Comment by kkpig** [comment]
非常感谢 迷茫了半天终于在这里找到方法了 需要Microsoft Visual C++ 2008 Redistributable - x86 ，建议写入README.MD里面

**Comment by xxnet** [comment]
​已经更新到
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
