### ISSUE TITLE
Google ip 数量只有49个。failed connection。

### ISSUE THREAD

**Issue by evilstyle** [XX-net/XX-Net#181]
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.8.10
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	49
connected link	23
ip_connect_interval

**Comment by latrikcoasler** [comment]
我只有117个，上午还是2000个的。

**Comment by xxnet** [comment]
请先手动升级新版，新版收录了GoGoTester的最新ip池
这几天也会部署自动升级了

2015-04-18 5:14 GMT-04:00 evilstyle <notifications@github.com>:

**Comment by xxnet** [comment]
请测试新版1.12.0
