### ISSUE TITLE
非默认浏览器无法使用

### ISSUE THREAD

**Issue by benpigchu** [XX-net/XX-Net#182]
情况是这样的
我安装了两个浏览器，搜狗和chrome
搜狗是默认浏览器（因为用的是家长的电脑，家长要用）
于是XX-Net可以在搜狗中使用
但不能在Chrome中使用
不知道是什么原因

**Comment by Cat7373** [comment]
选择设置代理之后，会设置IE的代理
非IE浏览器的，需要自己手动修改代理，有的支持直接用IE的代理，那种选上就成
不能用IE代理的，可以设置成下面两种
http://127.0.0.1:8086/proxy.pac（推荐）
或者也可以设置为127.0.0.1:8087，但是打开国内网站会比较慢

**Comment by benpigchu** [comment]
之前没有解释清楚
当我用Chrome打开XX-net控制台时
![1](https://cloud.githubusercontent.com/assets/9023067/7218216/f032d966-e693-11e4-9cbd-d3f333d1aa4d.png)
当我正确设置代理127.0.0.1:8087之后
![1](https://cloud.githubusercontent.com/assets/9023067/7218208/7d8943c8-e693-11e4-9595-fa3d9c9fd5d0.png)
400
而使用搜狗就一切正常
另外我的chrome代理是使用SwitchyOmega设置的

**Comment by xxnet** [comment]
你是用localhost:8087去打开控制页面的。

内部作了检查，防止跨站攻击，但是没有考虑localhost的情况。

你用127.0.0.1:8085访问就没有问题。

我下个版本修复

在 2015年4月19日 上午1:02，Ben Pig Chu <notifications@github.com>写道：

**Comment by digglefly** [comment]
额 昨晚我用360浏览器都可以 今早不行了 进来一看 原来大家都不行了 哈哈

**Comment by benpigchu** [comment]
控制页面可以正常使用了
可是依旧400
![image](https://cloud.githubusercontent.com/assets/9023067/7409841/6315a348-ef5c-11e4-981a-7ba6b4b84318.png)
