### ISSUE TITLE
如何打开ip扫描？

### ISSUE THREAD

**Issue by wan9wu** [XX-net/XX-Net#1825]
打开xx-net提示：You may want to turn on IP scaner.
点击进去后只看到【更新】、【提交】两个按钮，点完提交后没反应，看扫描日志也没反应。
在扫描日志页面点刷新也没反应。
检查所有ip的状态是：
状态
属性	值
总IP数	49
剩余数	0
有效IP数	0

**Comment by xxnet** [comment]
请贴出状态页或诊断信息

**Comment by wan9wu** [comment]
我把所有文件删了，重新下载了一个，没有用原来的data文件，一切都正常了。
状态

属性	值
总IP数	12549
剩余数	0
有效IP数	12126
