### ISSUE TITLE
xx，好冷

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1829]
一声哀叹，然后出去巡街了。大家后面跟上，活跃一下气氛！

**Comment by yeahwu** [comment]
世界上最好的语言是啥？
拍黄片就是世界上最好的语言！ 以后“拍黄片”就确定是 PHP 的别称了！

**Comment by xyuanmu** [comment]
:bird: 轻轻地飘过～

**Comment by xxnet** [comment]
​wiki还需要好好整理，能整整吗？

**Comment by yeahwu** [comment]
刚回来，看了wiki目录，完全不知道怎么下手。汗

**Comment by xxnet** [comment]
​是啊，太多了，前期太缺，就放开了加，现在太乱了。

而且考虑到多语言版本，需要给各个语言提供帮助，可以考虑重开一套，目前这套先放着不动。

新的内容，中文的以CN做前缀，英文以EN做前缀。。。

还有首页，加了英文之后，感觉太乱了，不如另外建一个英文版面，首页只给一个链接。

先梳理思路，看看怎么规划，再逐步细化

**Comment by yeahwu** [comment]
x大，我是不是闯祸了？怎么我就在你的wiki页面删删，怎么就没有了？按理说我没有权限哪？

**Comment by xxnet** [comment]
​不怕，都有git版本管理着的，我看看

**Comment by xxnet** [comment]
​看着都在，你刷新下看看

**Comment by yeahwu** [comment]
是这样你还是给他还原吧，我看有空把firefox篇，和chrome篇完善一下，再来删除重复的证书导入，插件使用之类。

**Comment by yeahwu** [comment]
完了，完了，我在你的中文首页删掉了好几项，好像真不在了。这不科学呀

**Comment by yeahwu** [comment]
那个，新手上路项，我删除了首页，超详细教程，插件使用，证书导入之类，看不见了。闯大祸了

**Comment by yeahwu** [comment]
你这wiki，看得我头皮发麻，相信等我看完了，这个xx-net也不知道怎么用了。看傻了

**Comment by yeahwu** [comment]
其实，我是极简主义者，这是这样想的，分成几大部分
windows ：包括火狐，chrome，ie，全局gaeproxy，pac代理。这一项内容可能比较多，包括插件安装，证书导入
linux：这项就简单了，着重各个版本的安装，启动命令，其他的浏览器部分的插件，证书导入，基本和windows上一个屌样。借用windows下的chrome，firefox教程链
mac ：这个同linux类似，
appid要单独教程。
其他的臭袜子给扔掉。因为在chrome，firefox教程里已经包括了，证书，插件，pac，再单独搞这些就是多余。
还有，就是把这三样还是写在你的code首页，超链形式，不占什么篇幅，例如
```
windows教程
linux教程
mac教程
```
英文部分，喊，mike过来翻译。

**Comment by panzer1313208** [comment]
我只想解决xxnet右键选择不了的问题。

**Comment by firefoxwang** [comment]
非常感谢你们

**Comment by simonasd** [comment]
@yeahwu 可以通过页面链接做成一个引导，
页面一：平台和操作系统。用户点击windows
页面二之windows：浏览器选择，用户点击Chrome
等等。

还有，我觉得内容可以模块化，共用。避免修改的时候只改了一部分。

**Comment by yeahwu** [comment]
主页面，系统平台。子页面，浏览器类。尽量做到傻瓜也能看得懂。
哎呦，你这样让我压力好大呀，话说我这边三天两头断网，烦死了，下次电信的人来，直接肛了他。
simonasd <notifications@github.com>于2016年1月9日 周六23:22写道：

**Comment by simonasd** [comment]
@yeahwu 本来我想继续搞wiki，但最近很忙，没什么精力了。你可以先把框架搭起来，内容慢慢补充
