### ISSUE TITLE
Mac下三点建议

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#183]
1.图标能不能换个，用python的总觉得有点别扭，当然我自己也可以换自己喜欢的，我觉得既然是一个产品总要有自己的特点，图标这个很重要，像goagentX的图标就还可以。
2.mac下运行start.command总要占用一个终端，能不能去掉这个呢。
3.既然使用了SwitchySharp或者别的插件，为何点击图标之后还有Enable Global Goagent Proxy和Disable Global Goagent Proxy两个选项呢？SwitchySharp里是可以设置全局和自动切换的。

**Comment by causlayer** [comment]
还有两个问题：
1.您与 www.facebook.com 之间的连接采用了过时的加密技术。
该连接使用 TLS 1.0。
该连接是使用 AES_256_CBC 进行加密的，同时使用 SHA1 进行讯息身份验证并使用 RSA 作为密钥交换机制。
2.在手机（我的是iphone）安装ca文件后,通过http代理访问不了。

**Comment by xxnet** [comment]
已经有网友贡献了图标，下周会换上。

SHA1身份验证问题，请升级新版，证书会用SHA256签名。
TLS 1.0的问题，暂时找不到 pyOpenSSL 支持TLS 1.2的库，有用过或知道的请帮忙

在 2015年4月18日 下午12:52，causlayer <notifications@github.com>写道：
