### ISSUE TITLE
XXNET自带的PAC并不完美

### ISSUE THREAD

**Issue by yaoguaishou** [XX-net/XX-Net#1875]
我用127.0.0.1:8087/porxy.pac只能访问谷歌系的网站，再有就是一些知名网站（维基百科推特等）。其他国外网站都无法通过代理，必须手动调用127.0.0.1:8087。太麻烦了

为什么不参考一下这个呢？
https://github.com/breakwa11/gfw_whitelist
https://raw.githubusercontent.com/breakwa11/gfw_whitelist/master/proxy.pac

**Comment by panzer1313208** [comment]
可以弄扩展啊。switchyomega

**Comment by xyuanmu** [comment]
xxnet 是由这个规则生成的
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by linhua55** [comment]
可以使用[cow](https://github.com/cyfdecyf/cow)

**Comment by jzp820927** [comment]
cow 的智能预判被墙状态其实不错！

**Comment by xxnet** [comment]
好东西集成进来，​两种方案：
1. 直接集成，单个平台1.6M zip包
   需要根据不同平台下载对应的版本。
   以后cow升级就跟着升级
2. 用python重新实现一遍
   大小肯定小很多（估计100k）
   个人使用流量不大，速度没有明显差别
   工作量估计要2-3周时间


可以先试试第一种方案，有兴趣的先折腾看看

**Comment by jzp820927** [comment]
如果能用 Python 实现它的智能判断功能，也挺不错，体积就小很多了，可惜要重新开发！

**Comment by xxnet** [comment]
要体验和定制化，还是用python重写比较好
COW可以借鉴，经验比代码更重要

**Comment by jzp820927** [comment]
我也是这么想的，可以借用 COW 的技术，用 Python 来重新实现，这样，统一代理，方便维护，稳定性和集成性也更好。
其实 cow 的实现技术也不算太难，就是通过返回的 RESET 状态码来确定走代理！

**Comment by xxnet** [comment]
​可以实现为独立的模块，再通过模块间调用GAE_proxy，或者PHP_Proxy。

对于定制，某些网站需要走PHP模块，比如youtube，解决地区限制。
记得fqrouter有实现过类似的机制，而且更智能，他要实现Socks协议，还要知道能否替换为GAE，值得学习。

**Comment by simonasd** [comment]
支持一下。在webUI可以有一个页面来查看和管理规则，这样开启“全局智能代理”之后就不需要浏览器插件了，对新手是个好事。目前基于gfwlist做的pac其实效果比较一般，新手遇到PAC没有收录的站点就只好干瞪眼。

除了选择直连、GAE、PHP之外，同时也可以支持把流量转向其他二级代理，比如SS。

这样一来XX-Net就从一个纯粹的代理工具，转型为代理工具+代理管理工具的复合型选手了。

**Comment by xxnet** [comment]
​以前设想过把Lantern也打包进来，GAE和Lantern/PHP/SS作为后端，自动判断哪个能用，用户只管用就好，不必担心哪个不行了

**Comment by simonasd** [comment]
@xxnet 可以结合模块化下载器来实现。默认只有GAE_Proxy，用户在WebUI里面开启PHP、Lantern或者SS之后再下载对应资源，并开启对应的代理管理配置文件。

**Comment by xxnet** [comment]
​集成进来也不难，只是产品设计和工程问题。

第一步就是要模块化下载器，先搞一个VBScript的下载脚本，把XX-Net下载下来，然后慢慢拆分模块就容易了

**Comment by jzp820927** [comment]
支持一下，希望能够实现上面的设想。

**Comment by yaoguaishou** [comment]
滋瓷

**Comment by philogicrock** [comment]
lantern的pac智能分流直连和被墙网站设计挺不错的，但不知道是怎么实现的。
