### ISSUE TITLE
https://www.google.com/?gws_rd=ssl

### ISSUE THREAD

**Issue by niodx** [XX-net/XX-Net#188]
有时候访问都自动跳转成这个了，有办法恢复https://www.google.com 么...实在不行就算了

**Comment by Cat7373** [comment]
有没有更详细点的说明 - -
比如当时的日志之类的

**Comment by xxnet** [comment]
先试试：
https://www.google.com/ncr

跳转后，有什么影响吗？

**Comment by niodx** [comment]
算了，最近都没复现，先用着吧。

**Comment by niucang** [comment]
有gws_rd=ssl表示你是从http重定向到Https的，改为https://www.google.com即可
