### ISSUE TITLE
关于wiki上浏览器多选方案。然后各种征集，美工，建议，写手。然后，我欠快播一个会员。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1884]
火狐：
firefox+pan
firefox+autoproxy,这个修改版第三方插件
firefox+foxyproxy
chrome：
chrome+SwitchyOmega,这个xx自带的，挺好
IE：
xx自带pac

**Comment by yeahwu** [comment]
@Cat7373 你长得太漂亮，所以chrome+SwitchyOmega教程就交给你了，限期春节前。

**Comment by Cat7373** [comment]
懒0.0

**Comment by yeahwu** [comment]
没义气，其实我也懒。
连我这半残的ps手，都准备下手了。你也得治治了。

**Comment by linhua55** [comment]
@yeahwu 
用插件+PAC对用户来说那么麻烦，干脆让他们用[cow](https://github.com/cyfdecyf/cow)吧

**Comment by yeahwu** [comment]
@linhua55 这个好像更麻烦，还得另下载程序。刚看了下pan插件，已经内置好了https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
默认有ss和goagent两个选项，真贴心。

**Comment by linhua55** [comment]
@yeahwu 
集成到发行里去呀。cow是全局的，通杀各种浏览器。而PAC需要频繁更新网址，cow不需要。

**Comment by xxnet** [comment]
​觉得最好把提纲先规划好，这是最基础也是很不容易的部分，还有框架设计，再开始较好

**Comment by simonasd** [comment]
cow看起来是个不错的思路，如果能跟XX-Net主程序结合起来也许是个不错的主意。

**Comment by linhua55** [comment]
@yeahwu
对了，cow是支持负载均衡的，可以同时设置多个代理，那个可用、（好用）就用哪个

**Comment by jzp820927** [comment]
COW 的优势就是能够在程序内部智能测试网站是否被墙，并根据测试结果决定是否调用代理，也就是说由程序自己觉得是否要走代理，也就省去了更新PAC的URL地址的麻烦！

**Comment by yeahwu** [comment]
@xxnet 年底挺忙的的，我没理解错的话，就指折腾wiki页吧？简单点讲也就是markdown写写吧？你不会是叫我另开web页面吧？

**Comment by yeahwu** [comment]
就我这半残的手艺，惚惚小菇娘还行，真干会早泄的。另外好像chrome又升级了识别机制，我那chrome-xx强制更改验证环境又别google给破了。MT破chrome

**Comment by xxnet** [comment]
wiki 就好，要以最低的成本去做，资源有限，要将效率。

感觉先要有一个框架，再慢慢往里面填。
框架起来了，就可以大家去帮忙搞了，截图、标文字、上传，都挺花时间的，文字就少点。

**Comment by linhua55** [comment]
关于图片的简便上传方法，可参考 http://mikehadlow.blogspot.com/2014/03/how-to-add-images-to-github-wiki.html

**Comment by simonasd** [comment]
@linhua55 其实用浏览器上传也挺方便的。随便点开一个issue，往回复里面拖拽上传，传好了直接把代码复制过去即可。

**Comment by yeahwu** [comment]
图片直接pull到自己的git上面就好了，比用图床还方便。

**Comment by yeahwu** [comment]
pan插件搞定，改天来搞定一下chrome+SwitchyOmega，还有wiki上的火狐篇，简单方法是错误的，步骤错误。

**Comment by Cat7373** [comment]
0.0
勤劳的小@yeahwu

**Comment by yeahwu** [comment]
@Cat7373 是的呀，工头刚咆哮完，回家还得上xx，知道现在这个时候，是单身狗最可怜的季节吗？
最后，妹子很负责任地告诉你，“哥会暖床！”

**Comment by Cat7373** [comment]
用了两天 lantern 发现：
1. 稳定性不是太好。
2. 某些国内网站各种出毛病。
3. 某些国外网站报 DNS 错误。

**Comment by yeahwu** [comment]
你用的什么版本？用插件调用，国内网站不走代理嘛！lantern还是比较稳定的，我这边。
Cat73 <notifications@github.com>于2016年1月12日 周二22:46写道：

**Comment by Cat7373** [comment]
最新稳定版，所有请求均走代理的模式。

**Comment by yeahwu** [comment]
给个最新源码编译，去pac，去弹窗版本，请用SwitchyOmega或者pan插件调用。
https://github.com/yeahwu/firefox-lantern/raw/master/Lantern.exe

**Comment by Cat7373** [comment]
http://play.elevatorsaga.com/
在玩介个游戏↑

**Comment by yeahwu** [comment]
@Cat7373  我媳妇玩的游戏都这么又个性，拜服

**Comment by Cat7373** [comment]
@yeahwu 酷爱来写一个能过15关的代码

**Comment by yeahwu** [comment]
像我这种成熟型男能做这种事？除了sex别来找我。
Cat73 <notifications@github.com>于2016年1月14日 周四12:15写道：

**Comment by fuding** [comment]
手动眼斜

**Comment by yeahwu** [comment]
@Cat7373 我什么称呼我为“酷爱”，我真是受宠若惊哪！

**Comment by simonasd** [comment]
@yeahwu 

kuai ==》 ku ai

很抱歉把你从中国梦中惊醒

**Comment by yeahwu** [comment]
![_2016-01-14t07-58-17 093z](https://cloud.githubusercontent.com/assets/13328328/12318864/a6c0645a-bad8-11e5-84f2-27fab64ec8fa.png)

**Comment by yeahwu** [comment]
@simonasd 这孩子瞎说什么大实话。春梦碎！

**Comment by Cat7373** [comment]
@yeahwu 
这是我现在的代码哟：
{update:function(){},init:function(a,b){function d(){var a,c,d;this.canUp()&&this.canDown()||this.setIsUp(!this.isUp),a=1-this.loadFactor()<1/this.maxPassengerCount()?void 0:this.isUp?b.findUp(this):b.findDown(this),c=this.isUp?this.findUp():this.findDown(),a=void 0===a?this.isUp?this.getMaxFloor():this.getMinFloor():a,c=void 0===c?this.isUp?this.getMaxFloor():this.getMinFloor():c,d=d=this.isUp?c>a?a:c:c>a?c:a,d===this.getMaxFloor()?this.setGoing(!1):d===this.getMinFloor()&&this.setGoing(!0),this.goToFloor(d)}function e(a){this._buttonStates[a]=!0}function f(a){this._buttonStates[a]=!1}function j(a,b){for(var c in b)a[c]=b[c]}function k(a){j(a,g),a._buttonStates=[];for(var b=a.getMinFloor();b<=a.getMaxFloor();b++)a._buttonStates[b]=!1;a.isUp=!0,a.on("idle",d),a.on("floor_button_pressed",e),a.on("stopped_at_floor",f)}function l(a){j(a,h)}function m(){j(b,i)}var n,g={setGoing:function(a){this.goingUpIndicator(a),this.goingDownIndicator(!a)},setIsUp:function(a){this.isUp=a,this.setGoing(a)},getMaxFloor:function(){return b.length-1},getMinFloor:function(){return 0},canUp:function(a){return a=void 0===a?1:a,this.currentFloor()+a<=this.getMaxFloor()},canDown:function(a){return a=void 0===a?1:a,this.currentFloor()-a>=this.getMinFloor()},findUp:function(){for(var a=this.currentFloor()+1;a<=this.getMaxFloor();a++)if(this._buttonStates[a]===!0)return a},findDown:function(){for(var a=this.currentFloor()-1;a>=this.getMinFloor();a--)if(this._buttonStates[a]===!0)return a}},h={getButtonStatus:function(a){return""!==this.buttonStates[a]}},i={findUp:function(a){for(var b=a.currentFloor()+1;b<=a.getMaxFloor();b++)if(this[b].getButtonStatus("up")===!0)return b},findDown:function(a){for(var b=a.currentFloor()-1;b>=a.getMinFloor();b--)if(this[b].getButtonStatus("down")===!0)return b}};for(n in a)k(a[n]);for(n in b)l(b[n]);m()}}

**Comment by yeahwu** [comment]
@Cat7373 要不要这么牛逼呀！我这学渣，表示无地自容。
