### ISSUE TITLE
2.8.9扫描线程为负数问题

### ISSUE THREAD

**Issue by G-monitor** [XX-net/XX-Net#1885]
---

问题：scan-ip-thread-num: -20
描述：。。。。。。。。。。。
补充1：之前2.7.9(我记得是这个版本)也反馈过一次扫描线程是负数的问题#1559
补充2：这次是单纯的挂在服务器上，使用量相对比较大(自我感觉)
补充3：时不时出现connected-link: 0 / 0的情况，不过大多时候重启gae模块就解决了
补充4：使用量真的比较大！
补充5：刚刚整体退出重开恢复正常使用了
吐槽1：三个新弄的appid一直部署不上去，提示连接超时，但是谷歌可以正常访问
吐槽2：上面好整齐

---

诊断信息：
sys-platform: AMD64, Windows-2008ServerR2-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 2008ServerR2
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:272; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.8.9
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 2467
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: -20
ip-quality: 151
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by xxnet** [comment]
2016-01-10 15:37 GMT+08:00 G-monitor <notifications@github.com>:

> ------------------------------
>
> 问题：scan-ip-thread-num: -20
> 描述：。。。。。。。。。。。
> 补充1：之前279(我记得是这个版本)也反馈过一次扫描线程是负数的问题#1559
> <https://github.com/XX-net/XX-Net/issues/1559>
>
抱歉，感觉没有那么严重，这个问题还没有来得及去看


>
> 补充2：这次是单纯的挂在服务器上，使用量相对比较大(自我感觉)
> 补充3：时不时出现connected-link: 0 / 0的情况，不过大多时候重启gae模块就解决了
>
这种情况下日志显示什么，贴一段出来看看

> 补充4：使用量真的比较大！
>
这种情况在2.8.5之类的版本有，2.8.9认为已经解决了，请确认是2.8.9(自动升级有时会部分没有升级到)
，如果不是直接下载2.8.9，那么请手动下载2.8.9压缩文件解压覆盖。

> 补充5：刚刚整体退出重开恢复正常使用了
> 吐槽1：三个新弄的appid一直部署不上去，提示连接超时，但是谷歌可以正常访问
>
看看GAE日志显示什么，注意不是部署的日志

**Comment by G-monitor** [comment]
>Jan 11 01:26:24.947 - [DEBUG] ssl_closed 203.210.4.180
Jan 11 01:26:24.967 - [DEBUG] create_ssl update ip:163.28.116.54 time:349
Jan 11 01:26:25.040 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.040 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25 - [DEBUG]LOG_EXCEPT: GAE_Exception 2 'try max times', Except:[Errno 9] Bad file descriptor
Jan 11 01:26:25.040 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.041 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.041 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.041 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.041 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.080 - [WARNING] APPID error:502 url:http://服务器ip:代理端口/
Jan 11 01:26:25.080 - [DEBUG] 210.242.125.87 close:app err
Jan 11 01:26:25.080 - [DEBUG] ssl_closed 210.242.125.87
Jan 11 01:26:25.137 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.137 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.139 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.139 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.139 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.139 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.145 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.145 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.145 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.145 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.239 - [DEBUG] create_ssl update ip:113.171.252.46 time:384
Jan 11 01:26:25.242 - [DEBUG] get ip:203.176.178.30 t:430
Jan 11 01:26:25.301 - [WARNING] APPID error:502 url:http://服务器ip:代理端口/
Jan 11 01:26:25.301 - [DEBUG] 213.81.154.134 close:app err
Jan 11 01:26:25.301 - [DEBUG] ssl_closed 213.81.154.134
Jan 11 01:26:25.315 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.315 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.315 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.315 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.323 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.323 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.323 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.323 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.393 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.393 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.456 - [WARNING] APPID error:502 url:http://服务器ip:代理端口/
Jan 11 01:26:25.456 - [DEBUG] 58.123.102.112 close:app err
Jan 11 01:26:25.457 - [DEBUG] ssl_closed 58.123.102.112
Jan 11 01:26:25.484 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.484 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.484 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.484 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.484 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.484 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.484 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.484 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.510 - [DEBUG] create_ssl update ip:185.1.11.169 time:424
Jan 11 01:26:25.533 - [DEBUG] get ip:78.11.253.219 t:453
Jan 11 01:26:25.538 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.538 - [DEBUG] create_ssl_connection fail
Jan 11 01:26:25.538 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:26:25.538 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:26:25.563 - [DEBUG] create ssl timeout fail.
Jan 11 01:26:25.563 - [DEBUG] create_ssl_connection fail

之前更新确实没有更新全，web ui没有替换掉，是手动下载覆盖解压的
等下重新部署一下试试看

**Comment by G-monitor** [comment]
>Jan 11 01:30:22.667 - [DEBUG] ssl_closed 200.115.94.42
Jan 11 01:30:22 - [DEBUG]LOG_EXCEPT: ssl_closed 200.81.125.28, Except:[Errno 9] Bad file descriptor
Jan 11 01:30:22.668 - [DEBUG] ssl_closed 74.125.171.233
Jan 11 01:30:22.668 - [DEBUG] ssl_closed 49.231.60.243
Jan 11 01:30:22.668 - [DEBUG] ssl_closed 103.30.113.175
Jan 11 01:30:22.669 - [DEBUG] ssl_closed 163.28.38.6
Jan 11 01:30:22.669 - [DEBUG] ssl_closed 203.176.178.50
Jan 11 01:30:22.670 - [DEBUG] ssl_closed 90.222.188.221
Jan 11 01:30:22.670 - [DEBUG] ssl_closed 118.98.106.169
Jan 11 01:30:22.671 - [DEBUG] ssl_closed 1.255.22.211

省略若干ssl_closed
>Jan 11 01:30:22.732 - [DEBUG] ssl_closed 202.248.151.59
Jan 11 01:30:22.800 - [WARNING] APPID error:502 url:http://服务器ip:代理端口/
Jan 11 01:30:22.800 - [DEBUG] 210.153.73.51 close:app err
Jan 11 01:30:22.800 - [DEBUG] ssl_closed 210.153.73.51
Jan 11 01:30:22.878 - [INFO] load manual.ini success
Jan 11 01:30:22.879 - [DEBUG] ssl_closed 140.113.14.58
Jan 11 01:30:22.879 - [DEBUG] ssl_closed 118.98.30.73
Jan 11 01:30:22 - [DEBUG]LOG_EXCEPT: ## GAEProxy set keep_running: True, Except:[Errno 9] Bad file descriptor
Jan 11 01:30:22.880 - [INFO] ------------------------------------------------------
Jan 11 01:30:22.880 - [INFO] Python Version : 2.7.9
Jan 11 01:30:22.880 - [INFO] OS : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:272; ProductType:0
Jan 11 01:30:22.880 - [INFO] Listen Address : 0.0.0.0:12450
Jan 11 01:30:22.880 - [INFO] GAE APPID : ***********
Jan 11 01:30:22.880 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jan 11 01:30:22.880 - [INFO] ------------------------------------------------------
Jan 11 01:30:22.923 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.923 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.923 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:30:22.923 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:30:22.937 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.942 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.947 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread , Except:[Errno 9] Bad file descriptor
Jan 11 01:30:22.957 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.962 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.967 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
Jan 11 01:30:22.967 - [DEBUG] GAE_Exception 2 'try max times'
Jan 11 01:30:22.967 - [WARNING] gae_exception:GAE_Exception() http://服务器ip:代理端口/
Jan 11 01:30:22.971 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\gae_proxy\local\gae_handler.py", line 151, in request ssl_sock = https_manager.get_ssl_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 539, in get_ssl_connection self.create_more_connection() File "E:\XX-Net\gae_proxy\local\connect_manager.py", line 341, in create_more_connection p.start() File "E:\XX-Net\python27\1.0\lib\threading.py", line 745, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread

**Comment by G-monitor** [comment]
看到了can't start new thread字样，去任务管理器看了下线程数量。。爆炸

![qq 20160111013410](https://cloud.githubusercontent.com/assets/11240579/12222892/a497d820-b803-11e5-9d24-dd21206c684b.jpg)

PS：传图慢炸了。

**Comment by G-monitor** [comment]
再次覆盖后暂时没有发现问题了，部署失败也有可能是那个二次验证和不安全的应用什么的锅，回头再研究一下。。
现在总线程数量是40左右
