### ISSUE TITLE
提示浏览器代理设置有问题，然而我觉得没问题。

### ISSUE THREAD

**Issue by cz726894926** [XX-net/XX-Net#1886]
---

问题描述： 对等端的证书有一个无效的签名
请在此描述你遇到的问题，必要时贴出相关的日志信息。

---

诊断信息：
sys-platform: x86, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:43.0) Gecko/20100101 Firefox/43.0
xxnet-version: 2.8.9
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 15 / 14
network-status: OK
connected-link: 2 / 10
scan-ip-thread-num: 50
ip-quality: 697
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​此处存在误报，可能浏览器可以访问墙外网站，但是诊断报错

**Comment by linhua55** [comment]
> proxy_state: Fail
> ca_state: Fail
如果觉得浏览器代理设置没有问题，那就查看证书是否导入或导入的证书是否匹配。
可参考 https://github.com/XX-net/XX-Net/issues/1877#issuecomment-170225836

**Comment by cz726894926** [comment]
我删了证书重新导入，现在可以了。

**Comment by pendave** [comment]
https://github.com/XX-net/XX-Net/issues/7580 Firefox 火狐浏览器证书失效后的更新办法！GIF动图教程
