### ISSUE TITLE
7*24挂着XX-NET后光猫各种延迟无响应

### ISSUE THREAD

**Issue by thekingofcity** [XX-net/XX-Net#1892]
默认开着50线程  从元旦开始光猫开个百度要十来秒 重启 重置都无果
关闭XX-NET后 不多时就恢复到默认速度
当时IP大概只有一百来个 

续   已入VPS并上传了goagent

**Comment by xxnet** [comment]
​扫描线程降低到1试试

**Comment by 1634814279** [comment]
那如何保证可连通IP数量 不过之后用过1的确在IP够时不卡

**Comment by simonasd** [comment]
@1634814279 并发的请求太多，光猫处理不过来了吧。你可以试试10线程，或者15线程，等等。反复尝试找到光猫能承受的上限。

顺带吐槽运营商的廉价设备

**Comment by looper1234** [comment]
淘宝买的 TP 光猫用下来很好，不掉线也没有慢下过。
就是需要破解下老猫都密码，看 LOID码 是啥。
