### ISSUE TITLE
英文版本中显示夹着中文

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#1896]
英文版本下面，部署完成之后，提示的是这个，里面多了一个"请在"
Current status: Deployment completed. 
Please go to 请在the configuration page to set AppID to enable them.

**Comment by xyuanmu** [comment]
问题出现在这里：[gae_proxy/web_ui/deploy.html#L152](https://github.com/XX-net/XX-Net/blob/42959b1d20af0ced1f470dd3fe751e951e65e2af/gae_proxy/web_ui/deploy.html#L152)

**Comment by xxnet** [comment]
收到，下次发布更新带上
