### ISSUE TITLE
下载 y2b 电影断流了。。。

### ISSUE THREAD

**Issue by litel** [XX-net/XX-Net#19]
用 http://savedeo.com/en 网站解析出 y2b 的链接后点击下载。
几分钟后，就是0b/s了。
How to Render Fire in Cycles (1).mp4 0 B/s - 24.0 MB，共 412 MB

另外就是，deploy里能加上一些参数么，比如 obfuscate 和 http + rc4 + password 等。
然后，config 里加上  window 和 http + rc4

**Comment by litel** [comment]
哦，对，版本
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
Browser	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2292.0 Safari/537.36
GoAgent Version	3.1.32
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
GAE appid	litel1234568|litel123456|litel1234567|litel1234569|
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	1211

**Comment by xxnet** [comment]
问题：
1. 能否直接看视频？
2. RC4 是加密的，但是https已经加密过了，没有必要了
   http 是太容易被封锁的，不建议用这种方式，这是我的理解。
   整个网络里到处是https，而http模式完全透明，很容易被发现特征从而被封锁。
  因此不建议使用http+ rc4
  欢迎交流。
3. password 是保护自己的appid不会被别人用
  首先本来是免费的，被人用了也问题不大；
  别人能猜到你的appid名字，那么猜password是不是也一样？
  所以价值也不大。
4. obfuscate 解决了什么问题？
5. window又解决了什么问题，不了解，能否帮忙解释？

**Comment by litel** [comment]
1可以直接看视频，但偶尔打不开，需要刷新。
然后视频载入一会就会停止，不会一直载入完。。。

2我忘记当初用http+rc4的初衷了。。。

3用rc4就必须要password，而且服务端和客户端的password要一致。

4同2，配置rc4的时候顺手开的。

5路由器很渣的时候，window降低能明显改善1的断流问题，而且同时也会改善甚至解决goagent下载东西会断流的问题。

**Comment by xxnet** [comment]
2，3，4， 建议直接用https，足够而且简单。
1. 视频还有优化空间，年后再优化吧
5. 估计window是类似tcp滑动窗口的概念，年后视频优化时参考下。

**Comment by xxnet** [comment]
1.1.0 版本发布，看Youtube很流畅，你试试看
