### ISSUE TITLE
Deploy not working after add Cancel button in this page

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#190]
Deploy not working after add Cancel button in this page.

I found that the deploy function not working. At least, the log doesn't displayed in the log textarea.

Please fix it ASAP.
BTW, please reject the pull request #186

**Comment by zjhzxhz** [comment]
The status told that the deploy is finished, but the log is still empty.
![deploy-empty-log](https://cloud.githubusercontent.com/assets/1730504/7218214/cc876752-e693-11e4-9940-5c6f3250871d.png)

**Comment by zjhzxhz** [comment]
**Another problem**:
If I click the `Cancel` button, before I click the deploy button.
I'll get an empty response from the server.

![deploy-empty-response](https://cloud.githubusercontent.com/assets/1730504/7218235/b192f5c2-e695-11e4-95f2-90b2c4a9230c.png)

**Comment by xxnet** [comment]
I have revert it.

sorry for that, I review the code change but not test it.
thank you!

2015-04-19 1:12 GMT-04:00 Howard Shieh <notifications@github.com>:

**Comment by xxnet** [comment]
1.9.3 加回去了

**Comment by haobug** [comment]
赞

**Comment by zjhzxhz** [comment]
The issue has fixed. Please close this issue.
