### ISSUE TITLE
手机用Pac脚本代理时候为什么不能用Google Play？

### ISSUE THREAD

**Issue by yujincheng08** [XX-net/XX-Net#1900]
已经成功把手机通过电脑fq了。WLAN连接时候设置使用PAC，已经可以成功连上网页版的Google和Play Store，但是用app版的Google Play似乎并不会走代理。。
不用PAC而是全局代理的时候，Google Play又能用了。。怎么解决这个问题。。

**Comment by jzp820927** [comment]
不确定 APPS 应用是否支持 PAC 。
