### ISSUE TITLE
为什么运行start.vbs后xx-net状态不正常

### ISSUE THREAD

**Issue by alexbbbb** [XX-net/XX-Net#1903]
为什么运行start.vbs后xx-net状态不正常。运行start.bat却可以。

**Comment by xxnet** [comment]
​打开 data/launcher/launcher.log文件看看启动日志有什么异常

**Comment by alexbbbb** [comment]
an 13 09:16:35.536 - [INFO] start XX-Net 2.8.9
Jan 13 09:16:35.536 - [DEBUG] start confirm_xxnet_exit
Jan 13 09:16:36.539 - [DEBUG] good, xxnet:8087 cleared!
Jan 13 09:16:37.550 - [DEBUG] good, xxnet:8085 clear!
Jan 13 09:16:37.550 - [DEBUG] finished confirm_xxnet_exit
Jan 13 09:16:40.255 - [ERROR] start module gae_proxy fail:[Errno 13] Permission denied: 'F:\\programms\\XX-Net-2.8.9\\data\\gae_proxy\\scan_ip.log'
Jan 13 09:16:40.266 - [ERROR] Except stack:Traceback (most recent call last):
  File "F:\programms\XX-Net-2.8.9\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "F:\programms\XX-Net-2.8.9\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\proxy.py", line 98, in <module>
    import proxy_handler
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\proxy_handler.py", line 20, in <module>
    import gae_handler
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\gae_handler.py", line 23, in <module>
    from connect_manager import https_manager
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\connect_manager.py", line 43, in <module>
    from google_ip import google_ip
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\google_ip.py", line 22, in <module>
    from scan_ip_log import scan_ip_log
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\scan_ip_log.py", line 65, in <module>
    scan_ip_log = Scan_ip_log()
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\scan_ip_log.py", line 16, in __init__
    self.open_log()
  File "F:\programms\XX-Net-2.8.9\gae_proxy\local\scan_ip_log.py", line 34, in open_log
    self.log_fd = open(self.log_path, "a")
IOError: [Errno 13] Permission denied: 'F:\\programms\\XX-Net-2.8.9\\data\\gae_proxy\\scan_ip.log'

Jan 13 09:16:40.267 - [INFO] start gae_proxy time cost 2713
Jan 13 09:16:40.267 - [INFO] begin to start web control
Jan 13 09:16:40.267 - [INFO] launcher web control started.
Jan 13 09:16:41.270 - [INFO] get uuid:2faafb67-1aff-4727-9d8f-15ce1bd9f279
Jan 13 09:16:42.278 - [WARNING] check_update fail:URLError(error(10061, ''),)
Jan 13 09:16:42.278 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to F:\programms\XX-Net-2.8.9\data\downloads\README.md, retry:0
Jan 13 09:17:15.679 - [WARNING] request module:gae_proxy start fail
Jan 13 09:17:15.681 - [DEBUG] launcher web_control 127.0.0.1:57373 GET /config?cmd=get_config 
Jan 13 09:17:23.420 - [WARNING] request module:gae_proxy start fail
Jan 13 09:17:23.421 - [WARNING] request module:gae_proxy start fail
Jan 13 09:17:23.421 - [WARNING] request module:gae_proxy start fail
Jan 13 09:17:23.422 - [WARNING] request module:gae_proxy start fail
Jan 13 09:17:23.424 - [WARNING] request module:gae_proxy start fail
Jan 13 09:17:23.425 - [WARNING] request module:gae_proxy start fail

**Comment by xxnet** [comment]
​这个文件权限你检查下：
F:\programms\XX-Net-2.8.9\data\gae_proxy\scan_ip.log

难道start.bat的权限比start.vbs高？你是不是设置了start.bat以管理员启动了？

**Comment by alexbbbb** [comment]
start.bat以管理员启动. start.vbs右键没有以管理员权限运行的菜单

**Comment by alexbbbb** [comment]
已经解决

**Comment by hrbxb** [comment]
问题怎么解决的？
