### ISSUE TITLE
所有带google.com的网址进进不去怎么破

### ISSUE THREAD

**Issue by zhouytforever** [XX-net/XX-Net#1907]
sudo ./start.sh跑完了是不是要注册  AppEngine  了，以前有google账号，不过手机号码一直不行，现在根本上不去带google的网址怎么办？
第一个：https://accounts.google.com/SignUp就拦住了
连的是wifi，软件跑的没有问题，依赖都安装了。

是不是差个公共appid，哪位有

**Comment by xxnet** [comment]
请发诊断和日志信息

**Comment by zhouytforever** [comment]
解决了，先设置代理插件就可以了，之前没有

ps：你们的流程好像不对，没使用代理插件之前是不能上google的，建议将设置代理的步骤提前

**Comment by simonasd** [comment]
@zhouytforever wiki中的使用教程确实有些混乱，抱歉，目前在整理中。
