### ISSUE TITLE
所有带google.com的网址进进不去怎么破

### ISSUE THREAD

**Issue by zhouytforever** [XX-net/XX-Net#1908]
---

问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

---

诊断信息：
sys-platform: x86_64, Linux-3.16.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
os-system: Linux
os-version: #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015
os-release: 3.16.0-57-generic
os-detail: Dist:Ubuntu; Version:14.04; ID:trusty
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
xxnet-version: 2.8.9
python-version: 2.7.6

ipv6-status: 0
gws-ip-num: 231 / 227
network-status: OK
connected-link: 0 / 3
scan-ip-thread-num: 50
ip-quality: 439
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by cdmask** [comment]
proxy_state: Fail
