### ISSUE TITLE
设置应用专用密码 提示：您的帐户不支持您正在尝试的设置。

### ISSUE THREAD

**Issue by WZero** [XX-net/XX-Net#1915]
Goole 申请appid 的步骤变了

设置应用专用密码提示： 您的帐户不支持您正在尝试的设置。

**Comment by xxnet** [comment]
​这是因为你没有启用2步验证，就不要去设置应用专用密码。

去开启允许弱安全应用。

**Comment by WZero** [comment]
嗯 好了 谢谢了 我理解错了 。。。

**Comment by kev1876** [comment]
我开启了，但是任然没有作用

**Comment by Xiecai** [comment]
请问一下，然后呢？我也开启了

**Comment by jzp820927** [comment]
新版 SDK 改用 Oauth 认证，直接部署就行了，不用设置了。

**Comment by yiwsnow** [comment]
不懂
