### ISSUE TITLE
XX-net 是否可以隐藏掉user-agent中的APP-ID

### ISSUE THREAD

**Issue by yoke88** [XX-net/XX-Net#1924]
使用goagent时会自动在user-agent 中加上APP-ID
<pre>
User-agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36 AppEngine-Google; (+http://code.google.com/appengine; appid: s~xxnet-119)
</pre>

**Comment by linhua55** [comment]
你怎么捕捉到的，使用https的话，应该看不到这些

**Comment by xyuanmu** [comment]
同问，一般到Safari/537.36就没了。

**Comment by fletchere** [comment]
我的也有这个问题。

**Comment by Lrevor** [comment]
不能，这是服务端AppEngine自动添加的，除非到谷歌公司去改代码

**Comment by simonasd** [comment]
+1，这是GAE的特性，我们无能为力。因此建议申请appid时，命名不要带有个人信息。
