### ISSUE TITLE
来一发，打算把chrome+xx改为firefox+xx，有以下几点原因

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1926]
1：由于chrome检测机制，每次都要比对Local State文件来强制更改chrome的运行环境，而最近chrome检测越来越频繁了，导致更改的文件差不多10天左右就失效，插件不能便携。和google斗了半年了，烦了。
2：有轻微洁癖，不想用第三方带壳浏览器，比如mychrome，greenchrome等，
3：chrome-xx,不能同步，自动升级。
改成firefox，这些问题就都不存在了，可自动升级，同步，麻烦的只是证书问题。
大家来扯扯咸淡，吹吹牛逼！

**Comment by wenliyang** [comment]
mychrome 只是使 Chrome 可以方便的便携化，不算是带壳浏览器吧

**Comment by yeahwu** [comment]
多出一个程序，看来看出感觉不干净

**Comment by linhua55** [comment]
打patch，自己编译chrome

**Comment by xxnet** [comment]
Windows下​firefox 导入证书，有一个工具，需要2M的压缩包，在
https://github.com/XX-net/nss

你自己看着办

**Comment by yeahwu** [comment]
@linhua55 这家伙源码这么大，艹，6个g，

**Comment by yeahwu** [comment]
@xxnet 嗯，想办法把这小玩意集成到firefox里面去。或许也可以把证书集成到firefox里面去，试试

**Comment by yeahwu** [comment]
另外感觉firefox-xx名字不太屌，得取个响亮点的名字，叫pirate，或者captain，反正和海盗有关的都可以，没办法呀，海盗迷

**Comment by Cat7373** [comment]
firefoxx

**Comment by yeahwu** [comment]
FF-XX

**Comment by simear2004** [comment]
FF证书导入很简单，只是每次升级后要删除原来的证书，再导入新的，这个的确麻烦了点

**Comment by yeahwu** [comment]
FF+XX来了，看哥这办事效率，测试，测试
https://github.com/yeahwu/firefox-xx/archive/master.zip

**Comment by yeahwu** [comment]
刚测试了下，好像不用手动导入证书，已经集成到firefox里面去了，哈哈哈哈

**Comment by Cat7373** [comment]
又没删 CA
0.0

**Comment by yeahwu** [comment]
@Cat7373 测试版嘛，不要在意这些细节，而且还没去掉创建桌面创建快捷方式。

**Comment by yeahwu** [comment]
台湾大选前，争取发布正式版，不能误了大家看大选

**Comment by yeahwu** [comment]
这家伙比chrome还方便，打开即用，不用重启浏览器等等。

**Comment by xxnet** [comment]
​好高兴，找到的nss等了9个月，终于被用上鸟

**Comment by yeahwu** [comment]
@xxnet 大大地址变更了，帮忙合并一下。
还有为什么后面是“鸟”而不是“了”？

**Comment by yeahwu** [comment]
后面打算把wiki开通了，教小白们怎么正确使用火狐，使用脚本，css样式，第三方扩展等等。

**Comment by yeahwu** [comment]
https://www.youtube.com/watch?v=CZtOueYSEXc&feature=youtu.be
看选举

**Comment by fhzyfjy** [comment]
还是喜欢CHROME，速度比FF快很多

**Comment by yeahwu** [comment]
自由度和实用性还是火狐好得多。比如扩展等。
fhzyfjy <notifications@github.com>于2016年1月16日 周六19:33写道：

**Comment by xxnet** [comment]
​@YeahWu
  已经合并

Chrome 的设计方向是内存很多，尽量用硬件加速，因此占用内存方面实在太多了。
在PC上也是最快的。

另外Google 的商业化，使chrome的开放性自然也没有firefox那么好

**Comment by yeahwu** [comment]
谢谢x大，
说到开放性我有得吐槽一下鸟，市面上所有的便携版chrome感觉或多或少的都有些病态，不是加壳，就是外挂。为的就是欺骗chrome不定期环境检测，这就像破解正版win7一样，一样的。便携版chrome类似于ghost版win。
火狐则没有这些限制。

说到chrome和火狐的区别，有一个很形象的比喻。chrome是一辆跑车，火狐则就像变形金刚。
只是许多小白不知道火狐怎么变形…

**Comment by xxnet** [comment]
​没有人去直接改Chrome源码关闭环境检测吗？
Chromium 呢？

**Comment by yeahwu** [comment]
失效很快，所以基本没人改。再加上，大多人很依赖chrome的帐号同步，这也是chrome最大的优势。
Michael.X <notifications@github.com>于2016年1月17日 周日09:41写道：

**Comment by Cat7373** [comment]
自从几年前复杂的FF备份还原机制几次弄丢我的东西后就再也没用过了。。。
不知现在是否有所改善。

**Comment by yeahwu** [comment]
我都是这样备份的，C:\Users\Administrator\AppData\Roaming\Mozilla\Firefox\Profiles，备份"Profiles"文件夹就可以了，插件，脚本，css一样都不会丢。

**Comment by jzp820927** [comment]
本机备份确实比较可靠

**Comment by fykwgl** [comment]
半个月前刚因为你这项目从FF转到Chrome，你居然又给我转回来了……话说这次FF弄个64位的行不？

**Comment by yeahwu** [comment]
好说，好说，64位稍晚点搞定。
