### ISSUE TITLE
XX-Net突然运行不了，出现WindowsError: [Error 2]错误

### ISSUE THREAD

**Issue by chunnallu** [XX-net/XX-Net#1938]
my XX-Net can not be started and shows message as below in cmd:  
出错信息如下：
···

C:\Users\luchu\Desktop\XX-Net-2.8.10>SET PYTHONPATH=

C:\Users\luchu\Desktop\XX-Net-2.8.10>"C:\Users\luchu\Desktop\XX-Net-2.8.10\python27/1.0/python.exe" "C:\Users\luchu\Desktop\XX-Net-2.8.10\launcher/start.py"
Traceback (most recent call last):
  File "C:\Users\luchu\Desktop\XX-Net-2.8.10\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "C:\Users\luchu\Desktop\XX-Net-2.8.10\launcher\win_tray.py", line 18, in <module>
    import win32_proxy_manager
  File "C:\Users\luchu\Desktop\XX-Net-2.8.10\python27\1.0\lib\win32\win32_proxy_manager.py", line 22, in <module>
    CONNECTIONS = winreg.OpenKey(winreg.HKEY_CURRENT_USER, CONN_PATH, 0, winreg.KEY_ALL_ACCESS)
WindowsError: [Error 2]

C:\Users\luchu\Desktop\XX-Net-2.8.10>pause
请按任意键继续. . .
···
for help!!!
求解决办法。

**Comment by chunnallu** [comment]
不是软件的问题，切换账户后，又可以启动软件。记得上午强行结束了一个pythonw的服务，然后下午软件就启动不了了。

it  isn't the software problem,when changed the account of windows ,it works normally again.i remember that i had killed a process named pythonw and then the software could not be started anymore.

**Comment by linhua55** [comment]
是不是权限的问题？
pythonw是在后台启动python程序，不弹出命令行窗口
