### ISSUE TITLE
XX-Net启动不了，试了很多次都不行，跪求帮忙！！

### ISSUE THREAD

**Issue by chunnallu** [XX-net/XX-Net#1946]
日志如下：
D:\XX-Net-2.8.10>SET PYTHONPATH=

D:\XX-Net-2.8.10>"D:\XX-Net-2.8.10\python27/1.0/python.exe" "D:\XX-Net-2.8.10\launcher/start.py"
Traceback (most recent call last):
  File "D:\XX-Net-2.8.10\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "D:\XX-Net-2.8.10\launcher\win_tray.py", line 18, in <module>
    import win32_proxy_manager
  File "D:\XX-Net-2.8.10\python27\1.0\lib\win32\win32_proxy_manager.py", line 22, in <module>
    CONNECTIONS = winreg.OpenKey(winreg.HKEY_CURRENT_USER, CONN_PATH, 0, winreg.KEY_ALL_ACCESS)
WindowsError: [Error 2]

D:\XX-Net-2.8.10>pause
请按任意键继续. . .

**Comment by xxnet** [comment]
​ 2.8.9 能用吗？

 此处 2.8.10 有改动过

**Comment by chunnallu** [comment]
https://github.com/XX-net/XX-Net/issues/1946#issuecomment-172756305

2.8.9可以用

**Comment by xxnet** [comment]
​请贴出状态页，后续研究原因

**Comment by malthae** [comment]
我遇到同样的情况,目前从桌面图标和开机自动启动 都会报这个错误
只有从文件夹里的start.bat可以正常打开
