### ISSUE TITLE
局域网代理问题

### ISSUE THREAD

**Issue by yanton** [XX-net/XX-Net#195]
公司使用的是http代理，我按照教程设置了代理，完美自动切换。

但是过了不到5分钟，墙内网站在自动切换模式下无法打开。墙外一切ok。

我的chrome用的是SwitchyOmega插件，现在的情景有直连，系统代理，goagent等。
（Ps：我装了Proxy SwitchySharp，问题依旧）
我认为在自动切换的时候，插件会在goagent和直连之间切换，无法达到在系统代理和goagent之间切换。

请问有什么解决方法吗？

**Comment by xxnet** [comment]
你仔细看自动模式里，把默认指向公司http代理，而不是直连

在 2015年4月20日 上午3:40，Yantong Wang <notifications@github.com>写道：

**Comment by yanton** [comment]
自动模式里中：默认指向是个下拉菜单，只有直连和goagent，没有系统代理什么的选项

**Comment by xxnet** [comment]
在Profiles里，新建一个模式：比如company，填好ip,端口。
  然后选择company，测试能够正常工作。

然后进入Options，Switch Rules， 最上面一行，默认是Direct Connect，把它改成你的公司代理company。




在 2015年4月20日 下午9:12，Yantong Wang <notifications@github.com>写道：

**Comment by yanton** [comment]
我之前用过这个方法，没有成功

刚才又试了一次，成功了，搞定。

谢谢指导~~~
