### ISSUE TITLE
Chrome篇也搞定了，大家快去找茬！还有x大说的先梳理wiki，臣妾实在是办不到哇！主要是到现在都没搞懂wiki

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1953]
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Chrome%E6%B5%8F%E8%A7%88%E5%99%A8

![czekgquuaaaqols](https://cloud.githubusercontent.com/assets/13328328/12415026/4a2e545e-bed4-11e5-92a0-ad1e6d1b1340.jpg)

**Comment by sbluoquan** [comment]
不错

**Comment by yeahwu** [comment]
这大雪天的，窝在家里，兄弟们出来唠唠嗑，不知道有木有小粉红光临呀！俺最喜欢小粉红了
@Cat7373 @xyuanmu @simonasd @mikedchavez1010 @xxnet ……

**Comment by xxnet** [comment]
​恩啊，可以去小粉红的窝里去宣传宣传

有谁知道哪里是小粉红的窝？

**Comment by yeahwu** [comment]
李毅吧，但是担心他们直接把appid给挤爆了，还有gae有个先天缺陷，fb上不能上图，要小小设置下，表情包大战，不能上图就麻烦了，哈哈

**Comment by yeahwu** [comment]
战斗嘛，首先要提供一个公平的战场环境。所以大家不妨去宣传一下
http://tieba.baidu.com/f?kw=%E6%9D%8E%E6%AF%85&ie=utf-8

**Comment by yeahwu** [comment]
翻墙的小粉红们且不论立场 也不论是否被洗脑 单就他们肯自发的翻出来维护自己心里认为正确的东西的这种态度就比这些只会躲在墙外吐槽一切的人可贵的多  ——张全蛋

**Comment by ARwMq9b6** [comment]
向诸位致敬。

**Comment by xyuanmu** [comment]
辛苦了！小粉红是谁啊？刚刚GG了下没结果 :ghost:

**Comment by jzp820927** [comment]
我也想知道 小粉红 是何许人也，谁来科普科普？

**Comment by yeahwu** [comment]
大多在推上，fb活动，昨天晚7点，今晚7点，小粉红一起出征facebook，蔡英文主页，羅志祥主页，三立主页，苹果日报主页，其实到这个主页看看评论就知道了
小粉红特指 翻墙过来的爱国小青年，因为挂的都是小女生图像，所以叫做小粉红

**Comment by yeahwu** [comment]
她们翻墙，目前观察用的最多的是lantern，天行vpn。gae因为有一定的学习成本，ss需要帐号，用的比较少。

**Comment by yeahwu** [comment]
小粉红攻击武器
![6b98ca8065380cd7fc898ce7a644ad345882810f](https://cloud.githubusercontent.com/assets/13328328/12477569/3a7517da-c06b-11e5-8ce6-5c9c0e88a0ef.jpg)

**Comment by jzp820927** [comment]
涨姿势了！

**Comment by ARwMq9b6** [comment]
会翻墙以前我是一个看到《参考消息》《环球时报》会激动的生物。结缘 code.google.com/p/goagent 后，我浏览了很多 Wikipedia, YouTube 的页面 —— 如梦初醒 —— 之前的我对正义和真相知之甚少。

窃以为“翻墙”总是好的。

**Comment by yeahwu** [comment]
是的，翻墙总是好的，至少能留住一小批人，留住了慢慢也就了解更多了。这是个好现象，然后感觉她们来了后，twitter，facebook中文圈确实多了些许欢乐。

**Comment by yeahwu** [comment]
战场 
https://www.facebook.com/setnews/?fref=ts
https://www.facebook.com/appledaily.tw/?fref=ts&rf=115571221786639
后方
http://tieba.baidu.com/f?kw=%E6%9D%8E%E6%AF%85&ie=utf-8

**Comment by yeahwu** [comment]
在百度上xx-net好像是敏感词，发不了。

**Comment by xxnet** [comment]
​来一篇小粉红的科普文：
http://blog.dwnews.com/post-873289.html


看来xx-net已经获得百度认证了。
可以这样讲，有个工具，上github搜xx 第一个就是

**Comment by mikedchavez1010** [comment]
哈哈，原以为”小红粉“是”年轻的红色知己“呢。看到这样的同类，特别是生活在自由世界的，内心总漾起一种深深的悲哀：虽然手拿智能手机，用着电脑和网络，挎着LV，开着欧美的汽车，住着洋房，但他（她）们的头脑连100多年前的大清和民国的国民都不如。

**Comment by yeahwu** [comment]
其实吧，出来的大多也就00，90后，想想那个时候的自己，也是听到国歌，热泪盈眶。这种年龄的孩子需要引导，而我们作为前辈，更应该谅解。
就好比，经常说“年轻人，应该多出来闯闯！”结果人家出来了，俺们又骂着往回赶，这样是很残忍的。
俺说话从来是口无遮拦的，要吐槽了
现在墙外的人，大多有一种高高在上的感觉，从来就没给过这些小粉红平等交流的机会。不是拿出来挂，就是嘲讽。不是骂“红卫兵”，就是说，“洗脑洗傻了”
俺还见过某开发人员，嘲讽人家的VPN，这，这，这
单说小粉红她们肯自发的翻出来维护自己心里认为正确的东西的这种态度，俺还是比较认可的。何况这次倒真的很少见到她们骂人，这一点值得赞扬！
网上需要不同声音，不论政见或者立场。都是一种声音的话，那和“新闻联播”就没什么区别了。
最后附上D8出征图
![12507088_105357326514845_7312140800745446758_n](https://cloud.githubusercontent.com/assets/13328328/12503014/8f3b3ade-c10a-11e5-8dae-b4e6b7c1b866.jpg)

**Comment by xxnet** [comment]
​赞同

**Comment by yeahwu** [comment]
![12509652_125809641133434_1748628513771777515_n](https://cloud.githubusercontent.com/assets/13328328/12511598/80211846-c14d-11e5-84d9-09e5ff7df511.jpg)

**Comment by Cat7373** [comment]
辛苦0.0

**Comment by yeahwu** [comment]
@Cat7373 妹子干嘛去了，想死俺鸟……

**Comment by Cat7373** [comment]
你可以看咱的 Github 状态页吖。
https://github.com/Cat7373

**Comment by yeahwu** [comment]
汗，不会玩游戏。这么勤劳

**Comment by simonasd** [comment]
有很多人都是抱着解放全世界的想法翻出来，当他们真正意识到“世界”一词所指的具体是什么之后，就会转化了。有句话好像是蔡英文说的，你们来的都是客，等你们回去之后，要记得在正常国家，是可以骂总统的。

从这一点上讲，赵国是不会放任这种行为持续发生的。

**Comment by yeahwu** [comment]
是的，昨晚的出征就被百度官方制止了。但是仍然有一小部分还在活动，只要还留在墙外就有机会转化，俺不看好推上那些没事挂小粉红的人能真正转化小粉红，因为本质上他们和小粉红是一类人。

**Comment by yeahwu** [comment]
居然没有人赞第一张图片？辣么美……

**Comment by mikedchavez1010** [comment]
赞同yeahwu的观点。哈哈，我可能属于yeahwu鄙视的那种”高高在上“之类的人了。谢谢指教。想想学生时代，也曾像这些小红粉那样傻冒过，只不过现在成熟了，会独立思考了。但愿现在的信息技术会让他们比我们那一代转变得更快。

**Comment by yeahwu** [comment]
@mike
mike兄言重了，我就说瞎鸡吧扯淡，不要放在心上。其实是很简单的选择题“毁人”和“度人”。现在的信息技术肯定比我们那时候要“幡然悔悟”得早，😄😄
mike <notifications@github.com>于2016年1月24日 周日23:05写道：

**Comment by mikedchavez1010** [comment]
愿我们相互包容、理解和支持。希望在有生之年，终有一天，我们大家能够自由地飞翔，在真实的世界里面对面，一起举杯。
