### ISSUE TITLE
google.com频繁出现502

### ISSUE THREAD

**Issue by alx696** [XX-net/XX-Net#1957]
1. That’s an error.
   The server encountered a temporary error and could not complete your request.
   Please try again in 30 seconds. That’s all we know.

只有Google搜索出问题，其它如Youtube，FaceBook，Twitter都能正常使用。

诊断信息：
XX-Net Status：

sys-platform: x86_64, Linux-4.2.0-24-generic-x86_64-with-Ubuntu-15.10-wily
os-system: Linux
os-version: #29-Ubuntu SMP Mon Jan 11 18:00:07 UTC 2016
os-release: 4.2.0-24-generic
os-detail: Dist:Ubuntu; Version:15.10; ID:wily
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.8.10
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 3000 / 1294
network-status: OK
connected-link: 11 / 49
scan-ip-thread-num: 0
ip-quality: 124
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AlephAlpha** [comment]
遇到同样的问题。只有google搜索出问题，gmail、地图、云端硬盘等google的其他服务都能正常使用。

**Comment by AlephAlpha** [comment]
好像加了https就没事了……https://www.google.com/
