### ISSUE TITLE
Can't get RC 4 Password Attribute

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#196]
When I saved `RC4 Password` in `config.html` of GoAgent.
The server returned success. But when I refresh the page. 
The value of password is empty.

I've fixed it with Pull Request #175 with commit `ae6ee7afee7c68190b2a1075978426d698f5c1b2`.
You returned the JSON is `password` instead of `passwd` in `get_config`.
But when you `set_config`, the attribute of `RC4 Password` is `passwd`.

In Chinese:
在set_config的时候你POST的参数RC4 Password对应的是passwd的Key.
在get_config的时候你给我的参数的Key实际上是password, 然后在JS中你写的还是passwd. 于是就获取失败了.
我已经随着那个Pull Request #175 一起提交了.

**Comment by xxnet** [comment]
好的！

居然现在才被发现，说明之前都没人用过这个功能，是不是考虑把它放到高级里面？
或者类似高级一样隐藏起来，这样就更简洁了。
哈哈！

2015-04-20 4:37 GMT-04:00 Howard Shieh <notifications@github.com>:

**Comment by zjhzxhz** [comment]
那我把它放到高级功能里面～
稍等哈…… 
那个不忍直视的Pull Request😅😅

发自我的 iPhone

**Comment by zjhzxhz** [comment]
那么问题来了, 哪个效果更好一些呢?

1. 使用箭头的效果
2. 使用开关的效果

个人觉得第2个比较好看呢~
​

On Mon, Apr 20, 2015 at 5:01 PM, Gmail <zjhzxhz@gmail.com> wrote:

> 那我把它放到高级功能里面～
> 稍等哈……
> 那个不忍直视的Pull Request[image: 😅][image: 😅]
>
> 发自我的 iPhone
>
> 在 2015年4月20日，17:00，xxnet <notifications@github.com> 写道：
>
> 好的！
>
> 居然现在才被发现，说明之前都没人用过这个功能，是不是考虑把它放到高级里面？
> 或者类似高级一样隐藏起来，这样就更简洁了。
> 哈哈！
>
> 2015-04-20 4:37 GMT-04:00 Howard Shieh <notifications@github.com>:
>
> > When I saved RC4 Password in config.html of GoAgent.
> > The server returned success. But when I refresh the page.
> > The value of password is empty.
> >
> > I've fixed it with Pull Request #175
> > <https://github.com/XX-net/XX-Net/pull/175> with commit
> > ae6ee7afee7c68190b2a1075978426d698f5c1b2.
> > You returned the JSON is password instead of passwd in get_config.
> > But when you set_config, the attribute of RC4 Password is passwd.
> >
> > In Chinese:
> > 在set_config的时候你POST的参数RC4 Password对应的是passwd的Key.
> > 在get_config的时候你给我的参数的Key实际上是password, 然后在JS中你写的还是passwd. 于是就获取失败了.
> > 我已经随着那个Pull Request #175 <https://github.com/XX-net/XX-Net/pull/175>
> > 一起提交了.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/XX-net/XX-Net/issues/196>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/196#issuecomment-94398508>.
>
>


-- 

谢浩哲

**Comment by zjhzxhz** [comment]
那么问题来了, 哪个效果更好一些呢?

**使用箭头的效果**
![option-with-arrow](https://cloud.githubusercontent.com/assets/1730504/7227282/26b9bd58-e782-11e4-9faf-59090ab77884.png)

**使用开关的效果**
![option-with-switch](https://cloud.githubusercontent.com/assets/1730504/7227288/2e201dee-e782-11e4-9ef4-0774615fa715.png)

个人觉得第2个比较好看呢~

**Comment by xxnet** [comment]
还是第一个直观。
第二个虽然美观上更好，但是传递的意义和本身常用的角色不相符，就像一个开关形状的东西，突然被拿来做成了抽屉的把手。
呵呵。

在 2015年4月20日 上午5:28，Howard Shieh <notifications@github.com>写道：

**Comment by zjhzxhz** [comment]
好, 那我按第一个写.
今晚睡觉前提交一个Commit. :)

**Comment by zjhzxhz** [comment]
Fixed! 看看效果如何~
![advanced-options](https://cloud.githubusercontent.com/assets/1730504/7230329/461cfd32-e79f-11e4-8291-ea148ee71c92.png)

**Comment by xxnet** [comment]
恩，很棒！

2015-04-20 8:53 GMT-04:00 Howard Shieh <notifications@github.com>:
