### ISSUE TITLE
无法修改扫描线程数

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1960]
不管设置成多少点保存后回到状态页都是原来的数字。
版本为 Git：52cddbdd43b3b0c5794d6f803312bc6fddb3a3bf

**Comment by yeahwu** [comment]
我就默默地看着你，不说话！

**Comment by Cat7373** [comment]
知道问题了。。。
要点右边的更新而不是下面的提交。。。
为什么要设计两个按钮。。。

**Comment by xxnet** [comment]
​有道理
