### ISSUE TITLE
有些网站翻了是白屏?

### ISSUE THREAD

**Issue by shinji-ikari** [XX-net/XX-Net#1965]
就像share.dmhy.org这个网站.前阵子还好好.不过最近XX-NET翻墙过去就变成了白屏了.
用VPN的翻能正常打开.是XX-NET需要设置哪里还是?

试过添加 gae_proxy/local/proxy.ini     share.dmhy.org = direct  然后一直提示连接超时. GAE的话就继续保持白屏.

这种情况有解决办法吗?（´Д`）

**Comment by wialny** [comment]
花园打开白屏并不是梯子的锅. 而是这个网站针对GAE的IP返回的403Forbidden页面. 
具体的你可以使用检查元素, 或者查看源代码看到.
想打开这个网站你可以使用其他的翻墙工具, 只要不是google ip应该都可以打开.
最后抱怨下, 这个网站的站长真不知道怎么想的, 明明就已经被墙了, 还要再再过来403我们墙内的人

**Comment by shinji-ikari** [comment]
原来是这样.感谢解答.明白了（´Д`）
