### ISSUE TITLE
您的帐户不支持您正在尝试的设置

### ISSUE THREAD

**Issue by Thyiad** [XX-net/XX-Net#1969]
https://security.google.com/settings/security/apppasswords

设置应用专用密码时一直提示这个，为啥？

**Comment by xxnet** [comment]
​没有启用2阶段验证。
请启用弱安全应用

**Comment by Thyiad** [comment]
哥，我已经启用了啊

![image](https://cloud.githubusercontent.com/assets/3324812/12505832/20598498-c125-11e5-8cea-36e11ca35f73.png)

**Comment by Thyiad** [comment]
呃。。我错了，两个账号一起登陆搞乱了，别回复了，谢谢了！我close掉这个issue
