### ISSUE TITLE
connected link	0 国内网站 正常 但是无法访问需要翻墙的

### ISSUE THREAD

**Issue by dlybz** [XX-net/XX-Net#198]
Property	Value
Sys Platform	linux2
OS System	Linux
OS version	#47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015
OS release	3.16.0-34-generic
OS detail	Dist:Ubuntu; Version:14.04; ID:trusty
architecture	64bitELF
Browser	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.8.12
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087
working appids	000000000000
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2929
connected link	0
ip_connect_interval	

Apr 20 20:32:38 - [DEBUG] GoAgent Web_control 127.0.0.1:53706 "GET /is_ready 
Apr 20 20:32:39 - [INFO] FWD CONNECT xxnet-update.appspot.com:443 
Apr 20 20:32:39 - [DEBUG] get ip:210.158.146.245 t:269
Apr 20 20:32:39 - [DEBUG] tcp conn 210.158.146.245 time:114
Apr 20 20:32:40 - [DEBUG] forward remote disconnected.
Apr 20 20:32:40 - [DEBUG] FWD CONNECT xxnet-update.appspot.com:443 with closed
Apr 20 20:34:29 - [INFO] check_ip add ip:212.188.10.249 time:5002
Apr 20 20:35:56 - [INFO] check_ip add ip:193.192.250.158 time:4626
Apr 20 20:39:22 - [INFO] check_ip add ip:212.188.10.113 time:4433

**Comment by xxnet** [comment]
你似乎没有设置通过XX-Net作为代理，请在浏览器的代理设置那里，设置 http/https方式， 127.0.0.1，端口8087作为代理。

具体操作细节，请搜索对应浏览器，如何设置http代理。

2015-04-20 8:44 GMT-04:00 dlybz <notifications@github.com>:

**Comment by dlybz** [comment]
试了以下 是switchysharp出问题了 应该强制挂比导致的重装switchysharp就好了
