### ISSUE TITLE
xx-net 如何手动部署GAE服务端

### ISSUE THREAD

**Issue by libillgithub** [XX-net/XX-Net#199]
xx-net 如何手动部署GAE服务端，是否跟goAgent的手动部署服务端的方法一致？如果可以是的话，部署完之后是否直接在配置文件(proxy.ini)中填入appids就行了?

**Comment by httpe** [comment]
额……完全是图形界面操作啊……

**Comment by xxnet** [comment]
手动部署，执行 goagent/x.x.x/server/uploader.py 或者 uploader.bat，执行后有帮助
