### ISSUE TITLE
xx-net  IOS9.2  局域网代理  wechat 订阅号中的文章乱码

### ISSUE THREAD

**Issue by KevinSunJin** [XX-net/XX-Net#1994]
Hi 
IOS9.2
Windows 7
xx-net 2.8.10
pythen 2.7.11
iphone通过局域网代理访问网络，有安装CA.crt，
google，facebook，instagram等都是正常，但是在使用wechat的时候打开订阅号中的文章出现乱码问题，通过safari打开也是同样的问题

![img_7622](https://cloud.githubusercontent.com/assets/13011160/12572480/dab3805a-c427-11e5-9384-1e7858239978.PNG)
![img_7623](https://cloud.githubusercontent.com/assets/13011160/12572481/dab5e23c-c427-11e5-91f3-16b48e797fec.PNG)
![qq 20160126120509](https://cloud.githubusercontent.com/assets/13011160/12572482/dab771e2-c427-11e5-9d50-d4c76a162d81.png)

**Comment by KevinSunJin** [comment]
python已经升级到2.7.11，但是还是显示2.7.9


XX-Net Status：

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2618.8 Safari/537.36
xxnet-version: 2.8.10
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 3000
network-status: OK
connected-link: 12 / 50
scan-ip-thread-num: 50
ip-quality: 177
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xyuanmu** [comment]
Windows好像用的是自带的python库。
问一下wechat是微信吗？会不会是那货故意搞的编码问题。

**Comment by KevinSunJin** [comment]
是微信，感觉不像微信的问题，不使用代理的话是正常的，

使用代理：

wechat(iphone)  ×
safari(iphone)    ×

不使用代理：

wechat(iphone) √
safari(Iphone)   √

windows 下打开都是正常的

不使用代理的web adress

http://mp.weixin.qq.com/s?__biz=MjM5MDI5MjAyMA==&mid=401997584&idx=1&sn=dc7ea33a8faf218b330b7176dc4a82d6&scene=0#wechat_redirect

使用代理的web adress

https://mp.weixin.qq.com/s?__biz=MjM5MDI5MjAyMA==&mid=401997584&idx=1&sn=dc7ea33a8faf218b330b7176dc4a82d6&scene=0&key=710a5d99946419d91f7dded4a8c7f06595e0ffc5594e70d0a777d39acf7ad1d4e98dfb42a624cae1de67118a2fac0b63&ascene=1&uin=NDMxNjIwODU%3D&devicetype=iPhone+OS9.2.1&version=16030913&nettype=WIFI&fontScale=100&pass_ticket=8D2ykwdLshCK8zASeps67mVxd5gB8zYI4bRXAi0j4rE%3D

**Comment by KevinSunJin** [comment]
已经好了，HTTP代理设置为“自动”(之前用的是“手动”)  通过PAC自动代理；；

**Comment by kittycheny** [comment]
PAC自动代理下，你是否修改好PAC指向的IP呢？

**Comment by KevinSunJin** [comment]
Hi Kitty
我是直接修改的配置文件，manual.ini   把listen和PAC 下的IP  的值都改为了0.0.0.0，
在设置手机HTTP 自动 代理是设置为  http://*.*.*.*:8086/proxy.pac      *.*.*.*  是我这只的默认IP
