### ISSUE TITLE
俺真是被wiki搞哭了，刚刚在首页点击new page创建了个x-tunnel教程，保存后，就不知道跑哪儿去鸟？

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#1995]
![12472266_203589869992173_5837311030910239332_n](https://cloud.githubusercontent.com/assets/13328328/12573471/86e93872-c434-11e5-8b65-e731c7301c7f.jpg)

**Comment by xyuanmu** [comment]
这个？https://github.com/XX-net/XX-Net/wiki/x-tunnel使用教程

**Comment by yeahwu** [comment]
玩不转哪！玩不转，这个教程还是留给你们大拿来写吧。

**Comment by yeahwu** [comment]
先来个简单的文字教程吧。
首先下载客户端： https://github.com/XX-net/XX-Net/archive/master.zip
解压后点击 start.vbs 运行
点击xx图标，进入web页面
点击配置，模块管理，启用 x_tunnel
然后web主页，左侧栏会有个 x_tunnel，点击 、首页、注册、登录。

下一步，浏览器安装代理插件
火狐用pan或者autoproxy，chrome用SwitchyOmega调用
最后socks5 主机127.0.0.1  端口1080 同ss端口代理
https://github.com/XX-net/XX-Net/wiki/%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86

最后一步
右键x图标，勾选“取消全局代理”  
……END……

**Comment by yechao25038** [comment]
小白一个。大部分都懂，就是“最后socks5 主机127.0.0.1 端口1080 同ss端口代理”始终搞不明白。。实在插件里设置还是在xx配置页面做修改，大大

**Comment by yeahwu** [comment]
在代理插件里修改就好了。
霹靂小黃牛 <notifications@github.com>于2016年1月26日 周二19:59写道：

**Comment by yechao25038** [comment]
了解，谢谢

**Comment by simonasd** [comment]
@yeahwu 
新建的页面，需要点右侧的“page”按钮，再点击“Show 37 more pages…”展开才能看到。

所以需要手动添加到Home页的目录中。

**Comment by yeahwu** [comment]
@simonasd 谢指教，俺有空再搞搞
![6b98ca8065380cd7fc898ce7a644ad345882810f](https://cloud.githubusercontent.com/assets/13328328/12581029/1178e85e-c46f-11e5-9743-89588b621dc9.jpg)

**Comment by caofengzi** [comment]
在瀏覽器的代理擴展裡面的socks5裡面填寫127.0.0.1:1080就行了。就是有時候會斷流。

**Comment by xxnet** [comment]
​斷流 表现是怎样的？
能否重现

**Comment by caofengzi** [comment]
@xxnet 就是有時候在正常訪問網站的時候打開另一個鏈接會打不開。

**Comment by xxnet** [comment]
​刷新一下可以吗？

**Comment by yeahwu** [comment]
据说github不支持断点速传，可以试着下载下面链接，就知道有没有断流？可惜的是我的网络环境测试不了。
https://github.com/yeahwu/firefox-xx/archive/master.zip

**Comment by caofengzi** [comment]
這個是備用，就是xx沒有贈送流量俺也準備捐贈幾個appid，發現用xx的用戶增長非常快，xx內置的appid有時候一啟動就已經沒有流量了，畢竟是眾人拾材火焰高嗎。

**Comment by zengkid** [comment]
这个不是都是自己申请appid吗？
