### ISSUE TITLE
打开后经常提示proxy.ini设置的密码错误，需要重新开启才行

### ISSUE THREAD

**Issue by Dreamray** [XX-net/XX-Net#20]
打开后经常提示proxy.ini设置的密码错误，页上传的goagent服务端是没加密码的，需要重新开启才行，谷歌的域名没有这个问题，像facebook,youtube等非谷歌域名有这个问题，1.02和1.04都是如此，希望能解决下

**Comment by xxnet** [comment]
你的服务端设置密码了吗？
其实没有必要设置密码，被人用了只是一点流量，何况别人要猜到你的appid跟猜密码一样难。
建议服务端不要部署密码，或者你重新申请几个appid，把名字起的复杂一点就好了。
