### ISSUE TITLE
很好,相当棒

### ISSUE THREAD

**Issue by anycall9696** [XX-net/XX-Net#200]
感谢作者,用了多年GoAgent了,XXnet很容易上手,不过我一般启动和别人不一样,我都是计划任务用system账户启动proxy.bat,后台只有个python27.exe,这样感觉更隐蔽
换到xxnet后怎么三个进程了.....
还有就是我导入了net的证书,不知道为什么https://www.google.com/?hl=zh-CN那个HTTPS有红色的警告叉......美国之音等网站也是
总体说来,感觉net更快,尤其设置为1-2秒后,打开速度绝对快于GoAgent
感谢作者,希望不只是现在好用,当受到鸭梨的时候依然能好用
再次感谢,解决我太多问题,搜索,邮件,太感谢了,这几天,唉,愁死了都

**Comment by xxnet** [comment]
要隐蔽，可以
c:\xx-net\python27\1.0\pythonw.exe c:\xx-net\goagent\x.x.x\local\proxy.py
没有黑窗口，只有一个进程。

红叉叉的问题1.8.12已经解决，请确认你使用的版本。

在 2015年4月20日 上午11:26，anycall9696 <notifications@github.com>写道：

**Comment by anycall9696** [comment]
很完美了!红叉的问题没有了,原来是我使用的版本太低,我其实是前几天在GoAgent的issues发现这个直接下载的,下载之后我看到里面有自动更新,我以为我一直使用的最新版呢....

**Comment by xxnet** [comment]
一直在修bug，怕不稳定，所以不敢轻易推送更新。

现在基本稳定了，明天推送更新。

在 2015年4月20日 下午1:52，anycall9696 <notifications@github.com>写道：

**Comment by anycall9696** [comment]
太好了,能自动更新的话,太方便了!
再次感谢,晚安
