### ISSUE TITLE
关闭后重新启动就什么都上不了了

### ISSUE THREAD

**Issue by yeyuguo** [XX-net/XX-Net#2000]
感觉真的是没啥用 就是刚开时候有用  后面关闭后重新启动就什么都上不了了

**Comment by zjgbql** [comment]
从来没有问题的飘过，很好用，比收费的还快，稳定

**Comment by yeyuguo** [comment]
原先我的google通过hosts文件能上的    如果使用再断开xx-net后，原来的google也不能用了的问题...

**Comment by kittycheny** [comment]
这个好办，你不要放在系统盘就可以了。重新下载，解压到其他没有非系统盘的分区上，重新安装。哈哈哈

**Comment by yeyuguo** [comment]
嗯 好的 非常谢谢你的办法，我试试效果看。感谢感谢
