### ISSUE TITLE
上传者已禁止在您的国家/地区播放此视频

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#201]
1.地址：https://www.youtube.com/watch?v=h2PKLBSlfHU
2.win_tray菜单，中文环境下，显示中文菜单，表示祝贺，同时也希望mac得到同样的待遇
3.希望能有个选择框“分享给局域网使用”，省得手工去改listen下的ip地址为0.0.0.0，如果能使用pac服务那就更智能了。
再次感谢作者的辛勤劳动。

**Comment by xxnet** [comment]
1. 请参考：https://github.com/XX-net/XX-Net/wiki/GoAgent-Limitation
2. mac下理论上也可以，昨天试了，获取本地语言时遇到了点麻烦。
  放到改进列表中吧。
3. 这个有讨论过，不建议这么用，会带来更多麻烦，建议每个设备自己装一个。

**Comment by causlayer** [comment]
1.不知道有没有什么曲线的方法可以绕道呢，我在网上找到一个：http://blog.csdn.net/XIAyuzheng/article/details/13168441，不知道有没有用。
2.辛苦了
3.我的意思是可以iphone或者android手机可以使用XX-Net代理翻墙，因为手机设备还不像pc设备功能这么多。例如我在iphone手机可以设置自动代理地址：http://192.168.1.111:8086/proxy.pac，pc端我是每台都独立运行的。

再次感谢作者的辛勤劳动给大家带来的福利

**Comment by xxnet** [comment]
1.一般用PHP模式解决
3. 需要在手机上导入证书，而且不同机器生成的证书不同，所以是很麻烦的。
  当然不怕麻烦是完全可以做到的。

在 2015年4月21日 上午2:46，causlayer <notifications@github.com>写道：

**Comment by causlayer** [comment]
好的，谢谢

**Comment by nictse2013** [comment]
1.一般用PHP模式解决

这个怎么弄能说的细致点么？@xxnet

**Comment by xxnet** [comment]
弄过一次，很麻烦，而且很慢，不喜欢折腾的不推荐。

原理上就是找免费的PHP空间，注册、把服务端部署到PHP空间，然后设置好访问链接。
中间很多环节，根据不同的PHP空间提供商，差异很大。
所以难以细致的提供文档，我只弄过一次，也是调试用，实在太慢，没有真正使用过。

在 2015年7月29日 下午3:39，nictse2013 <notifications@github.com>写道：
