### ISSUE TITLE
请添加android developer的网址~~

### ISSUE THREAD

**Issue by YuFong** [XX-net/XX-Net#2017]

**Comment by cdmask** [comment]
What do you mean?

**Comment by YuFong** [comment]
@cdmask eh...Could you please add https://developer.android.com/ or http://developer.android.com/ to the url list?Because I can not visit these website.Thx~

**Comment by YuFong** [comment]
https://developer.android.com/intl/zh-cn/index.html is OK,I can login in this website.

**Comment by cdmask** [comment]
I can access this website, no problem. What is the problem you have, show the log.

**Comment by YuFong** [comment]
It works now,I was visit the wrong website,which start with http but not https,thx. 发自网易邮箱大师 在2016年01月30日 17:51 ，cdmask写道： I can access this website, no problem. What is the problem you have, show the log. — Reply to this email directly or view it on GitHub.
