### ISSUE TITLE
部署服务端错误

### ISSUE THREAD

**Issue by jackwei86** [XX-net/XX-Net#202]
Log:
Apr 21 10:23:17 - ============  Begin upload  ============
appid:jackwei86 

Apr 21 10:23:17 - Application: jackwei86
Apr 21 10:23:17 - Host: appengine.google.com
Apr 21 10:23:17 - Rolling back the update.
Apr 21 10:23:28 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsObarltGQRCHKVDX1Hti1DH5ar43hSAlrlG1W2921aYXCRJ9EPaN7bUz5Wleys7jYs9ifrMrOd-WHnVQS3DOgRYerSlB94WrpCaGwlXKeVg3dpd2AXdjRli83sJJQhtRmB94sThe4V0xheMnB1AP3SUan1uDDj_bDAdgJgUvNu31mRb_hnLz5QtyFXPBpcoHz1PhRjFX-Ke5foFjsjubwEhmjhJvnfqQKjxgMVPB34d3FCjTI
Info=WebLoginRequired

Apr 21 10:23:28 - upload  fail: can't set attribute

Apr 21 10:23:28 - Retry again.

Apr 21 10:23:29 - Application: jackwei86
Apr 21 10:23:29 - Host: appengine.google.com
Apr 21 10:23:29 - Rolling back the update.
Apr 21 10:23:31 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbuBxmnWD0iBmREnFaKDA-u3rEEGGyK7kbxNPpYlWujg_B0cmlf44RI6Tl2b6Ifj-VogZnitXHBm37c4CBK2e6ScYf4zMiJ8aPYp-VthlcqD7EdSTG8qJzEyAOa8-aWgtv_jnaP-NhNNAZld0ZMP6ueT0WrnSh-0hCrGeTOfVGP2_LbJrzxaBWqqprWt83xpqilpsW-3oZHqriAlY_T0lrnLd28W8w
Info=WebLoginRequired

Apr 21 10:23:31 - upload  fail: can't set attribute

Apr 21 10:23:31 - Retry again.

Apr 21 10:23:32 - Application: jackwei86
Apr 21 10:23:32 - Host: appengine.google.com
Apr 21 10:23:32 - Rolling back the update.
Apr 21 10:23:38 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbtY1EbnYHIkBZZyV4I7_U6XwWmNBjVHnSSLxk5j5idihouocs61PwEU7l969UvJj9CsS7-oayylQR8q3CQ8GGMjDS4Ta0NBshpNxs5SW_GEN43Pjo_3kSbUix7xsUQtmiqca5XiCSw-MZtK5Jnc-v1nq8MU3uYs_vXXM7xqg7qLiTMMXfGH8S_4i1AXymiq61F33gxnxZTvNesntaiUgO05IVmKbRmWWvu5QJxYiDKoUebhsoM
Info=WebLoginRequired

Apr 21 10:23:38 - upload  fail: can't set attribute

Apr 21 10:23:38 - Retry again.

Apr 21 10:23:39 - Application: jackwei86
Apr 21 10:23:39 - Host: appengine.google.com
Apr 21 10:23:39 - Rolling back the update.
Apr 21 10:23:44 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbs8UiGXWd7Es5Sy92to3gEPJ_aOE8YKu1tsBAg_fqFj269ST6eaPTitICC_fy7VGQMgRyS2s9Hb00Kt6iHHAfG2WJXS3Nj0_Lz_UKngoZeAMy1VWMouoW1vw67xYHSR8gHrU_4kIPRbYdevUva1ZBQjV_bvQQdV3vV64jfv87ZHez0rXn9uysBMkPBtrF2u_IpCyLaXhPsFntv-R8Kmwe2o3US7CA
Info=WebLoginRequired

Apr 21 10:23:44 - upload  fail: can't set attribute

Apr 21 10:23:44 - Retry again.

Apr 21 10:23:45 - Application: jackwei86
Apr 21 10:23:45 - Host: appengine.google.com
Apr 21 10:23:45 - Rolling back the update.
Apr 21 10:23:51 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbs3LcIrrjoIhHT5ckkHRvoZhPdB0McrhS3STAUBWIA3tuqQi7gP8j5C-8mmrThyP8wH2KrcdPJmbN50KuvFBi8Jz_2kXMbvOlfa99fGzLUTN9oxc0p9n6fNa5xWL_MyJUcUTJFtHAdr2SbC306-gbRlt-bKZqQAA-TcZyUBDrAVudp4tlvFa-Is6QBUcrl-J3clp2xClMz7_QUhp31f0A1owFjLRCQ1615s1IfGzZCAyMqYT7k
Info=WebLoginRequired

Apr 21 10:23:51 - upload  fail: can't set attribute

Apr 21 10:23:51 - Retry again.

Apr 21 10:23:52 - Application: jackwei86
Apr 21 10:23:52 - Host: appengine.google.com
Apr 21 10:23:52 - Rolling back the update.
Apr 21 10:23:56 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbsxpRn_tTg3cVBYJJAfEZRccgadCI3rr8y4N3ikzsUhvyXWG9q-wAOxWi_lwFEVBrh9ScuqvZCJ0yHqcYfLVr-NjbGTgKgzahWKO5_mnoztCSj4oYKbqEFti8PHJlzW1nizLOpPITas0ZRDj9pfTDje989uoRSDCGcUcWcNCjmoq2_QyETgPUyiYEvw-E5n0ifGfhf36sYAvYP-YKT3Uv-IIETRgB8Y16Tr0KC8Dbsb8kRQ17Q
Info=WebLoginRequired

Apr 21 10:23:56 - upload  fail: can't set attribute

Apr 21 10:23:56 - Retry again.

Apr 21 10:23:57 - Application: jackwei86
Apr 21 10:23:57 - Host: appengine.google.com
Apr 21 10:23:57 - Rolling back the update.
Apr 21 10:24:08 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbtXrmwu8OWwkvK5DXQ8K-d08c3hwgoWxZGP9Cq8Y9zaNwmTaoVcDVhLU1Le_Gtawza74FUDhsIEEN3jfP_ynBTtHgqazxAgL-qJ_VH-oZagUjGG-M0M1MVyX9VH0Po_yl5QMLCRHXRTO6ZOWk01U4RS1q5Sg-E50-CGzYwcQHTOm8zRtrtg25sh4ihdQUomX2pVEbQuAiLXoZ3ijsrsH1m1Chwyp41Iaa2yIRVvEo8KUnRl5hI
Info=WebLoginRequired

Apr 21 10:24:08 - upload  fail: can't set attribute

Apr 21 10:24:08 - Retry again.
-------------------------------------------------------------------------------------------------------------
![qq 20150421102545](https://cloud.githubusercontent.com/assets/12042959/7244632/ea2c22d8-e810-11e4-809b-58cf247301eb.png)

**Comment by xxnet** [comment]
你密码错了。

你可以试试最新版，会有中文提示

2015-04-20 22:27 GMT-04:00 jackwei86 <notifications@github.com>:
