### ISSUE TITLE
年前最后一帖了哦，因为俺也要放假了。需要x-tunnel流量的赶紧注册，留下注册邮箱，限今明两天。放假，放假

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2020]
x-tunnel下载：https://github.com/XX-net/XX-Net/archive/master.zip
使用方法：https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B
另：不会使用代理插件的，请不要注册。谢谢

**Comment by yeahwu** [comment]
放假后，也就不会上外网了，在家聊聊qq，搞搞微信，遛遛知乎，榕树下写写暖文……陶冶一下情操。

不要问我，为什么是你派流量？
1:这种小事就不用x大出马了，频繁露面，不利于x大的安全。
2:你不能排除俺就不是x大？不是@Cat7373?不是@simonasd?
3:不要问那么多为什么？

**Comment by Cat7373** [comment]
cat7373@github.com
种子福利神马的大把大把的往这里发吧！！！

**Comment by yeahwu** [comment]
@Cat7373 明显你这个邮箱是无效的，哼，想骗俺

**Comment by Cat7373** [comment]
https://github.com/drduan/minggeJS/issues/214#issuecomment-176586826
Cat7373教你找茬。

**Comment by yeahwu** [comment]
目测，后面会有一大群喊“明嫂”的，哈哈哈

**Comment by xyuanmu** [comment]
那，提前祝你新年快乐！

**Comment by yeahwu** [comment]
@xyuanmu 谢谢，同乐。:blush::blush::blush:

**Comment by holiday5** [comment]
send me some wayne-yu @live.com

**Comment by yeahwu** [comment]
@holiday5 显示wayne-yu@live.com这个id无效，请确认能登录

**Comment by CHN008** [comment]
**要流量** zhoukvi#163.com

**Comment by yeahwu** [comment]
@CHN008 已转请查收。

**Comment by CHN008** [comment]
2.0GB,多谢! 哈哈.
**预祝新年快乐! **

**Comment by yeahwu** [comment]
@CHN008 有点少，试用先！不要介意，同乐、同乐。

**Comment by CHN008** [comment]
@yeahwu 不少了, 收一下邮件够用很久.

再说还有Gae的流量和其它的.先把电邮地址匿了.

你们定的价格也很实惠了,会推荐给朋友用的.

**Comment by zjhzxhz** [comment]
@yeahwu Hello~
zjhzxhz@gmail.com
谢谢~

**Comment by yeahwu** [comment]
@zjhzxhz 已转，请查处

**Comment by zjhzxhz** [comment]
@yeahwu 
Cool~ BTW, 你们竟然背着我写了这么丑的UI.
等我过几天提交一个PR XD

**Comment by yeahwu** [comment]
@zjhzxhz 好的，好的。感谢

**Comment by CyrusYzGTt** [comment]
cyrushmh@foxmail.com
在 2016年01月29日 20:33, YeahWu 写道:

**Comment by yeahwu** [comment]
@CyrusYzGTt 
已转，请查收

**Comment by CyrusYzGTt** [comment]
谢谢
在 2016年01月29日 21:43, YeahWu 写道:

**Comment by holiday5** [comment]
为啥，因为我刚注册的吗？

**Comment by holiday5** [comment]
altlance @gmail.com 试下

**Comment by yeahwu** [comment]
显示你的id无效，你至少登录一次嘛。看一下一楼的教程

**Comment by pgz123** [comment]
新春如意，要流量

**Comment by mervinwei** [comment]
joiedevivre#163.com
谢谢

**Comment by yeahwu** [comment]
@mervinwei 已转，请查收

**Comment by yeahwu** [comment]
@holiday5 已转，请查收

**Comment by wpyok500** [comment]
wpyok500@gmail.com已注册

**Comment by yeahwu** [comment]
@wpyok500 已转，请查收

**Comment by simonasd** [comment]
@zjhzxhz 

>你们竟然背着我写了这么丑的UI.

哈哈哈，就是为了把你们这些人逼出来提PR。

**Comment by zjhzxhz** [comment]
@simonasd 
你们这些坏人!

**Comment by pgz123** [comment]
新春如意，要流量/ @yeahwu

**Comment by yihong0618** [comment]
zouzou0208@gmail.com 谢谢~~
