### ISSUE TITLE
更新版本后旧证书不能自动删除 Firefox每次要重新手动 可有办法自动？

### ISSUE THREAD

**Issue by withero** [XX-net/XX-Net#203]
XX-Net真是给力，使用简单，更新即时，但每次更新都比较麻烦，Firefox要重新手动删除旧证书导入新证书，IE旧证书会一直保存在那里。
IE旧证书的存在直接导致不能访问github.com。
好像Firefox使用自动代理也不能正常文件github.com。

**Comment by xxnet** [comment]
这个问题有研究过，Windows下有一个NSS工具，理论上可以做到Linux下的效果，自动更新证书。
不过这个工具包要2M大小，不想打包进去。

其实可以在检测到Windows下有安装Firefox，就启动一个线程下载这个安装包，然后导入证书。

在 2015年4月21日 上午2:49，withero <notifications@github.com>写道：

**Comment by xxnet** [comment]
已经把这个二进制工具放到github上：
https://github.com/XX-net/nss

找这个工具都找了很久。

在 2015年4月21日 上午3:01，Net XX <xxnet.dev@gmail.com>写道：

**Comment by withero** [comment]
感谢，只是不会用。汗~~~~

**Comment by xxnet** [comment]
这个要为了后面写成脚本的配套工具。
目前先手动导入吧

2015-04-21 20:55 GMT-04:00 withero <notifications@github.com>:

**Comment by hyskyder** [comment]
我一直沿用老版本的证书。用老版本data/goagent文件夹下面的CA.crt覆盖新版本的CA.crt就行了啊，这样IE和Firefox就不用更新证书了。
