### ISSUE TITLE
更新XX-Net自带python库到2.7.11

### ISSUE THREAD

**Issue by xyuanmu** [XX-net/XX-Net#2037]
前几天看到有人在Windows上更新python库，可是xx-net依然是2.7.9，想必Windows版的xx-net用的是自带的库，今天心痒痒试着更新了下，并且打包主要文件，只留下 crypto、darwin、linux、noarch、win32 五个文件夹，因为不想看到一堆的 .pyc，强迫症没办法。不知道为什么 .pyd 文件不能打包进 python27.zip 中，一打包就提示imporError。

下载测试：https://github.com/xyuanmu/XX-Net/archive/master.zip
已测试平台：WinXp、Win7、Ubuntu，感谢大家反馈。

![xx-net](https://cloud.githubusercontent.com/assets/12442896/12700552/faebfbf0-c822-11e5-91e2-c6aa0bb2a070.png)
![winxp](https://cloud.githubusercontent.com/assets/12442896/12709020/5bf32bac-c8e2-11e5-996e-d9b592b473d6.png)
![ubuntu](https://cloud.githubusercontent.com/assets/12442896/12709347/f0d0e6e4-c8e5-11e5-93f4-c0418b279179.png)

另外我想问下有人知道 LIBEAY32.dll、SSLEAY32.dll 这两个文件是做什么的么？因为没有这两个文件不影响运行xx-net所以没加进去。

**Comment by yeahwu** [comment]
点个赞，可惜没办法测试。

**Comment by Cat7373** [comment]
感觉现在很多地方都遵循能用就成的态度。。。
而且py的库有些文件曾经打过patch，而且是直接改的文件，换起来很麻烦。。。
所以既然现在的能用，换了也没啥好处。。。
就一直不换了。。。

**Comment by caofengzi** [comment]
@xyuanmu 替換試了一下感覺速度有所提升的感覺。

**Comment by xyuanmu** [comment]
py库里加的东西我全保留了，只把python最原始的代码放到压缩包里，省了不少空间，而且使用起来CPU不升反降，估计2.7.11优化比较好。

**Comment by Cat7373** [comment]
你可以试着提个 Pull 0.0

**Comment by xyuanmu** [comment]
@Cat7373 等多点用户试用反馈吧，自己一个测试太局限了。有win10用户最好了，不知道这个版本能否解决破音问题。

**Comment by Cat7373** [comment]
@xyuanmu 
你 Fork 一个然后把 Python 库更新了，顺道提交个 Pull，酱紫才方便别人测试嘛~

**Comment by xyuanmu** [comment]
@Cat7373 有道理，不过我发现11比9更占内存，刚开始以为是压缩的原因，解压出来还是妥妥地吃了我24+M内存，不过咱内存管够。

**Comment by Gonesave** [comment]
换掉之后XX-NET就启动不了是什么情况

**Comment by xyuanmu** [comment]
@Gonesave 你是怎么换的，直接覆盖还是重命名？启动报错日志能不能发来看看。

**Comment by Gonesave** [comment]
@xyuanmu 覆盖啊，不会是要重命名吧............

**Comment by xyuanmu** [comment]
@Gonesave :dizzy_face:重命名也好有歌备份莫......

**Comment by Gonesave** [comment]
@xyuanmu 所以到底怎么用

**Comment by Cat7373** [comment]
所以说@xyuanmu 把你修改好的提交到你 Fork 的项目里呀- -
方便大家下载测试- -

**Comment by Gonesave** [comment]
你俩回复好快啊............

**Comment by Gonesave** [comment]
好了更完了

**Comment by xyuanmu** [comment]
@Cat7373 糟糕，GitHub不知为什么卡住了，这里也半天刷新不出来，挂代理访问的，囧:alien:

**Comment by Gonesave** [comment]
@xyuanmu WIN10表示更了之后速度直线下降

**Comment by xyuanmu** [comment]
@Gonesave 不会吧，看来还是不能解决win10的问题

**Comment by xyuanmu** [comment]
一直卡在：Writing objects:  56% (9/16)，看来今天是不能成功push了，明天再试试。各位晚安！

**Comment by Gonesave** [comment]
@xyuanmu 晚安

**Comment by SusakeGit** [comment]
谢谢，加油哦。

发自WPS邮箱客戶端在 xyuanmu <notifications@github.com>，2016年1月31日 下午10:46写道：一直卡在：Writing objects:  56% (9/16)，看来今天是不能成功push了，明天再试试。各位晚安！

**Comment by Gonesave** [comment]
哎，问你们个事你们知道那个X_tunnel的流量怎么弄不 @Cat7373 @xyuanmu

**Comment by xyuanmu** [comment]
流量暂时是跟 @yeahwu 要的，不过他现在放假了，嗯，就这样。

**Comment by Cat7373** [comment]
https://github.com/xyuanmu/XX-Net/archive/master.zip
下载这个地址来测试

**Comment by Gonesave** [comment]
@Cat7373 下载了当时我要流量，还有Σ(｀д′*ノ)ノ我居然用了QQ邮箱注册

**Comment by jzp820927** [comment]
@Gonesave 捐赠 APPID 也可以获取流量，X大推荐通过捐赠 APPID 来获取流量。

**Comment by caofengzi** [comment]
如果自己有多餘的appid或者可以多申請到appid的話最好是捐贈appid，這樣既可以利益他人自己也獲得了流量，因為還有很多人不懂得怎麼申請appid。

**Comment by github-xx** [comment]
升级后运行正常，windows 10 企业版 OS Ver：10586.71

**Comment by Gonesave** [comment]
windows 10 專業版依然有會有聲音問題

**Comment by diggerdu** [comment]
请问xx-net是怎么把python环境打包起来的

**Comment by xxnet** [comment]
​没有特别处理，只是把python 目录拷贝进去就能用了

**Comment by yeahwu** [comment]
😄，xyuanmu也回来了！好久不见
xyuanmu <notifications@github.com>于2016年6月18日 周六14:20写道：

**Comment by ManchesterWuer** [comment]
同问，xx-net是如何把python环境打包起来的？

**Comment by jzp820927** [comment]
好像就是一个简单的 zip压缩包，然后用 py 来引用，如果你不是 程序猿，估计很难解释清楚

**Comment by ManchesterWuer** [comment]
搞定如何打包python环境了，用的是python官方出的embedded python zip

**Comment by jzp820927** [comment]
感觉打包，不是必须的吧，也没什么太大的意义。
