### ISSUE TITLE
403 

### ISSUE THREAD

**Issue by zhengwhizz** [XX-net/XX-Net#204]
不时的会出现403错误，有人说是Google服务器不允许造成的，但是经过观察其它网站也会不时的出现这种情况，刷新两三次后可能就能正常访问。

**Comment by xxnet** [comment]
请贴出日志看看

**Comment by Botrix** [comment]
今天遇到同样的问题,不时的会出现403错误，显示下面这个页面：
共用appid因为资源有限，限制观看视频和文件下载等消耗资源过多的访问，请使用自己的appid。点击详情

注：已经配置了自己的appid，打开的是普通网页
////////////////////////////////////////////////////////////////////////////////////////
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
XX-Net Version	1.3.6
Launcher Version	1.0.8
GoAgent Version	3.1.40
Python Version	2.7.9
////////////////////////////////////////////////////////////////////////////////////////
Apr 25 22:30:13 - [DEBUG] tcp conn 210.242.125.50 time:100
Apr 25 22:30:16 - [INFO] FWD CONNECT ssl.gstatic.com:443 
Apr 25 22:30:16 - [DEBUG] get ip:173.194.38.218 t:735
Apr 25 22:30:16 - [DEBUG] get ip:210.242.125.49 t:790
Apr 25 22:30:16 - [DEBUG] tcp conn 210.242.125.49 time:111
Apr 25 22:30:16 - [DEBUG] tcp conn 173.194.38.218 time:646
Apr 25 22:30:31 - [DEBUG] FWD CONNECT clients4.google.com:443 with closed
Apr 25 22:30:34 - [DEBUG] ssl_pool.get:216.239.38.123 handshake:476
Apr 25 22:30:34 - [DEBUG] ssl conn_num:22
**Apr 25 22:30:35 - [WARNING] public appid deny this host:www.google.cn**
Apr 25 22:30:35 - [DEBUG] ssl_pool.get:64.233.162.87 handshake:788
Apr 25 22:30:35 - [DEBUG] ssl conn_num:21
Apr 25 22:30:36 - [INFO] "GAE t:728 speed:1348 len:982 status:200 GET http://www.google.cn/favicon.ico HTTP/1.1"
Apr 25 22:30:41 - [INFO] FWD CONNECT www.google.com.hk:443 
Apr 25 22:30:41 - [DEBUG] sort ip time:4
Apr 25 22:30:41 - [DEBUG] get ip:210.242.125.50 t:200
Apr 25 22:30:42 - [DEBUG] tcp conn 210.242.125.50 time:101
Apr 25 22:30:52 - [DEBUG] forward local disconnected.
Apr 25 22:30:52 - [DEBUG] FWD CONNECT www.google.com.hk:443 with closed
Apr 25 22:31:15 - [DEBUG] FWD CONNECT ssl.gstatic.com:443 with closed
Apr 25 22:31:19 - [DEBUG] FWD CONNECT csi.gstatic.com:443 with closed
Apr 25 22:31:22 - [DEBUG] FWD CONNECT ssl.google-analytics.com:443 with closed
Apr 25 22:31:32 - [DEBUG] FWD CONNECT www.google.com:443 with closed
Apr 25 22:31:43 - [INFO] FWD CONNECT www.google.com.hk:443 
Apr 25 22:31:43 - [DEBUG] sort ip time:3
Apr 25 22:31:43 - [DEBUG] get ip:210.242.125.50 t:203
Apr 25 22:31:43 - [DEBUG] tcp conn 210.242.125.50 time:114
Apr 25 22:31:53 - [DEBUG] forward local disconnected.
Apr 25 22:31:53 - [DEBUG] FWD CONNECT www.google.com.hk:443 with closed
Apr 25 22:31:53 - [DEBUG] ssl_pool.get:64.233.162.87 handshake:788
Apr 25 22:31:53 - [DEBUG] ssl conn_num:19
Apr 25 22:31:53 - [DEBUG] sort ip time:5
Apr 25 22:31:53 - [DEBUG] get ip:210.242.125.49 t:223
Apr 25 22:31:54 - [DEBUG] ssl_pool.get:64.233.162.86 handshake:825
Apr 25 22:31:54 - [DEBUG] ssl conn_num:18
Apr 25 22:31:54 - [DEBUG] get ip:210.242.125.50 t:228
Apr 25 22:31:54 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:847
Apr 25 22:31:54 - [DEBUG] ssl conn_num:17
Apr 25 22:31:54 - [DEBUG] get ip:216.239.38.123 t:305
Apr 25 22:31:54 - [DEBUG] ssl_pool.get:210.242.125.50 handshake:847
Apr 25 22:31:54 - [DEBUG] ssl conn_num:16
Apr 25 22:31:54 - [DEBUG] get ip:173.194.38.218 t:835
Apr 25 22:31:54 - [DEBUG] create_ssl update ip:216.239.38.123 time:519

**Comment by xxnet** [comment]
1.3.6是早期的版本，是有这个问题，刷新就好了

2015-04-25 10:42 GMT-04:00 Botrix <notifications@github.com>:

**Comment by tj8m23le** [comment]
报告 1.12.3仍然403 无好转迹象

**Comment by totoleo** [comment]
报告，最新版本，google搜索 403，这是错误提示：

403. That’s an error.

Your client does not have permission to get URL /sorry/IndexRedirect?continue=https://www.google.com/search%3Fnewwindow%3D1%26q%3Dssss%26cad%3Dh&q=CGMSBHoLJTsYx-2utwUiGQDxp4NLEQFOXQuA3sz2caj161Byl1UY6gEqNmh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vc2VhcmNoP25ld3dpbmRvdz0xJnE9c3NzcyZjYWQ9aA from this server. That’s all we know.
版本是：2.9.5
