### ISSUE TITLE
能否解决Android端证书问题

### ISSUE THREAD

**Issue by hotact** [XX-net/XX-Net#205]
通过修改Listen，手机Play商店能访问但是不能下载，导入goagent的手机通用证书也无法下载。能否生成一个本地的支持Android的手机证书。

**Comment by Cat7373** [comment]
安卓的证书是无法自动导入的（除非Root）
现阶段还是手动导入吧亲- -

**Comment by zhout26** [comment]
@Cat7373 How to import CA manually?

**Comment by linhua55** [comment]
android设备:
设置-->安全和隐私(或带有“安全”字眼的)-->凭据存储(或意思差不多的)-->从SD卡安装   
然后找到证书文件

**Comment by xinyan3** [comment]
如何手动导入证书？app都不能联。浏览器可以

**Comment by xxnet** [comment]
gae​证书问题无法解决，app很多是内置证书的。

用x-tunnel，没有证书问题，代理端口是1080
