### ISSUE TITLE
我们需要更多的免费服务器

### ISSUE THREAD

**Issue by yaoguaishou** [XX-net/XX-Net#2053]
随着使用人数越来越多，IP被封速度越来越快。总有一天会扫描不出来任何IP。

**Comment by linhua55** [comment]
这个是没办法的事。
封IP的同时，会有少量IP被解封。除非是特殊时期，会大量封IP，不过一般是先封锁高速IP，这时就看不了youtube了，然后使用人数会下降。

**Comment by jzp820927** [comment]
主要是封锁亚洲的IP吧

**Comment by xyuanmu** [comment]
据前段时间扫IP，我发现老毛子的IP有很多，但是延时都很高，不适合看视频，只能开网页。质量高的日韩东南亚地区的IP残段很多。

**Comment by jzp820927** [comment]
现在质量高的日韩东南亚地区的IP段，变动挺快的，一个24段，一般几天都会变动一次！

**Comment by simonasd** [comment]
GAE可利用的服务器，规模大约在百万以上。在这个数量级，继续增加服务器数量意义不大，如果GFW能把Google的服务器全封，那么就算再增加10万台，也不会有太大的差别。

说到封锁，据网友反馈，很多地区的ISP人为劣化国际线路通信质量，制造“国外网站很慢”的大众认知，加上GFW长期的屏蔽和丢包，过不了几年，恐怕直接拔海底光缆，民间都不会有什么反抗（类似于Google在中国最终被全局屏蔽）。我觉得，当局要“战胜”XX-Net，路线图应该就是这样。人工智能封锁、机器学习之类的方案，短时间内还应对不了全国规模的流量。

**Comment by xiuluo** [comment]
估计以后就是不对个人用户开放国外IP访问权限
