### ISSUE TITLE
xvideo无法播放

### ISSUE THREAD

**Issue by ehfwoievbewoig** [XX-net/XX-Net#206]
点击播放按钮后，会在审查元素中看到如下的一个HTTP请求
http://porn.im.6bb2c300.3796594.x.xvideos.com/videos/flv/c/9/6/xvideos.com_c962a2813897326e58fb58a891ce520c.flv?e=1429679017&ri=1024&rs=85&h=7e78eee2a0cee624029acd1e114aa011
但是这个请求会连接超时

Apr 22 10:09:39 - [DEBUG] sort ip time:5
Apr 22 10:09:39 - [DEBUG] get ip:210.158.146.208 t:207
Apr 22 10:09:39 - [DEBUG] tcp conn 210.158.146.208 time:102
Apr 22 10:09:43 - [WARNING] APPID error:502 url:http://porn.im.6bb2c300.3796594.x.xvideos.com/videos/flv/c/9/6/xvideos.com_c962a2813897326e58fb58a891ce520c.flv?e=1429679017&ri=1024&rs=85&h=7e78eee2a0cee624029acd1e114aa011
Apr 22 10:09:43 - [DEBUG] ssl_pool.get:210.158.146.245 handshake:253

**Comment by xxnet** [comment]
是不是最新版本？

2015-04-21 22:10 GMT-04:00 ehfwoievbewoig <notifications@github.com>:

**Comment by ehfwoievbewoig** [comment]
XX-NET 1.9.1无法播放
Goagent3.2.3(直接从Github下载的zip包)可以

**Comment by Cat7373** [comment]
http://cat73.sinaapp.com/xx-net/good_ips_sort.html
试试这个小工具吧 把good_ip.txt的内容复制进去 点Sort按钮即可
会自动排序后显示前100个在下面的框框里

把结果复制到Goagent的proxy.ini里
[iplist]
google_hk = 下面的框框里显示的内容复制到这里

在问题解决之前可以试试用这种办法加速Goagent

**Comment by internetic** [comment]
xxnet1.10.1可以播放
