### ISSUE TITLE
间歇性不能连上 XDA

### ISSUE THREAD

**Issue by xian2xian2** [XX-net/XX-Net#2064]
如题，有时候走 XX-Net 连不上 XDA，浏览器报502错，Dev Tools 显示卡在「Waiting (TTFB)」，同一时间上其它站没这个问题，手机上用赛风连 XDA 也没出这个问题

广东电信，用了私有 appid

浏览器显示：
Message From FetchServer
Python Urlfetch Error: 'GET'

DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: http://forum.xda-developers.com/',), timeout=19
DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: http://forum.xda-developers.com',), timeout=38

XX-Net Status：

sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:14257; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2633.3 Safari/537.36
xxnet-version: 2.8.10
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 454 / 219
network-status: OK
connected-link: 11 / 50
scan-ip-thread-num: 100
ip-quality: 141
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by thebestwayto** [comment]
我也有这种问题
