### ISSUE TITLE
FWD CONNECT www.google-analytics.com:443 

### ISSUE THREAD

**Issue by harryhkyy** [XX-net/XX-Net#207]
GoAgent状态信息
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_TW
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.9.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	harryhky|harryhkyy|harryhkyy2|harryhkyy3|harryhkyy4|harryhkyy5|harryhkyy6|harryhkyy7|harryhkyy8|harryhkyy9|harryhkyy10|harryhkyy11|harryhkyy12|harryhkyy13|harryhkyy14|harryhkyy15|harryhkyy16|harryhkyy17|harryhkyy18|harryhkyy19|harryhkyy20|harryhkyy21|harryhkyy22|harryhkyy23|harryhkyy24|harryhkyy25|harryhkyy26|harryhkyy27|harryhkyy28|harryhkyy29|harryhkyy30|harryhkyy31|harryhkyy32|harryhkyy33|harryhkyy34|harryhkyy35|harryhkyy36|harryhkyy37|harryhkyy38|harryhkyy39|harryhkyy40|harryhkyy41|harryhkyy42|harryhkyy43|harryhkyy44|harryhkyy45|harryhkyy46|harryhkyy47|harryhkyy48|harryhkyy49
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	4
connected link	19

Apr 22 11:41:21 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 22 11:41:21 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 22 11:41:21 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 22 11:41:21 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 22 11:41:21 - [WARNING] create tcp connection fail.
Apr 22 11:41:21 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 22 11:41:21 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 22 11:41:21 - [WARNING] create tcp connection fail.
Apr 22 11:41:21 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 22 11:41:21 - [WARNING] create tcp connection fail.
Apr 22 11:41:21 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 22 11:41:21 - [WARNING] create tcp connection fail.
Apr 22 11:41:21 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 22 11:41:21 - [WARNING] create tcp connection fail.
Apr 22 11:41:21 - [WARNING] FWD CONNECT www.google-analytics.com:443 create_connection fail
Apr 22 11:41:21 - [INFO] GAE t:683 s:0 304 https://fbstatic-a.akamaihd.net/rsrc.php/v2/yG/r/IBYl-1i7HGn.css
Apr 22 11:41:21 - [INFO] GAE CONNECT fbstatic-a.akamaihd.net:443 
Apr 22 11:41:21 - [INFO] GAE CONNECT fbstatic-a.akamaihd.net:443 
Apr 22 11:41:21 - [DEBUG] GAE CONNECT GET https://fbstatic-a.akamaihd.net/rsrc.php/v2

**Comment by xxnet** [comment]
你的google ip怎么只剩下4个？

**Comment by xxnet** [comment]
请先关闭，
删除 data/goagent/good_ip.txt
重新启动

**Comment by davizrrrr** [comment]
> 请先关闭，
> 删除 data/goagent/good_ip.txt
> 重新启动
>
