### ISSUE TITLE
X-Tunnel Return Status Code 502

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#2073]
我最近几天在改进 X-Tunnel 部分的用户体验。
但是最近调试的时候发现 X-Tunnel 的服务器跪了，所有请求全部返回502。

![screen shot 2016-02-10 at 09 36 59](https://cloud.githubusercontent.com/assets/1730504/12936570/c0a9cb56-cfda-11e5-9ea0-b6176b92f2e7.png)

BTW，X-Tunnel 的 UI 和 Translation 真是无力吐槽。

**Comment by jzp820927** [comment]
不会吧，才推出几天，都跪了，看来一个服务器还是力不从心啊
