### ISSUE TITLE
设置部署好了，也装了switchyomega了，但是还是上不了外网

### ISSUE THREAD

**Issue by jebchedan** [XX-net/XX-Net#2074]
XX-Net Version	2.8.10
Python Version	2.7.11
System Platform	armv7l, Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4
OS System	Linux
OS Version	#2 SMP PREEMPT Tue Dec 29 20:47:03 CST 2015
OS Release	2.6.36.4brcmarm
OS Detail	Dist:; Version:; ID:
Language	
Architecture	32bit,
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36

**Comment by jebchedan** [comment]
打开翻墙的网站就显示这个

您的连接不是私密连接

攻击者可能会试图从twitter.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_INVALID
  自动向Google报告可能出现的安全事件详情。隐私权政策
重新加载隐藏详情
twitter.com 通常使用加密技术来保护您的信息。Chrome 此次尝试连接到 twitter.com 时，此网站返回了异常的错误凭据。这可能是因为有攻击程序在试图冒充 twitter.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问twitter.com，因为此网站发送了Chrome无法处理的杂乱凭据。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by wenliyang** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Chrome%E6%B5%8F%E8%A7%88%E5%99%A8

看“手动导入证书”
