### ISSUE TITLE
[Bug] 1.92 无法使用gmail扩展

### ISSUE THREAD

**Issue by tianzhisun** [XX-net/XX-Net#208]
我使用的扩展如下：https://chrome.google.com/webstore/detail/checker-plus-for-gmail/oeopbcgkkoapgobdbedcemjljbihmemj?utm_source=chrome-app-launcher-info-dialog 

1.88版一切正常。 

pr 22 12:52:34 - [INFO] GAE CONNECT clients4.google.com:443 
Apr 22 12:52:34 - [DEBUG] GAE CONNECT POST https://clients4.google.com/invalidation/lcs/request?authuser=1 
Apr 22 12:52:34 - [DEBUG] ssl_pool.get:61.19.1.182 handshake:343 
Apr 22 12:52:34 - [DEBUG] ssl conn_num:20 
Apr 22 12:52:34 - [INFO] GAE t:388 s:0 204 https://clients4.google.com/invalidation/lcs/request?authuser=1 
Apr 22 12:52:42 - [INFO] GAE CONNECT talkgadget.google.com:443 
Apr 22 12:52:42 - [DEBUG] GAE CONNECT POST https://talkgadget.google.com/u/1/_/diagnostics/?_reqid=645711&rt=j 
Apr 22 12:52:42 - [DEBUG] ssl_pool.get:61.19.1.182 handshake:343 
Apr 22 12:52:42 - [DEBUG] ssl conn_num:20 
Apr 22 12:52:42 - [INFO] GAE t:439 s:59 200 https://talkgadget.google.com/u/1/_/diagnostics/?_reqid=645711&rt=j 
Apr 22 12:52:45 - [INFO] GAE CONNECT mail.google.com:443 
Apr 22 12:52:45 - [DEBUG] GAE CONNECT POST https://mail.google.com/mail/u/1/?ui=2&ik=c587ed97c1&rid=fe19..&view=tl&start=0&num=30&lhop=68467<up=%5Ei&slmm=14cd456da953173a&scid=5oiowv1zlgdx&avw=1748&ntlv=10&auto=1&ver=QZO1fiuYm1w.zh_CN.&am=!vnTMmHVpype3JseDLxvLA_yz78B_as2fBAM27gc3CwMLp18SQJa-pLxsPXVzpBvNHFY-qwN9&vas=1&ari=300&_reqid=1345636&usus=1&pcd=1&mb=0&rt=j&search=inbox 
Apr 22 12:52:45 - [DEBUG] ssl_pool.get:61.19.1.182 handshake:343 
Apr 22 12:52:45 - [DEBUG] ssl conn_num:20 
Apr 22 12:52:45 - [INFO] GAE t:649 s:1358 200 https://mail.google.com/mail/u/1/?ui=2&ik=c587ed97c1&rid=fe19..&view=tl&start=0&num=30&lhop=68467<up=%5Ei&slmm=14cd456da953173a&scid=5oiowv1zlgdx&avw=1748&ntlv=10&auto=1&ver=QZO1fiuYm1w.zh_CN.&am=!vnTMmHVpype3JseDLxvLA_yz78B_as2fBAM27gc3CwMLp18SQJa-pLxsPXVzpBvNHFY-qwN9&vas=1&ari=300&_reqid=1345636&usus=1&pcd=1&mb=0&rt=j&search=inbox 
Apr 22 12:52:48 - [DEBUG] FWD CONNECT ssl.google-analytics.com:443 with closed 
Apr 22 12:52:49 - [DEBUG] FWD CONNECT csi.gstatic.com:443 with closed 
Apr 22 12:52:49 - [DEBUG] FWD CONNECT ssl.gstatic.com:443 with closed 
Apr 22 12:52:55 - [INFO] GAE CONNECT groups.google.com:443 
Apr 22 12:52:55 - [DEBUG] GAE CONNECT POST https://groups.google.com/forum/read?appversion=1&hl=zh-CN&authuser=0 
Apr 22 12:52:55 - [DEBUG] ssl_pool.get:61.19.1.182 handshake:343 
Apr 22 12:52:55 - [DEBUG] ssl conn_num:20 
Apr 22 12:52:55 - [INFO] GAE t:588 s:32 200 https://groups.google.com/forum/read?appversion=1&hl=zh-CN&authuser=0 
Apr 22 12:52:55 - [INFO] FWD CONNECT csi.gstatic.com:443 
Apr 22 12:52:55 - [DEBUG] sort ip time:3 
Apr 22 12:52:55 - [DEBUG] get ip:61.19.1.216 t:258 
Apr 22 12:52:55 - [DEBUG] tcp conn 61.19.1.216 time:131 
Apr 22 12:52:56 - [WARNING] gae_handler err:error(10053, '') https://mail.google.com/mail/u/0/channel/bind?OSID=B89EEB605D1C713A&OAID=45&VER=8&at=AF6bupMdnYgKimFPR5JmjmsaLgvkZt9rUA&it=720900&RID=rpc&SID=491DDB322ADB0B42&CI=1&AID=17&TYPE=xmlhttp&zx=71jpal7zzn8n&t=3 
Apr 22 12:52:58 - [INFO] GAE CONNECT play.google.com:443 
Apr 22 12:52:58 - [DEBUG] GAE CONNECT OPTIONS https://play.google.com/log?format=json&u=1 
Apr 22 12:52:58 - [DEBUG] ssl_pool.get:61.19.1.182 handshake:343 
Apr 22 12:52:58 - [DEBUG] ssl conn_num:20 

但是更新到1.92后扩展就一直显示网络错误，log如下 
![Uploading 1.92.jpg . . .]()

Apr 22 12:57:52 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:57:52 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:57:52 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:57:54 - [DEBUG] FWD CONNECT gm1.ggpht.com:443 with closed 
Apr 22 12:57:57 - [DEBUG] FWD CONNECT talkgadget.google.com:443 with closed 
Apr 22 12:58:07 - [DEBUG] FWD CONNECT ssl.gstatic.com:443 with closed 
Apr 22 12:58:13 - [DEBUG] FWD CONNECT drive.google.com:443 with closed 
Apr 22 12:58:13 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:58:13 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:13 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:14 - [INFO]LOG_EXCEPT: GAE CONNECT www.googleapis.com:443 , Except:[Errno 9] Bad file descriptor 
Apr 22 12:58:14 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:14 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:15 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:58:15 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:15 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:16 - [DEBUG] FWD CONNECT clients6.google.com:443 with closed 
Apr 22 12:58:16 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:58:16 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:16 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:17 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:58:17 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:17 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:19 - [DEBUG] FWD CONNECT 6.client-channel.google.com:443 with closed 
Apr 22 12:58:19 - [DEBUG] FWD CONNECT plus.google.com:443 with closed 
Apr 22 12:58:22 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:58:22 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:22 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:52 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:58:52 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:58:52 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:59:14 - [INFO] check_ip add ip:62.1.38.152 time:3550 
Apr 22 12:59:22 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:59:22 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:59:22 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:59:47 - [DEBUG] FWD CONNECT clients4.google.com:443 with closed 
Apr 22 12:59:52 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 12:59:52 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:59:52 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 12:59:58 - [INFO] check_ip add ip:163.28.83.160 time:1488 
Apr 22 13:00:22 - [INFO] GAE CONNECT www.googleapis.com:443 
Apr 22 13:00:22 - [DEBUG] GAE CONNECT OPTIONS https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 
Apr 22 13:00:22 - [WARNING] Method OPTIONS not support in GoAgent for https://www.googleapis.com/gmail/v1/users/me/history?maxResults=100&startHistoryId=68469&labelId=INBOX 

公共appid和私人的都试过了，无改善

**Comment by tianzhisun** [comment]
更新： 我更新下服务器端看看，sorry

**Comment by xxnet** [comment]
1.9.3已修复，请测试
