### ISSUE TITLE
vpn+xxnet的惨痛组合...

### ISSUE THREAD

**Issue by Forty-nine** [XX-net/XX-Net#2088]
一时间忘了开着xxnet，就连接了vpn，2分钟左右搜寻到了100多个ip，当然...回墙之后一点用也没有。还把我原来的ip...
应该不会有像我一样的人吧....算是给大家提个醒

**Comment by jeromeli002** [comment]
什么意思？？？不明白

**Comment by simonasd** [comment]
@jeromeli002 楼主连上VPN之后，XX-Net运行在国外网络环境中，扫描到的IP都是在VPN出口处可以用的。关掉VPN之后就用不了了。

**Comment by jzp820927** [comment]
楼上正解
