### ISSUE TITLE
检查更新导致启动时间过长

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#209]
国内虽然可以访问Github，但是并不稳定，速度时快时慢，甚至无法访问，而打开检查更新后，假如遇到打不开Github的时候，就会一直不出现图标，导致用户以为没打开之类的，然后再开一次，因此我建议：
1.检查更新异步进行
2.增加多开检测，用独占文件其实就可以（同一个目录下只能开一次之类的- -）

**Comment by xxnet** [comment]
检查更新，已经放在后台线程中了，启动确实慢。

在 2015年4月22日 上午3:18，Cat73 <notifications@github.com>写道：

**Comment by ohzxc** [comment]
我也是，启动超级慢。
