### ISSUE TITLE
windows由7升级到10后，无法启动XX-net

### ISSUE THREAD

**Issue by kairi1227** [XX-net/XX-Net#2091]
年前将windows7升级为windows10.升级后发现xxnet无法使用。
以下是xxnet启动日志：

D:\XX-Net-2.8.9>SET PYTHONPATH=

D:\XX-Net-2.8.9>"D:\XX-Net-2.8.9\python27/1.0/python.exe" "D:\XX-Net-2.8.9\launcher/start.py"
Feb 15 15:25:16.949 - [INFO] start XX-Net 2.8.9
Feb 15 15:25:16.950 - [DEBUG] start confirm_xxnet_exit
Feb 15 15:25:16.955 - [DEBUG] good, xxnet:8087 cleared!
Feb 15 15:25:16.957 - [DEBUG] good, xxnet:8085 clear!
Feb 15 15:25:16.957 - [DEBUG] finished confirm_xxnet_exit
Feb 15 15:25:18.208 - [WARNING] network fail:gaierror(10022, 'getaddrinfo failed')
Feb 15 15:25:18.222 - [INFO] SSL use version:TLSv1
Feb 15 15:25:18.612 - [INFO] load ip range file:D:\XX-Net-2.8.9\gae_proxy\local\ip_range.txt
Feb 15 15:25:18.689 - [INFO] detect Win10, enable connect concurent control, interval:40
Feb 15 15:25:18.761 - [INFO] load google ip_list num:3000, gws num:3000
Feb 15 15:25:18.952 - [DEBUG] ## GAEProxy set keep_running: True
Feb 15 15:25:18.954 - [INFO] ------------------------------------------------------
Feb 15 15:25:18.954 - [INFO] Python Version     : 2.7.9
Feb 15 15:25:18.955 - [INFO] OS                 : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Feb 15 15:25:18.956 - [INFO] Listen Address     : 127.0.0.1:8087
Feb 15 15:25:18.957 - [INFO] GAE APPID          : xxxx-proxy
Feb 15 15:25:18.959 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Feb 15 15:25:18.961 - [INFO] ------------------------------------------------------
Feb 15 15:25:18.990 - [INFO] server 127.0.0.1:8087 started.
Feb 15 15:25:18.993 - [INFO] server 127.0.0.1:8086 started.
Feb 15 15:25:19.050 - [INFO] module gae_proxy started
Feb 15 15:25:19.052 - [INFO] start gae_proxy time cost 2085
Feb 15 15:25:19.053 - [INFO] begin to start web control
Feb 15 15:25:19.055 - [INFO] server 127.0.0.1:8085 started.
Feb 15 15:25:19.057 - [INFO] launcher web control started.
Feb 15 15:25:20.111 - [INFO] get uuid:9335c686-6932-4e18-9669-935dfee0bcc0
Feb 15 15:25:20.115 - [WARNING] check_update fail:URLError(gaierror(10022, 'getaddrinfo failed'),)
Feb 15 15:25:20.117 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-2.8.9\data\downloads\README.md, retry:0
Feb 15 15:25:20.157 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-2.8.9\data\downloads\README.md URL fail:URLError(gaierror(10022, 'getaddrinfo failed'),)
Feb 15 15:25:20.160 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-2.8.9\data\downloads\README.md, retry:1
Feb 15 15:25:20.162 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-2.8.9\data\downloads\README.md URL fail:URLError(gaierror(10022, 'getaddrinfo failed'),)
Feb 15 15:25:20.164 - [WARNING] check update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Feb 15 15:25:49.428 - [WARNING] socket accept fail(errno: 10022).
Feb 15 15:25:49.435 - [INFO] restart socket server.
Feb 15 15:25:49.437 - [INFO] server 127.0.0.1:8087 started.
Feb 15 15:25:49.510 - [WARNING] socket accept fail(errno: 10022).
Feb 15 15:25:49.516 - [INFO] restart socket server.
Feb 15 15:25:49.519 - [INFO] server 127.0.0.1:8085 started.
Feb 15 15:27:53.467 - [INFO] scan_ip add ip:103.11.28.183 time:1448
Feb 15 15:27:53.474 - [INFO] remove_slowest_ip:193.90.147.21 handshake_time:2148, fails:0

求助各位大神们，如何解决呀？

**Comment by Cat7373** [comment]
似乎没看到什么问题，试试看能不能打开状态页？
127.0.0.1:8085

**Comment by simear2004** [comment]
我也是win10使用正常，你以管理员身份运行试试

**Comment by kairi1227** [comment]
状态面打不开。管理员身份运行也试过了。
异常信息：Feb 15 15:25:18.208 - [WARNING] network fail:gaierror(10022, 'getaddrinfo failed')

**Comment by linhua55** [comment]
DNS的问题

kairi1227 <notifications@github.com>于2016年2月23日周二 上午10:37写道：

**Comment by kairi1227** [comment]
问题解决了，请参考#2315
