### ISSUE TITLE
以前goagent的服务器不能用，重新部署总是失败

### ISSUE THREAD

**Issue by ifq** [XX-net/XX-Net#2092]
在这里搜了下，
1、都说要可以再浏览器访问appengine之后，就可以部署了。这个我已经确保可以了，
2、而且appid都是以前goagent3.1版本时候一直用到现在的。

我使用
appengine.google.com = gae
appengine.google.com = direct 

但是部署还是一直出错：
Feb 15 22:46:06 - ============ Begin upload ============ 
appid:xxxxxx1

Feb 15 22:46:06 - Application: xxxxxx1
Feb 15 22:46:06 - Host: appengine.google.com
Feb 15 22:46:06 - Rolling back the update.
Feb 15 22:46:37 - Error 504: --- begin server output ---

请问是什么原因？

**Comment by wenliyang** [comment]
appengine.google.com = gae
appengine.google.com = direct 

不知道你是在什么文件里修改的，删除掉这两行恢复原有内容再试

**Comment by ifq** [comment]
D:\XX-Net-master\gae_proxy\local里的proxy.ini 文件，
我是先用原版的不行，才开始折腾这个选项的。

**Comment by ifq** [comment]
另外，我通过修改 hosts 文件，目前不用代理也可以访问https://appengine.google.com/的。
不过，{appid}.appspot.com 是访问不了的。 请问是要appengine.google.com可以访问就好了吗。

**Comment by wenliyang** [comment]
删除 hosts 文件里的 appengine.google.com 相关条目试下
先用 XX-Net 自带的 APPID，可以正常访问 appengine.google.com 的情况下部署自己的 APPID，hosts 里的相关条目按我以前的经验可能会造成你所说的问题

**Comment by ifq** [comment]
果然是hosts搞的鬼。。 去掉就好了。。
谢谢了。
