### ISSUE TITLE
问个小白的问题，XX-net的是一个人开发？

### ISSUE THREAD

**Issue by AgoniNemo** [XX-net/XX-Net#2096]
XX-net的是一个人开发？还是一个团队？叫什么

**Comment by zjhzxhz** [comment]
Please look at this page:
https://github.com/XX-net/XX-Net/graphs/contributors

**Comment by simonasd** [comment]
github上的项目大多数都是多人合作的产物，开发者们经常也是志愿工作的。二楼给出的链接就是本项目所有贡献过代码的账户。
