### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by q1728576493** [XX-net/XX-Net#210]
Apr 22 18:17:18 - ============  Begin upload  ============
appid:liuqy1728576493 

Apr 22 18:17:18 - Application: liuqy1728576493
Apr 22 18:17:18 - Host: appengine.google.com
Apr 22 18:17:18 - Rolling back the update.
Apr 22 18:17:21 - Error 404: --- begin server output ---

    <html><head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>404 No usable Appid Exists</title>
    <style></style>
    </head>
    <body text=#000000 bgcolor=#ffffff>
    <table border=0 cellpadding=2 cellspacing=0 width=100%>
    <tr><td bgcolor=#3366cc><font face=arial,sans-serif color=#ffffff><b>Message</b></td></tr>
    <tr><td> </td></tr></table>
    <blockquote>
    <H1>没有可用appid了，请配置可用的appid</H1>
    
    <p>
    </blockquote>
    <table width=100% cellpadding=0 cellspacing=0><tr><td bgcolor=#3366cc><img alt="" width=1 height=4></td></tr></table>
    </body></html>
    
--- end server output ---
Apr 22 18:17:21 - upload  fail: HTTP Error 404: 

Apr 22 18:17:21 - Retry again.

Apr 22 18:17:22 - Application: liuqy1728576493
Apr 22 18:17:22 - Host: appengine.google.com
Apr 22 18:17:22 - Rolling back the update.

**Comment by xxnet** [comment]
你设置的appid是不是还没有部署过？

如果没有部署过，请先从配置中取消，使用公共appid部署。

2015-04-22 6:18 GMT-04:00 q1728576493 <notifications@github.com>:

**Comment by q1728576493** [comment]
如何部署appid

**Comment by xxnet** [comment]
先从GoAgent的配置中删除你填入的appid
然后到部署页面部署

2015-04-22 7:33 GMT-04:00 q1728576493 <notifications@github.com>:

**Comment by q1728576493** [comment]
Apr 22 19:44:59 - ============  Begin upload  ============
appid:q1728576493 

Apr 22 19:44:59 - Application: q1728576493
Apr 22 19:44:59 - Host: appengine.google.com
Apr 22 19:44:59 - Rolling back the update.
Apr 22 19:45:00 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:00 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:00 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:01 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:01 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:01 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:02 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:02 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:02 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:02 - Error 401: --- begin server output ---
Must authenticate first.
--- end server output ---
Apr 22 19:45:02 - upload  fail: HTTP Error 401: Unauthorized

Apr 22 19:45:02 - Retry again.

Apr 22 19:45:03 - Application: q1728576493
Apr 22 19:45:03 - Host: appengine.google.com
Apr 22 19:45:03 - Rolling back the update.
Apr 22 19:45:04 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:04 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:04 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:05 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:05 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:05 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:06 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:06 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:06 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:06 - Error 401: --- begin server output ---
Must authenticate first.
--- end server output ---
Apr 22 19:45:06 - upload  fail: HTTP Error 401: Unauthorized

Apr 22 19:45:06 - Retry again.

Apr 22 19:45:07 - Application: q1728576493
Apr 22 19:45:07 - Host: appengine.google.com
Apr 22 19:45:07 - Rolling back the update.
Apr 22 19:45:09 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:09 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:09 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:09 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:09 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:09 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:11 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:11 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:11 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:11 - Error 401: --- begin server output ---
Must authenticate first.
--- end server output ---
Apr 22 19:45:11 - upload  fail: HTTP Error 401: Unauthorized

Apr 22 19:45:11 - Retry again.

Apr 22 19:45:12 - Application: q1728576493
Apr 22 19:45:12 - Host: appengine.google.com
Apr 22 19:45:12 - Rolling back the update.
Apr 22 19:45:13 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:13 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:13 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:14 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:14 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:14 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:15 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

Apr 22 19:45:15 - Use an application-specific password instead of your regular account password.
Apr 22 19:45:15 - See http://www.google.com/support/accounts/bin/answer.py?answer=185833
Apr 22 19:45:15 - Error 401: --- begin server output ---
Must authenticate first.
--- end server output ---
Apr 22 19:45:15 - upload  fail: HTTP Error 401: Unauthorized

Apr 22 19:45:15 - Retry again.

Apr 22 19:45:16 - Application: q1728576493
Apr 22 19:45:16 - Host: appengine.google.com
Apr 22 19:45:16 - Rolling back the update.
Apr 22 19:45:17 - WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
Info=InvalidSecondFactor

**Comment by q1728576493** [comment]
这个问题怎么解决？

**Comment by xxnet** [comment]
你的密码错了。

估计你是使用了2步登录，那么你需要申请应用专用密码
参考这里：
https://github.com/XX-net/XX-Net/wiki/Deploy-password-problem

2015-04-22 7:47 GMT-04:00 q1728576493 <notifications@github.com>:

**Comment by q1728576493** [comment]
是密码错了，开始用邮箱密码了。没有说清楚。
