### ISSUE TITLE
连接池问题，测试版...大概是bug

### ISSUE THREAD

**Issue by Forty-nine** [XX-net/XX-Net#2100]
....主要就是有ip，延迟很低，连接池变成0了，一直都是，重启无效。
同一配置；ip，在2.8.9正常。

**Comment by Cat7373** [comment]
我也有这种问题，用一段时间后连接池成 0，无法通过代理访问网页，但重启可以恢复。

**Comment by xxnet** [comment]
​@Forty-nine
  你试试 trunk 上的版本，下载这个链接：https://github.com/XX-net/XX-Net/archive/master.zip
  还不行把日志贴出来

@Cat
  你是trunk的版本还是2.8.10?
  进入连接池为0的日志贴来看看

**Comment by Cat7373** [comment]
最近比较懒- -
遇到问题就直接重启了- -
下次遇到的时候留日志吧- -

**Comment by Forty-nine** [comment]
@xxnet  这个版本，“.com”无法跳转到“.com.hk”，连接池在10以下，网页经常打不开。

-我是小白，看不出什么-

**Comment by xxnet** [comment]
@Forty-nine
  把日志贴出来看看
​

**Comment by Forty-nine** [comment]
Feb 18 10:33:42.515 - [INFO] SSL use version:TLSv1

Feb 18 10:33:43.125 - [INFO] load ip range file:D:\Program Files\ShadowsocksR\XX-Net-master\gae_proxy\local\ip_range.txt

Feb 18 10:33:43.250 - [INFO] load google ip_list num:3000, gws num:3000

Feb 18 10:33:43.281 - [DEBUG] sort ip time:30ms

Feb 18 10:33:43.390 - [DEBUG] ## GAEProxy set keep_running: True

Feb 18 10:33:43.390 - [INFO] ------------------------------------------------------

Feb 18 10:33:43.390 - [INFO] Python Version : 2.7.11

Feb 18 10:33:43.390 - [INFO] OS : Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0

Feb 18 10:33:43.390 - [INFO] Listen Address : 127.0.0.1:8087

Feb 18 10:33:43.390 - [INFO] GAE APPID : sishijiu-49|sishijiu-50|sishijiu-51|sishijiu-52

Feb 18 10:33:43.390 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac

Feb 18 10:33:43.390 - [INFO] ------------------------------------------------------

Feb 18 10:33:43.781 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.015 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.046 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.046 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.671 - [DEBUG] get ip:202.248.151.50 t:202

Feb 18 10:33:44.781 - [DEBUG] get ip:218.253.0.237 t:219

Feb 18 10:33:44.828 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet

Feb 18 10:33:44.828 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet

Feb 18 10:33:44.843 - [INFO] GAE CONNECT xxnet-update.appspot.com:443

Feb 18 10:33:44.859 - [DEBUG] GET http://www.twitter.com/xxnet

Feb 18 10:33:44.859 - [DEBUG] GET http://www.twitter.com/xxnet

Feb 18 10:33:44.859 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=7b6d62bf-41ba-4fba-a02d-9f2ba2831292&version=2.8.10&platform=Windows-XP-5.1.2600-SP3

Feb 18 10:33:44.859 - [DEBUG] get ip:218.253.0.220 t:219

Feb 18 10:33:44.875 - [DEBUG] get ip:202.248.248.246 t:219

Feb 18 10:33:44.984 - [DEBUG] get ip:218.253.0.250 t:219

Feb 18 10:33:45.078 - [DEBUG] get ip:216.58.200.113 t:219

Feb 18 10:33:45.187 - [DEBUG] get ip:218.253.0.219 t:233

Feb 18 10:33:45.203 - [DEBUG] create_ssl update ip:202.248.151.50 time:344

Feb 18 10:33:45.281 - [DEBUG] get ip:202.248.248.212 t:233

Feb 18 10:33:45.328 - [DEBUG] create_ssl update ip:202.248.248.246 time:297

Feb 18 10:33:45.375 - [DEBUG] get ip:219.124.146.172 t:233

Feb 18 10:33:45.484 - [DEBUG] get ip:219.124.146.160 t:233

Feb 18 10:33:45.515 - [DEBUG] create_ssl update ip:216.58.200.113 time:297

Feb 18 10:33:45.546 - [INFO] DIRECT t:687 s:1674 200 xxnet-update.appspot.com /update.json?uuid=7b6d62bf-41ba-4fba-a02d-9f2ba2831292&version=2.8.10&platform=Windows-XP-5.1.2600-SP3

Feb 18 10:33:45.593 - [DEBUG] create_ssl update ip:202.248.248.212 time:217

Feb 18 10:33:45.593 - [DEBUG] get ip:218.253.0.241 t:233

Feb 18 10:33:45.640 - [DEBUG] create_ssl update ip:218.253.0.237 time:687

Feb 18 10:33:45.687 - [DEBUG] get ip:218.253.0.249 t:233

Feb 18 10:33:45 - [DEBUG]LOG_EXCEPT: GET http://www.twitter.com/xxnet, Except:[Errno 9] Bad file descriptor

Feb 18 10:33:45.828 - [DEBUG] GET http://www.twitter.com/xxnet

Feb 18 10:33:45.890 - [DEBUG] create_ssl update ip:218.253.0.219 time:484

Feb 18 10:33:46.125 - [DEBUG] create_ssl update ip:218.253.0.249 time:296

Feb 18 10:33:46.203 - [DEBUG] create_ssl update ip:218.253.0.241 time:422

Feb 18 10:33:48.406 - [DEBUG] create_ssl update ip:218.253.0.220 time:359

Feb 18 10:33:48.500 - [DEBUG] create_ssl update ip:218.253.0.250 time:3312

Feb 18 10:33:49.484 - [DEBUG] 219.124.146.160 fail:timeout('timed out',)

Feb 18 10:33:49.484 - [DEBUG] report_connect_fail:219.124.146.160

Feb 18 10:33:56.640 - [DEBUG] create_ssl update ip:219.124.146.172 time:8000

Feb 18 10:33:56.640 - [DEBUG] 219.124.146.172 fail:error(' certficate is none',)

Feb 18 10:33:56.640 - [DEBUG] report_connect_fail:219.124.146.172

Feb 18 10:33:56.718 - [DEBUG] network is ok, cost:77 ms

Feb 18 10:34:03.187 - [DEBUG] restore ip:219.124.146.160

Feb 18 10:34:04.984 - [INFO] GAE CONNECT www.google.com:443

Feb 18 10:34:05.015 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/

Feb 18 10:34:05.187 - [INFO] DIRECT t:171 s:390 302 www.google.com /

Feb 18 10:34:07.625 - [DEBUG] restore ip:219.124.146.172

Feb 18 10:34:36.578 - [INFO] scan_ip add ip:216.58.203.74 time:469

Feb 18 10:34:36.593 - [INFO] remove_slowest_ip:208.65.154.195 handshake_time:639, fails:9

Feb 18 10:34:39.250 - [DEBUG] get ip:202.248.151.24 t:233

Feb 18 10:34:39.359 - [DEBUG] get ip:202.248.151.40 t:233

Feb 18 10:34:39.468 - [DEBUG] get ip:218.253.0.224 t:233

Feb 18 10:34:39.562 - [DEBUG] create_ssl update ip:202.248.151.24 time:203

Feb 18 10:34:39.578 - [DEBUG] get ip:218.253.0.218 t:234

Feb 18 10:34:39.671 - [DEBUG] get ip:218.253.0.204 t:234

Feb 18 10:34:39.781 - [DEBUG] get ip:218.253.0.247 t:234

Feb 18 10:34:39.828 - [DEBUG] create_ssl update ip:202.248.151.40 time:312

Feb 18 10:34:39.890 - [DEBUG] get ip:218.253.0.212 t:250

Feb 18 10:34:39.984 - [DEBUG] get ip:202.248.248.239 t:250

Feb 18 10:34:40.015 - [DEBUG] create_ssl update ip:218.253.0.204 time:234

Feb 18 10:34:40.140 - [DEBUG] create_ssl update ip:218.253.0.224 time:500

Feb 18 10:34:40.171 - [DEBUG] create_ssl update ip:218.253.0.247 time:265

Feb 18 10:34:40.218 - [DEBUG] create_ssl update ip:218.253.0.212 time:217

Feb 18 10:34:40.296 - [DEBUG] create_ssl update ip:202.248.248.239 time:203

Feb 18 10:34:40.390 - [DEBUG] create_ssl update ip:218.253.0.218 time:531

Feb 18 10:34:49.718 - [INFO] GAE CONNECT www.google.com:443

Feb 18 10:34:49.734 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/complete/search?client=firefox&q=ht

Feb 18 10:34:49.734 - [DEBUG] host_conn_pool www.google.com get:202.248.248.212 handshake:217

Feb 18 10:34:49.890 - [INFO] GAE CONNECT www.google.com:443

Feb 18 10:34:49.906 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/complete/search?client=firefox&q=htt

Feb 18 10:34:49.921 - [WARNING] direct_handler.handler send response fail. t:0 e:error(10053, '') www.google.com/complete/search?client=firefox&q=ht

Feb 18 10:34:49.921 - [INFO] DIRECT chucked t:187 s:0 200 www.google.com /complete/search?client=firefox&q=ht

Feb 18 10:34:50.062 - [INFO] DIRECT chucked t:156 s:91 200 www.google.com /complete/search?client=firefox&q=htt

Feb 18 10:34:51.296 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:51.328 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/

Feb 18 10:34:51.843 - [INFO] GAE CONNECT lh3.googleusercontent.com:443

Feb 18 10:34:51.843 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:51.875 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/images/nav_logo242_hr.png

Feb 18 10:34:51.890 - [DEBUG] GAE CONNECT GET https://lh3.googleusercontent.com/-6b1hVDM0BzQ/AAAAAAAAAAI/AAAAAAAAAAA/AMW9IgeDHt0hYVDUtY7yqxQ9NWte6hlEPw/s32-c-mo/photo.jpg

Feb 18 10:34:51.968 - [DEBUG] ssl_pool.get:218.253.0.249 handshake:296

Feb 18 10:34:51.968 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:51.968 - [INFO] DIRECT chucked t:639 s:54239 200 www.google.com.hk /

Feb 18 10:34:52 - [DEBUG]LOG_EXCEPT: GAE CONNECT Direct GET https://www.google.com.hk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png, Except:[Errno 9] Bad file descriptor

Feb 18 10:34:52.000 - [DEBUG] host_conn_pool www.google.com.hk get:202.248.248.239 handshake:203

Feb 18 10:34:52.078 - [INFO] DIRECT t:203 304 www.google.com.hk /images/nav_logo242_hr.png

Feb 18 10:34:52.109 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:52.140 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=MXoHSi2G9j8W9Ujsuk0-pA&cp=0&gs_id=0&q=&xhr=t

Feb 18 10:34:52.140 - [DEBUG] host_conn_pool www.google.com.hk get:218.253.0.212 handshake:217

Feb 18 10:34:52.156 - [INFO] DIRECT t:155 304 www.google.com.hk /images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

Feb 18 10:34:52.375 - [INFO] DIRECT chucked t:234 s:81 200 www.google.com.hk /complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=MXoHSi2G9j8W9Ujsuk0-pA&cp=0&gs_id=0&q=&xhr=t

Feb 18 10:34:52.375 - [INFO] GAE 1952|218.253.0.249|242 t:484 s:0 hs:296 304 https://lh3.googleusercontent.com/-6b1hVDM0BzQ/AAAAAAAAAAI/AAAAAAAAAAA/AMW9IgeDHt0hYVDUtY7yqxQ9NWte6hlEPw/s32-c-mo/photo.jpg

Feb 18 10:34:52.500 - [INFO] GAE CONNECT plus.google.com:443

Feb 18 10:34:52.515 - [DEBUG] GAE CONNECT POST https://plus.google.com/u/0/_/n/gcosuc

Feb 18 10:34:52.515 - [DEBUG] ssl_pool.get:218.253.0.249 handshake:296

Feb 18 10:34:52.609 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:52.625 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:52.656 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/images/nav_logo242.png

Feb 18 10:34:52.656 - [DEBUG] host_conn_pool www.google.com.hk get:202.248.248.239 handshake:203

Feb 18 10:34:52.656 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/gen_204?v=3&s=webhp&atyp=csi&ei=lC3FVu6LHoWc0gSx2pugCQ&imc=2&imn=2&imp=2&e=18167,1350414,3700319,4003510,4028875,4029815,4031109,4032677,4033307,4036509,4036527,4038012,4038214,4039268,4041776,4042784,4042788,4043041,4043492,4044542,4044606,4045096,4045293,4045841,4046043,4046304,4046397,4046835,4046837,4046904,4047593,4047780,4048909,4048980,4049063,4049501,4049549,4049553,4050281,4050886,4050912,4051241,4051267,4051596,4051886,4052304,4052751,4052954,4054284,4054552,4055381,4055948,4055952,4056038,4056126,4056163,4056589,4056682,4057170,4057586,4057836,4058004,4058117,4058277,4058315,4058332,4058337,4058343,4058512,4058624,4058636,4058908,4058913,4058931,4059318,4059327,4059438,4059504,4059510,4059789,4059825,4059978,4060008,4060835,8300096,8300273,8300310,8502315,8502451,8502691,8502986,8503011,8503039,8503210,8503303,8503306,8503404,8503585,10200083,10201630,10201648&adh=&xjs=init.40.18.sb.30.m.3.foot.2.bbd.1.cr.1&ima=0&rt=xjsls.99,xjses.256,xjsee.343,xjs.343,prt.356,iml.518,dcl.445,jraids.445,jraide.456,ol.895,aft.356,wsrt.432,cst.0,dnst.0,rqst.647,rspt.675,rqstt.68,unt.2,cstt.2,dit.818

Feb 18 10:34:52.656 - [DEBUG] host_conn_pool www.google.com.hk get:218.253.0.212 handshake:217

Feb 18 10:34:52.843 - [INFO] DIRECT t:187 304 www.google.com.hk /images/nav_logo242.png

Feb 18 10:34:53.125 - [INFO] GAE 1952|218.253.0.249|726 t:609 s:55 hs:296 200 https://plus.google.com/u/0/_/n/gcosuc Feb 18 10:33:42.515 - [INFO] SSL use version:TLSv1

Feb 18 10:33:43.125 - [INFO] load ip range file:D:\Program Files\ShadowsocksR\XX-Net-master\gae_proxy\local\ip_range.txt

Feb 18 10:33:43.250 - [INFO] load google ip_list num:3000, gws num:3000

Feb 18 10:33:43.281 - [DEBUG] sort ip time:30ms

Feb 18 10:33:43.390 - [DEBUG] ## GAEProxy set keep_running: True

Feb 18 10:33:43.390 - [INFO] ------------------------------------------------------

Feb 18 10:33:43.390 - [INFO] Python Version : 2.7.11

Feb 18 10:33:43.390 - [INFO] OS : Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0

Feb 18 10:33:43.390 - [INFO] Listen Address : 127.0.0.1:8087

Feb 18 10:33:43.390 - [INFO] GAE APPID : sishijiu-49|sishijiu-50|sishijiu-51|sishijiu-52

Feb 18 10:33:43.390 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac

Feb 18 10:33:43.390 - [INFO] ------------------------------------------------------

Feb 18 10:33:43.781 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.015 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.046 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.046 - [INFO] GAE CONNECT www.twitter.com:443

Feb 18 10:33:44.671 - [DEBUG] get ip:202.248.151.50 t:202

Feb 18 10:33:44.781 - [DEBUG] get ip:218.253.0.237 t:219

Feb 18 10:33:44.828 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet

Feb 18 10:33:44.828 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet

Feb 18 10:33:44.843 - [INFO] GAE CONNECT xxnet-update.appspot.com:443

Feb 18 10:33:44.859 - [DEBUG] GET http://www.twitter.com/xxnet

Feb 18 10:33:44.859 - [DEBUG] GET http://www.twitter.com/xxnet

Feb 18 10:33:44.859 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=7b6d62bf-41ba-4fba-a02d-9f2ba2831292&version=2.8.10&platform=Windows-XP-5.1.2600-SP3

Feb 18 10:33:44.859 - [DEBUG] get ip:218.253.0.220 t:219

Feb 18 10:33:44.875 - [DEBUG] get ip:202.248.248.246 t:219

Feb 18 10:33:44.984 - [DEBUG] get ip:218.253.0.250 t:219

Feb 18 10:33:45.078 - [DEBUG] get ip:216.58.200.113 t:219

Feb 18 10:33:45.187 - [DEBUG] get ip:218.253.0.219 t:233

Feb 18 10:33:45.203 - [DEBUG] create_ssl update ip:202.248.151.50 time:344

Feb 18 10:33:45.281 - [DEBUG] get ip:202.248.248.212 t:233

Feb 18 10:33:45.328 - [DEBUG] create_ssl update ip:202.248.248.246 time:297

Feb 18 10:33:45.375 - [DEBUG] get ip:219.124.146.172 t:233

Feb 18 10:33:45.484 - [DEBUG] get ip:219.124.146.160 t:233

Feb 18 10:33:45.515 - [DEBUG] create_ssl update ip:216.58.200.113 time:297

Feb 18 10:33:45.546 - [INFO] DIRECT t:687 s:1674 200 xxnet-update.appspot.com /update.json?uuid=7b6d62bf-41ba-4fba-a02d-9f2ba2831292&version=2.8.10&platform=Windows-XP-5.1.2600-SP3

Feb 18 10:33:45.593 - [DEBUG] create_ssl update ip:202.248.248.212 time:217

Feb 18 10:33:45.593 - [DEBUG] get ip:218.253.0.241 t:233

Feb 18 10:33:45.640 - [DEBUG] create_ssl update ip:218.253.0.237 time:687

Feb 18 10:33:45.687 - [DEBUG] get ip:218.253.0.249 t:233

Feb 18 10:33:45 - [DEBUG]LOG_EXCEPT: GET http://www.twitter.com/xxnet, Except:[Errno 9] Bad file descriptor

Feb 18 10:33:45.828 - [DEBUG] GET http://www.twitter.com/xxnet

Feb 18 10:33:45.890 - [DEBUG] create_ssl update ip:218.253.0.219 time:484

Feb 18 10:33:46.125 - [DEBUG] create_ssl update ip:218.253.0.249 time:296

Feb 18 10:33:46.203 - [DEBUG] create_ssl update ip:218.253.0.241 time:422

Feb 18 10:33:48.406 - [DEBUG] create_ssl update ip:218.253.0.220 time:359

Feb 18 10:33:48.500 - [DEBUG] create_ssl update ip:218.253.0.250 time:3312

Feb 18 10:33:49.484 - [DEBUG] 219.124.146.160 fail:timeout('timed out',)

Feb 18 10:33:49.484 - [DEBUG] report_connect_fail:219.124.146.160

Feb 18 10:33:56.640 - [DEBUG] create_ssl update ip:219.124.146.172 time:8000

Feb 18 10:33:56.640 - [DEBUG] 219.124.146.172 fail:error(' certficate is none',)

Feb 18 10:33:56.640 - [DEBUG] report_connect_fail:219.124.146.172

Feb 18 10:33:56.718 - [DEBUG] network is ok, cost:77 ms

Feb 18 10:34:03.187 - [DEBUG] restore ip:219.124.146.160

Feb 18 10:34:04.984 - [INFO] GAE CONNECT www.google.com:443

Feb 18 10:34:05.015 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/

Feb 18 10:34:05.187 - [INFO] DIRECT t:171 s:390 302 www.google.com /

Feb 18 10:34:07.625 - [DEBUG] restore ip:219.124.146.172

Feb 18 10:34:36.578 - [INFO] scan_ip add ip:216.58.203.74 time:469

Feb 18 10:34:36.593 - [INFO] remove_slowest_ip:208.65.154.195 handshake_time:639, fails:9

Feb 18 10:34:39.250 - [DEBUG] get ip:202.248.151.24 t:233

Feb 18 10:34:39.359 - [DEBUG] get ip:202.248.151.40 t:233

Feb 18 10:34:39.468 - [DEBUG] get ip:218.253.0.224 t:233

Feb 18 10:34:39.562 - [DEBUG] create_ssl update ip:202.248.151.24 time:203

Feb 18 10:34:39.578 - [DEBUG] get ip:218.253.0.218 t:234

Feb 18 10:34:39.671 - [DEBUG] get ip:218.253.0.204 t:234

Feb 18 10:34:39.781 - [DEBUG] get ip:218.253.0.247 t:234

Feb 18 10:34:39.828 - [DEBUG] create_ssl update ip:202.248.151.40 time:312

Feb 18 10:34:39.890 - [DEBUG] get ip:218.253.0.212 t:250

Feb 18 10:34:39.984 - [DEBUG] get ip:202.248.248.239 t:250

Feb 18 10:34:40.015 - [DEBUG] create_ssl update ip:218.253.0.204 time:234

Feb 18 10:34:40.140 - [DEBUG] create_ssl update ip:218.253.0.224 time:500

Feb 18 10:34:40.171 - [DEBUG] create_ssl update ip:218.253.0.247 time:265

Feb 18 10:34:40.218 - [DEBUG] create_ssl update ip:218.253.0.212 time:217

Feb 18 10:34:40.296 - [DEBUG] create_ssl update ip:202.248.248.239 time:203

Feb 18 10:34:40.390 - [DEBUG] create_ssl update ip:218.253.0.218 time:531

Feb 18 10:34:49.718 - [INFO] GAE CONNECT www.google.com:443

Feb 18 10:34:49.734 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/complete/search?client=firefox&q=ht

Feb 18 10:34:49.734 - [DEBUG] host_conn_pool www.google.com get:202.248.248.212 handshake:217

Feb 18 10:34:49.890 - [INFO] GAE CONNECT www.google.com:443

Feb 18 10:34:49.906 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/complete/search?client=firefox&q=htt

Feb 18 10:34:49.921 - [WARNING] direct_handler.handler send response fail. t:0 e:error(10053, '') www.google.com/complete/search?client=firefox&q=ht

Feb 18 10:34:49.921 - [INFO] DIRECT chucked t:187 s:0 200 www.google.com /complete/search?client=firefox&q=ht

Feb 18 10:34:50.062 - [INFO] DIRECT chucked t:156 s:91 200 www.google.com /complete/search?client=firefox&q=htt

Feb 18 10:34:51.296 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:51.328 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/

Feb 18 10:34:51.843 - [INFO] GAE CONNECT lh3.googleusercontent.com:443

Feb 18 10:34:51.843 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:51.875 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/images/nav_logo242_hr.png

Feb 18 10:34:51.890 - [DEBUG] GAE CONNECT GET https://lh3.googleusercontent.com/-6b1hVDM0BzQ/AAAAAAAAAAI/AAAAAAAAAAA/AMW9IgeDHt0hYVDUtY7yqxQ9NWte6hlEPw/s32-c-mo/photo.jpg

Feb 18 10:34:51.968 - [DEBUG] ssl_pool.get:218.253.0.249 handshake:296

Feb 18 10:34:51.968 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:51.968 - [INFO] DIRECT chucked t:639 s:54239 200 www.google.com.hk /

Feb 18 10:34:52 - [DEBUG]LOG_EXCEPT: GAE CONNECT Direct GET https://www.google.com.hk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png, Except:[Errno 9] Bad file descriptor

Feb 18 10:34:52.000 - [DEBUG] host_conn_pool www.google.com.hk get:202.248.248.239 handshake:203

Feb 18 10:34:52.078 - [INFO] DIRECT t:203 304 www.google.com.hk /images/nav_logo242_hr.png

Feb 18 10:34:52.109 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:52.140 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=MXoHSi2G9j8W9Ujsuk0-pA&cp=0&gs_id=0&q=&xhr=t

Feb 18 10:34:52.140 - [DEBUG] host_conn_pool www.google.com.hk get:218.253.0.212 handshake:217

Feb 18 10:34:52.156 - [INFO] DIRECT t:155 304 www.google.com.hk /images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

Feb 18 10:34:52.375 - [INFO] DIRECT chucked t:234 s:81 200 www.google.com.hk /complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=MXoHSi2G9j8W9Ujsuk0-pA&cp=0&gs_id=0&q=&xhr=t

Feb 18 10:34:52.375 - [INFO] GAE 1952|218.253.0.249|242 t:484 s:0 hs:296 304 https://lh3.googleusercontent.com/-6b1hVDM0BzQ/AAAAAAAAAAI/AAAAAAAAAAA/AMW9IgeDHt0hYVDUtY7yqxQ9NWte6hlEPw/s32-c-mo/photo.jpg

Feb 18 10:34:52.500 - [INFO] GAE CONNECT plus.google.com:443

Feb 18 10:34:52.515 - [DEBUG] GAE CONNECT POST https://plus.google.com/u/0/_/n/gcosuc

Feb 18 10:34:52.515 - [DEBUG] ssl_pool.get:218.253.0.249 handshake:296

Feb 18 10:34:52.609 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:52.625 - [INFO] GAE CONNECT www.google.com.hk:443

Feb 18 10:34:52.656 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/images/nav_logo242.png

Feb 18 10:34:52.656 - [DEBUG] host_conn_pool www.google.com.hk get:202.248.248.239 handshake:203

Feb 18 10:34:52.656 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/gen_204?v=3&s=webhp&atyp=csi&ei=lC3FVu6LHoWc0gSx2pugCQ&imc=2&imn=2&imp=2&e=18167,1350414,3700319,4003510,4028875,4029815,4031109,4032677,4033307,4036509,4036527,4038012,4038214,4039268,4041776,4042784,4042788,4043041,4043492,4044542,4044606,4045096,4045293,4045841,4046043,4046304,4046397,4046835,4046837,4046904,4047593,4047780,4048909,4048980,4049063,4049501,4049549,4049553,4050281,4050886,4050912,4051241,4051267,4051596,4051886,4052304,4052751,4052954,4054284,4054552,4055381,4055948,4055952,4056038,4056126,4056163,4056589,4056682,4057170,4057586,4057836,4058004,4058117,4058277,4058315,4058332,4058337,4058343,4058512,4058624,4058636,4058908,4058913,4058931,4059318,4059327,4059438,4059504,4059510,4059789,4059825,4059978,4060008,4060835,8300096,8300273,8300310,8502315,8502451,8502691,8502986,8503011,8503039,8503210,8503303,8503306,8503404,8503585,10200083,10201630,10201648&adh=&xjs=init.40.18.sb.30.m.3.foot.2.bbd.1.cr.1&ima=0&rt=xjsls.99,xjses.256,xjsee.343,xjs.343,prt.356,iml.518,dcl.445,jraids.445,jraide.456,ol.895,aft.356,wsrt.432,cst.0,dnst.0,rqst.647,rspt.675,rqstt.68,unt.2,cstt.2,dit.818

Feb 18 10:34:52.656 - [DEBUG] host_conn_pool www.google.com.hk get:218.253.0.212 handshake:217

Feb 18 10:34:52.843 - [INFO] DIRECT t:187 304 www.google.com.hk /images/nav_logo242.png

Feb 18 10:34:53.125 - [INFO] GAE 1952|218.253.0.249|726 t:609 s:55 hs:296 200 https://plus.google.com/u/0/_/n/gcosuc

**Comment by zjhzxhz** [comment]
@Forty-nine Google不会跳转的话, 因为你访问的是 http 的链接.
如果你访问 https://www.google.com 这样就会跳转了?

**Comment by Cat7373** [comment]
我的也不跳转到 hk 呀，问题在于为什么要跳转到 hk 呢？

**Comment by xxnet** [comment]
​@Forty-nine

这个是正常的日志吧，连接池为0的日志有没有？

**Comment by Forty-nine** [comment]
不是..我的意思是网页白屏，左下角一直在连接.hk。
手动输入.hk后可以打开网页

**Comment by 117649** [comment]
一样的问题访问 https://www.google.com 的话白屏 显示等待www.google.com.hk
直接访问 https://www.google.com.hk/ 没有问题
