### ISSUE TITLE
默默地冒个泡，然后大家新年好！另外需要试用x-tunnel的，留下注册号。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2104]
:heart_eyes:

**Comment by simonasd** [comment]
这个是怎么的？

**Comment by yeahwu** [comment]
@simonasd 你就当高潮后的抽搐……（赶脚俺说话越来越有内涵鸟）

**Comment by xxnet** [comment]
​刚发了2.9.0 版本，带上了x_tunnel

*@zjhzxhz <https://github.com/zjhzxhz> 的UI* 太棒了，今天又修复了新UI的一些bug，大家测测

**Comment by yeahwu** [comment]
干嘛用“注销”而不用“退出”或者“登出”
搞了“注销”两个字，俺都犹豫了好久，该不该点，怕点了以后，账户就没鸟！

**Comment by xxnet** [comment]
​恩，我也有同感，提个pull吧

**Comment by yeahwu** [comment]
这个版本很难登录，且不能记住登录。用不了，日志
Feb 19 18:36:52.345 - [ERROR] request except:KeyError(132,) retry 6

Feb 19 18:36:52.345 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net-2.9.0\x_tunnel\local\proxy_session.py", line 320, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 132

Feb 19 18:36:52.350 - [ERROR] request except:KeyError(133,) retry 6

Feb 19 18:36:52.350 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net-2.9.0\x_tunnel\local\proxy_session.py", line 320, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 133

Feb 19 18:36:52.465 - [ERROR] request except:KeyError(135,) retry 6

Feb 19 18:36:52.465 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net-2.9.0\x_tunnel\local\proxy_session.py", line 320, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 135

Feb 19 18:36:53.966 - [DEBUG] roundtrip time:17818 cost:2368 transfer_no:342 send_sn:342 send:25 recv_sn:90 rcv:633 status:200

Feb 19 18:36:53.967 - [WARNING] DATA conn_id 35 not in list

Feb 19 18:36:54.498 - [ERROR] request except:KeyError(23,) retry 8

Feb 19 18:36:54.498 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net-2.9.0\x_tunnel\local\proxy_session.py", line 320, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 23

Feb 19 18:36:56.173 - [ERROR] request except:KeyError(76,) retry 6

Feb 19 18:36:56.173 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net-2.9.0\x_tunnel\local\proxy_session.py", line 320, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 76

**Comment by yeahwu** [comment]
@xxnet 这会有能用鸟，可能是我网络的原因。再试试

**Comment by yeahwu** [comment]
已提pull，
试用后，其它的没什么问题。就是流量问题，有点混乱。

**Comment by xxnet** [comment]
​流量问题，什么问题？

**Comment by zjhzxhz** [comment]
@xxnet 应该是我之前把单位换算改成1024了. 但是我看你又改回1000了.

**Comment by yeahwu** [comment]
流量10g变为20g，就是你转100g给我，变成200g

**Comment by yeahwu** [comment]
场景是这样的，我转了某人10g流量，几分钟以后变成20g了

**Comment by xxnet** [comment]
​A 转 10G 给B，之后会怎样？

**Comment by yeahwu** [comment]
之后b就会有两个10g

**Comment by xxnet** [comment]
​服务端更新了，再试试

**Comment by yeahwu** [comment]
更新后没有数据返回，日志
```
Feb 19 23:07:01.168 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net-2.9.0\x_tunnel\local\proxy_session.py", line 153, in login_session g.last_api_error = "session server login fail:%d" % status TypeError: %d format: a number is required, not str

Feb 19 23:07:01.168 - [WARNING] x-tunnel session not start

Feb 19 23:07:08.184 - [WARNING] session not running, can't connect

Feb 19 23:07:08.184 - [WARNING] create conn fail

Feb 19 23:07:08.186 - [WARNING] session not running, can't connect

Feb 19 23:07:08.187 - [WARNING] create conn fail

Feb 19 23:07:21.299 - [WARNING] session not running, can't connect

Feb 19 23:07:21.299 - [WARNING] create conn fail

Feb 19 23:07:21.302 - [WARNING] session not running, can't connect

Feb 19 23:07:21.302 - [WARNING] create conn fail

Feb 19 23:08:12.969 - [WARNING] session not running, can't connect

Feb 19 23:08:12.969 - [WARNING] create conn fail

Feb 19 23:08:12.972 - [WARNING] session not running, can't connect

Feb 19 23:08:12.972 - [WARNING] create conn fail

Feb 19 23:08:15.406 - [WARNING] session not running, can't connect

Feb 19 23:08:15.406 - [WARNING] create conn fail

Feb 19 23:08:15.410 - [WARNING] session not running, can't connect

Feb 19 23:08:15.410 - [WARNING] create conn fail

Feb 19 23:08:47.067 - [WARNING] session not running, can't connect

Feb 19 23:08:47.067 - [WARNING] create conn fail

Feb 19 23:08:47.071 - [WARNING] session not running, can't connect

Feb 19 23:08:47.072 - [WARNING] create conn fail

Feb 19 23:09:01.386 - [WARNING] session not running, can't connect

Feb 19 23:09:01.386 - [WARNING] create conn fail

Feb 19 23:09:01.391 - [WARNING] session not running, can't connect

Feb 19 23:09:01.391 - [WARNING] create conn fail

Feb 19 23:09:02.979 - [WARNING] session not running, can't connect

Feb 19 23:09:02.979 - [WARNING] create conn fail

Feb 19 23:09:02.982 - [WARNING] session not running, can't connect

Feb 19 23:09:02.982 - [WARNING] create conn fail

Feb 19 23:09:16.263 - [WARNING] session not running, can't connect

Feb 19 23:09:16.263 - [WARNING] create conn fail

Feb 19 23:09:16.266 - [WARNING] session not running, can't connect

Feb 19 23:09:16.266 - [WARNING] create conn fail

Feb 19 23:09:21.489 - [WARNING] session not running, can't connect

Feb 19 23:09:21.490 - [WARNING] create conn fail

Feb 19 23:09:21.492 - [WARNING] session not running, can't connect

Feb 19 23:09:21.492 - [WARNING] create conn fail
```

**Comment by xxnet** [comment]
​已修复

**Comment by yeahwu** [comment]
刚转了几次流量，没什么问题了，挺好。

**Comment by simonasd** [comment]
@yeahwu 你是有多少流量，天天给别人转着玩？

**Comment by yeahwu** [comment]
@simonasd sm兄要不要来点？给你准备个大礼包

**Comment by simonasd** [comment]
@yeahwu 哈哈，天天搬砖，没时间上网呀！大礼包是个好事，我注册个账号先
