### ISSUE TITLE
无法部署,建议增加手动部署上传方法,如uploadmanaual.bat

### ISSUE THREAD

**Issue by decemer** [XX-net/XX-Net#2105]
无法部署,建议增加手动部署上传方法,如uploadmanaual.bat
日志没任何反应
连接时显示服务没部署,请部署
thx,谢谢

**Comment by xxnet** [comment]
​在 gae_proxy/server/uploader.bat

**Comment by decemer** [comment]
他没有让我输入账号上传服务端,这个是和网页连起来的,但是网页不能用啊

**Comment by xxnet** [comment]
​Usage: uploader.bat <appids> <email> [password] [rc4_password]

**Comment by decemer** [comment]
哦,明天我试试,thx

**Comment by decemer** [comment]
Traceback (most recent call last):
  File "uploader.py", line 34, in <module>
    from google.appengine.tools import appengine_rpc, appcfg
  File "D:\1-General Soft\XX-Net-master\gae_proxy\server\lib\google\appengine\to
ols\appengine_rpc.py", line 26, in <module>
    import cookielib
  File "D:\1-General Soft\XX-Net-master\python27\1.0\python27.zip\cookielib.py",
 line 1809, in <module>
ImportError: No module named _LWPCookieJar

不能用,cant upload

**Comment by xxnet** [comment]
​这是python27 升级带来的问题，请用2.8.9

**Comment by decemer** [comment]
请问旧版的下载地址在哪里呢?
或者我可以本机安装那个包能运行新版的bat吗

**Comment by decemer** [comment]
> 这是python27 升级带来的问题，请用2.8.9
还有下载链接吗?或者其他解决方案
i m stun here

**Comment by jzp820927** [comment]
直接下最新版吧

**Comment by decemer** [comment]
disappointment i used 2.94 still cant upload,and default ip cant work

**Comment by jzp820927** [comment]
实在不行，就用 goagent 上传吧，反正都兼容的。
要不就只有用 VPN 升级了

**Comment by decemer** [comment]
主要是upload.bat不行没用

**Comment by decemer** [comment]
i try this is Okay,and i can go on any website execpt Google.com,and facebook still upload picture,is upload be blocked?
按文档手动上传成功,很多网站都能上除了谷歌,还有facebook图片上传不了,上传是禁用了吗?
```
command line usage:
 python uploader.py <appid> <email> <password> <rc4-password>
```

**Comment by jzp820927** [comment]
facebook图片上传要修改 proxy.ini 中的 hosts 规则，你看看WIKI吧，有说明。视频流不流畅，和IP质量有关，等待多扫描一些时间吧，

**Comment by decemer** [comment]
视频流不流畅,是因为xx占用线程在扫描ip了,所以视频会卡,我试过同时gogotester和youtube,也会这样

**Comment by decemer** [comment]
有链接吗？求发
`facebook图片上传要修改 proxy.ini 中的 hosts 规则，`

**Comment by jzp820927** [comment]
@decemer https://github.com/XX-net/XX-Net/wiki/GoAgent-Limitation

**Comment by decemer** [comment]
谢谢,issue done
