### ISSUE TITLE
Mac端，顶部菜单栏图标，选择代理方式，前边没有钩钩

### ISSUE THREAD

**Issue by cqkkk** [XX-net/XX-Net#2106]
才发现的……虚拟机windows系统，安装发现选择代理前边是有钩钩的……

**Comment by cqkkk** [comment]
忘了说下，系统是10.11.3

**Comment by zjhzxhz** [comment]
+1
虽然不是什么大问题, 但是有的确会方便很多~

**Comment by xxnet** [comment]
​文件在 launcher/mac_tray.py
可以参考windows的实现： launcher/win_tray.py

**Comment by xxnet** [comment]
@zjhzxhz  刚提交了布丁，有Mac的来帮忙测试啦

没有用git的，可以通过这个连接下载开发版：
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by cqkkk** [comment]
@xxnet  嗯，最新开发版测试，钩钩的确是有了，虽然不是大问题，不过有这个就方便多了，感谢哈
