### ISSUE TITLE
年后发一帖，大家赶紧来唠唠嗑，别过年还搞得冷冷清清的！另外，顺便发放x_tunnel流量，需要试用的，留下注册邮箱！大家热闹一下

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2109]
x_tunnel使用方法：https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B
x_tunnel下载地址： https://github.com/XX-net/XX-Net/archive/master.zip
@Cat7373  @xyuanmu  @simonasd  @Kisesy  @xxnet  ……

**Comment by Cat7373** [comment]
噗！
注册邮箱

**Comment by yeahwu** [comment]
@Cat7373 妹纸，过年相亲没有哇？

**Comment by Cat7373** [comment]
注册邮箱
流量呢！

**Comment by yeahwu** [comment]
妹子，别岔开话题，相亲，约会啥的，交流一下心得

**Comment by Sherman-Liu** [comment]
唔......想试试X-Tunnel功能，不知道可不可以申请一些流量呢？......也不知道资格够不够......

liurunze3@gmail.com

**Comment by yeahwu** [comment]
@Sherman-Liu 已转，客气了

**Comment by Sherman-Liu** [comment]
谢谢大大啦~~~

**Comment by yeahwu** [comment]
@Sherman-Liu 不客气，俺不是泡泡糖。

**Comment by simonasd** [comment]
我就默默地看着你俩就好

**Comment by yeahwu** [comment]
过年的时候，一老友又相亲回来，递烟，闲聊。
照例，问战果？
老友，默默吐着烟圈，眼角抽搐了两下，良久……“你以后不要相亲了！”
再无多言，拖着沉重的步伐，消失在风雪中……

俺心里嘀咕了好久“这是受鸟多大的侮辱呀？”

**Comment by jy0001087** [comment]
x_tunnel干哈的呢 虽然有google但并不想搜索 自己开发微信公众号好累啊.. 要哭了

**Comment by Cat7373** [comment]
@yeahwu @xxnet 
那两个 110GB 的流量，把第二个给自己转了 1GB，然后两个成功合成了一个- -
到期时间	剩余流量
2017-01-28	219.99 GB [转让]

**Comment by yeahwu** [comment]
@Cat7373  这样，你转120g给我，看转不转得出去？一试便知
yeahwu404@gmail.com

**Comment by Cat7373** [comment]
@yeahwu  122880 MB 已转

到期时间	剩余流量
2017-01-28	97.11 GB [转让]

**Comment by yeahwu** [comment]
@xxnet 这果然是bug呀！ 我还一直以为用不了。
@Cat7373 你的邮箱，俺要还回去给你。

**Comment by Cat7373** [comment]
Cat7373@github.com
http://www.letv.com/ptv/vplay/24584877.html

**Comment by yeahwu** [comment]
克扣了零头。没办法呀！见到女生总要掀一下裙子的习惯改不了哇！

**Comment by Cat7373** [comment]
@yeahwu 如果不是熟人会被打死的吧。。。

**Comment by yeahwu** [comment]
哎，都是当年的事鸟。哥如今很斯文，斯文

**Comment by fykwgl** [comment]
咦，你回来了？期待你的64位ff-xxnet。

**Comment by xxnet** [comment]
2016-02-19 20:30 GMT+08:00 YeahWu <notifications@github.com>:

> @xxnet <https://github.com/xxnet> 这果然是bug呀！ 我还一直以为用不了。
> @Cat7373 <https://github.com/Cat7373> 你的邮箱，俺要还回去给你。
>
>
> 什么bug? 我没看明白，给俺解释下

**Comment by Cat7373** [comment]
@xxnet 找不到原始讨论在哪了- -
我就再说一次吧- -
--------------------------
首先注册后会有 1MB 的流量，然后你给转了 110GB，这样算起来我应该有 1MB + 110GB 流量。
之后我用掉了那 1MB 的流量，结果剩余流量成了两个 110GB。
最初怀疑只是显示 Bug 无法使用，但是今天我自己给自己转了 1GB 试了下，发现两个 110GB 合并成了 220GB。
然后试着给@yeahwu 转了120GB，发现可以成功转出。

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/issues/2039

**Comment by Cat7373** [comment]
那么如果多注册几个号多复制几次流量。。。。。

**Comment by yeahwu** [comment]
好像服务端已经修复了，当初怎么就没想到呢？:blush::blush::blush:

**Comment by yeahwu** [comment]
@fykwgl 64位的火狐哇！哎呀，你不说我都快忘了，好说，好说

**Comment by chillgoor** [comment]
chillgoor922@gmail.com 想试一下，不知道是哪国的

**Comment by yeahwu** [comment]
@chillgoor 已转

**Comment by PS0123456** [comment]
@yeahwu 一直看你谈情说爱，可以来个50G？

**Comment by yeahwu** [comment]
@fykwgl FF-XX 64位已到，下载地址：https://www.dropbox.com/s/wvc7l5fw53x5dkh/Firefox64-XX.rar?dl=0
![20160220141313](https://cloud.githubusercontent.com/assets/13328328/13194939/da147d10-d7dd-11e5-9743-070aff3dac3e.png)

**Comment by PS0123456** [comment]
@yeahwu 说好的福利呢。。

**Comment by Cat7373** [comment]
@PS0123456 
https://zh.moegirl.org/Template:%E8%90%8C%E5%AE%85%E7%94%A8%E8%AF%AD

**Comment by yeahwu** [comment]
@PS0123456 俺不是土豪，已转了点，试用先

**Comment by PS0123456** [comment]
@Cat7373 什么意思？俺纯洁的狠，不懂啊

**Comment by cobob** [comment]
刚在后台开通也不知道怎么用，哪位有余量麻烦转一点学习一下，3Q
@yeahwu @Cat7373  

概况

账户
vfans@gmx.com [注销]

余额
$ 0.00 [充值]

流量
1.00 MB

可用流量

到期时间	剩余流量
2016-03-22	1.00 MB [转让]

**Comment by yeahwu** [comment]
@cobob 已转，不多，试用先

**Comment by fykwgl** [comment]
@yeahwu dropbox？我这边总是下载不了，劳驾换成本地下载吧。

**Comment by yeahwu** [comment]
@fykwgl 用lantern或者ss全局下载。

**Comment by fykwgl** [comment]
@yeahwu 不行，开了全局且在登陆状态下还是下不了。

> Error (403)
It seems you don't belong here! You should probably sign in. Check out our Help Center and forums for help, or head back to home.

**Comment by renyouguo** [comment]
utpuwbrs@gmail.com

**Comment by yeahwu** [comment]
@renyouguo 用x_tunnel不用理会gae状态栏
远程dns选不选都没关系

**Comment by renyouguo** [comment]
@yeahwu 已收到，谢谢。
我的问题是firefox经常提示代理服务器拒绝连接，这时候X Tunnel基本就已经出现： 电子邮件地址已被他人使用。

**Comment by fykwgl** [comment]
@yeahwu 搞定，Lantern版ff下的，多谢。

**Comment by intelligentqi** [comment]
想试一下XX-tunnel,可不可以给点流量呢


intelligentforxxnet@gmail.com

**Comment by yeahwu** [comment]
@intelligentqi 已转，不客气

**Comment by intelligentqi** [comment]
@yeahwu 收到啦 谢谢

**Comment by CRAZYmoresTeam** [comment]
我也想试试o(︶︿︶)o 唉，能不能给我转一点呢
moresteam123@gmail.com

**Comment by yeahwu** [comment]
@CRAZYmoresTeam 这两天俺的帐号老登不上去，所以转不了。
@Cat7373 帮帮忙，转点给这位兄弟。

**Comment by yeahwu** [comment]
@CRAZYmoresTeam 好了，已转

**Comment by newcastlecy** [comment]
dbero-8s23@gmail.com  转一点 试试oo

**Comment by CRAZYmoresTeam** [comment]
@yeahwu @Cat7373 好给力啊

**Comment by yeahwu** [comment]
已转，请查收

**Comment by skykain** [comment]
想试一下XX-tunnel,可不可以给点流量呢 ^_^
skykainls@gmail.com

**Comment by yeahwu** [comment]
@skykain 已转

**Comment by skykain** [comment]
@yeahwu 收到啦 谢谢.

**Comment by YaQunChan** [comment]
tonytangjian780m@gmail.com   蟹蟹啦

**Comment by yeahwu** [comment]
@YaQunChan 已转，
吖，关贴

**Comment by simear2004** [comment]
simear2004@gmail.com，先谢谢大大啦！

**Comment by yeahwu** [comment]
@simear2004 已转，俺不是大大，建议把“大大”这两个字上面的一横去掉。

**Comment by Cat7373** [comment]
人人么。。。。。

**Comment by yeahwu** [comment]
大大，明显是极权的代名词嘛，人人，才意味着平等，自由

**Comment by jzp820927** [comment]
支持，大大是极权的代名词

**Comment by simear2004** [comment]
@yeahwu 收到，谢谢了！

**Comment by simonasd** [comment]
据说赵家高层下令，封杀大大麻麻称呼。真是一出热闹的现象喜剧。
