### ISSUE TITLE
mac下系统配置选项－开机自动启动显示问题

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#211]
选择开机自动启动ON状态，然后再点别的选项，回来再点系统配置选项，开机自动启动这里还是off，虽然这里是off，但开机确实可以自动启动。

**Comment by xxnet** [comment]
1.9.4发布修复

在 2015年4月22日 上午6:59，causlayer <notifications@github.com>写道：

**Comment by causlayer** [comment]
git pull，已拉取，谢谢
