### ISSUE TITLE
全局pac智能代理会出现部分网站一直加载中

### ISSUE THREAD

**Issue by developmoster** [XX-net/XX-Net#2120]
我一直比较喜欢开着pac智能代理，然后挂在那。但是我发现会有部分网站的的部分内容会出现无法加载。比如进入CSDN论坛帖子除了顶部板块内容，其他区域会出现一直加载中；BT天堂除影片介绍，下载种子列表区域也是会一直加载中。这种情况你关闭代理又会一下子马上加载出来。在Google有时候搜索到的内容是在csdn论坛上，非要关代理才能进，开代理才能搜索，这个真心不方便。

**Comment by jzp820927** [comment]
可以 F12 分析一下
