### ISSUE TITLE
自己的appid部署成功后没有日志，也无法使用

### ISSUE THREAD

**Issue by SatyrLee** [XX-net/XX-Net#2135]
appid只显示部署成功，但是配置时又显示未部署，部署日志里也没有内容。

**Comment by SatyrLee** [comment]
诊断信息
XX-Net Status：

sys-platform: x86, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
xxnet-version: 2.9.0
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 149 / 122
network-status: OK
connected-link: 11 / 1
scan-ip-thread-num: 50
ip-quality: 894
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xyuanmu** [comment]
下载稳定版重新部署一次。
或者下载最新提交版本：https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by yu8357305** [comment]
2.8.10版本也一样无法部署，表现情况也一样

**Comment by xxnet** [comment]
​试试 2.8.9

不行的话，用start.bat 启动，然后部署，看看命令行窗口有什么异常输出，贴出来

**Comment by yu8357305** [comment]
@ xxnet  使用2.8.9部署成功，部署第一个id花费一个小时
