### ISSUE TITLE
gmail上不去了

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#2139]
google.hk 可以正常使用，gmail只能显示进度条到达约90%，然后再也没进度了，无论怎么刷新。

**Comment by farshidvahid** [comment]
诡异的事：打开全局代理，使用IE浏览器，竟然上去了。但是用chrome还是问题如上。

**Comment by linhua55** [comment]
可能是chrome中代理没设置好，导致相关部分网址遗漏

farshidvahid <notifications@github.com>于2016年2月22日周一 下午6:19写道：

**Comment by farshidvahid** [comment]
在清理cookies之后，问题得以解决。
