### ISSUE TITLE
Password tip not working in deploy page

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#214]
I cannot click the link on `#password_tip`.
I'll fix it later by adding a new pull request.

**Comment by zjhzxhz** [comment]
BTW, `focusout()` not working in IE 8.
See this [post](http://stackoverflow.com/questions/12809388/jquery-focus-and-focusout-conflict-in-ie).

**Comment by zjhzxhz** [comment]
Fixed in Pull Request #213

**Comment by xxnet** [comment]
已经合并

2015-04-22 11:57 GMT-04:00 Howard Shieh <notifications@github.com>:
