### ISSUE TITLE
和谷歌的lantern比起来，速度怎么样？

### ISSUE THREAD

**Issue by xwzpp** [XX-net/XX-Net#2146]

**Comment by yeahwu** [comment]
首先，lantern不是google的
速度上，如果youtube的话，还真的难有别的工具能彻底超越gae
当然浏览网页方面，差异很小
这里面，还有一个重要因素，会不会玩？
lantern会不会寻找和替换yaml文件？
xx-net会不会优选ip段和ip？能不能明白local文件夹？
如果都会了，1080p都不是梦

**Comment by jzp820927** [comment]
如果是 电信网，1080 就是梦

**Comment by yeahwu** [comment]
放个lantern的日本yaml文件，大家测测看看youtube能冲到多少
https://www.dropbox.com/s/lmcaivvxkewbx0c/lantern-9999.99.99.yaml?dl=0

**Comment by jzp820927** [comment]
给个统一的 Youtube 测试链接呗。

**Comment by yeahwu** [comment]
https://www.youtube.com/watch?v=xTJDZEuxy8A
应该是可以的，设置为只读试试

**Comment by yeahwu** [comment]
刚试了下，是真的，新版真不能用了。lantern终于改进了，制止乱改ip了。

**Comment by jap33** [comment]
新版比原来优化过的还快、现在只是加了三个服务器不优化了。

**Comment by jzp820927** [comment]
![default](https://cloud.githubusercontent.com/assets/5740066/13251023/9945e21e-da68-11e5-85c5-01ffbcdac333.png)
电信垃圾网络测试结果来丢人现眼了。

**Comment by jap33** [comment]
![default](https://cloud.githubusercontent.com/assets/15140842/13252040/0a7c2762-da6f-11e5-8056-497f7343afa8.PNG)

**Comment by Dannywanxyz** [comment]
@yeahwu 请问怎么优选，我的ip越来越少，过年前达到1000个的，现在只剩下可怜的90个了，怎么解决这个问题

**Comment by CHN008** [comment]
我电信4MB宽带,测试了一下偶尔有中断,平均速度420KB/s,偶尔920多KB.

![1080p](https://cloud.githubusercontent.com/assets/16646697/13259837/1b493114-da94-11e5-8519-92dca48ab10f.jpg)


![1080p-2](https://cloud.githubusercontent.com/assets/16646697/13259864/35f32fa6-da94-11e5-8373-9979573262de.jpg)

**Comment by yeahwu** [comment]
你这已经很快的了，用的是什么工具？
CHN008 <notifications@github.com>于2016年2月24日 周三01:17写道：

**Comment by jzp820927** [comment]
400+kb 还快？我去。

**Comment by yeahwu** [comment]
4mb宽带能跑到400+kb还不算快？你这要求也太高了吧！
zxzz <notifications@github.com>于2016年2月24日 周三02:18写道：

**Comment by linhua55** [comment]
MB  vs   Mb   ,注意b的大小写

YeahWu <notifications@github.com>于2016年2月24日周三 上午8:40写道：

**Comment by yeahwu** [comment]
@linhua55 年纪大了，眼神不好鸟！

@Dannywanxyz ip和ip段得找@xyuanmu，土豪级别的，有不少私货，相信有很多还是没见过光的。

至于lantern得找@Kisesy，相信他对lantern的源码研究得比较透。

至于打情骂俏请找俺，虽然研究得不透……

**Comment by yeahwu** [comment]
相信x大看到这个贴，内心几乎是崩溃的。

我tm给你们开发xx-net，为了匿名，每天卡得不要不要的，啥时候能享受到400kb/s哇？

你们这般没良心的整天在我面前秀优越，不说了，先😭一会……
Wei Xu <notifications@github.com>于2016年2月24日 周三11:02写道：

**Comment by Dannywanxyz** [comment]
@yeahwu 上面两位同学用的测速是youtube自带的测速工具，直接在视频上面右键倒数第二项就好

**Comment by CHN008** [comment]
@yeahwu  你这已经很快的了，用的是什么工具？---- 就是你们这些大神开发的xx-net;现在20M的光纤效果更好了!
