### ISSUE TITLE
x-tunnel登录不上去，老提示用户名，密码不正确。昨天还好好的

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2149]
如题，好几个帐号都一样

**Comment by yeahwu** [comment]
@Cat7373 大家不要不理我呀！这样俺会很伤心的……

**Comment by Cat7373** [comment]
表示登出后再登入一切正常。

**Comment by yeahwu** [comment]
这不是欺负人嘛，好吧，俺再下载一遍。

**Comment by yeahwu** [comment]
还是这样，妹子你用的是什么版本？俺是哪啥最新版的

**Comment by Cat7373** [comment]
SHA-1: 763414468be99b2742e619a80121137d976025e8

* Merge pull request #2126 from zjhzxhz/master

Complete i18n for PHP proxy.

**Comment by yeahwu** [comment]
应该不是客户端的问题，服务端的问题了。最老的版本，和最新的版本都试了。都登录不上去

**Comment by yeahwu** [comment]
@Cat7373 @xxnet 好了，好了，多谢x大

**Comment by Cat7373** [comment]
我给这幅图加了个评论：亲密无间
![](http://ww4.sinaimg.cn/mw600/9103a520jw1f18epaqq3nj20g40lhmyk.jpg)

**Comment by yeahwu** [comment]
好邪恶，
但是……俺喜欢

**Comment by yeahwu** [comment]
还有你放图为嘛只放一半，另一半呢
想象力更不上

**Comment by Cat7373** [comment]
神马另一半

**Comment by yeahwu** [comment]
知道啥叫不厚道吗？
就是上图只上一半屁股。

**Comment by Cat7373** [comment]
话说 Gmail 打开好慢，话说神马图。

**Comment by yeahwu** [comment]
今天又登录不上去，老提示“Connect to server fail, check GAE first.”
x大昨天更新的版本
日志
```
Feb 24 15:32:37.915 - [INFO] use config_path:E:\QQ\XX-Net-master\data\x_tunnel\client.json
Feb 24 15:32:37.917 - [INFO] Use proxy:127.0.0.1:8087
Feb 24 15:32:37.917 - [DEBUG] x-tunnel no account
Feb 24 15:32:37.918 - [WARNING] x-tunnel session not start
Feb 24 15:32:37.920 - [INFO] Socks5 server listen:127.0.0.1:1080.
Feb 24 15:33:32.926 - [DEBUG] x-tunnel web_control 127.0.0.1:2436 POST /login 
Feb 24 15:33:52.929 - [WARNING] api:login fail:status:'UNKNOWN' t:20
```

**Comment by yeahwu** [comment]
吖，又好鸟，逗俺呢！

**Comment by xxnet** [comment]
服务端正常。
​你看看GAE代理是否正常工作

**Comment by yeahwu** [comment]
俺用x-tunnel时，没有管gae代理，一上来就直奔x-tunnel，俺看看。

**Comment by yeahwu** [comment]
切换代理，导入证书，gae正常工作。

**Comment by xxnet** [comment]
​出现错误时，先检查GAE有没有问题

**Comment by yeahwu** [comment]
好的，谢谢x大

**Comment by Cat7373** [comment]
今天真倒霉，睡午觉狗狗一直叫没睡好，起来喝杯水又把被子盖打了，摔成了十几块。。。
![](http://ww4.sinaimg.cn/mw600/7199a862gw1f18jju7hysj20ax1req9s.jpg)
![](http://ww3.sinaimg.cn/mw600/7199a862gw1f18jjvlf0oj20ax1ll7ak.jpg)

**Comment by Cat7373** [comment]
![](http://ww3.sinaimg.cn/mw600/ddf0f092gw1f19r7a3zluj20c811fjw4.jpg)

**Comment by yeahwu** [comment]
@Cat7373 你到底是男的还是女妹纸？
这个男的就是个话痨，

妹子来一场说干就干的爱情啵？

**Comment by Cat7373** [comment]
咦，咱只是看到有趣的图就转过来，有神马问题咩

**Comment by yeahwu** [comment]
从前，俺仰慕的一位妹纸，欲求之，而人家不鸟之的那种。
她也喜欢看这种内涵图，然后…… 变得太有内涵鸟，到现在还没嫁出去。
哎，这是一个忧伤的故事……

**Comment by Cat7373** [comment]
![](http://ww2.sinaimg.cn/mw690/9103a520jw1f1al0tqy3uj20jo0bot9s.jpg)
