### ISSUE TITLE
1.9.4版配置页面，局域网代理指引“如何通过文件配置”链接有误

### ISSUE THREAD

**Issue by tearfularcher** [XX-net/XX-Net#215]
1.9.4版配置页面，指引“如何通过文件配置”链接：hhttps://*******,貌似应该是https://*****

**Comment by zjhzxhz** [comment]
已修复 in Pull Request #213 
这个问题早就提交了Pull Request, 只是我提交Pull Request的时候懒得提交Issue了而已.

不过还是感谢你的指正.
等待原作者合并.

**Comment by causlayer** [comment]
这个功能太好了，不用修改proxy.ini本身，直接手动加个文件就解决了
[listen]
ip = 0.0.0.0

**Comment by xxnet** [comment]
已经合并，再测试下就发布新版

2015-04-22 20:51 GMT-04:00 causlayer <notifications@github.com>:
