### ISSUE TITLE
服务端部署错误

### ISSUE THREAD

**Issue by prosejazz** [XX-net/XX-Net#216]
Apr 23 12:35:06 - ============  Begin upload  ============
appid:fbitxxx 

Apr 23 12:35:06 - Application: fbitxxx
Apr 23 12:35:06 - Host: appengine.google.com
Apr 23 12:35:06 - Rolling back the update.
Apr 23 12:35:27 - upload  fail: The read operation timed out

Apr 23 12:35:27 - Retry again.

Apr 23 12:35:28 - Application: fbitxxx
Apr 23 12:35:28 - Host: appengine.google.com
Apr 23 12:35:28 - Rolling back the update.
Apr 23 12:35:53 - upload  fail: The read operation timed out

Apr 23 12:35:53 - Retry again.

Apr 23 12:35:54 - Application: fbitxxx
Apr 23 12:35:54 - Host: appengine.google.com
Apr 23 12:35:54 - Rolling back the update.
Apr 23 12:36:14 - upload  fail: The read operation timed out

Apr 23 12:36:14 - Retry again.

Apr 23 12:36:15 - Application: fbitxxx
Apr 23 12:36:15 - Host: appengine.google.com
Apr 23 12:36:15 - Rolling back the update.
Apr 23 12:36:35 - upload  fail: The read operation timed out

Apr 23 12:36:35 - Retry again.

Apr 23 12:36:36 - Application: fbitxxx
Apr 23 12:36:36 - Host: appengine.google.com
Apr 23 12:36:36 - Rolling back the update.
Apr 23 12:36:56 - upload  fail: The read operation timed out

Apr 23 12:36:56 - Retry again.

Apr 23 12:36:57 - Application: fbitxxx
Apr 23 12:36:57 - Host: appengine.google.com
Apr 23 12:36:57 - Rolling back the update.
Apr 23 12:37:17 - upload  fail: The read operation timed out

Apr 23 12:37:17 - Retry again.

Apr 23 12:37:18 - Application: fbitxxx
Apr 23 12:37:18 - Host: appengine.google.com
Apr 23 12:37:18 - Rolling back the update.
Apr 23 12:37:38 - upload  fail: The read operation timed out

Apr 23 12:37:38 - Retry again.

Apr 23 12:37:39 - Application: fbitxxx
Apr 23 12:37:39 - Host: appengine.google.com
Apr 23 12:37:39 - Rolling back the update.
Apr 23 12:37:59 - upload  fail: The read operation timed out

Apr 23 12:37:59 - Retry again.

Apr 23 12:38:00 - Application: fbitxxx
Apr 23 12:38:00 - Host: appengine.google.com
Apr 23 12:38:00 - Rolling back the update.
Apr 23 12:38:20 - upload  fail: The read operation timed out

Apr 23 12:38:20 - Retry again.

Apr 23 12:38:21 - Application: fbitxxx
Apr 23 12:38:21 - Host: appengine.google.com
Apr 23 12:38:21 - Rolling back the update.
Apr 23 12:38:41 - upload  fail: The read operation timed out

Apr 23 12:38:41 - == END ==

下面还有日志
Apr 23 12:38:45 - [DEBUG] get ip:1.179.248.167 t:938
Apr 23 12:38:46 - [DEBUG] create_ssl update ip:202.169.193.113 time:606
Apr 23 12:38:46 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:46 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:46 - [DEBUG] ssl conn_num:0
Apr 23 12:38:46 - [DEBUG] get ip:64.233.167.137 t:939
Apr 23 12:38:46 - [DEBUG] create_ssl update ip:64.233.162.86 time:740
Apr 23 12:38:46 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:46 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:46 - [DEBUG] ssl conn_num:0
Apr 23 12:38:46 - [DEBUG] get ip:123.205.250.106 t:939
Apr 23 12:38:47 - [DEBUG] get ip:64.233.176.196 t:939
Apr 23 12:38:47 - [DEBUG] create_ssl 64.15.116.214 fail:timed out c:0 h:0
Apr 23 12:38:47 - [DEBUG] create_ssl 1.179.248.167 fail:timed out c:0 h:0
Apr 23 12:38:47 - [DEBUG] network is fail
Apr 23 12:38:47 - [DEBUG] report_connect_fail network fail
Apr 23 12:38:47 - [DEBUG] get ip:194.78.99.217 t:939
Apr 23 12:38:47 - [DEBUG] network is ok
Apr 23 12:38:47 - [DEBUG] create_ssl 64.233.167.137 fail:timed out c:0 h:0
Apr 23 12:38:47 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:48 - [DEBUG] create_ssl 123.205.250.106 fail:timed out c:0 h:0
Apr 23 12:38:48 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:48 - [DEBUG] FWD CONNECT clients4.google.com:443 with closed
Apr 23 12:38:48 - [DEBUG] get ip:61.19.1.221 t:440
Apr 23 12:38:48 - [DEBUG] get ip:213.158.11.251 t:449
Apr 23 12:38:48 - [DEBUG] create_ssl 64.233.176.196 fail:timed out c:0 h:0
Apr 23 12:38:48 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:48 - [DEBUG] get ip:173.194.192.165 t:490
Apr 23 12:38:48 - [DEBUG] create_ssl 194.78.99.217 fail:timed out c:0 h:0
Apr 23 12:38:48 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:48 - [DEBUG] create_ssl update ip:61.19.1.221 time:447
Apr 23 12:38:48 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:48 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:49 - [DEBUG] ssl conn_num:0
Apr 23 12:38:49 - [DEBUG] get ip:64.233.182.201 t:503
Apr 23 12:38:49 - [DEBUG] create_ssl update ip:213.158.11.251 time:454
Apr 23 12:38:49 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:49 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:49 - [DEBUG] ssl conn_num:0
Apr 23 12:38:49 - [INFO] FWD CONNECT clients1.google.com:443 
Apr 23 12:38:49 - [DEBUG] get ip:173.194.202.31 t:512
Apr 23 12:38:49 - [DEBUG] create_ssl update ip:173.194.192.165 time:499
Apr 23 12:38:49 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:49 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:49 - [DEBUG] ssl conn_num:0
Apr 23 12:38:49 - [DEBUG] get ip:213.158.11.170 t:528
Apr 23 12:38:49 - [DEBUG] get ip:213.158.11.222 t:626
Apr 23 12:38:49 - [DEBUG] create_ssl update ip:64.233.182.201 time:511
Apr 23 12:38:49 - [DEBUG] tcp conn 173.194.202.31 time:326
Apr 23 12:38:49 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:49 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:49 - [DEBUG] ssl conn_num:0
Apr 23 12:38:49 - [DEBUG] get ip:74.125.224.25 t:940
Apr 23 12:38:49 - [DEBUG] get ip:178.45.251.103 t:940
Apr 23 12:38:50 - [DEBUG] tcp conn 213.158.11.222 time:259
Apr 23 12:38:50 - [DEBUG] get ip:64.233.185.90 t:940
Apr 23 12:38:50 - [DEBUG] create_ssl update ip:213.158.11.170 time:557
Apr 23 12:38:50 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:50 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:50 - [DEBUG] ssl conn_num:0
Apr 23 12:38:50 - [DEBUG] get ip:64.15.113.184 t:940
Apr 23 12:38:50 - [DEBUG] get ip:64.15.126.254 t:940
Apr 23 12:38:51 - [DEBUG] create_ssl 74.125.224.25 fail:timed out c:0 h:0
Apr 23 12:38:51 - [DEBUG] get ip:213.158.11.59 t:434
Apr 23 12:38:51 - [DEBUG] create_ssl 178.45.251.103 fail:timed out c:0 h:0
Apr 23 12:38:51 - [DEBUG] network is fail
Apr 23 12:38:51 - [DEBUG] report_connect_fail network fail
Apr 23 12:38:51 - [DEBUG] create_ssl 64.233.185.90 fail:timed out c:0 h:0
Apr 23 12:38:51 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:52 - [DEBUG] network is ok
Apr 23 12:38:52 - [DEBUG] create_ssl 64.15.113.184 fail:timed out c:0 h:0
Apr 23 12:38:52 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:52 - [DEBUG] create_ssl update ip:213.158.11.59 time:549
Apr 23 12:38:52 - [DEBUG] create_ssl 64.15.126.254 fail:timed out c:0 h:0
Apr 23 12:38:52 - [DEBUG] report_connect_fail network fail recently
Apr 23 12:38:52 - [ERROR] No usable appid left, add new appid to continue use GoAgent
Apr 23 12:38:52 - [WARNING] gae_exception: 'https://appengine.google.com/api/appversion/rollback?version=1&app_id=fbitxxx'
Apr 23 12:38:52 - [DEBUG] get ip:213.158.11.177 t:512

输入网址打开appengine的时候也是打不开

![image](https://cloud.githubusercontent.com/assets/6355442/7290756/26a3bee0-e9b7-11e4-90ab-2a011547a1bd.png)

**Comment by xxnet** [comment]
No usable appid left

部署前，先确认能够访问网站。

估计你填的appid还没有部署。
你应该先部署，再填如设置中。

2015-04-23 0:40 GMT-04:00 prosejazz <notifications@github.com>:

**Comment by momoca** [comment]
通过 XX-Net\goagent\3.1.49\server>uploader.bat <appids> <email> [password]
部属成功了.但怎么感觉没有以前快了呢?
