### ISSUE TITLE
Ajax Option 请求没有办法通过XX-NET 代理出去

### ISSUE THREAD

**Issue by SuperMatch** [XX-net/XX-Net#2164]
最近有访问到网站发现没有办法通过xxnet代理option方法的ajax请求。因为网站是adobe的一个需要登陆的网页。公司的登陆凭据没法提供。所以不知道能不能看下源码哪里可以改改的？

**Comment by jzp820927** [comment]
gae 不支持 option方法，和 XX 没关系

**Comment by SuperMatch** [comment]
哦 好的 谢谢
