### ISSUE TITLE
google 搜索经常需要输入验证码

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#2167]
首先google.com上不去，只能上google.com.hk；其次，使用google.hk搜索时，经常说流量异常，要求输入很长的验证码。如图所示。请教这个问题怎么解决？
![aa](https://cloud.githubusercontent.com/assets/13399800/13346302/3cbf38f8-dca0-11e5-8fdb-ada0200652d1.jpg)

**Comment by linhua55** [comment]
#2159 
https://www.google.com/ncr

**Comment by farshidvahid** [comment]
感谢！
