### ISSUE TITLE
卡带的问题

### ISSUE THREAD

**Issue by Archer-zty** [XX-net/XX-Net#2172]
电脑win10，有时候会有整个界面卡住的不到1秒的时间。
网上有人说是xxnet的问题，求证~

**Comment by xiuluo** [comment]
是的，这是一个已知bug，暂时无法完美解决。你可以进，http://127.0.0.1:8085/?module=gae_proxy&menu=advanced，把最大扫描线程数改为1

**Comment by tedchina** [comment]
未必与XXNET相关。
电脑什么配置？低配置电脑在Win10下是会有类似现象，特别是用Chrome等内存消耗大户时，在Win7/Win8下没有此类突然卡顿（只是整体不流畅而已）。

**Comment by Archer-zty** [comment]
(〃･̆ ･̆〃) ​​​​老哥，这是两年前的问题，而且人家已经说了，「这是已知bug」。现在没事了
