### ISSUE TITLE
2.8.9 版本，firefox打不开Google+,chrome可以

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#2174]
https://github.com/XX-net/XX-Net/commit/18a028b29bf39a10fa3571ef29966d2e7253d6ab

https://plus.google.com

https://github.com/XX-net/XX-Net/commit/262bc7343f2ee8533df66316e8c5d1c1b00ec796
Google+ 用firefox,又可以访问了

谷歌需先用 https://www.google.com/ncr 访问

**Comment by yeahwu** [comment]
啥子情况？
