### ISSUE TITLE
右键google搜索无法使用

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#2195]
以前使用google搜索，经常需要输入验证码。参照#1573 修改后，验证码不要求了。但右键google搜索的功能却废了。选定某个内容，右键google搜索，始终打不开网页。只有复制该内容，在新tab里打开google，然后搜索。

请教这个问题如何解决？感谢！

**Comment by linhua55** [comment]
试试2.9.3测试版

**Comment by farshidvahid** [comment]
感谢！
