### ISSUE TITLE
怎么goagent/3.1.32里面没有goagent.exe呀?下载一个3.4版本的goagent放进去不行呀

### ISSUE THREAD

**Issue by lijinshanmx** [XX-net/XX-Net#22]
是不是goagent.exe,忘了push上去了?还是不需要它了呢.
真心喜欢这个整合版的,希望给点提示,我在弄弄.

**Comment by xxnet** [comment]
对，goagent.exe不需要了，完全的proxy实现，调用win32api。
有什么问题欢迎交流，可以看看wiki的资料，不定期更新。

代码特别清理过，遵循python已读容易理解的原则，欢迎review.

**Comment by xxnet** [comment]
哪里有3.4的版本？
