### ISSUE TITLE
自动更新影响Unix文件权限

### ISSUE THREAD

**Issue by cc941201** [XX-net/XX-Net#2206]
`launcher/update_from_github.py`中使用从GitHub上面下载的zip包来更新程序，导致所有修改后的文件权限被重置。#2198 中的问题就是因此引起的，经过更新的`start.command`不再有执行权限。如果手动下载最新版解压不出现此问题。

建议在替换前读取原文件权限，替换后复原。

**Comment by cc941201** [comment]
估计得先回滚e10dce2，确保更新时能保留执行权限再动

**Comment by xxnet** [comment]
​明白了，需要可执行权限的，只有2个文件，也只有Linux/Mac两个平台需要，可以在升级脚本中实现

**Comment by cc941201** [comment]
@xxnet 恩，还有一个问题是如何确保升级脚本是最新的，如果有人从老版更新依然会出问题。`start.command`和`start.sh`估计是不能动了。

**Comment by xxnet** [comment]
​目前的升级设计有问题，经常升级到一半遇到问题，然后部分文件是新的，部分文件是旧的，结果再启动就无法工作了。
整个结构要大改，升级要放到一个新的目录，升级完整后，再整个切换过去

**Comment by cc941201** [comment]
那估计得加入阶段式升级了，比如要求先升到2.10再升3.0。以现在的升级方式，直接升上去不出问题比较难

**Comment by xxnet** [comment]
恩，这是个办法，必须先升级的2.10，才拥有升级3.x能力，否则只能手动下载

**Comment by zhenhappy** [comment]
@xxnet 2.10在哪里下载,为何我找不到

**Comment by cc941201** [comment]
@zhenhappy 还没出，只是一个假设

**Comment by cc941201** [comment]
Closed by #2945
