### ISSUE TITLE
借xx宝地，又来无耻一把。讨APPID鸟，发现大家最近不是很活跃嘛，俺来召唤一下。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2207]
依然是APPID捐赠，由于firefox-xx项目下载量比较大。ID不够用了，大家有闲余的捐献几个，方便小白呼吸到自由空气。
另，不接受设置了rc4密码的ID，谢谢大家
联系邮箱：yeahwu404@gmail.com
项目地址：https://github.com/yeahwu/firefox-xx﻿
@Cat7373 @simonasd @xyuanmu @Kisesy @linhua55 @mikedchavez1010 @zjhzxhz ……

**Comment by caofengzi** [comment]
@yeahwu 看起來捐贈appid的人還是不多啊，如果一個帳號能夠多申請點就好了。

**Comment by panzer1313208** [comment]
@yeahwu 虽然我有几百个Appid。我只用了28个。但是问题是你并没有艾特我。所以我很生气。决定不给你捐Appid了！

**Comment by xxnet** [comment]
​@YeahWu
  捐appid就送X_tunnel流量吧，这样大家更有动力。
  最近1个月收到接近200个appid的捐献。

**Comment by jzp820927** [comment]
我去，看来流量的吸引力还是挺大的，都是被SS给弄的，现在流量太宝贵了。

**Comment by yeahwu** [comment]
这真是奇了怪了，今天流量还剩挺多。前两天不到12点就用完了。
@panzer1313208 俺@你鸟，后面不是还有一个省略号嘛，
@xxnet 谢x大建议，也对哦，忘了这茬。

**Comment by yeahwu** [comment]
话说妹子@Cat7373最近很文静嘛，粗来扯扯蛋！

**Comment by Cat7373** [comment]
给泥萌看个新闻↓

![](http://ww4.sinaimg.cn/large/9103a520jw1f1ilgsyg8yj20l20gn78z.jpg)
![](http://ww4.sinaimg.cn/large/9103a520jw1f1ilgsc81ej20kv0fjgqm.jpg)

**Comment by yeahwu** [comment]
小屁娃儿，这年龄应该是“踢房子”的年龄，禽兽父母

**Comment by yeahwu** [comment]
最近phuslu现身鸟，goproxy时隔半年更新鸟，shadowsocks也更新鸟，形势一片大好哇

**Comment by Cat7373** [comment]
shadowsocks 从一开始就没删0.0
只是建了个新版本库并设置成主版本库
然后在里面加了个项目已删除的说明
以前的库其实还在0.0

**Comment by yeahwu** [comment]
其实俺更喜欢搞goproxy，大有可为的项目。
有没有感觉x-tunnel非常不稳定？

**Comment by yeahwu** [comment]
在推上看到这段话，真tm有道理“男人有錢會變壞，Linux 用戶有錢會投入 Mac 懷抱”

**Comment by yeahwu** [comment]
https://github.com/programthink/zhao/issues
这里很热闹，哈哈

**Comment by caofengzi** [comment]
@yeahwu 這個地址是編程隨想建立的。

**Comment by xyuanmu** [comment]
谷歌帐号都是几年前申请的，多年木有添加appid了，之前能申请25个的时候没申请现在有点后悔啊，不然现在就有很多多余的appid了。

**Comment by yeahwu** [comment]
俺也是，帐号注册好几年，然后申请的时候，没申请到25个的时候就不耐烦鸟，结果也就是一个帐号申请10来个。
不过没关系，好像ID又够用了，前两个好像是“姨妈期”，现在好鸟。

**Comment by Cat7373** [comment]
表示我注册了25个。。。

**Comment by yeahwu** [comment]
https://github.com/programthink/zhao/issues/23

**Comment by Cat7373** [comment]
刚刚升级了win10，格盘重装的那种- -
正在重新装乱七八糟的工具。。。

**Comment by yeahwu** [comment]
@Cat7373 傻孩子，干嘛要往坑里跳！迟早你会回到win7的。
建议win7，或者linux，ubuntu或者linux mint啥的

**Comment by Cat7373** [comment]
整个win7系统盘用Ghost分区对分区直接备份到了另外一个硬盘里。。。

**Comment by yeahwu** [comment]
哎，俺这电脑跑不动windows鸟，只得linux慢慢熬，有钱鸟必须投奔mac的怀抱。

**Comment by Cat7373** [comment]
除了列了个巨大的清单需要装之外。。。
目前唯一的问题就是，网会 5 ~ 30 分钟之间，随机断，显示黄感叹号，点开连接信息看到IP网关DNS的一切正常，过一会就自动又连上了。。。

**Comment by yeahwu** [comment]
你这应该是网卡驱动的问题，或者是网线松了
俺来告诉你以后会遇到什么问题，
1:菜单键卡死
2:小娜就是个累赘，卡死
3:天天给你同步，不经过你同意
4:各种驱动，各种游戏不兼容
5:翻墙软件，未知错误，明明脚本没问题，就是给你报错
……

**Comment by Cat7373** [comment]
@yeahwu 现在的确还有不少毛病- -
不过补丁还没打到最新- -
打完再试试看吧- -
（装完第一次打补丁，提示正在准备Windows，请勿关闭你的计算机，然后等了一个半小时，然后是安装失败- -）

**Comment by caofengzi** [comment]
感覺還是7穩定。

**Comment by Cat7373** [comment]
果然是驱动精灵的错，驱动都不知道是哪年的，驱动精灵居然没找到有更新- -
还驱动人生马上提示无线网卡驱动需要更新惹

**Comment by panzer1313208** [comment]
win10绝对有问题。相信我。软件不兼容。而且还有其他问题。赶紧退回win7吧。我以一个用了1年win10的前辈身份来告诉你！

**Comment by Cat7373** [comment]
噗，win10正式发布有够一年么。。。

**Comment by panzer1313208** [comment]
@Cat7373 我会告诉你win10从2014年10月份的时候就有大把的人用了么？

**Comment by panzer1313208** [comment]
@Cat7373 然后2015年7月份才出的专业版。

**Comment by Cat7373** [comment]
那是预览版，预览版就跟XX-Net的测试版似的，有毛病不是很正常的。

**Comment by panzer1313208** [comment]
@Cat7373 我说了我已经用了一年了。从预览版到专业版的th2版本。然后就退回win7了。

**Comment by yeahwu** [comment]
嗯，俺用过的就是开发者预览版，后来提醒俺可以升级到正式版，伤得太深，弃微软而去。

**Comment by Cat7373** [comment]
@yeahwu 目前没啥大毛病- -
唯一一个问题就是微软的C#开发工具VS没法用。。。

**Comment by yeahwu** [comment]
Visual Studio 
1，太臃肿
2，对 C++ 标准的支持太慢
3 ，编辑功能弱
4，哥不会编程，就是瞎讲的

**Comment by Cat7373** [comment]
我快绝望了。。。
一个修复一小时，然后不行。
一个卸载一个安装，俩小时，然后还是不行。

**Comment by yeahwu** [comment]
赶紧弃window奔liunx保平安

**Comment by yeahwu** [comment]
另外悄悄告诉你，这个群里很多妹子哦，一般淫，俺不告诉他
https://plus.google.com/communities/101215702940766881013

**Comment by Cat7373** [comment]
@yeahwu 
win10其实没出什么问题，不过这Visual Studio的确是够屌的。
安装路径里不能有中文，不然安装之后就给你抛错，什么都不能用，而且安装的时候一点提示也不带给你的，鬼知道不能带中文。
然后卸载了重装发现，重装的时候路径选择是灰色的，不让选路径了，也就是说就这样再装上还是那个带中文的地方，百度Google半天也没找到个解决方案。
然后下了个注册表读写监视器，找到了安装路径存在哪，强行改了。
这次打开可以安装到纯英文的路径了，结果安装完打开项目后提示找不到编辑器，要不就是把源码以纯文本打开了，一点高亮语法分析的都没有。
然后果断再次打开安装器，选修复，一个小时过去修复完了让重启，重启之后，该什么样还什么样。
好吧，我现在认了，VS这东西只要第一次选路径没选对，就再也没机会改正了，唯一的办法就是整个系统重装。
微软你牛逼！

**Comment by yeahwu** [comment]
离不开windows的都不是好孩子，哼
今天第一次用xx部署APPID，原来这么简单，汗
以前用goagent部署的时候，还得搞vpngate全局辅助。

**Comment by Cat7373** [comment]
发几张图给你们感受下：
![](http://ww1.sinaimg.cn/large/9103a520jw1f1km4hchbkj20d80gjwgl.jpg)
![](http://ww1.sinaimg.cn/large/9103a520jw1f1km4g4ybej20c204jjt2.jpg)
![](http://ww4.sinaimg.cn/large/9103a520jw1f1km4glfbij20r10eladh.jpg)

**Comment by yeahwu** [comment]
技术支持388，艹
俺帮人家装系统，修电脑，胸都不给俺摸一下

**Comment by Cat7373** [comment]
重装完了，VS用默认路径，一点也没敢改，这次没问题了- -

**Comment by yeahwu** [comment]
你上次给lantern反应的，好像2.1.0版，给办鸟

**Comment by Cat7373** [comment]
好像是，但是没放编译结果 - -
反正我也不常用 - -
也就没去研究怎么编译- -

**Comment by yeahwu** [comment]
其实是没搞懂搞个“设置系统代理”是干嘛的？
![lantern11](https://cloud.githubusercontent.com/assets/13328328/13527948/e3afe9e8-e24d-11e5-9668-8435bb2cd5eb.JPG)

**Comment by Cat7373** [comment]
最新的有编译结果的稳定版里似乎没这个选项0.0
你自己编译的么- -

**Comment by yeahwu** [comment]
gary12编译的，应该是最新源码。俺嘛，认识ABCD就不错鸟。

**Comment by caofengzi** [comment]
哈哈嘿嘿。

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=4.4.4&source=email_footer_2] On 周五, 3月 04, 2016 at 9:28 下午, YeahWu < notifications@github.com [notifications@github.com] > wrote:
gary12编译的，应该是最新源码。俺嘛，认识ABCD就不错鸟。

—
Reply to this email directly or view it on GitHub
[https://github.com/XX-net/XX-Net/issues/2207#issuecomment-192283054] .[https://github.com/notifications/beacon/ANBJTH8qqtdwdFuCKf2ss1gmCIb25Krhks5pqDN9gaJpZM4HmiZN.gif]

**Comment by yeahwu** [comment]
曹兄见笑鸟。
下面是lantern2.1.0版
https://copy.com/DIqj28Fre9W12PQf/lantern160303b.tar.gz?download=1

**Comment by xyuanmu** [comment]
**设置系统代理**就是那个设置pac的选项，不管有没有勾选退出蓝灯都会强制清空pac，这个选项有没有都那么DT。

**Comment by yeahwu** [comment]
lantern的pac能用？看来以后还得用gary的版本鸟。

**Comment by yeahwu** [comment]
@xyuanmu 兄，ip段得更新鸟，私货啥的放出来呗。

**Comment by xyuanmu** [comment]
@yeahwu 上次放出来的还有好多能用的，看样子GFW不积极，等它积极了我再放。

**Comment by simonasd** [comment]
现在部署已经很程序化很方便了，不知道申请APPID有没有办法自动化

**Comment by caofengzi** [comment]
申请appid不可能自动化，因为申请和xx没有关系。

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=4.4.4&source=email_footer_2] On 周六, 3月 05, 2016 at 1:13 下午, simonasd < notifications@github.com [notifications@github.com] > wrote:
现在部署已经很程序化很方便了，不知道申请APPID有没有办法自动化

—
Reply to this email directly or view it on GitHub
[https://github.com/XX-net/XX-Net/issues/2207#issuecomment-192576691] .[https://github.com/notifications/beacon/ANBJTJyp2F5-xro69JIf1Ned-wBWpkJ6ks5pqRDpgaJpZM4HmiZN.gif]

**Comment by xxnet** [comment]
​申请APPID是有可能自动化的，看看这个项目：
https://github.com/jay0lee/GAM

理论上所有web上的操作，都是js脚本和http api的交互。
很多API google都有提供文档，有些是有现成的项目可以参考的。

**Comment by simonasd** [comment]
@caofengzi 同意@xxnet 所说的“理论上所有web上的操作，都是js脚本和http api的交互。”我的疑惑主要是在“实现成本”而不是“可能性”，哈哈

**Comment by xxnet** [comment]
为了提高接收appid捐献的效率，目前​已经实现脚本自动化了，感觉没有想象那么麻烦。
不过目前的cookie是从浏览器里抄的，不是脚本通过登陆获取的。

之前有看过一个脚本去下载google driver的文件，也是需要去模拟浏览器行为。
包括you-get应该也是类似。
感觉这个领域很多人在研究，应该没有那么难的。

**Comment by linhua55** [comment]
对，需要模拟浏览器行为
cookie一般是从某个HTTP请求/应答中获得的，也有可能是js代码中算法生成的，只需要获取必需的cookie就行了。如果服务端只是验证是否存在这个cookie，而不对它的值进行验证的话，自己指定/伪造cookie的值也是可以的。关键就是找到那些最少的必需的请求。

Michael.X <notifications@github.com>于2016年3月7日周一 下午12:13写道：

**Comment by simonasd** [comment]
@xxnet 就python而言，一些基于curl的库应该都支持保存cookie，可以试试用post命令登录Google？

试着看了一下，Google账号的登录，是往[https://accounts.google.com/ServiceLoginAuth]发送的一个post请求。不过除了“email”和“password”之外的字段还有很多，其中有一些似乎是加密后的信息。

**Comment by jglimmers** [comment]
看这标题俺就知道是同道中人 俺就点进来了：）

**Comment by yeahwu** [comment]
@jglimmers 欢迎，同道中人！
