### ISSUE TITLE
建议：可否考虑增加 data/gae_proxy 下面 ip_range.txt 文件，作为自定义IP扫描数据来源？

### ISSUE THREAD

**Issue by jzp820927** [XX-net/XX-Net#2214]
目前，默认扫描的 IP 数据源来自 gae_proxy/local/ip_range.txt，里面包含了上百万个所有可能是 GWS 的IP 段，可否考虑在 data/gae_proxy 下面，让用户可以手动添加 ip_range.txt 文件，作为用户自定义 IP 数据源，当 data/gae_proxy 下面有 ip_range.txt 文件的时候，自动读取这个文件作为IP数据扫描来源，默认的 gae_proxy/local/ip_range.txt 则不扫描，如果data下面没有这个文件，则读取默认位置文件  gae_proxy/local/ip_range.txt，作为IP数据扫描来源。类似于 proxy.user.ini 的作用。

好处：减小IP扫描数据源的IP数量，这样可以调小扫描线程，减小网络压力，特别适合 路由器，手机这种移动设备。而且放在data下面，也比直接修改 gae_proxy/local/ip_range.txt 好，这样升级的时候，方便备份和还原。

不知建议适合合理，请XX老大评价。

**Comment by xxnet** [comment]
已经实现了，而且在web_ui界面上就可以操作，在高级菜单中

**Comment by jzp820927** [comment]
原来有啊，wiki 里面没看到说明，谢谢了！
