### ISSUE TITLE
百度百科乱码

### ISSUE THREAD

**Issue by xilovesyu** [XX-net/XX-Net#2217]
开启Proxy Switch 百度百科乱码，关闭正常显示

**Comment by zhenruyan** [comment]
=。=跳墙后看百度百科。。。。什么逻辑，，，，原谅我

**Comment by auyoung** [comment]
switch sharp用自动切换模式

**Comment by shanmm** [comment]
对的我也是这样，头疼

**Comment by simonasd** [comment]
可能是百度百科有部分地址放到了其他域名上，没有在直连名单中？

打开浏览器控制台（按F12）看看有没有报错。如果你使用了switch omiga插件，插件图标上是否有数字？如果有，单击图标之后点击“X个资源未加载”按钮，添加直接连接规则。

**Comment by xilovesyu** [comment]
还是把百度放在直连名单就好了
