### ISSUE TITLE
突然就上不去了呢今天，早上起来还好好的

### ISSUE THREAD

**Issue by hookybaby** [XX-net/XX-Net#222]
Apr 24 10:47:58 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:58 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:58 - [DEBUG] get ip:64.15.126.212 t:900
Apr 24 10:47:58 - [DEBUG] get ip:208.117.229.244 t:901
Apr 24 10:47:58 - [DEBUG] tcp conn 123.205.250.112 fail t:1000
Apr 24 10:47:58 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:58 - [DEBUG] tcp conn 203.116.165.247 fail t:1000
Apr 24 10:47:58 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:58 - [DEBUG] get ip:74.125.20.124 t:902
Apr 24 10:47:58 - [DEBUG] get ip:216.58.210.197 t:902
Apr 24 10:47:58 - [DEBUG] get ip:208.117.227.88 t:903
Apr 24 10:47:58 - [DEBUG] tcp conn 114.4.41.216 fail t:1000
Apr 24 10:47:58 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:58 - [DEBUG] get ip:64.15.116.250 t:904
Apr 24 10:47:59 - [DEBUG] tcp conn 210.245.14.247 fail t:1000
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:59 - [DEBUG] get ip:64.15.119.222 t:904
Apr 24 10:47:59 - [DEBUG] create_ssl 210.245.14.177 fail:timed out c:0 h:0
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:59 - [DEBUG] get ip:86.127.118.173 t:904
Apr 24 10:47:59 - [DEBUG] get ip:64.233.186.118 t:904
Apr 24 10:47:59 - [DEBUG] tcp conn 208.117.229.244 fail t:1001
Apr 24 10:47:59 - [DEBUG] tcp conn 64.15.126.212 fail t:1000
Apr 24 10:47:59 - [DEBUG] network is fail
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail
Apr 24 10:47:59 - [DEBUG] get ip:61.19.1.153 t:809
Apr 24 10:47:59 - [DEBUG] tcp conn 216.58.210.197 fail t:1001
Apr 24 10:47:59 - [DEBUG] tcp conn 74.125.20.124 fail t:1002
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:59 - [DEBUG] get ip:61.19.1.251 t:825
Apr 24 10:47:59 - [DEBUG] get ip:64.233.171.201 t:830
Apr 24 10:47:59 - [DEBUG] create_ssl 85.182.250.88 fail:timed out c:0 h:0
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:47:59 - [DEBUG] network is ok
Apr 24 10:47:59 - [DEBUG] get ip:61.19.1.178 t:837
Apr 24 10:47:59 - [DEBUG] tcp conn 64.15.116.250 fail t:1000
Apr 24 10:47:59 - [DEBUG]LOG_EXCEPT: report_connect_fail network fail recently, Except:[Errno 9] Bad file descriptor
Apr 24 10:47:59 - [DEBUG] get ip:208.117.225.42 t:852
Apr 24 10:47:59 - [DEBUG] create_ssl 64.233.180.166 fail:timed out c:0 h:0
Apr 24 10:47:59 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] tcp conn 64.15.119.222 fail t:1000
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] get ip:61.19.1.168 t:869
Apr 24 10:48:00 - [DEBUG] sort ip time:6
Apr 24 10:48:00 - [DEBUG] get ip:194.78.99.244 t:870
Apr 24 10:48:00 - [DEBUG] create_ssl 208.117.227.88 fail:timed out c:0 h:0
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] tcp conn 61.19.1.153 fail t:1000
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] get ip:195.249.20.231 t:876
Apr 24 10:48:00 - [DEBUG] tcp conn 61.19.1.251 fail t:1000
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] tcp conn 64.233.171.201 fail t:1000
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] get ip:216.58.211.193 t:876
Apr 24 10:48:00 - [DEBUG] get ip:123.205.251.114 t:878
Apr 24 10:48:00 - [DEBUG] get ip:173.194.204.191 t:878
Apr 24 10:48:00 - [DEBUG] tcp conn 61.19.1.178 fail t:1000
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] get ip:74.125.229.27 t:878
Apr 24 10:48:00 - [DEBUG] tcp conn 208.117.225.42 fail t:1000
Apr 24 10:48:00 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:00 - [DEBUG] get ip:203.165.13.210 t:878
Apr 24 10:48:00 - [DEBUG] get ip:64.15.116.186 t:878
Apr 24 10:48:01 - [DEBUG] create_ssl 86.127.118.173 fail:timed out c:0 h:0
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] create_ssl 64.233.186.118 fail:timed out c:0 h:0
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] tcp conn 61.19.1.168 fail t:1000
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] get ip:216.58.210.119 t:878
Apr 24 10:48:01 - [DEBUG] get ip:216.58.213.34 t:879
Apr 24 10:48:01 - [DEBUG] tcp conn 195.249.20.231 fail t:1000
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] get ip:173.194.71.90 t:889
Apr 24 10:48:01 - [DEBUG] get ip:86.127.118.172 t:891
Apr 24 10:48:01 - [DEBUG] tcp conn 216.58.211.193 fail t:1000
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] tcp conn 123.205.251.114 fail t:1000
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] get ip:216.58.210.113 t:891
Apr 24 10:48:01 - [DEBUG] create_ssl 194.78.99.244 fail:timed out c:0 h:0
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] tcp conn 74.125.229.27 fail t:1000
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] get ip:210.139.253.25 t:891
Apr 24 10:48:01 - [DEBUG] tcp conn 203.165.13.210 fail t:1000
Apr 24 10:48:01 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:01 - [DEBUG] get ip:199.87.241.51 t:891
Apr 24 10:48:02 - [DEBUG] get ip:123.205.251.112 t:892
Apr 24 10:48:02 - [DEBUG] get ip:216.58.220.68 t:893
Apr 24 10:48:02 - [DEBUG] tcp conn 216.58.210.119 fail t:1000
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [DEBUG] get ip:216.58.208.15 t:893
Apr 24 10:48:02 - [DEBUG] create_ssl 173.194.204.191 fail:timed out c:0 h:0
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [DEBUG] create_ssl 64.15.116.186 fail:timed out c:0 h:0
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [INFO] FWD CONNECT www.google-analytics.com:443 
Apr 24 10:48:02 - [DEBUG] tcp conn 173.194.71.90 fail t:1000
Apr 24 10:48:02 - [DEBUG] tcp conn 86.127.118.172 fail t:1000
Apr 24 10:48:02 - [DEBUG] network is fail
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail
Apr 24 10:48:02 - [DEBUG]LOG_EXCEPT: get ip:85.182.250.236 t:893, Except:[Errno 9] Bad file descriptor
Apr 24 10:48:02 - [DEBUG] tcp conn 216.58.210.113 fail t:1000
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [DEBUG] get ip:216.58.220.70 t:894
Apr 24 10:48:02 - [DEBUG] get ip:123.205.250.102 t:894
Apr 24 10:48:02 - [DEBUG] create_ssl 216.58.213.34 fail:timed out c:0 h:0
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [DEBUG] tcp conn 210.139.253.25 fail t:1000
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [DEBUG] get ip:64.15.117.120 t:894
Apr 24 10:48:02 - [DEBUG] tcp conn 199.87.241.51 fail t:1000
Apr 24 10:48:02 - [DEBUG] report_connect_fail network fail recently
Apr 24 10:48:02 - [DEBUG] get ip:64.15.117.122 t:894
Apr 24 10:48:02 - [DEBUG] network is ok

**Comment by Cat7373** [comment]
除了日志之外 打开网页的时候有什么提示没?

**Comment by hookybaby** [comment]
网络连接错误，早上起来的时候用还好好的呢。就是突然不能用了

**Comment by cap120** [comment]
同忽然上不去了，日志时不时就会出现这几行

Apr 24 11:35:43 - [WARNING] create tcp connection fail.
Apr 24 11:35:43 - [WARNING] FWD CONNECT www.google.com.hk:443 create_connection fail

Apr 24 11:35:43 - [DEBUG]LOG_EXCEPT: report_connect_fail network fail recently, Except:[Errno 9] Bad file descriptor

**Comment by cap120** [comment]
又能用了……orz

**Comment by mtvktvcn** [comment]
GoAgent代理处理超时，请查看日志！

**Comment by digglefly** [comment]
我的也不能用了 额 无法显示

**Comment by hyrz0123** [comment]
一样是：GoAgent代理处理超时，请查看日志！

**Comment by xxnet** [comment]
新版已恢复可用
