### ISSUE TITLE
windiows7 下点击start.vbs无效，但是用start.bat可以启动

### ISSUE THREAD

**Issue by fenzh4315** [XX-net/XX-Net#2222]
如题所示，双击start.lnk或start.vbs会有一个cmd窗口闪一下，之后就没有任何反映了
使用时可以通过start.bat来翻墙，并不影响使用
但是任务栏会始终存在一个报告当前状态的cmd窗口，比较碍眼，关闭后则失去翻墙功能

系统信息
属性	值
XX-Net Version	2.8.9
Python Version	2.7.9
System Platform	x86, Windows-7-6.1.7601-SP1
OS System	Windows
OS Version	6.1.7601
OS Release	7
OS Detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

launcher.log
Mar 03 15:07:37.222 - [INFO] start XX-Net 2.8.9
Mar 03 15:07:37.222 - [DEBUG] start confirm_xxnet_exit
Mar 03 15:07:38.251 - [DEBUG] good, xxnet:8087 cleared!
Mar 03 15:07:39.265 - [DEBUG] good, xxnet:8085 clear!
Mar 03 15:07:39.266 - [DEBUG] finished confirm_xxnet_exit
Mar 03 15:07:40.137 - [INFO] module gae_proxy started
Mar 03 15:07:40.138 - [INFO] start gae_proxy time cost 839
Mar 03 15:07:40.140 - [INFO] begin to start web control
Mar 03 15:07:40.147 - [INFO] launcher web control started.
Mar 03 15:07:41.007 - [DEBUG] launcher web_control 127.0.0.1:9441 GET /config?cmd=get_config 
Mar 03 15:07:41.493 - [INFO] get uuid:38a9ada8-1bf7-460f-bde1-a5644affd583
Mar 03 15:07:43.462 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to C:\Users\Administrator\Desktop\临时工具\XX-Net-2.8.9\data\downloads\README.md, retry:0
Mar 03 15:08:14.035 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to C:\Users\Administrator\Desktop\临时工具\XX-Net-2.8.9\data\downloads\README.md URL fail:URLError(SSLError('_ssl.c:492: The handshake operation timed out',),)
Mar 03 15:08:14.038 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to C:\Users\Administrator\Desktop\临时工具\XX-Net-2.8.9\data\downloads\README.md, retry:1
Mar 03 15:08:28.475 - [DEBUG] launcher web_control 127.0.0.1:9441 GET /img/full-width.png 
Mar 03 15:09:06.106 - [DEBUG] launcher web_control 127.0.0.1:9441 GET /config?cmd=get_config 
Mar 03 15:09:06.108 - [DEBUG] launcher web_control 127.0.0.1:9440 GET /update?cmd=get_progress 
Mar 03 15:13:33.157 - [DEBUG] launcher web_control 127.0.0.1:9441 GET /config?cmd=get_config 
Mar 03 15:13:37.153 - [DEBUG] launcher web_control 127.0.0.1:9441 GET /config?cmd=set_config&show_detail=1

**Comment by xxnet** [comment]
​start.bat 启动后，点击托盘图标，窗口会消失的，一般人我不告诉他

**Comment by fenzh4315** [comment]
嗯，我还奇怪为什么有的时候这个窗口会莫名其妙消失呢
解决了，谢谢

**Comment by yeahwu** [comment]
哈哈，一般人我不告诉他
