### ISSUE TITLE
使用XX-NET 2.9.2 Enable Auto GAEProxy 导致Github Desktop无法登陆

### ISSUE THREAD

**Issue by Carter-Pro** [XX-net/XX-Net#2224]
我使用XX-NET 2.9.2版本。
当Enable Auto GAEProxy时，Github Desktop无法登陆，提示"Could not connect securely"。
当取消全局代理之后可以正常登陆。
不知道能不能完善这个问题
对网络这块不太懂，希望懂得人能能解释下原理

**Comment by linhua55** [comment]
可能是证书的问题
需要把证书安装到系统中，而不是浏览器中，可参考
https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA#windows%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5%E8%AF%81%E4%B9%A6

**Comment by Carter-Pro** [comment]
@linhua55 非常感谢！以前导入了证书但是不被信任，调整过后问题解决了。
