### ISSUE TITLE
关于Appid数量限制的问题

### ISSUE THREAD

**Issue by UltraDWS** [XX-net/XX-Net#2228]
我是以前在用goagent的时候创建了25个appid，然后最近发现新的邮箱账号只能拥有12个免费的appid，我的疑问就是，我如果删除了已经创建的25个appid，然后我再重新创建appid的时候会不会被限制为12个？谷歌应该不会坑掉我以前超出默认的13个appid吧？

**Comment by jzp820927** [comment]
对。就是这样，如果你以前创建有超过12个 APPID,现在删除的话就不能再新建了，除非删到少于12个，才能新建，所以千万别删了，不然就浪费了。

**Comment by UltraDWS** [comment]
@jzp820927 好险，还好没有手贱。。。

**Comment by piaoyun** [comment]
还好看到这个了，我删除了，立马就恢复了。吓死哥了。

**Comment by UltraDWS** [comment]
@piaoyun 所以一定要小心操作，切记手残233

**Comment by kirbyzhu** [comment]
果然只有12个了 我的几个04年的老帐号 也只能建12个就要提交申请了
