### ISSUE TITLE
新版1.10.1 速度變好慢

### ISSUE THREAD

**Issue by Exiaotian** [XX-net/XX-Net#223]
之前看Youtube都有400k左右,現在還不到100k

**Comment by hyrz0123** [comment]
我的直接打不开...

**Comment by momoca** [comment]
是呀.变慢了很多.希望能找到问题所在呀.

**Comment by yfdyh000** [comment]
是今天死了很多IP，https://code.google.com/p/goagent/issues/list 可见

**Comment by hyrz0123** [comment]
我的出现：GoAgent代理处理超时，请查看日志！   完全上不去墙外网站

**Comment by hyrz0123** [comment]
@yfdyh000 怎么解决？？

**Comment by yfdyh000** [comment]
@hyrz0123 应该是暂时没法解决。有极少量IP仍然可用，但可能慢或不稳定，而且需要自己慢慢找到。
观察吧，过段时间是否会解封。或者暂时换用其他工具。

**Comment by hyrz0123** [comment]
@yfdyh000 好吧，我自己慢慢研究下

**Comment by superjyq** [comment]
遇到这个问题了

**Comment by xxnet** [comment]
新版已恢复可用
