### ISSUE TITLE
收到一封来自Google Cloud Platform的邮件，似乎要删除帐号，该怎么办

### ISSUE THREAD

**Issue by GitDot** [XX-net/XX-Net#2230]
今天收到一份电子邮件，觉得方方的，我该怎么办
想要enable似乎是需要建立一个收费账户？
我不大懂，还请大家帮忙。

Hello,
Your Google Cloud Platform project(s): 
myapp4
myapp6
myapp5
has/have been in the billing disabled state for more than 30 days. Since a valid billing account is required for Google Compute Engine, all related Google Compute Engine resources are scheduled to be deleted in as soon as 7 days.

Please note your Google Cloud Platform project(s) will not be deleted, and other services that do not depend on Google Compute Engine resources will not be affected.

If you take no action within 7 days, you will be unable to recover any resources under Google Compute Engine in this project. If disabling billing was unintentional, please follow the online instructions a and re-enable billing for this project within 7 days to avoid the resource deletion. 

If you have any questions, please visit the Project Billing Help page or Contact Support from the links below.

**Comment by BBeWthoson** [comment]
是因为google账户没绑定信用卡吗
我也收到诶

**Comment by GitDot** [comment]
又给我来一封，说是发错了......


The email quoted below was sent to some Google Cloud Platform customers in error.

If you do not use Google Compute Engine, you can safely ignore that message. We apologize for any confusion this has caused. We received feedback from many customers who do not use the Google Compute Engine service (for example, they only use Google App Engine). Your Google App Engine apps will continue to operate normally, and you do not need to take any action at this time.

Thanks,
The Google Compute Engine Team

**Comment by jzp820927** [comment]
我去，想不到，google 也会犯这种低级错误
