### ISSUE TITLE
为什么我用chrome的代理之后无法上网了 如何完全卸载XXNET

### ISSUE THREAD

**Issue by valbrea** [XX-net/XX-Net#2233]
原本用XXnet好好的  结果前几天开机发现如果不用chrome那个插件就无法上网 必须调成兼容模式才能正常浏览 于是我就卸载了这个插件 顺便删掉了XXnet文件夹准备该用VPN玩CSGO  但是到了学校无法使用校园网了  原来我在学校用XXNET也是照样 使用的啊

**Comment by xyuanmu** [comment]
打开IE - Internet 选项 - 连接 - 局域网设置，取消 **使用自动配置脚本**以及**代理服务器**下面的选项。

**Comment by simonasd** [comment]
@valbrea 

1. “兼容模式”是什么？Chrome好像没有这个东西。
1. XX-Net无需卸载，删掉文件夹、相应的快捷方式即可。有洁癖的，从系统证书库里面删掉Goagent CA。
1. 无法上网的问题，请按楼上所说检查一下代理服务器的设置。如果代理设置指向了某个代理程序的地址，但该程序没有运行，就会出现网络无法访问等问题。

**Comment by valbrea** [comment]
好的 谢谢各位~ 问题解决了
