### ISSUE TITLE
为什么iexplore.exe不停地访问不明ip端口80？

### ISSUE THREAD

**Issue by icreata** [XX-net/XX-Net#2246]
运行xx-net后，windows的resource monitor显示iexplore.exe不停地建立到不明ip端口80的连接。把ie关了连接就消失。2.9.3和2.9.1都有这现象。不知有没有解释？

**Comment by wenliyang** [comment]
在要求给出解释前，你要这样试
关闭除 XX-Net 和 IE 外的所有联网软件
你先要确认是 XX-Net 造成的这种情况

**Comment by icreata** [comment]
我原先就是按照你说的动机和做法在纯净VM检测，而且ie从来没有上过网

**Comment by simonasd** [comment]
@icreata 可能是状态页做的代理检测吧？每秒钟一次。

**Comment by icreata** [comment]
谢谢解答
