### ISSUE TITLE
xtunnel的一个问题

### ISSUE THREAD

**Issue by vSolo** [XX-net/XX-Net#2248]
1.开启xtunnel服务

2.注册一个账号为x@xx.net，点击Deploy Server 这里面的Google Account记录了刚才申请的账号x@xx.net

3.关闭xtunnel服务，上述描述依旧。

4.重命名client.json文件，上上描述依旧。

XX-Net-2.9.2.zip   SHA1:39c937b77f076fb1cd32e67dd7f1eb302435358e

XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 392 / 320
network-status: OK
connected-link: 14 / 50
scan-ip-thread-num: 50
ip-quality: 356
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​可能是浏览器记住了帐号

**Comment by vSolo** [comment]
果然如X大所料，检查了浏览器的配置，确实是FF记住了登录信息，谢谢。
