### ISSUE TITLE
Unknown Error Occurred on Settings Page

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#2250]
![screen shot 2016-03-07 at 22 27 44](https://cloud.githubusercontent.com/assets/1730504/13572182/e23ce4a4-e4b3-11e5-8cfe-23639b3d48fc.png)

我知道删除data文件夹肯定会好, 但是这是一个Bug.
貌似是自动升级引起的?
但是我 `git reset --hard`然后pull了最新的代码还是不行.

**Comment by zjhzxhz** [comment]
http://127.0.0.1:8085/config?cmd=get_config 的返回值如下:

```
{ "check_update": "stable", "language": "( en, "zh-Hans" ) ", "popup_webui": 1, "allow_remote_connect": 0, "show_systray": 1, "auto_start": 1, "show_detail": 0, "php_enable": 0, "gae_proxy_enable": 1, "x_tunnel_enable": 1}
```

"language"这个字段显然有问题.

**Comment by xxnet** [comment]
​状态页贴下，看看操作系统版本。

源码在 launcher/simple_i18n.py 的get_os_language函数。
@Haozhe Xie
  你可以简单加print 看看问题出在哪里。
  怀疑get_os_language 判断
  if sys.platform == "darwin": 应放在前面

**Comment by zjhzxhz** [comment]
那个判断Mac的 `if` 语句的确被正确执行了.
只是返回结果是一个 str 的字符串:

```
( en, "zh-Hans" )
```

这货是个字符串啊~ 你看一下PR #2251 
这样修复可以吗?

**Comment by xxnet** [comment]
​好，先这样，以后繁体中文再改

**Comment by zjhzxhz** [comment]
嗯~
其实现在的效果是繁体中文的用户也会显示简体中文.
其实也挺好的嘛~

On Tue, Mar 8, 2016 at 4:32 PM, Michael.X <notifications@github.com> wrote:

> ​好，先这样，以后繁体中文再改
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/2250#issuecomment-193662257>.
>



-- 

谢浩哲
