### ISSUE TITLE
求助，装了其他翻墙软件是否会导致XX-Net打开失效？

### ISSUE THREAD

**Issue by uolcano** [XX-net/XX-Net#2253]
昨天把`XX-Net`关了，听朋友的用`ss`和`fs`翻墙，可以高速访问油管。
今天习惯性的打开`XX-Net`用`google`的时候才发现快捷方式打不开，连带`start.bat`和`start.vbs`都运行不了了。
`XX-Net\python27\1.0\pythonw.exe`也是运行无反应。
不懂调试`XX-Net`，只知道按教程新装的小白，求助。

以下是`start.bat`的运行提示：
![image](https://cloud.githubusercontent.com/assets/13558290/13588432/98a2fd54-e50a-11e5-90cd-5d5e2617c6fc.png)

**Comment by xxnet** [comment]
​重新下载新版覆盖吧，应该是升级不完整

**Comment by jzp820927** [comment]
fs 是啥咚咚？还从没听说过。

**Comment by jzp820927** [comment]
@uolcano fs 是啥咚咚？从没听过说?

**Comment by uolcano** [comment]
@jzp820927 FinalSpeed

**Comment by uolcano** [comment]
@xxnet :+1: 谢谢，确实用`XX-Net-2.9.2`覆盖就好了。
是我想复杂了，以为是什么文件缺失了。 :smiley:
