### ISSUE TITLE
【求助】X-Tunnel如何分享到Surge（iOS移动设备)

### ISSUE THREAD

**Issue by kittycheny** [XX-net/XX-Net#2254]
X-Tunnel采用Socks协议的代理服务，而Surge支持Socks协议的代理。
故可以尝试通过Surge共享电脑中的代理资源给移动设备使用

1.Surge可以实现PAC智能代理的功能，我采用LiteABC_ADB方案
2.Surge采用VPN方案对移动设备进行全局代理，然后自行分流是否走GAE路线
3.移动设备与PC处于同一局域网内，Socks设置为PC端IP地址，端口为1080
4.然并404，设置后依然无法上网，X-Tunnel日志中无相关记录

故请求大家协助，为啥上不了？会不会有以下问题？
X-Tunnel是否只接受127.0.0.1的本地接入？已经使用采用CCProxy进行二级代理，本机走127.0.0.1:1080代理，然后用1085转surge，依然失败了

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1

**Comment by kittycheny** [comment]
谢谢XX大~~~太感激了~
幸福来得太突然

**Comment by B44ST** [comment]
不是太懂，有详细一些的步骤吗？

**Comment by jzp820927** [comment]
哪儿不懂，请具体说明

**Comment by B44ST** [comment]
是在Surge里直接添加一个 Sock5 吗？ 填127.0.0.1 端口1080 需要再填写帐户和密码吗？是直接可以用，还是需要X-Tunnel也开着 > < 呃，是不是问太多，抱歉，感觉基本上是什么都不懂的样子。

**Comment by jzp820927** [comment]
如果是用 GAE，就是 http 代理，IP 是运行 XX 的设备的 IP，端口是：8087，如果是用 X_TUNNEL 就是 socks5 代理，IP 是运行 XX 的设备的 IP，端口是：1080

**Comment by B44ST** [comment]
多谢，已经可以用了。
自己补充下之前自己提的问题。
直接在 Surge 里添加一个 Socks5， Server 填运行 XX-Net 设备的 IP，Port 填1080。用户密码我不确定是不是必填，我是在 XX-Net/data/x_tunnel/client.json 复制的。然后按上面那个Wiki里的指示，修改 XX-Net/data/x_tunnel/client.json 加入一行："socks_host": "0.0.0.0"，重启XX-Net。

**Comment by jzp820927** [comment]
XX 没有开发认证这一块，不用管用户密码。

**Comment by dandanielwu** [comment]
@OMDMOD 手机是不是要安装SURGE才可以使用XXTUNNEL？
PC这边不能用GAE.

**Comment by xiangrikui88200** [comment]
ios设备(如ipad)按此设置后，是全局代理都socks5吗，twitter客户端可以登入吗，twitter另需设置吗？
