### ISSUE TITLE
一直能用，忽然无法使用

### ISSUE THREAD

**Issue by mcvacv** [XX-net/XX-Net#2257]
GAEProxy状态信息

状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因.
start.bat:

E:\XX-Net-2.7.3>SET PYTHONPATH=

E:\XX-Net-2.7.3>"E:\XX-Net-2.7.3\python27/1.0/python.exe" "E:\XX-Net-2.7.3\launc
her/start.py"
Mar 08 09:55:51 - [INFO] start XX-Net 2.9.2
Mar 08 09:55:51 - [DEBUG] start confirm_xxnet_exit
Mar 08 09:55:52 - [DEBUG] good, xxnet:8087 cleared!
Mar 08 09:55:53 - [DEBUG] good, xxnet:8085 clear!
Mar 08 09:55:53 - [DEBUG] finished confirm_xxnet_exit
Mar 08 09:55:53 - [ERROR] start module gae_proxy fail:'str' object is not callab
le
Traceback (most recent call last):
  File "E:\XX-Net-2.7.3\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "E:\XX-Net-2.7.3\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "E:\XX-Net-2.7.3\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "E:\XX-Net-2.7.3\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "E:\XX-Net-2.7.3\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Mar 08 09:55:53 - [INFO] start gae_proxy time cost 13
Mar 08 09:55:53 - [INFO] begin to start web control
Mar 08 09:55:53 - [INFO] launcher web control started.
Mar 08 09:55:54 - [WARNING] request module:gae_proxy start fail
Mar 08 09:55:54 - [INFO] get uuid:06fefc7a-5a72-4b29-a5dd-444a1401b673
Mar 08 09:55:54 - [WARNING] request module:gae_proxy start fail
Mar 08 09:55:55 - [WARNING] request module:gae_proxy start fail
Mar 08 09:55:55 - [WARNING] check_update fail:URLError(error(10061, ''),)
Mar 08 09:55:55 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to E:\XX-Net-2.7.3\data\downloads\README.md, retry:0
Mar 08 09:55:56 - [WARNING] request module:gae_proxy start fail
Mar 08 09:55:57 - [WARNING] request module:gae_proxy start fail
Mar 08 09:55:58 - [WARNING] request module:gae_proxy start fail
Mar 08 09:55:59 - [WARNING] request module:gae_proxy start fail
Mar 08 09:56:00 - [WARNING] request module:gae_proxy start fail
Mar 08 09:56:05 - [WARNING] request module:gae_proxy start fail
Mar 08 09:56:06 - [WARNING] request module:gae_proxy start fail

任务管理器关python进程也没用
win7旗舰版 64位

直接运行gae似乎也是不行的，可能和运行fiddler2有关，但是开关fiddler以及重启系统问题依旧

**Comment by wuwuwuxxx** [comment]
我今天也是这个问题。。不是技术人员，不懂啥情况

**Comment by wuwuwuxxx** [comment]
我把版本直接换成最新的测试版就好了

**Comment by liushengyi** [comment]
更新最新版本就好了

**Comment by liushengyi** [comment]
将data文件夹copy过去

**Comment by jzp820927** [comment]
估计升级不完整，重新下载最新版试试

**Comment by mcvacv** [comment]
谢谢各位，已经好了
新下了2.9.3测试版，然后把旧文件夹的XX-Net-2.9.3\data\gae_proxy\good_ip.txt和ip_range.txt覆盖
