### ISSUE TITLE
状态页（127.0.0.1:8085）打开的同时浏览网页会造成卡顿和反应迟缓（Firefox 37.0.1）

### ISSUE THREAD

**Issue by zippo1933** [XX-net/XX-Net#226]
XX-Net版本1.10.1，Firefox版本37.0.1。
出现问题如题目所说，关掉即恢复正常。

**Comment by Cat7373** [comment]
刚刚测试了下下(Chrome43)，没有成功复现问题- -

**Comment by zippo1933** [comment]
那很有可能只是Firefox的问题。

**Comment by HUMORCE** [comment]
是查看日志的时候很卡，也是firefox

Property 	Value
Sys Platform 	win32
OS System 	Windows
OS version 	6.2.9200
OS release 	8
OS detail 	Version:10-0; Build:10041; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language 	zh_CN
architecture 	32bitWindowsPE
Browser 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by HUMORCE** [comment]
是查看日志的时候很卡，也是firefox

Property 	Value
Sys Platform 	win32
OS System 	Windows
OS version 	6.2.9200
OS release 	8
OS detail 	Version:10-0; Build:10041; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language 	zh_CN
architecture 	32bitWindowsPE
Browser 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by HUMORCE** [comment]
xx-net视乎吧x64 win10识别成x32了

**Comment by Cat7373** [comment]
你理解错了 那个位数是Python的位数
你换用x64的Python 就会显示x64

**Comment by HUMORCE** [comment]
感谢解答
