### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by realLARRY** [XX-net/XX-Net#2262]
XX-Net Status：

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
xxnet-version: 2.9.3
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 25 / 23
network-status: OK
connected-link: 1 / 22
scan-ip-thread-num: 50
ip-quality: 527
block-stat: OK
## ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
证书删除了又重新导入，SwitchyOmega也重新导入了那个bak文件。。还是不行。。求大神解决

**Comment by surlrs** [comment]
我也是这样子，刚刚2.8.9版本不能用了，我就更新了2.9.2
XX-Net Status：

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 181 / 55
network-status: OK
connected-link: 2 / 48
scan-ip-thread-num: 50
ip-quality: 594
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

浏览器显示
连接 www.google.com.hk 时发生错误。 对等端的证书有一个无效的签名。 （错误码： sec_error_bad_signature） 

然后导入证书没反应

**Comment by WangRex** [comment]
我也是发现2.82不能用了，但是2.9能用，还告诉我请检查浏览器代理设置。

**Comment by surlrs** [comment]
补充：刚刚用IE能打开，用原本设置的火狐还是  请检查浏览器代理设置。

**Comment by realLARRY** [comment]
我就是2.8.9用不了，然后更新，然后不行。。。

**Comment by surlrs** [comment]
我是现在更新了2.9.2
在火狐上部署完成了，但是状态还是  请检查浏览器代理设置。
我又用IE打开Google，可以访问。

**Comment by jzp820927** [comment]
应该是证书问题，试着把证书删了，重新生成，再导入试试

**Comment by WangRex** [comment]
我这儿是不耽误用，但是提示   请检查浏览器代理设置。

**Comment by jzp820927** [comment]
只要能正常使用就行了，那个可能是误判，不影响使用

**Comment by surlrs** [comment]
没错，我的就是证书问题，证书名字是：goagent xx-net，删除再重新导入，把勾勾全部选上。

**Comment by yeahwu** [comment]
先删除原有的证书，goagent xx-net，再删除xx客户端，重新下载一遍2.9.3版，
chrome应该是自动导入证书，然后就这样吧

**Comment by pendave** [comment]
https://github.com/XX-net/XX-Net/issues/7580 Firefox 火狐浏览器证书失效后的更新办法！GIF动图教程
