### ISSUE TITLE
浏览器代理未设置，已经添加appid，无法看视频

### ISSUE THREAD

**Issue by jinsihou19** [XX-net/XX-Net#2264]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
xxnet-version: 2.9.2
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 67 / 60
network-status: OK
connected-link: 7 / 0
scan-ip-thread-num: 50
ip-quality: 545
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
没有日志么？

**Comment by jinsihou19** [comment]
GAEProxy日志

Mar 08 18:09:07.749 - [DEBUG] network is ok, cost:444 ms
Mar 08 18:09:07.751 - [INFO] SSL use version:TLSv1
Mar 08 18:09:07.753 - [INFO] load ip range file:/Users/jinsihou/Downloads/XX-Net-2.9.2/gae_proxy/local/ip_range.txt
Mar 08 18:09:07.773 - [INFO] load google ip_list num:55, gws num:55
Mar 08 18:09:07.784 - [DEBUG] ## GAEProxy set keep_running: True
Mar 08 18:09:07.786 - [INFO] ------------------------------------------------------
Mar 08 18:09:07.786 - [INFO] Python Version : 2.7.10
Mar 08 18:09:07.787 - [INFO] OS : Release:10.11.3; Version:('', '', '') Machine:x86_64
Mar 08 18:09:07.787 - [INFO] Listen Address : 127.0.0.1:8087
Mar 08 18:09:07.787 - [INFO] GAE APPID : fqfq12138
Mar 08 18:09:07.787 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Mar 08 18:09:07.787 - [INFO] ------------------------------------------------------
Mar 08 18:09:07.810 - [INFO] GoAgent CA exist
Mar 08 18:09:09.075 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Mar 08 18:09:09.113 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=cf5efbbe-2b02-4f74-81b8-e29a364ea51f&version=2.9.2&platform=Darwin-15.3.0-x86_64-i386-64bit
Mar 08 18:09:09.116 - [DEBUG] get ip:218.253.0.246 t:118
Mar 08 18:09:09.298 - [DEBUG] create_ssl update ip:218.253.0.246 time:138
Mar 08 18:09:09.428 - [DEBUG] get ip:218.253.0.221 t:143
Mar 08 18:09:09.585 - [INFO] DIRECT t:470 s:1674 200 xxnet-update.appspot.com /update.json?uuid=cf5efbbe-2b02-4f74-81b8-e29a364ea51f&version=2.9.2&platform=Darwin-15.3.0-x86_64-i386-64bit
Mar 08 18:09:09.717 - [DEBUG] create_ssl update ip:218.253.0.221 time:248
Mar 08 18:09:09.733 - [DEBUG] get ip:218.253.0.209 t:169
Mar 08 18:09:10.041 - [DEBUG] get ip:218.253.0.207 t:169
Mar 08 18:09:10.088 - [DEBUG] get ip:218.253.0.235 t:174
Mar 08 18:09:10.172 - [DEBUG] create_ssl update ip:218.253.0.207 time:84
Mar 08 18:09:10.192 - [DEBUG] get ip:218.253.0.248 t:221
Mar 08 18:09:10.260 - [DEBUG] create_ssl update ip:218.253.0.235 time:131
Mar 08 18:09:10.293 - [DEBUG] get ip:202.248.248.233 t:346
Mar 08 18:09:10.303 - [DEBUG] get ip:212.188.49.205 t:456
Mar 08 18:09:10.400 - [DEBUG] get ip:104.237.161.47 t:457
Mar 08 18:09:10.505 - [DEBUG] get ip:190.167.241.243 t:532
Mar 08 18:09:10.596 - [DEBUG] create_ssl update ip:218.253.0.209 time:776
Mar 08 18:09:10.610 - [DEBUG] get ip:103.11.28.185 t:535
Mar 08 18:09:10.714 - [DEBUG] get ip:189.194.54.89 t:573
Mar 08 18:09:10.722 - [DEBUG] get ip:180.188.250.53 t:575
Mar 08 18:09:10.808 - [DEBUG] create_ssl update ip:218.253.0.248 time:545
Mar 08 18:09:10.963 - [DEBUG] create_ssl update ip:212.188.49.205 time:440
Mar 08 18:09:10.983 - [DEBUG] create_ssl update ip:202.248.248.233 time:464
Mar 08 18:09:11.191 - [DEBUG] create_ssl update ip:104.237.161.47 time:533
Mar 08 18:09:11.414 - [DEBUG] create_ssl update ip:190.167.241.243 time:614
Mar 08 18:09:11.573 - [DEBUG] create_ssl update ip:189.194.54.89 time:575
Mar 08 18:09:11.694 - [DEBUG] create_ssl update ip:180.188.250.53 time:648
Mar 08 18:09:15.116 - [DEBUG] create_ssl update ip:103.11.28.185 time:4270
Mar 08 18:09:26.972 - [INFO] scan_ip add ip:80.202.12.147 time:1053
Mar 08 18:09:29.453 - [INFO] scan_ip add ip:189.215.200.16 time:1288
Mar 08 18:09:39.263 - [INFO] scan_ip add ip:1.255.22.166 time:98
Mar 08 18:10:01.964 - [DEBUG] 218.253.0.246 close:host pool alive_timeout
Mar 08 18:10:01.967 - [DEBUG] ssl_closed 218.253.0.246
Mar 08 18:10:05.005 - [DEBUG] get ip:1.255.22.166 t:98
Mar 08 18:10:05.110 - [DEBUG] get ip:218.253.0.246 t:138
Mar 08 18:10:05.213 - [DEBUG] get ip:58.69.77.76 t:582
Mar 08 18:10:05.259 - [DEBUG] create_ssl update ip:1.255.22.166 time:170
Mar 08 18:10:05.319 - [DEBUG] get ip:218.253.0.232 t:585
Mar 08 18:10:05.358 - [DEBUG] create_ssl update ip:218.253.0.246 time:163
Mar 08 18:10:05.538 - [DEBUG] create_ssl update ip:218.253.0.232 time:146
Mar 08 18:10:05.872 - [DEBUG] create_ssl update ip:58.69.77.76 time:441
Mar 08 18:10:07.988 - [WARNING] 103.11.28.185 head fqfq12138 request fail:SysCallError(54, 'Connection reset by peer')
Mar 08 18:10:07.988 - [DEBUG] 103.11.28.185 close:HEAD
Mar 08 18:10:07.988 - [DEBUG] ssl_closed 103.11.28.185
Mar 08 18:10:10.429 - [DEBUG] get ip:103.11.28.98 t:587
Mar 08 18:10:10.530 - [DEBUG] get ip:189.194.54.84 t:590
Mar 08 18:10:10.633 - [DEBUG] get ip:180.188.250.18 t:602
Mar 08 18:10:10.735 - [DEBUG] get ip:213.163.23.106 t:612
Mar 08 18:10:10.841 - [DEBUG] get ip:213.163.23.91 t:626
Mar 08 18:10:10.946 - [DEBUG] get ip:185.2.108.235 t:638
Mar 08 18:10:11.049 - [DEBUG] get ip:216.58.195.184 t:648
Mar 08 18:10:11.154 - [DEBUG] get ip:185.2.108.225 t:652
Mar 08 18:10:11.255 - [DEBUG] get ip:67.218.93.155 t:681
Mar 08 18:10:11.256 - [DEBUG] create_ssl update ip:103.11.28.98 time:573
Mar 08 18:10:11.636 - [DEBUG] create_ssl update ip:180.188.250.18 time:665
Mar 08 18:10:11.787 - [DEBUG] create_ssl update ip:213.163.23.91 time:631
Mar 08 18:10:11.887 - [DEBUG] create_ssl update ip:189.194.54.84 time:1069
Mar 08 18:10:11.997 - [DEBUG] create_ssl update ip:216.58.195.184 time:631
Mar 08 18:10:12.099 - [DEBUG] create_ssl update ip:185.2.108.225 time:636
Mar 08 18:10:12.184 - [DEBUG] create_ssl update ip:67.218.93.155 time:632
Mar 08 18:10:12.238 - [DEBUG] create_ssl update ip:213.163.23.106 time:1149
Mar 08 18:10:13.610 - [DEBUG] create_ssl update ip:185.2.108.235 time:2323
Mar 08 18:10:14.933 - [INFO] start to terminate GAE_Proxy
Mar 08 18:10:14.933 - [DEBUG] ## Set keep_running: False
Mar 08 18:10:14.995 - [INFO] Exiting gae_proxy module...
Mar 08 18:10:15.002 - [DEBUG] ## GAEProxy set keep_running: False
Mar 08 18:10:15.040 - [DEBUG] ssl_closed 58.69.77.76
Mar 08 18:10:15.043 - [DEBUG] ssl_closed 180.188.250.18
Mar 08 18:10:15.046 - [DEBUG] ssl_closed 185.2.108.235
Mar 08 18:10:15.050 - [DEBUG] ssl_closed 185.2.108.225
Mar 08 18:10:15.054 - [DEBUG] ssl_closed 213.163.23.106
Mar 08 18:10:15.057 - [DEBUG] ssl_closed 1.255.22.166
Mar 08 18:10:15.060 - [DEBUG] ssl_closed 67.218.93.155
Mar 08 18:10:15.063 - [DEBUG] ssl_closed 218.253.0.232
Mar 08 18:10:15.067 - [DEBUG] ssl_closed 216.58.195.184
Mar 08 18:10:15.071 - [DEBUG] ssl_closed 189.194.54.84
Mar 08 18:10:15.074 - [DEBUG] ssl_closed 218.253.0.246
Mar 08 18:10:15.079 - [DEBUG] ssl_closed 103.11.28.98
Mar 08 18:10:15.083 - [DEBUG] ssl_closed 213.163.23.91
Mar 08 18:10:15.087 - [DEBUG] ssl_closed 218.253.0.221
Mar 08 18:10:15.090 - [DEBUG] ssl_closed 190.167.241.243
Mar 08 18:10:15.093 - [DEBUG] ssl_closed 218.253.0.235
Mar 08 18:10:15.095 - [DEBUG] ssl_closed 104.237.161.47
Mar 08 18:10:15.097 - [DEBUG] ssl_closed 218.253.0.207
Mar 08 18:10:15.099 - [DEBUG] ssl_closed 202.248.248.233
Mar 08 18:10:15.100 - [DEBUG] ssl_closed 212.188.49.205
Mar 08 18:10:15.103 - [DEBUG] ssl_closed 189.194.54.89
Mar 08 18:10:15.106 - [DEBUG] ssl_closed 180.188.250.53
Mar 08 18:10:15.109 - [DEBUG] ssl_closed 218.253.0.248
Mar 08 18:10:15.111 - [DEBUG] ssl_closed 218.253.0.209
Mar 08 18:10:15.111 - [DEBUG] ## GAEProxy set keep_running: True
Mar 08 18:10:15.112 - [INFO] ------------------------------------------------------
Mar 08 18:10:15.112 - [INFO] Python Version : 2.7.10
Mar 08 18:10:15.112 - [INFO] OS : Release:10.11.3; Version:('', '', '') Machine:x86_64
Mar 08 18:10:15.112 - [INFO] Listen Address : 127.0.0.1:8087
Mar 08 18:10:15.112 - [INFO] GAE APPID : fqfq12138
Mar 08 18:10:15.112 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Mar 08 18:10:15.112 - [INFO] ------------------------------------------------------
Mar 08 18:10:15.144 - [INFO] GoAgent CA exist
Mar 08 18:10:15.773 - [DEBUG] get ip:218.253.0.207 t:84
Mar 08 18:10:15.876 - [DEBUG] get ip:218.253.0.235 t:131
Mar 08 18:10:16.117 - [DEBUG] create_ssl update ip:218.253.0.235 time:160
Mar 08 18:10:16.192 - [DEBUG] create_ssl update ip:218.253.0.207 time:336
Mar 08 18:10:20.984 - [DEBUG] get ip:218.253.0.232 t:146
Mar 08 18:10:21.085 - [DEBUG] get ip:218.253.0.246 t:163
Mar 08 18:10:21.190 - [DEBUG] get ip:1.255.22.166 t:170
Mar 08 18:10:21.216 - [DEBUG] create_ssl update ip:218.253.0.246 time:79
Mar 08 18:10:21.294 - [DEBUG] get ip:218.253.0.221 t:248
Mar 08 18:10:21.344 - [DEBUG] create_ssl update ip:218.253.0.232 time:275
Mar 08 18:10:21.400 - [DEBUG] get ip:212.188.49.205 t:440
Mar 08 18:10:21.478 - [DEBUG] create_ssl update ip:1.255.22.166 time:193
Mar 08 18:10:21.724 - [DEBUG] create_ssl update ip:218.253.0.221 time:87
Mar 08 18:10:22.599 - [DEBUG] create_ssl update ip:212.188.49.205 time:977
Mar 08 18:10:27.303 - [INFO] scan_ip add ip:216.58.194.193 time:708
Mar 08 18:11:01.828 - [INFO] scan_ip add ip:222.251.134.77 time:410
Mar 08 18:11:27.975 - [INFO] scan_ip add ip:222.251.134.101 time:426
Mar 08 18:11:35.031 - [INFO] scan_ip add ip:79.136.239.87 time:555
Mar 08 18:12:33.994 - [INFO] scan_ip add ip:208.117.246.83 time:760
Mar 08 18:13:15.319 - [INFO] scan_ip add ip:86.51.35.206 time:1692
Mar 08 18:13:20.454 - [INFO] scan_ip add ip:49.231.60.213 time:711
Mar 08 18:13:35.857 - [INFO] scan_ip add ip:86.51.35.248 time:618
Mar 08 18:15:22.096 - [INFO] scan_ip add ip:49.98.25.155 time:1071
Mar 08 18:17:18.465 - [INFO] scan_ip add ip:103.11.28.113 time:612
Mar 08 18:17:36.715 - [INFO] scan_ip add ip:216.58.201.239 time:902
Mar 08 18:17:50.600 - [INFO] scan_ip add ip:194.44.4.91 time:469
Mar 08 18:18:48.870 - [INFO] scan_ip add ip:80.202.12.150 time:1468
Mar 08 18:19:07.820 - [INFO] PAC from:127.0.0.1:54726 GET /proxy.pac
Mar 08 18:19:15.785 - [INFO] scan_ip add ip:85.187.222.15 time:651
Mar 08 18:19:54.196 - [INFO] scan_ip add ip:222.251.134.117 time:424
Mar 08 18:20:12.549 - [INFO] scan_ip add ip:80.202.12.141 time:3755
Mar 08 18:20:15.140 - [INFO] PAC from:127.0.0.1:55353 GET /proxy.pac
Mar 08 18:20:31.259 - [INFO] scan_ip add ip:189.215.200.32 time:1089
Mar 08 18:21:13.728 - [INFO] scan_ip add ip:173.194.55.201 time:646
Mar 08 18:23:16.340 - [DEBUG] GAEProxy web_control 127.0.0.1:55013 POST /config?cmd=get_config
Mar 08 18:23:16.384 - [DEBUG] GAEProxy Web_control 127.0.0.1:57058 GET /scan_ip?cmd=get_range
Mar 08 18:23:16.385 - [INFO] load ip range file:/Users/jinsihou/Downloads/XX-Net-2.9.2/gae_proxy/local/ip_range.txt
Mar 08 18:23:19.400 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /scan_ip?cmd=get_scan_ip_log
Mar 08 18:23:22.912 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /check_ip?cmd=get_process
Mar 08 18:23:26.775 - [DEBUG] GAEProxy web_control 127.0.0.1:65315 POST /config?cmd=get_config
Mar 08 18:23:26.777 - [DEBUG] GAEProxy Web_control 127.0.0.1:55013 GET /scan_ip?cmd=get_range
Mar 08 18:23:26.777 - [INFO] load ip range file:/Users/jinsihou/Downloads/XX-Net-2.9.2/gae_proxy/local/ip_range.txt
Mar 08 18:23:28.233 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /scan_ip?cmd=get_scan_ip_log
Mar 08 18:23:31.921 - [INFO] scan_ip add ip:216.58.195.252 time:646
Mar 08 18:23:32.065 - [DEBUG] GAEProxy web_control 127.0.0.1:65315 POST /config?cmd=get_config
Mar 08 18:23:32.066 - [DEBUG] GAEProxy Web_control 127.0.0.1:55013 GET /scan_ip?cmd=get_range
Mar 08 18:23:32.066 - [INFO] load ip range file:/Users/jinsihou/Downloads/XX-Net-2.9.2/gae_proxy/local/ip_range.txt
Mar 08 18:23:46.299 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /deploy?cmd=get_log
Mar 08 18:23:51.195 - [DEBUG] GAEProxy web_control 127.0.0.1:65315 POST /config?cmd=get_config
Mar 08 18:23:53.574 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /deploy?cmd=get_log
Mar 08 18:23:53.994 - [DEBUG] GAEProxy web_control 127.0.0.1:65315 POST /config?cmd=get_config
Mar 08 18:24:40.017 - [INFO] scan_ip add ip:125.234.52.214 time:712
Mar 08 18:24:52.811 - [INFO] scan_ip add ip:92.46.70.28 time:429
Mar 08 18:25:17.476 - [INFO] scan_ip add ip:79.136.239.90 time:563
Mar 08 18:25:34.531 - [INFO] scan_ip add ip:1.255.22.211 time:70
Mar 08 18:25:50.009 - [INFO] scan_ip add ip:67.218.93.186 time:433
Mar 08 18:25:57.799 - [INFO] scan_ip add ip:80.233.168.96 time:2584
Mar 08 18:27:04.778 - [INFO] scan_ip add ip:217.119.118.111 time:1786
Mar 08 18:27:06.718 - [INFO] scan_ip add ip:103.11.28.216 time:462
Mar 08 18:28:47.782 - [INFO] scan_ip add ip:180.188.250.54 time:766
Mar 08 18:29:24.609 - [INFO] scan_ip add ip:103.11.28.150 time:563
Mar 08 18:30:22.417 - [INFO] scan_ip add ip:202.248.151.55 time:145
Mar 08 18:30:39.863 - [INFO] scan_ip add ip:217.119.118.112 time:2006
Mar 08 18:30:58.418 - [INFO] scan_ip add ip:212.20.34.179 time:3129
Mar 08 18:31:38.553 - [INFO] scan_ip add ip:64.15.120.217 time:743
Mar 08 18:32:22.407 - [INFO] scan_ip add ip:91.230.210.85 time:2360
Mar 08 18:33:29.899 - [INFO] scan_ip add ip:86.51.35.235 time:647
Mar 08 18:33:45.837 - [INFO] scan_ip add ip:203.211.8.111 time:417
Mar 08 18:34:32.061 - [INFO] scan_ip add ip:89.201.175.179 time:1227
Mar 08 18:35:40.142 - [INFO] scan_ip add ip:103.11.28.251 time:1943
Mar 08 18:36:09.542 - [INFO] scan_ip add ip:85.187.222.45 time:1150
Mar 08 18:36:31.360 - [INFO] scan_ip add ip:78.11.253.238 time:573
Mar 08 18:36:34.608 - [INFO] scan_ip add ip:90.201.124.27 time:682
Mar 08 18:36:35.663 - [INFO] scan_ip add ip:208.104.242.83 time:458
Mar 08 18:36:36.860 - [INFO] scan_ip add ip:218.253.0.215 time:85
Mar 08 18:37:23.259 - [INFO] scan_ip add ip:212.188.49.228 time:519
Mar 08 18:37:32.191 - [INFO] scan_ip add ip:219.124.146.152 time:298
Mar 08 18:39:17.519 - [INFO] scan_ip add ip:216.68.10.171 time:664
Mar 08 18:40:05.292 - [INFO] scan_ip add ip:84.15.64.237 time:1273
Mar 08 18:40:20.566 - [INFO] scan_ip add ip:62.168.125.178 time:1169
Mar 08 18:40:27.366 - [INFO] scan_ip add ip:180.188.250.41 time:781
Mar 08 18:42:13.330 - [INFO] scan_ip add ip:49.98.24.160 time:398
Mar 08 18:42:16.780 - [INFO] scan_ip add ip:219.124.146.158 time:201
Mar 08 18:43:04.210 - [INFO] scan_ip add ip:86.51.35.250 time:827
Mar 08 18:43:38.136 - [INFO] scan_ip add ip:1.255.22.146 time:114
Mar 08 18:44:21.987 - [INFO] scan_ip add ip:180.188.250.37 time:1466
Mar 08 18:44:39.311 - [INFO] scan_ip add ip:203.211.8.92 time:344
Mar 08 18:44:40.605 - [INFO] scan_ip add ip:219.124.146.173 time:105
Mar 08 18:44:47.313 - [INFO] scan_ip add ip:216.58.195.250 time:660
Mar 08 18:45:08.483 - [INFO] scan_ip add ip:218.253.0.245 time:220
Mar 08 18:45:18.897 - [INFO] scan_ip add ip:216.58.195.161 time:740
Mar 08 18:45:35.991 - [INFO] scan_ip add ip:103.11.28.145 time:527
Mar 08 18:45:55.409 - [INFO] scan_ip add ip:190.167.241.241 time:545
Mar 08 18:47:27.540 - [INFO] scan_ip add ip:58.69.77.90 time:668
Mar 08 18:48:15.710 - [INFO] scan_ip add ip:219.124.146.159 time:98
Mar 08 18:48:30.052 - [INFO] scan_ip add ip:79.136.239.89 time:556
Mar 08 18:48:40.016 - [INFO] scan_ip add ip:216.58.195.229 time:1360
Mar 08 18:50:21.760 - [INFO] scan_ip add ip:216.58.194.246 time:769
Mar 08 18:50:45.645 - [INFO] scan_ip add ip:103.11.28.244 time:555
Mar 08 18:50:53.259 - [INFO] scan_ip add ip:216.58.195.190 time:798
Mar 08 18:51:32.700 - [INFO] scan_ip add ip:216.58.194.152 time:738
Mar 08 18:51:35.825 - [INFO] scan_ip add ip:92.46.70.40 time:761
Mar 08 18:52:56.557 - [DEBUG] GAEProxy web_control 127.0.0.1:65315 POST /config?cmd=get_config
Mar 08 18:52:56.559 - [DEBUG] GAEProxy Web_control 127.0.0.1:56131 GET /scan_ip?cmd=get_range
Mar 08 18:52:56.559 - [INFO] load ip range file:/Users/jinsihou/Downloads/XX-Net-2.9.2/gae_proxy/local/ip_range.txt
Mar 08 18:52:58.180 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /scan_ip?cmd=get_scan_ip_log
Mar 08 18:53:11.683 - [DEBUG] GAEProxy web_control 127.0.0.1:65315 POST /config?cmd=get_config
Mar 08 18:53:13.436 - [DEBUG] GAEProxy Web_control 127.0.0.1:65315 GET /deploy?cmd=get_log
Mar 08 18:53:17.085 - [INFO] scan_ip add ip:219.124.146.142 time:317
Mar 08 18:53:21.123 - [INFO] scan_ip add ip:202.248.248.228 time:202

**Comment by jinsihou19** [comment]
因为我前改过hosts，所以其实不能翻墙

**Comment by jinsihou19** [comment]
访问google在日志中没有显示

**Comment by jinsihou19** [comment]
已经成功谢谢，浏览器安装了切换插件，然后全局都通了~
