### ISSUE TITLE
我的xx-net部署在路由器上，有些问题想请教

### ISSUE THREAD

**Issue by webnet918** [XX-net/XX-Net#2273]
我的xx-net部署在路由器上，按照教程配置在u盘上了，我现在想直接迁移到路由器上，应该怎么下手呢？另外，代理如何设置才能让该科学上网的科学上网，不该科学上网的直接走直连呢？

**Comment by jzp820927** [comment]
直接把整个 xxnet 文件夹 copy 到路由器上，PAC，可以智能分流，根据规则自动决定是否走代理，你可以用 pac

**Comment by kittycheny** [comment]
@webnet918 请问你用什么路由器？

**Comment by webnet918** [comment]
@kittycheny 华硕的AC88U

**Comment by webnet918** [comment]
@jzp820927 我后来又看了一下，u盘上主要安装的是Entware.NG,按照网上的资料执行mount -o bind /jffs/opt /opt后总是报错，mount: mounting /jffs/opt on /opt failed: No such file or directory，不知道什么原因

**Comment by jzp820927** [comment]
No such file or directory  提示的是 文件 目录不存在，你看看你要 mount 的目录是否已经建立？

**Comment by webnet918** [comment]
@jzp820927 已经建立了，有一个这样的现象：
1、插入U盘时执行mount -o bind /jffs/opt /opt，不报错，但是cd /opt之后，直接进入/tmp/mnt/Ext3/entware.ng#目录
2、不插U盘时就会报“mount: mounting /jffs/opt on /opt failed: No such file or directory”的错误

**Comment by jzp820927** [comment]
不接U盘，设备都不存在，应该是找不到的吧

**Comment by webnet918** [comment]
@jzp820927 经过昨天一天的折腾，我现在大体知道是怎么回事了，但是还是解决不了，原来是路由器根目录下已经创建了opt的软连接，这个链接就是我的U盘，我现在想修改opt，或者删除重建都不行，路由器的根目录不能读写，我很奇怪为什么Entware的安装程序就能创建这个目录呢？

**Comment by jzp820927** [comment]
这个也不太清楚了，不怎么玩路由器系统，不太熟悉

**Comment by webnet918** [comment]
@jzp820927 多谢！
