### ISSUE TITLE
部署私有ID失败，Error 404

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#2274]
版本：2.9.3测试版
系统：win7 家庭版

但虽然失败google，youtube什么的都能上，应该是使用的公有ID。请教这个问题如何解决？感谢！

部署失败：
Mar 09 08:21:25 - Application: ******
Mar 09 08:21:25 - Host: appengine.google.com
Mar 09 08:21:25 - Rolling back the update.
Mar 09 08:21:26 - Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
Mar 09 08:21:26 - upload fail: HTTP Error 404: Not Found

**Comment by youdengke** [comment]
同样问题，打开app engine 发现：GoAgent 服务端已经在 2016-02-01 14:18:48 升级到 3.3.1 版本, 请更新您的客户端。

**Comment by mrhop** [comment]
same question, maybe shall update to the oauth2 protocol

**Comment by GilesMai** [comment]
@mrhop How to update to the oauth2 protocol？

**Comment by kksse** [comment]
今天早上我的也是这样，但是昨天注册的APPID可以成功部署。

**Comment by DADAWOO** [comment]
电脑小白，怎么升级GoAgent 服务端

**Comment by jzp820927** [comment]
弱安全那些开启了没

**Comment by Hannibal5king** [comment]
同样问题。但是我把它当作部署成功，按照接下来的步骤去做，结果是成功的。

**Comment by AmonWalfram** [comment]
对的，按照部署成功的后续操作来进行，可以翻墙上youtube。

**Comment by kksse** [comment]
@AmonWalfram 不可能啊，部署失败，根本就无法配置APPID，只能用公用APPID，怎么上YOUTUBE。

**Comment by farshidvahid** [comment]
@kksse  部署失败，但youtube可上，速度还很快。亲测。

**Comment by DADAWOO** [comment]
确实可以用，tks，显示是失败，其实设置完可以上，很快

**Comment by farshidvahid** [comment]
今天早上部署成功了。感谢xx-net作者！
