### ISSUE TITLE
今天起启动脚本权限错了，google不能访问了

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#2278]
今天一早，可能是自动更新的结果
1.
在linux上运行发现start.sh没有x权限了

手动修改权限并运行

2.
发现google.com打不开了，google.com.hk却可以
查看配置proxy.ini发现
www.google.com = direct
....
许多网址direct了，不知道是不是这个原因

**Comment by ywg663** [comment]
是的
把direct注释了,好了!
