### ISSUE TITLE
从2.8.9自动升级到2.9.2后无法使用，自动升级功能可能有bug

### ISSUE THREAD

**Issue by funray** [XX-net/XX-Net#2291]
我是Win10_64，安徽合肥，长城宽带
从2.8.9自动升级到2.9.2时，出现如下错误：
![xx-net](https://cloud.githubusercontent.com/assets/5118705/13637785/2fdda892-e644-11e5-855f-3b999d1f0c67.png)
然后网页就无响应了，于是在桌面右下角右击退出，
双击桌面的图标后，无反应，
双击start.bat后，显示如下：
![cmd](https://cloud.githubusercontent.com/assets/5118705/13637828/5ee9db38-e644-11e5-8fe1-c02838e5df41.png)
之后手动下载最新稳定版2.9.2覆盖原来的后，恢复正常。
虽然正常了，但**不知道下次自动升级是否还会出现此情况**。

**Comment by linhua55** [comment]
已经确定有bug，不要使用自动升级功能

**Comment by jzp820927** [comment]
现在的自动升级问题多多，估计要等到 模块化后，才能彻底解决升级问题。

**Comment by caofengzi** [comment]
每次還是手動下載最新版本升級穩定。

**Comment by GoldenDewitt** [comment]
是的，我的也是。单独下2.9.2就好了

**Comment by caofengzi** [comment]
单独下载最新不版本，然后用自己已经部署成功的appid替换proxy.ini里面的公共appid就行了。

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.32&pv=4.4.4&source=email_footer_2] On 周四, 3月 10, 2016 at 10:15 上午, GoldenDewitt < notifications@github.com [notifications@github.com] > wrote:
是的，我的也是。单独下2.9.2就好了

—
Reply to this email directly or view it on GitHub
[https://github.com/XX-net/XX-Net/issues/2291#issuecomment-194621465] .[https://github.com/notifications/beacon/ANBJTBNdZkVq5OMp-995hiQ9ISHkPgnnks5pr37fgaJpZM4HsxJO.gif]
