### ISSUE TITLE
win 10双击start快捷方式无效

### ISSUE THREAD

**Issue by Farb** [XX-net/XX-Net#2297]
以前双击start快捷方式会打开浏览器启动服务的，但是现在双击之后弹出控制台窗口，并且一闪而过，浏览器没有打开，而且没有启动服务，请问怎么回事？

![image](https://cloud.githubusercontent.com/assets/7587900/13657200/46dd01aa-e6a8-11e5-9907-ce3b0070e1f8.png)

**Comment by jzp820927** [comment]
试试 start.bat 或者 start.vbs

**Comment by Farb** [comment]
@jzp820927 点击start.bat出现下面这样

![image](https://cloud.githubusercontent.com/assets/7587900/13657299/1b60ad78-e6a9-11e5-9cc5-3950d92c2a74.png)

点击start.vbs没有反应

**Comment by jzp820927** [comment]
会不会是程序又被自动升级给破坏了，要不你重新下载个最新版试试

**Comment by lovedelphi** [comment]
我的也这样了,重新下载个新的就可以了.

**Comment by Farb** [comment]
@jzp820927 @lovedelphi 好的 谢谢啦
