### ISSUE TITLE
建议修改 start.sh 里添加 python2

### ISSUE THREAD

**Issue by litel** [XX-net/XX-Net#23]
建议修改为 python2 launcher/start.py

原因：
linux下， python 3 和 python 2同时装了的时候，会默认 python3 打开了 start.py

然后报错：
  File "launcher/start.py", line 20
    except yaml.YAMLError, exc:
                         ^
SyntaxError: invalid syntax

**Comment by xxnet** [comment]
好的，下次把python2指定放入启动脚本。

发布包中的python27是win32版本，不是linux版本。
linux下的库已经包含进去了，在python/$version/lib/linux 下

**Comment by xxnet** [comment]
加上了，请测试

**Comment by litel** [comment]
好了，linux 基本可以开箱即用。
另外，我现在用的开机自启动是这样做的

➜  ~  cat .config/autostart/xx-net.desktop 
[Desktop Entry]
Name=xx-net
Exec=gnome-terminal -x /home/kokutou/Desktop/xx-net-1.0.9.sh
Type=Application
➜  ~  cat ~/Desktop/xx-net-1.0.9.sh 
#!/bin/bash
cd ~/app/XX-Net-1.0.9
gnome-terminal -x ./start.sh
➜  ~  

如果没有一个额外的 cd 切换目录的话，gnome-terminal 就会提示找不到 launcher/start.py 文件。

start.sh 能处理下目录的问题么。

**Comment by litel** [comment]
osx 下面添加开机启动项是弄了个 .command 文件，就能塞到设置 用户和组 登录项 里面了

$ cat ./XX-Net-1.0.9/start.command 
#!/bin/bash
cd ~/app/XX-Net-1.0.9

if hash python2 2>/dev/null; then
    python2 launcher/start.py
else
    python launcher/start.py
fi


一样要个 cd 切换到相应目录才行。

建议处理下目录并放一个 .command 文件。

**Comment by xxnet** [comment]
赞一个，start.sh 切换到脚本所在目录，应该有这个技巧，上网搜一下加上就好

**Comment by litel** [comment]
➜  ~  cat .config/autostart/xx-net.desktop 
[Desktop Entry]
Name=xx-net
Exec=nohup /home/kokutou/app/XX-Net-1.0.9/start.sh
Type=Application

➜  ~  cat app/XX-Net-1.0.9/start.sh 
#!/bin/bash
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if hash python2 2>/dev/null; then
    python2 launcher/start.py
else
    python launcher/start.py
fi

搜到了，就这一句  cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) 就行了~

**Comment by xxnet** [comment]
Cool !
下个版本加上.

**Comment by xxnet** [comment]
1.1.0 已经加上，哦耶
