### ISSUE TITLE
WinXP + XX 2.9.2 + Chrome + SwitchyOmega，失败

### ISSUE THREAD

**Issue by Krabapple** [XX-net/XX-Net#2313]
如题，WinXP系统使用2.9.2，畅游互联网失败。
 
当时想在chrome导入别人配好的SwitchyOmega配置，也就是导入bak文件，<a href="https://gochrome.info/switchyomega-config">教程在此</a>，但是chrome弹出对话框，说这个bak文件格式错误，无法导入。
 
昨天晚上用360浏览器安装了SwitchyOmega，导入bak成功，短暂畅游过一段时间，后来又失败。
（PS：在360浏览器搞这个是不是有风险？）
 
状态页内容如下，求帮助，谢谢！

XX-Net Status：

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 1
gws-ip-num: 12549 / 5282
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 0
ip-quality: 300
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by yeahwu** [comment]
xp要打tcp-z补丁，然后xx自带bak文件，在switchyomega文件夹里。
xp补丁：https://github.com/yeahwu/wu/raw/master/WindowsXP-TCPIP-concurrency-count-patch.rar
chrome教程：https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Chrome%E6%B5%8F%E8%A7%88%E5%99%A8

**Comment by Krabapple** [comment]
谢谢YW人人，我明天试一下去。
