### ISSUE TITLE
启动xx-net后，无法访问http://127.0.0.1:8085

### ISSUE THREAD

**Issue by kairi1227** [XX-net/XX-Net#2315]
系统：windows 10
xx-net版本：XX-Net-master；2.9.2；2.8.9（这几个版本都试过了）
launch文件中的日志如下：
Mar 11 11:36:13.929 - [INFO] start XX-Net get_version_fail
Mar 11 11:36:13.929 - [DEBUG] start confirm_xxnet_exit
Mar 11 11:36:13.932 - [DEBUG] good, xxnet:8087 cleared!
Mar 11 11:36:13.933 - [DEBUG] good, xxnet:8085 clear!
Mar 11 11:36:13.933 - [DEBUG] finished confirm_xxnet_exit
Mar 11 11:36:14.400 - [INFO] module gae_proxy started
Mar 11 11:36:14.400 - [INFO] start gae_proxy time cost 462
Mar 11 11:36:14.546 - [INFO] module x_tunnel started
Mar 11 11:36:14.546 - [INFO] start x_tunnel time cost 145
Mar 11 11:36:14.546 - [INFO] begin to start web control
Mar 11 11:36:14.547 - [INFO] launcher web control started.
Mar 11 11:36:16.443 - [INFO] get uuid:1b7569c3-a614-422a-a8a4-afa8c8388898
Mar 11 11:36:16.445 - [WARNING] check_update fail:URLError(gaierror(10022, 'getaddrinfo failed'),)
Mar 11 11:36:16.445 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-master\data\downloads\README.md, retry:0
Mar 11 11:36:16.482 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-master\data\downloads\README.md URL fail:URLError(gaierror(10022, 'getaddrinfo failed'),)
Mar 11 11:36:16.482 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-master\data\downloads\README.md, retry:1
Mar 11 11:36:16.485 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-master\data\downloads\README.md URL fail:URLError(gaierror(10022, 'getaddrinfo failed'),)
Mar 11 11:36:16.486 - [WARNING] check update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)

x-tunnel的日志如下：
Mar 11 11:36:14.446 - [INFO] use config_path:D:\XX-Net-master\data\x_tunnel\client.json
Mar 11 11:36:14.446 - [INFO] Use proxy:127.0.0.1:8087
Mar 11 11:36:14.446 - [DEBUG] x-tunnel no account
Mar 11 11:36:14.447 - [WARNING] x-tunnel session not start
Mar 11 11:36:14.449 - [INFO] Socks5 server listen:127.0.0.1:1080.
Mar 11 12:26:11.168 - [INFO] Close Socks5 server 
Mar 11 12:26:11.168 - [INFO] Stopping session

说明：
提示导入证书成功。
日志中提到的地址也能正常访问。https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md

chrome浏览器console信息：
`Failed to load resource: net::ERR_CONNECTION_RESET`

**Comment by jzp820927** [comment]
不会是自动升级弄得吧，你重新下载覆盖试试

**Comment by kairi1227** [comment]
@jzp820927 下载的是最新版本的。放弃升级前的版本了。

**Comment by jzp820927** [comment]
看不到什么明显的错误信息，等XX老大看看吧

**Comment by xxnet** [comment]
日志中没有看到gae_proxy的日志，没有看出其他异常

**Comment by kairi1227** [comment]
@xxnet 没有找到gae_proxy的日志，从哪里找，你说下，我找后贴出来。
上面的第一段日志是：%XX-Net-2.9.4%/data/launcher 文件夹下的launcher.log的内容。

**Comment by xxnet** [comment]
没有看到GAE_proxy 模块的输出信息

**Comment by kairi1227** [comment]
在data文件夹下有gae_proxy文件夹。只有一个证书和ip的信息：

Mar 11 15:48:00 - [INFO] Add 89.47.210.117 time:771 CN:google.com 
Mar 11 15:52:45 - [INFO] Add 216.58.199.31 time:183 CN:*.google.com 

如下图
![qq 20160314133446](https://cloud.githubusercontent.com/assets/4525647/13735866/9d7b2372-e9e9-11e5-9ded-500b7e2bf220.png)

在gae_proxy模块目录下没有找到相关的日志文件。
如下图：
![qq 20160314133808_1](https://cloud.githubusercontent.com/assets/4525647/13735897/fdfa967e-e9e9-11e5-8183-5c2005a246b4.png)

**Comment by jzp820927** [comment]
日志中 web 配置页，， http://127.0.0.1:8085

**Comment by kairi1227** [comment]
@jzp820927 没懂你的意思，能详细说一下嘛。

**Comment by jzp820927** [comment]
你目前是什么问题啊？

**Comment by kairi1227** [comment]
非常感谢@xxnet @jzp820927 
早上意外的解决的了问题。
出现的问题是：启动xxnet后，无法打开配置页面，当然就无法使用代理服务了。
如下图：
![qq 20160315095120](https://cloud.githubusercontent.com/assets/4525647/13765413/2dbbcd1a-ea94-11e5-8c49-b01d068aec59.png)

意外解决的办法是：
单击这个页面上的【详细信息】，如下图：
![qq 20160315094956](https://cloud.githubusercontent.com/assets/4525647/13765431/523d8962-ea94-11e5-9c13-91927f0079ba.png)

然后在这个页面中的最下面单击【 诊断错误...】，稍等一会儿就会出现如下图的提示：
![qq 20160315094607](https://cloud.githubusercontent.com/assets/4525647/13765444/7ce43a76-ea94-11e5-9309-99773ad6f668.png)
这个时候，http://127.0.01:8085页面就可以正常打开了。如下图：
![qq 20160315095925](https://cloud.githubusercontent.com/assets/4525647/13765461/9d0f9228-ea94-11e5-9244-631689e06120.png)
接下就可以按照xx-net的教程配置其他内容。
