### ISSUE TITLE
新版本XX-Net1.10.1，翻墙的网站都进不去了吗

### ISSUE THREAD

**Issue by 237505696** [XX-net/XX-Net#232]
如题，google之类的网站全部都进不去了，有能进谷歌网站的朋友吗？

Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36
XX-Net Version	1.10.1
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087

Apr 25 01:20:04 - Traceback (most recent call last):
Apr 25 01:20:04 - File "D:\360\XX-Net\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 218, in 
Apr 25 01:20:04 - Apr 25 01:20:04 - main()
Apr 25 01:20:04 - File "D:\360\XX-Net\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 215, in main
Apr 25 01:20:04 - Apr 25 01:20:04 - uploads(appids, email, password)
Apr 25 01:20:04 - File "D:\360\XX-Net\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 170, in uploads
Apr 25 01:20:04 - Apr 25 01:20:04 - if upload(appid, email, password):
Apr 25 01:20:04 - File "D:\360\XX-Net\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 125, in upload
Apr 25 01:20:04 - Apr 25 01:20:04 - my_stdout.write("Retry max time, failed.\n\n" % (i + 1))
Apr 25 01:20:04 - TypeErrorApr 25 01:20:04 - : Apr 25 01:20:04 - not all arguments converted during string formatting

**Comment by cdmask** [comment]
好用的很啊

**Comment by zjhzxhz** [comment]
好像是和网络环境有关系.
杭州电信基本很流畅, 但是我在上海出差偶尔就不太好用. 但也是可以用的.
