### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by kexul** [XX-net/XX-Net#2325]
3月 12 10:05:49.3 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
 3月 12 10:05:49.3 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/kkk/xx/launcher/update.py", line 244, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[0][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'

environment:
XX-Net 2.9.3
ubuntu 15.10

**Comment by xxnet** [comment]
​已知问题，是为了避免升级处理的，不影响使用。
