### ISSUE TITLE
为什么会有baidu的ip?

### ISSUE THREAD

**Issue by wialny** [XX-net/XX-Net#2330]
无意中发现的, 以为发现了好ip
再一想22延迟这不是国内才可能的吗?
一查结果是百度的ip, 而且还是80端口

![Image of Yaktocat](http://i.imgur.com/KdJdLFn.jpg)

我自己是没有动过ip列表的, 都是自动扫的.
请问这是XX-Net的问题, 还是我自己的问题呢?

**Comment by yeahwu** [comment]
百度好哇，可以叫外卖，可以买药，啥的

**Comment by jap33** [comment]
怎样扫道那么快的？

**Comment by jap33** [comment]
216.68.10.168 *.googlevideo.com gws 1003 0
36.37.218.15 *.googlevideo.com gws 1018 0
103.233.37.245 *.googlevideo.com gws 1026 0
61.91.161.160 *.googlevideo.com gws 1043 0
103.11.28.186 *.googlevideo.com gws 1072 0
36.37.218.59 google.com gws 1075 0
我们好慢。

**Comment by streamgo** [comment]
你是用什么手段检查出来的呀？再多发现一些这样的好IP呀。

**Comment by wjk199511140034** [comment]
同楼上

**Comment by jzp820927** [comment]
全都全局代理吧

**Comment by yfdyh000** [comment]
#2422 有解释。

**Comment by wialny** [comment]
@yfdyh000 多谢解答, 原来如此. 
是程序自己的行为就好, 我之前是怕中了baidu全家桶的毒.
