### ISSUE TITLE
cannot start xx-net-2.4.0(WIN10)

### ISSUE THREAD

**Issue by jhhuang96** [XX-net/XX-Net#2334]
Here is my problem.
![Uploading 123.png…]()

**Comment by jjandxa** [comment]
更新一下到最新版吧

**Comment by jzp820927** [comment]
你这个都好老的版本了，现在都 2.9.4 了，更新下吧

**Comment by HJH12315** [comment]
怎么更新？下载完覆盖就行？以前的appid是不是还要重新部署，证书要不要重新导入？ 谢谢

**Comment by jzp820927** [comment]
测试版(Test)： https://codeload.github.com/XX-net/XX-Net/zip/2.9.4

稳定版(Stable)： https://codeload.github.com/XX-net/XX-Net/zip/2.9.2

下载这个最新版

**Comment by HJH12315** [comment]
我用这个最新版  设置页面说我(火狐)浏览器没有代理设置，好坑！ 我用2.4.0就可以。

**Comment by jjandxa** [comment]
你需要重新导入新版本的证书！
