### ISSUE TITLE
不能访问谷歌搜索了。不过奇怪的是油管脸书都没问题。

### ISSUE THREAD

**Issue by cz726894926** [XX-net/XX-Net#2343]
XX-Net Status：

sys-platform: x86, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 2996 / 251
network-status: OK
connected-link: 11 / 50
scan-ip-thread-num: 50
ip-quality: 391
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by linhua55** [comment]
请使用测试版，在2.9.3版本中已修复firefox不能访问 google.com 的问题

**Comment by GreatBigWhiteWorld** [comment]
。。。正要同问呢，

如果2。9。3是修复的话，麻烦把他标为稳定版吧，2。9。2显然不是稳定版。

**Comment by jzp820927** [comment]
一般新出的版本，都要放一段时间，issues 没有人反应这个版本有问题，才会升为 稳定版

**Comment by GreatBigWhiteWorld** [comment]
呵呵，那2。9。2这么大问题。。。怎么竟然成稳定办了。。

我发现升级到292的没事，如果是全新下载的就有无法访问谷歌的问题，但是访问谷歌其他国家版本是可以的。

**Comment by CHN008** [comment]
我以前遇到这这种问题,你先访问一次:[https://www.google.com/ncr](https://www.google.com/ncr)

再打开https://www.google.com/ 应该就可以了.
