### ISSUE TITLE
You may want to turn on IP scaner

### ISSUE THREAD

**Issue by piaoyun** [XX-net/XX-Net#2344]
You may want to turn on IP scaner
这个是什么意思，今晚换了2.9.2的版本，之前的版本都扫描1个月左右，一个可用IP都没有，大家最近的可用IP怎么样呢

**Comment by jzp820927** [comment]
你是不是把扫描线程调到 0 了?

**Comment by piaoyun** [comment]
已经解决了，重新部署了一下服务端就好了
