### ISSUE TITLE
Firefox45.0集成XX-Net_2.9.4, 懒人翻墙包。已开启X_Tunnel模块，需要用X_Tunnel请在autoproxy插件上切换至“X_Tunnel”

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2354]
当然，你得先注册，登录。然后切换到“X_Tunnel”，如图，需要流量的留下注册邮箱，每人2g。默认的是gae模式。
https://github.com/yeahwu/firefox-xx

![20160314164909](https://cloud.githubusercontent.com/assets/13328328/13739330/87257656-ea05-11e5-9362-483b285bd971.png)

**Comment by jzp820927** [comment]
牛X

**Comment by user666666** [comment]
送我2G吧，谢谢。

**Comment by yeahwu** [comment]
@user666666 已转

**Comment by Krabapple** [comment]
支持IPv6吗？

**Comment by moxiea** [comment]
原来这里有流量啊，来一发    ad@anoob.cn

**Comment by yeahwu** [comment]
@moxiea 已转

**Comment by 935352** [comment]
求流量谢谢啊

**Comment by yeahwu** [comment]
你得先到web界面注册，登录。然后留下你的注册邮箱

**Comment by hwbasd** [comment]
试用下，谢楼主啦。。。
hwbasd@21cn.com

**Comment by yeahwu** [comment]
@hwbasd 已转

**Comment by leedx1** [comment]
nidhogger87@gmail.com,谢谢

**Comment by yeahwu** [comment]
@leedx1 已转

**Comment by x45993622** [comment]
x45993622@gmail.com 谢谢
