### ISSUE TITLE
PHP无法使用

### ISSUE THREAD

**Issue by HappysurfBlocking** [XX-net/XX-Net#2357]
PHP无法使用：
Exception happened during processing of request from ('127.0.0.1', 23102)
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 619, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxy.py", line 764, in __init__
    SimpleProxyHandler.__init__(self, *args, **kwargs)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 1295, in handle_one_request
    return BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 1326, in do_METHOD
    return plugin.handle(self, **action[1])
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 726, in handle
    self.do_ssl_handshake(handler)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 713, in do_ssl_handshake
    ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\win32\gevent\ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\win32\gevent\ssl.py", line 89, in __init__
    self._sslobj = _ssl.sslwrap(self._sock, server_side,
AttributeError: 'module' object has no attribute 'sslwrap'

并且，会看到这个：
Mar 14 20:44:43.684 - [ERROR] handler:UnicodeDecodeError('utf8', '<div id="log-container" class="row-fluid">\n    <div id="log" class="span12"></div> \n</div> \n\n\n<script type="text/javascript">\n    title(\'PHP\xe4\xbb\xa3\xe7\x90\x86\xe6\x97\xa5\xe5\xbf\');\n</script>\n<script type="text/javascript">\n    $(function() {\n        resizeLogWindow();\n    });\n\n    $(window).resize(function() {\n        resizeLogWindow();\n    });\n</script>\n<script type="text/javascript">\n    function resizeLogWindow() {\n        var windowHeight    = $(window).height(),\n            preservedHeight = 220;\n\n        $(\'#log\').css(\'height\', windowHeight - preservedHeight);\n    }\n</script>\n<script type="text/javascript">\n    $(function() {\n        window.previousOffset  = 0;\n        window.offset          = 1;\n        window.isAutoScrollLog = true;\n\n        var timer = $.timer(function() {\n            getLog();\n        });\n        timer.set({\n            time: 2500,\n            autostart: true\n        });\n    });\n</script>\n<script type="text/javascript">\n    $(function() {\n        getLog();\n    });\n</script>\n<script type="text/javascript">\n    $(\'#log\').scroll(function() {\n        var preservedHeight = $(\'#log\').height() + 10,\n            scrollHeight    = $(\'#log\')[0].scrollHeight,\n            scrollTop       = $(\'#log\').scrollTop();\n\n        if ( scrollTop + preservedHeight == scrollHeight ) {\n            window.isAutoScrollLog = true;\n        } else {\n            window.isAutoScrollLog = false;\n        }\n    });\n</script>\n<script type="text/javascript">\n    function scrollLog() {\n        if ( window.isAutoScrollLog ) {\n            $(\'#log\').scrollTop($(\'#log\')[0].scrollHeight);\n        }\n    }\n</script>\n<script type="text/javascript">\n    function getLog() {\n        var pageRequests = {\n            \'cmd\': \'get_new\',\n            \'last_no\': offset\n        };\n\n        $.ajax({\n            type: \'GET\',\n            url: \'http://127.0.0.1:8083/log\',\n            data: pageRequests,\n            dataType: \'JSON\',\n            success: function(result) {\n                $.each(result, function(lineNumber, log) {\n                    window.offset = lineNumber;\n\n                    var logTemplate = \'<p style="color: %s;">%s</p>\';\n                    if ( window.previousOffset != window.offset ) {\n                        $(\'#log\').append(logTemplate.format(getLogColor(getLogLevel(log)), log.replace(/\\n/g, \'<br>\')));\n                        scrollLog();\n                    }\n                });\n                window.previousOffset = window.offset;\n            }\n        });\n    }\n</script>\n<script type="text/javascript">\n    function getLogLevel(log) {\n        if ( log.indexOf(\'[DEBUG]\') != -1 ) {\n            return \'DEBUG\';\n        } else if ( log.indexOf(\'[INFO]\') != -1 ) {\n            return \'INFO\';\n        } else if ( log.indexOf(\'[WARNING]\') != -1 ) {\n            return \'WARNING\';\n        } else if ( log.indexOf(\'[ERROR]\') != -1 ) {\n            return \'ERROR\';\n        } else if ( log.indexOf(\'[CRITICAL]\') != -1 ) {\n            return \'CRITICAL\';\n        }\n        return \'DUMMY\';\n    }\n</script>\n<script type="text/javascript">\n    function getLogColor(logLevel) {\n        var colors = {\n            \'DUMMY\': \'#000\',\n            \'DEBUG\': \'#21610b\',\n            \'INFO\': \'#000\',\n            \'WARNING\': \'#ff8000\',\n            \'ERROR\': \'#fe2e2e\',\n            \'CRITICAL\': \'#d7df01\'\n        };\n\n        return colors[logLevel];\n    }\n</script>', 204, 206, 'invalid continuation byte') cmd:GET path:/?module=php_proxy&menu=logging from:127.0.0.1:22161
Mar 14 20:44:43.789 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\noarch\simple_http_server.py", line 129, in handle_one_request
    self.do_GET()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\launcher\web_control.py", line 105, in do_GET
    return self.req_index_handler()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\launcher\web_control.py", line 217, in req_index_handler
    data = (index_content.decode('utf-8') % (current_version, current_version, menu_content, right_content.decode('utf-8') )).encode('utf-8')
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 204-205: invalid continuation byte

系统配置：
系统版本

属性	值
XX-Net Version	2.9.2
Python Version	2.7.11
System Platform	AMD64, Windows-10-10.0.10586
OS System	Windows
OS Version	10.0.10586
OS Release	10
OS Detail	Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36

**Comment by jzp820927** [comment]
是不是自动升级造成的，还下载最新版覆盖试试？

**Comment by HappysurfBlocking** [comment]
没用啊，我捣鼓捣鼓

**Comment by HappysurfBlocking** [comment]
不管了，php的翻墙先用着以前的GAE，因为我发现XXnet的php代理这鬼玩意居然能在几年前的GAE上面用
