### ISSUE TITLE
建议以后翻墙的方法，相关友人不要分享到百度贴吧，那里就是zf的门口。

### ISSUE THREAD

**Issue by barnettzane** [XX-net/XX-Net#236]
希望通过层层筛选机制，让分享更安全，让查找路线非线性，这样zf就不容易查封。虽然我是通过百度avast吧 关注到这里的，但是百度不是我经常去的地方，甚至不愿意去。不知道作者有什么建议？

**Comment by Cat7373** [comment]
总有人会去分享的，你在这里建议是没用的吧。。。

**Comment by barnettzane** [comment]
你说的很对，总有喜欢分享的人，但我相信环境是可以改变一切的，文化也会随着时间而改变的，就像我们今天的普通话产生不到100年一样。
一般不是作者或相关人员，谁去会分享呢？ 一般的使用者写不了教程，也不会分享的

**Comment by barnettzane** [comment]
也不是反对分享，建议更系统更智能化的分享，这种拉锯战真的很消耗人的精神，不论是作者还是用户。

**Comment by quanru** [comment]
我发现github上还是有女生的。
