### ISSUE TITLE
求助：为什么我不能部署APPID，日志无任何记录

### ISSUE THREAD

**Issue by chalern** [XX-net/XX-Net#237]
我创建了这两个APPID，连同谷歌账号输入去，点击部署后没有反应啊，，，求助！！！
![qq 20150425182058](https://cloud.githubusercontent.com/assets/12110594/7332570/b9a2f62c-eb77-11e4-808e-965dcd7aa0d8.png)

**Comment by xxnet** [comment]
请看看GoAgent的日志

在 2015年4月25日 上午6:34，chalern <notifications@github.com>写道：

**Comment by kwwgh** [comment]
跟楼主一模一样的问题，下载的是最新版的1.11.1，感觉就是ID没有上传上去。

**Comment by stonism** [comment]
我用goagent3.2.3，要把google的安全设置Access for less secure apps打开，不知道楼主的问题是不是这个原因。

**Comment by Cat7373** [comment]
感觉是进程没成功启动 直接就挂了的样子?

**Comment by kingour** [comment]
我部署也是这样

**Comment by kingour** [comment]
找到原因了，125行多了个括号，⊙﹏⊙b

**Comment by kingour** [comment]
另外这是good_ip列表隔几分钟不可用的问题，重启又可以，我在列表牵头加上十几个一直可用的ip就部署上去了

**Comment by xxnet** [comment]
恩，应该在界面上加一个导入ip的功能。

寻找ip的方法千千万万，找到好用的就是好办法。

在 2015年4月26日 上午10:38，Kingour <notifications@github.com>写道：

**Comment by Cat7373** [comment]
- -我一会写个试试看

**Comment by xxnet** [comment]
恩，可以支持这样两种格式：
1.换行分割；
2.以|分割

如果再高级一点，可以像Excel导入表格一样，让用户自己填分隔符。（看难度决定吧）

导入前给出一个解析的结果，让用户看看对不对。（有没有必要？）

入口:
方案1：GoAgent的设置-》高级，有一个链接。
方案2：在GoAgent的菜单下，新增一项工具，里面有：
    导入ip，
    导出ip（给原版GoAgent）
    设置扫描ip的ip段、并发线程数。

先写最简单的方案，最短时间工作起来，以后再慢慢改进。



2015-04-26 21:57 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
我的想法是这样的 网页上加一个下拉选择框 选择多种导入格式
能在JavaScript上做完的都在JavaScript做
剩下的工作再交给Python(好吧其实主要是我对Python不熟- - 更倾向于写JS- -)

**Comment by xxnet** [comment]
可以的，先run起来更重要。

在 2015年4月26日 下午10:19，Cat73 <notifications@github.com>写道：

**Comment by xxnet** [comment]
good job

**Comment by decemer** [comment]
我也是一样,日志没任何反应
