### ISSUE TITLE
话说最近x大，泡妞去鸟？没看见人影嘛。大家来唠唠嗑。肯定有人会说，“就知道唠嗑、唠嗑，你话痨哇？“

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2373]
虽说这是解决问题的地方，但是偶尔大家还是要常聚聚滴，联络一下感情嘛。
@xxnet @xyuanmu @simonasd @Cat7373 @jzp820927

**Comment by Sowari** [comment]
就知道唠嗑、唠嗑，你话痨哇？

**Comment by yeahwu** [comment]
终于有鸟自己的appid，内牛满面哪！2，3年鸟终于找回鸟自己呀……

**Comment by jzp820927** [comment]
我们还是不要再 X大背后说他坏话......

**Comment by yeahwu** [comment]
然而大家还是很忙滴……

**Comment by xxnet** [comment]
​大伙想我了吗？最近泡了个妹子，夜夜那什么，没空整项目了

大伙组个团吧，我把项目管理交出来
先组个委员会，推举一个轮值CEO

不要笑，我说认真的

**Comment by Cat7373** [comment]
我真的笑了。。。。。
然后才看到最后一句0.0

**Comment by bickman** [comment]
突然go agent不能用了，然后看到XX，花了一个小时，发现真好用

**Comment by yeahwu** [comment]
俺只想问，夜夜哪什么？是什么？
自由软件嘛，自由开发，自由管理，能用就行。其余的爱咱咱的，不要背负责任感。
开心开发，自由生活。
只要别忘记出来唠嗑就好鸟！

**Comment by Cat7373** [comment]
对了，X大是汉子还是妹子呀？
（天真脸~）

**Comment by xxnet** [comment]
@Cat7373 
   你贡献排第二名哦

还有 @linhua55 @simonasd @xyuanmu 都来吧

 @zjhzxhz @yfdyh000 @mikedchavez1010 都在吗？

**Comment by Cat7373** [comment]
窝已经好久好久好久好久不提交代码啦0.0

**Comment by Cat7373** [comment]
如果是汉子的话0.0
注意节制0.0
如果是妹纸的话0.0
那画面。
脑补ing。。。。。。

**Comment by yeahwu** [comment]
@Cat7373 想打歪注意鸟？

**Comment by xxnet** [comment]
先把项目拆分成多个模块
另外Android 最好先弄一个简陋的执行环境，把现有的代码跑起来，能够通过设置本地代理访问就好。
不要像fqrouter搞太完美，结果作者一放手，就没人能够维护了

**Comment by Cat7373** [comment]
现在代码注释率超级低0.0
某个方法是干嘛的得分析半天才能知道0.0

**Comment by xxnet** [comment]
Android 跨出第一步最难，先弄出一个Android 下能跑的环境，什么适配都先别想，只要能运行，什么耗电、流量都不要考虑，跑起来了，大伙能够出力就慢慢优化了

**Comment by xxnet** [comment]
代码的注释问题，可以通过review来提问、回答解决
如何？

**Comment by xxnet** [comment]
因为有很多问题，我刚接手GoAgent 也是猜半天，后来的感觉是，重点在于对http协议、SSL以及GAE的理解，等我理解了，就懒得去写注释了。

我只做到代码自己过一年还能够看懂，就没再进行整理下去，而事实上过了一年，是有些地方忘记的，还好没有完全忘记，看看就恢复记忆了。
不过还是要补充一些文档好，比如GAE 客户端和服务端之间的通讯协议，我也只好跑去看服务端的代码才明白。

**Comment by yeahwu** [comment]
唉，搬砖的表示，一脸朦逼。

**Comment by xxnet** [comment]
@yeahwu  你可以来竞选CEO，CEO就需要你这种气质

**Comment by Cat7373** [comment]
记得我提交过一个清理行尾空格的pull么- -
估计第二就是这么来的- -

**Comment by yeahwu** [comment]
@xxnet 俺只想知道，CEO能讨到媳妇吗？CEO能讨到媳妇吗？CEO能讨到媳妇吗？
重要的事说三遍。

**Comment by xxnet** [comment]
能，能，能，做CEO 能取媳妇！！！

**Comment by yeahwu** [comment]
不以讨媳妇为目的的CEO,都是耍流氓。——马克 吐温

**Comment by xxnet** [comment]
@Cat7373 
  排名不是行数，是commit数！
  大家以后一个提交也要分多几个commit

**Comment by yeahwu** [comment]
proxy_handler.py 这个文件可能要动动刀子，有人反应google网盘打不开？好像俺这边也打不开。

**Comment by Cat7373** [comment]
XX-Net似乎是我接触Github甚至Git以来的第一个项目- -
Git怎么用都不太熟- -
所以嘛，那时候都搞得比较乱- -

**Comment by xxnet** [comment]
web端还是客户端？

日志显示什么，另外开个主题吧，这里讨论换CEO，我已经找到媳妇了，就换个CEO吧

**Comment by xxnet** [comment]
@Cat7373 
   我也是第一次。。。

**Comment by yeahwu** [comment]
@Cat7373 话说妹子最近不积极呀，这样是不对滴。不要整天植物大战僵尸，偶尔也要玩点成年人玩的游戏嘛，比如给xx提交点代码。

**Comment by yeahwu** [comment]
XX-Net似乎是我接触Github甚至Git以来的第一个项目- -
@Cat7373
我也是第一次

你俩这是干嘛？玩纯情呀！
好吧，俺也是第一次

**Comment by Cat7373** [comment]
植物大战僵尸怎么了！
那只是个项目名！
去掉题库就是个速查工具！

**Comment by xxnet** [comment]
不要跑题，组个委员会吧

**Comment by yeahwu** [comment]
你还真以为俺看得懂英文？
提个建议，你那些问题呀！太小儿科鸟。现阶段天朝对于性知识的普及，那真是初级阶段。
要不，考虑一下，你的那些问题，稍微靠近生理知识……

嗯，俺是认真的。要想美好，不能避开性滴

**Comment by yeahwu** [comment]
@xxnet 说实话时间到鸟
x大的这些诉求，注定是没有答案的。
组委会，CEO，这些问题太敏感。

**Comment by heikehuan** [comment]
我艹，头一回发现还能在issues里聊天，你们真有才

**Comment by yeahwu** [comment]
主干，和分支的区别
大旗，还得你来抗，虽然，俺是明白这样很残忍。
浑浊的世界，总得有一盏明灯的。

**Comment by Cat7373** [comment]
@heikehuan 还有人用Issue写博客呢。。。

**Comment by yeahwu** [comment]
@xxnet 不要给自己那么大的压力！其实嘛，也不需要什么规划。信马由缰，走到哪，算哪！
你做得已经够多鸟。责任，英雄主义，欲望，这些都是狗屁，都没有一碗热饭暖心。
吖，说得有点多鸟。

**Comment by jzp820927** [comment]
是不是要先整个 XX-Net 管委会

**Comment by zjhzxhz** [comment]
Hello～ 我出现啦～！最近都在忙着写论文 所以写没怎么维护（不过每天都有在用哦！）
话说这个项目最不能忍的就是代码风格了！～分分钟要逼死我这种强迫症！

**Comment by yeahwu** [comment]
大家注意鸟，方滨兴楼下的现身鸟……哈哈哈

**Comment by zjhzxhz** [comment]
@yeahwu 
够了…… 不过我的确打算申请一个小号！

**Comment by xxnet** [comment]
@zjhzxhz 
代码风格，上次是不是你提的pull，太多了，看不过来。
不过确实可以整理下，我现在是遇到哪里有问题的就处理

**Comment by zjhzxhz** [comment]
@xxnet 
好像不是我吧? Pull的内容是什么?

**Comment by xxnet** [comment]
有收到过一个pull，提交了所有代码的风格修改

**Comment by heikehuan** [comment]
车上，一个小伙一路抱怨：活是我干的，受表扬的却是组长，最后成果又是经理的。 不公平！ 他旁边的老人微微一笑：小伙子，看着你的手表，仔细看，是不是先看时针，再看分针，可运转最多的秒针你看都不看一眼？你看，生活就是这样，当年轻人还盯着手表思考人生，睿智的老人已趁机偷到了他的钱包
http://music.163.com/#/m/song?id=5086081

**Comment by yeahwu** [comment]
话说x大你是怎么找到妹子的？还夜夜哪啥！
传授布道一下呗，也让俺们这些单身屌，早日脱离xvideos嘛

**Comment by xxnet** [comment]
话说xvideo挺好，妹子也挺烦人的。

**Comment by xyuanmu** [comment]
这里好热闹，话说还是之前在 Google code issue 里知道xvideos

**Comment by yeahwu** [comment]
xx要组团打怪，问你啥子意见？

**Comment by xyuanmu** [comment]
组团可以啊，那个 proxy_handler 的已经PR了

**Comment by xxnet** [comment]
看到PR，我发了个讨论

**Comment by zjhzxhz** [comment]
申请了一个小号~ 你们应该冥冥之中可以猜到哪个是我的小号。
我要从此隐退江湖了。

**Comment by xxnet** [comment]
大家都去申请个小号，哪天我也换个小号来提交pull啦

**Comment by yeahwu** [comment]
下次搞个小号叫"三个代表"

**Comment by xyuanmu** [comment]
我不会说，其实，我已经是小号。只不过这个小号用的比大号还要频繁。

**Comment by yeahwu** [comment]
上面就是俺的小号，上上面也是俺的小号，大家注意鸟。

**Comment by zjhzxhz** [comment]
@xxnet 
只要申请小号提交就好了吗？（当然提交时候的Git信息会一起更改）
还有其他要注意的吗？

你之前是不是说过用Tor？有必要用那个吗？

**Comment by yeahwu** [comment]
正规步骤是vpn全局带虚拟机，虚拟机里跑tor
xx用的是Whonix，安全性没得说，
熟悉Linux应该会很快上手。

**Comment by yeahwu** [comment]
哎呀，一不小心暴露身份了。俺怎么知道xx用的是什么呢？

**Comment by yeahwu** [comment]
用tor的话，其实很难受。必须前置，而且速度很慢。浏览器方面也要加固。
其实俺是想说，大家一直忽略鸟俺这个项目，这是俺专门为安全打造的匿名包，浏览器经过长期打磨，tor也经过12道工艺完成，尽量保证”速度与激情“的安全包。
初次用tor的可以尝试下
https://github.com/yeahwu/firefox-tor

**Comment by zjhzxhz** [comment]
哦~~ 表示一直用Chrome呢，而且你这货是Windows版的？
Linux倒是用的很熟练~ 我还是看一下“ Whonix”好了。
真心不想单独为他开一个虚拟机。

**Comment by yeahwu** [comment]
whonix官网，
https://www.whonix.org/
其实这东西也不是那么好搞的，初次接触tor的话，可以先到tor官网下载试试看。这东西其实也不是人用的东西。

**Comment by jzp820927** [comment]
匿名与速度，不可兼得啊！

**Comment by xxnet** [comment]
X_tunnel 对于天朝来说已经足够匿名了，而且速度足够日常使用。

靠谱的匿名环境，还是需要双虚拟机

**Comment by yeahwu** [comment]
对呀，怎么忘了这茬呢！其实当初的宣传重点应该突出在“匿名”两个字上。搞得现在大家都忽视鸟x-tunnel的匿名性。
汗，也包括俺！

**Comment by Cat7373** [comment]
@yeahwu 哇 评论加的图标变成彩色的啦！

**Comment by yeahwu** [comment]
建议x大，在x-tunnel的wiki上加上这货的匿名性详解，俺只知道经过几重跳，其余的不了解！

**Comment by xxnet** [comment]
​https://github.com/XX-net/XX-Net/wiki/X_Tunnel%E4%BB%8B%E7%BB%8D

匿名性

   - 两跳 第一跳是google，大部分情况下可与tor媲美
   - 通讯过程拆分、合并
   到一个目标主机的通讯，会分解成多个google ip的通讯
   多条链路通讯，会混在多个链路中
   因此难以通过对单个连接的传输指纹分析通讯的内容
   - 外在特征 没有类似Tor的通讯特征
   和普通的GoAgent上网类似

**Comment by yeahwu** [comment]
嗯，这个屌，这个屌爆鸟。

下面是个人匿名心得
首先，要注重个人信息泄露，就算你整天挂着个tor，用的是个实名，还挂个艳照，双重虚拟机加tor也是白搭

其次，pc环境，这里要说的是系统，和软件。不建议windows拿来匿名，然后国产软件最好一个都不要

必要的工具，x-tuuel或者tor，这里要时刻清楚，自己客户端发出的流量走向。

最后，就是浏览器加固鸟，除了必要的设置，还有浏览使用习惯，尽量不要同步和自动更新。

**Comment by simonasd** [comment]
天天搬砖的人，哪有时间在issue聊天啊！

搬完手头这个大工程剩下的一万块砖，估计可以轻松一段时间。

匿名这个东西，有一个很关键的思想，就是独立性。网络身份与真实身份之间、不同网络身份之间都要保持独立，不要有太多相互关联。否则千里之堤，溃于蚁穴。

操作系统环境，纯内存的live os是个不错的选择。每次启动都是新的，硬盘上也不留痕迹。

**Comment by nxtreaming** [comment]
"x 大" 是人还是鬼？这种issue开了有什么用？应该早点关闭。
