### ISSUE TITLE
我想加一个网站进pac怎么实现

### ISSUE THREAD

**Issue by pingtouge** [XX-net/XX-Net#2388]
比如百度

**Comment by jzp820927** [comment]
打开 pac 文件，按照里面网址的格式添加就行了

**Comment by pingtouge** [comment]
@jzp820927 不行的
    if (dnsDomainIs(host, ".baidu.com") || host == "baidu.com") return "PROXY GOAGENT_LISTEN";
    if (dnsDomainIs(host, ".ip138.com") || host == "ip138.com") return "PROXY GOAGENT_LISTEN";

然而我用百度搜索“ip”还是我的真实ip

**Comment by jzp820927** [comment]
那就不知道了，没改过自带的 PAC文件

**Comment by pingtouge** [comment]
@jzp820927  那你是用了其他pac么，能给个教程不

**Comment by jzp820927** [comment]
我是自己搭建了个 web server 把PAC放上面的，你也可以试试

**Comment by lts9165** [comment]
在FindProxyForURL那个函数里加规则，不要在下面加规则

**Comment by lts9165** [comment]
你改完以后可以看一下http://127.0.0.1:8086/proxy.pac 有没有生效，我怀疑你改错文件了，pac文件是在data\gae_proxy 目录下面的

**Comment by pingtouge** [comment]
​还是不行

2016-03-18 17:03 GMT+08:00 lts9165 <notifications@github.com>:

**Comment by pingtouge** [comment]
2016-03-18 17:26 GMT+08:00 张忠毅 <pingtouge@gmail.com>:

**Comment by jzp820927** [comment]
pac 文件格式看着没什么问题，不晓得是不是格式问题

**Comment by lts9165** [comment]
http://127.0.0.1:8086/proxy.pac 文件变化了吗，如果变化了，重启浏览器就可以了

**Comment by pingtouge** [comment]
解决了，谢谢，没有重启浏览器

**Comment by rocke** [comment]
@pingtouge  请问，您是如何解决的啊？我按照@lts9165  他的方法去添加，还是不行！

**Comment by pingtouge** [comment]
@rocke 试过重启没有？我就是没重启，之后重启就好了

**Comment by rocke** [comment]
@pingtouge 能不能把您的pac文件上传一个看看，我对比下我自己这边的，我重启了浏览器还是不行，重启了电脑之后也是不行！

**Comment by pingtouge** [comment]
@rocke  传不上来，你留个邮箱行不

**Comment by rocke** [comment]
@pingtouge  我的邮箱地址是 rocke@live.cn

**Comment by rocke** [comment]
@pingtouge  我还未收到您的文件，我的邮箱地址是rocke@live.cn
