### ISSUE TITLE
关于使用x-tunnel匿名，浏览器加固篇

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2396]
1：删除CNNIC证书：
    China Financial Certification
    China Internet Network
    Chuanghwa Telecom Co
    CNNIC
上面的几个流氓都可以删掉。

2：浏览器关闭RTC:
    火狐地址栏输入：about:config, 把media.peerconnection.enabled由true改为false，就可以彻底匿名了。
    谷歌浏览器：安装谷歌官方扩展  实现WebRTC网络限制器 。

尽量避免浏览器自动更新和同步。

**Comment by PS0123456** [comment]
表示你说的证书，删除后，再次点击查看证书，又自然出现了。。。

**Comment by yeahwu** [comment]
删除了就是不信任鸟，再出现也没事。

**Comment by jzp820927** [comment]
直接使用 Tor Browser 自带的浏览器不就行了

**Comment by yeahwu** [comment]
Tor Browser 自带的浏览器那个破烂货，是人用滴？
提醒一下，即使是tor自带的浏览器CNNIC证书，也要自己手动删除哦！

**Comment by PS0123456** [comment]
@yeahwu 什么叫删除了就叫不信任了，未添加到不信任里去啊，还是在证书机构里面

**Comment by xxx233** [comment]
可以到点击CNNIC证书-编辑信任，看看勾勾还在不在，就知道有没有被信任。

**Comment by tempso** [comment]
我查看了Safari，发现压根没有这几个证书。。。这算是很干净了呗
