### ISSUE TITLE
请问是否需要一些额外的Appid

### ISSUE THREAD

**Issue by DIYgod** [XX-net/XX-Net#24]
做 EasyGoAgent 的时候搜集过一些Appid，都是网友捐赠的，但是 GoAgent V3.2 之后需要重新上传，所以有些 Appid 只能 V3.2 之前的版本用，闲着也浪费了，不知道作者是否需要？

还有， SwitchySharp 早已停止更新，建议换成 SwitchyOmega

**Comment by xxnet** [comment]
谢谢！

对 SwitchySharp：
 原来的版本够用了，用着一直稳定。 SwitchyOmega没发现什么有价值的东西，先不换。
 你觉得呢？

有空开发一个更加智能的自动切换，集成到XX-Net，而不是在浏览器插件：
+ 根据DNS解析域名，如果是国内的，就直连，否则通过代理。
+ 加入PHP代理支持，某些不支持gae的网站，采用PHP
+ 某些网站可以通过类似Hosts的方式直连
+ 可以自动切换，先尝试直连，不行换Host，再不行才用代理。

**Comment by frozen2020** [comment]
有这种智能的浏览器插件嘛？
现在国内外需要手动切换

**Comment by DIYgod** [comment]
40个3.1版appid，无密码

``diydgod|diydgod1|diydgod2|diydgod3|diydgod4|diydgod5|diydgod6|diydgod7|diydgod8|diydgod9|ihacat002|ihacat003|ihacat004|ihacat005|ihacat006|ihacat007|ihacat008|ihacat009|ihacat010|zsq4115|zsq25251|zsq00112|kwmmfsa|qsefthuko00044|zscfbhn|awdrgyj741|asdrgyuuu|hfmsgae|pzmslunli|pzmslunli2|pzmslunli3|pzmslunli4|ahspagh|fantuqiang001|fantuqiang002|fantuqiang003|fantuqiang004|fantuqiang005|fantuqiang006|fantuqiang007|fantuqiang008``

SwitchySharp使用是没感觉有什么差别，只是SwitchyOmega界面更人性化（图标更好看(๑•̀ㅂ•́)و✧  (8），（据说）跟新版chrome兼容更好一些

先尝试直连，不行换Host，再不行才用代理 这样代价略大，不如根据 [GFW List](https://autoproxy.org/) ，列表内的如果有hosts规则优先hosts，没有hosts规则走代理，列表外的直连，连不上的提示用户，方便用户选择性的手动添加其到代理列表（类似红杏那种）

**Comment by xxnet** [comment]
thanks for appids
