### ISSUE TITLE
很意外的一个发现

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#241]
其实我个人一直在用1.9.1 没往后更新(因为看到后面主要是WebUI部分的更新)
刚刚发现 1.9.1打开后1分钟内可以找到20个可用IP
而1.11.1在5分钟内一个都找不到
一会我再去试试1.10.x- -
*****************
刚刚测试1.10.1也可以找到少量IP 但是已经很少了 再去试试1.9.4 先缩小下范围吧- -
多次测试均如此 1.9.1打开后10秒内就可以找到5个以上的IP 1分钟以内20个
*****************
1.9.4测试结果与1.10.1相同
初步怀疑是这个更新的问题:https://github.com/XX-net/XX-Net/commit/8bc7873be7baf9a97fe1d61ba4f030735f36dcf8
继续测试ing...
*****************
再次经过多次测试 https://github.com/XX-net/XX-Net/commit/8bc7873be7baf9a97fe1d61ba4f030735f36dcf8 跟1.10.1结果相同 找IP相当慢 1分钟只能找到一两个
*****************
再次非常意外的 https://github.com/XX-net/XX-Net/commit/18b4938cf2fe377a14995052ee38a727193c1ff2 依旧跟1.10.1结果相同
正在重新下载https://github.com/XX-net/XX-Net/commit/4b009e331f296eb33036242a1b4759e4a97e088d 进行测试
*****************
不是一般的蛋疼.............
官网下的1.9.1就算配置了自己的Appid照样找不到IP 但是自己一直用的就可以 我搞俩代码库对比下...
*****************
OK 找到了最终原因 把1.9.1里面的good_ip.txt复制到1.11.1里 立马1.11.1就找到IP了
不大明白1.11.1的IP显示的意思 30秒内到5,5 然后不变了
不过1.11.1里的IP用掉一个少一个 不会再加回去 不知道为何- - 一会就成了0,0 然后不加了...

**Comment by sagaql** [comment]
我也是同样的看法，最新版翻不过去-。-

**Comment by xxnet** [comment]
新版把找ip停了，可以修改找ip线程数看看效果。

文件： goagent/x.x.x/local/proxy.ini

[google_ip]
max_check_ip_thread_num = 0 <--改为5





2015-04-25 8:56 GMT-04:00 sagaql <notifications@github.com>:

**Comment by Cat7373** [comment]
看到你最新提交的才停掉的max_check_ip_thread_num，我测试的1.11.1是没有停掉的，还是5。。。

**Comment by sagaql** [comment]
目前根本就连不上了=。=

**Comment by lifeva** [comment]
我发现用公共的appid好一些，用自己的，很快就block了，根本没法正常使用

**Comment by Cat7373** [comment]
其实感觉目前的Block有点蛋疼 - - 一但连接失败就是300秒。。。

**Comment by superjyq** [comment]
block  这功能去掉吧，加上了以后基本不能用了

**Comment by Cat7373** [comment]
- -也算一种保护吧 GFW会屏蔽一些IP 一屏蔽就是15分钟
这样可以避免频繁的去请求，减少被屏蔽的概率。。。
虽然做的还不算好。。。

**Comment by lifeva** [comment]
发现有些早期的版本工作的好好的，貌似没有新版的问题比如1.3.6

**Comment by lifeva** [comment]
发现有些早期的版本工作的好好的，貌似没有新版的问题比如1.3.6

**Comment by lifeva** [comment]
发现有些早期的版本工作的好好的，貌似没有新版的问题比如1.3.6

**Comment by lifeva** [comment]
发现有些早期的版本工作的好好的，貌似没有新版的问题比如1.3.6

**Comment by lifeva** [comment]
发现有些早期的版本工作的好好的，貌似没有新版的问题比如1.3.6

**Comment by Cat7373** [comment]
- -表示开始用的时候就是1.8.x惹- -

**Comment by xxnet** [comment]
用1.11.2，已经停了

2015-04-25 9:49 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by xxnet** [comment]
回头对比1.3.6的ip列表，梳理一遍

2015-04-25 10:53 GMT-04:00 Net XX <xxnet.dev@gmail.com>:
