### ISSUE TITLE
xx-net怎么把桌面快捷方式调出来啊？

### ISSUE THREAD

**Issue by obnews** [XX-net/XX-Net#2416]
xx-net怎么把桌面快捷方式调出来啊？带图标的那个。

**Comment by jzp820927** [comment]
第一次运行的时候，会自动生成

**Comment by yeahwu** [comment]
删data文件，重启一下。记得备份ip

**Comment by zhxzhjz** [comment]
Windows下执行`start.vbs`即可.

**Comment by obnews** [comment]
感谢，删除了data文件夹，再运行start，问题解决。

**Comment by youdengke** [comment]
双击XX-Net\launcher目录下的create_shortcut.js
