### ISSUE TITLE
Get_Version_Fail的问题

### ISSUE THREAD

**Issue by ByeGFW** [XX-net/XX-Net#2417]
最新版本的`master`分支, 版本信息获取不到.
原因是原本在`README.md`中的版本信息被移动到了`download.md`中.
同时带来的问题包括自动更新的失效.

解决方案有2个:

1. 恢复README.md文件(因为分离download.md)文件没有意义
2. 修改源代码, 但是在解析文件之前还需要获取当前用户更新的是测试版还是稳定版.

@xxnet 请问要恢复README.md文件吗?
BTW, 谁提交的PR 0 0

**Comment by zhxzhjz** [comment]
我看到了, Commit 7e2ef7b70336962c5dfc38544c300180c29ffcc9
@xxnet 为什么要avoid auto update?

**Comment by yeahwu** [comment]
@zhxzhjz 是不是那楼下的，换小号名字风格也换一下嘛。真为你着急

**Comment by zhxzhjz** [comment]
@yeahwu 哈哈哈哈哈哈哈~~
那我想想哈~ 最不会起名字了呢!!
