### ISSUE TITLE
请问新版本当中的Block是什么意思？

### ISSUE THREAD

**Issue by Sherman-Liu** [XX-net/XX-Net#242]
今天一天之内更新了四个版本......几乎吐血......发现新版1.11.2状态页下方多了一栏，用了不到两分钟就出现了Blocked.Wait For 300 Seconds之类的字样，等到计数器数到0后，又重新Blocked 300 秒，根本就用不了，而原来1.9.4的版本还可以用，能找到20多个可连接的IP，请问这是为什么呢？

**Comment by latrikcoasler** [comment]
同问。用不了.....

**Comment by superjyq** [comment]
退回1.10.X，这个版本基本是不能用的

**Comment by Cat7373** [comment]
是一种保护机制啦- -

**Comment by Sherman-Liu** [comment]
回楼上的开发者，请问保护机制保护的是什么呢？如果用户完全不能使用的话，保护的意义何在呢？

**Comment by Cat7373** [comment]
- -我不是开发者
https://github.com/XX-net/XX-Net/issues/241#issuecomment-96217018

**Comment by superjyq** [comment]
为了保护ip不被GFW封了，让用户不断的不能翻墙

这样有点本末倒置了

索性大家都不翻墙了，ip都安全了

**Comment by xxnet** [comment]
解释一下，block几次之后，xx-net会学习到哪些ip是不能去访问的，下次再用，就会避免触发规则。
所以需要些耐心。

回头大家把 data/goagent/bad_ip.txt的内容贴出来，看看都是哪些ip是有问题的，从ip库里去掉。

2015-04-25 10:59 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by Sherman-Liu** [comment]
哦哦，这回楼上的是开发者了吧......
话说不是避免触发的问题啊，而是根本就用不了，五分钟后又五分钟，不断重复能有半个多小时了......

**Comment by Cat7373** [comment]
可以试着把之前版本的 good_ip.txt 复制过去
可以改善一些

**Comment by Cat7373** [comment]
感觉如果能在Block stat后面加个(?)的链接
到Wiki来简单讲解下就好了...

**Comment by latrikcoasler** [comment]
用不了.....

**Comment by siwday** [comment]
360还在，这些都不行吧

**Comment by cottonty** [comment]
完全没法用，无限五分钟循环

**Comment by xxnet** [comment]
恩，升级很快，昨晚还能工作，今天早上又不行了

2015-04-25 20:59 GMT-04:00 cottonty <notifications@github.com>:

**Comment by causlayer** [comment]
216.58.211.0 216.58.211.84

208.117.227.0 208.117.227.177

210.242.125.0 210.242.125.50

64.233.171.0 64.233.171.166

222.255.120.0 222.255.120.59

212.188.10.0 212.188.10.152

193.192.226.0 193.192.226.187

64.233.162.0 64.233.162.87

210.245.14.0 210.245.14.50

81.175.29.0 81.175.29.176

193.192.250.0 193.192.250.177

85.182.250.0 85.182.250.29

193.134.255.0 193.134.255.172
216.58.216.0 216.58.216.132

我的bad_ip列表，不能直接翻墙就用php_proxy。就是不会如何使用php_proxy也搞成自动切换，请高手给弄个教程，如果嫌麻烦指点一下也行啊，谢谢

**Comment by xxnet** [comment]
感谢反馈，新版1.12.0 已经发布，请测试
