### ISSUE TITLE
请问下在配置中，是将所有appid都填写上，还是没流量了在填写另一个？

### ISSUE THREAD

**Issue by Ailea** [XX-net/XX-Net#2427]
请问下在配置GAEProxy中，是将所有appid都填写上，还是没流量了在填写另一个

我刚刚查看了一下appid的剩余流量，发现几个appid的剩余流量大小好像都是一样的，我怕是走重了，想问下是不是应该一个一个的用啊。还是都写上。

**Comment by ByeGFW** [comment]
不同的ID之间使用`|`分隔, 例如:

```
APPID1|APPID2|APPID3
```

**Comment by Ailea** [comment]
@ByeGFW 好的，谢谢。

**Comment by ByeGFW** [comment]
@xxnet 
帮忙Close this issue.

**Comment by Ailea** [comment]
抱歉，我不知道要关掉，已经关了。

2016-03-21 20:45 GMT+08:00 Dr. Anonymous <notifications@github.com>:
