### ISSUE TITLE
1.11.2无法启动

### ISSUE THREAD

**Issue by sanguinaryangel** [XX-net/XX-Net#244]
开机后双击桌面图标可以启动,托盘右键退出后再次双击桌面图标.无法启动,必须要重启电脑,而且也没有办法再退回低版本.我现在就想知道,1.11.2版本对我的电脑做了什么?我该怎么卸掉?

**Comment by sanguinaryangel** [comment]
补充下,1.11.2无法启动的时候进程里会出现pythonw.exe的进程,继续双击,pythonw.exe进程会无限增多,但就是不启动XX-net

**Comment by xxnet** [comment]
卸载删除目录就好。


你试试用start.bat启动，看看出现卡在什么地方了

在 2015年4月25日 下午3:03，sanguinaryangel <notifications@github.com>写道：

**Comment by sanguinaryangel** [comment]
感谢开发者回复,下面是start.bat启动后的报错信息
D:\360Downloads\goagent\XX-Net-1.11.2>"D:\360Downloads\goagent\XX-Net-1.11.2\pyt
hon27/1.0/python.exe" "D:\360Downloads\goagent\XX-Net-1.11.2\launcher/start.py"

launcher version: 1.4.0
Apr 26 12:19:22 - [INFO] use php_proxy version:1.0.0
Apr 26 12:19:22 - [INFO] php_proxy 1.0.0 started D:\360Downloads\goagent\XX-Net-
1.11.2\php_proxy\1.0.0\start.py
Apr 26 12:19:23 - [INFO] ------------------------------------------------------
PHP proxy Version    : 3.2.3 (python/2.7.9 gevent/1.0.1 pyopenssl/0.13.1)
------------------------------------------------------

Apr 26 12:19:23 - [INFO] start php_proxy time cost 1069
Apr 26 12:19:23 - [INFO] use goagent version:3.1.49
Apr 26 12:19:23 - [INFO] goagent 3.1.49 started D:\360Downloads\goagent\XX-Net-1
.11.2\goagent\3.1.49\start.py
Apr 26 12:19:23 - [INFO] load ip range file:D:\360Downloads\goagent\XX-Net-1.11.
2\goagent\3.1.49\local\ip_range.txt
Traceback (most recent call last):
  File "D:\360Downloads\goagent\XX-Net-1.11.2\goagent\3.1.49\start.py", line 13,
 in <module>
    import local.proxy as goagent
  File "D:\360Downloads\goagent\XX-Net-1.11.2\goagent\3.1.49\local\proxy.py", li
ne 83, in <module>
    import proxy_handler
  File "D:\360Downloads\goagent\XX-Net-1.11.2\goagent\3.1.49\local\proxy_handler
.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "D:\360Downloads\goagent\XX-Net-1.11.2\goagent\3.1.49\local\connect_manag
er.py", line 40, in <module>
    from google_ip import google_ip
  File "D:\360Downloads\goagent\XX-Net-1.11.2\goagent\3.1.49\local\google_ip.py"
, line 29, in <module>
    max_check_ip_thread_num = config.CONFIG.getint("google_ip", "max_check_ip_th
read_num") #5
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\ConfigParser.py",
 line 359, in getint
    return self._get(section, int, option)
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\ConfigParser.py",
 line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '5max_good_ip_num = 3000'

**Comment by sanguinaryangel** [comment]
下面是放了一会儿以后又跳出来的
Apr 26 12:26:03 - [INFO] start goagent time cost 400381
Apr 26 12:26:03 - [DEBUG] launcher web_control 127.0.0.1:52989 "GET /
Apr 26 12:26:04 - [INFO] get uuid:913790eb-a9d1-4f9a-9b7a-4ecd14e03c50
Apr 26 12:26:05 - [ERROR] check_update except:<urlopen error [Errno 10061] >
Traceback (most recent call last):
  File "D:\360Downloads\goagent\XX-Net-1.11.2\launcher\1.4.0\update.py", line 21
6, in check_update
    update_content = opener.open(req_url).read()
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\urllib2.py", line
 404, in open
    response = self._open(req, data)
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\urllib2.py", line
 422, in _open
    '_open', req)
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\urllib2.py", line
 382, in _call_chain
    result = func(*args)
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\urllib2.py", line
 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\360Downloads\goagent\XX-Net-1.11.2\python27\1.0\lib\urllib2.py", line
 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Apr 26 12:28:02 - [DEBUG] launcher web_control 127.0.0.1:53487 "GET /
Apr 26 12:28:03 - [DEBUG] launcher web_control 127.0.0.1:53488 "GET /
Apr 26 12:28:03 - [DEBUG] launcher web_control 127.0.0.1:53493 "GET /
Apr 26 12:34:35 - [DEBUG] launcher web_control 127.0.0.1:55505 "GET /?module=goa
gent&menu=config
Apr 26 12:34:37 - [DEBUG] launcher web_control 127.0.0.1:55510 "GET /?module=goa
gent&menu=deploy
Apr 26 12:34:38 - [DEBUG] launcher web_control 127.0.0.1:55532 "GET /?module=goa
gent&menu=config
Apr 26 12:34:41 - [DEBUG] launcher web_control 127.0.0.1:55541 "GET /?module=php
_proxy&menu=config
Apr 26 12:34:41 - [DEBUG] PHP web_control 127.0.0.1:55542 POST /config?cmd=get_c
onfig

**Comment by xxnet** [comment]
5max_good_ip_num = 3000

你修改了哪个配置文件，检 查下，前面加多了一个5.
可能在:
data/goagent/manual.ini
data/goagent/config.ini
goagent/x.x.x/local/proxy.ini


2015-04-26 0:35 GMT-04:00 sanguinaryangel <notifications@github.com>:

**Comment by sanguinaryangel** [comment]
非常感谢,找到了.我改了IP检索数量为5.后面的换行符丢失了..TXT的锅.我用NOTEPAD搞定了.
