### ISSUE TITLE
请问一下为什么不能翻墙，在线坐等！

### ISSUE THREAD

**Issue by shanxijinzhong** [XX-net/XX-Net#245]
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
XX-Net Version	1.11.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	00000
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2920
connected link	0,0
ip-connect-interval	10
block stat

**Comment by shanxijinzhong** [comment]
日志页面，显示空白！

**Comment by xxnet** [comment]
打开CMD，在里面执行start.bat看看哪里出问题了

2015-04-25 15:17 GMT-04:00 shanxijinzhong <notifications@github.com>:
