### ISSUE TITLE
杀毒软件报unicodedata.pyd有毒。。。

### ISSUE THREAD

**Issue by UltraDWS** [XX-net/XX-Net#2460]
在目录X:\Program Files (x86)\XX-Net\python27\1.0\lib下的unicodedata.pyd被瑞星检测说是Malware，瑞星脑残了还是我下载压缩包的时候出问题了。。。（23日更新描述，已经证实是瑞星脑残）

**Comment by caofengzi** [comment]
@UltraDWS 你膽子挺大哦，還敢用瑞星等等國產殺毒程序呢？沒有毒，這是google在線多引擎殺毒的結果。

**Comment by UltraDWS** [comment]
@caofengzi 一般都是全部关闭状态，装国外的各种选择障碍，推荐下国外的几款呗，公认的比较不占用系统资源的，上谷歌搜老外的喜好也是各种花式推荐。。。诚恳的求推荐，诚恳的求推荐，诚恳的求推荐。。。

**Comment by simonasd** [comment]
@UltraDWS  原来瑞星还活着呢！

个人推荐大a、小a、nod32、诺顿。

**Comment by CyrusYzGTt** [comment]
我用 comodo个人防火墙， 还有小红伞
在 2016年03月23日 01:36, UltraDWS 写道:

**Comment by UltraDWS** [comment]
@CyrusYzGTt 谢谢推荐！目前小红伞两票哈哈哈，防火墙啥的我一般不用，chrome上弄个脚本安全检测插件就行了，陌生网站就用这货扫一下是人是鬼检测都还挺准，我家路由器和猫都有硬件防护隔离手段。

**Comment by UltraDWS** [comment]
@simonasd 瑞星这货现在开始各种无节操广告啦，国内大量的弱势用户又不想被大流氓360插眼，就只能选择相对不太流氓的瑞星了。。。
