### ISSUE TITLE
浏览器代理设置的问题

### ISSUE THREAD

**Issue by GitFuture** [XX-net/XX-Net#2468]
每次重启后都必须手动把证书删除再重新导入一遍，GAE才能工作，否则就是一直提示浏览器代理设置fail，即便是浏览器代理设置失败，连接池里依然有已用的连接数

**Comment by jzp820927** [comment]
浏览器代理设置检查，不一定准确，只要能用就行

**Comment by GitFuture** [comment]
只有重新导入证书之后才能上外网

**Comment by jzp820927** [comment]
上网和证书没什么关联啊，你说的 https 网站麽？

**Comment by GitFuture** [comment]
对，都是 https 网站没法进

**Comment by jzp820927** [comment]
那确实是证书问题，但是也不至于每次重启都要导入证书吧，证书只要导入一次就行了

**Comment by GitFuture** [comment]
是啊 我也不清楚什么情况

**Comment by jzp820927** [comment]
是不是你操作系统有问题了

**Comment by linhua55** [comment]
可能你的浏览器运行在安全软件/或杀毒软件提供的沙盒模式下，导致更改只对本次生效

天朝猪 <notifications@github.com>于2016年3月22日周二 下午10:30写道：

**Comment by GitFuture** [comment]
用的google chrome，电脑没装杀毒软件，只有Windows自带的防火墙，有可能只是个例

**Comment by yeahwu** [comment]
删除data文件重新生成一下证书，然后删除老证书，重新导入试试。
