### ISSUE TITLE
昨晚跑了一段之后的bad_ip.txt的内容

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#247]
所在地：山东省临沂市
运营商：联通
XX-Net版本：1.11.2
系统版本：Windows7 x64
bad_ip.txt内容：
210.242.125.0 210.242.125.50
222.255.120.0 222.255.120.57
203.117.34.0 203.117.34.172
193.120.166.0 193.120.166.110

64.233.162.0 64.233.162.86
85.182.250.0 85.182.250.178
94.40.70.0 94.40.70.48

**Comment by causlayer** [comment]
所在地：北京
运营商：歌华有线
XX-Net版本：1.11.3
系统版本：mac OS X 10.10.3

bad_ip.txt内容：
216.58.211.0 216.58.211.84
208.117.227.0 208.117.227.177
210.242.125.0 210.242.125.50
64.233.171.0 64.233.171.166
222.255.120.0 222.255.120.59
212.188.10.0 212.188.10.152
193.192.226.0 193.192.226.187
64.233.162.0 64.233.162.87
210.245.14.0 210.245.14.50
81.175.29.0 81.175.29.176
193.192.250.0 193.192.250.177
85.182.250.0 85.182.250.29
193.134.255.0 193.134.255.172
216.58.216.0 216.58.216.132

**Comment by nsonline** [comment]
吉林长春
电信
OS version	6.2.9200
XX-Net Version	1.11.3

64.233.164.0 64.233.164.191
210.242.125.0 210.242.125.45
64.233.162.0 64.233.162.86
31.7.160.0 31.7.160.237
94.40.70.0 94.40.70.48
193.92.133.0 193.92.133.54
85.182.250.0 85.182.250.178

**Comment by xxnet** [comment]
多谢

2015-04-26 21:51 GMT-04:00 nsonline <notifications@github.com>:

**Comment by tomaseery** [comment]
所在地：北京
运营商：电信通
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:6-2; Build:9200; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.11.3
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
 

badip

210.242.125.0 210.242.125.34
一直就这两个.怎么也上不去.

**Comment by xxnet** [comment]
请先试试 1.9.4

2015-04-27 3:32 GMT-04:00 tomaseery <notifications@github.com>:

**Comment by xxnet** [comment]
已经发布新版 1.12.0，谢谢各位反馈的信息。

**Comment by smaa** [comment]
区域：上海
网络：长城宽带

=============XX-net Status=============
Property	Value
Sys Platform	linux2
OS System	Linux
OS version	#108-Ubuntu SMP Thu Apr 11 15:55:01 UTC 2013
OS release	2.6.32-46-generic
OS detail	Dist:Ubuntu; Version:10.04; ID:lucid
language	en_US
architecture	32bitELF
Browser	Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.22 (KHTML, like Gecko) Ubuntu Chromium/25.0.1364.160 Chrome/25.0.1364.160 Safari/537.22
XX-Net Version	1.12.1
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.6.5

=================bad_ip2.txt ==================
64.233.162.86
64.233.162.87
64.233.162.84
64.233.162.85
64.233.162.82
64.233.162.83
64.233.162.81
4

**Comment by ILlolita** [comment]
上海
电信（？）
Sys Platform	win32
language	ja_JP
XX-Net Version	1.12.1

64.233.162.86
64.233.162.87
64.233.162.84
64.233.162.85
85.182.250.55
64.233.162.83
64.233.162.81
193.192.250.158
62.1.38.177
64.233.162.82
62.1.38.84
64.233.164.143

**Comment by nocole** [comment]
江苏电信

64.233.162.86
64.233.162.82
64.233.162.83
193.192.226.187
9
193.192.226.177
210.242.125.50

**Comment by newcastlecy** [comment]
64.233.162.87
64.233.162.85
64.233.162.82
64.233.162.83
64.233.162.81
193.192.250.158
85.182.250.55

**Comment by xxnet** [comment]
谢谢

2015-04-27 9:25 GMT-04:00 newcastlecy <notifications@github.com>:

**Comment by yu0425** [comment]
青岛联通

64.233.162.87
64.233.162.84
64.233.162.82
193.192.250.158
64.233.162.81
4
85.182.250.55

**Comment by FingerArts** [comment]
安徽电信

195.249.20.224
64.15.119.88
216.58.210.7
64.233.177.90
213.158.11.151
64.233.176.94
118.174.25.119
74.125.226.93
0
64.233.166.156
4
81.175.29.154
9
64.233.176.132
85.182.250.168
7
208.117.253.22
64.15.126.242
64.233.165.86
194.78.99.148
2
64.15.116.218
173.194.219.86
74.125.206.84
1.179.251.89

**Comment by xxnet** [comment]
多谢

2015-04-27 9:52 GMT-04:00 FingerArts <notifications@github.com>:

**Comment by ILlolita** [comment]
上海电信

216.58.211.110
64.233.176.167
210.245.14.109
74.125.69.196
64.233.161.165
1.179.248.152
1.179.248.232
64.233.184.104
64.15.126.239
64.233.179.85
74.125.198.124
64.15.113.40
64.233.166.18
64.15.116.117
64.233.167.148
216.58.220.231
64.15.126.138
64.15.126.232
216.58.217.52
64.233.191.118
216.58.209.228
197.84.128.39
173.194.219.104
81.175.29.176
111.168.255.113
5
202.39.143.40
64.15.116.22
213.158.11.215
173.194.196.152
64.233.185.86
1.179.248.49
210.245.14.119
208.117.233.21
216.58.209.118
149.3.177.86
193.90.147.57
83.94.121.242
216.58.217.184
64.233.177.103
83.94.121.222
210.139.253.29
216.58.210.244
208.117.228.51
74.125.134.142
64.233.168.155
208.117.224.205
216.58.219.237
208.117.224.164
61.19.1.49
41.201.128.39
93.123.23.18
106.162.216.35
194.78.99.158
173.194.122.3
64.233.191.124
118.143.88.35
64.233.179.105
95.54.196.237
95.54.196.230
64.233.171.191

**Comment by causlayer** [comment]
所在地：北京
运营商：歌华有线
XX-Net版本：1.12.2
系统版本：mac OS X 10.10.3

173.194.38.0 173.194.38.209
193.192.250.0 193.192.250.177
216.58.211.0 216.58.211.19
210.242.125.0 210.242.125.34
222.255.120.0 222.255.120.59
64.233.162.0 64.233.162.83
213.158.11.0 213.158.11.241
64.15.113.0 64.15.113.113
64.233.164.0 64.233.164.149
193.134.255.0 193.134.255.172
210.245.14.0 210.245.14.30

**Comment by smaa** [comment]
上海，长城宽带

=============XX-net=================
Property	Value
Sys Platform	linux2
OS System	Linux
OS version	#108-Ubuntu SMP Thu Apr 11 15:55:01 UTC 2013
OS release	2.6.32-46-generic
OS detail	Dist:Ubuntu; Version:10.04; ID:lucid
language	en_US
architecture	32bitELF
Browser	Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.22 (KHTML, like Gecko) Ubuntu Chromium/25.0.1364.160 Chrome/25.0.1364.160 Safari/537.22
XX-Net Version	1.12.1
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.6.5
Proxy Listen	127.0.0.1:8087

=============bad_ip2.txt==============
212.188.7.45 
210.242.125.34 
95.143.84.154 
2 
5 
4 
9 
193.192.226.183 
210.242.125.55 
95.143.84.148 
31.209.137.59

**Comment by Aetherus** [comment]
所在地：上海
运营商：电信

===========bad_ip2.txt===========
64.233.162.87
64.233.162.84
64.233.162.85
64.233.162.82
64.233.162.83
216.58.223.29
216.58.223.23
208.117.224.136
74.125.195.198
216.58.211.190
208.117.229.16
216.58.216.89
64.15.124.251
208.117.228.218
64.15.116.26
61.219.131.88
37.228.69.34
216.58.216.64
83.94.121.178
61.19.1.104
173.194.219.191
74.125.24.142
208.117.229.28
213.158.11.173
1.179.248.34
61.19.1.187
208.117.230.30
64.233.162.136
86.127.118.167
173.194.67.196
64.233.169.156
213.158.11.185
173.194.197.190
37.228.69.23
216.58.221.205
62.197.198.241
210.153.73.20
216.58.221.97
118.174.25.50
216.58.208.98
213.158.11.39
1.179.248.182
74.125.143.50
88.159.13.249
74.125.71.115
64.15.124.118
64.233.177.104
64.233.176.99
37.228.69.19
203.66.124.157
64.233.168.195
1.179.248.162
64.15.116.214
64.15.119.220
80.64.175.109
85.182.250.103
64.233.178.138
173.194.211.91
74.125.21.122
74.125.131.124
208.117.253.52
210.153.73.118
64.233.185.90
64.233.171.194
213.158.11.221
83.145.196.163
216.58.221.221
64.233.177.114
64.233.179.199
83.94.121.217
64.233.167.145
216.58.219.23
74.125.229.92
208.117.224.202
64.15.124.181
64.233.178.122
149.126.86.38
139.175.107.55
193.134.255.177
64.233.177.189
149.3.177.26
64.233.185.114
64.15.126.254
208.117.253.23
208.117.228.113
193.192.250.172
64.233.179.17
123.205.250.84
64.15.113.50
64.233.167.137
61.219.131.246
194.78.99.230
64.233.177.197
62.1.38.148
149.126.86.26
118.143.88.95
82.135.118.42
213.158.11.82
197.199.253.35
149.3.177.91
83.94.121.237
64.15.116.244
216.58.219.1
123.205.250.106
208.117.253.90
208.117.253.122
210.245.14.227
216.58.221.163
178.45.251.109
74.125.137.137
210.139.253.55
64.233.176.196
64.233.166.164
64.233.164.143
216.58.212.94
213.158.11.32
173.194.73.81
216.58.219.50
208.117.224.157
94.40.70.20
193.90.147.113
216.58.221.170
178.45.251.113
93.123.23.38
64.233.179.144
64.233.179.143

**Comment by xxnet** [comment]
谢谢，请用1.12.2跑看看

2015-04-28 19:35 GMT-04:00 aetherus <notifications@github.com>:

**Comment by Aetherus** [comment]
对不起，忘了系统和XX-Net的状态信息了。
Sys Platform	darwin
OS System	Darwin
OS version	Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
OS release	14.3.0
OS detail	Release:10.10.3; Version:('', '', '') Machine:x86_64
language	( en, "zh-Hans", ja )
architecture	64bit
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36
XX-Net Version	1.12.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087
working appids	goagentzmh|goagentzmh0|goagentzmh1|goagentzmh2|goagentzmh3|goagentzmh4|goagentzmh5|goagentzmh6|goagentzmh7|goagentzmh8|goagentzmh9
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2991
connected link	11,11
ip-connect-interval

**Comment by newcastlecy** [comment]
210.139.253.216
64.233.162.85
64.233.162.82
173.194.195.97
64.233.162.81
173.194.204.190
208.117.224.40
173.194.67.200
193.90.147.102
85.182.250.152
216.58.209.106
61.19.1.212
216.58.211.22
64.233.178.165
216.58.211.116
64.233.191.118
64.233.166.139
216.58.209.184
81.175.29.176
62.1.38.109
78.37.100.245
74.125.195.165
74.125.69.196
64.233.168.155
1.179.252.113
216.58.217.52
173.194.194.97
193.192.226.148
64.233.184.154
216.58.222.62
64.233.177.123
216.58.221.197
173.194.77.190
216.58.217.152
106.162.192.172
208.117.224.145
213.158.11.24
41.201.128.39
93.123.23.18
173.194.66.86
86.127.118.163
41.201.164.20
37.228.69.42
216.58.208.84
193.192.250.182
216.58.219.184
216.58.221.222
64.15.117.24
74.125.227.76
210.139.253.236
64.233.191.195
173.194.124.93
64.233.184.190
216.58.222.29
64.15.116.117
213.158.11.31
193.134.255.39
216.58.208.90
216.58.210.30
64.233.166.156
218.176.242.88
64.233.169.142
197.84.128.50
64.233.182.201
208.117.228.83
85.182.250.246
149.3.177.118
64.233.185.86
203.66.124.152
64.233.168.197
193.192.250.152
1.179.248.167
216.58.210.244
210.158.146.121
74.125.134.142
208.117.224.166
173.194.122.3
64.233.179.165
208.117.253.52
64.233.179.105
149.3.177.55
149.3.177.54
210.153.73.118
216.58.221.104
149.126.86.42
64.15.116.213
64.233.171.191
64.233.185.90
197.199.253.53
74.125.229.71
64.233.177.117
1.179.248.152
64.233.177.114
64.233.167.142
64.233.185.136
210.158.146.223
208.117.227.18
64.15.126.177
111.92.162.19
64.233.191.152
208.117.224.205
173.194.207.113
210.245.14.24
199.87.241.57
202.169.193.121
216.58.219.192
216.58.219.218
216.58.210.59
64.233.180.166
64.233.161.165
61.19.1.237
173.194.121.56
208.117.253.22
64.233.166.199
64.233.184.90
61.19.1.172
173.194.118.200
83.94.121.222
210.158.146.230
64.15.116.120
37.228.69.29
64.15.116.122
210.245.14.94
74.125.196.191
193.120.166.110
208.117.228.51
194.78.99.238
173.194.66.142
173.194.219.86
173.194.192.117
74.125.206.84
194.78.99.230
64.233.160.31
173.194.213.137
216.58.220.127
64.233.191.124
212.188.7.45
95.54.196.237
216.58.220.52
194.78.99.183
1.179.251.89
118.143.88.95
210.245.14.109
216.58.220.252
64.15.126.254
1.179.248.84
64.15.116.154
216.58.220.163
64.15.113.40
210.245.14.221
208.117.224.227
194.78.99.224
194.78.99.117
178.45.251.93
208.117.233.21
118.174.25.119
64.233.179.85
106.162.216.35
199.87.241.51
216.58.208.243
193.192.226.183
1.179.251.94
81.175.29.154
31.209.137.31
173.194.196.152
64.15.114.54
64.15.126.249
210.245.14.119
173.194.194.176
74.125.143.77
216.58.208.39
77.66.9.102
77.66.9.106
193.134.255.29
216.58.209.112
216.58.220.228
106.162.216.29
64.233.167.95
64.233.167.90
193.120.166.102
202.39.143.34
61.19.1.49
81.175.29.166
85.182.250.187
193.134.255.246
216.58.208.250
64.233.167.191
64.233.167.196
208.117.224.24
半小时这么多 湖南电信楼

**Comment by feifei2050** [comment]
上海电信
64.233.162.86
64.233.162.87
95.143.84.163

**Comment by jeremy0714** [comment]
XX-Net Version	1.12.5

其中一个pythonw.exe cpu稍微有点高，百分之30多
block stat(帮助)	Blocked, 29 seconds to wait  一直 显示 ，但是没有bad_ip2.txt

**Comment by ycfriend** [comment]
上海电信

64.233.162.86
64.233.162.136
61.219.131.123
74.125.143.66
212.188.7.216
64.233.162.81
216.58.220.23
203.117.34.173
208.117.224.40
83.145.196.181
74.125.196.191
208.117.224.136
173.194.64.167
74.125.195.198
216.58.211.79
64.233.181.198
64.15.126.234
197.199.253.35
210.245.14.162
74.125.26.115
64.15.119.213
64.233.171.194
216.58.209.188
93.123.23.24
216.58.209.225
210.153.73.118
208.117.229.184
173.194.122.246
208.117.230.30
216.58.223.29
83.94.121.217
208.117.224.241
203.66.124.227
208.117.233.87
64.15.116.20
173.194.122.105
216.58.218.182
62.1.38.84
64.233.176.133
216.58.213.47
84.235.77.168
84.235.77.40
41.201.128.30
208.117.229.9
222.255.120.15
193.192.226.148
216.58.220.134
103.1.139.152
64.233.162.82
194.78.99.148
74.125.24.142
216.58.211.181
64.233.165.146
64.233.184.165
64.233.162.31
64.233.177.114
216.58.223.23
213.158.11.173
74.125.131.81
208.117.228.17
64.233.163.116
64.233.180.138
61.19.1.187
173.194.77.195
208.117.224.140
93.183.211.212
114.4.41.249
86.127.118.167
173.194.67.31
173.194.67.196
208.117.224.148
41.201.164.20
202.65.246.85
64.233.161.138
1.179.248.182
213.158.11.185
62.1.38.177
64.233.161.136
178.45.251.45
173.194.197.190
83.145.196.148
216.58.220.115
83.145.196.144
194.78.99.88
216.58.219.123
64.233.180.201
1.179.248.173
64.233.177.132
66.185.84.153
74.125.142.122
37.228.69.34
64.233.167.166
85.182.250.50
216.58.221.97
118.174.25.50
216.58.208.98
203.165.14.241
118.174.25.119
213.158.11.39
216.58.210.33
208.117.228.83
64.233.177.104
64.233.168.86
74.125.69.149
64.233.169.143
212.188.7.114
64.233.180.145
64.233.166.86
208.117.253.84
64.15.116.187
208.117.253.22
149.3.177.26
193.90.147.16
74.125.71.115
193.192.250.158
173.194.116.224
64.233.183.90
64.233.165.167
203.66.124.157
64.233.168.195
64.15.116.214
64.15.126.169
1.179.248.167
64.233.167.152
80.64.175.102
64.15.126.165
213.158.11.151
85.182.250.103
216.58.216.89
64.233.178.96
216.58.210.29
173.194.73.81
64.15.119.226
64.233.168.104
213.158.11.245
64.233.165.124
64.233.166.164
74.125.131.124
208.117.253.52
194.78.99.25
64.15.119.220
64.233.180.157
208.117.227.84
213.158.11.249
173.194.194.165
64.233.185.90
216.58.210.90
216.58.220.106
61.19.1.157
208.117.228.218
1.179.248.153
216.58.216.32
118.174.25.44
64.233.167.147
64.233.177.94
64.15.126.177
64.233.187.106
208.117.224.173
64.233.177.143
178.60.128.37
121.78.74.101
123.205.250.106
213.240.44.22
199.87.241.57
64.15.116.26
210.245.14.20
216.58.211.169
149.126.86.38
74.125.192.69
62.116.207.26
64.15.124.212
149.126.86.31
216.58.210.57
74.125.202.197
216.58.216.47
77.66.9.90
203.66.124.177
64.233.161.83
208.117.228.209
208.117.228.113
83.94.121.178
208.117.228.118
64.233.179.17
78.37.100.249
74.125.141.196
216.58.211.74
64.233.183.118
216.58.218.160
88.159.13.227
85.182.250.123
64.233.167.137
61.219.131.246
194.78.99.238
210.158.146.80
173.194.219.86
194.78.99.102
194.78.99.230
84.235.77.232
118.174.27.123
74.125.224.25
64.233.162.84
216.58.211.150
64.233.176.132
74.125.143.85
216.58.211.159
210.139.253.54
64.233.180.19
118.143.88.95
64.233.183.136
212.188.7.236
74.125.229.92
216.58.211.133
216.58.219.240
93.123.23.38
64.233.185.116
64.15.126.254
83.94.121.231
64.15.113.49
193.90.147.121
64.15.116.155
64.15.126.153
208.117.253.90
64.233.177.176
208.117.224.166
64.233.167.86
216.58.216.64
64.233.178.101
194.78.99.223
210.139.253.55
216.58.217.99
64.15.112.180
178.45.251.103
64.233.176.196
203.165.13.212
95.143.84.170
81.175.29.154
216.58.216.125
202.86.162.20
64.233.164.143
213.158.11.32
216.58.212.94
64.233.162.97
216.58.209.50
64.15.124.155
106.162.198.93
64.233.162.123
64.233.162.83
64.233.165.86
41.206.96.154
60.199.175.152
216.58.219.50
173.194.124.49
216.58.209.130
193.90.147.113
216.58.221.170
202.39.143.30
64.233.180.87
80.228.65.163
81.175.29.166
24.156.131.109
193.134.255.246
62.1.38.148
61.19.1.183
64.233.179.146
64.233.179.144
208.117.224.25

**Comment by nocole** [comment]
64.233.181.124
173.194.196.145
210.245.14.242

**Comment by whzzz** [comment]
所在地：江苏省南京市
运营商：电信（高校内的电信）
XX-Net版本：1.12.2
系统版本：Windows8.1 x64
bad_ip.txt内容：
74.125.195.117
61.219.131.123
216.58.212.114
64.233.180.193
64.233.167.166
208.117.224.40
64.233.184.144
193.90.147.102
74.125.129.197
222.255.120.27
64.15.126.234
194.78.99.84
64.15.126.231
210.245.14.163
216.58.209.188
62.0.54.103
216.58.211.26
66.185.84.162
74.125.196.96
64.15.113.25
64.233.181.116
203.66.124.227
178.45.251.44
106.162.192.182
173.194.64.198
41.201.164.39
173.194.71.189
210.139.253.89
222.255.120.19
216.58.219.239
210.153.73.94
216.58.211.187
208.117.253.116
74.125.21.144
64.233.162.31
64.233.180.138
173.194.219.112
85.182.250.20
216.58.208.88
197.84.128.40
64.233.176.87
74.125.134.133
210.139.253.237
74.125.133.114
123.205.251.80
1.179.248.177
64.233.177.138
203.211.0.59
203.66.124.242
208.117.224.139
216.58.209.117
216.58.210.35
216.58.216.207
64.233.166.86
64.233.168.137
193.120.166.121
74.125.21.199
118.174.25.231
178.45.251.35
202.39.143.88
216.58.219.112
80.64.175.83
216.58.219.116
64.233.167.157
64.15.116.212
64.15.126.165
216.58.217.213
64.15.126.247
216.58.217.126
216.58.220.193
64.233.181.81
210.242.125.45
210.245.14.34
80.228.65.173
64.233.178.133
64.15.124.185
216.58.213.26
216.58.216.174
193.134.255.162
64.15.117.23
64.233.176.165
216.58.221.222
64.15.119.147
64.233.181.155
64.233.178.201
1.179.253.88
208.117.224.208
208.117.227.85
64.15.126.160
62.116.207.20
64.233.179.117
111.168.255.167
173.194.112.77
216.58.211.164
64.233.168.176
64.233.166.198
216.58.212.123
64.15.119.154
216.239.32.6
74.125.141.196
216.58.211.74
64.15.116.122
64.233.171.137
210.158.146.80
210.242.125.34
1.179.248.54
64.233.163.152
64.233.163.155
216.58.208.45
216.58.219.160
216.58.209.65
210.245.14.108
82.135.118.46
213.158.11.88
64.233.162.113
208.117.224.118
64.233.180.189
216.58.209.122
64.233.167.87
64.233.167.86
1.179.248.89
194.78.99.227
193.120.166.102
216.58.217.99
61.19.1.34
210.139.253.114
84.235.77.246
111.168.255.49
78.37.100.222
213.158.11.162
74.125.136.197
64.233.162.103
74.125.133.146
62.1.38.158
194.78.99.96
64.233.160.176
216.58.221.176
208.117.253.89
194.78.99.113
74.125.192.60
64.233.178.176
64.233.171.136
24.156.131.109
178.45.251.119
178.45.251.118
216.58.216.131
212.188.10.20
64.233.160.116
64.233.163.95

**Comment by liaoyaoheng** [comment]
所在地：广东省广州市
运营商：电信adsl
XX-Net版本：1.12.5
系统版本：Windows7 x64

213.240.44.25
64.233.162.84
216.58.212.115
1.179.248.237
210.153.73.25
118.174.25.34
173.194.219.90
64.15.117.120
216.58.220.70
173.194.121.71
64.233.161.148
216.58.219.138
216.58.210.117
64.233.179.106
106.162.192.177
1.179.248.99
210.245.14.231
64.233.171.137
74.125.131.84
173.194.71.90
216.58.211.164
173.194.203.166
64.233.180.156

**Comment by derik1527** [comment]
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.12.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087


1
8
2
210.153.73.55
0

**Comment by ecamel** [comment]
所在地：北京市
运营商：教育网
XX-Net版本：教育网
系统版本：Windows8.1 x64
bad_ip.txt内容：
61.219.131.123
216.58.211.113
111.92.162.53
95.143.84.185
106.162.216.84
139.175.107.98
216.58.209.106
64.15.126.234
139.175.107.93
208.117.224.139
64.15.119.109
210.245.14.163
111.168.255.183
74.125.196.96
213.158.11.172
203.66.124.187
64.233.181.116
1.179.248.109
0
106.162.192.182
216.58.218.180
111.92.162.44
111.92.162.45
216.58.219.239
210.153.73.93
139.175.107.108
106.162.198.109
216.58.209.111
216.58.222.62
64.233.177.123
106.162.192.178
173.194.204.90
218.253.0.87
106.162.192.172
203.117.36.162
106.162.192.177
218.253.0.82
212.188.15.187
203.66.124.232
210.61.221.178
173.194.77.190
85.182.250.20
139.175.107.29
210.61.221.94
199.87.241.54
197.199.253.16
216.58.218.196
64.233.176.87
213.240.44.24
210.61.221.172
210.158.146.223
111.168.255.93
203.116.165.183
74.125.21.199
74.125.133.114
106.162.216.30
213.158.11.96
194.78.99.227
106.162.192.167
74.125.136.197
210.61.221.89
216.58.209.117
64.15.126.231
139.175.107.30
121.78.74.90
116.92.194.155
64.233.166.86
64.233.168.137
203.116.165.167
60.199.175.172
203.66.124.157
193.192.226.172
106.162.192.157
218.189.25.159
106.162.192.152
216.58.217.213
106.162.192.158
111.92.162.29
1.179.248.54
118.143.88.59
64.15.126.206
203.165.13.247
213.158.11.46
202.86.162.20
173.194.121.109
208.117.224.236
208.117.253.59
202.39.143.93
64.233.176.165
203.117.34.152
216.58.216.34
202.39.143.99
216.58.221.222
212.188.10.227
64.233.160.103
111.92.162.15
106.162.192.148
173.194.219.146
194.78.99.96
218.189.25.146
121.78.74.102
64.233.171.102
60.199.175.24
114.4.41.216
216.58.217.152
64.15.126.160
74.125.134.133
62.116.207.20
62.116.207.27
64.233.179.117
173.194.112.77
216.58.220.193
106.162.198.123
64.233.161.166
106.162.216.118
64.233.168.176
64.233.166.198
106.162.198.94
106.162.198.93
216.58.212.123
74.125.141.196
1.179.249.242
64.233.178.176
222.255.120.53
123.205.250.117
61.219.131.242
58.145.238.38
210.242.125.30
210.139.253.40
64.233.163.155
203.165.13.227
111.168.255.123
208.117.224.188
64.15.116.154
208.117.227.85
210.245.14.108
202.39.143.119
213.158.11.207
111.168.255.163
64.233.178.133
208.117.224.118
222.255.120.45
216.58.209.122
218.189.25.166
64.233.177.138
178.45.251.118
1.179.248.89
210.245.14.222
194.78.99.116
208.117.253.54
210.242.125.29
64.233.179.81
106.162.216.29
210.158.146.99
210.242.125.20
106.162.216.20
61.19.1.34
1
60.199.175.162
78.37.100.222
213.240.44.16
64.233.167.166
193.134.255.50
203.66.124.242
202.39.143.108
173.194.194.176
195.249.20.230
60.199.175.96
64.233.162.103
74.125.133.146
203.116.165.231
106.162.216.99
210.245.14.212
173.194.209.103
203.116.165.237
74.125.192.60
64.15.113.25
202.39.143.34
193.120.166.113
203.66.124.217
193.134.255.247
203.66.124.212
64.233.160.116
216.58.211.74
64.15.117.23
103.25.178.19

**Comment by xxnet** [comment]
收到，谢谢。
不需要再反馈这个列表了。
 
新版1.13.6在各位的支持下，已经比较稳定的能够在各种环境下工作了。
新用户需要跑一段时间，比如放一个晚上，第二天就会比较快了。
有发现问题请继续反馈。

**Comment by mini2017** [comment]
XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 QQBrowser/9.3.6581.400
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 0 / 0
network-status: Fail
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by mini2017** [comment]
XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 QQBrowser/9.3.6581.400
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 0 / 0
network-status: Fail
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true我想问下我这是怎么回事啊上不了

**Comment by mini2017** [comment]
XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 QQBrowser/9.3.6581.400
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 0 / 0
network-status: Fail
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true江苏电信的昨天还好好的
