### ISSUE TITLE
关注项目挺久了，出来冒个泡

### ISSUE THREAD

**Issue by cntanglijun** [XX-net/XX-Net#2473]
发现项目团队正在折腾代码风格:alien:，提个建议，可以添加一个[.editorconfig](http://editorconfig.org/)文件，确保不同的编辑器可以统一代码风格。比如文件的编码，代码缩进等等:ghost:

**Comment by zjhzxhz** [comment]
我们说的代码风格指的是那些驼峰命名什么的.
你说的这些并不是特别重要.

**Comment by simonasd** [comment]
其实编码什么的还是有点影响的。遇到过用户编辑GAEproxy的proxy.ini文件，因为编码变化导致读取错误的。

**Comment by zjhzxhz** [comment]
一切都是WIndows的错~
你看Linux和Unix默认全都是`UTF-8`，多和谐~

**Comment by cntanglijun** [comment]
@zjhzxhz soga， 了解了。

**Comment by simonasd** [comment]
@zjhzxhz 巨硬药丸

**Comment by zjhzxhz** [comment]
巨硬手机市场没保住 连Windows也搭进去了。
Windows 8和10应该都表现不佳吧~ 要不是“强制”升级才没有那么多人装Windows。
表示现在还在用Windows 7，难道是我老了吗？
