### ISSUE TITLE
Mac下代理设置的问题和WebUI的问题

### ISSUE THREAD

**Issue by hahn1994** [XX-net/XX-Net#2490]
我来反馈一个问题：
当Mac使用PPPoE拨号方式的时候不能在拨号连接上设置代理，需要手动设置方可生效。
还有Mac的WebUI下证书的检查和代理的检测都是Fail，但是经过手动设置是可以翻墙的，应该是WebUI的BUG
——————————————————————————————————————————
这是设置代理的日志：
Mar 25 16:42:35.733 - [INFO] try enable proxy:osascript -e 'do shell script "networksetup -setwebproxystate Ethernet off;networksetup -setwebproxystate \"Thunderbolt Ethernet\" off;networksetup -setwebproxystate Wi-Fi off;networksetup -setsecurewebproxystate Ethernet off;networksetup -setsecurewebproxystate \"Thunderbolt Ethernet\" off;networksetup -setsecurewebproxystate Wi-Fi off;networksetup -setautoproxystate Ethernet off;networksetup -setautoproxystate \"Thunderbolt Ethernet\" off;networksetup -setautoproxystate Wi-Fi off;networksetup -setautoproxyurl Ethernet \"http://127.0.0.1:8086/proxy.pac\";networksetup -setautoproxyurl \"Thunderbolt Ethernet\" \"http://127.0.0.1:8086/proxy.pac\";networksetup -setautoproxyurl Wi-Fi \"http://127.0.0.1:8086/proxy.pac\"" with administrator privileges' 
** Error: The parameters were not valid. database.
——————————————————————————————————————————
XX-Net Status：

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 143 / 70
network-status: OK
connected-link: 4 / 1
scan-ip-thread-num: 50
ip-quality: 518
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by hahn1994** [comment]
新发现：自动调整扫描线程数也不管用，ip延迟为295 线程数还是是50 不会自动减小

**Comment by xxnet** [comment]
@zjhzxhz @cc941201 
“当Mac使用PPPoE拨号方式的时候不能在拨号连接上设置代理，需要手动设置方可生效。”
能否看看？

**Comment by hahn1994** [comment]
Mar 26 16:05:07.783 - [DEBUG] network is ok, cost:147 ms
Mar 26 16:05:07.783 - [INFO] SSL use version:TLSv1
Mar 26 16:05:07.785 - [INFO] load ip range file:/Users/Hahn/Library/XX-Net/data/gae_proxy/ip_range.txt
Mar 26 16:05:07.820 - [INFO] load google ip_list num:376, gws num:376
Mar 26 16:05:07.821 - [INFO] Adjust scan thread num from 50 to 36
Mar 26 16:05:07.836 - [DEBUG] ## GAEProxy set keep_running: True
Mar 26 16:05:07.837 - [INFO] ------------------------------------------------------
Mar 26 16:05:07.837 - [INFO] Python Version : 2.7.10
Mar 26 16:05:07.837 - [INFO] OS : Release:10.11.4; Version:('', '', '') Machine:x86_64
Mar 26 16:05:07.838 - [INFO] Listen Address : 127.0.0.1:8087
Mar 26 16:05:07.838 - [INFO] GAE APPID : hahn1994-ga-1|hahn1994-ga-2|hahn1994-ga-3|hahn1994-ga-4|hahn1994-ga-5|hahn1994-ga-6|
Mar 26 16:05:07.838 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Mar 26 16:05:07.838 - [INFO] ------------------------------------------------------
**Mar 26 16:05:07.871 - [INFO] GoAgent CA exist**

这是今天启动时看到的 日志输出证书存在，但是WebUI上的CA证书状态，仍然是Fail
正如我之前描述的，虽然代理状态和CA状态都是Fail，但是我手动检查代理都已设置好，是可以番茄的

**Comment by cc941201** [comment]
@xxnet 如果要解决这个问题，估计就不能hard code接口名了，因为PPPoE连接可以随意命名。我在看API是否可以获取当前使用的接口名。

**Comment by zjhzxhz** [comment]
@xxnet 
Macbook 没有插网线的地方~ 哈哈哈哈哈哈哈~

**Comment by xxnet** [comment]
还是要根据获取到的接口名称来设置代理，我记得命令行里是有这个功能的，不过需要解析它的输出文本，再逐个设置，比较麻烦，不过这才能根本上解决这个问题。

**Comment by cc941201** [comment]
刚在Playground里试了下，这段Swift代码可以找出当前使用的IPv4接口
```Swift
import SystemConfiguration
let global = SCDynamicStoreCopyValue(nil, "State:/Network/Global/IPv4") as! [String: String]
let interface = global["PrimaryService"]!
let service = SCDynamicStoreCopyValue(nil, "Setup:/Network/Service/" + interface) as! [String: String]
service["UserDefinedName"]
```

**Comment by xxnet** [comment]
Swift代码能做脚本吗？
​最好是python代码里实现，或者Mac脚本实现

**Comment by cc941201** [comment]
SystemConfiguration中都是C的API，在python中调用没问题。我再看看文档，尽量今晚写好提交PR

**Comment by xxnet** [comment]
我印象中 networksetup 有一个命令是列出当前网络设备的。
你可以看看。

C接口准备用ctype调用吗？

哪个方法简单用哪个，呵呵。

**Comment by xxnet** [comment]
代码合并了。

@hahn1994 可以下载下面的地址，测试是否解决了：
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by hahn1994** [comment]
@xxnet 可以的，代理设置的问题解决了

**Comment by hahn1994** [comment]
@xxnet 但是为什么我的WebUI上面的代理状态和证书状态一直检测不到

**Comment by cc941201** [comment]
@hahn1994 试一下我刚修改的版本：
https://github.com/cc941201/XX-Net/archive/master.zip

**Comment by hahn1994** [comment]
@cc941201 还是那个问题
--------------------------
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: 2.9.5
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: total:2748 good:2462
network-status: OK
connected-link: new:6 used:3
scan-ip-thread-num: 37
ip-quality: 162
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
--------------------------------------
启动日志：

Mar 28 09:37:59.316 - [DEBUG] start confirm_xxnet_exit
Mar 28 09:37:59.320 - [DEBUG] good, xxnet:8087 cleared!
Mar 28 09:37:59.321 - [DEBUG] good, xxnet:8085 clear!
Mar 28 09:37:59.321 - [DEBUG] finished confirm_xxnet_exit
Mar 28 09:37:59.502 - [DEBUG] network is ok, cost:65 ms
Mar 28 09:37:59.509 - [INFO] SSL use version:TLSv1
Mar 28 09:37:59.513 - [INFO] load ip range file:/Users/Hahn/Library/XX-Net/data/gae_proxy/ip_range.txt
Mar 28 09:37:59.564 - [INFO] load google ip_list num:2689, gws num:2689
Mar 28 09:37:59.569 - [INFO] Adjust scan thread num from 50 to 38
Mar 28 09:37:59.595 - [DEBUG] ## GAEProxy set keep_running: True
Mar 28 09:37:59.596 - [INFO] ------------------------------------------------------
Mar 28 09:37:59.596 - [INFO] Python Version     : 2.7.10
Mar 28 09:37:59.596 - [INFO] OS                 : Release:10.11.4; Version:('', '', '') Machine:x86_64
Mar 28 09:37:59.597 - [INFO] Listen Address     : 127.0.0.1:8087
Mar 28 09:37:59.597 - [INFO] GAE APPID          : hahn1994-ga-1|hahn1994-ga-2|hahn1994-ga-3|hahn1994-ga-4|hahn1994-ga-5|hahn1994-ga-6|
Mar 28 09:37:59.597 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Mar 28 09:37:59.597 - [INFO] ------------------------------------------------------
Mar 28 09:37:59.631 - [INFO] GoAgent CA exist
Mar 28 09:37:59.631 - [INFO] server 127.0.0.1:8087 started.
Mar 28 09:37:59.632 - [INFO] server 127.0.0.1:8086 started.
Mar 28 09:37:59.694 - [INFO] module gae_proxy started
Mar 28 09:37:59.695 - [INFO] start gae_proxy time cost:373 ms
Mar 28 09:37:59.695 - [INFO] begin to start web control
Mar 28 09:37:59.696 - [INFO] server 127.0.0.1:8085 started.
Mar 28 09:37:59.696 - [INFO] launcher web control started.
Mar 28 09:38:00.034 - [INFO] try setup helper:osascript -e 'do shell script "cp \"/Users/Hahn/Library/XX-Net/launcher/mac_helper\" \"/Users/Hahn/Library/XX-Net/launcher/../data/launcher/helper\";chmod 4777 \"/Users/Hahn/Library/XX-Net/launcher/../data/launcher/helper\";chown root \"/Users/Hahn/Library/XX-Net/launcher/../data/launcher/helper\"" with administrator privileges' 

Mar 28 09:38:00.645 - [DEBUG] launcher web_control 127.0.0.1:50125 GET /config?cmd=get_config

**Comment by cc941201** [comment]
@hahn1994 你试下访问https://www.twitter.com/xxnet，是否显示OK

**Comment by hahn1994** [comment]
@cc941201 翻墙是可以的，证书和代理都是设置好的，只是XX-NET的网页管理页面上检测不到这两个的正确状态

**Comment by cc941201** [comment]
@hahn1994 XX-Net的检测机制是基于那个网址的，在通过代理访问该网址时网页内容会被替换为OK。通过别的翻墙方式访问则会看到twitter。

请确认一下是否是OK，以便查明是哪一块出的问题

**Comment by hahn1994** [comment]
@cc941201 好奇怪的现象。。你没回复之前是网页，刚你回复了 我又试了一下 显示是OK 然后赶忙去看了一下检测状态全OK了 现在都正常
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: 2.9.5
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: total:3000 good:3000
network-status: OK
connected-link: new:5 used:50
scan-ip-thread-num: 50
ip-quality: 166
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
如果是个奇葩的问题，可以载入史册

**Comment by hahn1994** [comment]
@cc941201 @jzp820927 @xxnet 
我刚又试了一下怎么才能出现那个奇怪的现象，现在来猜测一下BUG的原因，我没有看过代码不知道说的对不对：
程序启动还未设置好代理的时候就去检测https://www.twitter.com/xxnet这个网址
代理设置成功后，没有重新请求，或者卡在那个检测的地方，一直未返回OK
结果导致CA和代理一直是Fail
有没有这个可能

**Comment by cc941201** [comment]
@hahn1994 检测失败会一直自动重试

**Comment by xxnet** [comment]
​这个问题似乎解决了，确实有发现浏览器缓存了结果，不过不确实是否已经发布版本
