### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by EI3ven** [XX-net/XX-Net#2491]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: get_version_fail
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: total:4 good:3
network-status: OK
connected-link: new:1 used:2
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
GAE日志呢？

**Comment by EI3ven** [comment]
Mar 25 18:11:54.156 - [INFO] try enable proxy:osascript -e 'do shell script "networksetup -setwebproxystate Ethernet off;networksetup -setwebproxystate \"Thunderbolt Ethernet\" off;networksetup -setwebproxystate Wi-Fi off;networksetup -setsecurewebproxystate Ethernet off;networksetup -setsecurewebproxystate \"Thunderbolt Ethernet\" off;networksetup -setsecurewebproxystate Wi-Fi off;networksetup -setautoproxystate Ethernet off;networksetup -setautoproxystate \"Thunderbolt Ethernet\" off;networksetup -setautoproxystate Wi-Fi off;networksetup -setautoproxyurl Ethernet \"http://127.0.0.1:8086/proxy.pac\";networksetup -setautoproxyurl \"Thunderbolt Ethernet\" \"http://127.0.0.1:8086/proxy.pac\";networksetup -setautoproxyurl Wi-Fi \"http://127.0.0.1:8086/proxy.pac\"" with administrator privileges'
Mar 25 18:11:54.855 - [DEBUG] 78.11.253.230 fail:timeout('timed out',)
Mar 25 18:11:54.855 - [DEBUG] report_connect_fail:78.11.253.230
Mar 25 18:11:55.169 - [DEBUG] 208.104.242.86 fail:timeout('timed out',)
Mar 25 18:11:55.169 - [DEBUG] report_connect_fail:208.104.242.86
Mar 25 18:11:55.280 - [DEBUG] 208.65.154.67 fail:timeout('timed out',)
Mar 25 18:11:55.280 - [DEBUG] report_connect_fail:208.65.154.67
Mar 25 18:11:55.375 - [DEBUG] 74.125.154.23 fail:timeout('timed out',)
Mar 25 18:11:55.378 - [DEBUG] report_connect_fail:74.125.154.23
Mar 25 18:11:55.480 - [DEBUG] 186.68.154.52 fail:timeout('timed out',)
Mar 25 18:11:55.480 - [DEBUG] report_connect_fail:186.68.154.52
Mar 25 18:11:55.719 - [DEBUG] 194.44.4.84 fail:timeout('timed out',)
Mar 25 18:11:55.720 - [DEBUG] report_connect_fail:194.44.4.84
** Error: The parameters were not valid. database.
Mar 25 18:11:56.014 - [DEBUG] 49.231.60.221 fail:timeout('timed out',)
Mar 25 18:11:56.014 - [DEBUG] report_connect_fail:49.231.60.221
Mar 25 18:11:59.652 - [DEBUG] create_ssl update ip:203.248.210.48 time:5968
Mar 25 18:12:09.868 - [DEBUG] ip:78.11.253.230 real fail

**Comment by jzp820927** [comment]
没看到错误日志，不过IP好像都连接超时了

**Comment by EI3ven** [comment]
Mar 25 18:32:30.309 - [WARNING] no enough ip
Mar 25 18:32:30.322 - [DEBUG] get ip:185.2.108.211 t:453
Mar 25 18:32:30.387 - [WARNING] no enough ip
Mar 25 18:32:30.423 - [DEBUG] get ip:49.231.60.246 t:593
Mar 25 18:32:30.497 - [WARNING] no enough ip
Mar 25 18:32:30.600 - [WARNING] no enough ip
Mar 25 18:32:30.612 - [WARNING] no enough ip
Mar 25 18:32:30.704 - [WARNING] no enough ip
Mar 25 18:32:30.807 - [WARNING] no enough ip
Mar 25 18:32:30.912 - [WARNING] no enough ip
Mar 25 18:32:31.016 - [WARNING] no enough ip
Mar 25 18:32:31.120 - [WARNING] no enough ip
Mar 25 18:32:31.154 - [DEBUG] create_ssl update ip:185.2.108.211 time:554
Mar 25 18:32:31.222 - [WARNING] no enough ip
Mar 25 18:32:31.278 - [DEBUG] create_ssl update ip:49.231.60.246 time:586
Mar 25 18:32:42.628 - [INFO] scan_ip add ip:222.251.134.95 time:271
Mar 25 18:32:56.142 - [INFO] try enable proxy:osascript -e 'do shell script "networksetup -setwebproxystate Ethernet off;networksetup -setwebproxystate \"Thunderbolt Ethernet\" off;networksetup -setwebproxystate Wi-Fi off;networksetup -setsecurewebproxystate Ethernet off;networksetup -setsecurewebproxystate \"Thunderbolt Ethernet\" off;networksetup -setsecurewebproxystate Wi-Fi off;networksetup -setautoproxystate Ethernet off;networksetup -setautoproxystate \"Thunderbolt Ethernet\" off;networksetup -setautoproxystate Wi-Fi off;networksetup -setautoproxyurl Ethernet \"http://127.0.0.1:8086/proxy.pac\";networksetup -setautoproxyurl \"Thunderbolt Ethernet\" \"http://127.0.0.1:8086/proxy.pac\";networksetup -setautoproxyurl Wi-Fi \"http://127.0.0.1:8086/proxy.pac\"" with administrator privileges'
** Error: The parameters were not valid. database.
之前都用好好的，今天突然有问题，我下载之后重新设置的，就开始有问题了

**Comment by yeahwu** [comment]
先检查证书，不行的话，再检查代理。就这两毛病

**Comment by EI3ven** [comment]
证书下载了，怎么导入啊

**Comment by EI3ven** [comment]
Mar 25 18:35:54.717 - [ERROR] handler:TypeError("'NoneType' object has no attribute '__getitem__'",) cmd:GET path:/update?cmd=get_new_version from:127.0.0.1:55401
Mar 25 18:35:54.719 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/admin/Desktop/XX-Net-master/python27/1.0/lib/noarch/simple_http_server.py", line 129, in handle_one_request
    self.do_GET()
  File "/Users/admin/Desktop/XX-Net-master/launcher/web_control.py", line 156, in do_GET
    self.req_update_handler()
  File "/Users/admin/Desktop/XX-Net-master/launcher/web_control.py", line 387, in req_update_handler
    data = '{"res":"success", "test_version":"%s", "stable_version":"%s", "current_version":"%s"}' % (github_versions[0][1], github_versions[1][1], current_version)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by yeahwu** [comment]
先删除老证书，再导入新证书
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Chrome%E6%B5%8F%E8%A7%88%E5%99%A8

**Comment by EI3ven** [comment]
证书是刚刚导入的，还是有问题

**Comment by yeahwu** [comment]
照着那个流程再操作一遍

**Comment by jzp820927** [comment]
MAC OS X 系统没用过，还真不太了解

**Comment by EI3ven** [comment]
~/Desktop/XX-Net-master » sudo sh xx_net.sh                                                                                                               
Password:
-n Starting xx_net proxy server:
xx_net.


这个脚本起不来是什么原因啊，那个我把静态IP换成dhcp就OK了
