### ISSUE TITLE
uploader.py 中 Your browser has been opened to visit: 时，cmd无法接受任何输入

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#2498]
包括Ctrl+C或其他输入，似乎只能终止进程，或者部署成功完成?（未尝试）。Win10。

命令示例（最新开发版）：
cmd 中 XX-Net\gae_proxy\server>`uploader.py xx-net 1@1.com 1`

**Comment by xxnet** [comment]
​oauth 会先弹出一个google 的登陆页面，在授权成功后，会访问localhost:8080的一个地址，带上oauth获取到的key.
在这个等待过程中，进程会开启8080端口，然后等待访问。

你遇到的情况，有没有看到弹出登陆google的窗口？
win10未测试，可能会有问题

**Comment by yfdyh000** [comment]
浏览器是正常弹出了。只是如果窗口未操作就被关掉了，这个cmd是没任何反应的，包括Ctrl+C，有点奇怪。不过cmd中有那个网址，复制应该不成问题。那么也关掉吧。
