### ISSUE TITLE
uploader.py 中文提示会乱码

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#2499]
2.9.2可见，2.9.4已换新SDK，重现方法不确定，但代码还在。Win10 cmd。
应该有办法转换输出编码到gbk吧。如果不能，只对非Windows显示中文吧，显示乱码无益。

XX-Net\gae_proxy\server>`uploader.py xx-net 1@1.com 1`
Auth fail. Please check you password.
鐧诲綍澶辫触锛岃妫€鏌ヤ綘鐨勫笎鍙峰瘑鐮併€?
濡傛灉鍚敤涓ら樁娈电櫥褰曪紝璇风敵璇峰簲鐢ㄤ笓鐢ㄥ瘑鐮? https://security.google.com/settings/security/apppasswords
濡傛灉娌℃湁鍚敤涓ら樁娈电櫥褰曪紝璇峰厑璁稿急瀹夊叏搴旂敤: https://www.google.com/settings/security/lesssecureapps

**Comment by yeahwu** [comment]
恩，这乱码有当年下黄片的感觉，

**Comment by xxnet** [comment]
觉得代码中不要放中文比较合理。
给出英文提示，而且这个提示也老了，oauth之后，不会有那么多登陆的疑难杂症了，可以先删掉

**Comment by yfdyh000** [comment]
嗯，那么就关闭这个问题吧，以后再加中文再考虑。
