### ISSUE TITLE
更新 1.11.3之後徹底掛了.

### ISSUE THREAD

**Issue by Exiaotian** [XX-net/XX-Net#250]
更新1.11.2的時候雖然速度很慢,但是還是可以用,但是更新1.11.3之後就徹底無法用了!

**Comment by xxnet** [comment]
现在1.11.2还能用吗？


2015-04-25 21:36 GMT-04:00 Exiaotian <notifications@github.com>:

**Comment by Cat7373** [comment]
1.11.2能找到少量ip
1.11.3无法找到
以上是在没修改good_ip.txt的情况下测试的

**Comment by lifeva** [comment]
还是程序机制出了问题，IP被全部封锁的可能性很小。早期的版本能工作就佐证了，估计是某个环节的更新出了问题。

**Comment by Cat7373** [comment]
不好说 早期版本也有些功能受到影响了 比如一些视频网站无法观看

**Comment by superjyq** [comment]
1.10.x没有问题，不要更新

**Comment by xxnet** [comment]
请测试新版 1.12.0
