### ISSUE TITLE
请问下ubuntu14.04如何配置自动启动，和如何更改全局代理。

### ISSUE THREAD

**Issue by Ailea** [XX-net/XX-Net#2500]
请问下ubuntu14.04如何配置自动启动，和更改全局代理。刚开始学习用ubuntu系统，知道的不多。

**Comment by jzp820927** [comment]
web 界面可以设置吧

**Comment by Iensgh** [comment]
打开终端并且把文件解压在的的ubuntu桌面(Desktop)：
1.cd ~
2.python Desktop/XX-Net-2.9.4/launcher/start.py
（注意，对着你下载的文件版本输入）

**Comment by Ailea** [comment]
@Iensgh 谢谢， 你的方法很好用。 
另外问一下改自动全局代理的话，配置文件怎么改。我现在是用网络设置里的全局代理，用手动填127.0.0.1:8087没问题，用PAC的自动代理连不上网，不知道是不是我哪里设置的不对。

**Comment by Iensgh** [comment]
你所说的网路设置，是ubuntu系统软件里的，还是浏览器上的？
如果是系统，都写成127.0.0.1:8087点确定后，在chrome浏览器上扩产程序的代理上，切换成"系统代理"

**Comment by Ailea** [comment]
@Iensgh OK 谢谢。
