### ISSUE TITLE
xx_net.sh 执行无反应

### ISSUE THREAD

**Issue by EI3ven** [XX-net/XX-Net#2505]
~/Desktop/XX-Net-master » sudo ./xx_net.sh                                                                                                                 
Password:
-n Starting xx_net proxy server:
xx_net.

然后就不工作

**Comment by xxnet** [comment]
​./start.sh 可以工作吗？

./xx_net.sh 启动，会到后台运行。
你可以用ps aux|grep python 看看有没有在后台运行

**Comment by EI3ven** [comment]
./start.sh正常启动
./xx_net.sh 后台有python在运行，可以xx_net 没有启动啊
root             5015   0.0  0.0  2473068   2640 s000  S     5:57PM   0:00.13 python launcher/start.py
admin            5461   0.0  0.0  2432792    564 s000  R+    6:31PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn python
root             5452   0.0  0.2  2474092  14344 s000  S     6:30PM   0:00.12 python launcher/start.py

**Comment by xxnet** [comment]
​xx_net 启动后台进程后，自己就退出了，正常的。
这个脚本是给服务器/路由器用的。

**Comment by EI3ven** [comment]
之前执行这个脚本就能启动xxnet，不想xxnet在后台一直有log输出
