### ISSUE TITLE
广东长城宽带全线无法FQ

### ISSUE THREAD

**Issue by jimmy-yao** [XX-net/XX-Net#251]
日志信息：

Apr 26 09:50:35 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:35 - [DEBUG] create_ssl 62.116.207.49 fail:timed out c:0 h:0
Apr 26 09:50:35 - [DEBUG] create_ssl 213.158.11.109 fail:timed out c:0 h:0
Apr 26 09:50:35 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:35 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:35 - [DEBUG] get ip:64.233.162.115 t:1030
Apr 26 09:50:35 - [DEBUG] tcp conn 64.233.160.132 fail t:1000
Apr 26 09:50:36 - [DEBUG] tcp conn 64.233.177.142 fail t:1000
Apr 26 09:50:36 - [DEBUG] network is fail
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail
Apr 26 09:50:36 - [DEBUG] get ip:216.58.216.168 t:1030
Apr 26 09:50:36 - [DEBUG] tcp conn 114.4.41.241 fail t:1001
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] network is ok
Apr 26 09:50:36 - [DEBUG] tcp conn 203.117.34.153 fail t:1001
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] get ip:173.194.42.109 t:1030
Apr 26 09:50:36 - [DEBUG] create_ssl 216.58.219.93 fail:timed out c:0 h:0
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] tcp conn 64.233.162.117 fail t:1000
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] get ip:173.194.212.133 t:1030
Apr 26 09:50:36 - [DEBUG] tcp conn 80.228.65.183 fail t:1000
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] get ip:64.233.163.154 t:1030
Apr 26 09:50:36 - [DEBUG] get ip:208.117.233.90 t:1030
Apr 26 09:50:36 - [DEBUG] tcp conn 216.58.211.145 fail t:1000
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] create_ssl 216.58.208.78 fail:timed out c:0 h:0
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] tcp conn 216.58.219.141 fail t:1000
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] get ip:84.235.77.187 t:1030
Apr 26 09:50:36 - [DEBUG] get ip:208.117.233.118 t:1030
Apr 26 09:50:36 - [DEBUG] get ip:216.58.221.59 t:1031
Apr 26 09:50:36 - [DEBUG] tcp conn 208.117.229.250 fail t:1000
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] create_ssl 64.233.166.142 fail:timed out c:0 h:0
Apr 26 09:50:36 - [DEBUG]LOG_EXCEPT: report_connect_fail network fail recently, Except:[Errno 9] Bad file descriptor
Apr 26 09:50:36 - [DEBUG] get ip:203.117.34.168 t:1031
Apr 26 09:50:36 - [DEBUG] get ip:216.58.209.205 t:1031
Apr 26 09:50:36 - [DEBUG] get ip:64.233.177.113 t:1031
Apr 26 09:50:36 - [DEBUG] create_ssl 64.233.178.167 fail:timed out c:0 h:0
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] tcp conn 64.233.162.115 fail t:1003
Apr 26 09:50:36 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:36 - [DEBUG] get ip:64.233.182.81 t:1032
Apr 26 09:50:37 - [DEBUG] tcp conn 216.58.216.168 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] get ip:64.233.180.156 t:1032
Apr 26 09:50:37 - [DEBUG] tcp conn 173.194.42.109 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] get ip:216.58.219.138 t:1032
Apr 26 09:50:37 - [DEBUG] get ip:216.58.217.8 t:1032
Apr 26 09:50:37 - [DEBUG] tcp conn 173.194.212.133 fail t:1003
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] tcp conn 64.233.163.154 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] tcp conn 208.117.233.90 fail t:1001
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] get ip:64.233.161.155 t:1034
Apr 26 09:50:37 - [DEBUG] get ip:208.117.224.197 t:1034
Apr 26 09:50:37 - [DEBUG] get ip:216.58.211.206 t:1034
Apr 26 09:50:37 - [DEBUG] tcp conn 84.235.77.187 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] get ip:118.174.25.241 t:1034
Apr 26 09:50:37 - [DEBUG] get ip:64.233.176.157 t:1034
Apr 26 09:50:37 - [DEBUG] tcp conn 208.117.233.118 fail t:1001
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] tcp conn 216.58.221.59 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] get ip:208.117.224.151 t:1034
Apr 26 09:50:37 - [DEBUG] get ip:216.58.220.226 t:1034
Apr 26 09:50:37 - [DEBUG] get ip:123.205.251.81 t:1034
Apr 26 09:50:37 - [DEBUG] create ssl timeout fail.
Apr 26 09:50:37 - [DEBUG] create_ssl_connection fail
Apr 26 09:50:37 - [DEBUG] ssl conn_num:0
Apr 26 09:50:37 - [DEBUG] tcp conn 203.117.34.168 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:37 - [DEBUG] get ip:216.58.212.79 t:1035
Apr 26 09:50:37 - [DEBUG] get ip:123.205.251.122 t:1035
Apr 26 09:50:37 - [DEBUG] tcp conn 64.233.182.81 fail t:1000
Apr 26 09:50:37 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] get ip:216.58.210.45 t:1035
Apr 26 09:50:38 - [DEBUG] tcp conn 64.233.180.156 fail t:1000
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] get ip:210.153.73.50 t:1035
Apr 26 09:50:38 - [DEBUG] tcp conn 216.58.217.8 fail t:1000
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] get ip:195.249.20.230 t:1035
Apr 26 09:50:38 - [DEBUG] create_ssl 216.58.209.205 fail:timed out c:0 h:0
Apr 26 09:50:38 - [DEBUG] create_ssl 64.233.177.113 fail:timed out c:0 h:0
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] tcp conn 64.233.161.155 fail t:1000
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] get ip:173.194.194.94 t:1035
Apr 26 09:50:38 - [DEBUG] tcp conn 216.58.211.206 fail t:1001
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] tcp conn 118.174.25.241 fail t:1000
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] tcp conn 64.233.176.157 fail t:1001
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] get ip:216.58.209.94 t:1035
Apr 26 09:50:38 - [DEBUG] get ip:216.58.219.78 t:1036
Apr 26 09:50:38 - [DEBUG]LOG_EXCEPT: tcp conn 208.117.224.151 fail t:1000, Except:[Errno 9] Bad file descriptor
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] create_ssl 216.58.219.138 fail:timed out c:0 h:0
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recently
Apr 26 09:50:38 - [DEBUG] get ip:216.58.217.138 t:1036
Apr 26 09:50:38 - [DEBUG] get ip:74.125.228.67 t:1036
Apr 26 09:50:38 - [DEBUG] tcp conn 123.205.251.81 fail t:1000
Apr 26 09:50:38 - [DEBUG] report_connect_fail network fail recent

系统信息：

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
XX-Net Version	1.8.5
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	jimmy7run
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2894
connected link	0
ip_connect_interval

**Comment by latrikcoasler** [comment]
死得很惨。

**Comment by jimmy-yao** [comment]
已经用上Shadowsocks

2015-04-26 10:29 GMT+08:00 latrikcoasler <notifications@github.com>:

**Comment by xxnet** [comment]
多备几把梯子

2015-04-26 3:18 GMT-04:00 jimmy-yao <notifications@github.com>:

**Comment by jimmy-yao** [comment]
电信的就行,长宽真是坑啊.
