### ISSUE TITLE
2.9.2 start.ink 无法启动，start.bat正常

### ISSUE THREAD

**Issue by lingyv-li** [XX-net/XX-Net#2510]
自启动的功能就没有了

**Comment by jzp820927** [comment]
日志？

**Comment by bartley-le** [comment]
start.ink闪退，start.bat又正常，所以好像……没有log

除了这个：
Mar 28 20:04:17.755 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to E:\Abroad\FGFW\XX-Net\data\downloads\README.md, retry:0
Mar 28 20:04:18.520 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
Mar 28 20:04:18.520 - [ERROR] Except stack:Traceback (most recent call last):
  File "E:\Abroad\FGFW\XX-Net\launcher\update.py", line 248, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[1][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jzp820927** [comment]
start.bat 正常，就用这个运行吧
