### ISSUE TITLE
撰写维基百科词条

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net#2522]
维基百科上还没有XX-Net的词条。撰写维基百科词条，对本项目的知名度会有很大帮助。

同时可以将XX-Net添加到[模板:突破网络封锁技术](https://zh.wikipedia.org/wiki/Template:%E7%AA%81%E7%A0%B4%E7%BD%91%E7%BB%9C%E5%B0%81%E9%94%81%E6%8A%80%E6%9C%AF)

不知道有没有哪位混维基百科的童鞋，熟悉相关的规则，能帮忙撰写？建议专门注册一个账号，避免个人身份信息泄漏。

**Comment by yeahwu** [comment]
这个建议好，必须顶顶。可惜，俺没文化呀。不过俺那个群里应该有相关人等。去喊喊

**Comment by jzp820927** [comment]
这个建议绝对支持

**Comment by xxnet** [comment]
这个不错，要加上一句：“这是一群匿名开发者参与开发的。。。”

**Comment by yeahwu** [comment]
https://zh.wikipedia.org/wiki/XX-Net
看来啥事得自己动手哇，还不快点赞

**Comment by yeahwu** [comment]
![10395542](https://cloud.githubusercontent.com/assets/13328328/14072502/b79d1138-f4f3-11e5-8cd0-fd34e1bffb3f.png)

**Comment by zhaipro** [comment]
无法编辑。原因为“google: "involuntary" open proxy”。

**Comment by yeahwu** [comment]
logo已经上传上去了。
提醒一下，lantern，gae，tor都是不可以编辑的，试试ss

**Comment by yeahwu** [comment]
https://zh.wikipedia.org/wiki/Template:%E7%AA%81%E7%A0%B4%E7%BD%91%E7%BB%9C%E5%B0%81%E9%94%81%E6%8A%80%E6%9C%AF
已链接至模板:突破网络封锁技术

**Comment by jzp820927** [comment]
x-tunnel 应该可以编辑吧

**Comment by yeahwu** [comment]
俺只能做到这鸟，其他的大家补充。

**Comment by yeahwu** [comment]
这个是怎么回事，直接给俺删鸟，我去
![2016-03-28 15 27 22](https://cloud.githubusercontent.com/assets/13328328/14073203/b1d54b3e-f4f9-11e5-8dcb-18a5fbdf79aa.png)

**Comment by jzp820927** [comment]
估计是内容太少了，被作为广告删掉了。

**Comment by yeahwu** [comment]
俺的帐号也被禁了，蛋疼
已经发邮件给维基，尼玛，俺们这是为了中国的劳苦大众，赶紧给劳资解封

**Comment by churximi** [comment]
也试着写了一个，不知道会不会被删- -

**Comment by yeahwu** [comment]
点赞。
churximi <notifications@github.com>于2016年3月28日 周一16:35写道：

**Comment by xxnet** [comment]
​看到了，赞。
可以加几个链接：
wsgzao.github.io/post/fq/ <https://t.co/SGRXxgqG9H>
https://wiki.archlinux.org/index.php/XX-Net_%28%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%29
https://gochrome.info/xxnet-tutorial/
http://t66y.com/htm_data/7/1512/1758850.html

wiki喜欢多点证据去证明

**Comment by yeahwu** [comment]
这个issus里果然是人才辈出哇！俺现在在这里都不敢大声说话鸟。

**Comment by churximi** [comment]
创建的词条又被删掉了，理由是广告宣传。。。

**Comment by yeahwu** [comment]
@churximi 辛苦，建议是在沙盒里一次性编辑完成。可能是内容太少，涉嫌广告。

**Comment by CHN008** [comment]
我看LibOffice有专门编辑维基百科的格式和功能,大家可以在那里面编辑好了传过去试试.

感觉在那上面创建一个条目要像写一篇论文一样? 哈哈

**Comment by AlexanderMisel** [comment]
暂时希望不要撰写这个条目。请大家对维基百科抱有信心。为了维基百科的质量，我们不能不加选择地收录条目。对于没有关注度或关注度有限的条目，我们不建议建立条目。由于大家在维基百科建立帐号只是为了宣传这款软件，我们会根据编辑倾向判定为傀儡或真人傀儡。不过主帐号应该是可以解封的，（只要不是来打广告，哈哈）。

**Comment by yeahwu** [comment]
楼上的应该是维基人员，俺也唠叨几句。
首先，这款软件是开源的。
其次，这是一款翻墙软件，也可以称为敏感软件。
再，这是唯一一款还活着的gae类翻墙工具。

--------------分割线

您说的知名度，在国内这类软件是注定没有知名度，有知名度的都“死”了。
比如，goagent，shadowsocks 这两个是很有名，但是已经停止维护了，具体原因，维基上也说得很清楚了。

其实写这个条目在大陆地区是比较困难的，首先你要翻墙，然后维基上撰写条目，IP还不能经常变换，这对翻墙写条目的大陆人是个大大的坎。
那俺们还为什么费劲地写这个条目？其实，很简单。让更多的能上维基百科，Google，YouTube。
参与写这条目的人，都是自愿的。完全没有利益接触。

俺们不是打广告，俺们只是一群理想主义者……
Alexander Misel <notifications@github.com>于2016年3月31日 周四11:48写道：

**Comment by AlexanderMisel** [comment]
嗯，我是维基人。很高兴维基百科在大家心目中还有一定地位。虽然你们可能是唯一，但很遗憾维基百科不认这个。我们会通过维基百科的关注度指引以及其他方针指引来判断是否可以收录某一条目。如果有一天XX-Net真的能达到我们的要求了，建立条目是完全允许的。不过在这之前，希望你们是在别的网站（或是Wiki类型的，或不是）对你们的开源软件进行宣传，以获得可靠来源的关注。另一方面，中文维基百科目前本身就是墙外网站，能够访问我们网站的应该已经有翻墙或是其他方法了，在维基百科上建立XX-Net的条目对推广的意义并不大。

**Comment by simonasd** [comment]
@AlexanderMisel 感谢您的解释。

请问是否可以先作为goagent的一个衍生项目（本项目最初确是衍生自goagent核心代码），添加在[goagent#派生项目](https://zh.wikipedia.org/wiki/GoAgent#.E8.A1.8D.E7.94.9F.E9.A1.B9.E7.9B.AE)段落中？从goagent的角度考虑，作为唯一一个尚在维护中的衍生品并在github有6K个star，应该是有资格列入介绍的吧？

您提到的关注度指引是指 [这篇指引](https://zh.wikipedia.org/wiki/Wikipedia:%E5%85%B3%E6%B3%A8%E5%BA%A6)吗？先学习了。

**Comment by AlexanderMisel** [comment]
对的，就是这个通用关注度指引（WP:GNG）。在goagnet派生项目中写一小段（不超过50字）我觉得是可以容忍的。但维基百科的其他巡查回退人员不一定也这么认为。记得附上github本身的来源。

**Comment by simonasd** [comment]
@AlexanderMisel 明白，谢谢解答。

**Comment by jzp820927** [comment]
IP都死绝了，写 wiki 也没啥意义了

**Comment by yeahwu** [comment]
@jzp820927 哎呦，不要老是这个死绝，那个死绝，你是不是才用gae呀？tm这ip也不是死了一次，两次了，不也活到现在。有心情说这风凉话，还是把你那在用的ip贡献出来给大家救救急不好吗？

**Comment by simonasd** [comment]
@jzp820927 怎么每个issue底下都有你（无奈.jpg）
