### ISSUE TITLE
用XX-NET智能代理后，非翻墙的网不能访问了

### ISSUE THREAD

**Issue by changshunxu520** [XX-net/XX-Net#2532]
用XX-NET智能代理后，非翻墙的网不能访问了，关闭智能代理退出XX-NET之后，停一小会就能访问了。后台日志好多fail time out 的日志

**Comment by jzp820927** [comment]
你是说的国内网站麽？

**Comment by changshunxu520** [comment]
是的，我在家里的一台电脑是可以的，但是在公司的那台电脑上就是不可以的。不知道  是为什么

**Comment by jzp820927** [comment]
用pac绕过非墙网站走代理，非墙网站也没必要走代理

**Comment by changshunxu520** [comment]
不知道什么原因，现在最新版本好了
