### ISSUE TITLE
一个小问题CUP识别错误，我是英特尔的识别成了AMD

### ISSUE THREAD

**Issue by ighack** [XX-net/XX-Net#2537]
一个小问题CUP识别错误，我是英特尔的识别成了AMD
不过不影响使用。东西还是非常好用的

**Comment by pingtouge** [comment]
我才发现。。。。。。。。。。。。

**Comment by wookongCN** [comment]
你说的是不是System Platform	 AMD64 
64位系统都是标记为amd啊，因为AMD64早，MS给AMD64开发了windows xp x64之后不想给intel再开发一个版本，intel也就拿着AMD64的用了,所以AMD64标识64位系统就成了行业默认

**Comment by CHN008** [comment]
对,楼上解答的是对的.

看来楼主不了解其中的内情啊

**Comment by o0TT0o** [comment]
学习了,我也一直以为是BUG = =..

**Comment by acrossabc** [comment]
哈哈，我以前也疑惑过，get
