### ISSUE TITLE
一直部署不成功

### ISSUE THREAD

**Issue by 18210165166** [XX-net/XX-Net#2540]
这是日志

Mar 29 16:36:47 - set proxy to http://127.0.0.1:8087 
Mar 29 16:36:47 - ============ Begin upload ============ 
appid:LuckyWannaBeee1018 

Mar 29 16:36:47 - Error parsing yaml file:
Unable to assign value 'LuckyWannaBeee1018' to attribute 'application':
Value 'LuckyWannaBeee1018' for application does not match expression '^(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{1,100}$'
in "C:\Users\lierl\Downloads\XX-Net-2.9.2\XX-Net-2.9.2\gae_proxy\server\gae\app.yaml", line 1, column 14
Mar 29 16:36:47 - Error parsing yaml file:
Unable to assign value 'LuckyWannaBeee1018' to attribute 'application':
Value 'LuckyWannaBeee1018' for application does not match expression '^(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{1,100}$'
in "C:\Users\lierl\Downloads\XX-Net-2.9.2\XX-Net-2.9.2\gae_proxy\server\gae\app.yaml", line 1, column 14
Mar 29 16:36:47 - Error parsing yaml file:
Unable to assign value 'LuckyWannaBeee1018' to attribute 'application':
Value 'LuckyWannaBeee1018' for application does not match expression '^(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{1,100}$'
in "C:\Users\lierl\Downloads\XX-Net-2.9.2\XX-Net-2.9.2\gae_proxy\server\gae\app.yaml", line 1, column 14
Mar 29 16:36:47 - =======================
Mar 29 16:36:47 - Deploy failed appid list:
Mar 29 16:36:47 - - LuckyWannaBeee1018
Mar 29 16:36:47 - == END ==

**Comment by jzp820927** [comment]
appid,不能有大写吧
