### ISSUE TITLE
所以現在是只有xxnet不能上嗎?

### ISSUE THREAD

**Issue by Exiaotian** [XX-net/XX-Net#255]
GoAgent FFGO 無界 自由門 都可以,只有xxnet還不行 @@

**Comment by Cat7373** [comment]
http://cat73.sinaapp.com/xx-net/good_ips_sort.html
自己用这工具挑出来IP然后临时用Goagent去了- -
XX-Net现在没法看一些网站的视频- -

**Comment by lg560852** [comment]
工具很好，如果能添加一个根据延迟排序功能就更好了。
另外，还缺一个逆向的，从gogotester导出为xx-net的good_ip.txt的工具

**Comment by Cat7373** [comment]
逆向有什么用处么?
谁会需要延迟巨高的IP

**Comment by kingour** [comment]
我是goagent今天出错了，找到这个的，goagent一直报405，用xxx-net就好了

**Comment by lg560852** [comment]
https://code.google.com/p/goagent/issues/detail?id=20406

**Comment by xxnet** [comment]
“从gogotester导出为xx-net的good_ip.txt的工具”

xx-net应该加一个导入ip的功能，至于格式，大家可以列一下什么形式方便。


2015-04-26 12:34 GMT-04:00 lg560852 <notifications@github.com>:

**Comment by Cat7373** [comment]
目前GogoTester的格式是跟Goagent一样的 IP|IP|IP
如果没有其他找IP的工具 那么这个格式就是最方便的了- -

**Comment by xxnet** [comment]
ok


2015-04-26 21:58 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by lg560852** [comment]
能否改改gogotest，那个工具测试完后就已经有了延迟和证书，只是没有导出来。

**Comment by Cat7373** [comment]
Gogo-Tester也是开源项目 当然可以改 - -
目前还在做XX-Net的IP导入导出- -
之后再看看吧- -

**Comment by xxnet** [comment]
可以把扫描的IP段导入也做好，就方便自己去找ip了。

2015-04-26 23:30 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
正在吃饭- -
吃完继续写- -

**Comment by xxnet** [comment]
吃饭的时候吃饭，睡觉的时候睡觉，这就是禅。

2015-04-27 0:24 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by nsonline** [comment]
我现在用Gogo-Tester一个ip都扫不出来了……
