### ISSUE TITLE
突然就不能用了，再上传ID也传不上了

### ISSUE THREAD

**Issue by bluelines** [XX-net/XX-Net#258]
Apr 27 10:26:54 - ============  Begin upload  ============
appid:*****

Apr 27 10:26:54 - Application: *****
Apr 27 10:26:54 - Host: appengine.google.com
Apr 27 10:26:54 - Rolling back the update.
Apr 27 10:26:54 - Error 403: --- begin server output ---
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/errors/logo_sm_2.png) no-repeat}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/errors/logo_sm_2_hr.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:55px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/_gh/</code> from this server.  <ins>That’s all we know.</ins>
--- end server output ---

**Comment by xxnet** [comment]
google 的ip被调整了，之前是gws，后来变成gvs了。新版有做处理。
不过1.9.4相对稳定些

2015-04-26 22:34 GMT-04:00 bluelines <notifications@github.com>:

**Comment by xxnet** [comment]
请用最新版 1.12.0
