### ISSUE TITLE
访问谷歌 504

### ISSUE THREAD

**Issue by GitFuture** [XX-net/XX-Net#2591]
-----------
问题描述：
访问Twwiter没问题，但是访问谷歌就是504GAEProxy proxy Time out。
时常掉线，屏蔽状态有时候会倒计时
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: get_version_fail
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:3000 good:1793
network-status: OK
connected-link: new:0 used:2
scan-ip-thread-num: 49
ip-quality: 459
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by wialny** [comment]
同, 
www.google.com 504
www.google.com.hk 504 
www.google.com.tw 正常
www.google.co.jp 要求机器人验证, 确认后正常

其他网站似乎也都没问题, 只是现在可用ip较少, 访问有点慢而已.

**Comment by exsystem** [comment]
同, 
www.google.com 504
www.google.com.hk 504 
www.google.com.tw 正常
www.google.co.jp 要求机器人验证, 确认后正常

**Comment by wialny** [comment]
@exsystem 今天我这里全部都504了

**Comment by GitFuture** [comment]
表示google.co.jp还能用

**Comment by decemer** [comment]
www.google.com不能,其他3个都能,不过都很慢啊
