### ISSUE TITLE
自动扫描可用ip的功能怎样用于修改hosts文件？

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#2596]
用xx-net自动修改ip的功能将自动修改hosts文件里的ip地址，这样在使用switchy omega时可以直接用hosts文件连接google的网站。

**Comment by jzp820927** [comment]
好像XX没这个功能

**Comment by fengixng** [comment]
扫描出来的IP，证书是*.google.com的你可以手动替换hosts

**Comment by taoist1994** [comment]
我觉得xx-net自动修改iplist的功能很好用，希望作者能移植出自动修改hosts文件里的ip功能。 @xxnet

**Comment by jzp820927** [comment]
IP都死绝了，已经没有意义了
