### ISSUE TITLE
不能识别密码中的特殊字符

### ISSUE THREAD

**Issue by ryRubyy** [XX-net/XX-Net#26]
当密码中含有特殊字符的时候，上传会失败。显示签名错误。

**Comment by xxnet** [comment]
收到，忘记给密码进行编码了。

**Comment by ryRubyy** [comment]
另外话说GAE密码直接明文写入配置......

**Comment by xxnet** [comment]
这个密码其实价值不大，GAE的appid本身能猜到就不容易，猜到了也无所谓，就是被用掉一点流量，多申请几个就好了，真没有必要设置密码

**Comment by ryRubyy** [comment]
好的,望修复主要的一个issue.这款软件很好用也很方便,就是墙高了......

另,请问如何自行升级G0Agent,旧版本的ga下载不到,传送不了server

**Comment by xxnet** [comment]
“请问如何自行升级G0Agent,旧版本的ga下载不到,传送不了server”
不明白，请解释详细

**Comment by ryRubyy** [comment]
很抱歉让你产生误会.我指的是在无法通过XX-Net直接上传服务端(由于本issue)时,无法下载到与当前xx-net中的ga的相同版本goagent,从而无法上传当前版本的客户端以供xx-net使用.希望能够提供让用户自行升级goagent的方法.谢谢.

**Comment by xxnet** [comment]
cd XX-Net/goagent/3.1.34/server
python uploader.py <appids> <email> [password]

密码可以在命令行中输入，也可以不填，执行后会提示输入，这样就不用担心特殊字符了。

如果是Windows，就执行:
uploader.bat <appids> <email> [password]


代码不复杂，如果会编程，仔细看看源码就能猜到大概了，
这也是开源的最大好处。

**Comment by xxnet** [comment]
能否告知是哪个特殊字符？我这边在调试

**Comment by ryRubyy** [comment]
很抱歉因为开学没有看GH。特殊字符是“#”。

**Comment by xxnet** [comment]
好的，我研究下。

**Comment by xxnet** [comment]
在windows /linux下试过，#字符可以正常传递
