### ISSUE TITLE
请教楼主goagent  单独这个包中的功能有IP自动扫描过滤的功能吗？？？

### ISSUE THREAD

**Issue by hehh2001** [XX-net/XX-Net#260]

**Comment by xxnet** [comment]
有的，可以把它的操作暴露出来：
  怎么设置扫描ip的范围，
  导入ip
  导出ip

**Comment by hehh2001** [comment]
万分感 谢 ！！！ 想用这个替换原版。一直用原版的GOAGENT+IPV6+GoGoTest    最近太烦了，扫出来的IP 用不到两天就挂了。墙越来越高，原版的也很久没更新了，一路追到你这。我是在ARCHLINUX下跑的，XFCE4的桌面，原版我自定义了一个终端来显示输出状态。你这缺少教程啊，对我等菜鸟来说有点难度，试用了一下，感觉还不错。提个小小建议，如果加入IPV6功能就好了，曾经有断时间IPV6就足以搞定一切，想必筑墙的成本及技术难度要比IPV4要大。还有个问题想问一下，你里面的goagent版本号是在原版 3.2.3的基础上改的吗？和原版的关系是什么？感觉你也是原版的开发者，原版你不再维护了是吗？

**Comment by xxnet** [comment]
ipv6的用户少，影响小，不是重点目标。
ipv6需要有环境测试，希望有环境、有能力的网友贡献补丁，其实需要写的代码并不多。

优先能够软件解决的问题，就不要留给教程。

教程也确实是缺，刚写里一份待写的教程列表：
https://github.com/XX-net/XX-Net/wiki/Todo-Wiki
希望有能力的人，去帮忙写一些，慢慢积累就多了。

**Comment by q1728576493** [comment]
用gogo tester 跑出来的IP210.242.125.34|193.120.166.95|77.66.9.113|85.182.250.25|31.209.137.31|77.66.9.91|223.26.69.46|62.1.38.84|173.194.123.123这样格式的如何使用？

**Comment by superjyq** [comment]
能用ipv6就好了，看视频会非常快

**Comment by hehh2001** [comment]
还是版本的问题，在linux下我用1.9.4的版本无任何问题，没有报错，要装python2-notify包

**Comment by xxnet** [comment]
找到问题了，我一会发新版

在 2015年4月27日 上午4:32，he <notifications@github.com>写道：

**Comment by xxnet** [comment]
@q1728576493 
 1.12.0 版本发布，UI上有导入ip功能

**Comment by hehh2001** [comment]
感谢，已更新，这几天墙越来越高了。
