### ISSUE TITLE
gae残遭灭门，俺来救火，下面ip段替换原本ip段，应该可以扫到一两百ip

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2603]
[ip_range.txt](https://github.com/XX-net/XX-Net/files/199536/ip_range.txt)

替换， XX-Net/gae_proxy/local/ip_range.txt 文件
建议删除data文件，重新扫。
提醒一下这是救急方案，总ip数只有3w多，等高压期过了，大家可换回原来ip段。

**Comment by jzp820927** [comment]
怕这次是永久性的了，不会恢复了。

**Comment by yeahwu** [comment]
不要这么悲观，总有办法滴

**Comment by redfrog999** [comment]
我这边的烂网络赛风和蓝灯一直可用的。不用灰心，办法总比困难多滴。云平台什么的都可以用起来。

**Comment by redfrog999** [comment]
新的IP Range很有用嘛，现在基本又恢复到满速状态了。

**Comment by sosmygirl** [comment]
前几天的3000高速ip是回光返照啊

**Comment by yeahwu** [comment]
另外大家有贡献ip段的请在下面留言，到时一并加上去，希望大家同舟共计，抵御GFW

**Comment by Cat7373** [comment]
我的可用IP掉到9个- -
然后各种不能用- -

**Comment by Cat7373** [comment]
这是出什么事了- -

**Comment by yeahwu** [comment]
@Cat7373 试试上面的ip段，扫的时候建议降低线程数，

**Comment by Cat7373** [comment]
一般平时都只用1个扫描线程- -
不能用了最多加到5个- -

**Comment by Cat7373** [comment]
扫到了第一个可用IP- -
以前的全都删了- -

**Comment by yuiwong** [comment]
虽然不明白原理，不过很有用。感谢

**Comment by Cat7373** [comment]
我想知道出什么事了，突然封了这么多- -

**Comment by zaney** [comment]
貌似好像活了点。。。

**Comment by Jankst** [comment]
我是直接把这个IP段给添加了，添加前有50多个可用IP，添加后正在扫描。这样之前的IP还是能用的

**Comment by brcm** [comment]
有所缓解了

**Comment by yeahwu** [comment]
@Cat7373 破墙改变封锁策略，尝试识别封杀所有带sffe服务器类型的ip字段。这次是搞得有点狠鸟

**Comment by konoha0723** [comment]
按照方法做了至少能看了，感谢，，，虽然还是没到10不过我已经满足了QAQ

**Comment by yeahwu** [comment]
扫几个小时，应该能有100来个。

**Comment by konoha0723** [comment]
话说为啥我的ip延迟有451那么高。。。

**Comment by yeahwu** [comment]
都tm到生死存亡的关口鸟，还挑食

**Comment by konoha0723** [comment]
不不，我只是问问。。。估计也和我网速差有关，能看油管我已经很满足了

**Comment by aceslup** [comment]
我只是为了看点英文文档，今天中午封死我。哎，感谢分享方法。

**Comment by jeromeli002** [comment]
怎么做到的 貌似好了点，这也不是长久之计啊啊啊

**Comment by CHN008** [comment]
感谢! 换了这个IP段正常了

状态

属性	值
本地网络状态	OK
IP数量	6
IP延迟	1836
连接池(帮助)	新:0 已用:3
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	0
屏蔽状态(帮助)	OK

扫描IP线程数(设置)	那里选了 **自动调整扫描线程数**
结果扫描IP线程数(设置)	显示为**0** ,如果取消那个自动调整扫描线程数就正常的

-2.9.6版的

**Comment by yeahwu** [comment]
线程数建议设置20或者30,这样不容易漏掉可用ip

**Comment by cacerlly** [comment]
请问扫描是什么意思？怎么操作？原谅我是个网络小白。。。

**Comment by yeahwu** [comment]
用这个文件，替换相同文件就好鸟。

**Comment by wuwuwuxxx** [comment]
感谢，翻个墙容易吗

**Comment by cacerlly** [comment]
@yeahwu  
原PO说替换掉文件之后，重新扫描，还建议重新删掉data文件夹。我不太明白扫描是啥意思，我把安装文件夹里面的文件替换掉了也还是连不上。。。

**Comment by kexul** [comment]
好慢。。。连接池1/50，吓得我换了个lantern。。。

**Comment by hawk119007** [comment]
试了 还是卡  赶紧买了个VPN以防万一

**Comment by LLLX77** [comment]
感谢，又能用了，不过不知道能撑到什么时候，GFW（后面的） 先倒还是我先倒呢。。。

**Comment by yeahwu** [comment]
这种情况去年也有过，只是暂时的。过段时间就好鸟

**Comment by Loyalists** [comment]
非常感谢，有用！不过这种情况去年7月的时候也出现过一次。

**Comment by myxvisual** [comment]
谢谢了 不错可以用

**Comment by pm19960106** [comment]
要删除data文件夹吗

**Comment by GoldenDewitt** [comment]
谢谢！

**Comment by sun3596209** [comment]
感谢Y大，可以用了

不需要删除data，只要在xx-net页面，高级--设置--IP段列表，替换为楼主附件的IP段就好

**Comment by lh471921250** [comment]
我现在的IP数是38个，是正常的吗，有时候谷歌搜索也不好用

**Comment by WLBF** [comment]
我说 怎么突然用不了google了，真是蛋疼

**Comment by nly4lov** [comment]
导入楼主提供的200个IP，然后仍然迅速降低数字，刚看了一眼都掉到40了
