### ISSUE TITLE
更新1.12.0后，Block依旧无限循环

### ISSUE THREAD

**Issue by Sherman-Liu** [XX-net/XX-Net#261]
地点：大连
接入商：大连教育网
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.12.0
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9

跑了几个循环了吧，问题照旧。可连接的IP始终为0,0.

1.9.4版本仍能正常工作，加入Block之后的新版本均无法使用。

无法上传BADIP文件内容，因为文件一直为空（0KB，无条目）。

还请开发者解惑......

**Comment by xxnet** [comment]
有没有bad_ip2.txt? 格式换了，文件名也换了。

2015-04-27 5:45 GMT-04:00 Sherman-Liu <notifications@github.com>:

**Comment by Sherman-Liu** [comment]
回开发者，说的就是这个文件。
![default](https://cloud.githubusercontent.com/assets/11748513/7345301/e9bac904-ed05-11e4-99fe-9fe9f20d6a65.PNG)

**Comment by Sherman-Liu** [comment]
而且为了确保问题能重现，刚才我在其他人的电脑上也进行了试验，同样是Block无限循环，怀疑是教育网的特殊性。

**Comment by xxnet** [comment]
刚发了1.12.1，你试试，我更新了ip库

在 2015年4月27日 上午5:50，Sherman-Liu <notifications@github.com>写道：

**Comment by Sherman-Liu** [comment]
( ⊙ o ⊙ )又有新版了......我先试试~~

**Comment by Sherman-Liu** [comment]
1.12.1：connected link 17,17 block stat OK

哭了，跪谢开发者.......虽然貌似没有1.9.4快.......但是能用了......谢谢......

**Comment by xxnet** [comment]
你可以把你用的 1.9.4的 data/goagent/good_ip.txt 拷贝到 1.12.1里去用

2015-04-27 5:53 GMT-04:00 Sherman-Liu <notifications@github.com>:

**Comment by Sherman-Liu** [comment]
好的~再次感谢~~辛苦了~~(╯3╰)

**Comment by Pd69bq** [comment]
1.12.1工作非常非常的好 恭喜xxnet有了新的突破 辛苦辛苦

**Comment by latrikcoasler** [comment]
善莫大yan
