### ISSUE TITLE
建议减少下Block时间

### ISSUE THREAD

**Issue by ehfwoievbewoig** [XX-net/XX-Net#262]
一Block就是5分钟，感觉有点太长了，不知道Block到底是怎么判断的？
如果是连续几个IP无法连接就Block，那可以5分钟内不连接这些IP嘛，为啥一定要5分钟内不去连接。
减少到1分钟感觉也好一些，有时候一打开就是Block，过上半个小时还在Block，完全不知道要怎么用

**Comment by xxnet** [comment]
你可以试试修改 goagent/x.x.x/local/connect_control.py 里面：
block_delay = (60 * 5)  <- 单位是秒

1.12.1 已经修改了机制，在无法翻墙1分钟后，才进入Block。比之前容易误入要好很多。

在 2015年4月27日 上午6:59，ehfwoievbewoig <notifications@github.com>写道：

**Comment by think2011** [comment]
@xxnet 新版本恢复正常了，谢谢！

**Comment by superjyq** [comment]
经过我试验了一段时间，新版本仍然是由问题的。

block整个的思路就是错的

如果有10个ip可用，经过一段时间的运行，通通都会被block了，然后就不能翻墙了

整个代码的思路都是错的

**Comment by yfdyh000** [comment]
其实，我也感觉block这个设计思路很怪，不知道是怎么得出的问题由“蜜罐”引起这个结论。

**Comment by xxnet** [comment]
只能说是猜测，而且做实验也验证有效，可惜全国网络条件差别很大，各地区都不相同

在 2015年4月28日 上午10:55，YFdyh000 <notifications@github.com>写道：
