### ISSUE TITLE
MAC上使用xx-net，出现以下错误，救助！openssl应该没装错啊

### ISSUE THREAD

**Issue by windfantacy** [XX-net/XX-Net#2622]
Apr 02 13:51:26.111 - [INFO] start XX-Net get_version_fail
Apr 02 13:51:26.112 - [DEBUG] start confirm_xxnet_exit
Apr 02 13:51:26.114 - [DEBUG] good, xxnet:8087 cleared!
Apr 02 13:51:26.116 - [DEBUG] good, xxnet:8085 clear!
Apr 02 13:51:26.116 - [DEBUG] finished confirm_xxnet_exit
Apr 02 13:51:26.133 - [ERROR] start module gae_proxy fail:dlopen(/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so
  Reason: image not found
Apr 02 13:51:26.135 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/apple/Downloads/XX-Net-2.9.6/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/apple/Downloads/XX-Net-2.9.6/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/Users/apple/Downloads/XX-Net-2.9.6/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/Users/apple/Downloads/XX-Net-2.9.6/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
ImportError: dlopen(/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so
  Reason: image not found

Traceback (most recent call last):
  File "launcher/start.py", line 135, in <module>
    main()
  File "launcher/start.py", line 110, in main
    module_init.start_all_auto()
  File "/Users/apple/Downloads/XX-Net-2.9.6/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/Users/apple/Downloads/XX-Net-2.9.6/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/apple/Downloads/XX-Net-2.9.6/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/Users/apple/Downloads/XX-Net-2.9.6/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/Users/apple/Downloads/XX-Net-2.9.6/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
ImportError: dlopen(/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so
  Reason: image not found
Stopping all modules before exit!
Apr 02 13:51:26.136 - [ERROR] stop module gae_proxy fail:'imp'
Apr 02 13:51:26.136 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/apple/Downloads/XX-Net-2.9.6/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by cc941201** [comment]
XX-Net只在OS X自带的Python上测试过，看起来是Anaconda造成的问题

**Comment by windfantacy** [comment]
请问怎么解决呢？

**Comment by cc941201** [comment]
可以试试把start.command中的python替换为指向系统python的绝对路径

**Comment by noveleven** [comment]
pyopenssl装没装成功，终端运行一下apple$ python >>>import OpenSSL就知道了，看错误输就是python执行import的时候出的问题。
我猜应该是export的问题，重建软连接试试
$ sudo rm /usr/lib/libssl.1.0.0.dylib
$ sudo rm /usr/lib/libcrypto.1.0.0.dylib
$ sudo ln -s /Users/apple/anaconda/lib/libssl.1.0.0.dylib /usr/lib
$ sudo ln -s /Users/apple/anaconda/lib/libcrypto.1.0.0.dylib /usr/lib

**Comment by cc941201** [comment]
/usr/lib是SIP保护区域，不建议修改，否则可能影响别的程序。自己装的东西尽量放在/usr/local中，最好用homebrew之类的软件包管理器

**Comment by windfantacy** [comment]
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
ImportError: dlopen(/Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/apple/anaconda/lib/python2.7/site-packages/OpenSSL/rand.so
  Reason: image not found
>>> 
NeodeMacBook-Air:~ apple$ sudo rm /usr/lib/libssl.1.0.0.dylib
Password:
rm: /usr/lib/libssl.1.0.0.dylib: No such file or directory
NeodeMacBook-Air:~ apple$ $ sudo rm /usr/lib/libcrypto.1.0.0.dylib
-bash: $: command not found
NeodeMacBook-Air:~ apple$ sudo rm /usr/lib/libcrypto.1.0.0.dylib
rm: /usr/lib/libcrypto.1.0.0.dylib: No such file or directory
NeodeMacBook-Air:~ apple$ $ sudo ln -s /Users/apple/anaconda/lib/libssl.1.0.0.dylib /usr/lib
-bash: $: command not found
NeodeMacBook-Air:~ apple$ sudo ln -s /Users/apple/anaconda/lib/libssl.1.0.0.dylib /usr/lib
ln: /usr/lib/libssl.1.0.0.dylib: Operation not permitted
NeodeMacBook-Air:~ apple$ sudo ln -s /Users/apple/anaconda/lib/libcrypto.1.0.0.dylib /usr/lib
ln: /usr/lib/libcrypto.1.0.0.dylib: Operation not permitted
NeodeMacBook-Air:~ apple$

**Comment by windfantacy** [comment]
一条也执行不了

**Comment by windfantacy** [comment]
cc941201 commented 8 minutes ago
可以试试把start.command中的python替换为指向系统python的绝对路径

cd "$(dirname "$0")"
/usr/bin/env python2.7 launcher/start.py

怎么改呢？

**Comment by cc941201** [comment]
@windfantacy 第二行换成`/usr/bin/python launcher/start.py`
我现在不在电脑旁边，系统python应该在这个路径，我不太确定。

**Comment by windfantacy** [comment]
cc941201 commented 5 minutes ago
@windfantacy 第二行换成/usr/bin/python launcher/start.py
我现在不在电脑旁边，系统python应该在这个路径，我不太确定。

果然可以了！！！
谢谢！
