### ISSUE TITLE
MD，俺看这是gae类极限鸟，这次封ip封得也太狠鸟

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2626]
![2016-04-02 16 08 03](https://cloud.githubusercontent.com/assets/13328328/14225230/81e8ca98-f8ed-11e5-968c-90f6a190092c.png)

**Comment by noveleven** [comment]
用的人多鸟，自然就封鸟

**Comment by simonasd** [comment]
我虽然还能用，但IP也是大幅度下降。不知道这次封锁能支撑多久，难道又更新了一大批设备，提升了黑名单的容量？

**Comment by angle1895** [comment]
![qq 20160402181148](https://cloud.githubusercontent.com/assets/4709543/14225703/c4f8df4c-f8fe-11e5-9e39-c7dda237d94f.png)

**Comment by jzp820927** [comment]
500+kb 就不错了，俺这儿也就 50+kb
