### ISSUE TITLE
请楼主解释一下部署是目的？

### ISSUE THREAD

**Issue by latrikcoasler** [XX-net/XX-Net#263]
部署是有什么用的？在配置自己的appid之后，怎样知道是否还需要重新部署？

**Comment by latrikcoasler** [comment]
Property	Value
Sys Platform	win32
OS System	Windows
OS version	5.1.2600
OS release	XP
OS detail	Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.12.1
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2991
connected link	0,0
ip-connect-interval	10
block stat(帮助)	OK


再次完全失败。是不是重新找到google ip地址就好？

**Comment by xxnet** [comment]
GoAgent是利用Google的App Engine服务作为代理，进行翻墙的。
我们需要在GoogleAppEngine上放代理的代码，才能使用。
  部署，就是把服务端的程序上传上去。

2015-04-27 9:33 GMT-04:00 latrikcoasler <notifications@github.com>:

**Comment by latrikcoasler** [comment]
是不是connected link项要处于非０状态才可以部署？而该项是否为０是不是取决于可用的google ip，如果是的话，那是不是最好每次使用前都导入gogotester搜索出来的可用ip?

**Comment by xxnet** [comment]
1.导入1次就好了，下次启动数据还在。
2. 部署前，请先在浏览器里访问appengine.google.com，看能否正常访问。
  因为如果你只启动XX-Net，没有访问过任何网站，connected link 是有可能为0的。


在 2015年4月27日 上午10:02，latrikcoasler <notifications@github.com>写道：

**Comment by latrikcoasler** [comment]
不行啊，楼主，导入再多ＩＰ，connect link最多时达到十几个，但只能持续十分钟，然后归０，然后就是不停的等。

**Comment by xxnet** [comment]
重启XX-Net，能恢复工作吗？

在 2015年4月27日 上午11:18，latrikcoasler <notifications@github.com>写道：

**Comment by latrikcoasler** [comment]
在重新导入新的ＩＰ后可以了，估计是不是被封的问题。请问直接换ＩＰ池的文件夹在哪里？

**Comment by xxnet** [comment]
goagent/x.x.x/local/ip_range.txt

在 2015年4月28日 上午6:04，latrikcoasler <notifications@github.com>写道：

**Comment by xxnet** [comment]
新版UI可以修改IP池了
