### ISSUE TITLE
google账户登不上

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#2631]
---

问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

---

诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 525
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 100
ip-quality: 9999
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by andylee1890** [comment]
Apr 02 17:41:52 - ============ Begin upload ============ 
appid:test002-1176 

Apr 02 17:41:52 - Application: test002-1176
Apr 02 17:41:52 - Host: appengine.google.com
Apr 02 17:41:52 - Rolling back the update.
Apr 02 17:42:12 - upload fail: The read operation timed out

**Comment by noveleven** [comment]
connected-link: 0 / 0
ip-quality: 9999
延迟太高，无法建立链接，高级-检查所有ip-运行，然后就等xx自己扫描新ip并添加到good_ip里面。

**Comment by jzp820927** [comment]
删除 data 重新扫描所有IP
