### ISSUE TITLE
救火，第二季    保守可用ip为200+

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2636]
[ip_range.txt](https://github.com/XX-net/XX-Net/files/200810/ip_range.txt)

增加了一些ip段，谢谢大家的贡献
替换， XX-Net/gae_proxy/local/ip_range.txt 文件
建议删除data文件，重新扫。
或者在web ui页面，高级--设置--IP段列表，替换为附件的IP段也行

提醒一下这是救急方案，总ip数只有3w多
@Cat7373 @xyuanmu

**Comment by xyuanmu** [comment]
其实这两天蓝灯速度还是不错的，我都是用它来看视频的，其他依然走gae

**Comment by yeahwu** [comment]
lantern的速度，俺这边不行，连上星岛基本上就萎了，
另外goproxy的php模式，在linux上比win上面慢好多，这两天也只有看看网页了。

**Comment by noveleven** [comment]
挂了1个小时效果很不错

**Comment by 935352** [comment]
谢谢咯

**Comment by marsrabel** [comment]
文件在哪？没找到下载的地方呀

**Comment by marsrabel** [comment]
哦哦 看到了 忽略 忽略

**Comment by yeahwu** [comment]
@xyuanmu  你的扫ip工具，格式转换好像不灵了，在win和linux上都试过。
@935352  不客气

**Comment by Cat7373** [comment]
我的理念是，有几个能用的就成- -
看到有效IP到了30多个就把扫描线程改成1惹- -
现在60多个惹- -

**Comment by heiheihei120** [comment]
# !!谢谢啦  非常时期真不容易 感谢楼主救火

**Comment by marsrabel** [comment]
我扫了一遍 只有7个有效 好蛋疼

**Comment by CHN008** [comment]
非常感谢分享,第一个的IP段还很给力;这个下载作为备份吧.

**Comment by zaney** [comment]
多谢

**Comment by hrerse** [comment]
我这儿蓝灯过个几分钟就断一下，又要重新连接，真是蛋疼

**Comment by GoForFree** [comment]
非常感谢，虽然ip数量只有100上下，但是终归是能用了，真的无以言谢

**Comment by fykwgl** [comment]
已添加，顺便求x-tunnel流量，fykwgl@gmail.com。@yeahwu

**Comment by lubenjie** [comment]
hi, 没找到文件？

**Comment by lubenjie** [comment]
粗心！ 惭愧！

**Comment by marsrabel** [comment]
找到了找到了 多谢

2016年4月3日星期日，lubenjie <notifications@github.com> 写道：

**Comment by yewei9390** [comment]
好多谢，宜家满血复活

**Comment by Vanjwu** [comment]
只能说感谢

**Comment by wangrk** [comment]
非常感谢 差点以为把所有ip都封了

**Comment by panzer1313208** [comment]
@yeahwu @Cat7373 @xyuanmu 以后有事能不能也艾特@一下我？

**Comment by yeahwu** [comment]
@panzer1313208 好说，好说。主要是你这名难记，呵呵

**Comment by xiaodongQ** [comment]
不得不说声谢谢

**Comment by vcteps** [comment]
@yeahwu 请教IP段如何搜寻，试过dig工具，不太理想

**Comment by hzc-citrus** [comment]
不得不说声谢谢。。试了一下暂时能用了

**Comment by cchenmx** [comment]
可用，谢谢。

**Comment by sokis** [comment]
非常感谢。

**Comment by simonasd** [comment]
我这边的isp似乎有解锁的迹象，这两天每天都能扫到好几十个，可用的已经有三五百个了，速度已经回归。

**Comment by jzp820927** [comment]
如果是 XX 自带 IP 段文件有解锁的 IP，才是解锁，第三方的，一直都有 IP 可用
