### ISSUE TITLE
就用了2小时

### ISSUE THREAD

**Issue by emon100** [XX-net/XX-Net#264]
所在地：广东省深圳市
运营商：电信
XX-Net版本：1.12.1
系统版本：Windows8.1 x64
bad_ip.txt内容：
64.233.162.86
64.233.162.87
193.192.226.152
77.66.9.88
64.233.162.84
194.78.99.84
31.7.160.237
210.242.125.24
1
5
41.201.164.34
95.143.84.174
197.84.128.50
4
77.66.9.91
9
212.188.7.45
210.242.125.34
93.183.211.230
93.183.211.234
210.242.125.59
95.143.84.148

**Comment by superjyq** [comment]
这个识别bad ip的机制是错误的

开始用的好好的，然后不断有ip被识别为bad ip，不断block

最后就没有一个ip能用了

**Comment by xxnet** [comment]
好的，把无证书时的判读去掉，看看效果能不能好点。
 新版 1.12.2

在 2015年4月27日 下午3:11，superjyq <notifications@github.com>写道：

**Comment by xxnet** [comment]
新版已恢复可用
