### ISSUE TITLE
关于这次针对xx列表进行封锁，大家怎么看？下一步怎么走？

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2645]
RT
就不一一召唤鸟！大家畅所欲言

**Comment by breakwa11** [comment]
貌似我能用啊

**Comment by pm19960106** [comment]
要是能像类似TOR那样就好了

**Comment by yeahwu** [comment]
根据观察，除去xx列表的ip段，其它ip段基本还能扫出ip，唯独xx内置ip段，几近全灭。有理由怀疑这是一次针对性的封锁。
当然可能各地封锁状况不一，即使能用ip也很少了。
下一步是替换ip列表？还是改变作战方向？

**Comment by breakwa11** [comment]
我这有30+个有效IP

**Comment by yeahwu** [comment]
30+太少了，正常情况下至少要2.3百个有效ip备选，才能保证延时

**Comment by pm19960106** [comment]
替换感觉总不是办法

**Comment by drg78rgjui** [comment]
虽然我是用goa的，也说一下我的经验。

首先，只扫到极少ip，10几个，而且延时偏高的情况下，XX的扫描线程就应该自动提高，可以提高到200-300。
其次，如果依然无法连接，应该提供一个选项，就不要再扫内置那点可怜的ip库了！！！应该让使用者选择随机扫描亚洲或欧洲、美洲某个国家的全部ip，例如随机扫描日本的全部ip。

**Comment by iceflame89** [comment]
有谁了解Google的IP策略吗，ipv4 资源这么有限，google也不大可能大范围的随机ip，估计就那么些有限的段里。google ipv6自由度大很多吧， 封锁成本应该更高, 无奈教育网外没法普及

**Comment by iceflame89** [comment]
都搞物联网了，ipv6还不赶紧跟上，希望早日出个支持ipv6的运营商

**Comment by yfdyh000** [comment]
IPv6可以用6to4/ISATAP/Teredo等隧道。

**Comment by drg78rgjui** [comment]
@yeahwu 
另：有没有可能推出“分布式扫描”的计划？
考虑到github未被墙，开一个新repositories，维护一份可用ip列表，XX的用户一开软件自动下载这个列表，自动加ip。
至于分布式方面的细节，在内置ip不可用、延时太高的情况下，或者即使在可用，不需要扫描的情况下，XX的用户被随机分配到一个国家的全部ip，开始扫描，（这点最容易实现了，只要在XX软件包附带全球42亿ip即可），扫描出的结果会上传更新到那份可用ip列表，让别的XX用户下载（这点最难，我没想到有什么经济的方式实现的办法，也许邮箱？）

**Comment by zjhzxhz** [comment]
@xxnet 最近勾搭妹纸都不搭理我们了~
我记得上次被封的时候版本号从1.0升级到了2.0. 改进了一下策略.
上次的改进是什么?

**Comment by zjhzxhz** [comment]
教育网表示毫无压力。
![screen shot 2016-04-03 at 08 44 43](https://cloud.githubusercontent.com/assets/1730504/14229968/a4d2dba8-f978-11e5-948a-e7cb4c1d47d0.png)

BTW，如果你们天真地认为IP v6没有墙的话你们就错了。
![screen shot 2016-04-03 at 08 45 51](https://cloud.githubusercontent.com/assets/1730504/14229970/b65aac2a-f978-11e5-9e8b-544f5e7d4dfc.png)

**Comment by N46AN** [comment]
ipv6 几年前还是没墙的

**Comment by GoForFree** [comment]
说明加大投资建了起来呗，想当年纳粹不也是给犹太人建材让犹太人自己吧集中营造了出来，最后怎么样大家都知道，那些帮政府干活的，我已经找不到什么预言来斥责他们了

**Comment by GoForFree** [comment]
我就纳闷，为什么我们就出不了一个斯诺登

**Comment by jzp820927** [comment]
可惜 IPV6，一般人也用不了

**Comment by zjhzxhz** [comment]
@jt6562 
就算没有IP v6, IP v4也是妥妥的~

**Comment by xiuluo** [comment]
@zjhzxhz 我们学校的IPv6可以正常上谷歌，ping平均在120左右。

**Comment by iceflame89** [comment]
最大的问题在于，我们在明gfw在暗，我们在这讨论的任何策略都更佳容易被应对

**Comment by zjhzxhz** [comment]
@xiuluo 
我有一个在科大的同学说他们的IPv6也是正常的~ 
但是我这边就妥妥的被墙呀~ Orz

**Comment by zjhzxhz** [comment]
@yeahwu 
我是不是应该早点发出来 然后你们好去丢鞋子😊
![screen shot 2016-04-03 at 23 03 43](https://cloud.githubusercontent.com/assets/1730504/14233072/603a602e-f9f0-11e5-962f-eaf1bad0e3f1.png)

**Comment by yeahwu** [comment]
老方楼下的

**Comment by xiuluo** [comment]
@zjhzxhz 这今天都在用ipv6模式，虽然连接多，但是网速满多了

**Comment by zjhzxhz** [comment]
@xiuluo 
我只有寝室有IPv6，实验室只有IPv4。
网速的确有下降，但是也还OK。看网页还是挺溜的~
