### ISSUE TITLE
最近怎么好多403

### ISSUE THREAD

**Issue by tj8m23le** [XX-net/XX-Net#265]
403. That’s an error.

Your client does not have permission to get URL /_gh/ from this server. That’s all we know.

错误如上

**Comment by xxnet** [comment]
请问你是否升级最新版本，这个问题之前有解决过了

2015-04-27 21:53 GMT-04:00 tj8m23le <notifications@github.com>:

**Comment by tj8m23le** [comment]
好像不是版本的事，我从1.92到最新的1.12.2都有这个问题 以前没事 突然出现的

**Comment by tj8m23le** [comment]
Apr 28 12:50:52 - [DEBUG] network is ok
Apr 28 12:50:52 - [DEBUG] ssl conn_num:0
Apr 28 12:50:52 - [DEBUG] sort ip time:6
Apr 28 12:50:52 - [DEBUG] get ip:216.239.38.123 t:550
Apr 28 12:50:53 - [DEBUG] get ip:208.117.229.73 t:1116
Apr 28 12:50:53 - [DEBUG] get ip:216.58.216.245 t:1116
Apr 28 12:50:53 - [DEBUG] create_ssl update ip:216.239.38.123 time:490
Apr 28 12:50:53 - [DEBUG] get ip:216.58.220.153 t:1116
Apr 28 12:50:54 - [DEBUG] get ip:123.205.250.102 t:1116
Apr 28 12:50:54 - [DEBUG] get ip:95.54.196.215 t:1116
Apr 28 12:50:54 - [DEBUG] get ip:216.58.220.147 t:1116
Apr 28 12:50:54 - [DEBUG] create_ssl 208.117.229.73 fail:timed out c:0 h:0
Apr 28 12:50:54 - [DEBUG] fetch gae status:403 url:http://wikiwiki.jp/kancolle/
Apr 28 12:50:54 - [INFO] GAE t:1967 s:1447 403 http://wikiwiki.jp/kancolle/
Apr 28 12:50:54 - [DEBUG] create_ssl 216.58.216.245 fail:timed out c:0 h:0
Apr 28 12:50:54 - [DEBUG] network is fail
Apr 28 12:50:54 - [DEBUG] report_connect_fail network fail
Apr 28 12:50:55 - [DEBUG] create_ssl 216.58.220.153 fail:timed out c:0 h:0
Apr 28 12:50:55 - [DEBUG] report_connect_fail network fail recently
Apr 28 12:50:55 - [DEBUG] network is ok
Apr 28 12:50:55 - [DEBUG] create_ssl 123.205.250.102 fail:timed out c:0 h:0
Apr 28 12:50:55 - [DEBUG] report_connect_fail network fail recently
Apr 28 12:50:55 - [DEBUG] create_ssl 95.54.196.215 fail:timed out c:0 h:0

**Comment by standritsu** [comment]
我最近这两个版本也是403问题严重

**Comment by xxnet** [comment]
是google的ip作了调整了，以前可以访问gae的ip，现在不行了。

后面会发新版修复这个问题

2015-04-28 1:55 GMT-04:00 standritsu <notifications@github.com>:

**Comment by y9ykid** [comment]
同样的问题,关注后续版本能否有灵活的方式进行可访问gae的ip调整;

**Comment by xxnet** [comment]
之前Server为gws的ip，都可以作为GAE服务使用，现在不行了，会返回403，要研究看看

在 2015年4月28日 下午9:24，Leo <notifications@github.com>写道：

**Comment by hehh2001** [comment]
Apr 29 10:41:07 - [DEBUG] ssl conn_num:0
Apr 29 10:41:22 - [DEBUG] create ssl timeout fail.
Apr 29 10:41:22 - [DEBUG] create_ssl_connection fail
Apr 29 10:41:22 - [DEBUG] ssl conn_num:0
Apr 29 10:41:36 - [INFO] GAE CONNECT encrypted.google.com:443 
Apr 29 10:41:36 - [INFO] GAE CONNECT encrypted.google.com:443 
Apr 29 10:41:37 - [DEBUG] create ssl timeout fail.
Apr 29 10:41:37 - [DEBUG] create_ssl_connection fail
Apr 29 10:41:37 - [DEBUG] ssl conn_num:0
Apr 29 10:41:38 - [DEBUG] ssl conn_num:0
Apr 29 10:41:52 - [DEBUG] create ssl timeout fail.
Apr 29 10:41:52 - [DEBUG] create_ssl_connection fail
Apr 29 10:41:52 - [WARNING] gae_exception:GAE_Exception() http://www.secretchina.com/
Apr 29 10:41:53 - [DEBUG] create ssl timeout fail.
Apr 29 10:41:53 - [DEBUG] create_ssl_connection fail
Apr 29 10:41:53 - [DEBUG] ssl conn_num:0
Apr 29 10:42:08 - [DEBUG] create ssl timeout fail.
Apr 29 10:42:08 - [DEBUG] create_ssl_connection fail
Apr 29 10:42:08 - [DEBUG] ssl conn_num:0

**Comment by hehh2001** [comment]
更新最新版后无法翻墙，估计是IP的问题

**Comment by xxnet** [comment]
可以试试把前面能工作的版本目录下 data/goagent/good_ip.txt 拷贝到新版下，


2015-04-28 22:44 GMT-04:00 he <notifications@github.com>:

**Comment by tj8m23le** [comment]
1.12.3仍然403

**Comment by tj8m23le** [comment]
到了1.30仍然403.。。

**Comment by AbelaroJiang** [comment]
最近的版本一直又这个问题
不知到怎么解决

**Comment by jzp820927** [comment]
多少版本

**Comment by AbelaroJiang** [comment]
3.27, 我这两天清除以前的goodip.txt. 然后在用看看会不会出现类似的情况

**Comment by jzp820927** [comment]
那就观察下吧

**Comment by AbelaroJiang** [comment]
还是会复现，提示错误如下：

403. That’s an error.

Your client does not have permission to get URL /sorry/index?continue=https://www.google.com.hk/search%3Fnewwindow%3D1%26safe%3Dstrict%26site%3D%26source%3Dhp%26q%3Dmysql%2Bbakup%2Ball%2Bdata%2Band%2Btable%26oq%3Dmysql%2Bbakup%2Ball%2Bdata%2Band%2Btable%26gs_l%3Dhp.3..33i21k1l2.2053.29653.0.30176.60.51.9.0.0.0.333.5172.16j27j0j1.44.0....0...1c.1j4.64.hp..8.35.3548.0..0j35i39k1j0i131k1j0i131i155k1j0i10k1j0i13k1j0i13i30k1j0i13i10i30k1j0i22i30k1j33i13i21k1.FBWQvAiz3yw%26bav%3Don.2,or.r_cp.%26bvm%3Dbv.136593572,d.dGo%26biw%3D1920%26bih%3D949%26dpr%3D1%26ech%3D1%26psi%3DNaENWMijKoWV0gTi5p-4Bw.1477288246903.3%26ei%3DNaENWMijKoWV0gTi5p-4Bw%26emsg%3DNCSR%26noj%3D1&q=CGMSBNoR5gwY1MK2wAUiGQDxp4NLyntLMbE_aycoiXu_RRFKS36T46c from this server. That’s all we know.

**Comment by AbelaroJiang** [comment]
还是会复现：

403. That’s an error.

Your client does not have permission to get URL /sorry/index?continue=https://www.google.com.hk/search%3Fnewwindow%3D1%26safe%3Dstrict%26site%3D%26source%3Dhp%26q%3Dmysql%2Bbakup%2Ball%2Bdata%2Band%2Btable%26oq%3Dmysql%2Bbakup%2Ball%2Bdata%2Band%2Btable%26gs_l%3Dhp.3..33i21k1l2.2053.29653.0.30176.60.51.9.0.0.0.333.5172.16j27j0j1.44.0....0...1c.1j4.64.hp..8.35.3548.0..0j35i39k1j0i131k1j0i131i155k1j0i10k1j0i13k1j0i13i30k1j0i13i10i30k1j0i22i30k1j33i13i21k1.FBWQvAiz3yw%26bav%3Don.2,or.r_cp.%26bvm%3Dbv.136593572,d.dGo%26biw%3D1920%26bih%3D949%26dpr%3D1%26ech%3D1%26psi%3DNaENWMijKoWV0gTi5p-4Bw.1477288246903.3%26ei%3DNaENWMijKoWV0gTi5p-4Bw%26emsg%3DNCSR%26noj%3D1&q=CGMSBNoR5gwY1MK2wAUiGQDxp4NLyntLMbE_aycoiXu_RRFKS36T46c from this server. That’s all we know.

**Comment by jzp820927** [comment]
用 https://www.google.com/ncr 试试

**Comment by AbelaroJiang** [comment]
Good, 我follow你的建议，如果又问题，在反馈. 感谢

**Comment by okyou** [comment]
这个问题有解决吗，我也是这种情况，用https://www.google.com/ncr 无效

**Comment by jzp820927** [comment]
设置直连规则
