### ISSUE TITLE
有很大几率失效，然后就是长时间的等待和504页面错误，不知道是不是我的配置错误，能不能搞个默认设置，出问题的时候使用

### ISSUE THREAD

**Issue by 451070257** [XX-net/XX-Net#2655]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 11
network-status: OK
connected-link: 0 / 11
scan-ip-thread-num: 30
ip-quality: 1294
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by noveleven** [comment]
没什么问题，就是延迟比较高，多试试其他网站 #2636

**Comment by ByeGFW** [comment]
你删除`data`文件夹下除了`gae_proxy/good_ip.txt`下的全部文件就会恢复默认设置。

**Comment by HappysurfBlocking** [comment]
你的ip可用量太低了，才11（gws-ip-num: 3000 / 11）
这是我的gws-ip-num: total:239 good:161

**Comment by 451070257** [comment]
那请问如何提高可用ip的数量？

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/2727
用这个提高 IP数量
