### ISSUE TITLE
部署时出错

### ISSUE THREAD

**Issue by extremk** [XX-net/XX-Net#266]
Property Value 
Sys Platform win32 
OS System Windows 
OS version 5.1.2600 
OS release XP 
OS detail Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0 
language zh_CN 
architecture 32bitWindowsPE 
Browser Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727) 
XX-Net Version 1.12.2 
Launcher Version 1.4.0 
GoAgent Version 3.1.49 
Python Version 2.7.9 
Proxy Listen 127.0.0.1:8087 
Set appids albert-washington|alice-jones|anne-sanders|annie-thompson|anthony-nelson|benjamin-price|betty-cook|dennis-lewis|emily-smith|helen-martin|irene-griffin|jimmy-gonzalez|joan-baker|john-perry|kenneth-roberts|larry-richardson|lois-stewart|marilyn-ross|pamela-turner|paula-sanchez|peter-bryant|philip-garcia|phyllis-thomas|raymond-patterson|stephanie-rodriguez 
working appids albert-washington|alice-jones|anne-sanders|annie-thompson|anthony-nelson|benjamin-price|betty-cook|dennis-lewis|emily-smith|helen-martin|irene-griffin|jimmy-gonzalez|joan-baker|john-perry|kenneth-roberts|larry-richardson|lois-stewart|marilyn-ross|pamela-turner|paula-sanchez|peter-bryant|philip-garcia|phyllis-thomas|raymond-patterson|stephanie-rodriguez 
Out of Quota appids  
Not Exist appids  
PAC URL http://127.0.0.1:8086/proxy.pac  
Google IP 2992 
connected link 13,13 
ip-connect-interval 10 
block stat(帮助) OK 

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4112)
Traceback (most recent call last):
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\pytho
n27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\goage
nt\3.1.49\local\proxy.py", line 108, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\pytho
n27\1.0\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\pytho
n27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\pytho
n27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\goage
nt\3.1.49\local\web_control.py", line 338, in do_POST
    return self.req_deploy_handler()
  File "C:\Documents and Settings\Administrator\My Documents\XX-Net-1.12.2\goage
nt\3.1.49\local\web_control.py", line 520, in req_deploy_handler
    appid = self.postvars['appid'][0]
KeyError: 'appid'
----------------------------------------

**Comment by xxnet** [comment]
看上去是程序代码里的错误，但是没有重现你的现象，请重新下载一个干净的版本试试。

2015-04-28 1:11 GMT-04:00 extremk <notifications@github.com>:
