### ISSUE TITLE
昨天不能用的时候goproxy倒是一直能用，xxnet有没有考虑过换成goproxy呢

### ISSUE THREAD

**Issue by eikeime** [XX-net/XX-Net#2665]
如题，昨天不能用的时候goproxy倒是一直能用，xxnet有没有考虑过换成goproxy呢，goproxy就是不太稳定

**Comment by HappysurfBlocking** [comment]
如果goproxy能用gae模式，那么xxnet必定能用

**Comment by HappysurfBlocking** [comment]
不过goproxy的php模式比xxnet要快，而且支持golang
