### ISSUE TITLE
大家不要悲观，不就是封个ip吗？没什么大不了的，技术层面上讲，这尼玛太小儿科鸟！大家有力出力，没力也打打气

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2668]
GFW干这种事不是一次两次了，作为过来人。想告诉大家，过了这段高压期就会慢慢好起来的。
其实连俺都没想到GFW这次会做这么绝，连xx这么大的ip库都敢一次性给灭鸟！
大家有ip的贡献ip，有方法的贡献方法，不要悲观。
gae不是那么容易死滴！

**Comment by jzp820927** [comment]
我只能在精神上支持一下了，不过俗话说的话，理想很丰满，现实很骨感

**Comment by yeahwu** [comment]
goagent这么难用的东西，到现在不也还有人用。说gae会挂，俺就呵呵了。
顶多沦为少数人的玩具，这尼玛就太恶了。
附上 昨天的ip段
https://github.com/XX-net/XX-Net/issues/2636

**Comment by yeahwu** [comment]
@xyuanmu 兄，建议整个ip段出来，内置mini，或者xx。主要是你那转换ip的工具，俺在win上还是linux上都启动不起来。

**Comment by Alan-li** [comment]
我们的程序员可是很牛逼的

**Comment by xyuanmu** [comment]
@yeahwu 启动不了有报错吗？

**Comment by panzer1313208** [comment]
@xxnet 建议内置IP段隐藏起来吧。

**Comment by yeahwu** [comment]
@xyuanmu 情况是这样的，到了选择1，2，3的时候点了以后没反映，也不创建ip段，恩，就是这样子

**Comment by xyuanmu** [comment]
选了要按回车的

**Comment by yeahwu** [comment]
汗，汗，汗，俺再试试，

**Comment by ByeGFW** [comment]
@panzer1313208 
用VPS的手段行不通~ 一封VPS直接全部跪。
其实X-Tunnel的VPS IP我好想之前哪里看到过（好像是104起头的）~ 不知道封了那个X-Tunnel是不是也会跪？

**Comment by jzp820927** [comment]
@ByeGFW 封 IP 没事，就怕 DDOS，因为是 GAE 中转，是 GAE 连接 VPS 不是，国内直接连接 VPS

**Comment by xiaodongQ** [comment]
真的是日了G F W，一天都在折腾这个，在google和百度直接切来切去

**Comment by pm19960106** [comment]
唉
