### ISSUE TITLE
IP爆炸了！！？又回来了！~！！

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#2672]
Apr 02 08:53:21 - [INFO] Add 222.165.163.89 time:878 CN:google.com 
Apr 02 10:15:47 - [INFO] Add 115.254.97.103 time:662 CN:*.googlevideo.com 
Apr 02 11:38:11 - [INFO] Add 115.254.121.219 time:821 CN:*.googlevideo.com 
Apr 02 15:02:26 - [INFO] Add 66.96.224.222 time:473 CN:google.com 
Apr 03 00:06:54 - [INFO] Add 115.254.106.242 time:654 CN:*.googlevideo.com 
Apr 03 00:26:14 - [INFO] Add 115.254.121.220 time:672 CN:*.googlevideo.com 
Apr 03 02:18:37 - [INFO] Add 115.254.121.206 time:622 CN:*.googlevideo.com 
Apr 03 02:21:57 - [INFO] Add 115.254.97.48 time:559 CN:*.googlevideo.com 
Apr 03 04:00:41 - [INFO] Add 115.254.97.14 time:554 CN:*.googlevideo.com 
Apr 03 04:12:21 - [INFO] Add 222.165.163.90 time:881 CN:google.com 
Apr 03 04:28:42 - [INFO] Add 115.254.106.246 time:503 CN:*.googlevideo.com 
Apr 03 04:55:08 - [INFO] Add 115.254.106.209 time:503 CN:*.googlevideo.com 
Apr 03 04:59:09 - [INFO] Add 115.254.121.222 time:556 CN:*.googlevideo.com 
Apr 03 05:32:32 - [INFO] Add 115.254.97.118 time:573 CN:*.googlevideo.com 
Apr 03 06:00:45 - [INFO] Add 115.254.121.207 time:572 CN:*.googlevideo.com 
Apr 03 06:49:39 - [INFO] Add 115.254.121.249 time:550 CN:*.googlevideo.com 
Apr 03 07:14:06 - [INFO] Add 115.254.97.55 time:542 CN:*.googlevideo.com 
Apr 03 07:15:14 - [INFO] Add 115.254.97.78 time:509 CN:*.googlevideo.com 
Apr 03 07:59:31 - [INFO] Add 115.254.121.228 time:600 CN:*.googlevideo.com 
Apr 03 09:13:53 - [INFO] Add 222.165.163.85 time:1269 CN:google.com 
Apr 03 12:03:01 - [INFO] Add 115.254.121.209 time:722 CN:*.googlevideo.com 
Apr 03 12:05:41 - [INFO] Add 115.254.121.225 time:724 CN:*.googlevideo.com 
Apr 03 12:51:03 - [INFO] Add 115.254.106.240 time:664 CN:*.googlevideo.com 
Apr 03 13:52:20 - [INFO] Add 115.254.121.217 time:1790 CN:*.googlevideo.com 
Apr 03 14:06:15 - [INFO] Add 115.254.121.239 time:710 CN:*.googlevideo.com 
Apr 03 14:26:30 - [INFO] Add 115.254.121.243 time:719 CN:*.googlevideo.com 
Apr 03 14:56:41 - [INFO] Add 115.254.121.221 time:567 CN:*.googlevideo.com 
Apr 03 15:06:38 - [INFO] Add 115.254.106.234 time:514 CN:*.googlevideo.com 
Apr 03 18:00:59 - [INFO] Add 115.254.121.218 time:743 CN:*.googlevideo.com 
Apr 03 20:25:56 - [INFO] Add 115.254.106.251 time:743 CN:*.googlevideo.com 
Apr 03 21:21:27 - [INFO] Add 115.254.97.96 time:715 CN:*.googlevideo.com 
Apr 03 21:39:18 - [INFO] Add 115.254.97.98 time:767 CN:*.googlevideo.com 
Apr 03 21:52:41 - [INFO] Add 212.50.193.115 time:1304 CN:*.googlevideo.com 
Apr 03 21:52:42 - [INFO] Add 200.172.62.26 time:1335 CN:*.googlevideo.com 
Apr 03 21:52:43 - [INFO] Add 85.239.127.111 time:1240 CN:*.googlevideo.com 
Apr 03 21:52:50 - [INFO] Add 62.197.198.218 time:1829 CN:google.com 
Apr 03 21:52:50 - [INFO] Add 193.192.226.157 time:1874 CN:google.com 
Apr 03 21:52:50 - [INFO] Add 190.240.6.178 time:1615 CN:*.googlevideo.com 
Apr 03 21:52:50 - [INFO] Add 103.25.178.44 time:1925 CN:google.com 
Apr 03 21:52:52 - [INFO] Add 192.122.185.109 time:1713 CN:google.com 
Apr 03 21:52:56 - [INFO] Add 103.16.207.174 time:1313 CN:*.googlevideo.com 
Apr 03 21:53:01 - [INFO] Add 62.119.230.105 time:1118 CN:*.googlevideo.com 
Apr 03 21:53:04 - [INFO] Add 177.159.237.48 time:1851 CN:google.com 
Apr 03 21:53:04 - [INFO] Add 200.216.56.145 time:1187 CN:*.googlevideo.com 
Apr 03 21:53:04 - [INFO] Add 196.46.123.158 time:2243 CN:google.com 
Apr 03 21:53:09 - [INFO] Add 212.2.108.123 time:2088 CN:google.com 
Apr 03 21:53:09 - [INFO] Add 79.171.163.169 time:1874 CN:*.googlevideo.com 
Apr 03 21:53:10 - [INFO] Add 111.107.254.147 time:966 CN:*.googlevideo.com 
Apr 03 21:53:12 - [INFO] Add 96.127.250.22 time:968 CN:*.googlevideo.com 
Apr 03 21:53:14 - [INFO] Add 80.91.176.59 time:1226 CN:*.googlevideo.com 
Apr 03 21:53:21 - [INFO] Add 182.79.253.27 time:1628 CN:*.googlevideo.com 
Apr 03 21:53:21 - [INFO] Add 190.122.100.209 time:1071 CN:*.googlevideo.com 
Apr 03 21:53:25 - [INFO] Add 201.248.78.232 time:1960 CN:*.googlevideo.com 
Apr 03 21:53:26 - [INFO] Add 191.99.255.223 time:2574 CN:google.com 
Apr 03 21:53:27 - [INFO] Add 216.11.246.243 time:1121 CN:*.googlevideo.com 
Apr 03 21:53:31 - [INFO] Add 202.248.248.162 time:1130 CN:*.googlevideo.com 
Apr 03 21:53:32 - [INFO] Add 74.124.63.112 time:972 CN:*.googlevideo.com 
Apr 03 21:53:32 - [INFO] Add 58.162.62.27 time:1351 CN:*.googlevideo.com 
Apr 03 21:53:39 - [INFO] Add 212.20.34.184 time:3006 CN:*.googlevideo.com 
Apr 03 21:53:43 - [INFO] Add 201.248.78.157 time:1623 CN:google.com 
Apr 03 21:53:47 - [INFO] Add 74.216.233.225 time:1872 CN:*.googlevideo.com 
Apr 03 21:53:48 - [INFO] Add 81.209.95.243 time:2296 CN:*.googlevideo.com 
Apr 03 21:53:52 - [INFO] Add 181.15.96.91 time:1319 CN:*.googlevideo.com 
Apr 03 21:53:55 - [INFO] Add 195.39.213.209 time:2381 CN:*.googlevideo.com 
Apr 03 21:53:58 - [INFO] Add 92.87.232.30 time:1816 CN:google.com 
Apr 03 21:54:01 - [INFO] Add 201.6.16.150 time:1174 CN:*.googlevideo.com 
Apr 03 21:54:01 - [INFO] Add 125.235.17.233 time:1266 CN:*.googlevideo.com 
Apr 03 21:54:01 - [INFO] Add 114.121.194.107 time:1503 CN:*.googlevideo.com 
Apr 03 21:54:06 - [INFO] Add 194.44.4.19 time:1239 CN:*.googlevideo.com 
Apr 03 21:54:07 - [INFO] Add 146.115.8.79 time:1503 CN:google.com 
Apr 03 21:54:11 - [INFO] Add 107.161.13.242 time:1213 CN:*.googlevideo.com 
Apr 03 21:54:15 - [INFO] Add 2.127.237.187 time:1546 CN:google.com 
Apr 03 21:54:18 - [INFO] Add 109.193.192.112 time:1082 CN:*.googlevideo.com 
Apr 03 21:54:19 - [INFO] Add 79.171.163.166 time:1687 CN:google.com 
Apr 03 21:54:19 - [INFO] Add 201.86.233.240 time:1402 CN:*.googlevideo.com 
Apr 03 21:54:21 - [INFO] Add 110.163.42.122 time:1036 CN:*.googlevideo.com 
Apr 03 21:54:25 - [INFO] Add 207.172.159.151 time:1469 CN:*.googlevideo.com 
Apr 03 21:54:27 - [INFO] Add 154.65.36.25 time:2400 CN:google.com 
Apr 03 21:54:27 - [INFO] Add 103.16.207.185 time:1374 CN:*.googlevideo.com 
Apr 03 21:54:28 - [INFO] Add 116.93.47.52 time:1223 CN:*.googlevideo.com 
Apr 03 21:54:31 - [INFO] Add 212.2.108.119 time:1622 CN:google.com 
Apr 03 21:54:34 - [INFO] Add 202.38.180.243 time:1287 CN:*.googlevideo.com 
Apr 03 21:54:46 - [INFO] Add 207.172.159.153 time:2138 CN:*.googlevideo.com 
Apr 03 21:54:46 - [INFO] Add 85.91.7.26 time:2141 CN:*.googlevideo.com 
Apr 03 21:54:50 - [INFO] Add 177.135.245.176 time:2549 CN:*.googlevideo.com 
Apr 03 21:54:54 - [INFO] Add 82.193.82.226 time:4945 CN:google.com 
Apr 03 21:54:55 - [INFO] Add 213.155.151.173 time:2911 CN:*.googlevideo.com 
Apr 03 21:54:57 - [INFO] Add 208.104.242.182 time:3328 CN:*.googlevideo.com 
Apr 03 21:54:57 - [INFO] Add 192.122.185.76 time:3328 CN:*.googlevideo.com 
Apr 03 21:55:04 - [INFO] Add 177.135.103.151 time:4746 CN:*.googlevideo.com 
Apr 03 21:55:05 - [INFO] Add 212.188.7.244 time:1208 CN:*.googlevideo.com 
Apr 03 21:55:06 - [INFO] Add 118.98.36.103 time:5101 CN:google.com 
Apr 03 21:55:08 - [INFO] Add 124.158.72.39 time:1018 CN:*.googlevideo.com 
Apr 03 21:55:14 - [INFO] Add 203.210.2.141 time:1219 CN:*.googlevideo.com 
Apr 03 21:55:14 - [INFO] Add 177.99.203.233 time:1247 CN:*.googlevideo.com 
Apr 03 21:55:16 - [INFO] Add 77.88.221.57 time:1701 CN:*.googlevideo.com 
Apr 03 21:55:19 - [INFO] Add 182.79.253.79 time:1513 CN:*.googlevideo.com 
Apr 03 21:55:22 - [INFO] Add 61.91.18.173 time:2288 CN:google.com 
Apr 03 21:55:22 - [INFO] Add 187.115.167.204 time:1278 CN:*.googlevideo.com 
Apr 03 21:55:25 - [INFO] Add 46.61.155.236 time:1855 CN:google.com 
Apr 03 21:55:26 - [INFO] Add 24.149.5.223 time:1685 CN:google.com 
Apr 03 21:55:28 - [INFO] Add 65.183.12.223 time:1579 CN:google.com 
Apr 03 21:55:38 - [INFO] Add 89.25.120.54 time:1101 CN:*.googlevideo.com 
Apr 03 21:55:41 - [INFO] Add 177.101.143.215 time:2544 CN:google.com 
Apr 03 21:55:47 - [INFO] Add 79.171.163.144 time:1210 CN:*.googlevideo.com 
Apr 03 21:55:49 - [INFO] Add 79.101.110.52 time:1095 CN:*.googlevideo.com 
Apr 03 21:55:55 - [INFO] Add 210.139.253.237 time:1378 CN:google.com 
Apr 03 21:55:56 - [INFO] Add 80.149.20.84 time:1432 CN:google.com 
Apr 03 21:55:57 - [INFO] Add 1.9.131.106 time:1111 CN:*.googlevideo.com 
Apr 03 21:56:00 - [INFO] Add 196.202.246.215 time:1752 CN:google.com 
Apr 03 21:56:00 - [INFO] Add 118.174.25.106 time:1066 CN:*.googlevideo.com 
Apr 03 21:56:01 - [INFO] Add 190.197.64.47 time:809 CN:*.googlevideo.com 
Apr 03 21:56:04 - [INFO] Add 118.143.88.19 time:970 CN:*.googlevideo.com 
Apr 03 21:56:06 - [INFO] Add 194.158.92.99 time:1065 CN:*.googlevideo.com 
Apr 03 21:56:07 - [INFO] Add 113.171.18.159 time:1092 CN:*.googlevideo.com 
Apr 03 21:56:09 - [INFO] Add 200.28.8.171 time:1305 CN:*.googlevideo.com 
Apr 03 21:56:10 - [INFO] Add 148.245.203.101 time:826 CN:*.googlevideo.com 
Apr 03 21:56:11 - [INFO] Add 118.98.106.235 time:1327 CN:*.googlevideo.com 
Apr 03 21:56:14 - [INFO] Add 186.73.79.32 time:1097 CN:*.googlevideo.com 
Apr 03 21:56:22 - [INFO] Add 201.6.16.185 time:1029 CN:*.googlevideo.com 
Apr 03 21:56:23 - [INFO] Add 177.43.115.150 time:1023 CN:*.googlevideo.com 
Apr 03 21:56:28 - [INFO] Add 217.73.128.227 time:1052 CN:*.googlevideo.com 
Apr 03 21:56:30 - [INFO] Add 94.40.70.168 time:968 CN:*.googlevideo.com 
Apr 03 21:56:32 - [INFO] Add 176.126.59.82 time:983 CN:*.googlevideo.com 
Apr 03 21:56:33 - [INFO] Add 64.20.30.250 time:758 CN:*.googlevideo.com 
Apr 03 21:56:33 - [INFO] Add 187.44.0.78 time:1012 CN:*.googlevideo.com 
Apr 03 21:56:39 - [INFO] Add 200.216.90.150 time:960 CN:*.googlevideo.com 
Apr 03 21:56:40 - [INFO] Add 46.29.169.219 time:1434 CN:google.com 
Apr 03 21:56:45 - [INFO] Add 185.2.108.36 time:1211 CN:*.googlevideo.com 
Apr 03 21:56:51 - [INFO] Add 82.76.79.81 time:1006 CN:*.googlevideo.com 
Apr 03 21:56:51 - [INFO] Add 201.248.76.83 time:956 CN:*.googlevideo.com 
Apr 03 21:56:52 - [INFO] Add 202.39.143.104 time:1520 CN:google.com 
Apr 03 21:56:53 - [INFO] Add 49.98.24.164 time:917 CN:*.googlevideo.com 
Apr 03 21:56:54 - [INFO] Add 204.186.215.23 time:803 CN:*.googlevideo.com 
Apr 03 21:56:54 - [INFO] Add 1.179.250.110 time:1219 CN:*.googlevideo.com 
Apr 03 21:57:01 - [INFO] Add 216.58.194.84 time:948 CN:*.google.com 
Apr 03 21:57:01 - [INFO] Add 41.206.96.151 time:1301 CN:*.googlevideo.com 
Apr 03 21:57:06 - [INFO] Add 189.203.232.44 time:1423 CN:google.com 
Apr 03 21:57:08 - [INFO] Add 78.11.253.151 time:1013 CN:*.googlevideo.com 
Apr 03 21:57:09 - [INFO] Add 190.221.162.36 time:1069 CN:*.googlevideo.com 
Apr 03 21:57:11 - [INFO] Add 77.37.252.25 time:1672 CN:google.com 
Apr 03 21:57:12 - [INFO] Add 210.191.74.43 time:889 CN:*.googlevideo.com 
Apr 03 21:57:12 - [INFO] Add 92.87.232.48 time:1023 CN:*.googlevideo.com 
Apr 03 21:57:13 - [INFO] Add 86.51.24.248 time:1082 CN:*.googlevideo.com 
Apr 03 21:57:13 - [INFO] Add 74.125.26.132 time:927 CN:*.googleusercontent.com 
Apr 03 21:57:13 - [INFO] Add 212.188.7.121 time:1004 CN:*.googlevideo.com 
Apr 03 21:57:14 - [INFO] Add 111.168.255.234 time:858 CN:*.googlevideo.com 
Apr 03 21:57:23 - [INFO] Add 4.59.67.49 time:1411 CN:google.com 
Apr 03 21:57:24 - [INFO] Add 185.3.1.23 time:1669 CN:google.com 
Apr 03 21:57:25 - [INFO] Add 61.91.8.155 time:1311 CN:*.googlevideo.com 
Apr 03 21:57:30 - [INFO] Add 185.73.88.28 time:1148 CN:*.googlevideo.com 
Apr 03 21:57:35 - [INFO] Add 177.43.165.77 time:1119 CN:*.googlevideo.com 
Apr 03 21:57:35 - [INFO] Add 142.176.121.211 time:957 CN:*.googlevideo.com 
Apr 03 21:57:37 - [INFO] Add 86.51.24.240 time:1220 CN:*.googlevideo.com 
Apr 03 21:57:37 - [INFO] Add 4.53.56.118 time:1443 CN:google.com 
Apr 03 21:57:38 - [INFO] Add 89.25.120.29 time:1101 CN:*.googlevideo.com 
Apr 03 21:57:42 - [INFO] Add 189.73.192.204 time:1235 CN:*.googlevideo.com 
Apr 03 21:57:43 - [INFO] Add 194.90.196.32 time:1292 CN:*.googlevideo.com 
Apr 03 21:57:47 - [INFO] Add 203.210.4.159 time:1602 CN:google.com 
Apr 03 21:57:50 - [INFO] Add 61.91.8.23 time:1375 CN:*.googlevideo.com 
Apr 03 21:57:54 - [INFO] Add 27.90.189.244 time:1064 CN:*.googlevideo.com 
Apr 03 21:57:54 - [INFO] Add 212.191.236.121 time:1750 CN:google.com 
Apr 03 21:58:00 - [INFO] Add 72.195.166.56 time:1467 CN:google.com 
Apr 03 21:58:01 - [INFO] Add 209.141.120.159 time:846 CN:*.googlevideo.com 
Apr 03 21:58:05 - [INFO] Add 94.20.252.88 time:1799 CN:google.com 
Apr 03 21:58:08 - [INFO] Add 58.162.16.55 time:1663 CN:google.com 
Apr 03 21:58:12 - [INFO] Add 213.158.11.181 time:1976 CN:google.com 
Apr 03 21:58:14 - [INFO] Add 125.235.30.250 time:1275 CN:*.googlevideo.com 
Apr 03 21:58:15 - [INFO] Add 177.91.191.25 time:1266 CN:*.googlevideo.com 
Apr 03 21:58:15 - [INFO] Add 31.55.162.147 time:1169 CN:*.googlevideo.com 
Apr 03 21:58:15 - [INFO] Add 189.1.145.12 time:1253 CN:*.googlevideo.com 
Apr 03 21:58:16 - [INFO] Add 217.19.150.90 time:1156 CN:*.googlevideo.com 
Apr 03 21:58:16 - [INFO] Add 167.206.12.106 time:986 CN:*.googlevideo.com 
Apr 03 21:58:17 - [INFO] Add 202.169.175.99 time:1187 CN:*.googlevideo.com 
Apr 03 21:58:18 - [INFO] Add 213.186.122.245 time:1187 CN:*.googlevideo.com 
Apr 03 21:58:22 - [INFO] Add 90.211.177.184 time:993 CN:*.googlevideo.com 
Apr 03 21:58:25 - [INFO] Add 70.34.140.210 time:767 CN:*.googlevideo.com 
Apr 03 21:58:28 - [INFO] Add 189.195.222.59 time:1396 CN:google.com 
Apr 03 21:58:29 - [INFO] Add 201.162.64.56 time:1103 CN:*.googlevideo.com 
Apr 03 21:58:31 - [INFO] Add 115.164.140.13 time:1081 CN:*.googlevideo.com 
Apr 03 21:58:33 - [INFO] Add 84.235.77.81 time:1200 CN:*.googlevideo.com 
Apr 03 21:58:34 - [INFO] Add 187.86.49.28 time:1069 CN:*.googlevideo.com 
Apr 03 21:58:40 - [INFO] Add 42.112.9.225 time:1032 CN:*.googlevideo.com 
Apr 03 21:58:41 - [INFO] Add 193.95.12.81 time:1069 CN:*.googlevideo.com 
Apr 03 21:58:41 - [INFO] Add 93.88.162.180 time:1250 CN:*.googlevideo.com 
Apr 03 21:58:48 - [INFO] Add 74.216.233.214 time:888 CN:*.googlevideo.com 
Apr 03 21:58:55 - [INFO] Add 139.175.107.224 time:1033 CN:*.googlevideo.com 
Apr 03 21:59:01 - [INFO] Add 212.112.37.97 time:1012 CN:*.googlevideo.com 
Apr 03 21:59:03 - [INFO] Add 111.168.255.229 time:891 CN:*.googlevideo.com 
Apr 03 21:59:05 - [INFO] Add 62.214.62.207 time:944 CN:*.googlevideo.com 
Apr 03 21:59:14 - [INFO] Add 186.192.145.36 time:1046 CN:*.googlevideo.com 
Apr 03 21:59:16 - [INFO] Add 154.67.1.220 time:1312 CN:*.googlevideo.com 
Apr 03 21:59:16 - [INFO] Add 193.170.141.251 time:1435 CN:google.com 
Apr 03 21:59:17 - [INFO] Add 201.248.76.216 time:1556 CN:google.com 
Apr 03 21:59:21 - [INFO] Add 200.115.94.19 time:1445 CN:google.com 
Apr 03 21:59:24 - [INFO] Add 88.222.2.109 time:1528 CN:google.com 
Apr 03 21:59:25 - [INFO] Add 58.162.16.144 time:1101 CN:*.googlevideo.com 
Apr 03 21:59:26 - [INFO] Add 95.168.222.123 time:1454 CN:google.com 
Apr 03 21:59:26 - [INFO] Add 177.43.196.179 time:1031 CN:*.googlevideo.com 
Apr 03 21:59:26 - [INFO] Add 212.56.71.39 time:1406 CN:google.com 
Apr 03 21:59:28 - [INFO] Add 5.20.5.40 time:1028 CN:*.googlevideo.com 
Apr 03 21:59:28 - [INFO] Add 190.241.121.21 time:904 CN:*.googlevideo.com 
Apr 03 21:59:30 - [INFO] Add 151.248.100.140 time:1164 CN:*.googlevideo.com

**Comment by xiaoyan94** [comment]
状态

属性	值
本地网络状态	OK
IP数量	645
IP延迟	692
连接池(帮助)	11 / 49
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	500
屏蔽状态 (帮助)	OK

**Comment by zaney** [comment]
真的吗

**Comment by xiaoyan94** [comment]
状态

属性	值
本地网络状态	OK
IP数量	1098
IP延迟	722
连接池(帮助)	12 / 50
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	500
屏蔽状态 (帮助)	OK
怎么IP一直再增加？？这会儿已经到一千了

**Comment by jzp820927** [comment]
@xiaoyan94 这是 XX 内置的IP，还是你找到 第三方 IP？

**Comment by xiaoyan94** [comment]
@jzp820927 不是内置的，我换了前面有个i那个人提供救急的IP段

**Comment by jzp820927** [comment]
那就对了，这次封锁是专门针对 XXNET 内置IP文件的，所以第三方IP，暂时幸免遇难。

**Comment by tianweiliang** [comment]
哪个ip段？麻烦给个链接哈

**Comment by yangkkokk** [comment]
这个IP段也费了

**Comment by jzp820927** [comment]
不会这么快又费了吧
