### ISSUE TITLE
GoAgent 服务端已经在 2015-04-28 16:07:16 升级到 3.3.1 版本, 请更新您的客户端。

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net#268]
部署后也正常，但访问
https://redstoneleo.appspot.com/
就出现

“GoAgent 服务端已经在 2015-04-28 16:07:16 升级到 3.3.1 版本, 请更新您的客户端。”

这是怎么回事？

Apr 28 16:16:08 - [INFO] GAE CONNECT redstoneleo.appspot.com:443 
Apr 28 16:16:08 - [DEBUG] GAE CONNECT GET https://redstoneleo.appspot.com/
Apr 28 16:16:08 - [DEBUG] new_conn_pool.get:64.233.162.85 handshake:648
Apr 28 16:16:08 - [DEBUG] new_conn_pool conn_num:12
Apr 28 16:16:09 - [INFO] DIRECT chucked t:469 s:121 200 redstoneleo.appspot.com /
Apr 28 16:16:09 - [INFO] GAE CONNECT redstoneleo.appspot.com:443 
Apr 28 16:16:09 - [DEBUG] GAE CONNECT GET https://redstoneleo.appspot.com/favicon.ico
Apr 28 16:16:09 - [DEBUG] new_conn_pool.get:64.233.162.85 handshake:658
Apr 28 16:16:09 - [DEBUG] new_conn_pool conn_num:11
Apr 28 16:16:10 - [INFO] DIRECT chucked t:477 s:87 200 redstoneleo.appspot.com /favicon.ico
Apr 28 16:16:23 - [DEBUG] sort ip time:16
Apr 28 16:16:23 - [DEBUG] get ip:64.233.162.87 t:698
Apr 28 16:16:23 - [DEBUG] get ip:64.233.162.86 t:943
Apr 28 16:16:24 - [DEBUG] create_ssl update ip:64.233.162.87 time:694
Apr 28 16:16:24 - [DEBUG] create_ssl update ip:64.233.162.86 time:656

GoAgent状态信息

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36
XX-Net Version	1.12.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	redstoneleo
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2991
connected link	10,10
ip-connect-interval	10
block stat(帮助)	OK

**Comment by Cat7373** [comment]
简单的看了看代码，应该是客户端的Bug

**Comment by xxnet** [comment]
这正常，不是bug，只是提示不友好。

**Comment by wzwmzm** [comment]
GoAgent 客户端Version 3.1.49，需要升级要3.3.1，不知道如何升级？
