### ISSUE TITLE
建议只保留山景城总部的ip段

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#2690]
亚洲地区的ip寿命普遍太短，建议在ip段列表里只保留几十万Mountain View总部的ip段，这样扫描效率会提高很多，ip寿命也相对长一些。

**Comment by heiheihei120** [comment]
请问山景城总部的ip是什么样的

**Comment by taoist1994** [comment]
IP段列表中类似×.×.0.0-×.×.255.255格式的都是山景城总部的IP，建议只保留这些IP段，这样扫描速度会大大提高。

**Comment by hwbasd** [comment]
山景城的ip质量非常的高，但是会被顺秒。我能瞬间扫到几百IP，但是不到一根烟的功夫IP又都失效。有功夫的再试试。。。

IP地址段：216.239.0.0 - 216.239.255.255 共【65536】个IP记录
详细地址：美国加利福尼亚州山景市谷歌公司
216.239.0.0 216.239.0.79 216.239.0.158 216.239.0.237 216.239.1.60 216.239.1.139 
216.239.1.218 216.239.2.41 216.239.2.120 216.239.2.199 216.239.3.22 216.239.3.101 
216.239.3.180 216.239.4.3 216.239.4.82 216.239.4.161 216.239.4.240 216.239.5.63 
216.239.5.142 216.239.5.221 216.239.6.44 216.239.6.123 216.239.6.202 216.239.7.25 
216.239.7.104 216.239.7.183 216.239.8.6 216.239.8.85 216.239.8.164 216.239.8.243 
216.239.9.66 216.239.9.145 216.239.9.224 216.239.10.47 216.239.10.126 216.239.10.205 
216.239.11.28 216.239.11.107 216.239.11.186 216.239.12.9 216.239.12.88 216.239.12.167 
216.239.12.246 216.239.13.69 216.239.13.148 216.239.13.227 216.239.14.50 216.239.14.129 
216.239.14.208 216.239.15.31 216.239.15.110 216.239.15.189 216.239.16.12 216.239.16.91 
216.239.16.170 216.239.16.249 216.239.17.72 216.239.17.151 216.239.17.230 216.239.18.53 
216.239.18.132 216.239.18.211 216.239.19.34 216.239.19.113 216.239.19.192 216.239.20.15 
216.239.20.94 216.239.20.173 216.239.20.252 216.239.21.75 216.239.21.154 216.239.21.233 
216.239.22.56 216.239.22.135 216.239.22.214 216.239.23.37 216.239.23.116 216.239.23.195 
216.239.24.18 216.239.24.97 216.239.24.176 216.239.24.255 216.239.25.78 216.239.25.157 
216.239.25.236 216.239.26.59 216.239.26.138 216.239.26.217 216.239.27.40 216.239.27.119 
216.239.27.198 216.239.28.21 216.239.28.100 216.239.28.179 216.239.29.2 216.239.29.81 
216.239.29.160 216.239.29.239 216.239.30.62 216.239.30.141 216.239.30.220 216.239.31.43 
216.239.31.122 216.239.31.201 216.239.32.24 216.239.32.103 216.239.32.182 216.239.33.5 
216.239.33.84 216.239.33.163 216.239.33.242 216.239.34.65 216.239.34.144 216.239.34.223 
216.239.35.46 216.239.35.125 216.239.35.204 216.239.36.27 216.239.36.106 216.239.36.185 
216.239.37.8 216.239.37.87 216.239.37.166 216.239.37.245 216.239.38.68 216.239.38.147 
216.239.38.226 216.239.39.49 216.239.39.128 216.239.39.207 216.239.40.30 216.239.40.109 
216.239.40.188 216.239.41.11 216.239.41.90 216.239.41.169 216.239.41.248 216.239.42.71 
216.239.42.150 216.239.42.229 216.239.43.52 216.239.43.131 216.239.43.210 216.239.44.33 
216.239.44.112 216.239.44.191 216.239.45.14 216.239.45.93 216.239.45.172 216.239.45.251 
216.239.46.74 216.239.46.153 216.239.46.232 216.239.47.55 216.239.47.134 216.239.47.213 
216.239.48.36 216.239.48.115 216.239.48.194 216.239.49.17 216.239.49.96 216.239.49.175 
216.239.49.254 216.239.50.77 216.239.50.156 216.239.50.235 216.239.51.58 216.239.51.137 
216.239.51.216 216.239.52.39 216.239.52.118 216.239.52.197 216.239.53.20 216.239.53.99 
216.239.53.178 216.239.54.1 216.239.54.80 216.239.54.159 216.239.54.238 216.239.55.61 
216.239.55.140 216.239.55.219 216.239.56.42 216.239.56.121 216.239.56.200 216.239.57.23 
216.239.57.102 216.239.57.181 216.239.58.4 216.239.58.83 216.239.58.162 216.239.58.241 
216.239.59.64 216.239.59.143 216.239.59.222 216.239.60.45 216.239.60.124 216.239.60.203 
216.239.61.26 216.239.61.105 216.239.61.184 216.239.62.7 216.239.62.86 216.239.62.165 
216.239.62.244 216.239.63.67 216.239.63.146 216.239.63.225 216.239.64.48 216.239.64.127 
216.239.64.206 216.239.65.29 216.239.65.108 216.239.65.187 216.239.66.10 216.239.66.89 
216.239.66.168 216.239.66.247 216.239.67.70 216.239.67.149 216.239.67.228 216.239.68.51 
216.239.68.130 216.239.68.209 216.239.69.32 216.239.69.111 216.239.69.190 216.239.70.13 
216.239.70.92 216.239.70.171 216.239.70.250 216.239.71.73 216.239.71.152 216.239.71.231 
216.239.72.54 216.239.72.133 216.239.72.212 216.239.73.35 216.239.73.114 216.239.73.193 
216.239.74.16 216.239.74.95 216.239.74.174 216.239.74.253 216.239.75.76 216.239.75.155 
216.239.75.234 216.239.76.57 216.239.76.136 216.239.76.215 216.239.77.38 216.239.77.117 
216.239.77.196 216.239.78.19 216.239.78.98 216.239.78.177 216.239.79.0 216.239.79.79 
216.239.79.158 216.239.79.237 216.239.80.60 216.239.80.139 216.239.80.218 216.239.81.41 
216.239.81.120 216.239.81.199 216.239.82.22 216.239.82.101 216.239.82.180 216.239.83.3 
216.239.83.82 216.239.83.161 216.239.83.240 216.239.84.63 216.239.84.142 216.239.84.221 
216.239.85.44 216.239.85.123 216.239.85.202 216.239.86.25 216.239.86.104 216.239.86.183 
216.239.87.6 216.239.87.85 216.239.87.164 216.239.87.243 216.239.88.66 216.239.88.145 
216.239.88.224 216.239.89.47 216.239.89.126 216.239.89.205 216.239.90.28 216.239.90.107 
216.239.90.186 216.239.91.9 216.239.91.88 216.239.91.167 216.239.91.246 216.239.92.69 
216.239.92.148 216.239.92.227 216.239.93.50 216.239.93.129 216.239.93.208 216.239.94.31 
216.239.94.110 216.239.94.189 216.239.95.12 216.239.95.91 216.239.95.170 216.239.95.249 
216.239.96.72 216.239.96.151 216.239.96.230 216.239.97.53 216.239.97.132 216.239.97.211 
216.239.98.34 216.239.98.113 216.239.98.192 216.239.99.15 216.239.99.94 216.239.99.173 
216.239.99.252 216.239.100.75 216.239.100.154 216.239.100.233 216.239.101.56 216.239.101.135 
216.239.101.214 216.239.102.37 216.239.102.116 216.239.102.195 216.239.103.18 216.239.103.97 
216.239.103.176 216.239.103.255 216.239.104.78 216.239.104.157 216.239.104.236 216.239.105.59 
216.239.105.138 216.239.105.217 216.239.106.40 216.239.106.119 216.239.106.198 216.239.107.21 
216.239.107.100 216.239.107.179 216.239.108.2 216.239.108.81 216.239.108.160 216.239.108.239 
216.239.109.62 216.239.109.141 216.239.109.220 216.239.110.43 216.239.110.122 216.239.110.201 
216.239.111.24 216.239.111.103 216.239.111.182 216.239.112.5 216.239.112.84 216.239.112.163 
216.239.112.242 216.239.113.65 216.239.113.144 216.239.113.223 216.239.114.46 216.239.114.125 
216.239.114.204 216.239.115.27 216.239.115.106 216.239.115.185 216.239.116.8 216.239.116.87 
216.239.116.166 216.239.116.245 216.239.117.68 216.239.117.147 216.239.117.226 216.239.118.49 
216.239.118.128 216.239.118.207 216.239.119.30 216.239.119.109 216.239.119.188 216.239.120.11 
216.239.120.90 216.239.120.169 216.239.120.248 216.239.121.71 216.239.121.150 216.239.121.229 
216.239.122.52 216.239.122.131 216.239.122.210 216.239.123.33 216.239.123.112 216.239.123.191 
216.239.124.14 216.239.124.93 216.239.124.172 216.239.124.251 216.239.125.74 216.239.125.153 
216.239.125.232 216.239.126.55 216.239.126.134 216.239.126.213 216.239.127.36 216.239.127.115 
216.239.127.194 216.239.128.17 216.239.128.96 216.239.128.175 216.239.128.254 216.239.129.77 
216.239.129.156 216.239.129.235 216.239.130.58 216.239.130.137 216.239.130.216 216.239.131.39 
216.239.131.118 216.239.131.197 216.239.132.20 216.239.132.99 216.239.132.178 216.239.133.1 
216.239.133.80 216.239.133.159 216.239.133.238 216.239.134.61 216.239.134.140 216.239.134.219 
216.239.135.42 216.239.135.121 216.239.135.200 216.239.136.23 216.239.136.102 216.239.136.181 
216.239.137.4 216.239.137.83 216.239.137.162 216.239.137.241 216.239.138.64 216.239.138.143 
216.239.138.222 216.239.139.45 216.239.139.124 216.239.139.203 216.239.140.26 216.239.140.105 
216.239.140.184 216.239.141.7 216.239.141.86 216.239.141.165 216.239.141.244 216.239.142.67 
216.239.142.146 216.239.142.225 216.239.143.48 216.239.143.127 216.239.143.206 216.239.144.29 
216.239.144.108 216.239.144.187 216.239.145.10 216.239.145.89 216.239.145.168 216.239.145.247 
216.239.146.70 216.239.146.149 216.239.146.228 216.239.147.51 216.239.147.130 216.239.147.209 
216.239.148.32 216.239.148.111 216.239.148.190 216.239.149.13 216.239.149.92 216.239.149.171 
216.239.149.250 216.239.150.73 216.239.150.152 216.239.150.231 216.239.151.54 216.239.151.133 
216.239.151.212 216.239.152.35 216.239.152.114 216.239.152.193 216.239.153.16 216.239.153.95 
216.239.153.174 216.239.153.253 216.239.154.76 216.239.154.155 216.239.154.234 216.239.155.57 
216.239.155.136 216.239.155.215 216.239.156.38 216.239.156.117 216.239.156.196 216.239.157.19 
216.239.157.98 216.239.157.177 216.239.158.0 216.239.158.79 216.239.158.158 216.239.158.237 
216.239.159.60 216.239.159.139 216.239.159.218 216.239.160.41 216.239.160.120 216.239.160.199 
216.239.161.22 216.239.161.101 216.239.161.180 216.239.162.3 216.239.162.82 216.239.162.161 
216.239.162.240 216.239.163.63 216.239.163.142 216.239.163.221 216.239.164.44 216.239.164.123 
216.239.164.202 216.239.165.25 216.239.165.104 216.239.165.183 216.239.166.6 216.239.166.85 
216.239.166.164 216.239.166.243 216.239.167.66 216.239.167.145 216.239.167.224 216.239.168.47 
216.239.168.126 216.239.168.205 216.239.169.28 216.239.169.107 216.239.169.186 216.239.170.9 
216.239.170.88 216.239.170.167 216.239.170.246 216.239.171.69 216.239.171.148 216.239.171.227 
216.239.172.50 216.239.172.129 216.239.172.208 216.239.173.31 216.239.173.110 216.239.173.189 
216.239.174.12 216.239.174.91 216.239.174.170 216.239.174.249 216.239.175.72 216.239.175.151 
216.239.175.230 216.239.176.53 216.239.176.132 216.239.176.211 216.239.177.34 216.239.177.113 
216.239.177.192 216.239.178.15 216.239.178.94 216.239.178.173 216.239.178.252 216.239.179.75 
216.239.179.154 216.239.179.233 216.239.180.56 216.239.180.135 216.239.180.214 216.239.181.37 
216.239.181.116 216.239.181.195 216.239.182.18 216.239.182.97 216.239.182.176 216.239.182.255 
216.239.183.78 216.239.183.157 216.239.183.236 216.239.184.59 216.239.184.138 216.239.184.217 
216.239.185.40 216.239.185.119 216.239.185.198 216.239.186.21 216.239.186.100 216.239.186.179 
216.239.187.2 216.239.187.81 216.239.187.160 216.239.187.239 216.239.188.62 216.239.188.141 
216.239.188.220 216.239.189.43 216.239.189.122 216.239.189.201 216.239.190.24 216.239.190.103 
216.239.190.182 216.239.191.5 216.239.191.84 216.239.191.163 216.239.191.242 216.239.192.65 
216.239.192.144 216.239.192.223 216.239.193.46 216.239.193.125 216.239.193.204 216.239.194.27 
216.239.194.106 216.239.194.185 216.239.195.8 216.239.195.87 216.239.195.166 216.239.195.245 
216.239.196.68 216.239.196.147 216.239.196.226 216.239.197.49 216.239.197.128 216.239.197.207 
216.239.198.30 216.239.198.109 216.239.198.188 216.239.199.11 216.239.199.90 216.239.199.169 
216.239.199.248 216.239.200.71 216.239.200.150 216.239.200.229 216.239.201.52 216.239.201.131 
216.239.201.210 216.239.202.33 216.239.202.112 216.239.202.191 216.239.203.14 216.239.203.93 
216.239.203.172 216.239.203.251 216.239.204.74 216.239.204.153 216.239.204.232 216.239.205.55 
216.239.205.134 216.239.205.213 216.239.206.36 216.239.206.115 216.239.206.194 216.239.207.17 
216.239.207.96 216.239.207.175 216.239.207.254 216.239.208.77 216.239.208.156 216.239.208.235 
216.239.209.58 216.239.209.137 216.239.209.216 216.239.210.39 216.239.210.118 216.239.210.197 
216.239.211.20 216.239.211.99 216.239.211.178 216.239.212.1 216.239.212.80 216.239.212.159 
216.239.212.238 216.239.213.61 216.239.213.140 216.239.213.219 216.239.214.42 216.239.214.121 
216.239.214.200 216.239.215.23 216.239.215.102 216.239.215.181 216.239.216.4 216.239.216.83 
216.239.216.162 216.239.216.241 216.239.217.64 216.239.217.143 216.239.217.222 216.239.218.45 
216.239.218.124 216.239.218.203 216.239.219.26 216.239.219.105 216.239.219.184 216.239.220.7 
216.239.220.86 216.239.220.165 216.239.220.244 216.239.221.67 216.239.221.146 216.239.221.225 
216.239.222.48 216.239.222.127 216.239.222.206 216.239.223.29 216.239.223.108 216.239.223.187 
216.239.224.10 216.239.224.89 216.239.224.168 216.239.224.247 216.239.225.70 216.239.225.149 
216.239.225.228 216.239.226.51 216.239.226.130 216.239.226.209 216.239.227.32 216.239.227.111 
216.239.227.190 216.239.228.13 216.239.228.92 216.239.228.171 216.239.228.250 216.239.229.73 
216.239.229.152 216.239.229.231 216.239.230.54 216.239.230.133 216.239.230.212 216.239.231.35 
216.239.231.114 216.239.231.193 216.239.232.16 216.239.232.95 216.239.232.174 216.239.232.253 
216.239.233.76 216.239.233.155 216.239.233.234 216.239.234.57 216.239.234.136 216.239.234.215 
216.239.235.38 216.239.235.117 216.239.235.196 216.239.236.19 216.239.236.98 216.239.236.177 
216.239.237.0 216.239.237.79 216.239.237.158 216.239.237.237 216.239.238.60 216.239.238.139 
216.239.238.218 216.239.239.41 216.239.239.120 216.239.239.199 216.239.240.22 216.239.240.101 
216.239.240.180 216.239.241.3 216.239.241.82 216.239.241.161 216.239.241.240 216.239.242.63 
216.239.242.142 216.239.242.221 216.239.243.44 216.239.243.123 216.239.243.202 216.239.244.25 
216.239.244.104 216.239.244.183 216.239.245.6 216.239.245.85 216.239.245.164 216.239.245.243 
216.239.246.66 216.239.246.145 216.239.246.224 216.239.247.47 216.239.247.126 216.239.247.205 
216.239.248.28 216.239.248.107 216.239.248.186 216.239.249.9 216.239.249.88 216.239.249.167 
216.239.249.246 216.239.250.69 216.239.250.148 216.239.250.227 216.239.251.50 216.239.251.129 
216.239.251.208 216.239.252.31 216.239.252.110 216.239.252.189 216.239.253.12 216.239.253.91 
216.239.253.170 216.239.253.249 216.239.254.72 216.239.254.151 216.239.254.230 216.239.255.53 
216.239.255.132 216.239.255.211

**Comment by fengixng** [comment]
as15169的IP是被重点照顾的，只保留的as15169的IP更是本末倒置

**Comment by taoist1994** [comment]
从15年到现在一直用山景城IP使用goagent，1年多观察下来一般山景城IP的寿命普遍在1-2个月，而亚洲的IP使用不到1个月一般就歇菜了。一般封锁山景城的一部分IP地址时，又会解封出另一部分的IP，而xx-net是自动扫描的，所以使用扫描山景城IP段是比扫描默认IP列表更有效的策略。
一般封锁山景城的一部分IP地址时，又会解封出另一部分的IP，而xx-net是全时段自动扫描的，所以使用扫描山景城IP段是比扫描默认IP列表更有效的策略。

**Comment by taoist1994** [comment]
从15年到现在一直用山景城IP使用goagent，1年多观察下来一般山景城IP的寿命普遍在1-2个月，而亚洲的IP使用不到1个月一般就歇菜了。封锁山景城的一部分IP地址时，同时又会解封出另一部分的IP，而xx-net是自动扫描的，所以使用扫描山景城IP段是比扫描默认IP列表更有效的策略。

**Comment by HappysurfBlocking** [comment]
顶一个，试了，效果还行

**Comment by HappysurfBlocking** [comment]
质量很高，不过失效很快啊

**Comment by HappysurfBlocking** [comment]
IP Number	289
IP Quality	296

**Comment by hwbasd** [comment]
状态
属性	值
本地网络状态	OK
IP数量	879
IP延迟	100
连接池(帮助)	新:0 已用:49
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	20
屏蔽状态(帮助)	OK
配置

用山景城的ip有个问题就是ip搜索飞快，但是失效也飞快，我瞬间就能搜到数百个IP，但是IP也在逐渐减少。等IP数稳定下来也能用用。

**Comment by jzp820927** [comment]
坚持一天，或者半天应该没问题吧，不可能分分钟变化吧？

**Comment by simonasd** [comment]
用户个人可以尝试这么做，但不适合作为默认设置。
