### ISSUE TITLE
状态是尚未建立连接是什么情况

### ISSUE THREAD

**Issue by theshiny** [XX-net/XX-Net#2696]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 2913
network-status: unknown
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 225
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
network-status: unknown

看信息，是网络有问题，能正常上网吗？

**Comment by tdy218** [comment]
我的今天也出现这个问题了，可以正常上网，但xx-net的config页面显示"尚未建立连接"，然后就无法科学上网了。
