### ISSUE TITLE
这两天一直上不了google，下面是日志，请帮忙看看

### ISSUE THREAD

**Issue by burness** [XX-net/XX-Net#2698]
---

问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

---

诊断信息：
sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
xxnet-version: 2.9.3
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 805
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 504
block-stat: OK
proxy_state: Fail
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
这两天IP被大量封锁，试试删除 data 目录，从新扫描所有IP
