### ISSUE TITLE
linux 下升级后打开 github 提示证书问题

### ISSUE THREAD

**Issue by litel** [XX-net/XX-Net#27]
从 1.0.6 升级倒 1.0.9
应该是 1.0.9 新打开会重新生成一个 CA.crt

我在 chrome 的设置的证书管理里面，删了 goagent 的证书，
再导入这个 1.0.9 的新证书就没问题了。

下面这样有用么？
添加一个升级说明让拷贝一下 CA.crt 或者检测 CA.crt 不同就删除然后重新导入一次。

**Comment by xxnet** [comment]
恩，这个要继续优化，一个是提示，一个自动升级，一个版本管理，要整个流畅都要完善。细节很多啊。

**Comment by xxnet** [comment]
1.1.0 已经实现证书重新导入，除了Windows平台Firefox
