### ISSUE TITLE
1.12.2的autoproxy2pac模块好像刚刚挂了......

### ISSUE THREAD

**Issue by Sherman-Liu** [XX-net/XX-Net#271]
这是现在它自动生成的文件内容，明显不正常啊......完全用不了，SwitchyOmega的PAC模式上网，Chrome直接显示配置错误，老版本1.9.4生成的PAC是正常的，可以直接使用，烦请开发者解惑......
![default](https://cloud.githubusercontent.com/assets/11748513/7370497/1f2e5082-eded-11e4-95fe-2b2d65f68967.PNG)

**Comment by Sherman-Liu** [comment]
顺便，这个问题是刚刚发生的，我已经重新安装了一份全新的，也不行。

**Comment by Sherman-Liu** [comment]
这是1.9.4生成的。
![2](https://cloud.githubusercontent.com/assets/11748513/7370605/c8e61006-eded-11e4-9c28-2dc4212ac612.PNG)

**Comment by internetic** [comment]
加密了

**Comment by Sherman-Liu** [comment]
可是加密了也不应该影响正常使用啊……

**Comment by xxnet** [comment]
从内容上看似乎是 base64没有解码，代码中看没有发现问题，这里确实有改过，我再测试看看。

2015-04-28 20:13 GMT-04:00 Sherman-Liu <notifications@github.com>:

**Comment by zhaohengxing** [comment]
貌似是id号为d60bc6cd8b124a83a1f37bab3b0bd204f663ce3d的提交改的有问题了

         try:
             logging.info('try download %r to update_pacfile(%r)', config.PAC_GFWLIST, filename)
-            autoproxy_content = base64.b64decode(opener.open(config.PAC_GFWLIST).read())
+            try:
+                content = opener.open(config.PAC_GFWLIST).read()
+            except Exception as e:
+                logging.warn("update_pacfile fail:%r", e)
+                return
+            autoproxy_content = base64.b64decode(content)
             logging.info('%r downloaded, try convert it with autoproxy2pac', config.PAC_GFWLIST)
             jsrule = PacUtil.autoproxy2pac(autoproxy_content, 'FindProxyForURLByAutoProxy', autoproxy, default)
             content += '\r\n' + jsrule + '\r\n'

**Comment by xxnet** [comment]
是

2015-04-28 22:06 GMT-04:00 zhaohengxing <notifications@github.com>:

**Comment by xxnet** [comment]
发了1.12.3修复
抱歉，前面的版本修改后没有测试。

2015-04-28 23:39 GMT-04:00 Net XX <xxnet.dev@gmail.com>:

**Comment by Sherman-Liu** [comment]
新版1.12.3经测试已无问题，感谢开发者的辛勤劳动，谢谢。：）
