### ISSUE TITLE
部署XX-Net至GAE时没有填gmail账户和密码的地方

### ISSUE THREAD

**Issue by gz8538** [XX-net/XX-Net#2715]
![image](https://cloud.githubusercontent.com/assets/18277687/14271307/8ad07472-faef-11e5-9d41-7b570706ddd6.png)
在部署XX-Net至GAE时页面显示是这样的 只有填Appid的地方 没有填写gmail账户和密码的地方 请问是怎么回事啊

**Comment by linweijun** [comment]
你填写完成点击开始部署会提示你要登入的。

**Comment by gz8538** [comment]
多谢 刚才试了下 原来是屏蔽广告的插件把弹出窗口给拦截了 怪不得一直部署不了

**Comment by ByeGFW** [comment]
Please close this issue.
@xxnet
