### ISSUE TITLE
mac 双击 start.command时报错，请各位大大看看是为什么？

### ISSUE THREAD

**Issue by zhouweiming** [XX-net/XX-Net#2724]
Apr 05 15:59:20.142 - [DEBUG] create ssl timeout fail.
Apr 05 15:59:20.145 - [WARNING] check_update fail:HTTPError()
Apr 05 15:59:20.145 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /Users/zhouweiming/Downloads/XX-Net-2.9.4/data/downloads/README.md, retry:0
Apr 05 15:59:22.131 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
Apr 05 15:59:22.132 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/zhouweiming/Downloads/XX-Net-2.9.4/launcher/update.py", line 248, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[1][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jzp820927** [comment]
试试终端运行  python start.py

**Comment by crystoneme** [comment]
我一般是在iterm终端运行bash start.command运行xxnet

**Comment by cc941201** [comment]
这个错误是自动更新获取不到版本信息造成的。目前更新模块有bug，所以自动更新被暂时关闭。
应该不会影响使用。

**Comment by zjhzxhz** [comment]
这个Bug不影响使用。
@xxnet 您老打算什么时候修复呀？

**Comment by jzp820927** [comment]
X老大正在搞 安卓APP，怕是没精力搞这个啦

**Comment by zjhzxhz** [comment]
我当年提交了一个PR。然后他没搭理我~
然而我用的是iOS!! Orz

**Comment by jzp820927** [comment]
不过最近IP封锁这么厉害，感觉做 app 的意义都不大了，万一 app 出来了，IP 没了，那就做无用功了，可以观察一段时间，等IP 恢复了，再继续开发 app

**Comment by ByeGFW** [comment]
@xxnet 
Close this issue.
