### ISSUE TITLE
Mac下开启Global Proxy以后，系统中gmail账户显示证书错误

### ISSUE THREAD

**Issue by ccdd9451** [XX-net/XX-Net#2725]
登录时提示：连接不安全，验证服务器证书失败，这可能是由于您的网络配置或代理设置所引起。

终端中运行 sudo xx_net.sh 和 start.command 均显示 GoAgnet CA exits。Chrome + SwitchyOmega运行正常。

同时软件Mendeley也显示证书有误，无法使用代理进行同步

**Comment by cc941201** [comment]
请尝试在钥匙串中把goagent xx-net的证书删掉，再启动xx-net重新导入证书

**Comment by zjhzxhz** [comment]
“Mendeley”了你的身份~

**Comment by ccdd9451** [comment]
证书重新导入有效～赞个
