### ISSUE TITLE
今天突然间变成”尚未建立连接”，why?

### ISSUE THREAD

**Issue by yunyu-Mr** [XX-net/XX-Net#2726]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: 2.8.9
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 2149
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 543
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
试试删掉 data 目录，重新扫描所有IP

**Comment by yunyu-Mr** [comment]
I‘m sorry. I try to remove data directory and rescan IP, but it doesn't work!

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/2727
那就用这个吧
