### ISSUE TITLE
下午装了MySQL,晚上就用不了XX-Net了。。。

### ISSUE THREAD

**Issue by jametang** [XX-net/XX-Net#2729]
---

问题描述：
下午装了MySQL,晚上就用不了XX-Net了。。。
是不是防火墙设置问题？

---

诊断信息：
sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 1017
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 296
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
MySQL 和 XX 有必然联系麽？

**Comment by lh471921250** [comment]
这两个东西没有联系

**Comment by jametang** [comment]
上面打印的ERROR信息该如何解决？？

**Comment by jzp820927** [comment]
没看到哪儿有 ERROR 信息，你是不是贴错地方了

**Comment by jametang** [comment]
汗，又自动好了，之前提示网络连接或者防火墙设置有问题

**Comment by jzp820927** [comment]
估计是 IP 不稳定造成的

**Comment by jametang** [comment]
难怪！另外问个问题，我是用的朋友的APPID，google官方是不是已经不提供APPID申请了？

**Comment by jzp820927** [comment]
可以申请啊，只要有 google 账号就行，应该账号可以申请 12个 appid
