### ISSUE TITLE
一直提示“当前状态：发生异常”

### ISSUE THREAD

**Issue by hsyyhcc** [XX-net/XX-Net#273]
![111](https://cloud.githubusercontent.com/assets/12161569/7382790/02c6f408-ee47-11e4-8be9-ff50b3ad25bf.jpg)

**Comment by xxnet** [comment]
请问是xx-net哪个版本？

你可以在Chrome里试试按 F12，弹出找到Console，看看有没有红字告警

2015-04-28 20:09 GMT-04:00 hsyyhcc <notifications@github.com>:

**Comment by xxnet** [comment]
此处对后面使用没有影响。

trunk上加了更详细的提示，如果再有出现，可以显示更多信息，帮助解决问题。
