### ISSUE TITLE
本地网络中断不会造成有效ip损失（修改了）

### ISSUE THREAD

**Issue by abchb99** [XX-net/XX-Net#2733]
标题改了下，结果这儿的内容丢失了。

**Comment by jzp820927** [comment]
那你估计只有经常备份 good_ip.txt 了

**Comment by yfdyh000** [comment]
"本地连接虽然是通的"时能访问百度吗，如果不能应该会自动中止才对。#2560。

**Comment by abchb99** [comment]
抱歉，是我弄错了，XX-Net没有这个问题，我刚测试了。
实际上我是使用https://github.com/xyuanmu/XX-Mini/ 时发现这个问题的，因为我认为主要的网络模块和XX-Net是一样的，所以发到这边来了，现在看来，XX-Mini精简掉了网络判断的部分。
另外回楼上，我说的那个情况出现时，百度是不通的，因为任何外网都不通。这个情况XX-Net可以判断出来，因为在管理界面看到提示网络连接有问题，这时所有good ip都保留，并不会减少，而XX-Mini会逐步减少good ip。

**Comment by yfdyh000** [comment]
那么关掉这个问题吧，点Close。可以去XX-Mini那边建议一下。
