### ISSUE TITLE
Ubuntu下怎么开启全局代理

### ISSUE THREAD

**Issue by roylin1994** [XX-net/XX-Net#2736]
Ubuntu的图标没有切换全局代理 的选项，那一般是怎么切换呢？

**Comment by jzp820927** [comment]
看你具体怎么用了，用的地方不一样，设置方法也不一样，一般来说，可以设置代理环境变量可以解决大部分问题

**Comment by roylin1994** [comment]
怎么说呢？ 比如我想git clone 或者用墙外的源。 怎么设置呢？ 就是想让全局走代理，例如 wget之类的

**Comment by jzp820927** [comment]
好像是配置 git 的 .gitconfig 配置文件，具体怎么配置，你可以 google 一下

**Comment by yeahwu** [comment]
linux下没那么简单，很麻烦

**Comment by zjhzxhz** [comment]
@jzp820927 这和.gitconfig有什么关系
@roylin1994 如果你连代理都不会设置的话 你还是别用Linux了吧

如果你在用Unity的桌面环境，在右上角应该可以调出“(System) Settings”，然后应该有一个“Network”，然后左边有一个“Proxy”吧。
太久不用Ubuntu了~ 但差不多是这样~

**Comment by ByeGFW** [comment]
Look at this.
![screenshot from 2016-04-06 12 38 47](https://cloud.githubusercontent.com/assets/17879520/14305955/914c7106-fbf4-11e5-8aac-a8539d66c73a.png)

**Comment by N46AN** [comment]
@roylin1994 建议 放弃 Linux 桌面全局代理的想法。哪个程序要用代理针对设置
例如命令行代理可用 proxychains。不是每个程序都遵守 http_proxy, https_proxy 变量的

**Comment by roylin1994** [comment]
@zjhzxhz 就算我不会配置代理，我就不能用linux了？我就是要长期在Ubuntu下面开发的。然后，我只是提出个问题，而你的回答也并没有解决我的问题，为什么回答别人问题要先秀一下优越呢？
@ByeGFW 谢谢你！我知道这个设置，但不知道具体的url。
@N46AN 懂你的意思了，谢谢。

**Comment by roylin1994** [comment]
@N46AN  是不是有些程序走的是sock层？不能用http代理？

**Comment by yeahwu** [comment]
俺说过很麻烦，而且gae也不适合全局，下面这个教程你看看
https://groups.google.com/forum/?hl=zh-CN#!topic/fqlt/f4ksOZpB3Dw

**Comment by roylin1994** [comment]
@yeahwu 谢谢，让我研究下。感觉在Ubuntu下面，还是直接买个VPN合适点。不然做开发，用到国外的源，很蛋疼。

**Comment by yeahwu** [comment]
其实还有一个很简单的方案，就是自己编译vpngate，相信搞开发的你，这个难不倒你吧！

**Comment by roylin1994** [comment]
@yeahwu  vpngate？ 是个什么东西？一个产品？

**Comment by yeahwu** [comment]
神器，基于p2p的开源vpn
然而你都懒得google一下

**Comment by roylin1994** [comment]
@yeahwu  google过了，只是有很多结果。

**Comment by zjhzxhz** [comment]
@roylin1994 
那两个账号都是我 - -|||

**Comment by ByeGFW** [comment]
@roylin1994
人家修一下优越怎么了~
遇到问题请先Google，不要总想着求助于人。
这是作为程序员的第一守则。 :)

**Comment by zjhzxhz** [comment]
@roylin1994
就是~ 我秀一下优越怎么了！
而且我不是给你操作的步骤了嘛~

**Comment by jzp820927** [comment]
vpngate 都已经被协议识别了。别想了

**Comment by roylin1994** [comment]
@zjhzxhz @ByeGFW  好吧，你赢了。。= =。 不过还是谢谢你把具体的url告诉我了

**Comment by zjhzxhz** [comment]
@roylin1994 
哈哈哈哈哈~
既然问题解决了 请关闭这个issue吧~

**Comment by yeahwu** [comment]
为什么会推荐vpngate，因为全局模式下俺还真没碰到有那个软件像vpngate这么牛逼接管整个网络。

**Comment by simonasd** [comment]
vpngate是直接搞了个虚拟网卡，和普通的代理设置还不一样
