### ISSUE TITLE
突然就“Connection not established yet.”了，好悲催

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#2739]
---

问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

---

诊断信息：
sys-platform: AMD64, Windows-10-10.0.14295
os-system: Windows
os-version: 10.0.14295
os-release: 10
os-detail: Version:10-0; Build:14295; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 2848 / 2668
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 0
ip-quality: 100
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
我今天中午升级WIN10了，升成了14295内测版，会跟这个有关系吗

**Comment by nly4lov** [comment]
添加与删除程序里搞掉了CHROME，然后硬盘里删除它的安装目录，重装CHROME，重装插件，重新布署。。。能上了。。。又不能了。。。。又能了。。。。。我日啊

**Comment by yunyu-Mr** [comment]
我也是，重新扫描IP一直失败。是IP枯竭了么？

**Comment by jzp820927** [comment]
IP问题，试试删除 data 重新扫描所有IP
