### ISSUE TITLE
已更新为最新1.12.2一切正常，证书问题怎么解决？

### ISSUE THREAD

**Issue by hehh2001** [XX-net/XX-Net#274]
今早更新到了1.12.2版，仔细看了一下Block保护机制,刚跑起来速度很慢，用一段时间后速度相当不错，顑谢楼主所做的工作，LINUX下一切正常。谷歌的IP大部份的确被做处理了，很多IP又不能一下完全断开，用这种下三烂的方法来让使用感受变差。最后想问的是我怎样删除原版证书，用sudo  .start.sh  的方法无法导入证书，这样使我的所有HTTPS的网站无法打开。

**Comment by xxnet** [comment]
你如果是Firefox浏览器，可以 设置-》高级-》证书里找到，删除老的，导入新的

在 2015年4月28日 下午11:22，he <notifications@github.com>写道：

**Comment by hehh2001** [comment]
奇怪的是上午还报证书问题，下午就完全好了，没任何问题了，我用的是CHROME,

**Comment by xxnet** [comment]
xx-net会自动导入证书，但Chrome需要重启才能生效

2015-04-29 4:46 GMT-04:00 he <notifications@github.com>:
