### ISSUE TITLE
俺来给大家一点信心，目测复活了一批ip

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2744]
就算死ip，大家也要抱着平常心，因为以后还是会死滴

![2016-04-06 18 46 37](https://cloud.githubusercontent.com/assets/13328328/14314134/2a026814-fc28-11e5-8d91-dd1a34e454dc.png)

**Comment by yeahwu** [comment]
@Cat7373 今天女神和她男朋友分手鸟，为毛俺感觉很开森捏？

**Comment by LaughXP** [comment]
一直504啊！！！

**Comment by yeahwu** [comment]
你需要的是这个   https://github.com/XX-net/XX-Net/issues/2727

**Comment by jtlifos** [comment]
这个形式的ip要转换吗？

**Comment by yeahwu** [comment]
不需要，替换就好了

**Comment by Cat7373** [comment]
@yeahwu 什么鬼。。。

**Comment by jtlifos** [comment]
可是这些ip的前面部分看不到啊

**Comment by jzp820927** [comment]
XX自带的IP列表确实在慢慢开始复活了。

**Comment by yeahwu** [comment]
看来三弹放完，xx也差不多活了，手上本来准备好了第四弹，留着自己用吧。

**Comment by Cat7373** [comment]
从网页上试图删除ip_range使用XX自带的range的时候遇到个小Bug。。
我删光了内容保存，然后日志里各种抛错- -
大概就是XX还是在读取那个空白的ip_range，而不是用自带的range- -

**Comment by yeahwu** [comment]
然而还是建议你先用俺那个ip段，效率高点

**Comment by Robin-front** [comment]
@yeahwu 好东西不能掖着，第四弹放马来吧，哈哈

**Comment by malthae** [comment]
@yeahwu 哈哈 已经替换了第三波的IPRANGE，等复活的差不多了再换回默认的。。。

**Comment by CongZeng** [comment]
第四弹发出来啊

**Comment by yeahwu** [comment]
第三弹延时已经很不错了，大家还是将就着用吧，没有第四弹，呵呵
