### ISSUE TITLE
xvideos里的很多视频都无法播放

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#275]
点开之后一直就是1%的状态
日志错误：Apr 29 11:54:06 - [WARNING] APPID error:502 url:http://porn.im.6bb2c200.7866732.x.xvideos.com/videos/flv/c/6/c/xvideos.com_c6cb2d2eb052a09dad5a5ec627c0bddb.flv?e=1430290372&ri=1024&rs=85&h=41910c994b3169d2a8dcc9ad6a9d8a6e

**Comment by xxnet** [comment]
服务端有重新部署过吗？

2015-04-28 23:54 GMT-04:00 causlayer <notifications@github.com>:

**Comment by causlayer** [comment]
我是10.9以后部署的服务器端，还需要重新部署吗？

**Comment by Cat7373** [comment]
经过测试的确是无法播放- -

**Comment by Pd69bq** [comment]
porn.....

**Comment by xxnet** [comment]
请给出浏览器的地址

你给出的地址是有失效的，过期都无法访问的。

2015-04-29 4:22 GMT-04:00 Chris Baconham <notifications@github.com>:

**Comment by Cat7373** [comment]
随便点开一个都是1%- -
比如这个
http://www.xvideos.com/video11092902/big_tit_18yr_old_girl_fucks

**Comment by xxnet** [comment]
研究发现：

xvideo对下载速度做了限制，因此在限定的时间内无法下载完分片，GAE报超时，导致一直出错。

解决方法也很简单，限制分片下载的大小，默认大于1M的，修改如下：
编辑：
================分割线=================
[autorange]
maxsize = 500304
================分割线=================
把内容保存到：
data/goagent/manual.ini

然后重启goaent.

如果再出现问题，可以试着再改小。



2015-04-29 9:40 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
threads = 3
maxsize = 1572864
waitsize = 524288
bufsize = 8192

这是Goagent的参数
为何明明比较大反而还可以用呢
而且还多一根线程

**Comment by Cat7373** [comment]
通过浏览器的审查元素看到，似乎是以下URL请求失败导致的无法播放：
http://videos1.cdn.xvideos.com/videos/flv/a/3/1/xvideos.com_a318c7c4ca665f629a5f031ebe49c2be.flv?e=1430371488&ri=1024&rs=85&h=b4b3d9e8f819b695e9372b6ca9f3a3e1

Apr 30 10:24:31 - [INFO] GAE t:953 s:29844 200 http://img-l3.xvideos.com/videos/thumbslll/a3/18/c7/a318c7c4ca665f629a5f031ebe49c2be/a318c7c4ca665f629a5f031ebe49c2be.4.jpg
Apr 30 10:24:31 - [WARNING] gae_handler err:error(10053, '') http://videos1.cdn.xvideos.com/videos/flv/a/3/1/xvideos.com_a318c7c4ca665f629a5f031ebe49c2be.flv?e=1430371375&ri=1024&rs=85&h=5f876341f14b2195fbf2f24275174bf8 

以及刚启动Goagent后的几分钟内，日志页显示为纯空白，不知何故。

**Comment by fhzyfjy** [comment]
data/goagent下面没有manual文件。是要自建吗？
