### ISSUE TITLE
给你们看看我的…………IP这么多……

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#2755]
![2016-04-06](https://cloud.githubusercontent.com/assets/17242539/14318972/e1bf8cf2-fc41-11e5-898d-536209a1ad04.png)

**Comment by xiaoyan94** [comment]
![2016-04-06 1](https://cloud.githubusercontent.com/assets/17242539/14319093/6d425ea8-fc42-11e5-85c4-9e359f1f511b.png)

**Comment by Tandent** [comment]
共享一下IP地址啊

**Comment by thinkfree1992** [comment]
求共享

**Comment by jzp820927** [comment]
这不会是传说中的 移动网吧

**Comment by 935352** [comment]
你不是开了个VPN在那里扫跑来得瑟吧哈哈

**Comment by zjhzxhz** [comment]
教育网吗？可是我都没有这么多IP呢~ 只剩下1400多个了。
之前的确有3000个~
一定是我离防火墙太近了。Orz

**Comment by zjhzxhz** [comment]
嘚瑟贴~ 鉴定完毕~

**Comment by ming1208** [comment]
不要得瑟 要共享，偷偷的发给我们就行

**Comment by zxeoc** [comment]
看了第二张图才发现原来那不是自己P上去的，是桌面歌词- -

**Comment by simonasd** [comment]
1. IP真多
2. Chrome插件真多

总结：楼主网络好、电脑配置好。壕
