### ISSUE TITLE
youtube  视频下载不完整的问题

### ISSUE THREAD

**Issue by yqfang** [XX-net/XX-Net#276]
如 #119 所述

**Comment by xxnet** [comment]
好的，这个问题需要过多点时间再处理，争取先把自动升级到github版先实现了。

2015-04-29 0:07 GMT-04:00 yqfang <notifications@github.com>:

**Comment by yqfang** [comment]
好的！ 之前1.8.X已经修复了这个问题，升级到1.12.X后又出现了

**Comment by xxnet** [comment]
1.13.6解决了youtube下载视频只有32M问题，
需要重新部署服务端。

请测试。

在 2015年4月29日 上午12:11，Net XX <xxnet.dev@gmail.com>写道：

**Comment by xxnet** [comment]
1.13.6解决了youtube下载视频只有32M问题，
需要重新部署服务端。

请测试。

在 2015年4月29日 上午2:52，yqfang <notifications@github.com>写道：
