### ISSUE TITLE
如何 启用 pythonw 而不是 python？

### ISSUE THREAD

**Issue by theprestigeqaz** [XX-net/XX-Net#277]
两台电脑，一台电脑打开xxnet后默认的进程是pythonw，可以翻过长城；
另一台电脑，默认的进程是python，就不能翻过。
试过在start.bat将python改成pythonw，则xxnet不能正常启动。

有什么方法可以设置使用pythonw？

1.8.4、1.9.4以及最新的版本均如此。

**Comment by xxnet** [comment]
strat.vbs就是pythonw启动的。

不过应该没有相关。

在 2015年4月29日 上午2:56，theprestigeqaz <notifications@github.com>写道：
