### ISSUE TITLE
504GARProxy Time Out

### ISSUE THREAD

**Issue by a63031626** [XX-net/XX-Net#2774]
其他网站，如facebook都可以访问，只有谷歌搜索的时候，出现这个错误。
求大神指导。

**Comment by jzp820927** [comment]
看看日志，有什么报错信息

**Comment by a63031626** [comment]
no enough ip 应该是这个吧。
没有 是不是大家都一样啊

**Comment by yeahwu** [comment]
看到504就赶紧换ip段嘛
https://github.com/XX-net/XX-Net/issues/2727

**Comment by a63031626** [comment]
可以了 谢谢
