### ISSUE TITLE
更新的真快呀，楼主辛苦了。LINUX版本跑起来后只能是全局吗？？能取消全局吗？？？

### ISSUE THREAD

**Issue by hehh2001** [XX-net/XX-Net#278]
两个问题，第一，CHROME怎样导入新的证书，我一直用原版的goagent，浏览器用的是chrome  
第二，主要是不太稳定，一会好，一会什么网站都打不开， 代带用的是Proxy Listen	127.0.0.1:8087  
端口，PAC URL	http://127.0.0.1:8086/proxy.pac

**Comment by hehh2001** [comment]
我在LINUX下用的是chrome+Proxy SwitchySharp

**Comment by hehh2001** [comment]
只有在全局下才能打开网站？何故？

**Comment by xxnet** [comment]
1.12.2 的pac有bug，请用1.12.3

2015-04-29 5:16 GMT-04:00 he <notifications@github.com>:

**Comment by hehh2001** [comment]
哦，自定义规则没办法实现，是proxy  switchysharp的问题还是PAC的问题？看中国，大纪元这样的网站打不开，加入自定义规则用GOAGENT代理也打不开？？

**Comment by xxnet** [comment]
规则方面不了解，请试试强制GoAgnet模式
