### ISSUE TITLE
google的ip会被封完吗

### ISSUE THREAD

**Issue by BENZJ** [XX-net/XX-Net#2780]
一直很好奇。这些ip都是大家都可见的。一次把已知的封锁完不就再也用不了了。可是好像用了好多年了。都还可以用。

**Comment by gs-liut** [comment]
朝鲜封完了啊

**Comment by taoist1994** [comment]
不会，我观察了两年山景城的IP段，一般每1-2个月封锁一部分的同时会释放另一部分，个人认为是由于主干路由器负荷太大，封锁过多会影响国内网速。

**Comment by jzp820927** [comment]
确实这种死了活，活了又死的封法，在没有XX之前也是可以达到目标的

**Comment by fengixng** [comment]
如果你要问能不能的话，那么答案是能
你要问会不会的话，暂时看来，不会
