### ISSUE TITLE
用xx-net浏览github出现websocket连接错误

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#2787]
使用switchy omega做切换，连接github时会出现下面的错误：
WebSocket connection to 'wss://live.github.com/_sockets/MTM4NzM4MDg6ZDFhNmQxZDI3MjQzNDU2YmJiNjBiODg1…YjQ2ZjcwZjg1OTU3ZWIxMjQzZTZiOQ==--1dbf1c0c4e4dfd639abfdad5a35a7387e6c18cc1' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by jzp820927** [comment]
这是用的 PHP 模式，还是 X_tunnel 模式

**Comment by taoist1994** [comment]
XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 399 / 396
network-status: OK
connected-link: 7 / 48
scan-ip-thread-num: 100
ip-quality: 421
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yeahwu** [comment]
是不是出现黄字？
如果是黄字的话，就当没看到。又不是不能用

**Comment by taoist1994** [comment]
Apr 09 16:52:59.355 - [WARNING] Method OPTIONS not support in GAEProxy for https://api.github.com/_private/browser/stats
Apr 09 16:53:06.764 - [WARNING] gae_handler.handler send response fail. t:20 e:error(10053, '') https://live.github.com/_sockets/

**Comment by jzp820927** [comment]
Apr 09 16:52:59.355 - [WARNING] Method OPTIONS not support in GAEProxy for

GAE 不支持 options 方法

**Comment by taoist1994** [comment]
goproxy有解决这个问题吗？

**Comment by jzp820927** [comment]
这是 GAE 的现在，和软件没有关系
