### ISSUE TITLE
google搜出来的链接点不开

### ISSUE THREAD

**Issue by hanwei2008** [XX-net/XX-Net#2788]
在www.google.com.hk进行搜索, 直接点击搜索结果的标题链接大部分网站打不开. 但是直接复制搜索结果中该处的url到浏览器地址栏是能访问成功的. 希望大神们能够解决, 感谢!

**Comment by jzp820927** [comment]
https://www.google.com/ncr

**Comment by Anudorannador** [comment]
应该是 com.hk 被封锁的比较厉害。直接用 <https://www.google.com/ncr> 会比较好。 NCR，NO Country Redirect，不进行国家跳转。
