### ISSUE TITLE
楼主可否在界面上加一个断开连接的按钮

### ISSUE THREAD

**Issue by latrikcoasler** [XX-net/XX-Net#279]
既然连得越久越容易被封锁ＩＰ，可否在界面上加断开连接的按钮，不用时点击断连，使用时点击打开。

**Comment by xxnet** [comment]
不是连越久越容易被封。

目前看反馈，是跟地区有关系。

在 2015年4月29日 上午6:12，latrikcoasler <notifications@github.com>写道：

**Comment by hehh2001** [comment]
我看没必要，因为在没有翻墙的情况下，日志是没有输出显示的。linux下是怎样实现开机自启动的？我昨天还试着自已写systemctl方式的自启，今天才看到已经有这样的功能了，打开一试，比我写的还好用。
