### ISSUE TITLE
Mac 能启动后结束脚本么

### ISSUE THREAD

**Issue by litel** [XX-net/XX-Net#28]
goagent 的，在 osx 上面启动了 .command 之后，会创建一个图标在任务栏上，而且原脚本也推出了，所有操作都由那个图标来做。
这样 terminal 就可以关掉了，不用老开着一个窗口。

linux 下的也是，脚本执行完后如果能自动推出的话，开机启动脚本也好写一点。

**Comment by xxnet** [comment]
可以做一个，思路是参考 goagent/3.1.34/local/goagent-osx.command
在launcher/1.0.1/实现一个osx_tray.py ，需要实现的功能，可以参考non_tray.py, win_tray.py 
  
手上没有osx机器，希望有哪位朋友帮忙弄一下，目前代码都尽量做到的简单易懂，
看不懂是我还没有整理好，有问题我尽量解答。

**Comment by xxnet** [comment]
包括做到开机启动，都可以做到UI界面里，实现点一下即设置好，都应该可以做到，网上有很多资料，希望有编程经验的一起参与

**Comment by xxnet** [comment]
1.1.0 Linux下开机后启动的已经实现了
Mac的还有待完善，希望有Mac, 熟悉Python的朋友帮忙搞搞，
goagent/xxx/local/proxy.command 可以参考
