### ISSUE TITLE
导入证书无效，无法浏览HTTPS网站。

### ISSUE THREAD

**Issue by bniw** [XX-net/XX-Net#280]
我是从前天在网上搜到XX-NET并开始使用的。开始时使用的是低版本，昨天升级到新的1.12.2版。
删除旧的证书，导入XX-Net-1.12.2\data\goagent下生成的证书，可以正常浏览HTTPS网址。
可今天早上再开机，打开HTTPS网站时提示证书错误，删掉证书再导入，没有作用。
来回重复多次依然无效。后来也不知道什么原因又可以正常浏览了。下午关机，晚上再上线，又提示证书错误了。还是删除后重新导入无效。请问是什么原因？
![qq 20150429182705](https://cloud.githubusercontent.com/assets/12168357/7389110/82c7e6fc-ee9d-11e4-8526-fbf47d38b0c3.png)
![qq 20150429182751](https://cloud.githubusercontent.com/assets/12168357/7389113/89cadeb4-ee9d-11e4-9e27-5f3ca405d07c.png)

**Comment by bniw** [comment]
呃....我是楼主。刚才发完求助帖发现又有新的1.12.3版本了，更新，删证书，导入证书，可以浏览HTTPS网站了。还没来得及测试关机或者重启后会不会和今天早上一样....

**Comment by xxnet** [comment]
xx-net会自动导入证书，Chrome需要重启，不过此处缺一个提示。
  也许来个弹出窗口？

在 2015年4月29日 上午6:37，bniw <notifications@github.com>写道：

**Comment by bniw** [comment]
我的浏览器是firefox。刚才为了测试正常不正常，特意重启了一下电脑，这次没问题了。对chrome要重启才生效的问题，加个弹出窗口是个好主意啊。

**Comment by annawongfo** [comment]
我的证书导入也无效，Chrome 版本41.0.2272.101 m (64-bit)
手动导入，重启Chrome，重启电脑都试过，还是出现“您的连接不是私密连接
攻击者可能会试图从support.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。”

**Comment by xxnet** [comment]
试试删除 data/goagent/certs目录

在 2015年4月29日 上午8:57，annawongfo <notifications@github.com>写道：

**Comment by bniw** [comment]
貌似找到了只要重启就提示证书错误的原因了。
我在使用XX-NET前一直用goagent，因为想留着它做备胎，所以没有删掉。
它的进程python27一直残留在启动项里。
刚才禁止了python27随系统启动，重启了两次电脑，正常了。

**Comment by xxnet** [comment]
ok，请关闭bug

在 2015年4月29日 下午9:24，bniw <notifications@github.com>写道：

**Comment by GoTop** [comment]
不启动goagent后，用xx-net还是提示错误：

This Connection is Untrusted

You have asked Firefox to connect securely to www.facebook.com, but we can't confirm that your connection is secure.

Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified.
What Should I Do?

If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.
