### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by DeepDeepDark** [XX-net/XX-Net#2805]
1.点击start.vbs无法启动，只能通过先前设置的开机启动启动
2.已在fiefox浏览器中用pan设置GoAgent代理，仍显示“请检查浏览器代理设置”，下载了“懒人集成浏览器版”后照旧

**Comment by DeepDeepDark** [comment]
第一个已自行解决

**Comment by yeahwu** [comment]
懒人集成版，用的是autoproxy插件，代理方面应该没有问题，你在集成的浏览器地址栏输入127.0.0.1:8085 看看

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by DeepDeepDark** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:120 good:1
network-status: OK
connected-link: new:1 used:0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by zhouxiaodo** [comment]
@yeahwu ，我用你推荐的工具，扫出来的
61.86.203.126 235 *.googlevideo.com gvs 1.0
77.42.249.106 1249 *.googlevideo.com gvs 1.0
61.86.203.109 241 *.googlevideo.com gvs 1.0
115.254.97.113 2855 *.googlevideo.com gvs 1.0
77.42.249.114 1094 *.googlevideo.com gvs 1.0
115.254.97.101 1134 *.googlevideo.com gvs 1.0
173.194.2.72 2662 *.c.docs.google.com gvs 1.0
210.2.185.104 4100 *.googlevideo.com gvs 1.0
216.177.189.144 10001 *.googlevideo.com 
173.194.67.116 1714 upload.video.google.com gws
210.2.185.119 3885 *.googlevideo.com gvs 1.0
77.42.249.104 1073 *.googlevideo.com gvs 1.0
79.171.121.144 6331 *.googlevideo.com gvs 1.0
36.76.161.200 1112 google.com gws
210.2.185.105 2027 *.googlevideo.com gvs 1.0
177.100.48.54 10921 *.googlevideo.com 
61.86.203.111 248 *.googlevideo.com gvs 1.0
115.254.121.244 1330 *.googlevideo.com gvs 1.0
210.2.185.120 2357 *.googlevideo.com gvs 1.0
176.255.201.33 12838 *.googlevideo.com 
210.2.185.76 2195 *.googlevideo.com gvs 1.0
222.165.163.83 1703 google.com gws
203.233.126.244 2907 *.googlevideo.com gvs 1.0
220.255.2.150 1386 *.googlevideo.com gvs 1.0
添加到xx-net那个文件

**Comment by yeahwu** [comment]
代理和证书的问题，你到wiki里再看看教程

**Comment by DeepDeepDark** [comment]
谢谢

**Comment by DeepDeepDark** [comment]
终于好了
