### ISSUE TITLE
Is  xx-net dead ?

### ISSUE THREAD

**Issue by CRISzzz** [XX-net/XX-Net#2806]

**Comment by jzp820927** [comment]
no, xx-net not dead

**Comment by yeahwu** [comment]
然而你们的英文差得离谱，连俺这种就认识ABCD的人，都知道你们在说什么！

**Comment by xiaoas** [comment]
I hope so 
though I don't think so
the Ips left are being banned quicker & quicker now!
I'm not optimistic about the future at all
