### ISSUE TITLE
[转]看过很不错的一些话

### ISSUE THREAD

**Issue by vcteps** [XX-net/XX-Net#2807]
你所谓的国家，不过是一群自利者的婊子，它们爱怎么玩就怎么玩，你又能决定半点？...
日本从一个贫困的农业国......，而中国直到今天还是一群土匪的后代，成了它们享乐的天堂...
日本1870年实现的东西，我们再过1870年恐怕也实现不了
建议大家看看《走向共和》最后一集，孙中山的演讲。

希望大家下辈子都能投个好胎，永远不要来这个糜烂的国家，扶不起的阿斗国，哪怕去非洲也不要来这个蛆虫一般的国家。

这个十几亿人吃地沟油和毒奶粉，贪官、土匪和二代们吃特供的国家

**Comment by hcym** [comment]
真的很烦

共产党不是好人，但都是中国人里相对精英企图心更强的家伙

魔鬼的对立面也不是天使

就算共产党崩溃，也和49年国民党溃败一样

能替代它们上台的除了更加无耻更加贪婪不会有其他不同

**Comment by vcteps** [comment]
你觉得烦不要看就行了，仁者见仁，智者见智的东西，没人强迫你什么

**Comment by Freedom000** [comment]
Github什么时候沦为这种话题的工具了...

**Comment by vcteps** [comment]
猪圈里的猪总觉得它们的主人是精英，于是要翻墙来秀对主子的仰慕之情，哈哈哈哈，真是滑天下之大稽，要么就是冷嘲热讽，想想真是活该生在猪圈里啊。
夏虫不可语冰，
不过希望多少能让某些人多些思考的空间。真寒心啊，也许这就是猪的命运如此的原因吧。
