### ISSUE TITLE
升级到1.12.3还是无法翻墙—升至1.12.5，证书错误继续—1.12.5问题暂时解决

### ISSUE THREAD

**Issue by annawongfo** [XX-net/XX-Net#281]
GoAgent状态信息
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
XX-Net Version	1.12.3
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	annawongfo|annawongsummer
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2983
connected link	14
ip_connect_interval	

Apr 29 18:39:53 - [DEBUG] create_ssl 60.199.175.167 fail:timed out c:0 h:0
Apr 29 18:39:53 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:53 - [DEBUG] network is ok
Apr 29 18:39:54 - [DEBUG] get ip:210.245.14.173 t:1064
Apr 29 18:39:54 - [DEBUG] get ip:64.233.178.199 t:1064
Apr 29 18:39:54 - [DEBUG] get ip:64.233.177.95 t:1038
Apr 29 18:39:54 - [DEBUG] get ip:173.194.207.193 t:1038
Apr 29 18:39:54 - [DEBUG] get ip:64.233.163.143 t:1038
Apr 29 18:39:54 - [DEBUG] get ip:210.245.14.157 t:1038
Apr 29 18:39:55 - [DEBUG] create_ssl 210.245.14.173 fail:timed out c:0 h:0
Apr 29 18:39:55 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:55 - [DEBUG] create_ssl 64.233.178.199 fail:timed out c:0 h:0
Apr 29 18:39:55 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:56 - [DEBUG] create_ssl 64.233.177.95 fail:timed out c:0 h:0
Apr 29 18:39:56 - [DEBUG]LOG_EXCEPT: report_connect_fail network fail recently, Except:[Errno 9] Bad file descriptor
Apr 29 18:39:56 - [DEBUG] create_ssl 173.194.207.193 fail:timed out c:0 h:0
Apr 29 18:39:56 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:56 - [DEBUG] create_ssl 64.233.163.143 fail:timed out c:0 h:0
Apr 29 18:39:56 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:56 - [DEBUG] create_ssl 210.245.14.157 fail:timed out c:0 h:0
Apr 29 18:39:56 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:56 - [DEBUG] get ip:173.194.37.202 t:1039
Apr 29 18:39:56 - [DEBUG] get ip:173.194.206.31 t:1039
Apr 29 18:39:57 - [DEBUG] get ip:173.194.122.11 t:1064
Apr 29 18:39:57 - [DEBUG] get ip:78.37.100.251 t:1064
Apr 29 18:39:57 - [DEBUG] get ip:202.169.193.93 t:1064
Apr 29 18:39:57 - [DEBUG] get ip:1.179.248.123 t:1064
Apr 29 18:39:58 - [DEBUG] create_ssl 173.194.37.202 fail:timed out c:0 h:0
Apr 29 18:39:58 - [DEBUG] create_ssl 173.194.206.31 fail:timed out c:0 h:0
Apr 29 18:39:58 - [DEBUG] network is fail
Apr 29 18:39:58 - [DEBUG] report_connect_fail network fail
Apr 29 18:39:58 - [DEBUG] network is ok
Apr 29 18:39:58 - [DEBUG] create_ssl 173.194.122.11 fail:timed out c:0 h:0
Apr 29 18:39:58 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:58 - [DEBUG] create_ssl 78.37.100.251 fail:timed out c:0 h:0
Apr 29 18:39:58 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:58 - [DEBUG] create_ssl 202.169.193.93 fail:timed out c:0 h:0
Apr 29 18:39:58 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:58 - [DEBUG] create_ssl 1.179.248.123 fail:timed out c:0 h:0
Apr 29 18:39:58 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:39:59 - [DEBUG] get ip:173.194.65.142 t:1023
Apr 29 18:39:59 - [DEBUG] get ip:64.233.163.86 t:1023
Apr 29 18:39:59 - [DEBUG] get ip:216.58.209.207 t:1026
Apr 29 18:39:59 - [DEBUG] get ip:1.179.248.55 t:1026
Apr 29 18:39:59 - [DEBUG] get ip:208.117.226.27 t:1026
Apr 29 18:39:59 - [DEBUG] get ip:216.58.221.119 t:1026
Apr 29 18:40:00 - [DEBUG] create_ssl 173.194.65.142 fail:timed out c:0 h:0
Apr 29 18:40:00 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:00 - [DEBUG] create_ssl 64.233.163.86 fail:timed out c:0 h:0
Apr 29 18:40:00 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:01 - [DEBUG] create_ssl 216.58.209.207 fail:timed out c:0 h:0
Apr 29 18:40:01 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:01 - [DEBUG] create_ssl 1.179.248.55 fail:timed out c:0 h:0
Apr 29 18:40:01 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:01 - [DEBUG] create_ssl 208.117.226.27 fail:timed out c:0 h:0
Apr 29 18:40:01 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:01 - [DEBUG] create_ssl 216.58.221.119 fail:timed out c:0 h:0
Apr 29 18:40:01 - [DEBUG] network is ok
Apr 29 18:40:01 - [DEBUG] get ip:64.233.181.86 t:1027
Apr 29 18:40:01 - [DEBUG] get ip:216.58.217.0 t:1027
Apr 29 18:40:02 - [DEBUG] sort ip time:3
Apr 29 18:40:02 - [DEBUG] get ip:64.233.162.118 t:1028
Apr 29 18:40:02 - [DEBUG] get ip:173.194.116.249 t:1039
Apr 29 18:40:02 - [DEBUG] get ip:64.233.171.167 t:1039
Apr 29 18:40:02 - [DEBUG] get ip:216.58.216.54 t:1027
Apr 29 18:40:03 - [DEBUG] create_ssl 64.233.181.86 fail:timed out c:0 h:0
Apr 29 18:40:03 - [DEBUG] create_ssl 216.58.217.0 fail:timed out c:0 h:0
Apr 29 18:40:03 - [DEBUG] network is fail
Apr 29 18:40:03 - [DEBUG] report_connect_fail network fail
Apr 29 18:40:03 - [DEBUG] network is ok
Apr 29 18:40:03 - [DEBUG] create_ssl 64.233.162.118 fail:timed out c:0 h:0
Apr 29 18:40:03 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:03 - [DEBUG] create_ssl 173.194.116.249 fail:timed out c:0 h:0
Apr 29 18:40:03 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:03 - [DEBUG] create_ssl 64.233.171.167 fail:timed out c:0 h:0
Apr 29 18:40:03 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:04 - [DEBUG] create_ssl 216.58.216.54 fail:timed out c:0 h:0
Apr 29 18:40:04 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:04 - [DEBUG] get ip:173.194.37.207 t:1028
Apr 29 18:40:04 - [DEBUG]LOG_EXCEPT: get ip:216.58.213.54 t:1028, Except:[Errno 9] Bad file descriptor
Apr 29 18:40:04 - [DEBUG] get ip:208.117.226.21 t:1028
Apr 29 18:40:04 - [DEBUG] get ip:64.233.186.64 t:1028
Apr 29 18:40:04 - [DEBUG] get ip:74.125.192.165 t:1028
Apr 29 18:40:05 - [DEBUG] get ip:194.78.99.110 t:1039
Apr 29 18:40:05 - [DEBUG] create_ssl 173.194.37.207 fail:timed out c:0 h:0
Apr 29 18:40:05 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:05 - [DEBUG] create_ssl 216.58.213.54 fail:timed out c:0 h:0
Apr 29 18:40:05 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:06 - [DEBUG] create_ssl 208.117.226.21 fail:timed out c:0 h:0
Apr 29 18:40:06 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:06 - [DEBUG] create_ssl 64.233.186.64 fail:timed out c:0 h:0
Apr 29 18:40:06 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:06 - [DEBUG] create_ssl 74.125.192.165 fail:timed out c:0 h:0
Apr 29 18:40:06 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:06 - [DEBUG] create_ssl 194.78.99.110 fail:timed out c:0 h:0
Apr 29 18:40:06 - [DEBUG] network is ok
Apr 29 18:40:06 - [DEBUG] get ip:173.194.115.240 t:1039
Apr 29 18:40:06 - [DEBUG] get ip:64.233.177.133 t:1040
Apr 29 18:40:07 - [DEBUG] get ip:208.117.229.78 t:1040
Apr 29 18:40:07 - [DEBUG] get ip:173.194.122.16 t:1064
Apr 29 18:40:07 - [DEBUG] get ip:64.233.178.142 t:1064
Apr 29 18:40:07 - [DEBUG] get ip:64.233.185.149 t:1065
Apr 29 18:40:08 - [DEBUG] create_ssl 173.194.115.240 fail:timed out c:0 h:0
Apr 29 18:40:08 - [DEBUG] create_ssl 64.233.177.133 fail:timed out c:0 h:0
Apr 29 18:40:08 - [DEBUG] network is fail
Apr 29 18:40:08 - [DEBUG] report_connect_fail network fail
Apr 29 18:40:08 - [DEBUG] network is ok
Apr 29 18:40:08 - [DEBUG] create_ssl 208.117.229.78 fail:timed out c:0 h:0
Apr 29 18:40:08 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:08 - [DEBUG] create_ssl 173.194.122.16 fail:timed out c:0 h:0
Apr 29 18:40:08 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:08 - [DEBUG] create_ssl 64.233.178.142 fail:timed out c:0 h:0
Apr 29 18:40:08 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:09 - [DEBUG] create_ssl 64.233.185.149 fail:timed out c:0 h:0
Apr 29 18:40:09 - [DEBUG] report_connect_fail network fail recently
Apr 29 18:40:09 - [DEBUG] get ip:173.194.207.139 t:1065
Apr 29 18:40:09 - [DEBUG] get ip:64.233.180.112 t:1065

**Comment by xxnet** [comment]
请问是什么地区？什么网络接入商？

有广西电信的网友说无法用

2015-04-29 6:40 GMT-04:00 annawongfo <notifications@github.com>:

**Comment by xxnet** [comment]
connected link 14

表示你已经翻墙了呀，你配置好浏览器的代理了吗？

2015-04-29 7:36 GMT-04:00 Net XX <xxnet.dev@gmail.com>:

**Comment by annawongfo** [comment]
四川电信。Switchysharp一直配置好的。开全局代理的话比自动切换效果稍微好一点，能打开个空白页。

之前截的那段没有红字：

Apr 29 19:50:16 - [DEBUG]LOG_EXCEPT: tcp conn 123.205.251.81 fail t:1001, Except:[Errno 9] Bad file descriptor
Apr 29 19:50:16 - [DEBUG] report_connect_fail network fail recently
Apr 29 19:50:16 - [DEBUG] get ip:74.125.143.73 t:1035
Apr 29 19:50:16 - [DEBUG] get ip:216.58.216.85 t:1035
Apr 29 19:50:17 - [DEBUG] get ip:216.58.212.79 t:1035
Apr 29 19:50:17 - [DEBUG] tcp conn 216.58.220.217 fail t:1001
Apr 29 19:50:17 - [DEBUG] report_connect_fail network fail recently
Apr 29 19:50:17 - [DEBUG] get ip:216.58.211.234 t:1035
Apr 29 19:50:17 - [DEBUG] get ip:123.205.251.122 t:1035
Apr 29 19:50:17 - [DEBUG] get ip:216.58.210.45 t:1035
Apr 29 19:50:17 - [DEBUG] get ip:216.58.220.17 t:1035
Apr 29 19:50:17 - [DEBUG] tcp conn 64.233.180.197 fail t:1001
Apr 29 19:50:17 - [DEBUG] report_connect_fail network fail recently
Apr 29 19:50:17 - [WARNING] create tcp connection fail. <---------
Apr 29 19:50:17 - [WARNING] FWD CONNECT www.google.com.hk:443 create_connection fail <------
Apr 29 19:50:17 - [INFO] GAE CONNECT uib.ff.avast.com:443 
Apr 29 19:50:17 - [DEBUG] tcp conn 84.235.77.30 fail t:1000

**Comment by xxnet** [comment]
刚才发了一个测试版 1.12.4，会滚以前的ip库，你试试。

2015-04-29 7:53 GMT-04:00 annawongfo <notifications@github.com>:

**Comment by annawongfo** [comment]
Apr 29 20:02:29 - [DEBUG] create_ssl 216.58.217.177 fail:timed out c:0 h:0
Apr 29 20:02:29 - [DEBUG] network is ok
Apr 29 20:02:30 - [DEBUG] get ip:78.37.100.241 t:1021
Apr 29 20:02:30 - [DEBUG] create_ssl 216.58.221.173 fail:timed out c:0 h:0
Apr 29 20:02:30 - [DEBUG] create_ssl 64.233.161.198 fail:timed out c:0 h:0
Apr 29 20:02:30 - [DEBUG] network is fail
Apr 29 20:02:30 - [DEBUG] report_connect_fail network fail
Apr 29 20:02:30 - [DEBUG] create_ssl 210.139.253.157 fail:timed out c:0 h:0
Apr 29 20:02:30 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:30 - [DEBUG] create_ssl 216.58.210.166 fail:timed out c:0 h:0
Apr 29 20:02:30 - [DEBUG]LOG_EXCEPT: report_connect_fail network fail recently, Except:[Errno 9] Bad file descriptor
Apr 29 20:02:30 - [DEBUG] create_ssl 216.58.216.146 fail:timed out c:0 h:0
Apr 29 20:02:30 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:30 - [DEBUG] network is ok
Apr 29 20:02:31 - [DEBUG] get ip:216.58.209.97 t:1021
Apr 29 20:02:31 - [DEBUG] get ip:216.58.222.40 t:1021
Apr 29 20:02:31 - [DEBUG] get ip:64.233.167.102 t:1022
Apr 29 20:02:31 - [DEBUG] get ip:216.58.216.216 t:1026
Apr 29 20:02:31 - [DEBUG] get ip:210.153.73.24 t:1027
Apr 29 20:02:32 - [DEBUG] create_ssl 78.37.100.241 fail:timed out c:0 h:0
Apr 29 20:02:32 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:33 - [DEBUG] get ip:216.58.219.56 t:1027
Apr 29 20:02:33 - [DEBUG] create_ssl 216.58.209.97 fail:timed out c:0 h:0
Apr 29 20:02:33 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:33 - [DEBUG] create_ssl 216.58.222.40 fail:timed out c:0 h:0
Apr 29 20:02:33 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:33 - [DEBUG] create_ssl 64.233.167.102 fail:timed out c:0 h:0
Apr 29 20:02:33 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:33 - [DEBUG] create_ssl 216.58.216.216 fail:timed out c:0 h:0
Apr 29 20:02:33 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:33 - [DEBUG] create_ssl 210.153.73.24 fail:timed out c:0 h:0
Apr 29 20:02:33 - [DEBUG] report_connect_fail network fail recently
Apr 29 20:02:34 - [DEBUG] get ip:74.125.207.17 t:1027
Apr 29 20:02:34 - [DEBUG] get ip:64.233.181.86 t:1027
Apr 29 20:02:34 - [DEBUG] get ip:216.58.210.48 t:1027
Apr 29 20:02:34 - [DEBUG] get ip:74.125.138.98 t:1027
Apr 29 20:02:34 - [DEBUG] get ip:216.58.219.159 t:1027


另外还出现证书错误。

**Comment by hehh2001** [comment]
证书需要重新导入的，如果原来用的原版 ，最好先删除goagent的证书，再导入新版的，data目录下。如果是chrom浏览器+proxy switchysharp

**Comment by hehh2001** [comment]
的方式，那么代理方式一定要选系统代理。

**Comment by annawongfo** [comment]
系统代理完全不行。今天又把证书全部重新导了一遍，自动切换模式可以了。
