### ISSUE TITLE
启动失败，状态页打不开，右下角没有托盘图标请问如何解决？

### ISSUE THREAD

**Issue by aworimania** [XX-net/XX-Net#2813]
D:\XX-Net-2.9.3>SET PYTHONPATH=

D:\XX-Net-2.9.3>"D:\XX-Net-2.9.3\python27/1.0/python.exe" "D:\XX-Net-2.9.3\launc
her/start.py"
Apr 09 21:21:56.878 - [INFO] start XX-Net 2.9.3
Apr 09 21:21:56.893 - [DEBUG] start confirm_xxnet_exit
Apr 09 21:21:57.923 - [DEBUG] good, xxnet:8087 cleared!
Apr 09 21:21:58.921 - [DEBUG] good, xxnet:8085 clear!
Apr 09 21:21:58.921 - [DEBUG] finished confirm_xxnet_exit
Apr 09 21:21:59.093 - [DEBUG] network is ok, cost:108 ms
Apr 09 21:21:59.093 - [INFO] SSL use version:TLSv1
Apr 09 21:21:59.733 - [INFO] load ip range file:D:\XX-Net-2.9.3\gae_proxy\local\
ip_range.txt
Apr 09 21:21:59.764 - [INFO] load google ip_list num:0, gws num:0
Apr 09 21:21:59.779 - [DEBUG] ## GAEProxy set keep_running: True
Apr 09 21:21:59.779 - [INFO] ---------------------------------------------------
---
Apr 09 21:21:59.779 - [INFO] Python Version     : 2.7.11
Apr 09 21:21:59.779 - [INFO] OS                 : Version:6-1; Build:7600; Platf
orm:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Apr 09 21:21:59.779 - [INFO] Listen Address     : 127.0.0.1:8087
Apr 09 21:21:59.779 - [INFO] GAE APPID          :
Apr 09 21:21:59.779 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pa
c
Apr 09 21:21:59.779 - [INFO] ---------------------------------------------------
---
Apr 09 21:21:59.795 - [INFO] server 127.0.0.1:8087 started.
Apr 09 21:21:59.795 - [ERROR] bind to 127.0.0.1:8086 fail
Exception in thread Thread-54:
Traceback (most recent call last):
  File "D:\XX-Net-2.9.3\python27\1.0\lib\threading.py", line 801, in __bootstrap
_inner
    self.run()
  File "D:\XX-Net-2.9.3\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\XX-Net-2.9.3\gae_proxy\start.py", line 19, in main
    client.main()
  File "D:\XX-Net-2.9.3\gae_proxy\local\proxy.py", line 242, in main
    pac_daemon = simple_http_server.HTTPServer((config.PAC_IP, config.PAC_PORT),
 pac_server.PACServerHandler)
  File "D:\XX-Net-2.9.3\python27\1.0\lib\noarch\simple_http_server.py", line 259
, in __init__
    self.init_socket()
  File "D:\XX-Net-2.9.3\python27\1.0\lib\noarch\simple_http_server.py", line 264
, in init_socket
    self.add_listen(addr)
  File "D:\XX-Net-2.9.3\python27\1.0\lib\noarch\simple_http_server.py", line 273
, in add_listen
    raise e
error: [Errno 10013]

**Comment by aworimania** [comment]
2.9.6版本同样的提示，一样也启动失败

**Comment by jzp820927** [comment]
Apr 09 21:21:59.795 - [ERROR] bind to 127.0.0.1:8086 fail

端口占用，查查看是那个进程占用了 8086 端口

**Comment by heiheihei120** [comment]
我先打开浏览器再开xx-net程序的 你试试看

**Comment by zhouxiaoxiaoxujian** [comment]
@aworimania 可以在命令行里面查看下端口被什么程序占用了.
```cmd
netstat -abno -p tcp | findstr :8086
```

**Comment by 178620086** [comment]
```
Apr 11 13:03:49.349 - [WARNING] check_update fail:URLError(error(10060, ''),)
Apr 11 13:06:29.423 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\软件\XX-Net\data\downloads\README.md, retry:0
Apr 11 13:06:30.493 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
Apr 11 13:06:30.498 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\软件\XX-Net\launcher\update.py", line 248, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[1][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'
```
请问这个是什么情况呢 我是win10 下载的最新xxnet

**Comment by jzp820927** [comment]
@178620086 检查更新失败，应该不影响使用的
