### ISSUE TITLE
1.12.2及1.12.3无法部署自己的appID~

### ISSUE THREAD

**Issue by WoodyLin** [XX-net/XX-Net#283]
1.12.2部署服务端成功但是我的三个app显示
Not Exist appids

然后更新到1.12.3版本，服务器端无法部署，一直显示错误
upload  fail: HTTP Error 404: Not Found

**Comment by WoodyLin** [comment]
用自带的appids一切正常~~

**Comment by annawongfo** [comment]
我今天换了三个版本，最后用到1.9.4，没有部署自己的Appid，终于成功。但还是很卡。
