### ISSUE TITLE
youtube 可以上，就是google不行是为什么

### ISSUE THREAD

**Issue by shizhongyu** [XX-net/XX-Net#2835]
youtube 可以上，就是google不行是为什么

**Comment by jzp820927** [comment]
试试 https://www.google.com/ncr

**Comment by nly4lov** [comment]
不行的就是美国GOOGLE和香港的，那么多GOOGLE，为啥非上他们两个
https://www.google.co.uk 英国
https://www.google.ca 加拿大
https://www.google.com.au 澳大利亚
https://www.google.ie 爱尔兰
https://www.google.co.nz 新西兰

**Comment by jzp820927** [comment]
曲线救国
