### ISSUE TITLE
最近几版facebook 又不能上传照片了。

### ISSUE THREAD

**Issue by ILlolita** [XX-net/XX-Net#284]
我想在facebook上传几张照片，但是它弹出窗口，说只能传一张。那好吧，我就选一张，结果还是不能传。

不能上传照片的反问题1.8几版曾经有过，但自从去掉了上传64k限制后就没有问题了。
因为最近很封锁更新很频繁我没有上传，今天上传又出现了这个问题。
希望作者在跟墙作战时注意一下这个问题。
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	ja_JP
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36
XX-Net Version	1.12.5
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087

Apr 29 22:50:22 - [INFO] GAE CONNECT 1-edge-chat.facebook.com:443 
Apr 29 22:50:22 - [DEBUG] GAE CONNECT GET https://1-edge-chat.facebook.com/ping?partition=-2&cb=4v4a&sticky_token=86&sticky_pool=ash2c06_chat-proxy&reason=ar%3Atransport%20error&uid=100001391896136&viewer_uid=100001391896136&wtc=112%2C100%2C1.000%2C112%2C112
Apr 29 22:50:22 - [DEBUG]LOG_EXCEPT: ssl_pool.get:64.233.162.84 handshake:565, Except:[Errno 9] Bad file descriptor
Apr 29 22:50:22 - [DEBUG] ssl conn_num:8
Apr 29 22:50:22 - [DEBUG] get ip:216.58.208.234 t:888
Apr 29 22:50:22 - [INFO] DIRECT t:592 s:6380 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:50:22 - [INFO] GAE CONNECT clients4.google.com:443 
Apr 29 22:50:22 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:50:22 - [DEBUG] host_conn_pool clients4.google.com get:64.233.162.84 handshake:561
Apr 29 22:50:22 - [INFO] DIRECT t:332 s:392 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:50:23 - [INFO] GAE t:933 s:454 200 http://qurl.f.360.cn/wdinfo.php
Apr 29 22:50:23 - [INFO] GAE t:776 s:43 200 https://1-edge-chat.facebook.com/ping?partition=-2&cb=4v4a&sticky_token=86&sticky_pool=ash2c06_chat-proxy&reason=ar%3Atransport%20error&uid=100001391896136&viewer_uid=100001391896136&wtc=112%2C100%2C1.000%2C112%2C112
Apr 29 22:50:23 - [INFO] GAE CONNECT 1-edge-chat.facebook.com:443 
Apr 29 22:50:23 - [INFO] GAE CONNECT www.facebook.com:443 
Apr 29 22:50:23 - [DEBUG] GAE CONNECT GET https://1-edge-chat.facebook.com/pull?channel=p_100001391896136&seq=1&partition=-2&clientid=3b2a0949&cb=jasl&idle=0&cap=8&wtc=113%2C100%2C1.000%2C113%2C112&msgs_recv=1&uid=100001391896136&viewer_uid=100001391896136&sticky_token=86&sticky_pool=ash2c06_chat-proxy&traceid=8EqRf&state=active
Apr 29 22:50:23 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:561
Apr 29 22:50:23 - [DEBUG] ssl conn_num:10
Apr 29 22:50:23 - [DEBUG] GAE CONNECT POST https://www.facebook.com/ajax/mercury/thread_sync.php
Apr 29 22:50:23 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:50:23 - [DEBUG] ssl conn_num:9
Apr 29 22:50:23 - [INFO] GAE t:500 s:108 200 https://www.facebook.com/ajax/mercury/thread_sync.php
Apr 29 22:50:24 - [DEBUG] create_ssl 210.245.14.177 fail:timed out cost:2000 h:0
Apr 29 22:50:24 - [INFO] GAE CONNECT ssl.gstatic.com:443 
Apr 29 22:50:24 - [DEBUG] GAE CONNECT GET https://ssl.gstatic.com/safebrowsing/csd/client_model_v5.pb
Apr 29 22:50:24 - [DEBUG] new_conn_pool.get:64.233.162.84 handshake:565
Apr 29 22:50:24 - [DEBUG] new_conn_pool conn_num:9
Apr 29 22:50:24 - [DEBUG] get ip:114.4.41.216 t:888
Apr 29 22:50:24 - [DEBUG] network is ok
Apr 29 22:50:24 - [DEBUG] create_ssl 216.58.208.234 fail:timed out cost:2000 h:0
Apr 29 22:50:24 - [DEBUG] network is ok
Apr 29 22:50:24 - [INFO] GAE t:2513 s:49491 200 https://www.facebook.com/ILlolita/photos_albums?ajaxpipe=1&ajaxpipe_token=AXjatbZbDBY1Yh5_&quickling[version]=1711798%3B0%3B&__user=100001391896136&__a=1&__dyn=7nm8QW8BgBlymfDgDxiWEB197xSq78hAKGgyi8DDirWU8popyUW3F6xybxu3fzoy2e4K5ebAxacFoy8J6xuFCE&__req=jsonp_6&__rev=1711798&__adt=6
Apr 29 22:50:24 - [INFO] GAE CONNECT fbstatic-a.akamaihd.net:443 
Apr 29 22:50:24 - [DEBUG] GAE CONNECT GET https://fbstatic-a.akamaihd.net/rsrc.php/v1/yT/r/v4YOKLMeTHJ.swf
Apr 29 22:50:24 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:50:24 - [DEBUG] ssl conn_num:9
Apr 29 22:50:25 - [DEBUG] get ip:208.117.224.246 t:888
Apr 29 22:50:25 - [DEBUG] get ip:106.162.216.50 t:889
Apr 29 22:50:25 - [INFO] GAE t:776 s:33597 200 https://fbstatic-a.akamaihd.net/rsrc.php/v1/yT/r/v4YOKLMeTHJ.swf
Apr 29 22:50:26 - [DEBUG] direct_create_ssl 114.4.41.216 fail:timed out cost:2000 h:0
Apr 29 22:50:26 - [DEBUG] network is ok
Apr 29 22:50:27 - [DEBUG] create_ssl 208.117.224.246 fail:timed out cost:2000 h:0
Apr 29 22:50:27 - [DEBUG] network is ok
Apr 29 22:50:27 - [DEBUG] create_ssl 106.162.216.50 fail:timed out cost:2000 h:0
Apr 29 22:50:27 - [DEBUG] network is ok
Apr 29 22:50:31 - [INFO] DIRECT t:7076 s:77984 200 ssl.gstatic.com /safebrowsing/csd/client_model_v5.pb
Apr 29 22:50:33 - [INFO] GAE CONNECT clients4.google.com:443 
Apr 29 22:50:33 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:50:33 - [DEBUG]LOG_EXCEPT: host_conn_pool clients4.google.com get:64.233.162.84 handshake:565, Except:[Errno 9] Bad file descriptor
Apr 29 22:50:34 - [INFO] DIRECT t:923 s:6030 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:50:34 - [INFO] GAE CONNECT clients4.google.com:443 
Apr 29 22:50:34 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:50:34 - [DEBUG] host_conn_pool clients4.google.com get:64.233.162.84 handshake:565
Apr 29 22:50:35 - [INFO] DIRECT t:327 s:267 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=AEPq8vU0wRCdZrDpQqnzaQ%3D%3D
Apr 29 22:51:09 - [INFO] GAE t:46268 s:964 200 https://1-edge-chat.facebook.com/pull?channel=p_100001391896136&seq=1&partition=-2&clientid=3b2a0949&cb=jasl&idle=0&cap=8&wtc=113%2C100%2C1.000%2C113%2C112&msgs_recv=1&uid=100001391896136&viewer_uid=100001391896136&sticky_token=86&sticky_pool=ash2c06_chat-proxy&traceid=8EqRf&state=active
Apr 29 22:51:09 - [INFO] GAE CONNECT 1-edge-chat.facebook.com:443 
Apr 29 22:51:09 - [DEBUG] GAE CONNECT GET https://1-edge-chat.facebook.com/pull?channel=p_100001391896136&seq=2&partition=-2&clientid=3b2a0949&cb=lm1b&idle=43&cap=8&wtc=159%2C146%2C0.500%2C159%2C158&msgs_recv=2&uid=100001391896136&viewer_uid=100001391896136&sticky_token=86&sticky_pool=ash2c06_chat-proxy&traceid=SCQMm&state=active
Apr 29 22:51:09 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:561
Apr 29 22:51:09 - [DEBUG] ssl conn_num:11
Apr 29 22:51:31 - [WARNING] _request:SysCallError(10053, 'Software caused connection abort')
Apr 29 22:51:31 - [DEBUG] fetch gae status:UNKNOWN url:https://1-edge-chat.facebook.com/pull?channel=p_100001391896136&seq=2&partition=-2&clientid=3b2a0949&cb=lm1b&idle=43&cap=8&wtc=159%2C146%2C0.500%2C159%2C158&msgs_recv=2&uid=100001391896136&viewer_uid=100001391896136&sticky_token=86&sticky_pool=ash2c06_chat-proxy&traceid=SCQMm&state=active
Apr 29 22:51:31 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:51:31 - [DEBUG] ssl conn_num:10
Apr 29 22:51:37 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:51:37 - [DEBUG] ssl conn_num:9
Apr 29 22:51:37 - [DEBUG] sort ip time:5
Apr 29 22:51:37 - [DEBUG] get ip:64.233.162.84 t:619
Apr 29 22:51:37 - [INFO] GAE CONNECT 56kupdate.com:443 
Apr 29 22:51:38 - [DEBUG] GAE CONNECT GET https://56kupdate.com/?ref=http%253A%252F%252F127.0.0.1%253A8085%252F%253Fmodule%253Dgoagent%2526menu%253Dstatus&modules%5B%5D=&addon=lostfriends&addon_version=2.5&browser=chrome&browser_version=31.0.1650.57&locale=ja&ef_version=2&_=1430311754760
Apr 29 22:51:38 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:51:38 - [DEBUG] ssl conn_num:8
Apr 29 22:51:38 - [DEBUG] get ip:64.15.124.180 t:889
Apr 29 22:51:38 - [DEBUG] create_ssl update ip:64.233.162.84 time:575
Apr 29 22:51:39 - [INFO] GAE t:1217 s:246 200 http://qurl.f.360.cn/wdinfo.php
Apr 29 22:51:39 - [INFO] GAE t:1210 s:20 200 https://56kupdate.com/?ref=http%253A%252F%252F127.0.0.1%253A8085%252F%253Fmodule%253Dgoagent%2526menu%253Dstatus&modules%5B%5D=&addon=lostfriends&addon_version=2.5&browser=chrome&browser_version=31.0.1650.57&locale=ja&ef_version=2&_=1430311754760
Apr 29 22:51:40 - [DEBUG] create_ssl 64.15.124.180 fail:timed out cost:2000 h:0
Apr 29 22:51:40 - [DEBUG] network is ok
Apr 29 22:51:51 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:51:51 - [DEBUG] ssl conn_num:10
Apr 29 22:51:52 - [INFO] GAE t:957 s:285 200 http://220.181.131.236/msvquery
Apr 29 22:51:54 - [DEBUG] sort ip time:6
Apr 29 22:51:54 - [DEBUG] get ip:64.233.162.84 t:575
Apr 29 22:51:55 - [DEBUG] create_ssl update ip:64.233.162.84 time:628
Apr 29 22:52:05 - [INFO] GAE t:56172 s:963 200 https://1-edge-chat.facebook.com/pull?channel=p_100001391896136&seq=2&partition=-2&clientid=3b2a0949&cb=lm1b&idle=43&cap=8&wtc=159%2C146%2C0.500%2C159%2C158&msgs_recv=2&uid=100001391896136&viewer_uid=100001391896136&sticky_token=86&sticky_pool=ash2c06_chat-proxy&traceid=SCQMm&state=active
Apr 29 22:52:08 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:08 - [DEBUG] ssl conn_num:10
Apr 29 22:52:09 - [INFO]LOG_EXCEPT: GAE t:915 s:34 200 http://config.pinyin.sogou.com/api/popup/lotus.php?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&ppversion=3.0.0.1863, Except:[Errno 9] Bad file descriptor
Apr 29 22:52:09 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:09 - [DEBUG] ssl conn_num:10
Apr 29 22:52:11 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:11 - [DEBUG] ssl conn_num:9
Apr 29 22:52:11 - [DEBUG] sort ip time:6
Apr 29 22:52:11 - [DEBUG] get ip:64.233.162.84 t:628
Apr 29 22:52:12 - [DEBUG] create_ssl update ip:64.233.162.84 time:584
Apr 29 22:52:12 - [INFO] GAE t:970 s:0 404 http://ping.pinyin.sogou.com/pingback_bubble.gif?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&passport=ILlolita%40sogou.com&ppversion=3.0.0.1863&bb_type=Query_period
Apr 29 22:52:14 - [INFO] GAE t:4842 s:10690 200 http://info.pinyin.sogou.com/ime_push/getPopupIni.php?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&passport=ILlolita%40sogou.com&activeOp=0&action_skin=2&action_dict=1&action_normal=2&action_gram=32785&skinOp=c2i16554&updateOp=15&dictOp=c2i16554&DisabledEntries=0&disable_newword=0&uex=0&defaultime=1&sgse=0&ppversion=3.0.0.1863&active_skin=Clannad&active_skin_id=&active_skin_md5=0255F9CD69E78071464C729FDB6FB267&active_skin_isflash=0&urlguide=20150123&type=query&Popup_DisableSkinBubble=0&pushids=&hpushids=Y10000001&hpopids=G10000817&popids=&condids=&sgse_r=
Apr 29 22:52:15 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:15 - [DEBUG] ssl conn_num:11
Apr 29 22:52:15 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:15 - [DEBUG] ssl conn_num:10
Apr 29 22:52:15 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:15 - [DEBUG] ssl conn_num:9
Apr 29 22:52:15 - [DEBUG] get ip:64.15.119.156 t:889
Apr 29 22:52:15 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:566
Apr 29 22:52:15 - [DEBUG] ssl conn_num:8
Apr 29 22:52:15 - [DEBUG] get ip:173.194.71.90 t:889
Apr 29 22:52:16 - [INFO] GAE t:654 s:0 404 http://ping.pinyin.sogou.com/pingback.gif?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&id=G10000306&passport=ILlolita%40sogou.com&type=condition&ppversion=3.0.0.1863&conres=000uu
Apr 29 22:52:16 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:16 - [DEBUG] ssl conn_num:8
Apr 29 22:52:16 - [INFO] GAE t:663 s:0 404 http://ping.pinyin.sogou.com/pingback.gif?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&id=N10000801&passport=ILlolita%40sogou.com&type=condition&ppversion=3.0.0.1863&conres=0u
Apr 29 22:52:16 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:16 - [DEBUG] ssl conn_num:8
Apr 29 22:52:16 - [INFO] GAE t:1022 s:0 404 http://ping.pinyin.sogou.com/pingback.gif?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&id=N10000113&passport=ILlolita%40sogou.com&type=condition&ppversion=3.0.0.1863&conres=01
Apr 29 22:52:16 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:16 - [DEBUG] ssl conn_num:8
Apr 29 22:52:16 - [INFO] GAE t:1038 s:0 404 http://get.sogou.com/q
Apr 29 22:52:16 - [INFO] GAE t:653 s:0 404 http://ping.pinyin.sogou.com/pingback.gif?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&id=Y10000001&passport=ILlolita%40sogou.com&type=predownload&ppversion=3.0.0.1863
Apr 29 22:52:17 - [INFO] GAE t:657 s:0 404 http://ping.pinyin.sogou.com/pingback.gif?h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f&id=N10000112&passport=ILlolita%40sogou.com&type=condition&ppversion=3.0.0.1863&conres=001000000000000000000000001100000000001000100000100100000000000000000000000000000000000000
Apr 29 22:52:17 - [INFO] GAE t:716 s:0 404 http://ping.pinyin.sogou.com/gender.gif?prob0=0.041125&prob1=0.958875&ppversion=3.0.0.1863&passport=ILlolita%40sogou.com&h=C8C8F634361A6D1C66684D0C9C204CD5&v=7.5.0.5550&r=0000_sogou_pinyin_71f
Apr 29 22:52:17 - [DEBUG] create_ssl 64.15.119.156 fail:timed out cost:2000 h:0
Apr 29 22:52:17 - [DEBUG] create_ssl 173.194.71.90 fail:timed out cost:2001 h:0
Apr 29 22:52:17 - [DEBUG] network is fail
Apr 29 22:52:17 - [DEBUG] report_connect_fail network fail
Apr 29 22:52:17 - [DEBUG] network is ok
Apr 29 22:52:59 - [INFO]LOG_EXCEPT: GAE CONNECT autoproxy-gfwlist.googlecode.com:443 , Except:[Errno 9] Bad file descriptor
Apr 29 22:52:59 - [DEBUG] GAE CONNECT GET https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt
Apr 29 22:52:59 - [DEBUG] new_conn_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:59 - [DEBUG] new_conn_pool conn_num:9
Apr 29 22:52:59 - [DEBUG] sort ip time:9
Apr 29 22:52:59 - [DEBUG] get ip:64.233.162.84 t:584
Apr 29 22:52:59 - [INFO] GAE CONNECT www.facebook.com:443 
Apr 29 22:52:59 - [DEBUG] GAE CONNECT POST https://www.facebook.com/ajax/feed/ticker/multi_story
Apr 29 22:52:59 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:52:59 - [DEBUG] ssl conn_num:8
Apr 29 22:52:59 - [DEBUG] get ip:173.194.71.90 t:889
Apr 29 22:52:59 - [DEBUG] get ip:64.233.160.104 t:889
Apr 29 22:53:00 - [INFO] GAE CONNECT www.facebook.com:443 
Apr 29 22:53:00 - [DEBUG] GAE CONNECT POST https://www.facebook.com/ajax/feed/ticker/multi_story
Apr 29 22:53:00 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:565
Apr 29 22:53:00 - [DEBUG] ssl conn_num:7
Apr 29 22:53:00 - [DEBUG] get ip:210.245.14.236 t:889
Apr 29 22:53:00 - [DEBUG] direct create_ssl update ip:64.233.162.84 time:605

**Comment by xxnet** [comment]
前面有观察过Facebook上传图片，采用OPTIONS命令，GAE是不支持的。
  这个问题暂时无法解决。
  为什么以前能够上传，也许Facebook在某些情况下不是使用OPTIONS去上传？
  你发的日志里没有看到类似上传的日志，无法确定原因。
  下次上传失败，可以立即在日志里搜索OPTIONS的关键词。

2015-04-29 10:58 GMT-04:00 ILlolita <notifications@github.com>:
