### ISSUE TITLE
浏览器状态页 127.0.0.1:8085 打不开

### ISSUE THREAD

**Issue by Krabapple** [XX-net/XX-Net#2842]
周末手贱下载了 Hola，一个可以把本机 IP 地址改成美/英/澳等国 IP 的 chrome 插件，然后 127.0.0.1:8085 就打不开了，不知道和 Hola 有没有关系。
参考了[#2813](https://github.com/XX-net/XX-Net/issues/2813)，还是不太会弄。
点进了旧版本的start.bat，无效。
下载2.9.6后，start.bat也无效。
求帮助，多谢！

**Comment by jzp820927** [comment]
把 hola 关了，再打开撒

**Comment by Krabapple** [comment]
Hola 昨天已经从 Chrome 移除，也重启过电脑了。

**Comment by jzp820927** [comment]
用 IE 之类的试试能不能打开

**Comment by Krabapple** [comment]
IE也不行，圆圈一直转，没反应。
刚刚试了一下检测端口占用，出来一大片:
TCP xx.xx.xx.xx xx.xx.xx.xx xxxxx xxxx
有十多行。
所以是不是 Hola 的问题？十分烦躁啊。

**Comment by jzp820927** [comment]
这个就麻烦了啊， web 打不开，日志也看不到，不好分析，你看看是不是有什么占用了 8085 端口吧

**Comment by Krabapple** [comment]
突然又可以了，莫名其妙。
参考了[百度经验](http://jingyan.baidu.com/article/3c48dd34491d47e10be358b8.html)，强制结束了 pythonw 的几个进程。
多谢@jzp820927 ！
