### ISSUE TITLE
继续放弹，炸墙。这一次，主要是让大家用得安逸。xx还在，大家安心

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#2853]
第四弹
替换， XX-Net/gae_proxy/local/ip_range.txt 文件
建议删除data文件，重新扫。（需要重新配置id，代理等）
或者在web ui页面，高级--设置--IP段列表，替换为附件的IP段也行，
总ip数增加到5w多
其实就是不想xx沦为少数人的玩具，放出来大家一起用。
然后那些connected-link: 0／0的，504的也不要另发帖问了，就是没有可用ip了，替换这个应该可以使用。
感谢 @jasonliul @xyuanmu ……  提供ip段的兄弟，然后广传之

[ip_range.txt](https://github.com/XX-net/XX-Net/files/214501/ip_range.txt)

**Comment by TonnyTonny** [comment]
@yeahwu 謝謝。

**Comment by PvCDp** [comment]
多谢！马上复活，这几天只能用蓝灯，可惜蓝灯速度太慢。

**Comment by solxnp** [comment]
非常感谢 验证OK

**Comment by whhxmwhh** [comment]
五万多。我试试了。感谢。

**Comment by sunking0505** [comment]
感谢大神！

**Comment by GoldenDewitt** [comment]
无法感谢更多！！！！

**Comment by IKAR1SHINJI** [comment]
你这不还是放出了，嘴上说着不要，身体却······

**Comment by IKAR1SHINJI** [comment]
你这不还是放出了，嘴上说着不要，身体却······
另外 感谢！

**Comment by 7559ykq** [comment]
真的太感谢了

**Comment by yeahwu** [comment]
@IKAR1SHINJI 恩，你说到重点鸟，主要是这东西藏着掖着也不能怀孕。干脆放出来大家一起用。
另外，你就当俺说话不算话吧，没关系滴

**Comment by abchb99** [comment]
前几个用着不错。

**Comment by ytgala** [comment]
感谢楼主分享

**Comment by excellenttank** [comment]
非常感谢楼主，终于爽了

**Comment by spphinslove** [comment]
为什么我只有1000ip

**Comment by yeahwu** [comment]
@spphinslove 能用就行，计较那么多干嘛！给你10000个ip，你又生不出10001个。

**Comment by flykarry** [comment]
data 文件在哪？我这没有找到这个啊，只有个文件夹叫data

**Comment by kingjia1989** [comment]
文件怎么打不开？

**Comment by panzer1313208** [comment]
嘴上说着不要，身体却很老实呢！

**Comment by vilen1** [comment]
新:10 已用:49 十分感谢!

**Comment by charmanchur** [comment]
无法下载！

**Comment by yeahwu** [comment]
多试几次吧，就几kb的东西。

**Comment by charmanchur** [comment]
@yeahwu 谢谢！已经ok。提醒：下载不了的不要直接点击下载（地址与直接拷贝地址不一样），而是拷贝地址下载。

**Comment by goodboytxw** [comment]
这个ip段怎么找的？十分感谢提供的IP段！！！

**Comment by yeahwu** [comment]
找算命先生哪！

**Comment by heikehuan** [comment]
感谢作者

**Comment by mihongkun** [comment]
gws-ip-num: 3000 / 108
network-status: OK
connected-link: 3 / 50
scan-ip-thread-num: 50
ip-quality: 460
block-stat: OK

**Comment by curiosity2016** [comment]
good！

**Comment by qq864045244** [comment]
嘻嘻  谢谢大神
