### ISSUE TITLE
http 无法自动跳转到 https

### ISSUE THREAD

**Issue by Sam0523** [XX-net/XX-Net#2855]
-----------
Problem Description:
Chrome + SwitchyOmega

地址栏输入 google.com 无限加载，输入 https://www.google.com 秒开。
http 站点也会因为加载 *.googleapis.com 而卡住
不是很确定是不是 XX-Net 的问题，先在这里问一下，谢谢了

-----------
Diagnostic information:
sys-platform: x86_64, Linux-4.5.0-3-default-x86_64-with-SuSE-20160408-x86_64
os-system: Linux
os-version: #1 SMP PREEMPT Mon Mar 28 07:27:57 UTC 2016 (8cf0ce6)
os-release: 4.5.0-3-default
os-detail: Dist:openSUSE ; Version:20160408; ID:x86_64
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 2.9.6

python-version: 2.7.10

ipv6-status: 0
gws-ip-num: total:3000 good:244
network-status: OK
connected-link: new:5 used:48
scan-ip-thread-num: 50
ip-quality: 508
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
可以按照  https everywhere 插件实现 http 自动跳转 https

**Comment by Sam0523** [comment]
@jzp820927 这个必须要插件才行吗？以前不用插件也行啊

**Comment by jzp820927** [comment]
chrome 浏览器可以设置 HSTS，也行.
