### ISSUE TITLE
1.12.5 反馈

### ISSUE THREAD

**Issue by yqfang** [XX-net/XX-Net#286]
1.12.5 连接超时错误， 从未成功过

1.12.3 总体来说好评～

（youtube 下载的问题很捉急啊！ 平时就靠下载youtube 视频学习先进文化了，直接在线看基本不能忍受啊！！，求XX大神优先解决下，看有些人问怎么利用代理下youtube视频，之后我做个wiki～）

**Comment by larsenlouis** [comment]
来借个楼，建议测试版发布到release的时候check一下下面的This is a pre-release

**Comment by xxnet** [comment]
好

2015-04-29 23:58 GMT-04:00 Louis Lu <notifications@github.com>:

**Comment by lifeva** [comment]
无限block

**Comment by streamgo** [comment]
测试版无限block

**Comment by fbwfbi** [comment]
今天刚装了一下xx-net 1.12.3，发现好卡啊.......后来发现在配置中把ip是用的频率改为2，明显就快多了，打开youtube也没问题

**Comment by yqfang** [comment]
@fbwfbi  时间一长你就发现ip都被block了～

**Comment by xxnet** [comment]
新版恢复正常
