### ISSUE TITLE
为什么每次打开后只能用几分钟，然后就没作用了，要重新打开

### ISSUE THREAD

**Issue by Beginner258** [XX-net/XX-Net#2864]
-----------
问题描述：
每次刚打开的时候能用，但是几分钟后就失效了，要关掉重新打开才行，请问这是为什么？

-----------
诊断信息：
sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:44 good:29
network-status: OK
connected-link: new:0 used:23
scan-ip-thread-num: 50
ip-quality: 613
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
贴日志出来看看
