### ISSUE TITLE
XX-net网络不稳定

### ISSUE THREAD

**Issue by zhanglaplace** [XX-net/XX-Net#287]
本人chrome XXnet版本1-12-2，
在http://127.0.0.1:8085上部署了自己的appid后chrome载入switchyomega.bak文件。
然后可以登录google.youtube/、谷歌学术等网站。
但过了一段时间，可能是3分钟，也可能只有1分钟，就连不上上述网页了。
![image](https://cloud.githubusercontent.com/assets/12178974/7405740/a0718776-ef29-11e4-969b-563392b59e46.png)
有知道怎么解决的么？谢谢了

**Comment by xxnet** [comment]
新版已经恢复正常
