### ISSUE TITLE
0000000000000000000000000000000

### ISSUE THREAD

**Issue by liumuqi** [XX-net/XX-Net#2870]
---

Problem Description:
Please describe your problem, running logs may be needed.

---

Diagnostic information:
sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:13546 good:37
network-status: unknown
connected-link: new:0 used:36
scan-ip-thread-num: 0
ip-quality: 525
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/2727
