### ISSUE TITLE
firefox手动添加证书失败。

### ISSUE THREAD

**Issue by chaizia** [XX-net/XX-Net#29]
firefox中有个goagent原版的证书，删除后再手动导入
XX-Net\goagent\3.1.34\local\CA.crt证书 然后编辑信任
结果只能打开Google搜索和youtube主页，不能看youtube视频
其他https网站均提示证书错误，求解答如何正确添加证书

**Comment by chaizia** [comment]
已解决：
“郭靖 下午3:47（4 小时前）
删除Firefox\Profiles文件夹里*.default里面的cert8.db，然后再添加ca.crt”

**Comment by pendave** [comment]
https://github.com/XX-net/XX-Net/issues/7580 Firefox 火狐浏览器证书失效后的更新办法！GIF动图教程
