### ISSUE TITLE
谷歌浏览器说WWW.GOOGLE.COM.HK身份无法验证。。。

### ISSUE THREAD

**Issue by Ghostsnail** [XX-net/XX-Net#290]
![image](https://cloud.githubusercontent.com/assets/11720644/7408193/113e47c8-ef4d-11e4-82df-3e40f749c081.png)
这个。。。。是XX的问题还是谷歌浏览器自己搞掉自己？

**Comment by xxnet** [comment]
新版解决了

在 2015年4月30日 上午3:26，Ghostsnail <notifications@github.com>写道：

**Comment by Ghostsnail** [comment]
原来是1.12.3，换最新1.12.5测试版，问题依旧，是不是要手动重新注册什么证书？

**Comment by Ghostsnail** [comment]
感觉没以前旧版本好用，以前网络状态比现在还差，起码经常还能用，现在的版本是经常不能用。。。。
不知道是广西地区的运营商的问题还是真的是网速的问题

**Comment by xxnet** [comment]
试试新版 1.14.x
