### ISSUE TITLE
XX-NET在openwrt里运行不起来．

### ISSUE THREAD

**Issue by firefoxwang** [XX-net/XX-Net#2901]
这几天没事干想把XX-NET放进我的openwrt路由里面，但是一直没有成功．环境是网件3800外挂在一个sdb1移动硬盘．我把python装在/mnt/sdb1/usr/bin下面，然后在/etc/profile里修改了环境变量，使之能被访问到，但是关键是　openwrt里没有bash,所以.sh里关于#!/bin/bash就没有什么用了．而且我也找不到openwrt　pyopenssl的包．

**Comment by jzp820927** [comment]
可以试试 XXMINI，有人成功运行起来了

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/%E5%9C%A8OpenWrt%E9%87%8C%E8%BF%90%E8%A1%8CXX-Net

**Comment by firefoxwang** [comment]
@xxnet 我过几天再试试，用的明月的固件 没有bash ,/bin/sh　start.sh　会报错　脚本路径问题．

**Comment by firefoxwang** [comment]
@jzp820927 XXMINI具体指的什么，阁下有相应的资料或者链接吗

**Comment by jzp820927** [comment]
@firefoxwang  项目主页：https://github.com/xyuanmu/XX-Mini
成功运行经验：https://github.com/xyuanmu/XX-Mini/issues/12

**Comment by firefoxwang** [comment]
@jzp820927 谢谢咯，晚上下了班就试试

**Comment by jzp820927** [comment]
已经有好几个成功运行了，你可以试试

**Comment by firefoxwang** [comment]
@jzp820927 初步成功了．安装pyopenssl后，再用xx-net mini运行就能跑起来．先运行起来，等我自己摸会了就写个文档．阁下给我看的精简版的xx-net可以直接在配置好环境的openwrt系统里面跑．

**Comment by firefoxwang** [comment]
介绍一下把xx-net放路由的具体思路：
a. 首先要有个能运行openwrt的路由器，最好带usb(方便挂在u盘或者移动硬盘)然后刷上固件．
b. python的安装包比较大，所有要修改opkg的配置文件，把python安装在挂在的移动存储介质里 etc下的profile文件也要修改
c. 安装pyopenssl,如果opkg的源list里没有就去官网自己下载，然后安装．注意要安装到python所在的/usr/bin下面  这样python xxx.py就不会出现找不到openssl了
d.配置proxy.ini 　监听端口0/0，然后运行proxy.py 一般就可以了
f.一般问题，要么是找不到库，要么是没有设置号proxy.ini 建议把proxy.ini 备份一下cp proxy.ini proxy.ini.bak 以后出问题了再cp回来

**Comment by jzp820927** [comment]
一般出问题最多的就是 pyopenssl 库的问题

**Comment by firefoxwang** [comment]
@jzp820927 是的，非常感谢
