### ISSUE TITLE
如何用XXnet代理spotify软件

### ISSUE THREAD

**Issue by sololo312** [XX-net/XX-Net#2902]
软件通过XXnet无法连上，软件中的代理设置也各种试过

**Comment by sololo312** [comment]
使用网页的也无法登陆，估计是没有代理spotify的IP

**Comment by jzp820927** [comment]
软件支持设置代理麽？

**Comment by sololo312** [comment]
@jzp820927 有的。登录界面settings里面

**Comment by jzp820927** [comment]
那应该没问题吧，你看看 XX 的日志，有没有什么报错信息？

**Comment by sololo312** [comment]
@jzp820927 主要是地址和port不太清楚

**Comment by lineex** [comment]
在设定里  显示进阶设置   然后 proxy设置  类型  自动侦测    http: 127.0.0.1     port :8087       
我也很喜欢spotify 想买会员没办visa卡  还没办

**Comment by sololo312** [comment]
@lineex 不好意思，现在才看到。谢啦哥。会员貌似听说某宝可以买到
