### ISSUE TITLE
使用xx-net和goagent上FB都会出现的错误

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#2905]
XMLHttpRequest cannot load https://4-edge-chat.facebook.com/pull?......
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.facebook.com' is therefore not allowed access. The response had HTTP status code 502.

**Comment by jzp820927** [comment]
XMLHttpRequest cannot load https://4-edge-chat.facebook.com/pull?......

好像是不能加载 ajax 导致的问题吧？不知道我猜的对不对

**Comment by nly4lov** [comment]
我是能打开的。
