### ISSUE TITLE
git使用代理clone失败，如何解决？

### ISSUE THREAD

**Issue by soiff** [XX-net/XX-Net#2909]
$ git -c http.proxy=http://127.0.0.1:8087 -c http.sslVerify=false clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 19.43 MiB ...
remote: Counting objects: 990, done
remote: Finding sources: 100% (5/5)
error: RPC failed; curl 18 transfer closed with 9776169 bytes remaining to read
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by soiff** [comment]
First, turn off compression:

git config --global core.compression 0
Next, let's do a partial clone to truncate the amount of info coming down:

git clone --depth 1 <repo_URI>
When that works, go into the new directory and retrieve the rest of the clone:

git fetch --unshallow 
or, alternately,

git fetch --depth=2147483647
Now, do a regular pull:

git pull --all
I think there is a glitch with msysgit in the 1.8.x versions that exacerbates these symptoms, so another option is to try with an earlier version of git (<= 1.8.3, I think).

[see](http://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed)

**Comment by jzp820927** [comment]
解决了麽？

**Comment by soiff** [comment]
@jzp820927 解决了，按照我在2楼的回复操作即可~

**Comment by jzp820927** [comment]
我刚刚试了一下，也是报错，但是报错的信息和你不一样。
我看2楼的配置好像和代理没有任何关系啊？

下面是我的报错。
root@ubuntu:~# git -c http.proxy=http://127.0.0.1:8087 -c http.sslVerify=false clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools/': Received HTTP code 407 from proxy after CONNECT

**Comment by soiff** [comment]
@jzp820927 我理解出错的原因在于git需要从代理读取数据并解压，但是代理结束标志透传给git时有点问题，所以禁用git压缩功能就可以避免这个问题。你这个错误是407，通常是因为你的代理需要凭证而你访问的时候没有提供(用户名/密码)。除非你需要访问 https://chromium.googlesource.com/chromium/tools/depot_tools/ 否则，可以使用github其他repository来验证，如果有用户密码也需要指定（部分googlesource的repository禁止通过Google App Engine访问，具体原因不明）。

**Comment by jzp820927** [comment]
@soiff 对对对，你没说我差点忘记了，我用的 XX-MINI，开启了 XX 本身的认证功能，是代理本身的认证，那么，git 这么配置带认证的代理呢？

**Comment by soiff** [comment]
@jzp820927 Ok，理论上Mini和Net应该没差，如果对于 https://chromium.googlesource.com/chromium/tools/depot_tools/ Mini可以访问那么说明XX-Net还是有隐含问题存在！

**Comment by jzp820927** [comment]
不知道是本机环境问题，还是网络问题，或者说是 XX 的问题，我==再用 XXNET 试试，再来汇报一下。

**Comment by jzp820927** [comment]
刚刚我用 XXNET 测试了，也是没有做2楼的配置，直接代理 clone，一切正常，估计是不是你系统环境的问题，或者和你网络有关？

**Comment by soiff** [comment]
@jzp820927 有可能，不过理论上没有什么特别的，后边出了问题再来反馈好了~

**Comment by humengchi** [comment]
git clone --depth 1 <repo_URI> 这一步具体怎么实现

**Comment by jzp820927** [comment]
不太明白，你想问什么

**Comment by humengchi** [comment]
看不懂你的步骤二
First, turn off compression:

git config --global core.compression 0
Next, let's do a partial clone to truncate the amount of info coming down:

git clone --depth 1 <repo_URI>
When that works, go into the new directory and retrieve the rest of the clone:

git fetch --unshallow
or, alternately,

git fetch --depth=2147483647
Now, do a regular pull:

git pull --all
I think there is a glitch with msysgit in the 1.8.x versions that exacerbates these symptoms, so another option is to try with an earlier version of git (<= 1.8.3, I think).

**Comment by jzp820927** [comment]
这不是我的步骤，是 LZ 的步骤。
git clone --depth 1 <repo_URI>
这个命令的作用是下载源代码，比如说，你要下载 XXNET 的源代码，你就执行
git clone --depth 1 https://github.com/XX-net/XX-Net
就可以了。这样再不懂，我就没法解释了。

**Comment by BigBlueMan19911109** [comment]
![5b89fa3a-8efa-4c6e-9aa7-c2b2a875c60d](https://user-images.githubusercontent.com/15261995/28205345-2e5fc812-68b4-11e7-8b41-3caa16e28ade.png)

**Comment by BigBlueMan19911109** [comment]
请问这个情况怎么处理，我也试了你的方法，但是没用。我用浏览器可以访问这个网站的。

**Comment by jzp820927** [comment]
超时了，你命令没加代理选项。除非你能直接连接 google 的服务器，不然就加上代理选项。

**Comment by BigBlueMan19911109** [comment]
我配置了http.proxy，然后git clone 报404。是我设置的代理有问题吗，怎么看我电脑上的代理？我可以用谷歌的。

**Comment by BigBlueMan19911109** [comment]
是我给git设置的代理有问题。看网络设置里的代理是自动代理，然后后面跟着个url，我直接把url的服务地址当作代理了，使用之后就404了。我把这个url的文件下载下来，发现里面的代理是不同的，用了这个作为代理后就可以clone了

**Comment by HansenMo** [comment]
感谢楼主，解决了！哈哈哈
