### ISSUE TITLE
本地服务器部署，其他机子通过代理地址访问出现证书问题

### ISSUE THREAD

**Issue by angrydigital** [XX-net/XX-Net#2913]
我在做了一台服务器，在家里。上面部署了XX-net。然后自己用的电脑的SwitchyOmega的代理地址设置成服务器的IP地址。可以翻墙，但是出现证书问题，说不安全。有什么办法解决？

**Comment by soiff** [comment]
如果是浏览器访问，可以将XX-net的证书(data\gae_proxy\CA.cert)导入浏览器（IE：Internet选项-内容-证书-导入）重新尝试访问；如果是Linux系统，可以参考对应系统证书导入办法；总之确保XX-net证书被系统信任即可。如果是个别工具，比如git，可以增加选项-c http.sslVerify=false来规避，如果是curl，可以增加-k参数来避免证书校验。希望能帮到你~

**Comment by jzp820927** [comment]
所有客户端都需要安装证书，可以通过 在 XX 的 web 页面下载证书安装即可。

**Comment by angrydigital** [comment]
@soiff @jzp820927 已经解决了。问题：其他机子上面安装的证书如果使用127.0.0.1的话不会出现证书问题，如果使用服务器地址的话就会出现，查找原因后发现其他机子的证书和服务器上的不一致（指纹明显不一样）。解决：我把服务器上已经安装的证书导出来，替换其他的机子上的证书。
