### ISSUE TITLE
现在IP地址很少么？

### ISSUE THREAD

**Issue by changshunxu520** [XX-net/XX-Net#2926]
我的3.0.2上面才寥寥几个····很无语

**Comment by yeahwu** [comment]
3版以后已替换ip库，等待扫描时间长点，大概半天，可扫出足够ip。

**Comment by aescin** [comment]
@yeahwu xx-net可以和xx-mini同时扫描ip吗

**Comment by yeahwu** [comment]
没必要，开一个扫描，然后把扫出来的good ip复制到另一个，在data文件夹。

**Comment by aescin** [comment]
@yeahwu 复制出goog-ip和scan-ip这两个文本文本文件吧

**Comment by xiaoyan94** [comment]
扫描一天，140个ip  正常吗？

**Comment by yeahwu** [comment]
正常，能用就正常，ip多少无所谓

**Comment by jzp820927** [comment]
现在总的可用 IP 估计也就几百个，能上百，就已经很好了

**Comment by changshunxu520** [comment]
应该是扫描时间的问题了
