### ISSUE TITLE
目前一直无法访问外网，请大神帮着看看

### ISSUE THREAD

**Issue by changshunxu520** [XX-net/XX-Net#2927]
-----------
问题描述：为啥IP连接数一直这么少
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 3.0.2

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:6 good:2
network-status: OK
connected-link: new:0 used:2
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yeahwu** [comment]
扫描时间长点，可扫出足够IP，大概半天吧。

**Comment by jzp820927** [comment]
xxnet-version: 3.0.2 ,看你的版本是 3.0.2，已经包含 更新 IP了，那应该就是时间问题了
