### ISSUE TITLE
已经没有办法了，无限block

### ISSUE THREAD

**Issue by lifeva** [XX-net/XX-Net#293]
Apr 30 17:06:19 - [INFO] GAE CONNECT www.google-analytics.com:443 
Apr 30 17:06:19 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
Apr 30 17:06:19 - [DEBUG] new_conn_pool conn_num:0
Apr 30 17:06:20 - [DEBUG]LOG_EXCEPT: create ssl timeout fail., Except:[Errno 9] Bad file descriptor
Apr 30 17:06:20 - [DEBUG] create_ssl_connection fail
Apr 30 17:06:20 - [WARNING] gae_exception:GAE_Exception() http://portableappz.blogspot.jp/
Apr 30 17:06:20 - [DEBUG] ssl conn_num:0
Apr 30 17:06:20 - [INFO] GAE CONNECT www.google-analytics.com:443 
Apr 30 17:06:20 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
Apr 30 17:06:20 - [DEBUG] new_conn_pool conn_num:0
Apr 30 17:06:20 - [INFO] GAE CONNECT www.google-analytics.com:443 
Apr 30 17:06:20 - [DEBUG] GAE CONNECT GET https://www.google-analytics.com/collect?v=1&_v=j30&a=1036724621&t=pageview&_s=1&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fnotifications&ul=zh-cn&de=UTF-8&dt=Notifications%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1920x1080&vp=1263x991&je=1&fl=16.0%20r0&_u=eACAAAQBM~&jid=&cid=1419274226.1420791241&tid=UA-3769691-2&cd1=Logged%20In&cd2=Header%20v3&z=260679489
Apr 30 17:06:20 - [DEBUG] new_conn_pool conn_num:0
Apr 30 17:06:23 - [INFO] GAE CONNECT www.google-analytics.com:443 
Apr 30 17:06:23 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
Apr 30 17:06:23 - [DEBUG] new_conn_pool conn_num:0
Apr 30 17:06:35 - [DEBUG] create ssl timeout fail.
Apr 30 17:06:35 - [DEBUG] create_ssl_connection fail
Apr 30 17:06:35 - [DEBUG] ssl conn_num:0
Apr 30 17:06:48 - [INFO] GAE CONNECT api.twitter.com:443 
Apr 30 17:06:48 - [DEBUG] GAE CONNECT GET https://api.twitter.com/1.1/search/tweets.json?count=200&since_id=593694736214401024&q=cosbeta&result_type=recent
Apr 30 17:06:48 - [DEBUG] ssl conn_num:0
Apr 30 17:06:50 - [DEBUG] create ssl timeout fail.
Apr 30 17:06:50 - [DEBUG] create_ssl_connection fail
Apr 30 17:06:50 - [DEBUG] ssl conn_num:0
Apr 30 17:06:51 - [INFO] GAE CONNECT api.twitter.com:443 
Apr 30 17:06:51 - [DEBUG] GAE CONNECT GET https://api.twitter.com/1.1/statuses/home_timeline.json?count=200&since_id=593702873583587328&include_entities=true
Apr 30 17:06:51 - [DEBUG] ssl conn_num:0
Apr 30 17:07:03 - [DEBUG] create ssl timeout fail.
Apr 30 17:07:03 - [DEBUG] create_ssl_connection fail
Apr 30 17:07:03 - [DEBUG] ssl conn_num:0

**Comment by annawongfo** [comment]
已经累觉不爱。不知道是不是该去买VPN了。

**Comment by siwday** [comment]
免费ss很多啊

**Comment by anycall9696** [comment]
我不是来拆台的...ShadowSocks现阶段比XX和GoAgent好用,来这里只是看看有没有好的迹象能重新用回GAE,ShadowSocks免费的账号不少的,收费的自己买个VPS也不过一年20多块钱足够自己用了

**Comment by KeyLin** [comment]
我有VPN和ShadowSocks账号卖，价格从优。自建服务器，稳定，不用折腾。

**Comment by annawongfo** [comment]
收费的20多块在哪里买？能不能给个链接？我找到的最少是5元/月的。

**Comment by annawongfo** [comment]
好吧，询个价可以吗？

**Comment by anycall9696** [comment]
在 15/5/1，annawongfo<notifications@github.com> 写道：
> 收费的20多块在哪里买？能不能给个链接？我找到的最少是5元/月的。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/XX-net/XX-Net/issues/293#issuecomment-98071281
淘宝自己买美国VPS空间,自己搭建服务器,很简单的,不会的话+QQ：898-6627我帮你弄

**Comment by annawongfo** [comment]
记下了，如果Goagent和SSX都被屏蔽就准备走这一步了。

**Comment by lifeva** [comment]
更新到1.13，这次干脆不启动了，郁闷

**Comment by xxnet** [comment]
新版已经恢复正常
