### ISSUE TITLE
self-signed SSL certificate issue

### ISSUE THREAD

**Issue by suiwenfeng** [XX-net/XX-Net#2931]
```
Protocol         : tcp
Alert Message    : MALWARE-OTHER self-signed SSL certificate with default Internet Widgits Pty Ltd organization name (1:19551:6)
```

get this alert messages from administrator while using XX-net in company network

is the CA used in XX-net a test SSL ca？ not valid？

**Comment by xiaoas** [comment]
It's valid & signed
You might need to import the CA.crt generated by XX-net

**Comment by suiwenfeng** [comment]
but i continuiously recieved alerts from administrator , it seems the CA created by openssl?
and it cannot go through the enterprise access rules.

How to get a trusted CA?

**Comment by xiaoas** [comment]
It's pretty hard I think...
you might need to add the XX certificate publisher to your company's network host if adding it to your computer doesn't work

**Comment by suiwenfeng** [comment]
if so , you can close the issue. but i think it is a defect...
anyway , i have never got such alerts while using Tor or lantern. 

Last but not least , a technical answer wanted if possible.
