### ISSUE TITLE
xx-net 能否设置一个vpn让外部访问

### ISSUE THREAD

**Issue by huchengbei** [XX-net/XX-Net#2932]
电脑通过xx-net能访问，想设置个vpn通过xx-net让手机也访问啊

**Comment by soiff** [comment]
如果是同一个局域网，可以在XX-net配置中增加：
```
[listen]
ip = 0.0.0.0
```
保存配置并重启XX-net，然后在手机端设置代理为电脑的IP地址:端口。

如果是iPhone，在Wi-Fi设置界面，下拉到最底部有代理设置，将代理设置为手动，输入电脑的同网段地址和端口即可；安卓系统类似找找，没有的话可以下载个代理软件。

要确保Wi-Fi地址和电脑地址是同一个网段，如果手机显示Wi-Fi地址为：`192.168.1.128`/`255.255.255.0`，那么对应电脑的IP地址以`192.168.1`开头才对，比如：`192.168.1.8`

**Comment by soiff** [comment]
更复杂的使用VPN方式，参考这个[软件](https://github.com/SoftEtherVPN/SoftEtherVPN)，确保手机和电脑在同一个私有VPN以后，采用上述设置代理方式，也可以确保你能够通过代理访问网络。这种方式虽然复杂，但不要求电脑和手机在同一个局域网。

**Comment by jzp820927** [comment]
直接监听 4个0 简单多了，设置 VPN 多辅助

**Comment by kimbuy** [comment]
\gae_proxy\local\proxy修改了端口后，关闭XXNET后无法重新开启，是什么原因？修改回127.0.0.1也打不开。双击无反应

**Comment by soiff** [comment]
@kimbuy 打开任务管理器，找到python.exe进程，杀死该进程后重启再试试看~

**Comment by huqiao1206** [comment]
@kimbuy 我也出现了～～不过我保留了data文件夹～剩下的文件及文件夹全部用源码替换了一下～～好了～～

**Comment by kimbuy** [comment]
应该是python.exe的原因，关闭了就可以了，谢谢。
