### ISSUE TITLE
升级3.0.2之后，设置系统代理用Safari只能上google搜索主页，其他需要翻墙的网站都上不了

### ISSUE THREAD

**Issue by VinkenCheng** [XX-net/XX-Net#2935]
升级3.0.2之后，用chrome插件代理一切正常。但是换成设置系统代理用Safari只能上google搜索主页，其他所有需要翻墙的网站（包括Twitter、fb、gmail、google+等）都上不了，之前用2.9.6没问题的

**Comment by VinkenCheng** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17
xxnet-version: 3.0.2

python-version: 2.7.10

ipv6-status: 0
gws-ip-num: total:174 good:85
network-status: OK
connected-link: new:3 used:50
scan-ip-thread-num: 50
ip-quality: 705
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by VinkenCheng** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 3.0.2

python-version: 2.7.10

ipv6-status: 0
gws-ip-num: total:4 good:4
network-status: OK
connected-link: new:4 used:1
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by VinkenCheng** [comment]
删除重装一次还是一样，顺便贴上chrome的状态页

**Comment by xxnet** [comment]
​看看是不是证书问题
另外访问个twitter，再打开gae的日志发上来看看

**Comment by VinkenCheng** [comment]
Apr 17 17:42:38.006 - [INFO] GAE CONNECT twitter.com:443
Apr 17 17:42:38.011 - [INFO] ssl error: EOF occurred in violation of protocol (_ssl.c:590), create full domain cert for host:twitter.com
Apr 17 17:42:41.791 - [INFO] scan_ip add ip:201.57.54.225 time:1241
Apr 17 17:42:45.077 - [WARNING] no enough ip
Apr 17 17:42:45.084 - [DEBUG] get ip:201.57.54.225 t:1241
Apr 17 17:42:46.580 - [INFO] GAE CONNECT www.twitter.com:443
Apr 17 17:42:46.585 - [INFO] ssl error: EOF occurred in violation of protocol (_ssl.c:590), create full domain cert for host:www.twitter.com
Apr 17 17:42:46.585 - [WARNING] no enough ip
Apr 17 17:42:46.821 - [DEBUG] create_ssl update ip:201.57.54.225 time:1158
Apr 17 17:42:47.585 - [WARNING] no enough ip
Apr 17 17:42:49.852 - [WARNING] no enough ip

**Comment by VinkenCheng** [comment]
看起来是证书问题吧？但是我已经把data/gae下的ca.crt导入了，导入后钥匙串那里显示“此根证书不被信任”然后手动修改为信任了

**Comment by VinkenCheng** [comment]
现在用chrome插件代理试了一下twitter

**Comment by VinkenCheng** [comment]
Apr 17 17:54:42.196 - [INFO] GAE CONNECT abs.twimg.com:443
Apr 17 17:54:42.206 - [DEBUG] GAE CONNECT GET https://abs.twimg.com/b/front_page/v1/US_CA_5.jpg
Apr 17 17:54:42.207 - [DEBUG] ssl_pool.get:202.75.141.235 handshake:295
Apr 17 17:54:42.778 - [INFO] GAE CONNECT twitter.com:443
Apr 17 17:54:42.781 - [INFO] GAE CONNECT abs.twimg.com:443
Apr 17 17:54:42.783 - [INFO] GAE CONNECT abs.twimg.com:443
Apr 17 17:54:42.784 - [INFO] GAE CONNECT abs.twimg.com:443
Apr 17 17:54:42.801 - [INFO] GAE CONNECT abs.twimg.com:443
Apr 17 17:54:42.806 - [INFO] GAE CONNECT abs.twimg.com:443
Apr 17 17:54:42.808 - [INFO] GAE CONNECT syndication.twitter.com:443
Apr 17 17:54:42.810 - [INFO] GAE CONNECT syndication.twitter.com:443
Apr 17 17:54:42.811 - [INFO] GAE CONNECT syndication.twitter.com:443
Apr 17 17:54:42.816 - [INFO] GAE CONNECT twitter.com:443
Apr 17 17:54:42.819 - [INFO] GAE CONNECT twitter.com:443
Apr 17 17:54:42.823 - [INFO] GAE CONNECT twitter.com:443
Apr 17 17:54:42.868 - [DEBUG] GAE CONNECT GET https://twitter.com/
Apr 17 17:54:42.868 - [DEBUG] ssl_pool.get:217.18.145.96 handshake:297
Apr 17 17:54:43.700 - [INFO] GAE 23|217.18.145.96|230686 t:831 s:16815 hs:297 Spd:43066 200 https://twitter.com/
Apr 17 17:54:43.713 - [DEBUG] GAE CONNECT POST https://twitter.com/i/jot
Apr 17 17:54:43.714 - [DEBUG] ssl_pool.get:217.18.145.96 handshake:297
Apr 17 17:54:43.935 - [DEBUG] 190.113.97.227 close:host pool alive_timeout
Apr 17 17:54:43.937 - [DEBUG] ssl_closed 190.113.97.227
Apr 17 17:54:44.124 - [INFO] GAE 23|217.18.145.96|247972 t:410 s:0 hs:297 200 https://twitter.com/i/jot
Apr 17 17:54:44.185 - [DEBUG] GAE CONNECT GET https://abs.twimg.com/b/front_page/v1/US_CA_7.jpg
Apr 17 17:54:44.185 - [DEBUG] ssl_pool.get:217.18.145.96 handshake:297
Apr 17 17:54:45.594 - [WARNING] gae_handler send to browser return error(32, 'Broken pipe') 'https://abs.twimg.com/b/front_page/v1/US_CA_5.jpg'
Apr 17 17:54:45.594 - [INFO] GAE 42|202.75.141.235|745399 t:3387 s:167364 hs:295 Spd:57475 200 https://abs.twimg.com/b/front_page/v1/US_CA_5.jpg
Apr 17 17:54:48.223 - [INFO] GAE 23|217.18.145.96|248349 t:4037 s:176521 hs:297 Spd:48698 200 https://abs.twimg.com/b/front_page/v1/US_CA_7.jpg
Apr 17 17:54:48.587 - [DEBUG] GAE CONNECT GET https://syndication.twitter.com/i/jot/syndication?l=%7B%22_category_%22%3A%22syndicated_impression%22%2C%22event_namespace%22%3A%7B%22client%22%3A%22web%22%2C%22page%22%3A%22front%22%2C%22action%22%3A%22impression%22%7D%2C%22triggered_on%22%3A1460886888571%7D
Apr 17 17:54:48.587 - [DEBUG] ssl_pool.get:202.75.141.235 handshake:295
Apr 17 17:54:48.613 - [INFO] GAE CONNECT www.google-analytics.com:443
Apr 17 17:54:48.621 - [DEBUG] GAE CONNECT GET https://www.google-analytics.com/collect?v=1&_v=j41&a=844909201&t=pageview&_s=1&dl=https%3A%2F%2Ftwitter.com%2F&dp=%2Fanon%2Ffront%2Ffront&ul=zh-cn&de=UTF-8&dt=%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%20Twitter%20-%20%E7%99%BB%E5%BD%95%E6%88%96%E6%B3%A8%E5%86%8C&sd=24-bit&sr=1920x1080&vp=1920x1080&je=0&fl=21.0%20r0&_u=ACCAgAAB~&jid=&cid=1982549855.1459244506&tid=UA-30775-6&z=1418331854
Apr 17 17:54:48.621 - [DEBUG] ssl_pool.get:217.18.145.96 handshake:297
Apr 17 17:54:49.009 - [INFO] GAE 42|202.75.141.235|913239 t:421 s:65 hs:295 200 https://syndication.twitter.com/i/jot/syndication?l=%7B%22_category_%22%3A%22syndicated_impression%22%2C%22event_namespace%22%3A%7B%22client%22%3A%22web%22%2C%22page%22%3A%22front%22%2C%22action%22%3A%22impression%22%7D%2C%22triggered_on%22%3A1460886888571%7D
Apr 17 17:54:49.265 - [INFO] GAE 23|217.18.145.96|425198 t:644 s:35 hs:297 200 https://www.google-analytics.com/collect?v=1&_v=j41&a=844909201&t=pageview&_s=1&dl=https%3A%2F%2Ftwitter.com%2F&dp=%2Fanon%2Ffront%2Ffront&ul=zh-cn&de=UTF-8&dt=%E6%AC%A2%E8%BF%8E%E6%9D%A5%E5%88%B0%20Twitter%20-%20%E7%99%BB%E5%BD%95%E6%88%96%E6%B3%A8%E5%86%8C&sd=24-bit&sr=1920x1080&vp=1920x1080&je=0&fl=21.0%20r0&_u=ACCAgAAB~&jid=&cid=1982549855.1459244506&tid=UA-30775-6&z=1418331854

**Comment by VinkenCheng** [comment]
更改下问题，应该是google.com.hk的都可以访问，其他的就不行了。

**Comment by xxnet** [comment]
​看上去证书已经被接受了，代理设置正常，但浏览器拒绝接收数据，很奇怪。

你试试装个chrome

**Comment by VinkenCheng** [comment]
chrome我有啊，只是平时上网一般都是用Safari，方便和手机同步

**Comment by VinkenCheng** [comment]
我有个朋友在2.9.6版本曾经遇到过类似问题，后来通过 sudo killall -9 networkd 解决了 @xxnet

**Comment by xxnet** [comment]
先通过chrome对比，排查问题出在什么地方

网上没有找到networkd 太多资料

**Comment by VinkenCheng** [comment]
没找到原因，总结一下：

**Comment by jzp820927** [comment]
只有 safari 有问题，其他都正常，那说明问题和 XX 没有关系，应该是 safari 浏览器自身的问题吧

**Comment by VinkenCheng** [comment]
但是今天升级3.X.X之前用2.9.6一切正常啊，不知道是不是新版本的改动导致的问题。对了，还有，新版本mac开启自启无效

**Comment by xxnet** [comment]
开机自启动是因为没有start.command
前面有提交说start.sh 可以实现，不会弹出窗口
是否需要保留start.command?

**Comment by VinkenCheng** [comment]
start.sh 实现不会弹出窗口这个我知道，现在已经默认没窗口了啊，所以原来那条sudo xx-net.sh start命令也没必要了。
我看了一下com.xxnet.launcher.plist，里面写的是start.sh，而老版本的是start.command，我还以为现在改了呢

**Comment by VinkenCheng** [comment]
start.sh 实现不会弹出窗口这个我知道，现在已经默认没窗口了啊，所以原来那条sudo xx-net.sh start命令也没必要了。
我看了一下com.xxnet.launcher.plist，里面写的是start.sh，而老版本的是start.command，我还以为现在改了呢

**Comment by VinkenCheng** [comment]
3.0.4 Safari翻墙异常的问题已解决，对比了一下。前面ca证书会自动导入到“钥匙串-登录”里面，而现在是在“钥匙串-系统”里面 @xxnet

**Comment by jzp820927** [comment]
原来是 证书的问题，证书应该只影响 https，对 http 应该没影响吧，那也不至于除了 google，其他都不行吧

**Comment by VinkenCheng** [comment]
start.command修改了一下丢到xx-net根目录，把com.xxnet.launcher.plist的路径指向start.command可以开机自启了
[start.command.zip](https://github.com/XX-net/XX-Net/files/222694/start.command.zip)
