### ISSUE TITLE
已允许远程连接Web控制端，但通过 ip:8085/ 还是访问不了 

### ISSUE THREAD

**Issue by huchengbei** [XX-net/XX-Net#2937]
提示如下：
您被禁止访问互联网

防火墙或防病毒软件可能已阻止您连接到网络。
请试试以下办法：
检查网络连接
检查防火墙和防病毒配置
ERR_NETWORK_ACCESS_DENIED

**Comment by jzp820927** [comment]
试试本机能不能用  ip:8085/ 访问？

**Comment by huqiao1206** [comment]
本机也不行

**Comment by jzp820927** [comment]
那应该是你设置不正确，看看监听装  8085 端口 是不是监听的 0.0.0.0
