### ISSUE TITLE
iphone5  IOS 9.3.1 通过设置代理上网，证书问题

### ISSUE THREAD

**Issue by KevinSunJin** [XX-net/XX-Net#2955]
遇到的问题是，手机通过设置代理上网，每次xx-net升级后都要重新装一边证书
![image](https://cloud.githubusercontent.com/assets/13011160/14593306/71222bb2-055b-11e6-800e-c5bfa7fab09a.png)

并且家里、公司用的是相同版本的XX-NET，在公司安装过证书后在家里还要重新装一边证书才能正常使用，关键问题是证书只能装一个。
有什么好的解决办法吗？

**Comment by KevinSunJin** [comment]
同样在家里安装证书后，到公司又要再重新安装证书，同样版本的XXNET家里跟公司电脑里的证书不兼容(data\gae_proxy 下的CA.crt)？

**Comment by jzp820927** [comment]
你把家里，或者公司其中的一个证书考到另一个地方，证书就统一了。以后升级先备份证书，升级完了，再还原证书，就不用每次升级偶安装证书了。

**Comment by elvis1121** [comment]
我关联这个地址完全木用啊😂

**Comment by Jaggle** [comment]
这样就可以让手机翻墙吗？我试了好像不行啊

**Comment by jzp820927** [comment]
那肯定是你设置不对，肯定可以的

**Comment by KevinSunJin** [comment]
@jzp820927 Good idea.进入了思维误区，没想起来统一CA.crt 文件，以前升级只是会备份manual.ini 和good_ip.txt

**Comment by KevinSunJin** [comment]
@Jaggle 配置文件中 listen下的ip设为0.0.0.0；xx-net 选择Set Global Pac Proxy

**Comment by Jaggle** [comment]
@KevinSunJin 非常感谢你的反馈，现在我按照你的要求配置重启了xx-net，但是手机还不行，是不是手机要装什么插件，或者你说的导证书是怎么回事，需要向手机中导入证书吗？

**Comment by jzp820927** [comment]
@Jaggle 你先确认电脑端的 XX 是不是监听的 4个0 端口，如果是，再检查手机代理设置的 IP ，是不是电脑端的IP，如果这2个都没问题，肯定就没问题。证书只影响 https 网站 ，对 http 网站没有影响。

**Comment by Jaggle** [comment]
@KevinSunJin ，能否帮我看一下我的配置哪里出问题了，现在我改IP了电脑可以翻墙，但是手机还是不行，下面是我的配置截图：
电脑xx-net配置页面显示的配置：

![img1](http://static.yeskn.com/images/2.png)


手机的配置：

![img1](http://static.yeskn.com/images/1.png)

**Comment by jzp820927** [comment]
@Jaggle 我去，你如果要用 PAC ，PAC 的监听也要改成 4个0，你这儿是 127.0.0.1 ，肯定不行啊

![image](https://cloud.githubusercontent.com/assets/5740066/14638862/17ae281c-066c-11e6-939f-4e32327ac1ed.png)
