### ISSUE TITLE
建议项目描述去掉翻墙套件，如果只是为了翻墙，层次一下子就低了许多

### ISSUE THREAD

**Issue by soiff** [XX-net/XX-Net#2961]
我认为XX-Net定位应该是为广大科研人员有效访问互联网资源提供可行方案的，而不仅仅是翻墙，况且翻墙总感觉有点政治意味在里面，某种程度上还是偷偷摸摸见不得光的。

说句实话，个人使用XX-Net查资料、查解决方案居多，非死不可、推特什么的也没什么兴趣，访问谷歌、亚马逊、优图碧和一些不通过隧道基本无法访问(主要还是受网络负载影响)的优秀解决方案网站占据了绝大多数流量。

我所在的行业，谷歌亚马逊拍袜套阿帕奇等等这些老牌技术型公司几乎有全套的解决方案，非常感谢老外为我们准备了这么好的平台，包括林林总总的开源软件。

没有别的意思，只是希望XX-Net能够产生更大的价值，能走的更远！

**Comment by yeahwu** [comment]
首先，俺不反对改描述，
但是，你通篇在我认为，我所在的行业，个人使用……
xx不是为你个人提供的，你不上facebook，推特等，别人要上
还有你所说的，不仅仅是翻墙，但是归根结底就是翻墙，换个名称，它也还是翻墙工具

**Comment by yeahwu** [comment]
还有，不上facebook，不上推特，
就到google，亚马逊等平它查查资料做做项目，就不是翻墙了？别自欺欺人了

**Comment by BruinY** [comment]
挺逗逼的一想法。不翻墙来这里装什么X

**Comment by soiff** [comment]
@yeahwu @BruinY 两位为何攻击性这么强？我在这里装X有什么好处？我不想攻击两位，也请两位冷静一下，如题所述，这只是个建议，采不采纳我都没有什么意见。阁下翻墙的理由可能和这个不同，而且我不曾攻击过其他人翻墙理由。至于对推特非死不可的兴趣，我也说那是个人（明确一下，这个个人仅指我）兴趣，两位没必要非得往自己身上套。所以，两位有意见欢迎良性讨论，不喜欢请绕行！

**Comment by BruinY** [comment]
@soiff 傻孩子。这就算是攻击了？你还真是脆弱呀。你好好看看你的言论，什么叫做提供有效访问互联网资源提供可行方案。其核心本质就是翻墙。你说一堆废话，没人鄙视你，你还说别人攻击你。思维有够混乱的。

**Comment by simonasd** [comment]
这其实是很多初出墙人的普遍想法。类似的还有，“请不要在Github上发布政治内容”等等。从小生活在大陆，也难免。想我们大多数人，不都有一段这样的时期吗？随着眼界的开阔，人对事物的认知是会改变的。希望不要在这些方面有太多的争吵。

@soiff 
回答一下楼主的问题——实际上在issue区回答过无数次了，再重复一遍。
1. 这种行为属于自我审查。
2. 自我审查既不能提升逼格，也不能避免被gfw关注。
3. 事实上在防火墙之外，自我审查普遍被认为是一种很low的行为。过去也有一些打着擦边球提供服务的低调工具，但均已被封，说明闷声发大财并不是醉吼的。
4. 从SEO的角度，挂出招牌，有利于揽客。翻墙是网络反审查手段在中国大陆等地区语境的特殊称谓，并无任何不妥。
5. 从xxnet项目的角度看，本项目的定位并不是为科研人员提供Google学术访问渠道。而是让中国、伊朗等国家的民众拥有不受在地政府审查的网络访问权限，也就是翻墙。

**Comment by yeahwu** [comment]
没别的意思，你可能嫌弃"翻墙工具套件“这几个字不文雅，这个俺还是赞成的
但是你说定位应该是为广大科研人员有效访问互联网资源提供可行方案
这个定位未免狭隘，小众了？

**Comment by soiff** [comment]
@BruinY 如果不是攻击，收回你的侮辱不雅用词，我不和你争论这个！

@simonasd 我和你的观点不同，但并不妨碍正常交流。

既然这个话题比较敏感，意见也有比较大的出入，没有继续存在的必要。我关闭这个问题，浪费各位时间了，抱歉！

**Comment by BruinY** [comment]
其实没有什么雅不雅，又不是叫"出柜工具套装"。做人不能这么自欺欺人。
就个人观点来说，没有什么敏感不敏感，既不是政治问题也不是立场问题，对于该项目而言，更多是学术问题，技术问题。

**Comment by simonasd** [comment]
@soiff 其实这个话题并不敏感，完全可以讨论。只是长久以来（至少可以追溯到好多年前，xxnet项目成立之前的goagent时代），许多新人刚来的时候都会发起类似的讨论，客观上消耗了一些社区老成员的耐心吧。

当然，从另一个方面讲，在提出issue之前，如果能对既往的讨论稍加检索，可能会更好。祝好。

**Comment by soiff** [comment]
@simonasd 多谢提醒，我会关注。我从不会在意谁是老人谁是新人，对我没有什么意义。笔者提出这个问题确实有失偏颇，因为没什么意义，笔者会自我反思。

@BruinY @simonasd 这个问题不作过多讨论，即浪费各位时间，也没有什么太大的价值，感谢大家参与！
