### ISSUE TITLE
开启XX-Net后死机

### ISSUE THREAD

**Issue by always-waiting** [XX-net/XX-Net#2970]
我的电脑在开启XX-Net后总是死机,正常浏览网页的时候就会卡死.
其他的程序也没有开.
我测试了一下不开XX-Net的时候,死机的情况就没有了.

难道是我的电脑太破了吗?还是我开启程序的方法有问题?

```
nohup sudo python2 launcher/start.py &
```

**Comment by jzp820927** [comment]
你是 Linux ？还从来没听说过 Linux 也会司机

**Comment by netRuby** [comment]
内存明显不够

**Comment by Hollykitty** [comment]
感觉是XX net的内存/CPU的性能门槛要求高问题，我同样使用win10 x64，chrome，相同的扩展，台式机16g内存，较高cpu，使用起来未卡机。另外两台4g内存，i3笔记本，在偶尔打开网页时会卡机达10秒~几分钟之间，ip扫描数调整为1无效。
网上搜索了其他人均有此情况，win7，win8，win10都不例外，似乎都是配置较低。

**Comment by always-waiting** [comment]
@Hollykitty 
是啊，我的电脑才3G内存......
都不敢开10个以上的网页。

**Comment by jzp820927** [comment]
估计应该是 浏览器占用资源，和XX应该没关系

**Comment by always-waiting** [comment]
@jzp820927 

现在看来是这样，用了一台新电脑，再也没有出现死机的情况了

**Comment by jzp820927** [comment]
你太牛了，你用了整整半年时间，才找到问题根源。
