### ISSUE TITLE
只能chrome能上网？

### ISSUE THREAD

**Issue by ydl825312** [XX-net/XX-Net#298]
xxnet是全局代理么？怎么我装了这个后只能chrome上网，sasfari不能上Apple store也连不上

**Comment by ydl825312** [comment]
Safari显示  GoAgent代理处理超时，请查看日志！  但是我上的是百度新浪这些啊……

**Comment by xxnet** [comment]
默认不会打开全局代理。
安装后不会影响其他应用使用。

建议用Chrome，方便切换代理模式。

**Comment by xxnet** [comment]
应该是当时墙太高，新版已经恢复正常
