### ISSUE TITLE
connection aborted. too short headers data=ent 服务端已经在 2014-11-26 15:51:45 升级到 3.

### ISSUE THREAD

**Issue by zqzhuqiu** [XX-net/XX-Net#30]
connection aborted. too short headers data=ent 服务端已经在 2014-11-26 15:51:45 升级到 3.
不知道什么意思啊

**Comment by xxnet** [comment]
请重新部署服务端

**Comment by angel126** [comment]
这个是怎么部署呀？
是通过XX-Net-1.0.9\goagent\3.1.34\server 下面的upload 来部署吗？

**Comment by xxnet** [comment]
访问http://127.0.0.1:8085/ 看deploy

**Comment by xxnet** [comment]
1.1.0 对这个提示进行了优化，会直接显示“请部署新版服务端”
