### ISSUE TITLE
代理访问1024受限制，Tunnel无限制

### ISSUE THREAD

**Issue by nalanqinwang** [XX-net/XX-Net#3005]
t66y.com 
草榴社區：您所處的網絡環境被限制訪問，需要驗證后，才可進行基礎瀏覽（無法發帖，回帖）
未升级前旧版本代理不受限制。

**Comment by jzp820927** [comment]
按理说，这种提示，应该是 1024 限制了 GAE IP 的访问。

**Comment by nalanqinwang** [comment]
IP不是扫出来的么？他不可能全部限制的吧？

**Comment by jzp820927** [comment]
你扫的只是连接 GAE 的IP，部署 GAE 的出口 IP ，GAE 的出口 IP，是固定的，而且数量不多。如果网站要限制 GAE 的代理访问，很容易的

**Comment by nalanqinwang** [comment]
有解决办法么？

**Comment by jzp820927** [comment]
没办法，只能换代理，或者就用 X_TUNNEL
