### ISSUE TITLE
非常感谢作者，希望能解决无法看视频的硬伤。

### ISSUE THREAD

**Issue by fhzyfjy** [XX-net/XX-Net#301]
非常感谢作者的辛苦劳动。目前大部分网友都希望可以用该软件看视频。但除了youtube外，绝大部分视频无法观看（用自己的ID）。但在goagent中没有这个问题（但现在IP基本死光了）。希望能解决无法看视频的硬伤。谢谢

**Comment by fhzyfjy** [comment]
补充说明，看了前面网友有关无法观看视频的留言，大部分都集中在http://www.xvideos.com，这个网站。谢谢

**Comment by kingour** [comment]
看这些大部分报了504，goagent3.2上ok的

**Comment by xxnet** [comment]
恩，目前还有很多网友说无法使用，所以暂时重点还是解决可用性问题，
等稳定下来了，再处理视频吧，精力有限，请谅解

2015-05-03 23:16 GMT-04:00 Kingour <notifications@github.com>:

**Comment by xxnet** [comment]
1.13.6解决了视频下载限速网站，导致下载失败。
需要重新部署服务端。

请测试。

在 2015年5月4日 上午9:00，Net XX <xxnet.dev@gmail.com>写道：
