### ISSUE TITLE
The new version seems will delete files improperly on start

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#3010]
I upgraded xxnet to 3.0.4, for my `Linux` machine, then found that on starting xxnet process, following files are deleted automatically, thus making it impossible to start xxnet again.

```

	deleted:    launcher/DO_NOT_PUT_ANYTHING_HERE
	deleted:    launcher/start.py

```

Following are errors when try to start xxnet again:

```
Apr 21 20:31:31.761 - [INFO] start XX-Net 3.0.4
Apr 21 20:31:31.761 - [DEBUG] start confirm_xxnet_exit
Apr 21 20:31:31.762 - [DEBUG] good, xxnet:8087 cleared!
Apr 21 20:31:31.762 - [DEBUG] good, xxnet:8085 clear!
Apr 21 20:31:31.762 - [DEBUG] finished confirm_xxnet_exit
Apr 21 20:31:31.762 - [ERROR] launcher except:OSError(2, 'No such file or directory')
Apr 21 20:31:31.763 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 143, in <module>
  File "code/default/launcher/start.py", line 115, in main
  File "/mnt/star/git_repository/xxnet/code/default/launcher/post_update.py", line 27, in run
    shutil.rmtree(os.path.join(top_path, 'launcher')) # launcher is for auto-update from 2.X
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/mnt/star/git_repository/xxnet/launcher'

Press any to exit...

```

Seems due to the missing file `code/default/launcher/start.py`.

I need do `git reset --hard` to make it work again.
I checked source code of file `xxnet` and `code/default/launcher/start.py`, but didn't found which part delete the code.

So, can anyone fix this bug ?

**Comment by jzp820927** [comment]
我去，升个级，文件都升丢了

**Comment by kuchaguangjie** [comment]
I updated the code via git, the file `code/default/launcher/post_update.py` changed, and the bug was gone, so it seems to be this `post_update.py` that had deleted files improperly.

The relevant line changes are:

```

-    run_cmd = os.path.abspath( os.path.join(root_path, "start.sh"))
+    run_cmd = os.path.abspath( os.path.join(root_path, os.pardir, os.pardir, "xxnet"))

```

Good work, but I suggest after each bug fix, should create a new tag for it, e.g `3.0.5 beta 1`, and inform people about that, if the bug has been raised in `issues`.
