### ISSUE TITLE
PHP Proxy not Working in Debian 8

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#302]
XX-Net Status:

| Property            | Value                                                                                                       |
| ------------------- |-------------------------------------------------------------------------------------------------------------|
| Sys Platform        | linux2                                                                                                      |
| OS System           | Linux                                                                                                       |
| OS version          | #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13)                                                                    |
| OS release          | 3.16.0-4-amd64                                                                                              |
| OS detail           | Dist:debian; Version:8.0; ID:                                                                               |
| language            | en_US                                                                                                       |
| architecture        | 64bitELF                                                                                                    |
| Browser             | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36    |
| XX-Net Version      | 1.12.5                                                                                                      |
| Launcher Version    | 1.4.0                                                                                                       |
| GoAgent Version     | 3.1.49                                                                                                      |
| Python Version      | 2.7.9                                                                                                       |
| Proxy Listen        | 127.0.0.1:8087                                                                                              |
| working appids      | ????????                                                                                                    |
| Out of Quota appids |                                                                                                             |
| Not Exist appids    |                                                                                                             |
| PAC URL             | http://127.0.0.1:8086/proxy.pac                                                                             |
| Google IP           | 2851                                                                                                          |
| connected link      | 0,0                                                                                                         |
| ip-connect-interval | 10                                                                                                          |
| block stat          | OK                                                                                                          |
Error Log:
```
Exception happened during processing of request from ('127.0.0.1', 48479)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/media/Data/Applications/GoAgent/xx-net/php_proxy/1.0.0/local/proxylib.py", line 619, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/media/Data/Applications/GoAgent/xx-net/php_proxy/1.0.0/local/proxy.py", line 763, in __init__
    SimpleProxyHandler.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/media/Data/Applications/GoAgent/xx-net/php_proxy/1.0.0/local/proxylib.py", line 1295, in handle_one_request
    return BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/media/Data/Applications/GoAgent/xx-net/php_proxy/1.0.0/local/proxylib.py", line 1326, in do_METHOD
    return plugin.handle(self, **action[1])
  File "/media/Data/Applications/GoAgent/xx-net/php_proxy/1.0.0/local/proxylib.py", line 726, in handle
    self.do_ssl_handshake(handler)
  File "/media/Data/Applications/GoAgent/xx-net/php_proxy/1.0.0/local/proxylib.py", line 713, in do_ssl_handshake
    ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
  File "/media/Data/Applications/GoAgent/xx-net/python27/1.0/lib/linux/gevent/ssl.py", line 419, in wrap_socket
    ciphers=ciphers)
  File "/media/Data/Applications/GoAgent/xx-net/python27/1.0/lib/linux/gevent/ssl.py", line 86, in __init__
    self._sslobj = _ssl.sslwrap(self._sock, server_side,
AttributeError: 'module' object has no attribute 'sslwrap'
```

**Comment by xxnet** [comment]
试试自己安装gevent
sudo pip install gevent

2015-04-30 22:29 GMT-04:00 Howard Shieh <notifications@github.com>:

**Comment by zjhzxhz** [comment]
I've installed `gevent`.
```
sudo apt-get install python-gevent
sudo pip install gevent
```

But still not working. 
And I CANNOT get exception this time from Shell or Web Log Window.

**Comment by xxnet** [comment]
debian 8还没有测试过，明天装个试试。

2015-05-05 5:30 GMT-04:00 Howard Shieh <notifications@github.com>:

**Comment by xxnet** [comment]
测试过，似乎是debian8 的gevent不完整。

python2.7 已经慢慢被淘汰了，gevent侵入模式，带来性能改善，缺很难维护。
如果一定要用php模式，先用goagent原版吧，早期的版本，好像3.1.18，可以不用gevent.

**Comment by zjhzxhz** [comment]
哦~~ 这样子~
主要是前段时间GoAgent模块不是不稳定嘛~
所以就会用下PHP模式~
现在稳定了就无所谓了~

2015-05-11 16:06 GMT+08:00 xxnet <notifications@github.com>:

> 测试过，似乎是debian8 的gevent不完整。
>
> python2.7 已经慢慢被淘汰了，gevent侵入模式，带来性能改善，缺很难维护。
> 如果一定要用php模式，先用goagent原版吧，早期的版本，好像3.1.18，可以不用gevent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/302#issuecomment-100807175>.
>



-- 

谢浩哲
