### ISSUE TITLE
IP一天比一天少怎么解决？

### ISSUE THREAD

**Issue by asaketsu** [XX-net/XX-Net#3020]

**Comment by windleafy** [comment]
开大扫描进程数

**Comment by jzp820927** [comment]
这几天IP都解封不少了，你居然还一天不一天少，不晓得你是啥宽带

**Comment by yukuai0011** [comment]
换个ip段

**Comment by yukuai0011** [comment]
最近确实解封了好多，g**f（）w估计扛不住了，我居然还扫到了一个日本ip

**Comment by asaketsu** [comment]
刚还得瑟，就挂了，好像不能用了一下子，重启不了了，傻了

**Comment by asaketsu** [comment]
大家看看都还能用不？

**Comment by windleafy** [comment]
目前正常
![1](https://cloud.githubusercontent.com/assets/18212994/14741992/7310345e-08cc-11e6-8145-f1013838ad1a.png)

**Comment by jzp820927** [comment]
这几天 IP 数量上千，都很正常，解封很多了

**Comment by keyoushi** [comment]
![qq 20160422210004](https://cloud.githubusercontent.com/assets/17884782/14742246/b2159314-08cd-11e6-8c54-3363599aba27.jpg)

**Comment by keyoushi** [comment]
在XX-Net\data\gae_proxy里面自行配置manual.ini文件，然后
[google_ip]
use_ipv6 = 0
auto_adjust_scan_ip_thread_num = 1
max_scan_ip_thread_num = ？自己改
max_good_ip_num = ？自己改
ip_connect_interval = 10

**Comment by asaketsu** [comment]
你们别晒了，我就得瑟了一下，就再也不能用了，也不能重启软件了，大神教教

**Comment by CHN008** [comment]
是的,现在可用IP比之前多得多了,怎么会少?

**Comment by windleafy** [comment]
重新下个包，换个目录重新装下呗

**Comment by asaketsu** [comment]
网络无法连接，请检查网络和防火墙设置。

本地网络状态	Fail

================
间断性出现怎么解决？

**Comment by windleafy** [comment]
这象是网络接触不好啊

**Comment by jzp820927** [comment]
这种问题不确定是什么原因导致的，但是本地网一般应该是不会出问题的

**Comment by keyoushi** [comment]
估计是笨雷 关掉这一类的下载工具试试

**Comment by asaketsu** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36
xxnet-version: 3.0.2

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:1303 good:198
network-status: OK
connected-link: new:8 used:29
scan-ip-thread-num: 500
ip-quality: 548
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
=================================
感觉超级不稳定了今天突然
IP从800降到了100多

**Comment by jzp820927** [comment]
说起迅雷我倒真觉得可能是他的原因，因为之前看到一个 issues 也是这个问题，然后他说卸了迅雷就好了

**Comment by asaketsu** [comment]
那会发现问题了，已经卸了QQ和QQ浏览器，那就也卸了迅雷吧

**Comment by asaketsu** [comment]
xxnet-version: 3.0.2

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:1308 good:729
network-status: OK
connected-link: new:4 used:50
scan-ip-thread-num: 500
ip-quality: 296
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
============================
立杆见影？！
见了鬼了

**Comment by keyoushi** [comment]
有什么奇怪的？笨雷大法好23333333

**Comment by jzp820927** [comment]
珍爱生命，远离国软

**Comment by tengjunhui123** [comment]
怎么你们的版本那么高，最新的不是2.9.7吗_(:3」 ∠）_

**Comment by windleafy** [comment]
最新版本下载地址
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by tengjunhui123** [comment]
我也是只找到十几个可用ip，开的200线程_(:3」 ∠）_【谢谢楼上~】

**Comment by jzp820927** [comment]
最近解封不少IP，多扫描些时间，就能知道结果了
