### ISSUE TITLE
如何配置只使用自己配置的ipList，将自带的iplist清空？

### ISSUE THREAD

**Issue by NorthFacing** [XX-net/XX-Net#303]
1、导入ip显示导入成功，保存在哪个文件中了呢？全局搜索并没有找到，是否表示并没有导入成功呢？
2、能不能告诉下怎么将软件本身的iplist清空，只使用自己导入的iplist？需要更改那个配置文件，像goagent配置proxy.ini中的[iplist]那样？

**Comment by Cat7373** [comment]
将XX-Net/data/goagent/good_ip.txt的内容清空试试- -

**Comment by Cat7373** [comment]
将XX-Net/data/goagent/good_ip.txt的内容清空试试- -

**Comment by NorthFacing** [comment]
@Cat7373 这个清空之后就上不了网了

**Comment by Cat7373** [comment]
对啊，这不是你问的第二个问题么？
就是这么清空的啊
然后再导入自己的不就可以了

**Comment by NorthFacing** [comment]
@Cat7373 清空之后就导入不进去了，你可以试下

**Comment by xxnet** [comment]
新版试过，可以正常导入。
