### ISSUE TITLE
连接超时，先休息一会再来！

### ISSUE THREAD

**Issue by harryhkyy** [XX-net/XX-Net#304]
连接超时，先休息一会再来！
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_TW
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.12.3
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	harryhky|harryhkyy|harryhkyy2|harryhkyy3|harryhkyy4|harryhkyy5|harryhkyy6|harryhkyy7|harryhkyy8|harryhkyy9|harryhkyy10|harryhkyy11|harryhkyy12|harryhkyy13|harryhkyy14|harryhkyy15|harryhkyy16|harryhkyy17|harryhkyy18|harryhkyy19|harryhkyy20|harryhkyy21|harryhkyy22|harryhkyy23|harryhkyy24|harryhkyy25|harryhkyy26|harryhkyy27|harryhkyy28|harryhkyy29|harryhkyy30|harryhkyy31|harryhkyy32|harryhkyy33|harryhkyy34|harryhkyy35|harryhkyy36|harryhkyy37|harryhkyy38|harryhkyy39|harryhkyy40|harryhkyy41|harryhkyy42|harryhkyy43|harryhkyy44|harryhkyy45|harryhkyy46|harryhkyy47|harryhkyy48|harryhkyy49
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	3000
connected link	7,7
ip-connect-interval	10
block stat(帮助)	OK
May 01 14:12:40 - [INFO] GAE t:401 s:37 200 https://5-edge-chat.facebook.com/pull?channel=p_636223821&seq=0&partition=-2&clientid=3b06b504&cb=8q27&idle=26&cap=8&msgs_recv=34&uid=636223821&viewer_uid=636223821&sticky_token=82&sticky_pool=prn1c13_chat-proxy&traceid=47vy6&state=active
May 01 14:12:41 - [DEBUG] create_ssl 218.176.242.50 fail:timed out cost:2000 h:0
May 01 14:12:41 - [DEBUG] report_connect_fail network fail recently
May 01 14:12:41 - [DEBUG] create_ssl update ip:64.233.179.200 time:690
May 01 14:12:41 - [DEBUG] direct_create_ssl 123.205.251.84 fail:timed out cost:2001 h:0
May 01 14:12:41 - [DEBUG] report_connect_fail network fail recently
May 01 14:12:41 - [DEBUG] direct_create_ssl 111.168.255.177 fail:timed out cost:2000 h:0
May 01 14:12:41 - [DEBUG] report_connect_fail network fail recently
May 01 14:12:42 - [DEBUG] get ip:74.125.229.70 t:1160
May 01 14:12:42 - [DEBUG] direct_create_ssl 149.3.177.118 fail:timed out cost:2003 h:0
May 01 14:12:42 - [DEBUG] report_connect_fail network fail recently
May 01 14:12:42 - [DEBUG] create_ssl 74.125.139.123 fail:timed out cost:2003 h:0
May 01 14:12:42 - [DEBUG] get ip:74.125.236.71 t:1160
May 01 14:12:42 - [DEBUG] create_ssl 178.45.251.93 fail:timed out cost:2000 h:0
May 01 14:12:42 - [DEBUG] network is fail
May 01 14:12:42 - [DEBUG] report_connect_fail network fail
May 01 14:12:42 - [DEBUG] create_ssl 216.58.220.163 fail:timed out cost:2001 h:0
May 01 14:12:42 - [DEBUG] report_connect_fail network fail recently
May 01 14:12:42 - [DEBUG] get ip:173.194.213.137 t:1160
May 01 14:12:42 - [DEBUG] create_ssl 149.126.86.42 fail:timed out cost:2000 h:0
May 01 14:12:42 - [DEBUG] report_connect_fail network fail recently
May 01 14:12:42 - [DEBUG] network is ok
May 01 14:12:42 - [DEBUG] get ip:173.194.203.122 t:1160
May 01 14:12:43 - [DEBUG] get ip:64.233.166.199 t:1161
May 01 14:12:43 - [DEBUG] get ip:216.58.211.127 t:1161
May 01 14:12:43 - [DEBUG] get ip:64.233.191.133 t:1161
May 01 14:12:43 - [DEBUG] get ip:31.209.137.59 t:1261
May 01 14:12:43 - [DEBUG] get ip:216.58.220.228 t:1161

**Comment by zhanglaplace** [comment]
我也总是这个问题。

**Comment by nocole** [comment]
一样的，G+社区刷开一半就不动了，再刷新就是连接超时

**Comment by lifeva** [comment]
知足吧，1.13干脆启动不了

**Comment by yjd** [comment]
因为快到5.4又封得严格了。

**Comment by xxnet** [comment]
新版已恢复
