### ISSUE TITLE
在部署新的APPID时无法弹出认证页是什么情况？

### ISSUE THREAD

**Issue by changshunxu520** [XX-net/XX-Net#3044]
我确信我没有屏蔽弹出框？版本是3.04

**Comment by simonasd** [comment]
您的默认浏览器是？

**Comment by changshunxu520** [comment]
无论默认浏览器是IE亦或者是Chrom都不行，好郁闷，win10系统专业版64bit

**Comment by tigerstorm2009** [comment]
同样的问题，不弹框，但是提示部署成功，之后再去墙外提示appid无效，需要先部署

**Comment by changshunxu520** [comment]
我的今天晚上可以弹出来了，不知道是为啥

2016-04-25 21:06 GMT+08:00 tigerstorm2009 <notifications@github.com>:

**Comment by weiguang-yin** [comment]
同样的问题，不过我的系统是 LMDE
firefox / chrome 都不行
xx-net: 3.0.4

**Comment by jzp820927** [comment]
这个估计是系统的问题吧
