### ISSUE TITLE
YouTube视频无法上传

### ISSUE THREAD

**Issue by Beginner258** [XX-net/XX-Net#3048]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:441 good:131
network-status: OK
connected-link: new:13 used:0
scan-ip-thread-num: 50
ip-quality: 239
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

可以正常看，但是没法上传，我发现github开了代理之后头像也无法上传，难道是上传时翻不过去？

**Comment by N46AN** [comment]
这是老问题。自行搜索本项目 issues

**Comment by LGA1150** [comment]
通过Google相册中转
