### ISSUE TITLE
家里的XX-net是好的了，但是公司的

### ISSUE THREAD

**Issue by changshunxu520** [XX-net/XX-Net#3061]
一直提示网络无法访问，请检查防火墙。。。可是我全部都关闭了啊

**Comment by JMaxime** [comment]
看看连接池的数量 我以前也遇到过

**Comment by changshunxu520** [comment]
连接池数量是有的，只是新的少，已用的多。只是一会显示XX-Net 3.0.4 ，一切正常，你可以访问真正的互联网了，然后一会就显示网络无法访问，请检查防火墙。本地网络状态一会是OK一会是unkonw,一会又是Fail

**Comment by Antecer** [comment]
我也出现这样的问题了，不知道什么鬼。
家里的移动网络能用，公司的电信网络就用不了：
本来显示的一切正常，但是只要一链接 https://www.google.com就会连接池0，提示尚未建立连接。

**Comment by GoForFree** [comment]
我遇到这种情况是之前全境封锁（差不多1个月前开始的）的时刻，最近刚刚解封？然后又来了

**Comment by jzp820927** [comment]
不会是你公司本身对网络的限制吧

**Comment by Antecer** [comment]
@jzp820927 我已经解决了，关闭自动调节线程，然后挂一会就行了。

**Comment by jzp820927** [comment]
那估计是你公司限制了网络连接数了
