### ISSUE TITLE
set Global PAC Proxy IE/Edge 无法正常使用代理

### ISSUE THREAD

**Issue by KevinSunJin** [XX-net/XX-Net#3065]
各位：
反馈一个问题，当我设置set Global PAC Proxy, IE和Edge无法正常使用代理，但是设置set Global GAEProxy Proxy 则一切正常。
以下是一些信息

![image](https://cloud.githubusercontent.com/assets/13011160/14809929/e008f1ec-0bc2-11e6-93d9-020c90e30e77.png)

XX-Net Status:

sys-platform: x86, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.19 Safari/537.36
xxnet-version: 3.0.4

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:3000 good:2993
network-status: OK
connected-link: new:7 used:49
scan-ip-thread-num: 50
ip-quality: 138
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by KevinSunJin** [comment]
补充一下，升级Windows后才出现的问题，Windows7时正常。

**Comment by KevinSunJin** [comment]
补充一下，升级Windows10后才出现的问题，Windows7时正常。

**Comment by UltraDWS** [comment]
用系统的浏览器你自己不需要指定代理，打开xxnet全局代理就能够直接上，你手动设置代理的同时还开了全局就会有冲突，手动设置代理只适合在取消全局代理的时候你又想用系统浏览器上网。开全局会直接覆盖windows的internet代理设置，你再手动设置就冲突。

**Comment by KevinSunJin** [comment]
@UltraDWS   并不是我手动设置的，而是当设置set Global PAC Proxy  时，IE和Edge会自动这样设置。

**Comment by KevinSunJin** [comment]
无语了，刚才把  use automatic configuration script  前面的勾去掉，试了下IE不行，然后又把勾勾上就好了。IE Edge都OK。
