### ISSUE TITLE
建议在可视化页面里添加手动修改proxy.pac文件的选项

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#3078]
这样就可以不必使用switchy omega等插件同时自己添加需要用gae代理的网址了。

**Comment by gurenn** [comment]
非常赞同，找了半天原来压根就还不能编辑啊~~不过，用文本文档打开PAC文件看语法不是很困难，应该能实现自定义添加。

**Comment by jzp820927** [comment]
这个可以有
