### ISSUE TITLE
upload fail: The read operation timed out

### ISSUE THREAD

**Issue by jackwei86** [XX-net/XX-Net#308]
May 01 22:59:33 - Retry 9 time...

May 01 22:59:34 - Application: hjq19861986
May 01 22:59:34 - Host: appengine.google.com
May 01 22:59:34 - Rolling back the update.
May 01 22:59:54 - upload fail: The read operation timed out

May 01 22:59:54 - Traceback (most recent call last):
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 218, in 
May 01 22:59:54 - May 01 22:59:54 - main()
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 215, in main
May 01 22:59:54 - May 01 22:59:54 - uploads(appids, email, password)
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 170, in uploads
May 01 22:59:54 - May 01 22:59:54 - if upload(appid, email, password):
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 125, in upload
May 01 22:59:54 - May 01 22:59:54 - my_stdout.write("Retry max time, failed.\n\n" % (i + 1))
May 01 22:59:54 - TypeErrorMay 01 22:59:54 - : May 01 22:59:54 - not all arguments converted during string formatting
May 01 22:59:33 - Retry 9 time...

May 01 22:59:34 - Application: hjq19861986
May 01 22:59:34 - Host: appengine.google.com
May 01 22:59:34 - Rolling back the update.
May 01 22:59:54 - upload fail: The read operation timed out

May 01 22:59:54 - Traceback (most recent call last):
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 218, in 
May 01 22:59:54 - May 01 22:59:54 - main()
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 215, in main
May 01 22:59:54 - May 01 22:59:54 - uploads(appids, email, password)
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 170, in uploads
May 01 22:59:54 - May 01 22:59:54 - if upload(appid, email, password):
May 01 22:59:54 - File "C:\Users\john\Desktop\XX-Net-1.10.1\XX-Net-1.10.1\goagent\3.1.49\server\uploader.py", line 125, in upload
May 01 22:59:54 - May 01 22:59:54 - my_stdout.write("Retry max time, failed.\n\n" % (i + 1))
May 01 22:59:54 - TypeErrorMay 01 22:59:54 - : May 01 22:59:54 - not all arguments converted during string formatting

------------------------------------------------------------------------------------------------------------------------------

GoAgent状态信息

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36
XX-Net Version	1.10.1
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	hjq12341234
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2925
connected link	0
ip-connect-interval	10

**Comment by xxnet** [comment]
新版已修复

2015-05-01 11:07 GMT-04:00 jackwei86 <notifications@github.com>:
