### ISSUE TITLE
以前给GA申请的appid可以直接部署XXnet吗

### ISSUE THREAD

**Issue by rafanir** [XX-net/XX-Net#3080]
以前用goa的时候申请过几个appid，现在也还可以用，请问如果直接在这些appid上部署xxnet会有什么影响吗？和申请新的appid专门部署xxnet有什么区别呢？谢谢！

**Comment by yeahwu** [comment]
没区别，直接用。
在配置项填入保存就好

**Comment by rafanir** [comment]
那GoA也能一起用么？

**Comment by blacklights** [comment]
以前GoAgent需要手动升级，这个不需要吗

**Comment by yeahwu** [comment]
APPID可以在goagent，xx-net，xx-mini，goproxy上通用，
xx-net可以自动升级

**Comment by rafanir** [comment]
好的，谢谢！
