### ISSUE TITLE
配置－升级管理－检查新版本 出现错误

### ISSUE THREAD

**Issue by lincf0912** [XX-net/XX-Net#3094]
Apr 28 15:23:25.171 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /Applications/XX-Net/data/downloads/README.md, retry:0
Apr 28 15:23:26.185 - [ERROR] handler:TypeError("'NoneType' object has no attribute '**getitem**'",) cmd:GET path:/update?cmd=get_new_version from:127.0.0.1:50284
Apr 28 15:23:26.186 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Applications/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 129, in handle_one_request
    self.do_GET()
  File "/Applications/XX-Net/launcher/web_control.py", line 156, in do_GET
    self.req_update_handler()
  File "/Applications/XX-Net/launcher/web_control.py", line 387, in req_update_handler
    data = '{"res":"success", "test_version":"%s", "stable_version":"%s", "current_version":"%s"}' % (github_versions[0][1], github_versions[1][1], current_version)
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by jzp820927** [comment]
XX什么版本

**Comment by lincf0912** [comment]
XX-Net-2.9.6

**Comment by jzp820927** [comment]
3.xx 以上版本才支持 更新

**Comment by lincf0912** [comment]
3.xx版本还没出吧？

以下是截图：

**Comment by jzp820927** [comment]
早就出了，目前最新是 3.0.4，去下面地址下载

https://github.com/XX-net/XX-Net/releases
