### ISSUE TITLE
感觉可以加一个 Issue 模板

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#3109]
@xxnet @yeahwu 
如下面这个：
https://github.com/PaperMC/Paper/tree/master/.github
https://github.com/PaperMC/Paper/issues/new

**Comment by xxnet** [comment]
​这个功能很好，以前还不知道有这种好东西。
客户端自动生成报告后，自动提交功能被我去掉了。太多没有说明的报告了。

我们先讨论模板怎么写。
- 先建议用户查找类似问题的讨论
- 查看wiki内容
- 提问时，描述自己做过哪些尝试和努力
  有条件先在另一台机器测试对比
- 贴上状态页
- 贴上GAE日志
- 尽量详细的描述问题出现的条件

**Comment by vSolo** [comment]
我这还有个可以参考的模板，最近一直忙没提交，@cat7373 心有灵犀啊
https://github.com/gorhill/uBlock/issues/new

**Comment by xxnet** [comment]
先建个模板，提个pull吧，以后慢慢改进
