### ISSUE TITLE
这几天用自己的appid,无法打开YouTube

### ISSUE THREAD

**Issue by Cococ** [XX-net/XX-Net#312]
# 以前是不会的, 这几天突然出现了，如下所示：
>
403. That’s an error.
Your client does not have permission to get URL /_gh/ from this server. That’s all we know.

好奇怪，有时候打得开，有时候打不开

# 这是我的xxnet状态图

![status](https://coding.net/u/tribleZero/p/Overview/git/raw/master/goadent-issues/QQ20150502-2%402x.png)

# 这是出现403的截图

![403](https://coding.net/u/tribleZero/p/Overview/git/raw/master/goadent-issues/QQ20150502-1%402x%20copy.png)

# 这是有时候打得开，但是存在https错误的截图

![https](https://coding.net/u/tribleZero/p/Overview/git/raw/master/goadent-issues/QQ20150502-1%402x.png)

**Comment by xxnet** [comment]
google 对ip进行了调整，以前gws的ip，现在却无法使用了。

新版做了处理了，识别到403错误，就把ip剔除掉。
