### ISSUE TITLE
证书不受信任？

### ISSUE THREAD

**Issue by Seikegn** [XX-net/XX-Net#313]
之前的1.8.4用不了了（总翻不出去），今天于是换成1.12.5。
解压之后，点开start.vbs，未出现管理员权限的要求。安装了XX-Net-1.12.5\data\php_proxy中的CA.crt。Chrome也安装了Switchsharp。
现在用搜狗浏览器打开google，FB，Youtube等网站，都会跳出安全提示；Chrome则显示不是私密链接。请问要怎么解决呢？
谢谢！

**Comment by evilstyle** [comment]
我也只同样的问题 我吧ca 证书已加入 受信任的网站了 还是没用 我去尝试下 GoAgent 吧

**Comment by nictse2013** [comment]
同楼主。。。。

**Comment by xxnet** [comment]
要安装data/goagent/CA.crt

chrome本来是支持自动导入证书的，不过要重启Chrome。

2015-05-04 3:08 GMT-04:00 nictse2013 <notifications@github.com>:

**Comment by xxnet** [comment]
新版加了重启浏览器的提示
