### ISSUE TITLE
切底的用不了了

### ISSUE THREAD

**Issue by boromeke** [XX-net/XX-Net#314]
create_ssl 216.58.209.16 fail:timed out cost:2002 h:0
May  2 15:55:07 - [DEBUG] network is ok
May  2 15:55:08 - [DEBUG] sort ip time:4
May  2 15:55:08 - [DEBUG] get ip:......... t:717
May  2 15:55:08 - [DEBUG] create_ssl update ip:....... time:611
127.0.0.1 - - [02/May/2015 15:55:14] code 400, message Bad request syntax ('\x05\x01\x00')
127.0.0.1 - - [02/May/2015 15:55:14] "" 400 -
127.0.0.1 - - [02/May/2015 15:55:14] code 400, message Bad request syntax ('\x05\x01\x00')
127.0.0.1 - - [02/May/2015 15:55:14] "" 400 -
127.0.0.1 - - [02/May/2015 15:55:19] code 400, message Bad request syntax ('\x05\x01\x00')
127.0.0.1 - - [02/May/2015 15:55:19] "" 400 -
127.0.0.1 - - [02/May/2015 15:55:19] code 400, message Bad request syntax ('\x04\x01\x01\xbb\xcb\xd04\x84\x00')
127.0.0.1 - - [02/May/2015 15:55:19] "???4?" 400 -
127.0.0.1 - - [02/May/2015 15:55:19] code 400, message Bad request syntax ('\x05\x01\x00')
127.0.0.1 - - [02/May/2015 15:55:19] "" 400 -
127.0.0.1 - - [02/May/2015 15:55:20] code 400, message Bad request syntax ('\x04\x01\x01\xbb@\xe9\xbd_\x00')
127.0.0.1 - - [02/May/2015 15:55:20] "?@?_" 400 -
127.0.0.1 - - [02/May/2015 15:55:22] code 400, message Bad request syntax ('\x05\x01\x00')
127.0.0.1 - - [02/May/2015 15:55:22] "" 400 -
127.0.0.1 - - [02/May/2015 15:55:22] code 400, message Bad request syntax ('\x04\x01\x01\xbb\xcb\xd04\x84\x00')
127.0.0.1 - - [02/May/2015 15:55:22] code 400, message Bad request syntax ('\x05\x01\x00')
127.0.0.1 - - [02/May/2015 15:55:22] "" 400 -
127.0.0.1 - - [02/May/2015 15:55:22] "???4?" 400 -
127.0.0.1 - - [02/May/2015 15:55:22] code 400, message Bad request syntax ('\x04\x01\x01\xbb\xcb\xd04\x84\x00')
127.0.0.1 - - [02/May/2015 15:55:22] "???4?" 400 -
127.0.0.1 - - [02/May/2015 15:55:24] code 400, message Bad request syntax ('\x04\x01\x01\xbbJ}\xccd\x00')
127.0.0.1 - - [02/May/2015 15:55:24] "?J}?d" 400 -
127.0.0.1 - - [02/May/2015 15:55:24] code 400, message Bad request syntax ('\x04\x01\x01\xbbJ}\xccd\x00')
127.0.0.1 - - [02/May/2015 15:55:24] "?J}?d" 400 -
127.0.0.1 - - [02/May/2015 15:55:32] code 400, message Bad request syntax ('\x04\x01\x01\xbb\xcb\xd04\x9e\x00')
127.0.0.1 - - [02/May/2015 15:55:32] "???4?" 400 -
127.0.0.1 - - [02/May/2015 15:55:34] code 400, message Bad request syntax ('\x04\x01\x01\xbbJ}\xccd\x00')
127.0.0.1 - - [02/May/2015 15:55:34] "?J}?d" 400 -
127.0.0.1 - - [02/May/2015 15:55:34] code 400, message Bad request syntax ('\x04\x01\x01\xbbJ}\xccd\x00')
127.0.0.1 - - [02/May/2015 15:55:34] "?J}?d" 400 -
127.0.0.1 - - [02/May/2015 15:55:34] code 400, message Bad request syntax ('\x04\x01\x01\xbbJ}\xccd\x00')
127.0.0.1 - - [02/May/2015 15:55:34] "?J}?d" 400 -

导入谷歌IP,也是用不了。

**Comment by jackguo007** [comment]
就是卡啊，我艹

**Comment by xxnet** [comment]
新版已经恢复正常
