### ISSUE TITLE
3.1.0版本在路由器使用无法打开WEB设置界面.如何修改127.0.0.1:8085为0.0.0.0:8085

### ISSUE THREAD

**Issue by sorsoso** [XX-net/XX-Net#3142]
简单点说就是我找不到如何修改配置文件的127.0.0.1:8085为0.0.0.0:8085 .貌似运行番茄的路由必须修改IP才行.求作者给指条路.....

**Comment by jzp820927** [comment]
改 data/launch/config.ini 文件，可以修改 8085 的监听地址

**Comment by sorsoso** [comment]
1.  3.1.0版本那文件并不在data/launch/config.ini 而是在data/gae_proxy/config.ini
2.  无所谓位置那文件也不能修改8085的监听,那里只能修改8086和8087.

**Comment by sorsoso** [comment]
我已解决,修改web_control.py内的
    if allow_remote:
        host_addr = "0.0.0.0"
    else:
        host_addr = "127.0.0.0"
为:
    if allow_remote:
        host_addr = "0.0.0.0"
    else:
        host_addr = "0.0.0.0"
就好了

**Comment by sorsoso** [comment]
找到问题,修改\data\launcher\config.yaml文件
修改
launcher: {allow_remote_connect: 0
为:
launcher: {allow_remote_connect: 1

xxnet默认不允许外网访问WEB设置界面,所以路由器上运行xxnet电脑端访问也算外网了.
此项修改就好了.
