### ISSUE TITLE
很难扫出ip了，有效ip一直在100个上下

### ISSUE THREAD

**Issue by Rongronggg9** [XX-net/XX-Net#3145]
-----------
问题描述：
ip库我已经稍微扩充过，但无论是否扩充都是100个上下，延迟高，已经扫了两天。
好像有可能是xx-net的问题，因为我用其他工具从相同的ip库里扫，都能扫出好多的。
比如这个[https://github.com/hlaspoor/Reclaim](https://github.com/hlaspoor/Reclaim)和这个[https://github.com/xyuanmu/checkiptools](https://github.com/xyuanmu/checkiptools)。1000ms以内的可以扫出几百个以上。

-----------
诊断信息：
sys-platform: AMD64, Windows-10-10.0.14295
os-system: Windows
os-version: 10.0.14295
os-release: 10
os-detail: Version:10-0; Build:14295; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.0.4

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:1524 good:113
network-status: OK
connected-link: new:6 used:22
scan-ip-thread-num: 100
ip-quality: 607
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jeremy0714** [comment]
3.10 我扫了有800多个，你换这个版本看看

**Comment by joinwuxiao** [comment]
3.1.0扫了快1000了

**Comment by jzp820927** [comment]
3.1.0 解决了好多问题，看试试

**Comment by Rongronggg9** [comment]
3.1.0解决问题了
