### ISSUE TITLE
数字对3.1很不友好啊，基本上每个操作都要弹窗

### ISSUE THREAD

**Issue by pingtouge** [XX-net/XX-Net#3148]

**Comment by jzp820927** [comment]
珍爱生命，远离国软

**Comment by xxnet** [comment]
​什么操作，比如呢？

是操作xx-net设置界面， 还是访问墙外网页？

**Comment by pingtouge** [comment]
@xxnet 操作页面设置开机之类的每次都要弹窗，还有一次访问维基弹窗，发起源是xx-net，操作对象是搜狗输入法，我点了之后xx-net和浏览器全部被光掉了
@jzp820927 我觉得也不至于，现在形势还不错，党国应该不会这么无孔不入

**Comment by xxnet** [comment]
​弹窗提示什么内容，截图发上来看看，注意隐私要加马赛克

**Comment by pingtouge** [comment]
按照顺序复制日志上来了，日志记录全部发生于同一秒，照你说的把有关可能隐私的文件名和路径用。。。代替
操作	说明	次数
[已阻止]	  修改 文档或图片文件	  防护 1 次
详细描述：
进程：F:\Program Files\sogoupinyin\。。。\userNetSchedule.exe
动作：删除
路径：C:\Users\Administrator\AppData\LocalLow\SogouPY.users\00000001\。。。.tmp.zip

操作	说明	次数
 [自动处理]	  结束进程	  防护 1 次
详细描述：
进程：D:\Documents\Downloads\XX-Net-3.1.0\code\default\python27\1.0\python.exe

操作	说明	次数
 [自动处理]	  结束进程	  防护 3 次
详细描述：
进程：C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

操作	说明	次数
[自动处理]	  结束进程	  防护 1 次
详细描述：
进程：F:\Program Files\sogoupinyin\。。。\SogouCloud.exe

操作	说明	次数
[自动处理]	  结束进程	  防护 1 次
详细描述：
进程：F:\Program Files\sogoupinyin\。。。\SGTool.exe

操作	说明	次数
[自动处理]	  结束进程	  防护 1 次
详细描述：
进程：F:\Program Files\sogoupinyin\。。。\userNetSchedule.exe

**Comment by nly4lov** [comment]
拜托不要用这么垃圾的软件来提问了。360算个神马东西？N年前就不用它也没中过毒

**Comment by pingtouge** [comment]
@nly4lov 人人都说数字垃圾，真知道它哪里垃圾的人有几个？你没中过毒不是我裸奔的理由，这题是我开的，你不认同数字可以选择不点进来。X大没说过不能开有关国软的题

**Comment by nly4lov** [comment]
360垃圾的地方多了：卡机，窃密，流氓（难以删除和清除）。我没中过毒不是你不用它的理由，随您大便吧。

**Comment by xxnet** [comment]
遇到了，​还是要研究的。
比较用了360之类的还是大多数。


老版本没有提醒吗？

日志里没有看到保护的理由。
这么多进程都被封了，不知道是触发什么规则。

**Comment by pingtouge** [comment]
老版本确实很少提醒，就连3.1.2都没有弹窗提醒，我从2.8.3开始用只有3.1.0有如此频繁和诡异的提醒

**Comment by xxnet** [comment]
​目前就你报告这个问题，再观察下

你可以先试试加入信任列表
