### ISSUE TITLE
Google搜索，提示：Message 连接超时，先休息一会再来！

### ISSUE THREAD

**Issue by liaoyaoheng** [XX-net/XX-Net#315]
Message
连接超时，先休息一会再来！

12.5，
广东电信

**Comment by Cat7373** [comment]
没找到可用IP吧
先试试用Gogo-Tester扫一些IP
导入到XX-Net临时凑活吧- -

**Comment by liaoyaoheng** [comment]
不时抽风，

嘛嘛～其实用xx就是懒扫ip，

祝越做越好，五一劳动快乐～

此邮件来自易信 - 点击下载，体验邮件随身提醒！


 在2015年5月2日 16:21:47, Cat73 <notifications@github.com> 写道：



没找到可用IP吧
先试试用Gogo-Tester扫一些IP
导入到XX-Net临时凑活吧- -

**Comment by latrikcoasler** [comment]
同意楼上观点，关键还是ip，提点建议，楼主不与集中力量研究怎样搜索ip？

**Comment by jackguo007** [comment]
我来了， 话说我是2手准备，SS+xx,哈哈，我依然坚挺着

**Comment by boromeke** [comment]
我倒入了IP也是一样完全连接不了。广州电信这边可能墙得特别厉害。

**Comment by xxnet** [comment]
恩，接下来会完善扫描ip的功能。

虽然内置扫描ip，但是一直没有暴露操作界面。
考虑到大家会不断去寻找新的ip段，所以后面会让用户自己去选择扫描什么ip范围、扫描线程、扫描日志等等。

在 2015年5月2日 下午7:47，boromeke <notifications@github.com>写道：

**Comment by xxnet** [comment]
1.14.x已经把扫描的控制权给用户了， UI上直接操作

**Comment by andnot** [comment]
问题是，google搜索、Gmail都没问题，唯独google scholar的导出BiBTeX有问题……

**Comment by jzp820927** [comment]
具体什么问题？

**Comment by andnot** [comment]
@jzp820927 就是在使用google和Gmail时都正常，google scholar搜索也正常，但是在使用导出引用文献的功能时（如「BibTeX」），就会报错「连接超时，先休息一会再来！」

我之前发现，点击「引用」后再点击「BibTeX」后，打开的页面地址是`.googleusercontent.com`，于是就在 manual.ini 中添加了直接连接的设置（如果不这么设置，则会显示IP请求过多的报错）。
刚设置时，还正常，后来就开始出现连接超时的错误了。

示例页面：
[https://scholar.google.com/scholar?q=Computing+sparse+representations+of+multidimensional+signals+using+kronecker+bases&hl=zh-CN&as_sdt=0,5](url)

**Comment by jzp820927** [comment]
F12 看看，是不是还有某些域名，没有直连？

**Comment by andnot** [comment]
@jzp820927 这个不懂啊...按了F12后, 控制板的那一项可以表明正在连接的网址呢?

**Comment by jzp820927** [comment]
network

**Comment by andnot** [comment]
@jzp820927 刚刚试了下，出来的都是一堆.js，貌似没看到有网址链接之类的内容……

<img width="960" alt="screenclip" src="https://cloud.githubusercontent.com/assets/6057231/18770535/c88e6e6c-8169-11e6-9438-f479f7db10f7.png">

**Comment by jzp820927** [comment]
或者把日志贴出来看看吧

**Comment by andnot** [comment]
文末是全部日志，其中跟google scholar有关的项有这些：

Sep 23 23:03:03.272 - [INFO] GAE CONNECT scholar.googleusercontent.com:443
Sep 23 23:03:03.291 - [DEBUG] GAE CONNECT Direct GET https://scholar.googleusercontent.com/scholar.bib?q=info:wTRjgcs6WIYJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAV-

以及：
Sep 23 23:03:05.848 - [WARNING] IP:110.163.42.173 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403

全部日志：
> 
Sep 23 23:03:03.272 - [INFO] GAE CONNECT scholar.googleusercontent.com:443
Sep 23 23:03:03.291 - [DEBUG] GAE CONNECT Direct GET https://scholar.googleusercontent.com/scholar.bib?q=info:wTRjgcs6WIYJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAV-U2vkd6yoCUC4mn_I2T53KIrlKPn2U3&scisf=4&ct=citation&cd=0&hl=zh-CN
Sep 23 23:03:03.298 - [DEBUG] get ip:191.253.208.26 t:839
Sep 23 23:03:03.794 - [DEBUG] get ip:63.88.73.180 t:1039
Sep 23 23:03:04.215 - [INFO] PAC from:127.0.0.1:14292 GET /proxy.pac
Sep 23 23:03:04.294 - [DEBUG] get ip:110.163.42.173 t:1039
Sep 23 23:03:04.575 - [DEBUG] create_ssl update ip:110.163.42.173 time:171 h2:0
Sep 23 23:03:04.576 - [DEBUG] create_ssl update ip:63.88.73.180 time:526 h2:1
Sep 23 23:03:04.796 - [DEBUG] get ip:209.85.202.153 t:1039
Sep 23 23:03:05.297 - [DEBUG] get ip:194.182.232.87 t:1052
Sep 23 23:03:05.576 - [DEBUG] get ip:213.105.64.245 t:1053
Sep 23 23:03:05.578 - [DEBUG] get ip:213.105.64.209 t:1059
Sep 23 23:03:05.799 - [DEBUG] get ip:59.18.35.223 t:1066
Sep 23 23:03:05.848 - [WARNING] IP:110.163.42.173 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403
Sep 23 23:03:05.849 - [DEBUG] report_connect_fail:110.163.42.173
Sep 23 23:03:06.003 - [DEBUG] ssl_closed 61.238.239.211
Sep 23 23:03:06.003 - [DEBUG] 61.238.239.211 worker close:idle timeout
Sep 23 23:03:06.135 - [DEBUG] create_ssl update ip:194.182.232.87 time:569 h2:0
Sep 23 23:03:06.266 - [DEBUG] create_ssl update ip:59.18.35.223 time:313 h2:0
Sep 23 23:03:06.389 - [DEBUG] create_ssl update ip:213.105.64.245 time:542 h2:0
Sep 23 23:03:06.436 - [DEBUG] create_ssl update ip:213.105.64.209 time:549 h2:0
Sep 23 23:03:06.439 - [DEBUG] ssl_closed 61.238.239.238
Sep 23 23:03:06.440 - [DEBUG] 61.238.239.238 worker close:idle timeout
Sep 23 23:03:07.107 - [DEBUG] create_ssl update ip:209.85.202.153 time:2004 h2:1
Sep 23 23:03:07.107 - [INFO] DIRECT t:24346 s:0 200 0.client-channel.google.com /client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20160919.11_p1&gsessionid=-b6bBMYfcAbuOX-esRsbrn5o34lpNoBu&VER=8&RID=rpc&SID=FEC3231DF42C5621&CI=1&AID=191&TYPE=xmlhttp&zx=ffwt1vpfjris&t=1
Sep 23 23:03:07.301 - [DEBUG] 191.253.208.26 fail:timeout('timed out',)
Sep 23 23:03:07.301 - [DEBUG] report_connect_fail:191.253.208.26
Sep 23 23:03:07.732 - [INFO] GAE CONNECT 0.client-channel.google.com:443
Sep 23 23:03:07.772 - [DEBUG] GAE CONNECT Direct GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20160919.11_p1&gsessionid=-b6bBMYfcAbuOX-esRsbrn5o34lpNoBu&VER=8&RID=rpc&SID=FEC3231DF42C5621&CI=1&AID=191&TYPE=xmlhttp&zx=1fxopeoy3h5t&t=2
Sep 23 23:03:07.773 - [DEBUG] host_conn_pool 0.client-channel.google.com get:202.224.62.13 handshake:180
Sep 23 23:03:08.263 - [WARNING] IP:194.182.232.87 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403
Sep 23 23:03:08.263 - [DEBUG] report_connect_fail:194.182.232.87
Sep 23 23:03:08.453 - [INFO] GAE CONNECT www.google.com:443
Sep 23 23:03:08.471 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=IB-2yis1POhTST6LK64VzQ&cp=0&gs_id=35g&q=&xhr=t
Sep 23 23:03:08.471 - [DEBUG] host_conn_pool www.google.com get:59.18.35.160 handshake:338
Sep 23 23:03:08.477 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 23:03:08.493 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=bGm4BE6qv2zYG/iPiey2cw%3D%3D
Sep 23 23:03:08.790 - [INFO] direct_handler.handler send response fail. t:0 e:error(10053, '') www.google.com/complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=IB-2yis1POhTST6LK64VzQ&cp=0&gs_id=35g&q=&xhr=t
Sep 23 23:03:08.791 - [INFO] DIRECT chucked t:319 s:0 200 www.google.com /complete/search?client=hp&hl=zh-CN&gs_rn=64&gs_ri=hp&tok=IB-2yis1POhTST6LK64VzQ&cp=0&gs_id=35g&q=&xhr=t
Sep 23 23:03:09.134 - [INFO] DIRECT chucked t:641 s:2093 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=bGm4BE6qv2zYG/iPiey2cw%3D%3D
Sep 23 23:03:09.143 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 23:03:09.176 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=bGm4BE6qv2zYG/iPiey2cw%3D%3D
Sep 23 23:03:09.176 - [DEBUG] host_conn_pool clients4.google.com get:213.105.64.245 handshake:542
Sep 23 23:03:09.428 - [INFO] PAC from:127.0.0.1:14306 GET /proxy.pac
Sep 23 23:03:09.588 - [INFO] DIRECT chucked t:411 s:370 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=bGm4BE6qv2zYG/iPiey2cw%3D%3D
Sep 23 23:03:10.283 - [WARNING] IP:59.18.35.223 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403
Sep 23 23:03:10.283 - [DEBUG] report_connect_fail:59.18.35.223
Sep 23 23:03:10.284 - [DEBUG] get ip:61.238.239.238 t:99
Sep 23 23:03:10.444 - [DEBUG] create_ssl update ip:61.238.239.238 time:115 h2:0
Sep 23 23:03:11.776 - [INFO] DIRECT chucked t:4003 s:398 200 0.client-channel.google.com /client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20160919.11_p1&gsessionid=-b6bBMYfcAbuOX-esRsbrn5o34lpNoBu&VER=8&RID=rpc&SID=FEC3231DF42C5621&CI=1&AID=191&TYPE=xmlhttp&zx=1fxopeoy3h5t&t=2
Sep 23 23:03:12.165 - [WARNING] IP:213.105.64.209 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403
Sep 23 23:03:12.166 - [DEBUG] report_connect_fail:213.105.64.209
Sep 23 23:03:12.727 - [INFO] GAE CONNECT 0.client-channel.google.com:443
Sep 23 23:03:12.755 - [DEBUG] GAE CONNECT Direct GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20160919.11_p1&gsessionid=-b6bBMYfcAbuOX-esRsbrn5o34lpNoBu&VER=8&RID=rpc&SID=FEC3231DF42C5621&CI=1&AID=191&TYPE=xmlhttp&zx=90j9an152wgc&t=1
Sep 23 23:03:12.755 - [DEBUG] host_conn_pool 0.client-channel.google.com get:202.224.62.13 handshake:180
Sep 23 23:03:12.757 - [DEBUG] get ip:61.238.239.211 t:111
Sep 23 23:03:12.914 - [DEBUG] create_ssl update ip:61.238.239.211 time:111 h2:0
Sep 23 23:03:14.177 - [WARNING] IP:61.238.239.238 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403
Sep 23 23:03:14.177 - [DEBUG] report_connect_fail:61.238.239.238
Sep 23 23:03:14.227 - [DEBUG] sort ip time:42ms
Sep 23 23:03:14.227 - [DEBUG] get ip:212.1.250.177 t:1075
Sep 23 23:03:14.321 - [DEBUG] GAEProxy web_control 127.0.0.1:14315 POST /config?cmd=get_config
Sep 23 23:03:14.322 - [DEBUG] GAEProxy Web_control 127.0.0.1:14315 GET /scan_ip?cmd=get_range
Sep 23 23:03:14.322 - [INFO] load ip range file:D:\Software\Network\XX-Net-3.1.14\code\3.2.5\gae_proxy\local\ip_range.txt
Sep 23 23:03:14.686 - [DEBUG] get ip:216.58.204.141 t:1089
Sep 23 23:03:15.125 - [DEBUG] create_ssl update ip:212.1.250.177 time:601 h2:1
Sep 23 23:03:15.187 - [DEBUG] get ip:222.165.163.89 t:1105
Sep 23 23:03:15.686 - [DEBUG] create_ssl update ip:216.58.204.141 time:671 h2:1
Sep 23 23:03:15.688 - [DEBUG] get ip:92.246.12.232 t:1108

**Comment by jzp820927** [comment]
Sep 23 23:03:05.848 - [WARNING] IP:110.163.42.173 host:scholar.googleusercontent.com not support GAE, server type:scholar status:403

看这个日志，应该是 IP 不支持。

**Comment by andnot** [comment]
呃，这就不知道了……
有时候可以正常打开，有时候就不行，也不知问题出在哪里。

**Comment by jzp820927** [comment]
那应该是 IP ，问题，这个问题不好处理。只能自己筛选下 IP 了

**Comment by andnot** [comment]
噢, 明白了, 多谢!
