### ISSUE TITLE
mac用3.1.0自动代理除google、YouTube、wikipedia等少数几个网，其它需代理的网页都不能上

### ISSUE THREAD

**Issue by fyrfox** [XX-net/XX-Net#3150]
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17
xxnet-version: 3.1.0

python-version: 2.7.10
openssl-version: 0.13.1 TLSv1 h2:no

ipv6-status: 0
gws-ip-num: total:171 good:153
network-status: OK
connected-link: new:0 used:0
worker: h1:30 h2:0
scan-ip-thread-num: 500
ip-quality: 346
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by fyrfox** [comment]
这个问题困扰了好久，除了用老版本自动升级到2.9.2的没有任何问题，到2.9.4以后版本，都是这个问题：自动代理下除google、YouTube、wikipedia等少数几个网，其它需代理的网页，如BBC中文、纽约时报等都不能上；全局代理下依然可上google、YouTube、wikipedia，其它的，包括国内网站百度等，输入地址后都没反应，日志文件里也没有记录。

**Comment by jzp820927** [comment]
全局都不行？这个有点不科学啊，是什么浏览器？

**Comment by xxnet** [comment]
自动代理是pac 的问题

**Comment by fyrfox** [comment]
浏览器是Safari/601.5.17。用2.9.2就没问题，全局、自动都可以，那个2.9.2是最早从2.6.x自动一点点升级上来的，后来自动升级停止就没升了，一直保留着那个版本，后来下了2.9.4直到3.1.0 怎么都出我说的问题，用新版本文件覆盖老版本，也不行，的确不科学！
这里有没有也用MAC的，碰到我相同的问题？

**Comment by fyrfox** [comment]
自动代理是PAC问题，那全局代理也是不能上啊，关键是日志里还没记录，地址栏进度条卡那里也不动。

**Comment by jzp820927** [comment]
之前也有人反映过，说是 MAC 系统，Safari 浏览器，部分网站不能访问，但是换成 chrome 就一起正常，不如你用 chrome 试试

**Comment by fyrfox** [comment]
chrome依然不行的 早试过了。。。

**Comment by jzp820927** [comment]
那你这个问题有不知道是什么导致的了，有点奇葩，等X大来处理吧

**Comment by xxnet** [comment]
切换为全局模式，​访问个无法连接的网站，然后把GAE日志发出来

**Comment by fyrfox** [comment]
问题找到了，是DNS原因，原来我用的是202.99.160.68，换别的诸如114.114.114.114即可代理过去，在换回来，也能正常代理，但只要是新地址，原202.99.160.68就不可解析出去，非要用别动DNS解析一下才可以，这个情况我自己试着重现了好几次。xx-net挑DNS地址？具体原理不明，有大神能分析一下么？

**Comment by jzp820927** [comment]
你这个 DNS 我试过来，解析不出IP，应该是 DNS 有问题。

C:\Users\Administrator>nslookup www.baidu.com 202.99.160.68
服务器:  UnKnown
Address:  202.99.160.68

*** UnKnown 找不到 www.baidu.com: Query refused

C:\Users\Administrator>nslookup www.qq.com 202.99.160.68
服务器:  UnKnown
Address:  202.99.160.68

DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时
