### ISSUE TITLE
能不能添加个隐藏托盘按钮的功能?

### ISSUE THREAD

**Issue by comup-x** [XX-net/XX-Net#317]
右下角空间有限啊。。。。

**Comment by Cat7373** [comment]
。。。
隐藏了托盘图标，那要怎么去控制。。。

**Comment by comup-x** [comment]
不是有127.0.0.1：8085么

添加个可以隐藏的功能不一定直接就隐藏了啊

右下角有限啊我又不喜欢隐藏不常用图标那个功能

**Comment by Cat7373** [comment]
感觉用处不会太大- -
不大愿意做- -
你可以试试自己改下代码- -

**Comment by xxnet** [comment]
请参考这里：
https://github.com/XX-net/XX-Net/wiki/How--to-hide-XX-Net-windows-tray

在 2015年5月3日 上午8:20，Cat73 <notifications@github.com>写道：

**Comment by Pd69bq** [comment]
万能的ps -ef 和sudo kill 可以实现在mac和linux下的停止 windows下只要goagent不是visable=0也可以关闭窗口实现停止 但是 xx的监控也没有时还是挺好用的 直接访问8085 是个不错的方法 选择是否可见图标有时比功能本身更能改善用户的体验
