### ISSUE TITLE
pythonw.exe有时候吃内存很严重

### ISSUE THREAD

**Issue by PaulUlrik** [XX-net/XX-Net#318]
最近碰到好几次这样的情况了，发现内存占用超多，打开管理器发现是pythonw.exe这个程序，占用了1G多的内存，请作者看看什么情况额。。
状态信息：
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:10-0; Build:9926; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	en_US
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
XX-Net Version	1.12.3
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	  XXXXXXXXXXXXX
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2996
connected link	11,11
ip-connect-interval	10
block stat(帮助)	OK

日志：
May 02 21:14:12 - [DEBUG] get ip:216.58.221.173 t:1213
May 02 21:14:12 - [DEBUG] direct_create_ssl 64.15.114.55 fail:timed out cost:2000 h:0
May 02 21:14:12 - [DEBUG] create_ssl 64.15.116.54 fail:timed out cost:2000 h:0
May 02 21:14:12 - [DEBUG] network is fail
May 02 21:14:12 - [DEBUG]LOG_EXCEPT: report_connect_fail network fail, Except:[Errno 9] Bad file descriptor
May 02 21:14:12 - [DEBUG] network is ok
May 02 21:14:12 - [DEBUG] create_ssl 64.15.116.27 fail:timed out cost:2002 h:0
May 02 21:14:12 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:12 - [DEBUG] create_ssl 216.58.209.169 fail:timed out cost:2001 h:0
May 02 21:14:12 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:13 - [DEBUG] direct_create_ssl 216.58.217.177 fail:timed out cost:2002 h:0
May 02 21:14:13 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:13 - [DEBUG] direct_create_ssl 173.194.196.17 fail:timed out cost:2000 h:0
May 02 21:14:13 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:13 - [DEBUG] get ip:64.233.162.83 t:751
May 02 21:14:13 - [DEBUG] get ip:64.233.162.86 t:796
May 02 21:14:13 - [DEBUG] create_ssl 216.58.221.144 fail:timed out cost:2000 h:0
May 02 21:14:13 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:13 - [DEBUG] get ip:64.233.162.87 t:831
May 02 21:14:13 - [DEBUG] get ip:208.117.253.88 t:1211
May 02 21:14:14 - [DEBUG] get ip:208.117.224.25 t:1211
May 02 21:14:14 - [DEBUG] get ip:212.188.7.216 t:1212
May 02 21:14:14 - [DEBUG] direct_create_ssl 208.117.227.50 fail:timed out cost:2000 h:0
May 02 21:14:14 - [DEBUG] create_ssl 64.15.116.152 fail:timed out cost:2000 h:0
May 02 21:14:14 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:14 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:14 - [DEBUG] direct_create_ssl 64.15.116.23 fail:timed out cost:2000 h:0
May 02 21:14:14 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:14 - [DEBUG] create_ssl 64.233.161.132 fail:timed out cost:2000 h:0
May 02 21:14:14 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:14 - [DEBUG] direct_create_ssl 216.58.221.173 fail:timed out cost:2000 h:0
May 02 21:14:14 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:14 - [DEBUG] get ip:208.117.228.118 t:1212
May 02 21:14:14 - [DEBUG] create_ssl update ip:64.233.162.83 time:814
May 02 21:14:14 - [DEBUG] direct create_ssl update ip:64.233.162.86 time:786
May 02 21:14:14 - [DEBUG] create_ssl update ip:64.233.162.87 time:804
May 02 21:14:15 - [DEBUG] create_ssl 208.117.253.88 fail:timed out cost:2000 h:0
May 02 21:14:15 - [DEBUG] network is ok
May 02 21:14:16 - [DEBUG] direct_create_ssl 208.117.224.25 fail:timed out cost:2000 h:0
May 02 21:14:16 - [DEBUG] direct_create_ssl 212.188.7.216 fail:timed out cost:2000 h:0
May 02 21:14:16 - [DEBUG] network is fail
May 02 21:14:16 - [DEBUG] report_connect_fail network fail
May 02 21:14:16 - [DEBUG] network is ok
May 02 21:14:16 - [DEBUG] create_ssl 208.117.228.118 fail:timed out cost:2000 h:0
May 02 21:14:16 - [DEBUG] report_connect_fail network fail recently
May 02 21:14:32 - [INFO] GAE CONNECT www.google-analytics.com:443 
May 02 21:14:32 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
May 02 21:14:32 - [DEBUG] host_conn_pool www.google-analytics.com get:64.233.162.83 handshake:651
May 02 21:14:32 - [INFO] GAE CONNECT www.google-analytics.com:443 
May 02 21:14:32 - [DEBUG] GAE CONNECT GET https://www.google-analytics.com/r/collect?v=1&_v=j30&a=436132490&t=pageview&_s=1&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues&dr=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&ul=en-us&de=UTF-8&dt=Issues%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1366x768&vp=1364x705&je=1&fl=17.0%20r0&_u=eACAAAQBM~&jid=1676229854&cid=1859005643.1428246918&tid=UA-3769691-2&_r=1&cd1=Logged%20In&cd2=Header%20v3&z=1293727755
May 02 21:14:32 - [DEBUG] host_conn_pool www.google-analytics.com get:64.233.162.84 handshake:763
May 02 21:14:32 - [INFO] GAE CONNECT www.google-analytics.com:443 
May 02 21:14:32 - [DEBUG]LOG_EXCEPT: GAE CONNECT GET https://www.google-analytics.com/collect?v=1&_v=j30&a=436132490&t=event&_s=3&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues&dr=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&ul=en-us&de=UTF-8&dt=Issues%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1366x768&vp=1364x705&je=1&fl=17.0%20r0&ec=Support&ea=view&el=no_last_repo&_u=eACAAAQFM~&jid=&cid=1859005643.1428246918&tid=UA-3769691-2&cd1=Logged%20In&cd2=Header%20v3&z=258354035, Except:[Errno 9] Bad file descriptor
May 02 21:14:32 - [DEBUG] host_conn_pool www.google-analytics.com get:64.233.162.87 handshake:763
May 02 21:14:32 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:14:32 - [INFO] DIRECT t:315 s:35 200 www.google-analytics.com /collect
May 02 21:14:32 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:14:32 - [DEBUG] ssl_pool.get:64.233.162.83 handshake:651
May 02 21:14:32 - [DEBUG] ssl conn_num:8
May 02 21:14:33 - [DEBUG] sort ip time:16
May 02 21:14:33 - [DEBUG] get ip:64.233.162.86 t:786
May 02 21:14:33 - [INFO] DIRECT t:394 s:35 200 www.google-analytics.com /r/collect?v=1&_v=j30&a=436132490&t=pageview&_s=1&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues&dr=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&ul=en-us&de=UTF-8&dt=Issues%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1366x768&vp=1364x705&je=1&fl=17.0%20r0&_u=eACAAAQBM~&jid=1676229854&cid=1859005643.1428246918&tid=UA-3769691-2&_r=1&cd1=Logged%20In&cd2=Header%20v3&z=1293727755
May 02 21:14:33 - [INFO] DIRECT t:368 s:35 200 www.google-analytics.com /collect?v=1&_v=j30&a=436132490&t=event&_s=3&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues&dr=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&ul=en-us&de=UTF-8&dt=Issues%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1366x768&vp=1364x705&je=1&fl=17.0%20r0&ec=Support&ea=view&el=no_last_repo&_u=eACAAAQFM~&jid=&cid=1859005643.1428246918&tid=UA-3769691-2&cd1=Logged%20In&cd2=Header%20v3&z=258354035
May 02 21:14:33 - [INFO] DIRECT t:1072282 s:49049680 200 dl.google.com /tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B5DAAC142-3020-A2EB-5037-AE74C3E9141C%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable%26installdataindex%3Ddefaultbrowser/update2/installers/ChromeStandaloneSetup64.exe
May 02 21:14:34 - [DEBUG] create_ssl update ip:64.233.162.86 time:800
May 02 21:14:42 - [INFO] GAE CONNECT collector.githubapp.com:443 
May 02 21:14:42 - [DEBUG] GAE CONNECT GET https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2Fnew&dimensions[title]=Issues%20%C2%B7%20XX-net%2FXX-Net&dimensions[referrer]=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F42.0.2311.90%20Safari%2F537.36&dimensions[screen_resolution]=1366x768&dimensions[pixel_ratio]=1&dimensions[browser_resolution]=1364x705&dimensions[tz_seconds]=28800&dimensions[timestamp]=1430572481860&dimensions[request_id]=7396D190%3A02C7%3A300640A%3A5544CDC8&dimensions[user_id]=10395542&dimensions[user_login]=XX-net&dimensions[repository_id]=29290473&dimensions[repository_nwo]=XX-net%2FXX-Net&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=29290473&dimensions[repository_network_root_nwo]=XX-net%2FXX-Net&&measures[performance_timing]=1-1439-1439--5417-5325-5301-2220-1439-1439-1439---0---1502-2563-2218---&&dimensions[actor_id]=11812477&dimensions[actor_login]=PaulUlrik&dimensions[actor_hash]=af64f4029ad74cc29e0c4659b96986bbc92a6d27065cacb2c4a8bdf54916dea1&dimensions[cid]=224628290.1428246921
May 02 21:14:42 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:763
May 02 21:14:42 - [DEBUG] ssl conn_num:11
May 02 21:14:43 - [INFO] GAE CONNECT collector.githubapp.com:443 
May 02 21:14:43 - [INFO]LOG_EXCEPT: GAE t:896 s:35 200 https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2Fnew&dimensions[title]=Issues%20%C2%B7%20XX-net%2FXX-Net&dimensions[referrer]=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F42.0.2311.90%20Safari%2F537.36&dimensions[screen_resolution]=1366x768&dimensions[pixel_ratio]=1&dimensions[browser_resolution]=1364x705&dimensions[tz_seconds]=28800&dimensions[timestamp]=1430572481860&dimensions[request_id]=7396D190%3A02C7%3A300640A%3A5544CDC8&dimensions[user_id]=10395542&dimensions[user_login]=XX-net&dimensions[repository_id]=29290473&dimensions[repository_nwo]=XX-net%2FXX-Net&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=29290473&dimensions[repository_network_root_nwo]=XX-net%2FXX-Net&&measures[performance_timing]=1-1439-1439--5417-5325-5301-2220-1439-1439-1439---0---1502-2563-2218---&&dimensions[actor_id]=11812477&dimensions[actor_login]=PaulUlrik&dimensions[actor_hash]=af64f4029ad74cc29e0c4659b96986bbc92a6d27065cacb2c4a8bdf54916dea1&dimensions[cid]=224628290.1428246921, Except:[Errno 9] Bad file descriptor
May 02 21:14:43 - [DEBUG] GAE CONNECT GET https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2Fnew&dimensions[title]=New%20Issue%20%C2%B7%20XX-net%2FXX-Net&dimensions[referrer]=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F42.0.2311.90%20Safari%2F537.36&dimensions[screen_resolution]=1366x768&dimensions[pixel_ratio]=1&dimensions[browser_resolution]=1364x705&dimensions[tz_seconds]=28800&dimensions[timestamp]=1430572482812&dimensions[request_id]=7396D190%3A02C7%3A300640A%3A5544CDC8&dimensions[user_id]=10395542&dimensions[user_login]=XX-net&dimensions[repository_id]=29290473&dimensions[repository_nwo]=XX-net%2FXX-Net&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=29290473&dimensions[repository_network_root_nwo]=XX-net%2FXX-Net&&&dimensions[actor_id]=11812477&dimensions[actor_login]=PaulUlrik&dimensions[actor_hash]=af64f4029ad74cc29e0c4659b96986bbc92a6d27065cacb2c4a8bdf54916dea1&dimensions[cid]=224628290.1428246921
May 02 21:14:43 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:763
May 02 21:14:43 - [DEBUG] ssl conn_num:11
May 02 21:14:43 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:14:43 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:14:43 - [DEBUG] ssl_pool.get:64.233.162.87 handshake:763
May 02 21:14:43 - [DEBUG] ssl conn_num:10
May 02 21:14:43 - [INFO] GAE CONNECT www.google-analytics.com:443 
May 02 21:14:43 - [INFO] GAE CONNECT www.google-analytics.com:443 
May 02 21:14:43 - [INFO] GAE t:669 s:35 200 https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2Fnew&dimensions[title]=New%20Issue%20%C2%B7%20XX-net%2FXX-Net&dimensions[referrer]=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&dimensions[user_agent]=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F42.0.2311.90%20Safari%2F537.36&dimensions[screen_resolution]=1366x768&dimensions[pixel_ratio]=1&dimensions[browser_resolution]=1364x705&dimensions[tz_seconds]=28800&dimensions[timestamp]=1430572482812&dimensions[request_id]=7396D190%3A02C7%3A300640A%3A5544CDC8&dimensions[user_id]=10395542&dimensions[user_login]=XX-net&dimensions[repository_id]=29290473&dimensions[repository_nwo]=XX-net%2FXX-Net&dimensions[repository_public]=true&dimensions[repository_is_fork]=false&dimensions[repository_network_root_id]=29290473&dimensions[repository_network_root_nwo]=XX-net%2FXX-Net&&&dimensions[actor_id]=11812477&dimensions[actor_login]=PaulUlrik&dimensions[actor_hash]=af64f4029ad74cc29e0c4659b96986bbc92a6d27065cacb2c4a8bdf54916dea1&dimensions[cid]=224628290.1428246921
May 02 21:14:43 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
May 02 21:14:43 - [DEBUG] host_conn_pool www.google-analytics.com get:64.233.162.84 handshake:763
May 02 21:14:43 - [DEBUG] GAE CONNECT GET https://www.google-analytics.com/collect?v=1&_v=j30&a=436132490&t=pageview&_s=4&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2Fnew&dr=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&ul=en-us&de=UTF-8&dt=New%20Issue%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1366x768&vp=1364x705&je=1&fl=17.0%20r0&_u=eACAAAQFM~&jid=&cid=1859005643.1428246918&tid=UA-3769691-2&cd1=Logged%20In&cd2=Header%20v3&z=9097601
May 02 21:14:43 - [DEBUG] host_conn_pool www.google-analytics.com get:64.233.162.86 handshake:779
May 02 21:14:44 - [DEBUG] sort ip time:19
May 02 21:14:44 - [DEBUG] get ip:64.233.162.86 t:800
May 02 21:14:44 - [INFO]LOG_EXCEPT: DIRECT t:365 s:35 200 www.google-analytics.com /collect?v=1&_v=j30&a=436132490&t=pageview&_s=4&dl=https%3A%2F%2Fgithub.com%2FXX-net%2FXX-Net%2Fissues%2Fnew&dr=http%3A%2F%2F127.0.0.1%3A8085%2F%3Fmodule%3Dgoagent%26menu%3Dstatus&ul=en-us&de=UTF-8&dt=New%20Issue%20%C2%B7%20XX-net%2FXX-Net&sd=24-bit&sr=1366x768&vp=1364x705&je=1&fl=17.0%20r0&_u=eACAAAQFM~&jid=&cid=1859005643.1428246918&tid=UA-3769691-2&cd1=Logged%20In&cd2=Header%20v3&z=9097601, Except:[Errno 9] Bad file descriptor
May 02 21:14:44 - [INFO] DIRECT t:372 s:35 200 www.google-analytics.com /collect
May 02 21:14:44 - [INFO] GAE t:677 s:0 200 https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:14:45 - [DEBUG] create_ssl update ip:64.233.162.86 time:723
May 02 21:14:53 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:14:53 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:14:53 - [DEBUG] ssl_pool.get:64.233.162.86 handshake:723
May 02 21:14:53 - [DEBUG] ssl conn_num:12
May 02 21:14:54 - [INFO] GAE t:641 s:0 200 https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:14:59 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:14:59 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:14:59 - [DEBUG] ssl_pool.get:64.233.162.86 handshake:723
May 02 21:14:59 - [DEBUG] ssl conn_num:12
May 02 21:15:11 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:15:11 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:15:11 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:763
May 02 21:15:11 - [DEBUG] ssl conn_num:11
May 02 21:15:12 - [INFO] GAE t:660 s:0 200 https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:15:19 - [WARNING] gae_handler err:error(10053, 'An established connection was aborted by the software in your host machine') https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d 
May 02 21:15:32 - [WARNING] gae_handler err:error(10053, 'An established connection was aborted by the software in your host machine') https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d 
May 02 21:15:32 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:15:32 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:15:32 - [DEBUG] ssl_pool.get:64.233.162.84 handshake:763
May 02 21:15:32 - [DEBUG] ssl conn_num:11
May 02 21:16:04 - [INFO] GAE CONNECT live.github.com:443 
May 02 21:16:04 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:16:04 - [DEBUG] ssl_pool.get:64.233.162.87 handshake:763
May 02 21:16:04 - [DEBUG] ssl conn_num:10
May 02 21:16:05 - [INFO] GAE t:594 s:0 200 https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d
May 02 21:16:32 - [WARNING]LOG_EXCEPT: gae_handler err:error(10053, 'An established connection was aborted by the software in your host machine') https://live.github.com/_sockets/MTE4MTI0Nzc6ZjUxODM2MDBhOGU4ZjBiZTViYTNkY2U3OTE5NWVjYmI6Y2UwYzdjYTg2Mjk0YjllYjRjMzY4NzczNDI1YjAwMDM3NTM4YzU2NzA2ZmUwNzY4YjEyZmYwMTcxN2U1N2I1Yw==--8e0c35882495c8456928a6af88819c550f93716d , Except:[Errno 9] Bad file descriptor

**Comment by Cat7373** [comment]
不至于吧。。
我就没见过大于20mb的时候
真的是1gb的话那大概是有内存泄漏
能不能再详细描述下出现问题之前你都做过什么？

**Comment by PaulUlrik** [comment]
我也不知道为什么啊。我记得的就是有一次是在看搜狐美剧，发现很卡然后发现是这个在吃内存。然后刚才就是在chrome官网下载最新版离线安装包。都是比较正常的使用啊。

**Comment by Cat7373** [comment]
表示开一整天，内存开销依旧在正常值，看起来你应该是因为哪里的内存泄露导致的问题了- -
这种问题最难查- -

**Comment by PaulUlrik** [comment]
嗯，谢谢楼上几位，我更新到最新的1.13.3用了一天也没再遇到了。。
