### ISSUE TITLE
购买了X-Tunnel 一季度 300GB 流量，显示历史为空

### ISSUE THREAD

**Issue by mayong43111** [XX-net/XX-Net#3180]
Hi 您好，

    我购买了3个月300GB流量，但是购买成功后显示流量依然为 1MB。我重新启动并重新登录以后依然是这样，请帮忙查询一下。我的收据号为：5524-8755-5598-3858。
    
日志信息部分如下：
May 03 14:50:41.108 - [INFO] Use proxy:127.0.0.1:8087
May 03 14:50:48.668 - [INFO] api:login success t:7559
May 03 14:50:48.669 - [INFO] update xt_server 104.207.140.47:6666
May 03 14:50:48.669 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:1000000.000000
May 03 14:50:49.280 - [INFO] login_session time:609 msg:Success
May 03 14:50:49.296 - [INFO] Socks5 server listen:127.0.0.1:1080.
May 03 14:54:37.591 - [DEBUG] x_tunnel force update info
May 03 14:54:38.239 - [INFO] api:login success t:648
May 03 14:54:38.239 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:1000000.000000
May 03 15:06:35.921 - [DEBUG] x-tunnel web_control 127.0.0.1:4955 POST /order
May 03 15:06:36.436 - [WARNING] api:order fail:balance not enough
May 03 15:06:36.437 - [WARNING] order fail:balance not enough
May 03 15:15:42.618 - [DEBUG] x-tunnel web_control 127.0.0.1:11812 POST /order
May 03 15:15:43.033 - [INFO] api:order success t:414
May 03 15:15:46.045 - [DEBUG] x_tunnel force update info
May 03 15:15:46.450 - [INFO] api:login success t:404
May 03 15:15:46.450 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:300001000000.000000
May 03 15:19:05.954 - [INFO] Close Socks5 server
May 03 15:19:05.954 - [INFO] Stopping session
May 03 15:19:05.954 - [INFO] start close all connection
May 03 15:19:05.954 - [DEBUG] stop all connection finished
May 03 15:19:05.954 - [INFO] roundtrip port:6666 thread exit
May 03 15:19:05.954 - [INFO] roundtrip port:6666 thread exit

**Comment by jzp820927** [comment]
你是不是只充值进去了，但是没买套餐？

**Comment by mayong43111** [comment]
> jzp820927 commented 10 minutes ago

> 你是不是只充值进去了，但是没买套餐？

购买过了，还短暂的显示300G 了一下，然后就消失的不见了。

**Comment by jzp820927** [comment]
有点诡异啊，刷新也不行，或者退出账号，重新登录？

**Comment by mayong43111** [comment]
> jzp820927 

> 有点诡异啊，刷新也不行，或者退出账号，重新登录？

目前没有重启电脑，其它方式都尝试过了。

**Comment by jzp820927** [comment]
好吧，那我也不知道了，找X大解决吧

**Comment by xxnet** [comment]
日志看过了，收到充值，时间是 15:15:32
流量打进去了，然后看到你15:15:53 登陆，显示流量已经包含在里面了。

你的客户端日志也显示拿到流量了：
May 03 15:15:46.450 - [INFO] request_balance host:104.207.140.47 port:6666
balance:0.000000 quota:300001000000.000000

你只需要重新登陆一次就好了，或者双击流量区域，就会刷新出来。

**Comment by mayong43111** [comment]
@xxnet 
问题奇怪就在于，我重新登录了一次以后，就再也看不到流量了。双击流量区域，流量显示为0 （刚才用掉了默认的1MB）

我重启电脑再次登录以后的日志如下：
May 03 16:56:43.793 - [INFO] use config_path:D:\XX-Net-2.9.4\data\x_tunnel\client.json
May 03 16:56:43.809 - [INFO] Use proxy:127.0.0.1:8087
May 03 16:56:45.043 - [INFO] api:login success t:1233
May 03 16:56:45.043 - [WARNING] no quota
May 03 16:56:45.043 - [INFO] update xt_server 104.207.140.47:6666
May 03 16:56:45.043 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:0.000000
May 03 16:56:45.387 - [WARNING] login_session time:344 fail, res:2 msg:no quota
May 03 16:56:45.387 - [WARNING] x-tunnel session not start
May 03 16:56:45.387 - [INFO] Socks5 server listen:127.0.0.1:1080.
May 03 16:56:59.006 - [DEBUG] x_tunnel force update info
May 03 16:56:59.338 - [INFO] api:login success t:332
May 03 16:56:59.338 - [WARNING] no quota
May 03 16:56:59.338 - [INFO] update xt_server 104.207.140.47:6666
May 03 16:56:59.338 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:0.000000
May 03 16:57:31.913 - [DEBUG] x_tunnel force update info
May 03 16:57:32.243 - [INFO] api:login success t:329
May 03 16:57:32.243 - [WARNING] no quota
May 03 16:57:32.244 - [INFO] update xt_server 104.207.140.47:6666
May 03 16:57:32.244 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:0.000000
May 03 16:57:33.310 - [DEBUG] x_tunnel force update info
May 03 16:57:33.638 - [INFO] api:login success t:328
May 03 16:57:33.638 - [WARNING] no quota
May 03 16:57:33.639 - [INFO] update xt_server 104.207.140.47:6666
May 03 16:57:33.639 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:0.000000
May 03 16:57:49.046 - [INFO] api:get_history success t:345

**Comment by xxnet** [comment]
​日志查到异常了，原因还要再查。
你可能会偶然出现问题，再出问题，重新注册个账号，我另外转给你流量
