### ISSUE TITLE
xxnet-version: 3.1.1，python.exe已停止工作

### ISSUE THREAD

**Issue by vSolo** [XX-net/XX-Net#3182]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
xxnet-version: 3.1.1

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3099 good:213
network-status: OK
connected-link: new:0 used:0
worker: h1:18 h2:4
scan-ip-thread-num: 15
ip-quality: 412
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

我进行的操作：
设置最大扫描线程数：50
自动调整扫描线程数(帮助)：OFF
再运行 【检查所有IP】
大约5秒钟左右，出现下图报错。

![-](https://cloud.githubusercontent.com/assets/9264222/14977806/fd4aab56-1149-11e6-90ae-c4f35066418b.PNG)

**Comment by jzp820927** [comment]
赶脚应该是系统的问题

**Comment by xxnet** [comment]
​能重现吗？

**Comment by vSolo** [comment]
我又重新操作了一下，这次没出现问题，发现我的版本不是最新的，我先升级一下，再有问题我保留下日志。
查找了系统事件查看器记录如下
日志名称:          Application
来源:            Application Error
日期:            2016/5/3 
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           233333
描述:
错误应用程序名称: python.exe，版本: 0.0.0.0，时间戳: 0x56634a05
错误模块名称: ntdll.dll，版本: 6.1.7601.18247，时间戳: 0x521ea8e7
异常代码: 0xc0000005
错误偏移量: 0x0002e3be
错误进程 ID: 0xbd0
错误应用程序启动时间: 0x01d1a48df97e4df8
错误应用程序路径: D:\XX-Net-3.1.1\code\default\python27\1.0\python.exe
错误模块路径: C:\Windows\SysWOW64\ntdll.dll
报告 ID: ×××××××××××××××××××××××××
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-05-02T.000000000Z" />
    <EventRecordID>31154</EventRecordID>
    <Channel>Application</Channel>
    <Security />
  </System>
  <EventData>
    <Data>python.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>56634a05</Data>
    <Data>ntdll.dll</Data>
    <Data>6.1.7601.18247</Data>
    <Data>521ea8e7</Data>
    <Data>c0000005</Data>
    <Data>0002e3be</Data>
    <Data>bd0</Data>
    <Data>01d1a48df97e4df8</Data>
    <Data>D:\XX-Net-3.1.1\code\default\python27\1.0\python.exe</Data>
    <Data>C:\Windows\SysWOW64\ntdll.dll</Data>
    <Data>55013ebd-1082-11e6-8b65-e60161542296</Data>
  </EventData>
</Event>

**Comment by zjhzxhz** [comment]
我也遇到了相同的问题～
等程序Crash的时候已经没法看日志了～
晚些时候我用Debug模式运行看看～

**Comment by zjhzxhz** [comment]
话说你更新到最新的master了吗? @vSolo

**Comment by vSolo** [comment]
@zjhzxhz 这3.1.3 怎么下载不下来

**Comment by zjhzxhz** [comment]
3.1.3不是最新版 :)

**Comment by zjhzxhz** [comment]
我这边的Crash信息~ 感觉是Python-OpeenSSL的问题?

![appcrash](https://cloud.githubusercontent.com/assets/1730504/14981234/4bd46404-1160-11e6-8eaa-11a2584302c0.png)

**Comment by zjhzxhz** [comment]
相关Issue: #3162 #3161

**Comment by xxnet** [comment]
​如果出现在OpenSSL里，那就好解释了，这是这次更新的二进制库。
而且cffi是一种类似hack的方式实现python对C库的调用，实现不完善容易出问题。

需要重新找一个公开发行版的python-OpenSSL win32的库，测试稳定了替换掉。

**Comment by jzp820927** [comment]
还好我只用 Linux ，win 各种问题

**Comment by xxnet** [comment]
​windows 用户还是大多数，虽然我也是linux

**Comment by zjhzxhz** [comment]
我现在是Windows + Linux同时用 0 0
Linux之前问题也很多好吗～ 虽然今天修复了~

**Comment by jzp820927** [comment]
我 Linux 用 XX，从来没遇到过问题，不管你们信不信，反正我是信了。

**Comment by zjhzxhz** [comment]
@jzp820927 
#3165 我是真的不想打你脸~

**Comment by zjhzxhz** [comment]
开了一晚上的Debug模式, Beep了一晚上, 终于等到它Crash.
然而什么都没有!!

![Error](https://cloud.githubusercontent.com/assets/1730504/14985334/a9dd0cfe-1179-11e6-8396-2cb71288d835.png)

没错~ 我就是像秀一下我的桌面 XD

**Comment by xxnet** [comment]
​目前的cryptgraph 还是0.8.2 ， python官网已经是1.3.1了
https://pypi.python.org/pypi/cryptography

试试更新这个库

**Comment by xxnet** [comment]
​master 上已经更新到 1.3.1，可以下载下来测试
