### ISSUE TITLE
部署失败，没有动静

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#3185]
2016-05-03 18:53:20,194 - root - INFO - enable debug logging
2016-05-03 18:53:20,194 - root - INFO - set proxy to http://127.0.0.1:8087
2016-05-03 18:53:20,224 - root - INFO - ============ Begin upload ============
2016-05-03 18:53:20,224 - root - INFO - appid:zzgldr
2016-05-03 18:53:20,302 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'zzgldr'}
2016-05-03 18:53:20,302 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-05-03 18:53:20,302 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=zzgldr&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=

这是部署的日志，到这个地方就没动静了，然后点左侧的状态、配置之类的就进不去了，也无法上网了

下面是这是总的日志：
May 03 18:59:18.596 - [INFO] deploy begin.
May 03 18:59:19.628 - [DEBUG] GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log
May 03 18:59:20 - [DEBUG]LOG_EXCEPT: GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log , Except:[Errno 9] Bad file descriptor
May 03 18:59:21.636 - [DEBUG] GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log
May 03 18:59:22.642 - [DEBUG] GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log
May 03 18:59:23.652 - [DEBUG] GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log
May 03 18:59:24.667 - [DEBUG] GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log
May 03 18:59:35.796 - [DEBUG] GAEProxy Web_control 127.0.0.1:50271 GET /deploy?cmd=get_log
然后就没动静，上不了网

**Comment by zzgpku** [comment]
2.9.2以后所有的版本都是这样
也启用了弱安全应用
挂SS的情况下上传也是如此

**Comment by xxnet** [comment]
​3.1.3 试过吗？

**Comment by zzgpku** [comment]
包括3.1.3

**Comment by xxnet** [comment]
诊断信息贴来看看

**Comment by zzgpku** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.3

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12517 good:11143
network-status: OK
connected-link: new:3 used:0
worker: h1:19 h2:0
scan-ip-thread-num: 0
ip-quality: 171
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by zzgpku** [comment]
还有一点需要说明的是，以前部署的时候，虽然也没有部署成功，但会弹窗让我确认一下，而现在没有弹窗提醒我了。

**Comment by jzp820927** [comment]
V6也太BT了吧，1W+ IP

**Comment by zzgpku** [comment]
@jzp820927 应该没那么多。。。这是刚下载下来的，有些无效的ip应该没有剔去。。以前用2.9.2版本稳定的时候能有七八十个
现在我觉得主要是看h2的数量，这个速度很快啊

**Comment by jzp820927** [comment]
你要 http2 ，全部上 gws 不就行了，我测试过，gws 基本上 100%支持，反正我还没测到过不支持，其实我也还没测多少

**Comment by zzgpku** [comment]
@jzp820927 怎么上gws？
现在速度杠杠的，1080p一点问题都没有，1440p也基本没问题，但2k的话速度就会一下子掉下来

**Comment by jzp820927** [comment]
全部用 gws 的IP，不用混着 GVS 就行了，gvs 不支持 http2

**Comment by xxnet** [comment]
​可以考虑统计有多少h2的ip，优先用h2了
