### ISSUE TITLE
 只有上谷歌学术的时候会这样，提示异常流量

### ISSUE THREAD

**Issue by xiayh17** [XX-net/XX-Net#3188]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

IP 地址：107.178.194.103
时间：2016-05-03T11:50:10Z
网址：http://www.google.com/

首先阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，90%的问题此处都有答案

#### 常见问题
1. 为什么我的连接数是0、是个位数，反正连不上真网？<br>
此处是你的真爱([issue#2853](https://github.com/XX-net/XX-Net/issues/2853))

2. 为什么状态页面提示代理、证书有问题（有问题并且无法上真网）？<br>
确保从官方下载的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，在此基础上参见[证书故障](https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA)

3. 为什么升级新版本后，出现奇奇怪怪的故障？<br>
开源项目开发者精力有限，不能把软件方方面面测试的很完美，但会有其他人遇到并解决了这些奇怪的问题，作者亦会很快的推出修复版，请确保你所使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，在此基础上你的问题依然没得到解决，[请到issue区搜索一下](https://github.com/XX-net/XX-Net/issues)

#### 提交issue时请贴出状态页、GAE_proxy日志、部署日志，以便开发者和其他用户更好地帮助你
 - 点击此页面http://127.0.0.1:8085 的【诊断信息】按钮，如没有此按钮，将【OFF】置为【ON】
 - 将诊断信息贴在此处

如果你不能提供【诊断信息】，我们将置此问题为无效。

#### 此处请描述你遇到的问题

1. 尽可能详细，如问题能重现请附带 Logs
2. 请记住：没有人能读懂你的心思
3. 当你的问题得到解决后，请到 Issue 区关闭问题。

**Comment by xxnet** [comment]
​什么版本？

**Comment by xiayh17** [comment]
3.1.1

**Comment by kingjia1989** [comment]
2.9.6 今天也出现这个问题了
