### ISSUE TITLE
[示例问题] 为什么使用一段时间后连接数会变为 0，重启 GAEProxy 后才能恢复？

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#3193]
### 问题描述
我发现 XX-Net 在使用一段时间，大概一个小时左右，连接数会变成 0，无法通过代理打开网页。
只有在托盘菜单重启 GAEProxy 后才能恢复正常。
但是再过一个小时左右又会出现这个问题。

### 诊断信息
    XX-Net Status:

    sys-platform: AMD64, Windows-10-10.0.10586
    os-system: Windows
    os-version: 10.0.10586
    os-release: 10
    os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
    architecture: 32bit,WindowsPE
    browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
    xxnet-version: 3.1.3

    python-version: 2.7.11
    openssl-version: 0.15.1 TLSv1_2 h2:alpn

    ipv6-status: 0
    gws-ip-num: total:595 good:244
    network-status: OK
    connected-link: new:0 used:0
    worker: h1:0 h2:0
    scan-ip-thread-num: 3
    ip-quality: 574
    is-idle: 0
    block-stat: OK
    proxy_state: OK
    ca_state: OK
    Appid_Working: true
    Appids_Out_Of_Quota: false
    Appids_Not_Exist: false
    Using_Public_Appid: false

### 连接数变成 0 后再打开网页的日志
    May 03 11:58:35.446 - [INFO] GAE t:307096 s:57718 GET https://www.google.com/async/newtab?async=xid:1,_fmt:json&ei=**************&espv=2&yv=2
    May 03 11:58:35.446 - [WARNING] gae_handler.handler send response fail. e:error(10053, '') https://www.google.com/async/newtab?async=xid:1,_fmt:json&ei=**************&espv=2&yv=2
    May 03 11:58:35.723 - [DEBUG] create_ssl update ip:113.171.247.58 time:318 h2:0
    May 03 11:58:35.737 - [INFO] GAE t:89815 s:0 POST https://www.google.com/chromesuggestions/click?q=**************&cd=3
    May 03 11:58:35.738 - [WARNING] gae_handler.handler send response fail. e:error(10053, '') https://www.google.com/chromesuggestions/click?q=**************&cd=3
    May 03 11:58:35.751 - [DEBUG] create_ssl update ip:202.75.147.50 time:560 h2:0
    May 03 11:58:35.781 - [DEBUG] get ip:66.96.226.244 t:451
    May 03 11:58:35.785 - [INFO] GAE t:87847 s:0 POST https://www.google.com/chromesuggestions/click?q=**************&cd=5
    May 03 11:58:35 - [WARNING]LOG_EXCEPT: gae_handler.handler send response fail. e:error(10053, '') https://www.google.com/chromesuggestions/click?q=**************&cd=5, Except:[Errno 9] Bad file descriptor

**Comment by Cat7373** [comment]
问题已在 https://github.com/XX-net/XX-Net/commit/739a915b2c35b64979278992a3a57f398faf7053 中修复。

**Comment by Cat7373** [comment]
因为问题已经解决，所以关闭这个 Issue。

**Comment by Cat7373** [comment]
这个 Issue 的源代码
    ### 问题描述
    我发现 XX-Net 在使用一段时间，大概一个小时左右，连接数会变成 0，无法通过代理打开网页。
    只有在托盘菜单重启 GAEProxy 后才能恢复正常。
    但是再过一个小时左右又会出现这个问题。

    ### 诊断信息
        XX-Net Status:

        sys-platform: AMD64, Windows-10-10.0.10586
        os-system: Windows
        os-version: 10.0.10586
        os-release: 10
        os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
        architecture: 32bit,WindowsPE
        browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
        xxnet-version: 3.1.3

        python-version: 2.7.11
        openssl-version: 0.15.1 TLSv1_2 h2:alpn

        ipv6-status: 0
        gws-ip-num: total:595 good:244
        network-status: OK
        connected-link: new:0 used:0
        worker: h1:0 h2:0
        scan-ip-thread-num: 3
        ip-quality: 574
        is-idle: 0
        block-stat: OK
        proxy_state: OK
        ca_state: OK
        Appid_Working: true
        Appids_Out_Of_Quota: false
        Appids_Not_Exist: false
        Using_Public_Appid: false

    ### 连接数变成 0 后再打开网页的日志
        May 03 11:58:35.446 - [INFO] GAE t:307096 s:57718 GET https://www.google.com/async/newtab?async=xid:1,_fmt:json&ei=**************&espv=2&yv=2
        May 03 11:58:35.446 - [WARNING] gae_handler.handler send response fail. e:error(10053, '') https://www.google.com/async/newtab?async=xid:1,_fmt:json&ei=**************&espv=2&yv=2
        May 03 11:58:35.723 - [DEBUG] create_ssl update ip:113.171.247.58 time:318 h2:0
        May 03 11:58:35.737 - [INFO] GAE t:89815 s:0 POST https://www.google.com/chromesuggestions/click?q=**************&cd=3
        May 03 11:58:35.738 - [WARNING] gae_handler.handler send response fail. e:error(10053, '') https://www.google.com/chromesuggestions/click?q=**************&cd=3
        May 03 11:58:35.751 - [DEBUG] create_ssl update ip:202.75.147.50 time:560 h2:0
        May 03 11:58:35.781 - [DEBUG] get ip:66.96.226.244 t:451
        May 03 11:58:35.785 - [INFO] GAE t:87847 s:0 POST https://www.google.com/chromesuggestions/click?q=**************&cd=5
        May 03 11:58:35 - [WARNING]LOG_EXCEPT: gae_handler.handler send response fail. e:error(10053, '') https://www.google.com/chromesuggestions/click?q=**************&cd=5, Except:[Errno 9] Bad file descriptor

**Comment by chn475111** [comment]
目前我3.3.1版本, 依然是这样;
连接上之后, 一会不用, 就会断开连接
每次都需要重新寻找可用ip, 感觉好麻烦...

**Comment by jzp820927** [comment]
升级到 3.3.4 试试

**Comment by chn475111** [comment]
感觉还是我的GoAgent好用

**Comment by jzp820927** [comment]
只要有 IP，什么都好用
