### ISSUE TITLE
3.1.2版本打开www.google.com为504 但是youtobe之类没有问题(换成3.1.3稳定版可以打开www.google.com)

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#3199]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.2

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:8954 good:8332
network-status: OK
connected-link: new:0 used:0
worker: h1:22 h2:0
scan-ip-thread-num: 50
ip-quality: 273
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Cat7373** [comment]
8000多个ip，看着眼红。。。

**Comment by JMaxime** [comment]
哈哈。。。。。。

**Comment by Cat7373** [comment]
既然新版已经可以用了。。。
那还提这个干嘛。。

**Comment by JMaxime** [comment]
@Cat7373 出现问题后发表的话题 然后自己下载最新的稳定版测试看有没有问题 测试没有问题之后就把主题改回来了 方便其他墙友

**Comment by jzp820927** [comment]
可以 close 了。
