### ISSUE TITLE
goagent 服务端怎么升级到新版本呢？

### ISSUE THREAD

**Issue by angel126** [XX-net/XX-Net#32]
goagent 服务端怎么升级到新版本呢？

**Comment by xxnet** [comment]
访问http://127.0.0.1:8085/ 看deploy，重新部署服务端

**Comment by angel126** [comment]
这个是只能升级到3.1.34 这个版本吧？

**Comment by xxnet** [comment]
其实是兼容3.2之前和3.2之后的版本。
 goagent的服务端目前就2个版本，现在我作成了兼容模式了，各个版本的客户端都可以兼容了。
