### ISSUE TITLE
日志错误

### ISSUE THREAD

**Issue by github-xx** [XX-net/XX-Net#3201]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.3

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:600 good:276
network-status: OK
connected-link: new:10 used:0
worker: h1:66 h2:8
scan-ip-thread-num: 100
ip-quality: 539
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
日志：
ay 04 10:43:21.183 - [INFO] GAE t:1157 s:4668 GET http://v.6.cn/room/getRoomList.php?id=41170632&tm=1462329804
DEBUG:root:buffer socket flush:17
May 04 10:43:23.448 - [DEBUG] ip:41.77.223.208 real fail
DEBUG:hyper.packages.hpack.hpack:HPACK encoding HTTPHeaderMap([(':method', 'POST'), (':scheme', 'https'), (':authority'
, 'gw105yy68.appspot.com'), (':path', '/_gh/'), ('Content-Length', '456')])
DEBUG:hyper.packages.hpack.hpack:Adding (':method', 'POST') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 3 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 7 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding (':authority', 'gw105yy68.appspot.com') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 116 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding (':path', '/_gh/') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 115 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding ('content-length', '456') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 111 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Encoded header block to 儑趔?
DEBUG:root:buffer socket flush:479
DEBUG:hyper.packages.hpack.hpack:Decoding 堲a栦Y>?Jh? 笭q2%1h唧\593
DEBUG:hyper.packages.hpack.hpack:Decoded 8, consumed 1 bytes
DEBUG:hyper.packages.hpack.hpack:Decoded (':status', '200'), consumed 1
DEBUG:hyper.packages.hpack.hpack:Decoded 116, consumed 1 bytes
DEBUG:hyper.packages.hpack.hpack:Decoded ('content-type', 'image/gif'), consumed 1
DEBUG:hyper.packages.hpack.hpack:Decoded 33, consumed 1 bytes
DEBUG:hyper.packages.hpack.hpack:Decoded 22, consumed 1 bytes
DEBUG:hyper.packages.hpack.hpack:Evicting date: Wed, 04 May 2016 02:39:39 GMT from the header table
DEBUG:hyper.packages.hpack.hpack:Decoded ('date', 'Wed, 04 May 2016 02:43:32 GMT'), total consumed 24 bytes, indexed Tr
ue

**Comment by xxnet** [comment]
​怎么会出这个日志，那是hyper里的，默认是不会出日志的

**Comment by github-xx** [comment]
直接下载的，没改过配置，老版本没有这个提示。
