### ISSUE TITLE
3.1.1版本无法访问google scholar，警告unusual traffic from your computer network

### ISSUE THREAD

**Issue by hairuo** [XX-net/XX-Net#3202]
**问题描述：**
能正常访问google, youtube等，只有google scholar无法访问。
打开网页https://scholar.google.com/ 显示如下：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the Terms of Service. The block will expire shortly after those requests stop.

This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests. If you share your network connection, ask your administrator for help — a different computer using the same IP address may be responsible. Learn more

Sometimes you may see this page if you are using advanced terms that robots are known to use, or sending requests very quickly.

IP address: 107.178.194.92
Time: 2016-05-04T02:43:49Z
URL: http://www.google.com/

从昨天更新XX-Net3.1.1版本开始出现问题，到今天问题还在。尝试过清除chrome浏览器的cookie和历史，重启电脑等无效。访问scholar镜像http://scholar.glgoo.org/ 正常。

**GAE_Proxy日志**：
May 04 10:43:04.260 - [INFO] GAE CONNECT scholar.google.com:443
May 04 10:43:04.260 - [INFO] GAE CONNECT scholar.google.com:443
May 04 10:43:04.260 - [INFO] GAE CONNECT scholar.google.com:443
May 04 10:43:04.302 - [DEBUG] GAE CONNECT GET https://scholar.google.com/
May 04 10:43:04.304 - [DEBUG] 202.75.141.245 Send:HeadersFrame 11 F:END_HEADERS
May 04 10:43:04.306 - [DEBUG] 202.75.141.245 Send:DataFrame 11 F:END_STREAM len:507
May 04 10:43:04.997 - [DEBUG] 202.75.141.245 Recv:HeadersFrame 11 F:END_HEADERS
May 04 10:43:05.011 - [DEBUG] 202.75.141.245 Recv:DataFrame 11 F:END_STREAM len:2101
May 04 10:43:05.012 - [DEBUG] 202.75.141.245 close stream:11 end stream
May 04 10:43:05.012 - [INFO] GAE t:710 s:1773 GET https://scholar.google.com/
May 04 10:43:05.013 - [DEBUG] 202.75.141.245 Recv:PingFrame
May 04 10:43:05.014 - [DEBUG] 202.75.141.245 Send:PingFrame F:ACK
May 04 10:43:05.499 - [INFO] GAE CONNECT live.github.com:443
May 04 10:43:05.499 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/NjM3MjM3OjhmMjVhNDI5NWY3NzJiZGVjYzQ0YjViNzkxNTlkOTAyOjE2YzVjYjU1MmRhNjAzNGJjYjVmYmI2YTk4NjM1ODg2OGI2OGM1M2U1ZDVjZGM2ZjhiNmFhODIzZTI1OWQyZmM=--58ea19c4ed7a01ae657fec5cb0e40e4ca32fbfea
May 04 10:43:05.515 - [DEBUG] 202.75.141.245 Send:HeadersFrame 13 F:END_HEADERS
May 04 10:43:05.531 - [DEBUG] 202.75.141.245 Send:DataFrame 13 F:END_STREAM len:599
May 04 10:43:05.535 - [DEBUG] GAE CONNECT GET https://scholar.google.com/favicon.ico
May 04 10:43:05.538 - [DEBUG] 202.75.147.39 Send:HeadersFrame 1 F:END_HEADERS
May 04 10:43:05.539 - [DEBUG] 202.75.147.39 Send:DataFrame 1 F:END_STREAM len:466
May 04 10:43:06.236 - [DEBUG] 202.75.147.39 Recv:HeadersFrame 1 F:END_HEADERS
May 04 10:43:06.236 - [DEBUG] 202.75.147.39 Recv:DataFrame 1 F:END_STREAM len:2100
May 04 10:43:06.236 - [DEBUG] 202.75.147.39 close stream:1 end stream
May 04 10:43:06.236 - [INFO] GAE t:700 s:1773 GET https://scholar.google.com/favicon.ico
May 04 10:43:06.236 - [DEBUG] 202.75.147.39 Recv:PingFrame
May 04 10:43:06.236 - [DEBUG] 202.75.147.39 Send:PingFrame F:ACK
May 04 10:43:14.514 - [INFO] GAE CONNECT mail.google.com:443
May 04 10:43:14.533 - [DEBUG] GAE CONNECT GET https://mail.google.com/mail/u/0/feed/atom/?timestamp=1462329794511
May 04 10:43:14.540 - [DEBUG] 202.75.147.39 Send:HeadersFrame 3 F:END_HEADERS
May 04 10:43:14.541 - [DEBUG] 202.75.147.39 Send:DataFrame 3 F:END_STREAM len:487
May 04 10:43:14.888 - [DEBUG] 202.75.147.39 Recv:HeadersFrame 3 F:END_HEADERS
May 04 10:43:14.894 - [DEBUG] 202.75.147.39 Recv:DataFrame 3 F:END_STREAM len:485
May 04 10:43:14.894 - [DEBUG] 202.75.147.39 close stream:3 end stream
May 04 10:43:14.894 - [INFO] GAE t:360 s:121 GET https://mail.google.com/mail/u/0/feed/atom/?timestamp=1462329794511
May 04 10:43:14.895 - [DEBUG] 202.75.147.39 Recv:PingFrame
May 04 10:43:14.895 - [DEBUG] 202.75.147.39 Send:PingFrame F:ACK
May 04 10:43:16.055 - [INFO] GAE CONNECT clients4.google.com:443
May 04 10:43:16.078 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
May 04 10:43:16.083 - [DEBUG] 202.75.147.39 Send:HeadersFrame 5 F:END_HEADERS
May 04 10:43:16.084 - [DEBUG] 202.75.147.39 Send:DataFrame 5 F:END_STREAM len:1374
May 04 10:43:16.504 - [INFO] GAE CONNECT live.github.com:443
May 04 10:43:16.526 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/NjM3MjM3OjhmMjVhNDI5NWY3NzJiZGVjYzQ0YjViNzkxNTlkOTAyOjZlOWNjNWMxYmFkMmZmYjFlMGY4MWFjM2JmMmEyMjdmNzA3YjYxNDczMDk2M2E5MGJlOTMxNzkwNjhjZTY0YTY=--69d7acbdaf2191078e63e57edd45c8476272afe2
May 04 10:43:16.532 - [DEBUG] 202.75.141.245 Send:HeadersFrame 15 F:END_HEADERS
May 04 10:43:16.533 - [DEBUG] 202.75.141.245 Send:DataFrame 15 F:END_STREAM len:603
May 04 10:43:16.664 - [DEBUG] 202.75.147.39 Recv:HeadersFrame 5 F:END_HEADERS
May 04 10:43:16.678 - [DEBUG] 202.75.147.39 Recv:DataFrame 5 F:END_STREAM len:14890
May 04 10:43:16.679 - [DEBUG] 202.75.147.39 close stream:5 end stream
May 04 10:43:16.679 - [INFO] GAE t:599 s:14464 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
May 04 10:43:16.680 - [DEBUG] 202.75.147.39 Recv:PingFrame
May 04 10:43:16.680 - [DEBUG] 202.75.147.39 Send:PingFrame F:ACK
May 04 10:43:16.697 - [INFO] GAE CONNECT clients4.google.com:443
May 04 10:43:16.720 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
May 04 10:43:16.725 - [DEBUG] 202.75.147.39 Send:HeadersFrame 7 F:END_HEADERS
May 04 10:43:16.727 - [DEBUG] 202.75.147.39 Send:DataFrame 7 F:END_STREAM len:1651
May 04 10:43:16.978 - [DEBUG] 202.75.141.245 Recv:HeadersFrame 15 F:END_HEADERS
May 04 10:43:16.982 - [DEBUG] 202.75.141.245 Recv:DataFrame 15 F:END_STREAM len:260
May 04 10:43:16.983 - [DEBUG] 202.75.141.245 close stream:15 end stream
May 04 10:43:16.983 - [INFO] GAE t:456 s:0 GET https://live.github.com/_sockets/NjM3MjM3OjhmMjVhNDI5NWY3NzJiZGVjYzQ0YjViNzkxNTlkOTAyOjZlOWNjNWMxYmFkMmZmYjFlMGY4MWFjM2JmMmEyMjdmNzA3YjYxNDczMDk2M2E5MGJlOTMxNzkwNjhjZTY0YTY=--69d7acbdaf2191078e63e57edd45c8476272afe2
May 04 10:43:16.983 - [DEBUG] 202.75.141.245 Recv:PingFrame
May 04 10:43:16.984 - [DEBUG] 202.75.141.245 Send:PingFrame F:ACK
May 04 10:43:17.195 - [DEBUG] 202.75.147.39 Recv:HeadersFrame 7 F:END_HEADERS
May 04 10:43:17.200 - [DEBUG] 202.75.147.39 Recv:DataFrame 7 F:END_STREAM len:825
May 04 10:43:17.200 - [DEBUG] 202.75.147.39 close stream:7 end stream
May 04 10:43:17.201 - [INFO] GAE t:480 s:399 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
May 04 10:43:17.201 - [DEBUG] 202.75.147.39 Recv:PingFrame
May 04 10:43:17.202 - [DEBUG] 202.75.147.39 Send:PingFrame F:ACK
May 04 10:43:18.351 - [WARNING] read request line empty

**Comment by xxnet** [comment]
​3.1.3 已经解决这个问题

**Comment by hairuo** [comment]
更新至3.1.3stable版，问题确实自然消失了，非常感谢!

**Comment by hairuo** [comment]
XX-net 3.2.5又遇到这个问题了。。。

**Comment by jzp820927** [comment]
3.2.6 呢

**Comment by hairuo** [comment]
3.2.6还不是稳定版，XX-Net还没有自动更新。更新后来反馈。

**Comment by hairuo** [comment]
刚刚想起来XX-Net是可以修改自动升级到测试版的。现在已经更新到3.2.6，发现问题还在。

问题描述：
google scholar能打开，搜索，但选择cite->endnote的时候会出现如下：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

**Comment by jzp820927** [comment]
ini 中改为 直连试试

**Comment by hairuo** [comment]
试了试ini直连，等了一天测试还是无效。

测试方法如下：
在data\gae_proxy\下自建了一个manual.ini，内容为：

> [hosts]
> scholar.google.com = direct

**Comment by yeahwu** [comment]
再添加一条
`.google.com = direct`
前面有一个点

**Comment by hairuo** [comment]
添加了.google.com = direct还是不行。

**Comment by jzp820927** [comment]
你这个太不科学了，添加了规则后，访问 google scholar 还是显示“IP address: 107.178.194.92” 吗？

**Comment by hairuo** [comment]
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?


IP address: 107.178.195.181
Time: 2016-08-03T13:14:43Z
URL: http://www.google.com/

**Comment by jzp820927** [comment]
这说明，规则没生效，域名还是走了 gae。你添加了规则以后，有没有重启 xx

**Comment by hairuo** [comment]
之前试过右击XX-Net选择重启GAEProxy。刚刚试了退出，然后重新打开start.bat，还是不行：

Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?


IP address: 107.178.195.161
Time: 2016-08-04T02:57:31Z
URL: http://www.google.com/

**Comment by jzp820927** [comment]
这个我也不知道是怎么回事了，应该是直连规则没有生效，你仔细检查下规则有没有问题吧

**Comment by jzp820927** [comment]
这个我也不知道是怎么回事了，应该是直连规则没有生效，你仔细检查下规则有没有问题吧

**Comment by hairuo** [comment]
好的，查了查规则也没有问题，我等下一个版本看看吧。感谢回复！

**Comment by hairuo** [comment]
反馈更新问题：
google scholar能打开，搜索，但选择cite->endnote的时候会出现如下：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

解决方法：
”将那个出现问题的网址也加入直联模式就行
scholar.googleusercontent.com = direct“

非常感谢@zhuoquanzhou

也谢谢楼上各位!

**Comment by hairuo** [comment]
后续升级版本，甚至直连模式，问题以及解决，因此关闭这个issue，谢谢回答！
