### ISSUE TITLE
Github趋势排名，“莆田系医院名单列表”排名第一

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3204]
为了健康，可以复制下这些名单，然后绕着走，当然也可以协作提交医院名单

Github趋势排名：https://github.com/trending

项目地址：https://github.com/langhua9527/BlackheartedHospital

**Comment by Cat7373** [comment]
第一眼看到这个标题以为是小广告。。。

**Comment by fuding** [comment]
感觉5线城市好多小私人医院都是走莆田模式。各种妇产各种给老年人体检的。

**Comment by yeahwu** [comment]
注意，名单里还有好多叫“第几人民医院”滴，这个国家烂透鸟。
主要是想到这些个医院害了多少无知少女，而感到愤慨。
最最主要的是这些信息还不能在墙内传播，烂透了，烂透了。

fuding <notifications@github.com>于2016年5月4日 周三13:52写道：

**Comment by JMaxime** [comment]
我靠 上海、成都、武汉这三个城市占了半壁江山啊 真是吓人啊

**Comment by heikehuan** [comment]
多宣传一下吧，官方到现在还藏着掖着不给传播。
莆田系的后台吓死人，你惹不起的。
莆田系高层陈某，跟上上届国家主席关系密切。
他们闹这么大事，莆田系一个高层也没被抓，这就是原因。

**Comment by Cat7373** [comment]
@heikehuan 看了下妮的个人资料。。。
妮这话基本就等于实名说的。。。

**Comment by yeahwu** [comment]
俺这个人平时还算克制滴，这次实在是忍不住了
古人尚有“悬壶济世”的情怀，
而如今这些个“百度”“莆田系”都变成了屠宰场，逮一个宰一个，不死不休
医院哪，生命托付的地方呀！

**Comment by Cat7373** [comment]
![](http://ww2.sinaimg.cn/large/9103a520jw1f3jme2xb1cj211y09tjt9.jpg)

**Comment by ming-ge** [comment]
百度一下"莆田系"
根据相关法律法规和政策，部分搜索结果未予显示。

**Comment by ming-ge** [comment]
http://finance.ifeng.com/a/20160505/14363747_0.shtml

**Comment by heikehuan** [comment]
@Cat7373吓我一跳，赶紧改了资料

**Comment by Krabapple** [comment]
@Cat7373 
请问如果个人页面里面没什么重要资料(就像我这样)，去参与扩充莆田系名单，会不会被逮到？
我是直连，顶多挂个xxnet强制GFW配置，改成美国IP。
至于虚拟机和Tor什么的，目前还不会用。
很想参与揭发行动，又怕因为IP或者其它什么信息暴露自己。
谢谢！

**Comment by jzp820927** [comment]
这是个两难的问题，如果要保证绝对安全，可以通过 gmail 右键点方式告知 repo 主，如果自己要维护，还说 tor 比较安全，或者 x_tunnel 安全性也不错。

**Comment by yeahwu** [comment]
@Krabapple 致敬，
现在的代理工具都不会直接爆ip的，你这种需求其实x-tunnel就可以满足你。
当然党国逮人是需要成本的，需要动用资源，他会衡量必要性。像这种项目，俺认为，不会引起党国主意的
你如果不放心的话，也可以email联系作者，名单交给他发表也行嘛。

**Comment by Cat7373** [comment]
http://finance.ifeng.com/a/20160506/14366341_0.shtml

**Comment by vSolo** [comment]
@heikehuan 小欢欢，开门！快递！，打你电话------512没人接，听说你会玩lol，还是白金段位，智慧大大的嘛。

**Comment by Krabapple** [comment]
谢谢解答！
另外贴一个知乎，可以看看：https://www.zhihu.com/question/45219415/answer/98957967

**Comment by simonasd** [comment]
@Krabapple 对于向敏感项目提交贡献，有一个补充的小建议：用随机字母用户名、密码注册一个gmail作为邮箱，再用另外的随机用户名密码注册一个Github，提交贡献。更可以每次贡献都采用不同的马甲。

**Comment by jzp820927** [comment]
匿个名，也真是不容易啊

**Comment by Krabapple** [comment]
@simonasd 
那我注册Gmail的时候需不需要挂虚拟机、Tor、多重代理？
操纵Github账号的时候需不需要挂这些？
以前看编程随想说过，只要全部过程中在虚拟机以外的环境操作过一次，即使以后再匿名，也没用了，所以一直很谨慎，想等全搞清楚以后真正弄几个匿名身份。谢谢！

**Comment by jzp820927** [comment]
按道理说，tor 只有隐藏IP，但是不能隐藏你的硬件信息，虚拟机可以隐藏硬件信息，也就是说，虚拟机+tor 可以隐藏所有和你相关的信息，就怕大数据分析，一旦留下一点痕迹，通过关联分析找出线索，也是很危险的。确实虚拟机+tor 也是确保万无一失，普通匿名，我觉得 tor 就够了，除非你是很危险的高危份子

**Comment by xxnet** [comment]
普通用户，换个马甲就好了，不需要加tor，tor太慢了。
持续贡献的，建议虚拟机+ 代理
高度匿名，建议双虚拟机隔离 + x_tunnel

**Comment by simonasd** [comment]
@Krabapple 其实最关键的，还是不同身份之间的隔离。编程随想的建议是给炼狱级别用户的。

当你处在普通匿名级别时，不要进行炼狱级别的敏感操作；当你决定加入这个行列时，依照相应的方式，重新建立完全独立的全新身份。

对于你当前“参与莆田系曝光”的操作，如果你每个临时网络身份都只短期使用，没搞出什么大新闻，那么每个临时身份都不会成为重要目标。不同身份之间不存在明显规律或联系，个人认为已经足够。

**Comment by yeahwu** [comment]
其实俺感觉匿名是个工程学，一两句还真讲不清楚。

**Comment by heikehuan** [comment]
我去，都让你们给吓着了，我之前在头条发过那么多敏感信息，早就该跨省追捕10次，牢底坐穿了。

**Comment by jzp820927** [comment]
想想前不久的枫叶香蕉，也是发布敏感信息，又不匿名，就进去了。
