### ISSUE TITLE
新版本完全用不了

### ISSUE THREAD

**Issue by Alucard1797** [XX-net/XX-Net#321]
GoAgent状态信息

Property	Value
Sys Platform	linux2
OS System	Linux
OS version	#80-Ubuntu SMP Thu Mar 12 11:16:18 UTC 2015
OS release	3.13.0-48-generic
OS detail	Dist:Ubuntu; Version:14.04; ID:trusty
language	en_US
architecture	32bitELF
Browser	Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
XX-Net Version	1.12.5
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087
working appids	billyyusonglin10|billyyusonglin|billyyusonglin2|billyyusonglin3|billyyusonglin6
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2915
connected link	0,0
ip-connect-interval	10
block stat(帮助)	

日志
May 3 11:01:10 - [DEBUG] new_conn_pool conn_num:0
May 3 11:01:18 - [DEBUG] create ssl for direct timeout.
May 3 11:01:22 - [INFO] GAE CONNECT www.google.com.hk:443 
May 3 11:01:23 - [INFO] GAE CONNECT mail.google.com:443 
May 3 11:01:23 - [DEBUG] GAE CONNECT GET https://mail.google.com/mail/u/0/feed/atom/?timestamp=1430622083042
May 3 11:01:23 - [DEBUG] new_conn_pool conn_num:0
May 3 11:01:23 - [DEBUG] create ssl for direct timeout.
May 3 11:01:23 - [DEBUG] create ssl for direct timeout.
May 3 11:01:23 - [INFO] GAE CONNECT www.google-analytics.com:443 
May 3 11:01:23 - [DEBUG] create ssl for direct timeout.
May 3 11:01:23 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
May 3 11:01:23 - [DEBUG] new_conn_pool conn_num:0
May 3 11:01:32 - [DEBUG] create ssl for direct timeout.
May 3 11:01:32 - [DEBUG] create ssl for direct timeout.
May 3 11:01:33 - [DEBUG] create ssl for direct timeout.
May 3 11:01:35 - [INFO] GAE CONNECT accounts.google.com:443 
May 3 11:01:35 - [DEBUG] GAE CONNECT POST https://accounts.google.com/o/oauth2/token
May 3 11:01:35 - [DEBUG] new_conn_pool conn_num:0
May 3 11:01:37 - [INFO] GAE CONNECT www.google.com.hk:443 
May 3 11:01:40 - [INFO] GAE CONNECT clients4.google.com:443 
May 3 11:01:40 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/experimentstatus
May 3 11:01:40 - [DEBUG] new_conn_pool conn_num:0
May 3 11:01:43 - [DEBUG] create ssl for direct timeout.
May 3 11:01:53 - [INFO] GAE CONNECT mail.google.com:443 
May 3 11:01:53 - [DEBUG] create ssl for direct timeout.
May 3 11:01:53 - [DEBUG] GAE CONNECT GET https://mail.google.com/mail/u/0/feed/atom/?timestamp=1430622113043
May 3 11:01:53 - [DEBUG] new_conn_pool conn_num:0
May 3 11:01:55 - [DEBUG] create ssl for direct timeout.
May 3 11:01:56 - [DEBUG] create ssl for direct timeout.
May 3 11:01:56 - [DEBUG] create ssl for direct timeout.

**Comment by cobob** [comment]
关闭自动更新，旧版本还能用可以不用更新，或者你可以同时安装多个版本也不矛盾的。

**Comment by Alucard1797** [comment]
现在就是通过terminal直接使用1.810里的Goagent, 但是连接不是很稳定, 时不时就断开.

**Comment by xxnet** [comment]
新版已恢复正常
