### ISSUE TITLE
这些代码是什么意思啊

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#3210]
177.124.192.115 *.googlevideo.com gws 1544 0 0

**Comment by yeahwu** [comment]
google ip | ip类型 | 延时 | 连接次数

**Comment by fengixng** [comment]
177.124.192.115 → IP
*.googlevideo.com → 这个IP的证书
gws → IP的类型
1544 → IP的延时
0 0 →  连接次数

**Comment by JMaxime** [comment]
感谢
