### ISSUE TITLE
关于XX-Net明文存储密码问题

### ISSUE THREAD

**Issue by byronwwang** [XX-net/XX-Net#3212]
今天在全新安装XX-net是发现，当我输入AppID保存后，自动生成的config.ini下，会有我proxy的账户名和密码信息。难道是XX-net把这些信息都存在运端了？然后根据AppID自动下载配置？这样是否不安全？密码还是明文存储
![qq 20160504193842](https://cloud.githubusercontent.com/assets/6510742/15013077/d33f13ce-122f-11e6-83d5-d42067f17e1e.png)

**Comment by xxnet** [comment]
​一般局域网代理是不需要秘密的，所以此处没有特殊处理。
如有要加秘密，也必须是可逆的解密，只是让密码没有那么容易看到而已，并无保密功能。

另外，没有上云端，所有云端都不要信任。

**Comment by byronwwang** [comment]
那它是怎么得到我的相关信息呢？我是全新安装，按理说应该不会从本地获取到。

**Comment by xxnet** [comment]
应该是浏览器自动填写的，这个地方目前没有想到办法避免

**Comment by byronwwang** [comment]
哦，这样啊！thx
