### ISSUE TITLE
xtunnel无法使用

### ISSUE THREAD

**Issue by Losalado** [XX-net/XX-Net#3214]
xtunnel日志
May 04 20:07:46.979 - [DEBUG] socks5 auth num:1, list:00
May 04 20:07:46.979 - [DEBUG] socks5 auth num:1, list:00
May 04 20:07:46.979 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:07:46.979 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:07:46.979 - [DEBUG] socks5 auth num:1, list:00
May 04 20:07:46.979 - [DEBUG] socks5 auth num:1, list:00
May 04 20:07:46.980 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:07:46.980 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:07:46.980 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:07:46.980 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:07:46.981 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:07:46.981 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:07:46 - [INFO]LOG_EXCEPT: Socks4:('127.0.0.1', 4714) to 203.98.7.65:443, conn_id:1, Except:[Errno 9] Bad file descriptor
May 04 20:07:57.414 - [DEBUG] roundtrip time:10431 cost:10107 transfer_no:1 send_sn:1 send:30 recv_sn:0 rcv:11 status:200
May 04 20:07:57.742 - [DEBUG] roundtrip time:10759 cost:10015 transfer_no:2 send_sn:2 send:531 recv_sn:0 rcv:11 status:200
May 04 20:07:59.707 - [DEBUG] socks5 auth num:1, list:00
May 04 20:07:59.707 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:07:59.707 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:03.822 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:03.822 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:03.822 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:11.882 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:11.882 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:11.882 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:12.142 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:12.142 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:12.142 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:16.652 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:16.652 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:16 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail , Except:[Errno 9] Bad file descriptor
May 04 20:08:16.983 - [DEBUG] Conn session:fpcmmdkc conn:1 stop:recv fail.
May 04 20:08:16.983 - [DEBUG] remove conn_id:1
May 04 20:08:17.343 - [DEBUG] roundtrip time:359 cost:54 transfer_no:3 send_sn:3 send:25 recv_sn:1 rcv:37 status:200
May 04 20:08:17.343 - [DEBUG] DATA conn_id 1 not in list
May 04 20:08:21.349 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:21.349 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:21.349 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:21.554 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:21.554 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:21.554 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.126 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.126 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.126 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.126 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.126 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.126 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.126 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.128 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.127 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.128 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail , Except:[Errno 9] Bad file descriptor
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.128 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.128 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:25.129 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.129 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.130 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.130 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.130 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail , Except:[Errno 9] Bad file descriptor
May 04 20:08:25.130 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.130 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.131 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.131 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.131 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.131 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.131 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.131 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.132 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:25.132 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:29.311 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:29.311 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:29.311 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:29.311 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:29.311 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:29.311 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:29.708 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:29.708 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:29.708 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:33.824 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:33.824 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:33.824 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:50.811 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:50.811 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:50.811 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:51.807 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:51.807 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:51.808 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:51.808 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:51.808 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:51.808 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:51.808 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:51.809 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:51.809 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:51 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail , Except:[Errno 9] Bad file descriptor
May 04 20:08:51.809 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:51.809 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
May 04 20:08:51.879 - [DEBUG] socks5 auth num:1, list:00
May 04 20:08:51.879 - [ERROR] socks5 protocol error:error('recv fail',)
May 04 20:08:51.879 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail

**Comment by xxnet** [comment]
​如果有迅雷，先关掉。

你的浏览器是什么？代理插件是什么，把GAE的诊断信息贴出来看看

**Comment by Ethan-Zocer** [comment]
迅雷关掉也没有用，需要重启吗？浏览器是chrome，代理是SwitchyOmega，诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.4

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:133 good:81
network-status: OK
connected-link: new:5 used:0
worker: h1:3 h2:65
scan-ip-thread-num: 50
ip-quality: 493
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​前面有几个反馈，就是迅雷导致的。
SS也有遇到。

你可以试试重启，或者先卸载，看看是不是因为迅雷。
据说新版的迅雷就解决了这个问题

**Comment by Ethan-Zocer** [comment]
谢谢，我试试

**Comment by Cat7373** [comment]
其实迅雷退出之后还有个迅雷下载服务在后台偷偷运行。。

**Comment by Cat7373** [comment]
完结撒花🎉

**Comment by xxnet** [comment]
好久不见 @Cat7373
