### ISSUE TITLE
下载的视频为什么老是32M

### ISSUE THREAD

**Issue by jackguo007** [XX-net/XX-Net#322]
我改了里面的GAE 的mixsize 啊，里面是4×1024×1024   算起来是4M吧，我还专门把它改成1G的还是不可以，到底是哪里出了问题呢？新版本也是，老版本也是一直都是32M?

**Comment by Sherman-Liu** [comment]
同问啊......下载的视频总是不完全......

**Comment by yqfang** [comment]
这个问题对我很重要！顶一下吧
