### ISSUE TITLE
除了修改缓冲块大小，还能修改什么参数以提升缓冲

### ISSUE THREAD

**Issue by wzdnzd** [XX-net/XX-Net#3220]
用的XX-net3.15，上YouTube时连接速度明显高于我的goproxy，可是还是没有gp流畅，有时候连接速度50000+都还会卡，发现Buffer Health明显不如gp，可是看了一下，两个的buffer size一样大的啊。请问该怎么修改？谢谢。 @xxnet

**Comment by xxnet** [comment]
​估计还是python Queue实现的延迟问题，等稳定了，我再把rangeFetch改了。

**Comment by wzdnzd** [comment]
谢谢

**Comment by wzdnzd** [comment]
![v5 d 288m y_qofgx 9 5m9](https://cloud.githubusercontent.com/assets/8565764/15036084/fe2c2940-12bc-11e6-9342-722da25d690f.png)

**Comment by jeremy0714** [comment]
![qq 20160505143339](https://cloud.githubusercontent.com/assets/12095602/15037559/d622717c-12ce-11e6-8444-c8df2ee6fc31.png)
 

同样 只开480p的质量  几秒卡一下

**Comment by jzp820927** [comment]
我去，2W+，还有比这个更 BT 的麽

**Comment by wzdnzd** [comment]
我的好多时候还能飙到5W+。。。可是看视频还是卡

**Comment by jzp820927** [comment]
好吧，你们都超神了，我还生活中原始社会
