### ISSUE TITLE
Configure GAEProxy里的 Advanced options中，Enable IPv6(If it's available)是啥意思

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#3226]
有什么好处吗

**Comment by Cat7373** [comment]
如果你看不懂英文，建议把语言改成简体中文。
下面的页面里有语言配置
http://127.0.0.1:8085/?module=launcher&menu=config

**Comment by HappysurfBlocking** [comment]
一般教育网用的，普通网络用不到

**Comment by nly4lov** [comment]
看得懂英文，非常地看得懂。只是不明白开IPv6有什么用呀

**Comment by jzp820927** [comment]
给有 IPV6 网络环境用的，一般是局域网，普通用户都不用开启

**Comment by nly4lov** [comment]
我们现在不都是局域网吗

**Comment by jzp820927** [comment]
打错字了，是 教育网，不是局域网

**Comment by nly4lov** [comment]
我
![11](https://cloud.githubusercontent.com/assets/11325411/15091274/59c69bfe-1476-11e6-88b8-ca60003249c5.gif)
服了

**Comment by jzp820927** [comment]
拼音输入法，你懂滴

**Comment by zzgpku** [comment]
ipv6速度快啊，Y2B 1080P完全没问题

**Comment by nly4lov** [comment]
![Uploading e103.gif…]()

**Comment by nly4lov** [comment]
![e103](https://cloud.githubusercontent.com/assets/11325411/15092080/8546e6d8-1491-11e6-91a5-afbf0a8692af.gif)
