### ISSUE TITLE
问：最近因何更新如此频繁？

### ISSUE THREAD

**Issue by Occhi14** [XX-net/XX-Net#323]
问：最近因何更新如此频繁？不更新就连不过去。
       为何不推送···

**Comment by Cat7373** [comment]
...
因为现在分测试版跟稳定版，以及长期稳定版
默认是更新长期稳定版
而长期稳定版现在还没推出过，当然不会自动更新

**Comment by Occhi14** [comment]
猫大师，您好。
请问，现在推荐用哪个型号？求稳定，快速。

**Comment by Cat7373** [comment]
因为我个人平时偶尔会给这个项目提交一些代码之类的
所以基本上我会存多个版本
目前我用的最多的是1.12.3，懒得更新到1.12.5- -
推荐你自动更新稳定版就可以- -

**Comment by Occhi14** [comment]
最近这两天，很慢很慢，不然就是掉线··

**Comment by Cat7373** [comment]
不会啊，1.13.3直接从官网下载下来就很好用的啊- -
打开一会就能找到一堆可用IP了- -
啥配置都不需要改- -

**Comment by Occhi14** [comment]
我这不行(+﹏+)~

**Comment by Cat7373** [comment]
XX-Net一直以来不就是在改善易用性么- -
基本上就是开箱即用

要是只是为了能翻粗去
那只需要像Gogo-Tester一样做个扫IP的就可以了- -

**Comment by biweijie751107089** [comment]
有GoAgent+Gogo Tester的话这个程序就意义不大了是吗

**Comment by Cat7373** [comment]
Goagent更像是一个工具性质的东西 什么都得自己去改配置文件 操作复杂 小白难以研究懂
XX-Net正是在改善这些东西
