### ISSUE TITLE
webui 无法启动 mac 10.11.4, 最新版xxnet

### ISSUE THREAD

**Issue by andmix** [XX-net/XX-Net#3230]
点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。
### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。
#### 获取诊断信息

点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。
#### 获取日志

打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---

请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by yeahwu** [comment]
先查看8087和1080端口有没有被占用？

**Comment by yeahwu** [comment]
先查看8087和1080端口有没有被占用？

**Comment by andmix** [comment]
8087 8085 都没占用 ，可以翻墙 就是没有webui

**Comment by yeahwu** [comment]
确认ss没有占用1080端口后，地址栏输入127.0.0.1:8085试试

**Comment by andmix** [comment]
可以了 多谢大哥  shadowsocks占了1080 ...
