### ISSUE TITLE
V3 全部版本只能在本地用？

### ISSUE THREAD

**Issue by newcastlecy** [XX-net/XX-Net#3235]
监听代理	0.0.0.0:8087
PAC自动代理地址	http://0.0.0.0:8086/proxy.pac

其他的主机只可以打开pac地址，

未连接到互联网

代理服务器出现问题，或者地址有误。
请试试以下办法：
检查代理服务器地址
联系系统管理员
ERR_PROXY_CONNECTION_FAILED

**Comment by Pd69bq** [comment]
listen 0.0.0.0 跟 listen 127.0.0.1 没区别的

**Comment by jzp820927** [comment]
看看 proxy.pac 里面的代理地址，是不是 127.0.0.1

**Comment by zjhzxhz** [comment]
局域网内表示没有问题。

@Pd69bq 你的说法不对。显然有大大的区别。

**Comment by newcastlecy** [comment]
3.1.7 已正常
