### ISSUE TITLE
有一个xxnet改变的问题

### ISSUE THREAD

**Issue by littlebigdream** [XX-net/XX-Net#3236]
@xxnet 
请问大大，xxnet 以后会考虑舍弃goagent，改用goproxy吗？
感觉goproxy性能要好一些。。。。

**Comment by jzp820927** [comment]
都不是一个语言的咚咚，除非 XX 改用 GO 。

**Comment by phuslu** [comment]
感觉这个东东一点都不可靠。楼主别发这种 FUD 帖子了。除了引发口水贴毫无益处。

http://wapbaike.baidu.com/view/815678.htm

**Comment by Wrecking-Ball** [comment]
@phuslu  
只是问问，别无他意。。
好的，下次提问题，想清楚再问。。。

**Comment by phuslu** [comment]
goproxy 在我看来还非常稚嫩，无奈作为新生事物的确会受到一些高于实际的褒扬。
而「经验」表明，大多数软件在“成熟”以后都会「感觉」变慢，这已形成了大众心理预期。

所以讨论此类话题，绝对不能以「感觉」说话，而且也要拿成熟度相同的软件比较。

FUD 的用辞极易引起口水贴，切切。

**Comment by xxnet** [comment]
抛开老的系统，重新搭建一个平台，需要解决的问题非常多，Plus Lu 辛苦了，加油！

**Comment by jzp820927** [comment]
这是第一次，X大和P大0距离接触。

**Comment by simonasd** [comment]
路过围观P大

**Comment by zjhzxhz** [comment]
哇哦~~！

**Comment by pgz123** [comment]
x大也要加油

**Comment by magnet1215** [comment]
在 github的第一帖 就贡献在这里了，围观P大和X大，献上满满的仰慕

**Comment by fuding** [comment]
围观！
