### ISSUE TITLE
[WARNING] no gws ip

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#324]
用着用着突然`Google IP`只剩下`78`. 之前是`2999`. 
这也太夸张了吧.

# Status

| Property            | Value                                                                                                       |
| ------------------- |-------------------------------------------------------------------------------------------------------------|
| Sys Platform        | linux2                                                                                                      |
| OS System           | Linux                                                                                                       |
| OS version          | #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13)                                                                    |
| OS release          | 3.16.0-4-amd64                                                                                              |
| OS detail           | Dist:debian; Version:8.0; ID:                                                                               |
| language            | en_US                                                                                                       |
| architecture        | 64bitELF                                                                                                    |
| Browser             | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36    |
| XX-Net Version      | 1.13.3                                                                                                      |
| Launcher Version    | 1.4.0                                                                                                       |
| GoAgent Version     | 3.1.49                                                                                                      |
| Python Version      | 2.7.9                                                                                                       |
| Proxy Listen        | 127.0.0.1:8087                                                                                              |
| working appids      | ????????                                                                                                    |
| Out of Quota appids |                                                                                                             |
| Not Exist appids    |                                                                                                             |
| PAC URL             | http://127.0.0.1:8086/proxy.pac                                                                             |
| Google IP           | 77                                                                                                          |
| connected link      | 0,0                                                                                                         |
| ip-connect-interval | 10                                                                                                          |
| block stat          | OK                                                                                                          |

# Log

```
May 3 22:07:57 - [WARNING] no gws ip
May 3 22:07:57 - [DEBUG] create_ssl update ip:210.242.125.45 time:3462
May 3 22:07:57 - [DEBUG] create_ssl update ip:64.233.162.81 time:653
May 3 22:07:57 - [DEBUG] get ip:222.255.120.19 t:1933
May 3 22:07:57 - [DEBUG] create_ssl 210.242.125.45 fail: certficate is none cost:4012 h:3462
May 3 22:07:57 - [DEBUG] create_ssl update ip:58.145.238.59 time:3014
May 3 22:07:57 - [DEBUG] create_ssl 58.145.238.59 fail: certficate is none cost:3217 h:3014
May 3 22:07:57 - [DEBUG] create_ssl update ip:210.242.125.50 time:1610
May 3 22:07:58 - [DEBUG] get ip:210.242.125.49 t:2045
May 3 22:07:58 - [DEBUG] get ip:193.120.166.95 t:2114
May 3 22:07:58 - [WARNING] gae_handler err:error(32, 'Broken pipe') https://live.github.com/_sockets/MTczMDUwNDo1ZWIwYmY2MTRlYjU2M2Q0ZjJjN2Y3NjA4ZmQ5Njc3NjoyMTgzYjRhNGRjZDJiOWRmYjVlYWMyZjU2ZTZhMzExODVlZWQ1MGE3NjcwNDAxNjBiMmE5ZTA1NDliZDBmZmVh--2b54b71000e75c3e9bc6c156f2bd09cf4039afdd 
May 3 22:07:58 - [DEBUG] get ip:222.255.120.57 t:2227
May 3 22:07:58 - [DEBUG] get ip:210.242.125.24 t:2425
May 3 22:07:59 - [WARNING] no gws ip
May 3 22:08:00 - [DEBUG] get ip:64.233.164.18 t:2200
May 3 22:08:00 - [DEBUG] create_ssl update ip:193.120.166.95 time:672
May 3 22:08:00 - [DEBUG] create_ssl update ip:222.255.120.19 time:2002
May 3 22:08:00 - [DEBUG] create_ssl 222.255.120.19 fail: certficate is none cost:3099 h:2002
May 3 22:08:00 - [DEBUG] create_ssl update ip:222.255.120.57 time:1683
May 3 22:08:01 - [DEBUG] create_ssl update ip:210.242.125.49 time:2716
May 3 22:08:01 - [DEBUG] create_ssl 210.242.125.49 fail: certficate is none cost:2818 h:2716
May 3 22:08:01 - [DEBUG] sort ip time:0
May 3 22:08:01 - [DEBUG] get ip:202.65.246.113 t:2202
May 3 22:08:01 - [DEBUG] get ip:31.7.160.244 t:2202
May 3 22:08:01 - [INFO] GAE CONNECT github.com:443 
May 3 22:08:01 - [DEBUG] GAE CONNECT POST https://github.com/preview?repository=29290473
May 3 22:08:01 - [DEBUG] ssl_pool.get:64.233.162.81 handshake:1844
May 3 22:08:01 - [DEBUG] get ip:64.233.164.104 t:2200
May 3 22:08:01 - [DEBUG] create_ssl update ip:210.242.125.24 time:2766
May 3 22:08:01 - [DEBUG] create_ssl 210.242.125.24 fail: certficate is none cost:2849 h:2766
May 3 22:08:02 - [DEBUG] get ip:95.143.84.174 t:2501
May 3 22:08:02 - [INFO] GAE t:834 s:146 200 https://github.com/preview?repository=29290473
May 3 22:08:02 - [DEBUG] create_ssl update ip:64.233.164.18 time:2001
May 3 22:08:02 - [DEBUG] create_ssl 64.233.164.18 fail: certficate is none cost:2386 h:2001
May 3 22:08:02 - [WARNING] no gws ip
May 3 22:08:03 - [DEBUG] create_ssl 31.7.160.244 fail:timed out cost:2002 h:0
May 3 22:08:03 - [INFO] remove ip:31.7.160.244 left amount:78 gws_num:77
May 3 22:08:03 - [DEBUG] create_ssl update ip:202.65.246.113 time:2002
May 3 22:08:03 - [DEBUG] create_ssl 202.65.246.113 fail: certficate is none cost:2263 h:2002
May 3 22:08:04 - [WARNING] gae_handler err:error(32, 'Broken pipe') https://live.github.com/_sockets/MTczMDUwNDo1ZWIwYmY2MTRlYjU2M2Q0ZjJjN2Y3NjA4ZmQ5Njc3NjoyMTgzYjRhNGRjZDJiOWRmYjVlYWMyZjU2ZTZhMzExODVlZWQ1MGE3NjcwNDAxNjBiMmE5ZTA1NDliZDBmZmVh--2b54b71000e75c3e9bc6c156f2bd09cf4039afdd 
May 3 22:08:04 - [DEBUG] get ip:64.233.179.200 t:702
May 3 22:08:04 - [DEBUG] create_ssl update ip:64.233.164.104 time:2002
May 3 22:08:04 - [DEBUG] create_ssl 64.233.164.104 fail: certficate is none cost:3006 h:2002
May 3 22:08:05 - [WARNING] no gws ip
May 3 22:08:05 - [DEBUG] create_ssl update ip:95.143.84.174 time:2002
May 3 22:08:05 - [DEBUG] get ip:64.233.162.86 t:1255
May 3 22:08:05 - [DEBUG] create_ssl 95.143.84.174 fail: certficate is none cost:3666 h:2002
May 3 22:08:05 - [DEBUG] create_ssl update ip:64.233.179.200 time:838
May 3 22:08:06 - [DEBUG] get ip:31.209.137.59 t:1303
May 3 22:08:06 - [DEBUG] get ip:210.242.125.50 t:1610
May 3 22:08:06 - [DEBUG] get ip:64.233.164.149 t:2201
May 3 22:08:07 - [DEBUG] create_ssl update ip:64.233.162.86 time:951
```

**Comment by EdwardDX** [comment]
发生同样情况，Google Ip 以减少到209个，而且频繁被 Block，希望早点作出改进。

**Comment by xxnet** [comment]
1.13.4, 改进连接质量，希望对你有用

在 2015年5月3日 下午9:20，EdwardDX <notifications@github.com>写道：
