### ISSUE TITLE
伊利社区上不去

### ISSUE THREAD

**Issue by chepirate** [XX-net/XX-Net#3246]
---
## 问题内容
1. 伊利社区上不去，总是显示www04.eyny.com 将您重定向的次数过多。

#### 获取诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36
xxnet-version: 3.1.4

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:29 good:18
network-status: OK
connected-link: new:0 used:0
worker: h1:9 h2:4
scan-ip-thread-num: 50
ip-quality: 1149
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志
May 07 11:35:34.129 - [INFO] GAE t:588 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:34.754 - [INFO] GAE t:598 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:35.380 - [INFO] GAE t:612 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:35.974 - [INFO] GAE t:578 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:36.568 - [INFO] GAE t:581 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:37.556 - [INFO] GAE t:960 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:38.153 - [INFO] GAE t:581 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:38.769 - [INFO] GAE t:592 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:39.398 - [INFO] GAE t:599 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:40.001 - [INFO] GAE t:585 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:40.625 - [INFO] GAE t:592 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:41.145 - [INFO] scan_ip add ip:217.18.145.114 time:332
May 07 11:35:41.253 - [INFO] GAE t:598 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:41.863 - [INFO] GAE t:586 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:42.484 - [INFO] GAE t:603 s:26 GET http://www04.eyny.com/index.php
May 07 11:35:48.309 - [INFO] scan_ip add ip:92.87.11.33 time:664
May 07 11:35:52.997 - [INFO] GAE CONNECT clients4.google.com:443
May 07 11:35:53.034 - [DEBUG] GAE CONNECT POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJIaVozM2xrb3FBbFlsOUlYMTZTMnNnc0VkUlg0bnNSYmpjWjhJV3hfek5WelZNTVRyRGw5djlXNXRPNkdmbFpqdms2WUVvaTBrLXRUV0QyVDlxNkJKQnVZRFlZb0wxSGZ6Q2NZN1M4TjlsSktGRl82eEp6eHJHR3IyYTRuTHM1bmNsbkc1YTBxZmNVRVRNb1NOMGZGMExVd3VUZVZQbGhBTHF4UnZGeXN2SVVjcHpCVkEaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM
May 07 11:35:54.078 - [INFO] GAE t:1042 s:0 POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJIaVozM2xrb3FBbFlsOUlYMTZTMnNnc0VkUlg0bnNSYmpjWjhJV3hfek5WelZNTVRyRGw5djlXNXRPNkdmbFpqdms2WUVvaTBrLXRUV0QyVDlxNkJKQnVZRFlZb0wxSGZ6Q2NZN1M4TjlsSktGRl82eEp6eHJHR3IyYTRuTHM1bmNsbkc1YTBxZmNVRVRNb1NOMGZGMExVd3VUZVZQbGhBTHF4UnZGeXN2SVVjcHpCVkEaACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM
May 07 11:35:58.380 - [INFO] scan_ip add ip:203.165.14.231 time:506

---

**Comment by vSolo** [comment]
#2853

**Comment by jzp820927** [comment]
这个是 伊利社区 对GAE 的请求处理有问题，wiki 有说明，和XX 没关系

**Comment by lele2010lele** [comment]
伊利社区有啥？

**Comment by chepirate** [comment]
好的，我会去看看，谢谢各位，
