### ISSUE TITLE
google的时候经常要输入验证码，何解

### ISSUE THREAD

**Issue by bighzl** [XX-net/XX-Net#3253]
google的时候，输入关键字回车后，经常会跳到一个输入验证码的界面，输完验证码才能返回搜索结果，验证码界面是google官方的

想搞清楚为什么
切换ip太频繁被认定不合理了？？

XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016
os-release: 4.4.0-22-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.36 Safari/537.36
xxnet-version: 3.1.6

python-version: 2.7.11+
openssl-version: 0.15.1 TLSv1_2 h2:npn

ipv6-status: 0
gws-ip-num: total:2804 good:2100
network-status: OK
connected-link: new:0 used:0
worker: h1:16 h2:4
scan-ip-thread-num: 10
ip-quality: 159
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yeahwu** [comment]
这个问题老早在xx上已经解决了哇！怎么又回来鸟

**Comment by bighzl** [comment]
新手..见谅

**Comment by yeahwu** [comment]
XX-Net/code/default/gae_proxy/local/proxy.ini文件中
；.google.com = direct
前面的注释去掉，试试

**Comment by ztmdsbt** [comment]
@bighzl , 问题如果解决了记得关闭issue.

**Comment by bighzl** [comment]
谢了=。=
