### ISSUE TITLE
 无法部署服务端

### ISSUE THREAD

**Issue by sunkinds** [XX-net/XX-Net#326]
无法部署服务端May 04 10:23:00 - Retry 28 time...

May 04 10:23:27 - Application: gdsgsdg2015
May 04 10:23:27 - Host: appengine.google.com
May 04 10:23:27 - Rolling back the update.
May 04 10:23:47 - upload fail: The read operation timed out

May 04 10:23:47 - Retry 29 time...

May 04 10:24:15 - Application: gdsgsdg2015
May 04 10:24:15 - Host: appengine.google.com
May 04 10:24:15 - Rolling back the update.

**Comment by jackwei86** [comment]
我跟你遇到相同的问题,retry 10次就出一堆信息然后就也没成功

**Comment by xxnet** [comment]
部署前，请看看能否访问appengine.google.com

新版1.13.4，改善链接性能，刚才测试部署没有问题，请测试

2015-05-04 3:37 GMT-04:00 jackwei86 <notifications@github.com>:

**Comment by redstoneleo** [comment]
1.13.5 测试通过，话说这个版本访问https://books.google.com.hk/books?id=AQEMCAAAQBAJ&pg=PA54&lpg=PA54&dq=infinitely+large+quantity&source=bl&ots=MeTEApaSSa&sig=UXRSBiDVnuV_epuiXL3J_Y4DN94&hl=zh-CN&sa=X&ei=bodIVdWPKcG8mgWNp4GQBA&ved=0CEIQ6AEwBQ#v=onepage&q=infinitely%20large%20quantity&f=false

老是提示超时啊，求解决

**Comment by jackwei86** [comment]
拿最新的测试版的可以打开你上面这个网站啊
