### ISSUE TITLE
关于路由上manual.ini配置文件是否限制h2连接问题

### ISSUE THREAD

**Issue by weiwei007** [XX-net/XX-Net#3266]
在梅林固件上安装xxnet3.17！配置手动文件！感觉一样版本在电脑上面用没有配置文件，吧路由上ip文件放在电脑板上直接扫描ip速度很快延时也低，而且显示h2连接数，但是路由上面h2一直显示为0！是路由openssl版本太低了吗！还是手动配置文件限制了！
[listen]
ip = 0.0.0.0
port = 8087
visible = 1
debuginfo = 0
    
[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
;adblock = http://adblock-chinalist.googlecode.com/svn/trunk/adblock.txt
; this project have stopped.
expired = 86400
    
[autorange]
threads = 8
maxsize = 524288
waitsize = 1048576
bufsize = 65535
    
[google_ip]
use_ipv6 = 0
auto_adjust_scan_ip_thread_num = 1
max_scan_ip_thread_num = 50
max_good_ip_num = 3000
ip_connect_interval = 8
max_links_per_ip = 3
    
; traffic quota: 100k/second
ip_traffic_quota = 100000
ip_traffic_quota_base = 100000
    
[connect_manager]
https_max_connect_thread = 10
https_connection_pool_min = 5
https_connection_pool_max = 50

路由版本状态

属性	值
本地网络状态	OK
IP数量	111
空闲	0
IP延迟	606
连接池(帮助)	新:8 h1:95 h2:0
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK
系统版本

属性	值
XX-Net Version	3.1.7
Python Version	2.7.11
OpenSSL Version	0.13.1 TLSv1 h2:no
System Platform	armv7l, Linux-2.6.36.4brcmarm-armv7l-with-glibc2.4
OS System	Linux
OS Version	#9 SMP PREEMPT Tue Dec 15 12:56:43 CST 2015
OS Release	2.6.36.4brcmarm
OS Detail	Dist:; Version:; ID:
Language	
Architecture	32bit,
Browser	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by jzp820927** [comment]
OpenSSL Version 0.13.1 TLSv1 h2:no

**Comment by weiwei007** [comment]
扫描ip慢是不是路由器性能，或者手动配置限制呢

**Comment by jzp820927** [comment]
扫描慢，你可以试试 调高线程，不过怕你路由器遭不住

**Comment by pm19960106** [comment]
@jzp820927 h2:no改怎么弄呢

**Comment by jzp820927** [comment]
@pm19960106 是 openssl 版本太低的问题，要升级 openssl，这个估计得你自己折腾了
