### ISSUE TITLE
我自动更新打开了额为什么 xx 不会自动更新？

### ISSUE THREAD

**Issue by sonlia** [XX-net/XX-Net#327]
我自动更新打开了额为什么 xx 不会自动更新？

**Comment by gmzlxx** [comment]
我的也是

**Comment by xxnet** [comment]
你是什么版本？

1.13 后面增加了新的更新规则，请参考这里：
https://github.com/XX-net/XX-Net/wiki/Auto-update

2015-05-03 22:26 GMT-04:00 sonlia <notifications@github.com>:

**Comment by sonlia** [comment]
我的是 1.10.1，有点强迫症  想一直更新到最新  哈哈 ，更新规则我看了 谢谢

**Comment by sonlia** [comment]
哈哈 最新版太帅了
