### ISSUE TITLE
BLOCK有没有用啊？能不能设置个开关，不需要BOLOCK行不行？

### ISSUE THREAD

**Issue by Ghostsnail** [XX-net/XX-Net#328]
如题，不然老在BLOCK，用不了啊都

**Comment by Cat7373** [comment]
XX-Net/goagent/3.1.49/local/connect_control.py

block_delay = (60 * 5)

修改为

block_delay = 0

**Comment by Ghostsnail** [comment]
改过了，只是觉得让它不做这个判断岂不是更好？

**Comment by Cat7373** [comment]
我不是开发者
这种对于核心的修改，我并不知道会导致什么后果
因此只能是告诉你怎么改能让Block失效
而不是增加一个Block开关

**Comment by xxnet** [comment]
此处确实存在bug，每次block之后，没有复位， 会进入死循环，没有起到设定的目标。

改动太匆忙，没有好好思考过。
新版发布，1.13.4，主要对链接的策略和一些参数进行调整，对比了之前的版本，这个版本的链接性能改进了不少。

在 2015年5月4日 上午7:43，Cat73 <notifications@github.com>写道：
