### ISSUE TITLE
希望xtunnel监听端口和地址可自行设定

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#3280]
希望可自定,不要硬编为127.0.0.1:1080

具体有两点
1.可自行设定监听127.0.0.1或0.0.0.0
2.可自行设定监听的端口号

**Comment by jzp820927** [comment]
config.ini 可以改

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/blob/master/code/default/x_tunnel/local/client.py#L79
这里改

**Comment by wpyok500** [comment]
![image](https://cloud.githubusercontent.com/assets/14154547/15105246/ac0798f0-15f2-11e6-9175-413f34622184.png)

**Comment by wooowooo** [comment]
多谢@yeahwu @wpyok500 , 但是
尽管改client.py能改掉地址和端口,但仍然是硬编码,并不能完全达到我所说的
我所说的是 不要硬编码, 可自定
可自定的既是设定应该被保存在data里,升级程序后仍然生效的

@jzp820927 该怎么改?请指示

**Comment by jzp820927** [comment]
说错了，是 data/x_tunnel/client.json 这个文件

{
  "socks_host": "0.0.0.0",

但是只能改 监听，端口不知道支不支持在这个文件改，问问X大吧

**Comment by xxnet** [comment]
都可以改动的，没有硬编码。


{
"socks_host": "0.0.0.0",
"socks_port“: ”1080“,
}

自己改吧

**Comment by jzp820927** [comment]
好吧，其实我以前试着添加过 socks_port ，不过当时没生效，看来现在是有效了。

**Comment by wooowooo** [comment]
试了,确实可以,不过上面xxnet提供的配置打错了,应该是
"socks_host": "0.0.0.0",
  "socks_port": 1080
没有引号的

**Comment by jzp820927** [comment]
加个引号，应该也不会出错吧，这是json 格式

**Comment by yeahwu** [comment]
俺只要一添加，web页面就无法打开
