### ISSUE TITLE
3.19版谷歌浏览器应用商店插件无法下载

### ISSUE THREAD

**Issue by weiwei007** [XX-net/XX-Net#3285]
3.19版可以正常访问谷歌浏览器商店，但是下载应用显示不成功,浏览器版本版本 50.0.2661.94 m！
但是用360极速又可以正常下载！Proxy SwitchyOmega设置完全一样！xxnet用都是默认设置，appid用的自己滴！

**Comment by xxnet** [comment]
​按F12，看控制台有什么异常日志

看GAE_proxy的日志，有什么异常日志

贴出来分析
