### ISSUE TITLE
mac还是无法使用h2

### ISSUE THREAD

**Issue by withwind8** [XX-net/XX-Net#3286]
版本3.1.7
已经brew install python及pip install pyOpenSSL
python -c 'import OpenSSL; print(OpenSSL.SSL.OPENSSL_VERSION_NUMBER > 0x1000200)' 2> /dev/null | grep True | wc -l
输出为1
但还是0.13 TLSv1 h2:no
能上网，但就是感觉很不爽＝。＝

XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.7

python-version: 2.7.10
openssl-version: 0.13 TLSv1 h2:no

ipv6-status: 0
gws-ip-num: total:4084 good:824
network-status: OK
connected-link: new:4 used:0
worker: h1:45 h2:0
scan-ip-thread-num: 50
ip-quality: 112
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxx233** [comment]
卸掉pyOpenSSL试试，就是自带的pyOpenSSL的祸

**Comment by withwind8** [comment]
@xxx233 
你说的卸掉pyOpenSSL是指什么
我用pip uninstall pyOpenSSL
启动检测都过不了，看代码又跳回系统自带的python了，仍然是0.13 TLSv1 h2:no

**Comment by xxx233** [comment]
rm:pyOpenSSL

**Comment by withwind8** [comment]
@xxx233 
不好意思，我不知道rm:openssl怎么用，提示找不到命令
确实openssl命令是系统的
$ which openssl
/usr/bin/openssl
$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
我用brew link openssl --force把brew的openssl链接过去
$ which openssl
/usr/local/bin/openssl
$ openssl version
OpenSSL 1.0.2h  3 May 2016

但打开xx-net还是OpenSSL Version	0.13 TLSv1 h2:no

**Comment by cc941201** [comment]
之前有版本是可以的

刚才试了一下，删除xxnet自带的pyopenssl for mac就可以：`code/default/python27/1.0/lib/darwin/OpenSSL`

**Comment by cc941201** [comment]
不过虽然有h2了，但却什么都打不开，日志里都是
`worker close:recv fail:TypeError("int() argument must be a string or a number, not 'list'",)`

**Comment by mk123789** [comment]
我刚删了还是h2:no,和以前一样

**Comment by mk123789** [comment]
自从用了xxnet都是h2:no

**Comment by puercha** [comment]
求解决啊，mac下的表现比windows下差太多了

**Comment by mk123789** [comment]
哎，一样也想用用h2

**Comment by cc941201** [comment]
3.1.12已发布，我在多个OS X 10.11.4测试过可以用h2，请大家测试一下。

**Comment by jzp820927** [comment]
土豪啊，居然还有多个 OSX

**Comment by withwind8** [comment]
3.1.13测试ok，终于可以愉快的玩耍了，感谢 @cc941201 的pr，感谢 @xxnet 
连接池(帮助)	新:1 h1:0 h2:57
OpenSSL Version	16.0.0 TLSv1 h2:alpn
