### ISSUE TITLE
看非youtube视频网站出问题

### ISSUE THREAD

**Issue by kingour** [XX-net/XX-Net#329]
报502，换成goagent就可以了，不知道怎么回事

**Comment by xxnet** [comment]
收到

2015-05-03 23:02 GMT-04:00 Kingour <notifications@github.com>:

**Comment by xxnet** [comment]
1.13.6解决了xvideo部分视频下载问题，
需要重新部署服务端。

请测试。

2015-05-04 9:00 GMT-04:00 Net XX <xxnet.dev@gmail.com>:

**Comment by causlayer** [comment]
希望下次升级时需要重新部署服务端的时候能注明一下，谢谢

**Comment by xxnet** [comment]
项目主页上有说明，不过似乎不够醒目。



在 2015年5月7日 下午1:29，causlayer <notifications@github.com>写道：

**Comment by causlayer** [comment]
https://github.com/XX-net/XX-Net/releases，如果能加到这里就更好了：）
