### ISSUE TITLE
系统日志分级

### ISSUE THREAD

**Issue by Sam0523** [XX-net/XX-Net#3295]
journalctl 输出的日志很大一部分都被 XX-Net 占满了，而且全部都是 warning level ，导致几乎看不到其他程序的日志，而且过滤很麻烦。
能否对输出到系统的日志设定正确的 level ？另外是不是可以减少一部分向系统日志的输出？

**Comment by xxnet** [comment]
​好的

**Comment by Sam0523** [comment]
‎谢谢！

**Comment by Sam0523** [comment]
目前似乎输出到系统的日志都是 INFO 级别的？为什么不按照 XX-Net 自己的日志级别分别输出为不同级别的呢？

**Comment by xxnet** [comment]
​没有输出到系统日志吧

**Comment by Sam0523** [comment]
@xxnet 我这里看到的是日志还像以前一样多，只不过变成了 INFO level
版本是3.1.11

**Comment by xxnet** [comment]
​看到了，你应该是用code/default/xx_net.sh 启动的，才会进入到系统日志中。
其实不应该进入系统日志才好，你可以自己修改，把

nohup "${PYTHON}" launcher/start.py 2>&1 | /usr/bin/logger -t
${PACKAGE_NAME} &
改成：
nohup "${PYTHON}" launcher/start.py >/dev/null 2>&1 &

**Comment by Sam0523** [comment]
不，我就是用 start 启动的……或者开机自动启动

其实我不反对把日志写入系统日志的（只要正确分级），不过反正现在最新版已经不向系统日志输出了，这样也挺好的。

**Comment by Sam0523** [comment]
我发现一个奇怪的事情……当我在命令行用 `start` 启动不会向系统输出日志，但是如果是开机自动启动就会（全部都是 WARNING 级别）。可是自动启动也是用 `start` 启动的啊……这是 `~/.config/autostart/XX-Net.desktop` 的内容：
```desktop
[Desktop Entry]
Name=XX-Net
Exec=/home/sam/github/XX-Net/start
Type=Application
Terminal=false
X-GNOME-Autostart-enabled=true
```
是不是命令行程序不在终端中启动的时候向 stdout 的输出就会自动进入日志？

**Comment by xxnet** [comment]
​试试把

Exec=/home/sam/github/XX-Net/start
改成
Exec=/home/sam/github/XX-Net/start >/dev/null 2&>1

**Comment by Sam0523** [comment]
> `Exec=/home/sam/github/XX-Net/start`
> 改成
> `Exec=/home/sam/github/XX-Net/start >/dev/null 2&>1`

应该是 `>/dev/null 2>&1` 或者 `&>/dev/null` 吧？不过我都试了，不行

**Comment by Sam0523** [comment]
这个问题在 3.2.2 依然存在，有没有谁比较懂的来看一下……谢了
