### ISSUE TITLE
3.1.10 发布，请测试

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#3297]
+ 修复3.1.9 版本引入的不断重试bug。
+ 避免建立过多worker

https://github.com/XX-net/XX-Net/releases/tag/3.1.10

请#3277， #3287 
下载3.1.10 测试，到这里反馈

**Comment by Cat7373** [comment]
目前看起来 h1 + h2 始终没超过 30，新没超过 5，应该是没内个问题惹0.0

**Comment by Cat7373** [comment]
新:2 h1:21 h2:10
还是超了。。
31个- -
多 1 个而已0.0
问题不大0.0

**Comment by Cat7373** [comment]
咦 配置文件里似乎限制是 50 个- -

**Comment by Cat7373** [comment]
好吧我只是在没话找话说。。
看看还会不会一下发一串0.0

**Comment by xxnet** [comment]
恩，此处是妥协的策略。
ip没有分h1/h2，因此不知道拿到的ip是h1还是h2，
而连接池希望能够保证有h1的连接，给Direct用。

之前测试过 h2的概率17%，但是还要看每个人的地区和网络，加入某个人的ip全是h2，那么就会导致一直等不到h1，一直在建立连接，导致worker爆多。

所以后面worker管理里再重新限制数量，超过50个，就会开始关闭最慢的worker

**Comment by Cat7373** [comment]
h2 的 IP 应该也可以支持 h1 吧 0.0
不能做下兼容么- -

**Comment by xxnet** [comment]
完美的策略，是ip池里就标记每个ip是否支持h2
然后在需要h1时，去获取h1的ip。

普通情况下，就根据ip的性能，优先挑选最快的。

目前ip挑选的策略还有改进空间：
  当前的策略，仅仅是根据tls握手时间进行计算。
  最近发现，在获取到http头之后，可以比较有依据的计算ip的实际通信速度。
  发现rtt和速度之间并不是绝对相关，甚至相邻的ip，rtt类似，速度也会有较大差别。

完美的方案，要把速度记录到ip信息中，帮助ip进行排序。
暂时的策略还凑合，也不准备做了。

**Comment by xxnet** [comment]
h2的ip，修改tls握手也是可以作为h1用的。

但是目前是尽力去建立h2连接，然后把连接丢进池里，需要的去拿。

要改，就必须把流程改掉，没想好一个清晰的思路，就不想再动了。

**Comment by Cat7373** [comment]
看到了不少这样的日志

May 09 22:08:27.820 - [ERROR] recv fail:ZeroDivisionError('float division by zero',)
May 09 22:08:27.821 - [ERROR] Except stack:Traceback (most recent call last):
    File "E:\tools\\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 181, in recv_loop self._consume_single_frame()
    File "E:\tools\\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 283, in _consume_single_frame self._consume_frame_payload(frame, data)
    File "E:\tools\\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 329, in _consume_frame_payload self.streams[frame.stream_id].receive_frame(frame)
    File "E:\tools\\XX-Net\code\default\gae_proxy\local\http2_stream.py", line 270, in receive_frame speed = self.task.content_length / (time_now - self.get_head_time) ZeroDivisionError: float division by zero

**Comment by keyoushi** [comment]
May 09 22:09:46.308 - [ERROR] recv fail:ZeroDivisionError('float division by zero',)
May 09 22:09:46.309 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 181, in recv_loop self._consume_single_frame() File "D:\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 283, in _consume_single_frame self._consume_frame_payload(frame, data) File "D:\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 329, in _consume_frame_payload self.streams[frame.stream_id].receive_frame(frame) File "D:\XX-Net\code\default\gae_proxy\local\http2_stream.py", line 270, in receive_frame speed = self.task.content_length / (time_now - self.get_head_time) ZeroDivisionError: float division by zero

**Comment by keyoushi** [comment]
用的是3.0.4的data,直接挂了，删了重新扫看看

**Comment by xxnet** [comment]
@Cat7373 
  另一处被0除的，我代码先上，再等等发版本

**Comment by Cat7373** [comment]
该睡觉惹0.0
明天再改也不迟嘛0.0

**Comment by streamgo** [comment]
点击 start 打开选择打开程序列表，估计是关联出问题了。请指教。

**Comment by Cat7373** [comment]
@streamgo 你确定开对了么？
如果不现实后缀名的话，其实应该有三个 start。

**Comment by streamgo** [comment]
@Cat7373 嗯嗯。我说的是没有后缀名的那个。以前我双击它，会自动运行并在桌面建立快捷方式。现在不行了，双击它，会打开选择程序执行它的窗口。

**Comment by keyoushi** [comment]
May 09 22:32:49.843 - [ERROR] req_config_handler except:can't start new thread
May 09 22:32:49.846 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\default\gae_proxy\local\web_control.py", line 508, in req_config_handler google_ip.reset() File "D:\XX-Net\code\default\gae_proxy\local\google_ip.py", line 111, in reset self.search_more_google_ip() File "D:\XX-Net\code\default\gae_proxy\local\google_ip.py", line 662, in search_more_google_ip p.start() File "D:\XX-Net\code\default\python27\1.0\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread
May 09 22:32:49.988 - [ERROR] req_config_handler except:can't start new thread
May 09 22:32:49 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\XX-Net\code\default\gae_proxy\local\web_control.py", line 508, in req_config_handler google_ip.reset() File "D:\XX-Net\code\default\gae_proxy\local\google_ip.py", line 111, in reset self.search_more_google_ip() File "D:\XX-Net\code\default\gae_proxy\local\google_ip.py", line 662, in search_more_google_ip p.start() File "D:\XX-Net\code\default\python27\1.0\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread , Except:[Errno 9] Bad file descriptor
现在google全家桶全上不去

**Comment by Cat7373** [comment]
出现 *ZeroDivisionError('float division by zero',)* 错误的时候，似乎这一次请求会失败。

**Comment by streamgo** [comment]
@Cat7373 不是BAT，也不是VBS的那个。

**Comment by Cat7373** [comment]
@streamgo 那是 Linux 跟 Mac 用的。

**Comment by keyoushi** [comment]
先洗洗睡了，XX辛苦了，大家安安

**Comment by streamgo** [comment]
@Cat7373 好奇怪啊。以前就是可以直接执行它的。晕了。现在连桌面快捷方式都不知道如何建立了。

**Comment by zjgbql** [comment]
bat执行可以建立快捷方式的

**Comment by xxnet** [comment]
@keyoushi
  最后状态页是什么内容，贴出来

**Comment by streamgo** [comment]
@zjgbql 不行 ，我这儿BAT不建立。。。。

**Comment by wpyok500** [comment]
扫不到ip，一大堆黄字
May 09 22:51:11.876 - [INFO] ------------------------------------------------------
May 09 22:51:12.376 - [DEBUG] get ip:61.86.203.119 t:246
May 09 22:51:12.396 - [DEBUG] create_ssl update ip:217.18.145.87 time:369 h2:0
May 09 22:51:12.396 - [DEBUG] get ip:203.176.178.36 t:328
May 09 22:51:12.886 - [DEBUG] get ip:92.246.12.250 t:2243
May 09 22:51:12.946 - [DEBUG] network is ok, cost:2401 ms
May 09 22:51:13.236 - [DEBUG] create_ssl update ip:23.228.130.101 time:890 h2:0
May 09 22:51:13.396 - [WARNING] no enough ip
May 09 22:51:13.556 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
May 09 22:51:13.566 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=75e210a2-6b21-44a1-9cbd-7a020717df20&version=3.1.10&platform=Windows-10-10.0.10586
May 09 22:51:13.936 - [INFO] DIRECT t:370 s:1674 200 xxnet-update.appspot.com /update.json?uuid=75e210a2-6b21-44a1-9cbd-7a020717df20&version=3.1.10&platform=Windows-10-10.0.10586
May 09 22:51:14.916 - [WARNING] no enough ip
May 09 22:51:15.926 - [WARNING] no enough ip
May 09 22:51:16.376 - [DEBUG] 61.86.203.119 fail:timeout('timed out',)
May 09 22:51:16.426 - [DEBUG] 203.176.178.36 fail:timeout('timed out',)
May 09 22:51:16.936 - [WARNING] no enough ip
May 09 22:51:17.946 - [WARNING] no enough ip
May 09 22:51:18.978 - [WARNING] no enough ip
May 09 22:51:18.978 - [DEBUG] report_connect_fail:61.86.203.119
May 09 22:51:18.978 - [DEBUG] report_connect_fail:203.176.178.36
May 09 22:51:18.978 - [WARNING] no enough ip
May 09 22:51:19.194 - [DEBUG] GAE POST https://accounts.google.com/ListAccounts?source=ChromiumBrowser&json=standard
May 09 22:51:20.004 - [WARNING] no enough ip
May 09 22:51:20.384 - [INFO] GAE t:1190 s:181 POST https://accounts.google.com/ListAccounts?source=ChromiumBrowser&json=standard h1_req:104,get_response:517
May 09 22:51:21.010 - [WARNING] no enough ip
May 09 22:51:22.013 - [WARNING] no enough ip
May 09 22:51:23.017 - [WARNING] no enough ip
May 09 22:51:24.021 - [WARNING] no enough ip
May 09 22:51:24.021 - [WARNING] no enough ip
May 09 22:51:24.782 - [INFO] PAC from:127.0.0.1:65033 GET /proxy.pac
May 09 22:51:25.022 - [WARNING] no enough ip
May 09 22:51:26.023 - [WARNING] no enough ip
May 09 22:51:26.107 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
May 09 22:51:26.312 - [DEBUG] GET http://www.twitter.com/xxnet
May 09 22:51:27.023 - [WARNING] no enough ip
May 09 22:51:28.033 - [WARNING] no enough ip
May 09 22:51:29.039 - [WARNING] no enough ip
May 09 22:51:29.039 - [WARNING] no enough ip
May 09 22:51:30.045 - [DEBUG] create_ssl update ip:92.246.12.250 time:6542 h2:0
May 09 22:51:31.048 - [WARNING] no enough ip
May 09 22:51:33.999 - [DEBUG] ip:61.86.203.119 real fail
May 09 22:51:39 - [DEBUG]LOG_EXCEPT: ip:203.176.178.36 real fail, Except:[Errno 9] Bad file descriptor
May 09 22:51:53.815 - [DEBUG] GAEProxy web_control 127.0.0.1:64963 POST /config?cmd=get_config
May 09 22:51:53.927 - [DEBUG] GAEProxy Web_control 127.0.0.1:64963 GET /scan_ip?cmd=get_range
May 09 22:51:53.927 - [INFO] load ip range file:D:\Program Files\XX-Net\code\default\gae_proxy\local\ip_range.txt
May 09 22:51:55.331 - [DEBUG] GAEProxy Web_control 127.0.0.1:64963 GET /scan_ip?cmd=get_scan_ip_log
May 09 22:52:01.224 - [DEBUG] 217.18.145.87 close:host pool alive_timeout
May 09 22:52:01.224 - [DEBUG] ssl_closed 217.18.145.87
May 09 22:52:30.048 - [DEBUG] get ip:217.18.145.87 t:369
May 09 22:52:30.098 - [DEBUG] create ssl timeout fail.
May 09 22:52:31.108 - [WARNING] no enough ip
May 09 22:52:31.108 - [WARNING] no enough ip
May 09 22:52:32.128 - [WARNING] no enough ip
May 09 22:52:33.133 - [WARNING] no enough ip
May 09 22:52:34.143 - [WARNING] no enough ip
May 09 22:52:35.153 - [WARNING] no enough ip
May 09 22:52:36.159 - [WARNING] no enough ip
May 09 22:52:36.159 - [WARNING] no enough ip
May 09 22:52:36.159 - [DEBUG] create_ssl update ip:217.18.145.87 time:340 h2:0
May 09 22:52:37.169 - [WARNING] no enough ip
May 09 22:52:38.179 - [WARNING] no enough ip
May 09 22:52:39.189 - [WARNING] no enough ip
May 09 22:52:40.199 - [WARNING] no enough ip
May 09 22:52:41.204 - [WARNING] no enough ip
May 09 22:52:42.215 - [WARNING] no enough ip
May 09 22:52:43.218 - [WARNING] no enough ip
May 09 22:52:43.584 - [DEBUG] GAEProxy web_control 127.0.0.1:64963 POST /config?cmd=get_config
May 09 22:52:43.588 - [DEBUG] GAEProxy Web_control 127.0.0.1:64963 GET /scan_ip?cmd=get_range
May 09 22:52:43.589 - [INFO] load ip range file:D:\Program Files\XX-Net\code\default\gae_proxy\local\ip_range.txt
May 09 22:52:44.224 - [WARNING] no enough ip
May 09 22:52:45.225 - [WARNING] no enough ip
May 09 22:52:46.235 - [WARNING] no enough ip
May 09 22:52:46.235 - [WARNING] no enough ip
May 09 22:52:47.238 - [WARNING] no enough ip
May 09 22:52:47.238 - [INFO] scan_ip add ip:92.226.2.92 time:1269
May 09 22:52:48.468 - [DEBUG] GAEProxy Web_control 127.0.0.1:64963 GET /scan_ip?cmd=get_scan_ip_log
May 09 22:53:36.179 - [DEBUG] create ssl timeout fail.
May 09 22:53:36.181 - [DEBUG] get ip:92.226.2.92 t:1269
May 09 22:53:37.689 - [WARNING] no enough ip
May 09 22:53:38.690 - [WARNING] no enough ip
May 09 22:53:39 - [WARNING]LOG_EXCEPT: no enough ip, Except:[Errno 9] Bad file descriptor
May 09 22:53:39.691 - [WARNING] no enough ip
May 09 22:53:39.693 - [DEBUG] create_ssl update ip:92.226.2.92 time:778 h2:0
May 09 22:53:40.694 - [WARNING] no enough ip
May 09 22:53:41.695 - [WARNING] no enough ip
May 09 22:53:42.695 - [WARNING] no enough ip
May 09 22:53:43.696 - [WARNING] no enough ip

**Comment by xxnet** [comment]
3.1.11 发布
#3298
没睡的帮忙测试

**Comment by yeahwu** [comment]
这个版本不错，好像解决了h2直连youtube的问题，
然而俺的h2还是超过了50，ip段还有啥的都是默认，h1很少
新:2 h1:0 h2:85

**Comment by zjgbql** [comment]
#xxnet 没睡是没睡,就是只会用,不会反馈,除非是很明显的bug,哈哈

**Comment by zjgbql** [comment]
没睡是没睡,就是只会用,不会反馈,除非是很明显的bug,哈哈
