### ISSUE TITLE
想请问一下andorid 手机上面有没有什么好的解决方案呀？

### ISSUE THREAD

**Issue by angel126** [XX-net/XX-Net#33]
想请问一下andorid 手机上面有没有什么好的解决方案呀？

**Comment by xxnet** [comment]
Android手机 fqrouter 项目不错
IOS的，还不了解。

不过要注意国内的应用市场，比如小米市场、360市场、91等等，被国安装了后门，会把fqrouter给替换掉，变成一个后门，一翻墙就把你的资料上传出去。
所以要非常小心。

在 2015年2月21日 下午8:06，angel126 <notifications@github.com>写道：
