### ISSUE TITLE
翻得好累，又翻不出去，感觉不会再爱了

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#330]
现在慢吞吞翻墙用的是别的软件，XXNET不会再爱了，所有版本都翻不动。全是FAIL, TIMEOUT, 什么的。

**Comment by zhanglaplace** [comment]
我现在用的1.12.2现在好蛮好的，就是好像对自身网速有要求。

**Comment by zhanglaplace** [comment]
我现在用的1.12.2现在好蛮好的，就是好像对自身网速有要求。

**Comment by nly4lov** [comment]
以前在公司能上，回家翻不了。我就相信是网速的问题。可现在不相信了，因为公司也上不了了。公司下载东西都是2m/s的。

**Comment by xxnet** [comment]
1.13.4，改善链接质量，希望能好用

在 2015年5月4日 上午12:54，Adam Song <notifications@github.com>写道：

**Comment by nly4lov** [comment]
13.4确实比原来的强，慢吞吞的总算翻出去了。。。。

**Comment by xxnet** [comment]
开着放那里，明天估计能更快

2015-05-04 10:18 GMT-04:00 Adam Song <notifications@github.com>:

**Comment by latrikcoasler** [comment]
应该和不同地点不同服务商有关系，还有就是版本。我一直用１.１２.１，前两天估计是封得厉害，网速不稳定，但这两点添加了扫出来的ＩＰ后就稳定了，每次连接至少有１０个以上的连接点。

**Comment by nly4lov** [comment]
[quote]开着放那里，明天估计能更快[/quote]
居然还有这样的道理。昨夜开机一夜，今早起来家里的笔记本果然翻得快了不少。
想了一下，把它复制出来用U盘拷到公司电脑里，居然也翻得比昨天早晨天壤之别

**Comment by xxnet** [comment]
后台会不断扫描ip的

在 2015年5月4日 下午8:08，Adam Song <notifications@github.com>写道：

**Comment by nly4lov** [comment]
又糟糕了啊。忽然之间就fail, timed out了

**Comment by xxnet** [comment]
重启xx-net试试？

我观察到目前的机制在什么地方还有问题。
好像重启会好点？请反馈

2015-05-05 3:12 GMT-04:00 Adam Song <notifications@github.com>:

**Comment by nly4lov** [comment]
不好意思，才看到你的回复。已经回家了啊，忽然FAIL TIMED OUT的是公司的电脑。家里的还能上。

**Comment by zhanglaplace** [comment]
我这边也是，一般情况下都翻的出去，而且速度还可以~

**Comment by nly4lov** [comment]
家里XXNET一夜开着。今早起来拷进U盘带到公司。目前谷歌简直是秒打开。FB，TT也极快

**Comment by nly4lov** [comment]
半小时前又FAIL了。然后重启XXNET，现在貌似好了。

**Comment by zhanglaplace** [comment]
感觉ip的可用变化太大了。一般刚刚开始挂也翻不了，一段时间才可以。将就用吧。~

**Comment by nly4lov** [comment]
这两天翻得非常痛快。不敢再升级了
