### ISSUE TITLE
XX-Net更新问题

### ISSUE THREAD

**Issue by littlebigdream** [XX-net/XX-Net#3301]
@xxnet 
我在https://appengine.google.com网页上点击我的appid,然后跳出提示：
GoAgent 服务端已经在 2016-05-07 23:18:10 升级到 3.3.1 版本, 请更新您的客户端。
我的XX-Net版本是3.1.11，已经是最新版本了。
请问为什么会这样，是bug吗？？

**Comment by caofengzi** [comment]
@Wrecking-Ball 俺剛纔試了一下沒有這個問題，可以用xx的uploader.bat重新上傳試試看。

**Comment by Wrecking-Ball** [comment]
@caofengzi 
你点击的是 appid名称，还是后面的 running ,要点击 running的，请点击后面的running 试试看。。

**Comment by jzp820927** [comment]
GoAgent 服务端已经在 2016-05-07 23:18:10 升级到 3.3.1 版本, 请更新您的客户端。

这个是正常提示，这个提示就是告诉你，服务端部署成功，可以正常使用了。
