### ISSUE TITLE
3.1.4是不是没有start.sh了，Linux下怎么用呢？

### ISSUE THREAD

**Issue by xiaodaowanwan** [XX-net/XX-Net#3303]
一直用的Linux,可是更新后发现没有start.sh了，重新看了下使用方法，然后还是不知道要怎么办了，希望阁下有时间的话解决一下。

**Comment by yeahwu** [comment]
直接start就好了

**Comment by Cat7373** [comment]
给 start x 权限。
./start

**Comment by yuan78** [comment]
chmod 755 start
./start

**Comment by yeahwu** [comment]
大家都这么早哇 :smile:

**Comment by Cat7373** [comment]
突然发现编辑过的回复会在时间后面加一个 edited 标记

**Comment by xiaodaowanwan** [comment]
已解决，谢谢大家
