### ISSUE TITLE
所有信息检查都正常 但是提示 尚未建立连接

### ISSUE THREAD

**Issue by tongliaozhang** [XX-net/XX-Net#3305]
-----------
问题描述：
 所有信息检查都正常 但是提示 尚未建立连接，请问如何手动操作 建立连接？

-----------
诊断信息：
sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: get_version_fail
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 2987 / 1010
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 355
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
请更新XX到最新版

**Comment by tongliaozhang** [comment]
谢谢 更新到3.1.14 已经能正常使用了
