### ISSUE TITLE
卧槽……这个IP数量涨得不正常啊，

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#3308]
状态

属性  值
总IP数    4632
剩余数   0
有效IP数 2905
一夜扫了3000多个IP？？而且扫描日志不知怎么了显示不出来

**Comment by Cat7373** [comment]
我最近也扫的挺快的，每分钟平均一个。。。
其实有一种比较恶心的攻击方案：
开放大量优质 IP 一段时间，让妮扫到一大堆优质 IP，旧的慢 IP 就都自动删掉惹0.0
然后再禁用这堆优质 IP 0.0

**Comment by yeahwu** [comment]
是的，先把你的ip库填满，然后一次性给灭了，再然后能用的ip进不了。
64快到了，预演俺看也要开始了

**Comment by liujindong121** [comment]
谎言就是某些国际的支柱

**Comment by keyoushi** [comment]
我这里是从3.1.4版本开始，内置的IP段极少能扫到优质IP，要换自己的。

**Comment by yeahwu** [comment]
现在的优质ip不能单看延时，日韩ip延时低，但是连通性差
一些小国，比如越南，马来西亚的ip延时稍高，但是连接稳定，看延时那已经是过去时了
再说xx内置的ip库，几乎是概括了东南亚大部分的ip，你能说这个ip库差
50w的ip库，调大线程挖，总能挖到好的

**Comment by xiaoyan94** [comment]
是的 ，检查了一下IP，4700个就剩下600个能用的ip了

**Comment by keyoushi** [comment]
不是帮测试么，用自带的IP段一天下来扫几十个，换了后2小时扫200个，跑3.1.11还是比较流畅了。但同样的IP段在3.0.x版本上就很容易有效IP上千，不知道神马鬼。

**Comment by zui0711** [comment]
我也是。。。9000ip今天检查了下就剩200多个了。。。

**Comment by xiuluo** [comment]
IPV4越发不稳定了，IPV6还好，虽然延迟高一点，但是一直很稳定，尤其最近配合http/2，还是挺不错的

**Comment by jzp820927** [comment]
ipv6，能用的人 屈指可数
