### ISSUE TITLE
为什么往返 < 400ms = bad ip？

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#331]
https://github.com/XX-net/XX-Net/blob/4149fefc3f5a71da3d5f618be50359ce4dd19af8/goagent/3.1.49/local/connect_manager.py#L514
意思是将延迟小于200ms的IP都视为蜜罐？

有部分幸存的GGC IP段是小于这个值的，从证书和连接稳定性上也没有看出问题。
建议改成往返<100 ms视为bad_ip。

**Comment by xxnet** [comment]
最新的trunck上没有这个逻辑了，这个假设也确实很容易绕过去。



在 2015年5月4日 上午8:39，YFdyh000 <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
已经没有了吗，最新版还有这个代码，而且还会报一些bad_ip。

**Comment by xxnet** [comment]
恩，抱歉，这个代码还在，不过都不会用到了。
现在google服务，采用direct模式，就是接入整个握手过程，替换证书。这样链接可靠性更可控。

forward代码暂时保留，但没有用到，就没有去维护它了。

bad ip，现在根据逻辑，只在确认证书不是google颁发的，才会列为bad ip。


2015-05-04 9:11 GMT-04:00 YFdyh000 <notifications@github.com>:

**Comment by yfdyh000** [comment]
我仍然看到几十个报告bad ip。好像原因是我禁用了“通过GAE进行部署”，所以会有`www.google.com = fwd`这条规则，在加载gmail邮箱时就会触发。不是因为证书有问题。

建议逻辑分开 / 报告详细bad原因 / 调低判定参数，不然低延迟的IP反而会判定为bad ip。

**Comment by xxnet** [comment]
恩，
1. 把这个判断bad ip的地方去掉；
2. 不通过GAE访问google, 就切换到Direct模式，而不是fwd模式。
我把这个改掉。

在 2015年5月4日 上午11:30，YFdyh000 <notifications@github.com>写道：
