### ISSUE TITLE
连接重置错误

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#3311]
## 问题内容
更新3.1.4版本后出现开机后一段时间可以使用代理，但是使用一段时间后就出现连接重置错误，但用出现错误的ip用到goagent中却不会出现这样的问题。另外换回2.9.4版本后该问题也不再出现。

#### 日志

May 10 15:09:10.511 - [WARNING] 209.85.234.155       _consume_single_frame:ConnectionResetError()
连接wikipedia.org时出现的错误如下
May 10 21:02:06.066 - [WARNING] 216.239.38.127 _consume_single_frame:SysCallError(10035, 'WSAEWOULDBLOCK')
May 10 21:02:06.066 - [DEBUG] ssl_closed 216.239.38.127
May 10 21:02:06.066 - [DEBUG] 216.239.38.127 worker close:disconnect:SysCallError(10035, 'WSAEWOULDBLOCK')
May 10 21:02:26.584 - [WARNING] server app return fail, status:502

#### 诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.4

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:937 good:464
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:3
scan-ip-thread-num: 50
ip-quality: 377
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by Cat7373** [comment]
这个错误是连接中断了。。。
并没有什么问题。。。

**Comment by taoist1994** [comment]
用3.1.4时隔不久就会这样，从而无法连接需要代理的网线，但换回2.9.4就立刻恢复正常了。
