### ISSUE TITLE
请问怎么修改配置才能设置为只扫描延迟低于200ms的ip？

### ISSUE THREAD

**Issue by wookongCN** [XX-net/XX-Net#3316]
请问怎么修改配置才能设置为只扫描延迟低于200ms的ip？有知道的兄弟麻烦告诉一下，谢谢！
@Cat7373 
@xyuanmu 
@xxnet

**Comment by jzp820927** [comment]
设置下IP数量不就行了，自然取前面的就是延时最低点

**Comment by wookongCN** [comment]
我的意思是扫描ip的时候只扫描延迟低于200的ip，高于200的不要了

**Comment by Cat7373** [comment]
你可以考虑先扫描一些 IP，比如扫描 1000 个，然后关掉 XX-Net，手动删除 IP 库里大于 200 的 IP。

**Comment by wookongCN** [comment]
这个不能在配置文件里面设置吗@Cat7373

**Comment by Cat7373** [comment]
目前似乎没有这种配置。

**Comment by jzp820927** [comment]
好像 googleipcheck 可以设置延时

**Comment by yeahwu** [comment]
你这需求太奇葩，会找ip吗？
找尽日韩澳港周边ip就好了，但是这些国家ip加起来也没几个。

**Comment by wookongCN** [comment]
@yeahwu 我不会可以了吧（我现在用的ip都是150以下的）
@Cat7373 我的manual.ini文件可以设置扫描线程。找了配置文件，没找到那个是延迟的代码，其他的代码看不懂，不知道是啥意思，而且好多代码没有注解，完全蒙逼...

**Comment by yeahwu** [comment]
xx一直的规则就是延时低的ip，取前10使用，不明白你这样做的意义。
如果要追求用你哪150ms以下的ip，可以去试试goproxy，goagent，ip都不用扫了，就用你那些ip。

**Comment by keyoushi** [comment]
好像在D:\XX-Net\code\default\gae_proxy\local里面check_ip.py里面可以改，忘了。意义不大，延时低不代表连接稳定。要是折腾过蓝灯的yaml,你一定会明白的2333333

**Comment by wookongCN** [comment]
@keyoushi 看了那个的，看不懂，没有注解

**Comment by keyoushi** [comment]
或者你可以把IP导出，用ip_mass_ping一类的工具筛一遍......话说XX不是自带的有check IP功能么.....
