### ISSUE TITLE
换了浏览器后就不能用了

### ISSUE THREAD

**Issue by fanzi630** [XX-net/XX-Net#332]
重装了一次浏览器 之后就不能翻墙了
部署id后 再刷新会显示 当前状态: 空闲

May 04 22:11:04 - [INFO] load ip range file:H:\XX-Net-1.13.3\goagent\3.1.49\local\ip_range.txt
May 04 22:11:04 - [INFO] load google ip_list num:3000, gws num:3000
May 04 22:11:04 - [DEBUG] sort ip time:0
May 04 22:11:04 - [INFO] ------------------------------------------------------
GoAgent Version : 3.1.49 (python/2.7.9 )
Listen Address : 127.0.0.1:8087
Control Address : 127.0.0.1:8084
GAE APPID : fanzi630
Pac Server : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

May 04 22:11:05 - [DEBUG] GoAgent Web_control 127.0.0.1:4055 "GET /is_ready 
May 04 22:11:06 - [DEBUG] get ip:64.233.189.201 t:156
May 04 22:11:07 - [DEBUG] get ip:210.61.221.153 t:203
May 04 22:11:07 - [DEBUG] create_ssl update ip:64.233.189.201 time:515
May 04 22:11:07 - [DEBUG] get ip:210.242.125.24 t:342
May 04 22:11:07 - [DEBUG] get ip:216.58.192.50 t:405
May 04 22:11:07 - [DEBUG] create_ssl update ip:210.242.125.24 time:281
May 04 22:11:07 - [DEBUG] get ip:94.40.70.48 t:468
May 04 22:11:08 - [DEBUG] get ip:202.65.246.118 t:515
May 04 22:11:08 - [DEBUG] get ip:83.145.196.185 t:515
May 04 22:11:08 - [DEBUG] get ip:64.233.168.201 t:516
May 04 22:11:09 - [DEBUG] create_ssl 210.61.221.153 fail:timed out cost:2000 h:0
May 04 22:11:09 - [DEBUG] create_ssl update ip:94.40.70.48 time:1078
May 04 22:11:09 - [DEBUG] create_ssl update ip:64.233.168.201 time:562
May 04 22:11:09 - [DEBUG] create_ssl 216.58.192.50 fail:timed out cost:2000 h:0
May 04 22:11:09 - [DEBUG] report_connect_fail network fail
May 04 22:11:10 - [DEBUG] create_ssl 202.65.246.118 fail:timed out cost:2000 h:0
May 04 22:11:10 - [DEBUG] report_connect_fail network fail
May 04 22:11:10 - [DEBUG] get ip:64.233.191.201 t:516
May 04 22:11:10 - [DEBUG] get ip:64.233.183.200 t:546
May 04 22:11:10 - [DEBUG] get ip:193.120.166.95 t:547
May 04 22:11:10 - [DEBUG] create_ssl update ip:83.145.196.185 time:2046
May 04 22:11:10 - [DEBUG] create_ssl 83.145.196.185 fail: certficate is none cost:2641 h:2046
May 04 22:11:11 - [DEBUG] create_ssl update ip:64.233.191.201 time:608
May 04 22:11:11 - [DEBUG] get ip:193.192.250.152 t:562
May 04 22:11:11 - [DEBUG] create_ssl update ip:64.233.183.200 time:594
May 04 22:11:11 - [DEBUG] create_ssl update ip:193.120.166.95 time:608
May 04 22:11:11 - [DEBUG] get ip:85.182.250.251 t:562
May 04 22:11:11 - [DEBUG] get ip:193.192.250.168 t:577
May 04 22:11:12 - [DEBUG] get ip:64.233.164.200 t:577
May 04 22:11:12 - [DEBUG] get ip:77.66.9.110 t:578
May 04 22:11:12 - [DEBUG] get ip:178.45.251.109 t:594
May 04 22:11:12 - [DEBUG] create_ssl update ip:193.192.250.168 time:625
May 04 22:11:13 - [DEBUG] create_ssl update ip:64.233.164.200 time:671
May 04 22:11:13 - [DEBUG] create_ssl 193.192.250.152 fail:timed out cost:2014 h:0
May 04 22:11:13 - [DEBUG] create_ssl 85.182.250.251 fail:timed out cost:2000 h:0
May 04 22:11:13 - [DEBUG] get ip:82.135.118.16 t:594
May 04 22:11:14 - [DEBUG] get ip:64.233.162.85 t:610
May 04 22:11:14 - [DEBUG] get ip:83.94.121.216 t:625
May 04 22:11:14 - [DEBUG] create_ssl 77.66.9.110 fail:timed out cost:2000 h:0
May 04 22:11:14 - [DEBUG] create_ssl 178.45.251.109 fail:timed out cost:2000 h:0
May 04 22:11:14 - [DEBUG] sort ip time:16
May 04 22:11:14 - [DEBUG] get ip:193.134.255.24 t:687
May 04 22:11:15 - [DEBUG] get ip:212.188.10.229 t:703
May 04 22:11:15 - [DEBUG] get ip:83.100.221.247 t:703
May 04 22:11:15 - [DEBUG] create_ssl update ip:193.134.255.24 time:717
May 04 22:11:15 - [DEBUG] create_ssl 82.135.118.16 fail:timed out cost:2000 h:0
May 04 22:11:16 - [DEBUG] create_ssl 83.94.121.216 fail:timed out cost:2000 h:0
May 04 22:11:16 - [DEBUG] create_ssl update ip:212.188.10.229 time:718
May 04 22:11:16 - [DEBUG] create_ssl update ip:64.233.162.85 time:2359
May 04 22:11:17 - [DEBUG] create_ssl 83.100.221.247 fail:timed out cost:2000 h:0
May 04 22:12:24 - [DEBUG] GoAgent web_control 127.0.0.1:4325 POST /importip?cmd=importip 
May 04 22:12:31 - [DEBUG] GoAgent Web_control 127.0.0.1:4335 "GET /deploy?cmd=get_log 
May 04 22:12:32 - [DEBUG]LOG_EXCEPT: GoAgent web_control 127.0.0.1:4340 POST /config?cmd=get_config , Except:[Errno 9] Bad file descriptor

**Comment by xxnet** [comment]
估计是墙高了，你试试最新版，刚才发了一个新版，1.13.5

2015-05-04 10:18 GMT-04:00 fanzi630 <notifications@github.com>:
