### ISSUE TITLE
mac,用3.1.12和3.1.13都打不开youtube，其他google什么的都秒开；退回到3.1.11就能打开youtube

### ISSUE THREAD

**Issue by mk123789** [XX-net/XX-Net#3320]
连接超时，先休息一会再来！错误504

**Comment by yeahwu** [comment]
打不开的情况，看一下h1是不是较少？

**Comment by mk123789** [comment]
对，h1:0

**Comment by mk123789** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17
xxnet-version: 3.1.12

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:1080 good:870
network-status: OK
connected-link: new:12 used:0
worker: h1:0 h2:21
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by cc941201** [comment]
要把`code/default/gae_proxy/local/proxy.ini`中`.youtube.com =`从direct改为gae

**Comment by yeahwu** [comment]
这个要 @xxnet  
这是由于h2不支持youtube直连导致的，如果改为gae转发就没问题了

**Comment by mk123789** [comment]
改了之后就出现“尚未连接”，本地网络unknown

**Comment by yeahwu** [comment]
俺就是这样改的，没有问题，可能你的姿势不对
建议新建一个manual.ini文件，里面改

**Comment by mk123789** [comment]
3.1.13改了之后就能用，3.1.12改了之后就是出现“尚未连接”，现在用3.1.13呢，谢谢各位

**Comment by mk123789** [comment]
刚才先改的3.1.12以为不能用，嘻嘻，后改的3.1.13就能用了

**Comment by JMaxime** [comment]
问题解决了 建议close issue
