### ISSUE TITLE
每次用google搜索都会跳出这样的验证代码 各位大大来看看

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#3321]
请键入下图显示的字符以继续操作：

38299 提交

关于此网页

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。为什么会这样？

**Comment by zjgbql** [comment]
留个记号,我也有这问题

**Comment by JMaxime** [comment]
# @xxnet

**Comment by yeahwu** [comment]
直连情况下，还是发生这个问题。
就只有ip的原因了

**Comment by yeahwu** [comment]
试试把 google.com 这一行前面的 引号去掉试试
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/proxy.ini#L36

**Comment by JMaxime** [comment]
全局PAC智能代理

**Comment by JMaxime** [comment]
;.google.com = direct
这一行前面“；.”都删掉吗 
右键编辑就可以了吗 不需要其他软件进行编辑吧
@yeahwu

**Comment by JMaxime** [comment]
右键编辑修改好后 就不能用了

**Comment by yeahwu** [comment]
点不要去掉 就去掉 ；号就好

**Comment by LongShaWu** [comment]
我也有这个问题，这样子感觉比较麻烦

**Comment by JMaxime** [comment]
@yeahwu 关键是右键进行编辑保存后 提示xx不能使用了 角标都不会出现了 

是不是需要其他软件来辅助编辑呢

**Comment by JMaxime** [comment]
@yeahwu 借助这个Notepad++ 编辑后可以成功打开xx 
会不会再出现验证码 现在就测试

**Comment by JMaxime** [comment]
@zjgbql  @LongShaWu 现在貌似没有出现验证码了 测试了三次

**Comment by iQuick** [comment]
最近也遇到了

**Comment by cdmask** [comment]
mark

**Comment by leedming** [comment]
mark  
***

这是什么原理呢？

**Comment by leedming** [comment]
###这还支持markdown语法呢呀

**Comment by withero** [comment]
Mark。记录下。我也有这个问题。

**Comment by redstoneleo** [comment]
@yeahwu  你看看那个文件顶部已经说明：

> 不要修改这个文件。
> ; 每次升级时，会自动覆盖这个文件
> ; 可以直接在webUI中设置，或者创建data/gae_proxy/manual.ini然后放入你自定义的部分配置

我改了之后xx-net也用不了了，害我又下载新版，哎~~~
求在webUI中设置的方法！！！

**Comment by jzp820927** [comment]
Web ui 中只能设置小部分内容，一些高级的修改，只能自己改 ini 文件

**Comment by redstoneleo** [comment]
我创建data/gae_proxy/manual.ini，并加入这些内容，结果还是老样子
[hosts]
.google.com = direct

**Comment by jzp820927** [comment]
有没有跳到 hk，如果有的话，hk也要添加

**Comment by redstoneleo** [comment]
搜索用的是https://www.google.com/search?q=
没有hk

**Comment by jzp820927** [comment]
最新版默认就是走直连，不用改配置的。可以试试

**Comment by sigmalumia1** [comment]
我也有这个问题，用的是3.2.4这个最新版本，大家有人解决没

**Comment by veyron9288** [comment]
希望可以解决掉

**Comment by YazidLee** [comment]
我用chrome没事 用firefox就这样了 同求解决方案

**Comment by jzp820927** [comment]
这样也太诡异了吧，还挑浏览器？
