### ISSUE TITLE
3.1.13 Mac下已部署私有AppID但无法进入Youtube

### ISSUE THREAD

**Issue by chenqp7** [XX-net/XX-Net#3330]
## 问题描述
Mac下使用Chrome并使用代理插件。之前用的2.9.4版本，完美使用YouTube，但是手动下载之后，不论是直接拷贝data文件夹，还是完全重新配置并部署私有appID，都访问不了YouTube，显示504 GAEProxy Proxy Time Out连接超时错误。

### 附加内容
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 3.1.13

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:9 good:1
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:2
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 日志
May 10 23:39:59.536 - [INFO] GAE CONNECT www.youtube.com:443
May 10 23:39:59.544 - [DEBUG] GAE CONNECT Direct GET https://www.youtube.com/
May 10 23:39:59.905 - [WARNING] no enough ip
May 10 23:40:00.905 - [WARNING] no enough ip
May 10 23:40:01.908 - [WARNING] no enough ip
May 10 23:40:02.909 - [WARNING] no enough ip
May 10 23:40:03.909 - [WARNING] no enough ip
May 10 23:40:04.910 - [WARNING] no enough ip
May 10 23:40:04.911 - [WARNING] no enough ip
May 10 23:40:05.914 - [WARNING] no enough ip
May 10 23:40:06.915 - [WARNING] no enough ip
May 10 23:40:07.915 - [WARNING] no enough ip
May 10 23:40:08.918 - [WARNING] no enough ip
May 10 23:40:09.922 - [WARNING] no enough ip
May 10 23:40:10.924 - [WARNING] no enough ip
May 10 23:40:11.855 - [DEBUG] create ssl timeout fail.
May 10 23:40:11.924 - [WARNING] no enough ip
May 10 23:40:12.925 - [WARNING] no enough ip
May 10 23:40:13.925 - [WARNING] no enough ip
May 10 23:40:14.664 - [DEBUG] GAE POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJFbkFrNUh1Ml9EejZjdlVKaXpxQlA4LXp5Q3dORHgyamdjdXBOWFdGWkl3R3lqNjZ6UWx1WjQ2ZWYteEVYeFpvSnBDZ2xDUERpVEpVYVNVdm9qTHNyLUxyaGtMNkxkcHcyMmg5a3NOSTJxTnhvNjJtQklLX0M5VTE3MV9fNmpiZjg3MktWd0dJZWdSMHVIOGZ1c0tsa25Hd21nMXdZU3JMTXg1QURCZmgzQ3JHNFBVb2caACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM
May 10 23:40:14.933 - [INFO] GAE t:269 s:0 POST https://clients4.google.com/invalidation/android/request/CHES4QEStwFBUEE5MWJFbkFrNUh1Ml9EejZjdlVKaXpxQlA4LXp5Q3dORHgyamdjdXBOWFdGWkl3R3lqNjZ6UWx1WjQ2ZWYteEVYeFpvSnBDZ2xDUERpVEpVYVNVdm9qTHNyLUxyaGtMNkxkcHcyMmg5a3NOSTJxTnhvNjJtQklLX0M5VTE3MV9fNmpiZjg3MktWd0dJZWdSMHVIOGZ1c0tsa25Hd21nMXdZU3JMTXg1QURCZmgzQ3JHNFBVb2caACoCCAAyH2NvbS5nb29nbGUuY2hyb21lLmludmFsaWRhdGlvbnM h2_get_head:267

**Comment by chenqp7** [comment]
但是目前测试其他诸如Google、Facebook、twitter之类的网站能够访问

**Comment by yeahwu** [comment]
已经修复了，等待下个版本更新吧，目前解决方案
https://github.com/XX-net/XX-Net/issues/3320

**Comment by chenqp7** [comment]
刚测试3.1.4版本，虽然扫描IP太慢，导入之前的IP出现了一丝丝问题，包括部署服务端appID卡在弹出页面那一步，但最终在不重新部署服务端的情况下，直接部署appID，完美访问YouTube，能播放1080P视频。

**Comment by chenqp7** [comment]
哦，好的，谢谢
