### ISSUE TITLE
阴谋论：不能用是谷歌封杀了

### ISSUE THREAD

**Issue by boromeke** [XX-net/XX-Net#334]
我之所以这样说是因为，我通过Tor走全局代理后，xx还是不能用。走SSH全局代理后，还是不能用。那就说明一个问题，如果不是程序本身的问题，那就是谷歌的问题了。因为同样的情况也发生在goagent中。

uproxy，不是公测了么，难道谷歌想去公测这东西。不过一看到要么登陆google＋，要么是facebook，我就感到恶心。

**Comment by Pd69bq** [comment]
Part 1 is a Chrome "extension" and part 2 is a Chrome "app." 不翻墙哪个也实现不了呀 如果google能本土提供翻墙到好了

**Comment by xxnet** [comment]
不必担心，谁翻墙很大可能都是google的用户，不会封杀谁的
