### ISSUE TITLE
尚未建立连接

### ISSUE THREAD

**Issue by MasterLuo** [XX-net/XX-Net#3345]
升级最新版后不是“检查浏览器代理设置”就是“尚未建立连接”，重新安装几次了都没用，请大家帮忙看看出了什么问题。

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 3.1.13

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2 good:2
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:1
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

GAEProxy 日志：

May 11 19:06:56.046 - [INFO] SSL use version:TLSv1_2
May 11 19:06:57.091 - [INFO] OpenSSL support alpn
May 11 19:06:57.102 - [INFO] load ip range file:D:\Program Files (x86)\XX-Net-3.1.13\code\default\gae_proxy\local\ip_range.txt
May 11 19:06:57.140 - [INFO] load google ip_list num:1, gws num:1
May 11 19:06:57.158 - [INFO] OpenSSL support alpn
May 11 19:06:57.159 - [DEBUG] get ip:113.171.252.211 t:433
May 11 19:06:57.162 - [WARNING] no enough ip
May 11 19:06:57.170 - [DEBUG] ## GAEProxy set keep_running: True
May 11 19:06:57.170 - [INFO] ------------------------------------------------------
May 11 19:06:57.170 - [INFO] Python Version : 2.7.11
May 11 19:06:57.170 - [INFO] OS : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
May 11 19:06:57.171 - [INFO] Listen Address : 127.0.0.1:8087
May 11 19:06:57.171 - [INFO] GAE APPID :
May 11 19:06:57.171 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
May 11 19:06:57.171 - [INFO] ------------------------------------------------------
May 11 19:06:57.778 - [DEBUG] network is ok, cost:2155 ms
May 11 19:06:58.663 - [WARNING] no enough ip
May 11 19:06:58.663 - [WARNING] no enough ip
May 11 19:06:58.663 - [DEBUG] create_ssl update ip:113.171.252.211 time:622 h2:0
May 11 19:06:59.663 - [WARNING] no enough ip
May 11 19:07:00.134 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
May 11 19:07:00.163 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=ecb60e0e-5584-4809-8ca2-f964532b85f8&version=3.1.13&platform=Windows-7-6.1.7601-SP1
May 11 19:07:00.663 - [WARNING] no enough ip
May 11 19:07:00.663 - [WARNING] no enough ip
May 11 19:07:00.678 - [INFO] DIRECT t:514 s:1674 200 xxnet-update.appspot.com /update.json?uuid=ecb60e0e-5584-4809-8ca2-f964532b85f8&version=3.1.13&platform=Windows-7-6.1.7601-SP1
May 11 19:07:01.683 - [WARNING] no enough ip
May 11 19:07:01.683 - [WARNING] no enough ip
May 11 19:07:02.509 - [INFO] PAC from:127.0.0.1:50361 GET /proxy.pac
May 11 19:07:02.689 - [WARNING] no enough ip
May 11 19:07:02.689 - [WARNING] no enough ip
May 11 19:07:03.697 - [WARNING] no enough ip
May 11 19:07:03.697 - [WARNING] no enough ip
May 11 19:07:04.698 - [WARNING] no enough ip
May 11 19:07:04.698 - [WARNING] no enough ip
May 11 19:07:05.698 - [WARNING] no enough ip
May 11 19:07:05.698 - [WARNING] no enough ip
May 11 19:07:06.704 - [WARNING] no enough ip
May 11 19:07:06.704 - [WARNING] no enough ip
May 11 19:07:07.704 - [WARNING] no enough ip
May 11 19:07:07.704 - [WARNING] no enough ip
May 11 19:07:30.935 - [DEBUG] GAE GET https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt
May 11 19:07:31.556 - [INFO] scan_ip add ip:201.218.56.149 time:2139
May 11 19:07:47.410 - [DEBUG] 113.171.252.211 close:host pool alive_timeout
May 11 19:07:47.410 - [DEBUG] ssl_closed 113.171.252.211
May 11 19:07:59.671 - [DEBUG] get ip:113.171.252.211 t:622
May 11 19:08:00.352 - [DEBUG] create_ssl update ip:113.171.252.211 time:453 h2:0
May 11 19:08:00.352 - [DEBUG] get ip:201.218.56.149 t:2139
May 11 19:08:00.891 - [INFO] GAE t:29953 s:298 GET https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt h1_req:29455,get_response:490
May 11 19:08:04.457 - [DEBUG] create_ssl update ip:201.218.56.149 time:3703 h2:1
May 11 19:08:05 - [WARNING]LOG_EXCEPT: no enough ip, Except:[Errno 9] Bad file descriptor
May 11 19:08:06.499 - [WARNING] no enough ip
May 11 19:08:06.499 - [WARNING] no enough ip
May 11 19:08:07.499 - [WARNING] no enough ip
May 11 19:08:08.507 - [WARNING] no enough ip
May 11 19:08:08.507 - [WARNING] no enough ip
May 11 19:08:09.507 - [WARNING] no enough ip
May 11 19:08:10.513 - [WARNING] no enough ip
May 11 19:08:10.515 - [WARNING] no enough ip
May 11 19:08:11.524 - [WARNING] no enough ip
May 11 19:08:12.544 - [WARNING] no enough ip
May 11 19:08:12.555 - [WARNING] no enough ip
May 11 19:08:13.555 - [WARNING] no enough ip
May 11 19:08:14.555 - [WARNING] no enough ip
May 11 19:08:14.555 - [WARNING] no enough ip
May 11 19:08:14.645 - [INFO] PAC from:127.0.0.1:51111 GET /proxy.pac
May 11 19:08:15.565 - [WARNING] no enough ip
May 11 19:08:16.567 - [WARNING] no enough ip
May 11 19:08:16.567 - [WARNING] no enough ip
May 11 19:08:17.568 - [WARNING] no enough ip
May 11 19:08:18.570 - [WARNING] no enough ip
May 11 19:09:04.502 - [DEBUG] create ssl timeout fail.
May 11 19:10:04.510 - [DEBUG] create ssl timeout fail.
May 11 19:10:05.510 - [WARNING] no enough ip
May 11 19:10:06.511 - [WARNING] no enough ip
May 11 19:10:06.511 - [WARNING] no enough ip
May 11 19:10:07.511 - [WARNING] no enough ip
May 11 19:10:08.511 - [WARNING] no enough ip
May 11 19:10:08.511 - [WARNING] no enough ip
May 11 19:10:09.516 - [WARNING] no enough ip
May 11 19:10:10.522 - [WARNING] no enough ip
May 11 19:10:10.522 - [WARNING] no enough ip
May 11 19:10:11.523 - [WARNING] no enough ip
May 11 19:10:12.526 - [WARNING] no enough ip
May 11 19:10:12.526 - [WARNING] no enough ip
May 11 19:10:13.529 - [WARNING] no enough ip
May 11 19:10:14.530 - [WARNING] no enough ip
May 11 19:10:14.531 - [WARNING] no enough ip
May 11 19:10:15.532 - [WARNING] no enough ip
May 11 19:10:16.539 - [WARNING] no enough ip
May 11 19:10:16.539 - [WARNING] no enough ip
May 11 19:10:17.540 - [WARNING] no enough ip
May 11 19:10:18.548 - [WARNING] no enough ip
May 11 19:11:04.510 - [DEBUG] create ssl timeout fail.
May 11 19:11:29.830 - [INFO] scan_ip add ip:92.226.2.93 time:560
May 11 19:12:04.457 - [DEBUG] ssl_closed 201.218.56.149
May 11 19:12:04.457 - [DEBUG] 201.218.56.149 worker close:GoAway: additional_data:session_timed_out
May 11 19:12:04.467 - [DEBUG] get ip:92.226.2.93 t:560
May 11 19:12:04.517 - [DEBUG] create ssl timeout fail.
May 11 19:12:04.517 - [DEBUG] get ip:201.218.56.149 t:2639
May 11 19:12:06.025 - [WARNING] no enough ip
May 11 19:12:07.033 - [WARNING] no enough ip
May 11 19:12:07.033 - [DEBUG] create_ssl update ip:92.226.2.93 time:514 h2:0
May 11 19:12:08.038 - [WARNING] no enough ip
May 11 19:12:08.038 - [WARNING] no enough ip
May 11 19:12:09.047 - [WARNING] no enough ip
May 11 19:12:11.061 - [WARNING] no enough ip
May 11 19:12:11.061 - [WARNING] no enough ip
May 11 19:12:11.896 - [DEBUG] 201.218.56.149 fail:error(' certficate is none',)
May 11 19:12:12.067 - [WARNING] no enough ip
May 11 19:12:13.074 - [WARNING] no enough ip
May 11 19:12:14.082 - [WARNING] no enough ip
May 11 19:12:14.082 - [WARNING] no enough ip
May 11 19:12:15.085 - [WARNING] no enough ip
May 11 19:12:16.086 - [WARNING] no enough ip
May 11 19:12:17.087 - [WARNING] no enough ip
May 11 19:12:17.087 - [DEBUG] report_connect_fail:201.218.56.149
May 11 19:12:17.087 - [WARNING] no enough ip
May 11 19:12:18.090 - [WARNING] no enough ip
May 11 19:12:19.092 - [WARNING] no enough ip
May 11 19:12:20.093 - [WARNING] no enough ip
May 11 19:12:20.093 - [WARNING] no enough ip
May 11 19:12:21.097 - [WARNING] no enough ip

**Comment by yeahwu** [comment]
给它扫过 一两个小时再来报告

**Comment by MasterLuo** [comment]
扫了3小时，可以翻墙了。一开始证书不可用，从没遇到过这个问题，有点慌。

**Comment by yeahwu** [comment]
呵呵，别慌，习惯就好了。
