### ISSUE TITLE
请大神给看看这个配置有问题没？还有优化的空间没？

### ISSUE THREAD

**Issue by nicky-sh** [XX-net/XX-Net#3347]
把XX-Net（版本：3.1.14）部署到两台服务器上，一台内网使用，电信百兆双线路拨号宽带，另一台外网使用，电信百兆单线路专线。

[autorange]
threads = 30
maxsize = 524288
waitsize = 262144
bufsize = 262144

[google_ip]
use_ipv6 = 0
auto_adjust_scan_ip_thread_num = 0
max_scan_ip_thread_num = 100
max_check_ip_thread_num = 100
max_good_ip_num = 30000
ip_connect_interval = 10
max_links_per_ip = 3
ip_traffic_quota = 102400
ip_traffic_quota_base = 102400
record_ip_history = 0

[connect_manager]
https_max_connect_thread = 30
https_new_connect_num = 5
https_connection_pool_min = 10
https_connection_pool_max = 50
keep_active_timeout = 600
https_keep_alive = 60
forward_max_connect_thread = 30
connect_interval = 50
max_worker_num = 100

@xxnet @yeahwu

**Comment by Cat7373** [comment]
这两个配置已经在最新版中被删除了。

    waitsize = 262144
    bufsize = 262144

**Comment by xxnet** [comment]
​有部分配置已经不需要了，不过放着也不影响。
此处：
[autorange]
threads = 30  太大了，可能会起反作用，建议保留原来设置或者改小。
原因：
+ 太多线程下载，有一个卡住，其他都会卡住。
+ 用的人多，每个人就不要占用太多资源更好。

其他参数，要看用的情况，路由器能不能抗得住。
要在使用过程中，测试路由器、非翻墙上网的性能是否正常，如果变慢了，要么换路由器，要么降低扫描线程。

**Comment by nicky-sh** [comment]
@Cat7373 
有些参数是从以前的版本合并过来的

**Comment by nicky-sh** [comment]
@xxnet 
路由器性能没问题，路由器CPU利用率不到8%。
其他参数还有优化的空间吗？

**Comment by yeahwu** [comment]
100的最大线程也够高的，以现在的ip延时算，线程也会彪到4，5百了

**Comment by nicky-sh** [comment]
@yeahwu 
帮忙修改下参数吧

**Comment by yeahwu** [comment]
下面是xx上ip线程的具体算法，延时越低，线程也就越低
```
(第100个IP的延时 - 200) ÷ 2 * 最大扫描线程 ÷ 50
```
依现在的ip质量，刚开始的时候建议保持默认50，随后ip充足了，可以逐渐往下降，降到10为止，这是俺的建议
max_scan_ip_thread_num = 50

**Comment by Cat7373** [comment]
@yeahwu 这算法真的对么。。
第100个IP的延时 = 2200
最大扫描线程 = 50
于是

扫描线程数
= (第100个IP的延时 - 200) ÷ 2 * 最大扫描线程 ÷ 50
= (2200 - 200) ÷ 2 * 50 ÷ 50
= 2000 ÷ 2 * 50 ÷ 50
= 1000 * 50 ÷ 50
= 1000 ？

**Comment by yeahwu** [comment]
对不对得问xx？反正俺这边没有这么高的延时，哈哈

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/google_ip.py#L251
具体算法在这，@yeahwu 你给的算法是正确的，但是漏了一点，如果计算结果大于最大线程数，则重置为最大线程数。

**Comment by yeahwu** [comment]
@Cat7373 其实俺就是随便说说滴，你还真去看代码了？
原来骗小菇凉这么容易！
