### ISSUE TITLE
XX-Net v3.1.14 运行后系统托盘无图标，无法打开Web页面。

### ISSUE THREAD

**Issue by nicky-sh** [XX-net/XX-Net#3348]
操作系统版本：Microsoft Windows Server 2008 R2 Service Pack 1 x64。
XX-Net版本：3.1.14。

运行后使用正常，Telnet测试8086、8087端口通，8085端口不通，系统托盘无XX-Net图标。

日志文件内容：
C:\XX-Net\data\launcher\launcher.log
May 11 18:38:55.223 - [INFO] use build-in openssl lib
May 11 18:38:55.225 - [INFO] start XX-Net 3.1.14
May 11 18:38:55.225 - [DEBUG] start confirm_xxnet_exit
May 11 18:38:56.237 - [DEBUG] good, xxnet:8087 cleared!
May 11 18:38:57.249 - [DEBUG] good, xxnet:8085 clear!
May 11 18:38:57.249 - [DEBUG] finished confirm_xxnet_exit
May 11 18:38:59.260 - [INFO] module gae_proxy started
May 11 18:38:59.260 - [INFO] start gae_proxy time cost:2006 ms

日志文件里只有这点日志。

**Comment by xxnet** [comment]
如果能够翻墙，说明GAE模块已经工作了，但是launcher模块卡住

到底在哪里卡住，需要单步跟踪才好

**Comment by yeahwu** [comment]
好像占用1080端口，好像也打不开web

**Comment by nicky-sh** [comment]
@xxnet 
1080端口也不通

![1](https://cloud.githubusercontent.com/assets/15864903/15208162/a4699d0c-185c-11e6-89ca-83ea888cee9a.png)
![2](https://cloud.githubusercontent.com/assets/15864903/15208180/b7911d7e-185c-11e6-8059-a6ad2061f66f.png)
![3](https://cloud.githubusercontent.com/assets/15864903/15208183/bedc5d32-185c-11e6-8b7b-43e53fee1706.png)
![4](https://cloud.githubusercontent.com/assets/15864903/15208191/c81a2f1e-185c-11e6-9700-6fe2d03e8fdf.png)

**Comment by nicky-sh** [comment]
@xxnet 
感觉是先启动GAE模块，然后启动X-Tunnel模块，最后启动Launcher模块，因为X-Tunnel模块启动失败，所以Launcher模块卡住的。

**Comment by nicky-sh** [comment]
@xxnet 
修改XX-Net\data\launcher\config.yaml文件，把x_tunnel: {auto_start: 1}改成x_tunnel: {auto_start: 0}，启动正常，系统托盘出现图标，然后再在Web界面启动X-Tunnel模块，一切正常，所有端口都可用。
但是不能关闭XX-Net，关闭以后问题依旧。

**Comment by xxnet** [comment]
​这么说来，就是launcher在启动x_tunnel时，卡住了，需要搭个环境来测试。

网上查资料，10013是权限错误，可能windows server 对这个端口有限制，可以用管理员权限启动，或者试试修改端口。

https://github.com/XX-net/XX-Net/wiki/X_tunnel-Config-file

**Comment by nicky-sh** [comment]
@xxnet 
是用管理员权限启动的，按照你说的方法修改端口为6666、7777、8888、9999都不行，问题依旧。
重启机器后，在不启动XX-Net的情况下，测试本地的8085、8086、8087、1080端口，均未被占用。
这个问题是在2.9.6手动升级到3.1.14后出现的。
在同样环境的另一台机器上无此问题，在虚拟机中测试也无此问题。

**Comment by xxnet** [comment]
​太奇怪，会不会绑定端口数限制？

你试试不启动GAE模块，能不能启动。
或者把PAC关掉。

**Comment by nicky-sh** [comment]
@xxnet 
系统端口没什么限制。
已测试，关闭X-Tunnel模块后，其他情况全部正常。
打开X-Tunnel模块，关闭GAE模块、PHP模块和PAC，问题依旧。
不知道是什么原因，用倒是可以用，不折腾了。

**Comment by xxnet** [comment]
​ok

**Comment by yajiya** [comment]
我也遇见这个问题，之前好的，某一天突然有这个问题了。输出的信息也是差不多一样的。
window7x64， 当时的版本是3.1.19，后来换了3.2.6，也是不行。
情况大致是，能科学上网，但是没有图标，手动输入 http://127.0.0.1:8085/ ，无法打开。
netstat看，8085端口没有任何监听。

**Comment by jzp820927** [comment]
直接终端运行，看日志有误报错

**Comment by yajiya** [comment]
@jzp820927 日志跟上面nicky-sh的截图几乎是完全一样的。

**Comment by jzp820927** [comment]
上面的日志是因为占用了 1080 端口，如果你和大一样，把占用 1080 端口的进程杀掉就行了

**Comment by yajiya** [comment]
@jzp820927 谢谢，果然搞定了。
