### ISSUE TITLE
ipv6数目逐渐下降，可以像ipv4一样通过扫描增加吗？

### ISSUE THREAD

**Issue by april4513** [XX-net/XX-Net#3359]

**Comment by jzp820927** [comment]
肯定可以啊，只要有工具

**Comment by xxnet** [comment]
照着ipv4的流程办法，改改代码就可以了。

**Comment by april4513** [comment]
看了下wiki/GoAgent-Config-file的介绍 是要建立data/gae_proxy/manual.ini
然后把以下的放进去？

[google_ip]
use_ipv6 = 1
max_check_ip_thread_num = 20 <- 扫描 ip 的线程数
max_good_ip_num = 3000 <- 最大保留ip 数
ip_connect_interval = 10 <- 单个ip连接的间隔

这个样子对吗，还需要改什么东西吗？（已经把ipv6的0改为了1）

**Comment by xxnet** [comment]
​需要改源码，没有编程基础不要尝试。

可以试试3.1.15，把所有ip都检查一遍看看

**Comment by april4513** [comment]
好的，我就不弄这个了，多谢了
