### ISSUE TITLE
现在速度太快乐，2000多ip全是100来的延迟，要憋大招啊

### ISSUE THREAD

**Issue by liujindong121** [XX-net/XX-Net#3369]
某部门又要故技重施Me?

**Comment by jzp820927** [comment]
这是 GFW 的新战术，欲擒故纵法

**Comment by dreamidiot** [comment]
@liujindong121 @jzp820927 
能问一下你们使用的版本、地区和isp吗？
为什么我魔都电信3.1.14和3.0.3都从没超过150个ip啊？
设置的应该没错，从2.x用到现在了。难道是地区和运营商的问题？
有没有其他人过来报一下魔都电信的使用情况

**Comment by streamgo** [comment]
应该是各地网络情况不同，所表现出来的不同差异。有的可能会好一些，有的就很差。

**Comment by zzgpku** [comment]
只有我的ip在掉么。。。从三百多掉到快两百了

**Comment by streamgo** [comment]
确实不稳定。我只有100左右。

2016-05-12 23:30 GMT+08:00 zzgpku <notifications@github.com>:

**Comment by liujindong121** [comment]
@dreamidiot 济南联通。应该是各地区单独拦截谷歌ip的原因吧

**Comment by jzp820927** [comment]
魔都电信 好像一直都是封锁最厉害的地方吧

**Comment by hwbasd** [comment]
深圳电信表示IP有4418个，延迟在31.

**Comment by CongZeng** [comment]
![image](https://cloud.githubusercontent.com/assets/17735842/15234154/49957524-18e1-11e6-9b0d-49a7d16d4db1.png)

**Comment by hulainwang** [comment]
GAEProxy状态信息

XX-Net 3.1.4 ，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	434
空闲	0
IP延迟	427
连接池(帮助)	新:0 h1:25 h2:3
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	200
屏蔽状态(帮助)	OK


我的非常稳定，广州电信的

**Comment by dreamidiot** [comment]
好吧，看来各地网络差异真的很大

**Comment by streamgo** [comment]
服！你的IP居然质量如此之好，数量如此之多！大写的服！

2016-05-13 7:54 GMT+08:00 hwbasd <notifications@github.com>:

**Comment by jeremy0714** [comment]
XX-Net 3.1.14 ，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	1410
空闲	0
IP延迟	176
连接池(帮助)	新:2 h1:17 h2:0
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK

**Comment by streamgo** [comment]
3.15 更改了proxy.ini 文件，修改了google为直连方式访问，由于部分IP不支持，所以会有问题。你直接用3.14版本的proxy.ini
替换就可以了。

在 2016年5月13日 上午10:38，jeremy0714 <notifications@github.com>写道：

**Comment by zzgpku** [comment]
![image](https://cloud.githubusercontent.com/assets/14359560/15236670/9e4d32c4-18f9-11e6-840a-92f7b3727e37.png)

**Comment by xxx233** [comment]
嗯，已经看到了，等下就给你们灭了。

**Comment by Antecer** [comment]
我想说2000多ip貌似并不多嘛，雾都移动在此路过...

> 属性	值
本地网络状态	OK
IP数量	5949
空闲	0
IP延迟	194
连接池(帮助)	新:3 h1:18 h2:3
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK

**Comment by zzgpku** [comment]
就在刚才，也就1分钟左右的时间。。。ip数量从二百多一瞬间掉到44了。。。
![image](https://cloud.githubusercontent.com/assets/14359560/15265441/2ae46dc6-19b6-11e6-9ba5-7c5161facfcf.png)

**Comment by sanan2015** [comment]
是bug吧？我这里完全没影响
![1463206505](https://cloud.githubusercontent.com/assets/12889741/15266644/d2c20594-19de-11e6-8bd7-42b310650a83.png)

**Comment by streamgo** [comment]
这是在拉仇恨啊！这IP延迟太霸道了！

2016-05-14 14:20 GMT+08:00 sanan2015 <notifications@github.com>:

**Comment by aiyh** [comment]
延迟9999的都没有抱怨，不看视频没多大关系
