### ISSUE TITLE
无法通过start.vbs启动

### ISSUE THREAD

**Issue by benpigchu** [XX-net/XX-Net#3370]
显示如下的错误信息
![image](https://cloud.githubusercontent.com/assets/9023067/15215395/e8df0076-1884-11e6-891a-c203f6f056aa.png)

**Comment by Cat7373** [comment]
估计是没下载完整，建议重新下载最新版本试试。

**Comment by benpigchu** [comment]
本问题是从windows10 预览版build14332 更新过来后新出现的问题

**Comment by benpigchu** [comment]
删除/code/version.txt后好了，可能是更新机制发现目前推送的最新的测试版本3.1.14低于实际的版本3.1.15而出现的bug，总之我先把自动更新关掉（

**Comment by benpigchu** [comment]
不对，是三个小时之前版本回滚了（

**Comment by a3349384** [comment]
我刚也遇到这个问题，看完代码后解决了。方法如下：
删除code目录下一个空的版本号目录即可。
