### ISSUE TITLE
3.1.15不能用google

### ISSUE THREAD

**Issue by ylivan09** [XX-net/XX-Net#3371]
1. 3.1.15不能用google搜索，gmail，地图等google服务

**Comment by kuchaguangjie** [comment]
换到 3.1.14 就可以了, 建议 xxnet 以后发布新版本先下基本测试.

**Comment by Cat7373** [comment]
本来就是测试版。。。

**Comment by kuchaguangjie** [comment]
@Cat7373 测试版 也是 要测试先下吧, 不是说测试版就不用做测试的 ...,
而且 如果是测试版本, 建议 放到 `develop` 之类的 branch, 而不是 放到 master, 基本稳定了再 merge 到 master.

而且 用户 pull 的时候, 谁知道哪个是不是测试版, 如果有想让用户帮助测试的目的, 那就 像上面说的 不要放到 master.

**Comment by kuchaguangjie** [comment]
另外, 最近 一天发布好几个版本, 建议 另建 branch 做开发, 不要这么频繁的发版本号, 稳定了再release 新版本号, 测试版用 `3.1.15 beta 3` 之类的 版本号, 不然用户根本没法分辨要不要更新.

**Comment by Cat7373** [comment]
如果你不喜欢折腾，那建议你直接选稳定版即可。
下载里也有稳定版与测试版之分。

**Comment by kuchaguangjie** [comment]
@Cat7373 程序员更新就是从 master pull 最新 或者 某个 版本 而已 ... , 不会重新整个下载 , master 的代码应该保持基本的稳定 ... , 我也 没看到 github 上哪里提示说 3.1.15 是测试版, 版本没带 `beta` / `rc` 之类的后缀,  通常 开源软件 都是 分 `alpha` `beta` `release candidate` `stable` 等 级别的, 这样方便判断是否更新, 比如: kernel 的版本发布: https://github.com/torvalds/linux/releases

**Comment by Cat7373** [comment]
你所说的这些对程序员而言很容易就能看懂，但是普通用户呢？
alpha 是啥？beta 又是啥？
我没见过啊？？？
分这些对普通用户而言根本没有什么帮助。

至于版本，下载页面里有稳定版与测试版的分别，至于旧的版本，普通用户根本不会去碰到，并不需要加什么标记。

对于程序员，稳定版还是测试版并没有什么意义吧，程序员更关系的还是到底改动了些什么。

**Comment by kuchaguangjie** [comment]
@Cat7373 Firefox 只是面向 程序员的么??? 去看看 Firefox 是怎么发布版本的好么. 算了 ...

**Comment by Cat7373** [comment]
对于普通用户，默认的更新选项是稳定版，对于他们而言，XX-Net 的更新与 FireFox 其实没有什么区别，也是很长一段时间才更新一次。

**Comment by jzp820927** [comment]
这几天发布版本是挺快的，可能是因为才 大重构的大版本的关系吧，问题较多，更新较快

**Comment by xxnet** [comment]
测试版，只给愿意折腾、尝试新功能，帮忙测试，属于自愿。
普通用户，不希望折腾，只需要关注稳定版即可。

​最近版本号更新较快，是考虑到几个因素：
+ 需要在不同平台上测试，因此需要大家帮忙，为了方便识别，采用正式的版本号来标识。
  所以看到一天几个版本。

+ 版本号没有标alpha/beta/RC1/RC2 这类后缀，是为了简化流程。
  一个版本在git上打了tag，至于是否稳定，要测试之后才知道，一旦稳定，就会保持推送给用户，而代码还是那个代码。
  另外维护了一个版本历史，记录每个版本都做了什么改动。

  版本号x.x.x 采用github推荐的命名规则：第一位表示兼容性大改变，第二位是新功能，第三位是修复bug。
  这次3.x.x相对2.x.x 在代码结构上做了大调整。
  3.2.x 相对 3.1.x 新增了http/2功能，内部流程也做了大调整
  3.1.14即达到稳定状态，前面的版本都算非稳定的开发/测试版本。


版本号命名规则，各项目是各自定义，没有一个权威标准，各有优缺点。
git分支规则，也是各有优缺点。
太多分支，参与开发的人会非常困惑。
目前XX-Net的规则是维持单一分支，并尽量保持可用，降低维护成本。
毕竟大家都是业余参与，人也不多，还是简单化好。

**Comment by jzp820927** [comment]
支持X大的意见，简化流程，把主要精力集中在性能优化，和 bug 修复上，而不影响使用的问题，可以不用太在意
