### ISSUE TITLE
python的窗口无法隐藏，即使在manual.ini设置visible = 0也无效

### ISSUE THREAD

**Issue by BLACKFLAGX** [XX-net/XX-Net#3379]
python的窗口无法隐藏，即使在manual.ini设置visible = 0也无效
也已经按照操作
; 不要修改这个文件。
; 每次升级时，会自动覆盖这个文件
; 可以直接在webUI中设置，或者创建data/gae_proxy/manual.ini然后放入你自定义的部分配置

也无效，前几个版本是有效的，现在设置了也一直显示。

**Comment by BLACKFLAGX** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.15

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2121 good:493
network-status: OK
connected-link: new:6 used:0
worker: h1:23 h2:2
scan-ip-thread-num: 50
ip-quality: 619
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SCP-028** [comment]
我是开start.bat,然后点一下右下角状态栏的XX-Net，Python窗口就消失了。

**Comment by Cat7373** [comment]
请使用 vbs 来启动，而不是编辑配置。

**Comment by Cat7373** [comment]
visible 这个配置在 XX-Net 里应该是不存在的。

**Comment by Swan-dev** [comment]
现在推荐使用vbs启动，visible是在最近的一个版本中移除了，这个设置好像是继承自goagent。

**Comment by Cat7373** [comment]
是在这里移除的
https://github.com/XX-net/XX-Net/commit/cbb88eadf4832bd290cd764af1efd4ee844df022#diff-f188a46a7aff388f8f920a1497de7dfcL12

**Comment by BLACKFLAGX** [comment]
已经解决！谢谢！
