### ISSUE TITLE
ip数量为0，延迟9999，每次提示扫描IP，半天都没结果

### ISSUE THREAD

**Issue by garbitsch** [XX-net/XX-Net#3395]
重装系统，重装软件，半天没结果，换了lantern，但不稳定，求助各位，谢谢！

XX-Net Status:

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36
xxnet-version: 3.1.14

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
很明显，没IP

**Comment by dvquest** [comment]
:x: :parking: 的默认连接数貌似限制为:keycap_ten:,线程跑不起来,也许还有其它问题,最好还是装个win7吧! :end:

**Comment by yeahwu** [comment]
xp去打个补丁就好了，
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
数量调节为2014

**Comment by garbitsch** [comment]
谢谢
