### ISSUE TITLE
xxnet 在梅林固件里安装不了 ，已按教程做个无数遍了，请各位大神看看 ！已经到第9不了

### ISSUE THREAD

**Issue by haotia** [XX-net/XX-Net#3396]
梅林 6.6上面安装 XX 在第9部的时候出错。没有反应，好像提示没有找到程序。具体请看图。
谢谢
![33](https://cloud.githubusercontent.com/assets/10241594/15274154/ca0401ea-1ade-11e6-8196-c4f38e898d0d.png)
![35](https://cloud.githubusercontent.com/assets/10241594/15274156/d5684b2c-1ade-11e6-835d-4f8c44e1750c.png)
![37](https://cloud.githubusercontent.com/assets/10241594/15274158/d9fec170-1ade-11e6-8fef-a24cb5212c75.png)
![39](https://cloud.githubusercontent.com/assets/10241594/15274174/175e6d7c-1adf-11e6-952f-c304d3d6e116.png)
![32](https://cloud.githubusercontent.com/assets/10241594/15274178/1cdb8406-1adf-11e6-8cd5-0fb7d5f436c6.png)
请问我是不是什么地方操作错误，望大神指教

**Comment by jzp820927** [comment]
没有XX运行的截图？不知道什么情况

**Comment by haotia** [comment]
路由器里面安装，都没有安装好怎么截图啊

**Comment by jzp820927** [comment]
就看到第3个图片提示 pyopenssl 没安装，你可以先试着运行下 XXNET，看看日志，再根据日志信息，来处理

**Comment by sorsoso** [comment]
看贴图你只是在路由上装了entware,你还需要安装openssl python py-openssl 然后再看教程吧

**Comment by aiyh** [comment]
我只能说 其实有命令可以自动安装依赖包的

**Comment by haotia** [comment]
哦，谢谢 我是小白求问可以告诉我 是什么命令吗

Date: Mon, 16 May 2016 02:37:38 -0700

**Comment by haotia** [comment]
请问怎么在路由器里面 安装 pyopenssl  我是小白 不懂啊
Date: Sun, 15 May 2016 08:27:40 -0700

**Comment by haotia** [comment]
怎么添加源啊，谢谢

**Comment by jzp820927** [comment]
可以试试 pip install pyopenssl ，路由器不是太熟

**Comment by weiwei007** [comment]
opkg install python-pyopenssl

**Comment by haotia** [comment]
谢谢你，但还是不行
但还是不行我给你截图你帮我看看吧，请问是不是下载这些插件路由器要翻墙啊

**Comment by edwinhuish** [comment]
#3417 
这个应该能帮到你。
