### ISSUE TITLE
刚才电脑黑屏，强制关机以后再打开发现XX的ip都丢了，要重头开始扫描了……

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#3408]
有可能改进下软件防止丢失全部数据这个状况发生吗？

**Comment by xiaoyan94** [comment]
manual的配置还在

**Comment by ARCHOTZ** [comment]
试过，good_ip.txt会变成跟原来同样大小的空白文件。

**Comment by usami2525** [comment]
同遇到过这问题，用XX的时候停电，恢复供电以后IP就全没了..

**Comment by xxnet** [comment]
扫描日志文件递增的，不会全丢失。
可以考虑从扫描日志文件中恢复，格式做些处理就好。

**Comment by ztjal** [comment]
这个问题我以前也反映过，是程序上的不好。
应该先生成如“good_ip.txt.new”之后再判断“good_ip.txt.new”文件大小，不是再删除“good_ip.txt”和改名new。

**Comment by Cat7373** [comment]
我也遇到过一次0.0

**Comment by Cat7373** [comment]
我好像是待机恢复IP就都没了，太久了记不清了。。。

**Comment by g8up** [comment]
XX-Net 3.2.5
待机唤醒后 ，GAEProxy状态信息页显示的 IP 数量是0。

**Comment by jzp820927** [comment]
还是放在 服务器上 7×24 小时跑好。

**Comment by yfdyh000** [comment]
应用那个补丁后仍遇到过丢失，可能需其他方案，比如检测和恢复bak。

**Comment by Cat7373** [comment]
试试打开扫描日志，然后全选，粘贴到导入 IP 里，会自动识别出来里面的 IP 地址并导入。
然后再执行一次检查所有 IP。
