### ISSUE TITLE
小米路由器R1D XX-NET部署教程，并求redsocks部署教程。

### ISSUE THREAD

**Issue by edwinhuish** [XX-net/XX-Net#3417]
由于多个网友请求，现先附上小米路由R1D，XX-NET的简单部署教程。

---
### 配置Python 到小米路由R1D:

主要参考http://me.deepgully.com/post/5638916786880512 ，
这位大神已经弄好小米路由器R1D的Python完整版。如果你想直接用, 请到这下载http://deepgully.qiniudn.com/xiaomi/python2.7_xiaomi.zip , 

解压之后 ssh 传到小米路由器的 /userdisk/python 目录, 
并修改 /etc/profile 文件，加入 export PATH=/userdisk/python/bin:${PATH}, 重连 ssh 就能执行 python 了 。

其他方面，这个作者写得比我详细，请直接看他的网页吧。

---

部署完Python之后，基本上都已经可以了，直接将XX-NET完整版拷贝到/userdisk/XX-Net 下，或者其他位置，一般只能放到硬盘里，R1D的ROM太小，放不下XX-NET 完整版，尝试过XX-MINI，可是貌似不理想，既然完整版XX-NET放在硬盘里运行起来没有问题就不研究XX-MINI了。

最后一步，就是使XX-NET 自启，网上说在/etc/init.d 和/etc/rc.d添加文件都可以，为了避免问题，我还是简单粗暴地在原有文件上修改添加需要启动的文件。
![image](https://cloud.githubusercontent.com/assets/5207925/15526123/0783a9aa-2262-11e6-9906-86719e4ae71a.png)

![2](https://cloud.githubusercontent.com/assets/5207925/15529849/f15e9588-2282-11e6-9672-6d36d70868e6.jpg)

![3](https://cloud.githubusercontent.com/assets/5207925/15529850/f198ffe8-2282-11e6-859d-3b7371f6b2d9.jpg)

完成后效果图如下：

![image](https://cloud.githubusercontent.com/assets/5207925/15349313/7a3d7682-1d04-11e6-97f8-7847a779df6a.png)

---

**Comment by wookongCN** [comment]
有部署教程没？

**Comment by dvquest** [comment]
电脑用SwitchyOmega,移动设备用proxy.pac,只能这样了.

**Comment by edwinhuish** [comment]
@wookongCN 弄好再考虑上教程，其实就是部署好路由器的Python后，用Python运行xx-net，并添加开机自启动。

**Comment by edwinhuish** [comment]
@dvquest 这样意义不大啊，搞个路由器翻墙，就是需要全智能翻墙。。

**Comment by jzp820927** [comment]
要在路由器上做智能翻墙，估计只能通过透明代理了吧

**Comment by edwinhuish** [comment]
@jzp820927 是的，是需要透明代理，可是，怎么装呢？看了很多redsocks2的贴子，按照教程，弄不成功。

下面这个是我已经成功架设到小米路由器R1D的截图。

![image](https://cloud.githubusercontent.com/assets/5207925/15349313/7a3d7682-1d04-11e6-97f8-7847a779df6a.png)

**Comment by jzp820927** [comment]
我以前配置过 redsocks，也没成功，不知道问题出在哪儿

**Comment by lele2010lele** [comment]
求教程

**Comment by sntea** [comment]
怎添加开机自启动？我在rc.local 文件添加了下面一行代码，并没有自启动，请问你的能自动启动吗？
python /userdisk/data/xx-net/code/default/launcher/start.py

**Comment by edwinhuish** [comment]
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()

**Comment by edwinhuish** [comment]
@Cat7373 @xxnet  @xxnet2 @yeahwu  请问大神们，有没有路由器部署redsocks2或者类似透明代理的教程？网上看的都不行。

**Comment by sntea** [comment]
@edwinhuish 按照你说的，在/etc/init.d/plugin_start_script.sh中添加了
/userdisk/data/python/bin/python /userdisk/data/xx-net/code/default/launcher/start.py &
终于可以开机自启动了！
谢谢!

**Comment by edwinhuish** [comment]
@sntea 你有配置透明代理么？

**Comment by edwinhuish** [comment]
@lele2010lele @wookongCN 忘了提示你们，简单写了教程上去。

**Comment by littleShy** [comment]
为啥下载你们发的python在我的小米路由mini上无法执行？
root@XiaoQiang:/extdisks/sda1# python -v
/extdisks/sda1/python2.7/bin/python: line 1: syntax error: unexpected word (expecting ")")
root@XiaoQiang:/extdisks/sda1# which python
/extdisks/sda1/python2.7/bin/python

**Comment by jzp820927** [comment]
语法错误，是不是 python 版本太低了。

**Comment by littleShy** [comment]
不清楚，反正用不了，后来我换成用opkg 下载安装到外置存储器，都下好了，但还是运行不了，提示import time 错误，唉，折腾啊。话说潘多拉和openWrt还有小米官方的固件区别在那里？我用的是官方开发版，已开ssh的，哦对了我是小米路由mini。

**Comment by jzp820927** [comment]
就是定制不一样吧，就好像 android 和 miui 的区别一样

**Comment by edwinhuish** [comment]
@littleShy 我附上的这个python只是对应小米路由R1D的，mini的还不如直接刷一个OPENWRT呢。

如果你不想刷固件，请自行寻找mini的PYTHON,或者自己编译一个。

**Comment by littleShy** [comment]
@edwinhuish 哦，那我回去试试openwrt的固件。

**Comment by magian1127** [comment]
我是RD2 部署成功...最新的版本...但是 网上下的 python2.7.5 版本太低..无法支持http/2...
希望谁能编译下 python2.7.12 包含 pyopenss最新版就好了..这样就可以比较好的支持新版xx

**Comment by edwinhuish** [comment]
@magian1127  部署成功也没有用，没有扶墙工具。无法自动翻墙。

**Comment by CHN008** [comment]
先回复收藏了!

**Comment by roc1010kmt** [comment]
樓主這個對應其他路由器嗎?OPENWRT15.05.1的系統.
安裝好python2.7.9.6,顯示沒有openssl?
啟動不了xxnet?

**Comment by jzp820927** [comment]
pyopenssl ，python-openssl 安装了没。

**Comment by edwinhuish** [comment]
@roc1010kmt 我的这个仅仅对应小米路由R1D，因为小米路由是阉割版的openwrt。如果不是阉割版的话，缺什么模块就装上就好了。

**Comment by roc1010kmt** [comment]
~# opkg install pyopenssl
Unknown package 'pyopenssl'.
Collected errors:
 * opkg_install_cmd: Cannot install package pyopenssl.

**Comment by roc1010kmt** [comment]
~# opkg install pyopenssl python-openssl
Unknown package 'pyopenssl'.
Package python-openssl (2.7.9-6) installed in root is up to date.
Collected errors:
 * opkg_install_cmd: Cannot install package pyopenssl.

**Comment by roc1010kmt** [comment]
~# opkg install pyopenssl python-openssl --force-depends --force-ov
erwrite
Unknown package 'pyopenssl'.
Package python-openssl (2.7.9-6) installed in root is up to date.
Collected errors:
 * opkg_install_cmd: Cannot install package pyopenssl.

**Comment by roc1010kmt** [comment]
~# python proxy.py
Traceback (most recent call last):
  File "proxy.py", line 63, in <module>
    from OpenSSL import version as openssl_version
ImportError: No module named OpenSSL

**Comment by jzp820927** [comment]
看样子，openssl 还是没装上，据我所知就是这2个包，如果不行，就不太清楚了，没有 openwrt 环境，不能测试。

**Comment by edwinhuish** [comment]
@roc1010kmt 你的数据源更换一下，然后重新安装就好了，网上很多替换数据源的教程。

**Comment by roc1010kmt** [comment]
Traceback (most recent call last):
File "proxy.py", line 63, in 
from OpenSSL import version as openssl_version
File "/usr/lib/python2.7/site-packages/OpenSSL/init.py", line 8, in 
from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in 
from OpenSSL._util import (
File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in 
from cryptography.hazmat.bindings.openssl.binding import Binding
File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in 
from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: File not found

**Comment by roc1010kmt** [comment]
怎麼過一段時間就會顯示Killed,強制退出?

**Comment by jzp820927** [comment]
意思是能运行？

**Comment by roc1010kmt** [comment]
@jzp820927 系統平均負荷到過3.13左右,正常嗎?

**Comment by roc1010kmt** [comment]
xxmini可以啟動,xxnet啟動路徑是哪個?
XX-Net/code/default/launcher/start.py?
XX-Net/code/default/gae_proxy/start.py

**Comment by jzp820927** [comment]
XX-Net/code/default/launcher/start.py

**Comment by roc1010kmt** [comment]
@jzp820927 XX-Net/code/default/launcher/start.py啟動報錯?
XX-Net/code/default/gae_proxy/start.py可以啟動,怎麼回事?

**Comment by jzp820927** [comment]
应该都可以，只要能运行就行了，

**Comment by JasonQWJ** [comment]
部署的教程链接打不开啊
能不能写写怎么部署Python？

**Comment by jzp820927** [comment]
一般都自带 python 吧

**Comment by edwinhuish** [comment]
@jzp820927 @JasonQWJ 小米路由器并没有自带python，下载链接没有问题，文档链接已经修复。不过既然已经有编译好的python，就没有必要看那位大神的编译过程了。

**Comment by jzp820927** [comment]
好吧，没完过路由器的飘过。

**Comment by JasonQWJ** [comment]
@edwinhuish 下载链接就是编译好的 python了吗？

**Comment by edwinhuish** [comment]
@JasonQWJ 是的。你们有透明代理的教程？否则架设好，还是得配合chrome的Proxy SwitchOmega，没有多大实际意义。

**Comment by linhua55** [comment]
透明代理的话，可以使用 proxifier软件，不过需要把  证书 导入到系统中而不是浏览器中。另外firefox好像不认系统的证书，如果是那样的话，就需要额外将  证书  导入到firefox中

**Comment by edwinhuish** [comment]
@linhua55 需要导入证书没有问题，可是需要知道如何将redsocks之类的代理部署到小米路由器R1D上

**Comment by linhua55** [comment]
@edwinhuish 
opkg命令不能用？   没用过openwrt

**Comment by edwinhuish** [comment]
小米路由器不能用。。。

**Comment by linhua55** [comment]
@edwinhuish 
自己照着 shadowsocks的例子，编译吧
http://ju.outofmemory.cn/entry/211796

**Comment by edwinhuish** [comment]
@linhua55 公司的路由器，不敢乱动，况且网上的都是新版的小米路由，R1D的教程非常少。。。

**Comment by jzp820927** [comment]
太牛了吧，公司也用小米路由器

**Comment by xiaonan0527** [comment]
怎么在小米路由上初始化xx－net？

**Comment by edwinhuish** [comment]
照着我的教程就可以部署了。。。

**Comment by kirbyzhu** [comment]
@edwinhuish 主要参考http://me.deepgully.com/post/5638916786880512 ，这个链接打不开啊

**Comment by xiaonan0527** [comment]
把我mac上使用过的xxnet上传到小米路由，可以启动，但是无法起作用

**Comment by edwinhuish** [comment]
是的，需要搭配客户端的SwitchyOmega，没有透明代理，不能直接翻墙。

**Comment by roc1010kmt** [comment]
小米路由器卡不卡？機能低的路由器很卡的。

**Comment by edwinhuish** [comment]
刷tomato 了，感觉还好吧。现在如果要入手的话，不建议用小米路由，可玩性太低

**Comment by roc1010kmt** [comment]
tomato是什麼？番茄？

**Comment by jzp820927** [comment]
tomato 是路由器估计

**Comment by JasonQWJ** [comment]
用opkg的方式在 r2d上安装了 python2.7  可是不能运行  不知道是什么原因  安装的时候一切顺利，各种依赖全部都自动安装了  提示 python 没找到    profile里已经设置好路径了。。。。。

**Comment by edwinhuish** [comment]
是的，每个路由器用的python不一样，需要编译。

**Comment by JasonQWJ** [comment]
@edwinhuish 今天折腾劲上来了  装了 python 和 git 全部  -ash: python&& git :not found    

因为把 opkg的路径设定在 userdisk 所以 profile里指定了路径 
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/userdisk/data/opkg/usr/bin
这样没有错误吧？  难道 git 也不能装在 r2d上？？

**Comment by edwinhuish** [comment]
不清楚，你还是搜一下R2D的python吧，anyway, 就算你折腾成功也没有什么用，因为没有透明代理，最终你的chrome还是需要有switchyomega，做不到智能翻墙，倒不如直接用电脑翻。

**Comment by sntea** [comment]
你好！
 
  您的邮件我已经收多到
 
  我现在在忙，无法亲自回复您的邮件。我将在稍后，尽快给您回复。
