### ISSUE TITLE
xx-net,goproxy 下载32M

### ISSUE THREAD

**Issue by littlebigdream** [XX-net/XX-Net#3419]
我用XXNET下载VPN GATE，但是下载完成的zip包只有32m,而且也不能正常打开，
实际的文件包是50几兆。
另外，说一下 我之前用过goproxy，上传过goproxy的服务端，
不知道和这个有没有关系。
请问，
xxnet下载限制的问题怎么解决，是用xxnet最新版重新部署appid吗？？？

**Comment by 821938089** [comment]
不要用goproxy的服务端，有问题的，作者正在修复
重新部署过吧

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/issues/362
虽然没实际试过，不过应该跟这个问题差不多。

**Comment by Wrecking-Ball** [comment]
@xxnet 
下载了xxnet3.1.17 ，然后重新部署appid,
再次去下载vpn gate想实验一下，发现还是不行，报time out。
![default](https://cloud.githubusercontent.com/assets/18393082/15322663/a6cddc76-1c70-11e6-8a3a-53a4bebf2b83.PNG)
然后根据 @Cat7373  所说，改变 threads ，但是不论20或者 1 都不行，都报错timeout。

而且看youtube，只能看见首页，不论点哪个视频，都会自动跳到首页。。。。
在 https://appengine.google.com   点击appid后面的 running，也会报错，报 网页被重定向多次，无法打开。 原来都是 提示 服务端在xxx时 更新到 xxx版本，请更新客户端。。。

现在又换回 xxnet3.1.14, 一切正常，只是下载还是有32m 限制。。。

**Comment by masktao** [comment]
@Wrecking-Ball 
跟你一样的问题,升级了goproxy的最新服务端,下载只有32M了,然后想用最新的xx-net重新部署,无法完成
