### ISSUE TITLE
部署页面，显示状态异常

### ISSUE THREAD

**Issue by fhzyfjy** [XX-net/XX-Net#342]
还没有部署就显示： 
![2015-05-05_201340](https://cloud.githubusercontent.com/assets/11030827/7472288/91e61cce-f363-11e4-8716-6ac0fe3ac1a7.jpg)

![image](https://cloud.githubusercontent.com/assets/11030827/7472273/69dae2a0-f363-11e4-93ee-fd0d79586fc3.png)

**Comment by jzmswe** [comment]
运行start.bat，在IE页里填好各项，点击部署，然后看CMD里的信息，不用再管IE页了。

**Comment by fhzyfjy** [comment]
按jzmswe网友说的做了，CMD无任何显示啊

**Comment by xxnet** [comment]
我在trunk上提交一个patch，下次提示会显示更多信息，看看到底是什么状态引起的
