### ISSUE TITLE
Win10(x64)爆音貌似不是XX-net的问题

### ISSUE THREAD

**Issue by cya03** [XX-net/XX-Net#3420]
没开**XX-net**，只开了个**迅雷**下载和**IE**，也出现过一次爆音，应该是Win10本身的问题吧。

**Comment by JollyDan** [comment]
跟win10有啥关系。。

**Comment by Michael7CAT** [comment]
弱弱的问句爆音是什么样的？

**Comment by streamgo** [comment]
以前我用WIN10时偶尔会有此情况。当有网络动作时，声音会卡顿。现在换回WIN7了。

**Comment by dvquest** [comment]
用win10一直带耳机,从未听到过爆音.
会不会是声卡驱动问题?可以考虑用驱动精灵类的软件多尝试一些驱动版本试试.

**Comment by yj1** [comment]
是卡住然后beep，类似嗡嗡的声音，严重时听着很恐怖，我新买的电脑自带的win10 ，因为这个声音专门去售后做了检测，怀疑是电脑本身的问题，但最后发现是这个软件的问题。

**Comment by dvquest** [comment]
@yj1 我看了下我的声卡是Realtek High Definition Audio(貌似大多数主板带的都是这个),驱动版本6.0.1.7647.
你们有爆音的是不是该核查一下声卡型号和驱动看是否有共通点?

**Comment by yj1** [comment]
平常不会卡主，只有看视频或者听音乐的时候有，不过最新的稳定版本已经很少了。

**Comment by theGTAmaster** [comment]
我是win10刚出来更新的，半年前开始用的XX -NET，在用之前没出现过，所以应该是软件问题，google group上有个人推荐了个方法，不知道管不管用（我在测试中），你们也可以试试
