### ISSUE TITLE
国内用什么DNS比较好，快速，纯净，无劫持？？？

### ISSUE THREAD

**Issue by littlebigdream** [XX-net/XX-Net#3423]
请问  国内用什么DNS比较好，快速，纯净，无劫持？？？

**Comment by panzer1313208** [comment]
你还不如直接问什么DNS可以上谷歌。

**Comment by panzer1313208** [comment]
毕竟不能上谷歌的DNS全部都是被劫持的DNS。

**Comment by huimiao638** [comment]
现在的icp经常搞http劫持，没用。

**Comment by yeahwu** [comment]
俺来推荐一个吧，就怕你不敢用，黑帮头子的dns，大概没人敢劫持吧
延时大概比什么阿里云，114要好得多吧
CNNIC 
首选：1.2.4.8
备用：210.2.4.8

**Comment by ztjal** [comment]
要用TCP的，不要用UDP的。

**Comment by 200433zc** [comment]
> 俺来推荐一个吧，就怕你不敢用，黑帮头子的dns，大概没人敢劫持吧 延时大概比什么阿里云，114要好得多吧 CNNIC 首选：1.2.4.8 备用：210.2.4.8

差点信了😁
