### ISSUE TITLE
梅林上面部署 XX-NET 成功，但不能看视频和手机不能翻，请问什么原因（附日志和截图）

### ISSUE THREAD

**Issue by haotia** [XX-net/XX-Net#3430]
@May 18 04:35:54.429 - [INFO] SSL use version:TLSv1_2
May 18 04:35:54.434 - [INFO] OpenSSL support alpn
May 18 04:35:54.530 - [INFO] load ip range file:/tmp/mnt/sda1/entware.ng/XX-Net/data/gae_proxy/ip_range.txt
May 18 04:35:54.901 - [INFO] load google ip_list num:536, gws num:536
May 18 04:35:55.031 - [INFO] OpenSSL support alpn
May 18 04:35:55.035 - [DEBUG] get ip:217.18.145.100 t:323
May 18 04:35:55.058 - [DEBUG] get ip:203.233.96.12 t:345
May 18 04:35:55.269 - [INFO] load manual.ini success
May 18 04:35:55.282 - [DEBUG] ## GAEProxy set keep_running: True
May 18 04:35:55.287 - [INFO] ------------------------------------------------------
May 18 04:35:55.288 - [INFO] Python Version : 2.7.11
May 18 04:35:55.291 - [INFO] OS : Dist:; Version:; ID:
May 18 04:35:55.292 - [INFO] Listen Address : 0.0.0.0:8087
May 18 04:35:55.293 - [INFO] GAE APPID : 
May 18 04:35:55.294 - [INFO] Pac Server : http://0.0.0.0:8086/proxy.pac
May 18 04:35:55.294 - [INFO] ------------------------------------------------------
May 18 04:35:55.304 - [DEBUG] network is ok, cost:1684 ms
May 18 04:35:55.675 - [DEBUG] get ip:66.96.226.210 t:346
May 18 04:35:55.872 - [DEBUG] create_ssl update ip:203.233.96.12 time:573 h2:0
May 18 04:35:55.871 - [DEBUG] create_ssl update ip:217.18.145.100 time:613 h2:0
May 18 04:35:55.873 - [DEBUG] get ip:203.233.96.46 t:354
May 18 04:35:56.176 - [DEBUG] get ip:203.233.96.30 t:366
May 18 04:35:56.235 - [DEBUG] create_ssl update ip:203.233.96.46 time:245 h2:0
May 18 04:35:56.236 - [DEBUG] get ip:172.217.3.193 t:401
May 18 04:35:56.252 - [DEBUG] create_ssl update ip:66.96.226.210 time:357 h2:0
May 18 04:35:56.536 - [DEBUG] create_ssl update ip:203.233.96.30 time:247 h2:0

![48](https://cloud.githubusercontent.com/assets/10241594/15348024/73c0e66e-1cf9-11e6-9796-dc9df0fa0acb.png)
![46](https://cloud.githubusercontent.com/assets/10241594/15348038/86681c4c-1cf9-11e6-9e67-0d08ca6f076d.png)
![44](https://cloud.githubusercontent.com/assets/10241594/15348045/9442add2-1cf9-11e6-93c2-1ea767014e05.png)

![49](https://cloud.githubusercontent.com/assets/10241594/15348276/df49aa54-1cfb-11e6-8cf1-879b21da21e1.png)

请问是什么问题，是还有什么插件没有安装吗

**Comment by zhenhappy** [comment]
证书装了吗

**Comment by haotia** [comment]
请问证书装在路由器里面 还是电脑里面，电脑里面以前就可以看，还有请问是什么证书

**Comment by zhenhappy** [comment]
打开http://路由器ip:8085
![image](https://cloud.githubusercontent.com/assets/9161946/15348344/8b2edeb6-1cfc-11e6-9376-55fe82bada39.png)
看到CA证书状态

**Comment by haotia** [comment]
关键是这个怎么下载到路由器上面去，我电脑上面本来就安装的有，路由器里面没有
