### ISSUE TITLE
梅林上面部署 XX-NET 成功，但不能看视频，手机不能翻，请问什么原因（附日志和截图）

### ISSUE THREAD

**Issue by haotia** [XX-net/XX-Net#3434]
怎么帖子自动关闭了
![49](https://cloud.githubusercontent.com/assets/10241594/15348918/2f76d15a-1d01-11e6-82ba-f6be3395fd9a.png)
![48](https://cloud.githubusercontent.com/assets/10241594/15348962/69ed24e2-1d01-11e6-848c-b426671f4364.png)
![46](https://cloud.githubusercontent.com/assets/10241594/15348967/769d9c1c-1d01-11e6-8129-5536ae5d9efb.png)
![44](https://cloud.githubusercontent.com/assets/10241594/15348987/a0323592-1d01-11e6-8cac-4565d3fc1952.png)

**Comment by edwinhuish** [comment]
你的应该跟我的差不多吧？

去我的那里一起讨论吧。 #3417
