### ISSUE TITLE
求教--xx-net执行start.vbs闪退，无法启动

### ISSUE THREAD

**Issue by bohemianalfred** [XX-net/XX-Net#3443]
前几日更新3.1.17版开始正常，重启电脑后就再也无法进入xx-net。表现为执行start.vbs闪退。先后用最近几个版本覆盖后均同样表现。且进入code\default\launcher文件夹执行start.py显示无可执行程序。后单独安装python2.7.11版后进入系统控制台手动执行phthon start.py后反馈如下信息：

C:\Users\yangjun\Desktop\XX-Net-2.0.2\code\default\launcher>python start.py
Traceback (most recent call last):
  File "start.py", line 66, in <module>
    from win_tray import sys_tray
  File "C:\Users\yangjun\Desktop\XX-Net-2.0.2\code\default\launcher\win_tray.py"
, line 18, in <module>
    import win32_proxy_manager
  File "C:\Users\yangjun\Desktop\XX-Net-2.0.2\code\default\python27\1.0\lib\win3
2\win32_proxy_manager.py", line 22, in <module>
    CONNECTIONS = winreg.OpenKey(winreg.HKEY_CURRENT_USER, CONN_PATH, 0, winreg.
KEY_ALL_ACCESS)
WindowsError: [Error 2]

C:\Users\yangjun\Desktop\XX-Net-2.0.2\code\default\launcher>

同期使用了xx-net mini，使用正常，只是xx-net各个版本以及系统多处目录下均无法运行。

求问高手上述情况如何解决？怎么才能恢复xx-net的正常工作。先行谢过。

**Comment by Cat7373** [comment]
实际上，你应该在 C:\Users\yangjun\Desktop\XX-Net-2.0.2\ 目录，运行下面的命令

    python code\default\launcher\start.py

同时建议试试用 bat 启动，看看有没有什么输出，以及看看 data\launcher\launcher.log 里的内容。

**Comment by yeahwu** [comment]
几种原因吧
1:请关掉系统防火墙，360之类
2:系统补丁缺失，打开update打补丁
3:迅雷

**Comment by bohemianalfred** [comment]
@Cat7373 是这样，我查找过log，但是launcher.log里面没有任何内容。用.bat启动同样是自动执行.vbs后闪退。如果直接运行.vbs不会出现控制台而是直接没反应。

刚又以python code\default\launcher\start.py试了一下，还是上述描述的现象。

**Comment by bohemianalfred** [comment]
@yeahwu 关掉防火墙试验过，而且此前开着防火墙用也都正常，就是前天突然开始这杨的。系统补丁目前是齐全的，没有遗漏。迅雷平日里基本不开，而且连同后台服务我都会关掉。

**Comment by yeahwu** [comment]
其实这种情况俺也遇到过，是在一台全新环境的电脑上。后来打上补丁，关掉防火墙就好了。
究其原因，应该是脚本的问题。

**Comment by bohemianalfred** [comment]
起初我怀疑过是系统变量的问题，但后来越弄越不明白。暂时只好用xx-net mini替代使用。

**Comment by yeahwu** [comment]
你放在那，说不定过几天就好了，windows上是有这种毛病。

**Comment by bohemianalfred** [comment]
ok，解决掉了。按照控制台里的信息一步一步找，发现是注册表internet setting项下丢失了connections子项，导致启动xx-net过程中无法读取系统网络连接设置。重新补充上之后用新下载的xx-net直接运行、导入证书。。。。搞定。

**Comment by simonasd** [comment]
@yeahwu 应该和补丁没有关系，我接触过的电脑都是在系统安装之初就关闭了自动更新，从未安装过任何补丁，但运行XX并不曾出错。

此外，打补丁会引入“升级到win10”的**feature**

**Comment by yeahwu** [comment]
现在win10都这么流氓了？俺还在xp的镜像，想虚拟机里装一个

**Comment by simonasd** [comment]
@yeahwu 可在Google news中搜一下，媒体报道了不少“中国网民的不满”
