### ISSUE TITLE
桌面应用程序如何科学上网

### ISSUE THREAD

**Issue by kevin4fly** [XX-net/XX-Net#3448]
桌面应用程序，比如**dropbox**如何才能科学的上网呢？

**Comment by yfdyh000** [comment]
Dropbox的选项里不是有代理设置吗，设为HTTP 127.0.0.1 8787 就行了吧。其他支持设置的也可以同样设置。不支持的可以用proxifier或者其他类似软件。

**Comment by yeahwu** [comment]
8787是lantern
8087是xxnet

**Comment by yfdyh000** [comment]
嗯。一时写错了。

**Comment by yeahwu** [comment]
其实俺也用的是dropbox，就用网页版，也很便捷。

**Comment by kevin4fly** [comment]
嗯， 谢谢你们的回复。我之前都是用VPN翻墙的，设置好了之后，所用的应用程序都可以直接连接，没有用过proxy代理。

我现在使用proxy设置下，看看效果。

**Comment by kevin4fly** [comment]
急死人了，好不容易安装了最新的**dropbox**， 点击preference，一直都没有反应。

xxnet 可以做成或者设置成像VPN那样，一处设置，所有的地方都不用管了，都可以连接上网吗？

**Comment by jzp820927** [comment]
除非把 XX 安装在路由器上，并且配置 透明代理

**Comment by kevin4fly** [comment]
我使用的一些app都不知道怎么设置proxy，比如*BlueStacks***， 感觉好麻烦。

**Comment by kevin4fly** [comment]
这个是我的*XX-Net\data\gae_proxy\manual.ini*文件，我想设置让我的iphone也可以翻墙。手机上*HTTP PROXY：Auto http://192.168.0.105:8086/proxy.pac*, 但是还是不能翻墙，能说下原因，谢谢。

>[listen]
ip = 0.0.0.0 
port = 8087

>[gae]
appid = kevin4fly|kevin4fly01|kevin4fly02|kevin4fly03|kevin4fly04|kevin4fly05|kevin4fly06|kevin4fly07|kevin4fly08|  kevin4fly09|kevin4fly10|kevin4fly11

>[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by jzp820927** [comment]
你先试试在手机上的浏览器 能不能打开 http://192.168.0.105:8086/proxy.pac 这个地址？

**Comment by kevin4fly** [comment]
@jzp820927 谢谢你的回复。可以访问上面的这个文件。

**Comment by dvquest** [comment]
@kevin4fly 安装证书没
[这个问题以前帖子讨论过,链接https://github.com/XX-net/XX-Net/issues/3349#issuecomment-218475345](https://github.com/XX-net/XX-Net/issues/3349#issuecomment-218475345)

**Comment by kevin4fly** [comment]
@dvquest 谢谢你的回复。我不会安装证书。囧。。

我访问了http://192.168.0.105:8085 这个地址，然后在*CA status(Download)*栏，点击Download连接，可是一直都没法download成功。

**Comment by kevin4fly** [comment]
尝试通过邮件发送**CA.crt**文件到收件邮件客户端，但是无法打开。现在不知道怎么样才能安装证书了。

**Comment by dvquest** [comment]
@kevin4fly 点击下载,弹出的新窗口应该是:安装描述文件,点安装,输入密码确定安装就可以了

**Comment by kevin4fly** [comment]
@dvquest 谢谢你的回复， 我重新尝试使用safari浏览器安装成功了。之前一直都是用的google chrome浏览器，chrome不能安装的。

**Comment by kevin4fly** [comment]
@dvquest 所有的步骤都弄完了，但是手机还是无法打开google。sadly。。。

**Comment by kevin4fly** [comment]
@dvquest 我使用的是**XX-Net 3.1.17** 不知道这算不算是个原因

**Comment by dvquest** [comment]
@kevin4fly 我之前还在想你可能用的不是safari,访问google请用https

**Comment by kevin4fly** [comment]
@dvquest https协议访问google 依然失败

**Comment by jzp820927** [comment]
访问不了，有什么错误提示？

**Comment by Swan-dev** [comment]
用Safari 访问`http://192.168.0.105:8085`，下载 `ca.cert`证书并安装。在WIFI设置中设置代理，代理地址为 __192.168.0.105:8087__ ，这样浏览器是可以访问的。Chrome等其他应用因为苹果没有提供权限是无法实现代理的。

**Comment by kevin4fly** [comment]
@dvquest @jzp820927 @Swan-dev 非常感谢大家的帮助。今天早上，我再次使用手机访问google的时候，已经成功了。不知道是重启的电脑的缘故，还是重启了xxnet。再次感谢大家的帮忙。

提出个小小的意见吧，可以完善一下wiki，毕竟使用这个功能的人还是蛮多的。我也阅读了现在[wiki](https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config#%E7%9B%AE%E5%89%8Dgoagent%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%9C%89)里面的说明，但是讲的非常的模糊.

**Comment by kevin4fly** [comment]
问题已经解决，关闭问题。

**Comment by tomorrowin** [comment]
@kevin4fly 我的情况跟你一样，也是都设置好了，cr也安装好了，电脑也重启了，手机还是无法使用
