### ISSUE TITLE
能不能在当前设置的代理状态前加一个对钩

### ISSUE THREAD

**Issue by qingshengwen** [XX-net/XX-Net#345]
能不能像goagent那样，在当前设置的代理前显示一个√，让用户一眼就能看出来当前代理是什么状态
就是全局通过GoAgent代理，全局PAC智能代理，取消全局代理
这3个状态，当前选的哪个，就在这个前面加√

**Comment by xxnet** [comment]
可以，希望哪位能够提交补丁

在 2015年5月5日 下午10:23，qingshengwen <notifications@github.com>写道：

**Comment by xxnet** [comment]
已解决
