### ISSUE TITLE
XX-net一周使用报告

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#3460]
XX-net近期速度较稳定，开网页速度个人觉得较为满意，没有很慢的时候，总体上来说是一种匀速、平稳的状态。一切状态良好。

感谢XX-net团队为谷歌用户开通了这条绿色高速通道。真诚感谢！！

**Comment by jzp820927** [comment]
主要看视频，网页那都不是事

**Comment by 80068** [comment]
@jzp820927 嗯嗯：D，看视频没问题。Lantern（兰特）就会比较慢
