### ISSUE TITLE
XX-net在Linux下的使用问题

### ISSUE THREAD

**Issue by GitFuture** [XX-net/XX-Net#3462]
关于Linux下的使用

在windows下面的任务栏可以点击图标进入配置页面，那么在Linux下面怎么便捷的进入配置页面呢？
在issues里面找了一圈，貌似没有提过这个问题。自己手动输入url也可以，但是有没有方便的方式呢？

Linux版本为kali linux
（Linux sun 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux）

浏览器为kali自带的浏览器Iceweasel

**Comment by jzp820927** [comment]
更便捷的方式就是，吧这个url加入收藏夹，或者建立桌面快捷方式

**Comment by GitFuture** [comment]
我的天 
好主意！

**Comment by GitFuture** [comment]
对了，那如果我想要完全全局代理或者暂时取消代理呢？
在linux下面没有图标啊
![Uploading image.png…]()
能像windows那样直接切换吗？

**Comment by jzp820927** [comment]
应该有图标的，不知道你是怎么启动的

**Comment by GitFuture** [comment]
我是直接在.bashrc里面加入alias xxnet="path-to-xxnet" 
然后用terminal启动的，并没有看到有图标啊
![image](https://cloud.githubusercontent.com/assets/7582298/15431408/4c7ff0c4-1edc-11e6-9017-282608526d19.png)

**Comment by GitFuture** [comment]
![image](https://cloud.githubusercontent.com/assets/7582298/15433818/79937a0e-1ee6-11e6-9714-c58abc948558.png)
哦找到了，在桌面的右下角
