### ISSUE TITLE
求助，打不开配置页面……

### ISSUE THREAD

**Issue by Pokemonfavor** [XX-net/XX-Net#3464]
之前更新了XX-Net 3.1.14，原本是能使用的，然后我就去配置专属APPID了然后……
localhost:8085就打不开了……
无限处于载入状态，完全进不去页面……然后相应的当然FB之类的也上不去……
用Chrome浏览器审查元素，什么都看不见……

**Comment by jzp820927** [comment]
是不是开着代理打开 8085 的

**Comment by Pokemonfavor** [comment]
也没开着别的代理啊……

**Comment by Pokemonfavor** [comment]
好吧，解决了……看起来是卡巴斯基给它墙了……关掉卡巴后就能进去了……
