### ISSUE TITLE
那啥纪念日快到了！X-Tunnel试用流量大放送，需要的留下注册邮箱

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3471]
需要的请到web页面注册，登录。一定要注册帐号，登录后再留下注册的邮箱，如图
使用方法
https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B

![_2016-05-07t05-05-21 277z](https://cloud.githubusercontent.com/assets/13328328/15448929/daa317e4-1fa1-11e6-9350-80ce512c345c.png)

**Comment by sunyik** [comment]
sorrowxin@gmail.com  谢谢好人！

**Comment by yj1** [comment]
yj_313@outlook.com  感谢

**Comment by yeahwu** [comment]
@sunyik 速度够快的，已转

**Comment by sunyik** [comment]
@yeahwu 哈哈，谢谢！请问你知道为啥我的xx-net用不了么，可以打开谷歌，但是不能搜索，显示Google Instant is unavailable. Press Enter to search.，大神求解==

**Comment by sun3596209** [comment]
scj3596209@gmail.com
又赶上了，感谢！~

**Comment by TonyDong51089** [comment]
chuchu2921@126.com 谢谢

**Comment by fuckGFW2015** [comment]
fangdoggotohell@gmail.com好人一生平安

**Comment by jaqty3** [comment]
chenjuncheng888@gmail.com 谢谢

**Comment by baidusile** [comment]
baiduson@gmail.com
谢谢你@yeahwu 辛苦了！

**Comment by haotia** [comment]
谢谢 haotia@live.com

**Comment by vSolo** [comment]
x@xx.net 让我们红尘作伴活的潇潇洒洒，策马奔腾啊，共享人世繁华。

**Comment by yeahwu** [comment]
@haotia 你这帐号，请注册，登录。其他已转
@sunyik 升级最新版试试

**Comment by 973204** [comment]
gf973204@hotmail.com
谢谢

**Comment by lineex** [comment]
linnot@163.com 
谢谢

**Comment by yeahwu** [comment]
已转

**Comment by skimen0818** [comment]
nick.tong1982@gmail.com
谢谢！

**Comment by yeahwu** [comment]
已转，大家可以留下注册邮箱，到时统一发放。

**Comment by gaupen1186** [comment]
gaupen1186@gmail.com

**Comment by gaupen1186** [comment]
gaupen1186@gmail.com
非常感谢！

**Comment by acrossabc** [comment]
2015happygo@gmail.com先谢了！

**Comment by yechao25038** [comment]
单身狗怒送流量

**Comment by LongShaWu** [comment]
longwusha@gmail.com
谢谢了！

**Comment by dayuanqiezi** [comment]
290623613@qq.com

**Comment by Rongronggg9** [comment]
1211536697@qq.com
还有你想说的难道是“稍有常识”的纪念日？

**Comment by yeahwu** [comment]
@Rongronggg9 你这个帐号转不过去，请先注册登录。64，自由，送流量
其他已转

**Comment by 0Oo0Oo0Oo** [comment]
谢谢啦

**Comment by crystoneme** [comment]
送64G么 
bigboy@xx-net.com

**Comment by lele2010lele** [comment]
1152009145@qq.com楼主好人

**Comment by TheCalling** [comment]
joiedevivre#null.net

**Comment by xiaoyan94** [comment]
ruguo_0904@163.com么么哒

**Comment by everhopingandwaiting** [comment]
351022095@qq.com  多谢(o^^o)

**Comment by novicewu** [comment]
novice.wu@gmail.com 多谢！

**Comment by everhopingandwaiting** [comment]
yuxingzhi170@163.com  不好意思，上面那个没有注册 ， 使用这个注册的 ，谢谢哈

**Comment by HappysurfBlocking** [comment]
账户
1435545184@vip.office365edu.cn

**Comment by HappysurfBlocking** [comment]
谢谢了

**Comment by zzgpku** [comment]
zzgpku@gmail.com  
楼主哪来的这么多流量，真是日了狗了
多谢~

**Comment by SCP-028** [comment]
jzhou0317#gmail.com 谢谢！

**Comment by lingshow** [comment]
yyc354019【at】gmail.com

好人一生平安～！

**Comment by 935352** [comment]
935352@qq.com

谢谢啊

**Comment by longyuan86** [comment]
longyuan86#gmail.com

Thx!

**Comment by hezma** [comment]
mesctan@gmail.com
谢谢喽

**Comment by UUNNFLY** [comment]
XTUNNEL@GMAIL.COM
谢谢

**Comment by april4513** [comment]
joshuakongchao@gmail.com  多谢

**Comment by 821938089** [comment]
821938089@qq.com
多谢

**Comment by xiuluo** [comment]
chen919695074@gmail.com，多谢

**Comment by JMaxime** [comment]
jianchimaxime@gmail.com
多谢

**Comment by newsuneg** [comment]
newsuncxl@gmail.com ,多谢

**Comment by CongZeng** [comment]
wzqaz10@gmail.com 给我些谢谢

**Comment by lighttopp** [comment]
lighttopp@outlook.com 谢啦！

**Comment by redmetal** [comment]
redmz361@gmail.com多谢！

**Comment by magnet1215** [comment]
magnet1215@gmail.com

**Comment by lazureice** [comment]
lazureice@gmail.com
THX~

**Comment by Wrecking-Ball** [comment]
xiaolili527@gmail.com  
thanks!!

**Comment by zaney** [comment]
nm460255424@gmail.com 
谢谢啦 :)

**Comment by Black94** [comment]
jxl1032705826@gmail.com
谢谢啦

**Comment by samanxx** [comment]
samantha23ll@gmail.com
thank you~

**Comment by thebestwayto** [comment]
xpirad@gmail.com 谢谢！！

**Comment by yeahwu** [comment]
转完，收工。下次有空再说！

**Comment by hellowx** [comment]
hellolionwx@gmail.com  
tks!

**Comment by Nickforever** [comment]
825250938@qq.com
今天才看到，谢谢啦

**Comment by yeahwu** [comment]
@hellowx 你这个帐号转不过去，请先注册登录
@Nickforever 已转
活动结束了，下次请早

**Comment by leave0** [comment]
lastsnow@gmail.com 谢谢

**Comment by yeahwu** [comment]
已转，就这样吧，锁了
