### ISSUE TITLE
开代理后刷网页会频繁出现连接已重置

### ISSUE THREAD

**Issue by wxy1106** [XX-net/XX-Net#3477]
-----------
使用直接连接的情况下没问题，使用XX-NET自动切换的话，chrome打开网页会经常出现连接已重置，刷新也打不开，这个情况出现在最近2周，以前没遇到过。
![qq 20160522101643](https://cloud.githubusercontent.com/assets/18569573/15451745/9c9426a4-2006-11e6-994a-bfd02ea82ad9.png)

-----------
诊断信息：
sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 98
network-status: OK
connected-link: 7 / 3
scan-ip-thread-num: 0
ip-quality: 403
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by wxy1106** [comment]
另外过几分钟再刷新就可以正常打开了

**Comment by 821938089** [comment]
更新版本

**Comment by jzp820927** [comment]
版本太老了吧

**Comment by wxy1106** [comment]
更新了最新版本，目前没有问题
