### ISSUE TITLE
一些新功能及建议

### ISSUE THREAD

**Issue by 821938089** [XX-net/XX-Net#3479]
1.希望gws和gvs的ip能够分开，以方便直连时直接使用gwsip，如果没有gwsip时，能够智能切换到gae代理模式
2.高级-检查所有ip里面能够增加一个定期自动检查功能
例如：当延迟高于___ms时，每隔____小时(分钟/天)启动检查
3.能够手动启动空闲模式。
4.导出ip能够只导出低于___ms的ip，能够增加支持goproxy的ip格式

**Comment by yeahwu** [comment]
1:直连只适应与google类网站，xxnet已经设置好了那些google类网站直连，那些gae转发。而且谁告诉你gvs不能直连的？
2:检查所有ip没有必要性
3:空闲模式，你把线程调到0，就是空闲模式了
4:一大堆找ip，转换格式工具。
