### ISSUE TITLE
为什么YouTube的电影基本都看不了？总是出现错误。需要在哪里设置一下吗？

### ISSUE THREAD

**Issue by hwuscut** [XX-net/XX-Net#348]
所使用的版本是1.13.6 ，前几天用1.12.2还偶尔可以看，这是怎么回事啊？我这里网速很快，下载2M/s。
 
![2015-05-06_18-44-56](https://cloud.githubusercontent.com/assets/12271927/7491880/cafcb4ec-f420-11e4-8d65-7c3e437aa70e.png)

**Comment by xxnet** [comment]
你先放着跑一个晚上，明天再试试

在 2015年5月6日 上午6:51，hwuscut <notifications@github.com>写道：

**Comment by hwuscut** [comment]
谢谢你的回复！我试试看。
