### ISSUE TITLE
希望加入Dropbox客户端支持

### ISSUE THREAD

**Issue by liangxiaorui** [XX-net/XX-Net#3482]
希望作者能加入让Dropbox客户端支持的功能，因为没办法同步dropbox实在是比较痛苦，翻墙最大的用处就是google和dropbox。谢谢。

**Comment by jzp820927** [comment]
应该可以用吧，自己做客户端设置代理

**Comment by liangxiaorui** [comment]
请问在dropbox里面怎么设置代理？ip设置为127.0.0.1? 那端口呢？

**Comment by jzp820927** [comment]
8087

**Comment by liangxiaorui** [comment]
试过了，不行哦。总是报连接代理服务器出错，但是我看XX-NET是正常工作的，而且网页版是可以打开的，就是客户端不行。请问还有什么需要注意的吗？配置如图所示：
![image](https://cloud.githubusercontent.com/assets/8081152/15454072/eca74f14-205f-11e6-855f-d69c75fd56eb.png)

**Comment by jzp820927** [comment]
我去，端口还能无效，不会是客户端本身的问题吧，还有，你导入证书到系统了没

**Comment by liangxiaorui** [comment]
证书已经导入的了。客户端应该是没问题的，我换成VPN去连接，就能连接上的，就是XX-NET不行。请问还有什么地方可能有问题？能否麻烦把配置截个图看看？我猜是不是XX-NET的证书不被信任。我的证书导入如下：
![2016-05-22_22-34-47](https://cloud.githubusercontent.com/assets/8081152/15454532/b4c25f68-206d-11e6-8289-4da3b3ae2376.png)

**Comment by jzp820927** [comment]
无法建立安全连接。那应该是证书问题，把XX的日志贴出来看看，要 dropbox 的日志

**Comment by lele2010lele** [comment]
如果你是更新的新版本。你删掉原来的证书，然后重新信任试试

**Comment by liangxiaorui** [comment]
我发现重新导入证书，今早重启后，不设置代理居然可以了。。不确定重启后dropbox还行不行。但是如果设置代理，就会报错。请问各位有配置代理?
xx-net里面的log是：ssl error: [SSL:TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca(_ssl:c:590), create full domain cert for host:d.dropbox.com

另外也测试了一下google云盘客户端，直接无法登录。

**Comment by liangxiaorui** [comment]
发现一个诡异的问题，我在公司就可以连接dropbox，在家里就一直连接不上，也没报什么错，就一直显示正在连接。等了好几十分钟还是一样，也没报错。请问下还有什么原因导致连不上？家里的网络是电信的，带宽也有30M，感觉应该不会是网速的问题，难道被电信封了？
![2016-05-23_19-05-18](https://cloud.githubusercontent.com/assets/8081152/15468956/c53599b2-2119-11e6-8af2-5bb106d53f29.png)

**Comment by liangxiaorui** [comment]
感谢jzp820927,lele2010lele,问题已经解决了，还是DNS被污染的问题，开启XX-NET，安装并使用DNSCrypt就好了，谢谢两位帮助，贴出方法，也希望帮助到需要的童鞋。
![2016-05-23_19-35-13](https://cloud.githubusercontent.com/assets/8081152/15469561/92a6632e-211d-11e6-9696-c5f85208fe21.png)

**Comment by largewhale** [comment]
@liangxiaorui 我也遇到同样的问题，用DNScrypt可以解决该问题，谢谢！
PS：这个issue可以close了，这个可以帮助大家了解件问题状态。

**Comment by jzp820927** [comment]
估计 LZ 都已经失踪了，close 的希望不大了。

**Comment by largewhale** [comment]
没有失踪~~

liangxiaorui <notifications@github.com>于2016年10月29日周六 下午9:13写道：

Closed #3482 <https://github.com/XX-net/XX-Net/issues/3482>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/XX-net/XX-Net/issues/3482#event-840909533>, or mute the
thread

**Comment by shixuguo** [comment]
这个方法在win上如何解决？

**Comment by beerlover086** [comment]
@liangxiaorui @jzp820927 @lele2010lele 
几位大佬，设置DNSCrypt登录dropbox办法还管用不？能不能提供下DNSCrypt的 .exe下载地址
找到了msi格式的，但是装不了
谢谢

**Comment by jzp820927** [comment]
现在好像 XXNET 就提供防污染的 DNS 了，不用安装 DNSCrypt 应该也行，你可以试试。
dropbox客户端是直连还是要设置代理通过xx-net登录，你分别试试不就知道了。
