### ISSUE TITLE
希望加入Profile功能

### ISSUE THREAD

**Issue by arslan2012** [XX-net/XX-Net#3483]
我是在笔记本上用，家里wifi和公司wifi可用的IP不一样
所以就导致在家里扫描完IP到公司IP数会减少很多，每次换wifi我都要重新扫描一边IP才可以正常用。
所以可否加个类似profile的功能，把扫描到的IP分开

**Comment by 821938089** [comment]
你装2个xx-net，到公司用公司的，到家用家的

**Comment by simonasd** [comment]
对于频繁在几个环境下切换的用户，似乎是有意义的。要手动实现也容易，建立两个data文件夹，要切换的时候用脚本重命名一下
