### ISSUE TITLE
关于扫描超时的取值

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#349]
目前的机制有一种问题，如果已有IP达到了最大值（目前3000）并且握手参数优良，扫描进程仍然会继续扫描新IP，并且不会降低标准，导致出现扫描出的IP是最慢，刚添加就移除的情况，浪费了时间和资源。
例如：
```
May 06 21:53:08 - [INFO] scan_ip add ip:95.143.84.154 time:5384
May 06 21:53:08 - [DEBUG] sort ip time:7
May 06 21:53:08 - [INFO] remove_slowest_ip:95.143.84.154 handshake_time:5384
```

扫描线程应该在IP库达到最大值时采用已有最慢的握手值作为超时标准，默认值与最慢值取低者。

并且在IP库足够时，应该考虑暂停网络扫描，改为检查已有IP和移除超时失效项。

**Comment by zhanglaplace** [comment]
确实是个好的建议。

**Comment by xxnet** [comment]
资源方面，CPU、带宽，都应该对用户影响不大。

检查已有ip是否可用，连接不上的删除，以前是这么做的，刚删除了相关代码，意义不大：
ip能不能用，也许今天不行，明天又可以了？这会不行，过会又可以了？


另外，ip 没有足够的时候，只有更好。
google会不断调整ip，ip段也可以不断增加，所以扫ip，慢慢扫吧，让电脑干活不累。


2015-05-06 20:11 GMT-04:00 zhanglaplace <notifications@github.com>:

**Comment by yfdyh000** [comment]
资源方面，不是大问题，但没有必要浪费用户和Google的带宽和资源。

我认为相比不稳定的IP，未知的新IP更靠谱一些。过会又可以的情况，扫描也可以覆盖，反正没忽略。

重点问题是，扫描、添加并保存、移除并保存，几秒内一轮并持续发生，不觉得设计有点问题吗，明明可以改善成不行动。

**Comment by xxnet** [comment]
如何判断有足够多足够好的ip？

个数不能说明问题，以前扫到4000个，但很多不能用了或变得不稳定。
质量也难以评估，几次连接失败，应该删除？
之前的版本连续3次连接失败，删除导致没有ip可用。

对于资源方面，目前用户量不多，对google影响很小，暂时可以不考虑。
以后用户多了确实是个问题。
设计确实不够理想，不过这算目前找到相对有效的方案。

当然改进是没有止境的，你也可以试试改一个版本，给大家测试效果。
我相信，更多的思路，是非常有帮助的。

在 2015年5月6日 下午11:47，YFdyh000 <notifications@github.com>写道：
