### ISSUE TITLE
封锁快到高潮期了！不好了！

### ISSUE THREAD

**Issue by panzer1313208** [XX-net/XX-Net#3490]
百度贴吧，美食吧被封了，海贼王吧也被封了。lantern吧被封了。我草这你妈了个逼的共产党是狗急跳墙了？还是你妈了个臭逼的百度审查员他全家暴毙了？我草你个血妈了个逼的

**Comment by ming-ge** [comment]
我看的一个小说的贴吧前两天还好好的，今天一看被封了。

**Comment by xiaoyan94** [comment]
没有啊  没被封

**Comment by yechao25038** [comment]
看楼主的名字好像昂是lantern的吧主？

**Comment by simonasd** [comment]
去建立一个“抄党章吧”，看他敢不敢封

**Comment by panzer1313208** [comment]
@yechao25038 哎呀，你是？

**Comment by panzer1313208** [comment]
@simonasd 应该敢

**Comment by yechao25038** [comment]
@panzer1313208  之前在贴吧逛过。这类帖吧早晚要封，就在贴吧建议你弄一个备用的google论坛。文学类贴吧全被封了，三国演义等古典文学也封了，，不知道这类有版权么？。。

**Comment by chumuye** [comment]
墙外有啥代替贴吧的好去处？

**Comment by jzp820927** [comment]
@chumuye google groups，github issues

**Comment by simonasd** [comment]
@yechao25038 作者去世超过一定年限，版权自动进入公有领域

@jzp820927 感觉Google group用着还是不舒服，所以至今也没正式加入

**Comment by jzp820927** [comment]
只是个习惯问题，我现在用 groups 感觉很习惯了。只不过 groups 上面的人气，没有 github issues 人气旺。最关键还说 groups 要翻，github 不用翻。

**Comment by simonasd** [comment]
@jzp820927 确实是习惯问题。groups一直火不起来，恐怕还是不习惯的人占多数

**Comment by jzp820927** [comment]
我现在基本上都在 github 上混了，groups 越来越冷清了。
