### ISSUE TITLE
Cannot Install pyOpenSSL automatically

### ISSUE THREAD

**Issue by hzxie** [XX-net/XX-Net#3498]
在Terminal中依旧提示我

`start`中相应的源代码是这样的:

```
if ! python -c 'import OpenSSL' 2> /dev/null; then
        echo 'You have not installed pyOpenSSL yet.'
        if [[ $- == *i* ]]; then
            # Install pyOpenSSL
        else
            # Seems reached here...
            echo 1>&2 'Please install pyOpenSSL.'
        fi
fi
```

我试着在Terminal中执行相应的判断:

```
if [[ $- == *i* ]]; then
    echo 1
fi
```

在Terminal中的输出结果的确是1.

然后我就不知道是什么情况了.

![screenshot from 2016-05-23 08 56 28](https://cloud.githubusercontent.com/assets/1730504/15490871/2cd855da-219e-11e6-89f0-c45d20404f69.png)

**Comment by zjhzxhz** [comment]
Debian 8.4 + Python 2.7.9

**Comment by xxx233** [comment]
自己修复，这事你应该搞得定。
