### ISSUE TITLE
CPU占用过高

### ISSUE THREAD

**Issue by joey4859** [XX-net/XX-Net#35]
win8.1 / Surface Pro 3 / FirFox 36.0
用一段时间之后会很占CPU, 睿频达最高值
退出再重新打开XX-NET,又会正常一段时间。

另外春节快乐！

![Uploading Ashampoo001.png . . .]()

**Comment by yqfang** [comment]
ubuntu下偶尔也会有cpu占用过高的问题，而且没有规律可循，期待下个版本优化

**Comment by xxnet** [comment]
gedit XX-Net/goagent/3.1.34/local/proxy.py
 修改第210行：
===================
    do_profile = False
===================
改成：
    do_profile = True
===================
Linux在命令行启动:
cd XX-Net/goagent/3.1.34/local
python proxy.py

在CPU很高时，用浏览器访问http://127.0.0.1:8084/quit
  goagent就会退出，并在命令行输出CPU开销高的地方

Windows平台，类似的方法启动：
python27\1.0.1\python.exe goagent\3.1.34\local\proxy.py

把输出的内容贴出来反馈，谢谢

**Comment by xxnet** [comment]
1.1.0 版本对所有线程都检测处理了一遍，希望能解决这个问题。

**Comment by xxnet** [comment]
1.3.1 中解决这个问题
  问题出在openssl 的sendall调用上，改成send就好了，不过还需要观察。
