### ISSUE TITLE
关于IP超时的移除

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#350]
我没有看到过因为IP连接超时引发的good_ip更新，似乎只是在内存中记录。而且好像基本没用，因为仅在超时出现50次后才更新，这在3000 IP随机取用的情况下，基本不可能发生。https://github.com/XX-net/XX-Net/blob/ad4dc870ee0f771b8d1f23d76408330d4a46047d/goagent/3.1.49/local/google_ip.py#L346 

建议改成每次都更新good_ip中的握手数据（到超时值），使其短期内不被优先采用，在未来被第二次检查时就移除。

如果是三次或更多次检查，也许需要增加good_ip的字段。或者用超时值倍数表示握手值，2000是一次，4000是两次这样。

**Comment by xxnet** [comment]
以前的策略是3次就移除，  这次才改成50次。

原因是墙最近的策略，很容易就触发到封锁，导致大量ip连接失败，结果就有用户反馈只剩下几十个ip。

所以现在的策略不会轻易的删除ip，也许下次能用呢。

增加good_ip的字段，有考虑“过连续失败的次数”作为一项指标。不过后来觉得没有必要，删除了又怎样？没有ip照样上不去。

每次连接失败，ip的握手时间都会递增，慢慢就会变成最慢的ip。
如果有扫到更好的ip，自动会把慢的替换掉的。

所以哪些总是无法连接的ip，就会慢慢被新发现的ip替换掉了，新陈代谢。


考虑到新版本下载后，data目录是空的，很多人没有把data目录拷贝过来，之前找到的ip又要重新找。
所以做好自动升级变得很重要。自动升级后，data目录会自动保存下来，继续发挥作用。


在 2015年5月6日 下午3:47，YFdyh000 <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
然而我没有看到那些超时ip的状态有被在good_ip持久保存，似乎每次xx-net关闭后记录就消失了。
握手值好像没有被更新，下次还会尝试那些可能已经超时失效很久的IP。
似乎已有库的失效IP似乎不会被移除，不知道是什么原因。

我感觉搜索新IP比尝试旧的曾经超时的IP几率更大一些。

如果第一次连接失败（超时），是否有必要即时增加尝试线程呢，比如第一次失败后同时尝试2个IP，并选用可用的。这样也许能避免大量超时IP而引发的超时或者长时间延滞？

**Comment by xxnet** [comment]
保存握手时间，被限制为10秒一次，减少写磁盘的次数。
在使用ip的地方，触发是否保存，而不是链接失败时。

所有状态，只保存了握手时间。链接失败，也是通过不断增加的握手时间去表示。

搜索、连接，都不用太过于频繁，不能因为连接失败，就增加连接的线程数。
建立连接的线程数，在很多环节是有限制的。

所以新版中采用了另一个策略：
建立链接是无法快起来的，所以平时就要去建立链接，并且保持住好的链接，在需要时，就能够使用了。

这样来解决用户体验。


在 2015年5月6日 下午10:51，YFdyh000 <notifications@github.com>写道：
