### ISSUE TITLE
xx-net播放youtube正常，但有的视频显示上传者禁止在您国家播放怎么解决？

### ISSUE THREAD

**Issue by stevenzhanglijun** [XX-net/XX-Net#351]
如题，正常播放很多视频，速度也很快，就是有时遇到显示“上传者禁止在您国家播放”怎么解决啊。谢谢！

**Comment by causlayer** [comment]
设置php代理，但目前版本设置php代理有问题

**Comment by stevenzhanglijun** [comment]
php要改配置参数吗？

**Comment by causlayer** [comment]
https://github.com/XX-net/XX-Net/issues/343
原来可以用，目前版本用不了
