### ISSUE TITLE
修改了一下主页，大家看看有没有好看一点。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3518]
x大不在，俺就使劲折腾，看他回不回来？:smirk::smirk:

https://github.com/XX-net/XX-Net

**Comment by iceliquid23** [comment]
看起来更加有范了。 ^^

**Comment by 935352** [comment]
千万不能罢工，祖国的翻墙党全靠你们啊

**Comment by alanOO7** [comment]
老被自动删除文件咋整，白名单什么的都设置了，我都快给搞哭了

**Comment by jzp820927** [comment]
删除啥文件？

**Comment by Cat7373** [comment]
![](https://github.com/XX-net/XX-Net/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by junegucas** [comment]
我很无聊的指出，语法有问题。
1. Web proxy **tools**.
单复数 a web proxy tool ||  web proxy  tool chains
2. XX-Net is a more **functions** gae proxy which can **help you get** through firewalls.
a more powerful would be better
help及物动词or不及物动词？
3. links
Usage : https://github.com/XX-net/XX-Net/wiki/使用方法

Update : https://github.com/XX-net/XX-Net/wiki/更新方法
链接里中英文统一一下，是否好些
https://github.com/XX-net/XX-Net/wiki/how_to_use
https://github.com/XX-net/XX-Net/wiki/how_to_update

**Comment by yeahwu** [comment]
刚关闭了自动更新
@junegucas 洋文实在太差，见笑了
链接中英文实在是不能统一，中文wiki，改了是一堆乱码
