### ISSUE TITLE
升級後无法登陆

### ISSUE THREAD

**Issue by matthewinhim** [XX-net/XX-Net#352]
升级后无法所有网站都登陆不了了，不知道什么原因。
![20150508](https://cloud.githubusercontent.com/assets/11926131/7507058/32205162-f49c-11e4-95bd-648da5559a13.jpg)
![20150508](https://cloud.githubusercontent.com/assets/11926131/7507059/38b3e8ae-f49c-11e4-91ea-7b91a961cb7b.jpg)
![2015050802](https://cloud.githubusercontent.com/assets/11926131/7507060/38c83f8e-f49c-11e4-8673-4bb941cb8c88.jpg)

**Comment by xxnet** [comment]
请用1.13.6

2015-05-06 21:34 GMT-04:00 matthewinhim <notifications@github.com>:
