### ISSUE TITLE
自动升级已关，建议大家还是手动升级。然后也没俺啥事了！大家再见

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3522]
更新方法：
https://github.com/XX-net/XX-Net/wiki/更新方法
然后自动更新发生问题，这个锅俺不背:smile: :smile:

**Comment by jzp820927** [comment]
推荐 linux 或者 win 安装有 git 的用户 git pull 方式升级，备份都不用，一条命令搞定。只下载改动的文件，速度很快。

**Comment by linhua55** [comment]
想要自动更新的话,可以给用户提供用git进行更新的选项
这个用git进行自动更新的方法可以写个教程(折腾一下)
1. 先安装个git的客户端,需要到其他地方额外下载安装, (安装过程也要写个教程, 把git可执行文件添加到path环境变量中)
2. 再写个简单的bat脚本,用户根据提示选择是否更新,更新到那个版本,执行命令,进行更新. 但是有一个很头疼的问题就是初始化下载的时候也需要用git clone进行下载,否则手动下载的zip文件解压后不是个git仓库.

想定制个简易git客户端,但是能力不足,然后就只能这样了, 这样也能减少维护成本.,,就是不利于传播, 因为
前面那个头疼的问题,所以不能以传送文件的方式,给别人发送安装包,需要先安装git客户端,然后才能在线下载安装包进行安装,虽然可以用git bundle的形式提供离线的bundle文件,但这个过程还是较繁琐. 如果将27M多大小的git客户端集成安装包里去, 放在慢速的github里供别人下载,这显然是不行.

变通的方法是: 还是提供原来的zip安装包, 在web页面中添加用git更新的流程(git环境初始化按钮), 内部下载git的安装包,并直接解压(不是安装),提取出来git文件夹,里面包含git可执行文件,然后放到xxnet主目录下的git文件夹下,这时就不用设置环境变量了,程序后台直接调用git重新下载(clone)新版本的xxnet,到另外一个文件夹下,当下载完成的时候, 再切换当前的xxnet文件夹到用git下载的xxnet文件夹, 这和现如今更新的逻辑差不多.

**Comment by lele2010lele** [comment]
好复杂，你们为啥不直接下载？

**Comment by jzp820927** [comment]
其实 git 更新，也就是第一次要折腾一下，要把整个仓库下载下来，最重要的是 .git 目录，包含有仓库数据，git 更新就全靠他了，第二次及以后更新就很方便了，属于折腾一次，幸福一辈子的事情，我觉得还是值得的。

**Comment by yeahwu** [comment]
@linhua55 看着都好复杂，俺还是研究一下现有的更新方式吧！

**Comment by linhua55** [comment]
`静默安装`不错
http://www.cnblogs.com/BeyondTechnology/archive/2011/01/15/1936511.html
http://cdjiangchao.blog.51cto.com/635910/1397920
