### ISSUE TITLE
晚上上youtube经常出现人机验证提示

### ISSUE THREAD

**Issue by jeremy0714** [XX-net/XX-Net#3527]
我用我自己的appid， 白天还好啊，为什么晚上会这样呢？ 

![qq 20160527223117](https://cloud.githubusercontent.com/assets/12095602/15611009/e1e385a8-245a-11e6-9ae7-020df2f288f2.png)

**Comment by jeremy0714** [comment]
这个人机验证很无聊啊

![qq 20160527223431](https://cloud.githubusercontent.com/assets/12095602/15611080/374c2bda-245b-11e6-881a-6ef94f584cd4.png)

**Comment by yeahwu** [comment]
嗯，这个无解，youtube直连的话，h2就用不了
gae转发，就避免不了验证
