### ISSUE TITLE
前两天有点不务正业了，还是分享一下自个编译的lantern，去弹窗，默认关闭pac

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3528]
go1.6.2，5.27最新源码编译，
默认关闭，可手动打开
```
AutoReport:  false,
AutoLaunch:  false,
ProxyAll:    false,
SystemProxy: false,
```
建议：
删除C:\Users\Name\AppData\Roaming\Lantern下所以文件后启动lantern
配合autoproxy，或者SwitchyOmega来使用，http 127.0.0.1:8787

只提供windows和linux版  下载
https://github.com/yeahwu/recycle-bin/files/286670/5.27.y.lantern.tar.gz

**Comment by yeahwu** [comment]
lantern编译越来越麻烦了，需要挂代理。

**Comment by linhua55** [comment]
持续集成(CI)服务可以吗? 像[Appveyor](https://www.appveyor.com/)

**Comment by yeahwu** [comment]
你的意思像goproxy那样?
lantern编译还是有点麻烦的

**Comment by linhua55** [comment]
对,像goproxy那样

**Comment by yeahwu** [comment]
这个好像很麻烦，再加上也不会持续更新的。就是玩玩
