### ISSUE TITLE
XP SP3 启动sart.bat后，只生成空的data文件夹格式，无法安装

### ISSUE THREAD

**Issue by oliverpep** [XX-net/XX-Net#3534]
一台老旧的机器，系统xp sp3,IE 8.0 安装了firefox 43.0.1，正常解压XXnet 3.1.4,运行start.bat后只生成一个空的data文件夹目录格式，包括gae_proxy、launcher文件夹，这两个子文件夹下没有任何文件。把这个data删除后，再试，还是生成空data.（tcp-z补丁已打）
 是不是xxnet不支持xp,还是有什么组件没安装，请大家指教，谢谢了

**Comment by jzp820927** [comment]
有没有日志

**Comment by oliverpep** [comment]
> 有没有日志``
主程序都没跑起来，没有日志的

**Comment by jzp820927** [comment]
那就不好判断问题了。运行start.bat 的时候，CMD 窗口，什么东西都没有麽？

**Comment by oliverpep** [comment]
`那就不好判断问题了。运行start.bat 的时候，CMD 窗口，什么东西都没有麽？`
CMD窗口闪一下就没有了。

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/issues/3443

**Comment by teN-XX** [comment]
在XX-Net的文件夹，就是有start.vbs的文件夹，Shift+右键空白处，选择在此处打开命令行窗口。
粘贴下面的指令后回车，然后把输出的内容粘贴到这里来看看。

    "code\default\python27\1.0\python.exe" "code\default\launcher\start.py"

**Comment by yeahwu** [comment]
昨天虚拟机里装了xp，果然也遇到这个问题，新版修复了一下，
 https://codeload.github.com/XX-net/XX-Net/zip/3.2.0

**Comment by playbeta** [comment]
你好，我用的最新版3.2.0(6也是如此)也是这个问题，无法启动：

Microsoft Windows XP [版本 5.1.2600]
(C) 版权所有 1985-2001 Microsoft Corp.

D:\XX-Net-3.2.0>code\default\python27\1.0\python.exe code\default\launcher\start
.py
Traceback (most recent call last):
  File "code\default\launcher\start.py", line 37, in <module>
    from instances import xlog
  File "D:\XX-Net-3.2.0\code\default\launcher\instances.py", line 12, in <module
>
    xlog = Logger(file_name=log_file)
  File "D:\XX-Net-3.2.0\code\default\python27\1.0\lib\noarch\xlog.py", line 32,
in __init__
    self.set_color()
  File "D:\XX-Net-3.2.0\code\default\python27\1.0\lib\noarch\xlog.py", line 67,
in set_color
    import ctypes
  File "D:\XX-Net-3.2.0\code\default\python27\1.0\lib\ctypes\__init__.py", line
10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: 由于应用程序配置不正确，应用程序未能启动。重新安装
应用程序可能会纠正这个问题。

**Comment by yeahwu** [comment]
用上面链接的3.2.0版

**Comment by playbeta** [comment]
是的，我用的就是上面的那个3.2.0版
