### ISSUE TITLE
XX-Net为啥老是卡?

### ISSUE THREAD

**Issue by Alanomn** [XX-net/XX-Net#3538]
不管XX-Net还是XX-Mi,为啥老是卡?
只要开启IP扫描就整个电脑都卡，
如果卡的时候在操作鼠标，就鼠标卡的难以动弹。
如果卡的时候在播放音频和视频(本地和在线)，就音画停止几秒。
退出XX-Net很流畅

附：
win8专业版  
XX-Net 3.1.14

**Comment by Cat7373** [comment]
请发完整的诊断信息谢谢

**Comment by jzp820927** [comment]
看看 任务管理器，CPU，和内存占用，找找是哪个进程中占用资源

**Comment by haibin88** [comment]
卡成翔了鼠标动不了，还怎么看CPU内存占用？

**Comment by fengixng** [comment]
应该是线程过高造成的，你试下调低线程试试

**Comment by jzp820927** [comment]
重启电脑，先打开任务管理器，再打开XX，然后观察 CPU 和 内存，看看是什么影响的

**Comment by keyoushi** [comment]
不一定就是XX引起的，比如你2G的内存跑64位系统，再chrome+插件管理XX，不卡出翔才怪2333333

**Comment by haibin88** [comment]
@keyoushi 本人不是电脑菜鸟，32位系统主流配置，3.25G内存，火狐+pan，

**Comment by yeahwu** [comment]
重新下载一下，或者升级到最新版试试。

**Comment by haibin88** [comment]
跟新旧版无关，一直是这样

**Comment by yeahwu** [comment]
你自己有没有改过配置？重新下载一下，然后重新配置。
默认内存不会超过60mb的占用

**Comment by haibin88** [comment]
跟CPU和内存无关 ，pythonw.exe进程占用闲时和忙时都很低
卡的时候CPU和进程也没好彪高。
会不会跟硬盘有关，我硬盘C6又黄了

**Comment by yeahwu** [comment]
那就是你机器问题了，这个锅也要xx-net来背？

**Comment by Cat7373** [comment]
C6 数据为非 0 代表你这块硬盘可以扔掉换一个了。

**Comment by haibin88** [comment]
XX扫描IP最大线程数，设置为1不卡

**Comment by jzp820927** [comment]
肯定是你机器的问题，不是硬件就是系统

**Comment by lh471921250** [comment]
我现在也有这个问题，我测试过了，只要打开xx-net，大概十分钟就会开始卡，过大概十分钟后又会变好，以前的版本没有这个问题，就是前几天用最新版的时候开始有这个问题的

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/releases
挨个版本试试看，看看是哪个版本之后才出现的问题？

**Comment by yeahwu** [comment]
win8装一下这个试试
```
Win8，win10 的APP，需要使用：https://loopback.codeplex.com/
```
