### ISSUE TITLE
托盘菜单显示当前代理模式

### ISSUE THREAD

**Issue by plmoknijnuy** [XX-net/XX-Net#354]
xx-net的全局代理和pac代理点击之后无任何提示，不知道xx-net是哪种代理状态，建议像goagnet一样，设置成功之后前面打上勾等标识。

**Comment by xxnet** [comment]
期待哪位提交个补丁

在 2015年5月7日 上午3:54，plmoknijnuy <notifications@github.com>写道：

**Comment by plmoknijnuy** [comment]
最新版本1.13.6的代理切换好像挂了。不管是pac代理，还是全局代理，点击之后都没反应。

**Comment by xxnet** [comment]
已解决
