### ISSUE TITLE
部署appid提示正常提交，允许提示部分appid不存在是怎么回事？

### ISSUE THREAD

**Issue by simi11king** [XX-net/XX-Net#3540]
设置的某个appid黄色字体的  set_appid_not_existing，不知道怎么把日志输出到文件，刷掉了，凭记忆提示如此

**Comment by simi11king** [comment]
抄了两句，大概如下报错：
603:appid not support  gae
appid_manager  set_appid_not_exist

**Comment by jzp820927** [comment]
应该是没部署成功吧，重新部署试试

**Comment by simi11king** [comment]
确实是部署问题，谢谢大神
