### ISSUE TITLE
还是关于ip的问题

### ISSUE THREAD

**Issue by Terry-** [XX-net/XX-Net#3544]
当断网之后，xxnet或者gae扫描ip的进程还在执行，然后丢掉了原来可用的ip，这个问题应该怎么解决一下？ 

XX-Net 3.1.14 更新一下版本。

之前看youtube的时候，连接速度可以到20kKbps，现在一般只有2kKbps了。。。

**Comment by jzp820927** [comment]
这是个大问题。不知道你用的啥版本，新版好像有网络检测机制

**Comment by yfdyh000** [comment]
遇到同样的问题，新版的网络检测可能有bug，旧版（无h2时）没问题。

**Comment by Cat7373** [comment]
昨晚我这停电了几分钟，正巧开了 XX-Net 状态页，那 IP，每秒几十个刷刷刷往下掉，网络状态还是 OK 的。。。
然后就顺手把 XX-Net 关了，来电重新开发现 IP 数量恢复正常。。。

**Comment by xxnet** [comment]
我来说说原来的设计逻辑：
  连接失败的ip，先标记为失败ip，然后放入一个队列，等候重新检查。
  重新检查的线程，先检查本地网络是否不可用，如果不可用，就把这些ip恢复为可用ip。
  在建立新的连接前，这些标记都不会写入硬盘。

所以可能在网络突然不可用时，会看到可用ip快速减少的现象。
  如果网络完全不可用，那么这些Ip一会会恢复。

不可用的ip，暂时只是标记。
在有效ip用完之前，也会尝试去连接。
因此最后也是会恢复可用的。

这些策略组合之后，基本可以不关心，只是恢复可用有时会慢一些。

这里优化是有空间的。
设计新的策略时，要有优先考虑任何情况下，不会出现太坏的情况，比如死循环、丢失数据等。
要避免人工干预，很多用户还是小白。

**Comment by Terry-** [comment]
如果能把扫描到的IP存放到gae里，需要的时候去获取，会减少很多客户端的压力的。我清理了10几万个ip，但是有很多也是可以用的。这个优化动作需要做啊。

**Comment by jzp820927** [comment]
感觉保存在本地和保存在云端并没啥区别，除非，你经常换电脑，移动办公

**Comment by Terry-** [comment]
楼上，你没看我的需求啊，我的意思是在云上迭代所有扫到的ip，总会有很多ip是可用的，但是不需要直接丢掉。

**Comment by jzp820927** [comment]
现在 IP 变动很频繁，很难找到稳定的IP了，你丢到云端，可能几个小时后，就是 badip 了，除非你能找到非常稳定的IP，反正我是找不到，我能找到的稳定的IP，都是 500ms 以上的，质量最差的 IP。我觉得意义不大。
