### ISSUE TITLE
关于x-tunnel流量分发，

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3548]
因为gae的问题，有些网站可能无法访问，可以通过x-tunnel来访问
那啥5.35快到了,提前防备
宣传x-tunnel，支持xx-net，为了项目持久
现挑选以下朋友来进行流量分发，（分发不限于这个论坛，最好发到墙内）同意的留下注册帐号，视报名多少，每人100g-200g
@Cat7373 @cc941201 @zjhzxhz @jzp820927 @panzer1313208 @yfdyh000 @linhua55 @xyuanmu

**Comment by yeahwu** [comment]
上面的朋友，能发多少是多少，不强求，发不完自己留着用。

**Comment by edwinhuish** [comment]
无法登陆，这个是什么意思？

![image](https://cloud.githubusercontent.com/assets/5207925/15640909/7c4e7bd2-266f-11e6-8497-5ebaf17bbd57.png)

**Comment by zjhzxhz** [comment]
Yes. 其实我用X-Tunnel真的不多~
目测在流量过期之前肯定用不完。

**Comment by acrossabc** [comment]
不太明白535代表什么，谷歌一下，原来是暗语。。。

**Comment by wzdnzd** [comment]
还没用过X-Tunnel☹。。。

**Comment by jzp820927** [comment]
好吧，为了支持 X大，为了 FQ 事业壮大，我报个名！

**Comment by yeahwu** [comment]
@jzp820927 留下你的x-tunnel帐号哇？给你转100g

**Comment by JMaxime** [comment]
虽然不在里面 也来支持一下

**Comment by yeahwu** [comment]
不限于名单里面，如果有心也可以留下帐号，俺筛选一下。

**Comment by xxnet** [comment]
支持，​流量可以再多一些，或者流量用完了再加。
其实受限制的网站，需要的流量不多。

还有，去墙内发流量的，要注意做好匿名。

**Comment by wzdnzd** [comment]
身边的同学和朋友都让他们用上了xx-net，xx-net真的很省心，希望此项目能够一直发展下去

**Comment by xxnet** [comment]
​建议经常在社区里冒泡的，都可以来帮忙发流量。
简单看看个人资料就可以知道了。

以后各种GAE不支持的站点，都走这种方案解决

**Comment by edwinhuish** [comment]
能不能不学国内运营商呢？还会过期清零。。。

**Comment by zzgpku** [comment]
有免费的ss梯子备用，过不去的就用ss

**Comment by jzp820927** [comment]
@yeahwu 不好意思，下午回帖那个时间正在上班，刚好有点事在忙，就没时间回，我现在去注册个专用流量分发账号上来。

**Comment by yeahwu** [comment]
已转100g，用完了再说
建议每人2g，（只是建议，确实1g都可以用好长时间。转给你了，就是你自己的，自由分发）

**Comment by jzp820927** [comment]
好，现在你是项目老大，都听你安排。

**Comment by yeahwu** [comment]
@jzp820927 别说笑话了，俺就是来搞笑滴！

**Comment by jzp820927** [comment]
只要有人管理就好。社区项目，回归社区本质。

**Comment by jzp820927** [comment]
这个流量是主动宣传？还是按需发放？

**Comment by yeahwu** [comment]
主动吧，别怕没流量，用完了再找俺

**Comment by jzp820927** [comment]
行吧，既然你都发话了，那俺就不客气了。

**Comment by Michael7CAT** [comment]
x-tunnel怎么玩？

**Comment by jzp820927** [comment]
wiki 有教程

**Comment by Michael7CAT** [comment]
可是我登入不上，和三楼显示一样@jzp820927

**Comment by JMaxime** [comment]
能有梯子用 作为答谢 已经在个人QQ群发了 也推荐身边的人用了 希望大神们不要放弃这个项目

**Comment by yeahwu** [comment]
@Michael7CAT 请先注册，然后登录

**Comment by Ethan-Zocer** [comment]
支持，xxnet最近很不错，yeanwu大送了20g，现在没怎么用。要是过几天不好用的话再拿出来。

**Comment by zjgbql** [comment]
没用过x-tunnel ,我来研究下 ,哈哈

**Comment by Michael7CAT** [comment]
我不记得密码了，之前注册的@yeahwu

**Comment by PS0123456** [comment]
@yeahwu 我往群里丢，god52501@gmail.com

**Comment by yeahwu** [comment]
@PS0123456  已转

**Comment by panzer1313208** [comment]
@yeahwu 最新测试版有bug不？2.1.19？

**Comment by edwinhuish** [comment]
我的账户为xch_566@163.com, 求发放，谢谢。

**Comment by magnet1215** [comment]
magnet1215@gmail.com  thanks

**Comment by iceliquid23** [comment]
= = X大发来的360G我还没用过呢。有效期一年过期后是不是都清零了？

**Comment by jzp820927** [comment]
@edwinhuish 已转，请查收

**Comment by jzp820927** [comment]
@magnet1215 已转，请查收

**Comment by lzw19961126** [comment]
lzw19961126@126.com   谢谢了

**Comment by zjgbql** [comment]
还有我 goodabu@gmail.com

**Comment by jzp820927** [comment]
@lzw19961126 @zjgbql 已转，请查收。
建议，x_tunnel 只用来代理 gae 不能代理的网站，合理利用 x_tunnel 流量。

**Comment by lzw19961126** [comment]
@jzp820927 知道了，谢谢了

**Comment by edwinhuish** [comment]
@jzp820927 非常感谢。

**Comment by Michael7CAT** [comment]
dydingjiawei@live.com  thanks so much

**Comment by jzp820927** [comment]
@Michael7CAT 已转，请查收。

**Comment by Michael7CAT** [comment]
流量收到，已配置，为何打不开啊？@jzp820927 
![image](https://cloud.githubusercontent.com/assets/19380683/15663074/4edd8296-2729-11e6-865f-1a1db715bd21.png)

**Comment by lele2010lele** [comment]
这个是福利吗？1152009145@qq.com

**Comment by jzp820927** [comment]
@Michael7CAT 看看 x_tunnel 模块有没有开启，1080 端口有没有监听，日志有没有什么报错。
@lele2010lele 算不上福利吧，算是 XXNET 的补充，主要用于代理XXNET 不能代理的网站。流量已转给你，请查收。

**Comment by Michael7CAT** [comment]
@jzp820927 
![image](https://cloud.githubusercontent.com/assets/19380683/15664075/f7af0a5e-273b-11e6-91d5-882ffb2a2f37.png)

**Comment by Michael7CAT** [comment]
啥意思啊？

**Comment by jzp820927** [comment]
@Michael7CAT 你有没有装迅雷？这个和迅雷有冲突，必须卸载迅雷才能用。

**Comment by Michael7CAT** [comment]
哇，真的欸，卸载迅雷就好了
@jzp820927

**Comment by lele2010lele** [comment]
收到了，谢谢j大

**Comment by jzp820927** [comment]
我气。我只是个打酱油的，喊我 j小 就行了。

**Comment by hzj-777** [comment]
3256646527@qq.com，谢谢！

**Comment by jzp820927** [comment]
@hzj-777 已转，请查收

**Comment by hzj-777** [comment]
@jzp820927 ,感谢

**Comment by hzj-777** [comment]
@jzp820927   x-tunnel能找回登陆密码吗？密码忘了。。。。

**Comment by jzp820927** [comment]
好像登录了一次，就可以自动登录了。

**Comment by zhanggangbz** [comment]
254586251@qq.com.感谢~

**Comment by jzp820927** [comment]
@zhanggangbz 已转，查收。

**Comment by hzj-777** [comment]
那个号登不进去了。。。能给我再发一份吗？另个邮箱2822857216@qq.com，这个是昨天刚注册的。谢谢了！

**Comment by hzj-777** [comment]
那个号登不进去了。。。能给我再发一份吗？另个邮箱2822857216@qq.com，这个是昨天刚注册的。谢谢了！

**Comment by zhanggangbz** [comment]
@jzp820927 收到，谢谢j大

**Comment by laozhu999** [comment]
@yeahwu 申请流量，谢谢。

**Comment by laozhu999** [comment]
laozhu999@gmail.com

**Comment by jzp820927** [comment]
@hzj-777 @laozhu999 已发，清查

**Comment by laozhu999** [comment]
@jzp820927 真心没有啊，只有原来的1M

**Comment by hzj-777** [comment]
@jzp820927 已收到，谢谢

**Comment by lovewe** [comment]
登上了，显示连接服务器失败，怎么回事

**Comment by jzp820927** [comment]
可能是服务端的问题，也可能是你本机的问题，重启XX试试吧
