### ISSUE TITLE
upload fail: 'utf8' codec can't decode byte 0xba in position 258: invalid start byte

### ISSUE THREAD

**Issue by Hunriken** [XX-net/XX-Net#355]
部署服务端时显示以上问题

**Comment by xxnet** [comment]
请贴出状态页

2015-05-07 4:31 GMT-04:00 Hunriken <notifications@github.com>:

**Comment by xxnet** [comment]
有更详细的日志吗？

**Comment by Hunriken** [comment]
已经ok了，虽然不知道什么原因已经配置好了。不过这几天总是显示连接超时啊。
2015年5月11日 下午4:37于 "xxnet" <notifications@github.com>写道：
