### ISSUE TITLE
能否提供一些易于扫描出可用的IP段？

### ISSUE THREAD

**Issue by witnessyin** [XX-net/XX-Net#3555]
扫描很久都没有几个可用IP，能否提供一些易于扫描出可用的IP段？这样可以缩短我扫描的时间。谢谢

**Comment by yeahwu** [comment]
只是第一次扫描要相对长时间，到后面就好了。

**Comment by witnessyin** [comment]
之前看到过帖子有人分享的一些IP段，确实很短时间就扫描出很多可用IP，就是现在找不到那个帖子了...@yeahwu

**Comment by yeahwu** [comment]
那个帖子是俺发的，里面的ip段已经整合到xx-net里面了，所以不需要费劲去找那些帖子了

**Comment by jzp820927** [comment]
XX现在的IP段，都是精简过含有可用IP的段了，只要耐心扫描，肯定会有的
