### ISSUE TITLE
能否加入ipv6的扫描功能，这样ip用光后还可以继续使用。

### ISSUE THREAD

**Issue by april4513** [XX-net/XX-Net#3559]

**Comment by jzp820927** [comment]
目前 XX 内置有部分固定的 IPv6 ，只要打开 ipv6 开关就能用，不需要扫描。

**Comment by april4513** [comment]
内置的各种失效已经没有连接可用了，删掉good_ipv6重新恢复内置库后ip失效也很快，所以希望能加入扫描的功能

**Comment by jzp820927** [comment]
这个就不大情况了，没有v6环境，无法测试，只有等项目老大来解决了。

**Comment by zzgpku** [comment]
v6ip还行吧，不至于全部失效。我以前几十个ip也用了很久

**Comment by zzgpku** [comment]
以及，有v6条件，推荐用v6 的hosts，谷歌的网站访问很快

**Comment by xiuluo** [comment]
最近ipv6速度明显变慢了

**Comment by zzgpku** [comment]
@xiuluo  还行吧，要是用hosts就很快了。其他的网站就用xx，xx用不了的就用x-tunnel或ss。
perfect！
show一张hosts下的速度。
![default](https://cloud.githubusercontent.com/assets/14359560/15676760/212d7d6e-277a-11e6-8aaa-d1de5e4e5732.png)

**Comment by jzp820927** [comment]
楼上的 v6 还是一如既往的这么牛B

**Comment by xiuluo** [comment]
@zzgpku 羡慕，我们学校的ipv6出口带宽很窄，除了直连USTC快之外，连其他站点都很慢😨

**Comment by zzgpku** [comment]
@xiuluo 但是除了hosts上的U2B之类的，其他打不开的网站还得用xx，速度一般般，不过也够了。
不知道为什么xx上ipv6的延迟会这么高

**Comment by jzp820927** [comment]
延迟不重要，重要的是带宽。确实访问国内网站，可以搭建在国内的 paas 上嘛

**Comment by xiuluo** [comment]
@jzp820927 安徽省高校应该都是先直连USTC，然后再由USTC中转出去，所以我感觉USTC给每个学校分配的出口带宽应该不一样。

**Comment by jzp820927** [comment]
难道 @zzgpku 的学习，比较高大上。

**Comment by zzgpku** [comment]
@jzp820927 ipv4的宽带不大，百度云vip下载最多也就能到1M/s。以及搭建paas是什么东西？完全没听说过啊。。。
@xiuluo USTC是中科大么，可为什么其他学校要转到中科大。。。

**Comment by jzp820927** [comment]
我是说的 IPV6 的带宽，你们学校这么高带宽，肯定是比较高大上。应该是 清华，百大吧

**Comment by xiuluo** [comment]
@zzgpku 不清楚，方便管控吧。

**Comment by simonasd** [comment]
现在有人整理初Google的ipv6段吗？有IP段的话也许可以做扫描
