### ISSUE TITLE
1.13.6还是youtube视频下载32m的梗。。。

### ISSUE THREAD

**Issue by yqfang** [XX-net/XX-Net#356]
版本： 1.13.6

➜  video  youx https://www.youtube.com/watch\?v\=hFOSXVT-Cps
site:                YouTube
title:               Angular 1.3 Data Binding, watchers & Lightning talks
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          32.0 MiB (33553218 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading Angular 1.3 Data Binding, watchers & Lightning talks.mp4 ...

**Comment by xxnet** [comment]
服务端重新部署了吗？

2015-05-07 5:18 GMT-04:00 yqfang <notifications@github.com>:

**Comment by yqfang** [comment]
恩，重新部署后可以啦！灰常感谢！
