### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by ssyangchn** [XX-net/XX-Net#3567]
---诊断信息---
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
xxnet-version: 3.1.14

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:216 good:152
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 398
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

---
## 问题内容
升级到最新稳定版还是无法使用，主页显示“请检查浏览器代理设置”

状态显示如下：
本地网络状态	OK
IP数量	180
空闲	0
IP延迟	324
连接池(帮助)	新:0 h1:6 h2:3
浏览器代理设置	Fail
CA证书状态(下载)	Fail
扫描IP线程数(设置)	100
屏蔽状态(帮助)	OK

**Comment by Wrecking-Ball** [comment]
Win7/8/10：将提示请求管理员权限（出于安装CA证书的需要）。请点击同意。

**Comment by ssyangchn** [comment]
1.我是win7 64位系统，双击start.vbs没有要求管理员权限
2.我自己右键用管理员身份运行还是无法使用
3.手动在chrome里导入ca证书也没用

**Comment by ssyangchn** [comment]
已解决！步骤如下：
1.下载运行最新版xx-net
2.删除旧版本Proxy SwitchyOmega  chrome插件
3.安装xx-net里面带的Proxy SwitchyOmega插件（XX-Net-3.1.19\SwitchyOmega\SwitchyOmega.crx）
4.导入Proxy SwitchyOmega配置文件即可
