### ISSUE TITLE
运行后导致外网瘫痪

### ISSUE THREAD

**Issue by dodo7519** [XX-net/XX-Net#3569]
运行xx-net并代理成功后（提示已翻墙成功），大约30秒之内外网连接就会瘫痪，同时局域网内所有终端都无法正常连接外网。关闭xx-net后重启路由，一切恢复正常。
好神奇，宽带用的华数，这是GFW的新招数还是华数？

**Comment by linhua55** [comment]
https://github.com/XX-net/XX-Net/wiki/%E6%95%85%E9%9A%9C%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8C#%E6%89%93%E5%BC%80xx-net%E5%90%8E%E5%9B%BD%E5%86%85%E7%BD%91%E7%AB%99%E7%9B%B4%E6%8E%A5%E8%BF%9E%E6%8E%A5%E7%9A%84%E6%89%93%E4%B8%8D%E5%BC%80
