### ISSUE TITLE
如何修改脚本里，使用xx-net代理

### ISSUE THREAD

**Issue by simi11king** [XX-net/XX-Net#3573]
需要使用google的脚本，但是需要修改脚本翻墙，修改后错误
curl -L -f -s -S -o\ 
-k -x http://127.0.0.1:8087 #这些是我自己加的\
https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf?source=linux_recovery.sh
提示我没有用-k这个参数，问题我加了啊！
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

curl -L -k -f -s -S -o -x http://127.0.0.1:8087 https://www.google.com
我把-k放到前面也是出错，又报404错误
GAEProxy Web_control 127.0.0.1:38118 GET /
curl: (22) The requested URL returned error: 404
curl: (7) Failed to connect to www.google.com port 443: Connection timed out
不太会curl，所以不知道啥错误。

**Comment by jzp820927** [comment]
https://dl.google.com/ 这个地址，在国内应该是可以直连的

**Comment by Pd69bq** [comment]
用curl的话 不光要代理 还要放证书 PEM格式 不是说你加了-k网站就不验证你的证书
