### ISSUE TITLE
怎样使用命令行或者脚本来启动”检查所有IP“？

### ISSUE THREAD

**Issue by cqman2** [XX-net/XX-Net#3575]
默认在启动XX-Net后会自动”检查所有IP“，但笔记本一直都不会关，每天都需要手动去”检查所有IP“。

但每次一步一步点进去很麻烦，有没有一句命令或者脚本直接来启动”检查所有IP“？

谢谢！

**Comment by 821938089** [comment]
http://127.0.0.1:8085/module/gae_proxy/control/check_ip?cmd=start
浏览器加这个书签，要开始时直接点这个书签开始

**Comment by cqman2** [comment]
测试成功，谢谢！
