### ISSUE TITLE
使用的是3.1.19版本 使用X-TUNNEL还没有pac代理的速度快

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#3577]
XX-Net 3.1.19 ，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	4923
空闲	0
IP延迟	179
连接池(帮助)	新:2 h1:35 h2:8
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK

@yeahwu @xxnet @Cat7373

**Comment by Cat7373** [comment]
没有人说过 X-tunnel 比 GaeProxy 快呀。。。

**Comment by Veeson** [comment]
据我使用来看，X-tunnel速度会相对慢一些。

**Comment by jzp820927** [comment]
x_tunnel 的数据都是通过 gae 传输的，怎么可能会比 GAE 快。

**Comment by yeahwu** [comment]
x-tunnel的优势是匿名性，兼容性，还有youtube效果可能相对好点。
