### ISSUE TITLE
Microsoft Visual C++ Runtime Library

### ISSUE THREAD

**Issue by donizyo** [XX-net/XX-Net#3586]
今天突然跳error，もしかして我中毒了？
<pre>
Runtime Error!
Program:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
</pre>

**Comment by donizyo** [comment]
<pre>
Windows Script Host<hr/>
脚本： D:\XX-Net-3.1.4\start.vbs
行：     64
字符： 1
错误： 系统找不到指定的文件。
代码： 80070002
源：     (null)
</pre>

**Comment by donizyo** [comment]
貌似是自动更新后的锅，我关掉自动更新好了\_(:зゝ∠)\_

不过3.1.4版本有问题的话希望快点更新3.1.5版本吧\_(:зゝ∠)\_

**Comment by yeahwu** [comment]
手动更新吧，自动更新有点问题。已经3.2.0版了
https://github.com/XX-net/XX-Net/releases

**Comment by donizyo** [comment]
是这次自动更新有问题还是一直有问题啊 :D

**Comment by yeahwu** [comment]
自动更新的问题
