### ISSUE TITLE
win10下智能代理常常无效

### ISSUE THREAD

**Issue by jkdfan** [XX-net/XX-Net#3592]
win10下，设置为智能代理，ie代理设置里面也显示是智能代理，但是智能代理常常不起作用。有时候在ie里面手动重设一下就好了，但有时候也无效。这个问题存在很久了。

**Comment by yeahwu** [comment]
3.2.0重新下载一下试试，刚更新了一下

**Comment by jkdfan** [comment]
现在用的就是3.2.0，一样有这个问题。

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by jkdfan** [comment]
这个不也是3.2.0版的么，有区别？

**Comment by yeahwu** [comment]
首先，俺不知道你说的无效是什么情况，是不能用了还是怎么？
然后智能pac代理建议chrome浏览器，
如果实在不行，建议你取消代理，用浏览器插件调用。

**Comment by jkdfan** [comment]
智能代理无效就是设置好后，应该走xx-net的没有走。http://127.0.0.1:8086/proxy.pac可以访问，也有正确的内容在，但是访问需要走xx-net的网站时，不能访问，xx-net的日志中也没有显示有访问的动作。

**Comment by Cat7373** [comment]
那么具体是什么网站不能访问呢？

**Comment by jkdfan** [comment]
所有被屏蔽的网站都不能访问啊。包括但不限于google.com、youtube.com、facebook.com以及一个佛学网站budaedu.org。设为全局代理可以访问，设为智能代理就不能访问。日志中也没有访问的动作记录。

更新为3.2.0版本后，唯一的改进就是禁用代理，再设置为智能代理后，一定可以用了。但是启动后还是不能直接可用（系统代理设置里面显示是智能代理）。

**Comment by yeahwu** [comment]
3.2.0版主要是针对老旧系统进行优化改进。你说的智能pac代理，针对不同的浏览器，有不同设置
这个你还是到wiki里面看看
不如火狐需要到浏览器代理设置里填入http://127.0.0.1:8086/proxy.pac
ie可能也要到ie设置里填入地址吧

**Comment by jkdfan** [comment]
能尝试的可能性我当然都考虑过了的。包括改注册表，包括搜寻win10有无这个bug，包括运行权限的问题等等。但目前，既没有人提交xx-net这个问题的讨论，也没有人提交win10类似问题的讨论，所以我也不得而知是哪方面的问题了。

不过这个问题终归是个小问题，重要的问题是前面那个较大文件下载的问题。

**Comment by Cat7373** [comment]
win10 用 Edge 呀。

**Comment by yeahwu** [comment]
下载问题，这个是先天问题，看到有人说下载超过1g的文件，这个几乎是不可能的。唯一的可能是下载链没经过代理。为什么这么说呢，因为有些网站即使被墙的，但是它用的云有可能没被墙，所以你才能下载。就像github网站虽然没被墙，但是它使用的亚马逊的云确给污染了。
gae是有限流的，不是随随便便给你流量玩的。

**Comment by yeahwu** [comment]
火狐不经过ie代理，必须到浏览器里设置代理。

**Comment by jkdfan** [comment]
gae流量是有限流，每日每appid 1g，20个账户每天下载已经足够正常使用。不要偏题和纠结于基本问题的讨论了。回归问题本身的讨论吧。我是没精力读代码，才来这反馈。也一并感谢所有奉献时间维护xx-net的程序猿。

**Comment by jkdfan** [comment]
基本问题是我没用火狐好吧？不要讨论这种基本问题了，直面问题本身吧。

**Comment by yeahwu** [comment]
俺也告诉你吧，gae下载最大32mb，超过下载不了。
这是一直的问题，而且是gae的问题，和xx没有关系

**Comment by jkdfan** [comment]
我一直通过xx-net下载超过32m的文件。上周就下载了每个数百M的文件上百个。不用解释是没有被墙，流量是通过xx-net的。

用户确实没有开发者更了解软件，但也不要过度质疑用户在错误使用软件。不是所有问题都能解决，但也不必总把问题归结为用户或运行环境吧。

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/server/gae/gae.py
有关下载大小限制的解释在这个文件的前几行里就有提到的哟 0.0

**Comment by yeahwu** [comment]
谁把这个问题归结为用户了？这个问题也可能是开发者无法解决，但是有没有必要解决也是开发者问题，自由软件自由开发，你有问题你可以提出来，但是开发者也不一定要解决。
不必激动，是开发的问题也好，是使用问题也好，都奈何不了对方。
再说这个项目……

**Comment by Cat7373** [comment]
我给自己的定位是普通用户，只有自己遇到的问题我才会提 PR 解决，而且涉及到核心的一律只提 Issue 不提 PR。
    以及核心的代码我基本没看过。
    偶尔闲着没事来回答点问题什么的。

**Comment by jkdfan** [comment]
GAE server will return 206 status code if file is too large and server support range fetch. Then GAE_proxy local client will switch to range fetch mode. 

这段不是很明白吗？服务器支持的话，range fetch mode可以下载大文件的啊。让我看这个是觉得我不懂英文吗……问题是现在xx-net下载到了文件，但不传输给下载工具，这个问题是算法的问题吧？是因为要针对实时播放媒体文件所做的优化？总要排序好才传给请求连接？因为刚好我下的文件是.rm的。正常下较大文件，应该不是这样的算法吧，应该是收到就马上转发啊……没看过代码，瞎猜的。

**Comment by Cat7373** [comment]
不是很喜欢你的说话风格。。。
我只是简单的转发下相关的说明。。。
并没有想过你看不看的懂，因为我英语也很渣，但我看这种东西也可以用翻译工具，所以我根本没想过这些问题。。。

文件下载失败有很多种可能性：
比如文件服务器屏蔽了 GAE 的服务器。
比如文件服务器不支持断点续传，而且你要下载的文件大于 10MB。
*range fetch mode* 需要下载文件的服务器支持才可以用，如果不支持那就只能下载到 10MB。

**Comment by Cat7373** [comment]
不要总以为其他人都是有恶意的。。。

**Comment by Cat7373** [comment]
事实上，我给你发的是注释而不是代码，就已经考虑到你可能看不懂代码，所以给你比较容易懂的注释。。

**Comment by yeahwu** [comment]
好吧，那就是算法的问题吧，多大的事！

**Comment by zzgpku** [comment]
哎呀，别吵了，没多大事，不能智能可能是pac文件有问题？用chrome就行了呗~有些大文件下载不了就用其他工具代替一下就行了，免费的ss还是很多的。

**Comment by jkdfan** [comment]
我既然提大文件下载这个问题，当然是已经考虑了各种因素了。包括服务器是否屏蔽了gae，是否支持断点继传。如果屏蔽、不支持断点继传，我何必来这问……log中也能看到，也有很多方法可以测试这两类问题。

倒不是觉得你们有恶意，只是觉得你们不是在讨论问题本身，而总是认为问题在使用者身上，总是想找到一些初级错误给使用者。最后连gae不支持大文件这样的理由都找出来了。我们不需要考虑更深入的知识，就只看我们能播放youtube.com的视频，就知道xx-net是解决了这个问题的。

我也已经说过xx-net在下载大文件时是有流量走，但抓回来的数据不传给请求连接。我觉得这个已经描述够清楚了。

事实上，如果我所提的问题，是属于你们不熟悉的那部分软件结构的，可以不回应。提问者期望的回应者应该是了解大文件下载算法的维护者。在抱怨我的讨论方式前，是否应该考虑下，其实你们的回复根本就不是在解决问题，而是在指责乃至于挑衅？

**Comment by Cat7373** [comment]
好好好，我取消 Subscribe 这个问题了，你们继续讨论吧。。。

**Comment by yeahwu** [comment]
你提出这个问题之前，俺第一个回答就已经很明确了
叫你使用别的代理，说gae有缺陷。俺说的是gae有缺陷，并没有说你使用问题，而你口口声声说指责用户使用问题！俺们哪里有指责用户的语句？
俺还说gae下载限流，这是在明确回答你的问题，你可以不满意这个回答。但是俺们并没有回避问题！
最后谁先挑衅的看楼上讨论
```
这个是基本常识吧……楼上回答的都参与维护的哦……
```
