### ISSUE TITLE
特殊日子来了，来个翻墙软件大合集

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3596]
首先gae类

XX-Net 自动扫ip的goagent，外号“叉烧狗”加入h2后性能更上一层楼
https://github.com/XX-net/XX-Net

goproxy  社长最新golang版的goagent，外号“狗屁”性能不俗，目前维护积极
https://github.com/phuslu/goproxy

goagent   外号“黄狗”，面前已不维护，但是仍是许多老狗迷的最爱

xx-mini    精简后的叉烧狗，linux的首选，安装包就一两百kb，xyuanmu的打包水平可见一般，外号“狗崽子”
https://github.com/xyuanmu/XX-Mini

隧道类

shadowsocks     这个不需要多讲了，应该是面前最受欢迎的代理方式
https://github.com/shadowsocks

v2ray
https://github.com/v2ray/v2ray-core
最近开发活跃，作者自带的服务器是可用的

gogo 外号“二狗”，是一个基于Paas平台的代理工具，同时支持SOCKS5和HTTP两种代理协议，面前自带的免费HEROKU空间，速度还是可以接受的，官网已经被gfw墙了
http://www.gogotunnel.com/

x-tunnel ，socks5通过gae转发，有效防止服务端ip被封，x大的衍生性作品

Gost TLS tunnel
https://github.com/ginuerzh/gost

隧道类太多了，不一一列举

该说说lantern了，这货以前速度很饱满，最近痿了，今天来说说lantern其他功效
首先lantern支持https代理，这样一特性让它可以成为tor的前置，而gae类是不行的。然后兼容性可能也要胜过gae，几乎没有打不开的网站，上传下载更不是问题。
鸡肋的是它自带的pac，和启动弹窗，稍慢的速度
https://github.com/getlantern/lantern

最后还是上tor吧
最近更新了6.0版，tor的用法呈多样化，俺自己用的话，是不带浏览器版的，提取tor文件或者自己编译一下，然后配合 torrc文件来使用。
关于自带网桥目前就obfs4可用，其他的obfs3，2基本被封杀殆尽。（去年，有友给了俺100多个网桥，很是感激）一般推荐前置，lantern或者ss
下载：https://dist.torproject.org/torbrowser/6.0/
获取网桥：https://bridges.torproject.org/options
自编译版：https://github.com/torproject/tor

差点忘了，下面这茬，很多人问俺怎么查找ip，下面推荐两工具

首先是 @xyuanmu 兄的多功能ip查找工具，集dig，扫描，格式转换于一身，被人们低估的工具，确实很强大
win和linux双平台：https://github.com/xyuanmu/checkiptools

再就是 @kisesy 兄的魔改MMF，这个确实魔性，一致好评
下载地址：https://github.com/phuslu/goproxy/files/273808/Release.tar.gz

就想到这些，有遗漏的大家补充

**Comment by Cat7373** [comment]
日常作大死。。。

**Comment by hkvsak** [comment]
hhhhhhhha！

**Comment by yeahwu** [comment]
还是关了吧，这些工具确实太有杀伤力了
