### ISSUE TITLE
启动读取机制是不是需要改下。

### ISSUE THREAD

**Issue by yjd** [XX-net/XX-Net#361]
我一直是手动下载新版解压覆盖。
然后点bat启动。
goagent目录下有两个文件夹3.1.49和3.1.48

它会启动旧版本。。是不是应该改成读取新版才合理

**Comment by Cat7373** [comment]
大概是data下的配置文件没自动更新- -
建议增加个update.py，每次自动更新后执行一次，做需要的自动升级操作- -

**Comment by xxnet** [comment]
现在有自动更新了，在System->设置里-》检查新版，然后发现有新版，可以点安装，就会自动升级到新版。

在 2015年5月7日 下午10:38，Cat73 <notifications@github.com>写道：

**Comment by yjd** [comment]
好的。更新地址不会被墙吧。

**Comment by Cat7373** [comment]
Github暂时没被墙- -
