### ISSUE TITLE
孤弱寡闻了，都3.2.0啦，我还在2.9.3，升到最新版有啥问题吗

### ISSUE THREAD

**Issue by 12343954** [XX-net/XX-Net#3611]
RT
也不知道升级的版本日志在哪看

**Comment by Cat7373** [comment]
日志在这里：https://github.com/XX-net/XX-Net/releases
然而是英文的。

**Comment by 12343954** [comment]
呵呵，翻了半天，终于找到中文日志了
https://github.com/XX-net/XX-Net/wiki/%E6%9B%B4%E6%96%B0%E5%8E%86%E5%8F%B2
