### ISSUE TITLE
为什么智能代理模式，优酷网页会乱码？

### ISSUE THREAD

**Issue by yj1** [XX-net/XX-Net#3613]

**Comment by Cat7373** [comment]
看看日志，优酷的资源是不是走了代理。

**Comment by yj1** [comment]
不是的，我怀疑是我们学校局域网的问题，反而全部走gae会全部加载完。

**Comment by jzp820927** [comment]
不开 XXNET，直接打开会不会乱码

**Comment by simonasd** [comment]
@yj1 好独特的网络环境。如果你的浏览器有控制台，打开看一下是什么资源加载失败了？分别尝试全部直连、智能代理和全部gae

**Comment by yj1** [comment]
@jzp820927 那倒不会，只不过需要重新断开拨号，要不然还是乱码。

**Comment by yj1** [comment]
SwitchyOmega提示*.ykimg.com，*.youku.com 加载失败。

**Comment by yj1** [comment]
![Uploading screenshot-www.youku.com 2016-06-08 10-04-14.png…]()

**Comment by yj1** [comment]
![Uploading screenshot-www.youku.com 2016-06-08 10-04-14.png…]()

**Comment by yj1** [comment]
![Uploading screenshot-www.youku.com 2016-06-08 10-04-14.png…]()

**Comment by yj1** [comment]
![Uploading screenshot-www.youku.com 2016-06-08 10-04-14.png…]()
