### ISSUE TITLE
看图写话

### ISSUE THREAD

**Issue by littlebigdream** [XX-net/XX-Net#3622]
![1](https://cloud.githubusercontent.com/assets/18393082/15882814/0ec4fe1c-2d75-11e6-9838-33a85a338ae5.PNG)

据说，现在 移动 的翻墙效果最好，电信的最差，
但是，明明 电信的带宽最大啊，这是为什么呢？有什么隐情？

**Comment by yeahwu** [comment]
俺就说两个字
“人均”

**Comment by wialny** [comment]
除了人均, 应该还有墙的问题. 最近AWS直连很不稳定啊

**Comment by Wrecking-Ball** [comment]
![2](https://cloud.githubusercontent.com/assets/18393082/15884124/a9124bd6-2d80-11e6-84e5-e2d7b0ae729b.PNG)

中国电信 的宽带用户大概是 移动的 不到 2倍，但是 出口带宽 是 移动的5倍啊！

**Comment by Wrecking-Ball** [comment]
墙，难道墙 对电信有特殊照顾。。。

**Comment by github-xx** [comment]
移动用户算上，人均移动用户不占优势的。

**Comment by Pd69bq** [comment]
带宽质量好坏跟墙木有太直接的关系 GFFW只起到过滤数据包的作用 对于咱们这种P民用户来说 出口带宽大小对于使用感知上一点关系都没有 我想在中国国内 一般用户没有10跳 到不了出口

**Comment by Wrecking-Ball** [comment]
啥意思，你是说 翻墙速度 快慢和出口带宽 没啥关系，
电信翻墙慢 是因为它自己搞的鬼，自己在国内转圈 吗？？

**Comment by Pd69bq** [comment]
我的意思是你的贷款质量是看运营商心情 你要是小区宽带 那还有3级运营商揩油 报个出口总带宽对一般用户来说没有意义 现在什么都封 不翻墙的一般用都用不到

**Comment by nly4lov** [comment]
不明觉厉
![e103](https://cloud.githubusercontent.com/assets/11325411/15887804/ca13fd1e-2d96-11e6-9101-b7cbfad889e5.gif)

**Comment by jrkkei** [comment]
我也想过这个问题，听说电信大部分国际带宽都是商用的，更赚钱嘛，P民用的就慢下来了，虽然不知道是不是这样，不过我从11年开始同时使用两家宽带开始，电信的国际访问速度就一直不如联通，前段时间TPE扩容，现在联通使用xxnet下载6MB/s,电信只有2MB/s,蓝灯之类的傻瓜软件电信能不能连上都是问题，联通就没事，不过本地移动好像并不热心于有线宽带，至今也没覆盖，无奈

**Comment by Wrecking-Ball** [comment]
@jrkkei  
“现在联通使用xxnet下载6MB/s,电信只有2MB/s”

请问是哪里的？？ 太牛了吧，只有羡慕的份。。

**Comment by funray** [comment]
浏览国外网站，是将数据传进国内，貌似是进口。
@Wrecking-Ball

**Comment by jrkkei** [comment]
@Wrecking-Ball 北方联通地盘。今天看到新闻电信的出口挂了几小时，对联通好感度又上升了。。。

**Comment by simonasd** [comment]
感觉有必要开一个wiki，甚至开一个项目，让网友汇报各地各运营商的情况，供新入网用户参考。

但是又担心变成方校长检阅的对象，这个名单上推荐的运营商肯定要被领导批评的。

**Comment by nly4lov** [comment]
方校长是谁？

**Comment by funray** [comment]
方滨兴
@nly4lov
