### ISSUE TITLE
XX-Net能安装到思科的哪些路由器上？

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#3624]
RT.
@yeahwu 来水一下

> System (hide)
Name	TomatoUSB
Model	Linksys E1200 v2.0
Chipset	Broadcom BCM53572 chip rev 1 pkg 8
CPU Freq	300MHz
Flash Size	8MB
 
Time	Sat, 11 Jun 2016 03:29:07 +0200
Uptime	0 days, 01:31:11
CPU Load (1 / 5 / 15 mins)	0.00 / 0.00 / 0.00
Total / Free Memory	27.99 MB / 18.13 MB (64.78%)
Total / Free NVRAM	64.00 KB / 43.21 KB (67.52%)

> Tomato Firmware 1.28.0000 MIPSR2-130 K26 Max
IPv6 support, 
Linux kernel 2.6.22.19 and Broadcom Wireless Driver 5.110.27.20012 updates,
support for additional router models, dual-band and Wireless-N mode.
Copyright (C) 2008-2011 Fedor Kozhevnikov, Ray Van Tassle, Wes Campaigne
http://www.tomatousb.org

OpenVPN integration and GUI,
Copyright (C) 2010 Keith Moyer,
tomatovpn@keithmoyer.com

"Shibby" features:
- NFS utils integration and GUI
- Custom log file path
- SD-idle tool integration for kernel 2.6
- SNMP integration and GUI
- DNScrypt-proxy 1.4.0 integration and GUI
- TOR Project integration and GUI
- OpenVPN: Routing Policy - TomatoAnon project integration and GUI
- TomatoThemeBase project integration and GUI
- Ethernet Ports State
- Extended MOTD (written by @Monter, modified by @Shibby)
- Webmon Backup Script
Copyright (C) 2011-2013 Michał Rupental
http://openlinksys.info

"JYAvenard" features:
- OpenVPN enhancements & username/password only authentication
- PPTP VPN Client integration and GUI
Copyright (C) 2010-2012 Jean-Yves Avenard
jean-yves@avenard.org

"TomatoEgg" feature:
- Openvpn username/password verify feature and configure GUI.

"Victek" features:
- Extended Sysinfo
- Captive Portal. (Based in NocatSplash)
Copyright (C) 2007-2011 Ofer Chen & Vicente Soriano
http://victek.is-a-geek.com

"Teaman" features:
- QOS-detailed & ctrate filters
- Realtime bandwidth monitoring of LAN clients
- Static ARP binding
- VLAN administration GUI
- Multiple LAN support integration and GUI
- Multiple/virtual SSID support (experimental)
- UDPxy integration and GUI
- PPTP Server integration and GUI
Copyright (C) 2011 Augusto Bott
Tomato-sdhc-vlan Homepage

"Lancethepants" Features:
- DNSCrypt-Proxy selectable/manual resolver
- Comcast DSCP Fix GUI
Copyright (C) 2014 Lance Fredrickson
lancethepants@gmail.com

"Toastman" features:
- Configurable QOS class names
- Comprehensive QOS rule examples set by default
- TC-ATM overhead calculation - patch by tvlz
- GPT support for HDD by Yaniv Hamo
- Tools-System refresh timer
Copyright (C) 2011 Toastman
Using QoS - Tutorial and discussion

"Tiomo" Features:
- IMQ based QOS Ingress
- Incoming Class Bandwidth pie chart
Copyright (C) 2012 Tiomo

"Victek/PrinceAMD/Phykris/Shibby" feature:
- Revised IP/MAC Bandwidth Limiter

Based on Tomato Firmware v1.28
Copyright (C) 2006-2010 Jonathan Zarate
http://www.polarcloud.com/tomato/

Built on pon, 08 cze 2015 18:00:34 +0200 by Shibby, http://openlinksys.info

**Comment by yeahwu** [comment]
路由器没安装过，所以没水分。
你可以呼叫“插插奶哒”！

**Comment by nly4lov** [comment]
@xxnet 插大进来看看呀

**Comment by drg78rnvgh** [comment]
思科不是用IOS系统吗

**Comment by jzp820927** [comment]
这个和路由器没关系吧，主要看 python 和 openssl 的环境是不是完整。

**Comment by nly4lov** [comment]
@jzp820927 完全不懂你说的呀

**Comment by jzp820927** [comment]
不懂就不深究喇叭，俺也是随口一说

**Comment by simonasd** [comment]
@nly4lov 按我的理解，应该是两个因素在影响：
* 路由器的操作系统：原生系统是否具备XX-Net所需的运行环境，不具备时是否能安装，或者是否能刷第三方系统
* 路由器的硬件：内存、闪存、处理器等能否满足XX-Net的需求。

没做过，纸上谈兵，还是希望有经验的用户来发言。issue区之前发过一些相关的帖子，可以整理一下。

**Comment by nly4lov** [comment]
@jzp820927 @simonasd 
我更新了硬件和系统信息，麻烦二位看看能装上XXNET吗？

**Comment by jzp820927** [comment]
没看到 python 和 openssl 的相关系统，不好判断，你直接运行下 XX，看看日志有没有报错，根据报错信息，来处理就行了。

**Comment by samho88** [comment]
内存好象少了点，可能跑不起吧

**Comment by Ikutariansama** [comment]
“Flash Size 8MB……Total / Free Memory 27.99 MB / 18.13 MB (64.78%)…………”

直说，看配置，应该是不行。

Python2.7开一个进程就直接爆内存了吧233333……
印象中debian的python2跑一个XXnet消耗20-40MB之间。
何况这系统本身维持转发机制都耗费60%多内存了………………
Flash Size 应该是指持久存储区吧，可惜才8MB；如果100MB以上的话，倒是有希望……。

**Comment by nly4lov** [comment]
感谢楼上各位，俺已经死心了，嘿嘿

**Comment by jzp820927** [comment]
确实也可以试试，很很多人成功在路由上运行了

**Comment by nly4lov** [comment]
我技术比较差的。只是个拿来主义者![qq 20160529140801](https://cloud.githubusercontent.com/assets/11325411/16064179/6e1e8c28-32d1-11e6-8235-eea4b9a6734a.png)
