### ISSUE TITLE
怎样为appid设置密码？

### ISSUE THREAD

**Issue by okgoogle** [XX-net/XX-Net#3627]
现在的新版本设置密码是不是只能通过这个方法设置：
https://github.com/XX-net/XX-Net/blob/d750d8705644a91fa17f85e66d46ed3b6b38445c/code/default/gae_proxy/server/README.md
Web部署界面或手动编辑配置文件ini都不行吗？如果可以请指出方法，谢谢

**Comment by jzp820927** [comment]
部署服务端是通过上面链接中的方法，客户端设置还说着 ini 文件中。

**Comment by okgoogle** [comment]
谢谢，刚才已经上传成功了，顺手换了新版本。用新版本上传时，可以先打开旧版本，这样就可以借助旧版本的“通道”上传了。
