### ISSUE TITLE
当PAC的监听IP改为0.0.0.0的时候，PAC文件里面的Proxy的IP未更新

### ISSUE THREAD

**Issue by cxjava** [XX-net/XX-Net#363]
当配置文件里面的配置如下时：

[pac]
enable = 1
ip = 0.0.0.0

在浏览器输入 http://12.25.62.11:8086/proxy.pac 时，PAC文件并没有随着监听IP变化而变化，文件内容还是

// Proxy Auto-Config file generated by autoproxy2pac, 2015-01-20 10:28:53
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 127.0.0.1:8087';  
    var blackhole = 'PROXY 127.0.0.1:8086';
.................

我觉得正确的应该是：  var autoproxy = 'PROXY 12.25.62.11:8087';

**Comment by xxnet** [comment]
这个似乎要改动pac文件的内部。

XX-Net不考虑支持远程访问，喜欢的自己折腾吧，实在太麻烦。
