### ISSUE TITLE
连接池第一位为0，‘/’后有几十个值，科学上网变困难了？

### ISSUE THREAD

**Issue by szwuzy** [XX-net/XX-Net#3636]
-----------
问题描述：
连接池分子为0，IP延迟300左右，访问常常出现问题：慢或连接不上。
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
xxnet-version: 2.9.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 161
network-status: OK
connected-link: 0 / 38
scan-ip-thread-num: 60
ip-quality: 228
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yeahwu** [comment]
升级，这都什么年代的版本

**Comment by szwuzy** [comment]
xxnet-version: 2.9.3
python-version: 2.7.9

**Comment by GoForFree** [comment]
醉了，1个月前我还在用2.9.2

**Comment by szwuzy** [comment]
升级后确实多一一个新IP, H1： H2：  基本都能保证有10以上的数字了。 多谢多谢
