### ISSUE TITLE
怎么关闭XX-Net启动时的弹窗

### ISSUE THREAD

**Issue by HappysurfBlocking** [XX-net/XX-Net#3647]
每次开机时的弹窗占用了不少系统资源，希望能去掉

**Comment by HappysurfBlocking** [comment]
找到方法了，注释掉一行代码就可以了

**Comment by jingouwangzi** [comment]
请问是怎么关闭的，注释哪行代码？

**Comment by yeahwu** [comment]
直接在web界面关闭不就好了
![2016-06-13](https://cloud.githubusercontent.com/assets/13328328/15998032/5bd4b6f6-316d-11e6-9043-69a160946ad1.png)

**Comment by jingouwangzi** [comment]
楼上的，似乎你理解错了，我说的是启动跳出一个命令行窗口，不过我发现用vbs启动就不会出现了。

**Comment by Sam0523** [comment]
话说以前 goagent 为啥可以随时弹出或者隐藏命令行窗口？‎XX 为啥不行？
