### ISSUE TITLE
对检查更新WebUI的一点疑惑

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#365]
launcher/1.4.0/web_ui/config.html
line(388): tip('更新进行中。。。.', "更新完毕！");
这行代码的第二个参数是何意呢 - -

**Comment by Cat7373** [comment]
https://github.com/XX-net/XX-Net/pull/367

**Comment by xxnet** [comment]
估计是个bug

2015-05-08 20:54 GMT-04:00 Cat73 <notifications@github.com>:
