### ISSUE TITLE
无法访问myfreecams.com

### ISSUE THREAD

**Issue by lele2010lele** [XX-net/XX-Net#366]
Sys Platform	darwin
OS System	Darwin
OS version	Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
OS release	14.3.0
OS detail	Release:10.10.3; Version:('', '', '') Machine:x86_64
language	zh_CN
architecture	64bit
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17
XX-Net Version	1.13.5
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.6

May 9 09:17:10 - [INFO] DIRECT t:163 s:35 200 www.google-analytics.com /__utm.gif?utmwv=1.4&utmn=1277307831&utmcs=UTF-8&utmsr=1440x900&utmsc=24-bit&utmul=zh-cn&utmje=1&utmfl=17.0%20r0&utmdt=MyFreeCams.com%20-%20The%20%231%20adult%20webcam%20community.%20Free%20live%20webcams%20and%20video-chat.&utmhn=www.myfreecams.com&utmhid=47188799&utmr=-&utmp=/&utmac=UA-295864-4&utmcc=__utma%3D265273107.1031792456.1431134119.1431134119.1431134119.1%3B%2B__utmz%3D265273107.1431134119.1.1.utmccn%3D(direct)%7Cutmcsr%3D(direct)%7Cutmcmd%3D(none)%3B%2B

**Comment by PaulUlrik** [comment]
我用最新版可以进去啊。那个网站貌似没在自动切换列表里，你确定你用了goagent模式进去吗？

**Comment by lele2010lele** [comment]
我用的稳定版。。。

**Comment by nicegoing** [comment]
这个网站我也进不了。页面显示
·```
500 Internal Error

no-server-data
```

**Comment by xxnet** [comment]
我可以进主页，但无法看视频
