### ISSUE TITLE
无法登录The Economist

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#3663]
英国的杂志 《经济学人》（The Economist）被封后，使用全局代理，可以访问，登录其账户后，虽然不能显示登录了，但能正常阅读（如不登录，每月只能看5篇免费的）。今天忽然不行了，登录账户后，不仅不能显示登录，而且无法阅读，显示“Access Denied / User Login”。而使用另外一款付费的（我的备案）则可以正常登录和阅读。

请问这个问题能否解决下？感谢！

**Comment by jzp820927** [comment]
把 url 地址贴出来，我也来试试

**Comment by farshidvahid** [comment]
url: www.economist.com

**Comment by farshidvahid** [comment]
又试了一下，今天登录后仍然不能显示登录，但可以正常阅读了

**Comment by jzp820927** [comment]
那能正常阅读，就行了吧

**Comment by farshidvahid** [comment]
但最好还是能显示已经登录（我相信不是什么技术难题，考虑到另一款那么廉价的收费VPN 就能做到），这样还是方便点。比如续费什么的，我还需要换另一款收费VPN重新登录。

**Comment by jzp820927** [comment]
刚刚我这边试了一下，可以正常登录，不过我是用的 xxmini，不过是一样的。

**Comment by liuhui0539** [comment]
我挂了代理，电脑能看，但是苹果手机端不能看，界面卡住了。谁能帮帮我解决下

**Comment by xxnet** [comment]
@liuhui0539 

收集日志发邮件：
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E6%8A%A5%E5%91%8A%E9%97%AE%E9%A2%98
