### ISSUE TITLE
论给这个项目添砖加瓦的好处……

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3672]
1:可以找到女朋友，xxnet就是极好的例子
2:可以在朋友圈吹牛逼“你们啊，naive！你们这样是不行的。看看俺在xx-net里面贡献的代码！”
3:可以浓墨重彩地在个人简历上添加一笔“xx-net项目维护者”
4:为国内网路的自由，贡献一分心力
……
什么？你不会！
不会可以学嘛，python很简单滴！
so 大家赶紧来提交代码吧。
然后这真不是在打广告
免责声明：
1:找不到女朋友的不要找俺，找不到男朋友的可以找俺
2:吹牛逼被打脸的，可以虚心向俺学习（教你吹牛逼）
3:本来没有3的，但是为了看上去整齐一点，所以才有了3.

**Comment by lhfly5201314** [comment]
大神，带我装逼，带我飞！！！我没有女朋友。。。。。

**Comment by xiaoyan94** [comment]
大神带我装逼带我飞

**Comment by xiaoyan94** [comment]
需要算法和计算机网络的知识吗

**Comment by YY007H** [comment]
求装逼，求飞

**Comment by lazureice** [comment]
1的意思是你找到女朋友了?

**Comment by yeahwu** [comment]
1的意思是，这就是个相亲贴

**Comment by lazureice** [comment]
「xxnet就是极好的例子」.xxnet找到女朋友了?

**Comment by yeahwu** [comment]
必须的嘛，都说了维护这个项目送女友

**Comment by malthae** [comment]
想要看上去整齐 应该有3和4啊。。。

**Comment by jzp820927** [comment]
事不过三，差不多了。
