### ISSUE TITLE
XXNET上不了https://www.tumblr.com/ ？？？

### ISSUE THREAD

**Issue by 12343954** [XX-net/XX-Net#3679]
XXNET上不了https://www.tumblr.com/ ？？？
怎么破？

**Comment by yeahwu** [comment]
吧tumblr加入代理，俺这边可以的
![2016-06-20 13 00 06](https://cloud.githubusercontent.com/assets/13328328/16183652/242bac30-36e7-11e6-8069-592c5e502821.png)

**Comment by Cat7373** [comment]
我这里可以打开
不过好像好多污污的网站都在这个域名下

**Comment by wenliyang** [comment]
Tumblr 不用翻吧，找个能防 DNS 投毒污染的软件就能破

**Comment by yeahwu** [comment]
不就是上次一个陆家嘴视频导致这个汤不热被封了嘛，里面确实好多小视频。

**Comment by 12343954** [comment]
额，，，，还在用2.9.3，不想升级，怕问题多

**Comment by 12343954** [comment]
@yeahwu 怎么加代理？

**Comment by 12343954** [comment]
PAC脚本里有

`if (dnsDomainIs(host, ".tumblr.com") || host == "tumblr.com") return "PROXY 127.0.0.1:8087";
    if (host.indexOf("blockedonweibo.tumblr.com") >= 0) return "PROXY 127.0.0.1:8087";
    if (dnsDomainIs(host, ".fqrouter.tumblr.com") || host == "fqrouter.tumblr.com") return "PROXY 127.0.0.1:8087";
    if (host.indexOf("fanqiangkan.tumblr.com") >= 0) return "PROXY 127.0.0.1:8087";
    if (host.indexOf("fubaichina.tumblr.com") >= 0) return "PROXY 127.0.0.1:8087";`

**Comment by 12343954** [comment]
@Cat7373  呵呵，少儿不宜

**Comment by 12343954** [comment]
代理加上了，好久不折腾了，都忘光光了
加在SwitchyOmega里

**Comment by malthae** [comment]
XXNET确实不能登陆，可以使用其他工具登陆以后 换成XXnet刷新一下就可以看了
同样xtube我这边也不能登录 但是登陆以后可以用xxnet看

**Comment by xiaoyan94** [comment]
怎么注册……
