### ISSUE TITLE
请问有安卓版本的xx-net吗或者怎样配置

### ISSUE THREAD

**Issue by ksi1110** [XX-net/XX-Net#3680]
如题

**Comment by jzp820927** [comment]
只有测试版，无正式版

**Comment by wpp214** [comment]
测试版本的有放出来吗 能给我个连接 看一下吗

**Comment by jzp820927** [comment]
https://github.com/XX-net/xxnet-android/releases

**Comment by Michael7CAT** [comment]
下载了一个，直接停止运行

**Comment by jzp820927** [comment]
所以说是测试版的，很多人反映运行不了，X大也没维护了，建议你用 PC运行+PAC模式 给手机用。

**Comment by nly4lov** [comment]
我想笑。因为我也经常遇到停止运行的APK

**Comment by LMJavaLife** [comment]
安卓我一般用的是lantern，不过明显没XX-NET稳定

**Comment by jzp820927** [comment]
蓝灯现在已经是和 tor 一个级别了。

**Comment by nly4lov** [comment]
@jzp820927 no idea. what's that supposed to mean?

**Comment by jzp820927** [comment]
就是慢成翔了。

**Comment by nly4lov** [comment]
![qq 20160529140801](https://cloud.githubusercontent.com/assets/11325411/16324918/8502387e-39eb-11e6-81f8-1873b8e84128.png)

**Comment by zhouxiaodo** [comment]
安卓版本的xx-net怎么用啊

**Comment by jzp820927** [comment]
目前还没有正式的安卓版本，只有一个测试版

**Comment by decemer** [comment]
蓝灯怎么配置速度快呢
