### ISSUE TITLE
start.bat / start.vbs isn't working. xx-net would not be installed.

### ISSUE THREAD

**Issue by matreex** [XX-net/XX-Net#3694]
Hi,
On windows7, start.bat / start.vbs isn't working. i don't know why, because i updated XX-Net from v2.6.2 to v3.2.2, so i deleted v2.6.2 of full folder and extracted XX-Net.v3.2.2.zip, and run start.bat or start.vbs, but it's happended anything, i don't know why, plz help, thanks.

run cmd: path\python path\start.py, and got it:
# ----------------------------------
"C:\Program Files\XX-Net\code\default\python27\1.0\python.exe" "C:\Program Files\XX-Net\code\default\launcher\start.py"
Traceback (most recent call last):
  File "C:\Program Files\XX-Net\code\default\launcher\start.py", line 66, in <module>               
    from win_tray import sys_tray
  File "C:\Program Files\XX-Net\code\default\launcher\win_tray.py", line 18, in <module>            
    import win32_proxy_manager
  File "C:\Program Files\XX-Net\code\default\python27\1.0\lib\win32\win32_proxy_manager.py", line 22
, in <module>
    CONNECTIONS = winreg.OpenKey(winreg.HKEY_CURRENT_USER, CONN_PATH, 0, winreg.KEY_ALL_ACCESS)                
WindowsError: [Error 5]
# ----------------------------------
I found v2.6.2 can be installed.

**Comment by Cat7373** [comment]
1. start cmd
2. cd "C:\Program Files\XX-Net\"
3. "code\default\python27\1.0\python.exe" "code\default\launcher\start.py"
4. If still not working, Please feedback output.

**Comment by Cat7373** [comment]
···
ERROR_ACCESS_DENIED
5 (0x5)
Access is denied.
···
As if you do not have permission to access the registry.

**Comment by Cat7373** [comment]
Try booting with administrator privileges

**Comment by yj1** [comment]
这是哪国的，也需要翻墙？

**Comment by matreex** [comment]
@Cat7373 OK, done. OIC. i set permission to access the registry. so... my fault.
"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections"
set to allow.

**Comment by drg78rnvgh** [comment]
新加坡人或印尼人

**Comment by jzp820927** [comment]
原来 新加坡，印尼 也有墙，我还用的蓝灯的新加坡服务器呢。

**Comment by drg78rnvgh** [comment]
@jzp820927 
你看他的名字叫Jason Kwan
就知道他是个香蕉人

**Comment by jzp820927** [comment]
香蕉人？求科普

**Comment by matreex** [comment]
But... PAC will be added to IE Proxy when lantern started, so i need lock IE Proxy, set permission of "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections" to reject, if i do this, xx-net v3.2.2 don't start, but v2.6.2 can start, why?
