### ISSUE TITLE
建议增加开机自启动功能设置

### ISSUE THREAD

**Issue by streamgo** [XX-net/XX-Net#37]
如标题。

**Comment by xxnet** [comment]
收到，请问是什么操作系统？

**Comment by streamgo** [comment]
我是WIN7 64位操作系统。goagent 是正常的。可以添加自启动。

2015-02-26 21:37 GMT+08:00 xxnet <notifications@github.com>:

**Comment by novicewu** [comment]
支持！我自己把桌面的快捷方式拖到[开始菜单>启动]下面，可以实现开机启动。但是每次开机都会弹出要确认，很烦人。能不能像GoAgent那样安静地自动启动？(操作系统win 7 x64)

**Comment by streamgo** [comment]
同意楼上的！赞！

**Comment by xxnet** [comment]
“每次开机都会弹出要确认”，是提示什么？

**Comment by novicewu** [comment]
就是自运行行python需要管理员权限，需要点确认是否允许运行

**Comment by xxnet** [comment]
这是检测到证书没有安装，才需要提示管理员权限，理论上只会出现一次，也许存在bug，检测存在问题。

**Comment by novicewu** [comment]
是的。每次开机都会提示。请帮忙修复，谢谢! :-)

**Comment by xxnet** [comment]
1.1.0 新增了开机启动选项了，晔！

**Comment by Megadotzip** [comment]
还是python2.7版本呢，什么时候发布python3.x版本的xxnet
