### ISSUE TITLE
能否加入iplist和智能代理功能

### ISSUE THREAD

**Issue by ivysrono** [XX-net/XX-Net#370]
gfwlist并不全，维护保守，很多都没有。
目前有两种解决方案：
1、通过ip判断，只要是国外的就走代理
2、智能代理，就是规则外的网站如果无法顺利访问就自动转为代理访问，这是WallProxy采用的方式。
当然WallProxy智能代理有点问题，比方说win8应用商店无法访问，等等。
个人感觉第一种ip判断方案应该更现实一些。

**Comment by xxnet** [comment]
有一种方式，根据域名的注册地判断。

有考虑过，可以设计一个智能代理模块，在所有代理模块的前面接收浏览器的请求，根据规则去切换。
规则可以很多种，包括逐个尝试可用的方式。

包括自己作DNS解析，然后自己建立链接。
包括Host的模式。


不过这样的项目很耗人力，需要大家来参与。


在 2015年5月9日 上午3:50，renyouguo <notifications@github.com>写道：

**Comment by xxnet** [comment]
可以找SwitchOmega的作者来开发

浏览器里的切换操作最直接方便。
