### ISSUE TITLE
访问google scholar: 网络中存在异常流量

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#3702]
今天使用xxnet翻墙，访问google scholar时，无法登录，显示：

我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？
IP 地址：***.178.***.***
时间：2016-06-24T00:31:09Z
网址：http://www.google.com/

本人的操作系统:win7
xx-net 版本，3.1.19
日志：
Jun 24 08:33:45.808 - [DEBUG] GAE GET https://scholar.google.nl/favicon.ico
Jun 24 08:33:46.404 - [INFO] GAE t:595 s:1704 GET https://scholar.google.nl/favicon.ico get_response:595
Jun 24 08:33:49.016 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D
Jun 24 08:33:49.539 - [INFO] GAE t:523 s:2849 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D get_response:523
Jun 24 08:33:49.695 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D
Jun 24 08:33:50.039 - [INFO] GAE t:344 s:606 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D get_response:344
Jun 24 08:34:06.895 - [DEBUG] GAE POST https://mail.google.com/mail/u/0/?ui=2&ik=7ae63bcef8&rid=a277..&at=AF6bupPGx3ot0LLsdrGM94SUFxXGhIob0g&view=tl&start=0&num=70&lhop=793702<up=%5Ei&slmm=155759a23897d874&scid=4g87vtla9obw&avw=1748&as=0&auto=1&ver=8cYU8dlsE7Y.en.&am=!osuh_XHx3QAXFHLmHWdHPRzuNvBQdBgnrJmNRq6lwtMmBLWZTlr1_QwV3MLb4lVOKXNU3p29yHL0&vas=1&ari=180&sstart=0%2C0%2C0&iosc=%5Esmartlabel_personal%7C%5Esmartlabel_social%7C%5Esmartlabel_promo&ioss=50%2C50%2C50&_reqid=2129698&pcd=1&mb=0&rt=j&search=mbox
Jun 24 08:34:07.208 - [INFO] GAE t:312 s:1007 POST https://mail.google.com/mail/u/0/?ui=2&ik=7ae63bcef8&rid=a277..&at=AF6bupPGx3ot0LLsdrGM94SUFxXGhIob0g&view=tl&start=0&num=70&lhop=793702<up=%5Ei&slmm=155759a23897d874&scid=4g87vtla9obw&avw=1748&as=0&auto=1&ver=8cYU8dlsE7Y.en.&am=!osuh_XHx3QAXFHLmHWdHPRzuNvBQdBgnrJmNRq6lwtMmBLWZTlr1_QwV3MLb4lVOKXNU3p29yHL0&vas=1&ari=180&sstart=0%2C0%2C0&iosc=%5Esmartlabel_personal%7C%5Esmartlabel_social%7C%5Esmartlabel_promo&ioss=50%2C50%2C50&_reqid=2129698&pcd=1&mb=0&rt=j&search=mbox h2_get_head:311
Jun 24 08:34:15.354 - [INFO] GAE t:45459 s:42 GET https://1.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20160620.11_p0&gsessionid=wOqUpQlkrFOVwPGzHiGVgdHrPjNTFy0K&VER=8&RID=rpc&SID=34BBBCED4EFD3D04&CI=1&AID=7&TYPE=xmlhttp&zx=6bv7ayuzhu32&t=2 h2_req:15,get_response:45428
Jun 24 08:34:15.973 - [DEBUG] GAE GET https://1.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20160620.11_p0&gsessionid=wOqUpQlkrFOVwPGzHiGVgdHrPjNTFy0K&VER=8&RID=rpc&SID=34BBBCED4EFD3D04&CI=1&AID=13&TYPE=xmlhttp&zx=9tfd65a9enao&t=1
Jun 24 08:34:19.492 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D
Jun 24 08:34:19.861 - [INFO] GAE t:368 s:2279 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D get_response:361,h2_finish[SP:1356936]:2
Jun 24 08:34:19.962 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D
Jun 24 08:34:20.291 - [INFO] GAE t:327 s:402 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=AGD3Og9d4PCejMcLeIuj5g%3D%3D get_response:322,h2_finish[SP:416480]:2

**Comment by jzp820927** [comment]
升级到最新版试试

**Comment by withero** [comment]
屏蔽 XX-Net\code\default\gae_proxy\local\proxy.ini 中的
;.google.com = direct

前面的分号去掉，原理不清楚。

**Comment by farshidvahid** [comment]
改完之后确实可以了。感谢！

**Comment by jzp820927** [comment]
最新版应该就是这个直连的配置
