### ISSUE TITLE
关于proxy.pac的功能

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#3705]
在选择“全局PAC智能代理"的模式下，直接修改proxy.pac文件是不是就可以自主添加代理网站.
比如我要添加".uk"结尾的所有网站使用xx-net代理就直接在pac文件中添加
`if (shExpMatch(host, "*.uk")) return "PROXY GOAGENT_LISTEN";`
就可以

**Comment by Cat7373** [comment]
这个是不可以的哟~

**Comment by jzp820927** [comment]
可以 google 一下 pac 的语法结构，自己从写一个pac

**Comment by funray** [comment]
可修改文件顶部的FindProxyForURL()函数，例如图中的amazonaws.com
![screenshot from 2016-06-24 16-31-26](https://cloud.githubusercontent.com/assets/5118705/16332543/3132d490-3a29-11e6-84e8-f20e90852ccc.png)

**Comment by jzp820927** [comment]
不确定直接修改 XX 内置的 PAC 文件，会不会被重写覆盖，最好是自己编写一个独立的 PAC 文件。

**Comment by funray** [comment]
我试过，有效。

**Comment by jzp820927** [comment]
内置的 PAC 是从 gfwlist 生成的，不知道是只生成一次，还是会定期更新，或者每次启动更新，如果有更新的话，肯定会被覆盖。

**Comment by funray** [comment]
我使用此方法1个月左右了，初步推测它只生成1次。

**Comment by jzp820927** [comment]
那可能就是这样吧，我是自己维护的独立的 PAC，没用过内置的，不太了解

**Comment by taoist1994** [comment]
@funray 感谢，我也试过了，确实有效，而且这个方法可以替代使用switchy omega插件做切换。
