### ISSUE TITLE
部分网站需要固定ip

### ISSUE THREAD

**Issue by ivysrono** [XX-net/XX-Net#371]
该网站目前是不断被要求重新登录
http://www.sis001.com/forum/forumdisplay.php?fid=322&filter=type&typeid=1256&orderby=dateline&ascdesc=DESC
goagent 和 WallProxy 都很正常。

**Comment by xxnet** [comment]
恩，目前的方案，要固定ip，也是有可能的，不过会牺牲一定的性能。

思路是某写需要固定ip的域名，固定同一个链接去访问。
1.需要白名单，哪些域名或url匹配。
2.这个域名用过的ssl_socks链接，就保留给这个域名使用。
  下一个请求，都只能通过这个链接来进行。
3. 或者要同一个ip或同一个段的ip再去建立链接
   这个目前架构不支持，改动太大了。

2015-05-09 3:51 GMT-04:00 renyouguo <notifications@github.com>:

**Comment by yjd** [comment]
这就跟我说的那个cookie丢失问题一样。。我把ip列表导到goagent的配置里，不存在这个问题，可以参考源代码看看。

**Comment by kmcbest** [comment]
我支持这个思路，用Google搜索经常被要求输入验证码 图形码，就是因为ip不固定，某些ip被Google认为「活动可疑」
