### ISSUE TITLE
mac不打开xx-net就连不上网了

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#3717]
在mac下使用xx-net, 应该是在终端执行了什么命令,导致它一直去找代理, 当我第二次开机,不启动xx-net的时候就会出现连上wifi,不能上网的情况.求原因

**Comment by cc941201** [comment]
请在网络偏好设置的高级里面将代理中的所有勾去掉
![2016-06-26 22 30 33](https://cloud.githubusercontent.com/assets/3082401/16362954/6a2e2832-3bee-11e6-82f5-8e5b4321dd55.png)

**Comment by andylee1890** [comment]
十分感谢🙏
            在2016年06月26日 22:37，CC-Dog 写道:请在网络偏好设置的高级里面将代理中的所有勾去掉
