### ISSUE TITLE
关于判断网络连接状态的问题

### ISSUE THREAD

**Issue by Rongronggg9** [XX-net/XX-Net#3720]
现在 XX-Net 可以检测电脑本身断网并防止掉 IP，但我实测 XX-Net 对路由器断网无能为力(即：电脑能够连接到上层设备却不可真正联网)(这种情况也挺常见的)，此时 XX-Net 不能识别出正处于断网状态，IP 可以全部掉完(会有少许剩余，很奇怪)。

这个检测可能较难(特别是在有所限制的网络环境下，比如公司或学校等)，我有个思路：
内置一些国内网站的列表(这里可以提供自定义，供处于特殊网络环境的用户使用)，在正常时记录有哪些可以访问；
当 IP 异常连续掉一定数量后，触发检测；
依次检测**在正常时可以访问的国内网站**，若均无法连接，则可判定为上层设备断网；
恢复异常掉的 IP，进入断网模式。

感谢各位。

**Comment by jzp820927** [comment]
我觉得应该很容易实现吧，只要后台有一个 deamon 一直 ping 外网IP就可以了（不如 ping 114.114.114.114），检查 timeout 就行了

**Comment by Rongronggg9** [comment]
@jzp820927 你想得太简单了，有些学校或公司会封锁掉一些网站，所以要内置一个列表。一直 ping 过于浪费，所以要在 IP 异常后开始检测

**Comment by Rongronggg9** [comment]
@yeahwu @xx-net 好像没人看到啊…

**Comment by xxnet** [comment]
xx-net不检测本地网卡状态的，而是判断是否能够连上微软、苹果服务器作为依据。
掉ip是临时的，一旦检测到网络确实不通（微软、苹果都连不上），这些ip就会恢复回去。

在不幸的情况下，刚好几百个google ip 无法连接，而刚好有一次微软能够连上，就会出现把这些ip列为无效ip。

这个时候，​重启一下xx-net就好了吧



此时如果重启xx-net进程，会重新尝试这些失败的ip，稍微等几分钟，就可以使用了。

这个逻辑，你也可以研究下代码，基本在 google_ip.py，check_ip.py，要设计一个完全自适应的逻辑，需要考虑更多可能。
比如检测延迟、偶然的网络卡顿、网络恢复后自动恢复工作。
当然还有尽量保持代码的独立和简洁。
欢迎探讨。

**Comment by Rongronggg9** [comment]
@xxnet 但是在我的实际使用中，我每次 Modern 掉线了 (此时是绝对不可能连接到外网的，这个 Modern 是我家有线网方面唯一的出口) ，IP 就会不停地掉直到剩下30-60个 (每次都有剩，不知道为什么会这么奇怪)，重启XX是没有用的，不会恢复。
为此我还特意测试过拔掉 Modern ，同上。
路由器不是智能路由器……
