### ISSUE TITLE
做了个超大的 Google IP 扫描范围库诶

### ISSUE THREAD

**Issue by Rongronggg9** [XX-net/XX-Net#3721]
https://github.com/Rongronggg9/Google-IP-Range

**Comment by drg78rnvgh** [comment]
这个很危险啊，楼主。
作为goa、gop的忠实用户，存攒了几年的亚洲ip段，它这里竟然都有.....
劝楼主发几天后自删把....

**Comment by 935352** [comment]
超大型IP库赞

**Comment by hwbasd** [comment]
不需要吧，我一般都够了呀。。。
![default](https://cloud.githubusercontent.com/assets/17849005/16366614/6e73b0b6-3c4c-11e6-9e0c-1a8f5c35d62d.png)

**Comment by hcym** [comment]
large

感谢

**Comment by Rongronggg9** [comment]
@drg78rnvgh 其实有是很正常的，因为这几乎把所有可能含有、现在含有、曾经含有 Google IP 的 IP 段都囊括了。
删除的话……5天后我把 **Large** 删掉吧。不过其实删掉也没啥用的，我都是在网上收集并整合的。

**Comment by drg78rnvgh** [comment]
@Rongronggg9 
之前xx-net内置ip被全封的教训啊......

**Comment by Rongronggg9** [comment]
@drg78rnvgh 我知道啊

**Comment by iceliquid23** [comment]
![1](https://cloud.githubusercontent.com/assets/19250468/16372653/42db8684-3c80-11e6-8496-235f0d67006a.jpg)

感觉我也不需要啊。。。

**Comment by jzp820927** [comment]
其实上次 XX内置IP被封，也只是那段时间的敏感期，后来没多久就恢复了。

**Comment by fengixng** [comment]
上次封锁不是针对XX的，而是针对所有证书为google的IP的，很大一部分XX没有收集，网上也没有出现的IP段都被封锁了

**Comment by Rongronggg9** [comment]
@iceliquid23 封锁不严重就没所谓啦

**Comment by Rongronggg9** [comment]
@drg78rnvgh  正如@fengixng 所说，我估计 GFW 手上有着全球最全的 Google IP 库呢 (当然不够 Google 自己的全) ，我这点还算不了什么。

**Comment by lindongbin** [comment]
备用，虽然最近IP基本都有六七千

**Comment by jzp820927** [comment]
赶脚现在不怎么封IP了，而是改变策略，进行疯狂掉包 和 疯狂限速（QoS）。

**Comment by Rongronggg9** [comment]
@jzp820927 的确。

**Comment by wialny** [comment]
不知道是google新增了国内的ip还是墙放松了封锁, 我现在的ip都是延迟60以下, 最低的甚至还有24ms的.
查询都是显示美国(Mountain View, California, United States), 但这延迟明显就是国内才有的啊
不过这些ip都有丢包的问题

**Comment by Rongronggg9** [comment]
@wialny 墙放松了，毕竟敏感时期过了。
至于低延迟和丢包，很有可能是墙伪造了 ping 请求的回复，把差的 IP 伪装成好的，或者是直接截取请求，获取信息

**Comment by wialny** [comment]
@Rongronggg9 但这些低延迟IP的下载速度也非常快, 瞬间速度能突破1M, 之后稳定在500K左右. 看youtube的1080P60毫无压力

**Comment by Rongronggg9** [comment]
@wialny 诶，那就有点扑朔迷离了

**Comment by wialny** [comment]
@Rongronggg9 随便拿了一个ip做测试. 这个ip直接访问会跳转到google.com
http://ceba.wangsucloud.com/wstCeba/ping/ping-test!result.action?id=28d2948c89f94847ad9798d8db3510fe
看起来服务器在广东?

**Comment by Rongronggg9** [comment]
@wialny 我早上起来也 ping 一下看看
不得不说这 ping 结果的地理位置和网络提供商也真是巧啊…

**Comment by Rongronggg9** [comment]
@wialny 
PING 216.239.37.1 (216.239.37.1): 56 data bytes
64 bytes from 216.239.37.1: seq=0 ttl=52 time=12.620 ms
64 bytes from 216.239.37.1: seq=1 ttl=52 time=14.555 ms
64 bytes from 216.239.37.1: seq=2 ttl=52 time=14.209 ms
64 bytes from 216.239.37.1: seq=3 ttl=52 time=12.527 ms
64 bytes from 216.239.37.1: seq=4 ttl=52 time=14.143 ms

--- 216.239.37.1 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 12.527/13.610/14.555 ms

这速度，太丧病了，即使我是ADSL也有这速度

**Comment by hulainwang** [comment]
属性	值
本地网络状态	OK
IP数量	7047
空闲	0
IP延迟	141
连接池(帮助)	新:2 h1:19 h2:10
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	200
屏蔽状态(帮助)	OK


不知道为什么就这么多了，以前只有300+

**Comment by Rongronggg9** [comment]
@hulainwang 毕竟最近封锁有所放松

**Comment by wialny** [comment]
@Rongronggg9 所以这ip实际位置到底是哪的? 感觉不像是香港, 因为香港ip我这里的平均延迟要有40~50

**Comment by Rongronggg9** [comment]
感觉的确是广东，因为我 ping 联通宽带提供的的DNS也是这个延迟

**Comment by Rongronggg9** [comment]
@wialny 如果你看到回复了我就把刚刚那条删掉，感觉容易被查水表

**Comment by wialny** [comment]
@Rongronggg9 嗯, 那个ip我也删掉好了

**Comment by magnet1215** [comment]
请教，怎么用啊？

**Comment by jzp820927** [comment]
添加到 XX IP 库就行了

**Comment by roc1010kmt** [comment]
用樓主這個ip庫不行，ip狂減到5.6個。

**Comment by Rongronggg9** [comment]
@roc1010kmt 唔……理论上来讲是没有问题的，因为囊括了 XX-Net 的所有 IP 段，理论上来讲不会减少……

不过实际上嘛……可能乃扫描太频繁被运营商限制了吧……也可能自动触发了验证所有 goodip ，导致本来就不可用但是没有除去的被除去了……

不过! 我准备要删掉这个 Repo 了…最近有些害怕￣へ￣

**Comment by jzp820927** [comment]
是发生什么大事了麽？害怕神马？

**Comment by Rongronggg9** [comment]
@jzp820927 这里是什么事都没发生啦……
至于害怕…确实和最近的这些事有关……

**Comment by jzp820927** [comment]
好吧，我懂了，不用说明了
