### ISSUE TITLE
twitter提示没有证书,请问怎么解决.

### ISSUE THREAD

**Issue by mtvktvcn** [XX-net/XX-Net#373]
twitter提示没有证书,请问怎么解决.

**Comment by mtvktvcn** [comment]
有人来教一下吗?

**Comment by xxnet** [comment]
是什么操作系统？什么浏览器？

除了Windows+ Firefox需要手动导入证书，大部分平台浏览器已经实现自动导入证书了。

2015-05-09 7:35 GMT-04:00 mtvktvcn <notifications@github.com>:

**Comment by mtvktvcn** [comment]
彻底删除浏览器,再重装好了.
折腾了半天.
感谢楼上的回复.
