### ISSUE TITLE
作为一名开发者, 我对3.2.4版很不满意!

### ISSUE THREAD

**Issue by hzxie** [XX-net/XX-Net#3733]
**Conclusion:** 自动更新太危险, 请不要乱开好嘛!

说说Bug:
1. Windows 7 64 Bit下直接跪了, 根本启动不起来, 表现为无法翻墙, 无法打开`127.0.0.1:8085`.
2. macOS 下托盘上有2个图标, 分别是2个版本的, 说明在自动更新后启动了2个XX-Net.

请问发布新版本前测试了吗! 差评!
虽然我恢复一下分分钟的事, 可是你让End User情何以堪!

**Comment by cc941201** [comment]
这些问题都是出在老版本，目前更新方式为整体更新，则老版本的自动更新代码出问题没法直接修复，这次更新后至少下次能正确更新。

这几个问题退出重开都能解决

**Comment by yeahwu** [comment]
组织批评的对呀！
首先俺测试了，是真测试了。可能是水平太渣，没测试出来。
接受批评，下次改正！（你tm不去逛V2EX，跑到这找茬鸟，俺委屈）

**Comment by Rongronggg9** [comment]
我才不会说其实win下自动更新后也会有两个图标呢。
不过我倒是没有遇到无法启动的问题，只是每次启动都有两个图标。
然后我一看，code 文件夹下有 default 和 3.2.4 两个文件夹，default 里面是旧版的，看来自动更新在删除旧版这方面有问题啊。
(于是我就删掉了 default ，把 3.2.4 重命名成了 default )

**Comment by yeahwu** [comment]
啊，有这事，好像问题挺严重哪！

**Comment by Rongronggg9** [comment]
而且，为什么自动更新的稳定版也是 3.2.4 了，这不是赤果果的作死嘛

**Comment by yeahwu** [comment]
这个是因为旧版代码有问题，在3.2.4版改好了。所以只得全部更新到3.2.4
因为更新到别的版本会出错。

**Comment by Rongronggg9** [comment]
这样啊

**Comment by yeahwu** [comment]
还需要观察，正常情况是关了，重启一下就好了。
如果是你说的这种情况，就还需 @cc941201 改进

**Comment by hcym** [comment]
強國人崩潰

**Comment by nly4lov** [comment]
我直接下载了删除原来的目录下所有只剩下data文件夹，然后解压放进去，一切OK![qq 20160529140801](https://cloud.githubusercontent.com/assets/11325411/16405510/d759f376-3d3a-11e6-90f9-b12388f5f6a6.png)

**Comment by yeahwu** [comment]
然而，俺们需要你测试更新哪！汗

**Comment by nly4lov** [comment]
好吧，正好我闲得不想干正事，重来一 遍

**Comment by nly4lov** [comment]
你可知道我为什么不喜欢自动更新？因为速度从几K到几十K，慢得要死

**Comment by nly4lov** [comment]
刚过50%![e103](https://cloud.githubusercontent.com/assets/11325411/16405832/1c6d38e0-3d3d-11e6-909f-06a73841cbc5.gif)

**Comment by yeahwu** [comment]
@nly4lov 这样才对嘛。更新完别忘了重启一下！
俺刚在xp虚拟机里又测了一遍，没啥问题!(原谅俺，不会用win10）

**Comment by nly4lov** [comment]
我更新完（web界面提示downloading complete），我就退出google chrome，再打开就是像大家说的那样，8085进不去了啊，google网站也打不开了
退出xx再启动，就好了。这有啥测试的嘛![qq 20160524145333](https://cloud.githubusercontent.com/assets/11325411/16406017/416274b6-3d3e-11e6-9e0f-1b385823d0d9.jpg)

**Comment by nly4lov** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:845
network-status: OK
connected-link: new:2 used:0
worker: h1:27 h2:12
scan-ip-thread-num: 50
ip-quality: 228
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zjhzxhz** [comment]
我好像是3.2.0升级到3.2.4的
分分钟恢复的方法如下:
```
git add -A
git reset --hard
git pull
```
(嘚瑟的表情)

**Comment by yeahwu** [comment]
嗯，要的就是这结果，谢谢反馈！另外，你是啥系统？

**Comment by nly4lov** [comment]
我后来帖了诊断日志啦！win10 64位最新中文版，就是四月份那版1511

**Comment by zjhzxhz** [comment]
@yeahwu 
一会儿要出远门~ 没时间逛V2EX~ 
然后发现XX-Net跪了~ 然后就来这儿吐槽了。

**Comment by yeahwu** [comment]
@zjhzxhz 重启一下的事，让你搞得这么复杂。reboot不就好鸟！

**Comment by nly4lov** [comment]
这不应该叫reboot,分明只是个restart

**Comment by zjhzxhz** [comment]
长期使用Linux的用户清楚的知道，重启是不能解决问题的。
所以我慢慢就失去这个技能了。 - -|||

**Comment by yeahwu** [comment]
@nly4lov 好同志，赞一个
@zjhzxhz  坏同志，找不到女票

**Comment by nly4lov** [comment]
我也水一帖去，不然咋能叫水王

**Comment by zjhzxhz** [comment]
@yeahwu 
我不需要女票~ 找个男票就好了(doge脸)

**Comment by yeahwu** [comment]
俺住隔壁，俺姓王！

**Comment by nly4lov** [comment]
你说姓王 我忽然想起一个同学唱的快板词开头两句：老王媳妇本领强，专夹别人疙瘩榔。。。。![qq 20160529140801](https://cloud.githubusercontent.com/assets/11325411/16406280/de279190-3d3f-11e6-838f-07c832916054.png)

**Comment by hehh2001** [comment]
开发老大都是欠你们的？？用着如果优秀免费的工具还TMD整天jjyy.有问题先自行解决，解决不了再求助不懂吗？最基本的尊重都不懂吗？伸手党还罢了，最可气的是无毛党也在

**Comment by yeahwu** [comment]
@hehh2001 大家都是兄弟，和气生财！就是平时开玩笑罢了，不要在意。大家都和气点 @zjhzxhz

**Comment by Rongronggg9** [comment]
@hehh2001 不能这么说吧…
毕竟提出批评还是有利的
而且不是说了请大家帮忙测试反馈么 #3729

**Comment by nly4lov** [comment]
楼上说得对。装逼的不要。

**Comment by yeahwu** [comment]
是滴，是俺要求测试的，有问题就提出来。没事滴，大家和和气气，不要打仗就好！
感谢反馈。

**Comment by nly4lov** [comment]
腰里别铳牌，谁说冲谁来![qq 20160529140801](https://cloud.githubusercontent.com/assets/11325411/16406802/e624c450-3d42-11e6-9c1e-e492db33e8f9.png)

**Comment by lele2010lele** [comment]
mac系统下启动了俩，竟然没有ip可用，以前7000的有效ip，我一看竟然更新了

**Comment by yeahwu** [comment]
你关掉重启一下看，会不会好！
lele2010lele <notifications@github.com>于2016年6月29日 周三11:34写道：

**Comment by yeahwu** [comment]
@lele2010lele 另外问一下，中文语言mac os 下的xx-net菜单是中文吗？

**Comment by overthehorizon123** [comment]
我是从3.1.19升级到3.2.4的，目前没发现太大的问题。只是，ip数量掉的有点快，速度与3.1.19相比也有些慢。

**Comment by zjhzxhz** [comment]
@506066
怎么感觉像某人的小号.
灰啊灰? 我的骄傲放纵 ...
