### ISSUE TITLE
用了一段时间就上不了了，添加IP也不行到底是什么回事

### ISSUE THREAD

**Issue by chemfly** [XX-net/XX-Net#3739]
XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1990
network-status: OK
connected-link: new:0 used:0
worker: h1:6 h2:6
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yeahwu** [comment]
这个扫描线程0，删除data文件，重新配置，扫描一下
另外不建议导入ip，让它慢慢扫，速度会好点

**Comment by chemfly** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:90 good:16
network-status: OK
connected-link: new:3 used:0
worker: h1:17 h2:4
scan-ip-thread-num: 50
ip-quality: 1047
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by chemfly** [comment]
还是连不上= =。以前用win7那个很快的，现在换了mac系统，不知是不是我不熟悉这系统的原因。今天弄了一下午了，好了一会，去吃个晚饭回来就不行了，，，，又继续弄一晚上，结果还是不行

**Comment by yeahwu** [comment]
这下看来，好像没什么问题呀？需要多扫一下ip

**Comment by chemfly** [comment]
![mac xxnet](https://cloud.githubusercontent.com/assets/5959735/16417283/a14b922a-3d77-11e6-9c07-9c8d4c4ed846.png)
老是这样

**Comment by chemfly** [comment]
是不是要设置网络？我用的是校园网的。

**Comment by yeahwu** [comment]
30分钟后再来反馈，看状态页，ip数量少，延时较高。不要关闭xxnet，让它扫30分钟

**Comment by yeahwu** [comment]
早说嘛，校园网还费那劲

**Comment by chemfly** [comment]
打不开= = 。
![Uploading xxnet2.png…]()
![Uploading xxnet2.png…]()
![Uploading xxnet2.png…]()

**Comment by chemfly** [comment]
启用不了

**Comment by jzp820927** [comment]
校园网都有 IPv6，你咋个会启动不了呢，你那儿没 IPv6 吗？

**Comment by chemfly** [comment]
我也不懂，应该是有ipv6的，我用Safari登ipv6.google.com都可以直接进

**Comment by jzp820927** [comment]
不知道你说的具体是什么状况，是 IPv6 的开关按钮点了没反应？还是按钮点开了，实际没效果？

**Comment by chemfly** [comment]
![xxnet ipv6](https://cloud.githubusercontent.com/assets/5959735/16437488/06ad23a6-3dda-11e6-8285-939ccdabd21d.png)
就是点开显示失败

**Comment by jzp820927** [comment]
看按钮状态 IPv6 是开启对，但是看你顶楼发的状态信息 ipv6-status: 0，ipv6 又是 0，没开启。
可以试试在 manual.ini 中直接改 ipv6 = 1，开启 ipv6
