### ISSUE TITLE
1024打不开

### ISSUE THREAD

**Issue by yanton** [XX-net/XX-Net#374]
报错：502
Python Urlfetch Error: 'GET'

DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: http://t66y.com/index.php',), timeout=19
DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: http://t66y.com/index.php',), timeout=38

**Comment by xxnet** [comment]
其他人有这问题吗？我这边正常。

2015-05-09 6:57 GMT-04:00 Yantong Wang <notifications@github.com>:

**Comment by chenj0726** [comment]
我这边也有相同的问题，连报错信息都一致。

Message From FetchServer
Python Urlfetch Error: 'GET'

DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: http://t66y.com/index.php',), timeout=19
DeadlineExceededError('Deadline exceeded while waiting for HTTP response from URL: http://t66y.com/index.php',), timeout=38

单独使用goagent，goagent 工作正常时，不会有这个error

**Comment by xxnet** [comment]
重现了这个现象，是老的服务端就可以工作，我研究下。

2015-05-15 22:45 GMT+08:00 chenj0726 <notifications@github.com>:

**Comment by uhfghkurf** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
航至滤空闪
