### ISSUE TITLE
教育网。ipv6设置打不开

### ISSUE THREAD

**Issue by chemfly** [XX-net/XX-Net#3744]
XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:2669 good:1590
network-status: OK
connected-link: new:2 used:0
worker: h1:17 h2:6
scan-ip-thread-num: 35
ip-quality: 126
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by chemfly** [comment]
爬不了墙，今天早上来，可以打开Google主页，点邮箱的时候就打不开了，然后现在再点Google主页又打不开了。。。网络是教育网，用的无线路由，

**Comment by yeahwu** [comment]
你以前有没有开启或者启用过IPv6？
chemfly <notifications@github.com>于2016年6月29日 周三07:28写道：

**Comment by chemfly** [comment]
好像昨天下午点过，不过好像开不了。然后我用Safari直接上ipv6.google.com能上，而且gmail也能打开。因为是昨天才拿到电脑的，不熟悉osx系统，自己搜了一下午都解决不了，然后就跑过来问问题了= =，

**Comment by chemfly** [comment]
so sorry，是我自己设置有问题。我仔细看了switchy设置，有个规则设置错了，，，，
