### ISSUE TITLE
版本3.2.4，有效IP数量飞涨...

### ISSUE THREAD

**Issue by IsabellRoy** [XX-net/XX-Net#3746]
![default](https://cloud.githubusercontent.com/assets/20197016/16437367/e888228c-3dd8-11e6-9cbc-db66c011552a.JPG)
![1](https://cloud.githubusercontent.com/assets/20197016/16437369/eb3b9bb2-3dd8-11e6-9b08-62cf4d65dc93.JPG)
同样的IP，昨天用3.2.1检查的时候只有3000个有效的，今天升级到3.2.4之后又检查了一遍，结果95%的IP都活过来了，会不会是显示上的bug？

**Comment by jzp820927** [comment]
你这个不会是 IPv6 吧

**Comment by IsabellRoy** [comment]
IPV4，内蒙古联通(/・ω・)/

**Comment by yj1** [comment]
我的也是。

**Comment by yj1** [comment]
昨天100多，今天2000多。

**Comment by hwbasd** [comment]
的确是很多。。。
![1](https://cloud.githubusercontent.com/assets/17849005/16437833/a8956190-3ddc-11e6-90ec-4edee54e75ba.png)

**Comment by IsabellRoy** [comment]
掉回3000惹...看来只是墙在例行抽风(´；ω；`)

**Comment by yeahwu** [comment]
速度还是以延时为准，和数量没什么太大的关系，3.2版本以后俺改为最大IP3000了！
IsabellRoy <notifications@github.com>于2016年6月29日 周三12:00写道：

**Comment by yjd** [comment]
开发者换人了？名字不一样。

**Comment by yeahwu** [comment]
开发者是一群人，有时间，有能力来提交代码就是开发者了。
yjd <notifications@github.com>于2016年6月29日 周三12:30写道：

**Comment by jzp820927** [comment]
鉴定：抽风

**Comment by fengixng** [comment]
大约七八个小时前google全国性的解封了一段时间，但是很快就全部封锁，所以你可以认为是GFW抽风

**Comment by jzp820927** [comment]
估计是 GFW 的服务器不堪重负，例行重启。

**Comment by drg78rnvgh** [comment]
@jzp820927 
其实我一直想不通，墙对googleip的封锁已经到了“最后一英里”
封锁100-200万个ip，现在白天全世界可以连上的ip绝对不超过1万个
为什么它不索性用现在1%的资源，把剩下的ip也全部封光？

**Comment by Shell1688** [comment]
请问如何增加ip数量？以及如何导入ip...
谢谢！

**Comment by jzp820927** [comment]
可以在 web 界面操作

**Comment by Shell1688** [comment]
@jzp820927 我有个2.7.3版本的文件夹你，不知道里面哪个是ip文件，另外假如没有ip文件的话讲如何找ip来源？

**Comment by IsabellRoy** [comment]
@Shell1688 增加ip上限的话，在XX文件夹下的data/gae_proxy里新建manual.ini，然后在里面添加上：
```
[google_ip]
max_good_ip_num = 100000
```
后面的数字就是IP上限(/・ω・)/，默认3000，调太大其实没什么用...

IP来源可参考 #3721

**Comment by Shell1688** [comment]
@IsabellRoy 我是说状态下那个ip数量，我现在是200左右，这个好像会随着时间增长而增长是吗？另外扫描IP线程数30和50有什么区别？
thx！

**Comment by IsabellRoy** [comment]
@Shell1688 会随着时间增加的，扫描线程越大扫到可用IP的速度也越快，不过线程开太大可能会导致性能比较差的路由器当掉（我们家只要线程开50以上其他设备就全连不上WiFi），电脑也可能会卡

**Comment by Shell1688** [comment]
@IsabellRoy 电脑真的会卡如果有开音箱还会有电流声，记得以前289的时候也是50的都没有这种情况，不过跑顺了之后就几乎没有出现这个情况了，如果再有就降个30试试，谢谢你！

**Comment by Shell1688** [comment]
@IsabellRoy  请教下，我把桌面那个X图标的快捷方式删了，请问如何重建？

**Comment by IsabellRoy** [comment]
@Shell1688 运行XX-Net\code\default\launcher\create_shortcut.js

**Comment by hzj-777** [comment]
我的3.2.1ip数量从7000多掉到3000，升级到3.2.4，ip只有300多，这还是扫描了一天的结果

**Comment by Shell1688** [comment]
@IsabellRoy  不知道为什么这个桌面图标不能固定到到开始屏幕也不能固定到任务栏，记得以前的版本是可以的，系统是win10

**Comment by Shell1688** [comment]
@hzj-777 不要急，挂一两天就会增加。

**Comment by IsabellRoy** [comment]
@Shell1688 这个就不太清楚惹(;''∀'')，win8也不能固定
