### ISSUE TITLE
几点注意事项

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3747]
1:关于自动更新，更新完后，请重启一下xx-net，然后请到 web页面/系统/配置/升级管理里面，设置自动更新到稳定版。当然，愿意为开发者测试的，可以选择测试版

2:最大ip数已经从9000降到了3000，这个数字是根据最近的ip状况计算出来的，也是为了避免资源浪费

3:如果延时超过500ms，或者速度变慢，请到web页面 /GAEPROXY/高级/检查所有ip，检查完后速度会恢复的。另（ip数量多并不等于速度快，那些出问题的很大一部分是因为ip过多，还是建议让程序自动扫，不建议导入一大批ip）

最后一个建议，如果你的xx-net出问题了，请先删除data文件夹，重新配置一下看能不能恢复，不能的话，再来提问，谢谢！

**Comment by jzp820927** [comment]
句句见血，牛逼。
