### ISSUE TITLE
求指教: Mac点开XX-net不出现图标

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#3751]
点击Start运行终端启动起来一个火箭小图标, 右上角没有X图标.
## 我的终端用户怎么变成:-bash-3.2$ , 怎么切换回来, 求指教

Last login: Wed Jun 29 22:48:43 on ttys000
-bash: /etc/profile: Permission denied
-bash-3.2$ /Users/AbrahamLee/Documents/XX-Net-3.1.19/start ; exit;
Python 2.7.10
XX-Net version:default

**Comment by andylee1890** [comment]
问题已经得到解决
/etc/profile: Permission denied

看到这句话感觉好像是没有权限,
我就试了一下, 切换到root 权限下, 命令 chmod 775 /etc/profile, 然后就好了, XX-net也能正常启动了

**Comment by andylee1890** [comment]
问题已经得到解决
/etc/profile: Permission denied

看到这句话感觉好像是没有权限,
我就试了一下, 切换到root 权限下, 命令 chmod 775 /etc/profile, 然后就好了, XX-net也能正常启动了

**Comment by jzp820927** [comment]
english 学到好，就是不一样

**Comment by andylee1890** [comment]
感谢这个项目, 有机会的话我也愿用闲暇时间为这个项目贡献代码

**Comment by yeahwu** [comment]
欢迎，欢迎！
AbrahamLee <notifications@github.com>于2016年7月1日 周五02:12写道：
