### ISSUE TITLE
广东电信只要一翻墙就断网，整治网络跟帖效果显著啊，有没有其他的墙友有类似的感受？

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#3759]
RT/

**Comment by fletchere** [comment]
翻墙的严冬就要来临了，我估计今晚是我第一次收听不了美国之音了。

**Comment by hcym** [comment]
美国之音和新华社都是傻逼才会看的

**Comment by fletchere** [comment]
@hcym 没办法呀，推荐几个不是傻逼看的，提前谢过！

**Comment by IsabellRoy** [comment]
广东是因为抗议事件层出不穷才会封得那么严吧，内蒙古人民表示天高皇帝远，清晨的时候看4K视频都没问题...而且这边抗议事件基本都在牧区，即使传进市里也成不了气候，蒙古族比例太少了，汉人完全事不关己，还有幸灾乐祸的，不像在其他地方动辄就是几万人为了共同目标上街(;・∀・)

**Comment by fletchere** [comment]
又好了。
