### ISSUE TITLE
对于CPU 突然高占用问题的数据提供

### ISSUE THREAD

**Issue by cnccn** [XX-net/XX-Net#376]
平台：Mac OS X 10.10 
首先谢谢作者，在这个作品开发之前，goagent在Mac上基本用不了
但是还是有些小问题，例如CPU占用突然提高，风扇狂转
因此我参考https://github.com/XX-net/XX-Net/issues/35 
这里面的设置方法，导出了相关数据，希望可以对解决这个问题提供一定的帮助

另外，出现该问题后，如果重启程序，或者 Reload Goagent 可以暂时解决
以下为第一次

 1766 function calls (1760 primitive calls) in 157.443 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.000    0.000    0.000    0.000 SocketServer.py:206(__init__)
        3    0.000    0.000    0.001    0.000 SocketServer.py:413(__init__)
        3    0.000    0.000    0.001    0.000 SocketServer.py:422(server_bind)
        3    0.000    0.000    0.000    0.000 SocketServer.py:433(server_activate)
        1    0.000    0.000    0.000    0.000 cert_util.py:194(get_cert_serial_number)
        1    0.000    0.000    0.019    0.019 cert_util.py:471(import_mac_ca)
        1    0.000    0.000    0.019    0.019 cert_util.py:476(get_exist_ca_sha1)
        1    0.000    0.000    0.019    0.019 cert_util.py:501(import_ca)
        1    0.000    0.000    0.021    0.021 cert_util.py:514(init_ca)
        1    0.000    0.000    0.000    0.000 config.py:130(info)
        2    0.000    0.000    0.000    0.000 fnmatch.py:45(filter)
        2    0.000    0.000    0.000    0.000 fnmatch.py:81(translate)
        1    0.000    0.000    0.000    0.000 gae_handler.py:63(spawn_later)
        2    0.000    0.000    0.000    0.000 genericpath.py:15(exists)
        1    0.000    0.000    0.000    0.000 genericpath.py:85(_splitext)
        2    0.000    0.000    0.001    0.000 glob.py:18(glob)
       71    0.000    0.000    0.001    0.000 glob.py:29(iglob)
        2    0.000    0.000    0.001    0.000 glob.py:66(glob1)
       70    0.000    0.000    0.000    0.000 glob.py:77(<lambda>)
        6    0.000    0.000    0.000    0.000 glob.py:94(has_magic)
        2    0.000    0.000    0.000    0.000 logging.py:51(<lambda>)
        1    0.000    0.000    0.000    0.000 logging.py:58(basicConfig)
        1    0.000    0.000    0.000    0.000 logging.py:63(log)
        1    0.000    0.000    0.000    0.000 logging.py:94(info)
        1    0.000    0.000    0.000    0.000 posixpath.py:104(splitext)
        1    0.000    0.000    0.000    0.000 posixpath.py:119(basename)
        1    0.000    0.000    0.000    0.000 posixpath.py:127(dirname)
        1    0.000    0.000    0.000    0.000 posixpath.py:139(islink)
        2    0.000    0.000    0.000    0.000 posixpath.py:321(normpath)
        2    0.000    0.000    0.000    0.000 posixpath.py:350(abspath)
        2    0.000    0.000    0.000    0.000 posixpath.py:51(normcase)
        2    0.000    0.000    0.000    0.000 posixpath.py:59(isabs)
       69    0.000    0.000    0.000    0.000 posixpath.py:68(join)
        2    0.000    0.000    0.000    0.000 posixpath.py:89(split)
        1    0.000    0.000    0.001    0.001 proxy.py:126(pre_start)
        1    0.000    0.000    0.000    0.000 random.py:271(choice)
        2    0.000    0.000    0.000    0.000 re.py:188(compile)
        9    0.000    0.000    0.000    0.000 re.py:204(escape)
        2    0.000    0.000    0.000    0.000 re.py:226(_compile)
        3    0.000    0.000    0.000    0.000 socket.py:185(__init__)
       12    0.000    0.000    0.001    0.000 socket.py:223(meth)
      4/2    0.000    0.000    0.000    0.000 sre_compile.py:32(_compile)
        2    0.000    0.000    0.000    0.000 sre_compile.py:354(_simple)
        2    0.000    0.000    0.000    0.000 sre_compile.py:359(_compile_info)
        4    0.000    0.000    0.000    0.000 sre_compile.py:472(isstring)
        2    0.000    0.000    0.000    0.000 sre_compile.py:478(_code)
        2    0.000    0.000    0.000    0.000 sre_compile.py:493(compile)
        8    0.000    0.000    0.000    0.000 sre_parse.py:126(__len__)
       12    0.000    0.000    0.000    0.000 sre_parse.py:130(__getitem__)
        2    0.000    0.000    0.000    0.000 sre_parse.py:134(__setitem__)
       13    0.000    0.000    0.000    0.000 sre_parse.py:138(append)
      6/4    0.000    0.000    0.000    0.000 sre_parse.py:140(getwidth)
        2    0.000    0.000    0.000    0.000 sre_parse.py:178(__init__)
       31    0.000    0.000    0.000    0.000 sre_parse.py:182(__next)
       14    0.000    0.000    0.000    0.000 sre_parse.py:195(match)
       27    0.000    0.000    0.000    0.000 sre_parse.py:201(get)
        5    0.000    0.000    0.000    0.000 sre_parse.py:257(_escape)
        2    0.000    0.000    0.000    0.000 sre_parse.py:301(_parse_sub)
        2    0.000    0.000    0.000    0.000 sre_parse.py:379(_parse)
        2    0.000    0.000    0.000    0.000 sre_parse.py:67(__init__)
        2    0.000    0.000    0.000    0.000 sre_parse.py:675(parse)
        4    0.000    0.000    0.000    0.000 sre_parse.py:90(__init__)
        1    0.000    0.000    0.000    0.000 stat.py:24(S_IFMT)
        1    0.000    0.000    0.000    0.000 stat.py:55(S_ISLNK)
        1    0.000    0.000    0.000    0.000 subprocess.py:1098(_get_handles)
        4    0.000    0.000    0.000    0.000 subprocess.py:1147(_set_cloexec_flag)
        2    0.000    0.000    0.000    0.000 subprocess.py:1160(pipe_cloexec)
        1    0.000    0.000    0.003    0.003 subprocess.py:1186(_execute_child)
        1    0.000    0.000    0.000    0.000 subprocess.py:1207(_close_in_parent)
        1    0.000    0.000    0.000    0.000 subprocess.py:1329(_handle_exitstatus)
        2    0.000    0.000    0.000    0.000 subprocess.py:1343(_internal_poll)
        1    0.000    0.000    0.000    0.000 subprocess.py:1370(wait)
        1    0.000    0.000    0.000    0.000 subprocess.py:458(_cleanup)
        3    0.000    0.000    0.017    0.006 subprocess.py:473(_eintr_retry_call)
        1    0.000    0.000    0.019    0.019 subprocess.py:544(check_output)
        1    0.000    0.000    0.003    0.003 subprocess.py:648(__init__)
        1    0.000    0.000    0.000    0.000 subprocess.py:753(__del__)
        1    0.000    0.000    0.015    0.015 subprocess.py:767(communicate)
        1    0.000    0.000    0.000    0.000 subprocess.py:801(poll)
        3    0.000    0.000    0.000    0.000 threading.py:1008(daemon)
        3    0.000    0.000    0.000    0.000 threading.py:1024(daemon)
        3    0.000    0.000    0.000    0.000 threading.py:1035(setDaemon)
        3    0.000    0.000    0.000    0.000 threading.py:1152(currentThread)
        9    0.000    0.000    0.000    0.000 threading.py:241(Condition)
        9    0.000    0.000    0.000    0.000 threading.py:259(__init__)
        3    0.000    0.000    0.000    0.000 threading.py:293(_release_save)
        3    0.000    0.000    0.000    0.000 threading.py:296(_acquire_restore)
        3    0.000    0.000    0.000    0.000 threading.py:299(_is_owned)
        3    0.000    0.000    0.000    0.000 threading.py:308(wait)
        6    0.000    0.000    0.000    0.000 threading.py:541(Event)
        6    0.000    0.000    0.000    0.000 threading.py:560(__init__)
        6    0.000    0.000    0.000    0.000 threading.py:569(isSet)
       18    0.000    0.000    0.000    0.000 threading.py:58(__init__)
        3    0.000    0.000    0.000    0.000 threading.py:602(wait)
        3    0.000    0.000    0.000    0.000 threading.py:627(_newname)
        6    0.000    0.000    0.000    0.000 threading.py:63(_note)
        3    0.000    0.000    0.000    0.000 threading.py:656(__init__)
        3    0.000    0.000    0.000    0.000 threading.py:709(_set_daemon)
        3    0.000    0.000    0.000    0.000 threading.py:726(start)
        2    0.000    0.000    0.000    0.000 urllib2.py:1104(__init__)
        1    0.000    0.000    0.000    0.000 urllib2.py:312(__init__)
        9    0.000    0.000    0.000    0.000 urllib2.py:323(add_handler)
        1    0.000    0.000    0.000    0.000 urllib2.py:454(build_opener)
       10    0.000    0.000    0.000    0.000 urllib2.py:464(isclass)
        8    0.000    0.000    0.000    0.000 urllib2.py:496(add_parent)
       13    0.000    0.000    0.000    0.000 urllib2.py:503(__lt__)
        1    0.000    0.000    0.000    0.000 urllib2.py:714(__init__)
        2    0.000    0.000    0.000    0.000 {OpenSSL.crypto.load_certificate}
        1    0.000    0.000    0.000    0.000 {__import__}
        8    0.000    0.000    0.000    0.000 {_bisect.insort}
        1    0.000    0.000    0.000    0.000 {_hashlib.openssl_md5}
        2    0.000    0.000    0.000    0.000 {_sre.compile}
        9    0.000    0.000    0.000    0.000 {dir}
        8    0.000    0.000    0.000    0.000 {fcntl.fcntl}
        1    0.000    0.000    0.000    0.000 {filter}
        1    0.000    0.000    0.000    0.000 {gc.disable}
        1    0.000    0.000    0.000    0.000 {gc.enable}
        1    0.000    0.000    0.000    0.000 {gc.isenabled}
       31    0.000    0.000    0.000    0.000 {getattr}
       24    0.000    0.000    0.000    0.000 {hasattr}
       43    0.000    0.000    0.000    0.000 {isinstance}
    96/94    0.000    0.000    0.000    0.000 {len}
       16    0.000    0.000    0.000    0.000 {method 'acquire' of 'thread.lock' objects}
        1    0.000    0.000    0.000    0.000 {method 'add' of 'set' objects}
      169    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        3    0.000    0.000    0.000    0.000 {method 'bind' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'close' of 'file' objects}
        1    0.000    0.000    0.000    0.000 {method 'count' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'digest' of 'X509' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'encode' of 'str' objects}
       69    0.000    0.000    0.000    0.000 {method 'endswith' of 'str' objects}
        2    0.000    0.000    0.000    0.000 {method 'extend' of 'list' objects}
       90    0.000    0.000    0.000    0.000 {method 'find' of 'str' objects}
       18    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 {method 'get_serial_number' of 'X509' objects}
        3    0.000    0.000    0.000    0.000 {method 'getsockname' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
        3    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
       12    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
        3    0.000    0.000    0.000    0.000 {method 'listen' of '_socket.socket' objects}
       83    0.000    0.000    0.000    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
        1    0.000    0.000    0.000    0.000 {method 'random' of '_random.Random' objects}
        3    0.016    0.005    0.016    0.005 {method 'read' of 'file' objects}
        7    0.000    0.000    0.000    0.000 {method 'release' of 'thread.lock' objects}
        1    0.000    0.000    0.000    0.000 {method 'remove' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'remove' of 'set' objects}
        1    0.000    0.000    0.000    0.000 {method 'replace' of 'str' objects}
        6    0.000    0.000    0.000    0.000 {method 'rfind' of 'str' objects}
        3    0.000    0.000    0.000    0.000 {method 'rstrip' of 'str' objects}
        6    0.000    0.000    0.000    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
       14    0.000    0.000    0.000    0.000 {method 'setdefault' of 'dict' objects}
        3    0.000    0.000    0.000    0.000 {method 'setsockopt' of '_socket.socket' objects}
        2    0.000    0.000    0.000    0.000 {method 'split' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'splitlines' of 'str' objects}
      161    0.000    0.000    0.000    0.000 {method 'startswith' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'update' of 'set' objects}
        3    0.000    0.000    0.000    0.000 {method 'write' of 'file' objects}
        8    0.000    0.000    0.000    0.000 {min}
        2    0.000    0.000    0.000    0.000 {open}
        9    0.000    0.000    0.000    0.000 {ord}
        1    0.000    0.000    0.000    0.000 {posix.WEXITSTATUS}
        1    0.000    0.000    0.000    0.000 {posix.WIFEXITED}
        1    0.000    0.000    0.000    0.000 {posix.WIFSIGNALED}
        1    0.000    0.000    0.000    0.000 {posix.chdir}
        3    0.000    0.000    0.000    0.000 {posix.close}
        1    0.000    0.000    0.000    0.000 {posix.fdopen}
        1    0.001    0.001    0.001    0.001 {posix.fork}
        2    0.000    0.000    0.000    0.000 {posix.listdir}
        1    0.000    0.000    0.000    0.000 {posix.lstat}
        2    0.000    0.000    0.000    0.000 {posix.pipe}
        1    0.002    0.002    0.002    0.002 {posix.read}
        2    0.000    0.000    0.000    0.000 {posix.stat}
        1    0.000    0.000    0.000    0.000 {posix.waitpid}
        1    0.000    0.000    0.000    0.000 {resource.setrlimit}
       18    0.000    0.000    0.000    0.000 {setattr}
       12    0.000    0.000    0.000    0.000 {thread.allocate_lock}
        3    0.000    0.000    0.000    0.000 {thread.get_ident}
        4    0.000    0.000    0.000    0.000 {thread.start_new_thread}
        1    0.000    0.000    0.000    0.000 {time.ctime}
      157  157.419    1.003  157.419    1.003 {time.sleep}

**Comment by cnccn** [comment]
以下为第二次
2363 function calls (2357 primitive calls) in 756.209 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.000    0.000    0.000    0.000 SocketServer.py:206(__init__)
        3    0.000    0.000    0.001    0.000 SocketServer.py:413(__init__)
        3    0.000    0.000    0.001    0.000 SocketServer.py:422(server_bind)
        3    0.000    0.000    0.000    0.000 SocketServer.py:433(server_activate)
        1    0.000    0.000    0.000    0.000 cert_util.py:194(get_cert_serial_number)
        1    0.000    0.000    0.018    0.018 cert_util.py:471(import_mac_ca)
        1    0.000    0.000    0.018    0.018 cert_util.py:476(get_exist_ca_sha1)
        1    0.000    0.000    0.018    0.018 cert_util.py:501(import_ca)
        1    0.000    0.000    0.020    0.020 cert_util.py:514(init_ca)
        1    0.000    0.000    0.000    0.000 config.py:130(info)
        2    0.000    0.000    0.000    0.000 fnmatch.py:45(filter)
        2    0.000    0.000    0.000    0.000 fnmatch.py:81(translate)
        1    0.000    0.000    0.000    0.000 gae_handler.py:63(spawn_later)
        2    0.000    0.000    0.000    0.000 genericpath.py:15(exists)
        1    0.000    0.000    0.000    0.000 genericpath.py:85(_splitext)
        2    0.000    0.000    0.001    0.000 glob.py:18(glob)
       71    0.000    0.000    0.001    0.000 glob.py:29(iglob)
        2    0.000    0.000    0.001    0.000 glob.py:66(glob1)
       70    0.000    0.000    0.000    0.000 glob.py:77(<lambda>)
        6    0.000    0.000    0.000    0.000 glob.py:94(has_magic)
        2    0.000    0.000    0.000    0.000 logging.py:51(<lambda>)
        1    0.000    0.000    0.000    0.000 logging.py:58(basicConfig)
        1    0.000    0.000    0.000    0.000 logging.py:63(log)
        1    0.000    0.000    0.000    0.000 logging.py:94(info)
        1    0.000    0.000    0.000    0.000 posixpath.py:104(splitext)
        1    0.000    0.000    0.000    0.000 posixpath.py:119(basename)
        1    0.000    0.000    0.000    0.000 posixpath.py:127(dirname)
        1    0.000    0.000    0.000    0.000 posixpath.py:139(islink)
        2    0.000    0.000    0.000    0.000 posixpath.py:321(normpath)
        2    0.000    0.000    0.000    0.000 posixpath.py:350(abspath)
        2    0.000    0.000    0.000    0.000 posixpath.py:51(normcase)
        2    0.000    0.000    0.000    0.000 posixpath.py:59(isabs)
       69    0.000    0.000    0.000    0.000 posixpath.py:68(join)
        2    0.000    0.000    0.000    0.000 posixpath.py:89(split)
        1    0.000    0.000    0.001    0.001 proxy.py:126(pre_start)
        1    0.000    0.000    0.000    0.000 random.py:271(choice)
        2    0.000    0.000    0.000    0.000 re.py:188(compile)
        9    0.000    0.000    0.000    0.000 re.py:204(escape)
        2    0.000    0.000    0.000    0.000 re.py:226(_compile)
        3    0.000    0.000    0.000    0.000 socket.py:185(__init__)
       12    0.000    0.000    0.001    0.000 socket.py:223(meth)
      4/2    0.000    0.000    0.000    0.000 sre_compile.py:32(_compile)
        2    0.000    0.000    0.000    0.000 sre_compile.py:354(_simple)
        2    0.000    0.000    0.000    0.000 sre_compile.py:359(_compile_info)
        4    0.000    0.000    0.000    0.000 sre_compile.py:472(isstring)
        2    0.000    0.000    0.000    0.000 sre_compile.py:478(_code)
        2    0.000    0.000    0.000    0.000 sre_compile.py:493(compile)
        8    0.000    0.000    0.000    0.000 sre_parse.py:126(__len__)
       12    0.000    0.000    0.000    0.000 sre_parse.py:130(__getitem__)
        2    0.000    0.000    0.000    0.000 sre_parse.py:134(__setitem__)
       13    0.000    0.000    0.000    0.000 sre_parse.py:138(append)
      6/4    0.000    0.000    0.000    0.000 sre_parse.py:140(getwidth)
        2    0.000    0.000    0.000    0.000 sre_parse.py:178(__init__)
       31    0.000    0.000    0.000    0.000 sre_parse.py:182(__next)
       14    0.000    0.000    0.000    0.000 sre_parse.py:195(match)
       27    0.000    0.000    0.000    0.000 sre_parse.py:201(get)
        5    0.000    0.000    0.000    0.000 sre_parse.py:257(_escape)
        2    0.000    0.000    0.000    0.000 sre_parse.py:301(_parse_sub)
        2    0.000    0.000    0.000    0.000 sre_parse.py:379(_parse)
        2    0.000    0.000    0.000    0.000 sre_parse.py:67(__init__)
        2    0.000    0.000    0.000    0.000 sre_parse.py:675(parse)
        4    0.000    0.000    0.000    0.000 sre_parse.py:90(__init__)
        1    0.000    0.000    0.000    0.000 stat.py:24(S_IFMT)
        1    0.000    0.000    0.000    0.000 stat.py:55(S_ISLNK)
        1    0.000    0.000    0.000    0.000 subprocess.py:1098(_get_handles)
        4    0.000    0.000    0.000    0.000 subprocess.py:1147(_set_cloexec_flag)
        2    0.000    0.000    0.000    0.000 subprocess.py:1160(pipe_cloexec)
        1    0.000    0.000    0.003    0.003 subprocess.py:1186(_execute_child)
        1    0.000    0.000    0.000    0.000 subprocess.py:1207(_close_in_parent)
        1    0.000    0.000    0.000    0.000 subprocess.py:1329(_handle_exitstatus)
        2    0.000    0.000    0.000    0.000 subprocess.py:1343(_internal_poll)
        1    0.000    0.000    0.000    0.000 subprocess.py:1370(wait)
        1    0.000    0.000    0.000    0.000 subprocess.py:458(_cleanup)
        3    0.000    0.000    0.016    0.005 subprocess.py:473(_eintr_retry_call)
        1    0.000    0.000    0.018    0.018 subprocess.py:544(check_output)
        1    0.000    0.000    0.003    0.003 subprocess.py:648(__init__)
        1    0.000    0.000    0.000    0.000 subprocess.py:753(__del__)
        1    0.000    0.000    0.014    0.014 subprocess.py:767(communicate)
        1    0.000    0.000    0.000    0.000 subprocess.py:801(poll)
        3    0.000    0.000    0.000    0.000 threading.py:1008(daemon)
        3    0.000    0.000    0.000    0.000 threading.py:1024(daemon)
        3    0.000    0.000    0.000    0.000 threading.py:1035(setDaemon)
        3    0.000    0.000    0.000    0.000 threading.py:1152(currentThread)
        9    0.000    0.000    0.000    0.000 threading.py:241(Condition)
        9    0.000    0.000    0.000    0.000 threading.py:259(__init__)
        3    0.000    0.000    0.000    0.000 threading.py:293(_release_save)
        3    0.000    0.000    0.000    0.000 threading.py:296(_acquire_restore)
        3    0.000    0.000    0.000    0.000 threading.py:299(_is_owned)
        3    0.000    0.000    0.000    0.000 threading.py:308(wait)
        6    0.000    0.000    0.000    0.000 threading.py:541(Event)
        6    0.000    0.000    0.000    0.000 threading.py:560(__init__)
        6    0.000    0.000    0.000    0.000 threading.py:569(isSet)
       18    0.000    0.000    0.000    0.000 threading.py:58(__init__)
        3    0.000    0.000    0.000    0.000 threading.py:602(wait)
        3    0.000    0.000    0.000    0.000 threading.py:627(_newname)
        6    0.000    0.000    0.000    0.000 threading.py:63(_note)
        3    0.000    0.000    0.000    0.000 threading.py:656(__init__)
        3    0.000    0.000    0.000    0.000 threading.py:709(_set_daemon)
        3    0.000    0.000    0.000    0.000 threading.py:726(start)
        2    0.000    0.000    0.000    0.000 urllib2.py:1104(__init__)
        1    0.000    0.000    0.000    0.000 urllib2.py:312(__init__)
        9    0.000    0.000    0.000    0.000 urllib2.py:323(add_handler)
        1    0.000    0.000    0.000    0.000 urllib2.py:454(build_opener)
       10    0.000    0.000    0.000    0.000 urllib2.py:464(isclass)
        8    0.000    0.000    0.000    0.000 urllib2.py:496(add_parent)
       13    0.000    0.000    0.000    0.000 urllib2.py:503(__lt__)
        1    0.000    0.000    0.000    0.000 urllib2.py:714(__init__)
        2    0.000    0.000    0.000    0.000 {OpenSSL.crypto.load_certificate}
        1    0.000    0.000    0.000    0.000 {__import__}
        8    0.000    0.000    0.000    0.000 {_bisect.insort}
        1    0.000    0.000    0.000    0.000 {_hashlib.openssl_md5}
        2    0.000    0.000    0.000    0.000 {_sre.compile}
        9    0.000    0.000    0.000    0.000 {dir}
        8    0.000    0.000    0.000    0.000 {fcntl.fcntl}
        1    0.000    0.000    0.000    0.000 {filter}
        1    0.000    0.000    0.000    0.000 {gc.disable}
        1    0.000    0.000    0.000    0.000 {gc.enable}
        1    0.000    0.000    0.000    0.000 {gc.isenabled}
       31    0.000    0.000    0.000    0.000 {getattr}
       24    0.000    0.000    0.000    0.000 {hasattr}
       43    0.000    0.000    0.000    0.000 {isinstance}
    96/94    0.000    0.000    0.000    0.000 {len}
       16    0.000    0.000    0.000    0.000 {method 'acquire' of 'thread.lock' objects}
        1    0.000    0.000    0.000    0.000 {method 'add' of 'set' objects}
      169    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        3    0.000    0.000    0.000    0.000 {method 'bind' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'close' of 'file' objects}
        1    0.000    0.000    0.000    0.000 {method 'count' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'digest' of 'X509' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'encode' of 'str' objects}
       69    0.000    0.000    0.000    0.000 {method 'endswith' of 'str' objects}
        2    0.000    0.000    0.000    0.000 {method 'extend' of 'list' objects}
       90    0.000    0.000    0.000    0.000 {method 'find' of 'str' objects}
       18    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 {method 'get_serial_number' of 'X509' objects}
        3    0.000    0.000    0.000    0.000 {method 'getsockname' of '_socket.socket' objects}
        1    0.000    0.000    0.000    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
        3    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
       12    0.000    0.000    0.000    0.000 {method 'join' of 'str' objects}
        3    0.000    0.000    0.000    0.000 {method 'listen' of '_socket.socket' objects}
       83    0.000    0.000    0.000    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
        1    0.000    0.000    0.000    0.000 {method 'random' of '_random.Random' objects}
        3    0.015    0.005    0.015    0.005 {method 'read' of 'file' objects}
        7    0.000    0.000    0.000    0.000 {method 'release' of 'thread.lock' objects}
        1    0.000    0.000    0.000    0.000 {method 'remove' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'remove' of 'set' objects}
        1    0.000    0.000    0.000    0.000 {method 'replace' of 'str' objects}
        6    0.000    0.000    0.000    0.000 {method 'rfind' of 'str' objects}
        3    0.000    0.000    0.000    0.000 {method 'rstrip' of 'str' objects}
        6    0.000    0.000    0.000    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
       14    0.000    0.000    0.000    0.000 {method 'setdefault' of 'dict' objects}
        3    0.000    0.000    0.000    0.000 {method 'setsockopt' of '_socket.socket' objects}
        2    0.000    0.000    0.000    0.000 {method 'split' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'splitlines' of 'str' objects}
      161    0.000    0.000    0.000    0.000 {method 'startswith' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {method 'update' of 'set' objects}
        3    0.000    0.000    0.000    0.000 {method 'write' of 'file' objects}
        8    0.000    0.000    0.000    0.000 {min}
        2    0.000    0.000    0.000    0.000 {open}
        9    0.000    0.000    0.000    0.000 {ord}
        1    0.000    0.000    0.000    0.000 {posix.WEXITSTATUS}
        1    0.000    0.000    0.000    0.000 {posix.WIFEXITED}
        1    0.000    0.000    0.000    0.000 {posix.WIFSIGNALED}
        1    0.000    0.000    0.000    0.000 {posix.chdir}
        3    0.000    0.000    0.000    0.000 {posix.close}
        1    0.000    0.000    0.000    0.000 {posix.fdopen}
        1    0.000    0.000    0.000    0.000 {posix.fork}
        2    0.000    0.000    0.000    0.000 {posix.listdir}
        1    0.000    0.000    0.000    0.000 {posix.lstat}
        2    0.000    0.000    0.000    0.000 {posix.pipe}
        1    0.002    0.002    0.002    0.002 {posix.read}
        2    0.000    0.000    0.000    0.000 {posix.stat}
        1    0.000    0.000    0.000    0.000 {posix.waitpid}
        1    0.000    0.000    0.000    0.000 {resource.setrlimit}
       18    0.000    0.000    0.000    0.000 {setattr}
       12    0.000    0.000    0.000    0.000 {thread.allocate_lock}
        3    0.000    0.000    0.000    0.000 {thread.get_ident}
        4    0.000    0.000    0.000    0.000 {thread.start_new_thread}
        1    0.000    0.000    0.000    0.000 {time.ctime}
      754  756.186    1.003  756.186    1.003 {time.sleep}

**Comment by zhangkaifei** [comment]
也遇到同样问题，mac book 15  os 10.10.2 cpu用一阵CPU占用极高，需要强制关掉后再打开，会反复出现

**Comment by ye-cao** [comment]
windows平台也会出现CPU占用高情况，希望作者仔细检查一下

**Comment by PaulUlrik** [comment]
嗯。本人Windows10预览版，用的是最新的1.14.1，昨天偶然发现CPU还是占用很高，而且是关掉了chrome蛮久的情况下。

**Comment by yanton** [comment]
我也是昨天发现的这个问题，win8.1

**Comment by cnccn** [comment]
如果页面中图片较多且均通过代理，容易重现这个问题，作者可以试试看

**Comment by xxnet** [comment]
恩，发了新版 1.14.2，把可能导致CPU高的地方梳理了一遍，希望能解决问题。

请大家升级，在SYSTEM的设置中，检查更新，然后点击更新。
可能会没有反应，等几分钟会自动升级。

等不及也可以自己下载新版。
1.14.2会显示下载进度了。

在 2015年5月10日 上午8:34，cnccn <notifications@github.com>写道：

**Comment by g8up** [comment]
我目前在 Mac 上使用的是 xx-net v3.8.7，启动后也是风扇狂转，发热。
我还以为是电脑的问题，退出 xx-net 后，电脑就冷／静下来了。

**Comment by xxnet** [comment]
用top 看​CPU 消耗有多少？
5%以下才正常的

**Comment by g8up** [comment]
重启了一次 xx-net 后，不再影响风扇，一切正常。
补充说明：
我是在一台新 MAC 上使用 xx-net，安装后电脑一直没有关机过（也没有重启xx-net），不用了就直接合上盖子。
我通过 Mac 里的工具看过一次，XX-net 的 CPU 占用最高，还有一列显示的线程，貌似达到190多。

**Comment by g8up** [comment]
补充：
我使用 Mac 经常直接合盖待机。唤醒后，风扇经常呼呼响。
观察活动监视器， python 进程 CPU 占用100%，线程300+。
退出 xx-net 发现恢复正常，另外，在图标菜单里点选一下`Reset Each Module`后也能恢复正常。
今天截了个图，供参考。
