### ISSUE TITLE
怎么把xx-net扫描到的ip转换为hosts

### ISSUE THREAD

**Issue by myfreeer** [XX-net/XX-Net#3762]
想自制hosts(自用)，不知有没有这种工具？

**Comment by riumiyama** [comment]
自己動手豐衣足食？

**Comment by jzp820927** [comment]
打开 记事本，替换，OK

**Comment by CHN008** [comment]
嘿嘿 我刚试过了 不成功

**Comment by yeahwu** [comment]
必需是gws ip
CHN008 <notifications@github.com>于2016年7月1日 周五02:51写道：

**Comment by myfreeer** [comment]
@yeahwu 意思是good_ip.txt中第三列为gws的ip可用于所有google域名？第二列的域名不用管吗？是否需要手动测试能否ping通？

**Comment by jzp820927** [comment]
看样子问题解决了？所以关闭 issues。
