### ISSUE TITLE
关于 #2507 的解决方案

### ISSUE THREAD

**Issue by funray** [XX-net/XX-Net#3767]
@yeahwu 
#2507 所反馈的问题，希望能应用我的方案(如下图)：

在`data/gae_proxy/proxy.pac`文件的顶部，将`blackhole`的值改为`PROXY 255.255.255.255`
这样会使其立即停止加载，而不是一直loading，例如这个[页面](http://www.ithome.com/html/win10/139519.htm)
![2016-07-01_155552](https://cloud.githubusercontent.com/assets/5118705/16515781/93b88682-3fa6-11e6-9c90-f473c03154cc.png)

**Comment by yeahwu** [comment]
由于用的是linux，一直没用过pac，还有这个文件是自动生成的吧！
@Cat7373 能复现吗？

**Comment by hcym** [comment]
mac吧

linux和win还是127.0.0.1比较好

**Comment by funray** [comment]
@yeahwu 
可以改生成规则呀，用其它方法也行，反正得解决。
经测试，生成规则不会覆盖所修改的部分。
话说，linux也是可以用pac的呀。

@hcym 
如果本机是Web服务器 也正好占用了80端口呢。
向`255.255.255.255`发送数据 是`广播`，若接收数据，应该是`黑洞`。

**Comment by hcym** [comment]
linux用过255.255.255.0一直loading一直转圈

可能有误，我再试试255.255.255.255

谢谢

**Comment by yeahwu** [comment]
俺这linux上用不了自带的pac，开了pac也生成不了proxy.pac文件
@Cat7373 帮忙改一下pac_server.py文件，
```
pac_listen = "255.255.255.255"
```
测试一下
