### ISSUE TITLE
在梅林上安装XXNET一直显示扫描IP，十几个小时都没看到安装成功，求解惑

### ISSUE THREAD

**Issue by kangmya** [XX-net/XX-Net#3770]
![Uploading QQ截图20160701204319.png…]()
如图
截至发帖已经扫描4800个IP，用时12个多小时了，下面贴出命令

ASUSWRT-Merlin RT-AC68U 380.59-X6.6.1 Wed Jun  1 13:51:01 UTC 2016
kang_mk@RT-AC68P:/tmp/home/root# sh /tmp/install_xxnet.sh
 Info:  This script was created by ryzhov_al and TeHashX modified by wxing82
 Info:  Thanks @zyxmon & @ryzhov_al for New Generation Entware
 Info:  and @Rmerlin for his awesome firmwares
 Info:  This script will guide you through the Entware-NG
/tmp/install_xxnet.sh: line 19: XX-Net: not found
 Info:  Script modifies only "entware-ng" folder on the chosen drive,
 Info:  no other data will be touched. Existing installation will be
 Info:  replaced with this one. Also some start scripts will be installed,
 Info:  the old ones will be saved on partition where Entware-NG is installed
 Info:  like /tmp/mnt/sda1/jffs_scripts_backup.tgz

 Info:  Looking for available partitions...
[1] --> /tmp/mnt/Download
 =>  Please enter partition number or 0 to exit
[0-1]: 1
 Info:  /tmp/mnt/Download selected.

 * Warning:  stopping running services...
/jffs/scripts/services-stop: line 3: /opt/etc/init.d/rc.unslung: not found
 Info:  Creating /tmp/mnt/Download/entware-ng.arm folder...
 * Warning:  Deleting old /tmp/opt symlink...
 Info:  Creating /tmp/opt symlink...
 Info:  Creating /jffs scripts backup...
tar: removing leading '/' from member names
 Info:  Modifying start scripts...
start to install entware-ng
--2016-07-01 10:08:19--  http://pkg.entware.net/binaries/armv7/installer/entware           _install.sh
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1564 (1.5K) [text/x-sh]
Saving to: 'STDOUT'

-                   100%[=====================>]   1.53K  --.-KB/s   in 0s

2016-07-01 10:08:21 (53.1 MB/s) - written to stdout [1564/1564]

Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Info: Opkg package manager deployment...
--2016-07-01 10:08:21--  http://pkg.entware.net/binaries/armv7/installer/opkg
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 127488 (125K) [text/plain]
Saving to: '/opt/bin/opkg'

/opt/bin/opkg       100%[=====================>] 124.50K  84.5KB/s   in 1.5s

2016-07-01 10:08:23 (84.5 KB/s) - '/opt/bin/opkg' saved [127488/127488]

--2016-07-01 10:08:23--  http://pkg.entware.net/binaries/armv7/installer/opkg.co           nf
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 142 [text/plain]
Saving to: '/opt/etc/opkg.conf'

/opt/etc/opkg.conf  100%[=====================>]     142  --.-KB/s   in 0s

2016-07-01 10:08:24 (5.39 MB/s) - '/opt/etc/opkg.conf' saved [142/142]

--2016-07-01 10:08:24--  http://pkg.entware.net/binaries/armv7/installer/ld-2.23           .so
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 142752 (139K) [text/plain]
Saving to: '/opt/lib/ld-2.23.so'

/opt/lib/ld-2.23.so 100%[=====================>] 139.41K  81.6KB/s   in 1.7s

2016-07-01 10:08:27 (81.6 KB/s) - '/opt/lib/ld-2.23.so' saved [142752/142752]

--2016-07-01 10:08:27--  http://pkg.entware.net/binaries/armv7/installer/libc-2.           23.so
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1227404 (1.2M) [text/plain]
Saving to: '/opt/lib/libc-2.23.so'

/opt/lib/libc-2.23. 100%[=====================>]   1.17M   302KB/s   in 4.0s

2016-07-01 10:08:31 (302 KB/s) - '/opt/lib/libc-2.23.so' saved [1227404/1227404]

--2016-07-01 10:08:31--  http://pkg.entware.net/binaries/armv7/installer/libgcc_           s.so.1.2.23
Resolving pkg.entware.net... 81.4.123.217
Connecting to pkg.entware.net|81.4.123.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39632 (39K) [text/plain]
Saving to: '/opt/lib/libgcc_s.so.1'

/opt/lib/libgcc_s.s 100%[=====================>]  38.70K  53.3KB/s   in 0.7s

2016-07-01 10:08:33 (53.3 KB/s) - '/opt/lib/libgcc_s.so.1' saved [39632/39632]

Info: Basic packages installation...
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/packages.
Installing entware-opt (222108-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/entware-opt_222108-2_armv7soft           .ipk.
Installing libc (2.23-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/libc_2.23-4_armv7soft.ipk.
Installing libgcc (5.3.0-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/libgcc_5.3.0-4_armv7soft.ipk.
Installing libssp (5.3.0-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/libssp_5.3.0-4_armv7soft.ipk.
Installing librt (2.23-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/librt_2.23-4_armv7soft.ipk.
Installing libpthread (2.23-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/libpthread_2.23-4_armv7soft.ip           k.
Installing libstdcpp (5.3.0-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/libstdcpp_5.3.0-4_armv7soft.ip           k.
Installing ldconfig (2.23-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/ldconfig_2.23-4_armv7soft.ipk.
Installing findutils (4.6.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/findutils_4.6.0-1_armv7soft.ip           k.
Installing terminfo (6.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/terminfo_6.0-1_armv7soft.ipk.
Installing locales (2.23-4) to root...
Downloading http://pkg.entware.net/binaries/armv7/locales_2.23-4_armv7soft.ipk.
Configuring libgcc.
Configuring libc.
Configuring libssp.
Configuring libpthread.
Configuring librt.
Configuring terminfo.
Configuring ldconfig.
Configuring locales.
Entware uses separate locale-archive file independent from main system
Creating locale archive - /opt/usr/lib/locale/locale-archive
Adding en_EN.UTF-8
Adding ru_RU.UTF-8
You can download locale sources from http://pkg.entware.net/sources/i18n_glib223           .tar.gz
You can add new locales to Entware using /opt/bin/localedef.new
Configuring libstdcpp.
Configuring findutils.
Configuring entware-opt.
Updating /opt/etc/ld.so.cache... done.
Info: Congratulations!
Info: If there are no errors above then Entware-ng was successfully initialized.
Info: Add /opt/bin & /opt/sbin to your PATH variable
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware-ng se           rvices to start
Info: Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/iss           ues
Package terminfo (6.0-1) installed in root is up to date.
Router model
RT-AC68P
---------
SWAP FILE
---------
Choose swap file size (Highly Recommended)
1. 256MB
2. 512MB (recommended)
3. 1024MB
4. Skip this step, I already have a swap file / partition
   or I don't want to create one right now
Enter your choice [ 1 - 4 ] 4

Congratulations! If there are no errors above then Entware-NG is successfully in           itialized.

Found a Bug? Please report at https://github.com/Entware-ng/Entware-ng/issues

>>>>>>>>>>>>>>>>Now we will install XX-Net on your Router<<<<<<<<<<<<<<<<<

 Info:  install pyopenssl...
Installing python-pyopenssl (16.0.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-pyopenssl_16.0.0-1_armv           7soft.ipk.
Installing python-light (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-light_2.7.11-8_armv7sof           t.ipk.
Installing python-base (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-base_2.7.11-8_armv7soft           .ipk.
Installing zlib (1.2.8-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/zlib_1.2.8-1_armv7soft.ipk.
Installing libffi (3.0.13-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libffi_3.0.13-1_armv7soft.ipk.
Installing libbz2 (1.0.6-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/libbz2_1.0.6-2_armv7soft.ipk.
Installing python-cryptography (1.3.1-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-cryptography_1.3.1-1_ar           mv7soft.ipk.
Installing libopenssl (1.0.2h-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libopenssl_1.0.2h-1_armv7soft.           ipk.
Installing python (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python_2.7.11-8_armv7soft.ipk.
Installing python-ctypes (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-ctypes_2.7.11-8_armv7so           ft.ipk.
Installing python-pydoc (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-pydoc_2.7.11-8_armv7sof           t.ipk.
Installing python-multiprocessing (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-multiprocessing_2.7.11-           8_armv7soft.ipk.
Installing python-logging (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-logging_2.7.11-8_armv7s           oft.ipk.
Installing python-codecs (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-codecs_2.7.11-8_armv7so           ft.ipk.
Installing python-sqlite3 (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-sqlite3_2.7.11-8_armv7s           oft.ipk.
Installing libsqlite3 (3120200-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libsqlite3_3120200-1_armv7soft           .ipk.
Installing python-gdbm (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-gdbm_2.7.11-8_armv7soft           .ipk.
Installing libgdbm (1.11-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libgdbm_1.11-1_armv7soft.ipk.
Installing python-email (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-email_2.7.11-8_armv7sof           t.ipk.
Installing python-distutils (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-distutils_2.7.11-8_armv           7soft.ipk.
Installing python-xml (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-xml_2.7.11-8_armv7soft.           ipk.
Installing libexpat (2.1.0-3) to root...
Downloading http://pkg.entware.net/binaries/armv7/libexpat_2.1.0-3_armv7soft.ipk           .
Installing python-compiler (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-compiler_2.7.11-8_armv7           soft.ipk.
Installing python-db (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-db_2.7.11-8_armv7soft.i           pk.
Installing libdb47 (4.7.25.4.NC-5) to root...
Downloading http://pkg.entware.net/binaries/armv7/libdb47_4.7.25.4.NC-5_armv7sof           t.ipk.
Installing libxml2 (2.9.3-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libxml2_2.9.3-1_armv7soft.ipk.
Installing python-openssl (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-openssl_2.7.11-8_armv7s           oft.ipk.
Installing python-decimal (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-decimal_2.7.11-8_armv7s           oft.ipk.
Installing python-unittest (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-unittest_2.7.11-8_armv7           soft.ipk.
Installing python-ncurses (2.7.11-8) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-ncurses_2.7.11-8_armv7s           oft.ipk.
Installing libncurses (6.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/libncurses_6.0-1_armv7soft.ipk           .
Installing python-cffi (1.5.2-2) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-cffi_1.5.2-2_armv7soft.           ipk.
Installing python-pycparser (2.14-3) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-pycparser_2.14-3_armv7s           oft.ipk.
Installing python-ply (3.8-3) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-ply_3.8-3_armv7soft.ipk           .
Installing python-enum34 (1.1.2-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-enum34_1.1.2-1_armv7sof           t.ipk.
Installing python-idna (2.1-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-idna_2.1-1_armv7soft.ip           k.
Installing python-ipaddress (1.0.16-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-ipaddress_1.0.16-1_armv           7soft.ipk.
Installing python-pyasn1 (0.1.9-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-pyasn1_0.1.9-1_armv7sof           t.ipk.
Installing python-six (1.10.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-six_1.10.0-1_armv7soft.           ipk.
Installing python-setuptools (20.7.0-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/python-setuptools_20.7.0-1_arm           v7soft.ipk.
Installing ca-certificates (20160104) to root...
Downloading http://pkg.entware.net/binaries/armv7/ca-certificates_20160104_all.i           pk.
Configuring zlib.
Configuring python-base.
Configuring libffi.
Configuring libbz2.
Configuring python-light.
Configuring python-idna.
Configuring python-codecs.
Configuring libxml2.
Configuring libdb47.
Configuring python-db.
Configuring python-ply.
Configuring python-decimal.
Configuring python-six.
Configuring python-pyasn1.
Configuring python-distutils.
Configuring python-pydoc.
Configuring python-ctypes.
Configuring python-multiprocessing.
Configuring python-logging.
Configuring libsqlite3.
Configuring python-sqlite3.
Configuring libgdbm.
Configuring python-gdbm.
Configuring python-email.
Configuring libexpat.
Configuring python-xml.
Configuring python-compiler.
Configuring libopenssl.
Configuring python-openssl.
Configuring python-unittest.
Configuring libncurses.
Configuring python-ncurses.
Configuring python.
Configuring python-pycparser.
Configuring python-cffi.
Configuring ca-certificates.
Configuring python-setuptools.
Configuring python-enum34.
Configuring python-ipaddress.
Configuring python-cryptography.
Configuring python-pyopenssl.
 Info:  Download latest XX-Net...
--2016-07-01 10:11:24--  https://github.com/XX-net/XX-Net/archive/master.zip
Resolving github.com... 192.30.253.113
Connecting to github.com|192.30.253.113|:443... connected.
WARNING: cannot verify github.com's certificate, issued by '/C=US/O=DigiCert Inc           /OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/XX-net/XX-Net/zip/master [following]
--2016-07-01 10:11:26--  https://codeload.github.com/XX-net/XX-Net/zip/master
Resolving codeload.github.com... 192.30.253.120
Connecting to codeload.github.com|192.30.253.120|:443... connected.
WARNING: cannot verify codeload.github.com's certificate, issued by '/C=US/O=Dig           iCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 14274495 (14M) [application/zip]
Saving to: '/opt/tmp/master.zip'

/opt/tmp/master.zip 100%[=====================>]  13.61M   995KB/s   in 17s

2016-07-01 10:11:44 (818 KB/s) - '/opt/tmp/master.zip' saved [14274495/14274495]

 Info:  Installing the XX-Net...
 Info:  Installing Bash...
Installing bash (4.3.42-1a) to root...
Downloading http://pkg.entware.net/binaries/armv7/bash_4.3.42-1a_armv7soft.ipk.
Configuring bash.
 Info:  Try to run the XX-Net for testing...
Python 2.7.11
XX-Net version:default
Jul 01 02:12:06.477 - [INFO] use build-in openssl lib
Jul 01 02:12:08.505 - [INFO] start XX-Net 3.2.4
Jul 01 02:12:08.505 - [DEBUG] start confirm_xxnet_exit
Jul 01 02:12:08.514 - [DEBUG] good, xxnet:8087 cleared!
Jul 01 02:12:08.518 - [DEBUG] good, xxnet:8085 clear!
Jul 01 02:12:08.519 - [DEBUG] finished confirm_xxnet_exit
Jul 01 02:12:08.526 - [INFO] migrating to 3.x.x
Jul 01 02:12:09.932 - [INFO] SSL use version:TLSv1_2
Jul 01 02:12:09.935 - [INFO] OpenSSL support alpn
Jul 01 02:12:10.004 - [INFO] load ip range file:/tmp/mnt/Download/entware-ng.arm           /xxnet/code/default/gae_proxy/local/ip_range.txt
Jul 01 02:12:10.273 - [INFO] load google ip_list num:0, gws num:0
Jul 01 02:12:10.368 - [INFO] OpenSSL support alpn
Jul 01 02:12:10.365 - [DEBUG] network is ok, cost:990 ms
Jul 01 02:12:10.441 - [WARNING] no enough ip
Jul 01 02:12:10.545 - [DEBUG] ## GAEProxy set keep_running: True
Jul 01 02:12:10.548 - [INFO] ---------------------------------------------------           ---
Jul 01 02:12:10.548 - [INFO] Python Version     : 2.7.11
Jul 01 02:12:10.552 - [INFO] OS                 : Dist:; Version:; ID:
Jul 01 02:12:10.553 - [INFO] Listen Address     : 127.0.0.1:8087
Jul 01 02:12:10.553 - [INFO] GAE APPID          :
Jul 01 02:12:10.553 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pa           c
Jul 01 02:12:10.553 - [INFO] ---------------------------------------------------           ---
Jul 01 02:12:10.554 - [INFO] no CA file exist
Jul 01 02:12:10.554 - [INFO] clean old site certs
Jul 01 02:12:10.558 - [INFO] generate CA file:/tmp/mnt/Download/entware-ng.arm/x           xnet/data/gae_proxy/CA.crt
Jul 01 02:12:10.942 - [WARNING] no enough ip
Jul 01 02:12:11.443 - [WARNING] no enough ip
Jul 01 02:12:11.945 - [WARNING] no enough ip
Jul 01 02:12:12.446 - [WARNING] no enough ip
Jul 01 02:12:12.947 - [WARNING] no enough ip
Jul 01 02:12:13.455 - [WARNING] no enough ip
Jul 01 02:12:13.950 - [WARNING] no enough ip
Jul 01 02:12:14.455 - [WARNING] no enough ip
Jul 01 02:12:14.958 - [WARNING] no enough ip
Jul 01 02:12:15.459 - [WARNING] no enough ip
Jul 01 02:12:15.960 - [WARNING] no enough ip
Jul 01 02:12:16.465 - [WARNING] no enough ip
Jul 01 02:12:16.966 - [WARNING] no enough ip
Jul 01 02:12:17.468 - [WARNING] no enough ip
Jul 01 02:12:17.970 - [WARNING] no enough ip
Jul 01 02:12:18.471 - [WARNING] no enough ip
Jul 01 02:12:18.972 - [WARNING] no enough ip
Jul 01 02:12:19.475 - [WARNING] no enough ip
Jul 01 02:12:19.976 - [WARNING] no enough ip
Jul 01 02:12:24.800 - [INFO] create CA
Jul 01 02:12:24.804 - [INFO] server 127.0.0.1:8087 started.
Jul 01 02:12:24.806 - [INFO] server 127.0.0.1:8086 started.
Jul 01 02:12:24.897 - [INFO] module gae_proxy started
Jul 01 02:12:24.897 - [INFO] start gae_proxy time cost:16342 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Jul 01 02:12:25.136 - [INFO] use config_path:/tmp/mnt/Download/entware-ng.arm/xx           net/data/x_tunnel/client.json
Jul 01 02:12:25.137 - [INFO] Use proxy:127.0.0.1:8087
Jul 01 02:12:25.137 - [DEBUG] x-tunnel no account
Jul 01 02:12:25.138 - [WARNING] x-tunnel session not start
Jul 01 02:12:25.139 - [ERROR] bind to 127.0.0.1:1080 fail:error(98, 'Address alr           eady in use')
Exception in thread Thread-80:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/mnt/Download/entware-ng.arm/xxnet/code/default/x_tunnel/start.py",            line 19, in main
    client.main()
  File "/tmp/mnt/Download/entware-ng.arm/xxnet/code/default/x_tunnel/local/clien           t.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.conf           ig.socks_port), Socks5Server)
  File "/tmp/mnt/Download/entware-ng.arm/xxnet/code/default/python27/1.0/lib/noa           rch/simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "/tmp/mnt/Download/entware-ng.arm/xxnet/code/default/python27/1.0/lib/noa           rch/simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "/tmp/mnt/Download/entware-ng.arm/xxnet/code/default/python27/1.0/lib/noa           rch/simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(98, 'Address already in use')

Jul 01 02:12:37.627 - [INFO] scan_ip add ip:189.45.193.233 time:1060
Jul 01 02:12:42.898 - [INFO] scan_ip add ip:177.35.32.209 time:838
Jul 01 02:12:44.058 - [INFO] scan_ip add ip:113.171.252.205 time:523

再往下面全部都是扫描IP的记录，求高手解答一下这是什么问题，难道不是应该按照成功之后再去扫描IP吗

**Comment by kangmya** [comment]
![Uploading QQ截图20160701204319.png…]()
图片传不上？不过没关系，反正就是扫描IP的截图，和IP列表的截图

**Comment by jzp820927** [comment]
XX本来就是要一直扫描IP的，这是正常情况

**Comment by kangmya** [comment]
那不也应该是安装完成的时候才扫描的吗，怎么安装过程来扫描了，昨天已经扫了12个小时了，扫了5000个IP还没安装完成，就只能关机睡觉了？难道安装一次要这么久啊 。

**Comment by jzp820927** [comment]
XX 是不需要安装的，下载就可以直接运行，只要运行就会开始一直扫描IP

**Comment by kangmya** [comment]
我是安装在路由器上的

**Comment by jzp820927** [comment]
你可以后台运行，然后就不用管了。

**Comment by kangmya** [comment]
已经搞定了  是他脚本有问题   https://github.com/XX-net/XX-Net/wiki/在有USB接口的梅林固件路由器上安装XX-Net-（懒人脚本）
这个脚本有问题   他们自己不知道是没发现还是懒得改

**Comment by jzp820927** [comment]
在路由器上，直接手工运行  python start.py 命令还方便些，用脚本还不好找问题。

**Comment by sjdr0127** [comment]
怎么处理的该

**Comment by pyysha** [comment]
请问一下，怎么解决的呢？我不懂Linux，研究了两天都没办法安装好，求帮忙，谢谢！@kangmya

**Comment by jzp820927** [comment]
直接命令行运行  python code/3.3.1/launcher/start.py

**Comment by 13889682014** [comment]
有没有最新的解决办法   求助帮忙  感谢 @kangmya

**Comment by gjbg1989** [comment]
😂强烈建议楼主：标题追加【已解决】 https://github.com/XX-net/XX-Net/issues/10183
