### ISSUE TITLE
建议XX-net建立【谷歌保佑系统】

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#3774]
首先说说最近使用XX-net状态良好，没有问题，速度较为稳定。诚挚感谢XX-net服务和工作人员的辛勤劳动，使得正义的人们得救了，能完美的使用谷歌网络、感谢XX-net！感谢美国！

建议XX-net研发团队能更深层次的研发一种由谷歌带来的心灵感知保佑系统，保佑这些忠实使用谷歌的人们生活顺利，思维意识正确。当然我只是提出这么一种框架，这种保佑就像一种咒语。

第一步：
谷歌首先建立一个法术咒语平台，这个平台由8个柱状石柱组成，地面由天然石砖组成，上面刻有能量点，然后通过SGI超级计算机将一种谷歌能量传输到8个石柱上，再把能量汇集到法术平台能量场中心，由此生成数十万个咒语密码护身符、控制符，再把这种护身符以咒语密码的形式发送给XX-net用户，发送一组英文、数字组成的平安护身符，用户只要默念几次即可接收谷歌保佑系统的保佑。每组谷歌密码护身符可以保佑24小时。

第二步：
然后与世界最先进的D-Wave量子计算机链接，再由100台SGI超级计算机控制，让其作为核心数据中心，2-3天后谷歌用户可以再把上网获得的心灵数据，通过密码的形式反馈给谷歌真实正义数据储存中心。

第三步：
这样一来谷歌可以保佑每个XX-net用户。用户也可以实时与谷歌保持心灵相通。

**Comment by 80068** [comment]
当遇到困难的时候谷歌保佑系统，就会派出神影出现在你身边，帮你化解困难。

谷歌神影：
以人形存在的透明光体，可以瞬间出现、瞬间消失。可与人心灵感知。谷歌神影主要为了帮助需要帮助的人。

**Comment by jzp820927** [comment]
你肯定玩 LOL 走火入魔了吧

**Comment by riumiyama** [comment]
還有什麼技能？

**Comment by robert301** [comment]
good idea

**Comment by 80068** [comment]
@jzp820927 LOL是什么，是哄小孩的电脑游戏吗

**Comment by liujindong121** [comment]
没看懂，谁看懂了解释一下，最好是翻译一下

**Comment by yeahwu** [comment]
嗯，这个建议不错，俺们准备研发这个“谷歌保佑系统”，争取出个XX-Net Pro版，不卖个648都不好意思见人！

**Comment by LuckyLearning** [comment]
没看懂，去大神翻译

**Comment by myjlpt** [comment]
有这能量，，。建议直接攻击GFW，执行物理攻击。完毕

**Comment by panzer1313208** [comment]
@yeahwu 他说的什么鸡巴，没看懂。你别出pro啊，毕竟服务器是人家GAE的，lantern人家自己研发了服务器。

**Comment by yeahwu** [comment]
哈，surge没有服务端，用的ss的，不还恬不知耻地卖648！
俺这有google保佑技能，说不定心血来潮加上导弹发射功能，一键来妞功能，648是你赚了，好吧！
panzer1313208 <notifications@github.com>于2016年7月2日 周六18:00写道：

**Comment by jzp820927** [comment]
@80068 LOL是什么，我也不太清楚，听别人说，是很牛逼滴一种咚咚。

**Comment by 80068** [comment]
@jzp820927 哈哈

**Comment by simonasd** [comment]
其实Google一直在进行相关计划的研究，所谓的浮动数据中心，也只不过是掩人耳目罢了，船体内部核心迷藏着阵石，用船载着满世界寻找最适合的阵位。



这个阵的目的是给长者续命。




+1s

**Comment by showlee** [comment]
XX-Net让大家打通绿色长城之外的联系，可楼主厉害！居然打通了天地线！！！
