### ISSUE TITLE
[WARNING] APPID error:400 url:https://localhost:26143/skypectoc/v1/pnr/parse

### ISSUE THREAD

**Issue by KevinLeung007** [XX-net/XX-Net#378]
时断时续的，这是为什么啊？我自己的AppID

**Comment by xxnet** [comment]
你访问本地的服务，怎么要通过代理呢？

https://localhost:26143/skypectoc/v1/pnr/parse
这是本地及其跑的什么服务？

2015-05-09 22:50 GMT-04:00 KevinLeung007 <notifications@github.com>:
