### ISSUE TITLE
手机上不了facebook？youtube视频可以正常看。

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#3780]
Jul 02 20:50:32.109 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:50:33.893 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:50:34.190 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:50:36.597 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:50:37.231 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:50:39.693 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:50:49.889 - [INFO] PAC from:127.0.0.1:1737 GET /proxy.pac
Jul 02 20:50:54.048 - [DEBUG] GAE GET http://google.com/ncr
Jul 02 20:50:54.319 - [INFO] GAE t:270 s:223 GET http://google.com/ncr h2_get_head:266
Jul 02 20:50:54.385 - [DEBUG] GAE GET https://www.google.com/ncr
Jul 02 20:50:54.674 - [INFO] GAE t:289 s:220 GET https://www.google.com/ncr get_response:289
Jul 02 20:50:54.777 - [DEBUG] GAE GET https://www.google.com/
Jul 02 20:50:55.084 - [INFO] GAE t:307 s:25151 GET https://www.google.com/ h2_get_head:282,h2_finish[SP:1106739]:22
Jul 02 20:50:55.100 - [INFO] PAC from:127.0.0.1:1748 GET /proxy.pac
Jul 02 20:50:55.251 - [DEBUG] GAE GET https://www.google.com/images/hpp/gsa_super_g-64.gif
Jul 02 20:50:55.251 - [DEBUG] GAE GET https://www.google.com/images/nav_logo242_hr.png
Jul 02 20:50:55.298 - [DEBUG] GAE GET https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png
Jul 02 20:50:55.525 - [INFO] GAE t:274 s:0 GET https://www.google.com/images/hpp/gsa_super_g-64.gif get_response:258,h2_finish[SP:18187]:16
Jul 02 20:50:55.525 - [INFO] GAE t:274 s:0 GET https://www.google.com/images/nav_logo242_hr.png h2_get_head:258,h2_finish[SP:18187]:16
Jul 02 20:50:55.571 - [INFO] GAE t:273 s:0 GET https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png get_response:243
Jul 02 20:50:56.198 - [DEBUG] GAE GET https://www.google.com/gen_204?v=3&s=mobilewebhp&atyp=csi&ei=rbh3V6PgE8vdjwTM7J2IBA&imc=2&imn=2&imp=2&adh=&xjs=init.139.13.sb_mob.99.dvl.19.c.6.jsa.5.async.4&conn=wifi&ima=1&rt=xjsls.84,prt.89,iml.786,dcl.130,xjses.436,xjsee.711,xjs.712,ol.918,aft.786,wsrt.1141,cst.78,dnst.0,rqst.339,rspt.43,sslt.56,rqstt.756,unt.666,cstt.678,dit.1266
Jul 02 20:50:56.260 - [DEBUG] GAE GET https://www.google.com/images/nav_logo242.png
Jul 02 20:50:56.336 - [DEBUG] GAE GET https://www.google.com/images/branding/product/1x/gsa_shadowed_144dp.png
Jul 02 20:50:56.344 - [DEBUG] GAE GET https://www.google.com/gen_204?atyp=i&ct=14&cad=i&ogsr=1&id=19000275&ic=2&ogd=google.com&ogprm=up&vet=10ahUKEwjj6srt6NTNAhXL7oMKHUx2B0EQjW0IAQ.rbh3V6PgE8vdjwTM7J2IBA.s&ei=rbh3V6PgE8vdjwTM7J2IBA&zx=1467463854683
Jul 02 20:50:56.463 - [INFO] GAE t:265 s:0 GET https://www.google.com/gen_204?v=3&s=mobilewebhp&atyp=csi&ei=rbh3V6PgE8vdjwTM7J2IBA&imc=2&imn=2&imp=2&adh=&xjs=init.139.13.sb_mob.99.dvl.19.c.6.jsa.5.async.4&conn=wifi&ima=1&rt=xjsls.84,prt.89,iml.786,dcl.130,xjses.436,xjsee.711,xjs.712,ol.918,aft.786,wsrt.1141,cst.78,dnst.0,rqst.339,rspt.43,sslt.56,rqstt.756,unt.666,cstt.678,dit.1266 h2_get_head:249,h2_finish[SP:15624]:16
Jul 02 20:50:56.510 - [INFO] GAE t:250 s:0 GET https://www.google.com/images/nav_logo242.png get_response:250
Jul 02 20:50:56.588 - [INFO] GAE t:252 s:0 GET https://www.google.com/images/branding/product/1x/gsa_shadowed_144dp.png get_response:235
Jul 02 20:50:56.588 - [INFO] GAE t:243 s:0 GET https://www.google.com/gen_204?atyp=i&ct=14&cad=i&ogsr=1&id=19000275&ic=2&ogd=google.com&ogprm=up&vet=10ahUKEwjj6srt6NTNAhXL7oMKHUx2B0EQjW0IAQ.rbh3V6PgE8vdjwTM7J2IBA.s&ei=rbh3V6PgE8vdjwTM7J2IBA&zx=1467463854683 get_response:227
Jul 02 20:50:57.103 - [DEBUG] GAE GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=jw.qust.edu.cn
Jul 02 20:50:57.108 - [DEBUG] GAE GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=wap.10010.com
Jul 02 20:50:57.109 - [DEBUG] GAE GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=self.qust.edu.cn:8080
Jul 02 20:50:57.111 - [DEBUG] GAE GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=172.16.10.3
Jul 02 20:50:58.046 - [INFO] GAE t:943 s:61 GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=jw.qust.edu.cn get_response:941
Jul 02 20:50:58.062 - [INFO] GAE t:953 s:61 GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=wap.10010.com get_response:953
Jul 02 20:50:59.084 - [INFO] GAE t:1975 s:61 GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=self.qust.edu.cn:8080 get_response:1974
Jul 02 20:51:00.233 - [INFO] GAE t:3121 s:61 GET http://browser.meizu.com/v1/public/favorite/icon?language=zh_CN&locale=CN&os=22&mzos=5.0&screen_size=1080x1920&device_model=mx5&v=4.5.0010&vc=450010&firmware_type=normal&domainname=172.16.10.3 get_response:3121
Jul 02 20:51:04.108 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:51:06.120 - [DEBUG] GAE GET http://cn.rfi.fr//20160629-
Jul 02 20:51:07.525 - [INFO] GAE t:1405 s:29581 GET http://cn.rfi.fr//20160629- get_response:1382,h2_finish[SP:1358555]:21
Jul 02 20:51:10.403 - [DEBUG] ssl_closed 203.252.15.141
Jul 02 20:51:10.403 - [DEBUG] 203.252.15.141 worker close:idle timeout
Jul 02 20:51:12.288 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:fbcdn-profile-a.akamaihd.net
Jul 02 20:51:12.413 - [INFO] scan_ip add ip:64.246.133.23 time:1176
Jul 02 20:51:15.732 - [DEBUG] ssl_closed 202.224.62.28
Jul 02 20:51:15.732 - [DEBUG] 202.224.62.28 worker close:idle timeout
Jul 02 20:51:15.825 - [DEBUG] sort ip time:31ms
Jul 02 20:51:15.825 - [DEBUG] get ip:202.224.62.28 t:144
Jul 02 20:51:17.065 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:fbcdn-profile-a.akamaihd.net
Jul 02 20:51:18.669 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:fbcdn-profile-a.akamaihd.net
Jul 02 20:51:19.837 - [DEBUG] 202.224.62.28 fail:timeout('timed out',)
Jul 02 20:51:19.837 - [DEBUG] report_connect_fail:202.224.62.28
Jul 02 20:51:19.837 - [DEBUG] get ip:203.252.15.141 t:151
Jul 02 20:51:20.055 - [DEBUG] create_ssl update ip:203.252.15.141 time:156 h2:0
Jul 02 20:51:20.055 - [DEBUG] get ip:203.233.96.30 t:175
Jul 02 20:51:20.298 - [DEBUG] create_ssl update ip:203.233.96.30 time:180 h2:0
Jul 02 20:51:20.499 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com
Jul 02 20:51:20.759 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:fbcdn-profile-a.akamaihd.net
Jul 02 20:51:21.945 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:graph.facebook.com

**Comment by yeahwu** [comment]
证书问题

**Comment by xiaoyan94** [comment]
@yeahwu 我导入证书了啊，google youtube视屏都能看？？？

**Comment by jzp820927** [comment]
不知道你出问题的是 手机浏览器，还是 APP，部分 APP 不支持自导入的证书

**Comment by DPABeginner** [comment]
xx-net有手机端？能否上个下载地址

**Comment by jzp820927** [comment]
手机可以用 PAC

**Comment by xiaoyan94** [comment]
是app。

**Comment by jzp820927** [comment]
首先手机要导入 证书，其次 部分 app 不支持 自导证书，这个基本上无解(或者很难解，要 root ，然后手动解决证书问题，不过那是程序员的事了，一般用户，没那个能力。)。
app 的话，可以试试 x_tunnel，x_tunnel 没有证书问题，应该可以解决。不过如果 app 不认 wifi 代理的话，估计也没办法。
