### ISSUE TITLE
php proxy 在https连接时报错 [except][errno 9]Bad file descriptor

### ISSUE THREAD

**Issue by burnegg** [XX-net/XX-Net#3788]
国外服务器，curl能正常连接https的谷歌
代理的时候https连接不上
在 strip connect https://client.google.com:443 HTTP/1.1
之后直接报错
 [except][errno 9]Bad file descriptor

**Comment by jzp820927** [comment]
这个是日志里面的报错信息？

**Comment by burnegg** [comment]
是的，具体如下
Jul 04 14:23:50 - [INFO] 127.0.0.1:5023 "STRIP CONNECT clients1.google.com:443 HTTP/1.1" - -
Jul 04 14:23:50 - [INFO] 127.0.0.1:5024 "STRIP CONNECT clients1.google.com:443 HTTP/1.1" - -
Jul 04 14:23:50 - [INFO]LOG_EXCEPT: 127.0.0.1:5025 "STRIP CONNECT clients1.google.com:443 HTTP/1.1" - -, Except:[Errno 9] Bad file descriptor

**Comment by jzp820927** [comment]
PHP X大很早之前就没维护了，这个还真不好说是啥问题。如果你喜欢用 PHP，建议你用 goproxy 性能很好，而且一直维护。

**Comment by burnegg** [comment]
好的，谢啦
