### ISSUE TITLE
部署服务端一直不成功Checking if deployment succeeded.

### ISSUE THREAD

**Issue by zhy0530** [XX-net/XX-Net#379]
![qq 20150510185545](https://cloud.githubusercontent.com/assets/12380332/7554004/8e6f3b7a-f746-11e4-859a-309eb5af9cca.png)
![qq 20150510185633](https://cloud.githubusercontent.com/assets/12380332/7554005/8e6fc6f8-f746-11e4-8c22-6e343d37a19a.png)
![qq 20150510185657](https://cloud.githubusercontent.com/assets/12380332/7554006/8e71e32a-f746-11e4-88ca-4136a205ff37.png)
我以前用goagent上传过的appid可以正常在xx-net上使用。

**Comment by xxnet** [comment]
这种现象没有遇到过。

可以试试在授权页面取消，重新部署

2015-05-10 7:01 GMT-04:00 zhy0530 <notifications@github.com>:

**Comment by Eri5Ch** [comment]
同样的情况，一直在检查，不知道成功与否。

**Comment by xxnet** [comment]
点击取消，再重新部署，可以吗

2015-05-11 5:05 GMT-04:00 Eri5Ch <notifications@github.com>:

**Comment by Eri5Ch** [comment]
试过几次了，不行，挂vpn上传也不行，一直提示正在检查，上GAE上查看，提示已经上传，不知道能不能用。另外，Google开启二次验证，用专用密码来上传的，不知道有没有关系。

**Comment by Eri5Ch** [comment]
May 11 17:10:46 - [INFO] PAC from:127.0.0.1:4981 GET /proxy.pac 
May 11 17:10:46 - [DEBUG] GoAgent Web_control 127.0.0.1:4982 "GET /deploy?cmd=get_log 
May 11 17:10:47 - [DEBUG] GoAgent Web_control 127.0.0.1:4987 "GET /deploy?cmd=get_log 
May 11 17:10:48 - [DEBUG] GoAgent Web_control 127.0.0.1:4990 "GET /deploy?cmd=get_log 
May 11 17:10:49 - [DEBUG] GoAgent Web_control 127.0.0.1:4991 "GET /deploy?cmd=get_log 
May 11 17:10:50 - [DEBUG] GoAgent Web_control 127.0.0.1:4993 "GET /deploy?cmd=get_log 
May 11 17:10:50 - [WARNING] _request:SysCallError(10054, 'Connection reset by peer')
May 11 17:10:50 - [WARNING] fetch gae status:UNKNOWN url:https://appengine.google.com/api/appversion/isready?version=1&app_id=........
May 11 17:10:50 - [WARNING] request failed:(10054, 'Connection reset by peer')

这是代理日志，已删除我的appid～
