### ISSUE TITLE
在centos7服务器下，本机没有图形界面，如何通过配置文件开启远程web ui？

### ISSUE THREAD

**Issue by changxy726** [XX-net/XX-Net#3799]
在 data/gae_proxy/config.ini或 data/gae_proxy/manual.ini尝试了这个配置，没有任何效果

[control]
; http 控制端口，配合launcher Web界面用
enable = 1
ip = 127.0.0.1
port = 8084

**Comment by jzp820927** [comment]
data/gae_proxy/config.ini
