### ISSUE TITLE
linux下浏览网页全是403error，同样的账号windows下正常？

### ISSUE THREAD

**Issue by johnhullv5** [XX-net/XX-Net#38]
linux下log:
FWD CONNECT xxnet-update.appspot.com 443,
 FWD CONNECT www.google.com 443
浏览网页全是403 error，
同一个账号在windows下正常浏览

**Comment by xxnet** [comment]
403 是没有权限的意思，具体的网页显示什么？
把详细的日志发给我分析吧， xxnet.dev@gmail.com
