### ISSUE TITLE
关于高CPU占用的问题

### ISSUE THREAD

**Issue by JebYore** [XX-net/XX-Net#380]
当我运行 goagent 3.2.3 的时候，终端中显示这么一句话"If you want to fix high cpu usage, please decrease [gae] window"

![1](https://cloud.githubusercontent.com/assets/12298166/7554521/c207d886-f6f9-11e4-943c-a7ed4b42ee56.png)

我不确定 [gae] window 是否指 goagent 运行时的窗口，但我决定照此思路试试看。

经过尝试，按照以下步骤调整终端窗口后，对于高cpu问题的解决有点效果

我用的是Linux，首先在终端中打开xx-net(试验的时候用的是1.14.1版)

![2](https://cloud.githubusercontent.com/assets/12298166/7554535/40e5285c-f6fa-11e4-9bc2-f3fb1e0a246c.png)

然后缩小窗口

![3](https://cloud.githubusercontent.com/assets/12298166/7554556/05d2dfb0-f6fb-11e4-9e4d-16c0fa58da1b.png)

滚动条向上滚动

![4](https://cloud.githubusercontent.com/assets/12298166/7554573/7bfb549c-f6fb-11e4-8d1c-0ab609671fba.png)

最后在浏览器中使用，让xx-net自动运行几秒钟后，窗口就会变成这样，不显示文字

![5](https://cloud.githubusercontent.com/assets/12298166/7554604/2eb9cf3c-f6fc-11e4-977a-cbd8e9bfd438.png)

这样调整窗口后，经过一个小时的不断地观看不同的youtube短视频，并没有出现高cpu的现象。我不清楚这样操作对于cpu占用过高的问题是否真的有效，但至少比以前好。之前观看youtube视频的时候问题出现的相当的频繁。

**Comment by yfdyh000** [comment]
这个 window 不是指运行窗口，而是数据收发窗口，原版goagent中是 proxy.ini 中的 [gae] window 那项参数。可能是巧合，或者运行日志输出/渲染造成了过高的占用。
