### ISSUE TITLE
3.2.4无法打开http页面，但https都没有问题

### ISSUE THREAD

**Issue by xiaodid** [XX-net/XX-Net#3811]
这个问题我没有注意从哪个版本开始的，现在在3.2.4中无法打开http，但可以打开https的网页。比如，http://www.bing.com不行，https://www.bing.com就可以。打不开的现象是再chrome的network里看不到任何连接请求发出，xx net的log里也看不到。

诊断信息：
XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:831 good:811
network-status: OK
connected-link: new:6 used:0
worker: h1:19 h2:2
scan-ip-thread-num: 50
ip-quality: 793
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
看状态，一切正常。

**Comment by yeahwu** [comment]
重新设置一下代理试试！

**Comment by xiaodid** [comment]
我换了不同的浏览器，还是不行，可能是系统的问题，因为同样的程序，在别的系统里没问题。close this issue
