### ISSUE TITLE
关于移除php-proxy模块问题

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3824]
已经由女神 @Cat7373精巧的双手，移除掉了php-proxy相关文件，代码。非常感谢

为什么要移除这个模块？

1:XX-Net内置的php-proxy模块效率比较低，已经跟不上现在的翻墙形势
2:有更好的替代php方案，比如x-tunnel，还有@phuslu 社长的goproxy-php，效率更高
3:php-proxy模块已经太久没更新了，同时轻量化XX-Net，提高效率。

向正在用php-proxy的朋友说声抱歉，建议转移到gae模块，X-Tunnel模块，或者goproxy-php。当然你也可以使用现有的3.2.5及以下的版本。

当然，已经知会过x大。下面版本已经移除了php，大家不妨试试。
下载：
 https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by jzp820927** [comment]
试了下，没发现啥问题，源代码也精简了很多，有点 mini 的味道了

**Comment by yeahwu** [comment]
去陈接新 嘛 :smile:

**Comment by simonasd** [comment]
不错不错。考虑XX-Net的定位，PHP模块其实是多余的。

**Comment by yeahwu** [comment]
@simonasd 兄台好久不见哪！

**Comment by verbamboo** [comment]
@jzp820927 手动更新xx-net该怎么办？

**Comment by Cat7373** [comment]
其实清理还是不干净的，内置的 Python 的 lib 里可能有些库只有 PHP 用到了。
不过这玩意我就不敢碰咯

**Comment by zzgpku** [comment]
赞成~

**Comment by riumiyama** [comment]
乾脆 吧 x-tunnel 也去掉好了 收費的不友好

**Comment by yeahwu** [comment]
gae有些缺陷需要x-tunnel来弥补，比如上传下载问题，零星网站打不开现象。
另外，给项目创收，募集appid，让更多不会申请id的朋友用上gae。
如果要用上x-tunnel，最简单的办法，捐appid就好了！
riumiyama <notifications@github.com>于2016年7月9日 周六12:18写道：

**Comment by yeahwu** [comment]
@Cat7373 其实已经清理得够干净了，辛苦你了。然后核心的依赖库慢慢来，不急

**Comment by yeahwu** [comment]
@Cat7373 刚看了下lib里面的文件，那些后缀为pyd的文件是干什么的？俺看都可以删掉！这里面的文件好像有点乱哪。

**Comment by yeahwu** [comment]
@Cat7373 妹纸，要不你windows下试试，删掉 python27/1.0/lib/  下的所有 .pyd 后缀的文件，然后启动测试一下有没有什么问题？  俺这边linux下删掉后没有什么问题！

**Comment by Cat7373** [comment]
pyd 在 Windows 下本质上是一个 dll 文件

**Comment by yeahwu** [comment]
哦，俺忘了。Linux依赖的是系统python，俺说呢！lib文件下都删光了，还是跑得挺溜。
Cat73 <notifications@github.com>于2016年7月9日 周六16:06写道：

**Comment by yeahwu** [comment]
刚试用了下lantern pro，一个月免费800m流量，速度好像和以前的lantern没什么区别呀？

**Comment by jzp820927** [comment]
以后要限速 20KB/s 了，只能看看网页了。

**Comment by yeahwu** [comment]
俺发现lantern pro版的支付方式还是很牛逼的，直接支付宝和信用卡支付。就不怕一言不合给查了？

**Comment by jzp820927** [comment]
不是直接用的 支付宝，是调用美国 Stripe 公司的支付接口。

**Comment by magnet1215** [comment]
@yeahwu 现在捐赠appid还有流量赠送吗？有相关链接吗？

**Comment by gjbg1989** [comment]
请问：为何此版近来总是将proxy.pac更新到不能正常工作的850KB（发现越来越大849-851）？貌似120KB才正常

**Comment by tkisme** [comment]
X-Tunnel 有server版源码么？

**Comment by jzp820927** [comment]
X-Tunnel 的 Server 源代码，X大没有公开。有能力的应该可以直接写代码实现。原理倒是比较简单。

**Comment by tkisme** [comment]
算了，懒得搞，ss 替代这个通道吧

**Comment by simonasd** [comment]
X-Tunnel 的 Server 源码问过X大几次，可能是出于什么考虑不便公开吧。虽然说可以用SS，但自建的SS基本都是单个IP，流量大的话，部分ISP会针对性掐网

**Comment by jzp820927** [comment]
X-Tunnel 的原理也不是很复杂，程序猿应该能直接写吧。

**Comment by SeaHOH** [comment]
原理不复杂，就是比较奇葩，也是逼出来的。

**Comment by jzp820927** [comment]
曲线救国，也是奇招

**Comment by gjbg1989** [comment]
请教：貌似标准版与此master版一样也已经移除了php？
