### ISSUE TITLE
AppID超额,传出带宽10%,传入带宽100%

### ISSUE THREAD

**Issue by jqtmviyu** [XX-net/XX-Net#3825]
ipv6,24个appid，都是这种情况。（以前也出现过一次）

诊断信息
XX-Net Status：

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 1
gws-ip-num: 3818 / 40
network-status: OK
connected-link: 12 / 0
scan-ip-thread-num: 0
ip-quality: 727
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: false
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zzgpku** [comment]
升级xxnet至新版
