### ISSUE TITLE
如何解决公司生产vpn和xx-net共用的问题？

### ISSUE THREAD

**Issue by lbx6z** [XX-net/XX-Net#3836]
在公司办公，如果要使用生产机器，就需要使用vpn。
可是我一打开xx-net，生产vpn就会自动断掉，请问这是什么原因？（我对vpn的原理不是很了解）以及如何解决？

**Comment by jzp820927** [comment]
不科学啊，这2个应该不干扰的吧

**Comment by yeahwu** [comment]
如果VPN是全局代理的话，还是干扰的。比如xx会扫出很多无用IP等。
还有端口占有等，不建议多个翻墙软件一起用。
天朝屁民 <notifications@github.com>于2016年7月11日 周一11:42写道：

**Comment by jzp820927** [comment]
那就不要同时运行，看看会不会出问题。如果正常的话，那就不能同时运行了。

**Comment by lbx6z** [comment]
不同时运行没啥问题。sad...所以得寻求别的翻墙机制了么？还有别的翻墙机制么？[泪目]

**Comment by linhua55** [comment]
自动断掉，是指VPN客户端软件崩溃了吗？ 可以试下减小扫描线程数 。如果不使用VPN就可以连接外网的话，那就使用route命令，手动设置路由表，连接外网 不经过VPN，连接内网才使用VPN

**Comment by lbx6z** [comment]
我错了，求原谅>.<   我又试了一下，可以共用。大概之前生产vpn断掉，是长时间不用，它自己断的。（我始终怀疑这两个会有干扰，所以就没有再验证）sorry..
