### ISSUE TITLE
日志页无显示

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#384]
有时候会出现，比如刚打开XX-Net后的几分钟内
Console看到的输出
GET http://127.0.0.1:8084/log?cmd=get_new&last_no=1 net::ERR_EMPTY_RESPONSE
GET http://127.0.0.1:8084/log?cmd=get_new&last_no=1 net::ERR_EMPTY_RESPONSE
GET http://127.0.0.1:8084/log?cmd=get_new&last_no=1 net::ERR_EMPTY_RESPONSE

**Comment by xxnet** [comment]
看看有没有什么规律。
近期这块印象中没有改动。

2015-05-11 3:16 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by Cat7373** [comment]
- -从很久之前就是这样的

**Comment by xxnet** [comment]
会不会是goagent模块还没有启动完成？
但不会几分钟还这样。一般goagent模块启动时间在10秒左右。

**Comment by Cat7373** [comment]
https://github.com/Cat7373/CatFamilyTree/blob/master/tmp/111.jpg
如上图- -
打开后2分钟左右才能获取到日志- -

**Comment by xxnet** [comment]
可以start.bat模式启动，看看发生了什么

2015-05-11 4:35 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by edwinfj** [comment]
我也遇到了类似的问题。配置页面中日志页是空白，但是dos console里都可以看到log。
另外，我启动xx-net之后，配置页也不会自动在chrome里加载。点击system tray里的xx-net图标，也不会打开配置页。点击xx-net图标里的“配置”，也不会打开配置页。
需要手动key 127.0.0.1:8085 才能在chrome里出现配置页。
我用的是1.14.2，刚刚用自己的appid配置好了服务端，用刚配置好的appid更新配置之后，就出现了这个问题。

**Comment by xxnet** [comment]
请用start.bat启动，
然后观察日志有没有异常

在 2015年5月11日 上午7:36，edwinfj <notifications@github.com>写道：

**Comment by nly4lov** [comment]
看着你们遇到的困难，忽然赶脚好幸福哈哈

**Comment by Pd69bq** [comment]
在mac下一直是console取不到参数 用start.command可以但是直接sudo start.sh就取不出来 同样和@edwinfj描述的情况一样 log可以看到 没试过直接手动输入的方式打开8085端口

**Comment by xxnet** [comment]
“在mac下一直是console取不到参数”
  是什么意思？

@edwinfj <https://github.com/edwinfj>
  请贴出启动日志

在 2015年5月14日 上午4:05，Chris Baconham <notifications@github.com>写道：

**Comment by Pd69bq** [comment]
@xxnet 意思就是在mac下我使用start.sh启动的话 点图标自动打开127.0.0.1:8085页面 GoAgent状态信息是空白的 完全取不到参数。 我曾经使用start.command启动就可以取到参数，不过在mac下 我还是习惯使用shell的东西

**Comment by edwinfj** [comment]
@xxnet 
今天特意跑了下XX-NET，贴出启动日志。设计隐私的部分用****带过。
May 23 21:57:43 - [INFO] use goagent version:3.1.49
May 23 21:57:43 - [INFO] goagent 3.1.49 started C:\Users\****\Dropbox\Useful st
uff\翻墙\XX-Net-1.14.2\goagent\3.1.49\start.py
May 23 21:57:43 - [INFO] load ip range file:C:\Users\****\Dropbox\Useful stuff\
翻墙\XX-Net-1.14.2\data\goagent\ip_range.txt
May 23 21:57:43 - [INFO] load google ip_list num:3000, gws num:3000
May 23 21:57:43 - [DEBUG] sort ip time:3
May 23 21:57:44 - [INFO] ------------------------------------------------------
GoAgent Version    : 3.1.49 (python/2.7.9 )
Listen Address     : 127.0.0.1:8087
Control Address    : 127.0.0.1:8084
GAE APPID          : edwinfjxxnet
Pac Server         : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

May 23 21:57:45 - [DEBUG] GoAgent Web_control 127.0.0.1:60623 "GET /is_ready
May 23 21:57:45 - [INFO] start goagent time cost 2007
May 23 21:57:45 - [DEBUG] launcher web_control 127.0.0.1:60624 "GET /
May 23 21:57:46 - [DEBUG] get ip:210.242.125.59 t:78
May 23 21:57:46 - [DEBUG] get ip:64.233.189.201 t:304
May 23 21:57:46 - [DEBUG] get ip:61.19.1.241 t:441
May 23 21:57:47 - [DEBUG] get ip:194.78.99.166 t:498
May 23 21:57:47 - [DEBUG] get ip:210.242.125.44 t:501
May 23 21:57:47 - [DEBUG] get ip:61.19.1.247 t:542
May 23 21:57:48 - [DEBUG] get ip:194.78.99.146 t:556
May 23 21:57:48 - [DEBUG] create_ssl 210.242.125.59 fail:timed out cost:2001 h:0

May 23 21:57:48 - [DEBUG] get ip:222.255.120.57 t:737
May 23 21:57:48 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:2001 h:0

May 23 21:57:48 - [DEBUG] report_connect_fail network fail
May 23 21:57:48 - [DEBUG] get ip:64.233.162.83 t:738
May 23 21:57:48 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:2000 h:0
May 23 21:57:48 - [DEBUG] report_connect_fail network fail
May 23 21:57:49 - [DEBUG] get ip:222.255.120.59 t:738
May 23 21:57:49 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:2000 h:0
May 23 21:57:49 - [DEBUG] report_connect_fail network fail
May 23 21:57:49 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:2000 h:0

May 23 21:57:49 - [DEBUG] report_connect_fail network fail
May 23 21:57:49 - [DEBUG] get ip:64.15.119.131 t:743
May 23 21:57:49 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:2000 h:0
May 23 21:57:49 - [DEBUG] report_connect_fail network fail
May 23 21:57:49 - [DEBUG] get ip:111.168.255.54 t:744
May 23 21:57:50 - [DEBUG] create_ssl update ip:64.233.162.83 time:917
May 23 21:57:50 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:2000 h:0
May 23 21:57:50 - [DEBUG] report_connect_fail network fail
May 23 21:57:50 - [DEBUG] get ip:178.45.251.40 t:744
May 23 21:57:50 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:2000 h:0

May 23 21:57:50 - [DEBUG] get ip:216.58.217.36 t:744
May 23 21:57:50 - [DEBUG] get ip:66.185.84.54 t:744
May 23 21:57:51 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:2003 h:0

May 23 21:57:51 - [DEBUG] get ip:81.175.29.185 t:744
May 23 21:57:51 - [DEBUG] get ip:61.219.131.109 t:744
May 23 21:57:51 - [DEBUG] get ip:111.92.162.34 t:745
May 23 21:57:51 - [DEBUG] get ip:111.168.255.44 t:745
May 23 21:57:51 - [DEBUG] create_ssl 64.15.119.131 fail:timed out cost:2000 h:0
May 23 21:57:51 - [DEBUG] create_ssl 111.168.255.54 fail:timed out cost:2000 h:0

May 23 21:57:52 - [DEBUG] get ip:210.139.253.45 t:745
May 23 21:57:52 - [DEBUG] create_ssl 178.45.251.40 fail:timed out cost:2000 h:0
May 23 21:57:52 - [DEBUG] create_ssl 216.58.217.36 fail:timed out cost:2001 h:0
May 23 21:57:52 - [DEBUG] get ip:103.1.139.174 t:745
May 23 21:57:52 - [DEBUG] create_ssl 66.185.84.54 fail:timed out cost:2001 h:0
May 23 21:57:52 - [DEBUG] get ip:218.253.0.80 t:745
May 23 21:57:53 - [DEBUG] create_ssl 81.175.29.185 fail:timed out cost:2000 h:0
May 23 21:57:53 - [DEBUG] create_ssl 61.219.131.109 fail:timed out cost:2000 h:0

May 23 21:57:53 - [DEBUG] get ip:216.58.192.8 t:745
May 23 21:57:53 - [DEBUG] create_ssl 111.92.162.34 fail:timed out cost:2000 h:0
May 23 21:57:53 - [DEBUG] create_ssl 111.168.255.44 fail:timed out cost:2000 h:0

May 23 21:57:53 - [DEBUG] get ip:210.139.253.221 t:745
May 23 21:57:53 - [DEBUG] sort ip time:3
May 23 21:57:53 - [DEBUG] get ip:64.233.178.81 t:746
May 23 21:57:54 - [DEBUG] create_ssl 210.139.253.45 fail:timed out cost:2000 h:0

May 23 21:57:54 - [DEBUG] get ip:103.25.178.19 t:746
May 23 21:57:54 - [DEBUG] get ip:202.86.162.49 t:746
May 23 21:57:54 - [DEBUG] get ip:220.255.6.55 t:746
May 23 21:57:54 - [DEBUG] get ip:202.39.143.54 t:746
May 23 21:57:54 - [DEBUG] create_ssl 103.1.139.174 fail:timed out cost:2000 h:0
May 23 21:57:54 - [DEBUG] create_ssl 218.253.0.80 fail:timed out cost:2001 h:0
May 23 21:57:55 - [DEBUG] get ip:218.176.242.34 t:746
May 23 21:57:55 - [DEBUG] create_ssl 216.58.192.8 fail:timed out cost:2000 h:0
May 23 21:57:55 - [DEBUG] create_ssl 210.139.253.221 fail:timed out cost:2000 h:
0
May 23 21:57:55 - [DEBUG] get ip:1.179.248.109 t:746
May 23 21:57:55 - [DEBUG] create_ssl 64.233.178.81 fail:timed out cost:2000 h:0
May 23 21:57:55 - [DEBUG] get ip:118.174.25.34 t:745
May 23 21:57:56 - [DEBUG] create_ssl 103.25.178.19 fail:timed out cost:2000 h:0
May 23 21:57:56 - [DEBUG] create_ssl 202.86.162.49 fail:timed out cost:2000 h:0
May 23 21:57:56 - [DEBUG] get ip:64.233.160.31 t:745
May 23 21:57:56 - [DEBUG] create_ssl 220.255.6.55 fail:timed out cost:2000 h:0
May 23 21:57:56 - [DEBUG] create_ssl 202.39.143.54 fail:timed out cost:2000 h:0
May 23 21:57:56 - [DEBUG] get ip:106.162.216.59 t:745
May 23 21:57:56 - [DEBUG] get ip:64.233.189.139 t:745
May 23 21:57:57 - [DEBUG] create_ssl 218.176.242.34 fail:timed out cost:2000 h:0

May 23 21:57:57 - [DEBUG] get ip:64.233.169.87 t:745
May 23 21:57:57 - [DEBUG] get ip:202.86.162.55 t:745
May 23 21:57:57 - [DEBUG] get ip:93.183.211.238 t:745
May 23 21:57:57 - [DEBUG] get ip:210.139.253.114 t:745
May 23 21:57:57 - [DEBUG] create_ssl 1.179.248.109 fail:timed out cost:2000 h:0
May 23 21:57:57 - [DEBUG] create_ssl 118.174.25.34 fail:timed out cost:2000 h:0
May 23 21:57:58 - [DEBUG] get ip:118.174.25.109 t:745
May 23 21:57:58 - [DEBUG] create_ssl 64.233.160.31 fail:timed out cost:2000 h:0
May 23 21:57:58 - [DEBUG] create_ssl 106.162.216.59 fail:timed out cost:2001 h:0

May 23 21:57:58 - [DEBUG] get ip:208.117.224.245 t:745
May 23 21:57:58 - [DEBUG] create_ssl 64.233.189.139 fail:timed out cost:2002 h:0

May 23 21:57:58 - [DEBUG] get ip:64.233.189.201 t:304
May 23 21:57:59 - [DEBUG] create_ssl 64.233.169.87 fail:timed out cost:2002 h:0
May 23 21:57:59 - [DEBUG] create_ssl 202.86.162.55 fail:timed out cost:2000 h:0
May 23 21:57:59 - [DEBUG] get ip:61.19.1.241 t:441
May 23 21:57:59 - [DEBUG] create_ssl 93.183.211.238 fail:timed out cost:2002 h:0

May 23 21:57:59 - [DEBUG] create_ssl 210.139.253.114 fail:timed out cost:2002 h:
0
May 23 21:57:59 - [DEBUG] get ip:194.78.99.166 t:498
May 23 21:57:59 - [DEBUG] get ip:210.242.125.44 t:501
May 23 21:58:00 - [DEBUG] create_ssl 118.174.25.109 fail:timed out cost:2000 h:0

May 23 21:58:00 - [DEBUG] get ip:61.19.1.247 t:542
May 23 21:58:00 - [DEBUG] get ip:194.78.99.146 t:556
May 23 21:58:00 - [DEBUG] get ip:83.94.121.178 t:745
May 23 21:58:00 - [DEBUG] get ip:210.139.253.88 t:746
May 23 21:58:00 - [DEBUG] create_ssl 208.117.224.245 fail:timed out cost:2000 h:
0
May 23 21:58:00 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:2000 h:0

May 23 21:58:01 - [DEBUG] get ip:118.143.88.35 t:746
May 23 21:58:01 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:2000 h:0
May 23 21:58:01 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:2000 h:0
May 23 21:58:01 - [DEBUG] get ip:202.86.162.45 t:746
May 23 21:58:01 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:2000 h:0

May 23 21:58:01 - [DEBUG] get ip:62.116.207.35 t:746
May 23 21:58:02 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:2000 h:0
May 23 21:58:02 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:2001 h:0
May 23 21:58:02 - [DEBUG] get ip:118.174.27.35 t:746
May 23 21:58:02 - [DEBUG] create_ssl 83.94.121.178 fail:timed out cost:2000 h:0
May 23 21:58:02 - [DEBUG] create_ssl 210.139.253.88 fail:timed out cost:2000 h:0

May 23 21:58:02 - [DEBUG] get ip:216.58.221.206 t:746
May 23 21:58:02 - [DEBUG] get ip:61.219.131.118 t:746
May 23 21:58:03 - [DEBUG] create_ssl 118.143.88.35 fail:timed out cost:2001 h:0
May 23 21:58:03 - [DEBUG] get ip:216.58.221.19 t:746
May 23 21:58:03 - [DEBUG] get ip:218.253.0.144 t:746
May 23 21:58:03 - [DEBUG] get ip:64.233.177.157 t:746
May 23 21:58:03 - [DEBUG] get ip:218.176.242.88 t:747
May 23 21:58:03 - [DEBUG] create_ssl 202.86.162.45 fail:timed out cost:2000 h:0
May 23 21:58:03 - [DEBUG] create_ssl 62.116.207.35 fail:timed out cost:2000 h:0
May 23 21:58:04 - [DEBUG] sort ip time:3
May 23 21:58:04 - [DEBUG] get ip:111.168.255.178 t:748
May 23 21:58:04 - [DEBUG] create_ssl 118.174.27.35 fail:timed out cost:2001 h:0
May 23 21:58:04 - [DEBUG] create_ssl 216.58.221.206 fail:timed out cost:2001 h:0

May 23 21:58:04 - [DEBUG] get ip:64.15.116.245 t:748
May 23 21:58:04 - [DEBUG] create_ssl 61.219.131.118 fail:timed out cost:2001 h:0

May 23 21:58:04 - [DEBUG] get ip:218.253.0.163 t:749
May 23 21:58:05 - [DEBUG] create_ssl 216.58.221.19 fail:timed out cost:2000 h:0
May 23 21:58:05 - [DEBUG] create_ssl 218.253.0.144 fail:timed out cost:2000 h:0
May 23 21:58:05 - [DEBUG] get ip:1.179.250.30 t:747
May 23 21:58:05 - [DEBUG] create_ssl 64.233.177.157 fail:timed out cost:2000 h:0

May 23 21:58:05 - [DEBUG] create_ssl 218.176.242.88 fail:timed out cost:2000 h:0

May 23 21:58:05 - [DEBUG] get ip:64.233.181.81 t:747
May 23 21:58:05 - [DEBUG] get ip:1.179.249.168 t:747
May 23 21:58:06 - [DEBUG] create_ssl 111.168.255.178 fail:timed out cost:2000 h:
0
May 23 21:58:06 - [DEBUG] get ip:218.176.242.24 t:747
May 23 21:58:06 - [DEBUG] get ip:216.58.196.54 t:747
May 23 21:58:06 - [DEBUG] get ip:24.156.131.30 t:747
May 23 21:58:06 - [DEBUG] get ip:216.58.221.67 t:747
May 23 21:58:06 - [DEBUG] create_ssl 64.15.116.245 fail:timed out cost:2000 h:0
May 23 21:58:06 - [DEBUG] create_ssl 218.253.0.163 fail:timed out cost:2000 h:0
May 23 21:58:07 - [DEBUG] get ip:64.15.112.153 t:747
May 23 21:58:07 - [DEBUG] create_ssl 1.179.250.30 fail:timed out cost:2000 h:0
May 23 21:58:07 - [DEBUG] create_ssl 64.233.181.81 fail:timed out cost:2000 h:0
May 23 21:58:07 - [DEBUG] get ip:118.174.27.39 t:747
May 23 21:58:07 - [DEBUG] create_ssl 1.179.249.168 fail:timed out cost:2001 h:0
May 23 21:58:07 - [DEBUG] get ip:193.90.147.121 t:747
May 23 21:58:08 - [DEBUG] create_ssl 218.176.242.24 fail:timed out cost:2000 h:0

May 23 21:58:08 - [DEBUG] create_ssl 216.58.196.54 fail:timed out cost:2000 h:0
May 23 21:58:08 - [DEBUG] get ip:218.176.242.98 t:747
May 23 21:58:08 - [DEBUG] create_ssl 24.156.131.30 fail:timed out cost:2000 h:0
May 23 21:58:08 - [DEBUG] create_ssl 216.58.221.67 fail:timed out cost:2000 h:0
May 23 21:58:08 - [DEBUG] get ip:74.125.194.97 t:747
May 23 21:58:08 - [DEBUG] get ip:64.15.119.141 t:748
May 23 21:58:09 - [DEBUG] create_ssl 64.15.112.153 fail:timed out cost:2000 h:0
May 23 21:58:09 - [DEBUG] get ip:118.174.25.88 t:748
May 23 21:58:09 - [DEBUG] get ip:203.117.35.158 t:748
May 23 21:58:09 - [DEBUG] get ip:118.174.27.187 t:748
May 23 21:58:09 - [DEBUG] get ip:210.139.253.226 t:748
May 23 21:58:09 - [DEBUG] create_ssl 118.174.27.39 fail:timed out cost:2000 h:0
May 23 21:58:09 - [DEBUG] create_ssl 193.90.147.121 fail:timed out cost:2000 h:0

May 23 21:58:10 - [DEBUG] get ip:210.139.253.216 t:748
May 23 21:58:10 - [DEBUG] create_ssl 218.176.242.98 fail:timed out cost:2000 h:0

May 23 21:58:10 - [DEBUG] create_ssl 74.125.194.97 fail:timed out cost:2000 h:0
May 23 21:58:10 - [DEBUG] get ip:216.58.218.210 t:748
May 23 21:58:10 - [DEBUG] create_ssl 64.15.119.141 fail:timed out cost:2000 h:0
May 23 21:58:10 - [DEBUG] get ip:197.199.253.38 t:748
May 23 21:58:10 - [INFO] module goagent stopped
May 23 21:58:10 - [INFO] begin to exit web control
May 23 21:58:11 - [INFO] launcher web control exited.

**Comment by evilstyle** [comment]
不要有中文路径 ！
