### ISSUE TITLE
编译lantern大家玩玩，免费版。

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#3846]
新版lantern不是收费了嘛！这里发个自编译版大家玩玩，去弹窗，默认关闭pac，另，不是收费版，不是收费版！重要的事说两遍。
 linux和windows两版，
下载：
https://github.com/yeahwu/recycle-bin/files/359575/7.11.y.lantern.tar.gz
另，启动不了，或者速度慢的童鞋请删除yaml文件后，再启动。

**Comment by lazureice** [comment]
THX.
====
lantern也收费,我就这表情
←
====
先试试现在lantern速度如何

**Comment by jzp820927** [comment]
免费版会限速 20 kbps 意义不大。

**Comment by yeahwu** [comment]
这个版本不会。
天朝屁民 <notifications@github.com>于2016年7月12日 周二23:08写道：

**Comment by hcym** [comment]
速度一直不行

放弃了

**Comment by yeahwu** [comment]
速度是大不如去年了，去年那速度感人！
hcym <notifications@github.com>于2016年7月12日 周二23:21写道：

**Comment by jzp820927** [comment]
官方论坛说了，包括 2.xx 的老版本，和 3.xx 的免费版，都会限速 20kbps，这个应该不会有假。只是不知道现在有没有开始执行，不过最后肯定会执行的。而且他限速肯定是在 服务端限速，不会在客户端。这个观察下流量应该就能确定了。

**Comment by yjd** [comment]
竟然收费了。。。不过现在转自建ss了。也用不上

**Comment by panzer1313208** [comment]
lantern的官方人员我真的对他们呵呵哒了

**Comment by panzer1313208** [comment]
我已经决定抵制lantern了

**Comment by panzer1313208** [comment]
@yeahwu @jzp820927

**Comment by panzer1313208** [comment]
情况是这样的，我从他们的github里发群号，然后几个人跳出来说我这是发广告，说我从群里卖SS【我就笑了，lantern的github里全都是要退钱和反映不能用的，管理员只会说请上传log。】，我就纳闷了，群里人想买SS，我在群里卖SS怎么了？强买强卖了？那傻吊管理员居然禁止我在论坛里发言了。呵呵。

**Comment by panzer1313208** [comment]
![1](https://cloud.githubusercontent.com/assets/13449426/16780184/2679d91c-48a8-11e6-982d-21673e62a3cb.png)
![2](https://cloud.githubusercontent.com/assets/13449426/16780192/2b5fc3ce-48a8-11e6-9445-f8f31edbb250.png)
![3](https://cloud.githubusercontent.com/assets/13449426/16780195/2e6e3208-48a8-11e6-87fb-2bf3ace0ee86.png)
![4](https://cloud.githubusercontent.com/assets/13449426/16780198/3129318c-48a8-11e6-862d-9ef30f069190.png)
![5](https://cloud.githubusercontent.com/assets/13449426/16780200/3363c1f6-48a8-11e6-8fff-abbab64f03cc.png)
![6](https://cloud.githubusercontent.com/assets/13449426/16780202/35c9544c-48a8-11e6-8e93-b95836ab23d4.png)
![7](https://cloud.githubusercontent.com/assets/13449426/16780206/37e680d8-48a8-11e6-819d-31d60e81bbf4.png)
![8](https://cloud.githubusercontent.com/assets/13449426/16780209/3a990af8-48a8-11e6-842b-2647e2d1170d.png)
![9](https://cloud.githubusercontent.com/assets/13449426/16780214/3cba5fb2-48a8-11e6-8e0a-140484fd63e7.png)
![10](https://cloud.githubusercontent.com/assets/13449426/16780217/3e96a192-48a8-11e6-89fe-019cb68b9f89.png)
![11](https://cloud.githubusercontent.com/assets/13449426/16780219/4056a8a6-48a8-11e6-8e53-c9ebc9b6dd8d.png)
![12](https://cloud.githubusercontent.com/assets/13449426/16780221/4214add2-48a8-11e6-87d2-83a4126bb41e.png)

**Comment by sunyik** [comment]
点开没反应啊。。。也不安装也打不开

**Comment by jzp820927** [comment]
我去，这吐槽吐滴，我也是醉了。

**Comment by hehanlin** [comment]
都不容易啊

**Comment by xiaoyan94** [comment]
安卓版的呢

**Comment by xiaoyan94** [comment]
有木有啊😄😄😄

**Comment by jzp820927** [comment]
官方有

**Comment by yeahwu** [comment]
lantern官方github基本上已不更新免费版代码了，收费版没有开源，所以俺也不编译了。
大家还是去用收费版吧！

**Comment by jzp820927** [comment]
可惜了，一个好软件没了。

**Comment by CHN008** [comment]
已经放弃灯笼了.
