### ISSUE TITLE
关于xx-net的一些问题，以及1.14.2的bug

### ISSUE THREAD

**Issue by OnionSalt** [XX-net/XX-Net#385]
1) 1.14.2的ip无法导出，点导出没反应，1.13.6版本的没问题

2) 听说xx-net要运行一段时间才能提速，我今天用1.13.6版，从早上8点左右开始一直使用到大概下午5点左右，看youtube依然超卡，大概缓存1分钟才能播放5秒左右（480p）

3) 听说状态页下的google ip应该是动态更新的，但是运行了大概10个小时左右，google ip一直是3000没变过

4) 对xx-net运行一晚会变快的概念不是很理解，xx-net会自动储存高速ip还是剔除bad ip？如果下载新版本之后这些提速效果如何继承？就比如我用1.13.6运行了10小时（假定提速了），提速效果如何继承到新下载的1.14.2版本中？

5）启动xx-net，有时运行python.exe有时运行pythonw.exe（进程里能看到），这两个文件都在XX-Net-1.14.2\python27\1.0下，这两个程序有什么不同吗？

edit:
最后问个题外话，标题上那些"bug" "help wanted"等有颜色标记的图标是怎么加上去的？

**Comment by xxnet** [comment]
在 2015年5月11日 上午6:57，OnionSalt <notifications@github.com>写道：

> 1) 1.14.2的ip无法导出，点导出没反应，1.13.6版本的没问题
>
有其他人有这个问题吗？我这边正常。


> 2)
> 听说xx-net要运行一段时间才能提速，我今天用1.13.6版，从早上8点左右开始一直使用到大概下午5点左右，看youtube依然超卡，大概缓存1分钟才能播放5秒左右（480p）
>


> 3) 听说状态页下的google ip应该是动态更新的，但是运行了大概10个小时左右，google ip一直是3000没变过
>
总ip数不会增加，找到好的ip，会替换掉慢的ip。

> 4) 对xx-net运行一晚会变快的概念不是很理解，xx-net会自动储存高速ip还是剔除bad
> ip？如果下载新版本之后这些提速效果如何继承？就比如我用1.13.6运行了10小时（假定提速了），提速效果如何继承到新下载的1.14.2版本中？
>
后台会扫描ip，找到好的ip会把慢的剔除。

>
> 5）启动xx-net，有时运行python.exe有时运行pythonw.exe（进程里能看到），这两个文件都在XX-Net-1.14.2\python27\1.0下，这两个程序有什么不同吗？
>
pythonw是没有显示黑色窗口的版本，一般pythonw就够了。python是分析问题看日志用的。

**Comment by yfdyh000** [comment]
这个问题怎么404了，勿删了吗。

第一个问题遇到了一次，报错是：
21:57:40.392 TypeError: title is not a function 127.0.0.1:8085:77:4
21:57:47.327 TypeError: title is not a function 127.0.0.1:8085:117:4
21:57:49.712 TypeError: tip is not a function 127.0.0.1:8085:188:0
相关原因应该是：
https://github.com/XX-net/XX-Net/pull/382/files

不过，现在不再重现。猜测原因，js文件被浏览器缓存。这种更新时加上 ?时间戳或版本号 比较好，强制刷新。

在 2015年5月11日 下午9:43，xxnet <notifications@github.com>写道：

> 在 2015年5月11日 上午6:57，OnionSalt <notifications@github.com>写道：
>
> > 1) 1.14.2的ip无法导出，点导出没反应，1.13.6版本的没问题
> >
> 有其他人有这个问题吗？我这边正常。
>
>
> > 2)
> >
> 听说xx-net要运行一段时间才能提速，我今天用1.13.6版，从早上8点左右开始一直使用到大概下午5点左右，看youtube依然超卡，大概缓存1分钟才能播放5秒左右（480p）
>
> >
>
>
> > 3) 听说状态页下的google ip应该是动态更新的，但是运行了大概10个小时左右，google ip一直是3000没变过
> >
> 总ip数不会增加，找到好的ip，会替换掉慢的ip。
>
> > 4) 对xx-net运行一晚会变快的概念不是很理解，xx-net会自动储存高速ip还是剔除bad
> > ip？如果下载新版本之后这些提速效果如何继承？就比如我用1.13.6运行了10小时（假定提速了），提速效果如何继承到新下载的1.14.2版本中？
> >
> 后台会扫描ip，找到好的ip会把慢的剔除。
>
> >
> >
> 5）启动xx-net，有时运行python.exe有时运行pythonw.exe（进程里能看到），这两个文件都在XX-Net-1.14.2\python27\1.0下，这两个程序有什么不同吗？
>
> >
> pythonw是没有显示黑色窗口的版本，一般pythonw就够了。python是分析问题看日志用的。
>
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/XX-net/XX-Net/issues/385>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/385#issuecomment-100912060>.
>



-- 
Best regards,
YFdyh000.

**Comment by Hslim94** [comment]
1.14.2 同样出现ip无法导入导出。
1.14.1可以
还有里面的ip怎么删除，我改那个proxy.ini 文件里面最大ip数据 2000后，没有用。ip在怎样的情况下才会被删除？不能手动删除么 这样就不能添加自己的ip了

**Comment by xxnet** [comment]
不会不能增加ip，导入ip后，会把最慢的挤掉而已。

总的ip数控制在3000个。

如果真好删除，可以把data/goagent/good_ip.txt置为空文件再重启。

在 2015年5月12日 上午12:58，Hslim <notifications@github.com>写道：

**Comment by OnionSalt** [comment]
无法导出ip的原因可能真的跟yfdyh000说的一样，我清除了chrome的浏览数据（具体应该清除哪些不是很清楚，所以就全部清除了），然后就可以正常导出ip了。

**Comment by xxnet** [comment]
原因是新版的js内容变了，而缺乏触发js更新的机制导致。


在 2015年5月12日 上午5:33，OnionSalt <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
issue回来了，重发一遍内容：

> 这个问题怎么404了，勿删了吗。
> 
> 第一个问题遇到了一次，报错是：
> 21:57:40.392 TypeError: title is not a function 127.0.0.1:8085:77:4
> 21:57:47.327 TypeError: title is not a function 127.0.0.1:8085:117:4
> 21:57:49.712 TypeError: tip is not a function 127.0.0.1:8085:188:0
> 相关原因应该是：
> https://github.com/XX-net/XX-Net/pull/382/files
> 
> 不过，现在不再重现。猜测原因，js文件被浏览器缓存。这种更新时加上 ?时间戳或版本号 比较好，强制刷新。

引用.js的后面加上 ?新的数值 就能避免缓存了。
#382 @zjhzxhz

**Comment by xxnet** [comment]
恩，能否提交个patch，原理了解，不过没有实操过

在 2015年5月12日 上午5:59，YFdyh000 <notifications@github.com>写道：

**Comment by zjhzxhz** [comment]
这是浏览器缓存的问题, 你Ctrl + F5清除以下浏览器缓存就好~
那我一会儿提交一个Pull Request吧.
