### ISSUE TITLE
大前天成功部署，IP地址今天一查居然是本地？

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#3856]
已成功解决

**Comment by yeahwu** [comment]
很正常，本地不走代理，智能pac就是干这分流的。
这只是一个代理工具，并没有匿名功能。想匿名请用tor或者x-tunnel
而且看你的描述，大概对匿名也没什么概念，平时翻翻墙，不是犯罪！
了解？
80068 <notifications@github.com>于2016年7月13日 周三23:55写道：

**Comment by panzer1313208** [comment]
@yeahwu 蓝灯太不要脸了，唉
