### ISSUE TITLE
使用xtunnel速度是否会变快？

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#3858]
因为现在用gaeproxy速度不稳定比较蛋疼，没法看直播什么的，所以问一下。
另外是否有方法不用手机号注册google账号？

**Comment by jzp820927** [comment]
xtunnel 的流量是通过 GAE 传输的，所以 xtunnel 的速度，完全取决于 GAE

**Comment by okgoogle** [comment]
我这里最近一个星期gae的速度下降了（全天候），而一个星期前凌晨时段gae的速度能达到带宽速度，现在不行了。不知道是否个例。

**Comment by jzp820927** [comment]
那你现在 GAE 速度是多少

**Comment by Temmie-hOi** [comment]
那么就是说xtunnel并不会比gae速度快？那这样的话xtunnel的优势是什么？以及如何提升gae速度？

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/wiki/X_Tunnel%E4%BB%8B%E7%BB%8D
