### ISSUE TITLE
连接超时，先休息一会再来！

### ISSUE THREAD

**Issue by harryhkyy** [XX-net/XX-Net#386]
May 11 19:30:23 - [WARNING] gae_exception:GAE_Exception() https://www.facebook.com/ai.php?aed=AQJZ0hLcPWMLBmi0u3RvkcnJNRhAuKcsAvDSE_Fb9hNfq7C9Cp3_t90ijfmQVI5jzW80mX4yZHIuER7YANyi90m58pfRQ0oEnGQPXdZK_uA9VCeDBRFq-8ej3S4MZXeMWzB85Tw645-NzW2W87MDxD1zlpLje-E6eMpHBOdpUmStfyZGkmoQ3iVJ-CUWW14YoQIy5aeAARB5hIP8Q7SgPvMWTqZPBi8oN6cxy0YGjpCU2LMKim3gr_ZZOAJuSCpC5kW6ySxOQUGBXtuaWS23VksJGC4jczceVtS5bzO4BQU5WARhr7gAdqSHf_Ht5JXLKeIH7YUzIFnaSkMPb75l-Ldo-UbKTINBNo9s6_NgSnja_fq3V35voL0kSap9L9e9oq8DdbG82ptLbZ0lEBNjnUlf7doP3i4NPEkhFnp08xvDE6cvJ3G8EBR1qyDSHfBlW8dx3pbKvL_YqPSqwd-p1ALc8MTEAnKsQ3vFdtJtFtONEJrDUyyxaU7-uctPZFmV8-yNFuswGkGp5_ZPeda0FYmW5M0M5amHfkWB6FP3WKV5d1cVsuHJ17KQNeWhBS1D4Ny0oLI-S8EIzIVaBkymfTWfYzNDlhajIkMr6JG-Xz4JYBiGr_16q-toK9d7o8nZLX2luxT6toFAHZ5oZjkhyYRS-vkfWHC1YUL2q-3AuX7mapoDGy_KDLZevHIZdmJinLGQWq861CkUNiM5sdeLvSP2lP4U_VF81A4Rdvku1YMDPdXIJIY5NVcvITPeYC-huabb50SXupPRzQBxdEFjueYJ8NLy6dkFp57M1lOrkcbJfDxPv0Vi_uKU8QBCGQuDnxZwy3Kis-f7yucb19kjtgEsNHs1VB4ukm9bmDjoLfGf_HmMZ2WszDFLSWVP4B-FwGWcKs-zigwA6wKzIXqBr_po_2KTb1Yp9r-h8xXTTFlKXGIT3UZc90cCufh7mZaHPGs2LmSg1M3VR5Qmi89xr3VJ7X_ylpBX8iaoCz_yGl7kMcg9gzVrcB_H6B84iaW5g4rrOgijnwjyz6UMewOPQWEqDmhlhs_QhQqmWos8V0hSZWCaSHkhbqwUJdZdBxJDHYHOKWo5mkIYHa9nLjnPpxTUhUNyBEpGPwbjsW_VPL3lUGfkB-S21Zl595VOtuVhRbHjoCkHN0N93Zj3czVcSf_Oj-_3fJBbXnzEsJS9MNEjraJKLw6antm5cA5FjFiIoVmw4aPdXuB0prcV8iYY0FPcydj_65HJIrOUFGVermmEf39epczBmqHZOKlUKaJaeJH-PmVeIg0MuILk5H_MUMfmFbsD1fiPxnm7asSjKSXpbQHRXxzSw3bRAwD5H4RQl-WYIl7bfaI0g-PM86eblPy3-3cLmCNQOnJE_lVm_3VP43HROVo06YbGe3aeNx0DsmRiUqiegsaWTWR1qAzMzNqsgB2kiGG4Aw_EN_uCz8CdxPn_YFFLRs41d766Ud1OPcAc6a9lEuV747Sjx-gNrr2uxFonlp6RFXKO8Gh_dAoy4oAxT5orKIWIbxtdYVJuFQbIHVl3C_EFhB0-ACby0N8KR7JwIzJsodaBZyaHL6VVqsLcPee47v1CFF9ShmjXImMyTKg_rogjm3PyCgvkPbr8IEshbhBKxZdtjCLUHEZJHEXaMMLIJBZChIWZWCdZR2zdR1Bv-3uFgYc7aVUcxWIc5J2xfob_CqNSseIvcvwFbBOP9mkqMDFLhORW0V5A5RkYtqcU6qkArK-S91GNxShB8qLw2GiZ0JrhlnU-T81Wq5Ktc41LXq0USsdiQT2qlFpyLMhcL-3t9HQYXHYE3UVVL3zmVwAnsL5zERl-0hp0Fap_6FQAZleiyZ1FomeUjGfyfS2Yz5nEVnUhtP4BBHRuc4Bwj6lvPM2i_xxQu3ugK86eSau63efwE7ZDRolEGEmcbKFy6kWgmhVjlQTrCRV247DDswvnn3cFZWGOriq4tWTSLbr1poNsKCeP7pxHT8ZU4DupEX5j-LI0AdUIbbYyQFt16_OqdXsDLaaN_S5OaJeTpv5q43KRYXL6RfpXdWuA_bSKu99zzJqtQgJ12hroHKCvMUpIUpJJtZVp0g8kOC46jYaIAr6IHHpx6JwieHO3NLjLErWSC1y31bcgQSOZmGrqnuJSTC5VdmCHMPF1RtDaTcH7cyvhez4yFRp2b0oQhB5fZRb_nvtMD5Us1ekWa8W-83EA94-ajKwUDCK8jLJNOyjGsKTCIm914UoWBGShqgHyuxA94_5xCkAjFFW0LOeM97UkuCdd7r4f141y2l9-1beL3_bDypStVCYtM81Gf6NogH6OiA1ulIjGGhXGOriXFNBeSZ16ZIWE54dV3NCcV0d1ysnNpx8Ab3dRjjBqu2zIyhLeQtg8B2hibfojGHKv6QL0oNJ_FXH8Q4nf7IqsBg71zkpyNVdXyVxABROn6I4g37WxZjggtQHx4QjLqOklUudtEsAoSEZTwD3VaujmNdQzxcOO4ubN-PTMudOpkwwcnX8mPEG0_Lpl15oRWfPBERqBijM0917x6dWl-eSxFZ0-y47uFR8E6_9iniGngf_0_Ec2RQvYqBU4a74XAlM6XYEHprWqOxDUxJFcmBW3xu5-8bu5n4STaG-TfQ-jpa62Ji4R960V9z8ZM4ElD7NtjfySQfPFTjfetwsHWicYCXjmexVcdBqLViGvy2Ez-MjhI_TZpdHyukMaoOi4dPKEgyRelKg96xFfSN5FvTOp-aN9HhAd9ZiHmmYKhbu8lBjbAklThb4MoVh13_PVmluRxpaj6ww36wsm0prN95aGAuk0Sviz80KSUFPCVgcyluzO9mzKrO2fWkzovOOgypzsJShReVI_CqEpVFMIQM6hH6qYt5XWibx_QNQtIiOnK_OPeA7ZUxHFtjFmBy0SSncucFhkIZd7Npn4TPg6FrEsp9fN09gD_We0Fl_EmsKRScCLe47ZWaJH5KgLbjFxxGGz--LdpZq-EnuKHp3rbrO-J-19K0aLY1WmWLjVJVH7v4JobxgEOwyvq75ZxtQOcp3tKOSuOETay9YJG-fYXjaGy12h2Rd51zXalYoo109lfP665gBWJ6HoQjAun0tsuAxSvLc3-K9Xh7Iygr0yQJnW6wMlNftlX6Z4CY1KTpvorH04m3NnMcPeNPZczfTQJiRKvSOz86X6F4AvlmvalY0AsC7x2Qb6PTfaa1mKgOmjOIgBE9Y98u4i7X-0G3YeL2OYqbjOJFpyrBPGkhD-sQ
May 11 19:30:23 - [DEBUG] get ip:193.134.255.247 t:792
May 11 19:30:23 - [DEBUG] create_ssl 210.153.73.88 fail:timed out cost:2000 h:0
May 11 19:30:23 - [DEBUG] get ip:203.117.36.152 t:792
May 11 19:30:23 - [DEBUG] get ip:203.117.36.173 t:792
May 11 19:30:24 - [DEBUG] get ip:212.188.10.119 t:792
May 11 19:30:24 - [DEBUG] create_ssl 178.45.251.94 fail:timed out cost:2000 h:0
May 11 19:30:24 - [DEBUG] get ip:1.179.249.39 t:792
May 11 19:30:24 - [INFO] GAE t:3506 s:9038 200 https://scontent-ord.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/s200x200/11139966_815797021835493_4987620949068462481_n.jpg?oh=ede1b72eb2ce10e6bfe2a7e5002f788f&oe=56072546
May 11 19:30:24 - [DEBUG]LOG_EXCEPT: create_ssl 203.211.0.49 fail:timed out cost:2000 h:0, Except:[Errno 9] Bad file descriptor
May 11 19:30:24 - [DEBUG] get ip:64.15.126.93 t:793
May 11 19:30:24 - [DEBUG] create_ssl 88.159.13.249 fail:timed out cost:2000 h:0
May 11 19:30:25 - [DEBUG] create_ssl 1.179.249.173 fail:timed out cost:2000 h:0
May 11 19:30:25 - [DEBUG] get ip:118.174.27.93 t:793
May 11 19:30:25 - [DEBUG] create_ssl 193.134.255.247 fail:timed out cost:2000 h:0
May 11 19:30:25 - [DEBUG] get ip:123.205.251.116 t:793
May 11 19:30:25 - [DEBUG] create_ssl 203.117.36.152 fail:timed out cost:2001 h:0
May 11 19:30:25 - [DEBUG] create_ssl 203.117.36.173 fail:timed out cost:2001 h:0
May 11 19:30:25 - [DEBUG] get ip:64.233.186.165 t:793
May 11 19:30:26 - [DEBUG] create_ssl 212.188.10.119 fail:timed out cost:2000 h:0
May 11 19:30:26 - [DEBUG] get ip:193.134.255.20 t:793
May 11 19:30:26 - [DEBUG] create_ssl 1.179.249.39 fail:timed out cost:2000 h:0
May 11 19:30:26 - [DEBUG] get ip:149.3.177.58 t:793
May 11 19:30:26 - [DEBUG] create_ssl 64.15.126.93 fail:timed out cost:2000 h:0
May 11 19:30:26 - [DEBUG] get ip:1.179.252.163 t:793
May 11 19:30:26 - [DEBUG] get ip:118.174.27.238 t:793
May 11 19:30:27 - [DEBUG] get ip:84.235.77.173 t:793
May 11 19:30:27 - [DEBUG] create_ssl 118.174.27.93 fail:timed out cost:2000 h:0
May 11 19:30:27 - [DEBUG] get ip:66.185.84.55 t:793
May 11 19:30:27 - [DEBUG] create_ssl 123.205.251.116 fail:timed out cost:2002 h:0
May 11 19:30:27 - [DEBUG] get ip:24.156.131.94 t:793
May 11 19:30:27 - [DEBUG] create_ssl 64.233.186.165 fail:timed out cost:2000 h:0
May 11 19:30:28 - [DEBUG] create_ssl 193.134.255.20 fail:timed out cost:2002 h:0
May 11 19:30:28 - [DEBUG] get ip:84.235.77.217 t:793
May 11 19:30:28 - [DEBUG] create_ssl 149.3.177.58 fail:timed out cost:2000 h:0
May 11 19:30:28 - [DEBUG] get ip:123.205.251.117 t:794
May 11 19:30:28 - [DEBUG] create_ssl 1.179.252.163 fail:timed out cost:2000 h:0
May 11 19:30:28 - [DEBUG] create_ssl 118.174.27.238 fail:timed out cost:2001 h:0
May 11 19:30:28 - [DEBUG] get ip:64.233.166.152 t:794
May 11 19:30:29 - [DEBUG] create_ssl 84.235.77.173 fail:timed out cost:2000 h:0
May 11 19:30:29 - [DEBUG] get ip:203.211.0.50 t:794
May 11 19:30:29 - [DEBUG] create_ssl 66.185.84.55 fail:timed out cost:2000 h:0
May 11 19:30:29 - [DEBUG] get ip:64.15.126.161 t:794
May 11 19:30:29 - [DEBUG] create_ssl 24.156.131.94 fail:timed out cost:2000 h:0
May 11 19:30:29 - [DEBUG] get ip:149.126.86.48 t:794
May 11 19:30:29 - [DEBUG] get ip:149.126.86.49 t:794
May 11 19:30:30 - [DEBUG] get ip:118.143.88.37 t:794
May 11 19:30:30 - [DEBUG] create_ssl 84.235.77.217 fail:timed out cost:2000 h:0
May 11 19:30:30 - [DEBUG] get ip:83.94.121.153 t:794
May 11 19:30:30 - [DEBUG] create_ssl 123.205.251.117 fail:timed out cost:2000 h:0
May 11 19:30:30 - [DEBUG] sort ip time:8
May 11 19:30:30 - [DEBUG] get ip:149.126.86.59 t:798
May 11 19:30:30 - [DEBUG] create_ssl 64.233.166.152 fail:timed out cost:2000 h:0
May 11 19:30:31 - [DEBUG] create_ssl 203.211.0.50 fail:timed out cost:2000 h:0
May 11 19:30:31 - [DEBUG] get ip:60.199.175.53 t:798
May 11 19:30:31 - [DEBUG] create_ssl 64.15.126.161 fail:timed out cost:2000 h:0
May 11 19:30:31 - [DEBUG] get ip:118.143.88.88 t:798
May 11 19:30:31 - [DEBUG] create_ssl 149.126.86.48 fail:timed out cost:2000 h:0
May 11 19:30:31 - [DEBUG] create_ssl 149.126.86.49 fail:timed out cost:2000 h:0
May 11 19:30:31 - [DEBUG] get ip:64.15.126.109 t:794
May 11 19:30:32 - [DEBUG] create_ssl 118.143.88.37 fail:timed out cost:2000 h:0
May 11 19:30:32 - [DEBUG] get ip:111.168.255.153 t:794
May 11 19:30:32 - [DEBUG] create_ssl 83.94.121.153 fail:timed out cost:2000 h:0
May 11 19:30:32 - [DEBUG] get ip:212.188.7.221 t:794
May 11 19:30:32 - [DEBUG] create_ssl 149.126.86.59 fail:timed out cost:2000 h:0
May 11 19:30:32 - [DEBUG] get ip:64.233.184.133 t:794
May 11 19:30:32 - [DEBUG] get ip:64.233.182.102 t:795
May 11 19:30:33 - [DEBUG] get ip:203.117.34.178 t:795
May 11 19:30:33 - [DEBUG] create_ssl 60.199.175.53 fail:timed out cost:2000 h:0
May 11 19:30:33 - [DEBUG] get ip:123.205.250.88 t:795
May 11 19:30:33 - [DEBUG] create_ssl 118.143.88.88 fail:timed out cost:2000 h:0
May 11 19:30:33 - [DEBUG]LOG_EXCEPT: get ip:1.179.251.104 t:796, Except:[Errno 9] Bad file descriptor
May 11 19:30:33 - [DEBUG] create_ssl 64.15.126.109 fail:timed out cost:2000 h:0
May 11 19:30:34 - [DEBUG] create_ssl 111.168.255.153 fail:timed out cost:2000 h:0
May 11 19:30:34 - [DEBUG] get ip:203.211.0.44 t:796
May 11 19:30:34 - [DEBUG] create_ssl 212.188.7.221 fail:timed out cost:2000 h:0
May 11 19:30:34 - [DEBUG] get ip:103.1.139.177 t:796
May 11 19:30:34 - [DEBUG] create_ssl 64.233.184.133 fail:timed out cost:2003 h:0
May 11 19:30:34 - [DEBUG] create_ssl 64.233.182.102 fail:timed out cost:2001 h:0
May 11 19:30:34 - [DEBUG] get ip:203.117.36.182 t:796
May 11 19:30:35 - [DEBUG] create_ssl 203.117.34.178 fail:timed out cost:2001 h:0
May 11 19:30:35 - [DEBUG] get ip:118.174.25.25 t:796
May 11 19:30:35 - [DEBUG] create_ssl 123.205.250.88 fail:timed out cost:2000 h:0
May 11 19:30:35 - [DEBUG] get ip:193.120.166.84 t:796
May 11 19:30:35 - [DEBUG] create_ssl 1.179.251.104 fail:timed out cost:2001 h:0
May 11 19:30:35 - [DEBUG] get ip:193.192.226.172 t:796
May 11 19:30:35 - [DEBUG] get ip:202.39.143.25 t:796
May 11 19:30:36 - [DEBUG] get ip:123.205.251.86 t:796
May 11 19:30:36 - [DEBUG] create_ssl 203.211.0.44 fail:timed out cost:2000 h:0
May 11 19:30:36 - [DEBUG] get ip:64.15.126.244 t:796
May 11 19:30:36 - [DEBUG] create_ssl 103.1.139.177 fail:timed out cost:2000 h:0
May 11 19:30:36 - [DEBUG] get ip:111.168.255.163 t:797
May 11 19:30:36 - [DEBUG] create_ssl 203.117.36.182 fail:timed out cost:2000 h:0
May 11 19:30:37 - [DEBUG] create_ssl 118.174.25.25 fail:timed out cost:2001 h:0
May 11 19:30:37 - [DEBUG] get ip:197.199.254.57 t:797
May 11 19:30:37 - [DEBUG] create_ssl 193.120.166.84 fail:timed out cost:2001 h:0
May 11 19:30:37 - [DEBUG] get ip:84.235.77.108 t:797
May 11 19:30:37 - [DEBUG] create_ssl 193.192.226.172 fail:timed out cost:2001 h:0
May 11 19:30:37 - [DEBUG] create_ssl 202.39.143.25 fail:timed out cost:2001 h:0
May 11 19:30:37 - [DEBUG] get ip:193.134.255.50 t:797
May 11 19:30:38 - [DEBUG] create_ssl 123.205.251.86 fail:timed out cost:2000 h:0
May 11 19:30:38 - [DEBUG] get ip:74.125.192.96 t:797
May 11 19:30:38 - [DEBUG] create_ssl 64.15.126.244 fail:timed out cost:2000 h:0
May 11 19:30:38 - [DEBUG] get ip:106.162.216.94 t:797
May 11 19:30:38 - [DEBUG] create_ssl 111.168.255.163 fail:timed out cost:2000 h:0
May 11 19:30:38 - [DEBUG] get ip:212.188.15.163 t:797
May 11 19:30:38 - [DEBUG] get ip:64.233.181.156 t:797
May 11 19:30:39 - [DEBUG] get ip:173.194.122.13 t:798
May 11 19:30:39 - [DEBUG] create_ssl 197.199.254.57 fail:timed out cost:2000 h:0
May 11 19:30:39 - [DEBUG] get ip:118.174.27.55 t:798
May 11 19:30:39 - [DEBUG] create_ssl 84.235.77.108 fail:timed out cost:2001 h:0
May 11 19:30:39 - [DEBUG] get ip:203.117.37.148 t:798
May 11 19:30:39 - [DEBUG] create_ssl 193.134.255.50 fail:timed out cost:2000 h:0

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_TW
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.14.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	harryhky|harryhkyy|harryhkyy2|harryhkyy3|harryhkyy4|harryhkyy5|harryhkyy6|harryhkyy7|harryhkyy8|harryhkyy9|harryhkyy10|harryhkyy11|harryhkyy12|harryhkyy13|harryhkyy14|harryhkyy15|harryhkyy16|harryhkyy17|harryhkyy18|harryhkyy19|harryhkyy20|harryhkyy21|harryhkyy22|harryhkyy23|harryhkyy24|harryhkyy25|harryhkyy26|harryhkyy27|harryhkyy28|harryhkyy29|harryhkyy30|harryhkyy31|harryhkyy32|harryhkyy33|harryhkyy34|harryhkyy35|harryhkyy36|harryhkyy37|harryhkyy38|harryhkyy39|harryhkyy40|harryhkyy41|harryhkyy42|harryhkyy43|harryhkyy44|harryhkyy45|harryhkyy46|harryhkyy47|harryhkyy48|harryhkyy49|Out|of|Quota
Out of Quota appids	
Not Exist appids	appids
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	3000
connected link(帮助)	0,1
ip-connect-interval	10
scan ip thread num	0
block stat(帮助)	OK

**Comment by Cat7373** [comment]
亲标题短点可以不。。。

**Comment by xxnet** [comment]
使用上有什么问题？

2015-05-11 7:31 GMT-04:00 harryhkyy <notifications@github.com>:

**Comment by harryhkyy** [comment]
用不了 FACEBOOK YOUTUBE GOOGLE等等都上不了

**Comment by harryhkyy** [comment]
scan ip thread num 長期是0

**Comment by superjyq** [comment]
用老版本啊，一直没更新，用的很流畅

**Comment by boromeke** [comment]
我这里也是，又开始上不了 “连接超时，先休息一会再来！”

**Comment by shufecrystal** [comment]
我也是这问题 connected link 为0,0

**Comment by xxnet** [comment]
请问是什么地区，什么接入商？

把扫描ip的线程数开到50，看能否改善

2015-05-12 0:23 GMT-04:00 shufecrystal <notifications@github.com>:

**Comment by harryhkyy** [comment]
开到50了 沒有改善
福建泉州電信 
connected link(帮助)	0,0

**Comment by xxnet** [comment]
扫描ip里，贴上蛤蟆的段试试：
103.246.0.0/16
104.132.0.0/16
104.135.0.0/16
104.154.0.0/16
104.155.0.0/16
104.196.0.0/16
104.199.0.0/16
107.167.0.0/16
107.178.0.0/16
107.188.0.0/16
108.170.0.0/16
108.177.0.0/16
108.59.0.0/16
109.114.0.0/16
113.21.0.0/16
12.216.0.0/16
123.202.0.0/16
129.60.0.0/16
130.211.0.0/16
132.185.0.0/16
142.250.0.0/16
142.251.0.0/16
146.148.0.0/16
149.193.0.0/16
149.3.0.0/16
15.176.0.0/16
162.222.0.0/16
171.147.0.0/16
172.217.0.0/16
172.253.0.0/16
173.192.0.0/16
173.194.0.0/16
173.227.0.0/16
173.255.0.0/16
19.217.0.0/16
192.104.0.0/16
192.119.0.0/16
192.158.0.0/16
192.178.0.0/16
192.179.0.0/16
192.200.0.0/16
193.120.0.0/16
193.142.0.0/16
193.186.0.0/16
193.51.0.0/16
195.22.0.0/16
198.159.0.0/16
199.18.0.0/16
199.192.0.0/16
199.223.0.0/16
199.28.0.0/16
200.202.0.0/16
206.169.0.0/16
207.223.0.0/16
208.74.0.0/16
209.85.0.0/16
212.113.0.0/16
212.188.0.0/16
213.144.0.0/16
213.152.0.0/16
213.186.0.0/16
213.200.0.0/16
216.21.0.0/16
216.239.0.0/16
216.252.0.0/16
216.58.0.0/16
217.163.0.0/16
217.30.0.0/16
23.228.0.0/16
23.236.0.0/16
23.251.0.0/16
23.255.0.0/16
32.253.0.0/16
38.106.0.0/16
38.107.0.0/16
38.98.0.0/16
4.3.0.0/16
41.206.0.0/16
45.56.0.0/16
5.210.0.0/16
52.115.0.0/16
62.116.0.0/16
62.231.0.0/16
62.78.0.0/16
64.233.0.0/16
64.68.0.0/16
64.9.0.0/16
66.102.0.0/16
66.249.0.0/16
70.32.0.0/16
72.14.0.0/16
74.125.0.0/16
74.94.0.0/16
77.67.0.0/16
8.15.0.0/16
8.34.0.0/16
8.35.0.0/16
8.6.0.0/16
8.8.0.0/16
80.149.0.0/16
80.227.0.0/16
80.228.0.0/16
80.239.0.0/16
85.233.0.0/16
86.127.0.0/16
88.204.0.0/16
89.207.0.0/16
89.83.0.0/16
90.84.0.0/16
92.241.0.0/16
95.80.0.0/16
99.198.0.0/16

2015-05-12 8:01 GMT-04:00 harryhkyy <notifications@github.com>:

**Comment by harryhkyy** [comment]
改了後 正常了

**Comment by xxnet** [comment]
扫描到新的ip了吗？


2015-05-12 8:18 GMT-04:00 harryhkyy <notifications@github.com>:

**Comment by harryhkyy** [comment]
對

**Comment by xxnet** [comment]
看来这批ip有效果啊，我把他们都加进去吧

2015-05-12 8:23 GMT-04:00 harryhkyy <notifications@github.com>:

**Comment by e-mailky** [comment]
这个IP在哪里加,,能详细说说吗?
@xxnet

**Comment by xxnet** [comment]
UI界面上的扫描ip里，在后面增加就好了。

最新版已经加进去了。

2015-05-12 22:36 GMT-04:00 Ling <notifications@github.com>:

**Comment by mochen91** [comment]
我这里也是，504超时。是在导入IP那里添加吗？那个蛤蟆IP段怎么加，直接复制的话，导入成功为0。

**Comment by mochen91** [comment]
@xxnet  我这里也是，504超时。是在导入IP那里添加吗？那个蛤蟆IP段怎么加，直接复制的话，导入成功为0。

**Comment by xxnet** [comment]
在扫描ip那里添加。

新版已经加了蛤蟆ip段在后面，可以拉到最后面看看

在 2015年5月16日 下午10:26，mochen91 <notifications@github.com>写道：

**Comment by mochen91** [comment]
@xxnet  嗯 我使用的是在官网下载的旧版，没有升级。现在好了~谢谢

**Comment by redstoneleo** [comment]
自己想找一些好IP加进去，然后看看能否访问
https://appengine.google.com
如果还是了问题就说明没有好IP，找到好IP才行啊
