### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by yaoguaishou** [XX-net/XX-Net#3865]
表现:
1.在首页推送google chrome
2.在首页请求设为主页
3.部分网址被屏蔽，但是没有给出提醒
例如
[177pic漫画](http://www.177pic.info/) 无法搜索到站内页面
4.图片搜索过滤更加严格
5.同一关键词在不同语言下，不同地区站点下搜索结果数量不一，且与安全搜索无关

**Comment by yaoguaishou** [comment]
chrome也越来越不好用了

**Comment by jzp820927** [comment]
不明觉厉

**Comment by drg78rnvgh** [comment]
chrome越来越不好用就是真。对低配电脑是个灾难.....
用回360浏览器了

**Comment by jzp820927** [comment]
chrome 对内存占用确实高

**Comment by lazureice** [comment]
(所以为啥发在这里...)

推送/设主页是之前的事吧,我今天打开已经没有了.

关于177,你google这两个TAG:
 [鬼窪浩久] 隷嬢未亡人 真理子
 [鬼窪浩久] 美畜淫婦 真理子

图搜,用的少(一般我用http://saucenao.com/),不清楚.过滤啥?政治,色情?

5.现在数量确实不一样呢,以前是一样的?
eg:fuck
cn:找到约 1,320,000,000 条结果
en:About 1,330,000,000 results
但第一页结果是差不多的.
话说你具体举几个例子呗,看看对搜索结果影响有多大.

至于浏览器,chrome占用高是事实,但占用没它高的也不是各方面都优于它嘛.
虽然我觉得chrome占用应该可以更低一点的,但人家注重的好像是速度,简洁,安全.
随便,坐等53

**Comment by jzp820927** [comment]
我是 chrome 铁粉，占用高，也一直用

**Comment by liangshi** [comment]
opera飘过，应用基本兼容，资源占用少

**Comment by nly4lov** [comment]
我是打酱油的

**Comment by dlzdwxdt** [comment]
把安全搜索给关掉，不要用google.hk

**Comment by pendave** [comment]
内存占用非常高！

有没有能替代的其他浏览器啊？

**Comment by pendave** [comment]
安全搜索 为啥我关不掉？有方法吗？

**Comment by jzp820927** [comment]
不会是古董电脑吧，一般的配置，这个内存影响不大
