### ISSUE TITLE
一自动更新，原来超过3000个的goodip.txt，变回3000去了

### ISSUE THREAD

**Issue by lg560852** [XX-net/XX-Net#387]
更新时是不是覆盖了？

**Comment by lg560852** [comment]
是不是更新后，删除本地的proxy.ini文件夹，然后新的版本在download下，读取还是原来的\XX-Net\data\goagent下的配置？然后我因为改的是goagent文件夹下的proxy.ini，所以IP上限更新后变回3000，超出的就删除了？

**Comment by xxnet** [comment]
是的，不用去改goagent/x.x.x/local/proxy.ini 这个目录会被覆盖的。

可以手动生成 data/goagent/manual.ini，把要改的字段放里面

在 2015年5月11日 下午8:01，lg560852 <notifications@github.com>写道：

**Comment by lg560852** [comment]
明白了，以后更改这里，多谢多谢

**Comment by KevinLeung007** [comment]
我一检测最新版本，就发生未知错误, 请刷新页面重试.这是为什么？

**Comment by xxnet** [comment]
请重新开新的bug

在 2015年5月11日 下午11:43，KevinLeung007 <notifications@github.com>写道：
