### ISSUE TITLE
length of URL too long(greater than 2083)

### ISSUE THREAD

**Issue by way-zer** [XX-net/XX-Net#3873]
最近使用XX-Net,点谷歌验证码时总是400,点开链接发现

> length of URL too long(greater than 2083)

`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2604
network-status: OK
connected-link: new:2 used:0
worker: h1:22 h2:3
scan-ip-thread-num: 50
ip-quality: 198
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by yeahwu** [comment]
把 hosts 里面的`;.google.com`前面的`；`去掉

**Comment by way-zer** [comment]
我在自动切换规则中加了个这个:
UrlRegex: .{2083} +direct

**Comment by jzp820927** [comment]
加了这个就解决问题了？

**Comment by way-zer** [comment]
是的,那句话意思是，超过2083个字符的链接直接连接,避免代理报错

**Comment by jzp820927** [comment]
原来如此，又学习了一个新语法

**Comment by hereiamfreeman** [comment]
UrlRegex: .{2083} +direct这个是在哪里加的? 请求详解
