### ISSUE TITLE
关于[autorange]

### ISSUE THREAD

**Issue by lazureice** [XX-net/XX-Net#3874]
goagent的[autorange]里除了threads和maxsize还有hosts.可以手动添加网站.
xxnet有办法这样做吗?复制到manual.ini里好像并没有用.

> [autorange]
hosts = *.c.youtube.com|*.atm.youku.com|*.googlevideo.com|*av.vimeo.com|smile-*.nicovideo.jp|video.*.fbcdn.net|s*.last.fm|x*.last.fm|*.x.xvideos.com|*.edgecastcdn.net|*.d.rncdn3.com|cdn*.public.tube8.com|videos.flv*.redtubefiles.com|cdn*.public.extremetube.phncdn.com|cdn*.video.pornhub.phncdn.com|*.mms.vlog.xuite.net|vs*.thisav.com|archive.rthk.hk|video*.modimovie.com|*.c.docs.google.com
endswith = .f4v|.flv|.hlv|.m4v|.mp4|.mp3|.ogg|.avi|.dmg|.iso
noendswith = .xml|.json|.html|.php|.py|.js|.css|.jpg|.jpeg|.png|.gif|.ico|.webp
threads = 8
maxsize = 524288
waitsize = 262144

**Comment by yeahwu** [comment]
XX-Net/code/default/gae_proxy/local/proxy.ini

**Comment by lazureice** [comment]
@yeahwu 不是不能编辑吗?

**Comment by jzp820927** [comment]
需要修改的相关内容复制到 manual.ini 文件里面，再修改就可以了

**Comment by lazureice** [comment]
嘛,算了.

我还有另一个问题. @yeahwu 
之前google升级, 导致goagent用不了gvs, 
xxnet完全没受到影响?

**Comment by yeahwu** [comment]
gvs禁用了SHA1的cipher，改了代码。
lazureice <notifications@github.com>于2016年7月16日 周六22:42写道：

**Comment by lazureice** [comment]
了解，谢谢解答
