### ISSUE TITLE
手动输入可用IP

### ISSUE THREAD

**Issue by tossp** [XX-net/XX-Net#388]
RT

今天刚开始用，我要怎么才能把，我在其他地方找到的goa的可用IP直接输入进入生效？
等xx自己扫实在太慢了

**Comment by xxnet** [comment]
可以修复扫描ip的线程数。

UI上有导入ip的界面，直接填好导入就可以了。

在 2015年5月11日 下午11:45，TossPig <notifications@github.com>写道：

**Comment by tossp** [comment]
谢谢
