### ISSUE TITLE
3.25 xx-net mac运行的时候，显示正常，但是用chrome + swichyomega 刷不出网页

### ISSUE THREAD

**Issue by neos2008** [XX-net/XX-Net#3885]
XX-Net Status:

sys-platform: x86_64, Darwin-15.6.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.6.0: Thu Jun 23 18:48:19 PDT 2016; root:xnu-3248.60.10~2/RELEASE_X86_64
os-release: 15.6.0
os-detail: Release:10.11.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:272 good:270
network-status: OK
connected-link: new:2 used:0
worker: h1:23 h2:4
scan-ip-thread-num: 50
ip-quality: 179
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
看状态页没啥异常

**Comment by neos2008** [comment]
是啊，所以才奇怪，有时候会出现
浏览器代理设置	Fail
CA证书状态(下载)	Fail   的情况

**Comment by jzp820927** [comment]
MAC 问题挺多的，没有 MAC 环境，无法定位我，等高手来看看吧

**Comment by zengqlleo** [comment]
你把php proxy模块打开
