### ISSUE TITLE
3.2.5 版本一直自动更新

### ISSUE THREAD

**Issue by jy02534655** [XX-net/XX-Net#3889]
设置了自动升级到测试版，主界面版本号正确。在升级管理界面显示的版本号却是 3.2.4 
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2791
network-status: OK
connected-link: new:2 used:0
worker: h1:22 h2:3
scan-ip-thread-num: 50
ip-quality: 266
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
没遇到过这种奇葩问题

**Comment by jy02534655** [comment]
现在又正常了，奇怪
