### ISSUE TITLE
无法上传appid，一直卡在checking if deployment succeeded

### ISSUE THREAD

**Issue by luckyfatpig** [XX-net/XX-Net#389]
无法上传appid，一直卡在checking if deployment succeeded，以前gae服務端用的是3.2

**Comment by tossp** [comment]
我也是

**Comment by xxnet** [comment]
不重新部署也可以用，看某些视频受影响而已

2015-05-12 0:26 GMT-04:00 TossPig <notifications@github.com>:

**Comment by tossp** [comment]
我看了一下，我的服务器版本应该是
goagent 3.2.0 

goagent原版的。。。最新3.0分支的版本，不会有问题吧？

**Comment by xxnet** [comment]
最好能重新部署，要是能用也可以先用着

在 2015年5月12日 上午1:55，TossPig <notifications@github.com>写道：

**Comment by tossp** [comment]
嗯，刚重新部署失败了，顺便检查了一下当前版
GoAgent 服务端已经在 2014-11-14 03:01:17 升级到 3.2.0 版本, 请更新您的客户端。

**Comment by xxnet** [comment]
服务端3.2 一般够用了

在 2015年5月12日 上午2:21，TossPig <notifications@github.com>写道：

**Comment by Cat7373** [comment]
May 12 15:39:22 - Starting deployment.
May 12 15:39:26 - Checking if deployment succeeded.
May 12 15:39:27 - Will check again in 1 seconds.
May 12 15:39:28 - Checking if deployment succeeded.
May 12 15:39:29 - Will check again in 2 seconds.
May 12 15:39:31 - Checking if deployment succeeded.
May 12 15:39:31 - Will check again in 4 seconds.
May 12 15:39:35 - Checking if deployment succeeded.
May 12 15:39:36 - Will check again in 8 seconds.
May 12 15:39:44 - Checking if deployment succeeded.
May 12 15:39:45 - Will check again in 16 seconds.
May 12 15:40:01 - Checking if deployment succeeded.
May 12 15:40:02 - Will check again in 32 seconds.
May 12 15:40:34 - Checking if deployment succeeded.

差不多的问题- -
一直在重试- -
明天就要去考C1证的科目1惹- -
最近没空研究代码了- -
天天在家练题- -

**Comment by xxnet** [comment]
恩，我研究下

2015-05-12 3:41 GMT-04:00 Cat73 <notifications@github.com>:

**Comment by xxnet** [comment]
定位到问题了，新版引入的一个bug。很快发一个版本。

2015-05-12 5:01 GMT-04:00 Net XX <xxnet.dev@gmail.com>:

**Comment by xxnet** [comment]
新版 1.14.3发布，修复无法部署问题，请升级

2015-05-12 5:13 GMT-04:00 Net XX <xxnet.dev@gmail.com>:

**Comment by tossp** [comment]
好像还是这样啊。。。
顺便我检查了一下`goagent\3.1.49\server\gae\wsgi.py`没有更新RC4密码，这个设定是对的么？
```python
#!/usr/bin/env python
# coding=utf-8
# Contributor:
#      Phus Lu        <phus.lu@gmail.com>

__version__ = '3.0.7'
__password__ = ''
__hostsdeny__ = ()
#__hostsdeny__ = ('.youtube.com', '.youku.com', ".googlevideo.com")
__content_type__ = 'image/gif'
```


Sys Platformwin32OS SystemWindowsOS version6.1.7601OS release7OS
detailVersion:6-1;
Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256;
ProductType:0languagezh_CNarchitecture32bitWindowsPE
XX-Net Version1.14.6Launcher Version1.4.0GoAgent Version3.1.49Python Version
2.7.9
```
May 13 00:07:52 - ============ Begin upload ============
appid:ttlovechina6

May 13 00:07:52 - Application: xxxx6
May 13 00:07:52 - Host: appengine.google.com
May 13 00:07:52 - Rolling back the update.
May 13 00:07:53 - Application: xxxx6; version: 1
May 13 00:07:53 - Host: appengine.google.com
May 13 00:07:53 -
Starting update of app: xxxx6, version: 1
May 13 00:07:53 - Scanning files on local disk.
May 13 00:07:54 - Cloning 5 application files.
May 13 00:07:55 - Compilation starting.
May 13 00:07:55 - Compilation completed.
May 13 00:07:55 - Starting deployment.
May 13 00:07:59 - Checking if deployment succeeded.
May 13 00:07:59 - Will check again in 1 seconds.
May 13 00:08:00 - Checking if deployment succeeded.
May 13 00:08:01 - Will check again in 2 seconds.
May 13 00:08:03 - Checking if deployment succeeded.
May 13 00:08:04 - Will check again in 4 seconds.
May 13 00:08:08 - Checking if deployment succeeded.
May 13 00:08:08 - Will check again in 8 seconds.
May 13 00:08:16 - Checking if deployment succeeded.
May 13 00:08:17 - Will check again in 16 seconds.
May 13 00:08:33 - Checking if deployment succeeded.
May 13 00:08:33 - Will check again in 32 seconds.
May 13 00:09:05 - Checking if deployment succeeded.
May 13 00:09:06 - Will check again in 60 seconds.
May 13 00:10:06 - Checking if deployment succeeded.
May 13 00:10:06 - Will check again in 60 seconds.
```


* 有任何疑问或者建议，请及时联系！ 谢谢！ *






* 砼砼.朱浩 ———————————————————————————— Mobile: +86.13419290962 QQ:156888120
<http://sighttp.qq.com/authd?IDKEY=c31473151092df4e0b8b865644d797cb27595df05699a32e>
WebSite: http://TossP.com <http://tossp.com/>*






*成都晨云信息技术有限责任公司Office: +86.028-81700511Mobile: +86.18980642996QQ:156888120
<http://sighttp.qq.com/authd?IDKEY=c31473151092df4e0b8b865644d797cb27595df05699a32e>
WebSite: http://www.CdMcit.Com
<http://www.cdmcit.com/>Address:四川省成都市光华东三路中铁西城写字楼5栋802*

2015-05-12 17:31 GMT+08:00 xxnet <notifications@github.com>:

**Comment by tossp** [comment]
好像还是这样啊。。。
顺便我检查了一下`goagent\3.1.49\server\gae\wsgi.py`没有更新RC4密码，这个设定是对的么？
```python
#!/usr/bin/env python
# coding=utf-8
# Contributor:
#      Phus Lu        <phus.lu@gmail.com>

__version__ = '3.0.7'
__password__ = ''
__hostsdeny__ = ()
#__hostsdeny__ = ('.youtube.com', '.youku.com', ".googlevideo.com")
__content_type__ = 'image/gif'
```


Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
XX-Net Version	1.14.6
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
```
May 13 00:07:52 - ============ Begin upload ============ 
appid:ttlovechina6 

May 13 00:07:52 - Application: xxxx6
May 13 00:07:52 - Host: appengine.google.com
May 13 00:07:52 - Rolling back the update.
May 13 00:07:53 - Application: xxxx6; version: 1
May 13 00:07:53 - Host: appengine.google.com
May 13 00:07:53 - 
Starting update of app: xxxx6, version: 1
May 13 00:07:53 - Scanning files on local disk.
May 13 00:07:54 - Cloning 5 application files.
May 13 00:07:55 - Compilation starting.
May 13 00:07:55 - Compilation completed.
May 13 00:07:55 - Starting deployment.
May 13 00:07:59 - Checking if deployment succeeded.
May 13 00:07:59 - Will check again in 1 seconds.
May 13 00:08:00 - Checking if deployment succeeded.
May 13 00:08:01 - Will check again in 2 seconds.
May 13 00:08:03 - Checking if deployment succeeded.
May 13 00:08:04 - Will check again in 4 seconds.
May 13 00:08:08 - Checking if deployment succeeded.
May 13 00:08:08 - Will check again in 8 seconds.
May 13 00:08:16 - Checking if deployment succeeded.
May 13 00:08:17 - Will check again in 16 seconds.
May 13 00:08:33 - Checking if deployment succeeded.
May 13 00:08:33 - Will check again in 32 seconds.
May 13 00:09:05 - Checking if deployment succeeded.
May 13 00:09:06 - Will check again in 60 seconds.
May 13 00:10:06 - Checking if deployment succeeded.
May 13 00:10:06 - Will check again in 60 seconds.
```

**Comment by xxnet** [comment]
刚才在Win7下试过，正常。
怀疑是自动升级有问题，请试试重新下载一份干净的版本试试

2015-05-12 12:19 GMT-04:00 TossPig <notifications@github.com>:

**Comment by tossp** [comment]
重新下载一份干净的版本,只保留data目录，更新成功了，恩恩，谢谢
