### ISSUE TITLE
提示 “考虑开启IP扫描器”

### ISSUE THREAD

**Issue by dirtCQ** [XX-net/XX-Net#3890]
---
## 问题内容
早上能正常上网，突然办公楼电压闪了下，电脑自动重启，重启之后打开XX.net 在状态页提示“您应该考虑开启IP扫描器“。
我查看先关配置，IP扫描器是开启状态，并已保存。

#### 获取诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 Core/1.47.640.400 QQBrowser/9.4.8309.400
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
#### 获取日志
Jul 18 11:40:53.586 - [INFO] SSL use version:TLSv1_2
Jul 18 11:40:53.712 - [DEBUG] network is ok, cost:1008 ms
Jul 18 11:40:54.011 - [INFO] OpenSSL support alpn
Jul 18 11:40:54.043 - [INFO] load ip range file:G:\XX-Net-3.1.19\code\default\gae_proxy\local\ip_range.txt
Jul 18 11:40:54.184 - [INFO] detected Win10, enable connect concurrency control, interval:40
Jul 18 11:40:54.203 - [WARNING] line err:
Jul 18 11:40:54.204 - [INFO] load google ip_list num:0, gws num:0
Jul 18 11:40:54.239 - [INFO] OpenSSL support alpn
Jul 18 11:40:54.269 - [WARNING] no enough ip
Jul 18 11:40:54.400 - [DEBUG] ## GAEProxy set keep_running: True
Jul 18 11:40:54.401 - [INFO] ------------------------------------------------------
Jul 18 11:40:54.401 - [INFO] Python Version : 2.7.11
Jul 18 11:40:54.401 - [INFO] OS : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Jul 18 11:40:54.401 - [INFO] Listen Address : 127.0.0.1:8087
Jul 18 11:40:54.401 - [INFO] GAE APPID : river-nation-137523|involuted-disk-137505|sonic-arcadia-137507|wutao1-1375|wutao2-1375|wutao3-1375|wutao4-1375|wutao5-1375|wutao6-1375|wutao7-1375|wutao8-1375|wutao9-1375|wutao10-1375
Jul 18 11:40:54.401 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jul 18 11:40:54.401 - [INFO] ------------------------------------------------------
Jul 18 11:40:55.148 - [WARNING] no enough ip
Jul 18 11:40:55.648 - [WARNING] no enough ip
Jul 18 11:40:56.152 - [WARNING] no enough ip
Jul 18 11:40:56.208 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Jul 18 11:40:56.328 - [DEBUG] GET http://www.twitter.com/xxnet
Jul 18 11:40:56.348 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Jul 18 11:40:56.367 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=fa8c08df-f4c3-4d4d-a88d-5922d765245b&version=3.2.5&platform=Windows-10-10.0.10586
Jul 18 11:40:56.652 - [WARNING] no enough ip
Jul 18 11:40:57.153 - [WARNING] no enough ip
Jul 18 11:40:57.668 - [WARNING] no enough ip
Jul 18 11:40:58.183 - [WARNING] no enough ip
---

**Comment by dirtCQ** [comment]
已解决。
由于是在高校，之前选择了IPV6
重新联网之后，没有分配IPV6地址，关闭该选项可重新联网

**Comment by yetwanng** [comment]
但是这样不就用不了IPv6了吗？教育网用户用IPv6的时候还是很方便的。。。
求解~

**Comment by jzp820927** [comment]
把 ipv6 ，设为 1，就可以用 ipv6 了

**Comment by yetwanng** [comment]
怎么设置啊，我的XX-net只有ipv6的开关选项

**Comment by jzp820927** [comment]
就是把开关开启就行了啊
