### ISSUE TITLE
是不是证书出了什么问题，好几台电脑状态都变成了：请检查浏览器代理设置。

### ISSUE THREAD

**Issue by lifeva** [XX-net/XX-Net#3894]
重新导入CA证书还是不行，这个问题大家都遇到了吗，近期的事情。

**Comment by jzp820927** [comment]
好几台电脑？你XX 是部署在 路由器上的吗？

**Comment by lifeva** [comment]
google没法访问，其他https正常

**Comment by lifeva** [comment]
您的连接不是私密连接

攻击者可能会试图从plus.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_DATE_INVALID
Subject: *.google.com
Issuer: GoAgent XX-Net
Expires on: 2016年7月16日
Current date: 2016年7月18日
PEM encoded chain: -----BEGIN CERTIFICATE-----
MIIDczCCAlugAwIBAgIQXzmUUmkG9ncbajff/dFotDANBgkqhkiG9w0BAQsFADBz
MQswCQYDVQQGEwJDTjERMA8GA1UECAwISW50ZXJuZXQxDzANBgNVBAcMBkNlcm5l
dDEQMA4GA1UECgwHR29BZ2VudDEVMBMGA1UECwwMR29BZ2VudCBSb290MRcwFQYD
VQQDDA5Hb0FnZW50IFhYLU5ldDAeFw0xNTA3MTcwNzU3NDZaFw0xNjA3MTYwODA3
NDZaMHgxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhJbnRlcm5ldDEPMA0GA1UEBwwG
Q2VybmV0MRcwFQYDVQQLDA5Hb0FnZW50IEJyYW5jaDEVMBMGA1UEAwwMKi5nb29n
bGUuY29tMRUwEwYDVQQKDAwqLmdvb2dsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCi8y+WAezsne7qOhn2mGMJunPQmttgQQfV2XrkHeb57sUD
NxpLXAiw/a2aS5EggUWDsMoMKQ6vluLqAwh/jdd+TTTNyOY4jsEjQH6Q+/k8baDb
L368qIRpW2qWttRxoOpmF6JAr+azz5ZdLURq8Sp+awYAfNToNiWBCpzoXbt0DGGQ
VrJ7tncKIuYMJJiDP9Tag60prNE/9lCr3SLX6Ybax7V+6MymuFdqYVvuSKu7rs/j
WRVksCrBlsbXG/tn8SBkLXlpjH3v62YGxKPyaKTezUiEp9Gn8J28A/LevH2yt9Rl
eYRuAS085/5Hc/ryR5+911K3SGvoYMJ28AfSidNdAgMBAAEwDQYJKoZIhvcNAQEL
BQADggEBAMIxHG78bfJBOjkNCDYgrZoGIiWep6sLGpfY7tnbAz3Za+9FrzKuF2F4
i+Ikp6qefT5tZdMfiB/aFkkYL/eyDmbHSgf0gHP7NfQ01h+3Ymo4EIJ+EVQTYb1l
I8cKDWdwP4KkIowif5G/Mgofl1lV+/AIQ8DZLt5CfFxRpo0RYbju41RlxlYdbNxQ
KN9O1Wa27PhZDzMXt63kuEoRWZfKeVMEm9LgFtstzA2LR4J5ygx0tKs94m5GWjLn
mbTd6rwkalmLpSOBBbhUL9wwJNM4STPiOdvkVdOsiwJqgjBR9UKrjd4hHknHIFtH
Rjv/1z7TofrozRLR3bsTT/4BZnMp+j0=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDWjCCAkICAQAwDQYJKoZIhvcNAQELBQAwczELMAkGA1UEBhMCQ04xETAPBgNV
BAgMCEludGVybmV0MQ8wDQYDVQQHDAZDZXJuZXQxEDAOBgNVBAoMB0dvQWdlbnQx
FTATBgNVBAsMDEdvQWdlbnQgUm9vdDEXMBUGA1UEAwwOR29BZ2VudCBYWC1OZXQw
HhcNMTUwNzE3MDgwNzAzWhcNMjUwNzE2MDgwNzAzWjBzMQswCQYDVQQGEwJDTjER
MA8GA1UECAwISW50ZXJuZXQxDzANBgNVBAcMBkNlcm5ldDEQMA4GA1UECgwHR29B
Z2VudDEVMBMGA1UECwwMR29BZ2VudCBSb290MRcwFQYDVQQDDA5Hb0FnZW50IFhY
LU5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANw9hEyIs4rfyQE+
tkbCluSShy1fHRbkq1REmEKTvASIqTLpS+2EGylTE9PLXmae2HMIxUyJZT39sQMu
2uZwX4hsm7i3jYFzFZdgiAy+kU9k/0HGftrfzU+MOpo5lA8aatGBSaLvJNTjWqXf
gN/R5N8YoakNzuAz7HYr13bZa3VwogZ0VmgCym1/GTV7ViQygxaScz9iA9QiPNLw
PudeIA4/U5ZTwMj0C2N2uytScR6SEPhe2oHMy5p7URLn27zajK2MMCD9FxCxGYYs
VjuDQXpP6zRwCYi8xjBgXLWyCmRikUTJUeR+5qwoVFUMsGLHkZulwQbKeVbyWMmI
mNTbHR0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEABM0SBX0Ag3YhHylYW5+b79os
W3/RCdNBX+UhiCxcnby5Rv/71FWQ5VgGzGU5p1nKkxgUftkr5zsmyRky7BeKv7ht
q/W8BTw2OJZaTWpmSOwU3+JiCCoWT8XlRLs003NUfYGPae9SPTxe0/RJBsSJZcas
UAzjpGIYylBRcKB0jfNW4PZcRw/2UmDaBWM6PeP2wXqMu/WjkvPRAYHxu9CWgKYD
/JunOExVlhFfrcSuLDlUmtw7vNABoLbly+ozd0uWBOVmzgKPu4zDUpjWIoDXQDuQ
gocYYUdOKa8k7Ge92H2EbreIV2TyP1Spw/Rwnv8Pwu56q7hcAos+k1g3RZSA4Q==
-----END CERTIFICATE-----

**Comment by lifeva** [comment]
是不是证书有问题了？

**Comment by jzp820927** [comment]
是证书问题，试试重新导入证书吧。或者删掉，重新生成

**Comment by IsabellRoy** [comment]
删掉data文件夹 重新生成一下证书。
（不知道从哪个版本就一直保留下来的data文件夹里）的证书昨天过期了（2015.7.17-2016.7.17）..

**Comment by jzp820927** [comment]
居然有用了一年的证书，牛啊

**Comment by lifeva** [comment]
已经解决，谢谢各位，删除文件夹里面的证书就可以了，不需要删除data文件夹
