### ISSUE TITLE
① chrome 提示 "账户登录信息已过期。重新登录" 但是不能登录。。。②Twitter 账号不能关注别的账号

### ISSUE THREAD

**Issue by os9sur** [XX-net/XX-Net#3895]
① chrome 提示 "账户登录信息已过期。重新登录" 但是不能登录……
②Twitter 账号不能关注别的账号
但是用 goproxy ，或者关闭xx-net，这两个问题就没有了。
证书已经删掉再重新导入......不过不行。
不知道为什么……
还烦请各位一直无私奉献，给力的开发者们，有时间看一下这个问题。
多谢啦！:-)
![2016-07-19_002824](https://cloud.githubusercontent.com/assets/6024166/16922512/5d4a312c-4d48-11e6-9262-aa70abb44ef1.png)

**Comment by jzp820927** [comment]
确认走 XX 代理了吗

**Comment by White99** [comment]
@jzp820927   多谢关注，  xx设置了全局代理，翻墙倒是没问题，但就突然出现这两个问题

**Comment by jzp820927** [comment]
翻墙没问题就行了吧

**Comment by White99** [comment]
@jzp820927   我刚刚测试了多个版本 如 3.19 \3.24 \3.25  ，删除过data，也重新注册过证书，换了几台电脑测试，均有这两个问题，但是之前一直是没有这些问题的。。。  twitter 不能关注也无所谓了，只是 chrome账号不能登录，chrome的数据不能同步，如收藏夹，操作记录 插件，所有配置。。。
当然，并不是很严重的问题（可以暂时用vpn，hosts等 实现同步），如果您或者哪一位什么时候有空的话，还烦请看一下。。。
多谢哈 :-)

**Comment by yeahwu** [comment]
应该还是代理设置的问题，上状态页，上日志
另外试试
Internet选项/连接/局域网设置
主机 127.0.0.1 端口8087 保存，
然后看看能不能登录？

**Comment by White99** [comment]
@yeahwu  多谢高手关注！
xx全局设置的时候，internet 那个局域网设置会自动改成：127.0.0.1 端口 8087
刚才在internet 取消了一下， 手动设置了一下127.0.0.1  8087，不过。。还是不行。。。
以下是状态页面截图：
*********************************************************************************
![2016-07-19_150026](https://cloud.githubusercontent.com/assets/6024166/16941656/06e1898a-4dc4-11e6-858c-4a843d8ef11a.jpg)

以下是日志（设置成全局通过GAEProxy代理，重启GAEProxy，分别操作了：①twitter 关注某一个账号。②chrome 账号尝试登陆了一下。）：
****************************************************************************************
Jul 19 15:05:42.657 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jul 19 15:05:42.657 - [INFO] ------------------------------------------------------
Jul 19 15:05:45.174 - [DEBUG] ip:190.240.2.156 real fail
Jul 19 15:05:46.658 - [DEBUG] get ip:188.43.68.40 t:246
Jul 19 15:05:46.946 - [DEBUG] create_ssl update ip:188.43.68.40 time:197 h2:0
Jul 19 15:05:46.946 - [DEBUG] get ip:203.252.15.186 t:288
Jul 19 15:05:47.195 - [DEBUG] create_ssl update ip:203.252.15.186 time:192 h2:1
Jul 19 15:05:48.216 - [DEBUG] GAE POST https://twitter.com/i/user/follow
Jul 19 15:05:48.631 - [DEBUG] GAE GET https://twitter.com/i/timeline?composed_count=0&include_available_features=1&include_entities=1&include_new_items_bar=true&interval=10000&last_note_ts=6361&latent_count=35&min_position=755297233688461312
Jul 19 15:05:48.678 - [INFO] GAE t:461 s:92 POST https://twitter.com/i/user/follow h2_get_head:454
Jul 19 15:05:49.184 - [INFO] GAE t:552 s:5262 GET https://twitter.com/i/timeline?composed_count=0&include_available_features=1&include_entities=1&include_new_items_bar=true&interval=10000&last_note_ts=6361&latent_count=35&min_position=755297233688461312 h2_get_head:547
Jul 19 15:05:49.266 - [DEBUG] GAE GET https://pbs.twimg.com/profile_images/731132378001879040/HWk2Eaxg_bigger.jpg
Jul 19 15:05:49.287 - [DEBUG] GAE GET https://pbs.twimg.com/media/Cnta-4IW8AAFngC.jpg
Jul 19 15:05:49.288 - [DEBUG] GAE GET https://pbs.twimg.com/media/Cnta-FKWYAAWxwC.jpg
Jul 19 15:05:49.557 - [INFO] GAE t:290 s:2439 GET https://pbs.twimg.com/profile_images/731132378001879040/HWk2Eaxg_bigger.jpg get_response:286
Jul 19 15:05:49.785 - [INFO] GAE t:496 s:30161 GET https://pbs.twimg.com/media/Cnta-FKWYAAWxwC.jpg get_response:458,h2_finish[SP:848944]:36
Jul 19 15:05:49.958 - [DEBUG] ssl_closed 92.126.121.58
Jul 19 15:05:49.958 - [DEBUG] 92.126.121.58 worker close:idle timeout
Jul 19 15:05:50.417 - [INFO] GAE t:1130 s:68327 GET https://pbs.twimg.com/media/Cnta-4IW8AAFngC.jpg h2_get_head:424,h2_finish[SP:97525]:702
Jul 19 15:05:50.435 - [DEBUG] ssl_closed 210.158.146.177
Jul 19 15:05:50.435 - [DEBUG] 210.158.146.177 worker close:idle timeout
Jul 19 15:05:50.700 - [DEBUG] ip:78.37.112.106 real fail
Jul 19 15:05:53.862 - [INFO] GAE CONNECT www.google.com:443
Jul 19 15:05:53.902 - [DEBUG] GAE CONNECT Direct POST https://www.google.com/gen_204?atyp=i&ct=slh&cad=&ei=x82NV9FgzLPQBMKkqLAG&s=15&v=2&pv=0.03439575011940921&me=44:1468911233092,V,0,0,0,0:720063,U,720063:1,V,0,0,1366,667:699,e,H&zx=1468911953855
Jul 19 15:05:53.940 - [DEBUG] sort ip time:36ms
Jul 19 15:05:53.941 - [DEBUG] get ip:210.158.146.177 t:193
Jul 19 15:05:54.044 - [INFO] DIRECT t:141 204 www.google.com /gen_204?atyp=i&ct=slh&cad=&ei=x82NV9FgzLPQBMKkqLAG&s=15&v=2&pv=0.03439575011940921&me=44:1468911233092,V,0,0,0,0:720063,U,720063:1,V,0,0,1366,667:699,e,H&zx=1468911953855
Jul 19 15:05:54.361 - [DEBUG] create_ssl update ip:210.158.146.177 time:248 h2:0
Jul 19 15:05:54.405 - [DEBUG] get ip:92.126.121.58 t:276
Jul 19 15:05:54.791 - [DEBUG] create_ssl update ip:92.126.121.58 time:260 h2:0
Jul 19 15:05:55.700 - [DEBUG] ip:2.127.237.226 real fail
Jul 19 15:05:56.426 - [DEBUG] GAE GET https://accounts.google.com/embedded/setup/chrome/usermenu?client_id=77185425430.apps.googleusercontent.com&hl=zh-CN&email_hint=whitezhen%40gmail.com&source=chrome&flow=signin
Jul 19 15:05:56.629 - [DEBUG] ssl_closed 59.18.45.171
Jul 19 15:05:56.629 - [DEBUG] 59.18.45.171 worker close:idle timeout
Jul 19 15:05:57.087 - [INFO] GAE t:660 s:161290 GET https://accounts.google.com/embedded/setup/chrome/usermenu?client_id=77185425430.apps.googleusercontent.com&hl=zh-CN&email_hint=whitezhen%40gmail.com&source=chrome&flow=signin get_response:315,h2_finish[SP:470343]:343
Jul 19 15:05:58.226 - [DEBUG] GAE POST https://accounts.google.com/_/lookup/accountlookup?hl=zh-CN&_reqid=54359&rt=j
Jul 19 15:05:58.453 - [INFO] GAE t:226 s:131 POST https://accounts.google.com/_/lookup/accountlookup?hl=zh-CN&_reqid=54359&rt=j get_response:223
Jul 19 15:05:58.521 - [DEBUG] GAE POST https://accounts.google.com/jserror
Jul 19 15:05:58.740 - [INFO] GAE t:219 s:131 POST https://accounts.google.com/jserror get_response:215
Jul 19 15:06:00.015 - [DEBUG] GAE GET https://accounts.google.com/_/back?backstep=1
Jul 19 15:06:00.294 - [INFO] GAE t:278 s:713 GET https://accounts.google.com/_/back?backstep=1 h2_get_head:273
Jul 19 15:06:00.340 - [DEBUG] GAE GET https://accounts.google.com/_/common/diagnostics/?diagnostics=%5B%5B%5B%22gaia_fe_minutemaid%3Ass%22%2Cnull%2Cnull%2Cnull%2C1468911957156%5D%2C%5B%22gaia_fe_minutemaid%3Ass%22%2Cnull%2Cnull%2Cnull%2C1468911957156%5D%2C%5B%5D%2C%5B%22gaia_fe_minutemaid%3AsignInAttempt%22%2Cnull%2Cnull%2Cnull%2C1468911957156%5D%2C%5B%5D%2C%5B%22gaia_fe_minutemaid%3AidentifierPage%22%2Cnull%2Cnull%2Cnull%2C1468911957396%2C1112%5D%5D%5D&rt=j&TL=undefined
Jul 19 15:06:00.611 - [INFO] GAE t:271 s:59 GET https://accounts.google.com/_/common/diagnostics/?diagnostics=%5B%5B%5B%22gaia_fe_minutemaid%3Ass%22%2Cnull%2Cnull%2Cnull%2C1468911957156%5D%2C%5B%22gaia_fe_minutemaid%3Ass%22%2Cnull%2Cnull%2Cnull%2C1468911957156%5D%2C%5B%5D%2C%5B%22gaia_fe_minutemaid%3AsignInAttempt%22%2Cnull%2Cnull%2Cnull%2C1468911957156%5D%2C%5B%5D%2C%5B%22gaia_fe_minutemaid%3AidentifierPage%22%2Cnull%2Cnull%2Cnull%2C1468911957396%2C1112%5D%5D%5D&rt=j&TL=undefined get_response:269
Jul 19 15:06:00.701 - [DEBUG] ip:62.252.173.160 real fail
Jul 19 15:06:05.701 - [DEBUG] ip:180.149.61.54 real fail
Jul 19 15:06:06.818 - [DEBUG] restore ip:94.20.252.41
Jul 19 15:06:07.224 - [DEBUG] GAE GET https://twitter.com/i/timeline?composed_count=0&include_available_features=1&include_entities=1&include_new_items_bar=true&interval=10000&last_note_ts=6362&latent_count=40&min_position=755297479969693696&oldest_unread_id=0
Jul 19 15:06:07.757 - [INFO] GAE t:532 s:2791 GET https://twitter.com/i/timeline?composed_count=0&include_available_features=1&include_entities=1&include_new_items_bar=true&interval=10000&last_note_ts=6362&latent_count=40&min_position=755297479969693696&oldest_unread_id=0 get_response:532
Jul 19 15:06:07.799 - [DEBUG] GAE GET https://pbs.twimg.com/media/CntbL-nXYAElL4D.jpg
Jul 19 15:06:08.139 - [INFO] GAE t:339 s:25069 GET https://pbs.twimg.com/media/CntbL-nXYAElL4D.jpg get_response:309,h2_finish[SP:849000]:29

**************************************
由于这方面我是外行。。。所以现在我只能临时部署了一个pac文件，删去了 google ，twitter ，走代理的if判断。

**Comment by jzp820927** [comment]
看日志和状态页，没看出啥问题，等 Y大来帮你看吧

**Comment by White99** [comment]
@jzp820927 多谢 您一直的关注！:-)

**Comment by jzp820927** [comment]
没看出啥问题，只能帮你到这儿了。
实在不行就用 hosts+pac，PAC里面删掉 google 域名就可以了。

**Comment by White99** [comment]
多谢,多谢!!!

**Comment by yeahwu** [comment]
清理一下缓存，点击xx图标勾选取消全局代理，然后用代理插件试试。wiki里有详细教程！如果这样还不行的话。看看别的浏览器有没有问题！
天朝屁民 <notifications@github.com>于2016年7月19日 周二15:42写道：

**Comment by White99** [comment]
@yeahwu 多谢您的关注。  从清缓存…一步一步操作下来，依然不行（其实一直用的都是SO）。不过按照您的提醒， 换了 IE 可以，搜狗还是不行（同样指定了代理 127.0.0.1端口8087）。
现在只能临时本地IIS 部署了pac，改走hosts。还是感觉这个问题好奇怪。。。

多谢你们的辛勤付出，才有了这个免费软件里面速度最快的 :-)！
Awesome work！

**Comment by jzp820927** [comment]
xx 就带有 PAC 功能，你还去部署 iis，用不着吧？

**Comment by White99** [comment]
@jzp820927  多谢! 多谢 :-)   哈哈，这不我是个外行嘛， 之前试图解决这个问题的时候， 删除过data文件夹，换过其他版本，担心pac 改过和没改过的 文件弄乱了，而且升级的时候会不会覆盖掉，都不太懂……最后就想着索性和项目文件夹分离，单独部署一个，呃……这似乎又是在迷茫之中走了弯路……:-)

**Comment by jzp820927** [comment]
data 目录内的文件，是用户数据，是不会被XX 修改的。而且 XX 生成的 pac 也是放在 data 里面的，你自己单独写一个pac 放里面，单独维护就行了，不用什么 iis 了。

**Comment by yjd** [comment]
xx-net不定时会切换ip。会有这种情况吧？
不然，ss也不会有个选项，同一域名走同一个ip。

**Comment by White99** [comment]
@jzp820927  多谢行家! :-)   学习了。但是还是暂时不改吧，以后如果下载新版本也不用覆盖这个pac了，如果以后其他电脑部署xx，就不走这个弯路了……哈哈 :-) 
再次感谢!

**Comment by White99** [comment]
@yjd  嗯嗯，您说的有道理。但是有点不解的是，即便取消关联，删除账号，重新登录也不行……

**Comment by yjd** [comment]
那这样应该不是我说的问题了。
你可以用排除法先用其他浏览器试如美分浏览器。不行再换另一台电脑试试。

**Comment by jzp820927** [comment]
部署 xx-net不定时会切换ip。而是 GAE 的出口IP 不固定，这个出口 IP ，XX 是无法控制的，只有 GAE 那端能控制

**Comment by malthae** [comment]
我也碰到过不能登录  切换成全局就好了
另外我的chrome一直不能自动更新 必须进IE设置代理才行 很是蛋疼

**Comment by Will97** [comment]
加入你用的时ubuntu等linux系统的话，可能时密钥环引起的，把密钥环密码置空，或者删除密钥环就可以啦……参考：https://bbs.deepin.org/forum.php?mod=viewthread&tid=44447

**Comment by CHN008** [comment]
我以前遇到过这个问题,也反应过这问题.

大家也没讨论出什么原因来,算起来是一个没太碍的Bug吧.

**Comment by Will97** [comment]
若用的是ubuntu类似的系统,关掉默认的秘钥环就可以了,或者将秘钥环密码置空....

**Comment by g8up** [comment]
我的chrome 稳定版（v55）这两个月也不能同步了；
我在同一电脑上安装了个 chrome canary 版，却可以正常同步。
两个 chrome 走的都是同一个 xx-net

稳定版也出现了“登录详细信息过期”提示，登录框加载不出来。

**Comment by jzp820927** [comment]
这个有点不科学啊，你的意思是说，canary 版没问题，只有稳定版有问题？

**Comment by g8up** [comment]
@jzp820927 ,刚刚竟然可以同步了。
之前有近2个月的时间不同步了，但 chrome 也没提示“登录详细信息过期”。
我今天精简了一下 SwithyOmega 的 rules（从 xx-net 提供的.bak里导入），系统托盘图标也切换到 全局 PAC， chrome 的同步登录页依然无法加载、白页。

但刚刚又试了一下，竟然好了。

**Comment by jzp820927** [comment]
好吧，好了就行了

**Comment by aceslup** [comment]
清空自己添加的规则，我这边有一个谷歌账号能登录了。另外一台机器的另外一个账号就不得行了。

**Comment by peqing** [comment]
@g8up  请问您最后这么解决的？精简了一下 SwithyOmega 的 rules，精简了哪些啊？

**Comment by SeaHOH** [comment]
无所谓精简，他只是使用了 XX-Net 自带的规则备份。
如果重新导入，会覆盖你之前的修改。

**Comment by g8up** [comment]
@peqing 如果要解决不同步问题，可以尝试
1.保证网络畅通
2. Chrome 设置里停止同步，退出Chrome 中的登录状态
3. 重新登录 Chrome，开启同步。
