### ISSUE TITLE
如果设置了自动检查更新但github/DNS被墙会导致xx-net卡顿过半分钟才启动界面

### ISSUE THREAD

**Issue by NAVrasZ** [XX-net/XX-Net#3897]
今天开xx-net突然启动不了，点击桌面图标没反应，再点击鼠标符号显示忙碌，几十秒后托盘区出现三个xx-net图标...过一开始还以为XX-NET坏了覆盖了好几次，后来发现开xx-net能上网关上不能上网，才发现自己设的DNS可能被封了，设回自动获取DNS，xx-net秒开流畅
日志从最后一次启动开始记录的，已不包含问题，不用贴了吧..？
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2731 good:1308
network-status: OK
connected-link: new:2 used:0
worker: h1:14 h2:8
scan-ip-thread-num: 300
ip-quality: 187
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

另外自己有python3.5的可以让xx-net用本机的吗？

**Comment by yaoguaishou** [comment]
听不懂你想说什么
[dns的问题可以使用`tcpdns`](https://github.com/henices/Tcp-DNS-proxy)

**Comment by jzp820927** [comment]
要用 python3.5，要下py3 分支的 xx 才行，默认分支的 XX 只支持 py2

**Comment by NAVrasZ** [comment]
@yaoguaishou 感觉这是个bug（或者故意不检查完更新不让用嘛2233）

**Comment by NAVrasZ** [comment]
@jzp820927 好的我去找下

**Comment by jzp820927** [comment]
py3 的分支好久没更新了，没有特殊情况，还是建议用 默认分支吧

**Comment by Cat7373** [comment]
所以说，自动检查更新应该新建个线程咯
