### ISSUE TITLE
墙的封锁方式变了还是怎么样？

### ISSUE THREAD

**Issue by OnionSalt** [XX-net/XX-Net#390]
刚刚启动xx-net然后过1分钟左右，connected link会保持在10,3左右，但是只要一访问任何跟youtube/google有关的网站，connected link马上就会变成0,0或者0,x，反映在页面上就是让我休息一会。

感觉现在gfw的封锁方式变了，在goagent的issue里看到有人猜测是现在gfw开始根据cert封锁了，只要发现google证书直接黑掉，也不知道真的假的

直接用goagent也是一样，休息一会

试验了下自由门，勉强能打开页面，但视频超卡，基本看不了

大家跟我状况一样吗？

**Comment by nly4lov** [comment]
没有啊。我通过控制页面升级到最新的，现在打开任何网站都流畅死了

**Comment by dickfej** [comment]
有相同的情况出现

**Comment by zhangkaifei** [comment]
"连接超时，先休息一会再来！" 我是已经买了红杏了，这几天goagent确实不好用了。。

**Comment by shufecrystal** [comment]
"连接超时，先休息一会再来！" 一直这样，开线程和加入ip都没有用

**Comment by nly4lov** [comment]
建议大家下载13.4的，然后从里边的设置升级到13.6和14.4.我就是这样做的。现在翻得蛮好的啊

**Comment by xxnet** [comment]
请试试最新版 1.14.6，加入了蛤蟆ip段，也有修复扫描ip线程在网络太差时会停止的问题

在 2015年5月12日 上午11:17，Adam Song <notifications@github.com>写道：

**Comment by OnionSalt** [comment]
刚升级到14.6了，已经加入蛤蟆ip段了，多谢阿！
