### ISSUE TITLE
桌面图标问题和稳定版升级问题

### ISSUE THREAD

**Issue by hzj-777** [XX-net/XX-Net#3909]
遇到两个问题。
1.升级3.2.6后点击桌面图标无法启动，删除data文件夹后没有用，依然只有第一次启动，之后启动不了。
2.稳定版升级到3.2.5安装包在哪下载？我只找到3.1.9的

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/releases

**Comment by hzj-777** [comment]
@yeahwu 这个是测试版?

**Comment by yeahwu** [comment]
备份data文件夹，删除老版本，包括快捷方式图标。下载3.2.6版，解压后把data文件夹放在主目录，点击start.vbs启动

**Comment by MichaelBeyond** [comment]
我现在升级都是直接解压，然后覆盖原来的版本。
