### ISSUE TITLE
更新到3.x.x后始终显示“请检查浏览器代理设置。”

### ISSUE THREAD

**Issue by Casperlet** [XX-net/XX-Net#3910]
之前用的2.9.4，这两天更新到3.1.9后始终显示“请检查浏览器代理设置。”，其中CA证书和浏览器代理设置始终显示Fail，但我查看证书是安装了的。之后，我尝试过安装3.2.5和3.2.6，以及删除证书后重新运行start、删除整个xx-net目录后重新Start等方式，始终未果。不知道是哪里的问题导致了这样的结果？

## 证书安装情况
![已安装证书](https://cloud.githubusercontent.com/assets/12539721/16992907/c577fe64-4ed3-11e6-9c4e-d8aec5d8411a.png)

## 诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:29 good:14
network-status: OK
connected-link: new:0 used:0
worker: h1:9 h2:0
scan-ip-thread-num: 50
ip-quality: 1279
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by chaohong** [comment]
请尝试删除 XX-Net/data/gae_proxy/certs 目录下的证书

**Comment by MichaelBeyond** [comment]
选择XX-NET自动切换试试。

**Comment by Casperlet** [comment]
折腾了两天，现在3.2.5可以工作了。

因为我是从2.9.X升级后出现这些问题的，于是我把Chrome以及Omega还有XX-NET都卸载了，以全新安装的方式从头来了一遍，包括重新检测IP等等，然后3.2.5就开始正常工作了。看来还是在升级过程中，有一些我不知道的地方有向下兼容性问题。
