### ISSUE TITLE
证书导入失败

### ISSUE THREAD

**Issue by forjiuzhou** [XX-net/XX-Net#3911]
使用chrome导入证书失败，显示“缺少此客户端证书的私钥，或私钥无效。”
直接双击证书可以导入
状态显示，浏览器代理设置fail，ca证书fail
以下是诊断
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
os-release: 4.4.0-31-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:164 good:161
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 490
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by forjiuzhou** [comment]
发现已经导入，但状态显示仍为fail

**Comment by forjiuzhou** [comment]
7月 21 13:02:08.66 - [INFO] SSL use version:TLSv1_2
7月 21 13:02:08.67 - [INFO] OpenSSL support alpn
7月 21 13:02:08.68 - [INFO] load ip range file:/home/jiuzhou/XX-Net-master/code/default/gae_proxy/local/ip_range.txt
7月 21 13:02:08.71 - [INFO] load google ip_list num:237, gws num:237
7月 21 13:02:08.74 - [INFO] OpenSSL support alpn
7月 21 13:02:08.74 - [DEBUG] get ip:202.224.62.21 t:145
7月 21 13:02:08.75 - [DEBUG] get ip:202.224.62.14 t:146
7月 21 13:02:08.78 - [DEBUG] ## GAEProxy set keep_running: True
7月 21 13:02:08.78 - [INFO] ------------------------------------------------------
7月 21 13:02:08.78 - [INFO] Python Version : 2.7.12
7月 21 13:02:08.78 - [INFO] OS : Dist:Ubuntu; Version:16.04; ID:xenial
7月 21 13:02:08.78 - [INFO] Listen Address : 127.0.0.1:8087
7月 21 13:02:08.78 - [INFO] GAE APPID : forjiuzhou|forjiuzhou1|forjiuzhou2|forjiuzhou3|forjiuzhou4|forjiuzhou5|forjiuzhou6
7月 21 13:02:08.78 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
7月 21 13:02:08.78 - [INFO] ------------------------------------------------------
7月 21 13:02:08.96 - [DEBUG] create_ssl update ip:202.224.62.21 time:147 h2:0
7月 21 13:02:08.96 - [DEBUG] get ip:202.224.62.58 t:147
7月 21 13:02:08.98 - [DEBUG] create_ssl update ip:202.224.62.14 time:162 h2:0
7月 21 13:02:08.99 - [DEBUG] network is ok, cost:389 ms
7月 21 13:02:09.18 - [DEBUG] GAE POST http://center.xx-net.net:8888/login
7月 21 13:02:09.25 - [DEBUG] get ip:202.224.62.49 t:148
7月 21 13:02:09.44 - [INFO] GAE t:263 s:185 POST http://center.xx-net.net:8888/login get_worker:2,h1_get_head:259
7月 21 13:02:09.44 - [DEBUG] GAE POST http://104.207.140.47:6666/data
7月 21 13:02:09.50 - [DEBUG] create_ssl update ip:202.224.62.58 time:353 h2:0
7月 21 13:02:09.50 - [DEBUG] get ip:210.158.146.169 t:165
7月 21 13:02:09.75 - [DEBUG] get ip:210.158.146.176 t:165
7月 21 13:02:09.99 - [DEBUG] get ip:210.158.146.171 t:172
7月 21 13:02:10.19 - [INFO] GAE t:748 s:13 POST http://104.207.140.47:6666/data h1_get_head:747
7月 21 13:02:10.25 - [DEBUG] get ip:202.224.62.18 t:178
7月 21 13:02:10.46 - [DEBUG] create_ssl update ip:210.158.146.171 time:404 h2:0
7月 21 13:02:10.57 - [DEBUG] create_ssl update ip:202.224.62.18 time:216 h2:0
7月 21 13:02:10.71 - [DEBUG] create_ssl update ip:210.158.146.169 time:134 h2:0
7月 21 13:02:10.71 - [DEBUG] get ip:210.158.146.161 t:206
7月 21 13:02:10.75 - [DEBUG] get ip:113.171.253.42 t:228
7月 21 13:02:10.79 - [INFO] scan_ip add ip:77.234.91.104 time:470
7月 21 13:02:10.87 - [DEBUG] create_ssl update ip:202.224.62.49 time:520 h2:0
7月 21 13:02:11.10 - [DEBUG] create_ssl update ip:210.158.146.176 time:230 h2:0
7月 21 13:02:11.25 - [DEBUG] get ip:210.158.146.168 t:232
7月 21 13:02:11.29 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
7月 21 13:02:11.30 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=80df0962-47f6-458e-93f3-1e8d5ffc704c&version=3.2.6&platform=Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
7月 21 13:02:11.38 - [DEBUG] create_ssl update ip:113.171.253.42 time:416 h2:0
7月 21 13:02:11.46 - [DEBUG] get ip:115.254.121.226 t:322
7月 21 13:02:11.57 - [DEBUG] get ip:113.171.253.31 t:332
7月 21 13:02:11.73 - [DEBUG] create_ssl update ip:210.158.146.168 time:412 h2:0
7月 21 13:02:11.75 - [DEBUG] get ip:202.224.62.54 t:348
7月 21 13:02:11.87 - [DEBUG] get ip:202.224.62.60 t:350
7月 21 13:02:11.99 - [INFO] DIRECT t:685 s:1674 200 xxnet-update.appspot.com /update.json?uuid=80df0962-47f6-458e-93f3-1e8d5ffc704c&version=3.2.6&platform=Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
7月 21 13:02:12.10 - [DEBUG] get ip:210.158.146.167 t:367
7月 21 13:02:12.12 - [INFO] scan_ip add ip:62.24.158.179 time:995
7月 21 13:02:12.25 - [DEBUG] get ip:115.254.97.23 t:373
7月 21 13:02:12.38 - [DEBUG] get ip:122.149.3.204 t:379
7月 21 13:02:12.74 - [DEBUG] get ip:122.149.3.240 t:388
7月 21 13:02:12.76 - [DEBUG] get ip:103.233.37.53 t:465
7月 21 13:02:12.79 - [DEBUG] create_ssl update ip:210.158.146.161 time:1024 h2:0
7月 21 13:02:12.79 - [DEBUG] get ip:103.233.37.33 t:466
7月 21 13:02:13.26 - [DEBUG] get ip:216.123.194.210 t:475
7月 21 13:02:13.55 - [DEBUG] create_ssl update ip:202.224.62.54 time:1737 h2:0
7月 21 13:02:13.64 - [DEBUG] create_ssl update ip:202.224.62.60 time:541 h2:0
7月 21 13:02:13.67 - [DEBUG] create_ssl update ip:210.158.146.167 time:862 h2:0
7月 21 13:02:13.75 - [DEBUG] create_ssl update ip:113.171.253.31 time:1928 h2:0
7月 21 13:02:13.76 - [DEBUG] get ip:216.123.194.206 t:476
7月 21 13:02:13.97 - [DEBUG] create_ssl update ip:122.149.3.204 time:993 h2:0
7月 21 13:02:14.18 - [DEBUG] create_ssl update ip:122.149.3.240 time:458 h2:1
7月 21 13:02:14.24 - [DEBUG] create_ssl update ip:216.123.194.210 time:493 h2:0
7月 21 13:02:14.26 - [DEBUG] get ip:65.199.32.176 t:476
7月 21 13:02:14.54 - [DEBUG] create_ssl update ip:216.123.194.206 time:524 h2:0
7月 21 13:02:14.55 - [DEBUG] get ip:104.134.128.52 t:503
7月 21 13:02:14.64 - [DEBUG] get ip:104.134.128.84 t:503
7月 21 13:02:14.65 - [DEBUG] create_ssl update ip:103.233.37.33 time:773 h2:0
7月 21 13:02:14.65 - [DEBUG] get ip:103.233.36.79 t:507
7月 21 13:02:14.67 - [DEBUG] get ip:104.134.128.86 t:507
7月 21 13:02:14.75 - [DEBUG] get ip:113.171.253.33 t:518
7月 21 13:02:14.76 - [DEBUG] get ip:113.171.244.37 t:518
7月 21 13:02:14.97 - [DEBUG] get ip:113.171.247.77 t:565
7月 21 13:02:15.04 - [DEBUG] create_ssl update ip:65.199.32.176 time:520 h2:0
7月 21 13:02:15.06 - [DEBUG] create_ssl update ip:104.134.128.52 time:339 h2:0
7月 21 13:02:15.14 - [DEBUG] create_ssl update ip:104.134.128.84 time:336 h2:0
7月 21 13:02:15.18 - [DEBUG] create_ssl update ip:104.134.128.86 time:346 h2:0
7月 21 13:02:15.18 - [DEBUG] get ip:200.124.254.224 t:569
7月 21 13:02:15.24 - [DEBUG] get ip:113.171.252.143 t:573
7月 21 13:02:15.26 - [DEBUG] get ip:186.46.140.97 t:574
7月 21 13:02:15.40 - [DEBUG] create_ssl update ip:113.171.253.33 time:428 h2:0
7月 21 13:02:15.47 - [DEBUG] 115.254.121.226 fail:timeout('timed out',)
7月 21 13:02:15.47 - [DEBUG] report_connect_fail:115.254.121.226
7月 21 13:02:15.60 - [DEBUG] create_ssl update ip:113.171.247.77 time:421 h2:0
7月 21 13:02:15.65 - [DEBUG] create_ssl update ip:113.171.244.37 time:680 h2:0
7月 21 13:02:15.88 - [DEBUG] create_ssl update ip:103.233.36.79 time:825 h2:0
7月 21 13:02:16.26 - [DEBUG] 115.254.97.23 fail:timeout('timed out',)
7月 21 13:02:16.26 - [DEBUG] report_connect_fail:115.254.97.23
7月 21 13:02:16.76 - [DEBUG] 103.233.37.53 fail:timeout('timed out',)
7月 21 13:02:16.76 - [DEBUG] report_connect_fail:103.233.37.53
7月 21 13:02:18.26 - [DEBUG] create_ssl update ip:113.171.252.143 time:852 h2:0
7月 21 13:02:18.75 - [DEBUG] create_ssl update ip:186.46.140.97 time:3183 h2:0
7月 21 13:02:19.18 - [DEBUG] 200.124.254.224 fail:timeout('timed out',)
7月 21 13:02:19.18 - [DEBUG] report_connect_fail:200.124.254.224
7月 21 13:02:19.23 - [INFO] scan_ip add ip:61.37.150.147 time:257
7月 21 13:02:30.48 - [DEBUG] ip:115.254.121.226 real fail
7月 21 13:02:31.32 - [INFO] scan_ip add ip:177.55.62.81 time:798
7月 21 13:02:35.49 - [DEBUG] ip:115.254.97.23 real fail
7月 21 13:02:40.49 - [DEBUG] ip:103.233.37.53 real fail
7月 21 13:02:45.50 - [DEBUG] ip:200.124.254.224 real fail
7月 21 13:02:51.13 - [INFO] scan_ip add ip:177.43.165.79 time:1669
7月 21 13:02:52.03 - [INFO] scan_ip add ip:80.233.168.224 time:527
7月 21 13:02:58.80 - [DEBUG] 210.158.146.168 close:host pool alive_timeout
7月 21 13:02:58.80 - [DEBUG] ssl_closed 210.158.146.168
7月 21 13:03:05.92 - [DEBUG] get ip:61.37.150.147 t:257
7月 21 13:03:08.30 - [INFO] scan_ip add ip:24.214.95.191 time:755
7月 21 13:03:09.92 - [DEBUG] 61.37.150.147 fail:timeout('timed out',)
7月 21 13:03:09.92 - [DEBUG] report_connect_fail:61.37.150.147
7月 21 13:03:09.92 - [DEBUG] get ip:210.158.146.168 t:412
7月 21 13:03:10.24 - [DEBUG] create_ssl update ip:210.158.146.168 time:251 h2:0
7月 21 13:03:10.24 - [DEBUG] get ip:77.234.91.104 t:470
7月 21 13:03:11.10 - [DEBUG] create_ssl update ip:77.234.91.104 time:581 h2:0
7月 21 13:03:14.25 - [INFO] scan_ip add ip:219.117.35.53 time:1052
7月 21 13:03:20.24 - [INFO] scan_ip add ip:219.88.188.220 time:881
7月 21 13:03:24.60 - [INFO] scan_ip add ip:200.216.56.168 time:670
7月 21 13:03:24.93 - [DEBUG] ip:61.37.150.147 real fail
7月 21 13:03:33.38 - [INFO] scan_ip add ip:216.11.246.158 time:528
7月 21 13:03:37.16 - [INFO] scan_ip add ip:167.206.245.215 time:825
7月 21 13:03:41.04 - [INFO] scan_ip add ip:181.47.248.38 time:764
7月 21 13:03:46.18 - [INFO] scan_ip add ip:202.75.147.30 time:2543
7月 21 13:03:53.32 - [INFO] scan_ip add ip:194.106.173.147 time:1049
7月 21 13:04:01.15 - [DEBUG] get ip:80.233.168.224 t:527
7月 21 13:04:04.67 - [DEBUG] create_ssl update ip:80.233.168.224 time:3261 h2:0
7月 21 13:04:04.67 - [DEBUG] get ip:216.11.246.158 t:528
7月 21 13:04:08.68 - [DEBUG] 216.11.246.158 fail:timeout('timed out',)
7月 21 13:04:08.68 - [DEBUG] report_connect_fail:216.11.246.158
7月 21 13:04:08.68 - [DEBUG] get ip:113.171.252.225 t:575
7月 21 13:04:09.46 - [DEBUG] create_ssl update ip:113.171.252.225 time:528 h2:0
7月 21 13:04:23.69 - [DEBUG] ip:216.11.246.158 real fail
7月 21 13:04:30.47 - [INFO] start to terminate GAE_Proxy
7月 21 13:04:30.47 - [DEBUG] ## Set keep_running: False
7月 21 13:04:31.25 - [INFO] Exiting gae_proxy module...
7月 21 13:04:32.07 - [INFO] scan_ip add ip:203.176.178.28 time:3417
7月 21 13:04:36.24 - [DEBUG] ## GAEProxy set keep_running: False
7月 21 13:04:36.29 - [DEBUG] ssl_closed 113.171.252.225
7月 21 13:04:36.29 - [DEBUG] ssl_closed 80.233.168.224
7月 21 13:04:36.29 - [DEBUG] ## GAEProxy set keep_running: True

**Comment by forjiuzhou** [comment]
删除data文件夹后正常。发现issue下有很多类似问题

**Comment by jzp820927** [comment]
试试能不能正常代理 https 网站，能正常代理就行了吧

**Comment by magnet1215** [comment]
@jzp820927 删了data后，运行显示
Jul 22 10:57:18.298 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
Jul 22 10:57:18.320 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca

**Comment by jzp820927** [comment]
这个提示是让你导入证书

**Comment by hzjhzjhj** [comment]
去Documents and Settings 搜索cert.db8然后删掉，重起firefox即可。别的浏览器不清楚

**Comment by miaoqiucheng** [comment]
自动导入证书，需安装 libnss3-tools 包
sudo apt-get install libnss3-tools

**Comment by decemer** [comment]
same issue libnss3-tools alreday installed 已经是最新版 (2:3.26.2-0ubuntu0.16.04.2)。

**Comment by jzp820927** [comment]
也是证书安装不了？

**Comment by decemer** [comment]
yes ubuntu

**Comment by jzp820927** [comment]
Linux 安装证书比较麻烦。建议你 google 搜索一下 linux 证书安装方法。
