### ISSUE TITLE
Google Scholar验证机器人失败

### ISSUE THREAD

**Issue by hairuo** [XX-net/XX-Net#3913]
- XX-Net版本 3.2.5， windows 7,  chrome Version 51.0.2704.106 m

- 使用Google Scholar可能因为搜索次数过多，昨天开始要求验证为非机器人。搜索任何关键词后总是显示页面为：Please show you're not a robot, 然后下面有个点击确认"I am not a robot".点击无响应。

- 等了一天再使用google scholar，发现还是没有解封。

- XX-net的日志如下, 其中artificial+intelligence为搜索关键词：

Jul 21 15:57:28.132 - [DEBUG] host_conn_pool scholar.google.com get:202.75.147.35 handshake:265
Jul 21 15:57:28.180 - [INFO] GAE t:456 s:627 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D get_response:453
Jul 21 15:57:28.192 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
Jul 21 15:57:28.652 - [INFO] GAE t:460 s:401 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D get_response:459
Jul 21 15:57:28.687 - [INFO] DIRECT chucked t:555 s:18672 200 scholar.google.com /scholar?q=artificial+intelligence&btnG=&hl=en&as_sdt=0%2C5
Jul 21 15:57:28.739 - [DEBUG] GAE GET https://www.google.com/recaptcha/api.js?onload=gs_captcha_cb&render=explicit&hl=en
Jul 21 15:57:29.087 - [INFO] GAE t:347 s:344 GET https://www.google.com/recaptcha/api.js?onload=gs_captcha_cb&render=explicit&hl=en h2_get_head:344
Jul 21 15:57:29.135 - [DEBUG] GAE GET https://www.google.com/recaptcha/api2/anchor?k=6LfFDwUTAAAAAIyC8IeC3aGLqVpvrB6ZpkfmAibj&co=aHR0cHM6Ly9zY2hvbGFyLmdvb2dsZS5jb206NDQz&hl=en&v=r20160712125018&size=normal&cb=k00d9bc3861x
Jul 21 15:57:29.500 - [INFO] GAE t:365 s:12711 GET https://www.google.com/recaptcha/api2/anchor?k=6LfFDwUTAAAAAIyC8IeC3aGLqVpvrB6ZpkfmAibj&co=aHR0cHM6Ly9zY2hvbGFyLmdvb2dsZS5jb206NDQz&hl=en&v=r20160712125018&size=normal&cb=k00d9bc3861x h2_get_head:353,h2_finish[SP:1306501]:9
Jul 21 15:57:29.606 - [DEBUG] GAE GET https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=r20160712125018
Jul 21 15:57:29.939 - [INFO] GAE t:332 s:99 GET https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=r20160712125018 get_response:332
Jul 21 15:57:38.708 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
Jul 21 15:57:39.260 - [INFO] GAE t:552 s:5263 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D get_response:549,h2_finish[SP:2850866]:2
Jul 21 15:57:39.286 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D
Jul 21 15:57:39.760 - [INFO] GAE t:473 s:490 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Rz8uW4pYrD5llITJH8pzBw%3D%3D h2_get_head:469

- 之前遇到过类似问题，后续升级XX-net版本后解决了：
https://github.com/XX-net/XX-Net/issues/3202

谢谢！

**Comment by jzp820927** [comment]
设置直连模式试试

**Comment by hairuo** [comment]
直连网页都打不开啊。

**Comment by jzp820927** [comment]
我说的是 xx 中的 [hosts] 中配置 scholar.google.com = direct，不是直接打开网站

**Comment by hairuo** [comment]
哦，好的，今天已经恢复正常，下次再试试。谢谢！

**Comment by tengjunhui123** [comment]
@jzp820927 我的也是谷歌认证不了，一直转圈- -我的是各种免费领steam游戏的网站~好几天了

**Comment by tengjunhui123** [comment]
@jzp820927 别的帖子找到了解决办法(⊙ｏ⊙)
data/gae_proxy文件夹新建一个manual.ini文件，里面加入以下内容

[hosts]
.google.com = direct
@yeahwu 能不能修复一下这个，要不每次都直接麻烦，嘻嘻~

**Comment by jzp820927** [comment]
manual.ini 这个文件是用户自定义文件，你只要定义一次，以后都可以生效，就算是升级也不影响。

**Comment by hairuo** [comment]
今天用google scholar，一如既往点击搜索结构的条目下的import into bibtex或着more->cite->endnote，
提示：
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.

//以前都是提示如下的：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

//另外，我是默认已经在data\gae_proxy下新建了manual.ini并包括内容如下的：
[hosts]
.google.com = direct

//XX-Net默认是更新到最新测试版的，目前使用版本是：3.2.6。系统Win7

谢谢！

**Comment by jzp820927** [comment]
挺诡异的，现在好像直连模式，也经常有这种问题，是不是大家都用直连模式了，直连模式的流量也多起来了，而且直连模式的 IP 应该比较集中。

**Comment by whimian** [comment]
现在我这里又出现这个问题了

**Comment by JmingZhang** [comment]
我也是最近一直是这个问题，可以正常浏览，导入endnote就有问题- -

**Comment by zhuoquanzhou** [comment]
将那个出现问题的网址也加入直联模式就行
scholar.googleusercontent.com = direct

**Comment by hairuo** [comment]
@zhuoquanzhou 果然管用，非常感谢!!!

**Comment by hairuo** [comment]
在manual.ini中添加
scholar.googleusercontent.com = direct
.google.com = direct
使用至今完好，今天同样点击" Import into BibTeX"开始出现问题如下：

chrome地址转向如下开头：
https://ipv4.google.com/sorry/IndexRedirect?continue=https://scholar.googleusercontent.com/scholar.bib%3Fq%3Dinfo:aGbbhM7BtvYJ:scholar.google.com/%26output%3Dcitation%26scisig%

显示chrome标签名：
504 GAEProxy Proxy Time out

chrome显示内容：
Message
连接超时，先休息一会儿再来！

**Comment by jzp820927** [comment]
把 ipv4.google.com 换成 www.google.com 试试

**Comment by hairuo** [comment]
现在自动又好了，可能是电脑恢复ipv6设置了。下次遇到再试试，谢谢回复!
