### ISSUE TITLE
xx-net启动之后本地的DNS受到污染，导致所有网页访问不了。

### ISSUE THREAD

**Issue by guotieman** [XX-net/XX-Net#3914]
再启动xx-net一段时间后，本地所有浏览器都不能访问任何页面。网站的主机也不能ping通，显示找不到主机。退出xx-net一段时间后，可以使用浏览器正常访问网站了。诊断网络发现DNS出了问题。我的一台MAC和一台windows电脑，都出现了同样的问题。
这个是xx-net的问题还是我的电脑的问题？

**Comment by jzp820927** [comment]
XX 和 DNS 有什么关系？XX 又不会去改 系统 DNS。是不是你启动 XX 设置了全局代理，导致所有流量都走了代理

**Comment by guotieman** [comment]
当然不是全局代理。即使是全局代理，不会造成所有的网站访问不了。

**Comment by jzp820927** [comment]
反正可以肯定的是，XX 不会影响 DNS，你应该检查下其他地方

**Comment by FinalAgito** [comment]
可以试着关掉浏览器的代理服务器试试

**Comment by guotieman** [comment]
确实不是浏览器的问题，昨天我直接ping 网站的ip地址都ping不同了。只好识别的方法了。

**Comment by guotieman** [comment]
问题找到了。公司网管将网络连接数大于500的机器的数据包全部丢掉了，所以出现所有网站不能访问的情况。

**Comment by jzp820927** [comment]
你们网管太狠了。

**Comment by FinalAgito** [comment]
....简直了
