### ISSUE TITLE
Win10无法启动xx-net3.1.19：launcher except:WindowsError(5, '')

### ISSUE THREAD

**Issue by appleshowc** [XX-net/XX-Net#3915]
操作系统：
win10 专业版 1151 x64

运行start.bat出现如下信息：
Jul 22 09:59:11.924 - [INFO] use build-in openssl lib
Jul 22 09:59:11.959 - [INFO] start XX-Net 3.1.19
Jul 22 09:59:11.959 - [DEBUG] start confirm_xxnet_exit
Jul 22 09:59:12.974 - [DEBUG] good, xxnet:8087 cleared!
Jul 22 09:59:13.978 - [DEBUG] good, xxnet:8085 clear!
Jul 22 09:59:13.979 - [DEBUG] finished confirm_xxnet_exit
Jul 22 09:59:14.004 - [ERROR] launcher except:WindowsError(5, '')
Jul 22 09:59:14.007 - [ERROR] Except stack:Traceback (most recent call last):
  File "F:\XX-Net-3.1.19\code\default\launcher\start.py", line 182, in <module>
    main()
  File "F:\XX-Net-3.1.19\code\default\launcher\start.py", line 155, in main
    post_update.run(last_run_version)
  File "F:\XX-Net-3.1.19\code\default\launcher\post_update.py", line 28, in run
    shutil.rmtree(os.path.join(top_path, 'launcher')) # launcher is for auto-update from 2.X
  File "F:\XX-Net-3.1.19\code\default\python27\1.0\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "F:\XX-Net-3.1.19\code\default\python27\1.0\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] : 'F:\\XX-Net-3.1.19\\launcher\\DO_NOT_PUT_ANYTHING_HERE'

**Comment by jzp820927** [comment]
下载最新版试试

**Comment by appleshowc** [comment]
这就是最新的稳定版啊

**Comment by jzp820927** [comment]
你这个是 3.1.19
最新的已经是 3.2.6 了

**Comment by appleshowc** [comment]
那是测试版啊，我下的是稳定版 最新的

**Comment by appleshowc** [comment]
试了测试最新版的 报一样的错 求解答~~~

**Comment by jzp820927** [comment]
没看明白你这个报错是什么意思，等Y大来看吧

**Comment by yaoguaishou** [comment]
F:\XX-Net-3.1.19\launcher\DO_NOT_PUT_ANYTHING_HERE 拒绝访问

**Comment by yeahwu** [comment]
试试下面这个版本，
https://github.com/XX-net/XX-Net/archive/3.2.0.zip

**Comment by appleshowc** [comment]
不管试那个版本，都出现如上错误，谢谢各位的帮助~
最终解决方案如下：
因本人是用微软账户登录win10的，虽然系统显示是管理员，但其实权限不够。
对xx-net的文件夹右击，选择 属性->安全，给当前用户附上所有权限，再次启动bat成功运行。
