### ISSUE TITLE
ios 局域网内翻墙

### ISSUE THREAD

**Issue by shankin** [XX-net/XX-Net#3917]
需求：
希望手机能通过台式机电脑xx-net代理翻墙上网：
已经在电脑上安装usb无线网卡，用软件虚拟出一个wifi热点abc
CMD/ipconfig情况如下：

### **以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::f947:b1b2:d3d2:235%20
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.34
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.1.13

无线局域网适配器 本地连接* 12:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::2038:6e45:1872:f2f0%6
   IPv4 地址 . . . . . . . . . . . . : 192.16.137.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0**

**1,**xx-ne版本3.2.5

**2.**在"XX-Net\data\gae_proxy"目录下建立manual.ini文件：
   文件内容如下：
[listen]
ip = 0.0.0.0
port = 8087

[gae]
appid =（（我的appid））
password =

[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**3.**手机配置
iPHone6 连接wifi热点abc
wifi下面 http代理http://192.16.137.1:8086/proxy.pac或者http://192.168.1.34:8086/proxy.pac

**4.**电脑上打开XX-NET 配置里打开 **允许远程连接Web控制端**

**5.**打开192.16.137.1:8085或者192.168.1.34:8085 下载证书

手机浏览器输入m.taobao.com,直接跳转到m.intl.taobao.com (应该是淘宝国际)
但是打不开google、facebook、和twitter,国内的网站打开没问题
电脑上facebook twitter和google都一切正常
求解

XXNET日志：
Jul 22 09:58:52.249 - [INFO] SSL use version:TLSv1_2
Jul 22 09:58:52.860 - [INFO] OpenSSL support alpn
Jul 22 09:58:52.861 - [INFO] load ip range file:D:\Program Files\XX-Net\code\3.2.5\gae_proxy\local\ip_range.txt
Jul 22 09:58:52.877 - [INFO] detected Win10, enable connect concurrency control, interval:40
Jul 22 09:58:52.896 - [INFO] load google ip_list num:3000, gws num:3000
Jul 22 09:58:52.907 - [INFO] OpenSSL support alpn
Jul 22 09:58:52.908 - [DEBUG] get ip:202.75.141.235 t:131
Jul 22 09:58:52.909 - [DEBUG] get ip:113.171.253.18 t:187
Jul 22 09:58:52.913 - [DEBUG] ## GAEProxy set keep_running: True
Jul 22 09:58:52.913 - [INFO] ------------------------------------------------------
Jul 22 09:58:52.913 - [INFO] Python Version : 2.7.11
Jul 22 09:58:52.914 - [INFO] OS : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Jul 22 09:58:52.914 - [INFO] Listen Address : 127.0.0.1:8087
Jul 22 09:58:52.914 - [INFO] GAE APPID : 不可见
Jul 22 09:58:52.914 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jul 22 09:58:52.914 - [INFO] ------------------------------------------------------
Jul 22 09:58:53.220 - [DEBUG] create_ssl update ip:202.75.141.235 time:200 h2:0
Jul 22 09:58:53.220 - [DEBUG] get ip:203.252.15.176 t:190
Jul 22 09:58:53.257 - [DEBUG] network is ok, cost:1236 ms
Jul 22 09:58:53.330 - [DEBUG] create_ssl update ip:113.171.253.18 time:248 h2:0
Jul 22 09:58:53.410 - [DEBUG] get ip:202.75.141.229 t:207
Jul 22 09:58:53.586 - [DEBUG] create_ssl update ip:203.252.15.176 time:236 h2:0
Jul 22 09:58:54.005 - [DEBUG] create_ssl update ip:202.75.141.229 time:202 h2:1
Jul 22 09:58:54.059 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Jul 22 09:58:54.068 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=c535ca76-c3f1-45bf-acff-f6f01ff5cffb&version=3.2.5&platform=Windows-10-10.0.10586
Jul 22 09:58:54.331 - [DEBUG] get ip:202.75.141.222 t:210
Jul 22 09:58:54.379 - [INFO] DIRECT t:309 s:1674 200 xxnet-update.appspot.com /update.json?uuid=c535ca76-c3f1-45bf-acff-f6f01ff5cffb&version=3.2.5&platform=Windows-10-10.0.10586
Jul 22 09:58:55.032 - [DEBUG] create_ssl update ip:202.75.141.222 time:213 h2:0
Jul 22 09:58:58.903 - [INFO] PAC from:127.0.0.1:10659 GET /proxy.pac
Jul 22 09:58:58.906 - [INFO] PAC from:127.0.0.1:10660 GET /proxy.pac
Jul 22 09:58:58.912 - [INFO] PAC from:127.0.0.1:10661 GET /proxy.pac
Jul 22 09:59:41.949 - [DEBUG] 202.75.141.235 close:host pool alive_timeout

**Comment by jzp820927** [comment]
导入证书了没？要导入路由上面生成的证书

**Comment by shankin** [comment]
@jzp820927 ios下证书以描述文件导入了。
问题找到了，是windows记事本的问题，用了notepad++和editplus编辑都没问题！
回头看看这个问题其实好简单啊 ，只要改[listen[和[pac]下面的两个ip地址以及输入自己的appid就好
