### ISSUE TITLE
一个不相关的高深的问题

### ISSUE THREAD

**Issue by littlebigdream** [XX-net/XX-Net#3918]
本人 WIN10 专业版 x64.

想让 系统 的 所有网络连接 都走代理shadowsocks. 就像 VPN一样。

请问如何实现？ 有人知道吗？？感谢告知。

**Comment by wenliyang** [comment]
你的需求，只有VPN能实现

**Comment by jzp820927** [comment]
也可以靠 第三方软件实现

**Comment by yaoguaishou** [comment]
proxifier

**Comment by Wrecking-Ball** [comment]
proxifier 试过了，只是部分网络连接走代理。。。。

**Comment by jzp820927** [comment]
那应该是你设置问题吧

**Comment by Wrecking-Ball** [comment]
我感觉应该没问题，我规则设置的是默认走shadowsocks.

**Comment by jzp820927** [comment]
那你是怎么确定只有部分连接走了代理的？

**Comment by Wrecking-Ball** [comment]
minecraft 官方启动器首页是空白。。。。

**Comment by jzp820927** [comment]
或者可以试试看看日志，能不能发现什么问题。
