### ISSUE TITLE
打开谷歌提示不受信任的连接,已添加CA证书。GoAgent v3.1.49的这个窗口不能够最小化？

### ISSUE THREAD

**Issue by shinji-ikari** [XX-net/XX-Net#392]
Property 	Value
Sys Platform 	win32
OS System 	Windows
OS version 	5.1.2600
OS release 	XP
OS detail 	Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
language 	zh_CN
architecture 	32bitWindowsPE
Browser 	Mozilla/5.0 (Windows NT 5.1; rv:37.0) Gecko/20100101 Firefox/37.0
XX-Net Version 	1.13.6
Launcher Version 	1.4.0
GoAgent Version 	3.1.49
Python Version 	2.7.9
Proxy Listen 	127.0.0.1:8087
**************
用的是稳定版1.13.6.刚下载.已经设置自己用的APPID,并且重新上传.
问题如题目所示.打开谷歌一直提示不受信任的连接,证书已经添加了进去.(记得GoAgent的时候只要添加了证书就不会有这个问题了吧?)
看了一下.貌似所有用GoAgent端口走代理的都提示连接不受信任了.python.exe的窗口会显示这个↓
[warning]method connect not support in goagent for www.youtube.com:443
[warnning]direct_handler err:error<10053,''>www.google.com www.google.com:443 time:0
**************
<del>然后就是GoAgent v3.1.49的这个窗口一直都在.不能够最小化到托盘么?试过点X关掉结果整个程序都关了.
运行是点的START.bat </del>
运行START.VBS就可以.

**Comment by xxnet** [comment]
用start.vbs启动就没有窗口出现。

证书在data/goagent/CA.crt，再试试导入

在 2015年5月12日 上午3:54，shinji-ikari <notifications@github.com>写道：

**Comment by shinji-ikari** [comment]
证书名字 GoAgent xx-net  服务器 * 生命周期 永久 过期时间  2025-5-11
确定是这个证书了吧?,路径也是data/goagent/ca.crt

状况依旧

**Comment by xxnet** [comment]
请升级到最新版，并重新生成证书（如果data/goagent/CA.crt存在，请删除）。

解释一下，之前的代码中，XP下的证书还是使用SHA1签名，而新的Chrome要求SHA256签名。


在 2015年5月12日 上午5:23，shinji-ikari <notifications@github.com>写道：

**Comment by shinji-ikari** [comment]
换了1.14.3,直接删掉旧版文件夹,用新版的.
对了.用的是 FIRE FOX.并不是CHROME浏览器.难道不支持FIRE FOX?
删除了CA证书.重新运行XX-NET自动生成了一个.每次打开都会提示"已经导入GoAgent证书.请重启浏览器"
问题是,手动点开证书查看还是没有,手动添加了证书之后.关掉FF重开.打开谷歌还是"不受信任的连接".

**Comment by xxnet** [comment]
试过XP下 Firefox，可以正常使用访问啊。

你能否试试chrome？

2015-05-12 8:27 GMT-04:00 shinji-ikari <notifications@github.com>:

**Comment by shinji-ikari** [comment]
又回去倒腾GoAgent了.找了几个可用IP.暂时先这样了吧.CHROME以前用过.占用太高网页多开几个就卡机子.

**Comment by xxnet** [comment]
Chrome好像内存占用多一点，加点内存吧

在 2015年5月12日 下午3:49，shinji-ikari <notifications@github.com>写道：

**Comment by shinji-ikari** [comment]
刚才继续测试了一次.还是这样的情况.就是搞不懂了.
GoAgent的话完全不会.理由真心莫名其妙了.@XXNET 要是有空的话.远程看看不?

**Comment by xxnet** [comment]
试试IE?

在 2015年5月13日 上午1:31，shinji-ikari <notifications@github.com>写道：

**Comment by shinji-ikari** [comment]
IE?这个还真没试过.怎么设置?

**Comment by xxnet** [comment]
系统托盘右键菜单里，点全局GoAgent，然后启动（重启）IE

2015-05-13 2:31 GMT-04:00 shinji-ikari <notifications@github.com>:

**Comment by shinji-ikari** [comment]
点了全局代理之后.窗口会显示这个.然后IE打开YOUTUBE跟GOOGLE.COM.先是跳到必应搜索.然后就算点链接打开GOOGLE.COM(您输入的网址无法访问！)或者YOUTUBE.COM.(  无法找到该网页 )
****
May 13 17:03:03 - [DEBUG] get ip:212.188.7.99 t:780
May 13 17:03:03 - [INFO] set register path:<PyHKEY object at 0x00B5C640> name:Au
toConfigURL type:1 value:
May 13 17:03:03 - [INFO] set register path:<PyHKEY object at 0x00B5C640> name:Pr
oxyEnable type:4 value:1
May 13 17:03:03 - [INFO] set register path:<PyHKEY object at 0x00B5C640> name:Pr
oxyOverride type:1 value:*.local;<local>
May 13 17:03:03 - [INFO] set register path:<PyHKEY object at 0x00B5C640> name:Pr
oxyServer type:1 value:127.0.0.1:8087
May 13 17:03:05 - [DEBUG] create_ssl 103.25.178.34 fail:timed out cost:4000 h:0
May 13 17:03:05 - [DEBUG] create_ssl 210.139.253.84 fail:timed out cost:4000 h:0

**Comment by eDracula** [comment]
可能是杀毒软件的问题，我最近也出现了这种情况，重新安装证书也解决不了。结果发现是BitDefender的Web Protect的Scan SSL在作祟，关闭即可

**Comment by shinji-ikari** [comment]
没有装杀毒.也就一个360安全卫士,把XX-NET添加了白名单.
