### ISSUE TITLE
最近ip掉的好快

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#3921]
月初的时候还有6000+ip，中旬的时候有3000+吧，大致是这样。这两天因大雨断网，没用，今天网好了，刚打开的时候，ip还有1000+，这会一看竟然只剩37个了，明天不知道还剩几个。。。
难道最近墙又加高了？
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2790.0 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:9508 good:37
network-status: OK
connected-link: new:2 used:0
worker: h1:25 h2:10
scan-ip-thread-num: 0
ip-quality: 157
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
实在不行，就删了data，重新扫嘛

**Comment by zzgpku** [comment]
@jzp820927 等到没ip了再删，先这样，目前不影响使用

**Comment by jzp820927** [comment]
IP 波动是很正常的。

**Comment by yeahwu** [comment]
你开的是ipv6好吧！
天朝屁民 <notifications@github.com>于2016年7月22日 周五22:47写道：

**Comment by zzgpku** [comment]
@yeahwu ipv6 也是ip，也会掉的。不过学校ipv4几乎搜不出ip来

**Comment by Lemonjay** [comment]
在学校通过ipv6翻墙，快的很，在外面ipv4找不到好的ip，看YouTube卡的很，有什么好的方法找ip吗？

**Comment by jzp820927** [comment]
好IP失效很快
