### ISSUE TITLE
显示安全连接失败

### ISSUE THREAD

**Issue by LuoXiangyu** [XX-net/XX-Net#3925]
firefox显示安全连接失败，点击重试后正常.证书已导入(chrome正常）【已尝试重新导入证书】

安全连接失败

载入页面时与 mail.google.com 的连接被中断。

    您尝试查看的页面无法显示，因为已收到数据的可靠性无法证实。
    请联系此网站的管理员并告知此问题。

详细了解…（其他访问失败的内容类似）
顺便问一下chrome+XX-NET会突然卡死，firxfox正常

**Comment by jzp820927** [comment]
firxfox 的证书是独立于系统证书的，所以要单独导入

**Comment by LuoXiangyu** [comment]
已经单独导入

**Comment by wenliyang** [comment]
和 XX-Net 无关，或者多刷新几次，或者关掉火狐设置里的“查询 OSCP 响应服务器以确认证书的当前有效性”

**Comment by LuoXiangyu** [comment]
还是存在

**Comment by LuoXiangyu** [comment]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:47.0) Gecko/20100101 Firefox/47.0
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1047 good:1006
network-status: OK
connected-link: new:2 used:0
worker: h1:17 h2:10
scan-ip-thread-num: 50
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
firefox显示安全连接失败，这个提示，肯定是证书问题，实在不行，就删除 data 重新生成证书，再导入

**Comment by LuoXiangyu** [comment]
已删除 data 重新生成证书，再导入。问题依旧

**Comment by yeahwu** [comment]
首先到浏览器里删除老证书，然后再导入新生成的证书。把浏览器证书列表里带`goagent`字样的证书全部删除后导入。

**Comment by LuoXiangyu** [comment]
问题依旧
安全连接失败

载入页面时与 translate.google.com 的连接被中断。

    您尝试查看的页面无法显示，因为已收到数据的可靠性无法证实。
    请联系此网站的管理员并告知此问题。

详细了解…（其他访问失败的内容类似）

**Comment by wenliyang** [comment]
@LuoXiangyu 你Firefox用的什么版本
不要使用中国版，如果用的中国版，请换成官网的中文版再试下
https://www.mozilla.org/en-US/firefox/all/

**Comment by LuoXiangyu** [comment]
不是Firefox中国版

**Comment by wenliyang** [comment]
在 Firefox 中新建用户配置文件，用新建的用户配置文件启动再试下
排除扩展等因素的问题

**Comment by jzp820927** [comment]
建议你换个浏览器试试（比如 chrome），好定位问题是出在 XX 还是 浏览器。

**Comment by LuoXiangyu** [comment]
chrome没问题

**Comment by LuoXiangyu** [comment]
发现ADGUARD的HTTPS广告拦截与XX-Net的证书冲突

**Comment by LuoXiangyu** [comment]
有办法解决冲突问题吗

**Comment by yeahwu** [comment]
解决办法：换别的代理

**Comment by LuoXiangyu** [comment]
好吧，只能选择一个的话，还是选择XX-Net吧

**Comment by jzp820927** [comment]
既然 chrome 没问题，换 chrome 用不就行了

**Comment by LuoXiangyu** [comment]
但是chrome会无故卡死
