### ISSUE TITLE
win10 Edge上不了google.com/ncr

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#3928]
Chrome可以上google.com/ncr，Edge上不了，提示代理服务器错误，但是可以上google.com.hk,虽然不影响但是强迫症啊不知道哪里出错了
![2016-07-23 1](https://cloud.githubusercontent.com/assets/17242539/17078506/a2609778-5127-11e6-96e9-27e604692fd5.png)
![2016-07-23 2](https://cloud.githubusercontent.com/assets/17242539/17078508/a33df49c-5127-11e6-92e3-3740b2f505c8.png)
![2016-07-23](https://cloud.githubusercontent.com/assets/17242539/17078507/a2655e02-5127-11e6-8b92-aaa525441c09.png)

**Comment by jzp820927** [comment]
https

**Comment by xiaoyan94** [comment]
![image](https://cloud.githubusercontent.com/assets/17242539/17082806/0c8f12b0-51bd-11e6-9ca1-1f263163c427.png)

还是不行

**Comment by jzp820927** [comment]
https://www.google.com/ncr

**Comment by kingour** [comment]
全局pac代理不就行了吗

**Comment by xiaoyan94** [comment]
#3947 这个解决了我的问题，解决方法就是在CMD下执行CheckNetIsolation LoopbackExempt -a -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe
