### ISSUE TITLE
如何确认xx-net确实在持续扫描IP？

### ISSUE THREAD

**Issue by OnionSalt** [XX-net/XX-Net#393]
开启xx-net一段时间后，状态页中的scan ip thread num会从20降到0，然后就一直保持在0，只有在扫描ip页中点击刷新，scan ip thread num才会重新变成20。

这个属于正常现象吗？大家情况如何？我怎么才能确定xx-net在持续扫描ip与否？
如果这不属于正常现象，要如何修复？

**Comment by xxnet** [comment]
似乎存在这个bug，我会研究，谢谢反馈

在 2015年5月12日 上午5:22，OnionSalt <notifications@github.com>写道：

**Comment by OnionSalt** [comment]
多谢关注，希望能尽快弄好，就是怕开了一晚结果没进展

**Comment by xxnet** [comment]
可以看看扫描页面的日志里，没有收获？

在 2015年5月12日 上午6:00，OnionSalt <notifications@github.com>写道：

**Comment by OnionSalt** [comment]
昨天晚上开了一晚，扫到不少ip，开到50扫的，早上依然是50，这次没出问题。
刚刚升级到16，应该以后也没问题了，多谢阿！！
