### ISSUE TITLE
为何加载不出ins

### ISSUE THREAD

**Issue by Tristanovo** [XX-net/XX-Net#3933]
RT

**Comment by YOYOsheep** [comment]
什么是ins？ instagram？

**Comment by jzp820927** [comment]
同问

**Comment by wenliyang** [comment]
估计是
楼主标题和内容都尽量简略，惜字如金，估计对解决问题兴趣不大

**Comment by Tristanovo** [comment]
就一个问题我需要说那么啰嗦吗，简单明了直奔主题不好吗， 哪来的制杖

**Comment by nxtreaming** [comment]
因为楼主本身就是个智障文艺青年，所以习惯说ins, 大家要包容些。

-----------------------------------------
Inspired by http://scale100.com

**Comment by Tristanovo** [comment]
@nxtreaming 我靠，我真无奈 问个问题引来俩智障东西，不知道可以不回复非要挑字眼来吗？你跟LS那个一个德行，非要逼我爆粗口 滚远点吧别回复了

**Comment by wenliyang** [comment]
建议楼主去学习一下《提问的艺术》

摘录：

当你提出问题的时候，首先要说明在此之前你干了些什么；这将有助于树立你的形象：你不是一个妄图不劳而获的乞讨者，不愿浪费别人的时间。如果提问者能从答案中学到东西，我们更乐于回答他的问题。

周全的思考，准备好你的问题，草率的发问只能得到草率的回答，或者根本得不到任何答案。越表现出在寻求帮助前为解决问题付出的努力，你越能得到实质性的帮助。
