### ISSUE TITLE
windows10 Powershell 怎么翻？？

### ISSUE THREAD

**Issue by FSD-Gaolei** [XX-net/XX-Net#3935]
有一个程序，需要读取twitter的数据，程序无出错的可能。Powershell能ping通谷歌，但是不能ping通twitter，是一个node.js程序，我该怎么做？？？

**Comment by jzp820927** [comment]
找个 hosts 文件吧

**Comment by FSD-Gaolei** [comment]
啊？？我听不懂哇，我的浏览器是可以正常翻的，没问题，但是Powershell就不行了

**Comment by jzp820927** [comment]
命令行一般不好处理

**Comment by FSD-Gaolei** [comment]
我好像能明白了，很感谢，大兄弟

**Comment by FSD-Gaolei** [comment]
问题结束
