### ISSUE TITLE
无论vbs或是bat都无法启动xx-net

### ISSUE THREAD

**Issue by bingsing** [XX-net/XX-Net#3936]
点击这两个都是闪退，无论是哪一个版本都不行，试过关闭防火墙也是不行。
win10系统

**Comment by yeahwu** [comment]
系统权限问题吧？

**Comment by bingsing** [comment]
那是什么权限问题？

**Comment by jzp820927** [comment]
邮件管理员权限打开

**Comment by bingsing** [comment]
什么邮件管理员权限?我是管理员打开的。

**Comment by jzp820927** [comment]
那就不知道是什么问题了

**Comment by q54528** [comment]
start.vbs提示证书导入成功，让重启浏览器。重启后，没见任何XXnet图标，全部系统图标里面也是。然后双击start.bat,窗口一直显示getip等。chrome设置switchomega为自动切换XXnet，google等都能上。
