### ISSUE TITLE
一切正常就是不能越墙

### ISSUE THREAD

**Issue by wangdeer** [XX-net/XX-Net#3940]
XX-Net 3.2.6，一切正常，你可以访问真正的互联网了。

全局PAC智能代理

![1](https://cloud.githubusercontent.com/assets/5895615/17099723/adc4aec6-529c-11e6-9054-e00e05dea6e0.png)
![2](https://cloud.githubusercontent.com/assets/5895615/17099725/ae82642a-529c-11e6-909a-0cdd51c38e93.png)

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1356 good:1074
network-status: OK
connected-link: new:2 used:0
worker: h1:3 h2:12
scan-ip-thread-num: 100
ip-quality: 236
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
用插件试试

**Comment by wenliyang** [comment]
全局通过GAEProxy代理呢，可以翻么

**Comment by neitherboy** [comment]
@jzp820927  用插件试了也不行
![image](https://cloud.githubusercontent.com/assets/5895615/17160909/66db9228-53db-11e6-9bfd-d43a6d01c79f.png)

**Comment by neitherboy** [comment]
@wenliyang  全局代理试过了  不行

**Comment by wenliyang** [comment]
既然楼主用了浏览器加扩展的方法 ，取消全局代理，试

**Comment by neitherboy** [comment]
@wenliyang  取消了呢。
 就是按照文档操作的，使用了扩展、取消全局代理。
不过还是不行。
![image](https://cloud.githubusercontent.com/assets/5895615/17161032/75be1418-53dc-11e6-9d04-b7f0fcac29bf.png)

**Comment by wenliyang** [comment]
@neitherboy 你在 SwitchyOmega 里选 XX-Net，而不要选择有自动切换的项，再试下

**Comment by neitherboy** [comment]
@wenliyang 选项都试过了哈 (┬＿┬)

**Comment by nly4lov** [comment]
@neitherboy 你是咋日弄的呢？不明觉厉。
下面是我给我的一个QQ群里的菜鸟们写的XXNET翻墙软件安装与设置简易教程
1.先安装GOOGLE CHROME，32位的下载http://pan.baidu.com/s/1kVfdynX，64位的下载http://pan.baidu.com/s/1pKFSMkb，下载后安装到系统中
2.http://pan.baidu.com/s/1hrCdrfu，下载这个SwitchyOmega.crx插件
3.http://pan.baidu.com/s/1sk9ddMl下载这个设置备份文件，
4.在CHROME的浏览器地址栏里输入chrome://extensions，把SwitchyOmega插件拉进extensions界面，自动安装，跳过向导，从文件恢复备份，浏览到OmegaOptions.bak,双击导入此备份后，点击GOOGLE chrome右上角的圆圈图标两两次，使出现绿色实心圈。
5.如不能安装SwitchyOmega,下载http://pan.baidu.com/s/1geAd0zD证书文件，然后点击chrome浏览器右上角的三个小横条，选择设置，点击弹出页面下部的高级设置，找到管理证书-导入-浏览到刚刚下载的CA证书-双击-下一步-选择放置证书的地点为受信任的根证书-确定导入，重启chrome浏览器，再进行步骤4即可安装switchyOmega了
6.下载http://pan.baidu.com/s/1eSCx9ia (3.2.4稳定版）或http://pan.baidu.com/s/1nuBTLqD （测试版），解压放到某个盘的program files目录下（或任意目录下），运行类似于D:\Program Files\XX-Net\code\default\launcher目录下的create_shortcut.js，桌面会生成快捷方式，双击此快捷方式后，即可实现翻墙，但此时是公用APPID，只能浏览网站，不能看视频。

**Comment by neitherboy** [comment]
@wenliyang  日志里面有报错
Jul 27 09:53:11.125 - [WARNING] session not running, can't connect
Jul 27 09:53:11.125 - [WARNING] create conn fail
Jul 27 09:53:11.129 - [WARNING] session not running, can't connect
Jul 27 09:53:11.129 - [WARNING] Socks4 connect fail, no conn_id

**Comment by neitherboy** [comment]
@jzp820927  @wenliyang  @nly4lov   把插件禁用、重新配置了下appid现在好了，原先也是同样的appid就是突然上不了。

**Comment by neitherboy** [comment]
@jzp820927  @wenliyang  @nly4lov   多谢各位帮忙！
