### ISSUE TITLE
HELP！Windows 10 Edge 浏览器 用不了 XX-Net 啊~

### ISSUE THREAD

**Issue by AntiGFW** [XX-net/XX-Net#3947]
### 求助！我使用的是最新测试版本（3.2.6），并按照使用手册成功完成了配置，**使用IE11和QQ浏览器的“极速模式”及“IE兼容模式”一切正常，可翻墙**；但**Edge 浏览器不能翻**，QQ浏览器的**“Edge模式”**亦不能翻。

- **具体表现为：**

1. Edge 浏览器无法打开 **127.0.0.1:8085**（XX-Net设置页面），提示**找不到网页**。
IE11和QQ浏览器可正常显示。

2. 无论使用**PAC代理**还是**系统全局代理**，Edge 浏览器及QQ浏览器的“Edge模式”均无法翻墙。

3. 将 XX-Net 切换为**系统全局代理**后，Edge 浏览器甚至无法上网**（墙内网站也打不开）**，提示**“代理服务器错误”**。

- **这是对应网址（仅可用Edge 浏览器打开）：**
`ms-appx-web://microsoft.microsoftedge/assets/errorpages/proxyerror.htm?ProxyDetail=127.0.0.1:8087#http://hao.qq.com/`

- **这是错误提示信息：**

> **无法连接到代理服务器
> 尝试此操作：
> •确保防火墙设置没有阻止 Web 访问
> •向你的系统管理员求助**

点击下方的**“Go to proxy settings”**按钮，会弹出**“设置”**窗口。

- **手动设置代理界面内容：**

> **代理服务器：**
>  `地址：127.0.0.1 端口：8087`
> **请勿对以下列条目开头的地址使用代理服务器：**
> `localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;172.32.*;192.168.*`
> 未勾选“请勿将代理服务器用于本地(Intranet)地址”。

**IE11及QQ浏览器基本不受影响。但QQ浏览器“Edge模式”不能翻墙。**

将 XX-Net 切换回**PAC智能代理**后，Edge浏览器可上**墙内网站**，但仍然**无法翻墙**。
- **手动设置代理界面内容：**
`脚本地址：http://127.0.0.1:8086/proxy.pac`

- **附：操作系统基本信息及诊断报告**

> **系统信息：Windows 10 家庭版 （x64）**

> **诊断信息（QQ浏览器极速模式）：**

```
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 Core/1.47.826.400 QQBrowser/9.4.8476.400
xxnet-version: 3.2.6
python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-status: 0
gws-ip-num: total:1269 good:1119
network-status: OK
connected-link: new:2 used:0
worker: h1:22 h2:5
scan-ip-thread-num: 500
ip-quality: 203
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
可参考：
1.https://github.com/XX-net/XX-Net/issues/3928
2.https://plus.google.com/+%E6%9D%8E%E6%AD%A5%E6%99%BA/posts/e2ZMBQPCYEK

**Comment by AntiGFW** [comment]
### 刚才发的诊断报告是在QQ浏览器**“极速模式”**下的诊断报告，系统提示**“一切正常”。**
下面是在QQ浏览器**“Edge模式”**下的诊断报告，系统提示**请检查浏览器代理设置。**

**【特别注明】Edge 浏览器无法打开 XX-Net 配置界面（127.0.0.1:8085）！！！**
```
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Core/1.47.826.400 QQBrowser/9.4.8476.400 Edge/12.10240
xxnet-version: 3.2.6
python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-status: 0
gws-ip-num: total:1316 good:1165
network-status: OK
connected-link: new:0 used:0
worker: h1:24 h2:0
scan-ip-thread-num: 500
ip-quality: 202
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by wenliyang** [comment]
微软的限制，试下这个方法：
http://zww.me/edge-browser-can-not-access-the-local-site.z-turn

**Comment by nly4lov** [comment]
有chrome不用，用什么edge啊

**Comment by AntiGFW** [comment]
@nly4lov  你没用过QQ浏览器吗？QQ浏览器是可以切换内核的，极速模式就是chrome，难道你不晓得？
好好看一下在“极速模式”下的诊断报告吧！

**Comment by AntiGFW** [comment]
### @wenliyang  按照你说的方法尝试，已成功打开设置界面，但仍然无法翻墙，系统提示**“请检查浏览器代理设置”**，切换**PAC模式**或**GAE全局代理**无任何反应！
**这是诊断报告：**
```
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
xxnet-version: 3.2.6
python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-status: 0
gws-ip-num: total:1677 good:1414
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 500
ip-quality: 155
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by wenliyang** [comment]
@AntiGFW 刚又找到一篇相关文章，转贴如下：
 
Microsoft Edge浏览器用上shadowsocks代理翻墙方法

1、windows 10 自带了一个程序：CheckNetIsolation.exe，通过它可以将指定的Metro程序添加到排除列表，让其可访问127.0.0.1。

具体方法：

① 找到你要挂代理的SID：Win键+R打开运行窗口，运行Regedit打开注册表管理器，找到以下注册表项：

HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Mappings

![qq 20150709110231](https://cloud.githubusercontent.com/assets/13804277/17161820/19cefa1c-53e3-11e6-9a08-387123fa89ed.png)

在Mappings项下找到你要挂代理的APP，比如我要将Microsoft edge挂代理，那么我要找到的结果如上图所示，窗口右侧DisplayName显示的就是这个APP的名字，而左边对应的项文件名就是这个APP的SID。

② 鼠标指针在屏幕左下角右键选择“命令提示符（管理员）”，打开CMD终端，在终端中输入命令：

CheckNetIsolation.exe loopbackexempt -a -p=② 鼠标指针在屏幕左下角右键选择“命令提示符（管理员）”，打开CMD终端，在终端中输入命令：

CheckNetIsolation.exe loopbackexempt -a -p=S-1-15-2-952914762-3925684122-2884453516-746264338-106963559-873903280-1628321774

![qq 20150709110330](https://cloud.githubusercontent.com/assets/13804277/17161832/3a6b6184-53e3-11e6-9cc5-66fcac2a58f5.png)

输入完成后，按回车键运行，提示完成后，即大功告成。
这样在edge上就可以用SS代理了！﻿

**Comment by xiaoyan94** [comment]
哈哈，用第一个方法我的问题解决啦~

**Comment by AntiGFW** [comment]
@wenliyang 还是不管用啊！问题同上。

**Comment by xiaoyan94** [comment]
@AntiGFW ca_state: Fail，是不是证书有问题？

**Comment by AntiGFW** [comment]
最新：Win10系统升级到10.0.14393（2016年8月3日更新），问题解决啦~
