### ISSUE TITLE
请问一下，目前一个谷歌账号能申请多少个APPID？

### ISSUE THREAD

**Issue by lingduwangjue** [XX-net/XX-Net#3951]
看之前的帖子说现在只能申请12个APPID。我的旧谷歌账号申请了25个APPID，今天新注册了一个谷歌 账号，咋申请了26个APPID？还有一个问题，旧账号的25个APPID会受影响么？

**Comment by nly4lov** [comment]
好流弊，我听说是10个啊

**Comment by jzp820927** [comment]
不确定，有些说，可以甚至30多个，有些说 20多个，有些说 10多个，可能有点随机性吧

**Comment by nly4lov** [comment]
我只申请了四个。事实上我觉得我好像一个的流量都用不完

**Comment by lingduwangjue** [comment]
我的旧账号申请了25个，用完了。今天又申请了26个。一天51G应该够用了~~

**Comment by heye521** [comment]
我申请了20个 绰绰有余了

**Comment by hcym** [comment]
比较乱，谷歌对这块不在意

妈的，就怕和reader一样

**Comment by q54528** [comment]
我就申请了8个，没试过上限，8G一天，怎么也用不完。

**Comment by RGordon24** [comment]
现在我还申请过四五十个的，早期的gmail账号只有25个。

**Comment by jzp820927** [comment]
你们都好 流弊 啊

**Comment by q54528** [comment]
看视频随意，不看视频哪里用得完

**Comment by nly4lov** [comment]
@lingduwangjue @RGordon24 你们都是用同一个账号申请了这么多的？

**Comment by nly4lov** [comment]
@q54528 哪有时间看视频啊，我电脑里电影都积压了130多G，都是2G左右一个的电影，都没时间看。有时间全用来看手机小说平板斗地主了

**Comment by lingduwangjue** [comment]
@nly4lov 是同一个账号。目前一个手机号可以绑定两个谷歌账号，我的旧谷歌账号申请了25个，新的谷歌账号申请了26了

**Comment by nly4lov** [comment]
![e103](https://cloud.githubusercontent.com/assets/11325411/17200245/32858002-54b6-11e6-8e45-6c449a41d8dc.gif)

**Comment by duskmoon314** [comment]
以前申请的，上限25个
经尝试，不能更多……

新账号不知道

**Comment by yqy6611** [comment]
当前是12个

**Comment by jzp820927** [comment]
我的3个号，申请的上限数都不一样，一个21，一个30多，一个24，感觉还是有随机性

**Comment by nobushige** [comment]
一个项目下最多10个id，超额需要申请。

**Comment by roc1010kmt** [comment]
一個手機號好像只能申請一個帳號,申請第二個帳號不讓用?

**Comment by jzp820927** [comment]
换手机
