### ISSUE TITLE
如何使用密码访问xx-net的代理

### ISSUE THREAD

**Issue by huchengbei** [XX-net/XX-Net#3958]
使用了很久了，但是想共享给手机用，但是8087代理只能在同一局域网内使用，离开电脑就不行，想把这个部署在我的服务器上，想知道能不能给xx-net放的代理加个密码啊，或者如何设置成一个类似vpn的东西。
只要能加密访问就行。
想请教有没有什么方案能解决。

**Comment by yaoguaishou** [comment]
手机只要有python环境都可以直接运行的

**Comment by jzp820927** [comment]
你说的加密，是指的 认证么？类似使用代理的时候，弹出窗口，要输入用户，密码，才能使用？

**Comment by john6193** [comment]
@huqiao1206  @jzp820927  我也希望有个用户登录认证这个模块，因为目前我的xx-net就是运行在我的服务器上，路由器也把8087端口转到xx-net的服务器上了，这样我在外地也可以用代理。但没有认证，任何人知道我开了这个端口，都可以用我的xx-net代理，确实增加不少风险。

**Comment by jzp820927** [comment]
如果需要认证，可以用 xxmini

**Comment by dlzdwxdt** [comment]
请问怎么设置局域网内共享?我把127.0.0.1改成了0.0.0.0并且插件里也改成了0.0.0.0但是本地就上不了网了

**Comment by jzp820927** [comment]
把你改的地方，贴出来看看

**Comment by dlzdwxdt** [comment]
找到原因了，防火墙把pythonw给BAN了，所以改成0.0.0.0就炸了，局域网内又把我手机连到电脑的通讯给BAN了，调整好规则就都好了
