### ISSUE TITLE
8085打不开了 托盘图标也没了 pythonw.exe进程还在 但是可以翻

### ISSUE THREAD

**Issue by xArbiterx** [XX-net/XX-Net#3968]
无法访问此网站

127.0.0.1 拒绝了我们的连接请求。
请试试以下办法：
重新加载网页
检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by jzp820927** [comment]
杀掉 pythonw.exe 经常，重新运行

**Comment by xArbiterx** [comment]
试过了 无效

**Comment by xArbiterx** [comment]
重启电脑好了 想问下这个是什么原因造成的

**Comment by jzp820927** [comment]
估计还有其他什么残留进程导致的

**Comment by yeahwu** [comment]
web界面打不开，两个原因
1:1080端口占用了
2:用的是全局代理

**Comment by vaseegoo** [comment]
我的也是这个原因怎么解决

**Comment by jzp820927** [comment]
web界面打不开，两个原因
1:1080端口占用了，也就是ss端口
2:用的是全局代理
