### ISSUE TITLE
计算机网络中存在异常流量

### ISSUE THREAD

**Issue by LuoXiangyu** [XX-net/XX-Net#3971]
我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。
XX-Net Status:

sys-platform: x86, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:47.0) Gecko/20100101 Firefox/47.0
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1509 good:1340
network-status: OK
connected-link: new:4 used:0
worker: h1:20 h2:1
scan-ip-thread-num: 100
ip-quality: 207
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
访问什么网站遇到这种问题？

**Comment by LuoXiangyu** [comment]
使用Google搜索
https://www.google.com

**Comment by yaoguaishou** [comment]
原因:代理访问'google'的人数太多,触到了他的G点

**Comment by jzp820927** [comment]
hosts 中改为直连试试

**Comment by LuoXiangyu** [comment]
怎么改

**Comment by jzp820927** [comment]
data/gae_proxy/manual.ini

[hosts]
scholar.google.com = direct
www.google.com = direct

需要什么域名直连，以此类推，自己添加就行了。

**Comment by yaoguaishou** [comment]
原来proxy.ini里面有这一行的

**Comment by LuoXiangyu** [comment]
加入后，问题再次出现

**Comment by yeahwu** [comment]
主要的是加入这一行
`.google.com = direct`
还有hosts只支持google类网站，其它无效
