### ISSUE TITLE
卧槽这个iP数量涨得不正常啊Σ(っ °Д °;)っ

### ISSUE THREAD

**Issue by yaoguaishou** [XX-net/XX-Net#3974]
还在以每分钟10-20个的速度增长

**Comment by yaoguaishou** [comment]
> https://s32.postimg.org/3mxw71u7p/2016_07_31_T08_26_31_246_Z.png

**Comment by yaoguaishou** [comment]
![_2016-07-31t08-26-31 246z](https://cloud.githubusercontent.com/assets/13164891/17275490/1b77c6ca-573d-11e6-99bc-899504db649b.png)

**Comment by yaoguaishou** [comment]
![_2016-07-31t08-38-17 720z](https://cloud.githubusercontent.com/assets/13164891/17275495/3c370f06-573d-11e6-8676-475b2f4b3c99.png)

**Comment by snoopygao** [comment]
不是最多3000吗

**Comment by jzp820927** [comment]
默认是你改过最大 IP 数，或者开了 开启了 IPv6

**Comment by nly4lov** [comment]
不明觉厉

**Comment by longsha911** [comment]
哦！不少

**Comment by xiaoyan94** [comment]
要那么多也没用

**Comment by yaoguaishou** [comment]
@xiaoyan94 看着舒服
