### ISSUE TITLE
听pandora音乐一直很慢，能改善下吗？或者我要怎么改下设置，改哪里？

### ISSUE THREAD

**Issue by entao** [XX-net/XX-Net#3975]
点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by jzp820927** [comment]
pandaro音乐 是神马咚咚？求科普。

**Comment by entao** [comment]
www.pandora.com 英文打错了 美国在线音乐，里面的歌很好听

**Comment by jzp820927** [comment]
行，我试试，给你反馈一下。你的意思是说慢？但是还是可以代理？那可能是不是你IP直连不加。

**Comment by entao** [comment]
有时候打得开 有时候打不开 听完一首歌到下一首歌有时候可以 有时候不可以 ，需要频繁刷新网页 ，直连肯定打不开 ，只针对美国地区

**Comment by jzp820927** [comment]
上面打错字了，我是要说，IP质量不佳。

**Comment by entao** [comment]
挂了好几天了，还好，google之类的快的多 只是这个有难度 电信的，你可以自己打开试试

**Comment by jzp820927** [comment]
测试过了，我能说，我这边流畅的1B么

**Comment by hcym** [comment]
最近韩国基本恢复

天凉些再找找日本的

**Comment by jzp820927** [comment]
IP数量都不成问题，主要是稳定性，低延时的IP现在也蛮多的，就是干扰太厉害。

**Comment by entao** [comment]
能否设置专用ip来打开pandora，我这里打开这个网站就是费劲

**Comment by jzp820927** [comment]
要不你试试 x_tunnel ？

**Comment by entao** [comment]
那收费的 不试

**Comment by jzp820927** [comment]
或者你可以换下 IP 试试，对比看看和 IP 有没有关系

**Comment by simonasd** [comment]
实测并不会比YouTube卡顿，广告播放也很流畅（斜眼）。

楼主可以对比一下pandora与YouTube，因为网页和流媒体不太一样，可能不好直接对比。

**Comment by entao** [comment]
又连续挂了几天 可能多了好多了 基本无障碍了 前几天听一首歌要刷新好几次
