### ISSUE TITLE
新手提问

### ISSUE THREAD

**Issue by beyondroot** [XX-net/XX-Net#4000]
1.怎样把网络分享给手机？搜了已有的issue没答案
2.修改的hosts文件直接跳过去了，能设置先读取hosts吗？（省流量）
3.一个appID一天流量1G,是从北京时间0点算起，还是美国时间0点？
新手莫见怪

**Comment by beyondroot** [comment]
XX-net 网速真的很给力

**Comment by jzp820927** [comment]
1.PAC
2.pac
3.美国时间0点

**Comment by yaoguaishou** [comment]
@beyondroot 手机使用gae比较麻烦,你需要把/CA.crt装载到存储卡,然后到"设置-安全"安装证书,全局代理建议使用postern

**Comment by jzp820927** [comment]
如果不想安装证书，也可以用 x_tunnel

**Comment by beyondroot** [comment]
@jzp820927 现在还有个问题，就是运行日志保存那个文件夹了？是不是关闭程序日志自动删除了？

**Comment by jzp820927** [comment]
日志在  data/gae_proxy/scan_ip.log
