### ISSUE TITLE
Can we access Netflix video with xx-net?

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#4009]
很简单的一个问题，用xx-net能不能在线看netflix视频呢？
我知道可以打开netflix网站，但是我没有购买会员，不知道购买会员之后能不能看视频。。
有没有谁知道啊？

**Comment by jzp820927** [comment]
只要能解除区域限制，应该就可以。

**Comment by yannhaur** [comment]
我试过了很多次，一直显示我未安装 SILVERLIGHT，虽然我也已经装了很多次。
不知是否该软件无法通过 XX－NET 链接。
有没有什么建议？

**Comment by jzp820927** [comment]
没有会员，无法测试

**Comment by cdmask** [comment]
俺也没有会员--把你的会员，借俺测试一下？@yannhaur

**Comment by yannhaur** [comment]
不好意思，会员也不是我自己的。
算了，战时使用别的。

**Comment by cdmask** [comment]
好滴 好滴：）

**Comment by hairuo** [comment]
可以在淘宝上购买1元的测试帐号来测试一下，比如这个：https://item.taobao.com/item.htm?spm=a230r.1.14.7.yIFLQ6&id=538219832554&ns=1&abbucket=6#detail

**Comment by cdmask** [comment]
@hairuo  谢谢。之前已经购买过了。xx-net不支持的，然后美国等地vpn，ss也不支持，日本，香港的ss可以用。
