### ISSUE TITLE
建议wiki添加proxy.ini里关于hosts的配置和原版的区别

### ISSUE THREAD

**Issue by 12c312312ceqsdcace123** [XX-net/XX-Net#401]
建议wiki添加proxy.ini里关于hosts的配置和原版的区别

**Comment by xxnet** [comment]
好

2015-05-12 17:12 GMT-04:00 12c312312ceqsdcace123 <notifications@github.com>:

**Comment by 12c312312ceqsdcace123** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
3q
