### ISSUE TITLE
请问XX-Net兼容goproxy r884 服务端吗?

### ISSUE THREAD

**Issue by kang000feng** [XX-net/XX-Net#4018]
我的appid 已经部署goproxy r884 服务端, 想用XX-Net来做客户端,请问要如何设置.  我在web ui 保存老提示appid无效,  请问XX-Net兼容服务端的goproxy 和goagent 服务端版本是多少? 多谢解惑!

**Comment by jzp820927** [comment]
goproxy 可以用 XX 的服务端，XX不能用 goproxy 的服务端，兼容部署 XX 的服务端，这样可以通用所有客户端
