### ISSUE TITLE
请问XX-Net兼容goproxy r884 服务端吗?

### ISSUE THREAD

**Issue by kang000feng** [XX-net/XX-Net#4019]
我的appid 已经部署goproxy r884 服务端, 想用XX-Net来做客户端,请问要如何设置.  我在web ui 保存老提示appid无效,  请问XX-Net兼容服务端的goproxy 和goagent 服务端版本是多少? 多谢解惑! @yeahwu

**Comment by phuslu** [comment]
这个算是 goproxy 或 GAE的锅。

GAE 的 go 环境生成的 cookie 是多行的，而 python 环境是单行的 cookie。

这导致两者不能通用。

理论上应该由 goproxy 的服务端来检测客户端类型来选择返回哪种类型的 cookie。 goproxy也有计划做这个事情。

可惜这个难度比预计的要大，在服务端较难实现。

所以就耽搁下来。

**Comment by kang000feng** [comment]
@phuslu 多谢社长解惑! 祝好! 保重!
