### ISSUE TITLE
部署失败，怎么办？重装系统了，以前能用的

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#4025]
Aug 09 16:53:15 - set proxy to http://127.0.0.1:8087 
Aug 09 16:53:15 - ============ Begin upload ============ 
appid:huangyuanwei1997 

Aug 09 16:53:15 - Application: huangyuanwei1997
Aug 09 16:53:15 - Host: appengine.google.com
Aug 09 16:53:15 - Rolling back the update.
Aug 09 16:53:47 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:53:47 - upload fail: HTTP Error 504: 

Aug 09 16:53:47 - Retry 1 time...

Aug 09 16:53:47 - Application: huangyuanwei1997
Aug 09 16:53:47 - Host: appengine.google.com
Aug 09 16:53:47 - Rolling back the update.
Aug 09 16:54:18 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:54:18 - upload fail: HTTP Error 504: 

Aug 09 16:54:18 - Retry 2 time...

Aug 09 16:54:19 - Application: huangyuanwei1997
Aug 09 16:54:19 - Host: appengine.google.com
Aug 09 16:54:19 - Rolling back the update.
Aug 09 16:54:50 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:54:50 - upload fail: HTTP Error 504: 

Aug 09 16:54:50 - Retry 3 time...

Aug 09 16:54:52 - ============ Begin upload ============ 
appid:huangyuanwei2012 

Aug 09 16:54:52 - Application: huangyuanwei2012
Aug 09 16:54:52 - Host: appengine.google.com
Aug 09 16:54:52 - Rolling back the update.
Aug 09 16:55:23 - upload fail: [Errno 9] Bad file descriptor

Aug 09 16:55:23 - Retry 1 time...

Aug 09 16:55:23 - Application: huangyuanwei2012
Aug 09 16:55:23 - Host: appengine.google.com
Aug 09 16:55:23 - Rolling back the update.
Aug 09 16:55:54 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:55:54 - upload fail: HTTP Error 504: 

Aug 09 16:55:54 - Retry 2 time...

Aug 09 16:55:55 - Application: huangyuanwei2012
Aug 09 16:55:55 - Host: appengine.google.com
Aug 09 16:55:55 - Rolling back the update.
Aug 09 16:56:26 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:56:26 - upload fail: HTTP Error 504: 

Aug 09 16:56:26 - Retry 3 time...

Aug 09 16:56:28 - ============ Begin upload ============ 
appid:huangyuanwei2015 

Aug 09 16:56:28 - Application: huangyuanwei2015
Aug 09 16:56:28 - Host: appengine.google.com
Aug 09 16:56:28 - Rolling back the update.
Aug 09 16:56:59 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:56:59 - upload fail: HTTP Error 504: 

Aug 09 16:56:59 - Retry 1 time...

Aug 09 16:56:59 - Application: huangyuanwei2015
Aug 09 16:56:59 - Host: appengine.google.com
Aug 09 16:56:59 - Rolling back the update.
Aug 09 16:57:30 - upload fail: [Errno 9] Bad file descriptor

Aug 09 16:57:30 - Retry 2 time...

Aug 09 16:57:31 - Application: huangyuanwei2015
Aug 09 16:57:31 - Host: appengine.google.com
Aug 09 16:57:31 - Rolling back the update.
Aug 09 16:58:02 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:58:02 - upload fail: HTTP Error 504: 

Aug 09 16:58:02 - Retry 3 time...

Aug 09 16:58:04 - ============ Begin upload ============ 
appid:huangyuanwei2013 

Aug 09 16:58:04 - Application: huangyuanwei2013
Aug 09 16:58:04 - Host: appengine.google.com
Aug 09 16:58:04 - Rolling back the update.
Aug 09 16:58:35 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:58:35 - upload fail: HTTP Error 504: 

Aug 09 16:58:35 - Retry 1 time...

Aug 09 16:58:35 - Application: huangyuanwei2013
Aug 09 16:58:35 - Host: appengine.google.com
Aug 09 16:58:35 - Rolling back the update.
Aug 09 16:59:06 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 16:59:06 - upload fail: HTTP Error 504: 

Aug 09 16:59:06 - Retry 2 time...

Aug 09 16:59:07 - Application: huangyuanwei2013
Aug 09 16:59:07 - Host: appengine.google.com
Aug 09 16:59:07 - Rolling back the update.
Aug 09 16:59:38 - upload fail: [Errno 9] Bad file descriptor

Aug 09 16:59:38 - Retry 3 time...

Aug 09 16:59:40 - ============ Begin upload ============ 
appid:huangyuanwei2011 

Aug 09 16:59:40 - Application: huangyuanwei2011
Aug 09 16:59:40 - Host: appengine.google.com
Aug 09 16:59:40 - Rolling back the update.
Aug 09 17:00:10 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 17:00:10 - upload fail: HTTP Error 504: 

Aug 09 17:00:10 - Retry 1 time...

Aug 09 17:00:10 - Application: huangyuanwei2011
Aug 09 17:00:10 - Host: appengine.google.com
Aug 09 17:00:10 - Rolling back the update.
Aug 09 17:00:41 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 17:00:41 - upload fail: HTTP Error 504: 

Aug 09 17:00:41 - Retry 2 time...

Aug 09 17:00:42 - Application: huangyuanwei2011
Aug 09 17:00:42 - Host: appengine.google.com
Aug 09 17:00:42 - Rolling back the update.
Aug 09 17:01:13 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 17:01:13 - upload fail: HTTP Error 504: 

Aug 09 17:01:13 - Retry 3 time...

Aug 09 17:01:15 - ============ Begin upload ============ 
appid:huangyuanwei2010 

Aug 09 17:01:15 - Application: huangyuanwei2010
Aug 09 17:01:15 - Host: appengine.google.com
Aug 09 17:01:15 - Rolling back the update.
Aug 09 17:01:46 - upload fail: [Errno 9] Bad file descriptor

Aug 09 17:01:46 - Retry 1 time...

Aug 09 17:01:46 - Application: huangyuanwei2010
Aug 09 17:01:46 - Host: appengine.google.com
Aug 09 17:01:46 - Rolling back the update.
Aug 09 17:02:07 - upload fail: ('The read operation timed out',)

Aug 09 17:02:07 - Retry 2 time...

Aug 09 17:02:10 - Application: huangyuanwei2010
Aug 09 17:02:10 - Host: appengine.google.com
Aug 09 17:02:11 - Rolling back the update.
Aug 09 17:02:52 - Error 504: --- begin server output ---

Message

连接超时，先休息一会再来！

--- end server output ---
Aug 09 17:02:52 - upload fail: HTTP Error 504: 

Aug 09 17:02:52 - Retry 3 time...

Aug 09 17:02:54 - =======================
Aug 09 17:02:54 - Deploy failed appid list:
Aug 09 17:02:54 - - huangyuanwei1997
Aug 09 17:02:54 - - huangyuanwei2012
Aug 09 17:02:54 - - huangyuanwei2015
Aug 09 17:02:54 - - huangyuanwei2013
Aug 09 17:02:54 - - huangyuanwei2011
Aug 09 17:02:54 - - huangyuanwei2010
Aug 09 17:02:54 - == END ==

**Comment by jzp820927** [comment]
应该是你的 GAE 不可用吧，估计还没扫到可用 IP

**Comment by LN-VIVI** [comment]
之前扫到有很多有用的IP，忘记备份了# #

**Comment by jzp820927** [comment]
等他运行一段时间，有可用 IP 了，就可以部署了

**Comment by LN-VIVI** [comment]
才扫到50个

**Comment by LN-VIVI** [comment]
之前上youtube很流畅能看1080P视频不卡的

**Comment by jzp820927** [comment]
以后记得要备份数据，特别是 扫描的 IP

**Comment by LN-VIVI** [comment]
QAQ
