### ISSUE TITLE
（not an issues）a human

### ISSUE THREAD

**Issue by beyondroot** [XX-net/XX-Net#4029]
Git 说我是机器人，怎破？
![](http://ww2.sinaimg.cn/large/0069EP5Mjw1f6nx5azqu5j30wk03xgm6.jpg)

**Comment by jzp820927** [comment]
由是走 gae 代理了吧

**Comment by yeahwu** [comment]
用注册邮箱发邮件给github，用英文，说明自己不是机器人就好了。这种情况俺也遇到过一次

**Comment by beyondroot** [comment]
恩，当天晚上发的，第二天就好了
