### ISSUE TITLE
Google reCAPTCHA 人机身份验证 一直转圈没反应

### ISSUE THREAD

**Issue by lumixx** [XX-net/XX-Net#4032]
出现好几个月了，只有一次成功了，其他时候包括现在都是一直转圈没有反应
是那种点击一个圆圈的
Chrome浏览器，试过换浏览器也没用

**Comment by jzp820927** [comment]
直连

**Comment by yeahwu** [comment]
google.com走直连就可以了，下面这一行改为`.google.com = direct`
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/proxy.ini#L37
也就是去掉前面的`;`号就好了
