### ISSUE TITLE
OpenWRT无法启动

### ISSUE THREAD

**Issue by TingyiChen** [XX-net/XX-Net#4042]
OpenWRT 15.05.1,python版本2.7.9,最新版本的无法打开,log:
root@OpenWrt:/mnt/sda1# python XX-Net/code/default/launcher/start.py
Traceback (most recent call last):
  File "XX-Net/code/default/launcher/start.py", line 37, in <module>
    from instances import xlog
  File "/mnt/sda1/XX-Net/code/default/launcher/instances.py", line 10, in <module>
    from xlog import Logger
  File "/mnt/sda1/XX-Net/code/default/python27/1.0/lib/noarch/xlog.py", line 8, in <module>
    import json
  File "/usr/lib/python2.7/json/**init**.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/lib/python2.7/json/decoder.py", line 24, in <module>
    NaN, PosInf, NegInf = _floatconstants()
  File "/usr/lib/python2.7/json/decoder.py", line 18, in _floatconstants
    _BYTES = '7FF80000000000007FF0000000000000'.decode('hex')
LookupError: no codec search functions registered: can't find encoding
这是python自己的问题吗？

**Comment by jzp820927** [comment]
可能是 python 的问题。是不是你的 python 不完整

**Comment by TingyiChen** [comment]
@jzp820927 装了openwrt的trunk分支的python全套

**Comment by jzp820927** [comment]
要不你试试 xxmini ？有人亲测，openwrt 最新的 trunk 分支，完美运行。

**Comment by gieaky** [comment]
重新安装一下python用 entware来安装python，获取后直接可以执行命令运行

**Comment by gieaky** [comment]
@jzp820927  XXmini能否添加自己的APPID呢，我现在是tomato使用的xx-net3.26

**Comment by jzp820927** [comment]
肯定可以啊，XXmini 就是提取自 XXNET 的精简版，处理 gae 和自动扫描，其他都精简掉了，很适合放在路由上，除了服务端要事先部署好，以后，其他的配置，和 XXNET一样，都可以在 ini 文件中配置。

**Comment by gieaky** [comment]
@jzp820927 那回头试试看用xxmini，我上次会网内自动翻墙不用设置好像就是用的精简版

**Comment by jzp820927** [comment]
客户端还是要设置代理才行啊，不用设置的那是 VPN

**Comment by gieaky** [comment]
@jzp820927 那就不知道上次是怎么搞得了,不过我发现,手机设置了PAC也照样不会自动翻墙

**Comment by jzp820927** [comment]
那应该是你还没配置正确。我这儿 PAC 没啥问题。

**Comment by TingyiChen** [comment]
@jzp820927 我现在放树莓派上面了，128M的内存XX和adbyby不能一起跑。。。openwrt的python和entware的好像有点不一样

**Comment by jzp820927** [comment]
核心都是一样的麽，都是 python

**Comment by TingyiChen** [comment]
@jzp820927 adbyby和xx-net一起跑内存不够。openwrt的python好像真的跑不起来xx.我树莓派和小米mini用op跑xx都报一样的错

**Comment by jzp820927** [comment]
具体什么报错，贴出来看看，或者可以试试 xxmini 有很多人都在 openwrt 上运行成功了。

**Comment by TingyiChen** [comment]
我xxmini跟xx都报我开始的那个错

**Comment by TingyiChen** [comment]
@jzp820927 找来找去都说是代码问题。。。

**Comment by jzp820927** [comment]
代码应该没问题，或者你可以试试，换个固件版本，重新刷机试试，或许是这个版本的固件的问题，也有可能。

**Comment by TingyiChen** [comment]
@jzp820927 路由器上面15.05.1和15.05都报错，树莓派我只试了15.05因为15.05.1的源是空的

**Comment by jzp820927** [comment]
我对 路由器的系统环境也不太熟悉，只有等高手来帮你了。或者你去 xxmini 的 issues 交流下吧，那边玩路由的也挺多的。不过好像这段时间没人说话。
