### ISSUE TITLE
xx-net 3.2.6 win10 设置局域网 手机上网根本不行 现在还能设置吗

### ISSUE THREAD

**Issue by entao** [XX-net/XX-Net#4053]
[listen]
ip = 0.0.0.0
port = 8087

[gae]
appid =（（我的appid））
password =

[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
这设置后连电脑都没法上网了 ，ios手机证书：8085也找不到，现在还能这样设置吗 是不是有所改动。

点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by jzp820927** [comment]
看你的设置没啥问题，不知道你手机是怎么设置的，详细说下，方便排查问题。

**Comment by entao** [comment]
gae proxy加上文件， 电脑都上不了网啦，手机正常设置 加上：8086 pac.然后8085访问证书根本打不开

**Comment by jzp820927** [comment]
首先确保电脑能用，如果电脑都不能正常使用，请帖出状态页，和日志。

**Comment by entao** [comment]
添加文件后直接打不开xx-net了，或者打开很困难，上网有问题

**Comment by xiaoyan94** [comment]
我的没问题 重新下一个试试

**Comment by entao** [comment]
今天又设置了一下 ，感觉xx有点抽风 还是我电脑慢，只是在手机导入证书那里过不去，输入：8085显示不了页面，换了其他方法导入证书后可以上网   http://www.realmb.com/droidCert/  不知道为什么，局域网里用的路由器，win10系统 ios7.1.2，不知道哪里被挡啦，还是什么情况

**Comment by jzp820927** [comment]
你的意思，现在是能用了？还是不能用？

**Comment by entao** [comment]
能用 打开网页，不过很遗憾Pandora在手机上只能用app,并且要ios8以上，我ios7,而且好像攻不破app走代理的问题，我理解正确吗

**Comment by jzp820927** [comment]
app 不一定都支持走代理。这是 app 自身的缺陷，和 XX 无关。
