### ISSUE TITLE
wrong pwd

### ISSUE THREAD

**Issue by MoguG** [XX-net/XX-Net#4055]
Wrong password('')

GoAgent proxy.ini password is wrong!
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: x86, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
xxnet-version: get_version_fail
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 1215,317
connected-link: 5,0
scan-ip-thread-num: 100
ip-handshake-10: 641
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by jzp820927** [comment]
秘密错误，如果你服务端设置了密码，客户端也要设置密码
