### ISSUE TITLE
MAC OS X 10.10.3 全局代理功能失效了

### ISSUE THREAD

**Issue by think2011** [XX-net/XX-Net#406]
XX-NET版本：1.14.8
系统版本：MAC OS X 10.10.3 

从顶部托盘启动的全局代理，接着输入授权密码，然后在 偏好设置-网络 中查看，并没有设置全局代理。

**Comment by xxnet** [comment]
请问你网络的名称是什么？

目前的XX-Net对网络名称兼容性没有做完善，如果网络名称比较不是默认的，就无法自动设置全局代理。
可以手动设置。

在 2015年5月14日 上午12:48，曾浩 <notifications@github.com>写道：

**Comment by think2011** [comment]
要在哪里可以查看自己的网络名称？

我是重新安装的系统，除了电脑名称，其他都是默认的，印象中以前的版本是有效的。

**Comment by xxnet** [comment]
Mac下的全局代理逻辑，是比较奇怪的。
  是针对具体的网络，比如有线网络、无限网络，各自定一个代理。
  如果你的网络不是Ethernet/Wi-Fi这种名字，就无法工作

在 2015年5月14日 上午3:07，曾浩 <notifications@github.com>写道：

**Comment by think2011** [comment]
@xxnet 噢，明白了，在公司用的是黑苹果，网络的名称是 USB WLAN。

**Comment by xxnet** [comment]
恩，这个要修复的，把所有网络设备枚举出来，然后逐个设置代理模式。

能否帮忙修复下？
代码在launcher/x.x.x/mac_tray.py


2015-05-14 16:52 GMT+08:00 曾浩 <notifications@github.com>:
