### ISSUE TITLE
打开google进行搜索时，提示私密连接问题

### ISSUE THREAD

**Issue by lafeed** [XX-net/XX-Net#4064]
访问网址：https：//www.google.com
错误提示::
您的连接不是私密连接
攻击者可能会试图从www.google.com.hk窃取您的信息（例如：密码、通讯内容或信用卡信息）。
----------------------------------------
您的连接不是私密连接

攻击者可能会试图从www.google.com.hk窃取您的信息（例如：密码、通讯内容或信用卡信息）。 **NET::ERR_CERT_DATE_INVALID
Subject: www.google.com.hk
Issuer: GoAgent XX-Net
Expires on: 2016年8月13日
Current date: 2016年8月16日**
PEM encoded chain: -----BEGIN CERTIFICATE-----
MIIDfjCCAmagAwIBAgIQPIIOmJJcQskukeoH8W5aEzANBgkqhkiG9w0BAQsFADBz
MQswCQYDVQQGEwJDTjERMA8GA1UECAwISW50ZXJuZXQxDzANBgNVBAcMBkNlcm5l
dDEQMA4GA1UECgwHR29BZ2VudDEVMBMGA1UECwwMR29BZ2VudCBSb290MRcwFQYD
VQQDDA5Hb0FnZW50IFhYLU5ldDAeFw0xNTA4MTQwODE2MDBaFw0xNjA4MTMwODI2
MDBaMIGCMQswCQYDVQQGEwJDTjERMA8GA1UECAwISW50ZXJuZXQxDzANBgNVBAcM
BkNlcm5ldDEXMBUGA1UECwwOR29BZ2VudCBCcmFuY2gxGjAYBgNVBAMMEXd3dy5n
b29nbGUuY29tLmhrMRowGAYDVQQKDBF3d3cuZ29vZ2xlLmNvbS5oazCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOZoKWWpdGJfQDSA0+u4VNbgO5ilrIlH
/UpguF4EBXZ/0sr//kizGFu1vH/u5CHPmJ1kBKhPycVmGpSWb7JmRx2lJd1PvAYs
HJHJIQdo8oQOQIXUBFtBB2mig6LdgRX3skHGBGEcNFdmKJlMaqGKUJnYWUz9svxR
QHflbYjOVyDpTk42xOaqeNVkUWmJ9yGKaliafMRRvp1ddn79/qar3j7OFWu+p5rA
zRbCe3SfvbhsjDXfWVfFJkvOi9u0TqZ2faIwZByKIXko6NmHy4cB+4BtmGWDDKkv
8keSN6eJ5cdPSkkRbDS1XlR6tvKRHDI1E3xqxUaLx2IwPQOYAGsDtf8CAwEAATAN
BgkqhkiG9w0BAQsFAAOCAQEAFd+iqD694nTx07KcQp9Xn0/TNY5zea8VAwX3sUNI
NW29d6YdHsfBVdcCod9D3JDYIwZZP2gSe3gJYPhJeYmQYBFbyy6X3GLJDcjPtVC1
vD5/epbans0zFPyQk/Kta/V7CsqPjr7nMHA5rBbLFehshSFyNa7/UT+Aq3BZcScS
wsolPG2yFn0GUGK9AF7uOCGT/VYLtJIcyGT0XAjjADeo3QkCIkHlCvpd32FbzUKJ
Ypg5vj2VFN3Wi2xd03mhirV8OsvlNhZeJHdwY4LA1D2HttBEGOUt8KxEBp8O1lXY
PtSwcOHIbnBCRHtTBcTqDGXPfvn1AUqF6L6PGONt74Nzbw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDWjCCAkICAQAwDQYJKoZIhvcNAQELBQAwczELMAkGA1UEBhMCQ04xETAPBgNV
BAgMCEludGVybmV0MQ8wDQYDVQQHDAZDZXJuZXQxEDAOBgNVBAoMB0dvQWdlbnQx
FTATBgNVBAsMDEdvQWdlbnQgUm9vdDEXMBUGA1UEAwwOR29BZ2VudCBYWC1OZXQw
HhcNMTUwODE0MDgyNTM2WhcNMjUwODEzMDgyNTM2WjBzMQswCQYDVQQGEwJDTjER
MA8GA1UECAwISW50ZXJuZXQxDzANBgNVBAcMBkNlcm5ldDEQMA4GA1UECgwHR29B
Z2VudDEVMBMGA1UECwwMR29BZ2VudCBSb290MRcwFQYDVQQDDA5Hb0FnZW50IFhY
LU5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKmnY+sVi1By9rm0
/yS7uOF+lKOc/yPZlk3RUGyfLEKD2+868X7GmHFCq5pi78aB4LIqGYATuvx8whZ0
LCp4xMhL/0UHv9hkFweUXwWMdbnyrhvndo3AYNkOAPWCfdWvZpCJQDGTqjs3KFU/
j0t2I55L49SwghTWVoKtB9LxON89vsb+Xlcf4+GMi+nL4ldfcxfvwRT0c9gcyFZW
zpKpJzqAosldoA84DBu65PvQsoe3b8Za4p3kD0KSvlT4dAMHRDvlmii8bruoZaVJ
2epoyOQdeTK98j1XD3lbmYrf/e7R+5aI66dtOVb56zNErfU2sTB9pEjQWXMhfCXj
++fH+BcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAKeEF1YQK6Q3JM3ZgghauyUxp
CR1EV3DnkPW9iAUYXy8eTkjn1hbxkSOB9ixqeXc5p9NUmn+MulL2q70fbSo4WS5f
yfXgXA2xVX2Iwm38KMt20BscUApdiztPclUnKmXfW4sl9yGxqcoq9Z1MUv4kjoFM
ic3j/GGyjEdLfSL0aksvPz+tUFr2e4ALjnpXEehN3ttXkCK4+NqoafwpLO/MuPg6
r8UlpUXfh/scyE50f56eFzIvQ7WtbXB8/y7k3ZXiFqwimqcx7kEZn0En1A/ub0dW
CXuFYNs2Q4A4QyqFh2cnqBwduoIZAgUvpmyfXk3TTCrZRtfwap2jDRo3wUOAgw==
-----END CERTIFICATE-----
-------------------------------------------------------
xxnet的配置信息
-------------------
roperty	Value
XX-Net Version	2.0.7
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	2248
100th IP handshake(ms)	709
connected link(帮助)	10,1
scaning ip thread num	50
block stat(帮助)	OK

**Comment by jzp820927** [comment]
导入证书

**Comment by lafeed** [comment]
导入证书了，还是不行

**Comment by lafeed** [comment]
https://www.facebook.com/
https://www.youtube.com/
以上的网站都可以正常访问，唯独google.com的网站不能访问，都提示：您的连接不是私密连接，攻击者可能会试图从www.google.com.hk窃取您的信息（例如：密码、通讯内容或信用卡信息）。

**Comment by jzp820927** [comment]
试试 ，https://www.google.com/ncr

**Comment by lafeed** [comment]
谢谢

**Comment by jzp820927** [comment]
问题解决了？google 可以访问了》

**Comment by snow8261** [comment]
我也遇到同样的问题，如何解决？
