### ISSUE TITLE
骂傻逼

### ISSUE THREAD

**Issue by panzer1313208** [XX-net/XX-Net#4065]
@EdwardAutumn 傻逼，你不是说我是骗子故意黑lantern么？嗯？擦你吗你看看现在lantern论坛全都他吗是骂他的。呵呵，时间会证明一切。

第一：为什么过了这么久，新线路和稳定性没有落实到位。

第二：为什么一个由团队维护开发的软件，竟然没有一个计费系统。

第三：为什么把反馈论坛建立在Github上。

第四：为什么因为3个傻逼在论坛里黑我，管理员直接ban我？是不是管理员因为我在论坛里说了一句实话然后害怕了？所以赶紧ban我？

**Comment by panzer1313208** [comment]
@p3rcya 顺便艾特下你，呵呵。

**Comment by panzer1313208** [comment]
https://github.com/getlantern/forum/issues，内几个黑我的，跟内个ban我的管理员啊，你们睁大眼睛看看论坛里都是一些什么问题？
退款？
怎么不能用？
公告？

**Comment by yeahwu** [comment]
这是反馈bug的地方，不是用来撕逼的。这里不提供战场，所以关闭了。对人对事不要伤及无辜！

**Comment by panzer1313208** [comment]
OK，关闭就关闭，能回复就行。

**Comment by panzer1313208** [comment]
@yeahwu 你好，为啥我没见过你呀。话说我也在这个论坛混了很久了

**Comment by QGB** [comment]
无所畏惧

**Comment by jzp820927** [comment]
@panzer1313208 你还在论坛混这么就了，连Y大都不知道。

**Comment by panzer1313208** [comment]
@jzp820927 表示真的不知道= =

**Comment by panzer1313208** [comment]
@EdwardAutumn 傻逼麻烦出来下

**Comment by nxtreaming** [comment]
这个maillist 怎么了？怎么不封了楼上这个 @panzer1313208 傻逼？

**Comment by panzer1313208** [comment]
@nxtreaming 你不傻逼？

**Comment by panzer1313208** [comment]
@jzp820927 高能预警，出现了跟lantern一伙的骗子。

**Comment by jzp820927** [comment]
@panzer1313208 不对啊，刚刚你说“”我参与过xxnet的设计，我查了下贡献列表，没你名字啊。
https://github.com/XX-net/XX-Net/graphs/contributors

**Comment by yeahwu** [comment]
@panzer1313208 不要再骂了，要撕逼到别处撕去。注意素质，否则给封了！
天朝屁民 <notifications@github.com>于2016年8月19日 周五21:09写道：
