### ISSUE TITLE
扫IP时同时下载大文件是否会影响xx-net推断IP质量的准确性？

### ISSUE THREAD

**Issue by OnionSalt** [XX-net/XX-Net#407]
比如晚上扫ip的同时下载电影，游戏，会不会因为下载占用带宽，导致高质量ip被误判成垃圾ip（比如timeout）

**Comment by ee3546** [comment]
我也想知道

**Comment by xxnet** [comment]
带宽方面，20个线程扫描，流量大约5kB，可以忽略不计。

至于，高质量ip被误判成垃圾ip，就当少发现一个ip，影响不大。

2015-05-14 13:23 GMT+08:00 ee3546 <notifications@github.com>:

**Comment by OnionSalt** [comment]
多谢回复。不影响就好
