### ISSUE TITLE
嘿，伙计们，恭喜入坑。

### ISSUE THREAD

**Issue by panzer1313208** [XX-net/XX-Net#4073]
恭喜你们被坑了。

**Comment by panzer1313208** [comment]
@code4impl @lianddao @jiajianrong

**Comment by panzer1313208** [comment]
@zxf8665905

**Comment by panzer1313208** [comment]
@EdwardAutumn 你不是说我是骗子故意黑lantern么？嗯？

**Comment by zxf8665905** [comment]
哈哈。。。我只是站在坑边上看了会，我还没下去呢，继续用我的shadowsocks。

**Comment by panzer1313208** [comment]
@zxf8665905 看看蓝灯论坛里都是些什么帖子就知道这个软件怎么样了。

**Comment by panzer1313208** [comment]
@EdwardAutumn 傻逼麻烦出来下
