### ISSUE TITLE
requirejs.org的js无法加载

### ISSUE THREAD

**Issue by taoist1994** [XX-net/XX-Net#4078]
设置requirejs.org的域名通过xx-net连接，结果出现错误使得在打开纽约时报（cn.nytimes.com）等网站时图片加载不出来。
控制台报错信息为

>Uncaught Error: Mismatched anonymous define() module: function (){return b}   require-jquery.js?v=25da8da:1746 
http://requirejs.org/docs/errors.html#mismatch

**Comment by jzp820927** [comment]
贴一个具体的 requirejs.org 的 js 的地址，我来试试
