### ISSUE TITLE
为什么每次部署服务端都只能上传8个ID呢？

### ISSUE THREAD

**Issue by bniw** [XX-net/XX-Net#408]
May 14 13:45:15 - Scanning files on local disk.
May 14 13:45:16 - Cloning 5 application files.
May 14 13:45:17 - Compilation starting.
May 14 13:45:18 - Compilation completed.
May 14 13:45:18 - Starting deployment.
May 14 13:45:23 - Checking if deployment succeeded.
May 14 13:45:24 - Deployment successful.
May 14 13:45:26 - Checking if updated app version is serving.
-----------------------------
第8个ID上传到这里，就停住不再继续了。我开始以为是这个ID有问题，可把10个ID打乱顺序上传，无论哪个ID，都是第8个时停住。试了几次都是这样，我推荐给一个朋友用，他也这种情况。
请问是什么原因，应该如何解决？多谢了。

**Comment by internetic** [comment]
从第8个开始重新上传

**Comment by bniw** [comment]
从第8个上传是可以的。我就是不知道为啥到第8个就停了呢...

**Comment by plmoknijnuy** [comment]
这个可能是Goagent的bug，我记得大约半年前用GoAgent上传的时候也是到第7个ID就停止。建议一次上传7个，再上传7个。或者去GoAgent的issue看看，记得有人提过这个问题，貌似没有解决。

**Comment by xxnet** [comment]
已修复
