### ISSUE TITLE
无法连接校园网

### ISSUE THREAD

**Issue by Ch-Song** [XX-net/XX-Net#4082]
我的xx-net使用的是最新稳定版，一切翻墙功能正常，但是有一个副作用求解答：
我一共使用了两个翻墙措施
1.[Laod的hosts](https://laod.org/hosts/2016-google-hosts.html)
2.xx-net
平时的一般功能，不需要开启xx-net在用视频的时候才用xx-net

### 但是产生了副作用：
无法在校园网wifi的环境下链接学校网主页
在非校园网，如电信宽带时可以打开校园网主页
校园网环境下可以打开学院的网站主页
校园网条件下不能打开正方的选课系统

请问这个是XX-net所致还是hosts所导致，还是二着共同影响的结果
以及解决办法？

**Comment by Ch-Song** [comment]
试过Chrome、edge、IE都连接失败
Chrome给出的错误是ERR_CONNECTION_TIMED_OUT

**Comment by jzp820927** [comment]
应该是 XXnet 影响的，你是用的全局模式？还是 智能PAC 模式？

**Comment by Ch-Song** [comment]
@jzp820927 我全局GAEProxy、全局PAC只能和取消全局代理都是过了。
我记得以前有一次取消全局代理成功连上校网首页，但是后来又不知道怎么了

**Comment by jzp820927** [comment]
用 Chrome ，然后安装代理管理扩展试试

**Comment by Ch-Song** [comment]
我用的就是chrome和代理的扩展，然后一般情况用的是直连，只有在开启xxnet的时候才能连上校网，但是校网部分内容需要校内的ip

**Comment by jzp820927** [comment]
扩展选择直连，都不行麽？

**Comment by Ch-Song** [comment]
@jzp820927 是，chrome开xxnet才能连上，校园网ip连不上，我用的电信网IP应该也和校园网有区别

**Comment by jzp820927** [comment]
挺诡异的，赶脚好像流量被全局代理了。但是你又是设置的直连。不知道是不是你校园网的问题了。

**Comment by Ch-Song** [comment]
我觉得应该没有被全局代理，因为一般的网站连接速度能感受到，而且hosts不能播放视频，我chrome的扩展没开xxnet的时候和用其他浏览器的时候u2b都是不能播放视频的。
我对计算机和互联网懂得不太多，我觉得可能是因为xxnet在运行的时候，可能更改过我不开xxnet也会影响的东西，感觉被影响的东西挺奇怪的，学校的网站只是一部分无法进入。
不知道如果卸载能不能还原回能进去的状态，如果不能的话就是可能更改了一些和学校网页识别的什么东西有关的东西。
改不了其实问题也不大，就是选课的时候麻烦一点。

**Comment by jzp820927** [comment]
可以重装系统试试

**Comment by Ch-Song** [comment]
还是没有办法登入校园网，我用的是最新版本的XX-net我现在发现我连登入学校网关的页面都没法打开，也就是说我的电脑没法用校园网了。我也是删掉重装过xx-net还是不能连接校园网。请问这个可能是哪里的问题？

**Comment by jzp820927** [comment]
检查下 IE 里面的 局域网设置，代理服务器，是不是有内容。有的话，清空。

**Comment by garyson** [comment]
同样的问题 怎么解决啊

**Comment by jzp820927** [comment]
先安装上面的方法走一遍看看。

**Comment by Ch-Song** [comment]
把dns获取方式改成自动获取 我已经解决了
