### ISSUE TITLE
设置了扫描的数量为2000， 然后崩溃了， 怎么样都打不开 修改配置文件为100后才能重新打开

### ISSUE THREAD

**Issue by soulomoon** [XX-net/XX-Net#4085]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:170 good:152
network-status: OK
connected-link: new:2 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 832
ip-quality: 307
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
不知道你说的 2000 是指的 扫描线程？还是 IP 数量？如果是扫描线程，2000，肯定要崩溃的。IP 数量到没什么影响。

**Comment by soulomoon** [comment]
-0- 扫描线程， 不知道大概支持多少不崩溃呢

**Comment by jzp820927** [comment]
2000 太高了，除非你的网卡非常好，带宽非常高。我觉得扫描线程调这么高，没什么意义，线程越高，漏扫情况越严重。

**Comment by cainiaowu** [comment]
一般设置20足够日常使用，主要电脑要常开。并发数多并不能多扫出IP，还容易触发GFW防御机制。

**Comment by wenliyang** [comment]
一般默认50就够了，改高了不如经常开机让它扫着好
