### ISSUE TITLE
Mac 10.10.3 xx-net 1.14.8无法启动

### ISSUE THREAD

**Issue by ninggu2008** [XX-net/XX-Net#409]
日志如下
$ /Volumes/Macdata/Downloads/XX-Net-1.14.8/start.command ; exit;
launcher version: 1.4.0
May 14 16:07:28 - [INFO] module goagent version _ not exist
May 14 16:07:28 - [INFO] module goagent auto upgrade to version 3.1.49
May 14 16:07:28 - [INFO] module launcher version _ not exist
May 14 16:07:28 - [INFO] module launcher auto upgrade to version 1.4.0
May 14 16:07:28 - [INFO] module php_proxy version _ not exist
May 14 16:07:28 - [INFO] module php_proxy auto upgrade to version 1.0.0
May 14 16:07:38 - [INFO] use goagent version:3.1.49
May 14 16:07:38 - [INFO] goagent 3.1.49 started /Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/start.py
May 14 16:07:40 - [INFO] load ip range file:/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/local/ip_range.txt
May 14 16:07:40 - [INFO] load google ip_list num:3000, gws num:3000
May 14 16:07:40 - [DEBUG] sort ip time:10
May 14 16:07:40 - [INFO] SSL use version:TLSv1_2
Traceback (most recent call last):
  File "/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/start.py", line 13, in <module>
    import local.proxy as goagent
  File "/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/local/proxy.py", line 83, in <module>
    import proxy_handler
  File "/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/local/proxy_handler.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/local/connect_manager.py", line 616, in <module>
    https_manager = Https_connection_manager()
  File "/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/local/connect_manager.py", line 188, in __init__
    self.openssl_context = SSLConnection.context_builder(ca_certs=g_cacertfile)
  File "/Volumes/Macdata/Downloads/XX-Net-1.14.8/goagent/3.1.49/local/openssl_wrap.py", line 130, in context_builder
    ssl_context = OpenSSL.SSL.Context(protocol_version)
  File "build/bdist.macosx-10.10-x86_64/egg/OpenSSL/SSL.py", line 261, in __init__
    # must be used.
ValueError: No such protocol
卡住，然后：
May 14 16:10:59 - [INFO] start goagent time cost 200809
May 14 16:10:59 - [INFO] generate desktop shortcut
May 14 16:11:00 - [DEBUG] launcher web_control 127.0.0.1:58943 "GET / 
May 14 16:11:00 - [DEBUG] launcher web_control 127.0.0.1:58946 "GET /js/site.js?20150512 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59128 "GET / 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59129 "GET /css/bootstrap.css 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59130 "GET /css/bootstrap-responsive.css 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59131 "GET /css/flat-ui.css 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59132 "GET /css/ladda-themeless.min.css 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59133 "GET /css/style.css 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59134 "GET /js/jquery-1.11.2.min.js 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59135 "GET /js/flat-ui.min.js 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59136 "GET /js/jquery.timer.js 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59137 "GET /js/spin.min.js 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59138 "GET /js/ladda.min.js 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59139 "GET /js/bootstrap.min.js 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59140 "GET /js/site.js?20150512 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59141 "GET /img/logo.png 
May 14 16:12:24 - [DEBUG] launcher web_control 127.0.0.1:59142 "GET /img/fixed-width.png 
May 14 16:12:25 - [DEBUG] launcher web_control 127.0.0.1:59146 "GET /favicon.ico 

状态页显示空白

**Comment by xxnet** [comment]
收到反馈，我处理下

2015-05-14 16:15 GMT+08:00 ninggu2008 <notifications@github.com>:

**Comment by xxnet** [comment]
发新版 1.14.9 处理mac 10.10 无法工作


2015-05-14 16:56 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by ninggu2008** [comment]
经测试1.14.9已经可以启动，正常使用。
我用start.command启动，终端窗口一直显示，关闭了就xxnet就退出了，虽说可以最小化。有没有办法像windows平台那样，启动了只是托盘有图标，隐藏这个终端窗口？？
开机启动mac上有效吗，还是要手动加启动项？我发现启动项并没有增加。

**Comment by ninggu2008** [comment]
经测试1.14.9已经可以启动，正常使用。
我用start.command启动，终端窗口一直显示，关闭了就xxnet就退出了，虽说可以最小化。有没有办法像windows平台那样，启动了只是托盘有图标，隐藏这个终端窗口？？
开机启动mac上有效吗，还是要手动加启动项？我发现启动项并没有增加。

**Comment by ninggu2008** [comment]
关于启动隐藏终端窗口的问题，已经解决了。
我使用了GoagentMac这个应用，它能够实现启动.py文件并且隐藏终端窗口，需要时再调出，我把文件路径指定为XX-Net-1.14.9/launcher/start.py，有效。加上xx-net本身带隐藏托盘图标功能，已经可以静默启动，后台运行，一点不打扰。
