### ISSUE TITLE
Mac环境下如何上传自家的ID

### ISSUE THREAD

**Issue by shawwokou123** [XX-net/XX-Net#41]
Mac 环境下，如何上传自己的GOODLE  id   ?

我看XXNET集成的是，goa3.x版本，能否换成3.2.3？如果能，怎么换？

**Comment by shawwokou123** [comment]
上传ID问题已解决！

xxnet集成的GOA能否更换？

**Comment by xxnet** [comment]
请不要替换为3.2.3，目前差异已经很大。
