### ISSUE TITLE
点击“检查最新版本”按钮出现 发生未知错误，请刷新页面重试

### ISSUE THREAD

**Issue by asmgcc** [XX-net/XX-Net#410]
V1.14.8版本点击“检查最新版本”按钮出现 发生未知错误，请刷新页面重试
有遇到过吗？

**Comment by tj8m23le** [comment]
有 奇怪的是板子就正常 本子就这样。。。

**Comment by lele2010lele** [comment]
mac遇到，再次进入就行

**Comment by xxnet** [comment]
怀疑js加载问题，可能刷新就解决了

2015-05-16 10:06 GMT+08:00 lele2010lele <notifications@github.com>:
