### ISSUE TITLE
mac下莫名除去chrome和QQ，其他软件都上不了网

### ISSUE THREAD

**Issue by Jack-Xiao** [XX-net/XX-Net#4101]
### 目前使用的版本为3.1.1.9, 
1.  使用自动GAEProxy时， 只能用chrome和QQ上网。其他如xcode、safari、androidstudio、网易云音乐都上了网
2. 使用全局GAEProxy时，以上软件都可以上网。
3. DNS试过114、8 。曾改过hosts，现在全部清空也没有用。使用过云梯VPN。
4. 可能与XX-Net有关。希望帮忙解决这问题。

**Comment by jzp820927** [comment]
莫非这些软件都走了 XX 代理了？

**Comment by Jack-Xiao** [comment]
1）全局GAEProxy模式下 都是走XX代理。这模式下软件都可以上网。
2）自动GAEProxy模式下, 只有chrome+QQ+微信等可以上网。
3）我电脑在不开XX时，也是只有chrome+QQ等可以上网。
我电脑出现的问题， 应该与代理有关。 所以才提这issue，看有没人遇到我同样的问题or 能够帮忙解决。

**Comment by jzp820927** [comment]
系统问题吧，要不重装系统？

**Comment by Jack-Xiao** [comment]
就是不想重装。另外因为与XX有很大可能有关系才提的。

**Comment by Jack-Xiao** [comment]
我的确有设置过全局代理。也的确有强制终止过（卡住了）。
重启过很多次，也把XX重新运行过，选了Disable，选了Quit。
然而还是出现上面描述的现象。

**Comment by Jack-Xiao** [comment]
http://blog.csdn.net/bao_libra/article/details/51374940
这是我找到的类似问题，也回复了作者。 也许能提供点思路。

**Comment by jzp820927** [comment]
没用过 mac ，不太情况，具体设置过程，不过可以找到设置系统代理的地方，看看是否设置了系统代理，然后把系统代理关闭就行了。

**Comment by Jack-Xiao** [comment]
通过disable，系统设置的代理就会被取消掉。
可否帮忙找xx mac开发或其他人帮忙解决呢。谢谢！

**Comment by jzp820927** [comment]
找Y大吧，现在他是主要维护者。

**Comment by Jack-Xiao** [comment]
谢谢回复，已通过reinstall重置数据。
