### ISSUE TITLE
Win10:部署appid无反应

### ISSUE THREAD

**Issue by Out3ider** [XX-net/XX-Net#4107]
问题描述：appid部署相关：（win10 64位英文版， xx-net 3.2.6测试版）
点击开始部署后没有任何认证提示然后
  当前状态：部署完成完成。
部署日志如下：
2016-08-24 21:09:03,746 - root - INFO - set proxy to http://127.0.0.1:8087
2016-08-24 21:09:03,746 - root - INFO - ============ Begin upload ============
2016-08-24 21:09:03,746 - root - INFO - appid:Initiald2733

配置时显示无效ID

诊断信息如下
Aug 24 21:17:19.585 - [INFO] GAE t:771 s:1026 POST https://github.com/preview?markdown_unsupported=false&repository=29290473&subject=0&subject_type=Issue get_response:767
Aug 24 21:17:19.648 - [DEBUG] GAE POST https://api.github.com/_private/browser/stats
Aug 24 21:17:20.353 - [WARNING] server app return fail, status:502
Aug 24 21:17:20.437 - [INFO] scan_ip add ip:216.123.194.215 time:2075
Aug 24 21:17:21.204 - [INFO] GAE t:1555 s:5 POST https://api.github.com/_private/browser/stats get_response:1539
Aug 24 21:17:21.979 - [WARNING] server app return fail, status:502
Aug 24 21:17:28.495 - [DEBUG] ssl_closed 203.233.96.23
Aug 24 21:17:28.495 - [DEBUG] 203.233.96.23 worker close:GoAway: additional_data:session_timed_out
Aug 24 21:17:30.412 - [DEBUG] get ip:203.233.96.23 t:1277
Aug 24 21:17:32.668 - [WARNING] server app return fail, status:502
Aug 24 21:17:33.272 - [DEBUG] create_ssl update ip:203.233.96.23 time:1738 h2:1
Aug 24 21:17:43.283 - [DEBUG] get ip:64.233.180.134 t:1520
Aug 24 21:17:45.698 - [DEBUG] create_ssl update ip:64.233.180.134 time:1460 h2:1
Aug 24 21:17:45.859 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=005GnoLzWPtBkCfKwsnJjw%3D%3D

还请大神帮忙诊断下，谢谢
已经可以翻墙，我想看youtube 所以才考虑部署私人appid

**Comment by jzp820927** [comment]
先确保是否能够通过 GAE 访问 google 网站

**Comment by Out3ider** [comment]
搞定了...appid输入错了.晕
