### ISSUE TITLE
在使用XX-Net的情况下Firefox卡死，再重新打开无法在非代理模型下访问基本任何网页

### ISSUE THREAD

**Issue by nibordooh** [XX-net/XX-Net#4109]
如题，是firefox崩了之后突然出现的情况，具体表现为：

1. 通过IE任何网站都无法访问，在开XXnet的情况下显示为代理服务器没有响应；在不用代理的时候显示网站无法访问。
2. firefox在未开xxnet时基本打不开任何网站，提示Sever not found；打开xxnet后可以访问部分网站比如gmail（但google.com连不上），但很多国内网站仍旧连不上。
3. chrome下未开xxnet时也基本打不开任何网站提示dns地址找不到；打开Xxnet后的表现跟firefox相同。
4. 用多年前的老版的opera(12.17)，国内网站没有任何问题，因为这个翻墙的设置应该不被xxnet自动影响。
5. QQ之类的软件都没有问题，本地连接自动查错也没有查出问题。
6. 用shadowsocks在全局代理的情况下墙内外网站均无问题。

根据上述情况估计是xxnet在随firefox崩掉后出了问题。

我尝试过
1. 重启xxnet,reset,正常关闭
2. 重新安装xxnet
3. flushdns
4. 手动改IE的代理设置为无。
5. 重装网卡驱动，dns设置从自动改成8.8.8.8

这些都没有用，不知道接下来除了重装系统，还有什么方法可以尝试的？

XXnet的状态
在代理打开（全局gaeproxy或者pac)的情况下显示：
XX-Net 2.9.3, Everything is OK. Welcome to the FREE Internet. 
但仍可以出现以上开了代理后的问题

以下三个选项倒是经常在ok和Fail中徘徊。
Local Network Status
Browser Proxy Setting 	
CA status(Download) 	

完整点的例子如下
XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
xxnet-version: 2.9.3
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 2966 / 133
network-status: OK
connected-link: 6 / 1
scan-ip-thread-num: 1
ip-quality: 873
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

XX-Net Status：

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
xxnet-version: 2.9.3
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 2 / 2
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 9999
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by yeahwu** [comment]
firefox下
首选项——高级——网络——连接国际互联网——设置——不使用代理——确定
firefox下建议用插件分流
xx-net下
勾选“取消全局代理”
这两项设置好了，应该火狐就没什么问题了

**Comment by wenliyang** [comment]
XX-Net 版本太老，请升级到最新版
可用IP太少

**Comment by nibordooh** [comment]
现在是不使用xxnet普通网络都不能上。


Get Outlook for Android






On Thu, Aug 25, 2016 at 3:41 PM +0800, "wenliyang" <notifications@github.com> wrote:












XX-Net 版本太老，请升级到最新版

可用IP太少

**Comment by wenliyang** [comment]
唔？刚才发现我的回答不太对，删了，没想到...

不开XX-Net浏览器不能看网页，那是代理设置问题，按yeahwu的方法试

另，Firefox和Chrome都推荐使用扩展来实现代理翻墙，XX-Net还是请升级到最新版

**Comment by nibordooh** [comment]
没事，我这个问题表现得比较怪。


不开xxnet的话, 其中有的网站比如百度通过ip访问又能看也能搜索。。。但只在 chrome和Firefox下可以 ie 则不行。。。


我到时看看升最新版可不可以一起解决了。


Get Outlook for Android



From: wenliyang

Sent: Thursday, August 25, 16:05

Subject: Re: [XX-net/XX-Net] 在使用XX-Net的情况下Firefox卡死，再重新打开无法在非代理模型下访问基本任何网页 (#4109)

To: XX-net/XX-Net

Cc: nibordooh, Author



唔？刚才发现我的回答不太对，删了，没想到...


不开XX-Net浏览器不能看网页，那是代理设置问题，按yeahwu的方法试


另，Firefox和Chrome都推荐使用扩展来实现代理翻墙，XX-Net还是请升级到最新版

**Comment by wenliyang** [comment]
楼主的问题似乎还是和DNS有关，8.8.8.8被干扰的厉害
试下国内的公共DNS看，比如阿里云的223.5.5.5、223.6.6.6

另外，也可以试下防DNS投毒污染的软件，比如
https://github.com/chengr28/Pcap_DNSProxy/

**Comment by nibordooh** [comment]
好的，多谢，到时我也都再试一下。

但我之前flushdns了，如果是投毒不至于基本任何网络都不打不开？此外是突然崩掉的，dns投毒的话不会这么巧吧？


Get Outlook for Android



From: wenliyang

Sent: Thursday, August 25, 16:29

Subject: Re: [XX-net/XX-Net] 在使用XX-Net的情况下Firefox卡死，再重新打开无法在非代理模型下访问基本任何网页 (#4109)

To: XX-net/XX-Net

Cc: nibordooh, Author



楼主的问题似乎还是和DNS有关，8.8.8.8被干扰的厉害

试下国内的公共DNS看，比如阿里云的223.5.5.5、223.6.6.6


另外，也可以试下防DNS投毒污染的软件，比如

https://github.com/chengr28/Pcap_DNSProxy/

**Comment by jzp820927** [comment]
DNS 不会影响访问国内网站。先把 DNS 设置为国内的 比如 114，国外的DNS，基本上都有干扰，经常解析不出结果。其次应该检查 IE 的代理设置，在XX关闭的情况下，是不是IE代理没有关闭。

**Comment by nibordooh** [comment]
IE已设置不用代理，但仍无法访问国内网站


Get Outlook for Android






On Thu, Aug 25, 2016 at 5:37 PM +0800, "天朝屁民" <notifications@github.com> wrote:












DNS 不会影响访问国内网站。先把 DNS 设置为国内的 比如 114，国外的DNS，基本上都有干扰，经常解析不出结果。其次应该检查 IE 的代理设置，在XX关闭的情况下，是不是IE代理没有关闭。

**Comment by nibordooh** [comment]
测试了一下 在没开启任何代理的情况下手动关闭Firefox代理国内网站仍无法访问


Get Outlook for Android






On Thu, Aug 25, 2016 at 3:32 PM +0800, "yeahwu" <notifications@github.com> wrote:












firefox下

首选项——高级——网络——连接国际互联网——设置——不使用代理——确定

firefox下建议用插件分流

xx-net下

勾选“取消全局代理”

这两项设置好了，应该火狐就没什么问题了

**Comment by nibordooh** [comment]
试了一下改dns 没有解决ie Firefox上不了国内网站的问题，应该不是dns的问题 因为不用chromium核的老版opera可以访问国内网站，应该还是xxnet崩掉后系统有地方卡死了，但不知是何处


Get Outlook for Android






On Thu, Aug 25, 2016 at 5:37 PM +0800, "天朝屁民" <notifications@github.com> wrote:












DNS 不会影响访问国内网站。先把 DNS 设置为国内的 比如 114，国外的DNS，基本上都有干扰，经常解析不出结果。其次应该检查 IE 的代理设置，在XX关闭的情况下，是不是IE代理没有关闭。

**Comment by jzp820927** [comment]
如果你没设置 IE 代理，XX是不会影响上网的。就算崩溃了，除非是设置了 IE 系统代理。
你现在的情况是，某些浏览器不能上网？但是 opero 老版又可以？
建议你 chrome F12 看看网站加载失败，是什么报错？

**Comment by nibordooh** [comment]
原则上是这样，但就是现在这样设的不走代理也上不了。怀疑是这个模块或者控制代理的模块已经卡死了，选与不选都不行。


Chrome显示 failed to load resource err name not resolved


Opera 12.17用的opera 自己的内核 管理方式不一样估计崩的地方不影响这浏览器


Get Outlook for Android



From: 天朝屁民

Sent: Thursday, August 25, 20:28

Subject: Re: [XX-net/XX-Net] 在使用XX-Net的情况下Firefox卡死，再重新打开无法在非代理模型下访问基本任何网页 (#4109)

To: XX-net/XX-Net

Cc: nibordooh, Author



如果你没设置 IE 代理，XX是不会影响上网的。就算崩溃了，除非是设置了 IE 系统代理。

你现在的情况是，某些浏览器不能上网？但是 opero 老版又可以？

建议你 chrome F12 看看网站加载失败，是什么报错？

**Comment by nibordooh** [comment]
总之多谢提供建议 搞不定到时我就重装个系统吧，只是好久都没重装系统就算病毒来了也是手动解决，这个估计其他地方也搜不到解决方法，因为这个重装略不爽啊 ：)


Get Outlook for Android






On Thu, Aug 25, 2016 at 8:28 PM +0800, "天朝屁民" <notifications@github.com> wrote:












如果你没设置 IE 代理，XX是不会影响上网的。就算崩溃了，除非是设置了 IE 系统代理。

你现在的情况是，某些浏览器不能上网？但是 opero 老版又可以？

建议你 chrome F12 看看网站加载失败，是什么报错？

**Comment by jzp820927** [comment]
Chrome显示 failed to load resource err name not resolved

这个错误很明显的提示你，域名解析失败，是 DNS 的问题。换DNS

**Comment by nibordooh** [comment]
这个提示是很明显，但是没有用。
1. 不换用opera老版没有任何问题
2. 换了几个都没用

**Comment by jzp820927** [comment]
那估计是你系统的问题了，你可以拿个不能打开的网站的域名在 cmd 下测试一下：
比如 www.qq.com 打不开，那么打开 cmd，输入：
nslookup www.qq.com
回车，看看能不能正确解析出这个域名的IP地址。

**Comment by nibordooh** [comment]
这个应该是xxnet和系统的交互里哪个地方改了设置导致无法还原，凡是通过这个渠道上网的都无法正常使用。

nslookup可以看到比如qq的地址，ping也是通的，但是就是那几个浏览器都无法访问。

**Comment by nibordooh** [comment]
问题解决了 - 果然还是出在代理上，只是是另一个代理受了xxnet非正常退出的影响。

我之前用Bluestacks的时候有用proxycap专门来控制应用程序走代理。这个程序虽然在xxnet崩的时候没有开，但后台服务应该是出了问题，重装proxycap之后就好了。
