### ISSUE TITLE
每次删除旧版更新后都会弹出控制台界面

### ISSUE THREAD

**Issue by galwaycat00** [XX-net/XX-Net#412]
首次start.bat后就会弹出这个界面。。。。能不能不弹出
![image](https://cloud.githubusercontent.com/assets/2385900/7648355/9bd526c2-fb14-11e4-886a-96f45c4ad5aa.png)

**Comment by yfdyh000** [comment]
用 start.vbs

**Comment by yjd** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config

启动时弹出状态页
