### ISSUE TITLE
上传用户已禁止在您的国家/地区播放此视频

### ISSUE THREAD

**Issue by jhhuang96** [XX-net/XX-Net#4123]
尝试修改YOUTUBE语言为英文，也没用。怎么解决还是有其他推荐的翻墙软件可以看那些被禁止的Youtube视频。谢谢

**Comment by jzp820927** [comment]
只能走代理

**Comment by HJH12315** [comment]
@jzp820927  具体怎么走？XX-net就是无法解决了？

**Comment by jzp820927** [comment]
可以试试全局代理。另外方便的话，帮你的限制视频的地址，发出来，我帮你测试一下/。。

**Comment by HJH12315** [comment]
@jzp820927  全局也没用 本来想在油管看美剧，好像都不行
https://www.youtube.com/watch?v=oHDDhJ1YRoU&list=ELzznUblzJbdp6EA9XZFivBA

**Comment by jzp820927** [comment]
![image](https://cloud.githubusercontent.com/assets/5740066/18028910/dced9a76-6cbb-11e6-8c41-c30aa4ae5389.png)

@HJH12315 大哥，你拿个付费视频来给我测试，你是在逗我玩吧？

**Comment by zhencaihao** [comment]
我用的是“全局通过GAEProxy代理”也显示"上传用户已禁止在您的国家/地区播放此视频"。

**Comment by HJH12315** [comment]
@jzp820927  我打开链接并没有显示付费，而是显示"上传用户已禁止在您的国家/地区播放此视频"。
你用的XX-net打开的？？？

**Comment by jzp820927** [comment]
*.youtube.com 走 PHP，其他走 GAE，就行了。

**Comment by HJH12315** [comment]
@jzp820927  什么叫走PHP，不太懂，有具体的操作嘛？谢谢！

**Comment by jzp820927** [comment]
好吧，确实有点麻烦，建议用其他工具试试。

**Comment by cainiaowu** [comment]
GAE出口是美国的，除非走别的出口（PHP自建服务器）不然无法解决。

**Comment by Conan96** [comment]
@jzp820927 @cainiaowu 现在能用的免费PHP空间有哪些？ OpenShift现在限制注册了。。。

**Comment by cainiaowu** [comment]
PHP空间免费不好用，好用不免费。

**Comment by jzp820927** [comment]
就 heroku 了吧

**Comment by edwinhuish** [comment]
刚刚看了一下文档。 @jzp820927 PHP为什么移除呢？
![image](https://cloud.githubusercontent.com/assets/5207925/18074422/00fa9506-6e9f-11e6-9bb6-bff78e81569f.png)

**Comment by jzp820927** [comment]
因为 PHP 很久没维护了，而且效率太低，所有干脆就去掉算了，其实如果你想用 PHP，可以试试 goproxy，比这个的 PHP 要好用，而且作者一直在维护。

**Comment by edwinhuish** [comment]
算了，没有在用PHP，仅仅是好奇问一下。

XX-NET很好用，不过就是偶尔google需要验证码，不知道 @jzp820927 大大有没有解决方法？

**Comment by edwinhuish** [comment]
已经将扫描线程改到10了，可是一样会出现验证码

**Comment by jzp820927** [comment]
验证码和扫描线程没啥关系，一般情况配置直连，可以解决，就是在 ini 配置文件中 添加 google相关的域名 driect。

**Comment by jillojill** [comment]
有没有可行的 比较先进的方法呢 “在该国家无法播放此视频”，我用一个该国家的vps就行了吗？

**Comment by jzp820927** [comment]
这个是 ytb 的地域性限制，只能通过使用没有现在的国家的代理，可以解决，一般情况，通过 GAE 就可以解决很大部分这种问题了。

**Comment by IDFREW** [comment]
也许可以尝试一下IP伪装,或者GPS模拟
