### ISSUE TITLE
wiki页面linux后台运行的路径还没改

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#4125]
https://github.com/XX-net/XX-Net/wiki/How-to-use
![image](https://cloud.githubusercontent.com/assets/17242539/18034090/ca9adc20-6d66-11e6-9027-31244c43cd0b.png)
现在的版本变成code/default/xx_net.sh了不是么

**Comment by jzp820927** [comment]
你更新一下 wiki 不就行了
