### ISSUE TITLE
超流量APPID列表不会准时清空

### ISSUE THREAD

**Issue by cainiaowu** [XX-net/XX-Net#4136]
每天15：00（GMT+8）超流量APPID就恢复了啊，可是XXnet自己不会清空失效APPID列表，总要手动重启，有啥办法没？

**Comment by cainiaowu** [comment]
谁懂python的写个准点清空appid的函数啊？@yeahwu

**Comment by jzp820927** [comment]
你弄错了，不是 15：00，是从6：00

**Comment by cainiaowu** [comment]
是15：00，不信自己看公共ID就知道了，2点半左右大部分失效，三点就准时回复了。

**Comment by jzp820927** [comment]
那就不知道了，按标准时间计算，美国 0点，就是我们这儿下午 16 点。
