### ISSUE TITLE
不能完整下载大文件

### ISSUE THREAD

**Issue by twofisher** [XX-net/XX-Net#4137]
xx-net 3.2.26 版本，不能完整下载git上的大文件，下载结束后总是提示zip文件异常结束。如果不通过代理，下载的文件没有问题。

当使用gradle通过xx-net代理下载依赖库的时候，如果遇到gwt-dev-2.7.0.jar这样的比较大的文件的时候也会出错并导致gradle中断编译。

看youtube那些没有问题。
有碰到类似问题的朋友麻烦支个招，谢谢！

**Comment by jzp820927** [comment]
GAE 的局限吧，估计只能换软件

**Comment by linhua55** [comment]
用goproxy试试，goproxy处理的可能好一些

**Comment by twofisher** [comment]
谢谢
