### ISSUE TITLE
自动更新经常删除 proxy.ini 用户appid

### ISSUE THREAD

**Issue by LArctic** [XX-net/XX-Net#414]
而且proxy.user.ini也一直无效。

**Comment by xxnet** [comment]
请在UI上配置。

手动修改配置，请参考：
https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config

2015-05-15 17:33 GMT+08:00 LArctic <notifications@github.com>:

**Comment by think2011** [comment]
XX-NET的信息应该保存在这里的，我的没被删过。
`/XX-Net/data/goagent/config.ini`

**Comment by xxnet** [comment]
不要手动修改 goagent/x.x.x/local/proxy.ini 和 proxy.user.ini

2015-05-16 12:38 GMT+08:00 曾浩 <notifications@github.com>:
