### ISSUE TITLE
Eclipse里设置代理，还是不能访问谷歌地图

### ISSUE THREAD

**Issue by gosple** [XX-net/XX-Net#4142]
## Eclipse里设置代理，还是不能访问谷歌地图
1. 在Network Connections里设置了  **手动代理**
http,hhtps设置成：
`127.0.0.1 8087`
或者是
`127.0.0.1 8085`
都访问不了

2. 但是设置全局智能代理，在IE中可以打开

**Comment by jzp820927** [comment]
估计可能是证书问题。看看能不能设置忽略证书

**Comment by linhua55** [comment]
双击证书文件，导入证书到系统中（注意：不是导入到浏览器中）

**Comment by twofisher** [comment]
如果是windows,可以用portecle打开jre\lib\security下cacerts，并导入xx-net的证书；
如果是linux,可用keytool 导入证书

**Comment by gosple** [comment]
用portecle打开jre\lib\security下cacerts，导入 \XX-Net-master\data\gae_proxy\CA.crt 之后，

> 包括系统自带的jre和jdk目录下的jre

设置成手动代理，依然不行呀。

**Comment by gosple** [comment]
弄清楚了，这跟eclipse的代理设置有关系

一般的Web Service程序, 需要访问网络资源, 此时设置的代理是使得JAVA VM通过代理访问,设置方式是:
>Run-->Run...-->(x=)Argument下面的VM Arguments下设置:
`-Dhttp.proxyHost=[代理IP地址]` [空格] -Dhttp.proxyPort=[端口]

**Comment by gosple** [comment]
问题解决了，谢谢大家！
弄清楚了，**这跟eclipse的代理设置有关系**

>一般的Web Service程序, 需要访问网络资源, 此时设置的代理是使得JAVA VM通过代理访问,设置方式是:
Run-->Run...-->(x=)Argument下面的VM Arguments下设置:
`-Dhttp.proxyHost=[代理IP地址]` [空格] -Dhttp.proxyPort=[端口]`

按照上面这段话设置如下
`-Dhttp.proxyHost=127.0.0.1  -Dhttp.proxyPort=8087`
