### ISSUE TITLE
You cannot visit productforums.google.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

### ISSUE THREAD

**Issue by huangjinqiang** [XX-net/XX-Net#4145]
Your connection is not private

Attackers might be trying to steal your information from productforums.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_DATE_INVALID
  Automatically report details of possible security incidents to Google. Privacy policy
ReloadHIDE ADVANCED
productforums.google.com normally uses encryption to protect your information. When Google Chrome tried to connect to productforums.google.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be productforums.google.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit productforums.google.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by huangjinqiang** [comment]
Chrome Version 53.0.2785.89 m

**Comment by jzp820927** [comment]
导入证书

**Comment by huangjinqiang** [comment]
好像和 HSTS 有关，导入证书没用

**Comment by jzp820927** [comment]
HSTS 是强制安全连接，也是必须要走 https 才行，而 https 就需要验证证书。

**Comment by phoenixbai** [comment]
同问,怎么解决? 导入证书没有解决问题.

**Comment by jzp820927** [comment]
可以试试 删除 CA.crt 和 certs/ 目录，删除导入的证书，然后重新运行XX，重新生成新的证书，再倒入

**Comment by phoenixbai** [comment]
果然解决了, 谢谢 @jzp820927

**Comment by huangjinqiang** [comment]
谢谢 @jzp820927

**Comment by chapgaga** [comment]
@phoenixbai 你用的什么浏览器？我chrome导入证书也没用啊

**Comment by jzp820927** [comment]
除了 FF 浏览器以外，其他浏览器都是导入系统证书就可以了。
