### ISSUE TITLE
好久没用了，之前是3.2.5，更新到3.2.6还是用不了

### ISSUE THREAD

**Issue by Lpursuit** [XX-net/XX-Net#4151]
状态页显示   您应该考虑开启IP扫描器。  IP那块都开着啊，不知道怎么操作

诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12539 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
日志
Sep 02 11:55:12.621 - [DEBUG] report_connect_fail:2001:4860:4001:3::11
Sep 02 11:55:12.621 - [DEBUG] report_connect_fail continue_fail_count:2162
Sep 02 11:55:12.621 - [DEBUG] report_connect_fail:2001:4860:4001:3::19
Sep 02 11:55:12.621 - [DEBUG] report_connect_fail continue_fail_count:2163
Sep 02 11:55:12.621 - [DEBUG] report_connect_fail:2001:4860:4001:3::18
Sep 02 11:55:12.988 - [DEBUG] 2404:6800:4005:11::a fail:timeout('timed out',)
Sep 02 11:55:12.988 - [DEBUG] report_connect_fail continue_fail_count:2164
Sep 02 11:55:12.988 - [DEBUG] report_connect_fail:2404:6800:4005:11::a
Sep 02 11:55:12.994 - [DEBUG] 2a00:1450:4001:30::c fail:timeout('timed out',)
Sep 02 11:55:12.994 - [DEBUG] 2a00:1450:4001:1::10 fail:timeout('timed out',)
Sep 02 11:55:12.994 - [DEBUG] report_connect_fail continue_fail_count:2165
Sep 02 11:55:12.994 - [DEBUG] report_connect_fail:2a00:1450:4001:30::c
Sep 02 11:55:12.994 - [DEBUG] report_connect_fail continue_fail_count:2166
Sep 02 11:55:12.994 - [DEBUG] report_connect_fail:2a00:1450:4001:1::10
Sep 02 11:55:13.510 - [DEBUG] 2a00:1450:4001:30::f fail:timeout('timed out',)
Sep 02 11:55:13.510 - [DEBUG] 2a00:1450:4001:30::b fail:timeout('timed out',)
Sep 02 11:55:13.510 - [DEBUG] 2a00:1450:4001:30::e fail:timeout('timed out',)
Sep 02 11:55:13.510 - [DEBUG] report_connect_fail continue_fail_count:2167
Sep 02 11:55:13.510 - [DEBUG] report_connect_fail:2a00:1450:4001:30::f
Sep 02 11:55:13.510 - [DEBUG] report_connect_fail continue_fail_count:2168
Sep 02 11:55:13.510 - [DEBUG] report_connect_fail:2a00:1450:4001:30::b
Sep 02 11:55:13.511 - [DEBUG] report_connect_fail continue_fail_count:2169
Sep 02 11:55:13.511 - [DEBUG] report_connect_fail:2a00:1450:4001:30::e

**Comment by xiaoyan94** [comment]
检查一下ip

**Comment by fengixng** [comment]
你本地没有IPV6环境就关闭IPv6

**Comment by Lpursuit** [comment]
已经可以使用了，谢谢大家
