### ISSUE TITLE
几个外网中文版无法访问

### ISSUE THREAD

**Issue by anuxs** [XX-net/XX-Net#4153]
---
## 问题内容
如下几个外网无法访问。但是挂别的vpn比如蓝灯、greenvpn等在全局模式下是可以访问的。自从某个版本更新之后就是这样。
用的chrome浏览器，switchyomega,xxnet自动切换模式。

http://www.bbc.com/zhongwen/simp
http://cn.nytimes.com/
http://cn.reuters.com/

#### 获取诊断信息
XX-Net Status:

sys-platform: x86_64, Darwin-16.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.0.0: Tue Aug 23 17:02:44 PDT 2016; root:xnu-3789.1.31~2/RELEASE_X86_64
os-release: 16.0.0
os-detail: Release:10.12; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:572
network-status: OK
connected-link: new:2 used:0
worker: h1:15 h2:6
scan-ip-thread-num: 20
ip-quality: 140
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志
日志里面没有上述网址的日志。诡异。
---

**Comment by xiaoyan94** [comment]
可以访问。

**Comment by zhencaihao** [comment]
我这里可以访问，用的是XX-NET全局代理。

**Comment by QGB** [comment]
@zhencaihao  @xiaoyan94  泥萌可以访问 http://lcx.cc 嘛

**Comment by zhencaihao** [comment]
![qq 20160902203835](https://cloud.githubusercontent.com/assets/19796493/18204113/8defeb22-714d-11e6-814c-cc645e167a0d.jpg)
刷新了好几次都是这个样子。

**Comment by jzp820927** [comment]
访问不了，应该是网站服务器本身出了问题，和 代理没关系

**Comment by MSTWHD** [comment]
我全部可以访问，到目前为止没出现过不能访问的情况

**Comment by WLZLCX** [comment]
正常访问

**Comment by anuxs** [comment]
自动切换模式 当然设置了啊。配置文件是备份的以前可以上网的配置，不能访问之后，又尝试过其他的几种域名匹配方式，包括正则模式，都不行。
系统代理设置pac试过，不行；
xx-net直接访问试过，不行；
蓝灯做全局pac代理是可以的，xx-net不管是pac还是全局全部代理都不行。

日志里面完全没有访问的信息，我怀疑是哪个地方被屏蔽了，检查过/etc/hosts，没有异常。

还有什么可能？再重申一遍，仅仅把xx-net换成蓝灯，浏览器和switchyproxy配置都不变，就可以访问这几个网址。

=========

刚刚换了firefox + autoproxy，还是不行。

准备上抓包工具了。

**Comment by jzp820927** [comment]
如果没有想过域名的日志，肯定是没走代理，这个得你仔细检查是哪个地方的设置问题了。
