### ISSUE TITLE
ubuntu16.06启动start无标题栏图标出现，打不开8085，并且最新版chrome导入证书提示无法解析文件

### ISSUE THREAD

**Issue by zhangjianhao** [XX-net/XX-Net#4158]
下载了最新版本的xx-net。
启动start，提示信息如下，其中有一段error,提示
**9月 04 11:57:32.06 - [ERROR] bind to 127.0.0.1:8086 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')**
运行start日志如下：
Python 2.7.11+
XX-Net version:default
XX-Net.desktop already exists
9月 04 11:57:28.72 - [INFO] use build-in openssl lib
9月 04 11:57:28.72 - [INFO] start XX-Net 3.2.6
9月 04 11:57:28.72 - [DEBUG] start confirm_xxnet_exit
9月 04 11:57:28.72 - [DEBUG] <0>: try to terminate xxnet:8087
9月 04 11:57:31.72 - [DEBUG] good, xxnet:8087 cleared!
9月 04 11:57:31.73 - [DEBUG] good, xxnet:8085 clear!
9月 04 11:57:31.73 - [DEBUG] finished confirm_xxnet_exit
9月 04 11:57:31.82 - [INFO] SSL use version:TLSv1_2
9月 04 11:57:31.82 - [INFO] OpenSSL support alpn
9月 04 11:57:31.82 - [INFO] load ip range file:/home/zjianhao/software/XX-Net-3.2.6/code/default/gae_proxy/local/ip_range.txt
9月 04 11:57:31.84 - [INFO] load google ip_list num:84, gws num:84
9月 04 11:57:31.84 - [INFO] OpenSSL support alpn
9月 04 11:57:31.84 - [DEBUG] get ip:220.255.2.164 t:163
9月 04 11:57:31.85 - [DEBUG] get ip:59.18.35.76 t:172
9月 04 11:57:31.85 - [DEBUG] ## GAEProxy set keep_running: True
9月 04 11:57:31.85 - [INFO] ------------------------------------------------------
9月 04 11:57:31.85 - [INFO] Python Version     : 2.7.11+
9月 04 11:57:31.85 - [INFO] OS                 : Dist:Ubuntu; Version:16.04; ID:xenial
9月 04 11:57:31.85 - [INFO] Listen Address     : 127.0.0.1:8087
9月 04 11:57:31.85 - [INFO] GAE APPID          : 
9月 04 11:57:31.85 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
9月 04 11:57:31.85 - [INFO] ------------------------------------------------------
GoAgent XX-Net - GoAgent                                     C,,  
9月 04 11:57:31.96 - [DEBUG] network is ok, cost:209 ms
GoAgent XX-Net - GoAgent                                     C,,  
9月 04 11:57:32.06 - [INFO] server 127.0.0.1:8087 started.
9月 04 11:57:32.06 - [ERROR] bind to 127.0.0.1:8086 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zjianhao/software/XX-Net-3.2.6/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/home/zjianhao/software/XX-Net-3.2.6/code/default/gae_proxy/local/proxy.py", line 161, in main
    pac_daemon = simple_http_server.HTTPServer((config.PAC_IP, config.PAC_PORT), pac_server.PACServerHandler)
  File "/home/zjianhao/software/XX-Net-3.2.6/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "/home/zjianhao/software/XX-Net-3.2.6/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "/home/zjianhao/software/XX-Net-3.2.6/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8086 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')

并且在导入证书环节，提示无法解析证书，chrome版本为： 53.0.2785.92 (64-bit)
操作系统为：ubuntu 16.04

**Comment by jzp820927** [comment]
恕我无知，没听说过 ubuntu16.06
并且 月 04 11:57:32.06 - [ERROR] bind to 127.0.0.1:8086 fail:error 这个错误提示，是说你的 8087 端口被占用，请检查是什么进程占用了 8087 端口，结束点，再运行就没问题了。

**Comment by zhangjianhao** [comment]
。。。
不好意思。小手一抖把16.04打成16.06了。。。
找到错误了，python的一个进程占用了1080端口，后来发现是Xware Desktop的迅雷启动的，卸载了之后，正常了

**Comment by jzp820927** [comment]
原来是这样，以前总说 迅雷和 X_tunnel 不兼容，原来是2个用了同样的端口。
