### ISSUE TITLE
googole搜索总是出现被拦截

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#4161]
![qq20160904-1](https://cloud.githubusercontent.com/assets/12568851/18231343/ec1f2616-72e9-11e6-8c32-c2044f250317.png)

**Comment by andylee1890** [comment]
![qq20160904-0](https://cloud.githubusercontent.com/assets/12568851/18231348/273adef2-72ea-11e6-803e-380472e44928.png)

**Comment by Eri5Ch** [comment]
同样的情况啊，xx是不是又被废弃了？

**Comment by jzp820927** [comment]
用直连

**Comment by anuxs** [comment]
google 搜索引擎的反机器人措施，要你输入显示的数字验证码证明你不是机器人在浏览网络。
输入三到四次验证码之后就不会出现。
如果浏览器升级了有变动，还会再次要你输入验证码。我最近就是升级到chrome53就要输入了。
跟代理的关系更大一些。
xx-net一直在更新。但是谷歌也经常在变动。

**Comment by Eri5Ch** [comment]
有时候不会出现数字验证，据说是某个ip流量过大导致的。
虽然不明白什么是直连，但是搜索了一下，按照建议在 data\gae_proxy 文件夹下建立一个新文件 manual.ini，输入 
```
[hosts]
google.com = direct
.google.com = direct
```
虽然不明白是什么意思，正在实验看看会不会好转。

**Comment by jzp820927** [comment]
直连就是 LS 的意思，意思就是不走 GAE，用 google_hk 里面的 IP 直连链接。因为 GAE 的IP 是固定的，大家都走 GAE，就会产生 google 异常流量验证。如果用  google_hk 直连，因为大家的 IP 都不一样，是分散的，理论上就能解决这个问题(实际能不能解决，就等你们验证了)。

**Comment by soulomoon** [comment]
使用之后，两天内没有再发生过we are sorry

**Comment by AbnerChen028** [comment]
将默认搜索引擎改为google.com.hk 就可以了

**Comment by linweijun** [comment]
@jzp820927 我这边搜索也会被拦截，更新到最新版的了，但是用不了直连。不知道有没有其他办法。谢谢

**Comment by jzp820927** [comment]
不知道你说的拦截，具体指的什么意思？

**Comment by linweijun** [comment]
@jzp820927 就是发生we are sorry

**Comment by jzp820927** [comment]
检查是不是设置了直连规则？

**Comment by GoldenDewitt** [comment]
我每次流量异常时，提示的IP都是107.178打头的，在XX-Net的设置页面和gae_proxy文件下的多个文件夹内清除了这个IP段，但并没有效果。依旧时常出现流量异常的提示，并且依旧是这个IP。

**Comment by Eri5Ch** [comment]
参考我7天之前的回复，至少到现在没有再次出现这个流量异常。

**Comment by jzp820927** [comment]
107.178 说明是走了 GAE，请设置直连规则

**Comment by Hang-Hu** [comment]
我只有上面哪个we're sorry, 下面的验证码输入网页怎么打开啊?

**Comment by jzp820927** [comment]
出现 we're sorry, 请配置直连规则

**Comment by Eri5Ch** [comment]
参考我的回答，至今再也没有出现过这个提示。
