### ISSUE TITLE
一直显示的是请导入CA证书

### ISSUE THREAD

**Issue by tinyperson** [XX-net/XX-Net#4167]
可是已经导入了，还是这样显示。

**Comment by jzp820927** [comment]
哪儿显示请导入 CA 证书

**Comment by tinyperson** [comment]
![image](https://cloud.githubusercontent.com/assets/14156036/18302298/a702aad6-7509-11e6-904f-9ef2b858bb77.png)
这里

**Comment by zhuoquanzhou** [comment]
你用的是不是2.X版本？
我之前在用老版本的时候就出现这个问题，手动装了证书也没用，换成最新的3.1.19版本就好了

**Comment by tinyperson** [comment]
有可能是这个问题，我有一个以前的data文件夹。
里面是
![image](https://cloud.githubusercontent.com/assets/14156036/18303912/fcc34982-7511-11e6-8460-f66ef33d09dd.png)

这几个文件。

但是不存进去要扫描ip很久

**Comment by jzp820927** [comment]
你的证书是导入什么浏览器的？还是导入系统的？

**Comment by tinyperson** [comment]
使用的是chrome浏览器

**Comment by tinyperson** [comment]
我不知道是怎么搞的突然就好了。

我的做法是这样子，把data文件夹先移出来，然后点击运行。

然后会出现一个python什么的证书，同意之后会提示重启浏览器。
重启浏览器会出现ip不够，扫描多久的提示。

最后一次成功的做法是把原来data文件内的CA删掉，再把里面的文件全存到新的data文件夹里。

不知道是不是把以前的CA文件删掉的原因。

**Comment by jzp820927** [comment]
那应该就是证书导致的问题了
