### ISSUE TITLE
使用谷歌学术总是显示IP异常

### ISSUE THREAD

**Issue by zhuoquanzhou** [XX-net/XX-Net#4168]
使用谷歌学术可以正常搜索，点击下载引用endnote文件时，出现错误信息：
<img width="340" alt="_20160907144426" src="https://cloud.githubusercontent.com/assets/11733883/18302301/b2efbd84-7509-11e6-8406-b27adf779222.png">

日志信息：
<img width="514" alt="default" src="https://cloud.githubusercontent.com/assets/11733883/18302373/1e47c25c-750a-11e6-9df0-d8a50ccb9258.png">

这个应该怎么解决？

**Comment by zhuoquanzhou** [comment]
已解决
在[hosts]中加入以下语句就可以解决：
scholar.googleusercontent.com = direct

**Comment by peterxj2006** [comment]
hosts文件还是proxy.ini啊

**Comment by zhuoquanzhou** [comment]
是proxy.ini中的hosts
