### ISSUE TITLE
有关开启xxnet服务之后，打开百度百科乱码问题

### ISSUE THREAD

**Issue by notcrydiedgod** [XX-net/XX-Net#4169]
有关开启xxnet服务之后，搜索百度，在点开百度百科的链接时，打开百度百科直接乱码，类似于这样的链接http://baike.baidu.com/link?url=_mD8SlxThcJ87jZUYPzaTOAVL2uojc-ivTUCk5KFXDuI6jpG87IDxBBRN7Cf0QlFN-4vVSLxOpYfP6yCkfgb-_    
不知道是百度特意加密了，还有开启了这个代理服务之后，可以只针对国外的网站开启代理，国内的就不开启。

**Comment by wenliyang** [comment]
国内网站，就不要用代理上了吧
还有，这是百度的锅

**Comment by jzp820927** [comment]
LS 正解诶

**Comment by notcrydiedgod** [comment]
那个xxnet.zip里的那个SwitchyOmega.crx，放到chrome浏览器里，直接无法添加来自此网站的应用，我在谷歌市场里下载了一个SwitchyOmega可以了。
