### ISSUE TITLE
是否考虑加入其他代理模式的支持？

### ISSUE THREAD

**Issue by renyouguo** [XX-net/XX-Net#417]
如shadowsocks等等。
就像PHP的辅助一样，效果会更好。

**Comment by xxnet** [comment]
恩，这个有需求吗？
有考虑过这种做法，看大家的反馈

2015-05-16 11:14 GMT+08:00 renyouguo <notifications@github.com>:

**Comment by xxnet** [comment]
lantern 2.0， TOR 都是可以翻墙的。
特别是TOR的配置，可以做成针对中国的特定配置，把firefox剥离掉。

lantern 可以给出好的帮助，像现在这样，都不知道怎么用，需要去看大家的讨论。

在 2015年5月16日 上午11:42，Net XX <xxnet.dev@gmail.com>写道：

**Comment by latrikcoasler** [comment]
希望楼主做TＯＲ

**Comment by renyouguo** [comment]
如果能将自动搜索ip与tor结合，能真实太好了。不过估计不现实。

**Comment by xxnet** [comment]
有考虑过tor，结合aws meek，那就封锁难度高很多了。
AWS的业务更多更广泛。

思路很简单，实现一个TOR的Meek，自己扫ip，自己构建HTTP请求，又可以轻松的翻了。

在 2015年5月17日 下午5:50，renyouguo <notifications@github.com>写道：

**Comment by renyouguo** [comment]
那为何没有做呢？那个比吃力不讨好的gae爽多了啊。

**Comment by xxnet** [comment]
发现有更加强大的项目，正在开发，估计半年不会推出大的改动。
所以这些改进，有兴趣的朋友可以帮忙搞搞，有问题我会提供技术支持。

在 2015年5月18日 上午10:31，renyouguo <notifications@github.com>写道：
