### ISSUE TITLE
Ubuntu 下 XX-Net 设置全局代理

### ISSUE THREAD

**Issue by New2World** [XX-net/XX-Net#4175]
怎么在Ubuntu下设置XX-Net，让其它应用能够使用代理

**Comment by jzp820927** [comment]
不知道你指的应用，具体是什么？Linux 下的代理设置没有通过方法，不过大部分可以通过设置 代理环境变量 实现。

**Comment by New2World** [comment]
比如 terminal 访问google源

**Comment by jzp820927** [comment]
terminal 下不同的应用方法也不一样，你是要用 git 嘛？大部分命令带有设置代理的 命令参数，或者在配置文件里面设置代理。还有一部分可以设置环境变量来实现。

**Comment by weichuanqianmu** [comment]
All settings --> Network --> Network Proxy.
