### ISSUE TITLE
Ubuntu 16.04 Chrome意外关闭

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#4179]
![2016-09-10 15-57-04](https://cloud.githubusercontent.com/assets/17242539/18408991/f9aa70de-7770-11e6-9043-2ef14cc0a79b.png)

- 系统是今天刚装上的
- 这个错误报告出现在第一次执行./start的时候
- 随后部署Appid的时候也会再次出现这个错误报告，而且跳出来的google登陆页面是用firefox打开的，可是我的默认浏览器是Crome
- 装了好几次xxnet一直都没看见过图标……

>XX-Net Status:
>
sys-platform: x86_64, Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
os-release: 4.4.0-36-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36
xxnet-version: 3.2.6
>
python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn
>
ipv6-status: 0
gws-ip-num: total:176 good:170
network-status: OK
connected-link: new:2 used:0
worker: h1:18 h2:6
scan-ip-thread-num: 50
ip-quality: 183
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
Ubuntu Server 16.04 运行 XXNET 没有任何问题。应该不是 XX 的问题，先检查下 python 的版本？
python --version

**Comment by xiaoyan94** [comment]
@jzp820927 2.7.12

**Comment by xiaoyan94** [comment]
@jzp820927 那个ProcCwd的路径是xxnet，ProcCwd是进程相关的什么东西么？

**Comment by jzp820927** [comment]
不是大清楚，我的 chrome 从来没出现过这种错误。你是用的 64 位的chrome？还是 32位的

**Comment by xiaoyan94** [comment]
@jzp820927 Chrome版本 53.0.2785.101 (64-bit)

**Comment by jzp820927** [comment]
我的是 ubuntu server 没有图像界面的，自然更不会有浏览器了，怎么可能看的到浏览器里面的错误报告

**Comment by xiaoyan94** [comment]
@jzp820927 没有图形界面666

**Comment by jzp820927** [comment]
反正我这儿没什么问题，我估计要不就是浏览器的问题，要不就是图像系统的兼容性问题。

**Comment by xiaoyan94** [comment]
行吧，反正就第一次运行会意外关闭。以后再运行也没报过错了。不影响使用。
