### ISSUE TITLE
PAC智能代理模式下打不开8085页面

### ISSUE THREAD

**Issue by junegucas** [XX-net/XX-Net#4194]
pac智能代理模式下打不开8085页面，而全局代理能打开8085页面，切换到pac模式下8085页面能正常操作，但显示“请检查浏览器代理设置”。诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14915
os-system: Windows
os-version: 10.0.14915
os-release: 10
os-detail: Version:10-0; Build:14915; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:70 good:46
network-status: OK
connected-link: new:2 used:0
worker: h1:25 h2:6
scan-ip-thread-num: 50
ip-quality: 518
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

重装CA无效，删除data文件夹无效。

现在pac模式下只能访问google，其他被墙网站不能访问。

**Comment by jzp820927** [comment]
你标题说 “PAC智能代理模式下打不开8085页面”
内容里面又是说 “切换到pac模式下8085页面能正常操作”
不确定，你究竟是能打开，还是不能打开

**Comment by junegucas** [comment]
@jzp820927 直接点击菜单室打不开的，先全局代理打开8085页面，再切换到pac模式，8085页面有效

**Comment by jzp820927** [comment]
那你现在的问题是？PAC 无法翻墙？

**Comment by junegucas** [comment]
pac下python假死
pac下导致除了google外其他都不能上网。
唉 已经说得很明白了。。。。。

**Comment by junegucas** [comment]
我在问题描述里已经说得很清楚。你非要把问题简化成“PAC无法翻墙”。抱歉，打扰到你。不需要你再提供帮助了。
