### ISSUE TITLE
校园网内用XX NET 启用IPV6 播放视频的时候缓冲很慢怎么破

### ISSUE THREAD

**Issue by kagurainroy** [XX-net/XX-Net#4199]
在浏览非视频播放和直播网页时，都非常流畅 加载很快
http://127.0.0.1:8085/ 显示的延迟也不算高 241 之前有150
但是一旦访问BILIBILI 或者其他视频网站 腾讯 优酷还有其他直播网站 斗鱼 虎牙什么的
视频和直播就是加载不出来。。。

**Comment by jzp820927** [comment]
用国外代理访问国内网站，速度肯定慢了，相当于绕路走了
