### ISSUE TITLE
怎么也上不去了

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#42]
刚刚开始时搞了一下，神马facebook, twitter,都上去了。好开心
然后后来不知怎么搞了一下，就怎么也上不去了。
proxy switchsharp都重装好几次了也不行。
怎么办啊

**Comment by xxnet** [comment]
估计是配错了，已反馈解决

**Comment by nly4lov** [comment]
谢谢你昨天的邮件，按你说的重新下载一个，已经解决啦。
不过奇怪的是，只要动过config，就会翻不了墙，连国内网站也打不开。
