### ISSUE TITLE
改进建议：mac系统下托盘图标建议改为黑白色。

### ISSUE THREAD

**Issue by ninggu2008** [XX-net/XX-Net#420]
因为mac系统下托盘图标大都是黑白色，现有xx-net图标是彩色，看起来不够协调。
我试着做了一个黑白的，（ICO格式无法上传，所以上传的PNG格式）效果良好。
![favicon](https://cloud.githubusercontent.com/assets/10868267/7665236/4a4453be-fbe1-11e4-83d0-b2d1d9c7b626.png)

![2015-05-16 3 38 16](https://cloud.githubusercontent.com/assets/10868267/7665245/9e59423e-fbe1-11e4-96da-16a83d83a036.png)

另外，看wiki，表述不太清楚，不知如何隐藏托盘图标。
我是把mac_tray.py删除，把non_tray.py改名为mac_tray.py，但是无效，不知道是不是理解错误了。请问到底如何更改？步骤希望详细些。

**Comment by xxnet** [comment]
欢迎提交补丁

在 2015年5月16日 下午3:38，ninggu2008 <notifications@github.com>写道：

**Comment by mickeybricks** [comment]
您好，我想咨询一下我的托盘图标不知怎么之前还有，后来可能被我关了，请问再怎么让图标出现在托盘位置呢？多谢

**Comment by yjd** [comment]
您好，我想咨询一下我的托盘图标不知怎么之前还有，后来可能被我关了，请问再怎么让图标出现在托盘位置呢？多谢

http://127.0.0.1:8085/?module=launcher&menu=config
