### ISSUE TITLE
是否可手动选择用于连接的appid？

### ISSUE THREAD

**Issue by NAVrasZ** [XX-net/XX-Net#4205]
RT
appid申请时有多个地区可选，xx-net可否手动选某个appid用于连接？这边连youtube测速欧洲的貌似更快些
另外日志中总是出现 [INFO] ssl error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590), create full domain cert for host:107.178.195.220 是否和我使用xx-net代理utorrent有关？（话说使用xx代理bt的正确方式是填入http 127.0.0.1 8087 吗，，50M上传ut做种只有600k，均速40k总觉得哪里出了问题..）

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2013
network-status: OK
connected-link: new:2 used:0
worker: h1:18 h2:5
scan-ip-thread-num: 6
ip-quality: 125
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by CHN008** [comment]
**当然可以同时使用2个账号的appid,我都用3个账号的APPID呢.**

**Comment by NAVrasZ** [comment]
@CHN008 原来这样，那我可以把3个地区的appid都申请得平均一点了~

挂代理后原来下载也很慢（几乎没速度，seeder有几个但连我都是2kb....）

**Comment by CHN008** [comment]
我创建APPID时有六个选择的是欧洲数据中心.

20Mb电信宽带,看Youtube能达到9Mb/s多,用另一个项目的Hosts能达到27m
b/s.

**Comment by jzp820927** [comment]
都是流弊的带宽

**Comment by S-H-Y-GitHub** [comment]
当然可以啊

**Comment by NAVrasZ** [comment]
多谢楼上~

**Comment by theratlesnake** [comment]
@CHN008 不是说了速度和服务器数据中心无关吗？难道欧洲的快一点？

**Comment by jzp820927** [comment]
不同的地域和 ISP ，可能情况不一样吧，可以自己测试一下
