### ISSUE TITLE
快捷方式没了...

### ISSUE THREAD

**Issue by imhentai** [XX-net/XX-Net#421]
今天重装系统后，xxnet的文件夹保留着
双击start.vbs运行后发现没有生成桌面快捷方式，请问有什么办法弄出来吗？

**Comment by xxnet** [comment]
删除 data/launcher/config.yaml 再启动XX-Net



在 2015年5月16日 下午6:50，imhentai <notifications@github.com>写道：

**Comment by imhentai** [comment]
多谢~



jianwen.tang@foxmail.com
 
发件人： xxnet
发送时间： 2015-05-16 20:32
收件人： XX-net/XX-Net
抄送： imhentai
主题： Re: [XX-Net] 快捷方式没了... (#421)
删除 data/launcher/config.yaml 再启动XX-Net 



在 2015年5月16日 下午6:50，imhentai <notifications@github.com>写道：
