### ISSUE TITLE
360浏览器无法进入Google

### ISSUE THREAD

**Issue by FinalAgito** [XX-net/XX-Net#4210]
打开XX-Net以后，
我使用360浏览器的话其他网站都可以进，比如Youtube,不过就是无法进入谷歌。
但是换Chrome浏览器就可以进入，可能是什么原因呢？

**Comment by everhopingandwaiting** [comment]
那就 不要用 360浏览器的啦

**Comment by wpyok500** [comment]
被劫持了，修复下浏览器试试。

**Comment by FinalAgito** [comment]
啊，我刚刚试了试，修复了一下还是一样....

**Comment by cobob** [comment]
这个问题你自己都已经解决了，只要卸载流氓360就好，Chrome可是目前为止地球上最好用的浏览器。

**Comment by zhencaihao** [comment]
删掉360换谷歌浏览器不久好了嘛。反正360浏览器的也用谷歌内核啊。

**Comment by FinalAgito** [comment]
..啊哈....虽然是不错啦，但是总有些情况会用到360浏览器，如果能解决当然最好啦...

**Comment by FinalAgito** [comment]
嘛，采用直接重装了一次的方法可以了...总之先谢谢大家啦！
