### ISSUE TITLE
mediafire下载卡在0.5mb

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#4213]
不管下哪个文件都这样

**Comment by jzp820927** [comment]
看看日志有没有什么报错信息

**Comment by jzp820927** [comment]
应该是 autorange 造成的，试着调整一下 autorange 的参数试试

**Comment by Temmie-hOi** [comment]
在哪儿改，config.ini里面没有

**Comment by Temmie-hOi** [comment]
改了没有用啊

**Comment by jzp820927** [comment]
要不就把 autorange 关了试试，再不行就试试 x_tunnel 吧，不过用来下载感觉挺费流量的

**Comment by Temmie-hOi** [comment]
怎么关

**Comment by jzp820927** [comment]
额，刚刚看了下配置文件，没发现有开关。或者你把 maxsize 数值调大点试试，再不行，就只有换其他代理了，比如 goproxy，或者你要下载的文件比较小的话可以试试 x_tunnel。
