### ISSUE TITLE
求助，xx-net可以让客户端翻吗？

### ISSUE THREAD

**Issue by Zangwill** [XX-net/XX-Net#4216]
因为要下Google云端硬盘中1G的文件，直接用chrome下老是断掉，于是下了Google云端硬盘的客户端（和onedrive差不多，在用户文件下放一个同步文件夹的那种），但是客户端不能用xx-net代理联网。
但是，我用 Lantern（https://github.com/getlantern/forum ）却可以让Google云端硬盘客户端联网，让文件自动同步，但是只有800M的免费流量。
我用的是3.2.5的稳定版，已经试过“全局通过GAEproxy代理”，Google云端硬盘客户端不能联网。

当然，我本来目的是要下云端硬盘上的文件，大家如果有办法让chrome自带的下载不断线，又或者有其他办法下载的话解决的话，就谢谢了。
我要下的是：Google Drive (One Full): https://goo.gl/Md5Tj7
或Google Drive (6 of 6): https://goo.gl/dDTQrQ
或Google Drive (One Full 2): https://goo.gl/7ZCMrj

**Comment by jzp820927** [comment]
用蓝灯可以的话，XX 应该也行，证书导入系统了吗？

**Comment by Zangwill** [comment]
@jzp820927 证书导入了，但是还是无法连接

**Comment by jzp820927** [comment]
看看 日志有无相关信息，确认是否走了 XX 代理。

**Comment by carotin** [comment]
试试 SocksCap64 吧，或者找个hosts

**Comment by jzp820927** [comment]
用 hosts 也行，这么大个问题，确实很难保障代理稳定性

**Comment by magnet1215** [comment]
drive 用hosts最好

**Comment by cdmask** [comment]
hosts不是经常要换吗--

**Comment by jzp820927** [comment]
现在 IP 都已经很稳定了，没什么变动，所以不用经常换，至于什么时候开始变动，可能就是到了重要日子吧

**Comment by Zangwill** [comment]
谢谢各位了，换到学校移动的CMCC-EDU后，用x-net，然后可以用chrome直接下下来，虽然网速不稳定，时高时低，但总算一直在下，而且网速有时达到1.5m/s，看到一次高到2m/s，低的时候就只有0~4~8~16~20kb/s了。
不会断（即使低到0了也不会断）是不是因为用了CMCC-EDU的原因？
平常的时候CMCC-EDU只有400kb/s，这里能达到2m/s，这有没有xx-net的功劳？
。。。

**Comment by jzp820927** [comment]
有可能吧，说不定 移动的 edu 有福利呢

**Comment by cdmask** [comment]
edu鼓励你翻墙！
