### ISSUE TITLE
路由 R7000 装XX-NET之后 IPAD证书问题

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#4219]
以前电脑便装有XX-NET 然后iPad通过邮件导入证书 iPad通过电脑代理翻没有问题 这次装入路由器 电脑通过路由代理翻  没有问题 但是 iPad导入新证书时显示 '尚未验证'    '描述文件安装失败 无法与帮助程序通信 '   安装不上导致的问题就是https网站无法打开 请问大大 这如何解决????

**Comment by jzp820927** [comment]
把你原来能用的证书，传到路由上去用。

**Comment by sky123456789sky** [comment]
对 上传之后可以用了  感谢大大 不过为何iPad不能安装新的证书了????

**Comment by jzp820927** [comment]
有可能是新生成的证书有问题吧，我只是估计，没验证过，有时间，你可以验证下。

**Comment by haotia** [comment]
兄弟你是怎么安装的我 6300V2安装的懒人脚本 ，进不去配置界面

**Comment by sky123456789sky** [comment]
你应该是没改配置

**Comment by onplus** [comment]
@sky123456789sky  自问自答

**Comment by sky123456789sky** [comment]
又出问题了 chrome升级 旧的证书不能用了 新证书又导入不了 疯了

**Comment by jzp820927** [comment]
只有 ios 不能导入？其他设置都可以正常导入？
