### ISSUE TITLE
之前用是1.09的版本，我总是下载后覆盖更新的。5月份出问题上不了后 ，更新版本，重新部署appid 总是失败。

### ISSUE THREAD

**Issue by barnettzane** [XX-net/XX-Net#422]
以前以为等新版本会自动好，现在都好几个版本了，仍无法重新部署。XX-net无法用快一个月了，求指点。

以下是无法部署的信息：
May 16 19:37:34 - ============  Begin upload  ============
appid:z3zhaozilong 

May 16 19:37:34 - Application: z3zhaozilong
May 16 19:37:34 - Host: appengine.google.com
May 16 19:37:34 - Rolling back the update.
May 16 19:37:55 - upload  fail: <urlopen error _ssl.c:492: The handshake operation timed out>

May 16 19:37:55 - Retry again.

May 16 19:37:56 - Application: z3zhaozilong
May 16 19:37:56 - Host: appengine.google.com
May 16 19:37:56 - Rolling back the update.
May 16 19:38:16 - upload  fail: <urlopen error _ssl.c:492: The handshake operation timed out>

==============================================================

以下是状态 信息（覆盖更新的）：

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
XX-Net Version	1.14.6
Launcher Version	1.0.9
GoAgent Version	3.1.42
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	z3zhaozilong|z3zhaozilong1|z3zhaozilong2|z3zhaozilong3
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP

**Comment by barnettzane** [comment]
PAC URL    	http://127.0.0.1:8086/proxy.pac
Google IP	       2953

**Comment by redstoneleo** [comment]
自己想找一些好IP加进去，然后看看能否访问
https://appengine.google.com
如果还是了问题就说明没有好IP，找到好IP才行啊
