### ISSUE TITLE
突然显示证书无效

### ISSUE THREAD

**Issue by kennir** [XX-net/XX-Net#4221]
突然显示证书无效，按照wiki里的教程，删掉证书重新生成导入还是这个问题，浏览器状态也显示Fail，已经尝试多次disable / enable auto proxy了

xx-net我记得原先是设置为中文，发生这个问题后xx-net变成英文了，有可能是关联的问题

XX-Net Status:

sys-platform: x86_64, Darwin-16.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
os-release: 16.0.0
os-detail: Release:10.12; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2237
network-status: OK
connected-link: new:0 used:0
worker: h1:31 h2:6
scan-ip-thread-num: 46
ip-quality: 159
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
把整个 data 目录全部删除，再删除导入的证书，然后重新运行，重新导入新证书

**Comment by kennir** [comment]
有效， 感谢 @jzp820927

**Comment by kennir** [comment]
Close Issue
