### ISSUE TITLE
Bug：无法自动更新

### ISSUE THREAD

**Issue by liaoyaoheng** [XX-net/XX-Net#423]
1选取自动更新到测试版，未能后台自动更新

2手动点选检查更新时，提示：发生未知错误, 请刷新页面重试.

win7 64X chrome 41
XX-Net Version	1.14.2

**Comment by liaoyaoheng** [comment]
更新，1.14.9后，问题2依旧（2手动点选检查更新时，提示：发生未知错误, 请刷新页面重试.）

Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
XX-Net Version	1.14.9
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9

**Comment by liaoyaoheng** [comment]
问题2解决，问题1待确认

**Comment by xxnet** [comment]
记得前面的版本有个bug

2015-05-17 6:44 GMT+08:00 liaoyaoheng <notifications@github.com>:

**Comment by KevinLeung007** [comment]
问题2怎么解决的？

**Comment by liaoyaoheng** [comment]
之前刷新几次就好了，现在又不可以了@KevinLeung007 

请求修复，因为每次手动更新，本地需要重新扫描ip，好麻烦啊。

**Comment by xxnet** [comment]
手动更新的时候，保留data目录就可以保留之前找到的ip

在 2015年6月1日 下午2:51，liaoyaoheng <notifications@github.com>写道：
