### ISSUE TITLE
请问各位大大'允许远程连接Web控制端' 这个值在哪个文件里存着??

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#4230]
XX-NET安装在路由器 不小心关了"允许远程连接Web控制端"  现在打不开配置页面了 请问这项值在哪里存着 我直接改下试试
 已经找到了 哈哈哈

**Comment by jzp820927** [comment]
web 界面可以设置

**Comment by N46AN** [comment]
data/launcher/config.yaml
