### ISSUE TITLE
APPID 流量已用完？实际有大量剩余

### ISSUE THREAD

**Issue by N46AN** [XX-net/XX-Net#4231]
XXnet 3.2.3 - 提示 APPID 流量已用完
```
Sep 20 08:19:49.961 - [WARNING] all appid out of quota, wait 514 seconds to reset
```
但登录 App Engine Dashboard 发现并未用完。8个 Appid 用量都在 0.1 GB 上下浮动。

**Comment by jzp820927** [comment]
除了流量外，检查其他指标，是不是其他指标用完了？另外你是用的直接的 appid？还是公共的？

**Comment by N46AN** [comment]
感谢关注，用的是自己的appid。原来是 Frontend Instance Hours 用完了。都提示：
Frontend Instance Hours	 28.61 of 28 Instance Hours
不过对此参数不甚理解。
谢谢！

**Comment by jzp820927** [comment]
从字面意思理解是 前端实例小时数，不也不是大明白，什么情况下会消耗这个东西，不知道你放了几个 appid？如果条件允许的话，建议多放几个 appid
