### ISSUE TITLE
路由器装XX-NET 手机远程VPN到路由器 可以上网 但不能翻墙

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#4242]
R7000 梅林固件装的XX-NET 以前是二级路由 手机VPN到上一级路由并设置192.168.1.1 :8087为代理 可以翻墙 现在直接拆掉上一级路由 用R7000直接拨号上网 然后R7000开VPN服务器  手机VPN到R7000 并在手机VPN选项下设置192.168.1.1:8087代理  可以上网 但不能翻墙 SS openvpn 都试了 都是可以上网 不可以翻墙 然后试了下手机不用VPN 直接设置代理为路由器的公网IP:8087 可以翻墙  查了下 据说要用iptables 完全不懂啊 求助各位大神了??????跪求

**Comment by jzp820927** [comment]
不明白，你为什么要设置 VPN，感觉 多此一举，直接设置 IP 端口就可以了。

**Comment by sky123456789sky** [comment]
主要是XX-NET没有用户名 密码 如果直接用他代理 这样会直接暴露在网络上 如果关掉允许远程连接的话 那么就只有内网用户可以翻墙 我的想法是VPN进去 然后再翻墙 结果是光手机设置代理是做不到的  可以不可VPN进去的机器上网全走8087端口代理上网????如何设置??

**Comment by jzp820927** [comment]
如果仅仅是为了认证，推荐你用 XX-MINI，是 XXNET 的精简版，非常适合路由器。文件很小，才十几KB，而且最重要的是带 认证 功能。

**Comment by sorsoso** [comment]
和你同样情况,不过我是小米R1D刷TOMATO开启PPTP SERVER.怎么试都不行,最后只能用ddns:端口的方式了.其实也没啥.路由设定每天重启的,又是ddns.不太容易被别人盗用

**Comment by sky123456789sky** [comment]
其实主要是为了翻墙方便 直接一点手机自带的VPN就可以翻墙 省去在手机端设置代理的步骤 因为gfwlist不全 不能翻的网站太多 所以不用PAC.........跪求大神帮忙 装MINI 这个问题还是解决不了

**Comment by jzp820927** [comment]
估计应该是 VPN 改动路由表造成的吧

**Comment by sky123456789sky** [comment]
问题解决了  清除DNS缓存后 VPN正常了  并且前面有个认知有问题 关闭允许远程连接 其实只是关闭了webUI 8087 8086还是可以使用的 至于验证问题 简单粗暴的解决了 直接iptables写入只允许本地网络与VPN网络的IP访问 哈哈哈哈 还有个疑问是INPUT链上竟然有允许anywhere访问anywhere  还怎么也删不掉这条规则 这是有问题吧??????

**Comment by jzp820927** [comment]
不明觉厉，DNS缓存 和 VPN 好像并没有什么直接联系。
把整个链的默认规则设为拒绝不就行了

**Comment by sky123456789sky** [comment]
有关系 服务端路由重启后 公网IP改了 VPN客户端并没有及时更新DDNS下发的新IP 这就导致VPN无法连接 那条规则删掉 然后保存 路由一重启 然后就又恢复了 还保持在我自己写入的规则之后第一位 因此应该是路由固件自带的 貌似无法删除 也找不到这条究竟在哪写着.......所以我能想到的治标不治本的办法就是 在/jffs/scripts目录编辑firewall-start文件 直接在每次重启时候自动删除这条 还没有试 应该是可行

**Comment by jzp820927** [comment]
好吧，如果是用的 DDNS 的话，那就是 DNS 的问题了。
openwrt 系统不太熟悉，Linux 的话，改下默认规则就行了。不过你说的通过启动脚本解决应该也行。

**Comment by sky123456789sky** [comment]
大大 我想问下 在INPUT的最后一条写有 iptables -A INPUT -s 0.0.0.0/0 -d 0.0.0.0/0  -j DROP 那么前面那 条 iptables -I  INPUT -s 0.0.0.0/0 -d 0.0.0.0/0  -j ACCEPT 还起作用吗 是不是前边有了ACCEPT 后面的加的这条DROP 就没有作用了??

**Comment by jzp820927** [comment]
按照 iptables 的匹配逻辑，是前面的规则如果匹配成功，就会忽略后面的规则，就是你说的，前面如果有 accept 规则并且匹配成功，后面的 drop 就无效了。

**Comment by leo1qaz** [comment]
请问问题解决了，能q吗495150905

**Comment by leo1qaz** [comment]
我的是华硕固件也是有这个问题，

**Comment by jzp820927** [comment]
@leo1qaz 怎么你也要套一层 VPN？
