### ISSUE TITLE
代理HTTP不起作用

### ISSUE THREAD

**Issue by blindlf** [XX-net/XX-Net#4252]
用curl代理访问HTTP地址没有反应，在日志中也没有出现任何log。访问HTTPS则正常。
操作系统macOS Sierra

**Comment by jzp820927** [comment]
那说明 代理本身没问题，可能是你访问的 http 服务器的问题吧

**Comment by blindlf** [comment]
debug以后发现，不知道是否因为升级了Mac，调用socket.gethostbyname_ex时卡住，不往下走了。

**Comment by jzp820927** [comment]
额，你的意思是系统的问题，那我就帮不到你了，我没有 mac 机器，没法测试

**Comment by blindlf** [comment]
fixed https://github.com/XX-net/XX-Net/commit/c10e93fdf293b444578fab039b46f21d90e123e3
