### ISSUE TITLE
每次启动XX-NET都会提示用户账户控制（UAC）

### ISSUE THREAD

**Issue by DaNuo** [XX-net/XX-Net#4257]
各位好，我使用的xx-net版本为3.2.5，系统是win7 64位，每次启动XX-NET时都会弹出下图的用户账户控制，请问怎么才能静默启动，谢谢！

![img_20160923_091905_meitu_1](https://cloud.githubusercontent.com/assets/22383553/18771779/30e0d63a-8174-11e6-8bd9-50d3b478460c.jpg)

**Comment by jzp820927** [comment]
把 UAC 关掉

**Comment by DaNuo** [comment]
@jzp820927 请问有不关闭UAC的方法吗

**Comment by jzp820927** [comment]
或者把 uac 的安全等级调低一点？

**Comment by DaNuo** [comment]
解决了每次启动都要弹出UAC的问题，解决办法如下：
1. 使用计划任务创建xx-net的快捷方式，教程：http://www.laifuying.com/archives/623  。
2. 然后运行下创建的快捷方式，提示导入证书成功。
3. 最后把计划任务创建的快捷方式每次启动都不会有uac弹框。

然后我尝试了下原生的xx-net快捷方式，发现运行原生的快捷方式（就是首次运行xx-net自动创建的快捷方式）也不会有uac弹窗了。
把计划任务禁用掉，运行原生的xx-net快捷方式也不会有弹窗。

这下就很完美了，把计划任务删掉，运行原生的xx-net快捷方式不会有弹窗了！！！

总结：可能是我刚开始安装的时候xx-net的证书导入有问题，我检查了下证书certmgr.msc，发现有两个一样的证书都在信任的根证书里面，所以没有发现到底哪儿出了问题，用计划任务导入的证书才可以，手动导入的证书还是会有UAC弹窗的，可能需要用管理员导入证书吧。

**Comment by DaNuo** [comment]
问题解决，关闭了，谢谢@jzp820927的帮助
