### ISSUE TITLE
xx net忽然很慢，有时还会断掉，但是一直显示“一切正常，你可以访问真正的互联网了”

### ISSUE THREAD

**Issue by xiyaoeva** [XX-net/XX-Net#4258]
**# 问题描述：**
两周前安装好了xxnet，一直非常好用，网速也很快，可是这两天，变得很卡，虽然一直显示“一切正常，你可以访问真正的互联网了”，但是google非常卡，总让填验证码，有时竟然appstore和github也上不去，mac笔记本，系统10.11.3 (15D21)。

**# 诊断信息：**
XX-Net Status:

sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:90
network-status: OK
connected-link: new:2 used:0
worker: h1:33 h2:2
scan-ip-thread-num: 50
ip-quality: 780
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

# **部分日志：**
Sep 23 10:49:26.134 - [DEBUG] 66.96.226.244 worker close:idle timeout
Sep 23 10:49:27.145 - [DEBUG] ssl_closed 113.171.253.57
Sep 23 10:49:27.145 - [DEBUG] 113.171.253.57 worker close:idle timeout
Sep 23 10:49:27.873 - [DEBUG] GAE POST https://www.google-analytics.com/r/collect
Sep 23 10:49:28.181 - [INFO] GAE t:307 s:35 POST https://www.google-analytics.com/r/collect h2_get_head:305
Sep 23 10:49:31.550 - [DEBUG] 61.238.239.190 close:host pool alive_timeout
Sep 23 10:49:31.551 - [DEBUG] ssl_closed 61.238.239.190
Sep 23 10:49:34.138 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 10:49:34.143 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:49:34.144 - [DEBUG] get ip:118.98.111.77 t:516
Sep 23 10:49:34.653 - [DEBUG] get ip:202.75.141.213 t:934
Sep 23 10:49:35.017 - [DEBUG] get ip:202.28.85.213 t:915
Sep 23 10:49:35.145 - [DEBUG] get ip:202.75.147.33 t:933
Sep 23 10:49:35.646 - [DEBUG] get ip:202.75.141.233 t:1017
Sep 23 10:49:35.832 - [DEBUG] create_ssl update ip:202.28.85.213 time:611 h2:0
Sep 23 10:49:35.832 - [DEBUG] get ip:106.103.1.141 t:1018
Sep 23 10:49:36.099 - [DEBUG] create_ssl update ip:202.75.147.33 time:740 h2:0
Sep 23 10:49:36.147 - [DEBUG] get ip:202.224.62.45 t:1027
Sep 23 10:49:36.569 - [DEBUG] create_ssl update ip:202.75.141.233 time:752 h2:0
Sep 23 10:49:36.570 - [DEBUG] create_ssl update ip:202.75.141.213 time:1762 h2:0
Sep 23 10:49:36.698 - [DEBUG] create_ssl update ip:106.103.1.141 time:692 h2:0
Sep 23 10:49:37.051 - [INFO] DIRECT chucked t:2907 s:2056 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:49:37.055 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 10:49:37.061 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:49:37.061 - [DEBUG] host_conn_pool clients4.google.com get:202.28.85.213 handshake:611
Sep 23 10:49:37.221 - [DEBUG] create_ssl update ip:202.224.62.45 time:913 h2:0
Sep 23 10:49:37.863 - [DEBUG] create_ssl update ip:118.98.111.77 time:3561 h2:0
Sep 23 10:49:38.161 - [INFO] DIRECT chucked t:1099 s:438 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:49:48.276 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 10:49:48.287 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:49:48.288 - [DEBUG] host_conn_pool clients4.google.com get:202.28.85.213 handshake:611
Sep 23 10:49:48.844 - [INFO] DIRECT chucked t:555 s:2037 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:50:05.444 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Sep 23 10:50:05.751 - [INFO] GAE t:306 s:35 POST https://www.google-analytics.com/collect h2_get_head:304
Sep 23 10:50:06.937 - [DEBUG] ssl_closed 216.58.200.7
Sep 23 10:50:06.937 - [DEBUG] 216.58.200.7 worker close:GoAway: additional_data:session_timed_out
Sep 23 10:50:15.640 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Sep 23 10:50:15.945 - [INFO] GAE t:304 s:35 POST https://www.google-analytics.com/collect h2_get_head:300
Sep 23 10:50:18.895 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 10:50:18.900 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:50:18.901 - [DEBUG] host_conn_pool clients4.google.com get:202.28.85.213 handshake:611
Sep 23 10:50:20.153 - [DEBUG] ssl_closed 106.103.1.160
Sep 23 10:50:20.153 - [DEBUG] 106.103.1.160 worker close:idle timeout
Sep 23 10:50:21.054 - [INFO] DIRECT chucked t:2153 s:739 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:50:21.060 - [INFO] GAE CONNECT clients4.google.com:443
Sep 23 10:50:21.066 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D
Sep 23 10:50:21.066 - [DEBUG] host_conn_pool clients4.google.com get:202.28.85.213 handshake:611
Sep 23 10:50:21.486 - [INFO] DIRECT chucked t:419 s:437 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=RFJnj2pboicEfbcYiymPZg%3D%3D

**Comment by jzp820927** [comment]
IP太少了，建议执行一下“扫描所有IP”

**Comment by xiyaoeva** [comment]
非常感谢！管用！

**Comment by lxianwei003** [comment]
只找到“”检查所有IP“ 没找到“”扫描所有IP“，是一样的吗，还大扫描线程数设置多少合适，我的XX-NET是跟楼主一样，没解决！

**Comment by lxianwei003** [comment]
@jzp820927

**Comment by lxianwei003** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2999 good:1760
network-status: OK
connected-link: new:2 used:0
worker: h1:19 h2:1
scan-ip-thread-num: 0
ip-quality: 78
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xiyaoeva** [comment]
@lxianwei003  没错，就是检查所有IP

**Comment by jzp820927** [comment]
就是检查所有IP
还有，你看状态页  scan-ip-thread-num: 0  你的扫描线程为 0，是不是你把扫描线程关了，至于具体数值，默认的 50 就很合适了。

**Comment by lxianwei003** [comment]
@jzp820927  具体扫描线程开关在哪？高级->自动调整扫描线程数，只有这个，谢谢啊 现在急用XX-NET,又出现这种问题，小白 有点着急

**Comment by jzp820927** [comment]
没有开关，高级，设置，最大扫描线程数，如果设置为 0，就是关闭扫描，非0就是开启扫描
