### ISSUE TITLE
部分网站502 Urlfetch Error

### ISSUE THREAD

**Issue by hanx-phy** [XX-net/XX-Net#4262]
Python Urlfetch Error: 'GET'
https://krs.kek.jp/uskek/ui/UI_C0401E.do无法链接，现实502
其他网页正常

Sep 24 10:31:05.038 - [INFO] GAE CONNECT krs.kek.jp:443
Sep 24 10:31:05.070 - [DEBUG] GAE CONNECT GET https://krs.kek.jp/uskek/ui/UI_C0401E.do
Sep 24 10:31:05.070 - [DEBUG] ssl_pool.get:216.58.200.2 handshake:128
Sep 24 10:31:05.197 - [INFO] GAE 3728|61.238.239.236|5363 t:319 s:488 hs:116 200 https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=kDzFdx4GAzuHskoauhsRQg%3D%3D
Sep 24 10:31:08.366 - [WARNING] APPID error:502 url:https://krs.kek.jp/uskek/ui/UI_C0401E.do
Sep 24 10:31:08.367 - [DEBUG] 216.58.200.2 close:app err
Sep 24 10:31:08.367 - [DEBUG] ssl_closed 216.58.200.2
Sep 24 10:31:18.386 - [INFO] GAE CONNECT clients4.google.com:443
Sep 24 10:31:18.403 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=kDzFdx4GAzuHskoauhsRQg%3D%3D
Sep 24 10:31:18.403 - [DEBUG] ssl_pool.get:61.238.239.236 handshake:116
Sep 24 10:31:19.055 - [INFO] GAE 3728|61.238.239.236|6255 t:651 s:1769 hs:116 Spd:5562 200 https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=kDzFdx4GAzuHskoauhsRQg%3D%3D
Sep 24 10:31:19.059 - [INFO] GAE CONNECT clients4.google.com:443
Sep 24 10:31:19.074 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=kDzFdx4GAzuHskoauhsRQg%3D%3D
Sep 24 10:31:19.074 - [DEBUG] ssl_pool.get:61.238.239.236 handshake:116
Sep 24 10:31:19.431 - [INFO] GAE 3728|61.238.239.236|8427 t:356 s:550 hs:116 200 https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=kDzFdx4GAzuHskoauhsRQg%3D%3D

**Comment by jzp820927** [comment]
可能是 GAE 本身的一些局限造成的吧，或者用 x_tunnel试试
