### ISSUE TITLE
ip被封的太厉害了。

### ISSUE THREAD

**Issue by KeymanLai** [XX-net/XX-Net#4269]
原本1000多的ip 100左右的延迟。今天查看下只剩下260个ip  380左右的延迟了。

**Comment by jzp820927** [comment]
不至于吧，没感觉IP有什么大变动

**Comment by KeymanLai** [comment]
你的有多少？
我今早打开状态页面确实是显示260个ip的，昨天状态页显示1000多。然后听你说了，我也去检查了下所有ip的。运行了后又变回了2787？可能是无法同步或同步不及时引起的假象吧。

**Comment by jzp820927** [comment]
感觉最近很多人反应，用一下就不能用了，然后检查了下所有ip，又好了，过一会又不行了，再检查了下所有ip，又好了，不知道是个例，还是普遍情况，估计得观察段时间了

**Comment by hzxie** [comment]
@jzp820927 
我也有相同的情况~

**Comment by huimiao638** [comment]
me too

**Comment by jzp820927** [comment]
难道是 GFW 能识别 GAE 流量了，开始间歇性干扰。如果是这样，估计就得改变扫描策略了。不过X 大都退居了，这个问题很难解决了。

**Comment by zhencaihao** [comment]
以前开这个软件2、3个小时，怎么也能拿到200个左右的IP，昨天我开了3个小时，IP只多了5、60个，扫描线程是50。用检查IP，原来1500多的，检查完了就剩1000多一点了。

**Comment by CHN008** [comment]
我这里也出现这种情况了,刚开启时只有60多个可用IP了,开一段时间又能慢慢涨回去,大半天后又能到1000多.

**Comment by jzp820927** [comment]
如果只涨，不减，那倒是正常

**Comment by acrossabc** [comment]
广州这边正常哦  ip一直慢性增加
![36233](https://cloud.githubusercontent.com/assets/16570906/18837641/1232e5d2-8437-11e6-82ae-21b467600e47.JPG)

**Comment by jzp820927** [comment]
我去 7K+，太BT了

**Comment by dgy125** [comment]
最近经常出现“请检查浏览器代理设置。”的问题，绝不是个例。

**Comment by jzp820927** [comment]
经常有人反映，确实不是个例，可以试试插件所有IP。

**Comment by xiaoliang2121** [comment]
![image](https://cloud.githubusercontent.com/assets/22428192/18941280/60d63592-8642-11e6-86a4-fa54a955e2ae.png)

**Comment by wqwin** [comment]
西安 90

**Comment by nly4lov** [comment]
原来是将近3000的Ip，不到200的延迟，现在是548，432

**Comment by jzp820927** [comment]
主要还是要稳定的 IP 才行，感觉现在低延时的 IP 还是多，就是稳定的太少了

**Comment by nly4lov** [comment]
我无所谓的其实，能翻就好了，哪怕慢一点。

**Comment by jzp820927** [comment]
关键就是现在好多人反应，翻着翻着就不能翻了。

**Comment by nly4lov** [comment]
咋会有这样的事？！能翻就是一直能，哪会忽然不能

**Comment by jzp820927** [comment]
我也不知道什么原因，然后检查下所有IP又好了，反正就是反复的这样

**Comment by nly4lov** [comment]
我连你这个环节都没有。就是一直在用。

**Comment by jzp820927** [comment]
那可能你的 ISP 连接 google 的 IP 比较稳定吧。不同地域，网络环境不一样。

**Comment by nly4lov** [comment]
不明觉厉

**Comment by dou4cc** [comment]
最近低延迟低速：
![default](https://cloud.githubusercontent.com/assets/7764678/19014739/873d8fb4-8827-11e6-918d-ba881d3be6e9.png)
![default](https://cloud.githubusercontent.com/assets/7764678/19014742/a0b52e70-8827-11e6-90a1-31b4e1e4c8c3.png)

**Comment by jzp820927** [comment]
这个早就发现了，低延时的带宽都不高，不知道是 GFW 的干扰，还是本身这个服务器的带宽就很低。感觉现在的扫描策略不适用了，不能安装延时排序，应该按照延时和带宽综合排序才行。

**Comment by nly4lov** [comment]
不明白。反正我所有网站都看得了。很happy.

**Comment by jzp820927** [comment]
网站都不是问题，问题是视频。

**Comment by nly4lov** [comment]
我很少看视频，不过youtube都能看到的啊。

**Comment by jzp820927** [comment]
我也很少看视频，不过现在的人，都喜欢用 720P，1080P，来比拼速度。

**Comment by nly4lov** [comment]
我电脑里上百G的电影都没时间看，哪有时间看在线这些扯淡的视频。。。。。

**Comment by jzp820927** [comment]
现在早就不流行下载了，现在流行 1080P online

**Comment by nly4lov** [comment]
online再流畅，还能有自己电脑里用播放器调整快进快退那样痛快吗？！我一个电影通常跳着审核一下就删除掉了啊

**Comment by jzp820927** [comment]
好吧，你是非主流。
