### ISSUE TITLE
ubuntu下XX-net是不是只能在终端中运行？

### ISSUE THREAD

**Issue by Zangwill** [XX-net/XX-Net#4273]
在ubuntu中每次启动XX-net都要先打开终端，然后cd到XX-net的目录，再sudo ./start，之后终端就会一直运行，关闭终端就是退出XX-net，有没有不用打开终端就能运行的办法，点击XX-net的图标是启动不起来的，它只会闪一闪就没了。

还有再ubuntu中chrome也会有卡住十几秒的情形（我设置ip的扫描数为10），之前这么多解决办法哪个是公认或最有效的解决办法，麻烦给个链接，谢谢。

**Comment by yaoguaishou** [comment]
第一次启动不要用sudo

**Comment by jzp820927** [comment]
XX-Net.desktop 这个不行麽？

**Comment by smallst** [comment]
`nohup ./start &`

打开后选择开机启动下次应该就不需要再启动了

**Comment by YaoC** [comment]
用 `./xx_net.sh` 不要用 `./start`

**Comment by Zangwill** [comment]
已解决，一开始装的时候不用 sudo
