### ISSUE TITLE
使用XX-Net时发现了大量的SYN和TCP重发

### ISSUE THREAD

**Issue by 0x4368697473756B6F** [XX-net/XX-Net#4274]
这样正常嘛=。=

<img width="943" alt="2016-09-25 1 33 53" src="https://cloud.githubusercontent.com/assets/17697118/18813208/bdc8a47c-8324-11e6-940f-50f3d1a005ba.png">
<img width="950" alt="2016-09-25 1 33 37" src="https://cloud.githubusercontent.com/assets/17697118/18813209/c122eaf6-8324-11e6-9cc6-0e4837c4fd9e.png">

在我上传上面两个图片的时候:
<img width="400" alt="2016-09-25 1 35 40" src="https://cloud.githubusercontent.com/assets/17697118/18813217/01f2ca88-8325-11e6-91ec-066bb95f7cc0.png">

总感觉不应该有那么多Retransmission吧

应该和我的网络有关系，但是我觉得应该更加智能一点，避免使用不稳定的IP

环境是OS X 10.11 El Capitan,浙江电信

XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:no

ipv6-status: 0
gws-ip-num: total:1637 good:305
network-status: OK
connected-link: new:2 used:0
worker: h1:23 h2:0
scan-ip-thread-num: 50
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yaoguaishou** [comment]
不懂，但我想问一下楼主这是什么软件？

**Comment by 0x4368697473756B6F** [comment]
抓包用的是wireshark

**Comment by 0x4368697473756B6F** [comment]
仔细想了一下，这一堆SYN是因为XX-Net一直在扫描IP引起的。将扫描数设置为0后就没有上面的那种情况了。

**Comment by 0x4368697473756B6F** [comment]
说起来，在网络断开的时候XX-Net还会不停的扫描IP，这个设计不是很好吧？CPU占用会变很高的。

**Comment by jzp820927** [comment]
目前设计的网络断开应该会停止扫描。

**Comment by 0x4368697473756B6F** [comment]
在mac上经常会遇到网络其实已经断了但是wifi还显示已连接的情况，这个时候xx-net还会继续扫描，导致性能占用非常高

**Comment by 0x4368697473756B6F** [comment]
还如如ping路由器什么的来的靠谱

**Comment by jzp820927** [comment]
作者都没怎么维护了，得靠自己了。
