### ISSUE TITLE
无法部署服务器端

### ISSUE THREAD

**Issue by ruihui** [XX-net/XX-Net#428]
下了1.14.6和1.14.9，appid什么的填好之后点击开始部署没有反应，换了多个浏览器(firefox，chrome，ie)

**Comment by litbeat** [comment]
我也是部署无能啊！
开启了弱验证。
然后挂了vpn（啥都能开），但还是不能部署我的appid……

May 18 20:22:53 - Retry 29 time...

May 18 20:23:21 - Application: ~~~~
May 18 20:23:21 - Host: appengine.google.com
May 18 20:23:21 - Rolling back the update.
May 18 20:23:41 - upload fail: The read operation timed out

----------状态页

Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36
XX-Net Version	1.14.6
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Google IP	3000
connected link(帮助)	1,0
ip-connect-interval	10
scan ip thread num	  20

**Comment by ruihui** [comment]
你还有log，我连log都不显示，点日志也没反应，什么都没反应。还在以前部署的还能用，但是主页上建议重新部署啊，可是部署不了

**Comment by blackangeldsf** [comment]
我的win7开始是这样，后来重新启动了下，居然好了。
