### ISSUE TITLE
重新安装xx时, 提示“检查浏览器代理设置”, 无法安装证书

### ISSUE THREAD

**Issue by HaohongWANG** [XX-net/XX-Net#4281]
大家好, 小白请教一下~

### 情况描述
fedora 24, 之前运行时命令行提示私有appid流量超限, 然后无脑重下了xxnet, 重新布置时提示请检查代理, 直接打开谷歌等出现安全提示, 然而在浏览器安装证书时提示文件无法解析. 这种情况该怎么解决呢? 请问是否存在由于以前的配置文件未清理导致的错误?
谢谢!

---
### 状态 
XX-Net Status:

sys-platform: x86_64, Linux-4.7.4-200.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
os-system: Linux
os-version: #1 SMP Thu Sep 15 18:42:09 UTC 2016
os-release: 4.7.4-200.fc24.x86_64
os-detail: Dist:Fedora; Version:24; ID:Twenty Four
architecture: 64bit,
browser: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:45 good:45
network-status: OK
connected-link: new:2 used:0
worker: h1:18 h2:7
scan-ip-thread-num: 50
ip-quality: 596
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
出现安全提示 就是证书没账号，可以试试删除所有导入的XX证书，删除 data 目录，重新运行XX，重新导入XX 新生成的证书

**Comment by HaohongWANG** [comment]
@jzp820927 这个方法尝试过了，但是没有效果，xx一直提示检查代理设置，安装证书时提示无法解析。重新下载了xx并重装了switchyomega 仍旧不好用……

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4028
这个帖子是讨论如何导入证书到 Linux 的，你可以参考下。你的问题就是证书没有成功导入，或者 google “fedora 导入 证书”，只要证书正确导入到系统就OK了。

**Comment by quanru** [comment]
我删除原有的 XX-Net 证书，重新导入就好了。

**Comment by HaohongWANG** [comment]
经过一番努力，问题已经解决了。
@jzp820927 首先感谢您的帮助。尝试了 #4028 中的方法，但是Ubuntu中的那个文件夹在Fedora下不存在，又搜索了下适合我的证书导入命令，尝试后证书导入成功，但XX仍旧提示导入失败。
@quanru 起初已经按照官方wiki尝试过删除证书的方法，但是不奏效，不知是否和我当初删除xx不彻底有关
最终成功的方法是重新安装了Chrome，重新下载了XX....- -||
