### ISSUE TITLE
提示导入浏览器CA证书，但导入后仍显示链接有问题

### ISSUE THREAD

**Issue by duskmoon314** [XX-net/XX-Net#4283]
XX-Net版本3.2.5

在一台未安装XX-Net的电脑上安装后，提示需导入证书。已尝试从系统和chrome两种方式导入，也可以看到证书中有，但是无法浏览google页面，显示链接有问题。

另：chrome中显示无权限删除

请问如何处理？

**Comment by jzp820927** [comment]
可以导入的证书，全部删除，然后删除 data 目录，然后重新运行XX，重新导入新生成的证书

**Comment by duskmoon314** [comment]
谢谢，已解决
