### ISSUE TITLE
MAC os X EI Capitan 代理无法生效

### ISSUE THREAD

**Issue by zhaoxiaohui** [XX-net/XX-Net#4288]
XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:2107 good:896
network-status: OK
connected-link: new:2 used:0
worker: h1:25 h2:1
scan-ip-thread-num: 10
ip-quality: 97
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

以上是诊断信息，刚刚从Windows 10转战过来，之前Windows一直好好的，Mac Chrome配置好之后，将Stackoverflow等站点加入过滤规则，日志有显示请求信息，然后也只是显示一下，之后就一直在页面加载了。
可以打开Google，但是用Google搜索之后，点击链接就打不开了，奇怪的是可以加载Title，页面出不来内容

**Comment by jzp820927** [comment]
F12 看看是那些域名无法加载

**Comment by zhaoxiaohui** [comment]
我把访问方式都改成https:然后就可以了

**Comment by jzp820927** [comment]
你别给我说，你用 google 都是用的 http ？

**Comment by zhaoxiaohui** [comment]
google当然是https啊，就是用google搜索的时候 转入stackoverflow时链接时http的，这时候需要把url=http%3A%2F%2Fstackoverflow.com这个地方改为https

**Comment by jzp820927** [comment]
建议你可以安装 HTTPS Everywhere 的 chrome 检查，可以自动上 https，不用你手动添加。
