### ISSUE TITLE
无法找到 outlook.live.com 的服务器 DNS address

### ISSUE THREAD

**Issue by emevael** [XX-net/XX-Net#4291]
用的是chrome浏览器
其他网站都可以登录，速度快也稳定。
只有登录outlook邮箱会出现问题，时好时坏，无法登录的时间多些！
会出现以下文字：
![qq 20160930102249](https://cloud.githubusercontent.com/assets/22534400/18978703/e332eae8-86f7-11e6-9846-299727bcaf79.jpg)

无法访问此网站
无法找到 outlook.live.com 的服务器 DNS address。
DNS_PROBE_FINISHED_BAD_CONFIG

**Comment by jzp820927** [comment]
这个是域名无法解析，和 XX 应该没关系，你用的什么 DNS？

**Comment by emevael** [comment]
自动获取的DNS地址

**Comment by emevael** [comment]
我测试过了 没打开XX前提下 正常登录 只要打开XX，过段时间就会出现DNS错误问题

**Comment by jzp820927** [comment]
实在不行，就直连吧，反正 outlook.live.com 也没被墙，没必要走XX代理
