### ISSUE TITLE
Youtube不能观看视频

### ISSUE THREAD

**Issue by MarshallZhug** [XX-net/XX-Net#4296]
1.播放视频的位置一直是进度圈在旋转
2.其他都是正常的，能看到视频下方的评论
3.昨天都能够一直看YouTube的视频、
4.我按着教程来的，昨天下载的稳定版

**Comment by linhua55** [comment]
请贴出 视频 地址！
试着降低清晰度 测试一下

**Comment by MarshallZhug** [comment]
所有的Youtube视频都一样，一直加载，然后提示 “ 出了点问题，请稍后再试。（播放Id: xxxxxx）”,我试了降低清晰度，没什么变化的

**Comment by zhencaihao** [comment]
试试在在“隐身窗口”里打开能不能看。

**Comment by jzp820927** [comment]
除了视频，其他都没问题麽

**Comment by MarshallZhug** [comment]
对啊，目前为止就是视频有问题，一直加载，然后到最后就显示“出了点问题..............”。

**Comment by MarshallZhug** [comment]
@zhencaihao 隐身窗口， 是个什么东西哦

**Comment by jzp820927** [comment]
ctrl + shift + n 就会打开隐身窗口，应该和这个没啥关系。

**Comment by MarshallZhug** [comment]
@jzp820927  当时是有黄色字体的warning，可是看不懂.... 嘻嘻~
不过，现在可以正常看视频了， 照这种状态应该是偶尔发生这种情况，这种偶然有什么前提吗？
Add : 因为家里有点事情，没能及时和你交流深感歉意.

**Comment by jzp820927** [comment]
这种偶尔，有可能就是 IP 受到干扰吧，不过也不是大确定，长期观察看看吧

**Comment by MarshallZhug** [comment]
@jzp820927 ok, Thx

**Comment by MarshallZhug** [comment]
Oct 06 18:56:12.022 - [WARNING] server app return fail, status:510
Oct 06 18:56:12.023 - [WARNING] report_out_of_quota:xxnet-371405
Oct 06 18:56:12.023 - [WARNING] 216.58.195.79 _consume_single_frame:ConnectionResetError()
Oct 06 18:56:12.023 - [DEBUG] ssl_closed 216.58.195.79
Oct 06 18:56:12.023 - [DEBUG] 216.58.195.79 worker close:disconnect:ConnectionResetError()
Oct 06 18:56:12.023 - [DEBUG] 216.58.195.79 worker close:appid out of quota:xxnet-371405
Oct 06 18:56:12.058 - [WARNING] server app return fail, status:510
Oct 06 18:56:12.059 - [WARNING] report_out_of_quota:xxnet-102
Oct 06 18:56:12.059 - [DEBUG] ssl_closed 59.18.35.168
Oct 06 18:56:12.059 - [DEBUG] 59.18.35.168 worker close:appid out of quota:xxnet-102
Oct 06 18:56:12.061 - [WARNING] 59.18.35.168 _consume_single_frame:ConnectionResetError()
Oct 06 18:56:12.061 - [DEBUG] 59.18.35.168 worker close:disconnect:ConnectionResetError()
Oct 06 18:56:12.081 - [INFO] DIRECT t:277 204 s.youtube.com /api/stats/qoe?event=streamingstats&fmt=243&afmt=251&cpn=HEIewlMzFkZbk975&ei=vi32V7bTH4jh4QLI9LI4&el=detailpage&docid=bIQA_aAXF8k&ns=yt&fexp=9412914%2C9417893%2C9419452%2C9422596%2C9428398%2C9431012%2C9433096%2C9433221%2C9433946%2C9434000%2C9434047%2C9434289%2C9435526%2C9436617%2C9438066%2C9438966%2C9439580%2C9439880%2C9439970%2C9441148%2C9443913%2C9444238%2C9446054%2C9446297%2C9446364%2C9446645%2C9447476%2C9447864%2C9447917%2C9448193%2C9448262%2C9449034%2C9449541&cl=135000414&html5=1&c=WEB&cver=1.20161001&cplayer=UNIPLAYER&cbr=Chrome&cbrver=51.0.2704.84&cos=Windows&cosver=6.1&vps=0.000:N,0.014:N&afs=0.014:251::i&vfs=0.014:243:244::i&view=0.014:854:480&bwe=0.014:130000&bh=0.014:0.000&vis=0.014:3&cmt=0.014:0.000
Oct 06 18:56:12.170 - [INFO] GAE t:328 s:0 GET https://www.youtube-nocookie.com/gen_204?attributionpartner=meizhe get_response:325
Oct 06 18:56:12.247 - [INFO] GAE t:323 s:1972 GET https://p2-hef2m5m57r2zo-3iznk3tlv2cddgey-if-v6exp3-v4.metric.gstatic.com/v6exp3/iframe.html h2_get_head:318
Oct 06 18:56:12.342 - [INFO] GAE t:1009 s:186 GET https://r13---sn-i3b7knez.googlevideo.com/crossdomain.xml get_response:1006
Oct 06 18:56:12.412 - [WARNING] server app return fail, status:510
Oct 06 18:56:12.412 - [WARNING] report_out_of_quota:zhouxingyucn6


@jzp820927 、这是部分的log你能看出问题所在吗？

**Comment by raawaa** [comment]
@MarshallZhug 我今天也遇到了相同的问题……

**Comment by raawaa** [comment]
@MarshallZhug 我是上海电信光纤。断开光猫重新拨号换了ip地址之后就好了……

**Comment by jzp820927** [comment]
Oct 06 18:56:12.022 - [WARNING] server app return fail, status:510
Oct 06 18:56:12.023 - [WARNING] report_out_of_quota:xxnet-371405

APPID 超出限额了，你是用的 公共 appid 吗？

**Comment by MarshallZhug** [comment]
@jzp820927  对，我用的就是公共 appid

**Comment by jzp820927** [comment]
这个的话，要不就部署自己的 appid ，要不就等下载 16：00 重置流量。

**Comment by MarshallZhug** [comment]
@jzp820927 thx.. 我**部署了自己的appid，问题解决**！

**Comment by Peter128** [comment]
Dec 03 15:41:51.481 - [WARNING] gae_handler.handler send response fail. t:0 e:error(32, 'Broken pipe') https://s.ytimg.com/yts/cssbin/www-pageframe-2x-webp-vflrQQKHT.css
Dec 03 15:41:51.481 - [INFO] GAE 73|184.150.152.212|161 t:336 s:0 hs:581 304 https://s.ytimg.com/yts/cssbin/www-pageframe-2x-webp-vflrQQKHT.css
Dec 03 15:41:51.486 - [WARNING] gae_handler.handler send response fail. t:0 e:error(32, 'Broken pipe') https://s.ytimg.com/yts/cssbin/www-player-2x-webp-vfloWpJy-.css

这个报错私啥意思？youbube视频不能看了。出现情况跟楼主一样的。

**Comment by jzp820927** [comment]
只有 youtube 有问题？其他网站有问题吗？

**Comment by f18love** [comment]
蓝灯可以开youtube哦   xx-net就不行了

**Comment by yemao221** [comment]
2024年最稳定梯子VPN，科学上网2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
[![QQ20240730 - 132944](https://github.com/user-attachments/assets/d537a5f3-3ec8-4d71-b979-99a01ea8a3c9)](https://www.xxxlsop.com/#/register?code=sf9UTRC0)
