### ISSUE TITLE
1.1.0后 ubuntu 每次都要sudo 运行

### ISSUE THREAD

**Issue by yqfang** [XX-net/XX-Net#43]
从1.0.6开始就一直用，非常好用， 升级1.1.0后有一些疑问，望告知

- 环境 ubuntu
- 升级后发现每次都要sudo 运行， 不适合脚本化， 每次都会导入一次证书， 问一下这里导入证书的意义是？
- 至今没有明白 web 页面下 config 和 deploy 的区别， 我理解都是配置app id？
- 1.1.0 比1.0.9 改进了那些？

**Comment by xxnet** [comment]
* 新版有登录后自动启动功能
  可能有问题，我看看
* deploy是部署服务端
  config是配置客户端用哪些appid，是设置客户端
* 改进的要点，请看： https://github.com/XX-net/XX-Net/releases
