### ISSUE TITLE
深度系统使用出问题了，需要预装的软件和模块都安装了，请求支援

### ISSUE THREAD

**Issue by Meteor-lws** [XX-net/XX-Net#4301]
诊断信息如下：

XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-2-deepin-amd64-x86_64-with-Deepin-15.3-unstable
os-system: Linux
os-version: #1 SMP Deepin 4.4.6-4 (2016-07-01)
os-release: 4.4.0-2-deepin-amd64
os-detail: Dist:Deepin; Version:15.3; ID:unstable
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11+
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:104 good:90
network-status: OK
connected-link: new:2 used:0
worker: h1:12 h2:1
scan-ip-thread-num: 50
ip-quality: 485
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

目前的问题主要有翻墙仍然失败，一直提示浏览器代理设置出错，证书导入出错，xdg-open: no method available for opening 'http://127.0.0.1:8085/'

正在自己努力排查问题，也请求各位帮忙，谢谢了

**Comment by Meteor-lws** [comment]
搞定了，手动导入证书就都ok了

**Comment by Meteor-lws** [comment]
xdg-open: no method available for opening 'http://127.0.0.1:8085/'
此问题好像仍然存在，不知道大家碰到过吗？我用的是chrome稳定版浏览器

**Comment by linhua55** [comment]
上面这个问题说明，没有对这个MIME类型配置默认的打开方式     ，你应该没有配置默认的浏览器

 > xdg-settings get default-web-browser

> man xdg-open

**Comment by Meteor-lws** [comment]
xdg-settings get default-web-browser
结果：google-chrome.desktop
而且这也和系统的设置一致，但仍然这样报错，不知道为什么

**Comment by jzp820927** [comment]
只要不影响代理使用就行了吧，至于这个问题，自己打开浏览器，手动输入网址 http://127.0.0.1:8085/ 不就行了

**Comment by Meteor-lws** [comment]
我现在就是这样用的，只是这样系统托盘就没用了，点击没反应

**Comment by jzp820927** [comment]
现在 linux 发行版太多了，很难兼容到所有系统，不过最基本的代理功能是通过的。就是那些辅助功能，兼容性不是太好。特别是托盘和菜单这一块。

**Comment by nmb2b** [comment]
请问楼主是怎么解决的，同深度系统，证书导入失败，代理失败，手动导入提示私钥错误是什么情况，我用的最新的chrome,我全局的时候，ip显示是谷歌服务器，但就是翻不了，私密链接

**Comment by nmb2b** [comment]
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-2-deepin-amd64-x86_64-with-Deepin-15.3-unstable
os-system: Linux
os-version: #1 SMP Deepin 4.4.6-4 (2016-07-01)
os-release: 4.4.0-2-deepin-amd64
os-detail: Dist:Deepin; Version:15.3; ID:unstable
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11+
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:174
network-status: OK
connected-link: new:2 used:0
worker: h1:27 h2:2
scan-ip-thread-num: 30
ip-quality: 197
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by Meteor-lws** [comment]
@nmb2b 我是直接重新手动导入证书解决的，没有出现手动导入证书失败的问题，你看看需要安装的那些openssl之类的软件你都安装了没。另外你这个ID略叼啊。。。
