### ISSUE TITLE
为什么xx-net和shadowsocks的端口冲突啊

### ISSUE THREAD

**Issue by vansto** [XX-net/XX-Net#4304]
shadowsocks是3.3.2
xxnet是3.2.6

shadowsocks端口是1080 xxnet是8087怎么会冲突呢

启动xxnet后打开shadowsocks提示：
System.Exception: 端口已被占用
   在 Shadowsocks.Controller.Listener.Start(Configuration config)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()

其实在使用上也没什么问题，就是不知道这种情况是怎么造成的

**Comment by jzp820927** [comment]
部署 XXNET 和 SS 端口冲突，而是 X-tunnel 和 SS 端口冲突，因为 X-tunnel 默认也是监听的 1080 端口。

**Comment by vansto** [comment]
多谢

**Comment by chuhaibo** [comment]
我之前都是两个同时开，旧版本没有冲突问题。xx-net升级到最新的稳定版后就出现了。请问如何破？

**Comment by jzp820927** [comment]
改掉其中一个的端口就行了

**Comment by chuhaibo** [comment]
请问如何改以及改成哪个端口？

**Comment by jzp820927** [comment]
那得看你是想改 ss 的端口，还是改 XX 的端口？

**Comment by cnjeffliu** [comment]
xx跟公司的一个软件1080冲突了，怎么修改 X-tunnel的1080为其他的？

**Comment by xxnet** [comment]
​参考
https://github.com/XX-net/XX-Net/wiki/X-Tunnel-Config-file

修改

"socks_port" : 1080,

其他的就不管它

**Comment by cnjeffliu** [comment]
已解决，tks
