### ISSUE TITLE
xtunnel支付只能用paypal吗

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#4305]
不考虑支持支付宝吗，这样付款方便可以吸引购买啊

**Comment by jzp820927** [comment]
作者可能是考虑到安全问题，就设置太多支持方式，而且作者现在已经没维护项目了。如果需要的话，可以留下你的 x_tunnel 账号，我送你点流量用。

**Comment by sunyingjian** [comment]
同求 xtunnel流量，，，

**Comment by jzp820927** [comment]
需要流量的，先注册 x_tunnel 账号，然后留下账号

**Comment by Temmie-hOi** [comment]
iQuickdrawX@gmail.com 感谢资助_(:_」∠)_

**Comment by Temmie-hOi** [comment]
iQuickdrawX@gmail.com

**Comment by jzp820927** [comment]
@Temmie-hOi 已转 2G，请查收

**Comment by Temmie-hOi** [comment]
xtunnel用不了，一直错误
Oct 06 20:23:43.206 - [WARNING] session not running, can't connect
Oct 06 20:23:43.206 - [WARNING] Socks4 connect fail, no conn_id

**Comment by jzp820927** [comment]
xtunnel 和迅雷有兼容性问题，需要卸载迅雷。还有 SS 也要关闭，不然端口会冲突。

**Comment by wenliyang** [comment]
@jzp820927 ss不用关闭，修改本地端口

**Comment by jzp820927** [comment]
都一样，只要端口不冲突就行了

**Comment by zhanghongyuuu** [comment]
fi322u8@gmail.com同求流量

**Comment by jzp820927** [comment]
@zhanghongyuuu 已转 2G，请查收

**Comment by zhanghongyuuu** [comment]
谢谢～

**Comment by kukuxz007** [comment]
kukuxz007@gmail.com 谢谢

**Comment by jzp820927** [comment]
@kukuxz007 已转，清查

**Comment by jjjyyyllll** [comment]
@jzp820927 guoqibest@qq.com 求流量谢谢了~

**Comment by jzp820927** [comment]
@jjjyyyllll 已转，清查

**Comment by bearai** [comment]
@jzp820927 求流量 bearai003010@gmail.com 多谢

**Comment by jzp820927** [comment]
@bearai 已转，请查。

**Comment by bearai** [comment]
谢谢。

2017-01-20 0:37 GMT+08:00 天朝屁民 <notifications@github.com>:
