### ISSUE TITLE
mac点击start不能打开，自动完成，显示name 'python_path' is not defined

### ISSUE THREAD

**Issue by eglits** [XX-net/XX-Net#4307]
打不开“start.command”，因为它来自身份不明的开发者。

然后这是后面运行之后的

iMacpoop:XX-Net apple$ Traceback (most recent call last):
  File "launcher/start.py", line 62, in <module>
    darwin_lib = os.path.abspath( os.path.join(python_path, 'lib', 'darwin'))
NameError: name 'python_path' is not defined

**Comment by jzp820927** [comment]
是不是没安装 python 环境？
打开终端执行 python --version 看看有没有输出结果？

**Comment by eglits** [comment]
前几天还正常的然后突然这样子了

**Comment by jzp820927** [comment]
是什么系统？会不会是系统问题

**Comment by szh7379** [comment]
看着扩展名应该是os x

**Comment by eglits** [comment]
os 10.11.3 (15D21)

**Comment by jzp820927** [comment]
MAC 问题挺多的，很多人反映，最近升级了 sierra 10.12 后，xx 不能使用的问题。应该是苹果升级造成的 bug。

**Comment by eglits** [comment]
不是自带python的吗，奇了怪了

**Comment by jzp820927** [comment]
一般情况是带 python 的，你可以终端执行 python --version 看看有没有输出。

**Comment by eglits** [comment]
iMacpoop:~ apple$  python --version 
Python 2.7.10
   


这叫有输出吗？

**Comment by jzp820927** [comment]
恩，python 是有的。

**Comment by jzp820927** [comment]
不对，你弄错了，
/Users/apple/Desktop/XX-Net/start.bat
这个的 windos 的启动文件。你是 mac 运行错命令了。

**Comment by eglits** [comment]
那这样子是没输出了。

**Comment by jzp820927** [comment]
或者你终端运行 ./start 试试

**Comment by eglits** [comment]
运行之后就出现如题目所现

**Comment by jzp820927** [comment]
因为是系统的问题了，mac 最近经常有人反映升级以后，就不能用了，我也没有 mac 系统，无法测试。你可以在 issues 搜索下 mac，有很多反映问题的 issues，看看他们有没有解决。

**Comment by eglits** [comment]
好吧

**Comment by jzp820927** [comment]
为了验证问题，你可以把当前 mac 下面的 XX 整个文件夹，复制到 WIN 下面试试

**Comment by hzx505** [comment]
平时是设为 enable auto gaeproxy
从新开机，要手动切换到 enable global gaeproxy 
再切回 enable auto gaeproxy
才能FQ
不知怎样处理？系统 10.10.5 
另一台就没问题。

**Comment by jzp820927** [comment]
奇葩问题，没有 mac 机器，没法测试。

**Comment by eglits** [comment]
重新下载

**Comment by jzp820927** [comment]
就OK了？

**Comment by eglits** [comment]
对，那时反正用不了然后删了全部重新下载，系统也顺便更新，然后就可以了！反正下载不同版本，全部都试下总有可以的
