### ISSUE TITLE
AppID集体罢工? 发生了啥?

### ISSUE THREAD

**Issue by DragoonKiller** [XX-net/XX-Net#4314]
一开始用的是自己的两个AppID
下午刚申请的
结果晚上发现提示说流量用完了...
其间只下载了大约200M的文件.....
之后换成公用ID
就变成下面这样........

<img width="960" alt="a1" src="https://cloud.githubusercontent.com/assets/22642079/19122076/80a69cd6-8b5b-11e6-9cd7-3edc7ec61b6c.png">

<img width="960" alt="a2" src="https://cloud.githubusercontent.com/assets/22642079/19122116/a8ccab88-8b5b-11e6-9d6c-fb86aa56b6b0.png">

墙内墙外网站都上不去.....
也没法上google看自己的appid....

**Comment by qiurongli** [comment]
我好像上不去google了！不知道什么情况，但是可以上google.hk

**Comment by jzp820927** [comment]
能确认是流量完了吗，最好去 https://console.cloud.google.com/appengine/ 确认下。

**Comment by DragoonKiller** [comment]
流量确实用完了,今早公用ID又正常了,赶紧上google看了看.
大概是公用ID的流量在昨晚被刷爆了? 还是说这是正常现象.........

**Comment by jzp820927** [comment]
公共 appid 经常流量超额，如果有条件的话，建议部署自己的 appid
