### ISSUE TITLE
深度linux手动导入证书失败

### ISSUE THREAD

**Issue by nmb2b** [XX-net/XX-Net#4315]
深度linux，证书导入失败，代理失败（代理已正确配置），手动导入证书提示私钥错误是什么情况，我用的最新的chrome,我全局的时候，ip显示是谷歌服务器，但就是翻不了，私密链接
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-2-deepin-amd64-x86_64-with-Deepin-15.3-unstable
os-system: Linux
os-version: #1 SMP Deepin 4.4.6-4 (2016-07-01)
os-release: 4.4.0-2-deepin-amd64
os-detail: Dist:Deepin; Version:15.3; ID:unstable
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11+
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2824
network-status: OK
connected-link: new:2 used:0
worker: h1:16 h2:1
scan-ip-thread-num: 0
ip-quality: 114
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
如果提示什么 私密链接 的话，很明显是证书没有正确导入系统。
Linux 导入证书好像比较麻烦。你可以试着 google 搜索 “Linux 导入 证书” 应该能找到答案。
