### ISSUE TITLE
无线路由器网络中，打开XX-NET后，一段时间后路由器整体断网

### ISSUE THREAD

**Issue by peterxj2006** [XX-net/XX-Net#4317]
咨询一个问题
我家里有宽带无线路由器（TP-LINK TL-WR886N）
我的笔记本（Win10）在无线网中
发现每次开启XX-NET以后 大概过20分钟就会断网
所有连到这个无线网的手机电脑都上不去网
但我的笔记本强制开GAEProxy全局代理是可以上网的
断10分钟左右 网又自己好了
请问是怎么回事 有什么解决办法？
谢谢

**Comment by jzp820927** [comment]
是不是扫描线程调的太高了？

**Comment by peterxj2006** [comment]
确实是这个原因。改成5以后好了。谢谢提醒！

2016-10-06 15:48 GMT+08:00 天朝屁民 <notifications@github.com>:
