### ISSUE TITLE
手机连上了电脑 为什么不能登录Google商店？

### ISSUE THREAD

**Issue by 1human** [XX-net/XX-Net#4318]
已经连好了 浏览器也能打开Google等等网站
但是不能登录google商店……

**Comment by jzp820927** [comment]
你的意思是 手机通过 PC 共享的 XX 代理上网？

**Comment by 1human** [comment]
恩…

**Comment by hcym** [comment]
共享的 XX-mini 代理google商店可以的

就是没法注册设备，不能下载

可能是限制第三方手机

**Comment by jzp820927** [comment]
手机端共享 PC 的XX 时候，限制比较多，很多 apps 都不支持。
