### ISSUE TITLE
xx-net 无法连上appengine

### ISSUE THREAD

**Issue by crVainglory** [XX-net/XX-Net#4337]
## 问题内容
无法部署appid，ubuntu，部署时反复出现upload fail
appid是没错的，因为我在win下的xxnet可以用它出去
我看了不少之前提出的问题，我的xx-net是链接不上APPengine.google
下好了打开不应该默认的appid是么。google依然打不开
真的不知道怎么破。求救

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。

4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 部署日志Oct 10 00:06:39 - ============ Begin upload ============
appid:brilliant-vent-145109

Oct 10 00:06:39 - Application: brilliant-vent-145109
Oct 10 00:06:39 - Host: appengine.google.com
Oct 10 00:06:39 - Rolling back the update.
Oct 10 00:06:40 - Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
Oct 10 00:06:40 - upload fail: HTTP Error 404: Not Found

Oct 10 00:06:40 - Retry 1 time...

Oct 10 00:06:40 - Application: brilliant-vent-145109
Oct 10 00:06:40 - Host: appengine.google.com
Oct 10 00:06:40 - Rolling back the update.
Oct 10 00:06:41 - Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
Oct 10 00:06:41 - upload fail: HTTP Error 404: Not Found

Oct 10 00:06:41 - Retry 2 time...

Oct 10 00:06:42 - Application: brilliant-vent-145109
Oct 10 00:06:42 - Host: appengine.google.com
Oct 10 00:06:42 - Rolling back the update.
Oct 10 00:06:43 - Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
Oct 10 00:06:43 - upload fail: HTTP Error 404: Not Found

Oct 10 00:06:43 - Retry 3 time...

Oct 10 00:06:45 - Application: brilliant-vent-145109
Oct 10 00:06:45 - Host: appengine.google.com
Oct 10 00:06:45 - Rolling back the update.
Oct 10 00:06:46 - upload fail: ''

Oct 10 00:06:46 - Retry 4 time...

#### 日志
Oct 10 00:06:06 - [INFO] load ip range file:/home/linuxcast/下载/XX-Net-2.0.5/gae_proxy/local/ip_range.txt

Oct 10 00:06:06 - [INFO] load google ip_list num:141, gws num:141

Oct 10 00:06:06 - [INFO] SSL use version:TLSv1_2

Oct 10 00:06:06 - [INFO] ------------------------------------------------------ GAEProxy Version : gae_proxy (python/2.7.1 ) Listen Address : 127.0.0.1:8087 GAE APPID : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159 Pac Server : http://127.0.0.1:8086/proxy.pac ------------------------------------------------------

Oct 10 00:06:07 - [DEBUG] get ip:113.171.242.177 t:279

Oct 10 00:06:07 - [INFO] GAE CONNECT xxnet-update.appspot.com:443

Oct 10 00:06:07 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=c8fd4288-cb21-476a-b2cb-10d651a79104&version=2.0.5

Oct 10 00:06:07 - [DEBUG] get ip:63.117.215.89 t:511

Oct 10 00:06:07 - [DEBUG] get ip:61.238.239.247 t:533

Oct 10 00:06:07 - [DEBUG] get ip:63.117.215.123 t:550

Oct 10 00:06:07 - [DEBUG] get ip:118.98.111.123 t:555

Oct 10 00:06:07 - [DEBUG] create_ssl update ip:61.238.239.247 time:293

Oct 10 00:06:07 - [DEBUG] get ip:118.98.111.118 t:578

Oct 10 00:06:08 - [DEBUG] get ip:65.199.248.59 t:586

Oct 10 00:06:08 - [DEBUG] get ip:202.28.85.234 t:633

Oct 10 00:06:08 - [DEBUG] get ip:23.228.130.108 t:648

Oct 10 00:06:08 - [DEBUG] create_ssl update ip:63.117.215.89 time:619

Oct 10 00:06:08 - [DEBUG] create_ssl update ip:118.98.111.123 time:582

Oct 10 00:06:08 - [DEBUG] get ip:222.165.163.90 t:770

Oct 10 00:06:08 - [DEBUG] create_ssl update ip:63.117.215.123 time:617

Oct 10 00:06:08 - [DEBUG] get ip:203.82.77.210 t:840

Oct 10 00:06:08 - [DEBUG] create_ssl update ip:118.98.111.118 time:617

Oct 10 00:06:08 - [DEBUG] create_ssl update ip:65.199.248.59 time:622

Oct 10 00:06:09 - [DEBUG] create_ssl update ip:202.28.85.234 time:676

Oct 10 00:06:09 - [INFO] DIRECT t:1848 s:1674 200 xxnet-update.appspot.com /update.json?uuid=c8fd4288-cb21-476a-b2cb-10d651a79104&version=2.0.5

Oct 10 00:06:09 - [INFO] GAE CONNECT raw.githubusercontent.com:443

Oct 10 00:06:09 - [DEBUG] GAE CONNECT GET https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md

Oct 10 00:06:09 - [DEBUG] get ip:202.86.162.41 t:899

Oct 10 00:06:09 - [DEBUG] create_ssl update ip:23.228.130.108 time:716

Oct 10 00:06:09 - [DEBUG] create_ssl update ip:222.165.163.90 time:550

Oct 10 00:06:09 - [DEBUG] get ip:216.58.204.36 t:924

Oct 10 00:06:09 - [DEBUG] get ip:216.58.204.29 t:929

Oct 10 00:06:09 - [INFO] GAE t:513 s:914 200 https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md

Oct 10 00:06:09 - [DEBUG] get ip:203.82.77.209 t:937

Oct 10 00:06:09 - [DEBUG] get ip:203.207.55.236 t:951

Oct 10 00:06:10 - [DEBUG] get ip:41.201.164.41 t:951

Oct 10 00:06:10 - [DEBUG] create_ssl update ip:203.82.77.210 time:972

Oct 10 00:06:10 - [DEBUG] get ip:193.4.115.27 t:955

Oct 10 00:06:10 - [DEBUG] get ip:216.58.195.73 t:964

Oct 10 00:06:10 - [DEBUG] create_ssl update ip:216.58.204.36 time:630

Oct 10 00:06:10 - [INFO] scan_ip add ip:118.98.111.93 time:827

Oct 10 00:06:10 - [DEBUG] create_ssl update ip:216.58.204.29 time:847

Oct 10 00:06:10 - [DEBUG] create_ssl update ip:216.58.195.73 time:389

Oct 10 00:06:11 - [DEBUG] create_ssl 113.171.242.177 fail:timed out cost:4004 h:0

Oct 10 00:06:11 - [DEBUG] create_ssl update ip:203.82.77.209 time:876

Oct 10 00:06:11 - [DEBUG] create_ssl update ip:193.4.115.27 time:1174

Oct 10 00:06:12 - [DEBUG] create_ssl update ip:203.207.55.236 time:1915

Oct 10 00:06:13 - [DEBUG] create_ssl 202.86.162.41 fail:timed out cost:4001 h:0

Oct 10 00:06:14 - [DEBUG] create_ssl 41.201.164.41 fail:timed out cost:4002 h:0

Oct 10 00:06:22 - [DEBUG] GAEProxy web_control 127.0.0.1:54788 POST /config?cmd=get_config

Oct 10 00:06:26 - [DEBUG] GAEProxy Web_control 127.0.0.1:54794 GET /deploy?cmd=get_log

Oct 10 00:06:39 - [DEBUG] GAEProxy web_control 127.0.0.1:55104 POST /deploy?cmd=deploy

Oct 10 00:06:39 - [INFO] deploy begin.

Oct 10 00:06:39 - [INFO] GAE CONNECT appengine.google.com:443

Oct 10 00:06:39 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:39 - [DEBUG] ssl_pool.get:118.98.111.123 handshake:582

Oct 10 00:06:40 - [INFO] GAE t:563 s:24 401 https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:40 - [INFO] GAE CONNECT www.google.com:443

Oct 10 00:06:40 - [DEBUG] GAE CONNECT POST https://www.google.com/accounts/ClientLogin

Oct 10 00:06:40 - [DEBUG] GAEProxy Web_control 127.0.0.1:55120 GET /deploy?cmd=get_log

Oct 10 00:06:40 - [INFO] DIRECT t:223 s:65 404 www.google.com /accounts/ClientLogin

Oct 10 00:06:40 - [INFO] GAE CONNECT appengine.google.com:443

Oct 10 00:06:40 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:40 - [DEBUG] ssl_pool.get:118.98.111.123 handshake:582

Oct 10 00:06:41 - [INFO] GAE t:589 s:24 401 https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:41 - [INFO] GAE CONNECT www.google.com:443

Oct 10 00:06:41 - [DEBUG] GAE CONNECT POST https://www.google.com/accounts/ClientLogin

Oct 10 00:06:41 - [DEBUG] host_conn_pool www.google.com get:216.58.195.73 handshake:389

Oct 10 00:06:41 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)

Oct 10 00:06:41 - [DEBUG] GAEProxy Web_control 127.0.0.1:55130 GET /deploy?cmd=get_log

Oct 10 00:06:41 - [INFO] DIRECT t:314 s:65 404 www.google.com /accounts/ClientLogin

Oct 10 00:06:42 - [DEBUG] GAEProxy Web_control 127.0.0.1:55136 GET /deploy?cmd=get_log

Oct 10 00:06:42 - [INFO] GAE CONNECT appengine.google.com:443

Oct 10 00:06:42 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:42 - [DEBUG] ssl_pool.get:118.98.111.123 handshake:582

Oct 10 00:06:43 - [INFO] GAE t:546 s:24 401 https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:43 - [INFO] GAE CONNECT www.google.com:443

Oct 10 00:06:43 - [DEBUG] GAE CONNECT POST https://www.google.com/accounts/ClientLogin

Oct 10 00:06:43 - [DEBUG] host_conn_pool www.google.com get:222.165.163.90 handshake:550

Oct 10 00:06:43 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)

Oct 10 00:06:43 - [INFO] DIRECT t:327 s:65 404 www.google.com /accounts/ClientLogin

Oct 10 00:06:43 - [DEBUG] GAEProxy Web_control 127.0.0.1:55206 GET /deploy?cmd=get_log

Oct 10 00:06:44 - [DEBUG] GAEProxy Web_control 127.0.0.1:55228 GET /deploy?cmd=get_log

Oct 10 00:06:45 - [INFO] GAE CONNECT appengine.google.com:443

Oct 10 00:06:45 - [DEBUG] GAE CONNECT POST https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:45 - [DEBUG] ssl_pool.get:118.98.111.123 handshake:582

Oct 10 00:06:45 - [DEBUG] GAEProxy Web_control 127.0.0.1:55248 GET /deploy?cmd=get_log

Oct 10 00:06:46 - [INFO] GAE t:552 s:24 401 https://appengine.google.com/api/appversion/rollback?version=1&app_id=brilliant-vent-145109

Oct 10 00:06:46 - [INFO] GAE CONNECT www.google.com:443 

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by jzp820927** [comment]
请升级最新版，老版本，已经不支持部署服务端。

**Comment by crVainglory** [comment]
xiexie
