### ISSUE TITLE
Google无限验证

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#4338]
无法搜索，一搜索要么是显示“We're sorry...... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.”要么就是跳验证码但是验证码图片加载不出，有什么办法么

**Comment by Temmie-hOi** [comment]
recaptcha同时也无法使用

**Comment by jzp820927** [comment]
配置直连规则了吗？

**Comment by xelamai** [comment]
same problem here but sometimes i got the luck to avoid it.

**Comment by 451070257** [comment]
我也是，几乎用不了google

**Comment by 451070257** [comment]
我解决了 等google出现图片验证码，你输入一次通过就可以不被阻挡了。不过不知道为什么chrome为什么老是显示不出来验证码图片，，费解

**Comment by Meteor-lws** [comment]
同样的问题，以前会有验证码，输入一次就行了，但现在直接是验证码图片都无法加载了

**Comment by Meteor-lws** [comment]
搞得现在google搜索没法用了

**Comment by Meteor-lws** [comment]
话说google需要验证好像是有异常流量的原因，这些异常流量应该是后台访问youtube之类用来验证翻墙是否成功时造成的流量吧，是不是可以降低下验证频度之类的

**Comment by 451070257** [comment]
@Meteor-lws  出现图片验证码后，你点下设置，把验证图片的那个网页也做成走代理，刷新一遍，就能看到图片了，我是这么干的。

**Comment by 451070257** [comment]
还是希望管理员能解决或者缓解下这个机器人验证问题，辛苦你们啦！

**Comment by Hang-Hu** [comment]
出现不了图片，也没有填验证码的地方。

**Comment by Gavin-Gong** [comment]
我的重启下就好了

**Comment by jzp820927** [comment]
反复出验证码，是因为 google 系域名走 GAE 的原因，只要配置直连规则，一般都能解决。

**Comment by 451070257** [comment]
@jzp820927 原谅我的无知，我以为，天朝之所以无法用google就是因为无法直连google，之所以用goagent，不就是为了让google走代理，难道不是这个原理？
求科普。

**Comment by Temmie-hOi** [comment]
@jzp820927 怎么配置直连规则

**Comment by jzp820927** [comment]
此直连非彼直连。

![image](https://cloud.githubusercontent.com/assets/5740066/19239989/08e61ff8-8f3b-11e6-8cba-245eb86463ec.png)

**Comment by sxyx2008** [comment]
禁用ipv6就ok了

**Comment by YOYOsheep** [comment]
配置直连后貌似可以，但访问google立马变得很慢。（我开始以为无法访问）

**Comment by jzp820927** [comment]
速度慢，可能就是 IP 直连不佳吧，可以试试重新检查所有 IP，直连就是通过 IP 来直接连接 google 的，所以连接速度快慢，完全取决于 IP。
