### ISSUE TITLE
用不了谷歌学术，但是谷歌和邮箱都能上

### ISSUE THREAD

**Issue by chemfly** [XX-net/XX-Net#4340]
XX-Net Status:

sys-platform: x86_64, Darwin-16.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
os-release: 16.0.0
os-detail: Release:10.12; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1463
network-status: OK
connected-link: new:4 used:0
worker: h1:20 h2:11
scan-ip-thread-num: 50
ip-quality: 188
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

YouTube也上不了，Twitter很快能开。

**Comment by jzp820927** [comment]
试试直连规则
