### ISSUE TITLE
mac突然翻不了墙了

### ISSUE THREAD

**Issue by asasdasasd** [XX-net/XX-Net#4343]
XX-Net Status:

sys-platform: x86_64, Darwin-15.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
os-release: 15.3.0
os-detail: Release:10.11.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.5

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:141
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:8
scan-ip-thread-num: 50
ip-quality: 103
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
---
昨天翻的好好的，今天突然就翻不了了，能上国内的网站，但是google上不了
系统是mac 10.11.3

**Comment by asasdasasd** [comment]
重启就好了。。。

**Comment by jzp820927** [comment]
MAC 的问题挺多的
