### ISSUE TITLE
使用XX-Net会与修改hosts冲突

### ISSUE THREAD

**Issue by gaoxinge** [XX-net/XX-Net#4352]
以前使用修改hosts的方法访问google，今天体验了一把XX-Net，还还错，但关闭了XX-Net后，把SwitchyOmega改为系统代理，或者是直接代理就不能上google了（照理来说，hosts文件没变，应该还是能上google的），想请教一下这是为什么？

**Comment by jzp820927** [comment]
是不是关闭了 XXNET 后，IE 的代理，没有被取消掉，可以检查下。

**Comment by gaoxinge** [comment]
@jzp820927 是这样的，十分感谢！
