### ISSUE TITLE
/data/gae_proxy/manual.ini设置直连和SwitchyOmega设置直连有区别吗？

### ISSUE THREAD

**Issue by RouRouChina** [XX-net/XX-Net#4360]
我想问问

> 添加文件:/data/gae_proxy/manual.ini
> 
> 文件内容:
> [hosts]
> google.com = direct
> .google.com = direct

和

> 在SwitchyOmega 里面设置的直接连接
>SwitchyOmega （就是chrome里面可以自动切换代理的扩展）

有什么区别？还是就是一样的？

**Comment by jzp820927** [comment]
区别太大了，manual.ini 里面的直接就是类似于 hosts 的作用，SwitchyOmega 的直连，就是直接访问，肯定不行啊。

**Comment by RouRouChina** [comment]
gae_proxy/manual.ini中

google.com = direct
google.com = gae

值分别是direct和gae时候都是什么意思？用户端和网站服务器端通信流程有什么区别？

**Comment by jzp820927** [comment]
google.com = direct ，表示 google.com 用 google_hk 里面的 IP 连接，类似于 hosts。
google.com = gae ，表示  google.com 用 gae 访问，也就是 浏览器 —> GAE —> google.com。

**Comment by RouRouChina** [comment]
google.com = direct 的模式 hosts 的列表在哪？还是IP是在gae那边远程DNS解析，获取到IP再用本地网络访问？

**Comment by jzp820927** [comment]
没有 hosts 列表，只是和 hosts 一样的原理。如果基本的东西，你都不知道，那很难给你说清楚了，建议你先 google 一下基本常识。

**Comment by RouRouChina** [comment]
我理解本地的hosts，就是把域名强制解析到某个ip啊，在本地C盘不是有hosts文件，里面有就列表。google.com = direct 要是类似于本地hosts 也要有个表吧。

**Comment by jzp820927** [comment]
既然你明白 hosts，就应该知道，google.com = direct，也是一样的代理，是把 google.com 域名解析到 google_hk 里面的 IP。都是一样的道理。
