### ISSUE TITLE
macOS 10.12 每次打开都需要密码

### ISSUE THREAD

**Issue by GFanya** [XX-net/XX-Net#4368]
<img width="555" alt="2016-10-14 7 28 29" src="https://cloud.githubusercontent.com/assets/22836701/19386846/16b86f1c-9249-11e6-9441-531ff7b68c5f.png">

程序使用最新稳定版，使用10.12系统版本时，不用每次输入密码，现在将系统升级至10.12，每次打开或者切换都需要密码，提示“osascript想要进行更改...”
请问是否有办法解决？

**Comment by GFanya** [comment]
把 XX-Net/code/default(或其他文件夹)/launcher/mac_tray.py 里面所有调用 osascript 的语句都加入用户名和密码，例如第176行修改如下
executeCommand            = 'do shell script "%s;%s" user name "aaron" password "12345678" with administrator privileges' % (disableGlobalProxyCommand, enableAutoProxyCommand)
aaron 和 12345678 分别是用户名和密码

**Comment by Ethan0w0** [comment]
楼上做法有效，mac10.12实测

**Comment by hzx505** [comment]
平时是设为 enable auto gaeproxy
从新开机，要手动切换到 enable global gaeproxy 
再切回 enable auto gaeproxy
才能FQ
不知怎样处理？系统 10.10.5 
另一台就没问题。

**Comment by MarshallZhug** [comment]
请问你是用的Chrome还是Safari访问Google?
