### ISSUE TITLE
Mac下打开软件如何自动切换至“Enable Auto GAEProxy”？

### ISSUE THREAD

**Issue by GFanya** [XX-net/XX-Net#4372]
使用macOS Sierra，不想每次打开软件都手动打勾“Enable Auto GAEProxy”，一般使用这种模式，是否有办法，在软件启动时自动切换至“Enable Auto GAEProxy”？

**Comment by jzp820927** [comment]
好像会自动记忆上次选择的状态

**Comment by but0n** [comment]
然而并没有自动记忆

**Comment by jzp820927** [comment]
那就不大情况了，进 web 页看看有没有想过选项吧。
