### ISSUE TITLE
socket accept fail(errno: 24)

### ISSUE THREAD

**Issue by netfun2000** [XX-net/XX-Net#4374]
XX-Net版本：3.2.7，3.2.6
这2个版本都出现了这个现象。
OS:archlinux(运行在树莓派2B+)

XX-Net运行一段时间后（大概1天-2天）会出现这种现象。
Oct 15 12:06:42.036 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.052 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.059 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.054 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.070 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.077 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.073 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.095 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.093 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.107 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.115 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.111 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.129 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.135 - [WARNING] socket accept fail(errno: 24).
Oct 15 12:06:42.142 - [WARNING] socket accept fail(errno: 24).
# 

XX-Net Status:

sys-platform: armv6l, Linux-4.4.24-2-ARCH-armv6l-with-glibc2.4
os-system: Linux
os-version: #1 Tue Oct 11 19:35:27 MDT 2016
os-release: 4.4.24-2-ARCH
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3002 good:4
network-status: OK
connected-link: new:0 used:0
worker: h1:12 h2:3
scan-ip-thread-num: 50
ip-quality: 456
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
哦，第一次见到这种错误，你系统没做什么修改吧

**Comment by netfun2000** [comment]
系统没有做什么修改，只是偶尔更新以下系统（估计是这个造成的）。另外给树莓派加了一个硬件时钟。

**Comment by netfun2000** [comment]
补充一下：
1、那个日志是我重启树莓派后的，不重启的话，这个时候不能够访问。
2、出问题的时候proxy也不能用。

**Comment by jzp820927** [comment]
不好确定是什么问题，你google 搜索下关键字“socket accept fail(errno: 24)”，看有没有相关信息

**Comment by netfun2000** [comment]
socket.accept error 24: To many open files。打开文件太多。
也可能是网络的问题。我再观察观察吧，谢谢了。

**Comment by jzp820927** [comment]
那个啥，你可以把 打开文件数，调高点。
