### ISSUE TITLE
X-Tunnel - AttributeError: 'module' object has no attribute 'inet_ntop'

### ISSUE THREAD

**Issue by Nova41** [XX-net/XX-Net#4376]
使用 XX-Net 3.2.7 的 X-Tunnel 配合 Proxifier 代理 javaw.exe 的网络连接
出现错误 Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'

---

Oct 16 14:28:44.792 - [INFO] use config_path:G:\Utils\XX-Net-3.2.7\data\x_tunnel\client.json
Oct 16 14:28:44.792 - [INFO] Use proxy:127.0.0.1:8087
Oct 16 14:28:44.792 - [DEBUG] x-tunnel no account
Oct 16 14:28:44.792 - [WARNING] x-tunnel session not start
Oct 16 14:28:44.808 - [INFO] Socks5 server listen:127.0.0.1:1080.
Oct 16 14:30:48.125 - [DEBUG] x-tunnel web_control 127.0.0.1:61150 POST /login
Oct 16 14:30:48.392 - [INFO] api:login success t:266
Oct 16 14:30:48.393 - [INFO] update xt_server 104.207.140.47:6666
Oct 16 14:30:48.393 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:965122.000000
Oct 16 14:30:48.630 - [INFO] login_session time:234 msg:Success
Oct 16 14:30:57.578 - [INFO] socks5 ('127.0.0.1', 63259) connect to 127.0.0.1:8087 conn_id:1
Oct 16 14:30:57.937 - [DEBUG] roundtrip time:358 cost:61 transfer_no:1 send_sn:1 send:28 recv_sn:1 rcv:37 status:200
Oct 16 14:30:57.937 - [INFO] Conn session:msrynbij conn:1 Peer Close:connect fail
Oct 16 14:30:57.937 - [DEBUG] Conn session:msrynbij conn:1 stop:peer close
Oct 16 14:30:58.606 - [DEBUG] remove conn_id:1
Oct 16 14:31:00.062 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:00.062 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'
Oct 16 14:31:00.104 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:00.104 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'
Oct 16 14:31:07.971 - [DEBUG] roundtrip time:10378 cost:10075 transfer_no:2 send_sn:2 send:195 recv_sn:0 rcv:11 status:200
Oct 16 14:31:08.278 - [DEBUG] roundtrip time:10341 cost:10047 transfer_no:3 send_sn:3 send:20 recv_sn:0 rcv:11 status:200
Oct 16 14:31:10.115 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:10.115 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'
Oct 16 14:31:10.185 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:10.185 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'
Oct 16 14:31:20.113 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:20.113 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'
Oct 16 14:31:25.186 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:25.187 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'
Oct 16 14:31:30.116 - [ERROR] any err:AttributeError("'module' object has no attribute 'inet_ntop'",)
Oct 16 14:31:30.116 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 30, in handle self.socks5_handler() File "G:\Utils\XX-Net-3.2.7\code\default\x_tunnel\local\proxy_handler.py", line 161, in socks5_handler addr = socket.inet_ntop(socket.AF_INET6, addr_pack) AttributeError: 'module' object has no attribute 'inet_ntop'

---

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2476 good:2470
network-status: OK
connected-link: new:2 used:0
worker: h1:26 h2:9
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by jzp820927** [comment]
是什么系统啊

**Comment by nascnova** [comment]
Win10，可以
把一个补丁放入lib文件夹里然后在那个报错的py文件里import了那个补丁之后没有报错了，但是还是不能使用，不返回任何东西
另，X-Tunnel可以配合Proxifier给游戏加速么？谢谢！

**Comment by jzp820927** [comment]
理论上应该可以。刚刚我本地测试了下，x_tunnel 虽然也有报错，但是可以正常使用。没有啥问题
