### ISSUE TITLE
好像不能自動更新每天的流量

### ISSUE THREAD

**Issue by hoshinokana** [XX-net/XX-Net#438]
使用自己的appid 當帳戶的流量到達上限后會把appid加入"Out of Quota appids"組 於是就一直呆在這個組裡不放出來了 必須要手動重啟xx-net才會更新流量 希望能加一個appid流量檢測功能 定時不定時都可以

**Comment by hoshinokana** [comment]
另外Out of Quota appids組的列表最好能加一個根據頁面寬度自動換行功能

**Comment by Cat7373** [comment]
实际上现在就已经有一个机制了
当所有的可用APPID都被加入无流量分组之后
会自动全部重新回到可用APPID分组重新开始使用
也就是说目前的理念是：保证有可用的APPID即可，当所有APPID都不可用的时候就重新设置为都可用。
