### ISSUE TITLE
谷歌学术文献导入Endnote出错！

### ISSUE THREAD

**Issue by kli-nlpr** [XX-net/XX-Net#4380]
用谷歌学术搜索文献，点击导入到endnote会报错。

具体操作如下图所示
![qq 20161016173741](https://cloud.githubusercontent.com/assets/13194870/19416603/41666f14-93c7-11e6-97c9-72404d0c327f.png)

出错信息如下图所示
![qq 20161016173846](https://cloud.githubusercontent.com/assets/13194870/19416609/66a4f67e-93c7-11e6-961a-c8e4ff0dc652.png)

**Comment by jzp820927** [comment]
设置直连规则试试

**Comment by kli-nlpr** [comment]
@jzp820927  谢谢，亲测可用，不过感觉好神奇。。。

**Comment by jzp820927** [comment]
这有什么好神奇的，原理和 hosts 一样，用过 hosts 的就应该明白
