### ISSUE TITLE
Bug自己的app id 下载文件经常出现32M

### ISSUE THREAD

**Issue by evilstyle** [XX-net/XX-Net#439]
当下载大数据文件的时候 文件超过32m 经常只会下载到32m 就完成了
是数据结构 头文件解析或者什么信息丢失吗？
顺带一问，今天是妹子维护issue吗？！

**Comment by evilstyle** [comment]
Url https://www.youtube.com/watch?v=BSCHeqzTgxU
我就想听听歌 我容易吗。╮(╯▽╰)╭

**Comment by renyouguo** [comment]
更新服务端即可

**Comment by evilstyle** [comment]
我现在试用的是1.4.6

**Comment by Cat7373** [comment]
对了你的服务端如果是1.13.6之前部署的 需要重新部署...

**Comment by xxnet** [comment]
youtube下载文件，请用最新版，并确认服务端重新部署过

2015-05-22 15:25 GMT+08:00 evilstyle <notifications@github.com>:
