### ISSUE TITLE
使用XX-NET,终端需要一直开着

### ISSUE THREAD

**Issue by Periclesgithub** [XX-net/XX-Net#4390]
我系统是Ubuntu 16.04LTS，今天刚装的稳定版XX-Net-3.2.6，可以上网了，效果不错。
现在我有几个问题如下，我不是很懂，请指教，麻烦了：
1.我在终端启动xx-net后，终端需要一直开着，关掉终端，XX-NET就断了。有没有办法让终端不用一直开着，xx-net还照样工作？
2.我申请了Appid，是不是127.0.0.1:8050里面，“当前工作AppID”有显示自己的Appid，就表明，现在是使用自己的Appid上网，而不是用公共Appid？
3.另外，使用Chrome+SwitchyOmega设置xx-net后，有的时候很卡，1-2分钟鼠标不能动。这种情况在SS中也存在，特别是在自动转换模式，但是没有XX-NET这么频繁和持续时间长！
我是小白，见笑了，希望得到支持！谢谢。

**Comment by jzp820927** [comment]
1. nohup python code/default/launcher/start.py &
2.对
3.查看任务管理器，CPU 和 内存情况，再根据情况处理

**Comment by Periclesgithub** [comment]
to:jzp820927 
谢谢你的回答，虽然第一个回答没看懂。
另外，为什么今天我的127.0.0.1:8085不会自动跳出来，昨天还能跳出来，今天就不跳出了，并且我在地址栏输入127.0.0.1:8085，也进不去，提示“127.0.0.1 refused to connect.”

**Comment by jzp820927** [comment]
关于第一个问题，打开终端，运行命令：nohup python code/default/launcher/start.py & ，这个时候，你关闭终端，XX 还是会继续运行的。不会跟着终端一起退出。
127.0.0.1:8085 打不开，建议查看日志，是否有报错信息。或者把日志贴出来，让别人帮你看看也行。

**Comment by Periclesgithub** [comment]
第一个问题解决了，谢谢。但是每次关机或者重启出现“System program problem detected”，不知什么原因？

**Comment by jzp820927** [comment]
“System program problem detected” 应该和 XX 无关，应该是你系统什么软件，或者设置造成的，可以 google 搜索一下“Ubuntu 16.04 System program problem detected”，看看是否有相关信息。
另外，如果你在终端运行 XXNET 了，就不用点击桌面上的图标了，不然就重复运行了，肯定是不行的。
捐赠AAPIP 是共享给大家使用的，如果你只是想自己使用，可以直接部署。
要查看 XX 的进程，看有通过终端运行命令：netstat -tlnp|grep 8087

**Comment by Periclesgithub** [comment]
非常感谢。
