### ISSUE TITLE
请问，可以登上谷歌，但是却无法登陆谷歌学术，这可能是什么问题呢？

### ISSUE THREAD

**Issue by FinalAgito** [XX-net/XX-Net#4392]
有什么比较好的解决方法吗？

**Comment by FinalAgito** [comment]
用其他浏览器点击出现了异常流量的问题，是在校园网中，会不会是有自身网络的原因？

**Comment by jzp820927** [comment]
配置直连规则

**Comment by FinalAgito** [comment]
怎么配置呢？抱歉，之前没接触过这方面的对这个不是很熟....

**Comment by FinalAgito** [comment]
我试过直接用SwitchyOmega的方式，但是好像不行...也许说的不是这种？

**Comment by jzp820927** [comment]
![image](https://cloud.githubusercontent.com/assets/5740066/19526602/79692608-9657-11e6-9baa-87b5e351bf55.png)

**Comment by FinalAgito** [comment]
Thanks~~~
