### ISSUE TITLE
【新功能建议】网络连通后就立刻“检查所有IP”

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net#4394]
建议网络连通后就让xx-net立刻“检查所有IP”

具体原因请看这里 https://groups.google.com/forum/#!topic/xx-net/hsa3b6FPo-M

@teN-XX @yeahwu

**Comment by jzp820927** [comment]
项目目前没人维护，估计要增加新功能是不太可能的了。

**Comment by samho88** [comment]
你这个是突然断网掉IP了，搜一下，我记得好象XXMINI那边有个修复链接的，你试试
https://github.com/xyuanmu/XX-Mini/commit/d3f42353f247778ff44266a53cbcecd1720b035c

**Comment by jzp820927** [comment]
现在最新版 XX 也已经修复了，断网掉 IP 的情况了

**Comment by redstoneleo** [comment]
@jzp820927 
(1) 3.2.7没这个bug吗？ 你是从哪里得知这个消息的？
（2） 项目目前没人维护，怎么了吗？xx-net不会再开发了？

**Comment by jzp820927** [comment]
(1) https://github.com/XX-net/XX-Net/commit/d6d8459b969476633397aa7fa6341b86bf406682 ，这个 commit 就是修复断网掉 IP 的，自己看。
(2) X大，也就是作者自己有私事，使用没时间开发了，至于以后会不会继续开发，不得而知，如果有人接受的话，应该就没问题了。而且目前也不是完全停止开发，偶尔Y大，也会来处理一下 bug，更新一下。

**Comment by redstoneleo** [comment]
@jzp820927  谢谢，还以为X大被请喝茶了呢

**Comment by jzp820927** [comment]
多虑了，X大是我见过目前匿名做的很好的一位。
