### ISSUE TITLE
安卓手机选择pac模式，手机GAEProxy状态页面各项值均为空白，不能正常上网

### ISSUE THREAD

**Issue by UchihaKutter** [XX-net/XX-Net#4396]
已经在manual.ini文件中设置
[listen]
ip = 0.0.0.0
[pac]
ip = 0.0.0.0
现在出现两种情况
手机在wifi下设置代理自动配置http://电脑ip;8086/proxy.pac，手机GAEProxy状态页面各项值均为空白，电脑端状态页面正常，手机不能正常上网；
手机在wifi下设置手动模式http://电脑ip:8087，手机GAEProxy状态页面各项值正常，电脑端状态页面正常，手机正常上网；
现在想通过pac模式上网，怎么办，问题出现在哪里

**Comment by jzp820927** [comment]
先用浏览器打开 http://电脑ip;8086/proxy.pac 这个地址，看看能否正常显示 PAC 文件的内容。

**Comment by UchihaKutter** [comment]
代理自动配置http://电脑ip;8086/proxy.pac下，手机浏览器打不开这个地址；
手动模式http://电脑ip:8087下，手机浏览器正常打开这个地址，并显示内容

**Comment by jzp820927** [comment]
那说明，你PAC 配置不对，如果配置正常，应该能在手机浏览器正确显示 PAC 文件的内容。

**Comment by UchihaKutter** [comment]
我在manual.ini文件中设置
[listen]
ip = 0.0.0.0
[pac]
ip = 0.0.0.0
手机wlan下选择代理自动配置http://电脑ip;8086/proxy.pac，证书已经正常导入，按理说不应该出现问题的

**Comment by jzp820927** [comment]
确认，你手机 IP，和电脑 IP，是不是在同一个网段

**Comment by UchihaKutter** [comment]
连同一个wifi，确定是同一个网段

**Comment by jzp820927** [comment]
那你这个就无法解释了，或者换个其他设备试试，比如换个手机，或者在另一台PC上测试下 PAC。或者看看日志，能不能发现什么相关信息

**Comment by shaboyi999** [comment]
me too, gae代理正常，pac打不开，安卓4.4

**Comment by jzp820927** [comment]
检查配置如果没有问题，就换设备测试

**Comment by UchihaKutter** [comment]
好的，我试试换设备
