### ISSUE TITLE
xx-net+tor问题

### ISSUE THREAD

**Issue by Periclesgithub** [XX-net/XX-Net#4397]
请问，xx-net可以作为tor前置代理吗？好像没有任何反应（进度条不动）。lantern和SS试过是可以的。
是我配置错误了吗？ 如下图：
![selection_001](https://cloud.githubusercontent.com/assets/22883361/19516946/0681d5fc-9631-11e6-9c55-0e6d6aa3fd45.png)
求解！谢谢

**Comment by yeahwu** [comment]
xx-net是http代理，不支持tor前置
Pericles <notifications@github.com>于2016年10月19日 周三19:21写道：

**Comment by Periclesgithub** [comment]
好的，谢谢。大神！谢谢你们的付出。

**Comment by jzp820927** [comment]
tor 只能用支持 connet 类型的 http 前置代理，XX 不支持。
