### ISSUE TITLE
原3.2.3，重新部署失败，这是啥情况？

### ISSUE THREAD

**Issue by hbklove8** [XX-net/XX-Net#44]
MAC10.9.5
============  Begin upload  ============
appid:...

Application: ...
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
urlopen error EOF occurred in violation of protocol (_ssl.c:581)
Retry again.

Application: ...
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
urlopen error EOF occurred in violation of protocol (_ssl.c:581)
Retry again.

Application:...
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>
urlopen error EOF occurred in violation of protocol (_ssl.c:581)
Application: ...
Host: appengine.google.com
Rolling back the update.

**Comment by shawwokou123** [comment]
应该是暂时无法使用3.2

**Comment by hbklove8** [comment]
重启后正常

**Comment by xxnet** [comment]
估计是刚启动，还没有建立稳定的链接。
解决了就好
