### ISSUE TITLE
Win10 双击xx-net或star.vbs没反应,右下角也没图标

### ISSUE THREAD

**Issue by MasterLuo** [XX-net/XX-Net#4406]
管理员身份运行start.bat才能使用
日志
Oct 20 18:18:02.275 - [INFO] server 127.0.0.1:8087 started.
Oct 20 18:18:02.276 - [INFO] server 127.0.0.1:8086 started.
Oct 20 18:18:02.312 - [INFO] module gae_proxy started
Oct 20 18:18:02.313 - [INFO] start gae_proxy time cost:1440 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Oct 20 18:18:02.653 - [INFO] use config_path:C:\Program Files (x86)\XX-Net-3.2.6\data\x_tunnel\client.json
Oct 20 18:18:02.655 - [INFO] Use proxy:127.0.0.1:8087
Oct 20 18:18:02.657 - [DEBUG] x-tunnel no account
Oct 20 18:18:02.659 - [WARNING] x-tunnel session not start
Oct 20 18:18:02.660 - [INFO] server 127.0.0.1:1080 started.
Oct 20 18:18:02.662 - [INFO] Socks5 server listen:127.0.0.1:1080.
Oct 20 18:18:02.706 - [DEBUG] get ip:217.18.145.118 t:240
Oct 20 18:18:02.753 - [INFO] module x_tunnel started
Oct 20 18:18:02.754 - [INFO] start x_tunnel time cost:434 ms
Oct 20 18:18:02.756 - [INFO] begin to start web control
Oct 20 18:18:02.757 - [INFO] server 127.0.0.1:8085 started.
Oct 20 18:18:02.759 - [INFO] launcher web control started.
Oct 20 18:18:02.759 - [DEBUG] create_ssl update ip:203.252.15.179 time:447 h2:0
Oct 20 18:18:02.762 - [DEBUG] get ip:64.15.115.87 t:364

是打开方式的问题吗？
![default](https://cloud.githubusercontent.com/assets/10327135/19555946/6fb77b74-96f1-11e6-9c4e-b24cba72610e.PNG)

如果是该怎么关联呢？

**Comment by jzp820927** [comment]
既然管理员身份运行start.bat才能使用，那就这样打开不就行了
