### ISSUE TITLE
保存可用ip的问题

### ISSUE THREAD

**Issue by tossp** [XX-net/XX-Net#441]
清空data目录下的good_ip.txt,再从页面上导入可用IP，
可生效，但并没被保存到磁盘。

**Comment by lg560852** [comment]
导入进去后，工具还得扫描一段时间，筛选可用IP，如果你导入的少，可能这个过程很快，导入的多，就很慢，等一段时间再看有没有good_ip.txt吧

**Comment by tossp** [comment]
哦，明白了

**Comment by clawneo** [comment]
踢出最慢速IP也需要大量时间。。。 囧~

**Comment by clawneo** [comment]
或者你可以直接进到文件夹把默认的3000个good_ip全删除  然后再上传你自己的  会快些
