### ISSUE TITLE
晒IP

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net#4410]
[适配南京电信](https://dou4cc.github.io/resource/chinanet-nanjing.ip.zip)（其它地方的也可试试）：共29200+；检查IP后，3000+有效，延迟低于300ms。

诚邀大家晒出自己的IP，助力中国网络自由~

**Comment by jzp820927** [comment]
牛B。

**Comment by dou4cc** [comment]
为什么有效IP降到2500了？

**Comment by thebestwayto** [comment]
支持楼主，不过晒ip容易被封，还是分享ip段好一些。

**Comment by jzp820927** [comment]
干扰吧，晚上是干扰最厉害的时候

**Comment by dou4cc** [comment]
现在有效IP只恢复到3400+。

**Comment by CHN008** [comment]
之前不是看有技术达人说IP越多延迟可能会越高嘛,要那么多IP做什么,能连上就好.

**Comment by chenTest2013** [comment]
ip不是最高3000吗？

**Comment by jzp820927** [comment]
最高IP数量，可以自己改，不过IP数量的多少，意义不大，IP质量才是最重要的

**Comment by biaoL** [comment]
ip.zip的压缩文件下载不了了

**Comment by dou4cc** [comment]
@biaoL 昨晚整理文件时不小心修改了路径，现已更新链接。

**Comment by biaoL** [comment]
多谢！！

**Comment by dou4cc** [comment]
更新了IP，见[一楼](https://github.com/XX-net/XX-Net/issues/4410#issue-184444046)。

**Comment by gagazx** [comment]
@dou4cc 请问您是如何把链接隐藏到文字里的？

**Comment by jzp820927** [comment]
可以直接写 makedown 语法

**Comment by mbcz123** [comment]
感谢！直接一步升天····

**Comment by ARCHOTZ** [comment]
楼主扫归扫，晒归晒，这样明晃晃放出来就不对了。

**Comment by citizentang** [comment]
晒毛晒，你很能吗，只有你的XX-NET能扫到，别人的扫不到？GFW的原则就是你用归用但不要传播，你公然传播就他妈封你，看把你能的，傻B一个。

**Comment by biaoL** [comment]
楼主本意也是好心的

**Comment by dou4cc** [comment]
更新了IP。

**Comment by houshengandt** [comment]
楼主本意就是装逼

**Comment by pendave** [comment]
晒出来就给封了。。。无语

**Comment by wenliyang** [comment]
楼主把顶楼链接删了，比更新有用
