### ISSUE TITLE
get方式地址过长bug

### ISSUE THREAD

**Issue by chenTest2013** [XX-net/XX-Net#4416]
**length of URL too long(greater than 2083**
诊断页：
**XX-Net Status:**

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1253 good:954
network-status: OK
connected-link: new:2 used:0
worker: h1:40 h2:7
scan-ip-thread-num: 264
ip-quality: 101
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
**日志：**
Oct 22 14:59:42.698 - [DEBUG] GAE GET https://www.google.com/recaptcha/api2/frame?c=03AHJ_Vuuo3wADPORvy2Dw00rUtnWqU6IKxbFky8YFD03EHnfd4uVdMn4zTyGTVYSvGEv48SmFS2pZGA1uenxTYW1xi_Fyw-nKNrPwYQFqeIIPz3ECdJ_oxwp0Do7Ho1CEPkT0KOoPH46rPJxlCIsfRY3oYk2lW1IDHPJE5sap_DrVzpgfnz8XuerG_NzU6kVdbLf6dwzMIj2-lvQaXkOVWpvEGMZd5cE9fgxm8F-Tjz3EYNXInSEvareFTiVnvLO3L80mAxEu2XI_Svnq8s9HsRd7bBCWYMStZwGgS09G7ArRJVbZ_RuMuZhV5uLMMEfNGgxxs8mdgErGwXF_vn1yYvcN7pxy8AES6H2-UvJ5vhDdvxLjk8rDM_JCD3Eq841s7t-C2L6A8P5TUE5Xo0HnS1Ck8kO-qGek8g&hl=zh-CN&k=6LfTsRoTAAAAACPNcZRKYGSMI0pOzn_W0H4ikKLR&v=r20161018160839&bcr=%5B369053276%2C1070854656%2C-1483471170%2C1275934586%2C1262006455%2C-995699340%2C-1497255390%5D&chr=%5B16%2C93%2C69%5D&fr=%5B%22aD6YAhpIAFNs2I2TQqpgDlrFYSSIS4ikyGa1ZgCB%22%2C%22YCYOAYxLYoO5OkHCqAAGiYzDcCwMCIE1NhFIfZAo%22%2C%22IAAIAAAAAAIAAAAAAAAAAAAAACAAAIAAAAAABAAA%22%2C%22YCQIAABIAAIAKAAAQAAACBABACCIQIYgAAAAJAAE%22%5D&bg=!FxGgETBHYHRfCON8NcNBQ1Csv6deZmwHAAAAPVcAAADanAQ2B9w372KHy_D4vfCl4IORpW8rQcfPn2wFyOsnlvnOwl-fD1m5rkcSzpKHWrMV8-4GUk_LtL4C6M-Ofn9Y14qSBa2JSGP_NDZKNz8h7_JMj1pjZSBNW6SnJZaZctiYj3UGO4-XXRfWrnR6K-eL66PYPXZU0HI8KaJr8Op0UfASj5AIYs9WqcRMC7r84O6uajCAQx1yvSnNyHw__DYWjaJaR7zSwSd4NEwSLdgiPufNnIdd2jjoCuyviRXy4p7F71q3hpUYTXgateSzRm1BneYq_KdH4dwEB1ykTfCc_RET7q8NrlECtkQHWWXqe5a5iOuJynrxpkJ06Ku4GpoSrZvpgnKsdgA6xpONKLx0G4UwzWKUKKw2Xpyft18CzkVv7Xk3AMXW5HttCUKz4EzLAdMdhRyqoNWNW4P_2KVAJErA191VgeR4eyCYRwgvqPPUZZuRGvZ27z32b9GD4u6GdPRwED9Cd6YGvE7c6kjaHydQRZb6ZJNvtamv-8z2uhh5mZIYtWSsTT97FkYPS3h1vm-x-1vSXNnffwXDOGotzPu3ZEMjV9y_OHN6JOABkkveYxHx7XWzFQYErKcmUEjyPPmMt9Msptyvd2A3EGOBWvPcYA9g6Tip0HsUiKWmJK4fM5H8hw3Vm60Toxn3l9cN4vJgTQZP_tI_xhn3l53b1_4skmVazu1KMsdHKmESBVffYjqN2O9BQKSpnZfa-DG-s6tax9Bz1tejLXGi9gL-ZmlSKLjToUn-O6PQyro5CYZCCOrfWft4A9bWvVoEmflJYNsYaXSUTDbErRYzC-U2k-3IZoM40huC764jv5_AnXdbRLPhAIyMwRJM_031hvGKePBl5GWxnVdvJv-p8Yn0QhWTxjWPJ1-8UA9Q7u6Cn_NYGGc9fVN4GnccMk2-9sJoVpxLOHPWdEiD_zPHQzLka_83RNpMoF7mhzfFlF4AiYwFBjNxRJjN4TRCFz7bCc2TNNQZPne_XtdarJ7_OgbywTnSnOiY9-v3RRPdtyUUNAO4XleZJKXZ-Hyv1hVb4l3lqykxv3ahPEFtpH09k02RlELsFI--NMd9DCc5EJV4It1QCx150d1OheTPgjj_bzACyBmIWQWQWjLqMRYAwYIde7Lw9G8gsApTHqrhDglRJu1J7RxU4kitYKAO61F5P5WyrEmSulnO1sy0DZ_XdmXQMSjs-z6JeBlCIM0kgteh9p6aO4p1cHEtaobM_TXHsDbklZXHrEMiC0A0YAa498lZqyV88OxMQTKS-Al3J8W24tM3qkrtLU_QzCPqdv667xcsbb3xb_VpSp78-h03NzFW5I8PBdIeKWGcU6SFMS8jV_08MIt3ZPKqLdVLx4w9ut6wIdwN1ZL1Z1fUnREkNENW2hLd7vMmOTX69RI-zW9eScOGaBBePV1B61o9q1FaL09-1c-yD6SFjYF2LQ

**Comment by jzp820927** [comment]
访问什么域名，会有这么长的 URL

**Comment by chenTest2013** [comment]
https://www.google.com/
谷歌的人机验证码api

**Comment by jzp820927** [comment]
配置直连了吗？如果配置直连了，应该不会出验证的

**Comment by chenTest2013** [comment]
FoxyProxy +fwlist 不知是否直连

**Comment by jzp820927** [comment]
我说的是配置 XX 的直连

**Comment by chenTest2013** [comment]
if (host.indexOf(".google.com") >= 0) return "PROXY 127.0.0.1:8087"; 是这个？貌似走的代理

**Comment by jzp820927** [comment]
![image](https://cloud.githubusercontent.com/assets/5740066/19635964/b4b1eab6-99f8-11e6-9fcc-30a67d0e29c4.png)

**Comment by chenTest2013** [comment]
这几天没做任何修改,没出现这个问题了.但如何出现断网一会,xx中的ip数量会变为0

**Comment by jzp820927** [comment]
网络恢复了，IP会自动恢复。

**Comment by chenTest2013** [comment]
好的
