### ISSUE TITLE
证书签名出错？

### ISSUE THREAD

**Issue by saya1892** [XX-net/XX-Net#442]
从1.8.3直接升级到1.14.9，firefox出现如下问题：

安全连接失败

连接 www.youtube.com 时发生错误。 对等端的证书有一个无效的签名。 （错误码： sec_error_bad_signature）

    您尝试查看的页面无法显示，因为已收到数据的可靠性无法证实。
    请联系网站的所有者，告知他们这个问题。

===========================
GoAgent状态信息

  

Property

Value

Sys Platform win32 
OS System Windows 
OS version 6.2.9200 
OS release 8 
OS detail Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0 
language zh_CN 
architecture 32bitWindowsPE 
Browser Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0) 
XX-Net Version 1.14.9 
Launcher Version 1.4.0 
GoAgent Version 3.1.49 
Python Version 2.7.9 
Proxy Listen 127.0.0.1:8087 
  
working appids saya1892|cyr52813|wadakoji-16|westnumber11|digimon10th|digimon15th 
Out of Quota appids  
Not Exist appids  
PAC URL http://127.0.0.1:8086/proxy.pac  
Google IP 3000 
connected link(帮助) 10,0 
ip-connect-interval 10 
scan ip thread num 20 
block stat(帮助)  
============================
删掉证书重新生成之后还是一样

**Comment by saya1892** [comment]
今天试用全局模式后可以用遨游打开了，想到本机上还装有GOAGENT3.2.3，不知道是不是两个证书间起了冲突，试着把两个证书都删掉按相反的顺序重新添加又可以用FF打开了

**Comment by pendave** [comment]
https://github.com/XX-net/XX-Net/issues/7580 Firefox 火狐浏览器证书失效后的更新办法！GIF动图教程
