### ISSUE TITLE
添加了直连还是跳转 ipv4.google.com

### ISSUE THREAD

**Issue by brcm** [XX-net/XX-Net#4431]
添加了直连规则，而且的确显示的 IP 也是本地的 IP。
但是有时候还是会跳出 ipv4.google.com 这个页面。
概率大概有 三分之一 吧？

有没有什么好的解决方法？

![img](http://chuantu.biz/t5/39/1477325997x707808304.jpg)

http://chuantu.biz/t5/39/1477325997x707808304.jpg

```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3903 good:144
network-status: OK
connected-link: new:3 used:0
worker: h1:19 h2:9
scan-ip-thread-num: 10
ip-quality: 116
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by jzp820927** [comment]
试试 https://www.google.com/ncr

**Comment by linhua55** [comment]
有的说是Cookie的问题， 可以试一下 清除Cookie或 使用浏览器的隐私浏览模式

    However, what I have found is that simply clearing my browser’s cookies gets this annoying search result interruption to go away, at least for a while. You can be selective in clearing specific cookies or you can delete them all – which will remove your saved settings for sites you’ve previously visited. Small price to pay in order to get your search results from Google.
    http://booleanblackbelt.com/2010/05/what-to-do-if-google-thinks-youre-not-human/

    Searching Google will only work if I turn off cookies. If not, it takes me back to the CAPTCH page.
    https://answers.yahoo.com/question/index?qid=20150526112517AAX7ZKf

**Comment by brcm** [comment]
@jzp820927 这个试过了好像没有用… 也有时候还是会弹出 ipv4 这个页面，以前这个页面会出验证码，现在直接卡在无法显示。

**Comment by brcm** [comment]
@linhua55 谢谢，我试试看

**Comment by jzp820927** [comment]
实在不行，就只能用浏览器扩展，自动重定向了。

**Comment by brcm** [comment]
试了一下清除 Cookies 还是不行，不过发现一个问题，
貌似访问 ipv4.google.com 的时候会跳到奇怪的 IP 地址。
比如会跳到 ```113.171.253.87``` 这种奇怪的 IP 地址。
貌似是同一个段里面的不知道能不能拉黑？

@jzp820927 @linhua55 感谢二位回复

抽样几条日志：
```
Oct 25 14:40:41.322 - [WARNING] IP:113.171.253.87 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Oct 25 14:40:41.863 - [WARNING] IP:113.171.252.220 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Oct 25 14:40:41.863 - [WARNING] IP:113.171.252.220 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Oct 25 14:40:45.255 - [WARNING] IP:113.171.242.159 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Oct 25 14:40:45.255 - [DEBUG] report_connect_fail:113.171.242.159
Oct 25 14:40:45.387 - [WARNING] IP:113.171.242.211 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Oct 25 14:40:45.387 - [DEBUG] report_connect_fail:113.171.242.211
Oct 25 14:40:45.522 - [WARNING] IP:113.171.242.176 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
```

**Comment by linhua55** [comment]
@brcm  重启一下xxnet

**Comment by brcm** [comment]
@linhua55 好的我试试，我刚刚又把 Ipv4.google.com 加直连了。

**Comment by jzp820927** [comment]
你日志里面的 IP 都是 gvs IP，不知道 xx 怎么识别错误，难道是 gvs 的 Ciphers 又改了。

**Comment by brcm** [comment]
@jzp820927 这个就不知道了

**Comment by linhua55** [comment]
也可以试一下这个
https://twocarlo.wordpress.com/2016/02/24/how-to-remove-google-httpsipv4-google-comsorryindexredirect/

**Comment by brcm** [comment]
@linhua55 好的我全部关了试试看，不过我也用了 #4285 提到的的插件跳转的方法
-------------
晚上重启 XXNET 后还暂时没有出现 IPV4 的跳转。
有新的情况再在这里更新，感谢两位 @jzp820927 @linhua55

**Comment by brcm** [comment]
2016年10月27日 13:14:05
问题还是依然存在，关闭全部选项和开启跳转插件后只是不会跳转到 Ipv4.google.com 但是会卡在原来的页面不动。 @jzp820927 @linhua55

**Comment by jzp820927** [comment]
是不是跳转插件规则设置有问题

**Comment by linhua55** [comment]
1. 检查规则设置是否有问题
2. 多刷新几下

**Comment by brcm** [comment]
```
{
    "createdBy": "Redirector v3.1.0",
    "createdAt": "2016-10-27T07:25:53.881Z",
    "redirects": [
        {
            "description": "Google IPv4",
            "exampleUrl": "https://ipv4.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dasdfasd&q=CGMSBNrx-4cYnvCmwAUiGQDxp4NLkOxw6O8l3lqKi5y5hnS1HsEBHQU",
            "exampleResult": "https://www.google.com/search?q=asdfasd",
            "error": null,
            "includePattern": "https://ipv4.google.com/sorry/index?continue=*&q=*",
            "excludePattern": "",
            "redirectUrl": "$1",
            "patternType": "W",
            "processMatches": "urlDecode",
            "disabled": false,
            "appliesTo": [
                "main_frame"
            ]
        }
    ]
}
```
应该不会吧？这是我的配置不知道有没有配置错误。
配置好了不会出现 ipv4.google.com 这个页面了，但是会卡在原来的地方不动。
按照插件逻辑应该不会出现这个问题呀

有劳 @jzp820927 @linhua55  麻烦检查一下配置，感谢！

**Comment by jzp820927** [comment]
规则好像没啥问题。

**Comment by brcm** [comment]
@jzp820927 我也觉得好奇怪，实在不行就把谷歌单独列出来用反代吧。反正其他都还没问题包括 U2B

**Comment by jzp820927** [comment]
你是哪个域名有问题，www.google.com？还是 www.google.com.hk？

**Comment by linhua55** [comment]
你真实的`example url`是什么？

            "exampleUrl": "https://ipv4.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dasdfasd&q=CGMSBNrx-4cYnvCmwAUiGQDxp4NLkOxw6O8l3lqKi5y5hnS1HsEBHQU",

这个，是我修改的Chrome的默认的搜索引擎填的

默认搜索设置

    google     google.com     https://www.google.com/search?q=%s

**Comment by brcm** [comment]
@jzp820927 @linhua55 抱歉昨晚没上 Github。
我的 URL 是  www.google.com.hk 。也就是 Example URI 必须和真实地址完全匹配？

**Comment by jzp820927** [comment]
规则是根据真实地址写的。

**Comment by linhua55** [comment]
@brcm
`真实地址`就是要求你输入验证码的那个地址，就是以`https://ipv4.google.com`开头的那个

**Comment by brcm** [comment]
@linhua55 @jzp820927 明白了，谢谢二位指导。
先试试看行不行，现在在用 www.google.com
```
{
    "createdBy": "Redirector v3.1.0",
    "createdAt": "2016-10-28T12:46:46.597Z",
    "redirects": [
        {
            "description": "Google IPv4",
            "exampleUrl": "https://ipv4.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%25D0%2593%25D0%2591%26oq%3D%25D0%2593%25D0%2591%26aqs%3Dchrome..69i57%26sourceid%3Dchrome%26ie%3DUTF-8&q=CGMSBDoURC0Y5J2zwAUiGQDxp4NLhCSEPobUCNJ8Y_7KuBusI89CrZk",
            "exampleResult": "https://www.google.com/search?q=%D0%93%D0%91&oq=%D0%93%D0%91&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8&q=CGMSBDoURC0Y5J2zwAUiGQDxp4NLhCSEPobUCNJ8Y_7KuBusI89CrZk",
            "error": null,
            "includePattern": "https://ipv4.google.com/sorry/index?continue=*",
            "excludePattern": "",
            "redirectUrl": "$1",
            "patternType": "W",
            "processMatches": "urlDecode",
            "disabled": false,
            "appliesTo": [
                "main_frame"
            ]
        }
    ]
}
```

**Comment by brcm** [comment]
@linhua55 @jzp820927 插件没有问题了，不过经常卡在这样的地址（开发者工具→网络）中看到的。
www.google.com/gen_204 然后这个时候就会出现大量的这种错误 
Oct 29 09:19:14.049 - [WARNING] IP:113.171.243.115 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
过一会儿就好了，估计是 IP 不干净，我试试重新扫描一遍看看，应该可以解决。

感谢二位帮助打扰了。

**Comment by jzp820927** [comment]
我怀疑是不是 113.171. 段的 IP 对 GAE 支持有可以，可以尝试从 ip 数据库里面删除 113.171. 段的 IP 再试试

**Comment by brcm** [comment]
@jzp820927 我发现是最近 IP 好像不稳定速度也有点慢了，嗯我试试。

**Comment by jzp820927** [comment]
尽量找稳定的IP，才能保证速度稳定。

**Comment by brcm** [comment]
@jzp820927 好的
