### ISSUE TITLE
IP延迟突然变得很大

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#4437]
mac装的双系统， 之前在Mac系统下ip延迟只有60左右，突然最近变的很慢，这两天超过200了， 在windows系统下一直就是120左右，没有快也没变慢，是哪个配置出现问题了吗，还是什么本地缓存文件导致

**Comment by andylee1890** [comment]
已经在两边都重新扫描过ip

**Comment by andylee1890** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-16.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
os-release: 16.0.0
os-detail: Release:10.12; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:2378 good:2318
network-status: OK
connected-link: new:4 used:0
worker: h1:20 h2:2
scan-ip-thread-num: 200
ip-quality: 919
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
![13](https://cloud.githubusercontent.com/assets/11325411/19710347/4f814268-9b60-11e6-9fc8-08fce611fa61.jpg)
![qq 20161026094046](https://cloud.githubusercontent.com/assets/11325411/19710355/559ac494-9b60-11e6-88e3-cf07937ba794.jpg)

**Comment by jzp820927** [comment]
有可能是 mac 自身的问题

**Comment by andylee1890** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-16.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
os-release: 16.0.0
os-detail: Release:10.12; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:1291 good:1282
network-status: OK
connected-link: new:2 used:0
worker: h1:23 h2:1
scan-ip-thread-num: 100
ip-quality: 74
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by andylee1890** [comment]
重新下了一个包，速度有上来了

**Comment by jzp820927** [comment]
还是 IP 问题。

**Comment by andylee1890** [comment]
ip之前清过的，不行，然后我下了个新版本的，五百多ip的时候延迟就在100以内了。应该是本地某些缓存引起的，最近一两个月正在熟悉python，工作之余看看xxnet的源代码，研究研究

**Comment by jzp820927** [comment]
好吧，以后 xxnet 的开发接力就靠你了。
