### ISSUE TITLE
验证一下是不是现在大部分手机都支持应用代理。LG G5亲测可用

### ISSUE THREAD

**Issue by lineex** [XX-net/XX-Net#4443]
10月 27 03:32:12.4 - [DEBUG] GAE POST https://reports.crashlytics.com/spi/v1**/platforms/android/apps/com.qianyan.eudi**c/reports
10月 27 03:32:12.9 - [INFO] GAE t:436 s:0 POST https://reports.crashlytics.com/spi/v1/platforms/android/apps/com.qianyan.eudic/reports h2_get_head:433
10月 27 03:32:13.3 - [DEBUG] GAEProxy Web_control 127.0.0.1:50692 GET /check_ip?cmd=get_process
10月 27 03:32:14.3 - [INFO] RangeFetch client closed([Errno 104] 连接被对方重设). http://static.frdic.com/e**xtra_eudb/Medical_Dictionary_with_Detailed_Explanations_(Chinese).eudic**
10月 27 03:32:14.3 - [DEBUG] GAEProxy Web_control 127.0.0.1:50692 GET /check_ip?cmd=get_process
10月 27 03:32:14.6 - [DEBUG] GAE GET https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.qianyan.eudic/settings?icon_hash=ba2baec0905843e06c8b6c3b7fe1db3fbf546458&display_version=5.3.5&source=4&instance=260f2c1b3151110f2e8337143026cb21d9839d4f&build_version=129
10月 27 03:32:15.0 - [INFO] GAE t:405 s:644 GET https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.qianyan.eudic/settings?icon_hash=ba2baec0905843e06c8b6c3b7fe1db3fbf546458&display_version=5.3.5&source=4&instance=260f2c1b3151110f2e8337143026cb21d9839d4f&build_version=129 h2_get_head:402
10月 27 03:32:17.8 - [DEBUG] create_ssl update ip:59.18.35.145 time:107 h2:0
10月 27 03:32:17.8 - [DEBUG] get ip:106.103.1.164 t:102
10月 27 03:32:18.0 - [DEBUG] create_ssl update ip:106.103.1.164 time:103 h2:0
10月 27 03:32:26.4 - [DEBUG] GAEProxy Web_control 127.0.0.1:50692 GET /check_ip?
10月 27 03:32:33.1 - [DEBUG] GAE GET http://lh3.ggpht.com/tBka6Uf-iBt75hd7vBNdVR--5yRjb6p5N8iAtasbEXDDqY3xQ4SJlAaA3p0QvxL1xI27RMbCmhgl9HD_gW8=rw-w110-h110-v1
10月 27 03:32:33.4 - [DEBUG] GAEProxy Web_control 127.0.0.1:50692 GET /check_ip?cmd=get_process
10月 27 03:32:33.4 - [INFO] GAE t:308 s:1040 GET http:/**/lh3.ggpht.com**/tBka6Uf-iBt75hd7vBNdVR--5yRjb6p5N8iAtasbEXDDqY3xQ4SJlAaA3p0QvxL1xI27RMbCmhgl9HD_gW8=rw-w110-h110-v1 h2_get_head:306
10月 27 03:32:34.2 - [DEBUG] GAE GET http://lh3.googleusercontent.com/6bQ-POCi4D-6-WOvNAlR1VacMY0UhzRUjAzKNUnoyX_05dCCr3b76WV4F_i1_lPfo5s=rw-w154-h154-v1
10月 27 03:32:34.3 - [DEBUG] GAE GET http://lh3.ggpht.com/yrkQ_bDsgS0eFn

**Comment by jzp820927** [comment]
应用代理？你指的是 apps 走代理？

**Comment by panghu1986** [comment]
求指导，手机如何走电脑上面的代理模式，在同一个网络内。

**Comment by jzp820927** [comment]
PAC

**Comment by lineex** [comment]
@jzp820927 app能够走代理了
如10月 27 17:50:46.6 - [INFO] GAE t:664 s:17506 POST https://mobile.facebook.com/stories.php?aftercursor=MTQ3NzU2MTgxMjoxNDc3NTYxODEyOjk6MTY1NTY3NTM2MjI1Njc5MTM0ODoxNDc3NTU1MjAxOjYzNDYwNzk3MjUyODg0NzE1NzE%3D&tab=h_chr&__m_log_async__=1 h1_get_head:573,h1_finish[SP:207401]:88

**Comment by jzp820927** [comment]
有部分 app 是能够走代理，但是也有部分不行。

**Comment by lineex** [comment]
@jzp820927 比如哪一些，我试一试

**Comment by jzp820927** [comment]
twitter
