### ISSUE TITLE
校园网ipv6无法启用（启用IPv6失败，请确认你的网络支持IPv6）

### ISSUE THREAD

**Issue by zhixin12** [XX-net/XX-Net#4446]
已解决：断网状态下可以启用，之后再连接校园网就可以了
校园网，测试ipv6是可以的，用hosts也能上谷歌，之前用的2.9.2版本可以开启，今天换了最新版之后发现ipv6无法启用，之前的版本也不行了。
配置界面提示：启用IPv6失败，请确认你的网络支持IPv6。
日志：Oct 27 12:17:42.202 - [WARNING] IPv6 was enabled, but check failed.

**Comment by CrazyRundong** [comment]
我也遇到了这个问题... 楼主怎么解决的？

**Comment by jzp820927** [comment]
LS不是解决了吗

**Comment by zhixin12** [comment]
回CrazyRundong，我的解决方法已经说明了呀。不过我遇到的问题是配置中打开ipv6时无法保存。因为我们的校园网是拨VPN，所以我的问题解决方法就是开机后先在配置中打开ipv6然后保存，之后再拨vpn即可。如果你遇到和我一样的问题，我猜或许你可先把ipv4禁掉，开启ipv6之后再启用

**Comment by jzp820927** [comment]
校园网的联网方式真是千奇百怪。
