### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#4449]
版本3.2.7 
状态页始终显示“请检查浏览器代理设置。”
同时也显示  CA证书状态(下载)	Fail

不妨碍使用，但感觉不爽。

重启、删了重新安装xx-net，都试过，没有用。

请教这个问题怎么解决？感谢！

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:50 good:46
network-status: OK
connected-link: new:1 used:0
worker: h1:31 h2:8
scan-ip-thread-num: 50
ip-quality: 249
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
可能是证书问题吧，可以把导入系统的证书，和data目录都删掉，重新运行，重新导入证书

**Comment by zhencaihao** [comment]
你可以参考一下 https://github.com/XX-net/XX-Net/issues/4389

**Comment by farshidvahid** [comment]
全部删除，然后win+r删除根证书，然后重启，重装，再翻墙打开一个网页，可以了。感谢！
