### ISSUE TITLE
是否可以考慮允許局域網內其他設備共享PAC設置

### ISSUE THREAD

**Issue by gam2046** [XX-net/XX-Net#446]
在我的環境裏，我希望通過共享，讓我的ipad等移動設備也可以使用XX-Net暢通無阻的訪問網路。
但是經過我的嘗試，發現無法訪問PAC。（WIN7系統）
我嘗試在命令提示符下輸入netstat -an -p TCP，結果讓我有點失望。
有的兩條記錄：
  协议  本地地址          外部地址        状态
  TCP    127.0.0.1:8085         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:8086         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:8087         0.0.0.0:0              LISTENING

很顯然，他只接受來自本地連接的請求，而我其他的局域網的設備來訪地址因為不為127.1，因此就無法享受XX-Net的便利了。
經確認，不是系統防火牆緣故，嘗試關閉防火牆依舊只能使用http://127.0.0.1:8086/proxy.pac 方法，而設置為http://192.168.1.106:8086/proxy.pac 則無法正常獲取。(192.*.*.*系我的內網IP地址)
希望你們在下一個版本中，可以考慮加入這個功能，感恩！

**Comment by xxnet** [comment]
现在修改监听的绑定ip就可以了，但是导入证书依然是个麻烦
