### ISSUE TITLE
建议加一个终端关闭或停用的功能

### ISSUE THREAD

**Issue by noveleven** [XX-net/XX-Net#4463]
有些软件和OSX的顶部Toolbar冲突，导致点击上面的图标无效（i.e. vpn xx-net 等等），由于需要关闭代理，这时候只有杀python进程才能退出。

**Comment by linhua55** [comment]
在web界面 的右上角 有`退出程序`按钮

**Comment by noveleven** [comment]
@linhua55 看见了，刚才进127的时候光注意左边菜单了。。。
