### ISSUE TITLE
不能用XX-Net提供的http代理连接SSH与shadowsocks。

### ISSUE THREAD

**Issue by TooYoungTooSimp** [XX-net/XX-Net#4464]
已确认是最新版本
XX-Net本体无故障
issue已查找
---
## 问题内容

不能用XX-Net提供的http代理连接SSH与shadowsocks。
SSH：将putty的http代理设为127.0.0.1:8087时出现错误："Server unexpectedly closed network connection"，但是设置为shadowsocks提供的http代理127.0.0.1:8123时就正常工作
[Shadowssocks：](https://github.com/shadowsocks/shadowsocks-windows/issues/843)
## 日志

Oct 30 20:49:44.938 - [INFO] ssl error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590), create full domain cert for host:xxx.xxx.xxx.xxx
那段xxx是服务器地址

**Comment by SeaHOH** [comment]
GAE 不支持，用 x-tunnel 来链接。
不过这种一般是直接用或者戴在 xx-net 前面，你这种用法无意义。

**Comment by TooYoungTooSimp** [comment]
感谢回答，但是考虑到xtunnel代码不公开不能自行部署到个人服务器上，只能试图这样做。
不过相对应的另一个issue里面已经有人指出了问题：

> XX-Net提供的http代理不能支持connect方法，所以是不能连接的

我想这可以算是一个功能缺陷，希望能够实现这个功能

**Comment by SeaHOH** [comment]
>XX-Net提供的http代理不能支持connect方法，所以是不能连接的

这句话指的就是 GAE 代理，XX-Net 本身是可以实现你所说的功能，但是这跟你直接使用是完全没有区别的。前面已经说了，你可以戴在 XX-Net 前面使用。

**Comment by TooYoungTooSimp** [comment]
感谢回答，但是我对您的解释还是有一些不清楚的地方：什么叫
> 但是这跟你直接使用是完全没有区别的
与
> 可以戴在 XX-Net 前面使用
我想的是这样一种状况，首先我的所在地区连接vps不能满速，但是gae可以跑满，不过gae有一个问题，就是ip飘忽不定并且使用google时总是提示要输入验证码或直接不让搜索，我想让gae作为shadowsocks的前置代理，以达到用 gae 中转流量来抵抗 IP 定点封锁，加大带宽和不被谷歌屏蔽的目的。（并且什么叫做戴在 XX-Net 前面使用？gae作为ss的代理还是ss作为gae的代理？）

**Comment by TooYoungTooSimp** [comment]
感谢回答，但是我还有两个地方不是很明白：
> 这跟你直接使用是完全没有区别的
> 可以戴在 XX-Net 前面使用

为什么说“跟你直接使用是完全没有区别的”？“可以戴在 XX-Net 前面使用”是什么意思？是用ss代理gae的流量还是其他什么的？

我现在的状况是shadowsocks不能跑满，但是gae可以；不过gae有个问题就是ip飘忽不定，并且访问谷歌时总是要输入验证码。我的想法是把gae作为shadowsocks的前置代理，通过gae中转流量，以达到抵抗 IP 定点封锁同时加快传输速度并且不被谷歌封的目的。

**Comment by SeaHOH** [comment]
先说结果吧，实际上这算第二次了，只能 SSH 和 shadowsocks 代理 GAE，反过来就不行。
看来你对这些了解太少，就不要想靠我在这里三言两语你就搞懂了。
google 是个好东西，不懂都问它。你关注一下网络代理的基本原理和种类，以及 GAE 的限制，然后你就明白了。
记住：既然是免费的东西，就不可能完美。

**Comment by TooYoungTooSimp** [comment]
好的，我已经了解了一部分，不过x_tunnel的服务端是如何工作的呢？是不是只要把tcp流包装成http就可以代理了？

**Comment by jzp820927** [comment]
你的需要，就是要同 gae 中转其他代理的流量。这个原理挺简单的，如果自己会写代码，应该可以自己写个服务端实现，就是把任意流量包装成标准的 http 1.1 流量，因为 gae 只能代理 http 1.1.

**Comment by TooYoungTooSimp** [comment]
感谢各位的回复，看看我考完联赛后有没有时间去胡搞一个服务端了
