### ISSUE TITLE
求助！部署成功了为什么还是用不了？

### ISSUE THREAD

**Issue by bbqwwb** [XX-net/XX-Net#447]
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36
XX-Net Version	1.14.9
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids*****************省略**********************
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	3000
connected link(帮助)	10,1
ip-connect-interval	10
scan ip thread num	20
block stat(帮助)	OK

May 24 21:33:34 - [DEBUG] get ip:58.145.238.57 t:764
May 24 21:33:34 - [DEBUG] create_ssl 64.233.184.17 fail:timed out cost:4000 h:0
May 24 21:33:35 - [DEBUG] get ip:202.86.162.44 t:764
May 24 21:33:35 - [DEBUG] create_ssl 111.168.255.157 fail:timed out cost:4000 h:0
May 24 21:33:35 - [DEBUG] get ip:106.162.216.39 t:765
May 24 21:33:35 - [DEBUG] get ip:64.233.184.194 t:765
May 24 21:33:35 - [DEBUG] create_ssl 64.233.179.148 fail:timed out cost:4002 h:0
May 24 21:33:35 - [DEBUG] create_ssl 64.233.168.141 fail:timed out cost:4002 h:0
May 24 21:33:35 - [DEBUG] get ip:197.199.254.31 t:765
May 24 21:33:36 - [DEBUG] create_ssl 203.117.35.183 fail:timed out cost:4000 h:0
May 24 21:33:36 - [DEBUG] create_ssl 149.3.177.88 fail:timed out cost:4006 h:0
May 24 21:33:36 - [DEBUG] get ip:106.162.192.168 t:765
May 24 21:33:36 - [DEBUG] get ip:93.183.211.245 t:765
May 24 21:33:36 - [DEBUG] get ip:194.78.99.46 t:765
May 24 21:33:37 - [DEBUG] get ip:118.174.25.45 t:765
May 24 21:33:37 - [DEBUG] get ip:58.145.238.42 t:765
May 24 21:33:38 - [DEBUG] create_ssl 58.145.238.57 fail:timed out cost:4006 h:0
May 24 21:33:39 - [DEBUG] create_ssl 202.86.162.44 fail:timed out cost:4006 h:0
May 24 21:33:39 - [DEBUG] create_ssl 106.162.216.39 fail:timed out cost:4000 h:0
May 24 21:33:39 - [DEBUG] create_ssl 64.233.184.194 fail:timed out cost:4004 h:0
May 24 21:33:39 - [DEBUG] get ip:218.176.242.35 t:765
May 24 21:33:39 - [DEBUG] create_ssl 197.199.254.31 fail:timed out cost:4000 h:0
May 24 21:33:40 - [DEBUG] get ip:216.58.196.20 t:765
May 24 21:33:40 - [DEBUG] create_ssl 106.162.192.168 fail:timed out cost:4006 h:0
May 24 21:33:40 - [DEBUG] get ip:212.188.7.98 t:765
May 24 21:33:40 - [DEBUG] get ip:203.211.0.25 t:765
May 24 21:33:40 - [DEBUG] create_ssl 93.183.211.245 fail:timed out cost:4000 h:0
May 24 21:33:40 - [DEBUG] create_ssl 194.78.99.46 fail:timed out cost:4000 h:0
May 24 21:33:40 - [DEBUG] get ip:64.15.113.185 t:765
May 24 21:33:41 - [DEBUG] create_ssl 118.174.25.45 fail:timed out cost:4000 h:0
May 24 21:33:41 - [DEBUG] create_ssl 58.145.238.42 fail:timed out cost:4000 h:0
May 24 21:33:41 - [DEBUG] sort ip time:3
May 24 21:33:41 - [DEBUG] get ip:118.143.88.89 t:767
May 24 21:33:41 - [DEBUG] get ip:193.134.255.242 t:767
May 24 21:33:41 - [DEBUG] get ip:197.199.253.59 t:767

**Comment by slyypp** [comment]
靠，我和你的症状一样。

**Comment by bbqwwb** [comment]
我是一台win7的机子使用没问题 另外一台win8的就用不了 不清楚什么原因

**Comment by xxnet** [comment]
浏览器没有设置代理
