### ISSUE TITLE
Google, facebook等无法连接

### ISSUE THREAD

**Issue by yuzhounh** [XX-net/XX-Net#4472]
之前已经稳定使用了数月，但今天下午好像无法访问被屏蔽网站了。

连接池(帮助)	0 / 49

GAEProxy状态信息 提示是已经成功翻墙的。这是什么原因呢？

**Comment by jzp820927** [comment]
删除 data ，重新扫描。如果有需要，可以先备份证书

**Comment by yuzhounh** [comment]
哦，是我的浏览器没有启动SwitchyOmega这个插件，启动就好了。
