### ISSUE TITLE
安卓版的xxnet

### ISSUE THREAD

**Issue by c0001** [XX-net/XX-Net#4480]
安卓版的xxnet什么时候出

**Comment by jzp820927** [comment]
应该不会出

**Comment by CHN008** [comment]
XX-Net-3.0-debug.apk - https://github.com/XX-net/xxnet-android/releases/download/3.0.0/XX-Net-3.0-debug.apk

**Comment by jzp820927** [comment]
这个是 N 久前的版本了，问题很多。可以玩玩，不过不适合长期使用。
另外说明一下，只能用于 android 4 及以下的系统，4以上的基本上闪退。

**Comment by Sisyphy** [comment]
只能借助其它vpn类的。。。或者开启局域网共享，小范围使用。。。

**Comment by jzp820927** [comment]
最方便的方法还是局域网共享 PAC

**Comment by whhxmwhh** [comment]
最近速度慢的如同蜗牛

**Comment by jzp820927** [comment]
IP 不好了，速度自然就慢了

**Comment by chumuye** [comment]
X大为何归隐，XX-NET项目还有人维护吗？

**Comment by jzp820927** [comment]
Y 大偶尔小修小补，维护一下。

**Comment by chumuye** [comment]
那好可惜啊~

**Comment by jzp820927** [comment]
没办法的事情，每个人都有忙其他事情的时候

**Comment by c0001** [comment]
现在呢  各位 有没有出现安卓版本的xx-net
