### ISSUE TITLE
高手大神帮帮我。。。

### ISSUE THREAD

**Issue by adaaaaaa** [XX-net/XX-Net#4487]
XXnet打开出现了这个，为啥感觉不像是报错，但是运行又失败
![xx](https://cloud.githubusercontent.com/assets/23206387/19917561/3516ccc8-a0ff-11e6-8868-feafe186dd08.png)
了？要怎么办？

**Comment by jzp820927** [comment]
应该是  python  你的路径/code/default/launcher/start.py

**Comment by adaaaaaa** [comment]
呵呵。。。奇葩了。。。3.2.7启动一大堆报错，3.2.8可以运行。。。
swichyomega应该怎么设置？我这个XX是在路由器上的。。。

**Comment by jzp820927** [comment]
设置路由器 IP 和端口就可以了

**Comment by adaaaaaa** [comment]
就是192.168.99.1，代理端口是8087这样？
不行哦。。。

**Comment by adaaaaaa** [comment]
直连，还是http，还是其他？

**Comment by jzp820927** [comment]
代理类型是 http 代理

**Comment by adaaaaaa** [comment]
![qq 20161102162727](https://cloud.githubusercontent.com/assets/23206387/19921537/495c931a-a119-11e6-8270-fe067cf237f9.png)
这是不是因为我修改了proxy文件才这样的？

**Comment by jzp820927** [comment]
你修改了什么文件？看提示，应该是你把文件的格式改混乱了。

**Comment by adaaaaaa** [comment]
XX-Net-3.2.8\code\default\gae_proxy\local\proxy.ini
格式没有变化啊。。。还是这个。。。

**Comment by jzp820927** [comment]
你都改了什么内容？用什么方法改的

**Comment by adaaaaaa** [comment]
神经。。。我就改了几个数字，然后还原了还是不行。。。
后来在压缩包里覆盖了解压原文件那个之后就可以了。。。

**Comment by adaaaaaa** [comment]
直接记事本打开。。。要用vim命令改？？

**Comment by adaaaaaa** [comment]
打开油管网页显示这样：您的系统已配置为使用代理，但UC浏览器无法连接到此代理。
代理协议：http     代理服务器：192.168.99.1   代理端口：8087，8086，8085，8888都试过
打不开油管。。。

**Comment by jzp820927** [comment]
记事本改要破坏格式，用 vim 改

**Comment by adaaaaaa** [comment]
那我离科学上网还差什么？路由上要怎么改，电脑端呢？

**Comment by jzp820927** [comment]
ssh 到路由器上，vim 改监听地址，把所有的127.0.0.1改成0.0.0.0，然后 电脑上设置代理ip为路由器IP，端口为 8087

**Comment by adaaaaaa** [comment]
那么多公共ID需要全部删除掉吗？我有自己的ID

**Comment by jzp820927** [comment]
或者你可以改 data/gae_proxy/manual.ini 这个文件，改 XX-Net-3.2.8\code\default\gae_proxy\local\proxy.ini 不是太方便

**Comment by adaaaaaa** [comment]
木有这个文件，手动创建一个可以的吧？

**Comment by adaaaaaa** [comment]
![default](https://cloud.githubusercontent.com/assets/23206387/19923487/966e3c18-a122-11e6-85db-d1aeb302ebad.png)
油管这是怎么了？要导入证书吗？从哪里？

**Comment by adaaaaaa** [comment]
路由器上启动的XXnet

你的解决方案：删除 data/gae_proxy/ 下面的 CA.crt 文件和 certs/ 目录，删除导入浏览器的证书。然后重新运行 XXNET，重新导入证书。

我现在电脑也装了XXnet，可以用电脑上XX目录里的证书替换路由的吗？

**Comment by adaaaaaa** [comment]
我就是这样做的。。。谢咯，大神！^_^

**Comment by jzp820927** [comment]
manual.ini 这个文件，这个文件本来就是要手动创建的，你的证书没导入吧

**Comment by SeaHOH** [comment]
公共 appid 不用删除，而且你自己的不要填在那里。
>public_appid = 公共……
appid = 自己的

由于同一程序生成的证书名是相同的，所以你要同时使用多个 XX-Net 证书也必须相同，也就是你现在做的：把其中一个生成的证书复制到其它 XX-Net 使用。

**Comment by adaaaaaa** [comment]
@SeaHOH 自己的ID填哪里？manual.ini里？这个配置文件有教程吗？

**Comment by SeaHOH** [comment]
``manual.ini`` 就行，这里的设置会覆盖默认设置。
点当前网页的 Wiki，自己看**手动设置GoAgent配置文件**。

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
真是服了，都不看 wiki 的吗

**Comment by adaaaaaa** [comment]
谢楼上两位大神，第一次看wiki。。。哈哈。。。
