### ISSUE TITLE
扫描IP设置timeout

### ISSUE THREAD

**Issue by tossp** [XX-net/XX-Net#449]
扫描IP设置能不能自定义超时限制，以保证IP的质量？

**Comment by xxnet** [comment]
考虑过，最后觉得不必要：

最终最好的ip会优先使用。
没有好的，差的也能凑合着用。



在 2015年5月25日 上午8:18，TossPig <notifications@github.com>写道：

**Comment by tossp** [comment]
比较过实际效果，
使用原版3000个IP,在24小时不关机扫描后
明显没有，把3000在GoGo Tester里面，设置线程5，超时400，测试3，用最后过滤出来的30多个IP的速度快。


ps:这种测试我做过两次。

**Comment by xxnet** [comment]
测试3，是什么意思？
超时400，是400毫秒吗？

如果懂点编程，你可以试试改check_ip，把参数调整成GoGoTester 的样子试试


在 2015年5月25日 上午9:07，TossPig <notifications@github.com>写道：

**Comment by tossp** [comment]
测试3是GoGoTester有个测试次数的输入框，我输入的3。
你的意思是只能手动修改max_timeout？
升级怎么办呢？

**Comment by xxnet** [comment]
先手动改，试试效果

如果有必要，可以提交补丁，或者增加手动微调细节的配置项，设置界面UI。

在 2015年5月25日 下午3:04，TossPig <notifications@github.com>写道：

**Comment by simonasd** [comment]
@tossp 一个比较有趣的情况，我朋友的反馈，GOGO测试出来的IP延时都在2000以上，但是测速可达2000KB/S，YouTube上1080P无压力。他说按照GOGO的数据，延时和速度之间的关系统计不显著。

**Comment by xxnet** [comment]
第一次连接ip，延迟是会很高，这跟第一次建立路由的耗时有关系，后面再使用，就不会延迟很高了。
一个RTT很高的ip，不可能真的很快的。

所以，你的朋友说的情况，估计是延迟2000指第一次连接的耗时。

在 2015年5月28日 下午9:13，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 恩，他说的延时是GoGoTester中显示的数值，应该与上面那位朋友说的是一样的吧？这方面并不是太懂。

**Comment by linhua55** [comment]
@simonasd  是的，延时主要决定打开网页的快慢。如果是看视频的话，则主要与用户占用服务器带宽有关。因为视频是提前缓冲的，虽然从每一次发出请求到收到数据之间的时间长点，但如果请求的频繁一点，单位时间内得到的数据量还是差不多的。

**Comment by xxnet** [comment]
Youtube视频默认采用HTML5 + js，会把每次请求的块控制得很小，1M左右，导致并发多链接下载的效果大打折扣。
最终还是要靠低RTT的ip，才能提升视频的下载速度。

在 2015年5月28日 下午9:28，linhua55 <notifications@github.com>写道：
