### ISSUE TITLE
一些猜测

### ISSUE THREAD

**Issue by dou4cc** [XX-net/XX-Net#4498]
我从9月中旬开始挂机搜了半个月IP，分享在[#4410](https://github.com/XX-net/XX-Net/issues/4410)，立即引来GFW把IP封到只剩3000+，可见事实并非[GFW没有足够经费封尽IP](https://github.com/XX-net/XX-Net/issues/4474#issuecomment-257761942)：GFW完全能封尽IP，但为了某种原因把GAE控制得可用却不爽，解释了为什么GAE总在像巴拿马这样的关键时刻失效。最近其它翻墙软件相继失效，GAE成为唯一免费翻墙途径让我起疑。考虑到GAE作为中间人能拿到明文，google会不会已和GFW交易？

**Comment by jzp820927** [comment]
可能性为0，不然 google 就不会退出中国市场，而是和（被过滤）合作的不亦乐乎了。

**Comment by guanyueqi** [comment]
所以你就是手贱

**Comment by FinalAgito** [comment]
GFW的加强是肯定的，在现在的政治和网络大环境情况下,个人认为交易不可能。而且既然曝光IP可能导致封尽和被针对，个人觉得还是少发出来比较好，既然有这种可能的话。

**Comment by SeaHOH** [comment]
墙的建成和现在免费的翻墙资源都是政治及意识形态斗争的过程。
交易什么的，不是这么简单，你想交就能交。

**Comment by simonasd** [comment]
记得前段时间 chengr28 在推特上表示，据他观察，近期国际出口对443端口通讯的人为丢包很严重。

如果这是普遍存在的现象，则对XX-Net的影响会比较大。

**Comment by jzp820927** [comment]
都影响一个月了，你现在才发现。

**Comment by distance00** [comment]
可能各地情况不一样吧，我这里也是最近几天才明显感觉到，估计是预热了一个月，现在全线发威。不知道会不会成为常态。

**Comment by jzp820927** [comment]
让丢包来的更猛烈些吧

**Comment by tianzhihao** [comment]
ip被封了好意思说，google和政府合作，你动脑子不？

**Comment by qiuhaotc** [comment]
现在只能算勉强用了

**Comment by guanyueqi** [comment]
IP数量37，IP延迟440，版本3.2.7，还能用么

**Comment by guanyueqi** [comment]
GG了

**Comment by jzp820927** [comment]
只要有IP就能用吧，只是速度快慢的问题

**Comment by guanyueqi** [comment]
更新到3.2.8测试版会不会好一点？

**Comment by jzp820927** [comment]
和版本没关系，上面楼层已经有人说了，近段时间，国际流量丢包很厉害，导致对 XX 的影响分成大。这个是 GFW 造成的结果，暂时没有解决办法，只能观望。

**Comment by guanyueqi** [comment]
记得之前有一段也是IP特别惨，基本处于瘫痪状态，后来就好了，这次还能挺过去么？

**Comment by jzp820927** [comment]
只有时间能回答这个问题。

**Comment by roc1010kmt** [comment]
沒有黑客去攻擊下gfw嗎?

**Comment by jzp820927** [comment]
有可能麽

**Comment by zhencaihao** [comment]
要么是打算未来的日子都在牢里过，不然哪位黑客敢去黑“防火墙”。

**Comment by Famingwu** [comment]
还猜测什么啊，现在IP可用性这么低，还不是有些人把IP公开在网络上发布造成的结果，不相信Google就别使用人家的技术翻墙，早在13 14年就说不要公开分享IP，那么多用户受到影响，仅仅是丢包的问题吗，做一些雪上加霜的事情还不知反思

**Comment by jzp820927** [comment]
看这次要持续多久

**Comment by mooredam** [comment]
估计某位是反串角色，打入敌人内部不是某朝光荣传统么

**Comment by simonasd** [comment]
主动攻击GFW的想法不是没有过，已经有人挖出了一些核心的服务器。如果能调动足够的资源，也许能给他们带来一些麻烦。但考虑到对手“近乎无限的资源”，简单的DDOS似乎意义并不大？

IP数量的话，好像还是跟ISP有关。有的人只能维持在20多个，但有的人能保持在一千多。可惜上千IP的人浏览速度也大不如前。有评论说，离物理断网又近了一步。

**Comment by SeaHOH** [comment]
为什么要攻击，别搞大新闻啊。

**Comment by jzp820927** [comment]
掉包的策略，真是无解了。

**Comment by popjimmy** [comment]
希望把所以商业网站也滤掉，把互联网变成局域网得了，哈哈哈。。。。。

**Comment by Limsig** [comment]
@dou4cc 请问该用什么工具搜索，筛选ip啊？这几天太卡了……

**Comment by jzp820927** [comment]
这几天国际流量掉包厉害，和 IP 没关系，只能等情况好转了

**Comment by citizentang** [comment]
楼主你他妈就是没事找事，还傻B一样的怀疑GOOGLE和GFW合作，你这么能耐也不见你开发个更好的翻墙软件，有了几个可用IP就得瑟的拿来晒，这下满意了？

**Comment by slyypp** [comment]
mark一下。

**Comment by zhencaihao** [comment]
最近两天好像开始恢复了，因为我这里看到IP数量开始增加了，而且也没有前段时间这么卡了。前段时间可能是国内“开会”或美国大选的关系导致变卡的。他也是运气不好，分享IP刚好赶上这事所以被人误认为是他导致了XX-NET变卡。没有证据就这么说，以后谁敢在这里做好事啊。

**Comment by jzp820927** [comment]
持续观望中。
