### ISSUE TITLE
私人appid无法同步进proxy.ini

### ISSUE THREAD

**Issue by uscm** [XX-net/XX-Net#45]
贵小组开发者您好，我面临以下两个问题，望解答。
一、在GoAgent 部署服务端页面填写私人appid并成功上传后，\XX-Net-1.1.0\goagent\3.1.35\local\proxy.ini没有同步；
二、手动填写appid进proxy.ini后，http://127.0.0.1:8085/--SYSTEM---GAE appid也没显示我的私人appid

**Comment by xxnet** [comment]
一、部署页面，不会影响到配置，需要去配置页面进行设置
  http://127.0.0.1:8085/?module=goagent&menu=config
二，手动修改proxy.ini后，需要重启
  不建议手动修改proxy.ini，用一提到的配置页面就好了。
