### ISSUE TITLE
部署显示成功，配置仍然提示Appid没有部署

### ISSUE THREAD

**Issue by W-quan** [XX-net/XX-Net#4501]
部署：
> 当前状态：部署完成。 
> 请在配置页面中设置AppID, 方会生效。

但是没有教程说的那样，弹出授权弹窗

**Comment by wenliyang** [comment]
请升级到 XX-Net 最新版本再部署

**Comment by jzp820927** [comment]
是什么版本

**Comment by W-quan** [comment]
3.2.7

**Comment by jzp820927** [comment]
也不算低，什么系统？

**Comment by W-quan** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-16.1.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64
os-release: 16.1.0
os-detail: Release:10.12.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:915
network-status: OK
connected-link: new:2 used:0
worker: h1:16 h2:4
scan-ip-thread-num: 50
ip-quality: 438
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
原来是 MAC 系统，MAC 系统问题挺多的，把部署的日志贴出来看看。

**Comment by W-quan** [comment]
我在Windows部署也是一样的，应该不关这事

**Comment by jzp820927** [comment]
那就检查浏览器，是不是屏蔽了，弹出窗口

**Comment by W-quan** [comment]
我肯定是检查过才敢提问的，而且程序提示部署成功，这肯定是有问题的。

**Comment by jzp820927** [comment]
https://你的appid.appspot.com
打开这个看看是什么内容

**Comment by W-quan** [comment]
404， 大概知道是由于appid有“-”符号导致的了。

**Comment by jzp820927** [comment]
哦，那删了，重建一个试试

**Comment by W-quan** [comment]
这能满足我的需求，但是不可否认，程序也是有问题的。明明没有部署成功，却显示成功了。希望改进，谢谢。
