### ISSUE TITLE
弹出广告

### ISSUE THREAD

**Issue by gyl33333** [XX-net/XX-Net#451]
请问是否加入推广广告的内容，使用过程中经常弹出阿里巴巴的页面和其他乱七八糟的页面。

**Comment by clawneo** [comment]
可能你的电信运营商的问题吧。。。 囧。。。 没遇到   作者不也说了。。。 不差钱暂时不需要赞助

**Comment by clawneo** [comment]
自己设置个dns试试。。。

**Comment by gyl33333** [comment]
应该是chrome上某个插件的问题，还没逮到是哪个。。。多谢
