### ISSUE TITLE
Macbook Pro 上如何用？

### ISSUE THREAD

**Issue by MarshallZhug** [XX-net/XX-Net#4513]
和windows一样用chrome么？Safari能不能用？

**Comment by jzp820927** [comment]
只要能设置代理，都可以用

**Comment by MarshallZhug** [comment]
@jzp820927Safari怎么设置代理啊？ 
另外，我刚在Mac上想打开start.vbs，但是显示需要指定程序，我该怎么指定？

**Comment by jzp820927** [comment]
vbs 是给 windows 用的。你可以用 chrome 配置 ome 插件

**Comment by MarshallZhug** [comment]
我目前用chrome ＋ ome可以Google了，希望能够有个Safari教程，万分感谢

**Comment by jzp820927** [comment]
google 搜索肯定有答案
