### ISSUE TITLE
XXNET用不了了

### ISSUE THREAD

**Issue by chris198685** [XX-net/XX-Net#453]
![bug](https://cloud.githubusercontent.com/assets/12598742/7799806/891eab9e-033d-11e5-942d-485e78afa48f.jpg)
现在每次进XXNET后台，都无法翻墙。而且日志点开一片空白，并且一直在报错，报错信息请看图片

**Comment by linhua55** [comment]
路径尽量不要包含中文名（“小工具”）

**Comment by chris198685** [comment]
谢谢，日志可以看了。正常了。不过之前也一直是中文路径，一直没事，不知道这次为什么有了这个问题

现在的新问题是无法翻墙，证书已更新，浏览器页面一直在刷新，就是不出内容。

May 26 01:18:55 - [DEBUG] GoAgent Web_control 127.0.0.1:64259 "GET /is_ready 
May 26 01:18:56 - [DEBUG] get ip:64.233.188.117 t:108
May 26 01:18:56 - [DEBUG] create_ssl update ip:64.233.188.117 time:112
May 26 01:18:56 - [DEBUG] get ip:139.175.107.242 t:187
May 26 01:18:56 - [DEBUG] get ip:139.175.107.162 t:835
May 26 01:18:56 - [DEBUG] get ip:123.205.251.114 t:835
May 26 01:18:57 - [DEBUG] get ip:106.162.216.29 t:835
May 26 01:18:57 - [DEBUG] get ip:84.235.77.247 t:835
May 26 01:18:57 - [DEBUG] get ip:202.65.246.112 t:835
May 26 01:18:57 - [DEBUG] get ip:178.60.128.37 t:835
May 26 01:18:58 - [DEBUG] get ip:106.162.198.93 t:835
May 26 01:18:58 - [DEBUG] get ip:139.175.107.49 t:835
May 26 01:18:58 - [DEBUG] get ip:61.19.1.158 t:835
May 26 01:18:58 - [DEBUG] create_ssl update ip:139.175.107.242 time:192
May 26 01:18:59 - [DEBUG] get ip:64.15.126.104 t:835
May 26 01:19:00 - [DEBUG] create_ssl 139.175.107.162 fail:timed out cost:4001 h:0
May 26 01:19:00 - [DEBUG] create_ssl 123.205.251.114 fail:timed out cost:4000 h:0
May 26 01:19:00 - [DEBUG] report_connect_fail network fail
May 26 01:19:01 - [DEBUG] create_ssl 106.162.216.29 fail:timed out cost:4000 h:0
May 26 01:19:01 - [DEBUG] report_connect_fail network fail
May 26 01:19:01 - [DEBUG] create_ssl 84.235.77.247 fail:timed out cost:4000 h:0
May 26 01:19:01 - [DEBUG] report_connect_fail network fail
May 26 01:19:01 - [DEBUG] create_ssl 202.65.246.112 fail:timed out cost:4000 h:0
May 26 01:19:01 - [DEBUG] report_connect_fail network fail
May 26 01:19:01 - [DEBUG] create_ssl 178.60.128.37 fail:timed out cost:4000 h:0
May 26 01:19:01 - [DEBUG] report_connect_fail network fail
May 26 01:19:01 - [DEBUG] get ip:74.125.192.41 t:835
May 26 01:19:02 - [DEBUG] create_ssl 106.162.198.93 fail:timed out cost:4000 h:0
May 26 01:19:02 - [DEBUG] report_connect_fail network fail
May 26 01:19:02 - [DEBUG] get ip:123.205.250.84 t:835
May 26 01:19:02 - [DEBUG] get ip:64.233.163.156 t:835
May 26 01:19:02 - [DEBUG] create_ssl 139.175.107.49 fail:timed out cost:4001 h:0
May 26 01:19:02 - [DEBUG] get ip:74.125.192.72 t:835
May 26 01:19:02 - [DEBUG] create_ssl 61.19.1.158 fail:timed out cost:4000 h:0
May 26 01:19:02 - [DEBUG] get ip:61.19.1.232 t:835
May 26 01:19:03 - [DEBUG] get ip:203.116.165.212 t:835
May 26 01:19:03 - [DEBUG] sort ip time:6
May 26 01:19:03 - [DEBUG] get ip:123.205.250.106 t:836
May 26 01:19:03 - [DEBUG] get ip:203.117.34.182 t:836
May 26 01:19:03 - [DEBUG] get ip:31.209.137.26 t:836
May 26 01:19:03 - [DEBUG] create_ssl 64.15.126.104 fail:timed out cost:4000 h:0
May 26 01:19:04 - [DEBUG] get ip:202.65.246.122 t:836
May 26 01:19:05 - [DEBUG] create_ssl 74.125.192.41 fail:timed out cost:4000 h:0
May 26 01:19:06 - [DEBUG] create_ssl 123.205.250.84 fail:timed out cost:4000 h:0
May 26 01:19:06 - [DEBUG] create_ssl 64.233.163.156 fail:timed out cost:4000 h:0
May 26 01:19:06 - [DEBUG] create_ssl 74.125.192.72 fail:timed out cost:4000 h:0
May 26 01:19:06 - [DEBUG] create_ssl 61.19.1.232 fail:timed out cost:4000 h:0
May 26 01:19:06 - [DEBUG] get ip:64.233.188.117 t:112
May 26 01:19:07 - [DEBUG] create_ssl update ip:64.233.188.117 time:118
May 26 01:19:07 - [DEBUG] create_ssl 203.116.165.212 fail:timed out cost:4000 h:0
May 26 01:19:07 - [DEBUG] get ip:139.175.107.242 t:192
May 26 01:19:07 - [DEBUG] get ip:123.205.251.114 t:835
May 26 01:19:07 - [DEBUG] create_ssl 123.205.250.106 fail:timed out cost:4000 h:0
May 26 01:19:07 - [DEBUG] create_ssl update ip:139.175.107.242 time:147
May 26 01:19:07 - [DEBUG]LOG_EXCEPT: create_ssl 203.117.34.182 fail:timed out cost:4000 h:0, Except:[Errno 9] Bad file descriptor
May 26 01:19:07 - [DEBUG] get ip:106.162.216.29 t:835
May 26 01:19:07 - [DEBUG] create_ssl 31.209.137.26 fail:timed out cost:4000 h:0
May 26 01:19:07 - [DEBUG] get ip:84.235.77.247 t:835
May 26 01:19:08 - [DEBUG] get ip:202.65.246.112 t:835
May 26 01:19:08 - [DEBUG] get ip:178.60.128.37 t:835
May 26 01:19:08 - [DEBUG] get ip:106.162.198.93 t:835
May 26 01:19:08 - [DEBUG] get ip:216.58.221.34 t:836
May 26 01:19:08 - [DEBUG] get ip:74.125.137.103 t:836
May 26 01:19:08 - [DEBUG] get ip:123.205.251.113 t:836
May 26 01:19:08 - [DEBUG] create_ssl 202.65.246.122 fail:timed out cost:4000 h:0
May 26 01:19:09 - [DEBUG] get ip:210.139.253.29 t:836
May 26 01:19:11 - [DEBUG] create_ssl 123.205.251.114 fail:timed out cost:4000 h:0
May 26 01:19:11 - [DEBUG] create_ssl 106.162.216.29 fail:timed out cost:4000 h:0
May 26 01:19:11 - [DEBUG] create_ssl 84.235.77.247 fail:timed out cost:4000 h:0
May 26 01:19:12 - [DEBUG] create_ssl 202.65.246.112 fail:timed out cost:4000 h:0
May 26 01:19:12 - [DEBUG] create_ssl 178.60.128.37 fail:timed out cost:4000 h:0
May 26 01:19:12 - [DEBUG] get ip:1.179.252.162 t:836
May 26 01:19:12 - [DEBUG] create_ssl 106.162.198.93 fail:timed out cost:4000 h:0
May 26 01:19:12 - [DEBUG] create_ssl 216.58.221.34 fail:timed out cost:4000 h:0
May 26 01:19:12 - [DEBUG] create_ssl 74.125.137.103 fail:timed out cost:4001 h:0
May 26 01:19:12 - [DEBUG] get ip:24.156.131.84 t:836
May 26 01:19:12 - [DEBUG] create_ssl 123.205.251.113 fail:timed out cost:4000 h:0
May 26 01:19:12 - [DEBUG] get ip:193.92.133.24 t:836
May 26 01:19:13 - [DEBUG] get ip:203.116.165.168 t:836
May 26 01:19:13 - [DEBUG] get ip:74.125.24.83 t:836
May 26 01:19:13 - [DEBUG] sort ip time:4
May 26 01:19:13 - [DEBUG] get ip:103.1.139.251 t:838
May 26 01:19:13 - [DEBUG] get ip:203.165.13.237 t:838
May 26 01:19:13 - [DEBUG] get ip:208.117.233.55 t:838
May 26 01:19:13 - [DEBUG] get ip:103.1.139.240 t:838
May 26 01:19:13 - [DEBUG] create_ssl 210.139.253.29 fail:timed out cost:4001 h:0
May 26 01:19:14 - [DEBUG] get ip:173.194.206.201 t:838
May 26 01:19:16 - [DEBUG] create_ssl 1.179.252.162 fail:timed out cost:4000 h:0
May 26 01:19:16 - [DEBUG] create_ssl 24.156.131.84 fail:timed out cost:4000 h:0
May 26 01:19:16 - [DEBUG] create_ssl 193.92.133.24 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] create_ssl 203.116.165.168 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] create_ssl 74.125.24.83 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] get ip:64.233.188.117 t:118
May 26 01:19:17 - [DEBUG] create_ssl 103.1.139.251 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] create_ssl update ip:64.233.188.117 time:117
May 26 01:19:17 - [DEBUG] create_ssl 203.165.13.237 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] create_ssl 208.117.233.55 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] get ip:139.175.107.242 t:147
May 26 01:19:17 - [DEBUG] create_ssl 103.1.139.240 fail:timed out cost:4000 h:0
May 26 01:19:17 - [DEBUG] create_ssl update ip:139.175.107.242 time:160
May 26 01:19:17 - [DEBUG] get ip:62.1.38.109 t:836
May 26 01:19:18 - [DEBUG] get ip:216.58.222.52 t:837
May 26 01:19:18 - [DEBUG] get ip:212.188.10.173 t:837
May 26 01:19:18 - [DEBUG] get ip:216.58.221.53 t:837
May 26 01:19:18 - [DEBUG] get ip:216.58.223.57 t:837
May 26 01:19:18 - [DEBUG] get ip:62.1.38.148 t:837
May 26 01:19:18 - [DEBUG] get ip:123.205.251.122 t:837
May 26 01:19:18 - [DEBUG] get ip:61.19.1.163 t:837
May 26 01:19:18 - [DEBUG] get ip:1.179.248.45 t:837
May 26 01:19:18 - [DEBUG] create_ssl 173.194.206.201 fail:timed out cost:4000 h:0
May 26 01:19:19 - [DEBUG] get ip:149.126.86.38 t:837
May 26 01:19:21 - [DEBUG] create_ssl 62.1.38.109 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] create_ssl 216.58.222.52 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] create_ssl 212.188.10.173 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] create_ssl 216.58.221.53 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] create_ssl 216.58.223.57 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] create_ssl 62.1.38.148 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG]LOG_EXCEPT: create_ssl 123.205.251.122 fail:timed out cost:4000 h:0, Except:[Errno 9] Bad file descriptor
May 26 01:19:22 - [DEBUG] create_ssl 61.19.1.163 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] create_ssl 1.179.248.45 fail:timed out cost:4000 h:0
May 26 01:19:22 - [DEBUG] get ip:222.255.120.57 t:837
May 26 01:19:23 - [DEBUG] get ip:139.175.107.34 t:837
May 26 01:19:23 - [DEBUG] get ip:193.134.255.158 t:837
May 26 01:19:23 - [DEBUG] sort ip time:4
May 26 01:19:23 - [DEBUG] get ip:24.156.131.108 t:839
May 26 01:19:23 - [DEBUG] get ip:203.116.165.183 t:839
May 26 01:19:23 - [DEBUG] get ip:193.192.250.148 t:839
May 26 01:19:23 - [DEBUG] get ip:213.240.44.18 t:839
May 26 01:19:23 - [DEBUG] get ip:213.240.44.16 t:839
May 26 01:19:23 - [DEBUG] get ip:84.235.77.222 t:840
May 26 01:19:23 - [DEBUG] create_ssl 149.126.86.38 fail:timed out cost:4000 h:0
May 26 01:19:24 - [DEBUG] get ip:139.175.107.163 t:840
May 26 01:19:26 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 139.175.107.34 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 193.134.255.158 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 24.156.131.108 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 203.116.165.183 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 193.192.250.148 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 213.240.44.18 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 213.240.44.16 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] create_ssl 84.235.77.222 fail:timed out cost:4000 h:0
May 26 01:19:27 - [DEBUG] get ip:64.233.188.117 t:117
May 26 01:19:28 - [DEBUG] create_ssl update ip:64.233.188.117 time:121
May 26 01:19:28 - [DEBUG] get ip:139.175.107.242 t:160
May 26 01:19:28 - [DEBUG] get ip:203.116.165.173 t:837
May 26 01:19:28 - [DEBUG] get ip:208.117.233.26 t:838
May 26 01:19:28 - [DEBUG] create_ssl update ip:139.175.107.242 time:146
May 26 01:19:28 - [DEBUG] get ip:203.116.165.227 t:838
May 26 01:19:28 - [DEBUG] get ip:218.253.0.187 t:838
May 26 01:19:28 - [DEBUG] get ip:91.213.30.173 t:838
May 26 01:19:28 - [DEBUG] get ip:64.15.124.153 t:838
May 26 01:19:28 - [DEBUG] get ip:212.188.7.187 t:838
May 26 01:19:28 - [DEBUG] create_ssl 139.175.107.163 fail:timed out cost:4000 h:0
May 26 01:19:29 - [DEBUG] get ip:222.255.120.59 t:838
May 26 01:19:29 - [DEBUG] get ip:139.175.107.24 t:838
May 26 01:19:29 - [DEBUG] get ip:84.235.77.162 t:838
May 26 01:19:32 - [DEBUG] create_ssl 203.116.165.173 fail:timed out cost:4001 h:0
May 26 01:19:32 - [DEBUG] create_ssl 208.117.233.26 fail:timed out cost:4001 h:0
May 26 01:19:32 - [DEBUG] create_ssl 203.116.165.227 fail:timed out cost:4001 h:0
May 26 01:19:32 - [DEBUG] create_ssl 218.253.0.187 fail:timed out cost:4000 h:0
May 26 01:19:32 - [DEBUG] create_ssl 91.213.30.173 fail:timed out cost:4000 h:0
May 26 01:19:32 - [DEBUG] create_ssl 64.15.124.153 fail:timed out cost:4001 h:0
May 26 01:19:32 - [DEBUG] create_ssl 212.188.7.187 fail:timed out cost:4000 h:0
May 26 01:19:33 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:4000 h:0
May 26 01:19:33 - [DEBUG] get ip:66.185.84.153 t:839
May 26 01:19:33 - [DEBUG] sort ip time:3
May 26 01:19:33 - [DEBUG] get ip:106.162.192.158 t:840
May 26 01:19:33 - [DEBUG] create_ssl 139.175.107.24 fail:timed out cost:4000 h:0
May 26 01:19:33 - [DEBUG] get ip:212.188.7.39 t:841
May 26 01:19:33 - [DEBUG] get ip:210.242.125.40 t:841
May 26 01:19:33 - [DEBUG] get ip:216.58.212.102 t:841
May 26 01:19:33 - [DEBUG] get ip:218.176.242.30 t:841
May 26 01:19:33 - [DEBUG] get ip:1.179.248.172 t:841
May 26 01:19:33 - [DEBUG] create_ssl 84.235.77.162 fail:timed out cost:4000 h:0
May 26 01:19:34 - [DEBUG] get ip:61.19.1.241 t:841
May 26 01:19:34 - [DEBUG] get ip:203.116.165.163 t:841
May 26 01:19:34 - [DEBUG] get ip:41.201.128.40 t:841
May 26 01:19:37 - [DEBUG] create_ssl 66.185.84.153 fail:timed out cost:4000 h:0
May 26 01:19:37 - [DEBUG] create_ssl 106.162.192.158 fail:timed out cost:4000 h:0
May 26 01:19:37 - [DEBUG] create_ssl 212.188.7.39 fail:timed out cost:4000 h:0
May 26 01:19:37 - [DEBUG]LOG_EXCEPT: create_ssl 210.242.125.40 fail:timed out cost:4000 h:0, Except:[Errno 9] Bad file descriptor
May 26 01:19:37 - [DEBUG] create_ssl 216.58.212.102 fail:timed out cost:4000 h:0
May 26 01:19:37 - [DEBUG] create_ssl 218.176.242.30 fail:timed out cost:4000 h:0
May 26 01:19:37 - [DEBUG] create_ssl 1.179.248.172 fail:timed out cost:4000 h:0
May 26 01:19:38 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:4000 h:0
May 26 01:19:38 - [DEBUG] get ip:64.233.188.117 t:121
May 26 01:19:38 - [DEBUG] get ip:139.175.107.242 t:146
May 26 01:19:38 - [DEBUG] create_ssl update ip:64.233.188.117 time:115
May 26 01:19:38 - [DEBUG] create_ssl 203.116.165.163 fail:timed out cost:4000 h:0
May 26 01:19:38 - [DEBUG] get ip:62.197.198.245 t:839
May 26 01:19:38 - [DEBUG] get ip:123.205.250.112 t:839
May 26 01:19:38 - [DEBUG] get ip:106.162.192.177 t:839
May 26 01:19:38 - [DEBUG] create_ssl update ip:139.175.107.242 time:158
May 26 01:19:38 - [DEBUG] create_ssl 41.201.128.40 fail:timed out cost:4000 h:0
May 26 01:19:42 - [DEBUG] create_ssl 62.197.198.245 fail:timed out cost:4000 h:0
May 26 01:19:42 - [DEBUG] create_ssl 123.205.250.112 fail:timed out cost:4000 h:0
May 26 01:19:42 - [DEBUG] create_ssl 106.162.192.177 fail:timed out cost:4000 h:0

**Comment by chris198685** [comment]
已找到原因，要把代理设置内的SOCKS代理的勾去掉。

**Comment by yinzq** [comment]
请问代理设置在哪里啊？ 我也遇到上图的问题
