### ISSUE TITLE
请问如何卸载？

### ISSUE THREAD

**Issue by w4brown** [XX-net/XX-Net#4536]
Hi,

这个太好了，但我现在需要卸载了重装，请问怎么卸载，直接把那个目录删除了吗？那之前运行过的start.vbs脚本会有残留吗？

**Comment by wenliyang** [comment]
直接删除，没有残留
如果想保留之前的设置、扫描得到的IP等，保存 data 文件夹

**Comment by w4brown** [comment]
哦，好的，谢谢，建议把这个加入手册里，毕竟安装卸载是配套的，手册只将了安装

**Comment by jzp820927** [comment]
就删个文件夹，还要写手册

**Comment by cdmask** [comment]
新手嘛
