### ISSUE TITLE
用xx-net上facebook老被冻结

### ISSUE THREAD

**Issue by JohnYinlubin** [XX-net/XX-Net#4538]
各位大神，我用xx-net上网页版facebook，每次重新打开浏览器就被冻结，每次都要获取手机验证码解冻，之后还要改密码，请问有破解的办法吗？还有facebook电脑版应用下载起来打不开？求解决办法~~~

**Comment by panghu1986** [comment]
你是那个版本啊 ，我用macbook xx-net上网感觉比windows的要好用很多，而且速度很快啊 。
![snip20161112_1](https://cloud.githubusercontent.com/assets/23070015/20235811/3fd3ea52-a8d8-11e6-9db6-5ddf1f278dfc.png)

**Comment by JohnYinlubin** [comment]
我是3.2.7

**Comment by JohnYinlubin** [comment]
速度没问题，就是上fb经常需要验证

**Comment by jzp820927** [comment]
是不是 fb 对 GAE 的 IP，有限制

**Comment by JohnYinlubin** [comment]
可能吧，而且网页的messenger还不能通话，之前用vpn gate 可以，但速度和xx-net没法比😁

**Comment by jzp820927** [comment]
那你用 x_tunnel 试试吧

**Comment by JohnYinlubin** [comment]
x_tunnel 怎么用尼？

**Comment by JohnYinlubin** [comment]
![image](https://cloud.githubusercontent.com/assets/23398081/20236182/b8313f32-a8e6-11e6-9302-c6c49871738c.png)

**Comment by jzp820927** [comment]
看 wiki

**Comment by JohnYinlubin** [comment]
好的，谢谢
