### ISSUE TITLE
自检时显示get_version_fail

### ISSUE THREAD

**Issue by kelvin7feng** [XX-net/XX-Net#4539]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: get_version_fail
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 1848 / 84
network-status: OK
connected-link: 6 / 2
scan-ip-thread-num: 50
ip-quality: 784
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by wenliyang** [comment]
手动下载 XX-Net 最新版本升级

**Comment by jzp820927** [comment]
只要不影响使用就行了，版本号显不显示无所谓
