### ISSUE TITLE
Require password while starting on macOS Sierra

### ISSUE THREAD

**Issue by hzxie** [XX-net/XX-Net#4551]
这个问题存在相当一段时间，我仔细分析了一下问题的原因。
情况是这样的：

之前不需要密码是因为，@cc941201 创建了 `mac_helper.c` 这个文件，这个文件在第一次创建时会赋予`root`权限。然后之后一直使用这个`helper`进行网络配置。

而在新的Sierra系统中，`mac_helper`在调用时提示必须以`root`用户启动，而代码中没有以`root`权限启动，导致`helper`调用失败（可能是新系统中的安全策略变更？）。进而执行 `mac_tray.py`中`except`中的语句：`do shell script ... with administrator privileges`。所以会提示用户输入密码。

解决方案如 #4249 中所述，当然这不是一个好的策略。
容我再想想，占个坑先。

**Comment by cc941201** [comment]
不好意思最近不在墙内，这个问题貌似只需要把`chmod`和`chown`对调一下就行。我马上提交一个PR

**Comment by yeahwu** [comment]
好久不见！

**Comment by hzxie** [comment]
@yeahwu
哈哈哈哈哈~ 好久不见~
我消失的原因和X大类似(捂脸)

**Comment by Pekary** [comment]
大大们,最近速度不行这个 问题有解决办法么

**Comment by jzp820927** [comment]
物理线路掉包，无解。
