### ISSUE TITLE
求助：两部机同用XX-net，一个顺畅，另一个No

### ISSUE THREAD

**Issue by topgun2016** [XX-net/XX-Net#4561]
在单位用台式机，XX-net正常，不用3秒，就可以连上。copy同样的文件（包括data目录）回到家里的神州笔记本。就不正常，只是试过一次在连接了很久以后（起码15分钟）才显示：XX-Net 3.2.7，一切正常，你可以访问真正的互联网了。其余的，都是不行，说要检查浏览器代理设置，就卡在这里。两台机都是用win7 64位旗舰版，chrome浏览器（同一个登录帐号，笔记本就是因为成功过一次，所以能同步Google账号的资料）。甚至将笔记本带回单位，在同一网络下，也是没试过成功。XX-net里面使用的GoAgent ID相同，Why？

[诊断信息--不成功的.docx](https://github.com/XX-net/XX-Net/files/588850/--.docx)
[日志--不成功的.docx](https://github.com/XX-net/XX-Net/files/588851/--.docx)
[日志--成功的.docx](https://github.com/XX-net/XX-Net/files/588852/--.docx)
[诊断信息--成功的.docx](https://github.com/XX-net/XX-Net/files/588853/--.docx)

**Comment by topgun2016** [comment]
补充：对比两个界面的显示，不成功的：老是显示“请检查浏览器代理设置。还显示：检查浏览器代理设置 fail。但检查过设置，就是跟正常的一样。

**Comment by SeaHOH** [comment]
安装证书没有？
还有不要发文档，直接贴出来就行，图片也可以。
这年头太危险，不敢乱开文档。

**Comment by topgun2016** [comment]
多谢指点！下面是日志（不成功的那个）。
Nov 14 17:24:17.522 - [INFO] scan_ip add ip:201.6.16.155 time:1808
Nov 14 17:24:17.533 - [INFO] remove_slowest_ip:40.136.3.112 handshake_time:799, fails:3
Nov 14 17:24:20.191 - [INFO] scan_ip add ip:103.233.37.12 time:802
Nov 14 17:24:20.213 - [INFO] remove_slowest_ip:77.153.128.248 handshake_time:1799, fails:2
Nov 14 17:24:26.171 - [INFO] scan_ip add ip:59.18.45.243 time:434
Nov 14 17:24:26.189 - [INFO] remove_slowest_ip:46.236.127.237 handshake_time:798, fails:3
Nov 14 17:24:28.237 - [INFO] scan_ip add ip:1.9.131.123 time:616
Nov 14 17:24:28.255 - [INFO] remove_slowest_ip:8.35.80.55 handshake_time:798, fails:3
Nov 14 17:24:30.542 - [INFO] scan_ip add ip:80.97.208.39 time:870
Nov 14 17:24:30.562 - [INFO] remove_slowest_ip:49.231.60.185 handshake_time:798, fails:3
Nov 14 17:24:42.622 - [INFO] scan_ip add ip:180.211.201.244 time:2006
Nov 14 17:24:42.638 - [INFO] remove_slowest_ip:201.248.76.149 handshake_time:797, fails:3
Nov 14 17:24:57.951 - [INFO] scan_ip add ip:23.236.5.180 time:806
Nov 14 17:24:57.969 - [INFO] remove_slowest_ip:85.187.222.34 handshake_time:797, fails:3
Nov 14 17:25:06.248 - [INFO] scan_ip add ip:1.9.131.119 time:1039
Nov 14 17:25:06.266 - [INFO] remove_slowest_ip:62.8.95.119 handshake_time:797, fails:3
Nov 14 17:25:14.832 - [INFO] scan_ip add ip:204.111.84.222 time:1414
Nov 14 17:25:14.850 - [INFO] remove_slowest_ip:78.11.253.150 handshake_time:797, fails:3
Nov 14 17:25:24.276 - [INFO] scan_ip add ip:201.218.56.176 time:1146
Nov 14 17:25:24.293 - [INFO] remove_slowest_ip:184.150.153.142 handshake_time:796, fails:3
Nov 14 17:25:26.484 - [INFO] scan_ip add ip:196.23.168.165 time:1114
Nov 14 17:25:26.505 - [INFO] remove_slowest_ip:203.118.141.251 handshake_time:796, fails:3
Nov 14 17:25:38.548 - [INFO] scan_ip add ip:85.91.7.34 time:575
Nov 14 17:25:38.566 - [INFO] remove_slowest_ip:112.72.5.99 handshake_time:795, fails:3
Nov 14 17:25:41.517 - [INFO] scan_ip add ip:82.221.224.38 time:1653
Nov 14 17:25:41.538 - [INFO] remove_slowest_ip:150.101.213.178 handshake_time:1795, fails:2
Nov 14 17:25:49.806 - [INFO] scan_ip add ip:194.78.0.79 time:407
Nov 14 17:25:49.828 - [INFO] remove_slowest_ip:186.2.131.185 handshake_time:794, fails:3
Nov 14 17:25:54.621 - [INFO] scan_ip add ip:110.93.194.19 time:1535
Nov 14 17:25:54.639 - [INFO] remove_slowest_ip:104.237.185.196 handshake_time:794, fails:3
Nov 14 17:25:55.619 - [INFO] scan_ip add ip:167.206.252.92 time:1519
Nov 14 17:25:55.639 - [INFO] remove_slowest_ip:77.242.30.13 handshake_time:793, fails:3
Nov 14 17:25:56.226 - [INFO] scan_ip add ip:203.233.126.179 time:211
Nov 14 17:25:56.243 - [INFO] remove_slowest_ip:5.102.167.22 handshake_time:792, fails:3
Nov 14 17:26:15.443 - [INFO] scan_ip add ip:186.251.10.40 time:1055
Nov 14 17:26:15.462 - [INFO] remove_slowest_ip:177.43.235.13 handshake_time:792, fails:3
Nov 14 17:26:24.189 - [DEBUG] GAEProxy web_control 127.0.0.1:58521 POST /config?cmd=get_config
Nov 14 17:26:24.190 - [DEBUG] GAEProxy Web_control 127.0.0.1:58517 GET /scan_ip?cmd=get_range
Nov 14 17:26:24.190 - [INFO] load ip range file:F:\\XX-Net-3.2.6\code\3.2.8\gae_proxy\local\ip_range.txt
Nov 14 17:26:26.281 - [DEBUG] GAEProxy Web_control 127.0.0.1:58517 GET /scan_ip?cmd=get_scan_ip_log
Nov 14 17:26:26.601 - [INFO] scan_ip add ip:186.2.131.172 time:720
Nov 14 17:26:26.614 - [INFO] remove_slowest_ip:177.100.48.33 handshake_time:792, fails:3
Nov 14 17:26:27.873 - [INFO] scan_ip add ip:193.134.255.207 time:559
Nov 14 17:26:27.890 - [INFO] remove_slowest_ip:90.150.4.93 handshake_time:792, fails:3
Nov 14 17:26:29.003 - [INFO] scan_ip add ip:173.218.248.172 time:790
Nov 14 17:26:29.025 - [INFO] remove_slowest_ip:45.64.138.142 handshake_time:792, fails:3
Nov 14 17:26:29.107 - [DEBUG] GAEProxy Web_control 127.0.0.1:58517 GET /scan_ip?cmd=get_scan_ip_log
Nov 14 17:26:29.116 - [INFO] scan_ip add ip:210.187.22.218 time:653
Nov 14 17:26:29.130 - [INFO] remove_slowest_ip:139.175.107.186 handshake_time:791, fails:3
Nov 14 17:26:36.525 - [DEBUG] ssl_closed 122.154.133.34
Nov 14 17:26:36.526 - [DEBUG] 122.154.133.34 worker close:idle timeout
Nov 14 17:26:36.823 - [INFO] scan_ip add ip:5.226.127.179 time:692
Nov 14 17:26:36.841 - [INFO] remove_slowest_ip:31.209.137.38 handshake_time:791, fails:3
Nov 14 17:26:49.887 - [INFO] scan_ip add ip:61.238.239.155 time:37
Nov 14 17:26:49.906 - [INFO] remove_slowest_ip:181.198.80.83 handshake_time:791, fails:3
Nov 14 17:27:04.555 - [INFO] scan_ip add ip:187.86.12.180 time:1862
Nov 14 17:27:04.572 - [INFO] remove_slowest_ip:197.199.254.58 handshake_time:791, fails:3
Nov 14 17:27:07.647 - [INFO] scan_ip add ip:58.123.102.33 time:128
Nov 14 17:27:07.667 - [INFO] remove_slowest_ip:190.116.191.33 handshake_time:790, fails:3
Nov 14 17:27:11.333 - [DEBUG] ssl_closed 71.19.173.97
Nov 14 17:27:11.333 - [DEBUG] 71.19.173.97 worker close:idle timeout
Nov 14 17:27:17.778 - [INFO] scan_ip add ip:219.88.189.52 time:1935
Nov 14 17:27:17.797 - [INFO] remove_slowest_ip:49.231.60.160 handshake_time:790, fails:3
Nov 14 17:27:36.064 - [INFO] scan_ip add ip:212.188.7.223 time:1506
Nov 14 17:27:36.083 - [INFO] remove_slowest_ip:184.150.183.221 handshake_time:790, fails:3
Nov 14 17:27:47.954 - [INFO] scan_ip add ip:41.206.96.164 time:687
Nov 14 17:27:47.973 - [INFO] remove_slowest_ip:178.132.81.108 handshake_time:1790, fails:2
Nov 14 17:28:08.900 - [DEBUG] ssl_closed 113.171.253.159
Nov 14 17:28:08.901 - [DEBUG] 113.171.253.159 worker close:idle timeout
Nov 14 17:28:17.690 - [INFO] scan_ip add ip:216.123.194.213 time:1016
Nov 14 17:28:17.707 - [INFO] remove_slowest_ip:201.49.80.55 handshake_time:790, fails:3
Nov 14 17:28:19.257 - [INFO] scan_ip add ip:74.124.63.96 time:628
Nov 14 17:28:19.275 - [INFO] remove_slowest_ip:45.116.219.55 handshake_time:789, fails:3
Nov 14 17:28:24.591 - [DEBUG] ssl_closed 210.143.70.17
Nov 14 17:28:24.591 - [DEBUG] 210.143.70.17 worker close:idle timeout
Nov 14 17:28:30.575 - [INFO] scan_ip add ip:58.123.220.20 time:180
Nov 14 17:28:30.593 - [INFO] remove_slowest_ip:24.214.95.167 handshake_time:789, fails:3
Nov 14 17:28:32.399 - [INFO] scan_ip add ip:82.135.118.42 time:859
Nov 14 17:28:32.419 - [INFO] remove_slowest_ip:200.29.113.41 handshake_time:1789, fails:2
Nov 14 17:28:32.764 - [INFO] scan_ip add ip:69.65.64.101 time:704
Nov 14 17:28:32.781 - [INFO] remove_slowest_ip:200.28.6.107 handshake_time:789, fails:3
Nov 14 17:28:42.272 - [INFO] scan_ip add ip:49.231.56.48 time:1510
Nov 14 17:28:42.289 - [INFO] remove_slowest_ip:103.233.36.112 handshake_time:788, fails:3
Nov 14 17:29:00.307 - [INFO] scan_ip add ip:186.215.155.37 time:1085
Nov 14 17:29:00.328 - [INFO] remove_slowest_ip:189.203.232.42 handshake_time:787, fails:3

**Comment by topgun2016** [comment]
下面是不成功的诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:929
network-status: OK
connected-link: new:2 used:0
worker: h1:5 h2:0
scan-ip-thread-num: 50
ip-quality: 373
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by topgun2016** [comment]
另外 关于证书，这个不是运行XX-net时就自动安装的吗？我查看过相关的证书列表，里面有两个证书，颁发给和颁发者都是 GoAgent XX-Net。还有一个颁发给和颁发者都是GoAgent。

**Comment by SeaHOH** [comment]
你安装的证书和 XX-Net 正在使用的证书是不是同一个，注意看 SHA 指纹。
不懂的话就把浏览器（如果自带证书管理）和操作系统中的 GoAgent 证书都删除，然后重新导入，指笔记本。
浏览器可能需要重启。

**Comment by topgun2016** [comment]
已经将原来的3个证书删除，然后重新运行eGoAgent，重新生成了证书（日期是今天的），然后再运行XX-net，它也导入了新证书（颁发给和颁发者都是 GoAgent XX-Net），日期是昨天，指纹是‎1f 8e ab 5b 3e a3 da 59 9a 30 f4 d7 7a de 68 02 e9 。。。。。。不过仍然显示“请检查浏览器代理设置。”

**Comment by SeaHOH** [comment]
原来的3个证书删除？是不是 XX-Net 文件夹中的？这个无所谓。
但必须要删除系统中的证书，不然不会重复导入，因为已经存在同名证书。
指纹只是让你能够确认，自签证书是随机密钥签名的，每次都不一样。

**Comment by SeaHOH** [comment]
原来的3个证书删除？是不是 XX-Net 文件夹中的？这个无所谓。
但必须要删除系统中的证书，不然不会重复导入，因为已经存在同名证书。
指纹只是让你能够确认，自签证书是随机密钥签名的，每次都不一样。

**Comment by topgun2016** [comment]
删除证书，就是删除ie里面的证书（证书列表，里面有两个证书，颁发给和颁发者都是 GoAgent XX-Net。还有一个颁发给和颁发者都是GoAgent），我的浏览器就是ie和chrome。你指的系统及浏览器中的证书，就是我IE里面的吗？

**Comment by jzp820927** [comment]
先试试能不能用吧，有时候那些提示并不影响使用。

**Comment by SeaHOH** [comment]
不用 IE，才发现能从 IE 删除系统证书。
确实不能用？看上面的状态网络也正常啊。
8085 端口正常，照道理 8086 和 8087 端口应该一样。
你是通过托盘图标设置的代理还是手动设置，建议手动设置尝试一下。

**Comment by topgun2016** [comment]
嗯 可能在大神们的感召下，最终能用了，就是显示还是要“请检查浏览器代理设置”。谢谢各位！

**Comment by SeaHOH** [comment]
这下真的不懂了，能用了为什么还是显示“请检查浏览器代理设置”，这个是哪儿显示的？

**Comment by jzp820927** [comment]
猜测，对于部署在路由器，共享给局域网使用的情况，局域网其他机器导入了证书，但是路由器没有导入证书，因此运行在路由器上的 XX 在通过连接 twitter 检查网络连通性的时候，由于证书错误，可能会导致显示检查代理设置。也就是对于部署在非本机的时候，可能会出现这种情况。

**Comment by SeaHOH** [comment]
好像不对，他这个是本机，不是路由器。

**Comment by jzp820927** [comment]
恩，我只是说有这种情况，具体问题，具体问题，如果是部署本机，那就没关系了。
