### ISSUE TITLE
用com.hk搜索会403，但com不会，上海电信

### ISSUE THREAD

**Issue by voidprotossarthas** [XX-net/XX-Net#4565]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2025
network-status: OK
connected-link: new:3 used:0
worker: h1:11 h2:7
scan-ip-thread-num: 20
ip-quality: 519
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

日志
Nov 15 20:12:37.618 - [DEBUG] GAE CONNECT Direct GET https://www.google.com.hk/search?q=xxnet+error+403&safe=off&hl=zh-TW&newwindow=1&ie=UTF-8

Nov 15 20:12:37.618 - [DEBUG] host_conn_pool www.google.com.hk get:93.87.90.36 handshake:519

Nov 15 20:12:38.369 - [INFO] DIRECT t:750 s:431 302 www.google.com.hk /search?q=xxnet+error+403&safe=off&hl=zh-TW&newwindow=1&ie=UTF-8

Nov 15 20:12:38.410 - [DEBUG] GAE GET https://ipv4.google.com/sorry/index?continue=https://www.google.com.hk/search%3Fq%3Dxxnet%2Berror%2B403%26safe%3Doff%26hl%3Dzh-TW%26newwindow%3D1%26ie%3DUTF-8&hl=zh-TW&q=EgQ9pe_MGLX3q8EFIhkA8aeDS48hnLerIZeuR1i_xzT9qTt5TXPQMgFj

Nov 15 20:12:38.654 - [INFO] GAE t:243 s:1789 GET https://ipv4.google.com/sorry/index?continue=https://www.google.com.hk/search%3Fq%3Dxxnet%2Berror%2B403%26safe%3Doff%26hl%3Dzh-TW%26newwindow%3D1%26ie%3DUTF-8&hl=zh-TW&q=EgQ9pe_MGLX3q8EFIhkA8aeDS48hnLerIZeuR1i_xzT9qTt5TXPQMgFj get_response:240

Nov 15 20:12:38.967 - [DEBUG] GAE GET https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png

Nov 15 20:12:39.208 - [INFO] GAE t:240 s:0 GET https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png get_response:237

Nov 15 20:12:42.386 - [DEBUG] 213.105.64.244 keep alive fail, inactive_time:230 head_timeout:41

Nov 15 20:12:42.386 - [DEBUG] report_connect_fail:213.105.64.244

Nov 15 20:12:47.387 - [DEBUG] 213.105.64.244 worker close:keep alive

Nov 15 20:12:48.592 - [DEBUG] ssl_closed 213.151.210.24

Nov 15 20:12:48.592 - [DEBUG] 213.151.210.24 worker close:GoAway: additional_data:session_timed_out

**Comment by SeaHOH** [comment]
怀疑配置问题，贴下``manual.ini``看看。

**Comment by voidprotossarthas** [comment]
[pac]
enable = 0

**Comment by SeaHOH** [comment]
就这一条？

**Comment by voidprotossarthas** [comment]
恩

**Comment by SeaHOH** [comment]
你这种情况是 hk **一定**会返回 ipv4.google.com/sorry，而 com **一定**正常？
默认配置里这种状况说不通。

**Comment by voidprotossarthas** [comment]
https://www.google.com.hk/search?q=qwe&safe=off&hl=zh-TW&newwindow=1&ie=UTF-8
https://www.google.com/search?q=qwe&safe=off&hl=zh-TW&newwindow=1&ie=UTF-8
对的

**Comment by SeaHOH** [comment]
不用 hk 也好啊，反正 com 正常。就是太奇怪了，你不会是改过默认配置吧？
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/proxy.ini

**Comment by voidprotossarthas** [comment]
我重下了3.2.7还是这样

**Comment by SeaHOH** [comment]
都没见过其他人有这情况，别人是 hk 和 com 都会出现 ipv4.google.com/sorry 。
这是 IP 问题，要不你备份 goodip 后删除重新扫描。
不过还是建议不要用 hk，也就不用重新扫描，毕竟 com 是正常的。

**Comment by voidprotossarthas** [comment]
清空cookie好了，fvck.........

**Comment by SeaHOH** [comment]
恭喜
