### ISSUE TITLE
adblock的支持程度是多少？

### ISSUE THREAD

**Issue by ivysrono** [XX-net/XX-Net#457]
隐藏规则是肯定不支持的，这不用问。
https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
这是去掉隐藏规则的easylist，这里面的语法又支持多少？
如果将该规则填入 adblock=url 里，不支持的部分是否会影响性能？

**Comment by jzp820927** [comment]
亲自试试不就知道了。

**Comment by jzp820927** [comment]
2 年前的 issues 还记得来 close，LZ 确实有心啊。

**Comment by ivysrono** [comment]
装了个app能显示出所有还开着的issues和pr，下午无聊就翻翻，把不需要了的关掉。
好多都不知道是啥玩意了，岁月啊…

**Comment by jzp820927** [comment]
什么 app？这么 NB ？

**Comment by ivysrono** [comment]
FastHub
也是无意中发现的功能。

**Comment by jzp820927** [comment]
感谢分享，我也装个玩玩
