### ISSUE TITLE
可以查看在使用哪个账号的appid吗？

### ISSUE THREAD

**Issue by NAVrasZ** [XX-net/XX-Net#4579]
之前申请了两个号的appid，最近网络不佳想捐appid换点xxtunnel流量，然而发现忘了google账户名...

**Comment by jzp820927** [comment]
你的意思，通过 appid 名称，查询 google 账号？这个应该不行吧

**Comment by NAVrasZ** [comment]
本以为xxnet也会记录授权的账户...才想起每个appid名称貌似都不同...好吧我再想想

**Comment by nly4lov** [comment]
如果是自己的账号，挨个看下它下挂哪些ID嘛

**Comment by NAVrasZ** [comment]
@nly4lov 蛤？怎么看？（不记得账户名登不了GAE...）

**Comment by jzp820927** [comment]
帐户名都忘记了，这个基本上无解了，一般服务只有找回密码功能，没有找回账号功能。

**Comment by nly4lov** [comment]
连自己账号都记不住，我们还有啥可说的

**Comment by NAVrasZ** [comment]
隔了半年想起账号 close
