### ISSUE TITLE
如何强制更新gfwlist？

### ISSUE THREAD

**Issue by ivysrono** [XX-net/XX-Net#458]
无意中发现一个gfwlist近期添加的网站，通过浏览器扩展可以正常访问了，但xxnet生成的pac就不行。
且无论是在 \local\proxy.ini 还是新建了 \data\goagent\manual.ini 修改

[pac]
gfwlist = https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt|https://list2.txt
adblock = https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt

都没有生效，无论是gfwlist的更新还是自定义的list2
已经多次重启goagent，重启xxnet，重启Windows。
还是希望能在gui高级选项中加入自定义列表的选项。

**Comment by clawneo** [comment]
再给你一个吧。。。 
http://www.firefoxfan.com/gfwlist/gfwlist.txt

昨天gfwlist又可以连上更新了。。。

**Comment by clawneo** [comment]
另外删除data文件夹  重新部署试试~

**Comment by renyouguo** [comment]
@clawneo 问题是，我自定义的规则地址在github，也没有效果啊。

**Comment by clawneo** [comment]
默认地址可以同步。。。 最近都是正常的。。。 
挂机多扫描会吧。。。 估计是你那的可用IP太少了。。。

**Comment by clawneo** [comment]
http://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt

**Comment by clawneo** [comment]
如果你正在使用 GFW List ，更新完毕后请前往选项中的自动切换选项卡，在靠近页面底部点击“立即更新情景模式”来下载 GFW List。如果下载失败，请切换到全局代理模式再尝试下载。

特别提醒：由于Chrome限制，同一时间只能有一个扩展控制代理设置，一般来说Chrome会优先后安装的扩展。冲突中若SwitchyOmega获得了优先权，则可以切换到“系统代理”模式，从而把优先权归还给其他扩展，从而解决问题。如果此扩展的配置被其他代理相关、或者去广告相关的扩展覆盖，则问题无法解决，只能通过重装SwitchyOmega来提高优先权。
https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-新功能

**Comment by renyouguo** [comment]
不是连接不上，访问gfwlist毫无问题，用扩展什么的没有任何问题，youtube都能很流畅。
问题是xxnet本身无法更新，包括我的自定义规则无法生效。

**Comment by xxnet** [comment]
你是什么操作系统？
前面有发现新的Linux发新版，证书导入方式变了，需要重新作适配。
  目前知道debian 8/ arch linux的证书导入，对系统默认没有起效。

在 2015年6月1日 下午10:42，renyouguo <notifications@github.com>写道：

**Comment by renyouguo** [comment]
win8.1 x64
win7 x64

**Comment by xxnet** [comment]
请把升级ftwlist的日志贴出来

2015-06-02 9:16 GMT+08:00 renyouguo <notifications@github.com>:

**Comment by clawneo** [comment]
7-8.1 x64 都是正常的。。。 囧。。。
