### ISSUE TITLE
继续编译个lantern大家玩玩，速度好像还不错

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#4586]
去掉弹窗，关掉pac，免费版
https://github.com/yeahwu/recycle-bin/files/599574/lantern11.18.tar.gz

**Comment by dou4cc** [comment]
南京电信完全连不上

**Comment by yeahwu** [comment]
俺这边连的是日本的节点，所以发出来大家玩玩。

**Comment by zhencaihao** [comment]
这个用的是XX-NET的服务器吗？麻烦问一下，XX-NET怎么连日本的额节点啊？是不是在创建appid的时候选亚洲服务器就，然后用这个APPID连就显示日本的IP了？

**Comment by Pekary** [comment]
lantern,linux下怎么用? 运行文件后不能进google, 需要像xx一样设置代理么?

**Comment by jzp820927** [comment]
@zhencaihao XXNET 无法选择出口IP位置，出口IP位置是由 GAE 服务器自动分配的，无法手动选择。

**Comment by Pekary** [comment]
@jzp820927  运行以后没有弹窗, 设置代理端口是? 能详细一点么,谢谢!

**Comment by yeahwu** [comment]
127.0.0.1:8787
Pekary <notifications@github.com>于2016年11月18日 周五20:20写道：

**Comment by Pekary** [comment]
@yeahwu  好了,谢了~  这个看coursera感觉比XX流畅一点

**Comment by jzp820927** [comment]
免费用户有流量限制的

**Comment by zhencaihao** [comment]
@jzp820927
![qq 20161118231420](https://cloud.githubusercontent.com/assets/19796493/20434882/d766f268-ade4-11e6-91f1-b9d80bd73ce0.jpg)
建立appid时下面选项里的美国中部、欧洲西部、美国东部、亚洲东北部这个不是服务器位置吗？

**Comment by jzp820927** [comment]
这个只是数据中心，并不是出口IP，不信的话，你可以用不同区域的 appid，访问  www.whatismyip.com ，看看你的IP就知道了/

**Comment by wpyok500** [comment]
这个是2.0还是3.0时代产品

**Comment by zhencaihao** [comment]
@jzp820927好吧，谢谢了。还有个问题啊，我现在几个APPID选得是美国中部的，如果换成亚洲东北部的那么网速是不是会快一点啊？

**Comment by jzp820927** [comment]
网速快不快，决定因素在 前端IP（也就是 GWS 和 GVS），是通过  GWS 和 GVS 来连接 GAE 数据中心的，然后再到 出口 服务器。你入口都不快，中间快也没用。

**Comment by roc1010kmt** [comment]
感覺這兩天亚洲东北部比美国中部慢.

**Comment by CHN008** [comment]
大佬,编译一下Android版的xxnet用一下啊,感激之情如长江之水滔滔不绝 :smile:

**Comment by jzp820927** [comment]
亚洲是干扰和掉包的重点区域。

**Comment by CHN008** [comment]
@jzp820927  那个版本早就下载过 用不了 :disappointed:

**Comment by jzp820927** [comment]
是啊，新系统都用不了，好像是只能用于 5以下的系统，不过有人问，我也就回一下，用不了，就没办法了。我还是趋向于用 PAC 模式。

**Comment by theratlesnake** [comment]
@jzp820927 老大，那个安装版的下载地址还有吗

**Comment by jzp820927** [comment]
什么安装版？

**Comment by theratlesnake** [comment]
@jzp820927 你说得android 5系统以下的xx-net安卓版安装包啊

**Comment by jzp820927** [comment]
https://github.com/XX-net/xxnet-android/releases

**Comment by theratlesnake** [comment]
@jzp820927 谢谢谢，我试试，刚好有台老手机

**Comment by jzp820927** [comment]
android 4及以下，应该没问题，5 和以上，不行

**Comment by theratlesnake** [comment]
@jzp820927 下了一天都下载不了，一直卡在0.4那，连速度都没了，也是醉了

**Comment by jzp820927** [comment]
开代理下，github 下载用的是 aws 的服务器，干扰很严重。

**Comment by theratlesnake** [comment]
@jzp820927   厉害，一下子就下载好了，谢谢大神
