### ISSUE TITLE
是否将goagent版本更新至3.2.3最后的正式版？

### ISSUE THREAD

**Issue by ivysrono** [XX-net/XX-Net#459]
目前用的3.1.19，其后的更新日志如下：

【11.22 是否上传：否】 3.2.3 正式版，修复 MacOSX/Linux 平台 CPU 100% 的问题；托盘图标支持设置ADSL拨号网络代理(注意：拨号网络请使用英文名称）。
【11.04 是否上传：否】 3.2.2 正式版， 优化 iplist 筛选算法，降低连接数要求；修复根证书不能导入的 bug。
【10.18 是否上传：否】 3.2.1 正式版， bug 修复，删除默认证书。
【10.02 是否上传：是】3.2.0 正式版，需要重新上传服务端并重启浏览器，如果出现 "Cannot set attribute" 错误，请暂时停用两部验证，并且到 google.com/settings/security 确认"不够安全的应用的访问权限"已启用)。
【08.17 是否上传：否】 3.1.22 正式版，将 GAE 不支持的 HTTP 方法(OPTIONS/PROFIND等)使用 php 或 direct 链接。
【08.08 是否上传：否】 3.1.21 正式版，优化连接方式，修复 php 模式， proxy.ini 支持 urlrewrite 规则

尤其是3.2.1，删除默认证书，这一点对安全性还是有不少提升的。

**Comment by yfdyh000** [comment]
xx-net所用的goagent与原goagent不在一条线上，已改动和增强甚多，并不兼容。

**Comment by Cat7373** [comment]
XX-Net内置的Goagent也是不带证书的，每次自动生成一个新的。

**Comment by simonasd** [comment]
建议：各位懂代码和网络的同仁，还是要紧盯goagent的pull，尤其是在修复漏洞等方面，可以和XX-net进行对比排查。也及时吸收该项目的一些性能更新。

**Comment by xxnet** [comment]
恩，goagent积累了很多年，有很多贡献者，有很多bug的修复会更快。

对于漏洞，在写代码、设计时就尽可能的去考虑到，避免像路由器漏洞那样被劫持，影响范围巨大

在 2015年7月12日 上午11:26，simonasd <notifications@github.com>写道：
