### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by strongant** [XX-net/XX-Net#4592]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:56 good:12
network-status: OK
connected-link: new:0 used:0
worker: h1:9 h2:2
scan-ip-thread-num: 50
ip-quality: 1320
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by SeaHOH** [comment]
win10 请手动设置代理，发 issues 前先搜索。
还有关闭这贴。

**Comment by strongant** [comment]
手动设置完毕需要重启电脑？我手动设置了！
[http://p1.bpimg.com/4851/5382cc7439821d41.jpg](局域网设置)

**Comment by jzp820927** [comment]
先试试能不能用吧，那些提示有时候没影响

**Comment by strongant** [comment]
访问不了，提示检查代理或者dns设置

**Comment by jzp820927** [comment]
那就检查下，证书是否正确导入，代理设置是否正常。

**Comment by strongant** [comment]
终于弄好了，我把扩展从chrome浏览器卸载掉就好了

**Comment by strongant** [comment]
谢谢

**Comment by jzp820927** [comment]
什么扩展？

**Comment by strongant** [comment]
是的

**Comment by strongant** [comment]
季度流量套餐这个是什么内容具体？

**Comment by jzp820927** [comment]
X_TUNNEL 流量
