### ISSUE TITLE
【求助】无限连接可以使用&有线连接无法使用

### ISSUE THREAD

**Issue by loginCanNotBeBlank** [XX-net/XX-Net#4597]
以下是有线连接的诊断说明
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2123
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 546
is-idle: 0
block-stat: OK
**proxy_state: Fail
ca_state: Fail**
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

改为无限网络连接后
这两个字段值变成OK了
proxy_state: OK
ca_state: OK

求助是什么原因

**Comment by jzp820927** [comment]
看看日志
