### ISSUE TITLE
在Mac上，正常使用XX-Net，合上电脑睡眠后，再开机就不能自由访问了

### ISSUE THREAD

**Issue by kelvin7feng** [XX-net/XX-Net#4603]
在Mac上，正常使用XX-Net，合上电脑睡眠后，再开机就不能自由访问了

一般情况是：
我每晚都把电脑合上盖子，让电脑睡眠。
第二天直接就打开电脑，但是这时候，不能自(翻)由(墙)上网了，需要重启XX-NET才可以。

请问这是正常情况吗？如果是，可以优化不？

**Comment by jzp820927** [comment]
应该是系统睡眠的时候，XX进程也结束了，但是系统代理设置没有关闭。造成代理没运行，你上网又走了代理，自然上不了网。建议在系统睡眠之前把 XXNET 正常退出

**Comment by harbenino** [comment]
我第一次部署成功，可以启动XX-Net，退出后再运行start就启动不了XX-Net了，OS 10.12

**Comment by jzp820927** [comment]
系统问题吧？

**Comment by causlayer** [comment]
我的mac没有问题，版本是10.12.1

**Comment by jzp820927** [comment]
没有 mac 机器，无法验证。

**Comment by kelvin7feng** [comment]
把代理设置成Auto GAEProxy就可以了
