### ISSUE TITLE
双击start.bat/start.vbs没有响应，闪一下就没了

### ISSUE THREAD

**Issue by ccccccmd** [XX-net/XX-Net#4605]
双击start.bat/start.vbs没有响应，闪一下就没了，不弹出浏览器，http://localhost:8085也没法访问

没有什么日志

**Comment by jzp820927** [comment]
什么系统

**Comment by ccccccmd** [comment]
win 7 旗舰 64位

**Comment by jzp820927** [comment]
只能 cmd 运行试试了，把杀软那些关了

**Comment by ccccccmd** [comment]
cmd也不起作用，奇怪了，估计是系统的原因。

**Comment by jzp820927** [comment]
我也估计是系统的问题

**Comment by wxbaijun** [comment]
我也是win7 64 旗舰啊  没毛病啊

2016-11-21 17:21 GMT+08:00 天朝屁民 <notifications@github.com>:

**Comment by jzp820927** [comment]
又不是所有的 win7 都有问题。
