### ISSUE TITLE
访问github出问题，不知道大家有没有遇到过

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#4606]
正常访问出现:
![image](https://cloud.githubusercontent.com/assets/7320355/20474101/cdd37ec0-afff-11e6-98de-9443fae0b4f9.png)

![image](https://cloud.githubusercontent.com/assets/7320355/20474081/b054bd5a-afff-11e6-8a30-db90e90f6fe0.png)
只有通过翻墙才可以正常访问github，导致我还需要设置gitconfig，才能让我的sourcetree能正常使用。
不知道是不是被万里长城劫持了呢
另外我在钥匙串中找不到github，正常情况应该是在DigiCert SHA2 Extended Validation Server CA下，我重新下载了DigiCert SHA2 Extended Validation Server CA并安装了
![image](https://cloud.githubusercontent.com/assets/7320355/20474210/70ea1d94-b000-11e6-9927-7bf20ffa33e0.png)
可时间是对不上的，我新安装的是到2028年，我在钥匙串中找不到2018年的这个，不知道有没有朋友遇到过这样的问题，都是如何解决的，谢谢

**Comment by causlayer** [comment]
另外我在使用代理的时候证书显示的时间是2017年，可我实际安装的证书是：
![image](https://cloud.githubusercontent.com/assets/7320355/20474652/8966c398-b002-11e6-82de-f0b96d130aa2.png)
![image](https://cloud.githubusercontent.com/assets/7320355/20474673/a804667a-b002-11e6-953c-a6aaa4e457bd.png)
莫非chrome访问的不是安装的证书，而是自己有自己安装证书的文件夹吗？我用的是macos系统。

**Comment by jzp820927** [comment]
证书问题，都是没有正确导入证书。

**Comment by causlayer** [comment]
@jzp820927 不是双击就安装了吗？给个正确安装方法，谢谢

**Comment by SeaHOH** [comment]
在证书系统中是不会有普通网站证书的，一般只有 CA 之类的证书，遇到未知证书时会根据证书链联网查询。
所以结论：偶然的网络故障，重启浏览器或电脑就好了。
XX 那个是正常的，那是两个证书。

**Comment by causlayer** [comment]
我开始也是以为是正常的网络故障，我清理了缓存，然后重启电脑，还是一个样，刚开始打开的一霎那是安全，然后马上就不安全了，我尝试在另一台电脑上只安装了xx-net，共用一个wifi热点，还是一样。于是我关闭Proxy SwitchyOmega，xx-net，利用iphone的热点连接上网，结果是没问题的
![image](https://cloud.githubusercontent.com/assets/7320355/20481747/ba0eb76e-b023-11e6-956a-f65106895319.png)
这说明就是我IP导致的问题。

**Comment by SeaHOH** [comment]
我这儿是正常的，起码墙没干扰我的证书查询。
你是说手机移动网络正常，而宽带网络不正常？你可以看证书指纹，如果不是下图就是假的。
![githubcrt](https://cloud.githubusercontent.com/assets/8470820/20482273/be7f71e6-b026-11e6-81fa-c9637f8dcc65.png)

**Comment by SeaHOH** [comment]
实在不行通过 XX-Net 代理能上也不影响使用。
ps：我看你第一个图是不是删除了某些系统预装证书？有没有可能删错某些证书。

**Comment by Pekary** [comment]
前段时间进百度也是这个问题,但过了两天又自动好了,不知道什么原因,网上有人说是中间人劫持...

**Comment by causlayer** [comment]
@SeaHOH 
和IP应该没关系直接关系，我做了测试，
如果手机和pc都使用家里的wifi热点，手机可以正常访问，pc则出现问题。
如果手机和pc都使用4g,手机和pc都可以正常访问。
不过有时候也可以正常访问，不过很快就不行了
![image](https://cloud.githubusercontent.com/assets/7320355/20507918/100cc5fa-b099-11e6-938a-3b2b32b04827.png)
我是从digicert的官方网站下载的最新版的证书。

**Comment by causlayer** [comment]
这个回复就是没使用代理发的，时好时坏很无奈啊

**Comment by SeaHOH** [comment]
证书一般不需要自己下载安装，系统或浏览器会自己联网查询。
你发的是两个不同的证书好不好，第二张图是 CA 证书，这个是没问题的。
关键是第一张中的 github.com 的证书，而且是浏览器提示错误时显示的证书，看那个是否是真的证书。

但我觉得真相是你删除了 PC 上某些系统默认证书（完全是根据你最开头那张图中的网址推测），导致证书查询量较多，然后网络干扰又严重，以至验证出错。手机没改过所以正常。

**Comment by causlayer** [comment]
@SeaHOH 昨天我连github不用代理都无法登陆，更无从说起发文章了，我也说了，一阵一阵的，能访问的时候我发了截图是可以正常访问的，所以两个证书不一样，现在访问的时候还是正常，你仔细看我之前回复说的很清楚，“不过有时候也可以正常访问，不过很快就不行了”，我没替换证书之前就没删过证书，也是没法访问，这又怎么说呢，替换而已，不是你所说的删除了某些系统默认证书，也不是你后面说的证书查询量较多的问题，我用另一台电脑打开github也是一样，那台电脑没有安装代理服务也是如此，和你说的没有关系。

**Comment by SeaHOH** [comment]
>关键是第一张中的 github.com 的证书，而且是浏览器提示错误时显示的证书，看那个是否是真的证书。

当然是要看错误的时候的信息，正常时怎么可能看出问题。证书是否一致**不是**看浏览器显示的状态，而是**指纹**。如果一致就是网络问题，不一致就是中间人劫持（但是失败了）。
确认一下：
你一台替换过证书和另一台没替换过证书的电脑都会在宽带连接时间隙性的发生这个错误。

**Comment by causlayer** [comment]
@SeaHOH 替换与没替换证书的两台电脑在相同宽带连接下发生同样的错误。

**Comment by SeaHOH** [comment]
应该没跑了，就按上一条来检查。

**Comment by jzp820927** [comment]
不会是你网络不稳定吧

**Comment by SeaHOH** [comment]
非常可能，因为如果墙要劫持你应该不会失败，不然就没意义了。

**Comment by jzp820927** [comment]
说的是，劫持的话，表面上说看不出来的，这种情况就属于失败的劫持了。

**Comment by causlayer** [comment]
不使用xx-net时DigiCert SHA2 Extended Validation Server CA证书的状态，分别来自钥匙串和网页:
![image](https://cloud.githubusercontent.com/assets/7320355/20525536/dfc7335a-b0fa-11e6-8126-652c6e6e2a57.png)
![image](https://cloud.githubusercontent.com/assets/7320355/20525538/e4859b20-b0fa-11e6-8b1a-23f4e86ad95d.png)
使用xx-net时GoAgent XX-Net证书的状态，分别来自钥匙串和网页:
![image](https://cloud.githubusercontent.com/assets/7320355/20525577/105e3f36-b0fb-11e6-9e56-689d9f8404c2.png)
![image](https://cloud.githubusercontent.com/assets/7320355/20525580/165fae6a-b0fb-11e6-875b-1f577a6beb76.png)
不使用xx-net调用DigiCert SHA2 Extended Validation Server CA证书，不使用调用GoAgent XX-Net证书。

**Comment by SeaHOH** [comment]
没看懂吗？不使用代理，被报错警告的网页证书。
我觉得写得很明白了，就这样。

**Comment by causlayer** [comment]
@SeaHOH 晕，这四张图没有一张是报错的状态的证书。

**Comment by jzp820927** [comment]
换个浏览器试试？

**Comment by SeaHOH** [comment]
好吧，虽说指纹截图不完整，但应该是一样的。网络问题。

**Comment by causlayer** [comment]
时好时坏，就是长城捣鬼的，没什么事，我用safari和Firefox也一样，chrome能不翻墙打开，其他两个浏览器也都能。我早就测试过了。麻烦点而已，不是什么大事，以后有相同问题的朋友看到这个帖子就不会着急了，这里已经分析的很清楚了。谢谢SeaHOH的热心回复。
