### ISSUE TITLE
咨询一个问题，firefox不添加PAN插件不能使用？

### ISSUE THREAD

**Issue by HWalt** [XX-net/XX-Net#4610]
XX net3.2.7的版本。firefox50 win10 64位
如果从右下角托盘中选择”全局PAC智能代理“firefox中就无法使用，状态页显示请检查浏览器代理设置。但是装上pan插件并使用就没有这个问题。
相同情况下chrome就没有这个问题。

**Comment by yeahwu** [comment]
去wiki看看，火狐要填入pac地址。
HWalt <notifications@github.com>于2016年11月22日 周二11:44写道：

**Comment by HWalt** [comment]
浏览器的代理PAC设置已经填过了。系统的代理地址也改了。唯一的问题就是，没有PAN插件就不能用，加上pan插件就可以用。

**Comment by CHN008** [comment]
我firefox50 win7 64位,不用插件有些网站就不能打开.发现必须用pan插件来打开.
以前直接xx-net的pac智能代理就好. 应该是Firefox 50.0的一个Bug吧.
所以我又换回Firefox 49.02了.

**Comment by jzp820927** [comment]
为啥我的 ff 50 没有这个问题呢，直接在 ff 设置 pac，不用代理插件，可以正常代理。

**Comment by HWalt** [comment]
@CHN008  不知道哎，是不是俩个的智能代理规则不一样。

**Comment by HWalt** [comment]
@jzp820927   已经解决，Internet选项里面的局域网设置，代理选自动，不要改成pac地址就可以了。我是这个问题。
