### ISSUE TITLE
XX-net 访问Vimeo显示You Have Been Banned

### ISSUE THREAD

**Issue by Askwind** [XX-net/XX-Net#4613]
## 问题内容
1. 本人系统为Win10+chrome54+XXnet3.2.7。
2. 访问www.Vimeo.com 显示You Have Been Banned。
3. 请问是XXnet（GAE）被GFW盯上了？还是Vimeo的问题？
如何解决呢？
请各位不舍赐教。

**Comment by jzp820927** [comment]
赶脚上好像是 vimeo 封锁了 GAE IP 的访问？

**Comment by Askwind** [comment]
还有有救吗？或者换点ip pool试试看？

**Comment by jzp820927** [comment]
换 IP，没用，vimeo 不是可以直连麽？

**Comment by Askwind** [comment]
只能期待解禁或者其他大神想其他方法了。
