### ISSUE TITLE
请问Mac下XX-Net如何共享给iOS用？

### ISSUE THREAD

**Issue by vvzwvv** [XX-net/XX-Net#4618]
我Mac可以正常用，然后按照其他贴子里的做法将manual.ini文件放在./data/gae_proxy里面后，Mac的XX-NET都用不了了，想问下这是什么原因？

XX-NET版本：3.2.8
Mac版本：10.12.1

manual.ini内容：
[listen]
ip = 192.168.1.101
port = 8087

[gae]
appid = xx-net-147209
password =

[pac]
enable = 1
ip = 192.168.1.101
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by jzp820927** [comment]
把 2处
ip = 192.168.1.101
改为
ip = 0.0.0.0

**Comment by vvzwvv** [comment]
原来如此。搞定，多谢！
