### ISSUE TITLE
通过端口转发让移动设备使用XX-Net，无法访问SSL网站

### ISSUE THREAD

**Issue by gam2046** [XX-net/XX-Net#462]
我通过端口转发的方式，让移动设备（iPad）通过电脑上的XX-Net帮助，成功翻越大墙。
可是我发现无论如何都无法访问基于SSL的网站（不出意外是证书问题）。而且我查阅的相关设置，似乎ipad上并没有类似电脑的设置，可以忽略SSL的校验。请问有其他方法可以变通么。
Sarari提示：There was a problem communicating with the secure web proxy server (HTTPS).

**Comment by simonasd** [comment]
用Sarari访问 http://电脑的局域网地址:8086/CA.crt，下载下来之后就可以看到安装证书的界面了。但似乎作用范围仅限于Sarari，没有进一步测试。

**Comment by gam2046** [comment]
感谢你的答复。
首先、XX-Net默认只监听来自本地的（127.0.0.1）对8086/8087端口的请求（通过netstat -an -p tcp得知），因此局域网内其他设备需要通过他，需要在电脑上端口转发。
其次，对于你所述的方式，我进行了尝试，在iOS设备（就我而言是iPad），确实导入证书后，没有问题了。不过对于Android设备（Android 4.x、5.x均尝试过），一样提示证书不可信，但是在Android中可以忽略，就是需要不停的点“继续”访问，比较麻烦。此外，在电脑中，导入该证书，在IE/Firefox中都是可用的，可是到Chrome里，也说证书不可信，原因不明（Chrome导入证书的设置是等同于IE的）

**Comment by simonasd** [comment]
@gam2046 因为一直在各种平台切换，用各种工具，记忆可能有一点混乱，姑妄言之。我记得可以修改proxy.ini，让XX-Net的监听从127.0.0.1改为0.0.0.0，局域网内就可以直接用IP+端口的形式访问了。（与goagent类似）

印象中安卓和win的Chrome，在设置中都能找到证书相关选项，如果始终提示不信任，不妨检查一下，也许Chrome使用的是一套独立的证书存储？

顺便提一下，我的习惯是导入证书之后清理浏览器缓存然后重启系统。（恶俗了:P）

**Comment by zhout26** [comment]
@gam2046 I have solved this issue by adding listen 0.0.0.0 in manual.ini.

**Comment by yumenkun** [comment]
你好！请问一下可否告知如何设置端口转发实现wifi分享，或者我笔记本已经可以分享wifi 但是ipad连还是翻不了墙请问知道方法吗，谢谢~

**Comment by jzp820927** [comment]
端口转发比较复杂，建议通过直接在 wifi 设置 pac 的方式代理。

**Comment by gam2046** [comment]
@yumenkun 可以自己修改pac生成规则，把默认的127.0.0.1改成你笔记本的内网地址，然后让软件监听0.0.0.0，最后在iPad上使用pac代理即可（我的老iPad2可以设置pac模式，连接WIFI在点击后边向右的箭头即可）
