### ISSUE TITLE
能上外网，但是浏览器代理和ca证书状态都显示fail

### ISSUE THREAD

**Issue by chichuyun** [XX-net/XX-Net#4633]
这是诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2799
network-status: OK
connected-link: new:0 used:0
worker: h1:40 h2:3
scan-ip-thread-num: 50
ip-quality: 437
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by chichuyun** [comment]
刚更新了win10，和这个有关系吗

**Comment by SeaHOH** [comment]
Ctrl+F5 刷新，这是缓存 bug。
