### ISSUE TITLE
关于新扫到的ip会替换掉handshake_time比较高的ip时的疑问

### ISSUE THREAD

**Issue by XueLongHui** [XX-net/XX-Net#4634]
@jzp820927 您好，请问当我已经扫够3000可用ip时，新扫到的ip会替换掉handshake_time比较高的ip，比如这样的：Nov 26 10:59:34.375 - [INFO] scan_ip add ip:202.28.85.240 time:325
Nov 26 10:59:34.386 - [INFO] remove_slowest_ip:201.157.200.32 handshake_time:891, fails:0
那么，被替换掉的ip会不会在某个文件中存储起来，当我的ip量不够时，优先从这个文件中找ip进行扫描，如果没有这个文件的话，建议加入一下这个功能（不过听你说X大好像最近已经不进行功能性的增加了， /(ㄒoㄒ)/~~），谢谢

**Comment by yaoguaishou** [comment]
我感觉没什么必要，ip段就够了
如果你想要多ip，修改一下配置文件
`max_good_ip_num = 999999999`

**Comment by XueLongHui** [comment]
好的，谢谢
