### ISSUE TITLE
如何走XX-NET流量下载文件？

### ISSUE THREAD

**Issue by FlyingFishF** [XX-net/XX-Net#4637]
电脑小白，在google上下载文件时发现速度很慢，估计是代理没有起作用，如何走XX-NET流量下载文件呢？
望大神不吝赐教，感谢！

**Comment by wenliyang** [comment]
你通过 XX-Net 可以访问 Google 等被墙网站么，可以的话，就是代理起作用了，可以下载了
下载速度慢是因为最近干扰严重，暂时没有好的解决办法

**Comment by NAVrasZ** [comment]
发现有时貌似只是使用了google的dns，下载慢试试开全局代理，但有的文件即使用代理下还是很慢...

**Comment by jzp820927** [comment]
最近干扰严重，所以影响了 GAE 的速度
