### ISSUE TITLE
写了一个过滤响应过慢的工具

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#4649]
`
package com.test;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;

public class IpFlterUtil {
	public static void main(String[] args) throws Exception {
		//最大超时时间
		final int MAX_OVER_TIME = 1000;
		
		String directoryPath = "/Users/AbrahamLee/Documents/Projects/XX-Net-master/data/gae_proxy/";
		String filePath = directoryPath + "good_ip.txt";
				
		File file = new File(filePath);
		if(!file.exists() || file.isDirectory()){
			System.out.println("文件不存在！");
			return;
		}
			
		InputStream inputStream = new FileInputStream(file);
		OutputStream outputStream = new FileOutputStream(filePath+System.currentTimeMillis()+".bak");
		
		byte[] data = new byte[1024];
		int flag = -1;
		while((flag = inputStream.read(data)) != -1){
			outputStream.write(data);
		}
		
		outputStream.flush();
		outputStream.close();
		outputStream.close();

		BufferedReader bf = new BufferedReader(new FileReader(file));
		
		List<String> lineList = new ArrayList<String>();
		
		String line = null;
		int temp;
		while ((line = bf.readLine()) != null) {
			try {
				temp = Integer.parseInt((line.substring(line.indexOf("gws")+4, line.indexOf(" ", line.indexOf("gws")+4))).trim());
				if(temp <= MAX_OVER_TIME)
					lineList.add(line);
			} catch (Exception e) {
				continue;
			}
		}
		
		bf.close();
		
		file.delete();
		
		BufferedWriter bw = new BufferedWriter(new FileWriter(filePath));

		for (String string : lineList) {
			bw.write(string);
			bw.newLine();
		}
		
		bw.close();
		System.out.println("End");
	}
}
`
java实现，过滤响应时间过长，地址配成自己的，时间根据自己的需求改

**Comment by andylee1890** [comment]
`package com.test;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;

public class IpFlterUtil {
	public static void main(String[] args) throws Exception {
		//最大超时时间
		final int MAX_OVER_TIME = 1000;
		
		String directoryPath = "/Users/AbrahamLee/Documents/Projects/XX-Net-master/data/gae_proxy/";
		String filePath = directoryPath + "good_ip.txt";
				
		File file = new File(filePath);
		if(!file.exists() || file.isDirectory()){
			System.out.println("文件不存在！");
			return;
		}
			
		InputStream inputStream = new FileInputStream(file);
		OutputStream outputStream = new FileOutputStream(filePath+System.currentTimeMillis()+".bak");
		
		byte[] data = new byte[1024];
		int flag = -1;
		while((flag = inputStream.read(data)) != -1){
			outputStream.write(data);
		}
		
		outputStream.flush();
		outputStream.close();
		outputStream.close();

		BufferedReader bf = new BufferedReader(new FileReader(file));
		
		List<String> lineList = new ArrayList<String>();
		
		String line = null;
		int temp;
		while ((line = bf.readLine()) != null) {
			try {
				temp = Integer.parseInt((line.substring(line.indexOf("gws")+4, line.indexOf(" ", line.indexOf("gws")+4))).trim());
				if(temp <= MAX_OVER_TIME)
					lineList.add(line);
			} catch (Exception e) {
				continue;
			}
		}
		
		bf.close();
		
		file.delete();
		
		BufferedWriter bw = new BufferedWriter(new FileWriter(filePath));

		for (String string : lineList) {
			bw.write(string);
			bw.newLine();
		}
		
		bw.close();
		System.out.println("End");
	}
}
`

**Comment by andylee1890** [comment]
格式没调好

**Comment by jzp820927** [comment]
不明觉厉，什么作用？过滤延迟时间？

**Comment by chenkaicheng** [comment]
怎么用？

**Comment by andylee1890** [comment]
goog_ip.txt里记录了延迟时间，根据延迟时间把过慢的去除掉

**Comment by jzp820927** [comment]
好像作用不大，XX会自动使用延时低的IP
