### ISSUE TITLE
你好，

### ISSUE THREAD

**Issue by panzer1313208** [XX-net/XX-Net#4654]
@jihaixiao8 你好，听说你的蓝灯不好用，并且卸载了？可否把帐号发给我，让我试试pro？我没买过pro不知道怎么样。

**Comment by jzp820927** [comment]
我去

**Comment by panzer1313208** [comment]
@jzp820927 噫，你是怎么进来的，主题不是被我关闭了吗

**Comment by jzp820927** [comment]
关贴又不是删帖，有啥不能进的

**Comment by panzer1313208** [comment]
@jzp820927 可是外面不是看不到帖子了吗？

**Comment by jzp820927** [comment]
notifications 有通知

**Comment by panzer1313208** [comment]
@jzp820927 可以，这很强势，话说怎么弄可以告诉我么？

**Comment by jzp820927** [comment]
不要给我说，你不知道

**Comment by panzer1313208** [comment]
@jzp820927 我并不会用github= =

**Comment by jzp820927** [comment]
好吧，这个问题就不讨论了，game over！
