### ISSUE TITLE
最近速度变慢了呢

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#4656]
ip数量也在下滑，墙又增高了？

**Comment by Temmie-hOi** [comment]
似乎我这边整体外国网站的速度都变慢了，不管要不要翻GFW，上海电信

**Comment by jzp820927** [comment]
整体国际流量受到严重干扰和丢包，所以，就这样了

**Comment by mirifem** [comment]
是的。以往xx-net是我主力，720P都能看，现在改成ss了。山东联通

**Comment by jzp820927** [comment]
ss，自建？收费？

**Comment by sandove** [comment]
最近一两周是感觉慢了不少

**Comment by jzp820927** [comment]
现在强化干扰，不慢，那还不正常了。

**Comment by mirifem** [comment]
自建的ss服务器，一直是手机上的主力。偶尔用gfw.press备胎。

**Comment by jzp820927** [comment]
还是自建的靠谱

**Comment by Temmie-hOi** [comment]
自建ss服务器怎么弄啊，然后资费大概多贵？

**Comment by jzp820927** [comment]
很简单，自己买个 VPS 就行了

**Comment by Temmie-hOi** [comment]
有什么vps推荐吗

**Comment by SeaHOH** [comment]
小日本有无限流量的包月，九十多 rmb，自己搜。

**Comment by SeaHOH** [comment]
小日本有无限流量的包月，九十多 rmb，自己搜。

**Comment by jzp820927** [comment]
邮件连击，为什么我连击不了

**Comment by SeaHOH** [comment]
我这儿有些时候访问 github 很慢，所以 github.com 域名是通过 GAE 代理的，然后就会抽风。
也有见过其他人连击，估计情况一样。

**Comment by jzp820927** [comment]
额，原来是走 GAE，我是直接访问。看来是 GAE 造成的？？

**Comment by SeaHOH** [comment]
GAE 不是根本原因，丢包严重才是根源。
github 在确认**收不到**请求反馈时（实际上已到达服务器，只是返回时断掉了）会尝试重新请求。

**Comment by jzp820927** [comment]
我这儿掉包也挺严重的，经常半天打不开 github。好吧，希望哪天我也能遇到连击。

**Comment by JohnYinlubin** [comment]
哎，我原来1080youtube都没问题，昨天电脑和xx-net都出了点问题，只能看720了~

**Comment by jzp820927** [comment]
我去，720，你还不满足？我只要 480 不卡，我就谢天谢地了。。。
