### ISSUE TITLE
win10下托盘图标的右键菜单无法切换

### ISSUE THREAD

**Issue by luantu** [XX-net/XX-Net#4658]
升级到win10 14965之后，托盘图标的右键菜单无法切换了。。。不论怎么操作，勾选的项都是取消全局代理。。

**Comment by jzp820927** [comment]
WIN 10 问题较多，自己手动设置一下代理吧

**Comment by SeaHOH** [comment]
win10 相关问题报告过多次了，为什么发帖前都不喜欢搜索一下呢？

**Comment by luantu** [comment]
同 #4371
