### ISSUE TITLE
前置没有https？

### ISSUE THREAD

**Issue by NAVrasZ** [XX-net/XX-Net#4660]
另外一个bug，配置界面点保存2次就会卡住“等待后台检验有效性什么的”，然后再点xx的图标，UI界面的显示也从edge变为ie，需退出重开

**Comment by jzp820927** [comment]
将就用吧，已经没人维护了，再说配置界面又不用经常进，也就最开始用的时候，要配置一下，我都好久没进过配置界面了。

**Comment by NAVrasZ** [comment]
@jzp820927 233好吧，话说没有https前置的选项直接改manual也无效吗？

**Comment by jzp820927** [comment]
公开的代理，基本上以 http 和 socks 为主，基本上没 https 代理，如果你说的 https 代理，是指的 http connect 的话，是支持的。

**Comment by NAVrasZ** [comment]
@jzp820927 
https://github.com/phuslu/goproxy/issues/373
嘛~就是这里发的一堆https前置
大大所说http connect是指用http代理上https网站？

**Comment by jzp820927** [comment]
那个 https 前置，其实就是 http 代理，只不过支持用 connect 方法代理 https，所以也可以叫 https 透明代理。你就当 http 代理用就行了。

**Comment by jang-u** [comment]
没人维护是作者出事了？

**Comment by jzp820927** [comment]
难道没维护，就是出事了？不能有自己的私事麽？

**Comment by NAVrasZ** [comment]
问题解决了，issue要关吧~
