### ISSUE TITLE
总是提示”您应该考虑开启 IP 扫描器“，然而我的是自动最大17线程，无效

### ISSUE THREAD

**Issue by AingW** [XX-net/XX-Net#4672]
如题，完全连不上网，重启xx-net或者电脑都没有用

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
你是 IPV6 网络？

**Comment by AingW** [comment]
然而我之前就用得好好的，突然不知怎么了就不行用ipv6了，（我支持，拥有ipv6网）；不过，切换回v4后就好了

**Comment by jzp820927** [comment]
IPV6 是用的程序内默认的 IP 库，而且不开启扫描，有可能是默认的 IP 库都被封了，可以试试自己在 
code/default/gae_proxy/local/good_ipv6.txt 文件里面更换新的可用IP段

**Comment by AingW** [comment]
十分感谢，我这就去试一试\^o^/

**Comment by matduniverse** [comment]
请问楼主你现在解决这个问题了吗？我也遇到了一样的事，ipv6下无效。

**Comment by jzp820927** [comment]
日志发来看看

**Comment by matduniverse** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-8-6.2.9200-SP0
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:6-2; Build:9200; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


Dec 15 07:20:26.981 - [WARNING] no enough ip
Dec 15 07:20:27.483 - [WARNING] no enough ip
Dec 15 07:20:27.984 - [WARNING] no enough ip
Dec 15 07:21:18.460 - [DEBUG] create ssl timeout fail.
Dec 15 07:21:28.140 - [DEBUG] GAEProxy web_control 127.0.0.1:54867 POST /config?cmd=get_config
Dec 15 07:21:30.738 - [DEBUG] GAEProxy web_control 127.0.0.1:54865 POST /config?cmd=get_config
Dec 15 07:21:30.739 - [DEBUG] GAEProxy Web_control 127.0.0.1:54867 GET /scan_ip?cmd=get_range
Dec 15 07:21:30.739 - [INFO] load ip range file:G:\XX-Net-master\data\gae_proxy\ip_range.txt
Dec 15 07:21:32.498 - [DEBUG] GAEProxy Web_control 127.0.0.1:54867 GET /scan_ip?cmd=get_scan_ip_log
Dec 15 07:22:18.461 - [DEBUG] create ssl timeout fail.
Dec 15 07:22:18.462 - [WARNING] no enough ip
Dec 15 07:22:18.964 - [WARNING] no enough ip
Dec 15 07:22:19.465 - [WARNING] no enough ip
Dec 15 07:22:19.966 - [WARNING] no enough ip
Dec 15 07:22:20.468 - [WARNING] no enough ip
Dec 15 07:22:20.968 - [WARNING] no enough ip

**Comment by C4DFAN** [comment]
scan-ip-thread-num: 0
这个是在说IP扫描进程是0？

2016-12-15 7:24 GMT+08:00 matduniverse <notifications@github.com>:

**Comment by jzp820927** [comment]
日志太少了，你看看日志里面有没有下面这样的内容：
[WARNING] IPv6 was enabled, but check failed.

**Comment by matduniverse** [comment]
没有check failed的提示，基本全都是no enough ip。
 
Dec 15 10:06:27.200 - [WARNING] no enough ip
Dec 15 10:06:27.702 - [WARNING] no enough ip
Dec 15 10:06:28.202 - [WARNING] no enough ip
Dec 15 10:06:29.989 - [DEBUG] GET http://www.twitter.com/xxnet
Dec 15 10:06:29.990 - [DEBUG] GET http://www.twitter.com/xxnet
Dec 15 10:06:30.065 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Dec 15 10:06:31.161 - [DEBUG] GET http://www.twitter.com/xxnet
Dec 15 10:06:31.161 - [DEBUG] GET http://www.twitter.com/xxnet
Dec 15 10:06:31.350 - [DEBUG] GAE POST https://s808.searchelper.com/related
Dec 15 10:06:31.352 - [DEBUG] GAE POST https://s1808.searchelper.com/service2
Dec 15 10:06:32.552 - [DEBUG] GAE POST https://s1808.searchelper.com/service2
Dec 15 10:06:32.622 - [DEBUG] GAEProxy web_control 127.0.0.1:58322 POST /config?cmd=get_config
Dec 15 10:06:32.624 - [DEBUG] GAEProxy Web_control 127.0.0.1:58322 GET /scan_ip?cmd=get_range
Dec 15 10:06:32.624 - [INFO] load ip range file:G:\XX-Net-master\data\gae_proxy\ip_range.txt
Dec 15 10:06:32.675 - [DEBUG] GAE POST https://s808.searchelper.com/related
Dec 15 10:06:33.004 - [DEBUG] GAE POST https://s1808.searchelper.com/service2
Dec 15 10:06:33.329 - [DEBUG] GAE POST https://s808.searchelper.com/related
Dec 15 10:06:40.300 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=x9bN99CEBzLuMPHwynGvug%3D%3D
Dec 15 10:07:01.448 - [DEBUG] GAE POST https://api.github.com/_private/browser/stats
Dec 15 10:07:18.665 - [DEBUG] create ssl timeout fail.
Dec 15 10:07:31.352 - [DEBUG] create ssl timeout fail.
Dec 15 10:07:31.352 - [DEBUG] GAE_Exception 1 'no ssl_sock'
Dec 15 10:07:31.352 - [WARNING] get worker fail:GAE_Exception()
Dec 15 10:07:31.352 - [DEBUG] response_fail:get worker fail:GAE_Exception()
Dec 15 10:07:31.352 - [DEBUG] GAE_Exception 601 'fetch gae fail:601'
Dec 15 10:07:31.353 - [WARNING] gae_exception:GAE_Exception() https://s808.searchelper.com/related
Dec 15 10:07:31.353 - [DEBUG] GAE_Exception 600 'gae_exception:GAE_Exception() https://s808.searchelper.com/related'
Dec 15 10:07:31.353 - [WARNING] GAE POST https://s808.searchelper.com/related request fail:GAE_Exception()
Dec 15 10:07:31.355 - [WARNING] no enough ip
Dec 15 10:07:31.855 - [WARNING] no enough ip
Dec 15 10:07:32.355 - [WARNING] no enough ip
Dec 15 10:07:32.856 - [WARNING] no enough ip
Dec 15 10:07:33.358 - [WARNING] no enough ip
Dec 15 10:07:33.859 - [WARNING] no enough ip

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4691
按照这个 issues 的方案改一下，看看行不行。

**Comment by matduniverse** [comment]
改了py文件，还是无效。依然提示“您应该考虑开启 IP 扫描器”

**Comment by jzp820927** [comment]
IPV6，是XX默认不需要开启扫描的。

**Comment by matduniverse** [comment]
是不是还是因为ipv6地址不够的问题

属性	值
本地网络状态	OK
IP数量	0
空闲	0
IP延迟	9999
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	0
屏蔽状态(帮助)	OK

**Comment by jzp820927** [comment]
你的 IPV6 网络没啥问题吧？

**Comment by matduniverse** [comment]
6v、kame、ipv6google都能正常打开，应该不是网络问题

**Comment by jzp820927** [comment]
看日志，好像是没有扫到可用的 IP。

**Comment by matduniverse** [comment]
我找过的扫IP工具都只有扫ipv4的，请问ipv6该怎么扫？

**Comment by SeaHOH** [comment]
IPv6 目标太多，没人做这个。
可以解析各个谷歌域名，取其中的 v6 地址，按 `good_ipv6.txt` 原本格式替换进去。
多解析几次， IP 就多了。

**Comment by jzp820927** [comment]
确实好像还真没有扫 IPV6 的工具，既然你是IPV6 的网，自己 nslookup 一些 google 的域名，放进去应该可以。不确定直接解析出来的 IPV6 有没有被封。

**Comment by matduniverse** [comment]
。。。我把good_ipv6.txt里面十几批地址都重新换了，ip数量还是0。ping出来的地址延迟二三百毫秒，应该在可接受范围内吧，怎么gae还是毫无反应

**Comment by jzp820927** [comment]
ping 试不出来，要测试 443 端口。

**Comment by SeaHOH** [comment]
把以前的全部删除，新加入的要按原先格式，话说1万2居然都不行，你的网络可能有限制。
```
ip 域名(随便写) gws 延迟(数字) 0
2a00:1450:4009:3b::19 r20---sn-aigllnsl.googlevideo.com gws 300 0
```

**Comment by jzp820927** [comment]
我也觉得他的 IPV6 网络是不是有问题，别人的 IPV6，随随便便都是 几千上万的，还是第一次见到 IPV6 网络日志报 [WARNING] no enough ip 错误的

**Comment by matduniverse** [comment]
我晕，闹了半天原来是文件上出了问题。我一直在修改的good_ipv6.txt是code\default\gae_proxy\local目录下的。刚才搜索了一下，data\gae_proxy目录下也有个good_ipv6.txt，然后这个txt是0字节。。。把前者copy到后者里面，立马正常了。真不知道后面这个good_ipv6.txt怎么会变成0字节的。
感谢两位大神，陪我为这么乌龙的事思考解决方案。。。感觉真是对不住。

**Comment by jzp820927** [comment]
原来 data\gae_proxy 里面也有 good_ipv6.txt 文件，没有 IPV6 网络表示，不知情。

**Comment by simonasd** [comment]
IPV6的扫描当年曾经想要做一个，但因为用户比较少，各位开发者又无一具备原生IPV6环境，最终作罢。

之前自带的IPV6地址整理方式，也许可供参考：通过各种途径解析ipv6.google.com等域名得到V6 ip，结合网络上收集到的各类IPV6 host，使用GoGo Tester之类的工具进行测速。

**Comment by jzp820927** [comment]
GoGo Tester 还能测 IPV6？这个真不知道

**Comment by simonasd** [comment]
@jzp820927 测速的工作我没有参与（没有IPV6环境），所以具体是不是这个工具，要打一个问号。有环境的朋友不妨试试。

**Comment by jzp820927** [comment]
好吧，确实我这儿也没 V6 环境，所以比较诧异。只能坐等 V6 的测试结果了。
