### ISSUE TITLE
mediafire无法下载

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#4673]
gae模式下到32m卡死，xtunnel下完全下不动

**Comment by jzp820927** [comment]
GAE 的限制，估计你只能用其他代理下了。

**Comment by SeaHOH** [comment]
加入多线程规则就好，可以避开 32M 限制。

**Comment by jzp820927** [comment]
不知道 mediafire 支不支持 autorange

**Comment by tommyclerk** [comment]
@SeaHOH 怎么加入多线程规则？

**Comment by jzp820927** [comment]
proxy.ini 里面好像 autorange 的相关配置，只有 
threads = 20
maxsize = 548576
 其他都被省掉了。

**Comment by SeaHOH** [comment]
嗯，我搞错了。XX-Net 强制所有超过 maxsize 的请求都使用多线程。
但是这就有问题了，你为什么会卡在 32M？说不通啊，要么直接失败，要么成功下载。

**Comment by SeaHOH** [comment]
嗯，我搞错了。XX-Net 强制所有超过 maxsize 的请求都使用多线程。
但是这就有问题了，你为什么会卡在 32M？说不通啊，要么直接失败，要么成功下载。

**Comment by jzp820927** [comment]
赶脚 GAE 代理在下载方面问题太多了。
