### ISSUE TITLE
在paypal上购买了x-tunnel一年,多久能显示流量到账？

### ISSUE THREAD

**Issue by topstarxxx** [XX-net/XX-Net#4682]
嗯，如标题所言。本人注册的x-tunnel ID是 topstarxxx@gmail.com

---

##为什么购买x-tunnel
从最初的goagent到xx-net，体验在越变越好。看到xx-net推出了x-tunnel这么久了，决定支持一下。

---

##支付到账的问题
打开购买套餐，有两档，选了一个一年的，用paypal支付了。回到xx-net下，刷新了一下x-tunnel的‘**历史**’标签，？只显示了一个注册的信息，再看‘**信息**’标签下流量还是1.00MB，充值那里也还是0。
我退出账号重新登录了一遍，还是0，嗯，看来是遇到问题了。想请教一下，为什么流量没有到账。

---

##用户服务问题
1. 这个到账是即时到账吗？
2. 这个付款的体验相当不人性化，也没有‘付款遇到问题/客服’这一类的联系方式，未来能否来解决一下呢？
3. 希望x-tunnel这个功能能有独立的页面，和客服联系方式。

![recipes](https://cloud.githubusercontent.com/assets/24417538/20939171/b3d2dcb6-bc28-11e6-9b67-7c093ee7797c.jpg)

**Comment by topstarxxx** [comment]
> Dec 07 03:06:48.199 - [DEBUG] x-tunnel web_control 127.0.0.1:56373 POST /login
> Dec 07 03:06:48.473 - [INFO] api:login success t:274
> Dec 07 03:06:48.473 - [WARNING] no quota
> Dec 07 03:06:48.473 - [INFO] update xt_server 104.207.140.47:6666
> Dec 07 03:06:48.473 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:0.000000
> Dec 07 03:06:48.748 - [WARNING] login_session time:273 fail, res:2 msg:no quota
> Dec 07 03:06:48.748 - [WARNING] x-tunnel session not start

现在都没有配额了no quota balance 000000，无法登录

**Comment by topstarxxx** [comment]
1小时内到账。
已到账。

**Comment by thexplorer** [comment]
要是能够支付宝支付就好啦

**Comment by jzp820927** [comment]
支付宝支付这个不安全，主要是要考虑安全问题。
