### ISSUE TITLE
求试用x_tunnel流量，ioupkutter@gmail.com

### ISSUE THREAD

**Issue by UchihaKutter** [XX-net/XX-Net#4683]
求试用x_tunnel流量，ioupkutter@gmail.com

**Comment by jzp820927** [comment]
去 https://github.com/XX-net/XX-Net/issues/1977 找 @pnjgyl ，专门发流量的。

**Comment by pnjgyl** [comment]
ioupkutter@gmail.com 5G已转 请查收 (ps, 感谢 jzp at我)

**Comment by jzp820927** [comment]
原来加个 @uid ，还有提醒作用？瞬间感觉又学到了很多咚咚。

**Comment by pnjgyl** [comment]
@jzp820927  233 我也是被你在别的issue里at了, 才发现的

**Comment by jzp820927** [comment]
好吧，看来还是要引用 issues 才行，我还以为直接 at 你，你就能收到。

**Comment by UchihaKutter** [comment]
非常感谢 @jzp820927

**Comment by UchihaKutter** [comment]
非常感谢 @pnjgyl
