### ISSUE TITLE
关于switchyomega

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#4684]
![image](https://cloud.githubusercontent.com/assets/14359560/20959624/dce0cd5c-bc96-11e6-991a-bbf795b54360.png)
如图所示，不知道大家有没有出现这个问题。
好几天没有网，所以没有用，今天一打开发现就变成这样了，卸载后重新安装扩展，刚开始还好，过了一会发现又是这样了。

**Comment by jzp820927** [comment]
看提示，好像是同步的问题。你的同步是开着的，还是关着的。

**Comment by zzgpku** [comment]
应该是开着的吧，没关注过它

**Comment by jzp820927** [comment]
那就关了试试，可能是有 BUG

**Comment by jzp820927** [comment]
再不行，就删了，重新安装官方版本。不要导入，bak，自己手动新建规则。

**Comment by zzgpku** [comment]
没法关，只好重新安装了

**Comment by zzgpku** [comment]
然并卵。。。过了一会又变成那样了，就这样吧，不管了。。。
