### ISSUE TITLE
关于start.*的文件名的小建议

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net#469]
XX-Net根目录下共有5个名为start.*的文件，一开始看着着实眼花，建议调整一下文件名。

这个主要出于提升win下小白用户的体验考虑，因为很多小白用户的系统是不显示后缀名的。（至于Linux狗嘛，肯定不至于找不到*.sh的，您就不用管我们了，哈！）

补充：我给小白用户做启动器，基本上是这样子命名的：
windows用户运行这个.exe
mac用户运行这个.command
Linux.sh
（当个笑话讲，哈，请忽略这部分）

辛苦了 : )

**Comment by Cat7373** [comment]
这个建议不错的感觉- -
不过名字不知道到底起什么好呢- -

**Comment by simonasd** [comment]
@Cat7373 是啊，而且Linux下中文总是会在不经意间带来一些问题。不过我是觉得，不用太担心Linux用户，根目录下有且仅有一个start.sh，应该都能明白。

至于windows平台，我觉得真可以搞一个“点此开始”之类的名字。就像游民星空打包游戏都会加上一个“开始游戏.exe”——当然了他们并不仅仅是为了方便用户。

**Comment by Cat7373** [comment]
我觉得名字还是由@XX-Net来想吧- -
我起名一直很废。。。

**Comment by simonasd** [comment]
@Cat7373 恩，现在我只希望issues区不要被所谓“你国特色”淹没。不看代码就阴谋论，以及指责一个contributor啥都不懂，这样的事情不应该发生在Github。（这个网站还没有中文界面呐！也许我们应该引导广大用户到Google group去讨论比较好，这里留给程序猿）

**Comment by Cat7373** [comment]
Github可以不翻墙上，只是慢一些
但是Google group可是需要翻墙了

**Comment by simonasd** [comment]
@Cat7373 确实。
<br>
很久不来Github了，看到goagent的issues区关闭了，肝颤，再去Google code那边的goagent issues看看，乱得一塌糊涂。有些事情可以想象。

**Comment by internetic** [comment]
曾今非常反感所谓“中国特色”，现在理解的更深入了。
在群盲头脑之间根本没有公民意识的今天，中国这片土地上发生任何事情都不足为奇
大政府的存在确实有其理由
不为任何事出头，仅仅作为一个引导者，愿意去了解事情的人就扶他一把
有能力还是要么向共产党靠拢，要么逃离这片土地

**Comment by internetic** [comment]
那个帖子从头看到尾，能感到xxnet的作者还是太过理想化
任何一个良好发展社区都必须要约法三章
goagent的googlecode区是眼前的前车之鉴

**Comment by Sinla** [comment]
后面加 _Windows _MAC 这样也可以方便辨认

**Comment by xxnet** [comment]
改成
start_windows.vbs
start_windows.bat
start_mac.command
start_linux.sh

还是直接这样:
windows.vbs
windows.bat
mac.command
linux.sh

另外：
start.lnk 的方式，觉得不如vbs的方式好用，考虑去掉

2015-05-30 13:05 GMT+08:00 Sinla <notifications@github.com>:

**Comment by yfdyh000** [comment]
两者都不错。后者比较简洁。如果前者，建议 start_windows_nowindow.vbs、start_windows_logs.bat
这样有些描述说明。

start.lnk 我也建议去掉，因为目录版本号变化后这lnk就会失效，虽然最近没有换过目录版本号。我指生成在桌面的那个。

在 2015年5月30日 下午2:35，xxnet <notifications@github.com>写道：

> 改成
> start_windows.vbs
> start_windows.bat
> start_mac.command
> start_linux.sh
>
> 还是直接这样:
> windows.vbs
> windows.bat
> mac.command
> linux.sh
>
> 另外：
> start.lnk 的方式，觉得不如vbs的方式好用，考虑去掉
>
> 2015-05-30 13:05 GMT+08:00 Sinla <notifications@github.com>:
>
> > 后面加 _Windows _MAC 这样也可以方便辨认
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/XX-net/XX-Net/issues/469#issuecomment-106990376>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/469#issuecomment-106995646>.
>



-- 
Best regards,
YFdyh000.

**Comment by Cat7373** [comment]
这样的结果就是 小白照样看不明白。。。

**Comment by xxnet** [comment]
恩，似乎不是特别理想，先保持不变吧，等找到好的方案，再改。

2015-05-31 11:43 GMT+08:00 Cat73 <notifications@github.com>:

**Comment by yfdyh000** [comment]
还有一种方法，弄一个“Windows用户启动这里.bat”，然后提供一些说明和数字选项。现有的文件可以继续保持。

可参考
https://github.com/chengr28/Pcap_DNSProxy/blob/Release/Windows/ServiceControl.bat

2015-05-31 13:58 GMT+08:00 xxnet <notifications@github.com>:

> 恩，似乎不是特别理想，先保持不变吧，等找到好的方案，再改。
>
> 2015-05-31 11:43 GMT+08:00 Cat73 <notifications@github.com>:
>
> > 这样的结果就是 小白照样看不明白。。。
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/XX-net/XX-Net/issues/469#issuecomment-107121607>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/469#issuecomment-107131548>.
>



-- 
Best regards,
YFdyh000.

**Comment by xxnet** [comment]
恩，重点照顾Windows的大量小白用户，思路不错

在 2015年5月31日 下午7:44，YFdyh000 <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 我觉得既然要照顾小白，那就得白到底，是有必要用中文的。我觉得@yfdyh000 的提议不错

**Comment by YanuZhen** [comment]
像goagent一样，写个 CMDLINE 的外壳，也不错的。
项目地址：https://github.com/goagent/taskbar
