### ISSUE TITLE
解析Http请求的Bug

### ISSUE THREAD

**Issue by tarolabs** [XX-net/XX-Net#4694]
具體為:
雖rfc 2616中有明文約定之:
specified by the absoluteURI. In order to avoid request loops, a
   proxy MUST be able to recognize all of its server names, including
   any aliases, local variations, and the numeric IP address. An example
   Request-Line would be:

       GET http://www.w3.org/pub/WWW/TheProject.html HTTP/1.1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
意思是向代理發起請求時URI必須為Absolute URI.

然後如果采用Hook或者LSP的代理技術, 則Browser的發出的請求頭都是相對路徑的.
如下:
GET / HTTP/1.1
Host: ip138.com

在此情況下xx net出現錯誤: Bad request syntax('1.1') , 請查看附件.

由此錯 誤判斷代碼中對get的解析只處理了AbsoluteURI的情況, 而相對URI的情況
處理有誤.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

在rfc2616中其實亦有對此情況做出明文約定, 如下:
1. If Request-URI is an absoluteURI, the host is part of the
     Request-URI. Any Host header field value in the request MUST be
     ignored.

   2. If the Request-URI is not an absoluteURI, and the request includes
     a Host header field, the host is determined by the Host header
     field value.

   3. If the host as determined by rule 1 or 2 is not a valid host on
     the server, the response MUST be a 400 (Bad Request) error message.

意思為, 若有絕對路徑, 則取絕對路徑, 若無則應由Host絕定. 若1,2均無才返回400
Bad Request.

請修改之!  

P.S 附件為出錯截圖.

![bug-1](https://cloud.githubusercontent.com/assets/16041324/21048577/e683e1cc-be4a-11e6-9f64-4ab6913435df.png)

**Comment by jzp820927** [comment]
额，大神出现！！！

**Comment by SeaHOH** [comment]
这段时间的合并请求都没人处理……

**Comment by jzp820927** [comment]
可惜了，项目也没人接手。

**Comment by zzgpku** [comment]
好厉害，希望有大神接手弄下去，要不然这个项目迟早就沉了

**Comment by jzp820927** [comment]
我也是这么想的，哪个人去找个 程序猿 来 fork 一个，然后继续开发。

**Comment by simonasd** [comment]
@jzp820927 这类反馈放在海量issue里面，怕是要沉，以后遇到比较重要的反馈，还是去dev那边登记一下吧。

**Comment by jzp820927** [comment]
X 大已经不维护很多年了，也就 Y 大偶尔来合并一下 PR。如果有人来提 RP，估计会合并。

**Comment by xxnet** [comment]
怎么我测试的时候是OK的？
谁在测试一下：
telnet 127.0.0.1 8087
输入：
GET / HTTP/1.1
Host: www.google.com


最后2个回车

**Comment by yfdyh000** [comment]
用楼上的命令：
HTTP/1.1 301
Location: https://www.google.com/
Content-Length: 0
楼顶的命令，正常返回了源码。

**Comment by jzp820927** [comment]
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
GET / HTTP/1.1
Host: www.google.com

HTTP/1.1 200 OK
Content-Length: 11829
X-Xss-Protection: 1; mode=block
Set-Cookie: NID=93=XGwmqCjT-ecoQvCCQV1eN2-Mv6fJru2sAWbMtnM92Tc2BoZkhcTwtSQgCSCDa1gYfCaAK04oaJxDHWQKdD8UUeqs_Up3FwwkfaSJId4iH-uYYNO1xJxlmm69-dC1cnYDYK5mM0t_B5IJTg; expires=Sun, 25-Jun-2017 13:22:36 GMT; path=/; domain=.google.com; HttpOnly
Expires: -1
Server: gws
Date: Sat, 24 Dec 2016 13:22:36 GMT
P3P: CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
Content-Type: text/html; charset=ISO-8859-1
X-Frame-Options: SAMEORIGIN

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description">
中间省略 1万个字符。。。
google.y.first.push(function(){if(google.med){google.med('init');google.initHistory();google.med('history');}});if(google.j&&google.j.en&&google.j.xi){window.setTimeout(google.j.xi,0);}
</script></div></body></html>

这样应该算正常吧？

**Comment by linhua55** [comment]
再补充个相关的问题吧，就是现在不能使用 proxychains来为终端程序设置xxnet代理了。只能用设置http_proxy环境变量的方式。可以使用 proxychains来设置  goproxy的代理

**Comment by xxnet** [comment]
@linhua55 
  刚测试了proxychains，在不使用远程DNS的情况下，可以工作。
  

测试方法：
 修改 /etc/proxychains.conf
注释掉  proxy_dns
代理设置为：
 http    127.0.0.1       8087

访问：
proxychains curl --insecure https://www.google.com
可以工作。

不知你那边遇到的是什么样的情况

**Comment by linhua55** [comment]
不用`https` 时，会出错，即 `https://www.google.com` 修改为 `http://www.google.com`或`www.google.com`时。不管是否 注释掉 `proxy_dns`

➜  ~ proxychains curl --insecure  https://www.baidu.com
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  10.0.2.2:8087  ...  www.baidu.com:443  ...  OK
<!DOCTYPE html>
<html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus=autofocus></span><span class="bg s_btn_wr"><input type=submit id=su value=百度一下 class="bg s_btn" autofocus></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=https://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');
                </script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2016&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>
➜  ~ proxychains curl --insecure  http://www.baidu.com 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  10.0.2.2:8087  ...  www.baidu.com:80  ...  OK
Bad request syntax ('1.1')%                                                     ➜  ~ proxychains curl --insecure  www.baidu.com 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  10.0.2.2:8087  ...  www.baidu.com:80  ...  OK
Bad request syntax ('1.1')%                                                     ➜  ~ proxychains curl  http://www.google.com 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] Strict chain  ...  10.0.2.2:8087  ...  www.google.com:80  ...  OK
Bad request syntax ('1.1')%

**Comment by xxnet** [comment]
​重现了，看XX-Net日志，显示：
unhandler cmd:None path：ip

问题应该出在 simple_http_server.py里
解析HTTP第一行时出问题了

**Comment by xxnet** [comment]
跟踪了一下，发现proxychains处理http请求时，采用下面的方式：
 CONNECT ip:80 HTTP/1.0
  gae_proxy收到这样的请求，会认为这是https，然后发起ssl握手。
  而proxychains实际上只是把代理当作一个socks通道，而不是一个标准的HTTP代理。
这就比较麻烦了，要适配不是不可以，但是如何判断比较简洁呢？

**Comment by jzp820927** [comment]
既然是 proxychains 不标准，估计就得针对 proxychains 来单独处理了。
