### ISSUE TITLE
好奇 XX-Net zip 压缩包内的数字干嘛用的？

### ISSUE THREAD

**Issue by jeopsh** [XX-net/XX-Net#4699]
今天才注意在 XX-Net 的压缩包里有一串数字，这个数字是干嘛用的？我试过了，也并不文件的哈希值啊（MD5 SHA-1 SHA-256）?

![image](https://cloud.githubusercontent.com/assets/20238490/21072109/7dfddab0-bef2-11e6-803c-6a0f6db5817b.png)

**Comment by jzp820927** [comment]
这是什么软件显示的啊？

**Comment by jeopsh** [comment]
@jzp820927 这个还真不是文件的校验码：我用 HashTab 工具把文件的每一种哈希算法都计算了出来，都没有与之匹配的值。（文件确实是官方的原文档，我也没做过任何修改）

![image](https://cloud.githubusercontent.com/assets/20238490/21078297/d7f012ce-bfa4-11e6-84ff-24c934d128cb.png)
![image](https://cloud.githubusercontent.com/assets/20238490/21078283/4fccfeca-bfa4-11e6-99c2-fd42b143474f.png)

**Comment by SeaHOH** [comment]
纠结什么，也有可能是 github 的 comment id。
