### ISSUE TITLE
建议：加密IP池

### ISSUE THREAD

**Issue by blob2015** [XX-net/XX-Net#470]
奇葩难免，恶心总有。
但能少一些是一些？

**Comment by Cat7373** [comment]
关联Issue
https://github.com/XX-net/XX-Net/issues/468
从这条信息开始
https://github.com/XX-net/XX-Net/issues/468#issuecomment-106204010

**Comment by xxnet** [comment]
IP池是给人用的，加密没有意义。

XX-Net目前的优势是动态扫描ip，那点ip给人拿去就拿去，不要在意。
翻墙不靠这点东西。
