### ISSUE TITLE
请问一下这两天gmail无法登陆了？

### ISSUE THREAD

**Issue by zszhong** [XX-net/XX-Net#4701]
版本是用3.2.8，发现网速比较慢。

google groups可以打开，google search可以搜索，但是就是gmail无法打开

请问这是什么问题？谢谢！

**Comment by myjlpt** [comment]
如果是加载过慢，你可以选择“加载基础HTML”即可

**Comment by zszhong** [comment]
@myjlpt 不是加载过慢，是加载几秒钟之后，出现如下错误。但是我可以接受cookie，另外其余的google也能访问，就是gmail不能访问

![a](https://cloud.githubusercontent.com/assets/8293993/21078035/6d42a256-bf9b-11e6-8d86-80b78910c495.png)

**Comment by zszhong** [comment]
@myjlpt 可以了，把firefox里cookies全部删除就行了。。。
