### ISSUE TITLE
XX-Net 会致电脑死机？

### ISSUE THREAD

**Issue by jeopsh** [XX-net/XX-Net#4704]
**1.状况：**
电脑频繁死机，具体表现为硬盘占用100%，Chrome 浏览器的标题栏提示无响应，此时电脑非常卡顿，基本不能进行任何操作，持续时间一般为几分钟左右，有时甚至会有完全死机和蓝屏（蓝屏原因未知，大概跟内存管理有关）的情况。

**2.分析：**
经测试，在死机时若能结束 XX-Net 的 pythonw.exe 进程，硬盘占用随之降了下来，之后电脑便恢复正常。在后来一周的时间里，我换用了 Shadowsocks ，电脑明显稳定多了。

 
**3.测试：**
在确定电脑死机和 XX-Net 有关后，我查了些资料，在这些地方 #2970 #3538 #4005 #4636 也提到了这个问题，不过却说和 SwitchOmega 代理插件、扫描线程数、代理规则过多有关。然而我也测试了在不禁用 SwitchOmega 插件，扫描线程数为默认设置的自动调整最大50，XX-Net 系统全局代理（非 PAC 代理）的情况下，问题依旧如此。

**4.求解：**
我想知道你们有这种情况没？在其它的操作系统、浏览器和固态硬盘上是否也存在该问题？又是什么原因造成的呢？

**5.环境：**
Windows: 10.0.14393 (64-bit)
XX-Net: 3.2.8
Chrome: 53+ (64-bit) （平时主要用的是这个浏览器，其它的浏览器我就没有去测试了）
硬盘: 机械硬盘，硬盘性能比较渣，4k读写只有600KB
内存: 6GB
CPU: Intel Core i5 480M

**Comment by SeaHOH** [comment]
据说换 Chrome 32bit 就好多了。

**Comment by jzp820927** [comment]
Win 10 问题挺多的，可以先试试 32 的 chrome，如果还无法解决，可以换 win7 试试。

**Comment by ARCHOTZ** [comment]
吃肉么64位坑多，还是用32位的。

**Comment by jeopsh** [comment]
@jzp820927 @ARCHOTZ 
这应该只是个别软件会造成这种情况，我现在换用了 Shadowsocks ，依旧是 Win10 64位和 Chrome 的64位，使用起来真的没问题了。话说 Win 10 的话我也用了将近一年半了，在刚开始的时候 Win10 确实是不稳定，兼容性差，但现在很多软件都优化好了，系统体验也很不错。

其实现在我是想问问还有没有其他的人也有类似的情况，如果有的话希望他们能够反馈出来我们一起分析下问题出在哪儿。

**Comment by jzp820927** [comment]
很多反映有问题的，都是 win10 系统，不排除和系统有联系。不过目前也没有明确的证书能说明，确实是 win10 的问题。

**Comment by JohnYinlubin** [comment]
我感觉也是win10 的原因，原来一直都很快，亲几天win10 更新了，xx-net就很慢了，ss也很慢了，连hosts都慢了😭😭😭😭

**Comment by jzp820927** [comment]
我去，你这更新个 win10，就一窝端了？

**Comment by JohnYinlubin** [comment]
是啊，啥都不管了。ss换收费的账号也不快了，还有救吗？

**Comment by jzp820927** [comment]
没救了吧，换系统？

**Comment by JohnYinlubin** [comment]
啊？这么惨，我用我同学的电脑试试明天

**Comment by JohnYinlubin** [comment]
现在只能youtube144或240，这变化一时接受不了啊

**Comment by JohnYinlubin** [comment]
![image](https://cloud.githubusercontent.com/assets/23398081/21146657/68983d44-c18d-11e6-898f-4b0037da0397.png)
毛病，手动改为1080，又好了会儿，重启不知道管不管了

**Comment by jzp820927** [comment]
我去，你这个也太霸气了吧，好久没看到过 1080P 的截图了。

**Comment by JohnYinlubin** [comment]
幻想，播放下一曲就不管了，不看youtube了，静观其变吧

**Comment by JohnYinlubin** [comment]
这叫回光返照🙁后来就不管了，上个月接触的xx-net,就这么快，后来看到了7万ip的帖子，手动导入了一下（当时什么都不懂，乱弄的），ip一万多了，但是扫描为0了，从那天开始就慢了，只能看720p了，后来更新了一下win10,就彻底不管了，所有的都不管了😂😂😂😂刚才是回光返照，就听了一首歌就废了

**Comment by jzp820927** [comment]
好吧，看来是黑暗前的黎明。

**Comment by MSTWHD** [comment]
我win10/chrome 64位，几个月前我出现过这个问题，磁盘占用100%，频繁死机（除了几分钟到十几分钟的等待或者强制关机别无他法，任何鼠标按键不起作用），搞了好几天，后来是换了个chrome版本就一直没出问题了，但这几天又出现了这个问题，已经不能正常使用了，但我用火狐的时候磁盘占用100%却不会死机，顶多卡几下，结果才想起来是前几天把chrome升到了58。。。于是换了个55的chrome又好了。。。所以我感觉找到了一个用起来稳定的版本就别轻易换其他版本了。另外那个扫描线程，我一直设置的300，用了几个月时间一直没啥问题

**Comment by jeopsh** [comment]
@MSTWHD 嗯，看来还是 XX-Net 软件本身优化不太好，和 Win10 系统和 部分浏览器兼容性不够好的问题吧。（对了，现在 Chrome 56+ 的是测试版）

**Comment by jzp820927** [comment]
测试版，本来就是用来测试的。
