### ISSUE TITLE
今天下载了git版本，发现不能启动，分析代码找到原因

### ISSUE THREAD

**Issue by kuletco** [XX-net/XX-Net#4718]
XX-Net/code/default/gae_proxy/local/config.py:59行self.CONFIG.get('proxy', 'hosts')中hosts与proxy.ini不符
应为host，所以启动失败，修正后成功。

**Comment by SeaHOH** [comment]
#4690 
你改错了，这是新增功能，但是配置文件没有改。
你应该修改配置文件而不是代码。

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4712#issuecomment-266739549
去这儿下载我上传的这个覆盖下就行了，或者自己改也行。
