### ISSUE TITLE
有没有觉得XX-NET现在经常请求超时？

### ISSUE THREAD

**Issue by edwinhuish** [XX-net/XX-Net#4724]
如题，请问大家有没有经常觉得XX-NET请求超时？到底是我的DNS污染问题还是大家都遇到呢？

**Comment by jzp820927** [comment]
看看可用 IP 多不多？是不是可用 IP 太少了？

**Comment by edwinhuish** [comment]
IP数够的。
![image](https://cloud.githubusercontent.com/assets/5207925/21219017/ed34d2f4-c2ed-11e6-934c-775e50110593.png)

我改成下面这样后好很多了。。。
![image](https://cloud.githubusercontent.com/assets/5207925/21219025/fa7125bc-c2ed-11e6-8f29-30e34d293887.png)

**Comment by jzp820927** [comment]
这个是智能模式，莫非你之前是全局模式？

**Comment by edwinhuish** [comment]
一直用的都是智能模式，同样是仅仅用google搜索，无论怎么设置google走xx-net，都经常出现超时。而用PAC模式就不会出现这个问题。

然后单纯的PAC模式又不能自主添加额外的URL， 所以只能改成已知的直接走xx-net，未知的再走一遍PAC。

**Comment by SeaHOH** [comment]
因为你的规则不全，谷歌域名不止这点。还有可能同时访问以下这些。
```ini
*.ggpht.com
goo.gl
*.google.cn
*.google.co.*
*.google.com
*.google.com.*
*.googleapis.com
*.googlecode.com
*.googlegroups.com
*.googlesource.com
*.googlesyndication.com
*.googletagmanager.com
*.googletagservices.com.
*.googleusercontent.com
*.google-analytics.com
*.gstatic.com
```

**Comment by edwinhuish** [comment]
@SeaHOH 非常感谢。

**Comment by edwinhuish** [comment]
@SeaHOH 请问下面这个列表没有用么？或者有没有其他好的列表URL??
![image](https://cloud.githubusercontent.com/assets/5207925/21222829/e8c47948-c2fe-11e6-96df-e5b260ab0981.png)

**Comment by jzp820927** [comment]
额，我懂了，你之前是用的 纯 PAC，现在用的 PAC+omega规则混合。
gfwlist 已经是目前最好，最全的了。

**Comment by SeaHOH** [comment]
LS +1

**Comment by edwinhuish** [comment]
谢谢

**Comment by roc1010kmt** [comment]
使用外語windows系統,omega顯示英文,能改中文嗎?

**Comment by jzp820927** [comment]
好像可以手动切换语言

**Comment by lon91ong** [comment]
多谢前面诸位的解答，我也遇到了同样的问题，已解决
