### ISSUE TITLE
3.2.7切换代理

### ISSUE THREAD

**Issue by forestbat** [XX-net/XX-Net#4736]
右击系统托盘的XX-net图标，点选全局代理的两个选项无效，无论怎么点，对号都在“取消全局代理”选项上。
![qq 20161218103102](https://cloud.githubusercontent.com/assets/23413915/21291093/96d585ac-c50e-11e6-8543-a152fff5f117.png)

**Comment by zhencaihao** [comment]
https://github.com/XX-net/XX-Net/issues/4389  网络设置成这里的图片。

**Comment by jzp820927** [comment]
直接手动设置吧
