### ISSUE TITLE
人机身份 验证！人机！人机验证！

### ISSUE THREAD

**Issue by Farb** [XX-net/XX-Net#4737]
以前每当打开下面这个网站时，都会提示人机验证，勾选之后，等6秒左右会出来弹窗，选择图片验证码，但今天勾选之后，一致弹不出图片验证码，怎么回事啊？我也看到有人说Vimeo这个网站，也要人机验证，但是我按照网友的做法在data文件夹下gae_proxy目录下新建了manual.ini文件，设置了直连规则，也没有作用！是不是最近很多人遇到这个问题啊？希望有高手可以诊断下这个问题的根源是什么？如何解决啊？

![image](https://cloud.githubusercontent.com/assets/7587900/21291941/307827e6-c52d-11e6-9c9b-3e2f9a35bf60.png)

![image](https://cloud.githubusercontent.com/assets/7587900/21291951/dc389048-c52d-11e6-9234-a9e7a521160c.png)

**Comment by Farb** [comment]
设置直连规则后，重启xx-net就解决问题了，但是还不知道问题的根本是什么？为什么之前没这个问题？希望有大神回答

**Comment by jzp820927** [comment]
直连规则只对 google 服务类网站有用，你这个好像不是 google 的网站吧

**Comment by kanidi** [comment]
我新建了manual.ini文件还是不行啊，一用google就要人机验证

**Comment by jzp820927** [comment]
应该是你规则没写对，把规则贴出来看看

**Comment by kanidi** [comment]
<img width="397" alt="2016-12-20_103331" src="https://cloud.githubusercontent.com/assets/18379892/21336365/d5584750-c69f-11e6-99c2-34e4438cd5e6.png">
是这样的吗？

**Comment by jzp820927** [comment]
大哥，你文件名弄错了，是 manual.ini，不是 mamual.ini

**Comment by kanidi** [comment]
hahah,还真是啊！不过我发现人机验证总是在傍晚才有的，早上还是正常的。。今晚再看看..

**Comment by jzp820927** [comment]
晚上上网人多啊，流量大了，自然就被 google 判定为异常流量啊。
