### ISSUE TITLE
vimeo网站现在老提示链接超时，求高手解答，平时看视频都在vimeo网站，这下彻底郁闷了

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#4740]
XX-Net 3.2.8，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	3000
空闲	0
IP延迟	503
连接池(帮助)	新:4 h1:27 h2:11
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK

![default](https://cloud.githubusercontent.com/assets/18569232/21292852/1d710e9a-c54d-11e6-8d71-24fb7fde16e0.png)

**Comment by jzp820927** [comment]
估计可能是 vimeo 屏蔽了 GAE 的 IP 吧，只有这1个网站有问题麽？

**Comment by JMaxime** [comment]
https://vimeo.com/
![1](https://cloud.githubusercontent.com/assets/18569232/21293230/115243ac-c559-11e6-956f-109f5a814bef.png)
![2](https://cloud.githubusercontent.com/assets/18569232/21293235/2c2dc02a-c559-11e6-9ed0-d583cbc295c5.png)

**Comment by JMaxime** [comment]
现在又是这样 要疯了 X大他们还维护吗？

**Comment by jzp820927** [comment]
早没人维护了，有问题得靠自己解决了。我试试看

**Comment by JMaxime** [comment]
好的 先谢了

**Comment by jzp820927** [comment]
刚刚试了下，和你一样的情况，基本上可以确定 GAE 的出口 IP 进入 vimeo 的黑名单了。

**Comment by JMaxime** [comment]
这就悲剧了

**Comment by jzp820927** [comment]
其实解决办法还是有的，只是麻烦点

**Comment by JMaxime** [comment]
怎么弄呢 望告知

**Comment by jzp820927** [comment]
不知道你是不是用的 chrome + omega 来 FQ 的？

**Comment by JMaxime** [comment]
不是 就是xx-net直接出去的 全局代理

**Comment by jzp820927** [comment]
全局代理肯定是不行的，要解决这个问题，就是要让 vimeo.com 直连，因为我试了一下，也就是首页有验证，其他没有，你可以把首页设成直连，其他的走代理，这样就没问题了。

**Comment by JMaxime** [comment]
怎么直连法 能发一下方法吗

**Comment by JMaxime** [comment]
这样吗 但是 我加了vime.com 也不行
![1](https://cloud.githubusercontent.com/assets/18569232/21293722/94e5b452-c567-11e6-8204-70f8699f364c.png)

**Comment by JMaxime** [comment]
加了直连就出现 链接超时，等一会回来

**Comment by jzp820927** [comment]
不是这个意思，这个直连只对 google 的域名有效，其他没有效果。
你是用的 chrome 浏览器吗？

**Comment by JMaxime** [comment]
是的

**Comment by jzp820927** [comment]
有没有安装 omega 插件？

**Comment by JMaxime** [comment]
装了 怎么弄

**Comment by JMaxime** [comment]
omega 插件 选了直连就不能打开谷歌网页了

**Comment by JMaxime** [comment]
你就直接把方法贴出来 也方便后面的Q友

**Comment by jzp820927** [comment]
你在 omega 中设置规则 vimeo.com 结尾的域名全部直连。默认规则设置为 XXNET
然后再 hosts 中添加 
23.235.33.217 vimeo.com

应该就没问题了，你试试。

**Comment by JMaxime** [comment]
没有默认规则 我是新手 能否截个图 谢谢
![1](https://cloud.githubusercontent.com/assets/18569232/21294060/8d75d32a-c56f-11e6-9084-f31a3240d9a7.png)

**Comment by jzp820927** [comment]
就是那个 “默认情景模式”，就是默认规则，选择 XXNET 就可以了。

**Comment by jzp820927** [comment]
直连规则再添加一条
*.vimeo.com

**Comment by JMaxime** [comment]
默认规则没有xxnet，你看看哪里不对，指出来。
![1](https://cloud.githubusercontent.com/assets/18569232/21294196/64f4b10c-c572-11e6-98d7-7614b9dff37f.png)
![2](https://cloud.githubusercontent.com/assets/18569232/21294180/0404ddcc-c572-11e6-9721-eadf1b1136b8.png)
![3](https://cloud.githubusercontent.com/assets/18569232/21294182/049f9222-c572-11e6-8db8-f879b7de9425.png)

**Comment by jzp820927** [comment]
那啥，你没用过 omega 么？

**Comment by JMaxime** [comment]
没有用过 你截图 如果还不行 我就要跪了

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Chrome%E6%B5%8F%E8%A7%88%E5%99%A8
按照上面这个教程
方案二：安装和使用代理切换插件  的内容，把那个文件导入进去，就有 XXNET 了。

**Comment by JMaxime** [comment]
已经在网上找到解决方法了，非常感谢你

**Comment by jzp820927** [comment]
你说的这网上找到解决方法，是指的 配置 omega 规则？还是指的 vimeo 访问的问题？

**Comment by JMaxime** [comment]
找到了配置方法，vimeo也可以打开了
 就是视频播放不了 ，这墙好高，放弃了

**Comment by jzp820927** [comment]
不应该，我这边测试过的，没啥问题。

**Comment by JMaxime** [comment]
那就不知道了 加hosts也加了 直连也加了 就是不能看视频 真是醉了

**Comment by jzp820927** [comment]
把你配置的 omega，贴出来，我看看

**Comment by JMaxime** [comment]
![1](https://cloud.githubusercontent.com/assets/18569232/21349778/b988a2aa-c6ee-11e6-9846-e0b868a8f12b.png)
![2](https://cloud.githubusercontent.com/assets/18569232/21349780/bbf8c7f4-c6ee-11e6-9ddf-a06cb289a081.png)

**Comment by jzp820927** [comment]
我不是叫你把“默认情景模式”设置为 XXNET 嘛

**Comment by JMaxime** [comment]
![1](https://cloud.githubusercontent.com/assets/18569232/21351309/dbb59718-c6f6-11e6-8216-2a7821580108.png)

**Comment by JMaxime** [comment]
填的就是xxnet啊 只不过名字不一样

**Comment by jzp820927** [comment]
我去。看图，红框处，改成 XXNET
![bbf8c7f4-c6ee-11e6-9ddf-a06cb289a081](https://cloud.githubusercontent.com/assets/5740066/21351801/8fe95a38-c6f9-11e6-8a0e-66d5c99f877f.png)

**Comment by JMaxime** [comment]
我的错

**Comment by jzp820927** [comment]
对了，记得把你在 manual.ini 里面和 vimeo 相关的直连配置删掉，不然会有问题。
还有，你再添加一条 *.vimeo.com 的直连规则就行了。

**Comment by JMaxime** [comment]
ok 已经加了  感谢你的耐心回答
![1](https://cloud.githubusercontent.com/assets/18569232/21354223/2af4591a-c704-11e6-9132-3c764cbe2280.png)

**Comment by jzp820927** [comment]
还有，你再添加一条 *.vimeo.com 的直连规则就行了。
我说的是加到  omega 规则里面，不是 manual.ini 文件。
manual.ini 文件里面和 vimeo 有关的，全部删掉。

**Comment by peter-wang-wsl** [comment]
配了host也不好使，不能看dotinstall的视频了，因为也是vimeo的...

**Comment by qazwsdc** [comment]
> 还有，你再添加一条 *.vimeo.com 的直连规则就行了。
> 我说的是加到 omega 规则里面，不是 manual.ini 文件。
> manual.ini 文件里面和 vimeo 有关的，全部删掉。

大神，现在你这方法好像失效了，我试了下能访问vimeo但加载不出视频
