### ISSUE TITLE
现在创建appid没有位置可选？

### ISSUE THREAD

**Issue by NAVrasZ** [XX-net/XX-Net#4749]
RT，只有填名字一行，点创建后就创建了

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4720
参考这个 issues 操作

**Comment by NAVrasZ** [comment]
@jzp820927 多谢，原来如此
（用edge打开白屏只好换IE不知是什么问题...

**Comment by jzp820927** [comment]
推荐 chrome，google 的服务配和 google 的浏览器，兼容性肯定是最好的。

**Comment by NAVrasZ** [comment]
ok，chrome打开正常，多谢~

**Comment by asd2003asd** [comment]
感谢，解决部署404错误的问题。

**Comment by jzp820927** [comment]
google 的服务老是变化，是挺麻烦的

**Comment by zhencaihao** [comment]
我这里20MB的电信光纤。以前网络好的额时候白天看youtube速度2500-3500kbps，晚上有1000-1500kbps。现在是卡的不行，白天500-1000，偶尔能到1500kbps左右，到了晚上就100-300kbps。

**Comment by jzp820927** [comment]
100-300kbps，有种一朝回到解放前的赶脚。

**Comment by zhencaihao** [comment]
现在就是很卡啊，等到晚上看twitter的图片、自动翻译都好等好久才出来。

**Comment by jzp820927** [comment]
现在哪儿都一样，IP 数量都是猛减。
