### ISSUE TITLE
请问如何为APPID设置密码,我所有私人APPID总被盗光流量

### ISSUE THREAD

**Issue by NorthMaple** [XX-net/XX-Net#4754]
RT. 25个APPID实际上没怎么用过, 然而每天一早就显示"您的APPID流量已经用完，请部署更多APPID。"
虽然个人认为APPID被偷光流量很正常, 因为它就在那
布署的时候尝试过设置密码, 但\XX-Net\code\default\gae_proxy\server\gae\gae.py里面的__password__项永远会在布署服务端的时候重设为""(空), 在布署服务端的报告可以看出(将gae.py设定为只读文件后会出现"password设定失败"的类似警告)
也许是我使用的错误的方法吧

**Comment by jzp820927** [comment]
上传到时候，通过命令行参数设置密码，不知道你是怎么操作的

**Comment by wenliyang** [comment]
XX-Net\code\default\gae_proxy\server\uploader.bat
用这个部署，可以同时设置密码

使用方法见
XX-Net\code\default\gae_proxy\server\README.md

**Comment by PvCDp** [comment]
你的id曝光了吗？如果是这样你就再申请一个账号，可以在布置12个id
