### ISSUE TITLE
为什么减少最大IP数，有效IP数量即使达到了也还是在不停的扫描？

### ISSUE THREAD

**Issue by fightingcat** [XX-net/XX-Net#4761]
状态

属性	值
总IP数	50
剩余数	0
有效IP数	51

扫描日志里仍不停出现：
Dec 24 00:05:01 - [INFO] Add xxx.xxx.xxx.xxx time:xxx CN:google.com

**Comment by fightingcat** [comment]
看了下源码，原来这个最大IP数并不是扫够了就不扫的意思，而是最多保存多少个IP，扫描是不停的，扫到一个就遍历一遍所有IP丢掉速度最慢的一个，所以界面才会出现有效IP数总是比总数多1的情况……

**Comment by jzp820927** [comment]
如果想停止扫描，可以把扫描线程设置为 0

**Comment by fightingcat** [comment]
@jzp820927 好的，谢谢
