### ISSUE TITLE
【Bug】建议增加如每隔两个小时自动检查所有IP这个功能

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net#4768]
基本每次都会显示有3000个有效IP，但是运行检查所有IP之后​就只有不到2000个有效IP，那么多无效IP掺杂着严重拖慢通过xx-net访问网站的速度。
所以建议增加如每隔两个小时自动检查所有IP这个功能。
​

**Comment by yaoguaishou** [comment]
建议降低最大ip上限，我的是80个

**Comment by zhout26** [comment]
@yaoguaishou 在哪里设置？google_ip.py吗？

**Comment by jzp820927** [comment]
web 界面设置，127.0.0.1:8085

**Comment by redstoneleo** [comment]
@jzp820927  web 界面设置的什么位置设置？讲清楚啊啊

**Comment by jzp820927** [comment]
你不会菜单一个一个点开找啊，这么简单的事情。真是服了。

**Comment by jzp820927** [comment]
刚刚看了下，web 界面好像没有，那你只能手动改配置文件了。
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by redstoneleo** [comment]
我的是 XX-Net-3.1.19\data\gae_proxy\manual.ini

[hosts]
.google.com = direct
[google_ip]
max_good_ip_num = 70
