### ISSUE TITLE
win10的14986版本不能设置为全局通过GAEProxy代理

### ISSUE THREAD

**Issue by Barra-Barracuda** [XX-net/XX-Net#4772]
没有升级win10之前是可以的，但是升级后点击却没有反应？始终是显示取消全局代理

**Comment by nly4lov** [comment]
有没有试过退出重新运行

**Comment by Barra-Barracuda** [comment]
@nly4lov 如果有这么简单就不用问了

**Comment by jzp820927** [comment]
如果托盘菜单不能设置，就手动设置一样的。
另外建议用 PAC，代理全局代理，这样不影响访问国内网站。
