### ISSUE TITLE
浏览器代理设置:Fail，CA证书状态(下载):Fail 怎么办

### ISSUE THREAD

**Issue by songhao8080** [XX-net/XX-Net#4774]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7600-SP0
os-system: Windows
os-version: 6.1.7600
os-release: 7
os-detail: Version:6-1; Build:7600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:502 good:221
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 422
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
自己下载，手动导入啊

**Comment by jzp820927** [comment]
证书问题吧，有没有导入证书。
如果导入了，可以试着删除 CA.crt 文件，certs/ 目录，然后重新运行 XXNET，重新导入新生成的证书。
