### ISSUE TITLE
这是啥情况？

### ISSUE THREAD

**Issue by yy197133** [XX-net/XX-Net#4776]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 87
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 48
ip-quality: 682
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
证书。

**Comment by yy197133** [comment]
换了最近版本，就好了

**Comment by nly4lov** [comment]
最新版本就包括最新的证书
