### ISSUE TITLE
打开google跳转到环聊怎么破。。

### ISSUE THREAD

**Issue by RainbowDashy** [XX-net/XX-Net#479]
重装了证书还是这样

**Comment by RainbowDashy** [comment]
“此页包含太多重定向循环”

**Comment by Cat7373** [comment]
发一下问题是怎么出现的吧，方便重现问题，方便定位于解决问题。

**Comment by RainbowDashy** [comment]
删除proxy.ini中[hosts]后解决

**Comment by proac50** [comment]
在chrome中清除cookie即可恢复正常

**Comment by SeaHOH** [comment]
环聊早没了好吧，这么老的你都挖。

**Comment by SeaHOH** [comment]
不是说环聊去年升级成另外的工具了么，刚看了下还在。

**Comment by proac50** [comment]
不好意思，我的环聊依然活着，前几天google的ncr居然都跳转到环聊，搜索了一下没有发现别的方法，于是自己动手清除了饼干就好了。
