### ISSUE TITLE
x-tunnel 不能工作

### ISSUE THREAD

**Issue by kingofmytoor** [XX-net/XX-Net#4790]
X-tunnel 流量有，但是不能上网 下面是log 已经更新了最新版的 还是不能工作 大家帮忙看看

Dec 29 09:59:04.690 - [DEBUG] socks5 auth num:1, list:00
Dec 29 09:59:04.690 - [ERROR] socks5 protocol error:error('recv fail',)
Dec 29 09:59:04.690 - [ERROR] Except stack:Traceback (most recent call last): File "D:\\\XX-Net-3.2.9\XX-Net-3.2.9\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\\\XX-Net-3.2.9\XX-Net-3.2.9\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
Dec 29 10:00:05.044 - [WARNING] socks version:47 not supported
Dec 29 10:00:19.485 - [ERROR] socks handler read error error('recv fail',)
Dec 29 10:00:19.486 - [ERROR] Except stack:Traceback (most recent call last): File "D:\\\XX-Net-3.2.9\XX-Net-3.2.9\code\default\x_tunnel\local\proxy_handler.py", line 26, in handle socks_version = self.read_bytes(1) File "D:\\\XX-Net-3.2.9\XX-Net-3.2.9\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail

**Comment by jzp820927** [comment]
是不是有安全迅雷？有可能有冲突，如果有的话，把迅雷卸载了试试

**Comment by kingofmytoor** [comment]
好的 谢谢解答 我先去试验下 有结果再来反馈
