### ISSUE TITLE
还是无法使用校园网

### ISSUE THREAD

**Issue by Ch-Song** [XX-net/XX-Net#4792]
我之前提问过关于[校园网的问题](https://github.com/XX-net/XX-Net/issues/4082)，现在我发现我根本没法用校园网。也就是学校网关登录界面也进不去。删除掉xxnet之后也不能解决。请问这个怎么办呢？

**Comment by jzp820927** [comment]
检查下 IE 里面的 局域网设置，代理服务器，是不是有内容。有的话，清空。

**Comment by Ch-Song** [comment]
谢谢您回复
我的IE的设置里面没有，我除了改过laod.cn给出的hosts之外没有设置任何东西，也不知道是什么情况😭😭😭

**Comment by jzp820927** [comment]
那在什么情况下，可以正常使用校园网/

**Comment by Ch-Song** [comment]
在非学校wifi下可以打开学校的网页比如电信网，手机。
连接学校wifi之后，必须先登录学校网关才能访问校外网页。登录学校网关的网页打不开。

**Comment by Ch-Song** [comment]
已经解决 解决办法是在internet协议版本里面把dns获取方式改成 自动获取dns地址
