### ISSUE TITLE
Youtube无法播放视频 救救孩子QAQ

### ISSUE THREAD

**Issue by EnnoonnE** [XX-net/XX-Net#4794]
-----------
问题描述：
之前看视频什么的都超级流畅 最近不知怎么打开youtube还是可以浏览，但是点进视频就是黑屏根本没办法放QAQ 人生少了好多乐趣啊QAQ 请问大大们可以从这个诊断信息看出点啥来吗？（一个文科生的哀嚎

-----------
诊断信息：
sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 10000 / 213
network-status: OK
connected-link: 9 / 47
scan-ip-thread-num: 50
ip-quality: 1025
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
你这个改升级 XX 版本了，版本太低了

**Comment by EnnoonnE** [comment]
我刚刚清了一下浏览记录就又可以正常使用了嘿嘿
如果不升级的话会有什么问题吗？
（其实是我不会弄所以懒得升级……
（谢谢您！


2016-12-29 

buyaoluanlianxi 



发件人：天朝屁民 <notifications@github.com>
发送时间：2016-12-29 16:29
主题：Re: [XX-net/XX-Net] Youtube无法播放视频 救救孩子QAQ (#4794)
收件人："XX-net/XX-Net"<XX-Net@noreply.github.com>
抄送："EnnoonnE"<buyaoluanlianxi@163.com>,"State change"<state_change@noreply.github.com>

你这个改升级 XX 版本了，版本太低了

**Comment by jzp820927** [comment]
也没什么影响，能用就行

**Comment by EnnoonnE** [comment]
谢谢您╭( ･ㅂ･)و ̑̑

2016-12-29 

buyaoluanlianxi 



发件人：天朝屁民 <notifications@github.com>
发送时间：2016-12-29 17:48
主题：Re: [XX-net/XX-Net] Youtube无法播放视频 救救孩子QAQ (#4794)
收件人："XX-net/XX-Net"<XX-Net@noreply.github.com>
抄送："EnnoonnE"<buyaoluanlianxi@163.com>,"State change"<state_change@noreply.github.com>

也没什么影响，能用就行
