### ISSUE TITLE
一切都很好，就差niconico了

### ISSUE THREAD

**Issue by cottonty** [XX-net/XX-Net#48]
网页能打开，视频缓冲不了

**Comment by xxnet** [comment]
用SwitchyProxy，导入GoAgent的配置后，自动模式可以看niconico的视频哦

**Comment by cottonty** [comment]
不行啊，自动不行，连强制goagent都不行
每次都是now loading一会之后，出来这个
動画の読み込みに失敗しました。
しばらく時間をおいてから、ページを再読み込みしてください。

※何度か再読み込みを行っても解決しない場合、以下の方法をお試しください。
読み込みに失敗した動画情報を削除するため、ブラウザのキャッシュをクリアしてください。

**Comment by xxnet** [comment]
好像可以看了，请测试新版
