### ISSUE TITLE
XX-Net 使用公用的appids也无法连接了

### ISSUE THREAD

**Issue by sunnyyouknow** [XX-net/XX-Net#480]
GoAgent状态信息
Property 	Value
Sys Platform	linux2
OS System	Linux
OS version	#79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015
OS release	3.13.0-46-generic
OS detail	Dist:Ubuntu; Version:14.04; ID:trusty
architecture	64bitELF
Browser	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
XX-Net Version	1.8.5
Launcher Version	1.3.0
GoAgent Version	3.1.48
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087
working appids	xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Out of Quota appids	
Not Exist appids	
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	0
connected link	0
ip_connect_interval	10

GoAgent日志:
May 31 13:45:09 - [INFO] load google ip_list num:5, gws num:5
May 31 13:45:09 - [DEBUG] sort ip time:0
May 31 13:45:09 - [INFO] ------------------------------------------------------
GoAgent Version : 3.1.48 (python/2.7.6 )
Listen Address : 127.0.0.1:8087
Control Address : 127.0.0.1:8084
GAE APPID : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Pac Server : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

May 31 13:45:11 - [DEBUG] get ip:106.162.216.49 t:307
May 31 13:45:12 - [DEBUG] get ip:106.162.216.59 t:307
May 31 13:45:12 - [DEBUG] get ip:210.245.14.183 t:822
May 31 13:45:12 - [DEBUG] get ip:24.156.131.50 t:1438
May 31 13:45:13 - [DEBUG] get ip:62.116.207.59 t:2954
May 31 13:45:13 - [DEBUG] create_ssl 106.162.216.49 fail:timed out c:0 h:0
May 31 13:45:13 - [DEBUG] network is ok
May 31 13:45:13 - [DEBUG] create_ssl 106.162.216.59 fail:timed out c:0 h:0
May 31 13:45:13 - [DEBUG] network is ok
May 31 13:45:14 - [DEBUG] create_ssl 210.245.14.183 fail:timed out c:0 h:0
May 31 13:45:14 - [DEBUG] network is ok
May 31 13:45:14 - [DEBUG] create_ssl 24.156.131.50 fail:timed out c:0 h:0
May 31 13:45:14 - [DEBUG] network is ok
May 31 13:45:14 - [DEBUG] create_ssl 62.116.207.59 fail:timed out c:0 h:0
May 31 13:45:14 - [DEBUG] network is ok
May 31 13:45:17 - [DEBUG] GoAgent web_control 127.0.0.1:47256 POST /config?cmd=get_config
May 31 13:45:22 - [DEBUG] get ip:106.162.216.49 t:307
May 31 13:45:23 - [DEBUG] sort ip time:0
May 31 13:45:23 - [DEBUG] create_ssl 106.162.216.49 fail:timed out c:0 h:0
May 31 13:45:23 - [DEBUG] network is ok
May 31 13:45:35 - [INFO] GAE CONNECT www.facebook.com:443
May 31 13:45:35 - [DEBUG] GAE CONNECT GET https://www.facebook.com/
May 31 13:45:35 - [DEBUG] ssl conn_num:0
May 31 13:45:48 - [INFO] GAE CONNECT clients4.google.com:443
May 31 13:45:48 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/dev/experimentstatus
May 31 13:45:48 - [DEBUG] ssl conn_num:0
May 31 13:45:50 - [DEBUG] create ssl timeout fail.
May 31 13:45:50 - [DEBUG] create_ssl_connection fail
May 31 13:45:50 - [DEBUG] ssl conn_num:0
May 31 13:46:03 - [DEBUG] create ssl timeout fail.
May 31 13:46:03 - [DEBUG] create_ssl_connection fail
May 31 13:46:03 - [DEBUG] ssl conn_num:0
May 31 13:46:05 - [DEBUG] create ssl timeout fail.
May 31 13:46:05 - [DEBUG] create_ssl_connection fail
May 31 13:46:05 - [DEBUG] ssl conn_num:0
May 31 13:46:05 - [INFO] FWD CONNECT www.gstatic.com:443
May 31 13:46:05 - [INFO] FWD CONNECT www.gstatic.com:443
May 31 13:46:16 - [INFO] GAE CONNECT accounts.google.com:443

**Comment by xxnet** [comment]
你的版本太老了，请下载新版，并放着运行1天再看看

sunnyyouknow <notifications@github.com>于2015年5月31日星期日写道：

**Comment by golden-hu** [comment]
为什么要放着运行1天？
昨晚刚装的时候，未能打开google,facebook
今早起来，可以了？
只是开着XX-NET一直在刷日志而已

**Comment by yfdyh000** [comment]
因为默认的good_ip很多失效了，需要扫描排除，以及扫描到新的IP。
可以自己手动删掉good_ip.txt再导入能用的IP，如果自己有。
