### ISSUE TITLE
在导出ip页面加上 请勿公开ip 文字提示

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#4801]
某人公开了ip会不会导致一片阵亡？
是不是需要加上这样的提示

**Comment by jzp820927** [comment]
想的太周到了

**Comment by J-XX-NET** [comment]
用xx-net科学上网后，某些国外网站打不开例如www.manta.com。请问这个有解决方法吗？其他的翻墙软件可以打开

**Comment by jzp820927** [comment]
一般这种情况，都是这个网站屏蔽了 GAE 的访问。

**Comment by J-XX-NET** [comment]
有解决的办法吗

**Comment by jzp820927** [comment]
除了换代理，别无他法，因为 gae 的出口 IP，就那么几个，如果被网站屏蔽了，就无解了。

**Comment by wooowooo** [comment]
怎么我的issue话题突然变了

**Comment by jzp820927** [comment]
楼歪了，手动扶正

**Comment by theratlesnake** [comment]
@J-XX-NET 那个是什么网站啊？打开居然说我是机器人不给访问

**Comment by SeaHOH** [comment]
不知道给 GAE Urlfetch 请求头部加上代理信息会不会解除部分网站对 GAE 出口 IP 的屏蔽。

**Comment by jzp820927** [comment]
这个应该是 IP 黑名单吧，IP 不变应该不行。

**Comment by SeaHOH** [comment]
刚想到的，等我找空试一下。

**Comment by jzp820927** [comment]
好吧，今天是新年，应该休息哈。

**Comment by theratlesnake** [comment]
@SeaHOH 大神，可以的话，公布一下啊，万众期待呢。可惜我不会操作。

**Comment by jzp820927** [comment]
急什么，今天是新年，总得让大神休息休息吧，不然累坏了，谁来处理。

**Comment by SeaHOH** [comment]
发现一个问题：
要加入代理信息，必须知道当前链接的 GAE 出口 IP，这需要修改服务端代码。

所以我决定不测试了，好麻烦~~

**Comment by jzp820927** [comment]
我猜也是这个结果。
