### ISSUE TITLE
证书导入了，但状态栏一直是Fail，请问是为什么

### ISSUE THREAD

**Issue by Piglet1994** [XX-net/XX-Net#4804]
ipv6-status: 0
gws-ip-num: total:1245 good:537
network-status: OK
connected-link: new:2 used:0
worker: h1:21 h2:4
scan-ip-thread-num: 50
ip-quality: 448
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
影响使用麽？

**Comment by Piglet1994** [comment]
@jzp820927 根本用不了，打开网页就私密链接错误

**Comment by jzp820927** [comment]
那是你没导入证书，先导入证书。

**Comment by hktxt** [comment]
导入证书了 可是显示的却是没有证书

**Comment by jzp820927** [comment]
在哪儿显示没有证书？截图发来看看

**Comment by 674273563** [comment]
WIN10出现这个问题 之前XP 良好

**Comment by 674273563** [comment]
![1](https://cloud.githubusercontent.com/assets/20715758/21705961/49183626-d3fe-11e6-80b6-45c93cf2ed64.jpg)

**Comment by jzp820927** [comment]
证书过期就要重新生成，删除 data，删除导入浏览器的证书，重启 XX，重新导入新证书到浏览器

**Comment by 674273563** [comment]
已搞定 但删除data后要重新输入appid 以前扫面的ip也没有了

**Comment by jzp820927** [comment]
想保留 IP 数据，就删除 data 下面的 CA.crt 文件和 certs 文件夹，我是懒得打字，所以直接叫你删除 data
