### ISSUE TITLE
关于移除最低速IP的日志

### ISSUE THREAD

**Issue by clawneo** [XX-net/XX-Net#481]
最新10测试版，在添加新扫描到IP及移除最低速IP上做了修正。

但是目前移除最低速IP的记录日志在总日志里。。。而在IP扫描的日志中没有。。。
可以将移除最低速IP日志记录也弄进IP扫描的日志中么？

这样子查看google_ip日志的会省力清晰很多。。。

**Comment by clawneo** [comment]
先赞一下最新版本添加新IP跟移除老的最低速IP的同步速度 ：）

**Comment by yfdyh000** [comment]
为什么移除IP的日志要放到扫描IP的日志里？移除是IP池管理的部分，跟扫描模块基本无关吧。

**Comment by xxnet** [comment]
是的，有什么场景需要关心被移除的ip?
如果需求不大，放在goagent日志中是不是就够了

在 2015年5月31日 下午7:45，YFdyh000 <notifications@github.com>写道：
