### ISSUE TITLE
连不上，这是为什么？

### ISSUE THREAD

**Issue by memopad** [XX-net/XX-Net#4816]
XX-Net Status:

sys-platform: x86_64, Darwin-16.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64
os-release: 16.3.0
os-detail: Release:10.12.2; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:129 good:91
network-status: OK
connected-link: new:2 used:0
worker: h1:8 h2:1
scan-ip-thread-num: 50
ip-quality: 777
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
证书导入了吗？

**Comment by memopad** [comment]
导入了，之前用得好好的，前几天突然出现“请检查浏览器代理设置。”我没在意，以为哪里暂时出问题了，没想到之后就都不能翻了，昨天重新配置后还是不行。不知道问题出在哪。

**Comment by jzp820927** [comment]
看状态页，到是没有什么太大的问题，就是 IP有点少，日志贴出来看看。

**Comment by memopad** [comment]
又可以了。。我擦，刚买了一年shadowsocks。。

**Comment by jzp820927** [comment]
近段时间 干扰很厉害，所以 XX 没以前稳定了，偶尔抽风一下，也算正常。

**Comment by SeaHOH** [comment]
买了也不亏，做后备嘛。

**Comment by memopad** [comment]
嗯嗯，谢谢
