### ISSUE TITLE
xx-net  can't run fine

### ISSUE THREAD

**Issue by cnjeffliu** [XX-net/XX-Net#4831]
./x_tunnel/client.log
Jan 06 10:57:16.732 - [INFO] use config_path:/home/software/XX-Net-3.2.8/data/x_tunnel/client.json
Jan 06 10:57:16.732 - [INFO] Use proxy:127.0.0.1:8087
Jan 06 10:57:16.732 - [DEBUG] x-tunnel no account
Jan 06 10:57:16.732 - [WARNING] x-tunnel session not start
Jan 06 10:57:16.732 - [INFO] Socks5 server listen:127.0.0.1:1080.
==========================================
./launcher/launcher.log
Jan 06 10:57:16.444 - [INFO] import build-in openssl fail:ImportError('/home/software/XX-Net-3.2.8/code/default/python27/1.0/lib/linux/_cffi_backend.so: undefined symbol: PyUnicodeUCS4_AsASCIIString',)
Jan 06 10:57:16.528 - [INFO] start XX-Net 3.2.8
Jan 06 10:57:16.528 - [DEBUG] start confirm_xxnet_exit
Jan 06 10:57:16.530 - [DEBUG] good, xxnet:8087 cleared!
Jan 06 10:57:16.530 - [DEBUG] good, xxnet:8085 clear!
Jan 06 10:57:16.530 - [DEBUG] finished confirm_xxnet_exit
Jan 06 10:57:16.727 - [INFO] module gae_proxy started
Jan 06 10:57:16.727 - [INFO] start gae_proxy time cost:197 ms
Jan 06 10:57:16.832 - [INFO] module x_tunnel started
Jan 06 10:57:16.832 - [INFO] start x_tunnel time cost:104 ms
Jan 06 10:57:16.832 - [INFO] begin to start web control
Jan 06 10:57:16.833 - [INFO] launcher web control started.
Jan 06 10:57:17.835 - [INFO] get uuid:350336fc-6e9d-4796-89cb-xxxxxxxxxxxxxxx
Jan 06 10:57:18.138 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to /home/software/XX-Net-3.2.8/data/downloads/version.txt, retry:0

**Comment by jzp820927** [comment]
运行失败？什么系统？

**Comment by nly4lov** [comment]
人家甩英文，你用国语回答

**Comment by jzp820927** [comment]
好吧，那你和他交流吧

**Comment by 674273563** [comment]
不明白老外为什么用xxnet 安全性？国外版gfw?

**Comment by cnjeffliu** [comment]
centos7.1

**Comment by cnjeffliu** [comment]
@jzp820927 
centos7.1

**Comment by jzp820927** [comment]
你 python 什么版本？有没有装 openssl，centos 的软件和库都比较老。

**Comment by cnjeffliu** [comment]
python2.7.5
openssl安装了

**Comment by cnjeffliu** [comment]
已经解决 谢谢各位

**Comment by cnjeffliu** [comment]
已经解决 谢谢各位

**Comment by jzp820927** [comment]
那啥，不分享一下，解决方法麽？

**Comment by cnjeffliu** [comment]
centos下rpm -ivh nss-tools-3.21.0-8.el6.x86_64.rpm 
证书安装完update-ca-certicate extract下

**Comment by jzp820927** [comment]
意思是 证书问题
