### ISSUE TITLE
注册appid提示未能加载

### ISSUE THREAD

**Issue by miku1958** [XX-net/XX-Net#4833]
按照教程https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids 到了选择语言为Python后，网页直接提示未能加载。然后就不能继续。是不是注册流程又改了？

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4720#issuecomment-267678714
参考这个操作。

**Comment by yaoguaishou** [comment]
@jzp820927 大神每次来issue都能看到你

**Comment by jzp820927** [comment]
这个项目目前没人管理，我就是来帮哈忙，解答哈问题。

**Comment by miku1958** [comment]
@jzp820927 我跟着那个comment发现云端shell是按不了的，然后觉得可能是浏览器问题，换了chrome就正常了.......连用shell都不用

**Comment by jzp820927** [comment]
那你之前用的什么浏览器？难道是 360 ？
