### ISSUE TITLE
3.2.9 无法使用

### ISSUE THREAD

**Issue by ywaby** [XX-net/XX-Net#4839]
压缩包无法打开，进而导致无法更新
![default](https://cloud.githubusercontent.com/assets/12198203/21750366/7ba2d430-d5ec-11e6-8991-c2b9cbfe34a2.png)

**Comment by jzp820927** [comment]
不能自动更新就手动更新包，可能是由于网络干扰导致下载本下载不完整，所以无法解压吧

**Comment by ywaby** [comment]
就是手动的zip解包，多次下载都是这样，你的确定没这个问题？

**Comment by wenliyang** [comment]
直连下载有问题的话，请翻墙下载试

**Comment by jzp820927** [comment]
要先确定下载完整，如果下载完整了，肯定可以解压。
