### ISSUE TITLE
证书已过期

### ISSUE THREAD

**Issue by out-sider** [XX-net/XX-Net#4847]
版本3.2.9
自带CA证书在1月9号也就是今天过期了，于是访问对应网站都会出现安全提醒

**Comment by jzp820927** [comment]
删除 CA.crt 和 certs/ 目录，删除导入浏览器的证书，重启 XX，重新导入新生成的证书。

**Comment by 674273563** [comment]
好的谢谢

**Comment by out-sider** [comment]
删除certs/CA.crt和会重新在原路径生成。
删除证书后重启浏览器，再启动xx，无论点不点uac都还是会出现隐私问题

**Comment by out-sider** [comment]
![qq 20170110183731](https://cloud.githubusercontent.com/assets/8955160/21803199/fe6eb58c-d763-11e6-840f-c7edeeac16e6.png)

**Comment by jzp820927** [comment]
你还要把之前导入浏览器的证书删除，再把新生成的证书，导入到了起来

**Comment by out-sider** [comment]
解决了。。原来是我没仔细看，要重新导入一遍
