### ISSUE TITLE
请教一个问题：不考虑安全性，这个ip可用吗？

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#485]
61.250.95.138

    curl -k -m 20 --resolve xxnet-13.appspot.com:443:61.250.95.138 https://xxnet-13.appspot.com/_gh/

>GoAgent 服务端已经在 2015-03-28 08:15:22 升级到 3.2.0 版本, 请更新您的客户端。

正常的输出应该是

    curl -k -m 20 --resolve xxnet-13.appspot.com:443:173.194.201.141 https://xxnet-13.appspot.com/_gh/

>GoAgent Python Server 3.2.0 works, deployed at 2015-03-28 08:15:22

证书不是Google的，用gogotester检测是NA

不用xxnet-13.appspot.com，输出为
    
    curl -k -m 20 --resolve flycraftfly.appspot.com:443:61.250.95.138 https://flycraftfly.appspot.com/_gh/
--
    <html><head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>404 Not Found</title>
    </head>
    <body text=#000000 bgcolor=#ffffff>
    <h1>Error: Not Found</h1>
    <h2>The requested URL <code>/ntop/_gh/</code> was not found on this server.</h2>
    <h2></h2>
    </body></html>

其中/ntop/_gh/ 表示好像把地址转换成了https://flycraftfly.appspot.com/ntop/_gh/

**Comment by xxnet** [comment]
是不是发现这个ip的证书有问题？

XX-Net对证书做了判断的，假证书的ip会被剔除

在 2015年6月1日 上午9:42，linhua55 <notifications@github.com>写道：

**Comment by linhua55** [comment]
是

    issuer: C=KR; ST=Gyeonggi-do; L=Sungnam-si; O=Actela Co., Ltd; OU=Research Institute; CN=Actela Server CA; emailAddress=support@actela.com

不知道像这样的ip有多少，是否可以利用(像浏览https站，youtube)?

**Comment by xxnet** [comment]
这个似乎是一家提供网络安全、加速的公司。

如果你的网络帐号安全不敏感，不怕泄漏，是可以用的。
假如这个ip背后的管理员想监听的的通讯过程，那他可以获取到你所有的网络帐号权限、密码等信息。

个人不建议去使用这样的ip，因为好用的google ip并不难找，没有必要去冒这个风险。

2015-06-01 15:26 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet 您的意思是，默认情况下XX-Net会排除证书错误的不可靠IP（但也许可用）？但如果用户愿意的话，是可以手动设定使用这些IP的？

**Comment by xxnet** [comment]
是的， XX-Net会检查ip的证书。

要跳过证书检查，目前只能手动改代码，不建议这么做，因为可用ip很多，没有必要冒险。


在 2015年6月18日 上午12:31，simonasd <notifications@github.com>写道：
