### ISSUE TITLE
AppID流量用完的问题

### ISSUE THREAD

**Issue by Ch-Song** [XX-net/XX-Net#4851]
使用最新版xx-net还有chrome64位
部署appID显示我成功部署了2个，然后配置里面也成功保存了。但是他提示我没有流量了，我去检查我的2个APPID，发现一个0.7/1g 另一个没有数据，不知道这是什么问题？

![image](https://cloud.githubusercontent.com/assets/21030720/21796719/804030b4-d745-11e6-95f9-86c12bc3f96f.png)

![image](https://cloud.githubusercontent.com/assets/21030720/21796726/8aaffd36-d745-11e6-98f4-29ed107bf89d.png)
这是两个appID的使用情况 请问一下这是啥情况

**Comment by jzp820927** [comment]
能正常使用吗？

**Comment by Ch-Song** [comment]
不能用了，然后提示我流量用光了，然后我去检查appengine的页面发现第二个appID根本没流量....现在好像过了刷新的时间了，能用了

**Comment by jzp820927** [comment]
如果部署成功了，流量消耗很快，则可能是被盗用？其他想不出什么问题，你可以观察几天，如果连续几天流量快速耗尽，则可以加密码重新部署，或者把 appid 改个名字。

**Comment by Ch-Song** [comment]
不是很快被耗尽，是我从appengine的数据来看是没有用光，第二个ID还没用，但是xxnet告诉我用光了

**Comment by jzp820927** [comment]
这个不太可能吧，你的意思是，APPID 的流量实际还有，但是 XX 说用完了？

**Comment by Ch-Song** [comment]
是的 上面那两张图是我的两个appID的使用情况

**Comment by jzp820927** [comment]
XX 是在哪儿提示用完的？

**Comment by Ch-Song** [comment]
在网页打开http://127.0.0.1:8085/ 提醒有没有打开xxnet的那个位置

**Comment by jzp820927** [comment]
能截图发来看看麽？不是太清楚

**Comment by wea76339** [comment]
我的也是，appengine显示用了0.79，但http://127.0.0.1:8085/却显示超量了，不能用了。因为我是苹果最新系统，部署不能顺利完成，12个，只有一个成功，其它11个ID在http://127.0.0.1:8085/页都显示无效。

**Comment by jzp820927** [comment]
没部署成功的，可以重新部署，公共 appid，流量用超很快，如果自己的 appid 只有1个的话，应该也不够。
