### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by Chroslen** [XX-net/XX-Net#4857]
---
## 问题内容
使用xxnet-3.2.8，mac os 10.12.2
第一次使用xxnet，浏览器代理设置了了xxnet 自动切换，也试过手动设置了系统代理，都还是请我检查浏览器代理设置。
请教一下大家我该如何设置。

#### 诊断信息
XX-Net Status:

sys-platform: x86_64, Darwin-16.3.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64
os-release: 16.3.0
os-detail: Release:10.12.2; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:65 good:30
network-status: OK
connected-link: new:1 used:0
worker: h1:25 h2:4
scan-ip-thread-num: 50
ip-quality: 634
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志

Jan 11 16:55:01.158 - [INFO] use config_path:/Users/yuanyuanzhang/Downloads/XX-Net-3.2.8/data/x_tunnel/client.json
Jan 11 16:55:01.159 - [INFO] Use proxy:127.0.0.1:8087
Jan 11 16:55:01.159 - [DEBUG] x-tunnel no account
Jan 11 16:55:01.159 - [WARNING] x-tunnel session not start
Jan 11 16:55:01.159 - [INFO] Socks5 server listen:127.0.0.1:1080.

---

**Comment by horizon365** [comment]
同样遇到。怎么就证书和代理Fail了？
`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2434
network-status: OK
connected-link: new:3 used:0
worker: h1:19 h2:1
scan-ip-thread-num: 0
ip-quality: 424
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by jzp820927** [comment]
有没有导入证书？

**Comment by Chroslen** [comment]
@jzp820927， 应该是有导入证书的，我刚删了一下，又放回去了

**Comment by jzp820927** [comment]
如果导入了，就直接测试代理是否可用。有时候状态页虽然有报错，但其实代理是可以正常使用的。

**Comment by Chroslen** [comment]
@jzp820927，谢谢大神！的确是可以用了。
