### ISSUE TITLE
求助！如何删除x_tunnel！

### ISSUE THREAD

**Issue by mssues** [XX-net/XX-Net#4859]

**Comment by mssues** [comment]
不好意思我写错了，我是想默认不启用x_tunnel

**Comment by jzp820927** [comment]
我觉得你适合用 XXMINI

**Comment by wenliyang** [comment]
3如何去掉winsxs文件夹，它有用吗？和那个文件关联？

这个问题和XX-Net有关？你去搜索下就知道winsxs这文件夹的重要性了吧
