### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by bodhijaa** [XX-net/XX-Net#486]
启动时看不到状态，进入start.sh, 显示如下：

#!/bin/bash

SCRIPTPATH=`dirname "${BASH_SOURCE[0]}"`
cd $SCRIPTPATH

if hash python2 2>/dev/null; then
    python2 launcher/start.py
else
    python launcher/start.py
fi

不知是什么原因？

**Comment by bodhijaa** [comment]
知道是啥原因了 - -

**Comment by xxnet** [comment]
start.sh 启动，输出什么信息？

2015-06-01 18:09 GMT+08:00 bodhijaa <notifications@github.com>:

**Comment by bodhijaa** [comment]
啊，我忘了存了 - - 

不过我这个问题可能和软件本身关系不大。昨天下午貌似有一段XX-NET的所有IP都被封了，不停的扫IP，完全连不上，在Goagent的论坛里也看到有人反映这个问题，我正好就是那个时候启动程序，所以状态页没法显示，晚上重新启动，就好了。
