### ISSUE TITLE
使用XXNET过程中经常浏览器消失（没监测过进程是否消失）

### ISSUE THREAD

**Issue by xingshu1990** [XX-net/XX-Net#4862]
## 问题内容
使用XXNET的时候，浏览器经常卡死。
初期判断是浏览器插件太多，把浏览器卡死。
但是后面在网咖也是使用XXNET，也同样是把浏览器消失。
使用的浏览器有360极速浏览器、chrome。
和电脑系统程序XP W7无关，家里的电脑也是W7，同样经常浏览器消失。

后 在github上搜索问题，说是【自动调整扫描线程数】需要调整，
然而调整为1，使用过程中，浏览器也是同样消失。
有GAE AppID，
GAEProxy日志正常，
但好像获取不到浏览器消失时的数据。

#### 获取诊断信息
XX-Net Status:

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:191
network-status: OK
connected-link: new:2 used:0
worker: h1:15 h2:4
scan-ip-thread-num: 10
ip-quality: 641
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志
Jan 12 13:39:38.694 - [INFO] SSL use version:TLSv1_2
Jan 12 13:39:38.772 - [DEBUG] network is ok, cost:875 ms
Jan 12 13:39:39.257 - [INFO] OpenSSL support alpn
Jan 12 13:39:39.428 - [INFO] load ip range file:D:\\\XX-Net-3.1.19\data\gae_proxy\ip_range.txt
Jan 12 13:39:39.897 - [INFO] load google ip_list num:3000, gws num:3000
Jan 12 13:39:39.975 - [INFO] OpenSSL support alpn
Jan 12 13:39:39.975 - [DEBUG] get ip:202.86.162.172 t:141
Jan 12 13:39:40.163 - [DEBUG] get ip:173.194.22.167 t:171
Jan 12 13:39:40.272 - [DEBUG] ## GAEProxy set keep_running: True
Jan 12 13:39:40.272 - [INFO] ------------------------------------------------------
Jan 12 13:39:40.272 - [INFO] Python Version : 2.7.11
Jan 12 13:39:40.272 - [INFO] OS : Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
Jan 12 13:39:40.272 - [INFO] Listen Address : 127.0.0.1:8087
Jan 12 13:39:40.272 - [INFO] GAE APPID : wpc-0001-1227
Jan 12 13:39:40.272 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jan 12 13:39:40.272 - [INFO] ------------------------------------------------------
Jan 12 13:39:40.382 - [DEBUG] create_ssl update ip:202.86.162.172 time:155 h2:1
Jan 12 13:39:40.382 - [DEBUG] get ip:118.143.88.168 t:407
Jan 12 13:39:40.382 - [DEBUG] create_ssl update ip:173.194.22.167 time:78 h2:0
Jan 12 13:39:40.663 - [DEBUG] get ip:92.226.2.115 t:437
Jan 12 13:39:43.397 - [DEBUG] get ip:87.79.22.238 t:546
Jan 12 13:39:43.397 - [DEBUG] get ip:122.154.76.59 t:578
Jan 12 13:39:43.413 - [INFO] PAC from:127.0.0.1:10462 GET /proxy.pac
Jan 12 13:39:43.413 - [INFO] PAC from:127.0.0.1:10463 GET /proxy.pac
Jan 12 13:39:43.897 - [DEBUG] get ip:80.252.129.13 t:578
Jan 12 13:39:43.975 - [DEBUG] create_ssl update ip:118.143.88.168 time:421 h2:0
Jan 12 13:39:44.006 - [INFO] scan_ip add ip:157.157.135.46 time:2500
Jan 12 13:39:44.022 - [INFO] remove_slowest_ip:181.224.253.115 handshake_time:625, fails:3
Jan 12 13:39:44.084 - [DEBUG] create_ssl update ip:122.154.76.59 time:515 h2:1
Jan 12 13:39:44.194 - [DEBUG] create_ssl update ip:87.79.22.238 time:514 h2:0
Jan 12 13:39:44.616 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Jan 12 13:39:44.678 - [DEBUG] 92.226.2.115 fail:timeout('timed out',)
Jan 12 13:39:44.678 - [DEBUG] report_connect_fail:92.226.2.115
Jan 12 13:39:44.709 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=e557aa67-91aa-4270-a0a3-223f04e973f9&version=3.2.8&platform=Windows-XP-5.1.2600-SP3
Jan 12 13:39:44.787 - [DEBUG] create_ssl update ip:80.252.129.13 time:577 h2:0
Jan 12 13:39:44.928 - [INFO] DIRECT t:218 s:1674 200 xxnet-update.appspot.com /update.json?uuid=e557aa67-91aa-4270-a0a3-223f04e973f9&version=3.2.8&platform=Windows-XP-5.1.2600-SP3
Jan 12 13:39:45.162 - [DEBUG] GET http://www.twitter.com/xxnet
Jan 12 13:39:45.194 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Jan 12 13:39:45.256 - [DEBUG] GET http://www.twitter.com/xxnet
Jan 12 13:39:45.272 - [DEBUG] GET http://www.twitter.com/xxnet
Jan 12 13:39:45.287 - [DEBUG] GET http://www.twitter.com/xxnet
Jan 12 13:39:50.928 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Chromium
Jan 12 13:39:50.943 - [DEBUG] get ip:198.7.237.234 t:610
Jan 12 13:39:51.115 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Chromium
Jan 12 13:39:51.271 - [INFO] GAE t:342 s:28 POST https://clients1.google.com/tbproxy/af/query?client=Chromium h2_req:15,get_response:327
Jan 12 13:39:51.365 - [INFO] GAE t:250 s:28 POST https://clients1.google.com/tbproxy/af/query?client=Chromium get_response:250
Jan 12 13:39:51.443 - [DEBUG] get ip:24.139.135.91 t:625
Jan 12 13:39:51.896 - [DEBUG] create_ssl update ip:198.7.237.234 time:625 h2:1
Jan 12 13:39:51.943 - [DEBUG] get ip:113.171.247.87 t:656
Jan 12 13:39:52.396 - [DEBUG] create_ssl update ip:24.139.135.91 time:625 h2:0
Jan 12 13:39:52.443 - [DEBUG] get ip:186.46.140.94 t:656
Jan 12 13:39:52.896 - [DEBUG] get ip:103.233.37.78 t:717
Jan 12 13:39:52.943 - [DEBUG] get ip:103.233.37.95 t:733
Jan 12 13:39:53.318 - [DEBUG] create_ssl update ip:186.46.140.94 time:594 h2:0
Jan 12 13:39:53.396 - [DEBUG] get ip:115.164.12.183 t:750
Jan 12 13:39:53.443 - [DEBUG] get ip:186.160.223.112 t:764
Jan 12 13:39:53.943 - [DEBUG] get ip:41.206.96.76 t:765
Jan 12 13:39:53.974 - [DEBUG] create_ssl update ip:103.233.37.95 time:687 h2:0
Jan 12 13:39:53.974 - [DEBUG] get ip:181.192.63.204 t:796
Jan 12 13:39:54.318 - [DEBUG] get ip:189.7.75.172 t:811
Jan 12 13:39:54.443 - [DEBUG] get ip:177.101.143.248 t:812
Jan 12 13:39:54.568 - [DEBUG] create_ssl update ip:186.160.223.112 time:750 h2:0
Jan 12 13:39:54.943 - [DEBUG] get ip:103.21.169.252 t:828
Jan 12 13:39:54.974 - [DEBUG] get ip:186.251.10.58 t:890
Jan 12 13:39:55.162 - [DEBUG] create_ssl update ip:103.233.37.78 time:1875 h2:0
Jan 12 13:39:55.177 - [DEBUG] create_ssl update ip:181.192.63.204 time:796 h2:0
Jan 12 13:39:55.177 - [DEBUG] get ip:41.184.60.43 t:953
Jan 12 13:39:55.443 - [DEBUG] get ip:181.30.242.159 t:953
Jan 12 13:39:55.552 - [DEBUG] create_ssl update ip:189.7.75.172 time:812 h2:0
Jan 12 13:39:55.568 - [DEBUG] get ip:177.131.1.239 t:969
Jan 12 13:39:55.943 - [DEBUG] get ip:201.218.56.154 t:985
Jan 12 13:39:55.943 - [DEBUG] 113.171.247.87 fail:timeout('timed out',)
Jan 12 13:39:55.943 - [DEBUG] report_connect_fail:113.171.247.87
Jan 12 13:39:55.943 - [DEBUG] get ip:77.234.90.76 t:985
Jan 12 13:39:56.162 - [DEBUG] get ip:210.187.22.244 t:985
Jan 12 13:39:56.287 - [DEBUG] create_ssl update ip:103.21.169.252 time:1016 h2:1
Jan 12 13:39:56.443 - [DEBUG] get ip:87.79.22.209 t:985
Jan 12 13:39:56.552 - [DEBUG] get ip:201.6.16.15 t:1000
Jan 12 13:39:56.693 - [DEBUG] create_ssl update ip:177.131.1.239 time:750 h2:0
Jan 12 13:39:56.693 - [DEBUG] create_ssl update ip:77.234.90.76 time:500 h2:0
Jan 12 13:39:56.943 - [DEBUG] get ip:178.132.81.97 t:1000
Jan 12 13:39:57.193 - [DEBUG] create_ssl update ip:41.184.60.43 time:1531 h2:0
Jan 12 13:39:57.193 - [DEBUG] get ip:177.55.62.78 t:796
Jan 12 13:39:57.287 - [DEBUG] get ip:181.192.63.212 t:1000
Jan 12 13:39:57.443 - [DEBUG] get ip:177.124.192.124 t:1000
Jan 12 13:39:57.693 - [DEBUG] get ip:216.58.195.161 t:1000
Jan 12 13:39:57.693 - [DEBUG] get ip:216.58.206.21 t:1000
Jan 12 13:39:57.802 - [DEBUG] create_ssl update ip:178.132.81.97 time:578 h2:0
Jan 12 13:39:57.880 - [DEBUG] create_ssl update ip:181.30.242.159 time:1968 h2:0
Jan 12 13:39:57.943 - [DEBUG] get ip:181.30.242.213 t:1000
Jan 12 13:39:57.943 - [DEBUG] 41.206.96.76 fail:timeout('timed out',)
Jan 12 13:39:57.943 - [DEBUG] report_connect_fail:41.206.96.76
Jan 12 13:39:57.943 - [DEBUG] get ip:187.86.12.182 t:1000
Jan 12 13:39:58.318 - [DEBUG] create_ssl update ip:177.55.62.78 time:750 h2:0
Jan 12 13:39:58.318 - [DEBUG] get ip:66.96.224.147 t:1000
Jan 12 13:39:58.443 - [DEBUG] get ip:216.11.246.73 t:1014
Jan 12 13:39:58.443 - [DEBUG] 177.101.143.248 fail:timeout('timed out',)
Jan 12 13:39:58.443 - [DEBUG] report_connect_fail:177.101.143.248
Jan 12 13:39:58.443 - [DEBUG] get ip:80.97.208.112 t:1014
Jan 12 13:39:58.443 - [DEBUG] create_ssl update ip:181.192.63.212 time:766 h2:0
Jan 12 13:39:58.474 - [DEBUG] create_ssl update ip:216.58.195.161 time:530 h2:1
Jan 12 13:39:58.615 - [DEBUG] create_ssl update ip:216.58.206.21 time:625 h2:1
Jan 12 13:39:58.802 - [DEBUG] get ip:62.209.24.32 t:1015
Jan 12 13:39:58.880 - [DEBUG] get ip:187.86.12.188 t:1015
Jan 12 13:39:58.943 - [DEBUG] get ip:200.77.139.80 t:1016
Jan 12 13:39:58.943 - [DEBUG] 115.164.12.183 fail:error(' certficate is none',)
Jan 12 13:39:58.943 - [DEBUG] report_connect_fail:115.164.12.183
Jan 12 13:39:58.943 - [DEBUG] get ip:191.243.156.31 t:1016
Jan 12 13:39:58.974 - [DEBUG] 186.251.10.58 fail:timeout('timed out',)
Jan 12 13:39:58.974 - [DEBUG] report_connect_fail:186.251.10.58
Jan 12 13:39:58.974 - [DEBUG] get ip:201.157.30.140 t:1016
Jan 12 13:39:59.333 - [DEBUG] create_ssl update ip:216.11.246.73 time:592 h2:0
Jan 12 13:39:59.474 - [DEBUG] create_ssl update ip:181.30.242.213 time:1030 h2:0
Jan 12 13:39:59.677 - [DEBUG] ip:92.226.2.115 real fail
Jan 12 13:39:59.833 - [DEBUG] create_ssl update ip:200.77.139.80 time:639 h2:1
Jan 12 13:39:59.943 - [DEBUG] 201.218.56.154 fail:timeout('timed out',)
Jan 12 13:39:59.943 - [DEBUG] report_connect_fail:201.218.56.154
Jan 12 13:40:00.130 - [DEBUG] create_ssl update ip:62.209.24.32 time:890 h2:0
Jan 12 13:40:00.162 - [DEBUG] 210.187.22.244 fail:timeout('timed out',)
Jan 12 13:40:00.162 - [DEBUG] report_connect_fail:210.187.22.244
Jan 12 13:40:00.333 - [DEBUG] create_ssl update ip:80.97.208.112 time:1592 h2:1
Jan 12 13:40:00.396 - [DEBUG] create_ssl update ip:187.86.12.188 time:1046 h2:1
Jan 12 13:40:00.443 - [DEBUG] 87.79.22.209 fail:timeout('timed out',)
Jan 12 13:40:00.443 - [DEBUG] report_connect_fail:87.79.22.209
Jan 12 13:40:00.552 - [DEBUG] 201.6.16.15 fail:timeout('timed out',)
Jan 12 13:40:00.552 - [DEBUG] report_connect_fail:201.6.16.15
Jan 12 13:40:01.443 - [DEBUG] 177.124.192.124 fail:timeout('timed out',)
Jan 12 13:40:01.443 - [DEBUG] report_connect_fail:177.124.192.124
Jan 12 13:40:01.943 - [DEBUG] 187.86.12.182 fail:timeout('timed out',)
Jan 12 13:40:01.943 - [DEBUG] report_connect_fail:187.86.12.182
Jan 12 13:40:02.943 - [DEBUG] 191.243.156.31 fail:timeout('timed out',)
Jan 12 13:40:02.943 - [DEBUG] report_connect_fail:191.243.156.31
Jan 12 13:40:02.974 - [DEBUG] 201.157.30.140 fail:timeout('timed out',)
Jan 12 13:40:02.974 - [DEBUG] report_connect_fail:201.157.30.140
Jan 12 13:40:03.943 - [DEBUG] 66.96.224.147 fail:error(' certficate is none',)
Jan 12 13:40:03.943 - [DEBUG] report_connect_fail:66.96.224.147
Jan 12 13:40:05.942 - [INFO] scan_ip add ip:63.135.48.145 time:453
Jan 12 13:40:05.942 - [INFO] remove_slowest_ip:189.215.200.45 handshake_time:625, fails:3
Jan 12 13:40:10.942 - [DEBUG] ip:113.171.247.87 real fail
Jan 12 13:40:14.301 - [INFO] scan_ip add ip:92.246.12.223 time:610
Jan 12 13:40:14.317 - [INFO] remove_slowest_ip:212.112.37.86 handshake_time:1625, fails:2
Jan 12 13:40:15.942 - [DEBUG] ip:41.206.96.76 real fail
Jan 12 13:40:20.941 - [DEBUG] ip:177.101.143.248 real fail
Jan 12 13:40:25.941 - [DEBUG] ip:115.164.12.183 real fail
Jan 12 13:40:27.941 - [DEBUG] restore ip:186.251.10.58
Jan 12 13:40:32.394 - [DEBUG] 173.194.22.167 close:host pool alive_timeout
Jan 12 13:40:32.394 - [DEBUG] ssl_closed 173.194.22.167
Jan 12 13:40:32.941 - [DEBUG] ip:201.218.56.154 real fail
Jan 12 13:40:36.737 - [DEBUG] GAE POST https://accounts.google.com/ListAccounts?source=ChromiumBrowser&json=standard
Jan 12 13:40:36.987 - [INFO] GAE t:250 s:163 POST https://accounts.google.com/ListAccounts?source=ChromiumBrowser&json=standard get_response:250
Jan 12 13:40:37.940 - [DEBUG] ip:210.187.22.244 real fail
Jan 12 13:40:42.940 - [DEBUG] ip:87.79.22.209 real fail
Jan 12 13:40:44.706 - [DEBUG] restore ip:201.6.16.15

**Comment by jzp820927** [comment]
浏览器消失，感觉应该是系统方面的问题，或者浏览器的问题，应该和 XX 关系不大吧？

**Comment by xingshu1990** [comment]
问题是家里W7电脑 用chrome 360极速 也是一样会卡死啊

**Comment by jzp820927** [comment]
看看 CPU 和 内存，有没有什么异常。
