### ISSUE TITLE
archlinux XX-Net/start: 行 32:  3371 段错误:(核心已转储)${PYTHON} code/${VERSION}/launcher/start.py

### ISSUE THREAD

**Issue by yyy123zc** [XX-net/XX-Net#4872]
XX-Net version:default
Jan 14 12:18:12.335 - [INFO] use build-in openssl lib
Jan 14 12:18:12.391 - [INFO] start XX-Net 3.2.9
Jan 14 12:18:12.391 - [DEBUG] start confirm_xxnet_exit
Jan 14 12:18:12.393 - [DEBUG] good, xxnet:8087 cleared!
Jan 14 12:18:12.394 - [DEBUG] good, xxnet:8085 clear!
Jan 14 12:18:12.394 - [DEBUG] finished confirm_xxnet_exit
/home/dzqn/XX-Net/start: 行 32: 11301 段错误               (核心已转储)${PYTHON} code/${VERSION}/launcher/start.py

archlinux系统，两周前XX-Net运行正常，在上周pacman -Syyu升级后，出现此错误。搜索后按照
#1464
修改launcher/start.py中 threading.stack_size(128*1024)为其它值（比如3*1024*1024），一样的错误。没找到其它参考解决方案，特来求助。

OS: Arch Linux 
Kernel: x86_64 Linux 4.8.13-1-ARCH
Shell: bash 4.4.5
DE: Cinnamon 3.2.8
WM: Muffin
Python:2.7.13
OpenSSL:1.0.2.j-1
python-pyopenssl-16.2.0-2
python2-pyopenssl-16.2.0-2

**Comment by jzp820927** [comment]
第一次遇到这种错误。应该是升级造成的，和 XX 相关的，都有什么升级了？

**Comment by yyy123zc** [comment]
和xx-net相关的应该只有python2.7.13、python3.6.0和python-pyopenssl-16.2.0-2、python2-pyopenssl-16.2.0-2外应该没别的了
@jzp820927

**Comment by jzp820927** [comment]
你按那个 issues 说的，把 threading.stack_size(1281024) 删了，试试看

**Comment by yyy123zc** [comment]
虽然不知道为什么，但刚刚下载XX-Net-python3版本运行正常。
@jzp820927谢谢你的帮助

**Comment by jzp820927** [comment]
难道是和 python2.7.13 兼容有问题？

**Comment by HE1HE** [comment]
@yyy123zc 我也同样的问题，“XX-Net-python3版本”是什么意思？

**Comment by jzp820927** [comment]
@HE1HE https://github.com/XX-net/XX-Net/tree/python3

**Comment by yeahwu** [comment]
已修复，你试试！
https://github.com/XX-net/XX-Net/archive/master.zip
