### ISSUE TITLE
Medium网站无法写作

### ISSUE THREAD

**Issue by zjplab** [XX-net/XX-Net#4874]
大家可以自己到Medium网站看看，注册一个号，右上角头像点下来有没有write a story，如果没有的话应该是和我一样就变成了How do I write .
Medium自己的网站诊断记录(官方答疑回复是认为是我vpn/proxy的问题，问题锁定在xxnet身上了..)
useragent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 AppEngine-Google; (+http://code.google.com/appengine; appid: s~shareahagfw)
browser = appengine-google
family = 
os = windows
version = 0
supportsDesktopEdit = false
supportsInteract = false
supportsView = true
isMobile = false
isTablet = false
isNative = false
supportsFileAPI = false
isTier1 = false
clientVersion = 
unknownParagraphsBad = false
clientChannel = 
supportsRealScrollEvents = false
supportsVhUnits = false
ruinsViewportSections = false
supportsHtml5Video = false
supportsMagicUnderlines = false
isWebView = false
isFacebookWebView = false
supportsProgressiveMedia = false
supportsPromotedPosts = true
isBot = false
supportsScrollableMetabar = false

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:599
network-status: OK
connected-link: new:2 used:0
worker: h1:15 h2:12
scan-ip-thread-num: 200
ip-quality: 564
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
#### 获取日志

Jan 14 18:58:57.559 - [DEBUG] GAE POST https://medium.com/_/api/stream-items?name=homeCatalogs&limit=3&maxPreviewLength=3
Jan 14 18:58:57.566 - [DEBUG] GAE GET https://medium.com/_/api/tags?source=followed
Jan 14 18:58:57.962 - [INFO] GAE t:395 s:119 GET https://medium.com/_/api/tags?source=followed get_response:391
Jan 14 18:58:58.284 - [DEBUG] GAE GET https://medium.com/_/activity-status
Jan 14 18:58:58.745 - [INFO] GAE t:460 s:135 GET https://medium.com/_/activity-status get_response:455
Jan 14 18:58:59.878 - [INFO] GAE t:2319 s:18830 POST https://medium.com/_/api/stream-items?name=homeCatalogs&limit=3&maxPreviewLength=3 get_response:2298,h1_finish[SP:1018260]:19
Jan 14 18:59:02.857 - [DEBUG] 113.171.253.79 close:host pool alive_timeout
Jan 14 18:59:02.864 - [DEBUG] ssl_closed 113.171.253.79
Jan 14 18:59:03.310 - [DEBUG] GAE POST https://medium.com/_/batch
Jan 14 18:59:03.312 - [DEBUG] GAE GET https://medium.com/me/activity
Jan 14 18:59:03.826 - [INFO] GAE t:513 s:128 GET https://medium.com/me/activity get_response:509
Jan 14 18:59:03.853 - [INFO] GAE t:542 s:119 POST https://medium.com/_/batch h1_get_head:537
Jan 14 18:59:04.008 - [DEBUG] get ip:202.86.162.172 t:172
Jan 14 18:59:04.318 - [DEBUG] create_ssl update ip:202.86.162.172 time:197 h2:1
Jan 14 18:59:04.318 - [DEBUG] get ip:203.66.155.56 t:174
Jan 14 18:59:04.866 - [DEBUG] 186.160.223.104 close:host pool alive_timeout
Jan 14 18:59:04.867 - [DEBUG] ssl_closed 186.160.223.104
Jan 14 18:59:07.145 - [INFO] GAE CONNECT clients4.google.com:443
Jan 14 18:59:07.188 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=7MIzOCFa0RXbrzwZR4ZHGg%3D%3D
Jan 14 18:59:07.189 - [DEBUG] host_conn_pool clients4.google.com get:186.160.223.113 handshake:612
Jan 14 18:59:07.190 - [DEBUG] get ip:66.96.224.147 t:312
Jan 14 18:59:07.646 - [INFO] DIRECT chucked t:457 s:2372 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=7MIzOCFa0RXbrzwZR4ZHGg%3D%3D
Jan 14 18:59:07.654 - [INFO] GAE CONNECT clients4.google.com:443
Jan 14 18:59:07.687 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=7MIzOCFa0RXbrzwZR4ZHGg%3D%3D
Jan 14 18:59:07.687 - [DEBUG] host_conn_pool clients4.google.com get:186.160.223.113 handshake:612
Jan 14 18:59:07.691 - [DEBUG] get ip:66.96.224.222 t:325
Jan 14 18:59:08.137 - [INFO] DIRECT chucked t:450 s:435 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=7MIzOCFa0RXbrzwZR4ZHGg%3D%3D
Jan 14 18:59:08.193 - [DEBUG] get ip:113.171.253.79 t:452
Jan 14 18:59:08.319 - [DEBUG] 203.66.155.56 fail:timeout('timed out',)
Jan 14 18:59:08.319 - [DEBUG] report_connect_fail:203.66.155.56
Jan 14 18:59:08.319 - [DEBUG] get ip:61.91.161.217 t:466
Jan 14 18:59:08.608 - [DEBUG] create_ssl update ip:66.96.224.222 time:226 h2:1
Jan 14 18:59:08.695 - [DEBUG] get ip:63.117.215.88 t:564
Jan 14 18:59:08.780 - [DEBUG] create_ssl update ip:66.96.224.147 time:319 h2:1
Jan 14 18:59:08.818 - [DEBUG] create_ssl update ip:61.91.161.217 time:318 h2:1
Jan 14 18:59:08.947 - [DEBUG] create_ssl update ip:113.171.253.79 time:457 h2:0
Jan 14 18:59:10.148 - [DEBUG] create_ssl update ip:63.117.215.88 time:1178 h2:1
Jan 14 18:59:13.245 - [INFO] GAE CONNECT clients1.google.com:443
Jan 14 18:59:13.281 - [DEBUG] GAE CONNECT Direct POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Jan 14 18:59:13.281 - [DEBUG] host_conn_pool clients1.google.com get:95.180.157.48 handshake:725
Jan 14 18:59:13.689 - [INFO] DIRECT chucked t:407 s:28 200 clients1.google.com /tbproxy/af/query?client=Google%20Chrome
Jan 14 18:59:18.825 - [DEBUG] restore ip:203.66.155.56
Jan 14 18:59:19.645 - [DEBUG] GAE POST https://medium.com/_/batch
Jan 14 18:59:20.089 - [INFO] GAE t:444 s:119 POST https://medium.com/_/batch get_response:440

**Comment by jzp820927** [comment]
其他代理有没有这个问题呢？

**Comment by zjplab** [comment]
怎么直连？没了gae国内连不上的

**Comment by jzp820927** [comment]
把下面的写到 hosts 里面，然后就可以用 https 访问了。

104.16.120.127	medium.com
104.16.120.145	cdn-static-1.medium.com
104.16.120.145	cdn-images-1.medium.com
103.245.222.101	cdn-images-2.medium.com

**Comment by zjplab** [comment]
嗯，确实管用，谢谢
