### ISSUE TITLE
您的连接不是私密连接

### ISSUE THREAD

**Issue by Mrknowledge** [XX-net/XX-Net#4891]
![image](https://cloud.githubusercontent.com/assets/5043454/22023366/d16f0eb8-dd00-11e6-9104-63baf80998bb.png)

**Comment by Mrknowledge** [comment]
升级到3.2.8之后报google网站的证书过期，重新导入证书问题依旧，twitter可以正常使用，就是google https证书过期，请问是ca.crt的google证书没更新吗？

**Comment by jzp820927** [comment]
删除 data，删除导入浏览器的证书，重启 XX，重新导入新证书到浏览器

**Comment by Mrknowledge** [comment]
@jzp820927  在此分享一下，如果自己直接去删除证书，然后重新导入，不行。
按你的方法，解决了。
