### ISSUE TITLE
关于安卓使用xx-net以及x-tunnel是否能用通过socks5 代理APP来使用的疑问

### ISSUE THREAD

**Issue by JaminYoung** [XX-net/XX-Net#4892]
我想用手机通过xx-net来翻。
有参考过wiki的“为其他设备提供代理服务”那一节内容以及issues里有类似相关的提问。
我目前的修改按照wiki的修改：
允许远程访问Web界面：
修改 XX-Net/data/launcher/config.yaml
modules:{
launcher:{ allow_remote_connect:1 }

允许GAE_proxy提供远程代理服务：
修改 XX-Net/data/gae_proxy/config.ini
[listen] ip = 0.0.0.0 

允许X_tunnel提供远程代理:
修改 XX-Net/data/x_tunnel/client.json
加入一行：
"socks_host": "0.0.0.0",

然后再按照Issues里有看到的在data\gae_proxy路径新建manual.ini文件 里面写[listen] ip=0.0.0.0

然后手机有安装data\gae_proxy下的CA证书，选择WLAN安装

然后请问下一步该怎么做呢？手机还要做什么配置吗？

我不懂这些，也不知道该搜索什么关键词。是通过电脑开热点给手机吗？还有，我按照wiki里修改时，发现，在x_tunnel文件加入"socks_host": "0.0.0.0",后重启xx-net，没有弹出web控制页面，也打不开。

还有一个问题是，我最近通过捐赠appid获得不少x_tunnel的流量。我看到x_tunnel是SOCKS5代理的？那这是否可以通过手机一些代理app如proxydroid,或者影梭之类的直接配置使用呢？如果可以的话，该怎么配置？不行的话，安卓手机该如何使用x_tunnel呢？

抱歉啊，问题问的有些多，因为也憋了很久==

**Comment by jzp820927** [comment]
要保证手机和 PC 在同一个局域网，然后手机上设置代理为 电脑共享的代理就行了

**Comment by JaminYoung** [comment]
首先，十分感谢您的回答。恕我愚钝，还是不太明白。关于“手机设置代理为电脑共享代理”是该怎么做？手机端该如何配置呢？除里安装证书之外？另外，想shadowsocks 这个APP就可以做代理socks5，但是不知道怎么配置，比如远程端口，本地端口，密码等这些该怎么填写呢？

**Comment by jzp820927** [comment]
看样子，你连基本的操作都不太清楚，一两句话，也讲不清楚，建议你 google 搜索，“手机代理设置”，应该会有一大堆图文教程。
