### ISSUE TITLE
总是无法建立连接

### ISSUE THREAD

**Issue by xmdhs** [XX-net/XX-Net#4893]
![default](https://cloud.githubusercontent.com/assets/20377726/22049184/c151e980-dd6c-11e6-9414-8babf73c28fd.JPG)
就是上图这样 有时可以连接 但经常不行
诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:69665 good:67931
network-status: unknown
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
日志
Jan 18 10:57:17.187 - [INFO] start to terminate GAE_Proxy
Jan 18 10:57:17.187 - [DEBUG] ## Set keep_running: False
Jan 18 10:57:17.609 - [INFO] Exiting gae_proxy module...
Jan 18 10:57:17.609 - [DEBUG] ## GAEProxy set keep_running: False
Jan 18 10:57:17.624 - [INFO] load manual.ini success
Jan 18 10:57:17.624 - [DEBUG] ## GAEProxy set keep_running: True
Jan 18 10:57:17.640 - [INFO] ------------------------------------------------------
Jan 18 10:57:17.640 - [INFO] Python Version : 2.7.11
Jan 18 10:57:17.640 - [INFO] OS : Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Jan 18 10:57:17.640 - [INFO] Listen Address : 0.0.0.0:8087
Jan 18 10:57:17.640 - [INFO] GAE APPID : 这个没必要了吧
Jan 18 10:57:17.640 - [INFO] Pac Server : http://0.0.0.0:8086/proxy.pac
Jan 18 10:57:17.640 - [INFO] ------------------------------------------------------
Jan 18 10:57:17.734 - [DEBUG] GAE POST http://center.xx-net.net:8888/login
Jan 18 10:57:19.080 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:57:19.080 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:19.082 - [DEBUG] get ip:64.53.251.21 t:100
Jan 18 10:57:19.514 - [DEBUG] GAEProxy web_control 127.0.0.1:53478 POST /config?cmd=get_config
Jan 18 10:57:19.516 - [DEBUG] GAEProxy Web_control 127.0.0.1:53478 GET /scan_ip?cmd=get_range
Jan 18 10:57:19.516 - [INFO] load ip range file:F:\XX-Net-3.2.9\code\default\gae_proxy\local\ip_range.txt
Jan 18 10:57:23.088 - [DEBUG] 64.53.251.21 fail:timeout('timed out',)
Jan 18 10:57:23.088 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:23.088 - [DEBUG] get ip:202.69.12.122 t:100
Jan 18 10:57:25.601 - [DEBUG] create ssl timeout fail.
Jan 18 10:57:25.601 - [DEBUG] create ssl timeout fail.
Jan 18 10:57:25.601 - [DEBUG] GAE_Exception 1 'no ssl_sock'
Jan 18 10:57:25.601 - [WARNING] get worker fail:GAE_Exception()
Jan 18 10:57:25.601 - [DEBUG] response_fail:get worker fail:GAE_Exception()
Jan 18 10:57:25.601 - [DEBUG] GAE_Exception 601 'fetch gae fail:601'
Jan 18 10:57:25.601 - [WARNING] gae_exception:GAE_Exception() https://www.googleapis.com/oauth2/v4/token
Jan 18 10:57:25.601 - [DEBUG] GAE_Exception 600 'gae_exception:GAE_Exception() https://www.googleapis.com/oauth2/v4/token'
Jan 18 10:57:25.601 - [WARNING] GAE POST https://www.googleapis.com/oauth2/v4/token request fail:GAE_Exception()
Jan 18 10:57:25.838 - [DEBUG] sort ip time:236ms
Jan 18 10:57:25.853 - [DEBUG] get ip:208.65.154.106 t:100
Jan 18 10:57:26.123 - [DEBUG] get ip:64.53.251.21 t:100
Jan 18 10:57:26.628 - [DEBUG] get ip:37.58.167.178 t:100
Jan 18 10:57:27.093 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:57:27.093 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:27.093 - [DEBUG] get ip:91.218.5.43 t:100
Jan 18 10:57:27.140 - [DEBUG] get ip:91.218.5.42 t:100
Jan 18 10:57:27.656 - [DEBUG] get ip:91.218.5.49 t:100
Jan 18 10:57:28.159 - [DEBUG] get ip:104.237.165.179 t:100
Jan 18 10:57:28.675 - [DEBUG] get ip:216.58.194.148 t:100
Jan 18 10:57:29.191 - [DEBUG] get ip:202.69.12.122 t:100
Jan 18 10:57:29.696 - [DEBUG] get ip:188.43.69.16 t:100
Jan 18 10:57:29.868 - [DEBUG] 208.65.154.106 fail:timeout('timed out',)
Jan 18 10:57:29.868 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:29.868 - [DEBUG] get ip:188.43.69.17 t:100
Jan 18 10:57:30.137 - [DEBUG] 64.53.251.21 fail:timeout('timed out',)
Jan 18 10:57:30.137 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:30.137 - [DEBUG] get ip:216.58.194.145 t:100
Jan 18 10:57:30.200 - [DEBUG] get ip:216.58.194.146 t:100
Jan 18 10:57:30.629 - [DEBUG] 37.58.167.178 fail:timeout('timed out',)
Jan 18 10:57:30.629 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:31.094 - [DEBUG] 91.218.5.43 fail:timeout('timed out',)
Jan 18 10:57:31.094 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:31.141 - [DEBUG] 91.218.5.42 fail:timeout('timed out',)
Jan 18 10:57:31.141 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:31.660 - [DEBUG] 91.218.5.49 fail:timeout('timed out',)
Jan 18 10:57:31.660 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:32.160 - [DEBUG] 104.237.165.179 fail:timeout('timed out',)
Jan 18 10:57:32.160 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:32.679 - [DEBUG] 216.58.194.148 fail:timeout('timed out',)
Jan 18 10:57:32.679 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:33.195 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:57:33.195 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:33.698 - [DEBUG] 188.43.69.16 fail:timeout('timed out',)
Jan 18 10:57:33.698 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:33.868 - [DEBUG] 188.43.69.17 fail:timeout('timed out',)
Jan 18 10:57:33.868 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:34.137 - [DEBUG] 216.58.194.145 fail:timeout('timed out',)
Jan 18 10:57:34.137 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:34.202 - [DEBUG] 216.58.194.146 fail:timeout('timed out',)
Jan 18 10:57:34.202 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:36.305 - [DEBUG] sort ip time:199ms
Jan 18 10:57:36.305 - [DEBUG] get ip:64.53.251.21 t:100
Jan 18 10:57:40.305 - [DEBUG] 64.53.251.21 fail:timeout('timed out',)
Jan 18 10:57:40.305 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:40.306 - [DEBUG] get ip:202.69.12.122 t:100
Jan 18 10:57:44.315 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:57:44.315 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:44.315 - [DEBUG] get ip:64.53.251.21 t:100
Jan 18 10:57:48.316 - [DEBUG] 64.53.251.21 fail:timeout('timed out',)
Jan 18 10:57:48.316 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:48.503 - [DEBUG] sort ip time:187ms
Jan 18 10:57:48.503 - [DEBUG] get ip:202.69.12.122 t:100
Jan 18 10:57:52.503 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:57:52.503 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:52.505 - [DEBUG] get ip:64.53.251.21 t:100
Jan 18 10:57:56.520 - [DEBUG] 64.53.251.21 fail:timeout('timed out',)
Jan 18 10:57:56.520 - [DEBUG] report_connect_fail network fail
Jan 18 10:57:56.520 - [DEBUG] get ip:202.69.12.122 t:100
Jan 18 10:58:00.521 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:58:00.521 - [DEBUG] report_connect_fail network fail
Jan 18 10:58:00.657 - [DEBUG] sort ip time:136ms
Jan 18 10:58:00.663 - [DEBUG] get ip:64.53.251.21 t:100
Jan 18 10:58:04.668 - [DEBUG] 64.53.251.21 fail:timeout('timed out',)
Jan 18 10:58:04.668 - [DEBUG] report_connect_fail network fail
Jan 18 10:58:04.668 - [DEBUG] get ip:202.69.12.122 t:100
Jan 18 10:58:08.668 - [DEBUG] 202.69.12.122 fail:timeout('timed out',)
Jan 18 10:58:08.668 - [DEBUG] report_connect_fail network fail
Jan 18 10:58:08.669 - [DEBUG] get ip:64.53.251.21 t:100

帮个忙 谢谢

**Comment by jzp820927** [comment]
你这个有点怪异，怎么会有 6万多 IP，你改过 IP 么？

**Comment by xmdhs** [comment]
导入了 别人的ip

**Comment by xmdhs** [comment]
导入了 别人的ip

**Comment by ssjlz4670** [comment]
应该和我之前一样，因为IP导致的。把 XX-Net\data\gae_proxy\good_ip.txt 删掉，然后重新扫描IP试试，如果还不行那就删掉data文件夹了只能。我这么折腾后是可以了

**Comment by xmdhs** [comment]
好的 我去试试
