### ISSUE TITLE
还是建议添加 http + rc4 + obfuscate 的选项

### ISSUE THREAD

**Issue by litel** [XX-net/XX-Net#49]
我在一个很差的 isp 上面用 https 模式的时候。

谷歌等网站会有时候提示找不到网页，要刷新下才行。
这时候日志里会有很多打开443端口错误的提示。

部署id的时候，会有如下报错：
    urllib2.URLError: \<urlopen error \[Errno 8\] _ssl.c:510: EOF occurred in violation of protocol\>

这时候我如果关掉 xx-net 打开 goagent 用 http + rc4 + obfuscate 模式，然后再来上传的话，就没报错了。

而且这时候上网站会感觉顺畅很多。

**Comment by xxnet** [comment]
你需要花点时间让XXNet进行扫描调整，找到好用的google ip。
安装包虽然包含了上千可用ip，但不是适合所有的ISP ，因此你要让XXNet扫描、适应一段时间，才能慢慢进入工作状态。

**Comment by litel** [comment]
我用 goagent 的 https 模式来上传也会报那个错误的。
goagent 用的 ip 是用 gogo tester 搜出来的。

**Comment by xxnet** [comment]
是哪个ISP? 如果担心隐私，请发邮件给我 xxnet.dev@gmail.com

从原理上讲，部署时，是直连Google的，http + rc4 + obfuscate跟部署没有关系。
所以这样的现象很奇怪，你能否多试几次，确认规律，谢谢。

**Comment by litel** [comment]
长城宽带
部署的时候 goagent 里面有日志啊。
从某个版本开始部署好像就要走 goagent 了啊。

**Comment by xxnet** [comment]
http + rc4 + obfuscate 从原理上讲，特征更明显。更容易被识别和封锁。
估计是真正使用的人很少，所以GWF还没有封锁。

1.3.1 对部署作了改进，请帮忙测试反馈，谢谢。
  也许会有失败几次，不过最后会部署成功才对。

**Comment by litel** [comment]
再次在那个渣网上试了下。
会不停报错 
记得好像是 handshake timed out

然后换用 http + rc4 + obfuscate 可以上传。。。

**Comment by xxnet** [comment]
要找个长城宽带的网络研究下才行，不知道长宽作了什么手脚。

谢谢反馈。

**Comment by xxnet** [comment]
1.7.0 解决部署问题，不需要http + rc4 + obfuscate
