### ISSUE TITLE
部分gvs ip可用于GAE，没找到原因

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#491]
https://code.google.com/p/goagent/issues/detail?id=21260
测试环境
ini文件里只贴写一个ip

google_cn = 74.125.216.36
google_hk = 74.125.216.36

>curl -k -I https://74.125.216.36

    HTTP/1.1 404 Not Found
    Date: Tue, 02 Jun 2015 18:26:24 GMT
    Content-Type: text/html; charset=UTF-8
    Server: gvs 1.0
    Content-Length: 1425
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN

访问twitter时，通过Wireshark抓包，可看到只有主机与该ip的通信

![screenshot_2015-06-03_02-28-05](https://cloud.githubusercontent.com/assets/6326116/7943695/b6b0a362-0998-11e5-968c-4145b2380471.png)

**Comment by xxnet** [comment]
这个酷，如果这样，可以直接验证是否可以通过ip 访问appid来判断是否可用，而不是gws。
以前试过，但是没有找到这样的ip。

gvs的ip要多很多的。

2015-06-03 2:31 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
关键是验证不了
正常ip

>curl -k --resolve xxnet-13.appspot.com:443:173.194.201.199  https://xxnet-13.appspot.com/_gh/

    GoAgent Python Server 3.2.0 works, deployed at 2015-03-28 08:15:22

此ip

>curl -k --resolve xxnet-13.appspot.com:443:74.125.216.36  https://xxnet-13.appspot.com/_gh/

    curl: (52) Empty reply from server

不知道goagent怎么请求的？

**Comment by xxnet** [comment]
可以安装pycharm，可以设置断点、单步跟踪，看goagent是怎么请求的

2015-06-03 18:16 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
研究了几个小时，只看到用post发送数据，怎么接收的呢？
    'POST /_gh/ HTTP/1.1\r\nContent-Length: 684\r\nHost: flycraftfly4.appspot.com\r\n\r\n\x02\xaa]\x92\xdbn\xda@\x10\x86\xef#\xe5\x1d|S\xa9M\x03\xde\x03>\x81|a 1\x90\xd8\t\x01\x87\xd87h\xb1\xd7\x07\xbc\xd8\xc4^\x83\xb1\xfa\xf0\xdd\xa0\xb6\x17\x95vV\xa3\x99O\xbf\xe6\x1f\x8d\xfd\xb0\x96R\xce\x8f\xf5P\x96\xf99\xe3\x9cV\xfd\xb0<\xc8\xd2l\xbd~\x95a\x1f\xde\xdeXaH\x8f\xbc\xf7L\x8a\xa4!\t\x1dJ]\xda\x9b\xb8\xf7\xb4\xe8y\xab\xd1\xa7\t\xfa\x9a\xc8\xaf\t\xfe\x07?\x14a\x19eE2\x94\x92.;\xdeK\x11\x8d\x19\xe1\xf4o\x7f(q\xdar9\xe5\x07vO\x8eG\x96\x85\x84ge!\xb7_\x95\x9f\xed\xff\xd5\x03\xbb\xca\x1b\xf7w\xf2\xdd5\xd3oo\xbc\x9aV=+\xa1\x85\x10s\xca.c\x8c\xc8J\x1fH\xdf? \x1cI\xcfY\xd1\xb4R\xab\xab[u0\x92\xaa\xd3\x10\xeb}\xf0C\xb2i\x98\x972\x02\x10\x88\x07\xa5\xc7\xac\xa2q\xd9\xca_\xcd\xdb\x9b\xe9\x97\x94\xf0;)\xcb<\x136\xc5\x84\xb4*\x08\xdb\n\x88V\xb42\x8f$J\x1b\xef\x88\xb5no\xb4\x8d\xf7\xf21q\x1fO3{\xd5L@\xa1\x80\xe8\x93\xac\xda\x99q\xd2l]/Bc\xff:\xb8\xc0\xf1\xb9\xe2\xd3\x14\xd8\xab\xa0\xe6\xab\xf2\x17\x18IICk\xbe\xcd"\xf3\x04\xbfa\x0b\x0e0\x82H\xc3\nTt\xa4\xa3\x81\xa1\x8e\xa4mBL\xdb\x82}\xd4\xd7u\xa0#`@\xb5\xff\x87ST<\x92\xf2\x88\x9b\xd3\xe7\xa7:6\xa6\x8c\xbf\xbdh\rr\xd6\xa0\xb5O\xea\x0c\x1b\xf4\x92[\x9fVa\xfb`R\xcd\x17>\x12\xd6\xe9\x81\x1ev\xb4\xda\x86\xa9\xf0N\xa3mY\x98b?\xa4\xe1\xe9\x96\x979-L\xb4#1P\x81\xa6\x11\xaa\x81(\xa6\xba\xa1\x13Bv\xea\x8e\x90\x88\x18: H\x0f#\x12\xd1\x91t\xa6;\x81\x0bTQ\x0c\x8c\xc5(L\x9c\x84)\xae!,\xc4\xd8\x7f\xaeg[\xd3\xba6\xc7V\xaaMV\xf3\xa7\xe0\xd0\xa6!J\x17\xcb\xae,\x96\x1b\x17\x90\x8d\xd1,\x91\xd1D\xb3\xc5ig\xb7,\xdc\x97\xea\xdb\x95I\xd4\x97<\xa8\xfd\x0f\xb7\xfc\x86\x14`\xad\xec\xc7\x8e\xccjk\xbc/\x9f\x96\xb3\xf7.\xd8\xbci\xd6\xb4|\xf5\xf1\x82\xf9\x1fo,x4\xd2\xc8>W\x93\x19\x05\x17\x8d\xbb\xd6\xbat|\xec^\x02f\x1c\xaf\x02\xc1d\xce\x9c\xcd\x12\xba\xe8=s\x90\x07\x82\x8d3\xf0\xd1"ulO,l|x\xb1\xdf\x99\xb3^d\xc1\xc1\xbb8\xfbP\x1d#\x96\xcf3\x0f\x07k\x0f^\x05\\{\xde:\xd3\x04\xfb\xdd"\x15\xc1\xfc\xcd"\x0f\xa6\xe1\xd9\xb1\xfd\x81\xdb1\xe6\xae\xf3\xd6I\x04\x8a\xa7\xd7\xaf\xd7\x831\x89b\x95\x84@\x03F\x18b\xb0\xd3\x07@Ep\xa7`\x18\xc5\x80\x02c\x10\x03\xa8"\xf5\xf6\xe67'

模拟了一个请求，但是不成功

    curl -k  --resolve flycraftfly4.appspot.com:443:59.18.34.36 https://flycraftfly4.appspot.com/_gh/ -H 'Content-Length: 684' -H 'Host: flycraftfly4.appspot.com' -d '\x02\xaa]\x92\xdbn\xda@\x10\x86\xef#\xe5\x1d|S\xa9M\x03\xde\x03>\x81|a 1\x90\xd8\t\x01\x87\xd87h\xb1\xd7\x07\xbc\xd8\xc4^\x83\xb1\xfa\xf0\xdd\xa0\xb6\x17\x95vV\xa3\x99O\xbf\xe6\x1f\x8d\xfd\xb0\x96R\xce\x8f\xf5P\x96\xf99\xe3\x9cV\xfd\xb0<\xc8\xd2l\xbd~\x95a\x1f\xde\xdeXaH\x8f\xbc\xf7L\x8a\xa4!\t\x1dJ]\xda\x9b\xb8\xf7\xb4\xe8y\xab\xd1\xa7\t\xfa\x9a\xc8\xaf\t\xfe\x07?\x14a\x19eE2\x94\x92.;\xdeK\x11\x8d\x19\xe1\xf4o\x7f(q\xdar9\xe5\x07vO\x8eG\x96\x85\x84ge!\xb7_\x95\x9f\xed\xff\xd5\x03\xbb\xca\x1b\xf7w\xf2\xdd5\xd3oo\xbc\x9aV=+\xa1\x85\x10s\xca.c\x8c\xc8J\x1fH\xdf? \x1cI\xcfY\xd1\xb4R\xab\xab[u0\x92\xaa\xd3\x10\xeb}\xf0C\xb2i\x98\x972\x02\x10\x88\x07\xa5\xc7\xac\xa2q\xd9\xca_\xcd\xdb\x9b\xe9\x97\x94\xf0;)\xcb<\x136\xc5\x84\xb4*\x08\xdb\n\x88V\xb42\x8f$J\x1b\xef\x88\xb5no\xb4\x8d\xf7\xf21q\x1fO3{\xd5L@\xa1\x80\xe8\x93\xac\xda\x99q\xd2l]/Bc\xff:\xb8\xc0\xf1\xb9\xe2\xd3\x14\xd8\xab\xa0\xe6\xab\xf2\x17\x18IICk\xbe\xcd"\xf3\x04\xbfa\x0b\x0e0\x82H\xc3\nTt\xa4\xa3\x81\xa1\x8e\xa4mBL\xdb\x82}\xd4\xd7u\xa0#`@\xb5\xff\x87ST<\x92\xf2\x88\x9b\xd3\xe7\xa7:6\xa6\x8c\xbf\xbdh\rr\xd6\xa0\xb5O\xea\x0c\x1b\xf4\x92[\x9fVa\xfb`R\xcd\x17>\x12\xd6\xe9\x81\x1ev\xb4\xda\x86\xa9\xf0N\xa3mY\x98b?\xa4\xe1\xe9\x96\x979-L\xb4#1P\x81\xa6\x11\xaa\x81(\xa6\xba\xa1\x13Bv\xea\x8e\x90\x88\x18: H\x0f#\x12\xd1\x91t\xa6;\x81\x0bTQ\x0c\x8c\xc5(L\x9c\x84)\xae!,\xc4\xd8\x7f\xaeg[\xd3\xba6\xc7V\xaaMV\xf3\xa7\xe0\xd0\xa6!J\x17\xcb\xae,\x96\x1b\x17\x90\x8d\xd1,\x91\xd1D\xb3\xc5ig\xb7,\xdc\x97\xea\xdb\x95I\xd4\x97<\xa8\xfd\x0f\xb7\xfc\x86\x14`\xad\xec\xc7\x8e\xccjk\xbc/\x9f\x96\xb3\xf7.\xd8\xbci\xd6\xb4|\xf5\xf1\x82\xf9\x1fo,x4\xd2\xc8>W\x93\x19\x05\x17\x8d\xbb\xd6\xbat|\xec^\x02f\x1c\xaf\x02\xc1d\xce\x9c\xcd\x12\xba\xe8=s\x90\x07\x82\x8d3\xf0\xd1"ulO,l|x\xb1\xdf\x99\xb3^d\xc1\xc1\xbb8\xfbP\x1d#\x96\xcf3\x0f\x07k\x0f^\x05\\{\xde:\xd3\x04\xfb\xdd"\x15\xc1\xfc\xcd"\x0f\xa6\xe1\xd9\xb1\xfd\x81\xdb1\xe6\xae\xf3\xd6I\x04\x8a\xa7\xd7\xaf\xd7\x831\x89b\x95\x84@\x03F\x18b\xb0\xd3\x07@Ep\xa7`\x18\xc5\x80\x02c\x10\x03\xa8"\xf5\xf6\xe67' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0' -H 'Accept-Language: zh-CN,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -vv


对于能在高版本Linux和mac上的goagent可利用，而windows上不可用，可能是什么原因呢？

**Comment by linhua55** [comment]
搞懂了为什么用curl命令模拟不成功，原来需要指定使用SSLv3协议，像这样

    curl -k  --resolve xxnet-13.appspot.com:443:59.18.34.36 https://xxnet-13.appspot.com/_gh/ -H 'Content-Length: 684' -H 'Host: xxnet-13.appspot.com' --data-urlencode '\x02\xaa]\x92\xdbn\xda@\x10\x86\xef#\xe5\x1d|S\xa9M\x03\xde\x03>\x81|a 1\x90\xd8\t\x01\x87\xd87h\xb1\xd7\x07\xbc\xd8\xc4^\x83\xb1\xfa\xf0\xdd\xa0\xb6\x17\x95vV\xa3\x99O\xbf\xe6\x1f\x8d\xfd\xb0\x96R\xce\x8f\xf5P\x96\xf99\xe3\x9cV\xfd\xb0<\xc8\xd2l\xbd~\x95a\x1f\xde\xdeXaH\x8f\xbc\xf7L\x8a\xa4!\t\x1dJ]\xda\x9b\xb8\xf7\xb4\xe8y\xab\xd1\xa7\t\xfa\x9a\xc8\xaf\t\xfe\x07?\x14a\x19eE2\x94\x92.;\xdeK\x11\x8d\x19\xe1\xf4o\x7f(q\xdar9\xe5\x07vO\x8eG\x96\x85\x84ge!\xb7_\x95\x9f\xed\xff\xd5\x03\xbb\xca\x1b\xf7w\xf2\xdd5\xd3oo\xbc\x9aV=+\xa1\x85\x10s\xca.c\x8c\xc8J\x1fH\xdf? \x1cI\xcfY\xd1\xb4R\xab\xab[u0\x92\xaa\xd3\x10\xeb}\xf0C\xb2i\x98\x972\x02\x10\x88\x07\xa5\xc7\xac\xa2q\xd9\xca_\xcd\xdb\x9b\xe9\x97\x94\xf0;)\xcb<\x136\xc5\x84\xb4*\x08\xdb\n\x88V\xb42\x8f$J\x1b\xef\x88\xb5no\xb4\x8d\xf7\xf21q\x1fO3{\xd5L@\xa1\x80\xe8\x93\xac\xda\x99q\xd2l]/Bc\xff:\xb8\xc0\xf1\xb9\xe2\xd3\x14\xd8\xab\xa0\xe6\xab\xf2\x17\x18IICk\xbe\xcd"\xf3\x04\xbfa\x0b\x0e0\x82H\xc3\nTt\xa4\xa3\x81\xa1\x8e\xa4mBL\xdb\x82}\xd4\xd7u\xa0#`@\xb5\xff\x87ST<\x92\xf2\x88\x9b\xd3\xe7\xa7:6\xa6\x8c\xbf\xbdh\rr\xd6\xa0\xb5O\xea\x0c\x1b\xf4\x92[\x9fVa\xfb`R\xcd\x17>\x12\xd6\xe9\x81\x1ev\xb4\xda\x86\xa9\xf0N\xa3mY\x98b?\xa4\xe1\xe9\x96\x979-L\xb4#1P\x81\xa6\x11\xaa\x81(\xa6\xba\xa1\x13Bv\xea\x8e\x90\x88\x18: H\x0f#\x12\xd1\x91t\xa6;\x81\x0bTQ\x0c\x8c\xc5(L\x9c\x84)\xae!,\xc4\xd8\x7f\xaeg[\xd3\xba6\xc7V\xaaMV\xf3\xa7\xe0\xd0\xa6!J\x17\xcb\xae,\x96\x1b\x17\x90\x8d\xd1,\x91\xd1D\xb3\xc5ig\xb7,\xdc\x97\xea\xdb\x95I\xd4\x97<\xa8\xfd\x0f\xb7\xfc\x86\x14`\xad\xec\xc7\x8e\xccjk\xbc/\x9f\x96\xb3\xf7.\xd8\xbci\xd6\xb4|\xf5\xf1\x82\xf9\x1fo,x4\xd2\xc8>W\x93\x19\x05\x17\x8d\xbb\xd6\xbat|\xec^\x02f\x1c\xaf\x02\xc1d\xce\x9c\xcd\x12\xba\xe8=s\x90\x07\x82\x8d3\xf0\xd1"ulO,l|x\xb1\xdf\x99\xb3^d\xc1\xc1\xbb8\xfbP\x1d#\x96\xcf3\x0f\x07k\x0f^\x05\\{\xde:\xd3\x04\xfb\xdd"\x15\xc1\xfc\xcd"\x0f\xa6\xe1\xd9\xb1\xfd\x81\xdb1\xe6\xae\xf3\xd6I\x04\x8a\xa7\xd7\xaf\xd7\x831\x89b\x95\x84@\x03F\x18b\xb0\xd3\x07@Ep\xa7`\x18\xc5\x80\x02c\x10\x03\xa8"\xf5\xf6\xe67'  -vv --sslv3  -X POST

**Comment by linhua55** [comment]
@xxnet

**Comment by cclu** [comment]
可用，已经在老版本比如3.1.0 goagent上修改代码实验挖成。赞一个

**Comment by wwbfred** [comment]
根据这个原理,经过测试gvs的ip也可用于hosts,不过会报证书错误,但服务的确可用.
chrome在加上--cipher-suite-blacklist=0x009c,0xc02f --ignore-certificate-errors参数之后59.18.34.36就能传输数据了.写个插件应该能解决问题.
不过在插件出来之前强烈不建议为了用Google一直保留这两个参数,代价太大了.

**Comment by LGA1150** [comment]
@wwbfred 
这时候GoAgent中fakehttps参数的价值就体现出来了:)

**Comment by wwbfred** [comment]
@LGA1150 是的...这样用效果拔群...

**Comment by Kisesy** [comment]
用 requests 来测试 gvsip 会直接返回 gws
 

    r = requests.head('http://59.18.34.146')
    for k,v in r.headers.items():
        print k,':',v
    


----------


    alternate-protocol : 80:quic,p=0
    content-length : 0
    x-xss-protection : 1; mode=block
    expires : Thu, 16 Jul 2015 17:05:35 GMT
    server : gws
    location : http://www.google.com/
    cache-control : public, max-age=2592000
    date : Tue, 16 Jun 2015 17:05:35 GMT
    x-frame-options : SAMEORIGIN
    content-type : text/html; charset=UTF-8

ip URL的前缀不能是 https 不然就会出错
但是如果还是写https，并且把head里写上verify=False这个参数，就不会出错了，但是会返回 gvs 1.0

**r = requests.head('https://59.18.34.146', verify=False)**

    content-length : 1425
    x-xss-protection : 1; mode=block
    server : gvs 1.0
    date : Tue, 16 Jun 2015 17:21:26 GMT
    x-frame-options : SAMEORIGIN
    content-type : text/html; charset=UTF-8

这挺有意思的...
