### ISSUE TITLE
连续几天所有google通过xxnet3.2.9的访问都不成功

### ISSUE THREAD

**Issue by kirbyzhu** [XX-net/XX-Net#4913]
![image](https://cloud.githubusercontent.com/assets/10296293/22240739/57ce489c-e257-11e6-8803-147302770799.png)

全部都是如图的提示。

谷歌学术需要人机验证但是无法显示验证图片

3.2.8之前无任何问题，xxnet已经正常使用了两年多。
更新了chrome到最新的64位版本。

Jan 24 17:05:30.928 - [WARNING] 43.245.195.178 head appid:******* request fail:SysCallError(10054, 'WSAECONNRESET')
Jan 24 17:05:30.928 - [DEBUG] report_connect_fail:43.245.195.178
Jan 24 17:05:36.296 - [DEBUG] 109.245.221.47 fail:timeout('timed out',)
Jan 24 17:05:36.298 - [DEBUG] report_connect_fail:109.245.221.47
Jan 24 17:05:36.498 - [DEBUG] get ip:195.8.11.41 t:500
Jan 24 17:05:37.849 - [DEBUG] create_ssl update ip:195.8.11.41 time:516 h2:0
Jan 24 17:05:37.901 - [DEBUG] 43.245.195.178 worker close:keep alive
Jan 24 17:05:39.693 - [DEBUG] ip:61.238.239.169 real fail
Jan 24 17:05:44.305 - [DEBUG] 80.91.176.15 worker close:keep alive
Jan 24 17:05:44.707 - [DEBUG] ip:118.143.88.170 real fail
Jan 24 17:05:49.006 - [DEBUG] ssl_closed 212.1.250.182
Jan 24 17:05:49.007 - [DEBUG] 212.1.250.182 worker close:idle timeout
---

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by jzp820927** [comment]
这个是证书问题，导入证书了吗？

**Comment by kirbyzhu** [comment]
证书没问题 根据网上有些攻略 昨天删除后重新导入了。
![image](https://cloud.githubusercontent.com/assets/10296293/22241363/fd817f78-e259-11e6-82b5-6da29a521e66.png)

并且把 cnnic root放到了未受信任的证书列表中

**Comment by jzp820927** [comment]
试试删除 data，删除导入浏览器证书，重启 XX，重新导入新生成的证书到浏览器。

**Comment by kirbyzhu** [comment]
删除data后好像问题消失，谢谢啦！
