### ISSUE TITLE
求大神帮忙看看怎么回事

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#4922]
谷歌浏览器进入 http://127.0.0.1:8085  很慢
**还有桌面打开从桌面打开xxnet没啥反应，打开速度也很慢**

尚未建立连接
状态

属性	值
本地网络状态	unknown
IP数量	2945
空闲	0
IP延迟	100
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	0
屏蔽状态(帮助)	OK
配置

属性	值
监听代理	127.0.0.1:8087
PAC自动代理地址	http://127.0.0.1:8086/proxy.pac
IPv6	禁用
Appid

属性	值
当前工作AppID	huangyuanwei1997|huangyuanwei0501|huangyuanwei2010|huangyuanwei2011|huangyuanwei2012|huangyuanwei2015|huangyuanwei2016
系统版本

属性	值
XX-Net Version	3.2.8
Python Version	2.7.11
OpenSSL Version	16.0.0 TLSv1_2 h2:alpn
System Platform	AMD64, Windows-10-10.0.10586
OS System	Windows
OS Version	10.0.10586
OS Release	10
OS Detail	Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.8 Safari/537.36

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586

os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.8 Safari/537.36
xxnet-version: 3.2.8

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2945
network-status: unknown
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Jan 27 01:14:31.991 - [INFO] use config_path:C:\Users\huang_000\Desktop\XX-Net-3.2.8\data\x_tunnel\client.json
Jan 27 01:14:31.996 - [INFO] Use proxy:127.0.0.1:8087
Jan 27 01:14:31.998 - [DEBUG] x-tunnel no account
Jan 27 01:14:32.004 - [WARNING] x-tunnel session not start
Jan 27 01:14:32.010 - [INFO] Socks5 server listen:127.0.0.1:1080.

**Comment by jzp820927** [comment]
扫描IP线程数(设置)	0

怎么你的扫描线程数是 0？

**Comment by LN-VIVI** [comment]
属性	值
本地网络状态	OK
IP数量	518
空闲	0
IP延迟	100
连接池(帮助)	新:0 h1:0 h2:0
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK

**Comment by jzp820927** [comment]
连接池(帮助)	新:0 h1:0 h2:0
没有连接池
