### ISSUE TITLE
XX-NET配置AppID无效

### ISSUE THREAD

**Issue by He110te4m** [XX-net/XX-Net#4923]
# 基于最新稳定版：3.2.8

# 状况说明
昨天提示超额，去配置了几个 AppID，配置完成了，今天一看是无效的，而且今天就去了油管看了2个视频，不到1G，有5个以前了AppID超额了

# 状态页
![default](https://cloud.githubusercontent.com/assets/16161582/22360921/b0cae4fc-e48f-11e6-9f2f-8223321cbcb1.png)
![default](https://cloud.githubusercontent.com/assets/16161582/22360930/c67c14ec-e48f-11e6-86f9-94c3fdbb8588.png)

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4720
