### ISSUE TITLE
win10预览版15014无法修改为全局pac只能代理

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#4926]
XX-Net 3.2.8，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	2339
空闲	0
IP延迟	105
连接池(帮助)	新:2 h1:16 h2:8
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK

**Comment by jzp820927** [comment]
不太明白，你具体是什么问题？

**Comment by JMaxime** [comment]
![image](https://cloud.githubusercontent.com/assets/18569232/22381365/527744a0-e4fc-11e6-8552-718c1ef98530.png)
不能选择“全局pac只能代理”，只能“全局通过gaeproxy代理”爬楼梯

**Comment by JMaxime** [comment]
不能选择“全局pac智能代理”，只能“全局通过gaeproxy代理”爬楼梯

**Comment by jzp820927** [comment]
你是指的托盘区的图标不能选择代理？那就手动设置吧，一样的。

**Comment by JMaxime** [comment]
![image](https://cloud.githubusercontent.com/assets/18569232/22395823/2c85a5ba-e584-11e6-86c2-4f03669fd48c.png)
这样感觉很不方便 还有没有其它的方法呢

**Comment by JMaxime** [comment]
![image](https://cloud.githubusercontent.com/assets/18569232/22395996/931f58b2-e588-11e6-89df-f08224080cc6.png)
已经解决

**Comment by jzp820927** [comment]
恩，用 PAC 算是最方便的了
