### ISSUE TITLE
X-Tunnel不稳定，低速，同时打开多个网页时明显卡顿

### ISSUE THREAD

**Issue by BreakShadow0504** [XX-net/XX-Net#4928]
Jan 28 00:32:25.980 - [DEBUG] Conn session:cvsubfax conn:66 stop:recv fail.
Jan 28 00:32:25.981 - [DEBUG] remove conn_id:66
Jan 28 00:32:26.249 - [DEBUG] roundtrip time:269 cost:0 transfer_no:363 send_sn:346 send:25 recv_sn:356 rcv:336 status:200
Jan 28 00:32:26.250 - [DEBUG] DATA conn_id 66 not in list
Jan 28 00:32:27.985 - [INFO] socks5 ('127.0.0.1', 3485) connect to live.github.com:443 conn_id:67
Jan 28 00:32:28.282 - [DEBUG] roundtrip time:292 cost:0 transfer_no:365 send_sn:348 send:237 recv_sn:358 rcv:2921 status:200
Jan 28 00:32:28.654 - [DEBUG] roundtrip time:667 cost:1 transfer_no:364 send_sn:347 send:34 recv_sn:357 rcv:386355 status:200
Jan 28 00:32:31.324 - [WARNING] roundtrip time:20000 transfer_no:258 send_sn:243 send:527 status:'UNKNOWN' retry:1
Jan 28 00:32:31.336 - [WARNING] roundtrip time:20000 transfer_no:260 send_sn:245 send:140 status:'UNKNOWN' retry:1
Jan 28 00:32:31.936 - [DEBUG] Conn session:cvsubfax conn:54 stop:recv fail.
Jan 28 00:32:31.939 - [DEBUG] remove conn_id:54
Jan 28 00:32:32.195 - [DEBUG] roundtrip time:256 cost:0 transfer_no:366 send_sn:349 send:25 recv_sn:359 rcv:162 status:200
Jan 28 00:32:32.497 - [DEBUG] roundtrip time:299 cost:0 transfer_no:368 send_sn:351 send:65 recv_sn:361 rcv:20395 status:200
Jan 28 00:32:32.619 - [DEBUG] roundtrip time:680 cost:0 transfer_no:367 send_sn:350 send:454 recv_sn:360 rcv:255618 status:200
Jan 28 00:32:32.622 - [INFO] Conn session:cvsubfax conn:44 Peer Close:recv closed
Jan 28 00:32:32.623 - [DEBUG] Conn session:cvsubfax conn:44 stop:peer close
Jan 28 00:32:32.627 - [INFO] Conn session:cvsubfax conn:56 Peer Close:recv closed
Jan 28 00:32:32.627 - [DEBUG] Conn session:cvsubfax conn:56 stop:peer close
Jan 28 00:32:32.679 - [DEBUG] roundtrip time:340 cost:0 transfer_no:260 send_sn:245 send:140 recv_sn:362 rcv:63936 status:200
Jan 28 00:32:32.681 - [INFO] Conn session:cvsubfax conn:57 Peer Close:recv closed
Jan 28 00:32:32.682 - [INFO] Conn session:cvsubfax conn:55 Peer Close:recv closed
Jan 28 00:32:32.683 - [DEBUG] Conn session:cvsubfax conn:57 stop:peer close
Jan 28 00:32:32.684 - [DEBUG] Conn session:cvsubfax conn:55 stop:peer close
Jan 28 00:32:32.806 - [DEBUG] roundtrip time:480 cost:0 transfer_no:258 send_sn:243 send:527 recv_sn:363 rcv:283 status:200
Jan 28 00:32:32.891 - [DEBUG] roundtrip time:263 cost:0 transfer_no:370 send_sn:353 send:20 recv_sn:364 rcv:2869 status:200
Jan 28 00:32:32.960 - [DEBUG] roundtrip time:337 cost:0 transfer_no:369 send_sn:352 send:20 recv_sn:365 rcv:17664 status:200
Jan 28 00:32:32.966 - [DEBUG] roundtrip time:284 cost:0 transfer_no:371 send_sn:354 send:20 recv_sn:366 rcv:195 status:200
Jan 28 00:32:32.974 - [DEBUG] roundtrip time:290 cost:0 transfer_no:372 send_sn:355 send:20 recv_sn:367 rcv:149 status:200
Jan 28 00:32:33.062 - [DEBUG] remove conn_id:44
Jan 28 00:32:33.106 - [DEBUG] remove conn_id:56
Jan 28 00:32:33.232 - [DEBUG] roundtrip time:270 cost:0 transfer_no:373 send_sn:356 send:60 recv_sn:368 rcv:71 status:200
Jan 28 00:32:33.253 - [DEBUG] roundtrip time:286 cost:1 transfer_no:374 send_sn:357 send:60 recv_sn:369 rcv:195 status:200
Jan 28 00:32:33.264 - [DEBUG] remove conn_id:57
Jan 28 00:32:33.396 - [DEBUG] remove conn_id:55
Jan 28 00:32:33.426 - [DEBUG] Conn session:cvsubfax conn:64 stop:recv fail.
Jan 28 00:32:33.426 - [DEBUG] Conn session:cvsubfax conn:65 stop:recv fail.
Jan 28 00:32:33.426 - [DEBUG] remove conn_id:64
Jan 28 00:32:33.427 - [DEBUG] remove conn_id:65
Jan 28 00:32:33.435 - [INFO] socks5 ('127.0.0.1', 3525) connect to github.com:443 conn_id:68
Jan 28 00:32:33.496 - [DEBUG] roundtrip time:262 cost:0 transfer_no:375 send_sn:358 send:60 recv_sn:370 rcv:195 status:200
Jan 28 00:32:33.655 - [DEBUG] roundtrip time:401 cost:0 transfer_no:376 send_sn:359 send:60 recv_sn:371 rcv:52335 status:200
Jan 28 00:32:33.744 - [DEBUG] roundtrip time:316 cost:0 transfer_no:378 send_sn:361 send:25 recv_sn:372 rcv:11637 status:200
Jan 28 00:32:33.753 - [DEBUG] roundtrip time:318 cost:1 transfer_no:379 send_sn:362 send:29 recv_sn:373 rcv:5817 status:200
Jan 28 00:32:33.776 - [DEBUG] roundtrip time:278 cost:23 transfer_no:381 send_sn:364 send:60 recv_sn:375 rcv:177 status:200
Jan 28 00:32:33.855 - [DEBUG] roundtrip time:414 cost:10 transfer_no:380 send_sn:363 send:250 recv_sn:374 rcv:5817 status:200
Jan 28 00:32:33.970 - [DEBUG] roundtrip time:543 cost:0 transfer_no:377 send_sn:360 send:25 recv_sn:376 rcv:14519 status:200
Jan 28 00:32:34.076 - [DEBUG] roundtrip time:296 cost:5 transfer_no:383 send_sn:366 send:936 recv_sn:378 rcv:8727 status:200
Jan 28 00:32:34.081 - [DEBUG] roundtrip time:304 cost:0 transfer_no:382 send_sn:365 send:65 recv_sn:377 rcv:5817 status:200
Jan 28 00:32:34.490 - [DEBUG] roundtrip time:510 cost:0 transfer_no:384 send_sn:367 send:840 recv_sn:379 rcv:13811 status:200
Jan 28 00:32:36.980 - [DEBUG] Conn session:cvsubfax conn:67 stop:recv fail.
Jan 28 00:32:36.981 - [DEBUG] remove conn_id:67
Jan 28 00:32:37.249 - [DEBUG] roundtrip time:269 cost:0 transfer_no:385 send_sn:368 send:25 recv_sn:380 rcv:7020 status:200
Jan 28 00:32:37.935 - [INFO] socks5 ('127.0.0.1', 3559) connect to github.com:443 conn_id:69
Jan 28 00:32:38.233 - [DEBUG] roundtrip time:296 cost:1 transfer_no:386 send_sn:369 send:29 recv_sn:381 rcv:4222 status:200
Jan 28 00:32:38.484 - [DEBUG] roundtrip time:546 cost:0 transfer_no:387 send_sn:370 send:250 recv_sn:382 rcv:119885 status:200
Jan 28 00:32:38.489 - [DEBUG] DATA conn_id 67 not in list
Jan 28 00:32:38.556 - [INFO] socks5 ('127.0.0.1', 3563) connect to assets-cdn.github.com:443 conn_id:70
Jan 28 00:32:38.563 - [INFO] socks5 ('127.0.0.1', 3564) connect to assets-cdn.github.com:443 conn_id:71
Jan 28 00:32:38.566 - [INFO] socks5 ('127.0.0.1', 3565) connect to assets-cdn.github.com:443 conn_id:72
Jan 28 00:32:38.567 - [INFO] socks5 ('127.0.0.1', 3566) connect to assets-cdn.github.com:443 conn_id:73
Jan 28 00:32:38.568 - [INFO] socks5 ('127.0.0.1', 3567) connect to assets-cdn.github.com:443 conn_id:74
Jan 28 00:32:38.955 - [DEBUG] roundtrip time:391 cost:94 transfer_no:392 send_sn:375 send:40 recv_sn:389 rcv:181 status:200
Jan 28 00:32:38.995 - [DEBUG] roundtrip time:440 cost:113 transfer_no:389 send_sn:372 send:584 recv_sn:387 rcv:2529 status:200
Jan 28 00:32:39.016 - [DEBUG] roundtrip time:449 cost:0 transfer_no:395 send_sn:378 send:40 recv_sn:386 rcv:11651 status:200
Jan 28 00:32:39.028 - [DEBUG] roundtrip time:535 cost:0 transfer_no:388 send_sn:371 send:968 recv_sn:383 rcv:261517 status:200
Jan 28 00:32:39.044 - [DEBUG] roundtrip time:475 cost:0 transfer_no:396 send_sn:379 send:40 recv_sn:388 rcv:16527 status:200
Jan 28 00:32:39.048 - [DEBUG] roundtrip time:476 cost:148 transfer_no:399 send_sn:382 send:531 recv_sn:391 rcv:181 status:200
Jan 28 00:32:39.066 - [DEBUG] roundtrip time:503 cost:6 transfer_no:391 send_sn:374 send:531 recv_sn:385 rcv:1558 status:200
Jan 28 00:32:39.069 - [DEBUG] roundtrip time:499 cost:1 transfer_no:398 send_sn:381 send:531 recv_sn:384 rcv:46487 status:200
Jan 28 00:32:39.133 - [DEBUG] roundtrip time:575 cost:42 transfer_no:390 send_sn:373 send:40 recv_sn:392 rcv:5817 status:200
Jan 28 00:32:39.182 - [DEBUG] roundtrip time:612 cost:137 transfer_no:397 send_sn:380 send:531 recv_sn:393 rcv:5831 status:200
Jan 28 00:32:39.256 - [DEBUG] roundtrip time:299 cost:0 transfer_no:400 send_sn:383 send:65 recv_sn:394 rcv:11623 status:200
Jan 28 00:32:39.361 - [DEBUG] roundtrip time:289 cost:0 transfer_no:407 send_sn:390 send:584 recv_sn:396 rcv:8713 status:200
Jan 28 00:32:39.366 - [DEBUG] roundtrip time:369 cost:72 transfer_no:402 send_sn:385 send:65 recv_sn:397 rcv:1848 status:200
Jan 28 00:32:39.416 - [DEBUG] roundtrip time:380 cost:90 transfer_no:404 send_sn:387 send:65 recv_sn:398 rcv:3828 status:200
Jan 28 00:32:39.425 - [DEBUG] roundtrip time:375 cost:50 transfer_no:406 send_sn:389 send:585 recv_sn:399 rcv:3415 status:200
Jan 28 00:32:39.432 - [DEBUG] roundtrip time:314 cost:47 transfer_no:408 send_sn:391 send:480 recv_sn:401 rcv:1811 status:200
Jan 28 00:32:39.438 - [DEBUG] roundtrip time:388 cost:0 transfer_no:405 send_sn:388 send:65 recv_sn:400 rcv:5817 status:200
Jan 28 00:32:39.584 - [DEBUG] roundtrip time:463 cost:190 transfer_no:410 send_sn:393 send:480 recv_sn:402 rcv:14533 status:200
Jan 28 00:32:39.584 - [INFO] socks5 ('127.0.0.1', 3573) connect to live.github.com:443 conn_id:75
Jan 28 00:32:39.608 - [DEBUG] roundtrip time:483 cost:2 transfer_no:411 send_sn:394 send:480 recv_sn:403 rcv:4642 status:200
Jan 28 00:32:39.689 - [DEBUG] roundtrip time:319 cost:1 transfer_no:412 send_sn:395 send:585 recv_sn:404 rcv:1995 status:200
Jan 28 00:32:39.706 - [DEBUG] roundtrip time:272 cost:0 transfer_no:413 send_sn:396 send:583 recv_sn:405 rcv:14547 status:200
Jan 28 00:32:39.906 - [DEBUG] roundtrip time:336 cost:0 transfer_no:414 send_sn:397 send:137 recv_sn:406 rcv:1705 status:200
Jan 28 00:32:39.958 - [DEBUG] roundtrip time:388 cost:0 transfer_no:415 send_sn:398 send:390 recv_sn:407 rcv:14561 status:200
Jan 28 00:32:39.976 - [DEBUG] roundtrip time:391 cost:0 transfer_no:417 send_sn:400 send:34 recv_sn:408 rcv:218 status:200
Jan 28 00:32:40.099 - [DEBUG] roundtrip time:512 cost:0 transfer_no:418 send_sn:401 send:237 recv_sn:411 rcv:5833 status:200
Jan 28 00:32:40.112 - [DEBUG] roundtrip time:421 cost:0 transfer_no:419 send_sn:402 send:587 recv_sn:413 rcv:599 status:200
Jan 28 00:32:40.114 - [DEBUG] roundtrip time:1117 cost:0 transfer_no:403 send_sn:386 send:582 recv_sn:409 rcv:11651 status:200
Jan 28 00:32:40.124 - [DEBUG] roundtrip time:1005 cost:0 transfer_no:409 send_sn:392 send:480 recv_sn:410 rcv:7138 status:200
Jan 28 00:32:40.130 - [INFO] socks5 ('127.0.0.1', 3576) connect to api.github.com:443 conn_id:76
Jan 28 00:32:40.186 - [DEBUG] roundtrip time:611 cost:14 transfer_no:416 send_sn:399 send:1696 recv_sn:412 rcv:162 status:200
Jan 28 00:32:40.199 - [DEBUG] roundtrip time:288 cost:0 transfer_no:420 send_sn:403 send:585 recv_sn:414 rcv:2117 status:200
Jan 28 00:32:40.296 - [DEBUG] roundtrip time:318 cost:0 transfer_no:421 send_sn:404 send:60 recv_sn:415 rcv:17241 status:200
Jan 28 00:32:40.413 - [DEBUG] roundtrip time:286 cost:0 transfer_no:422 send_sn:405 send:583 recv_sn:416 rcv:1385 status:200
Jan 28 00:32:40.466 - [DEBUG] roundtrip time:265 cost:0 transfer_no:427 send_sn:410 send:581 recv_sn:418 rcv:11623 status:200
Jan 28 00:32:40.518 - [DEBUG] roundtrip time:383 cost:1 transfer_no:424 send_sn:407 send:250 recv_sn:417 rcv:21971 status:200
Jan 28 00:32:40.611 - [DEBUG] roundtrip time:480 cost:0 transfer_no:423 send_sn:406 send:33 recv_sn:420 rcv:11637 status:200
Jan 28 00:32:40.645 - [DEBUG] roundtrip time:457 cost:0 transfer_no:425 send_sn:408 send:65 recv_sn:419 rcv:1745 status:200
Jan 28 00:32:40.683 - [DEBUG] roundtrip time:268 cost:0 transfer_no:428 send_sn:411 send:581 recv_sn:421 rcv:5997 status:200
Jan 28 00:32:40.822 - [DEBUG] roundtrip time:299 cost:0 transfer_no:429 send_sn:412 send:581 recv_sn:423 rcv:336 status:200
Jan 28 00:32:40.888 - [DEBUG] roundtrip time:699 cost:0 transfer_no:426 send_sn:409 send:840 recv_sn:422 rcv:4669 status:200
Jan 28 00:32:40.958 - [DEBUG] roundtrip time:273 cost:0 transfer_no:431 send_sn:414 send:65 recv_sn:424 rcv:19199 status:200
Jan 28 00:32:40.997 - [DEBUG] roundtrip time:310 cost:0 transfer_no:432 send_sn:415 send:557 recv_sn:425 rcv:17429 status:200
Jan 28 00:32:41.111 - [DEBUG] roundtrip time:287 cost:0 transfer_no:433 send_sn:416 send:96 recv_sn:426 rcv:2200 status:200
Jan 28 00:32:41.179 - [DEBUG] roundtrip time:531 cost:0 transfer_no:430 send_sn:413 send:581 recv_sn:427 rcv:20339 status:200
Jan 28 00:32:41.224 - [DEBUG] roundtrip time:262 cost:0 transfer_no:435 send_sn:418 send:583 recv_sn:428 rcv:1929 status:200
Jan 28 00:32:41.418 - [DEBUG] roundtrip time:300 cost:0 transfer_no:436 send_sn:419 send:1979 recv_sn:429 rcv:14740 status:200
Jan 28 00:32:41.806 - [DEBUG] roundtrip time:578 cost:0 transfer_no:438 send_sn:421 send:585 recv_sn:430 rcv:47851 status:200
Jan 28 00:32:41.832 - [DEBUG] roundtrip time:940 cost:0 transfer_no:434 send_sn:417 send:582 recv_sn:431 rcv:15130 status:200
Jan 28 00:32:41.963 - [DEBUG] roundtrip time:845 cost:0 transfer_no:437 send_sn:420 send:7011 recv_sn:432 rcv:27573 status:200
Jan 28 00:32:41.980 - [INFO] socks5 ('127.0.0.1', 3588) connect to live.github.com:443 conn_id:77
Jan 28 00:32:42.250 - [DEBUG] roundtrip time:269 cost:1 transfer_no:439 send_sn:422 send:34 recv_sn:433 rcv:829 status:200
Jan 28 00:32:42.406 - [DEBUG] roundtrip time:421 cost:0 transfer_no:440 send_sn:423 send:237 recv_sn:434 rcv:45039 status:200
Jan 28 00:32:54.985 - [INFO] socks5 ('127.0.0.1', 3650) connect to live.github.com:443 conn_id:78
Jan 28 00:32:55.256 - [DEBUG] roundtrip time:271 cost:1 transfer_no:441 send_sn:424 send:34 recv_sn:435 rcv:162 status:200
Jan 28 00:32:56.000 - [DEBUG] roundtrip time:742 cost:0 transfer_no:443 send_sn:426 send:65 recv_sn:437 rcv:407232 status:200
Jan 28 00:32:56.002 - [INFO] Conn session:cvsubfax conn:68 Peer Close:recv closed
Jan 28 00:32:56.002 - [DEBUG] Conn session:cvsubfax conn:68 stop:peer close
Jan 28 00:32:56.170 - [DEBUG] roundtrip time:1182 cost:0 transfer_no:442 send_sn:425 send:237 recv_sn:436 rcv:530113 status:200
Jan 28 00:32:56.312 - [DEBUG] roundtrip time:309 cost:0 transfer_no:445 send_sn:428 send:20 recv_sn:439 rcv:30707 status:200
Jan 28 00:32:56.496 - [DEBUG] remove conn_id:68
Jan 28 00:32:56.537 - [DEBUG] roundtrip time:365 cost:0 transfer_no:446 send_sn:429 send:22 recv_sn:440 rcv:16306 status:200
Jan 28 00:32:56.634 - [DEBUG] roundtrip time:320 cost:0 transfer_no:447 send_sn:430 send:65 recv_sn:441 rcv:29055 status:200
Jan 28 00:32:56.752 - [INFO] socks5 ('127.0.0.1', 3662) connect to api.bilibili.com:80 conn_id:79
Jan 28 00:32:56.834 - [DEBUG] roundtrip time:295 cost:0 transfer_no:449 send_sn:432 send:680 recv_sn:442 rcv:11637 status:200
Jan 28 00:32:56.841 - [DEBUG] roundtrip time:1582 cost:0 transfer_no:444 send_sn:427 send:840 recv_sn:438 rcv:238197 status:200
Jan 28 00:32:56.841 - [INFO] Conn session:cvsubfax conn:76 Peer Close:recv closed
Jan 28 00:32:56.842 - [DEBUG] Conn session:cvsubfax conn:76 stop:peer close
Jan 28 00:32:56.845 - [INFO] Conn session:cvsubfax conn:69 Peer Close:recv closed
Jan 28 00:32:56.846 - [DEBUG] Conn session:cvsubfax conn:69 stop:peer close
Jan 28 00:32:57.004 - [DEBUG] roundtrip time:465 cost:182 transfer_no:448 send_sn:431 send:96 recv_sn:443 rcv:5817 status:200
Jan 28 00:32:57.038 - [DEBUG] remove conn_id:69
Jan 28 00:32:57.120 - [DEBUG] remove conn_id:76
Jan 28 00:32:57.120 - [DEBUG] roundtrip time:274 cost:0 transfer_no:454 send_sn:437 send:20 recv_sn:444 rcv:8727 status:200
Jan 28 00:32:57.313 - [DEBUG] roundtrip time:559 cost:306 transfer_no:451 send_sn:434 send:35 recv_sn:446 rcv:282 status:200
Jan 28 00:32:57.328 - [DEBUG] roundtrip time:572 cost:294 transfer_no:452 send_sn:435 send:934 recv_sn:445 rcv:8727 status:200
Jan 28 00:32:57.544 - [DEBUG] roundtrip time:701 cost:182 transfer_no:453 send_sn:436 send:20 recv_sn:447 rcv:8727 status:200
Jan 28 00:32:58.045 - [DEBUG] roundtrip time:19087 cost:0 transfer_no:401 send_sn:384 send:585 recv_sn:395 rcv:3642 status:200
Jan 28 00:32:58.063 - [DEBUG] roundtrip time:19496 cost:0 transfer_no:393 send_sn:376 send:40 recv_sn:390 rcv:181 status:200
Jan 28 00:32:58.354 - [DEBUG] roundtrip time:290 cost:0 transfer_no:455 send_sn:438 send:65 recv_sn:448 rcv:52349 status:200
Jan 28 00:33:08.565 - [DEBUG] Conn session:cvsubfax conn:71 stop:recv fail.
Jan 28 00:33:08.566 - [DEBUG] remove conn_id:71
Jan 28 00:33:09.383 - [DEBUG] roundtrip time:815 cost:0 transfer_no:456 send_sn:439 send:25 recv_sn:450 rcv:525108 status:200
Jan 28 00:33:09.385 - [INFO] Conn session:cvsubfax conn:79 Peer Close:recv closed
Jan 28 00:33:09.387 - [DEBUG] Conn session:cvsubfax conn:79 stop:peer close
Jan 28 00:33:09.760 - [DEBUG] remove conn_id:79
Jan 28 00:33:10.161 - [DEBUG] roundtrip time:775 cost:0 transfer_no:457 send_sn:440 send:20 recv_sn:451 rcv:528189 status:200
Jan 28 00:33:10.984 - [DEBUG] Conn session:cvsubfax conn:70 stop:recv fail.
Jan 28 00:33:10.984 - [DEBUG] remove conn_id:70
Jan 28 00:33:10.988 - [INFO] socks5 ('127.0.0.1', 3745) connect to log.thevideo.me:443 conn_id:80
Jan 28 00:33:11.567 - [DEBUG] roundtrip time:574 cost:0 transfer_no:460 send_sn:443 send:531 recv_sn:454 rcv:58057 status:200
Jan 28 00:33:11.817 - [DEBUG] roundtrip time:827 cost:0 transfer_no:459 send_sn:442 send:34 recv_sn:453 rcv:293039 status:200
Jan 28 00:33:11.896 - [DEBUG] roundtrip time:911 cost:0 transfer_no:458 send_sn:441 send:25 recv_sn:452 rcv:528175 status:200
Jan 28 00:33:15.532 - [DEBUG] Conn session:cvsubfax conn:75 stop:recv fail.
Jan 28 00:33:15.533 - [DEBUG] remove conn_id:75
Jan 28 00:33:15.788 - [DEBUG] roundtrip time:256 cost:0 transfer_no:461 send_sn:444 send:51 recv_sn:455 rcv:177 status:200
Jan 28 00:33:15.915 - [DEBUG] roundtrip time:381 cost:0 transfer_no:462 send_sn:445 send:25 recv_sn:456 rcv:29086 status:200
Jan 28 00:33:16.378 - [DEBUG] roundtrip time:588 cost:0 transfer_no:464 send_sn:447 send:446 recv_sn:458 rcv:43616 status:200
Jan 28 00:33:16.378 - [DEBUG] DATA conn_id 75 not in list
Jan 28 00:33:16.527 - [DEBUG] roundtrip time:737 cost:0 transfer_no:463 send_sn:446 send:65 recv_sn:457 rcv:449776 status:200
Jan 28 00:33:16.529 - [INFO] Conn session:cvsubfax conn:78 Peer Close:recv closed
Jan 28 00:33:16.530 - [DEBUG] Conn session:cvsubfax conn:78 stop:peer close
Jan 28 00:33:16.533 - [DEBUG] DATA conn_id 75 not in list
Jan 28 00:33:16.541 - [WARNING] roundtrip time:20000 transfer_no:450 send_sn:433 send:863 status:'UNKNOWN' retry:1
Jan 28 00:33:16.599 - [INFO] socks5 ('127.0.0.1', 3781) connect to github.com:443 conn_id:81
Jan 28 00:33:16.816 - [DEBUG] roundtrip time:286 cost:0 transfer_no:465 send_sn:448 send:20 recv_sn:459 rcv:58099 status:200
Jan 28 00:33:16.919 - [DEBUG] roundtrip time:319 cost:27 transfer_no:466 send_sn:449 send:29 recv_sn:460 rcv:487 status:200
Jan 28 00:33:17.149 - [DEBUG] roundtrip time:546 cost:0 transfer_no:467 send_sn:450 send:250 recv_sn:461 rcv:29069 status:200
Jan 28 00:33:17.319 - [DEBUG] remove conn_id:78
Jan 28 00:33:17.804 - [DEBUG] roundtrip time:263 cost:0 transfer_no:450 send_sn:433 send:863 recv_sn:449 rcv:8727 status:200
Jan 28 00:33:18.078 - [DEBUG] roundtrip time:272 cost:0 transfer_no:468 send_sn:0 send:0 recv_sn:462 rcv:177 status:200
Jan 28 00:33:18.415 - [DEBUG] roundtrip time:332 cost:47 transfer_no:470 send_sn:452 send:1219 recv_sn:464 rcv:2395 status:200
Jan 28 00:33:18.471 - [DEBUG] roundtrip time:391 cost:0 transfer_no:469 send_sn:451 send:65 recv_sn:463 rcv:92935 status:200
Jan 28 00:33:18.481 - [INFO] socks5 ('127.0.0.1', 3795) connect to api.github.com:443 conn_id:82
Jan 28 00:33:18.749 - [DEBUG] roundtrip time:266 cost:1 transfer_no:471 send_sn:453 send:33 recv_sn:465 rcv:85 status:200
Jan 28 00:33:18.804 - [DEBUG] roundtrip time:319 cost:0 transfer_no:472 send_sn:454 send:250 recv_sn:466 rcv:11654 status:200
Jan 28 00:33:19.015 - [DEBUG] roundtrip time:265 cost:0 transfer_no:473 send_sn:0 send:0 recv_sn:467 rcv:56 status:200
Jan 28 00:33:19.091 - [DEBUG] roundtrip time:286 cost:0 transfer_no:474 send_sn:455 send:49 recv_sn:468 rcv:56 status:200
Jan 28 00:33:19.311 - [DEBUG] roundtrip time:295 cost:0 transfer_no:475 send_sn:456 send:49 recv_sn:469 rcv:7445 status:200
Jan 28 00:33:19.494 - [DEBUG] roundtrip time:399 cost:0 transfer_no:476 send_sn:457 send:49 recv_sn:470 rcv:44955 status:200
Jan 28 00:33:19.581 - [DEBUG] roundtrip time:267 cost:0 transfer_no:477 send_sn:458 send:65 recv_sn:471 rcv:11637 status:200
Jan 28 00:33:19.796 - [DEBUG] roundtrip time:480 cost:0 transfer_no:478 send_sn:459 send:532 recv_sn:472 rcv:5831 status:200
Jan 28 00:33:23.576 - [DEBUG] roundtrip time:305 cost:0 transfer_no:479 send_sn:460 send:22 recv_sn:473 rcv:2200 status:200
Jan 28 00:33:23.975 - [DEBUG] roundtrip time:391 cost:0 transfer_no:481 send_sn:462 send:10038 recv_sn:475 rcv:11623 status:200
Jan 28 00:33:24.176 - [DEBUG] roundtrip time:593 cost:0 transfer_no:480 send_sn:461 send:494 recv_sn:474 rcv:267339 status:200
Jan 28 00:33:30.970 - [DEBUG] Conn session:cvsubfax conn:82 stop:recv fail.
Jan 28 00:33:30.970 - [DEBUG] remove conn_id:82
Jan 28 00:33:31.059 - [INFO] socks5 ('127.0.0.1', 3860) connect to www.qq.com:80 conn_id:83
Jan 28 00:33:31.222 - [DEBUG] roundtrip time:250 cost:0 transfer_no:482 send_sn:463 send:25 recv_sn:476 rcv:829 status:200
Jan 28 00:33:31.223 - [DEBUG] DATA conn_id 82 not in list
Jan 28 00:33:31.776 - [DEBUG] roundtrip time:716 cost:1 transfer_no:483 send_sn:464 send:29 recv_sn:477 rcv:296386 status:200
Jan 28 00:33:32.390 - [DEBUG] roundtrip time:1328 cost:0 transfer_no:484 send_sn:465 send:682 recv_sn:478 rcv:226540 status:200
Jan 28 00:33:32.391 - [INFO] Conn session:cvsubfax conn:81 Peer Close:recv closed
Jan 28 00:33:32.394 - [DEBUG] Conn session:cvsubfax conn:81 stop:peer close
Jan 28 00:33:32.700 - [DEBUG] roundtrip time:307 cost:0 transfer_no:485 send_sn:466 send:20 recv_sn:479 rcv:16037 status:200
Jan 28 00:33:32.719 - [DEBUG] Conn session:cvsubfax conn:53 stop:recv fail.
Jan 28 00:33:32.719 - [DEBUG] remove conn_id:53
Jan 28 00:33:32.809 - [INFO] socks5 ('127.0.0.1', 3867) connect to mat1.gtimg.com:80 conn_id:84
Jan 28 00:33:32.990 - [DEBUG] roundtrip time:272 cost:0 transfer_no:486 send_sn:467 send:51 recv_sn:480 rcv:13057 status:200
Jan 28 00:33:33.086 - [DEBUG] remove conn_id:81
Jan 28 00:33:33.113 - [DEBUG] roundtrip time:299 cost:0 transfer_no:489 send_sn:470 send:384 recv_sn:482 rcv:11634 status:200
Jan 28 00:33:33.114 - [DEBUG] DATA conn_id 53 not in list
Jan 28 00:33:33.299 - [DEBUG] roundtrip time:579 cost:0 transfer_no:487 send_sn:468 send:25 recv_sn:481 rcv:133898 status:200
Jan 28 00:33:33.302 - [DEBUG] DATA conn_id 53 not in list
Jan 28 00:33:33.311 - [INFO] socks5 ('127.0.0.1', 3875) connect to mat1.gtimg.com:80 conn_id:85
Jan 28 00:33:33.332 - [DEBUG] roundtrip time:522 cost:0 transfer_no:488 send_sn:469 send:33 recv_sn:483 rcv:11637 status:200
Jan 28 00:33:33.582 - [DEBUG] roundtrip time:270 cost:0 transfer_no:490 send_sn:471 send:33 recv_sn:484 rcv:23277 status:200
Jan 28 00:33:33.811 - [DEBUG] roundtrip time:497 cost:154 transfer_no:491 send_sn:472 send:456 recv_sn:485 rcv:11651 status:200
Jan 28 00:33:36.899 - [DEBUG] Conn session:cvsubfax conn:84 stop:recv fail.
Jan 28 00:33:36.900 - [DEBUG] remove conn_id:84
Jan 28 00:33:36.903 - [DEBUG] Conn session:cvsubfax conn:85 stop:recv fail.
Jan 28 00:33:36.904 - [DEBUG] remove conn_id:85
Jan 28 00:33:36.945 - [INFO] socks5 ('127.0.0.1', 3896) connect to mat1.gtimg.com:80 conn_id:86
Jan 28 00:33:37.036 - [DEBUG] Conn session:cvsubfax conn:86 stop:recv fail.
Jan 28 00:33:37.036 - [DEBUG] remove conn_id:86
Jan 28 00:33:37.198 - [INFO] socks5 ('127.0.0.1', 3900) connect to www.twitter.com:443 conn_id:87
Jan 28 00:33:37.233 - [DEBUG] roundtrip time:332 cost:0 transfer_no:492 send_sn:473 send:25 recv_sn:486 rcv:72265 status:200
Jan 28 00:33:37.235 - [DEBUG] DATA conn_id 84 not in list
Jan 28 00:33:37.389 - [DEBUG] roundtrip time:440 cost:0 transfer_no:495 send_sn:476 send:466 recv_sn:488 rcv:187419 status:200
Jan 28 00:33:37.407 - [DEBUG] roundtrip time:503 cost:0 transfer_no:493 send_sn:474 send:25 recv_sn:487 rcv:109777 status:200
Jan 28 00:33:37.415 - [DEBUG] DATA conn_id 85 not in list
Jan 28 00:33:37.417 - [DEBUG] roundtrip time:381 cost:63 transfer_no:496 send_sn:477 send:25 recv_sn:489 rcv:28985 status:200
Jan 28 00:33:37.581 - [DEBUG] roundtrip time:382 cost:0 transfer_no:497 send_sn:478 send:34 recv_sn:490 rcv:18863 status:200
Jan 28 00:33:37.644 - [DEBUG] roundtrip time:699 cost:210 transfer_no:494 send_sn:475 send:33 recv_sn:491 rcv:3628 status:200
Jan 28 00:33:37.708 - [DEBUG] roundtrip time:503 cost:41 transfer_no:498 send_sn:479 send:531 recv_sn:492 rcv:20297 status:200
Jan 28 00:33:37.921 - [DEBUG] roundtrip time:273 cost:0 transfer_no:499 send_sn:480 send:140 recv_sn:493 rcv:23673 status:200
Jan 28 00:33:37.922 - [DEBUG] DATA conn_id 86 not in list
Jan 28 00:33:37.976 - [DEBUG] roundtrip time:324 cost:0 transfer_no:500 send_sn:481 send:165 recv_sn:494 rcv:3177 status:200
Jan 28 00:33:38.131 - [DEBUG] roundtrip time:477 cost:0 transfer_no:501 send_sn:482 send:283 recv_sn:495 rcv:69 status:200
Jan 28 00:33:38.335 - [DEBUG] roundtrip time:302 cost:0 transfer_no:502 send_sn:483 send:56 recv_sn:496 rcv:17495 status:200
Jan 28 00:33:38.494 - [DEBUG] roundtrip time:360 cost:0 transfer_no:503 send_sn:484 send:52 recv_sn:497 rcv:27893 status:200

**Comment by jzp820927** [comment]
GAE 怎么样？X_TUNNEL 是通过 GAE 传输的，速度直接取决于 GAE。

**Comment by BreakShadow0504** [comment]
@jzp820927 GAE速度轻微波动。X_Tunnel在选项里开启后，初期也是毫无问题，一旦距离它的开启时间久了，再访问网页就显得十分吃力，一个网页也打不开（视频流仍然在缓存）。求给个诊断。。。

**Comment by jzp820927** [comment]
不好判断，最近 X_TUNNEL 问题较多，不知道是 X_tunnel 自身的原因，还是 GAE 的问题。

**Comment by BreakShadow0504** [comment]
@jzp820927 THX.
