### ISSUE TITLE
可以上fb但是上不了youtube 和 twtter显示连接超时

### ISSUE THREAD

**Issue by Blyth0He** [XX-net/XX-Net#493]
![1](https://cloud.githubusercontent.com/assets/12743647/7979016/2b133fd6-0ace-11e5-9eaf-0557d9089557.PNG)
![Uploading 捕获.PNG…]()

**Comment by Cat7373** [comment]
贴一下日志吧- -
或许会对判断问题有点帮助- -

**Comment by Blyth0He** [comment]
昨天贴了但是上传失败，不过我把以前的文件删除又重新配置了一下，已经解决问题了，谢谢！
