### ISSUE TITLE
window8系统经常崩溃

### ISSUE THREAD

**Issue by ForestLeason** [XX-net/XX-Net#4930]
我的window8系统安装配置好后能够上Google，但过一会就崩溃了，这是什么情况

**Comment by jzp820927** [comment]
不知道你说的“崩溃”具体是指的哪方面？系统？XXNET？

**Comment by ForestLeason** [comment]
就是占用资源过多，电脑卡住，只能强行关机重启

**Comment by jzp820927** [comment]
估计是你系统的问题吧，系统用久了，都会卡的

**Comment by ForestLeason** [comment]
但不开xxnet就没问题，难道不是xxnet的问题？而且我试了五次都是这样。

**Comment by jzp820927** [comment]
这有点不科学，看看任务管理器，CPU 和 内存 的占用。

**Comment by ForestLeason** [comment]
这里也有很多类似问题[为什么用xx net电脑变得很卡？硬件资源占用并不高](https://www.zhihu.com/question/49197879)，建议解决一下。

**Comment by jzp820927** [comment]
Windows 的问题真是多，还是像我这样用 Linux 的一劳永逸。

**Comment by SeaHOH** [comment]
古董 Win7 很好用。
不用 Win8、Win10 完全理解不了，还有 Chrome 64bit。

**Comment by ForestLeason** [comment]
@jzp820927 ，现阶段还没钱

**Comment by jzp820927** [comment]
没钱？不知道你是什么意思？如果你是指的 linux 的话，那个不要钱。

**Comment by ForestLeason** [comment]
我指的是笔记本，这个本本不行了，懒得去折腾，打算以后换新的在折腾Linux

**Comment by jzp820927** [comment]
好吧，也只能这样了。
