### ISSUE TITLE
ipv6模式突然不能用了?

### ISSUE THREAD

**Issue by liulqx** [XX-net/XX-Net#4943]
提示     “启用IPv6失败，请确认你的网络支持IPv6。”
但是确实可以使用ipv6网络啊，pt什么的也可正常用。

ps:只是回了一趟家，回来就不能用了。。
pps:期间更新了Win10.

求问如何解决，who can help me???

**Comment by jzp820927** [comment]
什么版本？

**Comment by SeaHOH** [comment]
搜索 issues  >  尝试  >  失败  >  提问并提供详细信息

**Comment by liulqx** [comment]
ok,我在自定义配置里面强制开启ipv6，可以用了~~
