### ISSUE TITLE
求助：CA证书下载，删除，导入过好几次了，一直显示fail

### ISSUE THREAD

**Issue by wamgel** [XX-net/XX-Net#4944]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:608 good:121
network-status: OK
connected-link: new:3 used:0
worker: h1:18 h2:8
scan-ip-thread-num: 50
ip-quality: 461
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
通过 XX 打开 https://www.google.com 看看显示什么内容/

**Comment by wamgel** [comment]
@jzp820927 
不知道为什么打开google又可以连上了。不过登陆gmai相当慢，等了好几分钟没进去。。。
但是youtube显示：
> 无法访问此网站
连接已重置。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_RESET

**Comment by GoForFree** [comment]
我也是这个问题，打开google后显示“非安全链接”

**Comment by SeaHOH** [comment]
重新导入证书要按基本法来：
1、重启 XX-Net
2、删除证书
3、重启浏览器
4、重新导入证书

**Comment by wamgel** [comment]
@SeaHOH  按你说的来了，依然fail

**Comment by SeaHOH** [comment]
@wamgel 
你先把 XX-Net 关闭
再将data 目录改名备份
然后重新运行 XX-Net 并重新设置
再重新导入证书一次

**Comment by jzp820927** [comment]
@wamgel 你的意思，google 可以正常打开，gmail 一直打不开，youtube 显示连接被重置。

**Comment by wamgel** [comment]
@SeaHOH 谢谢，按你的方法OK了。

@jzp820927 gmail多等一会儿可以打开了，但是youtube偶尔能连上，大部分时候显示超时
> 无法访问此网站
www.youtube.com 的响应时间过长。
请在 Google 中搜索“youtube”
ERR_CONNECTION_TIMED_OUT

上google偶尔又会显示：
> 您的连接不是私密连接
攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_INVALID

**Comment by jzp820927** [comment]
好吧，问题解决了就行

**Comment by wamgel** [comment]
@jzp820927 谢谢
