### ISSUE TITLE
是什么占用空间了？

### ISSUE THREAD

**Issue by lele2010lele** [XX-net/XX-Net#495]
从1.6几用到现在，现在是最新测试版，我的电脑很少关机，是不是一直在扫描ip？
然后发现xx越来越大，是不是里面有什么垃圾文件啊，
我不在乎xx占用多少空间，我只是不明白是什么占用了。
![2015-06-05 9 21 10](https://cloud.githubusercontent.com/assets/10057760/7997736/93047f10-0b64-11e5-9f00-a408b6c48c81.png)

**Comment by Cat7373** [comment]
日志吧。。。

**Comment by Cat7373** [comment]
出门学车。。。
回来再看看。。。

**Comment by linhua55** [comment]
应该是XX-Net/data/goagent下的文件，估计是bad_ip2.txt

**Comment by xxnet** [comment]
刚才看了下，是 data/download目录。
升级后，没有删除对应的文件。

这个要修复。

2015-06-06 10:35 GMT+08:00 linhua55 <notifications@github.com>:
