### ISSUE TITLE
证书一直显示Fail，试了好多方法都没有解决  大神帮忙给看看

### ISSUE THREAD

**Issue by DenonLH** [XX-net/XX-Net#4952]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.103 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:490 good:178
network-status: OK
connected-link: new:1 used:0
worker: h1:7 h2:1
scan-ip-thread-num: 50
ip-quality: 180
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
现在用代理访问个网站，看看能不能用，比如  https://www.google.com

**Comment by DenonLH** [comment]
@jzp820927 不能访问

**Comment by jzp820927** [comment]
如果不能访问，显示的什么内容？

**Comment by DenonLH** [comment]
无法访问此网站

www.google.com.hk 的响应时间过长。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

**Comment by jzp820927** [comment]
https://www.google.com/ncr 呢？
再试试 非加密的网站（不是 https 的）

**Comment by DenonLH** [comment]
都不行

**Comment by jzp820927** [comment]
一样的提示？

**Comment by DenonLH** [comment]
问题完美解决 是插件导致的原因

**Comment by DenonLH** [comment]
问题完美解决   是浏览器插件问题会起冲突  
也谢谢@jzp820927 帮助我解决问题 
解决办法：
删除插件 
清楚插件数据

**Comment by jzp820927** [comment]
插件？什么插件？

**Comment by DenonLH** [comment]
视频屏蔽广告插件  插件名称：视频广告终结者

**Comment by jzp820927** [comment]
哦，没用过这个插件。我都是用 abp 。

**Comment by DenonLH** [comment]
abp 不能屏蔽视频广告  所以我就俩一起用

**Comment by jzp820927** [comment]
不是太明白，一个插件怎么会影响到 XXNET，不明觉厉。

**Comment by DenonLH** [comment]
不好说

**Comment by DenonLH** [comment]
可以能吧

**Comment by jzp820927** [comment]
算了吧，管他 三七二十一，问题解决了就行

**Comment by DenonLH** [comment]
对啊  也谢谢了 帮我解答
