### ISSUE TITLE
请问xx-net什么时候推出android版本？

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#4955]
很强大的软件。期望有手机版

**Comment by jzp820927** [comment]
https://github.com/XX-net/xxnet-android/releases
很久没更新了，可以试试，不保证 100% 能用。其实你可以通过 pac 共享 PC 上的 XXNET 给手机用。

**Comment by THLIVSQAZ** [comment]
安卓4.3没问题，一直在用，偶尔软件不稳定，重开就可以了

**Comment by kirbyzhu** [comment]
安卓6.0安装后无法启动 显示xx界面后闪退

**Comment by jzp820927** [comment]
好像是说只能用于 5以下的系统，不能用，就用 pac 共享吧

**Comment by yuyistar** [comment]
@jzp820927 pac是什么呀。

**Comment by jzp820927** [comment]
自动代理脚本，如果不清楚，可以 google 搜索 pac

**Comment by Sak1tama** [comment]
话说现在安卓挺难翻出去了

**Comment by jzp820927** [comment]
只要有工具，没什么不能翻到

**Comment by kirbyzhu** [comment]
装了个91vpn 感觉还行 就是断断续续

**Comment by gzl6** [comment]
91vpn官网是哪一个？

**Comment by jzp820927** [comment]
google 搜索一下，不什么都有了麽

**Comment by suqingdong** [comment]
可以试试云墙 速度和稳定性都不错

**Comment by gzl6** [comment]
@jzp820927 那你不知道现在山寨得太多了。lantern都有好几个山寨的。随便搜搜91vpn都有十几个号称自己是正宗的网站。

**Comment by jzp820927** [comment]
好吧，基本上不用 VPN，所以也不了解，这些小软件的官网确实难找。

**Comment by gzl6** [comment]
刚刚搜了一下，用了www.betternet.co 的VPN，测下来可用还不错。 
@suqingdong 云墙留着备用，因为不是免费的。谢谢推荐。

**Comment by jzp820927** [comment]
betternet 很早以前测试过，用不了，没想到，你那边还能用。

**Comment by suqingdong** [comment]
@gzl6 试了下betternet 确实不错 
![timg](https://cloud.githubusercontent.com/assets/15026019/22911776/71d790d6-f29c-11e6-82cb-c6fafd76c9c7.jpg)
