### ISSUE TITLE
我很好奇有一天gae的ip会不会全部死掉？

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#4956]
被大力封杀得一干二净？
我只是好奇，难道google的ip真的多到封不住？

**Comment by jzp820927** [comment]
可能性很少，要封死早封了，不会拖到现在，就像物理断网一样，也就是分分钟的事情

**Comment by THLIVSQAZ** [comment]
Google那么强大，应该不会吧

**Comment by wszgrcy** [comment]
真物理断网哪怕SS也没用吧..........

**Comment by jzp820927** [comment]
把你网线拔掉，你还能用 SS？

**Comment by fengixng** [comment]
gfw有实力能全部封掉，但是目前来说，并不会这样做，所以说不会死干净

**Comment by theratlesnake** [comment]
按照目前日益增长的xx-net用户使用数量，总感觉有一天会死掉

**Comment by theratlesnake** [comment]
1600多个ip，看youtube的速度才200多Kbps，速度比VPN还慢。。。。

**Comment by kirbyzhu** [comment]
今天下午ip数量从2800个急剧缩小到800个 不知道是咋回事

**Comment by jzp820927** [comment]
1600多个ip？你指的是总共 1600 多个IP？还是可用的 IP 有 1600 多个？

**Comment by kirbyzhu** [comment]
昨天最低到600个 今天略有反弹

**Comment by jzp820927** [comment]
正常情况，不用惊讶。

**Comment by Sak1tama** [comment]
除非是像朝鲜的物理断网，不然绝对封不掉的

**Comment by kirbyzhu** [comment]
为啥绝对封不掉？再怎么说，就算到了ipv6 ip数量总是有个极限的

**Comment by jzp820927** [comment]
还是硬件负载问题，和发展问题，综合考虑。

**Comment by wooowooo** [comment]
v4真的死了

**Comment by gjbg1989** [comment]
😱现在？不是去年9月下旬？

**Comment by wooowooo** [comment]
帖子是很早以前开的。

看来 “梯高一尺，墙高一丈。不是不封，时候未到。”

**Comment by xxnet** [comment]
​墙高一尺，梯高一仗
