### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by Sak1tama** [XX-net/XX-Net#4959]
目前我的笔记本电脑能正常加载github 的网页，而连接同一个局域网的华为手机默认浏览器打开 git.io 时被劫持到一个无法显示的网站，换成安卓版火狐时显示 error-name-not-resolved ，手机dns已设置为谷歌dns，且手机上未装360，腾讯管家等安全软件。这是怎么回事？

**Comment by jap33** [comment]
手机安上这个试试http://www.coolapk.com/apk/uk.co.mytechie.setDNS

**Comment by jap33** [comment]
安上这个这是手机端hostshttps://github.com/wangchunming/2017hosts

**Comment by Sak1tama** [comment]
谢谢，可以用了
