### ISSUE TITLE
使用XX-Net下载YouTube视频的问题

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#4961]
去年9月份以前，XX-Net一直很稳定，经常我都会用它来帮我下载YouTube视频，而且都是720p,1080p,文件大小都在2g以上，XX-Net都能帮我顺畅的把视频下载下来。但是到了十月份以后经历了一次ip风波，XX-Net变慢了不少，直到现在，使用XX-Net根本不能下载YouTube视频，50m以内的都是失败很多次之后偶尔能下载下来，但是100m以上的机会都没有成功过。YouTube上有很多BBC转播的比赛，高清资源，很多是我最想下来收藏的。

**Comment by Sak1tama** [comment]
用IDM加那个youtube video downloader 插件 IDM 改代理为8087

**Comment by Sak1tama** [comment]
也可以用http://www.clipconverter.cc 解析地址，然后下载

**Comment by andylee1890** [comment]
下载工具，下载插件这些我都试过了，感觉问题不是出在本地的这些工具或插件，感觉像是IP锁定，
就打比：
https://r5---sn-vgqsrn7s.googlevideo.com/videoplayback?expire=1486299767&mime=video%2Fmp4&key=cms1&sparams=dur,ei,expire,gcr,id,initcwndbps,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn&lmt=1486189760007884&dur=11327.994&ratebypass=yes&itag=22&requiressl=yes&upn=zvHvLJQX_sc&ipbits=0&ei=F86WWIDjJcWj4gLgz6XgAw&pl=28&gcr=cn&source=youtube&signature=520F5997535439134B3DD311409CEB2C23297801.786341992C7FE7197287BBC6E5609AB229D203A0&ip=107.178.194.18&id=o-AK6tS8xXf3VIx4MugZmuh_EVNLw48YrXRqvPGqaL-sPI&title=2017%20Masters%20Final%20Session%202%20Joe%20Perry%20vs%20Ronnie%20O%27Sullivan%2022%2001%2017%20BBC%20720p&redirect_counter=1&req_id=3e4334ce24fca3ee&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-vgqsrn7s&ms=au&mt=1486278561&mv=m
这个链接是解析到的一个视频下载地址，但是请求头里带有了指定服务器的IP，但是这个IP迟迟不响应，但是ping是能ping通的

**Comment by andylee1890** [comment]
107.178.194.18
![image](https://cloud.githubusercontent.com/assets/12568851/22624415/96baf146-ebb6-11e6-9f63-f160fcebe191.png)

**Comment by andylee1890** [comment]
![image](https://cloud.githubusercontent.com/assets/12568851/22624419/b59cf37a-ebb6-11e6-9c70-782a1a2925a1.png)
下载到这个程度基本上就不走了

**Comment by andylee1890** [comment]
向googlevideo.com发起请求的代理是我们good_ip.txt配置文件里的，但是googlevideo响应的时候给我们分配了一个新的IP，也就是本次下载的这个：107.178.194.18，ping能ping通，但是下载却始终停在某个节点上，一定有一边断掉了，ping下来的结果是服务器端通畅，那就是本地某处断掉了，究竟问题出在哪，也是我比较费解的

**Comment by Sak1tama** [comment]
也许是不了解服务器的下载机制吧，这个我也不懂。。。你试试www.clipconverter.cc 呗 这个网站出来的地址没问题的

**Comment by andylee1890** [comment]
![image](https://cloud.githubusercontent.com/assets/12568851/22624520/0f738d76-ebb9-11e6-9adf-43249487d5e8.png)
这个应该是提供了中间代理
![image](https://cloud.githubusercontent.com/assets/12568851/22624521/3548b1fc-ebb9-11e6-902c-510aef95059a.png)
比起直接请求googlevideo慢了不少

**Comment by Sak1tama** [comment]
这个应该是先把视频缓存到clipconverter的网站再提供下载的，类似与迅雷的离线下载。。管他呢，能用就行了

**Comment by andylee1890** [comment]
感谢哈，先下一个试试

**Comment by jzp820927** [comment]
看来你们都不太清楚 GAE 的原理，107.178.194.18 是 GAE 服务端的 IP，也就是出口的IP，而 good_ip.txt 里面的 IP 是入口 IP，也就是用来连接到 GAE 服务器的 IP。就类似于路由器的 lan 口和 wan 口的区别。

**Comment by theratlesnake** [comment]
@Sak1tama 你说的idm方法是真的有效么？

**Comment by Sak1tama** [comment]
@theratlesnake 你试试就知道了

**Comment by theratlesnake** [comment]
@Sak1tama 哈哈，又遇见你了

**Comment by BreakShadow0504** [comment]
@jzp820927 Youtube视频“无法下载”似乎与LZ说的无关，但是确实存在，下载中速度极度不稳定，中断，不靠IDM续传就只能等卡死了
XX在下载大文件的时候似乎都会出现类似问题，很尴尬，我想下载UTB上的演唱会，就此作罢，因为太不稳定了，几下就断流了。

**Comment by kirbyzhu** [comment]
试试看 you-get 据说很好用

**Comment by jzp820927** [comment]
下载 ytb 的下载工具真是太多了

**Comment by genliu777** [comment]
近期也是遇到同样的问题！！但是1个月前的时候下载youtube上的视频都没有问题！！不管视频大小如何！！

**Comment by jzp820927** [comment]
还是用6楼的工具下载靠谱

**Comment by linhua55** [comment]
以前测试的时候，xxnet几乎不能下载90M以上的文件，用goproxy可以
