### ISSUE TITLE
如果将Google App引擎设置为US-EAST或者US-CENTRAL?

### ISSUE THREAD

**Issue by gzl6** [XX-net/XX-Net#4968]
在这个界面里面根本看不到
![default](https://cloud.githubusercontent.com/assets/20939122/22642719/e1297f14-ec96-11e6-95ab-ce837a4ab6ca.png)

**Comment by jzp820927** [comment]
#4720

**Comment by gzl6** [comment]
> 2、上方选择刚刚新建的Project3、这时候页面右侧会显示“您的第一个应用”，点开下面的“选择一种语言”，选择Python（GoAgent基于Python，可能并没有实际关系，随便选一个也可以，因为之后并不需要在这里直接建立实例）

现在的界面和4720描数的不太一样了

**Comment by jzp820927** [comment]
不一样了？把不一样的地方截图发上来看看？

**Comment by Sak1tama** [comment]
@gzl6 你试过命令行操作了么 感觉命令行是最稳妥的，界面点半天都不知道自己点哪儿去了

**Comment by gzl6** [comment]
原来要命令行啊，怪不得菜单里面怎么也找不到。不过好像选区域的差别不大，IP都是美国的。谢谢 @jzp820927 @Sak1tama

**Comment by jzp820927** [comment]
选区域是没啥意义，不管你怎么选，出口IP都是 google 总部 山景城。所以不明白，你们选区域有什么意义。
