### ISSUE TITLE
xx-net只对浏览器起作用吗。如果我想让google输入法里面的用户同步登录，怎么可以做到？

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#4969]
也就是说对除浏览器以为的其他软件起作用。。。。win10

**Comment by jzp820927** [comment]
只要软件可以配置代理，或者可以识别系统代理，可以支持导入系统的证书，就都可以用 XX。
不过 google 输入法是不可能同步了，因为 google 输入 N 多年没更新过，而 google 现在的认证系统已经升级为 oauth ，而 google 输入法没有同时升级认证系统，所以通不过认证，就不能登录，也不能同步了。

**Comment by yuyistar** [comment]
恩。你好厉害呀。学习了

**Comment by theratlesnake** [comment]
谷歌还有输入法？学习了
