### ISSUE TITLE
创建新的appid说明（新手必看）

### ISSUE THREAD

**Issue by Sak1tama** [XX-net/XX-Net#4973]
### 1.进入 https://console.cloud.google.com/start  ，点击 `Project`  、创建项目，记下您的项目id，点击创建。

![default](https://cloud.githubusercontent.com/assets/25559628/22787763/5d034fec-ef18-11e6-8fb9-a4e146bbd9bd.png)

### 2.点击搜索框右边的按钮激活云端shell，页面底部会出现黑底白字，输入 `gcloud config set project 23333` ，将前面的23333替换为您的项目id ，按下键盘的enter键，然后输入 `gcloud beta app create --region us-central` ，再按一次enter。

![default](https://cloud.githubusercontent.com/assets/25559628/22777761/3adf4de0-eeef-11e6-89ac-9967809eee0b.png)

### 4.创建完appid之后，新建一个浏览器窗口打开XX-Net的设置页： `http://127.0.0.1:8085` ，切换到 `部署服务端` ,在 `GAE APPID` 输入框里填入你刚才创建的appid

![3-Deploy.png](https://cloud.githubusercontent.com/assets/5118705/19356731/61e3b1ca-91a1-11e6-85b3-c4e034d99d65.png)

### 5.点击 `开始部署 `，如果浏览器阻止弹窗，请点击允许，然后在浏览器弹出的窗口点击 `Allow` ，等待服务端部署完成

![4-RequestForPermission.png](https://cloud.githubusercontent.com/assets/5118705/19356129/501fa69e-919f-11e6-9b7a-549e4a0151de.png)

### 6.切换到 `配置` ，在 `GAE APPID` 输入框里填入你刚才部署的appid，点击保存后即可轻松上网

![5-Config.png](https://cloud.githubusercontent.com/assets/5118705/19356467/884aaba8-91a0-11e6-9f45-4d4648510d64.png)

**Comment by theratlesnake** [comment]
第一个

**Comment by Sak1tama** [comment]
@theratlesnake 刚刚我亲自试了一遍，这样做简单，高效

**Comment by theratlesnake** [comment]
赞一个先

**Comment by jzp820927** [comment]
应该写到 wiki

**Comment by kirbyzhu** [comment]
wiki里面有

**Comment by jzp820927** [comment]
那就重复了。

**Comment by Sak1tama** [comment]
@kirbyzhu 你哪只眼看到wiki里面有shell命令了？？？睁眼说瞎话还不害羞

**Comment by theratlesnake** [comment]
@jzp820927  为啥github的notifications里，点击【all notifications】看不到以前发过评论的帖子了？是github改版了吗？还是我的设置问题

**Comment by jzp820927** [comment]
只要看过的 issues，就会从 notifications 里面消失，除非 issues 有新的回复。
notifications 的作用是提醒，不是收藏夹。

**Comment by Sak1tama** [comment]
@theratlesnake 怎的，你还想找greatfire的那几只五毛谈谈人生经验么 哈哈~~

**Comment by theratlesnake** [comment]
前段时间还可以看到的啊，估计是github升级了吧，超不方便。@Sak1tama 懒得理五毛了

**Comment by whhxmwhh** [comment]
不错的教程。！～

**Comment by kirbyzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/10296293/22722256/b3f487ae-edf0-11e6-8f9d-dcf5e25b8243.png)

@Sak1tama 你如果认真看过wiki 就知道有没有

**Comment by kirbyzhu** [comment]
这个里面有详细的说明 当然 不管是不是选择python都没问题 命令行的方式在里面写得很清楚

**Comment by fafa2018** [comment]
+10086，终于部署成功服务端了，万分感谢

**Comment by theratlesnake** [comment]
楼上是新人？

**Comment by superabe** [comment]
创建多个id，每一个都要部署。默认是从第一个id开始代理，流量用完，再使用下一个，以此类推

**Comment by alexfan2016** [comment]
.点击搜索框右边的按钮激活云端shell? 我怎么没看到有这个按钮？

**Comment by Sak1tama** [comment]
@alexfan2016 现在看到了么

**Comment by Sak1tama** [comment]
@kirbyzhu 这东西是写给新手看了，会的就别逼逼了

**Comment by alexfan2016** [comment]
看到了，谢谢！不过我点击了按钮，没啥反应

**Comment by Sak1tama** [comment]
@alexfan2016 唉，加载不出来可能是翻墙失败了

**Comment by jzp820927** [comment]
就在右边，你账号头像旁边，有5个按钮，从左往右数的第二个。

**Comment by Sak1tama** [comment]
把教程补充完整了，哈哈~~

**Comment by kirbyzhu** [comment]
@sak1tama 就说个wiki里面有 你就跟个疯狗一样 有必要么

**Comment by skydhx** [comment]
无法连google 怎么 创建？ 现在 只要是https 就没法打开，总是报那个您的连接不是私密连接

**Comment by jzp820927** [comment]
#5322

**Comment by xinliya** [comment]
求助，我创建了新的项目，可是哪个激活的按钮不能点，是因为网速加载慢的问题么？

**Comment by jzp820927** [comment]
不知道你说的这个“不能点”应该怎么理解，我点了没任何反应，还是点了有反应，但是打不开？
