### ISSUE TITLE
升级到1.14.10后无法上网。

### ISSUE THREAD

**Issue by wan9wu** [XX-net/XX-Net#499]
升级前备份了一份1.8.5，升级后无法上网，连接数刚打开是1，0。然后就变成0，0了。
用新版的部署了一遍后，都部署成功，还是无法上网。
后用1.8.5，上网非常顺利。
以及有很多视频网站看不了，不知道什么问题，网站能打开，flash播放器会提示视频一直在加载中。

**Comment by wan9wu** [comment]
=====1.14.10========
Jun 6 12:05:06 - [INFO] load manual.ini success
Jun 6 12:05:06 - [INFO] load ip range file:/Applications/XX-Net-1.14.9/data/goagent/ip_range.txt
Jun 6 12:05:06 - [INFO] load google ip_list num:3000, gws num:3000
Jun 6 12:05:06 - [DEBUG] sort ip time:4
Jun 6 12:05:06 - [INFO] SSL use version:TLSv1
Jun 6 12:05:06 - [INFO] ------------------------------------------------------ GoAgent Version : 3.1.49 (python/2.7.6 ) Listen Address : 127.0.0.1:8087 Control Address : 127.0.0.1:8084 GAE APPID : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159 Pac Server : http://127.0.0.1:8086/proxy.pac ------------------------------------------------------
Jun 6 12:05:06 - [INFO] GoAgent CA exist
Jun 6 12:05:08 - [DEBUG] get ip:64.233.189.201 t:104
Jun 6 12:05:08 - [DEBUG] get ip:210.242.125.44 t:401
Jun 6 12:05:08 - [DEBUG] get ip:61.19.1.241 t:441
Jun 6 12:05:08 - [DEBUG] get ip:194.78.99.166 t:498
Jun 6 12:05:09 - [DEBUG] get ip:61.19.1.247 t:542
Jun 6 12:05:09 - [DEBUG] get ip:194.78.99.146 t:556
Jun 6 12:05:09 - [DEBUG] get ip:222.255.120.57 t:637
Jun 6 12:05:10 - [DEBUG] get ip:222.255.120.59 t:638
Jun 6 12:05:10 - [DEBUG] get ip:64.233.162.83 t:712
Jun 6 12:05:10 - [DEBUG] get ip:64.15.119.131 t:743
Jun 6 12:05:11 - [DEBUG] create_ssl update ip:64.233.162.83 time:835
Jun 6 12:05:12 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:4002 h:0
Jun 6 12:05:12 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:4000 h:0
Jun 6 12:05:12 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:12 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:4005 h:0
Jun 6 12:05:12 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:12 - [DEBUG] get ip:178.45.251.40 t:744
Jun 6 12:05:12 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:4001 h:0
Jun 6 12:05:12 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:13 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:4004 h:0
Jun 6 12:05:13 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:13 - [DEBUG] get ip:111.168.255.54 t:744
Jun 6 12:05:13 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:4000 h:0
Jun 6 12:05:13 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:13 - [DEBUG] get ip:220.255.6.20 t:744
Jun 6 12:05:13 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:4002 h:0
Jun 6 12:05:13 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:13 - [DEBUG] get ip:1.179.250.232 t:744
Jun 6 12:05:14 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:4000 h:0
Jun 6 12:05:14 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:14 - [DEBUG] get ip:83.94.121.247 t:744
Jun 6 12:05:14 - [DEBUG] get ip:82.135.118.16 t:744
Jun 6 12:05:14 - [DEBUG] create_ssl 64.15.119.131 fail:timed out cost:4001 h:0
Jun 6 12:05:14 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:14 - [DEBUG] get ip:223.26.69.57 t:744
Jun 6 12:05:15 - [DEBUG] get ip:163.28.116.52 t:744
Jun 6 12:05:15 - [DEBUG] get ip:216.58.221.218 t:744
Jun 6 12:05:16 - [DEBUG] create_ssl 178.45.251.40 fail:timed out cost:4001 h:0
Jun 6 12:05:16 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:17 - [DEBUG] create_ssl 111.168.255.54 fail:timed out cost:4002 h:0
Jun 6 12:05:17 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:17 - [DEBUG] create_ssl 220.255.6.20 fail:timed out cost:4000 h:0
Jun 6 12:05:17 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:17 - [DEBUG] sort ip time:8
Jun 6 12:05:17 - [DEBUG] get ip:216.58.217.36 t:744
Jun 6 12:05:17 - [DEBUG] create_ssl 1.179.250.232 fail:timed out cost:4004 h:0
Jun 6 12:05:17 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:18 - [DEBUG] create_ssl 83.94.121.247 fail:timed out cost:4000 h:0
Jun 6 12:05:18 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:18 - [DEBUG] get ip:66.185.84.54 t:744
Jun 6 12:05:18 - [DEBUG] create_ssl 82.135.118.16 fail:timed out cost:4002 h:0
Jun 6 12:05:18 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:18 - [DEBUG] get ip:81.175.29.185 t:744
Jun 6 12:05:18 - [DEBUG] create_ssl 223.26.69.57 fail:timed out cost:4002 h:0
Jun 6 12:05:18 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:18 - [DEBUG] get ip:64.233.189.201 t:104
Jun 6 12:05:19 - [DEBUG] create_ssl 163.28.116.52 fail:timed out cost:4003 h:0
Jun 6 12:05:19 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:19 - [DEBUG] get ip:210.242.125.44 t:401
Jun 6 12:05:19 - [DEBUG] get ip:61.19.1.241 t:441
Jun 6 12:05:19 - [DEBUG] create_ssl 216.58.221.218 fail:timed out cost:4005 h:0
Jun 6 12:05:19 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:19 - [DEBUG] get ip:194.78.99.166 t:498
Jun 6 12:05:20 - [DEBUG] get ip:61.19.1.247 t:542
Jun 6 12:05:20 - [DEBUG] get ip:194.78.99.146 t:556
Jun 6 12:05:21 - [DEBUG] create_ssl 216.58.217.36 fail:timed out cost:4000 h:0
Jun 6 12:05:21 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:22 - [DEBUG] create_ssl 66.185.84.54 fail:timed out cost:4002 h:0
Jun 6 12:05:22 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:22 - [DEBUG] create_ssl 81.175.29.185 fail:timed out cost:4003 h:0
Jun 6 12:05:22 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:22 - [DEBUG] get ip:222.255.120.57 t:637
Jun 6 12:05:22 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:4004 h:0
Jun 6 12:05:22 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:23 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:4005 h:0
Jun 6 12:05:23 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:23 - [DEBUG] get ip:222.255.120.59 t:638
Jun 6 12:05:23 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:4000 h:0
Jun 6 12:05:23 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:23 - [DEBUG] get ip:64.15.119.131 t:743
Jun 6 12:05:23 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:4003 h:0
Jun 6 12:05:23 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:23 - [DEBUG] get ip:178.45.251.40 t:744
Jun 6 12:05:24 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:4003 h:0
Jun 6 12:05:24 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:24 - [DEBUG] get ip:111.168.255.54 t:744
Jun 6 12:05:24 - [DEBUG] get ip:220.255.6.20 t:744
Jun 6 12:05:24 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:4000 h:0
Jun 6 12:05:24 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:24 - [DEBUG] get ip:1.179.250.232 t:744
Jun 6 12:05:24 - [INFO] GAE CONNECT www.google.com:443
Jun 6 12:05:24 - [DEBUG] GAE CONNECT GET https://www.google.com/search?q=nihao
Jun 6 12:05:25 - [DEBUG] get ip:83.94.121.247 t:744
Jun 6 12:05:25 - [DEBUG] get ip:82.135.118.16 t:744
Jun 6 12:05:26 - [INFO] GAE CONNECT www.google.com:443
Jun 6 12:05:26 - [DEBUG] GAE CONNECT GET https://www.google.com/xjs/_/js/sdch=d/k=xjs.s.en_US.5wK9YTZP3cY.O/m=sx,c,sb,cdos,cr,elog,jsa,r,hsm,j,p,d,csi/am=hEoI8TcYCAOTCqoJoQ4/rt=j/d=1/t=zcms/rs=ACT90oGV9BtAub1RGPjYQ6HA_g7JDFwLig
Jun 6 12:05:26 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:4005 h:0
Jun 6 12:05:26 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:26 - [INFO] DIRECT chucked t:1958 s:99782 200 www.google.com /search?q=nihao
Jun 6 12:05:27 - [INFO] GAE CONNECT clients5.google.com:443
Jun 6 12:05:27 - [DEBUG] GAE CONNECT GET https://clients5.google.com/pagead/drt/dn/
Jun 6 12:05:27 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:4004 h:0
Jun 6 12:05:27 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:27 - [DEBUG] create_ssl 64.15.119.131 fail:timed out cost:4003 h:0
Jun 6 12:05:27 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:27 - [DEBUG] sort ip time:8
Jun 6 12:05:27 - [DEBUG] get ip:223.26.69.57 t:744
Jun 6 12:05:27 - [DEBUG] create_ssl 178.45.251.40 fail:timed out cost:4002 h:0
Jun 6 12:05:27 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:28 - [DEBUG] create_ssl 111.168.255.54 fail:timed out cost:4004 h:0
Jun 6 12:05:28 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:28 - [DEBUG] get ip:163.28.116.52 t:744
Jun 6 12:05:28 - [DEBUG] create_ssl 220.255.6.20 fail:timed out cost:4003 h:0
Jun 6 12:05:28 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:28 - [DEBUG] get ip:216.58.221.218 t:744
Jun 6 12:05:28 - [DEBUG] create_ssl 1.179.250.232 fail:timed out cost:4000 h:0
Jun 6 12:05:28 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:29 - [DEBUG] get ip:64.233.189.201 t:104
Jun 6 12:05:29 - [DEBUG] create_ssl 83.94.121.247 fail:timed out cost:4000 h:0
Jun 6 12:05:29 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:29 - [DEBUG] get ip:210.242.125.44 t:401
Jun 6 12:05:29 - [DEBUG] get ip:61.19.1.241 t:441
Jun 6 12:05:29 - [DEBUG] create_ssl 82.135.118.16 fail:timed out cost:4004 h:0
Jun 6 12:05:29 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:29 - [DEBUG] get ip:194.78.99.166 t:498
Jun 6 12:05:30 - [DEBUG] get ip:61.19.1.247 t:542
Jun 6 12:05:30 - [DEBUG] get ip:194.78.99.146 t:556
Jun 6 12:05:31 - [DEBUG] create_ssl 223.26.69.57 fail:timed out cost:4000 h:0
Jun 6 12:05:31 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:32 - [INFO] GAE CONNECT plus.google.com:443
Jun 6 12:05:32 - [DEBUG] GAE CONNECT GET https://plus.google.com/u/0/_/notifications/frame?sourceid=1&hl=en&origin=https%3A%2F%2Fwww.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.6zwg_pEP_2A.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTNy-00ELgURzlKy-V-78pEvv5BpHA
Jun 6 12:05:32 - [DEBUG] create_ssl 163.28.116.52 fail:timed out cost:4002 h:0
Jun 6 12:05:32 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:32 - [INFO] GAE CONNECT www.google.com:443
Jun 6 12:05:32 - [DEBUG] GAE CONNECT GET https://www.google.com/search?sclient=psy-ab&newwindow=1&btnG=Search&q=%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5%EF%BC%9F
Jun 6 12:05:32 - [DEBUG] create_ssl 216.58.221.218 fail:timed out cost:4002 h:0
Jun 6 12:05:32 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:32 - [DEBUG] get ip:222.255.120.57 t:637
Jun 6 12:05:33 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:4005 h:0
Jun 6 12:05:33 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:33 - [INFO] GAE CONNECT live.github.com:443
Jun 6 12:05:33 - [DEBUG] GAE CONNECT GET https://live.github.com/_sockets/NDgzMTEwNjpmNjRjYzI1YTM4MmZlMzk1M2M0NzljYmNhYTc4MmMzNTozZjdlOGE2N2U1ZTg1ZGRkODllMjEwMjM1N2Y1OTE0ZDIzZTUxOWJmYzAzYzI0ODJmMjFjZjExNjdhNDJkM2E2--ad18d7d1341d43c7a2dcc68832a87668f8fac355
Jun 6 12:05:33 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:4000 h:0
Jun 6 12:05:33 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:33 - [DEBUG] get ip:222.255.120.59 t:638
Jun 6 12:05:33 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:4002 h:0
Jun 6 12:05:33 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:33 - [DEBUG] get ip:64.15.119.131 t:743
Jun 6 12:05:33 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:4000 h:0
Jun 6 12:05:33 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:34 - [DEBUG] get ip:178.45.251.40 t:744
Jun 6 12:05:34 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:4000 h:0
Jun 6 12:05:34 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:34 - [DEBUG] get ip:111.168.255.54 t:744
Jun 6 12:05:34 - [DEBUG] get ip:220.255.6.20 t:744
Jun 6 12:05:34 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:4002 h:0
Jun 6 12:05:34 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:34 - [DEBUG] get ip:1.179.250.232 t:744
Jun 6 12:05:35 - [DEBUG] get ip:83.94.121.247 t:744
Jun 6 12:05:35 - [DEBUG] get ip:82.135.118.16 t:744
Jun 6 12:05:36 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:4003 h:0
Jun 6 12:05:36 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:37 - [INFO] GAE CONNECT p5-rxdentthipxxu-akub6npkuu666yib-742309-i1-v6exp3-v4.metric.gstatic.com:443
Jun 6 12:05:37 - [INFO] GAE CONNECT p5-rxdentthipxxu-akub6npkuu666yib-742309-i2-v6exp3-ds.metric.gstatic.com:443
Jun 6 12:05:37 - [DEBUG] GAE CONNECT GET https://p5-rxdentthipxxu-akub6npkuu666yib-742309-i1-v6exp3-v4.metric.gstatic.com/v6exp3/6.gif
Jun 6 12:05:37 - [DEBUG] GAE CONNECT GET https://p5-rxdentthipxxu-akub6npkuu666yib-742309-i2-v6exp3-ds.metric.gstatic.com/v6exp3/6.gif
Jun 6 12:05:37 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:4003 h:0
Jun 6 12:05:37 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:37 - [DEBUG] create_ssl 64.15.119.131 fail:timed out cost:4000 h:0
Jun 6 12:05:37 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:37 - [DEBUG] sort ip time:7
Jun 6 12:05:37 - [DEBUG] get ip:223.26.69.57 t:744
Jun 6 12:05:38 - [DEBUG] create_ssl 178.45.251.40 fail:timed out cost:4000 h:0
Jun 6 12:05:38 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:38 - [DEBUG] create_ssl 111.168.255.54 fail:timed out cost:4000 h:0
Jun 6 12:05:38 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:38 - [DEBUG] get ip:163.28.116.52 t:744
Jun 6 12:05:38 - [DEBUG] create_ssl 220.255.6.20 fail:timed out cost:4000 h:0
Jun 6 12:05:38 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:38 - [DEBUG] get ip:216.58.221.218 t:744
Jun 6 12:05:38 - [INFO] GAE CONNECT www.google.com:443
Jun 6 12:05:38 - [DEBUG] GAE CONNECT GET https://www.google.com/search?sclient=psy-ab&newwindow=1&btnG=Search&q=%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5%EF%BC%9F
Jun 6 12:05:38 - [DEBUG] create_ssl 1.179.250.232 fail:timed out cost:4003 h:0
Jun 6 12:05:38 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:39 - [DEBUG] get ip:64.233.189.201 t:104
Jun 6 12:05:39 - [DEBUG] create_ssl 83.94.121.247 fail:timed out cost:4002 h:0
Jun 6 12:05:39 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:39 - [DEBUG] get ip:210.242.125.44 t:401
Jun 6 12:05:39 - [DEBUG] get ip:61.19.1.241 t:441
Jun 6 12:05:39 - [DEBUG] create_ssl 82.135.118.16 fail:timed out cost:4004 h:0
Jun 6 12:05:39 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:39 - [DEBUG] get ip:194.78.99.166 t:498
Jun 6 12:05:40 - [DEBUG] get ip:61.19.1.247 t:542
Jun 6 12:05:40 - [DEBUG] get ip:194.78.99.146 t:556
Jun 6 12:05:41 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:41 - [DEBUG] create_ssl 223.26.69.57 fail:timed out cost:4004 h:0
Jun 6 12:05:41 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:42 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:42 - [DEBUG] create_ssl 163.28.116.52 fail:timed out cost:4001 h:0
Jun 6 12:05:42 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:42 - [DEBUG] create_ssl 216.58.221.218 fail:timed out cost:4003 h:0
Jun 6 12:05:42 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:42 - [DEBUG] get ip:222.255.120.57 t:637
Jun 6 12:05:43 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:4002 h:0
Jun 6 12:05:43 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:43 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:4005 h:0
Jun 6 12:05:43 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:43 - [DEBUG] get ip:222.255.120.59 t:638
Jun 6 12:05:43 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:4000 h:0
Jun 6 12:05:43 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:43 - [DEBUG] get ip:64.15.119.131 t:743
Jun 6 12:05:43 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:4003 h:0
Jun 6 12:05:43 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:44 - [DEBUG] get ip:178.45.251.40 t:744
Jun 6 12:05:44 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:4000 h:0
Jun 6 12:05:44 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:44 - [DEBUG] get ip:111.168.255.54 t:744
Jun 6 12:05:44 - [DEBUG] get ip:220.255.6.20 t:744
Jun 6 12:05:44 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:4003 h:0
Jun 6 12:05:44 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:44 - [DEBUG] get ip:1.179.250.232 t:744
Jun 6 12:05:45 - [DEBUG] get ip:83.94.121.247 t:744
Jun 6 12:05:45 - [DEBUG] get ip:82.135.118.16 t:744
Jun 6 12:05:46 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:4001 h:0
Jun 6 12:05:46 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:47 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:47 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:4003 h:0
Jun 6 12:05:47 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:47 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:47 - [DEBUG] create_ssl 64.15.119.131 fail:timed out cost:4001 h:0
Jun 6 12:05:47 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:47 - [DEBUG] sort ip time:8
Jun 6 12:05:47 - [DEBUG] get ip:223.26.69.57 t:744
Jun 6 12:05:48 - [DEBUG] create_ssl 178.45.251.40 fail:timed out cost:4000 h:0
Jun 6 12:05:48 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:48 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:48 - [DEBUG] create_ssl_connection fail
Jun 6 12:05:48 - [DEBUG] create_ssl 111.168.255.54 fail:timed out cost:4005 h:0
Jun 6 12:05:48 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:48 - [DEBUG] get ip:163.28.116.52 t:744
Jun 6 12:05:48 - [DEBUG] create_ssl 220.255.6.20 fail:timed out cost:4005 h:0
Jun 6 12:05:48 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:48 - [DEBUG] get ip:216.58.221.218 t:744
Jun 6 12:05:48 - [DEBUG] create_ssl 1.179.250.232 fail:timed out cost:4004 h:0
Jun 6 12:05:48 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:49 - [DEBUG] get ip:64.233.189.201 t:104
Jun 6 12:05:49 - [DEBUG] create_ssl 83.94.121.247 fail:timed out cost:4004 h:0
Jun 6 12:05:49 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:49 - [DEBUG] get ip:210.242.125.44 t:401
Jun 6 12:05:49 - [DEBUG] get ip:61.19.1.241 t:441
Jun 6 12:05:49 - [DEBUG] create_ssl 82.135.118.16 fail:timed out cost:4001 h:0
Jun 6 12:05:49 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:49 - [DEBUG] get ip:194.78.99.166 t:498
Jun 6 12:05:50 - [DEBUG] get ip:61.19.1.247 t:542
Jun 6 12:05:50 - [DEBUG] get ip:194.78.99.146 t:556
Jun 6 12:05:51 - [DEBUG] create_ssl 223.26.69.57 fail:timed out cost:4004 h:0
Jun 6 12:05:51 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:52 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:52 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:52 - [DEBUG] create_ssl 163.28.116.52 fail:timed out cost:4000 h:0
Jun 6 12:05:52 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:52 - [DEBUG] create_ssl 216.58.221.218 fail:timed out cost:4005 h:0
Jun 6 12:05:52 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:52 - [DEBUG] get ip:222.255.120.57 t:637
Jun 6 12:05:53 - [DEBUG] create_ssl 64.233.189.201 fail:timed out cost:4004 h:0
Jun 6 12:05:53 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:53 - [DEBUG] create_ssl 210.242.125.44 fail:timed out cost:4001 h:0
Jun 6 12:05:53 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:53 - [DEBUG] get ip:222.255.120.59 t:638
Jun 6 12:05:53 - [DEBUG] create_ssl 61.19.1.241 fail:timed out cost:4000 h:0
Jun 6 12:05:53 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:53 - [DEBUG] get ip:64.15.119.131 t:743
Jun 6 12:05:53 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:53 - [DEBUG] create_ssl 194.78.99.166 fail:timed out cost:4000 h:0
Jun 6 12:05:53 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:54 - [DEBUG] get ip:178.45.251.40 t:744
Jun 6 12:05:54 - [DEBUG] create_ssl 61.19.1.247 fail:timed out cost:4001 h:0
Jun 6 12:05:54 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:54 - [DEBUG] get ip:111.168.255.54 t:744
Jun 6 12:05:54 - [DEBUG] get ip:220.255.6.20 t:744
Jun 6 12:05:54 - [DEBUG] create_ssl 194.78.99.146 fail:timed out cost:4001 h:0
Jun 6 12:05:54 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:54 - [DEBUG] get ip:1.179.250.232 t:744
Jun 6 12:05:55 - [DEBUG] get ip:83.94.121.247 t:744
Jun 6 12:05:55 - [DEBUG] get ip:82.135.118.16 t:744
Jun 6 12:05:56 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:56 - [DEBUG] create_ssl 222.255.120.57 fail:timed out cost:4004 h:0
Jun 6 12:05:56 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:57 - [DEBUG] create ssl timeout fail.
Jun 6 12:05:57 - [DEBUG] create_ssl 222.255.120.59 fail:timed out cost:4004 h:0
Jun 6 12:05:57 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:57 - [DEBUG] create_ssl 64.15.119.131 fail:timed out cost:4003 h:0
Jun 6 12:05:57 - [DEBUG] report_connect_fail network fail
Jun 6 12:05:57 - [DEBUG] sort ip time:7
Jun 6 12:05:57 - [DEBUG] get ip:223.26.69.57 t:744


网页端提示：
连接超时，先休息一会再来！

504 GoAgent Proxy Time out

**Comment by xxnet** [comment]
解决方案：把原来的data 目录拷贝过去。

原因是你以前扫描到的ip，才能快速上网。
目前下载包里的ip，都是被封的差不多了。

2015-06-06 12:07 GMT+08:00 wan9wu <notifications@github.com>:

**Comment by wan9wu** [comment]
大谢，解决了。
