### ISSUE TITLE
电脑的xxnet代理要怎么能给手机用？

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#4990]
电脑有无线网卡，通过无线网卡建立wifi分享代理可行吗？xxnet上需要设置什么？

**Comment by muyufan** [comment]
我是在电脑安装ccproxy设置二级代理，给手机用的

**Comment by jzp820927** [comment]
@Temmie-hOi 话说，你就没一个无线路由器？还要用无线网卡？
@muyufan 用不着二级代理，XX就可以分享代理，只要你手机和电脑在同一个局域网。

**Comment by SeaHOH** [comment]
电脑运行代理分享给手机，推荐 GoGo；
手机自己运行代理，推荐 SS/SSR。

以上设置都很简单，GoGo 有提供公共代理，免费 SS/SSR 分享社区也挺多的。

**Comment by Temmie-hOi** [comment]
@jzp820927 在同一个局域网的话，怎么分享代理

**Comment by muyufan** [comment]
xx-net 或者说底层的goagent的确提供局域网代理的功能，xxnet的高级设置里面。
但是我从来没成功过，手机连上代理后要么是翻不了墙，要么是只能看网页看不了youtube。
懒得去找原因，调试什么的，我就直接用ccproxy的二级代理功能了。

**Comment by SeaHOH** [comment]
非要用无线网卡，自己搜索 `net 命令 网卡 热点`，还要用 XX-Net 的话，设置可能比较麻烦。

必须按顺序来。
1、先开热点；
2、XX-Net 设置监听 `0.0.0.0`，已经设置可以忽略；
3、重启 XX-Net；
4、登录 Wifi 热点并设置 Wifi 代理，地址要搞对。

**Comment by theratlesnake** [comment]
手机用ssr超级方便

**Comment by jzp820927** [comment]
哎，共享比较麻烦，有条件的，建议手机用 SS，方便很多。

**Comment by kirbyzhu** [comment]
手机上还要装证书，这个比较烦人 所以用ss还是比较方便

**Comment by jzp820927** [comment]
证书是 GAE 类代理最大的缺陷。

**Comment by xuwanglin** [comment]
新建一个manual文件改下监听代理和pac自动代理地址，手机装下证书，用realmb上传下载安装很快，然后改下手机的代理，填电脑的ip和8087端口，这样就能用了，不过只要有你电脑IP的人都能用你的电脑做代理

**Comment by xuwanglin** [comment]
0.0.0.0 8087怎么设置密码，username password添加到manual中没有作用

**Comment by jzp820927** [comment]
XXNET，不支持认证，如果想要认证，可以考虑 XXMINI，也是基于 XXNET 的项目，是 XXNET 的精简版

**Comment by Temmie-hOi** [comment]
gae给手机用后怎么设置不经过gae的网站？pac有效吗？@jzp820927

**Comment by jzp820927** [comment]
PAC 对浏览器没问题，APPS 好像无效。

**Comment by zhangxulong** [comment]
装了证书，还是不能上网

**Comment by jzp820927** [comment]
那就得检查 XX 的设置了

**Comment by cocococowu** [comment]
@jzp820927  我也想电脑共享给手机科学上网，电脑上XX使用正常，也在Gae的配置文件里新增了[listen] ip = 0.0.0.0，重启XX正常可以科学上网， 手机上装了shadowsocks的app，服务器IP添电脑IP，服务器端口写8087，本地端口1080，还要输入密码（不能为空），我就输了我电脑的密码=.=， 这样上不了网，请问哪里出错了呢？谢谢大神。

**Comment by jzp820927** [comment]
我也是醉了，这个是 GAE 代理，不是 SS，你手机装 shadowsocks 干嘛？

**Comment by cocococowu** [comment]
@jzp820927  你上面说到“哎，共享比较麻烦，有条件的，建议手机用 SS，方便很多。”   那请问不是这个Shadowsocks么？  另外上面说到电脑共享给手机上网比较麻烦，是不是手机装个什么APP可以直接共享电脑的网络上网，这样省事一点？

**Comment by jzp820927** [comment]
我上面说的 SS 是另外的方案，和 GAE 没有任何关系，扯不到一起去。SS 需要自己有 VPS，或者自己去找账号。共享的麻烦之处主要是需要安装证书，wifi 直接就可以设置代理，不需要 app 也行。不过是全局代理。

**Comment by cocococowu** [comment]
好吧

获取 Outlook for Android<https://aka.ms/ghei36>


发件人: 天朝屁民
发送时间: 3月1日星期三 01:55
主题: Re: [XX-net/XX-Net] 电脑的xxnet代理要怎么能给手机用？ (#4990)
收件人: XX-net/XX-Net
抄送: cocococowu, Comment

我上面说的 SS 是另外的方案，和 GAE 没有任何关系，扯不到一起去。SS 需要自己有 VPS，或者自己去找账号。共享的麻烦之处主要是需要安装证书，wifi 直接就可以设置代理，不需要 app 也行。不过是全局代理。

―

**Comment by whuwangyong** [comment]
看wiki：
 https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1
