### ISSUE TITLE
升级到3.2.9/3.2.10以后Google连接不稳定

### ISSUE THREAD

**Issue by chpsky** [XX-net/XX-Net#5005]
升级到3.2.9/3.2.10以后Google连接不稳定，有时连接不上，说连接超时。
查了之前的别人提的issue，说是3.2.9开始与Google的连接方式改成直连了，但我希望与Google的连接能稳定点，及时有验证码也没关系。
那还能手动改成与Google为非直连吗？如果不能改，那有什么方法可以提高与Google的连接成功率呢？

谢谢！

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config

**Comment by chpsky** [comment]
@SeaHOH 搞定了，谢谢！

**Comment by chpsky** [comment]
@

**Comment by jzp820927** [comment]
验证码和稳定性是个两难的问题，不过目前看来，直连的稳定性很差，估计要回退到验证码的方案了，除非能改进 IP 筛选的策略

**Comment by chpsky** [comment]
@jzp820927 是啊，用直连偶尔能打开，大部分情况是打不开的。

**Comment by jzp820927** [comment]
主要是去年 11 月份开始的强力干扰，之前直连还是很稳定的。说不定那次干扰就是针对 XX 的。
