### ISSUE TITLE
3.3.0 貌似有点问题

### ISSUE THREAD

**Issue by myjlpt** [XX-net/XX-Net#5006]
问题描述：

CHROME 下配合Proxy SwitchyOmega 会出现代理冲突；导致优酷，土豆 ，爱奇异的网页视频无法播放。

切回3.2.9后正常

 请知悉。

PS:以判断出是其他代理导致的问题。关闭主题

**Comment by jzp820927** [comment]
代理冲突？不会是装了多个代理插件吧？

**Comment by myjlpt** [comment]
@jzp820927 扯，不可能。都是之前一直正常用的插件.

就算ADfree.Player.Online，和蓝灯插件也是关掉代理，在Proxy SwitchyOmega下设置的。

**Comment by SeaHOH** [comment]
信息太少，别人无法重现。

**Comment by jzp820927** [comment]
最好把你有问题的地方，截个图来看看。没遇到过这种问题。

**Comment by myjlpt** [comment]
这种问题还真没法截图，难道截取，不能播放和能正常播放的视频界面？

**Comment by SeaHOH** [comment]
比如设置、状态啥的。

**Comment by jzp820927** [comment]
你说的代理冲突，是怎么表现出来的？总有个表现方式吧，就是视频不能放？

**Comment by myjlpt** [comment]
==我先自己研究下。可能是UPYUN和百度CDN的播放代理自己的问题。回头再报告

**Comment by myjlpt** [comment]
已经确认是ADfree.Player.Online，代理问题。那个之前挂载点不稳定，正巧我升级3.3后出现问题，而在回滚3.2.9时候又正常了。之后呢，多次测试，3.2.9上面也表现出问题。在将代理换到irs01.com上现在以正常。
