### ISSUE TITLE
打开xx-net后使用chrome浏览网页，电脑有时会卡死一段时间，不知道有人遇到过没？

### ISSUE THREAD

**Issue by yachji** [XX-net/XX-Net#5011]
我的环境如下：
1、 Windows 10 64位操作系统
2、Chrome 56.0.2924.87 (64-bit) 版本的浏览器
3、xx-net 3.2.9
具体描述：
        打开xx-net后，再启动Chrome打开两三个选项卡浏览网页时，有时整个电脑会卡死一分钟左右。此时我停止操作电脑等一段时间，电脑会自动回复正常，可以继续浏览网页。在将xx-net升级到3.2.9之前用的3.2.8也会出现这个问题。

**Comment by jzp820927** [comment]
没遇到过类似问题，会不会是 chrome 的问题，听说 64 位的 chrome 有类似问题。

**Comment by yachji** [comment]
@jzp820927  你好。可是我如果不使用xx-net，似乎就没遇到过这样的问题。我也是刚刚使用xx-net的，以前我只使用Chrome是没有问题的。

**Comment by jzp820927** [comment]
没遇到此类问题。不知道和系统有没有关系。issues 上反映 win10 的问题较多

**Comment by Sak1tama** [comment]
@yachji 你电脑中毒了吧

**Comment by yachji** [comment]
@Sak1tama  你好，我认为不太可能是中毒的原因。理由如下：
1、我家里的笔记本和我办公室的台式电脑有同样的问题，环境也都是完全一样的。（windows 10 64位操作系统，Chrome版本 56.0.2924.87 (64-bit)）
2、这个问题是在先启动xx-net后再启动Chrome时打开三到四个选项卡出现的（一般浏览网页一段时间发生）。
3、一般卡死后等待将近一分钟电脑会自动恢复响应。然后再继续浏览网页基本不会再出现这种问题。
这个问题似乎集中出现在Chrome刚运行的那段时间内。
4、我从不看小电影(*＾-＾*)

**Comment by Sak1tama** [comment]
@yachji 我的是win 10 14393 64 + firefox 45.7 ESR 个人认为firefox较为稳定 以前机子差用chrome经常100% cpu 而firefox 不会

**Comment by jzp820927** [comment]
要不把扫描线程数调低试试

**Comment by yachji** [comment]
@jzp820927 好的，我来试下。

**Comment by myjlpt** [comment]
有种情况，会这样 ；平台 WIN7 /10 16G内存 I7 4790K 上； GreenChrome 启动器来启动chrome就会这样。原因未知

**Comment by kirbyzhu** [comment]
我的系统、配置和chrome版本和楼主是完全一样的 没有出现类似的问题 之前是2.9的时候没有 现在是3.0了也一样没有

**Comment by kirbyzhu** [comment]
ps 我不用greenchrome

**Comment by kirbyzhu** [comment]
ps 我不用greenchrome

**Comment by Dimagrio** [comment]
如果你的内存不是很够的话，你把chrome换到32bit就不会了

**Comment by roc1010kmt** [comment]
ｗｉｎ１０卡頓現象一直有，目前已知ｘｘｎｅｔ和BitComet都會引起卡頓，不會卡１分鐘，基本１到２秒左右．卡頓應該和網路有關．

**Comment by jianglwei** [comment]
之前这个问题已经出现几次了，把chrome换为32位即可，原因是switchy插件与64位兼容不是很好。

**Comment by yachji** [comment]
@jianglwei 我好几年用的goagent  好像也用到了switchy插件，没有卡顿。但是我不记得当时的chrome是不是64位了。

**Comment by yachji** [comment]
@roc1010kmt 我一卡就是整个电脑全没反应。按CTRL+ALT+DELETE都没反应的那种。一般要等个好几十秒才能反应过来。应该不是网络关系，因为家里和工作地方的电脑都有这个现象。我还是试试jzp820927所说的把扫描线程调看能不能解决。

**Comment by yachji** [comment]
@Dimagrio 我的内存就是4G，不知道内存算不算不够？我没打开其他什么东西。就开了个XX-net，Chrome，QQ还有个PDF文件。

**Comment by SeaHOH** [comment]
长时间卡有可能是显卡问题，短暂的卡可能是声卡问题。更新驱动会有改善。
但是旧硬件配新系统（Win8 及以上）可能就没有新驱动了，或者有但是实际上未改进。

**Comment by yachji** [comment]
@SeaHOH 你说的很有道理，我的笔记本可能是2013年买的，单位工作的台式机更是2011年买的。可能确实有些老了。联想笔记本的的独立显卡有缺陷，被我禁了，一直用的集成显卡。

**Comment by yachji** [comment]
刚刚我在家中的笔记本中试了下，又重现了这个问题。明天我去单位尝试降低一下扫描线程数看能否解决这个问题。我的笔记本显卡虽然是有点问题的，但是我在单位用的台式机一直是没问题的。明天早上我将结果告诉各位。

**Comment by WLZLCX** [comment]
Proxy SwitchyOmega 扩展引起的

用64位Chrome的话，内存至少8G以上，否则的话 肯定会出现整个系统卡顿

如果非要用64位Chrome，请删除扩展，改用XX-Net来接管系统全局代理

**Comment by yachji** [comment]
@WLZLCX 我今天试试你说的方法。用xx-net接管系统全局代理。我只是奇怪为什么只是开始卡一次，后面就不会出现这样的情况了。卡死不是一直伴随我的使用过程的。

**Comment by jzp820927** [comment]
直接用隐身模式，就可以禁用所有扩展了。

**Comment by yachji** [comment]
今天采用WLZLCX的方法，选择“全局通过GAEProxy代理”，没有出现任何异常。晚上回去我再将我的笔记本也设置下，如果不出现问题，那么应该就可以确定是插件的原因了。

**Comment by WLZLCX** [comment]
@yachji 我主用ShadowsocksR，它完全没这方面的问题，无论用它的全局模式或者PAC模式

**Comment by Sak1tama** [comment]
@WLZLCX 傻逼，你是来坑钱的吧 我建议用chrome 32 版本 64 可能会出一些奇怪的问题，楼主就遇到了

**Comment by WLZLCX** [comment]
@Sak1tama 傻逼是你！我用过多个代理工具，也有其它工具可选ShadowsocksR，GoProxy，Lantern等

换着用 有何不可？免费的随便用谁

别忘了Shadowsocks也有免费网站和收费网站，随便选择，一切以速度为主，看个人需求

**Comment by Dimagrio** [comment]
@yachji 全局总有不太方便的，你只有4G，那就用32bit（开全局下安装程序安装），我不知道这是插件的问题还是什么，照理32bit程序可以申请到的内存比较有限一点吧，不过好像又chrome开标签或者同网站开扩展都要一个进程，但是个人觉得总觉是要互动到主的进程吧，这样也许就不至于直接内存爆满卡死掉，当然也许我理解的不对，有人有比较正确的也可以赐教下我，感谢！

**Comment by yachji** [comment]
@WLZLCX @jzp820927 @Dimagrio @SeaHOH @roc1010kmt   选择“全局通过GAEProxy代理”，可以解决问题。工作的台式机和家里的笔记本都没问题了。但是我仍然觉得不是内存不够的原因。因为我看了，我的内存是3.9G正常也就用了2.3G.所以应该就是插件的问题，不太可能是内存过小的原因。谢谢大家。

**Comment by seashore001x** [comment]
是因为Utility: V8 proxy resolver这个进程内存暴增的原因。关掉xx-net就没问题了。不知道到底是xx-net的问题呢还是proxyomega的问题，现在表示以及改用shadowsokcs了
