### ISSUE TITLE
这几天ip越来越少了,大家的呢?

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#5012]
最近发现越来越慢了,前几天600,今天300了

大家的情况怎么样?

**Comment by jzp820927** [comment]
一样的，常态

**Comment by wooyunwang** [comment]
妹的，自动升级到测试版了，能不能不删除插件的情况下，退回来稳定版呀！！！！！好不容易都配置好了，测试版的老是掉线，还卡顿！

**Comment by kirbyzhu** [comment]
测试版跟稳定版基本一样 掉线的原因和版本无关 发自网易邮箱手机版 在2017年02月16日 00:57 ，wooyunwang写道： 妹的，自动升级到测试版了，能不能不删除插件的情况下，退回来稳定版呀！！！！！好不容易都配置好了，测试版的老是掉线，还卡顿！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jzp820927** [comment]
LS 正解，和版本无关，一般是 IP 的问题。

**Comment by wooowooo** [comment]
伤心～～我的楼【又】被歪了
