### ISSUE TITLE
退出蓝灯重新打开XX-net，就一直显示“请检查浏览器代理设置”

### ISSUE THREAD

**Issue by XSHC** [XX-net/XX-Net#5014]
我用蓝灯（lantern）开了代理之后退出蓝灯打开XX-net，就一直显示  请检查浏览器代理设置。
之前是好的。插件设置已经设置好，证书也替换了。
下面是诊断信息。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:111 good:44
network-status: OK
connected-link: new:6 used:0
worker: h1:14 h2:4
scan-ip-thread-num: 50
ip-quality: 759
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
想不出，XXNET 和蓝灯，有什么关联。唯一想到的就是蓝灯会修改系统代理设置。莫非是因为这个造成的？

**Comment by kirbyzhu** [comment]
应该是这样 和x-tunnel一个毛病 发自网易邮箱手机版 在2017年02月16日 14:52 ，天朝屁民写道： 想不出，XXNET 和蓝灯，有什么关联。唯一想到的就是蓝灯会修改系统代理设置。莫非是因为这个造成的？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jzp820927** [comment]
Linux 用户表示，不明觉厉。

**Comment by kirbyzhu** [comment]
用的是哪个发行版啊？

**Comment by jzp820927** [comment]
你是在问我？还说在问谁？

**Comment by XSHC** [comment]
蓝灯3.6.3   xxnet稳定版 @kirbyzhu

**Comment by XSHC** [comment]
我想说woc的是现在打开又莫名其妙好了，求解

**Comment by jzp820927** [comment]
好了就行了吧

**Comment by kirbyzhu** [comment]
问的是linux @jzp820927

**Comment by jzp820927** [comment]
我用的 ubuntu server 16.04

**Comment by kirbyzhu** [comment]
@jzp820927 是蛮好用的 最大的问题其实就是网银这些比较麻烦 还要装虚拟机什么的 我也想过换linux 安全又稳定

**Comment by jzp820927** [comment]
其实我的 XX 是运行在一台独立 PC 上的，平时还是用 win，ubuntu server 本来就是用于服务器的，桌面都没有。

**Comment by SeaHOH** [comment]
Linux 主要是一般软件服务提供者支持力度不够，基本上都要自己费心寻找编译，或者根本就没有。
@jzp820927 的用法挺适合普通 Win 用户，把 Linux 安装到 NAS、HP 服务器上（自组更便宜）随时可用，平时就用 Win。

**Comment by jzp820927** [comment]
是啊，我都是 putty 在 win 下面远程管理。XX 环境又干净，效率也高。不受 win 下面各种影响。而且我也不只有 XX，还有很多其他服务也是运行在 linux 下面的。
