### ISSUE TITLE
近期走xxnet代理后点击链接会弹出不同的广告页面？

### ISSUE THREAD

**Issue by chekafka** [XX-net/XX-Net#5018]
近期走xxnet代理后点击链接会弹出不同的广告页面，不用xxnet的时候没问题，用chrome的SwitchyOmega代理，IE全局或者PAC代理都有这种情况，杀毒WIN10自带defender软件。是我中毒了吗？谢谢

**Comment by kirbyzhu** [comment]
应该是的 从来没因为xxnet弹出过广告

**Comment by jzp820927** [comment]
没人反应过类似情况，应该是你系统的问题。
