### ISSUE TITLE
xxnet状态页默认使用ie打开

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#5032]
重装了一下chrome，然后打开xxnet的时候状态页就变成默认ie打开了，chrome是默认浏览器，怎么解决，

**Comment by jzp820927** [comment]
应该是默认浏览器没设置好吧

**Comment by kirbyzhu** [comment]
把chrome设置默认浏览器就行了 发自网易邮箱手机版 在2017年02月19日 21:33 ，Temmie-hOi写道： 重装了一下chrome，然后打开xxnet的时候状态页就变成默认ie打开了，怎么解决 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Temmie-hOi** [comment]
好了，似乎是360的锅

**Comment by jzp820927** [comment]
还是好装国软比较好
