### ISSUE TITLE
如何切换xx-net版本

### ISSUE THREAD

**Issue by 178620086** [XX-net/XX-Net#5036]
因为xx-net 3.29存在一定情况下无法访问google，所以想切换回老版本。

我观察到在xx-net的目录下有一个code文件夹里面包含了所有我升级过的版本。请问是不是通过修改某一个配置即可返回到指定版本。
是不是version.txt？或是把要切换的版本复制到default文件夹中？

**Comment by jzp820927** [comment]
应该是改 version.txt 可以试试

**Comment by 178620086** [comment]
XX-Net 3.2.8，一切正常，你可以访问真正的互联网了。
修改后可以访问google。（还在测试中）
确实是通过修改version.txt

**Comment by jzp820927** [comment]
不过老版可能会出验证码。
