### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by DuShuYuan** [XX-net/XX-Net#5044]
chrome和xxnet都重新安装的，没有ADM，一个扩展都没有呢

诊断：
`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:232 good:108
network-status: OK
connected-link: new:2 used:0
worker: h1:10 h2:0
scan-ip-thread-num: 50
ip-quality: 582
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

**Comment by DuShuYuan** [comment]
证书也安装了

**Comment by kirbyzhu** [comment]
如果使用了x-tunnel 那就ctrl F5 强制刷新一下

**Comment by kirbyzhu** [comment]
或者使用了其他代理切换工具

**Comment by jzp820927** [comment]
先试试代理能不能正常使用？

**Comment by SeaHOH** [comment]
信息太少！
代理设置正确没？
能上 http 么？
能上 https 么？
Ctrl + F5 试过没？

**Comment by DuShuYuan** [comment]
http能访问，https不行，提示  您的连接不是私密连接  ，但是证书已经安装了啊
状态信息：
浏览器代理设置	Fail
CA证书状态(下载)	Fail
Ctrl + F5 也试了，没用啊。。。。家里和公司的都这样了。。。

**Comment by kirbyzhu** [comment]
先把旧的证书删掉 然后再把xxnet的整个文件夹删掉 再重装试试

**Comment by jzp820927** [comment]
删除 data，删除导入浏览器的证书，重启XXNET，重新导入新证书到浏览器。

**Comment by kirbyzhu** [comment]
实在不行 删除证书后整个xx-net的文件夹都删掉 重来 全新的状态应该没有问题

**Comment by DuShuYuan** [comment]
已解决，配置好后等一段时间就能连了

**Comment by jzp820927** [comment]
想不到，你解决这个问题竟然用了快 2个月时间。
