### ISSUE TITLE
CentOS7 XX-Net.3.29已提示Everything is OK. Welcome to the FREE Internet.但是不能访问谷歌，也ping不通

### ISSUE THREAD

**Issue by LebrancBW** [XX-net/XX-Net#5052]
我是在腾讯云服务器上运行的XX-Net3.29，ping google.com 无响应。而且改动了CentOs的环境变量
vim /etc/profile

########################################################
# You could check uidgid reservation validity in
# /usr/share/doc/setup-*/uidgid `file`
if [ $UID -gt 199 ] && [ "`id -gn`" = "`id -un`" ]; then
    umask 002
else
    umask 022
fi

for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        if [ "${-#*i}" != "$-" ]; then
            . "$i"
        else
            . "$i" >/dev/null
        fi
    fi
done

unset i
unset -f pathmunge
export HISTTIMEFORMAT
export http_proxy="http://127.0.0.1:8087"
export https_proxy="http://127.0.0.1:8087"
####################################################

环境参数如下
XX-Net Status:
sys-platform: x86_64, Linux-3.10.0-327.36.3.el7.x86_64-x86_64-with-centos-7.2.1511-Core
os-system: Linux
os-version: #1 SMP Mon Oct 24 16:09:20 UTC 2016
os-release: 3.10.0-327.36.3.el7.x86_64
os-detail: Dist:CentOS Linux; Version:7.2.1511; ID:Core
architecture: 64bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.5
openssl-version: 0.13.1 TLSv1 h2:no

ipv6-status: 0
gws-ip-num: total:3000 good:2384
network-status: OK
connected-link: new:2 used:0
worker: h1:11 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

日志：
Feb 23 15:07:37.574 - [INFO] SSL use version:TLSv1
Feb 23 15:07:37.576 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
Feb 23 15:07:37.587 - [INFO] load ip range file:/home/XX-Net-3.2.9/code/default/gae_proxy/local/ip_range.txt
Feb 23 15:07:37.793 - [INFO] load google ip_list num:3000, gws num:3000
Feb 23 15:07:37.803 - [INFO] Adjust scan thread num from 100 to 0
Feb 23 15:07:37.840 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
Feb 23 15:07:37.852 - [DEBUG] get ip:110.93.194.161 t:100
Feb 23 15:07:37.864 - [DEBUG] network is ok, cost:427 ms
Feb 23 15:07:37.909 - [DEBUG] get ip:110.93.194.160 t:100
Feb 23 15:07:37.968 - [INFO] load manual.ini success
Feb 23 15:07:37.969 - [DEBUG] ## GAEProxy set keep_running: True
Feb 23 15:07:37.969 - [INFO] ------------------------------------------------------
Feb 23 15:07:37.969 - [INFO] Python Version : 2.7.5
Feb 23 15:07:37.977 - [INFO] OS : Dist:CentOS Linux; Version:7.2.1511; ID:Core
Feb 23 15:07:37.977 - [INFO] Listen Address : 0.0.0.0:8087
Feb 23 15:07:37.977 - [INFO] GAE APPID : bluewhite-yaoshan
Feb 23 15:07:37.977 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Feb 23 15:07:37.977 - [INFO] ------------------------------------------------------
Feb 23 15:07:38.114 - [INFO] system cert exist
Feb 23 15:07:38.410 - [DEBUG] get ip:203.233.96.50 t:100
Feb 23 15:07:38.912 - [DEBUG] get ip:41.201.164.162 t:100
Feb 23 15:07:39.066 - [DEBUG] create_ssl update ip:110.93.194.161 time:796 h2:0
Feb 23 15:07:39.066 - [DEBUG] get ip:41.201.164.161 t:100
Feb 23 15:07:39.149 - [DEBUG] create_ssl update ip:110.93.194.160 time:828 h2:0
Feb 23 15:07:39.181 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Feb 23 15:07:39.202 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=428201a4-8174-4201-b7c3-b3778fb46b54&version=3.2.9&platform=Linux-3.10.0-327.36.3.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Feb 23 15:07:39.413 - [DEBUG] get ip:212.113.52.241 t:100
Feb 23 15:07:39.676 - [DEBUG] create_ssl update ip:41.201.164.162 time:512 h2:0
Feb 23 15:07:39.857 - [INFO] DIRECT t:654 s:1674 200 xxnet-update.appspot.com /update.json?uuid=428201a4-8174-4201-b7c3-b3778fb46b54&version=3.2.9&platform=Linux-3.10.0-327.36.3.el7.x86_64-x86_64-with-centos-7.2.1511-Core
Feb 23 15:07:39.865 - [DEBUG] create_ssl update ip:41.201.164.161 time:535 h2:0
Feb 23 15:07:43.986 - [DEBUG] 203.233.96.50 fail:timeout('timed out',)
Feb 23 15:07:43.986 - [DEBUG] report_connect_fail:203.233.96.50
Feb 23 15:07:44.989 - [DEBUG] 212.113.52.241 fail:timeout('timed out',)
Feb 23 15:07:44.989 - [DEBUG] report_connect_fail:212.113.52.241
Feb 23 15:07:55.679 - [DEBUG] restore ip:203.233.96.50
Feb 23 15:08:00.683 - [DEBUG] ip:212.113.52.241 real fail
Feb 23 15:08:26.476 - [DEBUG] 110.93.194.161 close:host pool alive_timeout
Feb 23 15:08:26.476 - [DEBUG] ssl_closed 110.93.194.161
Feb 23 15:08:31.494 - [DEBUG] get ip:84.208.42.249 t:100
Feb 23 15:08:35.495 - [DEBUG] 84.208.42.249 fail:timeout('timed out',)
Feb 23 15:08:35.495 - [DEBUG] report_connect_fail:84.208.42.249
Feb 23 15:08:35.495 - [DEBUG] get ip:212.113.52.242 t:100
Feb 23 15:08:36.295 - [DEBUG] create_ssl update ip:212.113.52.242 time:519 h2:0
Feb 23 15:08:36.296 - [DEBUG] get ip:95.180.157.29 t:100
Feb 23 15:08:37.323 - [DEBUG] create_ssl update ip:95.180.157.29 time:686 h2:0
Feb 23 15:08:50.502 - [DEBUG] ip:84.208.42.249 real fail
Feb 23 15:09:27.374 - [DEBUG] get ip:112.72.5.110 t:100
Feb 23 15:09:28.229 - [DEBUG] create_ssl update ip:112.72.5.110 time:557 h2:0
Feb 23 15:09:28.230 - [DEBUG] get ip:103.43.149.175 t:100
Feb 23 15:09:29.854 - [DEBUG] create_ssl update ip:103.43.149.175 time:1175 h2:0
Feb 23 15:10:14.168 - [DEBUG] 41.201.164.161 keep alive fail, inactive_time:154 head_timeout:100
Feb 23 15:10:14.168 - [DEBUG] report_connect_fail:41.201.164.161
Feb 23 15:10:19.174 - [DEBUG] 41.201.164.161 worker close:keep alive
Feb 23 15:10:19.694 - [DEBUG] GAEProxy Web_control 223.129.16.179:61816 GET /deploy?cmd=get_log
Feb 23 15:10:19.898 - [DEBUG] get ip:77.88.221.204 t:100
Feb 23 15:10:20.507 - [DEBUG] GAEProxy web_control 223.129.16.179:61816 POST /config?cmd=get_config
Feb 23 15:10:20.513 - [DEBUG] GAEProxy Web_control 223.129.16.179:61814 GET /scan_ip?cmd=get_range
Feb 23 15:10:20.513 - [INFO] load ip range file:/home/XX-Net-3.2.9/code/default/gae_proxy/local/ip_range.txt
Feb 23 15:10:20.683 - [DEBUG] create_ssl update ip:77.88.221.204 time:515 h2:0
Feb 23 15:10:20.683 - [DEBUG] get ip:195.80.179.156 t:100
Feb 23 15:10:21.459 - [DEBUG] GAEProxy Web_control 223.129.16.179:61816 GET /scan_ip?cmd=get_scan_ip_log
Feb 23 15:10:21.577 - [DEBUG] create_ssl update ip:195.80.179.156 time:597 h2:0
Feb 23 15:10:22.499 - [DEBUG] GAEProxy Web_control 223.129.16.179:62195 GET /check_ip?cmd=get_process
Feb 23 15:10:23.498 - [DEBUG] GAEProxy Web_control 223.129.16.179:62195 GET /check_ip?cmd=get_process
Feb 23 15:10:24.500 - [DEBUG] GAEProxy Web_control 223.129.16.179:62195 GET /check_ip?cmd=get_process
Feb 23 15:10:25.501 - [DEBUG] GAEProxy Web_control 223.129.16.179:62195 GET /check_ip?cmd=get_process
Feb 23 15:10:26.502 - [DEBUG] GAEProxy Web_control 223.129.16.179:61816 GET /check_ip?cmd=get_process
Feb 23 15:10:28.070 - [DEBUG] GAEProxy web_control 223.129.16.179:61816 POST /config?cmd=get_config
Feb 23 15:10:29.170 - [DEBUG] ip:41.201.164.161 real fail
Feb 23 15:11:11.632 - [DEBUG] get ip:195.80.179.157 t:100
Feb 23 15:11:15.636 - [DEBUG] 195.80.179.157 fail:timeout('timed out',)
Feb 23 15:11:15.637 - [DEBUG] report_connect_fail:195.80.179.157
Feb 23 15:11:15.637 - [DEBUG] get ip:45.121.219.12 t:100
Feb 23 15:11:16.269 - [DEBUG] create_ssl update ip:45.121.219.12 time:414 h2:0
Feb 23 15:11:16.270 - [DEBUG] get ip:195.80.179.153 t:100
Feb 23 15:11:17.169 - [DEBUG] create_ssl update ip:195.80.179.153 time:601 h2:0
Feb 23 15:11:30.647 - [DEBUG] ip:195.80.179.157 real fail
Feb 23 15:11:42.744 - [DEBUG] GAEProxy web_control 223.129.16.179:61816 POST /config?cmd=get_config
Feb 23 15:11:44.387 - [DEBUG] GAEProxy web_control 223.129.16.179:61816 POST /config?cmd=get_config
Feb 23 15:11:44.390 - [DEBUG] GAEProxy Web_control 223.129.16.179:62195 GET /scan_ip?cmd=get_range
Feb 23 15:11:44.390 - [INFO] load ip range file:/home/XX-Net-3.2.9/code/default/gae_proxy/local/ip_range.txt
Feb 23 15:11:49.178 - [DEBUG] GAEProxy Web_control 223.129.16.179:61816 GET /deploy?cmd=get_log
Feb 23 15:12:02.476 - [DEBUG] 112.72.5.110 keep alive fail, inactive_time:154 head_timeout:100
Feb 23 15:12:02.477 - [DEBUG] report_connect_fail:112.72.5.110
Feb 23 15:12:03.328 - [DEBUG] 103.43.149.175 keep alive fail, inactive_time:153 head_timeout:100
Feb 23 15:12:03.328 - [DEBUG] report_connect_fail:103.43.149.175
Feb 23 15:12:07.219 - [DEBUG] get ip:77.88.221.208 t:100
Feb 23 15:12:07.486 - [DEBUG] 112.72.5.110 worker close:keep alive
Feb 23 15:12:08.332 - [DEBUG] 103.43.149.175 worker close:keep alive
Feb 23 15:12:08.513 - [DEBUG] create_ssl update ip:77.88.221.208 time:1039 h2:0
Feb 23 15:12:08.513 - [DEBUG] get ip:77.88.221.209 t:100
Feb 23 15:12:12.517 - [DEBUG] 77.88.221.209 fail:timeout('timed out',)
Feb 23 15:12:12.517 - [DEBUG] report_connect_fail:77.88.221.209
Feb 23 15:12:12.518 - [DEBUG] get ip:201.157.30.53 t:100
Feb 23 15:12:14.957 - [DEBUG] create_ssl update ip:201.157.30.53 time:2182 h2:0
Feb 23 15:12:19.692 - [DEBUG] restore ip:112.72.5.110
Feb 23 15:12:24.698 - [DEBUG] ip:103.43.149.175 real fail
Feb 23 15:12:29.703 - [DEBUG] ip:77.88.221.209 real fail
Feb 23 15:13:00.007 - [DEBUG] get ip:64.15.125.15 t:100
Feb 23 15:13:04.011 - [DEBUG] 64.15.125.15 fail:timeout('timed out',)
Feb 23 15:13:04.011 - [DEBUG] report_connect_fail:64.15.125.15
Feb 23 15:13:04.012 - [DEBUG] get ip:66.96.224.89 t:100
Feb 23 15:13:08.016 - [DEBUG] 66.96.224.89 fail:timeout('timed out',)
Feb 23 15:13:08.016 - [DEBUG] report_connect_fail:66.96.224.89
Feb 23 15:13:08.016 - [DEBUG] get ip:66.96.224.88 t:100
Feb 23 15:13:12.021 - [DEBUG] 66.96.224.88 fail:timeout('timed out',)
Feb 23 15:13:12.021 - [DEBUG] report_connect_fail:66.96.224.88
Feb 23 15:13:12.030 - [DEBUG] get ip:113.171.242.167 t:100
Feb 23 15:13:16.034 - [DEBUG] 113.171.242.167 fail:timeout('timed out',)
Feb 23 15:13:16.034 - [DEBUG] report_connect_fail:113.171.242.167
Feb 23 15:13:16.035 - [DEBUG] get ip:216.58.205.126 t:100
Feb 23 15:13:19.022 - [DEBUG] ip:64.15.125.15 real fail
Feb 23 15:13:20.039 - [DEBUG] 216.58.205.126 fail:timeout('timed out',)
Feb 23 15:13:20.039 - [DEBUG] report_connect_fail:216.58.205.126
Feb 23 15:13:20.039 - [DEBUG] get ip:65.199.248.62 t:100
Feb 23 15:13:24.028 - [DEBUG] ip:66.96.224.89 real fail
Feb 23 15:13:24.043 - [DEBUG] 65.199.248.62 fail:timeout('timed out',)
Feb 23 15:13:24.044 - [DEBUG] report_connect_fail:65.199.248.62
Feb 23 15:13:24.052 - [DEBUG] get ip:61.238.239.177 t:100
Feb 23 15:13:28.057 - [DEBUG] 61.238.239.177 fail:timeout('timed out',)
Feb 23 15:13:28.057 - [DEBUG] report_connect_fail:61.238.239.177
Feb 23 15:13:28.057 - [DEBUG] get ip:200.28.6.206 t:100
Feb 23 15:13:29.033 - [DEBUG] ip:66.96.224.88 real fail
Feb 23 15:13:29.205 - [DEBUG] create_ssl update ip:200.28.6.206 time:754 h2:0
Feb 23 15:13:29.206 - [DEBUG] get ip:200.28.6.207 t:100
Feb 23 15:13:33.208 - [DEBUG] 200.28.6.207 fail:timeout('timed out',)
Feb 23 15:13:33.208 - [DEBUG] report_connect_fail:200.28.6.207
Feb 23 15:13:33.209 - [DEBUG] get ip:194.182.232.122 t:100
Feb 23 15:13:33.836 - [DEBUG] create_ssl update ip:194.182.232.122 time:419 h2:0
Feb 23 15:13:34.039 - [DEBUG] ip:113.171.242.167 real fail
Feb 23 15:13:39.044 - [DEBUG] ip:216.58.205.126 real fail
Feb 23 15:13:44.050 - [DEBUG] ip:65.199.248.62 real fail
Feb 23 15:13:49.053 - [DEBUG] ip:61.238.239.177 real fail
Feb 23 15:13:50.834 - [DEBUG] 195.80.179.156 keep alive fail, inactive_time:209 head_timeout:100
Feb 23 15:13:50.834 - [DEBUG] report_connect_fail:195.80.179.156
Feb 23 15:13:51.368 - [DEBUG] 195.80.179.153 keep alive fail, inactive_time:154 head_timeout:100
Feb 23 15:13:51.369 - [DEBUG] report_connect_fail:195.80.179.153
Feb 23 15:13:54.058 - [DEBUG] ip:200.28.6.207 real fail
Feb 23 15:13:55.839 - [DEBUG] 195.80.179.156 worker close:keep alive
Feb 23 15:13:56.374 - [DEBUG] 195.80.179.153 worker close:keep alive
Feb 23 15:14:05.839 - [DEBUG] ip:195.80.179.156 real fail
Feb 23 15:14:10.844 - [DEBUG] ip:195.80.179.153 real fail
Feb 23 15:14:18.881 - [DEBUG] get ip:194.182.232.120 t:100
Feb 23 15:14:22.885 - [DEBUG] 194.182.232.120 fail:timeout('timed out',)
Feb 23 15:14:22.885 - [DEBUG] report_connect_fail:194.182.232.120
Feb 23 15:14:22.885 - [DEBUG] get ip:194.182.232.121 t:100
Feb 23 15:14:26.889 - [DEBUG] 194.182.232.121 fail:timeout('timed out',)
Feb 23 15:14:26.890 - [DEBUG] report_connect_fail:194.182.232.121
Feb 23 15:14:26.890 - [DEBUG] get ip:187.19.145.113 t:100
Feb 23 15:14:30.893 - [DEBUG] 187.19.145.113 fail:timeout('timed out',)
Feb 23 15:14:30.893 - [DEBUG] report_connect_fail:187.19.145.113
Feb 23 15:14:30.901 - [DEBUG] get ip:187.19.145.110 t:100
Feb 23 15:14:32.351 - [DEBUG] create_ssl update ip:187.19.145.110 time:961 h2:0
Feb 23 15:14:32.351 - [DEBUG] get ip:187.19.145.111 t:100
Feb 23 15:14:33.606 - [DEBUG] create_ssl update ip:187.19.145.111 time:836 h2:0
Feb 23 15:14:41.124 - [DEBUG] ip:194.182.232.120 real fail
Feb 23 15:14:46.129 - [DEBUG] ip:194.182.232.121 real fail
Feb 23 15:14:50.792 - [DEBUG] 212.113.52.242 keep alive fail, inactive_time:374 head_timeout:100
Feb 23 15:14:50.793 - [DEBUG] report_connect_fail:212.113.52.242
Feb 23 15:14:51.134 - [DEBUG] ip:187.19.145.113 real fail
Feb 23 15:14:55.797 - [DEBUG] 212.113.52.242 worker close:keep alive
Feb 23 15:15:05.808 - [DEBUG] ip:212.113.52.242 real fail
Feb 23 15:15:23.651 - [DEBUG] get ip:187.19.145.116 t:100
Feb 23 15:15:27.656 - [DEBUG] 187.19.145.116 fail:timeout('timed out',)
Feb 23 15:15:27.656 - [DEBUG] report_connect_fail:187.19.145.116
Feb 23 15:15:27.657 - [DEBUG] get ip:187.19.145.117 t:100
Feb 23 15:15:31.661 - [DEBUG] 187.19.145.117 fail:timeout('timed out',)
Feb 23 15:15:31.661 - [DEBUG] report_connect_fail:187.19.145.117
Feb 23 15:15:31.661 - [DEBUG] get ip:187.19.145.114 t:100
Feb 23 15:15:35.662 - [DEBUG] 187.19.145.114 fail:timeout('timed out',)
Feb 23 15:15:35.662 - [DEBUG] report_connect_fail:187.19.145.114
Feb 23 15:15:35.669 - [DEBUG] get ip:187.19.145.115 t:100
Feb 23 15:15:39.673 - [DEBUG] 187.19.145.115 fail:timeout('timed out',)
Feb 23 15:15:39.673 - [DEBUG] report_connect_fail:187.19.145.115
Feb 23 15:15:39.674 - [DEBUG] get ip:217.75.205.222 t:100
Feb 23 15:15:42.672 - [DEBUG] ip:187.19.145.116 real fail
Feb 23 15:15:43.678 - [DEBUG] 217.75.205.222 fail:timeout('timed out',)
Feb 23 15:15:43.678 - [DEBUG] report_connect_fail:217.75.205.222
Feb 23 15:15:43.678 - [DEBUG] get ip:200.124.254.228 t:100
Feb 23 15:15:47.677 - [DEBUG] ip:187.19.145.117 real fail
Feb 23 15:15:47.681 - [DEBUG] 200.124.254.228 fail:timeout('timed out',)
Feb 23 15:15:47.681 - [DEBUG] report_connect_fail:200.124.254.228
Feb 23 15:15:47.688 - [DEBUG] get ip:200.124.254.221 t:100
Feb 23 15:15:48.776 - [DEBUG] create_ssl update ip:200.124.254.221 time:764 h2:0
Feb 23 15:15:48.777 - [DEBUG] get ip:200.124.254.220 t:100
Feb 23 15:15:49.685 - [DEBUG] create_ssl update ip:200.124.254.220 time:607 h2:0
Feb 23 15:15:52.683 - [DEBUG] ip:187.19.145.114 real fail
Feb 23 15:15:57.688 - [DEBUG] ip:187.19.145.115 real fail
Feb 23 15:15:58.619 - [DEBUG] GAEProxy web_control 223.129.16.179:61816 POST /config?cmd=get_config
Feb 23 15:16:02.694 - [DEBUG] ip:217.75.205.222 real fail
Feb 23 15:16:03.158 - [DEBUG] 200.28.6.206 keep alive fail, inactive_time:153 head_timeout:100
Feb 23 15:16:03.158 - [DEBUG] report_connect_fail:200.28.6.206
Feb 23 15:16:07.699 - [DEBUG] ip:200.124.254.228 real fail
Feb 23 15:16:08.161 - [DEBUG] 200.28.6.206 worker close:keep alive
Feb 23 15:16:18.169 - [DEBUG] ip:200.28.6.206 real fail
Feb 23 15:16:39.735 - [DEBUG] get ip:200.124.254.223 t:100
Feb 23 15:16:40.822 - [DEBUG] create_ssl update ip:200.124.254.223 time:717 h2:0
Feb 23 15:16:40.823 - [DEBUG] get ip:80.64.175.142 t:100
Feb 23 15:16:44.823 - [DEBUG] 80.64.175.142 fail:timeout('timed out',)
Feb 23 15:16:44.824 - [DEBUG] report_connect_fail:80.64.175.142
Feb 23 15:16:44.824 - [DEBUG] get ip:196.203.102.205 t:100
Feb 23 15:16:46.593 - [DEBUG] create_ssl update ip:196.203.102.205 time:1354 h2:0
Feb 23 15:16:59.834 - [DEBUG] ip:80.64.175.142 real fail
Feb 23 15:17:06.000 - [DEBUG] 187.19.145.110 keep alive fail, inactive_time:153 head_timeout:100
Feb 23 15:17:06.000 - [DEBUG] report_connect_fail:187.19.145.110
Feb 23 15:17:08.717 - [DEBUG] recheck_ip:187.19.145.110 restore okl
Feb 23 15:17:08.718 - [DEBUG] 187.19.145.110 worker close:keep alive
Feb 23 15:17:17.723 - [DEBUG] restore ip:187.19.145.110
Feb 23 15:17:31.651 - [DEBUG] get ip:196.203.102.204 t:100
Feb 23 15:17:32.837 - [DEBUG] create_ssl update ip:196.203.102.204 time:783 h2:0
Feb 23 15:17:37.843 - [DEBUG] get ip:200.124.254.227 t:100
Feb 23 15:17:39.620 - [INFO] PAC from:127.0.0.1:46954 GET /proxy.pac
Feb 23 15:17:41.848 - [DEBUG] 200.124.254.227 fail:timeout('timed out',)
Feb 23 15:17:41.848 - [DEBUG] report_connect_fail:200.124.254.227
Feb 23 15:17:41.861 - [DEBUG] get ip:196.203.102.206 t:100
Feb 23 15:17:43.372 - [DEBUG] ssl_closed 110.93.194.160
Feb 23 15:17:43.372 - [DEBUG] 110.93.194.160 worker close:idle timeout
Feb 23 15:17:43.860 - [DEBUG] create_ssl update ip:196.203.102.206 time:1584 h2:0
Feb 23 15:17:44.385 - [DEBUG] ssl_closed 41.201.164.162
Feb 23 15:17:44.385 - [DEBUG] 41.201.164.162 worker close:idle timeout
Feb 23 15:17:53.181 - [DEBUG] restore ip:200.124.254.227
Feb 23 15:18:02.498 - [DEBUG] 187.19.145.111 keep alive fail, inactive_time:208 head_timeout:100
Feb 23 15:18:02.498 - [DEBUG] report_connect_fail:187.19.145.111
Feb 23 15:18:04.899 - [DEBUG] recheck_ip:187.19.145.111 restore okl
Feb 23 15:18:04.900 - [DEBUG] 187.19.145.111 worker close:keep alive
Feb 23 15:18:14.149 - [DEBUG] restore ip:187.19.145.111
Feb 23 15:18:23.900 - [DEBUG] get ip:212.113.52.209 t:100
Feb 23 15:18:25.468 - [DEBUG] create_ssl update ip:212.113.52.209 time:1309 h2:0
Feb 23 15:18:35.491 - [DEBUG] get ip:212.113.52.208 t:100
Feb 23 15:18:36.275 - [DEBUG] create_ssl update ip:212.113.52.208 time:510 h2:0
Feb 23 15:18:41.768 - [DEBUG] ssl_closed 95.180.157.29
Feb 23 15:18:41.768 - [DEBUG] 95.180.157.29 worker close:idle timeout
Feb 23 15:18:53.415 - [DEBUG] 194.182.232.122 keep alive fail, inactive_time:319 head_timeout:100
Feb 23 15:18:53.415 - [DEBUG] report_connect_fail:194.182.232.122
Feb 23 15:18:54.950 - [DEBUG] recheck_ip:194.182.232.122 restore okl
Feb 23 15:18:54.950 - [DEBUG] 194.182.232.122 worker close:keep alive
Feb 23 15:19:04.788 - [DEBUG] restore ip:194.182.232.122
Feb 23 15:19:14.841 - [DEBUG] 200.124.254.223 keep alive fail, inactive_time:154 head_timeout:100
Feb 23 15:19:14.841 - [DEBUG] report_connect_fail:200.124.254.223
Feb 23 15:19:16.235 - [DEBUG] recheck_ip:200.124.254.223 restore okl
Feb 23 15:19:16.235 - [DEBUG] 200.124.254.223 worker close:keep alive
Feb 23 15:19:16.319 - [DEBUG] get ip:212.113.52.205 t:100
Feb 23 15:19:20.323 - [DEBUG] 212.113.52.205 fail:timeout('timed out',)
Feb 23 15:19:20.323 - [DEBUG] report_connect_fail:212.113.52.205
Feb 23 15:19:20.324 - [DEBUG] get ip:212.113.52.204 t:100
Feb 23 15:19:24.325 - [DEBUG] 212.113.52.204 fail:timeout('timed out',)
Feb 23 15:19:24.325 - [DEBUG] report_connect_fail:212.113.52.204
Feb 23 15:19:24.326 - [DEBUG] get ip:212.113.52.206 t:100
Feb 23 15:19:25.703 - [DEBUG] create_ssl update ip:212.113.52.206 time:1098 h2:0
Feb 23 15:19:25.704 - [DEBUG] get ip:111.84.224.155 t:100
Feb 23 15:19:26.168 - [DEBUG] restore ip:200.124.254.223
Feb 23 15:19:27.578 - [DEBUG] create_ssl update ip:111.84.224.155 time:805 h2:0
Feb 23 15:19:35.331 - [DEBUG] ip:212.113.52.205 real fail
Feb 23 15:19:40.332 - [DEBUG] ip:212.113.52.204 real fail
Feb 23 15:20:06.749 - [DEBUG] 196.203.102.204 keep alive fail, inactive_time:153 head_timeout:100
Feb 23 15:20:06.750 - [DEBUG] report_connect_fail:196.203.102.204
Feb 23 15:20:11.755 - [DEBUG] 196.203.102.204 worker close:keep alive
Feb 23 15:20:17.628 - [DEBUG] get ip:59.18.45.250 t:100
Feb 23 15:20:21.632 - [DEBUG] 59.18.45.250 fail:timeout('timed out',)
Feb 23 15:20:21.633 - [DEBUG] report_connect_fail:59.18.45.250
Feb 23 15:20:21.633 - [DEBUG] get ip:49.106.234.147 t:100
Feb 23 15:20:22.150 - [DEBUG] ip:196.203.102.204 real fail
Feb 23 15:20:25.354 - [DEBUG] ssl_closed 77.88.221.204
Feb 23 15:20:25.354 - [DEBUG] 77.88.221.204 worker close:idle timeout
Feb 23 15:20:25.637 - [DEBUG] 49.106.234.147 fail:timeout('timed out',)
Feb 23 15:20:25.637 - [DEBUG] report_connect_fail:49.106.234.147
Feb 23 15:20:25.637 - [DEBUG] get ip:201.57.54.214 t:100
Feb 23 15:20:26.844 - [DEBUG] create_ssl update ip:201.57.54.214 time:796 h2:0
Feb 23 15:20:26.844 - [DEBUG] get ip:201.57.54.212 t:100
Feb 23 15:20:27.915 - [DEBUG] create_ssl update ip:201.57.54.212 time:717 h2:0

**Comment by jzp820927** [comment]
好了麽?

**Comment by LebrancBW** [comment]
已经搞定了。@jzp820927
