### ISSUE TITLE
最近无法看youtube视频，网页正常，报错Method CONNECT not support in GAEProxy for redirector.googlevideo.com

### ISSUE THREAD

**Issue by wenshanliren** [XX-net/XX-Net#5053]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:44
network-status: OK
connected-link: new:11 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 536
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Feb 23 21:56:11.442 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1751) path:redirector.googlevideo.com:443, errno:1

Feb 23 21:56:11.442 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Tools\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 314, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\ssl.py", line 734, in recv return self.read(buflen) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\ssl.py", line 621, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1751)

Feb 23 21:56:11.952 - [DEBUG] ip:92.226.2.88 real fail

Feb 23 21:56:13.536 - [DEBUG] restore ip:189.199.103.56

Feb 23 21:56:14.334 - [DEBUG] restore ip:110.164.8.204

Feb 23 21:56:15.366 - [DEBUG] restore ip:118.143.88.150

Feb 23 21:56:15.745 - [WARNING] Method CONNECT not support in GAEProxy for redirector.googlevideo.com:443

Feb 23 21:56:15.759 - [INFO] GAE CONNECT s.youtube.com:443

Feb 23 21:56:15.792 - [DEBUG] GAE CONNECT Direct CONNECT s.youtube.com:443

Feb 23 21:56:15.910 - [INFO] scan_ip add ip:198.70.70.238 time:901

Feb 23 21:56:15.920 - [INFO] remove_slowest_ip:216.254.140.208 handshake_time:1661, fails:1

Feb 23 21:56:16.163 - [WARNING] IP:118.69.249.219 host:s.youtube.com not support GAE, server type: status:404

Feb 23 21:56:16.163 - [DEBUG] report_connect_fail:118.69.249.219

Feb 23 21:56:20.368 - [DEBUG] ip:202.224.62.44 real fail

Feb 23 21:56:21.804 - [WARNING] Method CONNECT not support in GAEProxy for redirector.googlevideo.com:443

Feb 23 21:56:22.407 - [WARNING] Method CONNECT not support in GAEProxy for redirector.googlevideo.com:443

Feb 23 21:56:25.210 - [WARNING] Method CONNECT not support in GAEProxy for redirector.googlevideo.com:443

**Comment by jzp820927** [comment]
Feb 23 21:56:11.442 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1751) path:redirector.googlevideo.com:443, errno:1

**Comment by wenshanliren** [comment]
重新生成证书还是不行，访问twitter和facebook没有问题的，就是视频不能播放

**Comment by SeaHOH** [comment]
切换 U2B 登录状态试试。

**Comment by wenshanliren** [comment]
感谢大家，可以了，删掉了data文件夹重新生成，重新部署了服务器端，重新导入了证书（貌似前面导入的是goagent的证书）

**Comment by jzp820927** [comment]
服务端不用反复部署，弄一次就行了
