### ISSUE TITLE
教育网环境下ipv6不可用

### ISSUE THREAD

**Issue by Severn-Vergil** [XX-net/XX-Net#5062]
## 问题内容
假期后接回教育网，从配置处打开ipv6，结果失败。新年假期前可用，除配置“使用ipv6”开关关闭过，其他环境均没有改动过。感谢提供可能的解决方式！

## 诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1716
network-status: OK
connected-link: new:2 used:0
worker: h1:21 h2:9
scan-ip-thread-num: 50
ip-quality: 390
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
可以试试在 manual.ini 文件里面设置 IPV6 开关

**Comment by Severn-Vergil** [comment]
感谢指教，我的版本是3.2.9，没有发现有manual.ini这个文件？是在XX-Net-3.2.9\data\gae_proxy目录下吗？

**Comment by Severn-Vergil** [comment]
配置use_ipv6 = 1，gae_proxy日志出现大片的report_connect_fail network fail和create_ssl [IP地址] fail:timed out，看着像扫描不出来好的ip；但我自己找的hosts不用xx-net，是可以ipv6访问google的

**Comment by BreakShadow0504** [comment]
如果没错的话，我记得一些GAE V6 IP也在教育网被封了。单纯的无法访问。

**Comment by Severn-Vergil** [comment]
好的，感谢指点！另寻他法吧

**Comment by jzp820927** [comment]
IPV6 应该是可以用的。应该是其他问题。可以发日志出来看看

**Comment by Severn-Vergil** [comment]
感谢楼上的指点，找一哥们要了一份good_ipv6.txt，又复活了

**Comment by jzp820927** [comment]
看来是内置的 IP 被封了

**Comment by shakesnake** [comment]
@Severn-Vergil 能把那份能用的ipv6分享到这里么
