### ISSUE TITLE
xx-net 用不了IPV6功能

### ISSUE THREAD

**Issue by klyxtxz** [XX-net/XX-Net#5068]
我尝试了多个版本  除了3.3.0能够开启IPV6以外 3.2.9及其之前的版本都 显示 请 确认你的网络支持IPV6  日志中 是 ' IPv6 was enabled, but check failed.“    
3.3.0在开启IPV6后 则 都是 TIME OUT creat ssl faild   report connection faild

**Comment by klyxtxz** [comment]
Feb 26 22:31:00.418 - [INFO] SSL use version:TLSv1_2 
Feb 26 22:31:00.808 - [INFO] OpenSSL support alpn 
Feb 26 22:31:00.808 - [INFO] load ip range file:C:\Users\\Desktop\XX-Net-3.3.0\code\default\gae_proxy\local\ip_range.txt 
Feb 26 22:31:00.824 - [INFO] detected Win10, enable connect concurrency control, interval:40 
Feb 26 22:31:00.902 - [INFO] load google ip_list num:12549, gws num:12549 
Feb 26 22:31:00.918 - [INFO] OpenSSL support alpn 
Feb 26 22:31:00.918 - [DEBUG] get ip:2a00:1450:4009:6::6 t:300 
Feb 26 22:31:00.934 - [DEBUG] get ip:2a00:1450:4002:d::9 t:300 
Feb 26 22:31:00.934 - [DEBUG] ## GAEProxy set keep_running: True 
Feb 26 22:31:00.934 - [INFO] ------------------------------------------------------ 
Feb 26 22:31:00.934 - [INFO] Python Version : 2.7.11 
Feb 26 22:31:00.934 - [INFO] OS : Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0 
Feb 26 22:31:00.934 - [INFO] Listen Address : 127.0.0.1:8087 
Feb 26 22:31:00.934 - [INFO] GAE APPID : 
Feb 26 22:31:00.934 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac 
Feb 26 22:31:00.934 - [INFO] ------------------------------------------------------ 
Feb 26 22:31:01.438 - [DEBUG] get ip:2404:6800:4005:1c::a t:300 
Feb 26 22:31:01.943 - [DEBUG] get ip:2a00:1450:4001:9::8 t:300 
Feb 26 22:31:02.099 - [INFO] PAC from:127.0.0.1:57905 GET /proxy.pac 
Feb 26 22:31:02.099 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('C:\\Users\\\xcd\xf5\xbf\xa1\\Desktop\\XX-Net-3.3.0\\data\\gae_proxy\\proxy.pac') 
Feb 26 22:31:02.115 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt 
Feb 26 22:31:02.255 - [INFO] GAE CONNECT xxnet-update.appspot.com:443 
Feb 26 22:31:02.271 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=c6610fbc-1643-4795-8ecf-7d25bccb4d70&version=3.3.0&platform=Windows-10-10.0.14393 
Feb 26 22:31:02.459 - [DEBUG] get ip:2a00:1450:4007:10::15 t:300 
Feb 26 22:31:02.974 - [DEBUG] get ip:2a00:1450:4007:10::14 t:300 
Feb 26 22:31:03.490 - [DEBUG] get ip:2a00:1450:4001:2e::19 t:300 
Feb 26 22:31:04.006 - [DEBUG] get ip:2a00:1450:4001:2e::18 t:300 
Feb 26 22:31:04.522 - [DEBUG] get ip:2a00:1450:400c:401::14 t:300 
Feb 26 22:31:04.944 - [DEBUG] 2a00:1450:4009:6::6 fail:timeout('timed out',) 
Feb 26 22:31:04.944 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:04.944 - [DEBUG] get ip:2a00:1450:400c:401::15 t:300 
Feb 26 22:31:04.975 - [DEBUG] 2a00:1450:4002:d::9 fail:timeout('timed out',) 
Feb 26 22:31:04.975 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:04.975 - [DEBUG] get ip:2a00:1450:400c:401::12 t:300 
Feb 26 22:31:05.037 - [DEBUG] get ip:2a00:1450:400c:401::13 t:300 
Feb 26 22:31:05.444 - [DEBUG] 2404:6800:4005:1c::a fail:timeout('timed out',) 
Feb 26 22:31:05.444 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:05.444 - [DEBUG] get ip:2a00:1450:400c:401::10 t:300 
Feb 26 22:31:05.553 - [DEBUG] get ip:2a00:1450:400c:401::11 t:300 
Feb 26 22:31:05.943 - [DEBUG] 2a00:1450:4001:9::8 fail:timeout('timed out',) 
Feb 26 22:31:05.943 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:05.943 - [DEBUG] get ip:2a00:1450:4001:2e::11 t:300 
Feb 26 22:31:06.069 - [DEBUG] get ip:2a00:1450:4001:2e::10 t:300 
Feb 26 22:31:06.459 - [DEBUG] 2a00:1450:4007:10::15 fail:timeout('timed out',) 
Feb 26 22:31:06.459 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:06.459 - [DEBUG] get ip:2a00:1450:4001:2e::13 t:300 
Feb 26 22:31:06.584 - [DEBUG] get ip:2a00:1450:4001:2e::12 t:300 
Feb 26 22:31:06.975 - [DEBUG] 2a00:1450:4007:10::14 fail:timeout('timed out',) 
Feb 26 22:31:06.975 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:06.975 - [DEBUG] get ip:2a00:1450:4001:2e::15 t:300 
Feb 26 22:31:07.100 - [DEBUG] get ip:2a00:1450:4009:6::6 t:300 
Feb 26 22:31:07.491 - [DEBUG] 2a00:1450:4001:2e::19 fail:timeout('timed out',) 
Feb 26 22:31:07.491 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:07.491 - [DEBUG] get ip:2a00:1450:4002:d::9 t:300 
Feb 26 22:31:07.615 - [DEBUG] get ip:2404:6800:4005:1c::a t:300 
Feb 26 22:31:08.006 - [DEBUG] 2a00:1450:4001:2e::18 fail:timeout('timed out',) 
Feb 26 22:31:08.006 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:08.006 - [DEBUG] get ip:2a00:1450:4001:9::8 t:300 
Feb 26 22:31:08.131 - [DEBUG] get ip:2a00:1450:4007:10::15 t:300 
Feb 26 22:31:08.522 - [DEBUG] 2a00:1450:400c:401::14 fail:timeout('timed out',) 
Feb 26 22:31:08.522 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:08.522 - [DEBUG] get ip:2a00:1450:4007:10::14 t:300 
Feb 26 22:31:08.647 - [DEBUG] get ip:2a00:1450:4001:2e::19 t:300 
Feb 26 22:31:08.944 - [DEBUG] 2a00:1450:400c:401::15 fail:timeout('timed out',) 
Feb 26 22:31:08.944 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:08.944 - [DEBUG] get ip:2a00:1450:4001:2e::14 t:300 
Feb 26 22:31:08.991 - [DEBUG] 2a00:1450:400c:401::12 fail:timeout('timed out',) 
Feb 26 22:31:08.991 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:08.991 - [DEBUG] get ip:2a00:1450:4001:2e::17 t:300 
Feb 26 22:31:09.038 - [DEBUG] 2a00:1450:400c:401::13 fail:timeout('timed out',) 
Feb 26 22:31:09.038 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:09.038 - [DEBUG] get ip:2a00:1450:4001:2e::16 t:300 
Feb 26 22:31:09.163 - [DEBUG] get ip:2a00:1450:4001:33::10 t:300 
Feb 26 22:31:09.444 - [DEBUG] 2a00:1450:400c:401::10 fail:timeout('timed out',) 
Feb 26 22:31:09.444 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:09.444 - [DEBUG] get ip:2a00:1450:4001:33::11 t:300 
Feb 26 22:31:09.553 - [DEBUG] 2a00:1450:400c:401::11 fail:timeout('timed out',) 
Feb 26 22:31:09.553 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:09.553 - [DEBUG] get ip:2a00:1450:4001:33::12 t:300 
Feb 26 22:31:09.679 - [DEBUG] get ip:2a00:1450:4001:33::13 t:300 
Feb 26 22:31:09.944 - [DEBUG] 2a00:1450:4001:2e::11 fail:timeout('timed out',) 
Feb 26 22:31:09.944 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:09.944 - [DEBUG] get ip:2a00:1450:4001:33::14 t:300 
Feb 26 22:31:10.072 - [DEBUG] 2a00:1450:4001:2e::10 fail:timeout('timed out',) 
Feb 26 22:31:10.072 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:10.072 - [DEBUG] get ip:2a00:1450:4001:33::15 t:300 
Feb 26 22:31:10.182 - [DEBUG] get ip:2a00:1450:4001:2e::18 t:300 
Feb 26 22:31:10.465 - [DEBUG] 2a00:1450:4001:2e::13 fail:timeout('timed out',) 
Feb 26 22:31:10.465 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:10.465 - [DEBUG] get ip:2a00:1450:400c:401::14 t:300 
Feb 26 22:31:10.589 - [DEBUG] 2a00:1450:4001:2e::12 fail:timeout('timed out',) 
Feb 26 22:31:10.589 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:10.589 - [DEBUG] get ip:2a00:1450:400c:401::15 t:300 
Feb 26 22:31:10.683 - [DEBUG] get ip:2a00:1450:400c:401::12 t:300 
Feb 26 22:31:10.980 - [DEBUG] 2a00:1450:4001:2e::15 fail:timeout('timed out',) 
Feb 26 22:31:10.980 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:11.011 - [DEBUG] sort ip time:30ms 
Feb 26 22:31:11.011 - [DEBUG] get ip:2a00:1450:400c:401::13 t:300 
Feb 26 22:31:11.106 - [DEBUG] 2a00:1450:4009:6::6 fail:timeout('timed out',) 
Feb 26 22:31:11.106 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:11.106 - [DEBUG] get ip:2a00:1450:400c:401::10 t:300 
Feb 26 22:31:11.496 - [DEBUG] 2a00:1450:4002:d::9 fail:timeout('timed out',) 
Feb 26 22:31:11.496 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:11.496 - [DEBUG] get ip:2a00:1450:400c:401::11 t:300 
Feb 26 22:31:11.621 - [DEBUG] 2404:6800:4005:1c::a fail:timeout('timed out',) 
Feb 26 22:31:11.621 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:11.621 - [DEBUG] get ip:2a00:1450:4001:2e::11 t:300 
Feb 26 22:31:12.012 - [DEBUG] 2a00:1450:4001:9::8 fail:timeout('timed out',) 
Feb 26 22:31:12.012 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:12.012 - [DEBUG] get ip:2a00:1450:4001:2e::10 t:300 
Feb 26 22:31:12.137 - [DEBUG] 2a00:1450:4007:10::15 fail:timeout('timed out',) 
Feb 26 22:31:12.137 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:12.137 - [DEBUG] get ip:2a00:1450:4001:2e::13 t:300 
Feb 26 22:31:12.528 - [DEBUG] 2a00:1450:4007:10::14 fail:timeout('timed out',) 
Feb 26 22:31:12.528 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:12.528 - [DEBUG] get ip:2a00:1450:4001:2e::12 t:300 
Feb 26 22:31:12.653 - [DEBUG] 2a00:1450:4001:2e::19 fail:timeout('timed out',) 
Feb 26 22:31:12.653 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:12.653 - [DEBUG] get ip:2a00:1450:4001:2e::15 t:300 
Feb 26 22:31:12.951 - [DEBUG] 2a00:1450:4001:2e::14 fail:timeout('timed out',) 
Feb 26 22:31:12.951 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:12.951 - [DEBUG] get ip:2a00:1450:4001:33::16 t:300 
Feb 26 22:31:12.997 - [DEBUG] 2a00:1450:4001:2e::17 fail:timeout('timed out',) 
Feb 26 22:31:12.997 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:12.997 - [DEBUG] get ip:2a00:1450:4001:33::17 t:300 
Feb 26 22:31:13.044 - [DEBUG] 2a00:1450:4001:2e::16 fail:timeout('timed out',) 
Feb 26 22:31:13.044 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:13.044 - [DEBUG] get ip:2a00:1450:4001:33::18 t:300 
Feb 26 22:31:13.169 - [DEBUG] 2a00:1450:4001:33::10 fail:timeout('timed out',) 
Feb 26 22:31:13.169 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:13.169 - [DEBUG] get ip:2a00:1450:4001:33::19 t:300 
Feb 26 22:31:13.457 - [DEBUG] 2a00:1450:4001:33::11 fail:timeout('timed out',) 
Feb 26 22:31:13.457 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:13.457 - [DEBUG] get ip:2a00:1450:4009:6::6 t:300 
Feb 26 22:31:13.555 - [DEBUG] 2a00:1450:4001:33::12 fail:timeout('timed out',) 
Feb 26 22:31:13.555 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:13.555 - [DEBUG] get ip:2a00:1450:4002:d::9 t:300 
Feb 26 22:31:13.679 - [DEBUG] 2a00:1450:4001:33::13 fail:timeout('timed out',) 
Feb 26 22:31:13.679 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:13.679 - [DEBUG] get ip:2404:6800:4005:1c::a t:300 
Feb 26 22:31:13.945 - [DEBUG] 2a00:1450:4001:33::14 fail:timeout('timed out',) 
Feb 26 22:31:13.945 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:13.945 - [DEBUG] get ip:2a00:1450:4001:9::8 t:300 
Feb 26 22:31:14.086 - [DEBUG] 2a00:1450:4001:33::15 fail:timeout('timed out',) 
Feb 26 22:31:14.086 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:14.086 - [DEBUG] get ip:2a00:1450:4007:10::15 t:300 
Feb 26 22:31:14.195 - [DEBUG] 2a00:1450:4001:2e::18 fail:timeout('timed out',) 
Feb 26 22:31:14.195 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:14.195 - [DEBUG] get ip:2a00:1450:4007:10::14 t:300 
Feb 26 22:31:14.477 - [DEBUG] 2a00:1450:400c:401::14 fail:timeout('timed out',) 
Feb 26 22:31:14.477 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:14.477 - [DEBUG] get ip:2a00:1450:4001:2e::19 t:300 
Feb 26 22:31:14.601 - [DEBUG] 2a00:1450:400c:401::15 fail:timeout('timed out',) 
Feb 26 22:31:14.601 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:14.601 - [DEBUG] get ip:2a00:1450:4001:2e::14 t:300 
Feb 26 22:31:14.695 - [DEBUG] 2a00:1450:400c:401::12 fail:timeout('timed out',) 
Feb 26 22:31:14.695 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:14.695 - [DEBUG] get ip:2a00:1450:4001:2e::17 t:300 
Feb 26 22:31:15.023 - [DEBUG] 2a00:1450:400c:401::13 fail:timeout('timed out',) 
Feb 26 22:31:15.023 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:15.023 - [DEBUG] get ip:2a00:1450:4001:2e::16 t:300 
Feb 26 22:31:15.117 - [DEBUG] 2a00:1450:400c:401::10 fail:timeout('timed out',) 
Feb 26 22:31:15.117 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:15.117 - [DEBUG] get ip:2a00:1450:4001:33::10 t:300 
Feb 26 22:31:15.507 - [DEBUG] 2a00:1450:400c:401::11 fail:timeout('timed out',) 
Feb 26 22:31:15.507 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:15.507 - [DEBUG] get ip:2a00:1450:4001:33::11 t:300 
Feb 26 22:31:15.633 - [DEBUG] 2a00:1450:4001:2e::11 fail:timeout('timed out',) 
Feb 26 22:31:15.633 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:15.633 - [DEBUG] get ip:2a00:1450:4001:33::12 t:300 
Feb 26 22:31:16.023 - [DEBUG] 2a00:1450:4001:2e::10 fail:timeout('timed out',) 
Feb 26 22:31:16.023 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:16.023 - [DEBUG] get ip:2a00:1450:4001:33::13 t:300 
Feb 26 22:31:16.148 - [DEBUG] 2a00:1450:4001:2e::13 fail:timeout('timed out',) 
Feb 26 22:31:16.148 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:16.148 - [DEBUG] get ip:2a00:1450:4001:33::14 t:300 
Feb 26 22:31:16.539 - [DEBUG] 2a00:1450:4001:2e::12 fail:timeout('timed out',) 
Feb 26 22:31:16.539 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:16.539 - [DEBUG] get ip:2a00:1450:4001:2e::18 t:300 
Feb 26 22:31:16.664 - [DEBUG] 2a00:1450:4001:2e::15 fail:timeout('timed out',) 
Feb 26 22:31:16.664 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:16.664 - [DEBUG] get ip:2a00:1450:400c:401::14 t:300 
Feb 26 22:31:16.961 - [DEBUG] 2a00:1450:4001:33::16 fail:timeout('timed out',) 
Feb 26 22:31:16.961 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:16.961 - [DEBUG] get ip:2a00:1450:400c:401::15 t:300 
Feb 26 22:31:17.009 - [DEBUG] 2a00:1450:4001:33::17 fail:timeout('timed out',) 
Feb 26 22:31:17.009 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.009 - [DEBUG] get ip:2a00:1450:400c:401::12 t:300 
Feb 26 22:31:17.056 - [DEBUG] 2a00:1450:4001:33::18 fail:timeout('timed out',) 
Feb 26 22:31:17.056 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.056 - [DEBUG] get ip:2a00:1450:400c:401::13 t:300 
Feb 26 22:31:17.180 - [DEBUG] 2a00:1450:4001:33::19 fail:timeout('timed out',) 
Feb 26 22:31:17.180 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.180 - [DEBUG] get ip:2a00:1450:400c:401::10 t:300 
Feb 26 22:31:17.461 - [DEBUG] 2a00:1450:4009:6::6 fail:timeout('timed out',) 
Feb 26 22:31:17.461 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.461 - [DEBUG] get ip:2a00:1450:400c:401::11 t:300 
Feb 26 22:31:17.555 - [DEBUG] 2a00:1450:4002:d::9 fail:timeout('timed out',) 
Feb 26 22:31:17.555 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.555 - [DEBUG] get ip:2a00:1450:4001:2e::11 t:300 
Feb 26 22:31:17.680 - [DEBUG] 2404:6800:4005:1c::a fail:timeout('timed out',) 
Feb 26 22:31:17.680 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.680 - [DEBUG] get ip:2a00:1450:4001:2e::10 t:300 
Feb 26 22:31:17.946 - [DEBUG] 2a00:1450:4001:9::8 fail:timeout('timed out',) 
Feb 26 22:31:17.946 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:17.946 - [DEBUG] get ip:2a00:1450:4001:2e::13 t:300 
Feb 26 22:31:18.087 - [DEBUG] 2a00:1450:4007:10::15 fail:timeout('timed out',) 
Feb 26 22:31:18.087 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:18.087 - [DEBUG] get ip:2a00:1450:4001:2e::12 t:300 
Feb 26 22:31:18.196 - [DEBUG] 2a00:1450:4007:10::14 fail:timeout('timed out',) 
Feb 26 22:31:18.196 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:18.196 - [DEBUG] get ip:2a00:1450:4001:2e::15 t:300 
Feb 26 22:31:18.477 - [DEBUG] 2a00:1450:4001:2e::19 fail:timeout('timed out',) 
Feb 26 22:31:18.477 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:18.477 - [DEBUG] get ip:2a00:1450:4001:33::15 t:300 
Feb 26 22:31:18.603 - [DEBUG] 2a00:1450:4001:2e::14 fail:timeout('timed out',) 
Feb 26 22:31:18.603 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:18.603 - [DEBUG] get ip:2a00:1450:4001:33::16 t:300 
Feb 26 22:31:18.696 - [DEBUG] 2a00:1450:4001:2e::17 fail:timeout('timed out',) 
Feb 26 22:31:18.696 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:18.696 - [DEBUG] get ip:2a00:1450:4001:33::17 t:300 
Feb 26 22:31:19.025 - [DEBUG] 2a00:1450:4001:2e::16 fail:timeout('timed out',) 
Feb 26 22:31:19.025 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:19.025 - [DEBUG] get ip:2a00:1450:4001:33::18 t:300 
Feb 26 22:31:19.118 - [DEBUG] 2a00:1450:4001:33::10 fail:timeout('timed out',) 
Feb 26 22:31:19.118 - [DEBUG] report_connect_fail network fail 
Feb 26 22:31:19.118 - [DEBUG] get ip:2a00:1450:4001:33::19 t:300

**Comment by klyxtxz** [comment]
上面是日志  
![_we2lsucz i1lu7ifucx 8w](https://cloud.githubusercontent.com/assets/25860558/23340593/e8746940-fc73-11e6-9ed8-522fe62e0175.png)    ipv6是可以访问google的

**Comment by jzp820927** [comment]
好像全部超时了，难道内置的 IPV6 都被封了？

**Comment by qweroucherr** [comment]
我用的"ipv6.google.com", "www.kame.net"还能连上

**Comment by jzp820927** [comment]
IPV6 环境监测问题，好像最新版已经修复了吧？

**Comment by hzxie** [comment]
因为这个Bug在3.2.9之后被修复, 所以3.3.0是正常的.

**Comment by cmpute** [comment]
话说这些解决过的issue都不close掉吗。。。

**Comment by jzp820927** [comment]
这个就只能找 issues 主了吧

**Comment by cmpute** [comment]
项目owner是可以close issue的= = 3k+的issue看着吓人

**Comment by jzp820927** [comment]
难道你没发现，项目很早以前就没人管理了麽

**Comment by hzxie** [comment]
@klyxtxz Close issue, 从你做起吧~

**Comment by klyxtxz** [comment]
closed #24
