### ISSUE TITLE
手机使用xxnet看不了YouTube视频

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#5069]
电脑通过局域网分享代理给手机后手机可以上YouTube但是视频不加载

**Comment by linhua55** [comment]
https://github.com/phuslu/goproxy/issues/1347#issuecomment-265083631

Google系App如youtube，因为用了 apk签名检查机制，修改过后的youtube apk，虽然可以观看视频，但是不能登录Google帐号。  如果想要登录Google帐号，只能强制让修改过后的youtube apk文件使用原来的apk签名，但是这会导致 用正常安装途径 安装不了 修改过后的youtube。只能 在root过的手机上，手动将youtube apk文件移动到  apk应用文件夹，然后重启手机
