### ISSUE TITLE
xx-net怎么分享给智能电视或者家庭共享？

### ISSUE THREAD

**Issue by liu1169681** [XX-net/XX-Net#5070]
如何分享给智能电视或者分享给无线路由？我目前用的是网件的无线路由，可以实现么？

**Comment by Steve-luo** [comment]
按照下面的教程开启0.0.0.0的listen，其他在同一局域网下设备使用http代理即可
https://github.com/XX-net/XX-Net/wiki/为其他设备提供代理服务

**Comment by liu1169681** [comment]
非常感谢，这三条都修改么？

**Comment by Steve-luo** [comment]
改前两条就行了，第三条看你用不用X_Tunnel，用的话就改。

**Comment by liu1169681** [comment]
你好，我找了半天config.ini里没有[listen]这一行呢，是新加一条么？
![Uploading 屏幕快照 2017-02-27 下午12.11.06.png…]()

**Comment by kirbyzhu** [comment]
@liu1169681 重新自己写一个manual.ini 文件 放在data的gae目录下面。
