### ISSUE TITLE
google 经常504报错

### ISSUE THREAD

**Issue by yadex** [XX-net/XX-Net#5088]
XX-Net Status:

sys-platform: x86_64, Linux-4.8.0-39-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017
os-release: 4.8.0-39-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2888
network-status: OK
connected-link: new:4 used:0
worker: h1:13 h2:9
scan-ip-thread-num: 50
ip-quality: 224
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
504 报错？换回 3.2.8 版本试试？

**Comment by wxn52111314** [comment]
我发现这和域名有关，用.hk或.jp会504超时，而.com就不会

**Comment by jzp820927** [comment]
不明觉厉，估计是规则的问题吧

**Comment by gam2046** [comment]
@xxnet 同样有此问题，其他网站均正常，唯独Google几乎不可用。

**Comment by jzp820927** [comment]
如果只有 google 系列网站问题，如果是最新版，可以换到 3.2.8 及以下版本试试
