### ISSUE TITLE
有没有办法可以定时自动重启GAEProxy？

### ISSUE THREAD

**Issue by drliuhuan** [XX-net/XX-Net#5092]
自己家里的服务器长时间开着xxnet，但是经常代理无反应，需要进入服务器右键点击xxnet托盘图标对GAEProxy进行重启，非常繁琐。有没有办法知道点击重启的过程是怎么执行的？我想做个计划任务去实现自动重启。
我查看了wintray.py那个托盘命令实现，但是不会使用python编写程序运行on_restart_gaeproxy()的函数，写了几个都失败了…有没有大神可以写一个一键重启服务的方法？谢谢啦！

**Comment by myjlpt** [comment]
要我就直接BAT,计划任务

taskkill /f /im pythonw.exe /t
ping -n 13 localhost >nul
start start.vbs

**Comment by drliuhuan** [comment]
感谢myjlpt，bat确实好用，已经实现2小时自动重启

**Comment by nnop** [comment]
为什么连不上时自动重启能管用呢？

**Comment by jzp820927** [comment]
自动重启，可以重新开始扫描 IP，有点用吧
