### ISSUE TITLE
浏览器提示：请检查浏览器代理设置。

### ISSUE THREAD

**Issue by git4dhk** [XX-net/XX-Net#5093]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: x86_64, Darwin-16.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
os-release: 16.4.0
os-detail: Release:10.12.3; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 3000 / 123
network-status: OK
connected-link: 9 / 50
scan-ip-thread-num: 5
ip-quality: 606
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by git4dhk** [comment]
有些网站可以访问，但是gmail不能访问，提示：“您的连接不是私密链接”，YouTube视频也不能播放

**Comment by git4dhk** [comment]
升级版本后，问题解决

**Comment by jzp820927** [comment]
一般这个提示都是证书问题。解决了就行。
