### ISSUE TITLE
host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503

### ISSUE THREAD

**Issue by dinglj** [XX-net/XX-Net#5095]
## 日志  ##
host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503

这个是什么问题。

**Comment by HenryHYH** [comment]
原因不清楚，降成3.2.8就可以用

**Comment by dinglj** [comment]
不知道为什么，又可以翻了，一脸懵逼。可能跟网络有关系把

**Comment by jzp820927** [comment]
可能是干扰造成的吧

**Comment by zszszsz** [comment]
据称是因为google的反机器搜索机制
https://github.com/XX-net/XX-Net/issues/5038
应该是相同的原因
https://github.com/XX-net/XX-Net/issues/5243

**Comment by jzp820927** [comment]
确实是这样。
