### ISSUE TITLE
“请检查浏览器代理设置”

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#5098]
最新版本（3.2.9）；配置成功，不影响使用，但状态栏显示“请检查浏览器代理设置”。即使再次安装证书也不行。

以前这个问题遇到过。重新实践了当时的解决方法，这次没能创造奇迹。显然上次是走了狗屎运，不知道怎么解决了。哈哈

请高手指教。作为一个强迫症患者，这种状态让我非常不舒服。

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:138 good:119
network-status: OK
connected-link: new:1 used:0
worker: h1:5 h2:5
scan-ip-thread-num: 50
ip-quality: 444
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
又不影响使用，何必把时间浪费在这种没有意义的事情上。

**Comment by farshidvahid** [comment]
[冷汗]

**Comment by jzp820927** [comment]
花时间研究状态信息，还不如去找点IP实在

**Comment by HUMORCE** [comment]
一般只有选择 “全局通过GAEProxy代理” ，
WebUI 才会反馈这个错误。

**Comment by farshidvahid** [comment]
Ctrl + F5，强制刷新  后果然可以了。感谢！！
