### ISSUE TITLE
部署gae服务端长时间没反应

### ISSUE THREAD

**Issue by fhzyfjy** [XX-net/XX-Net#51]
部署时要“请记得开启Google的弱安全连接”是不是指
1、开启“应用专用密码”？我在部署服务端上传时输入专用密码很长时间无反应；
2、关闭“应用专用密码”？我在部署服务端上传时输入gmail邮箱登陆密码，也是很长时间无反应
开启Google的弱安全连接具体如何操作啊？谢谢

**Comment by xxnet** [comment]
这句话后面的链接，点击就是了。

**Comment by fhzyfjy** [comment]
没有看到连接啊？是不是没有贴上？谢谢

2015-03-08 20:14 GMT+08:00 xxnet <notifications@github.com>:

**Comment by fhzyfjy** [comment]
我看了，有些不明白。你的意思是我开启2步验证及应用专用密码。上传时输入该应用专用密码？

在 2015年3月8日 下午8:25，fhzyfjy . <fhzyfjy3@gmail.com>写道：

**Comment by xxnet** [comment]
链接就在：
请记得开启Google的弱安全连接: 跳转
 https://www.google.com/settings/security/lesssecureapps

开启2步验证及应用专用密码。上传时输入该应用专用密码
 是的。

**Comment by fhzyfjy** [comment]
已按你给的链接https://www.google.com/settings/security/lesssecureapps，打开该网页，但没看到有“允许”选择按钮啊。已开启应用专用密码，上传时也用的应用专用密码。上传还是没反应，日志空白。烦请指教，谢谢

**Comment by xxnet** [comment]
“已啟用兩步驟驗證功能的帳戶無法使用這項設定。這類帳戶必須使用應用程式專用密碼，才能存取安全性較低的應用程式設定”

日志空白，那么请用start.bat 启动，从黑色控制台窗口中看看发生了什么。

**Comment by xxnet** [comment]
把状态页和异常日志都发出来分析

**Comment by fhzyfjy** [comment]
非常感谢，已经搞定，没问题。但觉得看视频时速度不是太快，有些卡。是不是设置问题？谢谢

**Comment by xxnet** [comment]
视频要看ip的质量，有时会快，晚上相对会慢。
白天720p我这边很流畅，晚上就比较卡，将就吧。

网上有教用浏览器插件加速的，不过我没有试验。

**Comment by centralarea** [comment]
我这是什么情况

![default](https://cloud.githubusercontent.com/assets/7357506/8122393/cb242bde-10eb-11e5-895f-6460bb7bca8d.JPG)

**Comment by centralarea** [comment]
![qq 20150612102531](https://cloud.githubusercontent.com/assets/7357506/8122508/64431cfc-10ed-11e5-8a1b-5361f2884b76.png)
无论我选择是否“通过GAE部署服务端”都会出现“未知错误”
我的google appid全是running还是需要部署服务端吗
![qq 20150612102802](https://cloud.githubusercontent.com/assets/7357506/8122541/d2bff3d0-10ed-11e5-8e65-81e8ea17e246.png)

**Comment by centralarea** [comment]
一定要用google浏览器吗？我用的是猎豹浏览器

**Comment by luyiaya** [comment]
最近经常部署的时候没反应，有时候晚上8点多会有一次通过，有时候晚上10点多会通过，能部署，想不通，是审查的原因？
