### ISSUE TITLE
关于托盘右键菜单

### ISSUE THREAD

**Issue by Kisesy** [XX-net/XX-Net#510]
大家觉得这样是不是更好一些
![20150611105126](https://cloud.githubusercontent.com/assets/5843694/8098839/d7b9670c-1027-11e5-986e-3aeb55cb6e79.png)
我觉得这个“设置”满多余的,反正点一下图标就是设置

**Comment by Kisesy** [comment]
当然这不是重点,重点是我想加上选中样式,其实我已经弄好了
但是代码写出来感觉有些傻

**Comment by xxnet** [comment]
这样很好啊，等这个补丁已经很久了。

你可以先提交pull，大家看看，代码怎么写更好。

**Comment by xxnet** [comment]
确实，traybar文件是个通用模块。
不过可以扩展它，让它可以在每个菜单前面设置图标。
实在不行，重新写一个专用的模块。

**Comment by Kisesy** [comment]
先这样写吧，关于代理方式的检测我也用的最简单的方式.....
不知道为什么我用网页没法pull了，以前倒是可以啊...
用网盘吧 http://pan.baidu.com/s/1dDvXAJf

**Comment by Kisesy** [comment]
还有就是用xx-net目前的代理设置方式,我电脑win7 32位下是无法正常代理的,我电脑上只能修改
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections
这里的lan设置才能用，这很奇怪，不知道哪里的设置问题，我记得以前是正常的

**Comment by xxnet** [comment]
给我发邮件附件吧
 xxnet.dev@gmail.com

在 2015年6月11日 下午9:20，Kisesy <notifications@github.com>写道：
