### ISSUE TITLE
您的连接不是私密连接  攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by jiangbeth** [XX-net/XX-Net#5106]
更新了chrome开发版的最新版本，然后就一直提示这样。楼主怎么办啊

**Comment by jzp820927** [comment]
证书问题，导入证书了吗？

**Comment by bjlisong** [comment]
同样的问题，IE，EDGE木有问题，问题主要出在CHROME上面

**Comment by bjlisong** [comment]
CHROME截图
![image](https://cloud.githubusercontent.com/assets/26292973/23736298/6da8c5de-04c6-11e7-94ce-25e002f66f77.png)

**Comment by jiangbeth** [comment]
已经导入证书

**Comment by hookybaby** [comment]
我也有同样的问题，证书都是导入了的，稳定版，测试版都有同样的问题

**Comment by MacSur** [comment]
**昨天正常，今天，几台电脑的显示都是这样，看来，貌似“被和谐”了？**

> 

> `昨天正常，今天，几台电脑的显示都是这样，看来，貌似“被和谐”了？`

**Comment by MacSur** [comment]
更新到最新版本也是这样的。

> 昨天正常，今天，几台电脑的显示都是这样，看来，貌似“被和谐”了？

**Comment by bjlisong** [comment]
@jzp820927 
同一台电脑上，QQ浏览器正常，但是CHROME不正常，CHROME版本58.0.3029.6 dev

**Comment by g8up** [comment]
从昨天开始，PC 和 笔记本上都出现了这个。

**Comment by SeaHOH** [comment]
谷歌是直连的吧，应该是 IP 问题，换成走 GAE 就可以了。

**Comment by lzplzp001** [comment]
检查了一下，CHROME 56版本的没有问题，CHROME 58的有问题，XX-NET的证书有问题。
请作者解决下。

**Comment by jiangbeth** [comment]
版本 58.0.3029.6（正式版本） （32 位）

**Comment by lzplzp001** [comment]
你先换回56版本，就没有问题了。
58的还不行。

**Comment by bjlisong** [comment]
目前来看貌似就是昨天更新上去的CHROME不认XX的这个证书了……

**Comment by jiangbeth** [comment]
看来我也只能用智能代理了

**Comment by jzp820927** [comment]
默认是现在 chrome 准备开始不信任自签证书了？如果是这样的话，GAE 全部都要死了。除非是不升级 chrome。我这边用的 稳定版，暂时最高只能升级到 56，但是说来也怪，我这边安装有 金丝雀版，版本号是：版本 59.0.3035.0（正式版本）canary （64 位），比你们都还高，也没有任何问题啊。你们试试金丝雀版有没有问题？

**Comment by causlayer** [comment]
还以为是mac os系统的问题呢，看来是chrome的事，我的浏览器版本是58.0.3029.6 dev (64-bit)也是同样的问题。暂时只能用safari或firefox了。

**Comment by ShawnZhong** [comment]
同样问题，证书已导入，Safari可用
Chrome问题版本：Version 59.0.3036.0 (Official Build) canary (64-bit)

**Comment by ShawnZhong** [comment]
![image](https://cloud.githubusercontent.com/assets/6421097/23775985/666cd21a-0566-11e7-85f1-ffd911c29a8c.png)

**Comment by ShawnZhong** [comment]
启动时加入命令：--ignore-certificate-errors，可以忽略证书错误

**Comment by SeaHOH** [comment]
@ShawnZhong 
不要在日常中使用这种危险的命令。

可以试一下把下面这个注释取消，删除证书重新生成导入。
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252

**Comment by ShawnZhong** [comment]
好 谢谢！

**Comment by lzplzp001** [comment]
@SeaHOH  使用你的这个方法问题解决了。

**Comment by bacon8474** [comment]
应该是修复了，现在可以访问google、youtube了，但twitter还是提示不是私密连接，麻烦再帮忙检查，谢谢！

**Comment by zqw0010** [comment]
@bacon8474 表示并没有修复，还是无法正常访问

**Comment by bjlisong** [comment]
@zqw0010 至少……我们知道并不是所有浏览器全军覆没……还有的用，哈哈

**Comment by zqw0010** [comment]
@bjlisong 期待这个问题能快速解决

**Comment by SeaHOH** [comment]
@bacon8474 @zqw0010 
确定 CA.crt 和 certs 文件夹都删除了？

**Comment by bjlisong** [comment]
@zqw0010 如同J大所说，假如Google开始限制自签证书的话，那么就真的木有啥可靠的好方法了估计短期内

**Comment by bacon8474** [comment]
@zqw0010 我这儿可以访问google、youtube了，之前不行；twitter、facebook依然不行。

**Comment by SeaHOH** [comment]
不可能限制自签，只是要求更多了。

**Comment by bjlisong** [comment]
而且昨天测试的时候发现一个超级麻烦的临时性使用方法，就是出现错误链接的话，点击IEtab切换到IE模式，正常浏览，然后再切换回CHROME模式，当前页面可正常浏览，但是下一页面依然需要重复操作，临时使用性质

**Comment by zqw0010** [comment]
@SeaHOH 删除过，重新生成过

**Comment by SeaHOH** [comment]
@bacon8474 
google、youtube 证书是否是 XX-Net 的？
如果不是，那就是直连模式。
那么这个应对可能不行，要改其它属性。

**Comment by byronwwang** [comment]
@jzp820927 我的也是金丝雀，同样错误。感觉不是证书错误，应该是SwitchyOmega插件的问题

**Comment by bjlisong** [comment]
@byronwwang 但是同样的SwitchyOmega，同样的配置在其他CHROME内核的浏览器上没问题……当然了……其他的内核版本止步于56

**Comment by byronwwang** [comment]
@SeaHOH 按照你的方法，问题解决了

**Comment by bacon8474** [comment]
@SeaHOH 以前配置xx-net是手动导入证书，后面也没改过啥，也没导入什么别的证书。早上上youtube、google、twitter、facebook都有问题，后来可以访问youtube、google(有时导航栏输入不行）。

**Comment by SeaHOH** [comment]
那再跟 @zqw0010 确认一下：浏览器删除后重新导入新生成的证书，是这样操作的？
矛盾的结果让我困惑，请再检查一遍。

@bacon8474 
点导航栏锁图标，查看 youtube、google 是否 XX-Net 证书。

**Comment by bacon8474** [comment]
@SeaHOH 显示连接安全，但是”go agent xx-net可以访问您在这儿看到或输入的信息”

**Comment by zqw0010** [comment]
@SeaHOH我不懂你 https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252 这个里面怎么做，我是删除了，重新在证书下载处下载了，重新导入了

**Comment by SeaHOH** [comment]
那统计一下 3:1，这个改发应该可行。

**Comment by SeaHOH** [comment]
@zqw0010 
在你自己的文件中把注释符号 `#` 去掉，不要用记事本操作。

**Comment by lushilei** [comment]
下一步怎么办/?

**Comment by zqw0010** [comment]
@SeaHOH 删除了code/default/gae_proxy/local/cert_util.py#L252 这行代码，也提前删除了certs文件夹和原先的证书，然后重新管理员权限运行start.bat ，还是不行

**Comment by gooyie** [comment]
用 Chromium 59.0.3031.0（开发者内部版本）64 位，[xx-net](https://github.com/XX-net/XX-Net)和[anyproxy](https://github.com/alibaba/anyproxy/tree/4.x)访问https都出现了安全错误，而fiddler却不会。

这应该是证书问题吧？

**Comment by bacon8474** [comment]
查看证书信息显示：xx-net颁发给twitter、facebook的有效期是到3月9号，也就是昨天为止。颁发给谷歌的有效期从今天到18年的3月10号。怎么更新？

**Comment by bacon8474** [comment]
重新生成后好了。

**Comment by g8up** [comment]
- 取消代码注释“#”
 > https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252
- 删除 \data\gae_proxy\下的CA.crt 和 certs
- 重启 xx-net 
- 恢复了

**Comment by causlayer** [comment]
@SeaHOH 按照方法google,facebook,twitter,youtube全部可以访问。
操作系统 mac ox 10.12.3 (16D32)
chrome版本 58.0.3029.6 dev (64-bit)

**Comment by zqw0010** [comment]
@g8up 问一下“#”在哪个位置，252行好像没“#”

**Comment by zqw0010** [comment]
![qq 20170310145333](https://cloud.githubusercontent.com/assets/16249981/23785224/884832fe-05a1-11e7-80c3-6337cb2c5083.png)
取消注释了，删除 \data\gae_proxy\下的CA.crt 和 certs
重启了 xx-net  还是不行

**Comment by gooyie** [comment]
@zqw0010 
要看你用的是哪个版本再改。
我也是去掉了 code\default\gae_proxy\local\cert_util.py#L252 的注释没用，才看了用的是XX-Net 3.2.9。
去掉 code\3.2.9\gae_proxy\local\cert_util.py#L252 的注释后重新生成的证书，不会报错了。

**Comment by zqw0010** [comment]
@gooyie 这样啊，晕死。。。

**Comment by Goooooollum** [comment]
版本 59.0.3036.0 canary (64-bit)也不行了

**Comment by zqw0010** [comment]
@Goooooollum换3.2.9版 按上面的方法

**Comment by Goooooollum** [comment]
@SeaHOH @zqw0010 确实可行，我用的是3.2.8

**Comment by MacSur** [comment]
问题解决了！！！！ - “ 请检查浏览器代理设置 ” 和“您的连接不是私密连接。。。。。”

谢谢网友：@kuchaguangjie 和 @g8up

取消代码注释“#”
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252


删除 \data\gae_proxy\下的CA.crt 和 certs
重启 xx-net
恢复了

**Comment by jzp820927** [comment]
想不到一天没来，这个 issues 这么热闹。

**Comment by ZachXu** [comment]
问题解决了！！！！ - “ 请检查浏览器代理设置 ” 和“您的连接不是私密连接。。。。。”

谢谢网友：@kuchaguangjie 和 @g8up

取消代码注释“#”
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252

删除 \data\gae_proxy\下的CA.crt 和 certs
重启 xx-net
恢复了
 
我也尝试过了，问题恢复了

**Comment by jzp820927** [comment]
最新版，已经不需要改代码了，只要升级到最新 3.3.1 版本就可以了。

**Comment by xyoungleo** [comment]
XX-Net 3.3.1

Safari可以正常上YouTube、Facebook、Google等网站，

但Chrome 版本 58.0.3029.110 (64-bit) 不行，也是提示
您的连接不是私密连接
攻击者可能会试图从www.youtube.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

尝试楼上的办法——
取消代码注释“#”
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252
删除 \data\gae_proxy\下的CA.crt 和 certs

可之后Safari都不能用了额，只能回退操作了。

看 https://github.com/XX-net/XX-Net/issues/66 说Mac版本已实现自动导入证书呢？

**Comment by jzp820927** [comment]
#5322
