### ISSUE TITLE
如何知道自己使用xxnet后的位置

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#5107]
想要用Google Play买游戏，需要购买礼品卡，但是不知道自己的账号是哪个位置的(｡•́︿•̀｡)

**Comment by jzp820927** [comment]
美国山景城

**Comment by jzp820927** [comment]
对了，为了保护隐私，google 公司把他所有 GAE 服务器的 IP，都标识为 google 总部的 IP，无法改变。
