### ISSUE TITLE
“ 请检查浏览器代理设置 ” - 一直这样的显示，怎么了？

### ISSUE THREAD

**Issue by MacSur** [XX-net/XX-Net#5110]
# 昨天正常，今天，几台电脑的显示都是这样，看来，貌似“被和谐”了？

**Comment by jzp820927** [comment]
是不是你在另一个 issues 说的不是私密连接？

**Comment by MacSur** [comment]
问题解决了！！！！ - “ 请检查浏览器代理设置 ” 和“您的连接不是私密连接。。。。。”

谢谢网友：@kuchaguangjie 和 @g8up

取消代码注释“#”
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252


删除 \data\gae_proxy\下的CA.crt 和 certs
重启 xx-net
恢复了

**Comment by ZZJJZZKPI** [comment]
删除\ data \ gae_proxy \下的CA.crt和certs 
重启xx-net 

这个是是在哪里删除的。。小白一个

**Comment by jzp820927** [comment]
xxnet 目录下的 data 目录下面的 gae_proxy 目录里面
