### ISSUE TITLE
win 10 启用防火墙后xx-net无法使用

### ISSUE THREAD

**Issue by d5121226** [XX-net/XX-Net#5112]
停止Windows Firewall服务后xx-net可以正常使用
![image](https://cloud.githubusercontent.com/assets/5326899/23753319/f8ca24da-0513-11e7-96a9-1b2005238905.png)
![image](https://cloud.githubusercontent.com/assets/5326899/23753343/143aff1e-0514-11e7-8b46-5909c66f37c7.png)
启用防火墙后xx-net无法使用，管理地址127.0.0.1:8085也无法访问
![image](https://cloud.githubusercontent.com/assets/5326899/23753539/ce3ff450-0514-11e7-9217-26b040ae238a.png)

**Comment by jzp820927** [comment]
在防火墙里面把相当的端口打开应该就可以了。
