### ISSUE TITLE
有没有新疆的朋友，新疆xxnet可以用吗?

### ISSUE THREAD

**Issue by panxuelei** [XX-net/XX-Net#5114]
最近要去新疆工作了，听说那边很严。蓝灯和赛风可以用吗？被发现了会不会被抓

**Comment by thy3331** [comment]
可以使用XX，但是具体你访问什么内容，这就你自己把握了，以及如果你用的是二级网络代理商的话可能会比较慢，其他没什么问题。以及“被发现了会不会被抓”这种问题我实在是没法回答你了

**Comment by jzp820927** [comment]
确实不好回答

**Comment by Mybestway** [comment]
相信一定很多人用代理。剩下的问题就是你会不会被抓到了

**Comment by kirbyzhu** [comment]
堂堂正正的浏览新闻上google 不搞啥歪门邪道的谁管你

**Comment by baoziwan** [comment]
看到5L的留言，想起一则新闻：“新疆警方‘反恐’清查升级网民听‘自由亚洲’遭拘留”。
在老大哥眼里，用代理就是逃避审查，就是偷偷摸摸，就是歪门邪道，和堂堂正正扯不上关系。
管你看什么，上了根本不存在的网站，老大哥就要想办法管你。
建议LZ多学些tor，看看“编程随想”的博客，保护好自己，不要因为压力就画地为牢。
毕竟世界宽广，思想自由。

**Comment by PanXuelei** [comment]
楼上，我说的就是这个。已经联系编程随想，看看他有什么解决办法

**Comment by Van47** [comment]
如果如6L所言，恐怕你我随时有被’遭拘留”的危险？答案是否定的，正如前几天所谓封杀VPN，现在至少在一线城市稍微有点常识的人都在用，普及率之高，那’遭拘留”的危险是不是很高呢？
答案当然是否定，问题是不管是VPN还是XX，
问题是：LZ你用来做什么？如果你的’工作”就是制造社会矛盾，挑起民族矛盾，即便你不来翻墙，别说’遭拘留”了，你自己想想后果。所以问题别栽赃到翻墙上，你早不早拘捕其实和你翻墙做什么有关，和翻墙本身无关。
如果你只是用来查查资料，看看外部世界，看看新闻。人畜无害，请问他管你做什么？正如那位把自己标榜自由的博主，口口声声说闭关锁国，我在这里不想讨论政治历史文化政体制度，中国有如今的发展你要学会辩证的看待事物，这个世界也没有什么唯一不变的真理和恒定的道理，所谓的世界宽广，人生而自由，现实是：一个真的自由的世界是什么世界？LZ应该学会的是独立思考，而不是tor，真的开始画地为牢。

**Comment by baoziwan** [comment]
咦，碰到网络舆论引导员了吗？
“人畜无害，请问他管你做什么？”
![lipi1mydfnpmu-2](https://cloud.githubusercontent.com/assets/18445029/24071188/179a81e4-0c07-11e7-9ca9-00a60db40b63.png)
照片里“暴力恐怖翻墙软件”这几个字总认得吧。
《新疆警方关停VPN使用者手机服务》，搜索来看看呗。
旅行者一号的官网  voyager.jpl.nasa.gov ， 够人畜无害了吧，可惜被墙了。
我只是“查查资料，看看外部世界，看看新闻”而已啊。
要跟谁论理呢？
翻墙的人没有全部被拘留，这是事实，但这并不意味着我们都是安全的。
选择性执法的害处，请看《孙立平：恐惧的生产与再生产》。
当为墙辩护的人，教你“独立思考”的时候，一定要提高警惕，一定要保护好自己，
也许它是想吃人血馒头了。

**Comment by PanXuelei** [comment]
很多人只是好奇那些新闻，有些看了不爽后在微博朋友圈发发牢骚就被删帖喝茶。发发牢骚骂骂政府骂骂娘怎么能叫制造社会矛盾，挑起民族矛盾呢？！我关注的很多微博上的人被删帖封号，他们只是说一些政府不爱听的话，比如说秀才江湖，天天骂政府，然后经常有国宝在他家门前蹲点。我们不满的是政府，我们有批评他们的权利。还有，在新疆翻墙软件被列为二级暴恐物品，之前有人手机因为装了翻墙软件被停机我是知道的，近来则有那位使用翻墙软甲上自由亚洲电台被拘留罚款的。

在 2017年3月18日 下午1:54，Van47 <notifications@github.com>写道：

**Comment by PanXuelei** [comment]
受害者为加害者辩护、同情加害者，这不就是斯德哥尔摩综合症吗？！身在新疆，我从邮箱中点击这条帖子的链接想要跳转到github，直接访问不了，真是迄今为止最干脆的，我不用代理虽然也访问不了谷歌油管，但至少还会加载一会儿，这个倒好。

在 2017年3月18日 下午6:47，baoziwan <notifications@github.com>写道：

**Comment by Tujue** [comment]
不行,我是试了,能进去一会,过会就断了.有没有什么别的解决办法?

**Comment by intypython** [comment]
看你是什么民族了。如果是维吾尔族翻墙，那么你就是恐怖份子了。。。。

**Comment by panxuelei** [comment]
> 看你是什么民族了。如果是维吾尔族翻墙，那么你就是恐怖份子了。。。。

老哥，竟然在我的帖子下遇到你。。。我youtube、twitter都关注你了。
后来我也的确到新疆了，使用翻墙软件还是没有问题的，前提是你是汉族，还有就是别被查手机。但是我用了七年的微博在那段时间被封停了，微信朋友圈也被监控限制。

**Comment by panxuelei** [comment]
![img_20170724_154229](https://user-images.githubusercontent.com/10558195/52828345-6f17bb80-3103-11e9-8ae9-86b2610abb24.jpg)
![img_20170903_132103](https://user-images.githubusercontent.com/10558195/52828355-76d76000-3103-11e9-9422-8237baafe5dd.jpg)
![img_20170722_195803](https://user-images.githubusercontent.com/10558195/52828361-7ccd4100-3103-11e9-8435-899d1ed6d10c.jpg)
![img_20171020_134252](https://user-images.githubusercontent.com/10558195/52828374-8656a900-3103-11e9-868e-a8a9b2f4378a.jpg)
上传个图片真慢。。。
