### ISSUE TITLE
问题解决了！！！！ - “ 请检查浏览器代理设置 ” 和“您的连接不是私密连接。。。。。”

### ISSUE THREAD

**Issue by MacSur** [XX-net/XX-Net#5116]
问题解决了！！！！ - “ 请检查浏览器代理设置 ” 和“您的连接不是私密连接。。。。。”

谢谢网友：@kuchaguangjie 和 @g8up

取消代码注释“#”
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252

删除 \data\gae_proxy\下的CA.crt 和 certs
重启 xx-net
恢复了

![snap039](https://cloud.githubusercontent.com/assets/9836713/23797541/53b38112-05db-11e7-9fe3-d6876cc17f03.jpg)
![Uploading snap040.jpg…]()
![snap041](https://cloud.githubusercontent.com/assets/9836713/23797542/53f39478-05db-11e7-86bd-753966b86aa1.jpg)
![snap042](https://cloud.githubusercontent.com/assets/9836713/23797543/5432dbd8-05db-11e7-90e6-651f87927c88.jpg)
![snap043](https://cloud.githubusercontent.com/assets/9836713/23797544/54578636-05db-11e7-9100-2b64350a6a26.jpg)
![Uploading snap044.jpg…]()

**Comment by YangChern** [comment]
用此方法也解决了，多谢分享

**Comment by JohnnyHu** [comment]
突然就用不了，这个亲试，可以解决问题。Thanks!

**Comment by jzp820927** [comment]
高手在民间

**Comment by TIS-OMiddle** [comment]
现在chrome+xxnet不会爆内存了？

**Comment by MacSur** [comment]
谢谢网友：@kuchaguangjie 和 @g8up

**Comment by elbow95** [comment]
赞

**Comment by yh794406573** [comment]
原理是重新导入CA证书？

**Comment by dhssingle** [comment]
照着坐了，证书和浏览器代理设置还是fail

**Comment by anuxs** [comment]
证书是3月10日的，可以了。照做就可以了。之前是3月7日的证书，删除证书重新生成都是3月7日的证书，这次是3月10日的证书。
代码注释去掉反而可以？之前3.3.0版本为什么不走认证？

**Comment by jzp820927** [comment]
不明觉厉

**Comment by percyi** [comment]
照做了，还是不行。。证书和浏览器代理设置还是fail

**Comment by jzp820927** [comment]
等合并吧

**Comment by SeaHOH** [comment]
这个并不解决状态检测错误，兼容最新 Chrome 对自签证书的要求罢了。

**Comment by jzp820927** [comment]
状态检查引发太多 issues 了，但是实际上作用并不是大，权衡得失，感觉应该去掉状态监测。

**Comment by sudemo** [comment]
证书和浏览器代理设置fail+1
除了google其他网站都可以访问，而且开代理后chrome要卡死一会儿，更奇怪的是两台一样的电脑，用xxnet-mini的 不存在上述问题，完全正常

**Comment by jzp820927** [comment]
能用就行了。

**Comment by weijietong** [comment]
great work ! thanks!!!

**Comment by ZZJJZZKPI** [comment]
在哪里删除啊。。。

**Comment by weijietong** [comment]
* 1 在你的XX-Net 本地代码目录找到  cert_util.py 这个文件，在代码的这个
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252
位置，也许你代码位置不一样，找到同样的这一行代码，将#去掉
* 2  同样是在XX-Net的本地代码目录里，删除 \data\gae_proxy\目录下的CA.crt文件 和 certs目录
* 3  重启 XX-Net 即可

**Comment by dhssingle** [comment]
我是全删了，重启然后重新下了一个xx-net解决的。
https://github.com/XX-net/XX-Net/wiki/%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF

**Comment by ahangchen** [comment]
超赞

**Comment by MacSur** [comment]
使用 V56版本的谷歌浏览器。才可以。
百度盘下载地址：https://pan.baidu.com/s/1qYnI4W0#list/path=%2F%E8%BD%AF%E4%BB%B6%2F%5BChrome%5D%2F%E6%97%A0%E6%9B%B4%E6%96%B0%E5%8A%9F%E8%83%BD%E7%89%88%2F%E5%8E%86%E5%8F%B2%E7%89%88%E6%9C%AC&parentPath=%2F%E8%BD%AF%E4%BB%B6

**Comment by MacSur** [comment]
**# 使用 V56版本的谷歌浏览器。才可以。
百度盘**

**Comment by rescue1** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:814 good:272
network-status: OK
connected-link: new:5 used:0
worker: h1:17 h2:3
scan-ip-thread-num: 50
ip-quality: 622
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: true

照此解决了，状态检查依然是“请检查浏览器代理设置。”
Google App 新申请了ID，并设置了--region us-central, 但是依然无法上传应用。
我是刚刚开始用xx-net，之前一直在用3.2.3的5ea98a9 goagent版本。但是要经常自己搜索IP并手工编辑。最近IP被封杀的速度太神速了，100多个IP一天就全军覆没。

**Comment by jzp820927** [comment]
那应该就是证书问题了，导入证书了麽？

**Comment by rescue1** [comment]
证书导入了，查看了一下，有三个证书在上面。
![screenshot_1](https://cloud.githubusercontent.com/assets/10630965/24077769/0140243a-0c93-11e7-9bbb-457a009a899f.png)

**Comment by jzp820927** [comment]
估计有可能是证书有冲突，建议你删除现在导入系统的所有 XXNET 的证书，然后在重新导入一次证书。

**Comment by rescue1** [comment]
谢谢 jzp！
删除了全部已经安装的XX-net的证书，删除代码注释和已经下载的data目录下的证书，使用管理员权限run start.bat，但状态检测依然是“请检查浏览器代理设置“，浏览器代理设置与证书下依然是双fail。我不知是否与已经存在的Goagent 证书冲突，但我还不想删除Goagent证书。
部署appid，也不成功，但上面的部署状态显示”部署完成“
2017-03-19 22:23:36,443 - root - INFO - enable debug logging
2017-03-19 22:23:36,443 - root - INFO - set proxy to http://127.0.0.1:8087
2017-03-19 22:23:36,443 - root - INFO - ============ Begin upload ============
2017-03-19 22:23:36,443 - root - INFO - appid:MYGAPPID。。。

其实在这个状态下，XX-net可以使用，可以翻墙。但是我还是想用自己的appid，不想使用公共的appid。
或许这所有的一切都与google chrome 版本有关，因为上面有人说56版本的chrome是可以的，而我的是57版本。
所以我还是暂时用回Goagent 3.2.3，自己多搜搜IP吧。非常感谢jzp，我稍后再回来看看。

**Comment by jzp820927** [comment]
能正常翻墙，那就是状态监测的问题了，可以试试 ctrl+F5 强制刷新。
至于部署服务端问题。你可以浏览器打开 https://你的appid.appspot.com 看看显示的什么内容？

**Comment by rescue1** [comment]
CTRL+F5强制刷新，状态显示正确！
“您正在使用公共APPID，因为资源有限，使用上存在限制，建议部署私有APPID。”
浏览器代理设置和证书全部OK。
部署服务端方面，我用新申请的https://新申请的appid.appspot.com，
显示：
Error: Not Found
The requested URL / was not found on this server.

而我曾经部署goagent成功的https://mygoagentappid.appspot.com 显示：
GoAgent 服务端已经在 2015-04-27 03:11:32 升级到 3.2.0 版本, 请更新您的客户端。
我再挖一下部署AppID服务端的issue解决方案吧。谢谢jzp。
XX-net的确比Goagent方便多了，假如部署成功了我就更换到xx-net使用了。

**Comment by jzp820927** [comment]
提示 Error: Not Found 说明没部署成功。如果用 XX 不能成功部署，可以试试
https://github.com/jzp820927/Deploy_XXNET_Server

**Comment by rescue1** [comment]
非常感谢jzp820927，还有楼主以及坛子里其他的分享者。

XX-Net终于成功部署，分享一下过程。我会拷贝一些他人其他的内容过来，方便后来者查阅。

先说一下缘由，我一直使用Goagent 3.2.3，用Gogotester搜IP，填写到用户IP列表里面。但是GFW杀IP的速度太快，而且IP时死时活，变化太快，导致链接不稳定经常被复位。

得知XX-Net是相当于继Goagent的重生，于是有兴趣转换到XX-Net。下载了之后，按照wiki说明配置，当场就可以使用，但是浏览器代理和证书都fail，于是按照顶楼的做法（请参照顶楼），再删去旧的CA（用certmgr.msc在windows7），重新启动XX-net。这时还显示“请检查浏览器代理设置”，要将XX-net SwichyOmega工作方式切换到“System Proxy”，或者是”XX-Net自动切换“，然后强制刷新CTRL+F5，状态显示就正确了。在Direct方式按CTRL+F5是没用的。这是我纠证书的过程。其实这应该是状态检查的问题，不影响翻墙。

接下来是部署AppID。感谢以往Goagent的工作者，用Goagent我事先申请了5个新的AppID，并且参照https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids
我是参照“因GAE升级，设置AppID的App引擎需要用新的方法”部分设置的，两个命令行解决（下图，图中我隐去了自己的AppID）
![screenshot_2 - copy](https://cloud.githubusercontent.com/assets/10630965/24089494/43fb89ec-0d72-11e7-8709-d55d48b57233.png)

到页面
https://github.com/jzp820927/Deploy_XXNET_Server，
下载zip文件，并展开。接下来，使用ShadowSocksR免费账号搭梯子。这一步骤其实很关键，没梯子就够不着。不过我运气不好，折腾了一上午，也没找到好用的免费账号，后来想起来自己还有一个免费的VPN还有大概200Mb的流量，差不多够用了，就开启我的免费VPN开始上传。开启Chrome的运行pop-up弹窗，再到展开的Deploy_XXNET_Server目录下，以管理员方式运行uploader.bat，输入自己新申请的一个appid，等一会儿会弹出页面，就如同在下面链接中 “左击Allow，然后就会进行服务端的部署”部分：
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids
当然我是事先登录了appengine，如果事先没有登录，可能还要去登录appengine。
点击Allow以后，uploader会继续，直到完成上传。
然后我一下子上传了其余4个AppID的应用，这次uploader比较智能，直接拷贝了四份上传，比以前Goagnet一个一个上传快多了。
结束之后，验证一下 https://myxx-net-newappid.appspot.com, 显示内容为：
“GoAgent 服务端已经在 2017-03-20 12:51:51 升级到 3.3.1 版本, 请更新您的客户端。”
这应该是上传成功了。我把每一个新的AppID都验证了一下。
回到XX-net设置页，到配置页面填好新的AppID，5个都填入，以"|"隔开，点击保存。然后到状态页面，按CTRL+F5强制刷新，显示“XX-Net 3.2.9，一切正常，你可以访问真正的互联网了。”
其中AppID一项，显示了自己的五个新的AppID，不是以前的公共AppID了。5个AppID的quota，看一整天视频都够。
希望能帮助刚刚接触xx-的人。
最后，再次感谢jzp820927，还有其他无私提供帮助的人们。

**Comment by jzp820927** [comment]
恭喜你，问题解决了。

**Comment by Lancaster7** [comment]
按上面步骤删除了文件后重启xx.net,还是没有用。显示如下诊断信息，请大神帮忙看看，是什么情况？

我先按照建议进行了如下操作：
1 在你的XX-Net 本地代码目录找到 cert_util.py 这个文件，在代码的这个
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252
位置，也许你代码位置不一样，找到同样的这一行代码，将#去掉
2 同样是在XX-Net的本地代码目录里，删除 \data\gae_proxy\目录下的CA.crt文件 和 certs目录
3 重启 XX-Net 即可

然后还是不能翻墙。

显示诊断信息如下：

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1581
network-status: OK
connected-link: new:8 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 955
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
@Lancaster7 请问你通过 XX 代理访问一个被墙网站的时候，浏览器显示什么？

**Comment by wchyumo2009** [comment]
没改代码，删了证书，重启之后就好了

**Comment by jzp820927** [comment]
造成这种情况的原因很多，不一定非要改代码

**Comment by hawyrihby** [comment]
用这个方法解决了，昨天还正常，今天 突然就提示请检查浏览器代理设置

**Comment by jzp820927** [comment]
确实很多时候，这个状态不影响代理使用。

**Comment by xichagui** [comment]
同样解决 2.9.6版

**Comment by jzp820927** [comment]
现在直接用最新的 3.3.1 版本就可以了。

**Comment by xichagui** [comment]
使用最新版要重新授权appid么？我貌似不科学上网就授权不了。

**Comment by jzp820927** [comment]
appid 只需要部署一次，就可以终生使用了，不用反复部署。

**Comment by wu0407** [comment]
说一下我的解决方法
我使用的goagent 3.2.3
https://github.com/XX-net/XX-Net/issues/5116#issuecomment-286304594

> 1 在你的XX-Net 本地代码目录找到 cert_util.py 这个文件，在代码的这个
> https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252
> 位置，也许你代码位置不一样，找到同样的这一行代码，将#去掉
> 2 同样是在XX-Net的本地代码目录里，删除 \data\gae_proxy\目录下的CA.crt文件 和 certs目录
> 3 重启 XX-Net 即可

这里将local/proxylib.py里的275行的注释去掉，其他步骤一样即可
```
cert.add_extensions([OpenSSL.crypto.X509Extension(b'subjectAltName', True, ', '.join('DNS: %s' % x for x in sans))])
```

**Comment by jzp820927** [comment]
现在最新版已经解决这个问题了，不用改代码了。

**Comment by SeaHOH** [comment]
他还在用 goagent，实在人。

**Comment by jzp820927** [comment]
好吧，就当我没说

**Comment by blusunny** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1493
network-status: OK
connected-link: new:2 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 131
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


好神奇啊，我的chrome浏览器升到58就用不了了
设置页面：“请检查浏览器代理设置 ” 
搜索显示：“您的连接不是私密连接”
按照楼上折腾还没成功，准备升级到最新测试版试试

**Comment by blusunny** [comment]
升级了也不行
还有一个奇怪的问题，我同一电脑上的qq浏览器，同样的插件同样的设置，可以正常通过代理访问。
求大神指点

**Comment by jzp820927** [comment]
#5322

**Comment by scxkd2016** [comment]
解决了很6

**Comment by wangxiaotaot** [comment]
谢谢！

**Comment by johnwen18** [comment]
解决了，厉害炸了

**Comment by jzp820927** [comment]
解决了就行

**Comment by Johnkyens** [comment]
厉害了，这个方法是有效的，直接删除上面的两项就ok了
