### ISSUE TITLE
使用XX-Net和SwitchyOmega无法下载谷歌学术的引用endNote或者bibtex

### ISSUE THREAD

**Issue by xyzhangcs** [XX-net/XX-Net#5122]
点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by xyzhangcs** [comment]
举例：
https://scholar.google.com/scholar?q=data+deduplication&hl=en&as_sdt=0%2C5&oq=deduplication
然后点击某篇paper的cite，然后选择BibTex或者EndNote，都无法打开，显示结果如下：
Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

**Comment by jzp820927** [comment]
看样子又是检查到非法流量了，得走直连才行。

**Comment by kirbyzhu** [comment]
以前我用xx 3.3.0 没这个问题的

**Comment by xyzhangcs** [comment]
好的，我试试直连看看，
还有个问题，我Chrome插件+XX-Net<取消全局代理>，Chrome可以连接到“互联网”，但是用Firefox就不行
，Firefox我没有安装插件我关掉Chrome插件，XX-Net使用全局PAC智能代理，还是无法连接。
我的意思是如何使用XX-Net让各个浏览器都能正常连接

**Comment by jzp820927** [comment]
不知道你 ff 是如果设置代理的

**Comment by xyzhangcs** [comment]
之前没有设置代理，我去琢磨看看~非常感谢！
这个issue我可以关闭了~

**Comment by xyzhangcs** [comment]
之前没有设置代理，我去琢磨看看非常感谢！
这个issue我可以关闭了
