### ISSUE TITLE
这两天google搜索基本用不了了！！

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#5124]
版本：3.2.9，诊断信息如最下。

使用google 搜索，先时在左下角出现：正在等待ipv4.google.com响应；然后不多久，网页就变成了：连接超时，请先休息一会再来。都截图了。但看IP数量和IP延迟，都很正常。

![11](https://cloud.githubusercontent.com/assets/13399800/23830643/9a8a00dc-074a-11e7-851c-8707d6ea28a0.jpg)
![22](https://cloud.githubusercontent.com/assets/13399800/23830644/9e337812-074a-11e7-9918-49a3da53e5ab.jpg)

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:632
network-status: OK
connected-link: new:7 used:0
worker: h1:11 h2:10
scan-ip-thread-num: 43
ip-quality: 160
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zhehao** [comment]
+1

**Comment by yutianzeabc** [comment]
+1
Mar 12 18:35:43.118 - [WARNING] IP:58.26.8.77 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Mar 12 18:35:43.118 - [DEBUG] report_connect_fail:58.26.8.77
Mar 12 18:35:43.145 - [DEBUG] create_ssl update ip:112.72.5.114 time:214 h2:0
Mar 12 18:35:43.199 - [DEBUG] restore ip:118.107.75.152
Mar 12 18:35:43.225 - [DEBUG] create_ssl update ip:202.28.85.204 time:241 h2:0
Mar 12 18:35:43.287 - [WARNING] IP:203.233.96.13 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Mar 12 18:35:43.287 - [DEBUG] report_connect_fail:203.233.96.13
Mar 12 18:35:43.450 - [DEBUG] 49.106.234.181 fail:timeout('timed out',)
Mar 12 18:35:43.450 - [DEBUG] report_connect_fail:49.106.234.181
Mar 12 18:35:43.472 - [WARNING] IP:112.72.5.114 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Mar 12 18:35:43.472 - [DEBUG] report_connect_fail:112.72.5.114
Mar 12 18:35:43.629 - [WARNING] IP:202.28.85.204 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Mar 12 18:35:43.629 - [DEBUG] report_connect_fail:202.28.85.204
Mar 12 18:35:43.814 - [WARNING] IP:112.72.5.82 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503
Mar 12 18:35:43.814 - [DEBUG] report_connect_fail:112.72.5.82

**Comment by CSC1994** [comment]
+2

**Comment by zqw0010** [comment]
跟我一样，还以为就我一个人这样呢，原来大家都是啊，为什么都不上来反应呢，

**Comment by jzp820927** [comment]
退回到版本：3.2.8 试试呢？

**Comment by farshidvahid** [comment]
上其它网站都没问题，看youtube搜搜的，google scholar也正常使用。就是google本身使用不了。

**Comment by jzp820927** [comment]
https://www.google.com/ncr

**Comment by tannx** [comment]
开两会期间，我这边也一样
`连接超时，先休息一会再来！`

**Comment by farshidvahid** [comment]
@jzp820927 这个方案目前可行。希望以后也可以。感谢了！

**Comment by tannx** [comment]
可以在chrome安装这个插件:
https://chrome.google.com/webstore/detail/nocountryredirect-ncr/ciboebddidackjicoeoiigdnbmchkdll

**Comment by ZFSieben** [comment]
用ncr也不行，似乎是无法生成ssl连接？

Mar 13 09:26:27.066 - [INFO] GAE CONNECT www.google.com:443
Mar 13 09:26:27.073 - [INFO] ssl error: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:590), create full domain cert for host:www.google.com
Mar 13 09:26:27.156 - [INFO] GAE CONNECT www.google.com:443
Mar 13 09:26:27.162 - [INFO] ssl error: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:590), create full domain cert for host:www.google.com

**Comment by jzp820927** [comment]
这个错误没遇到过。是什么系统啊？

**Comment by ZFSieben** [comment]
Mac OS @jzp820927

**Comment by jzp820927** [comment]
除了 google ，其他网站正常吗？

**Comment by ZFSieben** [comment]
常用网站似乎只有Google打不开 @jzp820927

**Comment by jzp820927** [comment]
你用的什么版本啊？

**Comment by ZFSieben** [comment]
2.9.2 @jzp820927

**Comment by jzp820927** [comment]
这么低的版本，先升级到最新版试试看

**Comment by farshidvahid** [comment]
加上ncr使用一天了，正常，关帖子了。
