### ISSUE TITLE
SwitchyOmega插件无法使用

### ISSUE THREAD

**Issue by mttgh** [XX-net/XX-Net#5126]
首先我最新版xxnet可以正常fq。xx net改为取消全局代理，关闭并退出xx net，SwitchyOmega插件配置为xx net 却无法fq.

**Comment by mttgh** [comment]
![1](https://cloud.githubusercontent.com/assets/23295505/23833026/c460aa3e-077a-11e7-82d9-8be27e8d2938.png)
![3](https://cloud.githubusercontent.com/assets/23295505/23833029/d0bc6688-077a-11e7-8c97-faf02b51784c.png)
![4](https://cloud.githubusercontent.com/assets/23295505/23833030/d997f380-077a-11e7-8875-0a2d18503b85.png)
![2](https://cloud.githubusercontent.com/assets/23295505/23833037/f028fc20-077a-11e7-97fa-f527eecc0dfa.png)

**Comment by dgtsl32** [comment]
不要插件更好使啊！

**Comment by mttgh** [comment]
@dgtsl32 习惯chrme插件开启，刚又手动导入了备用的证书还是不行，请问自带的OmegaOptions.bak和自己创建的SwitchyOptions.bak哪个是最新的

**Comment by dgtsl32** [comment]
OmegaOptions.bak；

還是不要用插件為好！用插件很麻煩，我用幾天就不再用了！

2017-03-13 0:20 GMT+08:00 mttgh <notifications@github.com>:

**Comment by jzp820927** [comment]
关闭并退出xx net，SwitchyOmega插件配置为xx net 却无法fq.
你都推出 xxnet 了，还怎么fq？

**Comment by mttgh** [comment]
@jzp820927 用插件的作用不就是代理么 如果说我开了SwitchyOmega还要再手动开xx net，那SwitchyOmega不就没有了存在的意义么，我的意思是让SwitchyOmega去管理xx-net，问题可能出现在SwitchyOmega那边

**Comment by wenliyang** [comment]
@mttgh 建议你去看一下SwitchyOmega的常见问题

https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by jzp820927** [comment]
@mttgh 好吧，我无语了，等高手来解答你的问题

**Comment by mttgh** [comment]
@wenliyang 常见问题昨天翻了20多页，没找到匹配的 也不太清楚他们之间的关系，算了 我把问题关了吧

**Comment by royink** [comment]
插件只是告诉chrome要去用什么代理啊。
你代理的程序都关了还翻个じば墙

**Comment by ccwy** [comment]
真是牛逼啊，xx net是代理工具，你翻墙靠它，懂？

SwitchyOmega是网页插件，接管chrome的代理而已，你真当它本身就能翻墙？

不得不服了。。。。。。。

**Comment by mttgh** [comment]
@ccwy 求教 没有找到教程，xxnet目前可以独立fq。求教用chrome插件SwitchyOmega代理xxnet fq，目前SwitchyOmega是导入了默认配置。

SwitchyOmega配置：
其中MT开头的是我自己增加的情景模式，里面没有配置东西
![01](https://cloud.githubusercontent.com/assets/23295505/23850334/effa086c-0819-11e7-9db8-e5cd05858817.png)

**Comment by penwong** [comment]
围观zz

**Comment by mttgh** [comment]
个人感觉教程还没有结束，本人小白，只是个爱好者，原理什么的也都不懂，对xx net 和SwitchyOmega也是刚接触，xx net从刚接触到配置成功fq到配置多个appId也都是自己看教程解决的，SwitchyOmega中的教程和xx net中的教程也看了挺多遍的

**Comment by penwong** [comment]
switchyomega并没有翻墙作用好吧。只是一个自动分流工具

**Comment by jzp820927** [comment]
从来没想到过 1+1=2 这么难解释。看来我应该继续深造了。

**Comment by ccwy** [comment]
@mttgh  SwitchyOmega不能独立翻墙，必须有其他代理来翻墙，SwitchyOmega只是chrome的本地代理，翻墙必须要有其他代理工具，明白了吗？

xx net作为一个翻墙工具，可以和SwitchyOmega配合使用，也可以直接使用，直接使用chrome就是走IE代理了，你用SwitchyOmega可以改变chrome的代理模式，但SwitchyOmega本身是不能翻墙的。

目前的代理工具很多，你可以自己找找看吧，局限性是很可怕的，善用谷歌搜索，能帮你解决很多疑难杂症的。

**Comment by SeaHOH** [comment]
爱好者…者……者…………

**Comment by mttgh** [comment]
@ccwy 多谢了。之前用chrome插件穿越fq，现在是想着用SwitchyOmega管理xx-net。[链接](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。 不再追问了，各位也不要回复了。

**Comment by jianglwei** [comment]
打个比方，插件是电风扇，xx是电源，你把电源拔了，想让风扇自己转？让风扇转的是电，而不是风扇开关。

**Comment by jzp820927** [comment]
Chrome 上能直接翻墙的插件，是应该把代理服务器的信息写到插件里面了，因为集成了代理服务器，自然能翻墙了，Omega 设计初衷就是一个纯粹的代理管理插件，不集成任何代理服务器，所以不能独立使用。

**Comment by dgtsl32** [comment]
哥們有強迫症啦，為何一定用插件？！用插件時不時還要手動配製，你不覺得麻煩？！

2017年3月13日 下午11:27，"天朝屁民" <notifications@github.com>写道：
