### ISSUE TITLE
无法部署，app id创建完成，无法部署

### ISSUE THREAD

**Issue by s2006204023** [XX-net/XX-Net#5139]
1、配置GAEProxy 时 显示
无效的Appid:my-xxx-xxx|my-xxx-xxx|my-xxx-xxx|，使用前请先部署。
2、打开https://你的appid.appspot.com/，显示 
Error: Not Found
The requested URL / was not found on this server.

**Comment by jzp820927** [comment]
#4720

**Comment by s2006204023** [comment]
非常感谢，几个月没解决的问题，万分感谢。

**Comment by jzp820927** [comment]
几个月了，你现在才来发 issues？
