### ISSUE TITLE
现在IPV6的IP是不是都不能用了？

### ISSUE THREAD

**Issue by kagurainroy** [XX-net/XX-Net#5143]
现在我搜索每一个IP都是300MS TIME OUT了

**Comment by jzp820927** [comment]
不应该吧，IPV6 的数量无穷大，不可能全部封死，多找找，肯定有。

**Comment by kagurainroy** [comment]
用XX NET搜索IP的时候HOSTS不影响吧？

**Comment by jzp820927** [comment]
不影响，用的自带的 IPV6 数据

**Comment by kagurainroy** [comment]
可不可以设置成 专门搜索用于访问国内的IPV6地址啊  因为我用的是IPV6教育网 IPV4通道的话限流量收费

**Comment by jzp820927** [comment]
国内 IPV6 地址？不知道你什么意思。你是想 XXNET，能够扫描国内网站的 IPV6 地址？

**Comment by kagurainroy** [comment]
因为xx net扫描出来的都是可以访问国外网站的ipv6 地址 所以我想有没有可以访问国内网站的ipv6地址呢？直接用xx net ipv6访问国内网站 延迟很高我也看不了视频

**Comment by jzp820927** [comment]
这个应该是 hosts 的事情吧。XX 的目的不是用于解决这类问题。

**Comment by CrazyRundong** [comment]
电子科大这边的 IPv6 也没法用... 明明可以直接上 ipv6.google.com 的

**Comment by jzp820927** [comment]
应该和 IPV6 没关系，应该是 XX 的问题了。
