### ISSUE TITLE
update version Chrome(beta) shows: Your connection is not private

### ISSUE THREAD

**Issue by tannx** [XX-net/XX-Net#5159]
System Version:
System Platform: x86_64, Linux-4.5.0-2-amd64-x86_64-with-debian-9.0

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.19 Safari/537.36

XX-Net: 3.3.0

Python Version: 2.7.13

OpenSSL Version: 16.2.0 TLSv1_2 h2:alpn

Status：
Please check your browser proxy setting.
Browser Proxy Setting	Fail
CA status(Download)	Fail

It's work with Firefox browser .

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/5116

**Comment by tannx** [comment]
@jzp820927 
In this case, it didn't worked for me. I have already removed whole XX-net folder and reninstalled it again.
Chrome browser seems changed many from this update.

**Comment by jzp820927** [comment]
如果是浏览器的关系，就换个浏览器试试

**Comment by tannx** [comment]
@jzp820927 yes, using firefox browser now.
