### ISSUE TITLE
再次部署更多帐号失败

### ISSUE THREAD

**Issue by zhailei2014** [XX-net/XX-Net#5164]
![image](https://cloud.githubusercontent.com/assets/8652531/24073303/9ac30824-0c30-11e7-8bd4-85f94665f808.png)

很早之前部署了一个APPID 成功了， 用了很久 今天流量用完了，于是想多部署几个APPID ，结果只有之前那个ID 能部署成功，其他的都失败了，求助。

后面的帐号都是 Send 3次 下面的内容 然后直接跳下个帐号，最后 只成功1 个 其他全部失败

root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'NNX-123123'}

**Comment by zhailei2014** [comment]
问题找到了，没  设置AppID的App引擎

**Comment by jzp820927** [comment]
问题解决了就 close 吧
