### ISSUE TITLE
想提2个关于用户体验的问题

### ISSUE THREAD

**Issue by Jan9th** [XX-net/XX-Net#5166]
有两个问题：
问题1：是否可以增加一个设置，让控制xx net的日志控制台（就是那个类似于tomcat服务器的控制台，不知道如何描述它了）启动时是否显示那个控制台log日志呢，我想若非非正常情况下我们是不需要关注日志输出的。虽然我知道在图标通知那里可以点击后可以把他切换掉让他后台运行，另外一直显示可能会有误操作把他关掉。
问题2：是否可以设置在启动浏览器时增加一个关联启动xx net，我在另外一个基于chrome支持自定义的浏览器中实现了这个关联启动，不过控制台也是默认显示的，需要切换通知图标才能再关闭掉。

![555](https://cloud.githubusercontent.com/assets/23295505/24078741/fb9f4614-0cb0-11e7-9763-eb908b38af96.png)

**Comment by SeaHOH** [comment]
用 start.vbs 启动

**Comment by Jan9th** [comment]
@SeaHOH 多谢，原来是我打开姿势不对，那如果是让浏览器关联启动呢（我用的chrome），可以设置么

**Comment by SeaHOH** [comment]
应该也可以吧， bat 换成 vbs。

**Comment by jzp820927** [comment]
你应该是说的那种 一键整合包 吧。一键启动 chrome，xxnet，并且自动导入证书，配置好代理。
