### ISSUE TITLE
X-Tunnel页面 不刷新

### ISSUE THREAD

**Issue by WispZhan** [XX-net/XX-Net#5167]
---
## 问题内容

X-Tunnel 流量界面在充值之后不会自己刷新，而且不会跟随整个页面刷新。必须推出帐号重新登录之后才会刷新页面。

**Comment by jzp820927** [comment]
不是什么大问题吧

**Comment by WispZhan** [comment]
@jzp820927 不知道的人以为充值了没反映，用户体验不好。

**Comment by jzp820927** [comment]
确实对新人不太友好，反正 X 大回归了，你给他反映下，看他能不能处理下。就是添加个刷新功能，应该不难。

**Comment by Jan9th** [comment]
@jzp820927 是有些问题,X-Tunnel页面显示 请检查浏览器代理设置的错误,之前一直以为不能用,流量一下子给了10g,还不知道那两个appID是不是有效的,要不要转给你些,我只是好奇两者速度有没有差别.

**Comment by jzp820927** [comment]
不用了，我还有流量，而且也快到期了，用不完。
