### ISSUE TITLE
关于\data\downloads\文件夹

### ISSUE THREAD

**Issue by myhead** [XX-net/XX-Net#517]
这里是存放自动更新下载的文件的么？
删除是否有影响？

**Comment by Cat7373** [comment]
可以删除，不会有什么影响的，这个本来该是自动删除的，哪天有空我搞个pull吧。。。

**Comment by myhead** [comment]
多谢！





发件人: Cat73
发送时间: ‎2015‎年‎6‎月‎13‎日, ‎星期六 ‎20‎:‎10
收件人: XX-net/XX-Net
抄送: 吴梓靖





可以删除，不会有什么影响的，这个本来该是自动删除的，哪天有空我搞个pull吧。。。
