### ISSUE TITLE
 您的链接不安全

### ISSUE THREAD

**Issue by jhhuang96** [XX-net/XX-Net#5171]
www.google.com.hk 的管理员未正确配置网站。为避免您的信息被窃，Firefox 没有建立与该网站的连接。

此网站使用了 HTTP 严格传输安全（HSTS）要求 Firefox 只进行安全连接。正因如此，您不能为此证书添加一个例外。
报告此类错误以帮助 Mozilla 识别和拦截恶意站点

www.google.com.hk 使用了无效的安全证书。

证书过期日期为 2017年3月13日 10:18。而当前日期为 2017年3月20日 20:11。

错误代码: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by cdoge** [comment]
我的mac系统，解决方式是点击chrom设置->证书管理->左侧钥匙串有个登录->右侧选中www.google.com.hk证书->双击证书->选中左侧的信任->点开后选择使用此证书->选择始终信任
然后ok了

**Comment by jzp820927** [comment]
证书过期了，删除 data，删除导入浏览器的证书，重启XX，把XX新生成的证书导入系统。

**Comment by qhkingsilk** [comment]
火狐浏览器没有使用系统自带的证书管理工具，所有需要单独，手动到火狐的 首选项 -> 高级 -> 证书 那里重新添加一下XX-Net （比如： XX-Net-3.3.1/data/gae_proxy/CA.crt）的证书到 “证书机构” 里。
