### ISSUE TITLE
请检查代理

### ISSUE THREAD

**Issue by nobShiny** [XX-net/XX-Net#5183]
这几天chrome都没法翻，issues里的方法几乎都试过了，还是不行，代码注释也取消了，证书也重新安装了，自动代理也设置了，不论怎样都是“请检查浏览器代理设置”。大神们求救.... #5116 的办法行不通呀...

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:244
network-status: OK
connected-link: new:8 used:0
worker: h1:13 h2:5
scan-ip-thread-num: 100
ip-quality: 717
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
通过 XX 访问网页的时候，浏览器显示什么？

**Comment by qianzheng0819** [comment]
我也是啊，今天xxnet用不了，昨天还是好的

**Comment by jzp820927** [comment]
先通过 XXNET 访问一个网站，看看浏览器显示什么结果。
然后观察下日志，有误什么报错信息。

**Comment by nobShiny** [comment]
@jzp820927 显示“请检查浏览器代理设置”，3.2.9和3.3.0版本都试了，都是请检查浏览器代理设置。

**Comment by nobShiny** [comment]
@jzp820927 访问google显示“www.google.com 的响应时间过长。”，xxnet主页一直显示“请检查浏览器代理设置”，3.2.9和3.3.0版本都试了，都是请检查浏览器代理设置。

**Comment by ZXJohn** [comment]
相同问题+1，请检查浏览器代理设置，昨天发现的
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.33 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:910
network-status: OK
connected-link: new:1 used:0
worker: h1:16 h2:0
scan-ip-thread-num: 50
ip-quality: 219
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false，

**Comment by jzp820927** [comment]
如果显示 显示“www.google.com 的响应时间过长。应该是 IP 的问题。

**Comment by nobShiny** [comment]
@jzp820927 那请问有什么解决之道吗？谢谢

**Comment by jzp820927** [comment]
也就是没有可用 IP，如果一直不行的话，那就删除 data，重新扫描。

**Comment by LySnake** [comment]
我最近无奈重装了系统，重新配置 ，使用最新的3.2.9，也用过3.2.8，删除data后，重新扫描IP，在XX-NET配置页，显示扫描IP，要等待约半小时，但到了这一步，实际扫描时间不到3分钟，IP数不到10个。而如果使用以前使用的data目录，但IP不稳定，使用google search，有时可以，有时不可以。

**Comment by nobShiny** [comment]
@jzp820927 重新搜索ip后可以用了，只是速度比较慢，我再去多搜集一些有效ip吧，谢大神解答。

**Comment by LySnake** [comment]
@nobShiny 我是重新搜索IP，问题是不是慢不慢的问题，而是只扫描IP不到3分钟 ，从而IP数少

**Comment by LySnake** [comment]
我的问题算是有结果了。虽然删除data目录后，重新启动xx-net，会重新扫描IP，但确实扫描时间很短，不到3分钟，扫描到的IP数少到1到10个之间，但后续有自动扫描，随着XX-NET启动时间越长，扫描到更多的IP可用。到现的5小时过去了：
总IP数	440
剩余数	0
有效IP数	197

**Comment by jzp820927** [comment]
只扫描IP不到3分钟？不太明白什么意思，XX 是会一直不停扫描的，除非你把 XX 关了，不然扫描是不会停止的。

**Comment by jzp820927** [comment]
能用就行了，其他问题就别较真了。

**Comment by LySnake** [comment]
嗯，这时，好像可以直接在chrome里下插件了

**Comment by jzp820927** [comment]
没问题就行。
