### ISSUE TITLE
本地网络状态unknown问题

### ISSUE THREAD

**Issue by The-Earth** [XX-net/XX-Net#5189]
### 问题描述
启动XX-net之后，本地网络状态unknown，无法正常翻墙。排查网络连接未发现问题，不通过XX-Net的网络连接全部正常。版本为最新稳定版：3.2.9 未使用测试版。退出XX-Net重试无效。

### 诊断信息
     XX-Net Status:

     sys-platform: AMD64, Windows-10-10.0.14393
     os-system: Windows
     os-version: 10.0.14393
     os-release: 10
     os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
     architecture: 32bit,WindowsPE
     browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
     Chrome/57.0.2987.110 Safari/537.36
     xxnet-version: 3.2.9

     python-version: 2.7.11
     openssl-version: 16.0.0 TLSv1_2 h2:alpn

     ipv6-status: 0
     gws-ip-num: total:3000 good:2154
     network-status: unknown
     connected-link: new:0 used:0
     worker: h1:2 h2:0
     scan-ip-thread-num: 44
     ip-quality: 186
     is-idle: 0
     block-stat: OK
     proxy_state: OK
     ca_state: OK
     Appid_Working: true
     Appids_Out_Of_Quota: false
     Appids_Not_Exist: false
     Using_Public_Appid: false

## 日志
日志呈现如下状况：

    Mar 24 16:32:08.686 - [DEBUG] 49.231.58.14 fail:timeout('timed out',)
    Mar 24 16:32:08.686 - [DEBUG] report_connect_fail:49.231.58.14
    Mar 24 16:32:08.686 - [DEBUG] get ip:1.255.22.206 t:377
    Mar 24 16:32:08.746 - [DEBUG] 182.79.251.158 fail:timeout('timed out',)
    Mar 24 16:32:08.746 - [DEBUG] report_connect_fail:182.79.251.158
    Mar 24 16:32:08.746 - [DEBUG] get ip:111.84.224.22 t:269
    Mar 24 16:32:08.786 - [DEBUG] 119.149.188.76 fail:timeout('timed out',)
    Mar 24 16:32:08.786 - [DEBUG] report_connect_fail:119.149.188.76
    Mar 24 16:32:08.786 - [DEBUG] get ip:124.40.230.46 t:276
    Mar 24 16:32:08.842 - [DEBUG] 203.233.18.22 fail:timeout('timed out',)
    Mar 24 16:32:08.842 - [DEBUG] report_connect_fail:203.233.18.22
    Mar 24 16:32:08.842 - [DEBUG] get ip:118.98.30.100 t:279
    Mar 24 16:32:08.908 - [DEBUG] 1.255.33.92 fail:timeout('timed out',)
    Mar 24 16:32:08.908 - [DEBUG] report_connect_fail:1.255.33.92
    Mar 24 16:32:08.908 - [DEBUG] get ip:223.27.237.19 t:286
    Mar 24 16:32:09.060 - [DEBUG] 49.231.58.155 fail:timeout('timed out',)
    Mar 24 16:32:09.060 - [DEBUG] report_connect_fail:49.231.58.155
    Mar 24 16:32:09.060 - [DEBUG] get ip:125.235.36.45 t:378

**Comment by jzp820927** [comment]
看样子你的 带宽 有可能是 连接 google IP 比较困难。

**Comment by The-Earth** [comment]
带宽？能具体解释一下吗？

**Comment by jzp820927** [comment]
打反了，是 宽带，我的意思是说，你的网络环境不太容易连接 google 的 IP

**Comment by The-Earth** [comment]
试了几个不同的网络连接后，发现确实是这样（诶校园网

**Comment by jzp820927** [comment]
没有可用 IP，这个就无解了。校园网的话，是不是可以试试开启 IPV6？

**Comment by The-Earth** [comment]
不行，这里不支持IPv6

**Comment by jzp820927** [comment]
居然还有不知道 IPV6 的校园网，第一次遇到。
