### ISSUE TITLE
chrome的配置页面一直显示请检查代理设置，但功能一切正常，proxyswitchyomega的版本是2.3.5，照着wiki设置好了，手动导入证书后也没解决

### ISSUE THREAD

**Issue by OneCanType** [XX-net/XX-Net#5191]
##XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:509
network-status: OK
connected-link: new:2 used:0
worker: h1:8 h2:22
scan-ip-thread-num: 100
ip-quality: 397
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by OneCanType** [comment]
另外用之前用火狐配置一切正常，没有上述情况

**Comment by UltraDWS** [comment]
参考#5116，记得生成新证书的时候使用管理员身份运行start.bat，提升证书安装权限，避免出现UAC重复检测。

**Comment by jzp820927** [comment]
如果能正常使用，只是显示问题的话，可以试试 Ctrl+F5 强制刷行

**Comment by OneCanType** [comment]
@UltraDWS 解决了，感谢

**Comment by Jan9th** [comment]
解决了,就附上解决方法关了吧,开着的问题好多

**Comment by UltraDWS** [comment]
不客气，很高兴能帮到你哈哈

2017-03-25 8:18 GMT+08:00 OneCanType <notifications@github.com>:

**Comment by OneCanType** [comment]
closes #5191

**Comment by OneCanType** [comment]
close #1591
