### ISSUE TITLE
start.vbs运行错误

### ISSUE THREAD

**Issue by qhfls** [XX-net/XX-Net#52]
双击start.vbs后显示
![2015-03-08_193107](https://cloud.githubusercontent.com/assets/721889/6545594/d66b035e-c5c9-11e4-85b8-44821b4ec143.png)
系统信息
![2015-03-08_193153](https://cloud.githubusercontent.com/assets/721889/6545596/dfa8ff70-c5c9-11e4-992d-b6c75d680199.png)

**Comment by xxnet** [comment]
试了一下，是路径中存在空格造成的，你的目录中"Program Files"中有一个空格。
谢谢反馈，你可以先用start.lnk 或 start.bat，或者创建的桌面快捷方式。
我下一个版本中修复。

**Comment by streamgo** [comment]
的确有此问题。

**Comment by xxnet** [comment]
1.3.1 已经修复，谢谢反馈。
