### ISSUE TITLE
登陆google云端硬盘时，在左下角弹出提示：“服务器发生错误，请稍后重试”。如果用自由门代理就没有这样的问题

### ISSUE THREAD

**Issue by langbao** [XX-net/XX-Net#5201]
状态

属性	值
本地网络状态	OK
IP数量	67
IP延迟	809
连接池(帮助)	9 / 37
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	50
屏蔽状态 (帮助)	OK
配置

属性	值
XX-Net Version	2.9.4
Python Version	2.7.11
System Platform	AMD64, Windows-10-10.0.14393
OS System	Windows
OS Version	10.0.14393
OS Release	10
OS Detail	Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

登录其他网站一切正常。就是登陆google云端硬盘时，在左下角弹出提示：“服务器发生错误，请稍后重试”。如果用自由门代理就没有这样的问题。

**Comment by jzp820927** [comment]
估计应该是一些资源没有加载成功，需要 F12 分析一下，看看是什么域名。

**Comment by myjlpt** [comment]
最近GOOGLE扩展商店下载都错误的。更换蓝灯代理就正常下载.原因未知

**Comment by jzp820927** [comment]
不光是扩展，包括 chrome 升级也不行了，是因为google 官方屏蔽了 中国用户的 chrome 升级和扩展下载。和 功夫网 无关。

**Comment by myjlpt** [comment]
@jzp820927 表示Ubuntu下，chrome自主升级正常，已经57版本，还是自动升上去的，害我降级重装。并关闭相关源，之后正常不升级

**Comment by langbao** [comment]
有没有人和我的问题是一样的？

**Comment by jzp820927** [comment]
反正我这边不走代理是不能升级的。

**Comment by Eri5Ch** [comment]
![chrome](https://cloud.githubusercontent.com/assets/12391921/24359022/9e5455b8-1335-11e7-82ce-aa130b500dc6.JPG)
第一次看到这种错误

**Comment by langbao** [comment]
问题还是没有解决啊！怎么用xx-net代理登录谷歌云端硬盘就出错呢？用自由门就正常。

**Comment by jzp820927** [comment]
@Eri5Ch 因为 google 官方屏蔽了 中国大陆 用户的 chrome 升级和插件下载。

**Comment by langbao** [comment]
换了个版本的xx-net3.3.0后，问题解决了！关闭主题。
