### ISSUE TITLE
震惊 pac模式出现无法解决的问题

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#5211]
平时用安装在路由器上的XX-NET代理上网  昨天手贱在电脑上又安装了一个XX 然后自此之后 把系统代理设置为PAC模式时（已经改为路由器的PAC地址了） 电脑上不再能翻墙 这时候把系统代理设置为手动设置代理那项 翻墙是没问题的 只有系统代理的PAC模式不能翻 用SwitchyOmega也是可以翻的 那么 请问各位大大怎么修复

**Comment by jzp820927** [comment]
是不是你在电脑上安装的 XXNET，修改系统 PAC 地址为电脑端的 PAC 了。

**Comment by sky123456789sky** [comment]
@jzp820927 已经改为路由的PAC地址了 还是不行的 然后再开电脑上XX的系统PAC 没毛病。。。。不知道怎么可以彻底清除代理设置 电脑上的XX一定修改了某个设置是我们不知道的

**Comment by jzp820927** [comment]
和 PAC 相关的，也就 PAC 地址了，也没什么其他设置了。

**Comment by sky123456789sky** [comment]
可以正常打开 并且手机什么的是可以用PAC模式的

**Comment by jzp820927** [comment]
那把电脑上打开的 PAC 的内容贴出来看看。

**Comment by sky123456789sky** [comment]
两个都打开对比过 除了代理地址不同外 一模一样 一个是路由地址 一个是127.0.0.1

**Comment by sky123456789sky** [comment]
两个都打开对比过 除了代理地址不同外 一模一样 一个是路由地址 一个是127.0.0.1

**Comment by jzp820927** [comment]
如果 PAC 里面的 代理地址正确无误，这个问题就有点诡异了，直接设置 IP 和端口的全局代理没问题麽？

**Comment by sky123456789sky** [comment]
完全没问题.....注册表什么的都搞了 也不见起作用 pac不知道哪里抽筋 换浏览器也是不行的 一定是系统被XX更改了什么地方 但是我们不知道

**Comment by SeaHOH** [comment]
用 IE 打开 http://路由地址:8086/proxy.pac，头几行贴出来看看，还有 IE 的代理设置页面截图。

**Comment by shakesnake** [comment]
@SeaHOH GA的pac模式我没成功过一次

**Comment by jzp820927** [comment]
PAC 只要内容格式没错，代理地址正确，监听设置正确，应该不会出问题的。

**Comment by shakesnake** [comment]
也许是我电脑的问题吧,pac 开启pac模式在浏览器底部闪过 "正在解析pac地址" 然后一直显示"无法连接网络",怪了,127.0.0.1需要解析么

**Comment by SeaHOH** [comment]
@shakesnake 
确认 pac 模式设置里面的主机地址是 `127.0.0.1` 吗？如果是，那么换个浏览器试一下。
