### ISSUE TITLE
xx-net在Ubuntu下的代理问题

### ISSUE THREAD

**Issue by huiwenzhang** [XX-net/XX-Net#5215]
你好：
按照本项目的wiki，我在widows上利用xx-net和chrome+SwitchOmega，一切正常。但是在Ubuntu下，启动xx-net后，显示代理有问题。SwitchOmega下面只有auto switch而没有xx-net auto switch 或者x-tunnel auto witch，我觉得是我的浏览器没有识别到xx-net，请问怎么解决？
谢谢

**Comment by jzp820927** [comment]
导入备份文件了嘛？

**Comment by myjlpt** [comment]
直接复制WINDOWS下的XXNET到UBUNTU就可以了。终端运行./start; 开启其设置，开机启动，或者 终端运行sudo /home/username/xxnet/xx_net.sh start 以开机启动就好。

**Comment by huiwenzhang** [comment]
@myjlpt  Ok, xiexie!
