### ISSUE TITLE
在全局PAC智能代理模式下在edge中打不开设置

### ISSUE THREAD

**Issue by cv0cv0** [XX-net/XX-Net#5222]
必须切换为GAEProxy。

**Comment by shakesnake** [comment]
翻墙推荐chrome和firefox, edge现在,怎么说呢 还没成熟 有些bug也很正常

**Comment by jzp820927** [comment]
LS 正解

**Comment by cv0cv0** [comment]
Firefox和chrome都没edge好用。

**Comment by jzp820927** [comment]
赶脚用 google 自家的软件配合 google 自家的服务最靠谱。

**Comment by JerryLi1997** [comment]
Windows Apps 在默认状态下无法访问本地回环端口。

管理员cmd 输入 CheckNetIsolation LoopbackExempt -a -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe 试试。

**Comment by yangshuochina** [comment]
我有个小问题请教一下大家，在全局PAC智能代理模式下，XX-NET会影响Adobe软件修改的hosts文件，让Adobe的离线激活反弹，有没有好的方法防止激活反弹？

**Comment by jzp820927** [comment]
pac 和 hosts 没有任何关系麽，不知道你说的反弹，具体是什么情况

**Comment by yangshuochina** [comment]
Adobe大部分软件安装的时候需要在hosts中加入下列的内容
127.0.0.1 lmlicenses.wip4.adobe.com
127.0.0.1 lm.licenses.adobe.com
阻止Adobe的程序（例如Acrobat或者Photoshop）访问Adobe的license服务器，如果我使用全局通过GAEProxy代理或者全局PAC智能代理模式，则修改的hosts文件失效，Adobe的程序能通过XX-NET访问Adobe的license服务器，程序又会弹出序列号失效或者过期的提示。

**Comment by cv0cv0** [comment]
@yangshuochina 这个好像没办法。

**Comment by yangshuochina** [comment]
看来只能通过防火墙阻止访问license服务器了，谢谢。😁

2017-04-25 10:35 GMT+08:00 cv0cv0 <notifications@github.com>:

**Comment by jzp820927** [comment]
用全局的肯定不行，用 pac 应该没事，难道 pac 文件里面有  lmlicenses.wip4.adobe.com 和 lm.licenses.adobe.com 走代理的规则。

**Comment by eve8861** [comment]
想问问lz怎么在edge中用xxnet，我也喜欢edge但无奈不会用它fq

**Comment by jzp820927** [comment]
设置系统代理就行，可能需要破解 本地环回地址的限制
