### ISSUE TITLE
教育网用户无法启用ipv6

### ISSUE THREAD

**Issue by maxweIt** [XX-net/XX-Net#5225]
如上，可以确认的是ipv6是正常的(不开启代理时可以通过hosts直接访问ipv6.google.com），不清楚原因。电脑设置了isatap隧道，尝试过关闭隧道也无效。电脑修改了系统hosts文件。谢谢

**Comment by jzp820927** [comment]
应该是 XX 内置的 IPV6 都被封了，可以试试替换内置的 IPV6 数据试试。
