### ISSUE TITLE
选择pac模式就出现失败,只能选择gaeproxy模式,请问怎么回事

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#5226]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2970 good:1467
network-status: OK
connected-link: new:5 used:0
worker: h1:28 h2:11
scan-ip-thread-num: 30
ip-quality: 83
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
没遇到过类似问题，你说的失败，有什么错误提示么？
