### ISSUE TITLE
【求助】在mac上面xx-net如何正确退出以及代理模式

### ISSUE THREAD

**Issue by cell13** [XX-net/XX-Net#5229]
## 问题内容

1. 在mac上面xx-net如何正确退出以及代理模式
2. mac版本：Sierra 10.12
3. XX-Net版本：3.2.9

---
## 问题查询

1.  我在mac上面按照使用说明，点击了start文件，xx-net作为后台程序正常启动
2.  现在我想将xx-net停止该如何停止
3.  使用netstat查看进程号，但是在mac上面不支持显示进程号（-p参数不被支持），查看启动脚本，看到启动的命令是：
`${PYTHON} code/${VERSION}/launcher/start.py`
4. 查看了进程，存在python进程，这个问题基本解决了
5. 最后想了解下xx-net的默认代理模式

---
##致谢

如果有好的方法，请不吝赐教。

**Comment by cell13** [comment]
XX-Net位于顶栏，已经找到了问题的解决办法。

**Comment by jzp820927** [comment]
解决了就 close 吧
