### ISSUE TITLE
设置私有APPID，google已经授权但是没有效果

### ISSUE THREAD

**Issue by abaisa** [XX-net/XX-Net#5232]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:75 good:37
network-status: OK
connected-link: new:4 used:0
worker: h1:12 h2:9
scan-ip-thread-num: 50
ip-quality: 685
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
请问这是什么问题？

**Comment by abaisa** [comment]
已经处理好了

**Comment by jzp820927** [comment]
不分享一下解决方法麽？也可以帮忙后面的人。
