### ISSUE TITLE
【求助】无法启动程序

### ISSUE THREAD

**Issue by FriliShuiS** [XX-net/XX-Net#5236]
Apr 05 01:10:18.475 - [INFO] use build-in openssl lib
Apr 05 01:10:18.477 - [INFO] start XX-Net 3.2.9
Apr 05 01:10:18.477 - [DEBUG] start confirm_xxnet_exit
Apr 05 01:10:19.478 - [DEBUG] good, xxnet:8087 cleared!
Apr 05 01:10:20.481 - [DEBUG] good, xxnet:8085 clear!
Apr 05 01:10:20.482 - [DEBUG] finished confirm_xxnet_exit
Apr 05 01:10:20.848 - [INFO] SSL use version:TLSv1_2
Apr 05 01:10:21.657 - [INFO] OpenSSL support alpn
Apr 05 01:10:21.659 - [INFO] load ip range file:D:\Software\NetworkSoftware\XX-Net\code\default\gae_proxy\local\ip_range.txt
Apr 05 01:10:21.682 - [INFO] detected Win10, enable connect concurrency control, interval:40
Apr 05 01:10:21.688 - [INFO] load google ip_list num:608, gws num:608
Apr 05 01:10:21.701 - [INFO] OpenSSL support alpn
Apr 05 01:10:21.701 - [DEBUG] get ip:203.248.210.53 t:171
Apr 05 01:10:21.704 - [DEBUG] get ip:113.171.244.110 t:203
Apr 05 01:10:21.710 - [DEBUG] ## GAEProxy set keep_running: True
Apr 05 01:10:21.711 - [INFO] ------------------------------------------------------
Apr 05 01:10:21.711 - [INFO] Python Version     : 2.7.11
Apr 05 01:10:21.711 - [INFO] OS                 : Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Apr 05 01:10:21.711 - [INFO] Listen Address     : 127.0.0.1:8087
Apr 05 01:10:21.711 - [INFO] GAE APPID          :
Apr 05 01:10:21.711 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Apr 05 01:10:21.712 - [INFO] ------------------------------------------------------
Apr 05 01:10:21.716 - [INFO] server 127.0.0.1:8087 started.
Apr 05 01:10:21.716 - [INFO] server 127.0.0.1:8086 started.
Apr 05 01:10:21.808 - [INFO] module gae_proxy started
Apr 05 01:10:21.808 - [INFO] start gae_proxy time cost:1315 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Apr 05 01:10:21.840 - [INFO] use config_path:D:\Software\NetworkSoftware\XX-Net\data\x_tunnel\client.json
Apr 05 01:10:21.841 - [INFO] Use proxy:127.0.0.1:8087
Apr 05 01:10:21.841 - [DEBUG] x-tunnel no account
Apr 05 01:10:21.842 - [WARNING] x-tunnel session not start
Apr 05 01:10:21.842 - [ERROR] bind to 127.0.0.1:1080 fail:error(10013, '')
Exception in thread Thread-61:
Traceback (most recent call last):
  File "D:\Software\NetworkSoftware\XX-Net\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Software\NetworkSoftware\XX-Net\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Software\NetworkSoftware\XX-Net\code\default\x_tunnel\start.py", line 19, in main
    client.main()
  File "D:\Software\NetworkSoftware\XX-Net\code\default\x_tunnel\local\client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "D:\Software\NetworkSoftware\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "D:\Software\NetworkSoftware\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "D:\Software\NetworkSoftware\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(10013, '')

**Comment by jzp820927** [comment]
1080 端口占用，你是不是同时运行了 SS客户端。

**Comment by FriliShuiS** [comment]
好的解决了，是mobile_backup_status_server这个程序占用了1080端口，谢谢了
