### ISSUE TITLE
谷歌经常提示504 GAEProxy Proxy Time out，其他网站正常

### ISSUE THREAD

**Issue by Neofly1992** [XX-net/XX-Net#5249]
win10  chrome57稳定版 + xx-net3.2.9稳定版
已经配置个人的appid
使用谷歌时提示504 GAEProxy Proxy Time out
不是一定会出现这东西，不过确实是经常
其他网站没有任何问题

**Comment by jzp820927** [comment]
只有 www.google.com 这一个网站？

**Comment by Neofly1992** [comment]
不排除是谷歌用的远比其他网站多的可能行，不过目前其他网站确实没有遇到这样的问题。

**Comment by Neofly1992** [comment]
又试了下，在谷歌出问题的时候访问youtube没有问题。特别奇怪的一点是，就在刚才完成先进入google.com再搜索就没有问题，但是如果直接通过地址栏搜索就出现了 504 GAEProxy Proxy Time out

**Comment by SeaHOH** [comment]
要看地址栏搜索原始请求的地址，可能比较特别。如果是火狐可以自定义。

**Comment by Neofly1992** [comment]
搜索的时候是正常的地址，然后过一会前面多了https://ipv4.google.com/sorry/index?continue=这一串，并且提示504 GAEProxy Proxy Time out

**Comment by SeaHOH** [comment]
地址栏搜索的原始请求如果比较特别，那么很可能会被重定向，你在地址栏是看不出来的。
除非知道原始请求地址，一般还是不要用地址栏搜索的好。
如果是火狐倒是可以自定义地址栏搜索，其它浏览器我不清楚，但可以用搜索类扩展替代。

**Comment by jzp820927** [comment]
跳到 ipv4 肯定会出问题。之前有 issues 讨论过，还分享过解决方法。直接地址栏手动输入 https://www.google.com/ncr 回车后，再搜索试试。

**Comment by SeaHOH** [comment]
他这个不单纯是跳转的问题，楼主应该是主用地址栏快捷搜索，这个请求地址才是关键。

**Comment by Neofly1992** [comment]
嗯，目前出现问题99%都是地址栏快捷搜索的时候。
不过总感觉，谷歌公司自己的浏览器不会连默认搜索都搞不对吧…………

**Comment by jzp820927** [comment]
地址栏默认搜索引擎 URL 是可以修改了，可以试试自己修改。
