### ISSUE TITLE
ios下需要google账号登陆的app都不工作

### ISSUE THREAD

**Issue by INNNNG** [XX-net/XX-Net#525]
ios下需要google账号登陆的app都不工作

**Comment by 12c312312ceqsdcace123** [comment]
ios 谷歌的app 登陆界面 就会有很多这类提示 求解!

**Comment by xxnet** [comment]
这个日志是证书被客户端拒绝的意思。
IOS需要导入GoAgent的证书，具体怎么导入，没有试过。

2015-06-25 3:07 GMT+08:00 12c312312ceqsdcace123 <notifications@github.com>:

**Comment by 12c312312ceqsdcace123** [comment]
导入了 网页浏览没问题 就app里有问题
xxnet <notifications@github.com>于2015年6月25日 週四上午10:56写道：

**Comment by 12c312312ceqsdcace123** [comment]
删证书 导入新证书 也一样
Safari 访问正常 很奇怪
STS <tingpine@gmail.com>于2015年6月25日 週四上午11:08写道：

**Comment by xxnet** [comment]
哪些app有问题？哪些app没问题？

要收集个列表，看看GoAgent在IOS上是否合适。
如果太多APP有问题，就不要再这个方向上折腾了。

在 2015年6月25日 上午11:14，12c312312ceqsdcace123 <notifications@github.com>写道：

**Comment by 12c312312ceqsdcace123** [comment]
google所有需要登录的app都不行吧
STS <tingpine@gmail.com>于2015年6月25日 週四上午11:14写道：

**Comment by xxnet** [comment]
导入证书都无效吗？

在 2015年6月25日 下午12:21，12c312312ceqsdcace123 <notifications@github.com>写道：

**Comment by 12c312312ceqsdcace123** [comment]
证书应该没问题 safari登陆需要google账号都是正常的

**Comment by 12c312312ceqsdcace123** [comment]
用邮箱回复居然  居然显示邮箱了!!

**Comment by 12c312312ceqsdcace123** [comment]
@xxnet 证书应该没问题 safari登陆需要google账号都是正常的

**Comment by xxnet** [comment]
所以怀疑手机上用GoAgent本身这个模式有问题。
  关键点是：导入到手机系统的证书，到了App那里没有起作用。
  多试试，如果有问题，那么把GoAgent移植到手机平台，就可以放弃了。

2015-06-25 14:33 GMT+08:00 12c312312ceqsdcace123 <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet @12c312312ceqsdcace123 
我测试的情况是这样的，自己的无线局域网，iphone连接 192.168.X.X:对应端口 ，导入CA之后，只有safari能正常访问https网址。因为导入CA也是用safari完成的，因此怀疑这个证书库是safari自己的，与其他的应用无关。

**Comment by xxnet** [comment]
请参考这里：
https://blog.httpwatch.com/2013/12/12/five-tips-for-using-self-signed-ssl-certificates-with-ios/

里面提到，不要用Safari 去导入证书，而是发邮件附件，在手机的邮件客户端中去导入证书。

在 2015年6月25日 下午5:38，simonasd <notifications@github.com>写道：

**Comment by 12c312312ceqsdcace123** [comment]
@xxnet 邮件附件 并没有用!!

**Comment by tigeryangjin** [comment]
我是发邮件附近，然后在手机上打开邮件附件导入，但是APP登录仍然会出现问题：SSL验证失败什么的。facebook、twitter、youtube都不行。
