### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by EthanLuu** [XX-net/XX-Net#5254]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.6 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:267 good:71
network-status: OK
connected-link: new:2 used:0
worker: h1:8 h2:2
scan-ip-thread-num: 50
ip-quality: 723
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by EthanLuu** [comment]
状态

属性	值
本地网络状态	OK
IP数量	81
空闲	0
IP延迟	572
连接池(帮助)	新:1 h1:6 h2:5
浏览器代理设置	Fail
CA证书状态(下载)	Fail
扫描IP线程数(设置)	50
屏蔽状态(帮助)	OK
配置

属性	值
监听代理	127.0.0.1:8087
PAC自动代理地址	http://127.0.0.1:8086/proxy.pac
IPv6	禁用
Appid

属性	值
当前工作AppID	trusty-pixel-164004
系统版本

属性	值
XX-Net Version	3.3.0
Python Version	2.7.11
OpenSSL Version	16.0.0 TLSv1_2 h2:alpn
System Platform	AMD64, Windows-10-10.0.14393
OS System	Windows
OS Version	10.0.14393
OS Release	10
OS Detail	Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.6 Safari/537.36

**Comment by EthanLuu** [comment]
急~~

**Comment by jzp820927** [comment]
先在浏览器测试下 XXNET 能不能用？如果不能用，浏览器显示什么？

**Comment by EthanLuu** [comment]
不能用
浏览器代理设置	Fail
CA证书状态(下载)	Fail

**Comment by trystudy** [comment]
安卓系统毕业用firefox浏览器吗？ 用chrome不可以吗？
proxy droid 如何设置？

**Comment by EthanLuu** [comment]
无法访问此网站

网址为 http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/%3Fgws_rd%3Dcr&ust=1491657987334758&usg=AFQjCNEklrDbJl_qsYuvbhCA3MxzsScYGw 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONNECTION_ABORTED

**Comment by jzp820927** [comment]
什么浏览器都可以用，没什么限制

**Comment by EthanLuu** [comment]
可以搜索 youtube也能访问 但是放不了视频
Appid

属性	值
当前工作AppID	trusty-pixel-164004

appid也已经配置好了

**Comment by heroshit** [comment]
你装了flash插件了么

**Comment by jzp820927** [comment]
就是视频放不了，其他都没问题？

**Comment by EthanLuu** [comment]
flash插件装了 然而现在问题来了 
我把之前改的hosts改回来之后 发现连youtube和google都不能上了
似乎xx-net是完全没办法用

**Comment by EthanLuu** [comment]
无法访问此网站

www.google.com 的响应时间过长。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

**Comment by EthanLuu** [comment]
突然发现重新下载之后 竟然能用了 
还是谢谢了 @jzp820927

**Comment by jzp820927** [comment]
我去，这问题太奇葩了

**Comment by langbao** [comment]
我觉得主要还是证书问题。

**Comment by Eri5Ch** [comment]
同样的错误 pac模式 ie可以顺利出去 chrome打不开墙外网站,提示连接超时, chrome打开xx设置页提示浏览器代理设置

**Comment by jzp820927** [comment]
你的意思，IP + 端口的全局模式没问题？就 PAC 有问题？

**Comment by Eri5Ch** [comment]
原来是选择pac模式后 并不需要拓展 chrome 就可以直接翻出去 现在是需要先启用switchsharp后才可以 否则 chrome就提示 检查浏览器代理设置

**Comment by jzp820927** [comment]
switchsharp 是用到 pac？还是他自己的规则啊？

**Comment by Eri5Ch** [comment]
订阅gfw规则 然后自动模式

**Comment by jzp820927** [comment]
难道是 pac 的问题？浏览器能不能打开 pac 的地址？

**Comment by Eri5Ch** [comment]
不知道啊 浏览器怎么打开pac地址? xx在pac模式下 ie可以直接翻出去的

**Comment by jzp820927** [comment]
就是说，叫你浏览器打开 http://127.0.0.1/proxy.pac

**Comment by Eri5Ch** [comment]
ie和chrome均打不开

**Comment by jzp820927** [comment]
状态页，贴出来看看

**Comment by ilvegithub** [comment]
@Eri5Ch 你的chrome版本多少 还有系统版本

**Comment by Eri5Ch** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:675
network-status: OK
connected-link: new:4 used:0
worker: h1:18 h2:8
scan-ip-thread-num: 50
ip-quality: 266
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Eri5Ch** [comment]
@ilvegithub 又验证了一下 pac模式chrome不启用switchysharp是不能访问墙外网站的, 但ie可以,switchsharp版本是2.4.5,启用之后 chrome 也可以访问了

**Comment by Eri5Ch** [comment]
访问pac显示这个 chrome和ie均不能访问
![Uploading Capture.1JPG.JPG…]()

**Comment by jzp820927** [comment]
截图看不到。

**Comment by Eri5Ch** [comment]
图传不上去 提示错误
![capture 1jpg](https://cloud.githubusercontent.com/assets/12391921/24996684/6113015c-2066-11e7-8da5-1de0e62ccaa1.JPG)
![Uploading Capture.1JPG.JPG…]()
![Uploading Capture.1JPG.JPG…]()

**Comment by SeaHOH** [comment]
加端口

**Comment by Eri5Ch** [comment]
加了端口一样打不开...

**Comment by SeaHOH** [comment]
IE 不都正常吗，难道是防火墙？也不像，你确定 IE 用的是 pac？
pac 优先级最高，如果同时设置了其它代理设置，pac 又无效，那么实际使用的是其它代理设置。

**Comment by jzp820927** [comment]
我也觉得 pac 一般不容易出问题。

**Comment by czl0325** [comment]
XX-Net Status:

sys-platform: x86_64, Darwin-16.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
os-release: 16.5.0
os-detail: Release:10.12.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30
xxnet-version: 3.3.0

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:2831 good:1162
network-status: OK
connected-link: new:2 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 0
ip-quality: 150
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
LS 什么问题？请详细描述。

**Comment by summerIwinter** [comment]
浏览器代理设置	Fail
CA证书状态(下载)	Fail
状态显示请检查代理浏览器设置
但是能进谷歌，不知道是什么问题

**Comment by jzp820927** [comment]
除了谷歌，其他网站呢？试试 ctrl+F5
