### ISSUE TITLE
另一种在安卓上运行xx-net方法

### ISSUE THREAD

**Issue by THLIVSQAZ** [XX-net/XX-Net#5257]
xx-net大大的安卓版是python-android,在未出第二版前，曾想过python-android+xx-net,无奈在termux找不到python-OpenSSL，后来转用gnuroot，在debian arm源中找到了这个软件包，xx-net可以运行了，简要叙述过程
1.初始化gnuroot debian
![1491706924173](https://cloud.githubusercontent.com/assets/25531652/24834350/06abcb34-1ca8-11e7-91c6-99e89b484d90.jpg)
2.安装python环境
![1491706923030](https://cloud.githubusercontent.com/assets/25531652/24834367/9444a4fc-1ca8-11e7-87c0-e323ca740223.jpg)

3.安装python-openssl
![1491706920253](https://cloud.githubusercontent.com/assets/25531652/24834371/a474fcbe-1ca8-11e7-85bd-b0d852a190d4.jpg)
4.拷贝
![1491706921290](https://cloud.githubusercontent.com/assets/25531652/24834375/b9f1d6b6-1ca8-11e7-9791-801ae455c921.jpg)
5.执行
![1491706921891](https://cloud.githubusercontent.com/assets/25531652/24834382/ccf30618-1ca8-11e7-920a-b04a5224993a.jpg)
web控制页面
![1491706929419](https://cloud.githubusercontent.com/assets/25531652/24834387/e1dd1ed8-1ca8-11e7-8369-4330903e2ac6.jpg)

**Comment by THLIVSQAZ** [comment]
部署有反应，但会卡住不动，估计是无法弹窗的原因

**Comment by jzp820927** [comment]
应该写到 wiki 去。

**Comment by sakurasee** [comment]
最新的3.3.1版你试过么 @THLIVSQAZ

**Comment by THLIVSQAZ** [comment]
xxnetfana的3.3.1也可以运行，除了部署弹不了窗问题

**Comment by nextgental** [comment]
@THLIVSQAZ 第五步执行的时候提示 permission denied 以root用户运行
系统为 android 6.0.1 miui 8
这是为什么

**Comment by THLIVSQAZ** [comment]
@nextgental  start是个脚本，给它加个执行权限 chmod a+x start
@trystudy  主要写给那些xx-net安卓版无法运行的手机折腾

**Comment by nextgental** [comment]
@THLIVSQAZ 明白了
我手机打开 xx-net 安卓版显示 loading 一片空白 无法运行
所以试试这个

**Comment by nextgental** [comment]
@THLIVSQAZ  可以运行了
但是浏览器打开所有网站,除了 127.0.0.1:8085 显示 ERR_NAME_NOT_RESOLVED
我没改过dns
怎么回事??

**Comment by nextgental** [comment]
还有,为什么运行 ./start 之后 目录下的 xx_net.sh 不见了
然后退出软件时弹出 vnc login error 
gnuroot debian 有`bug吧

**Comment by THLIVSQAZ** [comment]
@nextgental  什么浏览器，wifi代理设置的是什么？我这边访问127.0.0.1：8085正常,没测过gnuroot debian的vnc，x太不美观了

**Comment by THLIVSQAZ** [comment]
系统和你的一样，安卓6.0.1 @nextgental

**Comment by nextgental** [comment]
我自己尝试解决吧 @THLIVSQAZ

**Comment by roc1010kmt** [comment]
樓主用的這個輸入命令的是什麼app？

**Comment by theratlesnake** [comment]
好像很复杂的样子，另外，为什么我看到的图片显示不全？

**Comment by THLIVSQAZ** [comment]
@roc1010kmt  键盘吗？黑客键盘，横屏时有ESC和Ctrl键，vim操作很方便

**Comment by THLIVSQAZ** [comment]
@theratlesnake 其实也不难，就几个插件罢了

**Comment by CHN008** [comment]
这个先收藏了! :+1:

**Comment by roc1010kmt** [comment]
@THLIVSQAZ 不是鍵盤，這個顯示命令行的是什麼app？

**Comment by THLIVSQAZ** [comment]
#6028

**Comment by roc1010kmt** [comment]
第4步拷貝是幹什麼用的？不能手動考到手機嗎？

**Comment by roc1010kmt** [comment]
那個電腦形狀的xterm是幹什麼用的？
