### ISSUE TITLE
XX-mini 1.3.0 发布 兼 XX-mini 安卓使用说明

### ISSUE THREAD

**Issue by nextgental** [XX-net/XX-Net#5259]
其实，研究xx-net 的初衷就是为了在安卓系统上免费翻墙，如今已达到目的
感谢各位开发者作的贡献
有些在xx-net 评论区的五毛，自己不贡献代码，见人就咬，我最看不惯这种奴才。所以删了此帖
如果有人收到了邮件，请你们告诉其他人吧

**Comment by thsmzy** [comment]
等待下载链接！！！

**Comment by jzp820927** [comment]
邮件？难道还像抽奖一样，随机抽一个邮箱来发？

**Comment by wz7465** [comment]
真神显身很好啊，能为广大墙友造福是我等福分。但是理科生的文科理解力确实都不太好，恭维的话都能理解成咬人的话，我也无语了

**Comment by phuslu** [comment]
昨天刚注册的小号，楼主真身目前应该是 @ghost

不过这号老喜欢注册新号发政治帖并且改名， github 官方拿他也没有太好办法。还在观察

这是中伤我的贴
https://github.com/phuslu/goproxy/issues/1585

**Comment by phuslu** [comment]
这是中伤 @breakwa11 的帖子 https://github.com/shadowsocksr/shadowsocksr-csharp/issues/88
https://github.com/breakwa11/shadowsocks-rss/issues/660

**Comment by wz7465** [comment]
社长加入，有趣了

**Comment by wz7465** [comment]
我的观点是，你有能力为广大网友造福，我欢迎，但是你用xxnetfans的名号行事，我不能不联想到x大马甲，毕竟x大隐身一段时间了，为了安全，换个马甲出来也是可以理解的。我的误解造成某人感觉自己的劳动成果被忽视了而动怒，那如果你在乎名声，那就以真身示人嘛

**Comment by phuslu** [comment]
本来我无所谓，可是昨天这号还注册了一个 @phus2b 狂发政治贴，这是把我放到火上烤的节奏。。。

**Comment by wz7465** [comment]
社长把人家的老底都挖出来了，此人持才傲物，应该收服之以为大用，我盼望XX-mini 1.3.0 尽早发布

**Comment by whhxmwhh** [comment]
哈哈！难道真的安卓能用了。感谢了。发发发888.

**Comment by SeaHOH** [comment]
这几天一眼望过去到处是 **ghost**。

**Comment by whhxmwhh** [comment]
ghost什么意识呀。大神？

**Comment by jzp820927** [comment]
不用谷歌了，我告诉你，是 “幽灵” 的意思

**Comment by kirbyzhu** [comment]
德才兼备 德在才前

**Comment by jzp820927** [comment]
不知道 LS 说的是谁

**Comment by wz7465** [comment]
都怪我，德行欠修为，竟因图一时口快，把楼主气得吐血而亡，一颗冉冉升起的新星就此陨落，实乃我翻墙界的重大损失，我不禁双手合十，心中默默念到：罪过罪过

**Comment by kirbyzhu** [comment]
@jzp820927 我这里没有针对谁：）  只是谈一下个人看法 不过从lu大的两个链接来看 ghost是没啥德

**Comment by breakwa11** [comment]
ghost是所有删除了的账号的统一显示

**Comment by theratlesnake** [comment]
@wz7465 你这狗嘴少说点话，别跟个傻逼一样装成侦探去打听开发者们的身份，懂？以为自己很有文科生头脑了？看看自己发的那些字，跟个弱智一样。我就看不惯那些装逼狗装成侦探去打听开发者身份，活该被骂五毛。这一点我支持楼主。
至于楼上说中伤开发者的帖子，我是没看到有什么中伤的事情发生，要么就是被修改了。

**Comment by phuslu** [comment]
@breakwa11 不是，@ghost 这几天还在这个repo回帖呢，你可以翻下。

不过他自删帖子很勤快，估计故意伪装，要看得抓紧。。。

**Comment by phuslu** [comment]
@breakwa11 他的手法是不停注册小号，暴露了就把自己rename成 @ghost ，因为他是 @ghost 的的拥有者，所以可以反复这么做。

**Comment by phuslu** [comment]
我贴出这两个链接，就是让大家众目睽睽之下，@ghost 账号只能定死在这两个中伤帖子了。

没法继续36变了

**Comment by MeABc** [comment]
github 还可以这样玩？

难怪以前有看到他发贴，点击过去看又变成"删除用户"。

这家伙也是拼了。

**Comment by wz7465** [comment]
@theratlesnake 这位谁啊，牙缝那么大，还嵌着几片隔夜蒜...
我就奇了怪了，左一口五毛，右一口五毛，五毛是你亲爹吗？叫的这么亲热
如今五毛这一词，已经烂大街了，像块狗皮膏药，什么猫三狗四都拿它用来贴，看谁不顺眼，就往身上一贴，自己好像立马就站在了正义的制高点，这“正义”也太廉价！
你要有社长的技术功底，也可以刨刨我的底，要是挖出个朝廷的五毛委任状，倒也立功了，结果什么也不做，什么也没有，就在那信口雌黄，血口喷人
不过是享用了@ghost几块狗骨头，你就在那儿吠，一付忠心护主的模样，做奴才你挺合格
你家主子已经断气48小时了，坟头草都两尺高了，你怒气冲冲的冲进来，是想为你家主子坟头上添新砖呢还是想扒坟呢？

**Comment by ugvf2009** [comment]
这种人傻逼，我们不理他就可以了。当成空气。

**Comment by kirbyzhu** [comment]
@breakwa11 ghost这个号08年就创建了 后面偶有年度有信息遗留 应该不是所有删除帐号的统一代号

**Comment by breakwa11** [comment]
你不信就自己实验呀，注册一号，发issue然后自己注销账号，原issue都会变成是ghost

**Comment by SeaHOH** [comment]
城会玩。我就没玩过，良民、大大嘀。

**Comment by linhua55** [comment]
@phuslu  
https://help.github.com/articles/deleting-your-user-account/

@breakwa11 
的确是

**Comment by phuslu** [comment]
啊，那就是楼主真身依然未知。

手法就是不停注册小号，发帖，然后注销自己账号。

**Comment by SeaHOH** [comment]
发现破姐真是言简意赅、正中要害，高冷之气跃然而出。

社长，信错你了~ 我还专门去看了看 @ghost。 :sweat_smile:

**Comment by theratlesnake** [comment]
@wz7465 狗杂种，回家给你妈扶灵车去吧，整件事就是你这死妈狗挑起来的，谁挑起谁死全家，你算哪根葱，你贡献代码了？你贡献解决方案了？你除了贡献你妈给我草，你有什么贡献，草你妈，在这搞内讧？我不管他们其他人有什么恩怨，我就知道现在在XX-net挑起事端的是你这条死妈的狗杂种，，楼主，这种没有一点贡献的死妈废物，你就别摆心里，你的贡献大家都有眼看到，这种死妈狗除了长着一张吃屎的狗嘴，另外一个功能就是用来喷人了，想跟我玩喷？你算老几，回家看好你妈的骨灰。

**Comment by theratlesnake** [comment]
@wz7465  我草着你妈再告诉你多一次，以后再让我看到你这死妈狗攻击侮辱开发者（或是对项目有贡献的人），或是故意揣测X大的身份，我看到一次，就草你妈一次，渣滓。

**Comment by wz7465** [comment]
@theratlesnake 你妈在我枕边呢，还是你妈比较识大体，让我不要动怒，她这个逆子狗嘴里吐不出象牙
怨我？
你和你主子都智商低下，我和@jzp唠唠嗑，推测一下xx-netfans可能是xx-net的马甲，又能怎么呢？他理解力低下要发飙，一上来就骂人脏话，后来觉得理亏又偷偷删掉了，你主子都不发声了，你这条狗倒开始发狂犬病了

**Comment by jzp820927** [comment]
好吧，我承认，这是一场唠嗑引发的血案。。。

**Comment by theratlesnake** [comment]
@wz7465  哟，死妈狗恼羞成怒了？喷楼主，质疑楼主，质疑X大的时候不是很正义，装得像美国侦探一样很光明正大的吗？现在容不得别人说你啦？你怎么不去做国家主席啊，垃圾，我素质不高，看不惯你这种死妈狗在这装逼，你这狗杂种也别装什么高级文科生说什么理科生理解能力，喷狗一只装你妈的比啊，喷别人很爽是不是，我喷你妈比，你这种来搞内讧的狗，我草你妈，先死一车妈吧，内讧狗！

**Comment by wz7465** [comment]
本来就没事，我又不是要刨xx-net的底细，也不是刨xx-netfans的底细，只是把两者关联一下，无伤大雅的事，某些人就要狂跳，真如某人说的我是五毛侦探，我不去挖xx-net的老底，却在这儿兴奋的宣布：啊，xx-netfans是xx-net的马甲唉，有这样的侦探吗？智障嘛

**Comment by theratlesnake** [comment]
@wz7465 先是给X大扣帽子，说X大有小号，现在又给我扣帽子，说我有主子了？新型红卫兵是这样当的？对啊，我是有主子，那就是你妈，我草了你妈，所以她是我主子啊，你满意了没，死妈狗。

**Comment by theratlesnake** [comment]
@wz7465 死妈狗，你这狗嘴是不是屎吃多了，不喷会死？闲得蛋疼就回家给你妈整理一下骨灰，免得被隔壁老王偷了做成面包喂你家旺财，跟我玩喷？来啊

**Comment by wz7465** [comment]
狂犬病发起来还真猛，以前只听说，今天见到，算开了眼界！晚上又可以开瓶小酒，心情不错中...

**Comment by theratlesnake** [comment]
@wz7465 楼主对XX贡献不少，你有什么资格逼逼，你告诉我，你这狗杂就和那些喷破娃SSR的脑残一样性质，你不服你可以自己搞个出来，何德何能轮到你在这讽刺贡献者了？

**Comment by wz7465** [comment]
哈哈哈，笑死我了！

**Comment by theratlesnake** [comment]
@wz7465  你现在心情不错？原来被人骂，你才会开心啊？果然是乱伦生出来的奇葩怪胎。你这种狗伎俩也学人做喷子？回家吃点屎早点睡吧，这世界轮不到你来装逼，更轮不到你来羞辱项目的贡献者。

**Comment by theratlesnake** [comment]
@wz7465  笑？我和各git友打赌，你现在的心理状态是这样的：被人骂，然后挨着之前装过的逼（自己说的话多有文科人的人文气息），不好意思对喷（其实平时生活里自己也是个低素质的喷子），然后心理很气愤的留下四个字：【笑死我了】。。。。。我已经告诉你了，你这种别人玩烂的梗，我已经见多了。弱智。

**Comment by wz7465** [comment]
有贡献就正正规规的贡献，开个账号，源码公布出来，下载链接做好，可楼主总是鬼鬼祟祟，行踪飘忽。想当初，我也下了他的软件，现在想想，有点后怕，他这人品，搞点病毒木马，我就死翘翘了，想想我也是以身试毒，作为先驱者，对论坛也有贡献啊

**Comment by theratlesnake** [comment]
@wz7465  破娃的推特下面，凡是我看到那些来搞事的，不论是大V小V，我都骂，也获得过不少推友点赞，再让我看到你说这种，让贡献者们心寒的话，看我会不会继续叼你！

**Comment by wz7465** [comment]
“叼”字用的好，看样子你已经渐入佳境了

**Comment by theratlesnake** [comment]
@wz7465 狗嘴少说点话，别装逼，别装侦探，有技术就做贡献，没技术就闭嘴，XX论坛懂技术的大有人在，而且楼主都说了是非官方，用不用是个人自由，没有强迫你，而且楼主有自己的解决方案，X大，Y大改进的时候也可以参考，你来装逼，就是找骂。

**Comment by theratlesnake** [comment]
@wz7465 你这种狗杂不去做五毛，真是浪费你妈生你下来的这些基因了。而且还爱装逼是吧

**Comment by wz7465** [comment]
算了算了，大家都歇歇气，@theratlesnake 你这病发起来，很耗费精神的，起码去掉半条命 
看在你是条好狗的份上，我有点动了恻隐之心
