### ISSUE TITLE
登陆Google 跳转到这个地址

### ISSUE THREAD

**Issue by evilstyle** [XX-net/XX-Net#526]
http://61.160.183.115/proxy?e=c7863c15f4ba20d7F_mV66IkkIxm6IIkbYvVeY~kPYq4UY~czRs4LYNkVIsKG6N0c9qKCXAk7Y8Vg6IPDIq4J29kTaWKMNI0i_s2G2ZP1Y45e~ZoKYVsCRaF
我是不是dns 劫持了呢 喵

**Comment by yfdyh000** [comment]
http://weibo.com/5424712657/CmkyN0yFH
这里有人说是114DNS的问题。我没遇到，仅供参考。

2015-06-17 14:26 GMT+08:00 evilstyle <notifications@github.com>:

>
> http://61.160.183.115/proxy?e=c7863c15f4ba20d7F_mV66IkkIxm6IIkbYvVeY~kPYq4UY~czRs4LYNkVIsKG6N0c9qKCXAk7Y8Vg6IPDIq4J29kTaWKMNI0i_s2G2ZP1Y45e~ZoKYVsCRaF
> 我是不是dns 劫持了呢 喵
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XX-net/XX-Net/issues/526>.
>



-- 
Best regards,
YFdyh000.

**Comment by evilstyle** [comment]
dns 问题 ╮(╯▽╰)╭
