### ISSUE TITLE
WebUI的多语言支持？

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net#527]
WebUI现在属于中英混杂的状态，全部修改成中文的话，又得考虑其他语言使用者的兼容问题。

所以我想我们是不是应该搞成多语言的模式？类似我之前看到的<a href='https://github.com/nylira/prism-break/tree/master/source/locales'>这个项目</a>的做法，用json文件分别储存各语种的相应内容，众多贡献者可以直接参与翻译，无需关心代码。

如果做了这个实现，很多帮助信息就可以直接写入WebUI中，以小字标注、浮动标签等形式体现。在wiki中写帮助文档虽然是必须的，但终究不是最方便的方法。

**Comment by xxnet** [comment]
这个好，其实还有很多国家有这个需求。

最近看fqrouter的源码，采用jinja2 实现，就是多语言的，而且很简洁，值得学习。



在 2015年6月17日 下午2:53，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 是啊，墙不是特有的。是时候轮到西朝鲜居民为全球贡献代码了。Jinjia看起来很厉害的样子，还不太看得懂。

框架搭起来，要扩充就很容易了，各语种的文字可以由社区大家一起提交

**Comment by xxnet** [comment]
去看看fqsocks的源码，manager部分就是类似webui
或者直搜jinja2的例子，好东西应该不会太复杂的。


http://docs.jinkan.org/docs/jinja2/

在 2015年6月17日 下午11:45，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet 多谢，正在学，但是主业比较忙，学习之路漫漫啊！
