### ISSUE TITLE
XX-Mini 1.3.0 回来了!!

### ISSUE THREAD

**Issue by ilvegithub** [XX-net/XX-Net#5270]
### 然后更改wifi设置即可翻墙

**Comment by ilvegithub** [comment]
这帖子下希望大家认真讨论问题，不要再说那些没有意义的话．随便猜疑别人是小人的做法，应以君子之腹度小人之心

**Comment by THLIVSQAZ** [comment]
变身真多😁，过程很详细支持👍

**Comment by wz7465** [comment]
哈哈，又活过来了？活过来是好事啊，支持！

**Comment by ilvegithub** [comment]
@wz7465 我上次说的就是你, 希望你能改掉你的坏毛病

**Comment by wz7465** [comment]
无所谓了，你说我小人就小人，我也不放在心上的

**Comment by ilvegithub** [comment]
@wpyok500 你试试用 gnuroot debian 能否运行gp ,这个不需要root权限

**Comment by ilvegithub** [comment]
有问题去上个帖子讨论吧

**Comment by WaterFloat** [comment]
你确定这个方法https://github.com/phuslu/goproxy/issues/1628 在手机上可行？
我用这个方法在Android x86（RemixOS、PhoenixOS、openthos）里实验了下，发现不管用哎。

**Comment by jzp820927** [comment]
试了不管用，那就是没用呗，android 很多版本，每个版本的效果都不一样。
