### ISSUE TITLE
一直显示请检查代理设置和不安全链接，尝试多种方法仍不行

### ISSUE THREAD

**Issue by arleyzhang** [XX-net/XX-Net#5273]
Chrome浏览器一直显示请检查代理设置，打开网页显示不是私密链接，按照其他帖子里的方法都试了还是不行，但是在360浏览器中就可以使用好奇怪啊？证书删了再导入也还不行。
诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:129 good:49
network-status: OK
connected-link: new:2 used:0
worker: h1:16 h2:9
scan-ip-thread-num: 50
ip-quality: 533
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

部分日志信息：
Apr 13 15:10:32.814 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:33.320 - [DEBUG] ssl_closed 210.7.45.40
Apr 13 15:10:33.320 - [DEBUG] 210.7.45.40 worker close:idle timeout
Apr 13 15:10:35.163 - [DEBUG] get ip:65.199.248.62 t:376
Apr 13 15:10:35.726 - [DEBUG] create_ssl update ip:65.199.248.62 time:378 h2:0
Apr 13 15:10:37.483 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:38.664 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:39.267 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:41.929 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:42.859 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:45.399 - [DEBUG] ip:66.96.226.84 real fail
Apr 13 15:10:45.615 - [INFO] scan_ip add ip:180.188.250.20 time:664
Apr 13 15:10:46.008 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:10:48.665 - [INFO] scan_ip add ip:41.206.96.195 time:822
Apr 13 15:10:49.967 - [INFO] scan_ip add ip:83.94.121.229 time:415
Apr 13 15:10:50.727 - [DEBUG] get ip:67.221.221.208 t:391
Apr 13 15:10:54.728 - [DEBUG] 67.221.221.208 fail:timeout('timed out',)
Apr 13 15:10:54.728 - [DEBUG] report_connect_fail:67.221.221.208
Apr 13 15:10:54.728 - [DEBUG] get ip:83.94.121.229 t:415
Apr 13 15:10:55.363 - [DEBUG] create_ssl update ip:83.94.121.229 time:421 h2:0
Apr 13 15:10:59.784 - [INFO] scan_ip add ip:2.127.237.211 time:498
Apr 13 15:11:00.455 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:01.283 - [INFO] scan_ip add ip:87.79.22.82 time:796
Apr 13 15:11:02.827 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:03.985 - [INFO] scan_ip add ip:201.57.54.221 time:886
Apr 13 15:11:06.634 - [INFO] scan_ip add ip:202.88.157.212 time:3424
Apr 13 15:11:07.494 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:08.677 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:09.283 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:09.728 - [DEBUG] ip:67.221.221.208 real fail
Apr 13 15:11:10.563 - [DEBUG] 121.78.52.78 keep alive fail, inactive_time:185 head_timeout:21
Apr 13 15:11:10.563 - [DEBUG] report_connect_fail:121.78.52.78
Apr 13 15:11:10.744 - [DEBUG] ssl_closed 200.149.119.89
Apr 13 15:11:10.744 - [DEBUG] 200.149.119.89 worker close:GoAway: additional_data:session_timed_out
Apr 13 15:11:11.941 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:12.700 - [DEBUG] ssl_closed 200.63.214.158
Apr 13 15:11:12.700 - [DEBUG] 200.63.214.158 worker close:GoAway: additional_data:session_timed_out
Apr 13 15:11:12.872 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:13.405 - [DEBUG] ssl_closed 190.212.166.170
Apr 13 15:11:13.405 - [DEBUG] 190.212.166.170 worker close:GoAway: additional_data:session_timed_out
Apr 13 15:11:15.564 - [DEBUG] 121.78.52.78 worker close:keep alive
Apr 13 15:11:16.023 - [INFO] GAE CONNECT clients1.google.com:443
Apr 13 15:11:19.590 - [INFO] scan_ip add ip:201.6.16.104 time:800

求解答

**Comment by arleyzhang** [comment]
3.2.9和3.3.0都试了，谷歌浏览器版本是57.0.2987.110 (64-bit），但是在另外一台电脑上就使用正常，那个谷歌浏览器版本是57.0.2987.133 (64-bit），

**Comment by arleyzhang** [comment]
好吧，刚才不知道怎么回事，又可以了，折腾了老半天

**Comment by jzp820927** [comment]
建议先升级到最新版，最新版解决了一个证书的问题。

**Comment by arleyzhang** [comment]
恩，现在已经可以用了，之前也是用的最新版但就老是检查代理设置和不是私密链接，后来不知道怎么回事，又可以用了，现在已经没问题了，感谢！

**Comment by jzp820927** [comment]
OK，没问题就行

**Comment by alexpdh** [comment]
升级到3.3.1能解决chrome 59版

**Comment by jzp820927** [comment]
3.3.1 确实解决了一个证书的问题。
