### ISSUE TITLE
3.3.1和3.3.0 GAE可以代理PAC不可以代理

### ISSUE THREAD

**Issue by cv0cv0** [XX-net/XX-Net#5274]
切换到PAC就不可以了。

**Comment by lelesu** [comment]
貌似是升级到3.3.1以后不可以用了，昨天我的3.3.0还可以正常使用，现在只好先用SwitchOmega了

**Comment by sorsoso** [comment]
悲剧,原来不是我一个人如此

**Comment by jzp820927** [comment]
这样，你换回 3.3.0 看看能不能用？

**Comment by cv0cv0** [comment]
@jzp820927 不行。看来是PAC有问题了。

**Comment by lelesu** [comment]
@cv0cv0 @sorsoso @jzp820927 应该是自动代理脚本有问题了吧，我家里那台没更新过就可以用

**Comment by lelesu** [comment]
@cv0cv0 @sorsoso @jzp820927 貌似是证书的我问题，把原证书(XX-net\data\gae_proxy\certs 文件夹和CA.crt文件)删掉，然后手动导入一下。我尝试使用chrome设置中的导入，但是不行，后来直接双击证书文件CA.crt导入，重启浏览器就好了

**Comment by jzp820927** [comment]
额，是挺奇怪的，最近很多人反映 pac 用不了，我觉得 pac 一般不容易出问题，就是说 js 脚本，只要在浏览器打开 pac 地址，能正常显示 pac 的内容，一般都可以正常使用。

**Comment by cv0cv0** [comment]
@jzp820927 http://127.0.0.1:8086/proxy.pac可以打开，但是PAC不走代理。

**Comment by jzp820927** [comment]
把你浏览器打开的 http://127.0.0.1:8086/proxy.pac 的内容贴出来，我看看

**Comment by cv0cv0** [comment]
@jzp820927 可能是太长了，发不出来。

**Comment by cv0cv0** [comment]
@lelesu 还是不行。

**Comment by lelesu** [comment]
@cv0cv0 那就不清楚了，我是这么解决的。。。

**Comment by jzp820927** [comment]
那贴一部分出来，就是有代理服务器的那部分贴出来看看。

**Comment by cv0cv0** [comment]
@jzp820927 `// Proxy Auto-Config file generated by autoproxy2pac, 2017-04-14 10:56:44
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 127.0.0.1:8087';
    var blackhole = 'PROXY 127.0.0.1:8086';
    if (dnsDomainIs(host, '.google.com') ||
        dnsDomainIs(host, '.google.com.hk') ||
        dnsDomainIs(host, '.google-analytics.com') ||
        dnsDomainIs(host, '.googleapis.com') ||
        dnsDomainIs(host, '.googlecode.com') ||
        dnsDomainIs(host, '.googlevideo.com') ||
        dnsDomainIs(host, '.googleusercontent.com') ||
        dnsDomainIs(host, '.ggpht.com') ||
        dnsDomainIs(host, '.wikipedia.org') ||
        dnsDomainIs(host, '.sf.net') ||
        dnsDomainIs(host, '.sourceforge.net') ||
        host == 'cdnjs.cloudflare.com' ||
        host == 'wp.me' ||
        host == 'ow.ly' ||
        host == 'po.st' ||
        host == 'goo.gl')
    {
        return autoproxy;
    }
    if (host == 'pagead2.googlesyndication.com' ||
        host == 'p.tanx.com' ||
        host == 'a.alimama.cn' ||
        FindProxyForURLByAdblock(url, host) != 'DIRECT')
    {
        return blackhole;
    } else {
        return FindProxyForURLByAutoProxy(url, host);
    }
}
`

**Comment by cv0cv0** [comment]
> // Proxy Auto-Config file generated by autoproxy2pac, 2017-04-14 10:56:44
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 127.0.0.1:8087';
    var blackhole = 'PROXY 127.0.0.1:8086';
    if (dnsDomainIs(host, '.google.com') ||
        dnsDomainIs(host, '.google.com.hk') ||
        dnsDomainIs(host, '.google-analytics.com') ||
        dnsDomainIs(host, '.googleapis.com') ||
        dnsDomainIs(host, '.googlecode.com') ||
        dnsDomainIs(host, '.googlevideo.com') ||
        dnsDomainIs(host, '.googleusercontent.com') ||
        dnsDomainIs(host, '.ggpht.com') ||
        dnsDomainIs(host, '.wikipedia.org') ||
        dnsDomainIs(host, '.sf.net') ||
        dnsDomainIs(host, '.sourceforge.net') ||
        host == 'cdnjs.cloudflare.com' ||
        host == 'wp.me' ||
        host == 'ow.ly' ||
        host == 'po.st' ||
        host == 'goo.gl')
    {
        return autoproxy;
    }
    if (host == 'pagead2.googlesyndication.com' ||
        host == 'p.tanx.com' ||
        host == 'a.alimama.cn' ||
        FindProxyForURLByAdblock(url, host) != 'DIRECT')
    {
        return blackhole;
    } else {
        return FindProxyForURLByAutoProxy(url, host);
    }
}

**Comment by cv0cv0** [comment]
@jzp820927 

> // Proxy Auto-Config file generated by autoproxy2pac, 2017-04-14 10:56:44
function FindProxyForURL(url, host) {
    var autoproxy = 'PROXY 127.0.0.1:8087';
    var blackhole = 'PROXY 127.0.0.1:8086';
    if (dnsDomainIs(host, '.google.com') ||
        dnsDomainIs(host, '.google.com.hk') ||
        dnsDomainIs(host, '.google-analytics.com') ||
        dnsDomainIs(host, '.googleapis.com') ||
        dnsDomainIs(host, '.googlecode.com') ||
        dnsDomainIs(host, '.googlevideo.com') ||
        dnsDomainIs(host, '.googleusercontent.com') ||
        dnsDomainIs(host, '.ggpht.com') ||
        dnsDomainIs(host, '.wikipedia.org') ||
        dnsDomainIs(host, '.sf.net') ||
        dnsDomainIs(host, '.sourceforge.net') ||
        host == 'cdnjs.cloudflare.com' ||
        host == 'wp.me' ||
        host == 'ow.ly' ||
        host == 'po.st' ||
        host == 'goo.gl')
    {
        return autoproxy;
    }
    if (host == 'pagead2.googlesyndication.com' ||
        host == 'p.tanx.com' ||
        host == 'a.alimama.cn' ||
        FindProxyForURLByAdblock(url, host) != 'DIRECT')
    {
        return blackhole;
    } else {
        return FindProxyForURLByAutoProxy(url, host);
    }
}

**Comment by kebinzhi** [comment]
把proxy.ini里面的adblock注释掉就可以了。

**Comment by cv0cv0** [comment]
@kebinzhi 可以了。这是为什么？

**Comment by lelesu** [comment]
好读书不求甚解，哈哈哈，好使了就行 @cv0cv0

**Comment by jzp820927** [comment]
原来是 adblock 影响的，没用过 XX 自带的 PAC 还真想不到。

**Comment by WLZLCX** [comment]
全新下载使用，无问题

**Comment by jzp820927** [comment]
因为最新版已经解决了这些问题了
