### ISSUE TITLE
今天突然pac模式所有网页都无法打开了.

### ISSUE THREAD

**Issue by sorsoso** [XX-net/XX-Net#5275]
包括不需要翻墙的网站,chrome提示
ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

选全局8087没问题,选直连也没问题
求分析问题...

**Comment by zking77** [comment]
2017-04-13 18:55 GMT+08:00 sorsoso <notifications@github.com>:

**Comment by zking77** [comment]
Thank you!

2017-04-13 18:55 GMT+08:00 sorsoso <notifications@github.com>:

**Comment by kebinzhi** [comment]
把proxy.ini里面的adblock注释掉就可以了。 @jzp820927

**Comment by jzp820927** [comment]
好吧，以后这个问题，你来解释。

**Comment by sorsoso** [comment]
大概我自己找到问题了,以前都是手动设置浏览器代理,这次更新后貌似需要导入xxnet自带的SwitchyOmega配置

**Comment by jzp820927** [comment]
用 pac 就可以不用导入 omega ，如果需要用 omage 才需要导入。

**Comment by WLZLCX** [comment]
人品问题

**Comment by jzp820927** [comment]
LS 正解
