### ISSUE TITLE
升级到3.3.1 PAC有问题的可以通过两种方式解决

### ISSUE THREAD

**Issue by cv0cv0** [XX-net/XX-Net#5279]
1. 退回到3.3.0，把/data/gae_proxy/proxy.pac删除，再打开就可以了。
2. 打开/code/default/gae_proxy/local/proxy.ini，把adblock = https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt 这一行前面加上;注释或删掉这一行，把/data/gae_proxy/proxy.pac删除，打开xx-net。

**Comment by 12343954** [comment]
mac下3.3.1 打不开github 是这个原因吗？之前还好好的

**Comment by yeahwu** [comment]
已经注释掉了adblock，下载链接不变
 https://codeload.github.com/XX-net/XX-Net/zip/3.3.1

**Comment by jzp820927** [comment]
这效率不是一般的高啊

**Comment by WLZLCX** [comment]
全新下载使用，无问题
