### ISSUE TITLE
Mac上Python图标不消失，菜单里不出现XXNet的图标

### ISSUE THREAD

**Issue by kennir** [XX-net/XX-Net#5280]
显示检查代理设置
证书也失败

浏览器用的是safari，我已经删除证书，删除data目录重新导入也没有用

XX-Net Status:

sys-platform: x86_64, Darwin-16.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
os-release: 16.5.0
os-detail: Release:10.12.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30
xxnet-version: 3.3.1

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:31 good:20
network-status: OK
connected-link: new:4 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 691
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by kennir** [comment]
已经解决，Mac连接到iPhone的热点后，mac_tray.py里或者网络信息的脚本会返回错误，只要断开热点就可以了，折腾一下午

**Comment by jzp820927** [comment]
看来因为 wifi 引发的问题还蛮多地，今天就碰到2次了。

**Comment by kennir** [comment]
主要是web里显示出来的错误和真正的原因完全无关，在终端里运行 mac_tray.py才看到返回的错误，这个错误在log里也没有出现

**Comment by jzp820927** [comment]
额，好吧，问题解决了就好
