### ISSUE TITLE
youtube 无法登录了

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#5281]
版本：3.3.0
操作系统：win7
今天下午开始，打开youtube, 网页左下角显示“正在等待ipv4.google.com相应”，然后很快就变成“连接超时，先休息一会再来！”

其它网站，包括google, twitter等都正常。

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2004
network-status: OK
connected-link: new:10 used:0
worker: h1:13 h2:8
scan-ip-thread-num: 50
ip-quality: 575
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by farshidvahid** [comment]
靠，又能打开了。

**Comment by jzp820927** [comment]
一般多刷新几次就好了。
