### ISSUE TITLE
xx-net代理时的爬虫速度问题

### ISSUE THREAD

**Issue by yjy20170** [XX-net/XX-Net#5290]
现在使用校园网ipv6+xx-net全局GAEProxy代理，浏览器访问网页的速度正常。Python 爬虫程序中以requests.get(url,verify=False) 发送请求，通过ipv4计费上网、不使用代理时，执行该语句的耗时约为0.15秒，现在增加到10.5秒左右。请问为什么会有如此大的差异？

**Comment by jzp820927** [comment]
走代理是会增加延时的啊

**Comment by yjy20170** [comment]
浏览器几乎感觉不到延迟而爬虫的延迟高达10秒以上，这是什么原因造成的呢

**Comment by SeaHOH** [comment]
试过用浏览器访问此 url 的速度没有？
如果正常，尝试修改爬虫的 `user-agent`。

**Comment by yjy20170** [comment]
爬虫的user-agent在一个列表里随机选择，应该没什么问题

**Comment by yjy20170** [comment]
我做了一组对照实验（+表示开启 -表示未开启）：
1：+xxnet+ipv6-ipv4  13秒
2：+xxnet-ipv6+ipv4  31秒
3：-xxnet-ipv6+ipv4   1秒

然后从状态3切换回状态1的时候，我无意间把全局GAEProxy代理改成了取消全局代理，爬虫就可以正常运作了......好像是因为在requests函数中设置proxies后，要刷新xxnet才能生效。感谢二位的热心解答！（不过还是有个疑问，为什么全局代理下爬虫很慢，取消全局代理后反而变快呢？从字面上理解，取消全局代理后爬虫没法走ipv6通道联网吧？）

测试代码如下(Python3.4)
```
import requests
import datetime
url = "http://movie.douban.com/top250?start=0&filter="
headers = {'User-Agent': "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36",
           'Accept': "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
           'Accept-Encoding': 'gzip, deflate, sdch'
           }
t0=datetime.datetime.now()
html=requests.get(url,headers=headers,verify=False,proxies={"http":"http://127.0.0.1:8087","https":"http://127.0.0.1:8087"})
print(datetime.datetime.now()-t0)``
```

**Comment by SeaHOH** [comment]
使用的什么浏览器？火狐？
我认为你的 v4 通道就没断过，所以取消代理还能联网。

**Comment by yjy20170** [comment]
最新版的Chrome，我在SwitchyOmega里设置的情景模式是XX-Net. 我用其它设备登录校园网，可以看到确实没有连上ipv4，计费的流量也没有变。现在爬虫基本上能2秒左右打开一个网页，偶尔跳到10秒以上。

**Comment by yjy20170** [comment]
我找个流量监控软件再看看吧，总感觉不太科学

**Comment by jzp820927** [comment]
我也觉得不科学，不明觉厉。

**Comment by SeaHOH** [comment]
@yjy20170 
你是不是设置过 NAT64？所以走的还是 v6.
