### ISSUE TITLE
安卓使用

### ISSUE THREAD

**Issue by april4513** [XX-net/XX-Net#5296]
最近看到XXnet安卓版出来了，把XXnet3.3.0安装到手机上后，先安装了证书，把config.ini从电脑复制到手机，发现Brower proxy setting 还是fail 状态， 把WiFi 的代理改为手动后（127.0.0.1   8087），Status状态页终于出现Welcome字样

1.手机WiFi设置自动代理（http://127.0.0.1:8086/proxy.pac）后，XXnet代理状态还是fail
2.手动代理配置下只能用浏览器网页访问ins、Facebook等，但软件APP类不能使用，无法联网
3.每次退出XXnet后要重新设置WiFi代理为无才可以浏览国内网站
4.手动代理下 网页速度不算很快
5.手机也不会出现VPN字样

XXnet一直很好，希望能继续开发下去。
（小白一个 摸索着用的）

**Comment by jzp820927** [comment]
apps 因为证书问题，很难解决。不用代理的时候，必须手动取消 wifi 代理才行。手机权限较低，不能做到 PC 上这么自动化。

**Comment by gmvp3** [comment]
那为什么蓝灯可以用APP

**Comment by jzp820927** [comment]
我上面都已经说的很清楚了，XX 不能用于 apps，是因为证书问题，这是 XX 特有的缺陷，其他代理没有这种缺陷。
