### ISSUE TITLE
关于远程连接Web控制端

### ISSUE THREAD

**Issue by zegzhi** [XX-net/XX-Net#5297]
因为XX-Net不是在本机，所以需要允许远程连接Web控制端。
但这样Web控制端就暴露在了外部网络环境中，能不能添加上访问IP白名单或者账号密码等验证手段？

**Comment by jzp820927** [comment]
项目目前没有继续开发，这个实现的可能性不多，不过你可以试试通过 nginx 反代，在 nginx 上做验证。
