### ISSUE TITLE
如何让GAEProxy Log不显示在systemd的系统日志里

### ISSUE THREAD

**Issue by guoqiyi** [XX-net/XX-Net#5298]
如题，大量的无意义的日志不仅增加了系统日志的体积，还让我想查看系统出错信息都无从查找。。。
使用的是XX-NET最新稳定版，启动脚本是配置页面生成的开机自启动脚本，即XX-NET.desktop

**Comment by guoqiyi** [comment]
![screenshot from 2017-04-17 17-13-13](https://cloud.githubusercontent.com/assets/3457554/25084975/44039362-2325-11e7-94f3-c567c3491c30.png)

**Comment by guoqiyi** [comment]
好吧，我的暂时的解决方案是手动创建一个.xprofile(.bash_profile好像gdm自启动不读取～)在里面添加一条命令nohup /home/yi/.local/XX-Net/start >/dev/null 2>&1 &，期待官方的自启动选项能解决问题～

**Comment by jzp820927** [comment]
目前项目已经没有继续开发了，任何问题都只能靠自己解决了。

**Comment by guoqiyi** [comment]
了解，感谢你们的付出～
