### ISSUE TITLE
对服务端3.2X以后的版本兼容性不是很好，可否考虑升级GoAgent Version

### ISSUE THREAD

**Issue by shoujiao** [XX-net/XX-Net#53]
比如wikipedia时常无法访问，证书似乎并没自动导入
Property	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
XX-Net Version	1.2.1
Launcher Version	1.0.4
GoAgent Version	3.1.37
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087

**Comment by xxnet** [comment]
精力有限，暂时没有考虑兼容3.2的服务端。

wikipedia无法访问时，其他非Google网站能否访问？
 
证书问题，第一次启动时，证书导入往往在浏览器启动之后，因此访问会提示证书有问题。
其实已经导入了，此时重启浏览器就好了。

下个版本我加上提示。

**Comment by xxnet** [comment]
发现3.2之前的服务端存在的一些具体的问题：
1. 某些一定情况下出错
2. 下载某些文件容易出错
  导致类似Facebook某些脚本加载失败。
3. Youtube等视频速度不能加速，3.2版本速度会自动加速。

正在计划升级到3.2的服务端中。

**Comment by shoujiao** [comment]
好的，等你的好消息吧。
另外会自动更新goagent吗？没有感觉到啊，呵呵

**Comment by xxnet** [comment]
1.3.5 发现自动升级的一个小问题，修复了。
  以后有新改进，可以用自动升级了。

**Comment by xxnet** [comment]
1.7 升级到 goagent 3.2服务端了
