### ISSUE TITLE
Linux/Ubuntu 17.04 无法使用及连接

### ISSUE THREAD

**Issue by Wows233** [XX-net/XX-Net#5308]
运行看日志似乎正常？莫名其妙的。最近从win10换到Ubuntu
启动后无法访问http://127.0.0.1:8085/ ，显示拒绝连接。SwitchyOmega设置http， 127.0.0.1:8087 显示代理服务器无法访问
8086的pac也无法访问

Python 2.7.13
XX-Net version:default
XX-Net.desktop already exists
4月 19 16:26:46.01 - [WARNING] import pynotify fail, please install python-notify if possiable.
4月 19 16:26:46.09 - [INFO] use build-in openssl lib
4月 19 16:26:46.09 - [INFO] start XX-Net 3.3.1
4月 19 16:26:46.09 - [DEBUG] start confirm_xxnet_exit
4月 19 16:26:46.09 - [DEBUG] good, xxnet:8087 cleared!
4月 19 16:26:46.09 - [DEBUG] good, xxnet:8085 clear!
4月 19 16:26:46.09 - [DEBUG] finished confirm_xxnet_exit
4月 19 16:26:46.20 - [INFO] SSL use version:TLSv1_2
4月 19 16:26:46.20 - [INFO] OpenSSL support alpn
4月 19 16:26:46.20 - [INFO] load ip range file:/home/xxx/XX-Net/code/default/gae_proxy/local/ip_range.txt
4月 19 16:26:46.22 - [INFO] load google ip_list num:149, gws num:149
4月 19 16:26:46.23 - [INFO] OpenSSL support alpn
4月 19 16:26:46.23 - [DEBUG] get ip:61.238.239.247 t:101
4月 19 16:26:46.24 - [DEBUG] get ip:202.75.147.32 t:145
4月 19 16:26:46.25 - [DEBUG] ## GAEProxy set keep_running: True
4月 19 16:26:46.25 - [INFO] ------------------------------------------------------
4月 19 16:26:46.25 - [INFO] Python Version     : 2.7.13
4月 19 16:26:46.25 - [INFO] OS                 : Dist:Ubuntu; Version:17.04; ID:zesty
4月 19 16:26:46.25 - [INFO] Listen Address     : 127.0.0.1:8087
4月 19 16:26:46.25 - [INFO] GAE APPID          : xx-net-163316
4月 19 16:26:46.25 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
4月 19 16:26:46.25 - [INFO] ------------------------------------------------------
/home/xxx/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/crypto.py:1110: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  self._x509, digest, result_buffer, result_length)
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxx/XX-Net/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/home/xxx/XX-Net/code/default/gae_proxy/local/proxy.py", line 153, in main
    CertUtil.init_ca()
  File "/home/xxx/XX-Net/code/default/gae_proxy/local/cert_util.py", line 554, in init_ca
    serial_number = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, fp.read()).get_serial_number()
  File "/home/xxx/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "/home/xxx/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

4月 19 16:26:46.39 - [DEBUG] create_ssl update ip:61.238.239.247 time:97 h2:1
4月 19 16:26:46.39 - [DEBUG] get ip:118.98.26.28 t:146
4月 19 16:26:46.47 - [DEBUG] network is ok, cost:334 ms
4月 19 16:26:46.61 - [DEBUG] create_ssl update ip:118.98.26.28 time:150 h2:0
4月 19 16:26:46.74 - [DEBUG] get ip:113.171.247.95 t:163
4月 19 16:26:46.99 - [DEBUG] create_ssl update ip:113.171.247.95 time:167 h2:0
4月 19 16:26:50.25 - [DEBUG] 202.75.147.32 fail:timeout('timed out',)
4月 19 16:26:50.25 - [DEBUG] report_connect_fail:202.75.147.32
4月 19 16:27:05.25 - [DEBUG] ip:202.75.147.32 real fail
4月 19 16:27:06.51 - [INFO] scan_ip add ip:5.20.5.215 time:544

**Comment by jzp820927** [comment]
终端运行命令
netstat -tlnp|grep 8087
看看 XX 运行起来了没？

**Comment by Wows233** [comment]
我什么都没做，吃饭回来就好了？？
然而有这个
无法建立 SSL 连接 是什么意思？好像没关系吧？应该是扫描的代理IP的？


[0419/181149.234327:ERROR:nss_util.cc(94)] Failed to create /home/wows233/.pki/nssdb directory.
--2017-04-19 18:11:49--  https://clients2.google.com/cr/report
正在解析主机 clients2.google.com (clients2.google.com)... 61.91.161.217
正在连接 clients2.google.com (clients2.google.com)|61.91.161.217|:443... 4月 19 18:11:50.02 - [INFO] get uuid:f3bbd735-550a-490a-b290-7bb58dfbb1df
4月 19 18:11:50.03 - [INFO] GAE CONNECT xxnet-update.appspot.com:443 
4月 19 18:11:50.04 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=f3bbd735-550a-490a-b290-7bb58dfbb1df&version=3.3.1&platform=Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty
4月 19 18:11:50.26 - [INFO] DIRECT t:221 s:1674 200 xxnet-update.appspot.com /update.json?uuid=f3bbd735-550a-490a-b290-7bb58dfbb1df&version=3.3.1&platform=Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty
4月 19 18:11:50.26 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to /home/wows233/XX-Net/data/downloads/version.txt, retry:0
已连接。
4月 19 18:11:50.83 - [INFO] scan_ip add ip:62.214.62.89 time:544
无法建立 SSL 连接。

Failed to get crash dump id.
Report Id: 
4月 19 18:11:58.81 - [INFO] scan_ip add ip:66.96.226.244 time:629
Illegal instruction (core dumped)
[0419/181159.469624:ERROR:nss_util.cc(94)] Failed to create /home/wows233/.pki/nssdb directory.
--2017-04-19 18:11:59--  https://clients2.google.com/cr/report
正在解析主机 clients2.google.com (clients2.google.com)... 61.91.161.217
正在连接 clients2.google.com (clients2.google.com)|61.91.161.217|:443... 已连接。
无法建立 SSL 连接。

Failed to get crash dump id.
Report Id: 
Illegal instruction (core dumped)
4月 19 18:12:09.94 - [DEBUG] launcher web_control 127.0.0.1:45830 GET /css/bootstrap.css 
4月 19 18:12:09.94 - [DEBUG] launcher web_control 127.0.0.1:45834 GET /css/bootstrap-responsive.css 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45836 GET /css/flat-ui.css 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45838 GET /css/ladda-themeless.min.css 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45842 GET /js/jquery-1.11.2.min.js 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45840 GET /css/style.css?ver=3.3.1 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45834 GET /js/bootstrap.min.js 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45830 GET /js/flat-ui.min.js 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45838 GET /js/jquery.timer.js 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45836 GET /js/spin.min.js 
4月 19 18:12:09.95 - [DEBUG] launcher web_control 127.0.0.1:45840 GET /js/ladda.min.js 
4月 19 18:12:09.96 - [DEBUG] launcher web_control 127.0.0.1:45842 GET /js/site.js?ver=3.3.1 
4月 19 18:12:10.00 - [DEBUG] launcher web_control 127.0.0.1:45830 GET /img/logo.png 
4月 19 18:12:10.00 - [DEBUG] launcher web_control 127.0.0.1:45836 GET /img/quit.png 
4月 19 18:12:10.00 - [DEBUG] launcher web_control 127.0.0.1:45834 GET /img/fixed-width.png 
4月 19 18:12:10.07 - [DEBUG] launcher web_control 127.0.0.1:45830 GET /config?cmd=get_config 
4月 19 18:12:10.12 - [DEBUG] launcher web_control 127.0.0.1:45836 GET /config?cmd=get_config 
4月 19 18:12:10.19 - [DEBUG] launcher web_control 127.0.0.1:45830 GET /favicon.ico 
4月 19 18:12:17.30 - [INFO] scan_ip add ip:200.28.6.231 time:1369

**Comment by jzp820927** [comment]
只要不影响使用就行了吧。

**Comment by Wows233** [comment]
感谢你的帮助～
