### ISSUE TITLE
一些gvs IP可用于GAE，~~但不能直连www.google.com~~

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#531]
>curl -k  -I http://118.174.27.106 

    HTTP/1.1 301 Moved Permanently
    Location: http://www.google.com/
    Content-Type: text/html; charset=UTF-8
    Date: Thu, 18 Jun 2015 09:25:24 GMT
    Expires: Sat, 18 Jul 2015 09:25:24 GMT
    Cache-Control: public, max-age=2592000
    Server: gws
    Content-Length: 219
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN
    Alternate-Protocol: 80:quic,p=0

直接把这个ip贴到浏览器地址栏里，回车访问，不会直接打开google页面，而是会跳转到google地址

>curl -k  -I https://118.174.27.106

    HTTP/1.1 404 Not Found
    Date: Thu, 18 Jun 2015 09:24:07 GMT
    Content-Type: text/html; charset=UTF-8
    Server: gvs 1.0
    Content-Length: 1425
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN

>curl -k  -I https://118.174.27.106 --ciphers ECDHE-RSA-AES128-SHA

    HTTP/1.1 301 Moved Permanently
    Location: http://www.google.com:443/
    Content-Type: text/html; charset=UTF-8
    Date: Thu, 18 Jun 2015 09:23:14 GMT
    Expires: Sat, 18 Jul 2015 09:23:14 GMT
    Cache-Control: public, max-age=2592000
    Server: gws
    Content-Length: 223
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN
    Alternate-Protocol: 443:quic,p=1

含有“301 Moved Permanently”字眼
>curl -k  --resolve xxnet-13.appspot.com:443:118.174.27.106 https://xxnet-13.appspot.com/_gh/ --ciphers ECDHE-RSA-AES128-SHA 

    GoAgent Python Server 3.2.0 works, deployed at 2015-03-28 08:15:22

好吧，有点草率，手动解析域名后可使用
>curl -k -I --resolve www.google.com:443:118.174.27.106 https://www.google.com/ncr --ciphers ECDHE-RSA-AES128-SHA

    HTTP/1.1 302 Found
    Location: http://www.google.com/
    Cache-Control: private
    Content-Type: text/html; charset=UTF-8
    Set-Cookie: PREF=ID=50e77cecfea72e47:FF=0:LD=en:NW=1:CR=2:TM=1434620783:LM=1434620783:S=6LmxsYDeSh1l4TrV; expires=Sat, 17-Jun-2017 09:46:23 GMT; path=/; domain=.google.com
    Date: Thu, 18 Jun 2015 09:46:23 GMT
    Server: gws
    Content-Length: 219
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN
    Alternate-Protocol: 443:quic,p=1

**Comment by xxnet** [comment]
这个ip不是GVS ip，根据iplocation.net 的查找结果：

118.174.27.106 Thailand Krung Thep Bangkok Ip Assignment For Google Caching
Systems

这是一个Google Cache 服务器。

要证明无法作为Google业务服务，还需要把Cookie等数据放入验证。
彻底验证的办法，是用原版的Goagent，只填入这个ip，然后访问google服务。

2015-06-18 17:32 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by yfdyh000** [comment]
gvs的概念就包括Google Cache Server吧，属于GGC，Google提供服务器和进行管理，托管在ISP的机架和网络上。从证书域名也可看出是Google在管理。

**Comment by xxnet** [comment]
有一类ip，如果直接curl -vv ip，会看到http头部的Server 字段是gvs，这类ip在不指定cipher情况下，是无法作为GAE
服务器的。
而Google Cache Server 的ip，Server字段是gws，不指定cipher也可以作为GAE服务器使用。

在 2015年6月19日 上午11:10，YFdyh000 <notifications@github.com>写道：
