### ISSUE TITLE
3.3.1证书过期?

### ISSUE THREAD

**Issue by peach5460** [XX-net/XX-Net#5310]
版本3.3.1
打开谷歌,脸书等网站,无论是用火狐还是谷歌浏览器,都提示证书过期

> 您的连接不安全
> www.google.com.hk 的管理员未正确配置网站。为避免您的信息被窃，Firefox 没有建立与该网站的连接。
> 此网站使用了 HTTP 严格传输安全（HSTS）要求 Firefox 只进行安全连接。正因如此，您不能为此证书添加一个例外。

> www.google.com.hk 使用了无效的安全证书。 
> 证书过期日期为 2017年4月18日 11:05。而当前日期为 2017年4月20日 9:26。 错误代码: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by JesusSave** [comment]
同问，今天一开机就不能用了，证书也导入不成功，何解？

Your connection is not private

Attackers might be trying to steal your information from mail.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID

**Comment by xianshanlai** [comment]
我也是这个问题，导致gmail和google搜索都用不了了，删过data，重新导入证书依然不行啊，不知道怎么解决

**Comment by hcym** [comment]
不是证书过期
--ignore-certificate-errors --allow-insecure-localhost

**Comment by jzp820927** [comment]
证书过期就重新生成。
不能导入证书没遇到过，有什么错误提示么？

**Comment by SeaHOH** [comment]
LZ 的情况的确是过期，二三楼不清楚。
如果的确是证书问题建议参照[这个证书生成条件](https://github.com/SeaHOH/GotoX/blob/master/local/CertUtil.py)修改，我测试过 Chromium 中也正常使用。

**Comment by peach5460** [comment]
>颁发者 GoAgent XX-Net
> 起始时间 2016年4月18日
> 过期时间 2026年4月18日

问题是我在firefox的证书管理里面看到的没过期啊...

**Comment by jzp820927** [comment]
你系统里面是不是有旧的 XX 证书没有删除？

**Comment by SeaHOH** [comment]
奇怪，这提示。
也许是强制 1 年过期，这个条件我还没测试过。

**Comment by SeaHOH** [comment]
@peach5460 
对了，你这是一年前的证书，所以你没有更新证书。
必须删除所有 XX-Net 证书重新生成导入，不然涉及到证书的新更新无法正常使用。

**Comment by jzp820927** [comment]
奇怪了，XX 好像不能改证书有限时间吧，不知道他怎么改的 10年，难道是 改的源代码？

**Comment by SeaHOH** [comment]
刚又翻了下，的确是 10 年，居然是去年 8 月修改的。

**Comment by peach5460** [comment]
@SeaHOH 
是运行certmgr.msc,删证书吧?
我把所有分类都看了一次,把xx-net的证书全删了,重新将CA导入"受信任的根证书颁发机构"
依然没用,提示我17年4月18日就过期了

**Comment by SeaHOH** [comment]
@peach5460 
XX-Net 的 data/certs 文件夹也要删除，然后重新运行 XX-Net。
不然你删它干嘛，换 SS 之类就不用操心了。
基础的概念还是要了解一下的。

**Comment by peach5460** [comment]
@SeaHOH 
删了data/certs 果然好了
谢谢

另外,不好意思,对证书这玩意的设置不是很了解...

**Comment by jzp820927** [comment]
问题出自子证书，不是根证书，所以要删 certs

**Comment by SeaHOH** [comment]
的确是都 10 年，昨天才发现去年 8 月就改了。
关键还是 3.3.1 的证书更新，很多人只更新 XX-Net，没动证书，所以昨天 Chrome 更新就杯具了。

**Comment by lewisgit** [comment]
在火狐下，输入about:config, 添加security.enterprise_roots.enabled布尔值，设置为TRUE。 这样就可以访问了，虽然没有解决证书的问题，但是可以访问了

**Comment by JustgoFlyme** [comment]
将XXnet文件夹下\data\gae_proxy\certs中的证书全部删除就可以了

**Comment by JustgoFlyme** [comment]
delete xxnet/data/gae_proxy/certs




发自网易邮箱大师
在2017年04月25日 08:30，RogerLee 写道：

Closed #5310.
