### ISSUE TITLE
xx-net检测到我有一个app id是不存在的,不过是申请一直使用的

### ISSUE THREAD

**Issue by entao** [XX-net/XX-Net#5314]
xx-net检测到我有一个app id是不存在的,不过是申请一直使用的。google网站上面显示此id：Your app is currently disabled,不知道为什么。明明有这个id,为什么xx-net给踢出来

**Comment by FocusChan** [comment]
是不是复制粘贴的时候前面多打了一个空格？？

**Comment by entao** [comment]
没有多余空格，特意复制了一遍的

**Comment by jzp820927** [comment]
浏览器打开  https://你的appid.appspot.com  看看结果显示的什么内容？
