### ISSUE TITLE
一直不能访问，证书重新安装也不行

### ISSUE THREAD

**Issue by xiehui999** [XX-net/XX-Net#5317]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:3000
network-status: OK
connected-link: new:2 used:0
worker: h1:26 h2:2
scan-ip-thread-num: 41
ip-quality: 316
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xiehui999** [comment]
之前好好的，今天不能访问了，提示
您的连接不是私密连接

攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by johnbitcn** [comment]
是升级了chrome 5.8 的问题，目前chrome对证书进行严格管理造成的结果。

**Comment by SeaHOH** [comment]
我十分不理解为什么要发这么多相同主题的 issuse。

**Comment by jzp820927** [comment]
我也不理解，还是说明一下吧，升级到 3.3.1，删除data，删除导入浏览器的证书，重启 XX，重新导入 XX 新的证书。

**Comment by a1307743680** [comment]
觉得不新开一个关注的人会少一点吧，可能。也是用各种chrome更新器的锅，谁让chrome更新了呢，没用更新器半年不升级一次的，还有3.3.1还是beta啊

**Comment by jzp820927** [comment]
现在已经不存在什么 beta 了，能有个更新都是奢望了。
