### ISSUE TITLE
Chrome 自动更新为 58 版后 XX-Net 失效

### ISSUE THREAD

**Issue by He110te4m** [XX-net/XX-Net#5321]
# 尝试 #
- 关闭 Chrome 和 XX-Net，删除整个 data 文件夹及所有内容，结果：无效
- 关闭 Chrome 和 XX-Net，删除计算机中的 GoAgent 证书和 data 目录下的 cers 目录以及 ca 证书，重启 XX-NET 和 Chrome，结果：无效

# 计算机环境 #
Win7 64 位
# XX-Net 版本 #
3.3.1

**Comment by SeaHOH** [comment]
第二种，重启 XX-Net 是否是管理员权限，也就是说证书是否导入系统了，确认一下。

**Comment by jzp820927** [comment]
不科学。会不会是 chrome上有什么插件影响了。

**Comment by a1307743680** [comment]
证书没删干净，当前用户和本地计算机都导入了证书，
或者单纯的ip不够？
上截图，就说挂了谁都不好说

**Comment by He110te4m** [comment]
已经好了，是证书没删除干净，谢谢各位了~

**Comment by cuiyuzhong** [comment]
请问没删除干净是什么意思？我在mac下面也遇到了这个问题。删除了certs目录、CA.crt文件。还是不行。还需要删除什么文件么？

**Comment by jzp820927** [comment]
比如说，重复导入了多个相同证书的情况下，只删掉了其中一个，自己做证书列表里面检查下，就能发现了。

**Comment by cuiyuzhong** [comment]
没发现@_@，safari都是好的，chrome就是不行。

**Comment by jzp820927** [comment]
那就把 XX 全部删掉，从头做一次

**Comment by cuiyuzhong** [comment]
搞定了，非常感谢:)
