### ISSUE TITLE
goagent 3.3.0在Firefox 53.0中google等使用不正常

### ISSUE THREAD

**Issue by ChenXingbo** [XX-net/XX-Net#5323]
今天Firefox自动更新到53.0，打开后google出现问题，使用地址栏搜索提示该页无法显示，单独输入google.com可以访问，可以搜索，但是搜索结果无法打开，同样提示无法显示，但twitter，youtube等网站访问正常。

**Comment by SeaHOH** [comment]
goagent 3.3.0？没这版本吧。

**Comment by ChenXingbo** [comment]
错了错了，是XX-NET 3.3.0

**Comment by jzp820927** [comment]
先升级到最新版 3.3.1 吧
