### ISSUE TITLE
XX-net在firefox 53.0下google不能用，twitter的t.co短链接也打不开

### ISSUE THREAD

**Issue by ChenXingbo** [XX-net/XX-Net#5324]
今天Firefox自动更新到53.0，打开后google出现问题，使用地址栏搜索提示该页无法显示，单独输入google.com可以访问，可以搜索，但是搜索结果无法打开，同样提示无法显示，但twitter，youtube等网站访问正常。

**Comment by a1307743680** [comment]
所有搜索结果还是特定某个？

**Comment by SeaHOH** [comment]
来几张截图

**Comment by ChenXingbo** [comment]
截图传不上来呀，全部结果都是这样子，但是在IE里就没有问题，所以怀疑是FF 53.0的问题

**Comment by SeaHOH** [comment]
估计是证书问题，参见其它帖子。

**Comment by jzp820927** [comment]
https://www.google.com/ncr

**Comment by ChenXingbo** [comment]
尝试过了删除证书，升级3.3.1还是同样的问题，准备降级FF了

**Comment by ChenXingbo** [comment]
找到问题了，应该是FF升级到53.0后，导致AUTOPROXY FIX（0.4b2.2013051811.5）插件出现了问题，现在换成FOXYPROXY就好了

**Comment by qingjiangshui** [comment]
AUTOPROXY FIX（0.4b2.2013051811.5）有哪位大侠做更新吗？

**Comment by jzp820927** [comment]
我觉得 FF 用 pac 最合适，什么插件都不用装
