### ISSUE TITLE
XX-Net打开后没有反应，但是可以翻墙了

### ISSUE THREAD

**Issue by angus96** [XX-net/XX-Net#5325]
xx-net版本是3.3.0
之前用的都挺正常的，重启电脑后发现打开XXnet快捷方式没有反应了，右下角任务栏也没有xxnet图标，在目录里手动打开start.vbs也没有效果
在浏览器手动输入127.0.0.1:8085提示无法访问此网站
但是还是可以翻墙上网的...
求大佬看看是什么问题

**Comment by angus96** [comment]
@jzp820927
@xxnet
@yeahwu 
@simonasd

**Comment by angus96** [comment]
@jzp820927
@xxnet
@yeahwu 
@simonasd

**Comment by jzp820927** [comment]
你的意思是，不打开 XX 也能翻墙？这个太不科学了吧，是不是 XX 在后台运行的？看看任务管理器，是不是有 python 的进程。

**Comment by angus96** [comment]
@jzp820927 有python进程的，不是不打开xx，是有进程在运行，但是任务栏没有xxnet图标，localhost也进不去

**Comment by jzp820927** [comment]
或者你可以把进程啥了，然后再运行试试

**Comment by angus96** [comment]
@jzp820927 杀了也不行...重启关机也试过了...一气之下刚刚把xxnet删除了再重新部署配置就行了...不过还是不是到为什么会出现这种情况，可不可能跟我安装了proxifier然后又卸载了有关？

**Comment by jzp820927** [comment]
既然处理好了，就不去追究原因了吧

**Comment by angus96** [comment]
我以为大佬都是把每个问题都追究到底的。。。😂。。

**Comment by jzp820927** [comment]
能找到原因当然最好，不过，你这种情况，我能想到的问题，都说了，都没解决问题，使用我也没辙了。而且很多时候问题的根源在于自己，比如因为安装的某个插件，或者软件，导致间接影响 XX 出现问题。这种情况不属于大众化，所以很难分析

**Comment by angus96** [comment]
好的，谢谢大佬的帮助@jzp820927
