### ISSUE TITLE
浏览器代理设置Fail，CA证书状态Fail

### ISSUE THREAD

**Issue by beyondyun** [XX-net/XX-Net#5330]
有人和我一样的状况吗？从新导入证书没法解决，打开网页显示隐私设置错误，你的链接不是私密链接，配置页提示检查浏览器代理设置，但是没动过代理设置，下面是诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1394
network-status: OK
connected-link: new:1 used:0
worker: h1:19 h2:9
scan-ip-thread-num: 500
ip-quality: 292
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by lmislm** [comment]
#5311 参考5311里面的讨论，应该是你更新chrome之后。我的方法是：
更新chrome浏览器后，ff是可以用的。（或者你可以重下3.3.1，没试过）

在ff，xx-net管理中点击配置->更新
到3.3.1然后找到原目录。XX-Net-3.3.0\data\gae_proxy\certs
把certs全部删除。
重启xx-net和chrome既可。

**Comment by a1307743680** [comment]
参考#5322

**Comment by miss13** [comment]
试一试这个方法：3.3.0 也是可以正常使用的，需要在XX-Net\code\default\gae_proxy\local\cert_util.py修改一个被注释的一行。应该是252行。

应该是chrome58 新版本对证书的机制有所改变

1 在你的XX-Net 本地代码目录找到 cert_util.py 这个文件，在代码的这个
https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/cert_util.py#L252
位置，也许你代码位置不一样，找到同样的这一行代码，将#去掉
2 同样是在XX-Net的本地代码目录里，删除 \data\gae_proxy\目录下的CA.crt文件 和 certs目录
3 重启 XX-Net 即可

**Comment by jzp820927** [comment]
最新版的 XX 已经不用修改代码了。直接下载最新版就行了

**Comment by peing** [comment]
完成上述操作后恢复正常
但浏览器仍显示为浏览器代理设置Fail，CA证书状态Fail。

**Comment by peing** [comment]
清除IE的cookie问题便解决了。

**Comment by beyondyun** [comment]
问题已经解决了，谢谢大家！
发自网易邮箱大师
在2017年04月25日 12:32，彭卓 写道： 清除IE的cookie问题便解决了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/XX-net/XX-Net","title":"XX-net/XX-Net","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/XX-net/XX-Net"}},"updates":{"snippets":[{"icon":"PERSON","message":"@peing in #5330: 清除IE的cookie问题便解决了。 \r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/XX-net/XX-Net/issues/5330#issuecomment-296901497"}}}

**Comment by jzp820927** [comment]
解决了就 close 吧
