### ISSUE TITLE
关于“打开xx-net后出现，（连接超时，请检查代理服务器）”的问题

### ISSUE THREAD

**Issue by xwtwzyzl** [XX-net/XX-Net#5332]
首先声明，我只是xx-net的使用者，不懂技术。
接下来说我遇到的问题及解决的过程：
一直在使用xx，直到前一段时间，在打开xx后出现了“连接超时请检查代理服务器”页面，然后来到lssues想找到问题的所在，按照所找到的解决方法逐一实验，然而都不可行。我用的是win10+chorme+ Omegaoptiones，还有腾讯管家，当时认为是腾讯管家的问题，所以打算格式化重装系统，在重装系统之前，打算先把win10升级先到（创新者）版，升级后win10的版本号是1607，然后就是问题解决了。
所以，我认为这个是win10的问题，升级到新版本就行了。

**Comment by jzp820927** [comment]
低概率事件

**Comment by SeaHOH** [comment]
一般浏览器让你“请检查代理服务器”就真的是要检查，很可能代理设置是错误的或代理没有正常监听需要重启。
