### ISSUE TITLE
CHROME 58  XX-NET 3.3.0 不管是全局GAE或者全局pac都提示您的连接不是私密连接

### ISSUE THREAD

**Issue by TonyAaron1206** [XX-net/XX-Net#5334]
您的连接不是私密连接，攻击者可能会试图从mail.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID
设置里显示 浏览器代理设置 FAIL
                   CA证书FAIL
我已经采取的措施：证书我按照之前的方法已经删除了 之后又重新自动生成导入了   还是这样，重新安装CHROME 58和XX net依旧无解，也已经重新部署了，仍旧没用

**Comment by jzp820927** [comment]
#5322

**Comment by gatieme** [comment]
+1，同求

**Comment by jzp820927** [comment]
+1，同答

**Comment by TonyAaron1206** [comment]
@jzp820927 多谢多谢  好了  哈哈

**Comment by gatieme** [comment]
@jzp820927 谢啦

**Comment by YKJL** [comment]
@jzp820927 5322什么意思

**Comment by jzp820927** [comment]
解决问题的一个链接，鼠标点击就行了。
