### ISSUE TITLE
试了各种方法，检查了各项配置，全局智能代理还是提示请检查浏览器设置，咋办？

### ISSUE THREAD

**Issue by bianqsh** [XX-net/XX-Net#5347]
诊断信息如下：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2140 good:1786
network-status: OK
connected-link: new:0 used:0
worker: h1:17 h2:16
scan-ip-thread-num: 50
ip-quality: 274
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
#5322

**Comment by bianqsh** [comment]
试过了，好像还是不行

**Comment by jzp820927** [comment]
估计是你操作问题，最重要的是要 删除 data，删导入浏览器的证书。

**Comment by bianqsh** [comment]
解决了，非常感谢！！
