### ISSUE TITLE
新版FireFox已经不能再加证书了

### ISSUE THREAD

**Issue by ace4dude** [XX-net/XX-Net#5348]
Ubuntu上的新版FireFox已经不能再加证书了——尝试了无数次都不行！现在使用https加密的网站FireFox都不能上了。现在的新版FirFox好像在安全设置上有根本性的改变，许多以前的插件包括淘宝的安全插件都不能用了。

XX-Net Status:

sys-platform: x86_64, Linux-3.19.0-80-generic-x86_64-with-Ubuntu-14.04-trusty
os-system: Linux
os-version: #88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017
os-release: 3.19.0-80-generic
os-detail: Dist:Ubuntu; Version:14.04; ID:trusty
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
xxnet-version: 3.3.1

python-version: 2.7.6
openssl-version: 16.0.0 TLSv1_2 h2:npn

ipv6-status: 0
gws-ip-num: total:3000 good:3000
network-status: OK
connected-link: new:2 used:0
worker: h1:6 h2:4
scan-ip-thread-num: 50
ip-quality: 198
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
没试过，围观~

**Comment by THLIVSQAZ** [comment]
你的还比我好，xx-net没有key文件，ubuntu的firefox非要crt+key才能导入

**Comment by jzp820927** [comment]
@ace4dude 不太可能吧，是不是你权限不足，是不是 root 用户操作的？

**Comment by ace4dude** [comment]
按照 #5361的讨论，还真是因为cert8.db的原因。只需将~/.mozilla/firefox/xxxxxxx.default/cert8.db删除或改名后，重新启动FireFox生成新的cert8.db即可。现在连支付宝的安全插件也可以用了！Awesome!
