### ISSUE TITLE
Chrome 58后无法使用

### ISSUE THREAD

**Issue by tomorrowin** [XX-net/XX-Net#5351]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:141 good:119
network-status: OK
connected-link: new:2 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 50
ip-quality: 515
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

出现：请检查浏览器代理设置。
访问goolge出现这个问题：
Your connection is not private
Attackers might be trying to steal your information from encrypted.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_INVALID

问题#5322 答案，我试过了，还是不行

**Comment by THLIVSQAZ** [comment]
尝试多几次，证书删除干净，可以解决的

**Comment by lineex** [comment]
今天晚上刚更新了chrome 然后就不能用了。其他浏览器正常

**Comment by tomorrowin** [comment]
怎么尝试多次？我重装xx-net和Chrome插件，还有按照#5322  方法试了很多次了，都无法解决问题。@THLIVSQAZ

**Comment by taoist1994** [comment]
重点是要把data\gae_proxy\certs文件夹删掉，chrome提示的错误就是证书的问题。

**Comment by THLIVSQAZ** [comment]
那我也帮不了你了，我一次就过了，没有出现那么多问题

**Comment by jzp820927** [comment]
LS 各位正解
