### ISSUE TITLE
Google Chrome 版本 58.0.3029.81 (64-bit)   XX-Net 版本: 3.3.1 一直提示您的连接不是私密连接

### ISSUE THREAD

**Issue by heigoo** [XX-net/XX-Net#5358]
![image](https://cloud.githubusercontent.com/assets/19522749/25370255/013d1f1a-29bc-11e7-9806-752a317749ec.png)
其他浏览器没有此问题。

**Comment by jzp820927** [comment]
#5322

**Comment by mizhiyusu** [comment]
同此问题，分别重装了chrome和xx-net都没用。

**Comment by mizhiyusu** [comment]
同时证书栏内有不能删除的goAgent证书

**Comment by diehard0823** [comment]
不要在浏览器里删，从windwos删就可以了。删除后重新安装有可能还会提示失败，不要管他，等十分钟以后再刷新，说不定就好了。我重装了好几次证书都不行，然后去干别的事，回来一看正常了。

**Comment by azluck** [comment]
证书删除可参考：
http://www.iefans.net/windows7-ie8-zhengshu-wufa-shanchu/

**Comment by a1307743680** [comment]
@mizhiyusu 那是导入本地计算机的证书，证书栏是当前用户的，所以只显示有，不能删除，如是win10pro用certlm.msc删，其他系统不确定，有人反映没这一东西，可以试试控制面板搜索 证书

**Comment by Hanleyz** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:6560 good:4555
network-status: OK
connected-link: new:2 used:0
worker: h1:19 h2:1
scan-ip-thread-num: 0
ip-quality: 299
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by j1angvei** [comment]
我也遇到了这个问题，无论怎么导入证书，设置全局模式都没作用。

**Comment by dfsr** [comment]
我也碰到这个问题，是不是等下一个chrome版本才行呢？

**Comment by rockleeyuetian** [comment]
同问，有没有哪位找到解决方案了的呢？ 我想重新安装低版本的chrome也安装不了，郁闷

**Comment by jzp820927** [comment]
#5322   请根据此 issues ，一步一步仔细操作。
