### ISSUE TITLE
很好奇，最近的网络是不是有异常？

### ISSUE THREAD

**Issue by theratlesnake** [XX-net/XX-Net#5360]
近段时间可以明确的感受到GFW的干扰好像很不给力，因为网速提速太多了，而且延迟也低，同时，这段时间推特上也在发生着让国内某些大人物很紧张的事，导致大量的国人翻墙上推，按道理，应该是加强GFW干扰才对，结果却是相反的结果，究竟是什么原因呢？想不通。 @xxnet @yeahwu @jzp820927 @breakwa11

**Comment by jzp820927** [comment]
说不定这只是黑暗前的黎明。
