### ISSUE TITLE
Ubuntu FireFox证书导入问题

### ISSUE THREAD

**Issue by kidloserme** [XX-net/XX-Net#5361]
Ubuntu 16.04 , FireFox 53
我在Chrome中导入证书已经可以成功访问谷歌，但是FireFox还是不行，提示：
**“www.google.com 的管理员未正确配置网站。为避免您的信息被窃，Firefox 没有建立与该网站的连接。
此网站使用了 HTTP 严格传输安全（HSTS），要求 Firefox 只进行安全连接。正因如此，您不能为此证书添加一个例外。”**

然后我就导入证书，FireFox中导入证书，但是证书列表中并没有显示GoAgent的证书，导入证书的时候也没有报错，所以很是奇怪。

另外FireFox访问谷歌报错信息：
4月 26 07:54:18.74 - [ERROR] ssl.wrap_socket(self.connection=
4月 26 07:54:18.74 - [ERROR] Except stack:Traceback (most recent call last): File "/home/helong/XXnet/XX-Net-3.3.0/code/default/gae_proxy/local/proxy_handler.py", line 314, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib/python2.7/socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib/python2.7/ssl.py", line 756, in recv return self.read(buflen) File "/usr/lib/python2.7/ssl.py", line 643, in read v = self._sslobj.read(len) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c :1754)

纠结这个问题主要是因为intellij idea访问谷歌报证书不受信任，不知道这个怎么解决，是不是跟firefox的证书有关。

**Comment by kidloserme** [comment]
试了在Mac下FireFox 53导入证书是没问题的，但是在Ubuntu下导入证书后在证书机构列表中是看不到的

**Comment by jzp820927** [comment]
是不是权限不够？是不是在 root 下面操作的？

**Comment by SeaHOH** [comment]
已有两例，似乎是 cert8.db 不完全兼容当前版本，删除让它重新生成就好了。

**Comment by kidloserme** [comment]
@SeaHOH 多谢了，确实是cert8.db的问题，删除旧的重新生成了一个导入成功了
