### ISSUE TITLE
访问的不是私密链接

### ISSUE THREAD

**Issue by huanhulan** [XX-net/XX-Net#5366]
---
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:30 good:23
network-status: OK
connected-link: new:0 used:0
worker: h1:5 h2:8
scan-ip-thread-num: 50
ip-quality: 971
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
---

按照issue5322试了好几次，也没办法解决

**Comment by Jack-ban** [comment]
chrome是不是版本58的，如果是的就将xx-net升级到3.1试试。

**Comment by huanhulan** [comment]
@Jack-ban 是58，刚刚从3.1升级到3.3.1的。。。因为3.1升级后就不能用了

**Comment by huanhulan** [comment]
另外，证书始终是fail

**Comment by xiaochanglaoshi** [comment]
我也是遇到这样的一个问题  ，在谷歌浏览器里面一直都是失败的 在firefox上的是可以用的

**Comment by Seraphli** [comment]
我也刚升级到了58,然后xx-net 3.3.0 提示不是私密链接 之前没升级chrome可以用的

**Comment by huanhulan** [comment]
@xiaochanglaoshi 对，ff没问题

**Comment by huanhulan** [comment]
。。。通过ff设置完appid后，chrome也可以用了

**Comment by Seraphli** [comment]
通过 #5322  解决了

**Comment by jzp820927** [comment]
@xiaochanglaoshi 请确认 data 删除干净，浏览器证书清除干净。再不行，就把 XX 全部删掉，重新下载。
解决了就 close 吧。

**Comment by mqhu0222** [comment]
求个mac的解决办法，我也是私密链接问题，重新导证书没用

**Comment by jzp820927** [comment]
贴状态页出来看看
