### ISSUE TITLE
X-Tunnel无法登陆，大大们帮忙看看

### ISSUE THREAD

**Issue by yaojun1314** [XX-net/XX-Net#5371]
![image](https://cloud.githubusercontent.com/assets/23252618/25470277/0bde545e-2b54-11e7-93ab-43f7e2c6a9ba.png)

**Comment by yaojun1314** [comment]
@想体验一下X-Tunnel，但是登陆出错。还有一点，新注册了11个appid，想要捐赠，哪位大大出来接受一下，顺便送我点流量玩一下。 @jzp820927，大大，出来帮忙看看。

**Comment by jzp820927** [comment]
你这个好像是没流量了

**Comment by yaojun1314** [comment]
@jzp820927 对，我发现是这么回事了。可以给我送点流量么。我已经新建了一个谷歌账户，注备捐赠appid。希望大大帮我高点流量。

**Comment by jzp820927** [comment]
我好想在另一个 issues 里面已经给你了 10G 流量了，你去查看下吧。

**Comment by yaojun1314** [comment]
@jzp820927 看到了，谢谢，我发过两个，所以。。。不好意思哈

**Comment by jzp820927** [comment]
有效期不是很长，先用着吧

**Comment by yaojun1314** [comment]
@jzp820927 刚试了一下，确实很爽，youtube 1080p一点都不卡，速度很快。再次感谢。

**Comment by jzp820927** [comment]
主要还是要靠 GAE，GAE 速度快，X-Tunnel 肯定就快，X-Tunnel 的速度是不会超过 GAE 的。
X-Tunnel 的设计初衷主要是解决手机端的证书问题。
