### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by iaminblacklist** [XX-net/XX-Net#5374]
请检查浏览器代理设置。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2638
network-status: OK
connected-link: new:1 used:0
worker: h1:9 h2:6
scan-ip-thread-num: 50
ip-quality: 263
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by iaminblacklist** [comment]
求助~

**Comment by iaminblacklist** [comment]
用#5322方法解决，感谢

**Comment by jzp820927** [comment]
close 吧
