### ISSUE TITLE
请检查浏览器代理设置，参考5322无法解决。

### ISSUE THREAD

**Issue by yuxuan1** [XX-net/XX-Net#5375]
诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:137 good:112
network-status: OK
connected-link: new:4 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 650
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

已经升级至3.3.1，无效。重启电脑，无效。重装chorme无效。
求助，折腾很长时间了。

**Comment by liumahao** [comment]
同样，我也遇到这个情况了，昨天突然开始，之前一直好好的

**Comment by jzp820927** [comment]
请仔细检查操作步骤，一定要保证旧证书删除干净，最好是把 data 全部删了，还有导入浏览器的证书也要删干净，然后重启 XX 后再导入新的证书
