### ISSUE TITLE
Add headless option 

### ISSUE THREAD

**Issue by postadelmaga** [XX-net/XX-Net#5381]
is it possible to add a option for headless start ? 
I mean something that prevent the start of the web browser and the icon in the systray.

**Comment by yeahwu** [comment]
127.0.0.1:8085
![2017-04-28](https://cloud.githubusercontent.com/assets/13328328/25514605/b6bed512-2c10-11e7-9bdf-c6abf9576766.png)

**Comment by postadelmaga** [comment]
Alright thanks
