### ISSUE TITLE
提示请检查浏览器代理设置，按#5322处理仍无效

### ISSUE THREAD

**Issue by Pyw2003** [XX-net/XX-Net#5387]
状态显示：请检查浏览器代理设置；浏览器代理设置 - Fail；CA证书状态 - Fail
按照#5322处理，删除已导入证书、certs文件夹和CA.crt文件并更新3.3.1，仍然无效，求解

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:50 good:17
network-status: OK
connected-link: new:0 used:0
worker: h1:8 h2:5
scan-ip-thread-num: 50
ip-quality: 1016
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by theratlesnake** [comment]
能上网就行啦，你管他是成功还是失败。。。

**Comment by jzp820927** [comment]
可以按 LS 所说，先测试下，能不能使用。

**Comment by if2012** [comment]
按ctrl+F5试试，能上网就行。

**Comment by Pyw2003** [comment]
但现在的问题是被墙的网站能打开，速度极慢（部分打不开报错）。

**Comment by Pyw2003** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:88 good:67
network-status: OK
connected-link: new:0 used:0
worker: h1:5 h2:11
scan-ip-thread-num: 50
ip-quality: 516
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by madshlices** [comment]
如果你的xx是开机启动，先删除xx目录里的证书文件

按#5322删了安全里的证书后最好重启一下电脑。

再重启xx-net 
再重启浏览器
有了导入证书成功的提示后再看看xx-net 的页面里的证书状态是不是正常
不正常就ctrl+F5 虽然我不知道这个命令有什么大用
有时候也不要急，等一下再刷新看一下。

**Comment by changxiangyang** [comment]
已成功解决，感谢

**Comment by zhaochenyou** [comment]
@changxiangyang  怎么解决的，我也是今天chrome开始突然证书失效，显示请检查浏览器代理设置。firefox却没问题。

**Comment by changxiangyang** [comment]
@zhaochenyou   按照#5322 的步骤弄的，一开始我弄完之后CA证书状态还是【Fail】, 但是我试着打开chrome应用商店既然能打开，于是我刷新了一下  他的状态就变成【OK】了。

**Comment by zhaochenyou** [comment]
@changxiangyang  谢啦，刚刚看issue list，发现好多这个问题，已经在搞了。

**Comment by Pyw2003** [comment]
今日打开问题突然解决，谢谢各位
