### ISSUE TITLE
Connect Blocked，第一次出现这种情况，上午升级的3.3.1

### ISSUE THREAD

**Issue by netfun2000** [XX-net/XX-Net#5393]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2018 good:1685
network-status: OK
connected-link: new:0 used:0
worker: h1:33 h2:0
scan-ip-thread-num: 50
ip-quality: 368
is-idle: 0
block-stat: Connect Blocked, 2009230397 seconds to wait.
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

看帮助，要找“建议您看看XX-Net/data/goagent/bad_ip2.txt”，但没有找到。

**Comment by SeaHOH** [comment]
跟 3.3.1 没关系，重启一次应该就好了。

**Comment by jzp820927** [comment]
没遇到过，这种情况。不明觉厉

**Comment by netfun2000** [comment]
睡了一觉，今天自己好了。
