### ISSUE TITLE
【讨论】该不该换一波亚洲appid

### ISSUE THREAD

**Issue by yuliangyang** [XX-net/XX-Net#5398]
刚才有人用我亚洲的appid，跟其欧洲appid对比，发现我的速度比他快的不是一点半点。。
反正我是没测试过。
对方测试的是goproxy，不过对方的appid没在goproxy上部署
我单独给了5个在goproxy最新版上部署的appid，那面说速度比他的快

那么，问题来了。速度问题到底是每部署goproxy引起的，还是地区引起的

**Comment by yuliangyang** [comment]
https://ctcwall.com/appid-apply/

**Comment by SeaHOH** [comment]
为什么跟欧洲比，不是该跟美洲比吗？

**Comment by yuliangyang** [comment]
发现地区并没多大关系

**Comment by SeaHOH** [comment]
出口一样，当然区别不大。如果不是代理 app，还是能看出区别的。

**Comment by kirbyzhu** [comment]
我测试了一下 亚洲的地址比美中地址看youtubue速度能相差一倍。
