### ISSUE TITLE
提请“请检查浏览器代理设置。”，无法上网，哪位大神给看看咋回事啊！

### ISSUE THREAD

**Issue by bljds** [XX-net/XX-Net#5406]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:134 good:87
network-status: OK
connected-link: new:2 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 50
ip-quality: 515
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
#5322
