### ISSUE TITLE
下载速度和观看Youtube的速度差别有点大

### ISSUE THREAD

**Issue by aaron-elkins** [XX-net/XX-Net#5410]
用 XX-Net 观看 Youtube 的视频，速度一般都超过 4Mbp，有时候还能达到 10Mbp，本地是电信100Mbp的宽带。但是在Google Chrome的官网下载 Chrome 的时候，速度都不曾超过80KB，很多时间都维持在20KB左右，不知道个中原因是什么？

排除 Google Chrome 官网的速度原因，因为在我国外的 VPS 下载 Chrome，下载速度可以达到 10M左右。

XX-Net 已经可以满足我上网的需要了，只是，如果下载速度可以再提高，就更完美了。

**Comment by theratlesnake** [comment]
能用就知足吧，要想完美，肉身翻墙不就得了。

**Comment by jzp820927** [comment]
下载 chrome 用的域名是在国内的服务器，使用你在下载 chrome 的时候，完全可以不走代理，而是直连下载。

**Comment by johndong9897** [comment]
这就是我不用电信的原因。
YouTube视频下载的时候最多500kb。
一直用移动，几乎满速。速度杠杠的。可能每个地方有差别吧。

**Comment by jzp820927** [comment]
移动在全国表现都不错。

**Comment by aaron-elkins** [comment]
用电信前，我也是用 12m 的移动，后来升级到100m电信。移动有时也很不稳定，玩东南亚服的游戏的时候，ping值跳动很大，但是ping值有时很小，连新加坡，ping值在50ms左右。

现在白天直连下载 vps 的文件，可以达到1.2MB/s, 但到了晚上，通常在20K/s左右，晚上都不敢玩外服游戏了。

**Comment by aaron-elkins** [comment]
我的vps的速度，下行和上行都接近 100mb/s.

**Comment by theratlesnake** [comment]
我的免费VPN，1080P都不成问题。

**Comment by jzp820927** [comment]
移动就是带宽足，如果要说延迟的话，还是电信好，因为骨干网都是电信的。

**Comment by Jan9th** [comment]
翻墙看视频一直很慢，已经部署了自己的 appId ，不知道你们都是怎么使用的

**Comment by jzp820927** [comment]
主要还不是看 IP，估计是的 IP 质量不佳
