### ISSUE TITLE
XX-NET总是提醒请检查浏览器代理设置。

### ISSUE THREAD

**Issue by tongyiwangzaimilk** [XX-net/XX-Net#5412]
-----------
XX-NET突然不好用……不管怎么更改浏览器代理设置，总是不行。不太懂为什么，能帮忙看下吗？

-----------
诊断信息：
sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.2604.400 QQBrowser/9.6.11013.400
xxnet-version: 2.9.2
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 1288
network-status: OK
connected-link: 5 / 0
scan-ip-thread-num: 50
ip-quality: 830
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
先升级到 3.3.1 再试试。
