### ISSUE TITLE
运行XX-Net，托盘图标不显示；8085页面不可以访问，无法科学上网

### ISSUE THREAD

**Issue by yimingjfe** [XX-net/XX-Net#5419]
系统：win8
chrome版本：57
[XX-Net版本：3.3.1

这是launchr.log下的信息：
```
May 03 14:03:41.885 - [INFO] use build-in openssl lib
May 03 14:03:41.887 - [INFO] start XX-Net 3.3.1
May 03 14:03:41.888 - [DEBUG] start confirm_xxnet_exit
May 03 14:03:41.891 - [DEBUG] <0>: try to terminate xxnet:8087
May 03 14:03:43.910 - [DEBUG] good, xxnet:8087 cleared!
May 03 14:03:44.913 - [DEBUG] good, xxnet:8085 clear!
May 03 14:03:44.913 - [DEBUG] finished confirm_xxnet_exit
May 03 14:03:45.970 - [INFO] module gae_proxy started
May 03 14:03:45.970 - [INFO] start gae_proxy time cost:1052 ms
```

**Comment by theratlesnake** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by jzp820927** [comment]
先升级到最新版 3.3.1 试试

**Comment by yimingjfe** [comment]
@jzp820927   端口是我输入错了，但是其实8085页面也打不开；最重要的是无法翻墙。

**Comment by jzp820927** [comment]
你打开网页的时候，显示什么？

**Comment by yimingjfe** [comment]
@jzp820927 打开网页和没开xx-net是一样的，右下角的托盘图标也没有；执行start.bat显示error：

![xxnet](https://cloud.githubusercontent.com/assets/10381581/25652093/019c919e-3019-11e7-8863-debfb5b3d913.png)

**Comment by jzp820927** [comment]
哦，我知道了，你这个是端口占用，你是不是同时运行了 SS 客户端了？把 1080 端口占用了？

**Comment by yimingjfe** [comment]
谢谢，确实是端口占用的问题，是window的svchost.exe占用这个端口。
