### ISSUE TITLE
手机chrome 也升级到58了，https怎么办呢

### ISSUE THREAD

**Issue by Wintrynoel** [XX-net/XX-Net#5422]
安卓原生7.1.2 
xxnet 3.3.0
chrome 58
xx的使用方式是在系统代理那设置pac
现在http的网页可用
已经尝试使用pc上3.3.1的证书但并没有效果
请问怎么办呢

**Comment by jzp820927** [comment]
XX 升级到 3.3.1，然后按照 #5322 操作。
