### ISSUE TITLE
手机chrome 也升级到58了，https怎么办呢？

### ISSUE THREAD

**Issue by Wintrynoel** [XX-net/XX-Net#5423]
安卓原生7.1.2
xxnet 3.1.0
chrome 58
xx的使用方式是在系统代理那设置pac
http的网页可用
已经尝试使用pc上3.3.1的提供的证书但并没有效果
请问怎么办呢

**Comment by jzp820927** [comment]
XX 升级到 3.3.1，然后按照 #5322 操作。

**Comment by Wintrynoel** [comment]
是手机版的问题呢~

**Comment by Yogg-Saron** [comment]
和 #5322 的操作步骤一致，相当于手动从3.3.0 升级到3.3.1
0 退出XX-net
1 sdcard/xx-net/code/default/gae_proxy/local/cert_util.py#L252
删除掉注释前的#
2 删除掉同目录cert_util.pyc文件
3 删除掉 sdcard/xx-net/data/gae_proxy/CA.crt 与 certs文件夹
4 删掉手机的证书
5 重启xx-net
6 重新导入一次sdcard/xx-net/data/gae_proxy/CA.crt的证书，看时间，是5生成的。
7 done

**Comment by jzp820927** [comment]
不管是什么平台，必须把 XXNET 升级到 3.3.1，然后按照 #5322 操作。

**Comment by Wintrynoel** [comment]
可以了呢，蟹蟹各位~

**Comment by jzp820927** [comment]
OK 了，就 close 吧
