### ISSUE TITLE
按教程设置好后 ----重启电脑重启xx-net  ----始终提示【请检查浏览器代理设置】

### ISSUE THREAD

**Issue by swifttao** [XX-net/XX-Net#5436]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7600-SP0
os-system: Windows
os-version: 6.1.7600
os-release: 7
os-detail: Version:6-1; Build:7600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2851
network-status: OK
connected-link: new:3 used:0
worker: h1:14 h2:5
scan-ip-thread-num: 49
ip-quality: 431
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
#5322

**Comment by swifttao** [comment]
按照 #5322 已成功解决，谢谢你们的帮助！

**Comment by xyf1219** [comment]
@swifttao 那把这个 issue 关了呀
