### ISSUE TITLE
配置appid后是否要下载其他vpn

### ISSUE THREAD

**Issue by watanabejump** [XX-net/XX-Net#5439]
除了配置appid外没有下载其他的vpn，是否需要下载新的vpn，或者？感谢解答

**Comment by jzp820927** [comment]
只要你的 VPN 服务器上日本的就可以了。VPN，好像和 xxnet 没啥关系，你是不是 issues 发错地方了？

**Comment by watanabejump** [comment]
除了xxnet我没有下载其他的vpn，但是配置了appid。需要下载其他的vpn吗？我对这方面不是太懂，可以解答一下吗？

**Comment by jzp820927** [comment]
完全不懂你想问什么

**Comment by watanabejump** [comment]
意思就是配置appid的时候如何选择区域
发自网易邮箱大师
在2017年05月05日 11:15，天朝屁民 写道： 完全不懂你想问什么

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/XX-net/XX-Net","title":"XX-net/XX-Net","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/XX-net/XX-Net"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jzp820927 in #5439: 完全不懂你想问什么"}],"action":{"name":"View Issue","url":"https://github.com/XX-net/XX-Net/issues/5439#issuecomment-299360955"}}}

**Comment by jzp820927** [comment]
关于选择区域的操作，请参考 https://github.com/XX-net/XX-Net/issues/4720
