### ISSUE TITLE
请问 "CA.crt"  和 "certs/" 下的 那些文件 有什么 区别 和 关系.

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#5446]
今天 给 rust 的 cargo 配 代理的时候, 在 `certs/` 下没找到 cargo 或 rust 相关的 .crt 文件,
但是 指定了 `CA.crt`, 然后就可以用 xxnet 代理的.

我对这块不是很熟悉, 所以想请教下:
1) `CA.crt`  和 `certs/` 下的 那些文件 有什么 区别 和 关系.
2) 我们在其他工具里 要指定 CA 文件时, 是不是 直接指定 那个 `CA.crt` 就可以了, 而不用管 `certs/` 目录下的子文件?

谢谢

**Comment by wenliyang** [comment]
CA.crt 是 XX-Net 的证书文件
certs 文件夹下是访问网站时根据你的证书文件自动生成的网站对应证书文件，第一次访问网站时会自动生成，所以随时可以删除，而且更新 CA.crt 必须删除此文件夹才会再次自动生成新的网站对应证书

**Comment by kuchaguangjie** [comment]
@wenliyang 多谢 !
