### ISSUE TITLE
升级python

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#5447]
非常感谢 @xyuanmu 兄升级了下Python版本为2.7.13，大家可以试试。
下载：
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by SeaHOH** [comment]
pyd 文件没有更新，会不会影响正常使用？

**Comment by xyuanmu** [comment]
@SeaHOH 忘了更新，实际使用没有问题，重新提交了pull

**Comment by gtwwrrrr** [comment]
@yeahwu 还有一个分支没合并的

**Comment by yeahwu** [comment]
合并了，辛苦大家了。

**Comment by gtwwrrrr** [comment]
6道工序更新ipv6列表
1.获取google ipv6 hosts列表
2.excel整理出可用ip与sn域名
3.ping筛选去掉已屏蔽ip
4.更改ip列表格式并导出txt文件
5.导入xx-net 并检查所有ip,重复3次
6.去掉无效的ip,生成新的 good_ipv6.txt

如果还有问题,可以再次用检查所有ip的方式去掉无效ip
上次更新已经是一年前了,其间不少ip已失效,请务必更新ipv6列表至最新版本

**Comment by yeahwu** [comment]
已合并，谢谢！大家给力

**Comment by yaojun1314** [comment]
可以说一下步骤么？ @yeahwu 谢谢哈，另外，这个版本跟3.3.1有什么区别么？

**Comment by roc1010kmt** [comment]
win10卡頓爆音問題不知解決了沒？

**Comment by roc1010kmt** [comment]
啟動不了，閃退，怎麼回事？

**Comment by jzp820927** [comment]
不应该吧，有报错么？

**Comment by roc1010kmt** [comment]
點start.bat啟動，窗口閃退，沒有报错。win10

**Comment by jzp820927** [comment]
没有报错？那就不好分析了，有可能是系统问题。你什么系统？或者试试命令行启动？

**Comment by yeahwu** [comment]
好滴，明天一早合并！辛苦了
xyuanmu <notifications@github.com>于2017年5月9日 周二19:49写道：

**Comment by wpyok500** [comment]
1、win10 1703前的版本好像没这个问题。
2、在1703版只会创建data文件夹及任务管理程序中有pythonw.exe在运行，但就是没运行GoAgent
3、使用管理员权限运行bat，有运行python和GoAgent。
可能是出在win10 1703版运行vbs没使用到管理员权限。
