### ISSUE TITLE
证书导入总是失败

### ISSUE THREAD

**Issue by always-waiting** [XX-net/XX-Net#5449]
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016
os-release: 4.4.0-21-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.81 Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:73 good:62
network-status: OK
connected-link: new:2 used:0
worker: h1:6 h2:2
scan-ip-thread-num: 50
ip-quality: 272
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by always-waiting** [comment]
下载了新的证书，导入后还是说证书失败，不知道为什么

**Comment by always-waiting** [comment]
![Uploading Screenshot from 2017-05-06 13-37-21.png…]()

**Comment by wenliyang** [comment]
升级到 3.3.1，然后 #5322
