### ISSUE TITLE
不能用……

### ISSUE THREAD

**Issue by JohnAppleseeder** [XX-net/XX-Net#546]
如题，打开之后无法访问墙外（网络连接错误），墙内很流畅，导入自己的appid也没反应，360：127.0.0.1：8087，swichysharp使用系统代理模式，
XX-Net Version	1.14.10
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
Google IP	3000
connected link(帮助)	0,0
ip-connect-interval	10
scan ip thread num	20
block stat(帮助)	Blocked, 5 seconds to wait.
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by JohnAppleseeder** [comment]
24 16:54:10 - [DEBUG] get ip:83.100.221.250 t:785
Jun 24 16:54:10 - [DEBUG] get ip:118.143.88.20 t:785
Jun 24 16:54:12 - [DEBUG] create_ssl 64.233.161.17 fail:timed out cost:4005 h:0
Jun 24 16:54:12 - [DEBUG] create_ssl 118.174.27.245 fail:timed out cost:4004 h:0
Jun 24 16:54:12 - [DEBUG] create_ssl 1.179.252.123 fail:timed out cost:4003 h:0
Jun 24 16:54:13 - [DEBUG] create_ssl 1.179.249.236 fail:timed out cost:4003 h:0
Jun 24 16:54:13 - [DEBUG] get ip:64.233.189.198 t:786
Jun 24 16:54:13 - [DEBUG] create_ssl 220.255.5.222 fail:timed out cost:4006 h:0
Jun 24 16:54:13 - [DEBUG] get ip:74.125.30.31 t:786
Jun 24 16:54:13 - [DEBUG] create_ssl 82.135.118.53 fail:timed out cost:4003 h:0
Jun 24 16:54:13 - [DEBUG] get ip:203.117.34.177 t:786
Jun 24 16:54:14 - [DEBUG] create_ssl 1.179.251.231 fail:timed out cost:4003 h:0
Jun 24 16:54:14 - [DEBUG] get ip:193.134.255.25 t:786
Jun 24 16:54:14 - [DEBUG] create_ssl 58.145.238.24 fail:timed out cost:4003 h:0
Jun 24 16:54:14 - [DEBUG] get ip:216.58.217.168 t:786
Jun 24 16:54:14 - [DEBUG] create_ssl 83.100.221.250 fail:timed out cost:4003 h:0
Jun 24 16:54:14 - [DEBUG] get ip:1.179.252.153 t:786
Jun 24 16:54:14 - [DEBUG] create_ssl 118.143.88.20 fail:timed out cost:4006 h:0
Jun 24 16:54:15 - [DEBUG] get ip:64.233.160.132 t:786
Jun 24 16:54:15 - [DEBUG] get ip:1.179.249.45 t:786
Jun 24 16:54:15 - [DEBUG] get ip:64.15.119.123 t:786
Jun 24 16:54:15 - [DEBUG] get ip:106.162.192.182 t:78
循环………………

**Comment by linhua55** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Blocked
或用1.15.2版本

**Comment by simonasd** [comment]
状态信息里面显示你遇到了屏蔽。参见https://github.com/XX-net/XX-Net/wiki/GoAgent-Blocked

**Comment by JohnAppleseeder** [comment]
怎么解决呢？

**Comment by JohnAppleseeder** [comment]
XX-Net Version	1.14.10
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
Google IP	3000
connected link(帮助)	10,3
ip-connect-interval	10
scan ip thread num	20
block stat(帮助)	OK
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36
