### ISSUE TITLE
start.vbs双击之后，弹出Windows Script Host （win10系统）

### ISSUE THREAD

**Issue by a13821190779** [XX-net/XX-Net#5463]
## 如题，打不开start.vbs文件，并且弹出  Windows Script Host，内容如下

```
脚本：C:\Users\xx\AppData\Local\Temp1_XX_Net-3.3.0.zip\XX-Net-3.3.0\start.vbs
行：64
字符：1
错误：系统找不到指定的文件
代码80070002
源：（null）
```

**Comment by jzp820927** [comment]
@a13821190779 自动升级后删除Code文件夹里面的version文件，退出重新双击XX快捷方式就能用了做，并且不用自动升级。以上就是当时的解决方法

**Comment by a13821190779** [comment]
@jzp820927  问题是，我按照github上xx-net的方法第一步，启动 vbs 都不行，我还没有走到XX快捷方式那一步呢

**Comment by jzp820927** [comment]
还有一个解决方法就是从  https://github.com/XX-net/XX-Net/releases  下载

**Comment by a13821190779** [comment]
@jzp820927  我试过了，不行，我重新下载了好几个版本，都是同样的问题

**Comment by yeahwu** [comment]
试试更新一下windows系统，应该是环境缺失导致的。

**Comment by jzp820927** [comment]
好吧，Linux 用户表示无能为力了，按照 Y 大说的试试吧

**Comment by a13821190779** [comment]
@yeahwu  是啊，我查了好久，有一些信息说是缺少啥环境安装包啥的，但是我弄了半天也不会弄- - 
我是自己做了win10的系统，然后东西全部格式化了，所以才需要重新安装XX-NET。
安装win10系统是在 i tell you 里找的win10，1703版本，然后用老毛桃做的U盘启动装的系统。
做好系统之后就出现这个问题了

**Comment by jzp820927** [comment]
vbs 不行，试试 bat 呢？

**Comment by a13821190779** [comment]
@jzp820927  试过了的，是在不知道怎么解决才来提issue的

**Comment by yeahwu** [comment]
把windows上的补丁都打上，然后，再启动xx试试！

**Comment by a13821190779** [comment]
@yeahwu  你说的补丁是指 驱动 还是 漏洞 还是全部都加上，还有，我现在电脑是“裸奔”，从网上看到的说win10的系统防护已经很好了，所以我就选择裸奔了，如果要是打补丁的话，用什么软件打补丁比较安全，快捷。
我对这块不了解，问的问题不是很专业，但是也恳请能回答一下，谢谢

**Comment by yeahwu** [comment]
windows上不都自带 windows update吗？点击更新就好了。

**Comment by a13821190779** [comment]
@yeahwu 哦哦，我去查查，谢谢指导。不行的话晚上再来，（沮丧....

**Comment by jzp820927** [comment]
再不行，就直接 cmd 下面 命令行启动。

**Comment by a13821190779** [comment]
@jzp820927  晚上你们说的方法，都尝试一遍，谢啦

**Comment by Wows233** [comment]
你的似乎没用完全解压。把所有zip的文件解压到一个文件夹里，我猜你是直接在压缩包里启动的吧
C:\Users\xx\AppData\Local\Temp1_XX_Net-3.3.0.zip\XX-Net-3.3.0\start.vbs
另外，别用老毛桃，会有兼容性问题。用ultraiso刻录iso文件到U盘，再启动

**Comment by a13821190779** [comment]
@Wows233 好的 我去试一下，刚到家，谢谢指导

**Comment by White99** [comment]
一样的问题，@a13821190779 你的OK了么？

**Comment by jzp820927** [comment]
@White99 看来 win10 的问题挺多的，和 LZ 一样，vbs 和 bat 都不行？

**Comment by White99** [comment]
@jzp820927   对都不行一样的错误提示，也是新系统，各种办法都试了，还是不行

**Comment by Wows233** [comment]
我另外安装了python 3.6（但是不是内置了2.7） 从https://github.com/XX-net/XX-Net/archive/3.3.1.zip 下载，解压到一个文件夹里，尝试右键管理员运行bat，给出输出

**Comment by Wows233** [comment]
我的win10怎么一点问题都没有呢。。别总赖系统啊。说什么 win10问题多。。

**Comment by jzp820927** [comment]
好像刚刚修复了一个 bug，是启动闪退的，你们马上现在最新版再试试。

**Comment by wpyok500** [comment]
1、win10   1703前的版本好像没这个问题。
2、在1703版只会创建data文件夹及任务管理程序中有pythonw.exe在运行，但就是没运行GoAgent
3、使用管理员权限运行bat，有运行python和GoAgent。
可能是出在win10  1703版运行vbs没使用到管理员权限。

**Comment by Wows233** [comment]
如果管理员运行正常，试试右键（默认没有此选项，添加请google）管理员取得所有权。
也可以：
搜索 任务计划程序
![image](https://cloud.githubusercontent.com/assets/24245520/25882672/d1271afc-3577-11e7-84cc-eca44200237c.png)
打开
![image](https://cloud.githubusercontent.com/assets/24245520/25882683/ea7e8332-3577-11e7-92ee-fa611adca976.png)
![image](https://cloud.githubusercontent.com/assets/24245520/25882709/17dff5cc-3578-11e7-94ef-cea136ece55d.png)
![image](https://cloud.githubusercontent.com/assets/24245520/25882738/408a4d9c-3578-11e7-8f59-616fd63fea37.png)
![image](https://cloud.githubusercontent.com/assets/24245520/25882762/5aabbfd0-3578-11e7-8123-36c5df5945e6.png)
选择你的bat目录，注销登陆试试

**Comment by a13821190779** [comment]
问题已解决，谢谢大家的帮助

**Comment by KyrieNakoo** [comment]
表示方法都用过了，一开始显示 “由于找不到python27.dll，无法继续执行代码，重新安装程序可能会解决问题。” 之后下载了好几个版本，双击vbs或者bat就是显示楼主的那个问题，而且解压到文件里面后 vbs bat 等好多文件都没有了。

**Comment by SeaHOH** [comment]
所以说，为什么都喜欢直接在压缩包里运行？解压后没有了是指什么，可能没下载完整，截个图看看。

**Comment by a13821190779** [comment]
这个问题我理解就是因为没解压缩，当初我直接点击 是因为 压缩文件 不太明显，我以为是解压缩的文件呢。
之后我解压缩之后就正常了

**Comment by Wows233** [comment]
Windows 自带的解压缩要全选文件然后右键复制到目录

**Comment by Hwzsnow** [comment]
同上面的老兄的问题，依旧是在win10打不开 start    ，liunx也打不开（树莓派）。
win10打开后直接弹出下列图：
![45jt8 7rt2frwdrtqxgcpm](https://user-images.githubusercontent.com/23456544/29993446-b95e227c-8fe9-11e7-8ddf-82d04de41210.png)
######################################################
and is而在树莓派上./strat  没这个指令，进入strat.sh看了下

**Comment by broardshore** [comment]
@Hwzsnow 我在win7上查看的打开方式默认是这个
![2017-09-02_14 24 30](https://user-images.githubusercontent.com/20060544/29993510-83fa4500-8feb-11e7-8ca3-5ce918015776.png)

**Comment by Hwzsnow** [comment]
@broardshore  ....好的，忘记了他是vb了

**Comment by Hwzsnow** [comment]
打开后还是闪退..............

**Comment by Hwzsnow** [comment]
@broardshore    打开后是闪退

**Comment by broardshore** [comment]
@Hwzsnow 我感觉很有可能跟你的系统缺少某些组件或功能有关，我在ghost win7以及原版win7上都运行过，均未发现该问题。建议按照楼上的建议，安装系统补丁，一些环境组件等

**Comment by xxnet** [comment]
​试试先启动cmd，再里面启动，可以看到异常日志
