### ISSUE TITLE
直接连代理可以翻墙，通过PAC不行

### ISSUE THREAD

**Issue by Domain** [XX-net/XX-Net#5470]
用的是傲游，代理设为127.0.0.1:8087可以翻墙，但是用http://127.0.0.1:8086/proxy.pac就不行，以前3.3.0是可以的

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16188
os-system: Windows
os-version: 10.0.16188
os-release: 10
os-detail: Version:10-0; Build:16188; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/5.0.3.1200 Chrome/47.0.2526.73 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2981
network-status: OK
connected-link: new:2 used:0
worker: h1:10 h2:3
scan-ip-thread-num: 50
ip-quality: 194
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Wows233** [comment]
如果你用chrome或firefox，别用pac了，用插件切换吧。chrome用SwitchyOmega，fx也有插件的

**Comment by Wows233** [comment]
傲游也就是chrome加个壳。理论上可以直接加chrome插件。https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif 但是还是建议用chrome

**Comment by Wows233** [comment]
另外，代理设置是
![image](https://cloud.githubusercontent.com/assets/24245520/25847527/129f9264-34e9-11e7-87f9-affde839ee2c.png)
![image](https://cloud.githubusercontent.com/assets/24245520/25847571/33ea19c6-34e9-11e7-83f4-5f56ffbed1ff.png)

**Comment by Domain** [comment]
以前一直都没问题的，只是最近几个星期不行了，win10自带的edge用pac也不行

**Comment by Wows233** [comment]
安装扩展试试

**Comment by theratlesnake** [comment]
对于这种使用国产浏览器翻墙的，我送两个字：傻逼！

**Comment by jzp820927** [comment]
浏览器打开 PAC 地址，能正常显示内容麽？

**Comment by qdpurple** [comment]
@jzp820927 , 请教个问题：
pac代理：http://127.0.0.1:8086/proxy.pac 能否改为
IP:8086/proxy.pac , 我想通过局域网使用pac代理。

**Comment by jzp820927** [comment]
@qdpurple 可以，但是你得修改配置文件，把 PAC 的监听地址，改为 0.0.0.0
