### ISSUE TITLE
github又上不去了，这回是windows

### ISSUE THREAD

**Issue by 12343954** [XX-net/XX-Net#5480]
除了github其他都能上
上回是mac上不去github，这回是windows，两台win都上不去
一个是3.3.2，chrome 52
一个是3.3.1，chrome 57

怎么破，github什么梗，老是过不去
还好mac还能上，上来发个贴，要不就真的与世隔绝了

**Comment by yeahwu** [comment]
这个锅xx不背，github并没有列入gfwlist黑名单。也就是xx-net的pac模式下，github也是直连，没有经过代理。
可以试试全局代理然后连接github

**Comment by jzp820927** [comment]
不科学啊，github 应该是可以直连的啊。你是什么 ISP 封这么死

**Comment by 12343954** [comment]
DNS: 8.8.8.8  8.8.4.4
就可以上来了
谢天谢地，我这歪打正着的瞎猫碰死耗子上了

**Comment by yeahwu** [comment]
能不能透露一下那个地区的？什么网络？
当然你可以不回答。

**Comment by addappcn** [comment]
什么鬼 又上不去了

**Comment by jzp820927** [comment]
github

**Comment by 12343954** [comment]
China Telecom
103.219.187.1*9
Beijing Telecom
Beijing

**Comment by jzp820927** [comment]
估计是 DNS 劫持？

**Comment by 12343954** [comment]
嗯，应该是DNS污染

**Comment by 12343954** [comment]
github是能打开了，但是不能上传图片了，shit

**Comment by yeahwu** [comment]
@12343954 好的，谢谢。那个地方就不奇怪!
另google的dns丢包很严重，可以试试别的dns

**Comment by jzp820927** [comment]
github 的图片用的是 amazon 的服务器，这个估计只能走代理了。

**Comment by 12343954** [comment]
求推荐DNS，别的不知道啊哈哈
不能上传图片是因为Amazon云被墙，艹，console里看到的

**Comment by 12343954** [comment]
![_20170510154606](https://cloud.githubusercontent.com/assets/1804003/25888608/755284ce-3599-11e7-930b-93a799919959.png)

**Comment by jzp820927** [comment]
这是 100 M 带宽？速度还不错。
可以考虑通过 omega 的自动规则，让 图片的域名单独走 XX 代理，其他的 github 域名直连。

**Comment by 12343954** [comment]
才10MB，企业宽带贵的要死
我已经加上代理
多谢二位
