### ISSUE TITLE
3.3.2版本添加新的id无法成功，一直处于终止部署状态

### ISSUE THREAD

**Issue by wangjihu** [XX-net/XX-Net#5489]
gae的id也申请成功了，但是在本地部署时，2s后即显示部署完成，此后一直处于终止部署状态，日志也没有显示。

恩，我总结一下，，一个id的流量用完，添加新的id时，
（1）在win10下面出现了这个问题，将3.3.2完全删除，使用3.3.1重新部署，success。
（2）在Llinux下面倒是没有出现这个问题，直接添加部署成功。

**Comment by westlife96** [comment]
你跟我的情况一样。我用3.2.9版本部署了。再用3.3.1版本即可

**Comment by jzp820927** [comment]
可以通过浏览器打开  https://您的appid.appspot.com/ 查看显示结果，判断部署是否成功

**Comment by wslf1995** [comment]
同上，重新用了3.3.1部署。

**Comment by wangjihu** [comment]
恩，我总结一下，，一个id的流量用完，添加新的id时，
（1）在win10下面出现了这个问题，将3.3.2完全删除，使用3.3.1重新部署，success。
（2）在Llinux下面倒是没有出现这个问题，直接添加部署成功。
