### ISSUE TITLE
xxnet版本号3.31 chrome版本号57，怎么还是显示请检查代理服务器设置

### ISSUE THREAD

**Issue by zhengchaoan** [XX-net/XX-Net#5491]
诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:379 good:196
network-status: OK
connected-link: new:2 used:0
worker: h1:15 h2:6
scan-ip-thread-num: 50
ip-quality: 411
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

ID部署以及浏览器设置这些都没问题的，我看论坛里有人说回退57版本就正常，可是也不行啊。和58版本显示同样的问题，难道也要按照论坛提供的删除证书等等步骤才行吗？还有一个问题，网站总是提醒非私密连接，google都上不了，见鬼。小弟愚昧，恳请各位老哥出出主意。还需要啥，可以再上传。

**Comment by zhengchaoan** [comment]
各位老哥来帮帮我，我不想升58了，57搞搞就行，难道xxnet也要用就版本吗？

**Comment by tang5188** [comment]
我今天也遇到了这个问题，手贱升级了chrome版本，结果就xxnet就不能用了。。。后来没办法把xxnet也升级了

**Comment by zhengchaoan** [comment]
@tang5188 那你升级XXnet有解决问题吗

**Comment by zhengchaoan** [comment]
@jzp820927 老哥求助啊

**Comment by zhengchaoan** [comment]
@wan9wu 这该如何解决啊

**Comment by wenliyang** [comment]
有关证书问题的解决方法，Wiki里是有详细说明的

https://github.com/XX-net/XX-Net/wiki/%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF

**Comment by zhengchaoan** [comment]
@wenliyang 谢啦，我发现一个很奇怪的问题，重装chrome后，如果先登录谷歌账号，再布置appid，就显示请检查代理服务器，但是如果先布置再登录，一点问题都没有。

**Comment by jzp820927** [comment]
意思是问题解决了？

**Comment by zhengchaoan** [comment]
@jzp820927 对的，稀里糊涂的能用了。我也不知道问题出在哪，重装的chrome先部署ID再登录google账号，就能使用。

**Comment by jzp820927** [comment]
好吧，问题解决了就行，其他问题就不用纠结了。
