### ISSUE TITLE
opera浏览器不能开启xx

### ISSUE THREAD

**Issue by Lemonjay** [XX-net/XX-Net#5494]
弹出ssl错误
原来好好的，更新了浏览器就出问题了

**Comment by Lemonjay** [comment]
#5322，一样的问题，不一样的浏览器，解决了，哈哈

**Comment by jzp820927** [comment]
其实也可以说是一样的浏览器，因为 opera 本来就是用的 chrome 的内核，就是换个外壳和商标而已。
