### ISSUE TITLE
Windows 10 64位家庭中文版无法联网

### ISSUE THREAD

**Issue by moarychan** [XX-net/XX-Net#5500]
点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 问题内容
1. 启动start.bat脚本后，提示扫描要等待半小时；
2. 等待很长时间，开始还显示尚未链接，最后就一直显示“请检查浏览器代理设置。“；
3. GAE AppID部署个人ID也是正常提示部署成功了，但是状态“请检查浏览器代理设置。“；

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
xxnet-version: 3.3.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:271 good:59
network-status: OK
connected-link: new:8 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 1707
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

---

**Comment by moarychan** [comment]
[Uploading good_ip.txt…]()
[Uploading scan_ip.log.txt…]()

**Comment by moarychan** [comment]
Thanks. Online, etc.

**Comment by Jan9th** [comment]
中间还有认证和部署两步，先检查你的 appId 是否有效，要不然的话就是 win10 的原因了。

**Comment by jzp820927** [comment]
#5322

**Comment by moarychan** [comment]
今天打开 状态为  “您正在使用公共APPID，因为资源有限，使用上存在限制”
神奇了，前几天死活都不行！但是我部署私有AppID，瞬间提示部署完成，但是还是显示的是使用公共APPID，过几天再看看，会不会变

**Comment by kirbyzhu** [comment]
部署好之后还要设置，千万不要忘记这个环节。不然再等几年看还是不会变。
