### ISSUE TITLE
The requested URL /&safe=off was not found on this server. That’s all we know.

### ISSUE THREAD

**Issue by sendreams** [XX-net/XX-Net#5504]
3.3.2

不能访问https://www.google.com.hk，页面总是跳转到 https://www.google.com.hk/&safe=off
然后页面显示：
404. That’s an error.

The requested URL /&safe=off was not found on this server. That’s all we know.

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1668
network-status: OK
connected-link: new:8 used:0
worker: h1:6 h2:21
scan-ip-thread-num: 50
ip-quality: 140
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
试试 https://www.google.com/ncr 行不行

**Comment by sendreams** [comment]
@jzp820927 之前使用ncr也没用，隔了一天后，可以用了，不过地址换成了日本的google，现在又正常了。

**Comment by jzp820927** [comment]
好吧，能用就行，其他问题就不深究了。
