### ISSUE TITLE
请问 git pull 更新 xxnet 之后, 需要手动 重启 xxnet 么?

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#5507]
如题.

**Comment by SeaHOH** [comment]
如果用 git pull，我觉得应该先关闭，再更新。

**Comment by kuchaguangjie** [comment]
@SeaHOH 关闭倒是不需要, 以前都是 直接 pull 的, 只是不知道 pull 之后, 不重启是否新功能可以生效.

**Comment by jzp820927** [comment]
肯定要重启啊，就像你，更新 windows，难道不重启么

**Comment by kuchaguangjie** [comment]
@jzp820927 毕竟 python 是 解释型 语言, 跟 操作系统 还是有些不同.

**Comment by SeaHOH** [comment]
用自带更新也需要重启，旧版本会保留，运行时定向到新版本。

**Comment by kuchaguangjie** [comment]
@SeaHOH Ok, 谢谢.
