### ISSUE TITLE
关于中间人攻击

### ISSUE THREAD

**Issue by Wows233** [XX-net/XX-Net#5510]
不小心找到了一个貌似被攻击，证书错误的网站，用SS，直接连接，蓝灯 访问，都出现了证书警告。但是使用XX-net连接却没有警报。目前还没有解决这个问题的办法吗？能不能在Google服务器判断证书是否有效并警告呢？

**Comment by jzp820927** [comment]
可以开启证书验证。

**Comment by theratlesnake** [comment]
哪个网站，贴出来啊

**Comment by Wows233** [comment]
@theratlesnake 没必要知道那个网站。只是有这个问题。
@jzp820927 如何开启证书验证？在gae服务器上还是本地配置？

**Comment by SeaHOH** [comment]
客户端开启
```json
"SSLVerify": true,
```

**Comment by Wows233** [comment]
请问具体设置文件路径呢？

**Comment by theratlesnake** [comment]
“没必要知道具体设置文件路径。只是有这个问题。”

**Comment by jzp820927** [comment]
data/gae_proxy/manual.ini

**Comment by Wows233** [comment]
无此文件。是否要创建？语法是什么？

**Comment by SeaHOH** [comment]
@Wows233 
不好意思，弄错了成 gop 了。
goagent 设置是 `validate = 1`
XX-Net 版本取消了这个设置。

**Comment by jzp820927** [comment]
我也发现，好像 XX 没有这个设置项，goa 有这个设置，你可以用 goa 试试。

**Comment by SeaHOH** [comment]
正在改，马上 rp。
