### ISSUE TITLE
XX-NET怎么和SocksCap64配合使用

### ISSUE THREAD

**Issue by KevinSunJin** [XX-net/XX-Net#5514]
![image](https://cloud.githubusercontent.com/assets/13011160/26032528/409834e0-38c8-11e7-8ca4-9691b1805a1f.png)

**Comment by KevinSunJin** [comment]
这样简单的配置一下，测试能通过，但是一些需要代理才能运行的东西仍是无法正常运行

**Comment by jzp820927** [comment]
不知道具体是什么程序无法成功运行，有可能和证书有关。

**Comment by SeaHOH** [comment]
8087 不支持 Socks，需要 1080 的 x_tunnel。

**Comment by Wows233** [comment]
GAE Proxy好像有点问题，git都不能用。还是用x_tunnel设置socks5

**Comment by jzp820927** [comment]
GAE 限制较多，如果不行，就只能用 x_tunnel 了

**Comment by KevinSunJin** [comment]
@jzp820927 @SeaHOH @Wows233  Thanks.
