### ISSUE TITLE
【新国际互联网公约】翻墙的五毛、自干五全家暴毙！

### ISSUE THREAD

**Issue by theratlesnake** [XX-net/XX-Net#5522]
@xxnet @phuslu @yeahwu @breakwa11 @programthink @clowwindy @jasonliul  @jzp820927 @CNMan 
各大佬冒着被查水表，坐牢的风险，为大家搭梯子，结果被五毛和自干五们，拿来翻墙维护极权，还有五毛公然跑来github请教技术问题，无疑是对大佬们的讽刺。
我呼吁一下：五毛、自干五翻墙，全家暴毙。
另外，开着国产杀毒软件，和浏览器翻墙的，都是傻比。

**Comment by jzp820927** [comment]
不明觉厉
