### ISSUE TITLE
YouTube Google突然看不了了，Chrome显示“您的连接不是私密连接”

### ISSUE THREAD

**Issue by dacoit1983** [XX-net/XX-Net#5533]
以下是XX-NET诊断信息

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2992
network-status: OK
connected-link: new:4 used:0
worker: h1:10 h2:11
scan-ip-thread-num: 50
ip-quality: 163
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
#5322

**Comment by dacoit1983** [comment]
已解决，方法是：删除XX-Net\data\gae_proxy\certs里的所有证书
