### ISSUE TITLE
有计划直接支持openwrt么？

### ISSUE THREAD

**Issue by tossp** [XX-net/XX-Net#555]
RT

**Comment by xxnet** [comment]
没有计划，不过如果要折腾也不难，需要解决的地方：
+ openwrt上python的相关库，重点是二进制编译的openssl
+ launcher/x.x.x/下 non_tray.py 覆盖 gtk_tray.py 因为没有图形界面
+ 设置相关监听端口，从127.0.0.1改为 0.0.0.0
+ 给各个设备导入证书
   需要逐个设备导入，这也是不准备支持的原因，对使用者不友好。

2015-06-26 14:50 GMT+08:00 TossPig <notifications@github.com>:

**Comment by tossp** [comment]
原来有个 non_tray.py。。。我找了好久，谢谢

差点想用golang重写了。。。。
