### ISSUE TITLE
谷歌云平台限制

### ISSUE THREAD

**Issue by ysjiang4869** [XX-net/XX-Net#5569]
各位：
  今天收到邮件，谷歌云平台的免费project数限制在五个以内了；问一下各位，如果在五个以下是不是不需要添加结算账户了呢？我看说明貌似必须添加结算账户才能使用，一个结算账户对应5个免费的project，50G存储等，具体可以看这个网站https://cloud.google.com/source-repositories/pricing
  有人可以解析一下吗？thanks

**Comment by Alexander-Chiang** [comment]
你是什么时候创建的project，我很早之前创建的好像没有受到影响，只有近期刚创建的一个似乎受到影响了。

**Comment by Alexander-Chiang** [comment]
@ysjiang4869 你是什么时候创建的project，我很早之前创建的好像没有受到影响，只有近期刚创建的一个似乎受到影响了。

**Comment by ysjiang4869** [comment]
@Alexander-Chiang 我project其中一个创建好几年了，另外的几个有一年了吧，但是目测与创建时间无关，受新的价格政策的影响，我总归有6个，然后以前是免费10个，现在免费5个，所以我project的列表中第一个（创建最早的）收到了邮件提醒，会受到影响，其他的没有；

我已经删除了一个project，如果我不绑定银行卡，剩余5个免费的应该是不受影响的吧？

**Comment by Alexander-Chiang** [comment]
@ysjiang4869 目前还不是很清楚，我另外一个账号申请了10个，几年前申请的，没有收到邮件，不知道是不是因为还没有推送邮件。在用的这个账号也是很早之前申请的一些project，只不过近期添加了一个project，收到邮件只提示这个project将受到影响。

另外，看了你发的那个网页，说是将不能通过git协议访问。xx-net是否受影响还是让开发者来解释解释吧。

**Comment by ysjiang4869** [comment]
我没有阅读明白，我的账户通知是因为我误使用了Cloud Source Repositories (CSR) 服务，与XX-NET使用的没有任何关联，所以应该是不受影响的

**Comment by jzp820927** [comment]
你把服务搞错了，应该是 GAE 服务。
