### ISSUE TITLE
google billing account.....

### ISSUE THREAD

**Issue by wangjihu** [XX-net/XX-Net#5572]
## 今天忽然接到一封邮件。。。gae需要添加信用卡账户。。。这个有经验的能谈下吗，试用期结束后会不会从信用卡里面扣钱。。。
Dear Google Cloud Source Repositories Customer,

The General Availability of Cloud Source Repositories (CSR) comes with a new pricing model effective from May 22, 2017.

The following is a list of all of your CSR projects that may be affected by this change:

From August 21st, 2017, all CSR projects, including projects in the free tier, must have an associated billing account for continued access to CSR repositories. Failure to associate a billing account for the projects containing your CSR repositories will cause you to lose access to them. If you do lose access to your repo due to the lack of a billing account, you’ll have until September 21st, 2017, to add a billing account and regain access.

**Comment by jzp820927** [comment]
到时候不就知道了

**Comment by wangjihu** [comment]
@jzp820927 
你好，我看了下google的credits。

What happens when my free trial ends?

After your trial ends, the resources you created during the trial are stopped, but can be restored **if you upgrade to a paid account** within 30 days.
**也就是说，一年之后不将信用卡升级为付费账户后，所有的appid都会失效。。。**

**Comment by jzp820927** [comment]
个人理解，从邮件内容看，他说的收费应该是指的“Cloud Source Repositories (CSR)”，并不是 GAE。

**Comment by wz7465** [comment]
确实没关系，gae上的app用不到CSR。只有gce上部署应用时，才会用到这个云代码仓库（CSR）

**Comment by wangjihu** [comment]
请问大家部署xx-net有收到过这样的邮件吗，，难道只有我中奖了。。。。。

**Comment by wz7465** [comment]
正常是不开启的
![222](https://cloud.githubusercontent.com/assets/7801728/26382299/f52750f2-405d-11e7-94b4-7806b77b1233.JPG)

试用过300美元的gce后开启的
![111](https://cloud.githubusercontent.com/assets/7801728/26382328/16f1e706-405e-11e7-8a2d-3c005d4b9eb6.JPG)

**Comment by wangjihu** [comment]
@jzp820927 @wz7465 谢谢你们。。。
在我的一个appid下面有个仓库，python-gae-quickstart（不懂这鬼东西啥时候加进去的），我已經将其删除。。。。

**Comment by jzp820927** [comment]
你是删除这个 appid ？还是删除仓库？我怎么没看到哪儿有删除仓库的功能？

**Comment by wangjihu** [comment]
@jzp820927 在projet下面代码库名称右侧下拉选择。。。输入名称。。。。

**Comment by panpeach** [comment]
我几十个AppID，其中一个AppID也收到楼主一样的邮件，
查看了所有AppID，只有收到邮件的那个ID代码库中有 python-gae-quickstart（不知道怎么注册的）
我也把他删除了，不知道今后有什么后遗症。

**Comment by jzp820927** [comment]
不知道有什么后遗症，我那个 CSR 是我以前自己管理 github 上的代码，弄上去的。

**Comment by gmdjh8341** [comment]
我的也收到邮件了，26个ID，2个ID收到

**Comment by RicoLiu** [comment]
Me Too．
我有一个ID收到了，如果不绑定信用卡不会影响正常使用吧？

**Comment by RicoLiu** [comment]
大家是不是都绑定了信用卡呢

**Comment by jzp820927** [comment]
上面都有人说了，把 CSR 删了就行了，不删应该也没影响，最多到期后，CSR 不能用，不影响 GAE

**Comment by gmdjh8341** [comment]
删除了，只要不影响GAE就行，现在申请，给几个免费的ID？我之前一个账号，申请了26个，不知道会不会收回。。。

**Comment by wangjihu** [comment]
@gmdjh8341   12 ge
ps: google's csr sames like github!!!!
