### ISSUE TITLE
申请x-tunnel流量来用用！

### ISSUE THREAD

**Issue by qjwshz** [XX-net/XX-Net#5584]
各位大拿！

我用xx-net也有一段时间了，兼用ss。前者主用于下载与看视频，后者用于浏览浏览网页。

再往前面追溯，就是阿根廷（gae）的时代，也是捣鼓不少。

今天有意用下x-tunnel.注册后只有1mb流量。捐赠appid账号换流量的方法没有找到相关页面（望有能人给出相关链接）。

哪位大拿赠予点流量让我试试x-t的快感。

至于为啥不选购套餐。

要么需求量不是太强烈，要么就是钱兜兜收紧，要么就.....。

嘿嘿，总而言之，这是个让人很尴尬的问题。

注册账户为：qjwshz@gmail.com

坐等为盼。

以后会多多冒泡，与流量多的大人们混个脸熟。

请洒潘江，各倾陆海…………

**Comment by jzp820927** [comment]
已转 5G，请查收。

**Comment by HughDong** [comment]
已转，查收

**Comment by qjwshz** [comment]
@jzp820927  已收到。非常感谢。make the net better.

**Comment by qjwshz** [comment]
@HughDong  20g已收到。够用一段时间了。非常感谢。等用完了再来issues模块浪荡～～   :-)

**Comment by jzp820927** [comment]
土豪在民间啊。

**Comment by ConanWu** [comment]
大神  也给我转一点吧 谢谢
457907449@qq.com

**Comment by jzp820927** [comment]
转了 4G 给你，提示一下，x_tunnel 是基于 GAE 的代理，如果 GAE 无法使用，X_TUNNEL 也无法使用。
最近封锁里面，可能 x_tunnel 不一定能用。

**Comment by SaDanic** [comment]
英雄给我转点吧
谢谢
fanzbiao@gmail.com

**Comment by SaDanic** [comment]
英雄，给我转点吧
fanzbiao@gmail.com

**Comment by jzp820927** [comment]
现在登录 x_tunnel 账号会自动赠送流量，不需要转流量了
