### ISSUE TITLE
"confirm_xxnet_exit" takes too long with iptables on

### ISSUE THREAD

**Issue by zszszsz** [XX-net/XX-Net#5599]
````
May 27 13:14:34.407 - [DEBUG] start confirm_xxnet_exit
May 27 13:15:04.439 - [DEBUG] good, xxnet:8087 cleared!
May 27 13:15:34.445 - [DEBUG] good, xxnet:8085 clear!
May 27 13:15:34.445 - [DEBUG] finished confirm_xxnet_exit
````

This is a router with iptables on to drop connections from outside.
like this:
````
ACCEPT     all  --  0.0.0.0/0            192.168.56.2
DROP       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8085
DROP       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8087
````
and manual.ini:
````
[listen]
ip = 192.168.56.2
port = 8087
````
and version
````
XX-Net Version	3.3.2
Python Version	2.7.13
````

I understand that this may be caused by trying to test if any processes listening `port 8085`

But is there a method set the `webui` to listen to just `192.168.56.2:8085`, instead of `0.0.0.0:8085`

Or is there a method to disable the `confirm_xxnet_exit` behavior ?

**Comment by jzp820927** [comment]
监听地址，可以改配置文件/

**Comment by zszszsz** [comment]
webui的监听地址不是在这个配置文件里面改的，以及把webui改成监听127.0.0.1:8080根本没用，把iptables对8080的策略改成REJECT也没用

**Comment by zszszsz** [comment]
解决(并不)方法
````
-A INPUT -p tcp --dport 8085 -j REJECT --reject-with tcp-reset
-A INPUT -p tcp --dport 8087 -j REJECT --reject-with tcp-reset
````

**Comment by zszszsz** [comment]
所以要解决这个东西就要看这个confirm_exit能不能关了。。。

**Comment by jzp820927** [comment]
webui 的监听地址，在 data/launcher/config.yaml 这个文件里面改

**Comment by SeaHOH** [comment]
但是 launcher 其它地方都把端口写死了（包括代理端口），改了就不好用了。

**Comment by zszszsz** [comment]
@jzp820927 你自己去看，那里只能设定127.0.0.1或者0.0.0.0

所以你也不想想我用iptables把这个端口封掉是为了什么。。。

**Comment by zszszsz** [comment]
@jzp820927 

modules:
  gae_proxy: {auto_start: 1, show_detail: 1}
  launcher: {allow_remote_connect: 1, auto_start: 1, control_port: 8085, last_run_version: 3.3.2,
    popup_webui: 0, proxy: pac, show_systray: 0, xxnet_port: 8087}

你告诉我哪个是ip地址？

**Comment by SeaHOH** [comment]
如果要停用 `confirm_xxnet_exit`，修改函数直接返回 `True` 就好了。

**Comment by jzp820927** [comment]
你是想改监听地址？如果想远程访问 8085 可以在 web 也打开，默认是监听 127，不知道你想怎么改。

**Comment by zszszsz** [comment]
@SeaHOH 那看来只能这样了

这周没空所以准备下周加上这个特性，以及webui的listen address，在配置文件里面加上一条……不知道这个项目对PR怎么审查的

**Comment by SeaHOH** [comment]
停用 `confirm_xxnet_exit` 的修改应该不会接受。
修改监听地址在下面这个位置，需要获取本地网络地址来替换 `0.0.0.0`。但是这样本机好像就不能通过 `127.0.0.1` 访问了，所以还需要改所有其它引用 `127.0.0.1` 的地方。
```python
#web_control.py L412
if allow_remote:
    host_addr = "0.0.0.0"
else:
    host_addr = "127.0.0.1"
```
