### ISSUE TITLE
访问显示：gzip: invalid header

### ISSUE THREAD

**Issue by gengmu** [XX-net/XX-Net#56]
出现：gzip: invalid header
不知是哪里出错？？？？
ca证书无法找到

**Comment by xxnet** [comment]
请附上GoAgent状态：
http://127.0.0.1:8085/
GoAgent日志：
http://127.0.0.1:8085/?module=goagent&menu=logging

**Comment by gengmu** [comment]
GoAgent状态：

Property	Value
Sys Platform	linux2
OS System	Linux
OS version	#43-Ubuntu SMP Tue Mar 10 17:37:36 UTC 2015
OS release	3.16.0-31-generic
OS detail	Dist:Ubuntu; Version:14.10; ID:utopic
architecture	64bitELF
Browser	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36
XX-Net Version	1.2.1
Launcher Version	1.0.4
GoAgent Version	3.1.37
Python Version	2.7.8
Proxy Listen	127.0.0.1:8087
GAE appid	qianjiuliu|qianjiuliu1|qianjiuliu2|qianjiuliu3|
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2183

**Comment by gengmu** [comment]
日志：

Mar 13 13:40:03 - [DEBUG] sort ip time:3
Mar 13 13:40:03 - [INFO] ------------------------------------------------------
GoAgent Version : 3.1.37 (python/2.7.8 )
Listen Address : 127.0.0.1:8087
Control Address : 127.0.0.1:8084
GAE APPID : qianjiuliu|qianjiuliu1|qianjiuliu2|qianjiuliu3
Pac Server : http://127.0.0.1:8086/proxy.pac
Pac File : file:///home/gm/XX-Net-1.2.1/goagent/3.1.37/local/proxy.pac
------------------------------------------------------

Mar 13 13:40:07 - [INFO] FWD CONNECT xxnet-update.appspot.com:443 
Mar 13 13:40:07 - [DEBUG] get ip:202.39.143.25 t:123
Mar 13 13:40:07 - [DEBUG] get ip:64.233.189.154 t:125
Mar 13 13:40:07 - [DEBUG] tcp conn 64.233.189.154 time:64
Mar 13 13:40:08 - [DEBUG] forward remote disconnected.
Mar 13 13:40:08 - [DEBUG] FWD CONNECT xxnet-update.appspot.com:443 closed
Mar 13 13:40:08 - [DEBUG] tcp conn 202.39.143.25 fail t:1001
Mar 13 13:40:43 - [DEBUG] GoAgent Web_control 127.0.0.1:52557 "GET /status 
Mar 13 13:40:44 - [DEBUG] GoAgent Web_control 127.0.0.1:52558 "GET /status 
Mar 13 13:40:45 - [DEBUG] GoAgent Web_control 127.0.0.1:52560 "GET /status 
Mar 13 13:40:46 - [DEBUG] GoAgent Web_control 127.0.0.1:52562 "GET /status 
Mar 13 13:40:47 - [DEBUG] GoAgent Web_control 127.0.0.1:52564 "GET /status 
Mar 13 13:40:48 - [DEBUG] GoAgent Web_control 127.0.0.1:52579 "GET /status 
Mar 13 13:40:49 - [DEBUG] GoAgent Web_control 127.0.0.1:52582 "GET /status 
Mar 13 13:40:50 - [DEBUG] GoAgent Web_control 127.0.0.1:52584 "GET /status 
Mar 13 13:40:51 - [DEBUG] GoAgent Web_control 127.0.0.1:52594 "GET /status 
Mar 13 13:40:52 - [DEBUG] GoAgent Web_control 127.0.0.1:52596 "GET /status 
Mar 13 13:40:53 - [DEBUG] GoAgent Web_control 127.0.0.1:52599 "GET /log?cmd=get_new&last_no=2 
Mar 13 13:40:55 - [DEBUG] GoAgent Web_control 127.0.0.1:52601 "GET /log?cmd=get_new&last_no=22 
Mar 13 13:40:57 - [DEBUG] GoAgent Web_control 127.0.0.1:52604 "GET /log?cmd=get_new&last_no=23 
Mar 13 13:40:59 - [DEBUG] GoAgent Web_control 127.0.0.1:52607 "GET /log?cmd=get_new&last_no=24 
Mar 13 13:41:01 - [DEBUG] GoAgent Web_control 127.0.0.1:52609 "GET /log?cmd=get_new&last_no=25 
Mar 13 13:41:03 - [DEBUG] GoAgent Web_control 127.0.0.1:52612 "GET /log?cmd=get_new&last_no=26

**Comment by xxnet** [comment]
你看到 gzip: invalid header是在浏览器里吧？
请把访问浏览器是看到这句话时的日志发出来。
 
你发的日志，没有翻墙的请求处理日志

**Comment by gengmu** [comment]
Mar 14 10:06:29 - [INFO] "GAE t:842 speed:24 len:21 status:500 GET http://www.atgfw.org/ HTTP/1.1"
Mar 14 10:06:29 - [DEBUG] ssl_pool.get:64.233.189.154 handshake:137
Mar 14 10:06:29 - [DEBUG] ssl conn_num:19
Mar 14 10:06:29 - [DEBUG] GoAgent Web_control 127.0.0.1:55884 "GET /log?cmd=get_new&last_no=318
Mar 14 10:06:29 - [INFO] "GAE t:237 speed:88 len:21 status:500 GET http://www.atgfw.org/favicon.ico HTTP/1.1"
Mar 14 10:06:29 - [DEBUG] ssl_pool.get:64.233.189.154 handshake:137
Mar 14 10:06:29 - [DEBUG] ssl conn_num:19
Mar 14 10:06:30 - [DEBUG] get ip:210.242.125.45 t:175
Mar 14 10:06:30 - [INFO] "GAE t:391 speed:53 len:21 status:500 GET http://www.atgfw.org/favicon.ico HTTP/1.1"
Mar 14 10:06:31 - [DEBUG] GoAgent Web_control 127.0.0.1:55887 "GET /log?cmd=get_new&last_no=326
Mar 14 10:06:34 - [DEBUG] GoAgent Web_control 127.0.0.1:55892 "GET /log?cmd=get_new&last_no=332
Mar 14 10:06:35 - [DEBUG] create_ssl update ip:210.242.125.45 time:5432
Mar 14 10:06:36 - [DEBUG] GoAgent Web_control 127.0.0.1:55897 "GET /log?cmd=get_new&last_no=333
Mar 14 10:06:37 - [DEBUG] ssl_pool.get:64.233.189.154 handshake:137
Mar 14 10:06:37 - [DEBUG] ssl conn_num:20
Mar 14 10:06:37 - [INFO] "GAE t:320 speed:65 len:21 status:500 GET http://allinfa.com/ HTTP/1.1"
Mar 14 10:06:37 - [DEBUG] ssl_pool.get:64.233.189.154 handshake:137
Mar 14 10:06:37 - [DEBUG] ssl conn_num:19
Mar 14 10:06:37 - [DEBUG] sort ip time:5
Mar 14 10:06:37 - [DEBUG] get ip:64.233.189.143 t:143
Mar 14 10:06:37 - [DEBUG] create_ssl update ip:64.233.189.143 time:160
Mar 14 10:06:38 - [DEBUG] GoAgent Web_control 127.0.0.1:55902 "GET /log?cmd=get_new&last_no=335
Mar 14 10:06:38 - [INFO] "GAE t:741 speed:28 len:21 status:500 GET http://allinfa.com/favicon.ico HTTP/1.1"
Mar 14 10:06:38 - [DEBUG] ssl_pool.get:64.233.189.154 handshake:137
Mar 14 10:06:38 - [DEBUG] ssl conn_num:19
Mar 14 10:06:38 - [INFO] "GAE t:237 speed:88 len:21 status:500 GET http://allinfa.com/favicon.ico HTTP/1.1"
Mar 14 10:06:40 - [DEBUG] GoAgent Web_control 127.0.0.1:55906 "GET /log?cmd=get_new&last_no=344
Mar 14 10:06:42 - [DEBUG] GoAgent Web_control 127.0.0.1:55918 "GET /log?cmd=get_new&last_no=349
Mar 14 10:06:44 - [DEBUG] GoAgent Web_control 127.0.0.1:55922 "GET /log?cmd=get_new&last_no=350
Mar 14 10:06:46 - [DEBUG] GoAgent Web_control 127.0.0.1:55923 "GET /log?cmd=get_new&last_no=351
Mar 14 10:06:48 - [DEBUG] GoAgent Web_control 127.0.0.1:55927 "GET

**Comment by xxnet** [comment]
日志中：
 GAE t:842 speed:24 len:21 status:500 GET http://www.atgfw.org/ HTTP/1.1"

status:500表示服务器内部错误。

我查到服务端有关500错误的日志：
wsgi.py", line 183, in gae_application
    payload = zlib.decompress(payload, -zlib.MAX_WBITS)
error: Error -3 while decompressing data: invalid distance too far back

具体原因还不明确，不过这里确实有可能出问题。
暂时的解决方案是：重启XXnet

我重启XXnet后，这个问题就没有出现了。

看来还是要升级用3.2的服务端，才能彻底解决问题。

**Comment by gengmu** [comment]
感谢您的解答！我重新部署后可以用了！

**Comment by xxnet** [comment]
谢谢反馈。

**Comment by xxnet** [comment]
1.7 版本已经使用使用goagent 3.2
不会再出现类似问题
