### ISSUE TITLE
换win10后忽然不能用，是不是我哪里犯蠢

### ISSUE THREAD

**Issue by zjuchenchao** [XX-net/XX-Net#5610]
## 问题内容
- 之前用win8.1一直正常，后来一段时间没用xxnet，换win10后发现直接不能用了，是不是某些win10的默认设置问题（如果是这个原因那我犯的一手好蠢）
- 全部代理度娘都打不开，pac能度娘不能谷鸽，应该是代理没起作用
- 已经更新3.3.1了，不是版本问题，包括删光文件夹重新下载解压也试过
- manual.ini里面放过找的一些appid，包括我之前自己用的几个也放进去试过无效

### 状态页打不开
http://127.0.0.1:8085  完全打不开，Edge提示

Hmm, we can't reach this page.
Try this
Make sure you’ve got the right web address: http://127.0.0.1:8085

### 本地log文件找不到
除了scan_ip.log其他log文件都是空的，这个也明显不是日志文件

### start.bat
运行扫描ip，头一次是扫了一个小时回来看关闭了，应该是扫完了正常退出吧，后面又扫了几次，几个小时扫不完只能直接关掉

### switchyomega
开始怀疑代理设置问题，后来换系统代理和xxnet都无法联网，直连可上度娘，应该就是没开起来

**Comment by zjuchenchao** [comment]
补充：
1.放到D盘，不存在读写权限问题
2.虽然没用测试版，但是localhost打不开貌似不是版本的问题吧，我总觉得是自己忘了什么，java/py之类的都安装了，到底忘记啥了

**Comment by wenliyang** [comment]
把 XX-Net 整个文件夹删除，重新从 github 下载最新版本来试

**Comment by jzp820927** [comment]
运行扫描ip，头一次是扫了一个小时回来看关闭了，应该是扫完了正常退出吧，后面又扫了几次，几个小时扫不完只能直接关掉

XXNET 要一直运行，不能关闭，关闭了，就不能用代理了。

**Comment by zjuchenchao** [comment]
谢谢回复！
@wenliyang 我就是重新下了试过了，待会试试3.3.2吧，貌似很多人3.3.1也用的好好的，我这个不像是版本的问题。
@jzp820927 扫ip的问题应该是这样，但我的意思是开着也不能用，http://127.0.0.1:8085这个就是打不开的状态，无论是用bat打开，还是vbs（其实应该效果一样），全局代理什么都上不了，pac的话墙内的度娘还能上。

**Comment by zjuchenchao** [comment]
对了，会不会是IIS服务的问题？win10默认是全部关闭的，忘记之前8.1是怎样的了

**Comment by jzp820927** [comment]
XXNET 和 IIS 扯不上什么关系，你的意思是 127.0.0.1：8085 打不开？如果是这样，就把刚刚运行时候的日志发来看看

**Comment by zjuchenchao** [comment]
@jzp820927 
谢谢，localhost打不开没法看日志，而且log文件都是空的，我截取了部分屏幕输出内容，感觉没啥问题，后面扫ip的就省略了。这个是刚刚用3.3.2跑的。（中间检查更新报warning是没错，但是我之前用3.3.0，成功更新到3.3.1也是一样不能用，应该也跟这个关系不大吧。）
[1.txt](https://github.com/XX-net/XX-Net/files/1034796/1.txt)

**Comment by SeaHOH** [comment]
看日志挺正常的，是不是防火墙没设置好？

**Comment by zjuchenchao** [comment]
@SeaHOH 谢谢，果然是这个愚蠢的问题，之前升win10的时候我手动关掉防火墙了，而且右下角一直弹窗提醒。估计是某次更新自己打开了，或者其他人碰我电脑了？反正弄好了就行，谢谢提醒。

**Comment by SeaHOH** [comment]
知见障，我有时也会这样，能自己破最好啦。
