### ISSUE TITLE
从大概1~2个小时前就没法使用了

### ISSUE THREAD

**Issue by githubhao0705** [XX-net/XX-Net#5612]
提示为：请检查浏览器代理设置。
但X-Tunnel模式仍旧可以使用。

如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2910
network-status: OK
connected-link: new:0 used:0
worker: h1:14 h2:6
scan-ip-thread-num: 50
ip-quality: 171
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
#5322

**Comment by githubhao0705** [comment]
@jzp820927 看了，我尝试过上述操作，可惜还是无解，就在刚才，清除了原本的3.3.1，下载了3.3.2，所有步骤都按照重新安装的步骤进行，可惜还是提示：请检查浏览器代理设置。
