### ISSUE TITLE
开贴 关贴问题

### ISSUE THREAD

**Issue by Jan9th** [XX-net/XX-Net#5624]
开的贴子太多了，建议在 wiki 或者模版中增加提示，也希望大家能把已经解决的问题自行关闭。

**Comment by jzp820927** [comment]
你也可以去 wiki 写教程啊

**Comment by Jan9th** [comment]
好的，我刚玩 GitHub 没多久，对于权限什么的也不熟悉，看到 wiki 中有待完善的列表，有时间了写一些，先把问题关了。
