### ISSUE TITLE
最近几天xx-net 状态页提示本地网络状态　unknow　ok　之间频繁切换　网速很慢有时根本翻不出去

### ISSUE THREAD

**Issue by taocunguijs** [XX-net/XX-Net#5631]
目前版本号：　３.3.2

是不是最近干扰严重导致的？我试遍了3.2.8　到3.3.2　之间的所有版本全都是这个问题，之前用了半年多用的好好的就从上周开始出现这个问题，而且同样的版本在单位电脑上没有这个问题，把家里有问题的电脑的网络链接切换成手机流量共享的热点的时候就不会来回从unknow　切换到ok。

请教一下有没有什么临时的解决方案？　或者哪个版本不会出现这个问题。　过了这段“强干扰”非常时期会好起来吗？

**Comment by hadementin** [comment]
剛從3.3.2 換回 3.3.1 解壓后沒再出現這個問題

**Comment by SeaHOH** [comment]
只是需要翻墙的网站慢还是所有网站都慢？
* 如果都慢就是线路问题了，请报修。严重怀疑是这种情况。
* 否则就是墙的干扰。不过这两个月形式还不错，干扰不算全面，建议删除 data 文件夹中的 IP 数据，然后重启 XX-Net 重新扫描。

**Comment by taocunguijs** [comment]
跟时间段有关系，白天没啥问题，晚上就不行了，删除所有ip也一样。

**Comment by taocunguijs** [comment]
换各种版本都没用

**Comment by zhencaihao** [comment]
前段时间延迟都是90-150左右的。昨天晚上开始延迟突然就涨到了450多，现在我的延迟显示495。不知道是不是和昨天实施的互联网安全法有关？

**Comment by taocunguijs** [comment]
难道是陆  肆到了，上网困难了？

**Comment by jzp820927** [comment]
如果按你所说单位没问题，只有家里有问题，应该可以确定是线路问题了。不知道你用的是什么 ISP？如果动手能力强的话，可以把单位的共享给家里用。

**Comment by taocunguijs** [comment]
用的是宽带通

**Comment by taocunguijs** [comment]
单位的网络ip地址是10.*.*.*的地址，　外部没法ping通，　请教一下有啥教程能够共享给家里用？　可以给个教程吗？　非常感谢

**Comment by jzp820927** [comment]
这个有点麻烦，除非你有权限能改单位的路由器，做端口映射才行。如果没有这个条件，就不用考虑了。

**Comment by taocunguijs** [comment]
就是内网地址，想要访问都得用easyconnet　vpn　链接到内部才能访问公司的电脑

**Comment by taocunguijs** [comment]
问题关闭，应该是最近网络质量变差导致的，等过了陆肆再说，暂时用其他选项解决问题

**Comment by jzp820927** [comment]
我还没确定，你说的 10，是指的单位上你的电脑的 IP ，还是互联网的出口的 IP？

**Comment by taocunguijs** [comment]
就是本地ip地址　

　eth1      Link encap:以太网  硬件地址 dc:4a:3e:46:ee:47  
          inet 地址:10.58.238.37  广播:10.58.239.255  掩码:255.255.252.0
          inet6 地址: fe80::de4a:3eff:fe46:ee47/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  跃点数:1
          接收数据包:20113294 错误:0 丢弃:109 过载:0 帧数:0
          发送数据包:64318598 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
          接收字节:17227101805 (17.2 GB)  发送字节:5612021962 (5.6 GB)

**Comment by taocunguijs** [comment]
有办法在家里用公司电脑做代理吗？

**Comment by taocunguijs** [comment]
互联网出口ip，用了也没用啊，应该是nat　转换成内网的，而且没法更改路由器端口映射

**Comment by SeaHOH** [comment]
非墙网站都正常吗？
如果也慢，检查一下你家里是否也是 NAT，这种带宽超卖以前很猖獗的，高峰时简直回到了 56K 拨号时代。

**Comment by taocunguijs** [comment]
国内的速度还行，５０M 带宽，看视频不卡

**Comment by taocunguijs** [comment]
家里面也是nat

**Comment by SeaHOH** [comment]
本来想建议你打客服帮你换公网 IP，但是我搜索了`宽带通`后觉得这招行不通，估计要换 ISP 才行。

**Comment by jzp820927** [comment]
不能映射端口就没办法了。这个肯定是要映射端口的，或者也可以做内网穿透，如果你有能力的话。

**Comment by taocunguijs** [comment]
不一样，公司是联通的，家里是宽带通，家里的各种xx-net都有类似问题，连安卓apk的xx-net也存在这个问题

**Comment by jzp820927** [comment]
基本上可以确定，是你家里 ISP 的国际线路质量的问题，不知道你家里的 宽带通 连 公司的 联通 怎么样，如果可以的话，通过共享公司的网络应该是没有问题的。如果没有外网出口路由器的控制权，可以做内网穿透

**Comment by SeaHOH** [comment]
内网穿透需要服务器中转，需要服务提供商或者自建服务器。
可惜你两边都是内网，不然在家里开个 VPN，公司登录后配置代理转发。

虽说不太可能，你还是跟客服沟通一下能否换成公网 IP，这样干扰较小。

**Comment by jzp820927** [comment]
如果两边都是内网，那确实就没办法了（除非你有另外的服务器，如果是这样，就可以直接部署在服务器上，也没必要连公司了），只要有一边是外网，就行。

**Comment by taocunguijs** [comment]
国际线路质量还可以，昨天还通过gfw.press传视频到youtube速度都在1兆以上，峰值能全速6mb/s上传,
这两天临时换用gfw.press工具看youtube，基本没问题。

**Comment by taocunguijs** [comment]
今天把xx-net降级到3.2.7后状态不再会出现unknow和ok来回切换，可以正常翻出去，基本满足看视频需求，虽然有时候还是会卡，遇到和我类似问题的可以考虑这种方案临时解决下

**Comment by jzp820927** [comment]
最近几个版本好像都是小修小改，没有性能方面的改进，不明觉厉。

**Comment by SeaHOH** [comment]
@taocunguijs 你这么一说，我好像找到原因了。
尝试一下这个修复，如果可行我就 pr。
https://github.com/SeaHOH/XX-Net/tree/bugfix-temp

**Comment by taocunguijs** [comment]
@SeaHOH 

 非常感谢，你改得这两行代码果然好使，修改完就不会再unknow 和 ok 之间来回切换，使用上可以达到3.2.7 的效果，非常感谢！

超过10链接失败就状态改为unknow 导致得问题吗？ 或者其他啥原因导致得bug,

最近家里得网络确实干扰严重，估计会触发这个10次失败的条件，

**Comment by SeaHOH** [comment]
主要是第二行修改的效果。

**Comment by taocunguijs** [comment]
懂了，谢谢

**Comment by taocunguijs** [comment]
@SeaHOH

　　我看到你有第两笔提交：
第一笔：

def report_network_fail():
     global network_stat, last_check_time, continue_fail_count
     continue_fail_count += 1
     last_check_time = time.time()
 
     if continue_fail_count > 10:
-        network_stat = "unknown"
+        # network_stat = "unknown"
         xlog.debug("report_connect_fail continue_fail_count:%d", continue_fail_count)
-        triger_check_network()
+        triger_check_network(True)


第二笔：

-def triger_check_network(force=False):
+def triger_check_network(fail=False, force=False):
     global _checking_lock, _checking_num, network_stat, last_check_time
     time_now = time.time()
     if not force:
         if _checking_num > 0:
             return
 
-        if network_stat == "OK":
-            if time_now - last_check_time < 10:
-                return
-        else:
+        if fail or network_stat != "OK":
             # Fail or unknown
             if time_now - last_check_time < 3:
                 return
+        else:
+            if time_now - last_check_time < 10:
+                return
 
     last_check_time = time_now
     th = threading.Thread(target=_simple_check_worker)
     th.start()


第二笔修改之后：　triger_check_network　函数走的分支应该一样吧？

感觉主要原因还是之前network_stat 被修改为unknow了，导致goole_ip.py　中访问is_ok　都返回Ｆalse　导致的问题，不知道这么理解是否正确？　可以说下问题根本原因吗？

多谢！

**Comment by SeaHOH** [comment]
不提前修改 `network_stat`，而是实际测试后修改。
添加 `fail` 参数确保在不修改 `network_stat` 的情况下，仍然能根据是否 3 秒时间差来判断是否进行测试，之前和再之前的代码都没有做到这个设计预期。

**Comment by taocunguijs** [comment]
谢谢！

**Comment by wmj765** [comment]
@taocunguijs 这个网址打不开了呢 我的也出现同样的问题
https://github.com/SeaHOH/XX-Net/tree/bugfix-temp

**Comment by jzp820927** [comment]
被删了，肯定打不开了啊

**Comment by taocunguijs** [comment]
最新3.3.4版本已经集成这个改动

**Comment by wmj765** [comment]
@jzp820927 额 来晚了，谁有这个文件呢 再次分享下呗 感谢！！

**Comment by jzp820927** [comment]
上面不是说了吗，最新3.3.4版本已经集成这个改动

**Comment by taocunguijs** [comment]
@wmj765 
  下载最新3.3.4就行啊

**Comment by wmj765** [comment]
@jzp820927 最新版的ip虽然解决了，但只能扫到1个，3.1的可以扫到1000+

**Comment by wmj765** [comment]
@jzp820927 最新版的虽然解决了，但ip只能扫到1个，3.1的可以扫到1000+

**Comment by taocunguijs** [comment]
ip扫描不到不是xx-net　bug ，网络环境问题，　跟版本没关系，你用3.1 删除data重新扫估计也扫不出什么东西

**Comment by jzp820927** [comment]
@wmj765 你可以考虑把 3.3.1 扫出来的 IP，放到 3.3.4 去用
