### ISSUE TITLE
请问1.15.2中的局域网代理是干什么的？

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#564]
可以用这个来实现给手机用吗？

**Comment by xxnet** [comment]
局域网代理，是给那些访问国内都需要先设置代理的，一般只在学校等少数地方会用到。

给手机代理，已经有很多朋友在探索，虽然折腾，但也是可行的。
完全运行在手机上的代理，也正在研究中，没预计中顺利，不过一个月内应该可以发布第一个版本。

2015-07-04 10:58 GMT+08:00 cdmask <notifications@github.com>:

**Comment by cdmask** [comment]
为什么在学校会需要先设置代理再进行网络访问呢？

**Comment by yfdyh000** [comment]
不少学校或者公司加了网络管理的软件，将内网流量经过代理过滤后转发。方便检测、过滤、限制、统计访问流量和内容等。

**Comment by cdmask** [comment]
谢谢！
