### ISSUE TITLE
Firefox无法通过XX-NET打开Google。ncr也不行

### ISSUE THREAD

**Issue by kmcbest** [XX-net/XX-Net#5642]
3.3.2版，Firefox 53配合Autoproxy
无论是使用全局还是自动模式，均无法打开www.google.com/ncr，也无法打开www.google.com.hk。提示连接超时。日志中根本没有任何关于正在连接Google.com的提示。
Youtube和duckduckgo同样超时，twitter提示 SEC_ERROR_REUSED_ISSUER_AND_SERIAL

同一时刻用Chrome或者IE均可以正常打开上述所有网站

---------
太笨了，Firefox的问题要找Firefox……原来是升级到53的时候Autoproxy失效了…

**Comment by kmcbest** [comment]
降级到Firefox 52，同样的配置上述网站立即正常，不知道Firefox 从 52 到 53 有什么地方变化了，非常费解！

**Comment by jzp820927** [comment]
FF 用 PAC 最方便，什么插件都不用装
