### ISSUE TITLE
xx-net 不跳出部署窗口

### ISSUE THREAD

**Issue by zhengyifei** [XX-net/XX-Net#5644]
打开XX-Net的设置页：http://127.0.0.1:8085 ，切换到部署服务端
输入AppID后，左击开始部署，会弹出授权窗口
3-Deploy.png
左击Allow，然后就会进行服务端的部署

我按照步骤，输入appid后，怎么都不跳出授权窗口（已经把弹出窗口改成全部允许了），有人知道怎么办吗？感谢

**Comment by jzp820927** [comment]
这之前有没有部署过 appid？

**Comment by zhengyifei** [comment]
之前没有部署过 appid，昨天刚刚接触xx-net，都配置完了，可以翻墙了，这都没问题
但是想再进一步试试用个人appid的时候，就碰到了这个问题。。

**Comment by wenliyang** [comment]
XX-Net 用的什么版本，最新的 3.3.2 的话，试试 3.3.1、3.3.0，等，降级试

**Comment by zhengyifei** [comment]
用的3.3.2。。。

**Comment by jzp820927** [comment]
你的默认浏览器是不是自动登录了 google 账号，如果是的话，先退出账号

**Comment by zhengyifei** [comment]
退出google账号了，还是老样子，点击部署，跳到日志页面，没有弹出授权窗口，日志也始终为空

**Comment by jzp820927** [comment]
https://github.com/jzp820927/Deploy_XXNET_Server
换这个工具部署实施？

**Comment by waitingHao** [comment]
的确是部署不了了。

**Comment by candy2107** [comment]
換個工具都不行麽

**Comment by waitingHao** [comment]
3.3.2的python的问题。

**Comment by candy2107** [comment]
换3.2.9部署

**Comment by jzp820927** [comment]
如果确实部署不了，上面已经提供第三方部署工具，可以试试，应该没问题

**Comment by xyuanmu** [comment]
缺了一个模块，已修复

**Comment by Jan9th** [comment]
我之前的也是，还是找人帮我弄好的，不清楚具体原因。

**Comment by malthae** [comment]
我也是一直部署不了，点了之后没反应也没log，后来用那个ss部署的工具部署的。。。

**Comment by jzp820927** [comment]
什么是 ss部署工具？难道你指的是 deploy_xxnet_server ?

**Comment by bljds** [comment]
经验证，3.3.2好像有问题，3.3.1可以部署，顺利弹出窗口。

**Comment by jzp820927** [comment]
332 已经提交修复PR了，只不过还没合并
