### ISSUE TITLE
macOS 10.12.5,XX-Net 3.3.1,运行start没有设置页面出现，也不显示X图标，且无法上网

### ISSUE THREAD

**Issue by caelanyang** [XX-net/XX-Net#5653]
与[issues #5616](https://github.com/XX-net/XX-Net/issues/5616)描述的一样
运行start后终端显示： 

> Downloads/XX-Net-3.3.1/start ; exit;
Python 2.7.10
XX-Net version:default
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[进程已完成]

与#5616不同的是，现在已经不能正常翻墙了。
以前用3.2.9的时候，一直很正常，然而，不知道什么时候就开始不显示X图标了，也不弹出设置页面了。只是还可以正常翻墙，所以也没去管它，直到最近出现不是私密链接的那个证书引起的问题，没法上网了，我才开始到Github上来看。

更新到3.3.1之后，并且按照#5322所总结的更新证书，也是不显示图标和设置页面，同时无法上网。
也有使用3.2.9，按照#5322更新证书，同样只是解决了不再弹出访问不是私密链接的问题。但是还是不显示图标和设置页面，也无法上网。
中间也有重启电脑，重启浏览器，重新安装浏览器，重新安装SwutchyOmega等尝试。
期间最好的时候是很慢的网速打开了Google主页，但是再去搜索就不行了。

总之，不论3.2.9还是3.3.1，start之后，就终端显示进程已完成。图标，设置页面，翻墙都不行。希望我的描述足够清晰。。。

**Comment by caelanyang** [comment]
忘记说了，也尝试了测试版3.3.2，也是一样的。

**Comment by jzp820927** [comment]
终端，手动运行试试

**Comment by HiGodfather** [comment]
如果改动过.ini文件或.json 文件，里面的引号或逗号非英文格式时，也会引起这种情况，我遇到过几次。

**Comment by caelanyang** [comment]
@jzp820927 你说的手动运行是指终端输入 ./start或者sudo ./start吗，试过了的，也是不行。
终端会显示：

> Python 2.7.10
XX-Net version:default

**Comment by caelanyang** [comment]
@HiGodfather 哪里面的ini或Json文件啊，我下载XX后都没动什么文件啊

**Comment by HiGodfather** [comment]
没动文件，那说明不是我说的这种情况了。

**Comment by jzp820927** [comment]
打开终端，运行下面的命令
python code/3.3.2/launcher/start.py

**Comment by caelanyang** [comment]
@jzp820927 这个方法也用了，使用后，终端那边会一直显示日志信息，不停的，目测是一直扫描IP，但是只能间歇性的可以以很慢的速度翻墙，很多时候无法翻墙。

以下是刚开始的一些日志信息，再往后就以debug和info信息为主了，基本是扫描IP的信息。能从日志看出什么问题吗，我看到有error和exception。谢谢啦
> Jun 05 14:52:10.681 - [INFO] use build-in openssl lib
Jun 05 14:52:10.682 - [INFO] start XX-Net 3.3.1
Jun 05 14:52:10.682 - [DEBUG] start confirm_xxnet_exit
Jun 05 14:52:10.684 - [DEBUG] <0>: try to terminate xxnet:8087
Jun 05 14:52:11.689 - [DEBUG] good, xxnet:8087 cleared!
Jun 05 14:52:11.690 - [DEBUG] good, xxnet:8085 clear!
Jun 05 14:52:11.690 - [DEBUG] finished confirm_xxnet_exit
Jun 05 14:52:11.764 - [INFO] SSL use version:TLSv1
Jun 05 14:52:11.765 - [INFO] OpenSSL support alpn
Jun 05 14:52:11.767 - [INFO] load ip range file:/Users/caelan/Downloads/XX-Net-3.3.1/code/default/gae_proxy/local/ip_range.txt
Jun 05 14:52:11.792 - [INFO] load google ip_list num:382, gws num:382
Jun 05 14:52:11.801 - [INFO] OpenSSL support alpn
Jun 05 14:52:11.802 - [DEBUG] get ip:216.58.200.192 t:165
Jun 05 14:52:11.808 - [DEBUG] get ip:115.84.108.161 t:179
Jun 05 14:52:11.813 - [DEBUG] ## GAEProxy set keep_running: True
Jun 05 14:52:11.813 - [INFO] ------------------------------------------------------
Jun 05 14:52:11.813 - [INFO] Python Version     : 2.7.10
Jun 05 14:52:11.814 - [INFO] OS                 : Release:10.12.5; Version:('', '', '') Machine:x86_64
Jun 05 14:52:11.814 - [INFO] Listen Address     : 127.0.0.1:8087
Jun 05 14:52:11.814 - [INFO] GAE APPID          : 
Jun 05 14:52:11.814 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Jun 05 14:52:11.814 - [INFO] ------------------------------------------------------
Jun 05 14:52:11.855 - [INFO] GoAgent CA exist
Jun 05 14:52:11.855 - [INFO] server 127.0.0.1:8087 started.
Jun 05 14:52:11.856 - [INFO] server 127.0.0.1:8086 started.
Jun 05 14:52:11.862 - [DEBUG] network is ok, cost:136 ms
Jun 05 14:52:11.912 - [INFO] module gae_proxy started
Jun 05 14:52:11.913 - [INFO] start gae_proxy time cost:222 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Jun 05 14:52:11.924 - [INFO] use config_path:/Users/caelan/Downloads/XX-Net-3.3.1/data/x_tunnel/client.json
Jun 05 14:52:11.924 - [INFO] Use proxy:127.0.0.1:8087
Jun 05 14:52:11.924 - [ERROR] bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/caelan/Downloads/XX-Net-3.3.1/code/default/x_tunnel/start.py", line 19, in main
    client.main()
  File "/Users/caelan/Downloads/XX-Net-3.3.1/code/default/x_tunnel/local/client.py", line 149, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/Users/caelan/Downloads/XX-Net-3.3.1/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "/Users/caelan/Downloads/XX-Net-3.3.1/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "/Users/caelan/Downloads/XX-Net-3.3.1/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')

**Comment by jzp820927** [comment]
Jun 05 14:52:11.924 - [ERROR] bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')
Exception in thread Thread-61:

你的 1080 端口被占用了，你是不是同时运行了 SS 客户端？

**Comment by caelanyang** [comment]
@jzp820927 没有啊，今天下午之前只用xx，日志中也有那个error，没有图表盒设置页面。今天下午为了暂时翻墙，下载了lantern。但是并没有在终端运行xx时打开lantern。

**Comment by jzp820927** [comment]
终端执行下面的命令
netstat -tlnp|grep 1080
把输出的内容贴出来看看

**Comment by caelanyang** [comment]
经过一番折腾问题已经解决了，感谢 @jzp820927 的耐心回复。
经过是这样的：
通过终端 Python 运行的那个日志显示1080端口被占用，刚开始没在意，查看了占用1080的是ss-local的进程，结合搜索结果和 @jzp820927 的回复，看到这属于ss。猛然想起自己以前好像安装过ss。然后经过一番折腾才找到是使用homebrew安装的，没有桌面图标。这才通过homebrew卸载掉。然后重启电脑就可以了，现在已经部署好了，正常使用。谢谢。
