### ISSUE TITLE
Mac 3.3.2没有菜单栏图标

### ISSUE THREAD

**Issue by wanghz** [XX-net/XX-Net#5659]
---
## 问题内容
如题，MacOS Sierra 10.12.4，试了很多办法都不见菜单栏图标，不能设置AutoProxy， 只好设置全局代理，挺不方便。

> Jun 06 14:02:05.479 - [INFO] SSL use version:TLSv1
Jun 06 14:02:05.480 - [INFO] OpenSSL support alpn
Jun 06 14:02:05.482 - [INFO] load ip range file:/Applications/XX-Net-3.3/data/gae_proxy/ip_range.txt
Jun 06 14:02:05.504 - [INFO] load google ip_list num:300, gws num:300
Jun 06 14:02:05.511 - [INFO] OpenSSL support alpn
Jun 06 14:02:05.511 - [DEBUG] get ip:202.78.113.229 t:153
Jun 06 14:02:05.514 - [DEBUG] get ip:115.84.108.142 t:229
Jun 06 14:02:05.519 - [INFO] load manual.ini success
Jun 06 14:02:05.519 - [DEBUG] ## GAEProxy set keep_running: True
Jun 06 14:02:05.520 - [INFO] ------------------------------------------------------
Jun 06 14:02:05.520 - [INFO] Python Version : 2.7.10
Jun 06 14:02:05.522 - [INFO] OS : Release:10.12.4; Version:('', '', '') Machine:x86_64
Jun 06 14:02:05.522 - [INFO] Listen Address : 127.0.0.1:8087
Jun 06 14:02:05.522 - [INFO] GAE APPID : 
Jun 06 14:02:05.522 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jun 06 14:02:05.522 - [INFO] ------------------------------------------------------
Jun 06 14:02:05.547 - [INFO] GoAgent CA exist
Jun 06 14:02:05.588 - [DEBUG] network is ok, cost:150 ms
Jun 06 14:02:05.748 - [DEBUG] create_ssl update ip:202.78.113.229 time:156 h2:0
Jun 06 14:02:05.748 - [DEBUG] get ip:115.84.108.43 t:233

**Comment by jzp820927** [comment]
XX 已经正常运行，就别纠结图标了，自己配置下浏览器代理，就可以用了

**Comment by wanghz** [comment]
自己配置下浏览器代理操作起来麻烦，不如图标操作方便，如果能增加命令行选项或配置文件也不错。

**Comment by jzp820927** [comment]
你可以 google 搜索下，mac 有没有设置系统代理的脚本。项目现在很少更新了，只能靠自己了。

**Comment by wanghz** [comment]
好，只能如此，谢谢
