### ISSUE TITLE
貌似翻不了墙？

### ISSUE THREAD

**Issue by RicoLiu** [XX-net/XX-Net#5663]
访问不到Google，以下为诊断信息和日志：

XX-Net Status:

sys-platform: x86_64, Darwin-16.6.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64
os-release: 16.6.0
os-detail: Release:10.12.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2754
network-status: unknown
connected-link: new:0 used:0
worker: h1:11 h2:3
scan-ip-thread-num: 50
ip-quality: 256
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

Jun 06 21:51:53.454 - [DEBUG] create ssl timeout fail.
Jun 06 21:52:06.557 - [DEBUG] create ssl timeout fail.
Jun 06 21:52:07.350 - [DEBUG] create ssl timeout fail.
Jun 06 21:52:13.284 - [DEBUG] create ssl timeout fail.
Jun 06 21:52:13.489 - [DEBUG] create ssl timeout fail.
Jun 06 21:52:17.486 - [INFO] GAE CONNECT clients4.google.com:443
Jun 06 21:52:17.494 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/rappor
Jun 06 21:52:23.061 - [INFO] GAE CONNECT clients4.google.com:443
Jun 06 21:52:23.068 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/uma/v2
Jun 06 21:52:33.669 - [DEBUG] create ssl timeout fail.

**Comment by candy2107** [comment]
高级 - 检查所有IP

**Comment by jzp820927** [comment]
请升级到最新版，已经解决了这个问题
network-status: unknown

**Comment by taocunguijs** [comment]
建议升级3.3.4
