### ISSUE TITLE
#5631 解决方案, 拔掉网线，断网后会导致丢失ip

### ISSUE THREAD

**Issue by taocunguijs** [XX-net/XX-Net#5666]
版本：　 master　分支最新代码（commit 8464ea0）

复现步骤：　1. xx-net　正常启动，　扫描到n个good ip
　　　　　　2. 断网
　　　　　　3.　几分钟后发现可用ip　大量丢失

**Comment by taocunguijs** [comment]
断网前：

![2017-06-07 12 25 32](https://user-images.githubusercontent.com/7934431/26862392-64ccb4cc-4b7d-11e7-946c-ed7e86922687.png)

断网一分钟后：

![2017-06-07 12 26 45](https://user-images.githubusercontent.com/7934431/26862404-79bc7a0c-4b7d-11e7-9b1a-602582cafeaa.png)

**Comment by taocunguijs** [comment]
相关提交：　

bugfix report network fail&check #5631 #5650

**Comment by jzp820927** [comment]
好像已经合并，发布新版本了。

**Comment by taocunguijs** [comment]
我用的版本的最后一次commit

commit 8464ea0f0ffc583dbca6e4ea9c2b70f5adf68375
Merge: 078ccdb 34181d3
Author: yeahwu <yeahwu@users.noreply.github.com>
Date:   Tue Jun 6 08:46:15 2017 +0800

    Merge pull request #5650 from SeaHOH/bugfix-temp
    
    bugfix report network fail&check #5631

**Comment by taocunguijs** [comment]
@jzp820927 

我用的代码是最新的，跟release　版本那个提交没有关系。

**Comment by taocunguijs** [comment]
该问题在2016-10-15日修复过一次，最近的一次提交又改回来了


![image](https://user-images.githubusercontent.com/7934431/26862863-15b3b512-4b81-11e7-93b7-1b00821ee222.png)

**Comment by taocunguijs** [comment]
经验证3.3.2　正式release　的版本没有这个问题。

**Comment by jzp820927** [comment]
现在最新版已经是 3.3.3 了，你 OUT 了

**Comment by taocunguijs** [comment]
taocunguijs@taocunguijs-HP-ProDesk-480-G3-MT:~/code/github/XX-Net$ git diff 8464ea0..HEAD
diff --git a/SwitchyOmega/SwitchyOmega.crx b/SwitchyOmega/SwitchyOmega.crx
index 6ff682e..ee2e9a4 100644
Binary files a/SwitchyOmega/SwitchyOmega.crx and b/SwitchyOmega/SwitchyOmega.crx differ
diff --git a/code/default/download.md b/code/default/download.md
index 4317f5d..180ba6c 100644
--- a/code/default/download.md
+++ b/code/default/download.md
@@ -1,7 +1,7 @@
 
 ## 下载(Download)：
 测试版(Test)：
-https://codeload.github.com/XX-net/XX-Net/zip/3.3.2
+https://codeload.github.com/XX-net/XX-Net/zip/3.3.3
 
 稳定版(Stable)：
 https://codeload.github.com/XX-net/XX-Net/zip/3.3.1
diff --git a/code/default/update_version.txt b/code/default/update_version.txt
index 0315356..f8a52ae 100644
--- a/code/default/update_version.txt
+++ b/code/default/update_version.txt
@@ -1,6 +1,6 @@
 
 ## 升级(Update)：
 测试版(Test)：
-https://codeload.github.com/XX-net/XX-Net/zip/3.3.2 d6f316e2941f6016fea144b163ae3469b8a2f7037d9c9dd43b800f3b9c8c1f0c
+https://codeload.github.com/XX-net/XX-Net/zip/3.3.3 7aa8b0b4d6255e464758896628b18897cf57cabe2d5b5e86145325b410ca1d19
 稳定版(Stable)：
 https://codeload.github.com/XX-net/XX-Net/zip/3.3.1 586202313ca894e1b74ff0cbfe002d9807aae9569416bc1c2bdc0131afefd069
diff --git a/code/default/version.txt b/code/default/version.txt
index 4772543..619b537 100644
--- a/code/default/version.txt
+++ b/code/default/version.txt
@@ -1 +1 @@
-3.3.2
+3.3.3

**Comment by taocunguijs** [comment]
我使用的8464ea0　与最新的3.3.3　没有实质性差异

**Comment by taocunguijs** [comment]
稍等sync　最新代码　验证这个问题

**Comment by tansuozhexigua** [comment]
之前的good ip一般都在1200左右 可是现在降到了300左右 不知道各位是怎样一种情况 烦请各位大神指点迷津

**Comment by SeaHOH** [comment]
@taocunguijs 
我针对你之前报告的问题修改的，没有仔细读其它相关代码。
刚才又看了一下，感觉之前丢 IP 的修复是有问题的，等会儿我会再提交一个修复。

**Comment by SeaHOH** [comment]
@taocunguijs 
麻烦再测试一下
https://github.com/SeaHOH/XX-Net/tree/tryfix-temp

**Comment by taocunguijs** [comment]
@SeaHOH 
　你的这个版本测试拔掉网线不会丢失ip　，　之前那个unknow　和ok　之间频繁切换的issue 得回家才能测试，公司的网络太好，无法复现这个问题

**Comment by taocunguijs** [comment]
@SeaHOH 
　１。插着网线的时候，运行起来xx-net 然后中途拔掉网线，　还是会大量丢失ip

   　２。　拔掉网线，再运行起来xx-net，　没有问题

**Comment by taocunguijs** [comment]
那个临时版本，先断网再运行xx-net ip不会丢失; 但是先运行xx-net后断网，就会丢失所有ip,越一分钟左右所有ip全部丢失。

**Comment by taocunguijs** [comment]
这个问题必现的，做复现前注意备份good_ip.txt文件

**Comment by SeaHOH** [comment]
@taocunguijs 
你第一个回复说不丢 IP，第二三个回复是相同的意思：先断网不丢，中途断网会迅速丢完。

刚才我自己做了个测试：
1. 联网启动 XX-net 扫描 IP
2. 等 IP 数量大于 15 断网
3. 通过全局端口访问任意地址
4. 网络状态迅速变为 `fail`，IP 数量无太大波动
5. 恢复联网，一切正常，IP 数量无太大波动

**Comment by SeaHOH** [comment]
又测试了几遍，不仅不丢，反而涨了......
删除 data 重新扫描就不会涨，接着上次的测试 data 重复测试就会涨。

**Comment by taocunguijs** [comment]
我第一个回复，没发现规律，当时开启xx-net的时候没联网，所以没丢，


中途断网我这儿必现丢ip，一分钟左右全丢光，断网后我就一直开着8085那个状态页观察，没有用浏览器访问别的任何网址

**Comment by taocunguijs** [comment]
是不是因为你的ip太少了，我操作之前的ip为5000个

**Comment by taocunguijs** [comment]
我这儿断网之后状态页一直显示网络为ok,所以才会丢光

**Comment by SeaHOH** [comment]
我平时没用 XX-Net，给我个几千的 good_ip.txt 试试。

**Comment by taocunguijs** [comment]
稍等

**Comment by SeaHOH** [comment]
保险起见，再问一句：你是否是用下面这个分支测试的？这个是才添加的。
https://github.com/SeaHOH/XX-Net/tree/tryfix-temp

**Comment by taocunguijs** [comment]
[good_ip.txt](https://github.com/XX-net/XX-Net/files/1058468/good_ip.txt)

**Comment by taocunguijs** [comment]
你那个版本我试过，一样会丢

**Comment by taocunguijs** [comment]
https://github.com/SeaHOH/XX-Net/tree/tryfix-temp  这个版本中途断网会丢ip

**Comment by SeaHOH** [comment]
又测试了几遍，完全正常，如果断网后不使用代理，会在一分钟时间内转换为 `fail`，IP 数量不变。

**Comment by taocunguijs** [comment]
那我明天再用你那个版本多测几遍试试

**Comment by SeaHOH** [comment]
作为对比测试，使用当前 XX-net 主分支，中途断网 IP 掉的飞快。
你是不是哪里弄错了？请检查 `check_local_network.py` 文件，主要修改是这个 34b6f1eac39a5455cfbaacf1a4cd9dd4204f474f 。

**Comment by taocunguijs** [comment]
对https://github.com/SeaHOH/XX-Net/tree/tryfix-temp 反复做压力测试，一个多小时（测了有个几十次），只出现一次丢ip

![2017-06-08 06 57 50](https://user-images.githubusercontent.com/7934431/26905331-68961ffc-4c19-11e7-9d40-00c0a84c817e.png)

其他得情况，都是过一会儿网络状况变为fail 就不会丢ip

概率太低了，不太好测，怀疑是xx-net 刚起来没初始化完成，我就断网导致的，你这个改动可以解决该问题，极限情况感觉可以不用管了，概率太低了，复现太费劲，正常使用也没有我这么干的，不会有大问题

**Comment by taocunguijs** [comment]
放心吧代码我用比较工具，比较后，跟你一模一样，我没对代码做过任何修改，我都是直接从上面下载zip包覆盖替换的，而且改动也一样，有你上面的那个改动

**Comment by taocunguijs** [comment]
这个问题不用管了，只能低概率复现，复现难度太大。

**Comment by taocunguijs** [comment]
补充下，打上你的patch后是低概率复现，仅一次，之前主线版本必现快速丢ip

**Comment by SeaHOH** [comment]
了解，感谢测试。

**Comment by taocunguijs** [comment]
再次感谢修复该bug,问题关闭处理
