### ISSUE TITLE
关于goagent源代码学习，如何把server端代码本地运行测试

### ISSUE THREAD

**Issue by bcddogdown** [XX-net/XX-Net#5668]
goagent一直在用，用了有好几年了，感谢各位前辈的努力为我们广大程序提供了这么好的工具！
最近也想研究一下，在读goagent的源代码(V3.2.3)，请问诸位，你们是如何把部署在age上的server
端代码放在本地测试运行的？按照gae的官方文档用：
```
$ dev_appserver.py app.yaml
```
好像不行，默认是监听在8080的HTTP，而goagent我跟踪代码发现是连接服务器的443端口，用的是https,在do_handshake()就报错了。google搜了下说要设置什么反向代理就可以，头大啊。。

小白一枚,求教各位大神.还望不吝赐教!

**Comment by jzp820927** [comment]
不知道你为什么要把服务端运行在本地机器。
goa 的服务端的运行在 google 的 gae 环境下的，不是一个简单的服务端程序，要有 gae 的环境才行。
而且我们正常情况下，使用的 GAE 代理，不是你想的这么简单，不是直接连接到 GAE 服务端的。
GAE 是后端服务器，监听 8080，前端服务器是 gws，用的 https 协议，使用连接 443 端口。然后 google 内部再通过前端服务器再连接后端服务器，在前端和后端之间，还会做负载均衡，资源动态分配等，很复杂的系统。在本地机应该很难模拟真实的 GAE 整个环境。

**Comment by bcddogdown** [comment]
非常感谢您的回答！

那你们开发者是如何调试server端代码的呢？本地调试还是直接部署到gae然后用[gae console](https://console.cloud.google.com)的debug信息来调试？

**Comment by SeaHOH** [comment]
付费版本可以 SSH 到虚拟机，免费的确只能用网页版 SSH 功能。

**Comment by jzp820927** [comment]
我觉得用 web console 应该是最方便的。而且我认为，主要调试的对象应该不是服务端，而是客户端，服务端就是调用 gae 的 urlfetch  api 就行了，很简单，主要功能是放在客户端，客户端应该才是重点调试的对象。

**Comment by bcddogdown** [comment]
感谢各位的回答！解决了我心中的疑惑，学习了！

**Comment by SeaHOH** [comment]
如果有心优化服务端也很好，一个稳定的服务端也很重要，urlfetch 的编码问题也需要解决。不过由于 Python 本身的特性，其实已经很稳定了，反而社长的 Go 服务端连续处理多个大文件时还是不够稳定。
