### ISSUE TITLE
我想知道对其他代理方式有影响吗？

### ISSUE THREAD

**Issue by lukepushsolo** [XX-net/XX-Net#5671]
我换了一个香港的ip，ping google.hk完全没有问题，但是所有网页都打不开。我想知道这和XX-NET的代理有冲突吗？关键是我并没有开全局代理。

**Comment by jzp820927** [comment]
你 香港的ip 是用的 hosts 方式麽？

**Comment by lukepushsolo** [comment]
yes,先是在hosts文件里添加了ip，然后用L2TP OVER IPSEC网络连接，ping没有问题

**Comment by SeaHOH** [comment]
你需要使用自己的代理规则，把 `hosts` 文件中定义的域名排除在代理范围外。

**Comment by jzp820927** [comment]
你的意思，你连接的 为皮恩？

**Comment by lukepushsolo** [comment]
yes, 但是用不了，所以我想是不是这两个代理冲突了？

**Comment by jzp820927** [comment]
如果是用了 为皮恩，所有流量都会走 为皮恩，就没必要再用 XXNET 了。
你指的所有网页，是指的国内的网页？还是国内+国外？如果是国内+国外都无法打开，应该是你 为皮恩 配置有问题吧。

**Comment by lukepushsolo** [comment]
我没有找出问题来，关掉XXNET后，连上“为皮恩”，登陆qq显示ip在香港，ping没有问题，但就是无法访问网页（ps.所有网页），可能是我的问题orz

**Comment by jzp820927** [comment]
检查下，你的系统代理是不是还设置的 XXNET？如果是，把系统代理清空。

**Comment by lukepushsolo** [comment]
如何清空系统代理？是指LAN设置吗？

**Comment by jzp820927** [comment]
internet，连接，局域网设置里面的设置，如果再不清楚，你就 google 搜索一下

**Comment by lukepushsolo** [comment]
呃，还是不行，顺便证书挂掉了

**Comment by jzp820927** [comment]
我上面都说了，连了 为皮恩，就不用 XXNET 了，你还去处理证书问题干嘛。如果还是不行，就把 DNS 换成 8.8.8.8 试试。

**Comment by lukepushsolo** [comment]
不是，就是单纯使用xxnet的时候显示证书fail，但是google照样连，chrome版本59.0.3071.86（正式版本） （32 位）

**Comment by jzp820927** [comment]
证书问题，就是按照 #5322 处理就行了，如果不行，就是证书没清理干净，再不行，就把 XX 删除了，chrome 卸载了，全部重装。

**Comment by lukepushsolo** [comment]
反正xxnet使用没问题，只是显示证书挂了

**Comment by jzp820927** [comment]
既然能使用，就别管证书了
