### ISSUE TITLE
误删了xx-net的文件夹，重新下载，用之前的appid部署，显示部署成功实际却没有之前私人appid的网速了？

### ISSUE THREAD

**Issue by demon19911011** [XX-net/XX-Net#5673]
重新下载之后用之前的私人appid部署有人知道应该怎么做吗？
un 08 22:28:22.849 - [DEBUG] restore ip:200.187.85.54
Jun 08 22:28:27.862 - [DEBUG] ip:92.246.12.250 real fail
Jun 08 22:28:30.037 - [WARNING] direct_handler.fetch:TypeError("unsupported operand type(s) for +=: 'int' and 'NoneType'",)
Jun 08 22:28:30.037 - [DEBUG] 115.164.12.243 close:request_fail
Jun 08 22:28:30.037 - [DEBUG] ssl_closed 115.164.12.243
Jun 08 22:28:30.037 - [DEBUG] get ip:87.79.22.219 t:778
Jun 08 22:28:30.556 - [DEBUG] get ip:103.9.105.109 t:1315
Jun 08 22:28:31.061 - [DEBUG] get ip:163.28.116.21 t:557
Jun 08 22:28:31.575 - [DEBUG] get ip:115.164.12.243 t:1918
Jun 08 22:28:31.638 - [DEBUG] create_ssl update ip:87.79.22.219 time:1144 h2:1
Jun 08 22:28:32.079 - [DEBUG] get ip:200.187.85.54 t:2338
Jun 08 22:28:32.580 - [DEBUG] get ip:109.195.105.186 t:1706
Jun 08 22:28:32.648 - [WARNING] no enough ip
Jun 08 22:28:32.863 - [DEBUG] ip:84.208.42.140 real fail
Jun 08 22:28:34.102 - [WARNING] no enough ip
Jun 08 22:28:34.557 - [DEBUG] 103.9.105.109 fail:timeout('timed out',)
Jun 08 22:28:35.105 - [DEBUG] 163.28.116.21 fail:timeout('timed out',)
Jun 08 22:28:35.105 - [WARNING] no enough ip
Jun 08 22:28:35.576 - [DEBUG] 115.164.12.243 fail:timeout('timed out',)
Jun 08 22:28:36.106 - [WARNING] no enough ip
Jun 08 22:28:36.106 - [DEBUG] report_connect_fail:103.9.105.109
Jun 08 22:28:37.107 - [WARNING] no enough ip
Jun 08 22:28:37.107 - [DEBUG] report_connect_fail:163.28.116.21
Jun 08 22:28:37.865 - [DEBUG] ip:115.164.12.140 real fail
Jun 08 22:28:38.112 - [WARNING] no enough ip
Jun 08 22:28:38.112 - [DEBUG] report_connect_fail:115.164.12.243
Jun 08 22:28:39.115 - [WARNING] no enough ip
Jun 08 22:28:40.117 - [WARNING] no enough ip
Jun 08 22:28:41.124 - [WARNING] no enough ip
Jun 08 22:28:41.124 - [DEBUG] create_ssl update ip:200.187.85.54 time:1264 h2:1
Jun 08 22:28:41.124 - [DEBUG] create_ssl update ip:109.195.105.186 time:2917 h2:1
Jun 08 22:28:43.144 - [WARNING] no enough ip

**Comment by myjlpt** [comment]
ip要重新扫描当然慢了

**Comment by jzp820927** [comment]
请问你是部署问题？还是网速问题？

**Comment by LockZhao** [comment]
[WARNING] no enough ip  应该是之前扫描的ip都没了，需要重新扫描，所以很慢

**Comment by demon19911011** [comment]
部署没有问题，只是速度慢了很多，不过现在好些了，谢谢

**Comment by jzp820927** [comment]
可能有时候干扰严重的时候，就会出现速度慢的情况，这个应该都是暂时的
