### ISSUE TITLE
突然显示“尚未建立连接”

### ISSUE THREAD

**Issue by Rafael-Chen** [XX-net/XX-Net#5674]
版本：3.3.1
Chrome版本：58

此前一直正常，今天突然显示“尚未建立连接”，日志中不断[Debug]report_connect_fail network fail
诊断信息如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1211
network-status: unknown
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 407
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

GAEProxy日志：
Jun 09 10:07:42.229 - [DEBUG] 84.208.42.243 fail:error(' certficate is none',)
Jun 09 10:07:42.229 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:42.229 - [DEBUG] get ip:203.211.8.17 t:452
Jun 09 10:07:42.391 - [DEBUG] 210.187.25.235 fail:timeout('timed out',)
Jun 09 10:07:42.391 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:42.391 - [DEBUG] get ip:209.33.235.120 t:452
Jun 09 10:07:42.438 - [DEBUG] 209.52.189.87 fail:timeout('timed out',)
Jun 09 10:07:42.438 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:42.438 - [DEBUG] get ip:209.52.189.97 t:453
Jun 09 10:07:42.750 - [DEBUG] 194.182.232.118 fail:error(' certficate is none',)
Jun 09 10:07:42.750 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:42.750 - [DEBUG] get ip:40.133.6.58 t:453
Jun 09 10:07:42.782 - [DEBUG] 202.38.180.207 fail:timeout('timed out',)
Jun 09 10:07:42.782 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:42.782 - [DEBUG] get ip:194.182.232.114 t:453
Jun 09 10:07:42.908 - [DEBUG] 64.71.249.90 fail:timeout('timed out',)
Jun 09 10:07:42.908 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:42.908 - [DEBUG] get ip:1.9.24.16 t:453
Jun 09 10:07:43.002 - [DEBUG] 42.112.9.212 fail:timeout('timed out',)
Jun 09 10:07:43.002 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:43.002 - [DEBUG] get ip:60.199.175.169 t:453
Jun 09 10:07:43.049 - [DEBUG] 61.91.160.81 fail:timeout('timed out',)
Jun 09 10:07:43.049 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:43.049 - [DEBUG] get ip:45.64.31.52 t:453
Jun 09 10:07:43.472 - [DEBUG] 202.148.204.81 fail:timeout('timed out',)
Jun 09 10:07:43.472 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:43.472 - [DEBUG] get ip:1.255.33.235 t:453
Jun 09 10:07:44.319 - [DEBUG] 58.26.8.93 fail:timeout('timed out',)
Jun 09 10:07:44.319 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.319 - [DEBUG] get ip:216.11.246.210 t:444
Jun 09 10:07:44.334 - [INFO] GAE CONNECT clients4.google.com:443
Jun 09 10:07:44.366 - [DEBUG] 42.112.9.239 fail:timeout('timed out',)
Jun 09 10:07:44.366 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.366 - [DEBUG] get ip:209.33.235.98 t:445
Jun 09 10:07:44.381 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/uma/v2
Jun 09 10:07:44.381 - [DEBUG] host_conn_pool clients4.google.com get:65.199.32.178 handshake:512
Jun 09 10:07:44.407 - [DEBUG] 1.9.57.245 fail:timeout('timed out',)
Jun 09 10:07:44.407 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.419 - [DEBUG] get ip:117.102.117.231 t:445
Jun 09 10:07:44.449 - [DEBUG] 173.224.96.14 fail:timeout('timed out',)
Jun 09 10:07:44.449 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.449 - [DEBUG] get ip:194.182.232.118 t:447
Jun 09 10:07:44.496 - [DEBUG] 204.111.84.210 fail:timeout('timed out',)
Jun 09 10:07:44.496 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.496 - [DEBUG] get ip:210.187.25.235 t:448
Jun 09 10:07:44.731 - [DEBUG] 24.100.187.141 fail:timeout('timed out',)
Jun 09 10:07:44.731 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.731 - [DEBUG] get ip:209.52.189.87 t:450
Jun 09 10:07:44.809 - [DEBUG] 216.177.189.183 fail:timeout('timed out',)
Jun 09 10:07:44.809 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.809 - [DEBUG] get ip:202.38.180.207 t:450
Jun 09 10:07:44.965 - [DEBUG] 182.253.220.248 fail:timeout('timed out',)
Jun 09 10:07:44.965 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:44.965 - [DEBUG] get ip:64.71.249.90 t:450
Jun 09 10:07:44.965 - [INFO] DIRECT chucked t:583 s:22 200 clients4.google.com /uma/v2
Jun 09 10:07:45.378 - [DEBUG] 118.98.36.147 fail:timeout('timed out',)
Jun 09 10:07:45.378 - [DEBUG] report_connect_fail network fail
Jun 09 10:07:45.378 - [DEBUG] get ip:42.112.9.212 t:452
Jun 09 10:07:45.744 - [INFO] GAE CONNECT clients4.google.com:443
......

**Comment by jzp820927** [comment]
请升级到最新版，最新版，应该解决了这个问题
