### ISSUE TITLE
http://localhost:8085/ 无法访问

### ISSUE THREAD

**Issue by x-a** [XX-net/XX-Net#5681]
Win10 1703 + chrome 版本59 64位 + xx-net3.3.1

右下方有xx-net图标, chrome浏览器也按照步骤装了插件

端口号:
`TCP    127.0.0.1:8085         0.0.0.0:0              LISTENING       8672`

launcher.log下没有内容, 0字节

本地的哪个服务没有开??

**Comment by SeaHOH** [comment]
>端口号:
TCP 127.0.0.1:8085 0.0.0.0:0 LISTENING 8672

状态对的啊，8672 是 PID？建议手动设置代理或检查防火墙。

**Comment by kirbyzhu** [comment]
直接点右下角图标 就应该能弹出来

**Comment by x-a** [comment]
点击右下角图标能弹出来, 但是访问不了啊 @kirbyzhu

**Comment by x-a** [comment]
手动设置代理?  如何设置?  我是按照新手教程一步步来的, http://localhost:8085/  这个网站应该类似与后台管理吧, 在这里设置?  但我访问不了啊 @SeaHOH

**Comment by x-a** [comment]
我刚才退出xx-net, 再在cmd里面查看确实没有8085端口了,  证明我打开xx-net, 8085端口是被该服务占用了, 但是为啥访问不了就有点怪了 @SeaHOH

**Comment by x-a** [comment]
@SeaHOH  @kirbyzhu   感谢两位,  是防火墙的原因, 关掉后, 可以打开http://127.0.0.1:8085/
