### ISSUE TITLE
点击start.vbs后变成在IE浏览器打开，之前都是chrome打开的，怎么回事

### ISSUE THREAD

**Issue by Jimmy45** [XX-net/XX-Net#5683]
之前chrome打开网页出现问题，于是我就打算重新设置chrome和xxnet，但是点开start.vbs后变成在IE打开页面，点击xxnet图标也是，之前都可以在chrome中打开的。我是打算完全重装xxnet的，可是删除chrome和xxnet证书后双击vbs文件就显示证书已导入。现在似乎证书导入不进去了，打开网页也显示不是私密连接。求大神指导

**Comment by wenliyang** [comment]
#5322

**Comment by Jimmy45** [comment]
@wenliyang 找不到证书在哪里，chrome里没有，运行cert那两项也找不到

**Comment by Jimmy45** [comment]
@wenliyang 有没有什么能把之前的东西全部清理掉，重新安装设置的方法

**Comment by jzp820927** [comment]
直接删除文件夹就是全部整理了，这个又不写注册表。

**Comment by yulu2000cn** [comment]
我也是同样的问题，希望谁能解决

**Comment by jzp820927** [comment]
WIN10 系统吗？

**Comment by yulu2000cn** [comment]
我的是win10 x64

**Comment by jzp820927** [comment]
试试 bat 能不能行？

**Comment by yulu2000cn** [comment]
不行，还是IE打开，不知道在哪控制这个

**Comment by jzp820927** [comment]
应该是 bat 的关联程序被改动了，可以 google 搜索一下，怎么解决 bat 的关联问题。
