### ISSUE TITLE
xx-net 安卓使用教程(不兼容安卓7)

### ISSUE THREAD

**Issue by candy2107** [XX-net/XX-Net#5687]
### [xx-net 安卓使用教程](https://github.com/XX-net/XX-Net/wiki/%E5%AE%89%E5%8D%93%E7%89%88)

**Comment by Jan9th** [comment]
貌似步骤比之前的少了不少步骤

**Comment by jzp820927** [comment]
支持一下，这个浏览器支持直接设置代理，这个挺有特点，比 FF 设置要方便多了。

**Comment by cuncaojin** [comment]
good！Thank you！

**Comment by qdpurple** [comment]
按照https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA 
打开设置-系统安全-从SD卡安装凭据（证书）.依次进入 XX-Net/data/gae_proxy , 选择该目录下的 CA.crt , 输入任意名称 , 按确定即可.入证书。
确定之后，提示“键入凭证存储的密码。” ，
请问证书密码是什么？

**Comment by JMaxime** [comment]
网页点不开啊

**Comment by jzp820927** [comment]
什么下载页面？什么网页？

**Comment by theratlesnake** [comment]
lighting web browser  是国产浏览器吗？随手百度，谷歌了一下，没看到官网

**Comment by jzp820927** [comment]
github 上的一个项目，应该是基于 chrome 内核的吧。

**Comment by JMaxime** [comment]
@jzp820927 已经解决 谢谢

**Comment by CHN008** [comment]
感谢分享,有去试试 :+1:

**Comment by fwfmiao** [comment]
什么时候兼容安卓7_(:з」∠)_

**Comment by jzp820927** [comment]
估计是 android 自身的问题，因为之前有几个人反映过，7 用不了，但只是网友的反应，不是官方的说明，或者你也可以试试，说不定也能用呢？

**Comment by Famingwu** [comment]
不兼容安卓7？只有安卓4.0和安卓7的设备，偏偏没有安卓5怎么破？！

**Comment by jzp820927** [comment]
如果可以 root 应该没问题。可以试试。

**Comment by rainbowsky911** [comment]
failed
步骤1√步骤3√步骤2线程没看懂，证书导入成功
 FlymeAndroid6.1,  xxnet3.1  
thanks

**Comment by rainbowsky911** [comment]
failed
步骤1√步骤3√步骤2线程没看懂，证书导入成功
 FlymeAndroid6.1,  xxnet3.1  
thanks

**Comment by ytxka** [comment]
@rainbowsky911 打开xxnet，找status里面的Number of IP-Scanning Threade,点settins，Max scan thread count改成200

**Comment by jzp820927** [comment]
@rainbowsky911 步骤2，不做也没影响，如果没有成功，看看日志？

**Comment by AIONZXP** [comment]
必须赞一个，好东西

**Comment by Freedom000** [comment]
额 什么时候兼容android 7  有朋友试过android 7或7.1么

**Comment by wf4gh** [comment]
本人的android 7.0不能用
以我个人微薄的开发经验，猜测原因可能是Android 7对应用间通讯及权限限制更严格了，虽然安全性提升了，但确实有些旧版本能用的功能无法顺利实现了

**Comment by fei5seven** [comment]
3.1一开始能用后来莫名其妙的出现了卡loading的问题 5.1 ，就很迷…

**Comment by fei5seven** [comment]
是只有在wifi环境下才能打开，流量环境打不开，奇怪

**Comment by dadou238** [comment]
1.手机版本号（NX523J_V1_CNCommon_V2.02）
2.Android 5.1.1
3.android system webview 版本号（50.0.2661.86）
4.XX-Net Status:

sys-platform: aarch64, Linux-3.10.73-perf-g9290072-00568-g5a61078-aarch64-with
os-system: Linux
os-version: #1 SMP PREEMPT Mon Jan 9 21:43:04 EST 2017
os-release: 3.10.73-perf-g9290072-00568-g5a61078
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 5.1.1; NX523J_V1 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Mobile Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.2
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:101 good:75
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:0
scan-ip-thread-num: 200
ip-quality: 519
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
______________________
除了证书添加信任失败，其他都弄好了。
虽然证书手机显示安装好了，在信任凭证列表中有。。但xx-net中显示fail...
不知是啥原因，捣腾了半天，实在自己无力解决。
大神们帮帮忙，解解惑哦
万分感谢
。。。

**Comment by candy2107** [comment]
@dadou238 
如果你能正常上网，就不用管证书状态

**Comment by dadou238** [comment]
@candy2107 
抱歉，就是不能正常上网，才去计较这些的。。。
看见你的回复后，以免无病呻吟，我卸载软件，删除手机文件，重新安装，但还是无法上网。。。
这是最新日志
XX-Net Status:

sys-platform: aarch64, Linux-3.10.73-perf-g9290072-00568-g5a61078-aarch64-with
os-system: Linux
os-version: #1 SMP PREEMPT Mon Jan 9 21:43:04 EST 2017
os-release: 3.10.73-perf-g9290072-00568-g5a61078
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 5.1.1; NX523J_V1 Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Mobile Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.2
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
____________________________________________
现在还是手机证书已经安装，其他全弄好了。。。
我小白一个，完全不懂是啥情况。。。

**Comment by candy2107** [comment]
@dadou238 
你的ip数量少，等他扫描半小时吧
通过 lightning browser 访问 127.0.0.1:8085 证书状态如何

**Comment by dadou238** [comment]
@candy2107 
在lightning browser访问127.0.0.1:8085，全部正常ok...证书也ok
但用lighting 浏览器还是无法用谷歌

**Comment by candy2107** [comment]
@dadou238 
你手机上有没有安装腾讯管家，百度卫士，360等安全类软件？
lightning browser 输入 google.com/ncr 能打开么

**Comment by GuanLuoFu** [comment]
我的三星S7安卓7可以，但仅限用lightning，其他火狐，chrome都显示证书fail，包括xxnet自己也显示fail，神奇的是lightning显示证书成功，而且第一次安装好证书后再移除，依然显示证书成功，不过浏览网页虽然可以但总是会提示站点不可信，这个很麻烦，不知道谁有办法解决

**Comment by asmosn** [comment]
请问yandex+xxnet如何设置?  加载switchyomega 后无法打开扩展配置~

**Comment by underlaw** [comment]
为什么不能弄成蓝灯那样的一键开关了

**Comment by xxnet** [comment]
​要做的，不过还没有实现，有谁熟悉的来搞搞？
