### ISSUE TITLE
1.1版本翻墙很不稳定

### ISSUE THREAD

**Issue by shawwokou123** [XX-net/XX-Net#57]
今天开始不稳定
1.1版本已经无法使用，大量皇字出现
1.21 勉强能翻

**Comment by xxnet** [comment]
昨天的公共appid流量跑光了。

先确认你是否部署了自己的appid，然后把日志发出来分析。

接下来会限制公共appid不能看视频，一个视频顶看网页好多好多了。

**Comment by shawwokou123** [comment]
我是自己的ID，昨天出现大量黄字

**Comment by shawwokou123** [comment]
我后来不得不使用1.2.1版本，你用1，1版本试试。

**Comment by xxnet** [comment]
1.1的appid太少了，很容易就跑光流量。

已经对服务端进行限制，不能看视频了。
看视频实在太耗流量了。

**Comment by xxnet** [comment]
早期的版本用的是比较激进的策略，容易被GFW检测出来然后封锁。
后期的版本就改了保守的策略，并采用动态优化性能的方法，虽然刚启动会慢，但慢慢就快起来。

谢谢反馈。
