### ISSUE TITLE
关于GoAgent证书的问题

### ISSUE THREAD

**Issue by mssues** [XX-net/XX-Net#570]
我在查看GoAgent证书的时候，看到这个证书的权限是全部权限，希望能够更改为创建时只创建需要的权限，谢谢！
![15123123123](https://cloud.githubusercontent.com/assets/13174648/8507004/60aaef8e-2263-11e5-9908-8a4248e39500.PNG)

**Comment by mssues** [comment]
或者能够给出证书够用的权限列表，我能够自己改正一下，谢谢！

**Comment by xxnet** [comment]
是什么操作系统？
  从截图上看应该是OSX

导入证书的代码在 goagent/x.x.x/local/cert_util.py
  import_mac_ca 函数中。

调用的命令是 security add-trusted-cert
从逻辑上讲，我们需要的权限，就是服务器身份验证。

你可以研究看命令行应该怎么改，如果可以，帮忙提交补丁。
 或者把命令导入的方案反馈回来，我来合并代码也可以。

谢谢

在 2015年7月4日 下午3:45，mssues <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
从截图来看，这应该是Windows吧

**Comment by mssues** [comment]
Windows 7 系统，我就是想问一下证书的权限设置。

**Comment by mssues** [comment]
Windows 7 系统，我就是想问一下证书的权限设置。

**Comment by mssues** [comment]
Windows 7 系统，我就是想问一下证书的权限设置。

**Comment by mssues** [comment]
Windows 7 系统，我就是想问一下证书的权限设置。
