### ISSUE TITLE
host:www.youtube.com not support GAE

### ISSUE THREAD

**Issue by way-zer** [XX-net/XX-Net#5704]
最近几天youtube进不去
按提示修改manual.ini也没用

日记中有提示:
Jun 14 12:25:54.362 - [WARNING] IP:202.169.173.215 host:www.youtube.com not support GAE, server type: status:403

诊断消息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1647
network-status: OK
connected-link: new:4 used:0
worker: h1:12 h2:2
scan-ip-thread-num: 50
ip-quality: 171
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ViajayTsui** [comment]
那咋整呢？

**Comment by SeaHOH** [comment]
有 403 提示就是没有正确修改，请检查。

**Comment by jzp820927** [comment]
试试这样看行不行
改 data/gae_proxy/manual.ini 文件
[hosts]
.youtube.com = gae

**Comment by wolfmarelalala** [comment]
之前打不开主页，现在都打不开了

**Comment by panpeach** [comment]
我的能打开，但时常要人机验证一下

**Comment by shipbk** [comment]
昨天还能打开视频链接，现在都不行了。
用notepad++ 改.youtube.com = gae 还是没用。

**Comment by poplong2** [comment]
改manual.ini 文件的方法目前有效，要是你失败了，可能是以下的原因：
如果你是从网页直接复制粘贴的，请检查一下“.youtube.com = gae ”前面是否有一个空格？这个空格记得一定要删掉！否则将失效。

**Comment by shipbk** [comment]
改成gae连接还是不行，日志如下

Jun 14 19:04:01.171 - [WARNING] IP:223.62.225.184 host:www.youtube.com not support GAE, server type: status:403

**Comment by byzod** [comment]
@jzp820927 改了之后没有504了
这个设置到底是什么意思，提示说不支持gae，改成`=gae`反而正常了？

**Comment by SeaHOH** [comment]
这个不支持提示是错误的。

**Comment by jzp820927** [comment]
@byzod .youtube.com = gae ，这个的意思是说，让 youtube.com 相关的域名的连接请求，全部通过 GAE 服务器来中转一次，之前的设置是不中转，直接连接到 youtube 的服务器

**Comment by ywcnba** [comment]
我也是这个问题啊... 我增加了manual.ini，但是还是说youtube are not support GAE, server type: status:403
昨天还好好的呢

**Comment by jzp820927** [comment]
有问题的看看自己是不是建立了一个名字叫manual.ini.txt的文件吧，我看了半天发现居然是扩展名在搞鬼。

**Comment by 13130110047** [comment]
你好，为什么我的data/gae_proxy/中没有manual.ini文件，只有config.ini文件

**Comment by jzp820927** [comment]
@13130110047 手动新建，注意扩展名

**Comment by roc1010kmt** [comment]
之前一直是direct，為什麼今天只能gae了？

**Comment by jzp820927** [comment]
@roc1010kmt google 封锁了直连流量，你用直连模式访问 youtube 首页，就知道是怎么回事了

**Comment by way-zer** [comment]
data/gae_proxy/manual.ini 还是能用的
之前是编码问题 UTF-8不能用，必须是 UTF-8 无BOM 编码

**Comment by jzp820927** [comment]
所以才建议你们不要用 记事本修改，记事本容易破坏格式和编码，notepad++ 可以保证编码不变。

**Comment by billizpl** [comment]
增加或改 data/gae_proxy/manual.ini 文件
[hosts]
.youtube.com=gae
用记事本就可以了。我解决了我的问题，谢谢之前的朋友的提示。
只是之前的朋友在gae 和=前多加了空格，让好多人没解决问题。

**Comment by jzp820927** [comment]
LS 的经验值得推广
