### ISSUE TITLE
IP数量清零是怎么回事？

### ISSUE THREAD

**Issue by wangyunlg** [XX-net/XX-Net#5707]
正在浏览网页，电脑突然蓝屏了，然后重新启动，结果IP数量清零了（原有1500多IP），这是怎么回事？

> Jun 14 14:43:03.369 - [INFO] SSL use version:TLSv1_2
Jun 14 14:43:04.554 - [INFO] OpenSSL support alpn
Jun 14 14:43:04.730 - [INFO] load ip range file:D:\XX-Net-3.2.6\code\3.3.2\gae_proxy\local\ip_range.txt
Jun 14 14:43:04.850 - [INFO] detected Win10, enable connect concurrency control, interval:40
Jun 14 14:43:05.173 - [DEBUG] network is ok, cost:4708 ms
Jun 14 14:43:05.321 - [WARNING] line err:
Jun 14 14:43:05.321 - [INFO] load google ip_list num:0, gws num:0
Jun 14 14:43:05.589 - [INFO] OpenSSL support alpn
Jun 14 14:43:05.767 - [WARNING] no enough ip
Jun 14 14:43:05.841 - [INFO] load manual.ini success
Jun 14 14:43:05.843 - [DEBUG] ## GAEProxy set keep_running: True
Jun 14 14:43:05.844 - [INFO] ------------------------------------------------------
Jun 14 14:43:05.844 - [INFO] Python Version : 2.7.13
Jun 14 14:43:05.844 - [INFO] OS : Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Jun 14 14:43:05.844 - [INFO] Listen Address : 127.0.0.1:8087
Jun 14 14:43:05.844 - [INFO] GAE APPID : xx-net-147306|xx-net123-147306|xx-net456|xx-net1111-155502
Jun 14 14:43:05.844 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Jun 14 14:43:05.844 - [INFO] ------------------------------------------------------
Jun 14 14:43:06.279 - [WARNING] no enough ip
Jun 14 14:43:06.949 - [WARNING] no enough ip
Jun 14 14:43:07.450 - [WARNING] no enough ip
Jun 14 14:43:07.951 - [WARNING] no enough ip
Jun 14 14:43:08.452 - [WARNING] no enough ip
Jun 14 14:43:08.952 - [WARNING] no enough ip
Jun 14 14:43:09.454 - [WARNING] no enough ip
Jun 14 14:43:09.799 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Jun 14 14:43:09.868 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=482a5ad1-6f97-409e-b47e-2212beec1ca5&version=3.3.2&platform=Windows-10-10.0.15063
Jun 14 14:43:09.956 - [WARNING] no enough ip
Jun 14 14:43:10.458 - [WARNING] no enough ip
Jun 14 14:43:10.959 - [WARNING] no enough ip
Jun 14 14:43:11.460 - [WARNING] no enough ip
Jun 14 14:43:11.962 - [WARNING] no enough ip
Jun 14 14:43:12.464 - [WARNING] no enough ip
Jun 14 14:43:13.011 - [WARNING] no enough ip
Jun 14 14:43:13.512 - [WARNING] no enough ip
Jun 14 14:43:14.013 - [WARNING] no enough ip
Jun 14 14:43:14.514 - [WARNING] no enough ip
Jun 14 14:43:15.016 - [WARNING] no enough ip
Jun 14 14:43:15.517 - [WARNING] no enough ip
Jun 14 14:43:18.020 - [INFO] PAC from:127.0.0.1:1807 GET /proxy.pac
Jun 14 14:43:18.037 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('D:\\XX-Net-3.2.6\\data\\gae_proxy\\proxy.pac')
Jun 14 14:43:18.756 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Jun 14 14:43:18.779 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token
Jun 14 14:43:18.779 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token
Jun 14 14:43:18.781 - [DEBUG] GAE POST https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumAccountReconcilor,counter:0,load_time_ms:3460&json=standard
Jun 14 14:43:19.743 - [WARNING] CONNECT mtalk.google.com port:5228 not support
Jun 14 14:43:19.760 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token
Jun 14 14:43:20.421 - [DEBUG] GAE GET https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=59.0.3071.86&lang=zh-CN&x=id%3Dmgndgikekgjfcpckkfioiadnlibdjbkf%26v%3D0.0.0.0%26uc&x=id%3Daapbdbdomjkkjkaonfhkkikfgjllcleb%26v%3D2.0.6%26uc&x=id%3Dapdfllckaahabafndbhieahigkjlhalf%26v%3D14.1%26uc&x=id%3Dbfbameneiokkgbdmiekhjnmfkcnldhhm%26v%3D0.4.8%26uc&x=id%3Dcfhdojbkjhnklbpkdaibdccddilifddb%26v%3D1.13.2%26uc&x=id%3Dchphlpgkkbolifaimnlloiipkdnihall%26v%3D1.18%26uc&x=id%3Dcoobgpohoikkiipiblmjeljniedjpjpf%26v%3D0.0.0.30%26uc&x=id%3Defaidnbmnnnibpcajpcglclefindmkaj%26v%3D15.1.0.6%26uc&x=id%3Dgbkeegbaiigmenfmjfclcdgdpimamgkj%26v%3D120.2070.2076%26uc&x=id%3Dghbmnnjooekpmoecnnnilnnbdlolhkhi%26v%3D1.4%26uc&x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D8.9.8.8%26uc&x=id%3Dgjldcdngmdknpinoemndlidpcabkggco%26v%3D6.0.2%26uc&x=id%3Dgmbmikajjgmnabiglmofipeabaddhgne%26v%3D2.1.1%26uc&x=id%3Dgmlllbghnfkpflemihljekbapjopfjik%26v%3D2.2016.128.11729%26uc&x=id%3Dgojbdfnpnhogfdgjbigejoaolejmgdhk%26v%3D3.7.4%26uc&x=id%3Dhbocinidadgpnbcamhjgfbgiebhpnmfj%26v%3D0.5.8%26uc&x=id%3Dhdokiejnpimakedhajhdlcegeplioahd%26v%3D4.1.52.100%26uc&x=id%3Dhoklmmgfnpapgjgcpechhaamimifchmp%26v%3D4.3.5%26uc&x=id%3Diiooodelglhkcpgbajoejffhijaclcdg%26v%3D1.0.9%26uc&x=id%3Dimilbobhamcfahccagbncamhpnbkaenm%26v%3D0.6.2%26uc&x=id%3Djnimonidkipnhnpgkhgliocfnnpgkhek%26v%3D1.3%26uc&x=id%3Dkbfnbcaeplbcioakkpcpgfkobkghlhen%26v%3D14.768.968%26uc&x=id%3Dkfimphpokifbjgmjflanmfeppcjimgah%26v%3D3.2.1%26uc&x=id%3Dlapoiohkeidniicbalnfmakkbnpejgbi%26v%3D1.0.1%26uc&x=id%3Dlkfkkhfhhdkiemehlpkgjeojomhpccnh%26v%3D2.7.1%26uc&x=id%3Dlneaknkopdijkpnocmklfnjbeapigfbh%26v%3D5.4.1%26uc&x=id%3Dmcbpblocgmgfnpjjppndjkmgjaogfceg%26v%3D0.98.92.2%26uc&x=id%3Dmciiogijehkdemklbdcbfkefimifhecn%26v%3D0.9.3%26uc&x=id%3Dmlpapfcfoakknnhkfpencomejbcecdfp%26v%3D0.1.6%26uc&x=id%3Dndnaehgpjlnokgebbaldlmgkapkpjkkb%26v%3D2.17.0%26uc&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D1.0.0.2%26uc
Jun 14 14:43:26.086 - [INFO] PAC from:127.0.0.1:1807 GET /proxy.pac
Jun 14 14:43:26.115 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('D:\\XX-Net-3.2.6\\data\\gae_proxy\\proxy.pac')
Jun 14 14:43:26.164 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Jun 14 14:43:28.567 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Jun 14 14:43:28.837 - [DEBUG] GET http://www.twitter.com/xxnet
Jun 14 14:43:29.390 - [DEBUG] GAE GET https://clients2.google.com/service/update2/crx?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D8.9.8.8%26uc&_=1497422609356
Jun 14 14:43:31.957 - [DEBUG] GAE GET https://www.google-analytics.com/r/__utm.gif?utmwv=5.6.7&utms=3&utmn=282901704&utmhn=chphlpgkkbolifaimnlloiipkdnihall&utmcs=UTF-8&utmsr=1366x768&utmsc=24-bit&utmul=zh-cn&utmje=0&utmfl=-&utmhid=1525568851&utmr=-&utmp=%2F_generated_background_page.html&utmht=1497422611465&utmac=UA-38573374-2&utmcc=__utma%3D140524640.941183787.1469973251.1497361356.1497421294.528%3B%2B__utmz%3D140524640.1469973251.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B&utmjid=301385684&utmredir=1&utmu=qAAAAAAAAAAAAAAAAAAAAAAE~
Jun 14 14:43:35.299 - [DEBUG] GAE POST https://www.googleapis.com/oauth2/v4/token
Jun 14 14:43:36.784 - [DEBUG] GAE GET https://www.google-analytics.com/r/__utm.gif?utmwv=5.6.7&utms=3&utmn=1599501225&utmhn=mciiogijehkdemklbdcbfkefimifhecn&utmcs=windows-1252&utmsr=1366x768&utmsc=24-bit&utmul=zh-cn&utmje=0&utmfl=-&utmdt=Chrono%20Download%20Manager&utmhid=328002057&utmr=-&utmp=%2Fbg%2Fbg.htm&utmht=1497422616749&utmac=UA-32450437-3&utmcc=__utma%3D84298501.1271552223.1496331728.1497344565.1497421300.20%3B%2B__utmz%3D84298501.1496331728.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B&utmjid=1029308136&utmredir=1&utmu=qAAAAAAAAAAAAAAAAAAAAAAE~
Jun 14 14:43:36.930 - [DEBUG] GAE GET https://www.google-analytics.com/__utm.gif?utmwv=5.6.7&utms=4&utmn=1014536192&utmhn=chphlpgkkbolifaimnlloiipkdnihall&utmcs=windows-1252&utmsr=1366x768&utmvp=1366x700&utmsc=24-bit&utmul=zh-cn&utmje=0&utmfl=-&utmdt=OneTab&utmhid=348774995&utmr=-&utmp=%2Fonetab.html&utmht=1497422616207&utmac=UA-38573374-2&utmcc=__utma%3D140524640.941183787.1469973251.1497361356.1497421294.528%3B%2B__utmz%3D140524640.1469973251.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B&utmjid=&utmu=qAAAAAAAAAAAAAAAAAAAAAAE~

> XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
xxnet-version: 3.3.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:9 good:6
network-status: OK
connected-link: new:0 used:0
worker: h1:5 h2:1
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by jzp820927** [comment]
估计是程序的 bug 吧，等他重新扫描就行了，影响不大。

**Comment by wangyunlg** [comment]
@jzp820927 就是要扫描好久了，好后悔没备份啊。

**Comment by jzp820927** [comment]
如果你电脑经常无故重启，建议定时备份。不过我觉得电脑莫名重启的概率还是很低的，除非是 系统有问题
