### ISSUE TITLE
我有5个Google APPID  倒是IP数量少 求解决

### ISSUE THREAD

**Issue by DenonLH** [XX-net/XX-Net#5709]
![xs_xag68 2 xta 54l5qae](https://user-images.githubusercontent.com/25523603/27127047-209a0d2c-512c-11e7-8fc5-10a1d870dfde.png)

**Comment by jzp820927** [comment]
让他多扫描一些时间

**Comment by 13130110047** [comment]
请问怎么多扫描一会儿？

**Comment by jzp820927** [comment]
就是开着不管他，他就一直扫描，你这个是没有可用的 IP。

**Comment by DenonLH** [comment]
@jzp820927 我在问你一下  现在用XX-Net 进YouTube 一直显示504连接超时  我试试我多次都是这样


![cy4dfym0kk5j _ u3m1ex](https://user-images.githubusercontent.com/25523603/27142861-feb74822-515e-11e7-8645-265c6f28ab87.jpg)

**Comment by jzp820927** [comment]
试试这样看行不行
改 data/gae_proxy/manual.ini 文件
[hosts]
.youtube.com = gae
不要用记事本改，尽量用 notepad++ 之类的改

**Comment by DenonLH** [comment]
没有看见这个文件 manual.ini

![mr1 8pre kg3q80i_3tl jn](https://user-images.githubusercontent.com/25523603/27144026-f5dd670a-5162-11e7-8074-feb71e3dd543.jpg)

**Comment by DenonLH** [comment]
@jzp820927 没有看到这个文件manual.ini
![mr1 8pre kg3q80i_3tl jn](https://user-images.githubusercontent.com/25523603/27144075-206c3776-5163-11e7-88be-89b774dd8ec7.jpg)

**Comment by jzp820927** [comment]
默认没有，手动新建，有条件的话，建议用 notepad++ 新建这个文件，最好不要用记事本

**Comment by DenonLH** [comment]
@jzp820927   还是不行

**Comment by jzp820927** [comment]
浏览器显示什么？

**Comment by DenonLH** [comment]
@jzp820927 跟我上面发的一样  连接超时

**Comment by DenonLH** [comment]
@jzp820927 我刚把电脑重启动了  现在好了 谢谢了

**Comment by DenonLH** [comment]
@jzp820927 我刚把电脑重启动了  现在好了 谢谢了

**Comment by jzp820927** [comment]
我去，重启下就好了？太奇葩了

**Comment by DenonLH** [comment]
嗯  我那那个完以后软件重启没用  电脑重启就好了  哎  我也很无语啊！！！！

**Comment by DenonLH** [comment]
我把那个文件改完以后 把软件重启没用   我又把电脑重启了 就好了

**Comment by pengweipro** [comment]
之前长时间挂着，IP是满的。这些天抽风了一样。。。

**Comment by jzp820927** [comment]
IP 没啥影响，主要是 ytb 直连被封了

**Comment by DenonLH** [comment]
太多奇葩问题  哎

**Comment by jzp820927** [comment]
只要解决了就行，每个人有不同的系统和网络环境。这个没办法。

**Comment by DenonLH** [comment]
是啊

**Comment by DenonLH** [comment]
我用代理谷歌的标签页还是打不开，不知道为啥，最后就显示 无法显示此网页

**Comment by jzp820927** [comment]
谷歌的标签页 是指什么？ google 网页呢？https://www.google.com/ncr 呢？

**Comment by DenonLH** [comment]
![qq 20170615230113](https://user-images.githubusercontent.com/25523603/27187792-b06b153e-521e-11e7-9ed4-4826ef425300.jpg) 点这个

![oue6p 91dtaobi 5vkvm_r](https://user-images.githubusercontent.com/25523603/27187876-f23127e2-521e-11e7-9f50-ced29bab0960.png)
点完就显示这个

**Comment by candy2107** [comment]
@DenonLH 
https://chrome.google.com/webstore/detail/nocountryredirect-ncr/ciboebddidackjicoeoiigdnbmchkdll?hl=en

**Comment by jzp820927** [comment]
LS 正解
