### ISSUE TITLE
这几个网站也上不去，是不是被google给屏蔽了？

### ISSUE THREAD

**Issue by RouRouChina** [XX-net/XX-Net#5710]
[hosts]
.youtube.com = gae
.avso.pw = gae
.avio.pw = gae
.avxo.pw = gae

这几个网站也上不去了，我加了gae也不行，youtube弄好了，这几个是不是被google给屏蔽了？

Jun 14 19:05:59.420 - [INFO] GAE CONNECT clients4.google.com:443
Jun 14 19:05:59.431 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/dev/command/?client=Chromium&client_id=ap6lFM6QuXaUfqqe2bQHXQ%3D%3D
Jun 14 19:05:59.432 - [DEBUG] host_conn_pool clients4.google.com get:43.245.144.249 handshake:233
Jun 14 19:05:59.665 - [INFO] DIRECT chucked t:233 s:432 200 clients4.google.com /chrome-sync/dev/command/?client=Chromium&client_id=ap6lFM6QuXaUfqqe2bQHXQ%3D%3D
Jun 14 19:06:00.332 - [INFO] scan_ip add ip:195.80.179.154 time:555
Jun 14 19:06:00.340 - [INFO] remove_slowest_ip:110.164.9.86 handshake_time:326, fails:1
Jun 14 19:06:03.257 - [INFO] scan_ip add ip:187.19.145.118 time:1026
Jun 14 19:06:03.262 - [INFO] remove_slowest_ip:118.107.75.154 handshake_time:326, fails:1
Jun 14 19:06:04.918 - [INFO] scan_ip add ip:200.149.119.57 time:884
Jun 14 19:06:04.932 - [INFO] remove_slowest_ip:58.123.102.244 handshake_time:326, fails:1
Jun 14 19:06:05.381 - [DEBUG] GAE GET https://avso.pw/cn
Jun 14 19:06:05.763 - [INFO] GAE t:381 s:0 GET https://avso.pw/cn get_response:381
Jun 14 19:06:09.062 - [DEBUG] GAE GET https://avio.pw/
Jun 14 19:06:09.826 - [INFO] GAE t:763 s:0 GET https://avio.pw/ get_response:762
Jun 14 19:06:10.019 - [DEBUG] 113.171.247.57 keep alive fail, inactive_time:571 head_timeout:21
Jun 14 19:06:10.019 - [DEBUG] report_connect_fail:113.171.247.57
Jun 14 19:06:15.588 - [DEBUG] 113.171.247.57 worker close:keep alive
Jun 14 19:06:16.236 - [INFO] scan_ip add ip:188.21.9.92 time:917
Jun 14 19:06:16.252 - [INFO] remove_slowest_ip:223.62.225.42 handshake_time:326, fails:1
Jun 14 19:06:16.782 - [INFO] GAE CONNECT clients4.google.com:443
Jun 14 19:06:16.798 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-

**Comment by DenonLH** [comment]
你是不是改过hosts文件  如果改过把hosts删了  用XX-Net代理

**Comment by RouRouChina** [comment]
我现在加不加hosts都上不去，你能上去那几个网站吗？用XX-NET

**Comment by jzp820927** [comment]
可以 https 直连访问。如果有污染就 + hosts，没必要走代理。

**Comment by 13130110047** [comment]
请问你是怎么弄好youtube的？我昨天今天一直打不开youtube，报错504 time out

**Comment by jzp820927** [comment]
@13130110047 试试这样看行不行
改 data/gae_proxy/manual.ini 文件
[hosts]
.youtube.com = gae
不要用记事本改，尽量用 notepad++ 之类的改

**Comment by oliyiyi** [comment]
@jzp820927 

> @13130110047 试试这样看行不行
改 data/gae_proxy/manual.ini 文件
[hosts]
.youtube.com = gae
——————————————————————————————
没有这个文件啊，我用的是3.3.1

**Comment by jzp820927** [comment]
自己手动新建这个文件

**Comment by whhxmwhh** [comment]
估计很多网站都受到影响了。
估计网络协议发生了重大变化？或者以色列的软件专家啊在做实验吗？

**Comment by jzp820927** [comment]
@whhxmwhh 我这边一切正常，应该还是配置和环境问题吧
