### ISSUE TITLE
Youtube 上不了了

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#5713]
版本 3.3.1
系统 win7
上google等网站没问题。上youtube时显示“连接超时，先休息一会再来！”

 诊断信息：

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3001 good:2973
network-status: OK
connected-link: new:3 used:0
worker: h1:8 h2:18
scan-ip-thread-num: 50
ip-quality: 106
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by oliyiyi** [comment]
我的也一样

**Comment by jzp820927** [comment]
试试这样看行不行
改 data/gae_proxy/manual.ini 文件
[hosts]
.youtube.com = gae

**Comment by farshidvahid** [comment]
@jzp820927 感谢！可以登录了，也没出现乱码。

**Comment by jzp820927** [comment]
最新版 chrome 都没有乱码

**Comment by rocke** [comment]
@jzp820927  我的XX3.3.1  data/gae_proxy/ 文件下面，没有 manual.ini 文件

**Comment by jzp820927** [comment]
@rocke 自己手动新建文件

**Comment by farshidvahid** [comment]
@rocke 新建 文本文档，再改后缀就行了。
