### ISSUE TITLE
chrome59,xx-net3.31访问google域站点证书报错

### ISSUE THREAD

**Issue by mymixing** [XX-net/XX-Net#5717]
您的连接不是私密连接

攻击者可能会试图从www.google.com.hk窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_AUTHORITY_INVALID
Subject: www.google.com.hk
Issuer: GoAgent
Expires on: 2026年9月21日
Current date: 2017年6月15日
PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIDazCCAlOgAwIBAgIRAIVwzfiBICnE+DMe1na4HkcwDQYJKoZIhvcNAQELBQAw
ZzELMAkGA1UEBhMCQ04xETAPBgNVBAgMCEludGVybmV0MQ8wDQYDVQQHDAZDZXJu
ZXQxEDAOBgNVBAoMB0dvQWdlbnQxEDAOBgNVBAsMB0dvQWdlbnQxEDAOBgNVBAMM
B0dvQWdlbnQwHhcNMTYwOTIxMDczMDQ5WhcNMjYwOTIxMDc0MDQ5WjB7MQswCQYD
VQQGEwJDTjERMA8GA1UECAwISW50ZXJuZXQxDzANBgNVBAcMBkNlcm5ldDEQMA4G
A1UECwwHR29BZ2VudDEaMBgGA1UEAwwRd3d3Lmdvb2dsZS5jb20uaGsxGjAYBgNV
BAoMEXd3dy5nb29nbGUuY29tLmhrMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAwtYxBtWZX1f+VHOPLrw1psScEBY9ubtvuuoU2M6jbjp4HSttp36va1Cm
o4rDpjzEcnqEo64c7xcyaoZzxV/RgNxL81nUuGZbwxwd8czZLzK1ANTUslyrJTGx
M0rO5knkgrz8k03SrAWWMRCgvSNvf0/ma1aZs0uPIVph7X1GgbCzMBonMntOGG5R
zB6NB1osUk9QoEE9q0Zlyli+xyLgg8mVZQYs36WGcguDY3F4GwmWR9Izj8cWKK8x
jAteHF9DOmWFY31++SYsN0Mz9x+8NTO+6a8X69r9xa2wuggtwItrygH6rFcSEAKt
DgyHl0kwMrOWXyJEyJEpXjZ0AEhP3wIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAF
18J2gRGC3UsUefP55Qrr/cQ3+8SnIi5fM1HdBJIg30BpIUMMyQB9MMUybXqManue
ohxG2oyCFZIT/sugpNzULb39tVeLx3KTdT7PmSkL14gN52ycP7yC//7lHaQ6gRwO
qJkOvEyYXtpr+wkF5l1zYCLPvSc06/4nj2Mmy1FKjk7GdpwMhra3VD2VIC3io7fY
7trNdYbKJY1HhAQkBno5U4yUksOe5+WfyhrCoBQrgV82sKto1U32+k6jXmRxr4Zs
GSGReYS45f2xK34u33WxTH/ufSCbYeONwLvrOOomcmZ1m7im6gG2EMWF6AvnqkCx
1C4aHi3UYChFcODMKg/s
-----END CERTIFICATE-----
 
请问这个能解决吗,貌似chrome完全不让使用自签名的证书了.

**Comment by jzp820927** [comment]
#5322

**Comment by mymixing** [comment]
@jzp820927 请问有chrome59正常的案例吗?
我的XXNET是3.3.1的,要下3.3.4(测试版)?

**Comment by jzp820927** [comment]
我的 金丝雀版 chrome 是 61 版本，没有任何问题。这个算案例麽？
XXNET 最新版是 3.3.4 ，对的，没问题

**Comment by mymixing** [comment]
唉~我这还是不行~

**Comment by mymixing** [comment]
@jzp820927 唉,我这还是不行,改成3.3.4甚至连http://127.0.0.1:8085/都打不开了.

**Comment by jzp820927** [comment]
访问 8085 的时候，不要开 代理

**Comment by mymixing** [comment]
哦,这应该算个bug,退出进程后,之前控制台的python还在,端口被占用着,新的webserver起不来.
不过8085是打开了,但还是一样的,
浏览器代理设置	Fail
CA证书状态(下载)	Fail
换成3.3.4一样不好使.

**Comment by mymixing** [comment]
呃,突然好使了..
不知道操作了什么,感觉试着访问了下facebook
然后就变成..

浏览器代理设置	OK
CA证书状态(下载)	OK

**Comment by jzp820927** [comment]
意思是，没问题了？
