### ISSUE TITLE
改 .youtube.com = gae 导致 Firefox 乱码的解决方法

### ISSUE THREAD

**Issue by candy2107** [XX-net/XX-Net#5720]
https://portableapps.com/apps/internet/firefox-portable-esr
选简体中文版下载
这个是火狐最新便携版
然后安装代理插件,后面的都会了吧

**Comment by wenliyang** [comment]
这次出得真快，这个站有时放出便携版会晚好几天

另，装官方中文版也行，不要用中国版

**Comment by warmd** [comment]
45.9 ESR ，因安装很多插件、工具及配置，有重装外的其他方法吗？

**Comment by jzp820927** [comment]
意思是说，除了中国版的会乱码，其他都没问题？

**Comment by wenliyang** [comment]
@jzp820927 不是说中国版的会乱码，是中国版的自带一堆中国特色垃圾扩展，喜欢用火狐的都不会碰它的
@warmd ESR不是一样可以升级么，52.2.0，顶楼那网站也有

**Comment by jzp820927** [comment]
好吧，我不用 FF，你们慢慢讨论，我就不参与了。

**Comment by shipbk** [comment]
亲测可行，感谢楼主

**Comment by candy2107** [comment]
@ximenlangzige 请使用
