### ISSUE TITLE
与periscope聊天室握手失败

### ISSUE THREAD

**Issue by PatrickWesley2333** [XX-net/XX-Net#5722]
![default](https://user-images.githubusercontent.com/26796537/27178394-9e0d4dfc-51fc-11e7-930f-e694589da12a.JPG)
按钮指向链接如下
'wss://prod-chatman-ancillary-eu-central-1.pscp.tv/chatapi/v1/chatnow'
我想问一下如何单独添加代理

**Comment by SeaHOH** [comment]
你是想 WebSocket 走其它代理？XX-Net 本身不支持分离单个域名的部分流量走其它通道。
如果只有 WebSocket 使用这个域名，直接设置根据域名选择代理，很多代理调度插件或软件都支持；
否则，需要使用支持网址匹配的代理调度插件或软件，好像 pac 也可以，但是变更设置比较麻烦。

**Comment by jzp820927** [comment]
经测试，可以直连

**Comment by PatrickWesley2333** [comment]
@jzp820927 如果给#wss://prod-chatman-ancillary-eu-central-1.pscp.tv/chatapi/v1/chatnow设置直连的话这个应该怎么填写（见图），因为*.pscp.tv被污染了，所以需要单独设置直连
![default](https://user-images.githubusercontent.com/26796537/27194460-2eea984c-5235-11e7-8ced-9b4fc2cc3ac7.JPG)
ps：之前应该是xx-net2.8.8stable时，不会出现这个问题

**Comment by SeaHOH** [comment]
星号 * 就是通配符。

**Comment by jzp820927** [comment]
@PatrickWesley2333 针对污染问题，最简单的办法就是修改 hosts ，用 DNS 也行
你可以在 hosts 中增加 *.pscp.tv 相关的域名对应到正确的 IP 地址就行了。
