### ISSUE TITLE
运行start.vbs无法打开XX-NET，大神解答下！

### ISSUE THREAD

**Issue by simonliyu** [XX-net/XX-Net#5723]
运行start.vbs无法打开XX-NET，运行后无反应，不会弹出管理员权限请求！运行它时还需要撘什么环境吗？大神 大神解答下！小弟愚昧！

**Comment by simonliyu** [comment]
bat可以

**Comment by DenonLH** [comment]
就是 点start.bat

**Comment by jzp820927** [comment]
bat 可以，就用 bat 呗，没啥区别

**Comment by simonliyu** [comment]
谢谢大家！现在已经搞清楚了，是因为没有获得系统权限，通过@Wows233的方法可以获得最高权限运行，完美解决问题！还能开机自启！哈哈！如果有遇到同样问题的请查阅 #5463 https://github.com/XX-net/XX-Net/issues/5463（在评论里）
