### ISSUE TITLE
xx-net完全失效了，紧急情况！！！！！

### ISSUE THREAD

**Issue by AndyLau2017** [XX-net/XX-Net#5730]
![xxxxxxxxxxxxxxxxxxxxx](https://user-images.githubusercontent.com/29122546/27220947-6dc1c6ba-52b9-11e7-8d02-d77c3673d4cc.jpg)

SS没问题，gop也没问题，就是xx有问题，chrome是59版本64位，xx是3.3.1，有人知道哪里出问题了么？

**Comment by SeaHOH** [comment]
3.3.4

**Comment by myjlpt** [comment]
你自己出问题了。 我这边3.3.1 正常着呢
XX-Net 3.3.1，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	3864
空闲	0
IP延迟	167
连接池(帮助)	新:2 h1:18 h2:3
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	42
屏蔽状态(帮助)	OK

**Comment by myjlpt** [comment]
你自己出问题了。 我这边3.3.1 正常着呢
XX-Net 3.3.1，一切正常，你可以访问真正的互联网了。
状态

属性	值
本地网络状态	OK
IP数量	3864
空闲	0
IP延迟	167
连接池(帮助)	新:2 h1:18 h2:3
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	42
屏蔽状态(帮助)	OK

**Comment by AndyLau2017** [comment]
@myjlpt 你是用Chrome 59 吗？

**Comment by AndyLau2017** [comment]
@SeaHOH 大佬，3.3.4有稳定版吗？另外，我的ip显示有1000多个，但是提示尚未连接，是ip全部死亡了吗

**Comment by myjlpt** [comment]
@AndyLau2017  ,用的第三方 cent 的。 看了一下是58.0.3029.110的核

**Comment by SeaHOH** [comment]
据我所知，3.3.4 比 3.3.1 只好不坏。

不看这个状态，关键是能用吗？

**Comment by AndyLau2017** [comment]
@SeaHOH  我昨天把chrome更新到59，然后今天早上就开始发现xx-net 3.3.1开始有问题了，
![2345 20170616163248](https://user-images.githubusercontent.com/29122546/27222081-8586977c-52bd-11e7-9155-cca8554c3ed8.jpg)

本地网络状态，由unknown到ok，一直在转换，但是能正常上网。然后到了下午，就彻底显示尚未建立连接了。

**Comment by AndyLau2017** [comment]
@SeaHOH  日志就一直显示连接失败
Jun 16 17:36:25.396 - [DEBUG] report_connect_fail network fail
Jun 16 17:36:25.396 - [DEBUG] get ip:119.149.188.97 t:131
Jun 16 17:36:25.405 - [DEBUG] 58.27.27.243 fail:timeout('timed out',)
Jun 16 17:36:25.405 - [DEBUG] report_connect_fail network fail
Jun 16 17:36:25.405 - [DEBUG] get ip:203.66.124.167 t:134
Jun 16 17:36:25.896 - [DEBUG] 112.72.5.112 fail:timeout('timed out',)

**Comment by SeaHOH** [comment]
升级 3.3.4

**Comment by AndyLau2017** [comment]
@SeaHOH 感觉最近的gfw越来越给力了，刚检查了一下ip，1000多个就30个不到可用的，又要死一大片了

**Comment by taocunguijs** [comment]
这个bug 3.3.4完美修复

**Comment by AndyLau2017** [comment]
感谢大佬们赐教，赶紧升级升级

**Comment by pengweipro** [comment]
???
我一直以为xx限制了最大IP数是3000，到了3000就不再涨了，
@myjlpt 你的竟然超过了。。。

**Comment by myjlpt** [comment]
@pengweipro 自定义呀！ 
max_good_ip_num = 10000

**Comment by zaihaib** [comment]
也是遇到了这个问题，升级了3.3.4就好了

**Comment by zhencaihao** [comment]
我也是3.3.1版的，谷歌浏览器59.0.3071.104。刚才打开也显示你这个情况，但是等一会就显示“一切正常，可以访问互联网了。”

**Comment by 80068** [comment]
刚升级了。还是没有什么效果，依然是无法访问，看来这次问题比较拗严重

**Comment by 80068** [comment]
![screenhunter_01 jun 16 22 05](https://user-images.githubusercontent.com/19446969/27229909-fbcb01f8-52df-11e7-96d3-e61be69cff3d.png)
升级后。问题还是存在。依然只能断断续续访问谷歌国际网站 www.googlge.com/ncr

**Comment by AndyLau2017** [comment]
GFW开始大杀四方了，会不会是和某些人安装的国产软件有关？不然不可能一下子死掉那么多ip

**Comment by taocunguijs** [comment]
我用的linux今天xx-net也跪了

**Comment by jzp820927** [comment]
XXNET 现在的扫描策略确实不太适应现在的网络状况了，而且 XXNET 的核心已经很久没开发了，所以。。。。遇到没有 IP 的情况，就删除 IP 数据，让他重新扫描所有 IP

**Comment by jzp820927** [comment]
实在扫不出 IP ，就试试 https://github.com/out0fmemory/GoAgent-Always-Available/ 吧，这个是别人维护的，筛选出来的高质量 IP

**Comment by AndyLau2017** [comment]
迟早大家一起死，这ip被封杀的太快了，究竟是什么原因呢？@jzp820927 那位兄台维护的，大佬低调传播啊，别搞得他维护的也死光光了，另外，肯定有GFW在这论坛里

**Comment by jzp820927** [comment]
在我之前，这个早就被别人转了N 次了，issues 搜一下就知道了。我不是第一个，应该也不是最后一个。只是顺带贴一下。

**Comment by AndyLau2017** [comment]
@jzp820927  大佬，问下，为什么我用VPN扫出来的ip不可用呢，一导入到xx中，检查ip，就全部失效了

**Comment by jzp820927** [comment]
你开着 VPN 的环境，就是没有墙的环境，也就是说，你开着 VPN扫，就相当于在没有墙的环境下扫。
你又拿到有墙的环境下用，肯定不能用撒。
相对于，你在国外找到的 IP，拿到国内来用，你说能不能用。

**Comment by AndyLau2017** [comment]
@jzp820927 也对。还有问下，那些扫出来的非谷歌证书的ip，可以用，应该就是所谓的GGC吧，用这些会有安全问题吗

**Comment by jzp820927** [comment]
非谷歌证书的 IP？有具体的 IP 我看看，不太情况，你指的 非 谷歌证书的 IP，具体是什么 IP，我用的都是 google 的正规 IP。没碰到过你说的这种 IP

**Comment by AndyLau2017** [comment]
![dfsfewtwtwetwet](https://user-images.githubusercontent.com/29122546/27253114-d83985d6-53a0-11e7-856e-6f63cf5376eb.jpg)

就是这种啊，好像可以使用，但是用不了多久就出错，不知道什么问题

**Comment by jzp820927** [comment]
这明显不是 google 的 IP，这是 akamai 的 IP，不太可能能用于 google。你是不是弄错了？
你是怎么用的？hosts？还是用作 XXNET 上？

**Comment by AndyLau2017** [comment]
@jzp820927  我是用台湾的ip段搜索出来的啊，难道这些不可以用吗？我用在gp上能用一会儿，接着就不行了。

**Comment by jzp820927** [comment]
你具体是用的上图中的哪个 IP？是只放了这一个 IP ？还是放了一堆？

**Comment by AndyLau2017** [comment]
@jzp820927 一堆放上去的，能跑一会，接着就报错。奇怪

**Comment by jzp820927** [comment]
那你放的一堆就不奇怪了，这个段是有 google IP 的，但是你上面那个3个是肯定用不到的，他不是 google 的 IP，至于用一下就失效了，可能就是这段干扰比较厉害，完全没有可用性了。只能换 IP 了。

**Comment by AndyLau2017** [comment]
@jzp820927  恩，还有一个问题很奇怪，为什么我和别人同样的用MFF扫always-goagent的那一堆ip，他能扫到50多个可用，而我这只有3个可用？

**Comment by jzp820927** [comment]
不同的 ISP，不同的地域，封锁程度都不一样，如果是一个地方的，一个 ISP 才有可比性。

**Comment by AndyLau2017** [comment]
@jzp820927  嗯，看来我处在最严重的地区。。。

**Comment by jzp820927** [comment]
电信封锁最厉害，还有地域不同封锁程度也不一样。不过移动普遍比较好，有条件可以考虑换移动
