### ISSUE TITLE
XX-net 3.3.1和3.3.4目前都无法使用，请求增援

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#5736]
![screenhunter_02 jun 16 22 11](https://user-images.githubusercontent.com/19446969/27230193-01bf8470-52e1-11e7-89a7-e322912ed0f0.png)

刚使用的是3.3.1但是出现时断时续的状况。看看论坛说升级可以解决问题，但是刚刚升级后发现升级也是无法访问Google.com/ncr的国际网站。这次问题比往回好想要严重，请求技术部帮忙解决，十分感谢！！

**Comment by Tiande** [comment]
应该和这次 Youtube 被攻击有关。

**Comment by taocunguijs** [comment]
我的可用ip从好几千到了个位数

**Comment by kevinweiqy** [comment]
@Tiande Youtube被攻击了？咋回事呀？

**Comment by jzp820927** [comment]
如果是才运行的，就等同多运行点时间，如果是运行很久了，就删除 data，让他全部重新扫描。

**Comment by 80068** [comment]
@jzp820927 在你的指点下，目前软件已经恢复（正在慢慢恢复中），谢谢！！！好人万岁！

**Comment by jzp820927** [comment]
只能这样了，这是长期战。
