### ISSUE TITLE
购买了$ 4.5的套餐，半个小时还没显示到账

### ISSUE THREAD

**Issue by huanhulan** [XX-net/XX-Net#5737]
如题。。

**Comment by DenonLH** [comment]
有延迟  等等把

**Comment by Jan9th** [comment]
估计没有配置自动发货的设置，多等些时间或者直接给开发者发送邮件 email： xxnet.dev@gmail.com ，问题关了吧。

**Comment by jzp820927** [comment]
购买流量分2不，先充值，再买套餐
确认购买成功后，退出账号，再登录账号，才能看到流量。
