### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by Seselin** [XX-net/XX-Net#5742]
公司电脑 win7通过 #5322 已解决

自己电脑 win10 试了好几次不行，xx-net删了旧的，重下也不行。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:12 good:4
network-status: OK
connected-link: new:1 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 50
ip-quality: 1487
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Seselin** [comment]
访问谷歌显示 **您的连接不是私密连接**

**Comment by jzp820927** [comment]
把 chrome 卸载了，重装

**Comment by DSKing377** [comment]
我有这个提示，但是使用正常。删了证书重新运行还是这样。

**Comment by zhangtianxiang** [comment]
一开始我是**尚未建立连接**，不能翻墙，之后升级到**3.3.4**，显示**请检查浏览器代理设置**，看了楼上发言后发现自己也是虽然有这个提示，但是能用了。

**Comment by Seselin** [comment]
重新导入证书解决了 [参考](http://blog.csdn.net/blueheart20/article/details/41729455])

**Comment by jzp820927** [comment]
能用，状态显示异常的，只需要 ctrl+F5 就可以了。
