### ISSUE TITLE
最近ip封得比较厉害，这里提供两方案。其实ip从来不是问题

### ISSUE THREAD

**Issue by yeahwu** [XX-net/XX-Net#5746]
首先 @Rongronggg9 的超大ip库
https://github.com/Rongronggg9/Google-IP-Range

还有 @xyuanmu 兄的dig神器
https://github.com/xyuanmu/dig

再有流行的hosts项目
https://github.com/racaljk/hosts

大家慢慢琢磨吧！
然后前几天好像看到issues里有人问，xx-net里的ip从哪里找的？

另，再分享一个免费代理方案大家救急用
神器 gogotunnel（二狗）  https://www.gogotunnel.com/

**Comment by wangyunlg** [comment]
非常感谢

**Comment by AndyLau2017** [comment]
Y大佬现身啊，但是有个问题，就是把可用的ip导进去后，数量依旧会不断变少，感觉是随时在封的样子

**Comment by AndyLau2017** [comment]
扫描及翻墙时关闭国产杀毒软件/安全软件，特别是 360 全系软件，此类软件可能会自动上报 IP 地址到 GFW，导致可用 IP 减少。
不要使用国产浏览器翻墙，理由同上，否则再大的 IP 库都救不了你。╭(╯^╰)╮

**Comment by AndyLau2017** [comment]
大家要低调，低调，另外，都卸载了国产软件，不然大家一起死

**Comment by moketing** [comment]
事件影响

**Comment by malthae** [comment]
> 事件影响

最近有什么大事件

**Comment by jzp820927** [comment]
赶脚要彻底解决问题，还是得改善一下扫描策略才行。

**Comment by candy2107** [comment]
@yeahwu 
已更新ip扫描库,建议合并

**Comment by AndyLau2017** [comment]
@candy2107 没卵用，一样扫不出来

**Comment by jzp820927** [comment]
看样子，电信网是没戏了？移动的应该没事

**Comment by candy2107** [comment]
@AndyLau2017 
这ip库较新,扫描正常
扫描出来之后失效,那是别的问题了

**Comment by jzp820927** [comment]
ISP 的关系还是挺大

**Comment by wangyunlg** [comment]
联通的感觉还行，差不多在800左右浮动，前几天一直是3000

**Comment by myjlpt** [comment]
个人觉着SSR零时代替就好 ，提供免费流量的很多的。

我这边提供一个，注册可获得100G流量应该够了吧
http://www.51out.tk

**Comment by CHN008** [comment]
我用这个项目shadowsocks-over-websocket
https://github.com/VincentChanX/shadowsocks-over-websocket 

免费使用 Heroku 部署 shadowsocks,弄好了没有Config Vars 设置项,有用过的朋友知道怎么弄不?

**Comment by jzp820927** [comment]
heroku 有很多其他方案，而且 这种部署方式，好像不兼容普通的 SS 客户端。

**Comment by AndyLau2017** [comment]
@CHN008 相关的问题，到相关的地方去问啊，跑这干嘛

**Comment by StarShield** [comment]
thanks

**Comment by malthae** [comment]
今天扫出来很多IP 应该是复活了

**Comment by yeahwu** [comment]
不要慌，这种事见得多了。一年总有那么几次，年年都会有人说，完了，完了，gae完了！到现在不也没死透嘛。
gae本来就是少数人的玩具，在XX-Net身上得以普及到小白用户。
最坏的结果是，再次沦落到少数人的玩具。
这都不叫个事……
malthae <notifications@github.com>于2017年6月18日 周日10:56写道：

**Comment by yeahwu** [comment]
另，再有个建议。可以去试试XX-Mini，v1.2.6版，俺只能帮你们到这了。
yeah wu <wujiayu02@gmail.com>于2017年6月18日 周日11:04写道：

**Comment by wpp214** [comment]
@myjlpt  试了一把 额 一直没收到邮件

**Comment by GitKKg** [comment]
谢谢楼主，large ip到今天已解决问题，youtube，google访问正常

**Comment by candy2107** [comment]
@yeahwu 
还有 goagent-always-available

**Comment by yeahwu** [comment]
好的，你提交的IP段明天看看，星期天不干活，😄
candy <notifications@github.com>于2017年6月18日 周日12:17写道：

**Comment by myjlpt** [comment]
@wpp214 垃圾箱呢？ gmail的邮箱应该可以收到的

**Comment by AndyLau2017** [comment]
我觉得你们这些口口声声说已解决问题的，最好补上自己的isp，还有xx版本，浏览器版本。而不是在这以偏概全。

**Comment by jzp820927** [comment]
只能静观其变了，现在确实是少数人的玩具了，不知道以后是什么情况

**Comment by AndyLau2017** [comment]
@jzp820927  墙(强)国人的悲哀啊.......

**Comment by jzp820927** [comment]
要学会适应生活

**Comment by trystudy** [comment]
学会被强奸

**Comment by xyuanmu** [comment]
感觉像是定向封锁xx-net的流量，checkgoogleip扫出的ip放到xx-net不能连上，原因不明，提示：换一个工具

**Comment by candy2107** [comment]
@xyuanmu
目前xxnet原来的ip库在我这里完全扫不到ip , 怀疑是对xxnet做了封锁
而goagent-always-available 竟然能正常使用 , 速度挺快

**Comment by xyuanmu** [comment]
找到问题了，把 proxy.ini 里的直连规则去掉就行了，不知道是不是IP不支持直连了。

**Comment by AndyLau2017** [comment]
@xyuanmu 不是直连，ip一样死得很快

**Comment by xyuanmu** [comment]
@AndyLau2017 的确死得很快，不过删掉下面两条直连后起码能访问youtube了。
```ini
.ytimg.com = direct
.youtube.com = direct
```
或者 manual.ini 里添加
```ini
.youtube.com = gae
.ytimg.com = gae
```

**Comment by AndyLau2017** [comment]
一直都能打开youtube啊

**Comment by xyuanmu** [comment]
我这里不可以，现在改了才能连上，移动宽带，不知道是不是DNS问题。

**Comment by AndyLau2017** [comment]
我看到有些用移动的，好像完全没受到什么影响，当我们这些电信用户不正常的时候，他们什么事都没，应该是不同地区，不同isp的问题，所以应该不是DNS的问题吧

**Comment by jzp820927** [comment]
@AndyLau2017 移动带宽的国际线路一直都比电信好很多，不光是这两天。
@xyuanmu 前两天是封锁了直连，不过现在已经解封了，你那儿还不能直连嘛？我这儿直连是没问题的。

**Comment by xyuanmu** [comment]
@jzp820927 可能我这里反应迟钝，昨晚才开始不能连

**Comment by jzp820927** [comment]
@xyuanmu 你直连的时候，报什么错？ 是 403 ？还是 sorry ？

**Comment by xyuanmu** [comment]
@jzp820927 连接超时

**Comment by jzp820927** [comment]
哦，连接超时，那就是 IP 问题了，和之前的情况不一样。

**Comment by Ch-Song** [comment]
第一个和最后一个链接都挂了....

**Comment by jzp820927** [comment]
原因你懂滴
