### ISSUE TITLE
部署XX-Net至GAE失败

### ISSUE THREAD

**Issue by iaminblacklist** [XX-net/XX-Net#5751]
删了data文件后重新部署XX-Net至GAE失败
![image](https://user-images.githubusercontent.com/7912108/27252490-a00365b4-5392-11e7-93e9-90cc038e2c79.png)
请问怎么解决？

**Comment by jzp820927** [comment]
是新申请的 google 账号嘛？

**Comment by iaminblacklist** [comment]
就是因为显示	‘’你正使用公共AppID‘’ 这种情况才重新部署的，请问这个是什么原因导致的？

**Comment by iaminblacklist** [comment]
哦，知道如何解决了，谢谢！

**Comment by jzp820927** [comment]
在 web 页，把 appid 填进去就可以了。
