### ISSUE TITLE
SSR的作者破娃酱对GAE安全性的一些评论

### ISSUE THREAD

**Issue by Sirlanri** [XX-net/XX-Net#5754]
无意在破娃酱的博客里看到了goagent，然后看了一下，似乎....gae并不安全？
有没有大触能解释一下，萌新表示不懂啊... 博客地址 https://breakwa11.blogspot.fr/search/label/GoAgent （已经被墙）
以下是博客原文

> 如果你了解GoAgent的SSL机制的话，你就会知道GoAgent提供了一个默认证书，代理充当中间人，以便于解决SSL协议下的数据传输问题，但是因为私钥是公开的，如果其它人也使用此证书来做中间人攻击，那就可以轻松的知道你所访问的内容，包括在你登陆的时候窃取登陆密码。
如果你已经搭建了一个GoAgent代理，那么要解决这个问题，首先停止代理，把local目录里的ca.crt删除，把local/certs下的所有*.crt文件删除，再把你的系统里曾经导入过的GoAgent证书全部删除。
然后启动GoAgent服务，打开浏览器随便访问一个站，以激活GoAgent服务，这时候GoAgent会自动重新生成一个ca.crt证书（若在linux下需要安装python2版本的pyOpenSSL），然后再重新导入这个新生成的证书即可
测试你的浏览器是否已经修正这个问题，访问https://goagent-cert-test.bamsoftware.com/   如果你能正常打开，表示你的浏览器有安全问题，如果弹出了警告窗口，表示你没有导入默认的证书，是安全的。

(顺便一提，似乎墙里面有些人对破娃酱意见挺大的...希望别开撕

**Comment by GoogleGFW** [comment]
几年前的事。
Goagent只是代理工具，并非匿名工具，对隐私保密要求高的人自然不会选择低成本的GAE代理。
你以为老大哥不知道你在爬墙？

**Comment by jzp820927** [comment]
@SLDeongaree 大概意思就是说，GAE 代理需要解密 ssl 流量，用自己的证书重新加密，因为以前有提供默认证书，私钥是公开的，所以很容易中间人。现在已经默认不提供证书了，不存在这个问题了。

**Comment by SLDeongaree** [comment]
感谢大触解答

**Comment by myjlpt** [comment]
自己生成CA证书是没有问题的,当然你真要矫情有问题，也依然存在问题。只要你上网就会可能有问题

**Comment by jzp820927** [comment]
任何事情都是相对的，没有绝对的东西

**Comment by Curriculu** [comment]
但是ip地址可查就已经安全性不高了吧，更不要说旧版本里面证书的问题了。顺便问一下，开启了ipv6之后在教育网改hosts就可以上了，这样怎么隐藏真实的ip地址呢？

**Comment by xxnet** [comment]
简单的，用X-tunnel会有2跳，再进一步的，X-tunnel +  tor，有5跳。

如果你是敏感人士，那么请好好阅读tor的文档，工具只是工具，如何用才重要。

**Comment by ZhangjinhuiFX** [comment]
我最近因为学python，注册了github账号，才知道破娃，其实我已一个路人来看，人家就是提出一个她的建议，毕竟安全还是第一位的！当然砸门都是学习用的，也不怕啥！但总归能帮助到别人，我觉得不错！对于随便就人肉别人，咒骂别人的人，我想说一些人真的就只会跟风，一点自我求证的能力都没有！这些人里面估计又得连怎么编程也不知道，只求嘴嗨！说实话我一向对这种行为非常反感！所以远离世界上的垃圾人是我的一条准则！能绕多远就绕多远！
