### ISSUE TITLE
1.16.3 打不开Gmail中的邮件

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#576]
GoAgent状态信息
系统版本
Property 	Value
XX-Net Version 	1.16.3
Launcher Version 	1.4.0
GoAgent Version 	3.1.49
Python Version 	2.7.1
Sys Platform 	linux2
OS System 	Linux
OS version 	#6 SMP PREEMPT Wed May 20 07:35:32 EEST 2015
OS release 	4.0.4-pf
OS detail 	Dist:; Version:; ID:
language 	en_US
architecture 	64bit,
Browser 	Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0
设置
Property 	Value
Proxy Listen 	127.0.0.1:8087
PAC URL 	http://127.0.0.1:8086/proxy.pac
IPv6 	0
ip-connect-interval 	10
状态
Property 	Value
Google IP num 	2763
100th IP handshake(ms) 	649
connected link(帮助) 	11,0
scaning ip thread num 	5
block stat(帮助) 	OK
日志：
Jul  6 08:19:50 - [DEBUG] create_ssl update ip:113.171.247.226 time:5965
Jul  6 08:19:51 - [DEBUG] get ip:101.99.49.185 t:418
Jul  6 08:19:51 - [DEBUG] get ip:113.171.243.152 t:444
Jul  6 08:19:51 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)
Jul  6 08:19:51 - [DEBUG] get ip:209.85.228.202 t:444
Jul  6 08:19:51 - [WARNING] direct_handler.fetch:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)
Jul  6 08:19:51 - [WARNING] direct_handler.handler send response fail. t:9 e:ResponseNotReady() plus.google.com/hangouts/_/hscv?pvt=AMP3uWbJfL7tx_hTdSVeYHbeSDyI80FPGpfSb4lPewNOvqiVWTlv3A1vxhMvQnTy926Kdfbz4cPFaqWnD_bNDG-a1Y7lSe5ipw%3D%3D&gew=1&xpc=%7B%22cn%22%3A%22ydE5KCL9Dv%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Ftalkgadget.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2Fplus.google.com%2Frobots.txt%22%7D
Jul  6 08:19:51 - [ERROR] direct_handler except:UnboundLocalError("local variable 'response_headers' referenced before assignment",) plus.google.com /hangouts/_/hscv?pvt=AMP3uWbJfL7tx_hTdSVeYHbeSDyI80FPGpfSb4lPewNOvqiVWTlv3A1vxhMvQnTy926Kdfbz4cPFaqWnD_bNDG-a1Y7lSe5ipw%3D%3D&gew=1&xpc=%7B%22cn%22%3A%22ydE5KCL9Dv%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Ftalkgadget.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2Fplus.google.com%2Frobots.txt%22%7D
Jul  6 08:19:51 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/direct_handler.py", line 118, in handler
    if 'Transfer-Encoding' in response_headers:
UnboundLocalError: local variable 'response_headers' referenced before assignment

Jul  6 08:19:52 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)
Jul  6 08:19:52 - [WARNING] direct_handler.fetch:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)
Jul  6 08:19:52 - [WARNING] direct_handler.handler send response fail. t:26 e:ResponseNotReady() plus.google.com/u/0/_/notifications/frame?sourceid=23&hl=zh-CN&origin=https%3A%2F%2Fmail.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.9ruYJpIsduc.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTN6RR24Ahcib0nCMs4uGYi9i5Toag
Jul  6 08:19:52 - [ERROR] direct_handler except:UnboundLocalError("local variable 'response_headers' referenced before assignment",) plus.google.com /u/0/_/notifications/frame?sourceid=23&hl=zh-CN&origin=https%3A%2F%2Fmail.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.9ruYJpIsduc.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTN6RR24Ahcib0nCMs4uGYi9i5Toag
Jul  6 08:19:52 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/direct_handler.py", line 118, in handler
    if 'Transfer-Encoding' in response_headers:
UnboundLocalError: local variable 'response_headers' referenced before assignment

Jul  6 08:19:52 - [INFO] GAE CONNECT plus.google.com:443 
Jul  6 08:19:52 - [DEBUG] GAE CONNECT GET https://plus.google.com/u/0/_/notifications/frame?sourceid=23&hl=zh-CN&origin=https%3A%2F%2Fmail.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.9ruYJpIsduc.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTN6RR24Ahcib0nCMs4uGYi9i5Toag
Jul  6 08:19:53 - [DEBUG] create_ssl update ip:110.164.10.24 time:6703
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35934)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/proxy.py", line 108, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/proxy_handler.py", line 129, in do_CONNECT
    return self.do_CONNECT_DIRECT()
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/proxy_handler.py", line 337, in do_CONNECT_DIRECT
    direct_handler.handler(self.command, host, path, request_headers, payload, self.wfile)
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/direct_handler.py", line 91, in handler
    except OpenSSL.SysCallError as e:
AttributeError: 'module' object has no attribute 'SysCallError'
----------------------------------------
Jul  6 08:19:53 - [DEBUG] create_ssl update ip:74.125.12.166 time:5016
Jul  6 08:19:53 - [DEBUG] create_ssl 113.171.251.241 fail:timed out cost:4004 h:0
Jul  6 08:19:53 - [DEBUG] report_connect_fail network fail
Jul  6 08:19:54 - [DEBUG] get ip:118.98.36.19 t:441
Jul  6 08:19:54 - [DEBUG] create_ssl update ip:46.61.155.219 time:3756
Jul  6 08:19:54 - [DEBUG] get ip:74.125.96.74 t:446
Jul  6 08:19:54 - [INFO] DIRECT t:17078 204 csi.gstatic.com /csi?v=3&s=oz&action=rpw&it=wtsrt_.473,tbsd_.1865,tbnd_.-2338&srt=473&rt=jsl.2151,es.2202,ec.2215,jl.2219,ol.2575,fll.5327
Jul  6 08:19:54 - [DEBUG] get ip:110.164.7.218 t:449
Jul  6 08:19:55 - [DEBUG] create_ssl update ip:113.171.245.37 time:4954
Jul  6 08:19:55 - [DEBUG] get ip:113.171.251.216 t:457
Jul  6 08:19:55 - [DEBUG] create_ssl update ip:203.233.18.46 time:4003
Jul  6 08:19:55 - [DEBUG] create_ssl 203.233.18.46 fail: certficate is none cost:5862 h:4003
Jul  6 08:19:55 - [DEBUG] report_connect_fail network fail
Jul  6 08:19:55 - [DEBUG] create_ssl update ip:209.85.228.202 time:2002
Jul  6 08:19:55 - [DEBUG] create_ssl update ip:101.99.49.185 time:4004
Jul  6 08:19:55 - [DEBUG] create_ssl 101.99.49.185 fail: certficate is none cost:4894 h:4004
Jul  6 08:19:55 - [DEBUG] report_connect_fail network fail
Jul  6 08:19:56 - [DEBUG] get ip:113.171.251.148 t:460
Jul  6 08:19:56 - [DEBUG] get ip:74.125.215.35 t:470
Jul  6 08:19:56 - [DEBUG] get ip:113.171.251.242 t:470
Jul  6 08:19:56 - [DEBUG] get ip:208.117.242.4 t:471
Jul  6 08:19:57 - [WARNING] direct_handler.fetch:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)
Jul  6 08:19:57 - [WARNING] direct_handler.handler send response fail. t:7 e:ResponseNotReady() csi.gstatic.com/csi?s=hangouts&v=3&action=host_cl&rt=hscc.291,hccc.2745,hcl.28277
Jul  6 08:19:57 - [ERROR] direct_handler except:UnboundLocalError("local variable 'response_headers' referenced before assignment",) csi.gstatic.com /csi?s=hangouts&v=3&action=host_cl&rt=hscc.291,hccc.2745,hcl.28277
**Jul  6 08:19:57 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/lh/openshift/XX-Net/goagent/3.1.49/local/direct_handler.py", line 118, in handler
    if 'Transfer-Encoding' in response_headers:
UnboundLocalError: local variable 'response_headers' referenced before assignment**

Jul  6 08:19:57 - [INFO] GAE CONNECT csi.gstatic.com:443 
Jul  6 08:19:57 - [DEBUG] GAE CONNECT GET https://csi.gstatic.com/csi?s=hangouts&v=3&action=host_cl&rt=hscc.291,hccc.2745,hcl.28277
Jul  6 08:19:57 - [DEBUG] host_conn_pool csi.gstatic.com get:110.164.4.25 handshake:3275
Jul  6 08:19:57 - [DEBUG] create_ssl update ip:113.171.243.152 time:4004
Jul  6 08:19:57 - [DEBUG] create_ssl 113.171.243.152 fail: certficate is none cost:5872 h:4004
Jul  6 08:19:57 - [DEBUG] report_connect_fail network fail
Jul  6 08:19:58 - [DEBUG] get ip:173.194.12.7 t:404
Jul  6 08:19:59 - [DEBUG] create_ssl update ip:113.171.251.216 time:1823
Jul  6 08:19:59 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)
Jul  6 08:19:59 - [DEBUG] create_ssl update ip:74.125.215.35 time:1967

提示：对不起…系统遇到问题 (#405) - 53秒后重试…
立即重试  了解详情

**Comment by xxnet** [comment]
日志里看，都是连接ip握手失败导致的，而且能够链接的ip握手时间都是很长（1.9秒、4秒都有），请确认其他网站能翻墙，只是gmail不行？

2015-07-06 8:23 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
现在Gmail中有的邮件可以打开，但网页上头还是显示“提示：对不起…系统遇到问题 (#405) - xx秒后重试…
立即重试 了解详情

youtube，google code都可以打开

在firefox地址栏中输入”www.google.com“，不能打开，而输入”https://www.google.com“可以立即打开

**Comment by xxnet** [comment]
怀疑是浏览器缓存有问题，试试Shift + F5 刷新看看

先用Chrome +SwitchyOmega/SwitchySharp，比较是Google自己的浏览器，也是作为对比。

 firefox设置代理后，www.google.com 输入后，goagent的日志显示什么？



在 2015年7月6日 上午9:28，linhua55 <notifications@github.com>写道：

**Comment by linhua55** [comment]
关于 不能打开 ”www.google.com“ 重现不了了，chrome中输入”www.google.com“，会自动变成”https://www.google.com“，但是显示的是Google的404页面，不断按刷新按钮，有时会正常，在Firefox和Chrome中都是这样。
日志中显示大量的”[WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)“

**Comment by xxnet** [comment]
是最新版本吗？ 1.16.3?

显示404， 不断刷新，有时会正常。
这个现象是ip无法提供服务，比如gvs ip但cipher没有指定，以前的版本会这样。

请试试重新下载最新的版本，并且按原始的设置进行测试

在 2015年7月6日 下午1:28，linhua55 <notifications@github.com>写道：

**Comment by linhua55** [comment]
是，git clone的，然后把data文件夹复制进来的。

**Comment by xxnet** [comment]
试试把data目录先移走，怀疑有些ip是非gws/gvs的

2015-07-06 15:40 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
会不会是TLS版本的问题
➜  XX-Net-1.16.3  ./start.sh
('launcher version:', '1.4.0')
Jul  6 15:51:12 - [WARNING] import pynotify fail, please install python-notify if possiable.
Jul  6 15:51:12 - [INFO] use goagent version:3.1.49
Jul  6 15:51:12 - [INFO] goagent 3.1.49 started /home/lh/download/XX-Net-1.16.3/goagent/3.1.49/start.py
Jul  6 15:51:13 - [INFO] load ip range file:/home/lh/download/XX-Net-1.16.3/data/goagent/ip_range.txt
Jul  6 15:51:13 - [INFO] load google ip_list num:3000, gws num:3000
Jul  6 15:51:13 - [DEBUG] sort ip time:91ms
**Jul  6 15:51:13 - [INFO] SSL use version:TLSv1_2**
Jul  6 15:51:14 - [INFO] ------------------------------------------------------
GoAgent Version    : 3.1.49 (python/2.7.1 )

**Comment by linhua55** [comment]
把data目录移走后，打不开
➜  XX-Net-1.16.3  ./start.sh 
('launcher version:', '1.4.0')
Jul  6 15:58:46 - [WARNING] import pynotify fail, please install python-notify if possiable.
Traceback (most recent call last):
  File "launcher/start.py", line 63, in <module>
    main()
  File "launcher/start.py", line 58, in main
    from start import main as launcher_main
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/start.py", line 13, in <module>
    from gtk_tray import sys_tray
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/gtk_tray.py", line 32, in <module>
    import module_init
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/module_init.py", line 7, in <module>
    import web_control
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/web_control.py", line 31, in <module>
    import update_from_github
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/update_from_github.py", line 20, in <module>
    from update import opener
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/update.py", line 49, in <module>
    opener = create_url_opener()
  File "/home/lh/download/XX-Net-1.16.3/launcher/1.4.0/update.py", line 41, in create_url_opener
    cafile=cafile)
  File "/usr/lib/python2.7/ssl.py", line 435, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
IOError: [Errno 2] No such file or directory

**Comment by xxnet** [comment]
是因为第一次启动，没有CA.crt，update 模块启动失败。
已经提交补丁到trunk了，请git pull 最新的代码测试，未发布新版

2015-07-06 16:00 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
确实是TLS版本的问题，还得剔除ECDHE-RSA-AES128-GCM-SHA256和AES128-GCM-SHA256

**Comment by xxnet** [comment]
good！

2015-07-06 16:22 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
trunk在哪里？怎样git pull trunk？

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/archive/master.zip
这个链接也可以

在https://github.com/XX-net/XX-Net的右侧栏上, Download zip 按钮也可以

2015-07-06 17:43 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by linhua55** [comment]
与git clone https://github.com/XX-net/XX-Net  的没什么变化呀，都是上面的错误，打不开。

**Comment by xxnet** [comment]
抱歉，刚才我push 没有成功，现在上去了，你在试试

2015-07-06 20:09 GMT+08:00 linhua55 <notifications@github.com>:
