### ISSUE TITLE
Chome 一直提示请检查浏览器代理设置，并且访问网站提示未加密，已安装证书，log如下

### ISSUE THREAD

**Issue by yuCharles** [XX-net/XX-Net#5765]
**Chome 版本** 58.0.3029.110
**xx-net 版本**XX-Net-3.3.4

**诊断信息**

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2995 good:13
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:10
scan-ip-thread-num: 0
ip-quality: 849
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
#5322

**Comment by 1178067429** [comment]
你吧XX-net的证书全部删除掉，还有的是源文件，然后再现在XXNET安装就可以解决。

**Comment by yuCharles** [comment]
已解决，感谢
