### ISSUE TITLE
初步得到解决,不知道你们现在还有啥问题没有

### ISSUE THREAD

**Issue by xxxg6666** [XX-net/XX-Net#5772]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:274 good:71
network-status: OK
connected-link: new:2 used:0
worker: h1:14 h2:15
scan-ip-thread-num: 50
ip-quality: 555
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

这是我弄好之后的状态,前两天也以为神器要挂了,很难受.
我的解决办法是把XX-NET之前老版本的全删了,下载最新的测试版本3.3.4,解压,运行,部署服务端,配置,全部走一遍就好了,希望能帮到还有问题的小伙伴

**Comment by xxxg6666** [comment]
谷歌,YouTube都能上了哦,只不过延迟相对出事之前要高一些,但是能用已经满足了

**Comment by overthere33** [comment]
你这情况基本没有借鉴价值。

**Comment by xxxg6666** [comment]
@overthere33 为什么这么说?

**Comment by jzp820927** [comment]
能用就行了，要求不能太高，现在的网络环境太恶劣了。

**Comment by overthere33** [comment]
xxxg6666 没有普遍性呗，多数人的问题还是ip不够，删了重装没法解决的。

**Comment by jzp820927** [comment]
没有 IP 的问题，如果多次重扫都没用的话，只能试试前置代理了。
