### ISSUE TITLE
不算提问，来讨论一下，这一大波僵尸的来由

### ISSUE THREAD

**Issue by pengweipro** [XX-net/XX-Net#5777]
看目前的问题下大家的回复，多数倾向是认为与锅某的事情有关；
不过我倒是有另一个想法，是不是也有那个新出台的什么《***网络安全法》的因素在里面？
刚刚登陆的时候，发现X乎都开始推行实名了，
从手机实名开始，逐渐串联起所有的网络账号，最后整个网络都成实名的了。。。
会不会是由于这个法案的出台，学爬梯子的人数开始暴涨，
所以才有了大规模的围剿。。。

**Comment by MNWPRO** [comment]
法案出台 爬梯子的人为啥会暴涨啊？？

**Comment by pengweipro** [comment]
@MNWPRO 个人看法，总会有那么些人反感gov的监控的，
就像斯诺登的爆料引起了那么大的反响一样，人们潜意识里是不喜欢被监视、被记录的，
而这新法案又在推进无匿名网络上加了一把火

**Comment by MNWPRO** [comment]
原来如此 @pengweipro

**Comment by pengweipro** [comment]
外网较上月略慢，
现在国内网也不正常了，断断续续的卡，
越发怀疑gfw鸟枪换炮了

**Comment by hui5500** [comment]
电信网络正常，可用ip获取了500多，导入家里移动宽带就剩下20个了。估计跟运营商有关系。

**Comment by jzp820927** [comment]
居然还有电信比移动好的情况，罕见。
这个的问题应该就是 youtube 的问题。其他应该关系不大

**Comment by pengweipro** [comment]
我也是电信，目前状况还凑合

**Comment by jzp820927** [comment]
其实都能用，只是好和坏的分别

**Comment by pengweipro** [comment]
这可跟好不沾边，
外网凑合也就罢了，问题是，
现在内网也只能用凑合来形容了。。。

**Comment by jzp820927** [comment]
内网？你指的是国内的网络？

**Comment by pengweipro** [comment]
@jzp820927 国内不就等同于一个大型局域网。。。

**Comment by jzp820927** [comment]
差不多吧
