### ISSUE TITLE
CA证书状态(下载)	Fail 问题又来了.

### ISSUE THREAD

**Issue by mymixing** [XX-net/XX-Net#5781]
本来chrome59+xxnet3.3.4已经没问题了,今早来公司win7系统更新了下.
结果证书就失效了,,依照各种办法,证书还是无效的.
记得之前正常的时候,certmgr中有两条goagent xxnet证书,
但现在重新导入的,只有一条,是fail的状态.
这该怎么搞啊..头痛..

**Comment by pengweipro** [comment]
/data/gae_proxy/ 下面有个ca.crt，
/usr/share/xx/code/default/gae_proxy/local/ 下面还有个 cacert.pem，
不知道俩有啥区别，反正我都导入了。。。

**Comment by jzp820927** [comment]
检查下系统证书，把所有的和 GAE 有关的证书全部删除，到导入一次试试
