### ISSUE TITLE
今早更新了一次win7,证书就失效了,彻底重新配置xxnet,也没用.

### ISSUE THREAD

**Issue by mymixing** [XX-net/XX-Net#5788]
如题,主要是证书出现问题搞不定啊.,诊断如下.

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by sgricky** [comment]
我的3.3.4，今天回复正常了，从15回复到6xx可用数。证书的问题你试试把Cert目录备份后删除再重启服务？我每次都这么折腾一下就好了。

**Comment by wenliyang** [comment]
gws-ip-num: total:0 good:0

楼主一个可用IP都没有

**Comment by mymixing** [comment]
@sgricky 都试过了,不行.
@wenliyang 和可用ip没关系,还没到可用ip这里呢.

**Comment by SeaHOH** [comment]
>proxy_state: Fail

这才是正确的吐槽方式

**Comment by jzp820927** [comment]
证书问题 #532

**Comment by mymixing** [comment]
@jzp820927 谢谢,我知道是证书的问题.
问题是,这些办法根本没用,我记得之前好用的时候,certmgr,受信认中,有两个xxnet证书.
但现在一切重新弄,受信认中只能导入一个xxnet证书,所以我想应该是少导入一个造成的.

**Comment by SeaHOH** [comment]
你代理都没设置好，关证书什么事。

**Comment by mymixing** [comment]
擦,找到问题了...
因为之前翻墙用goagent,有设置开机启动.
结果这货吧8087端口占用了,xxnet启动后并没有任何端口绑定失败的提示(包括日志中也没提示).
把占用程序结束就好了,这确实应该算是一个issue

**Comment by jzp820927** [comment]
端口占用，一般日志会提示的，可能没注意吧

**Comment by mymixing** [comment]
我确认过了,没有提示.

**Comment by jzp820927** [comment]
好比，那就不知道了，既然问题解决了，就算了吧，不纠结了。
