### ISSUE TITLE
打开XX-Net  就会显示请检查浏览器代理设置，最后清理一下浏览器缓存就好了，求解决

### ISSUE THREAD

**Issue by DenonLH** [XX-net/XX-Net#5789]
![un0f9xhp9ab5 4t t8 bk2](https://user-images.githubusercontent.com/25523603/27271928-3cfe712a-54fa-11e7-8ae9-a34eac91f954.png)

还有我有8个Google APPID扫描出来IP最多就33个，也不知道什么原因，不是说已经恢复了吗？

**Comment by AndyLau2017** [comment]
今天星期一，估计坏人开始上班了，受影响正常

**Comment by yabalababoom** [comment]
重启一下就好了

**Comment by jzp820927** [comment]
你这个 IP 数量也是少的可怜啊。看样子也不是所有人都恢复了，调大扫描线程试试

**Comment by DenonLH** [comment]
@jzp820927 你说那个CA证书？？？

**Comment by DenonLH** [comment]
我把线程调到了500 也是这样  证书我也导入了啊 
![fp x k b3dvwty1bd eh](https://user-images.githubusercontent.com/25523603/27283706-2240a1fe-5528-11e7-84df-bc657bcc02a6.png)

**Comment by jzp820927** [comment]
那应该就是 地域 和 ISP 的封锁了，不过看你还有 26 个IP，应该也能用吧？

**Comment by DenonLH** [comment]
延迟高啊  无奈啊  主要是这个 就会显示请检查浏览器代理设置，最后清理一下浏览器缓存就好了  也不知道为啥？？？？？

**Comment by DenonLH** [comment]
我西安啊

**Comment by DenonLH** [comment]
我是西安的  ISP我不知道怎么查询  可以用倒是延迟高

**Comment by AndyLau2017** [comment]
延迟高没什么的吧，之前1000多延迟还不是一样能用

**Comment by jzp820927** [comment]
ISP 的意思，就问你的宽带是 移动的？电信的？还是联通的？

**Comment by DenonLH** [comment]
我是电信

**Comment by DenonLH** [comment]
这么专业的术语 真心不懂

**Comment by jzp820927** [comment]
好吧，电信差不多就这鸟样了，如果实在没 IP，可能只能考虑试试前置代理了。

**Comment by DenonLH** [comment]
就没办法了吗？？？ 过几天在看把  如果还这样 就算了

**Comment by jzp820927** [comment]
或者等几天观察下，这种大规模封杀，一般不会持续太久时间。

**Comment by DenonLH** [comment]
嗯  这个是什么问题,打开XX-Net 就会显示请检查浏览器代理设置，最后清理一下浏览器缓存就好了

**Comment by jzp820927** [comment]
既然清理了缓存就好了，那就是缓存的问题呗。

**Comment by DenonLH** [comment]
缓存问题？？？  又是解决办法吗？

**Comment by jzp820927** [comment]
这种只不过是状态显示异常而已，不影响使用。
说直白点，就是你的 XX 是正常可用的，只不过状态错误的现实为异常而且，一般强迫症晚期患者比较在乎这个。

**Comment by DenonLH** [comment]
0.0

**Comment by DenonLH** [comment]
我只是感觉比较麻烦，还要清理缓存。

**Comment by jzp820927** [comment]
这个又不影响你使用，你不管他不就行了。
