### ISSUE TITLE
【新手提问】你们的网速怎么样？我的可以看视频，但是无法看直播

### ISSUE THREAD

**Issue by 673055938** [XX-net/XX-Net#5797]
菜鸟一个，今天才弄成功（应该是成功了吧....），正常浏览网页和观看视频都没有问题，但是各种直播平台都无法播放。   设置后有些问题也不太清楚
1、教程里说是选“XX-NET自动切换”，但是我用这个无法上网，换到”XX-NET”就可以了。
2、（我用的是chrome浏览器）一定要选“取消全局代理”吗？我还是选的全局PAC智能代理，也能上网。
3、XX-NET是只能在浏览器中使用吗？ 战网就无法登陆

可能有些问题比较白痴。。  求助各位了

**Comment by AndyLau2017** [comment]
123456789

**Comment by zhencaihao** [comment]
xx-net代理后。外国的直播平台twitch能看，只是有时候卡有时候流畅。我都是设置"全局通过GAEProxy代理"，等要用的时候才开软件。这个软件应该只能代理网页，玩游戏什么的不行。如果你想玩外国游戏还是花钱买SS吧。

**Comment by Acytoo** [comment]
1.2：教程只是针对大多数人的，你具体的设置要针对你的上网环境。
3：不是，但是软件要支持代理才可以用

**Comment by 673055938** [comment]
@zhencaihao @Acytoo 好的 谢谢

**Comment by jzp820927** [comment]
1。自动切换是属于只能代理，根据规则来确定是否走代理，XXNET，就是全局代理了，所有流量全部走代理。
2。哪种能用，你就用哪种就行了
3。一般都用于浏览器，因为 XXNET 只支持代理 http/https 协议，游戏这些什么的肯定是不支持的，游戏需要代理 UDP 的流量，可以用 支持 UDP 转发的 SS

**Comment by 673055938** [comment]
@jzp820927 多谢大神详细解答
