### ISSUE TITLE
GoAgent配置里的密码，填什么？

### ISSUE THREAD

**Issue by zhouhao1217** [XX-net/XX-Net#58]
![1](https://cloud.githubusercontent.com/assets/11462060/6641217/74da153c-c9d7-11e4-921f-71f9d33cd5d4.png)

配置GoAgent这里面APPID我知道是什么但是后面的PASSWORD，好像APPID没有PASSWORD的吧？？

**Comment by shawwokou123** [comment]
为空，没有密码就不填，只填appid即可

**Comment by xxnet** [comment]
新版在界面上加了说明了
