### ISSUE TITLE
出现隐私设置错误

### ISSUE THREAD

**Issue by HuZiyang2002** [XX-net/XX-Net#5803]
选择的PAC代理
打不开谷歌
显示隐私设置错误
请求解决方式

**Comment by HuZiyang2002** [comment]
附图
[截图](https://public.lightpic.info/image/C4A2_594892200.jpg)

**Comment by wenliyang** [comment]
#5322

**Comment by feverrun** [comment]
问题的简单描述：
您的连接不是私密连接
攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_AUTHORITY_INVALID
问题的解决方法：
1.这个问题，是证书问题，说我们的证书不被信任
2.到这里 设置-管理证书-授权中心
3.搜索goagent 把这个选项下面的所有证书，设置为可信的
结尾，自己遇到问题瞎搞的，解决了。
