### ISSUE TITLE
Gmail 无法打开.

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#5804]
用 xxnet 无法打开 Gmail, 但是 Google, Youtube, 还有其他 网站都没问题.
请问 如何解决, 谢谢!

**Comment by jzp820927** [comment]
要不加规则试试走 GAE

**Comment by kuchaguangjie** [comment]
@jzp820927 
果然 在 `xxnet/data/gae_proxy/config.ini` 里面 加上 下面的 就可以访问 gmail 了, 跟 youtube 一样.

```
[hosts]
.youtube.com = gae
mail.google.com = gae

```

**Comment by jzp820927** [comment]
建议你规则加在  manual.ini 文件，不要加 config.ini ，config.ini 文件会被覆盖。

**Comment by kuchaguangjie** [comment]
@jzp820927  好的, 多谢 提醒!
