### ISSUE TITLE
让人生气，谷歌应设法查清破坏XX-net的源头及位置

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#5809]
刚打开XX-net发现谷歌国际：www.google.com/ncr 无法访问。而且只有谷歌无法访问，因为那些坏人知道谷歌上可以说话。其他像推特，雅虎，CNN等都可以正常访问，因为这些网站都不像谷歌这么有用，这么好。所以谷歌一定要调查一下，到底是从哪里，极其隐蔽的地方发出的破坏XX-net的指令。因为如果不彻底查清，他们这些坏人还会反复重来。

**Comment by anwopen** [comment]
我也是同样的问题。。。

**Comment by jzp820927** [comment]
和 google 相关的网站，不能访问的，全部添加规则，走 GAE

**Comment by AndyLau2017** [comment]
设防火墙的不是谷歌，，你骂谷歌也没用

**Comment by langbao** [comment]
@jzp820927 求教！如何添加规则？

**Comment by 80068** [comment]
@jzp820927 好的，我试试。

**Comment by jzp820927** [comment]
@langbao 改 data/gae_proxy/manual.ini 文件
[hosts]
.不能访问的域名 = gae

**Comment by NuclearBlast** [comment]
有趣的是，hk可以访问

**Comment by jzp820927** [comment]
github 不能访问？是直连？还是代理？

**Comment by anwopen** [comment]
@jzp820927 请问gae_proxy文件夹下没有manual.inn文件怎么处理

**Comment by jzp820927** [comment]
自己新建这个文件
