### ISSUE TITLE
身在新疆，不能直连github、贴吧等，每次要切换到全局代理，麻烦。如何将这些网站加入GFW黑名单？

### ISSUE THREAD

**Issue by panxuelei** [XX-net/XX-Net#5813]

**Comment by jzp820927** [comment]
omega 可以直接配置规则。

**Comment by AndyLau2017** [comment]
启动图标，右下角选pac智能代理就好啦

**Comment by dlzdwxdt** [comment]
新疆连贴吧都BAN？过分了吧！

**Comment by jzp820927** [comment]
贴吧人多嘴杂，你懂滴

**Comment by AndyLau2017** [comment]
卧草，楼主的意思是，贴吧都不能直连了？

**Comment by panxuelei** [comment]
是的

**Comment by panxuelei** [comment]
@AndyLau2017  
这个我知道，但访问贴吧github时要全局代理，访问其它国内没有被墙的网站时要切换回智能代理，否则访问的比较慢。贴吧github在xxnet中默认直连的，如何设置让它们走代理。

**Comment by jzp820927** [comment]
上面都给你说了，用 omega 可以自己配置规则。xxnet 的规则是根据列表自动生成的，不支持自定义。

**Comment by panxuelei** [comment]
@jzp820927  好的，谢谢

**Comment by AndyLau2017** [comment]
@panxuelei  说实话，你在新疆，我还是不建议你用gae系列翻墙软件，安全性太低了，被抓到就麻烦了

**Comment by a270505969** [comment]
同是新疆的+1
新疆就是局域網裏的局域網 
貼吧 百度雲盤 還有一些直播網站等等都不能直連

**Comment by AndyLau2017** [comment]
@a270505969  靠，管那么严，真是如临大敌了。最好去看看编程随想的教程，把翻墙软件全部装虚拟机里，这样翻墙就会安全很多，不然就gae这种，要是真查起来，很容易查到

**Comment by Mach525** [comment]
如 @jzp820927 所说使用SwitchyOmega创建代理服务器规则和自动切换规则并将XX-NET设置为取消全局代理，可以对不同网站单独设置规则。

**Comment by overthere33** [comment]
@AndyLau2017 小屁民正常上网不扯些乱七八糟的，谁有空查你？

**Comment by AndyLau2017** [comment]
你想多了，如果你用xx在新疆西藏翻墙，真要查你，没可能查不到的

**Comment by jzp820927** [comment]
针对性封锁，特定区域，流量不大，所以可以封的比较死，这种封死肯定是 ISP 级别的了。
