### ISSUE TITLE
为什么电脑一死机，重启后IP数量就清零了呢？

### ISSUE THREAD

**Issue by wangyunlg** [XX-net/XX-Net#5822]
上次是电脑蓝屏，重启之后，1500IP没了；这次是电脑会灰屏，点击无任何响应，重启后，1000IP又没有了，准备下午备份一下呢。真悲催啊！

**Comment by jzp820927** [comment]
bug 吧，没太大影响，就别较真了，项目已经没人维护了，估计很难会有人来处理 bug。

**Comment by wangyunlg** [comment]
@jzp820927  恩，幸亏还有scan_ip.log在，提取一下就又好了

**Comment by jzp820927** [comment]
就当作是给 IP 洗了一次澡，全部重新扫描。
