### ISSUE TITLE
替代品：Bluemix创建Shadowsocks

### ISSUE THREAD

**Issue by jetyu** [XX-net/XX-Net#5825]
XX-NET暂时用不了了，没别的意思，就是想着造福大家，但是速度一般，看YouTube 720p没啥问题，所以现在XX-NET不好使的情况下，拿bluemix建立SS服务
https://jetyu.me/post/ibm-bluemix-ss.html

补充：研究明白了。。。。。不限制流量但是限制机器配置。。。这样就相当于一直免费了。。。

费用
外部客户：Bluemix 的免费账户有30 天的试用期，30 天之后添加有效的信用卡就可以继续使用免费额度内的运行时和容器，用全球付的虚拟信用卡可以通过验证，而且验证的时候没有扣款，应该只对信息的真伪进行了验证，而不像PayPal会进行扣款验证。
IBM员工 ：使用IBM邮箱是可以免费使用的，会显示有期限，但是是自动续期。

**Comment by jzp820927** [comment]
这个支持下

**Comment by AndyLau2017** [comment]
IBM还是吝啬了一点

**Comment by wpp214** [comment]
真心不错 但是一个月注册一次邮箱…………还是太蛋疼

**Comment by StarShield** [comment]
感谢分享

**Comment by Acytoo** [comment]
感谢分享

**Comment by lastboy1228** [comment]
只要容器的运行内存设置小点，就是不限流量的永久免费吧

**Comment by dlzdwxdt** [comment]
谢谢了~

**Comment by wpp214** [comment]
不是啊  作者博客写了只有ibm内部员工是免费的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: roc king<mailto:notifications@github.com>
发送时间: 2017年6月21日 19:40
收件人: XX-net/XX-Net<mailto:XX-Net@noreply.github.com>
抄送: wpp214<mailto:ksi_wang@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [XX-net/XX-Net] 暂时替代品：Bluemix创建Shadowsocks (#5825)


只要容器的运行内存设置小点，就是不限流量的永久免费吧

―

**Comment by perverseshadow** [comment]
填写完邮箱后，密码怎么输入都不对！啥情况啊？？

**Comment by AndyLau2017** [comment]
。。。。。。。。。。。。。。移步相关论坛去问

**Comment by Alvin9999** [comment]
如果只是临时用，可以用我分享的[免费ss账号](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7)

**Comment by SLDeongaree** [comment]
推荐GFW.PRESS

**Comment by jzp820927** [comment]
过墙途径有很多，还不用这么极端的方式。

**Comment by jetyu** [comment]
@wpp214 就你一个人看明白了。。。设置256M的内存配置。。。。相当于永久免费。

**Comment by jetyu** [comment]
@perverseshadow  我更新了一下微博，注意注册的时候使用bluemix.com这个网址.

**Comment by candy2107** [comment]
@jetyu 建议加上 dply.co , 用来构建ss

**Comment by ez213** [comment]
感谢分享

**Comment by AndyLau2017** [comment]
有个细节，就是注册要手机号，这个就蛋疼了，而且IBM并没有像谷歌一样退出中国....IBM在中国还有办事处..

**Comment by yaojun1314** [comment]
![fireshot capture 4 - wordpress - webide - https___ide coding net_ws_alalxn](https://user-images.githubusercontent.com/23252618/27429199-f79c55fa-5776-11e7-885e-66672cd529d2.png)
部署到这一步无法输入邮箱，求解，我的步骤是不是不对啊？

**Comment by yaojun1314** [comment]
@jetyu 大神，求教了，可以教教我么

**Comment by wz7465** [comment]
bluemix玩起来难度有点高了，它的cli容易被墙

**Comment by langbao** [comment]
@jetyu 用代理也无法注册IBM Bluemix账户，一直转着不停。
[https://www.flickr.com/photos/151863034@N05/shares/d6gj0t](url)

**Comment by langbao** [comment]
`https://www.flickr.com/photos/151863034@N05/shares/d6gj0t`

**Comment by langbao** [comment]
@jetyu 用代理也无法注册IBM Bluemix账户，一直转着不停。

- [https://www.flickr.com/photos/151863034@N05/shares/d6gj0t ]

**Comment by langbao** [comment]
@jetyu 用代理也无法注册IBM Bluemix账户，一直转着不停。
试了几次，图片上传不成功。

**Comment by langbao** [comment]
[https://www.flickr.com/photos/151863034@N05/shares/d6gj0t](url)

**Comment by jetyu** [comment]
@AndyLau2017 不仅仅是办事处，IBM在中国有6家公司，接近4W员工。

**Comment by langbao** [comment]
@AndyLau2017
AndyLau2017 commented 2 days ago
。。。。。。。。。。。。。。移步相关论坛去问

请问！相关论坛在哪？能给个链接吗？

**Comment by trdmm** [comment]
@yaojun1314 先注册，然后填写组织，空间什么的再弄

**Comment by Snowzyk** [comment]
刚试了下，网速太慢了，下载就是200-300kb的样子，youtube只能勉强看个320p，效果不太好，只能当个备用的，不过还是谢谢大大分享了

**Comment by AndyLau2017** [comment]
@langbao  其实你照教程弄就行了，不过这种要手机注册的，不安全

**Comment by jetyu** [comment]
@langbao  你可以网上找虚拟手机号的。

**Comment by AndyLau2017** [comment]
@jetyu 即使找到了手机号，还要找信用卡吧？

**Comment by jzp820927** [comment]
9494

**Comment by wooowooo** [comment]
@jetyu 请教 

添加信用卡时出现错误
Could not place order. Problem authorizing the credit card.

用的是wirex的信用卡.  全球付的信用卡需要充值才能申请.

**Comment by jzp820927** [comment]
应该是 bluemix 不认这个信用卡吧，估计得换其他信用卡

**Comment by zzgpku** [comment]
按着教程来，一直错误
![image](https://user-images.githubusercontent.com/14359560/31892532-d816f1ec-b83b-11e7-8a63-17c45f857065.png
@jetyu

**Comment by lzw9560** [comment]
现在还能用么，跟着做了半天还是失败了。提示我需要初始化组织，可是我无论怎么初始化都失败了。
