### ISSUE TITLE
ip严重缺少

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#5828]
今天突然就都死了......也不知道是什么敏感时期

**Comment by weixiaohhh** [comment]
我也是

**Comment by DenonLH** [comment]
什么网络啊？？？

**Comment by my-great** [comment]
最近啊！你们都不知道吗？中纪委第一人有点麻烦

**Comment by weixiaohhh** [comment]
wqs?

**Comment by AndyLau2017** [comment]
翻墙都还那么孤陋寡闻，难道你们翻墙都是看黄网的？

**Comment by SLDeongaree** [comment]
楼上评论666

**Comment by jzp820927** [comment]
我想问问，有没有人看成 wps 的？

**Comment by GitKKg** [comment]
前几天加large IP效果还不错的，现在也不行了，只能上google，邮箱和YouTube都上不去了
这么狠，难道wqs的事是真的？

**Comment by AndyLau2017** [comment]
我现在情况是，扫出ip有多少，就慢慢的死多少，明显616爆料过后，破墙加强了不少，我这边正是617开始出现问题的，616那晚youtube还出现了错误打不开，真疯狂

**Comment by luoni2002** [comment]
有时翻也并不想看ZG那点破事

**Comment by AndyLau2017** [comment]
你不关心政治，总有一天政治会主动来关心你，每个人都脱离不了政治，小到柴米油盐，大到衣食住行都相关，毕竟是每个人的切身利益....

**Comment by danielsuzx** [comment]
我也遇到了这样的问题，不过我是这样解决的：每次开启XX-Net后重新检查一遍IP，把无效的都丢了。

其实也有个疑惑，我把自动扫描都关了，为什么每次重开XX都这么多ip（无效的）？

**Comment by SeaHOH** [comment]
@danielsuzx 
这不很正常吗，墙又不是一成不变。而且关闭扫描是设置线程数为 0。

**Comment by whhxmwhh** [comment]
73罢了。

**Comment by AndyLau2017** [comment]
据说green VPN要被迫倒闭了，公司已经发出公告，要办理退款的可以申请。看来确实是在磊墙了。。

**Comment by Temmie-hOi** [comment]
奇怪我youtube能上但是google上不去......

**Comment by danielsuzx** [comment]
上不了谷歌的朋友试试https://www.google.com.hk，不要上google.com

**Comment by danielsuzx** [comment]
@SeaHOH 我是设置为0呀= =，我是想着我天天用，整天重复那个操作好麻烦- -

**Comment by Temmie-hOi** [comment]
google改成hk能上了，gmail上不去了......

**Comment by SeaHOH** [comment]
@danielsuzx 
没办法啊，它就是要干扰你，觉得麻烦？是的，我也是，换用其它工具可能会好些，但是最终也没什么不同。

**Comment by Temmie-hOi** [comment]
顺带好奇73是什么

**Comment by AndyLau2017** [comment]
@Temmie-hOi 是时候注册个推特玩玩啦

**Comment by jzp820927** [comment]
上不去的都走 GAE
没 IP 的的，都调大扫描线程

**Comment by out0fmemory** [comment]
试试这个，https://github.com/out0fmemory/GoAgent-Always-Available

可以直接用或者把里面的可用的ip导入到xx-net，作为种子ip，这两天应该勉强可用，最近确实ip很少而且被封的太快了。。。。。。。
