### ISSUE TITLE
托盘图标消失，localhost无法打开，start.bat提示network fail

### ISSUE THREAD

**Issue by wolvers** [XX-net/XX-Net#5833]
6月19号开机后发现无法连接网络，之前遇到过类似情况，重启下XXNET就ok
但是，右下角托盘图标消失，这种情况也遇到过，开下start.bat就可以搞定
不过，打开start.bat后，发现提示network fail，提示erro10106
根据查询后发现，可能是端口被占用，用命令行查询没有得到结果
之后，重新下载了3.3.1版本和3.3.4版本，仍然无法上网（360安全卫士和360杀毒都已卸载）

目前情况如下

托盘图标消失，localhost无法打开，start.bat提示network fail

launcher.log如下：
Jun 21 23:29:17.587 - [INFO] use build-in openssl lib
Jun 21 23:29:17.588 - [INFO] start XX-Net 3.3.1
Jun 21 23:29:17.589 - [DEBUG] start confirm_xxnet_exit
Jun 21 23:29:17.590 - [DEBUG] good, xxnet:8087 cleared!
Jun 21 23:29:17.590 - [DEBUG] good, xxnet:8085 clear!
Jun 21 23:29:17.590 - [DEBUG] finished confirm_xxnet_exit

使用start.bat提示如下：
Jun 21 23:29:17.587 - [INFO] use build-in openssl lib
Jun 21 23:29:17.588 - [INFO] start XX-Net 3.3.1
Jun 21 23:29:17.589 - [DEBUG] start confirm_xxnet_exit
Jun 21 23:29:17.590 - [DEBUG] good, xxnet:8087 cleared!
Jun 21 23:29:17.590 - [DEBUG] good, xxnet:8085 clear!
Jun 21 23:29:17.590 - [DEBUG] finished confirm_xxnet_exit
Jun 21 23:29:17.873 - [INFO] SSL use version:TLSv1_2
Jun 21 23:29:18.638 - [WARNING] network fail
Jun 21 23:29:18.909 - [INFO] OpenSSL support alpn
Jun 21 23:29:18.911 - [INFO] load ip range file:C:\Users\wolvers\Desktop\XX-Net-
3.3.1\code\default\gae_proxy\local\ip_range.txt
Jun 21 23:29:18.933 - [INFO] load google ip_list num:0, gws num:0
Jun 21 23:29:18.943 - [INFO] OpenSSL support alpn
Jun 21 23:29:18.945 - [WARNING] no enough ip
Jun 21 23:29:18.950 - [DEBUG] ## GAEProxy set keep_running: True
Jun 21 23:29:18.951 - [INFO] ---------------------------------------------------
---
Jun 21 23:29:18.952 - [INFO] Python Version     : 2.7.11
Jun 21 23:29:18.952 - [INFO] OS                 : Version:6-1; Build:7601; Platf
orm:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Jun 21 23:29:18.952 - [INFO] Listen Address     : 127.0.0.1:8087
Jun 21 23:29:18.952 - [INFO] GAE APPID          : wolverscg|cgwolvers|wolverscg1
|wolverscg2|wolverscg3|wolverscg4|wolverscg5
Jun 21 23:29:18.953 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pa
c
Jun 21 23:29:18.953 - [INFO] ---------------------------------------------------
---
Exception in thread Thread-58:
Traceback (most recent call last):
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\python27\1.0\lib\thre
ading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\python27\1.0\lib\thre
ading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\gae_proxy\start.py",
line 18, in main
    client.main()
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\gae_proxy\local\proxy
.py", line 155, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTE
N_PORT), proxy_handler.GAEProxyHandler)
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\python27\1.0\lib\noar
ch\simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\python27\1.0\lib\noar
ch\simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\python27\1.0\lib\noar
ch\simple_http_server.py", line 271, in add_listen
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "C:\Users\wolvers\Desktop\XX-Net-3.3.1\code\default\python27\1.0\lib\sock
et.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 10106]

Jun 21 23:29:19.445 - [WARNING] no enough ip

netstat查询网络连接情况如下：
活动连接

  协议  本地地址          外部地址        状态
  TCP                           wolvers-PC:0           LISTENING
  TCP                           wolvers-PC:0           LISTENING
  TCP                           wolvers-PC:0           LISTENING
  TCP                           wolvers-PC:0           LISTENING
  TCP                           wolvers-PC:0           LISTENING
  TCP                           wolvers-PC:0           LISTENING
  TCP    [::]:445               wolvers-PC:0           LISTENING
  TCP    [::]:2869              wolvers-PC:0           LISTENING
  TCP    [::]:49152             wolvers-PC:0           LISTENING
  TCP    [::]:49153             wolvers-PC:0           LISTENING
  TCP    [::]:49164             wolvers-PC:0           LISTENING
  TCP    [::1]:49154            wolvers-PC:0           LISTENING
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP                           *:*
  UDP    [::]:500               *:*
  UDP    [::]:3702              *:*
  UDP    [::]:3702              *:*
  UDP    [::]:4500              *:*
  UDP    [::]:5355              *:*
  UDP    [::]:53341             *:*
  UDP    [::1]:1900             *:*
  UDP    [::1]:53659            *:*
  UDP    [::1]:53998            *:*
  UDP    [::1]:56364            *:*
  UDP    [::1]:59821            *:*
  UDP    [::1]:65029            *:*
  UDP    [fe80::d00c:b2b0:a243:4fc0%13]:1900  *:*
  UDP    [fe80::d00c:b2b0:a243:4fc0%13]:53658  *:*

使用netstat查询8080 8085 8086 8087 1080端口都没有任何提示

**Comment by SeaHOH** [comment]
搜了一下，有人遇到相同问题重置 winsock 解决，不知道是不是真的，但我的确看不出有其它问题。
搜索 `Errno 10106 winsock 重置`。

**Comment by wolvers** [comment]
问题解决，运行cmd，使用 netsh winsock reset 重置后，network fail问题已解决
