### ISSUE TITLE
【已解决】你们的XXNET还能翻嘛，好几天了不能翻

### ISSUE THREAD

**Issue by lybglory** [XX-net/XX-Net#5838]
Jun 22 22:58:15.115 - [WARNING] no enough ip
Jun 22 22:58:15.625 - [WARNING] no enough ip
Jun 22 22:58:15.840 - [DEBUG] create ssl timeout fail.
Jun 22 22:58:16.132 - [WARNING] no enough ip
Jun 22 22:58:16.647 - [WARNING] no enough ip
Jun 22 22:58:17.164 - [WARNING] no enough ip
Jun 22 22:58:17.684 - [WARNING] no enough ip
Jun 22 22:58:18.200 - [WARNING] no enough ip
Jun 22 22:58:18.715 - [WARNING] no enough ip
Jun 22 22:58:19.231 - [WARNING] no enough ip
Jun 22 22:58:19.747 - [WARNING] no enough ip
Jun 22 22:58:20.263 - [WARNING] no enough ip
Jun 22 22:58:20.784 - [WARNING] no enough ip
Jun 22 22:58:21.300 - [WARNING] no enough ip
Jun 22 22:58:21.816 - [WARNING] no enough ip
Jun 22 22:58:22.333 - [WARNING] no enough ip
Jun 22 22:58:22.834 - [WARNING] no enough ip
Jun 22 22:58:23.339 - [WARNING] no enough ip

已经解决了，能翻墙
https://github.com/XX-net/XX-Net/issues/5847

**Comment by cobob** [comment]
现在好的IP越来越少, 很多IP都失效了.
你需要长时间保持XX开启状态,让它在后台不停的扫描才能保证有足够的IP可用.
你可以把XX安装在路由器24小时扫描.
仅仅是使用电脑时才打开XX进行扫描,那所扫描到的IP肯定是不够的.

**Comment by aaaweisen** [comment]
同样，一直都不能用~~~

**Comment by ffdzpilot** [comment]
ip一死一大片，重启路由器又回来一些，貌似那个旺旺亮灯进程很顽强，用尽各种办法都干不死它。只能手动频繁禁止。

**Comment by Kwyper** [comment]
我翻的了，但是衹有40到50 個IP。。

**Comment by whhxmwhh** [comment]
不能犯科。完全不能用了。五毛高兴了。我们找别的路出来

**Comment by kevinweiqy** [comment]
@cobob 请问下怎么将XXNET设置在路由器呀？有教程么？

**Comment by out0fmemory** [comment]
试试这个，https://github.com/out0fmemory/GoAgent-Always-Available

可以直接用或者把里面的可用的ip导入到xx-net

**Comment by cobob** [comment]
@kevinweiqy [https://github.com/XX-net/XX-Net/wiki/%E5%9C%A8%E6%9C%89USB%E6%8E%A5%E5%8F%A3%E7%9A%84%E6%A2%85%E6%9E%97%E5%9B%BA%E4%BB%B6%E8%B7%AF%E7%94%B1%E5%99%A8%E4%B8%8A%E5%AE%89%E8%A3%85XX-Net-%EF%BC%88%E6%87%92%E4%BA%BA%E8%84%9A%E6%9C%AC%EF%BC%89](url)

**Comment by jzp820927** [comment]
XX 安装到路由器，还是技术成本较高，而且并不是 100% 能成功。
没有 IP 的情况，目前只能调大扫描线程数看看有没有效果了。

**Comment by c6132a1** [comment]
我这里可以，720p 电影没问题，多大是谷歌官方ip, 我是用，港 台 日 韩 ip段。
157.197.93.0/24
74.125.130.0/24
59.18.45.0/24
163.44.26.0/24
106.162.216.0/24
58.176.217.0/24
220.255.2.0/24
74.125.203.0/24
216.58.200.0/24
216.58.220.0/24
203.79.253.0/24
172.217.10.0/24
74.125.23.0/24
210.139.253.0/24
202.224.62.0/24
203.248.210.0/24
203.233.96.0/24
163.28.130.0/24
210.242.125.0/24
74.125.204.0/24
163.28.116.0/24
59.18.46.0/24
210.92.119.0/24
74.125.68.0/24
211.239.188.0/24
60.199.175.0/24
203.66.169.0/24
157.197.92.0/24
210.158.146.0/24
61.33.130.0/24
216.58.211.0/24
210.94.153.0/24
59.18.49.0/24
218.219.168.0/24
211.117.39.0/24
216.58.197.0/24
163.28.83.0/24
61.37.150.0/24
203.211.0.0/24
203.248.132.0/24
61.238.239.0/24
203.66.182.0/24
203.233.126.0/24
121.78.42.0/24
58.229.92.0/24
64.233.187.0/24
216.58.203.0/24
172.217.9.0/24
211.239.234.0/24
119.149.187.0/24
202.142.225.0/24
211.49.146.0/24
119.149.188.0/24
64.233.188.0/24
59.18.35.0/24
203.233.37.0/24
61.219.131.0/24
172.217.27.0/24
210.242.128.0/24
163.28.38.0/24
173.194.74.0/24
172.217.23.0/24
61.205.127.0/24
203.233.10.0/24
58.123.102.0/24
163.28.51.0/24
172.217.20.0/24
210.143.70.0/24
58.123.220.0/24
216.58.212.0/24
210.143.147.0/24
172.217.26.0/24
203.248.180.0/24
216.58.199.0/24
118.143.88.0/24
203.211.8.0/24
172.217.16.0/24
203.233.18.0/24
1.255.33.0/24
203.233.92.0/24
216.58.221.0/24
108.177.97.0/24
59.18.34.0/24
64.233.189.0/24
203.66.124.0/24
124.153.255.0/24
74.125.24.0/24
216.58.196.0/24
121.78.206.0/24
202.88.193.0/24
211.1.149.0/24
203.252.15.0/24
74.125.200.0/24
1.255.22.0/24
61.219.146.0/24
121.78.52.0/24
203.233.63.0/24
202.169.173.0/24
216.58.216.0/24
202.208.170.0/24
202.39.143.0/24
202.166.193.0/24
172.217.17.0/24
172.217.11.0/24
123.205.250.0/24
172.217.24.0/24
211.76.107.0/24
203.66.180.0/24
59.18.44.0/24
182.163.240.0/24
124.216.0.0/24
210.242.127.0/24
59.20.132.0/24
211.76.116.0/24
139.175.107.0/24
172.217.25.0/24
202.169.175.0/24
203.66.155.0/24
203.233.88.0/24

**Comment by c6132a1** [comment]
157.197.93.0/24
74.125.130.0/24
59.18.45.0/24
163.44.26.0/24
106.162.216.0/24
58.176.217.0/24
220.255.2.0/24
74.125.203.0/24
216.58.200.0/24
216.58.220.0/24
203.79.253.0/24
172.217.10.0/24
74.125.23.0/24
210.139.253.0/24
202.224.62.0/24
203.248.210.0/24
203.233.96.0/24
163.28.130.0/24
210.242.125.0/24
74.125.204.0/24
163.28.116.0/24
59.18.46.0/24
210.92.119.0/24
74.125.68.0/24
211.239.188.0/24
60.199.175.0/24
203.66.169.0/24
157.197.92.0/24
210.158.146.0/24
61.33.130.0/24
216.58.211.0/24
210.94.153.0/24
59.18.49.0/24
218.219.168.0/24
211.117.39.0/24
216.58.197.0/24
163.28.83.0/24
61.37.150.0/24
203.211.0.0/24
203.248.132.0/24
61.238.239.0/24
203.66.182.0/24
203.233.126.0/24
121.78.42.0/24
58.229.92.0/24
64.233.187.0/24
216.58.203.0/24
172.217.9.0/24
211.239.234.0/24
119.149.187.0/24
202.142.225.0/24
211.49.146.0/24
119.149.188.0/24
64.233.188.0/24
59.18.35.0/24
203.233.37.0/24
61.219.131.0/24
172.217.27.0/24
210.242.128.0/24
163.28.38.0/24
173.194.74.0/24
172.217.23.0/24
61.205.127.0/24
203.233.10.0/24
58.123.102.0/24
163.28.51.0/24
172.217.20.0/24
210.143.70.0/24
58.123.220.0/24
216.58.212.0/24
210.143.147.0/24
172.217.26.0/24
203.248.180.0/24
216.58.199.0/24
118.143.88.0/24
203.211.8.0/24
172.217.16.0/24
203.233.18.0/24
1.255.33.0/24
203.233.92.0/24
216.58.221.0/24
108.177.97.0/24
59.18.34.0/24
64.233.189.0/24
203.66.124.0/24
124.153.255.0/24
74.125.24.0/24
216.58.196.0/24
121.78.206.0/24
202.88.193.0/24
211.1.149.0/24
203.252.15.0/24
74.125.200.0/24
1.255.22.0/24
61.219.146.0/24
121.78.52.0/24
203.233.63.0/24
202.169.173.0/24
216.58.216.0/24
202.208.170.0/24
202.39.143.0/24
202.166.193.0/24
172.217.17.0/24
172.217.11.0/24
123.205.250.0/24
172.217.24.0/24
211.76.107.0/24
203.66.180.0/24
59.18.44.0/24
182.163.240.0/24
124.216.0.0/24
210.242.127.0/24
59.20.132.0/24
211.76.116.0/24
139.175.107.0/24
172.217.25.0/24
202.169.175.0/24
203.66.155.0/24
203.233.88.0/24

**Comment by lybglory** [comment]
哈哈哈，能上啦能上啦！！

**Comment by jzp820927** [comment]
能上什么了？
