### ISSUE TITLE
还有可以用的方法么

### ISSUE THREAD

**Issue by Tindtily** [XX-net/XX-Net#5840]
除了xxnet，还有别的可用的吗？这个估计要废了

**Comment by summerIwinter** [comment]
明明还可以用啊

**Comment by out0fmemory** [comment]
试试这个，https://github.com/out0fmemory/GoAgent-Always-Available

**Comment by jzp820927** [comment]
我能说，其实这个和 XX 没关系，这次 XX 真是背了黑锅了，这其实是 IP 的问题。
只要有 IP，XX 永远都可以用。
可以试试 LS 的方法，换IP，或者调大扫描线程数试试

**Comment by Tindtily** [comment]
是可以了，是证书有问题。但是现在不稳定了。

**Comment by jzp820927** [comment]
不稳定是正常的，不然弄死这么多 IP，不是没啥用麽，只要能用就行了，其他问题就忽略吧
