### ISSUE TITLE
四川电信光宽，50M，持续掉IP

### ISSUE THREAD

**Issue by cdtsuipo** [XX-net/XX-Net#5842]
今天早上开机的时候还是800多IP，十几分钟过去，只剩下300多了，赶紧先关了...

是网络问题，还是3.3.4 的BUG呢？

**Comment by cdtsuipo** [comment]
刚才用来下载东西，开了一会儿，发现没有流量，IP就不掉。有流量，IP就哗哗的掉，这是被盯上了么

**Comment by AndyLau2017** [comment]
.........。。。。那么多issues都不看，就发新帖了？那我知道也不告诉你了。

**Comment by cdtsuipo** [comment]
我翻遍了也没看到有解决办法，没解决办法你说个鸟鸟，不说就不说呗。用个软件还这么高傲

**Comment by AndyLau2017** [comment]
@cdtsuipo  说得好像全世界人都要为你服务一样，既然没看到解决办法，那就是暂时没解决办法呗，这都不懂，用个免费软件，搞得好像要有专业客服给你服务一样。

**Comment by cdtsuipo** [comment]
@AndyLau2017 我只是来打探下消息而已，用得着冷嘲热讽的么？我是吃你谷子还你糠了还是怎么得？不想回复就闭嘴好么？显得你能是怎么得？

**Comment by jzp820927** [comment]
贴日志出来看看
