### ISSUE TITLE
掉ip和宽带运营商有关系吗

### ISSUE THREAD

**Issue by djfruewe** [XX-net/XX-Net#5846]
用联通网ip数量1400多 切换到移动宽带ip数量立马掉到13

**Comment by roc1010kmt** [comment]
你怎麼裝了兩個網線？

**Comment by AndyLau2017** [comment]
你这不是废话吗，发帖之前看看新帖，ok?

**Comment by jzp820927** [comment]
差不多吧，目前据反映，就 移动，和联通，最好，电信最差。

**Comment by trdmm** [comment]
还有地区

**Comment by gmvp3** [comment]
移动完蛋啦？

**Comment by out0fmemory** [comment]
试试这个，https://github.com/out0fmemory/GoAgent-Always-Available

可以直接用或者把里面的可用的ip导入到xx-net，作为种子ip，这两天应该勉强可用，最近确实ip很少而且被封的太快了。。。。。。。

**Comment by jzp820927** [comment]
谁说移动完蛋了？

**Comment by maidouexo** [comment]
怎么导入IP到XXNET?

**Comment by jzp820927** [comment]
浏览器打开 127.0.0.1：8085，在高级里面，有导入 IP
