### ISSUE TITLE
重新部署服務端能翻墻了

### ISSUE THREAD

**Issue by lybglory** [XX-net/XX-Net#5847]
- end_time_usec: 1498227456098000
path: /api/appversion/getresourcelimits
request_size_bytes: 0
response_code: 200
start_time_usec: 1498227454941000
- end_time_usec: 1498227457478000
path: /api/appversion/create
request_size_bytes: 521
response_code: 200
start_time_usec: 1498227456274000
- end_time_usec: 1498227460342000
path: /api/appversion/clonefiles
request_size_bytes: 276
response_code: 200
start_time_usec: 1498227457501000
- end_time_usec: 1498227461206000
path: /api/appversion/precompile
request_size_bytes: 0
response_code: 200
start_time_usec: 1498227460371000
- end_time_usec: 1498227464549000
path: /api/appversion/deploy
request_size_bytes: 0
response_code: 200
start_time_usec: 1498227461240000
- end_time_usec: 1498227465272000
path: /api/appversion/isready
request_size_bytes: 0
response_code: 200
start_time_usec: 1498227464571000
- end_time_usec: 1498227466862000
path: /api/appversion/startserving
request_size_bytes: 0
response_code: 200
start_time_usec: 1498227465315000
- end_time_usec: 1498227471277000
path: /api/appversion/isserving
request_size_bytes: 0
response_code: 200
start_time_usec: 1498227466881000
runtime: python27
sdk_version: 1.9.33
start_time_usec: 1498227454886000
success: true

2017-06-23 22:17:52,193 - root - INFO - Done!
2017-06-23 22:17:52,223 - root - INFO - =======================
2017-06-23 22:17:52,253 - root - INFO - Deploy 10 appid successed.
2017-06-23 22:17:52,260 - root - INFO - == END ==

**Comment by RuthlessVillain** [comment]
现在的主要问题是 IP 数量严重不足啊，重新部署真的有用处吗？

**Comment by lybglory** [comment]
@RuthlessVillain 我也不知大抽了什麽風，之前一直翻墻不了，連google都上不了。重新下了xxnet，重新部署服務端會掃描IP。然後就好了。。。。

> 属性	值
> 总IP数	14186
> 剩余数	0
> 有效IP数	5989

**Comment by AndyLau2017** [comment]
你用什么宽带？

**Comment by lybglory** [comment]
@AndyLau2017 用的是聯通寬帶

**Comment by AndyLau2017** [comment]
看来联通和移动受影响确实不如电信严重，电信太坑

**Comment by jzp820927** [comment]
IP 和 服务端没有任何关系，这个就是碰巧了。

**Comment by trdmm** [comment]
@AndyLau2017  移动表示并不是你说的那样

**Comment by gmvp3** [comment]
上海移动的完全不行了

**Comment by Flytheshrimp** [comment]
为了重新部署服务端，我把psiphon打开了，用VPN部署VPN

**Comment by AndyLau2017** [comment]
@Flytheshrimp 那你成功没

**Comment by jzp820927** [comment]
@trdmm 重点地域可能会重点监控
@gmvp3 普通方法不行，可以考虑特殊方法，天天大陆通罗马
@Flytheshrimp 不用这么麻烦，用 SS 也可以部署服务端。而且用 VPN 部署 VPN 是什么意思？

**Comment by Flytheshrimp** [comment]
重新部署了服务端都是徒劳，只能先用着Psiphon3赛风替代了

**Comment by jzp820927** [comment]
服务端是不用反复部署的，重点是 IP，只要有 IP 就能用。

**Comment by Flytheshrimp** [comment]
我这里有1300+个IP，照样“尚未建立连接”“网络状态：Unknown”

**Comment by jzp820927** [comment]
我觉得那 1300 个 IP，可能是僵尸 IP，你可以试试 重新扫描所有 IP

**Comment by lybglory** [comment]
@Flytheshrimp 抱歉哈。。。我的情况是突然不能翻墙，IP不足，然后把xxnet删除了，重新下载。重新部署服务器。第一次部署失败；第二次部署之前我改了IPV4的DNS改为自动获取。然后就好了。。可能真如 @jzp820927 大神说的，我碰巧而已。。。

**Comment by AndyLau2017** [comment]
难道你之前的DNS不是自动获取的？

**Comment by Flytheshrimp** [comment]
Fuck!一检查所有IP，可用IP数量直线下降，cao!

**Comment by lybglory** [comment]
@AndyLau2017 之前一直是自动的，不知道什么什么时候变成了手动DNS，估计是xxnet不能翻墙那会儿，我尝试过用goagent方法(这个没有用)，它搞成了手动DNS。。按理来说有可用IP数量，部署服务端基本上能成功。。

**Comment by lybglory** [comment]
@Flytheshrimp 可用数量虽然在下降，但能翻。。我之前5000多可用数量，一会儿下降到五六十。过一会儿又能飙回几百。。。

**Comment by Flytheshrimp** [comment]
"XX-net 3.3.1 一切正常“ 
Youtube:504 GAEProxy Time Out
Google:504 GAEProxy Time Out

**Comment by gmvp3** [comment]
GFW升级了，GAE彻底完了

**Comment by Flytheshrimp** [comment]
IP数量：9
连接池：新：1 h1:0 h2:11
无法翻墙
于2017.6.24 19:13

**Comment by Flytheshrimp** [comment]
延迟太高，导致超时，还是我的赛风好，虽然不能看高清视频，但是720p还算可以

**Comment by gmvp3** [comment]
@Flytheshrimp
赛风给个地址下载啊，我下载的怎么都是128版本的

**Comment by Flytheshrimp** [comment]
http://psiphon.cn.uptodown.com/
若无法访问（被墙），请发送邮件至get@psiphon3.com

**Comment by gmvp3** [comment]
邮件有回复，但是给我的都是128版本的，你是吗？

**Comment by Flytheshrimp** [comment]
我的是128版本

**Comment by Flytheshrimp** [comment]
喜大普奔！XX-net已可以访问维基百科简体中文版，但是Google和Youtube仍然处于无法访问状态（504超时）

**Comment by lybglory** [comment]
![xxnet](https://user-images.githubusercontent.com/28734075/27508548-2b2df2f8-591a-11e7-991c-92d238344258.PNG)

**Comment by jzp820927** [comment]
@Flytheshrimp 关于 504超时 的问题，处理方法很简单，设置规则走 GAE 就可以了。

**Comment by gmvp3** [comment]
@jzp820927
赛风运行了，无法连接上服务器，上海移动牛逼了

**Comment by jzp820927** [comment]
没这么严重吧，你那儿有能用的功能嘛？要不你试试 SS？我就不信 上海移动能把 SS 都封了

**Comment by gmvp3** [comment]
目前蓝灯还正常

**Comment by jzp820927** [comment]
那就用蓝灯吧，确实蓝灯也算是经典工具了，不过现在免费的限制流量，限制带宽了。

**Comment by tq01o3n** [comment]
@jzp820927 怎么扫描IP？

**Comment by mikedchavez1010** [comment]
自文贵爆料以来，ＸＸ－Ｎｅｔ应该是被重点关照了，因为它还是免费工具中重要的一个。

是不是管理界面的“高级”--“检查IP”？＠tq01o3n 

＠jzp820927　蓝灯的性能还是非常不错的。在ｗｉｆｉ环境上，可在lantern命令后添加参数--addr 0.0.0.0:8787（Windows下可创建快捷方式后添加），其它设备使用代理模式（运行lantern机器的IP地址，端口8787），这样就可以在局域网环境下共享lantern了，也就支持了iPhone/iPad，突破了专业版只能绑定3台设备的限制。

**Comment by AndyLau2017** [comment]
【管不好网络，提头来见】，某人亲自下令管理网络，你觉得呢？

**Comment by jzp820927** [comment]
@tq01o3n XXNET 是自动扫描 IP 的，不用手动控制。
@mikedchavez1010 lantern 的免费版不是有流量限制麽？
