### ISSUE TITLE
搬瓦工上搭建的xx-net为啥用不了？

### ISSUE THREAD

**Issue by taocunguijs** [XX-net/XX-Net#5853]
之前搭建的ss，到了晚上就不给力，想看看xx-net效果如何，但是跑起来，国内手机还是用不了，配置方法同电脑分享给手机的方法。

**Comment by taocunguijs** [comment]
家里网络无公网ip

**Comment by taocunguijs** [comment]
可以通过8085访问配置页面

**Comment by SeaHOH** [comment]
搬瓦工本身不给力吧，搭什么都没用。

**Comment by taocunguijs** [comment]
我在美国服务器搭不可能不给力吧，ip理论上都有效吧

**Comment by taocunguijs** [comment]
可以ping通服务器ip

**Comment by SeaHOH** [comment]
搬瓦工本身给用户的带宽有限，本来就是便宜货。

**Comment by taocunguijs** [comment]
好吧

**Comment by wz7465** [comment]
原理都没搞清，xx-net要搭在国内服务器上才有用

**Comment by SeaHOH** [comment]
其实搭在哪儿都可以，只要服务器支持，只不过国外用不着而已。但是搬瓦工不太合适，可能有并发限制，影响扫描，虽说用不着。

**Comment by wz7465** [comment]
xx-net真正的服务端始终在gae，在搬瓦工上搭建的其实是“客户端”而已，本机连接“客户端”是不加密的，“客户端”在国外，意味穿墙的是明文，明文怎么能通过gfw？如果搭在国内服务器上，国内服务器--gae是加密连接，才能穿墙。

**Comment by SeaHOH** [comment]
http 代理一直是可用的，只是对非加密流量有关键词过滤，如果你访问的网址没有被过滤是可以穿墙的。

**Comment by wz7465** [comment]
是可用啊，但是你只能访问那些非屏蔽网站，比如github，这种http代理没有意义啊，我不用也是这样

**Comment by SeaHOH** [comment]
>只是对非加密流量有关键词过滤

XX-Net 也支持加密流量

**Comment by wz7465** [comment]
XX-Net 也支持加密流量只是在“客户端”---加密---gae这一段上，所以必须保证架构上 “客户端”---墙（加密）---gae这种形式才有效
但是若把客户端架设在搬瓦工上，就是这种形式：本机---墙---“客户端”--加密--gae
本机---墙---“客户端”是不加密的，所以无法有效穿墙。

**Comment by SeaHOH** [comment]
非也，你 https 网址走 XX-Net 就是加密流量，不然安装 XX-Net 的证书干嘛用，就是搞定加密的。

**Comment by wz7465** [comment]
证书只是用来欺骗浏览器的，xx-net本身的流量并不用证书来加密，而是应该用自身的加密方式

**Comment by SeaHOH** [comment]
算了，不跟你讲了。

**Comment by taocunguijs** [comment]
还是多谢楼上各位解答，最终还是放弃这种想法直接架个ss算了

**Comment by wz7465** [comment]
@SeaHOH  我觉得你认识上还有误区，或许是我的误区，希望其他人来探讨探讨

**Comment by jzp820927** [comment]
@taocunguijs XXNET 搭建在国外服务器确实意义不大。不知道你的 BWG 有没有做过优化？服务器是选的哪个位置的？是 VZ 的？还是 kvm 的？

**Comment by taocunguijs** [comment]
做过bbr加速优化，服务器在洛杉矶，open vz, 只有晚上用着不行，白天没啥问题，晚上家里宽带 xx-net gfw.press 搬瓦工ss都不给力，晚上用数据网络连接ss一点问题没有

**Comment by taocunguijs** [comment]
还是isp网络干扰太严重，搞不懂对ss怎么做的干扰

**Comment by taocunguijs** [comment]
国内中转有啥教程不？家里网络没公网ip

**Comment by jzp820927** [comment]
问你，你家里是什么 ISP？

**Comment by taocunguijs** [comment]
宽带通

**Comment by wz7465** [comment]
@SeaHOH 我重新考虑了一下，觉得表述上还有些误区，重新梳理一下
无代理下，我们访问https网站，比如github，访问请求是可见的（gfw知道你访问了github），访问内容是不可见的（gfw无法知道你访问了github网站上的什么内容，因为内容被证书加密），gfw不去关心你访问什么内容，它只分析你的请求，如果你请求访问的是facebook，那么就屏蔽
xx-net客户端放在国外服务器上，其实质就是一个http代理，因此访问请求依然可见
xx-net客户端放在国内服务器上或本机上，其实质就是一个https代理，连访问请求都是加密的，gfw无法得知你访问哪些网站，也就无法屏蔽了
------
先前的表述中有如下问题，http代理虽然跑的是http流量，但是其中也包含https流量，不能简单的说http流量就是明文流量
xx-net访问https网站，最后一环是需要导入证书的，虽然是伪造的证书，但流量应该还是https流量，这点我可能认识有误，但这https流量应该只是内容的加密，不涉及请求

**Comment by SeaHOH** [comment]
我能说，墙拦截大部分网站根本就不是通过检测请求的网址么。

**Comment by wz7465** [comment]
这么说当然是行的通了，毕竟墙拦截的方式是多样，不是一种途径，但是把xxnet架设到bwg这种方式，显然给墙多留了条口子

**Comment by wz7465** [comment]
@SeaHOH  延伸开来的不说，只说结果
xxnet架设到国内服务器上，等同于在本地机上打开客户端，其结果是能访问facebook，twitter这类https网站
xxnet架设到bwg上，则不能访问，它只能访问非屏蔽的github网站
你认同这个结论吗？

**Comment by kirbyzhu** [comment]
真理越辩越明 不过还有一句话是 实践是检验真理的唯一标准 
so……

**Comment by wz7465** [comment]
是啊，试试看就知道了

**Comment by SeaHOH** [comment]
其实，我说两个例子你就明白了：
* 某些网站，http 无法访问，https 确可以；
* 某些网站 https 也无法访问，但是使用某些 hosts 或者 DNS 就能访问。
以上操作均无需任何代理软件。

**Comment by SeaHOH** [comment]
其实，XX-Net 搭在国外，会有部分 http 网站和 http 网址关键词以及**极少数 https 网站**被屏蔽。

**Comment by wz7465** [comment]
http 无法访问，https 确可以---应该可以解释为有些网站强制使用https，http会自动跳转到https模式
hosts方式----访问https网站的请求直接在本机就处理了，请求不出墙，墙也没办法封吧
个人理解

**Comment by SeaHOH** [comment]
非也
>http 无法访问，https 确可以---应该可以解释为有些网站强制使用https，http会自动跳转到https模式

有些被封网站支持 http 和 https 两种方式访问。
>hosts方式----访问https网站的请求直接在本机就处理了，请求不出墙，墙也没办法封吧

访问请求是真正到了对方的网页服务器，而且是直接。

**Comment by SeaHOH** [comment]
@wz7465 
其实能跟你讨论，我是很开心的啦。XX 这边小白太多，而且大多数还无视别人的帮助和建议（一不小心开了群嘲~会不会被扁），所以看到你能够用自己的思考理智地跟我讨论，我非常欢迎。以后还有什么其它问题，也可以大家一起研究讨论。 :smile:

**Comment by SeaHOH** [comment]
@wz7465 
其实能跟你讨论，我是很开心的啦。XX 这边小白太多，而且大多数还无视别人的帮助和建议（一不小心开了群嘲~会不会被扁），所以看到你能够用自己的思考理智地跟我讨论，我非常欢迎。以后还有什么其它问题，也可以大家一起研究讨论。 :smile:

**Comment by wz7465** [comment]
也许我表述的不够准确，访问一个网站比如https://google.com 其标准的过程是先通过dns进行域名解析，然后得到一个类似75.24.*.*的ip地址，解析的过程对gfw来说是一个暴露的过程，在这个过程中，直接给咔嚓了，返回一个错误的地址，用hosts方式等于省缺这一环节，对gfw来说，它只知道你连接上一个ip，干什么它不知道，但是如果这个ip在黑名单上，那么继续咔嚓掉

**Comment by wz7465** [comment]
我不是要争个高下，争个对错，确实是探讨一下，你不要担心会打击到我

**Comment by wz7465** [comment]
@SeaHOH  谢谢回复，我觉得可以暂时告一段落

**Comment by SeaHOH** [comment]
没问题~

现代浏览器访问 https 网站，链接握手的时候会附带 SNIServerName，这个是被访问网站域名的明文，墙可以看到。

**Comment by wz7465** [comment]
多谢指教

**Comment by SeaHOH** [comment]
不客气

**Comment by jzp820927** [comment]
@taocunguijs 宽带通 感觉很老火啊。VPS 可以搭建的方案有很多种，最方面的可能就是 SS了吧。
至于中转，最简单的，就是前置代理了。或者你有国内服务器，可以搭建更高级的中转，不过成本就比较高了。
