### ISSUE TITLE
问个非网络方面的问题，xx页面字体不正常。。。

### ISSUE THREAD

**Issue by pengweipro** [XX-net/XX-Net#5856]
用的manjaro-xfce-17.01，xx版本3.3.1，
在Firefox和Vivaldi浏览器中打开xx的设置页面，文字都很细，而其他的网站都没这样。
因为linux新手，所以总把系统弄崩，没几天就重做一次，（没备份，当练习了）
然而还是头一次遇见这问题，改系统默认字体也没有效果，况且以前也没改过字体...
![_2017-06-24_15-51-54](https://user-images.githubusercontent.com/29443123/27506911-552794fc-58f6-11e7-80f9-eca67ac63f88.png)
![_2017-06-24_15-52-36](https://user-images.githubusercontent.com/29443123/27506915-625f5920-58f6-11e7-9c50-4424f35a2e65.png)

**Comment by jzp820927** [comment]
要不系统字体问题，要不浏览器问题，如果修改系统字体无效，就试试换个浏览器
