### ISSUE TITLE
可用ip不多但是速度还行

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#5861]
可用的ip只有30上下......延迟600左右.......但是能用了，看youtube视频720p不卡（似乎YouTube视频的服务器没有被墙？不像是在走gae的样子，经常是界面加载不出但是视频能正常加载）
之前完全上不去，解决的方法是往manual.ini里面加上下面几行：
.google.com = gae
.youtube.com = gae
.ytimg.com = gae
现在就可用了

**Comment by jzp820927** [comment]
youtube 是 100% 早就被墙的，那只是你的错觉。
