### ISSUE TITLE
有没有安卓和ios可以使用的免费代理方式

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#5862]
由于xxnet给移动端用实在不方便而且gae的局限性很大，打算在移动端上使用其他的代理方式
以前尝试过免费的vpn服务（vpngate什么的），但是基本都用不了......
如果没有的话，能不能通过国外服务器上的域名架一个？

**Comment by Ninfiver** [comment]
你可以租借低价vps，自己搭建.....
其实移动端免费的vpn还是有的，拿ios来说，whalevpn每日签到可以累积，天行.非凡也都凑合能用,,,
至于ss，就很方便了，现在免费ss帐号一大把，你只需稍稍花点时间就能找到...不过值得一提的是很多ss站付费的ss服务都声明不能用来进行bt下载和p2p..这是为何，望诸君解惑

**Comment by jzp820927** [comment]
版权问题，国外版权管理很严格。

**Comment by iambonboncat** [comment]
ios现在上vpn挺麻烦的

**Comment by jzp820927** [comment]
不是刚刚才看到有消息说，所有移动端的 为皮恩 apps 全部都要下架了吗？这个就不是免费的问题了，而是不可用了。

**Comment by iambonboncat** [comment]
很多vpn已经不行了。手机版xxnet一直没动静啊！

**Comment by jzp820927** [comment]
XXNET 已经停止开发了，你要指望手机版 XXNET 了，除非有人接手开发。

**Comment by loveybaby** [comment]
[ios方法](https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6)

[安卓方法](https://github.com/greatfire/wiki)
