### ISSUE TITLE
无法在推特验证手机号

### ISSUE THREAD

**Issue by Temmie-hOi** [XX-net/XX-Net#5875]
输入验证码提交之后显示“Due to a technical issue, we couldn't complete this request. Please try again.”无法进行验证，重复了还是这样
现在没法用Twitter，一进去就要求验证手机号

**Comment by Temmie-hOi** [comment]
@jzp820927

**Comment by jzp820927** [comment]
应该是 twitter 的原因吧，估计得问问 twitter 的技术支持了。

**Comment by Temmie-hOi** [comment]
@jzp820927 有什么能换呢......vpn都要被封了，xtunnel能用吗

**Comment by dou4cc** [comment]
可以跳过手机号验证

**Comment by Temmie-hOi** [comment]
@dou4cc 怎么跳过呢

**Comment by jzp820927** [comment]
或者可以试试 xtunnel 吧。
