### ISSUE TITLE
能翻墙，可打开Google主页，但无法搜索

### ISSUE THREAD

**Issue by fisher251** [XX-net/XX-Net#5876]
XX-NET状态一切正常，测试能上推特能上YouTube，但Google有时无法搜索
主页www.google.com会自动转到https://www.google.com.hk/?gws_rd=ssl，输入搜索关键词后网址变了但是网页部分没反应一直是Google搜索的起始页面，有时等待很长一段时间后会504

**Comment by SeaHOH** [comment]
https://www.google.com/ncr 解决跳转问题

**Comment by fisher251** [comment]
@SeaHOH 感谢，已解决
