### ISSUE TITLE
检查浏览器代理设置

### ISSUE THREAD

**Issue by hahahaxixixihehehe** [XX-net/XX-Net#5889]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2988
network-status: unknown
connected-link: new:0 used:0
worker: h1:9 h2:5
scan-ip-thread-num: 16
ip-quality: 66
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 330128615** [comment]
遇到相同问题，不能翻墙了

**Comment by hahahaxixixihehehe** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2834
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 28
ip-quality: 158
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
升级后依旧存在

**Comment by whhxmwhh** [comment]
郭总放毒

**Comment by jzp820927** [comment]
先升级到 3.3.4 ，然后 #5322
