### ISSUE TITLE
怎么我把XX-NET带的IP列表替换了还显示原来的IP总数

### ISSUE THREAD

**Issue by beimunizhou** [XX-net/XX-Net#5895]
网上找了新IP，嫌之前的ip影响扫描速度直接把它换成自己找到的ip，结果还是显示原来的ip数 在慢慢扫描

**Comment by beimunizhou** [comment]
没事了，虽然显示那个IP总数不过扫描速度比原来快了几倍，刚扫完 看油管720P也不卡顿

**Comment by lanlingsheng** [comment]
看720p ，扎心了兄弟，能不能共享下 ip 啊，很急，我连网页都打不开

**Comment by jzp820927** [comment]
很多 issues 不是有分享 IP 的项目嘛，可以搜索下

**Comment by lanlingsheng** [comment]
导入1万2千多个ip， 扫完只有 3个

**Comment by jzp820927** [comment]
太夸张了，你是 什么 地方？什么 ISP？封锁这么厉害？
