### ISSUE TITLE
批量部署多个appid的时候最多只能3个到第4个就不卡死了

### ISSUE THREAD

**Issue by zhouhao1217** [XX-net/XX-Net#59]
然后到状态页面就一片空白

**Comment by xxnet** [comment]
请试试最新版本 1.3.1。
网络丢包高的时候，老版本会卡死，没有超时机制。
新版本加了超时机制，并且重试最多10次。
我测试丢包10%的情况下还可以正常完成。

时间久一点，但总是可以自动上传就好了。

**Comment by xxnet** [comment]
1.7版解决了部署问题
