### ISSUE TITLE
明天起全面禁用VPN，对本科学上网软件有影响吗？

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#5900]
如题。

**Comment by a13821190779** [comment]
我的好久之前就不稳定了－ － 不知道什么原因

**Comment by Goooooollum** [comment]
年初就开始了，现在依然潇洒

**Comment by WLZLCX** [comment]
年年有影响，年年仍在用

**Comment by EliteOtaku** [comment]
小道消息…… 七月一日开始大范围封封墙服务器，八月一日起不让一个梯子出墙。常去的几个论坛纷纷自我阉割

**Comment by cqzan** [comment]
常用的手机翻墙app  green今天不能用了。。

**Comment by Rodney2012** [comment]
这个事情肯定会导致数款VPN失效

**Comment by jzp820927** [comment]
不知道从哪儿来的消息

**Comment by farshidvahid** [comment]
@jzp820927
传 VPN 应用明日起将全面禁止，安卓、苹果无一幸免
 http://news.ifeng.com/a/20170630/51351260_0.shtml

**Comment by iambonboncat** [comment]
xx net youtube和google也不行了。

**Comment by jzp820927** [comment]
@farshidvahid 这个有点夸张了，root 后的苹果可以 ipk，android 也可以直接 apk，这个是封不死的，能封的只有商店。而且 google play 中国ZF也管不到，这个是封不掉的。估计封的都是国内的 apps store 吧。

**Comment by Goooooollum** [comment]
App Store目前一切正常

**Comment by medmin** [comment]
ss呢？

**Comment by jzp820927** [comment]
android 基本上不会受到影响。
