### ISSUE TITLE
xxnet 代码 研究 建议

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#5911]
Hi 各位 大神，

用 xxnet 很久了， 想好好研究下 其代码， 但是不想走弯路，
能否 给些 研究 xxnet 代码 的 建议， 可以用 最少的时间 能达到 比较熟悉的 程度。

**Comment by SeaHOH** [comment]
你是想开发新功能吗？

**Comment by jzp820927** [comment]
估计你要先学习 python 基础吧

**Comment by SeaHOH** [comment]
楼主还是有基础的，以前就提过。

**Comment by kuchaguangjie** [comment]
@SeaHOH 先熟悉下, 如果能开发, 当然 愿意 开发.

**Comment by kuchaguangjie** [comment]
@jzp820927 python 语法 超简单, 以前也用过, 不是很大的问题.

**Comment by SeaHOH** [comment]
想加新功能：
```
config.py                    #配置
proxy_handler.py   #处理请求
gae_handler.py       # GAE 请求
direct_handler.py   #直连
```
近期可能需要改进：
```
check_ip.py 和 openssl_wrap.py  #扫描方法
check_local_network.py                  #网络检查
```

**Comment by GitKKg** [comment]
留名，做个记录

**Comment by kuchaguangjie** [comment]
@SeaHOH Ok, 我先抽空熟悉下, 谢谢.

**Comment by jzp820927** [comment]
@kuchaguangjie 既然对 py 很熟悉，只要了解一些网络基础，应该就可以开发了，而且还是在 XX 基本上开发，就更容易了。

**Comment by kuchaguangjie** [comment]
@jzp820927 接手 不敢啊, 责任重大呀, 业余爱好 研究着 先吧, 走一步看一步吧, 呵呵.

**Comment by jzp820927** [comment]
有人开发，总比没人开发好吧。
就算不接手，能处理下 bug，做下日常维护也不错。

**Comment by kuchaguangjie** [comment]
这几个文件有要开发的东西么?

* check_ip.py 和 openssl_wrap.py		# 扫描方法
* check_local_network.py			# 网络检查

好像 没看到 哪里有说需求的事情.

**Comment by SeaHOH** [comment]
都是个人感受
* 现在的扫描方法并不精准，有错漏，缺乏验证（可通过内置 IP 段规避部分风险），不太适应现在的严峻形式。
* 网络检测使用的方法也不太合适，容易受干扰，[这个通过 DNS 的检测方法](https://github.com/SeaHOH/GotoX/blob/master/local/ProxyServer.py)，我觉得更加准确、通用和有效率，可以参考。
* 直连模式没有区分 GWS 和 GVS，有部分服务会出错，通过走 GAE 可以缓解，所以不添加区分功能也可以凑合着用，毕竟改起来很麻烦，但是修复后能够有效减少 issues 数量。
* 其它各种小问题也比较多，但影响都不大，就是小白太多不知道如何处理，又不查看过往 issues 和 Wiki。

**Comment by jzp820927** [comment]
一针见血
