### ISSUE TITLE
换了APPID又出问题

### ISSUE THREAD

**Issue by a1751874251** [XX-net/XX-Net#5930]
属性	值
本地网络状态	OK
IP数量	1
空闲	0
IP延迟	9999
连接池(帮助)	新:0 h1:0 h2:1
浏览器代理设置	OK
CA证书状态(下载)	OK
扫描IP线程数(设置)	39
屏蔽状态(帮助)	OK
配置

属性	值
监听代理	127.0.0.1:8087
PAC自动代理地址	http://127.0.0.1:8086/proxy.pac
IPv6	禁用
Appid

属性	值
当前工作AppID	
系统版本

属性	值
XX-Net Version	3.3.4
Python Version	2.7.13
OpenSSL Version	16.0.0 TLSv1_2 h2:alpn
System Platform	AMD64, Windows-7-6.1.7601-SP1
OS System	Windows
OS Version	6.1.7601
OS Release	7
OS Detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36[](url)

**Comment by jzp820927** [comment]
你这个不是 appid 的问题，是 IP 的问题，没有可用 IP。调大扫描线程数看看有没有作用。
