### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by hzj-777** [XX-net/XX-Net#5935]
Jul 03 22:33:49.830 - [DEBUG] report_connect_fail network fail
Jul 03 22:33:49.830 - [DEBUG] get ip:106.162.216.122 t:233
Jul 03 22:33:50.096 - [DEBUG] 203.233.126.249 fail:timeout('timed out',)
Jul 03 22:33:50.096 - [DEBUG] report_connect_fail network fail
Jul 03 22:33:50.096 - [DEBUG] get ip:111.86.157.142 t:233
Jul 03 22:33:50.648 - [DEBUG] 216.58.197.249 fail:timeout('timed out',)
Jul 03 22:33:50.648 - [DEBUG] report_connect_fail network fail
Jul 03 22:33:50.648 - [DEBUG] get ip:106.162.216.87 t:233
Jul 03 22:33:50.688 - [DEBUG] 220.255.5.247 fail:timeout('timed out',)
Jul 03 22:33:50.688 - [DEBUG] report_connect_fail network fail
Jul 03 22:33:50.689 - [DEBUG] get ip:182.248.204.90 t:248

用WIFI连接xxnet不可用，网线连接没问题。WIFI连接国内网站可以访问，WIFI和网线连接的是不同网

**Comment by hzj-777** [comment]
本地网络状态unkonwn

**Comment by chenzijng** [comment]
我这种情况有一段时间了，但是之前一直在使用也没有问题。但是今天就是有一点问题了，一直是尚未链接。

**Comment by jzp820927** [comment]
是最新版的 XXNET 吗？不同的 ISP 的封锁程度也不一样的。这个没办法。

**Comment by chenzijng** [comment]
是最新版本，有时能用，有时不能用。ip 比较少，有时候能打开twitter，facebook，就是Google的全部不能打开，全是504.

在 2017-07-10 18:54:20，"天朝屁民" <notifications@github.com> 写道：


是最新版的 XXNET 吗？不同的 ISP 的封锁程度也不一样的。这个没办法。

**Comment by jzp820927** [comment]
504 应该是直连造成的，改下规则，走 GAE 试试
