### ISSUE TITLE
ip數量只有兩個！

### ISSUE THREAD

**Issue by wsjzjt** [XX-net/XX-Net#5936]
我用的是3.3.1的穩定版，為什麼ip數量只有兩個？你們都是這樣嗎？

**Comment by wsjzjt** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2 good:2
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:3
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Eri5Ch** [comment]
刚看了一眼 还剩20多个 是使用这个以来数量最少的时候

**Comment by wsjzjt** [comment]
我才发现是因为更新了334测试版，现在还原成331就慢慢变成2500多个了

**Comment by jzp820927** [comment]
意思是说，从 3.3.4 降级到 3.3.1，IP 数量就变多了？这个确实挺奇葩的。没遇到过类似问题。
