### ISSUE TITLE
求助 今天上不了https://www.google.com/?hl=zh，谷歌学术也不行，流量异常(附日志)

### ISSUE THREAD

**Issue by uhiu** [XX-net/XX-Net#5954]
今天突然抽风上不去google，我自己弄了半天，现在能好像能上了，但是速度很慢。
求大神帮忙看一下是出了什么问题吗，如何解决？跪谢...

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2996 good:595
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:3
scan-ip-thread-num: 50
ip-quality: 183
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by uhiu** [comment]
上不了谷歌学术，根本不打开。打开台湾的额谷歌学术显示流量异常
![image](https://user-images.githubusercontent.com/29622719/27903422-d574f824-626b-11e7-9014-3f9ef12c2aef.png)

**Comment by jzp820927** [comment]
至于速度慢，先忍忍吧，我想说，现在很多人连用都用不了，能用已经很不错了。看以后会不会慢慢放宽封锁再找对策。
至于谷歌学术，看样子是必须走直连了，但是现在干扰厉害，直连模式又很容易失效，这确实是个两难的问题。或者你先试试直连行不行吧，不行再想其他办法
