### ISSUE TITLE
开机出现这个提示

### ISSUE THREAD

**Issue by xiaodaowanwan** [XX-net/XX-Net#5958]
![qq 20170706195539](https://user-images.githubusercontent.com/12395889/27909866-4c9b4db8-6285-11e7-8799-ac23650c2f6c.png)

**Comment by zanewayne78** [comment]
.NET Framework 4.6.2重新安装？具体到Shadowsock那边问问

**Comment by jzp820927** [comment]
SS 的问题，你跑到 XXNET 来提问，不太合适吧？
建议你去 SS 那边提问。

**Comment by xiaodaowanwan** [comment]
Sorry,我错了，打扰了。
