### ISSUE TITLE
XX-NET GAE 与youtube-dl无法同用

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#5964]
输入命令
`youtube-dl -F --proxy 127.0.0.1:8087 --no-check-certificate  https://www.youtube.com/watch?v=XqLLxaJPabU`

> [youtube] XqLLxaJPabU: Downloading webpage
> ERROR: Unable to download webpage: HTTP Error 504:  (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

xx-net的日志:
> 
> 7月 07 18:55:41.84 - [INFO] GAE CONNECT www.youtube.com:443 
> 7月 07 18:55:41.86 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:661), create full domain cert for host:www.youtube.com
> 7月 07 18:55:45.00 - [DEBUG] ip:201.157.30.169 real fail
> 7月 07 18:55:50.01 - [DEBUG] ip:210.143.147.36 real fail
> 7月 07 18:55:52.18 - [DEBUG] restore ip:80.97.208.104
> 7月 07 18:55:56.65 - [INFO] GAE CONNECT www.youtube.com:443 
> 7月 07 18:55:56.66 - [DEBUG] GAE CONNECT Direct GET https://www.youtube.com/watch?v=XqLLxaJPabU&gl=US&hl=en&has_verified=1&bpctr=9999999999
> 7月 07 18:55:57.18 - [DEBUG] ip:201.157.30.141 real fail
> 7月 07 18:56:02.19 - [DEBUG] ip:61.91.8.80 real fail
> 7月 07 18:56:07.19 - [DEBUG] ip:209.191.218.180 real fail
> 7月 07 18:56:12.20 - [DEBUG] ip:189.247.146.37 real fail
> 7月 07 18:56:13.00 - [DEBUG] get ip:203.233.96.15 t:178
> 7月 07 18:56:13.46 - [DEBUG] create_ssl update ip:203.233.96.15 time:267 h2:0
> 7月 07 18:56:13.46 - [DEBUG] get ip:202.28.85.161 t:399
> 7月 07 18:56:13.61 - [DEBUG] ssl_closed 113.171.242.238
> 7月 07 18:56:13.61 - [DEBUG] 113.171.242.238 worker close:GoAway: additional_data:session_timed_out
> 7月 07 18:56:14.48 - [DEBUG] ssl_closed 202.86.162.172
> 7月 07 18:56:14.48 - [DEBUG] 202.86.162.172 worker close:GoAway: additional_data:session_timed_out
> 7月 07 18:56:15.37 - [WARNING] head send len:None 49
> 7月 07 18:56:17.20 - [DEBUG] ip:83.139.106.228 real fail
> 7月 07 18:56:17.47 - [DEBUG] 202.28.85.161 fail:timeout('timed out',)
> 7月 07 18:56:17.47 - [DEBUG] report_connect_fail:202.28.85.161
> 7月 07 18:56:17.47 - [DEBUG] get ip:202.86.162.172 t:195
> 7月 07 18:56:17.72 - [DEBUG] create_ssl update ip:202.86.162.172 time:174 h2:1
> 7月 07 18:56:22.21 - [DEBUG] ip:58.27.27.214 real fail
> 7月 07 18:56:27.21 - [DEBUG] ip:90.201.124.102 real fail
> 7月 07 18:56:30.70 - [DEBUG] restore ip:203.176.178.48
> 7月 07 18:56:35.70 - [DEBUG] ip:194.24.134.158 real fail
> 7月 07 18:56:40.71 - [DEBUG] ip:88.217.135.23 real fail
> 7月 07 18:56:45.71 - [DEBUG] ip:190.92.89.49 real fail
> 7月 07 18:56:50.71 - [DEBUG] ip:120.28.12.181 real fail
> 7月 07 18:56:55.72 - [DEBUG] ip:189.247.134.81 real fail
> 7月 07 18:57:00.72 - [DEBUG] ip:188.43.68.208 real fail
> 7月 07 18:57:02.81 - [INFO] scan_ip add ip:213.94.75.118 time:645
> 7月 07 18:57:02.82 - [INFO] remove_slowest_ip:203.233.126.232 handshake_time:464, fails:2
> 7月 07 18:57:06.18 - [DEBUG] ip:113.171.253.22 real fail
> 7月 07 18:57:06.79 - [INFO] scan_ip add ip:134.90.151.33 time:1349
> 7月 07 18:57:06.80 - [INFO] remove_slowest_ip:114.4.4.206 handshake_time:1463, fails:1
> 7月 07 18:57:11.19 - [DEBUG] ip:179.154.191.151 real fail
> 7月 07 18:57:16.19 - [DEBUG] ip:90.201.124.97 real fail
> 7月 07 18:57:21.19 - [DEBUG] ip:103.233.36.114 real fail
> 7月 07 18:57:26.20 - [DEBUG] ip:2.127.251.102 real fail
> 7月 07 18:57:26.73 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)
> 7月 07 18:57:26.73 - [DEBUG] 120.28.26.190 close:request_fail
> 7月 07 18:57:26.73 - [DEBUG] ssl_closed 120.28.26.190
> 7月 07 18:57:31.20 - [DEBUG] ip:114.4.4.206 real fail

> XX-Net Version | 3.3.4
> Python Version | 2.7.13
> OpenSSL Version | 16.0.0 TLSv1_2 h2:alpn

1 | 2
-- | --
IP数量 | 919
空闲 | 1
IP延迟 | 555
连接池(帮助) | 新:2 h1:0 h2:0

蓝灯则没问题

**Comment by jzp820927** [comment]
用 XXNET 能直接在浏览器观看这个视频吗？

**Comment by wooowooo** [comment]
能

**Comment by wooowooo** [comment]
btw，youtube-dl是最新的

**Comment by jzp820927** [comment]
那就怪了，浏览器能直接观看的视频，下载应该就没问题。对了，你是就这一个视频不能下载？还是所有的视频都不能下载？

**Comment by wooowooo** [comment]
我试了一些，都不行

**Comment by jzp820927** [comment]
不会是 youtube-dl 的问题吧？

**Comment by wooowooo** [comment]
you-get需要导入证书到系统，不想导。ff的nethunter(叫什么了？)有些视频抓不到。
linux上不知道还有什么其他工具了

**Comment by jzp820927** [comment]
linux 确实没有太多下载工具。
另外看你日志，有个 504，你看看你连接 youtube 是用的直连模式？还是走的 GAE？

[youtube] XqLLxaJPabU: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 504: (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by wooowooo** [comment]
刚才又一试,竟然成功开始下载. netvideohunter好像也能抓了.

这个问题难道全归于gae网络的状态?

**Comment by wooowooo** [comment]
然而,没下多久就不行了

`$ youtube-dl --verbose  -c --proxy 127.0.0.1:8087 --no-check-certificate https://www.youtube.com/watch?v=eP1Q5JcCvYo`

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [u'--verbose', u'-c', u'--proxy', u'127.0.0.1:8087', u'--no-check-certificate', u'https://www.youtube.com/watch?v=eP1Q5JcCvYo']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2017.07.02
> [debug] Python version 2.7.13 - Linux-4.4.36-8-default-x86_64-with-SuSE-42.2-x86_64
> [debug] exe versions: ffmpeg 3.3, ffprobe 3.3
> [debug] Proxy map: {u'http': u'127.0.0.1:8087', u'https': u'127.0.0.1:8087'}
> [youtube] eP1Q5JcCvYo: Downloading webpage
> [youtube] eP1Q5JcCvYo: Downloading video info webpage
> [youtube] eP1Q5JcCvYo: Extracting video information
> [youtube] eP1Q5JcCvYo: Downloading MPD manifest
> [debug] Invoking downloader on u'https://r3---sn-i3b7knl7.googlevideo.com/videoplayback?id=78fd50e49702bd8a&itag=135&source=youtube&requiressl=yes&ms=au&mv=u&ei=_z5kWd7-O4GTqQHv9YvIBg&pl=20&mm=31&mn=sn-i3b7knl7&ratebypass=yes&mime=video/mp4&gir=yes&clen=385836814&lmt=1431969350831764&dur=5191.916&key=dg_yt0&mt=1499741517&signature=8BAC79EFDDC9F3816F2C5F139295FC1BA4267FC3.2A67DE67645F9EDA6988E39004B940EA7688B1FF&ip=222.216.97.33&ipbits=0&expire=1499763552&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,ei,pl,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
> [download] Resuming download at byte 5502976
> [download] Destination: 老夫子之小水虎傳奇 粵語.mkv-eP1Q5JcCvYo.f135.mp4
> [download]   4.7% of 367.96MiB at 143.03KiB/s ETA 41:50ERROR: unable to download video data: ('The read operation timed out',)
> Traceback (most recent call last):
>   File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1828, in process_info
>     partial_success = dl(fname, new_info)
>   File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1776, in dl
>     return fd.download(name, info)
>   File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
>     return self.real_download(filename, info_dict)
>   File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 165, in real_download
>     data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
>   File "/usr/lib64/python2.7/socket.py", line 384, in read
>     data = self._sock.recv(left)
>   File "/usr/lib64/python2.7/httplib.py", line 597, in read
>     s = self.fp.read(amt)
>   File "/usr/lib64/python2.7/socket.py", line 384, in read
>     data = self._sock.recv(left)
>   File "/usr/lib64/python2.7/ssl.py", line 774, in recv
>     return self.read(buflen)
>   File "/usr/lib64/python2.7/ssl.py", line 661, in read
>     v = self._sslobj.read(len)
> SSLError: ('The read operation timed out',)
> 

FF NetVideoHunter+downthemall 也是一样,无法完成下载

**Comment by jzp820927** [comment]
[download] 4.7% of 367.96MiB at 143.03KiB/s ETA 41:50ERROR: unable to download video data: ('The read operation timed out',)
超时了，应该是代理的问题，应该是代理不稳定，也就是可能是 IP 质量不佳。
