### ISSUE TITLE
更新windows后，闪退

### ISSUE THREAD

**Issue by akiritoa** [XX-net/XX-Net#5984]
版本3.3.1，点开start.bat，打开到python.exe，然后就没有然后了。

windows 更新内容是net.framework 4.7。除了这个软件其他也受影响，除了重装系统还有其他方法吗？

试了下3.3.4，也是闪退

使用驱动精灵稀里糊涂的解决了。。

**Comment by akiritoa** [comment]
试了下3.3.4也是闪退

**Comment by jzp820927** [comment]
驱动精灵？难道是硬件驱动有冲突？
