### ISSUE TITLE
IOS 请检查浏览器代理状态

### ISSUE THREAD

**Issue by SongYuanKun** [XX-net/XX-Net#5987]
ios手机通过自动代理翻墙，手机能访问pac文件。
但是安装证书后safari浏览器证书状态还是fail。
无法翻墙。

只配置了manual.ini文件
[listen]
ip = 0.0.0.0 
port = 8087

[gae]
appid =

[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

日志
ul 09 21:30:58.250 - [WARNING] 46.134.208.152 _consume_single_frame:SysCallError(10053, 'WSAECONNABORTED')
Jul 09 21:30:58.250 - [DEBUG] ssl_closed 46.134.208.152
Jul 09 21:30:58.250 - [DEBUG] 46.134.208.152 worker close:disconnect:SysCallError(10053, 'WSAECONNABORTED')
Jul 09 21:31:27.972 - [DEBUG] get ip:122.202.129.182 t:287
Jul 09 21:31:32.436 - [DEBUG] 122.202.129.182 fail:timeout('timed out',)
Jul 09 21:31:32.436 - [DEBUG] report_connect_fail:122.202.129.182
Jul 09 21:31:32.436 - [DEBUG] get ip:216.58.203.202 t:299
Jul 09 21:31:36.437 - [DEBUG] 216.58.203.202 fail:timeout('timed out',)
Jul 09 21:31:36.437 - [DEBUG] report_connect_fail:216.58.203.202
Jul 09 21:31:36.437 - [DEBUG] get ip:210.143.70.106 t:414
Jul 09 21:31:37.577 - [DEBUG] 201.57.54.213 keep alive fail, inactive_time:361 head_timeout:32
Jul 09 21:31:37.577 - [DEBUG] report_connect_fail:201.57.54.213
Jul 09 21:31:40.446 - [DEBUG] 210.143.70.106 fail:timeout('timed out',)
Jul 09 21:31:40.446 - [DEBUG] report_connect_fail:210.143.70.106
Jul 09 21:31:40.446 - [DEBUG] get ip:46.134.208.152 t:433
Jul 09 21:31:42.761 - [DEBUG] 201.57.54.213 worker close:keep alive
Jul 09 21:31:44.461 - [DEBUG] 46.134.208.152 fail:timeout('timed out',)
Jul 09 21:31:44.461 - [DEBUG] report_connect_fail:46.134.208.152
Jul 09 21:31:44.463 - [DEBUG] get ip:204.85.30.187 t:516
Jul 09 21:31:47.463 - [DEBUG] ip:122.202.129.182 real fail
Jul 09 21:31:48.564 - [DEBUG] 204.85.30.187 fail:timeout('timed out',)
Jul 09 21:31:48.564 - [DEBUG] report_connect_fail:204.85.30.187
Jul 09 21:31:48.565 - [DEBUG] get ip:66.96.226.100 t:578
Jul 09 21:31:49.303 - [DEBUG] restore ip:216.58.203.202

诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:180 good:43
network-status: OK
connected-link: new:1 used:0
worker: h1:14 h2:7
scan-ip-thread-num: 50
ip-quality: 475
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
你是 XXNET 运行在 PC 上，然后想 IOS 共享 PC 的 XXNET 嘛？

**Comment by SongYuanKun** [comment]
我之前用的就是3.3.4，之后重新弄了一份3.3.1的稳定版 @jzp820927

**Comment by jzp820927** [comment]
好吧，如果没问题，用低版本也行。
不知道你的问题解决了没有

**Comment by SongYuanKun** [comment]
@jzp820927 问题还没有解决，我准备重新安装一遍，360会导致不能使用么？

**Comment by jzp820927** [comment]
不确定，不过尽量少用国产软件吧，这个你应该懂。

**Comment by SongYuanKun** [comment]
用Safari访问https是无法验证服务器身份，貌似是证书不可信 @jzp820927

**Comment by jzp820927** [comment]
无法验证服务器身份？第一次听说这种报错，用 chrome 试试，看看是报什么错？

**Comment by SongYuanKun** [comment]
手机使用chrome浏览器尝试过了，打不开google，不是安全连接。证书无法通过chrome下载。
PC端访问google正常

**Comment by SongYuanKun** [comment]
以前配置好的代理是可以使用APP访问的，自从chrome升级证书之后就突然不能用了

**Comment by jzp820927** [comment]
ios端使用xxnet代理：
以下ip为安装部署好xxnet的PC端局域网地址

1.‘"设置"->"无线局域网"->"已连接的wifi"->"http设置"，输入代理地址http://ip:8086/proxy.pac

2.访问http://ip:8085/ 会提示"请检查浏览器代理设置"，下拉页面至"ca证书状态"，点击括号内的"下载"

3.按提示安装好证书

4.进入"设置"->"通用"->"关于本机"->"证书信任设置",找到"针对根证书启用完全信任"下方的GoAgent XX-net 勾选上就可以了
