### ISSUE TITLE
PC如何共享翻墙网络给安卓？

### ISSUE THREAD

**Issue by dacoit1983** [XX-net/XX-Net#5988]
我现在有一台通过XX-NET翻墙的PC。
内置一块INTEL AC 7260物理无线网卡。
并且已经在WIN7系统里设置了一个虚拟WIFI，安卓手机可以正常连接并访问墙内网络。

以上是我的基本条件，请教如何让PC通过WIFI共享xx-net翻墙的网络给安卓手机？

另外再问一个问题：我的无线路由是TP-Link的TL-WDR6500，不是什么智能路由器，有办法利用我现有的条件直接让路由器翻墙，由路由器直接提供翻墙WIFI吗？

第一个问题很重要，请赐教，谢谢！

**Comment by a1751874251** [comment]
长城发标不让翻

**Comment by dacoit1983** [comment]
PC能翻

**Comment by zhao94254** [comment]
开个http代理就可以给手机翻了

**Comment by jzp820927** [comment]
第一个问题，如果你的手机和 PC 在同一个局域网段，并且能互相 ping 通，那就没问题，办法很简单，只需要 PC 上的 XXNET 监听的 IP 地址，改为 0.0.0.0，然后手机设置代理为 PC 的 IP 地址，端口为 8087 就可以了。

第二个问题，估计不行，如果要想让路由器直接提供翻墙网络，需要在路由器上部署翻墙工具，所以必须的可以刷其他固件的路由器。如果可以刷固件，那就简单了，直接刷入第三方固件就可以了，一般第三方固件都会集成很多翻墙工具，直接配置下就能用了，基本上都能配置 SS 服务。

**Comment by dacoit1983** [comment]
@jzp820927 十分感谢，原来根本不需要虚拟WIFI，我还一直在调试虚拟WIFI连接的代理，一点用的没有。已经解决。

**Comment by jzp820927** [comment]
既然 浏览器 能看，那说明代理已经配置正确，而 apps 不行，就可以确定是 apps 的问题了。
部分 apps 有自己的证书管理系统，并不信任系统证书，或者是用户导入的证书，这个无解。
除非你 root 了设备，不过就算 root 了设备，解决方法也非常麻烦。建议就用浏览器看吧，别折腾了。

**Comment by dacoit1983** [comment]
@jzp820927 我清楚了，十分感谢。

**Comment by jzp820927** [comment]
不客气。

**Comment by Jan9th** [comment]
求推荐部署FQ的路由器 @jzp820927  极路由 梅林？ 好贵呀

**Comment by jzp820927** [comment]
你什么意思？是想要给你介绍一个可以 FQ 的路由器，你去买麽？

**Comment by Jan9th** [comment]
嗯 自己刷的也可以 我看你在其他地方有说用树莓派  是路由器么 天猫上看到的是一个板子 不像是路由器

**Comment by jzp820927** [comment]
现在最流行的 K2 就可以，而且是免费的。你可以考虑。

**Comment by Jan9th** [comment]
斐讯k2 么，我一个月前入手的，已经在用着，我找找教程，如果有推荐的教程看那就更好了

**Comment by jzp820927** [comment]
那不就行了，那你还找什么路由器，K2 就是最合适的，你刷 老毛子的估计了没？

**Comment by Jan9th** [comment]
求扔几个教程 [目前在看这个帖子，不是很懂吗，不敢操作](http://idannywu.com/20170625.html)

**Comment by jzp820927** [comment]
你可以去 恩山论坛 看看，里面有 K2 专版，有很多刷机教程。

**Comment by windlab2020** [comment]
做个标记，

**Comment by ljg6583** [comment]
> 既然浏览器能看，那说明代理已经配置正确，而apps不行，就可以确定是apps的问题了。
> 部分apps有自己的证书管理系统，并不信任系统证书，或者是用户导入的证书，这个无解。
> 除非你根了设备，不过就算root了设备，解决方法也非常
> 麻烦。还有个办法，就是用x_tunnel，不过流量要花钱买。



> 既然浏览器能看，那说明代理已经配置正确，而apps不行，就可以确定是apps的问题了。
> 部分apps有自己的证书管理系统，并不信任系统证书，或者是用户导入的证书，这个无解。
> 除非你根了设备，不过就算root了设备，解决方法也非常
> 麻烦。还有个办法，就是用x_tunnel，不过流量要花钱买。
我的问题同上，不过我想让智能电视看YouTube，有什么好办法

**Comment by AnyWAT** [comment]
PC（或其它设备）分享代理服务给安卓，原本在安卓上运行Xndroid 时（因证书？）不能正常的谷歌市场App 能正常。不知类似操作下智能电视的YouTube App 能否正常？
