### ISSUE TITLE
各种手机vpn纷纷被封，可怎么是好呀。

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#5991]
有什么好的办法吗。。。。

**Comment by myjlpt** [comment]
有这么厉害？纸飞机顶顶呀?

**Comment by jzp820927** [comment]
方法多的是，封不完的，比如 SS 之类的

**Comment by trdmm** [comment]
2L说得对

**Comment by nxtreaming** [comment]
自己搭建，私人使用，不公开，不推荐。

**Comment by Goooooollum** [comment]
哪个封了？

**Comment by theratlesnake** [comment]
@Goooooollum  到处都能看到你，幸灾乐祸的意思了？在首都还不低调点

**Comment by Goooooollum** [comment]
@theratlesnake 没有没有，只是奇怪，我觉得首都应该看得更紧，然而没有感受到；还有手机上的一些VPN也没收到影响，前几天还有讨论会在APP Store全面下架的

**Comment by theratlesnake** [comment]
@Goooooollum 推特上有人说GCE也开始封ip了，这次的封锁看来是下了重血本了，尤其是谷歌系列受害严重，有人开始揣测下一个会不会是亚马逊，不同的ISP作恶手段不一样，像你这种在敏感地区的，最好还是低调低调。万一被朝阳大妈发现...

**Comment by jzp820927** [comment]
封 GCE ？真的假的？应该是个例吧？

**Comment by SLDeongaree** [comment]
我想问问...xx-net有没有安卓版本？

**Comment by jzp820927** [comment]
@SLDeongaree https://github.com/XX-net/xxnet-android/releases
只是早上测试版，也是没有继续开发了，可用性不高。

**Comment by SLDeongaree** [comment]
我试了一下，xx-net设置“全局通过GAE代理”，电脑也设置了静态ip192.168.1.111，手机上设置代理服务器：192.1681.111 端口8087
但是用不了啊...连百度都打不开...

**Comment by jzp820927** [comment]
看看 日志有滚动吗？

**Comment by rbw233** [comment]
是啊很多VPN都下架了，我现在用的还是ssr呢n

**Comment by jzp820927** [comment]
看来以后 SS 就是唯一的救命稻草了。
