### ISSUE TITLE
Google App Engine upload fail

### ISSUE THREAD

**Issue by daiguawangzi** [XX-net/XX-Net#6]
Application: ********
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>

============  Begin upload  ============

试传了几组自己的appid,均失败
不知道原因

**Comment by xxnet** [comment]
请确认google的“允许弱安全”已经打开。
https://www.google.com/settings/security/lesssecureapps

**Comment by xxnet** [comment]
新版本有详细的提示，请用最新版本试试
