### ISSUE TITLE
使用公共appid，youtube 能上，但是没有办法播放

### ISSUE THREAD

**Issue by angel126** [XX-net/XX-Net#60]
版本已更新到最新版本

**Comment by xxnet** [comment]
你是不是用了公共的appid? 
公共appid流量不够了，为了保证新手能够一下载就能用上，限制了视频。

请老手都部署自己的appid，也不复杂。
视频太耗流量，把流量留给新手们吧，谢谢。

**Comment by angel126** [comment]
ok

**Comment by angel126** [comment]
如何设置密码呢？我在部署哪里填入密码，提示错误
WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication

upload  fail: can't set attribute

**Comment by xxnet** [comment]
建立不用给服务端设置密码，必要性不大。还会增加复杂性。
因此Web界面上没有给出设置密码的入口。

部署界面上的密码，是你登录google的密码（或者是应用专用密码）

WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication
upload fail: can't set attribute
意思是你的登录Google的密码错。
