### ISSUE TITLE
希望大神早点写好技术类指导wiki，好让更多的人参与进来

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#603]

**Comment by xxnet** [comment]
好的。

整体来讲，xx-net 采用python为开发语言，结构化、模块化设计，代码尽量简洁，易懂。

如果能够下载代码看看，应该比较容易明白的。
其实开发过程中，感觉门槛在于一些HTTP的协议、ssl 的规范、翻墙技术本身的知识。
语言和代码的复杂度并不高。

有疑问我尽可能的解答，也是给写技术指导的思路。

我回头可以先写一个目录结构说明、代码文件的说明。


2015-07-12 9:31 GMT+08:00 cdmask <notifications@github.com>:

**Comment by xxnet** [comment]
简单写了个概况：
https://github.com/XX-net/XX-Net/wiki/%E6%8A%80%E6%9C%AF%E8%AF%B4%E6%98%8E

慢慢再完善

在 2015年7月13日 下午3:29，Net XX <xxnet.dev@gmail.com>写道：

**Comment by cdmask** [comment]
辛苦了！
