### ISSUE TITLE
看MFC卡顿严重怎么办？有老司机解救吗？

### ISSUE THREAD

**Issue by Tesla1983** [XX-net/XX-Net#6035]
属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 1045
空闲 | 0
IP延迟 | 222
连接池(帮助) | 新:4 h1:13 h2:14
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 50
屏蔽状态(帮助) | OK

看YouTube都很流畅，反倒看MFC卡顿严重，求老司机解救啊！！！555555555555

**Comment by zhencaihao** [comment]
![qq 20170716152929](https://user-images.githubusercontent.com/19796493/28245535-b01978ca-6a3b-11e7-8a46-19d75de6a6ce.jpg)
![qq 20170716153004](https://user-images.githubusercontent.com/19796493/28245536-b01b70a8-6a3b-11e7-837b-0f94a79aad5d.jpg)
怎么我这里用XX-NET进MFC一直显示Loading HTML...

这个情况是从7月7日开始的，到现在一直是这个样子。

**Comment by zhencaihao** [comment]
刚才清空了浏览数据试了一下，发现可以用XX-NET进MFC了。问题是一登陆帐号就显示"Loading HTML..."按F12后可以看到登录帐号后多了一行“fcsl”。以前都是登录帐号状态下用XX-NET看MFC的一直没问题。就是7月7日那天突然就显示Loading HTML...直到现在也没恢复过。http和https都这样。

**Comment by Tesla1983** [comment]
我是可以进去，但是看直播很卡顿.

**Comment by zhencaihao** [comment]
你是用XX-NET，帐号登录状态下看的吗？

**Comment by Tesla1983** [comment]
是的

**Comment by zhencaihao** [comment]
这个我也是奇怪了，XX-NET已经升级到3.3.4了，谷歌浏览器也是最新的版本 59.0.3071.115（正式版本） （64 位）。为什么你们能用XX-NET正常登录、观看MFC，而我这里却是Loading HTML...。

**Comment by jap33** [comment]
奇怪我怎么直接能看。
![default](https://user-images.githubusercontent.com/15140842/28248661-a28fa456-6a7a-11e7-9075-0ffadfa5a0bd.PNG)

**Comment by jzp820927** [comment]
@zhencaihao 实在用 XXNET 不能登录，就考虑用 https 直连吧。
@Tesla1983 我感觉 XXNET 可能不太适合直播类视频。不视频，你用 XXNET 看 youtube 上的直播速度怎么样？

**Comment by Tesla1983** [comment]
@jzp820927 我看YouTube的720P直播还可以挺流畅的，偶尔卡一下。

**Comment by jzp820927** [comment]
@Tesla1983 其实我觉得 mfc 直连的速度都挺不错的，你可以试试。

**Comment by zhencaihao** [comment]
我这里白天直连MFC也卡，到了下午、晚上有时候干脆就打不开网页，得刷新好几次才会慢慢出来。

**Comment by Tesla1983** [comment]
@jzp820927 我试了直连也是卡，我估计是我自己的网络问题。

**Comment by jzp820927** [comment]
直播类视频对代理的质量要求比较高，如果可以流畅 youtube，都不能流畅 mfc 估计只能考虑换其他代理了。

**Comment by thq135** [comment]
用XX-NET的道友们，国内的安全软件都卸载了吧，测了火绒安全软件，确有端倪。

**Comment by jzp820927** [comment]
LS 说的太正确了。

**Comment by Tesla1983** [comment]
联系电信换了个光猫一切正常了。
