### ISSUE TITLE
突然gmail上不了了，youtube也没有缩略图，什么问题？

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#6040]
gmail是连接超时，youtube能看视频。但是缩略图都打不开。。。是哪出来问题，最新版。前几天正常的哦

**Comment by jzp820927** [comment]
直连找出的，可以配置对于的域名走 GAE，应该可以解决问题。

**Comment by yuyistar** [comment]
@jzp820927 能说下具体操作吗。听不懂

**Comment by jzp820927** [comment]
我在 issues 回答过很多次了，你在 issues 搜索一下，能找到很多答案

**Comment by yuyistar** [comment]
@jzp820927 已经解决了。gmail问题，但是youtube图标是碎的还是没有解决
[hosts]
.youtube.com = gae
.google.com = gae
代码是这样，奇怪的是youtube那行代码是之前加的，修复过碎图问题，但是现在问题又回来了。这个是什么情况呢

**Comment by jzp820927** [comment]
.ytimg.com = gae
这个是 ytb 图片的，看看有没有这个配置？

**Comment by yuyistar** [comment]
@jzp820927 感谢已经加上了。。。不过我还是很奇怪，为什么之前没有这些配置的时候可以正常，但是现在又要加入这些配置才可以呢。或者家里和单位的电脑，有的需要加，有的不用加也正常。。。。匪夷所思

**Comment by jzp820927** [comment]
如果你的网络状况比较好，IP 没什么干扰，就可以不加。也就是直连模式。
如果干扰厉害，就要加，通过走 GAE 来增加连接的稳定性。
