### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by knsong** [XX-net/XX-Net#6041]
-----------
问题描述：XX-Net总是出现“请检查浏览器代理设置。”问题
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 3000
network-status: OK
connected-link: 5 / 6
scan-ip-thread-num: 24
ip-quality: 119
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
你这个 XXNET 也太老了吧，先升级 3.3.4，如果不行，就按 #5322 解决。

**Comment by ez213** [comment]
“请检查浏览器代理设置。” 这句可以无视，一般是IE设置的问题
一般这时候都已经可以科上了
你用chrome或firefox加插件试试

**Comment by jzp820927** [comment]
LS 的方法也行。

**Comment by knsong** [comment]
更新版本后正常了，多谢！ @jzp820927 @ez213
