### ISSUE TITLE
manual.ini中gae、fwd、direct

### ISSUE THREAD

**Issue by yuliangyang** [XX-net/XX-Net#605]
xxnet1.15.2之前的版本hosts模块还是支持fwd模式发起连接的，为嘛之后的版本都不支持fwd了
修改为fwd模式，就会出现证书问题。是xxnet修改了，还是google的问题

**Comment by xxnet** [comment]
也许是bug

因为fwd 模式很容易收到干扰，所以默认都不使用fwd模式，代码都还没有删除，估计是升级其他地方的时候，此处没有升级导致。
请把错误日志发出来。

至于证书，那是不应该出现问题的，因为FWD模式，使用的是原始的google证书。

在 2015年7月12日 下午12:36，yuliangyang <notifications@github.com>写道：

**Comment by yuliangyang** [comment]
Jul 13 16:11:09 - [DEBUG] get ip:218.189.25.145 t:326
Jul 13 16:11:09 - [DEBUG] forward local disconnected.
Jul 13 16:11:09 - [DEBUG] FWD CONNECT www.google.com:443 with closed
Jul 13 16:11:09 - [DEBUG] tcp conn 218.189.25.184 fail t:1000
Jul 13 16:11:09 - [DEBUG] tcp conn 218.189.25.134 fail t:1000
Jul 13 16:11:09 - [DEBUG] create_ssl update ip:218.189.25.168 time:124
Jul 13 16:11:09 - [DEBUG] create_ssl update ip:218.189.25.145 time:125
Jul 13 16:11:09 - [DEBUG] get ip:218.189.25.176 t:326
Jul 13 16:11:09 - [DEBUG] get ip:218.189.25.172 t:326
Jul 13 16:11:09 - [DEBUG] get ip:218.189.25.158 t:327
Jul 13 16:11:09 - [DEBUG] tcp conn 173.194.14.119 fail t:1000
Jul 13 16:11:09 - [DEBUG] tcp conn 74.125.215.37 fail t:1000
Jul 13 16:11:09 - [DEBUG] create_ssl update ip:218.189.25.176 time:125
Jul 13 16:11:09 - [DEBUG] create_ssl update ip:218.189.25.172 time:125
Jul 13 16:11:09 - [DEBUG] create_ssl update ip:218.189.25.158 time:125
Jul 13 16:11:10 - [INFO] FWD CONNECT www.google.com:443
Jul 13 16:11:10 - [DEBUG] get ip:218.189.25.150 t:328
Jul 13 16:11:10 - [INFO] FWD CONNECT www.google.com:443

没啥问题了，.google.com = 改成fwd，重启xxnet
进入google会提示证书问题，多刷新几次就没问题了
现在已经没问题了   总觉得fwd模式速度快一点，尤其youtube

**Comment by xxnet** [comment]
好的。
如果提示证书问题，可以点击地址栏最左边的图标，可以看证书的详情，分析是什么原因导致。
感觉目前的速度比5月份慢很多，是可以研究到底哪里慢了的。

2015-07-13 16:15 GMT+08:00 yuliangyang <notifications@github.com>:
