### ISSUE TITLE
求x-tunnel 流量

### ISSUE THREAD

**Issue by xpirad** [XX-net/XX-Net#6058]
哪位好心人可以给下吗？

帐号：xpirad@gmail.com

万分感谢！！

**Comment by tomcat-bj** [comment]
同求，我有个号转让分享给项目，然后整个帐号被ban了……但是一点流量都没收到
cctvbtv09@gmail.com

**Comment by jzp820927** [comment]
有个 issues 是专门送流量的，可以 issues 搜索下。

**Comment by xpirad** [comment]
@jzp820927 https://github.com/XX-net/XX-Net/issues/3471 这个已经锁了

**Comment by xpirad** [comment]
好的，谢谢!
