### ISSUE TITLE
现在appID怎么申请不上了？

### ISSUE THREAD

**Issue by lele2010lele** [XX-net/XX-Net#606]
进入appengine，好像改版了，英语不好，不会申请了。
求帮助。

**Comment by shenhix** [comment]
@lele2010lele 
http://wallfans.eu.org/xxnet-course_new/
Google更改了，请看最新教程！

**Comment by xxnet** [comment]
相对麻烦一些，还是可以申请的。
网页网站也有变化，你点击下面的链接跳过去, https://console.developers.google.com/

2015-07-12 20:47 GMT+08:00 shenhix <notifications@github.com>:

**Comment by k0724** [comment]
https://console.developers.google.com/, 顺利解决，谢谢！
