### ISSUE TITLE
server certificate verification failed

### ISSUE THREAD

**Issue by llan-ml** [XX-net/XX-Net#6060]
系统：ubuntu 16.04 
问题：使用代理用apt安装package时，报错：<code>server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none</code>

我想用代理安装docker，之前已经用下面的命令加了认证。
<code>
sudo apt-key adv \
               --keyserver hkp://ha.pool.sks-keyservers.net:80 \
               --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
</code>

但是用代理下载就会报认证错误，网络小白求问，这个认证该怎么加？？？

**Comment by jzp820927** [comment]
证书导入系统了吗？

**Comment by llan-ml** [comment]
@jzp820927 嗯，在stackoverflow上找到啦~
