### ISSUE TITLE
墙封vpn，商业怎么办？

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#6064]
一些公司在国内外有办公的，不是自己搭建vpn来联络的吗？
不知道什么时候起vpn的流量已经是可探测的了？并且两年前已开始探测并阻断。那么做生意的怎么办？

**Comment by myjlpt** [comment]
政府专线。可以申请！呵呵,貌似，好像!@

**Comment by jzp820927** [comment]
总有办法的，比如专线之类的。

**Comment by WLZLCX** [comment]
楼主问这想干嘛？

**Comment by whhxmwhh** [comment]
没事照样用。除非物理断网！～

**Comment by Easefeel** [comment]
中国政府又封不了外企的vpn供应商，你可以选择ExpressVPN/NordVPN这些啊

**Comment by roc1010kmt** [comment]
外國大使館都用什麼網路？

**Comment by simonasd** [comment]
企事业单位要接入国际网络，无非就是签署一个责任状/保证书之类的东西，各大云服务提供商均有相关服务。但这中间还是有耳目的（例如，阿里在云主机上安装后门程序监听流量）。

**Comment by nxtreaming** [comment]
切记不要用阿里云主机翻墙，他监控所有网络请求。
