### ISSUE TITLE
system is idle & 尚未建立连接

### ISSUE THREAD

**Issue by Ch-Song** [XX-net/XX-Net#6073]
诊断状态：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:124
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

按问题58的方法改过了，升级到3.3.4了，ip昨天导入过一个帖子里的今天一看IP只剩一百多个了。很麻烦，请问这个要怎么解决

**Comment by Ch-Song** [comment]
日志：
Jul 21 13:06:54.009 - [DEBUG] 150.100.16.0 fail:timeout('timed out',)
Jul 21 13:06:54.009 - [DEBUG] report_connect_fail:150.100.16.0
Jul 21 13:06:54.009 - [DEBUG] get ip:103.37.34.251 t:100
Jul 21 13:06:55.442 - [DEBUG] ip:59.7.238.0 real fail
Jul 21 13:06:57.208 - [DEBUG] GAE GET https://github.com/Cat7373?tab=repositories&_pjax=%23js-pjax-container
Jul 21 13:06:58.042 - [DEBUG] 103.37.34.251 fail:timeout('timed out',)
Jul 21 13:06:58.042 - [DEBUG] report_connect_fail:103.37.34.251
Jul 21 13:06:58.043 - [DEBUG] get ip:119.67.241.0 t:100
Jul 21 13:06:58.079 - [DEBUG] ip:201.31.84.0 real fail
Jul 21 13:07:02.086 - [DEBUG] 119.67.241.0 fail:timeout('timed out',)
Jul 21 13:07:02.086 - [DEBUG] report_connect_fail continue_fail_count:11
Jul 21 13:07:02.087 - [DEBUG] report_connect_fail:119.67.241.0
Jul 21 13:07:02.114 - [DEBUG] get ip:182.221.114.255 t:100
Jul 21 13:07:02.211 - [DEBUG] network is ok, cost:124 ms
Jul 21 13:07:03.095 - [DEBUG] ip:124.153.225.255 real fail
Jul 21 13:07:06.145 - [DEBUG] 182.221.114.255 fail:timeout('timed out',)
Jul 21 13:07:06.145 - [DEBUG] report_connect_fail:182.221.114.255
Jul 21 13:07:06.165 - [DEBUG] get ip:66.34.117.255 t:100
Jul 21 13:07:08.097 - [DEBUG] ip:182.208.193.0 real fail
Jul 21 13:07:08.644 - [DEBUG] create ssl timeout fail.
Jul 21 13:07:08.644 - [DEBUG] create ssl timeout fail.
Jul 21 13:07:08.644 - [DEBUG] GAE_Exception 1 'no ssl_sock'
Jul 21 13:07:08.644 - [WARNING] get worker fail:GAE_Exception()
Jul 21 13:07:08.644 - [DEBUG] response_fail:get worker fail:GAE_Exception()
Jul 21 13:07:08.644 - [DEBUG] GAE_Exception 601 'fetch gae fail:601'
Jul 21 13:07:08.644 - [WARNING] gae_exception:GAE_Exception() https://www.google-analytics.com/collect
Jul 21 13:07:08.644 - [DEBUG] GAE_Exception 600 'gae_exception:GAE_Exception() https://www.google-analytics.com/collect'
Jul 21 13:07:08.644 - [WARNING] GAE POST https://www.google-analytics.com/collect request fail:GAE_Exception()
Jul 21 13:07:08.644 - [DEBUG] get ip:118.160.93.0 t:100
Jul 21 13:07:09.162 - [DEBUG] get ip:103.44.151.0 t:100
Jul 21 13:07:09.684 - [DEBUG] get ip:121.153.36.0 t:100
Jul 21 13:07:10.184 - [DEBUG] 66.34.117.255 fail:timeout('timed out',)
Jul 21 13:07:10.184 - [DEBUG] report_connect_fail:66.34.117.255
Jul 21 13:07:10.184 - [DEBUG] get ip:112.215.183.59 t:1100
Jul 21 13:07:10.200 - [DEBUG] get ip:94.40.70.0 t:100
Jul 21 13:07:10.715 - [DEBUG] get ip:221.146.174.0 t:100
Jul 21 13:07:11.231 - [DEBUG] get ip:202.67.41.255 t:100
Jul 21 13:07:11.746 - [DEBUG] get ip:182.211.18.255 t:100
Jul 21 13:07:12.263 - [DEBUG] get ip:112.155.24.255 t:100
Jul 21 13:07:12.647 - [DEBUG] 118.160.93.0 fail:timeout('timed out',)
Jul 21 13:07:12.647 - [DEBUG] report_connect_fail:118.160.93.0
Jul 21 13:07:12.647 - [DEBUG] get ip:182.214.172.255 t:100
Jul 21 13:07:12.783 - [DEBUG] get ip:202.152.47.255 t:100
Jul 21 13:07:12.996 - [INFO] GAE CONNECT clients4.google.com:443
Jul 21 13:07:13.007 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=8vtoqC%2B/xdcyGWTzDUMF/w%3D%3D
Jul 21 13:07:13.099 - [DEBUG] ip:125.180.93.0 real fail
Jul 21 13:07:13.299 - [DEBUG] get ip:114.206.94.255 t:100
Jul 21 13:07:13.568 - [DEBUG] 103.44.151.0 fail:timeout('timed out',)
Jul 21 13:07:13.568 - [DEBUG] report_connect_fail:103.44.151.0
Jul 21 13:07:13.568 - [DEBUG] get ip:121.149.246.0 t:100
Jul 21 13:07:13.816 - [DEBUG] get ip:119.9.76.255 t:100
Jul 21 13:07:13.847 - [DEBUG] 121.153.36.0 fail:timeout('timed out',)
Jul 21 13:07:13.847 - [DEBUG] report_connect_fail:121.153.36.0
Jul 21 13:07:13.847 - [DEBUG] get ip:203.233.10.219 t:101
Jul 21 13:07:14.233 - [DEBUG] 112.215.183.59 fail:timeout('timed out',)
Jul 21 13:07:14.233 - [DEBUG] report_connect_fail:112.215.183.59
Jul 21 13:07:14.233 - [DEBUG] get ip:61.238.203.143 t:101
Jul 21 13:07:14.332 - [DEBUG] get ip:1.255.33.154 t:102
Jul 21 13:07:14.551 - [DEBUG] 94.40.70.0 fail:timeout('timed out',)
Jul 21 13:07:14.551 - [DEBUG] report_connect_fail:94.40.70.0
Jul 21 13:07:14.551 - [DEBUG] get ip:41.223.219.93 t:1102
Jul 21 13:07:14.718 - [DEBUG] 221.146.174.0 fail:timeout('timed out',)
Jul 21 13:07:14.718 - [DEBUG] report_connect_fail:221.146.174.0
Jul 21 13:07:14.718 - [DEBUG] get ip:61.238.239.215 t:102
Jul 21 13:07:14.850 - [DEBUG] get ip:61.238.239.146 t:103
Jul 21 13:07:15.351 - [DEBUG] get ip:61.238.239.102 t:105
Jul 21 13:07:15.869 - [DEBUG] get ip:61.238.203.179 t:105
Jul 21 13:07:16.352 - [DEBUG] 112.155.24.255 fail:timeout('timed out',)
Jul 21 13:07:16.352 - [DEBUG] report_connect_fail:112.155.24.255
Jul 21 13:07:16.368 - [DEBUG] get ip:66.96.224.116 t:1112
Jul 21 13:07:16.390 - [DEBUG] get ip:187.123.28.33 t:1113
Jul 21 13:07:16.653 - [DEBUG] 182.211.18.255 fail:timeout('timed out',)
Jul 21 13:07:16.653 - [DEBUG] report_connect_fail:182.211.18.255
Jul 21 13:07:16.653 - [DEBUG] get ip:31.211.248.96 t:1113
Jul 21 13:07:16.706 - [DEBUG] 182.214.172.255 fail:timeout('timed out',)
Jul 21 13:07:16.706 - [DEBUG] report_connect_fail continue_fail_count:11
Jul 21 13:07:16.706 - [DEBUG] report_connect_fail:182.214.172.255
Jul 21 13:07:16.721 - [DEBUG] get ip:77.237.27.120 t:1114
Jul 21 13:07:16.790 - [DEBUG] 202.152.47.255 fail:timeout('timed out',)
Jul 21 13:07:16.790 - [DEBUG] report_connect_fail continue_fail_count:12
Jul 21 13:07:16.790 - [DEBUG] report_connect_fail:202.152.47.255
Jul 21 13:07:16.790 - [DEBUG] get ip:58.123.220.225 t:114
Jul 21 13:07:16.806 - [DEBUG] network is ok, cost:99 ms
Jul 21 13:07:16.905 - [DEBUG] get ip:61.238.203.250 t:115
Jul 21 13:07:17.084 - [DEBUG] 202.67.41.255 fail:timeout('timed out',)
Jul 21 13:07:17.084 - [DEBUG] report_connect_fail:202.67.41.255
Jul 21 13:07:17.084 - [DEBUG] get ip:140.113.14.25 t:115
Jul 21 13:07:17.421 - [DEBUG] get ip:201.248.78.115 t:1118
Jul 21 13:07:17.574 - [DEBUG] 121.149.246.0 fail:timeout('timed out',)
Jul 21 13:07:17.574 - [DEBUG] report_connect_fail:121.149.246.0
Jul 21 13:07:17.853 - [DEBUG] 203.233.10.219 fail:timeout('timed out',)
Jul 21 13:07:17.853 - [DEBUG] report_connect_fail:203.233.10.219
Jul 21 13:07:18.107 - [DEBUG] ip:124.56.32.255 real fail
Jul 21 13:07:18.233 - [DEBUG] 61.238.203.143 fail:timeout('timed out',)
Jul 21 13:07:18.233 - [DEBUG] report_connect_fail:61.238.203.143
Jul 21 13:07:18.552 - [DEBUG] 41.223.219.93 fail:timeout('timed out',)
Jul 21 13:07:18.552 - [DEBUG] report_connect_fail:41.223.219.93
Jul 21 13:07:18.718 - [DEBUG] 1.255.33.154 fail:timeout('timed out',)
Jul 21 13:07:18.718 - [DEBUG] report_connect_fail:1.255.33.154
Jul 21 13:07:18.767 - [DEBUG] 61.238.239.215 fail:timeout('timed out',)
Jul 21 13:07:18.767 - [DEBUG] report_connect_fail:61.238.239.215
Jul 21 13:07:18.850 - [DEBUG] 61.238.239.146 fail:timeout('timed out',)
Jul 21 13:07:18.850 - [DEBUG] report_connect_fail:61.238.239.146
Jul 21 13:07:19.193 - [DEBUG] 119.9.76.255 fail:timeout('timed out',)
Jul 21 13:07:19.193 - [DEBUG] report_connect_fail:119.9.76.255
Jul 21 13:07:19.252 - [DEBUG] 114.206.94.255 fail:timeout('timed out',)
Jul 21 13:07:19.252 - [DEBUG] report_connect_fail:114.206.94.255
Jul 21 13:07:19.363 - [DEBUG] 61.238.239.102 fail:timeout('timed out',)
Jul 21 13:07:19.363 - [DEBUG] report_connect_fail continue_fail_count:11
Jul 21 13:07:19.363 - [DEBUG] report_connect_fail:61.238.239.102
Jul 21 13:07:19.871 - [DEBUG] 61.238.203.179 fail:timeout('timed out',)
Jul 21 13:07:19.872 - [DEBUG] report_connect_fail continue_fail_count:12
Jul 21 13:07:19.873 - [DEBUG] report_connect_fail:61.238.203.179
Jul 21 13:07:19.978 - [DEBUG] network is ok, cost:105 ms
Jul 21 13:07:20.372 - [DEBUG] 66.96.224.116 fail:timeout('timed out',)
Jul 21 13:07:20.373 - [DEBUG] report_connect_fail:66.96.224.116
Jul 21 13:07:20.653 - [DEBUG] 31.211.248.96 fail:timeout('timed out',)
Jul 21 13:07:20.653 - [DEBUG] report_connect_fail:31.211.248.96
Jul 21 13:07:20.722 - [DEBUG] 77.237.27.120 fail:timeout('timed out',)
Jul 21 13:07:20.722 - [DEBUG] report_connect_fail:77.237.27.120
Jul 21 13:07:20.790 - [DEBUG] 58.123.220.225 fail:timeout('timed out',)
Jul 21 13:07:20.790 - [DEBUG] report_connect_fail:58.123.220.225
Jul 21 13:07:21.085 - [DEBUG] 140.113.14.25 fail:timeout('timed out',)
Jul 21 13:07:21.085 - [DEBUG] report_connect_fail:140.113.14.25
Jul 21 13:07:21.858 - [DEBUG] 201.248.78.115 fail:timeout('timed out',)
Jul 21 13:07:21.858 - [DEBUG] report_connect_fail:201.248.78.115

**Comment by jzp820927** [comment]
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
没有 IP，多扫点时间，再不行，估计没辙了，ISP 的关系

**Comment by THLIVSQAZ** [comment]
不得不承认，quic现在确实很强

**Comment by Ch-Song** [comment]
@jzp820927 怎重新扫Ip啊？有什么方法可以自动获取可用Ip或者有哪些能用的Ip库可以直接导入吗?
@THLIVSQAZ quic是什么东西怎么用啊？

我现在一般用Laod.cn发布的hosts一般的google就可以用了，xx-net偶尔用一下有的网站hosts不能解决，主要是偶尔看Pornhub、Redtube Laod.cn的hosts不能用只能借助xxnet就比较麻烦

**Comment by jzp820927** [comment]
重新扫描 IP ，就是让你删除 data，其他 IP 库，你在 issues 搜索一下，就能找到答案。
