### ISSUE TITLE
youtube-dl下载错误

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#6074]
我的命令是如下，但是为什么不能下载呢
C:\>youtube-dl --proxy 127.0.0.1:8087 --no-check-certificate https://www.youtube
.com/watch?v=A9WxTeLwVmc&spfreload=10
[youtube] A9WxTeLwVmc: Downloading webpage
[youtube] A9WxTeLwVmc: Downloading video info webpage
ERROR: A9WxTeLwVmc: "token" parameter not in video info for unknown reason; plea
se report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.
'spfreload' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

用的版本应该是最新版了，
C:\>youtube-dl --version
2017.07.15

**Comment by jzp820927** [comment]
直接浏览器能看吗？

**Comment by yuyistar** [comment]
@jzp820927 可以看呀

**Comment by N46AN** [comment]
这个问题好久了，一直没解决 https://github.com/XX-net/XX-Net/issues/5996

**Comment by simonasd** [comment]
@yuyistar 请使用如下命令：
youtube-dl --proxy 127.0.0.1:8087 --no-check-certificate https://www.youtube.com/watch?v=A9WxTeLwVmc

或在URL前后使用英文引号：
youtube-dl --proxy 127.0.0.1:8087 --no-check-certificate "https://www.youtube.com/watch?v=A9WxTeLwVmc&spfreload=10"

&符号在命令行下有特殊含义，会影响命令执行。

**Comment by yuyistar** [comment]
@simonasd 不行，依然报错

**Comment by fiefdx** [comment]
我尝试调试了下youtube-dl，发现在调用获取网页内容的时候，goagent会默认返回gzip压缩内容，导致youtube-dl的正则表达式不起作用，从而无法正常下载，我也尝试了在youtube-dl的项目中提交pr修复，不过他们说这个不是他们的bug，让goagent这边修复，正常处理Content-Encoding

https://github.com/rg3/youtube-dl/pull/13743

When call _download_webpage(), goagent return gziped page content, so, the regular expression do not work on those page content, I add a header, so it will let goagent return plain text page content, then it works.

“youtube-dl handles gzipped responses just fine. If goagent returns gzipped content without proper Content-Encoding set then it's a problem of goagent and should be addressed to its developers.
Post the output with --dump-pages --print-traffic.”

**Comment by fiefdx** [comment]
应该不是gzip，goagent返回的结果是Content-Encoding: br

**Comment by fiefdx** [comment]
youtube-dl请求为Accept-Encoding: gzip, deflate

$ curl -iv -H "Accept-Encoding: gzip, deflate" 'https://www.youtube.com/watch?v=aofJSEoAZqA&gl=US&hl=en&has_verified=0&bpctr=9999999999' --insecure | head -n 30
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8087 (#0)
* Establish HTTP proxy tunnel to www.youtube.com:443
> CONNECT www.youtube.com:443 HTTP/1.1
> Host: www.youtube.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< 
* Proxy replied OK to CONNECT request
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* found 701 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: *.youtube.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=CN,ST=Internet,L=Cernet,OU=GoAgent,CN=*.youtube.com,O=*.youtube.com
* 	 start date: Mon, 24 Jul 2017 11:26:16 GMT
* 	 expire date: Sat, 24 Jul 2027 11:36:16 GMT
* 	 issuer: C=CN,ST=Internet,L=Cernet,O=GoAgent,OU=GoAgent,CN=GoAgent
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /watch?v=aofJSEoAZqA&gl=US&hl=en&has_verified=0&bpctr=9999999999 HTTP/1.1
> Host: www.youtube.com
> User-Agent: curl/7.47.0
> Accept: */*
> Accept-Encoding: gzip, deflate
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< HTTP/1.1 200 OK
< Content-Length: 37816
< X-Xss-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
< X-Content-Type-Options: nosniff
< Content-Encoding: br
< Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
< Set-Cookie: VISITOR_INFO1_LIVE=fyZ4n8efeLg; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT; httponly
< Set-Cookie: PREF=f1=50000000; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT
< Set-Cookie: YSC=rkDPEq2ofAM; path=/; domain=.youtube.com; httponly
< Strict-Transport-Security: max-age=31536000
< Expires: Tue, 27 Apr 1971 19:44:06 EST
< Server: YouTubeFrontEnd
< X-Head-Content-Length: 
< Cache-Control: no-cache
< Date: Thu, 27 Jul 2017 03:55:55 GMT
< P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
< Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: SAMEORIGIN
< 
{ [8192 bytes data]
HTTP/1.1 200 OK

HTTP/1.1 200 OK
Content-Length: 37816
X-Xss-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
X-Content-Type-Options: nosniff
Content-Encoding: br
Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
Set-Cookie: VISITOR_INFO1_LIVE=fyZ4n8efeLg; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT; httponly
Set-Cookie: PREF=f1=50000000; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT
Set-Cookie: YSC=rkDPEq2ofAM; path=/; domain=.youtube.com; httponly
Strict-Transport-Security: max-age=31536000
Expires: Tue, 27 Apr 1971 19:44:06 EST
Server: YouTubeFrontEnd
X-Head-Content-Length: 
Cache-Control: no-cache
Date: Thu, 27 Jul 2017 03:55:55 GMT
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN

**Comment by fiefdx** [comment]
youtube-dl的请求头为Accept-Encoding: gzip, deflate

'''
$ curl -iv -H "Accept-Encoding: gzip, deflate" 'https://www.youtube.com/watch?v=aofJSEoAZqA&gl=US&hl=en&has_verified=0&bpctr=9999999999' --insecure | head -n 30
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8087 (#0)
* Establish HTTP proxy tunnel to www.youtube.com:443
> CONNECT www.youtube.com:443 HTTP/1.1
> Host: www.youtube.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< 
* Proxy replied OK to CONNECT request
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* found 701 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: *.youtube.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=CN,ST=Internet,L=Cernet,OU=GoAgent,CN=*.youtube.com,O=*.youtube.com
* 	 start date: Mon, 24 Jul 2017 11:26:16 GMT
* 	 expire date: Sat, 24 Jul 2027 11:36:16 GMT
* 	 issuer: C=CN,ST=Internet,L=Cernet,O=GoAgent,OU=GoAgent,CN=GoAgent
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /watch?v=aofJSEoAZqA&gl=US&hl=en&has_verified=0&bpctr=9999999999 HTTP/1.1
> Host: www.youtube.com
> User-Agent: curl/7.47.0
> Accept: */*
> Accept-Encoding: gzip, deflate
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< HTTP/1.1 200 OK
< Content-Length: 37816
< X-Xss-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
< X-Content-Type-Options: nosniff
< Content-Encoding: br
< Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
< Set-Cookie: VISITOR_INFO1_LIVE=fyZ4n8efeLg; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT; httponly
< Set-Cookie: PREF=f1=50000000; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT
< Set-Cookie: YSC=rkDPEq2ofAM; path=/; domain=.youtube.com; httponly
< Strict-Transport-Security: max-age=31536000
< Expires: Tue, 27 Apr 1971 19:44:06 EST
< Server: YouTubeFrontEnd
< X-Head-Content-Length: 
< Cache-Control: no-cache
< Date: Thu, 27 Jul 2017 03:55:55 GMT
< P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
< Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: SAMEORIGIN
< 
{ [8192 bytes data]
HTTP/1.1 200 OK

HTTP/1.1 200 OK
Content-Length: 37816
X-Xss-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
X-Content-Type-Options: nosniff
Content-Encoding: br
Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
Set-Cookie: VISITOR_INFO1_LIVE=fyZ4n8efeLg; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT; httponly
Set-Cookie: PREF=f1=50000000; path=/; domain=.youtube.com; expires=Tue, 27-Mar-2018 15:48:55 GMT
Set-Cookie: YSC=rkDPEq2ofAM; path=/; domain=.youtube.com; httponly
Strict-Transport-Security: max-age=31536000
Expires: Tue, 27 Apr 1971 19:44:06 EST
Server: YouTubeFrontEnd
X-Head-Content-Length: 
Cache-Control: no-cache
Date: Thu, 27 Jul 2017 03:55:55 GMT
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
Content-Type: text/html; charset=utf-8
X-Frame-Options: SAMEORIGIN

'''

**Comment by fiefdx** [comment]
@yuyistar @simonasd  目前找到一个不用改代码的方法，只需要添加一个youtube-dl的参数：
youtube-dl --add-header "accept-encoding: identity" --proxy "127.0.0.1:8087" --no-check-certificate  https://www.youtube.com/watch?v=aofJSEoAZqA

**Comment by raawaa** [comment]
@fiefdx 我试了一下不行，依然报错😭

**Comment by yuyistar** [comment]
对，我也试了，不行，会不会和python或者ffmpeg，我看安装攻略里面让配置这些，但是也都正确配置了

**Comment by fiefdx** [comment]
@yuyistar @raawaa 我是直接在运行的 XX-Net-3.3.5/code/default/gae_proxy/local/proxy.py 来测试的，
youtube-dl的版本是：
$ youtube-dl --version
2017.01.05

下面是两次尝试的输出，加了参数的可以，不加参数的会报错

$ youtube-dl --add-header "accept-encoding: identity" --proxy "127.0.0.1:8087" --no-check-certificate 'https://www.youtube.com/watch?v=A9WxTeLwVmc&spfreload=10'
[youtube] A9WxTeLwVmc: Downloading webpage
[youtube] A9WxTeLwVmc: Downloading video info webpage
[youtube] A9WxTeLwVmc: Extracting video information
[youtube] A9WxTeLwVmc: Downloading MPD manifest
[dashsegments] Total fragments: 113
[download] Destination: 秋激拉~武界合歡東進武嶺樂遊趣-完整版-A9WxTeLwVmc.f137.mp4
[download] 3.8% of ~238.28MiB at 76.97KiB/s ETA 40:46^C
ERROR: Interrupted by user

$ youtube-dl --proxy "127.0.0.1:8087" --no-check-certificate 'https://www.youtube.com/watch?v=A9WxTeLwVmc&spfreload=10'[youtube] A9WxTeLwVmc: Downloading webpage
[youtube] A9WxTeLwVmc: Downloading video info webpage
ERROR: A9WxTeLwVmc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yuyistar** [comment]
@fiefdx proxy.py是怎么用呀，是吧youtube-dl，copy到那个目录下，然后执行命令吗。如果是的话我还是没有成功，代码如下
C:\Program Files (x86)\XX-Net-3.2.8\code\default\gae_proxy\local>youtube-dl --ad
d-header "accept-encoding: identity" --proxy "127.0.0.1:8087" --no-check-certifi
cate 'https://www.youtube.com/watch?v=A9WxTeLwVmc&spfreload=10'
WARNING: The url doesn't specify the protocol, trying with http
[generic] watch?v=A9WxTeLwVmc: Requesting header
WARNING: Could not send HEAD request to http://'https://www.youtube.com/watch?v=
A9WxTeLwVmc: HTTP Error 600:
[generic] watch?v=A9WxTeLwVmc: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 600:  (caused by HTTPError()); ple
ase report this issue on https://yt-dl.org/bug . Make sure you are using the lat
est version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
'spfreload' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by fiefdx** [comment]
@yuyistar 你这个报错不是“token”的那个问题，是windows命令行的问题，没有必要在gae_proxy/local下运行的
windows下用：
youtube-dl --add-header "accept-encoding: identity" --proxy "127.0.0.1:8087" --no-check-certificate https://www.youtube.com/watch?v=A9WxTeLwVmc^&spfreload=10

**注意'^'转义'&' => '^&'**

**Comment by raawaa** [comment]
@fiefdx 我是archlinux，youtube-dl版本是2017.07.23。
之前是没有问题的，升级了youtube-dl版本之后发生了token的报错。不知道是不是跟新版本有关系。

**Comment by fiefdx** [comment]
@raawaa 这个我就不确定了，我也只是在用goagent+youtube-dl的时候碰到token的报错，顺便自己拿源码调试了下，发现goagent返回的内容与youtube-dl请求的格式不符，加--add-header "accept-encoding: identity"也只是强制goagent返回明文内容而已，这样youtube-dl就可以解析出相应信息了

**Comment by N46AN** [comment]
我使用以下命令下载视频，仍然出错。出错信息与 you-get https://github.com/XX-net/XX-Net/issues/6084 类似 。
```
$ youtube-dl --add-header "accept-encoding: identity" --proxy "127.0.0.1:8087" --no-check-certificate  https://www.youtube.com/watch?v=hEnyvdvS6UQ
[youtube] hEnyvdvS6UQ: Downloading webpage
[youtube] hEnyvdvS6UQ: Downloading video info webpage
[youtube] hEnyvdvS6UQ: Extracting video information
[youtube] hEnyvdvS6UQ: Downloading js player vflN55NZo
^C
ERROR: Interrupted by user
```

与此同时：
```
Aug 03 17:21:22.617 - [DEBUG] ssl_closed 173.194.151.74
Aug 03 17:21:22.618 - [DEBUG] 173.194.151.74 worker close:idle timeout
Aug 03 17:21:23.892 - [DEBUG] GAE GET https://www.youtube.com/watch?v=hEnyvdvS6UQ&gl=US&hl=en&has_verified=1&bpctr=9999999999

Aug 03 17:21:31.655 - [DEBUG] sort ip time:45ms
Aug 03 17:21:31.660 - [DEBUG] get ip:173.194.151.74 t:651
Aug 03 17:21:32.721 - [DEBUG] create_ssl update ip:173.194.151.74 time:651 h2:0
Aug 03 17:21:37.725 - [DEBUG] get ip:216.58.202.180 t:745
Aug 03 17:21:41.728 - [DEBUG] 216.58.202.180 fail:timeout('timed out',)
Aug 03 17:21:41.729 - [DEBUG] report_connect_fail:216.58.202.180
Aug 03 17:21:41.775 - [DEBUG] sort ip time:45ms
Aug 03 17:21:41.780 - [DEBUG] get ip:173.194.30.236 t:753
Aug 03 17:21:45.163 - [INFO] GAE t:21268 s:185852 GET https://www.youtube.com/watch?v=hEnyvdvS6UQ&gl=US&hl=en&has_verified=1&bpctr=9999999999 h2
_get_head:16672,h2_finish[SP:40672]:4583
Aug 03 17:21:45.630 - [DEBUG] GAE GET https://www.youtube.com/get_video_info?el=info&ps=default&video_id=hEnyvdvS6UQ&hl=en&sts=17379&gl=US&eurl=
Aug 03 17:21:46.691 - [DEBUG] create_ssl update ip:173.194.30.236 time:4426 h2:0
Aug 03 17:21:46.937 - [INFO] GAE t:1305 s:19667 GET https://www.youtube.com/get_video_info?el=info&ps=default&video_id=hEnyvdvS6UQ&hl=en&sts=173
79&gl=US&eurl= h2_get_head:542,h2_finish[SP:26719]:754
Aug 03 17:21:47.439 - [DEBUG] GAE GET https://www.youtube.com/yts/jsbin/player-vflN55NZo/en_US/base.js
Aug 03 17:21:48.480 - [INFO] RangeFetch 0-1249368 started('https://www.youtube.com/yts/jsbin/player-vflN55NZo/en_US/base.js') 
Exception in thread Thread-304:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/simon/Apps/XX-Net-3.2.3/code/3.3.6/gae_proxy/local/gae_handler.py", line 613, in fetch_worker
    self.fetch(begin, end, None)
  File "/home/simon/Apps/XX-Net-3.2.3/code/3.3.6/gae_proxy/local/gae_handler.py", line 649, in fetch
    response.worker.close("range status:%s", response.status)
TypeError: close() takes at most 2 arguments (3 given)

Aug 03 17:21:50.647 - [WARNING] 64.233.170.114 _consume_single_frame:ConnectionResetError()
Aug 03 17:21:50.648 - [DEBUG] ssl_closed 64.233.170.114
Aug 03 17:21:50.649 - [DEBUG] 64.233.170.114 worker close:disconnect:ConnectionResetError()
Aug 03 17:21:52.226 - [WARNING] 64.233.163.153 _consume_single_frame:ConnectionResetError()
Aug 03 17:21:52.228 - [DEBUG] ssl_closed 64.233.163.153
Aug 03 17:21:52.228 - [DEBUG] 64.233.163.153 worker close:disconnect:ConnectionResetError()
Aug 03 17:21:52.250 - [WARNING] 216.58.206.103 _consume_single_frame:ConnectionResetError()
Aug 03 17:21:52.254 - [DEBUG] ssl_closed 216.58.206.103
Aug 03 17:21:52.255 - [DEBUG] 216.58.206.103 worker close:disconnect:ConnectionResetError()
Exception in thread Thread-291:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/simon/Apps/XX-Net-3.2.3/code/3.3.6/gae_proxy/local/gae_handler.py", line 613, in fetch_worker
    self.fetch(begin, end, None)
  File "/home/simon/Apps/XX-Net-3.2.3/code/3.3.6/gae_proxy/local/gae_handler.py", line 649, in fetch
    response.worker.close("range status:%s", response.status)
TypeError: close() takes at most 2 arguments (3 given)

Aug 03 17:21:52.862 - [WARNING] 216.58.204.47 _consume_single_frame:ConnectionResetError()
Aug 03 17:21:52.864 - [DEBUG] ssl_closed 216.58.204.47
Aug 03 17:21:52.864 - [DEBUG] 216.58.204.47 worker close:disconnect:ConnectionResetError()
Aug 03 17:21:56.745 - [DEBUG] ip:216.58.202.180 real fail
Aug 03 17:21:56.821 - [DEBUG] RangeFetch [172.217.11.130] 43% length:548576 range:bytes 0-548575/1249369 https://www.youtube.com/yts/jsbin/playe
r-vflN55NZo/en_US/base.js h2_get_head:543,h2_finish[SP:62141]:8832
Aug 03 17:22:02.988 - [DEBUG] sort ip time:88ms
Aug 03 17:22:03.000 - [DEBUG] get ip:216.58.206.103 t:642
Aug 03 17:22:03.401 - [DEBUG] get ip:64.233.170.114 t:655
Aug 03 17:22:03.903 - [DEBUG] get ip:216.58.204.47 t:668
Aug 03 17:22:04.491 - [DEBUG] create_ssl update ip:216.58.206.103 time:855 h2:1
Aug 03 17:22:04.492 - [DEBUG] get ip:64.233.163.153 t:712
Aug 03 17:22:04.911 - [DEBUG] get ip:173.194.178.146 t:769
Aug 03 17:22:05.199 - [DEBUG] create_ssl update ip:216.58.204.47 time:871 h2:1
Aug 03 17:22:05.414 - [DEBUG] get ip:173.194.163.106 t:888
Aug 03 17:22:05.495 - [DEBUG] get ip:172.217.29.178 t:904

```

**Comment by yuyistar** [comment]
@fiefdx 感谢已经搞定了

**Comment by emacsenli** [comment]
我ssr直接用proxychains4 youtube-dl...

2017年8月6日 下午3:25，"yuyistar" <notifications@github.com>写道：

@fiefdx <https://github.com/fiefdx> 感谢已经搞定了

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/XX-net/XX-Net/issues/6074#issuecomment-320490738>, or mute
the thread

**Comment by rmouse** [comment]
@yuyistar 怎么搞定的？

**Comment by yuyistar** [comment]
看上面的回复

**Comment by zhufenggood** [comment]
@fiefdx 谢了，我也是４月开始goagent youtube-dl就不好用了，现在终于好了。

**Comment by wxy** [comment]
@fiefdx 谢谢，我只加了 `--add-header "accept-encoding: identity"` 即可。

**Comment by Token713** [comment]
@fiefdx
2017.10.29

>youtube-dl --add-header "accept-encoding: identity" --proxy "127.0.0.1:8087" --
no-check-certificate https://www.youtube.com/watch?v=JmvCpR45LKA
[youtube] JmvCpR45LKA: Downloading webpage
[youtube] JmvCpR45LKA: Downloading video info webpage
ERROR: JmvCpR45LKA: "token" parameter not in video info for unknown reason; plea
se report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.

**Comment by xxnet** [comment]
​估计是br压缩算法问题。
x-tunnel 没有这个问题，先用x-tunnel吧

**Comment by raawaa** [comment]
@fiefdx 非常感谢，昨天又试了一下你的方法，可以正常下载了。
💖💖💖
