### ISSUE TITLE
http代理的安全性

### ISSUE THREAD

**Issue by china-shang** [XX-net/XX-Net#6077]
在本地服务器与gae服务器之间使用的是http协议，不是很容易遭到中间人攻击吗？

在访问https网页的时候浏览器与本地服务器进行https通信，而本地服务器解密后，然后通过http发送到gae服务器，而gae服务器与原本服务器进行https通信，这样在本地服务器与gae服务器之间不是完全明文传送了

**Comment by jzp820927** [comment]
关于技术上的问题，建议你 google 搜索下，肯定会找到答案，客户端与 GAE 是 https 连接，不是 http。

**Comment by THLIVSQAZ** [comment]
楼上正解,只有xx-net传给浏览器或者其他代理设备才是明文

**Comment by china-shang** [comment]
那gae的证书应该能保证不会被任何人获得吧

**Comment by THLIVSQAZ** [comment]
证书自己本地生成，自行保管好，不泄露是其他人没法解密的

**Comment by china-shang** [comment]
本地生成的证书是本地服务器与客户端进行https通讯的吧，应该不是与gae进行通讯的，就算是那么gae服务器也根本不能对证书进行验证，因为并没有上传证书到gae端

**Comment by dou4cc** [comment]
http代理不是明文

**Comment by china-shang** [comment]
那么本地与gae端进行https通信，服务端证书是谁提供的，另一端怎么在没有证书的情况下进行验证证书？

**Comment by china-shang** [comment]
我觉得可以在部署gae的时候生成证书，然后把服务端证书上传至gae，客户端证书留在本地，只是这样如果需要在其他主机的xxnet使用AppID的时候就复制该客户端证书至该主机，虽然变麻烦了点，但是基本上就能保证与gae通讯的安全了

**Comment by theratlesnake** [comment]
朝廷大内高手众多，要找你翻墙的，还不是轻而易举，SS都能干掉，xx更不在话下
