### ISSUE TITLE
访问google系的网站速度越来越慢

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#6099]
大概从上周开始，访问google系的网站（google搜索、gmail、google scholar、youtube等）速度越来越慢，gmail经常要刷新好多次才能打开一封邮件；youtube前一段可以看720p的电影，现在360P都要缓冲。

看来确实封锁越来越严了。

xx-net 版本 3.31, IP可用数量1300多，IP延迟 300多。

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1367
network-status: OK
connected-link: new:5 used:0
worker: h1:0 h2:21
scan-ip-thread-num: 50
ip-quality: 303
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by whhxmwhh** [comment]
访问所有的外网都是变慢。速度大约是原来的10%左右。
在总出口增加识别检测。

**Comment by SLDeongaree** [comment]
我感觉只是Google系的网站访问受限，其他的速度依然很快。
![image](https://user-images.githubusercontent.com/29051450/28549813-581b4d9e-710f-11e7-852c-8ce0e13fb2a3.png)

**Comment by zhencaihao** [comment]
昨天晚上还看过youtube。刚才电脑死机，重启后XX-NET IP变0，导入以前备份的IP后进youtube显示 504 连接超时，休息一会再来。google何以进。

**Comment by mayichen1987** [comment]
升级3.3.4

**Comment by theratlesnake** [comment]
4月5月的时候，速度超级快，现在特殊时期，慢也正常，没啥好说的。
