### ISSUE TITLE
真的非常好用，但是如何才能开机自动启动呢？

### ISSUE THREAD

**Issue by kahrpba2100** [XX-net/XX-Net#61]
除了快捷方式我都不知道该用哪个文件启动，任务计划无从添加啊！

**Comment by kahrpba2100** [comment]
好像新版本可以自动启动？那么问题就是如何才能升级呢？

**Comment by xxnet** [comment]
谢谢！

关于开机自动启动：
http://127.0.0.1:8085/?module=launcher&menu=config
看到第一个，点击右边打开就可以了。

**Comment by xxnet** [comment]
先手动下载新版本覆盖吧，自动升级下周开始做。

**Comment by kahrpba2100** [comment]
嗯，新版本覆盖以后我要做什么呢？是不是config里面账号密码重填一下？我填了，点保存没反应啊。
