### ISSUE TITLE
调整PROXY.INI解决YouTube的上传者已禁止在您的国家/地区播放此视频的问题

### ISSUE THREAD

**Issue by shinji-ikari** [XX-net/XX-Net#610]
https://code.google.com/p/goagent/issues/detail?id=10837
貌似GAE的有解决办法.不过开了一下PROXY.INI.直接用NOTE.EXE打开是一堆黏在一起.无从下手.
请问有谁知道该怎么调整吗?

**Comment by xxnet** [comment]
因为这个文件是unix格式，notepad不能处理，可以试试ultraedit或者editplus等工具进行编辑。

下次把这个文件强制改成dos格式看看

在 2015年7月14日 上午1:17，shinji-ikari <notifications@github.com>写道：

**Comment by yuliangyang** [comment]
http://wallfans.eu.org/xxnet-problem_youtube/
看这把。已经解决了。

**Comment by yuliangyang** [comment]
请关注http://wallfans.eu.org
任何xxent、goagent相关问题解决不了，上这找找。如果有问题这没有，给我留个言。我去上教程

**Comment by shinji-ikari** [comment]
感谢,十分感谢.
P.S. 网站收藏了,感谢推荐

**Comment by Veeson** [comment]
虽然可以解决，但是速度会拖慢很多。
