### ISSUE TITLE
pc端ok，iphone代理提示请检查浏览器代理设置，证书也下载安装

### ISSUE THREAD

**Issue by yabaoer** [XX-net/XX-Net#6124]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1782 good:315
network-status: OK
connected-link: new:2 used:0
worker: h1:15 h2:4
scan-ip-thread-num: 100
ip-quality: 361
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by leiy88** [comment]
iPhone怎么代理?
