### ISSUE TITLE
server/gae/gae.py中为什么要有这么一段代码？

### ISSUE THREAD

**Issue by lzhr** [XX-net/XX-Net#6140]
```
 yield 'GoAgent Python Server %s works, deployed at %s\n' % (__version__, ctime)
 if len(__password__) > 2:
    yield 'Password: %s%s%s' % (__password__[0], '*'*(len(__password__)-2), __password__[-1])
```
特别是返回密码信息

**Comment by SeaHOH** [comment]
备忘？
这么处理的确不太好，我要是忘了就直接重传。

**Comment by china-shang** [comment]
代码的意思是在__password长度大于2，就yield ‘Password ：（密码第一位）（密码长度－2个*号）（密码最后一位） 
实际上password没用，看了看代码，不管你怎么设置都不使用rc4加密，所以设密码什么的都是让你心里安慰

**Comment by lzhr** [comment]
@china-shang   没说需要加密，这个密码不是可以一定程度防止别人盗用流量？
```
    if __password__ and __password__ != kwargs.get('password', ''):
        yield format_response(403, {'Content-Type': 'text/html; charset=utf-8'}, message_html('403 Wrong password', 'Wrong password(%r)' % kwargs.get('password', ''), 'GoAgent proxy.ini password is wrong!'))
        raise StopIteration
```
![qq](https://user-images.githubusercontent.com/6972978/28770536-15b9c5f4-7612-11e7-801d-ba98ffe9b262.png)

**Comment by china-shang** [comment]
客户端是可以肯定没有用rc4加密的，不是有些人以为的会在gae与客户端之间加密
![2017-08-01 14-17-50](https://user-images.githubusercontent.com/17249688/28812188-1e4db054-76c6-11e7-87a6-5e21b146c9a9.png)

**Comment by lzhr** [comment]
@china-shang 我提的issue和rc4加密没有关系
