### ISSUE TITLE
浏览器代理和CA证书状态均为fail，提示请检查浏览器代理设置。

### ISSUE THREAD

**Issue by raywang-nx** [XX-net/XX-Net#6156]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:11909
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by lzhr** [comment]
一万个IP从哪儿来的？！

https://github.com/XX-net/XX-Net/wiki/安装和使用-SwitchyOmega

**Comment by raywang-nx** [comment]
@lzhr IPV6，IP会比较多，但是连不上。switchyomega这个帖子我也看过了，不行

**Comment by raywang-nx** [comment]
目前还是这个情况，不过可以正常使用了。
