### ISSUE TITLE
好迷啊

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#6158]
昨天一直没有ip，到今天早上还是这样，然后电脑开着让它扫，出去了一下，回来3000ip，用到了晚上，刚去洗了个澡，突然就这样子了
![1372wplgn0 g1iek n 9ix0](https://user-images.githubusercontent.com/20419070/28831846-7540a5be-770d-11e7-9b96-41867330b471.png)

**Comment by zanewayne78** [comment]
假ip？也许你的那个本地ip掉包封锁比较严重，重新拨号换个ip试试

**Comment by luminouser** [comment]
不同的网络供应商封锁程度虽然是存在差别，但是你的情况看起来不是供应商的问题。

**Comment by luminouser** [comment]
不同的网络供应商封锁程度虽然是存在差别，但是你的情况看起来不是供应商的问题。
