### ISSUE TITLE
我想在2.9.7的基础上添加Options，请问怎么修改？谢谢

### ISSUE THREAD

**Issue by mssues** [XX-net/XX-Net#6167]
@xxnet @yeahwu @SeaHOH 
我想在2.9.7的基础上添加Options请求，请问怎么修改？谢谢参考https://github.com/XX-net/XX-Net/commit/d89e35be6db878ec82281593276354c6fe37a4c1
最后谢谢

**Comment by SeaHOH** [comment]
先说结论，“旧版本在某些方面比新版使用更方便”，对于某些商业软件来说这是现实，但就绝大部分非商业软件来讲，尤其是开源作品，这就是个偏见。
1. 你是想用 `rc4` 加密吧，没有必要，https 链接已经足够安全，要改进也不是倒退用 `rc4`。
1. 正常现象，原因很多，不用修改。新版也有，只是没有输出日志给你看，因为没有必要。
1. 正常现象，这是扫描时发现这个 IP 受到了干扰，告诉你一下而已。

**Comment by phuslu** [comment]
我疑心和 http2 有关，也许应该提供一个选项控制 http2 的开关，（默认关闭)

**Comment by mssues** [comment]
@SeaHOH 不是想添加rc4 ，是想添加Options请求，这个在3.1.7添加的，我想把它添加到2.9.7中，谢谢！

**Comment by SeaHOH** [comment]
@mssues 
Options 相关的两块代码很清晰，照着位置加上就行。

@phuslu 
第 3 条吗？看这个 IP 就是被干扰的节奏，错误提示也是，哪里不对吗？
不过我觉得在不太影响使用的情况下 X 大不会再增加特性了。

**Comment by mssues** [comment]
@SeaHOH 
您能不能帮我看看怎么添加，我昨天修改了半天老是出错，这个commit https://github.com/XX-net/XX-Net/commit/d89e35be6db878ec82281593276354c6fe37a4c1修改了12个文件，光添加OPTIONS的话要修改哪些？谢谢！

**Comment by SeaHOH** [comment]
这两块
https://github.com/XX-net/XX-Net/commit/d89e35be6db878ec82281593276354c6fe37a4c1#diff-cc5e935662f23df245644fccc2a958f8L213
https://github.com/XX-net/XX-Net/commit/d89e35be6db878ec82281593276354c6fe37a4c1#diff-cc5e935662f23df245644fccc2a958f8L121

**Comment by mssues** [comment]
谢谢谢谢！！！
