### ISSUE TITLE
xx-net自动扫描IP机制

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net#618]
说是xx-net能自动扫描IP，请问我一般上网半个小时左右就断网，然后再上网，如此反复循环，那么xx-net自动扫描IP的机制还能正常工作吗？
求解释xx-net自动扫描IP的工作机制！O(∩_∩)O谢谢

**Comment by xxnet** [comment]
自动扫描机制：
+ 后台开线程，不断从ip范围中，随机选择一个ip进行测试
+ 找到好的ip，放入可用ip库中去使用
+ 默认线程数50个，最近添加了自动调节功能，扫描到认为足够的ip，就会变慢甚至挺下来
+
认为足够ip的判断规则：以ip的ssl握手时间进行排序，第100个ip的握手时间，进行计算，如果小于200ms，可以暂停扫描，大于300ms的全速扫描
+ 只记录连接成功，对于连接失败，不会影响后续的扫描

在 2015年7月16日 上午10:09，redstoneleo <notifications@github.com>写道：

**Comment by redstoneleo** [comment]
多谢多谢！！！
我上网半个小时左右就断网，然后再上网，这时候xx-net会重新检测网络是否已经连接然后扫描IP吗？

**Comment by xxnet** [comment]
会不断尝试的，没有问题

在 2015年7月16日 下午12:40，redstoneleo <notifications@github.com>写道：

**Comment by ARwMq9b6** [comment]
@xxnet 请问已扫过的 IP 会被扫第二遍吗？我想用里面的扫描 IP 功能，但是想让每个 IP 只扫描一遍就结束扫描或提示扫描已结束。

如填一个 IP 段 0.0.0.0 - 1.1.1.1 ，从 0.0.0.0 开始按顺序扫，重开机后会从上次扫描结束的位置继续扫，一直扫的 1.1.1.1 结束。

checkgoogleip 能实现扫描 IP 功能，但是不是按顺序的，要把已扫过的 IP 放进内存，用久了内存占用太大。 

另外我还想要输出类似 scan_ip.log 这样的文件，要包含更多公司的 IP （或全部 HTTPS 有效的 IP），因为 Akamai 之类的 CDN 服务商的 IP 留着很有用。

**Comment by xxnet** [comment]
ip库太大，目前已经接近百万级别的规模。

为了扫描的稳定性，采用随机挑选ip的策略，而不是顺序扫描，也不会记录扫描过的ip。

如果你会一点python或者类似的编程语言，可以试着调用check_ip里的函数，花点时间看看源码，不会太复杂。
至少单线程实现并不难。

要多线程实现，需要有相关的编程经验，做好锁保护。

在 2015年7月17日 下午5:27，ARwMq9b6 <notifications@github.com>写道：

**Comment by ARwMq9b6** [comment]
多谢 xxnet. 你的 GoAgent 的 Google Group 论坛进展如何？

**Comment by xxnet** [comment]
只是一个准备，到8月大家需要有一个地方去的时候，不至于找不到组织

2015-07-17 20:34 GMT+08:00 ARwMq9b6 <notifications@github.com>:
