### ISSUE TITLE
改了自动扫描ip数后config.inf的数据就被重置

### ISSUE THREAD

**Issue by dgfrwx** [XX-net/XX-Net#6193]
导致youtube又不能搜索，又要重新在config修改一次，好麻烦啊

**Comment by lzhr** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config

**Comment by dgfrwx** [comment]
@lzhr 小白表示看不懂这些语法，求简单讲怎么避免在改扫描ip数之后避免config.inf的[host]有关的数据被重置

**Comment by lzhr** [comment]
新建一个data/gae_proxy/manual.ini，所有修改在manual.ini中进行，
不要修改 config.ini 和proxy.ini的内容。

```
[hosts]
.youtube.com=gae
.yting.com=gae
```
