### ISSUE TITLE
继续提问:用新版本覆盖旧版本,在配置里面填上账号密码，点保存并重启没有任何反应啊！

### ISSUE THREAD

**Issue by kahrpba2100** [XX-net/XX-Net#62]
旧版本的时候会有success的提示呢。

下次启动这里仍然是空的。

**Comment by xxnet** [comment]
你的是什么版本，我刚测试1.3.1，是有提示success。

请把状态页和日志发上来分析。

**Comment by kahrpba2100** [comment]
好了好了，我也是1.3.1.刚才看了你的贴，想到重启一下电脑，再输入就好了！
