### ISSUE TITLE
上传用户已禁止在您的国家/地区播放此视频

### ISSUE THREAD

**Issue by dgfrwx** [XX-net/XX-Net#6203]
Ke$ha - TiK ToK不能播放涉黄吗？

**Comment by dgfrwx** [comment]
![20170806233658](https://user-images.githubusercontent.com/30223562/29004802-90567698-7b00-11e7-8021-d3a5d83f3707.png)

**Comment by dgfrwx** [comment]
爱奇艺也有啊，难道是版权原因？

**Comment by dgfrwx** [comment]
![20170806235041](https://user-images.githubusercontent.com/30223562/29004898-125a060e-7b02-11e7-934e-8f3902492d64.png)

**Comment by lzhr** [comment]
#5701

**Comment by dgfrwx** [comment]
@lzhr 看不懂怎么弄？大佬教教俺！
