### ISSUE TITLE
XX-NET界面打不开：无法访问此网站，127.0.0.1 的响应时间过长。

### ISSUE THREAD

**Issue by Lily9694** [XX-net/XX-Net#6206]
## 问题内容
最新版本XX-NET  3.3.1，运行之后，界面无法打开，显示：
![qq 20170807100147](https://user-images.githubusercontent.com/30786473/29009623-6b5d99dc-7b57-11e7-9a6f-326e457ae751.png)

运行网络诊断，提示：
![2](https://user-images.githubusercontent.com/30786473/29009654-b4da72c4-7b57-11e7-86cb-7c61c3d88bd7.png)

#### 获取诊断信息
无（由于界面打不开）
#### 获取日志
无（界面打不开）

**Comment by Lily9694** [comment]
今天再看发现可以了，不晓得是什么原因

**Comment by skyremind** [comment]
同问题。。
