### ISSUE TITLE
校园网IPV6连不上XXnet，显示尚未建立连接

### ISSUE THREAD

**Issue by raywang-nx** [XX-net/XX-Net#6211]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:11987
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: Connect Blocked, 4 seconds to wait.
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by candy2107** [comment]
检查所有ip

**Comment by raywang-nx** [comment]
启用IPv6失败，请确认你的网络支持IPv6。   
IPV4能用，但IPV6就不行

**Comment by raywang-nx** [comment]
目前解决问题了，通过配置文件开打ipv6，https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

[google_ip]  
use_ipv6 = 1
max_check_ip_thread_num = 20     
max_good_ip_num = 3000            
ip_connect_interval = 10
