### ISSUE TITLE
今天突然ip都没掉了，就剩16个了。延迟1385，这是什么情况？公司是杭州电信的网络。

### ISSUE THREAD

**Issue by JasonQWJ** [XX-net/XX-Net#6214]
开google，页面显示一行：

gae_exception:GAE_Exception() https://www.google.com/

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2999 good:16
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:13
scan-ip-thread-num: 500
ip-quality: 1385
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by lefantian** [comment]
好像GFW全力开动，北方联通也差不多，早上少的时候快到个位数了

本地网络状态	OK
IP数量	43
空闲	0
IP延迟	861

**Comment by JasonQWJ** [comment]
@lefantian 有没有切换线路之类的方法？完全不想用baidu，根本查不到东西。

**Comment by dsgys** [comment]
过几天就好了,我这半月前只有几个,现在3000满血

**Comment by dsgys** [comment]
或者可以试试换一下IP,我这43开头的根本搜不到,得180的,166的也凑合

**Comment by JasonQWJ** [comment]
@dsgys  你说的是换dns？

**Comment by dsgys** [comment]
不是换DNS,是断开本地网络重新连一下,如果本地IP的第一位能变化,那还有戏,如果不变那就完了,只能等一段时间了

**Comment by XueTeng2** [comment]
电信封IP最厉害，我在学校用电信网就只有20几个IP，同学用移动网有2000+IP。

**Comment by lefantian** [comment]
@JasonQWJ 不挂VPN 我只用bing.com

**Comment by JasonQWJ** [comment]
@dsgys 那不好意思 把公司的网总是重新拨号。。。。

**Comment by JasonQWJ** [comment]
公司快下班了，重启了几次路由器，网段变成了60.xxx.xxx.xxx，ip上去了，延迟也1000以下了。。。哈哈哈

**Comment by out0fmemory** [comment]
试试https://github.com/out0fmemory/GoAgent-Always-Available

**Comment by naoh2004** [comment]
@out0fmemory 下了你这个不能用啊
