### ISSUE TITLE
你们还用别的什么方式？

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#622]

**Comment by EdwardDX** [comment]
VPN

**Comment by JebYore** [comment]
Lantern

**Comment by lihuayahaitang** [comment]
求蓝灯最新版下载地址啊

**Comment by cdmask** [comment]
@JebYore Lantern不是要好友吗？我下了蓝灯但是没有好友资源。。可否相助？

**Comment by cdmask** [comment]
@EdwardDX 我也用VPN但有时候也不稳定。

**Comment by cdmask** [comment]
@lihuayahaitang 就在github里面搜索lantern就可以找到。

**Comment by JebYore** [comment]
Lantern也有自己的服务器的，可以不通过好友这一途径来用。目前最新2.0.0 beta 7源码出了，但还没有可执行文件。可以用beta 6版的，地址https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions

**Comment by cdmask** [comment]
我昨天下载的，界面里面看到只有两个服务器，然后很卡。

**Comment by JebYore** [comment]
如果能连上日本节点，Lantern速度是比较快的。对了，windows下还可以用Psiphon，这几个是我的备胎，现在正好能用上。

**Comment by cdmask** [comment]
lantern beta6没有节点选择啊。打开就直接连接的。这两个都有一些网站打不开。比如说谷歌学术。

**Comment by lihuayahaitang** [comment]
晕= =忘记lantern使用方法了。。

在 2015-07-17 11:28:45，"cdmask" <notifications@github.com> 写道：


lantern beta6没有节点选择啊。打开就直接连接的。这两个都有一些网站打不开。比如说谷歌学术。

**Comment by cdmask** [comment]
@lihuayahaitang 直接下载 安装 就是。https://github.com/getlantern/lantern/wiki/Lantern-Beta-Versions
