### ISSUE TITLE
在manual.ini里面输入[profile] .youtube.com = withphp发现批突然剧烈变少

### ISSUE THREAD

**Issue by dgfrwx** [XX-net/XX-Net#6221]
突然发现ip剧烈变少，求大佬帮忙怎么取消这个指令，取消指令有什么方法

**Comment by lzhr** [comment]
你用的什么版本，php模块早移除了

**Comment by dgfrwx** [comment]
我的xxnet3.3.4 goagent3.3.1感觉在manual.ini输入这个
[profile]
.youtube.com = withphp之后ip好像发现有效ip突然减少很多的样子

**Comment by dgfrwx** [comment]
@lzhr 调了大了自动ip扫描线速到200后有效才慢慢恢复增多，通常只调90这样有效ip就不会减少了

**Comment by dgfrwx** [comment]
@lzhr 我只想问怎么取消[profile]
.youtube.com = withphp这个指令的影响

**Comment by lzhr** [comment]
把诊断信息和日志去敏贴出来

**Comment by dgfrwx** [comment]
诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
xxnet-version: 3.3.4

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2687
network-status: OK
connected-link: new:2 used:0
worker: h1:11 h2:11
scan-ip-thread-num: 88
ip-quality: 452
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
有问题吗？

**Comment by dgfrwx** [comment]
GAEProxy日志
Aug 08 20:24:45.989 - [DEBUG] 189.247.145.163 fail:timeout('timed out',)
Aug 08 20:24:45.989 - [DEBUG] report_connect_fail:189.247.145.163
Aug 08 20:24:48.839 - [DEBUG] ip:181.198.79.89 real fail
Aug 08 20:24:52.635 - [DEBUG] GET http://www.twitter.com/xxnet
Aug 08 20:24:52.679 - [DEBUG] GET http://www.twitter.com/xxnet
Aug 08 20:24:53.841 - [DEBUG] ip:111.95.240.219 real fail
Aug 08 20:24:54.873 - [INFO] scan_ip add ip:196.46.1.246 time:1983
Aug 08 20:24:54.892 - [INFO] remove_slowest_ip:196.46.1.246 handshake_time:1983, fails:0
Aug 08 20:24:54.918 - [DEBUG] restore ip:109.110.33.114
Aug 08 20:24:56.945 - [INFO] scan_ip add ip:203.207.55.246 time:953
Aug 08 20:24:56.954 - [INFO] remove_slowest_ip:178.23.236.145 handshake_time:674, fails:1
Aug 08 20:24:56.954 - [INFO] remove_slowest_ip:103.20.141.41 handshake_time:672, fails:1
Aug 08 20:24:59.920 - [DEBUG] ip:201.248.76.116 real fail
Aug 08 20:25:04.921 - [DEBUG] ip:201.151.207.56 real fail
Aug 08 20:25:06.843 - [INFO] scan_ip add ip:216.58.206.113 time:819
Aug 08 20:25:06.859 - [INFO] remove_slowest_ip:112.72.5.112 handshake_time:672, fails:1
Aug 08 20:25:09.922 - [DEBUG] ip:116.58.204.85 real fail
Aug 08 20:25:10.819 - [INFO] scan_ip add ip:96.127.250.55 time:631
Aug 08 20:25:10.839 - [INFO] remove_slowest_ip:180.149.91.83 handshake_time:672, fails:1
Aug 08 20:25:14.924 - [DEBUG] ip:116.58.204.81 real fail
Aug 08 20:25:19.925 - [DEBUG] ip:190.113.97.232 real fail
Aug 08 20:25:24.926 - [DEBUG] ip:103.244.186.210 real fail
Aug 08 20:25:24.931 - [INFO] scan_ip add ip:92.226.2.93 time:488
Aug 08 20:25:24.942 - [INFO] remove_slowest_ip:178.23.236.151 handshake_time:672, fails:1
Aug 08 20:25:25.145 - [INFO] scan_ip add ip:207.237.69.115 time:628
Aug 08 20:25:25.160 - [INFO] remove_slowest_ip:190.212.166.169 handshake_time:672, fails:1
Aug 08 20:25:26.647 - [DEBUG] restore ip:186.46.140.83
Aug 08 20:25:27.235 - [DEBUG] 210.187.22.151 close:host pool alive_timeout
Aug 08 20:25:27.236 - [DEBUG] ssl_closed 210.187.22.151
Aug 08 20:25:28.604 - [DEBUG] restore ip:203.252.15.184
Aug 08 20:25:29.092 - [DEBUG] restore ip:59.18.45.249
Aug 08 20:25:29.251 - [DEBUG] 62.4.253.87 close:host pool alive_timeout
Aug 08 20:25:29.251 - [DEBUG] ssl_closed 62.4.253.87
Aug 08 20:25:31.602 - [INFO] scan_ip add ip:59.18.35.166 time:187
Aug 08 20:25:31.654 - [DEBUG] sort ip time:52ms
Aug 08 20:25:31.654 - [INFO] remove_slowest_ip:201.248.78.101 handshake_time:671, fails:1
Aug 08 20:25:31.655 - [INFO] remove_slowest_ip:190.92.89.26 handshake_time:671, fails:1
Aug 08 20:25:31.655 - [INFO] remove_slowest_ip:120.28.53.158 handshake_time:671, fails:1
Aug 08 20:25:34.161 - [DEBUG] get ip:59.18.45.249 t:160
Aug 08 20:25:34.446 - [DEBUG] create_ssl update ip:59.18.45.249 time:190 h2:1
Aug 08 20:25:34.446 - [DEBUG] get ip:59.18.35.151 t:172
Aug 08 20:25:34.448 - [DEBUG] ip:113.171.244.59 real fail
Aug 08 20:25:36.361 - [WARNING] 202.28.85.234 _consume_single_frame:ConnectionResetError()
Aug 08 20:25:36.362 - [DEBUG] ssl_closed 202.28.85.234
Aug 08 20:25:36.362 - [DEBUG] 202.28.85.234 worker close:disconnect:ConnectionResetError()
Aug 08 20:25:36.422 - [DEBUG] restore ip:118.98.111.92
Aug 08 20:25:38.447 - [DEBUG] 59.18.35.151 fail:timeout('timed out',)
Aug 08 20:25:38.447 - [DEBUG] report_connect_fail:59.18.35.151
Aug 08 20:25:38.447 - [DEBUG] get ip:59.18.35.166 t:187
Aug 08 20:25:38.738 - [DEBUG] create_ssl update ip:59.18.35.166 time:183 h2:0
Aug 08 20:25:40.554 - [INFO] scan_ip add ip:41.189.230.61 time:917
Aug 08 20:25:40.572 - [INFO] remove_slowest_ip:186.68.154.173 handshake_time:671, fails:1
Aug 08 20:25:41.425 - [DEBUG] ip:66.96.224.168 real fail
Aug 08 20:25:43.022 - [DEBUG] restore ip:112.72.5.103
Aug 08 20:25:44.819 - [DEBUG] ssl_closed 61.91.161.217
Aug 08 20:25:44.819 - [DEBUG] 61.91.161.217 worker close:GoAway: additional_data:session_timed_out
Aug 08 20:25:48.024 - [DEBUG] ip:112.72.5.114 real fail
Aug 08 20:25:49.404 - [DEBUG] restore ip:217.18.145.100
Aug 08 20:25:51.859 - [DEBUG] restore ip:112.72.5.100
Aug 08 20:25:53.595 - [DEBUG] ssl_closed 41.201.164.179
Aug 08 20:25:53.595 - [DEBUG] 41.201.164.179 worker close:GoAway: additional_data:session_timed_out
Aug 08 20:25:56.860 - [DEBUG] ip:178.23.236.145 real fail
Aug 08 20:25:57.927 - [DEBUG] 61.238.239.230 keep alive fail, inactive_time:130 head_timeout:21
Aug 08 20:25:57.927 - [DEBUG] report_connect_fail:61.238.239.230
Aug 08 20:26:00.428 - [WARNING] 4.59.40.90 _consume_single_frame:ConnectionResetError()
Aug 08 20:26:00.429 - [DEBUG] ssl_closed 4.59.40.90
Aug 08 20:26:00.429 - [DEBUG] 4.59.40.90 worker close:disconnect:ConnectionResetError()
Aug 08 20:26:01.476 - [DEBUG] ssl_closed 118.98.30.218
Aug 08 20:26:01.476 - [DEBUG] 118.98.30.218 worker close:GoAway: additional_data:session_timed_out
Aug 08 20:26:01.861 - [DEBUG] ip:216.58.206.116 real fail
Aug 08 20:26:02.655 - [INFO] scan_ip add ip:200.115.94.169 time:924
Aug 08 20:26:02.663 - [INFO] remove_slowest_ip:201.248.76.236 handshake_time:671, fails:1
Aug 08 20:26:02.928 - [DEBUG] 61.238.239.230 worker close:keep alive
Aug 08 20:26:06.862 - [DEBUG] ip:66.96.224.142 real fail
Aug 08 20:26:07.608 - [INFO] scan_ip add ip:216.123.194.219 time:898
Aug 08 20:26:07.624 - [INFO] remove_slowest_ip:189.203.232.13 handshake_time:670, fails:1
Aug 08 20:26:11.864 - [DEBUG] ip:66.96.224.159 real fail
Aug 08 20:26:15.308 - [INFO] scan_ip add ip:61.238.203.247 time:174
Aug 08 20:26:15.324 - [INFO] remove_slowest_ip:71.19.173.85 handshake_time:670, fails:1
Aug 08 20:26:16.866 - [DEBUG] ip:216.254.140.211 real fail
Aug 08 20:26:16.932 - [DEBUG] ssl_closed 210.187.22.163
Aug 08 20:26:16.932 - [DEBUG] 210.187.22.163 worker close:idle timeout
Aug 08 20:26:21.867 - [DEBUG] ip:157.161.155.182 real fail
Aug 08 20:26:23.072 - [DEBUG] restore ip:201.157.30.177
Aug 08 20:26:23.740 - [DEBUG] get ip:61.238.203.247 t:174
Aug 08 20:26:24.017 - [DEBUG] create_ssl update ip:61.238.203.247 time:194 h2:1
Aug 08 20:26:24.452 - [DEBUG] restore ip:200.124.254.238
Aug 08 20:26:25.862 - [DEBUG] restore ip:66.96.224.153
Aug 08 20:26:25.888 - [DEBUG] 180.149.91.76 keep alive fail, inactive_time:208 head_timeout:45
Aug 08 20:26:25.888 - [DEBUG] report_connect_fail:180.149.91.76
Aug 08 20:26:29.028 - [DEBUG] get ip:61.91.161.217 t:398
Aug 08 20:26:30.862 - [DEBUG] ip:189.247.145.163 real fail
Aug 08 20:26:30.890 - [DEBUG] 180.149.91.76 worker close:keep alive
Aug 08 20:26:33.029 - [DEBUG] 61.91.161.217 fail:timeout('timed out',)
Aug 08 20:26:33.029 - [DEBUG] report_connect_fail:61.91.161.217
Aug 08 20:26:33.030 - [DEBUG] get ip:210.187.22.163 t:445
Aug 08 20:26:33.746 - [DEBUG] create_ssl update ip:210.187.22.163 time:475 h2:0
Aug 08 20:26:35.863 - [DEBUG] ip:59.18.35.151 real fail
Aug 08 20:26:37.658 - [INFO] scan_ip add ip:180.234.129.91 time:965
Aug 08 20:26:37.674 - [INFO] remove_slowest_ip:180.149.91.76 handshake_time:1145, fails:1
Aug 08 20:26:37.674 - [INFO] remove_slowest_ip:120.28.26.178 handshake_time:670, fails:1
Aug 08 20:26:40.406 - [INFO] scan_ip add ip:95.180.157.29 time:927
Aug 08 20:26:40.420 - [INFO] remove_slowest_ip:61.238.203.231 handshake_time:669, fails:1
Aug 08 20:26:40.865 - [DEBUG] ip:61.238.239.230 real fail
Aug 08 20:26:45.867 - [DEBUG] ip:180.149.91.76 real fail
Aug 08 20:26:46.924 - [DEBUG] restore ip:61.91.161.217
Aug 08 20:26:48.379 - [WARNING] 66.96.224.149 _consume_single_frame:ConnectionResetError()
Aug 08 20:26:48.380 - [DEBUG] ssl_closed 66.96.224.149
Aug 08 20:26:48.380 - [DEBUG] 66.96.224.149 worker close:disconnect:ConnectionResetError()
Aug 08 20:26:53.618 - [WARNING] 1.255.22.160 _consume_single_frame:ConnectionResetError()
Aug 08 20:26:53.618 - [DEBUG] ssl_closed 1.255.22.160
Aug 08 20:26:53.618 - [DEBUG] 1.255.22.160 worker close:disconnect:ConnectionResetError()
Aug 08 20:26:53.717 - [WARNING] 122.202.129.175 _consume_single_frame:ConnectionResetError()
Aug 08 20:26:53.718 - [DEBUG] ssl_closed 122.202.129.175
Aug 08 20:26:53.718 - [DEBUG] 122.202.129.175 worker close:disconnect:ConnectionResetError()
Aug 08 20:26:54.265 - [INFO] scan_ip add ip:213.145.140.81 time:1114
Aug 08 20:26:54.272 - [INFO] remove_slowest_ip:113.171.245.55 handshake_time:669, fails:1

**Comment by dgfrwx** [comment]
有问题吗？小白动哦

**Comment by lzhr** [comment]
你的manual.ini里是不是有一行
```
[google_ip]
max_good_ip_num = 3000
```

**Comment by dgfrwx** [comment]
额有，你怎么知道？

**Comment by dgfrwx** [comment]
嗯貌似现在有效ip恢复了，哈哈哈

**Comment by dgfrwx** [comment]
头像是你本人？看起来不错哦

**Comment by dgfrwx** [comment]
@lzhr 我的诊断信息和日志没问题吧？

**Comment by lzhr** [comment]
没问题，3000可以调到4000

**Comment by lzhr** [comment]
问题解决了就close吧

**Comment by lament-renaissance** [comment]
manual.ini  这个文件在哪里   我的貌似没有？

**Comment by roc1010kmt** [comment]
php模塊不是已經刪除了嗎？

**Comment by iSuperYang** [comment]
manual.ini找不到啊，路径在哪里？

**Comment by dgfrwx** [comment]
@iSuperYang @lament-renaissance https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config

**Comment by iSuperYang** [comment]
@dgfrwx .youtube.com = withphp这个指令的作用是什么？
