### ISSUE TITLE
群晖DS216Play DSM6.1安装XX-Net3.3.6遇到的问题

### ISSUE THREAD

**Issue by erdcy** [XX-net/XX-Net#6230]
### 群晖DS216Play采用了基于Linux的操作系统，在其上运行XX-Net遇到了问题，请各位不吝赐教，谢谢！
---
## 安装和运行
1. 用群晖自带的浏览器访问方式，在群晖DS216Play中新建了XX-Net文件夹，把XX-Net全部上传；

2. 用群晖自带的套件中心，在群晖安装了python和python modules；

3. 修改 XX-Net/data/launcher/config.yaml
modules:{
launcher:{ allow_remote_connect:1 }

4. 在../gae_proxy/文件夹下新建了manual.ini文件，并修改
[listen]
ip = 0.0.0.0
port = 8087
[pac]
enable = 1
ip = 0.0.0.0
port = 8086

5. Putty用ssh登陆，获取root权限，进入XX-Net文件夹，运行"./start"；

6. XX-Net开始工作，可以通过浏览器远程查看工作状态，配置等，也可以在日志页看到ip扫描的情况，例如:Aug 09 15:08:45.507 - [DEBUG] get ip:187.110.238.111 t:688 。

---
## 问题内容
1. 在状态页，监听代理仍然显示为：127.0.0.1:8087，PAC自动代理地址为：http://127.0.0.1:8086/proxy.pac，看起来manual.ini没有起作用，重启群晖，重新在XX-Net目录运行./start，仍然如此；

2. IP扫描了多次，状态栏中的“IP数量”一直为"0"，曾短暂出现过“IP数量”=“1”；

3. 顺带问一下，如何将XX-Net设置为自启动。

### 附加内容
1. 诊断信息：
XX-Net Status:

sys-platform: armv7l, Linux-3.10.102-armv7l-with-glibc2.4
os-system: Linux
os-version: #15152 SMP Thu Jul 13 04:19:00 CST 2017
os-release: 3.10.102
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
xxnet-version: 3.3.6

python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2999 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

2. GAEProxy 日志（一直在ip扫描，贴出一部分日志）

Aug 09 15:13:56.063 - [DEBUG] 188.43.69.91 fail:timeout('timed out',)

Aug 09 15:13:56.063 - [DEBUG] report_connect_fail:188.43.69.91

Aug 09 15:13:56.064 - [DEBUG] get ip:115.84.108.176 t:444

Aug 09 15:13:56.550 - [DEBUG] 193.95.144.77 fail:timeout('timed out',)

Aug 09 15:13:56.551 - [DEBUG] report_connect_fail:193.95.144.77

Aug 09 15:13:56.551 - [DEBUG] get ip:46.61.155.208 t:444

Aug 09 15:13:56.556 - [DEBUG] 114.120.192.236 fail:timeout('timed out',)

Aug 09 15:13:56.556 - [DEBUG] report_connect_fail:114.120.192.236

Aug 09 15:13:56.556 - [DEBUG] get ip:202.248.248.81 t:444

Aug 09 15:13:56.560 - [DEBUG] 183.91.18.18 fail:timeout('timed out',)

Aug 09 15:13:56.561 - [DEBUG] report_connect_fail continue_fail_count:11

Aug 09 15:13:56.561 - [DEBUG] report_connect_fail:183.91.18.18

Aug 09 15:13:56.561 - [DEBUG] get ip:45.121.219.13 t:445

Aug 09 15:13:57.051 - [DEBUG] 173.224.96.14 fail:timeout('timed out',)

Aug 09 15:13:57.052 - [DEBUG] report_connect_fail continue_fail_count:12

Aug 09 15:13:57.052 - [DEBUG] report_connect_fail:173.224.96.14

Aug 09 15:13:57.061 - [DEBUG] 124.248.162.160 fail:timeout('timed out',)

Aug 09 15:13:57.062 - [DEBUG] report_connect_fail continue_fail_count:13

Aug 09 15:13:57.062 - [DEBUG] report_connect_fail:124.248.162.160

Aug 09 15:13:57.065 - [DEBUG] 113.171.239.245 fail:timeout('timed out',)

Aug 09 15:13:57.065 - [DEBUG] report_connect_fail continue_fail_count:14

Aug 09 15:13:57.065 - [DEBUG] report_connect_fail:113.171.239.245

Aug 09 15:13:57.546 - [DEBUG] 119.110.118.144 fail:timeout('timed out',)

Aug 09 15:13:57.546 - [DEBUG] report_connect_fail continue_fail_count:15

Aug 09 15:13:57.547 - [DEBUG] report_connect_fail:119.110.118.144

Aug 09 15:13:57.558 - [DEBUG] 97.75.181.111 fail:timeout('timed out',)

Aug 09 15:13:57.558 - [DEBUG] report_connect_fail continue_fail_count:16

Aug 09 15:13:57.558 - [DEBUG] report_connect_fail:97.75.181.111

Aug 09 15:13:57.565 - [DEBUG] 106.103.1.182 fail:timeout('timed out',)

Aug 09 15:13:57.566 - [DEBUG] report_connect_fail continue_fail_count:17

Aug 09 15:13:57.566 - [DEBUG] report_connect_fail:106.103.1.182

Aug 09 15:13:57.619 - [DEBUG] network is ok, cost:71 ms

Aug 09 15:13:58.025 - [DEBUG] 201.174.98.47 fail:timeout('timed out',)

Aug 09 15:13:58.025 - [DEBUG] report_connect_fail:201.174.98.47

Aug 09 15:13:58.051 - [DEBUG] 209.141.120.179 fail:timeout('timed out',)

Aug 09 15:13:58.052 - [DEBUG] report_connect_fail:209.141.120.179

Aug 09 15:13:58.064 - [DEBUG] 211.239.234.227 fail:timeout('timed out',)

Aug 09 15:13:58.064 - [DEBUG] report_connect_fail:211.239.234.227

Aug 09 15:13:58.067 - [DEBUG] 103.233.36.43 fail:timeout('timed out',)

Aug 09 15:13:58.067 - [DEBUG] report_connect_fail:103.233.36.43

Aug 09 15:13:58.076 - [DEBUG] ip:78.11.253.241 real fail

Aug 09 15:13:58.602 - [DEBUG] 155.69.253.23 fail:timeout('timed out',)

Aug 09 15:13:58.602 - [DEBUG] report_connect_fail:155.69.253.23

Aug 09 15:13:58.603 - [DEBUG] 113.171.239.240 fail:timeout('timed out',)

Aug 09 15:13:58.603 - [DEBUG] report_connect_fail:113.171.239.240

Aug 09 15:13:59.057 - [DEBUG] 209.33.235.105 fail:timeout('timed out',)

Aug 09 15:13:59.057 - [DEBUG] report_connect_fail:209.33.235.105

**Comment by lzhr** [comment]
确认路径是XX-Net/data/gae_proxy/manual.ini 
最大扫描线程加到200
可能你的宽带这个ip段封锁比较严重，路由器重启重新拨号，看能不能切换到其他ip段

**Comment by erdcy** [comment]
谢谢lzhr，刚才在XX-Net/data/gae_proxy/新建了manual.ini，listen和pac的问题解决了
家里的电脑用xxnet一直没问题，有没有必要增加扫描线程啊？担心给群晖带来太大负担

**Comment by lzhr** [comment]
把电脑上XX-Net/data/gae_proxy/good_ip.txt的内容复制添加到群晖里的试试？

**Comment by erdcy** [comment]
ok，回家试试，谢谢！

**Comment by erdcy** [comment]
刚才试了把电脑上good_ip.txt的内容追加到群晖的good_ip.txt，刚添加完的时候，配置显示“可以访问真正的互联网了”，但无法通过代理上网，
从日志可以看到：
Aug 09 17:00:45.468 - [INFO] PAC from:125.71.229.102:56531 GET /proxy.pac
Aug 09 17:01:45.769 - [WARNING] get worker fail:GAE_Exception()
Aug 09 17:01:45.769 - [DEBUG] response_fail:get worker fail:GAE_Exception()
Aug 09 17:01:45.769 - [DEBUG] GAE_Exception 601 'fetch gae fail:601'
Aug 09 17:01:45.769 - [WARNING] gae_exception:GAE_Exception() https://www.google.com/
Aug 09 17:01:45.770 - [DEBUG] GAE_Exception 600 'gae_exception:GAE_Exception() https://www.google.com/'
Aug 09 17:01:45.770 - [WARNING] GAE GET https://www.google.com/ request fail:GAE_Exception() 

过一会儿，配置页又显示扫描ip了。

**Comment by iSuperYang** [comment]
@lzhr lzhr 群晖在哪里？

**Comment by erdcy** [comment]
@iSuperYang 群晖是私有云，www.synology.com

**Comment by erdcy** [comment]
扫描了一下午ip，晚上终于有两个可用的ip，局域网内可以通过pac上网了。
感谢 @lzhr

**Comment by erdcy** [comment]
另外，还有一个问题请教：
有没有方法可以实现自动检测xx-net进程是否运行，如果没有，则运行xx-net。
群晖可以设置定时任务，如果定时运行xx-net，会不会出现多个xx-net进程的情况？如果不会，定时运行有没有其他问题？

**Comment by lzhr** [comment]
群晖系统不了解，应该和其他linux系差不多少吧？
XX一运行就会占用三个端口8085，8086和8087，不会出现多个同时运行的

**Comment by erdcy** [comment]
@lzhr 群晖系统是基于Linux的，谢谢你的解答！另外，试了多次重启路由器，仍然在原ip网段内，没办法了。刚看了办公室pc上的xx-net状态，ip数接近3000，上网很稳定，看来是你下午说的问题。

**Comment by econwang** [comment]
如何开启ipv6？

**Comment by erdcy** [comment]
@econwang 
现在我的运营商已经提供ipv6，三大运营商应该都会逐步部署。
以前采取的方案是：
路由器通过he.net的免费ipv6 tunnel获取一个ipv6地址段，并下发ipv6地址给局域网的电脑、NAS和手机等终端。这个方案稳定使用了大概一年时间。不过这个方案需要你的有公网ip地址，并且可ping，路由器可刷openwrt或者梅林等。

**Comment by econwang** [comment]
> @econwang
> 现在我的运营商已经提供ipv6，三大运营商应该都会逐步部署。
> 以前采取的方案是：
> 路由器通过he.net的免费ipv6 tunnel获取一个ipv6地址段，并下发ipv6地址给局域网的电脑、NAS和手机等终端。这个方案稳定使用了大概一年时间。不过这个方案需要你的有公网ip地址，并且可ping，路由器可刷openwrt或者梅林等。

群晖上应该也可以通过Teredo 隧道让xxnet走ipv6吧，按你上面的说明，走ipv4没问题，但是一直显示ipv6不可用

**Comment by erdcy** [comment]
miredo是linux上的ipv6虚拟隧道程序，跟windows上的teredo类似，不过不知道能不能部署在群晖上。

Sent from my mobile.


在 2018年10月12日，下午5:42，Stephen Y.F. Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


@econwang<https://github.com/econwang>
现在我的运营商已经提供ipv6，三大运营商应该都会逐步部署。
以前采取的方案是：
路由器通过he.net<http://he.net>的免费ipv6 tunnel获取一个ipv6地址段，并下发ipv6地址给局域网的电脑、NAS和手机等终端。这个方案稳定使用了大概一年时间。不过这个方案需要你的有公网ip地址，并且可ping，路由器可刷openwrt或者梅林等。

群晖上应该也可以通过Teredo 隧道让xxnet走ipv6吧，按你上面的说明，走ipv4没问题，但是一直显示ipv6不可用
