### ISSUE TITLE
扫描不出来IP是怎么回事？

### ISSUE THREAD

**Issue by chenkaicheng** [XX-net/XX-Net#6236]
![image](https://user-images.githubusercontent.com/19286908/29154901-86b718b4-7dca-11e7-9f39-3fb830b40947.png)

**Comment by out0fmemory** [comment]
试试https://github.com/out0fmemory/GoAgent-Always-Available

**Comment by chenkaicheng** [comment]
@out0fmemory 多谢

**Comment by ycycoo** [comment]
@out0fmemory 那个链接项目也扫不出ip了，是不是全军覆没了啊...
