### ISSUE TITLE
用python3写了个扫描ip的工具

### ISSUE THREAD

**Issue by china-shang** [XX-net/XX-Net#6239]
使用了异步扫描，增加效率，扫不到ip的可以试试，[工具地址](https://github.com/china-shang/checkip)

**Comment by lzhr** [comment]
这个`{"Host": "my-project-1-1469878073076.appspot.com"}`，虽然加了密码

**Comment by china-shang** [comment]
难道有人对我DDOS攻击，，，

**Comment by china-shang** [comment]
当然如果有大量的人用这个，最好用自己的appid扫

**Comment by SeaHOH** [comment]
建议换个谷歌本身的 host，如 `www.appspot.com`。

**Comment by theratlesnake** [comment]
支持一下
