### ISSUE TITLE
不知XX-Net是如何淘汰不可用IP的?

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#624]
是这样的，我有一个windows 8的平板，不过这个平板天线不是很好，待机之后恢复大概要一分钟才连上网，有时候也会拿出去用，在外面的时候经常没有网用，但是并不会专门去关闭XX-Net，或者是用CMCC，但是信号不好的时候可能时连时断的。
我把XX-Net复制进去用了，并且把在台式机上用的很好的IP列表也复制进去了，但是发现，在几次待机并唤醒，以及拿出去一段时间后，XX-Net的可用IP变成了0个，不知是否与XX-Net的IP淘汰策略有关。

**Comment by xxnet** [comment]
这种有可能，太不稳定的网络

在 2015年7月17日 上午10:04，Cat73 <notifications@github.com>写道：

**Comment by Cat7373** [comment]
不知Python有没有什么办法来判断待机或者有无网络连接呢，这样可以防止这种情况发生。

**Comment by yuliangyang** [comment]
我都时刻备份good_ip.txt

**Comment by Cat7373** [comment]
但是这样麻烦啊。。。
以及我的台式机上也有好的，随时可以复制。。。

**Comment by yuliangyang** [comment]
如果有3个网络环境，我看得备份三份good_ip.txt   
实验室  寝室  家

**Comment by Cat7373** [comment]
我主要是家里啦- -
其他地方无所谓- -

**Comment by yuliangyang** [comment]
测试了下
最新版，可以正常打开了。。

**Comment by yuliangyang** [comment]
但是我这1.16.3一直能用
而且刚下载最新版。一分钟ip就建立好了
实在对你们没啥帮助了。等我一帮群好友的测试结果把

**Comment by yuliangyang** [comment]
大多数群好友反应可以正常使用

**Comment by chris198685** [comment]
xxnet2.0.1开了也有3小时，IP倒是扫到100多个，但是延迟高的吓人，2700ms
访问也是较不稳定

**Comment by xxnet** [comment]
大部分ip被封，能够坚持多久还去确定。
目前只能顶一阵

在 2015年7月17日 下午3:28，chris198685 <notifications@github.com>写道：
