### ISSUE TITLE
特意注册了下xx-net 账号来告诉大家如何更好的翻墙。欢迎指点

### ISSUE THREAD

**Issue by zhuchuanlong1988** [XX-net/XX-Net#6245]
看大家每次在评论里有些说ip不够什么的，或者翻墙卡顿什么，首先想要翻墙就要摒弃国内所有软件，包括国内系统。老鸟误喷，我用xx软件蛮好的，我都用很多年。
     首先系统要是原版，国人用盗版习惯，起码系统要正版，Ghost系统早已定制N个后台控制你了，本人是用的win7 原版
     摒弃所有国内的软件，一个都不要留，输入法也删掉，什么搜狗、QQ输入法，换Google输入法，不要说什么QQ、酷狗、360杀毒、QQ全家桶、想要好好翻墙就要摒弃国内所有软件。
     还有一个习惯方式就是用国产软件打补丁、比如360、QQ安全管家打补丁，这里面有些补丁你懂的，所以要习惯有微软的update更新。
     剩下的自己装国外的杀毒软件吧，本人用小红帽、Wise Care 365。
    最终要的鄙人用的“影子系统PowerShadow” 这个软件蛮好，用完电脑没有任何痕迹，保护隐私，具体的自己google。

**Comment by lzhr** [comment]
你不如去肉身翻墙。
小号在这儿指点江山，还有推广嫌疑

**Comment by macorange** [comment]
xx-net用了挺久了，我居然不知道什么是注册账号发言。

**Comment by wpp214** [comment]
这是推广贴？？？

**Comment by zhuchuanlong1988** [comment]
@lzhr 楼上的我只是实话实说，说我是小号，那我也没法子，我12年开始用的。

**Comment by zhuchuanlong1988** [comment]
@wpp214 算不上广告贴，知道的告诉大家而已

**Comment by dsgys** [comment]
没那么严重,GFW从源头上就给你封了,你能扫到IP,他们同样能扫到

**Comment by zanewayne78** [comment]
Wise Care 365是国产外销的吧，影子系统保护不了隐私，只要联网有一万种方法窃取，不要乱发错误的理论。

**Comment by zhuchuanlong1988** [comment]
@zanewayne78 你说的确实有理，不过对于我们这小网民做到这基本的，翻墙应该没问题，这是我表达的中意。

**Comment by WLZLCX** [comment]
谈到国产软件，能有几个人离得开迅雷？

就国内的网络环境，迅雷吸血的特色对于喜欢快速下载，喜欢冷门资源的人，他们是不会放弃国产软件的
更别谈QQ，微信，输入法...... 就算天塌下来了，照样有人用，多年的习惯没法改的

他们一边翻墙，一边照样用国产软件，有时照样抱怨为啥突然又翻不了墙

楼主别建议了，有人不会听的
