### ISSUE TITLE
win10 系统启动不了，也不报任何错

### ISSUE THREAD

**Issue by xiongyayun428** [XX-net/XX-Net#6248]
不管是点击start.bat还是start.vbs，都无法启动，没有报错信息，也没有日志信息的吗？

**Comment by lzhr** [comment]
打开cmd切换到软件目录，输入start.bat按回车运行，应该会有报错信息出来

**Comment by xiongyayun428** [comment]
运行start.vbs报错的，一闪而过，看不到报错信息啊

**Comment by xiongyayun428** [comment]
@lzhr 是不是我电脑有全局python的原因啊？
![image](https://user-images.githubusercontent.com/11458959/29245781-68c21e18-8017-11e7-86e2-ec1e87bbef87.png)
 我电脑装了git

**Comment by lzhr** [comment]
你这不是在软件目录啊
D:\XXNet\code\default\python27\1.0\pythonw.exe  D:\XXNet\code\default\launcher\start.py

**Comment by xiongyayun428** [comment]
@lzhr D:\Software\XX-Net>D:\Software\XX-Net\code\default\python27\1.0\pythonw.exe D:\Software\XX-Net\code\default\launcher\start.py
我运行这个没一点反应啊，也没有报错。
能不能加个QQ帮我看下，谢谢。
QQ：531158453

**Comment by lzhr** [comment]
好的，通过一下20*****70

**Comment by jzp820927** [comment]
我去，用 QQ 搞这个太不安全了吧

**Comment by lzhr** [comment]
@jzp820927 网速太慢，远程连不上

**Comment by xiongyayun428** [comment]
问题已经解决了，多亏了 @lzhr 在这里表示感谢
问题原因是因为我的电脑存在PYTHONHOME环境变量，干掉这个变量就可以了。
