### ISSUE TITLE
YOUTUBE 打开是乱码 已升级到3.36  ，XP系统  请求解决方案 

### ISSUE THREAD

**Issue by xpostx** [XX-net/XX-Net#6257]
已升级到3.36版本，系统为XP 浏览器为CHROME  

## 问题内容
1  能使用google, twitter 等，打开youtube时 全屏为乱码
2、扫描到的IP非常少，而且延时长达1000秒
3、已按相关的贴子的方法 在config.ini 中加入 youtube=gae等相关内容 ，但似乎没有改善。

### 附加内容
下面是我的日志内容 ，请帮我看看 有没有什么解决的方案 谢谢。
XX-Net Status:

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:28
network-status: OK
connected-link: new:7 used:0
worker: h1:3 h2:16
scan-ip-thread-num: 50
ip-quality: 953
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

---

**Comment by lzhr** [comment]
https://github.com/XX-net/XX-Net/issues/6116#issuecomment-318351126

到官网下载最新32位chrome 
https://www.google.com/intl/zh-CN/chrome/browser/desktop/index.html?standalone=1

**Comment by xpostx** [comment]
这个是真下不成了,chrome现在已经不支持XP了,

**Comment by justfornodejs** [comment]
QQ浏览器

**Comment by lzhr** [comment]
试试火狐最新版，还支持xp，注意别下载北京公司处理过的版本

**Comment by xpostx** [comment]
好的 我试试,谢谢

**Comment by lzhr** [comment]
我好像看错了
https://support.mozilla.org/zh-CN/kb/firefox-windows-xp-vista
https://caniuse.com/#search=brotli

**Comment by gggccc44** [comment]
用chrome 50以上内核的浏览器，或者48以上的火狐

**Comment by candy2107** [comment]
@xpostx 
https://portableapps.com/apps/internet/firefox-portable-esr
@lzhr 你用不着每天给新手回答问题，偶尔看看就行了

**Comment by ximenlangzige** [comment]
同样的问题YOUTUBE 打开是乱码

**Comment by gjbg1989** [comment]
刷新下？
