### ISSUE TITLE
在公司可以，在家不行

### ISSUE THREAD

**Issue by javayqy** [XX-net/XX-Net#6284]
之前在家用的好好地，突然这几天不能用了，本以为是xxnet出了什么问题，就更新到3.3.6然后

还是不行
去公司后可以正常使用
![qq 20170819174721](https://user-images.githubusercontent.com/29996523/29485678-5d5b3fe6-8508-11e7-85e8-934525cec0c7.png)
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1782 good:355
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:0
scan-ip-thread-num: 50
ip-quality: 1640
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by lzhr** [comment]
装两个xxnet，一个在家用，一个公司用。
不同网络扫出来的good_ip通用性很差

**Comment by suojiang** [comment]
最近这几天我也发现这个问题，公司可以用，家里就连不上了

**Comment by y838571025** [comment]
重装过一次最后一个ip也扫描不到了

**Comment by nerddd** [comment]
我也是这样
