### ISSUE TITLE
youtube 上不去了

### ISSUE THREAD

**Issue by sd613** [XX-net/XX-Net#6289]
400. That’s an error.
Your client has issued a malformed or illegal request. That’s all we know.

**Comment by WLZLCX** [comment]
打开既有的配置文件 XX-Net\data\gae_proxy\config.ini
添加 [hosts]
        .youtube.com = gae
        .ytimg.com = gae

或者创建新的配置文件 XX-Net\data\gae_proxy\manual.ini
添加
