### ISSUE TITLE
http://twrp.me 502 Python Urlfetch Error: 'GET' 了

### ISSUE THREAD

**Issue by piewan** [XX-net/XX-Net#6298]
## 问题内容
Message From FetchServer
Python Urlfetch Error: 'GET'

DownloadError('Unable to connect to server at URL: http://twrp.me/',), timeout=19
DownloadError('Unable to connect to server at URL: http://twrp.me/',), timeout=38
 

#### 获取诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2165 good:26
network-status: OK
connected-link: new:2 used:0
worker: h1:2 h2:18
scan-ip-thread-num: 10
ip-quality: 602
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志
Aug 23 08:42:18.021 - [DEBUG] GAE GET http://twrp.me/
Aug 23 08:42:18.828 - [DEBUG] restore ip:173.194.178.82
Aug 23 08:42:20.297 - [WARNING] server app return fail, status:502
Aug 23 08:42:20.594 - [DEBUG] GAE GET http://twrp.me/favicon.ico
Aug 23 08:42:20.808 - [DEBUG] 216.58.207.150 fail:timeout('timed out',)
Aug 23 08:42:20.808 - [DEBUG] report_connect_fail:216.58.207.150
Aug 23 08:42:20.809 - [DEBUG] get ip:173.194.176.224 t:680
Aug 23 08:42:22.881 - [WARNING] server app return fail, status:502
Aug 23 08:42:23.233 - [DEBUG] GAE GET http://twrp.me/
Aug 23 08:42:24.811 - [DEBUG] 173.194.176.224 fail:timeout('timed out',)
Aug 23 08:42:24.811 - [DEBUG] report_connect_fail:173.194.176.224
Aug 23 08:42:24.825 - [DEBUG] get ip:173.194.178.82 t:719
Aug 23 08:42:25.506 - [WARNING] server app return fail, status:502
Aug 23 08:42:25.566 - [DEBUG] GAE GET http://twrp.me/favicon.ico
Aug 23 08:42:25.909 - [DEBUG] create_ssl update ip:173.194.178.82 time:706 h2:0
Aug 23 08:42:27.842 - [WARNING] server app return fail, status:502
Aug 23 08:42:27.890 - [DEBUG] restore ip:173.194.24.85
Aug 23 08:42:30.432 - [DEBUG] GAE GET https://github.com/settings/replies?context=new_issue
Aug 23 08:42:32.306 - [INFO] GAE t:1874 s:555 GET https://github.com/settings/replies?context=new_issue h2_get_head:342
Aug 23 08:42:35.810 - [DEBUG] ip:216.58.207.150 real fail
Aug 23 08:42:40.611 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Aug 23 08:42:40.616 - [DEBUG] GET http://www.twitter.com/xxnet
Aug 23 08:42:40.702 - [DEBUG] GET http://www.twitter.com/xxnet
Aug 23 08:42:40.703 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Aug 23 08:42:40.811 - [DEBUG] ip:173.194.176.224 real fail
Aug 23 08:42:46.282 - [DEBUG] ssl_closed 216.58.203.190
Aug 23 08:42:46.282 - [DEBUG] 216.58.203.190 worker close:GoAway: additional_data:session_timed_out
Aug 23 08:43:00.917 - [DEBUG] get ip:216.58.203.190 t:286
Aug 23 08:43:01.475 - [DEBUG] create_ssl update ip:216.58.203.190 time:431 h2:1
Aug 23 08:43:09.948 - [WARNING] 216.58.206.174 _consume_single_frame:ConnectionResetError()
Aug 23 08:43:09.948 - [DEBUG] ssl_closed 216.58.206.174
Aug 23 08:43:09.948 - [DEBUG] 216.58.206.174 worker close:disconnect:ConnectionResetError()
Aug 23 08:43:16.484 - [DEBUG] get ip:173.194.24.85 t:391
Aug 23 08:43:18.102 - [DEBUG] create_ssl update ip:173.194.24.85 time:1414 h2:0
Aug 23 08:43:36.612 - [DEBUG] ssl_closed 172.217.8.202
Aug 23 08:43:36.612 - [DEBUG] 172.217.8.202 worker close:GoAway: additional_data:session_timed_out
Aug 23 08:43:50.494 - [DEBUG] ssl_closed 216.58.206.225
Aug 23 08:43:50.494 - [DEBUG] 216.58.206.225 worker close:GoAway: additional_data:session_timed_out
Aug 23 08:43:53.132 - [DEBUG] get ip:172.217.8.202 t:537
Aug 23 08:43:53.963 - [DEBUG] create_ssl update ip:172.217.8.202 time:549 h2:1
Aug 23 08:44:08.975 - [DEBUG] get ip:216.58.206.225 t:585
Aug 23 08:44:09.839 - [DEBUG] create_ssl update ip:216.58.206.225 time:574 h2:1
Aug 23 08:44:12.862 - [DEBUG] GAE GET https://chrome.google.com/webstore/download/eipdnjedkpcnlmmdfdkgfpljanehloah/package/main?authuser=8
Aug 23 08:44:13.242 - [INFO] GAE t:380 s:0 GET https://chrome.google.com/webstore/download/eipdnjedkpcnlmmdfdkgfpljanehloah/package/main?authuser=8 get_response:378

**Comment by onplus** [comment]
https直连
