### ISSUE TITLE
提示隐私设置错误

### ISSUE THREAD

**Issue by Neputune** [XX-net/XX-Net#63]
部署chrome之后，脸谱可以登录，可是登录谷系列服务，比如网站，邮箱提示隐私设置错误，因为不是私密连接，请问这个怎么设置？

**Comment by xxnet** [comment]
正常的google网站是直连的，不会替换Google的证书。

你的现象比较奇怪，先试试访问 
https://www.google.com/ncr 就可以避免被跳转到国家网站，一般会跳转到香港站。

或者手动导入 data/goagent/CA.crt 证书，看看还有没有问题。

**Comment by Neputune** [comment]
谢谢您，那怎么手动导入证书呢？

**Comment by xxnet** [comment]
http://www.utexas.edu/its/help/user-certs/818
https://www.digicert.com/ssl-support/p12-import-export-mac-mavericks-server.htm

http://www.bigsea.com.cn/archives/1094/
在 Launchpad > 实用工具 > 钥匙串访问 > 系统 中找到 GoAgent CA 并双击（在data/goagent/CA.crt）

选择 信任 > 使用此证书时 > 总是信任(不能编辑的时候记得把旁边的锁打开)

重启浏览器

2015-03-15 10:44 GMT-04:00 Neputune <notifications@github.com>:
