### ISSUE TITLE
2.0.1无法运行

### ISSUE THREAD

**Issue by JebYore** [XX-net/XX-Net#630]
ubuntu下2.0.1无法运行，在终端里打开1秒钟后自动退出

**Comment by xxnet** [comment]
ubuntu什么版本？

终端里执行start.sh后什么提示，贴上来

2015-07-17 11:38 GMT+08:00 JebYore <notifications@github.com>:

**Comment by JebYore** [comment]
Jul 17 11:58:52 - [DEBUG] start confirm_xxnet_exit
Jul 17 11:58:52 - [INFO] load ip range file:/home/jeb/XX-Net-2.0.1/gae_proxy/local/ip_range.txt
Jul 17 11:58:52 - [INFO] load google ip_list num:100, gws num:100
Jul 17 11:58:52 - [INFO] SSL use version:TLSv1
Jul 17 11:58:52 - [INFO] ------------------------------------------------------
GAEProxy Version    : gae_proxy (python/2.7.6 )
Listen Address     : 127.0.0.1:8087
GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Pac Server         : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

Jul 17 11:58:52 - [INFO] system cert exist
GoAgent XX-Net - GoAgent                                     C,,  
Jul 17 11:58:52 - [INFO] gae_proxy started
Jul 17 11:58:52 - [INFO] start gae_proxy time cost 150
Traceback (most recent call last):
  File "launcher/start.py", line 98, in <module>
    main()
  File "launcher/start.py", line 77, in main
    web_control.start()
  File "/home/jeb/XX-Net-2.0.1/launcher/web_control.py", line 389, in start
    server = LocalServer(("0.0.0.0", 8085), Http_Handler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Stopping all modules before exit!
Jul 17 11:58:52 - [DEBUG] module gae_proxy stopping
Jul 17 11:58:53 - [DEBUG] get ip:202.86.162.41 t:99
Jul 17 11:58:53 - [INFO] Exiting gae_proxy module...
Jul 17 11:58:53 - [DEBUG] get ip:103.1.139.167 t:392
Jul 17 11:58:53 - [DEBUG] get ip:208.117.255.111 t:453
Jul 17 11:58:54 - [DEBUG] get ip:208.117.239.132 t:491
Jul 17 11:58:54 - [INFO] Finished Exiting gae_proxy module...
Jul 17 11:58:54 - [INFO] module gae_proxy stopped

之前是这样，重启了下机器后又没问题了。不好意思应该是我搞错了。
