### ISSUE TITLE
 为什么一定要确保有只支持http1的ip

### ISSUE THREAD

**Issue by china-shang** [XX-net/XX-Net#6323]
看了代码后发现，只有使用direct直连google的一些网站用这样的ip，并且是只用这样的ip，难道direct不能使用http2连接吗？
![2017-08-28 13-13-18](https://user-images.githubusercontent.com/17249688/29760057-5ecd4238-8bf3-11e7-8881-38ec5cbc5436.png)
![2017-08-28 13-13-55](https://user-images.githubusercontent.com/17249688/29760075-76a0ce98-8bf3-11e7-8f4d-354dd411f6ca.png)
而且扫描出来的基本全是http2的ip;
![2017-08-28 13-19-37](https://user-images.githubusercontent.com/17249688/29760082-90d94114-8bf3-11e7-804f-95936418f911.png)
上面的情况是我改了源码后的结果，不然由于我导入的ip全是支持http2的，找不到only_h1的ip，会导致xxnet不断的建立新的连接，直到找到几个only_h1的ip才会停止，未改的代码如下
![2017-08-28 13-20-55](https://user-images.githubusercontent.com/17249688/29765916-90bfb8a4-8c0f-11e7-9e8a-df30b6a1301f.png)

**Comment by china-shang** [comment]
如果不该源码甚至会到h1:1,h2:50这样的情况，完全是浪费ip与电脑资源

**Comment by china-shang** [comment]
如果不改源码甚至会到h1:1,h2:50这样的情况，极大的浪费ip与电脑资源

**Comment by SeaHOH** [comment]
没看懂你在说什么。h1 一样可以用 https 链接。

而且你也没有表明修改了哪些内容。

**Comment by china-shang** [comment]
问题1：最后一张图的代码上写了，只要没找到only_h1的ip就一直建立连接，但使用gae却从来不会用only_h1的ip，因为现在访问google也是用gae所以这是无用功。
问题2：就算h1能https加密，为什么direct直连的就一定要用only_h1的ip呢？ @SeaHOH

**Comment by SeaHOH** [comment]
>为什么direct直连的就一定要用only_h1的ip呢？

不是一定，而是 h2 涉及到证书和域名匹配问题。

**Comment by china-shang** [comment]
那感觉与付出更多的代价去找h1的ip，然后不断的建立连接，直到建立的连接中出现h1相比，不如不要使用直连了

**Comment by SeaHOH** [comment]
你可以按你的想法修改，现在这个机制是没有区分 gws 和 gvs 等类型的，只是确定可以用于 GAE APP。

不过想要更加合理优化，需要修改的地方不少，光改这个可能会造成更多错误，需要多加测试。

**Comment by xxnet** [comment]
之前Google 的某些host是不支持GAE访问的，所以只能采用Direct模式，这不仅仅是因为流量问题。
不过Google 的服务器也一直在变化。

在去年，有些ip，只支持h1，有些ip只支持h2，有些都支持。
这些Direct访问的ip，只能是h1的ip才行，现在的情况需要重新测试。

这代码是一年前写的，当时从重底层实现了H2的高效利用，即使在ip极少的情况下，也能使用。
对于Direct 模式调用h1链接的逻辑，写得很纠结。

最终怎样的方案最好，现在可以重新考量。

需要先验证几个问题：
1. 是不是ip还是分成 只支持h1的/只支持h2的/同时支持2种的？
2. h2的ip，证书和域名匹配 问题，好解决吗？
3. 还有哪些host，只能Direct模式直连？

再根据这些情况决定如何设计。

**Comment by kxmp** [comment]
h1:0 h2:xx 我h1 咋都是0呢
而且这个真的支持h2么
我看nettab里面protocol还是h1.1 而且多路复用也没有哇!!!!
