### ISSUE TITLE
Linux centos 6.5 安装3.3.6 证书问题

### ISSUE THREAD

**Issue by paulcx** [XX-net/XX-Net#6336]
XX-Net Status:

sys-platform: i686, Linux-2.6.32-696.10.1.el6.i686-i686-with-centos-6.9-Final
os-system: Linux
os-version: #1 SMP Tue Aug 22 18:12:35 UTC 2017
os-release: 2.6.32-696.10.1.el6.i686
os-detail: Dist:CentOS; Version:6.9; ID:Final
architecture: 32bit,ELF
browser: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 17.2.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1308 good:1123
network-status: OK
connected-link: new:3 used:0
worker: h1:11 h2:10
scan-ip-thread-num: 50
ip-quality: 116
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

证书删了再导入还是不行，https安全连接不了。能不能帮忙看下是什么问题？

**Comment by paulcx** [comment]
有没有人帮忙看一下，谢谢！

**Comment by onplus** [comment]
你这是safari浏览器？
—————————
#4063
https://github.com/XX-net/XX-Net/wiki/How-to-use#linux%E7%B3%BB%E7%BB%9F

**Comment by paulcx** [comment]
我用ios safari和windows10，mac上的chrome都试过，强制刷新页面也没用。

**Comment by paulcx** [comment]
@onplus 我是iphone ios11 safari浏览器，怎么刷新？

**Comment by houhuliang** [comment]
证书没装对

**Comment by paulcx** [comment]
@houhuliang 特地删除了旧的，再装了新的，还特地把信任该证书选上了。还是不行。。。

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA#ipadiphone%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5%E8%AF%81%E4%B9%A6

**Comment by paulcx** [comment]
@onplus 太感谢你了，根据你的提示 #4063 和 https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA#ipadiphone%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5%E8%AF%81%E4%B9%A6 手动邮件证书安装成功！

很奇怪为什么直接从浏览器里点证书安装就不行呢。。。
