### ISSUE TITLE
PAC模式失效 问题解决

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#6341]
两台电脑chrome的PAC模式均失效 使用全局pac 用系统代理也失效 3.3.0与3.3.6都不行 以前3.3.0是可以用PAC模式的
其余模式没问题

**Comment by roc1010kmt** [comment]
chrome用PAC模式確實很多網站打不開，卡死。牆內網站也卡死。

**Comment by sky123456789sky** [comment]
并且两个路由器都装了XX-NET 然后手机通过PAC模式上网 现在也不行了 奶奶的PAC文件应该是出问题了

**Comment by jzp820927** [comment]
自己另外找个 PAC 文件来试试，对比一下，就知道是不是 PAC 的问题了。

**Comment by sky123456789sky** [comment]
我找个以前的旧PAC试试

**Comment by sky123456789sky** [comment]
换了旧的PAC 马上爽利了

**Comment by jzp820927** [comment]
那就用旧的吧

**Comment by sky123456789sky** [comment]
好吧 大概是gfwlist的锅 把他注释掉了事

**Comment by xxnet** [comment]
谁来提个pull

**Comment by jzp820927** [comment]
LZ 是用了独立的 PAC 文件，而 XX 的 PAC 是自动生成的，这个不好提吧，估计得从代码层面解决。

**Comment by xxnet** [comment]
​是，不能直接替换掉，除非自己维护这个列表。

有没有其他替代源，或者更好的解决方案？

**Comment by jzp820927** [comment]
我也很少用 PAC 了，都是直接用 chrome 的 omega 插件，方便一些，PAC 确实很难维护。

**Comment by sky123456789sky** [comment]
哈哈 这个也解决了 删掉data/gae_proxy下的 proxy.pac文件 重启XX 问题解决 奇怪的问题呀 这玩意竟然会自己坏掉

**Comment by linhua55** [comment]
xxnet 自己 应该 维护一个 pac列表 ， 建个repo ， 供使用者提交

**Comment by jzp820927** [comment]
这个想法不错，新建一个 pac 的 repo 专门维护一个独立的 pac

**Comment by xxnet** [comment]
gfwlist 格式改了，参考这个讨论：
https://github.com/gfwlist/gfwlist/issues/401

先做了base64编码，而新的格式采用AutoProxy，定义如下：
https://github.com/gfwlist/gfwlist/wiki/Syntax

需要做一些改动来适应新的格式，毕竟gfwlist维护还是比较活跃的，没有必要重新造轮子。

**Comment by onplus** [comment]
gfwlist大部分网址都用不到，用omega随时添加，定期导出适合自己的pac

**Comment by xxnet** [comment]
​也许最简单的做法，就是停掉自动升级 gfwlist
