### ISSUE TITLE
IOS10.3.3 导入证书失败 求大大帮助 已解决

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#6342]
以前导入过几次 这次升级了装在路由的XX 然后重新导入证书 出现了 ：描述文件安装失败 无法与帮助程序通信。请问如何解决

**Comment by onplus** [comment]
更新不会重写data文件夹，大概不需要再导入证书。
另外https://github.com/XX-net/XX-Net/search?utf8=✓&q=描述文件安装失败&type=Issues

**Comment by sky123456789sky** [comment]
不导入不行啊 chrome刚更新了 按各位大大的说法 直接删掉证书文件 重生成了一次 然后新的证书装不上了

**Comment by jzp820927** [comment]
其他设置能正常导入么？

**Comment by sky123456789sky** [comment]
对 其他没问题 记得以前我提过这问题 就是j大告诉我说用以前可用的证书解决的 这次实在是没办法了 两个IOS设备都是如此 j大 您再给看看

**Comment by jzp820927** [comment]
我没有 ios 设备，无法测试，把安装失败的界面，截个图发来看看

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/issues/6336#issuecomment-326245632

**Comment by sky123456789sky** [comment]
@onplus 我本来就是这样安的 不行的

**Comment by sky123456789sky** [comment]
https://github.com/sky123456789sky/hello/blob/master/1305431633.jpg

**Comment by sky123456789sky** [comment]
https://github.com/sky123456789sky/hello/blob/master/1305431633.jpg?raw=true

**Comment by jzp820927** [comment]
恩，看到了，你 google 搜索下，这个错误提示的关键字，看看能不能找到一些线索解决问题

**Comment by sky123456789sky** [comment]
O(∩_∩)O哈哈~ 解决了 以前被误导了 以为chrome升级之后必须用新证书 其实不是这回事 重新把以前IOS可以用的证书导入PC就可以了 而路由器端则删掉新生成的certs文件夹和CA文件 换成旧的可用的CA文件 重启路由器 问题解决
