### ISSUE TITLE
gae赠送300$ 的免费试用有没人注册过，

### ISSUE THREAD

**Issue by china-shang** [XX-net/XX-Net#6350]
注册过程中需要美国的信用卡，或者银行账号，应该怎么解决

**Comment by jzp820927** [comment]
确实是，信用卡的限制条件有点高，没办法，这个是必须的，听说国内的双币种信用卡也可以，如果你有的话，可以试试。

**Comment by EmmieMcDonald** [comment]
有什么用处，速度更快吗

**Comment by jzp820927** [comment]
就是一个 VPS，不懂的话，自己 google 搜索 “VPS” 就行了

**Comment by yaojun1314** [comment]
我注册了，我用的自己的信用卡，反正十分钟就搞定了。速度也挺快的。

**Comment by SeaHOH** [comment]
@yaojun1314 
注意，送的钱用完了或试用过了之后要设定消费限额为 0。
