### ISSUE TITLE
xxnet 启动报错

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#6352]
Linux 下, 最新版本 xxnet 启动 报错 如下:

> Traceback (most recent call last):
>   File "code/default/launcher/start.py", line 8, in <module>
>     from instances import xlog
>   File "/mnt/star/git_repository/xxnet/code/default/launcher/instances.py", line 10, in <module>
>     from xlog import Logger
> ImportError: No module named 'xlog'
> 

退到 历史版本 `36fef43` 就好了, 应该是新提交的代码有问题.

**Comment by xxnet** [comment]
​master上已经修复
