### ISSUE TITLE
http://127.0.0.1:8085配置页面进不去

### ISSUE THREAD

**Issue by skyremind** [XX-net/XX-Net#6356]
无法访问此网站

127.0.0.1 的响应时间过长。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

下了最新版也没用  公司里能用  家里前两天还好的突然不能用了

**Comment by seed-fe** [comment]
解决了吗，我自从更新了win10的创意者更新系统版本之后就打不开配置页面了。。

**Comment by xxnet** [comment]
​命令行启动，看看日志显示什么
