### ISSUE TITLE
用ipv6显示 “您应该考虑开启IP扫描器”

### ISSUE THREAD

**Issue by ablebodied** [XX-net/XX-Net#6368]
最开始的时候ipv6是可以用的，不知道为什么现在显示这个，可用IP数为0，不会自动扫描？这个在哪里配置呢？

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.4.0

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by onplus** [comment]
#6149

**Comment by ablebodied** [comment]
解决方案取自 #6149 

原因：XX-Net\data\gae_proxy\good_ipv6.txt 为乱码
解决方法：
把XX-Net\code\default\gae_proxy\local\good_ipv6.txt 复制到XX-Net\data\gae_proxy\good_ipv6.txt覆盖，重新启动xx-net，就正常了。
