### ISSUE TITLE
IP骤减，请求增援

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#6371]
![screenhunter_01 sep 05 12 52](https://user-images.githubusercontent.com/19446969/30045891-88969fd2-9239-11e7-83ad-088380b8b792.png)

启用新版XX-net 3.4后，总是显示（尚未建立连接）用老版本的还能用，一检查才知道，可用IP才有两个。照这样下去XX-net将来必定走向无法使用的局面，所以建议XX-net尽快研发新型软件，改变软件的结构，来拯救目前存在问题。还是那句话：XX-net 树大招风、就得经常变换，省着他们盯上后，成天惦记琢磨破坏。

**Comment by 80068** [comment]
另外XX-net还要加快建立，IP或网络反破坏跟踪、和反破坏多网联动机制。

**Comment by onplus** [comment]
你对GFW&GAE一无所知。
你不会以为这些ip是XX-Net提供的吧

**Comment by 80068** [comment]
@onplus 当然不会认为这些IP是XX-net提供的，都用到现在还不至于一无所知

**Comment by RageCooky** [comment]
说的真轻松 ╮(╯_╰)╭

**Comment by lijingwei0710** [comment]
今天下午我这里也是IP骤减，从3000多一下自掉到0，长时间搜索也只有个位数，估计是gcd找到了封闭xxnet ip的方法了

**Comment by jap33** [comment]
同上

**Comment by xxnet** [comment]
​试试这个扫描工具，能否扫描到ip
https://github.com/Kisesy/gscan_quic

**Comment by 80068** [comment]
@xxnet 好的，我回去试试看。
