### ISSUE TITLE
多台主机共享xxnet上网

### ISSUE THREAD

**Issue by xdnice** [XX-net/XX-Net#6380]
在一台能上网的linux主机装上了xxnet，其他的主机不能直接上网，请问下，其他主机怎么能通过xxnet代理翻墙。

**Comment by xxnet** [comment]
​设置页面里，高级里有

**Comment by xdnice** [comment]
设置页面的高级下面的导入IP吗？感觉这个和获取的代理地址有关，不知道是不是这个。

**Comment by xdnice** [comment]
已找到解决办法，谢谢。
https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1
