### ISSUE TITLE
最近代理好像都不能用了

### ISSUE THREAD

**Issue by ccitt** [XX-net/XX-Net#6386]
XX-Net Status:
sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.4.1

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:914 good:135
network-status: OK
connected-link: new:2 used:0
worker: h1:5 h2:15
scan-ip-thread-num: 50
ip-quality: 473
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

GAEProxy日志：
Sep 07 11:16:08.961 - [DEBUG] http1 get task
Sep 07 11:16:09.116 - [DEBUG] GAE_Exception 605 'status:500'
Sep 07 11:16:09.116 - [WARNING] gae_exception:'605:status:500' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Sep 07 11:16:09.117 - [DEBUG] http1 get task
Sep 07 11:16:09.219 - [DEBUG] GAE_Exception 605 'status:500'
Sep 07 11:16:09.219 - [WARNING] gae_exception:'605:status:500' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Sep 07 11:16:09.219 - [DEBUG] http1 get task
Sep 07 11:16:09.247 - [DEBUG] GAE_Exception 605 'status:500'
Sep 07 11:16:09.247 - [WARNING] gae_exception:'605:status:500' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

**Comment by MaoJianwei** [comment]
最新版的可以正常部署，但是部署上去的服务器端有问题，我刚刚提交了BUG修复，请跟踪：
https://github.com/XX-net/XX-Net/pull/6388

**Comment by ccitt** [comment]
收到！

**Comment by whhxmwhh** [comment]
谷歌的gae被封锁了的感觉。用备用的梯子吧。

**Comment by whhxmwhh** [comment]
Butterfly VPN 蝴蝶飞侠
https://www.butterflyvpn.com/
轉為繁體網頁
butterfly vpn, butterfly翻墙, butterfly vpn, 蝴蝶飞侠, 蝴蝶在家. ... Butterfly VPN 蝴蝶飞侠. 史上最小轻便的VPN路由器. 专为移动差旅人士、移动办公人士设计.
