### ISSUE TITLE
升级3.4.2后可用ip数量迅速降为0.

### ISSUE THREAD

**Issue by senbaikang** [XX-net/XX-Net#6395]
## 问题
升级3.4.2后可用ip数量迅速降为0.
网络：校园网。

## 诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.4.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

---
## 日志
Sep 07 20:51:34.648 - [WARNING] no enough ip
Sep 07 20:51:35.689 - [WARNING] no enough ip
Sep 07 20:51:36.730 - [WARNING] no enough ip
Sep 07 20:51:37.793 - [WARNING] no enough ip
Sep 07 20:51:38.845 - [WARNING] no enough ip
Sep 07 20:51:39.883 - [WARNING] no enough ip
Sep 07 20:51:40.941 - [WARNING] no enough ip
Sep 07 20:51:41.992 - [WARNING] no enough ip
Sep 07 20:51:43.048 - [WARNING] no enough ip
Sep 07 20:51:44.071 - [WARNING] no enough ip
Sep 07 20:51:45.089 - [WARNING] no enough ip
Sep 07 20:51:48.698 - [DEBUG] sort ip time:52ms
Sep 07 20:52:11.886 - [DEBUG] GET http://www.twitter.com/xxnet
Sep 07 20:52:12.002 - [DEBUG] GET http://www.twitter.com/xxnet
Sep 07 20:52:24.768 - [DEBUG] create ssl timeout fail.
Sep 07 20:52:48.755 - [DEBUG] sort ip time:35ms
Sep 07 20:53:24.781 - [DEBUG] create ssl timeout fail.
Sep 07 20:53:24.816 - [DEBUG] sort ip time:33ms
Sep 07 20:53:24.853 - [WARNING] no enough ip
Sep 07 20:53:26.351 - [WARNING] no enough ip
Sep 07 20:53:27.413 - [WARNING] no enough ip
Sep 07 20:53:28.462 - [WARNING] no enough ip
Sep 07 20:53:29.502 - [WARNING] no enough ip
Sep 07 20:53:30.561 - [WARNING] no enough ip
Sep 07 20:53:31.600 - [WARNING] no enough ip
Sep 07 20:53:32.623 - [WARNING] no enough ip
Sep 07 20:53:32.980 - [DEBUG] GET http://www.twitter.com/xxnet
Sep 07 20:53:33.107 - [DEBUG] GET http://www.twitter.com/xxnet
Sep 07 20:53:33.662 - [WARNING] no enough ip
Sep 07 20:53:34.686 - [WARNING] no enough ip
Sep 07 20:53:35.712 - [WARNING] no enough ip
Sep 07 20:53:36.740 - [WARNING] no enough ip
Sep 07 20:53:37.771 - [WARNING] no enough ip
Sep 07 20:53:38.797 - [WARNING] no enough ip

**Comment by xxnet** [comment]
​重新用回老版本看看

**Comment by onplus** [comment]
#  https://github.com/XX-net/XX-Net/issues/6149

现在没V6环境，测试不了

**Comment by JesusSave** [comment]
XX-Net Status:

sys-platform: x86_64, Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
os-system: Linux
os-version: #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017
os-release: 4.10.0-33-generic
os-detail: Dist:Ubuntu; Version:17.04; ID:zesty
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.4.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:17
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by JesusSave** [comment]
刚开机的时候还不行，过了一会儿，自己好了。Praise the Lord! 

XX-Net Status:

sys-platform: x86_64, Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty
os-system: Linux
os-version: #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017
os-release: 4.10.0-33-generic
os-detail: Dist:Ubuntu; Version:17.04; ID:zesty
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.4.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:18
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:2
scan-ip-thread-num: 50
ip-quality: 792
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
