### ISSUE TITLE
有关更新问题

### ISSUE THREAD

**Issue by fhzyfjy** [XX-net/XX-Net#64]
1、是否可以自动更新？
2、如果无法自动更新，是否每次都要重新上传服务端？
1.2.1布置自己的APPID看视频没问题，但1.3.1重新布置自己的APPID后无法看视频，连1.2.1也无法看视频了。谢谢

**Comment by lyp4140** [comment]
为什么自己的APPID感觉没有公共IP速度快啊

**Comment by xxnet** [comment]
自己的appid不会有性能，可能是你配置完之后，goagent重启，还没有进入最佳状态，需要稍微等一下。

1. 自动更新，下周开始部署。
2. 每次新版不需要重新上传服务端。除非特别声明。
3. 1.3.1 的服务端和1.2.1是一样的，你确认看看goagent/3.1.38/server/gae/wsgi.py 第8行
  __hostsdeny__ = ()
  表示没有限制
  而下面那行前面加了#注释掉了。

**Comment by fhzyfjy** [comment]
谢谢。是不是只在新版本中的“配置GoAgent”填入自己的APPID既可。

**Comment by xxnet** [comment]
如果以前已经部署过XXNet的服务端，那么填入自己的appid即可。
如果是goagent 3.2后的版本，那么需要重新部署服务端。

**Comment by fhzyfjy** [comment]
非常感谢。目前最大的问题是看视频时，不太流畅。有时可以看，过一阵又不能看。不知是否有好的解决办法。谢谢

**Comment by xxnet** [comment]
看视频的问题，正准备升级3.2的服务端版本，我测试过效果不多。希望可以优化。

**Comment by fhzyfjy** [comment]
期待中，辛苦了朋友。谢谢

**Comment by xxnet** [comment]
关于自动升级：

昨天调试了1天，发现之前忘记创建data/downloads，导致下载失败。所以之前的版本无法升级。
请手动升级到1.3.5之后，才能自动升级。


关于视频的速度，1.3.5调了参数，估计能够快一些了。

**Comment by xxnet** [comment]
1.7 发布几天了，准备发布自动更新
