### ISSUE TITLE
误点更新后出现“请检查浏览器代理设置。”问题，恢复稳定版亦无法恢复

### ISSUE THREAD

**Issue by latinisation** [XX-net/XX-Net#6408]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2991
network-status: OK
connected-link: new:2 used:0
worker: h1:3 h2:7
scan-ip-thread-num: 50
ip-quality: 549
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by latinisation** [comment]
属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 2990
空闲 | 0
IP延迟 | 550
连接池(帮助) | 新:0 h1:4 h2:5
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
扫描IP线程数(设置) | 50
屏蔽状态(帮助) | OK

**Comment by onplus** [comment]
###  cmd 
`ipconfig /flushdns`
### chrome
```
chrome://net-internals/#dns

> Clear host cache
```

**Comment by latinisation** [comment]
@onplus 感谢解答！试了但还是不行

**Comment by 308901951** [comment]
个人经验，把XXNET安装文件夹里始终保持只有一个版本，把另外一个旧版本删除，或者移出安装文件夹，一个大小估计50M左右，用360CHROME浏览器，CHROME各种问题，我连OMEGA插件都不用直接就用都行

**Comment by latinisation** [comment]
@308901951 试了，还是不行，谢谢
