### ISSUE TITLE
请问“扫描IP设置”可以设置排除的IP地址吗？

### ISSUE THREAD

**Issue by yebr** [XX-net/XX-Net#641]
请问格式该怎么写？
如果不能设置，希望后续能加上这个功能，谢谢！

**Comment by xxnet** [comment]
操作上，从ip_range.txt中剔除不想扫描的范围就好。

理论上，如果问题不大，就不必排除了，有很多ip段以前没有搜索到ip，后来google调整了，又可以了

在 2015年7月17日 下午4:10，yebr <notifications@github.com>写道：

**Comment by yebr** [comment]
好的，谢谢您的解答！
