### ISSUE TITLE
GAE的访问端口是什么？可以自己设置吗？

### ISSUE THREAD

**Issue by dao3300** [XX-net/XX-Net#6414]
局域网上网，到特定时间可能有些端口就关闭了，我的XX-NET就用不了了。但是我知道有一些端口还是开放着的，比如我的shadowsocks就改为这些端口就能继续用。

我想知道goagent 与 GAE之间的通讯端口是什么？可以自己重新设置吗？

**Comment by caofengzi** [comment]
可以修改端口，但是需要用專用修改工具打開goagent.exe才能修改端口。

**Comment by dao3300** [comment]
本地客户端、和远程服务器上面有配置文件吗？

**Comment by onplus** [comment]
@caofengzi xxnet里哪来的go.exe文件？

[https://github.com/XX-net/XX-Net/search?q=配置&type=Wikis](https://github.com/XX-net/XX-Net/search?q=%E9%85%8D%E7%BD%AE&type=Wikis&utf8=%E2%9C%93)
