### ISSUE TITLE
xx有断网情况

### ISSUE THREAD

**Issue by andylee1890** [XX-net/XX-Net#6419]
mac版, 刚升级了最新版. 这两天打开xx用一会儿就会断网, ping baidu.com都ping不通, 然后把xx关掉,过一会儿网就好了, 但是再打开xx,重新扫描一遍ip,过一会儿又断网了, 如此反复

**Comment by onplus** [comment]
同一路由器下的其他设备能正常联网吗

**Comment by andylee1890** [comment]
@onplus 手机是正常的

**Comment by onplus** [comment]
贴诊断信息和日志看看

**Comment by xxnet** [comment]
​一般 ISP 不会采用断网方式，即使检测到有人翻墙。
你先排除是自身机器原因，还是路由器原因。

**Comment by ugvf2009** [comment]
@xxnet 昨天一直Timeout，最新版本，今天竟然正常了。不知道为什么昨天的墙那么高。
