### ISSUE TITLE
客户端GoAgent 和服务器端 Google App Engine 之间的通讯端口是多少？

### ISSUE THREAD

**Issue by dao3300** [XX-net/XX-Net#6435]
局域网上网，到特定时间可能有些端口就关闭了，我的XX-NET就用不了了。但是我知道有一些端口还是开放着的，比如我的shadowsocks就改为这些端口就能继续用。

我想知道goagent 与 GAE之间的通讯端口是什么？可以自己重新设置吗？

**Comment by wenliyang** [comment]
https://github.com/XX-net/XX-Net/issues/6414

同样的问题，重复提问也不一定会有答案的
