### ISSUE TITLE
3.5.0 发布

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#6456]
## 新特性：
采用cloudflare 代替GAE前端，解决google ip 被封问题。
请使用x_tunnel 的代理，Socks5 端口 1080。
测试阶段，登陆送测试流量。
请不要滥用，谢谢支持。

[下载 3.5.3](https://github.com/XX-net/XX-Net/archive/3.5.3.zip)

**Comment by qjwq** [comment]
沙发，谢谢

**Comment by qjwq** [comment]
请使用x_tunnel 的代理，Socks5 端口 1080。
这句话怎么理解，与以往操作上有什么不同，小白求教！

**Comment by xxnet** [comment]
原来用GAE代理，是 https方式， 8087端口。
这个版本改进是x_tunnel，不再依赖GAE代理。

浏览器里的代理设置需要换为x_tunnel的，SwichySharp里设置：
代理模式： Socks5
代理服务器：  127.0.0.1 端口 1080

**Comment by lzhr** [comment]
lzhrsmile@gmail.com

**Comment by MadMaxPayne8964** [comment]
GAE伴随我走了很多年，很舍不得就这么完蛋。哎

**Comment by jzp820927** [comment]
改进很不错，看来 X 大是要转向 CDN 技术了。
不过流量是个大问题，XXNET 这么大的用户量，靠 x_tunnel ，估计力不从心啊。

**Comment by sky233** [comment]
感谢作者辛勤付出，造福大家

**Comment by xxnet** [comment]
过了这轮就会放开的，每年都会这样来两下。

需要大流量的可以花钱买，套餐应该足够使用的。
送大家的2G流量问题不大
@jzp820927
帮忙送下流量。

大家也反馈下使用情况。

**Comment by jzp820927** [comment]
@xxnet 好的，没问题。
我在想，如果不只是从 cf 中转到 x_tunnel，而且还可以从 cf 中转到 GAE，那就完美了。

**Comment by xxnet** [comment]
@jzp82927
  cloudflare 中转，要求把网站的顶级域名解析接管过来，GAE是不可能的了。

**Comment by qjwq** [comment]
@xxnet 请问如何获取xxx_tunnel帐号？搞不懂，见笑啦，先谢！

**Comment by xxnet** [comment]
客户端Web页面上注册

**Comment by sky233** [comment]
@xxnet lixingping233@163.com 请问下为啥注册一直卡在 请稍后呢？
![gh 0 knqircuh y h x39](https://user-images.githubusercontent.com/8347219/30434026-b09af440-9998-11e7-925b-812dc4ccc856.png)

**Comment by Hspine** [comment]
最近确实延迟越来越大了。
我的x_tunnel帐号为hspine@gmail.com，感谢。

**Comment by qjwq** [comment]
@xxnet 还需要复制date文件夹吗？

**Comment by Icarus079** [comment]
我的x_tunnel帐号为yylj77@gmail.com
多谢了  希望能解决掉这个问题   感谢XXnet的付出

**Comment by xxnet** [comment]
可能你的cloudflare还未连接上，如果是命令行启动，请看看命令行的日志。

赶着发布，还无法从web 界面上看到cloudflare_front的日志。

**Comment by doubi22** [comment]
我的x_tunnel帐号为2585015543@qq.com
谢谢了

**Comment by xxnet** [comment]
@sky233
  你重试下

@Hspine @lcarus079 @doubi22 流量已转

@qjwqu
  data目录可以不用复制

到目前有谁成功的，反馈下。

**Comment by sky233** [comment]
@xxnet 我看了控制台的日志
![1](https://user-images.githubusercontent.com/8347219/30435102-83e1bbc0-999b-11e7-85b1-396410e3e0a8.png)

**Comment by Icarus079** [comment]
我的XX-Tunnel 可用 不过速度没有xxnet快

**Comment by Icarus079** [comment]
![zz2y jml wh9oq jac76 10](https://user-images.githubusercontent.com/30079703/30435271-f30143cc-999b-11e7-82e3-281051b6d76c.png)

**Comment by trystudy** [comment]
@sky233
我和你一样，注册不了。

**Comment by zangyijun** [comment]
XX-Net-3.5.0安装了，也更新了SwitchyOmega可是怎么也进不了XX-Net页面了不知道是为什么

**Comment by qjwq** [comment]
我的问题好像和@sky233一样的状况。

**Comment by xxnet** [comment]
有bug，稍等，我发个补丁版本

**Comment by qjwq** [comment]
欢迎，辛苦了，感谢！@xxnet

**Comment by liyong1222** [comment]
x_tunnel帐号：705824983@qq.com。感谢

**Comment by xxnet** [comment]
好了，再试试.
[3.5.1 下载](https://github.com/XX-net/XX-Net/archive/3.5.1.zip)

**Comment by qjwq** [comment]
大虾告诉我如何注册？

**Comment by qjwq** [comment]
必须成功安装3.5.1后才能注册吗？

**Comment by qjwq** [comment]
没翻墙下载速度也这么慢？怎么回事呢？是要全面断网的节奏么？

**Comment by xxnet** [comment]
要用3.5.1 才能使用

使用指南：
https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B

**Comment by zangyijun** [comment]
感谢，@xxnet 辛苦了！

**Comment by trystudy** [comment]
@xxnet 
3.5.1好用了注册好了。
trystudy2@gmail.com

感谢，@xxnet 辛苦了！

**Comment by sky233** [comment]
@xxnet x_tunnel帐号：lixingping233@163.com。感谢 辛苦了

**Comment by kitkw** [comment]
jamw@live.cn  谢谢

**Comment by 924932118** [comment]
感谢，辛苦了！看了以后只能用x-tunel了，我的账号：924932118@qq.com

**Comment by cmhtdv** [comment]
谢谢,我的账号：sbhtsm69@gmail.com,试试速度怎样

**Comment by foho8080** [comment]
@xxnet  谢谢,我的账号 foho8080@gmail.com

**Comment by yingzhelai** [comment]
@xxnet 3.5.1可以注册，账号：1194439403@qq.com。谢谢

**Comment by shaodongliang** [comment]
@xxnet 我的账号787773580@qq.con 谢谢！

**Comment by guanyueqi** [comment]
@xxnet @jzp820927 我的账号guanyueqi9393@gmail.com

**Comment by a7082633** [comment]
我的x_tunnel帐号为a7082633@gmail.com
多谢了 希望能解决掉这个问题 感谢XXnet的付出

**Comment by daszgd** [comment]
我的账号是gaoke123gaoke@gmail.com
谢谢X大了

**Comment by xxnet** [comment]
guanyueqi9393@gmail.com 帐号不存在 @guanyueqi

其他流量都转了

**Comment by xxnet** [comment]
性能还未优化，还有很多细节要完善。

大家也可以反馈下使用感受

**Comment by foho8080** [comment]
@xxnet  這個新版是否都要將3.4.2的data移動到3.5.0版本

**Comment by foho8080** [comment]
@xxnet  這個新版是否都要將3.4.2的data移動到3.5.0版本

**Comment by kitkw** [comment]
guanyueqi9393@gmail.com 帐号不存在 @guanyueqi

其他流量都转了

怎么我还是没有   jamw@live.cn

**Comment by zxyduang** [comment]
我的账号是zxyduang@gmail.com
非常感谢

**Comment by Tsundoro** [comment]
哇.3.50搞了好久，还以为我操作有问题。。。
上来再看有个3.51.。。。
是不是还要留账号？
1907896023@qq.com
@xxnet

**Comment by zangyijun** [comment]
还是上不了 XX-Net的页面，浏览器提示 You can't perform that action at this time.请作者指点一下，多谢！

**Comment by decemer** [comment]
decemer@gmail.com
@xxnet

**Comment by kitkw** [comment]
有了  谢谢

**Comment by shaodongliang** [comment]
@xxnet  X-Tunnel账号登出之后重新登录登不上了   我的账号787773580@qq.com没看到有流量呀 劳烦帮看一下 谢谢x大

**Comment by serah0** [comment]
@xxnet 
我的账号是x42030670@163.com
感谢大大，辛苦了

**Comment by kitkw** [comment]
感觉这个很慢.还是原来的好用,就是扫不到IP.

**Comment by lzhr** [comment]
@foho8080 下载压缩包，替换原code文件夹就行了。data文件夹肯定是保留的，除非版本大改

@xxnet  x_tunnel打开网站比较慢，但是看youtube又不卡，web日志也看不出什么信息

**Comment by ToDonJing** [comment]
tudongjing@gmail.com
thanks.

**Comment by Alobe007** [comment]
lancitou@126.com
非常感谢。

**Comment by Zane0** [comment]
x_tunnel 帐号：zlzohvzew@gmail.com
求一些流量，谢谢。

**Comment by vondevil666** [comment]
dongzhimenjjy@gmail.com
谢谢

**Comment by zjcxdcq** [comment]
我这样直接把SwichySharp安装玩后就删除了x_tunnel 的代理选项的咋搞。。。

**Comment by lt201081** [comment]
我的x_tunnel帐号为lt201081@gmail.com

**Comment by mrqinmo** [comment]
谢谢,我的账号 mrqinmo@gmail.com

**Comment by foho8080** [comment]
為什麼這個版本的xx-net標誌不出現在任務欄.電腦重啟幾次都沒有出現

**Comment by Tsundoro** [comment]
话说扫描大概需要多久。我这扫了有40分钟了

**Comment by hellowx** [comment]
hellolionwx@gmail.com 谢谢老大！

**Comment by peter211CHEN** [comment]
Sep 14 23:28:06.582 - [ERROR] roundtrip time:640 transfer_no:43 sn:43 send:205 len:0 status:200 retry:6

Sep 14 23:28:12.944 - [ERROR] roundtrip time:6361 transfer_no:43 sn:43 send:205 len:0 status:200 retry:7

Sep 14 23:28:13.034 - [ERROR] roundtrip time:8291 transfer_no:48 sn:48 send:202 len:0 status:200 retry:7

Sep 14 23:28:13.686 - [ERROR] roundtrip time:7474 transfer_no:46 sn:46 send:202 len:0 status:200 retry:4

Sep 14 23:28:13.866 - [ERROR] roundtrip time:11965 transfer_no:45 sn:45 send:30 len:0 status:200 retry:4

Sep 14 23:28:16.336 - [ERROR] roundtrip time:2470 transfer_no:45 sn:45 send:30 len:0 status:200 retry:5

Sep 14 23:28:17.556 - [ERROR] roundtrip time:4522 transfer_no:48 sn:48 send:202 len:0 status:200 retry:8

Sep 14 23:28:17.706 - [ERROR] roundtrip time:1370 transfer_no:45 sn:45 send:30 len:0 status:200 retry:6

Sep 14 23:28:18.058 - [ERROR] roundtrip time:4371 transfer_no:46 sn:46 send:202 len:0 status:200 retry:5

Sep 14 23:28:18.598 - [ERROR] roundtrip time:539 transfer_no:46 sn:46 send:202 len:0 status:200 retry:6

Sep 14 23:28:19.878 - [WARNING] roundtrip time:25101 transfer_no:47 send_sn:47 send:30 status:500 retry:3

Sep 14 23:28:20.328 - [WARNING] roundtrip time:25101 transfer_no:49 send_sn:49 send:30 status:500 retry:2

Sep 14 23:28:20.878 - [WARNING] roundtrip time:25002 transfer_no:50 send_sn:50 send:202 status:500 retry:2

Sep 14 23:28:22.468 - [ERROR] roundtrip time:24289 transfer_no:42 sn:42 send:33 len:0 status:200 retry:5

Sep 14 23:28:22.578 - [WARNING] roundtrip time:25190 transfer_no:44 send_sn:44 send:25 status:500 retry:3

Sep 14 23:28:23.438 - [ERROR] roundtrip time:4839 transfer_no:46 sn:46 send:202 len:0 status:200 retry:7

Sep 14 23:28:23.558 - [ERROR] roundtrip time:1230 transfer_no:49 sn:49 send:30 len:0 status:200 retry:3

Sep 14 23:28:26.708 - [ERROR] roundtrip time:3269 transfer_no:46 sn:46 send:202 len:0 status:200 retry:8

Sep 14 23:28:27.438 - [ERROR] roundtrip time:4970 transfer_no:42 sn:42 send:33 len:0 status:200 retry:6

Sep 14 23:28:28.388 - [ERROR] roundtrip time:5509 transfer_no:47 sn:47 send:30 len:0 status:200 retry:4

Sep 14 23:28:28.730 - [ERROR] roundtrip time:15786 transfer_no:43 sn:43 send:205 len:0 status:200 retry:8

Sep 14 23:28:29.310 - [ERROR] roundtrip time:2601 transfer_no:46 sn:46 send:202 len:0 status:200 retry:9

Sep 14 23:28:30.160 - [ERROR] roundtrip time:1430 transfer_no:43 sn:43 send:205 len:0 status:200 retry:9

**Comment by onplus** [comment]
@foho8080 3.5.1 ？

@zjcxdcq https://github.com/XX-net/XX-Net/issues/6456#issuecomment-329485596
还有多用搜索https://github.com/XX-net/XX-Net/search?q=x-tunnel&type=Wikis&utf8=%E2%9C%93

**Comment by deepreflex** [comment]
binlibinli666@gmail.com，感谢您的无私分享！ @xxnet @jzp820927

**Comment by OneLine-Lee** [comment]
god654836493@gmail.com  感谢大大无私奉献！
@xxnet  @jzp820927

**Comment by qjwq** [comment]
cqrcb.wangqian@gmail.com谢谢 @xxnet

**Comment by xllfe** [comment]
maya5017@gmail.com 谢谢大大的分享 @xxnet

**Comment by sophiesugar** [comment]
pstheresa@gmail.com 感谢

**Comment by yuhui44** [comment]
谢谢,我的账号 yuhui4444@gmail.com

**Comment by qjwq** [comment]
@xxnet 这个状态正常吗
![image](https://user-images.githubusercontent.com/28836737/30439715-1d2fd644-99a7-11e7-820b-2ddf31ed39e2.png)

**Comment by hellowx** [comment]
wx16@tom.com谢谢,我的账号

**Comment by qjwq** [comment]
![image](https://user-images.githubusercontent.com/28836737/30439824-62eabbae-99a7-11e7-8565-1887ae61d966.png)

**Comment by kitkw** [comment]
添加了规则到switch   但很奇怪有时能上  不时不能………………

**Comment by foho8080** [comment]
x_tunnel 的代理 比xx-net代理打開網頁較慢

**Comment by fredahfred** [comment]
我的账号是li.fred@msn.com

谢谢大神。

**Comment by guo333323** [comment]
guo333323@sina.cn谢谢,我的账号

**Comment by foho8080** [comment]
為什麼登陸配置之後很容易自動退出賬號

**Comment by gaoxuezhao** [comment]
3.5.1 版本，
1、一直停留在 请等待大约半小时，XX-Net需要扫描IP 连接池为空。
2、x-tunnel 停留在请稍后。

**Comment by raojunwen** [comment]
我的账号raojunwen@gmail.com，感谢！

**Comment by gaoxuezhao** [comment]
我的账号gaoxuezhao@163.com，感谢！

**Comment by shisy** [comment]
我的账号，ssygogoo@sina.com，辛苦各位大神了！

**Comment by mib012** [comment]
我的账号，fireworkblow@gmail.com，感谢大神！

**Comment by NikoManiac** [comment]
我的x_tunnel帐号为996915941@qq.com，感谢。

**Comment by zangyijun** [comment]
重启了系统终于可以登上XX-Net页面了，我的x_tunnel帐号zangyj1971@gmail.com，感谢！

**Comment by zjcxdcq** [comment]
@onplus 感谢帮助！我的意思是 ——大神说：‘浏览器里的代理设置需要换为x_tunnel的，SwichySharp里设置。。。——这里代理设置指的是SwichySharp的x_tunnel选项吧？但当时我安装完SwichySharp设置了XX-NET的选项后就直接删除了x_tunnel的选项！我不知道怎么重新设置！您给的搜索结果只是介绍和怎么使用！没有怎么在SwichySharp里添加！

**Comment by mlxjshz** [comment]
我的 x_tunnel帐号 mlxjshz@gmail.com
谢谢大神
@xxnet

**Comment by jxgive** [comment]
我的x_tunnel帐号为18814125513@qq.com，感谢。@xxnet

**Comment by onplus** [comment]
### @zjcxdcq 你就是不会用switchyomega！搜索结果不就是教怎么使用？“添加”不是使用的一部分？
![sss](https://user-images.githubusercontent.com/31188782/30442025-c243455c-99ad-11e7-99f1-174a6058f2f1.JPG)
### 不会添加就直接重装吧
https://github.com/XX-net/XX-Net/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E4%BD%BF%E7%94%A8-SwitchyOmega#%E9%85%8D%E7%BD%AE

**Comment by will0705** [comment]
给点流量吧，
我的账号：  will0705@163.com

**Comment by zjcxdcq** [comment]
@onplus 感谢感谢！竟然那么简单 ！我的错。我没认真看使用教程！

**Comment by zangyijun** [comment]
大神给点流量吧
zangyj1971@gmail.com
特别感谢！

**Comment by DyingLight100** [comment]
oracle2012@foxmail.com

感谢大神

**Comment by holycake** [comment]
感謝大神。自從用上xx-net后就沒操心過失效的問題。想不到這一次出現大危機。
我的郵箱holycake@gmail.com由于X-Tunnel沒有流量，所以一直沒用，想不到密碼忘了。不知能否找回，或者將密碼發往郵箱？再次感謝。

**Comment by wlld1984** [comment]
weile.dandan@gmail.com
非常感谢！

**Comment by peter211CHEN** [comment]
我的 x_tunnel帐号chensj806@163.com

**Comment by Supgb** [comment]
supgb96@gmail.com
非常感谢！

**Comment by guangziyun** [comment]
@xxnet 谢谢,我的账号 guangziyun@gmail.com谢谢

**Comment by liu1169681** [comment]
我的x_tunnel帐号为275402937@qq.com，感谢！@xxnet

**Comment by czy09** [comment]
我的 x_tunnel帐号 czy09@hotmail.com 谢谢！

**Comment by zangyijun** [comment]
为什么X-Tunnel登录总是掉线？

**Comment by longlanyu** [comment]
@xxnet 谢过，我的账号是longlanyu@gmail.com

**Comment by iloveinter44** [comment]
@xxnet iloveinter44@gmail.com

**Comment by djfruewe** [comment]
@xxnet 1147165173@qq.com  非常感谢

**Comment by roc1010kmt** [comment]
是說這個新版本gae模塊部分沒有更新嗎？

**Comment by Cleonwang** [comment]
@xxnet 账户wangcl4833@sina.com  谢谢！！

**Comment by hibluesea** [comment]
@xxnet 账户bluesea7410@gmail.com 谢谢！顺便问下使用x_tunnel的话GAE AppID 的配置还需要填写吗？

**Comment by liqingshan177** [comment]
x-tunnel账号：liqingshan177@gmail.com  谢谢

**Comment by ZhangSiQihandsome** [comment]
x-tunnel账号：1098795322@qq.com 谢谢

**Comment by hibluesea** [comment]
@jzp820927 ,求一些流量x-tunnel:  bluesea7410@gmail.com，啥都看不到了

**Comment by chenzijng** [comment]
chkchj@126.com，我想试试看

**Comment by EzekielZC** [comment]
求流量ezekielzc@gmail.com

**Comment by djfruewe** [comment]
@xxnet w1271408017@gmail.com 谢谢

**Comment by jimmyyang1224** [comment]
kaoonline@gmail.com谢谢

**Comment by robinshiesh** [comment]
robinshiesh@gmail.com
非常感谢

**Comment by leowang029** [comment]
leowang029@gmail.com
感谢作者，几年一直用下来

**Comment by jxgive** [comment]
我的x_tunnel帐号为18814125513@qq.com，还没测试流量，另外邮箱还被大量订阅邮件。 @xxnet

**Comment by jxgive** [comment]
我的x_tunnel帐号为2423034145@qq.com，还没有测试流量，另外邮箱被大量订阅了X-TUNNEL的邮件，是设置出错么。 @xxnet

**Comment by wanghz** [comment]
@jzp820927  清施舍点流量，谢谢， wanghz@protonmail.com

**Comment by jxgive** [comment]
我的x_tunnel帐号为2423034145@qq.com，还没有测试流量。 @xxnet

**Comment by github-tom** [comment]
944797590@qq.com  摇啊摇

**Comment by internetboss** [comment]
大神啊求XT流量：cosmosee@gmail.com

**Comment by foho8080** [comment]
@causlayer   3.5.1版本可以用gmail

**Comment by wlwwm** [comment]
非常感谢：wlzawwm@163.com

**Comment by ElfenZ** [comment]
elfenzhang@gmail.com，非常感谢。另外，想知道如何购买套餐流量，在页面点了套餐购买，跳转不过去

**Comment by hefujian** [comment]
hefujian@gmail.com ，非常感谢。

**Comment by yiluheihei** [comment]
caoyang4277@126.com，谢谢

**Comment by yabaoer** [comment]
561496211@qq.com  非常感谢，我还没用过X-Tunnel，xxnet 3.3.6还可以使用，每天都有100来个ip

**Comment by HuberyQing** [comment]
yangyinqing@qq.com  谢谢，尝试一下xx-tunnel.这个可以智能pac嘛 还是智能安装chrome插件 浏览器使用

**Comment by lgc0313** [comment]
diver0912@gmail.com 谢谢，麻烦给点流量

**Comment by kevinweiqy** [comment]
kevinweiqy@gmail.com　谢谢！！！！！

**Comment by cz8123** [comment]
691120770@qq.com,非常感谢。

**Comment by xgytao** [comment]
给点流量吧，3629458@qq.com

**Comment by saintethan** [comment]
x-Tunnel账户masterkang92@gmail.com。感谢X大的付出。

**Comment by xirijn2** [comment]
xirijn@163.com，谢谢XX大，辛苦了！

**Comment by chaoxiaosu** [comment]
chaoxiaosu@gmail.com 谢谢

**Comment by wooowooo** [comment]
wooowooo@github.com
谢谢

**Comment by crdifa** [comment]
信息@xxnet 我的x_tunnel帐号sucaiTV@163.com

**Comment by boards77** [comment]
boards7777@163.com 谢谢

**Comment by teazean** [comment]
teazean@qq.com 谢谢楼主，之前一直用gae，现在不能用了，考虑要买一下xtunnel了，xxnet用起来还是省心。。

**Comment by litengzi** [comment]
@xxnet  我的x_tunnel帐号 10321034@qq.com  谢谢你~

**Comment by geshou** [comment]
@xxnet 谢谢,我的账号 hjldq2005@gmail.com

**Comment by liuchonggao** [comment]
@xxnet liuchonggao6@gmail.com 谢谢，以上是我的账号

**Comment by Ayler-Lee** [comment]
ayler3389@163.com

@xxnet  辛苦

**Comment by fanpishui** [comment]
@xxnet 感谢你的付出，yulaifozu123@163.com

**Comment by MitchellClark666** [comment]
感谢你的付出
wyj2009sky@gmail.com

**Comment by Lynchie** [comment]
shaohl629@gmail.com 感谢

**Comment by edtxer** [comment]
edtxer@gmail.com 谢谢
@xxnet 受累了

**Comment by popsky** [comment]
sukong@outlook.com  谢谢

**Comment by daomuwangzi** [comment]
daomuwangzi@gmail.com 非常感谢！

**Comment by Fangjunwen** [comment]
f_junwen@yeah.net  感谢

**Comment by izgy** [comment]
izgy@qq.com 
izgy@vip.qq.com
谢谢

**Comment by hdoo** [comment]
我的x_tunnel帐号 gzsbzbl528@163.com  谢谢X大

**Comment by yanjiuling** [comment]
@xxnet ali@bchuang.cn 刚购买一季度流量，设置没有问题，不能用什么原因
![image](https://user-images.githubusercontent.com/6215056/30466515-f158ee6a-9a10-11e7-84aa-ed8d72c23088.png)
![image](https://user-images.githubusercontent.com/6215056/30466542-22942922-9a11-11e7-9017-ce37bb26c46f.png)

**Comment by benjiexx** [comment]
coolpbj@qq.com 谢谢!

**Comment by g8up** [comment]
求测试流量，帐号：dodo.cpp@qq.com
这两天不能查资料，工作都耽搁了，但 gov 的税还是照收不误...

**Comment by xjedges** [comment]
我的x_tunnel帐号为 xj.edges@gmail.com
谢谢了

**Comment by VenusGitHub** [comment]
我的x_tunnel帐号272411754@qq.com
感谢

**Comment by xxnet** [comment]
上面的流量已转。


@decemer
decemer@gmail.com 账号不存在；

@hellowx 
hellolionwx@gmail.com 账号不存在

@sophiesugar 
pstheresa@gmail.com 不存在

@hellowx 
wx16@tom.com 不存在
  
@jxgive
18814125513@qq.com 不存在

**已发布3.5.3版本，改进性能，不过目前善存在改进空间。**
[下载 3.5.3](https://codeload.github.com/XX-net/XX-Net/zip/3.5.3)

**Comment by VenusGitHub** [comment]
@xxnet 大佬我的272411754@qq.com 没收到流量啊

**Comment by Weibin74** [comment]
@xxnet z751799647@163.com 下了新版准备试试看. 先谢过xxnet项目:-)

**Comment by noahvlin** [comment]
我的x_tunnel帐号  chihee1994@outlook.com
非常感谢！

**Comment by 2579019321** [comment]
我的x_tunnel帐号xxw86590@outlook.com

**Comment by xxnet** [comment]
@yanjiuling 
  你只是充值，没有换成流量，要点套餐，用里面的钱换流量。

**Comment by xxnet** [comment]
现在新注册的帐号，会自动送流量了。

**Comment by noahvlin** [comment]
@xxnet 流量收到，真的非常感谢，救急啊

**Comment by xxnet** [comment]
​有用就好，没有白忙乎。

你们的支持就是我的动力！

**Comment by izgy** [comment]
我的x_tunnel帐号izgy@qq.com

**Comment by VenusGitHub** [comment]
@xxnet 是不是不支持udp

**Comment by xxnet** [comment]
@VenusGitHub 
  目前还没有支持UDP，如果需求大的话，可以开发。

**Comment by litengzi** [comment]
@xxnet 你好，可不可以给我些测试流量？

**Comment by litengzi** [comment]
@xxnet 你好，可不可以给我些测试流量？10321034@qq.com

**Comment by dou4cc** [comment]
@xxnet 你身在国外，随便改前置也不讨论一下，XX-Net只会沦为Psiphon：
[CloudFlare从限速到间歇性封锁](https://twitter.com/kujou_rin/status/899292385057755137)

**Comment by dou4cc** [comment]
@xxnet 反人类罪犯是没有底线的

**Comment by xxnet** [comment]
采用扫ip的方式，真要封了cloudflare，影响就和断网差不多了。
墙如果真的完全断网，就只能靠P2P了。

**Comment by dou4cc** [comment]
@xxnet 扫ip和不和谐的dns请求影响网速，不管国内国外：https://github.com/phuslu/goproxy/issues/2026#issuecomment-329079553

**Comment by dou4cc** [comment]
@xxnet 现在的趋势是沦陷区只保证能上外网，似乎任何服务都能随时限速或间歇性封锁。

**Comment by vvvyyy** [comment]
问下为什么我最新版打开直接扫不到IP，x_tunnel注册了但是没用成功，不知道哪里步骤错了，现在怎么办，最新版配合x_tunnel是否速度更快，我现在用回3.3.6，起码能用，能扫到30个IP，请问我现在怎么办啊，怎么回事，有些步骤真的不懂，唉。。 @xxnet

**Comment by xxnet** [comment]
扫ip的线程开小，墙就不好判断了。
很多网页、手机app都会主动连墙外的网站，这种特征不明显。

直接封锁，这种做法在很多年前就试过，影响很不好。
很容易误伤，这也是墙要避免的。

**Comment by xxnet** [comment]
@vvvyyy
 有30个ip，在新版里可以跑得很欢快了。

看来x_tunnel需要有一份更加简单明了的说明文档。

**Comment by dou4cc** [comment]
@xxnet 不存在误伤，短连接较多isp可以直接限速。反正即使是良民，下载时也不会有很多短连接；浏览网页时短连接多，但这时即使限速也没啥影响。

**Comment by vvvyyy** [comment]
问题是我下了新版打开就没有IP呀，怎么办 @xxnet

**Comment by XueTeng2** [comment]
用XX-Net的自动检查更新不能升级最新版吗？

**Comment by lyfbuaa** [comment]
求测试流量，帐号：loooooooooogle@gmail.com

**Comment by xxnet** [comment]
@dou4cc
​新版x_tunnel 是长连接，连接会保持住重复使用。

@XueTeng2
 自动更新版本，也是在控制之内，是为了避免不稳定版本影响用户使用。
 暂时看来 3.5.3 可以进入测试版本的自动更新列表了。

**Comment by dou4cc** [comment]
@xxnet 我是说xtunnel扫ip产生的流量

**Comment by partery** [comment]
bookmark.cc@gmail.com

**Comment by xxnet** [comment]
@dou4cc 
  cloudflare 的ip 已经扫好一份了，拿到客户端就可以直接连接。
  后台默认开1个线程慢慢扫，这个线程应该不会影响什么。

  只要启动放在那里，也能慢慢更新ip库，这就达到我们要的目的了。
  毕竟cloudflare的ip大范围封的概率不大。

**Comment by alexbyrant** [comment]
kobebyrant236@gmail.com 多谢辛勤付出

**Comment by brookchou** [comment]
我的X-tunnel账号为greenberet003@gmail.com。谢谢开发人员的辛勤付出！

**Comment by xxnet** [comment]
现在测试阶段，登陆就送流量，不用再跟贴发帐号。
还没有流量的，只要重启xx-net就可以看到流量了。

大家不要滥用，毕竟都是要花钱买的。
流量有限，这一批流量用完就会调整策略。

**Comment by alex89999** [comment]
感谢大大的辛勤付出，好人有好报！！！！

**Comment by xxnet** [comment]
这贴太长了，想清理一下，还是放弃了。
直接关闭，另外开新帖。

#6480

**Comment by jzp820927** [comment]
直接锁贴不就得了。简单粗暴。

**Comment by lyfbuaa** [comment]
谢谢，这么快就收到流量了 ：）

**Comment by gaoxuezhao** [comment]
为什么登陆不上啊？
