### ISSUE TITLE
是IP问题？？还是XXNET问题？？？

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#6458]
我3.4.2扫到的IP很少只有5个，延迟高但还是能上，没什么问题。但用这5个导入3.5.0/1就不能用，就3.4.2没问题怎么回事？？
纯小白
只剩下救命的5个，请原谅不能分享。

是不是根本就不是IP问题！！！

**Comment by onplus** [comment]
3.3.6 > 3.4.2 修改了gae代码
3.4.2 > 3.5.1 并没有修改gae部分的功能代码

3.5.0有bug，不要用了

**Comment by kitkw** [comment]
不懂。好像是自动升了3.4.2才有这个IP问题。想转回旧版本但没有打到下载地址……

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/releases

**Comment by kitkw** [comment]
谢谢

**Comment by kitkw** [comment]
有2个包应该下哪一个
