### ISSUE TITLE
这什么情况，又好了吗？

### ISSUE THREAD

**Issue by lh471921250** [XX-net/XX-Net#6470]
昨天才5个ip，今天这么多了，还在不停的涨。。。 
![qq 20170915134132](https://user-images.githubusercontent.com/14818014/30468130-0002c296-9a1c-11e7-9d9e-3069439ccf11.png)

**Comment by dunhamdaxia** [comment]
我的还是不行呀

**Comment by mufengf** [comment]
昨天晚上一个ip都不能用今天突然有1000多个可以用了

**Comment by xxnet** [comment]
难道是发了新版3.5x，墙觉得这样封ip没有意义了，就放开了，哈哈哈。。。

**Comment by mufengf** [comment]
不知道 刚刚ip又掉下去了 没有ip但是能用

**Comment by dunhamdaxia** [comment]
我的一直显示尚未建立链接   可以了一瞬间   现在有不行了

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.4.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:18600 good:13802
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
