### ISSUE TITLE
X-tunnel无法注册

### ISSUE THREAD

**Issue by phycsjay** [XX-net/XX-Net#6475]
注册X-tunnel显示未知错误

日志
Sep 15 15:03:46.895 - [INFO] use config_path:C:\Users\phycs\Downloads\XX-Net-3.3.1\XX-Net-3.3.1\data\x_tunnel\client.json
Sep 15 15:03:46.896 - [INFO] Use proxy:127.0.0.1:8087
Sep 15 15:03:46.897 - [INFO] Socks5 server listen:127.0.0.1:1080.
Sep 15 15:06:58.635 - [DEBUG] x-tunnel web_control 127.0.0.1:49944 POST /register
Sep 15 15:06:58.654 - [INFO] request_balance register:402946108@qq.com
Sep 15 15:07:23.655 - [WARNING] api:register fail:status:'UNKNOWN' t:25
Sep 15 15:09:01.526 - [DEBUG] x-tunnel web_control 127.0.0.1:49944 POST /register
Sep 15 15:09:01.526 - [INFO] request_balance register:402946108@qq.com
Sep 15 15:09:26.528 - [WARNING] api:register fail:status:'UNKNOWN' t:25

诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.3.6

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:5204 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​用3.5.3 以上版本

**Comment by charmsoya** [comment]
感谢辛苦付出，但是我下载了3.5.3 注册 x-tunnel 不成功，停留在 Sep 15 15:53:32.762 - [INFO] request_balance register: ****@126.com，请问x-tunnel应该在哪个网站注册？谢谢！

**Comment by phycsjay** [comment]
升级3.5.3版本后成功注册
