### ISSUE TITLE
请教如何完全卸载XX-Net？

### ISSUE THREAD

**Issue by latinisation** [XX-net/XX-Net#6476]
因为我是和Proxy SwitchyOmega搭配使用，但我现在不用代理浏览网页时（两个插件我都退出了）无法登陆微博，但是新浪网本身能登，微博非要挂上代理转到北美微博界面登录才行。。。

而且就算单独使用ss传东西到谷歌云盘，原本显示只要二十几分钟的最后显示需要两小时，然而我传了一天一夜也传不上去（如果用了xx-net的话永远上传只差1秒就完成）

我试着删除了文件夹重新安装还是不行，因此**请教如何完整的卸载xx-net**，另外如果能一道告知完全卸载Proxy SwitchyOmega插件的方法就太感谢了，现在我在user-rule.txt里面自己ss加的网址全部因为这个代理插件失效了。。。

小白在这里感激不尽！！！

**Comment by onplus** [comment]
你是问 portable软件怎么卸载？chrome插件怎么卸载？

**Comment by latinisation** [comment]
@onplus 好吧原来是DNS以前我没清理干净，谢谢！
