### ISSUE TITLE
建议ip可用数量下调到百八十个吧！gwf也用这个扫的话，一次就能封锁三千个。

### ISSUE THREAD

**Issue by hongkonghot** [XX-net/XX-Net#6490]
建议ip可用数量下调到百八十个吧！能用就行！如果gwf也用这个扫的话，一次就能封锁三千个。而且咱们这些穷屌丝，怎么扫也扫不过gwf吧！

**Comment by retmania** [comment]
你觉得你调一下就能拦住gfw了吗。。。人家不会开一万个客户端吗。。。你也太低估国家机器了

**Comment by hongkonghot** [comment]
下调成100的话，起码难度增加了30倍啊！

**Comment by tislam8888** [comment]
我这里怎么扫IP
添加IP进去
过不了几分钟
也就是剩下不到400个是有效能用的

**Comment by poplong2** [comment]
那也得他们答应你不用旧版本扫，才有效吧？ @hongkonghot

**Comment by renqy** [comment]
gfw扫的话，肯定不用这个。人家自己写个程序，同时开上几万个进程不是轻轻松松的事？

**Comment by zegzhi** [comment]
参考：https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
最大IP数是可以手动调整的，再说一个开源软件你怎么改都没用。
