### ISSUE TITLE
[X-tunnel]好像发现一个bug

### ISSUE THREAD

**Issue by Dexilc** [XX-net/XX-Net#6495]
最近IP数量急剧减少，对F&Q造成很大不便，所以上这看看，XX-NET也用了很久了，其实很早就注意到x-tunnel，但以前没必要用，所以就没尝试，看到注册送流量，所以就尝试了一下，第一次送500M,退出XX-NET，再打开又增加几百M，之后反复操作，居然到了5G，但到期时间都是第二天
![1](https://user-images.githubusercontent.com/24988478/30510245-c3db4e14-9af2-11e7-8056-7632944a567e.png)
不过没什么用，按照其他人的介绍配置好了，但还是用不了，不知什么原因

**Comment by poplong2** [comment]
测试版本，每登录一次送200M测试流量，不是Bug。
