### ISSUE TITLE
现在的版本还能用，要不要升级呢？

### ISSUE THREAD

**Issue by xiaoyan94** [XX-net/XX-Net#6499]
![image](https://user-images.githubusercontent.com/17242539/30513020-a8657e5c-9b2e-11e7-8502-b669ad0e5eb9.png)

**Comment by onplus** [comment]
备份一下，升级3.4.2

**Comment by xiaoyan94** [comment]
看到有200MB流量可用   QQ客户端不能用？
Sep 16 22:36:42.458 - [WARNING] request not supported command mode:3
Sep 16 22:36:44.036 - [WARNING] request not supported command mode:3
Sep 16 22:36:47.473 - [WARNING] request not supported command mode:3
Sep 16 22:36:49.348 - [WARNING] request not supported command mode:3
Sep 16 22:36:55.653 - [WARNING] request not supported command mode:3

**Comment by qiurongli** [comment]
已经没有版本可以用了
