### ISSUE TITLE
xx-net最近几天突然无法访问google系列网站，显示“您的连接不是私密连接”

### ISSUE THREAD

**Issue by cidss** [XX-net/XX-Net#65]
原来一直使用xx-net都正常的，但奇怪的是，从最近3-4天开始，用xx-net突然无法登录google系列网站了（比如www.google.com），而其他的海外网站都可以打开的，完全没有问题，电脑设置也没有动过，xx-net已升级到最新版了。chrome浏览器显示“您的连接不是私密连接”，“NET::ERR_CERT_AUTHORITY_INVALID”。IE浏览器显示“此网站的安全证书存在问题。”  从新导入证书也没有效果。我是win8.1 64bit

有啥办法没有？

**Comment by lyp4140** [comment]
我的访问Google网站都是正常的，就是访问推特好像有点问题，我用自己的APPID

**Comment by xxnet** [comment]
请把状态页和日志发上来分析。
同时请看看显示证书有问题时，看看浏览器的具体地址，
同时看看证书的是谁签发的。

访问Twister好像有问题，具体是什么问题？
  可以在浏览器中右键，点击Inspect element，然后点击Console看看发生了什么情况

**Comment by cidss** [comment]
根据你的提示查了一下，大概发现问题是和我用的杀毒软件Bitdefender 2015 有关，这个杀软开启SSL扫描，并用xx-net上www.google.com的情况下，证书签发机构就变成Bitdefender了而不是google，导致上不了，但上其他的ssl网站，如微软邮箱，证书同样显示由Bitdefender颁发，却都可以正常访问。

我用另一个翻墙软件（freegate），在杀软开启ssl扫描的情况下上www.google.com，证书颁发机构则是正常的，为google internet authority g2。所以，用xxnet上谷歌的话，最近暂时只能关闭杀软的ssl扫描了，不知道是bitdefender和xx-net之间兼容有问题，还是xx-net本身有bug？
辛苦了: )

**Comment by xxnet** [comment]
收到。

xxnet是直连Google的ip，中间没有篡改过证书，倒是bitdefender把通讯内容给改了。
不知道bitdefender是在哪一层改的，如果是 browser -> bitdefender -> xxnet -> Google web
server
 那么就不管xxnet的事情，有可能是bitdefender和浏览器之间的问题。
 我怀疑是这样：
 browser -> bitdefender -> xxnet ->btidefender-> Google web server
 这样会导致bitdefender介入两次，中间出现什么状况也会超出bitdefender的假设，导致出问题。

只是猜想，有空可以研究看看。

在 2015年3月22日 上午4:12，cidss <notifications@github.com>写道：

**Comment by cidss** [comment]
更新最新版本1.6后，杀软开启ssl扫描情况下google系列网站均可正常访问了，看来问题基本解决，作者太厉害了: )
