### ISSUE TITLE
没有ip的试试重新拨号重启光猫换个ip吧

### ISSUE THREAD

**Issue by wialny** [XX-net/XX-Net#6515]
今天我这里也出现没有可用ip的情况, 试了很多方法都无效.
还好我留意了下我自己上网的ip, 发现和平时的不一样. 
重新拨号后XX-Net恢复了正常.
之前无ip可用时, 我自己的ip是58.48开头的, 现在可以的则是59.172开头
感觉墙已经有足够的能力封锁基于google ip的梯子了啊, 只是现在还没有应用到所有路由上而已

**Comment by xxnet** [comment]
​这样看来，墙是有一定的判别能力，识别出来XX-Net的行为了。
也许调小ip扫描的线程，会有一定的帮助。

如果增加访问其他国内网站的流量，不知道有没有帮助？

**Comment by if2012** [comment]
没有光猫的怎么办？

**Comment by xxnet** [comment]
没有光猫的，​停掉xx-net 几个小时，再试试看看

**Comment by kitkw** [comment]
@wialny 我这怎样换都是121.13开头的，之前是100.64的内网。应该不行吧…………。不过庆幸是出问题后一直还有5个基本不会掉的IP可用。

**Comment by 2579019321** [comment]
不行

**Comment by wialny** [comment]
看来每个地区的情况都不同啊
