### ISSUE TITLE
最近国网不知道咋了,西安电信,转投X-Tunnel,来帮帮我

### ISSUE THREAD

**Issue by DongpoAlex** [XX-net/XX-Net#6529]
X-Tunnel账号:billbob.dong@gmail.com
有没有好心的人转赠点流量.

最近IP咋了,一个IP都搜不到

**Comment by tamada007** [comment]
热烈迎接档的19大，上海电信，IP全挂。

**Comment by IrisZhang** [comment]
转了100M，想问下这个流量从哪里来的，第一次注册登陆就有一些到9月20号就过期的流量，用完了就只能购买吗？

**Comment by DongpoAlex** [comment]
@IrisZhang 是的额
