### ISSUE TITLE
3.4.2 扫描不到IP，回滚到3.2.9后IP数量一下子上去了

### ISSUE THREAD

**Issue by swim2sun** [XX-net/XX-Net#6530]
最近IP数量不断减少，基本上扫不到新IP，看到 #6516 提到IP数量上涨而我的却还是0，感觉有点不对劲。于是回滚到了3.2.9，IP数量立马上去了，现在已经200多了，数量还在上升。

因此，我怀疑最新的稳定版扫描新IP的功能可能有问题。建议扫不到IP的可以回滚下版本试试。

回滚方法：

1. 将xx-net设置为不更新
2. 打开`code`文件夹，里面有你当前所有用过的版本
3. 修改`version.txt`,将里面的版本号改为你要回滚的版本号
4. 重启xx-net

**Comment by simear2004** [comment]
没用，全部封死了

**Comment by OuyangIPC** [comment]
不啊，我在公司（电信网）用XX-net就能扫到1000左右的IP，但是家里面（电信网）用XX-net只能扫到个位数的ip，网速比较慢，另外我在家里的虚拟机里面用XX-Mini也能扫除200多的ip只是网速很让人捉急

**Comment by swim2sun** [comment]
还是不稳定.. 暂时转投lantern了 : (
