### ISSUE TITLE
来来回回切换XXNET版本后，出问题HTTPS提示不是私密连接.所有HTTPS都上不去…………（已解决）

### ISSUE THREAD

**Issue by kitkw** [XX-net/XX-Net#6532]
不断切换XXNET版本，之前因为不知道可以直接改目录下的code，都是删前一版本再贴旧版或新版。不知怎样搞的现在一些facebook  google. youtube都上不去,提示不是私密连接隐私设置错误。百度了一下都找不到能解决的方法，很多方法不起作用。  在此求救

**Comment by xxnet** [comment]
​浏览器里删除证书，手动重新倒入证书，重启浏览器。

**Comment by yaowangs** [comment]
大概跟我一样，用的nod32吧。。。把nod32里关于ssl的关了

**Comment by kitkw** [comment]
@yaowangs 对这个如何操作

**Comment by kitkw** [comment]
@xxnet 这方法不行……。

**Comment by kitkw** [comment]
@yaowangs 在网上找到关了方法，在高级设置里关闭 ssl/tls通讯过滤。但还是不是私密连接。@xxnet 也不行…………

**Comment by onplus** [comment]
win + R 
certmgr.msc
删除全部证书
https://www.zhiin.net/zhong-zhi-windows-zheng-shu-lie-biao/

**Comment by kitkw** [comment]
@onplus 删除全部？？还是只删除XXNET..

**Comment by onplus** [comment]
删除goagent签发的所有证书。
你用的火狐吗？

**Comment by kitkw** [comment]
chrome  已经删除了有关  goagent全部证书  再导入  还是提示不是私密连接

**Comment by kitkw** [comment]
@onplus  chrome 已经删除了有关 goagent全部证书 再导入 还是提示不是私密连接

**Comment by onplus** [comment]
win7 还是10？

把所有的goa相关证书删除，电脑里所有XX-Net文件夹删除（只保留data\gae_proxy\good_ip.txt）。
下载最新3.5.5，管理员运行start.bat

**Comment by kitkw** [comment]
@onplus  win7   好的试试看

**Comment by kitkw** [comment]
@onplus 可以了  谢谢

**Comment by kitkw** [comment]
@onplus 不过这个3.5.5 还是没法扫到IP...

**Comment by hczcyy** [comment]
请问楼主是怎么解决的？
我把证书删除了，然后再导入，还是不行啊

**Comment by pendave** [comment]
我的火狐浏览器最近更新了，这几天出现了推特这样的站打不开，报错说证书Error。

刚才参考了各路帖子操作成功了！
01_火狐浏览器先清除失效的GoAgent XX-Net证书
![01_ goagent xx-net](https://user-images.githubusercontent.com/1331881/31976684-7933bf80-b96b-11e7-9a63-8382a118a5bb.gif)

02_清除系统里旧的GoAgent XX-Net证书并重启XX-net会自动生成新的证书
![02_ goagent xx-net xx-net](https://user-images.githubusercontent.com/1331881/31976685-7cb3f148-b96b-11e7-9216-89d030719873.gif)

03_火狐浏览器再导入更新的GoAgent XX-Net证书
![03_ goagent xx-net](https://user-images.githubusercontent.com/1331881/31976696-8b84b77a-b96b-11e7-8add-8d8da94f8a15.gif)
