### ISSUE TITLE
请问 X 大，Xx-net 还会继续维护并更新吗！

### ISSUE THREAD

**Issue by ZhangLanqiu** [XX-net/XX-Net#6536]
非常感谢 X 大，写出这么棒的软件可以让我们0门槛科学上网，本人用 Xx-net 一年多了已经成为习惯了，最近突然 IP 猛掉，至此已经完全无法 FQ ，但还是每天都会习惯性的打开 Xnet ，虽然 IP 一直为0......，也不是没有别的方式FQ，但还是喜欢用 Xnet 毕竟习惯了,  习惯每天看看IP数量，习惯每天看看延迟，所以想问问 X 大，对 Xnet 的态度，还会继续坚持下去吗？ 
 无论回复与否我都由衷的感谢 X 大，让我免费畅游Q外一年多，谢谢！

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/commits/master

**Comment by ZhangLanqiu** [comment]
@onplus  你现在有IP吗？ 我这边好像彻底死了。。。。 扫一天了都

**Comment by xxnet** [comment]
​新方案已经出来，请用3.5.4版，x-tunnel模块

**Comment by jzp820927** [comment]
我猜测 LZ 想问的应该是，是否会继续维护 GAE。
