### ISSUE TITLE
一直扫描ip，怎么解决

### ISSUE THREAD

**Issue by SamoZ** [XX-net/XX-Net#6556]
![tim 20170919105700](https://user-images.githubusercontent.com/25240164/30574102-64265f74-9d2a-11e7-8c5c-ccb61e0ffd52.png)

**Comment by Christian-L** [comment]
跟你一样，，，难受，，，想哭

**Comment by SamoZ** [comment]
@Christian-L 今天刚出现的，这是咋了啊，无奈啊

**Comment by xxnet** [comment]
​下载3.5.5，用x-tunnel

**Comment by sliming** [comment]
启用ipv6

**Comment by Christian-L** [comment]
x-tunnel不是要收费吗，意思以后都要收费使用了吗

**Comment by Christian-L** [comment]
@xxnet 用了x-tunnel确实好了！感谢！

**Comment by xxnet** [comment]
也许这一波过去，​GAE就会恢复可用了
GAE也在改进中，效果还要看各地情况。

x-tunnel需要买服务器流量，所以是要收费的，目前是测试阶段，登陆会送流量。

**Comment by SamoZ** [comment]
@xxnet 大佬，你给份使用说明吧。。。。我是新手，才用没多久，谢谢大佬

**Comment by SamoZ** [comment]
@Christian-L 下载之后，直接就用吗？

**Comment by Christian-L** [comment]
@SamoZ 有wiki的啊，看wiki就行了

**Comment by SamoZ** [comment]
@Christian-L 给我个链接，我刚玩没多久，麻烦啦

**Comment by Christian-L** [comment]
@SamoZ 。。。https://github.com/XX-net/XX-Net/wiki

**Comment by SamoZ** [comment]
@Christian-L  之前的旧版本需要删除吗？

**Comment by IrisZhang** [comment]
设置了x-tunnel，没啥改变啊，还是在扫描IP。。。

**Comment by SamoZ** [comment]
@Christian-L 能加个联系方式么，还是不行啊

**Comment by SamoZ** [comment]
![image](https://user-images.githubusercontent.com/25240164/30577314-ff6a884c-9d3f-11e7-9577-7a5a3d8cfa2a.png)
很无奈，但是也没办法了，放弃了

**Comment by MadMaxPayne8964** [comment]
联通，从昨晚开始IP数爆炸了。由前几天的个位数暴增到五六千，50个线程一分钟能扫出二十多个，延迟都很低。

**Comment by sofaonsale** [comment]
@MadMaxPayne8964 还是要分地方。帝都封锁最严重

**Comment by if2012** [comment]
确实这段时间都是“请等待大约半小时，XX-Net需要扫描IP。”，不知怎么回事？

**Comment by xuehaiming** [comment]
等下个月19大开完就好了

**Comment by potterhere** [comment]
一个可用的IP都没有
