### ISSUE TITLE
升级3.4.2+ 后， 使用带密码的 XX-NET 会报 Wrong password('')

### ISSUE THREAD

**Issue by glasslion** [XX-net/XX-Net#6574]
报错页面信息:
---
```
Wrong password('')

GoAgent proxy.ini password is wrong!
```

---
## 问题内容
之前一直使用正常, 近期没有升级过XX-NET服务端， 也没有改过配置。 密码是设置在 `data\gae_proxy\manual.ini`。

查看 `\code` 目录， 发现刚升级到  3.4.2 这个版本。 将 3.4.2 目录删除， 重启 XX-NET 恢复正常。

同样的问题在两台不同的电脑上都出现了

**Comment by onplus** [comment]
代码修改了两个配置文件的优先级。
现在config > manual
删除config.ini中相关配置字段，或者把manual里的移到config

**Comment by glasslion** [comment]
@onplus 确认是这个原因。但 config > manual 这样感觉很怪啊

**Comment by xxnet** [comment]
​修改的原因是：
 在manual设置了的参数，WebUI上无法更改，变得奇怪。
