### ISSUE TITLE
近期XX-net GAE 问题报告

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#6586]
X-TUNNEL目前可以用，但GAE

日志：Sep 20 10:06:05.779 - [WARNING] no enough ip。
状态：请等待大约半小时，XX-Net需要扫描IP。
目前xx-net GAE链接方法无法使用。

从9月16日以后（天津联通）xxnet的GAE功能就开始出现停断现象，基本是无法连接成功，也不能正常上传APPID。之前试过3000个IP没有一个能正常使用。说明此次XX-net断网问题比较严重。最新版的3.5.6可以使用。

因为个人对于网络技术比较浅薄，所以只提一些建议或思路：

1、GAE增加伪装与隐蔽功能，再增加一种类似于分身术的理念。确保让GAE自身安全。
2、另外就是对用户进行清点，特别对于那些有特务性质的用户，要看管好他们，以免对X-TUNNEL造成损害。
3、最后是，启动多款全新翻墙软件研发与开发，以备在未来作为后备力量储备资源，就像X47B无人隐身飞行器随时执行特殊任务。

**Comment by xxnet** [comment]
​GAE 已经有改进方案，在进行中，暂时可以降低扫描线程，减少被探测到的概率。

X-Tunnel 被滥用，比如攻击google服务，会导致google 把ip列为异常，每次登陆要判断是否机器人。
  目前已经发生了。

目前x-tunnel的抗封锁能力可以放心使用，遇到问题再想办法。

**Comment by matrixirtam** [comment]
感觉 谷歌提示异常流量 是谷歌怀疑攻击 而主动屏蔽的 可能不一定和gae有关 也不一定肯定攻击导致 可能过多连接造成谷歌防火墙机制？ 实际中发现本地ip更换后 会有好转 浅见仅供参考。。。。

**Comment by 80068** [comment]
@xxnet 太好了，总的来说XX-net的 GAE 和 X-Tunnel都有很高优势，而且广受大家喜爱与欢迎。因为有了XX-net很多人才能看到和使用谷歌，XX-net是热爱互联网用户的重要基石。没有XX-net我们就没法上网。

**Comment by xxnet** [comment]
​谢谢支持，正在编译 Android版本，希望更多人能够方便访问网络

**Comment by yabaoer** [comment]
现在扫不到ip的，可以考虑通过ipv6的方式使用xxnet，还是很给力的，
![image](https://user-images.githubusercontent.com/9652060/30633183-5973f106-9e1d-11e7-8dc4-1c1ebcea8b58.png)
下面是2个ipv4获取v6的方式，亲测有效
![image](https://user-images.githubusercontent.com/9652060/30633280-a48d7ec8-9e1d-11e7-9c94-43ac615095c2.png)

win7 启用teredo的方法
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1580771

centos添加ipv6隧道
http://coolnull.com/4476.html

2个方式我在win7和centos6.5都测试ok了，均可开启ipv6

**Comment by vvvyyy** [comment]
@xxnet 大大能开发IOS版的么 _(:з」∠)_

**Comment by onplus** [comment]
国区不是禁止VPN类软件吗 @vvvyyy

**Comment by xxnet** [comment]
​IOS可以不经过市场安装app，不过需要手动，稍微麻烦一点。

可以考虑做一个IOS版本的。
暂时也就是把xx-net搬到IOS上运行，没有做其他适配。

**Comment by vvvyyy** [comment]
@xxnet 做吧，谢谢大大ヽ(￣▽￣)ﾉ

**Comment by DyingLight100** [comment]
应该是九月份开始ISP又加大了封锁力度，同为天津联通，发现平时最常见的IP段(111.165.*.*)已经封锁，只要是这个IP段，GAE基本没法用。今天开关光纤猫N次，始终是这个IP段。。。
