### ISSUE TITLE
火狐57X-tunnel用不了

### ISSUE THREAD

**Issue by dagerdager** [XX-net/XX-Net#6588]
插件用switchyomega，不知道是tunnel识别不了火狐版Omega，还是Omega识别不了tunnel？
并不是设置问题，火狐51我用foxyproxy使用tunnel没有问题。

**Comment by onplus** [comment]
两天更新一次的nightly吗。。。

https://github.com/FelisCatus/SwitchyOmega/issues/1171

**Comment by dagerdager** [comment]
也就是说57还没支持socks5

**Comment by onplus** [comment]
https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.5.4

**Comment by dagerdager** [comment]
@onplus 看到了 多谢
