### ISSUE TITLE
Mac 导入证书的方法

### ISSUE THREAD

**Issue by superjyq** [XX-net/XX-Net#66]
1 原来是1.2.1，mac系统，浏览器是chrome，证书正常，访问youtube也正常

2 更新到1.3.5, 访问youtube就显示不能访问了

3 只能退回到1.2.1，一切正常，希望解决

4 看youtube，速度一般，不如goagent原版，不过mac下goagent始终不稳定，这软件至少稳定性不错

**Comment by lifeva** [comment]
证书问题，可自行解决，到钥匙串中自己配置一下吧。

**Comment by superjyq** [comment]
已经导入新版本的证书了，无效

这不是用户能解决的，这是软件本身的bug

**Comment by xxnet** [comment]
2， 访问youtube就显示不能访问了 
  浏览器显示什么？ 证书问题还是什么？
  看看GoAgent日志，有没有报什么错误

另外请把状态页也贴上来

**Comment by superjyq** [comment]
1 显示您的连接不是私密连接

Mar 17 21:38:39 - [INFO] FWD CONNECT clients4.google.com:443 
Mar 17 21:38:39 - [DEBUG] get ip:64.233.189.166 t:84
Mar 17 21:38:39 - [DEBUG] tcp conn 64.233.189.166 time:93
Mar 17 21:38:40 - [INFO] GAE CONNECT www.youtube.com:443 
Mar 17 21:38:40 - [INFO] FWD CONNECT www.gstatic.com:443 
Mar 17 21:38:40 - [DEBUG] get ip:64.233.189.98 t:86
Mar 17 21:38:40 - [DEBUG] tcp conn 64.233.189.98 time:93
Mar 17 21:38:42 - [INFO] FWD CONNECT xxnet-update.appspot.com:443 
Mar 17 21:38:42 - [DEBUG] get ip:216.58.221.217 t:89
Mar 17 21:38:42 - [DEBUG] tcp conn 216.58.221.217 time:93
Mar 17 21:38:44 - [DEBUG] forward remote disconnected.
Mar 17 21:38:44 - [DEBUG] FWD CONNECT xxnet-update.appspot.com:443 with closed
Mar 17 21:39:38 - [DEBUG] FWD CONNECT www.gstatic.com:443 with closed
Mar 17 21:39:40 - [INFO] FWD CONNECT accounts.google.com:443 
Mar 17 21:39:40 - [DEBUG] sort ip time:3
Mar 17 21:39:40 - [DEBUG] get ip:216.58.221.153 t:94
Mar 17 21:39:40 - [DEBUG] tcp conn 216.58.221.153 time:98

**Comment by xxnet** [comment]
从日志看，你是直连google的ip的，goAgent只是找到Google，建立连接后就给浏览器了。
不会篡改连接。
 
你看看证书是谁发的，难道有中间人攻击？

**Comment by lifeva** [comment]
钥匙串中删除老证书----导入新证书-----查看证书显示简介----修改信任为始终信任（原状态为未设置）----问题解决。

**Comment by shawwokou123** [comment]
是你自己导入证书时有问题。
更新证书时，要将元证书删除，然后再导入新证书。导入后，选择为『始终信任』即可。

**Comment by xxnet** [comment]
已经实现Mac自动导入证书

**Comment by litanwei** [comment]
为啥证书也是导入成功了，还是报不信任错误？

**Comment by litanwei** [comment]
也全部设置始终信任

**Comment by jzp820927** [comment]
#5322
