### ISSUE TITLE
使用x-tunnel连接dropbox macos客户端的问题

### ISSUE THREAD

**Issue by saintethan** [XX-net/XX-Net#6610]
## 问题内容
使用x-tunnel，端口已配置好，dropbox客户端一直显示连接中。该如何解决？

#### 诊断信息
XX-Net Status:

sys-platform: x86_64, Darwin-16.7.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
os-release: 16.7.0
os-detail: Release:10.12.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
xxnet-version: 3.6.0

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:1227
network-status: OK
connected-link: new:9 used:0
worker: h1:5 h2:3
scan-ip-thread-num: 1
ip-quality: 457
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 日志
Sep 21 12:58:11.281 - [INFO] socks5 ('127.0.0.1', 60014) connect to photos-thumb.dropbox.com:443 conn_id:160
Sep 21 12:58:11.282 - [DEBUG] Conn session:snvvtgrz conn:160 stop:recv fail.
Sep 21 12:58:11.282 - [DEBUG] remove conn_id:160
Sep 21 12:58:11.313 - [INFO] socks5 ('127.0.0.1', 60015) connect to photos-thumb.dropbox.com:443 conn_id:161
Sep 21 12:58:11.314 - [DEBUG] Conn session:snvvtgrz conn:161 stop:recv fail.
Sep 21 12:58:11.315 - [DEBUG] remove conn_id:161
Sep 21 12:58:11.342 - [INFO] socks5 ('127.0.0.1', 60016) connect to photos-thumb.dropbox.com:443 conn_id:162
Sep 21 12:58:11.343 - [DEBUG] Conn session:snvvtgrz conn:162 stop:recv fail.
Sep 21 12:58:11.344 - [DEBUG] remove conn_id:162

**Comment by xxnet** [comment]
​日志上看，好像是dropbox 客户端自己断开连接，而且是连上就断开，没有发现其他异常。
dropbox 有没有日志？

**Comment by saintethan** [comment]
谢谢x大回复。刚才迷之成功了，用x-tunnel的端口设置，但是要把sock5改为http。供后来人参考。
