### ISSUE TITLE
x-tunnel上午使用了一下，晚上使用就无法使用了

### ISSUE THREAD

**Issue by XYCFY** [XX-net/XX-Net#6615]
使用的是3.6.0，
日志是这样的：Sep 21 18:46:43.273 - [DEBUG] session not running, try login..
Sep 21 18:46:43.511 - [WARNING] api:/login fail:auth fail
Sep 21 18:46:43.511 - [WARNING] x-tunnel request_balance fail when create_conn:auth fail
Sep 21 18:46:43.511 - [WARNING] Socks4 connect fail, no conn_id
Sep 21 18:46:43.814 - [DEBUG] session not running, try login..
Sep 21 18:46:44.058 - [WARNING] api:/login fail:auth fail
Sep 21 18:46:44.058 - [WARNING] x-tunnel request_balance fail when create_conn:auth fail
Sep 21 18:46:44.058 - [WARNING] create conn fail

**Comment by Zmm1977** [comment]
登录失败了，估计是服务器的问题

**Comment by xxnet** [comment]
​服务器在维护，请再试一试

**Comment by adamslam** [comment]
深圳中国电信用不了。

**Comment by lh471921250** [comment]
我这边也是每天早上可以用，从傍晚以后就断断续续不能用，第二天又恢复，这是什么情况

**Comment by xxnet** [comment]
​不能用的，请贴出 x-tunnel 的日志和cloudflare font log

**Comment by XYCFY** [comment]
今天早上又可以用了，好吧，看来只能上午用了
