### ISSUE TITLE
封锁又加强了

### ISSUE THREAD

**Issue by zanewayne78** [XX-net/XX-Net#6616]
ip在狂掉，刚从6000两小时掉到2000多，不知道这段风暴什么时候过去

**Comment by zanewayne78** [comment]
现在只有1000多了

**Comment by xxnet** [comment]
​你是什么版本？
最新3.6.x 有改进，扫描线程降低到5，可以解决问题。
不过新的版本，有5个ip就足够流畅翻墙了
