### ISSUE TITLE
请求帮助！

### ISSUE THREAD

**Issue by mingshse** [XX-net/XX-Net#6622]
我在2.8.9的基础上正在制作稳定版，请问2.8.9怎么支持tls1.2，我看2.8.9支持的tls只有1.0！谢谢！
@xxnet @xyuanmu @Cat7373 @yeahwu @SeaHOH

**Comment by xxnet** [comment]
​你试试替换 openssl_wrap.py
其他的包括升级OpenSSL crpytograph 库

**Comment by mingshse** [comment]
@xxnet 能不能简单修改一下能在2.7.9的基础上支持tls1.2

**Comment by xxnet** [comment]
​为什么是 2.7.9?
最新版有什么问题吗?

**Comment by mingshse** [comment]
我在2.8.9的基础上正在制作稳定版，因为我觉得xxnet2.8.9最好用，不想用http2，
我想问的是能不能简单修改一下能在xxnet 2.8.9的基础上支持tls1.2？

**Comment by xxnet** [comment]
​应该就是升级OpenSSL库和相关的open_wrap.py 就好了。
 http2 其实有很大的好处，只要1个支持http2的ip，就可以获得可以接受的体验。
之前的版本是做不到的。

**Comment by mingshse** [comment]
好的谢谢，我试试3.6.1
