### ISSUE TITLE
2.0.4 PHP模式提示您的连接不是私密连接

### ISSUE THREAD

**Issue by ych5318** [XX-net/XX-Net#663]
浏览器chrome43
gae模式没有证书问题
php模式肯定配置成功了 google twitter出现您的连接不是私密连接的问题哦
浏览某些需要翻墙的网站没有问题
配置应该是对的
而且证书都是已经导入了的
这个问题怎么解决呢
搜了很多帖子好像没有此类啊

**Comment by xxnet** [comment]
php模块的证书和gae的证书的分开的，有可能导入没有成功，你手动导入data/php_proxy/CA.crt证书到浏览器里试试

在 2015年7月18日 下午11:40，ych5318 <notifications@github.com>写道：

**Comment by ych5318** [comment]
感谢 已经解决了
