### ISSUE TITLE
两三个小时依然连不上：您正在使用公共APPID，因为资源有限，使用上存在限制，建议部署私有APPID。

### ISSUE THREAD

**Issue by zehuali90529** [XX-net/XX-Net#6632]
您正在使用公共APPID，因为资源有限，使用上存在限制，建议部署私有APPID。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36
xxnet-version: 3.6.1

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2 good:2
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:2
scan-ip-thread-num: 1
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xxnet** [comment]
看状态是可以用的了
还有问题，请发GAE的日志

2017-09-22 20:41 GMT+08:00 zehuali90529 <notifications@github.com>:

**Comment by roc1010kmt** [comment]
自己註冊id，不過你這ip太少了。

**Comment by zehuali90529** [comment]
我在部署过程中出现了Localhost:8080
请问是什么问题啊

**Comment by zehuali90529** [comment]
可以访问GOOGLE,确认授权的时候弹出：localhost拒绝了我们的连接请求，请搜索localhost 8080
ERR_CONNECTION_REFUSED

**Comment by onplus** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=deploy

贴日志
