### ISSUE TITLE
升级3.6.1 显示尚未建立连接 浏览器代理和CA证书都是fail 想知道该怎么办

### ISSUE THREAD

**Issue by Ewoodhouse** [XX-net/XX-Net#6653]
XX-Net Status:

sys-platform: x86_64, Darwin-15.6.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64
os-release: 15.6.0
os-detail: Release:10.11.6; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.6.1

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:12297 good:11967
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by xxnet** [comment]
​把 ip 全部删除掉，重新扫

**Comment by liangliangge521** [comment]
我也是这个显示，但翻墙正常，什么也不影响，

**Comment by Ewoodhouse** [comment]
重新下载安装了仍然这样 但不影响使用 真是专治强迫症 谢谢啦

**Comment by liumahao** [comment]
同样有这个问题
