### ISSUE TITLE
google.com和google scholar无法登陆

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#667]
使用最新稳定版2.0.2和最新测试版2.0.4，都无法登陆google.com和google scholar，但可以登陆google.com.hk。google scholar 太重要了，拜托一定在新版本中解决。万分万分感谢！

**Comment by cdmask** [comment]
我用2.0.2可以登录scholar啊

**Comment by xxnet** [comment]
我这边可以登录google 和 scholar，你把状态和日志贴上来

在 2015年7月19日 上午10:43，farshidvahid <notifications@github.com>写道：

**Comment by farshidvahid** [comment]
状态页：
GAEProxy状态信息

系统版本

Property	Value
XX-Net Version	2.0.2
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	142
100th IP handshake(ms)	1373
connected link(帮助)	8,1
scaning ip thread num	50
block stat(帮助)	OK
Appid

Property	Value

**Comment by farshidvahid** [comment]
日志页：
Jul 19 17:27:07 - [INFO] scan_ip add ip:59.18.34.183 time:274
Jul 19 17:27:12 - [INFO] GAE CONNECT 119.255.133.63:443
Jul 19 17:27:12 - [INFO] ssl error: [Errno 1] _ssl.c:507: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol, create full domain cert for host:119.255.133.63
Jul 19 17:27:12 - [INFO] GAE CONNECT 119.255.133.63:443
Jul 19 17:27:12 - [INFO] ssl error: [Errno 1] _ssl.c:507: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol, create full domain cert for host:119.255.133.63
Jul 19 17:27:19 - [INFO] GAE CONNECT clients1.google.com:443
Jul 19 17:27:19 - [DEBUG] GAE CONNECT POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Jul 19 17:27:19 - [INFO] DIRECT chucked t:230 s:68 200 clients1.google.com /tbproxy/af/query?client=Google%20Chrome
Jul 19 17:27:20 - [DEBUG] get ip:1.9.24.58 t:108
Jul 19 17:27:20 - [DEBUG] create_ssl update ip:1.9.24.58 time:102
Jul 19 17:27:21 - [INFO] GAE CONNECT 119.255.133.30:443
Jul 19 17:27:21 - [INFO] ssl error: [Errno 1] _ssl.c:507: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol, create full domain cert for host:119.255.133.30
Jul 19 17:27:22 - [INFO] scan_ip add ip:106.162.199.46 time:148
Jul 19 17:27:23 - [INFO] GAE CONNECT www.google.com:443
Jul 19 17:27:24 - [INFO] GAE CONNECT 119.255.133.63:443
Jul 19 17:27:24 - [INFO] ssl error: [Errno 1] _ssl.c:507: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol, create full domain cert for host:119.255.133.63
Jul 19 17:27:27 - [INFO] GAE CONNECT clients4.google.com:443
Jul 19 17:27:27 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/experimentstatus
Jul 19 17:27:27 - [INFO] DIRECT t:116 s:6 200 clients4.google.com /chrome-sync/experimentstatus
Jul 19 17:27:27 - [DEBUG] get ip:106.162.200.154 t:127
Jul 19 17:27:27 - [DEBUG] create_ssl update ip:106.162.200.154 time:125

**Comment by farshidvahid** [comment]
另外请教，小托盘里总是出现中文乱码和电脑发出警报的嘟嘟声（见issue #673）是怎么回事呢？

**Comment by xxnet** [comment]
日志里只有一行
Jul 19 17:27:23 - [INFO] GAE CONNECT www.google.com:443

看不出问题

**Comment by xxnet** [comment]
请用start.vbs启动

在 2015年7月19日 下午5:29，farshidvahid <notifications@github.com>写道：
