### ISSUE TITLE
请检查浏览器代理设置。公司电脑没事。家里的笔记本之前也还能用 最近发现不行了  浏览器重装  XX重装也不行了

### ISSUE THREAD

**Issue by songyazhao** [XX-net/XX-Net#6671]
*2017年9月26日 22:03:43 补充(**已解决**):*
将证书从新删除导入了一遍  然后重点来了 右键Chrome.exe属性, 兼容性那里勾上 **以管理员身份运行此程序** 然后重新打开浏览器, 好了

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.6.1

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3 good:3
network-status: OK
connected-link: new:0 used:0
worker: h1:1 h2:2
scan-ip-thread-num: 5
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by odrip** [comment]
反正我家移动网络的  死活登录不上了

**Comment by xxnet** [comment]
​@songyazhao
  你的状态看，连接是成功了，是不是浏览器设置问题？

@odrip
  把状态页贴出来

**Comment by Cathrine-Jiang** [comment]
我有一样的问题

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
xxnet-version: 3.6.1

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12545 good:472
network-status: OK
connected-link: new:0 used:0
worker: h1:9 h2:0
scan-ip-thread-num: 0
ip-quality: 437
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

也是proxy和ca有问题，显示为fail

**Comment by songyazhao** [comment]
@xxnet 
谷歌(https://www.google.com.hk)是能上去的, 但是会出现不受信任的连接, 于是证书删除从新导入了一遍, 问题依旧

**Comment by xxnet** [comment]
​看看证书是谁发布的，Firefox 可以看到详情
