### ISSUE TITLE
下载页面无法下载安卓版

### ISSUE THREAD

**Issue by ylwszb** [XX-net/XX-Net#6673]
下载页面，https://github.com/XX-net/XX-Net/blob/master/code/default/download.md
无法下载3.6.2安卓版APP，点击链接后会跳转到一个404页面，还望修复。

**Comment by onplus** [comment]
https://github.com/XX-net/xxnet-android/releases/download/3.6.3/XX-Net-3.6.3-debug.apk

**Comment by xxnet** [comment]
​好了

**Comment by chkjc10** [comment]
新版安卓可以直接覆盖升级吗

**Comment by xxnet** [comment]
​可以

**Comment by liyibo123** [comment]
没好，还是下载不了

**Comment by liyibo123** [comment]
@xxnet 没好，还是下载不了

**Comment by liyibo123** [comment]
@xxnet 直连无法下载，估计是被屏蔽了，翻墙才能下载

**Comment by liyibo123** [comment]
@xxnet 直连无法下载，估计是被屏蔽了，翻墙才能下载

**Comment by liyibo123** [comment]
@xxnet 直连无法下载，估计是被屏蔽了，翻墙才能下载
