### ISSUE TITLE
请问x-tunnel的流量会自动增加么？

### ISSUE THREAD

**Issue by xyoungleo** [XX-net/XX-Net#6686]
这段时间比较少翻墙，更没有用过x-tunnel，可流量增到3.85GB了，十多个9月26日到期的200MB流量，是墙友们捐出来的么？
看了x-tunnel的使用教程，里面没有提到流量会自动增加这一点啊！

**Comment by andytree** [comment]
每次登陆都会送200M，对此，感谢这个团队的大公无私！

**Comment by xyoungleo** [comment]
这样啊，感谢xx-net团队！
