### ISSUE TITLE
使用X-TUNNEL访问谷歌学术，不能访问成功并提示

### ISSUE THREAD

**Issue by andytree** [XX-net/XX-Net#6693]
版本是3.6.3，Windows10

---
## 问题内容
![image](https://user-images.githubusercontent.com/4092785/30848855-fdb40a80-a2d2-11e7-9eb9-b7b77c22b58e.png)

We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.

**Comment by xxnet** [comment]
看google 解释，是有人用x-tunnel 爬google的服务器，被封了。
不知道怎么处理。。。

换ip不是办法，https加密通讯，不知道是谁在攻击。

也许可以建立VIP机制，需要的我单独给你一个ip，保证不会有别人用。

**Comment by andytree** [comment]
谢谢了！使用GAEproxy就可以正常访问了。
原因应该是如你所说，我X-TUUNEL账号用的这台服务器，估计有其他人在用爬虫之类的程序。
