### ISSUE TITLE
macOS High Sierra 更新后xx-net图标不在工具栏，尝试很多次未果，可以正常登陆google

### ISSUE THREAD

**Issue by senbaikang** [XX-net/XX-Net#6698]
但是safari的youtube可以正常使用啦！

**Comment by stlinex** [comment]
是吗，我这里的safari打youtube还是乱码。

试一试这个？
http://127.0.0.1:8085/?module=launcher&menu=config
![2017-09-27 9 27 19](https://user-images.githubusercontent.com/32297746/30891468-269246e0-a366-11e7-848f-8836582e6679.png)

**Comment by saintethan** [comment]
@stlinex 感谢帮助，但我尝试过这个方法但是不好使。另外我使用的是3.6.3版本，可以用safari登陆youtube。

**Comment by saintethan** [comment]
@xxnet 求助x大

**Comment by bigboy1988** [comment]
macbook air  更新系统 macos high sierra 后  safari解决youtube乱码问题   （xx-net 3.6.1)

**Comment by xxnet** [comment]
​safari 看youtube 乱码，请换用Chrome浏览器
问题在于 br压缩算法，safari没有支持，而GAE服务端默认才用了。
解决方案是，GAE_proxy客户端智能解码。

**Comment by boiio** [comment]
同样是这个问题，在mac下尝试打开ipv6后状态栏图标就消失了，关闭ipv6、重新下个xxnet都解决不了问题。

**Comment by saintethan** [comment]
重装系统后解决。
