### ISSUE TITLE
xxnet1.3.6无法上传个人ID

### ISSUE THREAD

**Issue by shawwokou123** [XX-net/XX-Net#67]
出以下错误提示，请看看怎么办：
Application: shdgsj123
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>

Retry again.

**Comment by shawwokou123** [comment]
补充上边的错误日志：
Application: shdgsj123
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>

**Comment by shawwokou123** [comment]
系统为Mac10.10.1

**Comment by xxnet** [comment]
收到反馈，我看看

**Comment by shawwokou123** [comment]
谢谢，比较着急，无法上传ID

原始邮件
发件人:xxnetnotifications@github.com
收件人:XX-net/XX-NetXX-Net@noreply.github.com
抄送:shawwokou123shawokou123@gmail.com
发送时间:2015年3月18日(周三) 16:24
主题:Re: [XX-Net] xxnet1.3.6无法上传个人ID (#67)


收到反馈，我看看

**Comment by xxnet** [comment]
如果着急，可以找个Windows机器部署appid。
如果Mac里装虚拟机也可以跑windows。

找个朋友帮你部署也可以。
用公共的appid也可以.
如果要看youtube: 非xxnet开头的appid，不限制youtube.

**Comment by shawwokou123** [comment]
OK
谢谢




原始邮件
发件人:xxnetnotifications@github.com
收件人:XX-net/XX-NetXX-Net@noreply.github.com
抄送:shawwokou123shawokou123@gmail.com
发送时间:2015年3月18日(周三) 16:40
主题:Re: [XX-Net] xxnet1.3.6无法上传个人ID (#67)


如果着急，可以找个Windows机器部署appid。
 如果Mac里装虚拟机也可以跑windows。
找个朋友帮你部署也可以。
 用公共的appid也可以.
 如果要看youtube: 非xxnet开头的appid，不限制youtube.

**Comment by shawwokou123** [comment]
不过为什么MAC系统，一直无法正常部署自身的ID呢


盼望解决此问题！
原始邮件
发件人:shawokou123shawokou123@gmail.com
收件人:XX-net/XX-NetXX-Net@noreply.github.com; XX-net/XX-Netreply@reply.github.com
发送时间:2015年3月18日(周三) 16:41
主题:Re: [XX-Net] xxnet1.3.6无法上传个人ID (#67)


OK
谢谢




原始邮件
发件人:xxnetnotifications@github.com
收件人:XX-net/XX-NetXX-Net@noreply.github.com
抄送:shawwokou123shawokou123@gmail.com
发送时间:2015年3月18日(周三) 16:40
主题:Re: [XX-Net] xxnet1.3.6无法上传个人ID (#67)


如果着急，可以找个Windows机器部署appid。
 如果Mac里装虚拟机也可以跑windows。
找个朋友帮你部署也可以。
 用公共的appid也可以.
 如果要看youtube: 非xxnet开头的appid，不限制youtube.

**Comment by xxnet** [comment]
刚才我在Mac 10.8 和Mac10.10.2上测试，部署服务端没有发现问题。
不知道是哪里出了问题。

**Comment by jackwei** [comment]
mac 10.10.2
Sys Platform	darwin
OS System	Darwin
OS version	Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64
OS release	14.1.0
OS detail	Release:10.10.2; Version:('', '', '') Machine:x86_64
architecture	64bit
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
XX-Net Version	1.3.6
Launcher Version	1.0.8
GoAgent Version	3.1.40
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087

Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>

**Comment by xxnet** [comment]
请问你是什么网络？长城宽带用户有反馈无法部署，也有校园网的反馈部署几次后就不能部署。

能否找个windows或Linux机器，或者在虚拟机里测试部署服务端？

我这边测试过Mac 10.8, 10.10，部署是正常的。
多试试不同方法，研究规律看是什么原因。

2015-03-20 23:22 GMT-04:00 jackwei <notifications@github.com>:

**Comment by jackwei** [comment]
我用的是电信的宽带，在windows 下部署成功，Mac 试了多次都是不成功，同一错误，Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>
访问youtube时：提示请重新部署服务端: http://127.0.0.1:8085/?module=goagent&menu=deploy
ps:我在windows下已经部署成功了啊，为什么还要重新部署呢？
谢谢

**Comment by xxnet** [comment]
收到，Mac下部署问题，还要再研究，我这里测试都很顺利，问题还需要定位。

你在Windows下部署过了，应该就不需要重新部署了。
你可以测试自己的appid在windows下能否使用，再到Mac下测试。


2015-03-21 10:55 GMT-04:00 jackwei <notifications@github.com>:

**Comment by xxnet** [comment]
1.7已经通过GAE，大大提高部署通过率
