### ISSUE TITLE
Google chrome 更新后打开google 网站一直显示“Your connection is not private”

### ISSUE THREAD

**Issue by qw2003** [XX-net/XX-Net#6703]
问题描述

新版XX-Net3.6.3中没有了CA.CRT证书文件，用的3.5.2版的证书文件（2017年2月16日创建），采用说明文档的各种方法Google Chrome 均不能正常工作，显示：“Your connection is not private

Attackers might be trying to steal your information from zh.wikipedia.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID”。

加载3.5.2版的证书文件后，360浏览器可以正常打开各个网站，而Google Chrome对各个网站均提示Goagent证书问题。

Google Chrome F12 后显示信息：

Security overview

**This page is not secure (broken HTTPS).**

**Subject Alternative Name missing
The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address.**
View certificate

**Certificate error
There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).
View certificate**

Secure connection
The connection to this site is encrypted and authenticated using TLS 1.2 (a strong protocol), ECDHE_RSA with P-256 (a strong key exchange), and AES_128_GCM (a strong cipher).

Secure resources
All resources on this page are served securely.

诊断信息

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.3

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:684 good:212
network-status: OK
connected-link: new:6 used:0
worker: h1:3 h2:19
scan-ip-thread-num: 5
ip-quality: 650
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​启动之前是没有CA证书的，要启动之后才产生。

试试重新导入一次证书看看

**Comment by wenliyang** [comment]
删除原有证书重新生成导入

#5322

**Comment by qw2003** [comment]
已OK，谢谢以上两位大虾。

**Comment by qw2003** [comment]
问题解决，评论关闭。
