### ISSUE TITLE
请问GAE的数量上限？

### ISSUE THREAD

**Issue by xyoungleo** [XX-net/XX-Net#6715]
GAE的数量上限不是12个么？可为什么申请了6个后，就无法申请了？project的create按钮点了没反应。
看Google的帮助文档里说，必须要填写申请表，提交银行卡号，支付费用才能继续申请更多的project。
请问大家遇到过这种情况么？谢谢！

**Comment by WLZLCX** [comment]
GAE免费名额一直在变，曾经还能创建20多个...

**Comment by junjiego** [comment]
我申请了5个gmail，一共部署了50个appid

**Comment by xyoungleo** [comment]
50个溜啊～～自己平时用个5G就差不多了
