### ISSUE TITLE
新出的android app怎么设置呢，一直显示请检查代理设置，浏览器fail，ca也是fall

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#6726]
虽说和电脑差不多，但是电脑直接自动就都ok了

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/How-to-use#android

**Comment by ylwszb** [comment]
如果安装过老版本的XX，建议先卸载和删除干净。然后再下载最新版的安卓端。
安装后，先运行XX，再打开浏览器（我用的是qq浏览器，chrome浏览器备用），在手机浏览器中输入127.0.0.1:8085，就能看到像电脑端的相似页面，找到“CA证书状态”点旁边的下载，下载CA证书然后安装到手机。再到Google商店下载proxy settings 或 proxydroid软件，把手机代理连接上（我用的是proxy settings），都设置完，返回浏览器，再打开页面就能看到正常提示了，看到正常提示了，翻·墙就成功了。
