### ISSUE TITLE
goagent 小方框内出现中文乱码且电脑嘟嘟报警

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#673]
![bad code](https://cloud.githubusercontent.com/assets/13399800/8765017/c2841f54-2e2b-11e5-93f8-ceec71975b22.jpg)
最新版2.02和2.04都有这个现象，goagent小方框内出现中文乱码（见附图）且与此同时，电脑嘟嘟报警。但可以正常使用，youtube，google.com.hk，都可以使用。前面报告的Google系列网站依然不可以使用。

**Comment by xxnet** [comment]
嘟嘟声是Windows对一些特殊字符输出的特性，原因都是乱码造成。
你通过start.vbs启动，应该就不会显示了。

怀疑访问了某些url奇怪导致，如果方便，把访问的url发出来看看

**Comment by xxnet** [comment]
1. 试试start.vbs启动

2. google 网站，试试https方式访问

在 2015年7月19日 下午3:29，farshidvahid <notifications@github.com>写道：

**Comment by farshidvahid** [comment]
1，用vbs方式解决了乱码问题
2，用https方式上了google scholar,但google.com依然上不去，不过不重要。

圆满解决！非常感谢！

至于乱码来源，应该是58同城，当时开的全局代理，用google搜索一些同城的信息，点开了58同城，然后就出现乱码了。

**Comment by farshidvahid** [comment]
最古怪的事是，一旦xx net关闭，卡巴斯基竟然都无法更新了。哈哈哈。我土和老毛子不是铁哥们吗？怎么把老毛子的杀毒软件都给封了？

**Comment by linhua55** [comment]
我第一次运行时也是乱码，重新打开后，就没遇见过了

在 2015年7月19日 下午9:45，farshidvahid <notifications@github.com>写道：

**Comment by httpe** [comment]
我这里通过代理上58同城，程序也有时会崩溃

**Comment by xxnet** [comment]
试试先打开cmd命令行窗口，然后切换到目录下，执行start.bat
然后访问58，在崩溃时可以看有什么异常日志

2015-07-20 12:17 GMT+08:00 httpe <notifications@github.com>:
