### ISSUE TITLE
可以拷贝部署成功的数据文件来直接使用么？

### ISSUE THREAD

**Issue by rainplus** [XX-net/XX-Net#6736]
不想每次都重新部署，所以问一下，部署成功后可以将数据备份给其它的使用么？

**Comment by jzp820927** [comment]
其实服务端只要部署一次就可以终身使用了，根本不需要重复部署，下次用的时候，可以还原 data 文件夹，或者把 appid 配置进 web 界面就可以了。

**Comment by rainplus** [comment]
@jzp820927 我说的重新部署的条件是环境变了重新安装xx-net的问题（rm -rf ~[手快，不小心点到了]）。这个时候只要配置？appid?

**Comment by jzp820927** [comment]
GAE 服务端是部署在 google 在美国的服务器上面的，和你本地的环境有什么关系呢？就算你电脑重装系统了，也不会影响到 google 在美国的服务器。

**Comment by rainplus** [comment]
@jzp820927  好了。。竟然可以使用。。谢谢了
