### ISSUE TITLE
希望在linux下加系统托盘功能。

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#674]
因为通过桌面快捷方式启动，在通知栏没有图标，退出不方便，再次谢谢楼主提供这么牛逼程序。

**Comment by httpe** [comment]
不是有托盘图标的吗？

**Comment by fletchere** [comment]
应该没有，我试过了，楼上你试过吗？如果你试过并成功了，发个你的.desktop文件是怎么样子的，谢谢。

**Comment by xxnet** [comment]
目前是GTK实现，Ubuntu的桌面不支持GTK的托盘，需要单独开发一个。

暂时精力有限，看多少用户吧，先忍一忍吧

在 2015年7月19日 下午4:13，fletchere <notifications@github.com>写道：

**Comment by fletchere** [comment]
多谢xxnet大神，小瑕疵而已，无碍正常使用。
