### ISSUE TITLE
祝中国人，国庆节，快乐！ ---台湾国驻中国领事馆

### ISSUE THREAD

**Issue by Fuckyouchina** [XX-net/XX-Net#6747]
https://twitter.com/Taiwan_in_China/status/913967372444323840

**Comment by sunyingjian** [comment]
越是翻墙出来 越是能看清我们伟大祖国的强大！ 台独不过是跳梁小丑罢了！！！不想骂人 手动再见

**Comment by vvvyyy** [comment]
请不要在这里讨论政治话题，这很可笑很荒唐，配合上你的ID @Fuckyouchina 更可笑了，请马上删帖删除讨论并更改标题 @sunyingjian

**Comment by Fuckyouchina** [comment]
原来XXNET，
也有这么多，爱国人士！
本领事馆，太感动了。
你们中国籍的，爱国人士，
真是遍布宇宙各角落。

**Comment by WLZLCX** [comment]
习大大与人民同乐...

**Comment by shihaibing** [comment]
@vvvyyy 支持你，你讲的很对。 @Fuckyouchina 你是唯恐天下不乱吗

**Comment by xxnet** [comment]
无礼貌攻击，封.
