### ISSUE TITLE
X-Tunnel购买流量后怎么没有显示呢？

### ISSUE THREAD

**Issue by BLACKFLAGX** [XX-net/XX-Net#6765]
X-Tunnel购买流量后怎么没有显示呢？
还是200M？？？
![qq 20171002115600](https://user-images.githubusercontent.com/17492269/31063828-3c9b5952-a769-11e7-9033-b6fc9dbd1592.png)
![qq 20171002115627](https://user-images.githubusercontent.com/17492269/31063863-8362ebf2-a769-11e7-82f0-f0bbdd2fe5a6.png)

**Comment by xxnet** [comment]
​重新登陆看看

**Comment by BLACKFLAGX** [comment]
@xxnet 可以了，不过建议在说明那里写一下购买的步骤，我几个朋友都不懂怎么购买。

**Comment by xxnet** [comment]
​恩，这个步骤应改进。

**Comment by bowuL** [comment]
shit，now is 2020, this bug is still unresolved

**Comment by xxnet** [comment]
这个问题不算bug，之前已经解决了，如果还有出现请给xxnet.dev@gmail.com发邮件
