### ISSUE TITLE
关于“尚未建立连接”

### ISSUE THREAD

**Issue by hitrust** [XX-net/XX-Net#6776]
1.备份后，删掉 data/gae_proxy/good_ip.txt 重新启动扫描（未测，应该需要很长时间，ip不好扫）
2.通过“高级”——> "检查所有IP"后，有效（亲测），不过需要几个小时，请耐心等待。

![2017-10-02_233423](https://user-images.githubusercontent.com/3360631/31085711-832a2c70-a7ca-11e7-893f-19e6ae107933.png)

**Comment by caozhiqiango** [comment]
谢谢

**Comment by MadMaxPayne8964** [comment]
不同地区不同ISP封锁情况不一样，这种方法没有代表性，比如我这家里扫一天了一个也扫不出来，单位网还残存个位数的IP

**Comment by lndnxp** [comment]
掃了許久也沒有 網通的

**Comment by hjr0** [comment]
Ip数在10来个徘徊，开启ipv6就满血

**Comment by nictse2013** [comment]
如何开启ip6?
