### ISSUE TITLE
3.6.0之后的ip扫描策略有所改变

### ISSUE THREAD

**Issue by dizzam** [XX-net/XX-Net#6789]
发现 7b15a7aaf6ede523b2884f6ea40635275b0e9bc0 这个commit改变了ip扫描的策略，感觉自从3.6.0以后xxnet经常不能用，而且将data里的ip手动删除光了以后基本扫描不到新的ip了，是不是因为该策略存在一些问题？

**Comment by EmmieMcDonald** [comment]
优化过几次了，实际感受确实比旧版好一些

你可以试试旧版本，一会我也试一下旧版，昨今两天已濒临灭绝
