### ISSUE TITLE
直接从1.0.9升级到1.3.6是否不再需要重新deploy服务器？

### ISSUE THREAD

**Issue by latrikcoasler** [XX-net/XX-Net#68]
直接从1.0.9升级到1.3.6是否不再需要重新部署服务器？直接在配置处填入以往的appid即可？
如果我成功部署过几个，之后就显示
“Application: latrickcoasler2
Host: appengine.google.com
Rolling back the update.
WARNING:google.appengine.tools.appengine_rpc:Error=BadAuthentication

upload  fail: can't set attribute
是否意味要全部重新部署？

**Comment by latrikcoasler** [comment]
再问，如何查看所有服务器运作正常？

**Comment by xxnet** [comment]
不需要重新部署服务器；

BadAuthentication
 是密码错。

使用过程中，状态页面会显示发现异常的appid。
http://127.0.0.1:8085/?module=goagent&menu=status

**Comment by latrikcoasler** [comment]
谢谢

**Comment by latrikcoasler** [comment]
问题继续存在，
版本信息：
Sys Platform	win32
OS System	Windows
OS version	5.1.2600
OS release	XP
OS detail	Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
XX-Net Version	1.3.6
Launcher Version	1.0.8
GoAgent Version	3.1.40
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087

访问google台湾或脸谱时，出现以下语句：
请重新部署服务端: http://127.0.0.1:8085/?module=goagent&menu=deploy。

于是重新上传，日志显示：
Application: latrickcoasler
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error _ssl.c:492: The handshake operation timed out>

Retry again.

Application: latrickcoasler
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error _ssl.c:492: The handshake operation timed out>

Retry again.

Application: latrickcoasler
Host: appengine.google.com
Rolling back the update.
upload  fail: <urlopen error [Errno 8] _ssl.c:507: EOF occurred in violation of protocol>

Retry again.

Application: latrickcoasler
Host: appengine.google.com
Rolling back the update.
Application: latrickcoasler; version: 1
Host: appengine.google.com

Starting update of app: latrickcoasler, version: 1
Scanning files on local disk.
Cloning 5 application files.
Compilation starting.
Compilation completed.
Starting deployment.
Checking if deployment succeeded.
Deployment successful.
Checking if updated app version is serving.

日志定格，无法继续上传。

不知是何问题。

**Comment by xxnet** [comment]
是最新版吗？
  最新版已经加上超时处理了，不应该会卡住。

**Comment by latrikcoasler** [comment]
1.3.6版，卡住了，每次都卡。比1.0.9还不顺畅

**Comment by yqfang** [comment]
1.36 不知道, 反正1.35没问题~

**Comment by xxnet** [comment]
每次都停在
Checking if updated app version is serving. 这里吗？
还是有别的地方？

2015-03-20 12:31 GMT-04:00 yqfang <notifications@github.com>:

**Comment by latrikcoasler** [comment]
好像是。

**Comment by latrikcoasler** [comment]
每次卡的地方都不同。

**Comment by xxnet** [comment]
以后不需要重新部署了，采用goagent 3.2协议
