### ISSUE TITLE
关于 X-Tunnel 无法使用的问题

### ISSUE THREAD

**Issue by SuchThatOne** [XX-net/XX-Net#6814]
登陆之后确认了还有流量，但是无法使用 Socks5 代理。日志和 Cloudflare front Log 如下：

## 日志
Oct 04 15:48:01.181 - [WARNING] session not running, try to connect
Oct 04 15:48:12.956 - [WARNING] login session fail, status:500
Oct 04 15:48:12.956 - [WARNING] x-tunnel login_session fail, session not start
Oct 04 15:48:12.957 - [WARNING] Socks4 connect fail, no conn_id
Oct 04 15:48:12.957 - [DEBUG] session not running, try login..
Oct 04 15:48:13.416 - [INFO] api:/login success t:457
Oct 04 15:48:13.416 - [INFO] update xt_server v3.xx-net.net:443
Oct 04 15:48:13.416 - [INFO] request_balance host:v3.xx-net.net port:443 balance:0.000000 quota:318000000000.000000
Oct 04 15:48:13.416 - [WARNING] session not running, try to connect
Oct 04 15:48:23.841 - [WARNING] login session fail, status:500
Oct 04 15:48:23.841 - [WARNING] x-tunnel login_session fail, session not start
Oct 04 15:48:23.841 - [WARNING] Socks4 connect fail, no conn_id
Oct 04 15:48:23.841 - [DEBUG] session not running, try login..
Oct 04 15:48:24.287 - [INFO] api:/login success t:444
Oct 04 15:48:24.287 - [INFO] update xt_server v3.xx-net.net:443
Oct 04 15:48:24.287 - [INFO] request_balance host:v3.xx-net.net port:443 balance:0.000000 quota:318200000000.000000
Oct 04 15:48:24.287 - [WARNING] session not running, try to connect
Oct 04 15:48:34.833 - [WARNING] login session fail, status:500
Oct 04 15:48:34.833 - [WARNING] x-tunnel login_session fail, session not start
Oct 04 15:48:34.833 - [WARNING] Socks4 connect fail, no conn_id
Oct 04 15:48:34.833 - [DEBUG] session not running, try login..
Oct 04 15:48:35.286 - [INFO] api:/login success t:452
Oct 04 15:48:35.286 - [INFO] update xt_server v3.xx-net.net:443
Oct 04 15:48:35.286 - [INFO] request_balance host:v3.xx-net.net port:443 balance:0.000000 quota:318400000000.000000
Oct 04 15:48:35.286 - [WARNING] session not running, try to connect
---
## Cloudflare front Log
Oct 04 15:58:26.114 - [DEBUG] ip:104.28.208.71 real fail
Oct 04 15:58:31.942 - [DEBUG] ip:104.19.61.96 real fail
Oct 04 15:58:36.944 - [DEBUG] ip:198.41.192.151 real fail
Oct 04 15:58:37.263 - [DEBUG] ip:104.20.29.229 real fail
Oct 04 15:58:37.710 - [DEBUG] ip:104.24.242.120 real fail
Oct 04 15:58:38.594 - [DEBUG] ip:141.101.123.63 real fail
Oct 04 15:58:39.639 - [DEBUG] ip:104.25.249.1 real fail
Oct 04 15:58:40.174 - [WARNING] no enough ip
Oct 04 15:58:41.172 - [DEBUG] create ssl timeout fail.
Oct 04 15:58:42.176 - [WARNING] no enough ip
Oct 04 15:58:44.179 - [WARNING] no enough ip
Oct 04 15:58:45.182 - [WARNING] no enough ip
Oct 04 15:58:46.006 - [DEBUG] ip:108.162.253.206 real fail
Oct 04 15:58:46.187 - [WARNING] no enough ip
Oct 04 15:58:46.974 - [DEBUG] ip:172.64.66.28 real fail
Oct 04 15:58:52.699 - [DEBUG] ip:104.19.28.127 real fail
Oct 04 15:58:52.983 - [DEBUG] ip:104.31.153.145 real fail
Oct 04 15:58:58.756 - [DEBUG] ip:104.18.61.194 real fail
Oct 04 15:58:59.029 - [DEBUG] ip:172.64.106.197 real fail
Oct 04 15:59:00.157 - [DEBUG] ip:108.162.253.139 real fail
Oct 04 15:59:01.012 - [DEBUG] ip:104.31.10.222 real fail
Oct 04 15:59:02.104 - [DEBUG] ip:104.17.116.113 real fail
Oct 04 15:59:02.746 - [DEBUG] ip:104.28.205.220 real fail
Oct 04 15:59:08.501 - [DEBUG] ip:104.17.198.201 real fail
Oct 04 15:59:10.301 - [DEBUG] ip:104.16.113.126 real fail
Oct 04 15:59:10.587 - [DEBUG] ip:190.93.246.58 real fail
Oct 04 15:59:15.590 - [DEBUG] ip:198.41.200.65 real fail
Oct 04 15:59:21.341 - [DEBUG] ip:104.19.8.175 real fail
Oct 04 15:59:21.583 - [DEBUG] ip:190.93.247.22 real fail
Oct 04 15:59:22.160 - [DEBUG] ip:190.93.244.165 real fail
Oct 04 15:59:22.464 - [DEBUG] ip:104.16.216.138 real fail
Oct 04 15:59:28.187 - [DEBUG] ip:104.17.94.153 real fail
Oct 04 15:59:33.904 - [DEBUG] ip:104.16.95.213 real fail
Oct 04 15:59:34.203 - [DEBUG] ip:172.64.98.151 real fail
Oct 04 15:59:35.117 - [DEBUG] ip:104.31.13.51 real fail

**Comment by SAMANTHAyue** [comment]
+1

**Comment by akari263** [comment]
+1

**Comment by joycegirl** [comment]
+1

**Comment by alex30000** [comment]
+1

**Comment by kendyho** [comment]
+1
下午突然不行

**Comment by xxnet** [comment]
服务器下午挂了，这次是因为人太多，呵呵，抱歉啊，马上加多几台。
不过这也算是好事，说明x-tunnel的速度似乎恢复了一些

**Comment by tislam8888** [comment]
@xxnet
可是看youtube 都好慢啊
感觉整天断线
比GAE 还要差
现在的GAE 只有 5个IP

**Comment by colachen2017** [comment]
我的​x-tunnel ，gae都沒法用

**Comment by SuchThatOne** [comment]
恢复了，看来只是服务器下午挂了的问题
