### ISSUE TITLE
开启IPV6后，提示“尚未建立连接”

### ISSUE THREAD

**Issue by netfun2000** [XX-net/XX-Net#6815]
路由器开启了IPV6，XX-NET也开启了IPV6，结果就提示“尚未建立连接”

**Comment by cccwhatuneed** [comment]
楼下帖子 有服务商映射ipv6的方法

**Comment by vvvyyy** [comment]
应该不是每个人都可以开启的

**Comment by netfun2000** [comment]
现在变成了：“System is Idle.”

**Comment by netfun2000** [comment]
XX-Net Status:

sys-platform: armv6l, Linux-4.9.35+-armv6l-with-debian-8.0
os-system: Linux
os-version: #1014 Fri Jun 30 14:34:49 BST 2017
os-release: 4.9.35+
os-detail: Dist:debian; Version:8.0; ID:
architecture: 32bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.6.7

python-version: 2.7.9
openssl-version: 0.13.1 TLSv1 h2:no

ipv6-status: 1
gws-ip-num: total:12347 good:4359
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 1
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xiaozixun** [comment]
本地网络状态 | OK
IP数量 | 12272
空闲 | 0
IP延迟 | 300
连接池(帮助) | 新:10 h1:22 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK

**Comment by netfun2000** [comment]
上面的XX-NET是运行在树莓派上的，重新在WIN10上部署并开启IPV6。现在FW没有问题了，建议大家这样做。
