### ISSUE TITLE
xx-tunnel google scholar 不能访问

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#6818]
gae 没有IP，尝试使用了xx-tunnel，其它都能使用，但在打开google scholar时，出现如下问题：

We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

**Comment by onplus** [comment]
哪个学校的，连个谷歌学术镜像都没有吗

**Comment by sky2917** [comment]
是的，google scholar 不能访问。我这显示：连接超时，先休息一会再来！

google，twitter等都能访问。

**Comment by xxnet** [comment]
​google scholar 把咱的服务器列黑名单了，暂时没有办法，不知道谁用咱的服务做坏事了。

**Comment by sky2917** [comment]
@xxnet   有人盗用了咱的服务器？申诉一下，国内科研人员热切盼望能使用 ​google scholar.

**Comment by vvvyyy** [comment]
看看，连科研人员的工作都受到阻挠，就这还实现“中国梦”？还“伟大复兴”？呵呵。

**Comment by vvvyyy** [comment]
不过话说做了什么坏事能让Google拉黑。。可怕。。
