### ISSUE TITLE
越来越迷了

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#6819]
有155个ip但是连接池为0显示尚未建立连接
xtunnel流量以200mb一次的速度不断增加？

**Comment by Temmie-hOi** [comment]
还有浏览器代理设置和ca证书状态一直在fail

**Comment by HUMORCE** [comment]
xtunnel 是每次登录会赠送200MB

有155个ip但是连接池为0显示尚未建立连接 如果是在扫IP，那么说明列队中还有155个未扫描

浏览器代理设置和ca证书状态 fail 其实可以不管，因为实际上是生效的。

**Comment by colachen2017** [comment]
我的​x-tunnel 登錄上，可是不連不上網

127.0.0.1 8087  同樣的設置嗎？

**Comment by xxnet** [comment]
​端口是 1080
