### ISSUE TITLE
enable ipv6 on Windows 7, xx-net back to life

### ISSUE THREAD

**Issue by lndnxp** [XX-net/XX-Net#6829]
1.i got dual os(win7/10), win10 is ipv6 ready, win7/8 need some work
2.check this post [[技术] 在家轻轻松松上IPv6站点之Teredo篇——某站点又全站Free了](http://bbs.pcbeta.com/viewthread-1580771-1-1.html)
3.only need to execute part 四
4.use the cmd line of part 六 `netsh int ipv6 show teredo state`
5.looks like this, the Windows 7 is ipv6 ready!
![capture](https://user-images.githubusercontent.com/32247328/31187075-42558d76-a963-11e7-9ecb-b92a65876c93.PNG)

enable ipv6 of xx-net
make sure the config.ini look like this
![capture01](https://user-images.githubusercontent.com/32247328/31187186-b111ff7e-a963-11e7-8d8c-0fd03c18e02e.PNG)

and xx-net works just fine
![capture02](https://user-images.githubusercontent.com/32247328/31187245-e7759418-a963-11e7-92b6-8ee3c0f1f416.PNG)

**Comment by Askwind** [comment]
THX a lot！ win10 back to life.

**Comment by smsihe** [comment]
NAT   : symmetric (address)
Does it mean...I am done ? ToT

**Comment by nictse2013** [comment]
cant find part 四 in the link

**Comment by sakuratyan** [comment]
xx-net back to life

**Comment by zqchina** [comment]
![2017-10-05_150424](https://user-images.githubusercontent.com/26019692/31214631-a0fc4268-a9de-11e7-8229-be55f8bfb6d3.jpg)

**Comment by lndnxp** [comment]
1.运营商分配ipv6是前提，确定家里宽带拨号是有ipv6的，再接路由就可以
2.part 四 就是“四、重头戏，配置Teredo”那段...
3.我这里没炸...
![capture](https://user-images.githubusercontent.com/32247328/31216342-e64e0e76-a9e5-11e7-92c1-3547a2a1caf1.PNG)

4.ping的通吗,换下服务器试试
![capture01](https://user-images.githubusercontent.com/32247328/31216264-96c4743a-a9e5-11e7-93eb-c6a50cd11b1a.PNG)

**Comment by xiaozixun** [comment]
这个也是处在炸与未炸之间。昨晚1W+，现在只有10个。

**Comment by lndnxp** [comment]
1
