### ISSUE TITLE
GAEProxy状态信息尚未建立连接 gogotest 一个IP的扫不出来 XXNET要挂了么？

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#6838]
GAEProxy状态信息尚未建立连接 gogotest 一个IP的扫不出来
 XXNET要挂了么？

**Comment by tislam8888** [comment]
我这边也阵亡了 好惨啊

**Comment by RedLeavesSun** [comment]
同样阵亡

**Comment by nly4lov** [comment]
我也尚未连接，重新下载、导入证书就好了

**Comment by qaweqa** [comment]
Oct 05 12:42:58.918 - [DEBUG] 207.181.192.158 fail:timeout('timed out',)

Oct 05 12:42:58.918 - [DEBUG] report_connect_fail:207.181.192.158

Oct 05 12:42:59.373 - [DEBUG] 201.175.77.111 fail:timeout('timed out',)

Oct 05 12:42:59.373 - [DEBUG] report_connect_fail:201.175.77.111

Oct 05 12:42:59.881 - [DEBUG] 201.175.77.115 fail:timeout('timed out',)

Oct 05 12:42:59.881 - [DEBUG] report_connect_fail:201.175.77.115

Oct 05 12:43:00.411 - [DEBUG] 62.4.253.236 fail:timeout('timed out',)

Oct 05 12:43:00.411 - [DEBUG] report_connect_fail:62.4.253.236

Oct 05 12:43:01.110 - [DEBUG] 62.4.253.231 fail:timeout('timed out',)

Oct 05 12:43:01.110 - [DEBUG] report_connect_fail continue_fail_count:11

Oct 05 12:43:01.111 - [DEBUG] report_connect_fail:62.4.253.231

Oct 05 12:43:01.295 - [DEBUG] network is ok, cost:184 ms

Oct 05 12:43:01.365 - [DEBUG] ip:118.98.36.117 real fail

Oct 05 12:43:01.383 - [DEBUG] 200.28.8.224 fail:timeout('timed out',)

Oct 05 12:43:01.383 - [DEBUG] report_connect_fail:200.28.8.224

Oct 05 12:43:01.884 - [DEBUG] 177.67.85.237 fail:timeout('timed out',)

Oct 05 12:43:01.884 - [DEBUG] report_connect_fail:177.67.85.237

Oct 05 12:43:02.367 - [DEBUG] create ssl timeout fail.

Oct 05 12:43:02.409 - [DEBUG] 118.98.106.217 fail:timeout('timed out',)

Oct 05 12:43:02.409 - [DEBUG] report_connect_fail:118.98.106.217

Oct 05 12:43:02.449 - [DEBUG] 105.187.242.83 fail:timeout('timed out',)

Oct 05 12:43:02.449 - [DEBUG] report_connect_fail:105.187.242.83

**Comment by dzxion** [comment]
重新下载什么？

**Comment by nly4lov** [comment]
@dzxion 重新下载证书哇

**Comment by nly4lov** [comment]
只是IP总是个位数，2个或3个，妈的。

**Comment by missdown** [comment]
喜迎十九大，学校的ipv6也给关了

**Comment by kururu002** [comment]
ip quality:9999啊～～～

**Comment by dzxion** [comment]
@nly4lov 你的现在还可以用？

**Comment by LN-VIVI** [comment]
导入IP115.254.97.14试试@dzxion  @kururu002  @missdown

**Comment by LN-VIVI** [comment]
刚扫到一个IP 现在又挂了

**Comment by nly4lov** [comment]
@dzxion 虽然只有2个ip，但能翻。

**Comment by dzxion** [comment]
@nly4lov 嗯，我有3个IP，能翻但很慢

**Comment by shiyisyl** [comment]
导入一个不到一分钟就挂了

**Comment by liyibo123** [comment]
完了

**Comment by nly4lov** [comment]
@dzxion 我翻得很快
