### ISSUE TITLE
旧版本可用，自动更新到新版本就不行了

### ISSUE THREAD

**Issue by Seraphli** [XX-net/XX-Net#6842]
我昨天在另一台机子上用的旧版本，还可以直接上，今天一看给自动更新到了新版本，结果什么IP都没有了。我感觉是新版本有些问题。

**Comment by Seraphli** [comment]
我有朋友还在用旧版本，他说还是可以用的，他没有开自动更新。

**Comment by dzxion** [comment]
怎么变回旧版本

**Comment by Seraphli** [comment]
使用git回滚啊

**Comment by dzxion** [comment]
不懂，能不能说详细点？

**Comment by Thebiggestlight** [comment]
哪个版本能用？

**Comment by onplus** [comment]
直接把另一台的整个复制过来。
用什么git，随便选版本:https://github.com/XX-net/XX-Net/releases

**Comment by zqchina** [comment]
哪个版本？

**Comment by ShixiangWan** [comment]
我试了旧版本，也不能用。原因不是主页上说的GAE封锁严重么？
