### ISSUE TITLE
无法启动，点击XX-Net图标后没反应

### ISSUE THREAD

**Issue by Dilingg** [XX-net/XX-Net#6847]
之前一直都能正常使用，今天莫名其妙的无法启动。
点击图标之后，鼠标转下圈，然后没有任何反应了。地址栏输入 “http://127.0.0.1:8085” 也无法进入xx-Net管理页面。
系统是win10最新的。
请帮忙看看这是怎么回事，谢谢！

**Comment by azurelar** [comment]
重新下载一个包   你是不是修改配置文件了  修改后 就会无法启动  要改配置的话 要在data文件夹里改 不要改code里边的

**Comment by Dilingg** [comment]
@azurelar 没有修改过配置文件。重新下个包倒是能解决，不过又要重新扫描ip，配置APPID，有点麻烦。
谢谢
