### ISSUE TITLE
那些有IP的，能不能把你们的IP分享出来让扫描不到的手动加进去？

### ISSUE THREAD

**Issue by Bohan-Song** [XX-net/XX-Net#6851]
不知道这样可以不？

**Comment by Bohan-Song** [comment]
我没有ipv6，今天上午扫到了一个
115.254.97.14
扫不到的试试可以不

**Comment by LN-VIVI** [comment]
谢谢！

**Comment by TeslaHua** [comment]
没有用

**Comment by TeslaHua** [comment]
你刷到一个IP管用吗？

**Comment by Bohan-Song** [comment]
管用，能Google，不然我也不会分享啊。。。

**Comment by hahaliu2000** [comment]
119.28.87.227|119.28.84.182，反正一天也就封了，看到的可以试试

**Comment by roc1010kmt** [comment]
別人掃到的你不一定能用喔。

**Comment by t1413** [comment]
打开ipv6，有ip

**Comment by cjxxd** [comment]
119.28.87.227|119.28.84.182这两个ip能用，刚连上了

**Comment by Bohan-Song** [comment]
我不支持ipv6，不过开了之后竟然能扫出来。。。现在IP有7000+

**Comment by kim-wang-bj** [comment]
IP地址: 119.28.84.182香港特别行政区 腾讯集团？？？？？
