### ISSUE TITLE
X-Tunnel不能正常使用

### ISSUE THREAD

**Issue by SergeyChang** [XX-net/XX-Net#6863]
so ~~~ what's wrong~~~

**Comment by fa11111** [comment]
X-Tunnel又挂了。
Socks4 connect fail, no conn_id

**Comment by xxnet** [comment]
似乎数据库出问题，正在处理中，各位有问题给我发邮件，我稍后会逐个处理

先不要买套餐

**Comment by fa11111** [comment]
x大，gae是不是要到国庆大假过后才能恢复？

**Comment by s-mao** [comment]
确实xtunnel刚又挂了，还没恢复。。。

**Comment by Fzongx** [comment]
@xxnet  3小时前在X-Tunnel上花4.5$买了3个月的,至今账户余额还是0.另外还是3小时前,捐赠了15个appid,邮件已发.

**Comment by chenzijng** [comment]
![Uploading image.png…]()
Oct 05 22:03:54.777 - [WARNING] h1 head send len:0 39 172.64.37.161
Oct 05 22:03:54.777 - [WARNING] 172.64.37.161 trace: 0:connect, 4199:init, 0:head,:4102, processed:0, transfered:0
Oct 05 22:03:54.777 - [DEBUG] report_connect_fail:172.64.37.161
Oct 05 22:03:54.996 - [DEBUG] 104.24.41.65 worker close:keep alive
Oct 05 22:03:55.637 - [DEBUG] 190.93.247.183 worker close:keep alive
Oct 05 22:03:55.658 - [DEBUG] 162.159.131.244 worker close:keep alive
Oct 05 22:03:55.740 - [DEBUG] 162.159.228.202 worker close:keep alive
Oct 05 22:03:55.741 - [DEBUG] create_ssl update ip:104.24.190.50 time:4119 h2:0
Oct 05 22:03:55.771 - [DEBUG] new_conn_pool.get:104.24.190.50 handshake:4119
Oct 05 22:03:55.772 - [DEBUG] head request 104.24.190.50
Oct 05 22:03:55.959 - [DEBUG] 104.28.134.217 worker close:keep alive
Oct 05 22:03:56.076 - [DEBUG] 172.64.97.186 worker close:keep alive
Oct 05 22:03:56.616 - [WARNING] h1 190.93.244.205 HEAD keep alive request fail:Exception('time out',)
Oct 05 22:03:56.616 - [WARNING] 190.93.244.205 trace: 0:connect, 2557:init, 0:head,:5519, processed:0, transfered:0
Oct 05 22:03:56.616 - [DEBUG] 190.93.244.205 close:down fail
Oct 05 22:03:56.616 - [DEBUG] 190.93.244.205 worker close:head fail
Oct 05 22:03:56.617 - [DEBUG] report_connect_fail:190.93.244.205
Oct 05 22:03:57.021 - [DEBUG] create_ssl update ip:104.17.129.169 time:4107 h2:0
Oct 05 22:03:57.027 - [DEBUG] new_conn_pool.get:104.17.129.169 handshake:4107
Oct 05 22:03:57.027 - [DEBUG] head request 104.17.129.169
Oct 05 22:03:57.878 - [DEBUG] create_ssl update ip:104.24.76.123 time:4112 h2:0
Oct 05 22:03:57.888 - [DEBUG] ip:190.93.244.244 real fail
Oct 05 22:03:57.893 - [DEBUG] new_conn_pool.get:104.24.76.123 handshake:4112
Oct 05 22:03:57.894 - [DEBUG] head request 104.24.76.123
Oct 05 22:03:58.368 - [DEBUG] create_ssl update ip:104.25.92.74 time:4117 h2:0
Oct 05 22:03:58.873 - [WARNING] h1 head send len:0 39 104.24.99.28
Oct 05 22:03:58.873 - [WARNING] 104.24.99.28 trace: 0:connect, 4215:init, 0:head,:4105, processed:0, transfered:0
Oct 05 22:03:58.873 - [DEBUG] report_connect_fail:104.24.99.28
Oct 05 22:03:59.778 - [DEBUG] 172.64.37.161 worker close:keep alive
Oct 05 22:03:59.800 - [DEBUG] 104.23.138.138 fail:error(' certficate is none',)
Oct 05 22:03:59.800 - [DEBUG] report_connect_fail continue_fail_count:11
Oct 05 22:03:59.800 - [DEBUG] report_connect_fail:104.23.138.138
Oct 05 22:03:59.822 - [DEBUG] 104.28.3.190 fail:error(' certficate is none',)
Oct 05 22:03:59.823 - [DEBUG] report_connect_fail continue_fail_count:12
Oct 05 22:03:59.823 - [DEBUG] report_connect_fail:104.28.3.190
Oct 05 22:03:59.873 - [WARNING] h1 head send len:0 39 104.24.190.50
Oct 05 22:03:59.873 - [WARNING] 104.24.190.50 trace: 0:connect, 4217:init, 1:head,:4100, processed:0, transfered:0
Oct 05 22:03:59.873 - [DEBUG] report_connect_fail continue_fail_count:13
Oct 05 22:03:59.873 - [DEBUG] report_connect_fail:104.24.190.50
Oct 05 22:03:59.926 - [DEBUG] 104.19.118.8 fail:error(' certficate is none',)
Oct 05 22:03:59.926 - [DEBUG] 141.101.113.63 fail:error(' certficate is none',)
Oct 05 22:03:59.926 - [DEBUG] 104.16.119.252 fail:error(' certficate is none',)
Oct 05 22:03:59.926 - [DEBUG] report_connect_fail continue_fail_count:14
Oct 05 22:03:59.927 - [DEBUG] report_connect_fail:104.19.118.8
Oct 05 22:03:59.927 - [DEBUG] report_connect_fail continue_fail_count:15
Oct 05 22:03:59.927 - [DEBUG] report_connect_fail:141.101.113.63
Oct 05 22:03:59.927 - [DEBUG] report_connect_fail continue_fail_count:16
Oct 05 22:03:59.927 - [DEBUG] report_connect_fail:104.16.119.252
Oct 05 22:03:59.974 - [DEBUG] network is ok, cost:174 ms
Oct 05 22:04:00.233 - [DEBUG] 104.17.238.63 fail:error(' certficate is none',)
Oct 05 22:04:00.233 - [DEBUG] report_connect_fail:104.17.238.63
Oct 05 22:04:01.131 - [WARNING] h1 head send len:0 39 104.17.129.169
Oct 05 22:04:01.131 - [WARNING] 104.17.129.169 trace: 0:connect, 4171:init, 0:head,:4104, processed:0, transfered:0
Oct 05 22:04:01.131 - [DEBUG] report_connect_fail:104.17.129.169

**Comment by xxnet** [comment]
​数据库出了点问题，在处理中，部分用户受影响，需要重新导数据库，预计明天能恢复。
受影响的用户，可以试试重新注册用户先用着。

大家先不要买套餐。

**Comment by hhp99** [comment]
3.6.6能够登录x-tunnel，3.6.7说ID不对

**Comment by xxnet** [comment]
先试试，不行再

​退回 3.6.6 看看能否登陆

**Comment by SergeyJay** [comment]
@xxnet thanks
