### ISSUE TITLE
好像恢复了！

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#6869]
点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 12326
空闲 | 0
IP延迟 | 300
连接池(帮助) | 新:2 h1:11 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK

**Comment by GraceLum** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.7

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 8
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by GraceLum** [comment]
求协助

**Comment by lslsls1441** [comment]
你用的什么版本啊

**Comment by LN-VIVI** [comment]
@lslsls1441 3.67

**Comment by lslsls1441** [comment]
@LN-VIVI 谢谢了 待会去试试

**Comment by YUFUXUECHI** [comment]
刚刚xtunder都断了

**Comment by zhuchuanlong1988** [comment]
换xx用，ip只有两个用的还可以，不知道是不是路由重启的原因，不知道哪里弄好的

**Comment by bird-z** [comment]
如果没猜错的话 那两个也许理论上查出的地址是印度的

**Comment by MadMaxPayne8964** [comment]
楼主想多了，你那状态显然是基于teredo的IPv6

**Comment by LN-VIVI** [comment]
@MadMaxPayne8964  说的不是我吧，我家网络用不了IPV6你指的是我楼下那位？

**Comment by dzxion** [comment]
@LN-VIVI 没有恢复啊

**Comment by zhencaihao** [comment]
我这里现在X-TUNNEL连不了。开IPV6倒是能用，但是非常的卡。

**Comment by dzxion** [comment]
还有其他翻墙的方法么？

**Comment by MadMaxPayne8964** [comment]
@LN-VIVI ，就是说你，纯IPv4也可以开启基于teredo 6to4隧道的IPv6，速度和延迟全看隧道情况

**Comment by miss13** [comment]
我的ip也是9月30最后一次扫描到的，哎估计要等待一段时间了。应该是gfw升级的问题吧！

**Comment by LN-VIVI** [comment]
@MadMaxPayne8964  你的能用吗？我笔记本不行
<img width="847" alt="x" src="https://user-images.githubusercontent.com/18262731/31233693-c5367ca2-aa1f-11e7-8084-f5193206c4c2.png">

**Comment by AmelieNet** [comment]
@LN-VIVI 你这个测试网址是多少?

**Comment by MadMaxPayne8964** [comment]
@LN-VIVI ，这截图明显是走的teredo隧道，笔记本可能没配置好隧道。配置好隧道任意IPv4环境下都能启用ipv6

**Comment by LN-VIVI** [comment]
@MadMaxPayne8964 嗯，现在好了，层主大神啊懂得比我多

**Comment by LN-VIVI** [comment]
@MadMaxPayne8964  我不知道弄了什么，原来那台电脑又不能用了，直接变回尚未建立连接

**Comment by MadMaxPayne8964** [comment]
@LN-VIVI，隧道不稳定，很多6to4被ban，没被ban的速度带宽都不咋地

**Comment by AmelieNet** [comment]
不是校园网也可以通过隧道走IPV6吗?

**Comment by LN-VIVI** [comment]
@MadMaxPayne8964  我这边的速度挺好的，为什么我笔记本能连，台式电脑昨晚能连现在却不行了，我不知道弄了什么，现在是尚未建立连接 我发现连接池好像不对劲

属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 9190
空闲 | 0
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK

这是现在的





下面是昨晚能连的
属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 12326
空闲 | 0
IP延迟 | 300
连接池(帮助) | 新:2 h1:11 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK

**Comment by LN-VIVI** [comment]
@jzp820927  
我这边的速度挺好的，为什么我笔记本能连，台式电脑昨晚能连现在却不行了，我不知道弄了什么，现在是尚未建立连接 我发现连接池好像不对劲

**Comment by LN-VIVI** [comment]
## @MadMaxPayne8964  同在一个局域网，我家的是联通网络，不支持ipv6，为毛我笔记本电脑用xxnet可以开启ipv6网络而我的台式电脑却又不可以，都怪我昨晚多手在台式电脑上设置了什么搞得现在台式电脑xxnet用不了

**Comment by jzp820927** [comment]
@LN-VIVI 笔记本能用，就把笔记本上的 XXNET 复制到台式机上用吧，或者你直接用笔记本不就行了吗

**Comment by LN-VIVI** [comment]
@jzp820927  复制到台式电脑还是不行，笔记本能用，好奇怪哟

**Comment by jzp820927** [comment]
那就用笔记本的，或者把把笔记本的共享给台式机用
