### ISSUE TITLE
升级到2.0.4

### ISSUE THREAD

**Issue by evilstyle** [XX-net/XX-Net#687]
log 页面老是抛这个异常 请问什么情况？
Jul 21 09:54:19 - [WARNING] no gws ip
Jul 21 09:54:20 - [WARNING] no gws ip
Jul 21 09:54:21 - [WARNING] no gws ip
Jul 21 09:54:22 - [DEBUG] get ip:128.0.169.214 t:604
Jul 21 09:54:23 - [WARNING] no gws ip
Jul 21 09:54:24 - [WARNING] no gws ip
Jul 21 09:54:25 - [WARNING] no gws ip
Jul 21 09:54:25 - [WARNING] no gws ip
Jul 21 09:54:26 - [WARNING] no gws ip
Jul 21 09:54:27 - [WARNING] no gws ip
Jul 21 09:54:27 - [DEBUG] create_ssl update ip:128.0.169.214 time:1610
Jul 21 09:54:28 - [WARNING] no gws ip
Jul 21 09:54:28 - [DEBUG] sort ip time:2101ms
Jul 21 09:54:29 - [WARNING] no gws ip
Jul 21 09:54:30 - [WARNING] no gws ip
Jul 21 09:54:31 - [WARNING] no gws ip

**Comment by linhua55** [comment]
可用ip数量过少，运行一会就好了

2015-07-21 9:56 GMT+08:00 evilstyle <notifications@github.com>:

**Comment by evilstyle** [comment]
确实是 ，扫描了 半小时后就没了。谢谢
