### ISSUE TITLE
3.6.7 无法访问google学术，请帮忙，谢谢。

### ISSUE THREAD

**Issue by hulu1528** [XX-net/XX-Net#6870]
以前用的xx-net是可以使用google学术的，最近突然发现google学术https://scholar.google.com/和一些学校的邮箱系统竟然无法打开了。google学术提示的问题是：连接超时，先休息一会再来！  访问学校邮箱直接提示不安全连接。

配置文件中也提示了google学术是直连direct，即使注释掉不进行直连也不可以访问学术。
同时是可以使用youtube，facebook，google的。

![2](https://user-images.githubusercontent.com/3378255/31231681-18aa8eba-aa1a-11e7-8a05-3bbbdaeb114b.png)
![11](https://user-images.githubusercontent.com/3378255/31231680-18a39a60-aa1a-11e7-9943-cbe04161d8ba.png)

Oct 05 22:12:03.880 - [INFO] GAE t:381 s:1102 GET https://www.google.com/_/chrome/newtab-serviceworker.js 0:start_request,0:get_task,0:get_worker:119.28.87.227,0:h2_req,378:h2_get_head,0:get_response,0:h2_finish[SP:765055],:0
Oct 05 22:12:04.123 - [DEBUG] 213.145.140.28 fail:timeout('timed out',)
Oct 05 22:12:04.123 - [DEBUG] report_connect_fail:213.145.140.28
Oct 05 22:12:04.174 - [DEBUG] 177.55.62.105 fail:timeout('timed out',)
Oct 05 22:12:04.174 - [DEBUG] report_connect_fail:177.55.62.105
Oct 05 22:12:04.656 - [DEBUG] 201.157.200.17 fail:timeout('timed out',)
Oct 05 22:12:04.656 - [DEBUG] report_connect_fail:201.157.200.17
Oct 05 22:12:04.703 - [DEBUG] 202.75.147.24 fail:timeout('timed out',)
Oct 05 22:12:04.703 - [DEBUG] report_connect_fail:202.75.147.24
Oct 05 22:12:04.812 - [DEBUG] 216.58.206.4 fail:timeout('timed out',)
Oct 05 22:12:04.812 - [DEBUG] report_connect_fail:216.58.206.4
Oct 05 22:12:04.968 - [DEBUG] 203.176.178.48 fail:timeout('timed out',)
Oct 05 22:12:04.968 - [DEBUG] report_connect_fail:203.176.178.48
Oct 05 22:12:05.206 - [DEBUG] 180.149.91.90 fail:timeout('timed out',)
Oct 05 22:12:05.206 - [DEBUG] report_connect_fail:180.149.91.90
Oct 05 22:12:05.709 - [DEBUG] 203.114.135.23 fail:timeout('timed out',)
Oct 05 22:12:05.709 - [DEBUG] report_connect_fail:203.114.135.23
Oct 05 22:12:06.591 - [DEBUG] GAE GET https://notifications.google.com/u/0/widget?sourceid=243&hl=zh-CN&origin=https%3A%2F%2Fwww.google.com&uc=1&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.ZPSwvoEq44A.O%2Fm%3D__features__%2Fam%3DAAg%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo8-JL5R4cxPdwFdZ0Yu3_ek27rKCQ
Oct 05 22:12:06.932 - [DEBUG] ip:64.233.165.149 real fail
Oct 05 22:12:07.845 - [INFO] GAE t:1253 s:89280 GET https://notifications.google.com/u/0/widget?sourceid=243&hl=zh-CN&origin=https%3A%2F%2Fwww.google.com&uc=1&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.ZPSwvoEq44A.O%2Fm%3D__features__%2Fam%3DAAg%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo8-JL5R4cxPdwFdZ0Yu3_ek27rKCQ 0:start_request,0:get_task,0:get_worker:119.28.87.227,0:h2_req,655:h2_get_head,0:get_response,:0
Oct 05 22:12:08.024 - [DEBUG] GAE POST https://play.google.com/log?format=json
Oct 05 22:12:09.198 - [INFO] GAE t:1173 s:114 POST https://play.google.com/log?format=json 0:start_request,0:get_task,0:get_worker:119.28.87.227,0:h2_req,1171:h2_get_head,0:get_response,1:h2_finish[SP:672888],:0
Oct 05 22:12:09.198 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Hja1Xx6u9r8Y3/DZ3i90MA%3D%3D
Oct 05 22:12:09.651 - [INFO] GAE t:453 s:2345 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Hja1Xx6u9r8Y3/DZ3i90MA%3D%3D 0:start_request,0:get_task,0:get_worker:119.28.87.227,0:h2_req,450:h2_get_head,0:get_response,1:h2_finish[SP:2748543],:0
Oct 05 22:12:09.666 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Hja1Xx6u9r8Y3/DZ3i90MA%3D%3D
Oct 05 22:12:10.084 - [INFO] GAE t:418 s:438 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=Hja1Xx6u9r8Y3/DZ3i90MA%3D%3D 0:start_request,0:get_task,0:get_worker:119.28.87.227,0:h2_req,414:h2_get_head,0:get_response,2:h2_finish[SP:420980],:0
Oct 05 22:12:11.933 - [DEBUG] ip:95.180.157.19 real fail
Oct 05 22:12:12.271 - [DEBUG] 77.234.90.36 fail:timeout('timed out',)
Oct 05 22:12:12.271 - [DEBUG] report_connect_fail:77.234.90.36
Oct 05 22:12:13.517 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Oct 05 22:12:13.582 - [DEBUG] GET http://www.twitter.com/xxnet
Oct 05 22:12:16.355 - [DEBUG] 85.112.121.154 fail:timeout('timed out',)
Oct 05 22:12:16.355 - [DEBUG] report_connect_fail:85.112.121.154
Oct 05 22:12:16.933 - [DEBUG] ip:92.246.12.218 real fail
Oct 05 22:12:20.355 - [DEBUG] 188.43.68.111 fail:timeout('timed out',)
Oct 05 22:12:20.355 - [DEBUG] report_connect_fail:188.43.68.111
Oct 05 22:12:21.934 - [DEBUG] ip:91.103.72.57 real fail

**Comment by SeaHOH** [comment]
如果只是上谷歌，使用 Chrome 配合 hosts 就行。

**Comment by bolaparte** [comment]
用X-TUNNEL好像也无法访问谷歌网站了。。。
下午还能访问，晚上就不行了。

**Comment by hulu1528** [comment]
@SeaHOH  谢谢支持。  关键是我还有自己的邮箱也无法访问，以前好像是可以访问的，后来自动升级以后就不可以了。
