### ISSUE TITLE
我的X-Tunnel速度慢，是因为是试用版么？

### ISSUE THREAD

**Issue by ArchNew** [XX-net/XX-Net#6874]
鉴于最近的封锁加剧，我打算使用付费的X-Tunnel了。我已经注册了Paypal，并且注册了X-Tunnel。进入X-Tunnel后，发现有试用流量。于是我决定先试用一下后再付费。但试用时，速度比GAE_proxy只有两个IP时还慢，并且完全无法看Youtube视频。不知道这只是免费试用时的问题，还是说收费后仍然是这样。如果是后者，那我就没有购买的必要了。

**Comment by sylingd** [comment]
https://github.com/XX-net/XX-Net/issues/6863

**Comment by ArchNew** [comment]
在他宣布有问题之前，就很慢了……

**Comment by xxnet** [comment]
​速度慢是因为封锁干扰，同时算法也有改进空间，以后会持续改进。
