### ISSUE TITLE
[公告] X-Tunnel服务器 异常

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#6876]
目前服务器数据库出现异常，正在处理。
部分帐号受影响，请先不要支付购买流量，等待恢复。

重新导数据库需要花费时间，预计要明天下午。
需要用的，可以先试试重新注册一个新用户。

抱歉了各位，这几天GAE被封严重，x-tunnel的使用量增加，触发了不少问题，正在逐个处理完善。

**Comment by slyypp** [comment]
@xxnet  嗯，今天上午好好的，现在X-Tunnel是不能用了。不过期待众IT大神们迎难而上，破墙而出！！！

**Comment by colachen2017** [comment]
確實 有問題 幫不上什麼 ...只能多謝啦

**Comment by toobed** [comment]
辛苦了！，实在过意不去。

**Comment by mentalssh** [comment]
心塞，看了世界几分钟就没了。辛苦@xxnet

**Comment by mooredam** [comment]
X-Tunnel目前无法登陆，卡在请稍后页面

**Comment by guanyueqi** [comment]
希望XX-net能回复，GAE可以让我们继续用，虽然知道一直吃免费午餐不好，但XX的工作让我非常感动，感恩感动感谢！

**Comment by joycegirl** [comment]
这才是真正的为人民服务。
那些公仆：人民有好处的一录都反对，自己有好处的半夜鸡叫，一夜实施。

**Comment by zangyijun** [comment]
总之还是特别感谢@xxnet没有你的世界，真的充满黑暗！

**Comment by Ashu3166** [comment]
国庆期间也要劳心劳力, 真的太感谢你了

**Comment by renqy** [comment]
刚刚才买了3个月的套餐，不会有影响吧。

**Comment by ArchNew** [comment]
注册了新的用户，然而并没有用……

**Comment by xxnet** [comment]
服务器刚升级了一个版本，请重新测试。

**Comment by xxnet** [comment]
​丢失流量的，还要我逐个手工处理，没有那么快，但是每次登陆送流量的，应该好了。

**Comment by hhp99** [comment]
3.6.6的版本能登录，3.6.7的无法登录，说ID错误

**Comment by ffdzpilot** [comment]
Get Fail:status:500

**Comment by wsjzjt** [comment]
纠结流量的就别出来说了，之前双击X-TUNNEL配置也没就能获得200~400M流量，别给我说没人利用这个bug，我也用了。

**Comment by lw8228** [comment]
Login fail:status:500

**Comment by AlyoshaMa** [comment]
话说 就是北京时间6号 了  GAE 不会永远封吧？？？

**Comment by DanaYe** [comment]
Oct 06 00:45:51.472 - [INFO] X-Tunnel window:33554432
Oct 06 00:45:51.474 - [INFO] Socks5 server listen:127.0.0.1:1080.
Oct 06 00:45:56.730 - [DEBUG] x_tunnel force update info
Oct 06 00:45:57.533 - [DEBUG] x-tunnel web_control 127.0.0.1:12941 POST /login
Oct 06 00:47:23.076 - [DEBUG] x-tunnel web_control 127.0.0.1:12937 POST /login
Oct 06 00:48:34.123 - [INFO] api:/login success t:157391
Oct 06 00:48:34.123 - [INFO] update xt_server v2.xx-net.net:443
Oct 06 00:48:34.123 - [INFO] request_balance host:v2.xx-net.net port:443 balance:0.000000 quota:309441856425.000000
Oct 06 00:48:39.123 - [INFO] api:/login success t:76046
Oct 06 00:48:39.123 - [INFO] update xt_server v2.xx-net.net:443
Oct 06 00:48:39.123 - [INFO] request_balance host:v2.xx-net.net port:443 balance:0.000000 quota:309641856425.000000
Oct 06 00:48:41.061 - [INFO] api:/login success t:163527
Oct 06 00:48:41.061 - [INFO] update xt_server v4.xx-net.net:443
Oct 06 00:48:41.061 - [INFO] request_balance host:v4.xx-net.net port:443 balance:0.000000 quota:309841856425.000000
Oct 06 00:49:04.515 - [DEBUG] session not running, try login..
Oct 06 00:49:05.279 - [INFO] api:/login success t:763
Oct 06 00:49:05.279 - [INFO] update xt_server v4.xx-net.net:443
Oct 06 00:49:05.279 - [INFO] request_balance host:v4.xx-net.net port:443 balance:0.000000 quota:310041856425.000000
Oct 06 00:49:05.279 - [WARNING] session not running, try to connect

**Comment by DanaYe** [comment]
Oct 06 00:49:05.279 - [WARNING] session not running, try to connect
Oct 06 00:50:48.760 - [WARNING] login session fail, status:500
Oct 06 00:50:48.760 - [WARNING] x-tunnel login_session fail, session not start
Oct 06 00:53:14.725 - [DEBUG] x-tunnel web_control 127.0.0.1:13592 POST /login
Oct 06 00:53:15.283 - [INFO] api:/login success t:558
Oct 06 00:53:15.283 - [INFO] update xt_server v3.xx-net.net:443
Oct 06 00:53:15.283 - [INFO] request_balance host:v3.xx-net.net port:443 balance:0.000000 quota:310241856425.000000
Oct 06 00:53:48.811 - [WARNING] login session fail, status:500
Oct 06 00:53:48.811 - [WARNING] x-tunnel login_session fail, session not start

**Comment by lndnxp** [comment]
@xxnet 找到個網址 也不知有用沒用 [https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows](https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows)
感謝老大辛苦開發

**Comment by mooredam** [comment]
仍然无法登陆，3.6.7
@xxnet

![default](https://user-images.githubusercontent.com/13420372/31246670-b7241338-aa40-11e7-85c5-de46659e8603.png)

**Comment by jon945** [comment]
还是登陆不了，仍然显示api:/login fail:status:500 t:254，大大今天再看看吧

**Comment by yuyistar** [comment]
看见晚了，，已经充值了。有影响吗

**Comment by chenzijng** [comment]
Get Fail:session server login fail:500，怎么今天还是不行x-tunnel

**Comment by xxnet** [comment]
暂时x-tunnel 无法使用

**Comment by wicatu** [comment]
借道问xxnet一个技术问题，日志提示
fail:'module' object has no attribute 'dump_publickey' ，像是pyopenssl的版本出问题了

System Platform | armv7l, Linux-4.9.52-v7+-armv7l-with-debian-8.0
OpenSSL Version | 0.13.1 TLSv1

**Comment by xxnet** [comment]
​这个api有些 OpenSSL不支持，要升级python-openssl 库。
下一个版本会先判断有没有这个api

**Comment by QGB** [comment]
Get Fail:session server login fail:500

@xxnet

**Comment by xxnet** [comment]
​这是网络不通，目前服务器正常。
