### ISSUE TITLE
分享可以暂时使用6to4解决IP问题

### ISSUE THREAD

**Issue by PHPtits** [XX-net/XX-Net#6880]
先来个截图, 我的Win10, 电信网络
![enter image description here](https://github.com/PHPtits/gaeimg/blob/41c4741d076afea37c12d102690afff35ee78abc/0.gif?raw=true)

按Win+R, 输入gpedit.msc 打开本地策略组
![enter image description here](https://github.com/PHPtits/gaeimg/blob/41c4741d076afea37c12d102690afff35ee78abc/1.gif?raw=true)

然后打开到图片的这个地方, 按图片的设置启用项目就好
![enter image description here](https://github.com/PHPtits/gaeimg/blob/41c4741d076afea37c12d102690afff35ee78abc/2.gif?raw=true)

双击项目后点启用
![enter image description here](https://github.com/PHPtits/gaeimg/blob/41c4741d076afea37c12d102690afff35ee78abc/3.gif?raw=true)

最后xx里开启IPV6
![enter image description here](https://github.com/PHPtits/gaeimg/blob/41c4741d076afea37c12d102690afff35ee78abc/4.gif?raw=true)

**Comment by AmelieNet** [comment]
家里只有IPv6能用这个选项吗?

**Comment by sofaonsale** [comment]
win7 不行啊

**Comment by hzx505** [comment]
状态内容大概同你一样。就是ipv6连接老是自己断开，只能拨掉网线重新连接。
能连接ipv6的持续时间不长，大约几十分钟吧。

请问，这种6to4是什么作用力

**Comment by hzx505** [comment]
补充下：win10 和 Mac 都一样，是联通网络，不知是路由器问题还是什么？

**Comment by PHPtits** [comment]
@AmelieNet IPV6直接在XX里设置就好了,,

@sofaonsale Win7也应该是一样,,只要是专业版

@hzx505 我这边是IPV4..所以只能用6to4..看YouTube..1080P没有卡,,,

**Comment by neunundneunzig** [comment]
说我的网络不支持IPV6……

**Comment by PHPtits** [comment]
@neunundneunzig  6to4隧道本身不需要自己的网络是IPV6, 电脑开启后就可以了...开启6to4后重启式式...刚人在一台Win7虚拟机上也同样成功..

**Comment by AlyoshaMa** [comment]
@PHPtits  Yep！ Thanks！！！

**Comment by DyingLight100** [comment]
我是路由器拨号，需要选“局域网代理”吗？win10

**Comment by wantno** [comment]
你为什么这么牛逼啊！！！！！我的好使了。强。

**Comment by WLZLCX** [comment]
留名

**Comment by myjlpt** [comment]
@PHPtits 你的Teredo服务器是????????????????

**Comment by lon91ong** [comment]
启用IPv6失败，请确认你的网络支持IPv6。

**Comment by bitternolis** [comment]
启用IPv6失败，请确认你的网络支持IPv6。

**Comment by yuyistar** [comment]
是不是要开启本地网络里面的ipv6

**Comment by mgdgfbhevdyeh** [comment]
启用IPv6失败，请确认你的网络支持IPv6。

**Comment by toobed** [comment]
启用IPv6失败，请确认你的网络支持IPv6。

**Comment by dzxion** [comment]
启用IPv6失败，请确认你的网络支持IPv6

**Comment by corsowei** [comment]
我用macbook的，怎么开IPV6？

**Comment by xiaoyinping** [comment]
谢谢啦，真的可以

**Comment by latinpegasus** [comment]
启用IPv6失败，请确认你的网络支持IPv6

**Comment by ppskt** [comment]
不支持ipv6，是网络的问题还是路由器不支持？

**Comment by dfefefef** [comment]
win非专业版用户（家庭版）在开启6to4时，直接在命令提示符输入：netsh interface 6to4 set state enabled回车就行，然后再在xxnet配置里面开启ipv6.

**Comment by AmelieNet** [comment]
这个功能是不是必须有路由器支持啊?如果路由器不支持是不是不能6to4?

**Comment by moesora** [comment]
教育网才有ipv6 电信联通都只有ipv4

**Comment by astonetwobirds** [comment]
我就想问一下楼上们的，你们有没有按楼主的尝试？

**Comment by PHPtits** [comment]
这里集中回复一下.我也不是什么高手..只是在大大门提出IPV6可以使用.才去百度出来开6to4方法..
我的Win10是正版的专业版..是之前Win7D版免费升级来的..
我的网络是100m电信光纤..IPV4..有公网IP(没啥关系), 
普通的智能路由..也基本是默认设置..和路由器也没什么关系..
6to4就是把IPV6的数据通过IPV4走..是一种IPv4到IPv6的过渡解决方案
如果还是提示" 启用IPv6失败" 请确认能正常的开启...还有就是可以百度一下..

**Comment by lxwin** [comment]
终于连上了，之前按另一篇开启IPV6方式没成功，差了最后的启用6to4。没IPV4 IP的估计用这种方式都是可以的。
