### ISSUE TITLE
开启v6后可以用，但是提示检测代理设置，同时证书一直显示fail

### ISSUE THREAD

**Issue by royklaas** [XX-net/XX-Net#6888]
升级新版本后证书状态一直没OK过，按照wiki和之前的#issue5322里提到的方式初始化后还是不行（去certmgr.msc和certlm.msc删后重新初始化）。xtunnel也无法登陆。

按照之前某个issue里提到的使用组策略gpedit里启用6to4后，开启xxnet的ipv6后似乎可以正常使用，但是状态提示一直出错，显示：请检查浏览器代理设置。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.7

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12545 good:10380
network-status: OK
connected-link: new:0 used:0
worker: h1:12 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by wangfeng769** [comment]
Ctrl+F5强制刷新就好了

**Comment by TeslaHua** [comment]
把原来证书删了，重新导入一下证书，就是双击start.vbs

**Comment by royklaas** [comment]
好吧。之前试了那么多次都没行。现在ctrl+f5就好了。可能之前因为没有连接上吧

**Comment by biggg007** [comment]
我的也一样的问题，但是按了刷新之后还是不行。为什么？
