### ISSUE TITLE
咱这teredo服务器全部挂了，你们那情况如何？

### ISSUE THREAD

**Issue by Just2co** [XX-net/XX-Net#6891]
江西电信光纤宽带，昨天上午正常使用teredo隧道，开启IPV6，今天起来之后，就用不了了，ping teredo隧道服务器，断断续续，发现被强力干扰了，连续换了好几个teredo服务器都这样，本来指望着可以利用这个隧道，度过封锁期，结果还是落空了，大家那情况咋样？还有能正常用的没？

**Comment by mkhsj927** [comment]
sichuan 表示不行

**Comment by FL1399** [comment]
我一样的情况，只有挨个换了测试，好不容易找到一个通的结果IP只有20来个...

**Comment by xyq168370** [comment]
河北联通
刚刚ping了一下teredo.remlab.net服务器，还是能用，延迟也不算高。
然而并没有什么用，xxnet依然显示“尚未建立连接”

**Comment by mkhsj927** [comment]
ivp6都不能用

**Comment by Zmm1977** [comment]
那几台teredo服务器完全就是活靶子啊

**Comment by BLACKFLAGX** [comment]
我觉得应该是这几天teredo服务器流量过大，服务器直接限制了这个地区的连接！

**Comment by Just2co** [comment]
@BLACKFLAGX 非也，teredo仅仅相当于是DHCP而已，而teredo中继节点是不可见的，类似于承载实际跳板节点的TOR节点，所以中继节点无法封锁的，能封的只有有限的teredo服务器。

**Comment by wz7465** [comment]
中继节点一样能封，虽然客户端看不到，但在网络上中继节点都是以2001开头宣告的

**Comment by myjlpt** [comment]
kill 2001:*:*：：*??????????????

**Comment by wz7465** [comment]
不存在误伤问题

**Comment by tislam8888** [comment]
我这里也是

**Comment by caizzoo** [comment]
被封完了？！

**Comment by xiaomozhang** [comment]
我这显示也是,刚好使了一阵子,teredo服务器一连接不上立刻ip就显示为0了,重启好几次都不好使~~

**Comment by Just2co** [comment]
Leaved
