### ISSUE TITLE
下了最新的版本，但是点开了start.bat后提示“no enough ip”

### ISSUE THREAD

**Issue by spookhouse** [XX-net/XX-Net#6895]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
xxnet-version: 3.6.8

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by liangliangge521** [comment]
什么版本现在都不好使，只能等到官方修复

**Comment by spookhouse** [comment]
我原来3.5.5发现不能用了，然后升级也不行，就全部删除了想要重新安装一遍。是不是说要过一阵的，那我原来的项目ID还能用吗？还是全部要重新申请？
