### ISSUE TITLE
修复后，如果再次安装XX-net 需要新申请APPid吗

### ISSUE THREAD

**Issue by spookhouse** [XX-net/XX-Net#6899]
我原来3.5.5发现不能用了，然后升级也不行，就全部删除了想要重新安装一遍新版本。是不是说要过一阵的等待官方修复后我再重新安装设置，那我原来的项目ID还能用吗？还是全部要重新申请？

**Comment by TeslaHua** [comment]
不需要，可以用

**Comment by tq08rsu** [comment]
应该不需要部署了都部署完了
