### ISSUE TITLE
问一下开发者，为什么不用goagent最新版本呢？

### ISSUE THREAD

**Issue by ugvf2009** [XX-net/XX-Net#69]
小白，不懂技术，弱弱的问一下。

**Comment by xxnet** [comment]
早期的版本代码结构简单，容易改，就从早期的版本改过来的。
新版确实修复了一些问题，要用新版本，需要再花些精力去研究。。。

**Comment by cobob** [comment]
我感觉当前版本已经很好用了，没有必要太刻意的追求版本。
我MAC系统使用的是1.2.1版本，开机只要打开Terminal激活一下就可以直接关闭窗口使用到关机为止。
感谢作者的奉献。

**Comment by xxnet** [comment]
XX-Net 1.7.0 发布，用上新版goagent协议了，确实解决了几个问题。
向Phus Lu致敬！
