### ISSUE TITLE
登不上啊 (╯‵□′)╯︵┻━┻

### ISSUE THREAD

**Issue by dirtyluke** [XX-net/XX-Net#6904]
今天回来就登不上了，然后换了3.6.7，还是不行，然后换了3.6.8，还是不行，状态页显示请等待大约2小时，XX-Net需要扫描IP。自家用的guizhou电信，IPV6不知道，没用过，这边也可能没有，尝试中....

诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.6.8

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

日志信息：
Oct 06 12:59:15.530 - [INFO] SSL use version:TLSv1_2
Oct 06 12:59:15.765 - [DEBUG] network is ok, cost:481 ms
Oct 06 12:59:16.009 - [INFO] OpenSSL support alpn
Oct 06 12:59:16.010 - [INFO] load ip range file:G:\\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\local\ip_range.txt
Oct 06 12:59:16.041 - [INFO] Use google ip range.
Oct 06 12:59:16.042 - [INFO] load google ip_list num:0, gws num:0
Oct 06 12:59:16.045 - [INFO] OpenSSL support alpn
Oct 06 12:59:16.048 - [WARNING] no enough ip
Oct 06 12:59:16.053 - [DEBUG] ## GAEProxy set keep_running: True
Oct 06 12:59:16.054 - [INFO] ------------------------------------------------------
Oct 06 12:59:16.054 - [INFO] Python Version : 2.7.13
Oct 06 12:59:16.054 - [INFO] OS : Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Oct 06 12:59:16.054 - [INFO] Listen Address : 127.0.0.1:8087
Oct 06 12:59:16.054 - [INFO] GAE APPID :
Oct 06 12:59:16.054 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Oct 06 12:59:16.055 - [INFO] ------------------------------------------------------
Oct 06 12:59:16.549 - [WARNING] no enough ip
Oct 06 12:59:17.050 - [WARNING] no enough ip
Oct 06 12:59:17.561 - [WARNING] no enough ip
Oct 06 12:59:17.562 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Oct 06 12:59:17.580 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=b4d201f3-df0d-4058-b017-c98de330b14b&version=3.6.8&platform=Windows-8.1-6.3.9600
Oct 06 12:59:18.063 - [WARNING] no enough ip
Oct 06 12:59:18.564 - [WARNING] no enough ip
Oct 06 12:59:19.065 - [WARNING] no enough ip
Oct 06 12:59:19.566 - [WARNING] no enough ip
Oct 06 12:59:20.067 - [WARNING] no enough ip
Oct 06 12:59:20.569 - [WARNING] no enough ip
Oct 06 13:00:16.065 - [DEBUG] create ssl timeout fail.
Oct 06 13:00:16.067 - [WARNING] no enough ip
Oct 06 13:00:16.569 - [WARNING] no enough ip
Oct 06 13:00:17.070 - [WARNING] no enough ip
Oct 06 13:00:17.572 - [WARNING] no enough ip
Oct 06 13:00:17.588 - [DEBUG] create ssl timeout fail.
Oct 06 13:00:18.073 - [WARNING] no enough ip
Oct 06 13:00:18.574 - [WARNING] no enough ip
Oct 06 13:00:19.075 - [WARNING] no enough ip
Oct 06 13:00:19.576 - [WARNING] no enough ip
Oct 06 13:00:20.079 - [WARNING] no enough ip
Oct 06 13:00:20.582 - [WARNING] no enough ip
Oct 06 13:01:16.088 - [DEBUG] create ssl timeout fail.
Oct 06 13:01:16.089 - [WARNING] no enough ip
Oct 06 13:01:16.592 - [WARNING] no enough ip
Oct 06 13:01:17.092 - [WARNING] no enough ip
Oct 06 13:01:17.594 - [WARNING] no enough ip
Oct 06 13:01:18.096 - [WARNING] no enough ip
Oct 06 13:01:18.597 - [WARNING] no enough ip
Oct 06 13:01:19.099 - [WARNING] no enough ip
Oct 06 13:01:19.600 - [WARNING] no enough ip
Oct 06 13:01:20.101 - [WARNING] no enough ip
Oct 06 13:01:20.602 - [WARNING] no enough ip

**Comment by onplus** [comment]
Windows都能开teredo， ISP只是影响隧道质量

**Comment by dirtyluke** [comment]
刚刚搜了一下你说的teredo，网上的指导方法还是没法转换成IPV6，有资料有步骤吗

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/常见问题索引
https://github.com/XX-net/XX-Net/issues/6589
