### ISSUE TITLE
no gws ip

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#692]
| Property              | Value                                                                                                       |
| ----------------------|-------------------------------------------------------------------------------------------------------------|
| XX-Net Version        | 2.0.5                                                                                                       |
| Google IP num         | 102                                                                                                         |
| 100th IP handshake(ms)| 1742                                                                                                         |
| connected link        | 0,1                                                                                                         |
| scaning ip thread num | 50                                                                                                          |
| block stat            | OK                                                                                                          |

**ISP: 杭州电信**

不过好像无伤大雅. (连接貌似不太稳定的样子)
不过我想知道gws IP是什么 0 0

**Comment by zjhzxhz** [comment]
Log 差不多就是:

```
Jul 21 20:17:57 - [WARNING] no gws ip
Jul 21 20:17:58 - [WARNING] no gws ip
Jul 21 20:17:59 - [WARNING] no gws ip
Jul 21 20:17:59 - [DEBUG] create_ssl update ip:128.0.86.227 time:1733
Jul 21 20:18:00 - [WARNING] no gws ip
Jul 21 20:18:01 - [WARNING] no gws ip
Jul 21 20:18:02 - [WARNING] no gws ip
Jul 21 20:18:03 - [DEBUG] get ip:128.0.86.227 t:800
Jul 21 20:18:04 - [WARNING] no gws ip
Jul 21 20:18:04 - [DEBUG] sort ip time:3998ms
Jul 21 20:18:05 - [WARNING] no gws ip
Jul 21 20:18:05 - [WARNING] no gws ip
Jul 21 20:18:06 - [WARNING] no gws ip
Jul 21 20:18:07 - [WARNING] no gws ip
Jul 21 20:18:08 - [WARNING] no gws ip
Jul 21 20:18:08 - [DEBUG] create_ssl update ip:128.0.86.227 time:684
```

**Comment by xxnet** [comment]
每个ip限制的使用频率，所以如果每个ip刚用过，还需要建立连接，就会出现no gws ip的提示。

2015-07-21 20:18 GMT+08:00 Howard Shieh <notifications@github.com>:

**Comment by wz2326** [comment]
多申请些专案ID就可以解决吗

**Comment by xxnet** [comment]
跟专案ID没有关系，还是等扫描更多ip吧

2015-07-28 9:49 GMT+08:00 mangocool <notifications@github.com>:

**Comment by wz2326** [comment]
ip扫描xxnet自己会操作吧

**Comment by tinterking** [comment]
为什么全是 fail                     not support GAE, server type:这个是怎么了
Sep 06 11:03:26 - [DEBUG] create_ssl 111.168.255.49 fail:timed out cost:2000 h:0
Sep 06 11:03:26 - [WARNING] IP:210.245.14.218 not support GAE, server type:
Sep 06 11:03:26 - [DEBUG] create_ssl 64.233.179.91 fail:timed out cost:2002 h:0
Sep 06 11:03:26 - [WARNING] IP:210.245.14.203 not support GAE, server type:
Sep 06 11:03:27 - [DEBUG] create_ssl 74.125.194.201 fail:timed out cost:2004 h:0
Sep 06 11:03:27 - [DEBUG] get ip:123.205.251.82 t:972
Sep 06 11:03:27 - [DEBUG] GAEProxy Web_control 127.0.0.1:9689 GET /deploy?cmd=get_log
Sep 06 11:03:27 - [DEBUG] get ip:58.145.238.35 t:972
Sep 06 11:03:27 - [WARNING] IP:64.233.162.86 not support GAE, server type:
Sep 06 11:03:27 - [INFO] remove ip:64.233.162.86 left amount:2996 gws_num:2996
Sep 06 11:03:27 - [DEBUG] get ip:128.0.169.229 t:972
Sep 06 11:03:28 - [DEBUG] get ip:208.117.254.100 t:973
Sep 06 11:03:28 - [WARNING] IP:64.233.162.86 not support GAE, server type:
Sep 06 11:03:28 - [DEBUG] GAEProxy Web_control 127.0.0.1:9692 GET /deploy?cmd=get_log

**Comment by xxnet** [comment]
这是新的情况，2.2.0 已经修复，但2.2.0 的连接性能不好，待发新版解决

2015-09-06 11:25 GMT+08:00 tinterking <notifications@github.com>:

**Comment by tinterking** [comment]
那以前的版本呢,  这个问题有没有

2015-09-06 11:48 GMT+08:00 Michael.X <notifications@github.com>:

**Comment by xxnet** [comment]
新版 2.3.0 发布，改进连接策略，请测试，使用效果请反馈，谢谢

2015-09-07 10:59 GMT+08:00 tinterking <notifications@github.com>:

**Comment by tinterking** [comment]
还是不够稳定,速度也有点慢  加载不全

2015-09-07 15:36 GMT+08:00 Michael.X <notifications@github.com>:

**Comment by xxnet** [comment]
你是什么地区，什么网络运营商？

把状态页贴出来看看

2015-09-07 18:02 GMT+08:00 tinterking <notifications@github.com>:

**Comment by tinterking** [comment]
听你这么一说  感觉是我搞得有问题  又重新弄了下 好了

2015-09-07 18:10 GMT+08:00 Michael.X <notifications@github.com>:
