### ISSUE TITLE
XX

### ISSUE THREAD

**Issue by rainplus** [XX-net/XX-Net#6920]

**Comment by onplus** [comment]
如果你只是看看pornhub，安全

**Comment by MadMaxPayne8964** [comment]
goagent原项目里已经明确说明了：非匿名工具，切勿作大死。反正我只用Google搜搜资料，油管上看看youku上也能看的视频（无广告），从没考虑过安全性问题

**Comment by rainplus** [comment]
@onplus  @MadMaxPayne8964  非匿名工具，X-tunel有个人的访问历史?看了一下油管上关于最近FQ的评论，感觉都是有挂的节奏。。

**Comment by onplus** [comment]
x-tunnel有一定匿名作用

但显然你没有足够的匿名意识，匿名不是用一两个工具就能做到的
