### ISSUE TITLE
W

### ISSUE THREAD

**Issue by Xrunes** [XX-net/XX-Net#6921]
* closed by Python/3.8.6 Github-Bot/0.2, reason: empty content, you can call me to reopen it after write issue content.

**Comment by paladiners** [comment]
我觉得可能不会，这不单单是为了一个会，而是逐渐扎紧口袋的过程，恰恰相反，会是起点，不是终点。

**Comment by rainplus** [comment]
感觉不会，昨天看了最近的言论。是要彻底查封个人的FQ行为。。

**Comment by onplus** [comment]
GFW的资源是有限的。

我的梯子没受到一点影响，甚至可能因为最近出国流量少了，感觉速度还变快了（？？？）

**Comment by lndnxp** [comment]
盜國賊們表示這讓我很難辦啊

**Comment by toobed** [comment]
@paladiners 同意，频繁的各种网络安全法，各种实名制，对美访问也是重点谈的内容。他们肯定是意识到，对于统治稳定性来说，最大甚至唯一的威胁来自于网络传播作用和信息透明，只要拥有绝对的信息传播封锁和控制，只要经济不崩溃，可保千秋万代的绝对统治。所以这个是比100艘航母都更重要的头号大事。

**Comment by lndnxp** [comment]
@onplus 我還能肉翻 所以我應該毫不在乎?

**Comment by paladiners** [comment]
@onplus 那仅仅是因为，这有一个试探的过程。想当年SS也有人说很难封，结果最后连作者被吃牢饭了。总有一天，一旦算法能够筛选出他们需要筛选的人或者有一天他们觉得宁可错杀也不该放过的时候，没人是无辜的。

**Comment by onplus** [comment]
@ ALL  无所谓啊，反正xx-net不是我写出来的。

南望王师又一年，王师还剩几个连

你们的口号要喊到什么时候呢

**Comment by xyz8899** [comment]
这是开始，应该会形成常态，以后最好的办法是用付费的VPN

**Comment by roc1010kmt** [comment]
那得看他這會開成什麼樣子。

**Comment by ryu2gaku** [comment]
我是持有一种悲观的态度的，
泽茗时代不太清楚，毕竟那是我没电脑也没手机。
经历过老胡时代的 vpn 可以随便翻，
到袭帝时代网络渐渐封闭，vpn 越来越少到后来甚至是全都挂掉（壮哉我 greenvpn）
ss 也很悲观
所有的一切都是朝着朝鲜模式看齐（新闻现在歌功颂德的内容真的多到夸张啊）
能怎么办，我也很绝望

![131276886](https://user-images.githubusercontent.com/13306587/31304044-6fe8815e-aade-11e7-9208-06dd82a6a10b.jpg)

**Comment by krollMJ** [comment]
@onplus 你这种人，不悲天悯人就算了，连善恶都不分了，还能算是人吗？
【反正xx-net不是我写出来的】，这种猪狗不如的话，你也说得出口？！
告诉你，按照共产党，历次杀人运动的定罪标准，接触私藏使用的下场，不会好多少。
多看看历史，在消息极度封锁的时代，柏林墙是不是倒了。苏联是不是被干趴了。纳粹战犯是不是被摩萨德追杀到天涯海角。

**Comment by TRY666** [comment]
嗯，有本事可以游太平洋嘛。

**Comment by onplus** [comment]
@krollMJ
你也只会嘴里BB悲天悯人了。
睁大你的眼睛，好好看看我给xx-net做了什么，你做了什么

**Comment by xxnet** [comment]
​大家不必因为一点小事争吵，做正事。

有办法的注册些云前端CDN帐号发给我，我来研究。
可参考
https://trac.torproject.org/projects/tor/wiki/doc/meek

**Comment by BlankWhite** [comment]
不会的 只会越来越遭 fxxk chn gov

**Comment by rocke** [comment]
@xxnet  请问注册了的云前端CDN账号怎么发给你？

**Comment by xxnet** [comment]
​发邮件到：
xxnet.dev@gmail.com

感谢！

**Comment by lndnxp** [comment]
這是要上tor的節奏嗎 看來這次確實夠絶的

**Comment by zxk7516** [comment]
只要国外说中文的不要操心墙内的事, 就什么都好.  我对政府没有什么想批评的.
