### ISSUE TITLE
2.0.5自动翻墙？

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#693]
2.0.5版本 设置选的取消全局代理，Switchysharp选直接连接，chrome还可以直接上谷歌，反倒是Switchysharp选择goagent谷歌打不开。。

**Comment by xxnet** [comment]
看看XX-Net日志有没有收到访问google的日志？
多试几次

在 2015年7月21日 下午8:20，cdmask <notifications@github.com>写道：

**Comment by cdmask** [comment]
现在Switchysharp选goagent可以用了，可以看到日子有访问谷歌，但是关掉选择直接连接还是可以访问谷歌，并且在xx-net日志里面看不到访问谷歌日志，全是查找ip的提示。

**Comment by xxnet** [comment]
恭喜，试试关掉xx-net，哈哈

在 2015年7月21日 下午8:32，cdmask <notifications@github.com>写道：

**Comment by cdmask** [comment]
已经关掉了。。还是可以上谷歌--

**Comment by cdmask** [comment]
不过只能搜索搜索，youtube scholar啊都不行的。还是开叉叉吧～

**Comment by xxnet** [comment]
你是什么网络？教育网吗？

2015-07-22 10:31 GMT+08:00 cdmask <notifications@github.com>:

**Comment by cdmask** [comment]
嗯 学校的
