### ISSUE TITLE
跪求！帮忙通过heroku机器人验证!

### ISSUE THREAD

**Issue by zeitgeist8080** [XX-net/XX-Net#6934]
如题，跪谢！

**Comment by equinox-flower** [comment]
herokuapp？

**Comment by nly4lov** [comment]
https://signup.heroku.com/?c=70130000001x9jEAAQ
？

**Comment by nly4lov** [comment]
人机验证我倒是过了，但是“The domain qq.com has been blocked.”

**Comment by zeitgeist8080** [comment]
@nly4lov  感谢你！ 对的，https://signup.heroku.com/?c=70130000001x9jFAAQ ，换 lqqlovezy@sina.com 可以吗？ 国内不知道还有什么邮箱域名可以用。

**Comment by touchtop** [comment]
@zeitgeist8080 check your mailbox... :)

**Comment by gggccc44** [comment]
试试foxmail呢，也是qq的，在qq邮箱里面设置就行，貌似国外很多屏蔽qq。com的邮箱，因为很多用来发广告，还有微软的live。com邮箱

**Comment by zeitgeist8080** [comment]
@touchtop 已经收到了，但是还是点不了，https://id.heroku.com/account/accept/4969775/9d35c7c382219a2556cf70dc9ec550d1

**Comment by zeitgeist8080** [comment]
@gggccc44 看来新浪的可以

**Comment by zeitgeist8080** [comment]
邮件确认链接也需要翻墙，没有翻墙软件，看来真的很难注册，暂时放弃HEROKU，如果有好心人帮忙操作，愿意告知邮箱密码，私聊 QQ 94374903

**Comment by nly4lov** [comment]
Almost there...

Please check your email (lqqlovezy@sina.com) 
to confirm your account.

If lqqlovezy@sina.com is not your email address, please go back and enter the correct one.

If you haven't received our email in 15 minutes, please check your spam folder.

If you still haven't received it, please email us.
