### ISSUE TITLE
看着只有两个IP，觉得好担心，好忧桑

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#6937]
> XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.8

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:500 good:2
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:2
scan-ip-thread-num: 10
ip-quality: 186
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by nly4lov** [comment]
虽然也能翻，翻得还挺快，但我想这两个好的IP如果也玩蛋了，不就翻不了了吗？

**Comment by hhp99** [comment]
用IPV6，IPV6有成千上万个IP，看youtube 720p没有问题

**Comment by higoge** [comment]
我一个都木有了

**Comment by nly4lov** [comment]
@hhp99 我用不了，设置时说让我确认我的网络支持6.
@higoge 哈哈![e104](https://user-images.githubusercontent.com/11325411/31304261-7965587a-ab50-11e7-9695-ac9c894deb36.png)

**Comment by Parlin-Galanodel** [comment]
我试着不开ipv6扫了两天，一个ip都没有。。。

**Comment by hhp99** [comment]
@nly4lov  首先是宽带提供商要支持IPV6，然后是你的操作系统要支持IPV6，最后是你家里的局域网要支持IPV6，国内绝大多数路由器都不支持IPV6，把路由器改成集线器就解决了

**Comment by yuanchang2018** [comment]
哪两个，发出来，嘻嘻

**Comment by onplus** [comment]
@hhp99 你先查一下百科行不行。ipv6隧道需要这些支持？

**Comment by hhp99** [comment]
@onplus 与隧道无关，隧道是ipv4的封装包，我说的是完全的，真正的ipv6

**Comment by zpzpzp88** [comment]
除了教育网，一般人哪来的真正IPV6

**Comment by nly4lov** [comment]
@hhp99 宽带提供商电信，我们是100M企业光纤，应该是支持的；
我操作系统是win10，应该也支持IPV6；
最后是厂里的局域网，这个估计就完蛋了，全是垃圾路由器。

**Comment by nly4lov** [comment]
@yuanchang2018 不![11](https://user-images.githubusercontent.com/11325411/31304944-c75563e4-ab60-11e7-9bf9-cdb63b9c6011.gif)

**Comment by hhp99** [comment]
@nly4lov 问题就再你的局域网上，公司的局域网没办法，你改不来，只能是用隧道，如果是家里的小路由，直接把路由改成集线器就解决了，再路由控制软件中关掉DHCP功能，把LAN口的地址改成不要和光纤路由冲突，然后光纤出来的网线不要插WAN口，直接LAN口就解决了，集线器相当于对上层路由透明，只起到扩展和级联的作用

**Comment by hhp99** [comment]
@zpzpzp88 现在电信联通之类的都是光纤入户，千兆口都同时支持IPV6和IPV4协议，基本上问题出在家用的无线路由上

**Comment by nly4lov** [comment]
@hhp99 我是三级路由器,二级的都能进,一级的不知道用户名和密码.

**Comment by whz14** [comment]
> 用IPV6，IPV6有成千上万个IP，看youtube 720p没有问题

你好问一下，我有原生的IPV6也用不了啊，是为什么呢？缺了哪里的配置吗，还是需要更新哪个表？

**Comment by nly4lov** [comment]
@whz14 
GAEPROXY-ADVANCED-SCAN SETTINGS 
Auto-adjust scan thread count: On
IP Mode: Auto

**Comment by whz14** [comment]
> @whz14
> GAEPROXY-ADVANCED-SCAN SETTINGS
> Auto-adjust scan thread count: On
> IP Mode: Auto

我是这样的设置也不行啊。应该是我缺了IP列表，lz可以分享一下吗
