### ISSUE TITLE
fail:'module' object has no attribute 'dump_publickey' cost:2245 h:0

### ISSUE THREAD

**Issue by netfun2000** [XX-net/XX-Net#6945]
XX-Net Status:

sys-platform: armv6l, Linux-4.9.35+-armv6l-with-debian-8.0
os-system: Linux
os-version: #1014 Fri Jun 30 14:34:49 BST 2017
os-release: 4.9.35+
os-detail: Dist:debian; Version:8.0; ID:
architecture: 32bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.6.7

python-version: 2.7.9
openssl-version: 0.13.1 TLSv1 h2:no

ipv6-status: 1
gws-ip-num: total:12347 good:11177
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 1
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

树莓派，开启IPV6后，似乎无法使用IPV6的IP连接。
查看日志提示：
fail:'module' object has no attribute 'dump_publickey' cost:2245 h:0

**Comment by netfun2000** [comment]
在WIN10上运行XX-NET没有问题。

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/issues/6871

**Comment by netfun2000** [comment]
谢谢。
