### ISSUE TITLE
XX-Net 自己好了

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#6950]
扫了一天IP，突然好了。目前可用IP400多，google, google scholar, youtube访问速度都很快。

别问我怎么办的。我什么也没办。希望这是个普遍的和持久的现象。

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.7

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:102
network-status: OK
connected-link: new:8 used:0
worker: h1:2 h2:16
scan-ip-thread-num: 9
ip-quality: 423
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yaojun1314** [comment]
这是哪儿的网？

**Comment by Fuckingcoming** [comment]
我和楼主一样，我是17:30打开的XXNET，然后发现能扫了，扫了几百个打开顺畅无比..
然后与17:54分就扫不到了IP又归零...延迟9999呵呵..我还以为墙倒了结果只是玩玩而已...

**Comment by farshidvahid** [comment]
又不行了。持续了10分钟吧。靠。
