### ISSUE TITLE
您的连接不是私密连接。各种方法都试过了！！！

### ISSUE THREAD

**Issue by 0101777** [XX-net/XX-Net#6953]
重装了系统之后，安装XX-NET了，一直出现这个问题，包括win10自带的浏览器、chrome都是这样，打开斗鱼、贴吧之类的网站全部提示“您的连接不是私密连接”

现在XX-NET用不了了，关掉了，还是不行。

试过删除证书，删除ca文件夹等，重新部署，版本也是最新的。还是出现同样问题。。

重新安装了chrome，重置了网络设置，还是不能解决
有没有大大帮忙解决下，我不想再重装系统了。。。

**Comment by 0101777** [comment]
刚又试过把所有证书删除重启，还是不行。。

**Comment by xxnet** [comment]
提示不是私密连接，看看证书是谁颁发的。

如果是XX-Net，那么说明系统内还运行着XX-Net，启动任务管理器，找到pythonw进程，关掉。

在IE的设置里，找系统代理设置，是不是指向 8087端口，关掉。

**Comment by 0101777** [comment]
找到
