### ISSUE TITLE
按照帖子里各个大佬的执行下去还是无法开启ipv6

### ISSUE THREAD

**Issue by TOBOM** [XX-net/XX-Net#6963]
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
执行到这部就说文件名、目录名或卷标语法不正确。
尴尬

**Comment by LucyyHH** [comment]
后面双引号里的那串英文需要换成你自己的，一般是“本地连接* ”+一串数字，教程里说了怎么获取这个了，仔细看看吧

**Comment by 13130110047** [comment]
请问哪里有教程？

**Comment by Etzan** [comment]
或者用下面这条命令查询 本地连接* 的 Idx 替代 ”Teredo Tunneling Pseudo-Interface“
``netsh int ipv6 show route
参考[简书](http://www.jianshu.com/p/1433dd30f45a)

**Comment by miss13** [comment]
很简单的 ，开启了之后爽到爆。Ubuntu不用什么设置，一句，命令直接开启。很方便

**Comment by safarishi** [comment]
在我的 mac 下提示找不到 netsh 命令~

**Comment by miss13** [comment]
也许命令不一样，Ubuntu也是不一样的。
________________________________

**Comment by klcb2010** [comment]
求Win7开启教程@miss13

**Comment by miss13** [comment]
没有Win7系统，应该差不多cmd就好了不用powershell
________________________________
