### ISSUE TITLE
使用X-Tunnel无法联网

### ISSUE THREAD

**Issue by L-M-Sherlock** [XX-net/XX-Net#6970]
X-Tunnel有流量，但是没法连接任何网站。
日志里一直重复一下内容
Oct 08 00:41:54.836 - [WARNING] roundtrip time:114466 transfer_no:97 send_sn:97 send:43 status:500 retry:1
Oct 08 00:41:55.320 - [DEBUG] roundtrip time:33680 cost:5010 transfer_no:109 send_sn:109 send:33 recv_sn:0 rcv:11 status:200
Oct 08 00:41:55.321 - [WARNING] rtt:28670 speed:0 trace: 0:connect, 643:init, 0:head, 314:head end, 52:request, 2246:Res, 0:request, 5254:Res, 2:request, 5766:Res, 0:request, 15462:Res, 2:request, 307:Res, 2:request, 5345:Res, 0:request, 309:Res, 2:request, 4684:Res, 1:request, 5253:Res, 2:request, 250:Res, 2:request, 1227:Res, 2:request, 5260:Res, 3:request, 5269:Res, 3:request, 5078:Res, 2:request, 5257:Res, 2:request, 604:Res, 2:request, 5258:Res, 2:request, 15563:Res, 0:request, 5256:Res, 2:request, 740:Res, 2:request, 5253:Res, 0:request, 5266:Res, 2:request, 4854:Res, 1:request, 5322:Res, 1:request,:1, processed:24, transfered:22488
Oct 08 00:41:55.321 - [WARNING] task trace:0:start_request,27921:get_task(0),430:get_worker:104.25.137.56,1:h1_req,0:h1_req_sended,5322:response_begin,0:h1_get_head,0:h1_finish[SP:2],0:get_response,:3
Oct 08 00:41:55.322 - [DEBUG] block for none
Oct 08 00:41:55.546 - [DEBUG] Conn session:nfqylorv conn:58 stop:recv fail.
Oct 08 00:41:55.546 - [DEBUG] start roundtrip transfer_no:164 send_data_len:25 ack_len:0
Oct 08 00:41:55.547 - [DEBUG] remove conn_id:58
Oct 08 00:41:55.838 - [DEBUG] start roundtrip transfer_no:97 send_data_len:43 ack_len:0
Oct 08 00:41:59.701 - [DEBUG] Conn session:nfqylorv conn:59 stop:recv fail.
Oct 08 00:41:59.702 - [DEBUG] start roundtrip transfer_no:165 send_data_len:25 ack_len:0
Oct 08 00:41:59.703 - [DEBUG] remove conn_id:59
Oct 08 00:42:00.101 - [DEBUG] roundtrip time:38460 cost:5004 transfer_no:110 send_sn:110 send:38 recv_sn:0 rcv:11 status:200
然后Cloudflare front Log里面一直有' certficate is none'
Oct 08 00:44:04.378 - [WARNING] h1 head send len:0 39 104.20.73.129
Oct 08 00:44:04.379 - [WARNING] 104.20.73.129 trace: 0:connect, 4285:init, 1:head,:4203, processed:0, transfered:0
Oct 08 00:44:04.380 - [DEBUG] report_connect_fail:104.20.73.129
Oct 08 00:44:05.315 - [WARNING] h1 head send len:0 39 104.19.78.109
Oct 08 00:44:05.315 - [WARNING] 104.19.78.109 trace: 0:connect, 4328:init, 0:head,:4103, processed:0, transfered:0
Oct 08 00:44:05.315 - [DEBUG] report_connect_fail:104.19.78.109
Oct 08 00:44:05.567 - [DEBUG] 104.27.116.64 fail:error(' certficate is none',)
Oct 08 00:44:05.568 - [DEBUG] report_connect_fail:104.27.116.64
Oct 08 00:44:05.705 - [DEBUG] 198.41.209.198 worker close:keep alive
Oct 08 00:44:05.743 - [DEBUG] 104.27.9.154 fail:error(' certficate is none',)
Oct 08 00:44:05.744 - [DEBUG] report_connect_fail:104.27.9.154
Oct 08 00:44:06.255 - [DEBUG] 104.28.15.30 fail:error(' certficate is none',)
Oct 08 00:44:06.256 - [DEBUG] report_connect_fail:104.28.15.30
Oct 08 00:44:06.434 - [DEBUG] 104.28.154.102 fail:error(' certficate is none',)
Oct 08 00:44:06.434 - [DEBUG] report_connect_fail:104.28.154.102
Oct 08 00:44:06.606 - [DEBUG] 190.93.244.246 fail:error(' certficate is none',)
Oct 08 00:44:06.607 - [DEBUG] report_connect_fail continue_fail_count:11
Oct 08 00:44:06.609 - [DEBUG] report_connect_fail:190.93.244.246
Oct 08 00:44:06.739 - [DEBUG] network is ok, cost:131 ms
Oct 08 00:44:06.812 - [DEBUG] ip:104.20.32.95 real fail
Oct 08 00:44:09.766 - [DEBUG] 104.20.73.129 worker close:keep alive
Oct 08 00:44:09.969 - [DEBUG] 104.17.217.106 fail:error(' certficate is none',)
Oct 08 00:44:09.970 - [DEBUG] report_connect_fail:104.17.217.106
Oct 08 00:44:10.039 - [DEBUG] 104.27.82.38 fail:error(' certficate is none',)
Oct 08 00:44:10.040 - [DEBUG] report_connect_fail:104.27.82.38
Oct 08 00:44:10.638 - [DEBUG] 104.19.78.109 worker close:keep alive
Oct 08 00:44:10.651 - [DEBUG] 141.101.114.205 fail:error(' certficate is none',)
Oct 08 00:44:10.652 - [DEBUG] report_connect_fail:141.101.114.205
Oct 08 00:44:10.733 - [DEBUG] 104.31.83.15 fail:error(' certficate is none',)
Oct 08 00:44:10.734 - [DEBUG] report_connect_fail:104.31.83.15
Oct 08 00:44:11.883 - [DEBUG] 190.93.247.216 fail:error(' certficate is none',)
Oct 08 00:44:11.884 - [DEBUG] report_connect_fail:190.93.247.216
Oct 08 00:44:12.157 - [DEBUG] ip:108.162.253.212 real fail
Oct 08 00:44:14.262 - [DEBUG] 162.159.234.254 fail:error(' certficate is none',)
Oct 08 00:44:14.264 - [DEBUG] report_connect_fail:162.159.234.254
Oct 08 00:44:14.949 - [DEBUG] 141.101.114.113 fail:error(' certficate is none',)
Oct 08 00:44:14.950 - [DEBUG] report_connect_fail:141.101.114.113
Oct 08 00:44:15.008 - [DEBUG] 141.101.113.57 fail:error(' certficate is none',)
Oct 08 00:44:15.009 - [DEBUG] report_connect_fail:141.101.113.57
Oct 08 00:44:15.437 - [DEBUG] 104.24.252.22 fail:error(' certficate is none',)
Oct 08 00:44:15.438 - [DEBUG] report_connect_fail:104.24.252.22
Oct 08 00:44:16.280 - [DEBUG] 190.93.247.218 fail:error(' certficate is none',)
Oct 08 00:44:16.281 - [DEBUG] report_connect_fail:190.93.247.218
Oct 08 00:44:17.627 - [DEBUG] ip:108.162.253.164 real fail****

**Comment by xx791117** [comment]
I am also,求解

**Comment by safarishi** [comment]
貌似现在又可以了

**Comment by alex30000** [comment]
我现在还是这样
