### ISSUE TITLE
瞎搞一通，IPV6竟然开启成功了，又能上网了

### ISSUE THREAD

**Issue by wangguagua618** [XX-net/XX-Net#6975]
![image](https://user-images.githubusercontent.com/30017109/31313868-cf83ee06-ac22-11e7-9f04-87d9f39278b8.png)
![image](https://user-images.githubusercontent.com/30017109/31313869-d74c5b46-ac22-11e7-9bb5-d31f1a56703b.png)

**Comment by Farb** [comment]
怎么改的呀

**Comment by lovmone** [comment]
你这码打的有什么意思= =

**Comment by wangguagua618** [comment]
@Farb   我就

**Comment by Farb** [comment]
@wangguagua618 说话说一半  无语了
