### ISSUE TITLE
X-Tunnel充值后无法使用，显示以下日志，谢谢。

### ISSUE THREAD

**Issue by strongmny** [XX-net/XX-Net#6996]
Oct 08 18:16:40.143 - [DEBUG] Conn session:awlxcoqa conn:90 stop:recv fail.
Oct 08 18:16:40.143 - [DEBUG] remove conn_id:90
Oct 08 18:16:40.424 - [DEBUG] Conn session:awlxcoqa conn:91 stop:recv fail.
Oct 08 18:16:40.424 - [DEBUG] remove conn_id:91
Oct 08 18:16:40.565 - [DEBUG] Conn session:awlxcoqa conn:92 stop:recv fail.
Oct 08 18:16:40.565 - [DEBUG] remove conn_id:92
Oct 08 18:16:40.580 - [DEBUG] roundtrip time:115316 cost:2725 transfer_no:55 send_sn:55 send:33 recv_sn:25 rcv:36 status:200
Oct 08 18:16:40.580 - [WARNING] rtt:112591 speed:0 trace: 0:connect, 546:init, 0:head, 312:head end, 32:request, 10530:Res, 0:request, 10423:Res, 0:request, 15104:Res, 0:request, 16203:Res, 0:request, 15573:Res, 0:request, 10746:Res, 0:request, 5299:Res, 0:request, 5074:Res, 0:request, 5247:Res, 0:request, 5139:Res, 0:request, 5125:Res, 0:request, 5101:Res, 0:request, 3207:Res, 2:request, 5000:Res, 0:request, 2819:Res, 0:request, 5267:Res, 0:request, 4486:Res, 0:request, 2257:Res, 0:request, 5233:Res, 16:request, 5230:Res, 0:request, 3690:Res, 0:request, 2975:Res, 14:request,:0, processed:22, transfered:1887
Oct 08 18:16:40.580 - [WARNING] task trace:0:start_request,111493:get_task(0),822:get_worker:104.27.30.164,0:h1_req,0:h1_req_sended,2975:response_begin,0:h1_get_head,0:h1_finish[SP:12],0:get_response,:14
Oct 08 18:16:40.580 - [DEBUG] DATA conn_id 48 not in list
Oct 08 18:16:40.580 - [DEBUG] start roundtrip transfer_no:84 send_data_len:25 ack_len:8
Oct 08 18:16:45.280 - [DEBUG] Conn session:awlxcoqa conn:93 stop:recv fail.
Oct 08 18:16:45.280 - [DEBUG] remove conn_id:93
Oct 08 18:16:45.283 - [INFO] socks5 ('127.0.0.1', 51510) connect to clients2.google.com:443 conn_id:94
Oct 08 18:16:51.409 - [INFO] socks5 ('127.0.0.1', 51542) connect to www.googleapis.com:443 conn_id:95
Oct 08 18:16:55.961 - [INFO] socks5 ('127.0.0.1', 51559) connect to www.googleapis.com:443 conn_id:96
Oct 08 18:17:02.248 - [INFO] socks5 ('127.0.0.1', 51584) connect to www.google.com:443 conn_id:97
Oct 08 18:17:02.296 - [INFO] socks5 ('127.0.0.1', 51586) connect to plus.google.com:443 conn_id:98
Oct 08 18:17:05.905 - [INFO] socks5 ('127.0.0.1', 51605) connect to www.youtube.com:443 conn_id:99
Oct 08 18:17:15.284 - [DEBUG] Conn session:awlxcoqa conn:94 stop:recv fail.
Oct 08 18:17:15.284 - [DEBUG] remove conn_id:94
Oct 08 18:17:15.287 - [INFO] socks5 ('127.0.0.1', 51645) connect to clients2.google.com:443 conn_id:100
Oct 08 18:17:20.779 - [INFO] socks5 ('127.0.0.1', 51669) connect to accounts.google.com:443 conn_id:101
Oct 08 18:17:21.412 - [DEBUG] Conn session:awlxcoqa conn:95 stop:recv fail.
Oct 08 18:17:21.412 - [DEBUG] remove conn_id:95

**Comment by strongmny** [comment]
封锁太严重

**Comment by xxnet** [comment]
​速度太慢，请试试
https://codeload.github.com/XX-net/XX-Net/zip/3.6.9

**Comment by strongmny** [comment]
快了一些，谢谢
