### ISSUE TITLE
似乎ipv6也不是完全撑得住……

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#6998]
用了两天ipv6，现在ip已经从12000+掉到8900了……
连接池数量也不是很高，也没见到新扫到的ip
看来真的药丸

**Comment by hjfGitHub** [comment]
![image](https://user-images.githubusercontent.com/29224684/31316486-14c618de-ac61-11e7-8754-5847d64149a5.png)
你还好 我已经只有这么多了

**Comment by kalwahe** [comment]
陕西电信 已经挂了 一个都不剩

**Comment by hjfGitHub** [comment]
![image](https://user-images.githubusercontent.com/29224684/31316521-af8cc840-ac61-11e7-87af-2f5e755d9792.png)
才过几分钟  ……………………  无语了

**Comment by hjfGitHub** [comment]
只减不增

**Comment by zanewayne78** [comment]
ipv6的ip是内置的，不会扫描增加的

**Comment by hjfGitHub** [comment]
问一个比较傻的问题，内置的的ip的为啥会一直减少？

**Comment by zanewayne78** [comment]
@hjfGitHub 有些失效了呗，有些被屏蔽

**Comment by hjfGitHub** [comment]
药丸，只能求大神找出解决的办法了。

**Comment by hjfGitHub** [comment]
![image](https://user-images.githubusercontent.com/29224684/31316675-c327eddc-ac64-11e7-9f69-8b7f56ea1554.png)
太快了，我滴妈

**Comment by xxnet** [comment]
​如果连接不上，会标记为失败。
而ipv6没有建扫描机制，因此只会少不会多。

如果进入高级，重新检查一遍，应该能够找回来很多ip。
ipv6以前用的少，这个问题没有突出

**Comment by Zmm1977** [comment]
呵呵，那几个公用teredo服务器完全就是活靶子啊

**Comment by zhencaihao** [comment]
![qq 20171008205557](https://user-images.githubusercontent.com/19796493/31316980-22de240c-ac6b-11e7-82c6-d406f428283d.jpg)
我这里开了IPV6，虽然能用，但是非常地卡。

**Comment by ngsaam** [comment]
同出现了这个问题，我以为是我的操作姿势不对之类的...

**Comment by ngsaam** [comment]
@xxnet 高级？哪个高级？我没找到....请问能指出来在哪吗？

**Comment by wyjtm** [comment]
teredo一砍就直接GG

**Comment by wyjtm** [comment]
顺便ls语文是体育老师教的www   没毛病2333

**Comment by Mybestway** [comment]
原生的ipv6，ping所有v6地址都丢包

**Comment by toobed** [comment]
你们都比我多，我现在只有2000多，但是我觉得不是问题，墙如果要搞，只会一个不剩，所以2000和10000没有区别。楼上说的teredo服务器完全就是活靶这才是问题，土匪真要搞比搞ipv4容易太多了，毕竟 ipv4都是原生的， ipv6 只不过通过几个服务器。趁现在能用且行且珍惜了，估计过不了多久了。

**Comment by Temmie-hOi** [comment]
@xxnet 刚才本来还有7000+ip，突然全没了，检查所有ip的时候剩余数飞快的下降，几秒就扫完了，然后依然显示有效ip0

**Comment by Temmie-hOi** [comment]
似乎是ipv6突然连不上了

**Comment by ARCHOTZ** [comment]
点检查IP会回来好多，但有时很快会掉到剩下很少......
