### ISSUE TITLE
Facebook 上传图片问题

### ISSUE THREAD

**Issue by hombreray** [XX-net/XX-Net#70]
先表示下敬意，你的软件很好用。

问题：不管是goagent哪个版本都没有解决掉Facebook上传图片的问题，但是可以通过配置文件来解决这个问题。
Facebook的对应ip地址跟Google的域名ip地址类似，是否可以添加自动搜索Facebook的IP功能？

**Comment by xxnet** [comment]
理论上是可以的，不过改动不小。
1. 创建一个通用的ip地址扫描模块，可以从google_ip做调整，变成通用模块。
2. 选定Facebook的ip范围，验证方法的函数（check_ip里面有test_gws参考），目标的ip个数。
3. 启动时，启动一个线程，专门扫特定目的ip。
4. 访问特定域名时，使用特定目标ip

但是，从原理上来讲，这成本太高了，应该先研究为什么GAE无法上传Facebook图片。

我上次测试时，发现Facebook访问时，有一个js加载有问题，首先是怀疑这个js导致。可以先试试跳过这个js(针对这个js，用SwitchySharp切换到ShadowSocks，保证不出问题)，看看是否解决。

可以从浏览器的调试日志中看异常。

如何不是这个js的问题，可以看看GoAgent图片上传过程，是否哪些参数传递出错了，去解决具体的bug。可以搭建自己的服务，去模拟Facebook上传服务。

**Comment by hombreray** [comment]
我不是从事这方面开发的软件人员，如果自动扫描不行的话可以增加个手动添加就行了，之前我通过添加个IPList Facebook=1XXXXXXX 然后在添加一条 upload.facebook.com=Facebook.
这样就可以上传，但是现在的xxnet不知道哪个是配置配置文件

**Comment by xxnet** [comment]
暂时没有这个特性，有考虑过类似功能，不过还没有动手去做。
特别需要的访问，先挂个ShadowSocks解决吧。
 免费共享的ShadowSocks挺多的。Google一下就有了。

在 2015年3月20日 上午3:21，hombreray <notifications@github.com>写道：

**Comment by xxnet** [comment]
1.7采用GoAgent 3.2协议，这个问题应该就解决了
