### ISSUE TITLE
启动error

### ISSUE THREAD

**Issue by snow8261** [XX-net/XX-Net#700]
日志如下：
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'

帮忙看看是什么问题！

**Comment by xxnet** [comment]
什么操作系统？
xxnet什么版本？

2015-07-22 10:47 GMT+08:00 snow8261 <notifications@github.com>:

**Comment by snow8261** [comment]
windows xx 2.0.4

**Comment by xxnet** [comment]
请把详细的日志发上来

2015-07-22 11:28 GMT+08:00 snow8261 <notifications@github.com>:

**Comment by snow8261** [comment]
2.0.4已经不用了，关了吧，谢谢。等2.0.5再有问题在报。
