### ISSUE TITLE
为何win10可以用ipv6,linux不可以

### ISSUE THREAD

**Issue by ljhui** [XX-net/XX-Net#7009]
我在win10下启用ipv6,瞬间一万多个ip，可以使用，但在fedora 26 gnome下刚开始无法启用，后来参考了archwiki中IPV6的词条，我是使用PPPoE上网，创建/etc/ppp/pppoe.conf写入+ipv6,然后可以启用，但一万个瞬间清零，一万多个ip检查也太快了，2秒就5000，然后就2000,4秒就归零0了，一直提示你应该开启ip扫描器，返回看win10,发现虽然xx-net选择了使用ipv6选项，但是网络与共享中心没有勾选ipv6协议，ipv6是没有网络访问权限的,真是不懂，为何win10可以用ipv6,linux不可以，fedora要怎么正确设置ipv6?都是用的xx-net 3.6.10

**Comment by chanble** [comment]
http://blog.csdn.net/scylhy/article/details/72699166  ubuntu 下可以

**Comment by ljhui** [comment]
终于成功了
