### ISSUE TITLE
【技术讨论】XX-Net采用python进行编写的问题

### ISSUE THREAD

**Issue by rainplus** [XX-net/XX-Net#7011]
python是一门解释性的语言，源码可见，会不会更容易遭到GFW的针对。
源码可见 ，可以看出处理的细节，可以针对暴露的处理过程进行针对性的处理。

**Comment by penuser** [comment]
想多了，SS开源也没见到被针对。主要还是看对数据包特征的混淆与掩蔽，即使公开算法也无法特征性识别

**Comment by rainplus** [comment]
@penuser ss,现在不是原作者已经说被针对处理了么？深圳市开始对针ss的使用者进行精准定位。

**Comment by xxnet** [comment]
​封锁只需要抓包就可以分析，比看代码来的容易。

顺便也讨论Python语言的选择问题。

1、性能
   这个问题一开始是担心的，实践下来发现完全没有问题。
   a. 网络通信，主要瓶颈在网络延迟上，延迟级别一般60-200ms，严重是600-1500ms。
      而代码执行时间在0.1ms级别，基本忽略
   b. 耗时的都用native库
       最耗时的就算加密了，采用OpenSSL，完全感觉不到加密增加的CPU消耗。
       确实试过纯python实现的SSL，慢太多了，性能无法接受。
   c. 标准python库，不是最优
      体验最大的是Queue的实现，居然采用轮询+ sleep
        计时不准确，cpu负载高。
        项目很多库都是自己重新精简实现，性能优化过。
   d. 算法优化，优先于语言
     python开发效率高，让使用者有精力去优化。
     采用正确的算法，才能从根本上解决问题。

2、防木马
   一方面防止分发过程中被加入木马;
   另一方面，防止国内杀毒软件误报毒。
   因为python二进制文件是官方下载的，文件hash没有问题。而代码都是明文，有报毒的话可以让用户自己辨别。

3、开发门槛低
   参与贡献开发的人多。

   包括界面，采用html/css/js，会的人很多，都能参与进来。

4、夸平台
   目前支持的平台： Windows 全系列、Linux、MacOS、OpenWrt、Android
   IOS也只是需要时间来解决。

   一份代码，在全部平台上执行，只需要在个别细节上进行处理，网络编码部分都通用。
  减少了开发成本。

5、发布、升级方便
  如果是二进制包，github下载会转到amazon上，会被墙， android版安装包即如此。
  下载源码没有被墙，下载后覆盖就可以。
