### ISSUE TITLE
需要私密见谅！

### ISSUE THREAD

**Issue by whhxmwhh** [XX-net/XX-Net#7012]

**Comment by hudingyin** [comment]
342006428@qq.com

**Comment by renegade123** [comment]
1261754710@qq.com

**Comment by kaoshen** [comment]
kaotudou2015@qq.com

**Comment by f839903061** [comment]
f839903061@hotmail.com

**Comment by akiritoa** [comment]
wangguanyi1@126.com

**Comment by tommyclerk** [comment]
371488193@qq.com

**Comment by wcg928** [comment]
39908599@qq.com

**Comment by 990753707** [comment]
990753707@qq.com;这种留言方式似曾相识~~~~

**Comment by alphazhangnan** [comment]
418941393@qq.com  thx

**Comment by fiezwang** [comment]
240122605@qq.com
thx....

**Comment by Persephone3** [comment]
zhf_17@qq.com 
thx

**Comment by MRSUNGIT** [comment]
shhlat@163.com

**Comment by engenez** [comment]
engene@126.com

**Comment by mytac** [comment]
mytac1995@gmail.com 
thx~~

**Comment by mytac** [comment]
my_tac@126.com
thx

**Comment by bill0991** [comment]
289016734@qq.com
thx

**Comment by Fooooox** [comment]
lovewangrui@outlook.com，谢谢（ps：等了N个两小时了，也希望xxnet能度过这一劫！）

**Comment by whhxmwhh** [comment]
算了。吓死了。都是国内的信箱。开玩笑吧！～

**Comment by leixw0102** [comment]
0102lei@163.com

**Comment by whhxmwhh** [comment]
f839903061@hotmail.com
已经发了

**Comment by Sloancc** [comment]
1248548413@qq.com

**Comment by rainplus** [comment]
大家能不能私密一下。。这样直接暴露QQ。。真的好么？

**Comment by AaronLucas** [comment]
356079909@qq.com<mailto:356079909@qq.com>



发自我的小米手机
在 wcg928 <notifications@github.com>，2017年10月9日 上午9:04写道：

39908599@qq.com<mailto:39908599@qq.com>

**Comment by wanghz** [comment]
wa.n.ghz5.18@gmail.com， 谢谢！

**Comment by mytac** [comment]
my_tac@126.com
thx

**Comment by wangippy** [comment]
@whhxmwhh  wanghippy@qq.com

**Comment by xianxin88** [comment]
@whhxmwhh  52383145@qq.com
thx

**Comment by Mydong** [comment]
278052829@qq.com  谢谢啊

**Comment by whhxmwhh** [comment]
我去学习如何私密

**Comment by bill0991** [comment]
OKCupid_by@163.com  @whhxmwhh      3q

**Comment by weijie6067** [comment]
746497139@qq.com @whhxmwhh

**Comment by shikicc** [comment]
@whhxmwhh shikicc163@gmail.com

**Comment by shikicc** [comment]
@whhxmwhh shikicc163@yahoo.com

**Comment by hatplay** [comment]
hatplay@gmail.com @whhxmwhh

**Comment by alphazhangnan** [comment]
那楼主留个联系方式吧 现在不能翻墙留gmail也不行啊

**Comment by tommyclerk** [comment]
现在改用gmail了，求发tommyclerk88@gmail.com

**Comment by xianxin88** [comment]
@whhxmwhh   xiao-sen@hotmail.com   改邮箱了..发一下.谢谢

**Comment by alphazhangnan** [comment]
alphazhangN@hotmail.com qiufa

**Comment by weijie6067** [comment]
kongdj6067@gmail.com @whhxmwhh  谢谢

**Comment by xianxin88** [comment]
@whhxmwhh  xiao-sen@hotmail.com  谢谢

**Comment by bill0991** [comment]
bill0991@hotmail.com  谢谢  @whhxmwhh

**Comment by fiezwang** [comment]
fiezwang@hotmail.com
@whhxmwhh 谢谢！

**Comment by Sloancc** [comment]
sloan.yusl@gmail.com 谢谢！

**Comment by galaxyunion** [comment]
9823598@qq.com
THX!
@whhxmwhh

**Comment by yihangli** [comment]
hungryhenry.me@gmail.com
thx!

**Comment by onplus** [comment]
楼上各位开下门，快递到了 
https://github.com/onplus/shadowsocks-heroku

**Comment by huangsanm** [comment]
huangsanm@foxmail.com

**Comment by alphazhangnan** [comment]
@onplus    注册账号那里有验证,要翻墙的吧

**Comment by f839903061** [comment]
@whhxmwhh 谢谢
