### ISSUE TITLE
一个IP 下载速度2M 疯了~~

### ISSUE THREAD

**Issue by GFconcept** [XX-net/XX-Net#7036]
反正这会用着超快 就一个IP~

**Comment by Goooooollum** [comment]
少而精

**Comment by ylwszb** [comment]
可用ip数量太多未必是好事，几十个ip时看YouTube一点不卡，ip数上千了倒卡了。

**Comment by nly4lov** [comment]
我就两个 IP，该干嘛干嘛，速度完全跟之前一样

**Comment by hdoo** [comment]
@nly4lov @GFconcept 把ip发下我试试呗，我这扫不出来了

**Comment by nly4lov** [comment]
@hdoo 试也没用，好像每个IP只能用于其本机
119.28.87.227|119.28.84.182

**Comment by hdoo** [comment]
@nly4lov 竟然可以，thanks

**Comment by soaph** [comment]
@nly4lov 第一个ip我有，不过看到你发出来，我觉得很快就被封了

**Comment by e2889e** [comment]
@nly4lov 删了吧
这是墙内的, 别害了别人

**Comment by toobed** [comment]
@nly4lov 哈哈难道你的ip表不一样？自带的扫不出来

**Comment by hdoo** [comment]
那楼上几个你们ip都是哪里弄的？还有特殊渠道？

**Comment by nly4lov** [comment]
@soaph 我现在还在用啊
@e2889e 墙内是啥意思，怎么会害人？

**Comment by e2889e** [comment]
@nly4lov 貌似是腾讯云的, 貌似国内云要实名

**Comment by nly4lov** [comment]
@e2889e 不明觉厉

**Comment by hdoo** [comment]
在其他地方看到原来这两个ip
早就被分享出来了，也没事啊
