### ISSUE TITLE
XX-Net 3.6.8 正常，可用ip有6000多个

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#7062]
方法很简单：
1、开启ipv6；
2、使用新的ip段——网上能搜到。

GAEProxy状态信息
XX-Net 3.6.8，一切正常，你可以访问真正的互联网了。

属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 6202
空闲 | 0
IP延迟 | 968
连接池(帮助) | 新:7 h1:35 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK
···

**Comment by toobed** [comment]
我还奇怪为什么用同一个软件有的人能搜到ip，有的人挂一夜也是0，原来是这样。不管贴不贴楼主有这份心还是表示感谢

**Comment by theratlesnake** [comment]
楼主可以发个ip段给我吗？我的邮箱dgsr345gjh@gmail.com

**Comment by wuwuti** [comment]
发是没问题的，只是不知道管理员是否允许。另外，发出来以后，大家伙一块用，估计过不多久就会被封掉了。

**Comment by theratlesnake** [comment]
@wuwuti 私发一个都不行？那么叼

**Comment by tilneyyang** [comment]
怎么搜到的啊？ 我用gogotester挂了几天随机搜， 一个可连的ip都搜不到。。

**Comment by theratlesnake** [comment]
@tilneyyang 注意安全，等下都是蜜罐那就完蛋了

**Comment by toobed** [comment]
@wuwuti 没事发不发无所谓，都是暂时的东西

**Comment by wuwuti** [comment]
gogotester 是搜不到的。直接百度、谷歌“google ip段 最新”即可。看看文件日期，如是最近的，应该就能用。

**Comment by tilneyyang** [comment]
thx

**Comment by wuwuti** [comment]
另外，完全没必要用x-tunnel。

**Comment by shindaren** [comment]
老哥私我点IP，我是共匪的话，我是狗，求分享。
email:chinliu001@gmail.com

**Comment by wuwuti** [comment]
搜到以后，删掉老的ip段，把新的直接黏贴进去就ok。

**Comment by wuwuti** [comment]
随便贴几个，希望没违规。如违规，请斑竹直接删除。
113.197.104.0-113.197.107.255
209.62.176.0-209.62.191.255
108.177.0.0-108.177.0.255
45.121.228.0-45.121.231.255
113.197.106.0-113.197.106.255
185.25.28.0-185.25.29.255
192.178.0.0-192.179.255.255
185.25.30.0-185.25.30.255
216.239.44.0-216.239.45.255
207.251.96.0-207.251.96.255
104.237.172.0-104.237.172.255
208.117.224.0-208.117.235.255
208.117.253.0-208.117.253.255

**Comment by zxk7516** [comment]
你导入的IP正在心肉眼可见的速度 -1.

**Comment by Caixixuan** [comment]
我用XX-Net 3.6.8，还是搜不到ip啊，其他几个版本都试过了。

**Comment by wuwuti** [comment]
那是因为老的ip段彻底没用了。找新的ip段。

**Comment by currygithub** [comment]
还是不能用

**Comment by wuwuti** [comment]
属性 | 值
-- | --
总IP数 | 12347
剩余数 | 0
有效IP数 | 5925

**Comment by SSS666SSS** [comment]
请问怎么开启ipv6啊？谢谢

**Comment by wuwuti** [comment]
本地的ipv6打开，xx-net软件的教育网ipv6也打开，即可。

**Comment by SSS666SSS** [comment]
都打开了，总ip数为12347，过了几秒就都挂了

**Comment by whhxmwhh** [comment]
是的明显感到墙有针对xx-net的特性进行封杀。

**Comment by hujunyao** [comment]
晚上好用 早上8点后 不好用

**Comment by Dust1989** [comment]
我这边现在ipv6的ip几乎全灭了！！

**Comment by tilneyyang** [comment]
应该还是跟机器实际ip网段有关系的，我在公司（没有vpn）可以有700多个可用ip， 家里什么都没有。

**Comment by bb2bbdaye** [comment]
电脑上装着360或者其他安全软件都吧IP上报了？可以这么理解吧。。。
