### ISSUE TITLE
买了X-tunnel流量没增加

### ISSUE THREAD

**Issue by chenyuyou** [XX-net/XX-Net#7064]
买了X-tunnel怎么流量没增加还是500M

---

**Comment by carotin** [comment]
发email吧

**Comment by xxnet** [comment]
有时要刷新一下才能看到，还有问题把帐号发我邮箱 xxnet.dev@gmail.com

**Comment by hhhyde** [comment]
账号密码忘了也能重置吧. 发邮件申请?

**Comment by xxnet** [comment]
​给我发邮件 xxnet.dev@gmail.com
