### ISSUE TITLE
分析一下今天网络问题

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#7065]
分析一下今天网络问题。10月09日下午3点15分，在使用百度搜索后就出现图片卡顿的现象，过一会XX-net出现不稳定现象，接着就越来越不稳定，断断续续。后来就彻底用不了了。刚用了虚拟机重新测试了一下XX-net发现XX-net并没有彻底无法使用，只是GAE不能使用，即便使用起来要开IPV6而且工序比较麻烦，反反复复测试多数情况开IPv6不成功，只有在前几次试验中开启成功了。后来就没成功过。

刚开起了IP6后没多会儿，那12000多个IP就全部没了。很快就像IPV4一样迅速降到零。
个人认为GAE如果依然采用这种连接配置方案恐怕也没有太大希望，建议GAE模式大胆设想就是，彻底取消也就是说不再使用了，另外一个是想办法转型，寻求GAE彻底转型。这样才能稳住基础。

另外就是在这段测试的过程中，发现：XX-net启动中只要不访问 百杜、163、新郎等大型网站，依然可以保持小速稳定运行（x-tunnel），这可能暗示一些大型网站也对XX-net产生了不利的作用。所以建议，访问中文大型网站时，彻底关闭XX-net。

**Comment by carotin** [comment]
1.进入高级，重新扫一遍.
2.XX会自动分流

**Comment by georagy2004** [comment]
http://weibo.com/5868519209/FpAhD3Dpy?type=comment
