### ISSUE TITLE
求支付宝购买入口啊

### ISSUE THREAD

**Issue by SemenSwallower** [XX-net/XX-Net#7066]
并没有paypal，求个支付宝支付的方式，淘宝店也行

**Comment by onplus** [comment]
国内实名的支付方式不安全。
paypal注册很方便的

**Comment by BlankWhite** [comment]
注册一个 不难

**Comment by pcicp** [comment]
@onplus PayPal能用人民币支付吗，不行的话是不是要办VISA这样的外币卡，这样不是很麻烦吗，还要转人民币到美元

**Comment by FSSU** [comment]
@pcicp PayPal国际版（注意别注册国内版的贝宝）可以直接绑定银联卡支付的。我用的建行会自动把人民币兑换成美元支付。
