### ISSUE TITLE
 最近无法用xx-net上google了

### ISSUE THREAD

**Issue by jishuaihua** [XX-net/XX-Net#7086]
## 问题内容
无法上google，老显示请等待大约2小时，XX-Net需要扫描IP。其实无用。

### 日志
Oct 10 12:47:55.649 - [INFO] SSL use version:TLSv1_2
Oct 10 12:47:56.099 - [DEBUG] network is ok, cost:1907 ms
Oct 10 12:47:56.776 - [INFO] OpenSSL support alpn
Oct 10 12:47:56.826 - [INFO] load ip range file:D:\Software\XX-Net-3.6.11\code\default\gae_proxy\local\ip_range.txt
Oct 10 12:47:57.036 - [INFO] Use google ip range.
Oct 10 12:47:57.036 - [INFO] load google ip_list num:0, gws num:0
Oct 10 12:47:57.086 - [INFO] OpenSSL support alpn
Oct 10 12:47:57.156 - [WARNING] no enough ip
Oct 10 12:47:57.226 - [DEBUG] ## GAEProxy set keep_running: True
Oct 10 12:47:57.226 - [INFO] ------------------------------------------------------
Oct 10 12:47:57.226 - [INFO] Python Version : 2.7.13
Oct 10 12:47:57.236 - [INFO] OS : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Oct 10 12:47:57.236 - [INFO] Listen Address : 127.0.0.1:8087
Oct 10 12:47:57.236 - [INFO] GAE APPID :
Oct 10 12:47:57.236 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Oct 10 12:47:57.236 - [INFO] ------------------------------------------------------
Oct 10 12:47:57.246 - [INFO] no CA file exist
Oct 10 12:47:57.246 - [INFO] clean old site certs
Oct 10 12:47:57.356 - [INFO] generate CA file:D:\Software\XX-Net-3.6.11\data\gae_proxy\CA.crt
Oct 10 12:47:57.656 - [WARNING] no enough ip
Oct 10 12:47:58.156 - [WARNING] no enough ip
Oct 10 12:47:58.662 - [WARNING] no enough ip
Oct 10 12:47:59.172 - [WARNING] no enough ip
Oct 10 12:47:59.312 - [INFO] create CA
Oct 10 12:47:59.678 - [WARNING] no enough ip
Oct 10 12:48:00.178 - [WARNING] no enough ip
Oct 10 12:48:00.685 - [WARNING] no enough ip
Oct 10 12:48:01.185 - [WARNING] no enough ip
Oct 10 12:48:01.738 - [WARNING] no enough ip
Oct 10 12:48:07.531 - [DEBUG] GET http://www.twitter.com/xxnet
Oct 10 12:48:11.671 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Oct 10 12:48:11.751 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=96db5146-6624-4b21-a4f7-6620e9b354d6&version=3.6.11&platform=Windows-7-6.1.7601-SP1
Oct 10 12:48:14.194 - [DEBUG] GAE POST https://accounts.google.com/domainreliability/upload
Oct 10 12:48:43.346 - [INFO] PAC from:127.0.0.1:50258 GET /proxy.pac
Oct 10 12:48:52.204 - [DEBUG] GAE GET http://storage.googleapis.com/update-delta/ojjgnpkioondelmggbekfhllhdaimnho/534/533/75a2290d85466c35dce73603151a59d1b8f707194447f40022227815d417c16b.crxd
Oct 10 12:48:57.551 - [DEBUG] create ssl timeout fail.
Oct 10 12:48:57.551 - [WARNING] no enough ip
Oct 10 12:48:58.051 - [WARNING] no enough ip
Oct 10 12:48:58.554 - [WARNING] no enough ip
Oct 10 12:48:59.054 - [WARNING] no enough ip
Oct 10 12:48:59.569 - [WARNING] no enough ip
Oct 10 12:49:00.069 - [WARNING] no enough ip
Oct 10 12:49:00.572 - [WARNING] no enough ip
Oct 10 12:49:01.072 - [WARNING] no enough ip
Oct 10 12:49:01.577 - [WARNING] no enough ip
Oct 10 12:49:02.077 - [WARNING] no enough ip
Oct 10 12:49:11.995 - [DEBUG] create ssl timeout fail.
Oct 10 12:49:36.534 - [INFO] PAC from:127.0.0.1:50366 GET /proxy.pac
Oct 10 12:49:57.865 - [DEBUG] create ssl timeout fail.
Oct 10 12:49:57.865 - [WARNING] no enough ip
Oct 10 12:49:58.368 - [WARNING] no enough ip
Oct 10 12:49:58.868 - [WARNING] no enough ip
Oct 10 12:49:59.368 - [WARNING] no enough ip
Oct 10 12:49:59.868 - [WARNING] no enough ip
Oct 10 12:50:00.373 - [WARNING] no enough ip
Oct 10 12:50:00.881 - [WARNING] no enough ip
Oct 10 12:50:01.384 - [WARNING] no enough ip
Oct 10 12:50:01.886 - [WARNING] no enough ip
Oct 10 12:50:02.390 - [WARNING] no enough ip
Oct 10 12:50:58.068 - [DEBUG] create ssl timeout fail.
Oct 10 12:50:58.078 - [WARNING] no enough ip
Oct 10 12:50:58.578 - [WARNING] no enough ip
Oct 10 12:50:59.078 - [WARNING] no enough ip
Oct 10 12:50:59.578 - [WARNING] no enough ip
Oct 10 12:51:00.078 - [WARNING] no enough ip
Oct 10 12:51:00.579 - [WARNING] no enough ip
Oct 10 12:51:01.079 - [WARNING] no enough ip
Oct 10 12:51:01.579 - [WARNING] no enough ip
Oct 10 12:51:02.085 - [WARNING] no enough ip
Oct 10 12:51:02.592 - [WARNING] no enough ip
Oct 10 12:51:31.216 - [DEBUG] GAE POST https://clients4.google.com/chrome-sync/experimentstatus
Oct 10 12:51:58.286 - [DEBUG] create ssl timeout fail.
Oct 10 12:51:58.291 - [WARNING] no enough ip
Oct 10 12:51:58.792 - [WARNING] no enough ip
Oct 10 12:51:59.293 - [WARNING] no enough ip
Oct 10 12:51:59.807 - [WARNING] no enough ip
Oct 10 12:52:00.237 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Oct 10 12:52:00.310 - [WARNING] no enough ip
Oct 10 12:52:00.811 - [WARNING] no enough ip
Oct 10 12:52:01.318 - [WARNING] no enough ip
Oct 10 12:52:01.837 - [WARNING] no enough ip
Oct 10 12:52:01.904 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Oct 10 12:52:02.338 - [WARNING] no enough ip
Oct 10 12:52:02.844 - [WARNING] no enough ip
Oct 10 12:52:03.535 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Oct 10 12:52:06.778 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Oct 10 12:52:14.101 - [INFO] PAC from:127.0.0.1:50697 GET /proxy.pac
Oct 10 12:52:58.599 - [DEBUG] create ssl timeout fail.
Oct 10 12:52:58.617 - [WARNING] no enough ip
Oct 10 12:52:59.119 - [WARNING] no enough ip
Oct 10 12:52:59.619 - [WARNING] no enough ip
Oct 10 12:53:00.123 - [WARNING] no enough ip
Oct 10 12:53:00.732 - [WARNING] no enough ip
Oct 10 12:53:01.237 - [WARNING] no enough ip
Oct 10 12:53:01.755 - [WARNING] no enough ip
Oct 10 12:53:02.255 - [WARNING] no enough ip
Oct 10 12:53:02.757 - [WARNING] no enough ip
Oct 10 12:53:03.257 - [WARNING] no enough ip
Oct 10 12:53:28.863 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Oct 10 12:53:33.565 - [INFO] PAC from:127.0.0.1:50849 GET /proxy.pac
Oct 10 12:53:46.953 - [DEBUG] GAE POST https://www.google-analytics.com/collect
Oct 10 12:53:59.463 - [DEBUG] create ssl timeout fail.
Oct 10 12:53:59.463 - [WARNING] no enough ip
Oct 10 12:53:59.963 - [WARNING] no enough ip
Oct 10 12:54:00.466 - [WARNING] no enough ip
Oct 10 12:54:00.967 - [WARNING] no enough ip
Oct 10 12:54:01.467 - [WARNING] no enough ip
Oct 10 12:54:01.968 - [WARNING] no enough ip
Oct 10 12:54:02.469 - [WARNING] no enough ip
Oct 10 12:54:02.974 - [WARNING] no enough ip
Oct 10 12:54:03.479 - [WARNING] no enough ip
Oct 10 12:54:03.979 - [WARNING] no enough ip
Oct 10 12:54:18.723 - [DEBUG] GET http://www.twitter.com/xxnet
Oct 10 12:54:18.837 - [DEBUG] CONNECT GET https://www.twitter.com/xxnet
Oct 10 12:54:18.854 - [DEBUG] GET http://www.twitter.com/xxnet
Oct 10 12:54:59.618 - [DEBUG] create ssl timeout fail.
Oct 10 12:54:59.618 - [WARNING] no enough ip
Oct 10 12:55:00.123 - [WARNING] no enough ip
Oct 10 12:55:00.631 - [WARNING] no enough ip
Oct 10 12:55:01.140 - [WARNING] no enough ip
Oct 10 12:55:01.645 - [WARNING] no enough ip
Oct 10 12:55:02.148 - [WARNING] no enough ip
Oct 10 12:55:02.651 - [WARNING] no enough ip
Oct 10 12:55:03.153 - [WARNING] no enough ip
Oct 10 12:55:03.654 - [WARNING] no enough ip
Oct 10 12:55:04.160 - [WARNING] no enough ip
Oct 10 12:55:59.910 - [DEBUG] create ssl timeout fail.
Oct 10 12:55:59.910 - [WARNING] no enough ip
Oct 10 12:56:00.464 - [WARNING] no enough ip
Oct 10 12:56:00.950 - [WARNING] no enough ip
Oct 10 12:56:01.451 - [WARNING] no enough ip
Oct 10 12:56:01.957 - [WARNING] no enough ip
Oct 10 12:56:02.460 - [WARNING] no enough ip
Oct 10 12:56:02.964 - [WARNING] no enough ip
Oct 10 12:56:03.472 - [WARNING] no enough ip
Oct 10 12:56:03.974 - [WARNING] no enough ip
Oct 10 12:56:04.477 - [WARNING] no enough ip
Oct 10 12:56:27.616 - [INFO] PAC from:127.0.0.1:50697 GET /proxy.pac
Oct 10 12:56:45.488 - [DEBUG] GAEProxy web_control 127.0.0.1:50151 POST /config?cmd=get_config
Oct 10 12:56:45.496 - [DEBUG] GAEProxy Web_control 127.0.0.1:50151 GET /scan_ip?cmd=get_range
Oct 10 12:56:45.519 - [INFO] load ip range file:D:\Software\XX-Net-3.6.11\code\default\gae_proxy\local\ip_range.txt
Oct 10 12:56:52.719 - [DEBUG] GAEProxy Web_control 127.0.0.1:50151 GET /deploy?cmd=get_log
Oct 10 12:56:56.338 - [DEBUG] GET http://www.twitter.com/xxnet
Oct 10 12:56:56.341 - [DEBUG] GET http://www.twitter.com/xxnet
Oct 10 12:56:58.010 - [DEBUG] GAEProxy web_control 127.0.0.1:50952 POST /config?cmd=get_config
Oct 10 12:56:59.707 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Oct 10 12:57:00.177 - [DEBUG] create ssl timeout fail.
Oct 10 12:57:00.177 - [WARNING] no enough ip
Oct 10 12:57:00.682 - [WARNING] no enough ip
Oct 10 12:57:01.185 - [WARNING] no enough ip
Oct 10 12:57:01.685 - [WARNING] no enough ip
Oct 10 12:57:02.185 - [WARNING] no enough ip
Oct 10 12:57:02.485 - [DEBUG] GAEProxy Web_control 127.0.0.1:50952 GET /deploy?cmd=get_log
Oct 10 12:57:02.692 - [WARNING] no enough ip
Oct 10 12:57:03.192 - [WARNING] no enough ip
Oct 10 12:57:03.692 - [WARNING] no enough ip
Oct 10 12:57:04.244 - [WARNING] no enough ip
Oct 10 12:57:04.735 - [WARNING] no enough ip
Oct 10 12:57:05.515 - [DEBUG] GAEProxy web_control 127.0.0.1:50151 POST /config?cmd=get_config
Oct 10 12:57:05.524 - [DEBUG] GAEProxy Web_control 127.0.0.1:50151 GET /scan_ip?cmd=get_range
Oct 10 12:57:05.527 - [INFO] load ip range file:D:\Software\XX-Net-3.6.11\code\default\gae_proxy\local\ip_range.txt

**Comment by ylwszb** [comment]
网络正常但延迟很高

用的是pac模式。gae模式是否试过？

CA证书是否有问题？（经测试，多次全新安装XX，系统会保留早期比较旧的CA证书，旧证书太多有可能会影响XX运行，建议删除旧证书）

运行一次“检查所有IP”操作。

尝试开ipv6试试。

**Comment by jishuaihua** [comment]
谢谢，在data/gae_Proxy把CA删了,启动软件，会提示重启浏览器，重启后可用！

**Comment by jishuaihua** [comment]
@ylwszb 谢谢，删除CA后可以工作了！
