### ISSUE TITLE
最新版本 3.6.12，  IPV4只有2个了，IPV6开启过一会会显示无法建立连接

### ISSUE THREAD

**Issue by hulu1528** [XX-net/XX-Net#7089]
难道是可用的ip很少的原因么？
     出现google服务器: 我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？
IP 地址：35.187.132.31
时间：2017-10-10T02:00:54Z
网址：https://www.google.com/search?q=random+forest&oq=random+forest+&aqs=chrome..69i57j69i60l3j69i65l2.5228j0j7&sourceid=chrome&ie=UTF-8

启用ipv6以后

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.12

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:2
scan-ip-thread-num: 20
ip-quality: 189
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ylwszb** [comment]
ipv6-status: 0
XX的ipv6开了吗？
似乎没开！

**Comment by glitterlin** [comment]
![12](https://user-images.githubusercontent.com/29438372/31372716-b40c8658-adc9-11e7-9948-e37285cf6776.png)
我的这样，上不去啊

**Comment by ylwszb** [comment]
执行一次检查所有IP操作，看看是否有效。

重启计算机，再试。

尝试开启ipv6
