### ISSUE TITLE
x-tunnel注册帐号无法登录，怎么找回帐号？

### ISSUE THREAD

**Issue by jay0063** [XX-net/XX-Net#7111]
使用注册时的密码无法登录，再次注册提示
`电子邮件地址已被他人使用。
`

###版本信息

属性 | 值
-- | --
XX-Net Version | 3.6.12
Python Version | 2.7.10
OpenSSL Version | 16.0.0 TLSv1 h2:alpn
System Platform | x86_64, Darwin-15.6.0-x86_64-i386-64bit
OS System | Darwin
OS Version | Darwin Kernel Version 15.6.0: Sun Jun 4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64
OS Release | 15.6.0
OS Detail | Release:10.11.6; Version:('', '', '') Machine:x86_64
Language | zh_CN
Architecture | 64bit,
Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by zhangdaxi** [comment]
同问

**Comment by zhangdaxi** [comment]
情况一模一样

**Comment by Cielofartie** [comment]
同问

**Comment by xxnet** [comment]
​用注册的邮箱地址给我发邮件  xxnet.dev@gmail.com

**Comment by jay0063** [comment]
@xxnet 已发
