### ISSUE TITLE
更新3.6.13以后还是IP要扫描两个小时

### ISSUE THREAD

**Issue by christinlee2010** [XX-net/XX-Net#7119]
已经将IPV6按钮打开了，还是这样。求助。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
xxnet-version: 3.6.13

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by carotin** [comment]
不知道你所在地是否提供ip6接入，没有的话，你需要开启teredo隧道连接ip6网络，开启教程看这里https://github.com/XX-net/XX-Net/issues/6918 ，不然打开xx-net的ipv6按钮是无用的。
