### ISSUE TITLE
仅有的两个ip阵亡了一个，尼玛太吓人了啊

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#7126]
Property | Value
-- | --
Local Network Status | OK
IP Number | 1
Is Idle | 0
IP Quality | 9999
Connection Pool(Help) | new:0 h1:0 h2:1
Browser Proxy Setting | OK
CA status(Download) | OK
Number of IP-Scanning Threads(Settings) | 10
Block Status(Help)

**Comment by nly4lov** [comment]
咦，一转眼变成5个，再一眨眼变成 6个![e103](https://user-images.githubusercontent.com/11325411/31416744-d35fe542-ae5d-11e7-8650-f21f02c70fd9.gif)

**Comment by nly4lov** [comment]
现在是3个

**Comment by justfornodejs** [comment]
开启ipv6妥妥的

**Comment by shindaren** [comment]
求分享IP（手动滑稽）

**Comment by xiaoyan94** [comment]
@shindaren 头像滑稽就行

**Comment by zhuchuanlong1988** [comment]
开ipv6，拖拖地

**Comment by nly4lov** [comment]
又剩下1个了，不敢分享，我怀疑阵亡这个就是前天分享导致的![i_f33](https://user-images.githubusercontent.com/11325411/31420875-bb549d94-ae76-11e7-8774-d3384f28ffd8.png)

**Comment by nxtreaming** [comment]
发这种issue有什么意义？ 你要解决什么问题？
你要抒情吗？

只要能用就行了，管他有多少IP。

-----------------------------------------
Productive. Reliable. Fast.

**Comment by theratlesnake** [comment]
无非就是炫耀吧
