### ISSUE TITLE
2.0.5请帮助分析日志报错信息，谢谢！

### ISSUE THREAD

**Issue by citizentang** [XX-net/XX-Net#713]
感觉翻墙速度没以前流畅，而且会越来越慢，浏览器用的是傲游v4.4.6.2000

查看日志经常看到：
Jul 23 19:30:57 - [WARNING] gae_handler.handler send response fail. t:11 e:error(10053, '') http://quickaccess-dl.maxthon.cn/news/news_chief.js
Jul 23 19:30:57 - [INFO] GAE t:11032 s:0 304 http://quickaccess-dl.maxthon.cn/news/news_chief.js
。。。。。。
Jul 23 19:37:22 - [DEBUG] GAE_Exception 2 'try max times'
Jul 23 19:37:22 - [WARNING] gae_exception:GAE_Exception() http://safeurl.maxthon.cn/data/v3/config_cn.dat
Jul 23 19:37:22 - [DEBUG] get ip:128.0.169.242 t:606
Jul 23 19:37:22 - [DEBUG] GAE_Exception 2 'try max times'
Jul 23 19:37:22 - [WARNING] gae_exception:GAE_Exception() http://safeurl.maxthon.cn/data/5/21520.dat
。。。。。。
Jul 23 19:38:17 - [INFO] GAE CONNECT push-s.maxthon.com:80
Jul 23 19:38:17 - [INFO] ssl error: [Errno 1] _ssl.c:507: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request, create full domain cert for host:push-s.maxthon.com
。。。。。。
Jul 23 19:41:38 - [INFO]LOG_EXCEPT: GAE CONNECT push-s.maxthon.com:80 , Except:[Errno 9] Bad file descriptor
Jul 23 19:41:38 - [INFO] ssl error: [Errno 1] _ssl.c:507: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request, create full domain cert for host:push-s.maxthon.com

请问是何原因，谢谢！

**Comment by cdmask** [comment]
你用chrome试试看，看是不是浏览器的关系。

**Comment by xxnet** [comment]
主要原因是Google ip被封了太多

2015-07-24 9:47 GMT+08:00 cdmask <notifications@github.com>:
