### ISSUE TITLE
升级到3.6.13 .ipv6也扛不住了.上万ip全挂了????

### ISSUE THREAD

**Issue by TOBOM** [XX-net/XX-Net#7133]
`
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.9 Safari/537.36
xxnet-version: 3.6.13

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

`

手贱点击升级到测试版,,,ip全挂,,,然后,,,就悲剧了.3.6.12还有上w个地址,,,,,

**Comment by TOBOM** [comment]
提示 您应该考虑开启 IP 扫描器。

**Comment by phycsjay** [comment]
重设netsh int ipv6 add route ::/0 index

**Comment by wangjihu** [comment]
提示 您应该考虑开启 IP 扫描器。
也是这个问题

**Comment by zhou12808** [comment]
@phycsjay   怎么设置，我怎么输入，显示指令错误

**Comment by phycsjay** [comment]
@管理员权限的cmd里输入，  Index是teredo适配器的Idx
netsh int ipv6 show int 查看

**Comment by EmmieMcDonald** [comment]
不要用自动升级，手动下载，把 data 文件夹复制进去

**Comment by Askwind** [comment]
我的还剩余700多个可用的IP。
