### ISSUE TITLE
请教一个与翻墙无关的技术问题，感谢！

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#7136]
win7操作系统，chrome浏览器，打开google主页，右上角的gamail和google apps图标消失了。见图1。但用鼠标在二者应该在的位置上晃动一下，两个图标就又出出现了，见图2。请问这个问题怎么解决？感谢！ 

![aa](https://user-images.githubusercontent.com/13399800/31419649-7fe202bc-ae6f-11e7-8e58-653fea5f4dcd.jpg)

![bb](https://user-images.githubusercontent.com/13399800/31419653-833b0f62-ae6f-11e7-8c9f-ef5d5ce1a382.jpg)

**Comment by zhuxt2015** [comment]
网页加载的问题，和翻墙的网速有关。不影响使用就不用管。

**Comment by farshidvahid** [comment]
@zhuxt2015 感谢。应该和网速无关。我的笔记本就没有这个问题，而笔记本的速度显然慢于这个新的台式机。怀疑和cookies有关，但不知怎么处理。

**Comment by zhencaihao** [comment]
那就删除cookies试试。
