### ISSUE TITLE
XX-Net版本3.6.13，证书的状态就是失败

### ISSUE THREAD

**Issue by JMaxime** [XX-net/XX-Net#7139]
属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 0
空闲 | 0
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
扫描IP线程数(设置) | 50
屏蔽状态(帮助) | OK

**Comment by ghjtyry** [comment]
此版可用，永远支持XX-Net

**Comment by gustav183** [comment]
ctrl+F5

**Comment by JMaxime** [comment]
@gustav183 此方法可行

**Comment by zjhxmjl** [comment]
@gustav183 似乎不能解决？
![2017-10-12-094700_486x139_scrot](https://user-images.githubusercontent.com/4043922/31475286-96705894-af32-11e7-971f-fd0b22006b34.png)
