### ISSUE TITLE
老铁们说Win10专业版默认开启IPv6吗？

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#7152]
如题，已经找好win10资源了 晚上回去捣鼓一下，win7按照远景论坛的教程一直不成功！

**Comment by LuoboWang1** [comment]
没有 最新专业预览版都没有。自己手动。

**Comment by lambdaphy** [comment]
我的是默认开启的，直接在XX-Net的配置页面开启ipv6，电脑没有进行配置就开启了。

**Comment by nly4lov** [comment]
@lambdaphy 这个不是看系统,主要是看路由器里设置

**Comment by klcb2010** [comment]
所以 只与路由器有关？@nly4lov

**Comment by davidchen1028** [comment]
跟系统没关系吧，我这边主猫是由电信的工程师直接调好的，默认开启ipv6，有独立的公网V6地址。

**Comment by silascript** [comment]
没有。我学习了下。然后轻松开启了！不过重启后又失效了，又得重置teredo和add route!不过已经很幸福了！

**Comment by YoungJAF** [comment]
win10专 业 版 直接开启IP6 使用，有没有
![image](https://user-images.githubusercontent.com/32703584/31435869-9d9aac16-aeb3-11e7-8e81-e88406ebc1b0.png)

**Comment by klcb2010** [comment]
http://www.windows7en.com/jiaocheng/26518.html  这篇文章 解决问题  装了win10 LTSB 版本  虽然 网络显示无连接  但是 ipv6测试通过  哈哈

**Comment by nly4lov** [comment]
@klcb2010 我也是菜鸟。
