### ISSUE TITLE
昨天刚充了300G,今天连图标都看不到了...

### ISSUE THREAD

**Issue by tiger8888** [XX-net/XX-Net#7155]
我昨天刚充了300G,今天就打不开xx-net了,mac上的活动监视器,可以看到相应的进程,但是状态条上没有xxnet图标,也访问不了http://127.0.0.1:8085/,求解
luncher.log的日志一下:
Oct 11 16:54:58.319 - [INFO] use build-in openssl lib
Oct 11 16:54:58.320 - [INFO] start XX-Net 3.6.12
Oct 11 16:54:58.320 - [DEBUG] start confirm_xxnet_exit
Oct 11 16:54:58.321 - [DEBUG] good, xxnet:8087 cleared!
Oct 11 16:54:58.322 - [DEBUG] good, xxnet:8085 clear!
Oct 11 16:54:58.322 - [DEBUG] finished confirm_xxnet_exit
Oct 11 16:54:59.273 - [INFO] module gae_proxy started
Oct 11 16:54:59.273 - [INFO] start gae_proxy time cost:951 ms

顺便吐槽一下,GFW,就知道屏蔽,难道就不能提供下正规访问外网的渠道,那些搞学术的,搞开发的,都得用啊!!!  天朝就这么先进,用不到国外的东西????,大清锁国的思想与悲剧,还要在天朝上演??

**Comment by zhgna08** [comment]
现在X-Tunnel好像又不灵了。还好ipv6还正常。

**Comment by tiger8888** [comment]
我累了,不作了...,想死的心都有了...
