### ISSUE TITLE
重装系统后，xx-net状态无法切换，一直为取消全局代理

### ISSUE THREAD

**Issue by thiszhangjin** [XX-net/XX-Net#7163]
整个文件夹也删除过了，从新装了几遍，还是无法更改状态

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.13

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:12114
network-status: OK
connected-link: new:7 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 470
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by TooAndy** [comment]
用SwitchyOmega啊

**Comment by thiszhangjin** [comment]
日志如下
Oct 11 19:12:00.077 - [INFO] SSL use version:TLSv1_2
Oct 11 19:12:00.452 - [DEBUG] network is ok, cost:577 ms
Oct 11 19:12:00.608 - [INFO] OpenSSL support alpn
Oct 11 19:12:00.608 - [INFO] load ip range file:E:\XX-Net-3.6.13\code\default\gae_proxy\local\ip_range.txt
Oct 11 19:12:00.639 - [INFO] detected Win10, enable connect concurrency control, interval:40
Oct 11 19:12:00.639 - [INFO] Use google ip range.
Oct 11 19:12:00.717 - [INFO] load google ip_list num:12347, gws num:12347
Oct 11 19:12:00.749 - [INFO] OpenSSL support alpn
Oct 11 19:12:00.749 - [DEBUG] ## GAEProxy set keep_running: True
Oct 11 19:12:00.749 - [INFO] ------------------------------------------------------
Oct 11 19:12:00.749 - [INFO] Python Version : 2.7.13
Oct 11 19:12:00.749 - [INFO] OS : Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Oct 11 19:12:00.749 - [INFO] Listen Address : 127.0.0.1:8087
Oct 11 19:12:00.749 - [INFO] GAE APPID :
Oct 11 19:12:00.749 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Oct 11 19:12:00.749 - [INFO] ------------------------------------------------------
Oct 11 19:12:02.124 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Oct 11 19:12:02.157 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=270fc1ac-76bb-499b-893c-f6bbab90035a&version=3.6.13&platform=Windows-10-10.0.15063
Oct 11 19:12:04.749 - [DEBUG] 2607:f8b0:401a:16::6 fail:timeout('timed out',)
Oct 11 19:12:04.749 - [DEBUG] report_connect_fail:2607:f8b0:401a:16::6
Oct 11 19:12:04.795 - [DEBUG] 2607:f8b0:4007:4::a fail:timeout('timed out',)
Oct 11 19:12:04.795 - [DEBUG] report_connect_fail:2607:f8b0:4007:4::a
Oct 11 19:12:05.265 - [DEBUG] 2607:f8b0:401d:16::18 fail:timeout('timed out',)
Oct 11 19:12:05.265 - [DEBUG] report_connect_fail:2607:f8b0:401d:16::18
Oct 11 19:12:05.755 - [DEBUG] 2404:6800:400b:2e::c fail:timeout('timed out',)
Oct 11 19:12:05.755 - [DEBUG] report_connect_fail:2404:6800:400b:2e::c
Oct 11 19:12:06.270 - [DEBUG] 2404:6800:400b:2e::b fail:timeout('timed out',)
Oct 11 19:12:06.270 - [DEBUG] report_connect_fail:2404:6800:400b:2e::b
Oct 11 19:12:06.772 - [DEBUG] 2607:f8b0:400a:9::f fail:timeout('timed out',)
Oct 11 19:12:06.772 - [DEBUG] report_connect_fail:2607:f8b0:400a:9::f
Oct 11 19:12:07.283 - [DEBUG] 2607:f8b0:401d:9::18 fail:timeout('timed out',)
Oct 11 19:12:07.283 - [DEBUG] report_connect_fail:2607:f8b0:401d:9::18
Oct 11 19:12:07.787 - [DEBUG] 2404:6800:4001:b::9 fail:timeout('timed out',)
Oct 11 19:12:07.787 - [DEBUG] report_connect_fail:2404:6800:4001:b::9
Oct 11 19:12:08.357 - [DEBUG] 2607:f8b0:401d:17::17 fail:timeout('timed out',)
Oct 11 19:12:08.357 - [DEBUG] report_connect_fail:2607:f8b0:401d:17::17
Oct 11 19:12:08.751 - [DEBUG] 2607:f8b0:401e:12::16 fail:timeout('timed out',)
Oct 11 19:12:08.751 - [DEBUG] report_connect_fail:2607:f8b0:401e:12::16
Oct 11 19:12:08.800 - [DEBUG] 2607:f8b0:401d:9::17 fail:timeout('timed out',)
Oct 11 19:12:08.800 - [DEBUG] report_connect_fail continue_fail_count:11
Oct 11 19:12:08.800 - [DEBUG] report_connect_fail:2607:f8b0:401d:9::17
Oct 11 19:12:08.837 - [DEBUG] 2607:f8b0:401e:12::10 fail:timeout('timed out',)
Oct 11 19:12:08.837 - [DEBUG] report_connect_fail continue_fail_count:12
Oct 11 19:12:08.837 - [DEBUG] report_connect_fail:2607:f8b0:401e:12::10
Oct 11 19:12:08.929 - [DEBUG] network is ok, cost:128 ms
Oct 11 19:12:09.265 - [DEBUG] 2607:f8b0:401e:12::11 fail:timeout('timed out',)
Oct 11 19:12:09.265 - [DEBUG] report_connect_fail:2607:f8b0:401e:12::11
Oct 11 19:12:09.306 - [DEBUG] 2607:f8b0:4017:b::16 fail:timeout('timed out',)
Oct 11 19:12:09.306 - [DEBUG] report_connect_fail:2607:f8b0:4017:b::16
Oct 11 19:12:09.758 - [DEBUG] 2607:f8b0:4002:2b::8 fail:timeout('timed out',)
Oct 11 19:12:09.758 - [DEBUG] report_connect_fail:2607:f8b0:4002:2b::8
Oct 11 19:12:10.270 - [DEBUG] 2607:f8b0:4002:2b::a fail:timeout('timed out',)
Oct 11 19:12:10.270 - [DEBUG] report_connect_fail:2607:f8b0:4002:2b::a
Oct 11 19:12:10.772 - [DEBUG] 2a00:1450:4002:15::19 fail:timeout('timed out',)
Oct 11 19:12:10.772 - [DEBUG] report_connect_fail:2a00:1450:4002:15::19
Oct 11 19:12:10.819 - [DEBUG] sort ip time:46ms
Oct 11 19:12:11.295 - [DEBUG] 2607:f8b0:4004:20::17 fail:timeout('timed out',)
Oct 11 19:12:11.295 - [DEBUG] report_connect_fail:2607:f8b0:4004:20::17
Oct 11 19:12:11.394 - [DEBUG] connect 2607:f8b0:401a:14::19 fail:[Errno 10053] cost:574 h:0
Oct 11 19:12:11.394 - [DEBUG] report_connect_fail:2607:f8b0:401a:14::19
Oct 11 19:12:11.396 - [DEBUG] connect 2607:f8b0:401a:f::10 fail:[Errno 10053] cost:1125 h:0
Oct 11 19:12:11.396 - [DEBUG] connect 2607:f8b0:401c:1a::a fail:[Errno 10053] cost:100 h:0
Oct 11 19:12:11.397 - [DEBUG] 2607:f8b0:401a:b::e fail:error(10053, '')
Oct 11 19:12:11.397 - [DEBUG] connect 2607:f8b0:401a:f::12 fail:[Errno 10053] cost:1639 h:0
Oct 11 19:12:11.397 - [DEBUG] 2607:f8b0:4004:22::b fail:error(10053, '')
Oct 11 19:12:11.398 - [DEBUG] connect 2404:6800:400f:1::c fail:[Errno 10053] cost:2092 h:0
Oct 11 19:12:11.398 - [DEBUG] connect 2404:6800:400f:1::b fail:[Errno 10053] cost:2132 h:0
Oct 11 19:12:11.398 - [DEBUG] connect 2404:6800:400b:9::c fail:[Errno 10053] cost:2546 h:0
Oct 11 19:12:11.398 - [DEBUG] connect 2404:6800:400b:19::12 fail:[Errno 10053] cost:2645 h:0
Oct 11 19:12:11.399 - [DEBUG] report_connect_fail:2607:f8b0:401a:f::10
Oct 11 19:12:11.401 - [DEBUG] report_connect_fail:2607:f8b0:401c:1a::a
Oct 11 19:12:11.402 - [DEBUG] report_connect_fail:2607:f8b0:401a:b::e
Oct 11 19:12:11.402 - [DEBUG] report_connect_fail continue_fail_count:11
Oct 11 19:12:11.402 - [DEBUG] connect 2607:f8b0:401d:18::16 fail:[Errno 10065] cost:3 h:0
Oct 11 19:12:11.402 - [DEBUG] report_connect_fail:2607:f8b0:401a:f::12
Oct 11 19:12:11.403 - [DEBUG] report_connect_fail continue_fail_count:12
Oct 11 19:12:11.403 - [DEBUG] report_connect_fail:2607:f8b0:4004:22::b
Oct 11 19:12:11.403 - [DEBUG] report_connect_fail continue_fail_count:13
Oct 11 19:12:11.403 - [DEBUG] report_connect_fail:2404:6800:400f:1::c
Oct 11 19:12:11.403 - [DEBUG] report_connect_fail continue_fail_count:14
Oct 11 19:12:11.404 - [DEBUG] report_connect_fail:2404:6800:400f:1::b
Oct 11 19:12:11.404 - [DEBUG] report_connect_fail continue_fail_count:15
Oct 11 19:12:11.404 - [DEBUG] report_connect_fail:2404:6800:400b:9::c
Oct 11 19:12:11.404 - [DEBUG] report_connect_fail continue_fail_count:16
Oct 11 19:12:11.404 - [DEBUG] report_connect_fail:2404:6800:400b:19::12
Oct 11 19:12:11.405 - [DEBUG] connect 2607:f8b0:401a:b::a fail:[Errno 10053] cost:2592 h:0
Oct 11 19:12:11.405 - [DEBUG] report_connect_fail continue_fail_count:17
Oct 11 19:12:11.405 - [DEBUG] report_connect_fail:2607:f8b0:401d:18::16
Oct 11 19:12:11.406 - [DEBUG] report_connect_fail continue_fail_count:18
Oct 11 19:12:11.406 - [DEBUG] report_connect_fail:2607:f8b0:401a:b::a
Oct 11 19:12:11.438 - [DEBUG] connect 2404:6800:400b:25::c fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.438 - [DEBUG] report_connect_fail continue_fail_count:19
Oct 11 19:12:11.438 - [DEBUG] report_connect_fail:2404:6800:400b:25::c
Oct 11 19:12:11.440 - [INFO] PAC from:127.0.0.1:60339 GET /proxy.pac
Oct 11 19:12:11.479 - [DEBUG] connect 2404:6800:400b:25::b fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.479 - [DEBUG] report_connect_fail continue_fail_count:20
Oct 11 19:12:11.479 - [DEBUG] report_connect_fail:2404:6800:400b:25::b
Oct 11 19:12:11.519 - [DEBUG] connect 2404:6800:400f:5::8 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.519 - [DEBUG] report_connect_fail continue_fail_count:21
Oct 11 19:12:11.519 - [DEBUG] report_connect_fail:2404:6800:400f:5::8
Oct 11 19:12:11.559 - [DEBUG] connect 2607:f8b0:401d:18::15 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.559 - [DEBUG] report_connect_fail continue_fail_count:22
Oct 11 19:12:11.559 - [DEBUG] report_connect_fail:2607:f8b0:401d:18::15
Oct 11 19:12:11.601 - [DEBUG] connect 2404:6800:400f:5::9 fail:[Errno 10065] cost:1 h:0
Oct 11 19:12:11.601 - [DEBUG] report_connect_fail continue_fail_count:23
Oct 11 19:12:11.601 - [DEBUG] report_connect_fail:2404:6800:400f:5::9
Oct 11 19:12:11.641 - [DEBUG] connect 2a00:1450:401f:2a::b fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.641 - [DEBUG] report_connect_fail continue_fail_count:24
Oct 11 19:12:11.641 - [DEBUG] report_connect_fail:2a00:1450:401f:2a::b
Oct 11 19:12:11.683 - [DEBUG] connect 2a00:1450:4014:a::b fail:[Errno 10065] cost:1 h:0
Oct 11 19:12:11.683 - [DEBUG] report_connect_fail continue_fail_count:25
Oct 11 19:12:11.683 - [DEBUG] report_connect_fail:2a00:1450:4014:a::b
Oct 11 19:12:11.723 - [DEBUG] connect 2a00:1450:4014:a::c fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.723 - [DEBUG] report_connect_fail continue_fail_count:26
Oct 11 19:12:11.723 - [DEBUG] report_connect_fail:2a00:1450:4014:a::c
Oct 11 19:12:11.763 - [DEBUG] connect 2607:f8b0:401e:11::11 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.763 - [DEBUG] report_connect_fail continue_fail_count:27
Oct 11 19:12:11.763 - [DEBUG] report_connect_fail:2607:f8b0:401e:11::11
Oct 11 19:12:11.814 - [DEBUG] connect 2a00:1450:4014:a::f fail:[Errno 10065] cost:10 h:0
Oct 11 19:12:11.814 - [DEBUG] report_connect_fail continue_fail_count:28
Oct 11 19:12:11.814 - [DEBUG] report_connect_fail:2a00:1450:4014:a::f
Oct 11 19:12:11.846 - [DEBUG] connect 2607:f8b0:4008:10::18 fail:[Errno 10065] cost:3 h:0
Oct 11 19:12:11.846 - [DEBUG] report_connect_fail continue_fail_count:29
Oct 11 19:12:11.846 - [DEBUG] report_connect_fail:2607:f8b0:4008:10::18
Oct 11 19:12:11.884 - [DEBUG] connect 2404:6800:400c:16::c fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.884 - [DEBUG] report_connect_fail continue_fail_count:30
Oct 11 19:12:11.884 - [DEBUG] report_connect_fail:2404:6800:400c:16::c
Oct 11 19:12:11.924 - [DEBUG] connect 2404:6800:400c:16::a fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.925 - [DEBUG] report_connect_fail continue_fail_count:31
Oct 11 19:12:11.925 - [DEBUG] report_connect_fail:2404:6800:400c:16::a
Oct 11 19:12:11.966 - [DEBUG] connect 2a00:1450:401c:12::7 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:11.966 - [DEBUG] report_connect_fail continue_fail_count:32
Oct 11 19:12:11.967 - [DEBUG] report_connect_fail:2a00:1450:401c:12::7
Oct 11 19:12:12.007 - [DEBUG] connect 2a00:1450:401c:12::d fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.007 - [DEBUG] report_connect_fail continue_fail_count:33
Oct 11 19:12:12.007 - [DEBUG] report_connect_fail:2a00:1450:401c:12::d
Oct 11 19:12:12.048 - [DEBUG] connect 2a00:1450:401c:12::e fail:[Errno 10065] cost:1 h:0
Oct 11 19:12:12.048 - [DEBUG] report_connect_fail continue_fail_count:34
Oct 11 19:12:12.048 - [DEBUG] report_connect_fail:2a00:1450:401c:12::e
Oct 11 19:12:12.087 - [DEBUG] network is ok, cost:119 ms
Oct 11 19:12:12.088 - [DEBUG] connect 2a00:1450:401c:12::b fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.088 - [DEBUG] report_connect_fail:2a00:1450:401c:12::b
Oct 11 19:12:12.128 - [DEBUG] connect 2a00:1450:401c:12::c fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.129 - [DEBUG] report_connect_fail:2a00:1450:401c:12::c
Oct 11 19:12:12.180 - [DEBUG] connect 2a00:1450:401c:12::a fail:[Errno 10065] cost:11 h:0
Oct 11 19:12:12.180 - [DEBUG] report_connect_fail:2a00:1450:401c:12::a
Oct 11 19:12:12.210 - [DEBUG] connect 2607:f8b0:4007:2::9 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.211 - [DEBUG] report_connect_fail:2607:f8b0:4007:2::9
Oct 11 19:12:12.256 - [DEBUG] connect 2607:f8b0:4007:2::8 fail:[Errno 10065] cost:6 h:0
Oct 11 19:12:12.257 - [DEBUG] report_connect_fail:2607:f8b0:4007:2::8
Oct 11 19:12:12.297 - [DEBUG] connect 2607:f8b0:4000:b::10 fail:[Errno 10065] cost:6 h:0
Oct 11 19:12:12.298 - [DEBUG] report_connect_fail:2607:f8b0:4000:b::10
Oct 11 19:12:12.331 - [DEBUG] connect 2404:6800:400b:1c::d fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.332 - [DEBUG] report_connect_fail:2404:6800:400b:1c::d
Oct 11 19:12:12.372 - [DEBUG] connect 2a00:1450:401b:3::b fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.373 - [DEBUG] report_connect_fail:2a00:1450:401b:3::b
Oct 11 19:12:12.412 - [DEBUG] connect 2a00:1450:401b:3::c fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.413 - [DEBUG] report_connect_fail:2a00:1450:401b:3::c
Oct 11 19:12:12.454 - [DEBUG] connect 2404:6800:400c:9::9 fail:[Errno 10065] cost:2 h:0
Oct 11 19:12:12.455 - [DEBUG] report_connect_fail:2404:6800:400c:9::9
Oct 11 19:12:12.497 - [DEBUG] connect 2404:6800:400c:9::8 fail:[Errno 10065] cost:3 h:0
Oct 11 19:12:12.497 - [DEBUG] report_connect_fail continue_fail_count:11
Oct 11 19:12:12.497 - [DEBUG] report_connect_fail:2404:6800:400c:9::8
Oct 11 19:12:12.535 - [DEBUG] connect 2404:6800:400c:9::7 fail:[Errno 10065] cost:1 h:0
Oct 11 19:12:12.535 - [DEBUG] report_connect_fail continue_fail_count:12
Oct 11 19:12:12.535 - [DEBUG] report_connect_fail:2404:6800:400c:9::7
Oct 11 19:12:12.575 - [DEBUG] connect 2a00:1450:401f:43::19 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.576 - [DEBUG] report_connect_fail continue_fail_count:13
Oct 11 19:12:12.576 - [DEBUG] report_connect_fail:2a00:1450:401f:43::19
Oct 11 19:12:12.615 - [DEBUG] connect 2a00:1450:401f:43::18 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.616 - [DEBUG] report_connect_fail continue_fail_count:14
Oct 11 19:12:12.616 - [DEBUG] report_connect_fail:2a00:1450:401f:43::18
Oct 11 19:12:12.661 - [DEBUG] connect 2404:6800:400b:1c::e fail:[Errno 10065] cost:5 h:0
Oct 11 19:12:12.662 - [DEBUG] report_connect_fail continue_fail_count:15
Oct 11 19:12:12.662 - [DEBUG] report_connect_fail:2404:6800:400b:1c::e
Oct 11 19:12:12.702 - [DEBUG] connect 2a00:1450:401f:43::11 fail:[Errno 10065] cost:4 h:0
Oct 11 19:12:12.703 - [DEBUG] report_connect_fail continue_fail_count:16
Oct 11 19:12:12.703 - [DEBUG] report_connect_fail:2a00:1450:401f:43::11
Oct 11 19:12:12.737 - [DEBUG] connect 2a00:1450:401f:43::12 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.737 - [DEBUG] report_connect_fail continue_fail_count:17
Oct 11 19:12:12.738 - [DEBUG] report_connect_fail:2a00:1450:401f:43::12
Oct 11 19:12:12.777 - [DEBUG] connect 2a00:1450:401f:43::15 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.777 - [DEBUG] report_connect_fail continue_fail_count:18
Oct 11 19:12:12.778 - [DEBUG] report_connect_fail:2a00:1450:401f:43::15
Oct 11 19:12:12.818 - [DEBUG] connect 2a00:1450:401f:43::14 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.818 - [DEBUG] report_connect_fail continue_fail_count:19
Oct 11 19:12:12.819 - [DEBUG] report_connect_fail:2a00:1450:401f:43::14
Oct 11 19:12:12.861 - [DEBUG] connect 2a00:1450:401f:43::17 fail:[Errno 10065] cost:3 h:0
Oct 11 19:12:12.861 - [DEBUG] report_connect_fail continue_fail_count:20
Oct 11 19:12:12.861 - [DEBUG] report_connect_fail:2a00:1450:401f:43::17
Oct 11 19:12:12.899 - [DEBUG] connect 2a00:1450:401f:43::16 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.899 - [DEBUG] report_connect_fail continue_fail_count:21
Oct 11 19:12:12.900 - [DEBUG] report_connect_fail:2a00:1450:401f:43::16
Oct 11 19:12:12.939 - [DEBUG] connect 2404:6800:4007:6::14 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.940 - [DEBUG] report_connect_fail continue_fail_count:22
Oct 11 19:12:12.940 - [DEBUG] report_connect_fail:2404:6800:4007:6::14
Oct 11 19:12:12.981 - [DEBUG] connect 2404:6800:4007:6::15 fail:[Errno 10065] cost:0 h:0
Oct 11 19:12:12.981 - [DEBUG] report_connect_fail continue_fail_count:23
Oct 11 19:12:12.981 - [DEBUG] report_connect_fail:2404:6800:4007:6::15
