### ISSUE TITLE
一个关于艾克斯video的问题

### ISSUE THREAD

**Issue by georagy2004** [XX-net/XX-Net#7176]
发现一个很有意思的问题：

我手机和电脑用chorme 都能直接打开x videos，不需要任何代理工具；

我的其他浏览器都不能打开这个站，包括手机和电脑；

我用其他人手机电脑的chrome 都打不开这个站；

什么原因？

**Comment by MadMaxPayne8964** [comment]
你改过hosts

**Comment by onplus** [comment]
这个网站没有被墙，部分地区部分运营商自己屏蔽的
