### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by lusfold** [XX-net/XX-Net#719]
升级版本－检查最新版本 －－－》发生未知错误, 请刷新页面重试.

Property	Value
XX-Net Version	1.15.2
Launcher Version	1.4.0
GoAgent Version	3.1.49
Python Version	2.7.6
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac

**Comment by xxnet** [comment]
手动下载新版吧

2015-07-24 11:20 GMT+08:00 lusfold <notifications@github.com>:

**Comment by lusfold** [comment]
明白，多谢，这个项目后续有更新的优化么

**Comment by xxnet** [comment]
要持续优化完善的

2015-07-24 11:53 GMT+08:00 lusfold <notifications@github.com>:
