### ISSUE TITLE
无法通过 UDP 访问主 teredo 服务器

### ISSUE THREAD

**Issue by outofmemo** [XX-net/XX-Net#7196]
昨天已经通过teredo 成功连接到IPv6,但今天换了个网络,显示"无法通过 UDP 访问主 teredo 服务器"

>λ  netsh interface teredo show state
>Teredo 参数
>---------------------------------------------
>类型                    : enterpriseclient (Group Policy)
>服务器名称              : teredo.remlab.net (Group Policy)
>客户端刷新间隔          : 15 秒  (Group Policy)
>客户端端口                : unspecified
>状态                    : offline
>错误                    : 无法通过 UDP 访问主 teredo 服务器

**Comment by MichelChen2017** [comment]
teredo.remlab.net服务器时好时坏，得找稳定点得Teredo服务器。

**Comment by outofmemo** [comment]
恩恩，好长时间之后竟然自己好了。不过IP少了很多，只有二十多个了，昨天有一万多。、
>属性	值
>本地网络状态	OK
>IP数量	17
>空闲	0
>IP延迟	560

另外据我所知,好像只有这一个能用的服务器

**Comment by MichelChen2017** [comment]
还会掉线吗？

在 2017年10月12日 上午11:00，@echo off <notifications@github.com>写道：

**Comment by outofmemo** [comment]
刚刚又掉了

**Comment by MichelChen2017** [comment]
@outofmemo  try 一下 teredo.iks-jena.de .

**Comment by outofmemo** [comment]
试了下teredo.iks-jena.de 能连上,用段时间看看稳定性怎么样

**Comment by qumaggot** [comment]
同样的问题, 现在晚上一过9点就就疯狂掉线...看来是没救了..
