### ISSUE TITLE
使用xxnet1.3.6不规律的出现同一个问题:浏览器提示请重新部署服务端

### ISSUE THREAD

**Issue by internetic** [XX-net/XX-Net#72]
我确信自己的appid在服务端已经部署好，正在运行并且可用

我的apppid共10个，通过原版goagent3.2.3部署至服务端
最初使用xxnet时，添加了3个appid，没有出现过该提示。
最近2个星期添加至10个appid后，不同种类浏览器频繁，但不规律出现该提示“请重新部署服务端”
置之不理一段时间后，似乎又可以翻墙，使用一段时间后又复现该提示

win8.1 x64  xxnet1.3.6（除填入自己的appid无其他任何改动）

**Comment by xxnet** [comment]
用了403作为判断依据，会误判，不影响正常使用。
  以后优化。


在 2015年3月20日 上午12:24，internetic <notifications@github.com>写道：

**Comment by dteen** [comment]
同样遇到了类似问题。。。太频繁了受不了啊。。没有解决办法吗。。

win7 x32 xxnet1.3.6

**Comment by xxnet** [comment]
好的，我研究下，肯定有办法，下周出一个版本吧。

2015-03-21 7:25 GMT-04:00 dteen <notifications@github.com>:

**Comment by xxnet** [comment]
已经解决
