### ISSUE TITLE
Ipv6 自动获取并转换

### ISSUE THREAD

**Issue by songjinju** [XX-net/XX-Net#7202]
## 背景
如果你的内网IP不是固定的，那么你会发现你今天可能就无法翻了，ipv6测试不通过。然后又要重新根据你的内网IPV4的地址转换成IPV6，这就非常 繁琐。

之后，在同事的指导下，我们发现windows自带这个服务（Ipv6 转换），但是默认是关闭状态的，需要手动启动。（右击 我的电脑 -> 管理 -> 服务与应用程序 -> 服务）
右击[IP转换配置服务]，选择属性，改成自动启动，并**重启电脑**。
另外IP6也要改成自动获取。
可以参考这篇文章[Ipv6 自动转换](http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more)

我是win10的系统

**Comment by guanbaozi** [comment]
这个方法好使用，虽然我的ip是固定的，但是今天没法翻墙，看ipv6测试页上面显示没有可连接的ipv6，用过这个方法后，现在能上了

**Comment by muxushizi** [comment]
并不管用呀

**Comment by freesd** [comment]
WIN8以上才有这个服务，WIN7没有，不过WIN7现在还正常，就是IP少了很多

**Comment by muxushizi** [comment]
@freesd 原来是这样，晚上回家用win10试试，X-tunnel实在太慢了

**Comment by wiket** [comment]
win10系统并未发现该服务
![QQ截图20171012161059.png](https://i.loli.net/2017/10/12/59df23ae7ce83.png)

**Comment by onplus** [comment]
@wiket 官方教程 https://github.com/XX-net/XX-Net/issues/7156

**Comment by wiket** [comment]
@onplus 先谢谢回复，但是没用，按照教程下来依然找不到对应的服务

**Comment by Cleonwang** [comment]
@wiket 你这两项已经打开了啊

**Comment by wiket** [comment]
@Cleonwang  并没有呢，我的电脑里面根本没有“IP转换配置服务”或者是 “IpxlatCfgSvc”服务

**Comment by Cleonwang** [comment]
@wiket IP helper和IKE and AuthIP这两项就是，我也是win10
