### ISSUE TITLE
Teredo 状态为: probe (primary server)

### ISSUE THREAD

**Issue by IKAR1SHINJI** [XX-net/XX-Net#7237]
曾经配置成功并能顺利访问，今天不行了，重做之前的步骤发现Teredo的状态不再是qualified，而是probe (primary server)，求解。

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo host-specific relay
网络                    : unmanaged

**Comment by justfornodejs** [comment]
teredo.remlab.net换个

**Comment by IKAR1SHINJI** [comment]
虽然都可以ping通，但换了teredo.trex.fi依旧不行。 发现一个问题，试了几次连接不上，按照[尝试卸载Teredo适配器后重装](https://github.com/XX-net/XX-Net/issues/6918#issuecomment-334978237)排查问题把Teredo卸载重装后发现Teredo端口给搞没了，求解

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
 17          25        1500  disconnected  WLAN
 11          75        1280  disconnected  本地连接* 14
 10          35        1500  connected     以太网
 16          25        1500  disconnected  本地连接* 2
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 13          25        1500  disconnected  本地连接* 4
  6          25        1500  disconnected  本地连接* 13

**Comment by Sisyphy** [comment]
netsh interface Teredo set state disable
netsh interface teredo set state default

试试

**Comment by IKAR1SHINJI** [comment]
可以了，谢谢。
