### ISSUE TITLE
Mac 升级到3.6.15后，状态页一直处于"尚未建立连接"状态，IP却能扫描出，但翻不了墙了。求大神！

### ISSUE THREAD

**Issue by bluechang** [XX-net/XX-Net#7240]

**Comment by Xianmua** [comment]
我这边早就用不了了，昨天听见个消息说墙又加高，今天赛风就废了，连接不上。电脑上打开github格式都错乱的，而且很慢，我都以为github被封了……手机上可以正常打开...能上github就行……唉，据说以后的墙针要开始对ss和anyconnect，，

**Comment by fishinallblue** [comment]
上不了Google哭瞎了

**Comment by bluechang** [comment]
对外开放，就是扯淡啊

**Comment by steelsun** [comment]
我的3.6.14正常的，虽然现在扫的ip不多就8，9个的样子，但还是能上。看这么一说，不敢升级到15了
