### ISSUE TITLE
折腾了一会 MAC的IPV6终于搞定了 蛮分享一下

### ISSUE THREAD

**Issue by yakecanlee** [XX-net/XX-Net#7247]
Mac OS X 10.12.6
有效IP 7K+(感觉封的有点快)

1. 安装Miredo(能搜到pkg安装包)
2. 安装TunTap(pkg安装包 不安装的话 Miredo会一直链接不成功,设置界面显示红灯)
3. XX-Net启用IPV6

**Comment by pengchenglin** [comment]
两个安装包的下载地址有吗    找了半天 都没找到能安装的miredo

**Comment by yakecanlee** [comment]
@pengchenglin 邮件已发

**Comment by pengchenglin** [comment]
为啥我也是10.12.6 miredo安装不成功呢。。。。。

**Comment by yakecanlee** [comment]
@pengchenglin emmm...试试找别的安装包或者自行源码编译?😂

**Comment by mkanako** [comment]
是不是这里下载的啊http://www.deepdarc.com/miredo-osx/

**Comment by yakecanlee** [comment]
@mkanako 对 我的安装没问题

**Comment by zurich37** [comment]
tuntap下载地址：https://sourceforge.net/projects/tuntaposx/?source=typ_redirect
miredo下载地址：http://www.deepdarc.com/miredo-osx/

**Comment by mkanako** [comment]
安装时提示不兼容继续安装，最后安装失败，但是偏好设置那里有Miredo，以为实际成功，然后安装TunTap，然后Miredo一直是红灯😂最后编译源码报错😭

**Comment by smallant** [comment]
miredo 安装 不兼容 确定你连接成功吗 表示怀疑

**Comment by yakecanlee** [comment]
![image](https://user-images.githubusercontent.com/10167643/31553448-23a90d28-b000-11e7-99f6-9e93a99b2ffc.png)

**Comment by scq000** [comment]
可以翻了，但是老是要重启miredo服务，也不知道为什么？

**Comment by huanxiang0116** [comment]
mac下2个都安装了，但是teredo address 获取不到地址 不知道为什么？

**Comment by scq000** [comment]
@huanxiang0116 我知道了，你得确认那个teredo server的地址能ping通才行。ping通了如果还是不能用，就重启一下服务或电脑

**Comment by wushibinbilly** [comment]
@yakecanlee 我的Mac好像和你的差不多，但是安装miredo不成功啊，说不适合我的Mac电脑，怎么办，请教您一下

**Comment by yakecanlee** [comment]
@wushibinbilly 我朋友也遇到这问题 我也不清楚什么原因 我是13年MBP

**Comment by wushibinbilly** [comment]
你能邮箱发一个tuntop给我吗？我现在偏好设置里面有，但是是红灯，tuntop的下载地址一直打不开
@yakecanlee

**Comment by wushibinbilly** [comment]
我也是13年的，是air来的，哎，没有翻墙很痛苦啊 @yakecanlee

**Comment by yakecanlee** [comment]
@wushibinbilly 邮箱？

**Comment by wushibinbilly** [comment]
谢谢你了，我真心上不了那个tuntap的网址啊 @yakecanlee

**Comment by yakecanlee** [comment]
@wushibinbilly 大哥 你邮箱多少？😂

**Comment by wushibinbilly** [comment]
wushibin30913@outlook.com  @yakecanlee

**Comment by wushibinbilly** [comment]
都安装了，miredo安装失败，但是偏好设置有，tuntap成功；然后打开就是红灯。。哎 @yakecanlee 伤心

**Comment by yakecanlee** [comment]
看看teredo的服务器能不能连上 不行换一个@wushibinbilly

**Comment by mkanako** [comment]
@yakecanlee 我系统也是10.12.6，64位的，你难道是32位？

**Comment by yakecanlee** [comment]
@mkanako 64位

**Comment by mkanako** [comment]
@yakecanlee 哎，蛋疼，这里几个人都是这样安装失败，不知道为啥

**Comment by scq000** [comment]
感觉不太稳定，时好时坏，teredo服务器能ping通，但还是小黄点

**Comment by jsensun** [comment]
@yakecanlee  991343287@qq.com 麻烦发一份

**Comment by lalfie** [comment]
@yakecanlee 303837343@qq.com 麻烦发一份

**Comment by jiangshan1225** [comment]
orang_Js@hotmail.com 请帮忙给我发一个。我下载不来。

**Comment by luzhiy123** [comment]
同样是安装miredo失败，然后系统偏好设置里有，两个都安装显示红灯 ping teredo.remlab.net ping  time=242.641 ms，有人知道怎么处理吗，麻烦告诉下

**Comment by sgricky** [comment]
10.13表示完全安装Miredo失败。

**Comment by zlj-lol** [comment]
非常感谢，12000+有效IP，多谢！

**Comment by 1manmanlai** [comment]
有效！！！

**Comment by sgricky** [comment]
你们都是PPPoE环境下10.12.6成功的吗？WiFi/10.13可以使吗？我连Miredo都装不上~~~

**Comment by zlj-lol** [comment]
是的，12.6，用着很稳定，速度也可以！

**Comment by hzx505** [comment]
@zurich37 谢谢给的链接

**Comment by sgricky** [comment]
Sierra，我去哭一会儿……

**Comment by hzx505** [comment]
@yakecanlee 
这种情况，怎办？不能上
![2017-11-01 7 04 42](https://user-images.githubusercontent.com/9926035/32272109-a0976e1a-bf37-11e7-8c2d-6462b7b5a53b.png)

**Comment by hzx505** [comment]
补张图
![2017-11-01 7 07 35](https://user-images.githubusercontent.com/9926035/32272257-43b3664e-bf38-11e7-839a-c4b6e8668998.png)

**Comment by qingsheng0214** [comment]
同样安装出现问题啊

**Comment by tangyichao** [comment]
mac 10.13.1 有没有办法解决

**Comment by sophiesugar** [comment]
记录一下步骤：
mac os 10.13 
进恢复模式重启后按住（command+r）
打开终端：csrutil disable
重启：reboot
然后进行以下两步
1.安装miredo
2.安装tuntap

**Comment by jsensun** [comment]
开始是这样安装的，也能够正常使用xxnet上谷歌，但是重启电脑后就一直亮红灯。
是不是需要重新安装这两个软件呢？
怎么彻底卸载miredo tuntaposx这两个软件？

**Comment by cutecate** [comment]
能否发下Miredo的pkg包，我一直没办法开启ipv6

**Comment by jsensun** [comment]
啊，已经不用这个翻墙了，买的别人的


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: cutecate <notifications@github.com>
发送时间: 2019年7月23日 00:08
收件人: XX-net/XX-Net <XX-Net@noreply.github.com>
抄送: jsensun <jsensun@foxmail.com>, Comment <comment@noreply.github.com>
主题: 回复：[XX-net/XX-Net] 折腾了一会 MAC的IPV6终于搞定了 蛮分享一下 (#7247)

**Comment by cutecate** [comment]
安装包还在吗？
现在有什么更好用的梯子吗

**Comment by jsensun** [comment]
没有了，已经删除了。
买的个人的，10块一月，速度不错


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: cutecate <notifications@github.com>
发送时间: 2019年7月23日 11:32
收件人: XX-net/XX-Net <XX-Net@noreply.github.com>
抄送: jsensun <jsensun@foxmail.com>, Comment <comment@noreply.github.com>
主题: 回复：[XX-net/XX-Net] 折腾了一会 MAC的IPV6终于搞定了 蛮分享一下 (#7247)




安装包还在吗？
 现在有什么更好用的梯子吗
