### ISSUE TITLE
AppID怎么申请？

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#7251]
如题  百度一下发现都是老教程，现在谷歌改版了。百度到的链接打开不是申请AppID的页面了

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

**Comment by klcb2010** [comment]
要打开云端shell @onplus

**Comment by klcb2010** [comment]
退出教程以后就么反应了@onplus

**Comment by onplus** [comment]
5. 点击退出教程，进行下一步[部署服务端](https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids#%E9%83%A8%E7%BD%B2%E6%9C%8D%E5%8A%A1%E7%AB%AF)

**Comment by klcb2010** [comment]
退出教程后又回到选择语言@onplus

**Comment by sundaqing1969** [comment]
申请appid不成功，退出教程后似乎还没有完成申请

**Comment by onplus** [comment]
@sundaqing1969 
完成申请了，还需要用xxnet上传 代码http://127.0.0.1:8085/?module=gae_proxy&menu=deploy

**Comment by sundaqing1969** [comment]
===============================================================
 GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
特别提醒：appid 请勿包含 ID/Email 等个人信息！
APPID:daqing-sun
05:43 PM Application: daqing-sun
05:43 PM Host: appengine.google.com
05:43 PM Rolling back the update.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u'b~daqing-sun').
--- end server output ---
Traceback (most recent call last):
  File "uploader.py", line 151, in <module>
  File "uploader.py", line 144, in main
  File "uploader.py", line 112, in upload
  File "D:\下载夹\goproxy-gae-r90\google_appengine\google\appengine\tools\appcfg
.py", line 5516, in main
SystemExit: 1

**Comment by sundaqing1969** [comment]
这是部署日志

**Comment by klcb2010** [comment]
申请ID貌似现在必须云端shell才行  可是我等了半天也没加载出来 @sundaqing1969

**Comment by onplus** [comment]
@klcb2010 不需要shell，我刚成功部署一个

**Comment by klcb2010** [comment]
@onplus 多谢  部署成功了
![qq 20171015101628](https://user-images.githubusercontent.com/32628414/31581003-ee7c7412-b191-11e7-8e6a-6371f897b3ea.jpg)
