### ISSUE TITLE
状态一直是 "请等待大约2小时，XX-Net需要扫描IP。"

### ISSUE THREAD

**Issue by zwkno1** [XX-net/XX-Net#7253]
扫描ip的日志为空。
运行start.bat有行报错

handler:AttributeError("'module' object has no attribute '_strptime'",) cmd:CONNECT path:www.twitter.com:443 from:127.0.0.1:2401
Oct 13 20:17:17.246 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net-3.6.13\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 152, in handle_one_request
    self.do_CONNECT()
  File "D:\Program Files (x86)\XX-Net-3.6.13\code\default\gae_proxy\local\proxy_handler.py", line 301, in do_CONNECT
    return self.do_CONNECT_AGENT()
  File "D:\Program Files (x86)\XX-Net-3.6.13\code\default\gae_proxy\local\proxy_handler.py", line 308, in do_CONNECT_AGENT
    certfile = CertUtil.get_cert(host)
  File "D:\Program Files (x86)\XX-Net-3.6.13\code\default\gae_proxy\local\cert_util.py", line 295, in get_cert
    certfile = CertUtil._get_old_cert(commonname, full_name)
  File "D:\Program Files (x86)\XX-Net-3.6.13\code\default\gae_proxy\local\cert_util.py", line 283, in _get_old_cert
    if datetime.datetime.strptime(cert.get_notAfter(), '%Y%m%d%H%M%SZ') <= datetime.datetime.utcnow():
AttributeError: 'module' object has no attribute '_strptime'

诊断信息:
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.13

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by beIIII** [comment]
我也一直是这样了，两个星期没有出过墙了
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
xxnet-version: 3.6.8

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by langbao** [comment]
等等吧！非常时期

**Comment by unacyl** [comment]
我一开始也是这样，后来ID重新输入，重新部署一下，开启ipv6模式好像就行了，我也不确定到底哪里有问题，这样说希望能有点帮助吧。

**Comment by dahai058** [comment]
https://github.com/bannedbook/fanqiang/wiki  目前非常稳定，看油管720p不卡

**Comment by xxnet** [comment]
​@球状闪电
   你的bug很奇怪，也许可以试试重新下载一个新的版本看看。

另外，目前可以试试x-tunnel，或者GAE 采用ipv6，请看项目主页

**Comment by jimmychen312** [comment]
配置--高级选项--使用ipv6，可以。
