### ISSUE TITLE
无法看到teredo状态

### ISSUE THREAD

**Issue by terry20** [XX-net/XX-Net#7257]
新手求助，show teredo无法看到状态
只包含前4行内容
系统为win7 64位，请问是否为系统设置部分的问题？

XX中能开启IPV6选项，但一直显示 尚未建立连接

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:11871
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by GoodSake** [comment]
C:\>netsh int ipv6 show int

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 12          25        1500  connected     Wi-Fi
 14           5        1500  disconnected  本地连接* 1
 19          50        1280  connected     Teredo Tunneling Pseudo-Interface

只要看到最后这行的 connected 就能用了哦。
