### ISSUE TITLE
设置IPV6优先导致国内网站速度慢 删除设置即可

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#7265]
如题，删除HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters 中的 AddrConfigControl即可。重启电脑，IPv6 大封包测试与查找IPv6服务提供商为失败，不使用域名的 IPv6 测试成功。得分为0，但是ipv6仍然是开启的。   仅供参考

**Comment by HustCoderHu** [comment]
这个好像是优先v6解析？

**Comment by klcb2010** [comment]
是的 访问国内网站速度慢就是这个原因  科学上网没有必要开启IPv6优先@@HustCoderHu

**Comment by HustCoderHu** [comment]
那why @xxnet  还把这个加到ipv6的脚本里了
https://github.com/XX-net/XX-Net/blob/master/code/default/ipv6_script/win32/enable_ipv6.bat

**Comment by klcb2010** [comment]
enable是允许,不是优先@HustCoderHu。看看标题，如果没有设置优先，就不需要这么做

**Comment by Freikeit** [comment]
注册表里没有找到您提到的这项，请问还有其他办法删除吗？

**Comment by klcb2010** [comment]
@Freikeit 没有这项就不用呀 ping一下任意一个国内网站就知道当前那个解析方式优先
