### ISSUE TITLE
安卓6.0 最新版 chrome 开启省流量程序 

### ISSUE THREAD

**Issue by hyxjfl01** [XX-net/XX-Net#7274]
打开. test-ipv6.com 
能看到Google proxy ipv4 ipv6 都是通的，有人是一样情况么？

**Comment by hyxjfl01** [comment]
测试 IPv6 常见问题 镜像 统计 
IPv6 连接测试
有关服务台摘要 测试项目 分享测试结果 / 联系我们 其他IPv6网站

您在公网上的 IPv4 地址是 66.249.82.66
通过代理, Via: 1.1 Chrome-Compression-Proxy

您在公网上的 IPv6 地址是 2001:4860:4801:4009::2e
通过代理, Via: 1.1 Chrome-Compression-Proxy

您的互联网服务提供商（ISP）看起来是 GOOGLE - Google Inc., US

既然你有IPv6，我们就显示一个选项卡，显示您可以前往的其他IPv6网站。[更多信息]

您的浏览器有一个真正能用的IPv6地址 - 但它在避免使用它。我们对此表示关注。 [更多信息]

我们检测到您正在使用代理。这意味着您正在检测您的代理服务器，而非您的计算机。

用DNS的IPv6连接正常工作；但直接写IP地址的URL不能正常工作。虽然这在今日的网络上很少使用。

您的DNS服务器(通常由您的网络服务商提供)已经可以接入IPv6互联网了。
网络得分
10/10	访问仅支持IPv6的网站时，您的IPv6稳定性得分
点击察看 测试数据

(服务器上的IPv6统计信息更新完毕)

**Comment by onplus** [comment]
类似opera turbo
