### ISSUE TITLE
推特检索功能出现问题，搜任何信息都显示没有

### ISSUE THREAD

**Issue by lfkonen** [XX-net/XX-Net#7292]
以前没有这个问题，好像是从开启了ipv6之后出现的（并不确定），在推特种搜索任何关键词都会显示查不到，换了浏览器同样的问题，找了另一个城市的朋友部署好了之后同样也出现这个问题。是xxnet的问题还是switchyOmega的问题？

**Comment by onplus** [comment]
好像是twitter屏蔽了gae ip发起的搜索。
xtunnel应该没有问题

**Comment by lfkonen** [comment]
xtunnel也是同样的问题

**Comment by jzmswe** [comment]
赛风搜索推特没问题，看来确实是twitter屏蔽了gae ip发起的搜索。GoProxy在twitter上也搜索不出来任何东西，无论用哪个关键词。

**Comment by lfkonen** [comment]
那……就没办法了？

**Comment by lfkonen** [comment]
那……就没办法了？

**Comment by gosex** [comment]
Twitter搜索 ，無结果
用Firefox浏览器检测元素，出现下列问题
1.控制台 - 安全， Content Security Policy: 指令 'frame-src' 已不赞成使用。请使用指令 'child-src' 替换。
2..控制台 - JS， TypeError: this.database is undefined[详细了解] 
                         0.commons.zh-cn.fd505db771c206c8c1c4.js:1:44596
不知道有用不？？

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/8122#issuecomment-342727674
