### ISSUE TITLE
申请id 没法进入下一步呀

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#7293]
各位老铁看看怎么回事 ，退出教程就回到原点

**Comment by jzmswe** [comment]
Google APPID申请改版了，原教程已不适用于新版Google。自己结合Google翻译，慢慢琢磨吧。

**Comment by onplus** [comment]
是我修改的教程语义不明。
你的appid应该已经申请到了，只是没部署
直接用这个部署试试 https://github.com/XX-net/XX-Net/tree/master/code/default/gae_proxy/server

@jzmswe 最新教程完全适用

**Comment by klcb2010** [comment]
创建项目就等于获得ID， 只是要把它部署到项目里必须通过sell云端 @onplus

**Comment by onplus** [comment]
你用这个试过了？https://github.com/XX-net/XX-Net/tree/master/code/default/gae_proxy/server

**Comment by sundaqing1969** [comment]
今天申请的appid用xx-net可以部署，但是用goproxy的各版服务部署程序部署都不成功，下面是部署日志：

===============================================================
 GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
特别提醒：appid 请勿包含 ID/Email 等个人信息！
APPID:daqing-sun11
12:18 AM Application: daqing-sun11
12:18 AM Host: appengine.google.com
12:18 AM Rolling back the update.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u'b~daqing-sun11').
--- end server output ---
Traceback (most recent call last):
  File "uploader.py", line 151, in <module>
  File "uploader.py", line 144, in main
  File "uploader.py", line 112, in upload
  File "D:\下载夹\goproxy-gae-r90\google_appengine\google\appengine\tools\appcfg
.py", line 5516, in main
SystemExit: 1

现在较新的appid申请教程是正确的。

**Comment by sundaqing1969** [comment]
今天申请的appid，用xx-net可以部署，但是用goproxy的部署程序无法成功部署，下面是失败日志：


===============================================================
 GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
特别提醒：appid 请勿包含 ID/Email 等个人信息！
APPID:daqing-sun11
12:18 AM Application: daqing-sun11
12:18 AM Host: appengine.google.com
12:18 AM Rolling back the update.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u'b~daqing-sun11').
--- end server output ---
Traceback (most recent call last):
  File "uploader.py", line 151, in <module>
  File "uploader.py", line 144, in main
  File "uploader.py", line 112, in upload
  File "D:\下载夹\goproxy-gae-r90\google_appengine\google\appengine\tools\appcfg
.py", line 5516, in main
SystemExit: 1


xx-net的appid申请教程正确。
