### ISSUE TITLE
为什么我购买了 X-TUNNEL ， 支付成功了，流量还是 0 ？

### ISSUE THREAD

**Issue by buzheng** [XX-net/XX-Net#7303]
我购买的季度的 $4.5 的， 支付成功了，流量还是 0 ？

**Comment by xxnet** [comment]
刷新一下或重启进程看看，不行给我发邮件。
xxnet.dev@gmail.com

**Comment by buzheng** [comment]
@xxnet  已经显示了， 但是并不走 X-TUNNEL， 好像还是走GAE， 不知道是不是我哪里设置的不对。 我的系统是 Mac 的

**Comment by xxnet** [comment]
​x-tunnel的代理端口是1080
如果用Chrome，可以用插件SwitchyOmega切换

**Comment by buzheng** [comment]
已设置好，多谢了
