### ISSUE TITLE
突破5000+的issuess

### ISSUE THREAD

**Issue by yogaskung** [XX-net/XX-Net#7308]
本项目的大部分issue无甚结果，无疾而终，已经成功突破5000+，有望申报吉尼斯世界纪录
请管理当局行使权限，勿让issues区变成qq群。
@xxnet

**Comment by xxnet** [comment]
​现在基本就当论坛用了，太多贴，来不及关闭

**Comment by smy0419** [comment]
哈哈哈，我没事就上来看大家来发牢骚，挺有意思的。虽然我也翻不了了现在。

**Comment by yonghuming9** [comment]
你tm有病,不当交流群？不当论坛当啥？
给用户和技术人员提供一个交流平台，有啥不好？
以你的智商和心胸，如果你以后长大了有了权力，别人可怎么活？一点不能包容，大家在这里交流交流你就受不了，

还要关闭？你可真能装逼，

如果x大听取你的谗言，关闭了issuess交流，此xx软件数月后淹没在同类软件中，新的同类热门代替，

**Comment by nxtreaming** [comment]
@yogaskung 谁告诉你这里是交流群？ 不要认为所有人都像你这样。
