### ISSUE TITLE
chrome证书问题

### ISSUE THREAD

**Issue by Elfieee** [XX-net/XX-Net#732]
今天开始一直提示所有https协议的网站都进不了(包括google...), chrome一直提示NET::ERR_CERT_INVALID
我试过了把证书删了再手动导入, 不过貌似没用
![image](https://cloud.githubusercontent.com/assets/11966862/8890098/571ce7a0-32f4-11e5-8137-13ba0f00fa17.png)

**Comment by yuliangyang** [comment]
删除data/gae_proxy文件夹下的ca.crt跟certs文件夹
然后再次运行xxnet，会提示导入证书。
这样就好了

**Comment by Elfieee** [comment]
謝謝~

**Comment by yuliangyang** [comment]
叫我雷锋
