### ISSUE TITLE
是不是已经没人维护了？

### ISSUE THREAD

**Issue by MrOne1981** [XX-net/XX-Net#7321]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.15
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by onplus** [comment]
xxnet-version: 3.6.15
xxnet released this 3 days ago
14 commits to master since this release

**Comment by dagerdager** [comment]
你不看版本发布？

**Comment by roc1010kmt** [comment]
更新的都是X-Tunnel，GAE部分基本沒什麼更新。

**Comment by whhxmwhh** [comment]
GAE部分基本沒什麼更新。我只用gae。没钱呀。有钱自己建个大杀器
