### ISSUE TITLE
如果ipv6这种方式被墙的话,是不是真的就到世界末日了,马上离物理断网不远了？

### ISSUE THREAD

**Issue by xiaomozhang** [XX-net/XX-Net#7336]

**Comment by bqata** [comment]
自己建服务器，建超多端口，gfw的模型还超不成熟，勤换端口

**Comment by nxtreaming** [comment]
能不能有点脑子？
不要发这种没有意义的issue?
VPN 方式是一直可用的，你自己搞不定，是你自己水平不行，不要像个脑残一样在这里抒情！

**Comment by xiaomozhang** [comment]
艹,不要在这乱装逼好吗,我几时说vpn不能用了,仿佛感觉自己牛逼一样,看不懂问题别瞎比比~~
