### ISSUE TITLE
未来可以考虑加入I2P应急

### ISSUE THREAD

**Issue by jobs-github** [XX-net/XX-Net#7339]
目前gfw之所以这么牛逼，我觉得主要还是因为大部分梯子都是**基于中心化的设计**，导致gfw可以拦截的列表是一个**有限集**，而且很容易发现。要突破gfw，估计得加上基于**分布式**设计的方案，例如I2P。

[这篇文章](https://program-think.blogspot.com/2012/06/gfw-i2p.html)里面有介绍。

“对于普通的网友，平时是不需要用 I2P 的（因为速度太慢）。但是你最好在手头留一个可用的 I2P 软件，以防万一。说不定哪天，朝廷加大网络封锁力度，导致你正在用的翻墙软件失效，这时候你就可以用 I2P 去下载其它翻墙软件的最新版本。”

如果未来XX-Net也能有这个功能，应该就无敌了。当然，工程量应该很大，非短期可以上线。。。

**Comment by xxnet** [comment]
​未来是有这个计划的，不过确实没有那么快。
新版本正在开发中，这两天可以上线

**Comment by Goooooollum** [comment]
期待新版

**Comment by l-night** [comment]
期待新版ING

**Comment by gogonkt** [comment]
I2P之所以慢是因為用的人少，節點少吧。如果xx-net集成進來的話，節點多了自然速度就快了。不知是否這原理?

**Comment by GoodSake** [comment]
Lantern不是宣称I2P吗，怎么也死了，最后屹立的还是XX-net厉害啊。

**Comment by redstoneleo** [comment]
@xxnet 可以增加自动扫描ipv6吗还是不可以？

**Comment by jobs-github** [comment]
@gogonkt 正解。关键是要有人用，而且用户基数要打。如果没有人用，那么分布式的设计便形同虚设。所以现在那个官网的I2P很难扫到节点，基本等于残疾。但XX-net不同，用户多，如果支持了分布式，由于用户基数大，就很牛逼了，gfw短期内将无可奈何。

**Comment by robinshiesh** [comment]
支持楼主的设想
在XX-net的助力下，说不定I2P可发展起来

**Comment by onplus** [comment]
迅雷电驴下完就关的 就不要用i2p了

**Comment by jobs-github** [comment]
@onplus 这个跟迅雷电驴性质不一样，因为gfw的策略随时会更新，逼得你不得不更新可用的节点列表，所以你**不得不把自己的节点打开，否则就被墙**。

迅雷电驴则没有一个类似于gfw这样的东西来逼迫你必须开启节点，所以都是下完就撤。

**Comment by robinshiesh** [comment]
@jobs-github 
楼上的意思，没有共享精神，就不要玩i2p了

**Comment by scljy** [comment]
期待新版

**Comment by qwerttbb** [comment]
这个东西主要问题是用户不够分散，我是说如果只用作翻，那么没有足够应用场景的话，身处自由网络的用户为什么要用？你比如这个用户都在墙内，那么匿名是可以的，但是浏览u2b就不可能了

依目前xx的用户，我觉得基本就是国内用户，所以这种设想没意义

你比如tor，这个东西设计之初就是为了高度匿名，只是国内用户使用初衷就变成了翻墙。

当然，如果你只求翻，那么tor现在用不了了，已经完整可以识别obfs4和meek。。。。

**Comment by jobs-github** [comment]
@qwerttbb  明白你意思。。。  那基本所有可用的手段都死翘翘了。。。  看 XX-Net 团队有没有更好的办法吧。。。

**Comment by xxnet** [comment]
​@redstoneleo
  ipv6 暂时不需要扫描ip，而是能回复ip

**Comment by emacsenli** [comment]
还是加入zeronet支持比较好

2017年10月16日 下午2:12，"robinshiesh" <notifications@github.com>写道：

支持楼主的设想
在XX-net的助力下，说不定I2P可发展起来

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/XX-net/XX-Net/issues/7339#issuecomment-336789724>, or mute
the thread
