### ISSUE TITLE
connected link一直为0，且日志一直提示create ssl fail超时，IP已经扫描了两天了，求大神帮忙解决

### ISSUE THREAD

**Issue by totallyfrank** [XX-net/XX-Net#734]
Jul 26 22:11:11 - [DEBUG] create_ssl 125.234.52.117 fail:timed out cost:4000 h:0
Jul 26 22:11:11 - [DEBUG] get ip:213.155.151.142 t:687
Jul 26 22:11:11 - [DEBUG] create_ssl 203.78.32.47 fail:timed out cost:4003 h:0
Jul 26 22:11:11 - [DEBUG] get ip:31.209.137.18 t:687
Jul 26 22:11:11 - [DEBUG] create_ssl 206.248.151.84 fail:timed out cost:4000 h:0
Jul 26 22:11:12 - [DEBUG] get ip:195.149.238.242 t:687
Jul 26 22:11:12 - [DEBUG] create_ssl 114.120.192.250 fail:timed out cost:4000 h:0
Jul 26 22:11:12 - [DEBUG] get ip:210.245.14.144 t:687
Jul 26 22:11:12 - [DEBUG] create_ssl 87.245.200.181 fail:timed out cost:4002 h:0
Jul 26 22:11:12 - [DEBUG] get ip:46.108.1.173 t:687
Jul 26 22:11:12 - [DEBUG] get ip:125.234.52.180 t:687
Jul 26 22:11:13 - [DEBUG] get ip:124.158.72.45 t:687
Jul 26 22:11:13 - [DEBUG] get ip:61.37.150.169 t:687
Jul 26 22:11:15 - [DEBUG] create_ssl 151.21.210.87 fail:timed out cost:4000 h:0
Jul 26 22:11:15 - [DEBUG] create_ssl 213.155.151.142 fail:timed out cost:4001 h:0
Jul 26 22:11:15 - [DEBUG] create_ssl 31.209.137.18 fail:timed out cost:4001 h:0
Jul 26 22:11:16 - [DEBUG] create_ssl 195.149.238.242 fail:timed out cost:4000 h:0
Jul 26 22:11:16 - [DEBUG] get ip:203.211.0.27 t:687
Jul 26 22:11:16 - [DEBUG] create_ssl 210.245.14.144 fail:timed out cost:4000 h:0
Jul 26 22:11:16 - [DEBUG] get ip:118.143.88.30 t:687
Jul 26 22:11:16 - [DEBUG] create_ssl 46.108.1.173 fail:timed out cost:4000 h:0
Jul 26 22:11:16 - [DEBUG] get ip:41.254.36.31 t:687
Jul 26 22:11:16 - [DEBUG] create_ssl 125.234.52.180 fail:timed out cost:4000 h:0
Jul 26 22:11:17 - [DEBUG] get ip:111.94.248.205 t:687
Jul 26 22:11:17 - [DEBUG] create_ssl 124.158.72.45 fail:timed out cost:4001 h:0
Jul 26 22:11:17 - [DEBUG] get ip:93.191.15.85 t:687
Jul 26 22:11:17 - [DEBUG] create_ssl 61.37.150.169 fail:timed out cost:4000 h:0
Jul 26 22:11:17 - [DEBUG] get ip:93.183.211.239 t:687
![qq 20150726221210](https://cloud.githubusercontent.com/assets/13508381/8894342/054febba-33e5-11e5-94ed-b27c419ee8d0.png)

**Comment by xxnet** [comment]
你是什么ISP网络？什么版本？

2015-07-26 22:24 GMT+08:00 totallyfrank <notifications@github.com>:

**Comment by totallyfrank** [comment]
2.0.5 的版本，上海电信，不过现在connected link间断会有显示了，但是很不稳定，基本上一打开youtube，就会瞬间变为0
