### ISSUE TITLE
我一应用自己的APP，就翻不出去了

### ISSUE THREAD

**Issue by chalern** [XX-net/XX-Net#735]
用默认的APPID就可以，但一应用自己的，就不行了怎么回事啊？

**Comment by cdmask** [comment]
日志呢？

**Comment by chalern** [comment]
不用了，可以了谢谢哈。
其实是我自己的APP没有流量了，只是有点好奇，三个APP三GB都不够用。。。

在 2015-07-27 09:48:12，"cdmask" <notifications@github.com> 写道：


日志呢？

**Comment by cdmask** [comment]
3个还是比较少的～我注册了7个～

**Comment by wsgdlhy** [comment]
我早几年就注册了20个

**Comment by cdmask** [comment]
嗯 足够了 哈哈
