### ISSUE TITLE
【问题】XX-net 启动后，后台不时会出现cmd.exe，关掉后，依旧会继续出现。

### ISSUE THREAD

**Issue by liaoyaoheng** [XX-net/XX-Net#736]
@管理员 不知是否是XX-net 的问题，如不是，恕我冒昧。

XX-Net Version	2.0.5
win7 64x

**Comment by lele2010lele** [comment]
经测试win8/win7无楼主所说问题，win10没有测试

**Comment by wcg928** [comment]
win7 64 没这个现象

**Comment by zuyoushen** [comment]
无此现象，7  10  64位双系统，使用正常。

**Comment by xxnet** [comment]
1. xx-net 确认是从github上下载的。
  xx-net中没有调用cmd的代码，几个调用外部的地方：
  a. 创建桌面快捷方式，是js
  b. 导入证书，是直接调用API
  c. 开机启动、修改全局代理，是直接修改注册表

2. 你关闭XX-Net看看还会不会出现cmd
3. 用 ProcessExplorer 观察cmd是哪个进程fork出来的
  ProcessExplorer 工具可以自己搜索下载

2015-07-27 18:03 GMT+08:00 zuyoushen <notifications@github.com>:
