### ISSUE TITLE
xx-net + proxiflier 能让google earth pro连接服务器吗？

### ISSUE THREAD

**Issue by gaofenglv** [XX-net/XX-Net#737]
我不想另外建立php服务器，只用xx-net加个什么软件，让google earth pro走goagent的免费代理

**Comment by linhua55** [comment]
Proxifier
一定要设置好让xx-net直连(可以设置让python.exe（也可能是pythonw.exe）直连)，google earth
pro(对应的exe文件名)走代理。


在 2015年7月27日 下午12:40，gaofenglv <notifications@github.com>写道：

**Comment by gaofenglv** [comment]
![1](https://cloud.githubusercontent.com/assets/10943483/8967062/58f7d956-3667-11e5-93f0-b839a5230f77.png)如图，我首先开通h后ttp支持，然后搞了一个proxy server ，是127.0.0.1，端口8087
![2](https://cloud.githubusercontent.com/assets/10943483/8967063/590196e4-3667-11e5-8f65-52c106f50031.png)然后设置规则，pythonw.exe直连，google earth走端口8087
![3](https://cloud.githubusercontent.com/assets/10943483/8967065/591f1c32-3667-11e5-97bc-7bc6d31d8e24.png)
![4](https://cloud.githubusercontent.com/assets/10943483/8967067/59aeb194-3667-11e5-9b31-fb1a4b1b6ad8.png)
但是kh.google.com 仍然过不去

**Comment by gaofenglv** [comment]
把红字贴出来：[07.30 03:07:32] googleearth.exe - pki.google.com:443 HTTP connection error : Client sent incorrect HTTP request. Please make sure that client uses HTTP protocol.

**Comment by xxnet** [comment]
proxifier 没有开源，只能猜测。

googleearth.exe - pki.google.com:443 HTTP connection error : Client sent
incorrect HTTP request. Please make sure that client uses HTTP protocol.
从日志理解，是proxifier认为google earth没有使用HTTP协议请求，还没有到XX-Net。

443端口是HTTPS加密协议，会不会proxifier 区别对待http和https？
试试 讲127.0.0.1:8087 设置为HTTPS？





2015-07-30 3:10 GMT+08:00 gaofenglv <notifications@github.com>:

**Comment by ARwMq9b6** [comment]
Proxifier 不是默认隐藏 HTTP 选项的吗，你是手动调了出来吧。以前用 Proxifier 使 Google Earth 使用 GoAgent 的代理是能用的。

**Comment by gaofenglv** [comment]
http测试可以通过 但是https测试就通不过
![1](https://cloud.githubusercontent.com/assets/10943483/9001607/300a188a-378c-11e5-8fdd-888af5da5fed.png)
![2](https://cloud.githubusercontent.com/assets/10943483/9001608/300ebfca-378c-11e5-93ad-762f4f266b0b.png)
我不知道是设置的原因 还是什么原因

**Comment by xxnet** [comment]
https测试通不过，应该是证书检测失败了。
如果Google Earth 用了HTTPS（从前面的日志看端口，是这样的），会不会是Google Earth检查了证书？
可以试试wireshark 抓包分析，看在什么阶段中断了。

proxifier 没有开源，只能猜测。
这块似乎就没有开源的解决方案，埃！

2015-07-31 13:59 GMT+08:00 gaofenglv <notifications@github.com>:

**Comment by gaofenglv** [comment]
google earth选项里有"使用https与google通信“一项，不过开着proxifier和xxnet时，勾不勾选都连不上
![qq](https://cloud.githubusercontent.com/assets/10943483/9022361/1965ad82-38a5-11e5-8c98-d7b039fd0718.png)
proxifier这个东西，http可以测试通过，但是https就通不过，如下图google.com:80连接不上
![2](https://cloud.githubusercontent.com/assets/10943483/9022360/194e3724-38a5-11e5-82a0-654732dc7645.png)
当开着xxnet时，kh.google.com这个地址是报错的
![qq 3](https://cloud.githubusercontent.com/assets/10943483/9022362/19a8cc66-38a5-11e5-9406-beec5b6f8bc0.png)
大家也看下proxifier的错误信息，下图就是
![4](https://cloud.githubusercontent.com/assets/10943483/9022365/2489824c-38a5-11e5-9479-56b8420d02d8.png)
问题是不是有点明显？就是xxnet也就是goagent，对https支持不太好，kh.google.com和google.com:80连接不上
问题在上面的图片都很清楚，但是就缺个明白人给我们指条明路，或者说清楚为什么

**Comment by xxnet** [comment]
https://kh.google.com/ 用shadowsocks 也是404

另外，GAE方式的https，都是替换证书的，对于浏览器，可以统一加入证书，对于特定的应用程序，你需要知道怎么加入可信证书，每一个应用程序采用的方式都可能不同。
这点对于手机app更加明显。



在 2015年8月1日 下午11:34，gaofenglv <notifications@github.com>写道：

**Comment by gaofenglv** [comment]
谢谢各位 按你们指导 我又google了好一会  结果最后发现问题真他妈简单 googleearth用的是系统默认的internet设置，在控制面板里把internet项设置成走代理就可以了
但要注意，开启程序时，我这里仍然提示无法连接服务器，但是你不要管，点否，他自己可以连上服务器的
晕了 问题竟然这么简单就解决了
谢谢各位关注

**Comment by xxnet** [comment]
恭喜!

看来是proxifier 引入更多问题

在 2015年8月4日 下午11:14，gaofenglv <notifications@github.com>写道：

**Comment by liangliangge521** [comment]
你好gaofenglv 具体方法怎么在控制面板里把internet项设置成走代理

**Comment by jzp820927** [comment]
百度一下，你就知道
