### ISSUE TITLE
2.05 以上版本都不能连接，还是回到2.02吧

### ISSUE THREAD

**Issue by textformat** [XX-net/XX-Net#738]
关键是不能升级，一升级就no gfw ip，完全无法使用。2.02目前健在。

**Comment by HUMORCE** [comment]
可以啊

**Comment by hyskyder** [comment]
我05用得挺好。楼主这种只评论一下，不给出任何可分析资料的帖子毫无意义啊，连参数、日志都没有，这种请不要发issue，找个论坛灌水区抱怨就行了。
