### ISSUE TITLE
北京联通IPv4 IP段已经恢复

### ISSUE THREAD

**Issue by spearheartee** [XX-net/XX-Net#7410]
搞了两天用teredo连接IPv6也没能成功，刚刚突然扫到IPv4地址了，瞬间满血复活。

**Comment by spearheartee** [comment]
不过封锁仍然比往常要严重，有时候只有几个IP可以用，怀疑是GFW资源有限撑不住如此大规模的IP封锁

**Comment by shujunwu** [comment]
联通能用的ip到电信全死？
好在我有两个网络选择！

**Comment by GoodSake** [comment]
gfw可能是个1u的设备，各地机房连小县城都给硬装几个，所有cn gfw一天电费就上亿，哈哈。

**Comment by joycegirl** [comment]
GFW资源是无限的，别少看国家的力量

**Comment by GoodSake** [comment]
不过对XX-net来说，就是没用的垃圾了。。。

**Comment by carotin** [comment]
@GoodSake 新疆的今天就是咱们的明天.朝鲜的后天。

**Comment by joycegirl** [comment]
新疆没有办法，异族之地，现在还好了，参考王震治疆

**Comment by roc1010kmt** [comment]
浪費這麼多維穩費用，可以救活多少窮人。

**Comment by spearheartee** [comment]
看来是我想太多了，今天早上IP又全部被封锁了
