### ISSUE TITLE
我的联通网络还是有问题

### ISSUE THREAD

**Issue by zpc870921** [XX-net/XX-Net#7437]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.7 Safari/537.36
xxnet-version: 3.7.0
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:10731
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by zpc870921** [comment]
一直显示尚未建立连接

**Comment by zpc870921** [comment]
我的网络是北京市铁通

**Comment by zpc870921** [comment]
状态页：

属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 0
空闲 | 0
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
扫描IP线程数(设置) | 10
屏蔽状态(帮助) | OK

**Comment by klcb2010** [comment]
证书和浏览器代理问题不知道排查？

**Comment by fanmingming** [comment]
之前一直都好使，从昨天开始IPV6也不行了。和你一样的状态，显示尚未连接！

**Comment by zpc870921** [comment]
升级到3.7了可以了，没有问题！
