### ISSUE TITLE
求助，XX-NET部署无法弹出认证窗口

### ISSUE THREAD

**Issue by rongan123** [XX-net/XX-Net#7441]
按照这里的教程一步一步做的，前面没什么问题，但是到了部署界面点击“开始部署”，没有反应。

详见附图：
![-1](https://user-images.githubusercontent.com/32898516/31728944-3f65d6ea-b460-11e7-8f12-50a9fc6b69f6.jpg)

![-3](https://user-images.githubusercontent.com/32898516/31728980-5d0b7bdc-b460-11e7-9e30-09f9275a51c8.jpg)

如果还需要提供什么信息，请告知。小白求帮忙，万分感谢。

**Comment by vvvyyy** [comment]
用最新版

**Comment by onplus** [comment]
3.6.15的网页bug，更新版本即可。

另外教程里有用脚本部署的备选项

**Comment by rongan123** [comment]
用3.6.16版本搞定，非常感谢回答问题的各位~~~
