### ISSUE TITLE
求助：gaeproxy状态信息显示：请等待大约2小时，XX-Net需要扫描IP。

### ISSUE THREAD

**Issue by panjinhua** [XX-net/XX-Net#7443]
本来以为要等2个小时，但是我等了一天一夜。。。。依旧没有ＩＰ可用。
日志里显示的都是类似的东西。。。。
Oct 19 08:24:27.504 - [DEBUG] create ssl timeout fail.
Oct 19 08:24:27.504 - [WARNING] no enough ip
Oct 19 08:25:27.639 - [DEBUG] create ssl timeout fail.
Oct 19 08:25:27.639 - [WARNING] no enough ip
Oct 19 08:25:29.174 - [WARNING] no enough ip
Oct 19 08:25:30.184 - [WARNING] no enough ip
Oct 19 08:25:31.187 - [WARNING] no enough ip

哪位大神帮个忙？

**Comment by whhxmwhh** [comment]
你要更换你的网络服务商。用中国移动的吧。要问一下是否支持IPV6。
然后在xx-net只界面设置启用IPV6.
等待几分钟就好了。

**Comment by hzjnet** [comment]
电信不能用吗？

**Comment by KILAsteins** [comment]
我用电信，同遇到这种情况

**Comment by kevinlau2015** [comment]
等会开完再说吧。

**Comment by whhxmwhh** [comment]
电信的我没用。所以不知道。你可以在安装的时候确认。如果可以才安装，他们会帮你开通的。
联通的用过是可以的。移动有人反映是可以的。

**Comment by GoodSake** [comment]
云南电信ipv6正常。

**Comment by fanmingming** [comment]
内蒙古联通 IPV6 全部失效！

**Comment by panjinhua** [comment]
我家里的电脑和公司的电脑用的是同一个版本的xx-net，但是公司的能用，全是移动网。家里的一直可以用，就2个星期吧，没用xx-net，等想用时就变成这情况了.......想不通为什么
