### ISSUE TITLE
IPV6 昨天可以用， 今天用不了了

### ISSUE THREAD

**Issue by AbelaroJiang** [XX-net/XX-Net#7445]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
xxnet-version: 3.7.0
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

扫描不到IP了， 

最上面显示：You may want to turn on IP scanner.

**Comment by cym104** [comment]
开了ipv6以后出scanner报警是正常的。你去日志页面看看是不是有连接请求一直在尝试

**Comment by AbelaroJiang** [comment]
嗯， 好的， 不过我重启电脑了之后， 现在恢复正常了， 现在翻墙封得太严了。 
感谢XX-net 所做的所有工作.
