### ISSUE TITLE
只能上谷歌和youtube,非谷歌系的网站上不去

### ISSUE THREAD

**Issue by tb9821146** [XX-net/XX-Net#749]
Property	Value
XX-Net Version	2.0.5
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

无论用公共appid还是自己部署的appid，都无法打开非谷歌系的网站...

**Comment by xxnet** [comment]
确认证书是否安装，无法打开提示什么？
日志贴出来分析

2015-07-30 11:08 GMT+08:00 tb9821146 <notifications@github.com>:

**Comment by tb9821146** [comment]
没有提示，就只有浏览器打不开页面的“无法显示此页”...
下面放上日志，分别打开youtube和无法打开btdigg.org时的日志记录：
Jul 31 15:14:51 - [INFO] load ip range file:C:\Users\biostar\Desktop\XX-Net-2.0.5\data\gae_proxy\ip_range.txt
Jul 31 15:14:51 - [INFO] load google ip_list num:137, gws num:137
Jul 31 15:14:51 - [INFO] SSL use version:TLSv1
Jul 31 15:14:51 - [INFO] ------------------------------------------------------ GAEProxy Version : gae_proxy (python/2.7.9 ) Listen Address : 127.0.0.1:8087 GAE APPID : lxp609652231 Pac Server : http://127.0.0.1:8086/proxy.pac ------------------------------------------------------
Jul 31 15:14:52 - [DEBUG] get ip:103.7.200.79 t:460
Jul 31 15:14:53 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Jul 31 15:14:53 - [DEBUG] get ip:128.0.169.216 t:499
Jul 31 15:14:53 - [DEBUG] get ip:128.0.169.217 t:509
Jul 31 15:14:53 - [DEBUG] get ip:128.0.169.225 t:517
Jul 31 15:14:54 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=cb5fa31e-0260-49e9-be0e-b2743ff009a5&version=2.0.5
Jul 31 15:14:54 - [DEBUG] get ip:128.0.169.249 t:531
Jul 31 15:14:54 - [DEBUG] get ip:128.0.169.250 t:572
Jul 31 15:14:54 - [DEBUG] get ip:128.0.169.218 t:600
Jul 31 15:14:54 - [DEBUG] get ip:128.0.169.212 t:676
Jul 31 15:14:54 - [DEBUG] create_ssl update ip:128.0.169.225 time:489
Jul 31 15:14:54 - [DEBUG] get ip:128.0.169.243 t:705
Jul 31 15:14:54 - [DEBUG] create_ssl update ip:128.0.169.216 time:1160
Jul 31 15:14:54 - [DEBUG] get ip:128.0.86.197 t:719
Jul 31 15:14:54 - [DEBUG] create_ssl update ip:128.0.169.250 time:486
Jul 31 15:14:54 - [DEBUG] create_ssl update ip:128.0.169.249 time:565
Jul 31 15:14:55 - [DEBUG] create_ssl update ip:128.0.169.218 time:493
Jul 31 15:14:55 - [INFO] DIRECT t:1289 s:1674 200 xxnet-update.appspot.com /update.json?uuid=cb5fa31e-0260-49e9-be0e-b2743ff009a5&version=2.0.5
Jul 31 15:14:55 - [INFO] GAE CONNECT raw.githubusercontent.com:443
Jul 31 15:14:55 - [DEBUG] GAE CONNECT GET https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md
Jul 31 15:14:55 - [DEBUG] get ip:128.0.86.218 t:720
Jul 31 15:14:55 - [DEBUG] get ip:128.0.169.246 t:927
Jul 31 15:14:55 - [DEBUG] create_ssl update ip:128.0.169.243 time:531
Jul 31 15:14:55 - [DEBUG] create_ssl update ip:128.0.169.212 time:1110
Jul 31 15:14:55 - [INFO] GAE t:401 s:3522 200 https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md
Jul 31 15:14:55 - [DEBUG] get ip:128.0.86.198 t:939
Jul 31 15:14:55 - [DEBUG] create_ssl update ip:128.0.169.217 time:1782
Jul 31 15:14:55 - [DEBUG] get ip:128.0.169.237 t:942
Jul 31 15:14:56 - [DEBUG] get ip:128.0.86.232 t:947
Jul 31 15:14:56 - [DEBUG] create_ssl update ip:128.0.169.246 time:501
Jul 31 15:14:56 - [DEBUG] get ip:128.0.169.228 t:949
Jul 31 15:14:56 - [DEBUG] create_ssl update ip:128.0.169.237 time:603
Jul 31 15:14:56 - [DEBUG] get ip:128.0.169.215 t:951
Jul 31 15:14:56 - [DEBUG] get ip:128.0.86.211 t:963
Jul 31 15:14:57 - [DEBUG] create_ssl update ip:128.0.86.232 time:725
Jul 31 15:14:57 - [DEBUG] get ip:128.0.86.247 t:965
Jul 31 15:14:57 - [DEBUG] create_ssl update ip:128.0.86.197 time:2319
Jul 31 15:14:57 - [DEBUG] create_ssl update ip:128.0.86.211 time:756
Jul 31 15:14:58 - [DEBUG] create_ssl update ip:128.0.169.228 time:1237
Jul 31 15:14:58 - [DEBUG] create_ssl update ip:103.7.200.79 time:5381
Jul 31 15:14:58 - [DEBUG] create_ssl 103.7.200.79 fail: certficate is none cost:5909 h:5381
Jul 31 15:14:59 - [DEBUG] create_ssl update ip:128.0.169.215 time:2151
Jul 31 15:14:59 - [DEBUG] create_ssl update ip:128.0.86.198 time:794
Jul 31 15:14:59 - [DEBUG] create_ssl update ip:128.0.86.218 time:3612
Jul 31 15:14:59 - [DEBUG] create_ssl update ip:128.0.86.247 time:1822
Jul 31 15:15:06 - [INFO] scan_ip add ip:128.0.86.199 time:934
Jul 31 15:15:49 - [DEBUG] get ip:128.0.169.250 t:486
Jul 31 15:15:49 - [DEBUG]LOG_EXCEPT: get ip:128.0.169.225 t:489, Except:[Errno 9] Bad file descriptor
Jul 31 15:15:50 - [DEBUG] get ip:128.0.169.218 t:493
Jul 31 15:15:50 - [DEBUG] create_ssl update ip:128.0.169.225 time:490
Jul 31 15:15:50 - [DEBUG] create_ssl update ip:128.0.169.250 time:522
Jul 31 15:15:50 - [DEBUG] create_ssl update ip:128.0.169.218 time:506
Jul 31 15:15:51 - [DEBUG] get ip:128.0.169.246 t:501
Jul 31 15:15:51 - [DEBUG] get ip:128.0.169.243 t:531
Jul 31 15:15:51 - [DEBUG] get ip:128.0.169.249 t:565
Jul 31 15:15:51 - [DEBUG] get ip:128.0.169.216 t:599
Jul 31 15:15:52 - [DEBUG] create_ssl update ip:128.0.169.246 time:496
Jul 31 15:15:52 - [DEBUG] create_ssl update ip:128.0.169.249 time:575
Jul 31 15:15:52 - [DEBUG] create_ssl update ip:128.0.169.243 time:835
Jul 31 15:15:53 - [DEBUG] get ip:128.0.169.237 t:603
Jul 31 15:15:53 - [DEBUG] create_ssl update ip:128.0.169.216 time:1150
Jul 31 15:15:53 - [DEBUG] get ip:128.0.169.217 t:609
Jul 31 15:15:53 - [DEBUG] get ip:128.0.86.232 t:725
Jul 31 15:15:53 - [DEBUG] create_ssl update ip:128.0.169.237 time:558
Jul 31 15:15:54 - [DEBUG] get ip:128.0.86.211 t:756
Jul 31 15:15:54 - [DEBUG] create_ssl update ip:128.0.86.232 time:695
Jul 31 15:15:54 - [DEBUG] get ip:128.0.169.212 t:776
Jul 31 15:15:54 - [DEBUG] create_ssl update ip:128.0.169.217 time:1351
Jul 31 15:15:55 - [DEBUG] create_ssl update ip:128.0.86.211 time:722
Jul 31 15:15:55 - [DEBUG] create_ssl update ip:128.0.169.212 time:480
Jul 31 15:16:42 - [DEBUG] get ip:128.0.169.212 t:480
Jul 31 15:16:43 - [DEBUG] create_ssl update ip:128.0.169.212 time:495
Jul 31 15:16:44 - [DEBUG] get ip:128.0.169.225 t:490
Jul 31 15:16:45 - [DEBUG] get ip:128.0.169.246 t:496
Jul 31 15:16:45 - [DEBUG] create_ssl update ip:128.0.169.225 time:488
Jul 31 15:16:45 - [DEBUG] get ip:128.0.169.218 t:506
Jul 31 15:16:45 - [DEBUG] get ip:128.0.169.250 t:522
Jul 31 15:16:46 - [DEBUG] create_ssl update ip:128.0.169.246 time:487
Jul 31 15:16:46 - [DEBUG] create_ssl update ip:128.0.169.218 time:519
Jul 31 15:16:46 - [DEBUG] get ip:128.0.169.237 t:558
Jul 31 15:16:46 - [DEBUG] create_ssl update ip:128.0.169.250 time:509
Jul 31 15:16:47 - [DEBUG] create_ssl update ip:128.0.169.237 time:554
Jul 31 15:16:47 - [DEBUG] get ip:128.0.169.249 t:575
Jul 31 15:16:47 - [DEBUG] get ip:128.0.169.243 t:631
Jul 31 15:16:48 - [DEBUG] get ip:128.0.86.232 t:695
Jul 31 15:16:48 - [DEBUG] get ip:128.0.169.216 t:699
Jul 31 15:16:48 - [DEBUG] create_ssl update ip:128.0.169.243 time:493
Jul 31 15:16:49 - [DEBUG] create_ssl update ip:128.0.169.249 time:1468
Jul 31 15:16:49 - [DEBUG] create_ssl update ip:128.0.86.232 time:775
Jul 31 15:16:49 - [DEBUG] get ip:128.0.169.217 t:709
Jul 31 15:16:50 - [DEBUG] get ip:128.0.86.211 t:722
Jul 31 15:16:50 - [DEBUG] get ip:128.0.86.198 t:794
Jul 31 15:16:51 - [DEBUG] create_ssl update ip:128.0.169.217 time:1707
Jul 31 15:16:51 - [DEBUG] create_ssl update ip:128.0.86.198 time:789
Jul 31 15:16:51 - [DEBUG] create_ssl update ip:128.0.86.211 time:1165
Jul 31 15:16:52 - [DEBUG] create_ssl update ip:128.0.169.216 time:4214
Jul 31 15:17:25 - [INFO] scan_ip add ip:128.0.86.213 time:759
Jul 31 15:17:38 - [DEBUG] get ip:128.0.169.246 t:487
Jul 31 15:17:39 - [DEBUG] get ip:128.0.169.225 t:488
Jul 31 15:17:39 - [DEBUG] create_ssl update ip:128.0.169.246 time:509
Jul 31 15:17:39 - [DEBUG] create_ssl update ip:128.0.169.225 time:483
Jul 31 15:17:40 - [DEBUG] get ip:128.0.169.243 t:493
Jul 31 15:17:40 - [DEBUG] get ip:128.0.169.212 t:495
Jul 31 15:17:41 - [DEBUG] create_ssl update ip:128.0.169.243 time:536
Jul 31 15:17:41 - [DEBUG] get ip:128.0.169.250 t:509
Jul 31 15:17:41 - [DEBUG] create_ssl update ip:128.0.169.212 time:503
Jul 31 15:17:42 - [DEBUG] create_ssl update ip:128.0.169.250 time:485
Jul 31 15:17:42 - [DEBUG] get ip:128.0.169.218 t:519
Jul 31 15:17:42 - [DEBUG] get ip:128.0.169.237 t:554
Jul 31 15:17:43 - [DEBUG] create_ssl update ip:128.0.169.218 time:509
Jul 31 15:17:43 - [DEBUG] create_ssl update ip:128.0.169.237 time:546
Jul 31 15:17:44 - [DEBUG] get ip:128.0.169.249 t:675
Jul 31 15:17:44 - [DEBUG] get ip:128.0.86.213 t:759
Jul 31 15:17:44 - [DEBUG] get ip:128.0.86.232 t:775
Jul 31 15:17:45 - [DEBUG]LOG_EXCEPT: create_ssl update ip:128.0.169.249 time:565, Except:[Errno 9] Bad file descriptor
Jul 31 15:17:45 - [DEBUG] create_ssl update ip:128.0.86.213 time:749
Jul 31 15:17:45 - [DEBUG] create_ssl update ip:128.0.86.232 time:726
Jul 31 15:18:12 - [INFO] scan_ip add ip:128.0.169.220 time:510
Jul 31 15:18:32 - [DEBUG] get ip:128.0.169.225 t:483
Jul 31 15:18:32 - [DEBUG] get ip:128.0.169.250 t:485
Jul 31 15:18:33 - [DEBUG] create_ssl update ip:128.0.169.225 time:507
Jul 31 15:18:33 - [DEBUG] create_ssl update ip:128.0.169.250 time:490
Jul 31 15:18:34 - [DEBUG] get ip:128.0.169.212 t:503
Jul 31 15:18:34 - [DEBUG] get ip:128.0.169.246 t:509
Jul 31 15:18:34 - [DEBUG] create_ssl update ip:128.0.169.212 time:497
Jul 31 15:18:35 - [DEBUG] create_ssl update ip:128.0.169.246 time:1075
Jul 31 15:18:35 - [DEBUG] get ip:128.0.169.218 t:509
Jul 31 15:18:36 - [DEBUG] get ip:128.0.169.220 t:510
Jul 31 15:18:36 - [DEBUG] create_ssl update ip:128.0.169.218 time:510
Jul 31 15:18:36 - [DEBUG] create_ssl update ip:128.0.169.220 time:480
Jul 31 15:18:36 - [DEBUG] get ip:128.0.169.243 t:536
Jul 31 15:18:37 - [DEBUG] get ip:128.0.169.237 t:546
Jul 31 15:18:37 - [DEBUG] get ip:128.0.169.249 t:565
Jul 31 15:18:37 - [DEBUG] create_ssl update ip:128.0.169.243 time:528
Jul 31 15:18:38 - [DEBUG] create_ssl update ip:128.0.169.237 time:529
Jul 31 15:18:38 - [DEBUG] create_ssl update ip:128.0.169.249 time:569
Jul 31 15:18:38 - [DEBUG] get ip:128.0.86.232 t:726
Jul 31 15:18:39 - [DEBUG] get ip:128.0.86.213 t:749
Jul 31 15:18:39 - [DEBUG] get ip:128.0.86.198 t:789
Jul 31 15:18:39 - [DEBUG] create_ssl update ip:128.0.86.232 time:697

**Comment by xxnet** [comment]
日志里没有访问记录，是不是没有设置好代理？
  推荐Chrome + switchysharp

2015-07-31 15:24 GMT+08:00 tb9821146 <notifications@github.com>:

**Comment by tb9821146** [comment]
的确是没有设置代理，谢谢

**Comment by simonasd** [comment]
已将此问题记载到Wiki的[故障速查手册](https://github.com/XX-net/XX-Net/wiki/%E6%95%85%E9%9A%9C%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8C)中。

**Comment by acmeid** [comment]
我装完了，成功部署，但是访问不了YouTube，是不是还要设置代理，怎么设置？
