### ISSUE TITLE
导入IP的bug

### ISSUE THREAD

**Issue by clouduan** [XX-net/XX-Net#7498]
用的Ubuntu+Win10双系统，在Windows上面正常使用，Ubuntu上面扫描不到IP。
于是我在Windows下用xxnet导出IP，试着在Ubuntu下将其导入，结果显示**导入了0条IP**，好几个版本都是如此。
这是bug？还是我的导入姿势不对？
![default](https://user-images.githubusercontent.com/20282795/31822257-bd827ba2-b5da-11e7-960a-c7ac6621c99f.PNG)

**Comment by onplus** [comment]
ipv6功能不全。

直接复制data/gaeproxy/goodipv6.txt

**Comment by clouduan** [comment]
嗯果然ipv6功能不太完善，可是我复制了ipv6.txt，过了一会而IP还是变为0了，大概是系统的问题了。。。

**Comment by xxnet** [comment]
​ipv6不需要导，目前未收到封ipv6的报告。

关键是操作系统要开启ipv6 隧道。

**Comment by clouduan** [comment]
好的感谢两位解惑。
