### ISSUE TITLE
安卓手机可以通过XX-NET上网么

### ISSUE THREAD

**Issue by theguy111** [XX-net/XX-Net#75]
比如电脑使用XX-NET代理后，共享网络给手机，可行么？

**Comment by xxnet** [comment]
这个方案不好，只要是需要加密的https的网站，都需要导入证书，操作太麻烦了。
而且手机离开电脑，就要重新设置代理，使用起来非常不方便。

还是fqrouter好。

在 2015年3月22日 下午12:36，theguy111 <notifications@github.com>写道：

**Comment by theguy111** [comment]
不懂这么多，看来不可行....用了fqrouter，确实不错

**Comment by lele2010lele** [comment]
请问你是如何部署的fqrouter的啊

**Comment by xxnet** [comment]
没有部署，直接下载就用了

2015-04-03 0:06 GMT-04:00 lele2010lele <notifications@github.com>:

**Comment by siterkiso** [comment]
推特用FQ上不了啊。

**Comment by ycfriend** [comment]
FQ基本不能用了，市场不能下载

**Comment by boxsnake** [comment]
我是用Fiddler挂载到127.0.0.1，然后再把手机的代理设置为 电脑IP:888 （Fiddler代理的地址）实现的。
注意，Fiddler里面有个代理HTTPS请求，也勾上，另外Fiddler设置代理端口的地方有个填代理协议的，写https和http
