### ISSUE TITLE
升级功能有bug？？

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#7508]
3.6.15，不确定是怎么回事，手动在浏览器输入了更新指令，web出来一个奇怪的东西

![default](https://user-images.githubusercontent.com/12052610/31847950-08ce3410-b659-11e7-92d2-a5d4c8c6ae7d.png)

    10月 21 12:07:27.7 - [DEBUG] launcher web_control 127.0.0.1:37850 GET /update?cmd=update_version&version=3.7.2 
    10月 21 12:07:27.7 - [INFO] download https://codeload.github.com/XX-net/XX-Net/zip/3.7.2 to  /XX-Net/data/downloads/XX-Net-3.7.2.zip, retry:0
    10月 21 12:07:46.4 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to  /XX-Net/data/downloads/version.txt, retry:0
    10月 21 12:07:47.0 - [WARNING] update version 3.7.2 fail:TypeError("object of type 'NoneType' has no len()",)
    10月 21 12:07:50.0 - [DEBUG] launcher web_control 127.0.0.1:37850 GET /config?cmd=get_config 
    10月 21 12:07:50.1 - [DEBUG] x_tunnel force update info
    10月 21 12:07:50.1 - [DEBUG] launcher web_control 127.0.0.1:37846 GET /update?cmd=get_progress

**Comment by wooowooo** [comment]
好吧，我看到button有被修复。

**Comment by SeaHOH** [comment]
必然失败吗，重试过没？

**Comment by onplus** [comment]
因为未发布版本不能校验吗？
https://github.com/XX-net/XX-Net/blob/master/code/default/update_version.txt

**Comment by SeaHOH** [comment]
所以并没有 3.7.2 推送，手动也检测不到。

**Comment by wooowooo** [comment]
原来如此

**Comment by wooowooo** [comment]
@SeaHOH 

![default](https://user-images.githubusercontent.com/12052610/31857170-56c84e52-b709-11e7-9796-8671765bc169.png)

**Comment by SeaHOH** [comment]
3.7.3 已推送，有什么问题吗？

**Comment by wooowooo** [comment]
那个 下载中 显示成按钮了。是3.7.2版的

**Comment by SeaHOH** [comment]
是的，直接套用的按钮样式，你们可以继续修改，我折腾不来。

**Comment by wooowooo** [comment]
好吧，我看看，把它弄成长条的tip样子
