### ISSUE TITLE
看到一个replace google cdn的项目

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#752]
https://github.com/justjavac/ReplaceGoogleCDN
这个项目也没有具体写这个项目，想问一下，这个对xx-net有没有什么帮助？能不能提高性能？另外，这个安全吗？安装插件的时候提示，它可以查看上网的所有信息。

**Comment by xxnet** [comment]
从项目主页上看，只是对静态内容的加速，换到国内的供应商。
对翻墙没有帮助。

谢谢提供消息 :-)

在 2015年7月31日 下午3:37，cdmask <notifications@github.com>写道：

**Comment by cdmask** [comment]
不客气～
