### ISSUE TITLE
无法上网，报错

### ISSUE THREAD

**Issue by gypsygypsy** [XX-net/XX-Net#753]
配置后无法上网

**Comment by gypsygypsy** [comment]
Jul 31 17:27:22 - [DEBUG] GAEProxy web_control 127.0.0.1:58836 POST /scan_ip?cmd=set_scan_thread_num
Jul 31 17:27:22 - [WARNING] launcher.config save user config fail:C:\��\XX-Net-2.0.5\data\gae_proxy\config.ini
Jul 31 17:27:22 - [INFO] Adjust scan thread num from 5 to 10
Jul 31 17:27:24 - [DEBUG] GAEProxy web_control 127.0.0.1:58843 POST /scan_ip?cmd=set_scan_thread_num
Jul 31 17:27:24 - [WARNING] launcher.config save user config fail:C:\��\XX-Net-2.0.5\data\gae_proxy\config.ini
Jul 31 17:27:27 - [DEBUG] GAEProxy Web_control 127.0.0.1:58849 GET /scan_ip?cmd=get_scan_ip_log
Jul 31 17:27:45 - [DEBUG] GAEProxy Web_control 127.0.0.1:58915 GET /deploy?cmd=get_log
Jul 31 17:27:53 - [DEBUG] GAEProxy web_control 127.0.0.1:58932 POST /config?cmd=get_config
Jul 31 17:31:09 - [DEBUG] GAEProxy Web_control 127.0.0.1:59673 GET /deploy?cmd=get_log
Jul 31 17:33:44 - [DEBUG] GAEProxy web_control 127.0.0.1:60731 POST /config?cmd=get_config
Jul 31 17:33:46 - [DEBUG] GAEProxy web_control 127.0.0.1:60738 POST /config?cmd=set_config
Jul 31 17:33:46 - [WARNING] launcher.config save user config fail:C:\��\XX-Net-2.0.5\data\gae_proxy\config.ini
Jul 31 17:33:49 - [DEBUG] GAEProxy Web_control 127.0.0.1:60744 GET /deploy?cmd=get_log
Jul 31 17:34:04 - [DEBUG] GAEProxy Web_control 127.0.0.1:60784 GET /scan_ip?cmd=get_range
Jul 31 17:34:04 - [INFO] load ip range file:C:\��\XX-Net-2.0.5\data\gae_proxy\ip_range.txt
Jul 31 17:34:04 - [DEBUG] GAEProxy Web_control 127.0.0.1:60785 GET /scan_ip?cmd=get_scan_ip_log
Jul 31 17:34:04 - [DEBUG] GAEProxy web_control 127.0.0.1:60786 POST /config?cmd=get_config
Jul 31 17:34:08 - [DEBUG] GAEProxy web_control 127.0.0.1:60791 POST /scan_ip?cmd=set_scan_thread_num
Jul 31 17:34:08 - [WARNING] launcher.config save user config fail:C:\��\XX-Net-2.0.5\data\gae_proxy\config.ini
Jul 31 17:34:08 - [INFO] Adjust scan thread num from 50 to 10
Jul 31 17:34:21 - [DEBUG] GAEProxy web_control 127.0.0.1:60822 POST /importip?cmd=importip

**Comment by gypsygypsy** [comment]
状态页如下
Property	Value
XX-Net Version	2.0.5
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	368
100th IP handshake(ms)	1342
connected link(帮助)	0,0
scaning ip thread num	10
block stat(帮助)	OK
Appid

**Comment by gypsygypsy** [comment]
好了 看来是拼人品···
状态

Property	Value
Google IP num	371
100th IP handshake(ms)	1264
connected link(帮助)	11,2
scaning ip thread num	50
block stat(帮助)	OK

**Comment by cdmask** [comment]
都解决问题了，issue就关掉呗-
