### ISSUE TITLE
管理帮我看看我充值的tunnel流量显示不正确吧

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#7535]
我冲的是3个月的。。。这个地方好像不能上图吧。。。3个月的是不是应该显示有几个g的流量，我显示的是600多m，正确吗

**Comment by onplus** [comment]
余额显示？

传图可能需要梯子

**Comment by Zmm1977** [comment]
![image](https://user-images.githubusercontent.com/27794050/31860889-b9e98a5a-b754-11e7-8751-793efd10a99d.png)

**Comment by xxnet** [comment]
​x-tunnel 帐号发我邮箱
 xxnet.dev@gmail.com

**Comment by yuyistar** [comment]
@xxnet 已发送

**Comment by xxnet** [comment]
​流量已恢复

**Comment by yuyistar** [comment]
收到
