### ISSUE TITLE
GAEProxy状态信息显示：请等待大约2小时，XX-Net需要扫描IP  怎么解决啊啊啊啊？

### ISSUE THREAD

**Issue by panjinhua** [XX-net/XX-Net#7537]
新版的xx-net，日志显示的都是下面这些东西，哪位大神告诉我该怎么做？

Oct 22 21:19:21.697 - [WARNING] no enough ip
Oct 22 21:19:22.199 - [WARNING] no enough ip
Oct 22 21:19:22.700 - [WARNING] no enough ip
Oct 22 21:19:23.200 - [WARNING] no enough ip
Oct 22 21:19:23.702 - [WARNING] no enough ip
Oct 22 21:19:55.257 - [DEBUG] GAEProxy web_control 127.0.0.1:58549 POST /config?cmd=get_config
Oct 22 21:19:55.259 - [DEBUG] GAEProxy Web_control 127.0.0.1:58549 GET /scan_ip?cmd=get_range
Oct 22 21:19:55.259 - [INFO] load ip range file:D:\Program Files\GoEnglish\XX-Net-3.6.15\code\default\gae_proxy\local\ip_range.txt
Oct 22 21:19:56.722 - [DEBUG] GAEProxy web_control 127.0.0.1:58549 POST /config?cmd=get_config
Oct 22 21:20:19.216 - [DEBUG] create ssl timeout fail.
Oct 22 21:20:19.216 - [WARNING] no enough ip
Oct 22 21:20:19.718 - [WARNING] no enough ip
Oct 22 21:20:20.219 - [WARNING] no enough ip
Oct 22 21:20:20.720 - [WARNING] no enough ip
Oct 22 21:20:21.222 - [WARNING] no enough ip
Oct 22 21:20:21.723 - [WARNING] no enough ip
Oct 22 21:20:22.223 - [WARNING] no enough ip

**Comment by panjinhua** [comment]
我已经等了不知道多久了，没有一点反应...................

**Comment by liulinws** [comment]
IP减少太快的关系，很快就掉到0 了。先试试开启IPV6，如果仍然无效，恐怕需要等本月25日之后风头过了再试了

**Comment by shevchendov** [comment]
已经挂了一天都扫不了ip

**Comment by xxnet** [comment]
​这提示，也许应该改成： 试试去开启ipv6，然后给出ipv6开启的wiki指南

**Comment by dahai058** [comment]
晚上ipv4突然恢复了，89个ip 延迟368

**Comment by yuyuan5999** [comment]
win7旗舰版 广东联通 一直使用自己的30多个Appid
昨天重新安装XX-Net-3.7.2，然后悲剧的发现失败了
今天看了#7506这位亲的介绍 成功了 可以下载Y2B的视频 速度很快
步骤如下
1 控制面板---网络和共享中心--点本地连接---点属性---点tcp/IPv6----点属性---点 使用下面的DNS服务器---在上面一行复制黏贴 2001:4860:4860::8888 下面一行复制黏贴 2001:4860:4860::8844 ----确定

2 新建一个TXT文件，在里面复制黏贴这个

net start "ip helper"
netsh int ipv6 reset

netsh int teredo set state default
netsh int 6to4 set state default
netsh int isatap set state default
netsh int teredo set state server=teredo.remlab.net
netsh int ipv6 set teredo enterpriseclient
netsh int ter set state enterpriseclient
route DELETE ::/0
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
netsh int ipv6 set prefix 2002::/16 30 1
netsh int ipv6 set prefix 2001::/32 5 1
Reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f

netsh int teredo set state default
netsh int 6to4 set state default
netsh int isatap set state default
netsh int teredo set state server=teredo.remlab.net
netsh int ipv6 set teredo enterpriseclient
netsh int ter set state enterpriseclient
route DELETE ::/0
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
netsh int ipv6 set prefix 2002::/16 30 1
netsh int ipv6 set prefix 2001::/32 5 1
Reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters /v AddrConfigControl /t REG_DWORD /d 0 /f

ipconfig /all
ipconfig /flushdns
netsh int ipv6 show teredo
netsh int ipv6 show route
netsh int ipv6 show int
netsh int ipv6 show prefix
netsh int ipv6 show address
route print
cmd

3 关闭文件，重新命名为 IPV6.BAT 扩展名一定是BAT 才行
4 右键点 以管理员身份运行 ，文件打开后 等它自己运行结束再关闭
5 以管理员身份运行 XX-Net-3.7.2 里面的start.bat
6 等待 http://127.0.0.1:8085/?module=gae_proxy&menu=status 页面出现
在配置 ---高级选项---启用 使用IPv6(一般教育网才开)

就是这样了 希望能帮到大家

**Comment by LinTeX9527** [comment]
多谢楼主，楼主人好。

**Comment by Sinmoredella** [comment]
同样的情况

按照yuyuan5999介绍的方法运行bat文件 重启之后就活了！感谢！

**Comment by yangsl158** [comment]
非常感谢 @yuyuan5999 
可以用！！

**Comment by RJingwen** [comment]
这样弄完之后显示尚未建立连接怎么回事？

**Comment by yydzxz** [comment]
非常感谢 @yuyuan5999
可以用！！
