### ISSUE TITLE
google book无法访问

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#754]
O5feD_g&cp=0&gs_id=6&xhr=t&q=&tch=1&ech=4&psi=zzq8VZHgA4fue5vihagO.1438399192474.1
Aug 01 11:25:55 - [DEBUG] host_conn_pool www.google.com get:124.248.162.133 handshake:243
Aug 01 11:25:55 - [INFO] DIRECT chucked t:202 s:297 200 www.google.com /complete/search?client=hp&hl=en&gs_rn=64&gs_ri=hp&tok=PFxNETA-O7bVWI-O5feD_g&cp=0&gs_id=6&xhr=t&q=&tch=1&ech=4&psi=zzq8VZHgA4fue5vihagO.1438399192474.1
Aug 01 11:26:06 - [WARNING] gae_handler.handler send response fail. t:98 e:error(10053, '') https://books.google.cn/books/about/Induction_Machines_for_Special_Purposes.html?id=E37EAAAAIAAJ&redir_esc=y
Aug 01 11:26:06 - [WARNING] APPID error:502 url:https://books.google.cn/books/about/Induction_Machines_for_Special_Purposes.html?id=E37EAAAAIAAJ&redir_esc=y
Aug 01 11:26:06 - [WARNING] gae_handler err:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry') time:98 https://books.google.cn/books/about/Induction_Machines_for_Special_Purposes.html?id=E37EAAAAIAAJ&redir_esc=y
Aug 01 11:26:06 - [WARNING] APPID error:502 url:https://books.google.cn/books?id=jG8iXlT2ID0C&pg=PA592&lpg=PA592&dq=induction+machines+for+special+purposes&source=bl&ots=3z7O05Dpd0&sig=JV2xperlJx-tXp06pcIHUTHcoDQ&hl=en&sa=X&redir_esc=y
Aug 01 11:26:16 - [DEBUG] get ip:103.7.200.79 t:186
Aug 01 11:26:18 - [DEBUG] create_ssl update ip:103.7.200.79 time:2386
Aug 01 11:26:22 - [DEBUG] get ip:103.7.200.79 t:286
Aug 01 11:26:24 - [DEBUG] get ip:124.248.162.133 t:220
Aug 01 11:26:24 - [DEBUG] create_ssl update ip:103.7.200.79 time:2233
Aug 01 11:26:25 - [DEBUG] create_ssl update ip:124.248.162.133 time:210
Aug 01 11:26:27 - [INFO] GAE CONNECT books.google.cn:443
Aug 01 11:26:27 - [DEBUG] get ip:103.7.200.79 t:386
Aug 01 11:26:27 - [DEBUG] GAE CONNECT GET https://books.google.cn/favicon.ico
Aug 01 11:26:27 - [DEBUG] create_ssl update ip:103.7.200.79 time:296
Aug 01 11:26:28 - [DEBUG] get ip:128.0.169.220 t:687
Aug 01 11:26:28 - [DEBUG] get ip:31.55.163.133 t:695
Aug 01 11:26:28 - [DEBUG] get ip:61.91.18.247 t:1559
Aug 01 11:26:31 - [DEBUG] create_ssl update ip:128.0.169.220 time:1844
Aug 01 11:26:31 - [DEBUG] create_ssl update ip:31.55.163.133 time:2318
Aug 01 11:26:32 - [DEBUG] get ip:124.248.162.133 t:210
Aug 01 11:26:32 - [DEBUG] get ip:103.7.200.79 t:296
Aug 01 11:26:32 - [DEBUG] create_ssl update ip:124.248.162.133 time:233
Aug 01 11:26:32 - [DEBUG] create_ssl 61.91.18.247 fail:timed out cost:4000 h:0
Aug 01 11:26:33 - [DEBUG] get ip:128.0.169.220 t:787
Aug 01 11:26:33 - [DEBUG] create_ssl update ip:103.7.200.79 time:1219
Aug 01 11:26:34 - [DEBUG] get ip:31.55.163.133 t:795
Aug 01 11:26:34 - [INFO] GAE CONNECT www.google.com:443
Aug 01 11:26:34 - [DEBUG] GAE CONNECT GET https://www.google.com/complete/search?client=hp&hl=en&gs_rn=64&gs_ri=hp&tok=PFxNETA-O7bVWI-O5feD_g&cp=0&gs_id=8&xhr=t&q=&tch=1&ech=5&psi=zzq8VZHgA4fue5vihagO.1438399192474.1
Aug 01 11:26:35 - [INFO] DIRECT chucked t:199 s:296 200 www.google.com /complete/search?client=hp&hl=en&gs_rn=64&gs_ri=hp&tok=PFxNETA-O7bVWI-O5feD_g&cp=0&gs_id=8&xhr=t&q=&tch=1&ech=5&psi=zzq8VZHgA4fue5vihagO.1438399192474.1
Aug 01 11:26:35 - [DEBUG] create_ssl update ip:128.0.169.220 time:1411
Aug 01 11:26:35 - [DEBUG] create_ssl update ip:31.55.163.133 time:661
Aug 01 11:26:35 - [DEBUG] get ip:124.248.162.133 t:233
Aug 01 11:26:36 - [DEBUG] get ip:103.7.200.79 t:396
Aug 01 11:26:36 - [DEBUG]LOG_EXCEPT: get ip:128.0.169.220 t:887, Except:[Errno 9] Bad file descriptor
Aug 01 11:26:36 - [DEBUG] create_ssl update ip:124.248.162.133 time:424
Aug 01 11:26:36 - [INFO] GAE CONNECT www.google.com:443
Aug 01 11:26:36 - [DEBUG] GAE CONNECT GET https://www.google.com/complete/search?client=hp&hl=en&gs_rn=64&gs_ri=hp&tok=PFxNETA-O7bVWI-O5feD_g&cp=0&gs_id=a&xhr=t&q=&tch=1&ech=6&psi=zzq8VZHgA4fue5vihagO.1438399192474.1
Aug 01 11:26:36 - [INFO] DIRECT chucked t:154 s:297 200 www.google.com /complete/search?client=hp&hl=en&gs_rn=64&gs_ri=hp&tok=PFxNETA-O7bVWI-O5feD_g&cp=0&gs_id=a&xhr=t&q=&tch=1&ech=6&psi=zzq8VZHgA4fue5vihagO.1438399192474.1
Aug 01 11:26:37 - [DEBUG] get ip:143.215.193.232 t:1559
Aug 01 11:26:39 - [DEBUG] create_ssl update ip:103.7.200.79 time:631
Aug 01 11:26:40 - [DEBUG] get ip:124.248.162.133 t:333
Aug 01 11:26:41 - [DEBUG] create_ssl update ip:124.248.162.133 time:233
Aug 01 11:26:41 - [DEBUG] create_ssl 143.215.193.232 fail:timed out cost:4010 h:0
Aug 01 11:26:43 - [WARNING] gae_handler.handler send response fail. t:67 e:error(10053, '') https://books.google.cn/favicon.ico
Aug 01 11:26:43 - [WARNING] APPID error:502 url:https://books.google.cn/favicon.ico
Aug 01 11:26:43 - [WARNING] gae_handler err:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry') time:67 https://books.google.cn/favicon.ico
Aug 01 11:26:43 - [DEBUG] create_ssl update ip:128.0.169.220 time:6689
Aug 01 11:26:43 - [DEBUG] create_ssl 128.0.169.220 fail: certficate is none cost:6923 h:6689
Aug 01 11:26:47 - [INFO] GAE CONNECT www.google-analytics.com:443
Aug 01 11:26:47 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
Aug 01 11:26:47 - [DEBUG] get ip:124.248.162.133 t:233
Aug 01 11:26:47 - [INFO] DIRECT t:211 s:35 200 www.google-analytics.com /collect
Aug 01 11:26:47 - [DEBUG] create_ssl update ip:124.248.162.133 time:270
Aug 01 11:26:57 - [INFO] GAE CONNECT www.google-analytics.com:443
Aug 01 11:26:57 - [DEBUG] GAE CONNECT POST https://www.google-analytics.com/collect
Aug 01 11:26:57 - [DEBUG] host_conn_pool www.google-analytics.com get:124.248.162.133 handshake:233
Aug 01 11:26:57 - [INFO] DIRECT t:182 s:35 200 www.google-analytics.com /collect
Aug 01 11:27:05 - [INFO] GAE CONNECT www.gstatic.com:443
Aug 01 11:27:05 - [DEBUG] GAE CONNECT GET https://www.gstatic.com/generate_204
Aug 01 11:27:05 - [DEBUG] get ip:124.248.162.133 t:270
Aug 01 11:27:05 - [INFO] DIRECT t:607 204 www.gstatic.com /generate_204
Aug 01 11:27:05 - [DEBUG] create_ssl update ip:124.248.162.133 time:203
Aug 01 11:27:10 - [DEBUG] get ip:124.248.162.133 t:203
Aug 01 11:27:11 - [DEBUG] create_ssl update ip:124.248.162.133 time:233
Aug 01 11:27:13 - [WARNING] gae_handler.handler send response fail. t:46 e:error(10053, '') https://books.google.cn/favicon.ico
Aug 01 11:27:13 - [WARNING] APPID error:502 url:https://books.google.cn/favicon.ico
Aug 01 11:27:13 - [WARNING] gae_handler err:SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry') time:46 https://books.google.cn/favicon.ico
Aug 01 11:27:17 - [DEBUG] get ip:124.248.162.133 t:233
Aug 01 11:27:17 - [DEBUG] create_ssl update ip:124.248.162.133 time:244
Aug 01 11:27:19 - [INFO] GAE CONNECT www.google.com:443

**Comment by cdmask** [comment]
![default](https://cloud.githubusercontent.com/assets/11484898/9020477/b532dff6-3840-11e5-8593-1eb8f68b95c5.JPG)

**Comment by xxnet** [comment]
https://books.google.com/ 用这个

2015-08-01 11:31 GMT+08:00 cdmask <notifications@github.com>:

**Comment by cdmask** [comment]
我搜索的时候用的就是 https://books.google.com 然后书目搜索出来了之后点击书名，GAE就访问了book.google.cn 看09:21:35
Aug 03 09:21:34 - [DEBUG] create_ssl update ip:103.7.200.79 time:334
Aug 03 09:21:35 - [DEBUG] GAE CONNECT GET https://books.google.com/books?id=E37EAAAAIAAJ&q=induction+motors+for+special+purposes&dq=induction+motors+for+special+purposes&hl=en&sa=X&ved=0CCcQ6AEwAGoVChMI3LzjoN-LxwIVWAWOCh2qeQVm
Aug 03 09:21:35 - [INFO] DIRECT t:381 s:366 302 books.google.com /books?id=E37EAAAAIAAJ&q=induction+motors+for+special+purposes&dq=induction+motors+for+special+purposes&hl=en&sa=X&ved=0CCcQ6AEwAGoVChMI3LzjoN-LxwIVWAWOCh2qeQVm
Aug 03 09:21:35 - [INFO] GAE CONNECT books.google.cn:443
Aug 03 09:21:35 - [DEBUG] GAE CONNECT GET https://books.google.cn/books?id=E37EAAAAIAAJ&q=induction+motors+for+special+purposes&dq=induction+motors+for+special+purposes&hl=en&sa=X&redir_esc=y
Aug 03 09:21:35 - [DEBUG] ssl_pool.get:103.7.200.79 handshake:181
Aug 03 09:21:35 - [DEBUG] get ip:61.91.18.243 t:252
Aug 03 09:21:36 - [DEBUG] create_ssl update ip:61.91.18.243 time:296
Aug 03 09:21:38 - [DEBUG] get ip:61.91.18.90 t:266
Aug 03 09:21:38 - [DEBUG] get ip:103.7.200.79 t:334
Aug 03 09:21:38 - [DEBUG] create_ssl update ip:61.91.18.90 time:250
Aug 03 09:21:38 - [DEBUG] create_ssl update ip:103.7.200.79 time:539
Aug 03 09:21:40 - [DEBUG] get ip:128.0.169.217 t:593
Aug 03 09:21:40 - [DEBUG] get ip:128.0.169.232 t:600
Aug 03 09:21:41 - [DEBUG] create_ssl update ip:128.0.169.217 time:525
Aug 03 09:21:42 - [DEBUG] get ip:61.91.18.90 t:250
Aug 03 09:21:42 - [DEBUG] create_ssl update ip:61.91.18.90 time:259
Aug 03 09:21:43 - [DEBUG] create_ssl update ip:128.0.169.232 time:2394
Aug 03 09:21:43 - [INFO] GAE CONNECT clients4.google.com:443
Aug 03 09:21:43 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=2cZcc3Y5ctHVj1msukwvLw%3D%3D
Aug 03 09:21:43 - [DEBUG] host_conn_pool clients4.google.com get:61.91.18.243 handshake:246
Aug 03 09:21:44 - [INFO] DIRECT t:289 s:9704 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=2cZcc3Y5ctHVj1msukwvLw%3D%3D
Aug 03 09:21:44 - [INFO] GAE CONNECT clients4.google.com:443
Aug 03 09:21:44 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=2cZcc3Y5ctHVj1msukwvLw%3D%3D
Aug 03 09:21:44 - [DEBUG] host_conn_pool clients4.google.com get:61.91.18.243 handshake:246
Aug 03 09:21:44 - [INFO] DIRECT t:269 s:486 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=2cZcc3Y5ctHVj1msukwvLw%3D%3D
Aug 03 09:21:54 - [DEBUG] get ip:61.91.18.90 t:259
Aug 03 09:21:54 - [DEBUG] create_ssl update ip:61.91.18.90 time:252
Aug 03 09:21:55 - [DEBUG] get ip:61.91.18.243 t:296
Aug 03 09:21:56 - [DEBUG] create_ssl update ip:61.91.18.243 time:243
Aug 03 09:21:58 - [DEBUG] get ip:61.91.18.90 t:252
Aug 03 09:21:58 - [DEBUG] create_ssl update ip:61.91.18.90 time:254

**Comment by redstoneleo** [comment]
比如这个页面打不开
https://books.google.cn/books/p/princeton?id=lXjF7JnHQoIC&printsec=frontcover&hl=zh-CN&source=gbs_ViewAPI&redir_esc=y
你把cn换成ca应该就行了

**Comment by cdmask** [comment]
这样可以 谢谢。
