### ISSUE TITLE
证书状态始终是fail

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#7562]
今天下午两点多的时候最后一个ip阵亡了。
更奇葩的是不管重新导入，重新启动xx和google，删除某目录下所有证书，重启电脑，全都没用，始终是fail.
GAE Proxy Status Info

XX-Net is scanning IP. Please wait about half an hour.
Status

Property	Value
Local Network Status	OK
IP Number	0
Is Idle	0
IP Quality	9999
Connection Pool(Help)	new:0 h1:0 h2:0
Browser Proxy Setting	OK
CA status(Download)	Fail
Number of IP-Scanning Threads(Settings)	10
Block Status(Help)	OK

**Comment by pldeom** [comment]
可用，GFW居然还搞不死

**Comment by dylanleesky** [comment]
先全清ca证书，
然后管理员运行那个star.bat。会自动导入。
刷新试试。如果你的ca是旧的，建议删掉重新生成。旧的好像加密模式落后了、

**Comment by nly4lov** [comment]
@dylanleesky 我试试。

**Comment by cennong** [comment]
怎么全清ca证书

**Comment by MacSur** [comment]
看我的其它回复内容：

[ga](https://user-images.githubusercontent.com/9836713/31941586-ecfb469e-b8f4-11e7-8bd9-951798bb838b.JPG)

**Comment by carotin** [comment]
@cennong 删除旧的xx-net证书,重新导入新的就行，不要乱删其它证书。

**Comment by MacSur** [comment]
看我的其它回复内容：
![666](https://user-images.githubusercontent.com/9836713/31941748-795145d0-b8f5-11e7-9697-60b6e4c765ce.JPG)
CA证书状态(下载) | **Fail**

# **重新导入CA证书：**
方法：
    首先：关闭XX-Net程序，然后：
1. 删除：XX-Net-3.6.15\data\gae_proxy 目录下的certs【目录】、CA.crt 【证书文件】
2.重新启动，XX-Net程序会要求导入证书，点击同意。

另外：检查hotst文件，查看是否有其它被修改内容，有的话删除。或者，就复制以下内容后保存。
#windows xp/2003/vista/2008/7/8用户HOSTS文件是在 -   c:\windows\system32\drivers\etc

hotst 标准内容如下：

```
# Copyright (c) 1993-1999 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
127.0.0.1 localhost

```
hosts 参考内容：http://jingyan.baidu.com/article/9f7e7ec04dacc06f281554dd.html

https://github.com/XX-net/XX-Net/issues/7523#issuecomment-338887052

**Comment by styrenes** [comment]
安 “文档说明 ”里面的 指导 ，安装 ca

**Comment by nly4lov** [comment]
@dylanleesky 证书状态ok了，然仍没有一个ip

**Comment by LinTeX9527** [comment]
@MacSur 老哥，稳。。。
我昨天升级chrome浏览器，出现了CA证书FAIL的问题，按照你的步骤一折腾，果然可以了。

**Comment by dylanleesky** [comment]
@nly4lov 恩，因为老赵家开会，估计还要加上纽约某个某某贵先生的问题。封杀力度非常严。

**Comment by nly4lov** [comment]
@dylanleesky 仍然是成分感谢你，如果没有你的指点，我就开不了ipv6，现在就不能忽然恢复fq啦
https://github.com/XX-net/XX-Net/issues/7678
