### ISSUE TITLE
没有 IP 地址（开了 IPv6）

### ISSUE THREAD

**Issue by 71e6fd52** [XX-net/XX-Net#7569]
总 IP 数 为 0，扫描日志是空的

属性 | 值
-- | --
总 IP 数 | 0
剩余数 | 0
有效 IP 数 | 0
## 系统版本
属性 | 值
-- | --
XX-Net Version | 3.7.4
Python Version | 2.7.14
OpenSSL Version | 17.3.0 TLSv1_2 h2:alpn
System Platform | x86_64, Linux-4.13.5-1-lily-x86_64-with-glibc2.2.5
OS System | Linux
OS Version | #12 SMP PREEMPT Thu Oct 5 16:39:28 CST 2017
OS Release | 4.13.5-1-lily
OS Detail | Dist:; Version:; ID:
Language | zh_CN
Architecture | 64bit,
Browser | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

**Comment by lidawei1911** [comment]
我倒是开了Ipv6后ip上万。但是仍然无法建立链接。。

**Comment by styrenes** [comment]
个人觉得要用chrome这一样的浏览器，不要上google网站 。
chrome能有效识别陷阱 ，上google很容易被识别，而导致 ip全挂 。
我曾用低级浏览器，上google，几分钟ip全挂 。

**Comment by 71e6fd52** [comment]
@lidawei1911 重启一下

**Comment by 71e6fd52** [comment]
@styrenes 我是 **总 IP 数 为 0**
而且不用 chrome 用什么

**Comment by Hanmeim** [comment]
同样的问题

**Comment by 71e6fd52** [comment]
@Hanmeim 那你应该 add reaction +1

**Comment by styrenes** [comment]
用低级浏览器，是会导致总ip变成0的阿，我就是这个意思阿。

**Comment by 71e6fd52** [comment]
@styrenes 墙和 `总 IP` 什么关系

**Comment by 71e6fd52** [comment]
另外 低级浏览器 什么意思

**Comment by styrenes** [comment]
算了，算我什么都没有说。

**Comment by Hanmeim** [comment]
@styrenes 你这是胡扯啦，会被墙识别是因为你没用https吧

**Comment by styrenes** [comment]
是的，我是胡扯。就你厉害 。我只是说碰到的，以后不回你的帖了，算我对不起

**Comment by xxnet** [comment]
​大家文明交流

**Comment by 71e6fd52** [comment]
@xxnet 这怎么看都像是程序问题吧？为什么是交流

---
btw，你和@XX-net 什么关系

**Comment by 71e6fd52** [comment]
@styrenes 用 https 墙是不知道 chrome  的。而且让你推荐浏览器啊，你不会在用 IE 吧

**Comment by LokiSpark** [comment]
北京联通，ipv6，正在撸油管1080p，情绪稳定

**Comment by xxnet** [comment]
​其实Chrome 在访问网站前，会去另外地方验证网站的证书，所以理论上是可以被检测到Chrome。
https 有sni和证书是明文传输，是可以被墙检测到的。
不能排除Chrome的行为被检测到。
Firefox就没有这个问题。

各地的GFW策略不同，所以每个人遇到的情况都可能很特殊。

**Comment by 71e6fd52** [comment]
莫名其妙就行了。。。
