### ISSUE TITLE
X-Tunnel 反馈

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [XX-net/XX-Net#7570]
升 3.7.x 以后一直如此，登陆很稳，但是不能用．3.6.x 版本偶而可以登陆，但只要登陆上就一定可用

另外三张表数值浮动比较大，GAE front 一直 false，Cloudflare front 大多数时候 false 偶而显示几百，Heroku front 在 2000-30000 之间不停跳动

![default](https://user-images.githubusercontent.com/14090545/31946604-e26b8e7c-b904-11e7-835b-24c9fd689b30.png)
![default](https://user-images.githubusercontent.com/14090545/31946615-e65beb4e-b904-11e7-9b0a-de80282604ca.png)
![default](https://user-images.githubusercontent.com/14090545/31946620-e8783a22-b904-11e7-8aa9-0ee384cc0758.png)
![default](https://user-images.githubusercontent.com/14090545/31946625-eabb0d82-b904-11e7-9e0d-60786acb6c8e.png)
![default](https://user-images.githubusercontent.com/14090545/31946631-ec78b6ba-b904-11e7-936e-ee46055a1965.png)

**Comment by xxnet** [comment]
​从状态上看，似乎挺不错，只要有一个能用，比如heroku可用，x-tunnel就能用

**Comment by LakeishaKowalczyk** [comment]
@xxnet
是的，登陆完全没问题，但是打开网页就提示「安全连接失败」，如图一

**Comment by LakeishaKowalczyk** [comment]
@xxnet 
发现换用 Chrome 可以使用，Firefox 不行
3.6.x + Firefox 可以
3.7.x + Firefox 不行
3.7.x + Chrome 可以

**Comment by LakeishaKowalczyk** [comment]
@xxnet 
使用全新配置的火狐也可以，看上去是和某些扩展之类的有冲突，我再找找原因

**Comment by onplus** [comment]
火狐56还是57 ？

**Comment by xxnet** [comment]
​奇怪，你看看 3.7.x + Firefox 时， x-tunnel的日志显示什么
