### ISSUE TITLE
0

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#7573]
0

**Comment by vvvyyy** [comment]
你出多少钱？

**Comment by gogonkt** [comment]
還是那句老話，你行你上

**Comment by zanewayne78** [comment]
光缆过境还要政府批准，不光是钱的问题，楼主你帮忙建个国

**Comment by MeABc** [comment]
out 了，海底专用光缆算个屁，我们不用这种低端货，直接上高端产品----卫星上网。

每人 1GB 的带宽，这是下载速度吗? 不不不，上传也 1GB 的带宽，嗯，你没有看错，我们就是这么有任性。

你还在为数据安全担心吗？这一切就将成为过去，我们使用的是量子加密，银河一号破解也要一万年。

这一切都是幻想的吗？不不不，骚年，我们已在路上。

只有你想不到，没有我们做不到。

**Comment by kuchaguangjie** [comment]
天方夜谭 ... 你的光缆 进的了 中国的 海岸线 么 ???
