### ISSUE TITLE
大神们，安卓版怎么搞，我的魅族手机看下我这种情况

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#7581]

**Comment by LN-VIVI** [comment]
Local Network Status	OK
IP Number	7792
Is Idle	0
IP Quality	9999
Connection Pool(Help)	new:0 h1:0 h2:0
Browser Proxy Setting	Fail
CA status(Download)	Fail
Number of IP-Scanning Threads(Settings)	0
Block Status(Help)	OK
Configuration

**Comment by wywy4pm** [comment]
我的也是，用不了
