### ISSUE TITLE
teredo状态始终是unspecified，求大神指点

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#7584]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Windows\system32>netsh interface ipv6 set teredo enterpriseclient
Ok.

C:\Windows\system32>netsh interface ipv6 show teredo
Teredo Parameters
---------------------------------------------
Type                    : enterpriseclient (Group Policy)
Server Name             : teredo.remlab.net (Group Policy)
Client Refresh Interval : 30 seconds  (Group Policy)
Client Port             : unspecified

C:\Windows\system32>

**Comment by bechromail** [comment]
先看看cmd下ipconfig /all有没有隧道之类的

**Comment by nly4lov** [comment]
@bechromail 没有
