### ISSUE TITLE
Teredo 参数中状态是 probe (primary server)怎么办

### ISSUE THREAD

**Issue by q1374147274** [XX-net/XX-Net#7592]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

电脑是Win7系统，运行过IPV6.BAT了。之前可以连接上，但是状态突然就变了怎么办

**Comment by QGB** [comment]
pteredor
