### ISSUE TITLE
杀个建墙的程序员祭天，没人反对吧？

### ISSUE THREAD

**Issue by chuangzhanji** [XX-net/XX-Net#7598]

**Comment by chuangzhanji** [comment]
程序员何苦为难程序员

**Comment by yeezylife** [comment]
问题是在程序员么

**Comment by onplus** [comment]
你是程序员？没本事写翻墙软件？

**Comment by joycegirl** [comment]
战争，士兵是无罪的。
发动战争的人才是战犯

**Comment by 317053749** [comment]
战争，士兵是无罪的。
发动战争的人才是战犯

**Comment by tq08rsu** [comment]
这次搞得不让人活了。越来越难早死早投胎

**Comment by pldeom** [comment]
上街抗议游行？

**Comment by dahai058** [comment]
3.7.4 ip4刚又恢复，45个ip 延迟172 武汉长城宽带。

**Comment by aabababb** [comment]
做事不能太绝，出来混迟早要还的。。。

**Comment by clawshadow** [comment]
楼主这种没脑子，纯粹是嚷嚷，拉仇恨的
自己想怎么死，想怎么折腾是你的事，别特么在这里害人
发布这种言论，封了ｇｉｔｈｕｂ你高兴了？我这里可是能直连的

**Comment by pfpfpfp** [comment]
issues是拿来讨论问题的，不是给你拿来当贴吧水的

**Comment by hooyubin** [comment]
脑子？

**Comment by mooredam** [comment]
貌似这楼主是在玩暴风影音梗嘛，一群人这么蹦跶？

**Comment by GoodSake** [comment]
不反对，哈哈。

**Comment by xxnet** [comment]
以现代的文明来讲，我们不支持拉仇恨和人身攻击，但希望他们，找个别的工作吧，不要做这样伤天害理的事情。
