### ISSUE TITLE
XX-Net/code目录下之前的旧版本是否可以直接删除

### ISSUE THREAD

**Issue by zhilidali** [XX-net/XX-Net#7601]
![code](https://user-images.githubusercontent.com/13532122/31992215-403a0518-b9ac-11e7-88ec-5fceae6a483c.png)

**Comment by onplus** [comment]
看version.txt写的啥，留下那一个版本就行了

**Comment by zhilidali** [comment]
@onplus 好的，多谢！

**Comment by xxnet** [comment]
​升级时该自动删除一些旧版了，最近升级版本太多，囧

可以考虑保留最近的2个版本

**Comment by pinoren** [comment]
升级为什么不能直接覆盖现有文件呢。。。唉。

**Comment by xxnet** [comment]
如果挪动文件，或者删除文件呢？
这个方案以前试过的，出了问题。

**Comment by SeaHOH** [comment]
>这个方案以前试过的，出了问题。

主要是因为包含 `python27` 文件夹，这个单独更新其它部分就比较好处理。

**Comment by xxnet** [comment]
​python27是给windows平台准备的，如果能实现wscript脚本动态下载 python就好了，安装包会变很小。

**Comment by FrankHB** [comment]
希望能配置用户自行指定python27路径，升级时大部分情况下不需要动。
