### ISSUE TITLE
xxnet php搭建教程

### ISSUE THREAD

**Issue by yuliangyang** [XX-net/XX-Net#761]
http://wallfans.eu.org/xxnet_for_php/
求指导错误，帮忙改进

**Comment by yuliangyang** [comment]
对了，密码修改不知为嘛无效

**Comment by yuliangyang** [comment]
好吧，密码改错地方了
还有个问题，进youtube，进不去，直接把网页下载了

**Comment by guxinshamo** [comment]
我按照你的教程已经成功，就是进YouTube，是下载网页，这个问题如何解决。

**Comment by yuliangyang** [comment]
免费主机问题，
你用的哪款主机
谢谢支持

**Comment by yuliangyang** [comment]
就是我文中的主机吗
0fees

**Comment by guxinshamo** [comment]
0fees，就是你举例的这个。

**Comment by yuliangyang** [comment]
好吧。。。。
暂时无解，等我有时间换个主机试试

**Comment by guxinshamo** [comment]
另外你举例的xx-net的文件夹的结构是否最新，有点点偏差，比如，我需要上传的是这个里面的\XX-Net\php_proxy\1.0.0\server，这个无所谓一般都能找到，另外在Firefox里面需要重新布置一下证书，否则有些打不开。

**Comment by yuliangyang** [comment]
嗯
gae模式跟php模式都有各自的证书
火狐不会自动导入，我一般都是针对google chrome的。上手比较容易

**Comment by yuliangyang** [comment]
你那个是xxnet web界面更新的吧
你那个是旧版本的
重下下载下版本，替换下ip之类的

**Comment by guxinshamo** [comment]
我的是XX-Net Version 	2.0.5，一般我是自动更新的，这个不是最新的吗

**Comment by yuliangyang** [comment]
是最新的，但是xxnet2.0.2更新目录结构，web界面升级的，部分结构改不了

**Comment by yuliangyang** [comment]
你去下个最新版看看就明白了
可以替换xxnet/data/gae_proxy目录下的good_ip.txt

**Comment by yuliangyang** [comment]
该教程方法是没问题了，可是我用的那个主机，唉。。。。。
发到qq中，显示危险网站

**Comment by xxnet** [comment]
可以把教程加到wiki中，感谢分享

在 2015年8月2日 下午9:34，yuliangyang <notifications@github.com>写道：

**Comment by yuliangyang** [comment]
https://github.com/XX-net/XX-Net/wiki/xxnet-php%E6%90%AD%E5%BB%BA%E6%95%99%E7%A8%8B
简单介绍了下

**Comment by xxnet** [comment]
good

2015-08-04 11:30 GMT+08:00 yuliangyang <notifications@github.com>:

**Comment by yuliangyang** [comment]
大大，这样别人也看不到。不知道怎么放到wiki首页上

**Comment by xxnet** [comment]
php的页面里刚才建了一个参考链接。
你也可以直接修改首页wiki，在上面建一个链接

PHP其实可以独立一个章节出来

2015-08-04 14:17 GMT+08:00 yuliangyang <notifications@github.com>:

**Comment by yuliangyang** [comment]
看到了，大大。
php 不重要，就放个参考链接吧。我先把之前的xxnet教程放到首页wiki中

**Comment by yuliangyang** [comment]
好了，大大。都放到wiki首页了。这个issue我就关闭了

**Comment by cdmask** [comment]
没有说清楚，到底修改密码是修改哪一个文件？xx-net页面怎么设置，只需要点启用php proxy? 要不要配置server url，如果要的话要怎么填写？

**Comment by yuliangyang** [comment]
改密码的文件为index.php
服务端只需要改密码
客户端填网址就行
http://example.com/   注意格式

**Comment by cdmask** [comment]
我什么都没有修改，直接上传了，然后php_proxy/local 里面的proxy.ini 文件修改了
enable = 1
password = 123456
crlf = 0
validate = 0
listen = 127.0.0.1:8088
fetchserver = http://xxxxxxxx.0fees.us/
然后在 data/php_proxy的proxy.ini
enable = 1
password = 
fetchserver = 
然后 Switchysharp 选择的 PAAS 连接facebook.com提示无法连接到代理服务器。

**Comment by yuliangyang** [comment]
你的web界面php代理开了吗

**Comment by cdmask** [comment]
启用 php代理开了。然后配置php代理里面没有填内容。

**Comment by yuliangyang** [comment]
最好别填，有bug的
你如果连不上，可以这样
删除xxnet/data/php_proxy目录下的config.ini，或者修改config.ini里的enable = 0改成1

**Comment by cdmask** [comment]
嗯，删除了，然后重启了一下，可以了。谢谢啊！

**Comment by yuliangyang** [comment]
那是个bug。。。。。
web界面配置后，xxnet/data/php_proxy目录下的config.ini，中的enable = 0，，，修改为1就行了。。
简单办法就是直接删除
但是删除以后，下次xxnet升级，又得重新配置。。。。
欢迎访问http://wallfans.eu.org

**Comment by xxnet** [comment]
看到bug了，下次修复

在 2015年8月8日 下午3:37，yuliangyang <notifications@github.com>写道：
