### ISSUE TITLE
彻底没戏了

### ISSUE THREAD

**Issue by netfun2000** [XX-net/XX-Net#7612]
开启IPV6用了不到一星期，到前天IPV6也挂了。威武兲朝。

**Comment by netfun2000** [comment]
我只是用来访问GOOGLE。连这个也不行。

**Comment by xxnet** [comment]
​试试x-tunnel

**Comment by Blessedlsd** [comment]
XX大不是已经结束了吗，怎么还不恢复正常，碍事啊

**Comment by xxnet** [comment]
部分地区其实已经放开了，各地政策不同吧

**Comment by netfun2000** [comment]
t 25 07:51:11.920 - [DEBUG] report_connect_fail continue_fail_count:49
Oct 25 07:51:11.921 - [DEBUG] report_connect_fail:2404:6800:400f:2::a
Oct 25 07:51:11.922 - [DEBUG] report_connect_fail continue_fail_count:50
Oct 25 07:51:11.923 - [DEBUG] report_connect_fail:2a00:1450:401f:33::7
Oct 25 07:51:11.924 - [DEBUG] report_connect_fail continue_fail_count:51
Oct 25 07:51:11.926 - [DEBUG] report_connect_fail:2a00:1450:401f:2e::11
Oct 25 07:51:11.957 - [DEBUG] connect 2a00:1450:400d:f::7 fail:[Errno 97] Address family not supported by protocol cost:19 h:0
Oct 25 07:51:13.525 - [DEBUG] s

**Comment by FrankHB** [comment]
上海电信一直没问题，科技网前两天开始不行……算“地区”问题么。
连stackoverflow.com和stackexchange.com都上不去……

**Comment by FrankHB** [comment]
最奇葩的是一坨超时，msdn.microsoft.com给我来个“连接被重置”？？？？？
这是什么操作？？？？？

**Comment by Lancenas** [comment]
打开ipv6后就一直连接正常，应该是配置有问题吧

**Comment by netfun2000** [comment]
还正常使用了大概1个星期的样子，突然就挂了。
===============================
XX-Net Status:

sys-platform: armv6l, Linux-4.9.35+-armv6l-with-debian-9.1
os-system: Linux
os-version: #1014 Fri Jun 30 14:34:49 BST 2017
os-release: 4.9.35+
os-detail: Dist:debian; Version:9.1; ID:
architecture: 32bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
xxnet-version: 3.7.4
python-version: 2.7.13
openssl-version: 16.2.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:3842
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 1368
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​大家先用x-tunnel吧

GAE以后再想办法

**Comment by Ianwoo77** [comment]
魔高一尺 道高一丈……老公家认真起来，谁能撸动？

**Comment by xxnet** [comment]
​GAE 不行了，还有其他方案，不必担心

**Comment by FrankHB** [comment]
x-tunnel也不行。

诊断消息：
```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
xxnet-version: 3.7.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12346 good:2583
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 1759
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

日志：
```
Oct 26 11:13:16.326 - [WARNING] task trace:0:start_request,0:get_task(0),5261:get_worker:50.19.110.223,0:h1_req,0:h1_req_sended,247:response_begin,0:h1_get_head,0:h1_finish[SP:1443],0:get_response,:0

Oct 26 11:13:16.326 - [INFO] Conn session:qanrwgtq conn:5 Peer Close:connect fail

Oct 26 11:13:16.326 - [DEBUG] Conn session:qanrwgtq conn:5 stop:peer close

Oct 26 11:13:16.811 - [DEBUG] remove conn_id:5

Oct 26 11:13:16.811 - [INFO] socks5 ('127.0.0.1', 59833) connect to 127.0.0.1:8085 conn_id:6

Oct 26 11:13:20.101 - [WARNING] roundtrip time:15028 transfer_no:12 send_sn:12 send:20 status:602 retry:1

Oct 26 11:13:21.607 - [DEBUG] roundtrip time:5281 cost:5006 transfer_no:15 send_sn:15 send:20 recv_sn:0 rcv:11 status:200

Oct 26 11:13:22.088 - [DEBUG] roundtrip time:5276 cost:9 transfer_no:16 send_sn:16 send:28 recv_sn:6 rcv:37 status:200

Oct 26 11:13:22.088 - [INFO] Conn session:qanrwgtq conn:6 Peer Close:connect fail

Oct 26 11:13:22.088 - [DEBUG] Conn session:qanrwgtq conn:6 stop:peer close 
```

Heroku front Log
```
Oct 26 11:10:10.277 - [DEBUG] 54.225.128.217 fail:error(' certficate is none',)
Oct 26 11:10:10.277 - [DEBUG] report_connect_fail:54.225.128.217
Oct 26 11:10:10.292 - [DEBUG] 23.23.92.140 fail:error(' certficate is none',)
Oct 26 11:10:10.577 - [DEBUG] 54.225.121.197 fail:error(' certficate is none',)
Oct 26 11:10:11.279 - [WARNING] no enough ip 
```

**Comment by xxnet** [comment]
升级 3.7.5
把x-tunnel 的Status 页面贴出来

**Comment by FrankHB** [comment]
和 3.7.4没啥差别，score也是一坨False，就Heroku有几百个success其它都是0，但总之不管怎么设置都上不了。

不过现在GAE能用了，之前有问题的一些站点直连都行，不用代理。

**Comment by xxnet** [comment]
​升级 3.7.6看看，刚发布

**Comment by FrankHB** [comment]
正常升级，Status看起来也正常了，不过x-tunnel设置成代理还是都无法浏览。


Property | Value
-- | --
Score | 289
Success num | 2
Fail num | 0
Worker num | 48

日志


Oct 26 20:36:08.929 - [INFO] X-Tunnel window:33554432

Oct 26 20:36:08.929 - [INFO] Socks5 server listen:127.0.0.1:1080.

Oct 26 20:36:21.985 - [DEBUG] x_tunnel force update info

Oct 26 20:36:22.386 - [INFO] api:/login success t:401

Oct 26 20:36:22.386 - [INFO] update xt_server v4.xx-net.net:443

Oct 26 20:36:22.386 - [INFO] request_balance host:v4.xx-net.net port:443 balance:0.000000 quota:1091026462.000000

Oct 26 20:36:22.671 - [INFO] login_session vsahlxel time:285 msg:Success 

Cloudflare front Log

Oct 26 20:36:40.740 - [DEBUG] http2 141.101.120.38 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Oct 26 20:36:40.740 - [DEBUG] 141.101.120.38 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Oct 26 20:36:40.740 - [DEBUG] 141.101.120.38 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:15

Oct 26 20:36:40.740 - [DEBUG] 141.101.120.38 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Oct 26 20:36:51.872 - [DEBUG] 198.41.221.15 _consume_single_frame:SysCallError(10054, 'WSAECONNRESET'), inactive time:21

Oct 26 20:36:51.872 - [DEBUG] 198.41.221.15 worker close:disconnect:SysCallError(10054, 'WSAECONNRESET')

Oct 26 20:36:51.918 - [DEBUG] ip:141.101.123.183 real fail

Oct 26 20:36:56.927 - [DEBUG] ip:141.101.122.88 real fail

Oct 26 20:37:01.937 - [DEBUG] ip:172.64.104.66 real fail

Oct 26 20:37:47.602 - [DEBUG] 162.159.211.194 _consume_single_frame:SysCallError(10054, 'WSAECONNRESET'), inactive time:80

Oct 26 20:37:47.602 - [DEBUG] 162.159.211.194 worker close:disconnect:SysCallError(10054, 'WSAECONNRESET')

Heroku front Log

Oct 26 20:40:12.467 - [DEBUG] 50.16.218.193 fail:error(' certficate is none',)

Oct 26 20:40:12.467 - [DEBUG] report_connect_fail:50.16.218.193

Oct 26 20:40:12.668 - [DEBUG] 50.19.253.20 fail:error(' certficate is none',)

Oct 26 20:40:12.668 - [DEBUG] report_connect_fail:50.19.253.20

Oct 26 20:40:13.655 - [DEBUG] 23.23.120.204 fail:error(' certficate is none',)

Oct 26 20:40:13.655 - [DEBUG] report_connect_fail:23.23.120.204

**Comment by xxnet** [comment]
​浏览器代理端口改了没有？ 1080

**Comment by xxnet** [comment]
把x-tunnel 的状态页都贴出来

**Comment by FrankHB** [comment]
改了，之前没改回来我还没法回复这个issue。X-tunnel状态页是指status的话，就是上面贴的。

GAE的：

属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 3659
空闲 | 1
IP延迟 | 430
连接池(帮助) | 新:6 h1:0 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK

因为还是1080所以代理设置是Fail。

另外，流量看来是用掉了几M。

**Comment by FrankHB** [comment]
另外x-tunnel status的内容复制粘贴到这里始终只有第一个表格，所以之前先复制到记事本掉格式以后再贴。

**Comment by xxnet** [comment]
​x-tunnel 状态页应该有3个表，你只贴出来一个表，而且不知道是哪个表。

你全部贴出来吧，或者截图贴上来。

日志贴多一点，太少看不到有用的信息

**Comment by FrankHB** [comment]
我之前注意到只贴了1个表，后来编辑了。我现在再手动加格式区分一下标题。

现在更换了网络环境（之前IPv6也没问题），重启了XX-net，看起来GAE和x-tunnel都能正常连接了，但是x-tunnel个别网站有其它问题（GAE正常），主要是：

Secure Connection Failed

The connection to www.google.com.hk was interrupted while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

以及：

Your connection is not secure

The owner of encrypted.google.com has configured their website improperly. To protect your information from being stolen, Nightly has not connected to this website.

encrypted.google.com uses an invalid security certificate.

The certificate is only valid for the following names:
  *.facebook.com, *.facebook.net, *.fb.com, *.fbcdn.net, *.fbsbx.com, *.m.facebook.com, *.messenger.com, *.xx.fbcdn.net, *.xy.fbcdn.net, *.xz.fbcdn.net, facebook.com, fb.com, messenger.com  

Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by xxnet** [comment]
​这个现象就奇怪了，encrypted.google.com 指向了facebook的ip?

**Comment by netfun2000** [comment]
今天将以前SD卡备份还原回来，突然 一切正常 了。非常感谢XX-NET。
