### ISSUE TITLE
xx-net的ipv6功能不能开机自动启动

### ISSUE THREAD

**Issue by ljhui** [XX-net/XX-Net#7618]
#我设置xxnet开机启动，并开启了ipv6,但是每次开机时总是显示请开启扫描器，我试过重启gae，不起作用，ipv6没用，解决方法也简单只需关闭ipv6功能再重新开启保存一下就恢复正常，好像xx-net的ipv6功能不能开机自动启动一样，非得开机后关闭ipv6再重新开启才能用，这问题怎么解决
XX-Net Status:

sys-platform: x86_64, Linux-4.13.5-200.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
os-system: Linux
os-version: #1 SMP Thu Oct 5 16:53:13 UTC 2017
os-release: 4.13.5-200.fc26.x86_64
os-detail: Dist:Fedora; Version:26; ID:Twenty Six
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
xxnet-version: 3.7.4
python-version: 2.7.13
openssl-version: 16.2.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12345 good:35
network-status: OK
connected-link: new:2 used:0
worker: h1:25 h2:0
scan-ip-thread-num: 0
ip-quality: 359
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​你用什么版本？

**Comment by ljhui** [comment]
最新的稳定版3.7.4

**Comment by onplus** [comment]
估计是因为你的teredo隧道不稳定
