### ISSUE TITLE
雅虎邮箱无法使用怪象，如何解？

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#7655]
登录雅虎邮箱的登录界面后，一步一步按照正常程序却始终无法登录到雅虎邮箱收件箱界面，很奇怪。
目前正在使用XX-net的GAE模式。不知道是怎么回事，请求帮助。
![-1](https://user-images.githubusercontent.com/19446969/32061692-ea0942cc-baa4-11e7-9251-605384667e07.jpg)

**Comment by badabiba** [comment]
直接连接 不要翻墙的

**Comment by 80068** [comment]
@xxnet X大，新版本3.7.6 无法登陆雅虎邮箱，这个怎么办？

**Comment by xxnet** [comment]
​如果是GAE的限制，那就用X-tunnel吧。

如果是版本问题，你先对比测试老版本，看看是不是新版带来的问题。
