### ISSUE TITLE
不知道为什么dropbox连不上

### ISSUE THREAD

**Issue by ted423** [XX-net/XX-Net#766]
不知道为什么dropbox连不上
就是网页版的dropbox都能上，但是客户端就一直连不上
貌似都是报的ssl的问题，说是nuknow ca

**Comment by xxnet** [comment]
估计跟证书有关系

2015-08-03 21:02 GMT+08:00 ted423 <notifications@github.com>:

**Comment by kazexd** [comment]
@xxnet 
Sep 17 00:37:42 - [INFO] GAE t:713 s:62703 200 https://github.com/XX-net/XX-Net/suggestions/issue/98738242
Sep 17 00:38:14 - [INFO] GAE CONNECT client.dropbox.com:443 
Sep 17 00:38:14 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:client.dropbox.com
Sep 17 00:38:17 - [INFO] GAE CONNECT d.dropbox.com:443 
Sep 17 00:38:17 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:590), create full domain cert for host:d.dropbox.com

我遇到的是這樣
應該也是跟證書有關，有解決的方法嗎？

**Comment by ted423** [comment]
没有继续使用
