### ISSUE TITLE
ipv6方式上推特搜索都是搜索不到内容？

### ISSUE THREAD

**Issue by tamada007** [XX-net/XX-Net#7667]
如搜索xxnet都显示“没有关于 xxnet 的结果”
同样用x-tunnel可以搜得到。

**Comment by momo3030** [comment]
我这边可以

**Comment by spearheartee** [comment]
我也有同样的问题，以前用IPv4的时候都没有出现过类似问题

**Comment by IM-111** [comment]
应该是tweets被封了之类，因为搜索时网址会显示tweets&vertical之类的，hashtag也用不了。问题出现很久了，不过这段时间都在烦连接不上，所以没怎么反映这问题
