### ISSUE TITLE
Mac中使用Use dark menu时图标不显示

### ISSUE THREAD

**Issue by lusfold** [XX-net/XX-Net#767]
### Mac中使用Use dark menu时图标不显示

* 选中状态  

![image](https://cloud.githubusercontent.com/assets/13173319/9052392/90cd506e-3a99-11e5-94a7-9c6790b23576.png)

＊ 未选中状态（不显示）  

![image](https://cloud.githubusercontent.com/assets/13173319/9052399/98f56b1e-3a99-11e5-8823-b937daf55ab6.png)

**Comment by xxnet** [comment]
是不是图标的颜色有问题？
  这个是网友更新的黑白图标

2015-08-04 11:13 GMT+08:00 lusfold <notifications@github.com>:

**Comment by lusfold** [comment]
嗯，估计是图标有问题，不选中`Use dark menu`时没有问题

**Comment by lusfold** [comment]
看了下图标，并非黑白，而是黑色和透明。。。我来替换吧
