### ISSUE TITLE
2017年10月26日 郭文贵直播 十九大后爆料计划 曹長青：習近平用別人給寫的論文，靠同窗同室工農兵學員老友拿到博士帽，這次以烏紗帽回報。

### ISSUE THREAD

**Issue by fioolbx** [XX-net/XX-Net#7676]
向大家推荐台湾民视新闻台的政论节目《政经看民视》 每晚19:55直播
台湾民视新闻youtube直播地址：https://gaming.youtube.com/watch?v=XxJKnDLYZz4                         
《政经看民视》youtube 地址：https://www.youtube.com/channel/UCYIADVzNi0a3tebP67uKqpA/videos
《政经看民视》twitter： https://twitter.com/dennispamandal
曹長青 twitter： https://twitter.com/caochangqing
賴清德：6個決心不變，回应習近平提6個任何。賴清德說，行政院一貫立場，是捍衛台灣主權決心不變；維護國人自由、民主、人權生活決心不變；發展經濟、壯大台灣的決心不變；透過交流、求同存異，深化兩岸和平發展決心不變；維護國人對於未來權利的選擇權決心不變；也會捍衛區域的和平安全，這個決心也不會改變。

**Comment by wanghz** [comment]
偏离主题，建议删除主贴

**Comment by adminhex** [comment]
偏离主题，建议删除主贴

**Comment by largewhale** [comment]
偏离主题，建议删除主贴

**Comment by theratlesnake** [comment]
还是别在这里讨论政治好，毕竟X大也是冒着很大风险在维护软件，另外，这里五毛众多，容易被五毛抓到把柄举报，到时要删xx-net项目就麻烦了。

**Comment by akari263** [comment]
偏离主题，建议删除主贴

**Comment by sakuratyan** [comment]
偏离主题，建议删除主贴

**Comment by ckmark** [comment]
赶紧删了，别因为这个把xx-net整没了

**Comment by hawkxian** [comment]
删除了吧，别在这讨论政治

**Comment by xYz1988** [comment]
就讨厌你这种SB在没被墙的地方讨论这东西，非要弄的那天连github一起给墙了你就爽了是吧？

**Comment by ken520** [comment]
逗比 来这里 讨论 政治  你是头壳 坏掉么

**Comment by emacsenli** [comment]
你们，，，，GFW就是要把xxnet打成存与不存一个样

2017年10月27日 下午3:13，"ken520" <notifications@github.com>写道：

**Comment by wqwin** [comment]
stupid asshole

**Comment by Langgeligelang** [comment]
qnmd，以为我们翻墙是为了看sb台蛙？

**Comment by tamada007** [comment]
同意楼上，到时这里墙了，哭都来不及了
