### ISSUE TITLE
新电脑Teredo驱动好像有问题，设备管理器里边有个小叹号，自动修复不了。

### ISSUE THREAD

**Issue by Weijee** [XX-net/XX-Net#7677]
给设备无法启动 （10）

**Comment by ylwszb** [comment]
把Teredo适配器删了，重启电脑，让电脑自动识别驱动，自动安装。
如不能自动识别安装，就手动安装。但要注意安装后不能有重复的Teredo。
手动安装Teredo适配器：https://github.com/XX-net/XX-Net/issues/7241#issuecomment-338201699

**Comment by jackflyfly** [comment]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters修改DisabledComponents十六进制值为0，然后重启电脑，亲测有效

**Comment by Weijee** [comment]
666

**Comment by akyou** [comment]
https://appuals.com/category/guides/自行翻译
