### ISSUE TITLE
喜大普奔：我的xx不知何故忽然恢复了FQ能力

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#7678]
昨天下午重装了系统，今天早晨搞好了google chrome,当时也是不能翻的，随手启用了ipv6
刚刚重启了一下系统，启动xx发现界面不一样：让我部署自己的appid。。。后来你懂的![11](https://user-images.githubusercontent.com/11325411/32089890-32420a90-bb1f-11e7-9834-b9f8fe3c2f21.gif)

Property | Value
-- | --
Local Network Status | OK
IP Number | 11280
Is Idle | 0
IP Quality | 300
Connection Pool(Help) | new:1 h1:81 h2:0
Browser Proxy Setting | OK
CA status(Download) | OK
Number of IP-Scanning Threads(Settings) | 0
Block Status(Help) | OK

**Comment by HDFrank** [comment]
这会儿是不是又不行了？

**Comment by nly4lov** [comment]
@HDFrank 没有啊，还正常使用中

**Comment by Facesring** [comment]
看看现在是不是还是安然无恙？貌似彻底嗝屁了..........

**Comment by nly4lov** [comment]
@Facesring 嗯，今早上班发现“Connection not established yet.”

**Comment by nly4lov** [comment]
咦，忽然又好了，不知抽什么疯。
