### ISSUE TITLE
开启ipv6以后的错误日志

### ISSUE THREAD

**Issue by OnionSalt** [XX-net/XX-Net#7698]
用3.7.4开启ipv6使用了一天左右没问题，然后就出现如下错误
Oct 27 20:22:42.839 - [WARNING] gae_exception:"600:unpack protocol:ValueError('need more than 2 values to unpack',)" “这里跟的是访问的网站地址”
然后升级到3.7.7还是这个问题，一样的日志，全是unpack protocol错误

就在出错之前还用了大概1小时左右没问题(3.7.4)，然后就开始突然哪里都上不去了
帮忙解答下，多谢各位

**Comment by xxnet** [comment]
​发多点出错日志出来，前后2百行左右，才好分析

**Comment by OnionSalt** [comment]
知道什么问题了，前一段时间一直用gop，gop的服务端跟xxnet不兼容，重新部署以后已经没问题了
