### ISSUE TITLE
（mac）导入证书并修改成始终信任后依旧报错

### ISSUE THREAD

**Issue by RushPu** [XX-net/XX-Net#77]
我先是在登入和系统中导入了自动生成的ca证书，然后修改成全部始终信任
然后打开，日志如下：

/Users/rushpu/Downloads/XX-Net-1.3.6/start.command ; exit;
rushpudeMacBook-Air:~ rushpu$ /Users/rushpu/Downloads/XX-Net-1.3.6/start.command ; exit;
Mar 23 20:19:59 - [INFO] launcher version: 1.0.8
Mar 23 20:19:59 - [INFO] use goagent version:3.1.40
Mar 23 20:19:59 - [INFO] goagent 3.1.40 started /Users/rushpu/Downloads/XX-Net-1.3.6/goagent/3.1.40/start.py
Mar 23 20:19:59 - [INFO] load google ip_list num:2874, gws num:2874
Mar 23 20:19:59 - [DEBUG] sort ip time:6
Mar 23 20:19:59 - [INFO] ------------------------------------------------------
GoAgent Version    : 3.1.40 (python/2.7.6 )
Listen Address     : 127.0.0.1:8087
Control Address    : 127.0.0.1:8084
GAE APPID          : xxx
Pac Server         : http://127.0.0.1:8086/proxy.pac
Pac File           : file:///Users/rushpu/Downloads/XX-Net-1.3.6/goagent/3.1.40/local/proxy.pac
------------------------------------------------------

SecCertificateAddToKeychain: write permissions error
Mar 23 20:20:00 - [DEBUG] launcher web_control 127.0.0.1:61140 "GET / 
Mar 23 20:20:09 - [INFO] get uuid:89ae68d4-59f6-4191-8c58-84bf4f8f3bb2
Mar 23 20:20:09 - [INFO] FWD CONNECT xxnet-update.appspot.com:443 
Mar 23 20:20:09 - [DEBUG] sort ip time:8
Mar 23 20:20:09 - [DEBUG] get ip:64.233.189.167 t:98
Mar 23 20:20:09 - [DEBUG] tcp conn 64.233.189.167 time:71
Mar 23 20:20:10 - [DEBUG] forward remote disconnected.
Mar 23 20:20:10 - [DEBUG] FWD CONNECT xxnet-update.appspot.com:443 with closed

然后就不动了

**Comment by xxnet** [comment]
报什么错误？

日志里没有访问网站的日志，是否已经设置了使用127.0.0.1 8087作为代理？


2015-03-23 8:27 GMT-04:00 rushpu <notifications@github.com>:

**Comment by xxnet** [comment]
新版已经实现自动导入证书
