### ISSUE TITLE
xx-net 关掉， IE竟然无法上网了（已解决）

### ISSUE THREAD

**Issue by farshidvahid** [XX-net/XX-Net#771]
xx-net 已经选定“取消全局代理”，今天在上网银时（国内的网银只能IE上），发现关掉xx-net，IE就无法连接网络；而开着xx-net，由于使用的代理IP，登录网银时会自动登出。

请教这个问题怎么解决？感谢！

更新到2.0.7后问题解决。估计2.0.5版本的“取消全局代理”是无效的。

**Comment by xxnet** [comment]
打开IE，进入代理设置，确认代理已经取消

2.0.5取消代理，IE需要重启才能不经过代理。
2.0.7 已经修复这个bug

在 2015年8月5日 下午7:39，farshidvahid <notifications@github.com>写道：

**Comment by farshidvahid** [comment]
非常感谢！向您致敬！
