### ISSUE TITLE
发现gae和tunnel都不能访问日本yahoo的图片搜索页面，这是为什么

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#7718]
有没有好的解决办法，虽说日本yahoo可以直接访问，但是图片搜索不可以访问，即使gae和tunnel都不行，但是之前是可以的。大概是一个月之前可以

**Comment by xxnet** [comment]
​具体什么地址？

**Comment by yuyistar** [comment]
@xxnet 刚才给你复制地址的时候发现解决方法。。。以前直接在首页切换图片搜索标签不行，结果刚才给你复制地址的时候，直接复制到浏览器地址栏，再打开就可以用了。
