### ISSUE TITLE
救命...

### ISSUE THREAD

**Issue by zengsher** [XX-net/XX-Net#773]
Aug 06 00:19:57 - [DEBUG] create_ssl 83.100.221.238 fail:Error connecting to HTTP proxy 127.0.0.1:808: [Errno 10061] cost:1029 h:0
Aug 06 00:19:57 - [DEBUG] report_connect_fail network fail
Aug 06 00:19:57 - [DEBUG]LOG_EXCEPT: get ip:149.3.177.37 t:1389, Except:[Errno 9] Bad file descriptor
Aug 06 00:19:57 - [DEBUG] create_ssl 195.249.20.211 fail:Error connecting to HTTP proxy 127.0.0.1:808: [Errno 10061] cost:1013 h:0
Aug 06 00:19:57 - [DEBUG] report_connect_fail network fail
Aug 06 00:19:58 - [DEBUG] create_ssl 62.1.38.170 fail:Error connecting to HTTP proxy 127.0.0.1:808: [Errno 10061] cost:1006 h:0
Aug 06 00:19:58 - [DEBUG] report_connect_fail network fail

系统版本

Property	Value
XX-Net Version	2.0.5
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.2.9200
OS release	8
OS detail	Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	103
100th IP handshake(ms)	1742
connected link(帮助)	0,0
scaning ip thread num	50
block stat(帮助)	OK

**Comment by zengsher** [comment]
到处都是显示错误，醉了...

**Comment by zengsher** [comment]
Error connecting to HTTP proxy 127.0.0.1:808: [Errno 10061] cost:1029 h:0

这个是局域网代理设置错了，我明白了

**Comment by xxnet** [comment]
请Close Issue

2015-08-06 0:27 GMT+08:00 zengsher <notifications@github.com>:
