### ISSUE TITLE
123

### ISSUE THREAD

**Issue by Thebiggestlight** [XX-net/XX-Net#7730]

**Comment by onplus** [comment]
看wiki

**Comment by luogx10517** [comment]
wiki跟没说一样。

**Comment by xxnet** [comment]
​
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6

目前还无法做到傻瓜化，大家需要花点时间研究下。
大部分人还是可以连上Ipv6的。

**Comment by zoggee** [comment]
可以的,开启参考 #6918,我的开启就可以用了
