### ISSUE TITLE
第一次设置怎么都不成功

### ISSUE THREAD

**Issue by d364913862** [XX-net/XX-Net#774]
恳请大神帮忙看下谢谢，我这里图片为什么不能上传，只好复制了。
系统版本

Property	Value
XX-Net Version	2.0.7
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36

日志：
Aug 06 17:42:07 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=myproject
Aug 06 17:42:07 - [DEBUG] get ip:128.0.90.114 t:1496
Aug 06 17:42:07 - [DEBUG] get ip:128.0.86.217 t:1860
Aug 06 17:42:07 - [DEBUG] create_ssl update ip:128.0.90.96 time:1152
Aug 06 17:42:07 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Aug 06 17:42:07 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 17:42:07 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=myproject
Aug 06 17:42:08 - [DEBUG] create_ssl update ip:103.7.200.79 time:509
Aug 06 17:42:08 - [DEBUG] create_ssl update ip:128.0.90.88 time:1096
Aug 06 17:42:08 - [WARNING] no gws ip
Aug 06 17:42:08 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Aug 06 17:42:08 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 17:42:08 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=myproject
Aug 06 17:42:08 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Aug 06 17:42:08 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 17:42:08 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=myproject

**Comment by cdmask** [comment]
没有appid 部署app

**Comment by d364913862** [comment]
谢谢楼上。我重新配置了下appid。显示如下：
ug 06 19:02:23 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 19:02:23 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=perfect-purpose-102908
Aug 06 19:02:23 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Aug 06 19:02:23 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 19:02:23 - [WARNING]LOG_EXCEPT: gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=perfect-purpose-102908, Except:[Errno 9] Bad file descriptor
Aug 06 19:02:23 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Aug 06 19:02:23 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 19:02:23 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=perfect-purpose-102908
Aug 06 19:02:23 - [ERROR] No usable appid left, add new appid to continue use GAEProxy
Aug 06 19:02:23 - [DEBUG] GAE_Exception 1 'no appid can use'
Aug 06 19:02:23 - [WARNING] gae_exception:GAE_Exception() https://appengine.google.com/api/appversion/rollback?version=1&app_id=perfect-purpose-102908
Aug 06 19:02:24 - [WARNING] no gws ip
Aug 06 19:02:25 - [WARNING] no gws ip

**Comment by d364913862** [comment]
好像可以上YouTube了是否代表成功了。关闭问题了。再次感谢二楼的大神帮助。！

**Comment by d364913862** [comment]
啊，折腾半天，终于把APPID搞好了，现在日志又提示这个：
in "E:\Soft\XX-Net-2.0.7\gae_proxy\server\gae\app.yaml", line 1, column 14
Aug 06 20:18:49 - Error parsing yaml file:
Unable to assign value 'Myproject' to attribute 'application':
Value 'Myproject' for application does not match expression '^(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{1,100}$'
in "E:\Soft\XX-Net-2.0.7\gae_proxy\server\gae\app.yaml", line 1, column 14
Aug 06 20:18:49 - Error parsing yaml file:
Unable to assign value 'Myproject' to attribute 'application':
Value 'Myproject' for application does not match expression '^(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{1,100}$'
in "E:\Soft\XX-Net-2.0.7\gae_proxy\server\gae\app.yaml", line 1, column 14
Aug 06 20:18:49 - upload fail: [Errno 9] Bad file descriptor

Aug 06 20:18:49 - Retry 56 time...

**Comment by xxnet** [comment]
你的appid 应该是小写的字母，你似乎填了一个 Myproject ？

你先看看注册的appid是什么

2015-08-06 20:20 GMT+08:00 d364913862 <notifications@github.com>:
