### ISSUE TITLE
支持封锁网络，阻碍新闻自由的，都是盗国贼！打倒共产党里的盗国贼！建立民主宪政中国！！

### ISSUE THREAD

**Issue by fioolbx** [XX-net/XX-Net#7767]
向大家推荐台湾民视新闻台的政论节目《政经看民视》 每晚19:55直播
台湾民视新闻youtube直播地址：https://gaming.youtube.com/watch?v=XxJKnDLYZz4
《政经看民视》youtube 地址：https://www.youtube.com/channel/UCYIADVzNi0a3tebP67uKqpA/videos
《政经看民视》twitter： https://twitter.com/dennispamandal
曹長青 twitter： https://twitter.com/caochangqing
google：https://www.google.com
youtube：https://www.youtube.com
Facebook：https://www.facebook.com
Twitter：https://twitter.com
台湾自由時報：http://www.ltn.com.tw
BBC：http://www.bbc.com/zhongwen/simp
美国之音：https://www.voachinese.com
德国之声：http://www.dw.com/zh
法新社：http://cn.rfi.fr/
韩国之眼 朝鲜日报网：http://cnnews.chosun.com
韩国中央日报：http://chinese.joins.com/gb
纽约时报：https://cn.nytimes.com
賴清德：6個決心不變，回应習近平提6個任何。賴清德說，行政院一貫立場，是捍衛台灣主權決心不變；維護國人自由、民主、人權生活決心不變；發展經濟、壯大台灣的決心不變；透過交流、求同存異，深化兩岸和平發展決心不變；維護國人對於未來權利的選擇權決心不變；也會捍衛區域的和平安全，這個決心也不會改變。

**Comment by joycegirl** [comment]
别在这发啦

**Comment by wlm2012** [comment]
能到这的，还需要你提供这几个网站。。。。
