### ISSUE TITLE
支持封锁网络，阻碍新闻自由的，都是盗国贼！打倒共产党里的盗国贼！结束一党独裁！建立民主宪政中国！

### ISSUE THREAD

**Issue by fioolbx** [XX-net/XX-Net#7769]
向大家推荐台湾民视新闻台的政论节目《政经看民视》 每晚19:55直播
台湾民视新闻youtube直播地址：https://gaming.youtube.com/watch?v=XxJKnDLYZz4
《政经看民视》youtube 地址：https://www.youtube.com/channel/UCYIADVzNi0a3tebP67uKqpA/videos
《政经看民视》twitter： https://twitter.com/dennispamandal
曹長青 twitter： https://twitter.com/caochangqing
google：https://www.google.com
youtube：https://www.youtube.com
Facebook：https://www.facebook.com
Twitter：https://twitter.com
台湾自由時報：http://www.ltn.com.tw
BBC：http://www.bbc.com/zhongwen/simp
美国之音：https://www.voachinese.com
德国之声：http://www.dw.com/zh
法新社：http://cn.rfi.fr/
韩国之眼 朝鲜日报网：http://cnnews.chosun.com
韩国中央日报：http://chinese.joins.com/gb
纽约时报：https://cn.nytimes.com
台湾中央社：http://www.cna.com.tw
賴清德：6個決心不變，回应習近平提6個任何。賴清德說，行政院一貫立場，是捍衛台灣主權決心不變；維護國人自由、民主、人權生活決心不變；發展經濟、壯大台灣的決心不變；透過交流、求同存異，深化兩岸和平發展決心不變；維護國人對於未來權利的選擇權決心不變；也會捍衛區域的和平安全，這個決心也不會改變。
公平正义、民主宪政、三权分立、多党制、军队国家化、司法独立、普选、新闻自由、公民社会、公民权利、普世价值！
零八宪章全文：https://www.voachinese.com/a/charter-2008-109947549/773226.html

**Comment by SeaHOH** [comment]
发一次就够了，不要反复刷。

**Comment by onplus** [comment]
@SeaHOH 
何止两次 
https://github.com/geekcompany/ResumeSample/issues/17
https://github.com/FreeCodeCampChina/freecodecamp.cn/issues/421

**Comment by slyypp** [comment]
建议删帖。

**Comment by yeezylife** [comment]
别把这里也搞没了，有能耐您去局子面前喊去。

**Comment by RomanSmile** [comment]
我们是好好生活得小民，谁当局我们也是小民，我们不关心政治，不要把灾难引来这里，没有任何个人团体能和政府作对的，请走开/建议删帖！

**Comment by zentst** [comment]
滚蛋吧，看看灯塔和台湾岛，我才不想中国会变成这种狗屎样。你们这些台独的就滚出中国的地方，滚出台湾

**Comment by mooredam** [comment]
xswl，楼上那位，不想中国变啥样？每份报纸头版只放一张大头贴？粉得出了墙这红可就糊不住了嘛

不过话说回来了，issues一般是用来讨论项目技术问题的，这些花边还是去发推吧

**Comment by hallrady** [comment]
涉及政治煽动内容，建议删帖

**Comment by shindaren** [comment]
我就说一个事实，从初中到大学，年年我都拒绝加入共青团。
你们猜我反不反共？

**Comment by kevinlau2015** [comment]
新闻自由有老百姓安家乐业重要？

**Comment by theratlesnake** [comment]
等人均GDP超过了台湾，再来骂别人呗。呵呵

**Comment by TXIuTnVsbA** [comment]
66666666666666666666666
在一个代码托管平台涉及政治,你也是够6的,能上github的人,有空去看你的政治理论?

**Comment by Ikeblablabla** [comment]
节目只推荐绿营的，不厚道。
曹长青那水平的就不要放了，不知道的，大家一查便知。
不要在这疯子一样嗷嗷叫了，也老大不小了，太难看了。再说，地方也不对。

**Comment by bitternolis** [comment]
政治煽动，美国之音这种相声节目倒是挺好看的

**Comment by bitternolis** [comment]
所有的自由都是相对的，看看法国大革命之后成了什么样子，正是因为有太多利用网络打击中国的集团存在，我们才需要封锁网络。那些翻墙学习搜索资料的人，自然有法子翻出去。还新闻自由，都是谣言。

**Comment by louiewh** [comment]
虽然现在有很多不满意的地方，但是什么西方的民主宪政那套玩意真的在打完玩不转，只会更乱。

**Comment by pldeom** [comment]
不支持也不反对

**Comment by fq19851220** [comment]
建议删了 不然git也要被墙

**Comment by theratlesnake** [comment]
有些人啊，翻 墙都翻出了斯德哥尔摩综合症，建议早点吃药治疗。

**Comment by zuozuo3507** [comment]
发广告的就删了吧，与主题无关

**Comment by xxnet** [comment]
到处发广告，封id了

**Comment by broardshore** [comment]
建议删帖，别GitHub也被墙了
