### ISSUE TITLE
安装2.0.7的通过代理访问证书异常

### ISSUE THREAD

**Issue by jun-luo-changsha** [XX-net/XX-Net#777]
比如访问YouTube会显示证书颁发者是Goagent XX-NET

**Comment by jun-luo-changsha** [comment]
参考#636 已解决

**Comment by xxnet** [comment]
证书颁发者是Goagent XX-NET 是正常。
先确认你的证书是否导入？
访问github是否也提示异常？（github是强制https）

什么操作系统，把状态页贴出来

在 2015年8月7日 上午10:17，jun-luo-changsha <notifications@github.com>写道：
