### ISSUE TITLE
使用xx-net观看youtube视频时一直限速在128kb/s

### ISSUE THREAD

**Issue by HalfMAI** [XX-net/XX-Net#778]
使用xx-net观看youtube视频时一直限速在128kb/s

浏览器:chrome
xx-net版本:v2.0.5

测试网络是20M光纤，
使用VPN观看时满速 2m/s

使用xx-net时，打开chrome的任务管理器看得到速度被限制在128kb/s

请问有其它人遇到这种情况么？还是说这个需要设置autorange做优化？我已经测试过更改里面的数据没有发现有变化

**Comment by abcdcan** [comment]
卡卡卡。

**Comment by kenpachi123** [comment]
感觉到卡但是没注意具体速度。

发自我的 iPhone

**Comment by cdmask** [comment]
卡

**Comment by wcg928** [comment]
我也感觉youtube 很卡,以前4K视频都能播放的

**Comment by xxnet** [comment]
好像墙增加了墙外访问的限速功能？

2015-08-10 8:36 GMT+08:00 wcg928 <notifications@github.com>:
