### ISSUE TITLE
在Fedora22无法正常运行？（已解决）

### ISSUE THREAD

**Issue by l1000x** [XX-net/XX-Net#779]
在Fedora22无法正常运行？
下面贴出log.log

**Comment by xxnet** [comment]
请详细描述，把启动的日志贴出来

2015-08-07 12:49 GMT+08:00 l1000x <notifications@github.com>:

**Comment by l1000x** [comment]
Aug  7 13:42:10 - [WARNING] import pynotify fail, please install python-notify if possiable.
Aug  7 13:42:11 - [DEBUG] start confirm_xxnet_exit
Aug  7 13:42:11 - [ERROR] start module gae_proxy fail:libssl.so.1.0.0: 无法打开共享对象文件: 没有那个文件或目录
Aug  7 13:42:11 - [INFO] start gae_proxy time cost 20
Aug  7 13:42:12 - [INFO] get uuid:80349ca9-da04-419e-b5e7-f70533ec6127
Aug  7 13:42:12 - [WARNING] check_update fail:URLError(error(111, '\xe6\x8b\x92\xe7\xbb\x9d\xe8\xbf\x9e\xe6\x8e\xa5'),)
Aug  7 13:42:12 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/x/3/XX-Net-2.0.7/data/downloads/README.md
Aug  7 13:42:12 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/x/3/XX-Net-2.0.7/data/downloads/README.md fail:URLError(error(111, '\xe6\x8b\x92\xe7\xbb\x9d\xe8\xbf\x9e\xe6\x8e\xa5'),)
Aug  7 13:42:12 - [ERROR] check_update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Aug  7 13:42:36 - [ERROR] stop module gae_proxy fail:'imp'
Aug  7 13:42:36 - [INFO] begin to exit web control
Aug  7 13:42:36 - [INFO] launcher web control exited.

**Comment by xxnet** [comment]
看日志是ssl库有问题，我下一个fedora22 看看

2015-08-07 13:44 GMT+08:00 l1000x <notifications@github.com>:

**Comment by l1000x** [comment]
谢谢

**Comment by xxnet** [comment]
XX-Net自带的OpenSSL无法在Fedora 22下工作，请安装系统的版本：

sudo dnf install pyOpenSSL.noarch
已测试有效

2015-08-07 19:04 GMT+08:00 l1000x <notifications@github.com>:

**Comment by l1000x** [comment]
赞

**Comment by simonasd** [comment]
已将此问题记载到Wiki的[故障速查手册](https://github.com/XX-net/XX-Net/wiki/%E6%95%85%E9%9A%9C%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8C)中。

**Comment by cqspirit** [comment]
Centos 6.6下也报这个错，无法解决。。
