### ISSUE TITLE
简直要疯了,我不知道为什么,之前的版本,证书都能导入正常,十九大之后,一直就不能用了

### ISSUE THREAD

**Issue by ruiyongsheng** [XX-net/XX-Net#7792]
简直要疯了,我不知道为什么,之前的版本,证书都能导入正常,十九大之后,一直就不能用了,
我尝试了如下方法:
1.  xx-net我重装了好多次,证书已经删了,重新导入,不行
2.  按照网上的教程,删除data/gae_proxy里的所有文件,重新导入,还是不行
3. 重置chrome浏览器,不行
4.  卸载重装chrome浏览器,依旧不行
求大佬解决?
# XX-Net Status:

sys-platform: x86_64, Linux-4.9.0-deepin12-amd64-x86_64-with-Deepin-15.4.1-unstable
os-system: Linux
os-version: #1 SMP PREEMPT Deepin 4.9.40-3 (2017-09-19)
os-release: 4.9.0-deepin12-amd64
os-detail: Dist:Deepin; Version:15.4.1; ID:unstable
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
xxnet-version: 3.7.7
python-version: 2.7.13+
openssl-version: 16.2.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:8 good:8
network-status: OK
connected-link: new:0 used:0
worker: h1:2 h2:6
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by onplus** [comment]
和证书没关系 https://github.com/XX-net/XX-Net#最新状态


建议买xtunnel 或者 自建ss

**Comment by szwwluogang** [comment]
强制刷新

**Comment by theratlesnake** [comment]
IP都被封完了，就那么简单啊，而且按目前的走势，也不可能再恢复了实在不行就用X-tunnel呗，反正有X大在维护，或者蓝灯也不错，也有团队在维护
