### ISSUE TITLE
code文件夹中的老版本可以删除吗

### ISSUE THREAD

**Issue by q1374147274** [XX-net/XX-Net#7798]
如题，根目录文件夹中的code里面有版本号的文件夹。还有个default版本

我都打开看了 default版本是下载的时候的版本，现在更新后这些文件可以删掉吗

**Comment by colachen2017** [comment]
你試下看看啊， 刪掉不好用再復原

**Comment by lengfwang** [comment]
可以删除。

**Comment by xxnet** [comment]
​发了个任务：
https://github.com/XX-net/XX-Net-dev/issues/72

谁有编程经验的，可以来帮忙搞搞

**Comment by 308901951** [comment]
可以删除，一直是删除用的
