### ISSUE TITLE
支持封锁网络，阻碍新闻自由的，都是盗国贼！打倒共产党里的盗国贼！结束一党独裁！建立民主宪政中国！

### ISSUE THREAD

**Issue by fioolbx** [XX-net/XX-Net#7799]
向大家推荐台湾民视新闻台的政论节目《政经看民视》 每晚19:55直播
台湾民视新闻youtube直播地址：https://gaming.youtube.com/watch?v=XxJKnDLYZz4
《政经看民视》youtube 地址：https://www.youtube.com/channel/UCYIADVzNi0a3tebP67uKqpA/videos
《政经看民视》twitter： https://twitter.com/dennispamandal
曹長青 twitter： https://twitter.com/caochangqing
google：https://www.google.com
youtube：https://www.youtube.com
Facebook：https://www.facebook.com
Twitter：https://twitter.com
台湾自由時報：http://www.ltn.com.tw
BBC：http://www.bbc.com/zhongwen/simp
美国之音：https://www.voachinese.com
德国之声：http://www.dw.com/zh
法新社：http://cn.rfi.fr/
韩国之眼 朝鲜日报网：http://cnnews.chosun.com
韩国中央日报：http://chinese.joins.com/gb
纽约时报：https://cn.nytimes.com
台湾中央社：http://www.cna.com.tw
蔡英文 Facebook：https://www.facebook.com/tsaiingwen
賴清德 Facebook：https://www.facebook.com/chingte
賴清德：6個決心不變，回应習近平提6個任何。賴清德說，行政院一貫立場，是捍衛台灣主權決心不變；維護國人自由、民主、人權生活決心不變；發展經濟、壯大台灣的決心不變；透過交流、求同存異，深化兩岸和平發展決心不變；維護國人對於未來權利的選擇權決心不變；也會捍衛區域的和平安全，這個決心也不會改變。
公平正义、民主宪政、三权分立、多党制、军队国家化、司法独立、普选、新闻自由、公民社会、公民权利、普世价值！
零八宪章全文：https://www.voachinese.com/a/charter-2008-109947549/773226.html

                                           零八宪章
一、前言
今年是中国立宪百年，《世界人权宣言》公布60周年，“民主墙”诞生30周年，中国政府签署《公民权利和政治权利国际公约》10周年。在经历了长期的人权灾难和艰难曲折的抗争历程之后，觉醒的中国公民日渐清楚地认识到，自由、平等、人权是人类共同的普世价值；民主、共和、宪政是现代政治的基本制度架构。抽离了这些普世价值和基本政制架构的“现代化”，是剥夺人的权利、腐蚀人性、摧毁人的尊严的灾难过程。21世纪的中国将走向何方，是继续这种威权统治下的“现代化”，还是认同普世价值、融入主流文明、建立民主政体？这是一个不容回避的抉择。

19世纪中期的历史巨变，暴露了中国传统专制制度的腐朽，揭开了中华大地上“数千年未有之大变局”的序幕。洋务运动追求器物层面的进良，甲午战败再次暴露了体制的过时；戊戌变法触及到制度层面的革新，终因顽固派的残酷镇压而归于失败；辛亥革命在表面上埋葬了延续2000多年的皇权制度，建立了亚洲第一个共和国。囿于当时内忧外患的特定历史条件，共和政体只是昙花一现，专制主义旋即卷土重来。器物模仿和制度更新的失败，推动国人深入到对文化病根的反思，遂有以“科学与民主”为旗帜的“五四”新文化运动，因内战频仍和外敌入侵，中国政治民主化历程被迫中断。抗日战争胜利后的中国再次开启了宪政历程，然而国共内战的结果使中国陷入了现代极权主义的深渊。1949年建立的“新中国”，名义上是“人民共和国”，实质上是“党天下”。执政党垄断了所有政治、经济和社会资源，制造了反右、大跃进、文革、六四、打压民间宗教活动与维权运动等一系列人权灾难，致使数千万人失去生命，国民和国家都付出了极为惨重的代价。

二十世纪后期的“改革开放”，使中国摆脱了毛泽东时代的普遍贫困和绝对极权，民间财富和民众生活水平有了大幅度提高，个人的经济自由和社会权利得到部分恢复，公民社会开始生长，民间对人权和政治自由的呼声日益高涨。执政者也在进行走向市场化和私有化的经济改革的同时，开始了从拒绝人权到逐渐承认人权的转变。中国政府于1997年、1998年分别签署了两个重要的国际人权公约，全国人大于2004年通过修宪把“尊重和保障人权”写进宪法，今年又承诺制订和推行《国家人权行动计划》。但是，这些政治进步迄今为止大多停留在纸面上；有法律而无法治，有宪法而无宪政，仍然是有目共睹的政治现实。执政集团继续坚持维系威权统治，排拒政治变革，由此导致官场腐败，法治难立，人权不彰，道德沦丧，社会两极分化，经济畸形发展，自然环境和人文环境遭到双重破坏，公民的自由、财产和追求幸福的权利得不到制度化的保障，各种社会矛盾不断积累，不满情绪持续高涨，特别是官民对立激化和群体事件激增，正在显示着灾难性的失控趋势，现行体制的落伍已经到了非改不可的地步。

二、我们的基本理念

当此决定中国未来命运的历史关头，有必要反思百年来的现代化历程，重申如下基本理念：

自由：自由是普世价值的核心之所在。言论、出版、信仰、集会、结社、迁徙、罢工和游行示威等权利都是自由的具体体现。自由不昌，则无现代文明可言。

人权：人权不是国家的赐予，而是每个人与生俱来就享有的权利。保障人权，既是政府的首要目标和公共权力合法性的基础，也是“以人为本”的内在要求。中国的历次政治灾难都与执政当局对人权的无视密切相关。人是国家的主体，国家服务于人民，政府为人民而存在。

平等：每一个个体的人，不论社会地位、职业、性别、经济状况、种族、肤色、宗教或政治信仰，其人格、尊严、自由都是平等的。必须落实法律面前人人平等的原则，落实公民的社会、经济、文化、政治权利平等的原则。

共和：共和就是“大家共治，和平共生”，就是分权制衡与利益平衡，就是多种利益成分、不同社会集团、多元文化与信仰追求的群体，在平等参与、公平竞争、共同议政的基础上，以和平的方式处理公共事务。

民主：最基本的涵义是主权在民和民选政府。民主具有如下基本特点：（1）政权的合法性来自人民，政治权力来源于人民；（2）政治统治经过人民选择，（3）公民享有真正的选举权，各级政府的主要政务官员必须通过定期的竞选产生。（4）尊重多数人的决定，同时保护少数人的基本人权。一句话，民主使政府成为"民有，民治，民享"的现代公器。

宪政：宪政是通过法律规定和法治来保障宪法确定的公民基本自由和权利的原则，限制并划定政府权力和行为的边界，并提供相应的制度设施。

在中国，帝国皇权的时代早已一去不复返了；在世界范围内，威权体制也日近黄昏；公民应该成为真正的国家主人。祛除依赖“明君”、“清官”的臣民意识，张扬权利为本、参与为责的公民意识，实践自由，躬行民主，尊奉法治，才是中国的根本出路。

三、我们的基本主张
借此，我们本着负责任与建设性的公民精神对国家政制、公民权利与社会发展诸方面提出如下具体主张：

1、修改宪法：根据前述价值理念修改宪法，删除现行宪法中不符合主权在民原则的条文，使宪法真正成为人权的保证书和公共权力的许可状，成为任何个人、团体和党派不得违反的可以实施的最高法律，为中国民主化奠定法权基础。

2、分权制衡：构建分权制衡的现代政府，保证立法、司法、行政三权分立。确立法定行政和责任政府的原则，防止行政权力过分扩张；政府应对纳税人负责；在中央和地方之间建立分权与制衡制度，中央权力须由宪法明确界定授权，地方实行充分自治。

3、立法民主：各级立法机构由直选产生，立法秉持公平正义原则，实行立法民主。

4、司法独立：司法应超越党派、不受任何干预，实行司法独立，保障司法公正；设立宪法法院，建立违宪审查制度，维护宪法权威。尽早撤销严重危害国家法治的各级党的政法委员会，避免公器私用。

5、公器公用：实现军队国家化，军人应效忠于宪法，效忠于国家，政党组织应从军队中退出，提高军队职业化水平。包括警察在内的所有公务员应保持政治中立。消除公务员录用的党派歧视，应不分党派平等录用。

6、人权保障：切实保障人权，维护人的尊严。设立对最高民意机关负责的人权委员会，防止政府滥用公权侵犯人权，尤其要保障公民的人身自由，任何人不受非法逮捕、拘禁、传讯、审问、处罚，废除劳动教养制度。

7、公职选举：全面推行民主选举制度，落实一人一票的平等选举权。各级行政首长的直接选举应制度化地逐步推行。定期自由竞争选举和公民参选法定公共职务是不可剥夺的基本人权。

8、城乡平等：废除现行的城乡二元户籍制度，落实公民一律平等的宪法权利，保障公民的自由迁徙权。

9、结社自由：保障公民的结社自由权，将现行的社团登记审批制改为备案制。开放党禁，以宪法和法律规范政党行为，取消一党垄断执政特权，确立政党活动自由和公平竞争的原则，实现政党政治正常化和法制化。

10、集会自由：和平集会、游行、示威和表达自由，是宪法规定的公民基本自由，不应受到执政党和政府的非法干预与违宪限制。

11、言论自由：落实言论自由、出版自由和学术自由，保障公民的知情权和监督权。制订《新闻法》和《出版法》，开放报禁，废除现行《刑法》中的"煽动颠覆国家政权罪"条款，杜绝以言治罪。

12、宗教自由：保障宗教自由与信仰自由，实行政教分离，宗教信仰活动不受政府干预。审查并撤销限制或剥夺公民宗教自由的行政法规、行政规章和地方性法规；禁止以行政立法管理宗教活动。废除宗教团体（包括宗教活动场所）必经登记始获合法地位的事先许可制度，代之以无须任何审查的备案制。

13、公民教育：取消服务于一党统治、带有浓厚意识形态色彩的政治教育与政治考试，推广以普世价值和公民权利为本的公民教育，确立公民意识，倡导服务社会的公民美德。

14、财产保护：确立和保护私有财产权利，实行自由、开放的市场经济制度，保障创业自由，消除行政垄断；设立对最高民意机关负责的国有资产管理委员会，合法有序地展开产权改革，明晰产权归属和责任者；开展新土地运动，推进土地私有化，切实保障公民尤其是农民的土地所有权。

15、财税改革：确立民主财政和保障纳税人的权利。建立权责明确的公共财政制度构架和运行机制，建立各级政府合理有效的财政分权体系；对赋税制度进行重大改革，以降低税率、简化税制、公平税负。非经社会公共选择过程，民意机关决议，行政部门不得随意加税、开征新税。通过产权改革，引进多元市场主体和竞争机制，降低金融准入门槛，为发展民间金融创造条件，使金融体系充分发挥活力。

16、社会保障：建立覆盖全体国民的社会保障体制，使国民在教育、医疗、养老和就业等方面得到最基本的保障。

17、环境保护：保护生态环境，提倡可持续发展，为子孙后代和全人类负责；明确落实国家和各级官员必须为此承担的相应责任；发挥民间组织在环境保护中的参与和监督作用。

18、联邦共和：以平等、公正的态度参与维持地区和平与发展，塑造一个负责任的大国形象。维护香港、澳门的自由制度。在自由民主的前提下，通过平等谈判与合作互动的方式寻求海峡两岸和解方案。以大智慧探索各民族共同繁荣的可能途径和制度设计，在民主宪政的架构下建立中华联邦共和国。

19、转型正义：为历次政治运动中遭受政治迫害的人士及其家属，恢复名誉，给予国家赔偿；释放所有政治犯和良心犯，释放所有因信仰而获罪的人员；成立真相调查委员会，查清历史事件的真相，厘清责任，伸张正义；在此基础上寻求社会和解。

四、结语
中国作为世界大国，作为联合国安理会五个常任理事国之一和人权理事会的成员，理应为人类和平事业与人权进步做出自身的贡献。但令人遗憾的是，在当今世界的所有大国里，唯独中国还处在威权主义政治生态中，并由此造成连绵不断的人权灾难和社会危机，束缚了中华民族的自身发展，制约了人类文明的进步──这种局面必须改变！政治民主化变革不能再拖延下去。

为此，我们本着勇于践行的公民精神，公布《零八宪章》。我们希望所有具有同样危机感、责任感和使命感的中国公民，不分朝野，不论身份，求同存异，积极参与到公民运动中来，共同推动中国社会的伟大变革，以期早日建成一个自由、民主、宪政的国家，实现国人百余年来锲而不舍的追求与梦想。

**Comment by silascript** [comment]
傻B狗，老想让别人当炮灰，喊得这么猛，自己上啊，等你革命成功了，我们大家享受民主自由的果实！

**Comment by muxushizi** [comment]
@网警

**Comment by shindaren** [comment]
小伙子，别光嘴上说，我上学的时候，过双十节的时候，把学校共匪的旗给降下来了，你做过？

**Comment by Occup** [comment]
你有什么观点无所谓，我也懒得和你争个对错，
但给github无关政治，你在这个地方水这个内容怕是石乐志？

**Comment by xpf7622** [comment]
习主席挺不错的，不要在这里发这些言论。
我们上网只不过是想找些资料（比如科学研究最先进的资料），而不是反党。如果这里都是反党的，我们以后翻墙不可能了。

**Comment by Niinetan** [comment]
这智商失了智

**Comment by 308901951** [comment]
其实这位应该知道在这里的人心里跟明镜似的，这里只是技术交流平头，不必启蒙在这里面的人，一味鲁莽只会带来麻烦，不希望你是这里的麻烦制造者，希望你为大家多考虑

**Comment by xx-xx-xx-xx** [comment]
你别是个傻子吧？欧美为什么要针对中国，要启动303法则，因为怕现在的中国政治体系，这是个理想的政治体系，一党执政，能保证所有的政策都有效执行，而不是有别的党派从中作梗，中国用这么短的时间强势崛起就已经证明这一点。居然还看台湾的政治访谈节目？傻子？台湾那边这么多年来自己自以为是，看不起大陆，说大陆这里落后，那里落后，结果呢？讲真，我这段时间翻墙看的最多的就是台湾的喜剧“政治访谈类”。兵推？20架f35干翻中国空军？笑尿了。大陆这边从小收到的教育是，大陆台湾是一个国家，是同胞，我们要和平共处，结果翻了墙才发现，我们对你们台湾太宽容了，我们收到包容性的教育，你们却是诋毁，辱骂，看不起。别特么说，油管上大陆人喷你们，每一个大陆人翻墙前都是以友好共处的姿态面对你们，翻墙后，你们骂我们，我们还他么不能还嘴了？你说的人权限制我没看见，我只知道，我生活在一个制度健全，治安健全，能让人民安居乐业的国家。

**Comment by 335869741** [comment]
这里不是绿营宣传的地方，请你滚出去

**Comment by shindaren** [comment]
楼上两个五毛共匪。666666666

**Comment by happyvsp** [comment]
删了吧。。已经有消息说明年连github也要墙掉了你还在这里搞事怕不是嫌墙得不够快

**Comment by fengjie2018** [comment]
于理，这是一个技术交流平台，不是政治宣传平台，而且我拥护我的国家和我共党（虽然我不认同网络墙）。
与情，70年来，这个国家确实富强了，大部分人生活水平确实提高了，这里面没有我共的功劳吗？如果真的听了你的怂恿，给你当枪使，然后被消失，那才是智障，我想能来GITHUB的应该都有点脑子。
所以请你滚吧。

**Comment by fengjie2018** [comment]
你看看这里的大部分评论，你就明白，这个国家，这个政党目前是无法被撼动的，死了这份心吧。
