### ISSUE TITLE
看youtube没问题，其他视频网站无法观看

### ISSUE THREAD

**Issue by fhzyfjy** [XX-net/XX-Net#78]
如题。是不是设置问题？谢谢

**Comment by xxnet** [comment]
有可能存在一个bug，导致视频播放有问题，xvideos.com 有人反馈过，
niconico则使用自动模式可以解决（导入SwitchSharp/下面的.bak文件）

2015-03-23 9:26 GMT-04:00 fhzyfjy <notifications@github.com>:

**Comment by fhzyfjy** [comment]
niconico则使用自动模式可以解决（导入SwitchSharp/下面的.bak文件）
上述如何具体操作啊。我把SwitchSharp设置到自动模式连网都上不了。谢谢

**Comment by fhzyfjy** [comment]
最新版本1.4.1仍然无法观看其他网站视频。大家用这款软件主要是看视频的。烦请版主解决或答复。谢谢

**Comment by xxnet** [comment]
XX-Net优先解决的是看网页，视频的问题比较复杂，有些是GAE屏蔽，有些是对GAE屏蔽，有些还存在技术问题需要解决。
逐步来吧，谢谢支持。

在 2015年3月29日 上午6:41，fhzyfjy <notifications@github.com>写道：

**Comment by fhzyfjy** [comment]
理解。非常感谢

**Comment by hqs998** [comment]
我用3.1.2的GAE+使用自己寻找的IP看xvideos.com是没问题的，用xx-net就不行，用自己的ips也不行

**Comment by xxnet** [comment]
目前的版本，部分xvideo可以播放，部分不行，暂时没找到通用方案。
测试上看，是GAE文件无法自动分片

2015-04-13 22:56 GMT-04:00 hqs998 <notifications@github.com>:

**Comment by sunshie2177** [comment]
youtube视频看起来缓冲结束，但是刚播放一点就自动转到下一个视频，根本就没有播放完，还不是个别现象，都是这样。什么问题？如何解决？谢谢！

**Comment by xxnet** [comment]
没有遇到过，你把日志贴出来看看

在 2015年4月14日 上午11:35，sunshie2177 <notifications@github.com>写道：
