### ISSUE TITLE
删掉你电脑里面的某些软件,让翻墙软件稳定运行

### ISSUE THREAD

**Issue by fioolbx** [XX-net/XX-Net#7800]
本人亲测，把电脑里面的国产软件全卸载了，有些翻墙软件就好用了。阿里的流氓软件也要删掉后台进程全部删干净。搜狗浏览器，腾讯浏览器，输入法等等，全都要卸掉！
第三方监控；国内某安全卫士/管家，某输入法等等收集个人信息，全要卸载！
爱信不信，想翻墙还在自己的电脑里面装国产监控，那不是自己给自己找麻烦！

**Comment by shindaren** [comment]
小伙子，你现在才知道，我们都是几年前就知道了。
too young too simple.

**Comment by shindaren** [comment]
sometimes naive.

**Comment by yiqing95** [comment]
原来 还有这重视

**Comment by yiqing95** [comment]
原来 还有这种情况 ？

**Comment by theratlesnake** [comment]
我上次就是这样的建议，结果被人喷，楼主你也要小心了，政 治正确啊，呵呵。

**Comment by onplus** [comment]
换个小号行不行？
还以为你是台湾的呢，竟然装过管家卫士？
https://github.com/XX-net/XX-Net/issues/7799

**Comment by silascript** [comment]
够傻的，自欺欺人，还亲测，你家网络就是人家电信、联通的内网，以为不装那些软件就能躲过监视！要怕监视自己拉条光缆到美国－－到了美国也一样被监视，不过监视对你换成美国佬而已！

**Comment by Rintim** [comment]
一直不装，觉得没用，还占内存。

**Comment by theratlesnake** [comment]
https://github.com/getlantern/forum/issues/6153  一堆人反馈把国产输入法删了，蓝灯立马复活，楼主也是好心建议，@silascript  何必喷人？难道你是......？

**Comment by SeaHOH** [comment]
这年头根本不可能摆脱大数据监控，只是暴露的或多或少而已。
想对党国保持隐私，除非完全脱离国内网络环境。

**Comment by onplus** [comment]
@theratlesnake 一两个反馈，你就说一堆人了？你比共党更会代表别人了
还动不动就扣帽子。
软件肯定有后门，
但你真要分析就把数据抓包，代码分析贴出来，不要捕风捉影！

**Comment by allcatzoo** [comment]
不用为上。

**Comment by xx-xx-xx-xx** [comment]
不不不，能监控说明技术到位了，你去美国，英国照样监控，但台湾？恩，台湾估计没有

**Comment by jooloog** [comment]
真逗

**Comment by SeaHOH** [comment]
@theratlesnake @onplus
没有证据表明有**真正**的木马式行为，收集的信息都是用户“自愿”提交给所用软件的，然后党国可以随便审查。

因为其他人可以测试这个软件，而且一定能查出来，所以不会有明目张胆的木马行为。
