### ISSUE TITLE
弱弱问一下，一个X_tunnel账号最多能在几个设备上使用？

### ISSUE THREAD

**Issue by BrandyJer** [XX-net/XX-Net#7802]
弱弱问一下，一个X_tunnel账号最多能在几个设备上使用？
win7下配置好了，也能正常使用，但是ubuntu16.04下的chrome总是无法导入证书，重新重头试过好几次都不行。

**Comment by xxnet** [comment]
​x-tunnel 不限制设备数。
x-tunnel 不需要导入证书

**Comment by BrandyJer** [comment]
使用方法

首先下载XX-Net客户端

解压后点击 start.vbs 运行
点击xx图标，进入web页面

ubuntu下，是否是将“运行start.vbs”换成“sudo ./xx_net.sh”?

**Comment by BrandyJer** [comment]
好的，昨天可能是系统出问题了，ubuntu不稳定，今天可以了。
操作很简单，自己理解的复杂了。
多谢。
