### ISSUE TITLE
为什么扫描线程数显示是0

### ISSUE THREAD

**Issue by AbelaroJiang** [XX-net/XX-Net#7818]
为什么扫描线程数显示是0呢？
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
xxnet-version: 3.7.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:601
network-status: OK
connected-link: new:0 used:0
worker: h1:40 h2:0
scan-ip-thread-num: 0
ip-quality: 571
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

![image](https://user-images.githubusercontent.com/22406984/32204904-273ba3d0-be27-11e7-8964-b54a8b7b965a.png)

**Comment by OuyangIPC** [comment]
没提交上吧，重新提交一次呢？

**Comment by AbelaroJiang** [comment]
重新提交了还是一样哦

**Comment by AbelaroJiang** [comment]
但是使用正常， 可能是显示的问题
