### ISSUE TITLE
关于xxnet没有像GoAgent需要安装依赖的疑问

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#782]
为什么GoAgent要安装依赖：
sudo apt-get install python-dev python-greenlet python-gevent python-vte python-openssl python-crypto python-appindicator 
sudo apt-get install python-dev python-pip && sudo pip install gevent --upgrade
而xxnet却不要呢？会不会牺牲了安全性？

**Comment by xxnet** [comment]
这些库是XX-Net自带了，目的是减少使用者的麻烦。
对于安全性，XX-Net只是作为连接的客户端，不像服务端那样目标明确容易成为攻击目标。
对于钓鱼攻击，比如伪装成Goog le ip等着连接，那需要ssl
客户端存在严重的安全漏洞才行，目前还没有发现，但不排除，当然如果某一天OpenSSL被爆出这样的漏洞，我们也可以升级解决。而这种漏洞，自带库的安全性和系统默认库，差别并不大，都需要更新解决。

2015-08-07 22:43 GMT+08:00 fletchere <notifications@github.com>:
