### ISSUE TITLE
无法登陆！！！！

### ISSUE THREAD

**Issue by GFconcept** [XX-net/XX-Net#7846]
Oct 31 17:33:34.313 - [INFO] Socks5 server listen:127.0.0.1:1080.
Oct 31 17:33:37.688 - [DEBUG] session not running, try login..
Oct 31 17:33:47.843 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:33:47.843 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:33:47.843 - [WARNING] create conn fail
Oct 31 17:33:47.843 - [DEBUG] session not running, try login..
Oct 31 17:33:57.850 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:33:57.850 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:33:57.851 - [WARNING] create conn fail
Oct 31 17:33:57.851 - [DEBUG] session not running, try login..
Oct 31 17:34:07.859 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:07.860 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:34:07.862 - [WARNING] create conn fail
Oct 31 17:34:07.862 - [DEBUG] session not running, try login..
Oct 31 17:34:17.876 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:17.876 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:34:17.876 - [WARNING] create conn fail
Oct 31 17:34:17.876 - [DEBUG] session not running, try login..
Oct 31 17:34:22.216 - [DEBUG] x_tunnel force update info
Oct 31 17:34:27.915 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:27.915 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:34:27.915 - [WARNING] create conn fail
Oct 31 17:34:27.915 - [DEBUG] session not running, try login..
Oct 31 17:34:32.219 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:37.992 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:37.992 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:34:37.992 - [WARNING] create conn fail
Oct 31 17:34:37.992 - [DEBUG] session not running, try login..
Oct 31 17:34:38.680 - [DEBUG] x-tunnel web_control 127.0.0.1:1652 POST /login
Oct 31 17:34:48.001 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:48.001 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:34:48.001 - [WARNING] create conn fail
Oct 31 17:34:48.001 - [DEBUG] session not running, try login..
Oct 31 17:34:48.783 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:51.176 - [DEBUG] x-tunnel web_control 127.0.0.1:1652 POST /login
Oct 31 17:34:58.031 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:34:58.031 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:34:58.031 - [WARNING] create conn fail
Oct 31 17:34:58.031 - [DEBUG] session not running, try login..
Oct 31 17:35:17.167 - [WARNING] api:/login fail:status:500 t:25
Oct 31 17:35:17.172 - [WARNING] api:/login fail:status:500 t:19
Oct 31 17:35:17.172 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:35:17.172 - [WARNING] create conn fail
Oct 31 17:35:17.172 - [DEBUG] session not running, try login..
Oct 31 17:35:17.311 - [DEBUG] x_tunnel force update info
Oct 31 17:35:27.225 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:35:27.225 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:35:27.225 - [WARNING] create conn fail
Oct 31 17:35:27.225 - [DEBUG] session not running, try login..
Oct 31 17:35:27.369 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:35:37.299 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:35:37.299 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:35:37.299 - [DEBUG] session not running, try login..
Oct 31 17:35:37.299 - [WARNING] create conn fail
Oct 31 17:35:44.092 - [DEBUG] x-tunnel web_control 127.0.0.1:1654 POST /login
Oct 31 17:35:47.307 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:35:47.307 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:35:47.307 - [WARNING] create conn fail
Oct 31 17:35:47.307 - [DEBUG] session not running, try login..
Oct 31 17:35:54.099 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:35:57.317 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:35:57.317 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:35:57.317 - [WARNING] create conn fail
Oct 31 17:35:57.317 - [DEBUG] session not running, try login..
Oct 31 17:36:07.327 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:36:07.328 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:36:07.329 - [DEBUG] session not running, try login..
Oct 31 17:36:07.329 - [WARNING] create conn fail
Oct 31 17:36:17.343 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:36:17.344 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:36:17.344 - [WARNING] create conn fail
Oct 31 17:36:17.344 - [DEBUG] session not running, try login..
Oct 31 17:36:17.656 - [INFO] api:/login success t:310
Oct 31 17:36:17.656 - [INFO] update xt_server v8.xx-net.net:443
Oct 31 17:36:17.657 - [INFO] request_balance host:v8.xx-net.net port:443 balance:0.000000 quota:329855686927.000000
Oct 31 17:36:17.657 - [WARNING] session not running, try to connect
Oct 31 17:36:28.508 - [WARNING] login session fail, status:500
Oct 31 17:36:28.509 - [WARNING] x-tunnel login_session fail, session not start
Oct 31 17:36:28.509 - [DEBUG] session not running, try login..
Oct 31 17:36:28.509 - [WARNING] create conn fail
Oct 31 17:36:28.814 - [INFO] api:/login success t:303
Oct 31 17:36:28.814 - [INFO] update xt_server v9.xx-net.net:443
Oct 31 17:36:28.814 - [INFO] request_balance host:v9.xx-net.net port:443 balance:0.000000 quota:329855686927.000000
Oct 31 17:36:28.814 - [WARNING] session not running, try to connect
Oct 31 17:36:47.669 - [DEBUG] x-tunnel web_control 127.0.0.1:1654 POST /login
Oct 31 17:36:49.786 - [WARNING] login session fail, status:500
Oct 31 17:36:49.787 - [WARNING] x-tunnel login_session fail, session not start
Oct 31 17:36:49.787 - [WARNING] create conn fail
Oct 31 17:36:49.787 - [DEBUG] session not running, try login..
Oct 31 17:36:57.682 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:36:59.797 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:36:59.797 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:36:59.797 - [WARNING] create conn fail
Oct 31 17:36:59.797 - [DEBUG] session not running, try login..
Oct 31 17:37:09.824 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:37:09.824 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:37:09.825 - [WARNING] create conn fail
Oct 31 17:37:09.825 - [DEBUG] session not running, try login..
Oct 31 17:37:19.888 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:37:19.888 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:37:19.888 - [WARNING] create conn fail
Oct 31 17:37:19.888 - [DEBUG] session not running, try login..
Oct 31 17:38:32.957 - [WARNING] api:/login fail:status:500 t:73
Oct 31 17:38:32.958 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:38:32.959 - [WARNING] create conn fail
Oct 31 17:38:32.959 - [DEBUG] session not running, try login..
Oct 31 17:38:34.101 - [DEBUG] x-tunnel web_control 127.0.0.1:1654 POST /login
Oct 31 17:38:42.971 - [WARNING] api:/login fail:status:500 t:10
Oct 31 17:38:42.971 - [WARNING] x-tunnel request_balance fail when create_conn:status:500
Oct 31 17:38:42.971 - [WARNING] create conn fail
Oct 31 17:38:42.972 - [DEBUG] session not running, try login..
Oct 31 17:38:44.110 - [WARNING] api:/login fail:status:500 t:10

**Comment by xxnet** [comment]
​是哪个版本？
把X-tunnel状态页贴来看看
