### ISSUE TITLE
现在申请google appengine的appid需要填信用卡号？？

### ISSUE THREAD

**Issue by clawshadow** [XX-net/XX-Net#7849]
我有二三十个快10年的号，以前布署appid的时候，也不要手机号什么的，很容易就建立APPID，并布署

刚才去试了下，竟然要手机号，美国地址，谷歌现在也挺坑啊，开始显示，地址必，邮编，电话必填，等到我去中介网站找到了一所房子的地址，邮编，电话

它它它，又要信用卡号

还能愉快的玩耍吗？

**Comment by onplus** [comment]
你已经部署几十个了 ？

**Comment by clawshadow** [comment]
有20个appid以前弄的，有四五年了吧
得瑟了一下，朋友想要，打算给他申请几个，谁知道点了免费试用，要填，地址，邮编，信用卡

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

20 G够两个人普通使用了，不需要再申请了。

申请appid不需要点 免费试用，那和xxnet没关系了

**Comment by clawshadow** [comment]
感谢，很长时间没弄过，英文又是半调子，一下弄晕了，原来搞错地方了

对了，还有一个问题，如何查看，一个appid已经布署了xxnet

**Comment by onplus** [comment]
这就是一个部署好的appid 

### https://xxnet-1024.appspot.com/
