### ISSUE TITLE
xx-net已经关闭 但是ie浏览器显示无法连接代理

### ISSUE THREAD

**Issue by cdmask** [XX-net/XX-Net#785]
![default](https://cloud.githubusercontent.com/assets/11484898/9149192/28020f80-3dd1-11e5-82cb-5989b44bd4a6.JPG)

**Comment by farshidvahid** [comment]
更新到最新版2.07就解决了。

**Comment by thxhtp** [comment]
更新2.07 或者手动更改IE代理设置

**Comment by cdmask** [comment]
谢谢～

**Comment by cobob** [comment]
重新开启XX，然后关闭全局代理。

**Comment by cdmask** [comment]
嗯，这样可以。

**Comment by simonasd** [comment]
已将此问题记载到Wiki的[故障速查手册](https://github.com/XX-net/XX-Net/wiki/%E6%95%85%E9%9A%9C%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8C)中。

**Comment by xxnet** [comment]
good job!

2015-09-05 23:35 GMT+08:00 simonasd <notifications@github.com>:

**Comment by simonasd** [comment]
@xxnet 这个页面是按照我自己的理解编写的，难免有误，还请您有空的时候核查一下是否存在问题（尤其是开篇诊断指标那部分）。您可以把需要补充或者修改的地方提出来，我们大家来改，不占用您的时间。

**Comment by xxnet** [comment]
感谢， 诊断部分没有发现问题，如果能配一点图就更好了，毕竟图片更加直观。

如果你有时间能否补充几个文档：

1.一份给小白新手的图文说明
  原因：遇到很多新手，连代理都没有设置，就只知道无法翻墙，最后发现是没有设置代理。
  希望针对Windows7，Chrome 浏览器平台，
     一步一步的，从下载（这一步也有误解的，点了trunk的zip包），解压，启动（有不知道点哪个启动的），
   然后弹出浏览器，不知道要安装SwitchSharp，不知道要选GoAgent模式。

2. 补充一份Firefox的倒入证书的手册
  目前firefox无法自动倒入证书，所以经常遇到这类问题反馈。

谢谢


在 2015年9月6日 下午12:18，simonasd <notifications@github.com>写道：

**Comment by simonasd** [comment]
@xxnet Roger that~
