### ISSUE TITLE
一直显示“尚未建立连接”，3.7.7和3.7.8都一样 “扫描IP线程数”一直是0，但设置里面是10啊

### ISSUE THREAD

**Issue by YannKing** [XX-net/XX-Net#7853]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
xxnet-version: 3.7.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:9012
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by dahai058** [comment]
晚上又可以了，ip从十几个已增至六十几个。希望这次能稳定下来。感谢X大神

**Comment by zanewayne78** [comment]
ipv6开了就是0，现在还不支持扫描ipv6
