### ISSUE TITLE
X_tunnel无法登陆了

### ISSUE THREAD

**Issue by BrandyJer** [XX-net/XX-Net#7895]
Nov 02 08:38:34.606 - [DEBUG] session not running, try login..
Nov 02 08:39:55.988 - [WARNING] api:/login fail:status:501 t:81
Nov 02 08:39:55.998 - [WARNING] x-tunnel request_balance fail when create_conn:status:501
Nov 02 08:39:55.998 - [WARNING] create conn fail
Nov 02 08:39:55.998 - [DEBUG] session not running, try login..
Nov 02 08:40:36.994 - [WARNING] api:/login fail:status:501 t:40
Nov 02 08:40:36.994 - [WARNING] x-tunnel request_balance fail when create_conn:status:501
Nov 02 08:40:36.994 - [WARNING] create conn fail
Nov 02 08:40:36.994 - [DEBUG] session not running, try login..
Nov 02 08:40:47.004 - [WARNING] api:/login fail:status:602 t:10
Nov 02 08:40:47.004 - [WARNING] x-tunnel request_balance fail when create_conn:status:602
Nov 02 08:40:47.004 - [WARNING] create conn fail
Nov 02 08:40:47.004 - [DEBUG] session not running, try login..
Nov 02 08:40:57.018 - [WARNING] api:/login fail:status:602 t:10
Nov 02 08:40:57.018 - [WARNING] x-tunnel request_balance fail when create_conn:status:602
Nov 02 08:40:57.018 - [WARNING] create conn fail

Nov 02 09:30:28.283 - [INFO] Socks4:('127.0.0.1', 64864) to 66.220.147.47:443, conn_id:15
Nov 02 09:30:32.047 - [DEBUG] roundtrip time:5326 cost:5003 transfer_no:66 send_sn:66 send:25 recv_sn:0 rcv:11 status:200
Nov 02 09:30:32.077 - [DEBUG] roundtrip time:5342 cost:5010 transfer_no:68 send_sn:68 send:25 recv_sn:0 rcv:11 status:200
Nov 02 09:30:32.087 - [DEBUG] roundtrip time:5353 cost:5019 transfer_no:67 send_sn:67 send:25 recv_sn:0 rcv:11 status:200
Nov 02 09:30:33.584 - [DEBUG] roundtrip time:5301 cost:5010 transfer_no:69 send_sn:69 send:32 recv_sn:0 rcv:11 status:200
Nov 02 09:30:33.609 - [ERROR] request except:KeyError('POST jp1.xx-net.net/data:1509586228.283000',) retry 1
Nov 02 09:30:33.610 - [ERROR] Except stack:Traceback (most recent call last): File "D:\VPN\xx-net\XX-Net-3.7.4\code\default\x_tunnel\local\proxy_session.py", line 357, in normal_roundtrip_worker timeout=server_timeout + g.config.network_timeout) File "D:\VPN\xx-net\XX-Net-3.7.4\code\default\x_tunnel\local\front_dispatcher.py", line 42, in request return front.request(method, host=host, path=path, headers=headers, data=data, timeout=timeout) File "D:\VPN\xx-net\XX-Net-3.7.4\code\default\x_tunnel\local\cloudflare_front\front.py", line 93, in request response = dispatcher.request(method, host, path, headers, data, timeout=timeout) File "D:\VPN\xx-net\XX-Net-3.7.4\code\default\x_tunnel\local\cloudflare_front\http_dispatcher.py", line 191, in request del self.working_tasks[task.unique_id] KeyError: 'POST jp1.xx-net.net/data:1509586228.283000'
Nov 02 09:30:34.890 - [DEBUG] roundtrip time:280 cost:0 transfer_no:70 send_sn:70 send:213 recv_sn:0 rcv:11 status:200
Nov 02 09:30:40.544 - [INFO] Socks4:('127.0.0.1', 64891) to 66.220.147.47:443, conn_id:16
Nov 02 09:30:40.853 - [DEBUG] roundtrip time:309 cost:0 transfer_no:71 send_sn:71 send:32 recv_sn:32 rcv:752 status:200
Nov 02 09:30:40.854 - [DEBUG] roundtrip time:309 cost:0 transfer_no:72 send_sn:72 send:213 recv_sn:33 rcv:63 status:200
Nov 02 09:30:42.111 - [INFO] Socks4:('127.0.0.1', 64894) to 66.220.147.47:443, conn_id:17
Nov 02 09:30:42.424 - [DEBUG] roundtrip time:311 cost:0 transfer_no:74 send_sn:74 send:213 recv_sn:34 rcv:71 status:200
Nov 02 09:30:42.460 - [INFO] Socks4:('127.0.0.1', 64895) to 203.208.39.255:80, conn_id:18
Nov 02 09:30:46.142 - [DEBUG] Conn session:ttzacnzs conn:5 stop:recv fail.
Nov 02 09:30:46.142 - [DEBUG] remove conn_id:5
Nov 02 09:30:47.424 - [DEBUG] roundtrip time:5312 cost:5007 transfer_no:73 send_sn:73 send:32 recv_sn:0 rcv:11 status:200
Nov 02 09:30:47.730 - [DEBUG] roundtrip time:5305 cost:5001 transfer_no:75 send_sn:75 send:60 recv_sn:0 rcv:11 status:200
Nov 02 09:30:47.802 - [DEBUG] roundtrip time:5342 cost:5005 transfer_no:76 send_sn:76 send:33 recv_sn:0 rcv:11 status:200
Nov 02 09:30:47.803 - [DEBUG] roundtrip time:5342 cost:5015 transfer_no:77 send_sn:77 send:315 recv_sn:0 rcv:11 status:200
Nov 02 09:30:51.457 - [DEBUG] roundtrip time:5314 cost:5009 transfer_no:78 send_sn:78 send:25 recv_sn:0 rcv:11 status:200
Nov 02 09:30:58.285 - [DEBUG] Conn session:ttzacnzs conn:15 stop:recv fail.
Nov 02 09:30:58.286 - [DEBUG] remove conn_id:15
Nov 02 09:30:58.661 - [DEBUG] roundtrip time:375 cost:41 transfer_no:79 send_sn:79 send:25 recv_sn:35 rcv:37 status:200
Nov 02 09:31:10.550 - [DEBUG] Conn session:ttzacnzs conn:16 stop:recv fail.
Nov 02 09:31:10.550 - [DEBUG] remove conn_id:16
Nov 02 09:31:10.887 - [DEBUG] roundtrip time:337 cost:46 transfer_no:80 send_sn:80 send:25 recv_sn:36 rcv:37 status:200
Nov 02 09:31:12.121 - [DEBUG] Conn session:ttzacnzs conn:17 stop:recv fail.
Nov 02 09:31:12.121 - [DEBUG] remove conn_id:17
Nov 02 09:31:12.442 - [DEBUG] roundtrip time:320 cost:23 transfer_no:81 send_sn:81 send:25 recv_sn:37 rcv:37 status:200
Nov 02 09:31:26.599 - [INFO] Socks4:('127.0.0.1', 65005) to 64.233.188.188:5228, conn_id:19
Nov 02 09:31:26.928 - [DEBUG] roundtrip time:328 cost:1 transfer_no:82 send_sn:82 send:33 recv_sn:38 rcv:37 status:200
Nov 02 09:31:26.928 - [INFO] Conn session:ttzacnzs conn:18 Peer Close:connect fail
Nov 02 09:31:26.929 - [DEBUG] Conn session:ttzacnzs conn:18 stop:peer close
Nov 02 09:31:27.097 - [DEBUG] roundtrip time:496 cost:70 transfer_no:83 send_sn:83 send:200 recv_sn:39 rcv:4393 status:200
Nov 02 09:31:27.424 - [DEBUG] roundtrip time:496 cost:208 transfer_no:84 send_sn:84 send:20 recv_sn:40 rcv:346 status:200
Nov 02 09:31:27.519 - [DEBUG] remove conn_id:18
Nov 02 09:31:27.768 - [DEBUG] roundtrip time:666 cost:379 transfer_no:85 send_sn:85 send:272 recv_sn:41 rcv:55 status:200

**Comment by BrandyJer** [comment]
Nov 02 09:03:16.275 - [INFO] use config_path:D:\VPN\xx-net\XX-Net-3.7.4\data\x_tunnel\client.json
Nov 02 09:03:16.275 - [INFO] X-Tunnel window:33554432
Nov 02 09:03:16.275 - [INFO] Session Server:jp1.xx-net.net:443
Nov 02 09:03:16.285 - [INFO] Socks5 server listen:127.0.0.1:1080.
Nov 02 09:03:16.605 - [DEBUG] session not running, try login..
Nov 02 09:03:21.391 - [DEBUG] x_tunnel force update info
Nov 02 09:03:40.428 - [DEBUG] x-tunnel web_control 127.0.0.1:57174 POST /login
Nov 02 09:04:02.046 - [WARNING] api:/login fail:status:501 t:40
Nov 02 09:04:07.872 - [DEBUG] x_tunnel force update info
Nov 02 09:05:00.676 - [DEBUG] x_tunnel force update info
Nov 02 09:05:00.715 - [WARNING] api:/login fail:status:501 t:80
Nov 02 09:05:30.695 - [DEBUG] x_tunnel force update info
Nov 02 09:05:30.996 - [DEBUG] x-tunnel web_control 127.0.0.1:57636 POST /login
Nov 02 09:05:42.046 - [WARNING] api:/login fail:status:501 t:41
Nov 02 09:05:54.794 - [DEBUG] x-tunnel web_control 127.0.0.1:57723 POST /login
Nov 02 09:05:58.802 - [WARNING] api:/login fail:status:501 t:162
Nov 02 09:05:58.802 - [WARNING] x-tunnel request_balance fail when create_conn:status:501
Nov 02 09:05:58.802 - [WARNING] create conn fail
Nov 02 09:05:58.802 - [DEBUG] session not running, try login..
Nov 02 09:06:00.736 - [DEBUG] x_tunnel force update info
Nov 02 09:06:10.149 - [WARNING] api:/login fail:status:501 t:122
Nov 02 09:06:11.000 - [WARNING] api:/login fail:status:501 t:40
Nov 02 09:06:11.264 - [WARNING] api:/login fail:status:501 t:40
Nov 02 09:06:30.748 - [DEBUG] x_tunnel force update info
Nov 02 09:06:41.568 - [WARNING] api:/login fail:status:501 t:40
Nov 02 09:07:01.482 - [DEBUG] x_tunnel force update info
Nov 02 09:07:11.004 - [WARNING] api:/login fail:status:501 t:40
Nov 02 09:07:25.890 - [WARNING] api:/login fail:status:501 t:87
Nov 02 09:07:25.890 - [WARNING] x-tunnel request_balance fail when create_conn:status:501
Nov 02 09:07:25.890 - [WARNING] create conn fail
Nov 02 09:07:25.890 - [DEBUG] session not running, try login..
Nov 02 09:07:31.918 - [DEBUG] x_tunnel force update info
Nov 02 09:07:32.534 - [DEBUG] x-tunnel web_control 127.0.0.1:58308 POST /login

**Comment by xxnet** [comment]
​X-Tunnel 的状态页贴出来看看

**Comment by BrandyJer** [comment]
Cloudflare front

Property | Value
-- | --
Score | False
Success num | 0
Fail num | 5
Worker num | 0


Heroku front

Property | Value
-- | --
Score | False
Success num | 0
Fail num | 21
Worker num | 0

**Comment by BrandyJer** [comment]
Property | Value
-- | --
Score | 2885
Success num | 0
Fail num | 22
Worker num | 8

**Comment by BrandyJer** [comment]
Cloudflare front

Property | Value
-- | --
Score | False
Success num | 14
Fail num | 18
Worker num | 1


Heroku front

Property | Value
-- | --
Score | False
Success num | 0
Fail num | 49
Worker num | 3

现在能登录了，但是依然不能上外网。

**Comment by xxnet** [comment]
​请升级到最新版本

**Comment by BrandyJer** [comment]
更新到3.7.9已经可用，谢谢。
