### ISSUE TITLE
尚未建立链接 您应该考虑开启 IP 扫描器。

### ISSUE THREAD

**Issue by CNdsds** [XX-net/XX-Net#7914]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.7.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by CNdsds** [comment]
本来好好的然后电脑蓝屏重启就成这样了,艹

**Comment by Ikeblablabla** [comment]
@CNdsds 我电脑断网，我休眠再开，想把网恢复。
网恢复了，翻墙挂了....

**Comment by CNdsds** [comment]
@Ikeblablabla 你IPv6能连上么,我这蓝屏后连不上了

**Comment by gilbertjuly** [comment]
you are not alone.

**Comment by sutao80216** [comment]
我开了IPv6，今天升3.7.9后正常使用。晚饭后开机，XX提示扫描IP？！
点开配置页面，把高级选项下的两个开关切换一下状态再恢复原状，点保存，XX就神奇的恢复正常了！

**Comment by peterchan201604** [comment]
我的也是这样。这是一个bug。不只你一个，目前我知道的就有三个在论坛说出现蓝屏的事
[https://github.com/XX-net/XX-Net/issues/7778](url)

**Comment by CNdsds** [comment]
@peterchan201604 问题已经解决了,我这边蓝屏是因为游戏问题.
我去微软下载了个IPv6修复软件重启后就正常连接上了(不知道是不是因为抽风).

**Comment by dahai058** [comment]
3.7.8 ipv4.下午能用了

**Comment by kuchaguangjie** [comment]
重新下载 xxnet 试试.
