### ISSUE TITLE
至发反x言论的朋友！

### ISSUE THREAD

**Issue by 253681319** [XX-net/XX-Net#7961]
GitHub是中立的地方，你复制黏贴那些东西会害了GitHub会害了作者！
你发的那些东西和**老娘们儿**骂街没有任何区别毫无战斗力！
xx-net作者给我们提供了一个访问外网的工具，相信这里的大部分人对政治不感兴趣！
我只是想看一看空间站到哪了、YouTube上的一些有趣视频、以及有趣的代码！
请不要害了这个工具！
发表政治言论请去你该去的地方！
如果有“种”请去官府大门口！！！网络上的键盘侠没有任何意义！
如果你有能耐请自己写出有意义、有战斗力、有证据、有方案的文章！！！
否则请**滚蛋**！！

**Comment by GoodSake** [comment]
贴主发这个没任何意义,github目前还是自由之地，
他不发那些东西，GitHub和作者就不会被害吗？
在github还这么忍不住多管闲事替这替那担心。。。
too young, too simple!

**Comment by onplus** [comment]
@GoodSake 天天几个小号轮流发，管你什么内容，全部不允许

**Comment by GoodSake** [comment]
就跟gfw一样，不允许没意义，阻止不了的，他总是有办法发。
他不觉得累，你也不觉得累，就随便你们了。哈哈。看你一个阻一个破，也挺好。

**Comment by wlm2012** [comment]
发这些东西，要么是脑袋了里进了水，要么是收了钱（五毛美分都有可能）。介于他只发帖却不参与讨论，我觉得后者的可能性更大。

**Comment by TitusL** [comment]
发那些东西的人真的很烦人。

**Comment by breezeit** [comment]
那么喜欢发反x言论，自己买vpn发去啊，别祸害这里

**Comment by ylwszb** [comment]
又看到了，又再发，手动删贴不是办法，
能否对标题关键词进行识别屏蔽？
发现有相关关键词自动删帖，这样最好。

**Comment by TitusL** [comment]
X好像整了个任务，不知道有没有人在做。
问题：最近老是有人来发垃圾帖子。方案：使用github apihttps://developer.github.com/v3/issues/巡查新开的issues，发现关键词，自动关闭这里有一个例子，是关闭过期的讨论的：https://github.com/bstriner/github-bot-close-inactive-issues任务说明：难度: 2星技能需求： python把代码调试好了，我来部署
--

**Comment by nbwxbo** [comment]
毫无意义的。看历史，谁上台都一路货色。没上台前，忽悠他人卖命。

**Comment by YannKing** [comment]
发那个东西的人其实很搞笑，他以为咱们这些人会跟他有一样的想法才搞梯子。而事实是我们这些人都是出于对知识的探求。本就不是一个层级，还偏偏跑到这里来秀下限。真是笑死人。哈哈哈。可怜科知识改变了生活，却修不好脑子。

**Comment by feelsfreeman** [comment]
我对那人发表的内容不做评论.但是,看了这些评论,我有几点想说.

## 首先
就算没人发,党也会给这类工具扣一顶"提供侵入、非法控制计算机信息系统的程序、工具罪"的帽子.
> [提供侵入、非法控制计算机信息系统的程序、工具罪 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E6%8F%90%E4%BE%9B%E4%BE%B5%E5%85%A5%E3%80%81%E9%9D%9E%E6%B3%95%E6%8E%A7%E5%88%B6%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%BF%A1%E6%81%AF%E7%B3%BB%E7%BB%9F%E7%9A%84%E7%A8%8B%E5%BA%8F%E3%80%81%E5%B7%A5%E5%85%B7%E7%BD%AA)

## 其次
别逗了,你以为你在党的心中是良民???
别以为是因为你不访问敏感内容才能翻墙!
别以为你现在能访问一些网站是"党"的恩赐!
你在党的心中,和普通的需要维稳的对象没有任何区别!

因为,不同于国内的各种论坛,通信工具,例如QQ,微信.
你现在已经有能力知道党所禁止的东西了,同时党不能再审查你的通讯内容了.

如果有一天可以申请"良民证"了.
那么,你所访问的所有内容,就和现在的局域网一样,党都必须知道!
一旦访问了某些内容,或者发表了某些内容.可能就是喝喝茶,写写汇报,或者拘留,甚至用刑.

## 最后
翻墙是一场较量.
别以为短暂的胜利是对手的仁慈.

党的目的从来没有改变.
> "伟大的导师,伟大的领袖,伟大的统帅,伟大的舵手X主席万岁!万岁!万万岁!"


## 其它
欲加之罪何患无辞!
> [生产销售“翻墙”路由器属于违法行为！一名网络工程师被判刑！ - YouTube](https://www.youtube.com/watch?v=chgwpzaSOZI&t=360)
