### ISSUE TITLE
我按照教程开启了ipv6。GAEProxy状态信息显示：您应该考虑开启IP扫描器？？？？？

### ISSUE THREAD

**Issue by panjinhua** [XX-net/XX-Net#7980]
但是好像没什么用啊
日志是显示了如下的东东：

Nov 03 22:19:24.664 - [DEBUG] ip:2a00:1450:400a:4::13 real fail
Nov 03 22:19:24.664 - [DEBUG] ip:2a00:1450:400a:4::11 real fail
Nov 03 22:19:24.664 - [DEBUG] ip:2a00:1450:400a:4::10 real fail
Nov 03 22:19:24.665 - [DEBUG] ip:2a00:1450:400a:4::17 real fail
Nov 03 22:19:24.675 - [DEBUG] ip:2a00:1450:400a:4::16 real fail
Nov 03 22:19:24.715 - [DEBUG] ip:2607:f8b0:4007:4::8 real fail
Nov 03 22:19:24.717 - [DEBUG] ip:2800:3f0:4001:4::8 real fail
Nov 03 22:19:24.717 - [DEBUG] ip:2800:3f0:4001:4::9 real fail
Nov 03 22:19:28.701 - [DEBUG] create ssl timeout fail.
Nov 03 22:19:28.740 - [WARNING] no enough ip
Nov 03 22:19:30.253 - [WARNING] no enough ip
Nov 03 22:19:31.318 - [WARNING] no enough ip
Nov 03 22:19:31.627 - [INFO] PAC from:127.0.0.1:50043 GET /proxy.pac
Nov 03 22:19:32.388 - [WARNING] no enough ip
Nov 03 22:20:28.725 - [DEBUG] create ssl timeout fail.
Nov 03 22:20:28.767 - [WARNING] no enough ip
Nov 03 22:20:30.257 - [WARNING] no enough ip
Nov 03 22:20:31.276 - [WARNING] no enough ip
Nov 03 22:20:32.347 - [WARNING] no enough ip
Nov 03 22:20:33.407 - [WARNING] no enough ip
Nov 03 22:20:34.470 - [WARNING] no enough ip
Nov 03 22:20:34.701 - [INFO] PAC from:127.0.0.1:50326 GET /proxy.pac
Nov 03 22:20:35.490 - [WARNING] no enough ip
Nov 03 22:20:36.531 - [WARNING] no enough ip
Nov 03 22:20:37.596 - [WARNING] no enough ip
Nov 03 22:20:38.629 - [WARNING] no enough ip

我改怎么办啊？急死了。。。。。。。。。。。

**Comment by TitusL** [comment]
检查下 Teredo适配器开启了没有?
以管理员权限打开命令输入以下，重新启用
netsh interface teredo set state default
netsh interface Teredo set state type=default
