### ISSUE TITLE
休眠唤醒后要重启都能翻

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#7987]
每天下班时盖上笔记本的上盖，第二天再来时就尚未建立连接，重启xx不管用；要重启电脑才行。
昨晚下班时想起这件事，直接关机回家了。今早来了开机后，尚未建立连接；重启电脑又ok。
这是啥情况？！

**Comment by TitusL** [comment]
可以参考我的问题。
https://github.com/XX-net/XX-Net/issues/7962
主要是因为IPV6的隧道适配器 Teredo Tunneling Pseudo-Interface，没有启用。
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"

将上面的命令存成BAT批处理文件，管理员权限运行一下，就好了。

**Comment by nly4lov** [comment]
@TitusL 下次再这样子的时候我马上去看你的帖子，看是不是这个原因

**Comment by hzx505** [comment]
断网再开也可以，但维持不久，不要重复断、开

**Comment by nly4lov** [comment]
@TitusL 已验证不管用，不重启就无法连接

> netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"
> 
> 将上面的命令存成BAT批处理文件，管理员权限运行一下，就好了。

**Comment by nly4lov** [comment]
升级到3.7.15后，该症状消失了。
