### ISSUE TITLE
bug?   1.3.6 IP	 为4000 不扫描

### ISSUE THREAD

**Issue by newcastlecy** [XX-net/XX-Net#80]
XX-Net Version 1.3.6  win8
Google IP	 为4000的时候 ，就不会扫描了。刷选也不做了，有些失效的ip也不会剔除

**Comment by lg560852** [comment]
XX-Net\goagent\3.1.40\local\proxy.ini

[google_ip]
max_check_ip_thread_num = 20
max_good_ip_num = 12000
ip_connect_interval = 5

**Comment by xxnet** [comment]
新版已经修复。
最多保留3000个ip，有多的ip，删除最慢的ip
