### ISSUE TITLE
最近在搞OPENWRT  这东西太给力了，XX-NET能布署到OP上面吗？

### ISSUE THREAD

**Issue by hehh2001** [XX-net/XX-Net#800]
建议老大开发OPENWRT版，自动升级自动找IP

**Comment by wangxj-nemo** [comment]
openwrt适合shadowsocks和VPS

**Comment by xxnet** [comment]
不推荐，虽然可以这么干。前面有人试过，可以做到。

主要需要解决证书问题，其次是内存占用问题，自动升级和和自动找ip都已经有了

2015-08-12 15:56 GMT+08:00 Nemo <notifications@github.com>:
