### ISSUE TITLE
王岐山又在百度新闻上，公开支持一党独，裁，反对多，党竞争、三，权分立。这只巨贪老狗，怎么还不死！﻿阻碍中国民，主化的盗，国，贼，将遭到14亿人民的唾弃！

### ISSUE THREAD

**Issue by Hkfjklxc** [XX-net/XX-Net#8015]
让我们这些小蜡烛一起努力，点亮一个光明的中国！

**Comment by Forrk** [comment]
这些人是怎么趁虚而入的...没人来管一下吗？

**Comment by Zmm1977** [comment]
![image](https://user-images.githubusercontent.com/27794050/32404922-b3531bfc-c195-11e7-8eb4-9829ac513a0f.png)

**Comment by GoodSake** [comment]
github是自由的，谁都可以发帖。
