### ISSUE TITLE
运行不错 一直再涨IP

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#8016]
可以了 
XX-Net 3.7.7，一切正常，你可以访问真正的互联网了。
属性 | 值
-- | --
本地网络状态 | OK
IP数量 | 65
空闲 | 0
IP延迟 | 342
连接池(帮助) | 新:0 h1:65 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 0
屏蔽状态(帮助) | OK

属性 | 值
-- | --
监听代理 | 127.0.0.1:8087
PAC自动代理地址 | http://127.0.0.1:8086/proxy.pac
IPv6 | 启用

**Comment by wuyibin** [comment]
电脑好用！！         手机有什么呢！！！！@

**Comment by xiaoteai** [comment]
蓝   灯

**Comment by jooloog** [comment]
把ip拿出来用用

**Comment by sundaqing1969** [comment]
![16](https://user-images.githubusercontent.com/13601611/32411318-b7dc4a5e-c212-11e7-8de9-7a64c82106bb.gif)

**Comment by xiaoteai** [comment]
一百多IP能用  地区不一样

**Comment by goncha** [comment]
一定要走IPv6吗？

**Comment by xiaoteai** [comment]
目前   数这个 可靠 稳定   慢慢来 仔细 打开IPV6 设置的每个步骤  祝你成功
