### ISSUE TITLE
3.7.8是不是出问题了？

### ISSUE THREAD

**Issue by CodeTrainerMan** [XX-net/XX-Net#8017]
现在打开直接未建立连接什么意思

**Comment by dahai058** [comment]
我这里显示 请等待两小时xx-net需要扫描IP

**Comment by KAQSICE** [comment]
@dahai058 两小时+1

**Comment by TitusL** [comment]
可以参考我的问题。
#7962
主要是因为IPV6的隧道适配器 Teredo Tunneling Pseudo-Interface，没有启用。
netsh int ipv6 add route ::/0 "Teredo Tunneling Pseudo-Interface"

将上面的命令存成BAT批处理文件，管理员权限运行一下，就好了。
