### ISSUE TITLE
为什么我的cmd中ipconfig /all没有Teredo Tunneling Pseudo-Interface这一项？

### ISSUE THREAD

**Issue by Easefeel** [XX-net/XX-Net#8022]
在开启ipv6的过程中，为什么我的cmd中ipconfig /all找不到Teredo Tunneling Pseudo-Interface这一项？
我又输入了netsh int teredo show state，显示：
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

好苦恼，因为ipv6这个问题一直不会解决已经1个月用不了xxnet了...
求好心人帮忙解答...

**Comment by Easefeel** [comment]
目前问题已解决，方法是在注册表中把禁用teredo服务的数值调成0

**Comment by xiakejie** [comment]
在注册表中把禁用teredo服务的数值调成0  改成0之后呢。我改了还是  状态还一直是offline

**Comment by xiakejie** [comment]
嗯嗯，重启一下就好了
