### ISSUE TITLE
给开发者的一点拙见，谢谢！

### ISSUE THREAD

**Issue by huashang2014** [XX-net/XX-Net#8027]
墙升级了！最近看到您们辛苦劳作，首先表示感谢！从plus lu的goagent开始用的现在的xx-net一直不错，也很爱惜这个软件.
     看到最近墙厚了，我这个免费用户也就不好用了，IVP6也开了，3.7.9最新版看油管断流，3.6.15也是如此！当然免费用户也不要强求太多，至少480p不断流可以吧！，我也不是因为免费用户就不管不问，这不昨天刚发的帖子：
https://github.com/XX-net/XX-Net/issues/8003
众人拾柴火焰高！我建议开发上在开发的时候兼顾一下免费用户，就像杀毒avast一样！avast是通过免费版来聚人气！还有主要是收集病毒库，这个与xx-net一样。用得多了自然就会得到大家不同的体验，从而提升软件的实用性！只要大家齐心才能共同维护！谢谢！

**Comment by jinke159** [comment]
你在说啥？？？

**Comment by foxerfly** [comment]
建议免费用的别提要求

**Comment by xiaoas** [comment]
真的是有趣 凭什么免费用的就不能提要求？XX-net说的？
他是说了“我要用X-tunnel自己赚钱了 免费的你们就自生自灭吧 我不维护了”？

**Comment by zanewayne78** [comment]
看视频流量大用ss吧，日常搜索网页需求免费够用了，不断流要不断投入**高质量服务器**，免费项目哪来的钱去搞？而付费有其他替代方案

**Comment by huashang2014** [comment]
对不起，没休息好，有几个错别字，不过大致的意思大家也能看懂！，我是衷心希望，软件越办越好！

**Comment by onplus** [comment]
软件名字都错了。

逻辑不清，建议整理一下

**Comment by dagerdager** [comment]
GAE没法用 你认为是作者不作为？

**Comment by RomanSmile** [comment]
无论是免费还是付费xx-net都会一视同仁，
x隧道有时候也不见得比gae快，只是两个模块，gae走的是google家，作者xx-net没有收一分钱，
x隧道人家自己不花钱维护啊，墙是高了，xx-net也在努力升级，他已经把TSL1.3作为目标，但是这需要很大的精力来融合各个系统，这是需要一定时间的，希望大家耐心点等等，会好的！

**Comment by SeaHOH** [comment]
如果只是搜资料，那么每天登录 X-Tunnel 时，X 大都有送少量当日流量。
这个是由 X 大和付费用户共同购买的，保证普通用户不被墙围住就是积大德了，当然不要指望这看多少视频。

**Comment by touchmouse** [comment]
”免费“的慢了是因为ipv4的ip多数被封了，花多少精力也不可能恢复到之前的样子，这是工作原理决定的。ipv6如果不是原生还要走隧道，速度也不可能赶上ipv4的直接连接谷歌服务器。

所谓“免费”的条件是有人出于兴趣做出goagent或xx-net，再加上google的提供的免费服务。现在免费的路窄了，想快就花费点找条高速路。
xx-net已经维护的很棒了，免费想快回来很难了。

**Comment by hzx505** [comment]
@huashang2014 
中听

**Comment by huashang2014** [comment]
dagerdager: GAE没法用 你认为是作者不作为？

你这话什么意思？我说这些是为大家更好的用软件

**Comment by huashang2014** [comment]
dagerdager：GAE没法用 你认为是作者不作为？

我看看我写的再说话！谁不知plus lu做的已经很好了！
