### ISSUE TITLE
我的两台电脑在同一个路由器下（一个有线一个无线），有线的能翻，无线的翻不了。

### ISSUE THREAD

**Issue by ArchNew** [XX-net/XX-Net#8032]
我有两台电脑，一台是台式机，一台是笔电。台式机是通过网线接到路由器，能正常翻墙。但笔电通过wifi连接，就无法翻墙。这是这刚出现的问题，以前一直能翻

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.7.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。
Nov 05 18:34:12.435 - [WARNING] no enough ip
Nov 05 18:34:46.378 - [DEBUG] POST http://www.twitter.com/xxnet
Nov 05 18:34:46.488 - [DEBUG] POST http://www.twitter.com/xxnet
Nov 05 18:35:07.939 - [DEBUG] create ssl timeout fail.
Nov 05 18:35:07.940 - [WARNING] no enough ip
Nov 05 18:35:08.441 - [WARNING] no enough ip
Nov 05 18:35:08.734 - [DEBUG] GAE GET https://www.google.com/_/chrome/newtab-serviceworker.js
Nov 05 18:35:08.942 - [WARNING] no enough ip
Nov 05 18:35:09.444 - [WARNING] no enough ip
Nov 05 18:35:09.946 - [WARNING] no enough ip
Nov 05 18:35:10.447 - [WARNING] no enough ip
Nov 05 18:35:10.948 - [WARNING] no enough ip
Nov 05 18:35:11.450 - [WARNING] no enough ip
Nov 05 18:35:11.951 - [WARNING] no enough ip
Nov 05 18:35:12.453 - [WARNING] no enough ip

**Comment by ArchNew** [comment]
问题解决！解决方法：把能翻墙的那台电脑上xx-net的data文件夹复制到不能翻的那台上。当然，不能翻的那台，先要把软件关了，然后删除data文件夹。

**Comment by ylwszb** [comment]
gws-ip-num: total:0 good:0
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999

IP数都没了，连接池数也没了，扫描线程是0，延迟9999，这样的状态怎么能连接？

ipv6-status: 1

既然开了IPV6不应该是这样的，建议查一下Teredo隧道运行状态，是否稳定。
