### ISSUE TITLE
XX-Net bug 反馈, 3.7.8, 无网络时高cpu占用率

### ISSUE THREAD

**Issue by outofmemo** [XX-net/XX-Net#8041]
XX-Net 版本3.7.8 无网络连接时XX-Net cpu占用率过高(占满了一个cpu线程).下面是部分gae日志:

>Nov 05 22:24:38.970 - [DEBUG] connect 2607:f8b0:4004:21::19 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.971 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.971 - [DEBUG] connect 2607:f8b0:4002:13::11 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.971 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.972 - [DEBUG] connect 2a00:1450:4011:24::11 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.972 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.972 - [DEBUG] connect 2a00:1450:401c:20::e fail:[Errno 10065] cost:2 h:0
>Nov 05 22:24:38.973 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.974 - [DEBUG] connect 2800:3f0:4001:4::9 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.974 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.974 - [DEBUG] connect 2607:f8b0:4008:20::8 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.974 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.976 - [DEBUG] connect 2a00:1450:401c:a::e fail:[Errno 10065] cost:5 h:0
>Nov 05 22:24:38.976 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.977 - [DEBUG] connect 2a00:1450:4014:8::18 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.977 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.977 - [DEBUG] connect 2a00:1450:400f:a::11 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.977 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.978 - [DEBUG] connect 2607:f8b0:4016:10::f fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.978 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.979 - [DEBUG] connect 2a00:1450:4002:19::e fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.979 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.979 - [DEBUG] connect 2a00:1450:401c:1e::f fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.979 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.979 - [DEBUG] connect 2607:f8b0:4016::15 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.980 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.980 - [DEBUG] connect 2800:3f0:4001:15::10 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.980 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.980 - [DEBUG] connect 2607:f8b0:4004:25::b fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.981 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.982 - [DEBUG] connect 2607:f8b0:4016:13::10 fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.982 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.982 - [DEBUG] connect 2a00:1450:400e:8::c fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.982 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.983 - [DEBUG] connect 2a00:1450:401e:39::c fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.984 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.985 - [DEBUG] connect 2607:f8b0:4012:9::c fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.985 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.985 - [DEBUG] connect 2a00:1450:401c:f::c fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.985 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.986 - [DEBUG] connect 2a00:1450:400f:a::d fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.986 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.987 - [DEBUG] connect 2a00:1450:400e:48::11 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.987 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.987 - [DEBUG] connect 2607:f8b0:4004:f::9 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.987 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.987 - [DEBUG] connect 2a00:1450:4014:4::c fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.988 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.988 - [DEBUG] connect 2a00:1450:4014:7::6 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.989 - [DEBUG] connect 2607:f8b0:4004:2b::c fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.989 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.989 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.991 - [DEBUG] connect 2a00:1450:401c:9::f fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.991 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.991 - [DEBUG] connect 2800:3f0:4001:12::15 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.991 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.992 - [DEBUG] connect 2607:f8b0:4004:e::b fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.993 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.993 - [DEBUG] connect 2607:f8b0:4012:1::6 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.994 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.994 - [DEBUG] connect 2607:f8b0:4004:27::7 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.994 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.994 - [DEBUG] connect 2a00:1450:400f:3::14 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.995 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.996 - [DEBUG] connect 2607:f8b0:4016:b::16 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.996 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.996 - [DEBUG] connect 2800:3f0:4001:15::14 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.996 - [DEBUG] connect 2607:f8b0:4012:c::13 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.997 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.997 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.997 - [DEBUG] connect 2a00:1450:4014:a::16 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.997 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.997 - [DEBUG] connect 2607:f8b0:4017:4::15 fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.997 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.999 - [DEBUG] connect 2a00:1450:4011:1b::18 fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:38.999 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:38.999 - [DEBUG] connect 2a00:1450:400d:a::e fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:38.999 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.000 - [DEBUG] connect 2607:f8b0:4002:35::b fail:[Errno 10065] cost:3 h:0
>Nov 05 22:24:39.000 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.002 - [DEBUG] connect 2a00:1450:400d:b::c fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:39.002 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.003 - [DEBUG] connect 2a00:1450:400d:d::13 fail:[Errno 10065] cost:5 h:0
>Nov 05 22:24:39.003 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.004 - [DEBUG] connect 2607:f8b0:4017:4::17 fail:[Errno 10065] cost:4 h:0
>Nov 05 22:24:39.005 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.005 - [DEBUG] connect 2607:f8b0:4002:f::15 fail:[Errno 10065] cost:5 h:0
>Nov 05 22:24:39.007 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.014 - [DEBUG] connect 2607:f8b0:4017:3::8 fail:[Errno 10065] cost:12 h:0
>Nov 05 22:24:39.014 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.015 - [DEBUG] connect 2a00:1450:4011:35::16 fail:[Errno 10065] cost:13 h:0
>Nov 05 22:24:39.015 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.016 - [DEBUG] connect 2a00:1450:400f:3::c fail:[Errno 10065] cost:13 h:0
>Nov 05 22:24:39.018 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.024 - [DEBUG] connect 2607:f8b0:4002:22::a fail:[Errno 10065] cost:23 h:0
>Nov 05 22:24:39.025 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.027 - [DEBUG] connect 2a00:1450:400d:9::19 fail:[Errno 10065] cost:20 h:0
>Nov 05 22:24:39.029 - [DEBUG] connect 2404:6800:400c:15::19 fail:[Errno 10065] cost:25 h:0
>Nov 05 22:24:39.030 - [DEBUG] report_connect_fail network fail
>Nov 05 22:24:39.031 - [DEBUG] report_connect_fail network fail

似乎是因为gae仍然在不断尝试连接,XX-Net 状态信息:

>XX-Net Status:
>
>sys-platform: AMD64, Windows-7-6.1.7601-SP1
>os-system: Windows
>os-version: 6.1.7601
>os-release: 7
>os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
>architecture: 32bit,WindowsPE
>browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
>xxnet-version: 3.7.8
>python-version: 2.7.13
>openssl-version: 16.0.0 TLSv1_2 h2:alpn
>
>ipv6-status: 1
>gws-ip-num: total:12347 good:4318
>network-status: unknown
>connected-link: new:0 used:0
>worker: h1:0 h2:0
>scan-ip-thread-num: 0
>ip-quality: 263
>is-idle: 0
>block-stat: OK
>proxy_state: OK
>ca_state: OK
>Appid_Working: true
>Appids_Out_Of_Quota: false
>Appids_Not_Exist: false
>Using_Public_Appid: false

**Comment by jiutianzhiyu** [comment]
在无网络连接下出现该问题，cup占用疯涨。同样问题也会出现在锁屏后，吃饭半小时回来发现cpu占用居高不下。

**Comment by ylwszb** [comment]
扫描线程数是否更改过？

使用的代理方式是什么？
测试中发现，使用PAC比GAE消耗的系统资源更多，当电脑硬件水平比较低时更为突出。

建议，备份3.7.8版本，升级到3.7.9版本试试

**Comment by ylwszb** [comment]
建议，改用GAE或X-T代理方式

**Comment by outofmemo** [comment]
@ylwszb 最大扫描线程改过(12)，代理方式:空闲(没有代理请求) ，暂未使用3.7.9  使用过的朋友可以反馈一下

**Comment by ylwszb** [comment]
扫描线程改过还算适宜，
代理有三种，GAE，X-T，PAC，你现在选用的是哪个？
不建议使用PAC代理方式

**Comment by outofmemo** [comment]
浏览器没有打开任何页面(毕竟网络连接都没有)，与浏览器代理设置无关。gae  x-tunnel 模块均开启

**Comment by ylwszb** [comment]
还是升级到3.7.9版本试试吧
