### ISSUE TITLE
关于X-Tunnel付费的问题

### ISSUE THREAD

**Issue by heracleshebe147** [XX-net/XX-Net#8057]
开始使用X-Tunnel付费，要求用Paypal支付，可竟然要填写身份证号码，居住地址，手机号之类的个人信息，用这个软件的人费半天劲不就是要逃脱墙的控制吗，这下可好，都暴露了，那用支付宝或者微信又有什么不行
还是说用Paypal是为了它自己财务安全？

**Comment by GoodSake** [comment]
个人信息本来就是公开的呀，不然怎么让别人认识你呢。
用XX-net是为了上youtube,twitter,google的。
Paypal是为了支付美金，港币。
支付宝或微信能付美元账单吗？

**Comment by walterclozet** [comment]
我记得paypal以前是不需要这些东西的呀? 这世道变了?

**Comment by onplus** [comment]
PayPal还不放心的话，，，

你有比特币也行

**Comment by theratlesnake** [comment]
其实paypal是付款给X大，在外人看来就是一起正常的转账啊，这没什么好怕的吧？
