### ISSUE TITLE
Mac 安装miredo不成功

### ISSUE THREAD

**Issue by eljake58** [XX-net/XX-Net#8068]
系统是10.12.6，提示不兼容

**Comment by W-quan** [comment]
文档里关于Mac的应该是过时的

**Comment by TitusL** [comment]
![2017-11-07 1 29 01](https://user-images.githubusercontent.com/33217849/32454740-142a69f0-c35b-11e7-95fd-9125fa84dc0a.png)

**Comment by gothion** [comment]
@TitusL 麻烦分享下安装方法，非常感谢

**Comment by eljake58** [comment]
@TitusL  我也是一样版本啊，安装不成功

**Comment by eljake58** [comment]
哪个大侠指导一下啊，谢谢
