### ISSUE TITLE
Mac最新系统10.13.1打开程序失败

### ISSUE THREAD

**Issue by qhxzgl2006** [XX-net/XX-Net#8071]
/Users/chrisleon/Downloads/XX-Net-3.7.8/start ; exit;
XX-Net version:default
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

打开后显示如上内容。

**Comment by TitusL** [comment]
![2017-11-07 1 38 58](https://user-images.githubusercontent.com/33217849/32455196-797f64ee-c35c-11e7-81ac-824dad0a37ba.png)

**Comment by wanggggggg** [comment]
能否说一下步骤 安装步骤和链接

**Comment by TitusL** [comment]
双击运行start.而且浏览器最好用chrome，运行完，xx-net文件夹里就有SwitchyOmega，装插件，还原插件备份，选GAE-PROXY自动切换，应该就行了。
对了前提你mac是要开ipv6,
请参考：#8045

**Comment by TitusL** [comment]
![2017-11-07 1 48 40](https://user-images.githubusercontent.com/33217849/32455840-73fb51e8-c35e-11e7-9803-4f650e8e1549.png)

![2017-11-07 1 51 00](https://user-images.githubusercontent.com/33217849/32455818-66bac216-c35e-11e7-9adb-aa2cc39faeb5.png)

**Comment by jacksu** [comment]
mac os 新版本好像现在无解

**Comment by littlen9ne** [comment]
我也是，刚打开的时候X-TUNNEL可以用的，过一会儿程序就挂掉了。。

**Comment by qhxzgl2006** [comment]
我的解决了。原来是因为我的网络设置勾选了代理，坑。
