### ISSUE TITLE
不管哪个版本，连接池全部显示0，无法建立连接，求大神看一下

### ISSUE THREAD

**Issue by LGFUmrym** [XX-net/XX-Net#8074]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.7.8
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12347 good:12338
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: [true[](url)]

**Comment by ylwszb** [comment]
ipv6-status: 1
gws-ip-num: total:12347 good:12338
network-status: OK
ip-quality: 300

看这个没发现什么问题

proxy_state: Fail
ca_state: Fail

代理和证书是不是有问题？

**Comment by LGFUmrym** [comment]
谢谢您的回答！
代理和证书，我设置全局代理就会OK
我在其他问题里看见别人说连接池必须有一个不为0，才可以连接成功，我这边三个全部是0
还有IP数量，一万多，也不正常
但是我找不到解决的方法，网站上面的帮助也没有看懂，您看看

如下：
GoAgent 连接状态
状态页面上的connected link，表示已建立的有效连接数。
 目前有两个数字，解释如下：
•google 服务器在建立ssl握手之后，允许保持240秒。
•一个ssl一旦使用来访问某个host，就不能更换其他host

因此建立了2个重要的连接池：
•未用过的ssl连接池
•通用的gae连接池

规则如下：
•gae连接可以循环使用，只要使用过程没有出现异常。
•未用过的连接池，可以在需要时，被gae连接使用，也可以被Direct模式使用，即Host为www.googleapi.com之类的网站。

只要这两个连接池有可用连接，即可正常使用。

**Comment by ylwszb** [comment]
![2](https://user-images.githubusercontent.com/19790792/32479246-d87dfae8-c3c3-11e7-868f-54f030761de1.jpg)

我这也1万多IP，现在链接也比较正常，如果感觉不正常可以“检查所有IP”。

**Comment by ylwszb** [comment]
有时我的XX连接池也都是0，没关系，只要浏览器挂上代理上网，连接池就会有变化。

**Comment by LGFUmrym** [comment]
好吧，我再试试，要是不行再问你

**Comment by LGFUmrym** [comment]
还是不行啊

**Comment by LGFUmrym** [comment]
问题解决了，连接池数量为0的，一直无法建立连接，其他都没有问题的朋友（已经打开ipv6，显示启用），通过以下步骤解决：
1. 打开ipv6检测网址，http://test-ipv6.com/index.html.zh_CN，若测试项目”不使用域名的ipv6测试“不成功，那么请进行以下步骤
2. 打开 https://github.com/XX-net/XX-Net/wiki/IPv6-Win10，按照步骤操作
注意输入完命令以后点击enter，一次操作不成功请多次操作
3. GAEProxy状态信息始终显示 尚未建立连接
https://github.com/XX-net/XX-Net/issues/8063（类似的一个问题作为参考）

**Comment by JingyaoZhang** [comment]
我按https://github.com/XX-net/XX-Net/wiki/IPv6-Win10里的步骤操作后重启电脑是可以检测到ipv6成功的，也可以用xxnet。但是，我工作了一天后并不是关闭电脑而是将电脑休眠的，第二天唤醒后测试ipv6是失败的。需要再重新启动系统才可以重新连接上ipv6.请问这种情况怎么解决？如何让电脑休眼唤醒后自动连接上ipv6?
