### ISSUE TITLE
川'普：独'裁'者不应低'估美'国的决'心！徐'文'立：習'近'平是中'華'民'族的敗'家子！習'近'平是獨'裁'竊'國'賊-兼談習'初'心和崩'盤！習'近'平先生致'命的七'寸可能在哪裡？習'近'平五年來，有一點點自'由'民'主和憲'政的影'子嗎？！香/港的普/選呢？！

### ISSUE THREAD

**Issue by tyjxcbg** [XX-net/XX-Net#8079]
川；普：独；裁；者不应低估美；国的决心！ https://www.voachinese.com/a/trump-japan-20171105/4101759.html
徐；文；立：習；近；平是中；華；民；族的敗；家；子 http://enewstree.com/discuz/forum.php?mod=viewthread&tid=180152&extra=
徐【文【立:習【近【平是獨【裁【竊【國【賊-兼【談習【初心和崩【盤 http://www.duping.net/XHC/show.php?bbs=11&post=1394603
徐【文【立：習【近【平先生致【命的七【寸可能在哪裡？ http://enewstree.com/discuz/forum.php?mod=viewthread&tid=180119&extra=
徐【文【立 Twitter： https://twitter.com/xu_wenli
完整版： https://github.com/getlantern/forum/issues/6616

**Comment by sakuratyan** [comment]
喵喵喵
