### ISSUE TITLE
找不到IP,显示：您应该考虑开启 IP 扫描器。

### ISSUE THREAD

**Issue by hacky2015** [XX-net/XX-Net#8088]
版本3.7.9, IPV6已打开，上周还一切正常，这周就不行了，显示：您应该考虑开启 IP 扫描器。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.7.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:0 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by scljy** [comment]
我的也出现了这种状况

**Comment by scljy** [comment]
过了几分钟又对了

**Comment by hacky2015** [comment]
升级成3.7.10，有正常了。
