### ISSUE TITLE
最近在使用时，看YouTube有一点小问题

### ISSUE THREAD

**Issue by daerdai** [XX-net/XX-Net#81]
就是打开一个新的视频时，刚开始缓冲很慢！一卡一卡的，但是，过一会网速又一下提升好多，
720p无压力。还有时会断流，不再继续缓冲，不过刷新一下页面又可以缓冲了！
      请作者检查一下代码，是不是有什么地方需要优化！！

**Comment by xxnet** [comment]
谢谢反馈，这个是存在的，有改进的空间，再过两周吧，谢谢。

在 2015年3月28日 上午12:16，daerdai <notifications@github.com>写道：

**Comment by lyp4140** [comment]
我的也出现这种问题
