### ISSUE TITLE
ipv6配置问题

### ISSUE THREAD

**Issue by wozaitianwai** [XX-net/XX-Net#8120]
执行netsh int ipv6 add route ::/0 "有效的Teredo接口名称"
为啥现总是说语法错误- - ，接口名什么都查好了没问题啊

**Comment by feimeng2017** [comment]
[ipv6.7z.zip](https://github.com/XX-net/XX-Net/files/1452665/ipv6.7z.zip)

**Comment by feimeng2017** [comment]
试下这个批处理吧  我用的这个 (但是重启之后就失效,需要重新运行一下)  好像这个问题没有一个标准的操作方法  我也试过其他的 没用 就这个有作用

**Comment by zhmars** [comment]
请问这是哪里来的命令，有试过 wiki 吗？

https://github.com/XX-net/XX-Net/wiki/如何开启IPv6

**Comment by turbo5code** [comment]
端口名称在哪里看啊  我找不到 麻烦大佬教一下
