### ISSUE TITLE
请问如何解决推特无法搜索的问题

### ISSUE THREAD

**Issue by mengmengniao** [XX-net/XX-Net#8122]
问题：大概是因为推特限流的机制，用谷歌代理的地址太多人上了。导致搜索任何内容都被限制无法显示，只可以搜索用户名。
有没有大神解决这个问题呢？使用其他工具都不会被推特限流。只有XXnet会出现这样的问题。
3.6.x版本开始有这样的问题,求解决方案，谢谢！

**Comment by xxnet** [comment]
​用 x-tunnel

**Comment by mengmengniao** [comment]
​用 x-tunnel就不是自己工作的APPid了吧，走的不是谷歌，如果没有办法避规可以close了。谢谢回复

**Comment by mengmengniao** [comment]
SwitchyOmega插件设置了twitter用x-tunnel规则，暂时只能这样了
