### ISSUE TITLE
3.7.12 网络无法连接，请检查网络和防火墙设置

### ISSUE THREAD

**Issue by deximy** [XX-net/XX-Net#8135]
XX-Net Status:

sys-platform: armv8l, Linux-3.18.31-perf-g2d2384f-armv8l-with
os-system: Linux
os-version: #1 SMP PREEMPT Mon Nov 6 00:41:50 WIB 2017
os-release: 3.18.31-perf-g2d2384f
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36
xxnet-version: 3.7.12
python-version: 2.7.2
openssl-version: 0.14 TLSv1_2 h2:no
ipv6-tunnel: Developing
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: Fail
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

GAEProxy日志

Nov 08 19:32:00.902 - [INFO] SSL use version:TLSv1_2
Nov 08 19:32:00.903 - [WARNING] network IPv6 fail
Nov 08 19:32:00.905 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
Nov 08 19:32:00.910 - [INFO] load ip range file:/sdcard/XX-Net/code/3.7.12/gae_proxy/local/ip_range.txt
Nov 08 19:32:01.076 - [WARNING] network IPv4 fail
Nov 08 19:32:01.151 - [INFO] load google ip_list num:0, gws num:0
Nov 08 19:32:01.182 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
Nov 08 19:32:01.184 - [WARNING] no enough ip
Nov 08 19:32:01.205 - [DEBUG] ## GAEProxy set keep_running: True

**Comment by xxnet** [comment]
​墙内能连吗？

**Comment by deximy** [comment]
可以，这段issue就是直接连接发的

**Comment by xxnet** [comment]
​你这是Android 红米Note
在高级里，把IPv6 改为auto吧。

手机上IPv6还很少有成功的

**Comment by deximy** [comment]
开启auto后ipv4显示ok，但一直扫不到ip，这里ipv4封锁比较严重，电脑上ipv4也不行

**Comment by xxnet** [comment]
​手机上用x-tunnel，没有证书问题

**Comment by dahai058** [comment]
昨晚升级到3.7.12 ipv4不行，今早重启电脑可以用了。ip从2个涨到现在139个。万分感谢X神
