### ISSUE TITLE
求助，win10无法打开ipv6

### ISSUE THREAD

**Issue by 990753707** [XX-net/XX-Net#8153]
家里的电脑是win7，按照wiki里的方法能正常打开ipv6，可以正常使用xx-net。公司里的电脑是win10，按照wiki里的方法第一次可以正常开启，后来就不行了，重复几次也没用。求助，如何处理。。。

**Comment by DipperTheCoder** [comment]
这个问题我折腾两个月了，至今仍然没解决，跟你情况比较类似，现在有很多教程，但都是参考，要不然我早解决了。

**Comment by wengzeyu19911231** [comment]
https://support.microsoft.com/zh-cn/help/929852/how-to-disable-ipv6-or-its-components-in-windows
我用的第二排的第4个，检查一遍问题 修复重启就好了，不知道你有没有用。也是网上各种方法用了个遍，就这个成功了

**Comment by gjbg1989** [comment]
32位win7、win10可用3.7.11版并开启IPV6：解压包内的enable_ipv6.bat

**Comment by 990753707** [comment]
结贴，按照wengzeyu19911231的方法搞定了，还有@gjbg1989 没有附件。。同时谢谢诸位。
