### ISSUE TITLE
朋友用xx下载谷歌adwords表格时显示“该网页无法正常运作”

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#8180]
具体如图，判断不是她电脑的问题（电脑是我新给装的10系统），换了我电脑也是一样的下场。
这是啥情况呢？她FQ主要就是为了下载这种表格。
![_20171109172222](https://user-images.githubusercontent.com/11325411/32597745-9532b3c2-c572-11e7-9196-ecd194949976.jpg)

**Comment by gjbg1989** [comment]
貌似没有万能的代理。。。

**Comment by xxnet** [comment]
​用x-tunnel 试试，GAE 代理有时有兼容性问题

**Comment by nly4lov** [comment]
@xxnet 这个“有时”我认为是非常正确的。前段时间，19D以前，还可以正常用xx的时候，我是可以下载这个的；现在我也不能了。
X-tunnel应该无法尝试，我也想到了，不过她没有流量

**Comment by gjbg1989** [comment]
以前正常，或许等下也会变正常；注册X-tunnel即有免费流量

**Comment by nly4lov** [comment]
以前是的。还有个网友转了不少流量给我，可我一直没用上

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 启用 X_tunnel

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 模块管理-启用 X_tunnel

**Comment by nly4lov** [comment]
@gjbg1989 我有启用啊。一直就有，刚刚又试了，桌面右下角xx设置为全局通过x-tunnel代理，xx-net web界面登陆x-tunnel，下载那个excel仍然是
This page isn’t working

00e9e64bac0dbfe139d4a51499e5ca093fa8206bd041fc77b6-apidata.googleusercontent.com didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by gjbg1989** [comment]
浏览器代理插件启用端口SOCKS5:1080

**Comment by gjbg1989** [comment]
模块管理-启用 X_tunnel只是回应你流量一直没用上，并没说是一定成功下载excel。
要不，给个下载excel链接。。。

**Comment by nly4lov** [comment]
1. https://adwords.google.com/KeywordPlanner#search登陆你的谷歌邮箱
2. 在如下图所示区域输入随便一个词，比如power spring，然后点击左下方的get idea
![qq 20171110135807](https://user-images.githubusercontent.com/11325411/32644881-56370a76-c61f-11e7-97dc-da9b800684d4.png)
![qq 20171110135834](https://user-images.githubusercontent.com/11325411/32644889-5ee1e6c8-c61f-11e7-965f-13b7c544eb54.png)
3. 右边中间出现的一个download，格式选Excel CSV，然后按一下download,然后save files,弹出窗口https://00e9e64bacb31d7e2059857f75f8a410ff6de88000ae8c6596-apidata.googleusercontent.com/download/storage/v1/b/planner-download/o/f6e2376a-b498-4561-8e18-e31af76d70d4.csv?qk=AD5uMEuonebXOHm1XsH44bDMXQzBUBrUUBo895Qn6-0_BsWCo0LZXA2zwga4e92owHqeuzyL8GaLg_C4-wXWkcwiOGJ3NFJt7f4axK6_jL0hZYVSwvww4WHgpHTOCvz2PFHuI_hlNOQ7leCqQcIbPCjR9LdBrCrAEQHJOlvj-ZX3oukjIuNbSBGNeCloKA17UoR-Kzqm-vSie8A8hCDq7idOumZe7f4GnB9piutz_VaRXUdp20YnLMyBg4nOY863C4WYdVJy2jcx8ZaQgBt9-GbdoSH8I5_GyDTamqYpEfT0Ari7MoZj3AEh1VRfzt5qc0B5RHclCbgQ8fisBodrb9oQAvRySJQuB5Ke4vbAq0CjdIzelyNylBOJO3CJh29KbHVOgP0CRz8TLoxTDkZyX1HYRvQYhMfDHg0uZg7LeX9gth-kNkL7LyuXZN_4hwe1xUe112iTZOGF-Nun14tDQjCDRwTiibqV4JoJwWtyLbBh0TNyXn-GJN1xzTUYUqC11Q8yRW1HGoCYvLl2MM6CQiqC9nFk3qKN0uJtSInDiAEIt0U0o6AlEc1qQkro2L1gmqRTUHXx52zDaRUJ25Jj0tYjRp3dtRDc51T33oCAExC1HaFx4iwwiUdAgBVuFXas5BkAASlWN_iM5wvgWvwkhGeCKfRPP4gN3lVpxAoFL8SfpUdcfVNt-N-CpnrR4PE1ldSPoEyLgWF2j_lfdA8abM_e34bxNmYhCUdxr1nF8QhpHNxX1rL1ow32eOsDH_UsfWdsV-Aq91omO2XccIVBYZ6-wgwwdNT6Hg，然后就没有然后了

**Comment by gjbg1989** [comment]
不好意思，得登录adwords...无法进入第2步，给个下载excel链接都这么复杂，呵呵
看来此代理不行只能改用其它了

**Comment by nly4lov** [comment]
@gjbg1989 今天下午的xx一时能翻一时不能的，我也是分了两次才发出上面那个帖子。
那个长长的链接就是我当时点了save之后出来的窗口链接，不知道能不能直接下载。

**Comment by gjbg1989** [comment]
8087与SSR代理结果：{"error":{"errors":[{"domain":"global","reason":"badLockedDomainRequest","message":"Bad Locked Domain Request"}],"code":400,"message":"Bad Locked Domain Request"}}
x-tunnel超时

**Comment by gjbg1989** [comment]
8087或SSR代理结果：{"error":{"errors":[{"domain":"global","reason":"badLockedDomainRequest","message":"Bad Locked Domain Request"}],"code":400,"message":"Bad Locked Domain Request"}}
x-tunnel超时

**Comment by nly4lov** [comment]
![e103](https://user-images.githubusercontent.com/11325411/32646826-7c32dade-c629-11e7-9e72-fcc925a033da.gif)这是什么意思
