### ISSUE TITLE
又上不去了！

### ISSUE THREAD

**Issue by netfun2000** [XX-net/XX-Net#8213]
XX-Net Status:

sys-platform: armv6l, Linux-4.9.41+-armv6l-with-debian-9.1
os-system: Linux
os-version: #1023 Tue Aug 8 15:47:12 BST 2017
os-release: 4.9.41+
os-detail: Dist:debian; Version:9.1; ID:
architecture: 32bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
xxnet-version: 3.7.15
python-version: 2.7.13
openssl-version: 16.2.0 TLSv1_2 h2:alpn
ipv6-tunnel: Developing
use-ipv6: force_ipv6
gws-ip-num: total:7 ipv4:719 ipv6:0
ipv4-status: Fail
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​换 3.7.7 版本试试，看看是否版本问题

**Comment by gjbg1989** [comment]
ipv6-tunnel: Developing——3.7.15不应是该结果，开启正常应是enable
use-ipv6: force_ipv6——改为auto试试

**Comment by nly4lov** [comment]
今天下午比较古怪。一会能一会不能的。

**Comment by netfun2000** [comment]
下午升级到3.7.16可以翻了。
