### ISSUE TITLE
X-tunnel 无法访问安卓开发者官网

### ISSUE THREAD

**Issue by tianyajuechen** [XX-net/XX-Net#8219]
X-tunnel无法访问：https://developer.android.com/
![a](https://user-images.githubusercontent.com/11382955/32646252-54da8126-c5b1-11e7-8852-fe2b5b782699.png)

**Comment by gjbg1989** [comment]
貌似姿势不对？8087及X-tunnel的1080均可正常访问

**Comment by tianyajuechen** [comment]
刚刚打开了，但是！只是一会儿！还有就是就算打开了，网站跳转的子页面也定不开。现在又无法访问了。。。。

**Comment by zegzhi** [comment]
安卓者有国内版本。
https://developer.android.google.cn/index.html

**Comment by zegzhi** [comment]
安卓开发者网站有国内镜像。
https://developer.android.google.cn/

**Comment by tianyajuechen** [comment]
又好了。。。。。
