### ISSUE TITLE
每次开机运行或者直接运行软件的话是否可以设置了不弹出http://127.0.0.1:8085/这个页面呢？

### ISSUE THREAD

**Issue by piaoyun** [XX-net/XX-Net#822]
每次开机运行或者直接运行软件的话是否可以设置了不弹出http://127.0.0.1:8085/这个页面呢？

因为我觉得没有必要每次开机运行都自动打开这个页面，可以在需要的时候自己在打开呢。

谢谢了

**Comment by ll49** [comment]
配置里把‘启动时弹出状态页’切换到OFF

**Comment by cobob** [comment]
可以的，打开http://127.0.0.1:8085/?module=launcher&menu=config
把“启动时弹出状态页”设置成“OFF”

**Comment by piaoyun** [comment]
好的，谢谢楼上的朋友了。
