### ISSUE TITLE
升级3.7.15后不能用的可以试试参考win10开启ipv6设置

### ISSUE THREAD

**Issue by simonjoelucky** [XX-net/XX-Net#8221]
Wiki文档里面的win10开启ipv6更新了组策略方法，我按照那个操作后3.7.15就可以用了

**Comment by xpf7622** [comment]
是可以用了，但还不稳定，用上一个小时候，突然就显示“尚未建立连接”，不知啥时又好了。

**Comment by xpf7622** [comment]
状态栏显示：
IPv6 Tunnel | probe (primary server)
-- | --
IPv4 Status | OK
IPv6 Status | Fail

**Comment by xpf7622** [comment]
现在又好了，也没操作啥。

**Comment by xpf7622** [comment]
IPv6 Tunnel | enable
-- | --
IPv4 Status | OK
IPv6 Status | OK

**Comment by smartdancer** [comment]
但是我的ipv4 number是0个

**Comment by matrixirtam** [comment]
15
 ipv4 不能用了  原生ipv6
![image](https://user-images.githubusercontent.com/5365885/32649179-18b8a7bc-c634-11e7-9b51-ed40bd807daa.png)
