### ISSUE TITLE
macOS上非常不稳定，有遇到相同情况的吗？

### ISSUE THREAD

**Issue by qingsheng0214** [XX-net/XX-Net#8232]
折腾了一周多了，下载IPv6需要的安装包安装时出错，后来下载各种依赖包自己编译安装，安装成功但是无法正常使用，最后折腾了一周多到现在终于在macOS上安装成功并能够使用IPv6访问google了，但是发现访问非常不稳定，一会能够访问，一会不能访问，而且XX-NET看上去好像有卡死的情况，不知道到底是miredo的问题还是xx-net的问题。这个问题在Mac中存在，自己的另一台windows系统完全没有这样的情况(处于相同的网络环境)。不知道各位有没有这样的情况？

请点击上面的 ↑【Preview】标签↑ 查看格式化后的说明。
阅读完毕后，请点击上面的【 Write】标签，先【删除】本说明内容，然后描述你遇到的问题。

---
## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-Tunnel 流量丢失  
  先确认采用最新的版本，能够正常登录x-tunnel。
  请给xxnet.dev@gmail.com 发邮件
  
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。
   
---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

**Comment by wanggggggg** [comment]
macos 10.13.1 能安装成功吗？ 有链接可以参考一下没

**Comment by cncyk06** [comment]
你好，请问能提供一下你是如何在mac环境下安装miredo的吗？

**Comment by TitusL** [comment]
参考
https://github.com/XX-net/XX-Net/issues/8045
我的os 版本是10.12.6，有反馈10.13，可能有兼容性问题。你可以试试。

**Comment by qingsheng0214** [comment]
@wanggggggg 我在公司和在家里的都是10.12.6，公司的那台不稳定，家里的这台今天安装了一下，没有问题，运行很好，稳定有3000个可用IP。10.13.1没有试过，不知道怎么样。没有一个具体的链接，我是参考了很多文章，试验了很多次才最终安装上了，有需要的话，我之后可以写一下仅作参考

**Comment by qingsheng0214** [comment]
@cncyk06 需要的话，之后我写一个总结可以作为参考吧

**Comment by qingsheng0214** [comment]
@TitusL 不知道是不是xx-net版本过高引起的，我在公司用的那个是3.7.15,非常不稳定，公司的那个试验能够安装之后，今天在家里把家里的这台也安装了一下,xx-net用的是3.7.12，运行的非常好，没有任何问题。两台macOS都是10.12.6的。

**Comment by lichenyu** [comment]
问下你用的mac是64位的么？

**Comment by qingsheng0214** [comment]
@lichenyu 是64位的啊
