### ISSUE TITLE
安卓版本 尚未建立连接

### ISSUE THREAD

**Issue by ShixiangWang** [XX-net/XX-Net#8242]
XX-Net Status:

sys-platform: armv8l, Linux-3.18.41+-armv8l-with
os-system: Linux
os-version: #1 SMP PREEMPT Fri Sep 22 07:04:05 CST 2017
os-release: 3.18.41+
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 7.1.1; PRO 6s Build/NMF26O; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.102 Mobile Safari/537.36
xxnet-version: 3.7.9
python-version: 2.7.2
openssl-version: 0.14 TLSv1_2 h2:no

ipv6-status: 1
gws-ip-num: total:12347 good:7413
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ylwszb** [comment]
proxy_state: Fail
ca_state: Fail

似乎浏览器没找到代理？

安卓只开XX是不行的，还要运用软件或安装浏览器插件，来识别XX代理才能正常运行。

实在不行可放弃GAE，用代理软件直接走X-TUNNEL端口，也可正常fanqiang。

**Comment by ShixiangWang** [comment]
嗯嗯，那我试试。



来自 魅族 PRO 6s



-------- 原始邮件 --------
发件人：ylwszb <notifications@github.com>
时间：周六 11月11日 14:57
收件人：XX-net/XX-Net <XX-Net@noreply.github.com>
抄送：王诗翔 <wangshx@shanghaitech.edu.cn>,Author <author@noreply.github.com>
主题：Re: [XX-net/XX-Net] 安卓版本 尚未建立连接 (#8242)


proxy_state: Fail
ca_state: Fail

似乎浏览器没找到代理？

安卓只开XX是不行的，还要运用软件或安装浏览器插件，来识别XX代理才能正常运行。

实在不行可放弃GAE，用代理软件直接走X-TUNNEL端口，也可正常fanqiang。
