### ISSUE TITLE
运行start.bat报错

### ISSUE THREAD

**Issue by yuehuangquan** [XX-net/XX-Net#8251]
![error](https://user-images.githubusercontent.com/28100481/32687646-25f5c0f4-c6fc-11e7-81f3-7a5b140ef80f.PNG)

**Comment by gjbg1989** [comment]
貌似自动建立的启动图标是运行start.vbs而不是start.bat

**Comment by xxnet** [comment]
​8086的端口被别的软件占用了

**Comment by yuehuangquan** [comment]
感谢提醒！我用netstat -ano | findstr "8086"查到是PID为4，System进程占用的，然后用netsh http show servicestate查到是一个W3SVC的服务的问题，停止该服务后问题解决。再次感谢 @xxnet
