### ISSUE TITLE
按照教程做了，没有报错，IPV6网站依旧测试不通过

### ISSUE THREAD

**Issue by macroxmu** [XX-net/XX-Net#8255]
用的3.7.16最新版，WIN7 64位系统，按照《IPV6-Win7》，《IPv6-Win7 小白指引》两篇都做过，依然不行
执行脚本没有报错，各种错误检测方法也都看了，都正常，就是测试网站通不过，实在搞不懂哪里的问题，求解~~

各种设置如下：
=================================================================
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.1.146:55045
外部 NAT 映射    : 112.5.202.232:62861
=================================================================

无线局域网适配器 无线网络连接:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Intel(R) WiFi 链接 5100 AGN
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2002:6455:77c3:1:ed1c:1c84:7777:fa89(首选
)
   临时 IPv6 地址. . . . . . . . . . : 2002:6455:77c3:1:b906:834c:458:de07(首选)

   本地链接 IPv6 地址. . . . . . . . : fe80::ed1c:1c84:7777:fa89%12(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.146(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2017年11月11日 16:59:30
   租约过期的时间  . . . . . . . . . : 2017年11月12日 17:21:24
   默认网关. . . . . . . . . . . . . : ::
                                       192.168.1.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 218111589
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-1F-80-DF-3F-00-22-68-14-85-46

   DNS 服务器  . . . . . . . . . . . : 2001:4860:4860::8888
                                       2001:4860:4860::8844
                                       180.76.76.76
                                       114.114.114.114
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用
隧道适配器 isatap.{9F1CB3B4-5A70-43C0-8B24-4FEA241BBF04}:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft ISATAP Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::5efe:192.168.1.146%17(首选)
   默认网关. . . . . . . . . . . . . :
   DNS 服务器  . . . . . . . . . . . : 2001:4860:4860::8888
                                       2001:4860:4860::8844
                                       180.76.76.76
                                       114.114.114.114
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:53aa:64c:2ce4:a72:8ffa:3517(首选)

   本地链接 IPv6 地址. . . . . . . . : fe80::2ce4:a72:8ffa:3517%15(首选)
   默认网关. . . . . . . . . . . . . :
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用

==========================================================
发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        手动        256  ::/0                       12  无线网络连接
否        手动        256  ::1/128                     1  Loopback Pseudo-Interf
ace 1
否        手动        8    2001::/32                  15  Teredo Tunneling Pseud
o-Interface
否        手动        256  2001:0:53aa:64c:2ce4:a72:8ffa:3517/128   15  Teredo T
unneling Pseudo-Interface
否        手动        8    2002:6455:77c3:1::/64      12  无线网络连接
否        手动        256  2002:6455:77c3:1:b906:834c:458:de07/128   12  无线网
络连接
否        手动        256  2002:6455:77c3:1:ed1c:1c84:7777:fa89/128   12  无线网
络连接
否        手动        256  fe80::/64                  11  本地连接

**Comment by gjbg1989** [comment]
试试最简单的，运行程序目录内的 enable_ipv6.bat 手动开启ipv6

**Comment by gjbg1989** [comment]
参考： https://support.microsoft.com/zh-cn/help/929852/how-to-disable-ipv6-or-its-components-in-windows 用第二排的第4个，检查一遍问题、修复重启就好了——XX-Net开启IPv6

**Comment by gjbg1989** [comment]
32位系统正常的、与你有差异在（或许最后一行没问题）：
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否

**Comment by onplus** [comment]
有6to 4,禁用teredo `netsh int teredo set state disable`
别测试，只看force  ipv6能不能翻墙

**Comment by lawsherman** [comment]
把服务器名称teredo.remlab.net，改为 win10.ipv6.microsoft.com 试试

**Comment by ylwszb** [comment]
@macroxmu 

类型 : enterpriseclient (Group Policy)

你是用组策略开启的此项，没有问题


客户端类型 : teredo host-specific relay

我的是 “客户端类型 : teredo client”

建议用新批处理再试一下：[IPV6 update.zip](https://github.com/XX-net/XX-Net/files/1463573/IPV6.zip)

**Comment by Anesthesia2016** [comment]
我检查ipv6都是：没用检测到您的ipv6地址。
我也是折腾了好久，ipv6搞不定

**Comment by gjbg1989** [comment]
用的3.7.16最新版，按2楼不行再3楼。。。

**Comment by ylwszb** [comment]
建议把本地连接中ipv6协议停用，不是删除。
再更换teredo服务器，这样试试。

**Comment by gjbg1989** [comment]
ipv6开启方法 https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95

**Comment by macroxmu** [comment]
@gjbg1989 
您说的几种方式我都试过了，包括微软提供的修复，XXNET自带的开启脚本，都没用用，唯一可疑的是那个Teredo客户端，您是怎么设置的？貌似之前看过的教程都没有去设置这个

以及更换Teredo服务器域名，我把另一个帖子里的所有域名都试过了，依然没救……T______T~~~

@ylwszb 
按照您在#8254中提供的脚本跑了一遍，没有什么报错信息，但依然无法通过ipv6测试页测试?

**Comment by macroxmu** [comment]
蛮绝望的，不就是想Google点学术内容么，招谁惹谁了，╮(╯▽╰)╭。。。。

**Comment by gjbg1989** [comment]
看看：https://github.com/XX-net/XX-Net/issues/8265

**Comment by onplus** [comment]
@macroxmu 就想看谷歌学术？x-tunnel

**Comment by macroxmu** [comment]
按照这篇文章做了，终于可以了，谢谢大家！
http://bbs.pcbeta.com/viewthread-1580771-1-1.html
感觉差异就是按照这篇做的话，客户端类型是teredo client，之前按脚本做的不是这个
