### ISSUE TITLE
360弹窗警告问题

### ISSUE THREAD

**Issue by 1098274j** [XX-net/XX-Net#826]
昨天装了XX-net用了半天感觉不错也没什么问题 结果我今天一打开 360就弹窗警告说XX-net上传隐私信息 让我删除文件 是360误报吗？ 这是什么原理？

**Comment by xxnet** [comment]
请把360的弹窗截图贴上来看看

在 2015年8月18日 下午3:52，1098274j <notifications@github.com>写道：

**Comment by 1098274j** [comment]
我重装了一遍XX-net再运行 又不弹窗了 但我在360的隔离区看见了这个文件
![image](https://cloud.githubusercontent.com/assets/13847311/9325897/73f09f52-45c8-11e5-815b-77d7545a9d32.png)

360还弹过这种窗口
![image](https://cloud.githubusercontent.com/assets/13847311/9325989/39088caa-45c9-11e5-993e-6996a407247c.png)
这个我当时没仔细看 还以为是什么别的插件就选择了阻止操作+不再提醒 但是软件还能正常运行
这个弹窗跟之前的不是一种弹窗 那个直接就是让我删除文件的

**Comment by wenliyang** [comment]
goagent作者曾说过，360会干扰goagent等翻墙软件的运行
想翻墙就请卸载360

**Comment by 1098274j** [comment]
我以前用goagent没见360干扰或禁止 也没见弹窗说上传隐私啊

**Comment by ARwMq9b6** [comment]
抵制 360 用户。

**Comment by 1098274j** [comment]
真是搞不懂您哪里来的勇气说这种话。我使用了360与您何干呢？

**Comment by ARwMq9b6** [comment]
@1098274j 传言 360 会上报 Shadowsocks, VPN, SSH 等翻墙软件的信息给政府或 GFW 有关部门，俺没用过 360, 不知这种说法是真或是假。现状是很多翻墙社区都命令明令“禁止使用某数字的安全产品”，这是由于翻墙软件大多是公用的，如 GoAgent, 很多网友用同一个 IP 翻墙，泄漏之后会对多数人不利。

**Comment by 1098274j** [comment]
您既然已经说是传言了，那么这种说法本身真假就已经存疑，并且在我经常去的论坛、贴吧里很多人都在翻墙的同时使用着国产的安全软件，根本不止360一家，而且我相信，光是使用这个软件的人，就有不少人使用这些杀毒软件。我在下载安装这个软件时，并没有看见关于明令禁止使用360类似的提示。至于翻墙社区的提示，这里也没有，不是吗？更何况，咱们现在聊的话题已经与我原来发这个帖的目的没有关系了。不过谢谢您的认真回复，我也涨了涨知识，以后我会尽量留点神的。

**Comment by luyang93** [comment]
@1098274j  +1

**Comment by panzer1313208** [comment]
@1098274j 来，我跟你讨论下360的问题，360这个传言不是空穴来风。我朋友搭建了一条线路，当时没用360，后来有一次他手贱用了360，结果他线路从此断断续续的。

**Comment by cobob** [comment]
360、金山等都算是流氓软件的先行者吧，想翻墙的话其实直接卸载就好了。

**Comment by malthae** [comment]
用360您老还是乖乖上天朝局域网吧

**Comment by malthae** [comment]
360是标准的流氓软件,要证据网上一搜一堆,有理有据,360也就能哄骗一下没有电脑知识的普通用户,不过这群用户群里大到不敢想象
