### ISSUE TITLE
3.7.16 运行反馈

### ISSUE THREAD

**Issue by ylwszb** [XX-net/XX-Net#8260]
当前版本运行正常，IPV6的IP还在缓慢回升。就是有些慢，希望能优化一下。

XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-tunnel: enable
use-ipv6: auto
gws-ip-num: total:8162 ipv4:0 ipv6:3273
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:78 h2:0
scan-ip-thread-num: 50
ip-quality: 251
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

![1](https://user-images.githubusercontent.com/19790792/32689190-c0d6f12e-c71a-11e7-9f8a-aa06f4a49533.jpg)
![2](https://user-images.githubusercontent.com/19790792/32689191-c2adea98-c71a-11e7-8bf6-cc333fde38fa.jpg)
![3](https://user-images.githubusercontent.com/19790792/32689193-c36a5192-c71a-11e7-9f55-ad05c588880f.jpg)
![4](https://user-images.githubusercontent.com/19790792/32689194-c3c53972-c71a-11e7-885d-09e75fb08079.jpg)
![5](https://user-images.githubusercontent.com/19790792/32689195-c4a65290-c71a-11e7-9c4c-e05d76b66acf.jpg)

**Comment by ylwszb** [comment]
![6](https://user-images.githubusercontent.com/19790792/32689313-03a96728-c71d-11e7-9c89-be7cd1316a5b.jpg)

**Comment by xc1988** [comment]
ipv4看来是彻底堵死了。接下来估计要折腾IPV6了

**Comment by ken520** [comment]
能正常上  就知足吧

**Comment by ylwszb** [comment]
安卓手机无需开启ipv6，使用代理软件连接X-Tunnel端口就能正常fanqiang

**Comment by ylwszb** [comment]
PAC，GAE，X-Tunnel
三种模式全部开启局域网代理，已测试无问题。
就是有些慢，慢到连头像小图片都刷不出来。
