### ISSUE TITLE
建议修改程序Web控制页的稳定版本号为好用的3.7.16版

### ISSUE THREAD

**Issue by gjbg1989** [XX-net/XX-Net#8262]
https://github.com/XX-net/XX-Net/blob/master/code/default/download.md 所示的稳定版与程序web页不一致：一个是3.7.16，一个还是3.7.9
可能误导只使用稳定版的，如 #8250 #8252 #8259 #8261

**Comment by xxnet** [comment]
已经更新发布了，终于有一个新的稳定版。
