### ISSUE TITLE
win 7 本地连接  IPV6 无internet访问权限，求教

### ISSUE THREAD

**Issue by 308901951** [XX-net/XX-Net#8272]

**Comment by 308901951** [comment]
帖子刚发出又恢复正常了，不过本地连接 IPV6 还是无INTERNET访问权限

**Comment by onplus** [comment]
95%+的人都是这样，不用管
![image](https://user-images.githubusercontent.com/31188782/32695803-b7bf6e5e-c7a1-11e7-9642-afa9049a5498.png)
大规模应用的只有教育网

**Comment by 308901951** [comment]
事实证明确实如此，不过IPV6  IP数量比较少只有200不到

**Comment by gjbg1989** [comment]
数量多少需待以时日。。。

**Comment by 308901951** [comment]
IP 现在已经快600了
