### ISSUE TITLE
请问一下这是什么问题呢
电脑上终端ipv6也有2001的数字了

### ISSUE THREAD

**Issue by maoamiao** [XX-net/XX-Net#8289]
XX-Net Status:sys-platform: AMD64, Windows-10-10.0.15063os-system: Windowsos-version: 10.0.15063os-release: 10os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0architecture: 32bit,WindowsPEbrowser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.3538.400 QQBrowser/9.6.12501.400xxnet-version: 3.7.16python-version: 2.7.13openssl-version: 16.0.0 TLSv1_2 h2:alpnipv6-tunnel: probe (primary server)use-ipv6: autogws-ip-num: total:448 ipv4:0 ipv6:440ipv4-status: OKipv6-status: unknownconnected-link: new:0 used:0worker: h1:0 h2:0scan-ip-thread-num: 10ip-quality: 237is-idle: 0block-stat: OKproxy_state: OKca_state: OKAppid_Working: trueAppids_Out_Of_Quota: falseAppids_Not_Exist: falseUsing_Public_Appid: false

**Comment by gjbg1989** [comment]
难道不是系统的网络都被断过？
试试：退出XX-Net，先后运行程序自带的关闭、开启IPv6.bat

**Comment by maoamiao** [comment]
嗯好的 谢谢帮助
