### ISSUE TITLE
自己搭代理有什么推荐的方法吗

### ISSUE THREAD

**Issue by SchwarzXia** [XX-net/XX-Net#8292]
最近看上了一个不错的vps服务器，准备买下来搭代理fq，想知道有没有什么要注意的，还有需不需要用什么软件或者协议

**Comment by onplus** [comment]
小白一键SSR就行了 

或者https://github.com/waylybaye/HyperApp-Guide

**Comment by 2378** [comment]
哪家的

**Comment by CumpotRun** [comment]
租个VPS然后SSR

**Comment by zhaoliuduoduo** [comment]
多少钱啊？我也想自己搭建了 @Temmie-hOi

**Comment by CumpotRun** [comment]
最低2.5美元每月

**Comment by 2378** [comment]
@CumpotRun 
2.5刀是哪家
