### ISSUE TITLE
Wrong password('')  GoAgent proxy.ini password is wrong!  

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#8297]
头一次发现这样的错误提示

XX-Net 3.7.15，一切正常，你可以访问真正的互联网了。

**Comment by gjbg1989** [comment]
没明白：主题是wrong，正文又一切正常
基本常识——退出程序再解压覆盖不就好？

**Comment by shpherd** [comment]
之前能上youtube的。今天XX-NET提示“XX-Net 3.7.15，一切正常，你可以访问真正的互联”，但是google提示“Wrong password('')

GoAgent proxy.ini password is wrong!”

**Comment by onplus** [comment]
你的appid 有没有密码，有没有修改过manual.ini

**Comment by shpherd** [comment]
有密码，没有修改过manual.ini

**Comment by onplus** [comment]
看一下config.ini 里有没有密码

**Comment by gjbg1989** [comment]
有manual.ini文件一直存在，密码操作只有自己清清楚楚，proxy.ini是软件包自带文件，使用者不必修改它，故解压覆盖绝不会有任何问题！

**Comment by shpherd** [comment]
config.ini 中添加了密码，问题解决
