### ISSUE TITLE
小白表示不知道什么问题

### ISSUE THREAD

**Issue by zw5685669** [XX-net/XX-Net#8317]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-tunnel: enable
use-ipv6: force_ipv4
gws-ip-num: total:3000 ipv4:304 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1178
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by caizzoo** [comment]
管理员身份运行 XX-Net-3.7.16\code\default\gae_proxy\local\ipv6_tunnel 的 enable_ipv6.bat试试

**Comment by dahai058** [comment]
个人小白整了几次ipv6未成功，幸好还有quic和ssr两种方式

**Comment by gjbg1989** [comment]
@zw5685669 1、系统服务IP Helper 必须为自动。如还不行，
2、退出XX-Net，先管理员运行 disable_ipv6.bat，再 enable_ipv6.bat 
3、如以前是通过组策略来设置的，先全部设置回默认值“未设置”，再重复 2、一次

**Comment by gjbg1989** [comment]
今天Win10的IPV6断了几次了，但 disable_ipv6.bat enable_ipv6.bat 能解决问题

**Comment by hmdm123** [comment]
@gjbg1989 按照您说的【2，（退出XX-Net，）先管理员运行disable_ipv6.bat，再enable_ipv6.bat 】然后就好了。
谢谢！！

**Comment by zyxdtk** [comment]
补充下，按照 gjbg1989  说法还没有连接上，可以试试把 good_ip.txt 删除，然后重启XX.net

**Comment by gjbg1989** [comment]
删除或改名——保留

**Comment by mangic** [comment]
@zyxdtk 删了也不行

**Comment by gjbg1989** [comment]
试试貌似有些不一样参数的方法：关于 Teredo 隧道实现XXNET的IPV6 win7设置 - http://www.360doc.com/content/17/1010/16/496343_693814096.shtml

**Comment by jaxguo** [comment]
Get Admin
[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。
运行enable ip v6居然拒绝访问，我是管理员运行的
