### ISSUE TITLE
3.7.9（不含） 后的版本在window10上遇到了下面的问题，不能使用。

### ISSUE THREAD

**Issue by IBMMACROSOFT** [XX-net/XX-Net#8319]
![2017-11-14 09_23_13-c__users_administrator_desktop_](https://user-images.githubusercontent.com/33645376/32760276-8996f9f6-c928-11e7-97fd-ddfe8d99b8ad.png)
![2017-11-11 10_10_55- c__program files_xx-net-master_xx-net-master_code_3 7 15_python27_1 0_python e](https://user-images.githubusercontent.com/33645376/32760261-7ff284ba-c928-11e7-90a8-bbbc0fac95ca.png)

**Comment by xxnet** [comment]
​怀疑更新不完全，重新下载一个 3.7.16版本 试试

**Comment by IBMMACROSOFT** [comment]
我使用的是自动升级功能。难道自动升级不完整？！我单独下个3.7.16版本试试。
![image](https://user-images.githubusercontent.com/33645376/32760595-ebf8e46e-c929-11e7-93ba-f9d5cc6c5f76.png)

**Comment by nly4lov** [comment]
我从来不自动升级，那样会导致目录越来越大

**Comment by Hailprob** [comment]
@nly4lov 那下载新版本，清除原来的信息只用删除原文件夹就行了吗？

**Comment by nly4lov** [comment]
@Hailprob 把原目录下的、除了Data文件夹之外的所有东西，都删除；
下载的新版本，解压出来的，弄进去。
就齐活。

**Comment by IBMMACROSOFT** [comment]
![2017-11-14 13_19_05- c__program files_xx-net-master_xx-net-master_code_default_python27_1 0_python](https://user-images.githubusercontent.com/33645376/32764179-2018afb2-c93f-11e7-8770-0eaf7623cb07.png)
单独下载3.7.16 也还是有这个问题，无法启动程序。
![2017-11-14 13_19_36- c__program files_xx-net-master_xx-net-master_code_default_python27_1 0_python](https://user-images.githubusercontent.com/33645376/32764176-1a4358a8-c93f-11e7-82a0-5489dc53d30a.png)

**Comment by nly4lov** [comment]
右击start.bat，以管理员身份运行呢？

**Comment by IBMMACROSOFT** [comment]
一样的 问题 ，好像是创建线程失败，应该是python的语法错误，可惜我不会python

**Comment by IBMMACROSOFT** [comment]
![image](https://user-images.githubusercontent.com/33645376/32764510-d63edb3a-c940-11e7-9120-2f8194857b6c.png)

**Comment by nly4lov** [comment]
那干脆退出xx，删除data文件夹，然后右击start.bat，以管理员身份运行

**Comment by IBMMACROSOFT** [comment]
问题解决，主要原因是使用3.7.9的扫描IP数量线程配置为1000个。当升级到3.7.10以后版本，此1000导致程序出错了。修改成500个线程发现3.7.16可以正常工作。再次修改成1000后问题重现。建议大家不要配置1000了。
OK。问题解决。

**Comment by nly4lov** [comment]
你线程数设的实在太大了。默认的是多少你知道不？10~
而且以前大家讨论的结果是这个线程开得越高，电脑就会越卡。
