### ISSUE TITLE
居然出现了22个IPv4 ，速度暴增

### ISSUE THREAD

**Issue by toobed** [XX-net/XX-Net#8344]

**Comment by toobed** [comment]
![20171114220444](https://user-images.githubusercontent.com/13999690/32783753-cf93df5a-c987-11e7-9060-4bd7ce64cc85.png)

**Comment by yeezylife** [comment]
..请问怎么贴图片啊

**Comment by toobed** [comment]
![image](https://user-images.githubusercontent.com/13999690/32783900-42d01560-c988-11e7-90ce-4d44d84f5e40.png)

**Comment by toobed** [comment]
刚刚还是2000+的，

**Comment by gjbg1989** [comment]
贴图、附件——输入栏正下方 selecting them 或从剪贴板粘贴
