### ISSUE TITLE
无法登陆Google账号

### ISSUE THREAD

**Issue by superlucky8848** [XX-net/XX-Net#8353]
XX-Net 3.7.16 设置正常，封锁网站可以访问（GAE模式），Google网站也没问题
但是无法登陆google账号（Chrome登陆以及网站登陆都不行），用chrome登陆同步跳出504错误页
旧的GoAgent证书都删除了，appid是自己的。

请问这个问题怎么解决
XX-Net Status:

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-tunnel: null
use-ipv6: auto
gws-ip-num: total:339 ipv4:0 ipv6:314
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:63 h2:0
scan-ip-thread-num: 10
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​504 错误页贴来看看;
登陆失败时GAE 日志贴来看看

试试用x-tunnel 登陆
