### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by usa-ca** [XX-net/XX-Net#8361]
teredo

**Comment by usa-ca** [comment]
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 10.0.1.97:53789
外部 NAT 映射    : 218.246.21.194:6438


C:\Windows\system32>pause

**Comment by ning5211** [comment]
看看有多少人用这服务器就知道了，默认服务器就是它。换服务器吧。

**Comment by 2378** [comment]
本地映射 : 10.0.1.97:53789
外部 NAT 映射 : 218.246.21.194:6438

哥们，用不用那么高调啊
怕六扇门找不到吗
