### ISSUE TITLE
xp开启teredo隧道，一段时间就会不可用

### ISSUE THREAD

**Issue by jdfq** [XX-net/XX-Net#8365]
如题。用的这个方法：https://github.com/XX-net/XX-Net/wiki/IPv6-WinXP
不可用后，用命令“netsh int ipv6 show teredo state”，显示什么无法连接备用服务器
不可用后，重新用上面的方法换服务器也没有用，禁用ipv6再开启也没用。重启电脑后成功。

**Comment by gjbg1989** [comment]
#8317

**Comment by jdfq** [comment]
现在用我上面的方法，禁用ipv6再开启就行。
