### ISSUE TITLE
上youtube前面有括号数字是什么意思

### ISSUE THREAD

**Issue by eljake58** [XX-net/XX-Net#8468]
![2017-11-19 11 25 44](https://user-images.githubusercontent.com/23495963/32988122-63565458-cd38-11e7-8edf-2449ca77ed5c.png)

好像这个数据越来越大，退出chrome, 重启电脑都是这样

另外我的IPV6有几千个，延迟两百多，看720p都需要暂停缓冲怎么回事

**Comment by zanewayne78** [comment]
通知，你都不看右上角的提示吗？

**Comment by GoodSake** [comment]
那是youtube的notifications，现在不只有subscrible,还有"click that god damn bell"

**Comment by zanewayne78** [comment]
@GoodSake 没订阅的那种推荐通知我记得app客户端有选项，点了再也不会有推荐通知

**Comment by eljake58** [comment]
@zanewayne78 
@GoodSake 
感谢，只注意右边那个铃铛知道是通知
另外你们的ip延迟值多少，我五千多ip，延迟两百多，看720P都不顺畅

**Comment by zanewayne78** [comment]
@eljake58 都被封死了，我用的是X-Tunnel，480都要缓冲，现在都不怎么看视频了

**Comment by eljake58** [comment]
@zanewayne78 可能各地不一样，我这边还不错
