### ISSUE TITLE
求助，状态一直为等待扫描中

### ISSUE THREAD

**Issue by sunshichao520** [XX-net/XX-Net#8494]
状态为尚未建立连接或等待扫描IP中，看过几个帖子，试过几种方法，如开机关机IP等，都无效，也升级了版本，目前为3.7.16

状态码：
XX-Net Status:

sys-platform: x86_64, Linux-3.19.0-58-generic-x86_64-with-Ubuntu-14.04-trusty
os-system: Linux
os-version: #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016
os-release: 3.19.0-58-generic
os-detail: Dist:Ubuntu; Version:14.04; ID:trusty
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.6
openssl-version: 0.13 TLSv1 h2:no
ipv6-tunnel: Developing
use-ipv6: auto
gws-ip-num: total:3000 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

求帮助：
ping ipv6.test-ipv6.com　不通，还有什么方法，求助，谢谢

**Comment by onplus** [comment]
miredo状态？

**Comment by sunshichao520** [comment]
没用你说的这个，应该不是吧

**Comment by onplus** [comment]
不用miredo？你有公网ip吗

**Comment by sunshichao520** [comment]
有公网IP，公司网络

**Comment by sunshichao520** [comment]
需要安装miredo么？　之前好用的，10.18那次大会之后就不行了

**Comment by sunshichao520** [comment]
需要安装miredo么？　之前好用的，10.18那次大会之后就不行了
