### ISSUE TITLE
发个小心得给WIN10 IPV6链接不成功的朋友……

### ISSUE THREAD

**Issue by zongdream** [XX-net/XX-Net#8495]
折腾了几天，终于再次通过teredo搞定IPV6链接，值得注意的是WIN10 的teredo类型一定要改为enterpriseclient，之前我的类型设置设置为client，死活没链接上teredo服务器……可能只是一个低级错误，但确实让我折腾了几天……

**Comment by medivh91** [comment]
照着首页教程来就没问题。。

**Comment by Yealtmzq** [comment]
教程在哪

**Comment by medivh91** [comment]
https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6

**Comment by gjbg1989** [comment]
😂WIN10 的teredo类型一定要改为enterpriseclient——未必，在32Win7Pro新装32Win10Pro双系统，系统自动配置的是client、ping超时的win1710.ipv6.microsoft.com服务器，开机就能正常使用XX-Net
