### ISSUE TITLE
请问对于ie可以用么也就是不用浏览器上的代理可以用么

### ISSUE THREAD

**Issue by Awful-fresh-hand** [XX-net/XX-Net#85]
我今天在chrome官网上下一个chrome，然后通过安装软件却显示无法连接至服务器，最后用的goagent才好用

**Comment by xxnet** [comment]
你是说不用SwitchSharp/SwitchOmiga?

IE可以使用XX-Net访问网络，只是IE11以上才能管理XX-Net.
只需要设置IE的代理就可以了，也就是系统代理。
  右键XX-Net的系统托盘，菜单中选Enable Proxy就好了。
  当然手动设置代理也可以。

在 2015年3月28日 下午6:58，Awful-fresh-hand <notifications@github.com>写道：
