### ISSUE TITLE
FireFox 57相关

### ISSUE THREAD

**Issue by gjbg1989** [XX-net/XX-Net#8503]
Proxy SwitchyOmega - FireFox 57.0可用 附加组件 https://addons.mozilla.org/zh-CN/firefox/addon/switchyomega/ …
YouTube™ Flash-HTML5 - Firefox 附加组件 https://addons.mozilla.org/zh-CN/firefox/addon/youtube-flash-html5/ … FireFox 57.0首次播放YouTube前需点击扩展图标能见数字5才行

**Comment by onplus** [comment]
第二个插件什么目的？

**Comment by gjbg1989** [comment]
没它不能播放YouTube

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33010639-2d8fee86-ce16-11e7-8cfd-a221fee0e3a4.png)

**Comment by gjbg1989** [comment]
测试。。。

https://twitter.com/Trendmatometter/status/932166386100531200

**Comment by gjbg1989** [comment]
https://twitter.com/fang2hua/status/932590242313449473

**Comment by gjbg1989** [comment]
https://pbs.twimg.com/media/DPFONDuW0AAAErZ.jpg

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33025374-c6375d68-ce48-11e7-80e7-a2cdd93fdfaa.png)

**Comment by gjbg1989** [comment]
55-56-57使用代理扩展的一直正常

![default](https://user-images.githubusercontent.com/13290970/33059057-9879afcc-cecd-11e7-9b0d-51d3acfd02b3.png)

**Comment by gjbg1989** [comment]
请 @RomanSmile 解释，一楼的反 👍 的含义，亲测可行的被你这样，又不给出解决之道，何解？

**Comment by gjbg1989** [comment]
据中纪委网站消息，中共宣传部副部长鲁炜涉嫌严重违纪，目前正接受审查。 鲁炜曾任互联网信息办主任，被称为“中国互联网的守门人”。在他的监管下，中国政府加大了屏蔽国外网站的力度，并颁布规定加强对网络内容的审查。

**Comment by RomanSmile** [comment]
@gibg1989
你的这个帖子我几乎没有看明白什么意思，第一个插件是切换代理用，
第二个插件使你可以选择使用 Flash还是 HTML5播放视频，
我不知道别人怎么认为，我自己认为这个插件对于我是多余的，我的firefox使用的 Flash插件被我安装在
~/home文件夹里，我只是修改了fiirefox设置文件，指定路径去哪里调用flash插件，这样省去了每次关闭开启插件繁琐的操作，
但多数是屏蔽状态因为也只有浏览国内网页才用这个flash，至于外网看视频比如youtube，没有flash默认就是html5播放视频，
这是人人都应该知道的事啊！

**Comment by RomanSmile** [comment]
@gjbg1989 
据我知道firefox是目前对于ipv6支持最好的浏览器，google-chrome在中国的弊端在我的系统里是令我头痛的事情，因为chrome内置dns导致在中国境内不能很好的解析ipv6因为它默认检测v4v6哪个协议快就采用哪个协议，很久的老版本有开启或者关闭dns选项，新版本里的google认为他们的设计已经完美，取消了那个选项，在世界大多数地区它的设计都是完美的，但是在中国确实弊端目前看，我尝试用python启动导入他的基本核心文件，他能正确的使用并解析ipv6，从这里我感觉无论是什么浏览器，你还是使用更少的插件，最好是能不用就不用，实在没有办法才去找插件应用，尽量保持浏览器以最小的负荷做最快的反应工作，

**Comment by gjbg1989** [comment]
这是人人都应该知道的事——对一般人不会要求太高？
我的firefox使用的 Flash插件被我安装在......——多不多余因人各异，貌似不是一般人都这样做。
正是播放不了youtube才装的，至于你没有flash默认就是html5播放视频是怎么做到，小白不想。。。
貌似你把别人看得个个都与你一般或比你强。。。😂

**Comment by RomanSmile** [comment]
@gjbg1989 
听我的你可以尝试，把你是用的第二个插件删除或者屏蔽，把flash插件也关闭，就这样去看youtube视频，
他一定播放流畅，因为youtube默认就是html5

**Comment by gjbg1989** [comment]
上上楼的长篇对小白是天书，哎。。。这样了还在小白面前自称小白😭

**Comment by gjbg1989** [comment]
说出自己的更好做法或建议，倒是无私的分享👍

**Comment by RomanSmile** [comment]
![2017-11-23 18 40 15](https://user-images.githubusercontent.com/31476931/33168976-ce6bef3a-d07d-11e7-9e42-437c822e2ec0.png)
![2017-11-23 18 38 39](https://user-images.githubusercontent.com/31476931/33168977-ceb1181c-d07d-11e7-8e33-f06cbf918bf1.png)
你可以看看我为你的截图，我屏蔽了flash插件，
另外，对于活着的人，我认为每个人都是小白，没有万能的，我更是！！

**Comment by gjbg1989** [comment]
谢谢，没截图只要有清晰的说法，也会去尝试。
怪事多多，第一次出现
![default](https://user-images.githubusercontent.com/13290970/33169261-f0eadcdc-d07e-11e7-8478-30569b1c883c.PNG)

**Comment by RomanSmile** [comment]
怎么说呢，在我国任何都不能正常的理解与应用，最开的变成最慢的，或者不能用，
html5比我们使用多年的flash更好的支持视频，世界主流比如google很早就已经有迹象抛弃flash，我自己认为，人家都不在带他玩了，他的独霸时代已经是过去了，可是在国内，我就用flash，更改还要投入人力物力，中国人你不安装flash我就不给你干活，去youtube，政府不让，这就是他们依赖政府保护，强行控制我国网络，

**Comment by RomanSmile** [comment]
另外多说一句，建议你启动xx去他的文件夹下，找到py启动，尽可能以最小启动，让他干活，说句xx人不爱听的话，他的启动太臃肿肥大了，如果机子是老的都无法承受她，

**Comment by RomanSmile** [comment]
或者你在你的图形界面禁止一些启动,比如你不用x隧道，你就把那个模块关闭他，如果你决定用x隧道，就关闭gae模块，这样大大减少了机子负荷，

**Comment by gjbg1989** [comment]
嗯，谢谢绝对高手的建议。但某些东西对非程序员的老白来说，相当深奥。😱
与平时一样的操作，先前是127.0.0.1没响应，退出程序再启动解决。几分钟后又出上面图片错误，大致对比了下，文件与原来没发现异样，解压覆盖ok

**Comment by gjbg1989** [comment]
我的怎么多出一个插件？
![default](https://user-images.githubusercontent.com/13290970/33171004-6b268838-d085-11e7-971e-17f889531180.png)

**Comment by RomanSmile** [comment]
@gjbg1989 
感觉你是一个富有热心肠的人，每次没事来这里都看到你的身影，热心的帮助别人，
去下载一份goproxy，配置一下，你自己拥有自己appid已经在xx部署好了，直接填入就可以用，
这样你不用在每天找ip了，选择速度快的就好了，省事省心，

**Comment by RomanSmile** [comment]
那个插件貌似是google提供的，貌似对你应该没坏处，默认也行，或者尝试屏蔽看看会不会影响你，如果没有影响，你可以不开启他，

**Comment by gjbg1989** [comment]
goproxy r1624 与 r1632 都已无效🤣

**Comment by gjbg1989** [comment]
再次感谢！

**Comment by xxnet** [comment]
​性能优化，好久没做了，等针对路由器优化时再进行吧，暂时把精力放在可用性上。
记得之前还只要64M内存，现在已经跑到128M。
CPU负载也高了几倍

**Comment by RomanSmile** [comment]
@xxnet 
不知道可不可以考虑一下我的这句多余建议，
建议取消扫描ip那个模块，
至于ip你让个人自己需要去扫描填入即可，
你只要专心做好链接与协议，

**Comment by SeaHOH** [comment]
主要是 X 大的宗旨是为小白服务，更是为比小白还白的~
不然这些人怎么活？很可能就放弃了，只能活在于天朝上国。

普通人就没那么多耐心，毕竟时间有限，这就反衬 X 大伟光正。 :hand: :horse:

**Comment by xxnet** [comment]
​扫描ip模块已经很早前就完善了，最近只是调整线程数。
资源消耗方面，目前已经降低到10个线程，应该没有什么影响了。
不需要的话，也可以选择关闭。

**Comment by gjbg1989** [comment]
https://github.com/out0fmemory/Goproxy-Always-Available/issues/21 🤣

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33230835-9a96c708-d225-11e7-918b-eba2a021cbbe.png)
https://twitter.com/chenshaoju/status/934351658414256128
