### ISSUE TITLE
每次睡眠后无法使用

### ISSUE THREAD

**Issue by ycycoo** [XX-net/XX-Net#8511]
每次电脑睡眠后再登录，都显示IPv6无法正常使用，而重启系统后又正常了，系统是Win10专业版 1709
`XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-tunnel: disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:5877
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 338
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false`

```
 netsh int ipv6 show teredo state
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器
```

**Comment by gjbg1989** [comment]
改组策略法为BAT法即可保证使用正常！
确保系统服务IP Helper 为自动并已启动，先前修改的ipv6组策略退回到默认值的全部“未配置”，退出XX-Net，先disable_ipv6.bat，再enable_ipv6.bat即可。
ping 超时的微软服务器或许更稳定！

**Comment by ycycoo** [comment]
@gjbg1989 试了下，在睡眠后再进入，ipv6服务还是无法访问，只有先disable_ipv6.bat，再enable_ipv6.bat这样操作一下，才能访问服务

**Comment by gjbg1989** [comment]
亲测bat法睡眠后醒来好好的，才有上面的说法！

**Comment by ycycoo** [comment]
@换成了微软服务器，重新试了下，貌似解决了，3Q
