### ISSUE TITLE
有质量好的翻墙vpn推荐吗？花钱的别太贵可以接受。。。

### ISSUE THREAD

**Issue by mbhk2004** [XX-net/XX-Net#8533]
有质量好的翻墙vpn推荐吗？花钱的别太贵可以接受。。。最好可以支持多平台的

**Comment by gustav183** [comment]
懂点技术手勤快的话，自己搭建也可以的

**Comment by GoodSake** [comment]
花钱的没用过，应该都很好吧，不过客服可能要英语好才行吧。
中国人搞的latern或x-tunnel什么的速度都不能稳定在2MB/s以上，看youtube 4k就免了吧。

**Comment by onplus** [comment]
https://t.me/ShadowrocketApp

**Comment by willwudk** [comment]
lantern貌似恢复了

**Comment by diaodada** [comment]
2018年国内可用的VPN推荐 快速稳定不掉线国外VPN
https://vpnbay.com/
知乎推荐的免费/付费VPN（安卓/iOS翻墙软件）加速器官网
VPN已经被全网封杀，整理了一批可以用的，方便大家使用，需要的朋友记得收藏分享网址
https://vpnbay.com/the-5-best-vpn-services-for-2018.html

**Comment by hallochina** [comment]
当然有啦。
在中国，最好用的付费VPN推荐 https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。

**Comment by chinahallo** [comment]
在china，测试并推荐好用的付费v.pn
https://vpnchina.zdhweb.com

**Comment by hub6** [comment]
[这里](https://is.gd/tJxAoZ)长期更新

**Comment by longjmp** [comment]
免费的wujie 但经常会断线自动重连
