### ISSUE TITLE
UI界面小bug，配置选项下模块管理折叠菜单是自动展开的

### ISSUE THREAD

**Issue by UltraDWS** [XX-net/XX-Net#8536]
如题，应该是小毛病，但是强迫症的人很煎熬哈哈哈_(:з)∠)_

**Comment by gjbg1989** [comment]
不会是有意为之？以前不是这样的

**Comment by xxnet** [comment]
​是有意改成这样的

因为系统菜单中，已经分Tab 了，内容不会太多。
后面要给每个模块加上重启按钮，可以在web操作，所以默认改为展开。

**Comment by UltraDWS** [comment]
@xxnet 嗦嘎，感谢大佬答疑解惑哈哈，越来越先进了，致敬O7
