### ISSUE TITLE
搞定了！！YouTube 收到了大量由您的網路所發出的要求，因而中斷您的作業。不便之處，敬請見諒。 如要繼續使用 YouTube，請填寫下方的表單。 #8514==

### ISSUE THREAD

**Issue by whhxmwhh** [XX-net/XX-Net#8542]
https://github.com/XX-net/XX-Net/issues/8514
YouTube 收到了大量由您的網路所發出的要求，因而中斷您的作業。不便之處，敬請見諒。 如要繼續使用 YouTube，請填寫下方的表單。 #8514

看来干扰呀。我就是看youtub卡断电。媒体流断。怎么改都不行。现在先禁止谷歌更新了。

完美搞定了

看来是谷歌抽风的原因。现在已经完全禁用谷歌的自动更新了。连同它的更新程序名称也改掉了。看你今后还抽风！

**Comment by gjbg1989** [comment]
难怪用便携版的没遇到？
