### ISSUE TITLE
强悍的 3.8.2 ，晒晒

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#8547]
![image](https://user-images.githubusercontent.com/3606933/33132053-625ea56c-cfd3-11e7-9d30-819b05adf4eb.png)

![image](https://user-images.githubusercontent.com/3606933/33109792-92a994ca-cf7e-11e7-9927-190c7b6b98e3.png)

这个版本很强悍，已经发现的bug都解决了。各种代理方式用起来都顺手。

**Comment by BigBigWolf** [comment]
你的IPV4 Number 怎么这么多？

**Comment by gjbg1989** [comment]
😱久违了的IP延迟100
IPv4：1000
force_ipv4
能说说你是怎么做到的呢？

**Comment by keithhe** [comment]
v4不是早挂了吗？

**Comment by wuwuti** [comment]
告诉大家是怎么做到的：把老版本中的ip段导入新版本扫一扫就ok！10万个ip扫出来6千多个。

**Comment by gjbg1989** [comment]
😂貌似大家感兴趣的是IPv4：1000，而不是6千多个IPv6

**Comment by wuwuti** [comment]
注意：ipv4是扫出来的，ipv6是新版本自带的。

**Comment by wuwuti** [comment]
![image](https://user-images.githubusercontent.com/3606933/33118957-7429a1dc-cfa8-11e7-9e75-345d124b076b.png)

**Comment by gjbg1989** [comment]
貌似ipv6也是扫出来的，能否说出那老东西的版本号？

**Comment by wuwuti** [comment]
3.8.2之前的版本都翻翻看，只要goodip文件显示不是零，就导入试试。

**Comment by gjbg1989** [comment]
goodip文件不是在DATA下，哪有旧的？

**Comment by wuwuti** [comment]
旧版本你不保留的吗？那没办法了。

**Comment by gjbg1989** [comment]
👍楼主好淫 https://github.com/XX-net/XX-Net/issues/8587

**Comment by caizzoo** [comment]
楼主，你IP还能用吗？

**Comment by wuwuti** [comment]
兄弟，能用！4、6都能用，好几千个ip~

**Comment by gjbg1989** [comment]
RT @FENGJoy: 按照步骤一步一步在美国地质调查局网站上注册，设定要下载的地图范围，终于可以看到50年前的老家是个啥样了。有趣啊！（划了一个小范围，结果产生了三张图片，每张约800兆，需要下载一阵子） https://twitter.com/urumqi1987/status/932976483395444736pic.twitter.com/Kt9BMtC01n

**Comment by gjbg1989** [comment]
RT @FENGJoy: 按照步骤一步一步在美国地质调查局网站上注册，设定要下载的地图范围，终于可以看到50年前的老家是个啥样了。有趣啊！（划了一个小范围，结果产生了三张图片，每张约800兆，需要下载一阵子） https://twitter.com/urumqi1987/status/932976483395444736 pic.twitter.com/Kt9BMtC01n

**Comment by epsilono1** [comment]
小白 3.7.16用的好好地，不用升级了吧

**Comment by xxnet** [comment]
​能用就不用折腾
