### ISSUE TITLE
3.8.2 X-TUNNEL Heroku

### ISSUE THREAD

**Issue by ylwszb** [XX-net/XX-Net#8548]
正在使用X-TUNNEL，却发现Heroku连接有问题，Cloudflare日志看了一下，也是一片红

![1](https://user-images.githubusercontent.com/19790792/33110698-b278b938-cf84-11e7-84d0-62dcdda421db.jpg)
![2](https://user-images.githubusercontent.com/19790792/33110700-b2ec05b4-cf84-11e7-923e-0605554dc1d3.jpg)

**Cloudflare front Log红字部分**

![4](https://user-images.githubusercontent.com/19790792/33110878-e3abb95a-cf85-11e7-94aa-331bed28269c.jpg)
![5](https://user-images.githubusercontent.com/19790792/33110880-e71bb270-cf85-11e7-96fe-4e0c0a3a6ec1.jpg)
![3](https://user-images.githubusercontent.com/19790792/33110869-e000bc38-cf85-11e7-90b2-abf9dd0b3ffc.jpg)

Nov 22 12:57:54.633 - [DEBUG] 190.93.245.131 fail:error(' certficate is none',)
Nov 22 12:57:54.633 - [DEBUG] report_connect_fail:190.93.245.131
Nov 22 12:57:55.040 - [DEBUG] 104.16.80.122 fail:error(' certficate is none',)
Nov 22 12:57:55.040 - [DEBUG] report_connect_fail:104.16.80.122
Nov 22 12:57:55.429 - [DEBUG] 172.64.58.93 fail:error(' certficate is none',)
Nov 22 12:57:55.429 - [DEBUG] report_connect_fail:172.64.58.93
Nov 22 12:57:57.058 - [DEBUG] POST v18.singlefly.tk/data status:200 trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],:0
Nov 22 12:57:57.274 - [DEBUG] 141.101.121.90 fail:error(' certficate is none',)
Nov 22 12:57:57.274 - [DEBUG] report_connect_fail:141.101.121.90
Nov 22 12:58:04.224 - [WARNING] h2 timeout 172.64.58.93 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],:7165 worker_trace: processed:7, h2.stream_num:0, sni:yanes.io
Nov 22 12:58:04.335 - [WARNING] h2 timeout 141.101.115.108 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,:111 worker_trace: processed:7, h2.stream_num:0, sni:notetoscreen.com
Nov 22 12:58:04.721 - [WARNING] h2 timeout 141.101.121.90 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,:384 worker_trace: processed:3, h2.stream_num:0, sni:startup.global
Nov 22 12:58:04.885 - [WARNING] h2 timeout 104.19.100.123 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,:164 worker_trace: processed:4, h2.stream_num:0, sni:d.global
Nov 22 12:58:05.223 - [WARNING] h2 timeout 141.101.113.57 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,164:timeout,:338 worker_trace: processed:5, h2.stream_num:0, sni:journomate.com
Nov 22 12:58:05.338 - [WARNING] h2 timeout 104.16.80.122 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,164:timeout,338:timeout,:113 worker_trace: processed:7, h2.stream_num:0, sni:ultra-x.net
Nov 22 12:58:05.721 - [WARNING] h2 timeout 172.64.2.73 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,164:timeout,338:timeout,115:timeout,:382 worker_trace: processed:1, h2.stream_num:0, sni:anvilonline.net
Nov 22 12:58:05.797 - [DEBUG] restore ip:190.93.245.131
Nov 22 12:58:06.337 - [WARNING] h2 timeout 190.93.245.85 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,164:timeout,338:timeout,115:timeout,382:timeout,:615 worker_trace: processed:3, h2.stream_num:0, sni:drop-books.com
Nov 22 12:58:06.549 - [WARNING] h2 timeout 104.28.25.147 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,164:timeout,338:timeout,115:timeout,382:timeout,617:timeout,:210 worker_trace: processed:4, h2.stream_num:0, sni:cigarette-articles-p.ga
Nov 22 12:58:06.724 - [WARNING] h2 timeout 104.25.68.215 task_trace:0:start_request,0:get_task(3),0:get_worker(0):172.64.58.93,0:h2_req,0:start send header,0:start send left body,0:end send left body,198:retry,0:get_task(0),0:get_worker(0):141.101.115.108,0:h2_req,1:start send header,0:start send left body,0:end send left body,176:retry,0:get_task(0),0:get_worker(0):141.101.121.90,0:h2_req,2:start send header,0:start send left body,0:end send left body,266:retry,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,4:start send header,0:start send left body,0:end send left body,347:retry,1:get_task(0),0:get_worker(0):141.101.113.57,0:h2_req,3:start send header,0:start send left body,0:end send left body,161:retry,1:get_task(0),0:get_worker(0):104.16.80.122,0:h2_req,1:start send header,0:start send left body,0:end send left body,188:retry,0:get_task(0),11:get_worker(0):172.64.2.73,0:h2_req,16:start send header,1:start send left body,0:end send left body,713:retry,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,0:start send header,1:start send left body,0:end send left body,179:retry,1:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,180:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:h2_req,2:start send header,0:start send left body,0:end send left body,177:retry,0:get_task(0),0:get_worker(0):190.93.247.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,15336:h2_get_head,0:get_response,1:h2_finish[SP:21001],7165:timeout,112:timeout,384:timeout,164:timeout,338:timeout,115:timeout,382:timeout,617:timeout,210:timeout,:174 worker_trace: processed:5, h2.stream_num:0, sni:1.global
Nov 22 12:58:11.165 - [DEBUG] ip:104.16.80.122 real fail

**Comment by ylwszb** [comment]
虽然Heroku连接有问题，Cloudflare也是一片片的报红

FQ还是没有问题的……
![7](https://user-images.githubusercontent.com/19790792/33111063-db55e8ce-cf86-11e7-80f6-afd09141d39f.jpg)

**Comment by xxnet** [comment]
​谢谢反馈
