### ISSUE TITLE
感谢XX-Net团队！ 

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#8592]
感谢XX-Net团队！
一直在更新，一直没中断。
逢山开路、遇水架桥。
拥有顶尖的技术和想象力。
可贵的毅力和信念。
而这一切，没有任何报酬！
都是免费的···

**Comment by xxnet** [comment]
感谢大家，感谢开源社区的各位参与，也包括帮助回答问题的热心朋友!

GAE_proxy 是使用了Google的资源，包括目前使用IPv6 Teredo的资源，都是免费的。
​X-Tunnel 是收费的，当然也有免费获得流量的途径。
因为需要构建服务器、买一些CDN服务，而且有的还挺贵，所以必须建立可持续发展的模式。
欢迎大家发挥各自的力量，一起把项目发展起来。

这里是项目开发的讨论区：
https://github.com/XX-net/XX-Net-dev/issues

**Comment by wuwuti** [comment]
太好了。好好学习，天天向上。

**Comment by dahai058** [comment]
非常感谢X神让我们能真正畅游互联网。同时也教我这电脑小白慢慢入门了，经过多天的学习摸索前天晚上终于搞定ipv6。
