### ISSUE TITLE
速度飞快的SS加速器！可配合XX-net使用

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#8593]
速度飞快的SS加速器！可配合XX-net使用。
【个人认为这不是广告，不涉金钱。如果版主认为是广告，可立即直接删除，或通知我删除！请不要封禁、屏蔽俺，俺只是为了帮助大家，没别的意思。】
最近XX-net不太稳定，要是有何疑难问题，但临时上不去，找不到解决办法，该咋办呢？
可以试试下面这玩意。
速度飞快！注册即送10G，每天还能随机续命100M-1G流量（看手气），可说是源源不绝。
没必要花钱。没必要付费。
好东西要求也多，规定仅可用于游戏加速，不得用于非法用途，严禁观看任何政治相关内容，如有发现直接删除账号。 不得发布、传送、传播、储存违反国家法律法规禁止的内容：
（1）违反宪法确定的基本原则的；
（2）危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；
（3）损害国家荣誉和利益的；
（4）煽动民族仇恨、民族歧视，破坏民族团结的；
（5）破坏国家宗教政策，宣扬邪教和封建迷信的；
（6）散布谣言，扰乱社会秩序，破坏社会稳定的；
（7）散布淫秽、色情、赌博、暴力、恐怖或者教唆犯罪的；
（8）侮辱或者诽谤他人，侵害他人合法权益的；
（9）煽动非法集会、结社、游行、示威、聚众扰乱社会秩序；
（10）有版权的影视作品，软件作品或其它版权作品。
（11）含有法律、行政法规禁止的其他内容的。
违者后果自负。
网址https://www.feiyun.us/
邀请码
1327	8S1k85AKx0IW2EIK2nhspwvWGl5LAved	 可用
1325	mf3TQUDnr24rQFUOyeimJovHSsc7TnFS	 可用
1324	2OMjJCS5qptcX0ogHi7eRAvUidpczCCF	 可用
1323	6h6xlS1iTa9d08mKQP0PFXo9db1etWDT 	可用
1322	gME5GzdDLXrx8UVdWfjuxni2KD4CodBt	 可用
1326	abn7B79QUg7VOVaoWiYeoXvcjRbOGl0O	可用
1330	F4YIdzSjZffWZP0Vfh1HNCy6oDJIuz46	可用
1329	OfbgydAjEX1MivVrGOEiKJ40jnoUJKf2	可用
1328	IJSN7SG35ksZbcu0XeYEukYGNkLnQYZc	 可用
1317	3qM2I68KqQD0iiorKtHQIHMJs77H7UyF	 可用
1316	aERrmWzrQcaDkSskgNDesYngI4R05nMi	可用
1320	eVPwaaSOgqfXF9UPOHxKnZnfiZQ9pSNt	可用
1321	zJzLDJBPSB5h0dJncABeUGQLbhBKQFGx	  可用
1315	r5d5eMb1H0M4wRD7xHjBLtDPm5FnBpNW	可用
1313	aP1ixZfKJf0M548andOr6fzSNASCX6DY	可用

**Comment by wuwuti** [comment]
既然认为是违规，那就删除吧！我没有任何意见。

**Comment by onplus** [comment]
应该被机器人误杀的，之前为了屏蔽恶意刷屏的

**Comment by xxnet** [comment]
这也太多敏感关键词了吧，呵呵

**Comment by wuwuti** [comment]
哈，难怪直接被关。其实他们这个规则弄得很到位：先把丑话说在头里了，你们再瞎搞不关俺事儿。

**Comment by zzgpku** [comment]
每次续命可以获取10~300MB流量。

**Comment by wuwuti** [comment]
还真是，续命减少了。开始是1-3G，然后是100M-1G，现在直接10-300m了。

**Comment by wuwuti** [comment]
分享了1000个ipv4,1小时内死掉500.哈哈~

**Comment by szwwluogang** [comment]
飞云阁 telegram ssr大户

**Comment by szwwluogang** [comment]
chCRqUVZ565H24KJgtyIk1sXMENK2XcM | 可用
-- | --
976 | aljIrPQOUc3OJ0K3Nvfer8nqqtXduArd | 可用
975 | mKaAm9BiiHwzV1RkaKkauyHJuAspeX8v | 可用
973 | HRIYUPm2vmb8BFhPfD1yoFNKzMpFLs01
