### ISSUE TITLE
为啥使用了自己的appid 仍然无法观看 youtube 的视频？求指点， 有截图

### ISSUE THREAD

**Issue by barnettzane** [XX-net/XX-Net#86]
如图所示 自己加了三个appid 刚开始都工作，后来只剩一个了，但还是不能看视频。

Property 	Value
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture	32bitWindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; rv:36.0) Gecko/20100101 Firefox/36.0
XX-Net Version	1.4.1
Launcher Version	1.0.9
GoAgent Version	3.1.42
Python Version	2.7.9
Proxy Listen	127.0.0.1:8087
working appids	z3zhaozilong2

**Comment by barnettzane** [comment]
Proxy Listen	127.0.0.1:8087
working appids	z3zhaozilong2
Out of Quota appids	
Not Exist appids	z3zhaozilong1|z3zhaozilong
PAC URL	http://127.0.0.1:8086/proxy.pac
Google IP	2859

**Comment by xxnet** [comment]
working appids z3zhaozilong2
Out of Quota appids
Not Exist appids z3zhaozilong1|z3zhaozilong

z3zhaozilong1|z3zhaozilong 这两个appid不正常，先检查，看看是否已经部署好了，可以试试重新部署。

z3zhaozilong2 这个是流量跑超了。

2015-03-29 13:16 GMT-04:00 barnettzane <notifications@github.com>:
