### ISSUE TITLE
长城宽带无法开启ip6

### ISSUE THREAD

**Issue by hibluesea** [XX-net/XX-Net#8621]
如题，在电信及移动的网络测试可以正常获取ip6地址，使用长城宽带IPv6 Status 就变为fail，miredo面板中的teredo turnnel 显示为黄灯，请问有什么解决方案没？

**Comment by hibluesea** [comment]
问题已经解决，更换面板中的server地址即可

**Comment by sgricky** [comment]
我也是黄灯，有什么地址可以选择？
