### ISSUE TITLE
【3.8.3】 更强悍！关于配置技巧

### ISSUE THREAD

**Issue by wuwuti** [XX-net/XX-Net#8623]
3.8.3 更强悍！
基本上有五千个ipv6值，20万个ipv4值。
![image](https://user-images.githubusercontent.com/3606933/33171183-3eb1f11a-d086-11e7-9fd5-0e7a0b3dac8f.png)
IPv4收集自以前版本使用过程中产生的文件。
ipv6不灵的朋友，十有八九是【teredo服务器】被禁了。
下面给大家几个还能用的，括号中的数字是ping值：
teredo-debian.remlab.net （能用 242）
teredo.remlab.net （能用 244）
teredo.iks-jena.de  （能用 184）
teredo2.remlab.net  （能用 240）
teredo.trex.fi (能用 347)

**Comment by gjbg1989** [comment]
MFF扫描时间长了就被断网😂

**Comment by gjbg1989** [comment]
貌似对你有效的IPv4对别人未必有效？

**Comment by wuwuti** [comment]
gjbg1989 说的有道理。

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced v4为0置成force_ipv4？找si ?

**Comment by wuwuti** [comment]
gjbg1989    茅台股价连跌5天 市值蒸发超千亿。风险就摆在那，你咋办？

**Comment by gjbg1989** [comment]
🤣不喝的懵逼ing

**Comment by eljake58** [comment]
请问如何设置使IP延迟只有100的，我ipv6有五千个，但是延迟两百多，三百

**Comment by gjbg1989** [comment]
貌似得有ipv4

**Comment by okaylabababa** [comment]
ipv4為什麼我是0

**Comment by guangziyun** [comment]
我的ipv6有5千8百多ip，但ipv4为0,问题出在哪里，求大神指教

**Comment by gjbg1989** [comment]
🤣在哪里——不是GFW？

**Comment by DEMON414** [comment]
IPV4的txt文件可以共享出来吗@wuwuti

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8587

**Comment by wuwuti** [comment]
要点：1、将老版中扫描出来的ip集中收集起来，导入。
2、关掉【自动调整扫描线程数】，最大扫描线程数设为5

**Comment by wlm2012** [comment]
你只将原来的ip导入了，是不是忘了检测ip的有效性？

**Comment by chendaihang** [comment]
挑一个通畅的teredo服务器可以试试https://github.com/XX-net/XX-Net/issues/8482

**Comment by roc1010kmt** [comment]
你這ipv4怎麼這麼多？

**Comment by whhxmwhh** [comment]
我的V4是个鸭蛋呀！～

**Comment by gjbg1989** [comment]
鸭蛋正常，所以才开启IPv6，這麼多的是神人，不可比😂

**Comment by fzwzs** [comment]
IPv4收集自以前版本使用过程中产生的文件。
ipv6不灵的朋友，十有八九是【teredo服务器】被禁了。
 下面给大家几个还能用的，括号中的数字是ping值：
teredo-debian.remlab.net （能用 242）
teredo.remlab.net （能用 244）
teredo.iks-jena.de （能用 184）
teredo2.remlab.net （能用 240）
teredo.trex.fi (能用 347)
