### ISSUE TITLE
ipv6每次开机或者从睡眠唤醒总是不能使用, 但是ipv6数量很多. 每当开机一段时间, 一般到中午左右就开始很流畅了

### ISSUE THREAD

**Issue by RJustice** [XX-net/XX-Net#8630]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
ipv6-tunnel: disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:1 ipv6:3978
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 250
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
每次开机或唤醒总是不能使用，那又是如何开启ipv6的？
莫非系统服务 IP Helper 及其“依存关系”的服务不是自动？

**Comment by RJustice** [comment]
IP Helper 是自启动无延时, 有一个IP 转换配置服务 是自启动有延时并且是触发启动.  不知道是不是这个关系

**Comment by gjbg1989** [comment]
开机或唤醒总是能使用的 IP 转换配置服务也是触发启动。“依存关系”的呢？

**Comment by gjbg1989** [comment]
use-ipv6: auto 貌似改 force_ipv6 可触发启动

**Comment by RJustice** [comment]
依存关系都是自启动无延时的, 很奇怪

**Comment by RJustice** [comment]
会不会我使用的teredo转换服务, 我使用的 win1710.ipv6.microsoft.com

**Comment by gjbg1989** [comment]
不会，正常的也是使用它
那又是如何开启ipv6的——没有答案

**Comment by gjbg1989** [comment]
不稳定倒是可换换

**Comment by RJustice** [comment]
force_ipv6之后好像稳定了 不再出现睡眠之后需要等待才能使用的情况了
