### ISSUE TITLE
升级3.8.3以后,配置页面内容缺失

### ISSUE THREAD

**Issue by peach5460** [XX-net/XX-Net#8631]
升级3.8.3以后,配置页面没有任何内容了
![image](https://user-images.githubusercontent.com/3350332/33191461-69349c1c-d0f4-11e7-85c3-abcd5ec9944b.png)
但是功能是正常的

**Comment by wpyok500** [comment]
等一段时间就好了。

**Comment by xxnet** [comment]
​没有做好IE 兼容，先用Chrome/firefox，下个版本修复

**Comment by gjbg1989** [comment]
右键重启 GAEProxy 在 firefox 57 内也是，稍侯就好
