### ISSUE TITLE
需要X-Tunnel流量的可以留个账号，我转让一些出来

### ISSUE THREAD

**Issue by buzheng** [XX-net/XX-Net#8632]
300多G，明年4月份到期，我用不了，需要的可以留个 X-Tunnel 账号

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8598

**Comment by DamingLake** [comment]
ijibeisite#gmail.com

**Comment by cellx-yuki** [comment]
cellx@21cn.com
Thanks!

**Comment by maarxv** [comment]
markpoleon@gmail.com

**Comment by wildcatstudio** [comment]
wilcatstudio@gmail.com

**Comment by maarxv** [comment]
qyizhe@icloud.com

**Comment by xxnet** [comment]
​鼓掌鼓掌！

**Comment by DEMON414** [comment]
wz.king414@gmail.com          多谢多谢

**Comment by gitGksgk** [comment]
lzhr

**Comment by geshou** [comment]
hjldq2005@gmail.com 
多谢多谢

**Comment by 935352** [comment]
935352@qq.com
谢谢啊

**Comment by inumo** [comment]
inumowy@gmail.com
非常感谢

**Comment by llan-ml** [comment]
llan.xjtu@foxmail.com
谢谢！好人一生平安！

**Comment by boyjdy** [comment]
boyjdy@gmail.com谢谢！

**Comment by mickeygogogo1** [comment]
mickeygogogo1@gmail.com

**Comment by buzheng** [comment]
@DamingLake @cellx-yuki @wildcatstudio @maarxv @DEMON414  @geshou @935352 @inumo @llan-ml @boyjdy @mickeygogogo1   
各位，每个人转了 8888M，如果不够再留言或者 Email: zhjiun#gmail.com

**Comment by pldeom** [comment]
mgydyzzz@163.com

**Comment by 3176491236** [comment]
3176491236@qq.com
感谢 感恩

**Comment by happyendin** [comment]
xllche@126.com 谢谢分享

**Comment by april4513** [comment]
joshuakongchao@gmail.com非常感谢

**Comment by wgqwgqwgq** [comment]
qq196304611@gmail.com
非常感谢

**Comment by 935352** [comment]
收到了，谢谢锤子

**Comment by gjbg1989** [comment]
锤子😱

**Comment by buzheng** [comment]
@pldeom @3176491236 @happyendin @april4513 @wgqwgqwgq 
各位，每人转了6666M

**Comment by langzc520** [comment]
langzc520@gmail.com,谢谢！

**Comment by aa630510847** [comment]
630510847@qq.com,多谢了

**Comment by gjbg1989** [comment]
https://twitter.com/szshu/status/933943449048334336

**Comment by cellx-yuki** [comment]
收到了，多谢！

**Comment by lkhtty** [comment]
nn0430@gmail.com,希望来一点谢

**Comment by happyendin** [comment]
谢谢，收到

**Comment by feizaituzhu** [comment]
fat.aborigines@gmail.com  THX

**Comment by shinco20** [comment]
shinco20@gmail.com  thanks

**Comment by DEMON414** [comment]
@buzheng 
已经收到，谢谢分享

**Comment by SaDanic** [comment]
fanzbiao@gmail.com
谢谢

**Comment by SaDanic** [comment]
谢谢了

**Comment by buzheng** [comment]
@langzc520 @aa630510847 @lkhtty @feizaituzhu @shinco20 @SaDanic 
各位，转了 2000M 给你们，先用着。

**Comment by zeroabc** [comment]
zerozhenpeng@gmail.com
感激不尽！

**Comment by buzheng** [comment]
@zeroabc  已转

**Comment by xiaobainnz** [comment]
lvxiao778@aliyun.com

**Comment by lkhtty** [comment]
谢谢

**Comment by buzheng** [comment]
@xiaobainnz 已转

**Comment by spvwh** [comment]
myspvwh#gmail.com
有没有都要谢谢

**Comment by zhengan** [comment]
547796984@qq.com

thanks

**Comment by RomanSmile** [comment]
@gjbg1989
怎么不见你伸手呢？你这个人有点意思！

**Comment by gjbg1989** [comment]
仅仅是你看不见而已🙃

**Comment by RomanSmile** [comment]
@ gjbg1989 
整理点数据，干了一天实在是累了，喝点茶，来这看看新闻，我进入这个帖子因为好玩，所以每个楼层都看的仔细，唯独没有你的账号啊，哈哈哈！
也是这流量对于你来说有什么用呢？

**Comment by gjbg1989** [comment]
🙃仅仅是你没看到而已🙃

**Comment by zjcxdcq** [comment]
45527564@qq.com
感谢感谢！

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33215300-327377b8-d16a-11e7-9aa4-0c7608a24199.png)

**Comment by gitgaojiasheng** [comment]
turboy@126.com, 谢谢

**Comment by citizentang** [comment]
wowtyqwow@163.com

**Comment by JeanMaritain** [comment]
changli7g@gmail.com

**Comment by buzheng** [comment]
@zhengan  你的账号不存在，你确认一下有没有输入错误。
@spvwh @zjcxdcq @gitgaojiasheng @citizentang @JeanMaritain  各位，转了1G给你们

**Comment by gubu000** [comment]
先谢谢lz  mawuxiaoqu@126.com

**Comment by wingswing0000** [comment]
楼主，不知现在还有流量不。这边谢谢先！
lgp828@gmail.com

**Comment by szylmzs** [comment]
szylmzs@163.com 谢谢 上次一不小心看片用完了

**Comment by yhhu2049** [comment]
1014062545@qq.com  谢谢楼主~！

**Comment by frozenmaple** [comment]
feng.qian@colorado.edu 谢谢楼主，最近写论文需要常翻墙

**Comment by spvwh** [comment]
@buzheng 收到，谢谢

**Comment by ffdzpilot** [comment]
不知道还有吗？     lycwd01@gmail.com   
谢谢！

**Comment by wanggang427** [comment]
47367484@163.com  谢谢老板！祝老板心想事成！

**Comment by wky2017** [comment]
wky111@163.com 还有流量吗？谢谢了

**Comment by zhengan** [comment]
不好意思，忘记注册了。现在已经注册了。547796984@qq.com
感谢

**Comment by luweitu** [comment]
992671990@qq.com 谢谢转让

**Comment by blueSky1991** [comment]
谢谢装让    dongdongzhang1991@gmail.com

**Comment by scljy** [comment]
scljy@msn.com

**Comment by heeyongman** [comment]
heyongman95@gmail.com
给我也来点吧，谢谢你咯

**Comment by dragonstyle2** [comment]
394173771@qq.com
谢谢楼主，急需写论文。

**Comment by buzheng** [comment]
@gubu000 @wingswing0000 @szylmzs @yhhu2049 @frozenmaple @ffdzpilot @wanggang427 @wky2017 @zhengan  @luweitu @heeyongman @dragonstyle2 几位，给你们转了，你们看一下
@blueSky1991 @scljy 二位，你们的邮箱不对

**Comment by blueSky1991** [comment]
不好意思啊 m18210681011@163.com 谢谢转让

**Comment by szylmzs** [comment]
多谢楼主，收到了

**Comment by buzheng** [comment]
@blueSky1991 转给你了

**Comment by blueSky1991** [comment]
多谢楼主

**Comment by wingswing0000** [comment]
主要是使用scholar，已收到，非常感谢楼主！

**Comment by devkevinhou** [comment]
394620369@qq.com  还有的话 来点 谢谢楼主

**Comment by dragonstyle2** [comment]
@buzheng 谢谢兄弟啦。

**Comment by buzheng** [comment]
@devkevinhou 转给你了

**Comment by heeyongman** [comment]
谢谢啦，哈哈

**Comment by georgeQaQ** [comment]
122402666@qq.com 谢谢

**Comment by buzheng** [comment]
@georgeQaQ 已转

**Comment by alphabet719** [comment]
alphabet719@gmail.com。Thanks!😃

**Comment by Jan9th** [comment]
用了半年了 还没体验过两者的差距

**Comment by buzheng** [comment]
@alphabet719 已转

**Comment by guanghualiu** [comment]
light.where@gmail.com

**Comment by zzj0001** [comment]
给我一个，zhongzhuojun001@gmail.com

**Comment by saintethan** [comment]
jakepink2017@gmail.com，谢谢。

**Comment by buzheng** [comment]
@guanghualiu @zzj0001 @saintethan 已转

**Comment by saintethan** [comment]
@buzheng 多谢，收到了。

**Comment by alphabet719** [comment]
@buzheng ，多谢！收到！

**Comment by zzj0001** [comment]
谢谢楼主，收到了，谢谢啦

**Comment by halowtry** [comment]
不懂计算机语言，也没法给项目做什么贡献，只能捐点AppID。
我也无耻的做回伸手党，楼主如果还有流量也送我一些吧，感谢。trylmy@gmail.com

**Comment by buzheng** [comment]
@halowtry 已转

**Comment by helianvine** [comment]
helianvine@gmail.com, 谢谢楼主~

**Comment by buzheng** [comment]
@helianvine 已转

**Comment by king2333** [comment]
a6268626@vip.qq.com，多谢大哥

**Comment by starskero** [comment]
starkero@gmail.com

**Comment by buzheng** [comment]
@king2333 @starskero 已转

**Comment by starskero** [comment]
@buzheng 已收到，谢谢

**Comment by yhhu2049** [comment]
谢谢楼主！

2017-11-30 13:43 GMT+08:00 starskero <notifications@github.com>:

**Comment by lw8228** [comment]
lw8228@gmail.com 谢谢lz！

**Comment by Rui-Sun** [comment]
sunrui1992@foxmail.com

**Comment by Rui-Sun** [comment]
sunrui1992@foxmail.com
谢谢楼主！

**Comment by buzheng** [comment]
@lw8228 @Rui-Sun 已转

**Comment by dongman1988** [comment]
dongman1988@msn.com 谢谢了

**Comment by aa630510847** [comment]
@buzheng 已收到，非常感谢

**Comment by buzheng** [comment]
@dongman1988 已转 ^_^

**Comment by Rui-Sun** [comment]
@buzheng 已收到，谢谢~

**Comment by sn218** [comment]
如果还有流量请送一些吧，sn1000@sohu.com，谢谢！

**Comment by buzheng** [comment]
@sn218 已转

**Comment by kingjia1989** [comment]
kingjia1989@gmail.com
谢谢楼主！

**Comment by sn218** [comment]
收到了，非常感谢！

**Comment by 852468826** [comment]
aaaaaaaa15002946542@gmail.com  谢谢！

**Comment by buzheng** [comment]
@852468826 已转

**Comment by memege666** [comment]
如果还有流量麻烦送一点吧，1175723816@qq.com，谢谢

**Comment by buzheng** [comment]
@memege666 已转

**Comment by memege666** [comment]
@buzheng谢谢楼主

**Comment by zwtocn** [comment]
不知道还有没有 帐号lucjym@hotmail.com 谢谢楼主如此大方

**Comment by buzheng** [comment]
@zwtocn 已转

**Comment by water2049** [comment]
243084772@qq.com


谢谢

**Comment by buzheng** [comment]
@water2049  已转

**Comment by hookk** [comment]
z62578136@163.com. 谢谢。

**Comment by laosunxu** [comment]
如果还有流量希望能送一些：doudousun2012@gmail.com，感谢楼主慷慨相助！

**Comment by buzheng** [comment]
@hookk  你这个账户不存在

**Comment by buzheng** [comment]
@laosunxu  已转

**Comment by laosunxu** [comment]
@buzheng谢谢楼主！新年快乐！

**Comment by givemeyourmi1k** [comment]
440347@gmail.com 
谢谢楼主！

**Comment by buzheng** [comment]
@givemeyourmi1k 已转

**Comment by zicai1026** [comment]
xt-r@zicai.uu.me
谢谢大佬！新年快乐！ @buzheng

**Comment by givemeyourmi1k** [comment]
@buzheng 
谢谢楼主送流量

**Comment by buzheng** [comment]
@zicai1026 已转

**Comment by lyonferris** [comment]
lyonferris@outlook.com 谢谢楼主！

**Comment by buzheng** [comment]
@lyonferris 已转

**Comment by yuqi33** [comment]
yuqi33@gmail.com求流量,谢谢!

**Comment by githubcdh** [comment]
the_9city@126.com  谢谢

**Comment by buzheng** [comment]
@yuqi33 @githubcdh  已转

**Comment by yuqi33** [comment]
@buzheng 收到，多谢！

**Comment by kittycheny** [comment]
kittychenyuzhong@gmail.com 
thank you for sharing!

**Comment by buzheng** [comment]
@kittycheny  已转

**Comment by gjbg1989** [comment]
😱流量无限？

**Comment by buzheng** [comment]
@gjbg1989 有限，是我自己买了一个季度的，又用不了，就分享一些出来，现在剩的也不是很多了。

**Comment by xxnet** [comment]
@buzheng
  告诉我你的帐号，我给你转一些

**Comment by WhiteSwordSu** [comment]
2923171996@qq.com,太棒了！

**Comment by buzheng** [comment]
@xxnet  多谢了，我自己的还足够用。
@WhiteSwordSu 给你转了一点

**Comment by WhiteSwordSu** [comment]
那么快，非常感谢

**Comment by huangkio** [comment]
huangkaiu@gmail.com 感谢

**Comment by buzheng** [comment]
@huangkio  已转

**Comment by Next2Youhk** [comment]
cycong1997@gmail.com

**Comment by masamibf** [comment]
masamihusband@gmail.com

**Comment by buzheng** [comment]
@Next2Youhk @masamibf 已转

**Comment by Next2Youhk** [comment]
本来剩下不到100M，这几天一直省着用，现在又有流量了，真的非常非常感谢@buzheng

**Comment by zerozzp** [comment]
zerozzp@gmail.com 有没有也先谢过楼主了

**Comment by buzheng** [comment]
@zeroabc 已转

**Comment by dive2Pro** [comment]
toylucklebo@gmail.com

**Comment by 285571052** [comment]
qhy285571052@gmail.com 十分感谢

**Comment by gjbg1989** [comment]
😱约2小时测试：强烈建议用回 3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱

**Comment by buzheng** [comment]
@dive2Pro 已转给你
@285571052 你这个账号不存在，你看看是否输入正确

**Comment by 285571052** [comment]
@buzheng 才发现注册的账号多打了个2 , 我重新注册了, 还是这个 qhy285571052@gmail.com ,麻烦了

**Comment by buzheng** [comment]
@285571052 转给你了，你看一下

**Comment by buzheng** [comment]
大家流量不够的可以给我发邮件或者直接在这里留言。

**Comment by shuiRong** [comment]
beijindaoyu1@sina.com
多谢兄dei

**Comment by buzheng** [comment]
@shuiRong  已经转了，你可以用了

**Comment by zdd1007** [comment]
zdd1007@gmail.com

还有吗  来一点    谢谢啦

**Comment by buzheng** [comment]
@zdd1007 已转，查看一下

**Comment by SupremeWolf** [comment]
huyingqiwolf@163.com  谢谢

**Comment by buzheng** [comment]
@SupremeWolf  转了，请查看一下

**Comment by SupremeWolf** [comment]
Thank you

发送自 Windows 10 版邮件应用

发件人: 不争
发送时间: 2018年3月26日 9:39
收件人: XX-net/XX-Net
抄送: SupremeWolf; Mention
主题: Re: [XX-net/XX-Net] 需要X-Tunnel流量的可以留个账号，我转让一些出来 (#8632)

@SupremeWolf 转了，请查看一下

**Comment by pingtouzi** [comment]
pingtouzizi@hotmail.com   THX~~

**Comment by AnyWAT** [comment]
😜LS囤货？

**Comment by jianjhih** [comment]
jianjhih#gmail.com 謝謝

**Comment by buzheng** [comment]
@jianjhih  已转

**Comment by aruling** [comment]
xiruling881012@gmail.com

**Comment by buzheng** [comment]
@aruling  已转

**Comment by Stevenmfg** [comment]
fangangmengfangangmeng@gmail.com  谢谢

**Comment by Jerry-Chow** [comment]
jerry.chow✉️msn.com
谢谢

**Comment by SeaHOH** [comment]
> 4月份到期
