### ISSUE TITLE
XX-net启动失败，提示脚本错误

### ISSUE THREAD

**Issue by hygh** [XX-net/XX-Net#8634]
更新xx-net至最新版本3.8.3后，不知是出了什么问题，本来设置为开机启动的xx-net在重启开机启动时，提示脚本错误。

> 提示框名称为：Windows Script Hosts

脚本：D:\*****\XX-Net\start.vbs
行：   19
字符：9
错误：输入超出了文件尾
代码：800A003E
源：   Microsoft VBSCript运行时错误

手动运行start.vbs和start.bat都弹出同样的对话框。

更新3.8.3后，曾重启过几次，没有出现问题。
这次可能的问题，不知是不是点了一下设置里面的设置本地客户端。

求如何解决？

**Comment by hygh** [comment]
抱歉，已解决。
3.8.3版本的配置里面系统升级选项卡里面新增加的设置本地版本，把code文件夹里面的version.txt里面的版本后设置为该界面里上面的输入版本框。输入框里面默认是空的，所以version.txt也是空的了。将version.txt里面改成当前版本号3.8.3，即可正常启动xx-net了。

**Comment by xxnet** [comment]
保存时​已经加了检查，不存在的版本不会保存
@wooowooo

**Comment by gjbg1989** [comment]
重新解压覆盖后ok
![default](https://user-images.githubusercontent.com/13290970/33194608-132f8eae-d10c-11e7-9b8d-2f1e34ac98b8.PNG)
