### ISSUE TITLE
请问可以过滤只用延迟值低的IP吗

### ISSUE THREAD

**Issue by eljake58** [XX-net/XX-Net#8638]
有六千个IPV6，但是延迟值不太理想，要想youtube 720p秒开，可看直播，ip延迟一般要多少以下？
如何过滤设置，谢谢

**Comment by RomanSmile** [comment]
250---400

**Comment by luochuwei** [comment]
同求方法

如何过滤

**Comment by gjbg1989** [comment]
😂笨法：
1、 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查所有IP
2、剩余数为0后导出IP——运行，全选后复制
3、退出XX-Net，将good_ip.txt改名或删除
4、启动XX-Net，导入IP——粘贴后运行
再看IP延时，是不是从近300跑到了100？

**Comment by xxnet** [comment]
​这个是假象，因为导入的ip，默认是100

**Comment by gjbg1989** [comment]
😱超2小时的运行，还是假象？

**Comment by xxnet** [comment]
​你在高级里，重新检查一遍ip，理论上结果会回到之前的状态

**Comment by gjbg1989** [comment]
假、假、假😭

**Comment by gjbg1989** [comment]
https://twitter.com/qdsbm/status/934676667343175680
