### ISSUE TITLE
更新到最新版咋不显示信息了

### ISSUE THREAD

**Issue by wbj0815** [XX-net/XX-Net#8642]
![image](https://user-images.githubusercontent.com/22046776/33199209-437ae46e-d12a-11e7-98ec-2be7f6f5a852.png)
点开"展开详细信息"一刷新又成这样了

**Comment by wbj0815** [comment]
在楼下找到答案啦= =

**Comment by gjbg1989** [comment]
😁刚从楼下上来，没看到啊
