### ISSUE TITLE
笨法减小IP延时——有几千个IPV6后

### ISSUE THREAD

**Issue by gjbg1989** [XX-net/XX-Net#8666]
1、 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查所有IP
2、剩余数为0后导出IP——运行，全选后复制
3、退出XX-Net，将good_ip.txt改名或删除
4、启动XX-Net，导入IP——粘贴后运行
再看IP延时，是不是从近300跑到了100？

**Comment by gjbg1989** [comment]
🤣有效IP数与总IP数存在一定差距后，这样处理一下。。。

**Comment by wlm2012** [comment]
你再点一下检查有效ip就会发现延时又变回来了，延时变成100的原因是因为直接导入的ip默认延时100，而不是实际是100

**Comment by gjbg1989** [comment]
呵呵，此时次刻（自操作已过2小时）

![default](https://user-images.githubusercontent.com/13290970/33237557-9c34743e-d2b1-11e7-8b71-eff6d762d6fc.png)
