### ISSUE TITLE
github.com/goagent/goagent继shadowsocks后删了，xxnet要小心了。

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#867]
如题

**Comment by jackbull** [comment]
XX 的热门程度不及上述二者吧

**Comment by WLZLCX** [comment]
习大大的中国梦，呵呵

**Comment by chumuye** [comment]
加油坚持住！推翻这堵该死的墙！

**Comment by zjhzxhz** [comment]
果然有人提到这个问题~
我想说是不是准备一些备用方案呢~

**Comment by zjhzxhz** [comment]
在[开源中国](www.oschina.net/news/65566/github-ddos)上有人推荐了一个工具: [Lantern](https://getlantern.org)

It seems good as well.

<img width="1280" alt="Lantern" src="https://cloud.githubusercontent.com/assets/1730504/9484588/fd83cffa-4be0-11e5-8fa8-7e9a852216db.png">

**Comment by Loyalists** [comment]
貌似pluslu在外国，应该不会被跨国查水表吧

**Comment by lichunqiang** [comment]
Lantern 只能支持浏览器吗？

**Comment by xxnet** [comment]
只支持http代理，虽然理论上可以实现为socks，但没有

2015-08-27 16:10 GMT+08:00 李某某 <notifications@github.com>:

**Comment by lichunqiang** [comment]
那还不如xxnet呢 ;+1:

**Comment by lygoing** [comment]
没有xxnet 好
