### ISSUE TITLE
ipv6 已开启可以使用浏览器访问网络（包括外网），但使用的软件都无法连接网络，

### ISSUE THREAD

**Issue by yangxiRespect** [XX-net/XX-Net#8674]
重新安装了win7系统。xx-net版本3.8.4，使用disable_ipv6开启ipv6，可以正常访问外网。
重启系统之后所有的软件都无法连接网络。steam，360什么的都不行

GAEProxy状态信息

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:6001 ipv4:0 ipv6:5999
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:100 h2:0
scan-ip-thread-num: 200
ip-quality: 296
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

----------------------------------------------------------

**Comment by gjbg1989** [comment]
重启系统之后（是没有运行XX-Net？）所有的软件都无法连接网络——如是，取消IE的代理设置，或启动XX-Net并右键“取消全局代理”，退出XX-Net再试。。。

**Comment by simonjoelucky** [comment]
xx-net如果是在取消全局代理状态，浏览器使用stitchomega插件的话，确实是只能在浏览器访问墙外内容的。如果想所有的软件都能够翻墙，那么右键XX-NET托盘选择全局PAC智能代理即可
