### ISSUE TITLE
ipv6突然停止响应，x-tunnel也无法登陆

### ISSUE THREAD

**Issue by saintethan** [XX-net/XX-Net#8675]
* 简单描述遇到的问题：
晚八点左右，ipv6突然无法访问，x-tunnel无法登陆

* 做过哪些尝试：
重启xx-net和系统，重置网络设置，均无效。

* 请贴出对应模块的状态页
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:5949
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 276
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 请贴出相关的日志
xx-net log：
Nov 26 22:18:04.587 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.658 - [DEBUG] connect 2607:f8b0:401e:14::f fail:error(10051, '')
Nov 26 22:18:04.658 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.699 - [DEBUG] connect 2607:f8b0:401e:17::9 fail:error(10051, '')
Nov 26 22:18:04.699 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.740 - [DEBUG] connect 2607:f8b0:401e:17::7 fail:error(10051, '')
Nov 26 22:18:04.740 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.781 - [DEBUG] connect 2607:f8b0:4017:19::10 fail:error(10051, '')
Nov 26 22:18:04.781 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.822 - [DEBUG] connect 2607:f8b0:401c:5::7 fail:error(10051, '')
Nov 26 22:18:04.822 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.863 - [DEBUG] connect 2607:f8b0:4017:22::c fail:error(10051, '')
Nov 26 22:18:04.863 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.955 - [DEBUG] connect 2607:f8b0:401e:17::12 fail:error(10051, '')
Nov 26 22:18:04.955 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:04.996 - [DEBUG] connect 2607:f8b0:401e:17::17 fail:error(10051, '')
Nov 26 22:18:04.996 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.037 - [DEBUG] connect 2607:f8b0:4016:a::10 fail:error(10051, '')
Nov 26 22:18:05.037 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.078 - [DEBUG] connect 2607:f8b0:400f:3::8 fail:error(10051, '')
Nov 26 22:18:05.078 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.119 - [DEBUG] connect 2607:f8b0:4016:1::10 fail:error(10051, '')
Nov 26 22:18:05.119 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.151 - [DEBUG] connect 2607:f8b0:4007:1c::b fail:error(10051, '')
Nov 26 22:18:05.151 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.202 - [DEBUG] connect 2607:f8b0:400a:5::11 fail:error(10051, '')
Nov 26 22:18:05.202 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.285 - [DEBUG] connect 2607:f8b0:4016:1::b fail:error(10051, '')
Nov 26 22:18:05.285 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.354 - [DEBUG] connect 2607:f8b0:4004:23::e fail:error(10051, '')
Nov 26 22:18:05.354 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.405 - [DEBUG] connect 2607:f8b0:401e:15::11 fail:error(10051, '')
Nov 26 22:18:05.405 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.447 - [DEBUG] connect 2607:f8b0:4016:10::12 fail:error(10051, '')
Nov 26 22:18:05.447 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.487 - [DEBUG] connect 2607:f8b0:401e:17::15 fail:error(10051, '')
Nov 26 22:18:05.487 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.528 - [DEBUG] connect 2607:f8b0:401e:18::d fail:error(10051, '')
Nov 26 22:18:05.528 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.569 - [DEBUG] connect 2607:f8b0:401e:18::13 fail:error(10051, '')
Nov 26 22:18:05.569 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.610 - [DEBUG] connect 2a00:1450:401c:1d::19 fail:error(10051, '')
Nov 26 22:18:05.610 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.651 - [DEBUG] connect 2607:f8b0:401e:14::9 fail:error(10051, '')
Nov 26 22:18:05.651 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.693 - [DEBUG] connect 2607:f8b0:4017:1e::10 fail:error(10051, '')
Nov 26 22:18:05.693 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.774 - [DEBUG] connect 2607:f8b0:401e:13::7 fail:error(10051, '')
Nov 26 22:18:05.774 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.813 - [DEBUG] connect 2607:f8b0:401e:18::14 fail:error(10051, '')
Nov 26 22:18:05.813 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.854 - [DEBUG] connect 2607:f8b0:401e:18::18 fail:error(10051, '')
Nov 26 22:18:05.854 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.883 - [DEBUG] connect 2607:f8b0:4002:5::14 fail:error(10051, '')
Nov 26 22:18:05.883 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.923 - [DEBUG] connect 2607:f8b0:4004:23::10 fail:error(10051, '')
Nov 26 22:18:05.923 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:05.975 - [DEBUG] connect 2607:f8b0:401e:17::f fail:error(10051, '')
Nov 26 22:18:05.975 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:06.047 - [DEBUG] connect 2607:f8b0:401e:17::d fail:error(10051, '')
Nov 26 22:18:06.047 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:06.088 - [DEBUG] connect 2607:f8b0:4016:11::15 fail:error(10051, '')
Nov 26 22:18:06.088 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:06.179 - [DEBUG] connect 2607:f8b0:4016:6::13 fail:error(10051, '')
Nov 26 22:18:06.179 - [DEBUG] report_connect_fail network fail
Nov 26 22:18:06.208 - [DEBUG] connect 2607:f8b0:401d:18::d fail:error(10051, '')
Nov 26 22:18:06.209 - [DEBUG] report_connect_fail network fail

x-tunnel log：
Nov 26 22:13:14.863 - [INFO] Socks5 server listen:127.0.0.1:1080.
Nov 26 22:13:26.065 - [DEBUG] x_tunnel force update info
Nov 26 22:14:02.958 - [WARNING] api:/login fail:status:602 t:36
Nov 26 22:15:29.181 - [DEBUG] session not running, try login..
Nov 26 22:16:02.202 - [WARNING] api:/login fail:status:602 t:33
Nov 26 22:16:02.202 - [WARNING] x-tunnel request_balance fail when create_conn:status:602
Nov 26 22:16:02.202 - [WARNING] create conn fail
Nov 26 22:18:21.352 - [DEBUG] x_tunnel force update info

Cloudflare front Log：
Nov 26 22:13:14.665 - [INFO] load ip range file:E:\XX-Net-3.7.17\code\3.8.4\x_tunnel\local\cloudflare_front\ip_range.txt
Nov 26 22:13:14.694 - [INFO] load google ip_list num:3000, gws num:3000
Nov 26 22:13:14.950 - [DEBUG] network is ok, cost:296 ms
Nov 26 22:13:15.939 - [INFO] updated cloudflare front domains from github.
Nov 26 22:13:26.289 - [DEBUG] create_ssl update ip:104.25.69.34 time:210 h2:1 sni:seemoviez.cf top:freenum.cf
Nov 26 22:13:26.790 - [DEBUG] create_ssl update ip:104.27.184.105 time:217 h2:1 sni:missww4.cf top:movistar.gq
Nov 26 22:13:27.298 - [DEBUG] create_ssl update ip:104.27.64.78 time:222 h2:1 sni:startup.global top:singlefly.tk
Nov 26 22:13:27.444 - [DEBUG] 104.25.69.34 worker close:status 403
Nov 26 22:13:27.445 - [WARNING] POST center.freenum.cf/login status:403 trace:0:start_request,0:get_task(1),265:get_worker(0):104.25.69.34,0:h2_req,19:start send header,0:start send left body,0:end send left body,85:h2_get_head,0:get_response,:0
Nov 26 22:13:27.514 - [DEBUG] create_ssl update ip:104.24.229.124 time:223 h2:1 sni:blatantskills.com top:c-term.tk
Nov 26 22:13:27.804 - [DEBUG] create_ssl update ip:104.16.127.166 time:230 h2:1 sni:seemoviez.cf top:freenum.cf
Nov 26 22:13:27.920 - [DEBUG] 104.27.184.105 worker close:status 403
Nov 26 22:13:27.920 - [WARNING] POST center.movistar.gq/login status:403 trace:0:start_request,0:get_task(0),380:get_worker(0):104.27.184.105,0:h2_req,1:start send header,0:start send left body,0:end send left body,92:h2_get_head,1:get_response,:0
Nov 26 22:13:28.024 - [DEBUG] create_ssl update ip:104.17.169.168 time:233 h2:1 sni:finditmp.com top:singlefly.tk
Nov 26 22:13:28.286 - [DEBUG] create_ssl update ip:104.17.243.185 time:212 h2:1 sni:ragnaride.com top:freenum.cf
Nov 26 22:13:28.424 - [DEBUG] 104.27.64.78 worker close:status 403
Nov 26 22:13:28.425 - [WARNING] POST center.singlefly.tk/login status:403 trace:0:start_request,0:get_task(0),410:get_worker(0):104.27.64.78,0:h2_req,1:start send header,0:start send left body,0:end send left body,88:h2_get_head,2:get_response,:0
Nov 26 22:13:28.513 - [DEBUG] 104.24.229.124 worker close:status 403
Nov 26 22:13:28.513 - [WARNING] POST center.c-term.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.24.229.124,0:h2_req,1:start send header,0:start send left body,0:end send left body,82:h2_get_head,1:get_response,:0
Nov 26 22:13:28.558 - [DEBUG] create_ssl update ip:104.19.205.85 time:256 h2:1 sni:switchsitiosweb.com top:movistar.gq
Nov 26 22:13:28.700 - [DEBUG] 104.16.127.166 worker close:status 403
Nov 26 22:13:28.700 - [WARNING] POST center.freenum.cf/login status:403 trace:0:start_request,0:get_task(0),92:get_worker(0):104.16.127.166,0:h2_req,1:start send header,0:start send left body,0:end send left body,90:h2_get_head,0:get_response,:1
Nov 26 22:13:28.714 - [DEBUG] create_ssl update ip:104.25.237.101 time:198 h2:1 sni:daniel-latta.review top:movistar.gq
Nov 26 22:13:28.833 - [DEBUG] create_ssl update ip:162.159.216.196 time:257 h2:1 sni:happyfriendshipday2017i.com top:flar.tk
Nov 26 22:13:28.978 - [DEBUG] 104.17.169.168 worker close:status 403
Nov 26 22:13:28.978 - [WARNING] POST center.singlefly.tk/login status:403 trace:0:start_request,0:get_task(0),164:get_worker(0):104.17.169.168,0:h2_req,0:start send header,0:start send left body,0:end send left body,110:h2_get_head,0:get_response,:1
Nov 26 22:13:29.073 - [DEBUG] create_ssl update ip:104.28.72.193 time:266 h2:1 sni:audiodim.me top:c-term.tk
Nov 26 22:13:29.190 - [DEBUG] 104.17.243.185 worker close:status 403
Nov 26 22:13:29.190 - [WARNING] POST center.freenum.cf/login status:403 trace:0:start_request,0:get_task(0),113:get_worker(0):104.17.243.185,0:h2_req,3:start send header,0:start send left body,0:end send left body,89:h2_get_head,0:get_response,:1
Nov 26 22:13:29.269 - [DEBUG] create_ssl update ip:104.27.211.120 time:242 h2:1 sni:jentheeditor.com top:c-term.tk
Nov 26 22:13:29.307 - [DEBUG] create_ssl update ip:104.28.180.175 time:230 h2:1 sni:brain.ink top:c-term.tk
Nov 26 22:13:29.419 - [DEBUG] 104.19.205.85 worker close:status 403
Nov 26 22:13:29.419 - [WARNING] POST center.movistar.gq/login status:403 trace:0:start_request,0:get_task(0),130:get_worker(0):104.19.205.85,0:h2_req,4:start send header,0:start send left body,0:end send left body,92:h2_get_head,0:get_response,:0
Nov 26 22:13:29.507 - [DEBUG] create_ssl update ip:104.17.141.20 time:219 h2:1 sni:risk.co.uk top:dragon-dreamer.com
Nov 26 22:13:29.652 - [DEBUG] 104.25.237.101 worker close:status 403
Nov 26 22:13:29.653 - [WARNING] POST center.movistar.gq/login status:403 trace:0:start_request,0:get_task(0),128:get_worker(0):104.25.237.101,0:h2_req,8:start send header,0:start send left body,1:end send left body,91:h2_get_head,0:get_response,:2
Nov 26 22:13:29.746 - [DEBUG] 162.159.216.196 worker close:status 403
Nov 26 22:13:29.748 - [WARNING] POST center.flar.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):162.159.216.196,0:h2_req,0:start send header,0:start send left body,0:end send left body,90:h2_get_head,0:get_response,:0
Nov 26 22:13:29.814 - [DEBUG] create_ssl update ip:172.64.167.226 time:234 h2:1 sni:mozgcyhjj734z75f.xyz top:freenum.cf
Nov 26 22:13:29.828 - [DEBUG] create_ssl update ip:104.19.29.118 time:268 h2:1 sni:slooki.com top:flar.tk
Nov 26 22:13:29.935 - [DEBUG] 104.28.72.193 worker close:status 403
Nov 26 22:13:29.935 - [WARNING] POST center.c-term.tk/login status:403 trace:0:start_request,0:get_task(0),86:get_worker(0):104.28.72.193,0:h2_req,1:start send header,0:start send left body,0:end send left body,95:h2_get_head,0:get_response,:0
Nov 26 22:13:30.090 - [DEBUG] create_ssl update ip:104.19.130.64 time:254 h2:1 sni:parmaj.com top:superx.gq
Nov 26 22:13:30.324 - [DEBUG] create_ssl update ip:104.27.140.89 time:239 h2:1 sni:jentheeditor.com top:c-term.tk
Nov 26 22:13:30.331 - [DEBUG] create_ssl update ip:104.25.24.250 time:257 h2:1 sni:my-sub-shop.site top:flar.tk
Nov 26 22:13:30.538 - [DEBUG] create_ssl update ip:104.28.140.192 time:267 h2:1 sni:drafabianamello.com top:flar.tk
Nov 26 22:13:30.547 - [DEBUG] create_ssl update ip:104.16.138.56 time:238 h2:1 sni:drafabianamello.com top:flar.tk
Nov 26 22:13:30.611 - [DEBUG] create_ssl update ip:108.162.253.222 time:890 h2:1 sni:planningwales.com top:superx.gq
Nov 26 22:13:30.765 - [DEBUG] create_ssl update ip:104.25.57.22 time:256 h2:1 sni:denatran.net top:freenum.cf
Nov 26 22:13:37.361 - [WARNING] h2 timeout 104.25.69.34 task_trace:0:start_request,0:get_task(1),265:get_worker(0):104.25.69.34,0:h2_req,19:start send header,0:start send left body,0:end send left body,85:h2_get_head,0:get_response,:9916 worker_trace: processed:1, h2.stream_num:0, sni:seemoviez.cf
Nov 26 22:13:37.832 - [WARNING] h2 timeout 104.27.184.105 task_trace:0:start_request,0:get_task(0),380:get_worker(0):104.27.184.105,0:h2_req,1:start send header,0:start send left body,0:end send left body,92:h2_get_head,1:get_response,:9911 worker_trace: processed:1, h2.stream_num:0, sni:missww4.cf
Nov 26 22:13:38.338 - [WARNING] h2 timeout 104.27.64.78 task_trace:0:start_request,0:get_task(0),410:get_worker(0):104.27.64.78,0:h2_req,1:start send header,0:start send left body,0:end send left body,88:h2_get_head,2:get_response,:9914 worker_trace: processed:1, h2.stream_num:0, sni:startup.global
Nov 26 22:13:38.433 - [WARNING] h2 timeout 104.24.229.124 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.24.229.124,0:h2_req,1:start send header,0:start send left body,0:end send left body,82:h2_get_head,1:get_response,:9921 worker_trace: processed:1, h2.stream_num:0, sni:blatantskills.com
Nov 26 22:13:38.615 - [WARNING] h2 timeout 104.16.127.166 task_trace:0:start_request,0:get_task(0),92:get_worker(0):104.16.127.166,0:h2_req,1:start send header,0:start send left body,0:end send left body,90:h2_get_head,0:get_response,:9916 worker_trace: processed:1, h2.stream_num:0, sni:seemoviez.cf
Nov 26 22:13:38.872 - [WARNING] h2 timeout 104.17.169.168 task_trace:0:start_request,0:get_task(0),164:get_worker(0):104.17.169.168,0:h2_req,0:start send header,0:start send left body,0:end send left body,110:h2_get_head,0:get_response,:9895 worker_trace: processed:1, h2.stream_num:0, sni:finditmp.com
Nov 26 22:13:39.105 - [WARNING] h2 timeout 104.17.243.185 task_trace:0:start_request,0:get_task(0),113:get_worker(0):104.17.243.185,0:h2_req,3:start send header,0:start send left body,0:end send left body,89:h2_get_head,0:get_response,:9916 worker_trace: processed:1, h2.stream_num:0, sni:ragnaride.com
Nov 26 22:13:39.333 - [WARNING] h2 timeout 104.19.205.85 task_trace:0:start_request,0:get_task(0),130:get_worker(0):104.19.205.85,0:h2_req,4:start send header,0:start send left body,0:end send left body,92:h2_get_head,0:get_response,:9914 worker_trace: processed:1, h2.stream_num:0, sni:switchsitiosweb.com
Nov 26 22:13:39.567 - [WARNING] h2 timeout 104.25.237.101 task_trace:0:start_request,0:get_task(0),128:get_worker(0):104.25.237.101,0:h2_req,8:start send header,0:start send left body,1:end send left body,91:h2_get_head,0:get_response,:9915 worker_trace: processed:1, h2.stream_num:0, sni:daniel-latta.review
Nov 26 22:13:39.662 - [WARNING] h2 timeout 162.159.216.196 task_trace:0:start_request,0:get_task(0),0:get_worker(0):162.159.216.196,0:h2_req,0:start send header,0:start send left body,0:end send left body,90:h2_get_head,0:get_response,:9914 worker_trace: processed:1, h2.stream_num:0, sni:happyfriendshipday2017i.com
Nov 26 22:13:39.846 - [WARNING] h2 timeout 104.28.72.193 task_trace:0:start_request,0:get_task(0),86:get_worker(0):104.28.72.193,0:h2_req,1:start send header,0:start send left body,0:end send left body,95:h2_get_head,0:get_response,:9911 worker_trace: processed:1, h2.stream_num:0, sni:audiodim.me
Nov 26 22:17:29.523 - [DEBUG] 104.28.180.175 _consume_single_frame:ConnectionResetError(), inactive time:240
Nov 26 22:17:29.523 - [DEBUG] 104.28.180.175 worker close:disconnect:ConnectionResetError()
Nov 26 22:17:29.523 - [DEBUG] 104.27.211.120 _consume_single_frame:ConnectionResetError(), inactive time:240
Nov 26 22:17:29.523 - [DEBUG] 104.27.211.120 worker close:disconnect:ConnectionResetError()
Nov 26 22:17:29.744 - [DEBUG] 104.17.141.20 _consume_single_frame:ConnectionResetError(), inactive time:240
Nov 26 22:17:29.744 - [DEBUG] 104.17.141.20 worker close:disconnect:ConnectionResetError()
Nov 26 22:17:30.121 - [DEBUG] 172.64.167.226 _consume_single_frame:ConnectionResetError(), inactive time:240
Nov 26 22:17:30.121 - [DEBUG] 172.64.167.226 worker close:disconnect:ConnectionResetError()
Nov 26 22:17:30.137 - [DEBUG] 104.19.29.118 _consume_single_frame:ConnectionResetError(), inactive time:240
Nov 26 22:17:30.137 - [DEBUG] 104.19.29.118 worker close:disconnect:ConnectionResetError()
Nov 26 22:18:30.360 - [DEBUG] 104.16.138.56 close:get_timeout
Nov 26 22:18:30.361 - [DEBUG] 104.27.140.89 close:get_timeout
Nov 26 22:18:30.361 - [DEBUG] 104.19.130.64 close:get_timeout
Nov 26 22:18:30.362 - [DEBUG] 104.25.57.22 close:get_timeout
Nov 26 22:18:30.363 - [DEBUG] 104.25.24.250 close:get_timeout
Nov 26 22:18:30.377 - [DEBUG] 104.28.140.192 close:get_timeout
Nov 26 22:18:30.398 - [DEBUG] 108.162.253.222 close:get_timeout
Nov 26 22:18:30.659 - [DEBUG] create_ssl update ip:104.25.69.34 time:257 h2:1 sni:bookshop14.ru top:dragon-dreamer.com
Nov 26 22:18:31.106 - [DEBUG] create_ssl update ip:104.27.184.105 time:236 h2:1 sni:incisivecdn.com top:dragon-dreamer.com
Nov 26 22:18:31.628 - [DEBUG] create_ssl update ip:104.27.64.78 time:258 h2:1 sni:householdd.cf top:superx.gq
Nov 26 22:18:31.907 - [DEBUG] create_ssl update ip:104.24.229.124 time:246 h2:1 sni:bcstandart.ru top:dragon-dreamer.com
Nov 26 22:18:32.102 - [DEBUG] create_ssl update ip:104.16.127.166 time:227 h2:1 sni:empiretaxirva.com top:freenum.cf
Nov 26 22:18:32.360 - [DEBUG] create_ssl update ip:104.17.169.168 time:250 h2:1 sni:cnk8081toloac.ga top:c-term.tk
Nov 26 22:18:32.485 - [DEBUG] 104.25.69.34 worker close:status 403
Nov 26 22:18:32.485 - [WARNING] POST center.dragon-dreamer.com/login status:403 trace:0:start_request,0:get_task(302),11:get_worker(0):104.25.69.34,0:h2_req,3:start send header,0:start send left body,0:end send left body,104:h2_get_head,0:get_response,:0
Nov 26 22:18:32.528 - [DEBUG] connect 104.17.243.185 fail:[('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')] cost:155
Nov 26 22:18:32.528 - [DEBUG] report_connect_fail:104.17.243.185
Nov 26 22:18:32.782 - [DEBUG] create_ssl update ip:104.19.205.85 time:250 h2:1 sni:cvhsyu.cf top:movistar.gq
Nov 26 22:18:32.854 - [DEBUG] create_ssl update ip:104.25.237.101 time:225 h2:1 sni:klompen-scherjon.nl top:flar.tk
Nov 26 22:18:42.384 - [WARNING] h2 timeout 104.25.69.34 task_trace:0:start_request,0:get_task(302),11:get_worker(0):104.25.69.34,0:h2_req,3:start send header,0:start send left body,0:end send left body,104:h2_get_head,0:get_response,:9900 worker_trace: processed:1, h2.stream_num:0, sni:bookshop14.ru
Nov 26 22:18:42.888 - [DEBUG] ip:104.17.243.185 real fail

**Comment by gjbg1989** [comment]
任何程序停止响应，退出、结束进程，重新启动再试，或许就好了😂

**Comment by saintethan** [comment]
@gjbg1989 试过了，无效。请问能从日志里看出是什么原因么？

**Comment by gjbg1989** [comment]
开不懂长篇。。。use-ipv6: auto 改成 指使用ipv6或许触发正常。或
运行 netsh interface ipv6 show teredo 贴结果

**Comment by gjbg1989** [comment]
#8620 bat自动换服务器

**Comment by saintethan** [comment]
@gjbg1989 刚才按照你说的试了一下，现在还是不好使。

C:\Users\Ethan>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant


C:\Users\Ethan>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

上面的是更换teredo服务器以前的，下面的是更换之后的。
附目前xx-net status：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:0 ipv6:5949
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 276
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by saintethan** [comment]
另外x-tunnel一直无法登陆，提示error 602。一整天都这个样子。

**Comment by gjbg1989** [comment]
状态 : dormant——休眠中，启动XX-Net即可，这正常后或许x-tunnel也会正常

**Comment by saintethan** [comment]
这就怪了，我的xx-net一直处于启动状态的。。

**Comment by gjbg1989** [comment]
状态 : dormant
ipv6-status: Fail——右键重启xx

**Comment by gjbg1989** [comment]
是怪，本来use-ipv6:的3种状态改变，我的可以触发断了的IPv6变正常

**Comment by gjbg1989** [comment]
或用DNS：9.9.9.9
google ipv6 dns:
2001:4860:4860::8888
2001:4860:4860::8844 能更稳定？

**Comment by saintethan** [comment]
@gjbg1989 删除xx-net本地包，重启电脑，重新下载最新的3.8.4，更换了teredo服务器，打开后好使了，x-tunnel也正常了。。虽然不知道啥原因。谢谢帮助。

**Comment by gjbg1989** [comment]
删除xx-net本地包，重启电脑——解压覆盖，不必重启✌
