### ISSUE TITLE
Reset GAEproxy 是否等同于Reset X-tunnel？？

### ISSUE THREAD

**Issue by hsrrtx** [XX-net/XX-Net#8683]
如果等同，那没啥问题了。
如果不等同，是否可以加一个选项菜单，因为需要经常在不同网络环境下上网。但是目前看起来X-tunnel貌似自动切换或者说重新连接的功能总是有点好像不是很好的样子，一般都需要退出XX-net然后在重新打开会比较顺利一点~~

**Comment by xxnet** [comment]
两个模块是不等同的，托盘菜单是可以改成重启所有模块。

另外​计划在WebUI里加个模块重启功能，每个模块开关的后面，放一个重启按钮。

**Comment by hsrrtx** [comment]
Reset each module~~多谢~~
