### ISSUE TITLE
建议支持 OAuth2 部署

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#87]
建议支持 https://cloud.google.com/appengine/docs/python/tools/uploadinganapp#Python_Password-less_login_with_OAuth2
更加安全，更加方便。

**Comment by yfdyh000** [comment]
补充，试了一下，目前的部署也挺方便的（两步验证-应用专用密码），因此可低优先级。

**Comment by xxnet** [comment]
是的，尽量简单。

有很多用户反馈部署很困难，不知道用git push 的方法，行不行：
http://googlecloudplatform.blogspot.com/2013/07/google-app-engine-hello-world-using.html

有空帮忙研究下

在 2015年3月30日 上午3:24，YFdyh000 <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
如果用git，用户需要的库可就大了（主要是Windows用户）。

**Comment by xxnet** [comment]
看来暂时没有更好的办法

2015-03-30 4:03 GMT-04:00 YFdyh000 <notifications@github.com>:

**Comment by yfdyh000** [comment]
怎么关掉了，这应该是个增强目标……

**Comment by xxnet** [comment]
OK，留下来，有机会改进

**Comment by yfdyh000** [comment]
https://github.com/XX-net/XX-Net/commit/940962ca627362fd306e61418ad074a65bcd9902 已实现。

**Comment by xxnet** [comment]
​拖了一年，终于逼这升级了。

才发现oauth解决了部署难题，老的版本都说不清楚让用户填哪个密码好，新SDK就没有这个问题了。

**Comment by simonasd** [comment]
cool，测试下。
