### ISSUE TITLE
尚未建立连接：certificate verify failed

### ISSUE THREAD

**Issue by edamame43** [XX-net/XX-Net#8712]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:2100 ipv4:0 ipv6:1138
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 1256
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

日志里的消息：
Nov 28 14:15:14.246 - [DEBUG] report_connect_fail:2607:f8b0:401e:14::12
Nov 28 14:15:14.707 - [DEBUG] connect 2607:f8b0:4017:11::18 fail:Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 是
本地映射           : 192.168.5.102:56364
外部 NAT 映射    : 180.156.139.47:56364

**Comment by gjbg1989** [comment]
proxy_state: Fail——代理失败
ca_state: Fail——或许由上面引发此错，试试在FQ浏览器内 http://127.0.0.1:8085/

**Comment by xxnet** [comment]
​系统菜单中的 LAN proxy 是不是开了？一般要关闭

**Comment by edamame43** [comment]
proxy state和ca_state在我切换switchyomega时会自动在fail和ok之间变换，但日志中certificate verify fail没有变化，不过当我把zoomalarm Firewall关掉以后，就一切正常了。。。是防火墙的原因？？

**Comment by xxnet** [comment]
​那就是防火墙劫持了https 连接，替换了证书。
必须关防火墙

**Comment by edamame43** [comment]
果然zoomalarm开起来后ipv6又全部fail了。。。如何可以共存？就用了一个防火墙，关掉裸机

**Comment by xxnet** [comment]
​防火墙里，看看能否关闭 https 过滤之类的功能
