### ISSUE TITLE
可以连google，但是无法连接mega.nz

### ISSUE THREAD

**Issue by a909042793** [XX-net/XX-Net#8716]
最新版开启了ipv6可以连接谷歌，但是无法连接mega.nz(国外云盘)，不知道什么原因，通过ss是可以访问的！

**Comment by foho8080** [comment]
我這裡可以

**Comment by onplus** [comment]
XX-Net日志 以及 Chrome F12的console和network内容

**Comment by a909042793** [comment]
这是日志：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.221 Safari/537.36 SE 2.X MetaSr 1.0
xxnet-version: 3.8.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:6001
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:39 h2:0
scan-ip-thread-num: 50
ip-quality: 299
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

谷歌浏览器的Console为空
谷歌浏览器netWork：
Request URL:https://mega.nz/
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:d57e2dd1-0c4a-4b64-be6d-31dd345ea9ee

**Comment by xxnet** [comment]
​估计是GAE的限制，用X-Tunnel吧
