### ISSUE TITLE
问一个关于ss的问题

### ISSUE THREAD

**Issue by Temmie-hOi** [XX-net/XX-Net#8723]
ss有没有什么方法在服务器端设置自动代理呢？除了电脑客户端其他客户端都只会所有流量都过代理，我希望能让它国内连接直连

**Comment by siaimes** [comment]
流量都已经到服务器端了就已经是代理了，只能在客户端设置是否代理！改用SSR吧[传送门](http://github.com/siaimes/BTGFW)

**Comment by onplus** [comment]
所有SS/SSR客户端都应该支持PAC/GFWList 功能，仔细找一找

**Comment by gjbg1989** [comment]
右键ss客户端——启用系统代理——系统代理模式——PAC 模式

**Comment by gjbg1989** [comment]
右键SSR客户端——系统代理模式——PAC 模式

**Comment by Peytonlan** [comment]
这个要求可大可小

你若Linux还能折腾下, 或可一说
客户端设备不需要任何特殊设置, 包括不用安装ss客户端软件

**Comment by siaimes** [comment]
没用，代码仓库不存在了，目标地址不存在了，所以更新不了pac了，现在有两个解决方案：
1. 自己去下载pac文件放到ss/ssr安装目录；
2. 使用SwitchyOmega插件，[教程传送门](https://github.com/siaimes/BTGFW#42安装switchyomega_chromium插件)

**Comment by Temmie-hOi** [comment]
嗯主要不是电脑端而是移动端......移动端基本都不支持pac

**Comment by onplus** [comment]
https://youtu.be/5B9ue1Hj_e8?t=33
![image](https://user-images.githubusercontent.com/31188782/33436291-95a790e4-d61f-11e7-8765-17c85cffd8d0.png)
