### ISSUE TITLE
开teredo隧道报错 显示未能打开隧道适配器 求解

### ISSUE THREAD

**Issue by CodeTrainerMan** [XX-net/XX-Net#8739]
C:\Windows\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 10 秒  (Group Policy)
客户端端口                : 9901  (Group Policy)
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by whhxmwhh** [comment]
#8620 已说，用组策略填写的服务器才不能自动填入

**Comment by kukuxz007** [comment]
这个问题 我遇到过 要修改注册表。

1. Open registry editor.   How To Open Registry Editor

2. Navigate through the following:

    HKEY_LOCAL_MACHINE\SYSTEM\CURRENTCONTROLSET\SERVICES\TCPIP6\PARAMETERS

3. In the right pane, right click Disabled Components and select Edit. Set the DWord value to 0.

4. Restart your computer and the teredo tunneling adapter will now start.

**Comment by OsemDing** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

我也是同样的问题，注册表已经修改过了，还是不行

**Comment by gjbg1989** [comment]
#8620 tertdo.bat自动选用更好的服务器，或许就OK
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by BlackBeatles** [comment]
哥们，试试这个#8742

**Comment by kiki008** [comment]
3楼说中文行吗？不会看啊。。。。。。

**Comment by gjbg1989** [comment]
3楼说。。。
![default](https://user-images.githubusercontent.com/13290970/37479057-a2225c48-28b6-11e8-954c-8f2c12e7baff.png)

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）
