### ISSUE TITLE
Teredo隧道接入ipv6，错误：客户端在对称NAT后

### ISSUE THREAD

**Issue by tylerrrkd** [XX-net/XX-Net#8741]
* V3.8.4
  
* 搜索过Issue。

* 使用过[#7000](https://github.com/XX-net/XX-Net/issues/7000) 中的方法。
 
* 爬了好多文章，问题依旧，发现issue中跟“对称NAT”有关的问题只有一个。希望有遇到相同问题的gay友提下解决方法。

* 看的几篇文章，大概意思是：Teredo隧道不需要PC机具有公网IPv4地址，可以穿越NAT通过将IPv6数据包封装在UDP中访问IPv6网络。

* 可是，无论用enterpriseclient 还是直接使用 client 配置的服务器 **teredo.remlab.net** 都提示
错误：**客户端在对称NAT后**

* 于是：想用最后一招，用软件虚拟方式接入ipv6。尝试中...

* what the hell, 7k图片穿了半天。算了楼里传。

**Comment by e2889e** [comment]
可以配置路由器的话,设置本机为"DMZ主机".

**Comment by tylerrrkd** [comment]
@e2889e 呃啊，在公司，没权限进路由器哦。

**Comment by penuser** [comment]
请死心。

对称型NAT：与前三种锥型NAT不同，对称型NAT内网客户端在连接外部客户端时随连接的目标不同分配的端口也将发生改变，或者说当内外网客户端连接时，内网客户端分配到的IP地址和端口、外网客户端分配到的目标IP地址和端口，其中任一项发生改变，都会引起连接路径将随之改变。

简单说就是完全动态NAT，TEREDO协议对这东西没辙。

**Comment by tylerrrkd** [comment]
@penuser 谢谢你，那请问有啥虚拟隧道的软件推荐吗？

**Comment by penuser** [comment]
现在不比四年前，国内很多ipv6提供商已经倒了。
如果单纯是为了上网，请考虑其他技术方案。
打洞主要面对点对点通信，考虑teredo服务器并不在操控范围内，隧道打洞技术我觉得并不适合你面对的状况。

**Comment by tylerrrkd** [comment]
@penuser 好哒！谢谢你的回答！看来在对路由器没有控制权限的情况下是无解了~

**Comment by gjbg1989** [comment]
RT  @oiaBot：UPDATE: frp 是一个可用于内网穿透的高性能的反向代理应用，支持 tcp, udp, http, https 协议。- Latest v0.14.1 http://ift.tt/2aLDxAH

**Comment by tylerrrkd** [comment]
@gjbg1989 Thank you my friend.
