### ISSUE TITLE
3.8.5开启IP6 提示错误...

### ISSUE THREAD

**Issue by a250152** [XX-net/XX-Net#8748]
Get Admin
描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

**Comment by gjbg1989** [comment]
结束进程pythonw.exe，或先运行XX-Net目录内的disable_ipv6.bat，再enable_ipv6.bat

**Comment by a250152** [comment]
disable_ipv6.bat，再enable_ipv6.bat 还是一样的

**Comment by a250152** [comment]
Get Admin
描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

描述:
        在注册表和服务数据库中修改服务项。
用法:
        sc <server> config [service name] <option1> <option2>...

选项:
注意: 选项名称包括等号。
      等号和值之间需要一个空格。
 type= <own|share|interact|kernel|filesys|rec|adapt>
 start= <boot|system|auto|demand|disabled|delayed-auto>
 error= <normal|severe|critical|ignore>
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <依存关系(以 / (斜杠) 分隔)>
 obj= <AccountName|ObjectName>
 DisplayName= <显示名称>
 password= <密码>
[SC] StartService 失败 1056:

服务的实例已在运行中。

正在重置 前缀策略，完成!
重新启动计算机来完成此操作。

确定。

确定。

确定。

确定。

确定。

确定。

文件名、目录名或卷标语法不正确。


确定。

确定。

操作成功完成。

操作成功完成。

确定。

确定。

确定。

确定。

确定。

确定。

文件名、目录名或卷标语法不正确。


确定。

确定。

操作成功完成。


Windows IP 配置

已成功刷新 DNS 解析缓存。

**Comment by gjbg1989** [comment]
贴 XX-Net 诊断信息
netsh int ipv6 show teredo 贴运行结果

**Comment by xxnet** [comment]
​在哪里开户？
在哪里看到的这个错误？

**Comment by gjbg1989** [comment]
貌似XX-Net目录内的 enable_ipv6.bat
Windows: 如何配置IPv6隧道 - Lesca 技术宅 https://lesca.me/archives/how-to-build-ipv6-tunnel-on-windows.html

**Comment by a250152** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by a250152** [comment]
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo-debian.remlab.net.
客户端刷新间隔          : 60 秒
客户端端口                : 34567
状态                    : offline
错误                    : 无

**Comment by a250152** [comment]
@gjbg1989

**Comment by gjbg1989** [comment]
在代理设置正常的浏览器里打开 http://127.0.0.1:8085/
use-ipv6: auto 改成只使用IP6
scan-ip-thread-num: 10 改大到50-100，有一定IPv6数、代理正常后改回
#8620 tertdo.bat自动选用更好的服务器，运行XX数分钟或许就OK
如不行，重启机器，netsh int ipv6 show teredo 贴运行结果

**Comment by gjbg1989** [comment]
ps: 确保系统2服务为自动并开启
![default](https://user-images.githubusercontent.com/13290970/33408827-6a21b9ca-d5b3-11e7-8351-6511c4d8f861.png)

**Comment by gjbg1989** [comment]
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by charles203** [comment]
@gjbg1989 我的win7系统服务中 没有 “IP 转换配置服务”啊，怎么办？

**Comment by gjbg1989** [comment]
没有能咋办，不知。 Ipv6 自动转换 | 💖闪闪的红星💖 - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by gjbg1989** [comment]
没有能咋办——网文开始：内网固定IP。。。
