### ISSUE TITLE
win10 xx.net 启动失败

### ISSUE THREAD

**Issue by shishenzhezai** [XX-net/XX-Net#8772]
![tim 20171130192334](https://user-images.githubusercontent.com/13461444/33463423-a1967092-d678-11e7-8d7f-4bb19511d624.png)
启动时有这个弹窗，怎么处理？

**Comment by gjbg1989** [comment]
用新点的版本？

**Comment by shishenzhezai** [comment]
现在是最新的版本，文件夹的名字是最开始下载时的名字，但是程序用自带的升级程序升级过的，现在的版本是3.8.3

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/releases 最新3.8.5
https://github.com/XX-net/XX-Net/blob/master/code/default/download.md

**Comment by shishenzhezai** [comment]
非常感谢，重新下载后，现在可以使用了
