### ISSUE TITLE
.net问题求助

### ISSUE THREAD

**Issue by vinceyX** [XX-net/XX-Net#8781]
访问XXNET设置界面 出现如下信息 (3.8.3出现这个问题,手动删除后下载3.8.5还是这样)

.NET�������������System.Runtime.Remoting.RemotingException: TCP 淇￠亾鍗忚鍐茬獊: 搴斾负鎶ュご銆�
   鍦� System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   鍦� System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   鍦� System.Runtime.Remoting.Channels.Tcp.TcpServerSocketHandler.ReadHeaders()
   鍦� System.Runtime.Remoting.Channels.Tcp.TcpServerTransportSink.ServiceRequest(Object state)
   鍦� System.Runtime.Remoting.Channels.SocketHandler.ProcessRequestNow()����

**Comment by vinceyX** [comment]
运行批处理出现
Dec 01 16:03:22.380 [launcher][DEBUG] no_mess_system
Dec 01 16:03:22.581 [launcher][INFO] use build-in openssl lib
Dec 01 16:03:22.582 [launcher][INFO] start XX-Net 3.8.4
Dec 01 16:03:22.582 [launcher][DEBUG] start confirm_xxnet_exit
Dec 01 16:03:22.586 [launcher][DEBUG] <0>: try to terminate xxnet:8085
Dec 01 16:03:23.589 [launcher][DEBUG] <1>: try to terminate xxnet:8085
Dec 01 16:03:24.590 [launcher][DEBUG] <2>: try to terminate xxnet:8085
Dec 01 16:03:25.592 [launcher][DEBUG] <3>: try to terminate xxnet:8085
Dec 01 16:03:26.595 [launcher][DEBUG] <4>: try to terminate xxnet:8085
Dec 01 16:03:27.597 [launcher][DEBUG] <5>: try to terminate xxnet:8085
Dec 01 16:03:28.600 [launcher][DEBUG] <6>: try to terminate xxnet:8085
Dec 01 16:03:29.601 [launcher][DEBUG] <7>: try to terminate xxnet:8085
Dec 01 16:03:30.610 [launcher][DEBUG] <8>: try to terminate xxnet:8085
Dec 01 16:03:31.612 [launcher][DEBUG] <9>: try to terminate xxnet:8085
Dec 01 16:03:32.614 [launcher][DEBUG] <10>: try to terminate xxnet:8085
Dec 01 16:03:33.623 [launcher][DEBUG] <11>: try to terminate xxnet:8085
Dec 01 16:03:34.628 [launcher][DEBUG] <12>: try to terminate xxnet:8085
Dec 01 16:03:35.662 [launcher][DEBUG] <13>: try to terminate xxnet:8085
Dec 01 16:03:36.664 [launcher][DEBUG] <14>: try to terminate xxnet:8085

**Comment by onplus** [comment]
看一下端口占用情况

**Comment by vinceyX** [comment]
谢谢 果然是端口被占用 谢谢
