### ISSUE TITLE
Mac下突然系统托盘不见了

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#879]
Aug 28 13:07:34 - [DEBUG] init_ca
Aug 28 13:07:34 - [INFO] PHP_proxy CA exist
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51815 GET /css/bootstrap.css 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51817 GET /css/flat-ui.css 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51816 GET /css/bootstrap-responsive.css 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51818 GET /css/ladda-themeless.min.css 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51819 GET /css/style.css 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51820 GET /js/jquery-1.11.2.min.js 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51821 GET /js/bootstrap.min.js 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51822 GET /js/flat-ui.min.js 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51823 GET /js/jquery.timer.js 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51824 GET /js/spin.min.js 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51825 GET /js/ladda.min.js 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51826 GET /js/site.js?20150512 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51827 GET /img/logo.png 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51828 GET /img/fixed-width.png 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51829 GET /img/glyphicons-halflings.png 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51830 GET /download?cmd=get_progress 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51881 GET /config?cmd=get_config 
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51882 GET /img/switch-mask.png 
Aug 28 13:07:35 - [INFO] get uuid:067616b9-7bd6-43b4-b48b-e3a461ca74ce
Aug 28 13:07:35 - [DEBUG] launcher web_control 127.0.0.1:51883 GET /favicon.ico 
Aug 28 13:07:35 - [INFO] GAE CONNECT xxnet-update.appspot.com:443 
Aug 28 13:07:35 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=067616b9-7bd6-43b4-b48b-e3a461ca74ce&version=2.1.2
Aug 28 13:07:35 - [DEBUG] get ip:216.58.196.144 t:188
Aug 28 13:07:35 - [DEBUG] get ip:216.58.208.112 t:560
Aug 28 13:07:35 - [DEBUG] get ip:64.233.162.87 t:582
Aug 28 13:07:35 - [DEBUG] get ip:64.233.162.82 t:612
Aug 28 13:07:35 - [DEBUG] get ip:128.0.86.233 t:749

这里应该是加载了favicon.ico啊，为何看不到了呢？
~/Library/LaunchAgents下也有com.xxnet.launcher.plist，但不知道里面应该怎么修改

**Comment by xxnet** [comment]
是突然不见的？之前能看到？

看看应该出现的位置上有没有

2015-08-28 13:10 GMT+08:00 causlayer <notifications@github.com>:

**Comment by causlayer** [comment]
没有，我使用time machine恢复了一下，估计是我升级了pip的关系
