### ISSUE TITLE
http://uncensoredjavtorrents.com/还能打开

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#8792]
C:\Windows\System32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : start pending
客户端类型              : teredo client
网络                    : managed

C:\Windows\System32>

=========================
今天突然就这屄样了。。。但奇怪的是http://uncensoredjavtorrents.com/ 还能打开。

**Comment by GoodSake** [comment]
肏，不对了，图片显示不出来了

**Comment by onplus** [comment]
ping ipv6地址
