### ISSUE TITLE
[借楼发布] 全新Android版,XX-Net与fqrouter完美结合,支持teredo(IPV6)

### ISSUE THREAD

**Issue by XndroidDev** [XX-net/XX-Net#8797]
由于众所周知的原因,XX-Net目前需要IPV6才能完美使用,Android上没有原始teredo支持,并且没有好用的全局代理机制.
经过一段时间折腾,终于将fqrouter与XX-Net完美结合,并且为fqrouter添加了teredo,sock5支持,项目主页:
[Xndroid](https://github.com/XndroidDev/Xndroid)
[下载apk](https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-release.apk)

@xxnet 

## 特性
 * 集成XX-Net 3.7.16(版本号可自动更新)
 * 集成fqrouter, 实现真正的全局代理
 * 为fqrouter添加teredo支持, XX-Net + IPV6 自由浏览无障碍
 * 为fqrouter添加sock5支持, 方便使用 X_tunnel
 * 调用证书安装器安装证书, 确认即可一键安装(如果已经设置过图案解锁,却要求输入凭证,先清除屏幕锁即可)
 * 监听电量, 网络, 休眠状态, 自动调整最大扫描线程数
 * 集成LightningBrowser 4.5.1, 默认使用 localhost:8087 代理, 关闭证书警告
 * 将XX-Net目录放到应用数据目录(/data/data/net.xndroid), 避免误删, 卸载自动删除

**Comment by iopxiang** [comment]
谢谢你的贡献  试试

**Comment by XndroidDev** [comment]
![image](https://user-images.githubusercontent.com/32808859/33512472-45344e42-d76c-11e7-95f3-8e03d70211d1.png)
![image](https://user-images.githubusercontent.com/32808859/33512504-e22b426e-d76c-11e7-8722-271cecfd2b19.png)

**Comment by dahai058** [comment]
前些年最火的fq神器，网传fqrouter又重启开发了

**Comment by smgzj** [comment]
X86 CPU,安卓5.1，
可以安装，完成后打开报错，强退

**Comment by 514202207** [comment]
iphone多会可以上？

**Comment by XndroidDev** [comment]
@smgzj  要用到native库,busybox,python.不支持x86

**Comment by XndroidDev** [comment]
测试环境为Android 6.0.1, arm64-v8a. 如有不兼容(非arm除外)欢迎反馈或提供帮助

**Comment by mangic** [comment]
安卓4.2 华为X1

安装后打开提示致命错误窗口，内容为：start fqrouter fail:failed to list/proc/self/fd

**Comment by XndroidDev** [comment]
@mangic 
fqrouter无法访问"/proc/self/fd", 不清楚是不是Android版本的原因,

>private static String _startVpnService(){
>        String[] fds = new File("/proc/self/fd").list();
>        if (null == fds) {
>            return  "failed to list /proc/self/fd";
>        }
>        if (fds.length > 500) {
>            return  "too many fds before start: " + fds.length;
>        }
>        Intent intent = VpnService.prepare(sActivity);
>        if (intent == null) {
>            onRequestResult(RESULT_OK, sActivity);
>        } else {
>            sActivity.startActivityForResult(intent, ASK_VPN_PERMISSION);
>        }
>        while (!sRequestApproved){
>            try {
>                Thread.sleep(400);
>            } catch (InterruptedException e) {
>                e.printStackTrace();
>            }
>        }
>        return null;
>    }

**Comment by GGYNGG7** [comment]
start fqrouter fail: fai led to
list /proc/self/fd

**Comment by XndroidDev** [comment]
@GGYNGG7  @mangic  先简单地去掉了启动前的检查.
安装这个debug版看能否正常运行
[https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-debug.apk](https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-debug.apk)

**Comment by mazijing** [comment]
小米mix2   android7.1.1  
    teredo正常， ipv6扫描正常，xx-net页面证书和浏览器设置fail，不能翻墙，另外lighting browser一切访问都是网页无法打开
锤子坚果Pro2  android7.1.1
    安装之后teredo很快离线，另IP扫不到
另外两部手机     start fqrouter fail: failed to list/proc/self/fd
重新安装debug版本  打开后   弹出致命错误，fqrouter意外退出

**Comment by XndroidDev** [comment]
@mazijing 感谢,看来得多找些手机来测试

**Comment by mazijing** [comment]
mix2    teredo隧道连接正常，IP也能扫到，但是不能翻墙的原因是什么啊。是xx-net的浏览器代理以及证书fail的原因吗？

**Comment by XndroidDev** [comment]
@mangic 浏览器是否提示过证书错误,没有的话就是fqrouter的透明代理出了问题.另外点击"导入"即可导入证书.

**Comment by XndroidDev** [comment]
@mangic 建议导出日志并发过来(你可以先故意点击XX-Net右上角的退出按钮,会显示"XX-Net意外退出",这样下次启动时输出的日志会更加详细)

**Comment by XndroidDev** [comment]
@mazijing 浏览器是否提示过证书错误,没有的话就是fqrouter的透明代理出了问题.另外点击"导入"即可导入证书.

**Comment by XndroidDev** [comment]
@mazijing 建议导出日志并发过来(你可以先故意点击XX-Net右上角的退出按钮,会显示"XX-Net意外退出",这样下次启动时输出的日志会更加详细)

**Comment by mazijing** [comment]
浏览器 没有提示证书错误，另证书已经安装，重新导入好几次了  日志等会发你

**Comment by wankuizhuankan** [comment]
安卓5.1魅族
/proc/self/fd
致命错误

**Comment by XndroidDev** [comment]
@wankuizhuankan 尝试安装这个:
[https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-debug.apk](https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-debug.apk)
并将机型,系统版本,错误提示,导出日志 发送到 xndroiddev@gmail.com

**Comment by XndroidDev** [comment]
"failed to list /proc/self/fd" 已修复,重新下载最新版安装:
[https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-release.apk](https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-release.apk)

**Comment by XndroidDev** [comment]
@wankuizhuankan  @mazijing  @GGYNGG7 @mangic 
借了部手机测试,"failed to list /proc/self/fd", 和部分"fqrouter异常退出"的问题应该修复了

**Comment by hellowx** [comment]
感谢，已经用上。YOUTUBE 240 流畅。

**Comment by smgzj** [comment]
@XndroidDev 
谢谢，安卓5.1，正常FQ

**Comment by XndroidDev** [comment]
@wankuizhuankan @mazijing @GGYNGG7 @mangic 重新安装后请将运行状态,提示信息(或错误信息),导出日志,机型,系统版本 发送到 xndroiddev@gmail.com (即使正常运行也发一下), 以检查运行情况

**Comment by xxnet** [comment]
​大赞！！！
有需要完善配合的地方，告诉我。

**Comment by XndroidDev** [comment]
fqrouter实现了透明代理,在启动XX-Net前将socket, ssl, OpenSSL "打上补丁",保证不被fqrouter转发即可.
不过为了便捷使用,"xndroid"标签页下通过GET/POST来获取XX-Net的信息或设置,希望XX-Net的后续版本web控制页的URL不会随意变动.另外如果有用的新的python库,可能需要为Android编译一下.
Xndroid会删掉"code\3.8.3\python27\1.0\lib\win32","code\3.8.3\python27\1.0\lib\win32",*.dll,*.exe,以节省空间

**Comment by xxnet** [comment]
OK，找时间拜读大作。
对Windows和Android的空间优化，后面再研究办法吧，先放着。

**Comment by tommyclerk** [comment]
全局代理怎么弄哈，只能浏览器上Facebook

**Comment by XndroidDev** [comment]
@tommyclerk  其它APP的代理还没测试过,也许会有问题,等稳定了再解决

**Comment by XndroidDev** [comment]
如果有更新XX-Net,或更改默认设置,建议保持use_ipv6(使用IPv6)设置项为 force_ipv6 ,以减小SocksVpnService 的负担.

**Comment by carlchan99** [comment]
Many thanks for sharing.

**Comment by xxnet** [comment]
资源消耗的优化，最理想的方案是根据wifi/电源的情况，调整扫描线程。
根据操作系统的不同，进行参数调整。

**Comment by XndroidDev** [comment]
其实现在扫描线程开的都不大,手机未休眠时这点耗电影响还不大.
即使将扫描线程调为0,fqrouter和XX-Net仍然需要不断运行,锁屏后,要么Android不能很好得休眠,要么XX-Net和fqrouter的运行将受到抑制.
Android的休眠策略我也还不怎么懂,猜测大概是这样的.不过既然要用这个软件,就不应该在意耗电

**Comment by xxnet** [comment]
​理想状态下，用户不必担心开着这个软件，导致耗电量高，才能随时可以翻墙。

可以设计一个策略，探测到用户关闭屏幕超过5分钟，或者没有了翻墙流量，就停掉后台的连接。

**Comment by toobed** [comment]
集成XX-Net 3.7.16？不需要另外安装XX-Net 吗？我就安装了app-release，就行了吗？

**Comment by XndroidDev** [comment]
测试了一下Twitter APP,找到了原因:

>Dec 03 13:09:53.274 - [INFO] ssl error: [Errno 1] _ssl.c:582: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown, create full domain cert for host:api.twitter.com

>These errors indicate that the client/browser did not trust the certificate presented by the ProxySG appliance. The client/browser signals an alert when the appliance presents its certificate to the browser, which is not signed by a trusted CA. 
>
>When this happens, users see a warning regarding the certificate; when prompted, they decline proceeding to the website. This results in a termination of the SSL session. Then, the message is logged. 

就是说Twitter自己进行证书检查,没有使用系统证书,看来这个大概解决不了.不过用X_tunel可正常访问

**Comment by xxnet** [comment]
智能路由计划的策略：
​ 先尝试 GAE证书握手，握手失败的时候，记录下来，下次这个域名用x-tunnel

**Comment by jiang1102233** [comment]
红米note4x  安卓7.0 miui9未root,安装后证书导入成功，IPV6数量挺多，自带的LightningBrowser可以访问Facebook，谷歌，YouTube等都无法访问。用其他浏览器访问Facebook会提示证书错误，进入网页后排版也不对，求解

**Comment by XndroidDev** [comment]
>智能路由计划的策略：
>​ 先尝试 GAE证书握手，握手失败的时候，记录下来，下次这个域名用x-tunnel

高级特性以后再搞,先解决稳定性

**Comment by wooowooo** [comment]
围观捧场
注意安全啊

**Comment by dalton-chiou** [comment]
必须谢谢作者的工作。 @XndroidDev 
有一点想法：扫描线程可否让用户自己来设定，还有系统休眠时的应用行为？这样既尊重用户，也省去了“监听电量, 网络“的资源消耗？

**Comment by XndroidDev** [comment]
@dalton-chiou  把自动扫描线程关掉后就可以在XX-Net里设置,目前没有什么"系统休眠时的应用行为",只不过在选择线程数时可能选小一点.

**Comment by XndroidDev** [comment]
@jiang1102233   "自带的LightningBrowser可以访问Facebook，谷歌，YouTube等都无法访问" 这句话没看明白,哪个可以访问?哪个不能访问? 
"用其他浏览器"是什么浏览器,还是所以浏览器,
"排版也不对"是CSS样式加载不全还是软码之类的

**Comment by jiang1102233** [comment]
@XndroidDev  仔细试了一下只能访问Facebook和tumblr。不能访问google，YouTube。其他浏览器是指小米自带的浏览器和夸克浏览器，我手机上只有这两个。排版不对是css样式加载不全，只有文字，没有任何图片能加载出来

**Comment by mangic** [comment]
@XndroidDev 
![_20171203170745](https://user-images.githubusercontent.com/33594145/33523901-b753c396-d84c-11e7-8af0-33be6bfd6ac6.jpg)
华为X1 安卓4.2

**Comment by mangic** [comment]
@XndroidDev 
[xndroid-logs.tar.gz](https://github.com/XX-net/XX-Net/files/1524609/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
@mangic 安装这个debug版:
[https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-debug.apk](https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-debug.apk)
无论是否正常运行都将日志发过来

**Comment by xiaozijun** [comment]
这个有点太强了，一装上就能用了，能解释一下是有自动切换吗？还是全部走代理的？谢谢。

**Comment by XndroidDev** [comment]
@jiang1102233 我测试的上述网站都没有问题,你可以将日志发过来

**Comment by dalton-chiou** [comment]
xndroid 1.1.1。原生android 6.0。清空HOSTS（只剩localhost），在数据网络下测试：

1，内置的LB浏览器可以访问twitter,facetook，无法访问youtube。更无法使用google搜索，无法访问www.google.com/ncr。以上全部是https。LB的代理设置到8087、或不使用代理，都是如此（也就是说LB不设置代理也一样访问facebook等。而google怎样设置代理都不通。）
2，chrome倒可以使用google搜索。除facebook外，能够访问youtube并打开视频。
3，可以访问google play，但无法下载应用。这有点奇怪，因为同样是sn-domains，youtube可以开视频，play却不能下载。

情况就是这样。已经很不错了，加油。

还有几点小想法：
1，xndroid退出（从应用内右侧的退出按钮）正常，但lightningbrowser始终保留后台进程，有点不舒服。
2，来自xxnet的通知始终固定在左上角不可移去。可否改一下？
3，可否编译不带LB浏览器的版本？

**Comment by XndroidDev** [comment]
@xiaozijun fqrouter 会将常见国内IP和域名直连,你可在fqrouter中设置.

**Comment by XndroidDev** [comment]
@dalton-chiou 我测试的以上网站都可正常访问(google play测不了),你可重试后将日志发过来

1.后续可以尝试退出lightningbrowser
2.通知不可移出(一个是启动VPN时系统会强制显示,另一个是XX-Net的通知,一方面显示信息,更重要的是将xndroid进程置为前台进程,避免被系统强行杀掉),
3.如有广泛需要,lightningbrowser可移除

**Comment by XndroidDev** [comment]
LightningBrowser为早期未加入fqrouter的情况下,为方便使用加入.现已集成fqrouter,正常情况下无需LightningBrowser.是否希望移除LightningBrowser?
欢迎在 [https://github.com/XndroidDev/Xndroid/issues/8](https://github.com/XndroidDev/Xndroid/issues/8)  反馈建议

**Comment by xiaozijun** [comment]
@XndroidDev 谢谢，提个小建议：进入xxnet或者fqrouter后，按返回会直接退出，而不是返回Xndroid，这个可以修改一下。

进入XXnet提示更新，这个里面可以直接点更新吗？还是最好保持3.7.16？

**Comment by XndroidDev** [comment]
@xiaozijun 可以更新，建议将“使用IPV6”设置保持为 “force+ipv6”

**Comment by jiang1102233** [comment]
github怎么发送文件啊，我上传到百度网盘了 https://pan.baidu.com/s/1dE3Ox6x

**Comment by XndroidDev** [comment]
@jiang1102233  发到 xndroiddev@gmail.com

**Comment by mangic** [comment]
@XndroidDev 楼上贴图就是安装你发的那个版本

**Comment by ts0307** [comment]
荣耀v9成功翻墙，如果有全局代理的话那就更赞了

**Comment by XndroidDev** [comment]
@mangic  debug版已更新过，重新下载

**Comment by XndroidDev** [comment]
使用Android 7.x的朋友 测试一下证书是否正常 https://github.com/XndroidDev/Xndroid/issues/9
使用Android 8.0的， 执行busybox的ln, tar, chmod 命令会出现 “system call error”, 由于没有Android O 的手机测试，不清楚详细情况 https://github.com/XndroidDev/Xndroid/issues/10

**Comment by yaojiucai** [comment]
无法打开，安卓 最新版上面。一直显示 启动中，初始化中

**Comment by XndroidDev** [comment]
是否有日志导出，有的话将日志发过来，xndroiddev@gmail.com

2017-12-06 15:27 GMT+08:00 yaojiucai <notifications@github.com>:

**Comment by yangwencn** [comment]
大赞！！
Android 7.1.1 在浏览器上目前使用起来一切OK，就是其他App比如Play Store, Facebook, Instagram还没办法连接。

**Comment by gjbg1989** [comment]
就是其他App比如Play Store, Facebook, Instagram还没办法连接——不是有法在安卓手机系统网络设置代理？

**Comment by yaojiucai** [comment]
没有日志，一直卡在初始化中，没有任何反应。

发送自 Windows 10 版邮件应用

发件人: XndroidDev
发送时间: 2017年12月6日 16:48
收件人: XX-net/XX-Net
抄送: yaojiucai; Comment
主题: Re: [XX-net/XX-Net] [借楼发布] 全新Android版,XX-Net与fqrouter完美结合,支持teredo(IPV6) (#8797)

是否有日志导出，有的话将日志发过来，xndroiddev@gmail.com 

2017-12-06 15:27 GMT+08:00 yaojiucai <notifications@github.com>:

**Comment by VincentZhou98** [comment]
华为P10成功（只能用Chrome，内置Lightening会显示encoding error）
但是fqrouter无法打开，显示Internal Server Error
此外因为我没有root，所以好像没有办法取得日志， @XndroidDev 请问导出日志可以到其他地方吗

**Comment by e2889e** [comment]
@VincentZhou98 "Content-Encoding"是br的问题,貌似xxnet已经解决了
> [xndroid找开网站报 net::ERR_CONTENT_DECODING_FAILED · Issue #8852 · XX-net/XX-Net](https://github.com/XX-net/XX-Net/issues/8852#issuecomment-350405791)

**Comment by Freedom000** [comment]
appid无效 明明部署服务端的时候，秒部署，然后配置的时候，所有的appid都无效 只能用公共的id

**Comment by XndroidDev** [comment]
@VincentZhou98  发现"Internal Server Error"的问题了,是在修复Android8.0的时候换了busybox造成的bug,下次更新修复.如果你的手机不是Android8.0 下载这个即可: https://github.com/XndroidDev/Xndroid/releases/download/1.1.1/app-release.apk

**Comment by XndroidDev** [comment]
@VincentZhou98  点击菜单中的"导出日志"就可以导出了

**Comment by mirifem** [comment]
今天下午下载试用，一切正常，chrome浏览器内看youtube流畅，app能看但卡顿。
然而半小时后升级xx-net到3.8.5出现致命错误——意外退出；关闭Xndroid重启出现致命错误——无网络连接。
![screenshot_20171213-182153](https://user-images.githubusercontent.com/15632397/33935457-f4b9fa88-e036-11e7-8099-e8b5ae765239.png)
![screenshot_20171213-182603](https://user-images.githubusercontent.com/15632397/33935459-f7a6d540-e036-11e7-8419-860744bf1f6e.png)

手机pixel，8.1.0正式版，准备卸载重装Xndroid不更新xx-net再试。
两个日志都发给 @XndroidDev 供参考

**Comment by XndroidDev** [comment]
请转到  https://github.com/XndroidDev/Xndroid/issues 交流

**Comment by tradeshark** [comment]
太厉害了。装上就能用
