### ISSUE TITLE
IPv6 Status  Fail怎么解决啊

### ISSUE THREAD

**Issue by 0x45f** [XX-net/XX-Net#8800]
![Uploading image.png…]()
Dec 02 16:43:14.890 - [DEBUG] connect 2607:f8b0:4017:14::b fail:error(10051, '')
Dec 02 16:43:14.890 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:14.933 - [DEBUG] connect 2607:f8b0:400f:2::12 fail:error(10051, '')
Dec 02 16:43:14.933 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:14.982 - [DEBUG] connect 2607:f8b0:4008:21::9 fail:error(10051, '')
Dec 02 16:43:14.982 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.014 - [DEBUG] connect 2404:6800:400e:3::b fail:error(10051, '')
Dec 02 16:43:15.014 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.051 - [DEBUG] connect 2607:f8b0:4016:17::13 fail:error(10051, '')
Dec 02 16:43:15.051 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.092 - [DEBUG] connect 2607:f8b0:4016:c::b fail:error(10051, '')
Dec 02 16:43:15.092 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.134 - [DEBUG] connect 2607:f8b0:400f:1::12 fail:error(10051, '')
Dec 02 16:43:15.134 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.183 - [DEBUG] connect 2607:f8b0:4007:3::6 fail:error(10051, '')
Dec 02 16:43:15.183 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.224 - [DEBUG] connect 2607:f8b0:4012:1::16 fail:error(10051, '')
Dec 02 16:43:15.224 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.251 - [DEBUG] connect 2607:f8b0:4002:2f::7 fail:error(10051, '')
Dec 02 16:43:15.251 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.301 - [DEBUG] connect 2607:f8b0:401d:3::12 fail:error(10051, '')
Dec 02 16:43:15.301 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.331 - [DEBUG] connect 2607:f8b0:4017:1b::18 fail:error(10051, '')
Dec 02 16:43:15.331 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.412 - [DEBUG] connect 2607:f8b0:401d:19::14 fail:error(10051, '')
Dec 02 16:43:15.412 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.463 - [DEBUG] connect 2404:6800:400b:1c::b fail:error(10051, '')
Dec 02 16:43:15.463 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.493 - [DEBUG] connect 2a00:1450:401c:1b::c fail:error(10051, '')
Dec 02 16:43:15.493 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.585 - [DEBUG] connect 2404:6800:400e:6::c fail:error(10051, '')
Dec 02 16:43:15.585 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.614 - [DEBUG] connect 2607:f8b0:401d:b::a fail:error(10051, '')
Dec 02 16:43:15.614 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.654 - [DEBUG] connect 2607:f8b0:401d:15::e fail:error(10051, '')
Dec 02 16:43:15.654 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.734 - [DEBUG] connect 2404:6800:400b:25::18 fail:error(10051, '')
Dec 02 16:43:15.734 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.774 - [DEBUG] connect 2607:f8b0:4016:7::7 fail:error(10051, '')
Dec 02 16:43:15.774 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.815 - [DEBUG] connect 2607:f8b0:4016:8::13 fail:error(10051, '')
Dec 02 16:43:15.815 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.866 - [DEBUG] connect 2607:f8b0:4016:11::6 fail:error(10051, '')
Dec 02 16:43:15.866 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.908 - [DEBUG] connect 2404:6800:400f:7::b fail:error(10051, '')
Dec 02 16:43:15.908 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:15.979 - [DEBUG] connect 2404:6800:400c:13::d fail:error(10051, '')
Dec 02 16:43:15.979 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.030 - [DEBUG] connect 2607:f8b0:4017:15::a fail:error(10051, '')
Dec 02 16:43:16.030 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.060 - [DEBUG] connect 2607:f8b0:4017:a::16 fail:error(10051, '')
Dec 02 16:43:16.061 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.111 - [DEBUG] connect 2607:f8b0:4017:2d::f fail:error(10051, '')
Dec 02 16:43:16.111 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.150 - [DEBUG] connect 2a00:1450:401f:35::b fail:error(10051, '')
Dec 02 16:43:16.150 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.231 - [DEBUG] connect 2607:f8b0:401e:15::16 fail:error(10051, '')
Dec 02 16:43:16.231 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.260 - [DEBUG] connect 2607:f8b0:4007:3::16 fail:error(10051, '')
Dec 02 16:43:16.260 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.352 - [DEBUG] connect 2607:f8b0:4012:7::15 fail:error(10051, '')
Dec 02 16:43:16.352 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.392 - [DEBUG] connect 2607:f8b0:4016:5::a fail:error(10051, '')
Dec 02 16:43:16.392 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.432 - [DEBUG] connect 2607:f8b0:4016:a::13 fail:error(10051, '')
Dec 02 16:43:16.432 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.512 - [DEBUG] connect 2607:f8b0:4002:1b::13 fail:error(10051, '')
Dec 02 16:43:16.512 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.551 - [DEBUG] connect 2607:f8b0:4012:b::13 fail:error(10051, '')
Dec 02 16:43:16.551 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.581 - [DEBUG] connect 2607:f8b0:4007:1b::17 fail:error(10051, '')
Dec 02 16:43:16.581 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.630 - [DEBUG] connect 2607:f8b0:4002:f::d fail:error(10051, '')
Dec 02 16:43:16.630 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.668 - [DEBUG] connect 2607:f8b0:4012:1::19 fail:error(10051, '')
Dec 02 16:43:16.668 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.699 - [DEBUG] connect 2607:f8b0:401d:13::d fail:error(10051, '')
Dec 02 16:43:16.699 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.740 - [DEBUG] connect 2404:6800:4007:6::9 fail:error(10051, '')
Dec 02 16:43:16.740 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.783 - [DEBUG] connect 2607:f8b0:4017:2a::7 fail:error(10051, '')
Dec 02 16:43:16.783 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.822 - [DEBUG] connect 2404:6800:400c:14::17 fail:error(10051, '')
Dec 02 16:43:16.822 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.863 - [DEBUG] connect 2607:f8b0:401e:14::e fail:error(10051, '')
Dec 02 16:43:16.863 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.903 - [DEBUG] connect 2607:f8b0:4004:20::e fail:error(10051, '')
Dec 02 16:43:16.903 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.942 - [DEBUG] connect 2607:f8b0:4004:f::8 fail:error(10051, '')
Dec 02 16:43:16.942 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:16.983 - [DEBUG] connect 2607:f8b0:401d:13::6 fail:error(10051, '')
Dec 02 16:43:16.983 - [DEBUG] report_connect_fail network fail
Dec 02 16:43:17.064 - [DEBUG] connect 2607:f8b0:400a:7::14 fail:error(10051, '')
Dec 02 16:43:17.064 - [DEBUG] report_connect_fail network fail

**Comment by 516310189** [comment]
C:\Windows\system32>netsh interface ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by TangJiKe** [comment]
如果是MacIPv6 Status Fail的话肿么办😭😭😭

**Comment by TangJiKe** [comment]
如果是Mac IPv6 Status Fail的话肿么办😭😭😭

**Comment by 569985011** [comment]
我也是这个问题，而且时好时坏，有时重启计算机就又能用了。。

**Comment by gjbg1989** [comment]
#8620 tertdo.bat自动选用更好的服务器
netsh int ipv6 show teredo 贴运行结果

**Comment by 516310189** [comment]
@gjbg1989 下载不了怎么办

**Comment by jingyihiter** [comment]
我的是这样的，服务器名称怎么设置的？为什么我的是这个呢?
--------------------
类型                    : client
服务器名称              : teredo.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能解析服务器名

**Comment by gjbg1989** [comment]
刷新或重载控制页、右键XX状态栏图标重启不可恢复正常状态时：
（结束进程pythonw.exe）Win+X 打开Windows PowerShell（管理员），输入命令
netsh interface teredo set state enterpriseclient server=default
#8620 tertdo.bat自动选用更好的服务器
（检查 netsh int ipv6 show teredo 已待命，）运行 XX-Net 即可

**Comment by dancorpse** [comment]
上周五我开启ipv6以后就能使用了，可是今天连ipv6都开启不了，我是`win7 64.

**Comment by 569985011** [comment]
应该是teredo没有正常工作，你查一下，试试换个服务器。【具体实施方案你可以重复一遍第一次开启ipv6的过程】


发送自 Windows 10 版邮件应用

发件人: dancorpse
发送时间: 2017年12月4日 11:51
收件人: XX-net/XX-Net
抄送: Chauncy; Comment
主题: Re: [XX-net/XX-Net] IPv6 Status Fail怎么解决啊 (#8800)

上周五我开启ipv6以后就能使用了，可是今天连ipv6都开启不了，我是`win7 64.

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33552714-f0723ee8-d930-11e7-850a-5e9306ee3643.png)
貌似ping不通的微软服务器 win10.ipv6.microsoft.com. win1710.ipv6.microsoft.com. 更稳定😂怎么最后还带有句点？

**Comment by jingyihiter** [comment]
@gjbg1989  把服务器换成teredo.remlab.net，应该就可以了。命令：**netsh interface teredo set state enterpriseclient server=teredo.remlab.net**   我是这样在win7和win10上都成功了

**Comment by gjbg1989** [comment]
嗯，谢谢。
