### ISSUE TITLE
manjaro linux安装蓝灯，速度好快。

### ISSUE THREAD

**Issue by fletchere** [XX-net/XX-Net#881]
用yaourt -S lantern，然后输入密码，然后一路enter键就安装好了。
不知道是不是基于arch linux的滚动版本翻墙有特别的优势呢？

**Comment by xxnet** [comment]
本身linux的网络性能比Windows好不少，不同linux之间的性能差别不大。
在高负载情况下，FreeBSD性能比Linux好，不过翻墙的负载不高，普通linux够了

在 2015年8月28日 下午4:51，fletchere <notifications@github.com>写道：

**Comment by lele2010lele** [comment]
mac系统如何安装啊？

**Comment by fletchere** [comment]
@lele2010lele  下载这个 https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg 然后点击安装，下一步下一步就可以了。

**Comment by balbeleet** [comment]
windows下速度不砸滴 特别还是南方电信

**Comment by fletchere** [comment]
@balbeleet  各种Linux各种爽，我已经在Ubuntu, Kali, Fedora, Manjaro试过了。

**Comment by balbeleet** [comment]
= = 哎一直下不了心转linux

2015-08-29 18:25 GMT+08:00 fletchere <notifications@github.com>:

**Comment by PaulUlrik** [comment]
很奇怪，昨天下的Lantern还能用，今天又翻不了了。有没有大神能解答一下...

**Comment by ARwMq9b6** [comment]
谢谢推荐 http://sourceforge.net/projects/manjarolinux/

**Comment by balbeleet** [comment]
好好的呢!

2015-08-30 14:50 GMT+08:00 ARwMq9b6 <notifications@github.com>:

**Comment by wangy147** [comment]
请问，在manjaro上已经下好了蓝灯，但是还是不好翻墙这是怎么回事呢？？需要配置么？？

**Comment by deerainw** [comment]
> @balbeleet 各种Linux各种爽，我已经在Ubuntu, Kali, Fedora, Manjaro试过了。

请问在 manjaro 上怎么安装 lantern？
