### ISSUE TITLE
已购买xx-Tunnel套餐，怎么可用流量没增加呢？

### ISSUE THREAD

**Issue by marvin9826** [XX-net/XX-Net#8814]
PayPal交易号（1年套餐）
65T49912RA714035T
x_tunnel account
maiyy9826@gmail.com

**Comment by xxnet** [comment]
​查了日志，应该是paypal 推送到服务器的消息丢失了。
偶尔有这样的情况，已经手动给你转了流量，谢谢支持！

**Comment by marvin9826** [comment]
已解决，谢谢！
