### ISSUE TITLE
各位Mac用户，使用XX+Chrome过程中有出现过"卡死"现象吗？

### ISSUE THREAD

**Issue by cobob** [XX-net/XX-Net#882]
卡死是指在开启了XX后的使用过程中，除了F1 F2 F3这些苹果快捷键功能之外，其他鼠标等操作都卡住，持续大概几十秒-几分钟后恢复。
我的OS版本是10.10.5(10.10.4亦是)，在使用以前的XX版本时从未出现过卡死的情况，在最近的版本才出现(增加扫描IP功能)，如果关闭IP扫描 卡死的概率会相对降低。
不知道各位Mac用户有没有遇到类似情况，我这边重新安装系统后仍然有出现，考虑应该是XX的小bug。

**Comment by causlayer** [comment]
经常有，卡死短暂的2-3秒，然后就好了

**Comment by thxhtp** [comment]
win10 经常卡几秒

**Comment by xxnet** [comment]
大家观察下卡的时候CPU是否会高。

另外请不要把卡鼠标和声音卡混淆，Win10会出现卡声音，但不影响鼠标键盘

2015-08-29 0:06 GMT+08:00 Thxhtp <notifications@github.com>:

**Comment by causlayer** [comment]
mac卡的时候鼠标键盘都不可以用，关掉xx就不会出现了。

**Comment by lele2010lele** [comment]
2015款macbookpro和2014款imac没有任何问题

**Comment by gdgoldlion** [comment]
经常有，几秒到十几秒不等。你是不是用了proxifer，那个东西好久都不更新了，兼容性直线下降啊
