### ISSUE TITLE
没有证书，SSL握手失败

### ISSUE THREAD

**Issue by Reeeeeemi** [XX-net/XX-Net#883]
运行在树莓派上，设置浏览器代理后https的网站全部都存在证书问题，怎么解决？

*******************************************
XX-Net Version 	2.1.2
Python Version 	2.7.3
Sys Platform 	linux2
OS System 	Linux
OS version 	#755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015
OS release 	3.18.7-v7+
OS detail 	Dist:debian; Version:7.8; ID:
language 	en_GB
architecture 	32bit,ELF
******************************************************
logs:

Aug 29 02:52:17 - [DEBUG] create_ssl update ip:212.188.15.108 time:2003

Aug 29 02:52:17 - [DEBUG] create_ssl 212.188.15.108 fail: certificate is none cost:3439 h:2003

Aug 29 02:52:17 - [DEBUG] create_ssl update ip:113.171.243.140 time:1509

Aug 29 02:52:18 - [DEBUG] create_ssl update ip:113.171.245.165 time:1166

Aug 29 02:52:18 - [DEBUG] create_ssl 182.79.253.216 fail:timed out cost:2003 h:0

Aug 29 02:52:18 - [DEBUG] create_ssl update ip:113.171.245.140 time:1368

Aug 29 02:52:18 - [DEBUG] create_ssl update ip:212.188.15.104 time:2970

Aug 29 02:52:18 - [DEBUG] create_ssl 212.188.15.104 fail: certificate is none cost:3286 h:2970

Aug 29 02:52:18 - [DEBUG] create_ssl 222.255.120.32 fail:timed out cost:2003 h:0

Aug 29 02:52:18 - [DEBUG] create_ssl 58.145.238.18 fail:timed out cost:2003 h:0

Aug 29 02:52:19 - [DEBUG] create_ssl update ip:212.188.15.96 time:2003

Aug 29 02:52:19 - [DEBUG] create_ssl 212.188.15.96 fail: certificate is none cost:3435 h:2003

Aug 29 02:52:19 - [INFO] GAE CONNECT clients4.google.com:443

Aug 29 02:52:19 - [DEBUG] create_ssl update ip:113.171.243.229 time:2034

Aug 29 02:52:19 - [DEBUG] create_ssl update ip:212.188.15.72 time:2648

Aug 29 02:52:19 - [DEBUG] create_ssl 212.188.15.72 fail: certificate is none cost:3074 h:2648

Aug 29 02:52:20 - [INFO] GAE CONNECT clients4.google.com:443

Aug 29 02:52:22 - [INFO] GAE CONNECT clients4.google.com:443

Aug 29 02:52:27 - [INFO] GAE CONNECT clients4.google.com:443

Aug 29 02:52:39 - [INFO] GAE CONNECT clients4.google.com:443

Aug 29 02:52:57 - [INFO] GAE CONNECT clients4.google.com:443

Aug 29 02:53:03 - [INFO] GAE CONNECT www.google.com:443

Aug 29 02:53:03 - [INFO] GAE CONNECT plus.google.com:443

Aug 29 02:53:04 - [INFO] GAE CONNECT www.google.com:443

Aug 29 02:53:04 - [INFO] GAE CONNECT plus.google.com:443

Aug 29 02:53:06 - [INFO] GAE CONNECT www.google.com:443

Aug 29 02:53:09 - [DEBUG] head request fail:Error([('SSL routines', 'SSL3_WRITE_BYTES', 'ssl handshake failure')],)

Aug 29 02:53:09 - [INFO] GAE CONNECT plus.google.com:443

Aug 29 02:53:14 - [INFO] GAE CONNECT www.google.com:443

Aug 29 02:53:14 - [INFO] GAE CONNECT www.gstatic.com:443

Aug 29 02:53:21 - [INFO] scan_ip add ip:1.179.251.135 time:4231

**Comment by Reeeeeemi** [comment]
用的是自己的appid

**Comment by Reeeeeemi** [comment]
google youtube 因为证书问题都无法打开，没有忽视的选项

**Comment by linhua55** [comment]
手动导入证书
https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA

**Comment by Reeeeeemi** [comment]
成功解决，谢谢

**Comment by simonasd** [comment]
已将此问题记载到Wiki的[故障速查手册](https://github.com/XX-net/XX-Net/wiki/%E6%95%85%E9%9A%9C%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8C)中。

**Comment by DelingAlieZ10** [comment]
![image](https://user-images.githubusercontent.com/27910120/29249667-ca3ddb88-8066-11e7-991b-4fdae4ff94ff.png)
