### ISSUE TITLE
ubuntu xx-net 无法启动

### ISSUE THREAD

**Issue by rockwzy** [XX-net/XX-Net#8835]
```
XX-Net version:default
12月 04 22:22:05.0 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
12月 04 22:22:05.0 [launcher][INFO] start XX-Net 3.8.5
12月 04 22:22:05.0 [launcher][DEBUG] start confirm_xxnet_exit
12月 04 22:22:05.0 [launcher][DEBUG] good, xxnet:8085 clear!
12月 04 22:22:05.0 [launcher][DEBUG] finished confirm_xxnet_exit
12月 04 22:22:05.0 [gae_proxy][INFO] SSL use version:TLSv1
12月 04 22:22:05.0 [gae_proxy][INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
12月 04 22:22:05.0 [gae_proxy][INFO] load ip range file:/home/zywang/applications/XX-Net-master/code/default/gae_proxy/local/ip_range.txt
12月 04 22:22:05.1 [gae_proxy][INFO] load google ip_list num:707, gws num:707
12月 04 22:22:05.1 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
12月 04 22:22:05.1 [gae_proxy][INFO] ------------------------------------------------------
12月 04 22:22:05.1 [gae_proxy][INFO] Python Version     : 2.7.6
12月 04 22:22:05.1 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:14.04; ID:trusty
12月 04 22:22:05.1 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
12月 04 22:22:05.1 [gae_proxy][INFO] GAE APPID          : 
12月 04 22:22:05.1 [gae_proxy][INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
12月 04 22:22:05.1 [gae_proxy][INFO] ------------------------------------------------------
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zywang/applications/XX-Net-master/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/home/zywang/applications/XX-Net-master/code/default/gae_proxy/local/proxy.py", line 153, in main
    CertUtil.init_ca()
  File "/home/zywang/applications/XX-Net-master/code/default/gae_proxy/local/cert_util.py", line 606, in init_ca
    CertUtil.cert_publickey = OpenSSL.crypto.load_publickey(OpenSSL.crypto.FILETYPE_PEM, fp.read())
AttributeError: 'module' object has no attribute 'load_publickey'

12月 04 22:22:05.2 [gae_proxy][DEBUG] network IPv4 is ok, cost:175 ms
12月 04 22:22:06.4 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:7::11 time:528 h2:0
12月 04 22:22:07.1 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a::c time:785 h2:0
12月 04 22:22:07.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:5::15 time:526 h2:0
12月 04 22:22:09.5 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:c::b time:1430 h2:0
12月 04 22:22:09.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:7::c time:509 h2:0
12月 04 22:22:10.4 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:5::e time:1250 h2:0
12月 04 22:22:10.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:f::17 time:846 h2:0
12月 04 22:22:11.1 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:6::14 time:442 h2:0
12月 04 22:22:11.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:1::7 time:1516 h2:0
12月 04 22:22:11.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:7::7 time:860 h2:0
12月 04 22:22:12.2 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:13::7 time:1117 h2:0
12月 04 22:22:12.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:3::c time:4075 h2:0
12月 04 22:22:12.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401a:5::b time:552 h2:0
12月 04 22:22:12.8 [gae_proxy][DEBUG] connect 2607:f8b0:401d:3::7 fail:error(' certficate is none',)
12月 04 22:22:12.8 [gae_proxy][DEBUG] report_connect_fail:2607:f8b0:401d:3::7
12月 04 22:22:12.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d::c time:4091 h2:0
12月 04 22:22:13.1 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:12::9 time:3886 h2:0
12月 04 22:22:13.3 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4012:3::6 time:1451 h2:0
12月 04 22:22:13.6 [gae_proxy][DEBUG] connect 2607:f8b0:401d:e::19 fail:timeout('timed out',)
12月 04 22:22:13.6 [gae_proxy][DEBUG] report_connect_fail:2607:f8b0:401d:e::19
12月 04 22:22:13.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:d::6 time:494 h2:0
12月 04 22:22:14.0 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:3::8 time:699 h2:0
12月 04 22:22:14.3 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:3::10 time:1852 h2:0
12月 04 22:22:14.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:6::10 time:719 h2:0
12月 04 22:22:14.7 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:400f:1::7 time:948
12月 04 22:22:15.0 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:5::d time:771 h2:0
12月 04 22:22:15.4 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:15::8 time:455 h2:0
12月 04 22:22:16.3 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:b::11 time:1366 h2:0
12月 04 22:22:16.5 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:1::19 time:802 h2:0
12月 04 22:22:16.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:1c::9 time:488 h2:0
12月 04 22:22:17.2 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4002:27::a time:3249
12月 04 22:22:17.2 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:12::b time:1675 h2:0
12月 04 22:22:17.6 [gae_proxy][DEBUG] connect 2607:f8b0:401d:3::8 fail:timeout('timed out',)
12月 04 22:22:17.6 [gae_proxy][DEBUG] report_connect_fail:2607:f8b0:401d:3::8
12月 04 22:22:17.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4007:3::10 time:3161 h2:0
12月 04 22:22:18.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:12::15 time:857 h2:0
12月 04 22:22:18.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4012:8::c time:932 h2:0
12月 04 22:22:19.1 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4012::10 time:571 h2:0
12月 04 22:22:19.4 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4012::9 time:2363 h2:0
12月 04 22:22:19.9 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:1a::c time:3236 h2:0
12月 04 22:22:24.7 [gae_proxy][DEBUG] restore ip:2607:f8b0:401d:3::7
12月 04 22:22:27.8 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4016:13::e time:1510
12月 04 22:22:28.0 [gae_proxy][DEBUG] restore ip:2607:f8b0:401d:e::19
12月 04 22:22:32.1 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4012:5::6 time:1002
12月 04 22:22:32.3 [gae_proxy][DEBUG] restore ip:2607:f8b0:401d:3::8
12月 04 22:22:33.0 [gae_proxy][INFO] scan_ip add ip:2404:6800:400c:11::17 time:1515
12月 04 22:22:37.2 [gae_proxy][INFO] scan_ip add ip:2a00:1450:400a:3::9 time:714
12月 04 22:22:37.6 [gae_proxy][DEBUG] network IPv6 is ok, cost:32613 ms
```

**Comment by xxnet** [comment]
请​升级pyOpenSSL 库

**Comment by rockwzy** [comment]
python2 Python3的openssl都是最新的，第一行'No module named pycparser'不再报错，但是AttributeError: 'module' object has no attribute 'load_publickey'仍然存在错误

**Comment by xxnet** [comment]
​pyOpenSSL 是哪个版本？
怀疑老的ubuntu ，其库没有升级。
可以试试先卸载，再用pip install python-pyOpenSSL 来安装

**Comment by rockwzy** [comment]
感谢您的解答，升级了python-OpenSSL之后解决了一个问题，但是后面还会出现以下异常：

```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wangziyi/applications/XX-Net-master/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/home/wangziyi/applications/XX-Net-master/code/default/gae_proxy/local/proxy.py", line 153, in main
    CertUtil.init_ca()
  File "/home/wangziyi/applications/XX-Net-master/code/default/gae_proxy/local/cert_util.py", line 606, in init_ca
    CertUtil.cert_publickey = OpenSSL.crypto.load_publickey(OpenSSL.crypto.FILETYPE_PEM, fp.read())
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2759, in load_publickey
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
```

ubuntu是比较老的版本，14.04
这是我outupdated的包，请问哪些需要被升级？

chardet (2.0.1) - Latest: 3.0.4 [wheel]
duplicity (0.6.23) - Latest: 0.7.14 [sdist]
httplib2 (0.8) - Latest: 0.10.3 [sdist]
lockfile (0.8) - Latest: 0.12.2 [wheel]
lxml (3.3.3) - Latest: 4.1.1 [wheel]
oauthlib (0.6.1) - Latest: 2.0.6 [sdist]
pexpect (3.1) - Latest: 4.3.0 [wheel]
Pillow (2.3.0) - Latest: 4.3.0 [wheel]
ply (3.4) - Latest: 3.10 [sdist]
pycups (1.9.66) - Latest: 1.9.73 [sdist]
pyserial (2.6) - Latest: 3.4 [wheel]
pysmbc (1.0.14.1) - Latest: 1.0.15.8 [sdist]
python-apt (0.9.3.5ubuntu2) - Latest: 0.7.8 [sdist]
python-debian (0.1.21-nmu2ubuntu2) - Latest: 0.1.31 [sdist]
reportlab (3.0) - Latest: 3.4.0 [wheel]
requests (2.2.1) - Latest: 2.18.4 [wheel]
urllib3 (1.7.1) - Latest: 1.22 [wheel]
zope.interface (4.0.5) - Latest: 4.4.3 [wheel]

**Comment by Peytonlan** [comment]
换种思路吧, Ubuntu 14.04嫌老, 就换16.04好了, 再不行换17.10
何必纠结在一个系统版本上不肯放手
Linux发行版这么多, 每个发行版又有多个版本, 这么多发行版及版本, 要让软件都适配到, 确实也让开发人员为难

**Comment by rockwzy** [comment]
非常抱歉。主要是因为有些工作需要在14.04上跑。如果是我自己用的linux我早就换最新的了。所以还是想问下有什么解决办法。

**Comment by Peytonlan** [comment]
以下说得有点多, 希望你能认真看下

不是说不能在 14.04 上运行 XX-Net, 但不同的软件对库的依赖可能不同, 迁就了 XX-Net, 你可能会运行其它软件出问题, 我不太赞成这样的解决方式 

并不需要你换主机系统
你需要了解下什么是容器, 也就是 LXC & LXD 和 Docker 这些

大致说下
运行在容器里的系统, 性能上和主机系统比起来, 几乎无差
有些人粗粗地了解下, 喜欢把 Docker 和 LXC 对立起来, 认为 LXC 是落后的, 不如 Docker 时髦
其实两者的应用场合并不太一样
Docker 面向的是应用, 更适合大规模同质化部署, 单一节点不易持续性升级系统
LXC & LXD 提供的更像一个完整的操作系统环境, 在容器内安装应用, 升级系统, 使用体验和在一个完全独立的操作系统上操作, 没什么差别
LXD 是建立在 LXC 基础上的, 算是 LXC 的升级版, 操作起来更现代化点(一般不需要直接编辑配置文件), 增强了面向企业的应用特性, 但目前能够很好运行 LXD 的系统并不多, 通用性现在并不太好
LXC 使用起来略微原始点, 但好处是, 不支持 LXC 的系统不多
即使 2.6 内核的 CentOS 6 上也可以通过 LXC 跑 Ubuntu 16.04
路由器上 OpenWrt 可以通过 LXC 运行 Debian

你提到有些工作需要在 14.04 上跑, 如果对环境没有什么特殊依赖, 也可尝试移到 LXC 里运行, 方便以后的系统迁移

去尝试用下 LXC 吧, 你会发现世界从此不一样

以下为在 14.04 上运行 16.04 的简单示例
apt -t trusty-backports install lxc
lxc-create -n xenial -t ubuntu -- -r xenial
lxc-start -n xenial
lxc-attach -n xenial

这个是目前官方支持的映像列表, 当然如果自己定制, 可以支持的更多
DIST	  RELEASE	ARCH	VARIANT	BUILD
alpine	3.4	amd64	default	20171206_17:50
alpine	3.4	armhf	default	20170111_20:27
alpine	3.4	i386	default	20171206_17:50
alpine	3.5	amd64	default	20171206_17:50
alpine	3.5	i386	default	20171206_17:50
alpine	3.6	amd64	default	20171206_17:50
alpine	3.6	i386	default	20171206_17:50
alpine	3.7	amd64	default	20171206_17:50
alpine	3.7	i386	default	20171206_17:50
alpine	edge	amd64	default	20171206_17:50
alpine	edge	armhf	default	20170111_20:27
alpine	edge	i386	default	20171206_17:50
archlinux	current	amd64	default	20171207_01:27
centos	6	amd64	default	20171207_02:16
centos	6	i386	default	20171207_02:16
centos	7	amd64	default	20171207_02:16
debian	buster	amd64	default	20171206_22:42
debian	buster	arm64	default	20171206_22:42
debian	buster	armel	default	20171206_22:42
debian	buster	armhf	default	20171206_22:42
debian	buster	i386	default	20171206_22:42
debian	buster	ppc64el	default	20171206_22:42
debian	buster	s390x	default	20171206_22:42
debian	jessie	amd64	default	20171206_22:42
debian	jessie	arm64	default	20171206_22:42
debian	jessie	armel	default	20171206_22:42
debian	jessie	armhf	default	20171206_22:42
debian	jessie	i386	default	20171206_22:42
debian	jessie	powerpc	default	20171206_22:42
debian	jessie	ppc64el	default	20171206_22:42
debian	jessie	s390x	default	20171207_03:04
debian	sid	amd64	default	20171206_22:42
debian	sid	arm64	default	20171206_22:42
debian	sid	armel	default	20171206_22:42
debian	sid	armhf	default	20171206_22:42
debian	sid	i386	default	20171207_03:04
debian	sid	powerpc	default	20171206_22:42
debian	sid	ppc64el	default	20171206_22:42
debian	sid	s390x	default	20171206_22:42
debian	stretch	amd64	default	20171206_22:42
debian	stretch	arm64	default	20171206_22:42
debian	stretch	armel	default	20171206_22:42
debian	stretch	armhf	default	20171206_22:42
debian	stretch	i386	default	20171207_03:04
debian	stretch	powerpc	default	20161104_22:42
debian	stretch	ppc64el	default	20171206_22:42
debian	stretch	s390x	default	20171206_22:42
debian	wheezy	amd64	default	20171206_22:42
debian	wheezy	armel	default	20171206_22:42
debian	wheezy	armhf	default	20171206_22:42
debian	wheezy	i386	default	20171207_03:04
debian	wheezy	powerpc	default	20171206_22:42
debian	wheezy	s390x	default	20171206_22:42
fedora	25	amd64	default	20171207_01:27
fedora	25	i386	default	20171207_01:27
fedora	26	amd64	default	20171207_01:27
fedora	26	i386	default	20171207_01:27
fedora	27	amd64	default	20171207_01:27
fedora	27	i386	default	20171207_01:27
gentoo	current	amd64	default	20171206_14:12
gentoo	current	i386	default	20171206_14:12
opensuse	42.2	amd64	default	20171207_00:53
opensuse	42.3	amd64	default	20171207_00:53
oracle	6	amd64	default	20171206_11:40
oracle	6	i386	default	20171206_11:40
oracle	7	amd64	default	20171206_11:40
plamo	5.x	amd64	default	20171206_21:36
plamo	5.x	i386	default	20171206_21:36
plamo	6.x	amd64	default	20171206_21:36
plamo	6.x	i386	default	20171206_21:36
ubuntu	artful	amd64	default	20171207_03:49
ubuntu	artful	arm64	default	20171207_03:49
ubuntu	artful	armhf	default	20171207_03:49
ubuntu	artful	i386	default	20171207_03:49
ubuntu	artful	ppc64el	default	20171207_03:49
ubuntu	artful	s390x	default	20171207_03:49
ubuntu	bionic	amd64	default	20171207_03:49
ubuntu	bionic	arm64	default	20171207_03:49
ubuntu	bionic	armhf	default	20171207_03:49
ubuntu	bionic	i386	default	20171207_03:49
ubuntu	bionic	ppc64el	default	20171207_03:49
ubuntu	bionic	s390x	default	20171206_03:49
ubuntu	trusty	amd64	default	20171207_03:49
ubuntu	trusty	arm64	default	20171207_03:49
ubuntu	trusty	armhf	default	20171207_03:49
ubuntu	trusty	i386	default	20171207_03:49
ubuntu	trusty	powerpc	default	20171207_03:49
ubuntu	trusty	ppc64el	default	20171206_03:49
ubuntu	xenial	amd64	default	20171207_03:49
ubuntu	xenial	arm64	default	20171207_03:49
ubuntu	xenial	armhf	default	20171207_03:49
ubuntu	xenial	i386	default	20171207_03:49
ubuntu	xenial	powerpc	default	20171207_03:49
ubuntu	xenial	ppc64el	default	20171207_03:49
ubuntu	xenial	s390x	default	20171207_03:49
ubuntu	zesty	amd64	default	20171207_03:49
ubuntu	zesty	arm64	default	20171207_03:49
ubuntu	zesty	armhf	default	20171207_03:49
ubuntu	zesty	i386	default	20171207_03:49
ubuntu	zesty	powerpc	default	20170317_03:49
ubuntu	zesty	ppc64el	default	20171207_03:49
ubuntu	zesty	s390x	default	20171207_03:49

**Comment by xxnet** [comment]
​学习了。

@
Ziyi Wang

你可以试试先卸载系统的pyOpenSSL 库，启动XX-Net 会尝试用自带的pyOpenSSL 库

**Comment by xxnet** [comment]
​ 3.8.7 修复上面的问题，请测试。

**Comment by rockwzy** [comment]
抱歉最近事情比较多。
@xxnet ubuntu14.04运行xxnet3.8.7正常，感谢您的修复。
@Peytonlan 感谢您的指点，我会抽空学习下您的建议。
