### ISSUE TITLE
Win10家庭版 XX-Net无法链接，开启IPv6隧道 失败

### ISSUE THREAD

**Issue by MG202018** [XX-net/XX-Net#8838]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:91 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 9
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

PS C:\WINDOWS\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

PS C:\WINDOWS\system32>

**Comment by gjbg1989** [comment]
use-ipv6: auto 改为只用 ipv6
scan-ip-thread-num: 9 改大到50，正常后改回
管理权限运行 netsh int ipv6 set teredo enterpriseclient default default default
netsh int ipv6 show teredo 贴运行结果

**Comment by gjbg1989** [comment]
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个

**Comment by gjbg1989** [comment]
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、关闭浏览器、重启 XX-Net、再稍侯，或机器重启。

**Comment by MG202018** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by MG202018** [comment]
PS C:\WINDOWS\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by MG202018** [comment]
还是无效，前天晚上使用了WINDOWS IPV6补丁和teredo.remlab.net还正常了一晚，然后就没有然后了

**Comment by gjbg1989** [comment]
正常了一晚—— #8620 tertdo.bat自动选用更好的服务器，或许就OK

**Comment by MG202018** [comment]
PS C:\WINDOWS\system32> netsh interface ipv6 reset
正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

**Comment by gjbg1989** [comment]
前天晚上使用了WINDOWS IPV6补丁——非补丁是工具

**Comment by MG202018** [comment]
最终原因终于找到：某些應用程式可能會在安裝該應用程式時設定這些登錄值，藉此停用 Teredo，但也有些應用程式會在每次啟動時設定這些值。如果您的電腦安裝了其中一個應用程式，請確定您已更新為最新版本，或請參閱應用程式的支援文件，了解如何使用應用程式軟體啟用 Teredo 通道功能。
如* Asus Game First Service：

**Comment by MG202018** [comment]
谢谢@gjbg1989
