### ISSUE TITLE
【已解决】Teredo通道时不时开机就自动关闭？如何解决

### ISSUE THREAD

**Issue by Apathy94** [XX-net/XX-Net#8866]
用过微软的修复工具了，重启之后确实能够翻墙了，但是隔几天teredo就有自己关闭，显示错误未打开隧道适配器

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo-debian.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by gjbg1989** [comment]
确保系统服务IP Helper 为自动并已启动，先前修改的ipv6组策略退回到默认值的全部“未配置”，结束进程pythonw.exe，先管理权限运行3.7.11版XX-Net目录内disable_ipv6.bat，再enable_ipv6.bat即可。

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8620 tertdo.bat自动选用更好的服务器

**Comment by gjbg1989** [comment]
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个。
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、关闭浏览器、重启 XX-Net、再稍侯，或机器重启。禁用再启用网络也许行

**Comment by GoodSake** [comment]
机器重启。。。。我想5年不重启，老天姐你能帮我实现这个愿望吗！

**Comment by gjbg1989** [comment]
禁用系统升级，配后备电源，设置开启睡眠😱

**Comment by Apathy94** [comment]
用这个方法可以不用重启解决teredo通道关闭问题，至于以后能不能确保teredo通道会不会自己关闭有待验证。确保系统服务IP Helper 为自动并已启动，先前修改的ipv6组策略退回到默认值的全部“未配置”，结束进程pythonw.exe，先管理权限运行XX-Net目录内disable_ipv6.bat，再enable_ipv6.bat即可。
