### ISSUE TITLE
安装后浏览器代理设置和CA证书状态一直为Fail，提示“请检查浏览器代理设置”，已试过多种方法未解决

### ISSUE THREAD

**Issue by tshykj** [XX-net/XX-Net#8878]
* 简单描述遇到的问题：
安装后浏览器代理设置和CA证书状态一直为Fail，提示“请检查浏览器代理设置”，已试过多种方法未解决，一直无法使用，打不开任何网站。在Chrome证书里确认已经安装了证书。

* 做过哪些尝试：
一、用此解决方法无效。

1.删除已导入的证书文件（运行certmgr.msc和certlm.msc，然后自己找到xxnet删），
2.更新3.3.1（或是自己找到那行代码取消注释，楼下有人提及）
3.删除data文件夹（下的certs文件夹和CA.crt文件）
4.正常初始化（反正到这就结束了吧？，进入正常流程了）重新导入xxnet证书

二、安装火狐浏览器最新版问题依旧

三、安装58.X版本Chrome问题依旧

四、升级到最新版Chrome问题依旧，使用了58~62的多个版本都未解决

五、IPV6的组策略法反复做过两三次（设置“未配置”——重启——设置“启用”——重启）

六、在本地连接属性里已经取消了IPV6协议

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: force_ipv6
gws-ip-num: total:3155 ipv4:0 ipv6:2770
ipv4-status: OK
ipv6-status: OK
connected-link: new:10 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 397
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

================================================

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.3.201:49667
外部 NAT 映射    : 27.224.104.5:49061

   
请大家帮帮我吧，整了好几天没解决，谢谢

**Comment by gjbg1989** [comment]
确保系统服务IP Helper 为自动并已启动，先前修改的ipv6组策略退回到默认值的全部“未配置”，结束进程pythonw.exe，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个文件，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 贴运行结果

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8874

**Comment by gjbg1989** [comment]
IPV6貌似正常，
proxy_state: Fail——代理扩展的选用或设置问题？
ca_state: Fail——上面不正常引发或证书问题
参考：#8687

**Comment by gjbg1989** [comment]
现在这个扩展都影响XX-Net的正常与否
![default](https://user-images.githubusercontent.com/13290970/33674716-3d16901c-daeb-11e7-8400-fc33b49d23c7.png)

**Comment by tshykj** [comment]
谢谢各位的回复


使用微软的修复工具那条回复找不到了，我按着方法做过之后的结果如下

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant



==================================

PS：在纯净的Chrome和火狐上问题依旧估计与插件无关；Ctrl+F5也没有解决问题；在纯净版和非纯净版浏览器上均使用过SwitchyOmega，也无法解决问题。

**Comment by gjbg1989** [comment]
使用微软的修复工具那条回复找不到了——因：IPV6貌似正常——删除了
状态 : dormant——未运行XX-Net前的休眠正常状态
类型 : disabled——与 ipv6-status: OK 貌似矛盾，#8620 tertdo.bat自动选用更好的服务器，或许就OK
proxy_state: Fail
ca_state: Fail——前面已解释，貌似你的结论有误。可通过以下方法检验：
在纯净的Chrome里禁用扩展SwitchyOmega，用XX-Net的3个全局代理任一均可测试

**Comment by gjbg1989** [comment]
上传图片一直报错——代理问题？该网貌似可直连？

**Comment by gjbg1989** [comment]
用XX-Net的3个全局代理，配合火狐自身的正确代理设置（禁用代理扩展）同样。。。

**Comment by tshykj** [comment]
谢谢回复

> 类型 : disabled——与 ipv6-status: OK 貌似矛盾，#8620 tertdo.bat自动选用更好的服务器，或许就OK
proxy_state: Fail
------这个bat似乎有误，我的安装路径为D:\Program Files\XX-Net-3.8.4，运行bat之后提示“    ‘D:\Program ’不是内部或外部命令，也不是可执行的程序或批处理 请按任意键继续”

> ca_state: Fail——前面已解释，貌似你的结论有误。可通过以下方法检验：
在纯净的Chrome里禁用扩展SwitchyOmega，用XX-Net的3个全局代理任一均可测试
-----可能我表达有误，我的意思是在纯净的Chrome里用xx-net不行，然后只安装SwitchyOmega之后，使用SwitchyOmega也不行。

> 上传图片一直报错——代理问题？该网貌似可直连？
------github被墙了么？我一直直连github，全局代理模式就打不开任何网站。PAC模式就是通过代理的网站打不开，直连的网站正常。

**Comment by gjbg1989** [comment]
这个bat似乎有误——有人说加2引号即可，如下：
@echo off

"%~dp0"code\default\python27\1.0\python.exe "%~dp0teredo.py"
pause

**Comment by gjbg1989** [comment]
试试：下载3.8.5版 
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by gjbg1989** [comment]
有可能，试试清除Chrome。。。
![image](https://user-images.githubusercontent.com/13290970/33695225-19285f36-db37-11e7-94ca-9da3a446d78f.png)

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33695471-7d009cca-db38-11e7-9d2c-0f87c6e695a8.png)
未运行XX-Net前的休眠状态——IPv6完全正常

**Comment by tshykj** [comment]
这个bat似乎有误——有人说加2引号即可，如下：
@echo off

"%~dp0"code\default\python27\1.0\python.exe "%~dp0teredo.py"
pause

> 我自己加怎么就不行，复制你的就可以，我是英文标点啊，现在已经更换了服务器，但是问题又来了，XX-NET打不开Chrome，说Chrome未响应然后自行输入192.168.3.201:8085也打不开，可是127.0.0.1:8085可以打开，但是问题依旧

Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.3.201:63127
外部 NAT 映射    : 42.91.103.239:37144


=====================================

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: force_ipv6
gws-ip-num: total:4618 ipv4:0 ipv6:4193
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
gws-ip-num: total:3155 ipv4:0 ipv6:2770
gws-ip-num: total:3949 ipv4:0 ipv6:3524
以上数字说明先前正常使用过？

**Comment by tshykj** [comment]
gws-ip-num: total:3155 ipv4:0 ipv6:2770
gws-ip-num: total:3949 ipv4:0 ipv6:3524
以上数字说明先前正常使用过？

我一直都能检测到可用的IPV6但是就是不通，用代理连不上网，我现在看可用IPV6地址已经4k多了，但是问题依旧

**Comment by gjbg1989** [comment]
删除chrome里的代理插件，安装XX-Net目录里的并导入bak

**Comment by gjbg1989** [comment]
我一直都能检测到可用的IPV6但是就是不通——从没正常过？

**Comment by tshykj** [comment]
> 删除chrome里的代理插件，安装XX-Net目录里的并从bak恢复设置

问题未解决

> 我一直都能检测到可用的IPV6但是就是不通——从没正常过？

最初xx-net改IPV6时第一次按着教程设置后正常过，但是重启之后就再也连不上了，那之后我一直用自己的SS，可用xx-net看或者下载YouTube快，最近又想在YouTube下东西，但是就是一直连接不上。

**Comment by gjbg1989** [comment]
最后一招：
确保系统服务IP Helper 为自动并已启动，先前修改的ipv6组策略退回到默认值的全部“未配置”，结束进程pythonw.exe，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 贴结果

**Comment by gjbg1989** [comment]
有说重新装下系统1709会自动配置正常（疑是代理的问题，这也没用）

**Comment by gjbg1989** [comment]
没辙，88😂

**Comment by gjbg1989** [comment]
😱状态 : dormant——未运行XX-Net前的休眠状态——IPv6完全正常😂

**Comment by tshykj** [comment]
真心不想做系统呀要装的软件太多太麻烦，谢谢你了，就是这个证书一直不OK，但是也按着教程删除后重新添加了就是不OK

**Comment by gjbg1989** [comment]
就是这个证书一直不OK——首先是代理的问题，代理正常、证书错误的网页提示，貌似是报证书。。。。

**Comment by gjbg1989** [comment]
清空系统代理。。。

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33697683-15c48052-db43-11e7-98a2-d78c5d97d385.png)

**Comment by gjbg1989** [comment]
不会是XX-Net自身代理与插件代理的不配套，这个低级错误？

**Comment by tshykj** [comment]
> 清空系统代理。。。
如何清空？图中的代理设置，与我xx-net设置为“取消全局代理”时的系统一致呀

**Comment by gjbg1989** [comment]
🤣黔驴技穷，88

**Comment by gjbg1989** [comment]
#8874 (comment)
![image](https://user-images.githubusercontent.com/13290970/33698178-d18b2e7e-db45-11e7-8473-91507c9d3f86.png)

**Comment by gjbg1989** [comment]
[2017.03.12]MyChrome v3.8.1-可自动更新的Google Chrome便携版_Chrome_浏览器讨论区 卡饭论坛 - 互助分享 - 大气谦和! - https://bbs.kafan.cn/thread-1725205-1-1.html …😂整个便携版试试

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33698860-3cdc1266-db4a-11e7-8697-e0dbe5d8271f.png)

**Comment by tshykj** [comment]
> use-ipv6: auto 改为只用ipv6
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个。

未解决

> 确保系统服务IP Helper 为自动并已启动，先前修改的ipv6组策略退回到默认值的全部“未配置”，结束进程pythonw.exe，先管理权限运行3.7.11版XX-Net目录内disable_ipv6.bat，再enable_ipv6.bat即可正常开启、使用ipv6隧道。

之前做过，再试一遍，刚才发现我的“IP 转换配置服务”处于手动启动状态且未启动，再试一遍

**Comment by tshykj** [comment]
运行“enable_ipv6.bat”后的返回结果与日志



> Get Admin
[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。

正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

确定。

确定。

确定。

确定。

确定。

确定。

路由删除失败: 找不到元素。

确定。

确定。

确定。

操作成功完成。
操作成功完成。
确定。

确定。

确定。

确定。

确定。

确定。

 操作完成!
确定。

确定。

确定。

操作成功完成。

Windows IP 配置

已成功刷新 DNS 解析缓存。


=========================日志======================

> Windows IP 配置

   主机名  . . . . . . . . . . . . . : ******************
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Intel(R) Ethernet Connection (2) I219-V #2
   物理地址. . . . . . . . . . . . . : ***************
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 4:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   物理地址. . . . . . . . . . . . . : *******************
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN 3:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : TP-LINK Wireless USB Adapter #2 #2
   物理地址. . . . . . . . . . . . . : *********************
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.3.201(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2017年12月7日 星期四 12:58:44
   租约过期的时间  . . . . . . . . . : 2017年12月8日 星期五 12:58:44
   默认网关. . . . . . . . . . . . . : 192.168.3.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.3.1
   DNS 服务器  . . . . . . . . . . . : 192.168.3.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

隧道适配器 Teredo Tunneling Pseudo-Interface:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 2001:0:53aa:64c:8f6:****:****:9810(首选) 
   本地链接 IPv6 地址. . . . . . . . : fe80::8f6:****:****:9810%6(首选) 
   默认网关. . . . . . . . . . . . . : ::
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant


发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        手动        256  ::/0                        6  Teredo Tunneling Pseudo-Interface
否        系统        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        手动        256  2001::/32                   6  Teredo Tunneling Pseudo-Interface
否        系统        256  2001:0:53aa:64c:8f6:****:****:9810/128    6  Teredo Tunneling Pseudo-Interface
否        系统        256  fe80::/64                   9  以太网 2
否        系统        256  fe80::/64                   8  本地连接* 4
否        系统        256  fe80::/64                   6  Teredo Tunneling Pseudo-Interface
否        系统        256  fe80::8f6:784a:****:****/128    6  Teredo Tunneling Pseudo-Interface
否        系统        256  fe80::7126:****:****:9b3d/128    9  以太网 2
否        系统        256  fe80::a439:****:****:8168/128    8  本地连接* 4
否        系统        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        系统        256  ff00::/8                    9  以太网 2
否        系统        256  ff00::/8                    8  本地连接* 4
否        系统        256  ff00::/8                    6  Teredo Tunneling Pseudo-Interface


Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  6          75        1280  connected     Teredo Tunneling Pseudo-Interface
  9           5        1500  disconnected  以太网 2
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
  8          25        1500  disconnected  本地连接* 4

查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        30      1  2002::/16
         5      1  2001::/32


接口 6: Teredo Tunneling Pseudo-Interface

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
公用         首选项           infinite   infinite 2001:0:53aa:64c:8f6:****:****:****
其他         首选项           infinite   infinite fe80::***:****:****:9810%6

接口 9: 以太网 2

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::****:****:****:9b3d%9

接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 8: 本地连接* 4

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::****:****:****:8168%8

===========================================================================
接口列表
  9...** ** ** ** ** ** ......Intel(R) Ethernet Connection (2) I219-V #2
  8...** ** ** ** ** ** ......Microsoft Wi-Fi Direct Virtual Adapter #2
 17...** ** ** ** ** ** ......TP-LINK Wireless USB Adapter #2 #2
  1...........................Software Loopback Interface 1
  6...00 00 00 00 00 00 00 e0 Teredo Tunneling Pseudo-Interface
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.3.1    192.168.3.201     35
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      192.168.3.0    255.255.255.0            在链路上     192.168.3.201    291
    192.168.3.201  255.255.255.255            在链路上     192.168.3.201    291
    192.168.3.255  255.255.255.255            在链路上     192.168.3.201    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.3.201    291
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.3.201    291
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  6    331 ::/0                     在链路上
  1    331 ::1/128                  在链路上
  6    331 2001::/32                在链路上
  6    331 2001:0:53aa:64c:***:****:****:9810/128
                                    在链路上
  6    331 fe80::/64                在链路上
  6    331 fe80::8f6:****:****:9810/128
                                    在链路上
  1    331 ff00::/8                 在链路上
  6    331 ff00::/8                 在链路上
===========================================================================
永久路由:
 接口跃点数网络目标                网关
  0 4294967295 ::/0                     在链路上
===========================================================================

**Comment by gjbg1989** [comment]
天书
代理问题，折腾已正常的teredo也白瞎😂
整个便携版_Chrome乃正道

**Comment by tshykj** [comment]
> 天书
代理问题，折腾已正常的teredo也白瞎😂
整个便携版_Chrome乃正道

便携版从卡饭已下，问题依旧未解决

**Comment by gjbg1989** [comment]
真心不想做系统呀要装的软件太多太麻烦——能否整双系统——新的。。。
32Win7Pro上整的32Win10Pro，系统自动配置好的IPv6。。。

**Comment by mengmengniao** [comment]
那个插件，似乎只要一修改，证书就有问题，不懂为什么。我之前修改过个别规则，但证书就是不行，不过依然能FQ，另外强制6才可以上，自动就是连不上（4有100多的ip，6有7K多。）。

**Comment by gjbg1989** [comment]
那个插件，似乎只要一修改，证书就有问题——貌似不会

**Comment by xxnet** [comment]
可以试试 系统托盘中的菜单，选择全局 GAE代理，然后用IE 或Edge访问 127.0.0.1：8085
问题应该出在代理切换上。 IPv6是通的。

**Comment by gjbg1989** [comment]
127.0.0.1：8085 当心全角冒号😂 127.0.0.1:8085

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33791614-5f2e5f4c-dcc9-11e7-935f-260e59d5f6e2.png)
基于：现在这个扩展都影响XX-Net的正常与否
禁用chrome全部扩展，采用XX-Net自身代理开关。。。

**Comment by tshykj** [comment]
现在问题已解决
具体方法为：
1.没有改变之前的IPV6、浏览器等系统设置一切保持原样
2.卸载谷歌浏览器，完全卸载不保留任何数据
3.删除XX-NET
4.安装最新版谷歌浏览器，不登陆账号不做任何设置
5.安装最新版XX-NET
6.成功
我之前也重做系统试过还是不成功，我觉得问题应该在浏览器的账户同步上，因为相对这次，做系统肯定更清洁，但是不成功，和这次唯一的区别就是上次先设置好浏览器所有设置，包括登陆账号同步数据，希望对大家有帮助。

**Comment by gjbg1989** [comment]
同步正常。。。
中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6
