### ISSUE TITLE
Windows 10下，XX-Net依旧卡

### ISSUE THREAD

**Issue by xiuluo** [XX-net/XX-Net#888]
能不能让用户设置扫描间隔？

**Comment by xxnet** [comment]
这个猜测是windows10 的驱动实现机制有问题，建立网络连接和声音播放争用某个资源，比如某个全局锁或什么不知道的缓冲区之类。。。。

在 2015年8月30日 下午5:50，Shura <notifications@github.com>写道：

**Comment by malthae** [comment]
我已经习惯了。。。而且完全可以接受
另外好像只有播放本地视频会卡
油管和优酷之类的没有出现过这种现象
