### ISSUE TITLE
ＩＤＭ用xxnet下youtube视频现在一直失败

### ISSUE THREAD

**Issue by clawshadow** [XX-net/XX-Net#8880]
开会前一段时间，看youtube，点右上角ＩＤＭ下载，ＩＤＭ下视频很快也很正常
现在点下载后，下载完成后，双击打开文件，显示的是文件已经移除
就感觉很奇怪了
是youtube升级了防范措失吗？
还是因为xxnet代理经常换ip导致的？
用了很多油猴插件，一样无法下载

**Comment by gjbg1989** [comment]
ＩＤＭ设置？

**Comment by GoodSake** [comment]
用Google Chrome自带的下载就很好。IDM该淘汰了。

**Comment by clawshadow** [comment]
不是IDM的问题，已经找出原因，还是cookie的问题，xxnet频繁换ｉｐ，用油猴插件下视频时，经常出现cookie提示，实际上chrome已经打开了ｃｏｏｋｉｅ
