### ISSUE TITLE
总是“尚未建立连接”，如何解决？

### ISSUE THREAD

**Issue by waylenz** [XX-net/XX-Net#8883]
最近这段时间总是“尚未建立连接”
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
use-ipv6: auto
gws-ip-num: total:4968 ipv4:1 ipv6:2106
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 301
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果

**Comment by waylenz** [comment]
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问主 teredo 服务器

**Comment by GoodSake** [comment]
teredo是高科技啊，不是每个人都能简单实现的哦。

**Comment by gjbg1989** [comment]
结束进程pythonw.exe，先管理权限运行3.7.11版XX-Net目录内disable_ipv6.bat，再enable_ipv6.bat
#8620 tertdo.bat自动选用更好的服务器

**Comment by whhxmwhh** [comment]
teredo是高科技啊，不是每个人都能简单实现的哦。
我的也是哦。
![0](https://user-images.githubusercontent.com/7959854/33699384-d3119c62-db4d-11e7-99b8-b46edba0e08c.JPG)

**Comment by whhxmwhh** [comment]
![default](https://user-images.githubusercontent.com/7959854/33699425-19bf0e1a-db4e-11e7-9ebf-d4a0e898b272.JPG)
我可以设置为手动启动吗？今天网络好像是启用白名单了。基本网络都不能访问了。

**Comment by gjbg1989** [comment]
@whhxmwhh 什么意思？

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33699679-8f99b2ba-db4f-11e7-855c-b6de4afcb1d0.png)

**Comment by gjbg1989** [comment]
https://github.com/out0fmemory/Goproxy-Always-Available/issues/21

**Comment by whhxmwhh** [comment]
我那个项目也是不能实现。你有那个项目的上传文档吗？
我发现这个项目有个好处就是稳定一点。要吗是活要吗是死。。
我门这里今天实行新的网络封锁机制。所以上不来。见谅。

**Comment by gjbg1989** [comment]
@whhxmwhh 
[TCPIP6.zip](https://github.com/XX-net/XX-Net/files/1539638/TCPIP6.zip)

**Comment by waylenz** [comment]
以下方式及杀进程，重启等均尝试过，无效
试了disable_ipv6.bat，再enable_ipv6.bat
 用了tertdo.bat
注册表加了disablecomponent, 设为0
WiFi的属性设置中，取消了ipv6勾选
升级到了3.8.6
设置强制ipv6
目前XX-Net Status和netsh结果如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4219 ipv4:0 ipv6:2281
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 361
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

C:\Users\waylen>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.trex.fi
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (address)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.1.106:54080
外部 NAT 映射    : 183.53.65.8:25911

**Comment by waylenz** [comment]
另外，偶尔会显示可以访问真正的互联网，但仍然无法访问，而且很快会变成“尚未建立连接”

**Comment by gjbg1989** [comment]
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6
貌似一切正常，换下服务器，管理权限运行 netsh interface teredo set state server=teredo.iks-jena.de
出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。
https://github.com/XX-net/XX-Net/issues/8961

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by gjbg1989** [comment]
偶尔会显示可以访问真正的互联网，但仍然无法访问，而且很快会变成“尚未建立连接”——不会系统有360、管家之流。。。

**Comment by waylenz** [comment]
@gjbg1989
1.   DNS指向本地的话，无法访问任何网站
![pic](https://user-images.githubusercontent.com/19546561/33876029-34549820-df5f-11e7-8e3c-1039a7358297.jpg)
2. IPV6 自动转换已设置，访问IPv6测试网站，提示没有检测到IPV6地址
 http://test-ipv6.com/index.html.zh_CN
![ipv6](https://user-images.githubusercontent.com/19546561/33876196-c3cee226-df5f-11e7-81ba-59be6955f38f.jpg)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33876825-8ebe6316-df61-11e7-9287-000d26cff44b.png)

**Comment by waylenz** [comment]
smart router是打开的，默认就是打开
![image](https://user-images.githubusercontent.com/19546561/33878881-a9083d36-df67-11e7-901a-0b247ef57011.png)

**Comment by waylenz** [comment]
截图

![route](https://user-images.githubusercontent.com/19546561/33879119-62541bc0-df68-11e7-8e7b-758b894801fe.jpg)

**Comment by gjbg1989** [comment]
结束进程pythonw.exe、重启 XX-Net

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by gjbg1989** [comment]
5天前整没整好没后话。。。
先不采用DNS 127.0.0.1
结束进程 pythonw.exe，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33881144-de934f16-df6e-11e7-85a2-991915a7042f.png)
拒绝回答？

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33881307-6171a5cc-df6f-11e7-9414-a5049fff7806.png)
禁用再启用网络，运行XX-Net
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by gjbg1989** [comment]
😱首先得ipv4-status:正常
终极方法：
结束进程pythonw.exe，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。

**Comment by gjbg1989** [comment]
😂不配合，想解决。。。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8979#issuecomment-351026384 https://github.com/XX-net/XX-Net/issues/8974#event-1383329443 。。。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8978#issuecomment-351027666

**Comment by waylenz** [comment]
先回答大神的问题
1.  5天前没有搞好
2. 360 是有，但后来关掉了也仍然有同样的问题（显示可以访问，实际无法访问，很快变成未建立连接）
3. DNS是因为今天本机上指定了IP，所以也必须指定DNS。原因是 看了几个帖子说要固定内网IP，就这么搞了一下。原本是用路由器DHCP自动分配的，不用指定DNS。 不过结果都一样。
4. IPV4 现在是正常的，也许当时反馈太快了？
其他操作我尝试下。
现在的状态（DNS是路由器DNS，可以百度，仍然尚未建立链接）
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4219 ipv4:0 ipv6:1794
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 944
is-idle: 0
block-stat: Connect Blocked, 1 seconds to wait.
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
固定内网IP——需在路由器上解决，电脑仍然自动获取
netsh int ipv6 show teredo 贴运行结果

**Comment by gjbg1989** [comment]
XX-Net未正常前，建议关闭360

**Comment by waylenz** [comment]
现在按终极方案运行（尚未运行xx-net）,IP改为自动获取，netsh int ipv6 show teredo 结果如下
C:\Users\waylen>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.iks-jena.de
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by waylenz** [comment]
接上面，启动xx-net, 还是"尚未建立连接”
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4219 ipv4:0 ipv6:1844
ipv4-status: OK
ipv6-status: unknown
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 300
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
此时运行 netsh,结果如下
![ter](https://user-images.githubusercontent.com/19546561/33886509-c3fac234-df81-11e7-998b-70f55f32d2c7.jpg)

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by gjbg1989** [comment]
或将防火墙重置默认

**Comment by waylenz** [comment]
自动重选win10服务器，结果还是相同
C:\Users\waylen>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问主 teredo 服务器

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33887997-a1934f40-df86-11e7-8de8-f79106bb7757.png)
此时是正常的，但运行XX-Net的结果貌似又不正常，当然不能立竿见影，需要运行些时间。。。

**Comment by gjbg1989** [comment]
结束进程pythonw.exe，管理权限运行
netsh int ipv6 set teredo enterpriseclient default default default
启动XX-Net，让它运行些时间。。。

**Comment by gjbg1989** [comment]
期间可以多次刷新或重载控制页，
netsh int ipv6 show teredo 查看是否正常

**Comment by waylenz** [comment]
结束进程pythonw.exe，管理权限运行
netsh int ipv6 set teredo enterpriseclient default
启动XX-Net，让它运行些时间。。。
--------------------------------------------
已执行，反复运行 netsh int ipv6 show teredo 有三种情况：
1. 
![p1](https://user-images.githubusercontent.com/19546561/33938258-c6abe98e-e041-11e7-8f75-b6ef447e8a03.jpg)
2. 
![p2](https://user-images.githubusercontent.com/19546561/33938266-cc52e48c-e041-11e7-9d7d-03073e172427.jpg)
3. 
![p3](https://user-images.githubusercontent.com/19546561/33938273-d25c8c66-e041-11e7-9ca8-288efe59f07e.jpg)

**Comment by gjbg1989** [comment]
1、不正常
2、趋近正常
3、已正常

**Comment by waylenz** [comment]
3 同样显示尚未建立连接，刚刚3， 现在又变成2

**Comment by waylenz** [comment]
另外，现在无线链接中的IPV6复选框是去除的，昨天执行终极解决方案后，没有重新执行3.7.11 的disable和enable

**Comment by gjbg1989** [comment]
能有助稳定、观察到变化过程的 bat ，https://github.com/XX-net/XX-Net/issues/8919#issuecomment-350661237
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by waylenz** [comment]
netsh还在三种状态中切换，服务器不稳定？

**Comment by gjbg1989** [comment]
3 同样显示尚未建立连接，刚刚3， 现在又变成2——建议卸载流氓360
现在无线链接（？）中的IPV6复选框是去除的——不建议，不反对
执行终极解决方案后，没有重新执行3.7.11 的disable和enable——不需要

**Comment by gjbg1989** [comment]
netsh还在三种状态中切换，服务器不稳定？——貌似不应该，怀疑360

**Comment by waylenz** [comment]
上述结果是已经卸载了360的结果，进程中没有看到任何360的进程

**Comment by gjbg1989** [comment]
你是无线链接？已经卸载了360的结果——卸载与执行终极解决方案，谁前谁后？

**Comment by waylenz** [comment]
是无线链接，链接无线路由器。
执行终极解决方案是昨天，卸载是今天，今天发的结果是卸载后的结果。

**Comment by gjbg1989** [comment]
无线链接——笔记本，我的所有建议为台机
执行终极解决方案是昨天，卸载是今天——再来一次终极方案。。。

**Comment by waylenz** [comment]
近期出差，很久没有回这个帖子了。
按照gjbg大神的建议，换了台win7的台式机有线连接路由器测试。结果基本相同，还是”尚未建立链接“
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:1 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
![image](https://user-images.githubusercontent.com/19546561/34330761-510aa38c-e95b-11e7-9804-cece119edf22.png)
另外还有一种可能的结果是offline,没有qualified的结果。
系统已卸载杀毒软件，另：ipconfig /all 中，看到了teredo适配器分配了ipv6地址
![image](https://user-images.githubusercontent.com/19546561/34330802-d7d607c6-e95b-11e7-8a3a-01f14e59a906.png)
我自己怀疑是路由器不支持IPV6？ 路由器是普通路由器TPLINK TL_WR886N

**Comment by gjbg1989** [comment]
gws-ip-num: total:0 ipv4:1 ipv6:0——能不”尚未建立链接“？
貌似与路由器无关？
状态 : probe (primary server) 是接近正常的前状态，试试换服务器（前面已告知方法？）
耐心将前面的各法走一次。。。

**Comment by nttaoboy** [comment]
![image](https://user-images.githubusercontent.com/31844904/34348580-ad1deb0c-ea46-11e7-8776-0e999da32f32.png)

![image](https://user-images.githubusercontent.com/31844904/34348603-dafb6aa4-ea46-11e7-9ea9-9ddb88990e7b.png)

但GAEProxy状态信息一直显示
尚未建立连接

求助 @gjbg1989

**Comment by gjbg1989** [comment]
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。
#8620 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by waylenz** [comment]
今天重新试了win10开启IPV6的操作，并使用xx-net 3.11.3,结果一轮顺畅，直接成功（以前test-ipv6.com测试从未成功过）。
感谢gjbg1989大神的指导，不知道以前总是失败是什么原因, 自己怀疑是win10的版本问题。（这几个月期间win10打过官方升级包）

**Comment by gjbg1989** [comment]
有问题，参考：#10184
