### ISSUE TITLE
data 升级机制似乎有bug

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#89]
干净目录，切换到1.5.0，启动，正常。退出，保留data目录，切换到1.5.1，启动，网页端崩溃。
显示错误 `IOError: [Errno 2] No such file or directory: ...
\XX-Net\\launcher\\1.1.0\\web_ui\\index.html'`
1.5.1中的目录已经是1.1.1。config.yaml 中仍是 `launcher: {auto_start: 0, current_version: 1.1.0}`

1.5.3似乎同样。启动日志第一条是 `launcher version: 1.1.0`。

**Comment by xxnet** [comment]
是的，这个我也发现了，是有问题的，逻辑是这样的：
  config.yaml 中是老的版本，比如1.1.0
  而通过git 已经升级到1.1.1

我刚刚提交一个版本 1.5.5
  启动时，发现模块版本不存在，会自动扫描新的版本号。

2015-03-30 3:33 GMT-04:00 YFdyh000 <notifications@github.com>:

**Comment by yfdyh000** [comment]
好像并没有用，仍然显示 launcher version: 1.1.0，仍然崩溃。
好像未涉及config.py，直接在start.py就通过并继续了（用start.bat启动）。
将config.yaml中的版本号改为1.1.0来测试。

**Comment by xxnet** [comment]
我现在测试是，下载1.5.5，解压后，放入data目录是1.5.0生成的，
 启动正常。

你把异常日志和data/launcher/config.yaml 文件贴出来

在 2015年3月30日 上午4:59，YFdyh000 <notifications@github.com>写道：

**Comment by xxnet** [comment]
新版已经修复，每次启动时，会检查版本目录是否存在，不存在会重新扫描。

**Comment by yfdyh000** [comment]
@xxnet 感觉仍有问题，因为目录中有pyc和upload.log等文件，所以目录不会为空，除非手动删除。

**Comment by xxnet** [comment]
upload.log不会有影响
pyc文件，data目录下没有吧
goagent/launcher都在新的目录了，也应该没有影响的。

能否给出重现的步骤？

**Comment by yfdyh000** [comment]
这里检测的是/goagent和/launcher目录吧，每次目录更替后都会留下一个残留目录，里面有运行过的pyc和upload.log文件。某次偶然发现，好像一直使用的还是旧版本，至少日志显示的版本号是那样。
手动删除目录之后，启动日志才有检测到新版本的日志。不太确定。

**Comment by xxnet** [comment]
是这样的：
如果是git 升级的方式，不会自动切换到最新的版本，需要修改配置文件指定到最新的版本。
以后实现一套模块、版本管理界面再解决。

设计的考虑是：
允许磁盘上同时存在多个版本；
允许用户指定使用某个版本，除非该版本不存在，才会帮用户扫描一个能用的版本。

暂时先这样吧。。。辛苦一下，为后面升级准备。

在 2015年4月6日 上午8:53，YFdyh000 <notifications@github.com>写道：

**Comment by yfdyh000** [comment]
目前这样有版本目录但实际不能用挺坑的，还增加了不少问题。
如果是等版本系统弄好了再上版本号目录就好了……

**Comment by xxnet** [comment]
1.8.x 解决了老用户升级后，PHP模块不会自动加载问题

**Comment by xxnet** [comment]
在实现模块版本管理前，暂停升级模块版本号。
只在需要发布自动升级时才会升级模块版本号。
方便git方式升级。
