### ISSUE TITLE
Debian 启动时报 import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)

### ISSUE THREAD

**Issue by cloudfstrife** [XX-net/XX-Net#8903]
* 是否试过最新的测试版本？
未使用， XX-Net Version:3.8.5

* 是否看过Issues区最近的讨论？
已搜索，但未解决

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
已查看，但未解决

* 简单描述遇到的问题：
Debian Stretch ，使用./start 启动时报错
import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)

* 做过哪些尝试：
尝试安装最新的pyopenssl模块，但是依然失败。

* 请贴出对应模块的状态页

> XX-Net Status:
> 
> sys-platform: x86_64, Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
> os-system: Linux
> os-version: #1 SMP Debian 4.9.51-1 (2017-09-28)
> os-release: 4.9.0-4-amd64
> os-detail: Dist:debian; Version:9.2; ID:
> architecture: 64bit,
> browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
> xxnet-version: 3.8.5
> python-version: 2.7.13
> openssl-version: 17.5.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: auto
> gws-ip-num: total:0 ipv4:0 ipv6:0
> ipv4-status: OK
> ipv6-status: Fail
> connected-link: new:0 used:0
> worker: h1:0 h2:0
> scan-ip-thread-num: 10
> ip-quality: 9999
> is-idle: 0
> block-stat: OK
> proxy_state: OK
> ca_state: OK
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: true

* 请贴出相关的日志
> XX-Net version:default
> 12月 08 06:35:25.9 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
> 12月 08 06:35:25.9 [launcher][INFO] start XX-Net 3.8.5
> 12月 08 06:35:25.9 [launcher][DEBUG] start confirm_xxnet_exit
> 12月 08 06:35:25.9 [launcher][DEBUG] good, xxnet:8085 clear!
> 12月 08 06:35:25.9 [launcher][DEBUG] finished confirm_xxnet_exit
> 12月 08 06:35:26.0 [gae_proxy][INFO] SSL use version:TLSv1_2
> 12月 08 06:35:26.0 [gae_proxy][INFO] OpenSSL support alpn
> 12月 08 06:35:26.0 [gae_proxy][INFO] load ip range file:/opt/XX-Net-3.8.5/code/default/gae_proxy/local/ip_range.txt
> 12月 08 06:35:26.0 [gae_proxy][INFO] load google ip_list num:0, gws num:0
> 12月 08 06:35:26.0 [gae_proxy][WARNING] no enough ip
> 12月 08 06:35:26.0 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
> 12月 08 06:35:26.0 [gae_proxy][INFO] ------------------------------------------------------
> 12月 08 06:35:26.0 [gae_proxy][INFO] Python Version     : 2.7.13
> 12月 08 06:35:26.0 [gae_proxy][INFO] OS                 : Dist:debian; Version:9.2; ID:
> 12月 08 06:35:26.0 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
> 12月 08 06:35:26.0 [gae_proxy][INFO] GAE APPID          : 
> 12月 08 06:35:26.0 [gae_proxy][INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
> 12月 08 06:35:26.0 [gae_proxy][INFO] ------------------------------------------------------
> 12月 08 06:35:26.0 [gae_proxy][DEBUG] Importing CA
> 12月 08 06:35:26.0 [gae_proxy][DEBUG] Begin importing CA to Firefox
> 12月 08 06:35:26.0 [gae_proxy][INFO] Removing old cert to Firefox in /home/cloud/.mozilla/firefox/yfpd3a1q.default
> GoAgent XX-Net - GoAgent                                     C,,  
> 12月 08 06:35:26.1 [gae_proxy][INFO] Add new cert to Firefox in /home/cloud/.mozilla/firefox/yfpd3a1q.default
> 12月 08 06:35:26.1 [simple_http_server][INFO] server 127.0.0.1:8087 started.
> 12月 08 06:35:26.1 [simple_http_server][INFO] server 127.0.0.1:8086 started.
> 12月 08 06:35:26.1 [launcher][INFO] module gae_proxy started
> 12月 08 06:35:26.1 [gae_proxy][DEBUG] network IPv4 is ok, cost:198 ms
> 12月 08 06:35:26.1 [launcher][INFO] start gae_proxy time cost:205 ms
> 12月 08 06:35:26.1 [cloudflare_front][INFO] SSL use version:TLSv1_2
> 12月 08 06:35:26.1 [cloudflare_front][INFO] OpenSSL support alpn
> 12月 08 06:35:26.1 [cloudflare_front][INFO] load ip range file:/opt/XX-Net-3.8.5/code/default/x_tunnel/local/cloudflare_front/ip_range.txt
> 12月 08 06:35:26.2 [cloudflare_front][INFO] load google ip_list num:3000, gws num:3000
> 12月 08 06:35:26.2 [cloudflare_front][INFO] Adjust scan thread num from 1 to 0
> 12月 08 06:35:26.2 [x_tunnel][INFO] use config_path:/opt/XX-Net-3.8.5/data/x_tunnel/client.json
> 12月 08 06:35:26.2 [x_tunnel][INFO] X-Tunnel window:16777216
> 12月 08 06:35:26.2 [simple_http_server][INFO] server 127.0.0.1:1080 started.
> 12月 08 06:35:26.2 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
> 12月 08 06:35:26.3 [launcher][INFO] module x_tunnel started
> 12月 08 06:35:26.3 [launcher][INFO] start x_tunnel time cost:175 ms
> 12月 08 06:35:26.3 [cloudflare_front][DEBUG] network is ok, cost:177 ms
> 12月 08 06:35:26.3 [smart_router][WARNING] bind DNS 127.0.0.1:53 fail
 > .
 > .
 > .
 > .
> .
> 12月 08 06:37:26.1 [gae_proxy][DEBUG] create ssl timeout fail.
> 12月 08 06:37:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:26.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:27.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:27.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:28.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:28.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:29.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:29.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:30.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:30.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:37:39.8 [gae_proxy][DEBUG] GAE POST https://www.google-analytics.com/r/collect
> 12月 08 06:38:10.6 [launcher][DEBUG] launcher web_control 127.0.0.1:35092 GET /update?cmd=get_info 
> 12月 08 06:38:26.1 [gae_proxy][DEBUG] create ssl timeout fail.
> 12月 08 06:38:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:38:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:26.1 [gae_proxy][DEBUG] create ssl timeout fail.
> 12月 08 06:39:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:26.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:27.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:27.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:28.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:28.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:29.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:29.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:30.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:39:30.6 [gae_proxy][WARNING] no enough ip
> 12月 08 06:40:26.1 [gae_proxy][DEBUG] create ssl timeout fail.
> 12月 08 06:40:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:40:26.2 [gae_proxy][WARNING] no enough ip
> 12月 08 06:41:26.1 [gae_proxy][DEBUG] create ssl timeout fail.
> 12月 08 06:41:26.1 [gae_proxy][WARNING] no enough ip
> 12月 08 06:41:26.2 [gae_proxy][WARNING] no enough ip
> 12月 08 06:41:26.6 [gae_proxy][WARNING] no enough ip

**Comment by xxnet** [comment]
​没有看到
  import build-in openssl fail:AttributeError("'module' object has no
attribute 'SSL_ST_INIT'",)
 的日志。

选择卸载系统pyOpenSSL ，或者看能否升级系统pyOpenSSL 库
