### ISSUE TITLE
求助：google打不开....显示“此网站无法提供安全连接 www.google.com 发送的响应无效。”

### ISSUE THREAD

**Issue by 979500318** [XX-net/XX-Net#8943]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:2 ipv6:2487
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:43 h2:0
scan-ip-thread-num: 100
ip-quality: 278
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
![tim 20171210221056](https://user-images.githubusercontent.com/20274700/33805632-11a39ca4-ddf7-11e7-962e-39030dfad5ca.png)

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果

**Comment by onplus** [comment]
@gjbg1989 大概和teredo没关系

需要日志、证书之类的信息
![image](https://user-images.githubusercontent.com/31188782/33805822-b116c6a6-ddf9-11e7-9606-3ee0d619ffbd.png)![image](https://user-images.githubusercontent.com/31188782/33805825-bf407204-ddf9-11e7-91c3-4f0d7fa77e0a.png)

**Comment by tinyjff** [comment]
@onplus 一样的问题

![image](https://user-images.githubusercontent.com/34419001/33805926-075e334a-ddfb-11e7-83eb-fc2cc909e66a.png)

日志有报错
Dec 10 22:40:07.263 - [INFO] GAE CONNECT clients1.google.com:443
Dec 10 22:40:07.265 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients1.google.com

**Comment by onplus** [comment]
@tinyjff chrome63或者firefox可以查看证书内容

**Comment by gjbg1989** [comment]
亲历：网速慢上twitter时chrome正常，FireFox却报安全。。。不能正常，证书之类会报证书出错。。。
网速正常后没做任何修改的FireFox一切正常

**Comment by 979500318** [comment]
@gjbg1989 Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.5.104:50633
外部 NAT 映射    : 106.115.216.25:27192

**Comment by 979500318** [comment]
@onplus 
![tim 20171210221056](https://user-images.githubusercontent.com/20274700/33806018-66d606da-ddfc-11e7-93e1-1181cdb698e9.png)
用的是chrome63

**Comment by gjbg1989** [comment]
束进程pythonw.exe，管理权限运行
netsh int ipv6 set teredo enterpriseclient
#8915 tertdo.bat自动或手动优选服务器，或许就OK

**Comment by gjbg1989** [comment]
use-ipv6: auto改为只用ipv6

**Comment by 979500318** [comment]
@gjbg1989 
use-ipv6: auto改为只用ipv6
这一步怎么弄？

**Comment by gjbg1989** [comment]
上面说的都办好了？多次刷新下控制页，google打开了？

**Comment by gjbg1989** [comment]
这一步怎么弄？ http://127.0.0.1:8085/?module=gae_proxy&menu=advanced

**Comment by 979500318** [comment]
@gjbg1989 都弄完了 还是上不去...

**Comment by gjbg1989** [comment]
tertdo.bat自动或手动优选服务器了？netsh int ipv6 show teredo 贴运行结果

**Comment by 979500318** [comment]
@gjbg1989 
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.5.104:52962
外部 NAT 映射    : 106.115.216.25:25866

**Comment by gjbg1989** [comment]
多次刷新下控制页，google打开了？

**Comment by 979500318** [comment]
@gjbg1989 打不开

**Comment by gjbg1989** [comment]
结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net

**Comment by 979500318** [comment]
@gjbg1989 还是一样

**Comment by gjbg1989** [comment]
其他翻得正常？

**Comment by 979500318** [comment]
@gjbg1989 嗯

**Comment by gjbg1989** [comment]
删除目录 certs ，清除浏览器。。。
![image](https://user-images.githubusercontent.com/13290970/33807278-243939ba-de0f-11e7-9f5e-7c619bd0a1b4.png)

**Comment by 979500318** [comment]
@gjbg1989 用SS的话还是能进google 但是用XXNET就进不了

**Comment by gjbg1989** [comment]
删除XX-Net的目录 certs 。。。

**Comment by 979500318** [comment]
@gjbg1989 删了....还是不能进....  别的浏览器就能进

**Comment by gjbg1989** [comment]
还是不能进.... 别的浏览器就能进——早说，貌似与XX-Net无关，少白忙
![image](https://user-images.githubusercontent.com/13290970/33807624-a60994e4-de14-11e7-9775-d367dede1e02.png)

**Comment by 979500318** [comment]
@gjbg1989 没试重置，但是重新安装了一遍Google Chrome 还是一样

**Comment by 979500318** [comment]
@gjbg1989 www.google.com.hk 能进 去掉.hk别的浏览器也进不了...抱歉之前没看清楚网址...

**Comment by xxnet** [comment]
​试试 3.8.5或 3.8.4 ，看看是不是新版的问题。

**Comment by 979500318** [comment]
@xxnet 换3.8.5就变成“请检查浏览器代理设置。”了....

**Comment by gjbg1989** [comment]
[2017.03.12]MyChrome v3.8.1-可自动更新的Google Chrome便携版_Chrome_浏览器讨论区 卡饭论坛 - 互助分享 - 大气谦和! - https://bbs.kafan.cn/thread-1725205-1-1.html …

**Comment by Taitanxing** [comment]
我就是退回了385才正常。
XX显示运行正常。
但谷歌与火狐都提示安全链接问题。

**Comment by Taitanxing** [comment]
退回358后要检查火狐里的CA证书是否正确导入到了‘证书机构’里面，如果是出现在’你的证书’里就会出现“请检查浏览器代理”

**Comment by 979500318** [comment]
@xxnet 换回355后就正常了..

**Comment by 979500318** [comment]
@Taitanxing 我重下了一遍就行了...
