### ISSUE TITLE
XX-Net v3.8.6 系统托盘无图标，无法打开Web页面。

### ISSUE THREAD

**Issue by XhYde** [XX-net/XX-Net#8948]
之前使用XX-NET v3.8.5，一切正常，然后我刚更新了Windows小版本。
之后XX-NET仍可翻墙，但系统托盘无图标，无法打开Web页面127.0.0.1:8085。
XX-NET更新至v3.8.6问题依旧。

操作系统版本：Win10  1709（OS 内部版本 16299.98）
XX-Net版本：3.8.6。

参考了Issue #3348
但是我这里出错行数不一样，也没有具体错误说明。
没有运行X-Tunnel。

日志文件内容：
E:\My Files\Documents\Program Files\XX-NET\data\launcher\launcher.log
Dec 11 05:55:48.999 - [INFO] use build-in openssl lib
Dec 11 05:55:49.001 - [INFO] start XX-Net 3.8.6
Dec 11 05:55:49.001 - [DEBUG] start confirm_xxnet_exit
Dec 11 05:55:50.005 - [DEBUG] good, xxnet:8085 clear!
Dec 11 05:55:50.005 - [DEBUG] finished confirm_xxnet_exit
Dec 11 05:55:50.978 - [INFO] module gae_proxy started
Dec 11 05:55:50.979 - [INFO] start gae_proxy time cost:973 ms

管理员权限运行start.bat 状态如图：
![error log1](https://user-images.githubusercontent.com/16041746/33810084-9a4958ca-de3b-11e7-8cf0-7424c1081d79.png)
![error log2](https://user-images.githubusercontent.com/16041746/33810085-9b7f8174-de3b-11e7-8984-2c4918d7ee8a.png)

**Comment by xxnet** [comment]
​10013 错误，是防火墙软件保护，查看一下防火墙，先停掉安全软件试试

**Comment by XhYde** [comment]
我只用Windows Defender，防火墙和防毒规则里没找到XX-Net和Pythonw.exe的相关项，停用防火墙结束Pythonw.exe进程再以管理员运行Start.bat，还是一样的问题和出错信息。

**Comment by gjbg1989** [comment]
😂自动更新与下载解压，变换为另一种办法更新？

**Comment by SeaHOH** [comment]
看错了……

**Comment by gjbg1989** [comment]
😱下载解压覆盖更新的，没停用防火墙以管理员运行Start.bat，窗口内有楼主截图的相似错误，系统托盘无图标——被任务栏折叠隐藏了而已，可打开Web页面127.0.0.1:8085，代理正常

**Comment by ccyr119** [comment]
操作系统版本：Win10 1709（OS 内部版本 16299.98）
XX-Net版本：3.8.6。
我的也是刚刚升级完，启动就没有托盘图标了

**Comment by XhYde** [comment]
找到了\XX-NET\data\launcher\error.log。删掉了12月前的部分重复项。
倒数第二行，12月11日出现的新error是exceptions.EOFError。
是不是windows升级了以后，把什么网络设置相关文件的修改权限提高了……

Oct 05 01:27:35.507 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x662BC490>
Oct 19 13:11:56.592 type:<type 'exceptions.LookupError'> value=unknown encoding: mbcs traceback:<traceback object at 0x05735E90>
Oct 19 13:11:59.153 type:<type 'exceptions.LookupError'> value=unknown encoding: mbcs traceback:<traceback object at 0x048BDA08>
Oct 24 15:10:28.337 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x08D84710>
Nov 26 17:27:05.919 type:<type 'exceptions.LookupError'> value=unknown encoding: mbcs traceback:<traceback object at 0x05856670>
Nov 26 17:27:09.495 type:<type 'exceptions.LookupError'> value=unknown encoding: mbcs traceback:<traceback object at 0x040915D0>
Dec 11 01:00:12.562 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x06B0BCD8>
Dec 11 18:51:20.135 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x072938A0>

**Comment by SeaHOH** [comment]
建议 Defender 和 防火墙都停用再试

**Comment by gjbg1989** [comment]
Dec 14 01:05:37.407 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x1AF53760>
Dec 14 10:20:20.204 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x20234698>
Dec 14 15:11:59.345 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x09159D00>
Dec 15 09:12:09.554 type:<type 'exceptions.IOError'> value=[Errno 12] Not enough space traceback:<traceback object at 0x097A75D0>8>
Dec 15 09:12:18.699 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x095AD580>

**Comment by XhYde** [comment]
升级到3.9.6问题又解决了~ 满血复活撒花~
