### ISSUE TITLE
X-Tunnel无法登陆

### ISSUE THREAD

**Issue by waitingHao** [XX-net/XX-Net#8949]
本来打算付费购买的，结果没试用几天就挂了。

* 是否试过最新的测试版本？
  3.8.6
  

* X-tunnel 无法连接  
  无法登陆
   
* X-Tunnel 日志

Dec 11 09:33:21.637 - [INFO] xxnet_version:3.8.6
Dec 11 09:33:21.637 - [INFO] Socks5 server listen:127.0.0.1:1080.
Dec 11 09:33:50.319 - [DEBUG] x_tunnel force update info
Dec 11 09:34:24.878 - [WARNING] api:/login fail:status:602 t:34
Dec 11 09:34:45.365 - [DEBUG] x_tunnel force update info
Dec 11 09:35:15.383 - [WARNING] api:/login fail:status:602 t:30

* Cloudflare front Log

Dec 11 09:33:21.158 - [INFO] load ip range file:Z:\Program\XX-Net-3.1.19\code\3.8.6\x_tunnel\local\cloudflare_front\ip_range.txt
Dec 11 09:33:21.214 - [INFO] load google ip_list num:3000, gws num:3000
Dec 11 09:33:21.226 - [INFO] Adjust scan thread num from 1 to 0
Dec 11 09:33:21.278 - [DEBUG] network is ok, cost:579 ms
Dec 11 09:33:21.983 - [INFO] updated cloudflare front domains from github.
Dec 11 09:33:50.863 - [DEBUG] create_ssl update ip:104.25.116.231 time:528 h2:1 sni:hanthelconsulting.com top:gotoworld.tk
Dec 11 09:33:51.363 - [DEBUG] create_ssl update ip:172.64.2.73 time:537 h2:1 sni:pakmem.de top:dragon-dreamer.com
Dec 11 09:33:51.598 - [DEBUG] 104.25.116.231 worker close:status 403
Dec 11 09:33:51.599 - [WARNING] POST center.gotoworld.tk/login status:403 trace:0:start_request,0:get_task(1),89:get_worker(0):104.25.116.231,0:h2_req,1:start send header,0:start send left body,0:end send left body,181:h2_get_head,1:get_response,:0
Dec 11 09:33:51.836 - [DEBUG] create_ssl update ip:190.93.245.85 time:509 h2:1 sni:greenleafhealing.com top:superx.gq
Dec 11 09:33:52.329 - [DEBUG] create_ssl update ip:104.16.233.137 time:502 h2:1 sni:dropping.global top:singlefly.tk
Dec 11 09:33:52.445 - [DEBUG] create_ssl update ip:104.16.26.46 time:580 h2:1 sni:greenleafhealing.com top:superx.gq
Dec 11 09:33:52.795 - [DEBUG] 172.64.2.73 worker close:status 403
Dec 11 09:33:52.795 - [WARNING] POST center.dragon-dreamer.com/login status:403 trace:0:start_request,0:get_task(1),1:get_worker(0):172.64.2.73,0:h2_req,0:start send header,0:start send left body,0:end send left body,190:h2_get_head,0:get_response,:1
Dec 11 09:33:52.911 - [DEBUG] create_ssl update ip:190.93.244.244 time:546 h2:1 sni:bedmintoncoats.ml top:gotoworld.tk
Dec 11 09:33:52.942 - [DEBUG] create_ssl update ip:104.19.100.123 time:614 h2:1 sni:cigarette-articles-p.ga top:superx.gq
Dec 11 09:33:52.975 - [DEBUG] 190.93.245.85 worker close:status 403
Dec 11 09:33:52.975 - [WARNING] POST center.superx.gq/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,2:start send header,0:start send left body,0:end send left body,176:h2_get_head,0:get_response,:0
Dec 11 09:33:53.153 - [DEBUG] 104.16.233.137 worker close:status 403
Dec 11 09:33:53.153 - [WARNING] POST center.singlefly.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.16.233.137,0:h2_req,0:start send header,0:start send left body,0:end send left body,174:h2_get_head,0:get_response,:1
Dec 11 09:33:53.169 - [DEBUG] connect 104.25.151.172 fail:[('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')] cost:340
Dec 11 09:33:53.169 - [DEBUG] report_connect_fail:104.25.151.172
Dec 11 09:33:53.348 - [DEBUG] create_ssl update ip:172.64.132.40 time:509 h2:1 sni:techbestadsweb.site top:flar.tk
Dec 11 09:33:53.360 - [DEBUG] 104.16.26.46 worker close:status 403
Dec 11 09:33:53.360 - [WARNING] POST center.superx.gq/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.16.26.46,0:h2_req,0:start send header,0:start send left body,0:end send left body,204:h2_get_head,0:get_response,:0
Dec 11 09:33:53.591 - [DEBUG] 104.19.100.123 worker close:status 403
Dec 11 09:33:53.592 - [WARNING] POST center.superx.gq/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,0:start send header,0:start send left body,0:end send left body,229:h2_get_head,0:get_response,:0
Dec 11 09:33:53.697 - [DEBUG] create_ssl update ip:104.25.160.222 time:526 h2:1 sni:micasaba.com top:flar.tk
Dec 11 09:33:53.791 - [DEBUG] 190.93.244.244 worker close:status 403
Dec 11 09:33:53.791 - [WARNING] POST center.gotoworld.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.244,0:h2_req,1:start send header,0:start send left body,0:end send left body,196:h2_get_head,0:get_response,:0
Dec 11 09:33:53.902 - [DEBUG] create_ssl update ip:104.28.25.147 time:572 h2:1 sni:beerparade.com.mx top:gotoworld.tk
Dec 11 09:33:53.907 - [DEBUG] create_ssl update ip:104.25.131.96 time:567 h2:1 sni:jentheeditor.com top:c-term.tk
Dec 11 09:33:54.042 - [DEBUG] create_ssl update ip:104.19.198.107 time:595 h2:1 sni:householdd.cf top:superx.gq
Dec 11 09:33:54.262 - [DEBUG] 172.64.132.40 worker close:status 403
Dec 11 09:33:54.262 - [WARNING] POST center.flar.tk/login status:403 trace:0:start_request,1:get_task(0),121:get_worker(0):172.64.132.40,0:h2_req,1:start send header,0:start send left body,0:end send left body,345:h2_get_head,1:get_response,:0
Dec 11 09:33:54.304 - [DEBUG] create_ssl update ip:104.28.79.77 time:473 h2:1 sni:bmovietees.cf top:c-term.tk
Dec 11 09:33:54.401 - [DEBUG] create_ssl update ip:141.101.122.140 time:489 h2:1 sni:vilvulei.com top:gotoworld.tk
Dec 11 09:33:54.440 - [DEBUG] create_ssl update ip:190.93.245.131 time:496 h2:1 sni:decorationsforxmasdecor.com top:freenum.cf
Dec 11 09:33:54.449 - [DEBUG] 104.25.160.222 worker close:status 403
Dec 11 09:33:54.449 - [WARNING] POST center.flar.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.25.160.222,0:h2_req,0:start send header,0:start send left body,0:end send left body,184:h2_get_head,0:get_response,:0
Dec 11 09:33:54.654 - [DEBUG] 104.28.25.147 worker close:status 403
Dec 11 09:33:54.655 - [WARNING] POST center.gotoworld.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,202:h2_get_head,0:get_response,:0
Dec 11 09:33:54.714 - [DEBUG] connect 104.24.182.7 fail:[('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')] cost:364
Dec 11 09:33:54.714 - [DEBUG] report_connect_fail:104.24.182.7
Dec 11 09:33:54.858 - [DEBUG] 104.25.131.96 worker close:status 403
Dec 11 09:33:54.858 - [WARNING] POST center.c-term.tk/login status:403 trace:0:start_request,0:get_task(0),0:get_worker(0):104.25.131.96,0:h2_req,1:start send header,0:start send left body,0:end send left body,200:h2_get_head,0:get_response,:0
Dec 11 09:33:54.892 - [DEBUG] create_ssl update ip:190.93.244.75 time:559 h2:1 sni:checalo.cf top:mostlygood.ga
Dec 11 09:33:55.309 - [DEBUG] create_ssl update ip:162.159.230.45 time:593 h2:1 sni:greenleafhealing.com top:superx.gq
Dec 11 09:33:55.317 - [DEBUG] create_ssl update ip:104.27.130.187 time:483 h2:1 sni:cl8ud.com top:movistar.gq
Dec 11 09:33:55.490 - [DEBUG] create_ssl update ip:104.31.149.15 time:575 h2:1 sni:blacksdirectory.com top:c-term.tk
Dec 11 09:33:55.502 - [DEBUG] create_ssl update ip:172.64.194.73 time:596 h2:1 sni:bayliff.law top:mostlygood.ga
Dec 11 09:33:55.553 - [DEBUG] create_ssl update ip:104.20.28.75 time:508 h2:1 sni:createcookingschool.com top:freenum.cf
Dec 11 09:33:55.803 - [DEBUG] create_ssl update ip:190.93.247.160 time:496 h2:1 sni:sapphicdating.com top:singlefly.tk
Dec 11 09:33:56.417 - [WARNING] h2 timeout 104.25.116.231 task_trace:0:start_request,0:get_task(1),89:get_worker(0):104.25.116.231,0:h2_req,1:start send header,0:start send left body,0:end send left body,181:h2_get_head,1:get_response,:4819 worker_trace: processed:1, h2.stream_num:0, sni:hanthelconsulting.com, domain:gotoworld.tk
Dec 11 09:33:57.606 - [WARNING] h2 timeout 172.64.2.73 task_trace:0:start_request,0:get_task(1),1:get_worker(0):172.64.2.73,0:h2_req,0:start send header,0:start send left body,0:end send left body,190:h2_get_head,0:get_response,:4812 worker_trace: processed:1, h2.stream_num:0, sni:pakmem.de, domain:dragon-dreamer.com
Dec 11 09:33:57.800 - [WARNING] h2 timeout 190.93.245.85 task_trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.245.85,0:h2_req,2:start send header,0:start send left body,0:end send left body,176:h2_get_head,0:get_response,:4825 worker_trace: processed:1, h2.stream_num:0, sni:greenleafhealing.com, domain:superx.gq
Dec 11 09:33:57.981 - [WARNING] h2 timeout 104.16.233.137 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.16.233.137,0:h2_req,0:start send header,0:start send left body,0:end send left body,174:h2_get_head,0:get_response,:4828 worker_trace: processed:1, h2.stream_num:0, sni:dropping.global, domain:singlefly.tk
Dec 11 09:33:58.158 - [WARNING] h2 timeout 104.16.26.46 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.16.26.46,0:h2_req,0:start send header,0:start send left body,0:end send left body,204:h2_get_head,0:get_response,:4798 worker_trace: processed:1, h2.stream_num:0, sni:greenleafhealing.com, domain:superx.gq
Dec 11 09:33:58.365 - [WARNING] h2 timeout 104.19.100.123 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.19.100.123,0:h2_req,0:start send header,0:start send left body,0:end send left body,229:h2_get_head,0:get_response,:4773 worker_trace: processed:1, h2.stream_num:0, sni:cigarette-articles-p.ga, domain:superx.gq
Dec 11 09:33:58.598 - [WARNING] h2 timeout 190.93.244.244 task_trace:0:start_request,0:get_task(0),0:get_worker(0):190.93.244.244,0:h2_req,1:start send header,0:start send left body,0:end send left body,196:h2_get_head,0:get_response,:4807 worker_trace: processed:1, h2.stream_num:0, sni:bedmintoncoats.ml, domain:gotoworld.tk
Dec 11 09:33:58.920 - [WARNING] h2 timeout 172.64.132.40 task_trace:0:start_request,1:get_task(0),121:get_worker(0):172.64.132.40,0:h2_req,1:start send header,0:start send left body,0:end send left body,345:h2_get_head,1:get_response,:4657 worker_trace: processed:1, h2.stream_num:0, sni:techbestadsweb.site, domain:flar.tk
Dec 11 09:33:58.987 - [DEBUG] create_ssl update ip:104.17.88.238 time:4288 h2:1 sni:daniel-latta.review top:movistar.gq
Dec 11 09:33:59.267 - [WARNING] h2 timeout 104.25.160.222 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.25.160.222,0:h2_req,0:start send header,0:start send left body,0:end send left body,184:h2_get_head,0:get_response,:4818 worker_trace: processed:1, h2.stream_num:0, sni:micasaba.com, domain:flar.tk
Dec 11 09:33:59.456 - [WARNING] h2 timeout 104.28.25.147 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.28.25.147,0:h2_req,1:start send header,0:start send left body,0:end send left body,202:h2_get_head,0:get_response,:4802 worker_trace: processed:1, h2.stream_num:0, sni:beerparade.com.mx, domain:gotoworld.tk
Dec 11 09:33:59.660 - [WARNING] h2 timeout 104.25.131.96 task_trace:0:start_request,0:get_task(0),0:get_worker(0):104.25.131.96,0:h2_req,1:start send header,0:start send left body,0:end send left body,200:h2_get_head,0:get_response,:4802 worker_trace: processed:1, h2.stream_num:0, sni:jentheeditor.com, domain:c-term.tk

**Comment by gjbg1989** [comment]
貌似GAE正常，不会X-Tunnel无法登陆

**Comment by waitingHao** [comment]
@gjbg1989 实际上就是登录不了。

![image](https://user-images.githubusercontent.com/4094309/33823055-ad692670-de94-11e7-973c-dc01f5357f42.png)

**Comment by gjbg1989** [comment]
貌似GAE正常，不会X-Tunnel无法登陆——GAE正常了？

**Comment by xxnet** [comment]
​先启用IPv6，参考这里：
https://github.com/XX-net/XX-Net/wiki/如何开启IPv6

**Comment by waitingHao** [comment]
@xxnet X-Tunnel一定要IPv6吗？我这偶尔IPv6才会正常，就是因为IPv6不正常才用X-Tunnel的。

**Comment by gjbg1989** [comment]
既然偶尔IPv6会正常，貌似基本可以长期正常😂

**Comment by xxnet** [comment]
​你是什么网络ISP？

cloudflare 居然封你

X-Tunnel 有cloudflare 和 IPv6两条通道，你居然被cloudflare 拒绝服务，那只能IPv6。
都不行的话就要等以后改进加新通道了。

**Comment by hai1212** [comment]
我跟他一样也是被拒绝了！！

**Comment by xxnet** [comment]
​什么地区，什么ISP?

**Comment by waitingHao** [comment]
@xxnet 广东省深圳市 电信，是被cloudflare封了我这边，而不是因为ISP封了cloudflare ？

**Comment by xxnet** [comment]
​可能和ISP出口有关，403 是拒绝服务，具体原因只有cloudflare知道

**Comment by waitingHao** [comment]
好的，今天竟然又能用了，就是不稳定。这个不能用的时候只能找一下其他的替代方案了。

**Comment by xxnet** [comment]
​后面会继续开发新的通道，估计要1个月后了
