### ISSUE TITLE
尚未建立连接

### ISSUE THREAD

**Issue by l3125831q** [XX-net/XX-Net#8950]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:3510 ipv4:5 ipv6:468
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 343
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
use-ipv6: auto改为只用ipv6
netsh int ipv6 show teredo 贴运行结果

**Comment by l3125831q** [comment]
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                   : 客户端位于托管网络中

**Comment by gjbg1989** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient default
#8915 tertdo.bat自动或手动优选服务器，或许就OK
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个。

**Comment by l3125831q** [comment]
#8915 tertdo.bat自动或手动优选服务器，或许就OK
不懂这句是什么意思...新手见谅

**Comment by l3125831q** [comment]
@gjbg1989 
可以啦，非常感谢！

**Comment by nly4lov** [comment]
@gjbg1989  "没有项目新建一个“，新建个啥？！

**Comment by gjbg1989** [comment]
DisabledComponents

**Comment by nly4lov** [comment]
@gjbg1989 我知道新建的东西叫你说的这个DisabledComponents，可新建的时候有6种种类！是reg_binary还是reg_dword，如果是后者，是32还是64位的？
除了这3种，还有string, multiple string, expandable string呢

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33813298-b52517d4-de5d-11e7-9617-366531827484.png)

**Comment by nly4lov** [comment]
@gjbg1989 好的，我马上试试

**Comment by whhxmwhh** [comment]
感觉IPV6真的很不容易。IPV4又很容易被墙。真的两难。

**Comment by nly4lov** [comment]
@gjbg1989 仍然未建立连接。
另，我的netsh int ipv6 show teredo 结果是：
Type                    : enterpriseclient
Server Name             : win1710.ipv6.microsoft.com.
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : dormant

**Comment by gjbg1989** [comment]
State : dormant乃未启动XX-Net前的睡眠正常状态，#8915 tertdo.bat自动或手动优选服务器

**Comment by gjbg1989** [comment]
Server Name : win1710.ipv6.microsoft.com. 乃系统默认服务器，使用ping超时的微软服务器或许更稳定😂

**Comment by nly4lov** [comment]
我去看过三遍了，没看到teredo.bat

**Comment by nly4lov** [comment]
找到了

**Comment by gjbg1989** [comment]
没辙，如我上传，照样会——始终在转圈😂

**Comment by nly4lov** [comment]
我邮箱mkv@foxmail.com，你发给我吧

**Comment by gjbg1989** [comment]
还不如贴给你：tertdo.bat
@echo off

cd /d "%~dp0"
cacls.exe "%SystemDrive%\System Volume Information" >nul 2>nul
if %errorlevel%==0 goto Admin
if exist "%temp%\getadmin.vbs" del /f /q "%temp%\getadmin.vbs"
echo Set RequestUAC = CreateObject^("Shell.Application"^)>"%temp%\getadmin.vbs"
echo RequestUAC.ShellExecute "%~s0","","","runas",1 >>"%temp%\getadmin.vbs"
echo WScript.Quit >>"%temp%\getadmin.vbs"
"%temp%\getadmin.vbs" /f
if exist "%temp%\getadmin.vbs" del /f /q "%temp%\getadmin.vbs"
exit

:Admin


:begin
Echo. 请选择需要的操作
Echo     1 netsh int ipv6 show teredo
Echo     2 自动选择并设置teredo服务器
Echo     3 手动选择并设置teredo服务器
Echo     4 exit
Echo.
Set /P Choice= 　　　　　请选择要进行的操作数字 ，然后按回车：
If not "%Choice%"=="" (
  If "%Choice%"=="4" goto exit
  If "%Choice%"=="1" goto one
  If "%Choice%"=="2" goto two
  If "%Choice%"=="3" goto :begin2
)

:one
 netsh int ipv6 show teredo
goto begin
:two
"%~dp0code"\default\python27\1.0\python.exe "%~dp0teredo.py"
goto begin

:begin2
Echo. 请选择需要的操作
echo     1 	teredo.remlab.net
echo     2 	teredo2.remlab.net
echo     3 	teredo-debian.remlab.net
echo     4 	teredo.ngix.ne.kr
echo     5 	teredo.trex.fi
echo     6 	teredo.autotrans.consulintel.com
echo     7 	teredo.managemydedi.com
echo     8 	teredo.ipv6.microsoft.com
echo     9 	win10.ipv6.microsoft.com
echo     10	teredo.iks-jena.de
echo     11	win1710.ipv6.microsoft.com
echo     0 	返回
Set /P Choice= 　　　　　请选择要进行的操作数字 ，然后按回车：
If not "%Choice%"=="" (
	If "%Choice%"=="0" goto begin
	If "%Choice%"=="11" goto two11
	If "%Choice%"=="10" goto two10
	If "%Choice%"=="9" goto two9
	If "%Choice%"=="8" goto two8
	If "%Choice%"=="7" goto two7
	If "%Choice%"=="6" goto two6
	If "%Choice%"=="5" goto two5
	If "%Choice%"=="4" goto two4
	If "%Choice%"=="3" goto two3
	If "%Choice%"=="2" goto two2
	If "%Choice%"=="1" goto two1

)
:two1
netsh interface teredo set state server=teredo.remlab.net
goto begin
:two2
netsh interface teredo set state server=teredo2.remlab.net
goto begin
:two3
netsh interface teredo set state server=teredo-debian.remlab.net
goto begin
:two4
netsh interface teredo set state server=teredo.ngix.ne.kr
goto begin
:two5
netsh interface teredo set state server=teredo.trex.fi
goto begin
:two6
netsh interface teredo set state server=teredo.autotrans.consulintel.com
goto begin
:two7
netsh interface teredo set state server=teredo.managemydedi.com
goto begin
:two8
netsh interface teredo set state server=teredo.ipv6.microsoft.com
goto begin
:two9
netsh interface teredo set state server=win10.ipv6.microsoft.com
goto begin
:two10
netsh interface teredo set state server=teredo.iks-jena.de
:two11
netsh interface teredo set state server=win1710.ipv6.microsoft.com
goto begin







:exit
exit

**Comment by gjbg1989** [comment]
teredo.py

# -*- coding: utf-8 -*- # 
import time
import socket
import subprocess,re
import os
def getPING(domain):  
    p = subprocess.Popen(["ping.exe", domain], stdin = subprocess.PIPE, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell = True)  
    out = p.stdout.read().decode('gbk')    
    regAverage = u'Average = \d+ms|平均 = \d+ms'  
    average = re.search(regAverage, out)  
    if average:  
        average = filter(lambda x:x.isdigit(),average.group())  
    return average

def check(add, port):
    #print ('++++++++++UDP connection testing+++++++++')
    try:
        sock = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
        sock.settimeout(5)
        sock.connect((add, port))
        a=sock.sendto("123",(add, port))
        if a==3:
            #print ip,'accessible'
            return True
    except socket.error, e:
        return False
    finally:
        sock.close() 
if __name__ == "__main__":
    import ConfigParser
    iplist = [
    'teredo.remlab.net',
    'teredo2.remlab.net',
    'teredo-debian.remlab.net',
    'teredo.ngix.ne.kr',
    'teredo.trex.fi',
    'teredo.autotrans.consulintel.com',
    'teredo.managemydedi.com',
    'teredo.ipv6.microsoft.com',
    'win10.ipv6.microsoft.com',
    'teredo.iks-jena.de',
    'win1710.ipv6.microsoft.com']
    port = 3544
    okiplist =[]
    b =   {}
    print ('\n++++++++++UDP connection testing+++++++++\n')
    for ip in iplist:
        stat = check(ip, port)
        if stat == True:
            print '%s:%s is accessible' % (ip, port) 
            okiplist.append(ip)
        if stat != True:
            print '%s:%s isn\'t accessible' % (ip, port)       
    print ('\n++++++++++ping testing+++++++++\n')   
    for i in okiplist:
        a = getPING(i)
        if not a :a=9999
        a = int(a)
        b[i] = a
        print  i,a,'ms'
        
    d=min(b, key=b.get)
    print u'\n+++++++最佳teredo为：',d,'+++++++'
    sett='netsh interface teredo set state server='+d
    os.system(sett)

**Comment by gjbg1989** [comment]
开始部分貌似有。。。
![default](https://user-images.githubusercontent.com/13290970/33814316-6246cc54-de64-11e7-94b4-074e364dc2b6.png)

**Comment by nly4lov** [comment]
XX-Net 3.8.6, Everything is OK. Welcome to the FREE Internet.![11](https://user-images.githubusercontent.com/11325411/33814626-71bd6574-de66-11e7-9504-404246b3f713.gif)

**Comment by nly4lov** [comment]
THANKS A MILLION, @gjbg1989

**Comment by gjbg1989** [comment]
![](https://user-images.githubusercontent.com/11325411/33814626-71bd6574-de66-11e7-9504-404246b3f713.gif)

**Comment by nly4lov** [comment]
@gjbg1989 我操作过程中，那个bat文件里的2选项，回车后提示：系统找不到指定的路径，是啥情况？

**Comment by gjbg1989** [comment]
2文件放在XX-Net程序的根目录

**Comment by nly4lov** [comment]
自动，自动选了teredo.ngix.ne.kr后，立马从墙头上摔下来了。赶紧手动选回win10.ipv6.microsoft.com

**Comment by gjbg1989** [comment]
或许要刷新下控制页？

**Comment by nly4lov** [comment]
又完蛋了，奇怪。
Type                    : enterpriseclient
Server Name             : win10.ipv6.microsoft.com
Client Refresh Interval : 30 seconds
Client Port             : unspecified
State                   : dormant

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33817578-3854ff30-de7b-11e7-936c-480fd7403aac.png)
管理权限运行 netsh int ipv6 set teredo enterpriseclient default 回到系统默认服务器（最后有句点）

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by nly4lov** [comment]
我试试去。

**Comment by nly4lov** [comment]
我忽然想起，翻不了之前我因为迅雷下载东西很慢，切换到另一个无线网络里去了。
马上连接回之前的路由器，就ok了。

此前在公司设置好翻得了，回家就翻不了，跟这个是同种现象。

**Comment by gjbg1989** [comment]
貌似有人与你情况相似，笔记本在2网络下用XX-Net，换网前结束进程pythonw.exe，管理权限运行3.7.11版XX-Net目录内disable_ipv6.bat，换网后管理权限运行enable_ipv6.bat即可正常开启、使用ipv6隧道。

**Comment by nly4lov** [comment]
汗。可真复杂呀

**Comment by gjbg1989** [comment]
2网络下用同一内网IP貌似就简单了——Ipv6 自动转换 | ??闪闪的红星?? 。。。

**Comment by nly4lov** [comment]
闪闪红星那个我已经设置了，不过尚未重启。

**Comment by gjbg1989** [comment]
或许2网络下各用各的XX-Net文件更理想？

**Comment by nly4lov** [comment]
这明显是个好主意。
