### ISSUE TITLE
自3.8.x之后，没有“使用IPv6”这一选项了？

### ISSUE THREAD

**Issue by BoyChou123** [XX-net/XX-Net#8951]
原来使用3.7.4时，在配置里的高级选项中有“使用IPv6(一般教育网才开)”。
但是自从3.8以后的几个版本，配置中已经没有这一选项了，也不知道大家是否情况相同？
由于我们校园网对Ipv4收费，对Ipv6免费，所以希望把这个选项加回来。

**Comment by gjbg1989** [comment]
有，隐藏在 http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查所有IP 右边😂
运行XX-Net目录内的 enable_ipv6.bat 即可正常开启、使用ipv6隧道。

**Comment by onplus** [comment]
高级--扫描ip-
auto 改成force ipv6

**Comment by BoyChou123** [comment]
哦哦，看到了，现在的3.8.5版本中，在高级的设置里用一个“使用IPv6”，可以选择“只使用IPv6”。
