### ISSUE TITLE
持续上网，满血复活

### ISSUE THREAD

**Issue by yuzichuyu** [XX-net/XX-Net#8960]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4840 ipv4:0 ipv6:4686
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:43 h2:0
scan-ip-thread-num: 10
ip-quality: 250
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

笔记本电脑新装系统可以直接fq,重启了又失败了，后来重置电脑后修改了
IPv6 | force_ipv6和ipv4的DNS以及ipv6的DNS,之后可以一直fq了，重启后也是可以fq的，xx-net是3.8.6测试版
2017.12.13 15：10
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4886 ipv4:0 ipv6:4495
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:0
worker: h1:49 h2:0
scan-ip-thread-num: 10
ip-quality: 258
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33824301-e5164824-de98-11e7-97ec-a7892f941ea1.png)
