### ISSUE TITLE
试试：怎样保持一切正常，你可以访问真正的互联网了

### ISSUE THREAD

**Issue by gjbg1989** [XX-net/XX-Net#8961]
😱貌似减小teredo客户端刷新间隔从30秒变成20或15秒，都未能提高稳定性，哪怕 netsh int ipv6 show teredo 正常，都偶尔有 XX-Net 中断或不正常。试试：
https://github.com/XX-net/XX-Net/issues/8919#issuecomment-350661237 批处理实现每五秒自动检测一次teredo状态（一直运行）
经32Windows10Pro 使用系统默认服务器测试，（管理权限运行）
netsh int ipv6 set teredo enterpriseclient default default default
貌似 XX-Net 一直正常了😱

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33938035-e3bfafac-e040-11e7-8a5d-3753e5125936.png)

**Comment by Monarch1995** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:1 ipv6:5229
ipv4-status: OK
ipv6-status: OK
connected-link: new:3 used:0
worker: h1:25 h2:0
scan-ip-thread-num: 10
ip-quality: 430
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果

**Comment by Monarch1995** [comment]
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by Monarch1995** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:1 ipv6:5190
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:30 h2:0
scan-ip-thread-num: 10
ip-quality: 301
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
结束进程pythonw.exe，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by Monarch1995** [comment]
我的win10系统怎么没有IP转换配置服务

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/34401421-04fef2d6-ebd6-11e7-83d8-717e89af9bc4.png)
版本？网文开始：内网固定IP。。。

**Comment by Monarch1995** [comment]
我这是1511的版本，那怎么办啊，我只要一启动xxnet就断网，我这是校园网

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Intranet-proxy

**Comment by gjbg1989** [comment]
非校园网
![image](https://user-images.githubusercontent.com/13290970/34401908-33cc3710-ebd9-11e7-83df-b068d185bcde.png)
