### ISSUE TITLE
更新到3.8.6后访问google返回Secure Connection Failed

### ISSUE THREAD

**Issue by ZLZhang1** [XX-net/XX-Net#8962]
重新导入证书也不起作用
日志没有报错

An error occurred during a connection to www.google.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
 Please contact the website owners to inform them of this problem.

**Comment by ZLZhang1** [comment]
An error occurred during a connection to www.google.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by gjbg1989** [comment]
结束进程pythonw.exe，删除certs目录？

**Comment by xxnet** [comment]
​什么操作系统、浏览器、版本号？

把诊断信息发上来

**Comment by ZLZhang1** [comment]
XX-Net Status:

sys-platform: x86_64, Linux-4.13.16-302.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
os-system: Linux
os-version: #1 SMP Thu Nov 30 15:33:36 UTC 2017
os-release: 4.13.16-302.fc27.x86_64
os-detail: Dist:Fedora; Version:27; ID:Twenty Seven
architecture: 64bit,
browser: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.8.6
python-version: 2.7.14
openssl-version: 17.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:3000 ipv4:0 ipv6:3001
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:0
worker: h1:36 h2:0
scan-ip-thread-num: 100
ip-quality: 262
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


删除certs目录不起作用

**Comment by ZLZhang1** [comment]
刚才测试了一下
访问https://www.google.com/ 会报错
访问https://www.google.co.jp 正常

**Comment by SeaHOH** [comment]
一个直连，一个 GAE？

**Comment by ZLZhang1** [comment]
都是GAE
https://www.google.com.hk/ 也可以访问

**Comment by xxnet** [comment]
​转Chrome试试

**Comment by ZLZhang1** [comment]
更新到3.8.7后正常了
