### ISSUE TITLE
使用XX后，无法访问网络。

### ISSUE THREAD

**Issue by cryschao** [XX-net/XX-Net#897]
环境：
```
win7 64bit
xx 2.0.5（2.1.2也一样）
chrome43+switchyOmega
```
开始使用没问题，只设置了开机启动。
过一会之后出现的情况是：
ping 网页可以ping通，但是浏览器无法打开任何网页，包括xx的设置网页。QQ登陆状态，但是消息发送不了。
重启后，ping通，网页无法打开，QQ无法登陆。
结束Python开头的进程，删除xxnet文件夹，重启后问题解决。

xx是好东西，上周五突然出现的情况。重装系统再装xx问题依旧。
求救！！！

**Comment by xxnet** [comment]
检查代理设置：
1. Chrome + SwitchyOmega 设置为直连，能不能访问百度？
2. 系统托盘右键点击XXNet图标，看当前代理状态，应该在取消全局代理


在 2015年8月31日 下午6:37，Cryschao <notifications@github.com>写道：

**Comment by cryschao** [comment]
@xxnet 设置直连不能访问。
配置一直是默认，也就是取消全局代理
退出xx，依旧无法访问
只有删除xx才会。囧！

**Comment by xxnet** [comment]
这个现象无法理解，XXnet目录存在与否，并不会影响系统行为，只有修改配置、启动进程这种才会。
除非360之类搞鬼，但我不相信它会这么干。

首先，先分开分析，确定是不是只要目录存在，就无法上网。
  你可以把目录挪个位置试试。
  先排除是开机自动启动

在 2015年8月31日 下午7:35，Cryschao <notifications@github.com>写道：

**Comment by lichunqiang** [comment]
@xxnet 

```
oes not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>Invalid argument.</Message>
<Details>
POST object expects Content-Type multipart/form-data
</Details>
</Error>
```
za gao ...

**Comment by cryschao** [comment]
@xxnet 感谢答复，我会继续测试。有疑问，我再骚扰你 XD
