### ISSUE TITLE
win10休眠唤醒后IPv6 Status Fail，重启电脑后就正常了

### ISSUE THREAD

**Issue by kingzleshe** [XX-net/XX-Net#8973]
不知道这个是不是一个bug
有什么办法能解决吗？
或者有什么临时的办法不用重启电脑？
因为习惯了用休眠，老是重启太麻烦了

休眠唤醒后teredo就不正常了

C:\Users\kingz>netsh int ipv6 show teredo
Teredo 参数
类型                    : client
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by gjbg1989** [comment]
开机、休眠唤醒未启动XX-Net前，状态dormant乃正常。貌似启动XX-Net后休眠唤醒可正常代理，没有必要重启电脑

**Comment by gjbg1989** [comment]
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个。

**Comment by gjbg1989** [comment]
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。或结束全部RuntimeBroker.exe进程、右键 XX-Net 状态栏图标重启
https://github.com/XX-net/XX-Net/issues/8961

**Comment by kingzleshe** [comment]
@gjbg1989
我这边电脑唤醒后确实存在无法代理的情况
使用的是windows10 1709 版本

我网上搜索了一下发现休眠后与teredo或者TAP adapter相关的内容出现问题的情况挺多的
比如
https://github.com/OpenVPN/tap-windows6/issues/29

**Comment by GoodSake** [comment]
试试把上网的网卡禁用后再启用。

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by gjbg1989** [comment]
netsh interface ipv6 set teredo enterpriseclient

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33883608-5c6103c2-df77-11e7-81e3-2d392723d84a.png)
试试：休眠前结束进程 pythonw.exe，唤醒后再运行 XX-Net

**Comment by kingzleshe** [comment]
经过各种努力。问题还是没解决
休眠前结束进程 pythonw.exe 这个我还没去尝试，主要是不符合使用需求。。
我使用了一台全新的windiws10 系统在其他的网络环境里面尝试，也存在同样的问题。。

**Comment by gjbg1989** [comment]
经过各种努力。问题还是没解决——DisabledComponents 加了？
Ipv6 自动转换 | 动作了？
。。。

**Comment by gjbg1989** [comment]
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by gjbg1989** [comment]
改变网卡的电源管理？
休眠前结束进程 pythonw.exe 这个我还没去尝试，主要是不符合使用需求。——完全没必要的重启机器就符合？。。。

**Comment by kingzleshe** [comment]
DisabledComponents ，Ipv6 自动转换 ，网卡电源管理等操作都测试过了
睡眠或者是休眠唤醒后
GAEProxy状态信息还是显示尚未连接
IPv6 Status | Fail

**Comment by gjbg1989** [comment]
**开机或睡眠唤醒，未启动 XX-Net 前是状态 dormant，启动 XX-Net 后的睡眠唤醒即正常使用。**
XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4868 ipv4:0 ipv6:3923
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:47 h2:0
scan-ip-thread-num: 10
ip-quality: 312
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by zuiledemao** [comment]
我也遇到同样的问题，我重新启动IP Helper服务即可（虽然IP Helper一直在运行）@kingzleshe

**Comment by iarander** [comment]
@gjbg1989 确实，启动 XX-Net 后的睡眠唤醒即可正常使用了，楼主试试吧

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by gzl6** [comment]
@iarander "启动 XX-Net 后的睡眠唤醒" 具体是什么意思。具体的操作步骤是怎样的？

**Comment by gjbg1989** [comment]
启动 XX-Net 后运行一定时间——睡眠一定时间——唤醒：立马正常使用😂

**Comment by iarander** [comment]
@gzl6 电脑休眠重新唤醒之后，cmd命令打开Dos控制台，输入netsh int ipv6 show teredo可以看到ipv6的连接状态会变为offline，“无法访问主服务器地址”“UDP无法连接”之类错误，这时候重新启动 XX-Net，稍等一会儿，再输入netsh int ipv6 show teredo，就能看到状态变为dormant或者qualified，等出现本地映射和外部NAT映射IP地址时候，就可以正常使用了

**Comment by gjbg1989** [comment]
运行以下bat（内容）可观察变化过程。。。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by gzl6** [comment]
Thanks

@iarander  ipv6的连接状态会变为offline，然后恢复到dormant或者qualified。和XX-NET是否在运行或者是否重启，应该没有联系吧。

听上去网卡禁用后再启用，似乎有些关联。下次碰上，测试一下。

**Comment by gjbg1989** [comment]
😱约2小时测试：强烈建议用回 3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱
