### ISSUE TITLE
IPv6 每次都按win10的方法设置好了，能用。但是只要关机重启，就又不能用。每次都要到windows powershell里面重新设置一遍

### ISSUE THREAD

**Issue by spookhouse** [XX-net/XX-Net#8974]
日志：
Dec 12 15:26:57.500 - [INFO] xxnet_version:3.8.6
Dec 12 15:26:57.500 - [INFO] Socks5 server listen:127.0.0.1:1080.
X-Tunnel Status Info

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 进去之后只有(默认)和Dhcpv6DUID，没看到Disabled Components

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by gjbg1989** [comment]
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个。

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by GoodSake** [comment]
您露id了，加密码了吗？哈哈哈!

**Comment by gjbg1989** [comment]
当前工作AppID 😱

**Comment by spookhouse** [comment]
怎么办，我晕了，我这个蠢货

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/33875018-d5cac584-df5b-11e7-8797-32007e321b96.png)

**Comment by gjbg1989** [comment]
全删除
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by spookhouse** [comment]
Parameters 进去之后只有(默认)和Dhcpv6DUID，没看到Disabled Components

**Comment by gjbg1989** [comment]
没有，项目新建 Disabled Components

**Comment by spookhouse** [comment]
有没有什么链接的步骤能让我看看的，搞不定它，我这电脑白痴也不懂得十六进制怎么设置

**Comment by gjbg1989** [comment]
[TCPIP6.zip](https://github.com/XX-net/XX-Net/files/1551137/TCPIP6.zip)
解压后双击

**Comment by spookhouse** [comment]
哇塞，好厉害。已经彻底好了，太感谢了，我问了这么多白痴的问题，我是不是可以把问题注销了？

**Comment by szwuzy** [comment]
@gjbg1989 大神写个详细步骤就好了。
