### ISSUE TITLE
Android版无法上Twitter

### ISSUE THREAD

**Issue by zqdalianchina** [XX-net/XX-Net#8984]
Android版无法上twitter，提示：检查你的网络连接并重试。
但可以正常上YouTube。
若在手机上使用赛风，则可以正常上Twitter。

**Comment by Veeson** [comment]
android版本目前还是很难用的，上网速度很慢，特别是开启之后，导致上国内的网站也变得很慢，不建议使用。

**Comment by wankuizhuankan** [comment]
用Xndroid！！！！！！！

**Comment by zqdalianchina** [comment]
用的就是Xndroid
