### ISSUE TITLE
ipv6_status:fail，请问怎么回事？

### ISSUE THREAD

**Issue by binjoo** [XX-net/XX-Net#8988]
##### 诊断信息

> XX-Net Status:
> 
> sys-platform: AMD64, Windows-10-10.0.10586
> os-system: Windows
> os-version: 10.0.10586
> os-release: 10
> os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
> architecture: 32bit,WindowsPE
> browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
> xxnet-version: 3.8.5
> python-version: 2.7.13
> openssl-version: 16.0.0 TLSv1_2 h2:alpn
> lan-proxy: Disable
> use-ipv6: auto
> gws-ip-num: total:6000 ipv4:0 ipv6:2660
> ipv4-status: OK
> ipv6-status: OK
> connected-link: new:0 used:0
> worker: h1:8 h2:0
> scan-ip-thread-num: 200
> ip-quality: 256
> is-idle: 0
> block-stat: OK
> proxy_state: OK
> ca_state: OK
> Appid_Working: true
> Appids_Out_Of_Quota: false
> Appids_Not_Exist: false
> Using_Public_Appid: false

##### Teredo 参数

> C:\Users\ThinkPad>netsh int ipv6 show teredo
> Teredo 参数 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 类型                    : enterpriseclient
> 服务器名称              : teredo.remlab.net
> 客户端刷新间隔          : 30 秒
> 客户端端口                : unspecified
> 状态                    : probe (primary server)
> 客户端类型              : teredo client
> 网络                    : managed

**Comment by gjbg1989** [comment]
😂稍安勿躁，稍侯或许就好
试试： #8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by gjbg1989** [comment]
😱遗漏：use-ipv6: auto改为只用 ipv6

**Comment by gjbg1989** [comment]
scan-ip-thread-num: 200改小10-50？

**Comment by gjbg1989** [comment]
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。

**Comment by binjoo** [comment]
#8756 我现在就是这种情况。

**Comment by gjbg1989** [comment]
貌似换好些的服务器、多次刷新或重载控制页即可。终极方法：
确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。
