### ISSUE TITLE
xx-net 代理服务器对win10 更新有影响（已解决）

### ISSUE THREAD

**Issue by Rookie14** [XX-net/XX-Net#8989]
最近发现win10 无法更新，而且window聚焦（有些是windows自己的问题）也受到一定的影响。查找之后发现如果不勾选代理服务器
![tim 20171213114441](https://user-images.githubusercontent.com/34498001/33920818-01ca0088-dffb-11e7-93f6-358054f330e5.jpg)
就可恢复正常，由于每次局域网连接，重启总会重新设置，我想知道有没有其他的办法能解决这个问题

**Comment by onplus** [comment]
用chromefirefox+switchyomega，不用系统代理不用ieedge

**Comment by Rookie14** [comment]
在win10的网络设置里，将代理中的“安装程序脚本”打开，一切恢复正常，刚刚发现的
![tim 20171213121420](https://user-images.githubusercontent.com/34498001/33921506-1529035a-dfff-11e7-8784-13bb1190ad0a.jpg)
