### ISSUE TITLE
vmware的nat开启ipv6对用teredo方式有影响

### ISSUE THREAD

**Issue by sumbrez** [XX-net/XX-Net#8990]
Windows 10，teredo类型enterpriseclient、服务器teredo-debian.remlab.net。
使用teredo后，如果vmware的nat开启了ipv6（默认fd15:4ba5:5a2b:1008::/64网段），则xx-net的ipv6状态为fail，无法fq。

**Comment by xxnet** [comment]
​应该是ipv6的路由设置问题，要研究ipv6 的路由规则才行
