### ISSUE TITLE
北京市公安局海淀分局下架翻墙软件通知

### ISSUE THREAD

**Issue by KeymanLai** [XX-net/XX-Net#900]
![12](https://cloud.githubusercontent.com/assets/12146207/9582737/b4ff48a6-5039-11e5-8023-691de4220378.jpg)

**Comment by dongoo** [comment]
额，好多没听过，涨知识了

**Comment by DD-L** [comment]
收藏了

**Comment by aOJzQT** [comment]
翻墙不息 ‏@boy1573 8月22日

京痞爷：一边是天津爆炸案事前治理和事后处理的粗糙紊乱，另一边是抗战大阅兵每个人、每一步、每一方队的精益求精，以及提早的限行和各种防范措施的落实。这是皇权制度的最好的写照：但凡涉及民众的事情，能少用一份心思就少用一份心思，但凡涉及皇上的事情，能用十二分心思绝不用十一份。
55 转推 19 收藏

翻墙不息 转推了
美国之音中文网 ‏@VOAChinese 11小时11小时前

#VOA连线：美国之音驻北京记者 #东方：我在北京出席过很多大型活动，这次阅兵是安保控制最严的一次；今晚午夜12点后，很多重要路段禁止通行车辆及行人；很多车辆不准进入北京；9/1至5号，宣传部门要求所有省市的卫星频道停止娱乐性节目，要播放各种抗战节目；股市在9/3至5号休市。
16 转推 4 收藏
翻墙不息 转推了
美国之音中文网 ‏@VOAChinese 11小时11小时前

#VOA连线：美国之音驻北京记者东方@VOADongFang：最新消息是，为了保证飞机安全，整个北京市区上空列为禁飞区，所有鸽子及鸟类都不得飞上天空，严重违反者将追究刑事责任；官方还让经过训练的猴子爬上树去摧毁鸟窝。http://bit.ly/weishi-live  直播中！
10 转推 5 收藏
翻墙不息 ‏@boy1573 13小时13小时前

还是网友厉害，一语道破习近平急于大阅兵的天机：习对2019年大庆再阅兵是没太大把握的。就如当年李自成逃出北京城之前，先登基过把瘾再说。

**Comment by kmcbest** [comment]
咱们XX-NET幸运地没有上榜

**Comment by Pseudo11** [comment]
看看这语言组织能力，就能判断真伪。

**Comment by linuxbelletian** [comment]
好多工具 听都没听过，下下来试试

**Comment by 992939504** [comment]
看看这语言组织能力+1乐死我了
