### ISSUE TITLE
既然IPv6目前有各种问题 能不能加个选项 只启用IPV4 就和之前稳定版本一样了

### ISSUE THREAD

**Issue by Micolash** [XX-net/XX-Net#9005]
IPv6 改注册表一样有间歇性断开问题 需要重新运行cmd

**Comment by gjbg1989** [comment]
只启用IPV4—— http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 没有么？
#8961 保持运行某批处理，或许能更稳定（不再偶尔中断）？

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33941256-f326a336-e04c-11e7-8af6-6028467b9c8d.png)
