### ISSUE TITLE
使用GAE访问Twitter时无法搜索？

### ISSUE THREAD

**Issue by QGB** [XX-net/XX-Net#9014]
https://twitter.com/search?f=tweets&q=btc&src=typd
没有关于 btc 的结果
你输入的词语查不到任何结果。你可能打错了或者你的搜索设置为你提供了潜在敏感内容防护

换了几个词都是这样

**Comment by zhencaihao** [comment]
以前没这个问题的。前阵子开始用gaeproxy代理后twitter只能搜索用户，其他信息都搜索不出结果。不知道这个是怎么回事。但是换成X-tunnel或其他软件却正常。

**Comment by yoooooooo** [comment]
同样，x-tunnel 可以搜索。用gae不行。

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/8122#issuecomment-342727674

**Comment by la0s** [comment]
跪了，原来是xxnet的原因，我说Mac(SSR)上怎么能正常搜索呢。。。

**Comment by AnyWAT** [comment]
试试：GAE下在搜索页地址栏的 // 后面加入 m. 成 https://mobile.twitter.com/。。。再继续
