### ISSUE TITLE
更新到最新版，发现不能使用了

### ISSUE THREAD

**Issue by ShixiangWang** [XX-net/XX-Net#9031]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:5434
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 258
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ShixiangWang** [comment]
显示ipv6 fail，但我找不到之前ipv6在哪设置了~

**Comment by gjbg1989** [comment]
use-ipv6: auto改为只用ipv6
netsh int ipv6 show teredo 贴运行结果

**Comment by gjbg1989** [comment]
类型 : client
服务器名称 : win1710.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : offline
错误 : 未能打开隧道适配器

**Comment by gjbg1989** [comment]
管理权限运行 netsh int ipv6 set teredo enterpriseclient default
#8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by ShixiangWang** [comment]
@gjbg1989  tertdo.bat 在哪下？我刚用notepad++新建一个然后拷贝，点击运行全是乱码，不知道该设置成什么格式的utf-8？

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/33997256-bf04f382-e11e-11e7-8748-e5dac3b48553.png)

**Comment by ShixiangWang** [comment]
@gjbg1989  万分感谢，我弄了那个ipv6自动转换步骤然后重启就可以用了。
