### ISSUE TITLE
macOS 10.13.2 运行Start后无反应

### ISSUE THREAD

**Issue by Mr-Phone** [XX-net/XX-Net#9036]
macOS版本 10.13.2
XX-net版本 3.8.7

运行Start后，显示如下

Last login: Fri Dec 15 08:44:23 on ttys000
Taot:~ Double$ /Users/Double/XX-Net-3.8.7/start ; exit;
XX-Net version:default
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

正常情况应该是：会启动软件，并在状态栏显示图标。

现在的情况是：软件未启动，状态栏无图标。

不知道问题出在什么地方。

**Comment by Mr-Phone** [comment]
Taot:~ Double$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by superabe** [comment]
把activity monitor里把所有的python进程关掉，再启动一下试试

**Comment by Mr-Phone** [comment]
@superabe 谢谢，搞定了
