### ISSUE TITLE
关于block stat及最近使用的各种问题

### ISSUE THREAD

**Issue by dreamidiot** [XX-net/XX-Net#905]
上海电信的。之前一直用2.0.5，挺流畅的，后来大约4、5天前开始变慢，本来也没太注意，但是昨天下午开始就几乎上不了了，以前block stat一直是ok，然后昨天下午block stat那栏就高频率的出现connect block。connect link 一直是0，0。但去文件里找那个badip的txt，里面是空的？一点记录都没有

然后昨天晚上换了2.1.2，一开始没问题，但是现在又不行了。有几点疑问：
1. 还是block stat问题，我发现好用的时候，一直是ok；不好用的时候，就高频率connect block。但是badip那个txt一直是空的。我是小白，不是很懂什么是蜜罐ip？
2. 我发现google ip num一开始确实有链接失败几次剔除不好的ip这一功能，数量确实时减时增。但是现在貌似是一直增加，但我反而不能翻了！是不是哪里出问题了？（我还有个联想：之前2.0.5也是ip数到3000后开始出现各种问题了，但是我的100th ip handshake一直都是500左右，这个应该不算高吧）
3.最近connect link一直是0，0，怎么回事？

题外话：最近速度大不如前了，有时网页也打不开，是不是有什么重大变化？
不知道是单独情况还是什么的，其他上海网友情况如何？
小白问了好多，麻烦各位大侠了，谢谢！@xxnet

附：

Sep 01 21:44:47 - [DEBUG] create ssl timeout fail.
Sep 01 21:44:47 - [DEBUG] create_ssl_connection fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.241.243 fail:timed out cost:2003 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.244.158 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.241.156 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.241.176 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.18.106 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.246.110 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.246.86 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.251.147 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.18.230 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.243.37 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] create_ssl 113.171.247.141 fail:timed out cost:2000 h:0
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:47 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:48 - [DEBUG] get ip:113.171.252.20 t:501
Sep 01 21:44:48 - [DEBUG] get ip:113.171.246.54 t:501
Sep 01 21:44:48 - [DEBUG] get ip:113.171.242.87 t:505
Sep 01 21:44:48 - [DEBUG] get ip:113.171.18.36 t:506
Sep 01 21:44:48 - [DEBUG] get ip:113.171.18.173 t:506
Sep 01 21:44:48 - [DEBUG] get ip:113.171.246.72 t:507
Sep 01 21:44:48 - [DEBUG] get ip:113.171.251.5 t:508
Sep 01 21:44:48 - [DEBUG] get ip:113.171.243.59 t:508
Sep 01 21:44:48 - [DEBUG] get ip:113.171.246.196 t:509
Sep 01 21:44:48 - [DEBUG] get ip:113.171.243.91 t:510
Sep 01 21:44:48 - [DEBUG] get ip:113.171.18.27 t:511
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.246.239 fail:timed out cost:2008 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.244.166 fail:timed out cost:2008 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.251.183 fail:timed out cost:2000 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.245.214 fail:timed out cost:2003 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.241.233 fail:timed out cost:2004 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.18.143 fail:timed out cost:2012 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.245.179 fail:timed out cost:2011 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.251.116 fail:timed out cost:2015 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.18.251 fail:timed out cost:2015 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.242.120 fail:timed out cost:2010 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.246.187 fail:timed out cost:2003 h:0
Sep 01 21:44:49 - [DEBUG]LOG_EXCEPT: create_ssl 113.171.242.117 fail:timed out cost:2003 h:0, Except:[Errno 9] Bad file descriptor
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.246.39 fail:timed out cost:2015 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.247.203 fail:timed out cost:2003 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.246.7 fail:timed out cost:2006 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.251.223 fail:timed out cost:2006 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.19.186 fail:timed out cost:2006 h:0
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.241.134 fail:timed out cost:2003 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.252.34 fail:timed out cost:2011 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:49 - [DEBUG] create_ssl 113.171.251.31 fail:timed out cost:2011 h:0
Sep 01 21:44:49 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] get ip:222.255.120.22 t:210
Sep 01 21:44:50 - [DEBUG] get ip:222.255.120.39 t:213
Sep 01 21:44:50 - [DEBUG] get ip:113.171.19.43 t:226
Sep 01 21:44:50 - [DEBUG] get ip:113.171.19.199 t:239
Sep 01 21:44:50 - [DEBUG] get ip:113.171.19.33 t:243
Sep 01 21:44:50 - [DEBUG] get ip:113.171.19.143 t:247
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.165 t:250
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.164 t:250
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.81 t:250
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.208 t:250
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.115 t:250
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.7 t:250
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.244 t:253
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.144 t:254
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.90 t:254
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.240 t:256
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.248 t:256
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.224 t:256
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.134 t:256
Sep 01 21:44:50 - [DEBUG] get ip:61.91.18.200 t:263
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.252.20 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.18.173 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.242.87 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.246.54 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.18.36 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.251.5 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.246.196 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.246.72 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.243.59 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.243.91 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] create_ssl 113.171.18.27 fail:timed out cost:2006 h:0
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:50 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] create_ssl 113.171.19.199 fail:timed out cost:2014 h:0
Sep 01 21:44:52 - [DEBUG]LOG_EXCEPT: create_ssl 113.171.19.43 fail:timed out cost:2014 h:0, Except:[Errno 9] Bad file descriptor
Sep 01 21:44:52 - [DEBUG] create_ssl 222.255.120.22 fail:timed out cost:2014 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 113.171.19.143 fail:timed out cost:2000 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 113.171.19.33 fail:timed out cost:2000 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 222.255.120.39 fail:timed out cost:2014 h:0
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.165 fail:timed out cost:2000 h:0
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.115 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.7 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.244 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.164 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.81 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.144 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.208 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.224 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.240 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.90 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.134 fail:timed out cost:2000 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.248 fail:timed out cost:2016 h:0
Sep 01 21:44:52 - [DEBUG] create_ssl 61.91.18.200 fail:timed out cost:2000 h:0
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:44:52 - [DEBUG] report_connect_fail network fail
Sep 01 21:45:02 - [DEBUG] create ssl timeout fail.
Sep 01 21:45:02 - [DEBUG] create_ssl_connection fail
Sep 01 21:45:02 - [DEBUG] GAE_Exception 2 'try max times'
Sep 01 21:45:02 - [WARNING] gae_exception:GAE_Exception() https://github.com/favicon.ico

**Comment by xxnet** [comment]
蜜罐是6月出现的，现在已经取消了，有了更多高级的封锁策略，而且各地各网络不一样。
block是长时间没有连接上，会进入休息状态。

你另外下载2.2.0试试，2.2.0 限制了连接间隔，不知道有没有效果。

2015-09-01 22:21 GMT+08:00 dreamidiot <notifications@github.com>:

**Comment by dreamidiot** [comment]
感谢作者答疑。@xxnet

我又去试了下2.2.0，小白结合自身情况（上海电信）说一下，希望能给作者一些启发：

1.  2.2.0一开始不能用，翻不了，block stat一直断。后来把里面自带的3000ip测了一下，好的就剩30+，然后重新导入就能翻了,但是挺卡的。

2.  2.1.2也是类似的情况，之前自己搜到的400+ip剔除不好的，就剩20+，重新导入就又复活了，速度还行，ip数量有增有减的功能貌似也恢复了。

3.  2.0.5也是，之前自己搜到的3000ip，剔除不好的后，又复活了。

4.  作者是不是能强化一下“剔除不好的ip”这一功能？感觉ip数量不是关键，关键是好的ip（貌似哪怕只有10+也能比较顺利的翻）。感觉不好的ip就是搅屎棍，即使里面有10+个好的ip，几乎照样翻不了。还有，之前2.1.2貌似ip数到200之后就只增不减了，剔除不掉不好的ip，是不是里面有什么问题 

谢谢！

**Comment by xxnet** [comment]
恩，谢谢反馈，这个是不错的信息。

策略里很多参数，如何做到自动调整，是比较难的。
以前ip多，可以放宽，比如一个ip重复连接的间隔，太频繁了容易被识别，所以设得保守。
结果很多时候去连那些被封了的ip。

还有另一个问题，每个用户的网络情况、GFW的策略有差别，难以推出适应各种情况的策略。

怎么搞，还要再想想

在 2015年9月2日 下午1:18，dreamidiot <notifications@github.com>写道：

**Comment by dreamidiot** [comment]
嗯，看来又要麻烦作者了。。。
非常感谢你 @xxnet  的无私奉献，还有其他各位大侠。
英雄！

**Comment by jeff201314** [comment]
说的太对了，用工具扫了几个good IP出来，导入Goagent都能稳定翻墙，但是XX-net有 Google IP num 	2970，connected link依然为0,0。刚刚关闭开机自动运行的XX-net，手工运行发现win10自带防火墙又弹出警告有点奇怪，然后connected link=11，过几分钟又不行了。总之，最近几天时好时坏，反而不如原版Goagent稳定。不过支持作者，还在一直保持更新！

**Comment by dreamidiot** [comment]
我的感觉是ip超过200后，就要导出ip用工具查一下，剔除不好的ip，然后速度就一下子上去了。

不过也有其他网友也是用2.1.2，但是觉得它会误删好的ip，这种情况貌似和我们的感觉相反。。。

每个地区的网络环境真的差异好大
