### ISSUE TITLE
能正常使用google搜索，但是不能访问gmail,images等网页

### ISSUE THREAD

**Issue by pfpfpfp** [XX-net/XX-Net#9053]
访问gmail会报：
此网站无法提供安全连接
www.google.com 发送的响应无效。
尝试运行 Windows 网络诊断。
ERR_SSL_PROTOCOL_ERROR

其他需要梯子的twitter，facebook能正常访问。

试过根据wiki自查更新证书后，依然不能访问。

**Comment by pfpfpfp** [comment]
Dec 15 20:18:11.902 - [WARNING] server app return fail, status:502

Dec 15 20:18:17.105 - [DEBUG] 2607:f8b0:401a:21::a worker close:idle timeout

Dec 15 20:18:17.172 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:18:17.172 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:18:17.172 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:18:17.172 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:18:20.741 - [DEBUG] 2404:6800:400b:20::d worker close:idle timeout

Dec 15 20:18:22.269 - [DEBUG] 2607:f8b0:4009:3b::8 worker close:idle timeout

Dec 15 20:18:22.681 - [DEBUG] 2404:6800:400b:18::18 worker close:idle timeout

Dec 15 20:18:23.286 - [DEBUG] 2607:f8b0:4017:29::7 worker close:idle timeout

Dec 15 20:18:23.518 - [DEBUG] 2607:f8b0:4000:38::9 worker close:idle timeout

Dec 15 20:18:23.895 - [DEBUG] 2607:f8b0:401a:23::8 worker close:idle timeout

Dec 15 20:18:24.301 - [DEBUG] 2607:f8b0:401a:5::7 worker close:idle timeout

Dec 15 20:18:24.425 - [INFO] GAE CONNECT www.google.com:443

Dec 15 20:18:24.426 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:www.google.com

Dec 15 20:18:24.429 - [INFO] GAE CONNECT www.google.com:443

Dec 15 20:18:24.430 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:www.google.com

Dec 15 20:18:24.439 - [DEBUG] GAE POST https://www.google.com.hk/gen_204?atyp=i&ct=slh&cad=&ei=K70zWsTeJuXOjwT1jJ2oDQ&s=2&v=2&pv=0.8400697760614766&me=16:1513340253743,V,0,0,0,0:46504,U,46504:0,V,0,0,1704,870:4176,c,1418,577:0,e,U&zx=1513340304423

Dec 15 20:18:24.439 - [DEBUG] accept_br_encoding for https://www.google.com.hk/gen_204?atyp=i&ct=slh&cad=&ei=K70zWsTeJuXOjwT1jJ2oDQ&s=2&v=2&pv=0.8400697760614766&me=16:1513340253743,V,0,0,0,0:46504,U,46504:0,V,0,0,1704,870:4176,c,1418,577:0,e,U&zx=1513340304423

Dec 15 20:18:24.455 - [INFO] GAE CONNECT www.google.com:443

Dec 15 20:18:24.455 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:www.google.com

Dec 15 20:18:24.457 - [INFO] GAE CONNECT www.google.com:443

Dec 15 20:18:24.457 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:www.google.com

Dec 15 20:18:24.480 - [DEBUG] 2a00:1450:400a:2::13 worker close:idle timeout

Dec 15 20:18:24.912 - [INFO] GAE t:473 s:0 POST https://www.google.com.hk/gen_204?atyp=i&ct=slh&cad=&ei=K70zWsTeJuXOjwT1jJ2oDQ&s=2&v=2&pv=0.8400697760614766&me=16:1513340253743,V,0,0,0,0:46504,U,46504:0,V,0,0,1704,870:4176,c,1418,577:0,e,U&zx=1513340304423 0:start_request,0:get_task,0:get_worker:2607:f8b0:401d:6::9,0:h1_req,471:h1_get_head,0:get_response,:0

Dec 15 20:18:25.162 - [DEBUG] 2607:f8b0:4000:39::c worker close:idle timeout

Dec 15 20:18:26.730 - [DEBUG] create_ssl update ip:2607:f8b0:400a:8::c time:388 h2:0

Dec 15 20:18:29.449 - [DEBUG] 2607:f8b0:4016:14::e worker close:idle timeout

Dec 15 20:18:29.802 - [DEBUG] 2607:f8b0:400a::9 worker close:idle timeout

Dec 15 20:18:32.090 - [DEBUG] 2404:6800:400b:18::f worker close:idle timeout

Dec 15 20:18:32.955 - [DEBUG] 2a00:1450:4005:8::c worker close:idle timeout

Dec 15 20:18:37.831 - [DEBUG] create_ssl update ip:2607:f8b0:4016:17::16 time:488 h2:0

Dec 15 20:18:46.353 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:18:46.355 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:18:46.357 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:18:46.358 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:19:05.955 - [INFO] GAE CONNECT android.clients.google.com:443

Dec 15 20:19:05.956 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:android.clients.google.com

Dec 15 20:19:05.957 - [INFO] GAE CONNECT android.clients.google.com:443

Dec 15 20:19:05.957 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:android.clients.google.com

Dec 15 20:19:09.534 - [DEBUG] 2607:f8b0:400a:9::15 worker close:idle timeout

Dec 15 20:19:12.585 - [DEBUG] 2607:f8b0:400a:4::a worker close:idle timeout

Dec 15 20:19:13.571 - [DEBUG] 2607:f8b0:400a:c::e worker close:idle timeout

Dec 15 20:19:16.447 - [DEBUG] 2607:f8b0:400a:8::19 worker close:idle timeout

Dec 15 20:19:19.000 - [DEBUG] create_ssl update ip:2607:f8b0:4016:11::9 time:581 h2:0

Dec 15 20:19:19.546 - [DEBUG] 2607:f8b0:401d:2::c worker close:idle timeout

Dec 15 20:19:19.655 - [DEBUG] 2607:f8b0:400a:9::8 worker close:idle timeout

Dec 15 20:19:24.438 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:19:24.438 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:19:24.438 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:19:24.438 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:19:33.647 - [DEBUG] connect 2607:f8b0:400a:9::8 fail:error(' certficate is none',)

Dec 15 20:19:33.647 - [DEBUG] report_connect_fail:2607:f8b0:400a:9::8

Dec 15 20:19:35.928 - [DEBUG] create_ssl update ip:2607:f8b0:4016:14::e time:1999 h2:0

Dec 15 20:19:45.054 - [DEBUG] restore ip:2607:f8b0:400a:9::8

Dec 15 20:19:49.469 - [INFO] GAE CONNECT mtalk.google.com:443

Dec 15 20:19:49.470 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:mtalk.google.com

Dec 15 20:19:49.473 - [INFO] GAE CONNECT mtalk.google.com:443

Dec 15 20:19:49.474 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:mtalk.google.com

Dec 15 20:20:01.622 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:20:01.622 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

Dec 15 20:20:01.622 - [INFO] GAE CONNECT clients4.google.com:443

Dec 15 20:20:01.622 - [INFO] ssl error: [SSL] PEM lib (_ssl.c:2718), create full domain cert for host:clients4.google.com

**Comment by pfpfpfp** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:8326 ipv4:0 ipv6:4714
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:0
worker: h1:13 h2:0
scan-ip-thread-num: 500
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​1. 试试 3.8.7
  这个版本的 证书部分有更新
2. Chrome 浏览器打开，按F12，看下面的secure部分，提示什么问题

**Comment by pfpfpfp** [comment]
@xxnet 更新后已解决问题
