### ISSUE TITLE
X-TUNNEL 什么时候支持支付宝付款,,好多人没有paypal呀.

### ISSUE THREAD

**Issue by wiiii** [XX-net/XX-Net#9057]
X-TUNNEL,希望尽快开通支付宝付款方式,paypal没有账户,有账户了,没有银行卡,一直购买不了.谢谢

**Comment by tmttmd** [comment]
注册一个就好，使用挺方便的，能直接人民币对美元付款

**Comment by mitanikanae** [comment]
银行卡可以直接去办一张啊，办张农行的卡就行，现在支付宝国内版支持直接用农行的借记卡支付的.
