### ISSUE TITLE
科学上网？

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#9061]
科学上网？是啥意思？
为什么每次看到这几个字就让我想笑？
是高科技上网，技术上网的意思吗？
哈哈哈！

**Comment by lele2010lele** [comment]
没有技术，没有科学，就是上个网而已。。。没你的技术高，可以出去了吗？

**Comment by GoodSake** [comment]
....ok...you can dismiss.
have a nice day, sir!

**Comment by nbwxbo** [comment]
大清有文字狱，文人敏感词避讳。现在基本还是类似，以免麻烦。

**Comment by GoodSake** [comment]
哦，原来如此！

**Comment by deekjfs** [comment]
推荐一个自用的shadowsocks  SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com/

**Comment by ygccbkk** [comment]
推荐一个自用的shadowsocks  SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com/

**Comment by qionpolo** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
