### ISSUE TITLE
xx这样下去会不会有危险？

### ISSUE THREAD

**Issue by ShadowEmbrace** [XX-net/XX-Net#9062]
以前xxnet没这么多人用，issues也不多，现在这么热闹，会不会容易被搞啊。。。这可是我用得最爽的梯子了。。。

**Comment by GoodSake** [comment]
旧的不去，新的不来。
新旧交替，时间而已。

**Comment by onplus** [comment]
因为已经被限制了才这么热闹

**Comment by nbwxbo** [comment]
怎么搞？跨国抓人？D支部至少还没遍布全球？技术无止境。专制下，追求绝对服从，没啥创新力。
