### ISSUE TITLE
无法开启teredo，bat后详情如下

### ISSUE THREAD

**Issue by jaxguo** [XX-net/XX-Net#9064]
Windows IP 配置

   主机名  . . . . . . . . . . . . . : DESKTOP-NN0QQDS
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

无线局域网适配器 WLAN:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC
   物理地址. . . . . . . . . . . . . : 40-E2-30-0C-F9-45
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 本地连接* 1:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   物理地址. . . . . . . . . . . . . : 42-E2-30-0C-F9-45
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   物理地址. . . . . . . . . . . . . : C4-54-44-58-D2-44
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.0.201(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.0.1
   DNS 服务器  . . . . . . . . . . . : 114.114.114.114
                                       8.8.8.8
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        系统        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        系统        256  fe80::/64                   3  WLAN
否        系统        256  fe80::/64                   5  本地连接* 1
否        系统        256  fe80::8c9c:e5ed:9ea:125b/128    5  本地连接* 1
否        系统        256  fe80::bc56:5156:4e01:3fb3/128    3  WLAN
否        系统        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        系统        256  ff00::/8                    3  WLAN
否        系统        256  ff00::/8                    5  本地连接* 1

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
  3          25        1500  disconnected  WLAN
  5          25        1500  disconnected  本地连接* 1

查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        50      0  ::1/128
        40      1  ::/0
        35      4  ::ffff:0:0/96
        30      1  2002::/16
         5      1  2001::/32
         3     13  fc00::/7
         1     11  fec0::/10
         1     12  3ffe::/16
         1      3  ::/96

接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 3: WLAN

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::bc56:5156:4e01:3fb3%3

接口 5: 本地连接* 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::8c9c:e5ed:9ea:125b%5

===========================================================================
接口列表
  3...40 e2 30 0c f9 45 ......Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC
  5...42 e2 30 0c f9 45 ......Microsoft Wi-Fi Direct Virtual Adapter
 12...c4 54 44 58 d2 44 ......Realtek PCIe GBE Family Controller
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.0.1    192.168.0.201    291
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      192.168.0.0    255.255.255.0            在链路上     192.168.0.201    291
    192.168.0.201  255.255.255.255            在链路上     192.168.0.201    291
    192.168.0.255  255.255.255.255            在链路上     192.168.0.201    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.0.201    291
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.0.201    291
===========================================================================
永久路由:
  网络地址          网络掩码  网关地址  跃点数
          0.0.0.0          0.0.0.0      192.168.0.1     默认 
===========================================================================

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  1    331 ::1/128                  在链路上
  1    331 ff00::/8                 在链路上
===========================================================================
永久路由:
  无

**Comment by gjbg1989** [comment]
先disable_ipv6.bat，再enable_ipv6.bat

**Comment by jaxguo** [comment]
那肯定是先disabled，再enable。但是还是这样

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by jaxguo** [comment]
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4836 ipv4:17 ipv6:3700
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 317
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
use-ipv6: auto——改为只用ipv6
proxy_state: Fail
ca_state: Fail——在代理设置正常的浏览器内打开控制页
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by jaxguo** [comment]
试过，代理设置正常的浏览器内打开控制页？我一直是chrome的。
依然不行，不过有几个现象
Ping 请求找不到主机 ipv6.test-ipv6.com。请检查该名称，然后重试。
正在 Ping ipv6.test-ipv6.com [2001:470:1:18::4:230] 具有 32 字节的数据:请求超时。
请求超时。
请求超时。

上面是ping的情况
另外一个是


隧道适配器 Teredo Tunneling Pseudo-Interface:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

**Comment by jaxguo** [comment]
PS C:\Windows\system32> netsh interface Teredo show state
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无法通过 UDP 访问辅助 teredo 服务器

**Comment by gjbg1989** [comment]
终极方法：
确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。

**Comment by mktsyy** [comment]
感谢楼上,总算正常了.

**Comment by pinoren** [comment]
谢谢网友gjbg1989的终极方法，困扰了多天的问题终于解决了！

**Comment by jaxguo** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (secondary server)
客户端类型              : teredo client
网络                    : managed


我的重启后不是dormant。尴尬

**Comment by gjbg1989** [comment]
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。

**Comment by jaxguo** [comment]
感谢!重启几次换了服务器后成功了，看来还是teredo的服务器稳定性的问题

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8961 或许有助稳定？

**Comment by jaxguo** [comment]
关闭了ipv6 ，所有奇怪问题全部没了，使用了一个月，没问题了，谢谢支持
