### ISSUE TITLE
X-tunnels使用艰难

### ISSUE THREAD

**Issue by hsrrtx** [XX-net/XX-Net#9066]
一直都是在用最新的测试版，感觉x-tunnel的使用越来越难了，经常会发现无法使用。家里上海电信，12/16 晚就是无法使用中。。。而且在公司用过联通的出口和移动的出口，也发现联通的出口经常无法使用X-tunnel，而似乎移动的出口就好一点~~

因为有x-tunnel 流量了，GAE-proxy就直接关闭了，但是估计应该没有什么关联的吧？？

目前状态：
GAE front 的score = false；success num =0
Cloudflare front 的score=false； success num =23

Dec 16 19:58:26.030 - [INFO] login_session ptuncvgm time:2401 msg:Success
Dec 16 19:58:36.079 - [INFO] session started.
Dec 16 19:58:36.081 - [INFO] socks5 ('127.0.0.1', 64885) connect to www.googleapis.com:443 conn_id:1
Dec 16 19:58:36.081 - [INFO] socks5 ('127.0.0.1', 64886) connect to accounts.google.com:443 conn_id:2
Dec 16 19:58:36.081 - [INFO] socks5 ('127.0.0.1', 64902) connect to www.googleapis.com:443 conn_id:4
Dec 16 19:58:36.081 - [INFO] socks5 ('127.0.0.1', 64889) connect to mtalk.google.com:5228 conn_id:3
Dec 16 19:58:36.082 - [INFO] socks5 ('127.0.0.1', 64890) connect to www.googleapis.com:443 conn_id:5
Dec 16 19:58:36.082 - [INFO] socks5 ('127.0.0.1', 64904) connect to www.googleapis.com:443 conn_id:6
Dec 16 19:58:38.474 - [WARNING] server session_id:ptuncvgm not exist, reset session.
Dec 16 19:58:38.474 - [DEBUG] session reset

Dec 16 20:07:56.525 - [DEBUG] ip:190.93.246.66 real fail
Dec 16 20:08:01.914 - [DEBUG] ip:198.41.222.141 real fail
Dec 16 20:08:07.204 - [DEBUG] ip:104.18.34.153 real fail
Dec 16 20:08:12.603 - [DEBUG] ip:104.27.58.205 real fail
Dec 16 20:08:13.036 - [DEBUG] ip:104.28.20.125 real fail
Dec 16 20:08:16.972 - [DEBUG] restore ip:104.27.7.95
Dec 16 20:08:22.348 - [DEBUG] ip:104.17.1.92 real fail
Dec 16 20:08:22.726 - [DEBUG] ip:141.101.113.178 real fail
Dec 16 20:08:23.969 - [DEBUG] restore ip:104.28.212.109
Dec 16 20:08:24.860 - [DEBUG] restore ip:104.16.18.192
Dec 16 20:08:25.259 - [DEBUG] ip:104.28.188.43 real fail
Dec 16 20:08:26.278 - [DEBUG] restore ip:104.25.60.161
Dec 16 20:08:31.589 - [DEBUG] ip:190.93.246.144 real fail
Dec 16 20:08:32.595 - [DEBUG] restore ip:198.41.221.163
Dec 16 20:08:33.493 - [DEBUG] restore ip:190.93.244.205
Dec 16 20:08:38.941 - [DEBUG] ip:104.25.64.252 real fail
Dec 16 20:08:40.181 - [DEBUG] restore ip:162.159.238.220
Dec 16 20:08:43.244 - [DEBUG] create ssl timeout fail.
Dec 16 20:08:45.485 - [DEBUG] ip:141.101.121.118 real fail
Dec 16 20:08:50.784 - [DEBUG] ip:104.24.109.57 real fail
Dec 16 20:08:56.097 - [DEBUG] ip:141.101.114.164 real fail
Dec 16 20:08:56.908 - [DEBUG] ip:104.16.28.50 real fail
Dec 16 20:09:02.433 - [DEBUG] ip:172.64.135.11 real fail
Dec 16 20:09:03.524 - [DEBUG] restore ip:104.17.121.191
Dec 16 20:09:04.767 - [DEBUG] restore ip:104.19.2.101
Dec 16 20:09:06.080 - [DEBUG] restore ip:104.16.101.35
Dec 16 20:09:11.604 - [DEBUG] ip:104.17.110.14 real fail
Dec 16 20:09:16.940 - [DEBUG] ip:104.28.88.194 real fail

**Comment by hsrrtx** [comment]
GAE proxy在家同一时间开了ipv6倒是可以使用，这个有点郁闷啊~~免费的比收费的好用~~ipv4没地址~~~

**Comment by gjbg1989** [comment]
ipv4有地址还用开ipv6隧道？
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by xxnet** [comment]
​X-Tunnel 会使用GAE作为通道，所以请保持GAE 打开。
X-Tunnel 可以获得完全的加密通讯，而GAE因为不需要SSL 2次握手，会更快一些，是正常的。
完全的加密通讯，在手机上会显得更有价值，目前还在推进中。

新版 3.9.0 SmartRouter，可以自动在GAE和X-Tunnel中进行切换

**Comment by hsrrtx** [comment]
其实我的需求就是能够在不同网络环境中稳定使用翻墙功能。因为会在公司和家里不停切换网络环境。其实公司的限制和监控可能会比较多，比如IPv6 不能使用之类的。

目前看来，XX-net的还基本满足需求。不过总归偶尔会出现无法翻墙的现象，观察下来主要还是无法连接服务器之类的问题。
那么购买X-tunnel的需求就是稳定翻墙，当然速度快最好，但是如果足够稳定我也OK，因为一般也不会用到持续大流量。而且钱都花了，不稳定肯定不爽的啊~~毕竟花钱和免费是两回事啊~~哈哈~~

**Comment by xxnet** [comment]
​X-Tunnel 接下来会再进行一波优化，提高联通能力，预计一个月后吧，谢谢支持了。
