### ISSUE TITLE
3.8.4版本能开启ipv6科学上网，更新3.8.5版本后无法开启ipv6科学上网

### ISSUE THREAD

**Issue by egg347** [XX-net/XX-Net#9068]
在3.8.4版本时，光ipv4无法上网，开启ipv6才能科学上网。
升级3.8.5版本后，ipv4打开，ipv6fail，却提示“XX-Net 3.8.5，一切正常，你可以访问真正的互联网了。”然而我还是无法科学上网，尝试按照之前3.8.4版本中脚本方法尝试重新打开ipv6，一直失败。

开启ipv6的教程中说不要混用两种方法，所以我也没继续尝试别的方法。我的系统是win10专业版。

另，我看其他人提问会贴个日志文件？那个在哪啊？

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果及XX-Net诊断信息

![default](https://user-images.githubusercontent.com/13290970/34074544-7fb34e5c-e2ec-11e7-8f83-4b10604ac9ad.png)

**Comment by egg347** [comment]
感谢回复！

netsh int ipv6 show teredo 结果：（我在3.8.4版本是直接跑enable_ipv6.bat就能上网了）

Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                   : 所需的 BFE 服务未运行

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:43 ipv4:4 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:1 h2:3
scan-ip-thread-num: 10
ip-quality: 203
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
use-ipv6: auto 改为只用ipv6
错误 : 所需的 BFE 服务未运行
![default](https://user-images.githubusercontent.com/13290970/34074730-a7222518-e2f0-11e7-837c-af4dea1729e5.png)

**Comment by gjbg1989** [comment]
（我在3.8.4版本是直接跑enable_ipv6.bat就能上网了）——正常是更新3.8.5版本后无需再enable_ipv6.bat也正常。尝试先disable_ipv6.bat再enable_ipv6.bat

**Comment by egg347** [comment]
我最早的尝试就是先disable再enable。刚刚把use-ipv6改为force_ipv6了，BFE功能是正在运行的。依旧ipv6 status:fail 。

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果

**Comment by egg347** [comment]
跟原来一样。

类型 : disabled
服务器名称 : teredo.remlab.net
客户端刷新间隔 : 30 秒
客户端端口 : unspecified
状态 : offline
错误 : 所需的 BFE 服务未运行

而我也确定服务BFE是开启的。

**Comment by gjbg1989** [comment]
而我也确定服务BFE是开启的——系统认你还是。。。
截图证明你所说的

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34074954-9d92a690-e2f4-11e7-8670-10960b35d0b9.png)

**Comment by egg347** [comment]
我确定系统认。。。我传不上图啊。。好久都是上传中。

电脑-管理-服务 里面是正在运行的。
任务管理器-服务 里面也是正在运行的。

我刚刚去尝试重启BFE服务，结果竟然被拒绝访问。我以为是权限的问题，然后去注册表一看，BFE是完全控制权限。。。另外，您能帮我答疑下这个吗？

**Comment by gjbg1989** [comment]
不懂，问你——防火墙关了？貌似必须开启才正常——也没回应
自己解决了——错误 : 所需的 BFE 服务未运行——再继续😂

**Comment by gjbg1989** [comment]
尝试：结束进程pythonw.exe，删除data外全部目录与文件，重新解压软件包，看那错误。。。

**Comment by egg347** [comment]
抱歉。没看到您那句防火墙的话，正好在图片下面。我是开启的。我试试您说的这个方法。

**Comment by gjbg1989** [comment]
系统有360等国祸？

**Comment by gjbg1989** [comment]
系统安全模式修复？

**Comment by egg347** [comment]
感谢您的耐心，我的电脑没有安装360=-=国祸2333。
之前没法重启BFE服务是因为我的windows defender给阻挡了。
最终是通过Teredo连接了，可是我没有像教程里一样把ipv6协议的钩去掉。我做了下列操作，但是我不知道下列哪些操作是有效操作。贴出来，我是win10专业版，有需要的参考吧：

1. cmd ： “netsh winsock reset”
2. cmd ： “ipconfig /release6”
3. cmd ： "ipconfig /new6"
（对网络的重置，但是感觉没效果- -）

4. gpedit.msc ： 计算机配置 - 管理模块 - windows组件 - windows defender防病毒程序 - 关闭 Windows Defender 防病毒程序，选择“已启用”。
（关闭了windows defender，之后记得开启）

5. services.msc ： 找到 Peer Networking Grouping service 和 PNRP Machine Name Publication Service，设置其启动属性为“自动”，并启动服务。
6. regedit ： 找到HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters，将目录下的DisabledComponents的键值改为0。如果这个键不存在，可以右键新建-DWORD（32位）值，命名为DisabledComponents，数值数据设为0。（！此步更改ipv6的键值，最好先备份，找到要备份的注册表项，文件-导出）
7.重启电脑

**Comment by gjbg1989** [comment]
没有像教程里一样把ipv6协议的钩去掉也成功了——me too

**Comment by gjbg1989** [comment]
关闭了windows defender——问题的关键？
![default](https://user-images.githubusercontent.com/13290970/34075959-a9521e34-e312-11e7-9cbd-6c6303646202.png)

**Comment by egg347** [comment]
windows defender只是可能影响服务的开启、关闭？我是在微软社区里面看到有人的提问，官方答复的步骤第一步是把杀毒和防火墙暂时关闭，我就也这么做了。我觉得关键应该是5和6吧。

**Comment by gjbg1989** [comment]
（我在3.8.4版本是直接跑enable_ipv6.bat就能上网了）——貌似更新3.8.5版本后无需任何操作也应正常。不正常，是因为胡乱折腾了什么。。。

**Comment by egg347** [comment]
我也没折腾啊。。只是提示更新。。我自动更新下不下来。手动下载了一次，仅此而已。然后就不能用了。真要说折腾，难道是我科学上网，被联通那边封了ipv6？

**Comment by gjbg1989** [comment]
我觉得关键应该是5和6吧——5已贴图，手动没运行。6是（没有了错误 : 所需的 BFE 服务未运行）推荐

**Comment by gjbg1989** [comment]
一直是：先前正常，手动更新（下载、结束进程pythonw.exe、解压）后无需任何操作也应正常
