### ISSUE TITLE
速度不错哦，哈哈哈！

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#9078]
速度不错哦，哈哈哈！

![snap3](https://user-images.githubusercontent.com/19205130/34077194-40123f8c-e338-11e7-97bf-da0a9ab70909.png)

**Comment by gjbg1989** [comment]
电脑多大的内存？

**Comment by GoodSake** [comment]
4G

**Comment by gjbg1989** [comment]
😂4GB开辣么多网页，不怕坚持不了5年不关机？
