### ISSUE TITLE
请大家还是少去phuslu那里发表讨伐共匪的言论！！

### ISSUE THREAD

**Issue by aOJzQT** [XX-net/XX-Net#908]
> Shadowsocks 的作者 Clowwindy，因为受到朝廷方面的胁迫，不得不删除其在 GitHub 上的开源翻墙项目；另外，几乎在同一时间，GoAgent 的作者也删除了其在 GitHub 上的翻墙项目（有可能也是受到朝廷的威胁）

phuslu的身份已经被共匪确认并定位，只是现在他因为工作原因出差美国，但年底很可能回国。
> phuslu已经在其goproxy项目的issue中不止一次的提醒要大家”温和发言“，并关掉所有相关issue，可以去翻那些closed的issue。

**我们别给phuslu添麻烦了，xx大神这里应该很安全，匿名做的很好，共匪无法确定xx大神的身份，所以大家可以畅所欲言。**

* 讨论地址
一个是[这里](https://github.com/XX-net/XX-Net/issues)，另一个是xx大神前面组建的Google Group讨论组：
https://groups.google.com/forum/#!forum/fqlt

**Comment by Sherman-Liu** [comment]
这里是提交Issue的地方，请不要污染Issue的时间线，谢谢。

**Comment by xxnet** [comment]
比较笼统的讨论，建议到翻墙论坛吧
https://groups.google.com/forum/#!forum/fqlt

2015-09-02 13:11 GMT+08:00 Sherman-Liu <notifications@github.com>:
