### ISSUE TITLE
又一次什么都没做但是一直”请检查浏览器代理设置“。

### ISSUE THREAD

**Issue by UnuboreJoe** [XX-net/XX-Net#9083]
IPV6显示的是OK的，但是CA和浏览器设置一直是Fail

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36 OPR/49.0.2725.47
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5841 ipv4:7 ipv6:4192
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:0
worker: h1:28 h2:0
scan-ip-thread-num: 200
ip-quality: 246
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
proxy_state: Fail
ca_state: Fail——不是浏览器代理设置或选用的问题？
现在某些扩展的设置也会有影响，如 Disconnect ，使用 whitelist site 就不行，blacklist site 就 OK
禁用某些扩展。。。

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果

**Comment by UnuboreJoe** [comment]
果然是扩展的锅！谢了！
