### ISSUE TITLE
新手求助，网页打不开

### ISSUE THREAD

**Issue by bruceyaogit** [XX-net/XX-Net#909]
刚开始用，新手，有几个问题请大家帮忙：
1.原来使用goagent，配合chrome+switchyomega
2.刚开始运行测试版2.2.0后，还没有搞懂怎么设置，同时也还开着goagent，可以上网
3.部署个人appid的时候，一直timeout和滚回不成功。
4.一直不懂怎么在switchyomega设置。
---------目前
5.现在单开goagent，网页打不开，小窗里没任何信息。
6.单开xx，网页打不开。
7.两者同时开，还是打不开。

求助各位大神。

**Comment by yeahwu** [comment]
goagent和xx的端口是一样的，switchyomega不用设置。appid只要在xx主页配置项填上你的id保存即可。这几天gfw发力，打不开也很正常，换稳定版试试。

**Comment by bruceyaogit** [comment]
谢谢yeahwu 解答。请问是不是不用再开goagent了？
另外appid是不是不用部署？

**Comment by yeahwu** [comment]
不用再开goagent了，如果是以前goagent上用的id，直接填上就好了。不用部署。
