### ISSUE TITLE
smart_router通过http明文查询域名，遇到敏感的名字岂不是还是很容易被reset。

### ISSUE THREAD

**Issue by heroboy** [XX-net/XX-Net#9090]
建议通过tcp查询域名，大部分的域名服务器都支持tcp方式查询，而且不会被污染。

我自己就在用 https://github.com/heroboy/DnsProxy

最近我发觉开了xxnet就不能通过127.0.0.1访问53端口了，才发现多了这么个东西。

**Comment by gjbg1989** [comment]
https://github.com/chengr28/Pcap_DNSProxy

**Comment by TOBOM** [comment]
敢问smart-router是什么东西.求科普

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 最下面
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by roc1010kmt** [comment]
@gjbg1989 使用Pcap_DNSProxy會不會被rst？

**Comment by xxnet** [comment]
​smart_router是通过https 查询域名，不是明文

**Comment by heroboy** [comment]
@xxnet 我看的这里https://github.com/XX-net/XX-Net/blob/91bf3181e6463863cdbfbdaa3d4f955eb7f1fbfa/code/default/smart_router/local/dns_server.py#L35
然后，我访问了一下， `https://dns.xx-net.net/query?domain=www.baidu.com` 是访问不了的。改成`http`就可以

**Comment by xxnet** [comment]
是​经过x-tunnul 访问的，所以墙内是加密的
