### ISSUE TITLE
设置页面在使用pac并且连接正常时无法用edge访问

### ISSUE THREAD

**Issue by lychichem** [XX-net/XX-Net#9096]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  测试版未解决

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  没有搜索到类似问题

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
Wiki中没有相关页面

* 简单描述遇到的问题：
在重装系统（win10 16299 64位专业版），并应用来自https://github.com/lennylxx/ipv6-hosts 的hosts后，当xx-net使用gae模块，并设置为全局pac，且工作正常时，127.0.0.1:8085（设置页面）无法用edge打开

* 做过哪些尝试：
取消全局代理，可以打开此页面
将127.0.0.1改成localhost，可以打开设置页面
注释hosts中的127.0.0.1条目，无效

* 请贴出对应模块的状态页
无法提供，因为无法访问此页

另外在重装系统前是正常的，重装日期是12月16日中午左右

**Comment by onplus** [comment]
局域网地址不使用代理

**Comment by lychichem** [comment]
@onplus 没有开这个，我重装系统之后用的xx-net是直接从重装前的机子上拷来的，设置没动过

**Comment by smgzj** [comment]
edge确实有问题，用一阵xx后，会提示代理设置错误，而且也没法恢复初始设置
IE，chrome一点没问题

**Comment by lychichem** [comment]
这个问题我也有，至今原因不明，我只能多次删除证书重新导入了，但是显然这不是解决办法，我估计可能edge有奇妙的缓存机制？

发送自我的iPhone

在 2017年12月18日，14:39，smgzj <notifications@github.com<mailto:notifications@github.com>> 写道：


edge确实有问题，用一阵xx后，会提示代理设置错误，而且也没法恢复初始设置
IE，chrome一点没问题

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/1942
