### ISSUE TITLE
移植python3问题

### ISSUE THREAD

**Issue by inksnw** [XX-net/XX-Net#9098]
新手想学习一下xx-net代码提高下水平,想把gae_proxy这一模块移植到Python3,大部分问题都在逐渐解决,但cert_util.py这个生成证书的一直有问题,参考了分支的python3还是报OSError: exception: ,水平所限不知道怎么办了,有没有好心人帮助一下

**Comment by GoodSake** [comment]
Python3, Python2还不兼容啊，好奇怪哦。加油！

**Comment by gjbg1989** [comment]
😱哇。。。

**Comment by onplus** [comment]
参考这个呢？
https://github.com/xyuanmu/XX-Mini

**Comment by xxnet** [comment]
​支持一下，最好做成兼容模式，看这形势，还要1-2年 python3 才能完全普及。

**Comment by dou4cc** [comment]
@xxnet 翻看你commit note里的拼写/语法错误、琢磨你的断句，有种说不出的感觉。总之保护好你自己吧！
