### ISSUE TITLE
能不能自动升级啊。。。

### ISSUE THREAD

**Issue by Ghostsnail** [XX-net/XX-Net#91]
我一天手动升级了3次。。。。

**Comment by xxnet** [comment]
我都没有发布公共，就不用升级了。

这些发布解决的，都是一些小bug，特别针对新用户方便用的。
建议在你无法翻墙的时候，或者我发了公告、或者推送自动升级的时候，再来升级吧。

自动升级的机制是有的，只是觉得没有非常必要，就不会去干扰用户了。

2015-03-30 9:43 GMT-04:00 Ghostsnail <notifications@github.com>:

**Comment by Ghostsnail** [comment]
又有新版本了...
用了几天，的确很方便，不用自己找IP，申请ID和部署也比裸用方便。感谢XXNET做出这个软件方便大家。
