### ISSUE TITLE
64.233.162.85  无法导入

### ISSUE THREAD

**Issue by redstoneleo** [XX-net/XX-Net#910]
这个ip怎么无法导入
64.233.162.85
我查看了good_ip.txt，里面也没有这个ip。

**Comment by dingmx2008** [comment]
不能在good_ip.txt导入，应在“导入导出IP”项内导入。

**Comment by redstoneleo** [comment]
@dingmx2008 我就是按你说的方式无法导入

**Comment by lygoing** [comment]
@redstoneleo 你看看是不是导入之后被删除了？在页面执行导入操作的时候，页面有提示导入了多少个IP 的提示啊！

**Comment by redstoneleo** [comment]
没有导入之后被删除什么的，提示导入0个ip

**Comment by dingmx2008** [comment]
把ip都导出来，仔细查有没有64.233.162.85，导出的ip与good_ip.txt里的不完全一样。
一般导入都没问题的。

**Comment by redstoneleo** [comment]
谢谢啦
