### ISSUE TITLE
@gjbg1989 求助：用了teredo.bat，各种方法试过，还是不行，

### ISSUE THREAD

**Issue by wamgel** [XX-net/XX-Net#9102]
C:\WINDOWS\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.ipv6.microsoft.com (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能解析服务器名

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
use-ipv6: auto——改为只用 ipv6
确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by QGB** [comment]
C:\Users\Administrator>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by gjbg1989** [comment]
类型 : client——貌似没听从建议，至少不是全部，或贴图证明做到了上上楼的。。。

**Comment by gjbg1989** [comment]
@QGB 不能从楼贴看出所提供的信息还缺少什么？

**Comment by wamgel** [comment]
@gjbg1989  感谢，好了。

**Comment by wamgel** [comment]
@gjbg1989 大师，我按照这个来了一遍
>结束进程pythonw.exe，先管理权限运行3.7.11版XX-Net目录内disable_ipv6.bat，再enable_ipv6.bat即可正常开启、使用ipv6隧道。

又失败了。。。
> C:\Users\Administrator.WIN-RPL1O0DB2AU>netsh int ipv6 show teredo
Teredo 参数
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
禁用再启用网络

**Comment by wamgel** [comment]
@gjbg1989 照你说的做了，没有变化。。

**Comment by wamgel** [comment]
C:\WINDOWS\system32>netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:2872 ipv4:0 ipv6:2858
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 325
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
检查 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 项目DisabledComponents 值

**Comment by wamgel** [comment]
@gjbg1989    0x0000000ce(206)

**Comment by gjbg1989** [comment]
0x000000ce(206) 是十六进制值为0 ？
![default](https://user-images.githubusercontent.com/13290970/34325358-424dba8c-e8ca-11e7-8b48-da0d0e8a0153.png)

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34325363-6176b544-e8ca-11e7-8199-64bace4442dd.png)

**Comment by gjbg1989** [comment]
修改好注册表，再
结束进程 pythonw.exe，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
禁用再启用网络

**Comment by gjbg1989** [comment]
0x000000ce(206)又会是谁改的呢？系统上的360、管家等国祸？

**Comment by wamgel** [comment]
@gjbg1989 刚刚试过禁用再启用网络没成功。后来又从头来一遍，再重启，终于好了。
谢谢你这么耐心，再出问题我都不好意思问你了:P

**Comment by gjbg1989** [comment]
0x000000ce(206)又会是被谁改的呢？——关键的关键😂

**Comment by wamgel** [comment]
...
