### ISSUE TITLE
兄弟~你这支付有问题.

### ISSUE THREAD

**Issue by psychedelico** [XX-net/XX-Net#9104]
我购买的流量是 1200G 1年的,支付后 变成300G 一个季度的,然后账号还有余额10.5美金....... 你能不能在后台设置为一年1200G的把余额扣了.

![unnamed](https://user-images.githubusercontent.com/346631/34119190-3c6d34b6-e45c-11e7-9d47-308a5fc37c3b.png)

**Comment by xxnet** [comment]
​已经处理，谢谢支持

**Comment by whhxmwhh** [comment]
赞。楼主真哥们。支持xx-net！

**Comment by sun3596209** [comment]
有条件一定要支持xx-net，不过我的paypal怎么老注册不成功
