### ISSUE TITLE
10G流量能不能给了赶紧的

### ISSUE THREAD

**Issue by akakljf115** [XX-net/XX-Net#9110]
速度

**Comment by onplus** [comment]
。。。

**Comment by zanewayne78** [comment]
伸手这么...

**Comment by WLZLCX** [comment]
楼主付费了？

**Comment by wiiii** [comment]
想付费,可惜没有支持palpay的银行卡

**Comment by scljy** [comment]
cnscljy@gmail.com

**Comment by GoodSake** [comment]
10GB X-tunnel流量还没送出啊，哈哈哈！
给钱估计好多人排队。。。

**Comment by caizzoo** [comment]
账号多少，我转点给你

**Comment by akakljf115** [comment]
akakljf115@163.com

在 2017-12-20 12:18:32，"caizzoo" <notifications@github.com> 写道：


账号多少，我转点给你
