### ISSUE TITLE
Gmail顶层图标不显示

### ISSUE THREAD

**Issue by Danielshara** [XX-net/XX-Net#9115]
大家有遇到过这个问题吗?

![gmail](https://user-images.githubusercontent.com/33028673/34160721-11c2b788-e509-11e7-9c23-8314e9529dd3.png)

**Comment by GoodSake** [comment]
我和你不同:
![snap1](https://user-images.githubusercontent.com/19205130/34161012-1a7afefc-e50a-11e7-9339-ed01caac929e.png)

**Comment by Danielshara** [comment]
好吧。。刚切到英文看了一下，还是没图标

**Comment by ShureCool** [comment]
我用SSR也是不显示，默认gfw pac

**Comment by Danielshara** [comment]
Update: 已解决。
点击扩展程序里的SwitchyOmega，会显示有XX个资源未加载，然后添加条件到情景模式
