### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xdg92** [XX-net/XX-Net#9124]
本来IPV6是能用的，但今天翻墙速度有点慢就换了一个服务器试试，就此再也通不了，为何？

**Comment by jinke159** [comment]
贴点东西呀
cmd运行
netsh int teredo show state

**Comment by xdg92** [comment]
我是用7732楼的方法打能IPV6的，没运行过CMD之类的，也没用批处理命令。今天就是手闲的换了一下服务器就再也回不到从前了。

**Comment by jinke159** [comment]
提示：如按照教程设置无效出现其他莫名其妙的问题，建议：

1. 管理员模式运行disable_ipv6.bat。（如是用的组策略模式，请把所有更改过的组策略改成未配置）

2. 删除regedit：计算机\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ 下面的Tcpip6和TCPIP6TUNNEL两个选项。（改动注册表之前请备份）

**3. 在["自动禁用或重新启用 IPv6"](https://support.microsoft.com/zh-cn/help/929852/how-to-disable-ipv6-or-its-components-in-windows)  或其组件下载 在非隧道接口和 IPv6 隧道接口上重新启用 IPv6，运行后重启电脑，然后按照组策略教程再重做一遍。（切记：组策略方法开启IPv6必须指定服务器名称）**

    文章开头提示的：禁用IPv6协议。

**Comment by xdg92** [comment]
谢谢兄台，我试试看能否成功。

**Comment by 308901951** [comment]
退回原来系统状态#8500走一边，如果不行等几分钟，再运行相关.bat，注册表新建32位项目，以前没描述清楚

**Comment by xdg92** [comment]
308901951   ，按你说的走一遍不行，还是让开启IPV6，但还是感谢之前你的办法让我愉快地用了快两个月。

**Comment by xdg92** [comment]
jinke159  ，按你8500#所说的办法组策略还原成未配置状态，然后dis再en成功解决，没改注册表，感谢指导。
