### ISSUE TITLE
公司、家里两套xx-net操作中发生的趣事、及引发的思考

### ISSUE THREAD

**Issue by nly4lov** [XX-net/XX-Net#9130]
1. 以前就发现，在公司翻得好好的，回家、或者切换公司其他的无线局域网，就翻不了
2. 有两个朋友（咱们这里一个，还有一个是QQ上的网友）讲，你弄两个xx啊，目录不同，于是昨晚没事，把xx复制了一份，目录取名为XX-Net-H（Home的意思，原来的就叫XX-Net），复制后的新目录下把data文件夹删除，重新扫
3. 昨天在公司升级了最新的3.9.1，回家后这个版本时而free internet，时而无法连接ipv6，把原来xx目录下data的goodip等复制过来，ip数也是毫无变化，复制ip、导入也不行，导入数为0. 后来干脆换了智能路由前最后一个版本3.8.4，还算稳定，就是扫描很慢，干脆整夜开着让它扫去，
4. 已经deploy过的appid，我有4个，搞了三次也部署不了，后来发现每次卡住、终止部署后，它都会提示去设置里填写这几个id，就照办，然后看诊断信息才发现都已是部署好的。莫非已经部署过的appid，就无须再部署？还是我本机已经部署过的原因？
5. 今早起来一看已经280个ip了（到了公司才这一会就500了），家里是垃圾长宽，公司是电信，莫非长宽扫ip就是慢？
6. 到公司后（电脑今早关机了，到公司重新开机），随手运行xx，惊讶地发现，欢迎界面仍然是3.8.4！才想起原来xx每次运行start.bat后，它会创建新的桌面快捷方式，
7. 6还不是最诡异的，诡异的是，公司的xx（3.9.1及以前的任何版本，在我试验的时候发现）回了家不能用，为啥家里的（3.8.4）到了公司仍然能翻？

**Comment by GoodSake** [comment]
id部署过才能用，不管你部署的，还是你请英国网友部署的，都没关系。

**Comment by gjbg1989** [comment]
😂id部署过就能用，不管是你部署的，还是你请英国网友部署的，都没关系。

**Comment by nly4lov** [comment]
你俩好像都搞错重点啦

**Comment by gjbg1989** [comment]
😂楼主还得学习下：
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more

**Comment by GoodSake** [comment]
两个都搞错重点了。。。都怪你语文太好了，被你的文采弄晕了，哈哈哈！

**Comment by nly4lov** [comment]
@gjbg1989 不明觉厉
@GoodSake 我的重点是说呀，为什么另一个文件夹里没部署，id们居然也可以使用了呢？为什么公司的那个xx在公司能用回家不能，而家里的那个xx在家能用，到了公司也能用？

**Comment by gjbg1989** [comment]
你俩好像都搞错重点啦——从楼上看来就是2个重点，都说了第一个是你的理解有误——id部署过就能用，仅对第二个视而不见而已🤣

**Comment by GoodSake** [comment]
好吧，看到了:

id,部署,配置,可以使用。(没部署:为什么另一个文件夹里没部署。部署和没部署是放在google那的，和你的文件夹没关系)

XX-net,能用,不能用。(在公司能用回家不能用。在家能用，到了公司也能用。这可复杂了，GAE,X-tunnel,直连,前置代理,dns,udp,tcp,http reset....)。

**Comment by nly4lov** [comment]
第一个明白了。第二个太复杂，干脆不鸟了。反正能用就是好家伙。

**Comment by onplus** [comment]
1. 一个appid 服务端一般只需要部署一次
2. 不同网络环境的出国难度是不一样的，搜出的可用ip通用性不足
3. 不同版本的翻墙效果确实有差异，出现问题需要大家及时反馈
4. 创建快捷方式是可以关闭的，以绿色软件运行
