### ISSUE TITLE
xx-net占硬盘达到1g了，可以把之前版本目录删除吗？

### ISSUE THREAD

**Issue by mike0902adf** [XX-net/XX-Net#9136]
![image](https://user-images.githubusercontent.com/34730186/34239100-23d2ed0c-e640-11e7-9877-7dadf38cd1ae.png)

**Comment by GoodSake** [comment]
我肏，姐姐你这太多了呀。。。我觉得都可以删。

**Comment by xxnet** [comment]
​正在开发中。

**Comment by mike0902adf** [comment]
Defaul那个目录也可以删吗？

**Comment by GoodSake** [comment]
就留一个version和[default]吧，其实我觉得[default]也可以删。。。

**Comment by gjbg1989** [comment]
貌似除了 version.txt 内描述的版本，都可以删除

**Comment by Jacobax** [comment]
我都是更新完手动删除旧版本

**Comment by cv0cv0** [comment]
default可以删除，只留最新版本就行。
