### ISSUE TITLE
报告一个局域网代理的问题:[WARNING] launcher.config save user config fail:D:\XX-Net\data\gae_proxy\config.ini AttributeError("'User_config' object has no attribute 'LISTEN_IP'",)

### ISSUE THREAD

**Issue by mtgitnerd** [XX-net/XX-Net#9137]
如题:填写完代理主机，用户名 密码后，日志报的这个警告
Dec 21 12:21:18.178 - [WARNING] launcher.config save user config fail:D:\XX-Net\data\gae_proxy\config.ini AttributeError("'User_config' object has no attribute 'LISTEN_IP'",)

**Comment by xxnet** [comment]
找到问题了，已经修复，下次发布新版带上

**Comment by mtgitnerd** [comment]
X大V5! 大拇哥
