### ISSUE TITLE
捣鼓半天正常了

### ISSUE THREAD

**Issue by xuanbeads** [XX-net/XX-Net#9141]
正常了

**Comment by xuanbeads** [comment]
GAEProxy状态信息
请检查浏览器代理设置。
属性 | 值
-- | --
IPv4 Status | OK
IPv6 Status | OK
IPv4 Number | 0
IPv6 Number | 2595
空闲 | 0
IP延迟 | 299
连接池(帮助) | 新:0 h1:56 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
扫描IP线程数(设置) | 10
屏蔽状态(帮助) | OK


属性 | 值
-- | --
监听代理 | 127.0.0.1:8087
PAC自动代理地址 | http://127.0.0.1:8086/proxy.pac
使用IPv6 | auto
LAN proxy | Disable

**Comment by xuanbeads** [comment]
Dec 21 15:01:53.043 - [DEBUG] ## GAEProxy set keep_running: True

Dec 21 15:01:53.043 - [INFO] ------------------------------------------------------

Dec 21 15:01:53.043 - [INFO] Python Version : 2.7.13

Dec 21 15:01:53.043 - [INFO] OS : Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0

Dec 21 15:01:53.043 - [INFO] Listen Address : 127.0.0.1:8087

Dec 21 15:01:53.043 - [INFO] GAE APPID : g198410142812|g198410142813|g198410142815|g198410142816|g198410142817|g198410142818|g198410142819|s198410142813|s198410142814|s198410142815|s198410142816|s198410142817|s198410142818|s198410142819|spring-nova-832|x19841014281|x198410142811|x198410142814|x198410142813|x198410142815|x198410142816|x198410142817|x198410142818|x198410142819|x19841014282

Dec 21 15:01:53.043 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac

Dec 21 15:01:53.043 - [INFO] ------------------------------------------------------

Dec 21 15:01:53.043 - [DEBUG] Importing CA

Dec 21 15:01:53.043 - [DEBUG] Removing windows CA

Dec 21 15:01:53.063 - [DEBUG] Begin to import Windows CA

Dec 21 15:01:53.153 - [DEBUG] network IPv4 is ok, cost:1062 ms

Dec 21 15:01:53.935 - [DEBUG] create_ssl update ip:2607:f8b0:4009:3d::9 time:615 h2:0

Dec 21 15:01:54.374 - [DEBUG] create_ssl update ip:2607:f8b0:4009:36::7 time:541 h2:0

Dec 21 15:01:54.907 - [DEBUG] create_ssl update ip:2607:f8b0:4009:37::8 time:555 h2:0

Dec 21 15:01:55.778 - [DEBUG] create_ssl update ip:2607:f8b0:4009:3d::b time:2433 h2:0

Dec 21 15:01:55.888 - [DEBUG] create_ssl update ip:2607:f8b0:4017:15::7 time:594 h2:0

Dec 21 15:01:56.048 - [DEBUG] create_ssl update ip:2607:f8b0:4017:12::c time:617 h2:0

Dec 21 15:01:56.821 - [DEBUG] create_ssl update ip:2607:f8b0:4017:15::c time:555 h2:0

Dec 21 15:01:57.105 - [DEBUG] create_ssl update ip:2607:f8b0:4009:2d::b time:552 h2:0

Dec 21 15:01:57.605 - [DEBUG] create_ssl update ip:2607:f8b0:4009:39::c time:1167 h2:0

Dec 21 15:01:57.812 - [DEBUG] create_ssl update ip:2607:f8b0:4009:35::7 time:546 h2:0

Dec 21 15:01:58.054 - [DEBUG] create_ssl update ip:2607:f8b0:401a:25::b time:559 h2:0

Dec 21 15:01:58.606 - [DEBUG] create_ssl update ip:2607:f8b0:401a:3::7 time:571 h2:0

Dec 21 15:01:58.781 - [DEBUG] create_ssl update ip:2607:f8b0:401a:6::8 time:566 h2:0

Dec 21 15:01:59.012 - [DEBUG] create_ssl update ip:2607:f8b0:401a::7 time:558 h2:0

Dec 21 15:01:59.743 - [DEBUG] create_ssl update ip:2607:f8b0:401a:23::8 time:570 h2:0

Dec 21 15:01:59.824 - [DEBUG] create_ssl update ip:2607:f8b0:4009:3a::b time:561 h2:0

Dec 21 15:01:59.964 - [DEBUG] create_ssl update ip:2607:f8b0:401a:26::7 time:562 h2:0

Dec 21 15:02:00.251 - [DEBUG] create_ssl update ip:2607:f8b0:401a:4::a time:572 h2:0

Dec 21 15:02:00.381 - [DEBUG] create_ssl update ip:2607:f8b0:4000:3b::b time:597 h2:0

Dec 21 15:02:00.461 - [DEBUG] create_ssl update ip:2607:f8b0:401a:1::9 time:576 h2:0

Dec 21 15:02:00.571 - [DEBUG] create_ssl update ip:2607:f8b0:4017:30::b time:550 h2:0

Dec 21 15:02:00.697 - [DEBUG] create_ssl update ip:2607:f8b0:4000:38::6 time:565 h2:0

Dec 21 15:02:00.777 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1d::c time:546 h2:0

Dec 21 15:02:00.944 - [DEBUG] create_ssl update ip:2607:f8b0:4000:3c::b time:562 h2:0

Dec 21 15:02:01.026 - [DEBUG] create_ssl update ip:2607:f8b0:4009:2d::a time:565 h2:0

Dec 21 15:02:01.146 - [DEBUG] create_ssl update ip:2607:f8b0:4009:3e::b time:584 h2:0

Dec 21 15:02:01.636 - [DEBUG] network IPv6 is ok, cost:9534 ms

Dec 21 15:02:01.747 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1e::a time:540 h2:0

Dec 21 15:02:01.951 - [DEBUG] create_ssl update ip:2607:f8b0:401d:6::7 time:535 h2:0

Dec 21 15:02:07.094 - [DEBUG] create_ssl update ip:2607:f8b0:401d:2::b time:542 h2:0

Dec 21 15:02:08.003 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::b time:538 h2:0

Dec 21 15:02:08.767 - [INFO] scan_ip add ip:2607:f8b0:401d:6::8 time:532

Dec 21 15:02:10.018 - [INFO] scan_ip add ip:2404:6800:400b:24::c time:921

Dec 21 15:02:10.966 - [INFO] scan_ip add ip:2607:f8b0:4013:5::14 time:5111

Dec 21 15:02:13.896 - [DEBUG] create_ssl update ip:2607:f8b0:401d:2::8 time:528 h2:0

Dec 21 15:02:14.830 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::a time:532 h2:0

Dec 21 15:02:20.766 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::8 time:544 h2:0

Dec 21 15:02:21.768 - [DEBUG] create_ssl update ip:2607:f8b0:4012:8::f time:600 h2:0

Dec 21 15:02:27.779 - [DEBUG] create_ssl update ip:2607:f8b0:4012:a::d time:611 h2:0

Dec 21 15:02:28.719 - [DEBUG] create_ssl update ip:2607:f8b0:401a:22::9 time:559 h2:0

Dec 21 15:02:28.975 - [INFO] scan_ip add ip:2404:6800:400b:18::c time:937

Dec 21 15:02:34.758 - [DEBUG] create_ssl update ip:2607:f8b0:4012:b::f time:600 h2:0

Dec 21 15:02:35.737 - [DEBUG] create_ssl update ip:2607:f8b0:4000:33::8 time:559 h2:0

Dec 21 15:02:36.142 - [INFO] scan_ip add ip:2607:f8b0:400a:3::18 time:1168

Dec 21 15:02:40.321 - [INFO] scan_ip add ip:2404:6800:400c:2::8 time:789

Dec 21 15:02:41.739 - [DEBUG] create_ssl update ip:2607:f8b0:4012:f::10 time:601 h2:0

Dec 21 15:02:42.759 - [DEBUG] create_ssl update ip:2607:f8b0:4012:c::b time:603 h2:0

Dec 21 15:02:48.198 - [INFO] scan_ip add ip:2a00:1450:4005:4::12 time:1365

Dec 21 15:02:48.751 - [DEBUG] create_ssl update ip:2607:f8b0:401a:22::8 time:572 h2:0

Dec 21 15:02:49.857 - [DEBUG] create_ssl update ip:2607:f8b0:4012:8::18 time:614 h2:0

Dec 21 15:02:55.945 - [DEBUG] create_ssl update ip:2607:f8b0:4012:9::8 time:608 h2:0

Dec 21 15:02:56.963 - [DEBUG] create_ssl update ip:2607:f8b0:4012:9::6 time:598 h2:0

Dec 21 15:02:58.590 - [INFO] scan_ip add ip:2a00:1450:400b:3::17 time:742

Dec 21 15:02:58.717 - [INFO] scan_ip add ip:2404:6800:400f:8::7 time:832

Dec 21 15:02:59.374 - [INFO] scan_ip add ip:2a00:1450:400f:8::10 time:1025

Dec 21 15:03:03.020 - [DEBUG] create_ssl update ip:2607:f8b0:4012:b::6 time:608 h2:0

Dec 21 15:03:04.018 - [DEBUG] create_ssl update ip:2607:f8b0:4012:9::17 time:598 h2:0

Dec 21 15:03:10.028 - [DEBUG] create_ssl update ip:2607:f8b0:4012:b::10 time:610 h2:0

Dec 21 15:03:10.558 - [INFO] scan_ip add ip:2404:6800:400b:8::11 time:869

Dec 21 15:03:10.983 - [DEBUG] create_ssl update ip:2607:f8b0:401a:21::8 time:574 h2:0

Dec 21 15:03:20.121 - [DEBUG] connect 2607:f8b0:401e:26::b fail:timeout('timed out',)

Dec 21 15:03:20.121 - [DEBUG] report_connect_fail:2607:f8b0:401e:26::b

Dec 21 15:03:21.157 - [DEBUG] create_ssl update ip:2607:f8b0:4012:f::15 time:595 h2:0

Dec 21 15:03:22.197 - [DEBUG] create_ssl update ip:2607:f8b0:4012:9::16 time:610 h2:0

Dec 21 15:03:28.230 - [DEBUG] create_ssl update ip:2607:f8b0:401a:6::9 time:571 h2:0

Dec 21 15:03:29.226 - [DEBUG] create_ssl update ip:2607:f8b0:4012:d::7 time:597 h2:0

Dec 21 15:03:32.094 - [DEBUG] restore ip:2607:f8b0:401e:26::b

Dec 21 15:03:32.839 - [INFO] scan_ip add ip:2607:f8b0:4016:5::15 time:4522

Dec 21 15:03:34.329 - [INFO] scan_ip add ip:2a00:1450:4005:3::e time:3700

Dec 21 15:03:35.238 - [DEBUG] create_ssl update ip:2607:f8b0:4012:c::10 time:608 h2:0

Dec 21 15:03:36.187 - [DEBUG] create_ssl update ip:2607:f8b0:401a:27::8 time:569 h2:0

Dec 21 15:03:42.132 - [DEBUG] create_ssl update ip:2607:f8b0:4017:c::c time:549 h2:0

Dec 21 15:03:43.172 - [DEBUG] create_ssl update ip:2607:f8b0:4012:d::18 time:601 h2:0

Dec 21 15:03:47.384 - [INFO] scan_ip add ip:2607:f8b0:4009:36::8 time:543

Dec 21 15:03:49.278 - [DEBUG] create_ssl update ip:2607:f8b0:4012:9::14 time:615 h2:0

Dec 21 15:03:49.672 - [INFO] scan_ip add ip:2607:f8b0:4016:1b::b time:3069

Dec 21 15:03:50.299 - [DEBUG] create_ssl update ip:2607:f8b0:4012:d::8 time:616 h2:0

Dec 21 15:03:56.464 - [INFO] scan_ip add ip:2a00:1450:4002:12::15 time:650

Dec 21 15:03:57.058 - [INFO] scan_ip add ip:2607:f8b0:401a:5::b time:565

Dec 21 15:03:59.442 - [DEBUG] connect 2607:f8b0:401d:1c::9 fail:timeout('timed out',)

Dec 21 15:03:59.442 - [DEBUG] report_connect_fail:2607:f8b0:401d:1c::9

Dec 21 15:04:03.363 - [DEBUG] create_ssl update ip:2607:f8b0:401d:6::8 time:529 h2:0

Dec 21 15:04:04.340 - [DEBUG] create_ssl update ip:2607:f8b0:4009:36::8 time:573 h2:0

Dec 21 15:04:07.295 - [DEBUG] create_ssl update ip:2607:f8b0:4004:2c::9 time:2417 h2:0

Dec 21 15:04:08.269 - [DEBUG] create_ssl update ip:2607:f8b0:401a:5::b time:574 h2:0

Dec 21 15:04:09.230 - [DEBUG] create_ssl update ip:2607:f8b0:401e:26::b time:572 h2:0

Dec 21 15:04:10.567 - [INFO] scan_ip add ip:2607:f8b0:400a:4::a time:1226

Dec 21 15:04:10.683 - [DEBUG] restore ip:2607:f8b0:401d:1c::9

Dec 21 15:04:12.020 - [INFO] scan_ip add ip:2404:6800:400b:23::17 time:885

Dec 21 15:04:14.676 - [INFO] scan_ip add ip:2607:f8b0:4016:17::12 time:687

Dec 21 15:04:15.258 - [DEBUG] create_ssl update ip:2607:f8b0:4012:b::16 time:614 h2:0

Dec 21 15:04:16.428 - [INFO] scan_ip add ip:2607:f8b0:400a:1::10 time:500

Dec 21 15:04:18.360 - [INFO] scan_ip add ip:2607:f8b0:4016:17::f time:3908

Dec 21 15:04:18.592 - [INFO] scan_ip add ip:2a00:1450:4005:3::6 time:1195

Dec 21 15:04:19.370 - [DEBUG] connect 2607:f8b0:4007:1b::b fail:timeout('timed out',)

Dec 21 15:04:19.370 - [DEBUG] report_connect_fail:2607:f8b0:4007:1b::b

Dec 21 15:04:20.234 - [DEBUG] create_ssl update ip:2607:f8b0:400a:1::10 time:495 h2:0

Dec 21 15:04:21.146 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1c::9 time:540 h2:0

Dec 21 15:04:27.527 - [INFO] scan_ip add ip:2a00:1450:4011:33::10 time:1512

Dec 21 15:04:30.258 - [DEBUG] connect 2607:f8b0:4012:a::11 fail:timeout('timed out',)

Dec 21 15:04:30.258 - [DEBUG] report_connect_fail:2607:f8b0:4012:a::11

Dec 21 15:04:34.378 - [DEBUG] connect 2607:f8b0:4012:8::7 fail:timeout('timed out',)

Dec 21 15:04:34.380 - [DEBUG] report_connect_fail:2607:f8b0:4012:8::7

Dec 21 15:04:34.484 - [DEBUG] ip:2607:f8b0:4007:1b::b real fail

Dec 21 15:04:35.435 - [DEBUG] create_ssl update ip:2607:f8b0:4012:c::6 time:605 h2:0

Dec 21 15:04:39.537 - [DEBUG] connect 2607:f8b0:4009:2f::11 fail:timeout('timed out',)

Dec 21 15:04:39.537 - [DEBUG] report_connect_fail:2607:f8b0:4009:2f::11

Dec 21 15:04:41.653 - [DEBUG] restore ip:2607:f8b0:4012:a::11

Dec 21 15:04:42.000 - [DEBUG] create_ssl update ip:2607:f8b0:4016:5::c time:1711 h2:0

Dec 21 15:04:42.707 - [INFO] scan_ip add ip:2a00:1450:4011:2f::19 time:1111

Dec 21 15:04:43.341 - [DEBUG] create_ssl update ip:2607:f8b0:4012:a::12 time:605 h2:0

Dec 21 15:04:44.346 - [DEBUG] create_ssl update ip:2607:f8b0:4012:a::11 time:605 h2:0

Dec 21 15:04:45.737 - [DEBUG] restore ip:2607:f8b0:4012:8::7

Dec 21 15:04:50.687 - [DEBUG] create_ssl update ip:2607:f8b0:4012:9::10 time:608 h2:0

Dec 21 15:04:54.654 - [DEBUG] ip:2607:f8b0:4009:2f::11 real fail

Dec 21 15:04:54.673 - [INFO] scan_ip add ip:2607:f8b0:4016:6::a time:2246

Dec 21 15:04:54.792 - [DEBUG] connect 2607:f8b0:401d:7::17 fail:timeout('timed out',)

Dec 21 15:04:54.793 - [DEBUG] report_connect_fail:2607:f8b0:401d:7::17

Dec 21 15:04:55.826 - [DEBUG] create_ssl update ip:2607:f8b0:4012:8::7 time:608 h2:0

Dec 21 15:04:59.983 - [DEBUG] connect 2607:f8b0:400f:2::c fail:timeout('timed out',)

Dec 21 15:04:59.983 - [DEBUG] report_connect_fail:2607:f8b0:40

**Comment by xuanbeads** [comment]
请问怎么回事？？？？

**Comment by GoodSake** [comment]
您露id了。。。。

**Comment by kelvin219** [comment]
咋弄好的？

**Comment by xuanbeads** [comment]
卸了重装。好像腾讯管家误删了什么。
