### ISSUE TITLE
XX-Net影响了微博图片加载？

### ISSUE THREAD

**Issue by superminian** [XX-net/XX-Net#9164]
最近一段时间，微博中很多图片无法加载，今天试着关掉XX-Net和Proxy SwitchyOmega扩展程序，马上就正常了。用无代理的IE打开微博也能正常显示图片。
XX-Net版本3.9.2。浏览器chrome版本63.0.3239.108。Proxy SwitchyOmega用自动切换模式。请高手支招。
![-1](https://user-images.githubusercontent.com/34767503/34293581-303c0a82-e740-11e7-99c4-d31460f520d9.jpg)

**Comment by AllahSaladin** [comment]
Omega里添加条件试试   *.weibo.com  直接链接

**Comment by onplus** [comment]
右键图片--检查此元素使用的代理

**Comment by Emphasia** [comment]
SwitchyOmega图标单击会有统计无法加载的资源，找到比如微博新浪域名直接设为直连确定应该就好了。

**Comment by superminian** [comment]
谢谢楼上各位
