### ISSUE TITLE
迅雷确实会影响xx的使用

### ISSUE THREAD

**Issue by ShadowEmbrace** [XX-net/XX-Net#9171]
之前看到过一个说迅雷等bt软件会影响xx使用的帖子（x大之后），刚刚确实发现开着迅雷会影响teredo联结，关了迅雷重启xx马上就变managed，开着迅雷重启好几遍无济于事

**Comment by gustav183** [comment]
是不是因为迅雷链接DHT网络加速下载的关系？那bit彗星应该也影响吧？

**Comment by ShadowEmbrace** [comment]
有可能，那能不大幅影响速度的解决么？
