### ISSUE TITLE
折腾疯了，重装之后可以用，不知道更新了什么有不能用了，总是显示“你可以试试 开启IPv6隧道 或者使用 X-Tunnel”求解答！

### ISSUE THREAD

**Issue by sxfsirg** [XX-net/XX-Net#9172]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by hitrust** [comment]
说的很明白了，开启IPv6隧道或者使用 X-Tunnel，怎么操作看教程。https://github.com/XX-net/XX-Net/wiki

**Comment by gjbg1989** [comment]
use-ipv6: auto 改为只用 ipv6
贴运行 netsh int ipv6 show teredo 结果

**Comment by zhangyinyuan** [comment]
![default](https://user-images.githubusercontent.com/17852036/34317000-450a1892-e7df-11e7-8f29-d49d26d98a49.png)

**Comment by gjbg1989** [comment]
禁用再启用网络

**Comment by gjbg1989** [comment]
使用ping超时的微软服务器或许更稳定！(win7除外)
管理权限运行 netsh int ipv6 set teredo enterpriseclient default

**Comment by sxfsirg** [comment]
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (secondary server)
客户端类型              : teredo client
网络                    : managed

PS C:\Windows\system32>
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
状态 : probe (secondary server)——结束进程 pythonw.exe，禁用再启用网络

**Comment by sxfsirg** [comment]
ip也固定了，也按照教程https://github.com/XX-net/XX-Net/wiki/teredo开启了ipv6，use-ipv6: auto 改为只用 ipv6也做了，就是不行，上面是诊断，麻烦各位大神给指点一下，望详细点，多谢多谢!

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by sxfsirg** [comment]
@gjbg1989 试过了还是那样啊，以前一直不能用，重装了win10就可以用了，第二天他自己升级了一些多谢，现在就不行了，你上面说的这些我都做过了，还是不行

**Comment by sxfsirg** [comment]
@hitrust 按照教程的做了，还是不能上网

**Comment by gjbg1989** [comment]
确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。

**Comment by gjbg1989** [comment]
ip也固定了——怎做的？

**Comment by sxfsirg** [comment]
@gjbg1989  
PS C:\Windows\system32> netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by sxfsirg** [comment]
SSID:	HUAWEI-SSS
协议:	802.11ac
安全类型:	WPA2-个人
网络频带:	5 GHz
网络通道:	149
IPv4 地址:	192.168.3.15
IPv4 DNS 服务器:	192.168.3.1
制造商:	Intel Corporation
描述:	Intel(R) Dual Band Wireless-AC 7265

**Comment by sxfsirg** [comment]
协议:	802.11ac
安全类型:	WPA2-个人
网络频带:	5 GHz
网络通道:	
IPv4 地址:	192.168.3.15
IPv4 DNS 服务器:	192.168.3.1
制造商:	Intel Corporation
描述:	Intel(R) Dual Band Wireless-AC 7265
驱动程序版本:	19.50.1.6
物理地址(MAC):	34-02-86-9C-2D-27

**Comment by sxfsirg** [comment]
SSID:	
协议:	802.11ac
安全类型:	WPA2-个人
网络频带:	5 GHz
网络通道:	149
IPv4 地址:	192.168.3.15
IPv4 DNS 服务器:	192.168.3.1
制造商:	Intel Corporation

**Comment by gjbg1989** [comment]
貌似在路由器固定电脑 IP 即可

**Comment by sxfsirg** [comment]
@gjbg1989 路由器DHCP已经关闭。现在已经是固定IP了，还是不行。


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
路由器DHCP已经关闭——为毛？在路由器固定电脑 IP 需如此操作？

**Comment by sxfsirg** [comment]
@gjbg1989 查了好多教程，现在我也糊涂了，反正现在就是连不上，就是不知道哪里不对
