### ISSUE TITLE
怎么取消自动IPv6

### ISSUE THREAD

**Issue by malt2008** [XX-net/XX-Net#9188]
使用IPv6 | auto
-- | --

这个怎么取消

**Comment by Emphasia** [comment]
http://localhost:8085/?module=gae_proxy&menu=advanced
![20171223233249](https://user-images.githubusercontent.com/8478234/34320634-9bd8e298-e839-11e7-8c1d-12db85327046.png)

**Comment by malt2008** [comment]
感谢，看了半天配置说明没找到。
