### ISSUE TITLE
发现个问题，good_ip.txt里的延迟都在1500以上，一直用自动升级的最新测试版

### ISSUE THREAD

**Issue by jeff201314** [XX-net/XX-Net#920]
比如，扫描日志里：
Sep 02 01:21:24 - [INFO] Add 61.91.18.8 time:301 CN:*.googlevideo.com type:gws
good_ip.txt 现在里面看是：
61.91.18.89 google.com gws 1627
不知道为什么数值变化这么大，而且所有以前扫描出来的近3000 IP 数都变成1500以上。

**Comment by wenliyang** [comment]
换回 2.0.5 版本

**Comment by jeff201314** [comment]
2.0.5 版本可用，2.2.0 版本果然有问题啊，每次启动时有连接过会就断了。
