### ISSUE TITLE
【已解决】求助，PC运行XXNET给局域网设备做代理，安卓手机可以上谷歌和看youtube，ios11能上谷歌，YouTube也能打开，就是无法播放

### ISSUE THREAD

**Issue by heckles** [XX-net/XX-Net#9200]
@xxnet 

如题

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.9.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4937 ipv4:0 ipv6:4333
ipv4-status: OK
ipv6-status: OK
connected-link: new:3 used:0
worker: h1:114 h2:2
scan-ip-thread-num: 10
ip-quality: 269
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by 2378** [comment]
证书问题吗？
ios用的p12
这事得问X大

**Comment by heckles** [comment]
如果是证书问题，不会tumblr和google都能正常访问啊

**Comment by 2378** [comment]
我了解也不深
只是脑子里冒出若干定义 仅当抛砖引玉
比如： PKI 块密码 流密码 p12格式

**Comment by 2378** [comment]
这帖子有帮助
不知你是用app看油管 还是wb看
#3349

**Comment by heckles** [comment]
就是那样设置的，我能上其它被墙的网站，youtube也能上，只是点开视频之后显示播放错误

**Comment by 2378** [comment]
鬼知道googlevideo用的什么黑科技 /play story

**Comment by chendaihang** [comment]
pac模式识别的是域名，ip地址没办法 试试全局模式

**Comment by heckles** [comment]
pc端改成全局代理，ios还是提示播放地址失效，正在跳转
问题是播放进度条都显示开始缓存了，可是就是无法播放

**Comment by gjbg1989** [comment]
此时，pc 是点下屏幕中央或暂停再正常播放的😂

**Comment by chendaihang** [comment]
@heckles  你改pc没用啊 pc全局对pc生效，你手机上改一下改为ip:8087这个代理，不要用自动的ip:8086/proxy.pac

**Comment by heckles** [comment]
@chendaihang
拜托，手机上代理，自动和手动都试过，都不行好吧

**Comment by XndroidDev** [comment]
@heckles  
可能是因为XX-Net 的br编码问题,  你可以试试将XX-Net版本换到3.8.5 及以下版本,  或换用firefox, chrome 浏览器
https://github.com/XX-net/XX-Net/issues/8852

**Comment by liamhui** [comment]
感谢各位。

**Comment by fretyvi** [comment]
IOS11中（其实IOS10就有了）还要在设置-通用-关于本机-证书信任设置 里面吧XX设置为信任。之前在IPV4时候，我INS APP可以访问，现在就他不得，但是打开网页版又得。很纠结

**Comment by GoodSake** [comment]
mac,iso...太高级的东西玩翻墙这类黑科技看着都累。。有没有

**Comment by heckles** [comment]
@XndroidDev @fretyvi
果然是证书信任设置的问题

**Comment by sgricky** [comment]
感谢分享。
现在我也能在有XX-Net的环境中科学上网了~~~
