### ISSUE TITLE
送xx-net流量了~先到先得~~10个~~

### ISSUE THREAD

**Issue by hsrrtx** [XX-net/XX-Net#9205]
买了一年的，分到两个账号，还是感觉完全用不了~~
先送一点吧，每人2G，一共10位，留账号~~
留言超过10位就当没看见了~~
见谅~~
如果GAE能翻墙的话，就让给他人吧~~
流量明天11月到期~~

**Comment by zehuali90529** [comment]
734036044@qq.com

谢楼主

**Comment by YorkMoon** [comment]
125471022@qq.com

谢谢楼主

**Comment by hbsxwhb** [comment]
65122799@qq.com

thank you

**Comment by waylenz** [comment]
676839770@qq.com
谢谢楼主

**Comment by gubu000** [comment]
mawuxiaoqu@126.com 谢lz

**Comment by alexbyrant** [comment]
kobebyrant236@gmail.com
感激不尽

**Comment by iamaccount** [comment]
910800379@qq.com
谢谢

**Comment by hsrrtx** [comment]
125471022@qq.com 不存在。。。。。。

**Comment by hsrrtx** [comment]
676839770@qq.com 不存在。。。

**Comment by hsrrtx** [comment]
910800379@qq.com 不存在。。。

**Comment by hsrrtx** [comment]
看来没用过x-tunnel吧~~

**Comment by hsrrtx** [comment]
七个里面三个不存在，其他四个都转好了~~

**Comment by iamaccount** [comment]
16409750@qq.com
是这个

**Comment by hsrrtx** [comment]
5个好了~~

**Comment by iamaccount** [comment]
已收到，thx

**Comment by waylenz** [comment]
zwrmail@163.com
用这个吧，谢谢

**Comment by 935352** [comment]
935352@qq.com 谢谢

**Comment by nmb2b** [comment]
qq2649767010@gmail.com谢谢

**Comment by XLX** [comment]
来凑个热闹
xionglinxin@gmail.com

不过话说现在不是测试阶段自动赠送流量的么

**Comment by Vicue** [comment]
xzy9681@163.com 谢谢. 虽然需求不大, 主要用来登陆steam和一些游戏. 2G应该能用很久了

**Comment by hsrrtx** [comment]
先封贴了~~

**Comment by hsrrtx** [comment]
zwrmail@163.com也不存在。。。。。。
都转好了，后续不要贴了~~~~
waylenz， 你弄好了在发我吧~~

**Comment by hsrrtx** [comment]
看网页的，感觉完全用不了很多~~ 
一年1200G完全用不了的~~
以后不如集资买流量好了~~
每人几块钱，足够用一年了~~
15刀，100rmb都不到，1200G，20人的话，每人60G，足够用很久了~~

**Comment by waylenz** [comment]
![image](https://user-images.githubusercontent.com/19546561/34333100-f8bf2202-e973-11e7-8d90-9bfa06741898.png)
邮箱是对的啊

**Comment by hsrrtx** [comment]
X-TUNNEL 是要注册的~ 可以看下xx-net 说明~~

**Comment by waylenz** [comment]
多谢指导，x-tunnel现在注册了，邮箱zwrmail@163.com
