### ISSUE TITLE
忧虑国产软件充当卧底的话应该怎么做比较好？

### ISSUE THREAD

**Issue by longjmp** [XX-net/XX-Net#9218]
个人认为 应该采用虚拟机跑国产（以及其他可能的卧底）软件的办法 建议采用Hyper-V虚拟机 因为它可以用动态分配内存的方式 相比vbox更适合内存少的（8G内存及以下）电脑

**Comment by GoodSake** [comment]
是啊，万不得以必须用，那就在虚拟机里。

**Comment by hyzaoia** [comment]
像我win10的话，国产应用只用UWP）

**Comment by wooowooo** [comment]
有种东西叫沙箱，比如[sandboxie](https://zh.wikipedia.org/wiki/Sandboxie)。我没用过
