### ISSUE TITLE
每次关机重开后都要从新配置IPV6

### ISSUE THREAD

**Issue by NOoNE7** [XX-net/XX-Net#9219]
有没有办法解决这个问题呢

**Comment by NOoNE7** [comment]
![Uploading 捕获.JPG…]()

**Comment by NOoNE7** [comment]
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

**Comment by GoodSake** [comment]
试试禁用后再启动网卡。

**Comment by NOoNE7** [comment]
试了，没用。。。

**Comment by GoodSake** [comment]
那就换teredo服务器，估计你那的gfw把win1710干扰得无法访问了。

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by gjbg1989** [comment]
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。

**Comment by NOoNE7** [comment]
都试了，还是不行。。。

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by NOoNE7** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:566 ipv4:0 ipv6:253
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 421
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by NOoNE7** [comment]
类型                    : enterpriseclient
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by NOoNE7** [comment]
还是上传不了图片

**Comment by gjbg1989** [comment]
use-ipv6: auto 改为只用 ipv6
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34375272-98eeeaf2-eb20-11e7-8c53-12e936bf530e.png)
都试了，还是不行——就是不行，最好也得如此。。。

**Comment by NOoNE7** [comment]
刚才又重新设置之后还是尚未建立连接。也下载了那个tertdo.bat选择了延迟最低的服务器，还是不行，但是我发现在开启另一个代理VPN后XXNET恢复了正常，再关闭VPNXXNET有显示尚未建立连接

**Comment by NOoNE7** [comment]
IPv6 Status 显示的是Fail，但是上面显示XX-Net 3.8.5，一切正常，你可以访问真正的互联网了。

**Comment by gjbg1989** [comment]
😱VPN与XXNET同时用？
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by gjbg1989** [comment]
IPv6 Status 显示的是Fail——貌似与teredo服务器失联

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/8961 或许有助稳定？

**Comment by NOoNE7** [comment]
感觉这个电脑快被我玩坏了，只开启VPN，CHROME无法打开GOOGLE并显示代理错误，再开启XXNET后chrome才可以连接外网

**Comment by gjbg1989** [comment]
😱
https://github.com/XX-net/XX-Net/wiki/GoAgent-Intranet-proxy

**Comment by gjbg1989** [comment]
开启VPN，CHROME代理插件貌似采用“系统代理”？

**Comment by gjbg1989** [comment]
感觉这个电脑快被我玩坏了——不至于吧，貌似是代理的设置或选用没匹配？

**Comment by NOoNE7** [comment]
是用的Proxy SwitchyOmega这个插件，我现在已经乱了。。。：）

**Comment by gjbg1989** [comment]
浏览器设置 #8687
