### ISSUE TITLE
Win10尚未建立连接

### ISSUE THREAD

**Issue by lizzliz** [XX-net/XX-Net#9222]
前几天还好好的，突然就尚未建立连接了。
而且看Teredo的参数是qualified，但是在ipv6的测试网站上都是没有检测到ipv6.

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.9.0
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:2 ipv6:4349
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:59 h2:0
scan-ip-thread-num: 10
ip-quality: 307
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy) 
服务器名称              : win10.ipv6.microsoft.com (Group Policy) 
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo host-specific relay
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 192.168.1.223:51114

**Comment by whiliang** [comment]
WIN10，貌似突然就好了呢，just now

**Comment by gjbg1989** [comment]
Appids_Not_Exist: true——有错误的Appid
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。

**Comment by lizzliz** [comment]
感觉不是appid的问题，因为我把电脑拿到学校连校园网就能上（校园网自带ipv6）。不明白自己的网为什么开启不了ipv6。


| |
tjlqq0117
|
|
邮箱：tjlqq0117@163.com
|

签名由 网易邮箱大师 定制

在2017年12月26日 14:51，gjbg1989 写道：

Appids_Not_Exist: true——有错误的Appid
多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或禁用再启用网络，或机器重启。

**Comment by gjbg1989** [comment]
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by lizzliz** [comment]
ipv6自动转换那个方法试过了…也失败了。

**Comment by gjbg1989** [comment]
确保系统服务IP Helper 为自动并已启动，结束进程 pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6
#8620 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by lizzliz** [comment]
Anyway，发现是因为之前一直用disable ipv6和 enable ipv6的bat导致的无法连接。总之谢谢@gjbg1989了～
