### ISSUE TITLE
请问“以绿色软件运行”的作用是什么？

### ISSUE THREAD

**Issue by imldf** [XX-net/XX-Net#9225]
我看到wiki有一个说明，看上去不是很懂，所以想问一问大家。
https://github.com/XX-net/XX-Net/wiki/%E4%BB%A5%E7%BB%BF%E8%89%B2%E8%BD%AF%E4%BB%B6%E8%BF%90%E8%A1%8C

**以绿色软件方式运行，不主动修改系统，不导入证书，不创建快捷方式** 区别是什么?

前面也看到有的人说 使用免费版的GAE 居然可以看4K YouTube视频，请问为什么会有这样的差距，我这里顶多只能流畅看480P的视频，是不是在配置上有差别？

**Comment by qwertccc** [comment]
我觉得对于你来说，就不要做“以绿色软件运行”。

你第二个疑惑，配置可能会有关系，但是关系我感觉不大。我感觉主要是线路（IP）的关系。

你可以：
1、试着调大一些扫描线程
2、长时间运行程序
目的在于多积攒一些好用的IP出来

**Comment by gjbg1989** [comment]
点击 http://127.0.0.1:8085/?module=launcher&menu=config 以绿色软件运行(帮助)

**Comment by imldf** [comment]
@qwertccc  为什么对于我来说就不能呢？我只是想弄清楚事情的原理，请不要说一些没用的。

**Comment by imldf** [comment]
@gjbg1989 那个文档我看了，就是想弄懂这个功能的原理。

**Comment by gjbg1989** [comment]
以非绿色软件运行——XX-Net默认在启动时会自动导入证书到系统，在每次升级、移动软件位置后会自动在桌面创建快捷方式。
以绿色软件方式运行——不主动修改系统，不导入证书，不创建快捷方式。
😂不需要弄懂这个功能的原理，只需要弄懂这个功能的作用

**Comment by gjbg1989** [comment]
前面也看到有的人说 使用免费版的GAE 居然可以看4K YouTube视频——TA 是谁？能写出天书代码的、否认是程序员的神😱

**Comment by imldf** [comment]
@gjbg1989 能看4k视频那个就是在这些问题回答的时候看到的，一下找不到了

**Comment by imldf** [comment]
@gjbg1989   我就是想了解清楚，以绿色软件运行   这个功能打开和关闭后有什么区别。
比如打开  会怎么样
关闭  会怎么样   

而不是 不主动修改系统，不导入证书，不创建快捷方式  和 修改系统、导入证书、创建快捷方式 
这两个有差别吗   还是说不管怎么选择  都能正常使用

**Comment by gjbg1989** [comment]
😱怀疑啥，自己动手试试。。。
https://github.com/XX-net/XX-Net/issues/9221#issuecomment-353932936

**Comment by imldf** [comment]
@gjbg1989 就是想问问有没有人试过啊，我怕自己试出问题可能浪费时间，毕竟现在能正常480p也不错啊

**Comment by imldf** [comment]
@gjbg1989 最近想到一个问题，如果github能在每个项目里有一个即时聊天功能的话应该很受欢迎，超telegram都不成问题。

**Comment by hyzaoia** [comment]
主动修改系统：大概是注册表相关内容
导入证书：gjbg1989已经解释的非常清楚了
创建快捷方式：正如描述，在桌面上创建的那个XX-Net图标
这些设置在某些方面有影响，但正常的家用或者公司网络你开不开都无所谓，对于软件本身并没有什么大的区别
如果这样你还是不能懂，那建议自行~~baidu~~ google相关内容
关于那个流畅度，跟这个设置是完全没有关系的。人家4K只是因为人家的IP质量好。。。多开着XX-Net看能不能扫到好IP吧。
