### ISSUE TITLE
Ubuntu16.04下IPv6 Status Fail求解

### ISSUE THREAD

**Issue by whiliang** [XX-net/XX-Net#9226]
Ubuntu16.04下IPv6 Status Fail，目前已经安装了miredo,
运行命令　　`sudo systemctl status miredo.service`
结果： ` miredo.service - Teredo IPv6 tunneling
   Loaded: loaded (/lib/systemd/system/miredo.service; enabled; vendor preset: e
   Active: active (running) since 二 2017-12-26 16:49:34 CST; 17min ago
  Process: 2573 ExecStartPre=/usr/sbin/miredo-checkconf -f /etc/miredo/miredo.co
 Main PID: 2577 (miredo)
   CGroup: /system.slice/miredo.service
           ├─2577 /usr/sbin/miredo -f
           ├─2579 /usr/sbin/miredo -f
           └─2580 /usr/lib/x86_64-linux-gnu/miredo/miredo-privproc 4

12月 26 16:49:34 whiliangRomandy systemd[1]: Starting Teredo IPv6 tunneling...
12月 26 16:49:34 whiliangRomandy systemd[1]: Started Teredo IPv6 tunneling.
12月 26 16:49:34 whiliangRomandy miredo[2577]: miredo[2577]: 启动中...
12月 26 16:49:34 whiliangRomandy miredo[2577]: 启动中...
12月 26 16:49:34 whiliangRomandy miredo[2577]: miredo[2579]: 新 Teredo 地址/MTU
12月 26 16:49:34 whiliangRomandy miredo[2577]: miredo[2579]: Teredo 虚假隧道已启
12月 26 16:49:34 whiliangRomandy miredo[2579]: 新 Teredo 地址/MTU
12月 26 16:49:34 whiliangRomandy miredo[2577]: miredo[2579]:  (地址：2001:0:53aa
12月 26 16:49:34 whiliangRomandy miredo[2579]: Teredo 虚假隧道已启动
12月 26 16:49:34 whiliangRomandy miredo[2579]:  (地址：2001:0:53aa:64c:28a4:ea23

目测通道已经ok了呢，为何还提示：你可以试试 开启IPv6隧道 或者使用 X-Tunnel ??

**Comment by jinke159** [comment]
ipv6-test.com测试一下是不是真的开了

**Comment by 2378** [comment]
ipv6-status: Fail
建议从miredo方面找问题
也许有干扰
