### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by hansen-xx** [XX-net/XX-Net#9243]
* 简单描述遇到的问题：
上周开始xx-net工作不正常，提示请检查浏览器代理设置，请大神帮忙分析一下，谢谢！

* 做过哪些尝试：
1、升级xx-net稳定版，及最新的3.9.2，无法解决
2、ipv6 teredo 目前正常，ping -6 2001:470:1:18::125 能通
3、多次重启xx-net，服务器，浏览器，问题仍然存在。

* 请贴出对应模块的状态页
XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4454 ipv4:0 ipv6:3106
ipv4-status: OK
ipv6-status: OK
connected-link: new:7 used:0
worker: h1:21 h2:0
scan-ip-thread-num: 200
ip-quality: 252
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 请贴出相关的日志
Dec 28 09:26:49.494 - [DEBUG] ## GAEProxy set keep_running: True

Dec 28 09:26:49.495 - [INFO] ------------------------------------------------------

Dec 28 09:26:49.495 - [INFO] Python Version : 2.7.13

Dec 28 09:26:49.495 - [INFO] OS : Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

Dec 28 09:26:49.495 - [INFO] Listen Address : 127.0.0.1:8087

Dec 28 09:26:49.495 - [INFO] GAE APPID : hansen-11|hansen-01|hansen-02|hansen-03|hansen-04|hansen-05|hansen-06|hansen-07|hansen-08|hansen-09|hansen-10

Dec 28 09:26:49.495 - [INFO] ------------------------------------------------------

Dec 28 09:26:49.497 - [DEBUG] Importing CA

Dec 28 09:26:49.497 - [DEBUG] Removing windows CA

Dec 28 09:26:49.511 - [DEBUG] Begin to import Windows CA

Dec 28 09:26:49.571 - [DEBUG] network IPv4 is ok, cost:1379 ms

Dec 28 09:26:50.547 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1d::a time:421 h2:0

Dec 28 09:26:50.608 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1c::9 time:430 h2:0

Dec 28 09:26:50.954 - [INFO] server 127.0.0.1:8087 started.

Dec 28 09:26:50.998 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1e::c time:417 h2:0

Dec 28 09:26:51.455 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1f::8 time:413 h2:0

Dec 28 09:26:51.898 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1e::7 time:414 h2:0

Dec 28 09:26:52.378 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::a time:417 h2:0

Dec 28 09:26:52.403 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1e::8 time:421 h2:0

Dec 28 09:26:52.532 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1f::a time:429 h2:0

Dec 28 09:26:53.289 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::9 time:420 h2:0

Dec 28 09:26:53.403 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1f::9 time:415 h2:0

Dec 28 09:26:53.809 - [DEBUG] create_ssl update ip:2607:f8b0:401d::9 time:417 h2:0

Dec 28 09:26:53.911 - [DEBUG] create_ssl update ip:2607:f8b0:401d::c time:425 h2:0

Dec 28 09:26:54.196 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1c::a time:415 h2:0

Dec 28 09:26:54.311 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1f::b time:415 h2:0

Dec 28 09:26:54.406 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::8 time:417 h2:0

Dec 28 09:26:54.453 - [DEBUG] create_ssl update ip:2607:f8b0:401d:2::c time:425 h2:0

Dec 28 09:26:54.458 - [DEBUG] create_ssl update ip:2607:f8b0:401d:6::b time:430 h2:0

Dec 28 09:26:54.458 - [DEBUG] create_ssl update ip:2607:f8b0:401d::b time:430 h2:0

Dec 28 09:26:54.912 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1d::9 time:421 h2:0

Dec 28 09:26:55.127 - [DEBUG] create_ssl update ip:2607:f8b0:401d:2::8 time:432 h2:0

Dec 28 09:26:55.359 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::c time:450 h2:0

Dec 28 09:26:55.776 - [DEBUG] create_ssl update ip:2607:f8b0:401d::8 time:417 h2:0

Dec 28 09:26:55.870 - [DEBUG] create_ssl update ip:2607:f8b0:401d:6::8 time:420 h2:0

Dec 28 09:26:56.084 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1c::7 time:433 h2:0

Dec 28 09:26:56.236 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::b time:427 h2:0

Dec 28 09:26:56.317 - [DEBUG] create_ssl update ip:2607:f8b0:401d:4::7 time:416 h2:0

Dec 28 09:26:56.386 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1c::c time:434 h2:0

Dec 28 09:26:56.387 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1d::c time:425 h2:0

Dec 28 09:26:56.387 - [DEBUG] create_ssl update ip:2607:f8b0:401d:2::a time:430 h2:0

Dec 28 09:26:56.845 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1d::b time:437 h2:0

Dec 28 09:26:59.223 - [DEBUG] network IPv6 is ok, cost:11031 ms

Dec 28 09:27:04.429 - [DEBUG] create_ssl update ip:2607:f8b0:401d::a time:414 h2:

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果
运行此bat可观察变化过程。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by Monarch1995** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:1 ipv6:5190
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:30 h2:0
scan-ip-thread-num: 10
ip-quality: 301
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Monarch1995** [comment]
我也是这个问题，怎么解决啊

**Comment by hansen-xx** [comment]
@gjbg1989 
[c:\~]$ netsh int ipv6 show teredo
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.124.11:50723
外部 NAT 映射    : 218.206.231.154:19680
-------------------------------------------------


C:\Windows\system32>ping 127.0.0.1  1>null

C:\Windows\system32>goto loop

C:\Windows\system32>netsh int teredo show stat
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 是，PortPreserving: 否
本地映射           : 192.168.124.11:50723
外部 NAT 映射    : 218.206.231.154:19680

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。

**Comment by hansen-xx** [comment]
@gjbg1989  os 8.1 已经是这个参数了，但是不行

**Comment by gjbg1989** [comment]
贴XX-Net诊断信息

**Comment by ashley1226** [comment]
WIN 10的话试试把防火墙都关掉，包括防火墙设置里面的东西也完全不用。

**Comment by hansen-xx** [comment]
**----问题已找到，各位可以试一下-----------**
@gjbg1989  
ca证书导入有问题，导致ca_state: Fail。可能原因是某些服务没有启动导致证书无法导入，现象是在手动导入确定后一直转圈。我个人电脑是由于服务“HDZB Comm Service 64 For V2.0”禁用导致（银行类服务），使用win+R  运行services.msc后启动HDZB相关服务后，导入正常，使用xx-net全局通过智能路由代理，正常！
