### ISSUE TITLE
如何设置智能路由的监听地址？

### ISSUE THREAD

**Issue by zegzhi** [XX-net/XX-Net#9252]
之前的PAC可以使用`data/gae_proxy/manual.ini`文件来配置。
现在的8086端口改成了智能路由，而且默认的地址为`127.0.0.1:8086`，怎么修改为`0.0.0.0:8086`？

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/blob/master/code/default/smart_router/local/__init__.py

**Comment by asd1219** [comment]
同问如何设置局域网监听
楼上的那个改了没用

**Comment by asd1219** [comment]
知道了，改这个
/code/default/smart_router/local/__init__.py
62行    config.set_var("proxy_bind_ip", "127.0.0.1")
老规矩，127.0.0.1 改成 0.0.0.0
