### ISSUE TITLE
XX-Net 2.05 MAC 10.10.5上始终报错端口在使用，同时无法访问8085

### ISSUE THREAD

**Issue by holdonyb** [XX-net/XX-Net#927]
刚刚重启过一次依然报错，之后就是一直在搜索IP
同时打开http://127.0.0.1:8085/ 打不开，我不知道是不是因为端口没有被打开？

错误信息：
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/peijie/XX-Net-2.0.5/gae_proxy/start.py", line 18, in main
    client.main()
  File "/Users/peijie/XX-Net-2.0.5/gae_proxy/local/proxy.py", line 235, in main
    proxy_daemon = LocalProxyServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use

Sep  4 21:04:14 - [DEBUG] get ip:150.100.16.11 t:208
Sep  4 21:04:14 - [DEBUG] get ip:2607:f8b0:4000:800::1002 t:300
Sep  4 21:04:14 - [DEBUG] create_ssl 2607:f8b0:4000:800::1002 fail:[Errno 65] No route to host cost:0 h:0
Sep  4 21:04:14 - [DEBUG] create_ssl update ip:150.100.16.11 time:213
Sep  4 21:04:15 - [DEBUG] get ip:2607:f8b0:4000:803::100f t:300
Sep  4 21:04:15 - [DEBUG] create_ssl 2607:f8b0:4000:803::100f fail:[Errno 65] No route to host cost:0 h:0
Sep  4 21:04:15 - [DEBUG] report_connect_fail network fail
Sep  4 21:04:15 - [DEBUG] get ip:2607:f8b0:4007:803::1008 t:300
Sep  4 21:04:15 - [DEBUG] create_ssl 2607:f8b0:4007:803::1008 fail:[Errno 65] No route to host cost:0 h:0
Sep  4 21:04:15 - [DEBUG] report_connect_fail network fail
Sep  4 21:04:15 - [DEBUG] get ip:2607:f8b0:4002:801::100d t:300
Sep  4 21:04:15 - [DEBUG] create_ssl 2607:f8b0:4002:801::100d fail:[Errno 65] No route to host cost:0 h:0
Sep  4 21:04:15 - [DEBUG] report_connect_fail network fail
Sep  4 21:04:15 - [DEBUG] get ip:2607:f8b0:400e:c04::8b t:300

**Comment by holdonyb** [comment]
另外，打开chrome后出现这个，有问题么？
XX-Net-2.0.5 UserName$ lsof -i:8087
COMMAND   PID   USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
Google    236 UserName  188u  IPv4 0x3946e8e0ce2c753      0t0  TCP localhost:59568->localhost:8087 (ESTABLISHED)

**Comment by uuudbx** [comment]
无法访问8085一般是由于退出进程不干净，还有pythonw进程在运行。
打开任务管理器，找到python进程（如果你还有其他python程序在跑，则查看一下进程详细信息，确定是xx的），杀掉python进程。然后再打开xx

**Comment by lele2010lele** [comment]
没错，打开活动监视器，找到py进程，杀掉

**Comment by malthae** [comment]
Mac上经常会出现这个问题，以前先要找到占用的port然后在终端里面杀掉，楼上说的用活动监视器没试过不过应该也是可行的，最白痴的办法就是重启

**Comment by uuudbx** [comment]
活动监视器很好用的，终端命令很多人不会。已经多年不用mac了

**Comment by holdonyb** [comment]
@uuudbx  @lele2010lele  @malthae  感谢

确实是进程不干净，但之前一直以为是XX的问题，但是关掉之后也不行，之后发现一直有一个Python进程杀不掉，关掉会自动重启，即使重新启动也无济于事。
通过活动监视器发现是Launchd打开的。原来是之前把goagent加入到了User和系统文件夹下Library/LaunchAgent和LaunchDaemons中，每次会自动启动，需要用launchctl unload 来清除，并移去plist文件后，然后再按一般程序杀掉Python进程，启动XX-net，即可正常使用。

**Comment by Pd69bq** [comment]
launchd的强大之处就是会监控进程 如果死掉了会自动重启 xx我每次都是手动启动 kill杀起来也方便
