### ISSUE TITLE
急，急，急，急，急

### ISSUE THREAD

**Issue by fangjun0704** [XX-net/XX-Net#9272]
我想问一下我就是运行了XX-Net-3.8.7\start.vbs；然后我访问百度就跳转http://2143.new.favo.xrcch.com/，而且很慢，我现在不想搞这些了，请问如何复原啊，很急，，新手，乱搞了，导致我现在上网很慢了

**Comment by gjbg1989** [comment]
把 百度 添加到直接连接
![default](https://user-images.githubusercontent.com/13290970/34442395-c8ac72f4-ecfc-11e7-9038-3a4c4821497e.png)

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34442475-674b36a2-ecfd-11e7-9380-ce3e1012c9e1.png)
😱貌似被劫持？

**Comment by fangjun0704** [comment]
老哥，请问在弄哦？？我现在不想搞这些翻墙的东西了，，但是之前乱搞，然后我现在每次只要访问百度就会通过两三层链接然后到百度，请问是不是开了代理或者别的什么服务了，，我是新手，不知道怎么复原

**Comment by fangjun0704** [comment]
老哥，请问在弄哦？？我现在不想搞这些翻墙的东西了，，但是之前乱搞，然后我现在每次只要访问百度就会通过两三层链接http://2143.new.favo.xrcch.com/        http://baidu.scj.xrcch.com/   然后到百度，请问是不是开了代理或者别的什么服务了，，我是新手，不知道怎么复原

**Comment by gjbg1989** [comment]
XX-Net 是解压即运行的绿色软件。。。
是不是开了代理或者别的什么服务，只有操作者自己才清楚😂
