### ISSUE TITLE
求助 ！IP Helper 无法开启

### ISSUE THREAD

**Issue by lanwanng** [XX-net/XX-Net#9296]
![image](https://user-images.githubusercontent.com/33820815/34460664-d6486036-ee4f-11e7-9dba-23c08ab30b7c.png)

依赖服务 WinHTTP Web Proxy Auto-Discovery Service 选项是灰色的  
昨天还都正常，今天重启机子就不行了

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34460707-6a8ec0c2-ee51-11e7-809b-f309a9807fb5.png)

**Comment by GoodSake** [comment]
又是cn软件干的好事？哈哈哈！

**Comment by lanwanng** [comment]
系统重置 已解决
