### ISSUE TITLE
关于GOOGLEID

### ISSUE THREAD

**Issue by NOoNE7** [XX-net/XX-Net#9307]
我最近刚重装了系统，之前的GOOGLEID还能继续使用吗

**Comment by gjbg1989** [comment]
继续，给在天边的他人依然继续😂

**Comment by NOoNE7** [comment]
😂现在重新安装一遍是正常的，但是不敢重启，怕他一重启又出现问题了

**Comment by gjbg1989** [comment]
新装系统默认正常，添加注册表项
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。
开机启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by NOoNE7** [comment]
我重启之后也是正常的，还需要添加这些东西吗？

**Comment by gjbg1989** [comment]
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或结束进程pythonw.exe、禁用再启用网络，或机器重启。或结束全部 RuntimeBroker.exe 进程、右键 XX-Net 状态栏图标重启（待验证）

**Comment by gjbg1989** [comment]
😂随意。。。

**Comment by NOoNE7** [comment]
那先不改了，万一又出问题有麻烦了😂

**Comment by gjbg1989** [comment]
32PRO win7&10 一直正常使用的经验而已😂
