### ISSUE TITLE
无聊发个帖

### ISSUE THREAD

**Issue by Da-Xin** [XX-net/XX-Net#9308]
无聊发个帖

**Comment by lam2000** [comment]
我的也遇到同样的问题，之前IPV4不能用IPV6一直很正常。现在系统启动后一定要执行《enable_ipv6.bat》才可以工作，如果连续使用XX-NET网页访问在线时间会久一点。如果不用XX-NET访问网页好像几分钟后IPV6 就显示 Fail 尚未进行连接。必须重新运行《enable_ipv6.bat》才可以工作。求大神们支招，谢谢了！



下面是断线后的诊断日志：
————————————————————————————————————————
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.9.1
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:27 ipv6:3865
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 5
ip-quality: 265
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果

**Comment by Da-Xin** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 10.0.5.39:56648
外部 NAT 映射    : 58.218.147.105:56648

这是失败的

**Comment by lam2000** [comment]
这个是IPV6 Fail 结果
![Uploading IPV6 Fail.png…]()

**Comment by lam2000** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.88.3:60013
外部 NAT 映射    : 119.123.72.6:32017

**Comment by gjbg1989** [comment]
@Da-Xin 
use-ipv6: auto 改为只用 ipv6
确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或结束进程pythonw.exe、禁用再启用网络，或机器重启。或结束全部 RuntimeBroker.exe 进程、右键 XX-Net 状态栏图标重启（待验证）

**Comment by gjbg1989** [comment]
@lam2000 
xxnet-version: 3.9.1——貌似比较短的时间内有3.9.2版，宜手动下载更新到最新版
use-ipv6: auto——改为只用 ipv6
Appids_Not_Exist: true——有appid错误
确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，管理权限运行 netsh int ipv6 set teredo enterpriseclient default
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或结束进程pythonw.exe、禁用再启用网络，或机器重启。或结束全部 RuntimeBroker.exe 进程、右键 XX-Net 状态栏图标重启（待验证）

**Comment by Da-Xin** [comment]
@gjbg1989 你弄好了吗？

**Comment by gjbg1989** [comment]
32PRO win7&10 一直正常使用的经验而已😂

**Comment by Da-Xin** [comment]
@gjbg1989 哦哦！我的还是不行。。

**Comment by Da-Xin** [comment]
@lam2000 你那弄好了吗

**Comment by gjbg1989** [comment]
开机启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by gjbg1989** [comment]
终极方法：确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，先管理权限运行3.7.11版XX-Net目录内disable_ipv6.bat，再enable_ipv6.bat即可正常开启、使用ipv6隧道。

**Comment by gjbg1989** [comment]
终极方法：确保系统服务IP Helper 为自动并已启动，结束进程pythonw.exe，先前修改的ipv6组策略退回到默认值的全部“未配置”，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。

**Comment by Da-Xin** [comment]
@gjbg1989  必须3.7.11吗？我3.8.15 断开我就这样，但是还是一会IPV6就为Fail

**Comment by gjbg1989** [comment]
使用ping超时的微软服务器或许更稳定！(win7除外？)
netsh int ipv6 set teredo enterpriseclient default

**Comment by esofar** [comment]
mark

**Comment by Da-Xin** [comment]
@gjbg1989 不知道什么鬼  就是IPV6就为Fail

**Comment by gjbg1989** [comment]
#8721 实现在本地的DNS 服务，通过在服务器上解析，避免DNS污染。
需要把DNS服务器指向 127.0.0.1
支持解析IPv4/IPv6

**Comment by Da-Xin** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : teredo.remlab.net (Group Policy)
客户端刷新间隔          : 30 秒
客户端端口                : unspecified


运行过这个 先运行上排3个，再运行下排3个，就是这样了

**Comment by gjbg1989** [comment]
不知道什么鬼 就是IPV6就为Fail——莫非系统有360、管家等之流国祸？

**Comment by Da-Xin** [comment]
有 腾讯管家。不过之前版本都没事，就升级8.15后老出现这个问题

**Comment by Da-Xin** [comment]
@gjbg1989 666

**Comment by gjbg1989** [comment]
不过之前版本都没事——基本常识都没有，昨天没事并不保证今天、明天依旧没事😝

**Comment by gjbg1989** [comment]
😄😄😄

**Comment by lam2000** [comment]
@Da-Xin @gjbg1989 
我刚刚下载了最新版本XX-NET 3.9.2.ZIP完整压缩包，进行重新登记Appid 等工作。目前十二个Appid有两个Appid错误，不过这不影响其它Appid使用，并发现错误Appid是随机的。
按照gjbg1989方法重置了ipv6 ，然后重新启动电脑重新运行《enable_ipv6.bat》。打开XX-NET 几分钟后IPV6 可用ID只有100个左右（扫描ID用的是默认10线程），XX-NET可正常使用但随后可用IP便急剧减少！！
我怀疑，极有可能遭到电信DNS污染造成。并非系统或设置问题！
我意外发现，如果一直都在刷网页，XX-NET的IPV6并不会 Fail中断。如果停止浏览刷新网页大约几分钟后，XX-NET显示系统空闲，然后IPV6就显示 Fail 。

是不是IPV6也遭到封杀了？因为好像前一分钟刚刚扫描到的可用ip，后一分钟日志里很快就是显示 timeout。这个状况跟当初封杀IPV4的状况一样。

**Comment by lam2000** [comment]
@gjbg1989 
运行teredo.exe 出现以下结果，这是什么情况？
请选择需要的操作
    1 netsh int ipv6 show teredo
    2 自动选择并设置teredo服务器
    3 手动选择并设置teredo服务器
    4 exit
请选择要进行的操作编号，然后按回车：2
系统找不到指定的路径。
请选择需要的操作
    1 netsh int ipv6 show teredo
    2 自动选择并设置teredo服务器
    3 手动选择并设置teredo服务器
    4 exit
请选择要进行的操作编号，然后按回车：

**Comment by Da-Xin** [comment]
@lam2000 我的好了
打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排后3个工具，先运行上排3个，再运行下排3个，机器重启后 运行 netsh interface Teredo set state disable,再运行 netsh interface Teredo set state type=default，然后把注册表修改了一下，HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0,再运行disable_ipv6.bat，在运行enable_ipv6.bat，就好了。

**Comment by gjbg1989** [comment]
按照gjbg1989方法重置了ipv6 ，然后重新启动电脑重新运行《enable_ipv6.bat》——后面是画蛇添足？
😱貌似可以怀疑，又一个不依建议按部就班。。。

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/34477119-35519aa6-efd2-11e7-8fc7-8395e5ad128d.png)
系统找不到指定的路径？

**Comment by Da-Xin** [comment]
现在都什么时代了，按部就班。。

**Comment by lam2000** [comment]
谢谢两位大神，我修正一下步骤重新来过。
