### ISSUE TITLE
送x-tunnel 流量了，25个，每个3G吧~~

### ISSUE THREAD

**Issue by hsrrtx** [XX-net/XX-Net#9309]
今年11月到期，先到先得~~
买一年实在太多，用不了~~
留邮箱~~
x-tunnel 要先注册，不是有邮箱就可以用的~~

PS：x-tunnel可以改成卖小流量，分拆卖，利润更高。建议精算下~~
1200G真是要成天看小电影才用的了的~~~

**Comment by chenwenhang** [comment]
我来了，老哥

**Comment by sck6162** [comment]
sck6162@gmail.com
感谢大佬

**Comment by chenwenhang** [comment]
cwh736@qq.com    谢谢老哥

**Comment by ecnuhk** [comment]
xiaomogd@gmail.com
祝新年工作顺利！

**Comment by liyu2217** [comment]
liyu2217@163.com
感谢！

**Comment by hsrrtx** [comment]
cwh736@qq.com账号不存在，先注册了在要流量~~

**Comment by hsrrtx** [comment]
liyu2217@163.com也是不存在~~

**Comment by hsrrtx** [comment]
liyu2217@163.com也是不存在~~

**Comment by hsrrtx** [comment]
# **_自己看帖~~~~ 
x-tunnel要先注册账号的~~~
不是有了邮箱就能用的~~_**

**Comment by chenwenhang** [comment]
噢噢不好意思之前没看见，刚刚注册好，cwh736@qq.com，谢谢老哥！！！

**Comment by hsrrtx** [comment]
# 以上有邮箱的都好了

**Comment by icopp-juve** [comment]
新年快乐，老板大气！
icopp.juve@gmail.com

**Comment by spvwh** [comment]
myspvwh#gmail.com
谢谢！

**Comment by asvue** [comment]
251243021@qq.com   谢谢大哥,,,,好人一生平安!!!!

**Comment by liyu2217** [comment]
liyu2217@163.com
抱歉，刚刚没理解意思，已经注册好了。
感谢

**Comment by Rachelqian** [comment]
731436284@qq.com，谢谢哦

**Comment by esofar** [comment]
973095739@qq.com
多谢！

**Comment by maolonghua** [comment]
longhua.mao@gmail.com 谢谢大佬！

**Comment by hsrrtx** [comment]
# 以上转好，没转的就是没注册，账户不存在~~

**Comment by hsrrtx** [comment]
操作失误，好像给两个qq账号多转了一次~~

**Comment by 29311514** [comment]
a29311514@qq.com

好人一世平安

**Comment by moonza** [comment]
moonza@yeah.net
Thanks，大气！

**Comment by erbinggang** [comment]
476697900@qq.com
十分感谢！

**Comment by spvwh** [comment]
@hsrrtx 收到，谢谢！

**Comment by Aargol** [comment]
995509487@qq.com, thanks!

**Comment by lkhtty** [comment]
nn0430@gmail.com 谢谢

**Comment by zlychen** [comment]
1292428713@qq.com多谢。。。

**Comment by plyyqmjs9527** [comment]
pyx9809829@163.com 谢谢老哥了！

**Comment by NOoNE7** [comment]
Z17320823792@gmail.com😂

**Comment by hsrrtx** [comment]
gmail某个账号又多转了一次~~
没收到的应该都是账号没注册~~
不能怪我了~~
不一一提示了~~

**Comment by hsrrtx** [comment]
发现用qq账号没注册的多~~
一般gmail的都没问题~~

**Comment by hsrrtx** [comment]
以上能转的都转好了~~

**Comment by Aargol** [comment]
yosoyskiboski@gmail.com, thank you!

**Comment by Emphasia** [comment]
Emphasia#github.com 谢谢。

**Comment by rebecca0001** [comment]
544059255@qq.com ，谢谢了

**Comment by frozenmaple** [comment]
feng.qian@colorado.edu 不知是否还有名额，先谢谢了

**Comment by hsrrtx** [comment]
先关贴了~后面的一会转~

**Comment by hsrrtx** [comment]
凡是没收到的，请检查账号是否注册~~
不想再说了~~
能转的都转好了~~
后续账号弄好了，可以继续回此贴~~

**Comment by zicai1026** [comment]
xt-r@zicai.uu.me
谢谢大佬

**Comment by lzpsgh** [comment]
lensaclrtn@gmail.com
祝大佬好人一生平安
