### ISSUE TITLE
XX-Net 无法访问谷歌学术（google scholar）

### ISSUE THREAD

**Issue by LebranceBW** [XX-net/XX-Net#9311]
每次访问谷歌学术的时候谷歌就要报异常，无法通过输入验证码跳过。
ps：我用的是最新版XX-Net(3.8.5) 且开了IPV6
   
![image](https://user-images.githubusercontent.com/19501514/34474817-6903399e-efbf-11e7-8d8c-a26b87bdc00b.png)

**Comment by Zmm1977** [comment]
那是因为谷歌学术没被墙

**Comment by gjbg1989** [comment]
X-TUNNEL 1080 代理尚可

**Comment by LebrancBW** [comment]
啊？我用的GAE代理妥妥的异常流量

**Comment by LebrancBW** [comment]
@Zmm1977 啊？我直连连不了

**Comment by Zmm1977** [comment]
我这边直连没问题，反而爬梯子不行

**Comment by onplus** [comment]
能直连的的大概是教育网

GAE代理不能使用谷歌学术，请使用x-tunnel

**Comment by Zmm1977** [comment]
我擦，我关了ipv6就不能直连了。。。

**Comment by gjbg1989** [comment]
RT @oiax: https://sci-bay.org  这个好，Google 学术搜索的镜像，免翻墙，速度快。
