### ISSUE TITLE
突然不能使用了

### ISSUE THREAD

**Issue by Gamehu** [XX-net/XX-Net#9312]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:479 ipv4:0 ipv6:438
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 226
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
use-ipv6: auto改为只用ipv6
贴运行 netsh int ipv6 show teredo 结果

**Comment by xelamai** [comment]
> gjbg1989

改成了force ipv6还是不行，谷歌搜索总是跳到ipv4的拒绝页面。

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5869 ipv4:23 ipv6:5387
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:51 h2:0
scan-ip-thread-num: 10
ip-quality: 291
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false


---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.1.107:52759
外部 NAT 映射    : 106.226.8.176:6170

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或结束进程pythonw.exe、禁用再启用网络，或机器重启。或结束全部 RuntimeBroker.exe 进程、右键 XX-Net 状态栏图标重启（待验证）

**Comment by rickertanks** [comment]
我的也有这问题，鉴于当前这种网络情况还是给大家推荐个备用的方法，点我头像查看吧！享受丝滑流畅！

**Comment by Gamehu** [comment]
谢谢
