### ISSUE TITLE
建议：XX-net着手定制全新网速新版本【XX-net-1080版】

### ISSUE THREAD

**Issue by 80068** [XX-net/XX-Net#9318]
最近使用XX-net依然很好，没有什么问题。但在高网速需求使用越来越大的网络环境中，XX-net现有版本用起来还是显得比较慢。建议XX-net开始着手研发超高速的翻墙软件。例如以1080视频播放为基准，新XX-net-1080版能满足用户观看youtube上的高清视频，并且不卡顿，长期保持高速状态。收费标准最好能低于蓝灯。因为现在蓝灯使用不是很安全，容易泄密。这点来看XX-NET更好。所以期待XX-net能有更新的软件开发。

**Comment by 2378** [comment]
高速～ 谈何容易
元旦假期从老同学口中听到一件事
他们干线机房近20%的带宽是被??部的服务器占用的
你懂的

**Comment by OuyangIPC** [comment]
能出去就不错了，高速还是自己花钱整个vps吧

**Comment by krollMJ** [comment]
什么高速翻墙都是浮云，出口带宽一卡死，都得嗝屁。

**Comment by shoujiao** [comment]
你知道喝茶的味道吗？
建议楼主肉身FQ

**Comment by ksit1110** [comment]
淡定   搭个vps吧

**Comment by imldf** [comment]
xx-net 本来就有收费版本啊

**Comment by OuyangIPC** [comment]
收费的最近也不得行了诶，不知道为何

**Comment by 80068** [comment]
@OuyangIPC  可行，但安全性、会不会泄漏个人信息这是问题

**Comment by OuyangIPC** [comment]
@80068 出去都搜资料和看看娱乐视频，没啥个人信息可泄露，哈哈哈

**Comment by zhencaihao** [comment]
还想高速。我这里看140P都非常卡。

**Comment by OuyangIPC** [comment]
以前1080P也可以啊，只是19big前夕ip都集体阵亡，这是没办法的事儿

**Comment by roc1010kmt** [comment]
主要是ipv4沒有ip，ipv6速度慢，怎麼提高速度？
