### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by lyonferris** [XX-net/XX-Net#9322]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2026 ipv4:1 ipv6:1761
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:44 h2:1
scan-ip-thread-num: 150
ip-quality: 378
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: true
Using_Public_Appid: false

**Comment by lyonferris** [comment]
chrome是 63.0.3239.108（正式版本） （64 位）
GreenChrome 6.3.7

**Comment by gjbg1989** [comment]
试试：网络属性内取消勾选 IPv6 协议

**Comment by lyonferris** [comment]
@gjbg1989 我发现虽然

**Comment by gjbg1989** [comment]
扩展 Disconnect 采用 whitelist site 时就是此状态，采用 blacklist site 即 OK
