### ISSUE TITLE
请重视并修复"请检查浏览器设置"的问题

### ISSUE THREAD

**Issue by fnatictreo** [XX-net/XX-Net#9327]
反馈区好多帖子都是这问题，试了几乎能试的方法

**Comment by hcrcaaaa** [comment]
一直是这个问题。一直来看看有没有解决办法。

**Comment by nly4lov** [comment]
下载最新证书，删除原来的，放进最新的，右键管理员运行start.bat，这个试过吗

**Comment by gjbg1989** [comment]
添加 127.0.0.1 走直接连接
添加 *.slice.org 走 GAE

**Comment by gustav183** [comment]
确实是，反馈区里几乎大部分都是这方面的问题，这好像不是墙改变策略造成，应该是XXnet自身存在某方面的欠缺，望改进

**Comment by xxnet** [comment]
​以后都切换到智能路由下工作，这个问题就可以解决了。
