### ISSUE TITLE
遭遇浏览器设置问题

### ISSUE THREAD

**Issue by hcrcaaaa** [XX-net/XX-Net#9329]
事实上浏览器设置是没问题的。突然不可用了，突然又可用了。刚刚紧急用时，尝试禁用SwitchyOmega后设全局又能用。

**Comment by nly4lov** [comment]
https://github.com/XX-net/XX-Net/issues/9327

**Comment by hcrcaaaa** [comment]
谢谢楼上提醒。除删除没做（不知道删哪个），其他的照做了，还是一样。

**Comment by hcrcaaaa** [comment]
现在又行了。我又启动了SwitchyOmega。我把GAE自动改为GAE代理，尝试使用，发现可以了。然后，还把XXNET改为取消全局，一样能用。

**Comment by hcrcaaaa** [comment]
虽然现在能用，不代表等下还能用。毕竟没有一个确定的正确的根据和操作。再说一个BUG，就是，这些天，发现用着用着，不能用了，XXNET不响应了，直接右键也退不出来。

**Comment by gjbg1989** [comment]
直接右键也退不出来——结束进程pythonw.exe

**Comment by hcrcaaaa** [comment]
是的。只能在任务管理器结束进程。

**Comment by gjbg1989** [comment]
运行 certmgr.msc 删除
![default](https://user-images.githubusercontent.com/13290970/34548656-3617a04e-f13e-11e7-8a88-e81636d9d8fc.png)

**Comment by hcrcaaaa** [comment]
谢谢1989.已删除后再导入。导入到个人还是受信任位置？我是后者。已重启正常。我又再尝试GAE自动切换，故障依然。再切回GAE-proxy,又能用。难道问题出现在这里？

**Comment by gjbg1989** [comment]
添加 127.0.0.1 走直接连接
添加 *.slice.org 走 GAE
GAE自动切换OK

**Comment by hcrcaaaa** [comment]
谢谢。能用，就不再折腾。毕竟是菜鸟。

**Comment by hcrcaaaa** [comment]
再 来报告一个有趣的事。刚又检查浏览器设置了。但可以爬出去。再看XXNET是取消全 局代理，又看SwitchyOmega被我改为自动GAE。这时，刷新下网页，发现正常能用。再打开别的被墙网页，都能出去。就是说，检查浏览器状态下，也能用。怪了。

**Comment by hcrcaaaa** [comment]
没任何操作有关软件，莫名其妙的又全部都正常了。
