### ISSUE TITLE
模式选择

### ISSUE THREAD

**Issue by YellowLei** [XX-net/XX-Net#9334]
使用GAE_Proxy自动切换模式时，提示 请检查浏览器代理设置

使用GEA_Proxy模式时可以正常使用

**Comment by gjbg1989** [comment]
添加 127.0.0.1 走直接连接
添加 *.slice.org 走 GAE
添加                走 GAE
代理和CA证书OK
GAE自动切换OK

**Comment by xxnet** [comment]
​3.9.3 推荐用Smart-Router模式，SwitchyOmega 请重新导入 .bak设置文件

**Comment by gjbg1989** [comment]
黑名单（？？？）——没有任何解释，不明觉厉。。。
![default](https://user-images.githubusercontent.com/13290970/34637662-040c4dac-f2f6-11e7-8a14-f8819e7b2a82.png)

**Comment by xxnet** [comment]
​就是直接拒绝访问的域名，可以用来过滤广告之类的。
此处需要添加一个链接，指向Wiki，提供帮助信息。

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
