### ISSUE TITLE
ubuntu16.04下xx-net默认浏览器无法配置成chrome

### ISSUE THREAD

**Issue by jfli-thu** [XX-net/XX-Net#9337]
* 是否试过最新的测试版本？
  已经最新版。
  

* 是否看过Issues区最近的讨论？
 已经搜索过无类似问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  查看过wiki。

* 简单描述遇到的问题：
ubuntu 16.04   已经安装了chrome，并且在system settings的details 里面把默认浏览器配置为chrome， 但是xx-net启动默认就打开firefox....  但是我用chrome已经能够配置代理并成功访问google。 
然而要配置appid时候，xxnet也是默认打开firefox...  firefox又不能翻墙，只有chrome的swtichyOmega在代理...  这就很尴尬

* 做过哪些尝试：
自己在ubuntu下ipython中写代码 
import webbrowser
webbrowser.open("http://127.0.0.1:8085")
运行确实打开的是chrome... 

* 请贴出对应模块的状态页
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017
os-release: 4.4.0-104-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:630 ipv4:0 ipv6:624
ipv4-status: OK
ipv6-status: OK
connected-link: new:3 used:0
worker: h1:22 h2:0
scan-ip-thread-num: 10
ip-quality: 364
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

* 请贴出相关的日志

**Comment by onplus** [comment]
![image](https://user-images.githubusercontent.com/31188782/34573943-e109acdc-f1b0-11e7-9a82-c035ca83eb11.png)

https://github.com/XX-net/XX-Net/tree/master/code/default/gae_proxy/server

**Comment by jfli-thu** [comment]
谢谢回复 ， @onplus  很神奇的就是直接运行也是默认打开firefox...   我启动xx_net的时候也是打开firefox，但是显示页面是“尚未连接”，但是马上打开chrome的 127.0.0.1:8085则可以看到表示已经链接。而且确实chrome也可以访问google...  
尝试过直接运行server中的uploader.py了，也是调用firefox。。。 很崩溃...

**Comment by jfli-thu** [comment]
@onplus  啊！ 我刚刚发现了，我自己谢了个test.py，里面是简单的 
import webbrowser
webbrowser.open("http://127.0.0.1:8085") 
这个脚本我用python test.py 运行的话，就是打开chrome；但是用sudo python test.py的话就是调用firefox！  这个是ubuntu的root用户配置问题么？

**Comment by 2378** [comment]
不是有个“首选应用设置”吗
要不就手动改
/usr/share/applications/defaults.list

**Comment by jfli-thu** [comment]
@2378  谢谢回复，不过不是这个的问题，这些默认配置都配置好了的。
google了很久，自己发现了问题。是chrome在root权限下无法用sandbox的方式启动，所以只要在chrome的启动脚本中添加--no-sandbox即可。  我的chrome是在/usr/bin/google-chrome， 是对/opt/google/chrome/google-chrome的链接，我修改了/opt/google/chrome/google-chrome文件的一行，如下原代码：
exec -a "$0" "$HERE/chrome" "$@"        
修改后：
exec -a "$0" "$HERE/chrome" "$@" "--no-sandbox"   # 修改后的加上--no-sandbox，否则在root下无法启用chrome

**Comment by 2378** [comment]
还真没想到啊
原以为只有国产软件那么牛逼哄哄的
