### ISSUE TITLE
求X-TUNNEL流量

### ISSUE THREAD

**Issue by yuqi33** [XX-net/XX-Net#9345]
刚注册的X-TUNNEL,只有500M,已捐献5个ID,捐献流量还没到账,求各位流量用不完的大神转让一些流量过渡一下,万分感谢!

  帐号:yuqi33@gmail.com

**Comment by Odaimoko** [comment]
需要多少= =？

**Comment by yuqi33** [comment]
@Odaimoko 1G,2G都可以,,过渡一下...谢谢!!!

**Comment by Odaimoko** [comment]
好了，查收~

**Comment by yuqi33** [comment]
@Odaimoko 已收到,,多谢!!
