### ISSUE TITLE
请问如何在启动start.bat后，隐藏日志窗口到后台

### ISSUE THREAD

**Issue by rockwzy** [XX-net/XX-Net#9348]
我记得以前可以设置参数不在前台显示，忘记了，恳请告知。

**Comment by sgricky** [comment]
在XX-Net中使用“开机自动启动”啊~

**Comment by sgricky** [comment]
如果是需要在Windows中手动启用，那可以执行相同目录下的start.vbs

**Comment by gjbg1989** [comment]
原 start.bat ：
SET PYTHONPATH="%~dp0%start.vbs" console
改成：
SET PYTHONPATH="%~dp0%start.vbs" noconsole

**Comment by rockwzy** [comment]
感谢楼上的解答，改为noconsole后可解决问题
