### ISSUE TITLE
无法为iPhone设备提供代理

### ISSUE THREAD

**Issue by vize-xpft** [XX-net/XX-Net#9366]
模块：GAE
手机信息
Apple iPhone 6
iOS11.2.1 (15c153)
连接了WiFi
IP：自动
DNS：自动
HTTP代理：自动
URL：http://192.168.0.254:8086/proxy.pac

可以访问pac地址，显示出文本文档，无乱码。
已经导入GoAgent XX-Net 证书
访问192.168.0.254:8085，显示

> Please check your browser proxy setting

访问google.com
浏览器显示：

> This Connection Is Not Private

查看证书，为XX-Net的，但是显示不被信任。
可以访问，但是感觉会有错误。

电脑信息
```
XX-Net Version | 3.8.7
Python Version | 2.7.13
OpenSSL Version | 16.0.0 TLSv1_2 h2:alpn
System Platform | AMD64, Windows-10-10.0.16299
OS System | Windows
OS Version | 10.0.16299
OS Release | 10
OS Detail | Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language | en_US
Architecture | 32bit,WindowsPE
Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```
电脑代理状态正常：

> XX-Net 3.8.7, Everything is OK. Welcome to the FREE Internet.

已部署APPID

监听端口：
```Listening Proxy | 0.0.0.0:8087
PAC URL | http://0.0.0.0:8086/proxy.pac
```
已按照[WIKI](https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1)
设置manual.ini
电脑局域网IP：
```
IPv4 Address. . . . . . . . . . . : 192.168.0.254
```

**Comment by liushuiguadanbo** [comment]
我也遇到了这个问题 求大佬解答

**Comment by liushuiguadanbo** [comment]
emmm我发现我电脑的IP和热点软件的ip不一样 要用电脑的ip 设置手动服务器和端口8087，手机能上google，但是电脑ip：8085打不开 而热点软件的ip：8085能打开可是上不了网

**Comment by vize-xpft** [comment]
@liushuiguadanbo 我和你的问题不太一样，我的感觉像是证书的问题

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA#ipadiphone%E6%89%8B%E5%8A%A8%E5%AF%BC%E5%85%A5%E8%AF%81%E4%B9%A6

**Comment by vize-xpft** [comment]
> Jan 07 14:16:03.734 [gae_proxy][INFO] PAC from:192.168.0.101:57428 GET /proxy.pac

可以看到iPhone可以获取pac
但是访问google会出现证书异常。但是如果一定要访问还是可以的。

**Comment by vize-xpft** [comment]
@onplus 我按照教程上做了，且设置中的Profiles有GoAgent XX-Net证书。

**Comment by onplus** [comment]
可以访问中文维基吗？
结果截图看看

**Comment by vize-xpft** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vize-xpft** [comment]
![06624cae3f4db2b61162b3c86e781fd4](https://user-images.githubusercontent.com/18572062/34647209-4fed1e88-f3b7-11e7-8a7b-18549639fef1.jpg)
![a8b5d3feed2809989db491afec5f00a6](https://user-images.githubusercontent.com/18572062/34647210-504738f0-f3b7-11e7-91dc-79c6035a636a.jpg)
![d5bc6c5653282dee9a5144a87c6f71a1](https://user-images.githubusercontent.com/18572062/34647211-50b9ff8e-f3b7-11e7-997f-643d6fcebc28.jpg)

**Comment by vize-xpft** [comment]
可以访问Google，但是不能访问Wiki

**Comment by yuqi33** [comment]
我怀疑跟IOS版本有关系,我用老的IPHONE4S ISO9.3.5同样的设置pac自动代理访问正常,,但是其他设备都是IOS10.X.X版本的同样设置PAC自动代理就没法正常打开被墙网站.证书代理都同样的设置步骤.

**Comment by carlchan99** [comment]
"通用“-”关于本机“-”证书信任设置“这里要启用完全信任

**Comment by vize-xpft** [comment]
@carlchan99 谢谢。我忘记IOS11有这个神奇的东西了。。。
