### ISSUE TITLE
Ping 请求找不到主机 ipv6.test-ipv6.com。请检查该名称，然后重试。

### ISSUE THREAD

**Issue by wxevu** [XX-net/XX-Net#9372]
找不到主机，什么情况？

**Comment by GoodSake** [comment]
正常哦：

![snap1](https://user-images.githubusercontent.com/19205130/34647351-9daf5a06-f3bb-11e7-84cd-46f8eb2aa053.png)

**Comment by 2378** [comment]
你没设置v6 dns吧
不过设置了 也常丢包的 这是特色

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/34647625-ebc97644-f3c1-11e7-86bf-fcd51db6ad98.png)
![image](https://user-images.githubusercontent.com/13290970/34647626-f0f7910a-f3c1-11e7-9522-130a5f0cae4b.png)

**Comment by GoodSake** [comment]
SD-WAN是啥？

**Comment by gjbg1989** [comment]
😱

**Comment by GoodSake** [comment]
哈哈哈！

**Comment by onplus** [comment]
@gjbg1989 可以单发有效信息，别在他人的issue里发无关的回复。
而且这个备案建站不影响翻墙。

**Comment by wxevu** [comment]
想了想和能连上的时候有什么不同——以前是手机开热点，现在连的是学校的宿舍宽带
一换，果然好了
