### ISSUE TITLE
有没哪位老铁做网站的，我们来互换友链吧

### ISSUE THREAD

**Issue by tibreak** [XX-net/XX-Net#9382]
https://www.tbreak.top

**Comment by GoodSake** [comment]
这网站干啥的呀？10cny一个啪啪啪？哈哈哈。

**Comment by tibreak** [comment]
这是博客。。。

**Comment by GoodSake** [comment]
blog?博客是啥意思？vlog是视频(v=video)记录？你的b屄啥意思？

**Comment by tibreak** [comment]
吊毛，你脑子被门夹了，走错地方了

**Comment by GoodSake** [comment]
哦，猜到了,book log是吧....Oops I messed up something.

**Comment by x86nat** [comment]
哈哈，，这是赤果果的广告贴么。。来啊。
www.in1d.net

**Comment by GoodSake** [comment]
有没有实业啊，比如10cny一个啪啪啪的？哈哈哈，你们这些看不懂到底是干啥的。。。

**Comment by underlaw** [comment]
哈哈内容比我的还少
www.vxget.com

**Comment by Iloveappleandperaaaa** [comment]
Hi，我觉得我们不能那么干了，在那么干，鱼塘里会引起注意，大家一琢磨，钓鱼的人多了我们都无法控制。我们都原创，然后创新标题，OK？
