### ISSUE TITLE
为什么connected link一栏里一直是0,0？

### ISSUE THREAD

**Issue by tinyperson** [XX-net/XX-Net#939]
![image](https://cloud.githubusercontent.com/assets/14156036/9709056/5168db7c-5557-11e5-8f35-e0e0049bf623.png)

第二个100th IP handshake（ms）为什么一直不变？
![image](https://cloud.githubusercontent.com/assets/14156036/9709093/b5cfddae-5557-11e5-84d2-f20a89ca5494.png)

浏览google是上图这种情况。

**Comment by tinyperson** [comment]
第二个100th IP handshake（ms）为什么一直不变？

**Comment by tinyperson** [comment]
![image](https://cloud.githubusercontent.com/assets/14156036/9709093/b5cfddae-5557-11e5-84d2-f20a89ca5494.png)

浏览google是上图这种情况。

**Comment by yuliangyang** [comment]
退回2.0.5版本，下次出现上述情况，重启xxnet

**Comment by tinyperson** [comment]
@yuliangyang 
可以了！谢谢啦！

**Comment by yuliangyang** [comment]
不客气，
