### ISSUE TITLE
为什么xx-net的手机版不能做成一键式vpn的方式

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#9399]
尝试过在2部手机部署，按照教程均不成功，tunnel流量也有，不知道能不能以后改成一键式，全局手机vpn那种

**Comment by onplus** [comment]
https://github.com/XndroidDev/Xndroid

**Comment by yuyistar** [comment]
@onplus 确实方便呀，不过怎么不能给app用，只能浏览器使用，这样几乎使用率相当低呀

**Comment by Lancenas** [comment]
可以通过自己架设VPN共享xxnet，不管到哪儿都可以用。

**Comment by yuyistar** [comment]
@Lancenas 能发一下教程链接吗。不是很明白怎么弄。谢谢
