### ISSUE TITLE
X-tunnel流量

### ISSUE THREAD

**Issue by qjwshz** [XX-net/XX-Net#9405]
深夜未眠，爬上来看看xxnet的近况。都更新到3.9.x系列了。我还在用着3.8.x系列。

* X大还管理着这个项目吗?如果没管理，那更新是不是其他人那里出来的?

* 问大拿们要点X-tunnel流星来使使，比较比较与xxnet的异同（主要试下下载速度）。1、2G均可。

19大会前一两个星期，xnet是熄火了，所幸大会之后半个月左右吧，就恢复正常了。走得v6隧道。v4看来是莫相了。虽然不懂其中原理，但还是衷心希望XXnet持续更新可用！！

激荡四十年！

四十年之后，谁知道世界会变成什么样～～:-)

对了，我的邮箱: qjwshz@gmail.com （也可 以算是X-tunnel 账号吧）。

**大拿们记得赏赐点流量玩玩。:-)**

**Comment by onplus** [comment]
#5584

**Comment by mitanikanae** [comment]
送你2G让你试试好了

**Comment by qjwshz** [comment]
谢谢！！
