### ISSUE TITLE
比较懵逼

### ISSUE THREAD

**Issue by Leecns** [XX-net/XX-Net#9409]
不知道怎么用，是封的严了，还是程序越来越脱离人性了。你好不容易写个代码，人家不会用。。。。。。。

**Comment by 2378** [comment]
小技巧：拿块豆腐狠拍脑门，就会用了 :smiling_imp:

**Comment by GoodSake** [comment]
啥都会，啥都知道，那就懒得用了，哈哈哈。

**Comment by Lancenas** [comment]
3.9.3很好用，只要有APPID，部署好了，没什么可懵懂
