### ISSUE TITLE
现在软件很不稳定呀。经常用几分钟就断

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#9416]
要不提示请检查浏览器代理设置。或者提示尚未建立连接，不理他过一会就好了。这个应该不是我设置的问题吧。因为有时候它是正常的

**Comment by gjbg1989** [comment]
保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by gjbg1989** [comment]
（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by yuyistar** [comment]
@gjbg1989 注册表里面是建字符串值，还是dword32值？
