### ISSUE TITLE
win7 没有IP转配置服务 如何解决

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#9418]
win7
没有IP转配置服务 如何 解决 请问 谢谢

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34779956-b68e53e4-f65c-11e7-9fab-38e6b5379aa0.png)

**Comment by xiaoteai** [comment]
![bjb43u69 lpld_ l0qtw](https://user-images.githubusercontent.com/10782704/34780900-58fda34e-f65f-11e7-9d6b-827ceb8342a3.jpg)

**Comment by xiaoteai** [comment]
一直 看不到 何解  是自带的吗    还是添加

**Comment by xiaoteai** [comment]
![ciiotztt5a 2mfvygr 6_7](https://user-images.githubusercontent.com/10782704/34781302-7331288e-f660-11e7-9e36-66240d527955.jpg)
