### ISSUE TITLE
3.9.3版本 PAC顯示好像有問題

### ISSUE THREAD

**Issue by imldf** [XX-net/XX-Net#9419]
選擇PAC智能代理是下圖的樣子，但可以上網
![001](https://user-images.githubusercontent.com/33856971/34781287-67916eda-f660-11e7-9b3c-76ebe323e6e7.PNG)

**Comment by Emphasia** [comment]
可以参考 #9330

**Comment by xxnet** [comment]
​3.9.4 里解决
https://github.com/XX-net/XX-Net/releases/tag/3.9.4
