### ISSUE TITLE
求助！win7 3.8.5 IPV6 fail 尚未建立连接

### ISSUE THREAD

**Issue by sakura00** [XX-net/XX-Net#9420]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:0 ipv6:981
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 90
ip-quality: 378
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by sakura00** [comment]
还有我不知道那个tertdo.bat是如何部署的，在wiki上也没找到教程，望指教

**Comment by gjbg1989** [comment]
不知道那个tertdo.bat——问度娘😂批处理。。。
WIN7没有IP转换那个服务—— https://github.com/XX-net/XX-Net/issues/9418

**Comment by sakura00** [comment]
你好，我想问一下这段话是什么意思：
下面的"有效的Teredo接口名称”需要自己查找替换，具体名称规则，不是Teredo开头的“Teredo Tunneling Pseudo-Interface”，就是本地连接挂*的，状态应该是已连接(connected)
有效的teredo接口名称是什么

**Comment by gjbg1989** [comment]
别理会。。。做好以下，貌似没有不成功的😂
保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by gjbg1989** [comment]
（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by scljy** [comment]
应该在上面（wlan附近）
