### ISSUE TITLE
估计墙又升级了

### ISSUE THREAD

**Issue by zanewayne78** [XX-net/XX-Net#9421]
X-Tunnel流量精准判断油管，推特，脸书断流终止链接，而其他被墙网站则能上，不知会不会一直持续下去

**Comment by zanewayne78** [comment]
现在又恢复了，日后再看看

**Comment by zanewayne78** [comment]
算我说错了，还是被墙

**Comment by gjbg1989** [comment]
弃用 ISP 商 DNS ，指定 IPv4 及 IPv6 DNS ？
