### ISSUE TITLE
能翻墙，但始终“检查浏览器设置”

### ISSUE THREAD

**Issue by emuo** [XX-net/XX-Net#9422]
请帮看看啥问题。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.9.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5876 ipv4:5 ipv6:2802
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:131 h2:0
scan-ip-thread-num: 10
ip-quality: 306
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Emphasia** [comment]
可以参考 https://github.com/XX-net/XX-Net/issues/9330

**Comment by emuo** [comment]
谢了!按照指点，瞬间搞掂！
