### ISSUE TITLE
3.9.4版本 全局GAE代理使用正常  PAC代理和智能路由失敗

### ISSUE THREAD

**Issue by imldf** [XX-net/XX-Net#9432]
還是上一版本 3.9.3 比較穩定，要穩定的朋友可以先觀望。

**Comment by xxnet** [comment]
​已经发布 3.9.5版本，修复智能路由失败，请帮忙测试。
需要稳定的，先不要升级

**Comment by imldf** [comment]
3.9.5版本 剛升級。很不錯，GAE\PAC\SMART三種模式都OK啦。建議大家使用3.9.5

**Comment by xx-Chen** [comment]
#9330
