### ISSUE TITLE
尚未建立连接 大神们帮忙看看 感谢!

### ISSUE THREAD

**Issue by MilesLo** [XX-net/XX-Net#9434]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5975 ipv4:0 ipv6:719
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 464
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by MilesLo** [comment]
类型                    : client
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

**Comment by gjbg1989** [comment]
netsh int ipv6 set teredo enterpriseclient
保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by MilesLo** [comment]
teredo.zip 点了没反应 下载不了

**Comment by MilesLo** [comment]
Test with IPv4 DNS record |   | ok (3.046s) using ipv4
-- | -- | --
Test with IPv6 DNS record |   | bad (2.033s)
Test with Dual Stack DNS record |   | ok (2.042s) using ipv4
Test for Dual Stack DNS and large packet |   | ok (1.804s) using ipv4
Test IPv4 without DNS |   | ok (2.042s) using ipv4
Test IPv6 without DNS |   | timeout (16.012s)
Test IPv6 large packet |   | bad (1.803s)
Test if your ISP's DNS server uses IPv6 |   | timeout (6.664s)
Find IPv4 Service Provider |   | ok (1.722s) using ipv4 ASN 4134
Find IPv6 Service Provider |   | bad (2.013s)
