### ISSUE TITLE
V3.9.4 X-TUNNEL无法连接

### ISSUE THREAD

**Issue by monkeyhai** [XX-net/XX-Net#9437]
Jan 11 20:33:16.276 - [INFO] xxnet_version:3.9.4

Jan 11 20:33:16.276 - [INFO] server 127.0.0.1:1080 started.

Jan 11 20:33:16.276 - [INFO] Socks5 server listen:127.0.0.1:1080.

Jan 11 20:33:18.855 - [DEBUG] x_tunnel force update info

Jan 11 20:33:24.872 - [WARNING] front retry /login

Jan 11 20:33:26.210 - [INFO] api:/login success t:7354

Jan 11 20:33:26.210 - [INFO] request_balance host: port:0 balance:0.000000 quota:1199977776707.000000

Jan 11 20:33:15.635 - [INFO] load ip range file:D:\XX-Net-3.9.4\code\default\x_tunnel\local\cloudflare_front\ip_range.txt

Jan 11 20:33:15.657 - [INFO] load google ip_list num:3000, gws num:3000

Jan 11 20:33:15.661 - [INFO] Adjust scan thread num from 1 to 0

Jan 11 20:33:16.776 - [DEBUG] network is ok, cost:2128 ms

Jan 11 20:33:17.475 - [INFO] updated cloudflare front domains from github.

Jan 11 20:33:18.857 - [DEBUG] trigger get more worker

Jan 11 20:33:18.857 - [DEBUG] try connect 104.25.116.231

Jan 11 20:33:19.358 - [DEBUG] try connect 172.64.2.73

Jan 11 20:33:19.493 - [DEBUG] create_ssl update ip:104.25.116.231 time:623 h2:1 sni:bijuteriya74.ru top:movistar.gq

Jan 11 20:33:19.858 - [DEBUG] trigger get more worker

Jan 11 20:33:19.859 - [DEBUG] trigger get more worker

Jan 11 20:33:19.987 - [DEBUG] create_ssl update ip:172.64.2.73 time:628 h2:1 sni:marketingbyliz.com top:superx.gq

Jan 11 20:33:20.103 - [DEBUG] trigger get more worker

Jan 11 20:33:20.493 - [DEBUG] try connect 190.93.245.85

Jan 11 20:33:20.988 - [DEBUG] try connect 104.16.233.137

Jan 11 20:33:21.253 - [DEBUG] trigger get more worker

Jan 11 20:33:22.360 - [DEBUG] trigger get more worker

Jan 11 20:33:22.737 - [DEBUG] create_ssl update ip:104.16.233.137 time:1749 h2:1 sni:lunasinstore.com top:c-term.tk

Jan 11 20:33:23.738 - [DEBUG] try connect 104.16.26.46

Jan 11 20:33:24.361 - [DEBUG] create_ssl update ip:104.16.26.46 time:623 h2:1 sni:crimsonrgames.com top:flar.tk

Jan 11 20:33:24.872 - [WARNING] req /login get response timeout

Jan 11 20:33:24.899 - [DEBUG] 190.93.245.85 fail:error('certficate is none, sni:incisivecdn.com, top:dragon-dreamer.com',)

Jan 11 20:33:24.899 - [DEBUG] report_connect_fail:190.93.245.85

Jan 11 20:33:25.362 - [DEBUG] try connect 104.19.100.123

Jan 11 20:33:25.905 - [DEBUG] try connect 104.25.131.96

Jan 11 20:33:26.210 - [DEBUG] POST center.superx.gq/login status:200 trace:0:start_request,0:get_task(2),0:get_worker(0):172.64.2.73,0:h2_req,0:start send header,0:start send left body,0:end send left body,336:h2_get_head,0:get_response,:0

Jan 11 20:33:27.896 - [WARNING] h2 timeout 104.25.116.231 task_trace:0:start_request,0:get_task(1),3018:get_worker(3):104.25.116.231,0:h2_req,15:start send header,0:start send left body,0:end send left body,1979:get_response,:3023 worker_trace: processed:0, h2.stream_num:1, sni:bijuteriya74.ru, domain:movistar.gq

Jan 11 20:33:27.896 - [DEBUG] POST center.xx-net.net/login response_fail:timeout

Jan 11 20:33:27.896 - [DEBUG] 104.25.116.231 close:down fail

Jan 11 20:33:27.896 - [DEBUG] 104.25.116.231 worker close:timeout

Jan 11 20:33:27.896 - [DEBUG] 104.25.116.231 _consume_single_frame:ConnectionResetError(), inactive time:5

Jan 11 20:33:27.897 - [DEBUG] 104.25.116.231 worker close:disconnect:ConnectionResetError()

Jan 11 20:33:29.681 - [DEBUG] 104.19.100.123 fail:error('certficate is none, sni:misyonporn.com, top:mostlygood.ga',)

Jan 11 20:33:29.681 - [DEBUG] report_connect_fail:104.19.100.123

Jan 11 20:33:30.222 - [DEBUG] 104.25.131.96 fail:error('certficate is none, sni:hollyrollers.ru, top:dragon-dreamer.com',)

Jan 11 20:33:30.222 - [DEBUG] report_connect_fail:104.25.131.96

Jan 11 20:33:30.681 - [DEBUG] try connect 190.93.244.244

Jan 11 20:33:31.223 - [DEBUG] try connect 104.25.151.172

Jan 11 20:33:31.316 - [DEBUG] create_ssl update ip:190.93.244.244 time:624 h2:1 sni:greenleafhealing.com top:superx.gq

Jan 11 20:33:35.550 - [DEBUG] create_ssl update ip:104.25.151.172 time:4326 h2:1 sni:growbitonline.com top:movistar.gq

Jan 11 20:37:23.127 - [DEBUG] 104.16.233.137 _consume_single_frame:ConnectionResetError(), inactive time:243

Jan 11 20:37:23.127 - [DEBUG] 104.16.233.137 worker close:disconnect:ConnectionResetError()

Jan 11 20:37:26.311 - [DEBUG] 172.64.2.73 _consume_single_frame:ConnectionResetError(), inactive time:240

Jan 11 20:37:26.311 - [DEBUG] 172.64.2.73 worker close:disconnect:ConnectionResetError()

Jan 11 20:37:28.071 - [DEBUG] trigger get more worker

Jan 11 20:37:28.072 - [DEBUG] 104.16.26.46 close:get_timeout

Jan 11 20:37:28.074 - [DEBUG] 190.93.244.244 close:get_timeout

Jan 11 20:37:28.074 - [DEBUG] 104.25.151.172 close:get_timeout

Jan 11 20:37:28.079 - [DEBUG] try connect 172.64.132.40

Jan 11 20:37:28.576 - [DEBUG] try connect 104.25.160.222

Jan 11 20:37:28.719 - [DEBUG] create_ssl update ip:172.64.132.40 time:614 h2:1 sni:construyehogar.com top:superx.gq

Jan 11 20:37:29.193 - [DEBUG] create_ssl update ip:104.25.160.222 time:616 h2:1 sni:pusatinkubatorbayi.com top:c-term.tk

Jan 11 20:37:29.721 - [DEBUG] try connect 104.28.25.147

Jan 11 20:37:30.071 - [DEBUG] trigger get more worker

Jan 11 20:37:30.124 - [DEBUG] connect 104.28.25.147 fail:conn fail, sni:gaolvh3.cf, top:movistar.gq e:Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],) cost:403

Jan 11 20:37:30.124 - [DEBUG] report_connect_fail:104.28.25.147

Jan 11 20:37:30.195 - [DEBUG] try connect 104.19.198.107

Jan 11 20:37:30.836 - [DEBUG] create_ssl update ip:104.19.198.107 time:641 h2:1 sni:daniel-latta.review top:movistar.gq

Jan 11 20:37:31.125 - [DEBUG] try connect 104.28.79.77

Jan 11 20:37:31.837 - [DEBUG] try connect 141.101.122.140

Jan 11 20:37:32.069 - [DEBUG] trigger get more worker

Jan 11 20:37:32.866 - [DEBUG] create_ssl update ip:104.28.79.77 time:1740 h2:1 sni:bijuteriya74.ru top:movistar.gq

Jan 11 20:37:33.296 - [DEBUG] connect 141.101.122.140 fail:conn fail, sni:rhinofitnessco.com, top:flar.tk e:Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],) cost:1459

Jan 11 20:37:33.296 - [DEBUG] report_connect_fail:141.101.122.140

Jan 11 20:37:33.868 - [DEBUG] try connect 190.93.245.131

Jan 11 20:37:34.297 - [DEBUG] try connect 190.93.244.75

Jan 11 20:37:34.494 - [DEBUG] create_ssl update ip:190.93.245.131 time:625 h2:1 sni:corporateleggerelibri.tk top:superx.gq

Jan 11 20:37:35.495 - [DEBUG] try connect 104.24.182.7

Jan 11 20:37:36.133 - [DEBUG] create_ssl update ip:104.24.182.7 time:638 h2:1 sni:ufcreader.cf top:singlefly.tk

Jan 11 20:37:38.609 - [DEBUG] create_ssl update ip:190.93.244.75 time:4312 h2:1 sni:dumpsterrentalmacon.club top:mostlygood.ga

Jan 11 20:38:02.392 - [DEBUG] 104.19.198.107 _consume_single_frame:SysCallError(10053, 'WSAECONNABORTED'), inactive time:33

Jan 11 20:38:02.392 - [DEBUG] 104.19.198.107 worker close:disconnect:SysCallError(10053, 'WSAECONNABORTED')

**Comment by xxnet** [comment]
​代理用哪个模式？

**Comment by monkeyhai** [comment]
勾选的取消全局代理。
部分日志内容：
Jan 12 10:26:40.337 - [WARNING] roundtrip time:10065 transfer_no:625 send:32 status:602

Jan 12 10:26:40.645 - [WARNING] front retry /data?tid=626

Jan 12 10:26:40.646 - [WARNING] roundtrip time:10055 transfer_no:626 send:0 status:602

Jan 12 10:26:40.956 - [WARNING] front retry /data?tid=627

Jan 12 10:26:40.957 - [WARNING] roundtrip time:10065 transfer_no:627 send:0 status:602

Jan 12 10:26:41.161 - [WARNING] front retry /data?tid=628

Jan 12 10:26:41.161 - [WARNING] roundtrip time:10068 transfer_no:628 send:128 status:602

Jan 12 10:26:41.365 - [WARNING] front retry /data?tid=629

Jan 12 10:26:41.365 - [WARNING] roundtrip time:10072 transfer_no:629 send:328 status:602

Jan 12 10:26:41.674 - [WARNING] front retry /data?tid=630

Jan 12 10:26:41.674 - [WARNING] roundtrip time:10078 transfer_no:630 send:551 status:602

Jan 12 10:26:41.748 - [DEBUG] Conn session:dmlcxdmd conn:30 stop:recv fail.

Jan 12 10:26:41.748 - [DEBUG] remove conn_id:30

Jan 12 10:26:41.987 - [WARNING] front retry /data?tid=631

Jan 12 10:26:41.988 - [WARNING] roundtrip time:10089 transfer_no:631 send:50 status:602

Jan 12 10:26:42.197 - [WARNING] front retry /data?tid=632

Jan 12 10:26:42.197 - [WARNING] roundtrip time:10098 transfer_no:632 send:586 status:602

Jan 12 10:26:42.402 - [WARNING] front retry /data?tid=633

Jan 12 10:26:42.403 - [WARNING] roundtrip time:10103 transfer_no:633 send:889 status:602

Jan 12 10:26:42.611 - [WARNING] front retry /data?tid=634

Jan 12 10:26:42.611 - [WARNING] roundtrip time:10008 transfer_no:634 send:1144 status:602

Jan 12 10:26:42.919 - [WARNING] front retry /data?tid=635

Jan 12 10:26:42.920 - [WARNING] roundtrip time:10016 transfer_no:635 send:64 status:602

Jan 12 10:26:43.128 - [WARNING] front retry /data?tid=636

Jan 12 10:26:43.129 - [WARNING] roundtrip time:10023 transfer_no:636 send:2528 status:602

Jan 12 10:26:43.336 - [WARNING] front retry /data?tid=637

Jan 12 10:26:43.336 - [WARNING] roundtrip time:10029 transfer_no:637 send:919 status:602

**Comment by monkeyhai** [comment]
好了，谢谢
