### ISSUE TITLE
今天升级系统后IPV6又是FAIL了

### ISSUE THREAD

**Issue by NOoNE7** [XX-net/XX-Net#9449]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17063
os-system: Windows
os-version: 10.0.17063
os-release: 10
os-detail: Version:10-0; Build:17063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2900 ipv4:0 ipv6:2536
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 246
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by NOoNE7** [comment]
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win1711.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by askaXX** [comment]
根本就没开启，怎么可能正常

**Comment by NOoNE7** [comment]
怎么开启。。。。之前是没有问题的啊

**Comment by NOoNE7** [comment]
好了，学到了，没想到升级系统IPV6关闭了。。。。。。

**Comment by gjbg1989** [comment]
服务器名称 : win1711.ipv6.microsoft.com. 😱
![default](https://user-images.githubusercontent.com/13290970/34874867-c419c7da-f7d5-11e7-9ddb-5177c2277c79.png)

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，管理权限运行 netsh int ipv6 set teredo enterpriseclient default

**Comment by NOoNE7** [comment]
嗯，我这个就是1711我也不知道怎么回事，我按照那个指令运行了一遍，开机就好了
