### ISSUE TITLE
为什么在chrome上的隐身模式里可以上youtube，但是在正常浏览的模式下却不可以？

### ISSUE THREAD

**Issue by tinyperson** [XX-net/XX-Net#946]
一直有这个疑问。
![image](https://cloud.githubusercontent.com/assets/14156036/9715874/4c77a7b6-5597-11e5-8662-3fb3b788ba12.png)
![image](https://cloud.githubusercontent.com/assets/14156036/9715879/5928334a-5597-11e5-870a-2452b5ebeb62.png)
就像是上面这个样子。

但是，当用隐身模式的时候：
![1](https://cloud.githubusercontent.com/assets/14156036/9715953/048d36ea-5598-11e5-81cc-fdc5b1b6f774.png)

就像上图一样可以用了。

**Comment by yuliangyang** [comment]
ie设置了代理，而chrome的swichyomega没设置代理

**Comment by tinyperson** [comment]
发现设置为GoAgent PAC的时候是可以连接上，但是当设置为自动切换的时候就不可以了。

**Comment by yuliangyang** [comment]
自动切换更新下情景模式

**Comment by tinyperson** [comment]
@yuliangyang 
可以了！谢谢！
