### ISSUE TITLE
请检查浏览器代理设置。 可以登录tw.youtube.umm..

### ISSUE THREAD

**Issue by huanxiang0116** [XX-net/XX-Net#9463]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:4107
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:74 h2:1
scan-ip-thread-num: 10
ip-quality: 269
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
添加 *.deja.com 走 GAE ？

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9461

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
