### ISSUE TITLE
请检查浏览器代理设置

### ISSUE THREAD

**Issue by chacha321052** [XX-net/XX-Net#9469]
* 简单描述遇到的问题：从3.8.5升级到3.9.4，重新导入证书均无用，且之前的appid，重新配置都显示无效

* 做过哪些尝试：尝试购买X-tunnel，palpay被拒绝，这该怎么解决

* XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.9.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1619 ipv4:0 ipv6:1619
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:81 h2:0
scan-ip-thread-num: 10
ip-quality: 417
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
重新导入证书均无用——或许不是证书问题。点击有数字显示的插件图标，将未加载资源添加，走GAE
且之前的appid，重新配置都显示无效——不会吧😱
http://127.0.0.1:8085/?module=gae_proxy&menu=config 高级技巧： 通过文件配置 https://github.com/XX-net/XX-Net/wiki/GoAgent-manual-config 
manual.ini 内容
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid = xxx|yyy|zzz
;appid密码，无可不填
password =

**Comment by chacha321052** [comment]
appid这个已经解决了，  有数字显示的插件图标  是什么意思？

**Comment by gjbg1989** [comment]
代理插件 SwitchyOmega

**Comment by gjbg1989** [comment]
3.9.6 👍 https://github.com/XX-net/XX-Net/issues/9461

**Comment by chacha321052** [comment]
想试着改goproxy，按步骤来，到运行goproxy.exe时，提示can not excute,？？？？？？？

**Comment by gjbg1989** [comment]
不是运行 goproxy.exe ，是运行 goproxy-gui.exe

**Comment by chacha321052** [comment]
还是不行。。。一样的问题

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/34915204-c85ce11e-f95c-11e7-81ac-df731e79b9ac.png)

**Comment by chacha321052** [comment]
![default](https://user-images.githubusercontent.com/32815416/34915239-73f41f7e-f95d-11e7-9172-df0ad0955434.png)
不知道能不能看到

**Comment by gjbg1989** [comment]
能看到

**Comment by gjbg1989** [comment]
复制 R1632 目录下 gae.json 为 gae.user.json ，编辑后者可添加私有 AppID
系统 IPv6 隧道工作正常，运行 XX-NET 导出 IP ，全选、复制，结束进程 pythonw.exe（关闭浏览器：二者 8087 的证书不同），运行 goproxy-gui.exe ，在浏览器内打开 http://127.0.0.1:8087/ip.html ，左键左边窗口、右键粘贴，点选 IPv6 ，点击“写入到本地 json 文件”，完成。R1624 也有效😱

**Comment by gjbg1989** [comment]
😂添加*.deja.com走GAE：XX-Net 3.9.6，一切正常，你可以访问真正的互联网了。

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
