### ISSUE TITLE
ipv6.google.com not support GAE

### ISSUE THREAD

**Issue by cancelpj** [XX-net/XX-Net#9473]
使用macOS 10.13.2，已经安装Miredo正常启用ipv6，xx-net中能够获取ipv6 IP。

使用chrome 63最新版，在地址栏输入 https://www.google.com 能正常访问，但是输入关键词搜索到时候，浏览器状态栏显示“**正在等待ipv6.google.com的响应**“，然后就提示**连接超时**，日志中显示“_Jan 14 19:32:45.840 - [WARNING] IP:2607:f8b0:4007:1c::c host:ipv6.google.com not support GAE, server type:HTTP server (unknown) status:503_”字样。

manual.ini中有配置：
[hosts]
.google.com = direct
尝试屏蔽该项，问题依旧。

尝试升级到xx-net 3.9.6，问题依旧。

补充：刚启用ipv6的时候，google搜索是正常的，有几天没用笔记本，最近两天使用时出现该问题。代理访问其他网址正常（如youtube等）。

**Comment by xxnet** [comment]
​在出问题时，把GAE的日志贴出来分析

**Comment by cancelpj** [comment]
哦，因为日志上下文正常提示信息里面内容不相关，我就只贴出了报错部分的，然后几天后问题奇妙的消失了。截止目前，在用google搜索时，不会再跳转到ipv6.google.com等待响应。
