### ISSUE TITLE
IPV6的IP数量一直近几天一直减少，怎么办？

### ISSUE THREAD

**Issue by sakura00** [XX-net/XX-Net#9478]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:0 ipv6:315
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:3 h2:0
scan-ip-thread-num: 200
ip-quality: 440
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始

**Comment by sakura00** [comment]
解决了谢谢
