### ISSUE TITLE
是否每次有新版本xx-net都要重新導入SwitchyOmega

### ISSUE THREAD

**Issue by foho8080** [XX-net/XX-Net#9486]
是否每次有新版本xx-net都要重新導入SwitchyOmega(還有就是忘了怎樣導入SwitchyOmega)

**Comment by hcrcaaaa** [comment]
安装文件夹

**Comment by foho8080** [comment]
@hcrcaaaa 安装什麼文件夹

**Comment by gjbg1989** [comment]
软件下 SwitchyOmega 目录

**Comment by Emphasia** [comment]
SwitchyOmega备份的话，既然你在问这个问题应该是对SwitchyOmega的用途不是很了解，那还是建议每次都导入最新的备份。

导入备份（二选一）：
- 于XX-Net\SwitchyOmega目录下找到备份文件后通过从备份文件恢复导入
- 使用在线恢复功能导入：https://raw.githubusercontent.com/XX-net/XX-Net/master/SwitchyOmega/OmegaOptions.bak

**Comment by gjbg1989** [comment]
😂添加*.deja.com走GAE：XX-Net 3.9.6，一切正常，你可以访问真正的互联网了。
