### ISSUE TITLE
怒发一帖，我又回来了

### ISSUE THREAD

**Issue by zhuhaxixiong** [XX-net/XX-Net#9489]
之前使用3.8.5不知道怎么回事ipv6老是开不了，今天一怒之下删了所有安装包，重新下载了新版本3.9.6，首先导入switchOmega，然后在文件夹code\default\gae_proxy\local\ipv6_tunnel路径下法线了一个IPV6_note.TXT,按照这个文件里的cmd命令一步一步来，没想到最后IPV6竟然通了；要提示大家的是，这个文件的29行在设置Teredo服务器市故意给了一个报废的服务器，因此我们只需把服务器换位24行的服务器即可，最终29行为:netsh interface ipv6 set teredo client teredo.remlab.net
然后再执行下去，直到换算ipv4地址这一步，首先查看ipv4地址（cmd->ipconfig命令），然后转换为ipv6地址，转换完的第一个ipv6那一行就是ipv6地址，复制这个地址，修改本地连接的ipv6地址,子网前缀长度 48，同时将ipv6DNS修改，文件里已经给了几个DNS，我用的是第一个谷歌的DNS。继续执行到63行”#看看teredo状态是不是qualified“这一步，我的状态并不是qualified，而是dormant，于是我就没管这个，结果一直执行完，打开ipv6测试网页，发现测试结果还是不同，但是用小污龟测试却可以，于是过了一会测试就通过了，打开xx-net虽然是请检查代理设置，但google打开了。

**Comment by gjbg1989** [comment]
😱如此这般复杂？

**Comment by myjlpt** [comment]
teredo.remlab.net我这边就正常，其他的目前不稳定。

之前一段时间确实不正常。

**Comment by roc1010kmt** [comment]
ipv6速度快嗎？我這基本沒速度。
