### ISSUE TITLE
无法正常打开配置页面，也无法正常翻墙

### ISSUE THREAD

**Issue by sanriqing** [XX-net/XX-Net#9490]
* 是否试过最新的测试版本？
是的，使用版本为3.9.6
  

* 是否看过Issues区最近的讨论？
是的
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  是的没有相关问题

* 简单描述遇到的问题：
系统为win10，版本为1703 os内部版本15063.0 专业版
无法正常打开配置页面，也无法正常翻墙

* 做过哪些尝试：
重新安装其他版本（版本都试过了），检查过端口未被其他程序占用

* 请贴出对应模块的状态页
无法看到

* 请贴出相关的日志
无法看到

**Comment by gjbg1989** [comment]
删除 data 以外的任何目录与文件，重新解压。。。

**Comment by gjbg1989** [comment]
😂大象的鼻子为什么那么长？
