### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by lkhtty** [XX-net/XX-Net#9491]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:473 ipv4:0 ipv6:432
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:83 h2:0
scan-ip-thread-num: 10
ip-quality: 279
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
![qq 20180115193004](https://user-images.githubusercontent.com/33829657/34940489-a9152838-fa2a-11e7-8d11-46638921a8b8.png)
3.9.6使用一切正常，智能路由模式，但是一直显示这行字，有谁能解决下吗？

**Comment by gjbg1989** [comment]
如果代理插件图标上有数字，试试：点击该图标，选择、复制未加载项，
http://127.0.0.1:8085/?module=smart_router&menu=config 规则——走GAE的列表——粘贴并编辑——提交（网页底部）
![image](https://user-images.githubusercontent.com/13290970/34947108-18f67710-fa44-11e7-81c3-eb9b42aa358a.png)

**Comment by Emphasia** [comment]
可以参考：#9330

**Comment by lkhtty** [comment]
是不是修改了，今天一打开直接显示一切正常，什么也还没改动呢

**Comment by Emphasia** [comment]
3.9.4开始更新了验证方式，如果开了自动更新的话就自己升上去了吧

**Comment by gjbg1989** [comment]
😂 3.9.6——3.9.4

**Comment by gjbg1989** [comment]
中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6

**Comment by gjbg1989** [comment]
中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6

**Comment by gjbg1989** [comment]
😂添加*.deja.com走GAE：XX-Net 3.9.6，一切正常，你可以访问真正的互联网了。
