### ISSUE TITLE
help：请检查浏览器代理设置。

### ISSUE THREAD

**Issue by chopper93** [XX-net/XX-Net#9495]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:2555 ipv4:0 ipv6:967
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:69 h2:1
scan-ip-thread-num: 10
ip-quality: 307
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by ZhangYaqing0128** [comment]
找到问题了，先禁用第三方的代理切换插件（Proxy SwitchyOmega等），然后xx-net设置为全局通过智能路由代理，然后再打开http://127.0.0.1:8085，一切OK

**Comment by zhmars** [comment]
Smart Router 关闭了，google 能上，也会提示这个，之前的版本不会有这个提示，可能是这个版本的问题

**Comment by Emphasia** [comment]
可以参考：https://github.com/XX-net/XX-Net/issues/9330
也不能算BUG..只能说是提示没到位..Smart Router还在测试..等测试到位推正式版的时候会好好引导用户..

**Comment by chopper93** [comment]
谢谢各位老哥，已经可以用了，用的是ZhangYaqing0128 的方法

**Comment by gjbg1989** [comment]
添加*.deja.com走GAE：XX-Net 3.9.6，一切正常，你可以访问真正的互联网了。

**Comment by chipspark6** [comment]
用了0128的还是不行

**Comment by gjbg1989** [comment]
试试：http://127.0.0.1:8085/?module=smart_router&menu=config 规则——走GAE的列表——添加 *.deja.com ——提交（页面底部）
