### ISSUE TITLE
关于SWITCHOMEGA

### ISSUE THREAD

**Issue by NOoNE7** [XX-net/XX-Net#9499]
我使用的是XXNET加SWITCHOMEGA，今天更新3.96之后重新导入了备份文件，现在开启浏览器后默认代理使用的是SMART-ROUTER怎么办

**Comment by Emphasia** [comment]
所以你想说的是什么..

**Comment by NOoNE7** [comment]
那个连接不到网络，显示检查代理，每次还要手动切换proxy

**Comment by NOoNE7** [comment]
有什么办法固定成g proxy自动切换吗

**Comment by Emphasia** [comment]
选择GAEProxy保存就行
![20180116133112](https://user-images.githubusercontent.com/8478234/34973237-a097e906-fac1-11e7-893c-640a9e01c425.png)

**Comment by NOoNE7** [comment]
哦，谢谢了
