### ISSUE TITLE
Local URLFetch 'https://www.facebook.com/' failed

### ISSUE THREAD

**Issue by harryhkyy** [XX-net/XX-Net#95]
GoAgent状态信息
Property    Value
Sys Platform    win32
OS System   Windows
OS version  6.1.7601
OS release  7
OS detail   Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture    32bitWindowsPE
Browser Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
XX-Net Version  1.6.0
Launcher Version    1.2.0
GoAgent Version 3.1.43
Python Version  2.7.9
Proxy Listen    127.0.0.1:8087
working appids  harryhky|harryhkyy|harryhkyy2|harryhkyy3|harryhkyy4|harryhkyy5|harryhkyy6|harryhkyy7|harryhkyy8|harryhkyy9|harryhkyy10|harryhkyy11|harryhkyy12|harryhkyy13|harryhkyy14|harryhkyy15|harryhkyy16|harryhkyy17|harryhkyy18|harryhkyy19|harryhkyy20|harryhkyy21|harryhkyy22|harryhkyy23|harryhkyy24|harryhkyy25|harryhkyy26|harryhkyy27|harryhkyy28|harryhkyy29|harryhkyy30|harryhkyy31|harryhkyy32|harryhkyy33|harryhkyy34|harryhkyy35|harryhkyy36|harryhkyy37|harryhkyy38|harryhkyy39|harryhkyy40|harryhkyy41|harryhkyy42|harryhkyy43|harryhkyy44|harryhkyy45|harryhkyy46|harryhkyy47|harryhkyy48|harryhkyy49
Out of Quota appids 
Not Exist appids  
PAC URL http://127.0.0.1:8086/proxy.pac
Google IP   

Apr 01 11:16:32 - [DEBUG] FWD CONNECT clients1.google.com:443 with closed
Apr 01 11:16:32 - [INFO] GAE CONNECT www.facebook.com:443 
Apr 01 11:16:32 - [DEBUG] GAE CONNECT GET https://www.facebook.com/
Apr 01 11:16:32 - [DEBUG] ssl_pool.get:210.245.14.187 handshake:145
Apr 01 11:16:32 - [DEBUG] ssl conn_num:19
Apr 01 11:16:32 - [DEBUG] sort ip time:7
Apr 01 11:16:32 - [DEBUG] get ip:210.158.146.241 t:140
Apr 01 11:16:33 - [DEBUG] create_ssl update ip:210.158.146.241 time:154
Apr 01 11:16:34 - [DEBUG] ssl_pool.get:210.158.146.112 handshake:151
Apr 01 11:16:34 - [DEBUG] ssl conn_num:19
Apr 01 11:16:34 - [DEBUG] get ip:210.245.14.187 t:145
Apr 01 11:16:34 - [DEBUG] create_ssl update ip:210.245.14.187 time:158
Apr 01 11:16:36 - [DEBUG] ssl_pool.get:210.158.146.241 handshake:154
Apr 01 11:16:36 - [DEBUG] ssl conn_num:19
Apr 01 11:16:36 - [DEBUG] get ip:106.162.198.114 t:150
Apr 01 11:16:37 - [DEBUG] create_ssl 106.162.198.114 fail:timed out c:0 h:0
Apr 01 11:16:38 - [WARNING] GET no response https://www.facebook.com/ 
Apr 01 11:16:39 - [DEBUG] get ip:210.158.146.112 t:151

**Comment by xxnet** [comment]
有挺多人反馈了，我已经在研究，谢谢反馈

2015-03-31 23:17 GMT-04:00 harryhkyy <notifications@github.com>:

**Comment by xxnet** [comment]
请试试1.7版本

2015-03-31 23:47 GMT-04:00 Net XX <xxnet.dev@gmail.com>:
