### ISSUE TITLE
IPV6状态为fail，未能打开隧道适配器

### ISSUE THREAD

**Issue by AsortKeven** [XX-net/XX-Net#9504]
IPV6状态为fail，未能打开隧道适配器

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:3856 ipv4:0 ipv6:2496
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 322
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AsortKeven** [comment]
系统为win10，版本为3.9.6，原本是3.8.7，出现问题后更新成这个版本的，依然存在

**Comment by pendave** [comment]
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题，有人试下不？

**Comment by VideCorMeum** [comment]
https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows
下载第一个执行后重启
Prefer IPv4 over IPv6 in prefix policies
--

**Comment by AsortKeven** [comment]
@VideCorMeum 谢谢，解决了

**Comment by gjbg1989** [comment]
😂 中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6

**Comment by BBC202** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4793 ipv4:0 ipv6:4788
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by BBC202** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4793 ipv4:0 ipv6:4788
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 233
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by pendave** [comment]
请问这个原理是？为啥以前没有专门指出这个操作？
`中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6`
@VideCorMeum

**Comment by BBC202** [comment]
一时断开，一时连接！
用了V4优先也不行！

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4793 ipv4:0 ipv6:4631
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 309
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
use-ipv6: auto 改为只用 ipv6
netsh int ipv6 show teredo 贴运行结果

**Comment by pendave** [comment]
每次关机前或者主动去重启电脑前运行下这个，还不错哦：
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题，有人试下不？
