### ISSUE TITLE
从3.9.1手动升级到3.9.6变成请检查浏览器代理设置

### ISSUE THREAD

**Issue by 2609665** [XX-net/XX-Net#9509]
![qq 20180117133826](https://user-images.githubusercontent.com/20493163/35027712-2be6b0a2-fb8d-11e7-9275-6a2f4055f232.jpg)
从3.9.1手动升级到3.9.6 变成这样 

请检查浏览器代理设置。

浏览器代理设置 | Fail
CA证书状态(下载) | Fail

用SwitchyOmega全局模式就变正常 ,
用根据条件切换就变
请检查浏览器代理设置。
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
但是切换条件下的网站还是能上的,
就是XX状态页面的问题
虽然现在不影响FQ使用就是看着不舒服!

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9491

**Comment by 2609665** [comment]
@gjbg1989 我没用智能路由模式    这个设置也支持纯GAE模式?

**Comment by gjbg1989** [comment]
纯GAE模式——GAE-Proxy 自动切换？同样：如果代理插件图标上有数字，添加未加载项走GAE
![default](https://user-images.githubusercontent.com/13290970/35029408-c8f86766-fb95-11e7-8888-d5d13149f07b.png)

**Comment by 2609665** [comment]
我只开启了GAE Proxy模块~
SwitchyOmega情景模式是用的我自建的自动根据条件切换模式
没导入3.9.3版XX-Net目录下最新的SwitchyOmega的配置备份

**Comment by gjbg1989** [comment]
添加*.deja.com走GAE则：XX-Net 3.9.6，一切正常，你可以访问真正的互联网了。

**Comment by 2609665** [comment]
@gjbg1989 好的  非常感谢!!!

**Comment by hbsxwhb** [comment]
我的是3.9.4出现这个问题，这前的版本没有这问题，更新到3.9.6修复好了

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
