### ISSUE TITLE
下载最新的XX-Net-3.8.7，还是没有足够的ip，各路大神看看

### ISSUE THREAD

**Issue by yuzhicngrain** [XX-net/XX-Net#9512]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:50 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 100
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
下载最新的XX-Net-3.8.7，还是没有足够的ip——最新3.9.6，貌似扫描出的而不是下载新版来的😂
