### ISSUE TITLE
google appid一次申请满了的话，会有什么影响吗。那东西只是为了提供流量的吗

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#9524]
从本质上我并不知道google appid是做什么用的。唯一知道就是可以提供1g流量。已经申请过的appid所选择的语言功能，之后也是可以更改的吧？

**Comment by GoodSake** [comment]
本质上是一台连上了真互联网的google免费提供的服务器。google appid一次申请满了,这是啥意思哦。一个gmail账号申请了12个appid吗？appid的用途非常多。语言可以改吧，我还没改过。

**Comment by yuyistar** [comment]
@GoodSake 对一次12个，现在出问题了吗。为什么上那些网站都突然变成这不是私密链接了。。。之前没事呀。有证书

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9530#issuecomment-358533756

**Comment by sgricky** [comment]
现在是12个吗？我之前一个AppID申请了25个，理念上可以提供每24小时25GB的流量，对我来说是够够的了。
