### ISSUE TITLE
有时候突然会变成不是私密链接是怎么回事，可是证书没有问题呀

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#9526]
证书肯定是早就导入了。不过现在不能访问那些网站了

您的连接不是私密连接
攻击者可能会试图从 facebook.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_INVALID
 
自动向 Google 发送一些系统信息和网页内容，以帮助检测危险应用和网站。隐私权政策
重新加载隐藏详情
facebook.com 通常会使用加密技术来保护您的信息。Google Chrome 此次尝试连接到 facebook.com 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 facebook.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Google Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 facebook.com，因为此网站发送了 Google Chrome 无法处理的杂乱凭据。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9530#issuecomment-358533756

**Comment by yuyistar** [comment]
@gjbg1989 就是建立一个tertdo.bat然后运行netsh那句话吧。我执行了。显示确定，但是变成尚未建立连接了。。。。
之前证书的那个问题自己好了。不过现在运行完那句话之后，变成了尚未建立连接啦

**Comment by gjbg1989** [comment]
百里挑一🙃

**Comment by gjbg1989** [comment]
尚未建立连接——主动创造条件检测：
1、（结束进程pythonw.exe、）禁用再启用网络
2、#8915 
3、（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。

**Comment by yuyistar** [comment]
@gjbg1989 https://github.com/XX-net/XX-Net/files/1544536/teredo.zip
这个文件不能下载呀
我昨天只是单独运行了这句话netsh int ipv6 set teredo enterpriseclient default，用bat。但是文件夹里面并没有teredo这个软件，结果就尚未建立链接了。。之前正常，是运行那句话造成的？到目前都没有好

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息
