### ISSUE TITLE
AppID流量已经用完

### ISSUE THREAD

**Issue by benpaodewoniu** [XX-net/XX-Net#9528]
我自己申请了一个AppID后，今早一打开就显示次AppID流量已经用完（我还没开始用，不知道怎么回事），但是自己的AppID流量用完后，再部署新的不成功，私以为是因为无法连接外网，导致自己的google账号也没法登录，所以不成功，现在我想用公共ID上网，但是不知道该如何操作，已经百度了好久。

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，编辑 config.ini 或 manual.ini ，将如下内容的 appid 前添加;（注释以停用）
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid =xxx|yyy|zzz
;appid密码，无可不填
password =

**Comment by benpaodewoniu** [comment]
楼上是解决方案
