### ISSUE TITLE
firefox tumblr登陆出现错误

### ISSUE THREAD

**Issue by WetD** [XX-net/XX-Net#9530]
Public-Key-Pins：该网站使用的证书不是由预设根证书库中的证书签发。为了避免意外损坏，已忽略指定的头。

**Comment by gjbg1989** [comment]
3.9.6版 Smart-Router 登录貌似没问题

**Comment by WetD** [comment]
多刷新的好久居然自己登陆进去了orz

**Comment by gjbg1989** [comment]
😂网速慢或断所致？

**Comment by gjbg1989** [comment]
使用ping超时的微软服务器或许更稳定！(win7除外？) 管理权限运行
netsh int ipv6 set teredo enterpriseclient default
