### ISSUE TITLE
有两个问题

### ISSUE THREAD

**Issue by NOoNE7** [XX-net/XX-Net#9532]
第一个是之前的APPLEID想要删除要怎么做，删除之后是不是就是只能创建11个APPLEID了，删除后XXNET用不用做什么操作？
第二个问题是现在我想体验使用SMARTROUTER，该怎样配置呢？

**Comment by gjbg1989** [comment]
好奇怪😱
1、结束进程 pythonw.exe，编辑 config.ini 或 manual.ini ，删除 appid 
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid = xxx|yyy|zzz
;appid密码，无可不填
password =
2、删除之后是不是就是只能创建11个APPLEID了——貌似不是
3、使用SMARTROUTER——3.9.6版导入 XX-Net 目录下的 OmegaOptions.bak ，右键系统状态栏 XX-Net 图标“取消全局代理”，代理插件选用 Smart-Router ，或需
http://127.0.0.1:8085/?module=smart_router&menu=config 规则——走GAE的列表——添加 *.deja.com ——提交（页面底部）

**Comment by gjbg1989** [comment]
😂有一个问题，为什么要删除某 appid ？

**Comment by NOoNE7** [comment]
因为一开始是新手，然后都是默认的，现在想改成好记一点的😁

**Comment by NOoNE7** [comment]
我启用smartrouter之后是不是要保持xxnet运行啊，在未打开xxnet情况下显示请检查代理设置

**Comment by gjbg1989** [comment]
是不是要保持xxnet运行——废——话😂

**Comment by gjbg1989** [comment]
未打开xxnet情况下，代理插件选择“直接连接”

**Comment by NOoNE7** [comment]
哦哦哦，懂了，😂
