### ISSUE TITLE
switchyomega使用智能路由浏览器代理设置和浏览器证书报错

### ISSUE THREAD

**Issue by chipspark6** [XX-net/XX-Net#9533]
使用GAE-PROXY就是正常的，请问是为什么？

**Comment by gjbg1989** [comment]
试试：http://127.0.0.1:8085/?module=smart_router&menu=config 规则——走GAE的列表——添加 *.deja.com ——提交

**Comment by chipspark6** [comment]
楼上的试了..不行

**Comment by chipspark6** [comment]
3.9.6版本

**Comment by gjbg1989** [comment]
使用SMARTROUTER——3.9.6版导入 XX-Net 目录下的 OmegaOptions.bak ，右键系统状态栏 XX-Net 图标“取消全局代理”，代理插件选用 Smart-Router ，或需
http://127.0.0.1:8085/?module=smart_router&menu=config 规则——走GAE的列表——添加 *.deja.com ——提交（页面底部）

**Comment by chipspark6** [comment]
我是按楼上说的操作的..

**Comment by chipspark6** [comment]
启用smartrouter以后所有网页都打不开了，提示代理出错

**Comment by gjbg1989** [comment]
3.9.6版 FireFox 及 chrome 均正常😂

**Comment by gjbg1989** [comment]
走GAE的列表——添加代理插件图标数字所列的 *****

**Comment by hbsxwhb** [comment]
@gjbg1989    ，Smart Router 走gae规则，这里如何填写，如谷歌*.google.com.*，是这么写吗，不懂

**Comment by gjbg1989** [comment]
*.deja.com，一行一个，回车或换行

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
