### ISSUE TITLE
显示请检查浏览器设置

### ISSUE THREAD

**Issue by xxh121** [XX-net/XX-Net#9536]
不知道为什么从好几天前起xx-net就不行了，一直显示请检查浏览器设置，而且状态栏里的所有代理点了都没反应

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4863 ipv4:0 ipv6:2623
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:68 h2:0
scan-ip-thread-num: 10
ip-quality: 292
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
导入 XX-Net 下的 OmegaOptions.bak
XX-Net 取消全局代理、代理插件选择 GAE 自动切换，添加 *.deja.com 及其他未加载资源走 GAE

**Comment by dahai058** [comment]
昨天重新升到3.9.6 没做任何操作。只选择了全局通过智能路由，虽然页面显示请检查浏览器代理设置但正常FQ，上油管流畅点播720p直播360p

**Comment by xxh121** [comment]
装了SwitchyOmega插件，然后就好了。。。

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
