### ISSUE TITLE
3.96 自检一切正常，但就是连不上

### ISSUE THREAD

**Issue by mkcczh** [XX-net/XX-Net#9537]
早上还用的好好的，突然下午就连不上了，自检的状态一切正常，浏览器显示等待网站响应，看debug出下面的错误，贴得有点长，望谅。有遇到一样问题的吗？请帮忙，谢谢！

**Comment by mkcczh** [comment]
诊断信息如下
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:1567
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:8 h2:0
scan-ip-thread-num: 200
ip-quality: 359
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
Appids_Out_Of_Quota: true 貌似流量玩完

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9528#issuecomment-358529411

**Comment by mkcczh** [comment]
我有10个appid，每个每天有1G，也有10G啊，从来没有试过用完，现在个人的appid流量让公用了吗？
但今天一早打开也是一样，没有流量了。难道被盗用了？！

**Comment by mkcczh** [comment]
查了下appengine.google.com，只有第一个appid用完了，其他9个都没有用过，这是怎么回事？我全部配置进xxnet了，自检页面也有全部10个id。有人知道怎么办吗？

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，检查 config.ini 或 manual.ini ，是否有10个 appid
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid = xxx|yyy|zzz
;appid密码，无可不填
password =

**Comment by mkcczh** [comment]
看了 config.ini，10个appid都在；保险起见，在manual.ini里面再重新复制一遍config的 appid内容，再重新部署和配置了一次，希望不要再只用一个的流量，看这两天用得怎样再反馈，谢谢了gjbg1989！

**Comment by mkcczh** [comment]
经过这几天的使用，终于正常了。谢谢！
