### ISSUE TITLE
Win 10 下 XX-NET 小图标总是隐藏

### ISSUE THREAD

**Issue by AaronLucas** [XX-net/XX-Net#9538]
* 简单描述遇到的问题：
Win 10 下 XX-NET 小图标总是隐藏

* 做过哪些尝试：
本来不想说的,但看老大开始加入版本本地删除管理,也想提提自己的看法.
每逢XX-NET更新,右侧小图标就被默默的隐藏了.虽然是个小问题,但重是要去设置也挺麻烦.
究其原因是不是运行路径发生了改变?
有没有简单的方法解决. 比如,可否考虑吧python单独独立出来一个目录,毕竟这个不是时常更新.  吧python目录移到Code同级,也不要在目录上加版本号了.更新体积也会缩小很多(只不过一但python更新,替换起来也会变麻烦)

**Comment by gjbg1989** [comment]
😱Win 10 下 XX-NET 小图标总是隐藏——乃 Win 10 系统的特性，右键——状态栏右边最前的图标——任务栏设置——选择那些图标显示在任务栏上——将 pythonw.exe 打开
其他任何程序图标显示也如此。。。

**Comment by gjbg1989** [comment]
XX-NET自动更新——程序路径发生了改变（路径为版本号）——自己检查下就知道😂
不改变路径——手动下载解压到默认路径😱

**Comment by gjbg1989** [comment]
有没有简单的方法解决. 比如,可否考虑吧python单独独立出来一个目录,毕竟这个不是时常更新. 吧python目录移到Code同级,也不要在目录上加版本号了.更新体积也会缩小很多(只不过一但python更新,替换起来也会变麻烦)——😱首次使用的咋办？

**Comment by xx-Chen** [comment]
python单独独立出来一旦更新没法和code版本配套结果会一团糟.
简洁易用为主。先解决温饱。
