### ISSUE TITLE
文件名、目录名或卷标语法不正确

### ISSUE THREAD

**Issue by jdfq** [XX-net/XX-Net#9549]
使用win7开启ipv6教程中的的方法，运行这个命令时：
netsh int ipv6 add route ::/0 "win10.ipv6.microsoft.com" metric=1
提示：
文件名、目录名或卷标语法不正确

**Comment by syjy2** [comment]
我也是这样~

**Comment by AnyWAT** [comment]
貌似组策略法？不建议。
初次使用，试试软件目录内的 enable_ipv6.bat
