### ISSUE TITLE
可以连接google可是配置页打不开

### ISSUE THREAD

**Issue by liushuiguadanbo** [XX-net/XX-Net#9554]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。
   

http://127.0.0.1:8085/?module=gae_proxy&menu=status这个网页打不开
无法访问此网站
127.0.0.1 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by gjbg1989** [comment]
XX-Net“取消全局代理”，代理插件选择： GAE-Pro自动切换
添加 127.0.0.1 走直接连接

**Comment by liushuiguadanbo** [comment]
大佬 我把右下角的图标隐藏了 没法调  我添加走直连以后也不好用

**Comment by gjbg1989** [comment]
😱那大佬你想干什么？

**Comment by liushuiguadanbo** [comment]
不是的大佬=。=其实是我可能在修理的过程中下了一个新的3.7.6的安装包覆盖了  然后现在是手机连电脑的wifi不能翻也不能上网。。。我在想是不是设置页面有问题。，。。比如远程那个没开。。。

**Comment by gjbg1989** [comment]
手机电脑没玩过，逃👌

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/35179241-510aeab0-fdd1-11e7-909c-1acb79be95f3.png)

**Comment by gjbg1989** [comment]
proxy: disable ——XX-Net“取消全局代理”

**Comment by liushuiguadanbo** [comment]
emmmm更新了一下chrome结果好用了。。。
