### ISSUE TITLE
ipv6失败 teredo：qualified

### ISSUE THREAD

**Issue by jaydinga** [XX-net/XX-Net#9555]
之前ipv6用的好好的，今天就不行了。
现在是teredo的状态是qualified，但是ipv6 status一直是failure。试过了那个微软的恢复设置的程序，也试过teredo.exe这个工具设置，都是失败的。不知道问题出在哪里了...

XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
gws-ip-num: total:0 ipv4:0 ipv6:0——完全不像——之前ipv6用的好好的，今天就不行了。

**Comment by pendave** [comment]
这个应该有用：
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

**Comment by jaydinga** [comment]
今天再开电脑能用了。谢谢各位。可能是昨天teredo很不稳定。@gjbg1989 我贴的这个是重新下载xxnet的，所以没有之前的ip记录
