### ISSUE TITLE
在 SSH 连接的 Ubuntu  VPS  下面如何运行 xx-net  ? 

### ISSUE THREAD

**Issue by kissxrl** [XX-net/XX-Net#956]
?? 谢谢了

系统是  Ununtu 14.04  python  什么都已经安装了..可以正常的跑 Goagent  3.23, 

root@default:/opt/XX-Net-2.0.5# sudo ./start.sh

Traceback (most recent call last):
  File "launcher/start.py", line 23, in <module>
    if X_is_running():
  File "launcher/start.py", line 19, in X_is_running
    p = Popen(["xset", "-q"], stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

root@default:/opt/XX-Net-2.0.5#

**Comment by aOJzQT** [comment]
已修改，发了[pull request](https://github.com/XX-net/XX-Net/pull/960)，请@xxnet 处理

**Comment by xxnet** [comment]
已经merge，感谢aOJzQT

2015-09-08 22:08 GMT+08:00 aOJzQT <notifications@github.com>:

**Comment by kissxrl** [comment]
2.0.5  版本会出现问题....但是用   2.3.0  就可以正常启动呢..

但是启动后      scaning ip thread num	0   这里一直都是 0


Property	Value
Google IP num	3913
100th IP handshake(ms)	100
connected link(帮助)	0,0
scaning ip thread num	0
block stat(帮助)	OK

**Comment by aOJzQT** [comment]
2.0.5的release中
[start.py](https://github.com/XX-net/XX-Net/blob/d90ca19169b64be8ed658ec987a027c156932f71/launcher/start.py#L19)没有设置shell=True，或者捕获异常，所以某些情况下会导致启动异常。

2.3.0版本中xx老大已经捕获了这里的异常，所以没有问题了。你如果坚持在无图形的VPS上用2.0.5版本，需要自己改一下，`p = Popen(["xset", "-q"], stdout=PIPE, stderr=PIPE, shell=True)`，或者捕获异常

**Comment by kissxrl** [comment]
换了个电脑...系统是 Ubuntu  14.04 的.....以前那个主机老是封我的端口....
包什么的都安装了...
但是运行提示..   
我已经安装了..

apt-get install python-dev
apt-get install libffi-dev
apt-get install python-pip
pip install pyOpenSSL


 sudo ./XX-Net-2.0.5/start.sh
Sep 10 13:16:55 - [DEBUG] start confirm_xxnet_exit
Sep 10 13:16:55 - [ERROR] start module gae_proxy fail:No module named cryptography.hazmat.bindings.openssl.binding


 sudo ./XX-Net-2.3.0/start.sh
Sep 10 13:18:12 - [DEBUG] start confirm_xxnet_exit
Sep 10 13:18:12 - [ERROR] start module gae_proxy fail:No module named cryptography.hazmat.bindings.openssl.binding
Traceback (most recent call last):
  File "/opt/XX-Net-2.3.0/launcher/module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)

**Comment by xxnet** [comment]
google
python No module named cryptography.hazmat.bindings.openssl.binding
得到答案。

参考这里：
http://raspberrypi.stackexchange.com/questions/28176/python-and-openssl-error-on-import

安装：
sudo pip install libffi-dev
或
sudo apt-get install libffi-dev
然后：
pip install cryptography

2015-09-11 1:25 GMT+08:00 kissxrl <notifications@github.com>:
