### ISSUE TITLE
广西柳州市交警的吃相。

### ISSUE THREAD

**Issue by holiday137** [XX-net/XX-Net#9564]
在新浪发都被吞了，我知道没有用，就是气不过！
身为一个程序员忍不了了，让大家看看柳州的交警吃相！！！！！！
柳州12月突然是电动三轮车上路直接罚500，一个三线城市别人一月才赚多少钱？现在一月20日干脆连别人停在自己店门口的电动三轮车也直接拖走了，20多人一起来不怕你反抗，说什么占道，怎么做生意，这就是万众创业？浙江也就是罚20-50，柳州一个破城市凭什么罚500，周围都挨罚500，有的人好像挨罚5000，准备告交警队了。交警队年底了每星期听说都有奖金，年底还有年终奖。

**Comment by rothen80** [comment]
兄弟 你注册个twitter账号到上面去说吧 在这发一点意义也没有

**Comment by GoodSake** [comment]
文字可信度太低，下次记得拍视频发youtube。

**Comment by myjlpt** [comment]
交警应该不会。到底是交警还是城管。 好像10月份就把步行道划归“城管”了。拖车的江苏这边几乎都是城管。LS说的对，注册个推特吧。

**Comment by holiday137** [comment]
爱怎么样就怎么样吧，跟我无关，你们就麻木吧。

**Comment by myjlpt** [comment]
@holiday137 可能大部分人到不是麻木。其实是无奈。没有办法。老百姓困难的活着。用什么去反抗这种非法行政呢？或者换句话说“在中国，老百姓维权成本太高了”。什么123XX其实没用的，只要涉及到政府违法，结果只能是一个，政府合法，你违法（哪怕你不违法，对方错误执法，越权执法等等等）。甚至不惜自损形象，捏造事实，选择性录像等。已经是常态。
