### ISSUE TITLE
Mac不打开XX-Net就上不了网，如何解决？

### ISSUE THREAD

**Issue by AlexanderShang** [XX-net/XX-Net#9571]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by GoodSake** [comment]
?

**Comment by Emphasia** [comment]
不会是XX-Net开了全局然后XX-Net没启动所有的流量都被拦下来了吧？猜测..

**Comment by AlexanderShang** [comment]
怎么关闭全局呢？

**Comment by AlexanderShang** [comment]
请各位大佬帮帮忙。。

**Comment by Emphasia** [comment]
没用过MAC，但MAC应该也在上面有个XX-Net的图标？里面菜单可选是全局还是啥的..？

**Comment by AlexanderShang** [comment]
<img width="218" alt="qq20180121-184840 2x" src="https://user-images.githubusercontent.com/35128091/35193331-dc322d78-fedb-11e7-8cbb-46dc890ce724.png">

**Comment by Emphasia** [comment]
对呀 就是这个 选成disable

**Comment by AlexanderShang** [comment]
但是一旦将XX-Net退出，其他软件就会让检查网络设置。

**Comment by Emphasia** [comment]
选成disable以后退出XX-Net还是会其他软件无法联网？

**Comment by AlexanderShang** [comment]
不会了

**Comment by Emphasia** [comment]
然后你要在浏览器里用的话就参考：https://github.com/XX-net/XX-Net/wiki/How-to-use#mac%E7%B3%BB%E7%BB%9F

**Comment by AlexanderShang** [comment]
好的，谢谢大佬！！

**Comment by lovexinqq** [comment]
@AlexanderShang 你能在Mac下配置成功啦嘛。。。求指导啊。我配置了好久都还是不能FQ

**Comment by mowenbole** [comment]
哈喽，我和你问题是你一样的，我也是昨天才用xx-net，然后刚发现我mac系统连不上网了，如果不打开xx-net，你是怎么解决的？？？ @AlexanderShang

**Comment by xxnet** [comment]
估计是退出时没有恢复系统的代理设置。
你试试在退出前取消全局代理模式
