### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by Gamehu** [XX-net/XX-Net#9575]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:92 ipv4:0 ipv6:81
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:32 h2:1
scan-ip-thread-num: 10
ip-quality: 337
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by Gamehu** [comment]
各位大神反反复复折腾几次了 老是浏览器代理设置问题 求解

**Comment by gjbg1989** [comment]
XX-Net 选“取消全局代理”，代理插件选“GAE自动切换”，添加 *.deja.com 或其他未加载资源走 GAE

**Comment by gjbg1989** [comment]
多次刷新或重载控制页，或换服务器，或（结束进程pythonw.exe、）禁用再启用网络稍侯即🆗

**Comment by sucymoon** [comment]
可以说得更详细吗？ “代理插件选“GAE自动切换”，添加 *.deja.com 或其他未加载资源走 GAE”在哪里设置

**Comment by gjbg1989** [comment]
😱浏览器代理插件

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9330
