### ISSUE TITLE
帮忙 解释一下

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#9579]
XX-Net Status:

sys-platform: x86, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:593 ipv4:0 ipv6:581
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 351
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by GoodSake** [comment]
ipv6-status: Fail

**Comment by xiaoteai** [comment]
ipv6 批处理 怎么都弄不好

**Comment by GoodSake** [comment]
怎么弄不好？

**Comment by xiaoteai** [comment]
请看 
![kuy wj z q kj 2hhyb 25](https://user-images.githubusercontent.com/10782704/35225723-04ed2dc4-ffc4-11e7-9b3b-8927d55f87cd.jpg)
win7 根本没有 ipv6自动转换

![bds7u 2 ej9no qet rlqm3](https://user-images.githubusercontent.com/10782704/35225862-63059f7c-ffc4-11e7-8a1d-611887a55489.jpg) haiyiou还有这个 怎么成了 公共ID 了 是不是 有人帮我的 ID 泄露了

**Comment by GoodSake** [comment]
哈哈哈

**Comment by gjbg1989** [comment]
win7 根本没有 ipv6自动转换——推敲下网文开始那句话
还有这个 怎么成了 公共ID 了 是不是 有人把我的 ID 泄露了——泄露？不是那啥蛋还有谁？😂

**Comment by gjbg1989** [comment]
config.ini 或 manual.ini 内有如下内容？
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid = xxx|yyy|zzz
;appid密码，无可不填
password =

**Comment by Emphasia** [comment]
显示公共ID是因为没检测到你有配置私人的ID，要么是没配置，要么是配置错了。

**Comment by gjbg1989** [comment]
😱 win7 根本没有 ipv6自动转换 😱
😡 https://github.com/XX-net/XX-Net/issues/9418 😡

**Comment by pendave** [comment]
`win7 根本没有 ipv6自动转换` 对的，这个并不影响忽略就是！

这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

**Comment by lolipopsq** [comment]
<html>
<body>

别折腾XX-NET了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
