### ISSUE TITLE
为什么我可以删除wiki

### ISSUE THREAD

**Issue by balalaXD** [XX-net/XX-Net#9589]
我删除了中文文档wiki,  可是为什么我能删掉， 我只是好奇的点了一下QAQ

**Comment by GoodSake** [comment]
?

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/35272981-e709110c-0071-11e8-8cb0-0803991df5f0.png)

**Comment by GoodSake** [comment]
真好玩，我也去删了几个page，哈哈哈！

**Comment by GoodSake** [comment]
你们能看到我的杰作吗？还是只有我看到了自己的版本。。。哈哈哈！

**Comment by balalaXD** [comment]
我已经恢复回去了, 不要捣乱啊😲

**Comment by gjbg1989** [comment]
@xx-net 😱

**Comment by GoodSake** [comment]
你只是增加了一个新版本而已，reversion没变回去哦，哈哈哈！

**Comment by onplus** [comment]
警告！
