### ISSUE TITLE
从家里换到酒店后Miredo就一直黄灯了

### ISSUE THREAD

**Issue by eljake58** [XX-net/XX-Net#9590]
之前用家里的wifi一直好好的，现在miredo黄灯，IPV6 fail，请教是怎么回事啊，谢谢

**Comment by gjbg1989** [comment]
参考：Windows系统网络（公司家庭2地）换了，貌似各用各的 good_ip.txt 或 XX-Net 为好（先完全复制，再各归各。。。）

**Comment by lolipopsq** [comment]
<html>
<body>

别折腾XX-NET了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by eljake58** [comment]
@gjbg1989 还是不太明白啊

**Comment by gjbg1989** [comment]
😂参考、类比，非windows系统盲，逃。。。

**Comment by eljake58** [comment]
mac系统，请教懂的朋友解答，感觉应该和系统关系不大啊

**Comment by gjbg1989** [comment]
😂还是不明白啊

**Comment by eljake58** [comment]
help, anyone knows?
