### ISSUE TITLE
想确认一下，是不是用xx-net无法使用twitter搜索？

### ISSUE THREAD

**Issue by akiritoa** [XX-net/XX-Net#9593]
好像是在ipv4不能用之后就不能在twitter搜索内容了

**Comment by pendave** [comment]
是的，我用twitter的时候就换其他SS代理或者免费代理就可以显示search结果了，XX-net上twitter就是一种被限制的状态不出现结果的！

**Comment by northsheep** [comment]
同问，YouTube 评论经常加载不出来

**Comment by zhencaihao** [comment]
好像17年国庆前都正常。之后twitter只能搜索用户，其他的都搜不出来。不知道twitter和GAE是谁屏蔽谁。

**Comment by shipbk** [comment]
换成手机推特版就可以搜索了

**Comment by lolipopsq** [comment]
<html>
<body>

别折腾XX-NET了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by lazureice** [comment]
试了一下，确实如此。用xx-net没有结果，换其他的就有结果。
不过楼上的youtube评论区倒是没出现不能加载的情况。（当然，我没测几组。）

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/8122#issuecomment-342727674
