### ISSUE TITLE
今天刚升级3.8.5，用一会儿ipv6就掉了，然后重启xxnet就又可以用了怎么回事

### ISSUE THREAD

**Issue by azsora** [XX-net/XX-Net#9596]
这个是teredo的参数，用的是教程默认的配置
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : cone
NAT 特殊行为   : UPNP: 是，PortPreserving: 否（PS：不知道为什么端口保护是否）

这个是xxnet的诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5214 ipv4:0 ipv6:1986
ipv4-status: OK
ipv6-status: OK
connected-link: new:10 used:0
worker: h1:1 h2:0
scan-ip-thread-num: 200
ip-quality: 461
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

这是在xxnet无法翻阅之后重启了才可以，并且如果选择全局代理，xxnet的控制页面无法打开，CA证书导入了，但是下次启动仍然显示未导入

**Comment by GoodSake** [comment]
估计是与teredo服务器的连接被干扰了，把上网的网卡禁用后再启动就可以了。

**Comment by way7539512** [comment]
我是只重启xxnet，没有断开网络连接，但是这样又可以使用了，这样还需要把无线网卡禁用在启动嘛 @GoodSake

**Comment by way7539512** [comment]
并且测试xbox网络，延迟达到400毫秒，丢包率最高达到48%

**Comment by gjbg1989** [comment]
proxy_state: Fail
ca_state: Fail——2项错误也能正常使用？
一般：不用全局、只用“取消全局代理”，由代理插件控制
无线网络试试禁用网卡的 IPv6 协议
多次刷新或重载控制页，或换服务器，或（结束进程pythonw.exe、）禁用再启用网络

**Comment by way7539512** [comment]
我刚才是取消全局用chrome上插件代理能上网，全局通过IE也可以，只是上面始终显示检测代理，并且在证书和浏览器代理哪里一直是fail

**Comment by way7539512** [comment]
@gjbg1989 网络的ipv6已经禁用，但是重启软件就能上网，只是这些数据不对

**Comment by gjbg1989** [comment]
3.8.5 时扩展如 Disconnect 使用 white site 也 proxy_state: Fail ca_state: Fail 使用 black site 则🆗

**Comment by lolipopsq** [comment]
<html>
<body>

别折腾XX-NET了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by gjbg1989** [comment]
保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop
