### ISSUE TITLE
我的XX-Net 3.8.7非常慢

### ISSUE THREAD

**Issue by tooyangtoonaive** [XX-net/XX-Net#9598]

**Comment by lolipopsq** [comment]
<html>
<body>

别折腾XX-NET了，推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by GoodSake** [comment]
gfw的干扰严重速度就慢了。

**Comment by szwuzy** [comment]
3.9.6也慢  不知何故。manual.ini 调整不知是否有效？

**Comment by tooyangtoonavie** [comment]
@xxnet 
因透露了不必要的信息，请管理员删除此issue，谢谢

**Comment by gjbg1989** [comment]
😱貌似管理员也只能是关闭？解铃还需系铃人，自己编辑或删除才是正道？

**Comment by xxnet** [comment]
​appid 没有保密的必要
