### ISSUE TITLE
移植python3 socket默认bytes问题

### ISSUE THREAD

**Issue by inksnw** [XX-net/XX-Net#9602]
在simple_http_client.py中,python3版本这样写
                    data = sock.recv(8192)
                    if isinstance(data, bytes):
                        data = data.decode()
但是,类似这样的data: b'HTTP/1.1 200 OK\r\nContent-Type: image/gif\r\nX-Cloud-Trace-Context: 0405
5e7abe7c625b41ee1342cde616fe\r\nDate: Wed, 24 Jan 2018 17:37:40 GMT\r\nServer: G
oogle Frontend\r\nContent-Length: 782\r\nAlt-Svc: hq=":443"; ma=2592000; quic=51
303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443";
ma=2592000; v="41,39,38,37,35"\r\n\r\n\x03\x0c\xadT\xdd\x8a\xdbF\x14\xbe7\xec;\x
9cz)\xec\x12\xcb\x92\xd6\xbb\xaeQ$\xc1\xa6tI\xa0\x81\xa51\xa4\x10\xca2\x9a9\x96\
x86\x1d\x8d\x94\x99\xb1\x1dgi\xc9\x13\xb4w\xb9\xcdK\x14z\x95\x.....' 
这种的\r\n\r\n后面的似乎不是用utf-8编码的,用decode会报错,这个怎么办呢,求助一下

**Comment by xxnet** [comment]
​如果不是用来显示的，那么就没有必要用utf-8

**Comment by inksnw** [comment]
因为后续有类似self.read_buffer +data,  find('\r\n)的操作,如果把self.read_buffer.encode()这样后面很多用到的地方都要改,而且不好实现Python2,3通用

**Comment by SeaHOH** [comment]
不要 decode，直接用 http.client.parse_headers 来解析。

**Comment by SeaHOH** [comment]
或者 ` find(b'\r\n)` 好像也行。
