### ISSUE TITLE
昨天还能连接 今天就没有可用IP了。。

### ISSUE THREAD

**Issue by LeoWang0812** [XX-net/XX-Net#961]
GAEProxy状态信息

系统版本

Property	Value
XX-Net Version	2.3.0
Python Version	2.7.9
Sys Platform	win32
OS System	Windows
OS version	6.1.7601
OS release	7
OS detail	Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
language	zh_CN
architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	5
状态

Property	Value
Google IP num	3000
100th IP handshake(ms)	1087
connected link(帮助)	9,1
scaning ip thread num	50
block stat(帮助)	OK
Appid

Property	Value
working appids	xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Out of Quota appids	
Not Exist appids	

日志信息
Sep 09 11:37:47 - [DEBUG] create_ssl 173.194.27.231 fail:timed out cost:4021 h:0
Sep 09 11:37:47 - [DEBUG] create_ssl 83.100.221.244 fail:timed out cost:4014 h:0
Sep 09 11:37:47 - [DEBUG] create_ssl 199.87.241.48 fail:timed out cost:4013 h:0
Sep 09 11:37:47 - [DEBUG] create_ssl 194.78.99.32 fail:timed out cost:4014 h:0
Sep 09 11:37:47 - [DEBUG] create_ssl 173.194.2.179 fail:timed out cost:4000 h:0
Sep 09 11:37:48 - [DEBUG] create_ssl 212.188.10.244 fail:timed out cost:4003 h:0
Sep 09 11:37:48 - [DEBUG] get enough conn for gae
Sep 09 11:37:48 - [DEBUG] get enough conn for gae
Sep 09 11:37:48 - [DEBUG] get enough conn for gae
Sep 09 11:37:48 - [DEBUG] get enough conn for gae
Sep 09 11:37:48 - [DEBUG] get enough conn for gae
Sep 09 11:37:48 - [DEBUG] get enough conn for gae
Sep 09 11:37:49 - [DEBUG] get enough conn for gae
Sep 09 11:37:56 - [INFO] PAC from:127.0.0.1:13422 GET /proxy.pac
Sep 09 11:38:10 - [DEBUG] get ip:64.233.162.81 t:683
Sep 09 11:38:11 - [DEBUG] create_ssl update ip:64.233.162.81 time:675
Sep 09 11:38:12 - [DEBUG] get enough conn for gae

**Comment by LeoWang0812** [comment]
重启了一下可以了 最近有点不稳定

**Comment by LeoWang0812** [comment]
Property	Value
Google IP num	2998
100th IP handshake(ms)	1258
connected link(帮助)	0,25
scaning ip thread num	50
block stat(帮助)	OK

现在又成这样子了 我是广西电信

**Comment by LeoWang0812** [comment]
Property	Value
Google IP num	2998
100th IP handshake(ms)	1270
connected link(帮助)	0,0
scaning ip thread num	50

。。。

**Comment by LeoWang0812** [comment]
Sep 09 12:16:52 - [DEBUG] create_ssl 82.135.118.6 fail:timed out cost:4010 h:0
Sep 09 12:16:52 - [WARNING] direct_handler.handler send response fail. t:21 e:error(10053, '') chrome.google.com/webstore/ajax/eventlog?hl=zh-CN&gl=CN&pv=20141016&mce=rlb%2Csvp%2Catf%2Chcn%2Cgtc%2Cc3d%2Cncr%2Cctm%2Cac%2Chot%2Cfcf%2Caph%2Cigb%2Cpot%2Cevt&_reqid=1444029&rt=j

**Comment by phy901106** [comment]
江西电信已阵亡

**Comment by matrixirtam** [comment]
上海电信 2.05 2.12 2.30 全挂 
connected link(帮助)	0,0
偶尔有连接 很快就失效

**Comment by xxnet** [comment]
上海电信，lantern能用吗？

2015-09-10 12:20 GMT+08:00 matrixirtam <notifications@github.com>:

**Comment by xxnet** [comment]
上海电信，还有ss能用吗？

2015-09-10 20:21 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by matrixirtam** [comment]
我在另外个回复中说过 10-11-12号 本地网络基本25-50%丢包 这个很有可能是造成不能连接的主要原因。新安装下载的3000个ip个人感觉是不能连接的最大的原因 可能里面的ip本地（当地）不适合所有区域？不能连？？？ 用自己扫描出的ip可以很快得到连接connected link。 谢谢xxnet 开发出这么好的程序。。。

**Comment by matrixirtam** [comment]
上海电信光纤 14日凌晨开始 丢包 ping 114.114.114.114

|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                                10.0.0.1 -    0 |  131 |  131 |    0 |    0 |    5 |    1 |
|                            101.229.56.1 -   46 |   46 |   25 |    3 |   21 |  111 |   50 |
|                           124.74.20.209 -   49 |   43 |   22 |    4 |    7 |   27 |    6 |
|                          124.74.210.125 -   53 |   42 |   20 |    4 |    7 |   27 |    7 |
|                           61.152.86.174 -   49 |   43 |   22 |    5 |    8 |   27 |    9 |
|                            202.97.82.26 -   49 |   43 |   22 |    7 |    9 |   28 |    8 |
|                         221.231.191.170 -   53 |   42 |   20 |   11 |   16 |   30 |   15 |
|                           58.217.249.94 -   49 |   43 |   22 |   10 |   11 |   28 |   12 |
|                      public1.114dns.com -   46 |   46 |   25 |    9 |   11 |   28 |   12 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

**Comment by xxnet** [comment]
114.114.114.114 是南京的ip，看上去是你自己到电信接入的丢包

2015-09-14 0:06 GMT+08:00 matrixirtam <notifications@github.com>:

**Comment by matrixirtam** [comment]
个人感觉不是光猫问题 而是GFW的干扰 GFW已经可以确定到IP了 发现特征该IP直接丢包
