### ISSUE TITLE
手机热点给电脑上网，是否可开启ipv6？

### ISSUE THREAD

**Issue by lazureice** [XX-net/XX-Net#9610]
**不是**电脑已经翻墙，要共享给手机用。
我是校园网太慢，所以干脆不用。手机是4G，比较快，所以一直用手机热点给笔记本上网。不知这样是否可以开启ipv6？

**Comment by lazureice** [comment]
嗯……出了点错，结果证明是可行的。

**Comment by nealu1** [comment]
有什么方法吗，我的4G网络有ipv6，开热点给电脑，显示ipv6无网络访问权限。望不吝指教
