### ISSUE TITLE
昨晚还好好的，早晨变成ipv6 status fail

### ISSUE THREAD

**Issue by dalton-chiou** [XX-net/XX-Net#9613]
MAC OS ，XXNET3.87。昨晚还好好的，从路由到系统任何配置没有改变，今天就变成ipv6 status fail。怎么回事呢？

**Comment by zhiganghan** [comment]
这个问题最近确实也是普遍发生。不知道。。。

**Comment by dalton-chiou** [comment]
使用同一个路由，手机里的3.7.16正常使用，MAC里的3.8.7和3.9.6就无法使用。奇怪。

**Comment by zhenthoe** [comment]
![2018-01-27 11 32 22](https://user-images.githubusercontent.com/26887843/35468286-d4135eb8-0355-11e8-8185-3d3cb7d13cbf.png)

**Comment by zhenthoe** [comment]
已经有两个多星期了  ![2018-01-27 12 14 29](https://user-images.githubusercontent.com/26887843/35468562-92558888-035b-11e8-93bf-bb5bbc0c7ffe.png)
