### ISSUE TITLE
Teredo状态正确，可是IPV6 fail

### ISSUE THREAD

**Issue by 75XiaoXuan12** [XX-net/XX-Net#9618]
![image](https://user-images.githubusercontent.com/30333158/35423518-15f5caa0-0289-11e8-8613-ddf30cae90e0.png)
系统开启IPV6的配置是正确的，Teredo状态开起来没有什么问题，可是test-ipv6.com 一直不通过。xxnet也显示IPV6 fail.
![image](https://user-images.githubusercontent.com/30333158/35423745-620c462a-028a-11e8-8ef0-46a0fa7e2819.png)
这是什么原因导致的呢。。。

**Comment by 2378** [comment]
我猜你的isp是二级运营商

**Comment by 75XiaoXuan12** [comment]
确实是二级运营商。。。
刚才看了下IPV4的DNS，不知道什么时候被搞成默认的了。
换了下DNSPod的dns，发现ipv6又好了= =。
