### ISSUE TITLE
IPv6 Status一直Fail 尚未建立连接

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#9630]
* 是否试过最新的测试版本？
试了 无效
  前天3.87还能翻一会，不过一下子ipv6就 fail 了 
3.95也是一直fail

* 是否看过Issues区最近的讨论？
看了，不管用

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
查了

* 简单描述遇到的问题：
ipv6  fail

* 做过哪些尝试：
讨论区里的方法都试过了，都无效

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  

Windows IP 配置

   主机名  . . . . . . . . . . . . . : FR9ALJCFH5WPCPM
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   物理地址. . . . . . . . . . . . . : 00-E0-4C-68-08-19
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.2.105(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年1月27日 16:15:51
   租约过期的时间  . . . . . . . . . : 2154年3月5日 22:55:32
   默认网关. . . . . . . . . . . . . : 192.168.2.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.2.1
   DNS 服务器  . . . . . . . . . . . : 192.168.2.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-B5-7F-AF-C9
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 本地连接* 9:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy) 
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : managed

发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        系统        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        系统        256  fe80::/64                  10  以太网 2
否        系统        256  fe80::/64                   7  本地连接* 9
否        系统        256  fe80::3a:323f:48fd:37b6/128    7  本地连接* 9
否        系统        256  fe80::68a3:e831:3fcd:c773/128   10  以太网 2
否        系统        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        系统        256  ff00::/8                   10  以太网 2
否        系统        256  ff00::/8                    7  本地连接* 9

Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
  7          75        1280  disconnected  本地连接* 9
 10          35        1500  disconnected  以太网 2

查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        30      1  2002::/16
         5      1  2001::/32

接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 7: 本地连接* 9

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::3a:323f:48fd:37b6%7

接口 10: 以太网 2

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::68a3:e831:3fcd:c773%10

===========================================================================
接口列表
  2...00 e0 4c 68 08 19 ......Realtek PCIe GBE Family Controller
 10...00 ff b5 7f af c9 ......TAP-Windows Adapter V9
  1...........................Software Loopback Interface 1
  7...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.2.1    192.168.2.105     35
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      192.168.2.0    255.255.255.0            在链路上     192.168.2.105    291
    192.168.2.105  255.255.255.255            在链路上     192.168.2.105    291
    192.168.2.255  255.255.255.255            在链路上     192.168.2.105    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.2.105    291
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.2.105    291
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  1    331 ::1/128                  在链路上
  1    331 ff00::/8                 在链路上
===========================================================================
永久路由:
  无

**Comment by gjbg1989** [comment]
中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6

**Comment by LN-VIVI** [comment]
@gjbg1989 还是不行

**Comment by LN-VIVI** [comment]
试了你的方法  再用tertdo.bat就可以了，非常感谢你！@ @gjbg1989

**Comment by LN-VIVI** [comment]
这是和原因造成的？
现在的ipv6 ip好少   上外网好慢
@gjbg1989 

IPv6 Number | 9
IP延迟 | 9999

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/35472860-06dda842-03b2-11e8-9daa-a2d39b58e277.png)

**Comment by pendave** [comment]
用我整理的批处理吧
@LN-VIVI 
总结自 @gjbg1989 
这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题

**Comment by UltraDWS** [comment]
@pendave 嗯，好用好用，之前就觉得这个批处理做得很不错，可以循环使用很便利，👍

**Comment by netRuby** [comment]
@pendave 批处理还是不行，关机和重启前执行了

**Comment by netRuby** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:3499 ipv4:0 ipv6:3370
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 562
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
