### ISSUE TITLE
我有一高招让防火墙失效，可惜我不会编程

### ISSUE THREAD

**Issue by dsgys** [XX-net/XX-Net#9634]
可以利用病毒去感染其他电脑，病毒类似bt软件，在不影响使用的情况下使感染的电脑自动变成代理服务器，自动连接彼此，请会编程的考虑使用这种方法，绝对能使防火墙失效的

**Comment by dsgys** [comment]
可以做成类似勒索病毒那样的，自动传播感染，只要开发者不做坏事，这种病毒很难被发现

**Comment by onplus** [comment]
i2p

**Comment by GoodSake** [comment]
不做坏事的大坏蛋！这比到处滥发广告骗来用户量还坏。

**Comment by dsgys** [comment]
@onplus i2p是用户自主选择安装，这样量太小，防火墙很轻易就能挡住

**Comment by dsgys** [comment]
@GoodSake 互联网的精髓就是共享，360那是为自己挣钱当然不可取，我这个方法没人能挣钱，却使大家都能自由的上网，这种坏事难道不值得做吗

**Comment by dsgys** [comment]
@GoodSake TOR就是光明正大的做了，结果基本连接不上，因为正常国家没人去装这玩意，装的大部分老是非正常国家的用户

**Comment by GoodSake** [comment]
tor在美国是很牛的哦，很有价值的软件，想匿名首选tor哦。

**Comment by onplus** [comment]
不做恶

**Comment by ARCHOTZ** [comment]
最好做成啥啥币那样的，矿老板出力应该会很给力的。

**Comment by LN-VIVI** [comment]
不现实

**Comment by imldf** [comment]
做出類似工具的人大有人在，衹是你不知道罷了。很多人被抓被消失了。
