### ISSUE TITLE
状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因.

### ISSUE THREAD

**Issue by tinyperson** [XX-net/XX-Net#964]
![image](https://cloud.githubusercontent.com/assets/14156036/9757903/f7c934b6-5715-11e5-89bb-d60a01315efd.png)

不知道与升级了版本有没有关系。
这个要怎么解决？

**Comment by yuliangyang** [comment]
方法1：彻底关闭xxnet，再打开（结束进程pythonw.exe）
方法2：检查xxnet/data/gae_proxy目录是否有manual.ini
注：先试试方法1。若方法1不行，试试方法2。若方法2中没有manual.ini
建议重新下载最新版xxnet

**Comment by tinyperson** [comment]
@yuliangyang 
我找到为什么了！
![image](https://cloud.githubusercontent.com/assets/14156036/9810923/84230176-58a6-11e5-8fd7-9a90a047bb89.png)
虽然不知道为什么会这样。
