### ISSUE TITLE
可以上外网，但是GAEProxy状态信息显示“请检查浏览器代理设置”

### ISSUE THREAD

**Issue by chiupak** [XX-net/XX-Net#9640]
以前是显示连接成功，你可以访问真正的互联网

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:5331 ipv4:1 ipv6:3003
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:37 h2:0
scan-ip-thread-num: 10
ip-quality: 369
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
GAE-Proxy 自动切换 添加 *.deja.com 走 GAE：XX-Net 3.9.6，一切正常，你可以访问真正的互联网了。

**Comment by YanceyChiew** [comment]
算了，那个deja的域名怎么都访问不了，当然，https时能访问，返回一个python库错误。
因为遮挡了其他信息，所以我手动修改了那个html文件让检查结果始终为真，确实跳过了检查网站，但是又提示证书错误。
当然，说到这里想必大家就明白了，证书重新导入是没有效果的，这个测试版还有不少问题，建议还是用稳定版本。

**Comment by chiupak** [comment]
@gjbg1989 添加了但是没用啊，还是显示“请检查浏览器代理设置”

**Comment by chiupak** [comment]
@YanceyChiew 嗯，已经换回3.8.5稳定版了

**Comment by xx-Chen** [comment]
#9330
