### ISSUE TITLE
保证注册表项 如何开启

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#9641]
![2j th gyn_8 p m9q l 5](https://user-images.githubusercontent.com/10782704/35483099-f52913da-0478-11e8-9a92-ed5fc0e59063.jpg)

**Comment by gjbg1989** [comment]
看来与度娘非常生疏😂
![default](https://user-images.githubusercontent.com/13290970/35483446-071b1c38-047d-11e8-8e21-b17f01efed81.png)

**Comment by xiaoteai** [comment]
![j 2606 4bd 1aljj pp nm](https://user-images.githubusercontent.com/10782704/35681494-8165c772-0798-11e8-9523-030a0b70b0aa.jpg)
![0reh0 _60rth logw90hvr](https://user-images.githubusercontent.com/10782704/35681500-844cb888-0798-11e8-8962-bfab54c3cd93.jpg)
![vx fgknc1i1f j5cwfa 1y5](https://user-images.githubusercontent.com/10782704/35681503-86ac38ce-0798-11e8-9cd8-3767a410f917.jpg)
批处理了 无效

**Comment by xiaoteai** [comment]
不是生 也不是熟  根本不用 老度
