### ISSUE TITLE
为啥我现在访问Youtube时这个desktop_polymer.js总是加载不全，中间被截断导致Youtube主页只显示头部框架

### ISSUE THREAD

**Issue by pendave** [XX-net/XX-Net#9643]
气死我了。
在Chome上切换我这里的各种代理，包括 XX-net、Puff、PsiPhon、自田门... 总是出现这个desktop_polymer.js 加载不全
![38 qxc3 _4m4j xn43ay6](https://user-images.githubusercontent.com/1331881/35490636-082bfae8-04dc-11e8-9009-6d8b0e71f09b.png)
![5 as1p6 f_bjb28yt ul](https://user-images.githubusercontent.com/1331881/35490647-1d410c70-04dc-11e8-8a3c-9cea51e6cfde.png)
监测缓存每次这个文件只加载不到1M：
![5ms 2if8qo i 4tp jgl_ u](https://user-images.githubusercontent.com/1331881/35490664-41f0c7b8-04dc-11e8-81b7-634033c5c0db.png)
而我用网页代理直接能访问这个文件正常的大小：
![hyr929w iqjh l lawq fj](https://user-images.githubusercontent.com/1331881/35490703-7bb15850-04dc-11e8-85a5-90551b37ce55.png)
完整有1.59M。
![uk e cm 2l52zpla90q ifj](https://user-images.githubusercontent.com/1331881/35490709-886de928-04dc-11e8-8367-986fbdfca729.png)

怎么搞定啊？Chrome加载不全这个
https://www.youtube.com/yts/jsbin/desktop_polymer-vflaPj5b2/desktop_polymer.js
是因为我网速慢？？？

从Google搜索里进单独的Youtube视频页面，现在也有框架的问题。现在右侧的list不显示，昨天都可以。
![bs9iq mzc315a tborzii11](https://user-images.githubusercontent.com/1331881/35490787-09ac3210-04dd-11e8-8c51-eb66a7518832.png)
![0 pm geg6 ea f_s2q1b](https://user-images.githubusercontent.com/1331881/35490790-0d69c43a-04dd-11e8-97de-2b2e962ce4b1.png)

**Comment by GoodSake** [comment]
Chrome哪个版本？

**Comment by lon91ong** [comment]
关注一下这个问题，我似乎也遇到了相同的情况，今天看YouTube视频速度特别慢，动不动卡住不动，页面框架也不全

**Comment by pendave** [comment]
Chrome 版本 62.0.3202.62（正式版本） （64 位）

**Comment by imldf** [comment]
爲什麽Google頁面會有“百度一下”？

**Comment by gjbg1989** [comment]
😂360极速浏览器😱

**Comment by gjbg1989** [comment]
敢用360极速浏览器，”大家“都说好的某管家呢？。。。

**Comment by gjbg1989** [comment]
https://assets-cdn.github.com/images/icons/emoji/unicode/1f631.png 转：中国人使用计算机最缺性能了。别说因为害怕损失30%的性能有人不愿意为Intel的CPU打补丁，很多人为了获得某些国内“安全软件”宣称的所谓“加速”功能甚至愿意安装这些闭源软件让他们随便扫描自己整个硬盘

**Comment by gjbg1989** [comment]
转：我的电脑好像中了一个很厉害的病毒，感染了浏览器还总是弹窗骚扰，删都删不干净。这个病毒最嚣张的是……还起了一个很霸气的名字，叫什么“毒霸”。

**Comment by gjbg1989** [comment]
转：【手机】国行诺基亚6升级安卓8.0了。下载了一个4GB多的安装包。新安装包内照例捆绑了腾讯的流氓软件。杀毒、市场、浏览器。这些流氓APP常驻内存，积极刺探用户隐私。用户也只能表面地停用一下。实际还是关不掉。

**Comment by pendave** [comment]
360极速浏览器 我已经卸载了，但是还是不能正常访问 Youtube 
360安全卫士搞的？ @gjbg1989

**Comment by pendave** [comment]
那是我装了油猴脚本 @imldf 
Google & baidu Switcher (修改版)
https://greasyfork.org/zh-CN/scripts/25964

**Comment by pendave** [comment]
刚关了360安全卫士
Youtube主页正常了....................................................
真的是360流氓搞的鬼？？？？？？？？？？？？
![h 183dcfgkjucsj a 4 n1](https://user-images.githubusercontent.com/1331881/35717095-00a3d2fc-0818-11e8-8681-9ca86b83ebd3.png)

**Comment by pendave** [comment]
不过 这几天我禁用了360安全卫士随开机运行 也关闭了360杀毒

又出现了这个问题啊  郁闷

![1y j tt1zgz cp2y y q](https://user-images.githubusercontent.com/1331881/35896519-92650854-0bf7-11e8-9bda-7ce0f1c3fbab.png)

**Comment by gjbg1989** [comment]
🙃得瑟——360安全卫士、360杀毒

**Comment by pendave** [comment]
什么意思 我全都关闭了啊  要卸载吗？ @gjbg1989

**Comment by pendave** [comment]
根据这帖子 https://www.zhihu.com/question/20135407  我关闭了插件 AdBlock 和 AdBlock plus 
貌似Youtube好了！
