### ISSUE TITLE
X-tunnel 无法打开设置页面 http://127.0.0.1:8085/

### ISSUE THREAD

**Issue by 1014942924** [XX-net/XX-Net#9647]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by 1014942924** [comment]
怎么解决

**Comment by 1014942924** [comment]
一直未响应

**Comment by GoodSake** [comment]
?

**Comment by 1014942924** [comment]
![image](https://user-images.githubusercontent.com/35915612/35503340-cb6dd79a-051a-11e8-986f-1a3361464874.png)

**Comment by 1014942924** [comment]
就是一直加载 没有反映

**Comment by 1014942924** [comment]
无法配置 ID了

**Comment by 1014942924** [comment]
@GoodSake

**Comment by 1014942924** [comment]
有人能帮忙 解惑么

**Comment by GoodSake** [comment]
哪个版本啊？

**Comment by 1014942924** [comment]
@GoodSake  现在是3.9.3，之前用的稳定版的，开始能登录，我把关了之后，去谷歌部署ID之后就无法打开网页了

**Comment by 1014942924** [comment]
找到解决办法了 OK
