### ISSUE TITLE
用Windows 10和2.3.0版还是有爆音

### ISSUE THREAD

**Issue by ybxb** [XX-net/XX-Net#965]
今天更新到2.3.0，偶尔还是有声音卡顿、爆音的问题，不过出现的频率比以前小多了，系统是Windows 10 企业版 LTSB 10240。
![image 2015-09-09 19 18 07](https://cloud.githubusercontent.com/assets/14197424/9760439/a8c32ff4-5727-11e5-934e-9a3e165af671.jpg)

**Comment by lewishuang14** [comment]
我也是。

**Comment by qq938403611** [comment]
= =爆音是win10驱动问题

**Comment by uuudbx** [comment]
爆音是windows的问题。我也有这个问题，看视频，听音乐时会时不时卡一下

**Comment by hstmodo** [comment]
我的都是听歌时会出现爆音，看视频时没事。

**Comment by lygoing** [comment]
@qq938403611 你说是声卡驱动问题吗？ 但是我发现卡声音的时候，鼠标也是卡。。。

**Comment by qq938403611** [comment]
那就不只是声卡问题了，应该是系统出错导致，你在开始菜单右键打开事件查看器，自定义视图的管理标签点开看看最近的出错提示，百度解决

**Comment by bioleon** [comment]
是系统出错，因为有些驱动会失效

**Comment by ltwell** [comment]
将最大扫描线程数设置为1 win10 系统卡顿,爆音现象消失

**Comment by uuudbx** [comment]
卡的时候是全卡，鼠标也不动，win10 每隔一段时间都会卡，这个肯定是系统问题

**Comment by ltwell** [comment]
但我将最大扫描线程数从50调到1以后系统就再没有卡过,这是网络软件,估计win10 内核网络子系统驱动还没有完善

**Comment by uuudbx** [comment]
扫描线程有可能引起堵塞系统。倒是没试过减小线程

**Comment by AAA-AAA** [comment]
我也是偶尔会卡一下啊，同时伴随爆音，持续半秒左右。总是找不到解决方法
