### ISSUE TITLE
尚未建立连接，IPv6 Status【Fail】

### ISSUE THREAD

**Issue by esofar** [XX-net/XX-Net#9653]
类型                    : enterpriseclient
服务器名称              : teredo-debian.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : offline
错误                    : 未能打开隧道适配器

**Comment by gjbg1989** [comment]
贴XX-Net诊断信息

**Comment by esofar** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:4822 ipv4:0 ipv6:3428
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 8
ip-quality: 435
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
试试：无线网络属性内取消勾选 IPv6 协议
保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
使用ping超时的微软服务器或许更稳定！(win7除外？)管理权限运行
netsh int ipv6 set teredo enterpriseclient default
（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by qiang92** [comment]
楼上可行

**Comment by esofar** [comment]
两条命令解决：
`netsh interface Teredo set state disable`
`netsh int ter set state enterpriseclient`

**Comment by jie2515** [comment]
@gjbg1989 work for me, thank you
