### ISSUE TITLE
enable_ipv6.bat提示“系统找不到指定路径”

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#9668]
![](https://user-images.githubusercontent.com/10782704/35681503-86ac38ce-0798-11e8-9cd8-3767a410f917.jpg)

**Comment by xiaoteai** [comment]
![p 6cn0oed0i4p12l2q02y2](https://user-images.githubusercontent.com/10782704/35683749-e114e14c-079f-11e8-9b12-54edb2ca89e8.jpg)

**Comment by gjbg1989** [comment]
乱码，繁体？
![default](https://user-images.githubusercontent.com/13290970/35723921-edbbe25a-0836-11e8-9414-5ca455531f8c.png)
检查你的 \default\python27\1.0\python.exe 所在目录，将 default 替换掉

**Comment by yutianzeabc** [comment]
建议先别用这个批处理，首先尝试微软的Teredo服务器，实在不行再去用这个批处理。
管理员权限CMD：
1.netsh int ter set state enterpriseclient server=win10.ipv6.microsoft.com
2.netsh int ter show state

**Comment by xiaoteai** [comment]
真的没辙了
一直开不了
