### ISSUE TITLE
您的APPID流量已经用完，请部署更多APPID。

### ISSUE THREAD

**Issue by LN-VIVI** [XX-net/XX-Net#9681]
*7个用完了

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，config.ini 或 manual.ini 如下 appid = 前添加注释符;而采用公共。。。
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid = xxx|yyy|zzz

**Comment by g8up** [comment]
现在用 GAE 还好使？

**Comment by gjbg1989** [comment]
😂自去年10月以来，貌似一直好使（其他如SS不好使）
