### ISSUE TITLE
大家，wiki中文文档被我弄坏了，万分抱歉，谁能帮我恢复一下

### ISSUE THREAD

**Issue by chentging** [XX-net/XX-Net#9689]
我看到wiki上中文文档这边有一个编辑的小标志，我好奇去点击了，关键我还删除了，因为我寻思，我不可能有权限把这个删除吧，但是竟然真的删除了，那一刻，我万分愧疚，然后我试图恢复，但是恢复好之后，和以前格式不一样了，万分愧疚，你们谁能帮我恢复到我修改之前的那个版本上啊，我修改用的ID:chentging
万分抱歉，抱歉
![image](https://user-images.githubusercontent.com/29357333/35769983-788aeeae-094e-11e8-80f0-84681dfaea60.png)

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9589

**Comment by xx-Chen** [comment]
全都恢复了，真的别再玩了..
