### ISSUE TITLE
访问微博问题

### ISSUE THREAD

**Issue by Ricky816845** [XX-net/XX-Net#9695]
访问新浪微博页面的时候貌似走的外部流量....

**Comment by gjbg1989** [comment]
添加“新浪微博”直接连接？

**Comment by Ricky816845** [comment]
用的SmartRouter

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=smart_router&menu=config
![default](https://user-images.githubusercontent.com/13290970/35779366-bc3c7ace-0a06-11e8-8034-31fb054ba5ac.png)
