### ISSUE TITLE
每次只能部署一个appid

### ISSUE THREAD

**Issue by KevinLeung007** [XX-net/XX-Net#97]
我按照标准方法，用|分隔多个appid，但是，每次只有一个appid部署成功。也没有错误提示，继续部署会提示already runing.

**Comment by KevinLeung007** [comment]
部署、使用过程中，日志没有刷新，也就是说没有新内容。
还停留在第一次配置的状态下：
Apr 01 16:37:28 - [INFO] load google ip_list num:2999, gws num:2999
Apr 01 16:37:28 - [DEBUG] sort ip time:3
Apr 01 16:37:29 - [INFO] ------------------------------------------------------
GoAgent Version : 3.1.43 (python/2.7.9 )
Listen Address : 127.0.0.1:8087
Control Address : 127.0.0.1:8084
GAE APPID : **********
Pac Server : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

**Comment by xxnet** [comment]
试试1.7版本

2015-04-01 5:50 GMT-04:00 KevinLeung007 <notifications@github.com>:

**Comment by lele2010lele** [comment]
1.7已经成功部署多个，我的是9个

**Comment by xxnet** [comment]
太好了

2015-04-03 0:04 GMT-04:00 lele2010lele <notifications@github.com>:
