### ISSUE TITLE
Linux下一切正常，提示可以正常上网，但是谷歌是上不去的，很奇怪，我看了一下，ip4的数量只有１个，求救，几天了已经

### ISSUE THREAD

**Issue by ruiyongsheng** [XX-net/XX-Net#9702]
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018
os-release: 4.4.0-112-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.119 Chrome/64.0.3282.119 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.12
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4628 ipv4:1 ipv6:1927
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:65 h2:0
scan-ip-thread-num: 20
ip-quality: 318
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by ruiyongsheng** [comment]
![default](https://user-images.githubusercontent.com/19965525/35785151-2d17cab2-0a59-11e8-82f1-b22b56c0c0b2.png)
![default](https://user-images.githubusercontent.com/19965525/35785152-2d5b023c-0a59-11e8-87e6-cbb798214543.png)

**Comment by Alobe007** [comment]
IPV4不行了。得开IPV6

**Comment by yutianzeabc** [comment]
请尝试将配置改为"只用ipv6"。
