### ISSUE TITLE
IP

### ISSUE THREAD

**Issue by kaixinwangzi1982** [XX-net/XX-Net#9705]
IPv6打开失败，win7 64位系统，系统重新安装的，我把日志贴出来
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
xxnet-version: 3.8.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by lon91ong** [comment]
检查三点, 1, IP Help服务开启; 2, teredo连接状态; 3, 路由表首项

**Comment by GoodSake** [comment]
最关键的怎么失败的？

**Comment by kaixinwangzi1982** [comment]
@lon91ong IP helper服务是启动的，teredo连接状态怎么看？？？  路由表首项怎么看？麻烦说详细下，谢谢

**Comment by lon91ong** [comment]
@kaixinwangzi1982 
[teredo.zip](https://github.com/XX-net/XX-Net/files/1694524/teredo.zip)
批处理选项, 1就是查看teredo连接状态; 4 查看路由表

**Comment by kaixinwangzi1982** [comment]
![1517823342 1](https://user-images.githubusercontent.com/19239894/35797562-0a5e504e-0a9b-11e8-9e65-3265db30dbb9.png)
我这个是关闭状态吧？哪里能开启

**Comment by lon91ong** [comment]
@kaixinwangzi1982 组策略里面关了
 Win+R ==> gpedit.msc ==> 计算机配置 ==> 管理模板 ==> 网络 ==> TCPIP 设置 ==> IPv6 转换技术
把有关Teredo的几个配置都改成**未配置**
而后命令行执行: netsh interface ipv6 set teredo enterpriseclient teredo.remlab.net 30 default

**Comment by kaixinwangzi1982** [comment]
@lon91ong 

你好，我按照你说的做了，这个是截屏，然后我启动xx-netzh之后。ipv6还是failed。你方便用qq给我远程下么？谢谢

**Comment by kaixinwangzi1982** [comment]
![1517840556 1](https://user-images.githubusercontent.com/19239894/35809516-df340d18-0ac3-11e8-8ecc-927e217c340a.png)

**Comment by lon91ong** [comment]
@kaixinwangzi1982 很明显你的teredo没有连上，还是自己先连上再说吧

**Comment by kaixinwangzi1982** [comment]
@lon91ong 有时候怎么连接不上teredo呢？有什么办法解决么？和网络环境有关，还是哪里配置出问题了，错误和上图是一样的

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验
