### ISSUE TITLE
SwitchyOmega配置问题

### ISSUE THREAD

**Issue by Ricky816845** [XX-net/XX-Net#9714]
switchyOmega现在配置有点问题
1.每次启动浏览器都会重置到SmartRouter配置
2.切换模式的时候会刷新页面 但是加载还是有问题 只有再次刷新才会好,但也不一定
3.指定当前网站的的加载配置并不总能好用 尤其是重新打开浏览器的时候 可能与1有关
因为我平常上B站和微博比较多,页面较之前的模式SmartRouter卡顿严重 而且不稳定

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/9501

**Comment by Ricky816845** [comment]
多谢
