### ISSUE TITLE
.

### ISSUE THREAD

**Issue by MaoJianwei** [XX-net/XX-Net#9715]
.

**Comment by gjbg1989** [comment]
😱GFW 没有为你特开IPV4？

**Comment by GoodSake** [comment]
xx-net不扫ipV4了，不可能吧。。。

**Comment by xx-Chen** [comment]
![2018020715](https://user-images.githubusercontent.com/36025202/35904699-163a01da-0c1f-11e8-8528-a7cc2c90fd68.png)
扫没扫你看扫描日志啊..

**Comment by gjbg1989** [comment]
😂应该没有，貌似楼主“只使用 IPv4”

**Comment by whhxmwhh** [comment]
想 GFW 对他网开一面！！！哈哈精辟的回答呀。原来程序员也有幽默的时刻！

**Comment by gjbg1989** [comment]
程序员？视代码为天书的纯老白而已😱
