### ISSUE TITLE
Wrong password!?

### ISSUE THREAD

**Issue by GoodSake** [XX-net/XX-Net#9723]
Wrong password!? 到底啥意思哦？

![wrongpassword](https://user-images.githubusercontent.com/19205130/35956460-f78ae634-0cd0-11e8-8fae-19951187aeb8.png)

**Comment by xx-Chen** [comment]
> GoAgent proxy.ini password is wrong!

这...不难理解吧..

**Comment by GoodSake** [comment]
你也遇到了？你怎么理解的，我到现在都还没理解，哈哈哈！

**Comment by xx-Chen** [comment]
proxy.ini里配置的password不匹配呗。
然后你说偶尔出现那估计是因为你的appids中有某个有密码然后别的没有，ini里配置密码的时候又是统一配置的，XX-Net一个一个appid用过去刚好用到那个要密码的就报错了呗。我猜的。

**Comment by GoodSake** [comment]
我的所有appid都没密码，也从来没修改过proxy.ini。所以我是无法理解的，哈哈哈。

**Comment by gjbg1989** [comment]
逻辑正确，不是 proxy.ini ，是 config.ini 或 manual.ini ？

**Comment by GoodSake** [comment]
肏，可能是有一个appid填写错误导致的。。。
