### ISSUE TITLE
尚未建立连接

### ISSUE THREAD

**Issue by l3125831q** [XX-net/XX-Net#9724]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:5252 ipv4:0 ipv6:2256
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 500
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by GoodSake** [comment]
在cn的话ipv6-status: Fail是不可以的哦。

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果

**Comment by Newbit13** [comment]
我的netsh int ipv6 show teredo结果是
类型                    : client
服务器名称              : teredo.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

**Comment by gjbg1989** [comment]
使用ping超时的微软服务器或许更稳定！(win7除外？)管理权限运行
netsh int ipv6 set teredo enterpriseclient default
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by oikimi** [comment]
@gjbg1989 这是我的结果 帮看看
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
就这些，今天win10自动更新完后就这样了，之前用的好好的

**Comment by gjbg1989** [comment]
上面——自动优选服务器
