### ISSUE TITLE
mac 3.9.6 图文配置后依然无法google

### ISSUE THREAD

**Issue by lovexinqq** [XX-net/XX-Net#9727]
属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | Fail
IPv4 IP数 | 0
IPv6 IP数 | 0
系统状态 | 0
IP延迟 | 9999
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | Fail
CA证书状态(下载) | Fail
IP扫描线程数(设置) | 10
屏蔽状态(帮助) | OK

版本3.9.6 安装完，配置完switchomega 一直无法上网，请大侠指点。

日志：
Feb 08 14:49:01.144 - [DEBUG] ## GAEProxy set keep_running: True

Feb 08 14:49:01.144 - [INFO] ------------------------------------------------------

Feb 08 14:49:01.144 - [INFO] Python Version : 2.7.10

Feb 08 14:49:01.144 - [INFO] OS : Release:10.13.3; Version:('', '', '') Machine:x86_64

Feb 08 14:49:01.144 - [INFO] Listen Address : 127.0.0.1:8087

Feb 08 14:49:01.144 - [INFO] GAE APPID :

Feb 08 14:49:01.144 - [INFO] ------------------------------------------------------

Feb 08 14:49:01.147 - [DEBUG] Importing CA

Feb 08 14:49:01.193 - [INFO] GoAgent CA exist

Feb 08 14:49:01.193 - [INFO] server 127.0.0.1:8087 started.

Feb 08 14:49:01.573 - [DEBUG] network IPv4 is ok, cost:582 ms

Feb 08 14:49:01.645 - [WARNING] no enough ip

Feb 08 14:49:02.151 - [WARNING] no enough ip

Feb 08 14:49:02.660 - [WARNING] no enough ip

Feb 08 14:49:03.164 - [WARNING] no enough ip

Feb 08 14:49:03.171 - [INFO] GAE CONNECT xxnet-update.appspot.com:443

Feb 08 14:49:03.326 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=12c856f5-e9f4-4017-bdbe-eb2aabeac038&version=3.9.6&platform=Darwin-17.4.0-x86_64-i386-64bit

Feb 08 14:49:03.666 - [WARNING] no enough ip

Feb 08 14:49:04.167 - [WARNING] no enough ip
Feb 08 15:09:24.238 - [DEBUG] GAEProxy Web_control 127.0.0.1:50609 GET /deploy?cmd=get_log

Feb 08 15:09:25.240 - [DEBUG] GAEProxy Web_control 127.0.0.1:50609 GET /deploy?cmd=get_log

Feb 08 15:09:25.851 - [DEBUG] GAEProxy web_control 127.0.0.1:50609 POST /deploy?cmd=cancel

Feb 08 15:09:26.245 - [DEBUG] GAEProxy Web_control 127.0.0.1:50609 GET /deploy?cmd=get_log

Feb 08 15:09:35.074 - [DEBUG] GAE GET http://google.com/

Feb 08 15:10:01.217 - [WARNING] no enough ip

Feb 08 15:10:04.165 - [DEBUG] create ssl timeout fail.

Feb 08 15:10:04.166 - [WARNING] no enough ip

Feb 08 15:10:04.671 - [WARNING] no enough ip

**Comment by Lancenas** [comment]
ipv6没开启

**Comment by lovexinqq** [comment]
@Lancenas 多谢。已成功
