### ISSUE TITLE
流量缩水了？或者id被盗用？

### ISSUE THREAD

**Issue by klcb2010** [XX-net/XX-Net#9730]
昨天下载22点到今天凌晨3点 总共2.76G，今天网上9点下载2.2g，刚才发现下载停止，进去看net主页发现一个提示————流量用完了。我用的12个id，应该12G才对呀。有同样情况的伙伴吗？

**Comment by SeaHOH** [comment]
多线程下载大文件会出现浪费

**Comment by klcb2010** [comment]
过了12点应该是新的一天  打开仍然提示超流量？？？？？！！！

**Comment by onplus** [comment]
北京时间16:00重置
