### ISSUE TITLE
电脑上的xxnet如何通过shadowrockets给ipad用

### ISSUE THREAD

**Issue by ipssyoungman** [XX-net/XX-Net#9731]
电脑上的xxnet可以正常使用，如何在ipad上用shadowrockets共享电脑的xxnet？
求大神告知

XX-Net-3.8.7\data\gae_proxy 下已建立manual.ini 如下：
`[listen]
ip = 0.0.0.0
port = 8087

[gae]
appid = xx|xxx|xxx|xxxx(已省略)

[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt`

shadowrockets用http代理 服务器地址填写的本机ip（192.168.0.101），端口8086，证书也已安装，还是无法上Google
ipad上看GAEProxy状态信息：浏览器代理设置和CA证书状态都显示Fail，证书我是在“CA证书状态（下载）”点击下载安装的

ipad上也能打开192.168.0.101/proxy.pac

**Comment by GoodSake** [comment]
shadowrockets是啥哦？

**Comment by ipssyoungman** [comment]
@GoodSake 苹果上的一个代理软件

**Comment by ipssyoungman** [comment]
@71e6fd52 ？？？

**Comment by 71e6fd52** [comment]
http://xyproblem.info/

**Comment by Selter** [comment]
你不能这么做。
xxnet与shadowrockets是两套完全不同的“fanqiang”方案。
你勉强的把两个不同的方案“合并”到一起并不能产生你想要的效果。
