### ISSUE TITLE
心慌慌啊! 求教更隐蔽更安全的方法!

### ISSUE THREAD

**Issue by lon91ong** [XX-net/XX-Net#9743]
刚刚在zdfans看到了这篇《[90年农村小伙售卖SS翻墙服务被判刑且重罚](http://www.zdfans.com/8348.html)》,本来大算转发过来的, 但是被自动关闭了话题, 可能有些敏感吧!
所以就不转了!
![20180211185258](https://user-images.githubusercontent.com/16462258/36072586-d1d7ea20-0f5c-11e8-9a38-7ca84e663bdf.png)

只是心慌慌啊! 求教更隐蔽更安全的方法!

**Comment by e2889e** [comment]
怕个毛
只敢抓卖的, 有种抓买的啊!

敢吗?
敢吗!
敢吗!

**Comment by lon91ong** [comment]
@e2889e 即使不便全抓, 但是杀鸡儆猴抓几个也不是不可能啊!

**Comment by 2378** [comment]
各大卫视 cctv等媒体 全都在youtube有频道 还是官方频道

先把这些抓了吧:smirk:

**Comment by GoodSake** [comment]
这么看来cn法律就是摆设，实际上想干啥就干啥。哈哈哈！
