### ISSUE TITLE
如何主动知道，我在访问某网站的时候用的是不是代理ip

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#9749]
有些网站可能会提供访问者ip在首页，但是大部分都没有，我需要知道这个，就是想确定我是不是在用代理来访问某网站。
当然有人会说，你不能访问的时候就是没有走代理。可以访问就是走了代理。或者从代理规则里面看。。。那样当然可以。。。但是这些不是我想要的答案。

我就是想知道，有没有办法主动知道。。。用来验证我设置规则的有效性

**Comment by xx-Chen** [comment]
查XX-Net log
看SwitchyOmega

**Comment by yuyistar** [comment]
@xx-Chen 我现在用的是ssr+switchyomega，如果从switchyomega里面要怎么看？我并不是要看switchyomega里面的规则

**Comment by onplus** [comment]
![image](https://user-images.githubusercontent.com/31188782/36096511-a313bd88-1031-11e8-803d-eb0667082a13.png)

![image](https://user-images.githubusercontent.com/31188782/36096526-b8d4502e-1031-11e8-87b7-99a6dae46f54.png)

**Comment by xx-Chen** [comment]
图标颜色和文字tip都能看到当前网页匹配的哪个模式：
![20180212225450](https://user-images.githubusercontent.com/36025202/36102610-cd4f1ed8-1047-11e8-9e3f-29833c393f99.png)

![20180212225806](https://user-images.githubusercontent.com/36025202/36102754-3ed5ccaa-1048-11e8-9e16-f9301dc6e08a.png)

以及SO的自带功能：
![20180212225943](https://user-images.githubusercontent.com/36025202/36102859-8cf785d6-1048-11e8-90dd-b43216443005.png)


当然上面onplus的直接用DevTools的更直观详细准确咯。

**Comment by yuyistar** [comment]
@onplus 这个是怎么看得。一个软件吗，还是一条命令

**Comment by yuyistar** [comment]
@xx-Chen 这个devtools怎么用，是不是右键选择检查，但是我并没有找到有ip显示的语句呀。。。应该怎么调出来
![_20180213085402](https://user-images.githubusercontent.com/14964575/36128085-799eb402-109b-11e8-8e06-0acf12fd51fb.png)

**Comment by xx-Chen** [comment]
![20180213125838](https://user-images.githubusercontent.com/36025202/36134122-ac2a51b6-10bd-11e8-9d86-8add30ccab66.png)

**Comment by yuyistar** [comment]
@xx-Chen 多谢。找到了

**Comment by caizzoo** [comment]
https://chrome.google.com/webstore/detail/%E7%BD%91%E7%AB%99-ip-%E4%BF%A1%E6%81%AF%E6%9F%A5%E8%AF%A2/mifjlfhembandabikpiehhokhdepbdai
试试这个插件
