### ISSUE TITLE
一直连不上不知道怎么回事了，家里的联通没有ipv6

### ISSUE THREAD

**Issue by xuesexingmang** [XX-net/XX-Net#9760]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv4
gws-ip-num: total:166 ipv4:0 ipv6:4047
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
use-ipv6: force_ipv4👍😱

**Comment by dahai058** [comment]
我是联通20兆光纤挺好用啊！

**Comment by xuesexingmang** [comment]
谢谢！已经解决了

**Comment by yunlaix** [comment]
求问 lz 如何解决的 -_-

**Comment by xuesexingmang** [comment]
按照GitHub里面的方法打开的ipv6


2018-02-15 14:09 GMT+08:00 yunlaix <notifications@github.com>:
