### ISSUE TITLE
[发布] 新版发布 3.10.4

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#9761]
新特性：
* X-Tunnel新增tls_relay通道 
  解决部分地区无法使用问题
  看视频、下载速度有大提升
* X-Tunnel可以在Web上选择服务器
* 新增加系统级别的状态页

新功能改动较大，未提供自动升级，请大家手动下载测试，反馈。
下载地址：
https://github.com/XX-net/XX-Net/archive/3.10.4.zip

更新：
* 3.10.2 无法关闭模块
 3.10.4 版本已经允许关闭x-tunnel和smart_router

**Comment by imldf** [comment]
3.10.0 升級后使用跟上一版本基本一樣，沒問題。

**Comment by yydxwt** [comment]
3.10.0版怎么关闭各模块？

**Comment by xxnet** [comment]
​新版本，各模块互相依赖，不建议关闭模块。
高级用户，可以手动修改 data/launcher/config.yaml 里面的auto_start为0

**Comment by liangliangge521** [comment]
不错新年更新了版本，我这全局pac智能代理加x tunnel自动切换好使，呵呵

**Comment by imldf** [comment]
升級3.10.1版本，一切正常。

**Comment by xx-Chen** [comment]
@yydxwt webUI暂时限制已开启GAEProxy模块的关闭GAEProxy模块，从关闭到开启以及X-Tunnel与SmartRouter不限制。

**Comment by weiwei007** [comment]
X-TUNNEL要auto_start为0才能关闭确实不方便，占用了ssr端口，xtun端口在哪里修改

**Comment by xx-Chen** [comment]
@weiwei007 webUI模块管理未限制X-Tunnel

**Comment by weiwei007** [comment]
webUI模块管理没有关闭X-Tunnel选项，要吧auto_start为0才行！X-TUNNEL端口哪里修改

**Comment by xxnet** [comment]
​1080端口，确实很多代理工具都会使用，要改动怕影响其他用户

改动的方法：
修改 data/x_tunnel/client.json
大括号里增加一行:
 "socks_port": 端口号,
要注意符合json格式

**Comment by penuser** [comment]
反馈一个麻烦的小问题
“你好”界面反复出现，对于老用户而言没有一个取消方式导致每次切换页面，屏幕都被占了一半。

**Comment by xx-Chen** [comment]
@penuser 延时15秒我记得。不过没考虑到中途关闭的问题抱歉，马上修复。

**Comment by dahai058** [comment]
感谢X神新年更新版本，目前我仍用3.9.6，回家换成联通宽带一切正常！

**Comment by lkhtty** [comment]
X-Tunnel可以在Web上选择服务器，这个是怎么用的？要更新CHROME的switchyomega代理设置吗？

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=x_tunnel&menu=config 设置——服务器

**Comment by xxnet** [comment]
3.10.4 版本发布，修复前面发现的问题，请大家测试反馈.

**Comment by xxnet** [comment]
3.10.4 版已推送测试版本更新

**Comment by imldf** [comment]
3.10.4 使用沒問題

**Comment by luyiaya** [comment]
3.10.4Android版本极不稳定，连不上网络，希望能处理一下

**Comment by xx-Chen** [comment]
3.10.4Android版本？

**Comment by xxnet** [comment]
​请贴出相关的日志

**Comment by XndroidDev** [comment]
`Smart router` 中似乎还有不少误判:
```
Feb 23 16:34:22.780 - [INFO] domain gw.alicdn.com:443 gae
Feb 23 16:34:22.794 - [DEBUG] host:gw.alicdn.com:443 do gae
Feb 23 16:34:23.063 - [INFO] domain ald.taobao.com:443 gae
Feb 23 16:34:23.076 - [DEBUG] host:ald.taobao.com:443 do gae
Feb 23 16:34:23.158 - [INFO] domain g.alicdn.com:443 gae
Feb 23 16:34:23.170 - [DEBUG] host:g.alicdn.com:443 do gae
Feb 23 16:34:23.253 - [INFO] domain cart.taobao.com:443 gae
Feb 23 16:43:18.080 - [INFO] domain res.wx.qq.com:443 gae
Feb 23 16:43:15.542 - [INFO] domain api.share.baidu.com:80 gae
```
另外, `TLS-Relay`用的什么原理呢? 目前似乎基本都是 timed out

**Comment by xxnet** [comment]
​smart router 还要完善

tls-relay是自建的CDN，目前还在优化中

**Comment by OuyangIPC** [comment]
3.10.4为啥没有gae proxy模块了？我之前的因为gae扫不到ip就把gae模块禁止了，一直用的x-tunnel的流量。现在遇到个问题，能上谷歌，但是不能登录Google账号

**Comment by gjbg1989** [comment]
3-4楼不是已很清楚😱
