### ISSUE TITLE
求解答  一直无法开启 

### ISSUE THREAD

**Issue by xiaoteai** [XX-net/XX-Net#9762]
![_v4k w y 8 mq02 owfi l](https://user-images.githubusercontent.com/10782704/36194584-2e82b0f8-11a5-11e8-9598-fa2fd58c1f6b.jpg)

**Comment by gjbg1989** [comment]
😱你家私有的服务器？
![default](https://user-images.githubusercontent.com/13290970/36202981-d3cac85a-11c0-11e8-8567-61718c7e080c.png)

**Comment by xiaoteai** [comment]
自动选择的

**Comment by gjbg1989** [comment]
吹吧，牛皮😂
一、貌似自动选择不支持组策略
二、貌似只有 teredo.iks-jena.de 没有你的。。。

**Comment by gjbg1989** [comment]
#8620 

![default](https://user-images.githubusercontent.com/13290970/36209077-b010664e-11d5-11e8-809b-241fefbd798c.png)

**Comment by xiaoteai** [comment]
teredo.iks-jena.de  被篡改   我去哪里 改回来   给个提示  详细一点

**Comment by gjbg1989** [comment]
给个提示 详细一点——😱难道下图不是自己干的？
![image](https://user-images.githubusercontent.com/13290970/36241082-101563fe-124f-11e8-8a0b-8eec36ca3089.png)

**Comment by xiaoteai** [comment]
印象 不深刻  不太清楚 是怎么 弄成这样子   改回 teredo.iks-jena.de 原版  才是关键
                                                                              请问 怎么改？

**Comment by gjbg1989** [comment]
确保系统服务 IP Helper 为自动并已启动，结束进程 pythonw.exe，先前修改的 ipv6 组策略退回到默认值的全部“未配置”，管理权限运行 netsh int ipv6 set teredo enterpriseclient default default 3544
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
