### ISSUE TITLE
更新3.10.0后用x-tunnel依然无法打开Google和YouTube

### ISSUE THREAD

**Issue by challen88** [XX-net/XX-Net#9763]
电脑Firefox52使用autoproxy，配置一起正常，之前可以成功上网
x-tunnel登录正常，但是打不开网页

全局
属性 | 值
-- | --
请求数 | 18
响应时间 | 8387
往返数 | 1018
较慢 | 23
重传 | 185
超时 | 0
当前速度 | Up: 0.0 B/s / Down: 0.0 B/s
使用总量 | Up: 10.7 KB / Down: 683.6 KB

GAE 前端
属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0.0 B / Down: 0.0 B

Cloudflare 前端
属性 | 值
-- | --
Score | 25833
成功数 | 84
失败数 | 0
工作数 | 43
使用总量 | Up: 10.7 KB / Down: 683.6 KB

Feb 14 18:38:24.934 - [INFO] xxnet_version:3.10.0

Feb 14 18:38:24.935 - [INFO] server 127.0.0.1:1080 started.

Feb 14 18:38:24.935 - [INFO] Socks5 server listen:127.0.0.1:1080.

Feb 14 18:38:27.086 - [DEBUG] x_tunnel force update info

Feb 14 18:38:28.456 - [INFO] api:/login success t:1369

Feb 14 18:38:28.456 - [INFO] update xt_server v18.xx-net.net:443

Feb 14 18:38:28.456 - [INFO] request_balance host:v18.xx-net.net port:443 balance:0.000000 quota:600203573012.000000

Feb 14 18:40:12.937 - [INFO] session timeout, reset it.

Feb 14 18:40:17.534 - [INFO] login_session asbbhain time:4596 msg:Success

Feb 14 18:40:18.091 - [INFO] session started.

Feb 14 18:40:18.094 - [INFO] socks5 ('127.0.0.1', 5057) connect to localhost:8085 conn_id:1

Feb 14 18:40:18.094 - [INFO] socks5 ('127.0.0.1', 5059) connect to localhost:8085 conn_id:2

Feb 14 18:40:18.095 - [INFO] socks5 ('127.0.0.1', 5062) connect to localhost:8085 conn_id:3

Feb 14 18:40:18.095 - [INFO] socks5 ('127.0.0.1', 5064) connect to localhost:8085 conn_id:4

Feb 14 18:40:18.096 - [INFO] socks5 ('127.0.0.1', 5068) connect to localhost:8085 conn_id:5

Feb 14 18:40:18.097 - [INFO] socks5 ('127.0.0.1', 5069) connect to www.google.com:443 conn_id:6

Feb 14 18:40:18.097 - [INFO] socks5 ('127.0.0.1', 5071) connect to localhost:8085 conn_id:7

Feb 14 18:40:18.098 - [INFO] socks5 ('127.0.0.1', 5072) connect to www.google.com:443 conn_id:8

Feb 14 18:40:18.099 - [INFO] socks5 ('127.0.0.1', 5073) connect to localhost:8085 conn_id:9

Feb 14 18:40:18.099 - [INFO] socks5 ('127.0.0.1', 5076) connect to localhost:8085 conn_id:10

Feb 14 18:40:18.100 - [INFO] socks5 ('127.0.0.1', 5080) connect to localhost:8085 conn_id:11

Feb 14 18:40:18.101 - [INFO] socks5 ('127.0.0.1', 5081) connect to localhost:8085 conn_id:12

Feb 14 18:40:18.101 - [INFO] socks5 ('127.0.0.1', 5085) connect to localhost:8085 conn_id:13

Feb 14 18:40:33.478 - [DEBUG] roundtrip time:15382 cost:15062 transfer_no:2 send:0 rcv:21

Feb 14 18:40:34.181 - [DEBUG] roundtrip time:16086 cost:15093 transfer_no:1 send:0 rcv:21

Feb 14 18:40:35.290 - [DEBUG] roundtrip time:17194 cost:15048 transfer_no:3 send:0 rcv:21

Feb 14 18:40:36.926 - [DEBUG] roundtrip time:18831 cost:15028 transfer_no:5 send:0 rcv:21

Feb 14 18:40:38.585 - [DEBUG] roundtrip time:20490 cost:15094 transfer_no:4 send:0 rcv:21

Feb 14 18:40:38.700 - [DEBUG] roundtrip time:20603 cost:15127 transfer_no:9 send:0 rcv:21

Feb 14 18:40:40.000 - [DEBUG] roundtrip time:21904 cost:15017 transfer_no:7 send:0 rcv:21

Feb 14 18:40:41.608 - [DEBUG] roundtrip time:23511 cost:15008 transfer_no:11 send:0 rcv:21

Feb 14 18:40:41.608 - [DEBUG] rtt:8503 speed:0 trace: processed:1, h2.stream_num:1, sni:crimsonrgames.com, domain:flar.tk

Feb 14 18:40:41.608 - [DEBUG] task trace:1:start_request,6550:get_task(0),1609:get_worker(1):198.41.208.250,0:h2_req,2:start send header,0:start send left body,0:end send left body,15337:h2_get_head,0:get_response,:0

Feb 14 18:40:43.192 - [WARNING] front retry v18.xx-net.net/data?tid=6

Feb 14 18:40:43.193 - [WARNING] front retry v18.xx-net.net/data?tid=8

Feb 14 18:40:43.193 - [WARNING] front retry v18.xx-net.net/data?tid=10

Feb 14 18:40:43.193 - [WARNING] front retry v18.xx-net.net/data?tid=13

Feb 14 18:40:43.194 - [WARNING] front retry v18.xx-net.net/data?tid=14

Feb 14 18:40:43.194 - [WARNING] front retry v18.xx-net.net/data?tid=17

Feb 14 18:40:43.194 - [WARNING] front retry v18.xx-net.net/data?tid=12

Feb 14 18:40:43.195 - [WARNING] front retry v18.xx-net.net/data?tid=16

Feb 14 18:40:43.195 - [WARNING] front retry v18.xx-net.net/data?tid=15

Feb 14 18:40:43.195 - [WARNING] front retry v18.xx-net.net/data?tid=18

.............

Feb 14 18:40:44.200 - [WARNING] roundtrip time:26095 transfer_no:48 send:0 status:602

Feb 14 18:40:44.200 - [WARNING] roundtrip time:26095 transfer_no:44 send:0 status:602

Feb 14 18:40:44.200 - [WARNING] roundtrip time:26095 transfer_no:41 send:0 status:602

Feb 14 18:40:44.201 - [WARNING] roundtrip time:26096 transfer_no:50 send:0 status:602

Feb 14 18:40:44.499 - [WARNING] roundtrip time:11021 transfer_no:51 send:5647 status:602

Feb 14 18:40:47.270 - [DEBUG] Conn session:asbbhain conn:2 stop:recv fail.

Feb 14 18:40:47.270 - [DEBUG] remove conn_id:2

Feb 14 18:40:47.271 - [DEBUG] Conn session:asbbhain conn:9 stop:recv fail.

Feb 14 18:40:47.271 - [DEBUG] Conn session:asbbhain conn:10 stop:recv fail.

Feb 14 18:40:47.271 - [DEBUG] Conn session:asbbhain conn:4 stop:recv fail.

Feb 14 18:40:47.271 - [DEBUG] remove conn_id:9

Feb 14 18:40:47.272 - [DEBUG] remove conn_id:10

Feb 14 18:40:47.272 - [DEBUG] Conn session:asbbhain conn:5 stop:recv fail.

Feb 14 18:40:47.272 - [DEBUG] remove conn_id:4

Feb 14 18:40:47.273 - [DEBUG] Conn session:asbbhain conn:13 stop:recv fail.

Feb 14 18:40:47.273 - [DEBUG] Conn session:asbbhain conn:1 stop:recv fail.

Feb 14 18:40:47.274 - [DEBUG] Conn session:asbbhain conn:7 stop:recv fail.

Feb 14 18:40:47.274 - [DEBUG] Conn session:asbbhain conn:11 stop:recv fail.

Feb 14 18:40:47.274 - [DEBUG] remove conn_id:5

Feb 14 18:40:47.274 - [DEBUG] Conn session:asbbhain conn:3 stop:recv fail.

Feb 14 18:40:47.274 - [DEBUG] remove conn_id:13

Feb 14 18:40:47.275 - [DEBUG] Conn session:asbbhain conn:12 stop:recv fail.

Feb 14 18:40:47.275 - [DEBUG] remove conn_id:1

Feb 14 18:40:47.275 - [DEBUG] remove conn_id:7

Feb 14 18:40:47.275 - [DEBUG] remove conn_id:11

Feb 14 18:40:47.275 - [DEBUG] remove conn_id:3

Feb 14 18:40:47.276 - [DEBUG] remove conn_id:12

Feb 14 18:40:47.317 - [INFO] socks5 ('127.0.0.1', 5167) connect to localhost:8085 conn_id:14

Feb 14 18:40:48.073 - [INFO] socks5 ('127.0.0.1', 5173) connect to localhost:8085 conn_id:15

Feb 14 18:40:48.273 - [DEBUG] Conn session:asbbhain conn:8 stop:recv fail.

Feb 14 18:40:48.273 - [DEBUG] remove conn_id:8

Feb 14 18:40:48.536 - [WARNING] front retry v18.xx-net.net/data?tid=52

Feb 14 18:40:49.075 - [INFO] socks5 ('127.0.0.1', 5178) connect to localhost:8085 conn_id:16

Feb 14 18:40:49.537 - [WARNING] roundtrip time:11032 transfer_no:52 send:5647 status:602

Feb 14 18:40:50.081 - [INFO] socks5 ('127.0.0.1', 5182) connect to localhost:8085 conn_id:17

Feb 14 18:40:51.082 - [INFO] socks5 ('127.0.0.1', 5184) connect to localhost:8085 conn_id:18

Feb 14 18:40:52.086 - [INFO] socks5 ('127.0.0.1', 5185) connect to localhost:8085 conn_id:19

Feb 14 18:40:53.572 - [WARNING] front retry v18.xx-net.net/data?tid=53

Feb 14 18:40:53.876 - [WARNING] front retry v18.xx-net.net/data?tid=54

**Comment by xxnet** [comment]
试试：
https://github.com/XX-net/XX-Net/archive/3.10.1.zip

​调了参数，请再测试。

**Comment by challen88** [comment]
你好，过年几天没有测试，现在下载了最新的3.10.4，问题依旧

全局
属性 | 值
-- | --
请求数 | 0
响应时间 | 9999
往返数 | 0
较慢 | 0
重传 | 0
超时 | 0
当前速度 | Up: 0.0 B/s / Down: 0.0 B/s
使用总量 | Up: 0.0 B / Down: 0.0 B

GAE 前端
属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0.0 B / Down: 0.0 B

Cloudflare 前端
属性 | 值
-- | --
Score | 13307
成功数 | 0
失败数 | 0
工作数 | 1
使用总量 | Up: 0.0 B / Down: 0.0 B

TLS_Relay 前端
属性 | 值
-- | --
Score | False
成功数 | 0
失败数 | 0
工作数 | 0
使用总量 | Up: 0.0 B / Down: 0.0 B

**Comment by xxnet** [comment]
​下面的几个日志都贴来看看

**Comment by challen88** [comment]
X-Tunnel 日志
Feb 20 16:00:06.867 - [INFO] xxnet_version:3.10.4

Feb 20 16:00:06.868 - [INFO] server 127.0.0.1:1080 started.

Feb 20 16:00:06.868 - [INFO] Socks5 server listen:127.0.0.1:1080.

Feb 20 16:00:07.254 - [DEBUG] x_tunnel force update info

Feb 20 16:00:09.760 - [INFO] api:/login success t:2506

Feb 20 16:00:09.760 - [INFO] update xt_server v18.xx-net.net:443

Feb 20 16:00:09.760 - [INFO] request_balance host:v18.xx-net.net port:443 balance:0.000000 quota:599987561036.000000

Feb 20 21:26:34.386 - [DEBUG] x_tunnel force update info

Feb 20 21:26:35.723 - [INFO] api:/login success t:1335

Feb 20 21:26:35.723 - [INFO] request_balance host:v18.xx-net.net port:443 balance:0.000000 quota:599987561036.000000 

Cloudflare前端 日志
Feb 20 16:00:06.799 - [INFO] SSL use version:TLSv1_2

Feb 20 16:00:06.801 - [INFO] OpenSSL support alpn

Feb 20 16:00:06.801 - [INFO] load ip range file:C:\Program Files portable\Freegate\XX-Net\code\3.10.4\x_tunnel\local\cloudflare_front\ip_range.txt

Feb 20 16:00:06.804 - [INFO] load ip_list num:100, target num:100

Feb 20 16:00:07.235 - [INFO] updated cloudflare front domains from github.

Feb 20 16:00:13.591 - [DEBUG] create_ssl update ip:190.93.246.139 time:5328 h2:1 sni:aahms.net, host:mostlygood.ga

Feb 20 16:00:16.556 - [DEBUG] create_ssl update ip:104.28.116.84 time:628 h2:1 sni:thefamilybackyard.com, host:superx.gq

Feb 20 16:00:16.608 - [DEBUG] WindowUpdateFrame 2147418112

Feb 20 16:00:23.701 - [DEBUG] http2 190.93.246.139 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 20 16:00:23.701 - [DEBUG] 190.93.246.139 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 20 16:00:23.701 - [DEBUG] 190.93.246.139 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 20 16:00:23.701 - [DEBUG] 190.93.246.139 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Feb 20 16:00:23.701 - [DEBUG] 190.93.246.139 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Feb 20 16:00:23.701 - [DEBUG] 190.93.246.139 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Feb 20 16:04:16.939 - [DEBUG] 104.28.116.84 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 20 16:04:16.939 - [DEBUG] 104.28.116.84 worker close:disconnect:ConnectionResetError()

Feb 20 16:04:16.940 - [DEBUG] 104.28.116.84 close:disconnect:ConnectionResetError()

Feb 20 16:04:18.153 - [DEBUG] create_ssl update ip:162.159.235.160 time:639 h2:1 sni:dumpsterrentalmacon.club, host:mostlygood.ga

Feb 20 16:04:18.186 - [DEBUG] WindowUpdateFrame 2147418112

Feb 20 16:04:49.509 - [DEBUG] 162.159.235.160 _consume_single_frame:SysCallError(10054, 'WSAECONNRESET'), inactive time:31

Feb 20 16:04:49.510 - [DEBUG] 162.159.235.160 worker close:disconnect:SysCallError(10054, 'WSAECONNRESET')

Feb 20 16:04:49.510 - [DEBUG] 162.159.235.160 close:disconnect:SysCallError(10054, 'WSAECONNRESET')

Feb 20 16:04:50.332 - [DEBUG] create_ssl update ip:141.101.122.94 time:641 h2:1 sni:artesolecuador.com, host:flar.tk

Feb 20 16:04:50.365 - [DEBUG] WindowUpdateFrame 2147418112

Feb 20 16:08:50.706 - [DEBUG] 141.101.122.94 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 20 16:08:50.706 - [DEBUG] 141.101.122.94 worker close:disconnect:ConnectionResetError()

Feb 20 16:08:50.706 - [DEBUG] 141.101.122.94 close:disconnect:ConnectionResetError()

Feb 20 20:00:08.251 - [INFO] updated cloudflare front domains from github.

Feb 20 21:26:34.997 - [DEBUG] create_ssl update ip:190.93.247.141 time:596 h2:1 sni:techbestadsweb.site, host:flar.tk

Feb 20 21:26:35.024 - [DEBUG] WindowUpdateFrame 2147418112

Feb 20 21:26:35.723 - [DEBUG] POST center.flar.tk/login status:200 trace:0:start_request,0:get_task(19588),0:get_worker(0):190.93.247.141,0:h2_req,5:start send header,1:start send left body,0:end send left body,324:h2_get_head,0:get_response,:1 

Heroku前端 日志
无

TLS-Relay前端 日志
Feb 20 16:00:06.824 - [INFO] SSL use version:TLSv1_2

Feb 20 16:00:06.824 - [INFO] OpenSSL support alpn

Feb 20 16:00:06.826 - [INFO] load ip_list num:2, target num:2

Feb 20 16:00:08.239 - [DEBUG] create_ssl update ip:207.148.13.70 time:978 h2:1 sni:friendship.health.ml, host:

Feb 20 16:00:08.591 - [DEBUG] WindowUpdateFrame 33488897

Feb 20 16:00:14.635 - [DEBUG] connect 104.207.138.116 fail:error('certficate is none, sni:normal-bonus.us, top:',)

Feb 20 16:00:14.635 - [DEBUG] report_connect_fail:104.207.138.116

Feb 20 16:01:08.276 - [DEBUG] create ssl timeout fail.

Feb 20 16:04:08.793 - [DEBUG] 207.148.13.70 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 20 16:04:08.794 - [DEBUG] 207.148.13.70 worker close:disconnect:ConnectionResetError()

Feb 20 16:04:08.794 - [DEBUG] 207.148.13.70 close:disconnect:ConnectionResetError()

Feb 20 16:04:14.921 - [DEBUG] connect 207.148.13.70 fail:error('certficate is none, sni:friendship.health.ml, top:',)

Feb 20 16:04:14.921 - [DEBUG] report_connect_fail:207.148.13.70

Feb 20 16:04:21.924 - [DEBUG] connect 104.207.138.116 fail:error("conn fail, sni:normal-bonus.us, top: e:timeout('timed out',)",)

Feb 20 16:04:21.924 - [DEBUG] report_connect_fail:104.207.138.116

Feb 20 16:04:30.465 - [DEBUG] connect 207.148.13.70 fail:error('certficate is none, sni:friendship.health.ml, top:',)

Feb 20 16:04:30.465 - [DEBUG] report_connect_fail:207.148.13.70

Feb 20 16:04:46.013 - [DEBUG] connect 207.148.13.70 fail:error('certficate is none, sni:friendship.health.ml, top:',)

Feb 20 16:04:46.013 - [DEBUG] report_connect_fail:207.148.13.70

Feb 20 16:05:01.456 - [DEBUG] connect 207.148.13.70 fail:error('certficate is none, sni:friendship.health.ml, top:',)

Feb 20 16:05:01.456 - [DEBUG] report_connect_fail:207.148.13.70

Feb 20 16:05:09.499 - [DEBUG] create ssl timeout fail.

Feb 20 16:06:09.767 - [DEBUG] create ssl timeout fail.

Feb 20 16:07:10.324 - [DEBUG] create ssl timeout fail.

Feb 20 16:07:27.544 - [DEBUG] connect 104.207.138.116 fail:error("conn fail, sni:normal-bonus.us, top: e:timeout('timed out',)",)

Feb 20 16:07:27.544 - [DEBUG] report_connect_fail:104.207.138.116

Feb 20 16:08:06.573 - [DEBUG] connect 207.148.13.70 fail:error("conn fail, sni:friendship.health.ml, top: e:timeout('timed out',)",)

Feb 20 16:08:06.573 - [DEBUG] report_connect_fail:207.148.13.70

Feb 20 16:08:10.563 - [DEBUG] create ssl timeout fail.

Feb 20 16:09:11.188 - [DEBUG] create ssl timeout fail.

Feb 20 21:26:39.398 - [DEBUG] connect 104.207.138.116 fail:error("conn fail, sni:normal-bonus.us, top: e:timeout('timed out',)",)

Feb 20 21:26:39.398 - [DEBUG] report_connect_fail:104.207.138.116

Feb 20 21:26:46.400 - [DEBUG] connect 207.148.13.70 fail:error("conn fail, sni:friendship.health.ml, top: e:timeout('timed out',)",)

Feb 20 21:26:46.400 - [DEBUG] report_connect_fail:207.148.13.70

Feb 20 21:27:34.414 - [DEBUG] create ssl timeout fail.

**Comment by xxnet** [comment]
​连接正常，请确认代理设置

**Comment by challen88** [comment]
你好，可以上了，可能是订阅了多个代理规则互相冲突了，不好意思，给你添麻烦了。
