### ISSUE TITLE
3.10.2版本没找到模块管理功能

### ISSUE THREAD

**Issue by pengpengbirdy** [XX-net/XX-Net#9771]
想关闭一些模块，只用得上GAEPROXY功能
平时用不上X-Tunnel功能，升级后找不到位置去关闭了。

**Comment by xxnet** [comment]
​恩，这个需求可以满足，下次再改回来。

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9761

**Comment by xx-Chen** [comment]
3.10.3起x-tunnel和smart_router允许关闭，GAE因未独立不能关闭。
