### ISSUE TITLE
大大们求救 lede路由器 6to4 6in4问题

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#9772]
软路由 6to4 以前可以用 现在连不上了
            6in4 现在可以连上 但是装在路由器里的xx-net显示 IPV6 fail 与此同时 如果在win10电脑上打开XX-NET ipv6 是OK 说明6IN4隧道是可用的 
           那么如何设置才能使6to4可用或者是路由器里的XX-NET可以利用6IN4隧道

**Comment by sky123456789sky** [comment]
6to4是自动选择的 不需要自己动手填地址

**Comment by sky123456789sky** [comment]
奶奶的 原来是电信给悄悄换成内网IP了....

**Comment by SasamiMasakiJurai** [comment]
请问 怎么解决的？？？我现在路由里面也是显示ipv6 fail。。。。。。。。。。。。。

**Comment by sky123456789sky** [comment]
@SasamiMasakiJurai 向电信申请公网IP就解决了
