### ISSUE TITLE
新年送流量了~~

### ISSUE THREAD

**Issue by hsrrtx** [XX-net/XX-Net#9776]
20个吧，10G每个，X-tunnel的，留邮箱。

**Comment by qiuyu2** [comment]
wholovethepig@gmail.com

**Comment by MitchellClark666** [comment]
wyj2009sky@gmail.com

**Comment by foho8080** [comment]
foho8080@gmail.com

**Comment by AlexanderShang** [comment]
alexshang843537710@163.com

**Comment by XLX** [comment]
xionglinxin@gmail.com

**Comment by sanwan2009** [comment]
sanwan1979@gmail.com

**Comment by lvyousmile** [comment]
lvyousmile@163.com

**Comment by lon91ong** [comment]
lon91ong@qq.com

**Comment by fengyiway** [comment]
fengyiway@gmail.com

**Comment by vert404** [comment]
1379733223vert@gmail.com

**Comment by bohemian67** [comment]
liuqipaul@hotmail.com

**Comment by lzlmcx001** [comment]
kmkmkmzzxxoo@gmail.com

**Comment by mgxz** [comment]
mkgsola@163.som

**Comment by aixiu** [comment]
4815563@qq.com

**Comment by heracleshebe147** [comment]
iwantfreedom519@gmail.com

**Comment by pldeom** [comment]
dahvusin@sina.com

**Comment by guo333323** [comment]
guo333323@sina.cn

**Comment by xxuont** [comment]
xxuont@gmail.com

**Comment by largewhale** [comment]
largewhale@gmail.com

**Comment by xtuont** [comment]
xtuont@gmail.com

**Comment by wanghz** [comment]
wanghz@protonmail.com， 还有吗？

**Comment by gjbg1989** [comment]
😂你说呢，第廿一个？

**Comment by angzhi** [comment]
zl_iot@163.com

**Comment by angzhi** [comment]
貌似来晚了。。。

**Comment by hsrrtx** [comment]
好像人够了，先关贴。稍后送出~~

**Comment by hsrrtx** [comment]
没收到的就是邮箱没注册，不要问我怎么注册~~

**Comment by lon91ong** [comment]
@hsrrtx 之前留的邮箱:lon91ong@qq.com没有注册过, 也没法注册, 刚刚新换了邮箱: lon91ong@gmail.com 可以重新发一下吗?

**Comment by gjbg1989** [comment]
可惜了，老8成了尾巴😂

**Comment by lvyousmile** [comment]
不好意思，没看到，我以为发到我留的那个163邮箱里了，现在回复晚吗？还有X-tunnel流量送吗?😂

2018-02-20 13:40 GMT+08:00 gjbg1989 <notifications@github.com>:

**Comment by hsrrtx** [comment]
@lvyousmile 留邮箱~~

**Comment by lvyousmile** [comment]
lvyousmile@163.com,多谢了😄

2018-03-07 16:28 GMT+08:00 hsrrtx <notifications@github.com>:

**Comment by hsrrtx** [comment]
账户不存在。。。。。。

**Comment by lvyousmile** [comment]
@hsrrtx ,没用过x-tunnel,刚注册了一个，lvyousmile@gmail.com，能麻烦再试下么？

**Comment by hsrrtx** [comment]
好了~

**Comment by lvyousmile** [comment]
多谢了~~

**Comment by aixiu** [comment]
@hsrrtx 我也没用过。不过我注册了一个，可以再送一次么4815563@gmail.com

**Comment by huangkio** [comment]
谢 huangkaiu@gmail.com
