### ISSUE TITLE
关于升级的问题。

### ISSUE THREAD

**Issue by tinyperson** [XX-net/XX-Net#978]
![image](https://cloud.githubusercontent.com/assets/14156036/9811035/62aea1fc-58a7-11e5-8149-9f5833a414a5.png)

点击升级之后会在这个文件里，那么之前的数据是要重新上传吗？
或者说旧版本的数据怎么到新版本？
比如说：
![image](https://cloud.githubusercontent.com/assets/14156036/9811075/9a4eed10-58a7-11e5-985c-4ac4af3929de.png)
这个AppID有存档吗？
还是说只能重新输入？

为什么IP 数量变多了？
之前只有1000多个然后就没再搜索了，而且（ms）也没怎么高的数字，这些多出来的IP要怎么办？
![image](https://cloud.githubusercontent.com/assets/14156036/9811468/0f21b2a6-58aa-11e5-9bc7-5548b3dd4b49.png)

**Comment by wenliyang** [comment]
旧版本，data文件夹保留，你的设置文件在里面，其它文件夹及文件删除
新版本文件解压进去，升级完成

**Comment by wenliyang** [comment]
补充，我说的是手动升级方法，不是软件的更新功能

**Comment by tinyperson** [comment]
@wenliyang 
成功了！谢谢！

**Comment by tinyperson** [comment]
@wenliyang 
好像手动升级比较好。
