### ISSUE TITLE
GFW又开始发力了

### ISSUE THREAD

**Issue by bolaparte** [XX-net/XX-Net#9780]
真无语。。。

**Comment by gjbg1989** [comment]
Smart-Router ：XX-Net 3.10.3，一切正常，你可以访问真正的互联网了。

**Comment by gjbg1989** [comment]
莫非类型 natawareclient 比 enterpriseclient 强劲？试试：管理权限运行
netsh int ipv6 set teredo natawareclient default default 3544

**Comment by dahai058** [comment]
联通20兆光纤，3.9.6版本设置natawareclient后油管直播480p点播720p非常稳定1080p缓冲较慢。但不知natawareclient是什么意思啊？

**Comment by bolaparte** [comment]
XX-Net 3.10.3，一切正常，你可以访问真正的互联网了。

**Comment by bolaparte** [comment]
升级之后正常了，多谢各位大佬！！
