### ISSUE TITLE
GAEProxy连接尚未建立，，，一直这样 我是用的ipv6 是最新版3.10.3

### ISSUE THREAD

**Issue by a1798636524** [XX-net/XX-Net#9781]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
xxnet-version: 3.10.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:2904
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 150
ip-quality: 262
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
这是诊断信息

**Comment by gjbg1989** [comment]
贴运行 netsh int ipv6 show teredo 结果

**Comment by a1798636524** [comment]
请问这个程序在哪里啊 XX-net  文件夹里没有这个程序

**Comment by gjbg1989** [comment]
命令提示符窗口

**Comment by a1798636524** [comment]
大佬，WIN+R 打开输入netsh int ipv6 show teredo以后，弹窗出来瞬间自己关了，，，看不清，怎么办呢

**Comment by a1798636524** [comment]
来不及看清就自动关了

**Comment by gjbg1989** [comment]
😱先打开命令提示符窗口，在窗口内运行。。。

**Comment by a1798636524** [comment]
大佬新年快乐，，我再试试

**Comment by a1798636524** [comment]
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器
大佬是这样

**Comment by gjbg1989** [comment]
保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
使用ping超时的微软服务器或许更稳定！(win7除外？)管理权限运行
netsh int ipv6 set teredo enterpriseclient default
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by gjbg1989** [comment]
试试：无线网络属性内取消勾选 IPv6 协议

**Comment by a1798636524** [comment]
谢谢大佬，，无线网络属性内取消勾选 IPv6 协议就可以了，，再次祝大佬在新的一年里大吉大利，恭喜发财

**Comment by pendave** [comment]
这个挺好用的：
每次关机或者重启之前操作一下就可以！
#9496 预防开机后IPv6 状态 Fail 及隧道适配器驱动感叹号问题
