### ISSUE TITLE
求助:xx-net 打不开配置页面

### ISSUE THREAD

**Issue by masamibf** [XX-net/XX-Net#9787]
下载最新版xx-net后打不开配置页面了 （http://localhost:8085/ 无法访问）

用的谷歌浏览器

之前用的旧版本可以打开并且可以正常使用

请教大神什么原因

**Comment by gjbg1989** [comment]
手动下载、解压为佳😱

**Comment by masamibf** [comment]
已解决，是Windows防火墙的原因，重置一下就好啦
