### ISSUE TITLE
尚未建立连接

### ISSUE THREAD

**Issue by adolescent2** [XX-net/XX-Net#9796]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  最新版本
  看过并试过重置IPV6,但问题依然存在

* 简单描述遇到的问题：
从家来学校的校园网后，XXnet就显示无法尚未建立连接

* 做过哪些尝试：
重置IPV6

* 请贴出相关的日志
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10240
os-system: Windows
os-version: 10.0.10240
os-release: 10
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:1194 ipv4:0 ipv6:1112
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 315
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
#9783
