### ISSUE TITLE
为啥gae-proxy模块屏蔽了推特的推文搜索功能

### ISSUE THREAD

**Issue by chiupak** [XX-net/XX-Net#9799]
之前一直觉得奇怪，为什么推特只能搜索用户，却搜索不到相关的推文；点进热门话题tag也看不见相关推文，还以为是推特没有这个功能，今天升级3.10.4后注册了个x-tunnel账号才发现是可以搜索的，不过gae-proxy屏蔽了⊙▽⊙
为了推广x-tunnel么，不过为啥维基什么的又能看

**Comment by zhencaihao** [comment]
这个情况我记得好像是去年国庆这段时间开始的，只能搜用户，其他都搜索不了。

**Comment by gosex** [comment]
推特不能搜索，总感觉少了点啥 😛
 希望能解决下

**Comment by xx-Chen** [comment]
https://github.com/XX-net/XX-Net/issues/8122#issuecomment-342727674
