### ISSUE TITLE
为什么Google Chrome浏览器翻译功能不能用啊国外网站能上了

### ISSUE THREAD

**Issue by zhouhao1217** [XX-net/XX-Net#98]
国外网站能上了就是用不了Google Chrome浏览器翻译功能一直翻译失败

**Comment by xxnet** [comment]
没试过，怀疑浏览器本身没有受SwitchSharp控制。

可以试试修改IE的全局代理

在 2015年4月1日 上午8:31，zhouhao1217 <notifications@github.com>写道：

**Comment by zhouhao1217** [comment]
可以试试修改IE的全局代理，这个怎么操作啊。

**Comment by xxnet** [comment]
右键XX-Net图标，点菜单中Enable Proxy就可以了。
取消设置，点Disable Proxy。

2015-04-02 6:13 GMT-04:00 zhouhao1217 <notifications@github.com>:

**Comment by zhouhao1217** [comment]
更新到 XX-Net-1.13.6好像没有 右键XX-Net图标，点菜单中Enable Proxy就可以了。
![q e4 evf 2wh mplat4lo n](https://cloud.githubusercontent.com/assets/11462060/7610948/5bcfe682-f9b3-11e4-9c96-c46eff799776.png)

**Comment by redstoneleo** [comment]
把
*://*.googleapis.com.*/*
换成
.*://.*[^(translate)]\.googleapis\.com/.*
并且把对应条目的匹配模式由“通配符”切换成“正则表达式”
然后就OK了
http://www.zhihu.com/question/21366346

**Comment by hardstruglling** [comment]
@redstoneleo 实测有效
