### ISSUE TITLE
xx-net的速度已“狂拽酷炫刁炸天”，坦克算个鸟!

### ISSUE THREAD

**Issue by aOJzQT** [XX-net/XX-Net#980]
某地电信，上图不解释
![xxnet](https://cloud.githubusercontent.com/assets/13990565/9815049/b4ca6568-5882-11e5-9fec-0729b1b20ab2.png)

**Comment by aOJzQT** [comment]
Chrome目前只适合用来看油管，其他请用Firefox，匿名请用Tor Browser。

https://ipleak.net/

How to Disable WebRTC

✔ Disable WebRTC in Firefox
WebRTC in Mozilla Firefox is partially supported since Firefox 22, and it's enabled by default.

To disable WebRTC in Firefox, go to about:config and toggle media.peerconnection.enabled to false.

?Disable WebRTC in Chrome
WebRTC in Google Chorme is supported and enabled by default since Chorme version 23 (and based on it, ex. Opera, Vivaldi).

Bad news:

You CAN'T turn off WebRTC on desktop version of Google Chrome, Disable WebRTC flag is available only on Android.

Good news:

There is a Chrome Extension: WebRTC Block.

Extension hides your public IP when you're behind VPN. It will leak only VPN's public IP, but not your real provider IP address! Extension also hides your Local/NAT IP addresses.

Unfortunately, if you're behind proxy but not VPN, WebRTC Block will not help you.

I can't do anything, and no one can. This piece of the periodic table is ****ed by design. So PLEASE stop insulting me on mail and webstore that it's "NOT WORKING !!!" :)

Just use FF. There is no drama.

**Comment by wenliyang** [comment]
WebRTC Block 这扩展没用的，还是用火狐浏览器好了

**Comment by ugvf2009** [comment]
我【这里速度更牛逼，吉林移动】http://i.minus.com/imDb65CkCKI4e.jpg

**Comment by skybai1987** [comment]
你这都有10M的网速了啊。像这些IP是怎么扫出来的，好用的IP保存在哪里啊。这个XX-NET原理是怎么样的。我看了半天，都没有弄明白

**Comment by lele2010lele** [comment]
你这个显示插件是什么

**Comment by cdmask** [comment]
鼠标放在视频上面，右击看到stats for nerds就是它了
