### ISSUE TITLE
DisabledComponents自动更改与隧道开启问题

### ISSUE THREAD

**Issue by liushuiguadanbo** [XX-net/XX-Net#9802]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：一重启DisabledComponents就自动变成8 要手动改成0 另外ipconfig/all里没有隧道适配器 怎么办呀

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by liushuiguadanbo** [comment]
设备管理器中没有这个Teredo Tunneling Pseudo-Interface

**Comment by gjbg1989** [comment]
先详列贵机器上的杀毒、管理控制软件😂

**Comment by liushuiguadanbo** [comment]
ping -6 [2001:470:1:18::125]显示正在 Ping 2001:470:1:18::125 具有 32 字节的数据:
PING：传输失败。常见故障。
PING：传输失败。常见故障。
PING：传输失败。常见故障。
PING：传输失败。常见故障。

**Comment by liushuiguadanbo** [comment]
ipconfig/all里没有teredo 感觉是这个原因=。=为什么没有呢，。。。是不是没有Teredo Tunneling Pseudo-Interface导致的呀  我手动安装了一个Microsoft Teredo Tunneling Adapter

**Comment by gjbg1989** [comment]
貌似“手动安装了一个Microsoft Teredo Tunneling Adapter”是不对的
没有国祸的系统保护，“一重启DisabledComponents就自动变成8”严重不科学😱

**Comment by liushuiguadanbo** [comment]
emmm变成8这个我可以手动改。。。那Microsoft Teredo Tunneling Adapter应该卸载吗 那我没有Teredo Tunneling Pseudo-Interface怎么办呀

**Comment by gjbg1989** [comment]
应该卸载
中文版：https://support.microsoft.com/zh-cn/help/929852/ 下载上排第一个执行后重启——在前缀策略中优先使用 IPv4 over IPv6

**Comment by gjbg1989** [comment]
https://support.xbox.com/zh-CN/xbox-on-windows/social/troubleshoot-party-chat

![default](https://user-images.githubusercontent.com/13290970/36462950-83ad5cc0-1701-11e8-8219-265c4d8f2b53.png)

**Comment by liushuiguadanbo** [comment]
emmm问题是运行netsh interface Teredo set state type=default以后不会重新安装隧道适配器=。=

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9783#issuecomment-366498197

**Comment by liushuiguadanbo** [comment]
弃用 ISP 商 DNS ，指定 IPv4 及 IPv6 DNS ？   emmmm这句话是什么意思呀

**Comment by liushuiguadanbo** [comment]
netsh int ipv6 set teredo natawareclient default default 3544
显示参数错误

**Comment by gjbg1989** [comment]
😱xp 系统？

**Comment by liushuiguadanbo** [comment]
win8呀

**Comment by gjbg1989** [comment]
😂那就只有没以管理权限运行的锅？

**Comment by liushuiguadanbo** [comment]
emmmm我感觉问题应该是我的设备管理器里没有Teredo Tunneling Pseudo-Interface 的问题 导致我的teredo的状态一直都是offline。。。。有没有办法安装上这个玩意呀

**Comment by gjbg1989** [comment]
确保系统服务IP Helper 为自动并已启动，结束进程 pythonw.exe，先前修改的 ipv6 组策略退回到默认值的全部“未配置”，打开 https://support.microsoft.com/zh-cn/help/929852/ 下载上下2排最后那个工具，先运行上排那个，再运行下排那个，机器重启，先不要运行XX-Net，运行 netsh int ipv6 show teredo 看结果：状态dormant即已正常。

**Comment by liushuiguadanbo** [comment]
我查了一下好像是DisabledComponents改成0然后重启就会自动安装teredo可是我重启就变成8了也安不上teredo的适配器。。。。

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/36467679-c7b641fc-171a-11e8-855b-b9e17a387547.png)

**Comment by gjbg1989** [comment]
😱莫非国产品牌机器？

**Comment by gjbg1989** [comment]
结束进程 pythonw.exe，运行 XX-Net 目录内的 disable_ipv6.bat，再 enable_ipv6.bat，最后查看系统设备
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by liushuiguadanbo** [comment]
好了 把DisabledComponents的控制权限全部改为读取 这样重启就不会自动变成8了 蟹蟹大佬
