### ISSUE TITLE
3.10.4一升级就不能用

### ISSUE THREAD

**Issue by cnjameschan** [XX-net/XX-Net#9804]
3.10.4一升级就不能用，重新用回3.8.7,X_tunnel,付费用户

**Comment by gjbg1989** [comment]
😂姿势不对？
![default](https://user-images.githubusercontent.com/13290970/36468205-6a392938-171d-11e8-811d-552bde217a67.png)

**Comment by cnjameschan** [comment]
是很奇怪，而且点下面的配置什么的会假死

**Comment by gjbg1989** [comment]
删除目录data以外的文件夹及文件，手动下载解压。。。

**Comment by cnjameschan** [comment]
我试试看
我都是自动升级的，哈

**Comment by cnjameschan** [comment]
嗯，好像行了，自动升级偷懒估计不行，哈，谢谢
