### ISSUE TITLE
X-Tunnel     Get Fail:status:602啥意思？

### ISSUE THREAD

**Issue by GFconcept** [XX-net/XX-Net#9808]
Feb 21 21:01:41.568 - [WARNING] h2 timeout 104.24.86.89 task_trace:0:start_request,0:get_task(33),1:get_worker:104.24.86.89,0:h2_req,199:h2_get_head,0:get_response,:9877 worker_trace: processed:1, h2.stream_num:0, sni:soldouttoysxmas.com

Feb 21 21:01:41.771 - [WARNING] h2 timeout 104.16.26.46 task_trace:0:start_request,0:get_task(0),0:get_worker:104.16.26.46,0:h2_req,197:h2_get_head,0:get_response,:9881 worker_trace: processed:1, h2.stream_num:0, sni:franklinmahotel.com

Feb 21 21:01:41.973 - [WARNING] h2 timeout 104.27.130.187 task_trace:0:start_request,0:get_task(0),0:get_worker:104.27.130.187,0:h2_req,203:h2_get_head,0:get_response,:9865 worker_trace: processed:1, h2.stream_num:0, sni:anvilonline.net

Feb 21 21:01:41.989 - [DEBUG] 104.28.4.211 fail:timeout('timed out',)

Feb 21 21:01:41.989 - [DEBUG] report_connect_fail:104.28.4.211

Feb 21 21:01:42.245 - [DEBUG] 104.24.59.101 fail:error(' certficate is none',)

Feb 21 21:01:42.245 - [DEBUG] report_connect_fail:104.24.59.101

Feb 21 21:01:42.587 - [DEBUG] 162.159.239.52 fail:timeout('timed out',)

Feb 21 21:01:42.587 - [DEBUG] report_connect_fail:162.159.239.52

Feb 21 21:01:42.883 - [DEBUG] ip:172.64.132.40 real fail

Feb 21 21:01:43.008 - [DEBUG] 104.16.235.161 fail:error(' certficate is none',)

Feb 21 21:01:43.008 - [DEBUG] report_connect_fail:104.16.235.161

Feb 21 21:01:44.201 - [DEBUG] create_ssl update ip:104.27.84.57 time:1614 h2:1 sni:anvilonline.net top:freenum.cf

Feb 21 21:01:44.285 - [DEBUG] 141.101.113.16 fail:Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],)

Feb 21 21:01:44.285 - [DEBUG] report_connect_fail:141.101.113.16

Feb 21 21:01:44.285 - [DEBUG] ip:104.28.25.147 real fail

Feb 21 21:01:44.301 - [DEBUG] 141.101.122.152 fail:error(' certficate is none',)

Feb 21 21:01:44.301 - [DEBUG] report_connect_fail:141.101.122.152

Feb 21 21:01:44.753 - [DEBUG] 104.16.26.46 fail:error(' certficate is none',)

Feb 21 21:01:44.753 - [DEBUG] report_connect_fail:104.16.26.46

Feb 21 21:01:45.003 - [DEBUG] 104.25.68.215 fail:error(' certficate is none',)

Feb 21 21:01:45.003 - [DEBUG] report_connect_fail:104.25.68.215

Feb 21 21:01:46.049 - [DEBUG] 104.31.230.171 fail:error(' certficate is none',)

Feb 21 21:01:46.049 - [DEBUG] report_connect_fail:104.31.230.171

Feb 21 21:01:46.160 - [DEBUG] connect 190.93.246.107 fail:[('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')] cost:1407

Feb 21 21:01:46.160 - [DEBUG] report_connect_fail:190.93.246.107

Feb 21 21:01:46.191 - [WARNING] h2 timeout 104.16.26.46 task_trace:0:start_request,0:get_task(4),0:get_worker:104.16.26.46,0:h2_req,210:h2_get_head,0:get_response,:9849 worker_trace: processed:1, h2.stream_num:0, sni:yanes.io

Feb 21 21:01:46.532 - [DEBUG] 190.93.247.251 fail:error(' certficate is none',)

Feb 21 21:01:46.532 - [DEBUG] report_connect_fail:190.93.247.251

Feb 21 21:01:46.735 - [DEBUG] 190.93.245.61 fail:error(' certficate is none',)

Feb 21 21:01:46.735 - [DEBUG] report_connect_fail:190.93.245.61

Feb 21 21:01:47.296 - [DEBUG] 198.41.214.148 fail:error(' certficate is none',)

Feb 21 21:01:47.296 - [DEBUG] report_connect_fail:198.41.214.148

Feb 21 21:01:47.411 - [DEBUG] 104.19.22.194 fail:error(' certficate is none',)

Feb 21 21:01:47.411 - [DEBUG] report_connect_fail:104.19.22.194

Feb 21 21:01:48.417 - [WARNING] h2 timeout 104.25.68.215 task_trace:0:start_request,0:get_task(2),0:get_worker:104.25.68.215,0:h2_req,187:h2_get_head,0:get_response,:9868 worker_trace: processed:1, h2.stream_num:0, sni:milfmovies.cf

Feb 21 21:01:48.589 - [WARNING] h2 timeout 190.93.246.107 task_trace:0:start_request,0:get_task(0),0:get_worker:190.93.246.107,0:h2_req,233:h2_get_head,0:get_response,:9806 worker_trace: processed:1, h2.stream_num:0, sni:soldouttoysxmas.com

Feb 21 21:01:48.962 - [DEBUG] create_ssl update ip:104.20.107.3 time:2226 h2:1 sni:mozgcyhjj734z75f.xyz top:freenum.cf

Feb 21 21:01:49.596 - [DEBUG] ip:104.25.131.96 real fail

Feb 21 21:01:50.161 - [DEBUG] 104.24.194.34 fail:timeout('timed out',)

Feb 21 21:01:50.161 - [DEBUG] report_connect_fail:104.24.194.34

Feb 21 21:01:50.366 - [DEBUG] connect 198.41.215.185 fail:[('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')] cost:392

Feb 21 21:01:50.367 - [DEBUG] report_connect_fail:198.41.215.185

Feb 21 21:01:50.453 - [DEBUG] 190.93.246.70 fail:error(' certficate is none',)

Feb 21 21:01:50.453 - [DEBUG] report_connect_fail:190.93.246.70

Feb 21 21:01:50.454 - [DEBUG] 190.93.247.54 fail:error(' certficate is none',)

Feb 21 21:01:50.454 - [DEBUG] report_connect_fail:190.93.247.54

Feb 21 21:01:50.951 - [DEBUG] create_ssl update ip:104.31.189.15 time:583 h2:1 sni:franklinmahotel.com top:freenum.cf

Feb 21 21:01:51.706 - [DEBUG] 162.159.229.179 fail:error(' certficate is none',)

Feb 21 21:01:51.706 - [DEBUG] report_connect_fail:162.159.229.179

Feb 21 21:01:54.604 - [DEBUG] ip:104.19.198.107 real fail

Feb 21 21:01:54.755 - [DEBUG] 104.24.248.167 fail:error(' certficate is none',)

Feb 21 21:01:54.755 - [DEBUG] report_connect_fail:104.24.248.167

Feb 21 21:01:55.331 - [DEBUG] create_ssl update ip:172.64.59.76 time:575 h2:1 sni:createcookingschool.com top:freenum.cf

Feb 21 21:01:55.526 - [DEBUG] 162.159.223.178 fail:error(' certficate is none',)

Feb 21 21:01:55.526 - [DEBUG] report_connect_fail:162.159.223.178

Feb 21 21:01:55.890 - [DEBUG] 104.20.93.31 fail:error(' certficate is none',)

Feb 21 21:01:55.890 - [DEBUG] report_connect_fail:104.20.93.31

Feb 21 21:01:56.157 - [DEBUG] create_ssl update ip:104.16.31.215 time:630 h2:1 sni:anvilonline.net top:freenum.cf

Feb 21 21:01:56.297 - [DEBUG] create_ssl update ip:162.159.131.184 time:4342 h2:1 sni:dogpuppy.xyz top:freenum.cf

Feb 21 21:01:58.116 - [DEBUG] create_ssl update ip:104.31.185.210 time:6409 h2:1 sni:festivalarabe.com top:freenum.cf

**Comment by GFconcept** [comment]
Feb 21 21:13:00.717 - [INFO] use config_path:D:\TEMP\XX-Net-3.7.8\data\x_tunnel\client.json

Feb 21 21:13:00.717 - [INFO] X-Tunnel window:33554432

Feb 21 21:13:00.733 - [INFO] Socks5 server listen:127.0.0.1:1080.

Feb 21 21:13:22.969 - [DEBUG] x_tunnel force update info

Feb 21 21:13:23.740 - [INFO] api:/login success t:770

Feb 21 21:13:23.740 - [INFO] update xt_server v3.xx-net.net:443

Feb 21 21:13:23.740 - [INFO] request_balance host:v3.xx-net.net port:443 balance:0.000000 quota:309150554568.000000

Feb 21 21:13:23.981 - [DEBUG] x-tunnel web_control 127.0.0.1:17871 POST /login

Feb 21 21:13:33.842 - [WARNING] login session fail, status:602

Feb 21 21:13:33.842 - [WARNING] x-tunnel login_session fail, session not start

Feb 21 21:13:34.076 - [WARNING] api:/login fail:status:602 t:10

**Comment by xxnet** [comment]
​602 是连接失败的意思。

请用最新版本 3.10.4
