### ISSUE TITLE
3.10.4 查看系统-状态时僵死

### ISSUE THREAD

**Issue by jay0063** [XX-net/XX-Net#9812]
疑似mac下bug  OS 10.11.6
后台管理进入“系统”－“状态”后，程序僵死，点任何功能没有反应。
代理功能仍能正常使用

**Comment by xx-Chen** [comment]
“僵死”后能自己恢复吗？

**Comment by jay0063** [comment]
chrome
版本 64.0.3282.140（正式版本） （64 位）
从反馈到现在（5h）没管，我刚才试了下可以恢复。
我没打开gea

找了下launcher日志：

```
Feb 22 17:21:09.894 - [DEBUG] launcher web_control 127.0.0.1:50027 GET /update?cmd=get_info 
Feb 22 17:21:10.894 - [WARNING] request /module/gae_proxy/control/status no module in path
Feb 22 17:21:10.897 - [WARNING] request /module/gae_proxy/control/status no module in path 
```

**Comment by xx-Chen** [comment]
webUI卡顿的确有可能，因为有ajax关了异步，但时长应该在毫秒级（只涉及对web_control.py获取设置的请求，实测11.97毫秒），而且是在整个webUI框架里，只要是webUI的页面应该都有影响而不是只状态页。

另外，GAE模块和webUI的联系还没理干净，GAE模块不打开webUI是没法正常工作的。
看你提供的日志也的确是因为GAE模块没打开，
/module/gae_proxy/control/status 涉及基本上整个状态页状态的获取了。

**Comment by jay0063** [comment]
@xx-Chen 打开GAE解决了。
不过3.10.4 webUI没有控制GAE的开关（我临时退回到旧版本打开的），mark下个版本可以加下。
辛苦了

**Comment by xx-Chen** [comment]
@jay0063 其实已经加回来了，但不适合单发一版，等下一版就会包含了。
