### ISSUE TITLE
过大的js文件加载时被截断

### ISSUE THREAD

**Issue by XndroidDev** [XX-net/XX-Net#9813]
这个BUG估计存在了很久, 测试发现 text/javascript请求response 较大时会被截断.
之前这个问题基本不会出现, 但3.8.6版之后, 对不支持br编码的浏览器请求可能返回br编码的网站时会将 `Accept-Encoding` 中的 gzip去除, 导致 https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js 较大, 超过1M, 被截断(实际大小:1,241,399 字节, response 大小:548,576 字节). 浏览器会出现 `net::ERR_CONTENT_LENGTH_MISMATCH` , 无法播放, youtube. 

另见 : 
https://github.com/XX-net/XX-Net/issues/9643
https://github.com/XX-net/XX-Net/issues/8852

@xxnet

**Comment by XndroidDev** [comment]
重新看了一下, 根据 https://github.com/XX-net/XX-Net/issues/9643
9643中禁用插件后正常了, 我并没有找到其他大的js文件来测试. 不过在3.8.6前并没有出现这个问题, 我认为应该是GAE的bug

**Comment by xxnet** [comment]
​好的，我测试下。

**Comment by XndroidDev** [comment]
相关日志:
```
Feb 23 22:30:38.568 - [DEBUG] GAE GET https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js
Feb 23 22:30:39.626 - [INFO] GAE t:1057 s:0 GET https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js 0:start_request,0:get_task,0:get_worker:2607:f8b0:401c:5::a,7:h1_req,1047:h1_get_head,0:get_response,:0
Feb 23 22:30:39.628 - [DEBUG] GAE GET https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js
Feb 23 22:30:39.987 - [INFO] RangeFetch 0-1241398 started('https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js')
Feb 23 22:30:46.745 - [DEBUG] RangeFetch [2607:f8b0:4007:1c::c] 44% length:548576 range:bytes 0-548575/1241399 https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js 0:start_request,0:get_task,0:get_worker:2607:f8b0:4007:1c::c,0:h1_req,348:h1_get_head,9:get_response,6756:h1_finish[SP:81127],:0
Feb 23 22:30:57.461 - [WARNING] RangeFetch try max times, exit. https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js
Feb 23 22:30:57.462 - [ERROR] get notify but no data
```
https://github.com/XX-net/XX-Net/blob/1c0a3db305b0ff67742a9e6a20ada6379131b6f1/code/default/gae_proxy/local/gae_handler.py#L758
中 response.status 值为 416

**Comment by XndroidDev** [comment]
似乎 https://www.youtube.com/yts/jsbin/player-vflLdwQUM/zh_CN/base.js 并不支持 range fetch ,
可否 将 https://github.com/XX-net/XX-Net/blob/1c0a3db305b0ff67742a9e6a20ada6379131b6f1/code/default/gae_proxy/local/proxy.ini#L75
中的 maxsize  调大, 2M 左右
@xxnet

**Comment by xxnet** [comment]
​可以调大的，设置这么小，是希望分小块下载会快一些，但是如果影响可用性，必须调整。
