### ISSUE TITLE
我的右上角怎么没有xxnet自动切换的选项了

### ISSUE THREAD

**Issue by liangliangge521** [XX-net/XX-Net#9814]
![115 20180222155834](https://user-images.githubusercontent.com/24711077/36527449-c227d96c-17ec-11e8-8116-5b3c3146cbed.png)

**Comment by liangliangge521** [comment]
昨天还有来着，今天重做的系统，在登录一看，右上角没有了xxnet自动切换的选项了

**Comment by gjbg1989** [comment]
看来是程序员老大取错了名😂

**Comment by liangliangge521** [comment]
好的

**Comment by xx-Chen** [comment]
@gjbg1989 怎么就成取错名了。😂
