### ISSUE TITLE
谷歌CLOUDPLATFORM有了一个错误报告

### ISSUE THREAD

**Issue by NOoNE7** [XX-net/XX-Net#9828]
点开后显示UnboundLocalError: local variable 'traceback' referenced before assignment，这是什么情况

**Comment by xxnet** [comment]
​具体在哪个地方看到？

trackback 是一个python库，应该是没有import 就直接调用了

**Comment by NOoNE7** [comment]
@xxnet 就在https://console.cloud.google.com/home/这个网站，我有两个项目ID，都出现了这个错误
![default](https://user-images.githubusercontent.com/33977540/36627380-a67e67a8-197c-11e8-94ec-744a6558e4fc.PNG)

**Comment by xxnet** [comment]
​可以不理他
