### ISSUE TITLE
临时解决办法 3.10.4 给其他设备提供代理时 提示"检查浏览器代理设置" 

### ISSUE THREAD

**Issue by 253681319** [XX-net/XX-Net#9829]
不是很懂python 
SMART ROUTER模块的监听地址貌似写死了127.0.0.1 导致其他设备无法访问proxy.pac文件
**临时办法**
打开 `code/3.10.4/smart_router/local/__init__.py`
复制第62行并注释掉该行

 _# config.set_var("proxy_bind_ip", "127.0.0.1")
 _# 黏贴刚才复制的62行 改为如下_
 _config.set_var("proxy_bind_ip", "0.0.0.0")__

重启XX即可

**Comment by gjbg1989** [comment]
参考：https://github.com/xyuanmu/XX-Mini proxy.ini 配置文件说明：
建议大家在 data 目录新建一份 manual.ini 文件，优先级大于 proxy.ini 设置，避免升级的时候设置丢失。。。

**Comment by 253681319** [comment]
@gjbg1989 这个地方貌似写死了127.0.0.1 并没有读取manual.ini里关于pac的定义，以前版本是可以的

**Comment by gjbg1989** [comment]
manual.ini 文件，貌似优先级最高，高于“写死了127.0.0.1 ”

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 😱打开——允许远程访问控制页(帮助)

**Comment by 253681319** [comment]
@gjbg1989 我可能问题描述的不是很清楚，我不是要改远程访问控制页，而是要给其他设备共享自动代理配置文件，默认情况下这个文件是 `http://127.0.0.1:8086/proxy.pac`，本机用是没有问题的，给其他的设备共享代理的时候要改这个ip
以前版本我的manual.ini里是这么配置的
```
[pac]
enable = 1
ip = 0.0.0.0
port = 8086
```
并没有问题，但是这个3.10.4不起作用，netstat查看是监听的127的8086没有监听0.0.0.0，我改了一下就可以了，可能我理解错了吧，感觉下面这句是写死了的样子，不是很懂python
`config.set_var("proxy_bind_ip", "127.0.0.1")`
也许是我哪里搞错了

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1

**Comment by 253681319** [comment]
@gjbg1989 那是针对 gae_proxy 模块的 但是SMART ROUTER 模块读取的不是这个，具体配置文件格式没有研究，我试了一下复制到smart_router目录下一份gae_proxy的manual.ini并没有起作用，具体格式没有找到，可能我写的不对，如果你知道可以发一下，多谢

**Comment by xx-Chen** [comment]
@253681319 你都找到__init__.py了你就没往上看看这整个函数是干啥的？😂

**Comment by 253681319** [comment]
@xx-Chen 粗看了下 没深入 哈

**Comment by chameleonscool** [comment]
打开XX-Net/data/smart_router/config.json
改成以下内容就可以了，
{
"proxy_bind_ip":"0.0.0.0"
}

**Comment by xxnet** [comment]
系统菜单中，允许远程连接就可以了

**Comment by 253681319** [comment]
@chameleonscool 3ks 正解

**Comment by nickonline2005** [comment]
@xxnet 3.10.4中，已经开启远程连接，但还是会监听在127.0.0.1上，只有改config.json或者直接代码里改。看代码里有判断开启远程就监听在0.0.0.0,但是不起作用？

**Comment by xxnet** [comment]
​打开允许远程访问的开关，显示的日志贴来看

**Comment by nickonline2005** [comment]
xxnet在ubuntu server上，没法在本地登陆设置页啊

**Comment by xxnet** [comment]
​那可以在命令行启动时，加入参数：

./start -allow_remote

**Comment by nickonline2005** [comment]
XX-Net version:3.10.4
PuTTY X11 proxy: Unsupported authorisation protocol
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Mar 01 16:18:14.722 [launcher][INFO] use build-in openssl lib
Mar 01 16:18:14.825 [launcher][INFO] start XX-Net 3.10.4
Mar 01 16:18:14.825 [launcher][DEBUG] start confirm_xxnet_exit
Mar 01 16:18:14.829 [launcher][DEBUG] <0>: try to terminate xxnet:8085
Mar 01 16:18:15.833 [launcher][DEBUG] <1>: try to terminate xxnet:8085
Mar 01 16:18:16.835 [launcher][DEBUG] good, xxnet:8085 clear!
Mar 01 16:18:16.836 [launcher][DEBUG] finished confirm_xxnet_exit
Mar 01 16:18:16.836 [launcher][INFO] command args:-allow_remote
Mar 01 16:18:16.849 [gae_proxy][INFO] load manual.ini success
Mar 01 16:18:16.884 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
Mar 01 16:18:16.943 [gae_proxy][INFO] SSL use version:TLSv1_2
Mar 01 16:18:16.946 [gae_proxy][INFO] OpenSSL support alpn
Mar 01 16:18:16.950 [gae_proxy][INFO] load ip range file:/home/ydl/XXNet/code/3.10.4/gae_proxy/local/ip_range.txt
Mar 01 16:18:17.060 [gae_proxy][DEBUG] network IPv4 is ok, cost:175 ms
Mar 01 16:18:17.099 [gae_proxy][INFO] load google ip_list num:3000, gws num:3000
Mar 01 16:18:17.132 [gae_proxy][INFO] load manual.ini success
Mar 01 16:18:17.168 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
Mar 01 16:18:17.168 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
Mar 01 16:18:17.169 [gae_proxy][INFO] ------------------------------------------------------
Mar 01 16:18:17.169 [gae_proxy][INFO] Python Version     : 2.7.14
Mar 01 16:18:17.169 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:17.10; ID:artful
Mar 01 16:18:17.169 [gae_proxy][INFO] Listen Address     : 0.0.0.0:8087
Mar 01 16:18:17.169 [gae_proxy][INFO] ------------------------------------------------------
/home/ydl/XXNet/code/3.10.4/python27/1.0/lib/noarch/OpenSSL/crypto.py:1110: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  self._x509, digest, result_buffer, result_length)
Mar 01 16:18:17.174 [gae_proxy][DEBUG] Importing CA
Mar 01 16:18:17.175 [gae_proxy][DEBUG] Begin importing CA to Firefox
Mar 01 16:18:17.175 [gae_proxy][INFO] server 0.0.0.0:8087 started.
Mar 01 16:18:17.230 [launcher][INFO] module gae_proxy started
Mar 01 16:18:17.230 [launcher][INFO] start gae_proxy time cost:393 ms
Mar 01 16:18:17.244 [smart_router][DEBUG] x_tunnel not running
Mar 01 16:18:17.244 [smart_router][INFO] Load file:/home/ydl/XXNet/code/3.10.4/smart_router/local/gfw_black_list.txt
Mar 01 16:18:17.249 [smart_router][INFO] Load file:/home/ydl/XXNet/code/3.10.4/smart_router/local/gfw_white_list.txt
Mar 01 16:18:17.252 [smart_router][DEBUG] use local DNS server:127.0.0.53
Mar 01 16:18:17.253 [smart_router][INFO] server 0.0.0.0:8086 started.
Mar 01 16:18:17.253 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
Mar 01 16:18:17.253 [smart_router][WARNING] bind DNS 0.0.0.0:53 fail
Mar 01 16:18:17.254 [smart_router][WARNING] You can try: install libcap2-bin
Mar 01 16:18:17.254 [smart_router][WARNING] Then: sudo setcap 'cap_net_bind_service=+ep' /usr/bin/python2.7
Mar 01 16:18:17.254 [smart_router][WARNING] Or run XX-Net as root
Mar 01 16:18:17.254 [smart_router][INFO] dns_server stop
Mar 01 16:18:17.344 [launcher][INFO] module smart_router started
Mar 01 16:18:17.344 [launcher][INFO] start smart_router time cost:114 ms
Mar 01 16:18:17.345 [launcher][INFO] allow remote access WebUI
Mar 01 16:18:17.345 [launcher][INFO] begin to start web control
Mar 01 16:18:17.345 [launcher][INFO] server 0.0.0.0:8085 started.
Mar 01 16:18:17.346 [launcher][INFO] launcher web control started.

**Comment by xxnet** [comment]
​看了代码，是log错了，8086端口实际监听的ip应该 0.0.0.0
你可以用命令行查看

sudo netstat -napt |grep 8086 |grep LIST

**Comment by nickonline2005** [comment]
log显示监听在127.0.0.1上时，smart router不可用，改config.json后就正常了。
