### ISSUE TITLE
gae无法连接

### ISSUE THREAD

**Issue by abedr** [XX-net/XX-Net#9831]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:9 ipv6:1909
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 351
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

* 请贴出相关的日志
Feb 24 12:53:17.149 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:20.186 - [DEBUG] sort ip time:34ms

Feb 24 12:53:25.254 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:53:25.254 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:29.368 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:53:29.368 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:30.114 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Feb 24 12:53:30.114 - [WARNING] gae_exception:'600:fetch gae fail' https://www.googleapis.com/chromewebstore/v1.1/items/verify

Feb 24 12:53:30.114 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.googleapis.com/chromewebstore/v1.1/items/verify"

Feb 24 12:53:30.114 - [WARNING] GAE POST https://www.googleapis.com/chromewebstore/v1.1/items/verify request fail:"600:gae_exception:'600:fetch gae fail' https://www.googleapis.com/chromewebstore/v1.1/items/verify"

Feb 24 12:53:30.315 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Feb 24 12:53:30.315 - [WARNING] gae_exception:'600:fetch gae fail' https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1

Feb 24 12:53:30.315 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1"

Feb 24 12:53:30.315 - [WARNING] GAE GET https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1 request fail:"600:gae_exception:'600:fetch gae fail' https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1"

Feb 24 12:53:32.201 - [DEBUG] GAE GET https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1

Feb 24 12:53:32.501 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:53:32.501 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:33.202 - [DEBUG] connect 2607:f8b0:400a:f::13 fail:error(10051, '')

Feb 24 12:53:35.503 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:39.417 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:53:39.417 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:39.606 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:53:42.418 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:45.460 - [DEBUG] sort ip time:31ms

Feb 24 12:53:45.576 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:53:45.576 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:45.678 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:53:48.581 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:51.710 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:53:51.710 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:51.806 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:53:54.726 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:57.875 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:53:57.875 - [DEBUG] report_connect_fail network fail

Feb 24 12:53:57.969 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:53:59.846 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Feb 24 12:53:59.846 - [WARNING] gae_exception:'600:fetch gae fail' https://www.google.com/searchdomaincheck?format=domain&type=chrome

Feb 24 12:53:59.846 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.google.com/searchdomaincheck?format=domain&type=chrome"

Feb 24 12:53:59.846 - [WARNING] GAE GET https://www.google.com/searchdomaincheck?format=domain&type=chrome request fail:"600:gae_exception:'600:fetch gae fail' https://www.google.com/searchdomaincheck?format=domain&type=chrome"

Feb 24 12:53:59.892 - [DEBUG] GAE GET https://www.google.com/searchdomaincheck?format=domain&type=chrome

Feb 24 12:54:00.886 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:03.996 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:54:03.996 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:04.106 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:54:07.000 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:10.046 - [DEBUG] sort ip time:30ms

Feb 24 12:54:10.203 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:54:10.203 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:10.312 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:54:13.218 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:13.906 - [DEBUG] create ssl timeout fail.

Feb 24 12:54:14.542 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Feb 24 12:54:14.542 - [WARNING] gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect

Feb 24 12:54:14.542 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Feb 24 12:54:14.542 - [WARNING] GAE POST https://www.google-analytics.com/collect request fail:"600:gae_exception:'600:fetch gae fail' https://www.google-analytics.com/collect"

Feb 24 12:54:14.757 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Feb 24 12:54:14.757 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Feb 24 12:54:14.757 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Feb 24 12:54:14.757 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Feb 24 12:54:15.601 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Feb 24 12:54:16.351 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:54:16.351 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:16.460 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:54:16.570 - [DEBUG] connect 2607:f8b0:400a:f::13 fail:error(10051, '')

Feb 24 12:54:16.679 - [DEBUG] connect 2607:f8b0:400a:2::6 fail:error(10051, '')

Feb 24 12:54:17.570 - [DEBUG] connect 2607:f8b0:4012:a::16 fail:error(10051, '')

Feb 24 12:54:17.773 - [DEBUG] connect 2607:f8b0:401a:23::8 fail:error(10051, '')

Feb 24 12:54:17.929 - [DEBUG] connect 2607:f8b0:400a:f::b fail:error(10051, '')

Feb 24 12:54:19.353 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:22.354 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:25.355 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:28.357 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:28.458 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:54:28.712 - [DEBUG] connect 2607:f8b0:400a:1::12 fail:error(10051, '')

Feb 24 12:54:31.369 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:32.282 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Feb 24 12:54:32.282 - [WARNING] gae_exception:'600:fetch gae fail' https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1

Feb 24 12:54:32.282 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1"

Feb 24 12:54:32.282 - [WARNING] GAE GET https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1 request fail:"600:gae_exception:'600:fetch gae fail' https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1"

Feb 24 12:54:34.369 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:36.093 - [DEBUG] GAE GET https://clients2.google.com/service/update2/crx?os=win&arch=x64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=64.0.3282.140&lang=zh-CN&acceptformat=crx2,crx3&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpkedcjkdefgpdelpbcmbmeomcjbeemfm%26v%3D0.0.0.0%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dpadekgcemlokbadohgkifijomclgjgif%26v%3D2.4.6%26uc%26ping%3Dr%253D-1%2526e%253D1

Feb 24 12:54:37.419 - [DEBUG] sort ip time:44ms

Feb 24 12:54:37.419 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:40.421 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:43.561 - [DEBUG] connect 2607:f8b0:400a:6::14 fail:error(10051, '')

Feb 24 12:54:43.561 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:45.509 - [DEBUG] connect 2607:f8b0:4016:d::17 fail:error(10051, '')

Feb 24 12:54:45.941 - [DEBUG] connect 2607:f8b0:4016:12::12 fail:error(10051, '')

Feb 24 12:54:46.154 - [DEBUG] connect 2607:f8b0:401a::c fail:error(10051, '')

Feb 24 12:54:46.265 - [DEBUG] connect 2607:f8b0:4012:a::16 fail:error(10051, '')

Feb 24 12:54:46.486 - [DEBUG] connect 2607:f8b0:401a:23::8 fail:error(10051, '')

Feb 24 12:54:46.561 - [DEBUG] report_connect_fail network fail

Feb 24 12:54:47.673 - [DEBUG] connect 2607:f8b0:400a:f::b fail:error(10051, '')

Feb 24 12:54:48.390 - [DEBUG] connect 2607:f8b0:400a:2::6 fail:error(10051, '')

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
试试：无线网络属性内取消勾选 IPv6 协议
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）

**Comment by abedr** [comment]
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : win10.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : unspecified

**Comment by abedr** [comment]
C:\windows\system32>ping -6 ipv6.test-ipv6.com
Ping 请求找不到主机 ipv6.test-ipv6.com。请检查该名称，然后重试。
已试无线网络属性内取消勾选 IPv6 协议

**Comment by abedr** [comment]
按照https://support.xbox.com/zh-CN/xbox-on-windows/social/troubleshoot-party-chat中的
解决方案 2：卸载 Teredo 适配器

右键单击“开始”图标，然后选择“命令提示（管理）”。
要禁用 Teredo，在管理命令提示符下运行以下命令：
netsh interface Teredo set state disable

右键单击“开始”图标，然后选择“设备管理器”。
选择“查看”，然后选择“显示隐藏的设备”。
选择“网络适配器”。
找出所有含有“Teredo”的适配器，如 Teredo 隧道伪接口 或 Microsoft Teredo 隧道适配器。 右键单击适配器名称，然后选择“卸载”。
重新启动您的电脑。
要重新启用 Teredo：

右键单击“开始”图标，然后选择“命令提示（管理）”。
在管理命令提示符下运行以下命令：
netsh interface Teredo set state type=default

注意 Microsoft Teredo 隧道适配器 会自动重新安装。 请不要在设备管理器中手动安装 Teredo 隧道伪接口 适配器，这可能使 Teredo 功能出现问题。
就变成Teredo 参数
类型 : disabled

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验：

**Comment by abedr** [comment]
1、试试：无线网络属性内取消勾选 IPv6 协议--已经勾选

2、弃用 ISP 商 DNS ，指定 IPv4 及 IPv6 DNS ？ http://www.freenom.world——无法打开视频（没看懂这是干什么的，改完DNS也没法打开视频，只好又改会来了）

3、保证注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000（这个看不懂如何操作，尚未尝试）

4、Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
（没有这一个选项）


5、出问题：多次刷新或重载控制页，或（结束进程pythonw.exe、）禁用再启用网络并稍侯。。。（尝试多次无果）

6、#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
（ win10/64: win10.ipv6.microsoft.com.感觉与运行的Teredo 参数
类型 : disabled
服务器名称 : win10.ipv6.microsoft.com.
客户端刷新间隔 : 30 秒
客户端端口 : unspecified没有错误，或者我理解错误？）
7、使用ping超时的微软服务器或许更稳定！(win7除外？)莫非类型 natawareclient 比 enterpriseclient 强劲？试试：管理权限运行
netsh int ipv6 set teredo natawareclient default default 3544
8、（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop
（运行结果如下C:\windows\system32>:loop
C:\windows\system32>netsh int teredo show state
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : 3544


C:\windows\system32>ping 127.0.0.1 > null

C:\windows\system32>goto loop
好像，也不行）
求大佬解答，谢谢大佬

**Comment by gjbg1989** [comment]
稍微推敲下“Ipv6 自动转换 | ??闪闪的红星??”网文，补课注册表、批处理bat（内容）后再继续😂

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/36638640-93e21234-1a35-11e8-9fe8-c708f8a29c56.png)

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/36638644-cff0629e-1a35-11e8-8dff-44d982c92399.png)

**Comment by abedr** [comment]
XX-Net 3.10.4，一切正常，你可以访问真正的互联网！
哈哈，成功了，虽然不知道是怎么成功的。。。
1.tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
的确放到根目录了D:\Program Files\XX-Net-3.3.1\.github\tertdo.bat，但是提示系统打不开
（这一部分其实是有点蒙的 ）
2.补课编辑注册表，改正 成功
3.看了💖闪闪的红星💖的文章，很有帮助
4.改了IP Help的状态
差不多了
谢谢大佬

**Comment by gjbg1989** [comment]
但是提示系统打不开——不是找不到路径？将 tertdo.bat 内的 \default\python27\1.0\python.exe 用你 XX-Net 目录 XX-Net-3.3.1.github 替换掉 default 即可

**Comment by gjbg1989** [comment]
![rongjian1957-968037509623173120-20180226_161822-img1](https://user-images.githubusercontent.com/13290970/36664742-9639d8aa-1b20-11e8-8127-1b196d91597c.jpg)
![rongjian1957-968037509623173120-20180226_161822-img2](https://user-images.githubusercontent.com/13290970/36664747-9d2416b2-1b20-11e8-922d-2fcbde815be9.jpg)
