### ISSUE TITLE
大家好，图片中打圏的地方，哪个能帮我详细说明一下不，可以在配置文件文件中修改吗？

### ISSUE THREAD

**Issue by skybai1987** [XX-net/XX-Net#986]
![ip](https://cloud.githubusercontent.com/assets/5781464/9824641/c8add1c2-5900-11e5-80dd-4e8081f48dd6.png)
这里的日志说明了什么呢？
![default](https://cloud.githubusercontent.com/assets/5781464/9824642/c8dc00c4-5900-11e5-8441-a3e84330e131.png)
这里默认10，能修改吗？
![default](https://cloud.githubusercontent.com/assets/5781464/9824643/c8f6ef6a-5900-11e5-94aa-be7f48389732.png)

**Comment by skybai1987** [comment]
秀张图，看看速度！但是显示的连接速度也很慢啊。win10隔一段时间，就会爆音2.0.5的版python2.7.9
![Uploading 1080P.png…]()

**Comment by simonasd** [comment]
* 图1:应该是导出你目前可用的IP列表，跟good_ip.txt内容估计是一致的。点导出ip，点执行，你的IP列表会出现在那个大文本框中，供你复制粘贴
* 图2 你一定是想问那些蓝色的字是啥意思吧？这是你在看YouTube视频的时候的一些网络活动。
* 图3 第一个圈：你可以看[“Google IP使用频率限制”选项](About ip connect interval)里面的说明。第二个圈表示你现在可用的IP数量，第三个圈表示你的IP的质量，数字越小越好。第四个圈表示你现在已经建立的连接数，只要不是“0, 0”，就说明可以翻。

**Comment by skybai1987** [comment]
感谢
