### ISSUE TITLE
系统配置gae模块不见了

### ISSUE THREAD

**Issue by 75XiaoXuan12** [XX-net/XX-Net#9863]
如图，之前把gae模块关了。一旦时间后想打开，发现module management里gae模块开关选项消失了。求助下怎么搞，多谢多谢。

![image](https://user-images.githubusercontent.com/30333158/36720333-b17a038e-1be2-11e8-9c82-e1b889e66295.png)

**Comment by gjbg1989** [comment]
config.yaml 
gae_proxy: {auto_start: 1, show_detail: 1}

**Comment by xx-Chen** [comment]
升级3.10.4及以上

**Comment by 75XiaoXuan12** [comment]
@xx-Chen 现在用的版本就是3.10.4，而且我理解这个配置和版本没有关系。
参照 @gjbg1989 提供的方法搞定了，多谢哈。

**Comment by xx-Chen** [comment]
@75XiaoXuan12 sorry,记错了，https://github.com/XX-net/XX-Net/issues/9812#issuecomment-367670673 https://github.com/XX-net/XX-Net/commit/a27d50d6b719fcb9de3c3fac9d4f7724bcca62e9#diff-ecec8d57557aaab08a614ce68d106b49R57 是在3.10.4后修改的，还没发布。😂
