### ISSUE TITLE
请问怎么排查ssr服务器连接慢，或者ping丢包问题。

### ISSUE THREAD

**Issue by yuyistar** [XX-net/XX-Net#9866]
有时候服务器异常的慢，要怎么排查错误，？
有时候我发现会链接不上，但是也没有被封ip，可能ping一次只有1/4的包收到，或者ping值比正常情况下高，比如正常100，但是不正常时候1000多。或者丢包。

想知道原因，或者如何能排查问题

**Comment by xx-Chen** [comment]
S?S?R???

**Comment by yuyistar** [comment]
@xx-Chen 对ssr，就是我的服务商提供给我的虚拟主机有时候很慢。。。不知道怎么能排查问题
