### ISSUE TITLE
一直是“连接尚未建立”，求教各位大佬

### ISSUE THREAD

**Issue by xzhe57** [XX-net/XX-Net#9873]
* 如题，所以能找到的方法试了多遍，还是连接尚未建立，原来ipv6很正常，从昨天开始，一直fail.求教了，着急中

诊断如下：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.88 Safari/537.36
xxnet-version: 3.9.6
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:71 ipv6:1668
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 278
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
#9783 win7&10 32位??开机及唤醒几乎秒秒均正常的非组策略??经验

**Comment by xzhe57** [comment]
@gjbg1989 试过了，全不行。也不知道什么原因。能帮我看看诊断是啥问题吗？我小白一个

**Comment by xzhe57** [comment]
主机名  . . . . . . . . . . . . . : idea-PC
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : lan

无线局域网适配器 本地连接* 3:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct 虚拟适配器
   物理地址. . . . . . . . . . . . . : 48-D2-24-AA-1A-CF
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : lan
   描述. . . . . . . . . . . . . . . : Realtek RTL8723AU Wireless LAN 802.11n USB 2.0 Network Adapter
   物理地址. . . . . . . . . . . . . : 48-D2-24-AA-1A-CF
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::9c7e:e0a2:9dd3:f09d%8(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.2.144(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年2月28日 18:32:04
   租约过期的时间  . . . . . . . . . : 2018年3月1日 18:32:04
   默认网关. . . . . . . . . . . . . : 192.168.2.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.2.1
   DHCPv6 IAID . . . . . . . . . . . : 289985060
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-19-B6-00-B1-48-D2-24-AA-1A-CF
   DNS 服务器  . . . . . . . . . . . : 192.168.2.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 Bluetooth 网络连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Bluetooth 设备(个人区域网)
   物理地址. . . . . . . . . . . . . : 48-D2-24-AA-41-DB
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
PS C:\WINDOWS\system32>

**Comment by gjbg1989** [comment]
试过了，全不行——😱全试过了，不行——系统有 IP 转换配置服务？😂

**Comment by xzhe57** [comment]
ip转换已配置，自动。不过每次启动电脑以后，又变成手动。即便是启动自动转换，xx-net 依旧不行

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果

**Comment by xzhe57** [comment]
Teredo 参数
---------------------------------------------
类型                    : disabled
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 无

**Comment by xzhe57** [comment]
@gjbg1989 始终不清楚“连接尚未建立”的原因是啥，难道是因为ipv6   fail的原因？

**Comment by gjbg1989** [comment]
😱全试过了——结束进程 pythonw.exe，管理权限运行
netsh int ipv6 set teredo natawareclient default default 3544
多次刷新或重载控制页。。。

**Comment by xzhe57** [comment]
@gjbg1989 
类型                    : disabled
服务器名称              : win1710.ipv6.microsoft.com.
客户端刷新间隔          : 30 秒
客户端端口                : 3544
状态                    : offline
错误                    : 无

**Comment by gjbg1989** [comment]
（结束进程pythonw.exe、）禁用再启用网络。。。

**Comment by gjbg1989** [comment]
证明你——保证了注册表项：
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters]
"DisabledComponents"=dword:00000000

**Comment by xzhe57** [comment]
@gjbg1989 这两个键值确信和你的一样。不会截图，没法传上来。需要重启电脑吗？

**Comment by gjbg1989** [comment]
试试：无线网络属性内取消勾选 IPv6 协议

**Comment by xzhe57** [comment]
@gjbg1989 已取消勾选，依旧不行

**Comment by gjbg1989** [comment]
既然 IP 转换配置服务不正常
![default](https://user-images.githubusercontent.com/13290970/36791007-9dc4f16a-1cd1-11e8-9213-5b4fff1b8607.png)
如能内网固定 IP 最好

**Comment by gjbg1989** [comment]
貌似有人说手动重启 IP Helper 服务后正常

**Comment by xzhe57** [comment]
@gjbg1989 再试试吧。谢谢你了。今天不搞了。以后再求教了

**Comment by happygoodday** [comment]
本人現在不斷在這個平臺學習，感謝大家；
現在看到這個問題，就說下自己的經驗，如果你是使用路由器上網的，請在路由器終端把上網的電腦鎖定為固定IP，同時連同 電腦 的MACA地址一起綁定，然後在電腦端同樣設定一樣的固定IP。電腦如果重啓，電腦的IP可能和原先在路由器終端設定的固定IP不一樣，這樣你需要把電腦端的IP 設定為原先的固定IP。

**Comment by gjbg1989** [comment]
在路由器終端上将電腦的MAC地址綁定——即電腦鎖定為固定IP，把電腦端的IP 設定為自动获取即🆗

**Comment by lon91ong** [comment]
试试这个：https://pan.baidu.com/s/1qZjjbBm
一次执行里面的文件，重启试试

**Comment by Guowei1992** [comment]
我之前也遇到同样的问题，
1: 我先退出xx-net；
2: 执行\XX-Net-3.3.1\code\3.9.6\gae_proxy\local\ipv6_tunnel 文件夹下的 "disable_ipv6 tunnel"批处理文件；(这个路径中可能有些版本号不同，不过这些批处理文件都能找得到)。
3: 之后再点击 "enable_ipv6 tunnel" 批处理文件，再次打开xx-net就好了。

**Comment by sowpl** [comment]
多谢楼上，按照你说的方法解决了
