### ISSUE TITLE
ipv6显示失败 各位大神 求救

### ISSUE THREAD

**Issue by kevin111999** [XX-net/XX-Net#9875]
属性 | 值
-- | --
IPv4 Status | OK
IPv6 Status | Fail
IPv4 Number | 4
IPv6 Number | 1937
空闲 | 0
IP延迟 | 248
连接池(帮助) | 新:0 h1:0 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
扫描IP线程数(设置) | 10
屏蔽状态(帮助) | OK

谢谢谢谢

**Comment by kevin111999** [comment]
Mar 01 10:41:17.041 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:21.046 - [DEBUG] connect 2607:f8b0:400a:4::18 fail:timeout('timed out',)

Mar 01 10:41:21.046 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:25.047 - [DEBUG] connect 2607:f8b0:400a::11 fail:timeout('timed out',)

Mar 01 10:41:25.047 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:25.097 - [DEBUG] sort ip time:49ms

Mar 01 10:41:29.105 - [DEBUG] connect 2607:f8b0:400a:4::18 fail:timeout('timed out',)

Mar 01 10:41:29.105 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:33.106 - [DEBUG] connect 2607:f8b0:400a::11 fail:timeout('timed out',)

Mar 01 10:41:33.106 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:37.111 - [DEBUG] connect 2607:f8b0:400a:4::18 fail:timeout('timed out',)

Mar 01 10:41:37.111 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:37.166 - [DEBUG] sort ip time:54ms

Mar 01 10:41:41.166 - [DEBUG] connect 2607:f8b0:400a::11 fail:timeout('timed out',)

Mar 01 10:41:41.166 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:43.525 - [DEBUG] CONNECT POST https://www.twitter.com/xxnet

Mar 01 10:41:43.535 - [DEBUG] POST http://www.twitter.com/xxnet

Mar 01 10:41:43.618 - [DEBUG] POST http://www.twitter.com/xxnet

Mar 01 10:41:43.622 - [DEBUG] CONNECT POST https://www.twitter.com/xxnet

Mar 01 10:41:45.172 - [DEBUG] connect 2607:f8b0:400a:4::18 fail:timeout('timed out',)

Mar 01 10:41:45.172 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:48.509 - [DEBUG] GAEProxy Web_control 127.0.0.1:61753 GET /deploy?cmd=get_log

Mar 01 10:41:49.172 - [DEBUG] connect 2607:f8b0:400a::11 fail:timeout('timed out',)

Mar 01 10:41:49.172 - [DEBUG] report_connect_fail network fail

Mar 01 10:41:49.340 - [DEBUG] sort ip time:167ms

Mar 01 10:41:49.583 - [DEBUG] GAEProxy web_control 127.0.0.1:61754 POST /config?cmd=get_config

Mar 01 10:41:49.591 - [DEBUG] GAEProxy Web_control 127.0.0.1:61754 GET /scan_ip?cmd=get_range

Mar 01 10:41:49.592 - [INFO] load ip range file:C:\proxy\XX-Net-3.7.4\code\3.8.5\gae_proxy\local\ip_range.txt

Mar 01 10:41:49.932 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Mar 01 10:41:53.343 - [DEBUG] connect 2607:f8b0:400a:4::18 fail:timeout('timed out',)

Mar 01 10:41:53.343 - [DEBUG] report_connect_fail network fail

**Comment by gjbg1989** [comment]
#9783 win7&10 32位??开机及唤醒几乎秒秒均正常的非组策略??经验

**Comment by kevin111999** [comment]
@gjbg1989 请问是什么意思？

**Comment by gjbg1989** [comment]
😱什么意思？高抬贵鼠标到 #9783

**Comment by kevin111999** [comment]
@gjbg1989 哦哦，明白了，谢谢谢谢 请见谅。

**Comment by aoyoo111** [comment]
重启一次就好了

**Comment by kevin111999** [comment]
多谢各位大神相助， 今天突然好了。重启了下确实有效。
