### ISSUE TITLE
问题：等待ipv6.google.com响应

### ISSUE THREAD

**Issue by pepsicolor** [XX-net/XX-Net#9876]
![1](https://user-images.githubusercontent.com/22813066/36824753-fa786a3c-1d3e-11e8-92f6-f1318b328c1d.png)
![2](https://user-images.githubusercontent.com/22813066/36824761-03acde3a-1d3f-11e8-93e4-10eff344f223.png)
![3](https://user-images.githubusercontent.com/22813066/36824771-15548ef8-1d3f-11e8-93d6-9a480671bb5a.png)
google可以正常打开，搜索的时候就会卡在如图1左下角提示的“等待ipv6.google.com响应”，然后就显示结果如图2。请教如何解决。

**Comment by pepsicolor** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:3000 ipv4:0 ipv6:2030
ipv4-status: OK
ipv6-status: OK
connected-link: new:8 used:0
worker: h1:14 h2:1
scan-ip-thread-num: 50
ip-quality: 407
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by pepsicolor** [comment]
google图片搜索的时候也会这样，最近发生的几率很高。

**Comment by gjbg1989** [comment]
代理使用情况？

**Comment by pepsicolor** [comment]
xxnet（取消全局）+chrome（switchyomega的GAE自动切换）。
youtube还是可以看的，就是google搜索这里出问题。

**Comment by pepsicolor** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy)
服务器名称              : win10.ipv6.microsoft.com
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : managed
NAT                     : restricted (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 是
本地映射           : 192.168.1.200:65493

**Comment by gjbg1989** [comment]
试试：
1、结束进程 pythonw.exe
2、config.ini 添加
[system]
fake_host = deja.com
3、manual.ini 添加
[hosts]
*.deja.com = gae

**Comment by gjbg1989** [comment]
系统默认服务器名称 :不是 win10.ipv6.microsoft.com 而是 win10.ipv6.microsoft.com.
先前修改的 ipv6 组策略退回到默认值的全部“未配置”，管理权限运行
netsh int ipv6 set teredo natawareclient default default 3544

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验

**Comment by pepsicolor** [comment]
谢谢，正在按步进行。

**Comment by pepsicolor** [comment]
问题依旧。 @gjbg1989 
https://ipv6.google.com/sorry/index?continue=https://www.google.com.hk/search%3Fq%3D%25E4%25BB%258A%25E5%25A4%25A9%26rlz%3D1C1CHWL_zh-CNCN777CN777%26oq%3D%25E4%25BB%258A%25E5%25A4%25A9%26aqs%3Dchrome..69i57j69i61l2j0l3.2569j0j7%26sourceid%3Dchrome%26ie%3DUTF-8&q=EhAgAQAAnTiVPACO8iePmcIUGKy83tQFIhkA8aeDSx8qlRrKKFKEa_T3PWQGK5gEwllIMgFy

**Comment by c6132a1** [comment]
ipv6封了很多
