### ISSUE TITLE
XX-NET使用“全局PAC智能代理”不能科学上网，网上查了很久都不能解决

### ISSUE THREAD

**Issue by obeey** [XX-net/XX-Net#9881]
* 是否试过最新的测试版本？
  已经升级到了最新版本3.10.4。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
没有公告
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
查看了，没有发现类似问题
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：
使用“全局通过GAEProxy代理”没有问题。
使用“全局PAC智能代理”时非墙网站能够访问，墙掉的网站就不能访问

* 做过哪些尝试：
reset chrome没有效果
将data/gae_proxy/manual.ini重命名，没有效果

用netstat查看，发现8086端口根本没有监听，难道是软件bug？
$ netstat -anp TCP  | grep LISTENING
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:554            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1025           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1026           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1027           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1028           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1170           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:2869           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:3389           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5091           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:10243          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:50115          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:4012         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:4013         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:4300         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:4301         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:8085         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:8087         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:10101        0.0.0.0:0              LISTENING
  TCP    192.168.8.184:139      0.0.0.0:0              LISTENING
  TCP    192.168.56.1:139       0.0.0.0:0              LISTENING

$ netstat -anp TCP  | grep LISTENING | grep 8086

* 请贴出对应模块的状态页

* 请贴出相关的日志
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:4673 ipv4:21 ipv6:2571
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:76 h2:0
scan-ip-thread-num: 5
ip-quality: 255
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
参考：https://github.com/XX-net/XX-Net/issues/9859

**Comment by gjbg1989** [comment]
XX-Net ：全局 PAC 智能代理，浏览器代理插件：系统代理或禁用该插件
![image](https://user-images.githubusercontent.com/13290970/36835448-383cc4e4-1d71-11e8-8294-a4a949498a79.png)

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/36835827-69945f92-1d72-11e8-94ce-e1451f3c9b8b.png)

**Comment by gjbg1989** [comment]
😱 必须启用 Smart Router
https://user-images.githubusercontent.com/13290970/36715451-3d77b924-1bd1-11e8-9c32-81a84a1bc08e.png

**Comment by obeey** [comment]
非常感谢！没有启用插件，开启了Smart Router后OK了！
但是我今天半天尝试的时候也开启过Smart Router试过啊，当时是不行的。
我记得我的Smart Router上是有配置的，难道是因为这个原因？
![image](https://user-images.githubusercontent.com/10753768/36848886-8b6c1f8a-1d9d-11e8-92f4-6b2515102810.png)
可能是上面红框中的配置错了，之前我配置的是黑名单-》GAEProxy

**Comment by gjbg1989** [comment]
貌似 PAC 策略任一选项都成

**Comment by qibin8687** [comment]
各位好，我碰到了和楼主同样的问题。根据回帖中的开启smart router提示解决了问题。不过我有一点好奇：既然启用smart router来智能筛选代理路径，干嘛还留着pac智能代理选项呢？是不是历史遗留问题？毕竟以前xxnet版本还没有整合smart router，所以我一直使用pac智能代理（我没使用omegaswitch习惯）。
我翻了一下pac所在的文件夹，位于smart router下。是否有什么运作机理我没明白？

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=launcher&menu=config 模块管理：启用 Smart Router 😜ON
http://127.0.0.1:8085/?module=smart_router&menu=config PAC 策略：黑名单走GAE
