### ISSUE TITLE
win10 xx-net 打开浏览器无法访问

### ISSUE THREAD

**Issue by zoeblow** [XX-net/XX-Net#9882]
一直转圈圈，过了一会就直接显示网未连接了    根本打不开127.0.0.1:8085 页面 买的x-tunnel 根本没法用啊 @xx-Chen  大佬帮忙看看啊！

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验

**Comment by zoeblow** [comment]
电脑的问题，重置电脑 好了，哈哈哈
