### ISSUE TITLE
访问谷歌和脸书显示无法访问

### ISSUE THREAD

**Issue by AnLvNing** [XX-net/XX-Net#9885]
好像升级3.10.4之后出现的问题，打不开谷歌和脸书，链接其他网站速度感觉也降低了 一些错误提示如下：
GAE：

Mar 02 10:57:31.667 - [WARNING] h2 2607:f8b0:401c:10::a http://center.xx-net.net/report_stat:1519959446.662000 timeout, trace:0:start_request,0:get_task,0:get_worker:2607:f8b0:401c:10::a,0:h2_req,1:send headert,0:send body,341:retry,0:get_task,0:get_worker:2607:f8b0:401c:10::b,0:h2_req,0:send headert,0:send body,4661:h2 timeout,:0

Mar 02 10:57:31.667 - [DEBUG] http://center.xx-net.net/report_stat response_fail:h2 timeout

Mar 02 10:57:31.667 - [DEBUG] GAE_Exception 601 'fetch gae fail:601'

Mar 02 10:57:31.667 - [WARNING] gae_exception:'601:fetch gae fail:601' http://center.xx-net.net/report_stat

XTUN：
Mar 02 10:58:34.318 - [WARNING] front retry center.xx-net.net/report_stat

![facebook](https://user-images.githubusercontent.com/33977540/36881577-c8b35afe-1e09-11e8-805f-0afa10ca2679.PNG)
![google](https://user-images.githubusercontent.com/33977540/36881578-c8eac336-1e09-11e8-9771-885b57619c31.PNG)

**Comment by xxnet** [comment]
​是用GAE代理吗？
如果是GAE代理，请贴出GAE的日志

**Comment by NOoNE7** [comment]
用的是smartrouter，当时gae和xtunnel出现的红色日志我都发在上面的正文里了，还需要全部日志吗？要等到明天

**Comment by WorkShop-Office** [comment]
問題の



Sent from my Redmi 4A
On NOoNE7 <notifications@github.com>, Mar 2, 2018 10:51 PM wrote:

用的是smartrouter，当时gae和xtunnel出现的红色日志我都发在上面的正文里了，还需要全部日志吗？要等到明天

**Comment by NOoNE7** [comment]
Mar 03 07:30:17.894 - [DEBUG] 2800:3f0:4001:9::b worker close:idle timeout

Mar 03 07:30:19.239 - [DEBUG] GAE GET https://api.github.com/repos/xx-net/XX-Net/issues?labels=%E5%8F%91%E5%B8%83,3.10.4

Mar 03 07:30:19.502 - [DEBUG] 2404:6800:400e:3::c worker close:idle timeout

Mar 03 07:30:19.787 - [INFO] GAE t:547 s:1254 GET https://api.github.com/repos/xx-net/XX-Net/issues?labels=%E5%8F%91%E5%B8%83,3.10.4 0:start_request,0:get_task,0:get_worker:2607:f8b0:4000:33::a,0:h1_req,536:h1_get_head,0:get_response,11:h1_finish[SP:154085],:0

Mar 03 07:30:20.702 - [DEBUG] 2404:6800:400c:3::a worker close:idle timeout

Mar 03 07:30:20.838 - [DEBUG] 2a00:1450:4003:10::f worker close:idle timeout

Mar 03 07:30:22.300 - [DEBUG] connect 2607:f8b0:4002:14::b fail:timeout('timed out',)

Mar 03 07:30:22.300 - [DEBUG] report_connect_fail:2607:f8b0:4002:14::b

Mar 03 07:30:22.348 - [DEBUG] GAE GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.81qcNVAdPP0.O/m=gapi_iframes,googleapis_client,iframes_styles_slide_menu,plusone/rt=j/sv=1/d=1/ed=1/am=AAE/rs=AHpOoo-rnjHqcvRAlxtG-9gMfTrV90boIA/cb=gapi.loaded_0

Mar 03 07:30:23.105 - [INFO] GAE t:756 s:62148 GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.81qcNVAdPP0.O/m=gapi_iframes,googleapis_client,iframes_styles_slide_menu,plusone/rt=j/sv=1/d=1/ed=1/am=AAE/rs=AHpOoo-rnjHqcvRAlxtG-9gMfTrV90boIA/cb=gapi.loaded_0 0:start_request,0:get_task,0:get_worker:2607:f8b0:4000:33::a,3:h1_req,362:h1_get_head,0:get_response,390:h1_finish[SP:160305],:0

Mar 03 07:30:23.863 - [DEBUG] create_ssl update ip:2607:f8b0:400a:d::e time:388 h2:0

Mar 03 07:30:24.415 - [DEBUG] create_ssl update ip:2607:f8b0:401c:12::7 time:375 h2:0

Mar 03 07:30:26.270 - [DEBUG] GAE GET https://apis.google.com/js/api.js

Mar 03 07:30:26.558 - [INFO] GAE t:288 s:4729 GET https://apis.google.com/js/api.js 0:start_request,0:get_task,0:get_worker:2607:f8b0:400a:d::e,0:h1_req,268:h1_get_head,0:get_response,19:h1_finish[SP:266300],:0

Mar 03 07:30:26.602 - [DEBUG] GAE GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.81qcNVAdPP0.O/m=gapi_iframes_simple/rt=j/sv=1/d=1/ed=1/am=AAE/rs=AHpOoo-rnjHqcvRAlxtG-9gMfTrV90boIA/cb=gapi.loaded_0

Mar 03 07:30:26.971 - [DEBUG] 2404:6800:400c:8::7 worker close:idle timeout

Mar 03 07:30:27.067 - [INFO] GAE t:464 s:25426 GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.81qcNVAdPP0.O/m=gapi_iframes_simple/rt=j/sv=1/d=1/ed=1/am=AAE/rs=AHpOoo-rnjHqcvRAlxtG-9gMfTrV90boIA/cb=gapi.loaded_0 0:start_request,0:get_task,0:get_worker:2607:f8b0:401c:12::7,0:h1_req,250:h1_get_head,0:get_response,214:h1_finish[SP:119972],:0

Mar 03 07:30:32.484 - [DEBUG] create_ssl update ip:2607:f8b0:4002:13::b time:2747 h2:0

Mar 03 07:30:33.044 - [DEBUG] create_ssl update ip:2607:f8b0:401d:1f::a time:379 h2:0

Mar 03 07:30:33.271 - [DEBUG] GAE GET https://api.github.com/repos/xx-net/XX-Net/issues?labels=%E5%8F%91%E5%B8%83,3.10.4

Mar 03 07:30:33.447 - [DEBUG] 2607:f8b0:400a:2::6 worker close:idle timeout

Mar 03 07:30:33.563 - [DEBUG] 2404:6800:400b:3::9 worker close:idle timeout

Mar 03 07:30:33.718 - [INFO] GAE t:447 s:0 GET https://api.github.com/repos/xx-net/XX-Net/issues?labels=%E5%8F%91%E5%B8%83,3.10.4 0:start_request,0:get_task,0:get_worker:2607:f8b0:401c:12::7,0:h1_req,447:h1_get_head,0:get_response,:0

Mar 03 07:30:34.254 - [DEBUG] restore ip:2607:f8b0:4002:14::b

Mar 03 07:30:34.725 - [DEBUG] 2607:f8b0:4004:28::9 worker close:idle timeout

Mar 03 07:30:35.732 - [DEBUG] 2404:6800:400c:5::8 worker close:idle timeout

Mar 03 07:30:35.910 - [DEBUG] 2607:f8b0:400a:3::15 worker close:idle timeout

Mar 03 07:30:36.934 - [DEBUG] 2a00:1450:4002:10::a worker close:idle timeout

Mar 03 07:30:39.170 - [DEBUG] 2a00:1e48:99:16::d worker close:idle timeout @xxnet

**Comment by NOoNE7** [comment]
Mar 03 07:27:31.306 - [DEBUG] start report_stat

Mar 03 07:27:31.450 - [DEBUG] roundtrip time:15299 cost:15016 transfer_no:250 send:0 rcv:21

Mar 03 07:27:31.606 - [INFO] api:/report_stat success t:299

Mar 03 07:27:31.845 - [DEBUG] roundtrip time:15381 cost:15095 transfer_no:251 send:0 rcv:21

Mar 03 07:27:32.145 - [DEBUG] roundtrip time:15372 cost:15097 transfer_no:252 send:0 rcv:21

Mar 03 07:27:32.446 - [DEBUG] roundtrip time:15358 cost:15072 transfer_no:253 send:0 rcv:21

Mar 03 07:27:32.746 - [DEBUG] roundtrip time:15350 cost:15024 transfer_no:254 send:0 rcv:21

Mar 03 07:27:33.050 - [DEBUG] roundtrip time:15334 cost:15057 transfer_no:255 send:0 rcv:21

Mar 03 07:27:33.448 - [DEBUG] roundtrip time:15421 cost:15086 transfer_no:256 send:0 rcv:21

Mar 03 07:27:33.756 - [DEBUG] roundtrip time:15406 cost:15074 transfer_no:257 send:32 rcv:21

Mar 03 07:27:34.359 - [DEBUG] roundtrip time:15384 cost:15048 transfer_no:259 send:0 rcv:21

Mar 03 07:28:31.610 - [DEBUG] start report_stat

Mar 03 07:28:31.829 - [WARNING] front retry center.xx-net.net/report_stat

Mar 03 07:28:33.145 - [INFO] api:/report_stat success t:1535

Mar 03 07:29:33.149 - [DEBUG] start report_stat

Mar 03 07:29:33.394 - [WARNING] front retry center.xx-net.net/report_stat

Mar 03 07:29:34.677 - [INFO] api:/report_stat success t:1528

Mar 03 07:30:16.472 - [WARNING] front retry dns.xx-net.net/query?domain=clients5.google.com

Mar 03 07:30:21.286 - [WARNING] front retry dns.xx-net.net/query?domain=apis.google.com

Mar 03 07:30:34.679 - [DEBUG] start report_stat

Mar 03 07:30:34.956 - [INFO] api:/report_stat success t:277

Mar 03 07:31:34.960 - [DEBUG] start report_stat

Mar 03 07:31:35.229 - [INFO] api:/report_stat success t:269

**Comment by NOoNE7** [comment]
Mar 03 07:35:27.030 - [DEBUG] task trace:7:start_request,49:get_task,0:get_worker:2a00:1450:400a:5::b,0:h1_req,23818:h1_get_head,0:get_response,:0

Mar 03 07:35:27.278 - [DEBUG] roundtrip time:256 cost:0 transfer_no:69 send:0 rcv:21

Mar 03 07:35:28.212 - [WARNING] front retry v12.xx-net.net/data?tid=2

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=26

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=18

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=23

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=21

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=24

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=27

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=31

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=30

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=33

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=35

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=37

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=32

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=40

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=34

Mar 03 07:35:28.216 - [WARNING] front retry v12.xx-net.net/data?tid=43

Mar 03 07:35:28.220 - [WARNING] front retry v12.xx-net.net/data?tid=42

Mar 03 07:35:28.220 - [WARNING] front retry v12.xx-net.net/data?tid=44

Mar 03 07:35:28.220 - [WARNING] front retry v12.xx-net.net/data?tid=39

Mar 03 07:35:28.220 - [WARNING] front retry v12.xx-net.net/data?tid=45

Mar 03 07:35:28.220 - [WARNING] front retry v12.xx-net.net/data?tid=41

Mar 03 07:35:28.220 - [WARNING] front retry v12.xx-net.net/data?tid=49

Mar 03 07:35:29.216 - [WARNING] roundtrip time:26127 transfer_no:2 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:35 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:30 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:24 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:31 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:23 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:33 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:21 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:27 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:26 send:0 status:602

Mar 03 07:35:29.220 - [WARNING] roundtrip time:26125 transfer_no:18 send:0 status:602

Mar 03 07:35:29.224 - [WARNING] roundtrip time:26129 transfer_no:41 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:49 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:45 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:39 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:44 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:42 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:34 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:32 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:43 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:40 send:0 status:602

Mar 03 07:35:29.225 - [WARNING] roundtrip time:26130 transfer_no:37 send:0 status:602

Mar 03 07:35:35.250 - [DEBUG] Conn session:vizodghf conn:3 stop:recv fail.

Mar 03 07:35:35.250 - [DEBUG] remove conn_id:3

Mar 03 07:35:35.494 - [WARNING] front retry v12.xx-net.net/data?tid=70

Mar 03 07:35:36.320 - [DEBUG] start report_stat

Mar 03 07:35:37.628 - [INFO] api:/report_stat success t:1308

**Comment by NOoNE7** [comment]
Mar 03 07:28:31.610 - [DEBUG] start report_stat

Mar 03 07:28:31.829 - [WARNING] front retry center.xx-net.net/report_stat

Mar 03 07:28:33.145 - [INFO] api:/report_stat success t:1535

Mar 03 07:29:33.149 - [DEBUG] start report_stat

Mar 03 07:29:33.394 - [WARNING] front retry center.xx-net.net/report_stat

Mar 03 07:29:34.677 - [INFO] api:/report_stat success t:1528

Mar 03 07:30:16.472 - [WARNING] front retry dns.xx-net.net/query?domain=clients5.google.com

Mar 03 07:30:21.286 - [WARNING] front retry dns.xx-net.net/query?domain=apis.google.com

Mar 03 07:30:34.679 - [DEBUG] start report_stat
