### ISSUE TITLE
3.8.5版本，可以上谷歌，但是谷歌学术无法访问

### ISSUE THREAD

**Issue by funnyphd** [XX-net/XX-Net#9888]
有没有人与我碰到同样的问题啊。使用ipv6可以正常访问谷歌，但是无法访问谷歌学术。
访问谷歌学术的提示如下：
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

IP 地址：x.x.x.x
时间：2018-03-02T12:13:35Z
网址：https://scholar.google.com/schhp?hl=zh-CN

**Comment by Icarus079** [comment]
一样的  不知道为什么

**Comment by gjbg1989** [comment]
8087不行，还有1080

**Comment by xx-Chen** [comment]
谷歌学术不要用GAE用X-Tunnel

**Comment by gjbg1989** [comment]
转：速度！教育邮箱注册不限容量的谷歌网盘 https://mp.weixin.qq.com/s/jaNXluwbSl_IZeBc9hqvMA … 已薅成功

**Comment by liushuiguadanbo** [comment]
大佬 这个公众号被封了  相应的连接也找不到了=。=

**Comment by gjbg1989** [comment]
RT @oiax: https://sci-bay.org  这个好，Google 学术搜索的镜像，免翻墙，速度快。
