### ISSUE TITLE
X装入路由器 PAC模式失效

### ISSUE THREAD

**Issue by sky123456789sky** [XX-net/XX-Net#9896]
X装入路由器 手机用PAC模式翻墙 以前版本PAC模式可用 3.10.4不可用 求助

**Comment by gjbg1989** [comment]
? http://127.0.0.1:8085/?module=launcher&menu=config 必须启用 Smart Router

**Comment by sky123456789sky** [comment]
@gjbg1989  不行 不起作用

**Comment by gjbg1989** [comment]
firefox一直显示“请检查浏览器代理设置”？ #9859

**Comment by sky123456789sky** [comment]
@gjbg1989 不是 只是单纯的PAC不可用 我试试把老版本扔进去试试

**Comment by LoveFForever** [comment]
怎么搞入路由器啊/。。。。。。

**Comment by sky123456789sky** [comment]
@LoveFForever 这里就有教程 你搜搜试试 不难

**Comment by sky123456789sky** [comment]
@LoveFForever 最好是装入openwrt软路由 极其方便

**Comment by nickonline2005** [comment]
我的xxnet 3.10.4也跑在路由（梅林固件）上，smart router虽说绑定53端口失败，但是可以用，只要ipv6正常，就可以使用。注意你要在config.json里改一下8086端口的监听地址为0.0.0.0.
