### ISSUE TITLE
怎么卸载

### ISSUE THREAD

**Issue by cczyjacky** [XX-net/XX-Net#99]
用了xx，改回之前的GoAgent不能用了。

**Comment by xxnet** [comment]
估计是证书问题，重新导入就好了。

GoAgent如果黄字太多，那是GFW最近动作，GoAgent已经几个月没有更新了。

2015-04-01 21:23 GMT-04:00 cczyjacky <notifications@github.com>:

**Comment by xxnet** [comment]
1.6 开始，证书名称和GoAgent保持不同，不会覆盖原版GoAgent的证书。
