### ISSUE TITLE
状态显示正常，但是无法访问google

### ISSUE THREAD

**Issue by alanOO7** [XX-net/XX-Net#9900]
* 简单描述遇到的问题：
无法浏览google，

* 做过哪些尝试：

切换代理
* 请贴出对应模块的状态页

属性 | 值
-- | --
IPv4 状态 | OK
IPv6 状态 | Fail
IPv4 IP数 | 903
IPv6 IP数 | 240
XX-Net 状态 | 工作
IP延迟 | 280
连接池(帮助) | 新:0 h1:2 h2:0
浏览器代理设置 | OK
CA证书状态(下载) | OK
IP扫描线程数(设置) | 10
屏蔽状态(帮助) | OK

* 请贴出相关的日志
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:903 ipv6:240
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 280
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by alanOO7** [comment]
Mar 05 14:13:43.461 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:13:46.697 - [DEBUG] connect 2607:f8b0:401d:1d::8 fail:timeout('timed out',)

Mar 05 14:13:46.697 - [DEBUG] report_connect_fail network fail

Mar 05 14:13:47.550 - [DEBUG] connect 2607:f8b0:400a:1::6 fail:timeout('timed out',)

Mar 05 14:13:47.787 - [DEBUG] connect 2607:f8b0:4017:29::9 fail:timeout('timed out',)

Mar 05 14:13:49.176 - [DEBUG] connect 2607:f8b0:401c:3::9 fail:timeout('timed out',)

Mar 05 14:13:49.577 - [DEBUG] connect 2607:f8b0:401d:5::14 fail:timeout('timed out',)

Mar 05 14:13:49.698 - [DEBUG] report_connect_fail network fail

Mar 05 14:13:50.481 - [DEBUG] connect 2607:f8b0:401c:18::c fail:timeout('timed out',)

Mar 05 14:13:52.700 - [DEBUG] report_connect_fail network fail

Mar 05 14:13:53.891 - [DEBUG] connect 2607:f8b0:401c:12::8 fail:timeout('timed out',)

Mar 05 14:13:54.802 - [DEBUG] connect 2607:f8b0:401c:9::b fail:timeout('timed out',)

Mar 05 14:13:55.701 - [DEBUG] report_connect_fail network fail

Mar 05 14:13:58.702 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:01.703 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:04.704 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:07.705 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:10.763 - [DEBUG] sort ip time:56ms

Mar 05 14:14:10.811 - [DEBUG] sort ip time:48ms

Mar 05 14:14:12.295 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Mar 05 14:14:12.295 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Mar 05 14:14:12.295 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:12.295 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:12.398 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Mar 05 14:14:12.398 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Mar 05 14:14:12.398 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:12.398 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:14.916 - [DEBUG] connect 2607:f8b0:401c:9::b fail:timeout('timed out',)

Mar 05 14:14:14.916 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:15.015 - [DEBUG] connect 2607:f8b0:401c:12::8 fail:timeout('timed out',)

Mar 05 14:14:15.116 - [DEBUG] connect 2607:f8b0:401c:18::c fail:timeout('timed out',)

Mar 05 14:14:15.809 - [DEBUG] connect 2607:f8b0:401d:1d::8 fail:timeout('timed out',)

Mar 05 14:14:16.766 - [DEBUG] connect 2607:f8b0:400a:1::6 fail:timeout('timed out',)

Mar 05 14:14:17.668 - [DEBUG] connect 2607:f8b0:4017:29::9 fail:timeout('timed out',)

Mar 05 14:14:17.917 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:19.858 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Mar 05 14:14:19.858 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Mar 05 14:14:19.858 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:19.858 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:20.918 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:22.767 - [DEBUG] connect 2607:f8b0:401c:3::9 fail:timeout('timed out',)

Mar 05 14:14:23.222 - [DEBUG] connect 2607:f8b0:401d:5::14 fail:timeout('timed out',)

Mar 05 14:14:23.919 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:25.748 - [DEBUG] create ssl timeout fail.

Mar 05 14:14:26.921 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:29.923 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:30.689 - [DEBUG] GAE_Exception 600 'fetch gae fail'

Mar 05 14:14:30.689 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Mar 05 14:14:30.690 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:30.690 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:32.923 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:35.924 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:38.973 - [DEBUG] sort ip time:49ms

Mar 05 14:14:39.018 - [DEBUG] sort ip time:44ms

Mar 05 14:14:39.061 - [DEBUG] sort ip time:43ms

Mar 05 14:14:39.122 - [DEBUG] sort ip time:59ms

Mar 05 14:14:39.219 - [DEBUG] sort ip time:97ms

Mar 05 14:14:43.327 - [DEBUG] connect 2607:f8b0:401c:9::b fail:timeout('timed out',)

Mar 05 14:14:43.327 - [DEBUG] report_connect_fail network fail

Mar 05 14:14:43.359 - [DEBUG] GAE_Exception 600 'fetch gae fail'
补充日志信息
Mar 05 14:14:43.359 - [WARNING] gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Mar 05 14:14:43.359 - [DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

Mar 05 14:14:43.359 - [WARNING] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome request fail:"600:gae_exception:'600:fetch gae fail' https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome"

**Comment by GoodSake** [comment]
IPv6 状态  Fail

这样不行的哦

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验

**Comment by alanOO7** [comment]
禁用ivp6后正常
