### ISSUE TITLE
[发布] 3.10.7 版发布

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#9920]
## What is new:
* refactor gae_proxy
* update gae ip list
* update gae public appid
* improve smart_router rule
* don't use direct ipv6, gae is more faster.
* fix bug: gae download large file fail.

## 新版改进：
* 重构 GAE_PROXY 代码
* 更新 GAE ip 列表
* 更新 GAE 公共 appid
* 优化智能路由规则
* 不再优先使用ipv6直连
* 修复bug：某些大文件下载失败。

下载地址：
[下载](https://github.com/XX-net/XX-Net/archive/3.10.7.zip)

**Comment by myjlpt** [comment]
最新版本貌似manual.ini这个文件配置被无视了？

怎么回事？

**Comment by gjbg1989** [comment]
无视 config.ini 、manual.ini，新宠 config.json 😂

**Comment by foho8080** [comment]
新版的工作AppID變成公共AppID.個人的AppID怎樣設置

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=config 部署——保存

**Comment by myjlpt** [comment]
@gjbg1989 
config.json 编辑求教

有密码的
[gae]
appid = ooxe
password = xxxx
validate = 1

这个怎么在config.json中表示/编辑

**Comment by gjbg1989** [comment]
😱试试：
![image](https://user-images.githubusercontent.com/13290970/37103698-c8cbb062-2265-11e8-9613-46d029d6b5f7.png)

**Comment by gjbg1989** [comment]
"GAE_PASSWORD": "xxxx"

**Comment by xxnet** [comment]
​看来需要一个配置文件导入功能。

新版的智能路由也有改进，大家测试下效果如何

**Comment by myjlpt** [comment]
@gjbg1989 好吧表示已经试过了，改完之后，神奇的奔溃了。
@xxnet 新版本的smart非常棒，解析情况好了很多，不再有出现部分常见的国内站点解析缓慢。而且GAE速度比起之前快了不少从40K直飙2M。坐标江苏
至于导入功能实在太有必要。表示公共APPID实在不够，请提点修改config.json要点。祝安

**Comment by xxnet** [comment]
​这种属于反广告的部分，可以考虑加入

**Comment by dahai058** [comment]
好的，非常感谢！

**Comment by Balnea** [comment]
Smart Router Config中Rules一栏是否能给一个
Direct List，GAEProxy List，SOCKS List，Redirect HTTPS，Black List
这些格式规范，另外SOCKS List是做什么的？

**Comment by weiwei007** [comment]
3.10.6是不是限制ip总数只有100，扫描线程只有1！我吧3.10.4ip和设置导入3.10.6里面，ip自动被删除嘞扫描线程也没有改变！

**Comment by gjbg1989** [comment]
😂貌似：
扫描线程可在控制页内设置，限制ip总数只有100，想改得编辑 config.json

**Comment by nly4lov** [comment]
用了最新版，ivp6的ip数嗖地一下就变成2位数了，还在持续下降中

**Comment by yangsl158** [comment]
3.10.6的IPV6的IP数从100往下降到2位数了，还在持续下降。。。
之前是2K+。。

**Comment by nly4lov** [comment]
@yangsl158 我也是啊。用回3.9.2也来不及了，都掉过40以下去了。赶快关掉，用另一个文件夹中的旧版3.8.4，还有2000+个ip，不过观察了一会，貌似也在往下掉

**Comment by imldf** [comment]
3.10.6  爲什麽IP數量減少后感覺很不踏實？

**Comment by xxnet** [comment]
ipv6时代，​100个ip足够了。

确实想要更多ip，可以修改data/gae_proxy/config.json
{
  "max_good_ip_num": 3000
}


Smart Router Config中Rules一栏是否能给一个
Direct List，GAEProxy List，SOCKS List，Redirect HTTPS，Black List
这些格式规范
这个确实需要给的
简单的，比如
  www.baidu.com
如果需要*.baidu.com，就填
*.baidu.com




另外SOCKS List是做什么的？
就是需要走X-Tunnel通道的host列表。
能够保证真实的证书和兼容性。

**Comment by chkjc10** [comment]
max_good_ip_num”：3000这个可以直接添加在文件最后吗

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37153396-8f6f1b76-2317-11e8-8aba-034ee11e1c97.png)

**Comment by chkjc10** [comment]
我的文件GAE_PASSWORD跑到文件第一行了，max_good_ip_num”：3000按你的格式放在后面，为什么改成3000，反而启动不了了

**Comment by gjbg1989** [comment]
😱貌似空格、英文标点等格式不对

**Comment by imldf** [comment]
**IP數量在100的時候延遲經常達到600多，不知道是不是IP太少的原因？
按照提示修改IP數量后，爽多了！**
![001](https://user-images.githubusercontent.com/33856971/37153837-f36ab2a6-2318-11e8-9747-05505eddb745.PNG)
![002](https://user-images.githubusercontent.com/33856971/37153849-fc664744-2318-11e8-9484-9830c551620f.PNG)

**Comment by chkjc10** [comment]
我再试下，不行的话，我就贴图

**Comment by chkjc10** [comment]
![2018-03-08_215344](https://user-images.githubusercontent.com/11959923/37154791-1662f1b2-231c-11e8-9506-b8bbb24ae3c5.png)

**Comment by chkjc10** [comment]
我就在18行添加的，还是不行

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37154919-692ea792-231c-11e8-9939-372c7c0f922b.png)

😱英文标点！英文标点！英文标点！

**Comment by chkjc10** [comment]
哦，我的ID的后面那些他们是自动导入的啊，我没动，也要换成英文标点吗

**Comment by chkjc10** [comment]
![2018-03-08_220119](https://user-images.githubusercontent.com/11959923/37155740-082901ce-231f-11e8-8163-586b3ffcb767.png)

**Comment by chkjc10** [comment]
是用英文模式输入的啊，退出后，还是打不开，去掉第18行，可以打开的

**Comment by gjbg1989** [comment]
貌似至少18行的最后标点是多余的😂

**Comment by chkjc10** [comment]
17行中括号后的逗号需要吗？最后一个id后有没有逗号

**Comment by gjbg1989** [comment]
😱自加的都搞不清，还敢动“自动导入的啊”

**Comment by chkjc10** [comment]
感谢，终于搞定

**Comment by chkjc10** [comment]
其实还是符号有疏忽了，谢谢了

**Comment by xuwanglin** [comment]
3.10.4 好用，3.10.5/6 一更新就不好用了

**Comment by xuwanglin** [comment]
3.10.6 设置成 3000个IP   扫描200线程 很快就会扫描到2000ip数 ，但是通过检查  有效IP  却只有  110个    ip池里  H2 15个    延迟  500   youtube  看不了

**Comment by gjbg1989** [comment]
😱看 youtube ：貌似3.10.4只是开播不正常，需缓冲几秒、暂停再播，后面一直正常
3.10.6开播正常，卡、卡停、卡、卡停。。。

**Comment by nly4lov** [comment]
我youtube一直是只能看240p流畅。再高的都是卡、放、卡、放。。。。

**Comment by nly4lov** [comment]
@xxnet 我那个config.json里只有下面一点点内容：
{
  "max_scan_ip_thread_num": 50, 
  "GAE_APPIDS": [
    "a-song-pac", 
    "orchid-maggie", 
    "yoyo-mylov", 
    "mom-bgud"
  ]
}

**Comment by yxr877431436** [comment]
找不到config.json文件，版本3.10.6

**Comment by myjlpt** [comment]
@xxnet  关于 “智能路由”这块，貌似还需要很多改进。
huanqiu.com ，卡巴BBS等很多类似站点，都卡的打不开，手动直连迅开。

**Comment by nly4lov** [comment]
我觉得3.8.4挺好的，哈哈

**Comment by xxnet** [comment]
​重构变化比较大，参数还需要微调完善。
已更新配置文件说明到wiki
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by xxnet** [comment]
发布 3.10.7 版

根据大家的反馈，微调了相关的参数。
* 默认最高保留500个ip;
* 默认5个扫描线程
* 增加ipv6库

已推送测试版更新

**Comment by imldf** [comment]
爲什麽要減少IP和掃描綫程數量呢？ IP數量少很容易IP全部消耗完。掃描綫程少就變得很慢了。

**Comment by gjbg1989** [comment]
#9944 
😂 貌似 GAE 弱化了，扫描待 h1 达 20 左右，只有 Smart-Router 完全模式正常工作😱

**Comment by nly4lov** [comment]
我昨天就自己改成500和50了![qq 20170822085259](https://user-images.githubusercontent.com/11325411/37235907-adbd11a6-243d-11e8-9e8c-f716065a1a8a.gif)

**Comment by xxnet** [comment]
发布3.10.8
 根据 3.8.4 的参加进行修改，感觉性能有提高。

**Comment by nly4lov** [comment]
@xxnet 我也感觉速度有提高，居然能勉强看720P的油管了

**Comment by yeezylife** [comment]
。。俺一直都能流畅砍720P的油管啊

**Comment by imldf** [comment]
3.10.8和3.10.6兩個版本都會出現連接池突然歸零，導致無法連接的現象。
所以暫時退回3.10.4比較穩定。

**Comment by nly4lov** [comment]
@imldf 对，我现在就已经归零了。

**Comment by xxnet** [comment]
归零时，有没有什么日志异常信息？
贴出来分析

**Comment by nly4lov** [comment]
等我重新用一下它，等到它归零了再复制日志给你

**Comment by nly4lov** [comment]
奇怪从昨天下午到现在它还不归零了啊。

**Comment by gjbg1989** [comment]
异动大且快😱

**Comment by nly4lov** [comment]
@gjbg1989 不明觉厉
