### ISSUE TITLE
xx-net安装后无法打开本地设置页面http://localhost:8085,也不能翻墙。

### ISSUE THREAD

**Issue by fire2013** [XX-net/XX-Net#9928]

**Comment by gjbg1989** [comment]
代理插件添加 127.0.0.1 走直接连接？

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by fire2013** [comment]
走直接链接和代理都不行

**Comment by gjbg1989** [comment]
手动下载、解压覆盖。。。

**Comment by fire2013** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : dormant

xx-net地址打不开

**Comment by fire2013** [comment]
![2018-03-08_192348](https://user-images.githubusercontent.com/3623484/37148682-46816498-2306-11e8-9a57-e95394c31e07.jpg)

**Comment by fire2013** [comment]
我试了下3.10.6版本，重新安装不管用，一样打不开。

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/

**Comment by fire2013** [comment]
一样打不开，不清楚是哪里的问题，原来可以，今天突然不行了。系统也没有做什么修改和升级。

**Comment by gjbg1989** [comment]
检查系统文件 hosts ？

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net/issues/7366

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37149150-f04f6410-2307-11e8-9df2-9663528fd4c5.png)

**Comment by fire2013** [comment]
这些方法我试过了，都不行。。

**Comment by gjbg1989** [comment]
![image](https://user-images.githubusercontent.com/13290970/37149505-3686618a-2309-11e8-94d4-67b124486103.png)

**Comment by gjbg1989** [comment]
啥系统，Win10？检查
![image](https://user-images.githubusercontent.com/13290970/37149728-061bf4a0-230a-11e8-8af3-c28680a43482.png)

**Comment by whiliang** [comment]
是Win10系统吧，前几天系统升级自动打开防火墙了，把防火墙关掉就好了

**Comment by gjbg1989** [comment]
把防火墙关掉😱

**Comment by fire2013** [comment]
今天重装了下xx-net，搞了个3.10.4版本，防火墙啥的都关了，然后就好了。。。
