### ISSUE TITLE
请问scan ip worker exit该怎么解决？

### ISSUE THREAD

**Issue by yinzq** [XX-net/XX-Net#993]
在2.12时尝试配置了一个appid未果，重新下载安装2.12、2.20、2.30、SwitchySharp都无法翻墙了。之前的问题是DEBUG，现在是scan ip worker exit，求助~~
日志：
Sep 12 22:58:45 - [INFO] load ip range file:F:\software\XX-Net-2.2.0\XX-Net-2.2.0\gae_proxy\local\ip_range.txt
Sep 12 22:58:45 - [INFO] load google ip_list num:3000, gws num:3000
Sep 12 22:58:45 - [INFO] SSL use version:TLSv1
Sep 12 22:58:45 - [INFO] ------------------------------------------------------ GAEProxy Version : gae_proxy (python/2.7.9) Listen Address : 127.0.0.1:8087 GAE APPID : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159 Pac Server : http://127.0.0.1:8086/proxy.pac ------------------------------------------------------
Sep 12 22:58:46 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Sep 12 22:58:47 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=34e201f9-7a88-4047-95c6-23aeff7cd25c&version=2.2.0
Sep 12 22:58:47 - [DEBUG] get ip:210.61.221.168 t:180
Sep 12 22:58:47 - [DEBUG] get ip:208.117.236.172 t:521
Sep 12 22:58:47 - [DEBUG] get ip:85.182.250.173 t:534
Sep 12 22:58:47 - [DEBUG] get ip:64.15.116.148 t:541
Sep 12 22:58:47 - [DEBUG] get ip:128.0.169.250 t:554
Sep 12 22:58:53 - [DEBUG] create_ssl 128.0.169.250 fail:timed out cost:2000 h:0
Sep 12 22:58:53 - [DEBUG] create_ssl 64.15.116.148 fail:timed out cost:2001 h:0
Sep 12 22:58:53 - [DEBUG] report_connect_fail network fail
Sep 12 22:58:53 - [DEBUG] create_ssl 85.182.250.173 fail:timed out cost:2000 h:0
Sep 12 22:58:53 - [DEBUG] report_connect_fail network fail
Sep 12 22:58:53 - [DEBUG] create_ssl 208.117.236.172 fail:timed out cost:2002 h:0
Sep 12 22:58:53 - [DEBUG] report_connect_fail network fail
Sep 12 22:58:54 - [DEBUG] get ip:128.0.169.205 t:558
Sep 12 22:58:54 - [DEBUG] get ip:128.0.169.243 t:567
Sep 12 22:58:54 - [DEBUG] get ip:128.0.169.239 t:573
Sep 12 22:58:55 - [DEBUG] create_ssl 210.61.221.168 fail:timed out cost:2002 h:0
Sep 12 22:58:55 - [DEBUG] get ip:128.0.169.230 t:605
Sep 12 22:58:56 - [DEBUG] create_ssl 128.0.169.205 fail:timed out cost:2000 h:0
Sep 12 22:58:56 - [DEBUG] get ip:128.0.169.204 t:611
Sep 12 22:58:56 - [DEBUG] create_ssl 128.0.169.239 fail:timed out cost:2000 h:0
Sep 12 22:58:57 - [DEBUG] get ip:128.0.169.233 t:588
Sep 12 22:58:57 - [DEBUG] create_ssl 128.0.169.230 fail:timed out cost:2001 h:0
Sep 12 22:58:57 - [DEBUG] get ip:208.117.224.157 t:708
Sep 12 22:58:58 - [DEBUG] create_ssl 128.0.169.204 fail:timed out cost:2000 h:0
Sep 12 22:58:58 - [DEBUG]LOG_EXCEPT: get ip:210.153.73.84 t:846, Except:[Errno 9] Bad file descriptor
Sep 12 22:58:59 - [DEBUG] create_ssl 128.0.169.243 fail:timed out cost:2002 h:0
Sep 12 22:58:59 - [DEBUG] create_ssl 128.0.169.233 fail:timed out cost:2000 h:0
Sep 12 22:58:59 - [DEBUG] get ip:84.235.77.251 t:918
Sep 12 22:58:59 - [DEBUG] create_ssl 208.117.224.157 fail:timed out cost:2001 h:0
Sep 12 22:59:00 - [DEBUG] get ip:216.58.213.59 t:918
Sep 12 22:59:00 - [DEBUG] get ip:208.117.236.172 t:521
Sep 12 22:59:00 - [DEBUG] get ip:85.182.250.173 t:534
Sep 12 22:59:01 - [DEBUG] create_ssl update ip:210.153.73.84 time:2000
Sep 12 22:59:01 - [DEBUG] create_ssl 210.153.73.84 fail: certificate is none cost:2799 h:2000
Sep 12 22:59:01 - [DEBUG] create_ssl 84.235.77.251 fail:timed out cost:2000 h:0
Sep 12 22:59:02 - [DEBUG] create_ssl 216.58.213.59 fail:timed out cost:2001 h:0
Sep 12 22:59:02 - [DEBUG] get ip:64.15.116.148 t:541
Sep 12 22:59:02 - [DEBUG] get ip:220.255.5.84 t:918
Sep 12 22:59:02 - [DEBUG] create ssl timeout fail.
Sep 12 22:59:02 - [DEBUG] get ip:41.206.96.213 t:918
Sep 12 22:59:03 - [DEBUG] get ip:118.174.25.103 t:918
Sep 12 22:59:03 - [DEBUG] create_ssl 85.182.250.173 fail:timed out cost:2002 h:0
Sep 12 22:59:04 - [DEBUG] create_ssl 208.117.236.172 fail:timed out cost:2000 h:0
Sep 12 22:59:04 - [DEBUG] GAEProxy Web_control 127.0.0.1:51397 GET /quit
Sep 12 22:59:04 - [INFO] scan_ip_worker exit
Sep 12 22:59:04 - [DEBUG] create_ssl 64.15.116.148 fail:timed out cost:2000 h:0
Sep 12 22:59:04 - [INFO] Exiting gae_proxy module...
Sep 12 22:59:05 - [INFO] Finished Exiting gae_proxy module...
Sep 12 22:59:06 - [DEBUG] create_ssl 118.174.25.103 fail:timed out cost:2000 h:0
Sep 12 22:59:06 - [DEBUG] create_ssl 41.206.96.213 fail:timed out cost:2000 h:0
Sep 12 22:59:06 - [DEBUG] create_ssl 220.255.5.84 fail:timed out cost:2000 h:0
Sep 12 22:59:07 - [INFO] scan_ip_worker exit
Sep 12 22:59:09 - [INFO] scan_ip_worker exit
Sep 12 22:59:10 - [INFO] scan_ip_worker exit
Sep 12 22:59:11 - [INFO] scan_ip_worker exit
Sep 12 22:59:11 - [INFO] scan_ip_worker exit
Sep 12 22:59:12 - [INFO] scan_ip_worker exit
Sep 12 22:59:14 - [INFO] scan_ip_worker exit
Sep 12 22:59:15 - [INFO] scan_ip_worker exit
Sep 12 22:59:16 - [INFO] scan_ip_worker exit
Sep 12 22:59:16 - [INFO] scan_ip_worker exit
Sep 12 22:59:17 - [INFO] scan_ip_worker exit
Sep 12 22:59:17 - [DEBUG] create ssl timeout fail.
Sep 12 22:59:19 - [INFO] scan_ip_worker exit
Sep 12 22:59:20 - [INFO] scan_ip_worker exit
Sep 12 22:59:21 - [INFO] scan_ip_worker exit
Sep 12 22:59:21 - [INFO] scan_ip_worker exit
Sep 12 22:59:21 - [INFO] scan_ip_worker exit
Sep 12 22:59:22 - [INFO] scan_ip_worker exit
Sep 12 22:59:25 - [INFO] scan_ip_worker exit
Sep 12 22:59:26 - [INFO] scan_ip_worker exit

**Comment by wenliyang** [comment]
把旧版本删除，保留配置文件（data文件夹就是），再试新版本

**Comment by xxnet** [comment]
有另一个xx-Net在启动，出发这个XX-Net退出？

2015-09-13 7:19 GMT+08:00 wenliyang <notifications@github.com>:

**Comment by yinzq** [comment]
更新了2.40，仍然上不了T.T。求助~~
有时候点击START会提示无法访问windows smartscreen。之前在WIN10下使用是顺畅的...

Sep 16 21:56:02 - [INFO] detect Win10, enable connect concurent control, interval:40
Sep 16 21:56:02 - [INFO] load ip range file:F:\software\XX-Net-2.4.0\XX-Net-2.4.0\gae_proxy\local\ip_range.txt
Sep 16 21:56:02 - [INFO] load google ip_list num:3000, gws num:3000
Sep 16 21:56:02 - [INFO] SSL use version:TLSv1
Sep 16 21:56:03 - [INFO] ------------------------------------------------------
Sep 16 21:56:03 - [INFO] Python Version : 2.7.9
Sep 16 21:56:03 - [INFO] Listen Address : 127.0.0.1:8087
Sep 16 21:56:03 - [INFO] GAE APPID : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Sep 16 21:56:03 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Sep 16 21:56:03 - [INFO] ------------------------------------------------------
Sep 16 21:56:03 - [INFO] no CA file exist
Sep 16 21:56:03 - [INFO] clean old site certs
Sep 16 21:56:03 - [INFO] generate CA file:F:\software\XX-Net-2.4.0\XX-Net-2.4.0\data\gae_proxy\CA.crt
Sep 16 21:56:03 - [INFO] create ca
Sep 16 21:56:08 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Sep 16 21:56:09 - [DEBUG] get ip:210.61.221.168 t:180
Sep 16 21:56:09 - [DEBUG] get ip:208.117.236.172 t:521
Sep 16 21:56:09 - [DEBUG] get ip:85.182.250.173 t:534
Sep 16 21:56:09 - [DEBUG] get ip:64.15.116.148 t:541
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.250 t:554
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.205 t:558
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.243 t:567
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.239 t:573
Sep 16 21:56:09 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=3cbf1ee8-17a8-4595-90e6-026ce2072db8&version=2.4.0
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.233 t:588
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.230 t:605
Sep 16 21:56:09 - [DEBUG] get ip:128.0.169.204 t:611
Sep 16 21:56:13 - [DEBUG] 210.61.221.168 fail
Sep 16 21:56:13 - [DEBUG] 208.117.236.172 fail
Sep 16 21:56:13 - [DEBUG] get ip:208.117.224.157 t:708
Sep 16 21:56:13 - [DEBUG] 85.182.250.173 fail
Sep 16 21:56:17 - [DEBUG] 208.117.224.157 fail
Sep 16 21:56:17 - [DEBUG] 128.0.169.204 fail
Sep 16 21:56:17 - [DEBUG]LOG_EXCEPT: 128.0.169.230 fail, Except:[Errno 9] Bad file descriptor
Sep 16 21:56:17 - [DEBUG] 128.0.169.233 fail
Sep 16 21:56:18 - [DEBUG] 128.0.169.239 fail
Sep 16 21:56:18 - [DEBUG] 128.0.169.243 fail
Sep 16 21:56:18 - [DEBUG] 128.0.169.205 fail
Sep 16 21:56:18 - [DEBUG] 128.0.169.250 fail
Sep 16 21:56:18 - [DEBUG] 64.15.116.148 fail
Sep 16 21:56:18 - [DEBUG] get ip:210.153.73.84 t:846
Sep 16 21:56:18 - [DEBUG] get ip:84.235.77.251 t:918
Sep 16 21:56:18 - [DEBUG] get ip:216.58.213.59 t:918
Sep 16 21:56:18 - [DEBUG] get ip:220.255.5.84 t:918
Sep 16 21:56:18 - [DEBUG] get ip:41.206.96.213 t:918
Sep 16 21:56:18 - [DEBUG] get ip:118.174.25.103 t:918
Sep 16 21:56:18 - [DEBUG] get ip:94.40.70.53 t:918
Sep 16 21:56:18 - [DEBUG] get ip:208.117.224.179 t:918
Sep 16 21:56:18 - [DEBUG] get ip:64.233.181.19 t:918
Sep 16 21:56:19 - [DEBUG] get ip:64.15.116.184 t:918
Sep 16 21:56:19 - [DEBUG] get ip:82.135.118.47 t:918
Sep 16 21:56:22 - [DEBUG] 210.153.73.84 fail
Sep 16 21:56:22 - [DEBUG] get ip:31.7.160.223 t:918
Sep 16 21:56:24 - [DEBUG] 82.135.118.47 fail
Sep 16 21:56:24 - [DEBUG] 64.15.116.184 fail
Sep 16 21:56:24 - [DEBUG] create ssl timeout fail.
Sep 16 21:56:24 - [DEBUG] get ip:64.15.116.52 t:926
Sep 16 21:56:26 - [DEBUG] 31.7.160.223 fail
Sep 16 21:56:26 - [DEBUG] 64.233.181.19 fail
Sep 16 21:56:26 - [DEBUG] 208.117.224.179 fail
Sep 16 21:56:27 - [DEBUG] 94.40.70.53 fail
Sep 16 21:56:27 - [DEBUG] 118.174.25.103 fail
Sep 16 21:56:27 - [DEBUG] 41.206.96.213 fail
Sep 16 21:56:27 - [DEBUG] 220.255.5.84 fail
Sep 16 21:56:27 - [DEBUG] get ip:84.235.77.251 t:918
Sep 16 21:56:27 - [DEBUG] get ip:216.58.213.59 t:918
Sep 16 21:56:27 - [DEBUG] get ip:202.39.143.104 t:918
Sep 16 21:56:27 - [DEBUG] get ip:61.219.131.103 t:918
Sep 16 21:56:27 - [DEBUG] get ip:203.117.35.152 t:926
Sep 16 21:56:27 - [DEBUG] get ip:216.58.223.36 t:926
Sep 16 21:56:27 - [DEBUG] get ip:208.117.238.240 t:926
Sep 16 21:56:28 - [DEBUG] get ip:118.174.25.157 t:926
Sep 16 21:56:28 - [DEBUG] 64.15.116.52 fail
Sep 16 21:56:29 - [DEBUG] get ip:64.233.189.143 t:926
Sep 16 21:56:30 - [DEBUG] 84.235.77.251 fail
Sep 16 21:56:30 - [DEBUG] get ip:74.125.102.151 t:927
Sep 16 21:56:31 - [DEBUG] 84.235.77.251 fail
Sep 16 21:56:31 - [DEBUG] get ip:194.78.99.157 t:927
Sep 16 21:56:32 - [DEBUG] 118.174.25.157 fail
Sep 16 21:56:32 - [DEBUG] get ip:64.233.167.114 t:927
Sep 16 21:56:32 - [DEBUG] 208.117.238.240 fail
Sep 16 21:56:33 - [DEBUG] 64.233.189.143 fail
Sep 16 21:56:33 - [DEBUG] get ip:210.61.221.187 t:927
Sep 16 21:56:34 - [DEBUG] 74.125.102.151 fail
Sep 16 21:56:34 - [DEBUG] get ip:118.174.27.25 t:927
Sep 16 21:56:34 - [DEBUG] create_ssl update ip:216.58.213.59 time:8000
Sep 16 21:56:34 - [DEBUG] 216.58.213.59 fail
Sep 16 21:56:34 - [DEBUG] get ip:95.143.84.166 t:927
Sep 16 21:56:35 - [DEBUG] 216.58.223.36 fail
Sep 16 21:56:35 - [DEBUG] 194.78.99.157 fail
Sep 16 21:56:36 - [DEBUG] 203.117.35.152 fail
Sep 16 21:56:36 - [DEBUG] 61.219.131.103 fail
Sep 16 21:56:36 - [DEBUG] 202.39.143.104 fail
Sep 16 21:56:36 - [DEBUG] 64.233.167.114 fail
Sep 16 21:56:37 - [DEBUG] 210.61.221.187 fail
Sep 16 21:56:38 - [DEBUG] 118.174.27.25 fail
Sep 16 21:56:38 - [DEBUG] 95.143.84.166 fail
Sep 16 21:56:38 - [DEBUG] get ip:121.78.74.113 t:927
Sep 16 21:56:39 - [DEBUG] get ip:64.233.167.148 t:927
Sep 16 21:56:39 - [DEBUG] 216.58.213.59 fail
Sep 16 21:56:39 - [DEBUG] get ip:203.117.35.162 t:927
Sep 16 21:56:39 - [DEBUG] get ip:64.233.191.90 t:927
Sep 16 21:56:39 - [DEBUG] get ip:203.66.124.217 t:927
Sep 16 21:56:39 - [DEBUG] create ssl timeout fail.
Sep 16 21:56:39 - [DEBUG] get ip:118.174.27.173 t:927
Sep 16 21:56:39 - [DEBUG] get ip:118.174.27.172 t:927
Sep 16 21:56:39 - [DEBUG] get ip:85.182.250.46 t:927
Sep 16 21:56:40 - [DEBUG] get ip:64.233.183.117 t:927
Sep 16 21:56:40 - [DEBUG] get ip:61.19.1.226 t:927
Sep 16 21:56:40 - [DEBUG] get ip:208.117.251.183 t:928
Sep 16 21:56:42 - [DEBUG] 121.78.74.113 fail
Sep 16 21:56:43 - [DEBUG]LOG_EXCEPT: 203.117.35.162 fail, Except:[Errno 9] Bad file descriptor
Sep 16 21:56:43 - [DEBUG] get ip:209.85.229.51 t:928
Sep 16 21:56:43 - [DEBUG] 85.182.250.46 fail
Sep 16 21:56:43 - [DEBUG] get ip:173.194.137.150 t:928
Sep 16 21:56:43 - [DEBUG] get ip:61.219.131.98 t:928
Sep 16 21:56:45 - [DEBUG] 208.117.251.183 fail
Sep 16 21:56:46 - [DEBUG] 61.19.1.226 fail
Sep 16 21:56:46 - [DEBUG] 64.233.183.117 fail
Sep 16 21:56:46 - [DEBUG] 118.174.27.172 fail
Sep 16 21:56:47 - [DEBUG] 118.174.27.173 fail
Sep 16 21:56:47 - [DEBUG] 203.66.124.217 fail
Sep 16 21:56:47 - [DEBUG] 64.233.191.90 fail
Sep 16 21:56:47 - [DEBUG] 209.85.229.51 fail
Sep 16 21:56:47 - [DEBUG] 173.194.137.150 fail
Sep 16 21:56:47 - [DEBUG] get ip:64.233.167.148 t:927
Sep 16 21:56:49 - [DEBUG] get ip:83.94.121.221 t:928
Sep 16 21:56:49 - [DEBUG] get ip:210.158.146.85 t:928
Sep 16 21:56:49 - [DEBUG] get ip:66.185.84.168 t:928
Sep 16 21:56:49 - [DEBUG] get ip:208.117.224.144 t:928
Sep 16 21:56:49 - [DEBUG] get ip:24.156.131.25 t:928
Sep 16 21:56:49 - [DEBUG] get ip:83.94.121.251 t:928
Sep 16 21:56:49 - [DEBUG] get ip:64.233.178.103 t:928
Sep 16 21:56:49 - [DEBUG] get ip:202.39.143.20 t:928
Sep 16 21:56:50 - [DEBUG] 61.219.131.98 fail
Sep 16 21:56:50 - [DEBUG] 64.233.167.148 fail
Sep 16 21:56:51 - [DEBUG] get ip:203.66.124.221 t:928
Sep 16 21:56:51 - [DEBUG] get ip:213.240.44.27 t:928
Sep 16 21:56:51 - [DEBUG] 64.233.167.148 fail
Sep 16 21:56:52 - [DEBUG] get ip:85.182.250.39 t:928
Sep 16 21:56:53 - [DEBUG] 83.94.121.221 fail
Sep 16 21:56:53 - [DEBUG] get ip:64.233.183.17 t:928
Sep 16 21:56:54 - [DEBUG] 202.39.143.20 fail
Sep 16 21:56:54 - [DEBUG] get ip:208.117.224.250 t:928
Sep 16 21:56:54 - [DEBUG] 64.233.178.103 fail
Sep 16 21:56:55 - [DEBUG] 203.66.124.221 fail
Sep 16 21:56:56 - [DEBUG] 213.240.44.27 fail
Sep 16 21:56:56 - [DEBUG] 83.94.121.251 fail
Sep 16 21:56:56 - [DEBUG] 24.156.131.25 fail
Sep 16 21:56:56 - [DEBUG] 208.117.224.144 fail
Sep 16 21:56:56 - [DEBUG] 66.185.84.168 fail
Sep 16 21:56:56 - [DEBUG] 210.158.146.85 fail
Sep 16 21:56:56 - [DEBUG] 85.182.250.39 fail
Sep 16 21:56:57 - [DEBUG] get ip:62.0.54.89 t:928
Sep 16 21:56:57 - [DEBUG] 64.233.183.17 fail
Sep 16 21:56:57 - [DEBUG] get ip:103.25.178.27 t:928
Sep 16 21:56:58 - [DEBUG] 208.117.224.250 fail
Sep 16 21:57:00 - [DEBUG] get ip:202.39.143.93 t:928
Sep 16 21:57:00 - [DEBUG] get ip:128.0.86.213 t:930
Sep 16 21:57:00 - [DEBUG] get ip:173.194.138.180 t:930
Sep 16 21:57:00 - [DEBUG] get ip:24.156.131.99 t:930
Sep 16 21:57:00 - [DEBUG] get ip:106.162.216.98 t:930
Sep 16 21:57:00 - [DEBUG] get ip:208.117.251.136 t:930
Sep 16 21:57:00 - [DEBUG] get ip:193.192.226.160 t:930
Sep 16 21:57:00 - [DEBUG] get ip:41.201.128.23 t:930
Sep 16 21:57:00 - [DEBUG] get ip:210.245.14.218 t:930
Sep 16 21:57:01 - [DEBUG] 62.0.54.89 fail
Sep 16 21:57:01 - [DEBUG] 103.25.178.27 fail
Sep 16 21:57:02 - [DEBUG] get ip:84.235.58.83 t:931
Sep 16 21:57:02 - [DEBUG] get ip:208.117.231.135 t:931
Sep 16 21:57:04 - [DEBUG] 202.39.143.93 fail
Sep 16 21:57:04 - [DEBUG] get ip:208.117.242.162 t:931
Sep 16 21:57:05 - [DEBUG] 210.245.14.218 fail
Sep 16 21:57:05 - [DEBUG] get ip:1.179.251.84 t:931
Sep 16 21:57:05 - [DEBUG] 41.201.128.23 fail
Sep 16 21:57:05 - [DEBUG] 193.192.226.160 fail
Sep 16 21:57:05 - [DEBUG] 208.117.251.136 fail
Sep 16 21:57:05 - [DEBUG] 106.162.216.98 fail
Sep 16 21:57:05 - [DEBUG] 24.156.131.99 fail
Sep 16 21:57:06 - [DEBUG] 173.194.138.180 fail
Sep 16 21:57:08 - [DEBUG] 208.117.242.162 fail
Sep 16 21:57:09 - [DEBUG] 208.117.231.135 fail
Sep 16 21:57:09 - [DEBUG] 1.179.251.84 fail
Sep 16 21:57:09 - [DEBUG] 84.235.58.83 fail
Sep 16 21:57:09 - [DEBUG] 128.0.86.213 fail
Sep 16 21:57:10 - [DEBUG] get ip:173.194.195.147 t:931
Sep 16 21:57:10 - [DEBUG] get ip:220.255.6.30 t:931
Sep 16 21:57:10 - [DEBUG] get ip:209.85.228.14 t:931
Sep 16 21:57:10 - [DEBUG] get ip:118.174.25.236 t:931
Sep 16 21:57:10 - [DEBUG] get ip:121.78.74.112 t:931
Sep 16 21:57:10 - [DEBUG] get ip:118.174.25.123 t:931
Sep 16 21:57:10 - [DEBUG] get ip:118.174.27.59 t:931
Sep 16 21:57:10 - [DEBUG] get ip:203.165.13.251 t:931
Sep 16 21:57:10 - [DEBUG] get ip:74.125.100.48 t:931
Sep 16 21:57:10 - [DEBUG]LOG_EXCEPT: get ip:1.179.248.59 t:931, Except:[Errno 9] Bad file descriptor
Sep 16 21:57:10 - [DEBUG] get ip:202.86.162.25 t:931
Sep 16 21:57:14 - [DEBUG] 202.86.162.25 fail
Sep 16 21:57:15 - [DEBUG] 1.179.248.59 fail
Sep 16 21:57:15 - [DEBUG] 74.125.100.48 fail

**Comment by yinzq** [comment]
已解决。
之前的问题是在没有“部署”appid的情况下，无意中“配置”了一个appid，后来虽然清空配置仍无法连接，因为着急便开了多个不同版本的xx-net。
wenliyang的方法可以有效解决scan ip worker问题，但仍不能解决失联问题。
解决方法是把“状态”中APPID下所有的working appid复制一遍，黏贴到“配置”的gae appid中，便可顺利翻墙。
