### ISSUE TITLE
在linux下无法监听全部IP地址

### ISSUE THREAD

**Issue by hzexe** [XX-net/XX-Net#9939]
XX-Net Status:

sys-platform: mips, Linux-3.4.113-mips-with-libc0
os-system: Linux
os-version: #10 Mon Sep 18 23:43:27 CST 2017
os-release: 3.4.113
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
xxnet-version: 3.10.6
python-version: 2.7.12
openssl-version: 17.3.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:100 ipv4:0 ipv6:41
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 2
ip-quality: 634
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

---------------------------------------------------------------------------
准备是全部走IPV6做局域网代理,希望能监听0.0.0.0地址,当前只能监听127.0.0.1
已分别试过以下方法:
data\gae_proxy\manual.ini
data\gae_proxy\proxy.ini
code\default\gae_proxy\local\manual.ini

内添加:
[listen]
ip = 0.0.0.0
port = 8087
都无法生效(之前在windows下可以工作).

另外已尝试过/opt/XX-Net/data/launcher/config.yaml
gae_proxy: {**allow_remote_connect: 1**, auto_start: 1, show_detail: 1}
内添加allow_remote_connect: 1,仍然无效...

[RT-N14U /opt/XX-Net]# netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:30605           0.0.0.0:*               LISTEN      551/miniupnpd
tcp        0      0 0.0.0.0:8085            0.0.0.0:*               LISTEN      16689/python
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      1749/dnsmasq
tcp        0      0 192.168.123.1:53        0.0.0.0:*               LISTEN      1749/dnsmasq
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      16689/python
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      547/dropbear
**tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN      16689/python**
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      15586/koolproxy
tcp        0      0 :::80                   :::*                    LISTEN      532/httpd
tcp        0      0 ::1:53                  :::*                    LISTEN      1749/dnsmasq
tcp        0      0 2001:470:1f09:2ba:::53  :::*                    LISTEN      1749/dnsmasq
tcp        0      0 fe80::20c:43ff:fe76:20c0:53 :::*                    LISTEN      1749/dnsmasq
tcp        0      0 :::22                   :::*                    LISTEN      547/dropbear

proxy监听的地址仍然是127.0.0.1上.

之前用这些方法设置通过.仍而现在不工作了....希望帮看看原因

**Comment by SeaHOH** [comment]
需要传递命令行参数
https://github.com/XX-net/XX-Net/blob/5289372f7cdcc4303ec6e2c06fec1d2bba9924a4/code/default/launcher/start.py#L199-L205

**Comment by SeaHOH** [comment]
改 config.json 好像也行

**Comment by xxnet** [comment]
​可以参考这里：
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by hzexe** [comment]
谢谢, @SeaHOH 搞定.
感谢作者 @xxnet 的wiki.
