### ISSUE TITLE
使用SwitchyOmega插件的话具体应该怎么设置

### ISSUE THREAD

**Issue by xman5j** [XX-net/XX-Net#9942]
是否应取消全局代理？
SwitchyOmega里具体应该如何设置呢？是否需要导入在线规则列表？
不好意思试了几次实在是设置不好SwitchyOmega。

**Comment by gjbg1989** [comment]
取消全局代理，由 SwitchyOmega 控制
导入 XX-Net 下 SwitchyOmega 目录内的 bak
