### ISSUE TITLE
手动更新3.10.7后无法访问GITHUB

### ISSUE THREAD

**Issue by AnLvNing** [XX-net/XX-Net#9943]
今天手动更新3.10.7，用的SMARTROUTER，打开GITHUB主页显示
600:gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/gae_exception:"600:unpack protocol:ValueError('cannot modify size of memoryview object',)" https://github.com/

用直连可以访问

**Comment by gjbg1989** [comment]
GAE 自动切换时，FireFox 可以，Chrome 不可以 😱

**Comment by AnLvNing** [comment]
@gjbg1989 刚才试了试，GAE自动切换可以，好像就SMARTROUTER不能访问

**Comment by gjbg1989** [comment]
😂 貌似 GAE 弱化了，扫描待 h1 达 20 左右，Smart-Router 模式正常工作😱

**Comment by gjbg1989** [comment]
#9944

**Comment by AnLvNing** [comment]
对了，那个id加密码有什么用，还有怎么加密码呢

**Comment by fengzean** [comment]
不用代理，直接连接啊
