### ISSUE TITLE
求助  w10 IPv6协议 前面的勾无法去掉，有人碰到这种问题吗？

### ISSUE THREAD

**Issue by gzc07** [XX-net/XX-Net#9956]
求助  w10 IPv6协议 前面的勾无法去掉，有人碰到这种问题吗？

![11](https://user-images.githubusercontent.com/32999734/37252083-33aa397e-2556-11e8-84a6-ac3d119fc120.png)

![image](https://user-images.githubusercontent.com/32999734/37252100-643a53b2-2556-11e8-96de-7612500b717e.png)

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:6000 ipv4:0 ipv6:2190
ipv4-status: Fail
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 242
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by gjbg1989** [comment]
至少有线网络没有必要取消勾选 IPv6 协议
ipv4-status: Fail——😱
ipv6-status: Fail
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）

**Comment by gzc07** [comment]
你好，我的是连wifi的，之前是可以，w10更新重启后就不行了

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/37292213-696992bc-264b-11e8-8f0b-031d3d4a709f.png)

**Comment by gjbg1989** [comment]
准备好网卡驱动，删除网卡再安装网卡？

**Comment by gzc07** [comment]
ok
