### ISSUE TITLE
[无伤大雅]64位系统下，“状态信息”中Sys Platform检测为win32

### ISSUE THREAD

**Issue by simonasd** [XX-net/XX-Net#996]
今天在一台64位win7的电脑上意外看到，”状态信息“中Sys Platform显示的是win32.不知道是不是这边对应的检测代码有问题。

**Comment by gc12345** [comment]
同上

**Comment by xxnet** [comment]
win32 不是 32位系统，而是MS windows系列， 下面的Arch 有32/64的信息

2015-09-13 11:50 GMT+08:00 gc12345 <notifications@github.com>:

**Comment by matrixirtam** [comment]
Win 10 pro 64bit 显示如下
architecture	32bit,WindowsPE

**Comment by aOJzQT** [comment]
This string contains a platform identifier that can be used to append platform-specific components to sys.path, for instance.

For other systems, the values are:

System |platform value 
----------|------------------
Linux (2.x and 3.x) | 'linux2' 
Windows | 'win32' 
Windows/Cygwin | 'cygwin' 
Mac OS X | 'darwin' 
OS/2 | 'os2' 
OS/2 EMX | 'os2emx' 
RiscOS | 'riscos' 
AtheOS | 'atheos'
