### ISSUE TITLE
roundtrip time:25087 transfer_no:3889 send:1475 status:602

### ISSUE THREAD

**Issue by hydra1024** [XX-net/XX-Net#9971]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：
X-tunnel 3月11日下午开始无法登陆和使用，roundtrip time:25087 transfer_no:3889 send:1475 status:602
偶尔会短时间正常一会

* 做过哪些尝试：
重启电脑，重新下载XX.NET

* 请贴出对应模块的状态页
![1](https://user-images.githubusercontent.com/37279795/37261607-dd57b5e6-25d8-11e8-8f45-5c9dbc64e49e.jpg)
![2](https://user-images.githubusercontent.com/37279795/37261621-f558d12a-25d8-11e8-9fb5-d25a6f4bf4e5.jpg)

XX-Net Status:

sys-platform: AMD64, Windows-8.1-6.3.9600
os-system: Windows
os-version: 6.3.9600
os-release: 8.1
os-detail: Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

* 请贴出相关的日志

![3](https://user-images.githubusercontent.com/37279795/37261624-f9252056-25d8-11e8-8f1a-c0ed0d8cd974.jpg)

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
大佬云，正常的 GAE 有助于 X-TUNNEL
use-ipv6: auto —— 改为只用 ipv6
scan-ip-thread-num: 10 ——增大到2-10倍
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂（非校园）经验（至3.10.4版）
